### ISSUE TITLE
ARMv7 secure monitor code sm_a32.S Question

### ISSUE THREAD

**Issue by acy54321** [OP-TEE/optee_os#1000]
In 2.0.0 OPTEE release Linux kernel driver change to use Generic driver in linux v4.5. In Generic driver use SMCC interface to OPTEE, but I have some problem in ARMv8 ATF have modify "pass r0-r6 as part of smc param https://github.com/ARM-software/arm-trusted-firmware/commit/56a6412de86537d3445e36a5a81f515fa2c683a7" , In ARMv7 sm_a32.S continued use r0-r3 to pass  param. I guess on ARMv7 architecture use new Generic driver to run OPTEE will cause some 
problem.

Generic driver : 
drivers/tee/optee/core.c
invoke_fn(OPTEE_SMC_CALLS_UID, 0, 0, 0, 0, 0, 0, 0, &res);

res will not return by ARMv7 OPTEE

**Comment by jenswi-linaro** [comment]
Those registers (and more) where already passed in the ARMv7 `sm_a32.S`, see below `.smc_ret_to_sec:`. r4-r11 are passed as is, even if r4-12 are saved to be restored later when returning to normal world.

We're using the generic driver on ARMv7 and it works well.

**Comment by acy54321** [comment]
I look sm_a32.S in .smc_ret_to_nsec will use ldm>r0!, {r4-r12} restore r4~r12 register from nsec_ctx, in .smc_exit will pop>{r0-r3} to restore TEE param  pass to REE.

but in invoke_fn(OPTEE_SMC_CALLS_UID, 0, 0, 0, 0, 0, 0, 0, &res) example , It look have to get result from "res" param, If in above flow, Whether will get correct data from TEE ??

**Comment by jenswi-linaro** [comment]
Yes, it will get correct data from TEE, note that res of this type:
```
struct arm_smccc_res {
        unsigned long a0;
        unsigned long a1;
        unsigned long a2;
        unsigned long a3;
};
```

Only r0-r3 are updated on return as required by the ARM SMC Calling Convention.

**Comment by acy54321** [comment]
OK understanding, 
Thanks for support
