### ISSUE TITLE
OPTEE initcall Question

### ISSUE THREAD

**Issue by acy54321** [OP-TEE/optee_os#1001]
In OPTEE OS use initcall  mechanisms to init some function in the system up. And divided initcall to two level "service_init" and "driver_init", "service_init" will early then "driver_init".
But I have a confused in
core/tee/tee_fs_key_manager.c:service_init(tee_fs_init_key_manager);
core/tee/tee_cryp_utl.c:service_init(tee_cryp_init);

tee_fs_init_key_manager will use crypto_ops to generate some key, but in initcall tee_fs_init_key_manager and tee_cryp_init in same initcall level, compiler how to guarantee tee_cryp_init will execute before tee_fs_init_key_manager. If tee_cryp_init not execute before tee_fs_init_key_manager, I guess will some problem in running

**Comment by jenswi-linaro** [comment]
I agree, this look like a problem.

**Comment by jforissier** [comment]
Indeed we can't rely on any specific order within one initcall level. Perhaps the FS initialization stuff should simply be switched to the "driver" level, i.e., do `driver_init(tee_fs_init_key_manager);`. The only downside I see is that it does not sound good, I mean FS key manager is more a "service" than a "driver" since it's not driving hardware, so it would be a bit misleading.

**Comment by jenswi-linaro** [comment]
We could introduce priority levels in services and drivers, this could be done with zero overhead. It's perhaps not a perfectly scalable solution, but it's easy to implement.

**Comment by jforissier** [comment]
@jenswi-linaro yeah that could be useful. Driver vs. service would hopefully be enough for most cases then the priority would allow to sort out special cases.

**Comment by jenswi-linaro** [comment]
OK, I'll make a proposal.

**Comment by jenswi-linaro** [comment]
Problem should be solved on master now as #1002 was merged.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
