### ISSUE TITLE
[Secure Storage]Is there any plan for the secure storage future work?

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#1007]
The futrue work in documentation/secure_storage.md:
1)TA storage space isolation.
2)TEE file renaming attack detection.
Is there any plan for it? Please share, thanks.

For TA  isolation,  I want to generate FEK with TA UUID. FEK = HMAC(PRNG, UUID). Is it OK?
For renaming attack, if calculate TAG with file name, all operation about rename should calculate again, it seem conflict to current implement and it is hard to keep it atomic. 

Please help me and give me some advise, thanks.

**Comment by jforissier** [comment]
Hi @airbak,

Regarding your first question: please check this commit: https://github.com/OP-TEE/optee_os/commit/fde4a756bfc8 (it was pushed to the master branch 20 days ago). I think it addresses the issue. There is also a new test case to validate the protection: https://github.com/OP-TEE/optee_test/commit/e3854167c8e9.

As for the TEE file renaming scenario: I think your proposal to keep a tag in the meta-data is good. I suggest to use a secure hash of the filename. It is true that one needs to be careful about making the update atomic. It should be relatively easy to do if you use the new SQL FS (https://github.com/OP-TEE/optee_os/commit/2ef14de19093) which is still work in progress... And a bit more complex with the default REE FS, but still doable IMO.

**Comment by airbak** [comment]
I'm sorry for I have not updated the code to latest.  The commit fde4a75 and e385416 are very good. Thanks for your reply.

I think even though using a secure hash of the filename, it can not avoid the attack that copy the meta and block files from file_A to file_B. SQL FS may be doable, but do you have other suggest for file isolation ?

**Comment by jforissier** [comment]
One could in theory add a hash of the file name to each meta and data block, but then to rename the file you would have to rewrite the whole meta and data.
