### ISSUE TITLE
Can i use CA in kernel space (TEE OS 2.1)??

### ISSUE THREAD

**Issue by cloudnew** [OP-TEE/optee_os#1010]
Hi !!  I have one question in TEE OS2.1 , 
When I use TEE OS1.4 , I can find function (EX: TEEC_InitializeContext , TEEC_OpenSession .....  in optee_linuxdriver) , so i  can creat CA in kernel space ,but TEE OS 2.1 , I can't find the same function ,
Do you have any function can  achieve this goal ?thank you for your help!!!!!!!!!

**Comment by jbech-linaro** [comment]
Hi @cloudnew , this was answered just a couple of days ago in https://github.com/OP-TEE/optee_os/issues/979. So please have a look there.

**Comment by cloudnew** [comment]
Thank you very much ~~!!! I will check this item~~
