### ISSUE TITLE
[static TA] Does it allowed to use TEE_XXX APIs under the directory of libutee ?

### ISSUE THREAD

**Issue by bradlin** [OP-TEE/optee_os#1011]
Hi,

I have a "normal TA" and I try to change it to a "static TA". 

I use some APIs under the directory of libutee (for example, TEE_OpenPersistentObject) to operate secure storage, but this library is not linked in "static TA" with deafult sub.mk in core/arch/arm/sta.
The error message is "undefined reference to `TEE_OpenPersistentObject' ".

I think I can try to link the libutee.a to resolve this issue.
I do not see the sample code in core/arch/arm/sta use these APIs.
Do you think that violate your architecture?

Thanks a lot.

**Comment by jenswi-linaro** [comment]
The GP API isn't available for static TAs. The only thing in common between static TAs and user (normal) TAs is that they are invoked by the client in the same way.

**Comment by bradlin** [comment]
Hi,
Thank you.  I can keep my implementation as the user TA.
One more question:
In the future, you will plan to add support for this or just keep current status?
Thanks a lot.

**Comment by jenswi-linaro** [comment]
There's no plans to make GP API available for static TAs.

**Comment by bradlin** [comment]
Thank you.
