### ISSUE TITLE
Using Kernel Privilege in TA

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#1016]
Hi,

I'm wondering is there a method for me to call the function `get_core_pos` of `/core/arch/arm/include/kernel/misc.h` in a TA? I think this method requires kernel privilege while the TA only runs with user level.

One possible solution I think is adding a syscall for this purpose. 
However, I don't find any syscall table such as `/arch/arm/kernel/calls.S` within the OPTEE project.
In this case I also want to know is that possible to add a syscall for OPTEE-OS?

Thank you very much.

**Comment by jforissier** [comment]
Indeed, MPIDR is not accessible from EL0.
The syscall table is in https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/tee/arch_svc.c.
I'm not sure the information you will get this way will be meaningful, because AFAIK your TA may be scheduled on a different core at any time.

**Comment by jbech-linaro** [comment]
Indeed it's easy to add a syscall and we've done so a couple of times, but we try to avoid add new syscalls and instead try to do it in another way. Also Jerome is right, you can end up on any core, so without knowing the use case I think it's probably not that useful to be able to get the current core running.

**Comment by SimonWan** [comment]
@jforissier Thank you for sharing the table. Is there any more details about why or how the TA would be reschedule during it runs?

**Comment by SimonWan** [comment]
By the way, yesterday I also fought some materials about static TA. So I'm wondering if I implement a static TA, does it also have the kernel privilege? Could the static TA run `get_core_pos`?

**Comment by jforissier** [comment]
I'm thinking interrupts will cause OP-TEE to return to normal world to have them handled. @jenswi-linaro can you confirm?
Static TAs do run inside the TEE at EL1 (kernel mode) so `get_core_pos()` can be used. Note however that the usual API used by TAs, that is, the _GP TEE Internal Core API v1.1_, can *not* be used by a static TA.

**Comment by jenswi-linaro** [comment]
@jforissier, yes that's how TAs are rescheduled. That can happen in kernel mode too as long as IRQs aren't masked which they usually aren't.

**Comment by SimonWan** [comment]
@jforissier  Sorry I have another question. When you mention GP TEE can not be used by a static TA, you mean I cannot call a static TA from CA like calling a dynamic TA?

Also, can I call a static TA's function from dynamic TA? Is there any example I can look for?

Thank you so much for your help.

**Comment by jforissier** [comment]
@SimonWan no, that's not what I meant. The static TA can be called by a CA exactly like a dynamic TA. I wanted to point out that you cannot simply re-use code written for a dynamic TA and compile it as a static TA. Because static TA cannot use the TEE Internal Core API functions: `TEE_*()`.

**Comment by Matheus-Garbelini** [comment]
@jforissier I'd need for my TA to access the performance counter directly using asm directive. would the TAbe able to access the mrs register?

**Comment by igoropaniuk** [comment]
@Matheus-Garbelini 
It's possible to enable access to PMUs from EL0 (https://github.com/linaro-swg/linux/blob/optee/drivers/tee/optee/bench.c#L71), but the actual configuration of PMUs should be done from EL1 (EL1/S-EL1). 

However, as each CPU core has it's own performance counter, it's possible that you face the same behavior when TA is rescheduled on a different core, which @jforissier already explained.

**Comment by Xinyao90** [comment]
@igoropaniuk  How to configure PMUs from EL1 (EL1/S-EL1)? Which file do you mean? 
I want to measure function TEEC_InvokeComman() using perf_syscall in main.c The idea is If I made changes in TA called function, then the PMU value will be changed. The original code is from
https://github.com/linaro-swg/optee_examples/blob/master/hello_world/host/main.c 

    ioctl(fd, PERF_EVENT_IOC_RESET, 0);
    ioctl(fd, PERF_EVENT_IOC_ENABLE, 0);
    res = TEEC_InvokeCommand(&sess, TA_HELLO_WORLD_CMD_DEC_VALUE, &op,
                             &err_origin);
    ioctl(fd, PERF_EVENT_IOC_DISABLE, 0);
    read(fd, &count1[iter], sizeof(long long));
