### ISSUE TITLE
get_core_pos Function Outputs Issue

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#1020]
Hi,

Yesterday I post an issue about using function `get_core_pos` in static TA, here is the link: [my closed issue](https://github.com/OP-TEE/optee_os/issues/1016) .

Today I built the system with the static TA and I called this function successfully.
My configuration is: Juno r1 with OE as the normal OS. 

In the TA, I write a loop:
`for (i=0;i<1000;i++)	{DMSG("Static TA's Current cpu %zu", get_core_pos());}`

So I could keep getting outputs:
`DBG TEE-CORE:inc_value:60: Static TA's Current cpu 3`

Meanwhile, I also use `top` command in normal world to monitor the CPUs' usages.
The interesting part is I found out that when the TA is looping, only CPU 5's `sy` value is 100%. I think this means the TA is actually running on the core 5. 
I also checked CA's `pid` and it did run on core 5 before switch to TA, so I think the `top`'s result is correct.

In this case, I did some tests for this issue, and I found that:
The results 0-3 of `get_core_pos` could match to the real cores 2-5 (A53 cores);
`get_core_pos`'s 4-5 could match to the real cores 0-1 (A57 cores).

I'm currently checking the source code of `get_core_pos` but it's not easy so I thought maybe you guys know why this happens.

Thank you.

**Comment by jforissier** [comment]
Hello @SimonWan,

`get_core_pos()` certainly does not "output a wrong value" on Juno. Maybe it does not return the value you expect, that's a different thing ;)
The code for Aarch64 is here: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/misc_a64.S#L34-L41 and it's about the same for 32-bit. As the comment says, `CorePos = (ClusterId * 4) + CoreId`. `CoreId` and `ClusterId` are read from the MPIDR register, i.e., bits [7:0] and [15:8] respectively, which corresponds to the so-called "affinity levels" 0 and 1. What this means, typically, is that affinity level 0 is the identifier of the core within the higher affinity level, which is the cluster. Affinity level 1 is therefore the identifier of the cluster within the system (assuming there is no higher affinity level such as several CPU sockets for instance).
Now the purpose of `get_core_pos()` is to return an index for each core in the whole system, unique for each core, and comprised between `0` and `(ncores - 1)`. It is used for instance to access per-CPU translation tables or temporary stacks. There is no reason why the mapping between MPIDR values and core index would be the same as in the Linux kernel.

**Comment by SimonWan** [comment]
@jforissier thank you. You are right it's not "wrong output", I'm sorry for the words I used and I just edit the issue. I would keep learning these related codes and close this issue. Have a good day.

**Comment by jforissier** [comment]
@SimonWan it's OK, my remark was not meant to be taken too seriously (note the smiley!).

**Comment by SimonWan** [comment]
@jforissier yeah I noted the smile ;) Thanks.

By the way, may I ask how to call a static TA from a dynamic TA? 
Is there any code I can look for? 
I tried to search for the answer but I can't find.

Thank you.

PS: I don't open a new session since I feel this might be a naive problem and I hope I don't  trouble you with too many issues.

**Comment by SimonWan** [comment]
@jforissier could you please check my last question?

**Comment by jforissier** [comment]
@SimonWan sorry for not seeing your new question.
You can call a TA (static or dynamic) from dynamic TA by using `TEE_OpenTASession()`, `TEE_InvokeTACommand()` and `TEE_CloseTASession()` (section 4.9 Internal Client API in the GP TEE Internal Core API Specification 1.1)

**Comment by SimonWan** [comment]
@jforissier I understand that you are busy.
The document is very useful and I have called TA in TA successfully.

Sorry I have so many questions but I'm wondering is there any api for TA (dynamic or static) to get the time such as header file time.h for client application?

Thanks.

**Comment by SimonWan** [comment]
Oh I just found thre is TEE_Time in that document, I'll try by myself, thanks again.
