### ISSUE TITLE
AES CTS scheme

### ISSUE THREAD

**Issue by renzoz** [OP-TEE/optee_os#1022]
Hi,
I have been trying to use some cryptographic operations in order to cipher some data with some troubles.
The sequence of operations used is the following:

1. Initialize context and open a new session.
2. Create a transient object for a AES 256 key.
3. Allocate an operation for AES CTS with Encrypt mode.
4. Set the key to the allocated operation.
5. Init the operation with TEE_CipherInit.
6. Call TEE_CipherUpdate with the blocks to cipher.
7. Call TEE_CipherDoFinal with the last block to cipher.
8. Free operation and key.
9. Close session and context.

The problem is: When I call TEE_CipherUpdate and TEE_CipherDoFinal I pass two buffers with the same length (32B), one with the plain text and the other where the output is to be left, but TEE_CipherDoFinal returns TEE_ERROR_SHORT_BUFFER.
To my understanding if I use blocks of 32B the function should return the block encrypted, but after checking all the returned buffers it shows that the first call to TEE_CipherUpdate returns a buffer size of 0. Meaning that the first block isn't being encrypted on the first call.
After checking the source code in this repo I found on `tee_api_operations.c` that, when using AES CTS the first call to TEE_CipherUpdate will just save the input block on the internal buffer of the operation. What's more, this will propagate to subsequent calls where it will return the last block encrypted and save the current input for the next call. As a result, when TEE_CipherDoFinal is called there is an additional 32B of data left to be processed, so in turn it will expect a 64B output buffer.
At first, I thought this was needed for the CTS, given that the last block is needed for the penultimate block, but for AES the block size is 128 bits and this seems to be taken care of with the `buffer_two_blocks` variable, nevermind the fact that the processing sequence in TEE_CipherDoFinal would not be correct.

So, is this the intended behavior with AES CTS? or rather something else, e.g. a side effect of having to support different kinds of algorithms.

Thanks

**Comment by jforissier** [comment]
Hi @renzoz, 

There is no guarantee that `TEE_CipherUpdate()` will return any data. Only after `TEE_CipherDoFinal()` you have your encrypted data. As per the GP spec for `TEE_CipherUpdate()`:

> Unless one or more calls of this function have supplied sufficient input data, no output is generated. The cipher operation is finalized with a call to TEE_CipherDoFinal .

"Sufficient input data" is not specified, so it may mean any value depending on the algorithm, the implementation etc. So the behavior of OP-TEE is correct IMO.
Now, it might be that we could do differently and output data sooner (I did not check this particular case of AES CTS).

**Comment by renzoz** [comment]
Then, given an unknown stream of data of arbitrary length, how can I know how much space should need to reserve to `TEE_CipherDoFinal()`? Would my application have to keep track of the amount of data passed and received?.

Thanks

**Comment by jforissier** [comment]
Yes, you need to keep track of what's in and what's out. If you encrypt N bytes of plain text you should get N bytes of cipher text. Then suppose `TEE_CipherUpdate()` returns M bytes total (in one or several calls), then `TEE_CipherDoFinal()` will return the remaining N-M bytes.

**Comment by renzoz** [comment]
Understood, thank you very much for the clarification.
