### ISSUE TITLE
RPMB file system performance

### ISSUE THREAD

**Issue by zhupg** [OP-TEE/optee_os#1033]
Hi:
  I do a rpmb file system performance test, the performance is too poor, the write speed is only about 2KB/s.
    emmc: samsung KLM8G1WEMB
    After modify follow code, write speed is about 10KB/s.

    tee-supplicant/src/rpmb.c
    -               cmd.postsleep_min_us = 20000;
    +               cmd.postsleep_min_us = 0;

But the performance is still too poor.
    Have you test performance on a real platform? Is the performance same?
    Could you give some advice to optimize the rpmb performance? Thanks.

**Comment by jbech-linaro** [comment]
Hi @zhupg ,

Storage performance is OP-TEE is generally very poor, i.e., not only when using RPMB. We are aware of this and we have task that is about increase storage performance. One part of that task is that we're going to try to minimize the numbers of times we are jumping and back and forth between secure and non-secure world. We have just recently started to work with this task. Regarding performance figures for RPMB itself on real hardware, I think @jforissier can chime in, eventually he has done some.

**Comment by jforissier** [comment]
@jbech-linaro I did use real eMMC hardware with the HiKey board, but I have not done any performance testing. As you are suggesting, we may gain some performance by grouping writes together (or rather, not splitting them). Speaking of this, I don't understand the comment in `tee_rpmb_write_blk()`: https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_rpmb_fs.c#L1323-L1326.

@zhupg regarding the 'postsleep' settings, as the comment suggests it was set with trial and error on HiKey so it's definitely something that should be looked into and improved (can we find the correct value dynamically by probing the hardware maybe?).

**Comment by prime-zeng** [comment]
@jforissier  i think that means the EMMC hardware can only accept rel_wr_blkcnt blocks at one single write for reliability. (I guess Maybe because of the internal buffer of EMMC hardware).

**Comment by jforissier** [comment]
@prime-zeng yes I know that, but why would the function split the data to be written? There is no special handling on error (no retry for instance), other than returning from the function and leaving partially updated data (assuming you're trying to write more than the reliable write count) [1]. That would be exactly the same if we would send the whole data as one command, I think. What I am missing?

[1] Atomicity of the update is still achieved by allocation and FAT update algorithm

**Comment by zhupg** [comment]
@jforissier the 'postsleep' settings seems different from different emmc product. It is hard to dynamically get the setting from hardware, Maybe we can find the correct value by probing the hardware then look up a pre-defined table.

**Comment by jforissier** [comment]
@zhupg yes the table lookup is a good idea I think.

**Comment by zhupg** [comment]
Thanks for all your reply.
