### ISSUE TITLE
reserved memory in DTS for shared memory area

### ISSUE THREAD

**Issue by yanyan-wrs** [OP-TEE/optee_os#1034]
It appears that the generated "reserved-memory" node in DTS should have the "no-map" property set, or the `ioremap` of the tee driver in Linux would fail due to remap of system RAM area.

Currently, the DTS node generated is:
```
optee@78000000 {
    reg = <0x78000000 0x800000>;
};
```
It should be:
```
optee@78000000 {
    reg = <0x78000000 0x800000>;
    no-map;
};
```

**Comment by jenswi-linaro** [comment]
Fix in https://github.com/OP-TEE/optee_os/pull/1039

**Comment by jbech-linaro** [comment]
This means that we also should update all *.dts files where OP-TEE is used? Or can we always consider that we will fiddle with the DT blob before kernel see it? To me it sounds like it wouldn't hurt to update the dts files. What do you guys think? 
```bash
cd linux ...
./arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts:
./arch/arm64/boot/dts/arm/foundation-v8.dts:
./arch/arm64/boot/dts/arm/qemu-v8.dts:
./arch/arm64/boot/dts/mediatek/mt8173-evb.dts:
```

**Comment by jbech-linaro** [comment]
Let's keep this issue open until that has been done.

**Comment by jenswi-linaro-adm** [comment]
Keeping this issue open until the our kernel branch is updated too.

**Comment by jforissier** [comment]
OK, trying to figure out which DT files exactly need the `no-map` update. Our kernel branch has the following files that contain optee nodes:
```
$ git grep -l optee | grep dts
arch/arm64/boot/dts/arm/foundation-v8.dts
arch/arm64/boot/dts/arm/juno-base.dtsi
arch/arm64/boot/dts/arm/qemu-v8.dts
arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts
arch/arm64/boot/dts/mediatek/mt8173-evb.dts
```

Only `foundation-v8.dts` and `juno-base.dtsi` have an optee node in `reserved-memory`. `qemu-v8.dts` uses OP-TEE's `CFG_DT` so the node is added automatically by OP-TEE. HiKey does not need it (the memory is reserved by UEFI). As for `mt8173-evb.dts` I don't know how it reserves its memory but it must be similar..
So it seems that `no-map` has to be added to `foundation-v8.dts` and `juno-base.dtsi` only. I will create a PR for them.

**Comment by jbech-linaro** [comment]
Regardless how we're doing for MT8173, I think we should wait with it, since it's been a while since we tested that board. Speaking about that, at Connect I asked Freedom from MediaTek about that status of the support for the board and according to him it should be fine. So, I'll guess I'll try to boot it up when I find some time to do it. But for the 2.2.0 release I won't have time to dig into it.

**Comment by jforissier** [comment]
Ok. BTW, release 2.2.0 or 3.0.0 ? The secure storage has changed in an incompatible way (per-TA key).

**Comment by jbech-linaro** [comment]
Are API's using it affected? Core <-> TA? If not, then I'd suggest stick to 2.2.0.

**Comment by jforissier** [comment]
No, no change in the interfaces at all.
I'll check the code to make sure what really happens if you do use the new TEE with old data. IIRC, the REE fs will automatically delete the "corrupt" data, while RPMB will just report an error (and the TA _can_ delete the object).
