### ISSUE TITLE
How to link a static prebuilt library(libxxxx.a) into OP-TEE ?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1035]

**Comment by jforissier** [comment]
Try this:
```
diff --git a/core/core.mk b/core/core.mk
index afce7ea..6dbabf6 100644
--- a/core/core.mk
+++ b/core/core.mk
@@ -92,4 +92,6 @@ include mk/subdir.mk
 asm-defines-file := core/arch/$(ARCH)/kernel/asm-defines.c
 include mk/compile.mk
 
+libnames += foo
+libdirs += /path/to/lib/foo
 include $(platform-dir)/link.mk
```

I think it is a bit dangerous to link a library not compiled with the OP-TEE Makefiles, because you may have inconsistent build flags or section names (I'm thinking about the things we do when pager is enabled for instance). But you can try it of course ;)

**Comment by prime-zeng** [comment]
Yes, that works, thank you.
