### ISSUE TITLE
PL310 configuration wipes the entire L2 cache

### ISSUE THREAD

**Issue by vsiles** [OP-TEE/optee_os#1038]
Hi,

in the reset_primary (https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/generic_entry_a32.S line 263) function,  arm_cl2_enable is called, then there is a big comment about being careful to only invalidate data that are related to OP-TEE, avoiding to invalidate data that might be related to the ATF, so you invalidate by pa.

However, in arm_cl2_enable (https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-stm/tz_a9init.S line 144), at the end of the function, the whole cache (at least 8 ways, even if pl310 can use 16 ways) is invalidated by way.

So the invalidate L2 by pa seems redundant, and the comment seems off-topic since we just nuked everything in the pl310.

Am I missing something or this is a mistake ?

Best regards,
Vincent Siles

**Comment by etienne-lms** [comment]
`plat-stm` targets c-a9 and runs without ATF hence no cache invalidate big constraint.
At early reset, when `reset_primary` calls `arm_cl2_config`, `plat-stm` assumes L2 will be enabled and is, therefore, prepared (cleaned).

On the other hand `generic_entry_a32.S` is... generic and invalidates only what is needed.

So yes, stm run two cache invalidate sequence. Not that much waste of time.
If you run a optee/stm with a boot sequence before optee that enables L2 and other hw, you will likely disable most of the content of tz_a9init.S.

**Comment by vsiles** [comment]
Ok, I understand, thank you for clarifying the situation.

Best,
V.
