### ISSUE TITLE
[REE Storage] Why rename("file", "file.trash") in ree_fs_unlink()?

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#1041]
It seem can not ensure atomic unlink operation. Why not unlink the file directly?
Please share your mind, thanks.

**Comment by jforissier** [comment]
I don't see why `rename()` is needed either. How could `unlink()` not be atomic? (in this context, _atomic_ means: either succeeds or fails, and if it fails, the operation must have had no effect; in other words, we don't want partial modification of the file system).

**Comment by d3zd3z** [comment]
I believe `unlink()` is atomic per Posix, and is with most Linux filesystems. `rename()` is also atomic, provided both paths are on the same filesystem.

**Comment by jenswi-linaro** [comment]
REE FS files are represented by a directory containing a bunch of files (meta.{0,1}, block{1..n}.{0,1}). So the unlink is in the end an rmdir after all the files has been unlinked. I'm currently doing an overhaul of the different filesystem implementations. Expect some changes (pull requests) in the near future.

**Comment by jbech-linaro** [comment]
I guess this PR https://github.com/OP-TEE/optee_os/pull/1151 is an answer to the problem discussed here? @jenswi-linaro ? If yes, can we all agree to close this issue?

**Comment by jenswi-linaro** [comment]
@jbech-linaro, correct.

**Comment by jbech-optee-adm** [comment]
#1151 has been merged and based on the last comments here, I'm closing this issue.
