### ISSUE TITLE
Compilation and run time loading of TAs

### ISSUE THREAD

**Issue by chinnabha** [OP-TEE/optee_os#1042]
Hi experts,

Please help me in answering these questions?

1. Does all the TA need to be built with Optee statically? Is there a way to compile TAs separately and to attach them to Optee dynamically?

2. What are user TAs referred in the below function tee_ta_init_session( ) in bold colour? How those user TAs are compiled and where those originally stored before tee_ta_init_user_ta_session( )? 

static TEE_Result tee_ta_init_session( .  .  .)
{
          .    .    . 
       
        // Look for static TA 
        res = tee_ta_init_static_ta_session(uuid, s);
        if (res == TEE_SUCCESS || res != TEE_ERROR_ITEM_NOT_FOUND)
                goto out;

        // Look for user TA 
        res = **tee_ta_init_user_ta_session**(uuid, s);

            .    .    . 
}

3. What is the functionality provided by CFG_WITH_USER_TA?

**Comment by jenswi-linaro** [comment]
Hi,

A user TA is a normal dynamic TA that is build separately from OP-TEE. Static TAs on the other hand are built into OP-TEE. `CFG_WITH_USER_TA` enables support for user TAs.

Regards,
Jens

**Comment by jforissier** [comment]
Hi @chinnabha ,

There are currently two kinds of Trusted Applications: "static" TAs that are linked with OP-TEE, and "user" TAs that loaded dynamically from the REE filesystem by `tee-supplicant` (`*.ta` files). On ARMv8, static TAs execute in S-EL1 in the same virtual memory space as OP-TEE, while user TAs run in S-EL0 in their own virtual memory space. Currently, you cannot have a TA that is loaded dynamically and executed in the TEE virtual memory.
- For an example of a static TA, see for instance https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/sta/stats.c
- For an example of a user TA, see for instance https://github.com/linaro-swg/hello_world/

**Comment by chinnabha** [comment]
Thanks @jenswi-linaro & @jforissier for the pointers.

@jforissier, it seems tee-supplicant.bin is obtained by compiling [optee_client](https://github.com/OP-TEE/optee_client). I didn't understand how this tee-supplicant is tied to the hello world user TA for its dynamic loading. Does the tee-supplicant.bin compilation independent of user TAs?

**Comment by jbech-linaro** [comment]
tee-supplicant as such is a standalone binary. It is **used** when loading Trusted Application from the filesystem in Linux (it's used to more than that, but that is one of the use cases). When building a TA it will use the exported files in optee_client (the Client API headers etc, but not tee-supplicant) and it will use the "ta-dev-kit" in optee_os.

**Comment by chinnabha** [comment]
Thanks @jbech-linaro. Ok, user TA compilation has dependency only for the exported files in optee_client/out/export and optee_os/out/arm*/export-ta_arm64 respectively, but not on tee-supplicant.
 
What may be the default location in the Linux file-system from which tee-supplicant fetch & launch the userTA.bin? From the same directory where it (tee-supplicant) lives in, something like /system/bin/?
Otherwise can we specify its path? If yes where we need to give this path?

**Comment by jforissier** [comment]
Defaut path is `/lib/optee_armtz`. It's hardcoded in  `tee-supplicant`.

**Comment by chinnabha** [comment]
Ok. Thanks everyone for the help. Closing this issue.
