### ISSUE TITLE
OPTEE Build System for Library

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1043]
Hello, I am trying to understand the OPTEE build system. I am trying to answer the question whether a library linked to a TA (like libutee) can use code from the Core (include a header inside the Core and call one of its functions).

To be specific, I need to invoke a function inside core_memprot.h (optee_os/core/arch/arm/include/mm/core_memprot.h) from my TA. I cannot directly include the header, but I'm thinking if I could add a library that could have that header (and provide a way to call its functions), and link the library to the TA. So I'm checking libutee as an example to see if core methods are accessible to a library and if so where in the make files in such association established (for libutee, or one of the other libraries under /lib).

I can elaborate the question if needed. Any suggestions are helpful. Thanks.

**Comment by jenswi-linaro** [comment]
Hi,

A TA runs in user mode while the OP-TEE OS runs in privileged kernel mode. A TA can't access privileged memory or execute code/instructions that requires a privileged mode. You can compare the relationship between TA and OP-TEE OS as how user space programs in Linux relates to the Linux kernel.

Regards,
Jens

**Comment by a2t2** [comment]
Okay Thanks.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
