### ISSUE TITLE
build issue when CFG_WITH_PAGER is used

### ISSUE THREAD

**Issue by yanyan-wrs** [OP-TEE/optee_os#1046]
```c
    ASSERT(CFG_TEE_LOAD_ADDR >= CFG_TEE_RAM_START,
        "Load address before start of physical memory")
    ASSERT(CFG_TEE_LOAD_ADDR < (CFG_TEE_RAM_START + CFG_TEE_RAM_PH_SIZE),
        "Load address after end of physical memory")
    ASSERT(__tmp_hashes_end < (CFG_TEE_RAM_START + CFG_TEE_RAM_PH_SIZE),
        "OP-TEE can't fit init part into available physical memory")
    ASSERT((CFG_TEE_RAM_START + CFG_TEE_RAM_PH_SIZE - __init_end) >
        1 * 4096, "Too few free pages to initialize paging")
```

if the RAM is at the end of 4G space, for example, on ZYNQ7K:
```c
CFG_TEE_RAM_START = 0xFFFC0000
CFG_TEE_RAM_PH_SIZE = 0x40000
```
the ASSERT somehow uses 32 bit integer, which causes the value to overflow and the assertion fails.

Even if I removed the ASSERT, the resultant binary is not correct, the pager.bin is about 4.3Gb in size; there must be some overflow also in the build process.

**Comment by jenswi-linaro** [comment]
Another problem related to this is that the paging assumes that there's enough virtual memory space for the paged code after the start of the physical memory. It will require some work to get the paging working properly for this configuration.

**Comment by yanyan-wrs** [comment]
Yes, if the TEE RAM is at the end, any extra mapping would go wrap around 0x0 and conflicts with TA virtual space.
Why don't we just use fixed virtual space, and give up the 1:1 mapping for kernel.

**Comment by jenswi-linaro** [comment]
The first problem is that we need to have true position independent assembly code establishing the initial mapping before the MMU is enabled.
The second problem is if we need to disable the MMU due to taking cores down and up again it will be a bit tricky as we'll need to keep the piece of code that disables and enables the MMU in identity mapped memory.

**Comment by jbech-linaro** [comment]
@yanyan-wrs @jenswi-linaro , without spending too much digging into this it sounds like a bug, so my suggestion is to label this as a bug and keep it left open? Do you agree?

**Comment by jenswi-linaro** [comment]
@jbech-linaro, agree.

**Comment by yanyan-wrs** [comment]
@jbech-linaro, agree, although this bug only presents itself on some corner cases, i.e., when the physical memory is at high end of the address space.

**Comment by TEE-OS** [comment]
The problem happens in nxp i.mx6q sabresd board when CFG_WITH_PAGER is enabled and the CFG_TEE_LOAD_ADDR = TZSRAM_BASE.

Does anyone have solved this problem?

**Comment by jbech-linaro** [comment]
@TEE-OS , I'm afraid the issue is still there.

**Comment by etienne-lms** [comment]
I confirm that, as @jenswi-linaro said, optee pager still expects the paged virtual memory to be above the unpaged memory which is flat mapped. This forbids use of pager with a internal ram physically located at top of the virtual address space range.

**Comment by mimok** [comment]
I'm facing the same issue.

In your opinion, how much work would be needed to fix this bug? From what I can see, `core_mmu.c`, `tee_pager.c` and maybe `core_mmu_lpae.c` are impacted. Do you think any other parts of OP-TEE core are impacted?

**Comment by etienne-lms** [comment]
Not an easy change. `core_mmu_lpae.c` should not be impacted, rather `core_mmu.c` and `core/arch/arm/kernel/kern.ld.S`, and a bit in `tee_pager.c`.
