### ISSUE TITLE
Optee crash after moving to tag 2.1.0

### ISSUE THREAD

**Issue by chinnabha** [OP-TEE/optee_os#1053]
Hi,

Earlier I was using 2.0.0 tag. Now I moved to tag 2.1.0. Optee hanging noticed at the end of below log snippet.

Configuration:
    (TEE_RAM_START, TA_RAM_STAR) = (0x82000000, 0x82100000),
    (TA_RAM_START, TA_RAM_END) = (0x8210000, 0x88000000), and
    (NSEC_SHM_START, NSEC_SHM_END) = (0x88000000, 0x88200000).

            #define DEVICE0_PA_BASE         ROUNDDOWN(CONSOLE_UART_BASE, 
                                                           CORE_MMU_DEVICE_SIZE)
            #define DEVICE0_VA_BASE         DEVICE0_PA_BASE
            #define DEVICE0_SIZE            CORE_MMU_DEVICE_SIZE
            #define DEVICE0_TYPE            MEM_AREA_IO_SEC
     
2.  With the above configuration, can someone please help me knowing:
          (A)   Why the UART virtual address space mapped to 0x88200000..0x883fffff? 
          (B)   20 MB reserved virtual address space (teecore_memtype = 8= MEM_AREA_RES_VASPACE) showing up in the log. Does optee reserve this memory by default? 
    
NOTICE:  BL31: v1.2(debug):test
NOTICE:  BL31: Built : 07:54:36, Sep 15 2016
INFO:    GICv3 without legacy support detected. ARM GICV3 driver initialized in EL3
INFO:    BL31: Initializing runtime services
INFO:    DRAM memory information service registered
INFO:    BL31: Initializing BL32

DEBUG:   [0x0] TEE-CORE:add_phys_mem:258: CFG_TEE_RAM_START 1 0x82000000 size 0x00100000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:258: CFG_TA_RAM_START 3 0x82200000 size 0x05e00000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:258: CFG_SHMEM_START 4 0x88000000 size 0x00200000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:258: **DEVICE0_PA_BASE** 7 0x12600000 size 0x00200000
**DEBUG:   [0x0] TEE-CORE:add_phys_mem:258: 0 8 0x00000000 size 0x01400000**

DEBUG:   [0x0] TEE-CORE:init_mem_map:396: type va 1 0x82000000..0x820fffff pa 0x82000000..0x820fffff size 0x100000
DEBUG:   [0x0] TEE-CORE:init_mem_map:396: type va 3 0x82200000..0x87ffffff pa 0x82200000..0x87ffffff size 0x5e00000
DEBUG:   [0x0] TEE-CORE:init_mem_map:396: type va 4 0x88000000..0x881fffff pa 0x88000000..0x881fffff size 0x200000
DEBUG:   [0x0] TEE-CORE:init_mem_map:396: **type va 7 0x88200000..0x883fffff pa 0x12600000..0x127fffff size 0x200000**
DEBUG:   [0x0] TEE-CORE:init_mem_map:396: **type va 8 0x88400000..0x897fffff pa 0x00000000..0x013fffff size 0x1400000**

**Comment by jenswi-linaro** [comment]
We've recently changed to only identity map the `CFG_TEE_RAM_START` memory, the rest of the memory and devices uses non-linear map. Your crash is probably due using a physical pointer without translating it to a virtual pointer first.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by chinnabha** [comment]
Thanks @jenswi-linaro for the help. I had hard coded my console base address with Physical address. The crash issue solved after correcting this to derive the virtual address (after the mmu enable).

Please help me answering the following queries:

1.  what is the need of mapping the 20 MB physical address space (with CFG_WITH_LPAE=1) starting from 0x0 to optee_os virtual address space, via **register_phys_mem(MEM_AREA_RES_VASPACE, 0, RES_VASPACE_SIZE)** ?
2. Does this virtual space behave as secure memory or normal memory?

**Comment by jenswi-linaro** [comment]
This is an inactive mapping which just reserves an address range in the translation tables for later use by `core_mmu_add_mapping()`. The `0` isn't a physical address in this case, it's just an empty entry.
