### ISSUE TITLE
add arm-smccc patch version to port to 4.2 kernel

### ISSUE THREAD

**Issue by chinnabha** [OP-TEE/optee_os#1058]
Hi Jens,

There are multiple versions of the "add arm-smccc" v8 patch @https://patchwork.kernel.org/project/linux-arm-kernel/list/?submitter=129291, some in acked state and some not.

I need to port this patch to 4.2 kernel for arm64. Latest patch v8 state is as follows:
[v8, 4/4]  -> In Acked state
[v8, 3/4]  -> In Acked state
[v8, 2/4]  -> Don't care for me as this is for "arm" 
[v8, 1/4]  -> Not in acked state

Please tell me if it is safe to pick [v8, 4/4], [v8, 3/4] and [v8, 1/4] to port to arm64 Linux v4.2.

**Comment by jenswi-linaro** [comment]
Hi,

Cherry-pick the version of the patches merged into the v4.5 kernel.

Regards,
Jens
