### ISSUE TITLE
A problem in function tee_svc_cipher_update_helper

### ISSUE THREAD

**Issue by lackan** [OP-TEE/optee_os#1063]
Hi, in function tee_svc_cipher_update_helper, when value last_block is true and cs->ctx_finalize is not NULL, it will invoke cs->ctx_finalize(cs->ctx, cs->mode),  the second parameter here should be cs->algo.
Because the function cipher_final do nothing now, so all the tests can also pass. But actually, in function cipher_final we will never run into the right case.

**Comment by jforissier** [comment]
Hi @lackan,

You're right, good catch! Would you please create a pull request to fix this issue?
I'm wondering if we should add this also:
```diff
diff --git a/core/lib/libtomcrypt/src/tee_ltc_provider.c b/core/lib/libtomcrypt/src/tee_ltc_provider.c
index 75abfd3..b891efe 100644
--- a/core/lib/libtomcrypt/src/tee_ltc_provider.c
+++ b/core/lib/libtomcrypt/src/tee_ltc_provider.c
@@ -2219,7 +2219,7 @@ static void cipher_final(void *ctx, uint32_t algo)
                break;
 #endif
        default:
-               /* TEE_ERROR_NOT_SUPPORTED; */
+               assert(TEE_ALG_GET_CLASS(algo) == TEE_OPERATION_CIPHER);
                break;
        }
 }
```
(the assert *does* trigger when `xtest` is run and OP-TEE was built with CFG_TEE_CORE_DEBUG=y).

**Comment by jenswi-linaro** [comment]
@jforissier, this assert, can it be triggered from a user TA or is it only due to bad logic in OP-TEE Core?

**Comment by jforissier** [comment]
@jenswi-linaro I certainly hope it can only be triggered due to bad logic in the TEE core. My reasoning is that  `crypto_ops.cipher.final()` should never be called for an algorithm that is not a (symmetric) cipher. But I agree this has to be double-checked.

**Comment by jenswi-linaro** [comment]
@jforissier, I guess we can say that if it's triggered it's per definition due to bad logic in OP-TEE core.

**Comment by jforissier** [comment]
Exactly, in other words, I think assert()ing here is legitimate.

**Comment by jenswi-linaro** [comment]
Agree

**Comment by lackan** [comment]
@jforissier My pleasure, I will fix it with the assert.

**Comment by jforissier** [comment]
Fixed in https://github.com/OP-TEE/optee_os/pull/1066.
