### ISSUE TITLE
Can't find "adbg_case_declare.h" during optee_test compilation

### ISSUE THREAD

**Issue by yatrust** [OP-TEE/optee_os#1064]
Hi,

I'm trying to compile optee_test. I compiled optee_os and optee_client, I defined all global variables for compiling project.
I'm trying to use my own .xml testing files, so I run make patch in optee_test directory. Now I want to compile the optee_test itself.
When I run make command into optee_test folder, the compiler doesn't found "adbg_case_declare.h".

This .h file is not in the project, but declare in .gitignore. 
If someone has this issue.

Regards,

**Comment by jforissier** [comment]
Hi @yatrust ,

As you can see from the Makefile, `adbg_case_declare.h` is generated from `TEE.xml` and `adbg_case_declare.xsl` by the `xalan` tool when the GlobalPlatform test suite is enabled (that is, when $(CFG_GP_PACKAGE_PATH) is defined).
Usually we don't write `.xml` files to add new tests, we just write the C code directly. XML files are for the GP test suite.

**Comment by jbech-linaro** [comment]
Hi,

My guess is that you're trying to build everything manually? The most important thing is to get all flags set correctly:
https://github.com/OP-TEE/build/blob/master/common.mk#L214-L235

You're running `make patch`, which implies that you're trying to run the tests from GlobalPlatform. Do you have access to those? If not, then you should not run `make patch`.

Having that said, I haven't seen the issue you're facing.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since we think the question has been answered as good as we can and also we haven't seen any activity on this thread for more than a month. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
