### ISSUE TITLE
Optimized QEMU32 build

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#1067]
I am just wondering when these are compiled for the QEMU 32-bit build, are the ta, optee os, linux, optee linuxdriver, optee-client etc. compiled with optimization flags (e.g., -O3, no -g)? If not, is there a way to turn that on across everything that gets built?

**Comment by igoropaniuk** [comment]
Hi @peterfeifanchen,
I assume that it's not possible to set some global optimization flag for everything. 

For each product that you have mentioned, there is own "wrapper" for adjusting optimization settings. 
For example, for the Linux kernel you can add CONFIG_CC_OPTIMIZE_FOR_SIZE flag in .config .
For QEMU it's possible to pass additional compiler params (including -O3), to ./configure script
`./configure --extra-cflags="-O3"`

For optee_client, you can try to add -O3 to CFLAGS in optee_client/flags.mk. The same for optee_os, in mk/compile.mk

BTW, setting -O3 results to using some aggressive optimizations, and in some cases produces wrong code.

**Comment by peterfeifanchen** [comment]
I see thanks!
