### ISSUE TITLE
Enabling CNTPCT for EL0

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#1070]
On my HiKey board, I enabled EL0 access by adding this to optee_armtz kernel module:

`asm ( "msr cntkctl_el1, %0 \n\t" : : "r"(1) )`

While this allowed me to read cntpct from userspace on my QEMU setup. My HiKey board is giving me illegal instruction errors. 

I was wondering if this had something to do with multicore and that it is only enabled on the core that happens to be loading the kernel module. In QEMU, there is only one core so that won't have been a problem. If that is the case, does anyone know how I can enable CNTPCT_EL0 for every core?

**Comment by igoropaniuk** [comment]
Hi @peterfeifanchen,
What HiKey board are you using? 


BTW, I've found a good [manual](http://neocontra.blogspot.com/2013/05/user-mode-performance-counters-for.html) about using ARM generic timers in Linux + also there is info about working with timers on SMP systems. They are using MCR instruction for working with coprocessor registers([details](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0204h/Cihfifej.html)) instead of more convenient MSR, but anyway. I hope it helps

> mcr p15, 0, <Rt>, c14, 0
> where <Rt> is a register containing either 1, which enables user-mode access, or 0, which disables user-mode access.

**Comment by peterfeifanchen** [comment]
I have this [one](http://www.lemaker.org/product-hikey-index.html). 

The problem with the mcr p15, 0, c14, 0 was it did not even compile and when I looked at the [TRM](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0438c/BABIDBIJ.html). It is actually c14, c1 for CNTKCTL. I tried it in my QEMU 32-bit build with mcr p15, 0, c14, c1, 0 and it worked. But on my Hikey it takes aarch64 instructions so therefore the msr. 

But I will give the on_each_cpu() a try.

**Comment by peterfeifanchen** [comment]
Hmm...it seems to hang my kernel module now. When I try to enable user space access to CNTPCT.

**Comment by peterfeifanchen** [comment]
The error I get when I try to write a 1 to CNTKCTL in the kernel seem to be: 

> systemd-logind[1335]: Failed to apply ACLs: Operation not supported

**Comment by peterfeifanchen** [comment]
Ahh I figured it out. It seems something in the display and uart and probably others rely on some of the other bits in the CNTKCTL register. This was not a problem in QEMU apparently. 

uint32_t  cnkctl;
asm volatile( "mrs %0, cntkctl_el1" : "=r" (cntkctl) );
cntkctl |= 1;
asm ( "msr cntkctl_el1, %0\n\t" :: "r"(cntkctl) );

This will work!
