### ISSUE TITLE
Extract AES key to normal world (REE)

### ISSUE THREAD

**Issue by Faidon09** [OP-TEE/optee_os#1072]
Is it possible to extract and transfer an AES generated key from TEE to normal world (TEE)?

**Comment by jbech-linaro** [comment]
Yes, that is possible, as long as a Trusted Application can get hold of data, you can always send it back to normal world (using the standard communication interface, TEE Client API).

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
