### ISSUE TITLE
Access Physical address from TA

### ISSUE THREAD

**Issue by ggao-inven** [OP-TEE/optee_os#1073]
I read the issues https://github.com/OP-TEE/optee_os/issues/404 about physical address mapping. However, I still don't quite understand this problem. 
I am facing the same problem. There is a extra FPGA connected to the Juno box extension. It has a fixed physical address. I need to access it inside TEE. Here is the question I am having.
1. Why I have to use static TA? What is the difference between static TA and regular TA? Is there anything static TA can do but regular TA cannot do? This may be a stupid question since I don't quite understand the concept of static TA.
2. core/arch/arm/kernel/generic_core_bootcfg.c There is no such file at all. Thus there is no way I can add new memory section. I checked the latest optee_os as well as the a snapshot of optee_os(using 1606). 
Thanks.

Best Regards,

Ge Gao

**Comment by jenswi-linaro** [comment]
Hi,

1) A static TA is part of OP-TEE core and can call functions available in OP-TEE core, the environment is not GlobalPlatform like. While a user TA runs in user mode with GP APIs available and are loaded dynamically.

2) We've recently changed how mappings are established, now we use the `register_phys_mem()` macro. Examples in `core/arch/arm/mm/core_mmu.c` and `core/arch/arm/plat-vexpress/main.c`. 

Regards,
Jens

**Comment by ggao-inven** [comment]
Thanks. This is very helpful. So the static TA is part of the optee_os. If I changed static TA, I need to rebuild optee_os and rebuild Linux and update it? About this optee_os, I can't find where to update it into the Juno box, is it part of the Linux? If I update Linux, the optee_os is automatically updated?
For the physical address mapping, if I have device has a physical address of 0x60040000, accessible from REE world, that has a register size of 0x1000, I should write:
register_phys_mem(MEM_AREA_IO_SEC, 0x60040000, 0x1000). Is this correct?

Thanks.

Best Regards,

Ge Gao

**Comment by jenswi-linaro** [comment]
How to update optee_os into the Juno box depends on how you got it there from the beginning. There's some notes at https://github.com/OP-TEE/optee_os#57-juno .

If the device is accessible from non-secure world too it would be more correct to use
`register_phys_mem(MEM_AREA_IO_NSEC, 0x60040000, 0x1000)` instead.

**Comment by ggao-inven** [comment]
Thanks. I tried the method using https://github.com/OP-TEE/optee_os#57-juno . However, this is the error I got:

Cmd> ftp_on
Enabling ftp server...
 DHCP failed
 IP address: 192.168.0.100
If I use this IP address 192.168.0.100, it won't work cause the IP address is not correct. If I started the Juno box until Linux started, I get different IP address, which is a correct one.
I thought this optee_os is built into Linux and is part of the Linux?

Best Regards,

Ge Gao

**Comment by jenswi-linaro** [comment]
No, optee_os is placed in the FIP together with ARM-TF and the boot loader.

**Comment by ggao-inven** [comment]
I see there is a fip.bin file in the output/juno-android/uboot directory. If I copy this file to Juno Box like the instruction of Juno box said, I updated the optee_os. Is this correct?

Thanks.

Best regards,

Ge Gao

**Comment by jenswi-linaro** [comment]
Sounds OK, please note that the fip contains ARM-TF and other binaries too.

**Comment by ggao-inven** [comment]
Thanks.
This is very helpful.

Best Regards,

Ge Gao

**Comment by ggao-inven** [comment]
Another question maybe not related to this. About the debugging method. I am using Juno box, I wonder those DMSG messages. Is there anyway I can see those messages? I can only see the message from the REE world(normal world). not the secure world.

**Comment by ggao-inven** [comment]
Another question maybe not related to this. About the debugging method. I am using Juno box, I wonder those DMSG messages. Is there anyway I can see those messages? I can only see the message from the REE world(normal world). not the secure world

Thanks.

Best Regards,

Ge Gao

**Comment by jenswi-linaro** [comment]
The secure world messages are sent to a different uart (SoC UART1)

**Comment by ggao-inven** [comment]
Thanks. I can see them now.

Best

Ge Gao
