### ISSUE TITLE
Secure OS Output Issue

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#1075]
Hi experts,

I'm wondering is there anyway to display the output of secure OS with the same screen of the normal OS? 

I currently develop my CA/TA for Android and I want to display some information to the users. However, my threat model is that I don't trust the normal OS(Android) so I hope users could directly read the text/result from the secure OS.

Any advice is welcomed! Thank you.

Simon

**Comment by jforissier** [comment]
Hi @SimonWan,

OP-TEE does not support secure display currently. There is some code that can be useful to implement a Trusted User Interface (TUI) under `core/lib/libutee/tui` (text rendering functions, in particular). But to accomplish secure display, more is needed, such as properly sharing the frame buffer with the Normal World (Android kernel) and making it secure when needed, or dealing with any overlay buffer that the hardware might provide. This is largely platform-specific.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
