### ISSUE TITLE
bad mapping of TA secure memref parameters 

### ISSUE THREAD

**Issue by etienne-lms** [OP-TEE/optee_os#1081]
Optee core may badly maps TA buffer parameters (memref parameters) when a memref parameter for a nonsecure buffer has a lower parameter index than the memref parameter for a secure buffer. For example, assuming a TA expects parameter #0 to be a nonsecure buffer reference and parameter #1 refers to a secure buffer. Then those parameters gets a valid virtual address but the effective MMU table gets badly filled in by the core_mmu_lpae.c or core_mmu_v7.c.

This issue is found while experiencing test on the SMAF feature. Yet it can be reproduce in a TA-to-TA invocation setup.

The issue is in the tee_mmu.c implementation where the table listing the mapping for the TA is getting filled with the memref parameter info in the index order of the parameters while the virtual addresses are assigned first for secure memory area (including secure memref parameter) and then the non secure memory areas (obviously non-secure shared memory parameters.

xtest should be enhanced to cover such a setup. 

Proposed correction: https://github.com/etienne-lms/optee_os/commit/ef9d2229db1728907fd359f1b18fe719ff3d3903
This correction simply gets the mapping structure table being filled with secure memref parameters first, then non-secure parameter.

**Comment by jenswi-linaro** [comment]
Proposed fix looks good to me, please make a PR.

**Comment by etienne-lms** [comment]
ok i'll push the PR.

**Comment by etienne-lms** [comment]
fix merged through #1082
