### ISSUE TITLE
static TA vs normal TA

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#1085]
I can't seem to find this in any documentation. I was wondering what are some of the differences between static and non-static TA.

1) Is is it having to do with whether it is single instance or multi-session? Or is that an entirely orthogonal property?
2) Do static TA only exist in the OP-TEE OS or can it be in the secure world userspace too?
3) Are static TA just not paged in and out of memory whereas the normal non-static TA can?

**Comment by jenswi-linaro** [comment]
A static TA isn't a proper TA, it's rather a TA like interface. A static TA runs in secure world kernel mode only, the code is part of OP-TEE OS and paged where applicable. A static TA is single-instance, multi-session and can actually run several sessions concurrently, it's up to the implementation to serialize access/update of a common state when needed.

**Comment by peterfeifanchen** [comment]
Thanks!
