### ISSUE TITLE
static TA and persistent object

### ISSUE THREAD

**Issue by ggao-inven** [OP-TEE/optee_os#1086]
I am trying to read from a Physical address and save the result to a persistent object using APIs such as TEE_OpenPersistenentObject TEE_WriteObjectData, etc. Can I do that? I got a link error for those APIs.

**Comment by jenswi-linaro** [comment]
TEE_OpenPersistenentObject TEE_WriteObjectData, etc are only available to user TAs.

**Comment by ggao-inven** [comment]
Thanks.

Ge
