### ISSUE TITLE
Memory Footprint

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#1090]
Is there a way to find out the memory footprint for the optee-linuxdriver, optee-os, and TA?

**Comment by jbech-linaro** [comment]
Hi @peterfeifanchen ,

For optee_os, try run `make mem_usage`. For the others, there is nothing as a make target, but you can figure it out by running gcc's size commands, for example:

```
$ arm-linux-gnueabihf-size /mnt/sshd/devel/optee_projects/qemu/optee_test/out/ta/storage/b689f2a7-8adf-477a-9f9932e90c0ad0a2.elf
   text    data     bss     dec     hex filename
  74158     328   43920  118406   1ce86 /mnt/sshd/devel/optee_projects/qemu/optee_test/out/ta/storage/b689f2a7-8adf-477a-9f9932e90c0ad0a2.elf
```

The same would work in the Linux driver also, but you'd probably have to manually add the figure for some files.

**Comment by peterfeifanchen** [comment]
I see thanks.

A follow up question. If I have a multi-instance TA, does it instantiate a new instance every time or does it reuse the code section when it loads it into memory or just loads the TA completely again?

**Comment by jenswi-linaro** [comment]
Multi-instance TAs doesn't share/reuse any read-only sections with each other.
