### ISSUE TITLE
rcar-h3: xtest 4010 fails

### ISSUE THREAD

**Issue by lorc** [OP-TEE/optee_os#1092]
There are following error while running xtest:

`* XTEST_TEE_4010 Test TEE Internal API create transient object (negative)
/home/lorc/work/optee_test/host/xtest/xtest_4000.c:5037: ta_crypt_cmd_populate_transient_object(c, &session, o, &attr, 1) has an unexpected value: 0x0 = TEEC_SUCCESS, expected 0xffff3024
 = TEE_ERROR_TARGET_DEAD`

`optee_os` is on commit `f3b8897f3daae5d2f3238ba59ffd9c5f5fb54c9b`
`optee_client` is on `658ae538f76a2624b7f9c40539a600d281d872b4`
`optee_test` is on `a00eeb15ddfaa5b7d2cb340faeb36748d5aabffb`

Kernel is 4.6 with optee patches for K4.4

**Comment by jforissier** [comment]
Updated the title for the change log.

**Comment by lorc** [comment]
Could not reproduce on current master branches.
