### ISSUE TITLE
xtest 6009 panic issue

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1095]
DEBUG:   [0x0] TEE-CORE:tee_fs_rpc_lseek:281: ...0 ERROR:   TEE-CORE: Panic 'file too short' at core/tee/tee_ree_fs.c:363 <read_and_decrypt_file>

**Comment by prime-zeng** [comment]
I got the above error message when running the xtest 6009, and it seems that because of the broken ree fs, why not return an error instead of panic here?

**Comment by jenswi-linaro** [comment]
I agree, an error code in this case would be better. I'm currently refactoring the implementation of the different file systems. Removing all avoidable panics should be part of that.

**Comment by prime-zeng** [comment]
@jenswi-linaro , good news, so there will be new ree-fs based file system, and when will it be ready?

**Comment by jenswi-linaro** [comment]
It's hard to say as it's a rather big change I'm doing with all the file systems affected. I can't make any promises, but as an indication I can say I would be happy if it was merged before the end of this year. I'm not in control of when it will be merged, it depends on reviewers etc also.

**Comment by jenswi-linaro** [comment]
The panic is gone with c8016054915d2e5ec760128a309faebadf2716d6

**Comment by jforissier** [comment]
@prime-zeng may I close this issue?

**Comment by prime-zeng** [comment]
I think so, since the ree-fs has been refactoried.
