### ISSUE TITLE
Max number of multi cores supported in optee_os, requirement is to support 32 cores

### ISSUE THREAD

**Issue by chinnabha** [OP-TEE/optee_os#1104]
Hi,

Can someone please confirm the max number of multi cores supported by optee_os? 

Is it enough to define CFG_TEE_CORE_NB_CORE to the required value in optee_os/core/arch/arm/plat-xxxxx/platform_config.h? 

Does optee_os puts any stack size limitation?

**Comment by jforissier** [comment]
Hi,

The stack that depends on the number of physical cores is the "temporary stack", which is `stack_tmp` in `core/arch/arm/kernel/thread.c` Its size is `CFG_TEE_CORE_NB_CORE * STACK_TMP_SIZE`. There is nothing else you should need to change to adjust it to the number of cores of your SoC.

**Comment by chinnabha** [comment]
Thanks @jforissier. Awesome. It is straight forward then to enable optee_os support for multiple cores.

**Comment by jforissier** [comment]
Yes it is ;) Please also consider `CFG_NUM_THREADS` if you're interested in actual concurrency (executing secure code simultaneously on several cores).

**Comment by chinnabha** [comment]
Thanks @jforissier for this direction. I will get back to this thread after digging the technicalities little further.
