### ISSUE TITLE
static ta can access all memory space

### ISSUE THREAD

**Issue by zhizhouzh** [OP-TEE/optee_os#1105]
Hi,

To my understanding, TAs are like applications in linux. They should not have permission to access kernel space. I did a test in my armv8 board, my static TA can call any functions in optee-os, and read any global data in optee-os. Is this intended?

Thank you.

**Comment by jenswi-linaro** [comment]
Yes that's intended as static TAs runs in kernel mode. Static TAs is a last resort when a problem can't be solved with an ordinary user TA. So for isolation please use user TAs.

**Comment by zhizhouzh** [comment]
Thank you, by the way, did you mean static TAs runs in EL1 mode rather than EL0?

**Comment by jenswi-linaro** [comment]
Yes, they are part of OP-TEE OS code.

**Comment by zhizhouzh** [comment]
That really helps, thank you.
