### ISSUE TITLE
Invoking static TA as part of platform initialisation

### ISSUE THREAD

**Issue by radheshkrishnan** [OP-TEE/optee_os#1106]
Hi all,

I have implemented a Static TA to generate RSA key pair and saving it as persistent object. 
My question is how can I  call this STA on first boot of the device? Is it possible to call a STA  as part of (or during) platform initialisation before switching to normal world?  

Thank you,

**Comment by jenswi-linaro** [comment]
A static TA isn't a proper TA, it's just some OP-TEE OS code with a TA interface.
`driver_init_late()` probably does what you need except that since this is done before the first switch to normal world there's no normal storage available.

**Comment by radheshkrishnan** [comment]
Okay, that means I cannot generate persistent RSA keypair using STA., correct?  
My bad it was normal TA (what I implemented) which is generating persistent keypair for me not STA.
