### ISSUE TITLE
suspend/resume question for OP-TEE 

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1109]
Hi 
I have met a problem when implement the suspend and resume in OP-TEE, while doing the suspend and resume in OP-TEE, fiq/irq needs to be disabled, but when ARM-TF switch to the OP-TEE suspend entry, it just resume the spsr from the old saved spsr which maybe have already enabled the irq/fiq.

To solve the problem, i have got two ideas:
1. Disable the irq/fiq in ARM-TF before switch to the OP-TEE suspend entry, and restore it with the saved value when returned from the OP-TEE.
2. Keep the irq/fiq disabled in the OP-TEE just before switch to/back the ARM-TF, so that when ARM-TF switch to the OP-TEE irq/fiq status is always disabled.

**Comment by jenswi-linaro** [comment]
I think that 2) is what we do already.

**Comment by prime-zeng** [comment]
Good ,i have find some pieces of code doing 2), but i am not sure if all routines are covered.
