### ISSUE TITLE
question about ATF and OPTEE

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#1111]
In init_regs function, cpsr is assigned with EL1.

``` c
 367         thread->regs.pc = (uint64_t)thread_std_smc_entry;
xxx
 373         thread->regs.cpsr = SPSR_64(SPSR_64_MODE_EL1, SPSR_64_MODE_SP_EL0,
 374                                     DAIFBIT_IRQ | DAIFBIT_ABT);
```

Then in thread_resume, `eret` will runs into secure EL1 and pc points to thread_std_smc_entry.
But in my case, when eret, it runs into `fiq_el1_sp0`, I have no idea about what's wrong.

I am testing hello world test, the intialization and driver probe works well, but when execute hello_world, I met kernel panic in optee os side.
Per my understanding, in ATF + , el3_exit will runs into vector_std_smc_entry when run hello world, and exception level is EL1, but in thread_resume, EL1 eret to EL1?

Thanks.

**Comment by jenswi-linaro** [comment]
It could be that you have a pending FIQ that is taken as soon as it's unmasked by the `eret` due to the value in `SPSR_EL1`.

`eret` is used for atomic update of `pc` and `cpsr`, if exception level is changed or not doesn't matter.

**Comment by MrVan** [comment]
@jenswi-linaro Is it because SCR_EL3.FIQ is 0? Then non secure group1 taken as FIQ to Secure EL1?

**Comment by MrVan** [comment]
Seems main_fiq is not implemented. Then does optee os support GIC V3 , such as gic500 now?

**Comment by jenswi-linaro** [comment]
The design is that while the core is in secure `EL1`/`EL0` `SCR_EL3.FIQ` is `0` to take the FIQ as an exception directly. In non-secure `EL1`/`EL0` `SCR_EL3.FIQ` is `1` to take the FIQ in `EL3` and then enter OP-TEE via `vector_fiq_entry`.

`main_fiq` is still supposed to be implemented by platform specific code.
No, there's no support for GIC V3 yet.

**Comment by MrVan** [comment]
While the core is in secure `EL1/EL0` and `SCR_EL3.FIQ`  is 0, non secure group 1 interrupt is taken as FIQ to secure EL1 and runs into execption `fiq_el1_sp0`. right? But what should be done in main_fiq? The non secure group1 interrupt is for Linux in non secure world, but the interrupt happends when the core is in secure EL1.

If no GICV3, I may need to add it myself.

**Comment by jenswi-linaro** [comment]
Some of the variants of plat-vexpress has secure interrupt configured for input on `CONSOLE_UART` for test/demonstration purpose.

`main_fiq` is typically implemented as:
```
static void main_fiq(void)
{
        gic_it_handle(&gic_data);
}
```

As interrupt handling matures we may provide an implementation like that directly in the GIC driver.

**Comment by MrVan** [comment]
You may miss understand.  For example, when the core runs in non secure EL1, and do some mmc or timer operation, then wait for interrupt. Then the cores schedules tee process and switch to Secure EL1, now the mmc or timer interrupt comes, then FIQ triggered(because `SCR_EL3.FIQ` is 0) in secure EL1. But the interrupt is for non secure Linux, not for optee os.  If the interrupt is not for OPTEE os, optee should also handle it in `gic_it_handle`?

**Comment by jenswi-linaro** [comment]
Aha, sorry. Since we only have GICv2 (and v1?) support in OP-TEE secure interrupts are delivered as FIQ in secure world while the non-secure interrupts are delivered as IRQ in secure world. For GICv3 and onwards FIQ means it's an interrupt for the other world and IRQ something for this world.

To make things less confusing we'll need to drop the IRQ/FIQ terminology inside OP-TEE unless we're talking about the actual interrupt lines.

In GICv3 you'll need to do what `thread_irq_handler` does today for non-secure interrupts.

**Comment by MrVan** [comment]
Yout mean I need to take `thread_irq_handler` from `core/arch/arm/kernel/thread_a32.S` as a reference to implement `fiq_el1_sp0` in core/arch/arm/kernel/thread_a64.S?

**Comment by MrVan** [comment]
Or I need to use AArch32 mode for ARM64? Now I use `CROSS_COMPILE64=aarch64-poky-linux- PLATFORM_FLAVOR=mx8 make ARCH=arm PLATFORM=imx DEBUG=1 CFG_TEE_CORE_LOG_LEVEL=4 CFG_ARM64_core=y` , do I need to use `CFG_ARM32_core` but not `CFG_ARM64_core`?

**Comment by jenswi-linaro** [comment]
No you can continue to use Aarch64, the name of the corresponding function there is `elx_irq`

**Comment by MrVan** [comment]
How about set scr el3 fiq bit to 1 to let the interrupt runs into el3?

**Comment by jenswi-linaro** [comment]
No, that doesn't work. We have to be able to mask all interrupts in `S-EL1`.

**Comment by jenswi-linaro** [comment]
BTW have you read this: https://github.com/OP-TEE/optee_os/blob/master/documentation/interrupt_handling.md

**Comment by MrVan** [comment]
@jenswi-linaro I read it. As you know, several ARM64 boards are supported by OPTEE OS, I wonder how they handle the FIQ execption in secure world which is triggered by non secure interrupts.

**Comment by jenswi-linaro** [comment]
Maybe they don't have a GICv3 or have the GIC configured in v2 compat mode and receives the non-secure interrupts as IRQ instead.

**Comment by MrVan** [comment]
After some debug, I found that I always get interrupt 1023 FIQ in optee os. When first runs into fiq execption, the GIC IAR show interrupt 1023.. Strange.. 1023 means no interrupt to ack.

**Comment by jenswi-linaro** [comment]
Are you still using GICv3? If so the it's an non-secure interrupt, if you for some reason want to ack that there's probably some other register to read.

**Comment by MrVan** [comment]
Yeah, I am using gicv3. I wrote a simple v3 driver in optee to only check iar and write eoir.

Actually if it is non secure interrupt, I do not know what interrupt is. The iar shows 1023 and pending hipper? also shows 1023. Do you have ideas what interrupt happends when in secure world?

**Comment by jenswi-linaro** [comment]
From "4.6.2 Interrupt assignment to IRQ and FIQ signals" in http://infocenter.arm.com/help/topic/com.arm.doc.ihi0069c/index.html it look like an FIQ isn't destined S-EL1/0.

In this case it's likely that it's a non-secure timer interrupt.

We don't have many sources for secure interrupts, for demo/test purposes we have configured the secure UART to trigger secure interrupts on some platforms (FVP for instance).

**Comment by MrVan** [comment]
I use the following code to forward the 1023 interrupt to Linux. If not, always met 1023 interrupt at fiq_el0_sp0. I am not sure whether this is non secure timer  interrupt, IAR and HPPIR both shows 0x3ff(1023).
```
diff --git a/core/arch/arm/kernel/thread_a64.S b/core/arch/arm/kernel/thread_a64.S
index abd482b..59d0510 100644
--- a/core/arch/arm/kernel/thread_a64.S
+++ b/core/arch/arm/kernel/thread_a64.S
@@ -361,7 +361,8 @@ irq_el1_sp0:
        .align  7
 fiq_el1_sp0:
        store_xregs sp, THREAD_CORE_LOCAL_X0, 0, 3
-       b       elx_fiq
+       /*b     elx_fiq*/
+       b       elx_irq
        check_vector_size fiq_el1_sp0

        .align  7
@@ -417,7 +418,8 @@ el0_irq_a64:
        .align  7
 el0_fiq_a64:
        store_xregs sp, THREAD_CORE_LOCAL_X0, 0, 3
-       b       elx_fiq
+       b       elx_irq
+       /*b     elx_fiq*/
        check_vector_size el0_fiq_a64

        .align  7
@@ -449,7 +451,8 @@ el0_irq_a32:
        .align  7
 el0_fiq_a32:
        store_xregs sp, THREAD_CORE_LOCAL_X0, 0, 3
-       b       elx_fiq
+       /*b     elx_fiq*/
+       b       elx_irq
        check_vector_size el0_fiq_a32

        .align  7
```

With the upper code, xtest can work well on my platform.

**Comment by jenswi-linaro** [comment]
Yes that's expected, from Secure-EL1/EL0 point of view IRQ and FIQ are swapped with GICv3.

**Comment by chinnabha** [comment]
@jenswi-linaro, if optee doesn't support GICv3, can't we redirect the received IRQs/FIQs (while executing optee) to ATF (which has GICv3 support) via setting SCR_EL3.[IRQ] = 1 and SCR_EL3.[FIQ] =1? I don't know why this option cannot be exercised for the SOCs which need GICv3 support. 

By having SCR_EL3.[IRQ] = SCR_EL3.[FIQ] = 1, I am aware that the core always needs to jump to EL3 irq/fiq handler first (irrespective of which world it is executing in) before it jump further to the appropriate (Secure/Non-secure) ELx world where it can handle that physical interrupt. 

Can't the current ATF bl31 irq/fiq handlers support this kind of complexity? 

**SCR_EL3, FIQ, bit [2]**  Physical FIQ Routing:
0 Physical FIQ while executing at exception levels other than EL3 are not taken in EL3.
1 Physical FIQ while executing at all exception levels are taken in EL3.
**SCR_EL3, IRQ, bit [1]** Physical IRQ Routing:
0 Physical IRQ while executing at exception levels other than EL3 are not taken in EL3.
1 Physical IRQ while executing at all exception levels are taken in EL3.

**Comment by jenswi-linaro** [comment]
The problem with that approach is that the lower exception level can't mask the interrupt.

Another approach would be to just implement some simple almost stubbed GICv3 support in OP-TEE until something more advanced is available.

**Comment by chinnabha** [comment]
Sure Jens that seems to be the way to go for now.

Kindly advise the time frame you guys are planning for GICv3 support in optee. I am also the victim of this. Very lately realized that optee has no support for GICv3. The SOC that I work on is GICv3 based. 

How about other aarch64 guys? All of them on aarch64 and GICv2 combination? This is a kind of surprise to me.

**Comment by jenswi-linaro** [comment]
As far as I know we (Linaro) have no immediate plans for GICv3. Contributions are welcome, I'll review and help with whatever questions. @MrVan seems to be willing to add some GICv3 support, he even seem to have something very basic working judging from what I've seen in this issue.

**Comment by chinnabha** [comment]
That sounds good Jens. Thanks much for your time. As you suggested I will also try to come up with a simple stubbed version for your review.

**Comment by jbech-linaro** [comment]
@MrVan , @chinnabha are you happy with Jens' answers so far? The  reason for asking is that I'm going through all open issues trying to close the ones that have been answered. I think this one has been answered.

**Comment by MrVan** [comment]
Yeah. I am happy with Jens' answer.
