### ISSUE TITLE
library link for TA code

### ISSUE THREAD

**Issue by ggao-inven** [OP-TEE/optee_os#1112]
Hi,
  We have some third party library code that we can only get it in the form of libraries. It also must be run under TEE environment. Is that possible for the dynamic TA or static TA to link dynamic libraries while they are running?
  Thanks.

Ge

**Comment by jforissier** [comment]
Hi @ggao-inven,

Currently, TAs must be fully linked (statically).
- Static TAs are statically linked with the TEE and run in kernel mode. They are a very special case.
- User (-mode) TAs, on the other hand, are loaded dynamically from the REE filesystem, but must be fully linked with no unresolved symbols.

**Comment by ggao-inven** [comment]
Is it possible that a Dynamic TA call another Dynamic TA? This way, we can put third party library as a dynamic TA and call the TA from our TA. Is this possible? I know I can call static TA from Dynamic TA though. Not sure Dynamic TA can call each other inside TEE.
Thanks.

Ge

**Comment by jenswi-linaro** [comment]
Yes, a dynamic TA can call another dynamic TA.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
