### ISSUE TITLE
Question about ARM v7 MON and SVC Modes

### ISSUE THREAD

**Issue by dsblue** [OP-TEE/optee_os#1117]
I would like to know what happens in MON mode versus what happens in Secure SVC mode for ARM v7.  I know that the ARM v7 OPTEE has to handle more in MON mode than on ARM v8 because ARM v8 can use ARM Trusted Firmware.

Secure IRQ and FIQ make sense and I think that user TA code is the only thing that runs in Secure USR mode, but MON and SVC are less clear to me.

**Comment by etienne-lms** [comment]
Hello @dsblue,

Armv8:
- a-tf operates in EL3, get the SMCs (and secure interrupts) and forwards to optee EL1/EL0 the secure service request.
- optee runs in EL1 (optee core: priviledge mode, exceptions) and EL0 (user TA)

Armv7:
- no a-tf: optee implements its own "tz monitor" (see core/arch/arm/sm/*) to replace a-tf runtime services. The optee monitor executes in cpu  mode Monitor, gets the SMCs and secure interrupts and does the a-tf job: switching between secure (optee) context and nonsecure context.
- optee runs in priviledge modes (optee core: svc, expections, system) and user mode (user TA).

Hence optee is design the same way on armv7 and armv8: same entry points (std or fast smc, secure interrupt), same features.

**Comment by dsblue** [comment]
Great, thanks for the explanation.
