### ISSUE TITLE
Should malloc change to calloc in tee_fs_key_manager.c 

### ISSUE THREAD

**Issue by lackan** [OP-TEE/optee_os#1130]
In file tee_fs_key_manager.c, all the crypto context buffer use the malloc action as:
ctx = malloc(ctx_size),
But the same context buffer in tee_svc_cryp.c use the calloc action, should we change the malloc to calloc in file tee_fs_key_manager.c to keep consistent with each other. And I think,  an all zero context buffer is better than undefined one. Because when I want to adapt the hardware accelerator to the LibTom, the hardware descriptor  should be saved in the context, to enable the reentry of crypto init, I should distinguish the first entry with the reentry by the context is zero or not.

**Comment by jforissier** [comment]
Hi @lackan ,

I don't think malloc should be replaced with calloc, at least in the current code. Because, in all the functions that use malloc, there are two options:
- Either the function succeeds, and `ctx` contains valid data (set by `crypto_ops.{mac,cipher,authenc}.init()`)
- Or the function fails and `ctx` is freed.

In any case, there is no way `ctx` can be returned with undefined data, unless I missed something.

Now regarding what you are trying to accomplish (hardware acceleration): don't you have another option to detect first entry than checking if the `ctx` buffer is zero? Seems like a costly operation. Maybe add a flag somewhere?

**Comment by lackan** [comment]
Hi @jforissier ,

For the `crypto_ops.{mac,cipher,authenc}.init()`, the ctx is the input from the upper level, is the only private data be passed to the lower level, we think that it should better have an certain value than the undefined value(random value). Now the init function not use the value in this private data, so malloc is also ok, if in case it's going to be used in the future, the malloc seems not suitable.

**Comment by jenswi-linaro** [comment]
Wouldn't you agree that the point with an init function is to initialize whatever it's fed?

**Comment by prime-zeng** [comment]
My suggestion is to introduce create_ctx, and destroy_ctx instead of the get_ctx_size in the crypto_ops structure, for ctx is just a private data in the lower layer, we should hide the detail from the upper layer, and maybe the ctx contains more than pure memory resource.

**Comment by prime-zeng** [comment]
And following is the usage:
"
ctx = crypto_ops.cipher.create_ctx(...);
crypto_ops.cipher.init(ctx,...);
crypto_ops.cipher.update(ctx,...);
crypto_ops.cipher.final(ctx,...);
crypto_ops.cipher.destroy_ctx(ctx,...);
"

**Comment by jbech-linaro** [comment]
And yet another approach would be to let `crypto_ops.cipher.init`do all initialization, including the allocation of the context. I.e., both create the context (based on the "ALG"), and if the allocation of the context is fine it continues with initializing the actual parameters. Buy doing so you wouldn't even have to have a specific "create ctx" function and you won't need to call `get_ctx_size(...)`.

**Comment by jenswi-linaro** [comment]
@jbech-linaro, agree and `crypto_ops.cipher.final()` would free whatever `init()` has allocated etc.

**Comment by jforissier** [comment]
Sounds good. So we would have:
```C
ctx = crypto_ops.cipher.init(...);
crypto_ops.cipher.update(ctx, ...);
crypto_ops.cipher.final(ctx, ...);
```
 @prime-zeng, @lackan, would that work for you?

**Comment by prime-zeng** [comment]
@jforissier if the cipher.init don't take the ctx as an argument,  how to deal with the double init with the same ctx :
crypto_ops.cipher.init(ctx,...);
crypto_ops.cipher.update(ctx, ...);
crypto_ops.cipher.init(ctx,...);
crypto_ops.cipher.update(ctx, ...);
crypto_ops.cipher.final(...);

**Comment by jforissier** [comment]
I would say we shouldn't allow multiple inits of the same context. I don't think init is currently called several times for the same context, is it? Why would we need to support that? I think the only correct usage is init once, update zero or more times, then final.

**Comment by lackan** [comment]
But in xtest 9179, it tests cipher_init twice of the same context.

**Comment by jforissier** [comment]
@lackan you're right, although that's at the API level (`TEE_Cipherinit()`) not our internal function `crypto_ops.cipher.init()`. I mean we could decide to do otherwise internally... well it would probably not be a good idea ;)

So, now I see how your suggestion makes sense. Le me rephrase... what your are proposing is to separate the allocation of the cryptographic resource (`create_ctx()` and `destroy_ctx()`) and the cryptographic state itself (`init()` to start or re-initialize the operation, `update()`, `final()`).
Could we call just the new functions `create` and `destroy` maybe?

@jbech-linaro, @jenswi-linaro, what do you think?

**Comment by jenswi-linaro** [comment]
Sounds good, then we need to get rid of `get_ctx_size()`. We'll need a `copy()` function to for `syscall_cryp_state_copy()` also.

**Comment by jbech-linaro** [comment]
Sounds good to me too.

**Comment by jforissier** [comment]
@jenswi-linaro yes.
@prime-zeng, @lackan, can you propose something in a pull request? Thanks!

**Comment by lackan** [comment]
@jforissier OK, I will try to pull request.

**Comment by jbech-linaro** [comment]
@lackan , I've have to be honest saying that I've totally forgot this issue. Doesn't sound like a too big thing to do, so meanwhile waiting for the HiKey device, this is maybe something you can look into?

**Comment by lackan** [comment]
@jbech-linaro In this issue, it seems it's not such easy to do as I think before. Yes, it's easy to add create/destroy/copy to the ltc framework, take hash as example, it will be below；
```
crypto_ops.hash.create()
crypto_ops.hash.init()
crypto_ops.hash.update()
crypto_ops.hash.final()
crypto_ops.hash.copy()
crypto_ops.hash.destroy()
```
And for the original reason we want to add create/copy/destroy is that we want to add the hardware resource create/copy/destroy in this API, but at the same time, the libTomCrypt internal will also use the same hash.init/update/final, and it doesn't take the create/copy/destroy into consideration. So it will not work when we use the hardware accelerator, so maybe should change libTomcrypt source code or use other method, but now I don't have any idea about how to do... ;(

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
