### ISSUE TITLE
Do you planing to realize the Trusted UI or other human interface.

### ISSUE THREAD

**Issue by prz999** [OP-TEE/optee_os#114]
Hello everyone, 

I'm thinking about how I can use the optee this day. But I find a real problem. That I can't interact directly  with optee_os. Any information must send through client application. I think It is not very security. As I know GlobalPlatform has defined TUI. So I want to know if you have any plan to realize the TUI or other simple human interface. Because I think it is important. 

Best Regards,
Ruizhi,

**Comment by roman3017** [comment]
Is there any update on implementing TUI after a year?

**Comment by jbech-linaro** [comment]
Hi @prz999 , I'm afraid not, we haven't had time to look into this yet (and the v1.1 spec still haven't been released).

**Comment by bysun2013** [comment]
Hello everyone,

I'm learning the optee and find this issue,I want to implement a simple Trusted UI v1.0.Is there the possibility of implementation? If this is possible,what I should do and I should pay attention to what aspects?
Best Regards,
WeiMin

**Comment by bysun2013** [comment]
Hello everyone,

I'm learning the optee and find this issue,I want to implement a simple Trusted UI v1.0.Is there the possibility of implementation? If this is possible,what I should do and I should pay attention to what aspects?
Best Regards,
WeiMin

**Comment by jenswi-linaro** [comment]
Hi WeiMin,

I'm currently working on TUI 1.0. The end result depends on what reference platform I can integrate with.

Regards,
Jens

**Comment by bysun2013** [comment]
Hi Jens

I have been transplanted OPTEE into Hikey development platform and work on it,Will TUI 1.0 implementation in HIKEY development platform? If it  will be,may I need to wait  for how long time?

Best Regards
WeiMin

**Comment by jenswi-linaro** [comment]
@jbech-linaro can you comment on this?

**Comment by Lucasvo1** [comment]
Does anyone know if there has been any progress on this? I am thinking about using TUI with AOSP.
