### ISSUE TITLE
suspend in TEE

### ISSUE THREAD

**Issue by ggao-inven** [OP-TEE/optee_os#1157]
Hi,
   We are developing some applications that requires system enters suspend and wake up by the interrupts when certain event happens. We are wondering what will happen to the TEE environment when system is suspended.
   The situation is that we will open several TAs and keeps all the TA session opened such that it is faster to send and receive command. Then we want system to enter suspend state. Is this possible? Can system recover TEE environment just like it is before suspend? We are using Juno-Box.
   Thanks.

Best 

Ge Gao

**Comment by jenswi-linaro** [comment]
This should just work. If it doesn't it's a bug.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
