### ISSUE TITLE
Adding #include<math.h> to a TA

### ISSUE THREAD

**Issue by jsherman3** [OP-TEE/optee_os#1158]
Hello, I'm currently using the hello_world example on QEMU and I wanted to modify it a bit. However, whenever I add #include<math.h> to the hello_world_ta.c file and make it, it say's math.h no such directory or file. I was wondering if anyone knew where to add the -lm or if I need to do something else so it compiles.

**Comment by jbech-linaro** [comment]
`math.h` are not included in OP-TEE, remember that we're not using anything from the standard OS by default, everything that you can use is in the optee_os folder, so if for example `$ find . -name "math.h"` gives nothing, then it's not there. That's and easy way to figure out what is there or not if you aren't familiar with all files etc. If you need the math's lib you are referring to, then you have to include it separately.

I would probably have a look at newlib's implementation [here](https://sourceware.org/newlib/libm.html) and there are quite a few (closed) [questions](https://github.com/OP-TEE/optee_os/issues?utf8=%E2%9C%93&q=is%3Aclosed%20%20library%20) that answers how to add a library in OP-TEE.

If you decide to add it and want to see it upstream, feel free to create a pull request for it. The math lib from newlib would eventully fit in `lib/libutils/isoc/newlib`.

**Comment by jsherman3** [comment]
@jbech-linaro, is there any other documentation or examples that explain the API for building apps?

**Comment by jbech-linaro** [comment]
Best example besides that is probably the test suite itself (optee_test). Have a look at the Makefile's there for both the client app (xtest) and the TA's and you will see a pattern. In the past some people also found my "[comcast cryptoapi TA](https://github.com/jbech-linaro/comcast_cryptoapi_ta_example)" useful. I haven't tested it for a while, but there is a bit more text there about what's happening compared to other places. Of course we should not forget about https://github.com/OP-TEE/optee_os/blob/master/documentation/build_system.md which described the overall build system.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by xiaxinkai** [comment]
Hi:
I find a solution. If you are using gcc, maybe you can use gcc math Built-in Functions.
for example:
If you want to use floor() in math.h,
You can use gcc __builtin_floor() to replace it.
Thank you.
