### ISSUE TITLE
OP-TEE on UDOO NEO i.MX6

### ISSUE THREAD

**Issue by kdy1029** [OP-TEE/optee_os#1163]
Hello,
I'm porting OP-TEE to the UDOO Neo i.MX6 Board with Android.
http://shop.udoo.org/usa/catalog/product/view/id/38/s/udoo-neo-extended/category/3/

I basically followed the porting instruction and the Freescale MX6UL EVK guide. 
https://github.com/MrVan/uboot/commit/4f016adae573aaadd7bf6a37f8c58a882b391ae6

When the code loads the OPTEE_ENTRY, it causes an undefined instruction exception. But I checked the memory and the optee.bin still exists in the memory. 

_nonsec_init, arch/arm/cpu/armv7/nonsec_virt.S

+#ifdef CONFIG_ARMV7_TEE
 +	isb
 +
 +	mov	ip, r0
 +	adr	r0, _regs_save
 +	str	ip, [r0]
 +	add	r0, r0, #4
 +
 +	str	sp, [r0]
 +	add	r0, r0, #4
 +
 +	stmia	r0!, {r1-r12}
 +
 +	str	lr, [r0]
 +	adr	lr, end_init_optee
 +
 +	ldr	r0, =OPTEE_ENTRY
 +	movs	pc, r0
 +	b	.

I do not know why it happens. Could you help me?

Thanks,
Daniel

**Comment by MrVan** [comment]
@kdy1029 Please not follow mx6ulevk guide. I plan to drop that code and use new method to boot optee.

You could check `https://github.com/OP-TEE/optee_os/pull/936#issuecomment-240966240` about the boot.

There are still bugs in the patch to support 6q, mainly about PL310, I am debugging it.

**Comment by kdy1029** [comment]
OK, thanks. Hopefully, it will be done soon.
