### ISSUE TITLE
Some doubt about how to protect meta-counter

### ISSUE THREAD

**Issue by lackan** [OP-TEE/optee_os#1164]
Hi,

In newest REE FS implementation,  one file (in the sense of * struct tee_file_operations) maps to one file in REE filesystem, and files in REE sides have following structure:
[ 4 bytes meta-counter]
[ meta-data version 0][ meta-data version 1 ]
[ Block 0 version 0 ][ Block 0 version 1 ]
[ Block 1 version 0 ][ Block 1 version 1 ]
 ...
[ Block n version 0 ][ Block n version 1 ]

The meta-data and the Block {0..n} have been protected by the GCM, so some change on this data, we will  discover the tampering from the tag. But regard to the first 4 bytes meta-counter, how to protect it from others tampering. IMO, if someone increases the meta-counter by one, the meta-data may turn to the older version, but read_and_decrypt meta will not fail, is there something I'm have mistaken?

Thanks.

**Comment by vchong** [comment]
According to https://github.com/OP-TEE/optee_os/pull/1151#discussion_r86720877 anti-rollback protection hasn't been fully implemented yet.

**Comment by lackan** [comment]
@vchong Thanks, get it.
