### ISSUE TITLE
[libtomcrypt] Issue and patch in TEE adaptation for clearing big numbers

### ISSUE THREAD

**Issue by michelemmanuel** [OP-TEE/optee_os#1168]
Hello all,

It seems there is an issue in the TEE adaptation of the libtomcrypt for clearing big numbers.

Issue could be seen in the sequence:
```c
TEE_AllocateTransientObject
TEE_ResetTransientObject
TEE_PopulateTransientObject
```
where `TEE_ResetTransientObject` clears (and not free) the object. Clear mean zero the data. If this object is a big number, the leaf function is:
```c
static void bn_clear(struct bignum *s)
{
        struct mpa_numbase_struct *bn = (struct mpa_numbase_struct *)s;

        memset(bn, 0, bn->alloc);
}
```
corresponding to
```c
static struct bignum *bn_allocate(size_t size_bits)
{
..
        bn->alloc = sz - MPA_NUMBASE_METADATA_SIZE_IN_U32 * sizeof(uint32_t);
..
}
```

The underlying structure describing `struct bignum` is in `lib/libmpa/include/mpalib.h`:
```c
typedef struct mpa_numbase_struct {
	mpa_asize_t alloc;
	mpa_usize_t size;
	mpa_word_t d[];
} mpa_num_base;
```
As we can see, memset fills with zero not only the data, but the metadata and the begin of the datas, instead of zero only the whole data.

Based on OP-TEE `2.2.0`, even with the last commit 36d5a31387f01357077ca74444f3fd5ce1fcc690, a proposed patch:
```diff
diff --git a/core/lib/libtomcrypt/src/tee_ltc_provider.c b/core/lib/libtomcrypt/src/tee_ltc_provider.c
index fda9454..69620c6 100644
--- a/core/lib/libtomcrypt/src/tee_ltc_provider.c
+++ b/core/lib/libtomcrypt/src/tee_ltc_provider.c
@@ -691,7 +691,7 @@ static void bn_clear(struct bignum *s)
 {
        struct mpa_numbase_struct *bn = (struct mpa_numbase_struct *)s;
 
-       memset(bn, 0, bn->alloc);
+       memset(bn->d, 0, bn->alloc);
 }
``` 

Note:
`mpa_numbase_struct.size` is never set in this case, but it is not part of this ticket.

Best regards
Manu

**Comment by jbech-linaro** [comment]
Hi Manu,

Thanks for bringing this to our attention and your findings seems to make sense. Having that said, would you mind to do what Jens said on tee-dev mailinglist? I.e., create a pull request for it (which is how people submit patches to OP-TEE)? 

In short what you would need to do is:

1. Fork optee_os from https://github.com/OP-TEE/optee_os to your local GitHub account.
2. git clone your https://github.com/youraccount/optee_os fork locally.
3. Make changes to the code.
4. git push to https://github.com/youraccount/optee_os
5. Click the "New pull request" green button when having your branch with the fix active.

For more details about this, you can have a look here:
https://github.com/OP-TEE/optee_os/blob/master/documentation/github.md

// Regards Joakim

**Comment by michelemmanuel** [comment]
Fixed with pull request https://github.com/OP-TEE/optee_os/pull/1171.
