### ISSUE TITLE
phys_to_virt for MEM_AREA_RAM_NSEC

### ISSUE THREAD

**Issue by bentau** [OP-TEE/optee_os#1178]
Hello,

It seems that phys_to_virt does not return the correct virtual address. 
I currently use qemu for testing and added 

`register_phys_mem(MEM_AREA_RAM_NSEC, 0x7a620000, 0x80000);`

to core/arch/arm/plat-vexpress/main.c

When the system start I get the following output: 
```
DEBUG:   TEE-CORE:add_phys_mem:260: 0 9 0x00000000 size 0x01400000
DEBUG:   TEE-CORE:add_phys_mem:260: CFG_SHMEM_START 4 0x7fe00000 size 0x00200000
DEBUG:   TEE-CORE:add_phys_mem:260: CFG_TA_RAM_START 3 0x0e200000 size 0x00e00000
DEBUG:   TEE-CORE:add_phys_mem:260: CFG_TEE_RAM_START 1 0x0e100000 size 0x00100000
DEBUG:   TEE-CORE:add_phys_mem:260: 0x7a620000 5 0x7a620000 size 0x00001000
DEBUG:   TEE-CORE:add_phys_mem:260: CONSOLE_UART_BASE 8 0x09000000 size 0x00200000
DEBUG:   TEE-CORE:init_mem_map:398: type va 1 0x0e100000..0x0e1fffff pa 0x0e100000..0x0e1fffff size 0x100000
DEBUG:   TEE-CORE:init_mem_map:398: type va 3 0x0e200000..0x0effffff pa 0x0e200000..0x0effffff size 0xe00000
DEBUG:   TEE-CORE:init_mem_map:398: type va 4 0x0f000000..0x0f1fffff pa 0x7fe00000..0x7fffffff size 0x200000
DEBUG:   TEE-CORE:init_mem_map:398: type va 5 0x0f200000..0x0f200fff pa 0x7a620000..0x7a620fff size 0x1000
DEBUG:   TEE-CORE:init_mem_map:398: type va 8 0x0f400000..0x0f5fffff pa 0x09000000..0x091fffff size 0x200000
DEBUG:   TEE-CORE:init_mem_map:398: type va 9 0x0f600000..0x109fffff pa 0x00000000..0x013fffff size 0x1400000
```

I would assume that when I use 
phys_to_virt(0x7a620000, MEM_AREA_RAM_NSEC)  in a system call it returns 0x0f200000
However, it returns:  0xf220000

Is this a bug or am I doing something wrong?

When I do `core_mmu_add_mapping(MEM_AREA_RAM_NSEC, 0x7a620000, size)` instead of `register_phys_mem` it works correctly and the virtual address is mapped to the correct physical adress.

Thanks for your help!

**Comment by etienne-lms** [comment]
`phys_to_virt(0x7a620000, MEM_AREA_RAM_NSEC)` returns 0x0f220000 as you stated.
This is the right virtual address. 
`core_mmu_add_mapping()` should lead to an equivalent result.

The trace below is confusing, you just found that it is bugged:
```
DEBUG:   TEE-CORE:init_mem_map:398: type va 5 0x0f200000..0x0f200fff pa 0x7a620000..0x7a620fff size 0x1000
```
In fact, physical memory 0x7a620000 was mapped using "section" pages, not 4Kbyte small pages.
So physical range [7A60.0000 7A6F.FFFF] is mapped by virtual  range [0f20.0000 0f2f.ffff].
Hence pa 7A62.0000 => va 0F22.0000.
Why mapping with big sections, not fine grain small pages ? Memory footprint optimizations.
It is true that non memory constraint devices could spend more RAM to fine map core memory.
There are means in optee (core debug, kasan) to verify optee core memory accesses.

We will fix the trace. thanks.
