### ISSUE TITLE
Persistent object xtests fails on rootfs on NFS volume

### ISSUE THREAD

**Issue by msa2** [OP-TEE/optee_os#1181]
I followed the instructions on [rpi3.md](https://github.com/OP-TEE/optee_os/blob/master/documentation/rpi3.md) and configured rpi3 to boot over tftp and with NFS rootfs. Everything seems to be ok, except the xtest complains about persistent objects. The first failing test is:

```
* XTEST_TEE_6001 Test TEE_CreatePersistentObject
o XTEST_TEE_6001.1 Storage id: 00000001
..../rpi3/optee_test/host/xtest/xtest_6000.c:682: fs_create(&sess, file_00, sizeof(file_00), 0x00000002 | 0x00000004, 0, data_00, sizeof(data_00), &obj, storage_id) has an unexpected value: 0xffff3024 = TEE_ERROR_TARGET_DEAD, expected 0x0 = TEEC_SUCCESS
  XTEST_TEE_6001.1 FAILED
```
and the final report on xtest run is:

```
22501 subtests of which 147 failed
69 test cases of which 28 failed
0 test case was skipped
TEE test application done!
```

During the test I do see some files that appear on /srv/nfs/rpi/data/tee/..., so something working, but completely. Odd thing is that on wireshark I don't see any read data operations for NFS, only writes -- linux kernel caching causing that test never actually read data over NFS? Has anyone else tested this?

It is possible that I goofed up the configuration somehow, as I had to tweak the instructions on the web page, before I got the thing even to boot properly -- imho, there are several typos there, and in u-boot environment settings.

**Comment by jbech-linaro** [comment]
Hi Markku,

I'm the one that has mainly been working with RPi3 and NFS. Last time I tried (a couple of weeks ago now) I had no such issue. Having that said, there are a couple of recent patches related to secure storage and eventually you've found a something. Let me try to see if I can replicate the issue.

Regarding kernel caching, you're saying that kernel on RPi3 is the one caching. I haven't checked nor thought about it, sounds pretty strange.

I'll keep you posted.

**Comment by msa2** [comment]
Thanks,

Can you comment on issues relating to web page instructions:

`U-Boot> setenv optee 'usb start; dhcp ${kernel_addr_r} 192.168.1.100:Image; dhcp ${fdt_addr_r} 192.168.1.100:${fdtfile}; dhcp ${atf_load_addr} 192.168.1.100:${atf_file}; run boot_it'
`
I changed 'dhcp' to 'tftp', seemed to make much more sense...

The command uses fdt_addr_r, but in u-boot enviroment I got, "boot_it" refers to 'fdt_adddr_r", which has different value. Couldn't get the boot to work until I used same value (changed fdt_addr_r to fdt_adddr_r in optee definition.

**Comment by sorenb-xlnx** [comment]
Actually, I too, see xtest 6001 failing on ZynqMP since recently using a simple initramfs rootfs (no NFS involved whatsoever). I tried to narrow it down further, but haven't found the time yet to do it right.

The error is
```
root@zynqmp:~# xtest -t regression 6001
Test ID: 6001
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# XTEST_TEE_TEST
#
######################################################

* XTEST_TEE_6001 Test TEE_CreatePersistentObject
o XTEST_TEE_6001.1 Storage id: 00000001
ERR [334] TEES:read_request:468: TEE_IOC_SUPPL_RECV: Invalid argument
```

Bisecting it seems to point at (it's a little difficult to bisect as optee_test and optee_os have some dependencies. Hence I'm not sure how trustworthy this bisect is.):
```
621564da3a94abeb2d68b17601ec1c3063d6f670 is the first bad commit
commit 621564da3a94abeb2d68b17601ec1c3063d6f670
Author: Jens Wiklander <jens.wiklander@linaro.org>
Date:   Tue Oct 18 17:07:19 2016 +0200

    core: REE FS: use new RPC functions

    REE FS is simplified by using the new RPC functions instead of the
    legacy open/read/write/close.

    Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>
    Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

:040000 040000 d067183b9d09c54d235599456bb26af0a58be2e9 71478f33c34dffc2ae8c307ec3486e98fbb58d22 Mcore
```

And one more disclaimer: I haven't updated the kernel side of OP-TEE in a while. Have there been any changes that might cause this?

**Comment by jenswi-linaro** [comment]
Please step up optee_client to latest and make sure that the patch set for the kernel driver is v12.

**Comment by sorenb-xlnx** [comment]
@jenswi-linaro that was apparently my problem. I pulled in the updated kernel driver from https://github.com/linaro-swg/linux/tree/optee and updated optee_client (I was one commit behind): The whole xtest suite passing again. Thanks!

**Comment by msa2** [comment]
Ping? Has anyone else had this problem, or is this only something in my environment?

**Comment by jbech-linaro** [comment]
@msa2 , I just tried using latest and I too have some failures running latest. I suspect that there is a missing patch on the RPi3 setup in one of the gits (as mentioned by Jens), i.e, they are out of sync. I'll try to figure out what is wrong.

**Comment by jbech-linaro** [comment]
Yepps, it was a missing patch in Linux kernel, with that in place:
```
+-----------------------------------------------------
23520 subtests of which 0 failed
69 test cases of which 0 failed
0 test case was skipped
TEE test application done!
root@linaro-developer:~# 
```

I've created a pull request here: https://github.com/linaro-swg/linux/pull/28
If you need it right away, then you can just get the patch and apply to kernel:
```bash
$ cd linux
$ wget https://github.com/linaro-swg/linux/pull/28.patch
$ git am 28.patch
```

As soon as the PR has been merged you should be able to repo sync and get the patch.

**Comment by msa2** [comment]
FYI. I just rebuilt a clean system from repo, installed on SD card. Now I get the same persistent object failures on xtest (no NFS involved). I guess I have to try the patches now.

**Comment by msa2** [comment]
Applied the 28.patch set, xtest passed cleanly.

Conclusion: the current version is apparently broken without this patch set.

**Comment by jbech-linaro** [comment]
@msa2 , the patch has been merged, so know it should work again. Note however, not often, but sometimes things breaks when running latest, like what happened here. Most of the time it gets fixed rather soon. But if you really care about stability, then it's probably better to run the `xyz_stable.xml` manifest instead. Anyhow, thanks for reporting this issue, which I'll close since it has been resolved.
