### ISSUE TITLE
xtest 20022 fail when NS user is 64 bits and secure user is 32bits

### ISSUE THREAD

**Issue by lackan** [OP-TEE/optee_os#1185]
Hi,

When I run xtest 20022 in my environment, which NS user is 64 bits, and secure user is 32 bits, I get a error result. And I found the reason is that, the struct tee_fs_file_info size is 0x84 in the optee-os core, and have the size 0x88 in the NS client side. So the last byte corrupt test will fail. How to fix this problem?

Thanks.

**Comment by jenswi-linaro** [comment]
The problem is likely with the `size_t length` member. It should have a fixed width integer type instead.

**Comment by lackan** [comment]
Yes, and I have test two different fixed width integer type, one is type int, it has the same fail result(core size is 0x84, NS user size is 0x88), and when I change to int64_t, then it's work, all size are 0x88, then all the tests have passed. So the reason why the type int doesn't work may be related to some compile issues?

**Comment by jenswi-linaro** [comment]
Yes, `int` doesn't have a fixed width.

**Comment by lackan** [comment]
Hi, @jenswi-linaro , I don't surely know about why `int` doesn't have a fixed width, can you explain something to me. IMO, `int` will keep 4 bytes width regardless of the 32 or 64 bits system. So the reason is the different struct align between OPTEE core and client? Sorry to ask such simple problem.

**Comment by jenswi-linaro** [comment]
The width of `int` depends on the data model used by the compiler. We're using ILP32 (`int`, `long` and pointers 32 bits wide)  on ARM32 and LP64 (`long` and pointer 64 bits wide, `int` still 32 bits wide) on ARM64.

In both models the width of an `int` is 4 bytes so I suspect that something went wrong when you recompiled.

**Comment by lackan** [comment]
Get it, now I know that `int` can be 64 bits wide in ILP64 data model. You are right, I may not recompile completely before, and when I try again, it works well.

**Comment by jenswi-linaro** [comment]
@lackan are you intending to supply a pull request to fix this?

**Comment by lackan** [comment]
@jenswi-linaro Yes, I will.

**Comment by lackan** [comment]
fixed in #1219
