### ISSUE TITLE
libcap-dev libattr1-dev missing in pre-requisites

### ISSUE THREAD

**Issue by jbech-linaro** [OP-TEE/optee_os#1187]
If you are going to try mount the host folder in OP-TEE/QEMU on an Ubuntu based system, you will need to install two more packages than currently stated in the [pre-requisites](https://github.com/OP-TEE/optee_os#41-prerequisites).
```
sudo apt-get install libcap-dev libattr1-dev
```

Putting it here for now.

**Comment by igoropaniuk** [comment]
I'm going to fix it, but I'm not sure where it's better to add info about these additional pre-requisites, in the common list in 4.1 Prerequisites section, or to 5.9.3 Host-Guest folder sharing in QEMU/QEMUv8 configurations?

**Comment by jbech-linaro** [comment]
It should be 4.1, we keep all our pre-reqs for Debian/Ubuntu based systems there.

**Comment by jforissier** [comment]
Fixed in 88ed56e7.
