### ISSUE TITLE
Secure storage (SQL FS and REE FS): blocks not tied to current meta header

### ISSUE THREAD

**Issue by jenswi-linaro** [OP-TEE/optee_os#1188]
The blocks of a secure storage file aren't tied properly to the meta header. Even if there's no rollback protection for the meta header one can expect that given a certain version of the meta header only one combination of file blocks should be valid. Currently any block of a specific file can be rolled back and also supplied in a different order.

**Comment by jbech-linaro** [comment]
For users of OP-TEE not working directly with Linaro, I can just mention that we have started to look into this issue and if everything goes as planned there will be a fix implemented in OP-TEE 2.4.0, that is about to happen in April 2017. (Internally in Linaro this is handled in SWG-141).

**Comment by jbech-optee-adm** [comment]
Issue has been resolved, see [SFO17-309](https://connect.linaro.org/resource/sfo17/sfo17-309/).
