### ISSUE TITLE
Secure Storage- Disk Encryption

### ISSUE THREAD

**Issue by saravians** [OP-TEE/optee_os#1189]
I am beginner in Optee, I am looking for a way that how multiple files(system or configuration files) can be stored in secure storage or is there any way of disk encryption using Optee. 
saravians

**Comment by jbech-linaro** [comment]
Hi @saravians , OP-TEE has support for Secure Storage, it achieves this by calling the secure storage related functions as defined by GlobalPlatform Internal Core API specification (which you find [here](http://www.globalplatform.org/specificationsdevice.asp)). OP-TEE as such doesn't care about what kind of files you're trying to store. It see anything going to secure storage as a binary blob. So it could be system or configuration files, keys, certificates .. love letters etc. Having that said, pure full disk encryption is not really a use case for secure world. 

I encourage you to read about secure storage in the GP spec I linked to and also have a look [here](https://github.com/OP-TEE/optee_os/blob/master/documentation/secure_storage.md)? If you have more questions to ask after reading that feel free to ask here.

**Comment by saravians** [comment]
Hi Linaro, 
I want to mount a directory (with sub directories and files inside) using Optee. I have seen the Global Platform client and internal core APIs, but could not find any clue, I am wonder whether it is possible to do, and if possible how? Actually I am looking for a way in optee, similar to loop device mechanism to encrypt block devices in  linux.
Regards
saravians

**Comment by jbech-linaro** [comment]
What you're asking for it's not possible to do in a OP-TEE (in any GP TEE I think). As I hinted in my previous comment, to store files using a GP TEE you use use the "Persistent" storage functions. Typically it's the functions you find here: https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/include/tee_api.h#L182-L215

With lots of dedication and work, one could eventually write a TA that works as an overlay for a filesystem. But I don't think I would even try to do that.

Having that said, I absolutely understand that this seems desirable. Having the ability to do what you're asking for could end up with quite interesting Trusted Applications.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
