### ISSUE TITLE
Do you has any docment on how to port this in other armv7 paltform?

### ISSUE THREAD

**Issue by BZH001** [OP-TEE/optee_os#119]
Hi,

I has a armv7 board. I want to port this in my board. But I don't know how I can do that. Could you provide some document about that? Thank you very much.

Best Regards

**Comment by siva43** [comment]
Hi OPTEE experts, 
I have a arm cortex A5 board. I want to port OPTEE on this board. In our board generic uboot is available.I did some research , but i didn't get clear picture on this.Can you please clarify the below queries:
1. Optee loading procedure(Is uboot loads optee or optee loads uboot).
2 .For porting to optee to new platform , what are the required  changes.
3 .Is there any reference for arm cortex A5 ?

It would be very useful , if any body helps.
Thanks in advance.
