### ISSUE TITLE
How many core/processor does optee_os could occupy?

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#1194]
Hi experts,

I'm wondering every time when the normal world switch to the optee_os, how many cores can the OS use? Is there any preference about which core would be occupied by the trusted OS?

Also I want to know under what directory I can find the code about these problems, thank you and hope you have a great thanksgiving!

Shengye

**Comment by jenswi-linaro** [comment]
Any core can be used by OP-TEE. The number of cores that can be used concurrently is limited by the value of `CFG_NUM_THREADS`. You'll find code related to this in `core/arch/arm/kernel/thread*`.

**Comment by SimonWan** [comment]
@jenswi-linaro thank you.
