### ISSUE TITLE
"make toolchains" target fails to download the toolchains

### ISSUE THREAD

**Issue by msa2** [OP-TEE/optee_os#1195]
I attempted to make a clean build as per instructions

```
$ mkdir rpi3
$ cd rpi3
$ repo init -u https://github.com/OP-TEE/manifest.git -m rpi3.xml
$ repo sync -j3
$ cd build
$ make toolchains
```
at which point it fails while untarring `../toolchains/gcc-linaro-aarch64-linux-gnu-4.9-2014.08_linux.tar.xz`

```
toolchains$ file *.xz
gcc-linaro-5.3-2016.02-x86_64_aarch64-linux-gnu.tar.xz:   XZ compressed data
gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz: XZ compressed data
gcc-linaro-aarch64-linux-gnu-4.9-2014.08_linux.tar.xz:    HTML document, ASCII text
```
...and yes, that .xz file is really HTML file (at least as it appears in my directory)

**Comment by msa2** [comment]
Actually, at end of this html, there is...
```
<div id="content">
  
Page not found: /14.08/components/toolchain/binaries/gcc-linaro-aarch64-linux-gnu-4.9-2014.08_linux.tar.xz

</div>
<div id="footer">
  Running <a href="https://git.linaro.org/infrastructure/linaro-license-protection.git">linaro-license-protection</a> <a href="https://git.linaro.org/in
frastructure/linaro-license-protection.git/commit/4758205">4758205</a>.
</div>
</body>
</html>

```

**Comment by vchong** [comment]
Sorry the file got archived on the server. We will fix it asap but in the meantime, in `build/toolchain.mk`, please change:

`http://releases.linaro.org/14.08/components/toolchain/binaries/${LEGACY_AARCH64_GCC_VERSION}.tar.xz`

to

`http://releases.linaro.org/archive/14.08/components/toolchain/binaries/${LEGACY_AARCH64_GCC_VERSION}.tar.xz`


and try again.
