### ISSUE TITLE
GCC6 build errors

### ISSUE THREAD

**Issue by omnium21** [OP-TEE/optee_os#1200]
I'm attempting to build using GCC6 [1] and seeing two problems as shown in the output below:

```bash
  CC      out/arm-plat-vexpress/core/lib/libtomcrypt/src/tee_ltc_provider.o
core/lib/libtomcrypt/src/mpa_desc.c: In function 'deinit':
core/lib/libtomcrypt/src/mpa_desc.c:62:2: warning: dereferencing type-punned pointer might break strict-aliasing rules [-Wstrict-aliasing]
  mpa_free_static_temp_var((mpanum *) &a, external_mem_pool);
  ^~~~~~~~~~~~~~~~~~~~~~~~
core/lib/libtomcrypt/src/mpa_desc.c: In function 'montgomery_reduce':
core/lib/libtomcrypt/src/mpa_desc.c:492:2: warning: dereferencing type-punned pointer might break strict-aliasing rules [-Wstrict-aliasing]
  if (init((void **)&tmp) != CRYPT_OK) {
  ^~
  CC      out/arm-plat-vexpress/core/lib/libtomcrypt/src/ciphers/aes.o
  CC      out/arm-plat-vexpress/core/lib/libtomcrypt/src/ciphers/aes_tab.o
  CC      out/arm-plat-vexpress/core/lib/libtomcrypt/src/ciphers/des.o
core/lib/libtomcrypt/src/ciphers/aes_tab.c:1049:22: warning: 'rcon' defined but not used [-Wunused-const-variable=]
 static const ulong32 rcon[] = {
                      ^~~~
core/lib/libtomcrypt/src/ciphers/aes_tab.c:264:22: warning: 'Td4' defined but not used [-Wunused-const-variable=]
 static const ulong32 Td4[256] = {
                      ^~~
core/lib/libtomcrypt/src/ciphers/aes_tab.c:197:22: warning: 'TD0' defined but not used [-Wunused-const-variable=]
 static const ulong32 TD0[256] = {
                      ^~~
core/lib/libtomcrypt/src/ciphers/aes_tab.c:127:22: warning: 'Te4' defined but not used [-Wunused-const-variable=]
 static const ulong32 Te4[256] = {
                      ^~~
core/lib/libtomcrypt/src/ciphers/aes_tab.c:59:22: warning: 'TE0' defined but not used [-Wunused-const-variable=]
 static const ulong32 TE0[256] = {
                      ^~~
```
Building with GCC5 is okay.

[1] http://releases.linaro.org/components/toolchain/binaries/6.2-2016.11/arm-linux-gnueabihf/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz

**Comment by omnium21** [comment]
BTW, I tested this against these two points in the GIT history:

8daf3da  2016-11-24  core: fix stack setup at secondary core entry      [Etienne Carriere]
9eece61  2016-11-15  core: fix ta_private_vmem support  [Etienne Carriere]

Defining NOWERROR=1 works okay on ARM's FVP AEMv8 models.

**Comment by jbech-linaro** [comment]
Hi Ryan,

In short gcc6.x isn't supported in OP-TEE and I too started to play with GCC6.x a while ago, I started by solving the most obvious ones and then I suppressed some other that I didn't know how to solve to for moment:
https://github.com/jbech-linaro/optee_os/commits/gcc6

The thing with upgrading gcc version is that doing the upgrade as such is pretty straight forward, but it's a major pain to try it out on all supported hardware. Last time I stepped up from 4.x to 5.x I also got hit by a few (non OP-TEE) trees used in our repo setup that didn't support 5.x at all yet (relocation stuff).

Having that said, to go for gcc6.x, we we need to also
1. solve the ones I suppressed on my branch
2. we would need to update, our [toolchain makefile](https://github.com/OP-TEE/build/blob/master/toolchain.mk)
3. need to test on all [supported devices](https://github.com/OP-TEE/optee_os#3-platforms-supported). 
4. Then there are other builds that we normally don't build within the group, AOSP, OE, RPK etc.

I definitely think we should step up to gcc6.x, the sooner the better, but with all devices supported it has become much harder, so I think this has to be planned for a certain OP-TEE release. I'll take not of this and see if we can make it happen in OP-TEE 2.4.0 (after BUD17).

// Joakim

**Comment by omnium21** [comment]
Hi Joakim,
Thanks for the reply.
I agree that moving GCC versions is not straight-forward.  But in an attempt to move to a more recent Linaro version after 15.05/GCC4.9 was archived, I was pushing to see how far I could go.  ARM-TF has similar issues with GCC6, so I know I won't be able to move past GCC5 for a while.

**Comment by suihkulokki** [comment]
Using -Werror on release builds is frowned upon, precisely because it causes build failures when toolchain gets upgraded/changed. What Qemu does is enable -Werror when building from git (wen .git/ directory exists) but for builds from release tarballs -Werror is not used. And the behaviour can be overrided with --enable-werror / --disable-werror flags.

**Comment by jenswi-linaro** [comment]
`-Werror` can be disabled by defining `NOWERROR` when building OP-TEE.

**Comment by jbech-linaro** [comment]
Handled internally at Linaro in: SWG-211.

**Comment by jbech-linaro** [comment]
All fixes etc has been merged to all relevant repositories (and the internal SWG-211 has been resolved). Because of this I'll close this issue. Thanks!
