### ISSUE TITLE
Is running two xtest in parallel supposed to work?

### ISSUE THREAD

**Issue by msa2** [OP-TEE/optee_os#1201]
Just for a stress test (rpi3), I started two xtest processes in parallel. Does not seem to work too well, is it supposed to work? I guess this is not really an issue if there is something xtest that explicitly prevents parallel use.

Got following final reports from the two tests
```
22731 subtests of which 2126 failed
69 test cases of which 18 failed
0 test case was skipped
TEE test application done!

23133 subtests of which 1022 failed
69 test cases of which 12 failed
0 test case was skipped
TEE test application done!
```

Then running xtest alone (without reboot), resulted

```
22663 subtests of which 81 failed
69 test cases of which 16 failed
0 test case was skipped
TEE test application done!
```
...seems that the parallel runs "broke the driver"?

**Comment by jenswi-linaro** [comment]
Running two xtest processes in parallel will not work very well as it's likely to both run out of resources (memory) in some tests cases and cause secure storage conflicts in others. I guess most of the failed cases in the last run was in the 6000-series. It wouldn't surprise me if there's some real errors too as we usually don't test (and fix real errors) in this way.

**Comment by msa2** [comment]
> ...seems that the parallel runs "broke the driver"?

Seems that problem is just a "dirty" /data directory. Parallel test didn't clean it, and subsequent lone test does not like existing stuff in there.

**Comment by jforissier** [comment]
@msa2 exactly. `xtest` assumes a "clean" environment to start with.

**Comment by msa2** [comment]
So no real issue then.

However, the resulting xtest fail was rather "sticky" to clean. I'm using NFS root and

- removing files from NFS server didn't remove the fails
- rebooting rpi3 didn't remove the fails (data also cleared)
- xtest passed after I rebooted both the NFS server and rpi3

I've no idea what was going on. Issue can be closed, but someone should  keep an open eye for the cause of this sticky state (if it can be replicated by others).

**Comment by etienne-lms** [comment]
@msa2: as stated, `xtest` is quite sticky on test environment. running and aborting `xtest` may leave nonvolatile data in a unexpected state from `xtest` tool view. Actually removing all secure storage content data (`rm -rf /data/tee`) and operating a clod boot should result in a clean test setup.
If you have secure data. a backup before test is preferred...
Below are some details on the test, in case informative to anyone.

Some of the 6xxx, the 10xxx and 20xxx and the benchmark/100x act on secure storage. These tests should better be run from clean storage state. Secure storage default path is `/data/tee/` but one can set it from [sql_fs.c#L413](https://github.com/OP-TEE/optee_client/blob/master/tee-supplicant/src/sql_fs.c#L413) for the SQLite based secure storage path.  The REE based storage is [hard coded](https://github.com/OP-TEE/optee_client/blob/master/tee-supplicant/src/tee_supp_fs.c#L52).

Test serie 1008 creates/destroys a TA image file. Test 1008 includes [a specific path trick on loaded TA base path](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/xtest_1000.c#L508).

To answer initial question: several un-argument-ed `xtest` cannot be run in parallel.
Use test 1013 to stress multi-threading of load/invokation of TAs:  `xtest _1013`
Use test 6016 to stress multi-threading on secure storage:  `xtest _6016`
Most basic TA load/invoke/close test is the `xtest _1004`.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
