### ISSUE TITLE
SPI Test for HiKey: Size of Tx seems to be limited to first transaction?

### ISSUE THREAD

**Issue by gitfineon** [OP-TEE/optee_os#1208]
Hey @vchong ,
are you aware of this behavior or can you give me a hint how to fix it?

Adding a second transaction to **spi_test.c** with longer arrays fails after sending number of bytes of the first array:
```
	uint8_t tx_string[8] = {"opteespi"};
	uint8_t rx_string[8] = {0};
	size_t len_string = 8;
```

```
	DMSG("SPI test to send a string\n");
	platform_pl022_data.chip.ops->txrx8
		(&platform_pl022_data.chip, tx_string, rx_string, len_string, &num_rxpkts);
	for (i = 0; i < num_rxpkts; i++)
		DMSG("rx[%zu] = 0x%x\n", i, rx_string[i]);
```
The logic analyzer shows SPI_ENABLE is only LOW for the first 4 bytes, MOSI sends all 8 bytes. There is no obvious problem if the first array had 16 bytes, but I don't see any common context because of using separate variables.

Diggin' deeper without interruption of DMSG output:
```
	uint8_t tx[4] = {0x01, 0x80, 0x00, 0x42};
	uint8_t tx_string[2] = {"2b"};
	uint8_t tx_long[8] = {"8 bytes"};
	uint8_t rx[4] = {0};
	uint8_t rx_string[2] = {0};
	uint8_t rx_long[8] = {0};
	size_t j, num_rxpkts, len = 4, len_string = 2, len_long = 8, num_rxpkts_long;
```
```
	pl022_start(&platform_pl022_data);

	for (j = 0; j < 2; j++) {
		platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip,
						tx, rx, len, &num_rxpkts);
		udelay(20);
	}
	udelay(20);
	
	platform_pl022_data.chip.ops->txrx8
		(&platform_pl022_data.chip, tx_string, rx_string, len_string, &num_rxpkts);
	udelay(40);
	
	platform_pl022_data.chip.ops->txrx8
		(&platform_pl022_data.chip, tx_long, rx_long, len_long, &num_rxpkts_long);
	udelay(40);

	for (j = 0; j < 2; j++) {
		platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip,
						tx, rx, len, &num_rxpkts);
		udelay(20);
	}
	udelay(20);

	for (j = 0; j < 2; j++) {
		platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip,
						tx, rx, len, &num_rxpkts);
		udelay(20);
	}
	udelay(40);

	pl022_end(&platform_pl022_data);
```
![logic_025_crop](https://cloud.githubusercontent.com/assets/11716650/20795749/0fe26e9a-b7d3-11e6-82b3-4941b2bd6b3e.png)
Maybe it helps to see the problem in more detail
![logic_026_crop](https://cloud.githubusercontent.com/assets/11716650/20795748/0fdc7634-b7d3-11e6-8192-381035d3a40a.png)

**Comment by vchong** [comment]
@gitfineon Thanks for helping to test again and reporting the issue!

Several issues:
1. Lack of documentation.
`*num_rxpkts` is supposed to hold the number of max packets to receive.
Re: https://github.com/OP-TEE/optee_os/pull/905#r69943362.

2. Bug from code in `spi_test` being a victim of 1 above.
In https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/spi_test.c#L57, we should have set `num_rxpkts = 3`.

Will submit a patch for 1 and 2. In the meantime, can you adjust `num_rxpkts_xxx` as necessary in your additional test code and try again?

3. Probably the most important of all, there seems to be noise interrupting with the proper behavior of SPI_ENABLE. I would like to rule out the pl022 driver as the cause by:

3.1 Comment out https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/main.c#L208.
This will ensure nothing in OP-TEE has touched any SPI related registers and settings.

3.2 Boot to linux, run some userland spi tests (preferably those that continuously send long streams of data - probably 8 or more bytes should be enough) and check for noise in SPI_ENABLE.
If there is noise, then we can rule out the pl022 driver.

In my experiment using http://learn.linksprite.com/96-board/sliding-rheostat/, I do see noise (the pin-like spikes in the attached image, above the Error label in blue )..

![screen shot 2016-12-02 at 6 00 39](https://cloud.githubusercontent.com/assets/7334750/20828178/7d6f57ac-b8b9-11e6-8b67-6e23e65d8255.png)

..but it would be nice if others (you? :P) can verify it on their board/setup as well.

Thanks!

**Comment by vchong** [comment]
Forgot to mention that the noise doesn't happen on every cycle of transfer. There are some clean cycles too.

**Comment by vchong** [comment]
@gitfineon Submitted PR https://github.com/OP-TEE/optee_os/pull/1215.

**Comment by gitfineon** [comment]
There are no spikes using linux kernel spidev with a simple test tool which tries to detect a device but doesn't get a answer because atm there is no device connected.
![selection_027](https://cloud.githubusercontent.com/assets/11716650/21013586/fc8bc12e-bd5a-11e6-9f5e-ac56bea35cb9.png)
![selection_028](https://cloud.githubusercontent.com/assets/11716650/21014360/fc139c0a-bd5d-11e6-8b1d-846f9f51701c.png)

Nice to see you are using the same logic analyzer ;-)
I'll rebase my optee_os branch and check if your recommendations solved the problem

**Comment by gitfineon** [comment]
Hey @vchong ,
I tried to analyze the behavior, and it is not the first transaction it is the smallest transaction which sets the limit.
You can reproduce the following trace by adding
```
#define PKTS_MAX 8

void spi_test(void)
{
	...
	uint8_t tx[4] = {0x01, 0x80, 0x00, 0x42};
	uint8_t tx_string[2] = {"2b"};
	uint8_t tx_long[PKTS_MAX] = {"8 bytes"};
	uint8_t rx[4] = {0};
	uint8_t rx_string[2] = {0};
	uint8_t rx_long[PKTS_MAX] = {0};
	size_t j, num_rxpkts = PKTS_MAX, len = 4, len_string = 2, len_long = PKTS_MAX;

	...
	pl022_start(&platform_pl022_data);

	udelay(60);

 /* 2 x 4 Bytes */
	for (j = 0; j < 2; j++) {
		udelay(20); 
		platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip, tx, rx, len, &num_rxpkts);
	}

	udelay(60);

 /* 1 x 2 Bytes */	
	platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip, tx_string, rx_string, len_string, &num_rxpkts);

	udelay(60);
	
 /* 1 x 8 Bytes */	
	platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip, tx_long, rx_long, len_long, &num_rxpkts);

	udelay(60);

 /* 2 x 4 Bytes */
	for (j = 0; j < 2; j++) {
		udelay(20);
		platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip, tx, rx, len, &num_rxpkts);
	}

	udelay(60);

 /* 2 x 4 Bytes */
	for (j = 0; j < 2; j++) {
		platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip, tx, rx, len, &num_rxpkts);
		udelay(20);
	}

	udelay(60);

	pl022_end(&platform_pl022_data);

```
![saleae logic software_029_comment](https://cloud.githubusercontent.com/assets/11716650/21152067/1e8971be-c165-11e6-896e-448f64b9ee99.png)

You mentioned the function should receive the same number of bytes as send but instead it holds the number of bytes received within the last transaction. [`*num_rxpkts = j;`](https://github.com/OP-TEE/optee_os/blob/master/core/drivers/pl022_spi.c#L206)

In combination with the counting of `j` this can be only a decreasing `num_rxpkts`. Is that the behavior you would expect? What about using `j < *num_txpkts` in the receive loop? Or maybe a kind of guarding should be implemented to prevent setting `cs_gpio_pin` to HIGH before transmit is done completely.

Why do we need to check `j < *num_txpkts` twice? In the first run `j = 0` and therefore it is smaller. But it is possible to limit the number of packages you want to receive by setting `num_rxpkts` before calling `txrx`. Than you also limit the packages to send because of release chip select as soon as the maximum number of packages are received.

**Comment by vchong** [comment]
Hi @gitfineon Thanks as usual for helping to test and analyze!

I think you misunderstood my previous comment. Sorry if I wasn't being too clear. `*num_rxpkts` is an `inout` variable, with `in` being the maximum number of packets to receive and `out` the number of packets actually received. As such, `*num_rxpkts` needs to be set (to equal to `num_txpkts`) **every time** before calling (or going **in**to) `txrx`, otherwise the `rx` part of the algorithm can/will be messed up from the previous call. So, there is a bug [here](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/spi_test.c#L57,). `*num_rxpkts` should be set to 3. It should not be uninitialized. And your code should also look like this:

```
 /* 2 x 4 Bytes */
	for (j = 0; j < 2; j++) {
		udelay(20); 
		num_rxpkts = len; //ADDED THIS
		platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip, tx, rx, len, &num_rxpkts);
	}

	...
 /* 1 x 2 Bytes */	
	num_rxpkts = len_string; //ADDED THIS
	platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip, tx_string, rx_string, len_string, &num_rxpkts);

	...	
 /* 1 x 8 Bytes */	
	num_rxpkts = len_long; //ADDED THIS
	platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip, tx_long, rx_long, len_long, &num_rxpkts);

	...
 /* 2 x 4 Bytes */
	for (j = 0; j < 2; j++) {
		udelay(20);
		num_rxpkts = len; //ADDED THIS
		platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip, tx, rx, len, &num_rxpkts);
	}

	...
 /* 2 x 4 Bytes */
	for (j = 0; j < 2; j++) {
		num_rxpkts = len; //ADDED THIS
		platform_pl022_data.chip.ops->txrx8(&platform_pl022_data.chip, tx, rx, len, &num_rxpkts);
		udelay(20);
	}
```

However, with all that said above, in principal you're right about using `j < *num_txpkts` in the receive loop and not having to check `j < *num_rxpkts` twice. In summary, this is because SPI always receive the same number of bits transmitted, so `num_rxpkts != num_txpkts` is not a valid use case and hence we don't need both. See discussion [here](https://github.com/OP-TEE/optee_os/pull/1215#discussion_r90820299) for details.

I plan to submit a patch to remove `num_rxpkts` and `num_txpkts` altogether and just use `num_pkts`. This is in line with most other implementations out there. Do you agree with this change?

**Comment by gitfineon** [comment]
Yes, I think that would be more simple to understand! But then the following questions came up in my mind:

1. Do we still need the `num_txpkts` to specify length of data to be transmitted as parameter for txrx function?
  * No, because same size
  * Yes, if we want to specify send 2Bytes but receive 4Bytes (Is that a possible use case, we can not handle in a higher level? No!)

2. Why do we have to split up between 8 and 16 bytes?
  * The function `pl022_configure` is responsible to check if data size is configured and supported. Therefore we can use configured data_size to choose appropriate I/O function, right?
  * Is it a possible use case to switch `data_size` from transmission to transmission? I don't think so.
  * There is a comment about io.h is going to be deprecated, better use `mmio.h` (and switch all addr/val tuple in the write calls)

3. Wouldn't it be great to also access start, end and configure via generic `ops` like  `spi_data.chip.ops->configure()` ...

Great job so far @vchong ! And by the way ... there are no spikes any more and a can not reproduce them *confused*

**Comment by vchong** [comment]
> Yes, if we want to specify send 2Bytes but receive 4Bytes (Is that a possible use case, we can not handle in a higher level? No!)

The code was written to cover this use case, which made it a bit more complicated and prone to the issues you're experiencing if not careful with `num_rxpkts`, but the links provided above showed that this is not a valid use case, so we should just remove and simplify things.

> Why do we have to split up between 8 and 16 bytes?

The intent was to make it easier to code, easier to review/understand and harder to make mistakes. Technically, they can be combined but void pointers will have to be used and casted to either `uint8_t` or `uint16_t` in several places based on the data size specified. Is that your preference to have them combined?

> There is a comment about io.h is going to be deprecated, better use mmio.h (and switch all addr/val tuple in the write calls)

Where is this comment?

> Wouldn't it be great to also access start, end and configure via generic ops

Yes. These are part of several other things on the to-do list.

Thanks!

**Comment by gitfineon** [comment]
Sorry in my local branch I use [mmio.h](https://github.com/ARM-software/arm-trusted-firmware/blob/master/include/lib/mmio.h) from arm-trusted-firmware and I forgot that this it is not from master. I would suggest to use the same `mmio.h`, because this implementation does always use `addr` as first parameter, but this is a separate topic to simplify porting.
I misread the comment, which is only for the macro:
https://github.com/OP-TEE/optee_os/blob/master/core/include/io.h#L35

A simple solution to make read and write operations more generic would be, to use a wrapper function e.g. `mmio_write(uintptr_t addr, UINT_MAX_T value, size_t data_size)` which internally checks current `data_size` and casts value to the right size. 

If we don't need to change size on runtime, it may be possible to improve performance using a define like `DEFAULT_DATA_SIZE`
```
mmio_write(uintptr_t addr, UINT_DEF_T value){
#if DEFAULT_DATA_SIZE == 16
	mmio_write_16(addr, value);
#else
	mmio_write_8(addr, value);
#endif 
}
```
What is your opinion?

**Comment by vchong** [comment]
Sorry but I'm a bit confused. I thought we were talking about spi tx and rx, so why the sudden change to mmio read and write which aren't really directly related?

**Comment by gitfineon** [comment]
You're right that's off topic now. The only relation is to merge 8 and 16 bit functions for txrx, tx, rx because they are identical.

**Comment by vchong** [comment]
@gitfineon 

I decided to keep the 8 and 16 bit functions separate, else the combined function will look like below, be hard to maintain and be error prone. Hope you agree.

```
static void pl022_txrx(struct spi_chip *chip, void *wdat, void *rdat, size_t num_pkts)
{
	size_t i = 0;
	size_t j = 0;
	uint16_t *wp = (uint16_t *)wdat;
	uint16_t *rp = (uint16_t *)rdat;
	struct pl022_data *pd = container_of(chip, struct pl022_data, chip);

	if (!num_pkts) {
		EMSG("*num_pkts = 0!\n");
		return;
	}

	if (wp) {
		while (i < num_pkts) {
			if (read8(pd->base + SSPSR) & SSPSR_TNF) {
				/* tx 1 packet */
				if (pd->data_size_bits == 8) {
					write8((uint8_t)wp[i/2], pd->base + SSPDR);

					/* if num_pkts is odd, break after only 1 tx */
					if (i+1 == num_pkts) {
						DMSG("breaking out of ODD\n");
						break;
					}

					write8((uint8_t)(wp[i/2]>>8), pd->base + SSPDR);
					i+=2;
				}
				else
					write16(wp[i++], pd->base + SSPDR);
			}
		}
	}

	if (rp) {
		while (j < num_pkts) {
			if (read8(pd->base + SSPSR) & SSPSR_RNE) {
				/* rx 1 packet */
				if (pd->data_size_bits == 8) {
					rp[j/2] = (uint16_t)read8(pd->base + SSPDR);

					/* if num_pkts is odd, break after only 1 rx */
					if (j+1 == num_pkts) {
						DMSG("breaking out of ODD\n");
						break;
					}

					rp[j/2] |= (uint16_t)(read8(pd->base + SSPDR) << 8); 
					j+=2;
				}
				else
					rp[j++] = read16(pd->base + SSPDR);
			}
		}
	}
}
```

It would be easier if I could perform function arithmetic on void pointers like in Linux, but optee_os uses -Werror so it will not compile.
