### ISSUE TITLE
build error : arm-linux-gnueabihf-gcc: ELF: not found

### ISSUE THREAD

**Issue by cxdinter** [OP-TEE/optee_os#1216]
Hi,
I am trying to download op-tee source code and compile it.
 Befor 'make all run', everything is ok.
When I execute 'make all run' command in consol, I always met below error:
```bash
**/home/yfve/Projects/Security/optee/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-gcc: 1:
/home/yfve/Projects/Security/optee/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-gcc: ELF: not found**
```
But, I confirm : toolchanis installed OK, I can find arm-linux-gnueabihf-gcc in that folder.

Anyone_ can help me to fix this issue?
I checked some old topics which related with similar build error, they all said need install some librarieds(lib32z1, lib32ncurses5, lib32bz2-1.0), but when I use apt-get to install these libraries, always met 'unable to locate package'.

Note : 
```bash
     I am using Ubuntu14.04 LTS 32 bit system ( 14.04.1-Ubuntu SMP Thu Jan 15 17:45:15 UTC 2015 i686 i686 i686 GNU/Linux).
     But the CPU is 64 bit ( Pentium(R) Dual-Core CPU E5300 @ 2.60GHz × 2).
```

**Comment by jbech-linaro** [comment]
All pre-reqs installed as described in the README.md? Even though you said toolchain is installed OK are you 100% sure that worked? Did you actually download the toolchains correctly, i.e, `make toolchains`? What happens if you simply call `arm-linux-gnueabihf-gcc` without any arguments at all? It should reply like this:
```bash
$ ./arm-linux-gnueabihf-gcc
arm-linux-gnueabihf-gcc: fatal error: no input files
compilation terminated.
```

**Comment by cxdinter** [comment]
Hi Jbech,
    sure. I followed the guide step by step. installed many libraries which decribed in session4.1, instaled repo and done 'repo sync', then done 'make toolchains'.

    When I simpley call arm-linux-gnueabihf-gcc, below is the output:

    ~/Projects/Security/optee/toolchains/aarch32/bin$ ./arm-linux-gnueabihf-gcc 
**bash: ./arm-linux-gnueabihf-gcc: cannot execute binary file: Exec format error**

**Comment by jforissier** [comment]
Are you using a 32-bit distro maybe? AFAIK, `arm-linux-gnueabihf-gcc` is a x86_64 binary.

**Comment by jbech-linaro** [comment]
Ah, I know what the problem is, the AArch32 toolchain is compiled for x64.

**Comment by cxdinter** [comment]
Hi Jbech,
     Could you please tell me how to fix it?
     maybe I need re-config some parameter, and do 'make toochain' again?

**Comment by jbech-linaro** [comment]
Basically, the AArch32 toolchain that you get is a 64bit binary:
``` bash
$ file arm-linux-gnueabihf-gcc
arm-linux-gnueabihf-gcc: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=6f4ca271f87a254c36c9c2dd1d998aad784e5ebd, not stripped
```

Seems like you're the first one we know of that are trying to run our setup on a pure 32-bit environment.  Unfortunately I cannot find and 32bit toolchain here:
http://releases.linaro.org/components/toolchain/binaries/5.3-2016.02/arm-linux-gnueabihf/

If you find a 32bit ARM toolchain, extract that into the `<optee_root>/toolchains/aarch32` folder and try again (delete or move the old folder first). An alternative would be to try to just simply apt-get search (`apt-cache search arm-linux-gnueabihf`  ... and installed a suitable if found) for an ARM toolchain, install that using apt-get. But if you go that path, then you will probably also going to need to update the parameters here so they find your toolchain:
https://github.com/OP-TEE/build/blob/master/common.mk#L90-L93

Any special reason for running 32bit OS when you have 64bit CPU?

**Comment by cxdinter** [comment]
Hi Jbech,
     Thank you. I will try your suggestion and let you the result.
      There are no special reason why I installed 32bit OS. I just copied one Ubuntu14.04 install package from my collegue and installed on my computer. I haven't checked it is 32bit or 64bit untill today....... 

    Anyway, is there any plan to support 32bit ARM toolchain? Yes, I am the first one who meet this type issue, but I don't think I am also the last one..

**Comment by jbech-linaro** [comment]
No, no plans really to support that. If you however get it to work and can update the makefiles etc to support it, then we of course would consider merging your patches. Btw, I found a toolchain that you can try:
http://releases.linaro.org/components/toolchain/binaries/latest-5/arm-linux-gnueabihf/gcc-linaro-5.3.1-2016.05-i686_arm-linux-gnueabihf.tar.xz

I think if you just delete `<optee_root>/toolchains/aarch32` and extract that toolchain to the same dir, then it will probably just work (on QEMU). I.e, you should not need to make any further changes to makefiles etc.

**Comment by cxdinter** [comment]
Hi Jbech,

Thank you very much!
After download your suggest link, now 'make all run' working normally.

Anyway, I still suggest you add some description in README.md file for this situation, it will help later users.

Thank you again. This topic can be closed.
Now I will start really op-tee study/work, if I have other concern/suggestion, I will come back here again.

**Comment by jbech-linaro** [comment]
Hi,

I will add it to our FAQ (op-tee.org). I updated the FAQ last week, but it has not been published on the web page yet. I'll add this issue too.
