### ISSUE TITLE
Error in documentation/debug.md

### ISSUE THREAD

**Issue by holmastoo** [OP-TEE/optee_os#1220]
In the chapter 1.2, the source https://releases.linaro.org/14.09/components/toolchain/binaries/gcc-linaro-arm-none-eabi-4.9-2014.09_linux.tar.xz  is unavailable.

**Comment by vchong** [comment]
@holmastoo Sorry, it's been moved to https://releases.linaro.org/archive/14.09/components/toolchain/binaries/gcc-linaro-arm-none-eabi-4.9-2014.09_linux.tar.xz. We will update the doc. Thanks!
