### ISSUE TITLE
Trusted Application execution on JUNO

### ISSUE THREAD

**Issue by aminusamine** [OP-TEE/optee_os#1229]
Hello, 

I have an ARM JUNO board on which i installed OP-TEE by following the steps i found on this github. Then i run xtest on it to check the systems the results are : 
```bash
23475 subtests of which 0 failed
67 test cases of which 0 failed
0 test case was skipped
```

Then, i wanted to run an application i have successfully execute on OP-TEE FVP. I imported the Client Application from the folder Host and the TA from the out folder. 

Then, i copied them on the board in the /bin folder and the /lib/optee-armtz respectively. Then i launched the client application and i have this error message : 

```bash
root@FVP:/ comcast_crypto_demo 
Opening the session to Comcast RDK TA
Opening the session was ok !!!!
Invoking a function in Comcast RDK TA
comcast_crypto_demo: TEEC_InvokeCommand failed with code 0xffff000c origin 0x1
```

I checked the error, it is "out of memory". I don't understand what i did wrong. 

Can someone help me with this please ?

Best Regards.

**Comment by jforissier** [comment]
Hello @aminusamine,

Origin 0x1 is `TEEC_ORIGIN_API` which indicates that the out-of-memory condition originates from the client library (libteec). If I'm not mistaken, this can only be a failure to allocate shared memory (buffer used to pass parameters between normal and secure world). This memory is allocated by the linux driver, from a pool that is reserved in the device tree and described by OP-TEE (see `core/arch/arm/plat-vexpress/platform_config.h`,  `CFG_SHMEM_START` and  `CFG_SHMEM_SIZE`).
What puzzles me, is that FVP and Juno have the same shared memory size. So unless you changed this define, the behavior should be the same I suppose.

I suggest adding some debug traces to `libteec/src/tee_client_api.c` to better understand what's happening. You may also try to increase the size of the shared memory in the DT and in `platform_config.h` (be careful not to overlap other memory areas!).

**Comment by aminusamine** [comment]
Hello @jforissier , 

Thank you very much for your answer. You were wright about the shared memory. It was a problem and i tried to write a small program which displays only something in the secure world. I tried to execute my program on OP-TEE- FVP and it works normally. 

However, when i deployed it on OP-TEE-JUNO, i still have problems. I past you the result of the execution on JUNO.

root@FVP:/ hashing 
Context Established successfuly
Session was opened successfuly !!! 
ERR [1205] TEEC:TEEC_InvokeCommand:566: TEE_IOC_INVOKE failed
hashing: Calculation of the hash failed with code 0x2


I do not understand why it does not work.

Can you help me on this please ?

Thank you very much

**Comment by jbech-linaro** [comment]
@aminusamine can you run [hello_world](https://github.com/linaro-swg/hello_world) on Juno? That is very stripped down and included in our default setups. I think it could be worth starting out with that ensure that you have a plain simple TA working.

**Comment by aminusamine** [comment]
Hello @jbech-linaro, 

I tried to execute hello_world on JUNO, this is what i have.


root@FVP:/ hello_world 
Invoking TA to increment 42
ERR [992] TEEC:TEEC_InvokeCommand:566: TEE_IOC_INVOKE failed
hello_world: TEEC_InvokeCommand failed with code 0xffff0000 origin 0x2
root@FVP:/ 

But when i run xtest, it works correctly. 

23475 subtests of which 0 failed
67 test cases of which 0 failed
0 test case was skipped

I do not understand what it can be ? Do you ?

Thank you

**Comment by jbech-linaro** [comment]
Ah, it's bailing out already in userspace normal world. It's the 
```c
rc = ioctl(session->ctx->fd, TEE_IOC_INVOKE, &buf_data);
```
that fails. It's hard to say why and where it fails. Can you try adding a couple of debug prints in the TEE driver to see whether it stops in the driver or if it goes down to the secure side?

Is the TA deployed on the filesystem? I.e. `"TA_HELLO_WORLD_UUID".ta` in `/lib/optee_armtz`? But on the other hand the OpenSession seems to work and that means that the RPC message to load the TA should work. I.e., seems like the TA is indeed deployed.

**Comment by jforissier** [comment]
Perhaps not related at all, but please check your device tree. Make sure the TEE memory and the shared memory are properly reserved. It should be like: https://github.com/linaro-swg/linux/blob/optee/arch/arm64/boot/dts/arm/juno-base.dtsi#L179-L196
All kinds of weird things can happen if Linux is allowed to touch that memory outside the TEE driver.

**Comment by vchong** [comment]
@aminusamine Did you actually rebuild your TA against the Juno setup (libraries, headers, etc), or did you just copy the files from the FVP setup over to the Juno board? If you just copied the files over, please try rebuilding instead, as the libraries and headers are mostly platform specific and cannot be reused for different targets/boards.

**Comment by aminusamine** [comment]
Hello @vchong, Can you explain me how to rebuild the TA against the JUNO setup please. 

I copied directly the from the FVP setup. 

Thank you.

**Comment by vchong** [comment]
How did you build it for FVP in the first place? You should be able to just use the same process, and just replace all the FVP-related/specific stuffs with Juno's.

**Comment by aminusamine** [comment]
I have this lines in my compilation script 
export PLATFORM=vexpress
export PLATFORM_FLAVOR=fvp_virt

How i should replace these to build my TA for JUNO ?

**Comment by vchong** [comment]
You can't just run the compilation script without having built optee_os and optee_client for FVP first, so if you've already built optee_os and optee_client for FVP, you should be able to build them for Juno as well using the same commands and replacing FVP-related/specific flags/configurations with those of Juno's.

Also, you're using the comcast_cryptoapi_ta_example compilation script which is not maintained anymore. You can still refer to the contents of the .c files if you want to use the example crypto ops there, but please use to https://github.com/linaro-swg/hello_world instead.

In essence, follow the instructions [here](https://github.com/OP-TEE/optee_os#5-repo-manifests) for Juno. This will created (build) the Juno setup, which includes the hello_world above.

Then you can build your TA against this setup based on the instructions [here](https://github.com/linaro-swg/hello_world/blob/master/README.md). You can clone this hello_world repo, give it a different name (since it's already included in the Juno setup above) and make your own modifications to the code. Note that you'll also need to change the TA's UUID [here](https://github.com/linaro-swg/hello_world/blob/master/ta/Makefile#L5) and [here](https://github.com/linaro-swg/hello_world/blob/master/ta/include/hello_world_ta.h#L32) to one of your own.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered and it's been inactive for quite a while. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
