### ISSUE TITLE
Problem with running optee on Hikey (Initramfs based && debian-OS)

### ISSUE THREAD

**Issue by sunzc** [OP-TEE/optee_os#1234]
I'm using Hikey(Lemaker version, 2GB RAM, 8GB eMMC).  and I'm using the 8GB partition table.
When I try to run OP-TEE on this board, after I do the following:

make all
make flash

when I reboot with jumpers properly setted(1-2 closed, others open), I can't see anything on the monitor. 
I thought this simple configuration should work immediately, but it is not, any hints? 

BTW, I also tried running optee on hikey board with debian OS as the normal world OS, however I also get stuck after I finished installing the linux-image and optee image with the following cmds:

$ dpkg --force-all -i /tmp/out/optee_2.0-1.deb
$ dpkg --force-all -i /tmp/linux-image-*.deb

When I reboot, the kernel get stuck saying usb-bus is in high-speed mode and it can't enumerate low-speed usb-device and it stuck there.

FYI, I am using HDMI - VGA converter to connect hikey board to a VGA monitor. So far I don't have a uart cable for the uart3 on hikey board.

Thanks!

**Comment by vchong** [comment]
For initramfs, I think you won't see anything on the monitor since it's console only so you'll need a uart cable for the uart3.

For debian, I'm not sure but if you have the microusb cable connected, please try removing it and reboot the board to see if it helps. If you check the [96boards hikey forum](http://www.96boards.org/forums/forum/products/hikey/), you can also see that some monitors might have compatibility issues with the board as well.

**Comment by sunzc** [comment]
Thanks a lot! 

For initramfs, I am so happy to hear that. I doubted the kernel might be configured for console only, but I don't have a uart3 cable to verify. I will try that.

**Comment by vchong** [comment]
You're welcome. If you don't already have one, the easiest would probably be to get the UART Serial Adapter [here](http://www.96boards.org/product/debug/). Then you can just use any ordinary usb-microusb cable to plug into it.

**Comment by sunzc** [comment]
That's really helpful, thanks!
BTW, I already have the uart0 cable, but to configure the kernel to use uart0 needs some effort, is that worth trying while waiting for the new adapter?

**Comment by vchong** [comment]
It's not a lot of effort to configure for UART0, but does your board already have a 4-pin header soldered onto the UART0 location J801? See http://wiki.lemaker.org/HiKey(LeMaker_version):UART (How to change the debug UART from UART3 to other UART port)

If you do, then you can just change https://github.com/OP-TEE/build/blob/master/hikey.mk#L12-L13 from 3 to 0 and rebuild.

**Comment by vchong** [comment]
When you make your connection, please also note the warning on the lemaker page: Do NOT connect VCC to the J801-01 1.8V pin or else the board will be damaged!

**Comment by sunzc** [comment]
Yes, my board already has a 4-pin header soldered onto the UART0 on location J801. On the wiki, it seems that the all the UART ACC pin has already been powered, so I just need to to connect the rest 3 pins. I will try that.  Thank you for your kind warning!

**Comment by sunzc** [comment]
For debian OS, when I install the linux-image and optee image with the following cmds:

$ dpkg --force-all -i /tmp/out/optee_2.0-1.deb
$ dpkg --force-all -i /tmp/linux-image-*.deb

I get the following info:

naro@linaro-alip:~$ sudo dpkg --force-all -i /tmp/out/optee_2.0-1.deb 
Selecting previously unselected package op-tee.
(Reading database ... 61912 files and directories currently installed.)
Preparing to unpack /tmp/out/optee_2.0-1.deb ...
Unpacking op-tee (2.0-1) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/bin/tee-supplicant', which is also in package tee-supplicant 1.0.1+git5+g89f25ce-1.linarojessie.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/aarch64-linux-gnu/libteec.so.1.0', which is also in package libteec1.0 1.0.1+git5+g89f25ce-1.linarojessie.1
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/usr/lib/aarch64-linux-gnu/libteec.so.1', which is also in package libteec1.0 1.0.1+git5+g89f25ce-1.linarojessie.1
Setting up op-tee (2.0-1) ...
linaro@linaro-alip:~$ sudo dpkg --force-all -i /tmp/linux-image-*.deb
Selecting previously unselected package linux-image-4.4.11-optee-rpb.
(Reading database ... 61929 files and directories currently installed.)
Preparing to unpack .../linux-image-4.4.11-optee-rpb_4.4.11-optee-rpb-1_arm64.deb ...
Unpacking linux-image-4.4.11-optee-rpb (4.4.11-optee-rpb-1) ...
Preparing to unpack .../linux-image-4.4.11-optee-rpb_4.4.11-optee-rpb-2_arm64.deb ...
Unpacking linux-image-4.4.11-optee-rpb (4.4.11-optee-rpb-2) over (4.4.11-optee-rpb-1) ...
More than one copy of package linux-image-4.4.11-optee-rpb has been unpacked
 in this run !  Only configuring it once.
Setting up linux-image-4.4.11-optee-rpb (4.4.11-optee-rpb-2) ...
update-initramfs: Generating /boot/initrd.img-4.4.11-optee-rpb
Copying hi6220-hikey.dtb as /boot/hi6220-hikey-4.4.11-optee-rpb.dtb
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.4.11-optee-rpb
Found initrd image: /boot/initrd.img-4.4.11-optee-rpb
Found devicetree image: /boot/hi6220-hikey-4.4.11-optee-rpb.dtb
Found linux image: /boot/vmlinuz-4.4.0-104-arm64
Found initrd image: /boot/initrd.img-4.4.0-104-arm64
Found devicetree image: /boot/hi6220-hikey-4.4.0-104-arm64.dtb
blockdev: ioctl error on BLKROSET: Operation not permitted
blockdev: ioctl error on BLKROSET: Operation not permitted
blockdev: ioctl error on BLKROSET: Operation not permitted
blockdev: ioctl error on BLKROSET: Operation not permitted
blockdev: ioctl error on BLKROSET: Operation not permitted
blockdev: ioctl error on BLKROSET: Operation not permitted
blockdev: ioctl error on BLKROSET: Operation not permitted
done

When I reboot, the kernel get stuck after printing those info below:

usb 1-1.1: device descriptor read/64, error -71
usb 1-1.1: device descriptor read/64, error -71
usb 1-1.1: device descriptor read/64, error -71
usb 1-1.1: device not accepting address 5,, error -71
usb 1-1.1: device not accepting address 5,, error -71
usb 1-1-port1: unable to enumerate USB device at low-speed while bus at HIGH_SPEED

I only have a usb keyboard and usb mouse connected to hikey board, no macro-usb connected. Do you have any idea?

**Comment by sunzc** [comment]
Since the problem has been resolved in #1257, I will close this issue by myself.
