### ISSUE TITLE
run optee on hikey(initramfs based), usb keyboard does not work

### ISSUE THREAD

**Issue by sunzc** [OP-TEE/optee_os#1240]
I am using HiKey(LeMaker version, 2GB RAM, 8GB eMMC), and flash initramfs based boot image to the board and it boot normally and wait at "Press Enter to activate console", however, it does not accept input from the connected usb keyboard. Has anyone come into this problem?

**Comment by jbech-linaro** [comment]
Do you have the OTG cable plugged in? If yes, unplug that and reboot and try again.

**Comment by sunzc** [comment]
Thanks, Now I figured out that when run the initramfs based version, the hikey board only accept input from the host machine keyboard(the minicom terminal on the host linux machine).

**Comment by jbech-linaro** [comment]
It wasn't clear to me how you were trying this. Like you said, the usual way of doing is to have no keyboard / mice whatever connected to the HiKey, instead you just use the UART. But depending on what filesystem you are using you can even have X. So, are you OK with me closing the issue?

**Comment by sunzc** [comment]
Yes, I'm using the initramfs, so no need to use the keyboard/mice. it's OK to close this issue.
