### ISSUE TITLE
HiKey Manual error on uart0 pin description

### ISSUE THREAD

**Issue by sunzc** [OP-TEE/optee_os#1241]
Just to warn anybody who is planning to run op-tee on hikey board with initramfs based version, the hikey manual is incorrect on the description of uart0 pins.

Due to lack of UART Serial Adapter(from LS connector to microUSB) (for uart3), I tried reconfigure the default uart from uart3 to uart0, and I connect the uart0 pin to the UART to USB Adapter Cable as what is described in the hikey manual:

uart0
1.8V    1    2 UART0_RX
DGND 3   4 UART0_TX
（In either case, don't connect the ACC 1.8v pin to the adapter, that would burn the PMC, refer to [here](http://wiki.lemaker.org/HiKey(LeMaker_version):UART) ）

However, it doesn't output anything readable. But after I try to exchange the RX and TX cable, it works.

uart0
1.8V    1    2 **UART0_TX**
DGND 3   4 **UART0_RX**
（In either case, don't connect the ACC 1.8v pin to the adapter, that would burn the PMC, refer to [here](http://wiki.lemaker.org/HiKey(LeMaker_version):UART) ）.

**Comment by vchong** [comment]
Hi @sunzc,

Thanks for your comment! Which manual are you referring to? Can you provide an url?

In either case, I think it's just a matter of perspective, because you're supposed to connect RxD of board to TxD of cable, and TxD of board to RxD of cable, so whether it's RxD or TxD depends on which side of the connection you're looking from.

Manuals probably label it from the board's perspective.

**Comment by sunzc** [comment]
[hikey manual](https://www.96boards.org/wp-content/uploads/2015/02/HiKey_User_Guide_Rev0.2.pdf)

You can check it out on the section "UART".

For me, the manual is the only reliable source to figure out how to connect the cable to the pins on hikey board, Usually, manual is usually the trust base, so it cost me a lot of time to figure this out. I hope this will save other people some time.

**Comment by vchong** [comment]
Yes, perhaps there should be a note that says connect tx to rx and vice versa. Let's hope your comment will be helpful to many others.

Thanks again!
