### ISSUE TITLE
One question about SMC in OP-TEE and PSCI on ARMv7

### ISSUE THREAD

**Issue by teddybearw2016** [OP-TEE/optee_os#1243]
I am a new learner for OP-TEE. As I know, there is secure monitor and the corresponding smc function in OP-TEE. But in U-Boot, if PSCI is enabled, there is related secure monitor and smc function too. Is there any conflict between them? Which secure monitor and smc function should be called?

**Comment by etienne-lms** [comment]
Hello @teddybearw2016. you are right on ARMv7: op-tee comes with its own TZ Monitor (when built without ARM TrustedFirmware support), u-boot comes with its own monitor (PSCI + booting image in NonSecure TZ state).

There can be only 1 monitor at runtime in the system. So either the u-boot one or the op-tee one. As far as op-tee provides the runtime "secure" service, I would recommend to add all runtime services into op-tee monitor: so you must port the PSCI stack into op-tee. Note that there are on-going work on PSCI in op-tee, so keep synchronized...

One could want op-tee to support pre-installed SMC services (as those PSCI from another component as u-boot). I think this can be quite difficult to maintain in the long term and we should better have ARMv7 full support within the optee core.

**Comment by teddybearw2016** [comment]
Thanks for your reply. I still have two questions.
1. As you mentioned, there are on-going work on PSCI in op-tee. Where can I find these code?
2. As only 1 monitor at runtime in the system, if we want to run op-tee, we must disable PSCI in u-boot and kernel, right?

**Comment by etienne-lms** [comment]
Early PSCI in optee is proposed here: https://github.com/OP-TEE/optee_os/pull/1242 .
It is still proposal and we looking for the best way to get psci support in op-tee, known that it is required only for ARMv7 cores (and possibly ARMv8 full Aarch32 cores).

> As only 1 monitor at runtime in the system, if we want to run op-tee, we must disable PSCI in u-boot and kernel, right?
Yes, that is right.
Currently there is no psci support in vanilla op-tee. So either you port psci into optee for your platform, or you must drop psci support. I think kernel should be able to boot even if PSCI is broken: i am not sure you really need to disable PSCI from kernel to get your platform booting on a single core.

**Comment by teddybearw2016** [comment]
Thank you so much for your detailed reply.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
