### ISSUE TITLE
Android + OP-TEE on QEMU (with ARM TrustZone) 

### ISSUE THREAD

**Issue by mame2015** [OP-TEE/optee_os#1246]
Hi,
I can manage to run OPTEE + Linux kernel on ARM QEMU (https://github.com/OP-TEE/optee_os). Now, I wanted to run OPTEE with Android on QEMU (with TrustZone extensions enabled). Can anyone explain me how to setup Android on ARM QEMU with OPTEE OS running as a secure kernel?  or steps if possible. Thanks for your answers.

**Comment by jbech-linaro** [comment]
Hi @mame2015 , I don't think anyone has went that path yet. We had it up for discussion ~2 years ago, but we never got started. If I would try to get this working I'd probably start out with focusing on getting Android working first without involving OP-TEE. When you have that working, then try to enable OP-TEE pieces. If you get anywhere with this and like to have patches etc officially merged, please let us know and we can probably help you out. Sorry for not being able to give a better answer at this point.

**Comment by vchong** [comment]
Hi @mame2015

@yingkailiang was trying this in https://github.com/OP-TEE/optee_os/issues/737 back in April. If he's reading this, maybe he can let us know his progress?

**Comment by yingkailiang** [comment]
Hi, @mame2015 

I have already given up this approach and adopted the "hikey + android + optee" solution for my current research project. Porting optee + android requires the expertise for both optee OS and qemu hardware knowledge.
 
Just another thought. Qemu is the base line for android emulator (ranchu). Maybe it makes more sense to run android + optee on ranchu instead of qemu, since google customize a lot of phone features on this virtual board.

**Comment by romanliv** [comment]
Trying to make the android + qemu + optee setup to work as well.
I am trying to understand whether system and userdata can be mapped in combination with -bios optionin the same way as Android emulator does this: passing these through the -device and -driver qemu switches, like this:
`-drive index=1,id=userdata,file=~/.android/avd/Nexus_5_API_24_arm.avd/userdata-qemu.img \
-device virtio-blk-device,drive=userdata \
-drive index=2,id=cache,file=~/.android/avd/Nexus_5_API_24_arm.avd/cache.img \
-device virtio-blk-device,drive=cache \
-drive index=3,id=system,file=~/Android/Sdk/system-images/android-24/default/armeabi-v7a//system.img,read-only \
-device virtio-blk-device,drive=system `

**Comment by yieux** [comment]
@romanliv  Did it work well?
I also try to make the "android + qemu + optee". 
It seems that I can use "-drive" and "-device" to assign the system.img and userdata.img files to qemu.
As OP-TEE for linux kernel, we also need a bios.bin file that contains kernel, root fs and optee-os. 


So my question is how to build the useful root fs.  
Android source code could be completed to generate a ramdisk.img. 
The directorys of " ramdisk.img" is not same with the the directorys of a linux kernel root fs.
And also op-tee used root fs has  busybox, xtest,helloworld and tee-supplicant.

I can't to replace the optee's root fs with Android's "ramdisk.img" easily. 
So someone could give me some suggest? Thanks.~

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
