### ISSUE TITLE
Android and OP-TEE integration

### ISSUE THREAD

**Issue by typeless** [OP-TEE/optee_os#1247]
I am try to integrate OP-TEE into an Android (4.4) BSP and encountering some problems.

My setup is as follows (Is there any recommended way, btw?):

- android-k/
  - vendor/
    - foo/
      - optee_os/
      - lib/
        - libbar/
          - Android.mk
          - helloworld_ta/
            - Android.mk
          - helloworld_ca/
            - Android.mk

Relevant variables mentioned in `mk/aosp_optee.mk` have been added into the `device.mk` accordingly. `libbar` and `ca` can be built successfully too. However, I encountered some problems when building `helloworld_ta`.

Its `Android.mk` is as follows:
```
local_module := optee-helloworld-ta
include vendor/foo/optee_os/mk/aosp_optee.mk
```

When invoking `mm` under the directory of the ta (`android-k/vendor/foo/lib/libbar/helloworld_ta/`), it entered infinite loop which kept building the ta and optee_os.
I was trying to diagnose the building process, can not find anything obviously wrong except that the `TA_DEV_KIT_DIR` variable was set to a path which is in fact the concatenation of two absolute paths. It appears not to be the root cause though.

Any ideas are appreciated.

**Comment by jbech-linaro** [comment]
Hi @typeless , it's been quite a while since someone in the team actively working with OP-TEE did an Android build. Having that said, the instructions [here](https://github.com/linaro-swg/optee_android_manifest) used to be working. I think my colleague kept it up-to-date and used it in September when we were at Linaro Connect. If you manage to get it working and would like to update our current build instructions we would be more than happy to do so. Sorry for not being able to give better help as of now.

**Comment by typeless** [comment]
@jbech-linaro Thanks for your kind reply. I just found some resources which might be helpful to get it further.
Such as https://github.com/linaro-swg/optee_android_manifest/blob/master/optee.xml
and https://github.com/kuscsik/lcu14_optee_hello_world

If that works I'll feedback the good news 😸

**Comment by typeless** [comment]
It turns out the mistake I made is I didn't put `LOCAL_PATH:=$(call my-dir)` at the beginning of the Android.mk. I thought the `local_module` variable serves the same purpose.

**Comment by jbech-linaro** [comment]
@vchong is currently maintaining the build for OP-TEE and those can be found here:
https://github.com/linaro-swg/optee_android_manifest

To my knowledge that is working.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
