### ISSUE TITLE
TA for OPTEE that returns a string

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1248]
Merry Xmas !

I am trying to write a TA for OPTEE that can get a string argument, as well as return a string. I am modifying the hello world example for the test. The problem is that when the TA returns, the string buffer comes to null, but the size returns correctly. I show the relevant code below.

`In Host Code:`
char arg[20];
memset(arg, 0, sizeof(arg));
strcpy(arg,"Hello World");

memset(&op, 0, sizeof(op));
op.params[0].tmpref.buffer = (void *)arg;
op.params[0].tmpref.size = str_size;

op.paramTypes = TEEC_PARAM_TYPES(
                TEEC_MEMREF_TEMP_INPUT,
                TEEC_MEMREF_TEMP_OUTPUT,
                TEEC_NONE,
                TEEC_NONE);

res = TEEC_InvokeCommand(&sess, TA_HELLO_WORLD_CMD, &op, &err_origin);

`In TA code:`
uint32_t exp_param_types = TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT,
                                                   TEE_PARAM_TYPE_MEMREF_OUTPUT,
                                                   TEE_PARAM_TYPE_NONE,
                                                   TEE_PARAM_TYPE_NONE);
......
char ret_arg[] = "Bye Bye";
params[1].memref.buffer = (void *) ret_arg;
params[1].memref.size = 8;
return TEE_SUCCESS;

`Result checked back in host code:`
if (res == TEEC_SUCCESS) {
                printf("Return Success \n");
                printf("Returned string : %s \n", (char *) op.params[1].tmpref.buffer); // this comes to null
                printf("Returned size : %d \n\n", op.params[1].tmpref.size); // this prints 8
 }`

Can someone tell what I'm doing wrong to return the character array content (ret_arg) ?

**Comment by a2t2** [comment]
I added the following in the host code:
char ret[20];
op.params[1].tmpref.buffer = (void *)ret;
op.params[1].tmpref.size = 20;

In the TA I copied the character string to the passed buffer and updated the length before return.

**Comment by jbech-linaro** [comment]
The string you are trying to return to normal world is on the TA stack (secure side memory), you should instead provide a pre-allocated buffer (as arg[1] from normal world) or use the shared memory mechanism.

**Comment by a2t2** [comment]
@jbech-linaro Yes the second code I posted worked.

**Comment by jbech-linaro** [comment]
Perfect! Thanks for closing the issue when you've found an answer, helps us to keep track of what's open and not so to say.

**Comment by a2t2** [comment]
I wanted to double check my understanding. In the solution I posted, when the TA is called, is the buffer being copied over into TA memory; once modified in TA, on return is it being copied back ? I ask because you mention the second shared memory mechanism.
