### ISSUE TITLE
Compiling Android SDK - Error related to OPTEE mk file

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1254]
I am trying to compile Android + OPTEE code as follows:

$ lunch sdk-eng
$ make sdk

I am getting the following error:
build/core/binary.mk:1444: *** external/optee_test/Android.mk: xtest: C_INCLUDES must be under the source or output directories: /host_include.
make: *** [out/build-sdk-sdk.ninja] Error 1

I wanted to ask if anyone knows how this may be resolved. The code was downloaded in September 2016.

Thanks.

Note: The branch compiles fine for lunch option hikey-userdebug.

**Comment by jbech-linaro** [comment]
@vchong is currently maintaining the build for OP-TEE and those can be found here:
https://github.com/linaro-swg/optee_android_manifest

To my knowledge that is working.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
