### ISSUE TITLE
Failure when using Allocate Operation for HMAC SHA256

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1256]
I am trying to write a TA wherein I need to use a 20 byte key to calculate HMAC using SHA256. I am testing OPTEE in QEMU.
Similar to [sample](https://github.com/OP-TEE/optee_test/blob/master/ta/crypt/cryp_taf.c#L39), my TA contains the following code:

```c
// Code before has some array declarations
// HMAC_SHA256 - 0x30000004
// MODE_MAC - 4

res = TEE_AllocateOperation(&op, 0x30000004, 4, 20);
```

I get the error `TEE_ERROR_NOT_SUPPORTED`. Can anyone tell what is wrong with the above call ?

Thanks.

Note:
The xtest 4002 test does pass. In that code, arguments passed for HMAC SHA256 are:
```c
TEE_AllocateOperation(&op, 0x30000004, 4, 8);
```
When I try it in my TA, it doesn't work.

**Comment by jbech-linaro** [comment]
I believe the keysize you are providing is wrong, the spec says:
"_TEE_TYPE_HMAC_SHA256 Between 192 and 1024 bits, multiple of 8 bits_" which is in the interval [24, 192] bytes.

When I read test 4002, I see that the macro expand to `sizeof(mac_data_sha256_key1[24])`. I.e. it's 24 and not 8 as you said. 

So, try to adjust your keysize and I'm sure it will work.

**Comment by jbech-linaro** [comment]
And by the way, things like this is pretty easy to figure out in QEMU and gdb. It could be worth spending some time setting up that. We have some information about it [here](https://github.com/OP-TEE/optee_os/blob/master/documentation/debug.md#1-qemu). Getting a TA to work too is also easy. Let me know if you are interested in trying that and I'll help you out.

**Comment by a2t2** [comment]
I used 1024 as an argument and it worked. 

`TEE_AllocateOperation(&op, 0x30000004, 4, 8);`

Thanks.
