### ISSUE TITLE
Docs: clarify secure storage key storage on Hikey

### ISSUE THREAD

**Issue by lws-team** [OP-TEE/optee_os#1258]
I read this presentation

http://www.slideshare.net/linaroorg/sfo15503-secure-storage-in-optee

and the optee_os documentation markdown

https://github.com/OP-TEE/optee_os/blob/master/documentation/secure_storage.md

Both the presentation and markdown docs simply say, "SSK is a per-device key and is generated and stored in secure memory when OP-TEE is booting".  I understand there is a CPUID and it seems a magic "per-device key" comes from somewhere, presumably accessible only when NS=0.

Since the TAs are unencrypted, per-device secrets are going to have to go in Secure Storage...

How does that actually play out on the Hikey platform specifically?  Does the per-device key exist in e-fuses on Hikey already... something else?

**Comment by jforissier** [comment]
Hi @lws-team, 

Actually, the upstream implementation of the secure storage keys is not secure. At the very least, you need to provide a platform-specific implementation of `tee_otp_get_hw_unique_key()`. But for better security, the per-device key should be accessible to the crypto engine only (e-fuses typically), and not accessible to the software even when NS=0. The SSK (as well as any other device-specific key) would then be derived from this per-device key by the crypto engine, kept in secure memory, and never written anywhere. Unfortunately, we don't have the datasheet for the HiKey crypto engine so we could not go this route. That's why the SSK is derived from hard-coded strings and IDs (see `tee_fs_init_key_manager()`). It is good enough for testing but obviously not usable as-is in a real product.

**Comment by lws-team** [comment]
@jforissier Thanks for the info.

Right now the platform is just a generic Hikey, so there is no way for us to provide a meaningful overload of getting the per-device key AFAIK, since Hisilicon are not going to tell me anything they aren't already telling Linaro.

I think my customer can probably shrug at this, since we already don't have a workable Chain of Trust from ROM with Hikey, and continue the approach of getting everything else proven and in place for reimplementation on a platform capable to be secure.  But it's a bit disappointing.  And there is no reason not to plainly document it, since anyone who cares is going to find out (hopefully before they are hacked).  It seems particularly dangerous to bandy around a term like "**Secure** Storage" when it's anything but on one of the major recommended platforms, without spelling the caveats out clearly.

If it's already written up somewhere I'll be happy to read it or provide a patch explaining it if not.

**Comment by jbech-linaro** [comment]
I have a porting guide line on my to-do list and how to deal with the HUK is one thing that should go there. As long as we have no device fully open to us we cannot provide a complete implementation. There are "gaps" that needs to be implemented by the OEM. Secure boot (from ROM is one), HUK is another. Power management is another and firewalls is yet another. We are trying to make implementations as generic as we can, but in some cases it's really hard for us (hardware not open enough or lacking documentation). But again a coming  porting guide line should address what needs to be done by the OEM. Just need to find some time to get it done...

**Comment by lws-team** [comment]
Yeah... I do understand the situation.

But there's no reason not to spell it out.  And as soon as you talk about "**secure** storage" without explaining this clearly, the sins of omission are starting to mount up.

Like I say if your todo list is overwhelming I will be happy to provide a patch explaining it for you.

**Comment by jforissier** [comment]
@lws-team I share your feelings re. HiKey, about Hisilicon not publishing (enough) information, and believe me, I tried to get data from inside... Memory firewall, secure UART, crypto engine...

What about adding a "Caveat" section to `README.md`? There we could briefly mention the security shortcomings of the upstream code and later link to the more comprehensive porting guide that @jbech-linaro mentioned. Feel free to propose something.

**Comment by lws-team** [comment]
@jforissier Yeah... I really do understand the difficulty.  And all users without a big order for SoCs in their hand face the same situation.

I also think something like that Caveat section is required if you will use the word "Secure" otherwise unqualified.  I'll take a look at the code you pointed to later to make sure I understand how it is and send a PR.

**Comment by jbech-linaro** [comment]
@lws-team I'd be more than happy if you could provide patches for this. We're struggling in general to find time to all activities. We're a rather small team and for OP-TEE with the increased device support, different variants of build, plain Linux, AOSP, OpenEmbedded, Debian, answering issues takes quite a lot of time for us. Then we have new features on the roadmap etc and to top that we have other areas related to security not at all related to OP-TEE, so yes .. if you can and have time, we would be more than happy to get patches which clarifies and fixes problems.

**Comment by lws-team** [comment]
So it seems the section should say something along the lines that:

 - no platform in stock optee currently implements a HUK in "OTP" (no platform has CFG_OTP_SUPPORT), which means

 - for all platforms the HUK is set to all zeros

 - for all platforms the CPUID is set to 'B' 'E' 'E' 'F' repeated as much as needed

IIUI, all of the elements to generate the SSK are constants in fact... the SSK is always the same for every device.  That can't help any effort checking it, for, eg, security against encrypted file copying between devices, because that'll work if it's like this.

How about tee-supplicant sets the key using an untrusted filesystem file if no better key already available?  Like `/lib/optee-armtz/fake-huk.dat`?  tee-supplicant can create that file with `/dev/[u]random` if it doesn't exist.  That is not solving the security side but it is at least acting like it has a per-device key, and that code is platform-independent.

**Comment by lws-team** [comment]
@jbech-linaro I'm getting paid to use optee rather than work on it... you guys are getting paid to work on it.  But since I expect I get more questions and problems and it feels like I should try to balance the books by giving back a bit atm, even if it's docs patches.

**Comment by jforissier** [comment]
@lws-team your understanding is 100% correct.

Regarding your "fake HUK" proposal, that would certainly work, but we do not run the kind of tests you're mentioning currently (copying between devices), so generating that fake HUK would be of limited interest IMO.
Now if that's something you would like to exercise, a simpler option would be to obtain the hard-coded default HUK from a config variable that one could easily override at build time (`make CFG_HUK=foobar`).

**Comment by lws-team** [comment]
Hard-coding the huk in the optee blob isn't the same result... the way I described you can distribute one bootloader + optee blob, but every device will get a 'unique' key that is sticky.

From a code coverage pov as it stands you don't even know the crypto / key elaboration works with any other key if the entire stack never sees anything but the same constants.  That's a situation that should be improved somehow...

**Comment by 21212124** [comment]
Hi @lws-team 

As he understood it, the SSK is derived from HUK and a constant string that uses HMAC-SHA256, but right now the SSK is not derived from the HUK right?
Is the constant key predefined? where?

Could you explain it to me better?

Thanks

**Comment by 21212124** [comment]
> En realidad, la implementación aguas arriba de las claves de almacenamiento seguro no es segura. Como mínimo, debe proporcionar una implementación específica de la plataforma `tee_otp_get_hw_unique_key()`. Pero para una mejor seguridad, la clave por dispositivo debe ser accesible solo para el motor de cifrado (fusibles electrónicos normalmente), y no accesible para el software incluso cuando NS = 0. El SSK (así como cualquier otra clave específica del dispositivo) se derivaría de esta clave por dispositivo mediante el motor de cifrado, se mantendría en una memoria segura y nunca se escribiría en ningún lado. Desafortunadamente, no tenemos la hoja de datos para el motor criptográfico HiKey, por lo que no pudimos seguir esta ruta. Es por eso que el SSK se deriva de cadenas e ID codificadas (ver `tee_fs_init_key_manager()`). Es lo suficientemente bueno para las pruebas, pero obviamente no se puede usar tal cual en un producto real.

@jforissier Is this still correct?
In Qemu and in the IMX board if there is an implementation of tee_otp_get_hw_unique_key ()?

**Comment by jforissier** [comment]
> @jforissier Is this still correct?

Yes. For i.MX however things have changed a bit, see in particular commit 919323d9 ("caam: add BLOB module for MKVB retrieval"). I will let the i.MX comment in more details if needed.
