### ISSUE TITLE
Docs: CFG_ENC_FS deprecated?

### ISSUE THREAD

**Issue by lws-team** [OP-TEE/optee_os#1259]
`optee_os/documentation/secure_storage_rpmb.md` and `optee_os/documentation/secure_storage.md` refer to `CFG_ENC_FS`.  It's also confidently mentioned in a Secure Storage presentation found via Google.

Grepping around, this only seems to exist in .md files.

CHANGELOG.md mentions its introduction, but not its deprecation.

CFG_REE_FS, CFG_RPMB_FS and CFG_SQL_FS exist OK in the build system.  But not CFG_ENC_FS.

Is it in fact deprecated and should be removed from the docs?

**Comment by jenswi-linaro** [comment]
Yes you're right it's deprecated and should have been removed from the docs.
