### ISSUE TITLE
Xtest 6007 fails for CFG_SQL_FS=y

### ISSUE THREAD

**Issue by jenswi-linaro** [OP-TEE/optee_os#1268]
Since commit 8ced8945bffa101b6da3f3cf71b7485e3e5877cc xtest 6007 fails if compiling with CFG_SQL_FS=y

**Comment by jforissier** [comment]
Yes, and xtest 6010 too, it seems.

**Comment by jenswi-linaro** [comment]
True, maybe it's easier to see what's wrong in 6010.

**Comment by lackan** [comment]
Oh no, I have a look also.
