### ISSUE TITLE
Random and Hikey

### ISSUE THREAD

**Issue by lws-team** [OP-TEE/optee_os#1273]
I am wiring up an SSL library inside a TA.

What is the best way to get some highest-quality random data in optee?  Is there a generic api that just uses the best available random source?

I couldn't find any sign of a HWRNG in the hikey plat; maybe I missed it.

However grepping around in the kernel, there seems to be an implementation there, its dts name is hisilicon,hip04-rng / hisilicon,hip05-rng and it was provided by Huawei, not Hisi.  Neither Hikey dts nor hi6220 dtsi instantiates it though, so we don't know the address if it exists in Hikey.  It's unclear hi6220 has the same unit

https://patchwork.kernel.org/patch/8769541/

What is the situation with Hikey HWRNG in optee and if not there, what are the prospects of knowing if we can crib the Linux driver and know the address of the IP?

**Comment by jforissier** [comment]
Hi Andy,

No, I don't think the RNG in hip04/hip05 is the same as hi6220. Actually I have no info about the hi6220 RNG, I'm not even sure the SoC has a hardware RNG.

We do have a RNG driver in OP-TEE for hip05 which is the SoC used on the D02 board (https://github.com/OP-TEE/optee_os/blob/master/core/drivers/hi16xx_rng.c ; more or less the same code as the Linux driver ; hi16xx is another name for hip05, which is also called PV660 or Phosphor 660).

Regarding hi6220, I found this repo: https://github.com/olrak2/android_kernel_huawei_hi6210sft/tree/android-6.0/arch/arm64/boot/dts/auto-generate which has a bunch of DTS files for hi6220. A quick look did not reveal any trace of a RNG device, though.

**Comment by lws-team** [comment]
Thanks... there's also this more official-looking one 

https://github.com/hisilicon/linux-hisi/tree/hisi-dt-4.9/arch/arm64/boot/dts/hisilicon

which has dts for hip06... nuffin about the rng.

They surely have a hwrng.... what might have happened is they reserve it for secure world only now and then it's not for public consumption.

Rpi3 HWRNG access is in the kernel...

I didn't find a generic api for random, again maybe I simply missed it.  That might be a useful thing to have to abstract away where the random is coming from in the case your TA may find itself running on different optee platforms with different arrangements.

**Comment by jforissier** [comment]
Sorry I realize I focused on the driver thing but didn't answer your first question actually :(
TAs can access the TEE's random source via `TEE_GenerateRandom()`.

**Comment by lws-team** [comment]
Just the job, thanks.

**Comment by vchong** [comment]
Yes there is a hw crypto engine but the spec is not open.
