### ISSUE TITLE
Equivalent of TA_InvokeCommandEntryPoint for TEE->REE events?

### ISSUE THREAD

**Issue by lws-team** [OP-TEE/optee_os#1277]
1) I understand the operation of `TA_InvokeCommandEntryPoint()` to send "commands" from REE->TEE.

But what about events that are generated on TEE side that it may asynchronously wish to inform REE about?

Is there a corresponding API, or the idea is you open a second session and do a "long poll" until an event arrives?  Any example code either way?

Edit: I got more related questions, just add them here rather than spam new issues.

2) it is in fact directly related -- I read here there are plans for a "Posix socket proxy" https://github.com/OP-TEE/optee_os/issues/873 ... I am writing my own, is the official one forthcoming shortly and I should use that instead?

3) How will blocking in the TA side work?  I can imagine starting a new thread when the TA initializes (although not sure how).  But eventually the worker thread wants to get the REE to do something for him, eg, fulfil getaddrinfo().  The flow then would somehow be like

  - TA does getaddrinfo()
   - there's a trick getaddrinfo() implementation in the TA that asks the REE to do it "somehow"
    - the getaddrinfo implementation should block... what is the recommended way?  There are mutexes but no Linux-style completion wait?
     - the original thread communicates with the REE and gets the result
     - the original thread releases the mutex and the worker thread is unblocked and continues.

This kind of flow is possible?  Any example code?

**Comment by vchong** [comment]
> But what about events that are generated on TEE side that it may asynchronously wish to inform REE about?

I don't know this in-depth but you might get something out of these:
https://github.com/OP-TEE/optee_os/blob/master/core/include/optee_msg.h#L334-L360
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/user_ta.c#L685
https://github.com/OP-TEE/optee_client/blob/master/tee-supplicant/src/tee_supplicant.c#L63-L68
https://github.com/OP-TEE/optee_client/blob/master/tee-supplicant/src/tee_supplicant.c#L420-L437

**Comment by vchong** [comment]
Sorry, pressed closed by mistake.

**Comment by vchong** [comment]
> I read here there are plans for a "Posix socket proxy" #873 ... I am writing my own, is the official one forthcoming shortly and I should use that instead?

https://github.com/OP-TEE/optee_os/pull/1262

**Comment by lws-team** [comment]
@vchong Thanks for the pointers... it seems very cutting-edge but it looks like I should try the trees in the PR first.

**Comment by lws-team** [comment]
Small update on looking at them

 - socket stuff looks like it may be too WIP atm, client part cannot build without patches.  It looks like it'll be good but doesn't cover ancillary socket functions like getaddrinfo() etc (there are a pile of these needed for a real system).

 - the RPC stuff you pointed to looks workable, thanks.  IIUI the RPC side of it cannot directly be implemented in a TA, it has to be added to optee_core directly and exported, because the kernel/ includes are not exported in the "dev kit".  FS stuff does it that way too.  This is why looking in the exported api headers didn't help.

**Comment by vchong** [comment]
@lws-team You're welcome. Not sure if a static TA can be an easier alternative or workaround. Even if yes, there's a higher security risk associated with it as well. See below for more info on static TAs.

https://wiki.linaro.org/WorkingGroups/Security/OP-TEE#What_exactly_is_a_static_TA_anyway.3F_How_different_is_it_than_a_regular_GlobalPlatform_defined_.28dynamic.29_TA.3F
https://github.com/OP-TEE/optee_os/tree/master/core/arch/arm/sta

**Comment by lws-team** [comment]
I was able to implement a syscall + RPC to implement a proxy for socket() that works in an externally-built TA.  Although that only has value params to marshal I think that broke the back of it.

Thanks for the help.
