### ISSUE TITLE
QEMU - OUT_OF_MEMORY error

### ISSUE THREAD

**Issue by gaurav4dev** [OP-TEE/optee_os#1281]
I get 0xFFFF000C(TEE_ERROR_OUT_OF_MEMORY) error while calling TEEC_InvokeCommand. Before this few InvokeCommand calls were successful and my tempref.buffer size are generally 8 and 16 bytes for these commands.
Tried to increase QEMU RAM size(-m 2048) and CFG_SHMEM_SIZE	to 8MB in platform_config.h, but these didn't help.
How can I check what is the available memory in the system in REE/TEE side while running the process?
Thank you.

**Comment by etienne-lms** [comment]
@gaurav4dev, check the value of 'error_origin' argument related to your TEEC_InvokeCommand(). It shows which OP-TEE layer complained (linux driver, core, TA). 

Also: there are 'op-tee core' malloc stats available in somewhere, in case it' the core that is running out of memory.

**Comment by gaurav4dev** [comment]
@etienne-lms error_origin is 0x1, ie "TEEC_ORIGIN_API, error originated within the TEE Client". Is it related to QEMU RAM size?

**Comment by etienne-lms** [comment]
TEEC_ORIGIN_API is the linux userland 'TEE Client API library' (libteec in optee_client).
Looking at the lib, you are likely running out of REE/TEE non-secure shared memory as you suspected.

Check size of the buffer parameters used when invoking the TA through TEEC_InvokeCommand(). "temporary" memory references trigger shm allocation/release before/after TA is invoked. Check also that all TEEC_AllocateSharedMemory()/TEEC_RegisterSharedMemory() calls have a TEEC_ReleaseSharedMemory() companion to prevent leakage.

**Comment by gaurav4dev** [comment]
Hi @etienne-lms , The OOM occurs in 6th TEEC_InvokeCommand where I use 2 buffers of 8 Bytes each. Before this if I sum all buffers in previous 5 TEEC_InvokeCommand, it totals to 138 Bytes which is small memory if suspect a memory leak scenario.  As you told that TEMP_BUFFER implementation in libteec takes care of memory alloc/release, I verified the same in each InvokeCommand and it's proper.
I just added some extra TEEC_AllocateSharedMemory() calls to narrow down the OOM scenario and  observing a strange behaviour between 5th and 6th InvokeCommand, 

In InvokeCommand_wraper,
...1024 times TEEC_AllocateSharedMemory() for 1024 buffer-size each
...5th TEEC_InvokeCommand with 3 temp-buffers size 8, 16, 2
... TEEC_ReleaseSharedMemory() previous 1024 allocations 
...1024 times TEEC_AllocateSharedMemory() for 1024 buffer-size each
... TEEC_ReleaseSharedMemory() 1024 times
InvokeCommand_wrapper returns

Then some processing in some other lib and another call to InvokeCommand_wrapper
...TEEC_AllocateSharedMemory() for 8 Bytes fails - OOM
...6th TEEC_InvokeCommand with 2 temp-buffers size 8, 8 fails - OOM

Between 5th and 6th TEEC_InvokeCommand() call, all shared-memory is eaten up.
Is it the case "REE/TEE non-secure shared memory" can only allocated by only TEEC_AllocateSharedMemory/TEEC_RegisterSharedMemory() or malloc() can also allocate from this area?

**Comment by jforissier** [comment]
@gaurav4dev as a (somewhat) quick check, can you try and increase the size of the shared memory and run your test tagain? My idea is, if it still fails but later, it probably means there is a memory leak, otherwise it's likely just insufficient memory size.
Also be careful when tracing memory usage, it's not so simple because shared memory is allocated by the Linux driver and is also used by tee-supplicant.

**Comment by gaurav4dev** [comment]
Hi @jforissier  , I increased shared memory size by modifying CFG_SHMEM_SIZE(=0x1000000) to 16MB in plat-vexpress/plat_config.h. But still get same error. I am not directly using TEEC_AllocateSharedMemory/TEEC_RegisterSharedMemory() in my host app, only using temp-ref buffers and I checked by printing logs before mmap/munmap in libteec and it shows for every allocation, release is called. Here is pmap of the application at time of oom, one thing is that here heap size is 148K, otherwise in xtest apps I have observed it is 132K, stack size is 132K in both case.
Is because of this increased heap size, non-secure REE/TEE shared memory is eaten up?
![pmap](https://cloud.githubusercontent.com/assets/23352706/21845687/95bfaa80-d819-11e6-9941-c70f3ce3d045.png)

**Comment by etienne-lms** [comment]
does qemu get shm from CFG_xxx or from the DT ?

**Comment by gaurav4dev** [comment]
Hi @etienne-lms , I am using QEMU-arm32 and I took reference from this patch https://github.com/OP-TEE/optee_os/commit/6da451b203aee2701bb9776efd6bd4a7a4cd2a96. Is there any more file to patched to increase shared memory?

**Comment by etienne-lms** [comment]
I confirm that on qemu (arm32), nonsecure shared memory size is set from `CFG_SHMEM_SIZE` in 
plat-vexpress/platform_config.h (pre-2.3.0, at  line 211 under `PLATFORM_FLAVOR_qemu_virt`).

At boot time, 'qemu' optee core fills devicetree used by linux kernel with the 'optee' node and with the optee shm area in the `@reserved-memory` node so that linux does not use it until optee driver iomaps the piece of memory.

I don't understand how you can leak of shm if using about the same optee as we (client/drv/os).

**Comment by jbech-linaro** [comment]
@gaurav4dev , any updates? Still an issue? It the issue has been resolved I'd like to close it (I'm doing a general clean among the open issues).

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins

**Comment by vchong** [comment]
@gaurav4dev Did you ever manage to fix this? I'm seeing a possible similar issue.

**Comment by vchong** [comment]
For posterity.

A possible solution to this is to increase OPTEE_SHM_NUM_PRIV_PAGES in the linux kernel tee driver. OPTEE_SHM_NUM_PRIV_PAGES is the 'private' space carved out from OP-TEE's shared memory for the allocation of the TEE params passed between the REE and TEE. Although it can differ by platform, by default [1] an OPTEE_SHM_NUM_PRIV_PAGES of 1 corresponds to 4K of memory which might not be big enough if the params contain many big buffers, especially more so if running multiple threads.

[1]
https://elixir.bootlin.com/linux/latest/source/drivers/tee/optee/Kconfig#L11
https://elixir.bootlin.com/linux/latest/source/drivers/tee/optee/core.c#L26
https://elixir.bootlin.com/linux/latest/source/drivers/tee/optee/core.c#L474
https://elixir.bootlin.com/linux/latest/source/arch/arm64/include/asm/page-def.h#L17
https://elixir.bootlin.com/linux/latest/source/arch/arm64/Kconfig#L202
