### ISSUE TITLE
Using SHM on TA side

### ISSUE THREAD

**Issue by lws-team** [OP-TEE/optee_os#1287]
The docs mention how to reserve shared memory on the client side, and that is able to work (I increased CONFIG_SHMEM_SIZE to 6MB)

```
	shm.flags = TEEC_MEM_INPUT | TEEC_MEM_OUTPUT;
	shm.size = 5 * 1024 * 1024;
	nError = TEEC_AllocateSharedMemory(context, &shm);
```

shm.buffer is set to a usable VA for the client side.

But what is the procedure for referencing and using this shared memory on the TA side (if it makes any difference, a dynamic TA)?  I failed to find any example or docs.

For example, I want to allocate this when the session is opened in the client, and inform the TA about the shared area somehow, to indicate I want it to write into it.  How to do?

**Comment by lackan** [comment]
Hi,

IMO, after you invoke `TEEC_AllocateSharedMemory(context, &shm)`,
```
op.paramTypes = TEEC_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INOUT, TEEC_NONE, TEEC_NONE, TEEC_NONE);
then set
op.params[0].memref.parent = &shm;
op.params[0].memref.size = 5 * 1024 * 1024;
TEEC_InvokeCommand(&sess, YOURTAUUID, &op, &err_origin);
```
And in the ta side, you can write into the shm buffer just using the 
`params[0].memref.buffer`

**Comment by lws-team** [comment]
Thanks @lackan ... I will try this later... at the moment I am getting by with dynamic buffers that works, but is needlessly slow (and needs memcpy each way).

**Comment by etienne-lms** [comment]
@lws-team, regarding ns-shm size increase I think you're right. I will crosscheck on my side.

Regarding shm buffer on TA side:
A TA gets knowledge (and mapping) of shm references only when the TA is invoked with parameters including "memory reference parameters". 
shm buffers are mapped at runtime by the core right before entering the TA. memref parameters are volatile between TA invocations. When a TA is called several time with some same shm buffers reference, the target shm buffers may have been mapped with different virtual addresses at each invocation. 

`kernel/user_ta.c` implements the requests for building 'memref parameters' mapping (based on `tee_mmu.c` support: mmu for TAs).

**Comment by lws-team** [comment]
Thanks... I did not really understand the implications of the reply.  But I completed the network stuff and it can perform 4096-bit ECC TLS from Secure World side at 8MiBytes/sec, even for 450MB payloads, this seems enough for now just using dynamic RPC buffers.  So closing... if the customer wants to improve throughput by using a big chunk of shm as a side-buffer, I guess I will revisit it then.

**Comment by etienne-lms** [comment]
Great you made your way.

Just to sumup my previous comment:
> (...) what is the procedure for referencing and using this shared memory on the TA side (... no docs...) ?

In current OP-TEE, for a TA to access a "shm buffer", the client must store the "shm buffer" as a "memref parameters" argument to the TA invocation request.
