### ISSUE TITLE
Increase malloc pool a TA is allowed to use?

### ISSUE THREAD

**Issue by lws-team** [OP-TEE/optee_os#1288]
My dynamic TA is running out of malloc() space, always at the same place.

Several smallish allocations up to about 6KB succeed, then in a sequence of three allocations

 - a few 100 bytes

 - 4KB

 - 4KB (fails)

So it looks like hitting a limit of some kind from somewhere.  The total number of allocations is under a dozen.

I tried to up the "core heap size" like this

```
diff --git a/core/arch/arm/plat-hikey/conf.mk b/core/arch/arm/plat-hikey/conf.mk
index 8a8ef2f..a4fde51 100644
--- a/core/arch/arm/plat-hikey/conf.mk
+++ b/core/arch/arm/plat-hikey/conf.mk
@@ -24,6 +24,8 @@ CFG_NUM_THREADS ?= 8
 CFG_CRYPTO_WITH_CE ?= y
 CFG_WITH_STACK_CANARIES ?= y
 
+CFG_CORE_HEAP_SIZE ?= 131072
+
 CFG_PL061 ?= y
 CFG_PL022 ?= y
 CFG_SPI ?= y
```

No change in the place it dies.

I tried to enable CFG_TEE_TA_MALLOC_DEBUG=y, but this kills my TA link... nothing can find `malloc()` any more.

Is there something else I should be doing to increase the malloc pool size, or increase the number of blocks it can allocate or so?

**Comment by lackan** [comment]
If you want to increase the TA malloc space, I think you should increase ta_heap[TA_DATA_SIZE] in user_ta_header.c.

**Comment by jforissier** [comment]
Hi @lws-team ,

The TA heap is inside the TA's `.bss` section. Try increasing `TA_DATA_SIZE` in your `user_ta_header.h`. This value is used here: https://github.com/OP-TEE/optee_os/blob/master/ta/arch/arm/user_ta_header.c#L91.
Note that increasing `CFG_CORE_HEAP_SIZE` as you did *might* be useful still, in case you would reach a limit such that the TEE core would not have enough memory to load the TA binary.

**Comment by jforissier** [comment]
About the TA not linking when `CFG_TEE_TA_MALLOC_DEBUG=y`: that is not a very good thing IMO but on the other hand, TAs are supposed to use `TEE_Malloc()`, that's the GP API.

**Comment by lws-team** [comment]
Thanks guys.

I'll check it is the problem (it sounds like it is gonna be) and if so I will send a couple of documentation PRs immortalizing this wisdom and also about yesterday's TA mapping restriction when getting core-allocated buffers via a syscall.

And @jforissier thanks for TEE_Malloc I will try turn my malloc consumers to that.

**Comment by lws-team** [comment]
Yes that was it, thanks again.
