### ISSUE TITLE
TA on-the-fly decryption?

### ISSUE THREAD

**Issue by jeffy1009** [OP-TEE/optee_os#1292]
Hello,

Is there some way to do on-the-fly decryption of TAs in OP-TEE? 
So that we only have encrypted TAs in the disk.
Or is it already like that?

We want to disallow normal world from accessing the TA binary.
Where can I look for relevant information?

Thank you in advance.

**Comment by jenswi-linaro** [comment]
Hi,

On-the-fly decryption of TAs are currently not supported, it shouldn't be too hard to implement. Look in `core/arch/arm/kernel/user_ta.c`.

Contributions are welcome!

Regards,
Jens

**Comment by jbech-linaro** [comment]
Having that said, we haven't decided, but it might be that we decide to implement OTrP support in OP-TEE and if we do that, then we will need to encrypt the TA's also:
https://tools.ietf.org/html/draft-pei-opentrustprotocol-01#section-14.4

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
