### ISSUE TITLE
iMX6 CAAM implementation

### ISSUE THREAD

**Issue by jeffy1009** [OP-TEE/optee_os#1293]
Hello,

I read from [here](https://github.com/OP-TEE/optee_os/tree/7a37af4a16d9e4dbc1c58de093c7ec74cb0c465b) that CAAM is not implemented now.

What is the status or plan for the implementation?

Is there anything I can do if it's not available for some time? (How can I implement secure driver?) 

Thank you:)

**Comment by jbech-linaro** [comment]
Hi @jeffy1009 ,

The core OP-TEE team has no plans on implementing CAAM support. In fact, we have no Freescale devices in our possession. But @MrVan and @yanyan-wrs has done some great work on i.MX6 devices with OP-TEE. It might be that they have some plans.

If no-one has any plan, we would be glad to help you as much as we can if you're up to the task.

I think the i.MX6 device seems to be a pretty nice device in terms of security, so I'm thinking about getting one for the core OP-TEE team.

**Comment by MrVan** [comment]
@jeffy1009 I have not start the work to enable caam in OP-TEE, busy with the psci part. @jbech-linaro  Besides random number generator, what hardware functions are needed in OP-TEE?

**Comment by jforissier** [comment]
@MrVan in my opinion, one thing that would be nice to have is key derivation for secure storage, i.e., generating the SSK (Secure Storage Key) from a device-specific key that is not readable by software.
Also, hardware crypto acceleration (AES/RSA) would be good to have upstream, because currently we have no example of how to implement this properly.

**Comment by MrVan** [comment]
@jforissier Thanks for the inputs. @jeffy1009 If you are interested, feel free to send out patches, I am happy to see that. When I finished the power things, I may follow up.

**Comment by jbech-linaro** [comment]
> @MrVan 
>  @jbech-linaro Besides random number generator, what hardware functions are needed in OP-TEE?

If I look at the security reference manual for i.MX6, things that get my attentiond are:
- The already mentioned CAAM and like you said RNG.
- There is support for the HAB (i.e., secure boot).
- Ability to use OTP (fuses)
- There is an Address Space Controller (TZASC-380).
- You have the ability to use HDCP or DTCP (depending on the configuration).
- The device has ways of detecting and protecting against glitch attacks.
- TrustZone watchdog

So, for TrustZone development I think the i.MX6 devices are very interesting. I do think it's possible to implement end to end secure using those devices. That is why I'm tempted to get one for the core OP-TEE team.

**Comment by jforissier** [comment]
@jbech-linaro agreed. Is the programming documentation publicly available? I mean, comprehensive doc, with all the register descriptions and base addresses etc. for all devices including security IPs? (TZASC, CAAM etc. as you mentioned). What about the hardware? Isn't it somehow locked or covered by NDA if you want some keys to deploy secure boot etc.? If all is unlocked and properly documented, then yes it should be a great platform for OP-TEE development, allowing integration of many things we're currently missing.

**Comment by jbech-linaro** [comment]
@jforissier , it's available [here](https://www.freescale.com/webapp/Download?colCode=IMX6DQ6SDLSRM&appType=moderatedWithoutFAE&fpsp=1&WT_TYPE=Reference%20Manuals&WT_VENDOR=FREESCALE&WT_FILE_FORMAT=pdf&WT_ASSET=Documentation&Parent_nodeId=1337637154535695831062&Parent_pageType=product), but you'll need to register to be able to download it. It's a very comprehensive document. Regarding hardware, my impression after reading various docs is that it's not locked and not covered by NDA, which also one of the reasons why I think it sounds like a really interesting device. Maybe @MrVan @b49020 have some more information about. Besides the already supported i.MX6 based devices in OP-TEE, there is the [MarS board](http://www.exp-tech.de/en/mars-board-freescale-i-mx6-dual-processor-development-board) that someone already asked about in optee_os/issue a while ago. That is the board that got my attention.

**Comment by jeffy1009** [comment]
Hello, I'm importing some u-boot code that use CAAM to OPTEE. (u-boot has code to create DEK blob which is needed for HAB(High Assurance Boot))

I've used `register_phys_mem` to register CAAM related physical memory. (although it is overlapped with `SRC_BASE`)

Then I used `phys_to_virt` to get the virtual address.

I'm trying to use CAAM when the TA is loaded (in `user_ta.c`), so I tried to access the CAAM register after `rpc_load` is done, but the OPTEE hangs.

I've tried accessing the register at the end of `init_primary_helper`, and it works fine.

Could anyone tell us what we're missing here?

**Comment by jforissier** [comment]
> (I disabled CAAM in linux device tree)

That is the first thing I was going to suggest ;)

Does OP-TEE just hang silently as you access the CAAM registers? (i.e., no exception reported on the console?). Did you try read and write access? Did you try several registers? Did you try `virt_to_phys()` to check if the VA is still properly mapped?

**Comment by jeffy1009** [comment]
I've only tried reading. When I tried to read without `phys_to_virt`, I encountered panic message. If I use `phys_to_virt`, OP-TEE hangs silently. The thing I don't understand is why it succeeds in  `init_primary_helper` but fails in `tee_ta_init_user_ta_session`.

I'll try the things you've suggested and update the results.

**Comment by jeffy1009** [comment]
I found that after `clk_disable_unused` function is called in linux kernel, OPTEE cannot access CAAM register.

linux kernel must be turning off the clocks to CAAM device.

looking for ways to fix the problem.

**Comment by jforissier** [comment]
Ha! That would make sense indeed.

How did you disable the CAAM in the DT? By removing the node, or setting its status to disabled? I would expect the kernel *not* to turn off the clocks for a device that has `status = "disabled"` and `secure-status = "okay"`. But maybe it's not how it's supposed to work (and I can't find any reference to `secure-status` in the kernel code, only in the bindings documentation). In any case, the DT is supposed to be a description of the hardware and not much more. So, if clocks or devices have to be shared between NW and SW, some sort of protocol is probably needed. The LKML is probably a good place to discuss these things.

**Comment by jeffy1009** [comment]
I used `status = "disabled"` as done in [here](https://github.com/MrVan/linux/commit/9bdae97f6fd2f541c2f6593c26036f35e2a59194#diff-36115d249d58894aa794074a379d46dfR946)

For the moment, I just set the CLK_IGNORE_UNUSED flag for the CAAM clocks in `arch/arm/mach-imx/clk-imx6q.c` as a work around.

**Comment by jeffy1009** [comment]
Hello,

I need to access 0x00101000 which is the address for CAAM secure memory. 

memcpy'ing to that address is causing translation fault.

I see following mapping.
`DEBUG:   [0xffff] TEE-CORE:init_mem_map:439: type va 9 0x8b000000..0x8b9fffff pa 0x00000000..0x009fffff size 0xa00000`

So I used `0x8b101000` but still causing translation fault.

Could you help me?

**Comment by jeffy1009** [comment]
Nevermind.

I added new mapping with `register_phys_mem` and it works!

**Comment by MrVan** [comment]
@jeffy1009 do you have plan to upstream your code?

**Comment by jeffy1009** [comment]
@MrVan Currently all I've done is just port most of the CAAM related code in u-boot.

I think the code in u-boot is only a subset of the code in linux and CAAM code in linux is more complete.

Porting linux CAAM code from scratch could be better than adding linux code on top of my code.

I could share my code (how do I share patch file here?) but I afraid I don't have time to port linux code, or organize the code.

As a side note, Porting u-boot code was easier than I thought, but porting linux code could be a little more complex. Following are the major things I changed from u-boot code (which could help if you want to port linux CAAM code)

- disable linux code that turn off CAAM clock (but I think we can turn on CAAM clock in OP-TEE instead of changing linux code. the reason I changed linux code to not disable CAAM clock is that u-boot CAAM code checks the initialization status of CAAM by checking CAAM's output ring size register, which don't work if CAAM clocks are turned off.
- register physmem for CAAM register mapping and CAAM secure memory
- convert all CAAM access to virtual address
- change `sec_in` and `sec_out` to `read32` and `write32` (assuming all freescale targets using little-endian)
- change `flush_dcache_range` into a sequence of `cache_maintenance_l1` and `cache_maintenance_l2`

**Comment by MrVan** [comment]
@jeffy1009 I think there is no need to port full linux caam code to tee, also linux caam code is a bit complicated.  If you are willing to open source code, you could create a github repo or use `https://gist.github.com/`. Let me work on it.  I am trying to make caam both functional in linux and optee, linux caam is working in non-secure world. Have not add the caam code in TEE.

**Comment by jeffy1009** [comment]
@MrVan I've uploaded the patch files [here](https://gist.github.com/jeffy1009/a40cd16b09d87e57d4eee85624d29923).

The base u-boot version could be quite old. I don't know the exact version but README file contains 2013

**Comment by jforissier** [comment]
@jenswi-linaro is right, we can't accept code that is copied from Linux or U-Boot. You have to write it yourself, in your own way (which is probably a good thing so that it integrates better with OP-TEE).

**Comment by code-ing** [comment]
Hello, We have this imx6 based platform:

https://treats4geeks.com/

We could send you a sample, would this help?
It doesn't have a jtag connector

**Comment by jbech-linaro** [comment]
> Hello, We have this imx6 based platform:
> 
> https://treats4geeks.com/
> 
> We could send you a sample, would this help?
> It doesn't have a jtag connector

@code-ing , sorry for the late reply. Are you saying that you are willing to send the Linaro team an imx6 based development board? If that is that case, we would be grateful to get one, since we have been wanting to look into imx6 for quite a while. If I understood you correctly, please let me know and I will give you the shipping address etc.

**Comment by ranjithvs** [comment]
@MrVan @jeffy1009 @jbech-linaro  Any one working on CAAM for OP-TEE.  When I look into linux caam in non-secure world it is very complicated code. So what is the best way to start.? @MrVan you are trying to make caam both functional in linux and optee, linux caam is working in non-secure world. Have not add the caam code in TEE. any thing you worked upon...?

**Comment by jbech-linaro** [comment]
> @jbech-linaro Any one working on CAAM for OP-TEE.

I haven't (actually I have no i.MX6 device ... yet).

**Comment by MrVan** [comment]
@ranjithvs We have that in Trusty, I have not port that to OP-TEE. You could first take the uboot caam code as a reference.

**Comment by jeffy1009** [comment]
@ranjithvs I've ported some caam code from linux to OP-TEE. 
(the gist above is the caam code from u-boot, but I needed some more functionality so I ported more code from linux)
you can refer to my gist https://gist.github.com/jeffy1009/ec23aa219a4141ba12dd4df3d2caaede for patch files. 
It is based on 192cd5688293ff32779ed6d5e5861169ffe0b109 this commit.
These codes are not thoroughly tested so please use at your own risks.
Theses patches cannot be integrated into OP-TEE because of the license problems, as noted above.

**Comment by jbech-linaro** [comment]
@jeffy1009 , so the license issue here comes from that you have used CAAM code from U-boot (which is GPL). I.e., what I'm trying to say, that if someone wrote code for CAAM for OP-TEE from scratch there won't be any license issue, right?

**Comment by jeffy1009** [comment]
@jbech-linaro Yes, based on the comments from @jforissier @jenswi-linaro , I think there won't be any license issues if someone wrote CAAM for OP-TEE from scratch.

**Comment by myopensrc2015** [comment]
Hi, is the imx6 CAAM support have been added in the current OPTEE release?

**Comment by jforissier** [comment]
Hi @myopensrc2015,

No, there is still no i.MX6 CAAM support in OP-TEE. I have not heard about anyone working on a BSD-compatible implementation (license-wise).
