### ISSUE TITLE
unable to flash optee onto HiKey

### ISSUE THREAD

**Issue by Valeri99** [OP-TEE/optee_os#1296]
Hello,

A week ago I received the HiKey with 2GB RAM. 

Then I built the optee stuff according to the nice page:
https://github.com/OP-TEE/build
(No errors were detected.)

However, all attempts to flash optee onto computer failed.
More details:
It looks like, all the components are being flashed Ok, besides the normal operating system.
e.g. 

sudo make recovery 

gives:

python /home/devel/optee2/build/../burn-boot/hisi-idt.py --img1=/home/devel/optee2/build/../l-loader/l-loader.bin
+----------------------+
(' Serial: ', '/dev/serial/by-id/usb-\xe4\x95\x87\xe4\x95\x8e\xe4\xa5\x8e_\xe3\x84\xb0\xe3\x8c\xb2\xe3\x94\xb4\xe3\x9c\xb6\xe3\xa4\xb8-if00-port0')
(' Image1: ', '/home/devel/optee2/build/../l-loader/l-loader.bin')
(' Image2: ', '')
+----------------------+

('Sending', '/home/devel/optee2/build/../l-loader/l-loader.bin', '...')
Done

fastboot flash ptable /home/devel/optee2/build/../l-loader/ptable-linux-4g.img
< waiting for device >
target reported max download size of 268435456 bytes
sending 'ptable' (17 KB)...
OKAY [  0.001s]
writing 'ptable'...
OKAY [  0.002s]
finished. total time: 0.003s
fastboot flash fastboot /home/devel/optee2/build/../arm-trusted-firmware/build/hikey/release/fip.bin
target reported max download size of 268435456 bytes
sending 'fastboot' (1381 KB)...
OKAY [  0.052s]
writing 'fastboot'...
OKAY [  1.012s]
finished. total time: 1.064s
fastboot flash nvme /home/devel/optee2/build/../out/nvme.img
target reported max download size of 268435456 bytes
sending 'nvme' (128 KB)...
OKAY [  0.005s]
writing 'nvme'...
OKAY [  0.004s]
finished. total time: 0.009s
fastboot flash boot /home/devel/optee2/build/../out/boot-fat.uefi.img
target reported max download size of 268435456 bytes
sending 'boot' (65536 KB)...
OKAY [  2.221s]
writing 'boot'...
OKAY [  3.040s]
finished. total time: 5.261s
fastboot flash system /home/devel/optee2/build/../out/debian_system.img
target reported max download size of 268435456 bytes
erasing 'system'...
OKAY [  0.000s]
sending sparse 'system' (262140 KB)...
OKAY [  9.017s]
writing 'system'...
FAILED (status read failed (Protocol error))
finished. total time: 14.104s
Makefile:358: recipe for target 'flash' failed
make[1]: *** [flash] Error 1
Makefile:333: recipe for target 'recovery' failed
make: *** [recovery] Error 2

///==============

sudo make flash
gives similar crash.

///==============

I also downloaded the prebuilt latest binaries:
from 
http://builds.96boards.org/releases/hikey/linaro/binaries/latest/
and
https://builds.96boards.org/releases/hikey/linaro/debian/latest/

The flashing is still crashing in the same way.

Any help is appreciated.

Thanks.

**Comment by vchong** [comment]
Hi @Valeri99,

I'll try to reproduce and get back to you, but I need to order a 2gb which will take a while to arrive. In the meantime, can you please try below:

Under `/home/devel/optee2/build/`, run `make cleaner` just to be sure that we're starting from scratch.

Then in lines hikey_debian.mk lines 253 and 358 (also referenced below), change `linux-4g` to `linux-8g`.
https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L253
https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L358

Then redo the build and try flashing again. The 2GB board has 8GB of storage rather than 4GB. We should try to update the makefiles to to cover this.

HTH

**Comment by Valeri99** [comment]
Hi,

Thanks a lot for your help! 
Finally it works.

**Comment by vchong** [comment]
Great! That's good to know so thanks for reporting back!

I have submitted https://github.com/OP-TEE/build/pull/111 to fix this.
