### ISSUE TITLE
Question: How are TAs loaded?

### ISSUE THREAD

**Issue by JossMarley** [OP-TEE/optee_os#1298]
Hi,
I'm studying OP-TEE and I would like to understand how trusted applications are loaded, I wasn't able to find the source code for this operation. I would like to know which is the part of the code which is responsible to receive an executable (the TA itself) and to load it in memory, creating page tables, global offset table and so forth. Can you help me to understand how all of this process works? References to code are highly appreciated. Thank you

**Comment by vchong** [comment]
Try core/arch/arm/kernel/user_ta.c as a start.
Also documentation/optee_design.md#12-trusted-applications for the format.

**Comment by JossMarley** [comment]
Thank you for your answer @vchong, very useful. My situation now is the following: I have an elf file and I want to sign it (adding the header) to create a trusted application and I want to load it in the secure world and execute it. I know how to perform this steps "manually", but I would like to write an application that do this. I've studied how ta are loaded in `user_ta.c` but I cannot produce any code. Can you tell me what I should do to load and execute an arbitrary elf in the secure world?

**Comment by vchong** [comment]
You can refer to ta/arch/arm/link.mk. It looks pretty straightforward as far as 'converting' a TA .elf to a .ta file, but you can't just use any elf you want. The code used to generate the elf file has to follow certain format/structure/rules, e.g. has a unique uuid, use GP API calls, etc before the TA can be loaded and executed in secure world. See https://github.com/linaro-swg/hello_world for example.

**Comment by etienne-lms** [comment]
@JossMarley , I OP-TEE is not really designed to load arbitrary executable code in a secure environment. 
Following the GP TEE design specs, OP-TEE rather provides a secure (and featured?) execution environment for 'service' applications which in turn must conform to some rules: define identity, entry points, API with application clients, heap and stack constraints, ...

**Comment by JossMarley** [comment]
@vchong @etienne-lms thank you for your reply. `core/arch/arm/kernel/user_ta.c` is responsible of all operations related to loading a ta. Can I just use the functions defined in that file to load arbitrary executable code even if OP-TEE is not really designed to do that? If yes, can you address me on how I can do it?

**Comment by vchong** [comment]
@JossMarley Same question answered on your other post here: https://github.com/OP-TEE/optee_os/issues/1314#issuecomment-275303494

**Comment by JossMarley** [comment]
Thank you
