### ISSUE TITLE
Question: Run executables in secure world

### ISSUE THREAD

**Issue by ArnoldoM** [OP-TEE/optee_os#1304]
Hi,
I'm trying to use optee and I would like to write some code. My system needs to download a blob of code (it is the text segment of an executable file) and execute it in the trusted world. I don't know where to start, I need some sample code to get the process (my blob of code) running in the trusted world and some code to initialize all registers with values read in the secure world (or even custom values).
Could you please help me?

**Comment by lws-team** [comment]
This is a good starting point for sample code for the TA and client side

https://github.com/jenswi-linaro/lcu14_optee_hello_world/commits/master

It should be part of optee tree but it isn't.

**Comment by ArnoldoM** [comment]
Thank you, I read the hello world example but my question is another. I already have a trusted application (the blob of code which I talked about), I have also a normal world application that downloads the TA (this blob of code). Now I would like to know how I can load the TA in the trusted world from my normal world application and how I can execute it. Another thing that I would like to do is setting the values of the registers in normal and secure world.

**Comment by lws-team** [comment]
When your normal world app opens a session, if the UUID of the TA you asked to talk to is not already loaded in Secure World, `tee-supplicant` will automagically fish it out of `/lib/optee_armtz` in the Normal World filesystem and give it to Secure World.

So I dunno what your "code to load the TA in secure world" looks like, but this feature is already baked into the optee pieces: all you have to do from your client code in Normal World is give the UUID you want to talk to and stash your .ta s down the magic path `/lib/optee_armtz`.

"Setting values of registers"... what do you mean?

**Comment by ArnoldoM** [comment]
My situation is the following: I have a normal application running. This application downloads a blob of code which is supposed to run in secure world. So I have to load this code in the trusted world and execute it there. I don't know the UUID, I have just a text segment that should be executed in the trusted world.

**Comment by lws-team** [comment]
What OP-TEE wants you to do is to put that code in a TA and load it as I described.  The TA is built with a UUID.  Maybe you should back up and try follow what OP-TEE wants you to do...

**Comment by ArnoldoM** [comment]
I don't have always the code ready to use, I would like to do that starting from text segments of already compiled binaries. Is there a fast way to reconstruct a TA starting from such a situation?

**Comment by ArnoldoM** [comment]
Ah ok, I read the format for a TA, I just have to get my elf and add to it a signed header.

**Comment by ArnoldoM** [comment]
So how can I get the UUID? I can't find /lib/optee_armtz!
