### ISSUE TITLE
Adding another dynamic TA

### ISSUE THREAD

**Issue by booble89** [OP-TEE/optee_os#1310]
I am beginner in OPTEE
I tried the hello world TA and its client and I can successfully see the results. But I am wondering how I can add another simple dynamic TA so I can have two TAs running at the same time.

**Comment by lackan** [comment]
There are all kinds of TAs in https://github.com/OP-TEE/optee_test, you can try to use them.
And if you just want to run two TAs at the same time, you can just run such as: 
`hello_world& hello_world&`

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
