### ISSUE TITLE
OP-TEE vs kexec

### ISSUE THREAD

**Issue by lws-team** [OP-TEE/optee_os#1312]
If I boot into Linux on Hikey, using the eMMC system partition with Debian, I can run xtest three times (presumably more too) in succession without problems.  Every result now (after disabling v8 AES acceleration support) is

```
23571 subtests of which 0 failed
70 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

If I reboot, and without using OP-TEE client side, kexec into the same kernel image, with same dtb, again with eMMC system (/dev/mmcblk0p9) with Debian, same tee-supplicant, libteec and TAs, xtest can also work well in the kexec'd kernel.  So everything up to here is very nicely working.

However... if I run xtest (successfully) one time in the first kernel, when I kexec into the second kernel, xtest can no longer run successfully.  The attempt in the second kernel looks like this

```
# tee-supplicant & xtest
[1] 2960
Run test suite with lev[   13.860680] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
el=0

TEE test a[   13.870726] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
pplication started[   13.880799] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
 with device [(nul[   13.890906] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
l)]
#############[   13.900978] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
##################[   13.911084] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
#################[   13.921078] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
######
#
# regr[   13.931078] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
ession
#
######[   13.941063] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
#################[   13.951051] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
#################[   13.961039] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
##############
 [   13.971035] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed

* regression_100[   13.981033] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
[   13.991110] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed

  regression_1001[   14.001184] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
 OK
 
* regressi[   14.011262] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
on_1004 Test User [   14.021336] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
Crypt TA
/project[   14.031412] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
s/aist-tb/optee_te[   14.041490] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
st/host/xtest/xte[   14.051564] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
st_1000.c:288: xt[   14.061554] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
est_teec_open_ses[   14.071541] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
sion( &session, &[   14.081531] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
crypt_user_ta_uui[   14.091521] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
d, ((void *)0), &r[   14.101526] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
et_orig) has an un[   14.111620] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
expected value: 0x[   14.121679] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
ffff0000 = TEEC_E[   14.131743] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
RROR_GENERIC, exp[   14.141732] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
ected 0x0 = TEEC_[   14.151723] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
SUCCESS
  regress[   14.161713] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
ion_1004 FAILED
 [   14.171791] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033306c00 failed
...
```

Does this scenario violate some expectation that the kernel driver part or the tee-supplicant part and the OP-TEE part are somehow synchronized wrt VAs?  Or in some way does using OP-TEE in the first kernel session "leave it dirty" in the second kernel session?

**Comment by lws-team** [comment]
The problem seems to be that OP-TEE asks for shm "handles" from the kernel driver; these are VA of allocated shm objects from the kernel driver.

OP-TEE caches these, and uses them to pass parameters.

Since OP-TEE does not know that the kernel went away and a new kernel started, next time we talk to it from the new kexec'd kernel session, it gives us a cached shm VA "handle" from the old kernel instance.  That points somewhere else in the new kernel.

Here is the end of the xtest in the first kernel (completely successful with expected error shown)

```
ERROR:   TEE-CORE: Error code=f0100001
ERROR:   TEE-CORE: Object corrupt
[  361.297448] OPTEE_SMC_RPC_FUNC_CMD shm: ffff800033a90a00
[  361.302906] OPTEE_SMC_RPC_FUNC_CMD shm: ffff800033a90a00
[  361.308665] OPTEE_SMC_RPC_FUNC_CMD shm: ffff800033a90a00
[  361.314639] OPTEE_SMC_RPC_FUNC_CMD shm: ffff800033a90a00
[  361.320062] OPTEE_SMC_RPC_FUNC_CMD shm: ffff800033a90a00
[  361.325690] OPTEE_SMC_RPC_FUNC_CMD shm: ffff800033a90a00
  regression_20523.2 OK
  regression_20523 OK
+-----------------------------------------------------
Result of testsuite regression:
...
```

OP-TEE is using shm handle 0xffff800033a90a00.

After the kexec, I run xtest again

```
# tee-supplicant & xtest
[1] 2971
Run test suite with lev[   15.250977] optee firmware:optee: handle_rpc_func_cmd: tee_shm_get_va ffff800033a90a00 failed
el=0
...
```

Therefore it seems something is missing.... the kernel should inform OP-TEE that it is a new kernel and all cached RPC handles must be discarded.

Does this make sense / sound right?

**Comment by etienne-lms** [comment]
makes sense. rahter a some "wipe NonSecure cache" at NS OS init ? or a "release OS resource" before exiting old OS? This could apply if a nonsecure boot stage communicates with OP-TEE OS before linux is booted.

**Comment by lws-team** [comment]
Yeah, "release" sounds maybe a better fit.  And you're right, it's not just kexec if there is a second stage bootloader who wants to query something the same problem will come.

I'll take a look at understanding the caching business and report back later.

**Comment by jenswi-linaro** [comment]
The function `optee_disable_shm_cache()` in the OP-TEE driver probably does what you need.

**Comment by lws-team** [comment]
Sounds good, thanks.

**Comment by lws-team** [comment]
It turned out almost everything was already implemented to do the invalidation.  All that was needed was a few extra lines wiring up platform_data .shutdown.  See the top two patches here (the first one is cosmetic, it just corrects a cut-and-paste error in a comment)

https://github.com/lws-team/linux/commits/fix-kexec

I confirmed now I can use OP-TEE in the second kernel instance, and xtest can run in both the first and second instances before and after kexec without any errors.

I couldn't find the correct remote for the original basis tree with the optee patches on any more, if you want a PR there please remind me of the coordinates.

**Comment by vchong** [comment]
Good work! :)
https://github.com/linaro-swg/linux/ (optee branch)
