### ISSUE TITLE
Loading bin files

### ISSUE THREAD

**Issue by JossMarley** [OP-TEE/optee_os#1314]
Hi,

how can I load bin files (not entire elf) in secure world and execute them?

**Comment by vchong** [comment]
See https://github.com/OP-TEE/optee_os/issues/1304 for reference. The author deleted all his comments, but they were as below. Looks like he's trying to do the same thing? Are you guys maybe associated in some ways?

Question: Run executables in secure world
Hi,
I'm trying to use optee and I would like to write some code. My system needs to download a blob of code (it is the text segment of an executable file) and execute it in the trusted world. I don't know where to start, I need some sample code to get the process (my blob of code) running in the trusted world and some code to initialize all registers with values read in the normal world (or even custom values).
Could you please help me?

> This is a good starting point for sample code for the TA and client side
> https://github.com/jenswi-linaro/lcu14_optee_hello_world/commits/master
> It should be part of optee tree but it isn't.

Thank you, I read the hello world example but my question is another. I already have a trusted application (the blob of code which I talked about), I have also a normal world application that downloads the TA (this blob of code). Now I would like to know how I can load the TA in the trusted world from my normal world application and how I can execute it. Another thing that I would like to do is setting the values of the registers in normal and secure world.

> When your normal world app opens a session, if the UUID of the TA you asked to talk to is not already loaded in Secure World, tee-supplicant will automagically fish it out of /lib/optee_armtz in the Normal World filesystem and give it to Secure World.
> So I dunno what your "code to load the TA in secure world" looks like, but this feature is already baked into the optee pieces: all you have to do from your client code in Normal World is give the UUID you want to talk to and stash your .ta s down the magic path /lib/optee_armtz.
> "Setting values of registers"... what do you mean?

My situation is the following: I have a normal application running. This application downloads a blob of code which is supposed to run in secure world. So I have to load this code in the trusted world and execute it there. I don't know the UUID, I have just a text segment that should be executed in the trusted world.

> What OP-TEE wants you to do is to put that code in a TA and load it as I described. The TA is built with a UUID. Maybe you should back up and try follow what OP-TEE wants you to do...

I don't have always the code ready to use, I would like to do that starting from text segments of already compiled binaries. Is there a fast way to reconstruct a TA starting from such a situation?

Ah ok, I read the format for a TA, I just have to get my elf and add to it a signed header.

**Comment by JossMarley** [comment]
@vchong Yeah, it looks like we're doing the same thing, but I'm not associate with anybody. I imagine that when he talks about "blobs" he is referring to bin files... Anyway, the answer given didn't provide a way to load these bin/blobs. It is assumed that we have complete trusted applications, but what is supposed to do if we just have a generic bin?

**Comment by ArnoldoM** [comment]
@vchong I deleted my comments and you should respect my choice...

**Comment by lws-team** [comment]
@ArnoldoM  You published your comments on a public forum that Google indexes... you no longer have control of it... same as sending an email on a mailing list...

**Comment by lws-team** [comment]
@JossMarley what I was trying to explain to the OP... OP-TEE says give it a properly-signed TA and it / tee-supplicant will deal with everything.  Or you can build your stuff into OP-TEE OS itself as a Static / Pseudo TA.

You cannot get Secure World to run arbitrary bleeding chunks of code, at least not unless you write a "load chunks of insecure code and bypass all security" TA.  The TA signature is checked to confirm it's from the keypair that the OP-TEE OS part has the public key for before it will let it in.  Being able to inject attacks would make the concept of a Secure World pointless, right?

**Comment by vchong** [comment]
@ArnoldoM Sorry! I wasn't aware of the circumstances or reasons of which the comments were deleted. I'll remove your comments here as well, but please note that, as @lws-team had mentioned, this is a public forum and your comments had already gone out to 90 users watching this repo and possibly indexed and archived by other sites on the web as well. There really is no undoing of anything after clicking send.

@lws-team Thanks!

@JossMarley As noted above, it kind of defeats the purpose of security if you can just run anything you want. Is it ok to close this issue?

**Comment by JossMarley** [comment]
Thank you so much for your help. I close the issue.
