### ISSUE TITLE
xtest AES performance test broken

### ISSUE THREAD

**Issue by etienne-lms** [OP-TEE/optee_os#1321]
Since commit https://github.com/OP-TEE/optee_os/commit/b1ecda78bab43d76bc570ecff30ddd232caecf18 ("libutee: fix off-by-one error in tee_buffer_update()"), is merged, xtest AES perf tool is broken.

Since the changed, the AES CipherUpdate from AES perf TA get "SHORT_BUFFER".
Not yet found where is the issue...

**Comment by jforissier** [comment]
Should be fixed by https://github.com/OP-TEE/optee_os/pull/1315.

**Comment by etienne-lms** [comment]
right, confirmed regarding AES perfs test.
thanks. closed.
