### ISSUE TITLE
HiKey: xtest 8040 (GP) fails when CFG_PAGED_USER_TA=y

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#1323]
Current master (bf7a587) fails `xtest 8040` on HiKey when `CFG_WITH_PAGER=y`:
```
root@HiKey:/ xtest 8040
Test ID: 8040
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# regression
#
######################################################
 
* regression_8040 a7-42-f9
/home/jerome/work/hikey_optee/optee_test/host/xtest/xtest_8000.c:704: Invoke_Simple_Function(c, SESSION01, 0x00000204) has an unexpected value: 0xffff0000, expected 0x0
  regression_8040 FAILED
+-----------------------------------------------------
Result of testsuite regression filtered by "8040":
regression_8040 FAILED first error at /home/jerome/work/hikey_optee/optee_test/host/xtest/xtest_8000.c:704
+-----------------------------------------------------
11 subtests of which 1 failed
1 test case of which 1 failed
714 test cases was skipped
TEE test application done!
root@HiKey:/ 
```

Note that:
- The test is successful if `CFG_PAGED_USER_TA=n`
- `git bisect` points to d8555bdd2c26 ("core: add paged secure shared memory")

**Comment by jenswi-linaro** [comment]
I suppose this test calls another TA from a TA and uses some buffers in internal memory. I wonder what's the significant difference from xtest 1011.

**Comment by etienne-lms** [comment]
Testing today's optee's top master branches on my b2260 with pager+paged-tas gives me some nice pager panics on 8040. 
xtest standard (non GP) tests run ok. All GP tests run OK but 8040! Various symptoms: assertions, when enabled, unexpected data-aborts, or simply test failure, depending on configuration, but symptoms are quite systematic for a given test setup
As jerome stated, not reproduced with `CFG_PAGED_USER_TA=n`.

**Comment by etienne-lms** [comment]
Reproduced on **vexpress-qemu_virtwith** pager fixed (i'll push a PR: need to fix TA_RAM location): test ok but 8040 that panics core on translation fault.

**Comment by etienne-lms** [comment]
about enabling pager on qemu, I strangely could not use the [0e00.0000 0e10.0000] for core and page-store. Here is a hack => move TA_RAM in TZ reserved DDRAM0.

###
```
--- a/core/arch/arm/plat-vexpress/platform_config.h
+++ b/core/arch/arm/plat-vexpress/platform_config.h
@@ -193,8 +193,8 @@
 #define TZSRAM_BASE		0x0e000000
 #define TZSRAM_SIZE		CFG_CORE_TZSRAM_EMUL_SIZE
 
-#define TZDRAM_BASE		(TZSRAM_BASE + TZSRAM_SIZE)
-#define TZDRAM_SIZE		(0x01000000 - TZSRAM_SIZE)
+#define TZDRAM_BASE		0x7E000000 //(TZSRAM_BASE + TZSRAM_SIZE)
+#define TZDRAM_SIZE		0x02000000 //(0x01000000 - TZSRAM_SIZE)
 
 #else /* CFG_WITH_PAGER */
 
```

**Comment by jenswi-linaro** [comment]
Why is this change needed? I'm using what's on master all the time, I suspect that something is wrong in your setup.

**Comment by etienne-lms** [comment]
i'll cross check my setup. might be a dis-alignment...
the point is that I think the issue is not related to cache, as qemu fails on it.

**Comment by jforissier** [comment]
Testing again on HiKey with latest master, I'm not having an error status any more, instead TEE core asserts. As suggested by @etienne-lms I've tried QEMU, did not need to hack the memory layout, it also asserts but at a different place than HiKey. Interestingly, `xtest 8040` runs normally on QEMU if LPAE is enabled...
Some dumps at https://pastebin.linaro.org/view/90f0df18

**Comment by etienne-lms** [comment]
@jenswi-linaro, thanks, indeed my bios_qemu was a bit old. no need to patch optee_core for qemu.

I checked the differences between 1011 and 8040 but there are not much: TA private mem used is in the stack vs the heap, and nore in/out/inout memref params passed at each TA invocation. I modified 1011 to reflect those "differences" but 1011 remains stable while 8040 is not.

**Comment by jenswi-linaro** [comment]
I guess you've noticed by now that these kinds of errors are very tricky to debug. I suspect that something goes wrong below `transfer_tables()` which sometimes panics directly and sometimes causes `tee_pager_unhide_page()` to panic.
Since it's working with LPAE on hikey, perhaps there's some boundary crossed when using the v7 tables.

**Comment by jforissier** [comment]
@jenswi-linaro it's working with LPAE on QEMU but not on HiKey which has LPAE always set.

**Comment by etienne-lms** [comment]
i could not find any root of cause and failed to reproduce the issue with the xtest 1011...

**Comment by etienne-lms** [comment]
At least found the diff between 8040 and 1011 that trig the failure: TA invokes TA several times with "private memory" memrefs. Here a [patch](https://drive.google.com/open?id=0B9imFTR69u-QelNxOUswazZGanM) to reproduce with `xtest 1011`.
Root cause not found yet but at least we can share the test setup.

**Comment by jenswi-linaro** [comment]
Thanks for the patch, I think I've nailed it in https://github.com/OP-TEE/optee_os/pull/1339
Please test.

**Comment by jforissier** [comment]
@jenswi-linaro works for me! Congrats!

**Comment by rahul-janani** [comment]
how to create new test case in optee os ? if i want to test any api what is the procedure to follow create new test case.

**Comment by rahul-janani** [comment]
my task is to create new test case in optee os ,for example i want to test adding two variables functionality for this how to create test case in optee os ? I am new to this ,could you please help me to do this.
