### ISSUE TITLE
Using sprintf() inside TA

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1324]
I am trying to use a the sprintf() function inside TA code.
I included stdio.h. (# include <stdio.h>)

In the TA, I use the following:

```c
char test[20];
int a = 3;
sprintf(test, "var is %d", a);

```
On compilation I get the errors:

```bash
hello_world_ta.c:193:9: error: implicit declaration of function 'sprintf' [-Werror=implicit-function-declaration]
          sprintf(test, "var is %d", a);
          ^
 hello_world_ta.c:193:9: error: incompatible implicit declaration of built-in function 'sprintf' [-Werror]
``` 

How can I use sprintf() inside TA code ? I am using dynamic TA.

**Comment by jforissier** [comment]
Hi @a2t2,

`sprintf()` is bad. Use `snprintf()` instead.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
