### ISSUE TITLE
Managing mount state of secure storage partition

### ISSUE THREAD

**Issue by lws-team** [OP-TEE/optee_os#1325]
I think it's maybe not such an unusual situation that Secure Storage is only, or mainly, used to hold keys or certs that are very seldom if ever updated or added to.

For example it's not so strange if certs go in there at the factory and will never change for the device lifetime.  Since TAs are unencrypted, they cannot contain any secrets, meaning they must go in Secure Storage.

For that kind of usage, the cert lifetime and binding is unrelated to the main "system" OS lifetime... the cert is bound to the device for life, whereas the OS image is transient and has no intrinsic customization for the device.

Therefore at least for these cases, it makes sense to have /data its own partition with its own filesystem.

If writes are unexpected or uncommon, it's desirable to keep the filesystem on `/data` mounted read-only.  If there is some problem like unexpected powerdown and the fs becomes corrupted since it was being written to for metadata or whatever, that would be a major problem in the case the cert is used to give the device identity and authentication.

The issue with doing this all outside tee-supplicant is that it will typically be the TA who decides he wants to write the certs.  The storage is opaque to userland.

So I would like to suggest adding some way in tee-supplicant to manage /data mount state, either explicitly as in adding new apis or implicitly as in adding counters and hooks around functions that want write access that are used to manage the mount state if the device's userland needs it.

Edit: There is also the case to consider that once in the TA and trying to use the storage, it finds an unreasonable situation like a corruption, which was not visible at mount-time.  At the moment he just bricks.  If he can stop panicking for long enough ^^ recovery would look like Normal World reformat the /data partition and reboot... next time around TA would see he is unprovisioned and divert to trying the provisioning process.

Does it make sense?  Any thoughts?

**Comment by lws-team** [comment]
I found today this is killing me... basically there is no relationship between OP-TEE thinking it has created something in Secure Storage and the actual commit to flash.  My files were created but next boot were corrupted since no synchronous flush through ext4 -> eMMC.

There seems to be a missing step somewhere for a real system to unconditionally commit it.... it's not a ree_fs specific issue either since the other fs can have similar backing layers.  In my case I added a reference counting RPC + Syscall that wraps stuff in my TA that will perform write actions; the first guy that request write access remounts /data rw and the last guy giving up the write access remounts it ro... and it starts off ro.

Since this isn't in the official TEE stuff I guess it gets a rough ride here... so then what is the recommended way to deal with it?

**Comment by jenswi-linaro** [comment]
If we're talking about REE FS you could try adding `O_DSYNC` whenever tee-supplicant is opening a file.

**Comment by lws-team** [comment]
Thanks... it won't help with wanting to keep the mount ro at boot and all the time except when the TA decides it wants to write something, though.

**Comment by jenswi-linaro** [comment]
True

**Comment by lws-team** [comment]
ree_fs_new_open() in tee_supp_fs.c just does this, even if the file was not opened needing write permissions.

```
	fd = open_wrapper(abs_filename, O_RDWR);
```

this is fundamentally incompatible with a RO /data.  I am guessing whatever standards apply here do not mandate (or probably even mention) that the storage area in REE must be writeable?

**Comment by lws-team** [comment]
Making him fall back to O_RDONLY if O_RDWR failed is enough to allow RO operations on RO-mounted /data for me.

https://github.com/OP-TEE/optee_client/pull/77

**Comment by lws-team** [comment]
(Continuing from discussion on PR above)

It has to be written at least once in order to have anything read, right?  The whole idea of Secure Storage is we have to write it from "inside" the TA that first time too since the crypto is customized for the device.  So the refcounting is aimed at managing that.

Other TAs may want to write asynchronously.... there is serialization of ree fs actions but other OP-TEE fses like SQL may be backed by the same real REE fs, even though they are not logically linked inside OP-TEE.

I'll be very happy if you have a better idea that hits the same marks.

**Comment by jenswi-linaro** [comment]
I'm not a storage guy, but surely there has to be a file system which is crash safe enough to keep it RW mounted.

For provisioned certificates etc I can see benefits in keeping them in a RO location which only can be updated while the system is in production mode.

**Comment by lws-team** [comment]
> I'm not a storage guy, but surely there has to be a file system which is crash safe enough to keep it RW mounted.

I think rather than OP-TEE being in the architectural position to decide that for the whole system, it's a decision that is taken considering specifics of the system.

It being Linux the filesystem may be in raw NAND, serial EEPROM - both of which may have hardware WE pins - or have other constraints like erase / write cycles.

Since writes are very unusual for my case, the crash-after-write part is a lesser issue if it is mounted ro normally.  But for other use cases that is what their product is doing all the time.  VFAT certainly can get trouble if it is repeatedly mounted rw and randomly powered off and ext4 can suffer 0 length "metadata-only" files after a crash and maybe other commit issues.  If your TA is in a real product, these would be a real problem.  What is the better filesystem that doesn't have these problems?

However if you think it is "out of scope" for OP-TEE I can understand it and just keep OOT patches.  But I think for real implementations they must deal with it.
