### ISSUE TITLE
const missing in standardized apis?

### ISSUE THREAD

**Issue by lws-team** [OP-TEE/optee_os#1326]
For these guys....

```
/* Property access functions */

TEE_Result TEE_GetPropertyAsString(TEE_PropSetHandle propsetOrEnumerator,
                                   char *name, char *valueBuffer,
                                   uint32_t *valueBufferLen);

TEE_Result TEE_GetPropertyAsBool(TEE_PropSetHandle propsetOrEnumerator,
                                 char *name, bool *value);

TEE_Result TEE_GetPropertyAsU32(TEE_PropSetHandle propsetOrEnumerator,
                                char *name, uint32_t *value);

TEE_Result TEE_GetPropertyAsBinaryBlock(TEE_PropSetHandle propsetOrEnumerator,
                                        char *name, void *valueBuffer,
                                        uint32_t *valueBufferLen);

TEE_Result TEE_GetPropertyAsUUID(TEE_PropSetHandle propsetOrEnumerator,
                                 char *name, TEE_UUID *value);

TEE_Result TEE_GetPropertyAsIdentity(TEE_PropSetHandle propsetOrEnumerator,
                                     char *name, TEE_Identity *value);
```

It should all be `const char *name`?  Is that broken in the standard?

**Comment by jforissier** [comment]
Hi @lws-team ,

Well spotted! It's actually broken in our implementation. In the standard, these function use the `[instring]` annotation for `name`. And section _3.4 Parameter Annotations_ reads:

> The `[in]`, `[inbuf]`, `[instring]`, `[instringopt]`, and `[ctx]` annotations can make use of the `const` `C` keyword [...]. The C header file of a compliant Implementation SHOULD use the `const` keyword when these annotations appear.

**Comment by lws-team** [comment]
OK... I'll send a patch later.

**Comment by jforissier** [comment]
Thanks. Or I can do it myself if you wish, because there are other functions that need a `const`, I mean do you have the spec to check them out?

**Comment by lws-team** [comment]
Ah no go ahead then, no worries.

**Comment by jforissier** [comment]
OK, will do.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/1327
