### ISSUE TITLE
OP-TEE OS Forwarding IRQ Issue

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#1333]
Hi experts,

I'm currently developing a security extension running on Trusted OS. 
My extension requires continuously executing in Trusted OS which means I hope it will not be stopped by any Normal World operation.

I just checked the document about [interrupt handling](https://github.com/OP-TEE/optee_os/blob/master/documentation/interrupt_handling.md) and the document mentions that once Trusted OS receives an IRQ, Trusted OS would forward it to the Normal World.
Based on my understanding, in this case, any process running in the Trusted OS could be stopped by the Normal OS. Furthermore, the TZ-process only could resume after the Normal OS returns from the IRQ.

I want to confirm my understanding is correct or not.
If my understanding is correct, is there any way for me to let my extension block all IRQs until it's finished? (so far I am developing a STA as the extension while any other solution is acceptable.)

Also, I want to ask where is the code about "forwarding IRQ from Trusted OS to Normal World"?

Thank you very much.

Simon

**Comment by jenswi-linaro** [comment]
You can block IRQ with `thread_mask_exceptions()`.
Forwarding of IRQ starts at `thread_irq_handler()` in `core/arch/arm/kernel/thread_a32.S`

**Comment by SimonWan** [comment]
Got it, thanks.
