### ISSUE TITLE
memory map question

### ISSUE THREAD

**Issue by zhizhouzh** [OP-TEE/optee_os#1337]
Hi,

I'm reading memory mapping code in optee_os, the following code get me a little confused. I didn't get why reverse the list when map->pa is above a point. I think we can always use ROUNDUP to walk upward va. It will be more simple. Did I miss some details?

Another question is va could be large than 32-bit. In struct optee_msg_arg we declare session as a uint32_t. session is cut from a 64-bit value(arg->session = (vaddr_t)out.sess;). I think, we should limited return value of calloc to 0-4G. Or high 32-bit may be thrown unintentional.

```c
        if (core_mmu_place_tee_ram_at_top(map->pa)) {
                va = map->va;
                map++;
                while (map->type != MEM_AREA_NOTYPE) {
                        map->attr = core_mmu_type_to_attr(map->type);
                        va -= map->size;
                        map->va = va;
                        map++;
                }
                /*
                 * The memory map should be sorted by virtual address
                 * when this function returns. As we're assigning va in
                 * the oposite direction we need to reverse the list.
                 */
                for (n = 0; n < last / 2; n++) {
                        struct tee_mmap_region r;

                        r = memory_map[last - n - 1];
                        memory_map[last - n - 1] = memory_map[n];
                        memory_map[n] = r;
                }
        } else {
```

**Comment by prime-zeng** [comment]
For the first region, the va is set to equal to the pa, the following regions will use increasing va to walk if the starting va is not at top(>2G) or  decreasing while the starting va is at top.  This is designed to avoid va overflow i think, for example, if the first region pa is 0xfff00000,  and the va is the same, if we use increasing va, the va will easy get overflow.

**Comment by zhizhouzh** [comment]
@prime-zeng That make sense. However, if va is higher than 0xffffffff, it brings some problems. To my opinion, we don't need to assign va equal to pa even for TEE_RAM. Just do a trick as linux do, jump to new va after turning on mmu. I think a fixed virtual address memory layout would be more succinct.

**Comment by jenswi-linaro** [comment]
So far we haven't faced a platform where the physical TEE_RAM has an address larger than `0xffffffff`, until then the problem with the session pointer is of a different nature. Long-term we should avoid leaking secure world pointers to normal world.

Regarding using identity map (where virtual and physical address is the same) of TEE_RAM. Letting go of that would make the partitioning of the virtual memory space easier, but the boot code and possibly some power management code would be more complicated.

In order to be able to turn off MMU we'd need to run that code in at least temporarily identity mapped memory (or use some platform specific trick that may be hard to replicate), this would put a slight restriction on how we can partition the virtual memory space. Currently I don't see that the advantages are greater than the disadvantages.

**Comment by zhizhouzh** [comment]
@jenswi-linaro Thanks for reply. Unfortunately my SoC is using physical address larger than `0xffffffff`. So all virtual address are 64-bit. So far I faced several problems:

- `ADDR_SPACE_SIZE` defined in `core/arch/arm/mm/core_mmu_lpae.c` is 32. Which lead tcr configure limited address space.
- `load_addr` defined in `struct user_ta_ctx` is 32-bit.
- `session` is convert from a virtual address.
- build error, which is fixed with the patch in pull request.

In my opinion, if we limited all virtual addresses between 0-4G, most problems are solved. And I think optee-os will never need 64-bit address space. I'm not quite familiar to `optee-os`. Could you help to point a gentle way to solve my problem?

**Comment by jenswi-linaro** [comment]
@zhizhouzh Interesting, I was wondering if/when we'd ever have to face this. I assume we're talking about a ARMv8-A platform using ARM-TF.

I agree that it's probably easier to run with a 0-4G VA space than something else. With ARM-TF you'll probably never need to disable MMU at `S-EL1` where OP-TEE runs.

To avoid building the translation tables in assembly you'll need to have some initial tables generated at build time, shouldn't be too hard to do with some macros. Once you enable MMU you'll get a prefetch abort since `PC` will not have been updated to a virtual address, I suppose this can be handled with a temporary vector. You'll probably need to fix a couple of bugs related to invalid assumptions about TEE_MEM being identity mapped.

If this turns out well I think we can consider switching some other ARMv8-A platform to this scheme too (or at least with a config option) as we probably can save some memory by using an optimized VA space layout.

**Comment by etienne-lms** [comment]
Shouldn't extending to more than 4GB map range cost only 2 extra mmu tables (that still makes 8kB of RAM!):
- an extra table for the level1 table to cover several GB
- an extra table for the level2 table for target 1GB range where `vcore` is located?

**Comment by jenswi-linaro** [comment]
@etienne-lms , yes, but then there's assumptions here and there that we're only using 0-4G so some work is needed too.

**Comment by zhizhouzh** [comment]
@jenswi-linaro I am trying to do something today. It seems to be not good to catch a prefetch abort after turn on MMU . Since the next PC's value is possibly to be already mapped in page table, so there may be no prefetch abort, and go to the wrong VA to execute.

You had mentioned "we probably can save some memory by using an optimized VA space layout.". I didn't get it. Could you explain how to do and why can save some memory?

Another problem, do we need to unify CFG_TEE_LOAD_ADDR for each board? If VA is not tied to PA. I think we can link the target objects to a fixed address. And it will help for debugging. I tried to set CFG_TEE_LOAD_ADDR to 0, but a lot problems occurred before turn on MMU.

**Comment by jenswi-linaro** [comment]
@zhizhouzh I think we should try to only solve one problem at a time here. Given that your PA is above 4G and you only use VA in 0-4G range you'll never have a valid virtual address matching your PA.

With an optimal VA layout you can minimize the number of translation tables needed, and save memory by using fewer translation tables.

We're already linking to a fixed address, specific for each platform. At least some (maybe all) of the ARMv7-A platforms will regardless need to keep the current setup with identity mapped TEE_RAM.

**Comment by zhizhouzh** [comment]
@jenswi-linaro  Thank you for quick response. So it seems this can't be a general solution for ARMv8. It's more like an option for ARMv8 with large PA. I think this patch will change a lot, as you mentioned,  we need to fix a couple of bugs. If this option is off for most users. I'm afraid it will be buggy and hard to maintain.

How about to pick 2GB (more or less, by the way, how much VA space is enough for OPTEE?), these addresses are not overlap with TEE_LOAD_ADDR (physical address). Before turn on mmu, create two mapping to TEE_RAM, one for identity mapping, one for general mapping. After turn on mmu, we switch to use general mapping address.

Thank you for you patience.

**Comment by jenswi-linaro** [comment]
If we make sure this solution runs on one of the plat-vexpress variants (preferably FVP or qemu_armv8a) it will not be that hard to keep it working.

I'd stick to the normal 4G space, but I guess 2G would be more than enough.

**Comment by zhizhouzh** [comment]
@jenswi-linaro 
Thank you, I tried to work it out but failed. First I modify CFG_TEE_LOAD_ADDR to 0. That make my tee.elf linked from 0. If everything is OK, after I turned on MMU, the system will see the right virtual address. But before turn on MMU, the CPU have to do a lot thing. And the CPU access some address that is not PC relative address.

For example, `&__start_phys_mem_map_section` and `&__end_phys_mem_map_section` in `core/arch/arm/mm/core_mmu.c` come from link script. They are not available before turning on MMU unless in identity mapping case. Another example, `trace_ext_prefix` in lib/libutils/ext/trace.c is load from another address. of cause the address is not calculated from PC. Maybe there some more other similar cases.

If I didn't change CFG_TEE_LOAD_ADDR, after turn on MMU, the same problem will wait there.

So it seems if we want to use non-identity mapping, we should turn on MMU as early as possible. I start to believe moving to 64-bit address will be more simple...

**Comment by jenswi-linaro** [comment]
All the code that execute before MMU is enabled has to be position independent code. Given the circumstances, that's special assembly code. So it's a bit inconvenient to build dynamic translation tables before MMU is enabled. You can without too much effort craft a suitable top level translation table (that maps using 1G granularity but that's not a problem if you have caching disabled to avoid speculative prefetching and the need to clean caches when switching to the translation tables generated with `core_init_mmu_map()`.

You should probably not set `CFG_TEE_LOAD_ADDR` to `0`, `1G` would be more suitable. Keeping the first `1G` unmapped to catch NULL dereferencing.

Yes, perhaps it's easier keep the identity mapping of TEE_RAM.
