### ISSUE TITLE
Access Normal World Physical Address from OPTEE

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#1343]
Hi there,

I'm trying to develop a security tool in trusted world for conducting integrity check about the normal OS's kernel. By doing this I can always know the kernel's integrity and decide to trust the normal world OS or not.

To develop this tool, I need to scan the entire normal OS kernel's memory from trusted world. The only way I come out with is that scanning the memory according to the physical address.

I'm wondering is there anyway for the OPTEE to access the normal world memory according to the physical address? 

I also found a [similar issue](https://github.com/OP-TEE/optee_os/issues/404) before. However, the solution in that issue mentioned `bootcfg_memory_map` and I can't find this in my OPTEE workspace.

So my question has two parts: 1) If OPTEE could access normal world memory, please let me know the method; 2) If there is no way like the 2015 issue, do you have any idea about how to do this?

Thank you in advanced.

**Comment by vchong** [comment]
I think you can still use the same concept/approach but instead of mapping the address in `bootcfg_memory_map` which has been deprecated when the core switched to non-linear mapping, use `register_pys_mem` like in https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/core_mmu.c#L104.

**Comment by SimonWan** [comment]
@vchong thank you for the answer. 
By reading the example you gave, my understanding is that `register_pys_mem` could add the specific memory address into the OPTEE_OS MMU and I think I should register the normal world kernel memory as type `MEM_AREA_RAM_NSEC` for my case. 
Could you please check my understanding is right or not?

Also, all the header files I found only define the PA values of TZ so I'm wondering is there any file includes any information about what PA range the normal world uses?

Best regards.

**Comment by vchong** [comment]
@SimonWan You're welcome.

Yes, that's right.

No, there's no such file. It's platform dependent, and I think you should be able to know the memory mapping for the system from either the kernel or normal world bootloader like uefi/edk2 or u-boot.

Also found several other related issues: https://github.com/OP-TEE/optee_os/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22physical%20address%22%20AND%20%22normal%20world%22, especially https://github.com/OP-TEE/optee_os/issues/1249 and https://github.com/OP-TEE/optee_os/issues/803.

**Comment by SimonWan** [comment]
@vchong got it. I'll check the platform related document to look for this information, thanks.

**Comment by SimonWan** [comment]
Hi @vchong ,

Sorry I have to reopen the issue again.
Recently I found a way to figure out the physical address of NS world that I want to read in OPTEE so I test the method you told me above.

The address I want to read is `0x80080000 - 0x80b1ffff`, and the size is `0xa9ffff`.
I added a function `register_phys_mem(MEM_AREA_RAM_NSEC, 0x80080000, 0xa9ffff)` right after the example you gave me.

However, by doing this, my equipment cannot boot up anymore.

The booting procedure is stuck after these outputs:                            
```
INFO:    ARM GICv2 driver initialized                                           
INFO:    BL31: Initializing runtime services                                    
INFO:    BL31: Initializing BL32 
```
and my secure world port outputs `Panic` after `init_mem_map type va 9 - 1` .

I also tried a simpler function `register_phys_mem(MEM_AREA_RAM_NSEC, 0x80000000, 0x1)` while the procedure still got stuck on the same step.

Could you please take a look and let me know:
1) Do I use the register_phys_mem correctly?
2) Should I do anything else to map those pa for OPTEE to access?

Thank you very much.

**Comment by vchong** [comment]
Hi @SimonWan Can you please attach the boot log?

**Comment by SimonWan** [comment]
Hi @vchong , I just tested twice this morning. 

For the first time I annotated my code: `register_phys_mem(MEM_AREA_RAM_NSEC, 0x80000000, 0x1);` in `core_mmu.c` and I booted the board successfully.
For the second time. I put the code back and here are the boot logs I got:
`Writing File board.dtb to Flash Address 0x0A700000                              
                                                                                
Image: board.dtb UPDATED from \SOFTWARE\juno-r1.dtb                             
Erasing Flash image ramdisk.img                                                 
.                                                                               
Erasing Flash                                                                   
.                                                                               
Writing File ramdisk.img to Flash Address 0x09800000                            
                                                                                
Image: ramdisk.img UPDATED from \SOFTWARE\ramdisk.img                           
PCIE clock configured...                                                        
                                                                                
Testing motherboard interfaces (FPGA build 118)...                              
SRAM 32MB test: PASSED                                                          
LAN9118   test: PASSED                                                          
KMI1/2    test: PASSED                                                          
MMC       test: PASSED                                                          
PB/LEDs   test: PASSED                                                          
FPGA UART test: PASSED                                                          
PCIe init test: PASSED                                                          
PCIe MAC addresss 0002-F700-62E8                                                
MAC addrs test: PASSED                                                          
                                                                                
SMC MAC address 0002-F700-62E7                                                  
Setting HDMI0 mode for SVGA.                                                    
Setting HDMI1 mode for SVGA.                                                    
                                                                                
SoC SMB clock enabled.                                                          
                                                                                
Testing SMB clock...                                                            
SMB clock running                                                               
Releasing system resets...                                                      
                                                                                
UART0 set to SoC UART0                                                          
UART1 set to SoC UART1                                                          
                                                                                
NOTICE:  Booting Trusted Firmware                                               
NOTICE:  BL1: v1.3(debug):c59428b                                               
NOTICE:  BL1: Built : 10:31:21, Feb 24 2017                                     
INFO:    BL1: RAM 0x4037000 - 0x4040000                                         
INFO:    Using crypto library 'mbed TLS'                                        
INFO:    BL1: Loading BL2                                                       
INFO:    Loading image id=6 at address 0x4006000                                
INFO:    Skip reserving region [base = 0x4006000, size = 0x37f]                 
INFO:    Image id=6 loaded at address 0x4006000, size = 0x37f                   
INFO:    Loading image id=1 at address 0x4006000                                
INFO:    Image id=1 loaded at address 0x4006000, size = 0x11158                 
NOTICE:  BL1: Booting BL2                                                       
INFO:    Entry point address = 0x4006000                                        
INFO:    SPSR = 0x3c5                                                           
NOTICE:  BL2: v1.3(debug):c59428b                                               
NOTICE:  BL2: Built : 10:31:21, Feb 24 2017                                     
INFO:    Using crypto library 'mbed TLS'                                        
INFO:    BL2: Loading SCP_BL2                                                   
INFO:    Loading image id=7 at address 0x4023000                                
INFO:    Skip reserving region [base = 0x4023000, size = 0x5ae]                 
INFO:    Image id=7 loaded at address 0x4023000, size = 0x5ae                   
INFO:    Loading image id=8 at address 0x4023000                                
INFO:    Skip reserving region [base = 0x4023000, size = 0x47a]                 
INFO:    Image id=8 loaded at address 0x4023000, size = 0x47a                   
INFO:    Loading image id=12 at address 0x4023000                               
INFO:    Skip reserving region [base = 0x4023000, size = 0x389]                 
INFO:    Image id=12 loaded at address 0x4023000, size = 0x389                  
INFO:    Loading image id=2 at address 0x4023000                                
INFO:    Skip reserving region [base = 0x4023000, size = 0xeadc]                
INFO:    Image id=2 loaded at address 0x4023000, size = 0xeadc                  
INFO:    BL2: Initiating SCP_BL2 transfer to SCP                                
INFO:    BL2: SCP_BL2 transferred to SCP                                        
INFO:    Configuring TrustZone Controller                                       
INFO:    BL2: Loading BL31                                                      
INFO:    Loading image id=9 at address 0x4023000                                
INFO:    Skip reserving region [base = 0x4023000, size = 0x47a]                 
INFO:    Image id=9 loaded at address 0x4023000, size = 0x47a                   
INFO:    Loading image id=13 at address 0x4023000                               
INFO:    Skip reserving region [base = 0x4023000, size = 0x389]                 
INFO:    Image id=13 loaded at address 0x4023000, size = 0x389                  
INFO:    Loading image id=3 at address 0x4023000                                
INFO:    Image id=3 loaded at address 0x4023000, size = 0xc020                  
INFO:    BL2: Loading BL32                                                      
INFO:    Loading image id=10 at address 0xff000000                              
INFO:    Skip reserving region [base = 0xff000000, size = 0x488]                
INFO:    Image id=10 loaded at address 0xff000000, size = 0x488                 
INFO:    Loading image id=14 at address 0xff000000                              
INFO:    Skip reserving region [base = 0xff000000, size = 0x397]                
INFO:    Image id=14 loaded at address 0xff000000, size = 0x397                 
INFO:    Loading image id=4 at address 0xff000000                               
INFO:    Image id=4 loaded at address 0xff000000, size = 0x39b70                
INFO:    BL2: Loading BL33                                                      
INFO:    Loading image id=11 at address 0xe0000000                              
INFO:    Skip reserving region [base = 0xe0000000, size = 0x48b]                
INFO:    Image id=11 loaded at address 0xe0000000, size = 0x48b                 
INFO:    Loading image id=15 at address 0xe0000000                              
INFO:    Skip reserving region [base = 0xe0000000, size = 0x39a]                
INFO:    Image id=15 loaded at address 0xe0000000, size = 0x39a                 
INFO:    Loading image id=5 at address 0xe0000000                               
INFO:    Image id=5 loaded at address 0xe0000000, size = 0x3f1c8                
NOTICE:  BL1: Booting BL31                                                      
INFO:    Entry point address = 0x4023000                                        
INFO:    SPSR = 0x3cd                                                           
NOTICE:  BL31: v1.3(debug):c59428b                                              
NOTICE:  BL31: Built : 10:31:21, Feb 24 2017                                    
INFO:    ARM GICv2 driver initialized                                           
INFO:    BL31: Initializing runtime services                                    
INFO:    BL31: Initializing BL32`

**And here are the logs I got from Secure port:**
`add_phys_mem: 0 9 0x00000000 size 0x01400000
add_phys_mem: 0x80000000 5 0x80000000 size 0x00000001
add_phys_mem: CFG_SHMEM_START 4 0xfee00000 size 0x00200000
add_phys_mem: CFG_TA_RAM_START 3 0xff200000 size 0x00c00000
add_phys_mem: CFG_TEE_RAM_START 1 0xff000000 size 0x00100000
add_phys_mem: GICC_BASE 8 0x2c000000 size 0x00200000
add_phys_mem: GICD_BASE 8 0x2c000000 size 0x00200000
add_phys_mem: Physical mem map overlaps 0x2c000000
add_phys_mem: CONSOLE_UART_BASE 8 0x7fe00000 size 0x00200000
init_mem_map: type va 9 0xfc800000..0xfdbfffff pa 0x00000000..0x013fffff size 0x1400000
init_mem_map: type va 8 0xfdc00000..0xfddfffff pa 0x7fe00000..0x7fffffff size 0x200000
init_mem_map: type va 8 0xfde00000..0xfdffffff pa 0x2c000000..0x2c1fffff size 0x200000
init_mem_map: type va 5 0xfe000000..0xfe000000 pa 0x80000000..0x80000000 size 0x1
init_mem_map: type va 4 0xfe200000..0xfe3fffff pa 0xfee00000..0xfeffffff size 0x200000
init_mem_map: type va 3 0xfe400000..0xfeffffff pa 0xff200000..0xffdfffff size 0xc00000
init_mem_map: type va 1 0xff000000..0xff0fffff pa 0xff000000..0xff0fffff size 0x100000
 Panic
`

PS: I might annotate some codes about the logs of secure port while I cannot remember now. If you think any log is missing, please let me know, thank you.

**Comment by SimonWan** [comment]
Hi @vchong , just found the problem. I should set the size as the multiple of the PAGE_SIZE. It works now! Thanks.
