### ISSUE TITLE
Can we use Valgrind on TA process?

### ISSUE THREAD

**Issue by gaurav4dev** [OP-TEE/optee_os#1344]
I want to run Valgrind or any dynamic memory analyzer on TEE side to debug/profile memory related issues in TA? How much complex will it be to compile Valgrind with TA build environment? Valgrind can be used to pass an argument for system() call while launching the process, but since TA process is launched with some predefined entry point other than main() how Valgrind know? Is any dynamic analysis tool there for TA?  Thanks.

**Comment by jforissier** [comment]
Hi @gaurav4dev,

I don't know much about the inner workings of valgrind, but I guess it would be rather complex to port it to the TA environment (although certainly not impossible). AFAIK, valgrind works like an interpreter. It loads the application binary and executes it instruction after instruction on a virtual CPU, while maintaining the information that is useful for its task. That includes monitoring memory allocations to know about the heap and intercepting all memory accesses for instance.
To do that with TAs, you first need a way to tell OP-TEE that the TA should not be executed directly but through valgrind. One option may be to pass parameters to `TEEC_OpenSession()`. Or you could call a pseudo-TA (static TA) to enable valgrind on a particular TA UUID. Then valgrind itself could be a TA or a special module inside the TEE core. Having it implemented in user mode would probably be more flexible and closer to the current architecture, but a TA does not have a way to load the binary for another TA like valgrind needs to do. In any case, as you said, the interfaces with the TA entry points would need adjusting.
That's just a few thoughts obviously, bottom line is you would need a very good knowledge of both the architecture and implementation details of valgrind *and* OP-TEE before embarking on such a project.

HTH.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
