### ISSUE TITLE
physical memory and cache

### ISSUE THREAD

**Issue by JunOllyLi** [OP-TEE/optee_os#1347]
Hi,
I am writing some driver in OPTEE that I need to allocate a memory block which is physically continuous. What API I should use? The design doc mentioned something about mobj_phys_alloc but I cannot find that API, is it out of date?

Also, the reason why I need this memory is to let DMA to use it. After CPU writes to it, what API should I use to flush the cache so DMA can pickup the data correctly? And vice versa? Or is it possible for me to mark a dynamically allocated memory area as non-cached?

Thanks a lot!

**Comment by jenswi-linaro** [comment]
Hi,

Try the using the `register_phys_mem()` macro. You can map the memory uncached if needed through that.

**Comment by JunOllyLi** [comment]
Jenswi,
Thanks a lot for the response. I understand this solution of using register_phys_mem. However, I think that requires me to reserve a memory block at build time, right?
I am wondering if I can dynamically allocate this memory block, which is physically continuous and can be mapped as un-cached. My driver is not going be used a lot by the system, so reserving a dedicated buffer for it would be a waste of memory.

Thanks!

**Comment by jenswi-linaro** [comment]
We don't have a good API to allocate secure physically contiguous memory. If `CFG_PAGED_USER_TA=n` you can allocate memory with `tee_mm_alloc(&tee_mm_sec_ddr, size)`. The memory will currently be mapped as normal cached memory. All this may change in the long run though.

**Comment by etienne-lms** [comment]
Hello @JunOllyLi.

Here are few details about allocating/flushing in "sec_ddr" (also known as "TA_RAM"), through the `mobj` layer, if it helps. Such allocated buffers are always physically contiguous and cached as "sec_ddr" is mapped with cache attribute.

As Jens stated, this consider your platform expects the "sec_ddr" (`CFG_TA_RAM_START`/`_SIZE`) is a reliable secure memory area. When `CFG_PAGED_USER_TA=y` and `CFG_WITH_PAGER=y,` some platform do not consider "sec_ddr" memory as secure enough.

```
  struct mobj *my_mobj = mobj_mm_alloc(mobj_sec_ddr, my_size, &tee_mm_sec_ddr);
  if (!my_mobj) { /* error */ }

  /* to get the virtual address of the allocated buffer: */
  void *my_va = mobj_get_va(my_mobj, 0);
  if (!my_va) { /* error */ }
  /* now you can access the allocated buffer */

  /* to get the physical address of the allocated buffer: */
  paddr_t my_pa;
  if (mobj_get_pa(my_mobj, 0, 0, &my_pa) != TEE_SUCCESS) { /* error case */ }
  /* now you can use the physical address */

  /* to free the allocated memory: */
  mobj_free(my_mobj);
```
Note: `mobj_sec_ddr` and `tee_mm_sec_ddr` are global variable related to TA_RAM 


Regarding cache management, there are currently 2 cases: is there an outer cache that needs to be manually synchronised (as a PL310 outer cache)?
If no, you can synchronize cache through:
```
  if (cache_maintenance_l1(DCACHE_AREA_CLEAN_INV, my_va, my_size) != TEE_SUCCESS) { /* error */
```
If there is an outer cache (only PL310 currently supported), you can sync through sequence:
```
  if (cache_maintenance_l1(DCACHE_AREA_CLEAN, my_va, my_size) != TEE_SUCCESS) { /* error */ }
  if (cache_maintenance_l2(L2CACHE_AREA_CLEAN_INV, my_va, my_size) != TEE_SUCCESS) { /* err */ }
  if (cache_maintenance_l1(DCACHE_AREA_CLEAN_INV, my_va, my_size) != TEE_SUCCESS) { /* err */ }
```

**Comment by JunOllyLi** [comment]
@etienne-lms @jenswi-linaro 
Thanks a lot!
But where can I find the API you mentioned? I did "grep -r mobj *" and it did not find anything.

**Comment by jforissier** [comment]
@JunOllyLi the memory objects (mobj) abstraction was introduced just after the 2.3.0 release. So you will need to checkout from the current master branch to have it.

**Comment by etienne-lms** [comment]
you might need to sync on latest optee_os master branch.
mobjs are in core/arch/arm/mm/mobj.c/

**Comment by JunOllyLi** [comment]
Ah! Thanks! I will try it.

**Comment by JunOllyLi** [comment]
@etienne-lms 
I have not tried the mobj stuff yet, but I first tried to do cache maintenance when I map a dedicated memory region as cached. So far it did not work.
I do have L2 cache (PL310), so I tired to use the code you mentioned:
  if (cache_maintenance_l1(DCACHE_AREA_CLEAN, my_va, my_size) != TEE_SUCCESS) { /* error */ }
  if (cache_maintenance_l2(L2CACHE_AREA_CLEAN_INV, my_va, my_size) != TEE_SUCCESS) { /* err */ }
  if (cache_maintenance_l1(DCACHE_AREA_CLEAN_INV, my_va, my_size) != TEE_SUCCESS) { /* err */ }

But:
1. cache_maintenance_l2 requires the second parameter to be paddr_t, should I do virt_to_phys(my_va)?
2. Is the first call to cache_maintenance_l1 a typo when it only CLEAN but not CLEAN_INV?
Anyway, I tried modify the code as I guessed and it still not working if I map the area as MEM_AREA_RAM_SEC instead of MEM_AREA_IO_SEC in phys_to_virt

Any suggestion?

**Comment by etienne-lms** [comment]
oups! you're right. i forgot the physical address stuff. So for the physical address (typed `paddr_t`) yes you need to call `virt_to_phys(my_va)`. Check returned physical address is not null: means a faulty translation (physical address 0x00000000 is banned :( from optee!)

The first L1 CLEAN (not CLEAN_INV) is not a error; it's a light optim. I recommend you to have a look at the [ARM recomandation about pl310 outer cache maintenance](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0246d/Beicdhde.html).

Also, here is another pitfall: if you run a SMP system, you must prevent from concurrent accesses on outer cache: refer to `tee_l2cc_mutex.c`.

**Comment by jbech-linaro** [comment]
@JunOllyLi still an issue? If not, I'd like like to close this issue.

**Comment by JunOllyLi** [comment]
@jbech-linaro Technically it is still a problem. The functions mentioned above do not really work. However, I have decided to avoid the trouble and allocated the physically memory pool statically.
So you can close this issue for now.
