### ISSUE TITLE
Trying to send an email to op-tee-AT-linaro-DOT-org

### ISSUE THREAD

**Issue by dnovick** [OP-TEE/optee_os#1351]
I have been trying to send an email to the OP-TEE team at Linaro, but for some reason it keeps bouncing, telling me the address is wrong or that I don't have access to the mailing list. Is this a known issue?

My question is not a bug, but I will ask it here in hopes that somebody might field the question. From my email:

I have been doing some work with OP-TEE over the last few months. Among numerous other things, I've done a pretty thorough study of the code. One of the things I've been looking for, but unable to find is how you prevent one TA from accessing the memory of another TA. This certainly may be user error on my part. I've looked to see if this is a requirement of the GP spec, and haven't seen anything specific, but obviously this is a property any reasonable TEE should have. Is such a capability implemented in OP-TEE? If so, where can I look in the code to better understand how you've tackled it. If it isn't implemented, is it planned for a future release? BTW, my study of the code was on a version prior to 2.0....I have just upgraded to 2.0 today, and am currently looking at the new version's code.

**Comment by jenswi-linaro** [comment]
Hi,

I'll let @jbech-linaro answer why the mail bounces.

TAs are isolated from each others by the way memory is mapped and accessible. TAs has its private memory mapped and accessible only to itself. Look in `tee_mmu_set_ctx()`

**Comment by jbech-linaro** [comment]
Short answer to the email issue: no idea why it doesn't work, it should work. But I've raised a ticket internally with our IS/IT people, asking them to double check that people external to Linaro also should be able to post question to that address (internal ticket number ITS-2082).

**Comment by jbech-linaro** [comment]
@dnovick , seems to be a setting here that was wrong. Our IS/IT folks have changed it now and I've just tried to send an email to the list using my personal account and that seemed to work fine. Thanks for reporting this issue.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
