### ISSUE TITLE
failure at thread_check_canaries

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#1358]
I met an strange issue, I build the tee image with the two command, but one work, the other not work.
`make PLATFORM=imx-mx7 ARCH=arm CFG_PAGEABLE_ADDR=0 CFG_BUILT_IN_ARGS=y CFG_NS_ENTRY_ADDR=0x80800000 CFG_DT_ADDR=0x83000000 CFG_DT=y CFG_TEE_CORE_LOG_LEVEL=0 CFG_PSCI_ARM32=y CFG_MX7=y CFG_DDR_SIZE=0x40000000 CFG_TZDRAM_BASE=0xbe200000 CFG_BOOT_SECONDARY_REQUEST=y CFG_TEE_CORE_NB_CORE=2` work ok

`make PLATFORM=imx-mx7 ARCH=arm CFG_PAGEABLE_ADDR=0 CFG_BUILT_IN_ARGS=y CFG_NS_ENTRY_ADDR=0x80800000 CFG_DT_ADDR=0x83000000 CFG_DT=y DEBUG=y CFG_PSCI_ARM32=y CFG_MX7=y CFG_DDR_SIZE=0x40000000 CFG_TZDRAM_BASE=0xbe200000 CFG_BOOT_SECONDARY_REQUEST=y CFG_TEE_CORE_NB_CORE=2 CFG_TEE_CORE_DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4  CFG_CORE_UNWIND=y`
not work

xtest 1006 will fail the last line in the following piece code
`
void thread_check_canaries(void)                                                
{                                                                               
#ifdef CFG_WITH_STACK_CANARIES                                                  
        size_t n;                                                               
                                                                                
        for (n = 0; n < ARRAY_SIZE(stack_tmp); n++) {                           
                if (GET_START_CANARY(stack_tmp, n) != START_CANARY_VALUE)           
                        CANARY_DIED(stack_tmp, start, n);
`

I do not have a good idea on this, please adivse.

**Comment by jenswi-linaro** [comment]
It looks like the second image uses more stack than the first. The canaries are used to detect stack overruns.

**Comment by jbech-linaro** [comment]
@MrVan still an issue? If not, I'd like like to close this issue.
