### ISSUE TITLE
MMU page table 

### ISSUE THREAD

**Issue by benthomasq** [OP-TEE/optee_os#1363]
Hi,

I was wondering there is a page table implementation in secure kernel. 

Here is my question in detail: 
Normally in Linux, for translation of virtual address to physical address, system will use TLB table. I know that, when have a miss occur on TLB, it will find physical page from page table. 
From table index of virtual address and table base address, will have first-level descriptor, the first-level descriptor will be input for page table to get physical page table from page table
then fill it to TLB table.
If page table miss, it will find physical page form external memory (RAM) and fill it to page table with it's attribute.

Does this work same way in Optee OS? If so, could you point me to the code that creates the page table for a trusted app, updates the page table. 

I went through the documentation of Optee OS. It mentions about a "Pager" which is different from page table I described about I think. Am I correct?  

Thank you!
Ben

**Comment by zhizhouzh** [comment]
Page table is described in architecture document. page table is normal memory, no different with other memory. TLB is something like cache. I think you may mixed up TLB with page table.

For MMU operations, you can refer to `core/arch/arm/mm/core_mmu_lpae.c`.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
