### ISSUE TITLE
Hide data used by TA

### ISSUE THREAD

**Issue by pastern** [OP-TEE/optee_os#1369]
Hi,

I want to create a TA that use some personal information and I would like to be sure that that information is visible only in the secure world. Does OPTEE provide this feature? Can I hide data in order to be processed only by a TA in the secure world without worrying about normal world users? If yes, can you explain me how does it work?

**Comment by jforissier** [comment]
Hi @pastern, 

Secure storage (https://github.com/OP-TEE/optee_os/blob/master/documentation/secure_storage.md) is probably what you're after. Please not the caveats (https://github.com/OP-TEE/optee_os/blob/master/documentation/secure_storage.md#important-caveats) which are essential for a practical implementation.

**Comment by pastern** [comment]
Thank you @jforissier. So, I have a TA that needs to manipulate some sensitive data. I want to download the data (asymetrically encrypted) from normal world and to transfer it in the secure world. Then there I would like to decrypt the data, since secret key is stored in the secure os (how?), and use the decrypted data as input to some functions in my TA. How can I do that?

**Comment by jbech-linaro** [comment]
@pastern if you have a look at the TA's in https://github.com/linaro-swg/optee_examples, then you can probably figure out how to do it. All the building blocks to encrypt/decrypt use storage etc are there. If you still cannot figure it out, please feel free to re-open this ticket and we will see if we're able to give a bit more detailed guidance. Thanks!
