### ISSUE TITLE
core broken when CFG_SECURE_TIME_SOURCE_REE=y since commit 82f97f19

### ISSUE THREAD

**Issue by etienne-lms** [OP-TEE/optee_os#1371]
Since commit 82f97f19fe2d763dfa6c2da85385e6cda5b43b64, `tee_ltc_prng_init()` injects entropy from secure time value during the service initcalls, at early OP-TEE boot. When `CFG_SECURE_TIME_SOURCE_REE=y,` the not-so-secure time is retrieved from non-secure world through RPC.  Since non secure world is not alive duing OP-TEE early boot, RPC fails and OP-TEE cre hangs.

Solutions proposal:
- don't inject entropy from no-so-secure time when `CFG_SECURE_TIME_SOURCE_REE=y.`
- wait non secure world is up and ready before injecting entropy when `CFG_SECURE_TIME_SOURCE_REE=y.`
- let's think about it....

**Comment by jforissier** [comment]
The second options sounds best to me (although the third one is good also ;-)).

**Comment by jforissier** [comment]
How about `tee_time_get_ree_time()` would check a global flag, let's call it `rpc_ready`, and return immediately with an error code if not set. The flag could be set by `tee_entry_std()` because at that point we know everything is ready.

**Comment by jenswi-linaro** [comment]
The flag should probably be set at the end of `init_primary_helper()` after the call to `init_teecore()`, but I don't think that's enough as `rpc_cmd_nolock()` also calls `plat_prng_add_jitter_entropy()`.

**Comment by etienne-lms** [comment]
`rpc_cmd_nolock()` calls `plat_prng_add_jitter_entropy().` With `CFG_SECURE_TIME_SOURCE_REE=y,` weaked `plat_prng_add_jitter_entropy()` calls `thread_rpc_cmd()`. Is it really clean to call `thread_rpc_cmd()` from `rpc_cmd_nolock()`?

Also, when pager is enabled, the full RPC support becomes unpaged which is not optimal (let's say not affordable).

**Comment by jforissier** [comment]
Hmmm. How about this:
```diff
diff --git a/core/arch/arm/kernel/thread.c b/core/arch/arm/kernel/thread.c
index a13598c..e1efe7a 100644
--- a/core/arch/arm/kernel/thread.c
+++ b/core/arch/arm/kernel/thread.c
@@ -1199,7 +1199,9 @@ static uint32_t rpc_cmd_nolock(uint32_t cmd, size_t num_params,
 
        assert(arg && carg && num_params <= THREAD_RPC_MAX_NUM_PARAMS);
 
+#ifndef CFG_SECURE_TIME_SOURCE_REE /* Prevent recursive RPC invocation */
        plat_prng_add_jitter_entropy();
+#endif
 
        memset(arg, 0, OPTEE_MSG_GET_ARG_SIZE(THREAD_RPC_MAX_NUM_PARAMS));
        arg->cmd = cmd;
diff --git a/core/lib/libtomcrypt/src/tee_ltc_provider.c b/core/lib/libtomcrypt/src/tee_ltc_provider.c
index 06dc983..ed43b6e 100644
--- a/core/lib/libtomcrypt/src/tee_ltc_provider.c
+++ b/core/lib/libtomcrypt/src/tee_ltc_provider.c
@@ -171,7 +171,13 @@ static TEE_Result tee_ltc_prng_init(struct tee_ltc_prng *prng)
 
        prng->index = prng_index;
 
+#ifndef CFG_SECURE_TIME_SOURCE_REE
+       /*
+        * Not when entropy is gathered from the REE time source because RPCs
+        * are not yet available at this point
+        */
        plat_prng_add_jitter_entropy();
+#endif
 
        return  TEE_SUCCESS;
 }
```
Not pretty, but should work, no?

**Comment by jenswi-linaro** [comment]
Yes, it should work.

**Comment by etienne-lms** [comment]
Actually it does (work). This is the workaround i used to test the interrupts renaming.
... but do you think it's useful in some point to rely on REE time to inject entropy?

**Comment by jforissier** [comment]
@etienne-lms you say "useful", do you actually mean it could be unsafe? And that it would be "less unsafe" not to add entropy when `CFG_SECURE_TIME_SOURCE_REE=y`? Frankly I don't know.

**Comment by etienne-lms** [comment]
I would rather propose to patch the weaked `plat_prng_add_jitter_entropy()`. Something like this.

```
 __weak void plat_prng_add_jitter_entropy(void)
 {
+#ifdef CFG_SECURE_TIME_SOURCE_REE
+	/*
+	 * Do not inject entropy from data provided by the non secure world
+	 * through RPCs. This expects RPC support is available which may not
+	 * be the case. Platforms relying on CFG_SECURE_TIME_SOURCE_REE=y
+	 * should provide another source of entropy to the PRNG. This gets
+	 * some dummy entropy from the current stack address.
+	 */
+	unsigned long int sp;
+
+	asm volatile ("mov %0, sp" : "=r" (sp));
+	tee_prng_add_entropy((uint8_t *)&sp, sizeof(sp));
+#else
 	TEE_Time current;
 
 	if (tee_time_get_sys_time(&current) == TEE_SUCCESS)
 		tee_prng_add_entropy((uint8_t *)&current, sizeof(current));
 #endif
 }
```

**Comment by jenswi-linaro** [comment]
In practice we'll only get very few different values from SP, perhaps its better not to bother to collect anything at all to be clear that these platforms really need to do something.

**Comment by etienne-lms** [comment]
ok, agreed. Let's go for this ?
```
 __weak void plat_prng_add_jitter_entropy(void)
 {
+#ifdef CFG_SECURE_TIME_SOURCE_REE
+	/*
+	 * Do not inject entropy from data provided by the non secure world
+	 * through RPCs. This expects RPC support is available which may not
+	 * be the case. Platforms relying on CFG_SECURE_TIME_SOURCE_REE=y
+	 * should provide another source of entropy to the PRNG.
+	 */
+#else
 	TEE_Time current;
 
 	if (tee_time_get_sys_time(&current) == TEE_SUCCESS)
 		tee_prng_add_entropy((uint8_t *)&current, sizeof(current));
 #endif
 }
```

**Comment by jenswi-linaro** [comment]
Looks good to me.

**Comment by jforissier** [comment]
Thinking more about it, I'm not convinced it's ok to simply remove all entropy generation from REE, for the following reason. Assume a platform with `CFG_SECURE_TIME_SOURCE_REE=y` (we have 3 currently: `imx`, `stm` and `zynq7k`).

Prior to the problematic patch 82f97f1 ("prng: call plat_prng_add_jitter_entropy() at PRNG init and before NW RPC"), such a platform would at least benefit from some entropy. Admittedly, if NW is hacked this can result in weaknesses in the PRNG. But what we're proposing here is to make all such platforms weak, all the time, more or less.

So I am tempted to propose again https://github.com/OP-TEE/optee_os/issues/1371#issuecomment-283019303 or in other word, fix the problematic commit which introduced more entropy gathering without taking care of the special restrictions about getting the REE time.

Am I missing something?

**Comment by lws-team** [comment]
To the limited extent I understand the problem, the issue is new jitter collection events using old jitter collection code.... if so I agree @jforissier's patch will sort it, and / or implement reading the tsc in those platforms to get the improved entropy.

**Comment by jenswi-linaro** [comment]
@jforissier OK, good point.

**Comment by jforissier** [comment]
Proposed fix in https://github.com/OP-TEE/optee_os/pull/1377.

**Comment by etienne-lms** [comment]
fixed through https://github.com/OP-TEE/optee_os/pull/1377.
Thanks Jerome and all.
