### ISSUE TITLE
sucure login with optee

### ISSUE THREAD

**Issue by maxma668** [OP-TEE/optee_os#1374]
hello,
I'm new to the optee.I want to make a sucure login application but don't konw how to do that ,do you have any good ideas?

**Comment by etienne-lms** [comment]
@maxma668, first define what do you expect as a secure login usecase, on which kind of secret can it rely, where is this secret stored, what kind of data can be exposed in the non-secure world when executing a secure login usecase, what should the secure world and the non-secure world do if the secure login succeed and if secure login failed. I think your question is too wide to get a clear answer.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
