### ISSUE TITLE
How to flash efuse on IMX6UL EVK?

### ISSUE THREAD

**Issue by LeiShenHeros** [OP-TEE/optee_os#1384]
Hi,
I have been set TZASC registers on IMX6UL EVK ,but it look like disable,I find  a  Fusemap Descriptions Table in IMX6ULRM.pdf Table 5-9 and  I think I have to flash efuse to change a value (TZASC_EN) ,I have been try to set BOOTMODE = 00b,and download u-boot.imx by Mfgtool2, but still can't find message in terminal, anything I missed ? 
I find a community about this ,https://community.nxp.com/thread/384890,but still can't find uboot message in terminal

**Comment by MrVan** [comment]
@LeiShenHeros If you would like to program TZASC_EN into fuse, you could use `fuse prog` command in uboot.

**Comment by LeiShenHeros** [comment]
Hi,
I have been find this command in uboot,The problem is I can't see the log in terminal after download u-boot.imx.
thanks

**Comment by MrVan** [comment]
@LeiShenHeros After you program the tzasc_en fuse bit, u-boot fails to print out any log in the uart terminal? Did you initialize tzasc driver? If you only program tzasc_en and tzasc not initialized, uboot should work as before you did not program the tzasc_en.

**Comment by LeiShenHeros** [comment]
Hi,
yes,I have been initialize tzasc driver. I can't see the u-boot command line after download u-boot.imx. so I can't program the tzasc_en fuse bit. I just use this command to download the u-boot.imx in ucl2.xml :
 <CFG>
    <STATE name="BootStrap" dev="MX6UL" vid="15A2" pid="007D"/>
  </CFG>
<LIST name="SDCard" desc="Choose SD Card as media">
	<CMD state="BootStrap" type="boot" body="BootStrap" file ="firmware/u-boot.imx" >Loading U-boot</CMD>
<CMD state="BootStrap" type="jump" > Jumping to OS image. </CMD>
The cfg.ini is:
profiles]
chip = Linux

[platform]
board = MX6UL

[LIST]
name = SDCard

[variable]
board = MX6UL
6uluboot=14x14ddr3arm2
6uldtb=14x14-ddr3-arm2
ldo=
plus=
initramfs=fsl-image-mfgtool-initramfs-imx_mfgtools.cpio.gz.u-boot
seek = 1
sxnor=qspi2
7dnor=qspi1
6ulnor=qspi1
nor_part=0
anything I missed ?
thanks

**Comment by LeiShenHeros** [comment]
@MrVan,I see a way to program the fuse,I just follow this way but still disable: http://www.nxpic.org/module/forum/thread-571825-1-1.html

**Comment by LeiShenHeros** [comment]
Hi,
@MrVan ,now, I see the uboot command line,after read your code [https://github.com/MrVan/uboot/blob/imx_v2016.03_4.1.15_2.0.0_ga/cmd/fuse.c](uboot/cmd/fuse),I think the uboot command is  `fuse prog 0 6 10000000` right? program the fuse is dangerous,so please forgive my caution.
Thanks again for your help

**Comment by MrVan** [comment]
`fuse  prog 0 6 0x10000000` After this, repower your board, uboot should work as before. Then initialize tzasc in optee or in uboot.
