### ISSUE TITLE
Problem with running optee client on Hikey 8GB eMMC

### ISSUE THREAD

**Issue by sthomsen1** [OP-TEE/optee_os#1387]
I'm using Hikey(Lemaker version, 2GB RAM, 8GB eMMC). and I'm using the 8GB partition table and the 	hikey_debian.xml manifest.

I use this command to flash my board: 

```
make all
make flash
```

After i boot up the board using the `make send` command to push the data to the board, 
i use the following cmds:

```
sudo dpkg --force-all -i /tmp/out/optee_2.0-1.deb
sudo dpkg --force-all -i /tmp/linux-image-*.deb
```
will get me the following error:
`blockdev: ioctl error on BLKROSET: Operation not permitted`

After i reboot the device will not boot and give me a black screen. 

I read other issues here with identical problems (like #1234 #1257) , but no solution will work for me. 

**What i already tried**

- using the ptable 8g (hardcoded in the hikey_debian.mk file
- re-sync everything
- try the hikey.xml manifest.
- replace the SYSTEM_IMG_URL and BOOT_IMG_URL to newer Version.

With the rootfs version 16.06 (the SYSTEM_IMG_URL) i cant even flash the board. It stops after some seconds flashing the debian_system.img and holds there with no error (longest wait = 8 hours). 

This version is what I need for research purpose hope someone knows a solution for that ? 
Thanks!

**Comment by vchong** [comment]
Please try this:

Power off board
Connect jumpers 1-2 and 3-4
Power on board
On your PC or development machine, run `make recovery`. NOTE: You have 90 seconds to do this, or else the command will fail!

**Comment by vchong** [comment]
If `make recovery` command completes successfully, then:

Power off board
Remove jumpers 3-4
Power on board
Check if board boots properly

**Comment by sthomsen1** [comment]
Boots up properly and `uname -a` gives me: 
`linux linaro-alip 4.4.0-135-arm64 #1 SMP Debian 4.4.11.linaro.135-1linarojessiel(2016-06-28) aarch64 GNU/Linux`
The hole flash process took 149.724 seconds.
The boards works fine from here

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
