### ISSUE TITLE
Problems booting Linux on Zedboard after OP-TEE boots

### ISSUE THREAD

**Issue by dnovick** [OP-TEE/optee_os#1390]
I don’t know if this is the right place to post a question like this. If not, please point me to the right place.

I have been working with OP-TEE since last year. I’ve created my own TA for my project, tested it using the QEMU “port”, etc. During the last month, I’ve been trying to get things running on a Xilinx Zedboard (ZYNQ 7k). I’ve worked with Yan Yan at WindRiver to get some tips on the Zynq port he did. Unfortunately, I’m running into a very strange problem that he is unable to help with.

I’m using a Xilinx version of Linux that is configured for the Zedboard, and of course am booting it as secondary through OP-TEE as primary. Although this Linux kernel will boot by itself (as long as I disable the SMCCC change I need for handoff from OP-TEE), it boots fine. However, when Linux is boot as secondary, I end up with a kernel panic when trying to initialize the ARM PLL (first clock to be initialized). I’ve posted on the Xilinx forums to no avail, unfortunately Yan doesn’t have much Linux experience, and have beat my head on the wall for hours. I know exactly what instruction causes the panic, but have no clue as to why, nor as to what I need to do to fix it. It makes no sense to me that the same image boots fine by itself, but fails to load after an OP-TEE boot.

BTW, I've done a comparison between the Xilinx Linux I'm using and the Linux branch provided with OP-TEE, and in the areas of failure there are no significant differences.

I’m hoping that somebody else has run into similar problems, even on other platforms (especially ARM), and has suggestions on how to resolve this issue. I’m very desperate at this point, as this is the focus of an important demo I’m doing for my management (I’m a Principal Engineer at Intel). 

Is there anybody who can help?

Dave

**Comment by jforissier** [comment]
Hi @dnovick,

This is definitely the right place to ask any OP-TEE related question, although I'm not sure we have many Zynq users monitoring this issue tracker.

The first things that comes to my mind when I read your description is, could it be that OP-TEE performs some early initialisations that would prevent the Normal World from accessing the clock? (in plat_init.S or main.c, or possibly some earlier boot code that would differ whether you're loading OP-TEE or not).

Another thing to look at: do you know more about the characteristics of the kernel panic? Data abort, prefetch abort, decode DFSR/IFSR. This could give clues.

**Comment by dnovick** [comment]
Thanks for the response. So, your suggestion is what I first thought about, though I have yet to find anything specific that would address my problem. Let me take another more thorough look. Also, I do have details on exactly the kind and location of the panic. I've got meetings today...but will provide more details if I don't figure it out from my further analysis of OP-TEE boot.

Dave

**Comment by dnovick** [comment]
Well, I had hoped I had found the problem, as I found what appears to be a misconfiguration of the PCR during OP-TEE boot on the Zynq port (I've already notified Yan - the author). Unfortunately, that doesn't fix my problem. I checked other board config params during OP-TEE boot, and find nothing amiss. So here are more details. I'm getting an imprecise external abort (0x406) at 0x00000000. I have included a link to my boot output, which includes some additional debug messages I put in to help me locate the exact location of failure. This all happens during clk_register_zynq_pll()...specifically, right after the call to spin_lock_irqsave(), there is a call to clk_readl(pll->pll_ctrl). This is an inline function that issues a DSB SY instruction. It is this instruction that causes a jump to panic.

[https://dl.dropboxusercontent.com/u/44678754/terminal04.jpg](url)

Any help is appreciated.

Dave

**Comment by jbech-linaro** [comment]
@dnovick , our Xilinx setups hasn't been maintained for a while, so I'm afraid we can't really give any good advice here. Having that said, we've just recently got our hands on a [96Boards Ultra96](https://www.96boards.org/product/ultra96/) and our intention is to use that to bring back life of the Xilinx setups. That's the best news I can give right now and based on this I'm closing the ticket. Feel free to re-open it if you have additional questions.
