### ISSUE TITLE
Hikey: trying to allocate more physical memory to secure world

### ISSUE THREAD

**Issue by fxlin** [OP-TEE/optee_os#1396]
Hello folks,

I was trying to reserve more physical memory for OPTEE but failed to boot to the normal world. Did I miss anything? Thanks a lot!

---- 

So I did the following changes:

**optee_os**

```
diff --git a/core/arch/arm/plat-hikey/platform_config.h b/core/arch/arm/plat-hikey/platform_config.h
index 633759f..3f1df06 100644
--- a/core/arch/arm/plat-hikey/platform_config.h
+++ b/core/arch/arm/plat-hikey/platform_config.h
@@ -82,7 +82,9 @@
  */
 
 #define DRAM0_BASE             0x00000000
-#define DRAM0_SIZE             0x3F000000
+#define DRAM0_SIZE             0x38000000      
 
 #ifdef CFG_WITH_PAGER
 
@@ -94,19 +96,30 @@
 
 #else /* CFG_WITH_PAGER */
 
-#define TZDRAM_BASE            0x3F000000
-#define TZDRAM_SIZE            (16 * 1024 * 1024)
+
+#define TZDRAM_BASE            0x38000000
+#define TZDRAM_SIZE            0x08000000
 
 #endif /* CFG_WITH_PAGER */
 
-#define CFG_SHMEM_START                0x3EE00000
+#define CFG_SHMEM_START                0x37E00000 
 #define CFG_SHMEM_SIZE         (2 * 1024 * 1024)
 
 #define CFG_TEE_CORE_NB_CORE   8
 
 #define CFG_TEE_RAM_VA_SIZE    (1024 * 1024)
 
-#define CFG_TEE_LOAD_ADDR      0x3F000000
+#define CFG_TEE_LOAD_ADDR      0x38000000 
 
 #ifdef CFG_WITH_PAGER
```

**arm_trusted_firmware**

```
diff --git a/plat/hikey/hikey_def.h b/plat/hikey/hikey_def.h
index 2007633..0c91665 100644
--- a/plat/hikey/hikey_def.h
+++ b/plat/hikey/hikey_def.h
@@ -50,7 +50,8 @@
  *   - Secure DRAM (default is the top 16MB)
  *   - Non-Secure DRAM (remaining DRAM starting at DRAM_BASE)
  */
-#define DRAM_SEC_SIZE                  0x01000000
+#define DRAM_SEC_SIZE                  0x08000000 
 #define DRAM_SEC_BASE                  (DRAM_BASE + DRAM_SIZE - DRAM_SEC_SIZE)
 
 #define DRAM_NS_BASE                   DRAM_BASE
```

I rebuilt everything in DEBUG, and put them on the hikey board. 

Problem: the board seems to hang upon switching to BL33 (normal world), after 
"BL3-1: Preparing for EL3 exit to normal world"
 BL33 is loaded at 0x35000000, which I assumed will not be affected by my modification above.

----

The buggy boot log: http://pastebin.com/CXGciUAY
The normal boot log without my modification: http://pastebin.com/8tJ9wket

**Comment by msa2** [comment]
Hmm.. is hikey using device tree (dtb)? At least with rpi3 I observe some memory allocations in  `arch/arm/boot/dts/bcm2710-rpi-3-b.dtsi`, begins with...
```
 /memreserve/ 0x00000000 0x00001000;
 /memreserve/ 0x08000000 0x02000000;
```
However, not sure whether really related to your problem. I run into this when I tried to reserve fixed block of physical memory and trying to pass it to TA as parameter by "faking" a shm_mem struct -- I get FFFF0006 error back, I guess my faking is not complete...

**Comment by jforissier** [comment]
Some memory is reserved by UEFI (https://github.com/96boards/edk2/blob/hikey/HisiPkg/HiKeyPkg/Library/HiKeyLib/HiKeyMem.c#L44) so that reserving it in the DT is not necessary. But, if you're changing the addresses, then you may need to change UEFI or declare the new range in the DT.

**Comment by fxlin** [comment]
Thanks for the input. I further modified UEFI as follows:

**edk2**
```
diff --git a/HisiPkg/HiKeyPkg/HiKey.dsc b/HisiPkg/HiKeyPkg/HiKey.dsc
index 0663324..a6a3f4f 100644
--- a/HisiPkg/HiKeyPkg/HiKey.dsc
+++ b/HisiPkg/HiKeyPkg/HiKey.dsc
@@ -263,7 +263,8 @@
 
   # System Memory (1GB)
   gArmTokenSpaceGuid.PcdSystemMemoryBase|0x00000000
-  gArmTokenSpaceGuid.PcdSystemMemorySize|0x3E000000
+  gArmTokenSpaceGuid.PcdSystemMemorySize|0x37000000
 
   # HiKey Dual-Cluster profile
   gArmPlatformTokenSpaceGuid.PcdCoreCount|8
 
diff --git a/HisiPkg/HiKeyPkg/Library/HiKeyLib/HiKeyMem.c b/HisiPkg/HiKeyPkg/Library/HiKeyLib/HiKeyMem.c
index cad60ca..5eff126 100644
--- a/HisiPkg/HiKeyPkg/Library/HiKeyLib/HiKeyMem.c
+++ b/HisiPkg/HiKeyPkg/Library/HiKeyLib/HiKeyMem.c
@@ -41,7 +41,8 @@ STATIC struct HiKeyReservedMemory {
   { 0x06DFF000, 0x00001000 },    // MAILBOX
   { 0x0740F000, 0x00001000 },    // MAILBOX
   { 0x21F00000, 0x00100000 },    // PSTORE/RAMOOPS
-  { 0x3E000000, 0x02000000 }     // TEE OS
+  { 0x37000000, 0x09000000 }     // TEE OS
 };
 
 STATIC
```

It still hangs in the same place -- upon switching to BL33 (unsecure world).

Is JTAG the best way to debug this problem?

**Comment by vchong** [comment]
Try changing below as well?
https://github.com/linaro-swg/linux/blob/optee/arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts#L36

**Comment by fxlin** [comment]
Thanks @vchong . My understanding is that the platform hangs in switching to BL33; at that moment, Linux is not loaded yet. Therefore, the Linux dts shouldn't be the problem. Do I miss anything?

Nevertheless, I tried your suggestion. The problem remains the same: 

```
diff --git a/arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts b/arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts
index 6753e63..9febf32 100644
--- a/arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts
+++ b/arch/arm64/boot/dts/hisilicon/hi6220-hikey.dts
@@ -42,7 +42,8 @@
                      <0x00000000 0x05f02000 0x00000000 0x00efd000>,
                      <0x00000000 0x06e00000 0x00000000 0x0060f000>,
                      <0x00000000 0x07410000 0x00000000 0x1aaf0000>,
-                     <0x00000000 0x22000000 0x00000000 0x1c000000>;
+                     <0x00000000 0x22000000 0x00000000 0x15000000>;
        };
 
        reserved-memory {
```

**Comment by maxymedup** [comment]
Hi all, 

I found this topic which is almost 1 year old and seems to do the kind of TEE RAM mapping adjustment I need. What is the current status, do you finally manage to make it work on Hikey 620?

Currently, my TA (code + heap + stack =~25MB) doesn't fit in the default OP-TEE RAM mapping that provides ~15MB of TA RAM. My idea is at least to double the TEE RAM to get 32 MB for TEE RAM (OS + TA). 
For now I'm on Qemu v8 but the target is Hikey 620 running AOSP.
