### ISSUE TITLE
HiKey: no mouse/keyboard after dpkg update

### ISSUE THREAD

**Issue by sthomsen1** [OP-TEE/optee_os#1397]
hi folks,
after i flash my HiKey Board (8GB variant) it boot up properly and i can connect to my network. 
Using the `make send` command i pushed the OP-TEE client binaries (optee_2.3-0.deb) and the kernel with OP-TEE support (linux-image-*.deb) to my board.
When i execute the given commands everything is okay, but if i reboot the board my mouse/keyboard are disabled. 

I already tried:
* Use another mouse/keyboard
* Check if USB slots are disabled (or defect), but USB sticks are read. 
* Executeing just one of both commands and reboot, leads to the same problem.
* If i edit the /etc/network/interfaces file to add my wifi, the board lose this connection too after rebooting

Im using system_img 16.06. Is there a bug in the .deb files or am i missing something ?

thanks for your help

**Comment by vchong** [comment]
Do u still have the microusb cable attached to the board?

**Comment by sthomsen1** [comment]
Nope, mouse and keyboard are working and microusb is disconnect. 
i can use or reboot the board after flashing without any problems. 
I can even install both .deb files and use `tee-supplicant &` `xtest`, but a reboot cause the problem (several reboots don't fix it).

**Comment by bofeng17** [comment]
I have exactly the same issue with you. Did you solve it?

**Comment by sthomsen1** [comment]
Unfortunately no :( But i recognized that the icons (bottom right) sometimes have broken graphics. 
So somehow the OP-TEE client binaries are broken ?

**Comment by bofeng17** [comment]
If I only dpkg --force-all -i optee_2.3-0.deb and reboot, everything is OK. But if I also dpkg  --force-all -i linux-image-*.deb and reboot, none of mouse, keyboard and network work. So I think there is something wrong with linux-image-*.deb. But I don't know how to fix that.

**Comment by vchong** [comment]
For those who are interested, the hikey_debian build has recently been updated. Note that this is however an non-gui build only. To enable wifi, see https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L448.

**Comment by jbech-linaro** [comment]
And since last comment here we have deprecated the HiKey Debian build, hence this is no longer relevant. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
