### ISSUE TITLE
rpi3 rpmb access?

### ISSUE THREAD

**Issue by msa2** [OP-TEE/optee_os#1402]
When I boot rpi3 linux, it only shows

```
brw-rw---- 1 root disk 179, 0 Jan  1  1970 /dev/mmcblk0
brw-rw---- 1 root disk 179, 1 Jan  1  1970 /dev/mmcblk0p1
brw-rw---- 1 root disk 179, 2 Jan  1  1970 /dev/mmcblk0p2
```
I don't see any /dev/mmcblk0rpmb (or equivalent)? Should rpmb work anyway?
(another problem is that I would need rpmb *before* tee-supplicant is running).

ps. I downloaded mmc-utils and compiled in rpi3, and tried to use some "read" only commands, like

```
mmc extcsd read <device>
mmc status get <device>
mmc rpmb read-counter <rpmb device>
mmc csd read <device path>
mmc cid read <device path>
mmc scr read <device path>
```
...all failed, and kernel showed lots of error messages, and one of those (or all) destroyed the partition table (mmcblk0p1 and mmcblk0p2 disappeared). Had to repartition and redo image installation... :-(

**Comment by jforissier** [comment]
Hi @msa2 ,

First of all, what is your device ? SD card, or eMMC chip? SDs don't have RPMB partitions. You need an eMMC chip for that.
Then, the kernel has to support it. I don't know much about rpi3, but, you may check which driver is being loaded, then you can check the source and figure out if it supports CMD23 (that's required for RPMB).

**Comment by msa2** [comment]
U-Boot 2016.03-g10577db (Mar 08 2017 - 12:50:01 +0200)
Following is from u-boot...
```
DRAM:  932 MiB
Relocation Offset is: 3a332000
Relocating to 3a33a000, new gd at 39f35df8, sp at 39f35de0
gdb symbol-file offset is: 3a33a000
RPI 3 Model B (0xa02082)
boot regs: 0x00000000 0x00000000 0x00000000 0x00000000
MMC:   bcm2835_sdhci: 0
...
```
...and then from linux boot mmc related extracted...

```
[    2.687050] bcm2835-cpufreq: min=600000 max=1200000
[    2.692251] sdhci: Secure Digital Host Controller Interface driver
[    2.698541] sdhci: Copyright(c) Pierre Ossman
[    2.703199] sdhost: failed to allocate log buf
[    2.776854] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    2.804738] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    2.810677] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    2.848978] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.856915] Indeed it is in host mode hprt0 = 00021501
...
[    2.933345] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    2.940461] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    2.947566] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    2.955884] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    3.013820] mmc0: host does not support reading read-only switch, assuming write-enable
[    3.025360] mmc0: new high speed SDHC card at address aaaa
[    3.031529] mmcblk0: mmc0:aaaa SL08G 7.40 GiB
[    3.037877]  mmcblk0: p1 p2
[    3.072568] mmc1: new high speed SDIO card at address 0001
...

         Starting Provide limited super user privileges to specific users...
[[32m  OK  [0m] Started Deferred execution scheduler.
[   17.002751] brcmfmac: brcmf_sdio_drivestrengthinit: No SDIO Drive strength init done for chip 43430 rev 1 pmurev 24
[   17.014155] usbcore: registered new interface driver brcmfmac
         Starting Deferred execution scheduler...
[   17.038274] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430-sdio.bin failed with error -2
         Starting System Logging Service...

```

**Comment by igoropaniuk** [comment]
Hi @msa2,

RPi3 doesn't have eMMC on-board (one of the reasons it's so cheap :) ), and as @jforissier said it's not possible to have RPMB partitions on SD card.

BR,
Igor

**Comment by msa2** [comment]
Ok, thanks... I think this issue can be closed then.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins

**Comment by PhilArmstrong** [comment]
SD specification 9.0 includes RPMB support, so this might be possible with modern SD cards: https://www.sdcard.org/cms/wp-content/uploads/2022/05/Boot-TCG-and-RPMB-The-New-Security-Featu-res-Introduced-in-SD-9.0.pdf

I haven’t been able to find any cards that implement the new version of the spec with a cursory search, but there might be some out there by now?

**Comment by jbech-linaro** [comment]
> 

Cool! Seems like we should keep an eye on this! Thanks for sharing this with us.
