### ISSUE TITLE
OP-TEE + Android 6.0 on HiKey

### ISSUE THREAD

**Issue by ppeiffer** [OP-TEE/optee_os#1406]
Hi,

I'm trying to setup an environment to have Android 6.0 + op-tee en HiKey.
1) I have Android 6.0 alone working fine on HiKey
2) I have op-tee alone (I mean, + linux, as described here: https://github.com/OP-TEE/build#op-tee-buildgit ) working fine
3) Then, I have followed these steps (https://github.com/linaro-swg/optee_android_manifest) to add op-tee on top of Android 6.0. For that, I switched to kernel 4.1.15 (branch aosp-optee-4.1 of hikey-kernel) and checkouted an oldest commit to try to have something aligned with that kernel.

I'm able to flash it, run Android, but TEE-OS seems not be there as is kernel log i see:
    [    3.852513] optee firmware:optee: probing for conduit method from DT.
    [    3.852569] optee: probe of firmware:optee failed with error -22

despite fib.bin is flashed.

If I (stupidly) replace l-loader.bin and fip;bin under device/linaro/hikey/installer with the one generated in optee environment (in step 2 above), it doesn't work: TEE-OS starts based on serial out-put but linux-kernel doesn't apparently.

So here my question:
So I'm looking for some help to have op-tee OS running in my Android 6.0 environment with op-tee support. I'd like to both understand what must be aligned and how to align between TEE-OS (fip.bin), first stage of boot loader (l-loader.bin) and linux-kernel.

Apart of that, it's more related to HiKey than op-tee but if there are some pointers on what is nvme.img, l_loader.bin, etc, that would be nice.

Thanks for any help,

**Comment by vchong** [comment]
Hi,

This sounds difficult to do since there are no proper tags for the older versions. Sorry :(. It can be that the kernel doesn't have the latest patches to work with all the other optee_* components since these are at the latest. You can try updating aosp-optee-4.1 to be on par with aosp-optee-4.9 wrt to OP-TEE related patches, but not sure what other roadblocks will appear after that.

The nvme.img and l_loader.bin rarely changes so they shouldn't be something you should worry about.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
