### ISSUE TITLE
How to dynamically load a TA from Rich Execution Environment file system?

### ISSUE THREAD

**Issue by hypersimple** [OP-TEE/optee_os#1407]
If I build a TA from elsewhere, how to dynamically load this TA into the secure world (TEE)?

For example, if building a TA (one part for secure world and one part for normal world) on the local machine, I first move this TA binary file to the REE file system in normal world (in FVP, for example), then dynamically load this TA into the TEE. Next the client in the normal world can communicate with the one in the secure world.

Is it possible to implement? Or I have to compile and statically put the TA (as the HelloWorld example) into TEE from the beginning offline?

**Comment by jforissier** [comment]
Hi @hypersimple,

The answer is yes. TAs are loaded dynamically by OP-TEE from the normal world filesystem. If you add a new TA file, OP-TEE can find it.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
