### ISSUE TITLE
Does OPTEE support i.mx53 QSB board? 

### ISSUE THREAD

**Issue by karthikrish9** [OP-TEE/optee_os#1411]
Hi all,

Is it possible to run optee on [ i.MX53 Quick Start Board](http://www.nxp.com/products/automotive-products/energy-power-management/pmics/power-management-for-i.mx-application-processors/i.mx53-quick-start-board:IMX53QSB)? 
I don't see that board [here](https://github.com/OP-TEE/optee_os )

Thank you,
Karthik

**Comment by jforissier** [comment]
Hi @karthikrish9,

I don't know this particular board, and indeed it is not supported upstream at the moment.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
