### ISSUE TITLE
Is OPTEE_OS for Juno using 32-bit arch or 64-bit arch?

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#1415]
I remember I once found the document said the old OPTEE was 32-bit while I'm not sure now so I want to confirm this information.

By the way, if it's still using 32-bit, is there plan about 64-bit trusted OS? Thank you.

**Comment by jforissier** [comment]
Hi @SimonWan ,

Both 32 and 64 bits are supported. 64-bit TAs require a 64-bit TEE Core, while 32-bit TAs may be run on a 32- or 64-bit TEE Core.

**Comment by SimonWan** [comment]
Hi @jforissier , thank you for the reply. Sorry I got another related question.

Now I'm trying to access the 8GB DRAM of Juno from Secure OS while the [configuration file of Juno](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-vexpress/platform_config.h) only claims 2GB as DRAM and all addresses in this file are 32-bits.

My idea is setting some some address area as `MEM_AREA_RAM_NSEC` via function `register_pys_mem` so I'm wondering does this function support addresses more than 32-bit?

**Comment by jforissier** [comment]
This I'm not sure... @jenswi-linaro?

**Comment by jenswi-linaro** [comment]
If you compile OP-TEE OS as 64-bit (AArch64) I think it should be possible to use `register_pys_mem()` with 64-bit physical addresses. We certainly want it to work so patches are welcome.

**Comment by SimonWan** [comment]
@jenswi-linaro okay, I'll try to compile it as AArch64 and let you guys know if it works!
