### ISSUE TITLE
OP-TEE with Android on hikey : TA not found

### ISSUE THREAD

**Issue by yulongtian** [OP-TEE/optee_os#1418]
Hi,all
      Following this guide [https://github.com/linaro-swg/optee_android_manifest] .I have successfully put AOSP + OP-TEE on the HiKey board .When Android loaded ,I want to run xtest ,but got this output:
       Run test suite with level=0
       TEE test application started with device [(null)]
 
      * regression_1001 Core self tests
        regression_1001 OK
 
      * regression_1004 Test User Crypt TA
       external/optee_test/host/xtest/xtest_1000.c:288: xtest_teec_open_session( &session,       &crypt_user_ta_uuid, ((void*)0), &ret_orig) has an unexpected value: 0xffff000e = TEEC_ERROR_COMMUNICATION, expected 0x0 = TEEC_SUCCESS
        regression_1004 FAILED
 
       * regression_1005 Many sessions
      ERR [24963] TEES:load_ta:279:   TA not found
      external/optee_test/host/xtest/xtest_1000.c:343: xtest_teec_open_session(&sessions[i], &concurrent_ta_uuid, ((void*)0), &ret_orig) has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
        regression_1005 FAILED

The result was:
      845 subtests of which 391 failed
      75 test cases of which 57 failed
      0 test case was skipped
      TEE test application done!

  I also input dmesg | grep optee ,and got:
optee firmware:optee :probing for conduit method from DT.
optee firmware:optee :initialized dirver

I can't find .ta files in out/ directory and even can't find system/lib/optee_armtz/ directory in out/ after building ,does it matter?
Can anyone give me some advice?Thanks.

**Comment by vchong** [comment]
Hi @yulongtian 

https://github.com/linaro-swg/optee_android_manifest (master branch) is outdated. Last I remember it wasn't even building at all. How did you manage to get it to work?

This repo is currently in a WIP stage. You can try https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9 for now but please expect some instability until we can sort things out better.

Thanks!

**Comment by yulongtian** [comment]
Hi, @vchong
Thank you for your reply. When I tried to build the program ,there were several problems.First I made some tiny changes to the optee/build_kernel.sh ,and then add SElinux support for tee_supplicant refer to https://github.com/linaro-swg/device-linaro-hikey/pull/4/commits/.I also have encountered such a problem like https://github.com/linaro-swg/optee_android_manifest/issues/6.
By the way,I have solved the problem above, by adding all the *.ta files as  LOCAL_ADDITIONAL_DEPENDENCIES in external/optee_test/Android.mk.So all the *.ta files could be built as expected.

**Comment by vchong** [comment]
@yulongtian you're welcome, and thanks for sharing the solution!

Anyway, just fyi, the *.ta files are supposed to be built when building optee_os, in mk/aosp_optee.mk. Maybe optee_os build is not started.
