### ISSUE TITLE
mkdir operation implementation

### ISSUE THREAD

**Issue by saravians** [OP-TEE/optee_os#1427]
Hi, 
 How we can implement mkdir operation  on trusted side. 
Thanks

**Comment by jforissier** [comment]
Hi @saravians,

By "trusted side", do you mean TA? (Trusted Application). There is no concept of directory in secure storage.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
