### ISSUE TITLE
TA_DATA_SIZE limit

### ISSUE THREAD

**Issue by invhchan** [OP-TEE/optee_os#1429]
Hi,

I would like to know if it's possible to increase TA_DATA_SIZE?
I think the current maximum value is about (640*1024*6)?

Thanks!

**Comment by jenswi-linaro** [comment]
The maximum depends on several factors, first of all how much memory is available for TAs (`CFG_TA_RAM_SIZE`). Given that there's a lot of TA memory the value of `CFG_WITH_LPAE` will also affect the maximum.

There's no default value of `TA_DATA_SIZE`, it has to be configured for each TA.

**Comment by invhchan** [comment]
Thanks. So is it possible to increase CFG_TA_RAM_SIZE?

**Comment by jenswi-linaro** [comment]
Yes, but it depends on the platform.

**Comment by invhchan** [comment]
We tried increasing CFG_TA_RAM_SIZE but it caused problem running code in the Linux kernel side.
Is it possible to configure an overall increase in memory for Juno box?

**Comment by jenswi-linaro** [comment]
Yes, I think so, it involves updating ARM-TF to configure more DRAM as secure. The DTB used by the Linux kernel has to be updated with the new memory configuration.

**Comment by invhchan** [comment]
Thanks. Could you provide more details on how to update ARM-TF?

**Comment by jenswi-linaro** [comment]
I have no details on that, it shouldn't be too hard to find in the source though.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
