### ISSUE TITLE
hikey_debian: tee-supplicant fails: please clarify the build instruction around tee-supplicant, xtest

### ISSUE THREAD

**Issue by Valeri99** [OP-TEE/optee_os#1432]
Hello,

I am eager to run xtest after the long fighting with ethernet connection.
Please clarify the instruction for the hikey_debian at the
https://github.com/OP-TEE/build

The instruction suggests to do: $ make all run 
**But there is no target "run" in the hikey_debian.mk  (?)**
(I am asking because according the instruction the "make run" is needed 
 for "xtest" later in the instruction).
  
The instruction suggests to run: 
tee-supplicant &
xtest
**Do I need to do the "make send" before to run "tee-supplicant" and "xtest" ?**

Anyway: 

### 1) Test #1
(I used tag 2.3.0 everywhere)

 I just tried to run "tee-supplicant &" strictly according to instruction
 (i.e. after "make flash" and booting the device up)
 That is what I have:
 **tee-supplicant &
 [1] 1079**
 **linaro@linaro-alip:~$ ERR [1079] TEES:main:392: error opening [/dev/opteearmtz00]**

### 2) Test #2
 On the host machine:
 I run the "make send" before to run "tee-supplicant" and "xtest" on the HiKey.
 On the HiKey machine:
 
 **sudo dpkg --force-all -i /tmp/out/optee_2.3-0.deb**

 Selecting previously unselected package op-tee.
 (Reading database ... 61912 files and directories currently installed.)
 Preparing to unpack /tmp/out/optee_2.3-0.deb ...
 Unpacking op-tee (2.3-0) ...
 dpkg: warning: overriding problem because --force enabled:
 dpkg: warning: trying to overwrite '/usr/bin/tee-supplicant', which is also in package tee-supplicant 1.0.1+git5+g89f25ce-1.linarojessie.1
 dpkg: warning: overriding problem because --force enabled:
 dpkg: warning: trying to overwrite '/usr/lib/aarch64-linux-gnu/libteec.so.1.0', which is also in package libteec1.0 1.0.1+git5+g89f25ce-1.linarojessie.1
 dpkg: warning: overriding problem because --force enabled:
 dpkg: warning: trying to overwrite '/usr/lib/aarch64-linux-gnu/libteec.so.1', which is also in package libteec1.0 1.0.1+git5+g89f25ce-1.linarojessie.1
 Setting up op-tee (2.3-0) ...

 **sudo dpkg --force-all -i /tmp/linux-image-4.4.11-optee-rpb_4.4.11-optee-rpb-3_arm64.deb**
 Selecting previously unselected package linux-image-4.4.11-optee-rpb.
 (Reading database ... 61929 files and directories currently installed.)
 Preparing to unpack .../linux-image-4.4.11-optee-rpb_4.4.11-optee-rpb-3_arm64.deb ...
 Unpacking linux-image-4.4.11-optee-rpb (4.4.11-optee-rpb-3) ...
 Setting up linux-image-4.4.11-optee-rpb (4.4.11-optee-rpb-3) ...
 update-initramfs: Generating /boot/initrd.img-4.4.11-optee-rpb
 Copying hi6220-hikey.dtb as /boot/hi6220-hikey-4.4.11-optee-rpb.dtb
 Generating grub configuration file ...
 Found linux image: /boot/vmlinuz-4.4.11-optee-rpb
 Found initrd image: /boot/initrd.img-4.4.11-optee-rpb
 Found devicetree image: /boot/hi6220-hikey-4.4.11-optee-rpb.dtb
 Found linux image: /boot/vmlinuz-4.4.0-104-arm64
 Found initrd image: /boot/initrd.img-4.4.0-104-arm64
 Found devicetree image: /boot/hi6220-hikey-4.4.0-104-arm64.dtb
 **blockdev: ioctl error on BLKROSET: Operation not permitted
 blockdev: ioctl error on BLKROSET: Operation not permitted
 blockdev: ioctl error on BLKROSET: Operation not permitted
 blockdev: ioctl error on BLKROSET: Operation not permitted
 blockdev: ioctl error on BLKROSET: Operation not permitted
 blockdev: ioctl error on BLKROSET: Operation not permitted
 blockdev: ioctl error on BLKROSET: Operation not permitted**
 done 

 **tee-supplicant &**
 **[1] 4904**
 **linaro@linaro-alip:~$ ERR [4904] TEES:main:397: failed to find an OP-TEE supplicant device**

 
### 3) Test #3
  I tried to reboot the HiKey machine after test#2 
  but the booting up crashed.
   
 
 Please, help.
 
 Thanks a lot.

**Comment by vchong** [comment]
@Valeri99 Did you manage to resolve the issue yourself?

**Comment by Valeri99** [comment]
@vchong 
It works for me for tag 2.2.0
In my post just I wanted to know in particular if the confusing output like
------- blockdev: ioctl error on BLKROSET: Operation not permitted -------
is normal and also I needed an obvious confirmation that "make send"
is needed.
Yes, indeed, the confusing output seems to be normal (it does not affect the later test execution).
Yes, indeed, the "make send" is obviously needed.
Thanks.
