### ISSUE TITLE
AOSP 7 + OPTEE on Hikey : ADB device not found

### ISSUE THREAD

**Issue by karthikrish9** [OP-TEE/optee_os#1439]
1) I flashed Android 7 + OP-TEE to my Hikey board. 
2) I enabled developer mode and then `USB debugging` in the Android settings window
3) Added following to my Ubuntu host machine (in the file /etc/udev/rules.d/51-android.rules)

```
# fastboot protocol on HiKey
SUBSYSTEM=="usb", ATTR{idVendor}=="18d1", ATTR{idProduct}=="d00d", MODE="0660", GROUP="dialout"
# adb protocol on HiKey
SUBSYSTEM=="usb", ATTR{idVendor}=="12d1", ATTR{idProduct}=="1057", MODE="0660", GROUP="dialout"
# rndis for HiKey
SUBSYSTEM=="usb", ATTR{idVendor}=="12d1", ATTR{idProduct}=="1050", MODE="0660", GROUP="dialout"
```

4) Connected the USB micro cable to host machine.

Still cannot find hikey device using the command  `$ sudo adb devices    `

How can I get a shell access to the hikey device? Am I missing something? Following is what I am getting! I spent quite some  time now on this. Not sure what is wrong. I did restarted `adb` many times and tried it on different machine too. Any help? 
```

[17:11:20] karthik@sec:~/Desktop $ dmesg
[  851.528325] usb 1-13: device not accepting address 21, error -62
[  851.640374] usb 1-13: new high-speed USB device number 22 using xhci_hcd
[  856.652643] xhci_hcd 0000:00:14.0: Command completion event does not match command
[  856.652651] xhci_hcd 0000:00:14.0: Timeout while waiting for setup device command
[  861.868550] xhci_hcd 0000:00:14.0: Timeout while waiting for setup device command
[  862.072574] usb 1-13: device not accepting address 22, error -62
[  862.072627] usb usb1-port13: unable to enumerate USB device
[17:11:23] karthik@sec:~/Desktop $ sudo adb kill-server   
[17:11:31] karthik@sec:~/Desktop $ sudo adb devices    
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached 

[17:11:36] karthik@sec:~/Desktop $ 
```
I also see `Select USB Connfiguration` in the android settings window. I tried MTP and PTP in that. Still no luck finding device with ADB command. :(

**Comment by karthikrish9** [comment]
I also see `Select USB configuration` inside settings and I tried MTP and PTP.  Still, I can't find device using adb command. I wonder what I am missing.

**Comment by vchong** [comment]
Are you using https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9?
It defaults to tcp. Please try below on the serial console to set it back to usb.
```
su
setprop sys.usb.configfs 1
stop adbd
start adbd
```

If you don't have console access, you'll have to rebuild the image after making the change below, and flash the images again.

In `device/linaro/hikey/init.common.usb.rc`, change `setprop sys.usb.configfs 0` to `setprop sys.usb.configfs 1`.

**Comment by karthikrish9** [comment]
Hi @vchong ,

Yes, I am using exactly that branch (hikey-n-4.9). I just need a root shell to the device to run trusted applications. 
How do I use the serial console? It is just by connecting  to UART3 or UART0? and using mincom? 
Can you paste the minicom command too?  Thanks alot!

**Comment by karthikrish9** [comment]
Hi @vchong ,

Also, I cannot find  the optee_hello_world related two binaries in the system.

1. 8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta is not found in /system/lib/optee_armtz/
2. tee_helloworld is not founf in /system/bin 

Could you please tell me how to add this?

**Comment by vchong** [comment]
Yes, sorry. This build doesn't include hello_world. I'm trying to add it back in. In the meantime, you can do below and rebuild.

In `device/linaro/hikey/optee-packages.mk`, add:
```
PRODUCT_PACKAGES += tee_helloworld
PRODUCT_PACKAGES += 8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta
```

**Comment by karthikrish9** [comment]
Hi @vchong ,

Currently I don't see any logs from secure world TA on UART0 or UART3? How do I set this?  

I think, I should add` CFG_SW_CONSOLE_UART=0 `and `CFG_TEE_TA_LOG_LEVEL=3`
somewhere could you please tell me where to add these two config flags so that I can see logs from `hello_world_ta`. 


```
TEE_Result TA_CreateEntryPoint(void)
{
  DMSG("TA Create entry point has been called");
  return TEE_SUCCESS;
}

```

Currently, I see UART3 is used as serial port to NW.

Thanks  lot,

**Comment by vchong** [comment]
Secure world logs default to UART3.
`CFG_SW_CONSOLE_UART` is a flag specific to the https://github.com/OP-TEE/build project only. Please don't use it anywhere else! For `optee_os`, you want to use `CFG_CONSOLE_UART=3` or `0`.
Do you have access to UART0? If not, just keep it at UART3. UART0 access requires a different kind of cable which is more expensive than the UART adapter for the UART3.

For the log level, you can just add the flags to your build command. E.g. `make TARGET_BUILD_KERNEL=true CFG_TEE_TA_LOG_LEVEL=3 CFG_TEE_CORE_LOG_LEVEL=3`.

**Comment by radheshkrishnan** [comment]
Thank you.

yes, I do have access to UART0. So how do I change optee_os to UART0 from UART3?

**Comment by karthikrish9** [comment]
Hi @vchong ,

I have access to UART0. So how to I change OPTEE_OS to output to UART0? 
Where do I add `CFG_CONSOLE_UART=3`?

**Comment by vchong** [comment]
It's not in any Makefile. If it's not defined, it defaults to UART3. See https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/platform_config.h#L43.

As mentioned earlier, you can set most if not all flags you want from the prompt.
`make TARGET_BUILD_KERNEL=true CFG_TEE_TA_LOG_LEVEL=3 CFG_TEE_CORE_LOG_LEVEL=3 CFG_CONSOLE_UART=0 CFG_FOO_BAR=baz`. If you must put in somewhere, I guess `optee_os/core/arch/arm/plat-hikey/conf.mk` would be ok.

**Comment by karthikrish9** [comment]
Thank you it worked!

Also, Why is that Wifi not working in Android? Is that also a configuration thing?

Thanks again,

**Comment by vchong** [comment]
It should work. I assumed you've already turned wifi on via Settings?

**Comment by karthikrish9** [comment]
Yes, on Android phone settings window,  when I turns on the wifi, It searches for available wifi for a minute, but fails to find any available Wifi. After that it automatically turns off Wifi on the settings. . Mac address of it looks weird too, it  is 02:00:00:00:00:00.  I wonder why is it. Any suggestions to debug this?

**Comment by vchong** [comment]
Sorry. I just confirmed it doesn't work as well, but this isn't really an op-tee issue. In any case, will check with android people and post an update when available. In the meantime can you try an USB-LAN adapter?

**Comment by vchong** [comment]
@karthikrish9 Please try reverting commit 17ea3f3016b967ddcca535acb90dc1c3f8d98ec2 in device/linaro/hikey to see if that helps.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
