### ISSUE TITLE
memory access issue

### ISSUE THREAD

**Issue by yuhsien-chen** [OP-TEE/optee_os#1444]
Hi, I encountered a problem.
When I'm using static library, I store the pointer to function into array.
I meet the situation is when I use loop to traversal it, the dump result was fault.
But, when I enumerate it by index, the result is correct.
like this.
```
// failed address
a[0] = 0xa8098
a[1] = 0xa8068
a[2] = 0xa8038
a[3] = 0xa8008
a[4] = 0xa7fd8

// expected address
a[0] = 0x40129098
a[1] = 0x40129068
a[2] = 0x40129038
a[3] = 0x40129008
a[4] = 0x40128fd8
```

My code would like this.
```C
// test.h for prebuilt library libtest.a
extern const testTypeI func1;
extern const testTypeI func2;
extern const testTypeI func3;
extern const testTypeI func4;
extern const testTypeI func5;

// mysdk.h for seperated function define
void some_func(void);

// mysdk.c for seperated function implement
static testTypeI* FUNC[] = {
    &func1,
    &func2,
    &func3,
    &func4,
    &func5
};

void some_func(void) {
    // will dump failure result
    for(i = 0;i < 5;i++) {
        IMSG("FUNC[%d] = %p", i, (void *)FUNC[i]);
    }

    IMSG("===================");

    // will dump correct result
    IMSG("FUNC[0] = %p", (void *)FUNC[0]);
    IMSG("FUNC[1] = %p", (void *)FUNC[1]);
    IMSG("FUNC[2] = %p", (void *)FUNC[2]);
    IMSG("FUNC[3] = %p", (void *)FUNC[3]);
    IMSG("FUNC[4] = %p", (void *)FUNC[4]);
}

// myTA.c for TA command entry
static TEE_Result some_test(uint32_t param_types,
							TEE_Param params[4])
{
    // call func
    some_func();

    return TEE_SUCCESS;
}
```

By the way, when I combine mysdk.c functions and array definition into myTA.c, it will correct. Why?
Any advice will be appreciated.

**Comment by jforissier** [comment]
Hi @yuhsien-chen,

It looks like it could be a relocation problem. Are you running with the patch I proposed here: https://github.com/OP-TEE/optee_os/issues/1399#issuecomment-286414944? If so, please try the latest optee_os instead (or cherry-pick commit https://github.com/OP-TEE/optee_os/pull/1419/commits/ef53fb06ad9e5dd616e327a05fce60c74db90ce7) because my first proposal was incorrect.

**Comment by yuhsien-chen** [comment]
@jforissier Thanks, I'll try it soon and report the result.

**Comment by yuhsien-chen** [comment]
@jforissier Thanks.
It works fine. 
Now I can get correct address.
