### ISSUE TITLE
unable to insmod optee.ko

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#1445]
insmod /optee.ko
optee: probing for conduit method from DT.
optee: capabilities mismatch
insmod: ERROR: could not insert module /optee.ko: Invalid parameters

I found that `https://github.com/linaro-swg/linux/blob/optee/drivers/tee/optee/core.c#L330`, there is a check for cpus and smp, since 6UL is a single a7 core soc, this will cause optee.ko can not be insmod.

@jenswi-linaro do you have ideas?

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/optee_os/commit/8d22aebbbd393cc31f523b2356ebeea9bd3f45fe is missing

**Comment by MrVan** [comment]
Thanks. I use latest kernel driver, but local tee is still 2.3.0. Need to cherry pick this patch. :)
