### ISSUE TITLE
How to run TA in 64 bits for TA in Juno Box OPTEE

### ISSUE THREAD

**Issue by ggao-inven** [OP-TEE/optee_os#1454]
Hi,
 I am trying to use JUNO Box OPTEE to run TA. I noticed that in the example code "Hello World", we are supposed to set "TA_DEV_KIT_DIR=arm-plat-vexpress/export-ta_arm32" and "CROSS_COMPILE=arm-linux-gnueabihf-". This basically set the TA running in 32 bits. According to issue
https://github.com/OP-TEE/optee_os/issues/1210#issuecomment-265665072
, OPTEE/JUNO box supports both 32 bits and 64 bits. I tried to change it to "TA_DEV_KIT_DIR=arm-plat-vexpress/export-ta_arm64" and "CROSS_COMPILE=aarch64-linux-gnu-". The compilation is OK. However, when I pushed the compiled TA to TEE enviroment, it gave me the error of "Unknown relocation type 257". 
  I check the TEE core compilation flag. The way I check is to check the "out/" directory under "optee_os" check one files compilation command, such as "core/kernel/tee_ta_manager.o". The compiler it uses is "aarch64-linux-gnu-gcc". It looks the core is compiled in 64 bits. So the TA compiled this way should work. 
  Could you help me about this?

  Thanks.

Best

Ge

**Comment by jenswi-linaro** [comment]
This problem is fixed with commit ef53fb06ad9e5dd616e327a05fce60c74db90ce7

**Comment by ggao-inven** [comment]
Thanks. I will try it out.

**Comment by ggao-inven** [comment]
I tried this new commit. It seems a lot of things changed compared with the version I was using, which is 16-06. It can't load my dynamic TA, even I change the endianess according to its requirements. 
My current configuration is: Android M, 16-06 Linux, with this commit's OPTEE_OS. 
The error is can't find the item (0xffff0008).

**Comment by vchong** [comment]
Did you just cherry-pick the commit, or pull optee_os up to that commit?
How are you changing the endianness?
Are you building from source, or using prebuilt images?
If building from source, do you see the *.ta files in the out/ dir?

**Comment by ggao-inven** [comment]
I pull optee_os up to that commit.
The UUID of TA is changed. It was big-endian and it is little-endian.

**Comment by vchong** [comment]
Did you change the endian in related android makefiles too, if applicable?
Also maybe try running as root.

**Comment by ggao-inven** [comment]
I did run as root. There is no endianness need to be changed on the android side.

**Comment by vchong** [comment]
Ok, so you're compiling hello world separately/independently outside of the android source tree? In that case, then try using an android toolchain instead. They can be found under the android source tree at prebuilts/gcc/linux-x86/aarch64/.

**Comment by vchong** [comment]
In any case, it's probably a bad idea to update optee_os only while leaving the other optee_* repos alone. It might be easier to just cherry pick the https://github.com/OP-TEE/optee_os/commit/ef53fb06ad9e5dd616e327a05fce60c74db90ce7 patch.

**Comment by ggao-inven** [comment]
Thanks. I think that is a better idea. It works. I just worried that in the future update it would not work when I really need to update to that commit. So far it is OK.
Thanks.

Ge

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
