### ISSUE TITLE
optee qemu repo sync : busybox.net connection refused

### ISSUE THREAD

**Issue by saurabhsamanta** [OP-TEE/optee_os#1457]
I am a newbie and trying to build optee qemu version. Before that I tried my hands on raspberry pi3 and my endeavour was successful. Now when I am  trying to build qemu version things are not working with busybox link. 

Command run : 
$ sudo  repo init -u https://github.com/OP-TEE/manifest.git -m default_stable.xml -b master
$ sudo repo sync 
... A new repo command ( 1.23) is available.
... You should upgrade soon:

    cp /home/trustzone/qemu/.repo/repo/repo /usr/bin/repo

Fetching project build.git
Fetching projects:   8% (1/12)  Fetching project soc_term.git
Fetching projects:  16% (2/12)  Fetching project arm-trusted-firmware.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
remote: Counting objects: 18440, done.        
remote: Compressing objects: 100% (3/3), done.        
remote: Total 18440 (delta 0), reused 0 (delta 0), pack-reused 18437        
Receiving objects: 100% (18440/18440), 8.09 MiB | 109.00 KiB/s, done.
Resolving deltas: 100% (11306/11306), done.
From https://github.com/linaro-swg/arm-trusted-firmware
 * [new branch]      hikey      -> linaro-swg/hikey
 * [new branch]      hikey-sec  -> linaro-swg/hikey-sec
 * [new branch]      hikey_gendrv -> linaro-swg/hikey_gendrv
 * [new branch]      integration -> linaro-swg/integration
 * [new branch]      master     -> linaro-swg/master
 * [new branch]      mt8173_evb -> linaro-swg/mt8173_evb
 * [new branch]      optee_paged_armtf_v1.1 -> linaro-swg/optee_paged_armtf_v1.1
 * [new branch]      optee_paged_armtf_v1.2 -> linaro-swg/optee_paged_armtf_v1.2
 * [new branch]      optee_paged_armtf_v1.3 -> linaro-swg/optee_paged_armtf_v1.3
 * [new branch]      optee_v2.1.0_paged_armtf_v1.2 -> linaro-swg/optee_v2.1.0_paged_armtf_v1.2
 * [new branch]      qemu_optee_v8 -> linaro-swg/qemu_optee_v8
 * [new branch]      rfc/psci-comp-pwr-states -> linaro-swg/rfc/psci-comp-pwr-states
 * [new branch]      rfc/psci-comp-pwr-states-v2 -> linaro-swg/rfc/psci-comp-pwr-states-v2
 * [new branch]      rfc/psci-new-top-desc -> linaro-swg/rfc/psci-new-top-desc
 * [new branch]      rpi3_initial_drop -> linaro-swg/rpi3_initial_drop
 * [new tag]         for-v0.4-rc0 -> for-v0.4-rc0
 * [new tag]         for-v0.4/05.20 -> for-v0.4/05.20
 * [new tag]         for-v0.4/05.21 -> for-v0.4/05.21
 * [new tag]         for-v0.4/05.22 -> for-v0.4/05.22
 * [new tag]         v0.2       -> v0.2
 * [new tag]         v0.3       -> v0.3
 * [new tag]         v0.3-Juno  -> v0.3-Juno
 * [new tag]         v0.3-Juno-0.2 -> v0.3-Juno-0.2
 * [new tag]         v0.3-Juno-0.3 -> v0.3-Juno-0.3
 * [new tag]         v0.4       -> v0.4
 * [new tag]         v0.4-Juno-0.4 -> v0.4-Juno-0.4
 * [new tag]         v0.4-Juno-0.4-rc0 -> v0.4-Juno-0.4-rc0
 * [new tag]         v0.4-Juno-0.5 -> v0.4-Juno-0.5
 * [new tag]         v0.4-Juno-0.5-rc0 -> v0.4-Juno-0.5-rc0
 * [new tag]         v0.4-Juno-0.5-rc1 -> v0.4-Juno-0.5-rc1
 * [new tag]         v0.4-Juno-0.6-rc0 -> v0.4-Juno-0.6-rc0
 * [new tag]         v0.4-Juno-0.6-rc1 -> v0.4-Juno-0.6-rc1
 * [new tag]         v0.4-rc1   -> v0.4-rc1
 * [new tag]         v0.4-rc2   -> v0.4-rc2
 * [new tag]         v1.0       -> v1.0
 * [new tag]         v1.0-rc0   -> v1.0-rc0
 * [new tag]         v1.1       -> v1.1
 * [new tag]         v1.1-Juno-0.1 -> v1.1-Juno-0.1
 * [new tag]         v1.1-rc0   -> v1.1-rc0
 * [new tag]         v1.1-rc1   -> v1.1-rc1
 * [new tag]         v1.1-rc2   -> v1.1-rc2
 * [new tag]         v1.1-rc3   -> v1.1-rc3
Fetching projects:  25% (3/12)  Fetching project qemu.git
remote: Counting objects: 13, done.        
remote: Compressing objects: 100% (13/13), done.        
remote: Total 13 (delta 3), reused 0 (delta 0), pack-reused 0        
From https://github.com/qemu/qemu
   95b31d7..6954cdc  master     -> qemu/master
Fetching projects:  33% (4/12)  Fetching project optee_test.git
Fetching projects:  41% (5/12)  Fetching project code
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
remote: Counting objects: 31561, done.        
remote: Compressing objects: 100% (11022/11022), done.        
remote: Total 31561 (delta 23289), reused 27276 (delta 20059)        
Receiving objects: 100% (31561/31561), 6.93 MiB | 518.00 KiB/s, done.
Resolving deltas: 100% (23289/23289), done.
From http://git.code.sf.net/p/strace/code
 * [new branch]      ldv/master -> sfnet/ldv/master
 * [new branch]      ldv/selinux -> sfnet/ldv/selinux
 * [new branch]      ldv/unifdef -> sfnet/ldv/unifdef
 * [new branch]      lp/mpers   -> sfnet/lp/mpers
 * [new branch]      master     -> sfnet/master
 * [new branch]      obsolete/HEAD -> sfnet/obsolete/HEAD
 * [new branch]      obsolete/WTA -> sfnet/obsolete/WTA
 * [new branch]      obsolete/ia64.0 -> sfnet/obsolete/ia64.0
 * [new branch]      obsolete/v4.0.1 -> sfnet/obsolete/v4.0.1
 * [new branch]      rebase     -> sfnet/rebase
 * [new tag]         v3.99.1    -> v3.99.1
 * [new tag]         v4.1       -> v4.1
 * [new tag]         v4.10      -> v4.10
 * [new tag]         v4.11      -> v4.11
 * [new tag]         v4.12      -> v4.12
 * [new tag]         v4.13      -> v4.13
 * [new tag]         v4.14      -> v4.14
 * [new tag]         v4.15      -> v4.15
 * [new tag]         v4.16      -> v4.16
 * [new tag]         v4.2       -> v4.2
 * [new tag]         v4.3       -> v4.3
 * [new tag]         v4.4       -> v4.4
 * [new tag]         v4.4.90    -> v4.4.90
 * [new tag]         v4.4.91    -> v4.4.91
 * [new tag]         v4.4.92    -> v4.4.92
 * [new tag]         v4.4.93    -> v4.4.93
 * [new tag]         v4.4.95    -> v4.4.95
 * [new tag]         v4.4.98    -> v4.4.98
 * [new tag]         v4.5       -> v4.5
 * [new tag]         v4.5.1     -> v4.5.1
 * [new tag]         v4.5.10    -> v4.5.10
 * [new tag]         v4.5.11    -> v4.5.11
 * [new tag]         v4.5.12    -> v4.5.12
 * [new tag]         v4.5.13    -> v4.5.13
 * [new tag]         v4.5.14    -> v4.5.14
 * [new tag]         v4.5.15    -> v4.5.15
 * [new tag]         v4.5.16    -> v4.5.16
 * [new tag]         v4.5.17    -> v4.5.17
 * [new tag]         v4.5.18    -> v4.5.18
 * [new tag]         v4.5.19    -> v4.5.19
 * [new tag]         v4.5.2     -> v4.5.2
 * [new tag]         v4.5.20    -> v4.5.20
 * [new tag]         v4.5.3     -> v4.5.3
 * [new tag]         v4.5.4     -> v4.5.4
 * [new tag]         v4.5.5     -> v4.5.5
 * [new tag]         v4.5.6     -> v4.5.6
 * [new tag]         v4.5.7     -> v4.5.7
 * [new tag]         v4.5.8     -> v4.5.8
 * [new tag]         v4.5.9     -> v4.5.9
 * [new tag]         v4.6       -> v4.6
 * [new tag]         v4.7       -> v4.7
 * [new tag]         v4.8       -> v4.8
 * [new tag]         v4.9       -> v4.9
 * [new tag]         version.1.0 -> version.1.0
Fetching projects:  50% (6/12)  Fetching project hello_world.git
Fetching projects:  58% (7/12)  Fetching project busybox.git
fatal: unable to connect to busybox.net:
busybox.net[0: 140.211.167.122]: errno=Connection refused

fatal: unable to connect to busybox.net:
busybox.net[0: 140.211.167.122]: errno=Connection refused

error: Cannot fetch busybox.git

error: Exited sync due to fetch errors
----------------------------------------------------------

**Comment by etienne-lms** [comment]
The URL defined in the OP-TEE manifest (git://busybox.net/busybox.git) seems valid: see https://busybox.net/source.html.

Maybe you fail to clone it through the git protocol and should try through a http port.
Try to update your **.repo/manifest.xml** file the following way

Either using the github mirror:
```
-	<remote name="busybox" fetch="git://busybox.net" />
+	<remote name="busybox" fetch="https://github.com/mirror" />
```

Or using thebusybox http url:
```
-	<remote name="busybox" fetch="git://busybox.net" />
+	<remote name="busybox" fetch="http://git.busybox.net" />
```
and 
```
-	<project remote="busybox" path="busybox" name="busybox.git" revision="dbf5a6da6a4295ce26edd1ce34fde567d19afa02" />
+	<project remote="busybox" path="busybox" name="busybox" revision="dbf5a6da6a4295ce26edd1ce34fde567d19afa02" />
```

Once done, `repo sync` again.

**Comment by saurabhsamanta** [comment]
Thanks a lot @etienne-lms . Its working. I tried changing it but I was doing mistake in remote part.
