### ISSUE TITLE
OP-TEE does not boots on RCAR H3 board. 

### ISSUE THREAD

**Issue by lorc** [OP-TEE/optee_os#1460]
I have identified patch that causes this: c7743970a05d95909ced0ed841ae2e895926c0c7

Reverting that patch fixes issue. I'm looking for proper fix.

**Comment by lorc** [comment]
Just found another workaround: disable UART driver.

**Comment by lorc** [comment]
Another workaround:
```
--- a/core/arch/arm/mm/core_mmu.c
+++ b/core/arch/arm/mm/core_mmu.c
@@ -450,11 +450,6 @@ static void init_mem_map(struct tee_mmap_region *memory_map, size_t num_elems)
 	     mem < &__end_phys_mem_map_section; mem++) {
 		struct core_mmu_phys_mem m = *mem;
 
-		if (m.type == MEM_AREA_IO_NSEC || m.type == MEM_AREA_IO_SEC) {
-			m.addr = ROUNDDOWN(m.addr, CORE_MMU_PGDIR_SIZE);
-			m.size = ROUNDUP(m.size + (mem->addr - m.addr),
-					 CORE_MMU_PGDIR_SIZE);
-		}
 		add_phys_mem(memory_map, num_elems, &m, &last);
 	}
```

**Comment by jenswi-linaro** [comment]
Does it make any difference if you're using LPAE or not?
When printing out the mapping information that is going to be used, can you see anything suspicious?

**Comment by lorc** [comment]
It is armv8 CPU, so LPAE is only one option.

I can't print anything, because it hangs when I try to use UART.

**Comment by jenswi-linaro** [comment]
Before MMU is turned ON this stuff shouldn't matter.

**Comment by lorc** [comment]
There was two issues. One with UART (ARM TF now disables it before calling OP-TEE). Another with xlat tables:

> DEBUG:   TEE-CORE:add_phys_mem:353: CFG_SHMEM_START 4 0x47e00000 size 0x00100000
> DEBUG:   TEE-CORE:add_phys_mem:353: CFG_TA_RAM_START 3 0x44200000 size 0x03c00000
> DEBUG:   TEE-CORE:add_phys_mem:353: CFG_TEE_RAM_START 1 0x44100000 size 0x00100000
> DEBUG:   TEE-CORE:add_phys_mem:353: GICC_BASE 8 0xf1000000 size 0x00200000
> DEBUG:   TEE-CORE:add_phys_mem:353: GICD_BASE 8 0xf1000000 size 0x00200000
> DEBUG:   TEE-CORE:add_phys_mem:365: Physical mem map overlaps 0xf1000000
> DEBUG:   TEE-CORE:add_phys_mem:353: CONSOLE_UART_BASE 8 0xe6e00000 size 0x00200000
> DEBUG:   TEE-CORE:add_va_space:390: type 9 size 0x01400000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 1 0x44100000..0x441fffff pa 0x44100000..0x441fffff size 0x100000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 3 0x44200000..0x47dfffff pa 0x44200000..0x47dfffff size 0x3c00000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 4 0x47e00000..0x47efffff pa 0x47e00000..0x47efffff size 0x100000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 8 0x47f00000..0x480fffff pa 0xe6e00000..0xe6ffffff size 0x200000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 8 0x48100000..0x482fffff pa 0xf1000000..0xf11fffff size 0x200000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 9 0x48300000..0x496fffff pa 0x00000000..0x013fffff size 0x1400000
> ERROR:   TEE-CORE: Panic 'running out of xlat tables' at core/arch/arm/mm/core_mmu_lpae.c:407 <init_xlation_table>
> ERROR:   TEE-CORE: pc  0x00000000441088f4


I have increased number of xlat tables, now it just hangs:

> DEBUG:   TEE-CORE:add_phys_mem:353: CFG_SHMEM_START 4 0x47e00000 size 0x00100000
> DEBUG:   TEE-CORE:add_phys_mem:353: CFG_TA_RAM_START 3 0x44200000 size 0x03c00000
> DEBUG:   TEE-CORE:add_phys_mem:353: CFG_TEE_RAM_START 1 0x44100000 size 0x00100000
> DEBUG:   TEE-CORE:add_phys_mem:353: GICC_BASE 8 0xf1000000 size 0x00200000
> DEBUG:   TEE-CORE:add_phys_mem:353: GICD_BASE 8 0xf1000000 size 0x00200000
> DEBUG:   TEE-CORE:add_phys_mem:365: Physical mem map overlaps 0xf1000000
> DEBUG:   TEE-CORE:add_phys_mem:353: CONSOLE_UART_BASE 8 0xe6e00000 size 0x00200000
> DEBUG:   TEE-CORE:add_va_space:390: type 9 size 0x01400000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 1 0x44100000..0x441fffff pa 0x44100000..0x441fffff size 0x100000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 3 0x44200000..0x47dfffff pa 0x44200000..0x47dfffff size 0x3c00000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 4 0x47e00000..0x47efffff pa 0x47e00000..0x47efffff size 0x100000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 8 0x47f00000..0x480fffff pa 0xe6e00000..0xe6ffffff size 0x200000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 8 0x48100000..0x482fffff pa 0xf1000000..0xf11fffff size 0x200000
> DEBUG:   TEE-CORE:init_mem_map:537: type va 9 0x48300000..0x496fffff pa 0x00000000..0x013fffff size 0x1400000


... at that's all.
