### ISSUE TITLE
Can I get device infomation by TA?

### ISSUE THREAD

**Issue by JQkai** [OP-TEE/optee_os#1469]
HI, 
If I want to get some device information (like CPU id or MAC address etc.) to check the device is correct or not, can I finish this work at TA?

Presently, I can get those information at CA and commit to TA, but I do not find the relative method or api at security world to read the device info. So I want to confirm that is the device info can be read by TA?

Thanks for reply.

**Comment by etienne-lms** [comment]
Hi @JQkai, there is no such API for a TA to get these information. If your TA need them, they shall be provided by the CA.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
