### ISSUE TITLE
Can the GP functions be called in TA_CreateEntryPoint?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1471]
Hi

In TA_CreateEntryPoint, the TA context is not fully created, so my understanding is that there maybe are some restrictions, and i can't find exactly what can be done in TA_CreateEntryPoint, there is no guide or example. 

Thank you.

**Comment by etienne-lms** [comment]
Hi @prime-zeng,
At `TA_CreateEntryPoint(),` the TA context is already full initialized and there is no specific restriction on what a TA can do. This entry point is there for a TA to do whatever it needs to. Check [`ta_header_add_session()`](https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/arch/arm/user_ta_entry.c#L151), `TA_CreateEntryPoint()` is only called before the session info are setup for the `TA_OpenSessionEntryPoint()` to use them.

**Comment by prime-zeng** [comment]
@etienne-lms 
Yes,  when calling the TA_CreateEntryPoint, only the ta_session is not inserted into the ta_sessions list, i have search the code, it won't restrict what the TA_CreateEntryPoint can do.

Thank you.
