### ISSUE TITLE
QEMU_v8 hang after run

### ISSUE THREAD

**Issue by saurabhsamanta** [OP-TEE/optee_os#1476]
![errot](https://cloud.githubusercontent.com/assets/20583900/24867292/60af25f8-1e2a-11e7-82da-8b2570043d7d.png)
After make all run I am getting the above image.
I am trying c on qemu shell but nothing is happening.

**Comment by vchong** [comment]
You're using qemu_v8. No need to type c. But there was an issue that was fixed recently. Please clean your builds, run `repo sync` to update your sources and build again.

**Comment by saurabhsamanta** [comment]
After repo sync and build, I am stuck with following errors. With default qemu I have success. Struggle is with qemu_v8.

"GenFw" -e UEFI_DRIVER -o /home/trustzone/qemu-v8/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdeModulePkg/Universal/Network/Udp4Dxe/Udp4Dxe/DEBUG/Udp4Dxe.efi /home/trustzone/qemu-v8/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdeModulePkg/Universal/Network/Udp4Dxe/Udp4Dxe/DEBUG/Udp4Dxe.dll
"iasl"  -p/home/trustzone/qemu-v8/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDxe/OUTPUT/./RamDisk.aml /home/trustzone/qemu-v8/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDxe/OUTPUT/./RamDisk.iiii
/bin/sh: 1: iasl: not found
GNUmakefile:612: recipe for target '/home/trustzone/qemu-v8/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDxe/OUTPUT/RamDisk.aml' failed
make[2]: Leaving directory '/home/trustzone/qemu-v8/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDxe'
make[2]: *** [/home/trustzone/qemu-v8/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDxe/OUTPUT/RamDisk.aml] Error 127


build.py...
 : error 7000: Failed to execute command
	make tbuild [/home/trustzone/qemu-v8/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDxe]


build.py...
 : error F002: Failed to build module
	/home/trustzone/qemu-v8/edk2/MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDxe.inf [AARCH64, GCC49, DEBUG]

- Failed -
Build end time: 01:14:38, Apr.13 2017
Build total time: 00:00:22

ArmPlatformPkg/Scripts/Makefile:58: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/trustzone/qemu-v8/edk2'
common.mk:183: recipe for target 'edk2-common' failed
make: *** [edk2-common] Error 2

**Comment by vchong** [comment]
Try `sudo apt-get install iasl` first.

**Comment by saurabhsamanta** [comment]
Thanks a ton @vchong  . Now things are working properly. I faced with one more error with missing content in qemu/dtc/ directory which I sorted by downloading the contents from 
http://git.qemu-project.org/?p=dtc.git;a=snapshot;h=1760e7ca03894689118646e229ca9487158cd0e8;sf=tgz 
Then everything worked fine.
