### ISSUE TITLE
how to use TZC400 in foundation fvp

### ISSUE THREAD

**Issue by clark-chen** [OP-TEE/optee_os#1479]
i used fvp.xml,and dowload the foundation fvp, everythong is ok. But when i see:
https://github.com/ARM-software/arm-trusted-firmware/blob/77b05323921c23e4261ddd8fee5c326a79b0af97/plat/arm/board/fvp/fvp_security.c
i found The Base FVP has a TrustZone address space controller, the Foundation FVP does not. So,is it means i can not use the TZC400 unless i use the base fvp?
another question:how can i download the base fvp with the below website?
https://developer.arm.com/products/system-design/fixed-virtual-platforms
and can i use TZC400 in qemu?
thanks for your answer.

**Comment by jenswi-linaro** [comment]
As for how to download FVP Base Model I suppose you need to follow the instructions at that page.
I don't know if QEMU emulates TZC400, probably not.

**Comment by clark-chen** [comment]
Do you mean that the foundation fvp does not emulates TZC400?

**Comment by jenswi-linaro** [comment]
I don't think it does. but you'd better consult the documentation to be sure.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
