### ISSUE TITLE
storage subsystem becomes broken after error in `ree_fs_readdir_rpc()`

### ISSUE THREAD

**Issue by lorc** [OP-TEE/optee_os#1482]
I have found this issue accidentally, when playing with shared memory. Please close it if it is irrelevant.

Looks like internal state of `tee_pobj` brokes when TA panics during FS operations.

Steps to reproduce:

1. Apply this patch:
```
diff --git a/core/tee/tee_ree_fs.c b/core/tee/tee_ree_fs.c
index ca27373..9710669 100644
--- a/core/tee/tee_ree_fs.c
+++ b/core/tee/tee_ree_fs.c
@@ -77,7 +77,9 @@ static void ree_fs_closedir_rpc(struct tee_fs_dir *d)
 static TEE_Result ree_fs_readdir_rpc(struct tee_fs_dir *d,
                                     struct tee_fs_dirent **ent)
 {
-       return tee_fs_rpc_readdir(OPTEE_MSG_RPC_CMD_FS, d, ent);
+       d = d;
+       ent = ent;
+       return TEE_ERROR_GENERIC;
 }
 
 static TEE_Result out_of_place_write(struct tee_fs_fd *fdp, size_t pos,
```

Now one of tests will always fail. This will lead to TA panic.

2. Build OPTEE and run `xtest 600`:

> root@Vexpress:/ xtest 600
> Test ID: 600
> Run test suite with level=0
> 
> TEE test application started with device [(null)]
> ######################################################
> #
> # regression
> #
> ######################################################
>  
> * regression_6001 Test TEE_CreatePersistentObject
> o regression_6001.1 Storage id: 00000001
>   regression_6001.1 OK
> o regression_6001.2 Storage id: 80000000
>   regression_6001.2 OK
>   regression_6001 OK
>  
> * regression_6002 Test TEE_OpenPersistentObject
> o regression_6002.1 Storage id: 00000001
>   regression_6002.1 OK
> o regression_6002.2 Storage id: 80000000
>   regression_6002.2 OK
>   regression_6002 OK
>  
> * regression_6003 Test TEE_ReadObjectData
> o regression_6003.1 Storage id: 00000001
>   regression_6003.1 OK
> o regression_6003.2 Storage id: 80000000
>   regression_6003.2 OK
>   regression_6003 OK
>  
> * regression_6004 Test TEE_WriteObjectData
> o regression_6004.1 Storage id: 00000001
>   regression_6004.1 OK
> o regression_6004.2 Storage id: 80000000
>   regression_6004.2 OK
>   regression_6004 OK
>  
> * regression_6005 Test TEE_SeekObjectData
> o regression_6005.1 Storage id: 00000001
>   regression_6005.1 OK
> o regression_6005.2 Storage id: 80000000
>   regression_6005.2 OK
>   regression_6005 OK
>  
> * regression_6006 Test TEE_CloseAndDeletePersistentObject
> o regression_6006.1 Storage id: 00000001
>   regression_6006.1 OK
> o regression_6006.2 Storage id: 80000000
>   regression_6006.2 OK
>   regression_6006 OK
>  
> * regression_6007 Test TEE_TruncateObjectData
> o regression_6007.1 Storage id: 00000001
> o regression_6007.1.1 Test truncate file length
>   regression_6007.1.1 OK
> o regression_6007.1.2 Test extend file length
>   regression_6007.1.2 OK
> o regression_6007.1.3 Test file hole
>   regression_6007.1.3 OK
>   regression_6007.1 OK
> o regression_6007.2 Storage id: 80000000
> o regression_6007.2.1 Test truncate file length
>   regression_6007.2.1 OK
> o regression_6007.2.2 Test extend file length
>   regression_6007.2.2 OK
> o regression_6007.2.3 Test file hole
>   regression_6007.2.3 OK
>   regression_6007.2 OK
>   regression_6007 OK
>  
> * regression_6008 Test TEE_RenamePersistentObject
> o regression_6008.1 Storage id: 00000001
>   regression_6008.1 OK
> o regression_6008.2 Storage id: 80000000
>   regression_6008.2 OK
>   regression_6008 OK
>  
> * regression_6009 Test TEE Internal API Persistent Object Enumeration Functions
> o regression_6009.1 Storage id: 00000001
> /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:1118: fs_next_enum(&sess, e, info, sizeof(info), id, sizeof(id)) has an unexpected value: 0xffff3024 = TEE_ERROR_TARGET_DEAD, expected 0x0 = TEEC_SUCCESS
>   regression_6009.1 FAILED
> o regression_6009.2 Storage id: 80000000
> /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:1083: fs_create(&sess, file_00, sizeof(file_00), 0x00000002, 0, data_01, sizeof(data_01), &obj0, storage_id) has an unexpected value: 0xffff0003 = TEEC_ERROR_ACCESS_CONFLICT, expected 0x0 = TEEC_SUCCESS
>   regression_6009.2 FAILED
>   regression_6009 FAILED
> +-----------------------------------------------------
> Result of testsuite regression filtered by "600":
> regression_6001 OK
> regression_6002 OK
> regression_6003 OK
> regression_6004 OK
> regression_6005 OK
> regression_6006 OK
> regression_6007 OK
> regression_6008 OK
> regression_6009.1 FAILED first error at /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:1118
> regression_6009.2 FAILED first error at /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:1083
> regression_6009 FAILED
> 

Note that first 8 tests are running fine. 6009 fails due to our patch.

3. Now any attempt to run any FS-related test will fail with `TEEC_ERROR_ACCESS_CONFLICT`:

> root@Vexpress:/ xtest 6001
> Test ID: 6001
> Run test suite with level=0
> 
> TEE test application started with device [(null)]
> ######################################################
> #
> # regression
> #
> ######################################################
>  
> * regression_6001 Test TEE_CreatePersistentObject
> o regression_6001.1 Storage id: 00000001
> /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:737: fs_create(&sess, file_00, sizeof(file_00), 0x00000002 | 0x00000004, 0, data_00, sizeof(data_00), &obj, storage_id) has an unexpected value: 0xffff0003 = TEEC_ERROR_ACCESS_CONFLICT, expected 0x0 = TEEC_SUCCESS
>   regression_6001.1 FAILED
> o regression_6001.2 Storage id: 80000000
> /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:737: fs_create(&sess, file_00, sizeof(file_00), 0x00000002 | 0x00000004, 0, data_00, sizeof(data_00), &obj, storage_id) has an unexpected value: 0xffff0003 = TEEC_ERROR_ACCESS_CONFLICT, expected 0x0 = TEEC_SUCCESS
>   regression_6001.2 FAILED
>   regression_6001 FAILED
> +-----------------------------------------------------
> Result of testsuite regression filtered by "6001":
> regression_6001.1 FAILED first error at /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:737
> regression_6001.2 FAILED first error at /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:737
> regression_6001 FAILED
> 

That is the issue. Imagine, that there will be single error in FS. After that all TA's will lose ability to work with FS.

**Comment by etienne-lms** [comment]
True. If a TA panics, its related read/write secure storage could be compromised.
Should it be wiped-out? or restored to a trusted backup?

**Comment by lorc** [comment]
I don't know. Maybe it should be wiped out.
It bothers me from user's point of view: TA just breaks and you don't know
why and how to fix this.

Again, I'm not sure if it is a bug. I just stumbled on strange behavior and
decided to report it.

**Comment by jbech-linaro** [comment]
@lorc, have digged more into this since the last comment? I'm trying to do an issue cleanup and close old, fixed or irrelevant issues.

**Comment by lorc** [comment]
@jbech-linaro, no, sorry. I even don't know if it is still reproducible.

I just wanted to asked your, opinion, guys. As I said, from user perspective this looks bad. But right now I have no real use case, when you hit this issue. So, I'll close this issue for now. 
It can be reopened, if someone else will stumble over it.
