### ISSUE TITLE
Virtual address and Physical address for TA

### ISSUE THREAD

**Issue by toddkuhreng** [OP-TEE/optee_os#1484]
Hi all,
I am trying to find physical address on a variable declared inside a  
Pseudo TA. I see virtual address and physical address of the variable are  same. 
So does this mean OP-TEE uses direct mapping, that is, VA  is same as PA.

Following is the code I tested: 
```

static TEE_Result test_trace(uint32_t param_types __unused,
                        TEE_Param params[TEE_NUM_PARAMS] __unused)
{
        unsigned int x = 4;
        paddr_t x_pa;

        vaddr_t x_va = (vaddr_t) &x;
        x_pa = virt_to_phys((void *)x_va);

        IMSG("Pseudo TA \"%s\" says \"Hello world !\"", TA_NAME);
        IMSG("VA x address x_va:  0x%lx ", x_va);
        DMSG("PA :  0x%lx ", x_pa);
        return TEE_SUCCESS;
}

```

Output:
```
INFO:    TEE-CORE: VA x address x_va:  0x3f08531c 
DEBUG:   [0x0] TEE-CORE:test_trace:58: PA :  0x3f08531c

```

Is this case for normal TA too?

**Comment by jforissier** [comment]
Yes, flat mapping for TEE core (EL1) but not for TAs (EL0).

**Comment by toddkuhreng** [comment]
How can I find physical address of a variable defined in TA? is there any API like virt_to_phys for TA?

**Comment by jforissier** [comment]
Short answer: you can't.
Long answer: Can you do this in a Linux app for instance? The answer is no, and it's the same in the secure world. What would you do with the PA? If you could access any PA not mapped by the TA, it would be a security violation (TA separation). In addition, even for addreses mapped by the TA, there is no guarantee that the PA remains the same for a given VA. Paging is a typical case.

**Comment by toddkuhreng** [comment]
I understand. I was wondering whether there is any mechanism like pagemap in secureworld (Or any kind of hack)? In normal world I could translate VA to PA using pagemap.

**Comment by jforissier** [comment]
Right, I forgot about `pagemap`, sorry. Anyway, there is no such mechanism in OP-TEE.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
