### ISSUE TITLE
Integrity check of dynamic TA in Android + OPTEE setup 

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1485]
I have setup a branch containing Android + OPTEE. I have a question about the use of dynamic TA. When I compile my branch, all the TA folders sit in Android's `external` folder. Once the device is running, the TA (.ta) files end up in `/system/lib/optee_armtz`. When a TA is invoked, my understanding is that one of the .ta files from this folder is loaded into TEE to get executed. 

My question is that does the OPTEE OS do some kind of integrity check of the .ta files before executing them inside TEE. I ask because the .ta files are sitting in the file system of a potentially compromised space.

If there is no integrity check, is using static TA the only solution towards guaranteeing which code is executed inside TEE (because such TA sits inside OPTEE kernel).

**Comment by jforissier** [comment]
Yes, TAs are signed. The default key is https://github.com/OP-TEE/optee_os/blob/master/keys/default_ta.pem. You should obviously change it if you're deploying a real product.

**Comment by a2t2** [comment]
Can you tell which component in OPTEE OS verifies the signature ?

**Comment by jforissier** [comment]
The TA binary is hashed as it is loaded by the ELF loader, then the hash is verified. It all happens here: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/user_ta.c#L393-L399

**Comment by jforissier** [comment]
So, it is the TEE core (secure EL1) that perfoms the check.

**Comment by a2t2** [comment]
Okay thanks.
