### ISSUE TITLE
Enforcement of MEM_AREA_IO_SEC flag in OPTEE

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1486]
I have a question regarding the MEM_AREA_IO_SEC flag which I find being mentioned in the following files:

- [core_mmu.h](https://github.com/OP-TEE/optee_os/blob/62ede146cd05fc17421728debc5f9d9c6c614d76/core/arch/arm/include/mm/core_mmu.h) 
- [core_mmu.c](https://github.com/OP-TEE/optee_os/blob/62ede146cd05fc17421728debc5f9d9c6c614d76/core/arch/arm/mm/core_mmu.c)

Based on my understanding so far, it seems that these flags are to protect hardware registers (e.g. for UART), and that the enforcement is in the MMU. My question is as follows (I will use UART as an example):
if a UART physical address is marked as MEM_AREA_IO_SEC, and untrusted OS (normal world) somehow has a virtual address that maps to this physical address, is the enforcement in MMU done by refusing to do translation from virtual to physical (by looking at the NS bit and noticing that the corresponding physical address is marked  MEM_AREA_IO_SEC) ? Would it be possible for the untrusted normal world OS to directly read from that physical address ?

**Comment by jenswi-linaro** [comment]
`MEM_AREA_IO_SEC` is used to indicate that the NS should be cleared when mapping this particular memory. It is assumed that the address range already is secure.

If normal world can access a physical address or not is not controlled by the MMU (unless there's a hypervisor but then it only applies to the guest and not the hypervisor itself).

**Comment by a2t2** [comment]
So based on what you are saying, just setting the flag `MEM_AREA_IO_SEC` for a physical address is not enough to protect it from normal world ?

**Comment by jenswi-linaro** [comment]
Correct.

**Comment by a2t2** [comment]
What is the recommended way to enforce such protection then ? Let's take the UART example again. Suppose I know the physical address of the hardware register for a particular UART. I don't want the normal world to be able to read / write from this UART. How would suggest configuring this protection requirement using OPTEE ?

**Comment by jforissier** [comment]
Restricting access to some hardware devices to secure world only is platform specific, and oftentimes undocumented (or under NDA). You may be interested in reading this thread however: https://github.com/OP-TEE/optee_os/issues/1065 (shows how to make HiKey UART3 secure).

**Comment by a2t2** [comment]
@jforissier 
Lets say I have to protect UART 2 from the normal world. Based on the code you posted in the linked question, to protect UART 2, would it be enough to set the appropriate bit (bit 28) from TZPC base address ? Also to double check with you, the TZPC register should not be accessible from normal world.

**Comment by jforissier** [comment]
@a2t2 
>  to protect UART 2, would it be enough to set the appropriate bit (bit 28) from TZPC base address ?

Yes, that should work.

> Also to double check with you, the TZPC register should not be accessible from normal world.

I hope so, but I did not try.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
