### ISSUE TITLE
About shared memory

### ISSUE THREAD

**Issue by yym-hjr** [OP-TEE/optee_os#1487]
Hello, I have a new question about shared memory. When the first TEEC_InvokeCommand allocates a shared memory, and the assignment, when the second TEEC_InvokeCommand, does not pass any arguments, but can not read and write the shared memory. The error log is as follows:
NW: TEEC_InvokeCommand failed with code 0xffff3024 origin 0x3

```
// linux code: 
`TEEC_SharedMemory shm;
	shm.buffer = s1;
	shm.flags = TEEC_MEM_INPUT | TEEC_MEM_OUTPUT;
	shm.size  = 12;
	res = TEEC_RegisterSharedMemory(&ctx, &shm);
	check_res(res, "TEEC_RegisterSharedMemory");
	memset(&op, 0, sizeof(op));
	op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_WHOLE ,TEEC_NONE,TEEC_NONE,TEEC_NONE);
	
	op.params[0].memref.parent= &shm;
	op.params[0].memref.offset = 0;
	op.params[0].memref.size = count;
	
	res = TEEC_OpenSession(&ctx, &sess, &uuid,
			       	TEEC_LOGIN_PUBLIC, NULL, NULL, &err_origin);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_Opensession failed with code 0x%x origin 0x%x",res, err_origin);

// the first  TEEC_InvokeCommand
	res = TEEC_InvokeCommand(&sess, MEMARY_NO_1, &op,&err_origin);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_InvokeCommand failed with code 0x%x origin 0x%x",res, err_origin);
	
//the second TEEC_InvokeCommand
	res = TEEC_InvokeCommand(&sess, MEMARY_NO_2,NULL, &err_origin);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_InvokeCommand failed with code 0x%x origin 0x%x",res, err_origin);`


// ta code
`static TEE_Result memory_first(uint32_t param_types,TEE_Param params[4])
{
	uint8_t *p;
	int32_t in_len;
	uint32_t exp_param_types = TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INOUT,
						   TEE_PARAM_TYPE_NONE,
						   TEE_PARAM_TYPE_NONE,
						   TEE_PARAM_TYPE_NONE);

	if (param_types != exp_param_types)
		return TEE_ERROR_BAD_PARAMETERS;
	
	p = params[0].memref.buffer;
	in_len = params[0].memref.size;
	TEE_SetInstanceData(p);	
	IMSG ("size=%d     optee_string=%s", in_len, p);
	return TEE_SUCCESS;
}

static TEE_Result memory_second(void)
{
	IMSG ("optee_string_second=%s", (char *)TEE_GetInstanceData());	
	return TEE_SUCCESS;
}
```

**Comment by etienne-lms** [comment]
Hello @yym-hjr,

`TEE_Set/GetInstanceData()` can only be used to refer to memory that is owned by the TA: in the TA heap (malloc pool), in the TA static read-only or read/write data, or in the TA stack but this later is obviously NOT recommended.

A shared memory buffer provided to a TA as an invocation parameters is not memory owned by the TA. Such a shared memory can be accessed by the TA only for the very specific invocation(s) that referred the buffer as an argument. If a TA needs to access a shared memory area for several invocations, the client must invoke the TA each time with the buffer passed as parameter. And note that even so, the buffer may change of (virtual) address at each TA invocation, hence TA must get the buffer address from the invocation parameters and cannot assume it always located at the same (virtual) address. 

OP-TEE currently provides no support for allocating/assigning a shared memory buffer that is mapped/accessible in the TA address space for the whole TA life cycle.
