### ISSUE TITLE
Secure clock API

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1489]
I wanted to ask if OPTEE has any API for a secure clock to get system time (clock not influenced by the normal world).
Thanks.

**Comment by jforissier** [comment]
Hi @a2t2,

It depends on the platform, but generally: yes. `TEE_GetSystemTime()` will return a value based on the physical timer count register (CNTPCT) when the platform supports it, that is, when OP-TEE is built with `CFG_SECURE_TIME_SOURCE_CNTPCT=y`.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
