### ISSUE TITLE
how the function“tee_entry_std(struct thread_smc_args *smc_args)“be called

### ISSUE THREAD

**Issue by clark-chen** [OP-TEE/optee_os#1491]
i knew "tee_entry_std"is the entry point of the TA,when a SMC come.
https://github.com/OP-TEE/optee_os/blob/b5acd532ff25a9b20d8b51fbcfe5400dd507706c/core/arch/arm/tee/entry_std.c#L340
and i find in struct handlers also with it.
`static const struct thread_handlers handlers = {
	.std_smc = tee_entry_std,
	.fast_smc = tee_entry_fast,
	.nintr = main_fiq,`
but i still donot understand where did the parameter (struct thread_smc_args *smc_args) come frome. and when the function tee_entry_std to execute. 
thanks for your help!

**Comment by jenswi-linaro** [comment]
Hi,

Take a look in `vector_std_smc_entry()` and `vector_fast_smc_entry()` in `core/arch/arm/kernel/thread_a{32,64}.S`

**Comment by clark-chen** [comment]
thanks，
i want to assign different address spaces for different TAs in optee_os, so could you tell me the memory allocation process of TAs.
my platform is foundation fvp, thanks for your answer.

**Comment by jenswi-linaro** [comment]
TAs  (user TAs that is, for pseudo TAs it would make sense) already have separate address spaces.

**Comment by clark-chen** [comment]
ok, could you please point out where is the code ,thank you very much!

**Comment by jenswi-linaro** [comment]
If you study `load_elf()` in `core/arch/arm/kernel/user_ta.c` you'll find it.

**Comment by clark-chen** [comment]
as i know, There are two ways to implement Trusted Applications (TAs),Pseudo TAs and Dynamically Loaded TAs, so can you explain what is the user TAs?
my static TA  get out in:
https://github.com/OP-TEE/optee_os/blob/df05d4ea7d586234a254d60818154256cac10489/core/kernel/tee_ta_manager.c#L501

**Comment by jenswi-linaro** [comment]
Yes

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
