### ISSUE TITLE
USB access from pseudo-TA

### ISSUE THREAD

**Issue by yuralty** [OP-TEE/optee_os#1499]
Hello,
I am trying to establish a secure communication to a USB device through OP-TEE on RPi3. I find this task related to #1461 and #1496, where comments suggest that a pseudo-TA may be used in this case.
Then I looked into optee_os/core/include/drivers/ but only found several gpio/uart/serial drivers available. Can anyone help me to figure out which APIs I could use to access my USB device?

To give a little bit more detail, the driver I use for my device in normal world is cdc_acm (http://lxr.free-electrons.com/source/drivers/usb/class/cdc-acm.c). This will create an entry "/dev/ttyACM0" for the and I can simply call "cat /dev/ttyACM0" in user space.

**Comment by vchong** [comment]
Unfortunately, as you'd mentioned above, there's currently no drivers available to talk to a USB device.
