### ISSUE TITLE
xtest 6016 failed question

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#1500]
I am running optee on big.little ARM64. but met the following failure. I set the affinity of xtest to run on one a53 and one A72, and failure.
`optee_test/host/xtest/xtest_6000.c:1582: fs_create(&sess, a->file_name, sizeof(a->file_name), 0x00000002, 0, data_01, sizeof(data_01), &obj, a->storage_id) has an unexpected value: 0xffff0003 =                           TEEC_ERROR_ACCESS_CONFLICT, expected 0x0 = TEEC_SUCCESS`

If I set the affinity to only on A53, no error. If set the affinity to only A72, no error. I do not have a clear idea on this. any comment? Thanks.

**Comment by jenswi-linaro** [comment]
Hi @MrVan 

It sounds like a memory coherency problem between clusters (assuming that big and little are in different clusters). In the end all synchronization depends on a spinlock. I'd double check memory attributes for heap and global variables.

**Comment by jbech-linaro** [comment]
@MrVan @jenswi-linaro still an issue? If not I'd like to close this. Any relation between this one and https://projects.linaro.org/browse/SWG-200: `Xtest 6016 is sometimes (quite often) failing on FVP Foundation model with a 4.9-rc7 kernel`, no?

**Comment by MrVan** [comment]
Not an issue for me now.
