### ISSUE TITLE
Force execution on given core

### ISSUE THREAD

**Issue by paullgnc** [OP-TEE/optee_os#1503]
Hi, 
I am currently working on OP-TEE on HiKey board. I read OP-TEE is multicore. Nonetheless, I would like to control on which core my TA is executing. Is there any way I can do it ? Maybe by modifying something in the kernel to allow OP-TEE to run only on a given core.
Thank you in advance for your support

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/optee_os/issues/926

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
