### ISSUE TITLE
Where in the world can somebody acquire a Juno board.

### ISSUE THREAD

**Issue by dnovick** [OP-TEE/optee_os#1506]
As I've posted before, I'm working on a demo of a specialized crypto algorithm running under TZ. I've got code written, running fine under QEMU, and originally targeting a Xilinx Zedboard. Unfortunately, I'm on hold with that platform, as there seems to be a problem booting Linux in NS world. I'm working with Xilinx on the issue, but no joy yet.

In order to expedite my efforts, and give me a comparison point for debugging my Zynq issues, I figured I'd use a board that is OP-TEE "well-traveled". I posted a question regarding which board would be best, but have no response yet. I went ahead and built the Raspberry PI version this AM...but apparently, I need to make myself a special cable in order to do USB -> UART for console access - i.e. the HDMI I/O doesn't appear to be implemented, and when I boot, the device doesn't get on the net...so I can't interact via SSH either.

Before going out to my local Fry's in search of cable ingredients, I thought I'd look at maybe using the Juno instead. Money really isn't an issue...just whatever platform is least painful to deploy my TA and client. That will at least make my managers happy with a demo, while I go back and figure out my platform issues....oh yeah...and do an OP-TEE implementation on an Altera board (I'm in an Intel person).

Unfortunately, I can't find anywhere online that sells the Juno board. Is it available anywhere? If so, where?

Thanks,
Dave

**Comment by jbech-linaro** [comment]
> Unfortunately, I can't find anywhere online that sells the Juno board. Is it available anywhere? If so, where?

One thing for sure is that we in Linaro are not selling it :) The one that should be able tell where to get it is [Arm](https://developer.arm.com/products/system-design/development-boards/juno-development-board). I would have tried their [support](https://developer.arm.com/support) to get in contact with them.

Regarding hardware to use there are a couple of different alternatives. You have touched RPi3 also. That is fine also and, btw, you don't need to assemble the entire debug cable. If you're not going to use JTAG, then a normal [UART -> USB cable](http://www.ebay.com/itm/Pl2303hx-Converter-Usb-To-Uart-Ttl-Usb-To-Com-Cable-Module-Ic-New-L-/231965014443) is sufficient. Having that said, RPi3 and OP-TEE have some rough corners even though it works. If you cannot find Juno and don't want to use RPi3, then I would probably recommend using [HiKey](https://www.96boards.org/products/ce/), either 960 or 620 (this is being sold out I think) instead. That is a device that used by a few different people in the core OP-TEE team.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
