### ISSUE TITLE
Best way to view secure world console output on RPI3

### ISSUE THREAD

**Issue by dnovick** [OP-TEE/optee_os#1507]
So now that I have a stable OP-TEE platform on my RPI3 with which to work with, I need to be able to debug my client and TA. I'm most concerned about the secure world side of things. With the QEMU build, we get a couple of xterm windows, one with normal world output, and one with secure world output. 

Is there anything analogous to this with the Raspberry PI3 configuration? Normal world is just going to be standard console output...but what about secure world. I need some way to be able to know what is going on there...in case my TA has problems. 

What do others do?

Dave

**Comment by igoropaniuk** [comment]
Hi Dave,

In case if we are talking about UART (as it's possible to receive SW debug output only via UART), you should receive all NW and SW output to it without any additional changes in configs. 

Separation of NW/SW output for RPi3 is a bit complex task, and the complexity is more connected with getting more than one UART working on RPi3. There is a similar discussion in https://raspberrypi.stackexchange.com/questions/3475/how-to-get-more-than-one-uart-interface, and IMHO it is not worth it.

Regards,
Igor

**Comment by dnovick** [comment]
So, I don't need to separate the output. Right now, I'm running only HDMI...so I guess I'll have to go put one of those UART cables together if I want to see those SW messages. For the moment, my client and TA are working fine. I just built a bunch of trace messaging into the TA which might be nice for the demo...and of course necessary if I run into a problem while debugging.

Thanks again,
Dave

**Comment by nikoskoutr** [comment]
Hello,

i would like to get just the NW output for demonstration purposes.
Is there a way to achieve that? My target is to suppress all DEBUG, FLOW and custom dmesg output.

Thank you all for your help.
Nick

**Comment by jforissier** [comment]
Hi @nikoskoutr ,

You can suppress OP-TEE and TA console output by setting `CFG_TEE_CORE_LOG_LEVEL=0` and `CFG_TEE_TA_LOG_LEVEL=0`.

**Comment by nikoskoutr** [comment]
@jforissier Thank you for your help! It is really appreciated!
I have applied your solution to my problem and most of the debug log is suppressed.
I am still getting messages from TEE-CORE, more specifically, the messages are:

`DEBUG:   [0x0] TEE-CORE:tee_ta_init_pseudo_ta_session:259:    Lookup for pseudo TA 3e93872e-aab0-4c7e-abbc-cdde98877665
DEBUG:   [0x0] TEE-CORE:tee_ta_init_user_ta_session:610: Load user TA 3e93872e-aab0-4c7e-abbc-cdde98877665
DEBUG:   [0x0] TEE-CORE:ta_load:316: ELF load address 0x40001000

DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:378: tee_ta_close_session(0x8483e70)
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:397:    ... Destroy session
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:423:    ... Destroy TA ctx`

I have omitted the output of my code to clear things up.
Thank you again,
Nick

**Comment by jforissier** [comment]
Hmmmm... you should not see those messages with `CFG_TEE_CORE_LOG_LEVEL=0`. Something has to set it to 3 or higher in your back. Please check the actual value used during build in out/arm-plat-rpi3/conf.mk (see the `grep` below).

```
optee_os (master)$ make -j9 -s PLATFORM=rpi3
[...]
optee_os (master)$ grep CFG_TEE_CORE_LOG_LEVEL out/arm-plat-rpi3/conf.mk 
CFG_TEE_CORE_LOG_LEVEL=1
optee_os (master)$ strings -a out/arm-plat-rpi3/core/tee.elf | grep "ELF load address"
optee_os (master)$ make -j9 -s PLATFORM=rpi3 CFG_TEE_CORE_LOG_LEVEL=3
[...]
$ grep CFG_TEE_CORE_LOG_LEVEL out/arm-plat-rpi3/conf.mk 
CFG_TEE_CORE_LOG_LEVEL=3
optee_os (master)$ strings -a out/arm-plat-rpi3/core/tee.elf | grep "ELF load address"
ELF load address 0x%x
```

**Comment by nikoskoutr** [comment]
Thank you for your help once again,
I have manipulated a file in the build system to set the log variable for some reason.
I fixed it by using the ?= in the Makefile and it all works, I am not getting any debug messages!
