### ISSUE TITLE
Why would adding a new TA and client app cause boot issues?

### ISSUE THREAD

**Issue by dnovick** [OP-TEE/optee_os#1509]
So, I have a TA and associated normal world client app that I've just deployed with my OP-TEE build for the PI3. Both binaries deployed fine to the rootfs and got built into the SD card image as expected.

However, now when I boot...I never get a command prompt. I am setup for HDMI, and can see all the boot messages down to the keyboard and mouse init. It is right after this that I usually just hint <enter> and have my prompt. Now when I hit enter, a "2" is printed...then keyboard will echo whatever I type...but I never get a prompt...it's as if my initial shell process never starts.

I cannot see how my changes could be related. I didn't rebuild the kernel, etc...as I saw no reason to. However, I'm going to go ahead and build clean and try  again. I figured I'd post this question just in case there is a logical reason for this to be happening.

Very weird.

Thanks,
Dave

**Comment by dnovick** [comment]
So, I went ahead and built clean like I stated above. I'm still seeing the same behavior. 

This is very strange. I guess next step is to temporarily disable my TA and app from getting built into the rootfs and see if I still see the problem. I can't imagine why I wouldn't. This almost seems like more of an SD card issue. I'm scratching my head, as I have changed nothing else...and am following the image build process exactly.

Dave

**Comment by igoropaniuk** [comment]
Hi Dave,

It will be good if you share your actual console output you receive on your display (at least last 2-3 lines you see) , because I can't help you me with anything based only on description you provided.

Regards,
Igor

**Comment by dnovick** [comment]
Unfortunately, since I boot with HDMI, I can neither copy the output or even scroll up to see all of it.

BTW, I just confirmed that I'm now seeing the same behavior when I remove my TA and client, with the slight difference that I don't see the "2" printed first. This of course makes sense, as neither one is loaded on boot. Given that, it seems that something has either gone awry with my image building or my build itself. I was very careful when I updated the Makefile and common.mk with my TA and client (which I organized exactly like the hello_world example to make things easy), to not touch anything I shouldn't. 

So, I am at least looking at the output I can see for anything significant. If there is something particular you are looking for? Here are a few things of note:

optee firmware: optee: initialized driver
...
mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
EXT4-fs (mmcblk0p2): couldn't mount as ext3 due to feature compatibilities
mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
EXT4-fs (mmcblk0p2): couldn't mount as ext2 due to feature compatibilities
mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
...
mmc1: new high speed SDIO card at address 0001
EXT4-fs (mmcblk0p2): recovery complete
EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
VFS: Mounted root (ext4 filesystem) on device 179:2.

I'm not sure if that's what is supposed to happen...but it looks suspicious to me.

After this, USB probing is performed, followed by network bring up...running rc.d services....starting telnetd, starting tee-supplicant....and then detecting my net device as well as USB devices, including my keyboard.

After that...it just sits there. Usually, I hit enter and get a shell prompt...but no longer.

I'm going to do another repo sync of the RPI3 environment in a different dir and then diff the Makefile and common.mk with mine...just in case I brought this upon myself.

Help?
Thanks,
Dave

**Comment by dnovick** [comment]
OK....So, I just pulled a fresh version of rpi3_stable....and diffed everything in the top level build dir, especially Makefile and common.mk (those were the ones I changed)....and I can confirm that nothing is different besides my specific TA and app changes - which are temporarily commented out.

So...what is going wrong with boot?

Dave

**Comment by dnovick** [comment]
I'm wondering if the following is my problem:

In order to use HDMI, I followed the instructions on another post (https://github.com/OP-TEE/optee_os/issues/1367). One of the things that is required is that you substitute the uboot.env on your SD card boot partition. When I went and build with my TA and app, I did a clean first....and never repeated the uboot specific steps. I checked, and my uboot.env.txt still has ttyconsole=tty0, but I didn't copy the updated uboot.env over to my SD card's boot partition. Do I need to do this each time I build...and if so, might this be my issue? 

I'm going to try now...but figured I'd ask too.

Dave

**Comment by dnovick** [comment]
So, I went ahead and also checked that the inittab ttyS0 -> tty0 changes were maintained after my clean...and they weren't. I suspect this is my problem. I'll give it a try...and if it works, I'll post here and close the issue.

Dave

**Comment by dnovick** [comment]
Problem solved. I don't think the problem was the uboot.env config, as this appeared to survive a clean. However, the inittab change wasn't preserved, and of course this line is responsible for initializing the default shell on the console. 

So, this was my bad. I'm very sorry for wasting this forum's time on a self inflicted issue. I should have caught this earlier. 


Thanks,
Dave
