### ISSUE TITLE
Can TA thread obtain persistent memory in TEE?

### ISSUE THREAD

**Issue by Kailiangying** [OP-TEE/optee_os#1514]
Is there a way for TA to gain a persistent memory after the command finish? For example, the TA cache some variable in TEE memory for the first invocation and access the same variable for the second invocation.

So far, I am saving the content in the trust storage. For performance reason, I want to see is there any memory storage I can use to optimize the storage performance. 

Thanks for any advise

**Comment by jenswi-linaro** [comment]
Allocate some memory with `TEE_Malloc()` and store the pointer in some global variable. Note that single-instance and multi-instance matters in this case.

**Comment by Kailiangying** [comment]
@jenswi-linaro thanks for your response. I can only allocate one block of persistent memory?

**Comment by jenswi-linaro** [comment]
This isn't persistent memory, this is volatile memory that will be recycled when the TA shuts down.

**Comment by jenswi-linaro** [comment]
Perhaps it would make sense to cache the content of a secure storage object in memory using this memory.

**Comment by Kailiangying** [comment]
Thanks
