### ISSUE TITLE
Networking in normal world

### ISSUE THREAD

**Issue by JossMarley** [OP-TEE/optee_os#1521]
Hi,
how can I configure qemu and my host system in order to have internet access in the normal world?

**Comment by vchong** [comment]
Is https://github.com/OP-TEE/build/blob/master/docs/qemu.md#5-slirp-user-networking what you're looking for?

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
