### ISSUE TITLE
TEE_Mem vs mem related functions

### ISSUE THREAD

**Issue by ggao-inven** [OP-TEE/optee_os#1522]
Hi,
  I have some questions about the memory related functions such TEE_MemMove TEE_MemAlloc. It was supposed to be used by TA(trusted applicaiton). However, OPTEE  provided libutils that has memcpy, malloc and free, etc. Are they using the same HEAP memory? Which function shall I use when I want to use the memory functions?
  The problem is that some 3rd party lib uses memcpy, malloc and free. I am not sure that these functions going to any where. 
   Thanks.

Best

Ge Gao

**Comment by jforissier** [comment]
Hi @ggao-inven ,

The GP functions are implemented using the POSIX ones, so there should be no problem.

**Comment by ggao-inven** [comment]
From the description of OPTEE, the TA is supposed to use the HEAP memory, which uses the GP function, while the kernel is supposed to use memcpy, malloc functions. When TA is using memcpy, malloc function, what memory are they using? Are they still using the HEAP memory?

Thanks.

Ge

**Comment by ggao-inven** [comment]
I read the code and found that TEE_MemXXX is actually calling libutils functions. It causes a crash in my code. I am using 2.4.0 release of OPTEE.
Here is the crash information:
------------------------------------------------------------------------------------
assertion 'b->bh.bsize < 0' failed at lib/libutils/isoc/bget.c:868 in brel()
TA panicked with code 0xffff0000 user_sp 0x0 usr_lr 0x0.
-------------------------------------------------------------------------
The crash happens in a third party closed source lib. That is why I can't see what is exactly the problem. It seems to be the memory release problem. Could you help take a look?

Thanks.

Best

Ge

**Comment by ggao-inven** [comment]
I read the code and found that TEE_MemXXX is actually calling libutils functions. It causes a crash in my code. I am using 2.4.0 release of OPTEE.
Here is the crash information:

assertion 'b->bh.bsize < 0' failed at lib/libutils/isoc/bget.c:868 in brel()
TA panicked with code 0xffff0000 user_sp 0x0 usr_lr 0x0.

The crash happens in a third party closed source lib. That is why I can't see what is exactly the problem. It seems to be the memory release problem. Could you help take a look?

Thanks.

Best

**Comment by doanquangviet** [comment]
I got the same error:

`assertion 'b->bh.bsize < 0' failed at lib/libutils/isoc/bget.c:868 in brel()`

The reason:
- allocate with TEE_Malloc and release with free.

After I change all to malloc/memset/realloc/free  OR TEE_Malloc/TEE_Memset/TEE_Realloc/TEE_Free-> It is FIXED.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.

**Comment by Christian56** [comment]
Hi I got the same issue, 
```
E/TC:0 0 brel:880 brel::bsize=-80 
with theE/TA:  assertion 'b->bh.bsize < 0' failed at lib/libutils/isoc/bget.c:879 in brel()
```
With the current version of bget there is no longer any TEE_* function used

**Comment by jenswi-linaro** [comment]
The solution was to be applied to the TA, not bget. By the way, this error can occur if you're writing outside an allocated buffer too.
