### ISSUE TITLE
Shared memory size bigger than 1MB

### ISSUE THREAD

**Issue by jeffy1009** [OP-TEE/optee_os#1523]
Hello,

Can anybody help me how to use shared memory size bigger than 1MB?
I increased CFG_PUB_RAM_SIZE, but OPTEE complains N page tables not available.

Thanks,

**Comment by etienne-lms** [comment]
Hello,
You should be able to set the shared memory to any size, assuming the shared memory pool is at least 4KByte page aligned.
Could you show the exact error trace you get ? (If no explicit trace, please try `CFG_TEE_CORE_DEBUG=y` and`CFG_TEE_CORE_LOG_LEVEL=4`).

**Comment by jeffy1009** [comment]
```
DEBUG:   [0x0] TEE-CORE:tee_ta_init_static_ta_session:160:    Lookup for Static TA 1111a200-2450-11e4-abe2-0002a5d5c51b
DEBUG:   [0x0] TEE-CORE:init_session_with_signed_ta:775:    Load dynamic TA
DEBUG:   [0x0] TEE-CORE:ta_load:506: Loaded TA at 0x8e100000
DEBUG:   [0x0] TEE-CORE:ta_load:507: ELF load address 0x101000
DEBUG:   [0x0] TEE-CORE:init_session_with_signed_ta:781:       dyn TA : 1111a200-2450-11e4-abe2-0002a5d5c51b
FLOW:    [0x0] TEE-CORE:trace_syscall:144: syscall #1 (syscall_log)
DEBUG:   USER-TA: tee_user_mem_alloc:343: Allocate: link:[0x111b98], buf:[0x111ba8:16]
FLOW:    [0x0] TEE-CORE:trace_syscall:144: syscall #1 (syscall_log)
ERROR:   TEE-CORE: 5 page tables not available
DEBUG:   [0x0] TEE-CORE:tee_ta_invoke_command:568:   => Error: ffff000c of 3
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:318: tee_ta_close_session(0x8e057f78)
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:337:    ... Destroy session
FLOW:    [0x0] TEE-CORE:trace_syscall:144: syscall #1 (syscall_log)
DEBUG:   USER-TA:TA_CloseSessionEntryPoint:94: Goodbye!
FLOW:    [0x0] TEE-CORE:trace_syscall:144: syscall #1 (syscall_log)
DEBUG:   USER-TA: tee_user_mem_free:442: Free: link:[0x111b98], buf:[0x111ba8:16]
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:358:    ... Destroy TA ctx
```

I think using more than 4MB shared memory in total is causing error. 
Note that CFG_SMALL_PAGE_USER_TA is set in my platform.

Relevant code:
```{c}
#ifdef CFG_SMALL_PAGE_USER_TA
static TEE_Result check_pgt_avail(vaddr_t base, vaddr_t end)
{
        vaddr_t b = ROUNDDOWN(base, CORE_MMU_PGDIR_SIZE);
        vaddr_t e = ROUNDUP(end, CORE_MMU_PGDIR_SIZE);
        size_t ntbl = (e - b) >> CORE_MMU_PGDIR_SHIFT;

        if (!pgt_check_avail(ntbl)) {
                EMSG("%zu page tables not available", ntbl);
                return TEE_ERROR_OUT_OF_MEMORY;
        }
        return TEE_SUCCESS;
}
```

**Comment by jenswi-linaro** [comment]
So `PGT_CACHE_SIZE` needs to be increased in some way.

**Comment by jeffy1009** [comment]
`#define PGT_CACHE_SIZE  ROUNDUP(CFG_NUM_THREADS * 2, PGT_NUM_PGT_PER_PAGE)`

I increased `PGT_NUM_PGT_PER_PAGE` and it works fine.

I guess I was a little afraid to change the macro definition.

I still wonder if it won't have any side effects, though.

Thank you for the attention!

**Comment by etienne-lms** [comment]
True that the current setting of `PGT_CACHE_SIZE` does match the default 2MByte SHM defined by the supported platforms.

@jenswi-linaro: do you think we should allow platform to define a default value for `PGT_CACHE_SIZE` ? or should we size it so that at least almost the full SHM can be used as a TA invocation (based on `CFG_SHMEM_SIZE` from platform_config.h) ? With coming registered shm we may face again such issue. 

Maybe a more explicit trace should be enough for users to handle such issue.

@jeffy1009 : no do not increase `PGT_NUM_PGT_PER_PAGE` which has a specific meaning. Rather force a numerical value for `PGT_CACHE_SIZE` or increase `CFG_NUM_THREADS` .

**Comment by jeffy1009** [comment]
`#define PGT_CACHE_SIZE  ROUNDUP(CFG_NUM_THREADS * 3, PGT_NUM_PGT_PER_PAGE)`

Okay, I changed the multiplier for `CFG_NUM_THREADS`.

May I ask what is the meaning for `CFG_NUM_THREADS` ?  

`# How many threads are enabled in TEE core`

Does it limit the number of User TA threads? (If the host code create more than `CFG_NUM_THREADS` and each thread calls a TA, Only `CFG_NUM_THREADS` will be run simultaneously?

**Comment by jenswi-linaro** [comment]
@etienne-lms, I agree there should be some means for platforms to control `PGT_CACHE_SIZE`, exactly how isn't clear to me right now.

@jeffy1009, yes `CFG_NUM_THREADS` works as you describe it.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
