### ISSUE TITLE
Being able to read SW memory from NW through '/dev/mem'.

### ISSUE THREAD

**Issue by cubarco** [OP-TEE/optee_os#1528]
I am testing this on Qemu.
I insert the code below to the function `invoke_command` in core/arch/arm/sta/sta_self_tests.c.
```c
static TEE_Result invoke_command(void *pSessionContext __unused,
                uint32_t nCommandID, uint32_t nParamTypes,
                TEE_Param pParams[TEE_NUM_PARAMS])
{
    char *pa_sw, *va_sw;
    va_sw = malloc(0x1000);
    pa_sw = (void*)virt_to_phys(va_sw);
    DMSG("pa_sw: %p, va_sw: %p", pa_sw, va_sw);
    va_sw[0] = '\xde';
    va_sw[1] = '\xad';
    va_sw[2] = '\xbe';
    va_sw[3] = '\xef';

    ...
}
```
The output `pa_sw` is something like `0x7dfxxxxx`(say 0x7df5ef18).
And then I tried to access to that physical address(0x7df5ef18) from Normal world through `/dev/mem` and I read `0xdeadbeef` as I set in `sta_self_tests.c`.

I'm so confused. Why is that possible to access to `TZ_RAM` from NW?
My assumption is that the memory alloced from `malloc` is not in the secure memory area. Am I correct?

**Comment by igoropaniuk** [comment]
Hi @cubarco, 

QEMU isn't considered as a secure platform. It is mostly used just to lower barriers to enter TEE development (as it's possible to develop trusted application working only on a local pc without acquiring additional hardware), but it doesn't have all needed infrastructure to fully support ARM TrustZone technology. There was a fork of QEMU (https://git.linaro.org/virtualization/qemu-tz.git), where initial support of memory securing was added (TrustZone Address Space Controller (TZC-380), TrustZone™ Protection Controller (BP147) emulation), but, if I'm right, it wasn't upstreamed to the QEMU mainline. 

For additional details you can check https://www.linaro.org/blog/core-dump/arm-trustzone-qemu/

Hope it helps
BR,
Igor

**Comment by cubarco** [comment]
@igoropaniuk Thanks for you reply. It helps a lot.
