### ISSUE TITLE
Uboot + optee Is this possible?

### ISSUE THREAD

**Issue by yym-hjr** [OP-TEE/optee_os#1529]
Hello everyone
I want to use uboot initialization trustzone based armv8.I found arm64 bit, based on armv8 architecture, the basic use of atf to initialize and start. Due to the limitations of the platform, I would like to give up ATF to use the most primitive way to Uboot to drive the trustzone and adapt optee.
Looking forward to your reply!!!

**Comment by jenswi-linaro** [comment]
Hi,

One difference with ARMv8-A is that OP-TEE doesn't take over the complete secure world only secure EL1/EL0. EL3 still has to be managed by some other firmware. If you're skipping ARM-TF you'll need to keep that in u-boot instead, for instance the OP-TEE dispatcher and PSCI.

The `RESET_TO_BL31` compile flag for ARM-TF may be of interest to you. I don't know much about it myself, but I've stumbled on it from time to time. See  https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/reset-design.md

**Comment by yym-hjr** [comment]
Thank you very much for your answer. 
Do you mean to adopt this model?
Proprietary Boot ROM -> Proprietary  firmware -> ATF BL31-> optee -> U-Boot -> Linux

**Comment by jenswi-linaro** [comment]
Yes, something like that could be an option.
If you plan to work much with secure world (or if your fail-safe update is based on u-boot) you could even do it like this:
Proprietary Boot ROM -> Proprietary firmware ->  U-Boot -> ATF BL31-> optee -> [U-Boot ->] Linux

**Comment by yym-hjr** [comment]
Thank you very much for your answer.
According to my way, is to retain only ATF BL31, behind the uboot only used to load linux. And you in front of ATF BL31 also mentioned a U-Boot, you mean to let u-boot to play as BL1 and BL2 function? The second problem is that I found ATF BL1, BL2, BL3, part of the function Is it repeated, I discarded BL1 and BL2 so there is no Trusted boot board, which is allowed?
Looking forward to your reply! Best wishes to you!

**Comment by jenswi-linaro** [comment]
Allowed by who? BL1, BL2 etc are as I see it examples and recommendations. How you implement the boot in the end is up to you.

Regarding U-boot before ARM-TF BL31, something has to load the other binaries because BL31 will not.

**Comment by yym-hjr** [comment]
Trusted boot board is necessary?

**Comment by jenswi-linaro** [comment]
It depends on what's the purpose. If it's to be used only for development I guess it would make sense to have it at optional or even skip it.

**Comment by yym-hjr** [comment]
Thank you very much for your answer.   Best wishes to you!
