### ISSUE TITLE
How to set the CPU affinity of Secure OS for Juno r1?

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#1540]
Hi experts,

I'm using the Juno r1 board with OPTEE released normal OS + secure OS.

After some tests, I find that every time when the Client Application (CA) calls the function of a Trusted Application (TA), the secure OS is just running on the same core as the CA.

So it's like when CA is on core 0 and it's calling secure function via **_smc_**, then the TA would run core 0  too.

I'm wondering is there anyway to set CPU affinity of the secure OS so no matter on which core the smc is generated, the secure OS could always be fixed on the core I need like core 2?

I think this issue should be related to the trusted firmware design such as the function [opteed_smc_handler](https://github.com/linaro-swg/arm-trusted-firmware/blob/optee_paged_armtf_v1.2/services/spd/opteed/opteed_main.c#L333). However, after reading some documents and code, I cannot find the place the set this affinity.

Thank you in advance.

Simon

**Comment by jenswi-linaro** [comment]
Eventual affinity is the responsibility of normal world, select it before doing the SMC and you should be done.

**Comment by SimonWan** [comment]
@jenswi-linaro thank you. However, I'm wondering is that possible for me to fix the secure world CPU affinity from secure level (S-EL1, EL3 etc.) instead of assigning this job to the normal world?

**Comment by jenswi-linaro** [comment]
It's technically possible, but I wouldn't recommend it. It would involve juggling with SGI:s in order to trap the right CPU in secure world and then you'd need some way to communicate back when this CPU is done with its job.
 
Why would you want such a complicated solution instead of using the infrastructure that is already available in normal world?

**Comment by SimonWan** [comment]
@jenswi-linaro I'm  trying to developing a security research tool in secure world that is working for detecting rootkit of normal world. I hope the tool could run even if the normal world OS is corrupted so it would be better if I can set the CPU affinity of this tool without relying on normal world activity.

**Comment by igoropaniuk** [comment]
Hi @SimonWan,

I'm not sure I understand what you are trying to achieve by specifying affinity, and, to my mind, if you don't what to rely on normal world and the main purpose of your tool is going to be detection of linux kernel is legitimate, I suggest to check how TIMA PKM (Periodic Kernel Measurement) works on Samsung KNOX-enabled devices. There is no much public information (as Samsung Mobicore OS is proprietary TEE implementation), but at least there are couple of docs that describe how it works (for example,
 [this one](https://arxiv.org/pdf/1605.08567.pdf)) so you can obtain some ideas about possible details of it's implementation (for example, based on description, TIMA PKM component code is invoked by secure timer interrupt handler,  and not from smc call from NW)

Maybe it's a bit off-topic information, but I hope it could help somehow

Best regards,
Igor

**Comment by igoropaniuk** [comment]
@SimonWan @etienne-lms 
Hah, just found the same suggestions about the secure interrupt handler from @etienne-lms (https://github.com/OP-TEE/optee_os/issues/1541#issuecomment-301918160). Seems that I'm a bit late with an answer

Anyway, check this doc, there is a lot information which can help you

**Comment by SimonWan** [comment]
@igoropaniuk thanks for the document link! I read some TIMA PKM information before but it's good for me to know that secure timer is a possible solution. I'll close this issue right now and reopen it if I still got some problem, have a good one!
