### ISSUE TITLE
ARM trusted firmware hangs with 32 bit builds of OP-TEE on RPI3

### ISSUE THREAD

**Issue by dnovick** [OP-TEE/optee_os#1545]
This is a new thread to focus on what I have determined thus far regarding the issue that I encountered with 32 bit builds of OP-TEE on RPI3. 

After successfully building op-tee as 32 bit, my host and ta both worked fine. I then proceeded to build clean. Ever since then, my device will not boot. It hangs in the arm trusted firmware, within the function opteed_synchronous_sp_entry(), more specifically within the ASM function opteed_enter_sp(). 

One curiosity I noticed is that opteed_enter_sp() is 64 bit ASM. I'm not sure what the assembler is supposed to do when it encounters 64 bit asm in a 32 bit build...but I thought it worth mentioning.

What is most curious to me is that everything was working until I did a clean build. I have since tried other RPI3s, other SD cards, and even rebuilt my entire dev environment. So far, nothing works.

Please note that this happens on both the stable branch as well as the tip.

Does anybody have any idea what could be going on? 

Thanks,
Dave

**Comment by jforissier** [comment]
EL3 runs in Aarch64 state, hence A64 instructions, no matter which state is used for SEL1 (Aarch64 with A64 instructions or Aarch32 with A32 or T32 instructions).
[Here, EL3 is ARM-TF BL31 and SEL1 is OP-TEE].

**Comment by dnovick** [comment]
Yeah...I figured that out after posting this. So, any ideas why 32 bit OP-TEE boots aren't working on the RPI3? Is there any way to workaround this, so I can at least get back to a stable state?

Dave

**Comment by vchong** [comment]
Providing detailed descriptions of each step/instructions/commands you took/used from the very beginning to the point where the problem manifest will make it easier for the maintainers and others to try to help you, i.e. steps to reproduce is best.

**Comment by igoropaniuk** [comment]
Hi @dnovick 
Regarding 32-bit builds for RPi3 https://github.com/OP-TEE/optee_os/issues/1526#issuecomment-302396228

**Comment by dnovick** [comment]
Steps to reproduce are straightforward. Starting with a clean environment and a fresh pull of the code based on rpi3.xml or rpi3_stable.xml:

- Change the build/Makefile entries override COMPILE_S_USER and COMPILE_S_KERNEL to 32.
- Within the build dir, perform a make all. This succeeds
- Build the SD card image according to the instructions found by executing make img-help.
- Move the SD card to the RPI3. 
- Power up.

The failure is immediately evident. Note: If I build and boot 64 bit secure world, the device boots just fine.

As mentioned previously, my first build with 32 bit secure world actually worked. This was last Friday AM. After doing a rebuild, I encountered the described behavior. This is when I went and created a brand new environment (Linux VM, dev tools, etc.). I've continued to see the same failures with 32 bit secure world, and success with 64 bit secure world. Unfortunately, I cannot use 64 bit builds for my project.

Dave

**Comment by dnovick** [comment]
I should have closed this post earlier as this was resolved on another thread. The problem was that I was trying to run 32 bit secure world for both kernel and user space. Apparently, 32 bit kernel mode is no longer supported. However, running 64 bit kernel mode and 32 bit user mode in the secure world does work fine.

Dave
