### ISSUE TITLE
Which function (loads and) verifies the RSA-encrypted signature of TA?

### ISSUE THREAD

**Issue by hypersimple** [OP-TEE/optee_os#1546]
And where is the RSA-encrypted signature located in the TA? 
Header, or end of the ELF(MCLF?) file?
Thanks.

**Comment by jforissier** [comment]
Header. See https://github.com/OP-TEE/optee_os/blob/master/scripts/sign.py.
In fact a `.ta` file is a signed header followed by an ELF file.

**Comment by hypersimple** [comment]
Thanks for the quick reply.
In OP-TEE (C code), which function (loads and) verifies the RSA-encrypted signature of TA?

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/ree_fs_ta.c#L78-L124
