### ISSUE TITLE
How to import Openssl into op-tee

### ISSUE THREAD

**Issue by ConsoleLin** [OP-TEE/optee_os#1553]
Hi everyone:
       I just started learning op-tee, and now I have encountered a problem, for some reason I need to use the openssl library in op-tee, but every time i want to import openssl it will show that no openssl header files was found.So i would like to ask someone to help me solve the problem!
      Thanks!

**Comment by ConsoleLin** [comment]
Thank you everyone!

**Comment by yuhsien-chen** [comment]
Hi @ConsoleLin 

You can refer to this.
https://github.com/OP-TEE/optee_os/issues/340

Good Luck!

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
