### ISSUE TITLE
xtest 1006 fail when CFG_SMALL_PAGE_USER_TA=n

### ISSUE THREAD

**Issue by zhupg** [OP-TEE/optee_os#1554]
Hi,
  On the latest version, xtest 1006 will fail when CFG_SMALL_PAGE_USER_TA=n. I remember xtest 1006 can pass with this configuration on version 2.2.
  Details:
  Platform: FVP
  Position: [optee_test/ta/os_test/os_test.c : 438](https://github.com/OP-TEE/optee_test/blob/master/ta/os_test/os_test.c)
```
    res = TEE_CheckMemoryAccessRights(TEE_MEMORY_ACCESS_WRITE,                   
          (void *)&test_uuid, sizeof(test_uuid));                    
    if (res == TEE_SUCCESS)                                                         
        return TEE_ERROR_GENERIC;
```
  Please help to check why? thank you.

**Comment by jenswi-linaro** [comment]
The problem is that we check if the address is writable or not based on how the address is actually mapped. With `CFG_SMALL_PAGE_USER_TA=n` what could have been read-only becomes read-write as the variables will have to be mapped with the same attributes.

**Comment by zhupg** [comment]
Thanks, got it.

**Comment by jenswi-linaro** [comment]
@zhupg , by the way, do you have a special use-case where you need to configure with `CFG_SMALL_PAGE_USER_TA=n`.

We're currently considering removing `CFG_SMALL_PAGE_USER_TA=n`.
