### ISSUE TITLE
readelf warning trace on some paged core builds

### ISSUE THREAD

**Issue by etienne-lms** [OP-TEE/optee_os#1560]
When building optee_os core with specific configuration directives, the build displays some warning traces, i.e:
> (...)
> readelf: Warning: Corrupt ARM compact model table entry: e1910f9f 
> readelf: Warning: Unknown ARM compact model index encountered
> (...)
> readelf: Warning: Corrupt ARM compact model table entry: e12fff1e 
> readelf: Warning: Unknown ARM compact model index encountered
> (...)

These traces come from the readelf parsing of generated **unpaged.o** used to retrieve all unpaged resources. Hence, the issue is related configuration where pager is enabled. So far, this issue seems harmless :) but the linker message remains.

Can be reproduced on qemu_virt:
    `make PLATFORM=vexpress-qemu_virt CFG_WITH_PAGER=y CFG_TEE_CORE_DEBUG=y`
Strangely, when using  `CFG_TEE_CORE_DEBUG=n`, the warning trace is not logged.

See also the travis build log, i.e this one from a merged P-R: https://travis-ci.org/OP-TEE/optee_os/builds/233988404#L1963.

This issue was already reported by @MrVan : https://github.com/OP-TEE/optee_os/issues/1193.

**Comment by jbech-linaro** [comment]
@etienne-lms status? keep the issue open?

**Comment by etienne-lms** [comment]
Fixed in current mainline.
Closing.
