### ISSUE TITLE
Lost wlan0 device after installing OP-TEE kernel on hikey

### ISSUE THREAD

**Issue by nikoskoutr** [OP-TEE/optee_os#1567]
Hello,
I have followed every step on the build instructions and after i run this and reboot:
`dpkg --force-all -i /tmp/linux-image-*.deb`

I loose the wlan0 device, it is not listed anywhere.
Thanks for any help,
-Nick

**Comment by vchong** [comment]
The kernel is a minimal/barebone one as of right now, with enough support to run xtest and perhaps lacking drivers to do certain things. We're trying to find time to work on this, hopefully soon. Apologies and thank you for your patience!

**Comment by nikoskoutr** [comment]
Ok, thank you a lot!

**Comment by vchong** [comment]
If you're still interested, the hikey_debian build has recently been updated. Note that this is however an non-gui build only. To enable wifi, see https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L448.

**Comment by nikoskoutr** [comment]
Hello,
I have recently tried using the CA/TA application that I am building without installing the linux image with
`dpkg --force-all -i /tmp/linux-image-*.deb`
Everything runs as expected, is that normal?
@vchong I will try the new build, thank you a lot !!

**Comment by vchong** [comment]
You're welcome!
If everything runs as expected, that means the kernel in the rootfs supports OP-TEE enough to do what you need. If that's the case, and you don't care about the kernel, i.e. you're not doing any kernel-related development, then you don't have to dpkg install the linux image.
