### ISSUE TITLE
REE FS tree

### ISSUE THREAD

**Issue by ppeiffer** [OP-TEE/optee_os#1571]
Hi,

In the doc included in optee-os, I can read (file documentation/secure_storage.md) that the persistent object are stored in Linux FS using a tree like /data/tee/<ta-uuid>/<obj_id>

But when looking on linux FS, I see this:
```
$ ls -l /data/tee
total 2768
-rw------- 1 root  root   16384 1970-01-01 00:00 0
-rw------- 1 root  root   16384 1970-01-01 00:00 1
-rw------- 1 root  root  503808 1970-01-01 00:04 2
-rw------- 1 root  root   16384 1970-01-01 00:04 3
-rw------- 1 root  root  557056 1970-01-01 00:04 4
-rw------- 1 root  root   16384 1970-01-01 00:04 5
-rw------- 1 root  root   16384 1970-01-01 00:03 6
-rw------- 1 root  root  479232 1970-01-01 00:04 7
-rw------- 1 root  root  479232 1970-01-01 00:03 8
-rw------- 1 root  root   16384 1970-01-01 00:03 9
-rw------- 1 root  root   16384 1970-01-01 00:04 b
-rw------- 1 root  root  495616 1970-01-01 00:03 c
-rw------- 1 root  root   16384 1970-01-01 00:04 dirf.db
drwxrwxr-x 2 shell shell   4096 1970-01-01 00:00 optee_armtz

```
I didn't check in the code, but what am I missing ? (I'm using REE_FS for storage type, of course))

P.

**Comment by jenswi-linaro** [comment]
Aha, sorry it seems the documentation isn't entirely up to date.
The translation from `<uuid>/<obj_id>` to those numbers is done in `dirf.db` which also is integrity protected.

**Comment by jforissier** [comment]
Yep, refer to commit: https://github.com/OP-TEE/optee_os/commit/ac0bab7. If I'm not wrong that's when things changed.

**Comment by ppeiffer** [comment]
ok, thanks !

**Comment by ppeiffer** [comment]
One more quick question: with this new scheme, there is no more any way to remove data (objects) belonging to one given TA, right ?

**Comment by jenswi-linaro** [comment]
It should not go unnoticed at least since it's presence is recorded in `dirf.db`.

**Comment by etienne-lms** [comment]
Would this need a support (in some debug mode) for reseting secure storage contents belonging to a given TA ?

**Comment by jenswi-linaro** [comment]
Yes

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
