### ISSUE TITLE
Why need lock_single_instance for single_instance TA?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1576]
Hi 

We have already got the ctx->busy,and for the  lock_single_instance, if we have 2 single_instance TAs, we can't access them in parallel, could anyone help to explain?
Thanks.

**Comment by jenswi-linaro** [comment]
It's a way of guaranteeing that we can't deadlock. Single instance TAs can form lock graphs that could lead to deadlocks. I suppose there's some more advanced way we can detect this, but the advantage with this somewhat blunt approach is that  the we always have the same behavior regardless of which other TAs are active etc.

**Comment by prime-zeng** [comment]
@jenswi-linaro  any detail about the lock graphs? So if i have all TAs set to single instance, the performance will be bad because we can't take advantage of the SMP, right?

**Comment by jenswi-linaro** [comment]
I don't have any more details on the lock graphs. I only realized that something had to be done about potential deadlocks and this works and is predicable.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/1915 added a config option to disable the global lock.
