### ISSUE TITLE
"make toolchains" downloads 64bit tools even for 32bit Ubuntu build machine

### ISSUE THREAD

**Issue by P1119r1m** [OP-TEE/optee_os#1584]
Next steps were successfully executed:

> ## 7.4 Get the toolchains
> In OP-TEE we're using different toolchains for different targets (depends on
> ARMv7-A ARMv8-A 64/32bit solutions). In any case start by downloading the
> toolchains by:
> ```bash
> $ cd build
> $ make toolchains
> ```

but when after that we're trying to build the solution:

> ## 7.5 Build the solution
> We've configured our repo manifests, so that repo will always automatically
> symlink the `Makefile` to the correct device specific makefile, that means that
> you simply start the build by running:
> 
> ```bash
> $ make
> ``` 

process fails, because downloaded tools (like compiler) are for 64bit build platform.

P.S. It fails with following message:

> "/bin/bash: /home/user/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc: cannot execute binary file".

Additional info:

> $ readelf -h /home/user/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc
> ELF Header:
>   Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
>   Class:                             ELF64
>   Data:                              2's complement, little endian
>   Version:                           1 (current)
>   OS/ABI:                            UNIX - System V
>   ABI Version:                       0
>   Type:                              EXEC (Executable file)
>   Machine:                           Advanced Micro Devices X86-64
>   Version:                           0x1
>   Entry point address:               0x40385e
>   Start of program headers:          64 (bytes into file)
>   Start of section headers:          926032 (bytes into file)
>   Flags:                             0x0
>   Size of this header:               64 (bytes)
>   Size of program headers:           56 (bytes)
>   Number of program headers:         10
>   Size of section headers:           64 (bytes)
>   Number of section headers:         30
>   Section header string table index: 29

> $ uname -m
> i686

**Comment by jforissier** [comment]
Hi @P1119r1m,

We assume that pretty much everyone runs a x64 development machine these days so we don't bother with x86 toolchains.

**Comment by P1119r1m** [comment]
I'm sorry, that posted this issue in a wrong repository tree. I've duplicated it in proper place:
https://github.com/OP-TEE/build/issues/153
