### ISSUE TITLE
Meanings of TA FLAGS

### ISSUE THREAD

**Issue by jeffy1009** [OP-TEE/optee_os#1590]
Hello,

Could I ask what the meanings for the following FLAGS are? What are their uses?

`TA_FLAG_USER_MODE TA_FLAG_EXEC_DDR TA_FLAG_SINGLE_INSTANCE TA_FLAG_MULTI_SESSION TA_FLAG_INSTANCE_KEEP_ALIVE`

Is there some document that explains this? I couldn't find any.

Thank you.

**Comment by jeffy1009** [comment]
I'm asking this because I want to leave TA loaded in TA RAM once it is loaded.
So I used `TA_FLAG_INSTANCE_KEEP_ALIVE`, but I found that if I don't use `TA_FLAG_SINGLE_INSTANCE`, OP-TEE anyways creates new TA instance.

I have one TA and I want to run multiple threads calling the same TA. There are no data sharing between the threads.

Will it be okay to just set the two flags for this purpose? `TA_FLAG_INSTANCE_KEEP_ALIVE` and `TA_FLAG_SINGLE_INSTANCE`?

**Comment by jforissier** [comment]
Hi @jeffy1009, 
- `TA_FLAG_SINGLE_INSTANCE`, `TA_FLAG_MULTI_SESSION` and `TA_FLAG_INSTANCE_KEEP_ALIVE` correspond to the "Single instance", "Multi session" and "Keep alive" properties defined in the GlobalPlatform Internal Core API Specification v1.1. See sections 2.1.6 "Instance Types" and 4.5 "Trusted Application Configuration Properties".
- `TA_FLAG_USER_MODE` means that the TA should be executed in user mode (Secure EL0 / Secure PL0), while `TA_FLAG_EXEC_DDR` means that the TA should run in (secure) dynamic RAM. Currently, these flags must always be set or the TA won't load. I'm ignoring them in the description below, but please don't forget to add them.

Basically you have 2 options:
- If you really want the TA to remain loaded always, then you set (TA_FLAG_SINGLE_INSTANCE | TA_FLAG_INSTANCE_KEEP_ALIVE | TA_FLAG_MULTI_SESSION). You will be able to run multiple threads calling the TA, although they will be serialized (so possible performance bottleneck). If you don't set TA_FLAG_MULTI_SESSION, then you can't have several clients with valid sessions simultaneously (one client must wait for another client to close its session before it can open its own).
- If you want better performance and are willing to drop the "remain loaded" requirement, then you set no flag. With this setup, several threads can run in your TA concurrently using different sessions. One instance is loaded per session. When a session ends, the corresponding TA instance is unloaded.
- Note that TA_FLAG_INSTANCE_KEEP_ALIVE without TA_FLAG_SINGLE_INSTANCE is ignored.
- Note also that:
  - Concurrent execution requires !TA_FLAG_SINGLE_INSTANCE
  - TA_FLAG_MULTI_SESSION is meaningful only with TA_FLAG_SINGLE_INSTANCE
  - TA_FLAG_MULTI_SESSION does *not* imply concurrent execution of commands. Sessions coexist but invokes are serialized.

> Will it be okay to just set the two flags for this purpose? TA_FLAG_INSTANCE_KEEP_ALIVE and TA_FLAG_SINGLE_INSTANCE?

Yes, it is valid, but as I said above, several threads won't be able to enter the TA concurrently. Use one session per thread and set TA_FLAG_MULTI_SESSION if you need concurrency.

**Comment by jeffy1009** [comment]
> If you want better performance and are willing to drop the "remain loaded" requirement, then you set no flag. With this setup, several threads can run in your TA concurrently using different sessions. One instance is loaded per session. When a session ends, the corresponding TA instance is unloaded.

> TA_FLAG_MULTI_SESSION is meaningful only with TA_FLAG_SINGLE_INSTANCE

>Use one session per thread and set TA_FLAG_MULTI_SESSION if you need concurrency.

It is a little confusing, but in conclusion, I need to set `TA_FLAG_SINGLE_INSTANCE` and `TA_FLAG_MULTI_SESSION`, and no `TA_FLAG_INSTANCE_KEEP_ALIVE`. Right?

I definitely need the concurrent execution.

One thing I'm worried is the comment on `rpc_load` function in `core/arch/arm/kernel/user_ta.c` that says the function is not thread safe.

(I'm using OP-TEE version 2.3.0 )

**Comment by jforissier** [comment]
> I definitely need the concurrent execution.

Try `#define TA_FLAGS (TA_FLAG_USER_MODE | TA_FLAG_EXEC_DDR)`.

> One thing I'm worried is the comment on rpc_load function in `core/arch/arm/kernel/user_ta.c` that says the function is not thread safe.

IMO that comment is obsolete but I might be missing something.

**Comment by etienne-lms** [comment]
Hi,

`TA_FLAG_USER_MODE` and `TA_FLAG_EXEC_DDR` are asserted in the core but quite useless as not alternative is supported. Libutee enforces `TA_FLAG_USER_MODE` but not `TA_FLAG_EXEC_DDR` so all TAs must at least add `TA_FLAG_EXEC_DDR` to its `TA_FLAGS` macro. I setup a patch proposal for this:
```patch
--- a/ta/arch/arm/user_ta_header.c
+++ b/ta/arch/arm/user_ta_header.c
@@ -79,6 +79,6 @@ const struct ta_head ta_head __section(".ta_head") = {
 	 */
 	.stack_size = TA_STACK_SIZE + TA_FRAMEWORK_STACK_SIZE,
-	.flags = TA_FLAG_USER_MODE | TA_FLAGS,
+	.flags = TA_FLAG_EXEC_DDR | TA_FLAG_USER_MODE | TA_FLAGS,
 #ifdef __ILP32__
 	/*
 	 * This workaround is neded on 32-bit because it seems we can't
```

**Comment by etienne-lms** [comment]
Here is another overview of the flag properties it case it helps to clarify.
courier are GP TEE Specs (Core API) extracts.


`TA_FLAG_SINGLE_INSTANCE`
- OPTEE expects TA to set this flag in order enable property `gpd.ta.singleInstance` (GP TEE specs).
This must be enabled "`whether the Implementation SHALL create a single TA
instance for all the client sessions (if true) or SHALL
create a separate instance for each client session
(if false).`"
- if enabled, all invocation of the TA will end is the very same instance of the TA.
If disabled, each successful open session request creates a new independent instance of the TA which will be called based in the established session ID.


`TA_FLAG_MULTI_SESSION`
- OPTEE expects TA to set this flag in order enable property `gpd.ta.multiSession` (GP TEE specs).
- It must be enabled "`whether the Trusted Application instance supports multiple sessions`".
- `This property is ignored when gpd.ta.singleinstance is set to false.`
- If enabled, the single instance TA is invoked for all open session requests.
If disabled, If the single instance TA will support 1 opened session at most.

`TA_FLAG_INSTANCE_KEEP_ALIVE`
- OPTEE expect TA to set this flag in order enable property `gpd.ta.keepAlive` (GP TEE specs). 
- It must be enabled "`whether the Trusted Application instance context SHALL
be preserved when there are no sessions connected to the
instance.` (...) `When this property is set to false , then the TA instance
MUST be created when one or more sessions are opened
on the TA and it MUST be destroyed when there are no
more sessions opened on the instance.
When this property is set to true , then the TA instance is
terminated only when the TEE shuts down` (...)"
- `This property is meaningful only when the
gpd.ta.singleInstance is set to true`.
- If enabled then once the TA is loaded, it it never unloaded unless the TEE is rebooted.
  If disabled, once a TA has no more opened session, it is unloaded (execution context destroyed).

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
