### ISSUE TITLE
Shared Memory Mechanism

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1601]
Hi, 

I have been looking through the code all afternoon but just cannot seem to find a SIMPLE shared memory example. Basically I would like to create some shared memory (lets say 100 chars), copy a string into it and then pass it to the TA. In the TA I would just print out what is in the shared memory, then change the contents and finish. 

Thanking you in advance
Ursus

PS: I have looked through the tests (regression) but I cannot see the forest for the trees :o)

**Comment by etienne-lms** [comment]
Hello Ursus,

This code snipped should do the work: a CA (non secure) allocates a shared memory buffer and invokes a TA with a reference to the buffer passed as invocation argument.
```c
{
	TEEC_Result res;
	TEEC_Context ctx;
	TEEC_Session sess;
	TEEC_Operation op;
	TEEC_SharedMemory shm;
	TEEC_UUID uuid = MY_TA_UUID;
	uint32_t origin;

	res = TEEC_InitializeContext(NULL, &ctx);
	/* check return status */

	res = TEEC_OpenSession(&ctx, &sess, &uuid, TEEC_LOGIN_PUBLIC, NULL, NULL, &origin);
	/* check return status */

	shm->buffer = NULL;
	shm->size = 100;
	res = TEEC_AllocateSharedMemory(&ctx, shm);
	/* check return status */

	/* load some data in the buffer */
	memset(shm.buffer, 0, size);

	memset(&op, 0, sizeof(op));
	op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_WHOLE,
					 TEEC_NONE, TEEC_NONE, TEEC_NONE);
	op.params[0].memref.parent = &shm;
	res = TEEC_InvokeCommand(&sess, MY_CMD_TO_MY_TA, &op, &origin);
	/* check return status */

	/* we're done, let's close everything */
	TEEC_ReleaseSharedMemory(&shm);
	TEEC_CloseSession(&sess);
	TEEC_FinalizeContext(&ctx);
}
```

**Comment by ursus-the-bear** [comment]
That is so nice of you - thank you very much. Makes perfect sense now. Do you maybe have something similar for the TA side of things?

**Comment by jforissier** [comment]
@ursus-the-bear yeah the regression tests are definitely not the best reference to learn the basics ;)
You may want to check out the "Hello world" application https://github.com/linaro-swg/hello_world and try to adjust it according to what @etienne-lms proposed. Shouldn't be that hard.

**Comment by ursus-the-bear** [comment]
Hi again Jérôme, we do seem to be speaking often today :o)

I have the hello world example up and running (in my own TA i.e. not just compiling the one in the download) without any problems - the only thing there was that the parameter passed was just an integer (liked the Adams reference :o) and I wanted more of a structure which @etienne-lms gave me. Due to me doing very little C programming was looking for more simple examples than the ones in the tests. 

Thank you again (and @etienne-lms of course) for the help today, it is much appreciated!

**Comment by ursus-the-bear** [comment]
Should anybody else need a place to start here is my code that sends a line of text from the normal world to the secure world using shared memory:

Normal world part: 
`	

    {

    TEEC_Result rc;
	TEEC_Context ctx;
	TEEC_Session sess;
	TEEC_Operation op;
	TEEC_SharedMemory shm;
	TEEC_UUID uuid = FIM_TA_UUID;
	uint32_t err_origin;

	printf ("Version 15.06.2017 - Build 3\n");

	/* Initialize a context connecting us to the TEE */
	rc = TEEC_InitializeContext(NULL, &ctx);
	check_rc (rc, "TEEC_InitializeContext", NULL);

	// open a session to the TA
	rc = TEEC_OpenSession(&ctx, &sess, &uuid, TEEC_LOGIN_PUBLIC, NULL, NULL, &err_origin);
	check_rc (rc, "TEEC_OpenSession", &err_origin);

      // create the shared memory buffer
	shm.buffer = NULL;
	shm.size = 50;
	shm.flags = TEEC_MEM_INPUT;
	rc = TEEC_AllocateSharedMemory(&ctx, &shm);
	check_rc (rc, "TEEC_AllocateSharedMemory", NULL);

	// clear the buffer
	memset (shm.buffer, 0, shm.size);

      // copy some test data to buffer
	const char src[50] = "this is some text";
	memcpy (shm.buffer, src, strlen(src) + 1);

	/* Clear the TEEC_Operation struct */
	memset(&op, 0, sizeof(op));

	// assign param
	op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_WHOLE, TEEC_NONE, TEEC_NONE, TEEC_NONE);
	op.params[0].memref.parent = &shm;

	printf("Invoking TA with the READ_SHARED_MEMORY command\n");
	rc = TEEC_InvokeCommand(&sess, READ_SHARED_MEMORY, &op, &err_origin);
	check_rc (rc, "TEEC_InvokeCommand", &err_origin);

	// clean up once you have finished
	TEEC_CloseSession(&sess);
	TEEC_FinalizeContext(&ctx);

	// finally finished
	return 0;

    }
`
 the function check_rc does just that, it checks the RC and exits if there is an error:

`   
    {
    // check your return code
    static void check_rc (TEEC_Result rc, const char *errmsg, uint32_t *orig) {

	if (rc != TEEC_SUCCESS) {
		fprintf(stderr, "%s: 0x%08x", msg, rc);
		if (orig)
			fprintf(stderr, " (orig=%d)", (int)*orig);
		fprintf(stderr, "\n");

		exit (1);
	}
    }
`

and finally the part of the secure world (TA) that reads the data

`
    {
	// check the parameters
	uint32_t exp_param_types = TEE_PARAM_TYPES(
			TEE_PARAM_TYPE_MEMREF_INPUT,
			TEE_PARAM_TYPE_NONE,
			TEE_PARAM_TYPE_NONE,
			TEE_PARAM_TYPE_NONE);
      if (param_types != exp_param_types) return TEE_ERROR_BAD_PARAMETERS;

	// message what you received!
	DMSG ("Received: %s", (char *) params[0].memref.buffer);
    }
`

please excuse that the code is not formatted properly but somehow it doesn't work for me! not sure whats going on but anyway...
