### ISSUE TITLE
Creating a TA

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1604]
Hi

I am just starting out writing TA's and am having a couple of problems with the make / build system. 

My setup is that I have optee installed on a VM on my server, I have a SMB connection to the optee directory and SSH into the machine to do the 'make'. I am using ATOM as an editor. To run my code I then go to the desktop on the VM and do a make run-only. Is this the recommended setup? I am missing a IDE which I am used to for things like typeahead, partial compiling and debugging (the last one I am clear that it would be very difficult for the kind of programming we are doing :o)

I have taken the hello_world directory and cloned it (my application is called fim). I then updated the files as best as I knew how.  Finally I went into the 'build' directory and searched for hello_world in the relevant .md files (common.mk, qemu.mk and qemu_v8.mk) and, basically, just copied the lines creating the fim-clean etc. When I do a "make all" everything works correctly.  Doing a 'make fim' just complies my code. I was wondering if this is the correct way to setup my build process? 

thanking you in advance
Ursus

**Comment by jforissier** [comment]
Hi @ursus-the-bear ,

I suppose development environments are a matter of personal preference. The way you're doing is perfectly fine as long as it fits your needs ;)
Regarding IDEs: I use Qt Creator for "serious" development, or vim when I'm just hacking simple things. In Qt Creator I'm really only using the editor, which has the nice features you can expect from such a tool (completion, go to definition, show usage...). I run `make` and `git` in terminal windows.

**Comment by ursus-the-bear** [comment]
Hi @jforissier 

Super - good to hear. 

I am just doing a small TA so I think that setting up Qt would be too much trouble .

Thank you and have a great day
Ursus
