### ISSUE TITLE
Shutdown of SoC from TA

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1609]
Hi

I am checking to see if the normal world has been manipulated from the TA. I have the code up and running and can see if anything is fishy -> yay :o)

I was wondering if there is any way to shutdown the normal world from the TA -> by this I mean it could be a panic, anything really - I would just want to stop the whole system running - a "clean" shutdown would be nice but I would be happy for anything - ideas?

Thanking you in advance
Ursus

**Comment by jforissier** [comment]
Hi,

It is not possible at the moment, but it shouldn't be that hard to implement. What I'm thinking is add a pseudo-TA implementing a "shutdown" command. The pTA would check if it is called by a TA (not a CA), then send some new RPC command to `tee-supplicant` which would trigger the shutdown. This assumes that `tee-supplicant` has enough privileges of course (which might not always be the case, Android may be problematic for instance).

**Comment by ursus-the-bear** [comment]
That sounds very good. Will look into tee-supplicant. Thank you for the info.
