### ISSUE TITLE
Infinite loop in TA would cause system crashed.

### ISSUE THREAD

**Issue by BZH001** [OP-TEE/optee_os#162]
Hi,

I has read the thread part of source code. I find that the thread status almost totally determined by itself. So I find that if I write a infinite loop in TA, all system can't work anymore when running the TA. Because there are no way to stop this TA. I think it would be a serious problem. So I want to know do you have any plan to design some timeout handle for TA? Thanks a lot. 

Best Regards,

**Comment by jenswi-linaro** [comment]
Hi,

We have no immediate plans to handle this. An endless loop in a TA is a DOS attack and TAs are supposed to be signed with a key that you can trust. Terminating a TA before it's done can be dangerous as it could be part of an attack from normal world.

Regards,
Jens

**Comment by BZH001** [comment]
Hi,

Yes, you are right. But as I know that any one can get the UUID of TA if he can see the name its stored. It is possible to design a fake TA, and replace the real one. To avoid it, the sign should be verified before the TA loaded. Do you have plan to added this function?

Best Regards,

**Comment by jbech-linaro** [comment]
Hi,

That question is answered [here](https://wiki.linaro.org/WorkingGroups/Security/OP-TEE#The_Trusted_Applications_doesn.27t_seem_to_be_verified.3F). It's "planned", but there is no date when this will happen.

// Regards Joakim

**Comment by BZH001** [comment]
OK, I got that. Thanks.
