### ISSUE TITLE
Unhandled level 2 translation fault, rpi3 TA error.

### ISSUE THREAD

**Issue by nikoskoutr** [OP-TEE/optee_os#1620]
Hello,
I am trying to transform an application to make it work with TEE.
I have succeeded in doing so, using the hikey board, but when i try to run the same application on rpi3 i am getting the following error:
Edit: I am getting a return error of 0xffffffff and origin 4.

```
[  308.775514] idemix[152]: unhandled level 2 translation fault (11) at 0x00000000, esr 0x92000006
[  308.788563] pgd = ffffffc033a3d000
[  308.796102] [00000000] *pgd=00000000336ec003, *pud=00000000336ec003, *pmd=0000000000000000
[  308.808799] 
[  308.814477] CPU: 3 PID: 152 Comm: idemix Not tainted 4.6.3-17570-g9f38d0f9d4aa #3
[  308.826320] Hardware name: Raspberry Pi 3 Model B (DT)
[  308.835796] task: ffffffc0335f2700 ti: ffffffc0341a4000 task.ti: ffffffc0341a4000
[  308.847672] PC is at 0x40316c
[  308.854923] LR is at 0x403164
[  308.862138] pc : [<000000000040316c>] lr : [<0000000000403164>] pstate: 80000000
[  308.873958] sp : 0000007fcc7e0ed0
[  308.881610] x29: 0000007fcc7e0ed0 x28: 0000000000000000 
[  308.891361] x27: 0000000000000000 x26: 0000000000000000 
[  308.901079] x25: 0000000000000000 x24: 0000000000000000 
[  308.910730] x23: 0000000000000000 x22: 0000000000000000 
[  308.920365] x21: 0000000000401610 x20: 0000000000000000 
[  308.929983] x19: 00000000004053f0 x18: a0481273f1109c7f 
[  308.939527] x17: 0000007f946ce980 x16: 0000007f94a2fc00 
[  308.949070] x15: f366382b87799ada x14: 3405ff695a6473d1 
[  308.958584] x13: 80811047f93879f8 x12: 848d5ddde2ef0f8b 
[  308.968063] x11: 0000000000443010 x10: 0000000000442f10 
[  308.977541] x9 : 0000000000418440 x8 : 00000000004182a8 
[  308.986977] x7 : 0000000000000000 x6 : 0000000000000000 
[  308.996413] x5 : 0000007fcc7e0e58 x4 : 0000000000418290 
[  309.005835] x3 : 0000000000000010 x2 : 0000000000000008 
[  309.015209] x1 : 0000000000000000 x0 : 0000000000000000
```
I have narrowed down that it is happening while in the TA.
As a side note, i have compiled the openssl library that the CA uses, and it seems to work fine.
Unfortunately, the i do not own the code and the owner cannot share it.

I know I don't give enough information, but i am hoping someone can give me the right directions, as i cannot seem to find any material on the matter using the web.

Thank you for your help,
Nick

**Comment by jforissier** [comment]
This is a linux crash dump. The fault is not occurring in secure world (not in the TA). It is the CA that crashes because it it trying to de-reference a NULL pointer. You have the PC so you should be able to find the file/line number easily using `aarch64-linux-gnu-addr2line`. Or use GDB, or add debug traces in you CA.

**Comment by nikoskoutr** [comment]
After following your recommendation, i debugged my application and now it is working fine.
Thank you for all your help!

**Comment by rmdcom** [comment]
Hello, I have the similar issue while porting from atmel board to Linux mpxls1043 aarch64.
Anyone ,please help me on this topic. Even my gdb does not five anyhints.
However i could able to run the Hello world  program with same cross tool build.

![screenshot from 2017-12-28 13-31-59](https://user-images.githubusercontent.com/20185713/34421680-f9941c92-ec10-11e7-9d99-36c57c70a9d1.png)
