### ISSUE TITLE
Trust

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1624]
Hi, 

sorry if this is a stupid question and has been asked 100 times before - somehow I just cannot seem to find the answer here :o(

I was wondering how a TA knows that the optee_os can be trusted? By this I mean if I am, for example, calculating hash values for DRM in the TA from the normal world. How do I know that the TA i.e. the secure world has not been compromised? I would like to "prove" to the client app that I am safe i.e. I have not been somehow compromised. 

Thanking you for any help given
Ursus

**Comment by jforissier** [comment]
TAs are signed, so optee_os can (and does) verify them. See `optee-os/keys/default_ta.pem`. Therefore, if optee_os has not been compromised, you can trust the TAs.

So the next question is: how do you know that optee_os has not been compromised? It's simple: the chain of trust has to extend all the way from the first boot loader binary (in ROM) up to optee_os. Every boot loader stage is signed, each stage checks the signature of the next stage before executing it. You can see this scheme implemented in ARM Trusted Firmware.

**Comment by ursus-the-bear** [comment]
So what you are saying is that if the TA runs i.e. I can call it all is well? But if we have a problem with optee being compromised then I assume it does not boot (as optee boots the Richos the Richos cannot call the TA).

What happens if eg. the 3. boot loader (I am assuming there are more than three) is compromised - I assume that the 2. boot loader checks the hash of the 3. one and finds that they are not equal - does it then just stop loading? How would the user of the system (mine is running on a Pi3) know?

Thank you for your help.

**Comment by lorc** [comment]
Hi, @ursus-the-bear 

It all starts from trusted root. On most SoC trusted root is a ROM code inside a chip. Chip always boots from ROM code, that is fused by manufacturer. ROM code checks signature of a first boot loader, first bootloader checks second one and so on. If check fails on any step, then board just not boots up. You can see this on smartphones: when you try to mess with bootloaders, you easily can "brick" your phone.

Most of dev boards (like Pi3) does not have this feature enabled. That means, that ROM code on Pi3 will execute any bootloader. So, you can't build real chain of trust on Pi3. 

Moreover, you need a key to sign your first stage bootloader. Most of SoC vendors will refuse to give you this key, or will share developer key. You will need to ask vendor to provision chips with your own keys, when time comes to real production.

**Comment by ursus-the-bear** [comment]
Thank you very much for the informative information guys. Great job 👍
