### ISSUE TITLE
Confused by phys_mem_map_section

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#1626]
Hi everyone,
I'm reading the source code of OP-TEE, and have a little confusion about its memory initialization in the boot stage.
From the kernel linker script (kern.ld.S), we know that the phys_mem_map_section is kept from the address of __start_phys_mem_map_section.
	___start_phys_mem_map_section = . ;
		KEEP(*(phys_mem_map_section))
	__end_phys_mem_map_section = . ;_

In the boot stage of OP-TEE, it initializes the MMU map in the function of core_init_mmu_map, which is defined in the core_mmu.c. 
core_init_mmu_map calls the function of init_mem_map to initialize the global  memory map  static_memory_map (struct core_mmu_phys_mem). The init_mem_map function adds all the sections between __start_phys_mem_map_section and  __end_phys_mem_map_section to static_memory_map.

However, I look through the source code of OP-TEE, and find no sections defined as type of phys_mem_map_section. So the init_mem_map function initializes the static_memory_map with none elements.
I think there must be something wrong with my understanding, but I indeed find no code to initialize the global  structure static_memory_map.

**Comment by jenswi-linaro** [comment]
The `register_phys_mem()` macro is used to put stuff in "phys_mem_map_section".

**Comment by TEE-OS** [comment]
Hi jenswi,

Thanks for your reply.
Yes, the register_phys_mem() macro can put sections in "phys_mem_map_section". However, after I look through the source code of OP-TEE, I find that this macro is not invoked in anywhere.
What I want to know is how the TEE memory (such as secure_only and nsec_shared memory region) is mapped. However, I find no place where the secure_only and nsec_shared memroy are added to the static_memory_map .

_static struct memaccess_area secure_only[] = {
#ifdef TZSRAM_BASE
	MEMACCESS_AREA(TZSRAM_BASE, TZSRAM_SIZE),
#endif
	MEMACCESS_AREA(TZDRAM_BASE, TZDRAM_SIZE),
};

static struct memaccess_area nsec_shared[] = {
	MEMACCESS_AREA(CFG_SHMEM_START, CFG_SHMEM_SIZE),
};_

**Comment by jenswi-linaro** [comment]
Check here
https://github.com/OP-TEE/optee_os/blob/a04aa50fa65ad25cca059589c6b0732fdf140153/core/arch/arm/plat-vexpress/main.c#L88
and here
https://github.com/OP-TEE/optee_os/blob/a04aa50fa65ad25cca059589c6b0732fdf140153/core/arch/arm/mm/core_mmu.c#L106

**Comment by TEE-OS** [comment]
Hi jenswei,
Thanks for your kindly reply. 
I get it. 
I mistook the macro for a function.
