### ISSUE TITLE
Perpetually running TA

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1627]
As I have read in the GlobalPlatform homepage there is no scheduler in the TEE so that it can be kept lean. I fully understand this design decision. I was wondering if you guys see any reason why I cannot start a TA when the system starts up and just keep it running in a loop? The normal world will do any scheduling necessary and make sure that everything runs smoothly... or are the TA's somehow allowed to finished before they are swapped out again? I assume that I can run more that one TA at a time, is that correct?

I would just like to thank the people in this "forum" for answering my newbie questions here and generally being nice - that is not the case everywhere 👍

**Comment by jenswi-linaro** [comment]
It is possible to start a TA as you describe, but it will take up resources and potentially block other TAs forever since it's assumed that a TA sooner or later will return and free up resources that others may be waiting for.

**Comment by ursus-the-bear** [comment]
Thank you for your answer Jens, just to be sure I understand you correctly, I *can* start a "perpetual" TA and the RichOS scheduler will take care of the scheduling for me. So if I had a Pi3 for example I could launch a daemon when Raspian starts, let the daemon and the TA keep talking to one another and never really stop... if I keep my programming lean then other TA's can still be started from eg. another application in Raspbian that speaks to another TA.

Asked another way, how many TA's can be run at the same time (TA - CA pair naturally)? Is it just limited by the CPU and TEE memory (32 MB as far as I can remember)?

**Comment by lorc** [comment]
OP-TEE is multi threaded. But number of threads is limited (check out `CFG_NUM_THREADS`). Every thread potentially can execute call to a TA. 
You can load many TAs,  but you can't run more than  `min(CFG_NUM_THREADS,  number-of-cores)` simultaneously (actually `CFG_NUM_THREADS` by default is equal or bigger than number of cores).

And yes, RichOS scheduler will take care about scheduling CAs and, thus, scheduling TAs. One TA can call other TA, but anyways, first call should be issued from REE.

Problem can arise if you'll write `while(1);` TA. But why you can want to do this? Remember, that OP-TEE will load only TAs signed by you, so it is your responsibility to ensure that all TAs will behave correctly.

**Comment by ursus-the-bear** [comment]
This is me just trying to understand how the scheduling works i.e. how the TA scheduling is connected to the RichOS. Thank you for your input, it is greatly appreciated :o)
