### ISSUE TITLE
Booting OPTEE in custom i.MX6UL board.

### ISSUE THREAD

**Issue by kumarabekur** [OP-TEE/optee_os#1628]
Hi, I am trying to boot the optee in my custom i.MX6UL board. I have followed [this](http://mrvan.github.io/optee-imx6ul) link by @MrVan  to port optee to my board. This is what I have done:

- Took  base U-boot from NXP for imx6ul and compared it with the U-boot from above link and made following changes: 
file : configs/mx6ul_iwg18m_defconfig
`CONFIG_ARM=y
CONFIG_ARCH_MX6=y
CONFIG_TARGET_MX6UL_IWG18M=y
CONFIG_SYS_EXTRA_OPTIONS="IMX_CONFIG=board/freescale/mx6ul_iwg18m/imximage.cfg,TEE_RAM_SIZE=0x4000000"
CONFIG_CMD_GPIO=y
CONFIG_CMD_DHCP=y
CONFIG_CMD_PING=y`
file : board/freescale/mx6ul_iwg18m/mx6ul_iwg18m.c
`gd->ram_size = imx_ddr_size() - CONFIG_TEE_RAM_SIZE;`

-  Took linux kernel from the above link then added our board specific patches.

- Took optee os from above link and changed `core/arch/arm/plat-imx/platform_config.h` :
`#define DDR_PHYS_START                  DRAM0_BASE
#define DDR_SIZE                        DRAM0_SIZE

#define CFG_DDR_START                   DDR_PHYS_START
#define CFG_DDR_SIZE                    DDR_SIZE

/* Full GlobalPlatform test suite requires CFG_SHMEM_SIZE to be at least 2MB */
#define CFG_SHMEM_START                 (TZDRAM_BASE - 0x100000)
#define CFG_SHMEM_SIZE                  0x100000

/* Location of trusted dram on imx */
#define TZDRAM_BASE                   (0x8C100000) // 256MB RAM (193rd MB starting add)
#define TZDRAM_SIZE                     (0x03000000)

#define CFG_TEE_RAM_VA_SIZE             (1024 * 1024)

#ifndef CFG_TEE_LOAD_ADDR
#define CFG_TEE_LOAD_ADDR               CFG_TEE_RAM_START
#endif
`
Our board has 256MB RAM so changed TZDRAM_BASE from 0x9C100000 to 0x8C100000 . My understanding is in i.MX6UL evk(512MB RAM) board 0x9C100000 corresponds to 449th MB RAM address while remaining 64MB RAM allocated to optee . So in our board changed TZDRAM_BASE address to 0x8C100000 which corresponds to 193rd MB RAM location. 

- Generated uTee by giving following commands 
`mkimage -A arm -O linux -C none -a 0x8c0fffe4 -e 0x8c100000 -d ./out/arm-plat-imx/core/tee.bin uTee`

- Compiled OPTEE Client and Xtest as per link instructions. 

- Tried to boot OPTEE OS. But unfortunately I got error message like
 `Not valid image format for Authentication, Please check`
Here is the complete [debug log](https://gist.github.com/kumarabekur/eacaefb4be3b44f9c359a50ac71e051c) 

- Next after checking [this](https://gist.github.com/acalb/8c64437641d53b6237dfff92cb126a23) link I tried to boot optee os without generating uTee ; directly using tee.bin file by giving below commands in U-boot
`run bootargs_msd;mmc dev 0;fatload mmc 0 ${loadaddr} ${kernel};fatload mmc 0 ${fdt_addr} ${fdt_file};`
`fatload mmc 0:1 0x8c100000 optee.bin;`
`bootz ${loadaddr} - ${fdt_addr}`

- This time I got [this](https://gist.github.com/kumarabekur/94a303cd4b70d6704049222735d60ff8) error. It  seems there is error is loading optee driver. I can't able to figure it out. Please help me to solve this issue 

Thanks in advance.

**Comment by MrVan** [comment]
@kumarabekur please make sure the mkimage you used is the same one that generated when you compling uboot source code.

**Comment by kumarabekur** [comment]
yes @MrVan . I have used same mkimage which is generated when I compiled U-Boot source code. Still I got _"Not valid image format for Authentication, Please check"_  error.

**Comment by MrVan** [comment]
Please reread the doc http://mrvan.github.io/optee-imx6ul, uTee is used, not optee.bin. bootm [uTee addr] - [fdtaddr].

**Comment by kumarabekur** [comment]
yes @MrVan , for this approach I used uTee which is generated using mkimage. Using optee.bin is different approach. Using optee.bin step I tried after failing in booting uTee . Now I am struggling to boot optee as per instructions you have given in  http://mrvan.github.io/optee-imx6ul .

**Comment by MrVan** [comment]
Use uTee please. optee.bin needs hack code in uboot. What error msg when booting utee?

**Comment by kumarabekur** [comment]
> Use uTee please. optee.bin needs hack code in uboot. What error msg when booting utee?

_**"Not valid image format for Authentication, Please check"**_  -This is the error msg I get when I use uTee. Please ignore that optee.bin step I have mentioned in qustn. It was just experimentation I did while debugging. I am following ur link http://mrvan.github.io/optee-imx6ul . 

After I give `bootm 0x84000000 - ${fdt_addr};` , I am getting above error message.

**Comment by MrVan** [comment]
you are using the following steps, right?
```
mkimage -A arm -O linux -C none -a 0x8c0fffe4 -e 0x8c100000 -d ./out/arm-plat-imx/core/tee.bin uTee
fatload mmc 0:1 0x84000000 uTee
bootm 0x84000000 - ${fdt_addr}
```

After all the images loaded into DRAM, saying kernel/dtb/uTee, could you check whether image at 0x84000000 is still uImage format? If no valid image, I suspect you uTEE maybe overridden by Kernel image. Where do you load Kernel and the size of zImage?

**Comment by kumarabekur** [comment]
> mkimage -A arm -O linux -C none -a 0x8c0fffe4 -e 0x8c100000 -d ./out/arm-plat-imx/core/tee.bin uTee
fatload mmc 0:1 0x84000000 uTee
bootm 0x84000000 - ${fdt_addr}

Yes @MrVan . I am following the same steps. After `bootm 0x84000000 - ${fdt_addr}` I get 
_**"Not valid image format for Authentication, Please check"**_
Here is the zImage,dtb load addr and size 
zImage Load addr = 0x80800000 
zImage size = 6655544 bytes
dtb load addr = 0x83000000
dtb size = 38482 bytes

**Comment by MrVan** [comment]
Just check whether data at 0x84000000 is uImage format or not after all images loaded. Besides this, I do not have more clues.

**Comment by kumarabekur** [comment]
Hello @MrVan . I tried same procedure with uImage. It worked and I can able to boot OPTEE but now booting stops after below message. 
```
switch to partitions #0, OK
mmc0 is current device
reading uImage
6708328 bytes read in 315 ms (20.3 MiB/s)
reading imx6ul-iwg18m-twr-pos_keshu.dtb
38569 bytes read in 22 ms (1.7 MiB/s)
imx6ul_iwg18m_twr_pos>  fatload mmc 0:1 0x84000000 uTee
reading uTee
221188 bytes read in 27 ms (7.8 MiB/s)
imx6ul_iwg18m_twr_pos>  bootm 0x84000000 - ${fdt_addr}
RET1=1hab fuse not enabled
## Booting kernel from Legacy Image at 84000000 ...
   Image Name:   
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    221124 Bytes = 215.9 KiB
   Load Address: 8c0fffe4
   Entry Point:  8c100000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 83000000
   Booting using the fdt blob at 0x83000000
   Loading Kernel Image ... OK
   Using Device Tree in place at 83000000, end 8300c6a8
ft_system_setup for mx6

Starting kernel ...

DEBUG:   [0x0] TEE-CORE:add_phys_mem:365: CFG_SHMEM_START type NSEC_SHM 0x8c000000 size 0x00100000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:365: CFG_TA_RAM_START type TA_RAM 0x8c200000 size 0x02f00000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:365: VCORE_UNPG_RW_PA type TEE_RAM_RW 0x8c134000 size 0x000cc000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:365: VCORE_UNPG_RX_PA type TEE_RAM_RX 0x8c100000 size 0x00034000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:365: GIC_BASE type IO_SEC 0x00a00000 size 0x00100000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:365: CONSOLE_UART_BASE type IO_NSEC 0x02000000 size 0x00200000
INFO:    TEE-CORE: No NSEC DDR memory area defined
DEBUG:   [0x0] TEE-CORE:add_va_space:404: type RES_VASPACE size 0x00a00000
DEBUG:   [0x0] TEE-CORE:add_va_space:404: type SHM_VASPACE size 0x00a00000
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:531: type IO_NSEC      va 0x87a00000..0x87bfffff pa 0x02000000..0x021fffff size 0x00200000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:531: type NSEC_SHM     va 0x87c00000..0x87cfffff pa 0x8c000000..0x8c0fffff size 0x00100000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:531: type TA_RAM       va 0x87d00000..0x8abfffff pa 0x8c200000..0x8f0fffff size 0x02f00000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:531: type RES_VASPACE  va 0x8ac00000..0x8b5fffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:531: type IO_SEC       va 0x8b600000..0x8b6fffff pa 0x00a00000..0x00afffff size 0x00100000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:531: type SHM_VASPACE  va 0x8b700000..0x8c0fffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:531: type TEE_RAM_RX   va 0x8c100000..0x8c133fff pa 0x8c100000..0x8c133fff size 0x00034000 (smallpg)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:531: type TEE_RAM_RW   va 0x8c134000..0x8c1fffff pa 0x8c134000..0x8c1fffff size 0x000cc000 (smallpg)
DEBUG:   [0x0] TEE-CORE:core_mmu_alloc_l2:248: L2 table used: 1/4
INFO:    TEE-CORE: 
DEBUG:   [0x0] TEE-CORE:init_canaries:167: #Stack canaries for stack_tmp[0] with top at 0x8c15e7f8
DEBUG:   [0x0] TEE-CORE:init_canaries:167: watch *0x8c15e7fc
DEBUG:   [0x0] TEE-CORE:init_canaries:168: #Stack canaries for stack_abt[0] with top at 0x8c15f038
DEBUG:   [0x0] TEE-CORE:init_canaries:168: watch *0x8c15f03c
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_thread[0] with top at 0x8c161078
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x8c16107c
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_thread[1] with top at 0x8c1630b8
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x8c1630bc
DEBUG:   [0x0] TEE-CORE:add_optee_dt_node:406: OP-TEE Device Tree node already exists!
INFO:    TEE-CORE: OP-TEE version: 2.4.0-130-gf9a64f1-dev #8 Sat Jun 24 10:12:34 UTC 2017 arm
INFO:    TEE-CORE: Shared memory address range: 8b700000, 8c100000
FLOW:    [0x0] TEE-CORE:plat_prng_add_jitter_entropy:97: plat_prng_add_jitter_entropy: 0xA5DB
INFO:    TEE-CORE: Initialized
DEBUG:   [0x0] TEE-CORE:init_primary_helper:585: Primary CPU switching to normal world boot
```
I have referenced the thread #1284 . In this kernel PSCI already enabled and I am not quite understanding why CPU not switching to normal world boot. Any idea @MrVan

**Comment by MrVan** [comment]
@kumarabekur  Please enable Linux kernel earlyprintk and pass earlyprintk bootargs to kernel and see whether there is any kernel log output in console. The last line in your log shows TEE switched to Linux, but no output from Linux. So enable earlyprintk to debug.

**Comment by j824737450** [comment]
Booting the board , the log like these.It stops at 'Starting kernel.....'.  What are the possible reasons?
Thank you !

Hit any key to stop autoboot:  0 
Using FEC device
TFTP from server 192.168.0.119; our IP address is 192.168.0.120
Filename 'uImage'.
Load address: 0x12000000
Loading: #################################################################
         #################################################################
         #################################################################
         #################################################################
         ############################################################
         2.5 MiB/s
done
Bytes transferred = 4695688 (47a688 hex)
Using FEC device
TFTP from server 192.168.0.119; our IP address is 192.168.0.120
Filename 'imx6q-sabrelite.dtb'.
Load address: 0x18000000
Loading: ###
         2.3 MiB/s
done
Bytes transferred = 31927 (7cb7 hex)
Using FEC device
TFTP from server 192.168.0.119; our IP address is 192.168.0.120
Filename 'uTee'.
Load address: 0x20000000
Loading: ##################
         2.6 MiB/s
done
Bytes transferred = 258132 (3f054 hex)
## Booting kernel from Legacy Image at 20000000 ...
   Image Name:   
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    258068 Bytes = 252 KiB
   Load Address: 4dffffe4
   Entry Point:  4e000000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 18000000
   Booting using the fdt blob at 0x18000000
   Loading Kernel Image ... OK
   Using Device Tree in place at 18000000, end 1800acb6

Starting kernel ...
