### ISSUE TITLE
Best Practice for Profiling TAs with Gprof

### ISSUE THREAD

**Issue by CarltonShepherd** [OP-TEE/optee_os#1629]
Hello all,

I'm looking to profile an extended version of `hello_world` using gprof.  I've followed the gprof.md guide, but I can't run it successfully; both execute normally as if gprof wasn't present at all.   I'm likely setting the CFLAGs wrong, both in the OS and hello_world.

The documentation is slightly unclear.  Is it best to run `make helloworld` with flags, or within the hello_world directory itself where the Makefiles are stored, i.e. `make hello_world` in `/hello_world/`?.  

For the OS, is it best to set `CFG_TA_GPROF_SUPPORT ?= y` and  `CFG_ULIBS_GPROF ?= y` directly in the config mk files?  If not, what would be a command line example to run it correctly?

I'm using a fresh `hikey_debian.xml` build on a HiKey LeMaker.  Thanks for any help.

**Comment by jforissier** [comment]
Hi @CarltonSheperd,

`make CFG_TA_GPROF_SUPPORT=y CFG_ULIBS_GPROF=y CFLAGS_ta_arm32=-g` in the `build` directory should do the trick.

**Comment by CarltonShepherd** [comment]
Thank you, @jforissier.  That worked perfectly!
