### ISSUE TITLE
va conflicts with user ta address

### ISSUE THREAD

**Issue by nodeax** [OP-TEE/optee_os#1632]
Trying to run op-tee from internal SRAM at 0x201000 (<32MiB address range) results in **_va conflicts with user ta address_** panic. The SoC is a single core Cortex A5, so LPAE is not available. Running op-tee from DRAM works fine, but does not fit our security requirement.

Is there a way to map user space to a different location? Any other alternatives if I want run op-tee from SRAM?

> DEBUG:   [0x13e9d980] TEE-CORE:add_phys_mem:318: CFG_SHMEM_START type NSEC_SHM 0x3e000000 size 0x00400000
DEBUG:   [0x13e9d980] TEE-CORE:add_phys_mem:318: CFG_TA_RAM_START type TA_RAM 0x3e500000 size 0x01b00000
DEBUG:   [0x13e9d980] TEE-CORE:add_phys_mem:318: CFG_TEE_RAM_START type TEE_RAM 0x00201000 size 0x0001f000
DEBUG:   [0x13e9d980] TEE-CORE:add_phys_mem:318: CONSOLE_UART_BASE type IO_SEC 0xf8000000 size 0x00200000
DEBUG:   [0x13e9d980] TEE-CORE:add_va_space:357: type RES_VASPACE size 0x00a00000
DEBUG:   [0x13e9d980] TEE-CORE:add_va_space:357: type SHM_VASPACE size 0x00a00000
DEBUG:   [0x13e9d980] TEE-CORE:dump_mmap_table:471: type TEE_RAM      va 0x00201000..0x0021ffff pa 0x00201000..0x0021ffff size 0x0001f000 (smallpg)
DEBUG:   [0x13e9d980] TEE-CORE:dump_mmap_table:471: type TA_RAM       va 0x00400000..0x01efffff pa 0x3e500000..0x3fffffff size 0x01b00000 (pgdir)
DEBUG:   [0x13e9d980] TEE-CORE:dump_mmap_table:471: type NSEC_SHM     va 0x01f00000..0x022fffff pa 0x3e000000..0x3e3fffff size 0x00400000 (pgdir)
DEBUG:   [0x13e9d980] TEE-CORE:dump_mmap_table:471: type IO_SEC       va 0x02300000..0x024fffff pa 0xf8000000..0xf81fffff size 0x00200000 (pgdir)
DEBUG:   [0x13e9d980] TEE-CORE:dump_mmap_table:471: type RES_VASPACE  va 0x02500000..0x02efffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
DEBUG:   [0x13e9d980] TEE-CORE:dump_mmap_table:471: type SHM_VASPACE  va 0x02f00000..0x038fffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
ERROR:   TEE-CORE: Panic 'va conflicts with user ta address' at core/arch/arm/mm/core_mmu_v7.c:715 <map_memarea>

Thanks for your help,
Akshay

**Comment by jenswi-linaro** [comment]
Yes it's possible, but it will require some non-trivial changes in `core/arch/arm/mm/core_mmu_v7.c`. We have some vague plans for unifying `core_mmu_v7.c` and `core_mmu_lpae.c` that would probably take care of problems like this at the same time. However, when and how that will be done is far from decided, so I'm afraid that will not help you immediately.

If you're prepared to do something about this I can assist with review etc.

**Comment by nodeax** [comment]
Thanks for the info :) What kind of non-trivial changes are we talking about? Is it a matter of creating a non-identity map (va different from pa) for TEE_RAM and jumping to the new va immediately after mmu is enabled (something similar to what Linux kernel does)? Or are there things that need to be considered (making sure code is position independent? any power management code changes? etc.). Trying to gauge the scope of work before attempting to undertake it.

For my understanding, I would appreciate if you could give me a quick background about the RES_VASPACE (why does it need to be 1st 32 MiB and how/where is it being used?)

Lastly in my usecase, we are using TEE with a pseudo TA (no user/dynamic TA's). So is there a short term way of working around this issue (even if it means maintaining a term local patch)? Thanks.

**Comment by jenswi-linaro** [comment]
If you don't need user TA's you can compile with CFG_WITH_USER_TA=n and hopefully that should be enough. If there's still a conflict with the user space range you can make changes under `#ifndef CFG_WITH_USER_TA` which could be accepted upstream.

With the v7 translation tables we keep a small per cpu level1 translation table in ttbr0 and a large shared level1 table in ttbr1 when a user mapping is active (see `core_mmu_set_user_map()` in `core_mmu_v7.c`). If user mappings are inactive ttbr0 point to the same level1 table and ttbr1.

The easiest way forward for you as I see it is to keep the identity map for TEE_RAM and change the handling of the small level1 table that is used in ttbr0 when user mapping is active. This is made a bit easier by the fact that the TEE_RAM mapping is static unless the pager is active but then all the TEE_RAM is mapped in a level2 table so the level1 table still always uses the same values.

`core_mmu_get_user_va_range()` in `core_mmu_v7.c` need to be updated to avoid the range used for TEE_RAM. `core_mmu_create_user_map()` need to be updated to not use the entire level1 table etc.

I think the changes you'll need to make will be quite small and well contained, the challenge is to understand the code in `core_mmu_v7.c` and how it interacts with rest of OP-TEE.

**Comment by prime-zeng** [comment]
@jenswi-linaro  i have met the same problem, i can work around by using two page tables for OP-TEE kernel,  one is the identify map for boot(including slave core power up) and the other is plat map for runtime,  what do you think about my solution? by the way, i don't quite understand your ideas, ^_^.

**Comment by jenswi-linaro** [comment]
@prime-zeng this is an interesting topic. By "two page tables", do you mean two level 1 translation tables?

Ideally I'd like to have one solution that works for all situations. With the exception of the conflict with user VA space as in this case (which can be fixed) I think our current solution is good.
- It saves memory by not needing a second set of translation tables.
- Identity map of memory makes the boot and slave core power quite simple, the biggest thing to mind is the caches.

What I was describing in the earlier comment was a way of emulating what we're doing with LPAE tables. In order to do that we need to mirror some entries in the level 1 tables. Those entries will point to level 2 tables (corresponding to the level 3 tables with LPAE) in which there may be dynamic updates (paging), but never dynamic updates of the level 1 entries.

**Comment by etienne-lms** [comment]
Regarding user TAs virtual location, @jenswi-linaro, you mean changing `core_mmu_get_user_va_range()` to dynamically get the 1st suitable large enough free area in the core virtual mapping to locate user TAs base address ?

The non-lpae uses the top/bottom ways for the core mapping (static and dynamic) through `core_mmu_place_tee_ram_at_top()`:
- if core identity map is below 0x8000.0000: core static/dynamic mapping is below this limit.
- if core identity map is above 0x8000.0000: core static/dynamic mapping is above this limit.
We could easily find a free place for the user TAs base address and supported range.

**Comment by prime-zeng** [comment]
@jenswi-linaro yes, i mean two level1 translation tables.  
For the two translation tables solution:
-  The additional translation table size is 16k,  not to much waste, and we can try to reuse it after boot.
-  The OP-TEE can run at any position and no limit, one binary with device tree can fit different hardware configurations.

Compared with the currently solution, no too much fixes are need.

**Comment by jenswi-linaro** [comment]
What's not too much waste is very subjective, try to squeeze OP-TEE into 256 KiB of RAM and you'll notice that 16 KiB can make the difference. But on the other hand on platforms with lots of available memory it would make sense. So this is something to keep in mind if/when we make complete overhaul of the translation table stuff.

**Comment by prime-zeng** [comment]
@jenswi-linaro   agree with you.   Currently we can clean the mm code which heavily depends on the identity mapping, in fact, we only the boot code depends on the identity mapping and the other should only treat the mapping as plat-mapping.  for the two translation tables solution, we have a simple idea:
- use the exisit level1 translations tables for boot identity mapping, clear it after use. use plat-mapping for runtime.
- the problem is that the plat-mapping may conflict with the identity-mapping.(for example, plat-maping 0xc0000000~0xc2000000,  identity-mapping is 0xc0100000 ~0xc1100000 when the phyic address is from 0xc0100000).

**Comment by jenswi-linaro** [comment]
This mapping conflict has to be a universal problem, how does others deal with this?

**Comment by prime-zeng** [comment]
@jenswi-linaro  they can change the compile address(plat-mapping) to work around the mapping conflict.

**Comment by jordanrh1** [comment]
Hi, do you know if there are any plans to address this issue? This affects IMX6 which has it's SRAM block in the first 32MB of address space.

**Comment by jenswi-linaro** [comment]
Perhaps @prime-zeng has some news?

**Comment by prime-zeng** [comment]
@jenswi-linaro  Please help to review the https://github.com/OP-TEE/optee_os/pull/1661.  Currently the physic address equals to the virtual address in the OP-TEE core, and we don't have a clear boundary between the physic and virtual address usage, if we want to support non-identity mapping,  i think this is the first problem to be resolved,  and my patch aims that,  in fact,  i have a implementation which support non-identity mapping , unfortunately it doesn't support Pager and break the current mm design.
