### ISSUE TITLE
A question about the map_page_memarea_in_pgdirs() function

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#1633]
I think one line code of the  map_page_memarea_in_pgdirs() function is wrong. The following is my explanation.

The function map_page_memarea_in_pgdirs() is used to map a memory map region using two level translation, and the page size is 4K. The logic of this function is as follows:
First, map the L2 translation table for mm (struct tee_mmap_region). Each L2 translation table contains 256 entries, each entry maps 4K (SMALL_PAGE_SIZE) address space, and the size of one L2 translation table is 256*4=1K. 
Second, map the L1 translation table for mm. Each entry of L1 translation table points to a L2 translation table, and maps 1M (SECTION) address space.

The code of this function is pasted at the end. The ttb is the L1 translation table. In the second part of the function, each entry of L1 translation table points to the physical address of a L2 translation table, and the code is ttb[idx] = pa|addr (idx index one entry of L1 table, and pa is the physical address of L2 translation table). As the size of each L2 table is 1K, the pa should be added 1K when idx increases. However, the code adds one SECTION_SIZE to pa (pa += SECTION_SIZE). I think the correct code should be: pa += 1K (the size of L2 translation table).

The reason why OP-TEE runs well is that actually each time the function maps one SECTION most, so the n is 1, and the pa += SECTION_SIZE actually does not work.

static void map_page_memarea_in_pgdirs(const struct tee_mmap_region *mm,
					uint32_t *ttb)
{
       .......
       //map the L2 translation page table first.
	if (mm->attr & TEE_MATTR_VALID_BLOCK) {
		attr = mattr_to_desc(1, mm->attr | TEE_MATTR_TABLE);
		pa = map_page_memarea(mm, ttb[idx]);
	}
       
       //then map the L1 translation page table.
	n = ROUNDUP(mm->size, SECTION_SIZE) >> SECTION_SHIFT;
	while (n--) {
		assert(!attr || !ttb[idx] || ttb[idx] == (pa | attr));
		ttb[idx] = pa | attr;
		idx++;
		pa += SECTION_SIZE; // I think this should be: pa += 1K(the size of L2 translation table)
	}
}

**Comment by jenswi-linaro** [comment]
Yes, I think you're right. If possible please create a pull request fixing this.

**Comment by etienne-lms** [comment]
Well, you are right that the `pa += SECTION_SIZE;` is buggy, but in the other hand, there is no insurance that `map_page_memarea()` returns the base address of set of contiguous L2 tables: in case the table is not allocated but reused from an already filled L2 table.

Current implementation starts from function`map_memarea()` that insures `map_page_memarea_in_pgdirs()` is called only for a single L2 table mapping range: if more pgdirs are required, the function will call `map_page_memarea_in_pgdirs()` for each required pgdir entry.

So, the fix could be:
- rename `map_page_memarea_in_pgdirs()` into `map_page_memarea_in_pgdir()`, remove the useless loop (the one that use increment `pa`, and check that `mm->size` is lower than `SECTION_SIZE` at `map_page_memarea()` entry.
or
- make deeper changes in this mapping sequence.

**Comment by TEE-OS** [comment]
@etienne-lms yes, your suggestion on fixing the bug is right.

Actually the L2 translation table returned by map_page_memarea() is contiguous as OP-TEE uses global L2 table `main_mmu_l2_ttb[MAX_XLAT_TABLES]`. However, the `MAX_XLAT_TABLES` is defined as 4. So the max virtual address space that the level two translation table maps is 4M.  As I know that OP-TEE uses 32M physical memory, is 4M is enough for OP-TEE?

```
#define MAX_XLAT_TABLES		4
static uint32_t main_mmu_l2_ttb[MAX_XLAT_TABLES][NUM_L2_ENTRIES]
		__aligned(L2_ALIGNMENT) __section(".nozi.mmu.l2");
```

**Comment by etienne-lms** [comment]
> L2 translation table returned by map_page_memarea() is contiguous

Yes. But the static mapping can also share L2 tables between different areas. Calling `map_page_memarea()` is currently safe only if it maps an area within a single pgdir entry (section) so that it returns the  base address of the unique allocated or reused L2 table.

> As I know that OP-TEE uses 32M physical memory, is 4M is enough for OP-TEE (...)

OP-TEE does not use 32MB of physical memory. It uses... the physical memory defined by the platform. Platform currently supported in [optee_os](https://github.com/OP-TEE/optee_os) defines between 1MB and 4MB of physical memory for the 'core' (`CFG_TEE_RAM_PH_SIZE`) and from 16MB to 60MB of physical memory for the 'TAs' (`CFG_TA_RAM_SIZE`).

> (...) is 4M is enough (...) ?

Note that the value a 4 for `MAX_XLAT_TABLES` can be overridden by platforms to fit the best/optimized value according to platform mapping requirements.

**Comment by TEE-OS** [comment]
@jenswi-linaro , Hi jenswi, I will create a pull request to fix this.
As discussed above, current source code of OP-TEE will not trigger this bug. So actually the code is still safe.

**Comment by etienne-lms** [comment]
Hello @TEE-OS. Great. Do not hesitate for proposals. 
Trying to understand your goal, I wondered if you had some dynamic mapping support requirements to handle.

**Comment by prime-zeng** [comment]
@TEE-OS    @jenswi-linaro    @etienne-lms     Any update ?

**Comment by prime-zeng** [comment]
if (mm->attr & TEE_MATTR_VALID_BLOCK)  {    
		attr = mattr_to_desc(1, mm->attr | TEE_MATTR_TABLE);
	n = ROUNDUP(mm->size, SECTION_SIZE) >> SECTION_SHIFT;
	while (n--) {
		pa = map_page_memarea(mm, ttb[idx]);
		assert(!attr || !ttb[idx] || ttb[idx] == (pa | attr));
		ttb[idx] = pa | attr;
		idx++;
	}
 


what about the above fix ?

**Comment by TEE-OS** [comment]
@prime-zeng , I'm looking through the code of OP-TEE, and find some incorrect codes. I plan to fix these errors in a focused time. However, it would be very kind if you can fix this. 
My suggestion is the same as @etienne-lms proposed: rename `map_page_memarea_in_pgdirs()` into `map_page_memarea_in_pgdir()`, remove the useless loop (the one that use increment pa, and check that mm->size is lower than SECTION_SIZE at map_page_memarea() entry.

**Comment by prime-zeng** [comment]
@TEE-OS  Got it , and i will wait for your fix,  Thank you.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
