### ISSUE TITLE
console_init before core_init_mmu_map

### ISSUE THREAD

**Issue by P1119r1m** [OP-TEE/optee_os#1641]
I'm confused a little bit...
I found that console_init() was called before initialization of the MMU.
Is it ok?

File: /optee/core/arch/arm/kernel/generic_entry_a32.S

Source code extraction:
```
	/* Enable Console */
	bl	console_init

        ...

	bl	core_init_mmu_map
	bl	core_init_mmu_regs
	bl	cpu_mmu_enable
	bl	cpu_mmu_enable_icache
	bl	cpu_mmu_enable_dcache
```

Thanks!

**Comment by jforissier** [comment]
@P1119r1m yes, it is on purpose. To facilitate debugging, we want to be able to use the console as early as possible, even before the MMU is turned on. Therefore, ` console_init()` is supposed to work with physical addresses. Then `console_putc()`, `console_flush()` etc. are expected to work with or without MMU enabled. Some UART drivers use the helper function `io_pa_or_va()` to do just that.

**Comment by P1119r1m** [comment]
@jforissier Thanks for you answer! But in this case we need to "switch off" mmu at the beginning, right?

**Comment by jforissier** [comment]
Since OP-TEE configures the MMU for its own use (`core_init_mmu_map`, `core_init_mmu_regs`), it should be off initially, yes.

**Comment by P1119r1m** [comment]
@jforissier Ok. Thank you!
