### ISSUE TITLE
Link error: TA calls pTA

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1642]
Hi

I am trying to do a shutdown from a TA via a pTA (https://github.com/OP-TEE/optee_os/issues/1609).  I have the code and it works perfectly when I call the pTA from the NW... I have now moved the code to the TA and got it to compile correctly, unfortunately I cannot work out the correct Makefile so that it will link as well, here is the error I am getting when I compile the TA (the pTA and CA are compiling without any problems, and, as stated everything works perfectly):

```
make[2]: Entering directory '/home/ursus/devel/optee/fim/ta'
  CC      fim_ta.o
  CPP     ta.lds
  LD      361142ae-ec3e-4576-8883-a6c0f6c6ec71.elf
./fim_ta.o: In function `shutdown':
/home/ursus/devel/optee/fim/ta/fim_ta.c:243: undefined reference to `TEEC_InitializeContext'
/home/ursus/devel/optee/fim/ta/fim_ta.c:247: undefined reference to `TEEC_OpenSession'
/home/ursus/devel/optee/fim/ta/fim_ta.c:254: undefined reference to `TEEC_InvokeCommand'
/home/ursus/devel/optee/fim/ta/fim_ta.c:258: undefined reference to `TEEC_CloseSession'
/home/ursus/devel/optee/fim/ta/fim_ta.c:259: undefined reference to `TEEC_FinalizeContext'
/home/ursus/devel/optee/optee_os/out/arm/export-ta_arm64/mk/link.mk:47: recipe for target '361142ae-ec3e-4576-8883-a6c0f6c6ec71.elf' failed
make[2]: *** [361142ae-ec3e-4576-8883-a6c0f6c6ec71.elf] Error 1
make[2]: Leaving directory '/home/ursus/devel/optee/fim/ta'
Makefile:6: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ursus/devel/optee/fim'
common.mk:342: recipe for target 'fim-common' failed
make: *** [fim-common] Error 2
```
here is my Makefile in the TA directory:

```
CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL) -I$(TEEC_EXPORT)/include
BINARY=361142ae-ec3e-4576-8883-a6c0f6c6ec71
include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
```

Thank you for any help given
Ursus

~ps: sorry about using quote and not code to display the code but I cannot get code to work correctly for me!~
*[Edit - JF] Fixed text formatting. You need to use three backticks to start/end a verbatim block.*

**Comment by jforissier** [comment]
Hi @ursus-the-bear ,

You're almost there... you just need to adjust the API you are using to invoke the TA. Although your TA behaves as a client wrt. to your pTA, the TEE Client API is not suitable. TAs must use the TEE Internal Core API, which has specific functions to invoke another (p)TA:

```
TEEC_InitializeContext() => (not used)
TEEC_OpenSession()       => TEE_OpenTASession()
TEEC_InvokeCommand()     => TEE_InvokeTACommand()
TEEC_CloseSession()      => TEE_CloseTASession()
TEEC_FinalizeContext()   => (not used)
```

**Comment by ursus-the-bear** [comment]
ah, ok, so that is why it worked from the NW but not from the TA :o) I'm trying that now.

I was wondering - you said I need to make sure it is being called from the TA and not the NW - not quite sure how I should do this? Can I somehow get the the caller name?

**Comment by jforissier** [comment]
You may check that `tee_ta_get_calling_session()` does not return NULL. Then it means the caller of your pTA is a TA (or pTA). See here: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/pta/gprof.c#L186-L189.

**Comment by ursus-the-bear** [comment]
perfect - thank you very much for the pointers :)
