### ISSUE TITLE
question about the usage of  CFG_TEE_RAM_START and CFG_TEE_LOAD_ADDR

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1647]
Hi:

There are some usage of the CFG_TEE_RAM_START and CFG_TEE_LOAD_ADDR in the  [https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/kern.ld.S](), in fact, i don't quite understand them all.  

In my understanding, the CFG_TEE_LOAD_ADDR should be used as virtual compile address, the CFG_TEE_RAM_START should be used as physical load address, and in the kern.ld.S, i think the CFG_TEE_RAM_START should not be used.

Can anyone help to explain?
Thank you.

**Comment by etienne-lms** [comment]
`CFG_TEE_RAM_START` is the base address of the TEE private RAM. It must be 4kB paged aligned for mapping constraint.

`CFG_TEE_LOAD_ADDR` is the load and cold boot entry address. It may not be 4kB page aligned. It must be inside range `CFG_TEE_RAM_START/_PH_SIZE`.

**Comment by prime-zeng** [comment]
@etienne-lms    ` CFG_TEE_LOAD_ADDR ` may not be 4KB aligned?   i can't understand that , what is the usecase for unaligned ` CFG_TEE_LOAD_ADDR `?     ` CFG_TEE_LOAD_ADDR `  is the compile address which also represents the virtual start address of the OP-TEE core.  I want to do something preparing for the non-identity mapping for OP-TEE core, so i need to make clear them first.

**Comment by etienne-lms** [comment]
One may want  CFG_TEE_LOAD_AD`D`R to start few bytes after the physical base address. I.e to use the first byte as a mailbox from bootstage (for some params).

From functionnal view, `CFG_TEE_LOAD_ADDR` does not need to be paged aligned.

**Comment by TEE-OS** [comment]
After viewing some platform's config file (platform_config.), I find that the `CFG_TEE_LOAD_ADDR `and `CFG_TEE_RAM_START `are always the same.

**Comment by etienne-lms** [comment]
Lots of platforms default `CFG_TEE_LOAD_ADDR` to `CFG_TEE_RAM_SIZE` if not defined, but one can still  build the OP-TEE providing a specific value for `CFG_TEE_LOAD_ADDR`.

**Comment by prime-zeng** [comment]
@etienne-lms  agree with you.  Maybe we need to introduce CFG_TEXT_OFFSET and CFG_TEE_START_VADDR which make more sense , the current CFG_TEE_LOAD_ADDR and CFG_TEE_RAM_START tightly depends on the identity mapping.
