### ISSUE TITLE
Does the pager is enabled on i.mx6q board?

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#1648]
After looking through the `kern.ld.s` and `platform_config.h` (for i.mx6q), I find that the load memory address is not configured correctly when pager is enabled. The reason is as follows:
The load address of the kernel is defined by `CFG_TEE_LOAD_ADDR`. So when pager is enabled, the kernel should be loaded to the SRAM (which is emulated by DRAM in i.mx6q), and the start address of SRAM is defined by `TZSRAM_BASE`. However, I find that the `CFG_TEE_LOAD_ADDR `is always defined as `TZDRAM_BASE `in the `platform_config.h` of i.mx6q whether the pager is enabled or not. 
It makes me more confused that `CFG_TEE_RAM_PH_SIZE `is defined as `TZSRAM_SIZE `when pager is enabled (but the load address is configured as the start address of DRAM. )

In the platform_config.h of the zynq7k platform, the CFG_TEE_LOAD_ADDR is defined as `TZSRAM_BASE`, and the CFG_TEE_RAM_PH_SIZE is defined as `TZSRAM_SIZE`. I think this is the correct configuration.

```
//platform_config.h of i.mx6q
#ifndef CFG_TEE_LOAD_ADDR
#define CFG_TEE_LOAD_ADDR		TZDRAM_BASE
#endif
//however, the PH_SIZE is defined as TZSRAM_SIZE
#define CFG_TEE_RAM_PH_SIZE		TZSRAM_SIZE

//platform_config.h of zynq7k
#define CFG_TEE_RAM_PH_SIZE		TZSRAM_SIZE
#ifndef CFG_TEE_LOAD_ADDR
#define CFG_TEE_LOAD_ADDR		TZSRAM_BASE
#endif
```

So my question is: does the pager function support i.mx6q? Or the CFG_TEE_LOAD_ADDR is a just typo.

**Comment by MrVan** [comment]
@TEE-OS To support Linux, pager is not supported. I am not sure whether windriver supports it or not, 
 @coolfengyu may comment on it.

**Comment by TEE-OS** [comment]
@MrVan, thanks for your reply.
Why the pager should be disabled to Linux? I don't see any relationship between pager and Linux.

**Comment by coolfengyu** [comment]
VxWorks can work when pager enabled (verified on 2.2.0)

**Comment by TEE-OS** [comment]
Hi, @coolfengyu . in the Vxworks environment, is the CFG_TEE_LOAD_ADDR defined as TZSRAM_BASE or TZDRAM_BASE?

**Comment by coolfengyu** [comment]
It's TZSRAM_BASE. I think the latest code is incorrect.

**Comment by TEE-OS** [comment]
Thanks @coolfengyu

**Comment by MrVan** [comment]
@TEE-OS I would like to see section mapping to implement low power features. I did not look into the detail of pager things. If i.mx low power things could work well, pager could be enabled.
