### ISSUE TITLE
can't understand the rule about UTEE_SYSCALL

### ISSUE THREAD

**Issue by cxdinter** [OP-TEE/optee_os#1655]
Hi,
   I have a question about UTEE_SYSCALL, I don't know why it can work, what's the mechanism? 
   For example:

    **UTEE_SYSCALL utee_asymm_verify, TEE_SCN_ASYMM_VERIFY, 7**
   I can't find the implementation for utee_asymm_verify(),  so how can utee_asymm_verify() work? 
   I guess utee_asymm_verify() may be related with libtom library, but I still haven't found the relationship.

   could you please give me some guide? Thanks.

**Comment by vchong** [comment]
The calls eventually trace back to https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/tee/arch_svc.c#L65. In `TEE_SCN_ASYMM_VERIFY`'s case, it corresponds to `syscall_asymm_verify`, which is defined in https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_svc_cryp.c#L3434.

**Comment by cxdinter** [comment]
Hi vchong,
    Thanks! Now I understood.
