### ISSUE TITLE
Compiler problem in compiling OPTEE OS, XTEST etc.

### ISSUE THREAD

**Issue by kumarabekur** [OP-TEE/optee_os#1660]
Hello @MrVan ,

I am following [your](http://mrvan.github.io/optee-imx6ul) document to port OPTEE to custom i.MX6UL EVK board. Till now i was struggling with #1628 issue. Now I have reduced CMA reserved-memory in linux device tree from 120MB  to 32MB to boot Linux kernel. Now I want to run xtest. But when I try to run xtest it is giving error `-sh: /bin/xtest: No such file or directory`. I used Yocto 1.7 dizzy cross compiler to compile OPTEE OS , XTEST etc. Suspecting cross compiler issue, I tried to compile OPTEE OS, xtest using Yocto Krogoth 2.1 compiler it is giving error to comiple optee os, xtest. So I would like to know which poky cross compiler you used to compile source code mentioned in [your](http://mrvan.github.io/optee-imx6ul) website??

**Comment by MrVan** [comment]
`xx-readelf -a xtest | grep Shared` to find out which shared libraries are used and not exsit in your system. And did you put client libraries into your rootfs?

**Comment by kumarabekur** [comment]
I had to 4.1.15-2.10 Yocto compiler to compile xtest. It is running in our custom imx6ul boarrd now :)
