### ISSUE TITLE
How to increase TEE RAM

### ISSUE THREAD

**Issue by doanquangviet** [OP-TEE/optee_os#1665]
1. u-boot:
- In configs\ezsys_imx6q2g_defconfig, I added TEE_RAM_SIZE:
`CONFIG_SYS_EXTRA_OPTIONS="IMX_CONFIG=board/ezsys/ezsys_imx6q/ezsys_imx6q2g.cfg**,TEE_RAM_SIZE=0x8000000**,MX6Q,DDR_MB=2048,DEFCONFIG=\"ezsys_imx6q2g\""`

- In board\ezsys\ezsys_imx6q\ezsys_imx6q.c, I changed dram_init function:
`int dram_init(void)
{
	gd->ram_size = ((ulong)CONFIG_DDR_MB * 1024 * 1024)  - CONFIG_TEE_RAM_SIZE;
	return 0;
}`

2. Optee: 
- In core\arch\arm\plat-imx\platform_config.h, I modified CFG_DDR_TEETZ_RESERVED_START and CFG_DDR_TEETZ_RESERVED_SIZE as:
`#define CFG_DDR_TEETZ_RESERVED_START	0x88000000
#define CFG_DDR_TEETZ_RESERVED_SIZE	0x08000000`

- And in build cmd: mkimage -A arm -O linux -C none -a 0x8dffffe4 -e 0x88000000 -d ./out/arm-plat-imx/core/tee.bin uTee

But got error when booting:

`## Booting kernel from Legacy Image at 20000000 ...
   Image Name:   
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    370956 Bytes = 362.3 KiB
   Load Address: 8dffffe4
   Entry Point:  88000000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 18000000
   Booting using the fdt blob at 0x18000000
EHCI failed to shut down host controller.
   Loading Kernel Image ... OK
   Using Device Tree in place at 18000000, end 1800d796

Starting kernel ...

undefined instruction
pc : [<88000004>]          lr : [<87f409c0>]
reloc pc : [<178c3004>]    lr : [<178039c0>]
sp : 8733acb0  ip : 0000000c     fp : 87f40b98
r10: 8733c28c  r9 : 8733aed0     r8 : 00000000
r7 : 00000000  r6 : 88000000     r5 : 87fa42b4  r4 : 00000000
r3 : 0000a797  r2 : 18000000     r1 : 00000eb9  r0 : 00000000
Flags: nZCv  IRQs off  FIQs off  Mode SVC_32
Resetting CPU ...

resetting ...
`

**Comment by tkggithub** [comment]
Hi,
At least one issue with your changes is that your mkimage arguments seem to be wrong.
Your execution address/entry point (-e) is lower than the load address (-a) so it is likely that instead of starting your optee code you start running some random instructions.
