### ISSUE TITLE
Adding RTC

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#1673]
There is a thread talking this #1352 , but I still have a question about how to update RTC that in secure world.  There is an secure RTC in i.MX platform, that I would like to use it for secure world, but if this RTC assigned to secure world, how to update the date and time for the RTC without hacking from REE. Thanks for any comments.

**Comment by jenswi-linaro** [comment]
Hi,

In #1352 you mention that there's both SRTC and an RTC. Give that I guess normal world never has a need to do anything with SRTC. In secure world we don't care that much about the actual value of SRTC, it's how much it has changed that is interesting when implementing `TEE_GetTAPersistentTime()` and `TEE_SetTAPersistentTime()`. So SRTC would never need to be updated from software, or am I missing something?

**Comment by MrVan** [comment]
@jenswi-linaro When first time power up the board, there maybe no backup power, then I have no idea how to set an initial correct value to SRTC.

**Comment by jenswi-linaro** [comment]
It depends what you'd like to do with the value. To implement `TEE_GetTAPersistentTime()` and `TEE_SetTAPersistentTime()` you need to do nothing, those only care about the relative change in SRTC.
I suppose more or less the same pattern will cover most cases we'll have in secure world. We're interested in know how much time has elapsed since an event, not what the calendar time happens to be.

**Comment by MrVan** [comment]
@jenswi-linaro I still have an issue. The normal world RTC would not survive reboots, it will lose power, but SRTC could survive reboots. The normal world RTC could sync with SRTC by setting a register. So I think need to let SRTC provide calendar time. Then need to update SRTC with correct calendar time.

**Comment by jenswi-linaro** [comment]
If SRTC is supposed to keep correct calendar time I it needs to be updated from time to time. Another option is to let normal world maintain an offset to SRTC. If normal world is will be allowed to update SRTC secure world will need to at least be notified to be able to maintain a secure world offset to SRTC. Which option is selected is platform specific. A fastcall based interface (in the SIP or OEM SMC range, see http://infocenter.arm.com/help/topic/com.arm.doc.den0028b/ARM_DEN0028B_SMC_Calling_Convention.pdf) to read/update SRTC seems a straight forward solution.

**Comment by MrVan** [comment]
From GP Internal core API spec, chaper 7.2.3, it says persistant time based on a TEE-controlled real-time clock and tee TEE Trusted storage for protection level 1000. If TEE does not care about calendar time, could we use a Monotonic counter that monotonic counter (MC) that cannot be exhausted or
returned to any previous value during the product's lifetime for TEE_GetTAPersistentTime() and TEE_SetTAPersistentTime()?

**Comment by jenswi-linaro** [comment]
You need to fulfill this also (next dot):
>  System time MUST advance within plus or minus15% of the passage of real time in the outside
 world including while the device is in low power states, to ensure that appropriate security levels
 are maintained when, for example, system time is used to implement dictionary attack protection.
 This accuracy also applies to timeout values where they are specified in individual routines.

So just a monotonic counter is not enough.

**Comment by MrVan** [comment]
Thanks. Then back to export SRTC from TEE to REE. A fastcall implementation is easy to update SRTC from REE side. I am thinking how to avoid attach by setting an old RTC time, not have a good idea(:

**Comment by jenswi-linaro** [comment]
This can be handled with an offset which is always added to the value of SRTC to get the "system time". Whenever SRTC is updated from normal world you need to update the offset to avoid changing "system time".

**Comment by MrVan** [comment]
So it seems like such an example, right?
The current SRTC time is 10000, the RTC offset is hardcoded with value 500, so the value TEE get is 10000 + 500. Then Linux update SRTC with new value 9000, then TEE needs to update RTC offset with value 500 + (10000 - 9000). Then the time TEE get is 9000(new SRTC time) + 1500(new SRTC offset), same value as before 10000(old time) + 500(old offset).

Then the RTC offset needs to be protected by secure storage, right?

**Comment by jenswi-linaro** [comment]
Yes, you're right.
From chapter 7 "Time API", below "TA Persistent Time, a real-time source of time"
> The origin of this time is set individually by each Trusted Application and MUST persist across reboots.

That's a problem since secure storage isn't available for a fastcall handler. So updates of SRTC has to go via a standard call to a Pseudo TA. These calls will be quite slow since there's going to be some RPC to secure storage.

**Comment by MrVan** [comment]
If use Pseudo TA to update SRTC, we also need to develop a Client Application in Linux side? 
My understanding is if the following could be supported is good. I do not want a CA in linux side.
Linux hwclock->SRTC OEM driver->SMC->OPTEE->Update SRTC and offset->back to linux.

**Comment by jenswi-linaro** [comment]
Yes with a Pseudo TA you'd need a kernel client.
The flow you suggest will not work as storing the offset in secure storage is a bit more complicated than that.
Another option is to never change SRTC and thus never need to store an offset in secure storage, instead normal world will keep track of it's own offset from SRTC.

**Comment by MrVan** [comment]
If let normal keep track of it's own offset, need to store the offset in a place that could survive reboots also. This makes things easier comparing to maintaining offset in secure world. Each time normal world update SRTC, it just update the normal world offset.  I'll try this. @jenswi-linaro  Thanks.
