### ISSUE TITLE
TA public/private key example

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1674]
I have a TA up and running that uses shared memory to communicate with a CA. The TA and CA are working perfectly. What I now want to do is be *sure* that when the CA calls the TA that the TA is being called and not a "man in the middle". What I was thinking was to add a private key to the TA code, and a public key to the CA code. I would then use one of the 4 parameters to pass a bit of text (let's say 1234567890) to the TA from the CA. The TA could then use the private key to encrypt the text and send the encrypted text back. The CA could now use the public key to decrypt the text - if what was sent (1234567890) was not what was received back from the TA after decryption we have an imposter pretending to be the TA.

This is what I mean:

CA sends 1234567890 in param 1 to the TA
TA encrypts 1234567890 using the private key and places the answer in param 2
CA decrypts parameter 2 using the public key and checks that param 1 == param 2

This is example C the code that I found to do something link this: http://hayageek.com/rsa-encryption-decryption-openssl-c/ using openSSL. 

I read in the slides here: https://s3.amazonaws.com/connect.linaro.org/bkk16/Presentations/Monday/BKK16-110.pdf (slide 15) that I could use Asymmetric Encryption and Decryption from the TEE core APIs to do this and have looked at the tee_api_operations.c file but it is all a bit complicated if you are just starting out. 

Does anybody have an example of how I could go about doing the above? Or have I totally misunderstood and there is some other way I can check if I am actually talking to "my" TA?

Thank you for any help given.
Ursus

**Comment by jforissier** [comment]
Hi @ursus-the-bear,

I don't have a simple example to provide, unfortunately. For the encryption step, the TA functions you're looking for are: `TEE_AllocateOperation()`, `TEE_SetOperationKey()`, and `TEE_AsymmmetricEncrypt()`. The key should probably come from secure storage. Don't store it in clear in the TA binary! it would be quite easy to hack. Instead, implement a command in your TA to save the keypair once (provisioning step). For that you would use `TEE_CreatePersistentObject()`. It's quite possible you would also need `TEE_AllocateTransientObject()` and `TEE_PopulateTransientObject()` to create an object from the raw key material, before making it a persistent object (I don't remember exactly how it's supposed to work). When you need the key you would read it with `TEE_OpenPersistentObject()`, and you would pass this object to `TEE_SetOperationKey()`, then call `TEE_AsymmetricEncrypt()`.

For more details, please look at `xtest_tee_test_4006()` ([here](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000.c#L3734)), it is a regression test for all kinds of asymmetric crypto cases. As for the secure storage (persistent objects), the tests are in `regression_6000.c`. That's for the client side (CA). The corresponding TAs are https://github.com/OP-TEE/optee_test/tree/master/ta/crypt (for the crypto) and https://github.com/OP-TEE/optee_test/tree/master/ta/storage (for the secure storage). With this and the GP Internal Core API specification, you should be able to figure out something hopefully.

**Comment by ursus-the-bear** [comment]
Thank you very much for the pointers I’ll check it out tomorrow 😊

**Comment by igoropaniuk** [comment]
Hi @ursus-the-bear 
Maybe it's a bit off-topic, but the main problem is in your scheme is that the whole REE is insecure by definition, including all CAs.

Even if you add any functionality for decrypting in your CA, it will be possible for someone to inject additional code into your CA (for example, the function which de-crypts data from TA and verifies its identity, can be hooked with some "stab"-function, which simply will return true in any case)

So, frankly speaking, there is something wrong in all whole scheme. All decision making code, that you want to be secured - should be run in TEE. Or maybe I just misunderstood want actually you need to do.

>This is example C the code that I found to do something link this: http://hayageek.com/rsa-encryption-decryption-openssl-c/ using openSSL.

OpenSSL is used for a bit different case, where we assume that (ok, we also have authentication of the identity of the server with a chain of certificates) both client and server are secure (so, basically, it's kind of defense of **external** traffic sniffing). It won't help, if you will have some malware on your pc, which, for example, will simply hook `SSL_read()`/`SSL_write()` functions (for example, LD_PRELOAD "hack" which allows you to tell the linker to bind symbols provided by a certain shared library before other libraries)

BR,
Igor

**Comment by ursus-the-bear** [comment]
@igoropaniuk Thank you for taking the time to answer. I do have a problem if a hacker where to inject code into the CA *and*  pretend to be the TA at once... If just one of these things is done, eg. inject code into the CA I would notice as the TA checks the MD5 of the CA (which the CA calculates on each call and passes to the TA, the CA does not know the "correct" MD5 as it is stored in the TA) on each call and I would do a system shutdown. If the attacker pretends to be the TA I would notice it as the CA would get the incorrect data when it decrypts and also shutdown. It's not a perfect system but I am just learning TAs - very interesting all in all :)
