### ISSUE TITLE
gdb hangs when debugging

### ISSUE THREAD

**Issue by LoicH** [OP-TEE/optee_os#1675]
Hello, I followed the process described here: https://github.com/OP-TEE/build/blob/master/docs/debug.md#14-debug
gdb can interrupt the emulation fine when I launch `hello_world` for instance, but I can not make gdb resume the execution, whether by typing `c`, `s` or `n`, gdb simply hangs and nothing happens.
When gdb hangs, I can not stop gdb by pressing Ctrl-C, I can press Ctrl-Z and then kill gdb.

I have the same problem on Ubuntu 16.04 and Lubuntu 16.04.

Do you have an idea on how to solve this problem? Or another way of debugging Trusted Applications?

**Comment by LoicH** [comment]
Follow up: when I remove the line 	`handle SIGTRAP noprint nostop pass`, from `~/.gdbinit`, gdb acts fine, but I can't pinpoint which signal handling causes gdb to hang, because I tried to `handle` them one by one but I couldn't reproduce the hang without handling the 4 signals at once. Maybe it's one special combination of these signals that causes gdb to hang?

Anyway, I don't understand why, but my issue seem solved.

By the way, have you got any resource on how to debug a Trusted Application, like the TA for `hello_world`: 8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta?

**Comment by jbech-linaro** [comment]
@LoicH , still an issue? I've used GDB quite a bit the last week and I haven't seen any issues (I'm running QEMU v7).

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.

**Comment by igoropaniuk** [comment]
@jbech-linaro @LoicH 
Reproduced the same issue a few days ago (didn't spend much time on this, as was leaving the office and then simply forgot about this case)

In two words, gdb is hanging after the first breakpoint is hit (it's possible to receive backtrace, print source code line etc) and after that execution is resumed (`c`). So, basically, after `c` gdbserver just becomes unresponsive.

Will try to reproduce and provide more details today.
