### ISSUE TITLE
Confusion about set_alias_area() during pager initialization

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#1676]
If pager is enabled, the tee_pager_init() function will call the set_alias_area() function to clear the mappings in the alias area (pager_alias_tbl_info). The pager_alias_tbl_info points to the L2 translation table which maps the top TZSRAM_SIZE virtual address of tee_mm_vcore (we can see this from the code below). 

```
//Quoted from intit_runtime function
mm = tee_mm_alloc2(&tee_mm_vcore, (vaddr_t)tee_mm_vcore.hi - TZSRAM_SIZE, TZSRAM_SIZE);

//Quoted from set_alias_area function
if (!ti->num_entries && !core_mmu_find_table(smem, UINT_MAX, ti)) //smem is the base address of mm
		panic("Can't find translation table");
```

The tee_mm_vcore is a memory pool contains the virtual address space of TEE kernel. Its start address is CFG_TEE_RAM_START, and its total size is `CFG_TEE_RAM_VA_SIZE `(1M). 

However, after looking through the MMU mapping initialization code (`core_init_mmu_map`), I find that OP-TEE only maps the following memory region:
```
#ifdef CFG_CORE_RWDATA_NOEXEC
register_phys_mem(MEM_AREA_TEE_RAM_RX, VCORE_UNPG_RX_PA, VCORE_UNPG_RX_SZ);
register_phys_mem(MEM_AREA_TEE_RAM_RO, VCORE_UNPG_RO_PA, VCORE_UNPG_RO_SZ);
register_phys_mem(MEM_AREA_TEE_RAM_RW, VCORE_UNPG_RW_PA, VCORE_UNPG_RW_SZ);
#ifdef CFG_WITH_PAGER
register_phys_mem(MEM_AREA_TEE_RAM_RX, VCORE_INIT_RX_PA, VCORE_INIT_RX_SZ);
register_phys_mem(MEM_AREA_TEE_RAM_RO, VCORE_INIT_RO_PA, VCORE_INIT_RO_SZ);
#endif
#else
register_phys_mem(MEM_AREA_TEE_RAM, CFG_TEE_RAM_START, CFG_TEE_RAM_PH_SIZE);
#endif
register_phys_mem(MEM_AREA_TA_RAM, CFG_TA_RAM_START, CFG_TA_RAM_SIZE);
register_phys_mem(MEM_AREA_NSEC_SHM, CFG_SHMEM_START, CFG_SHMEM_SIZE);
```

From above regions, we can see that the physical memory for the kernel start from `CFG_TEE_RAM_START`, and the total size is  `CFG_TEE_RAM_PH_SIZE`. As OP-TEE uses identity mapping, the virtual address that the translation table maps for the kernel starts from `CFG_TEE_RAM_START `to `CFG_TEE_RAM_START + CFG_TEE_RAM_PH_SIZE`, but not to `CFG_TEE_RAM_START  + CFG_TEE_RAM_VA_SIZE `.

Question: as the translation table does not map the virtual address higher than `CFG_TEE_RAM_START  + CFG_TEE_RAM_PH_SIZE `, I think the `core_mmu_find_table()` function in the `set_alias_area() ` does not return true, as current L1 translation table doesn't contain a L2 translation table that maps the  top virtual address of tee_mm_vcore, i.e., the virtual address higher than `CFG_TEE_RAM_START  + CFG_TEE_RAM_PH_SIZE `. The virtual address range of the kernel is listed in the following picture.
My second question is : what is the alias area (pager_alias_tbl_info) used for?

```
Address range of the kernel

-------------// CFG_TEE_RAM_START  + CFG_TEE_RAM_VA_SIZE
|           |
|           |
-------------- // CFG_TEE_RAM_START  + CFG_TEE_RAM_PH_SIZE
|           |
|           |
------------- //CFG_TEE_RAM_START 
```
```
//set_alias_area function
if (!ti->num_entries && !core_mmu_find_table(smem, UINT_MAX, ti)) //smem is the base address of mm
		panic("Can't find translation table");
```

**Comment by jenswi-linaro** [comment]
This behavior is being changed in https://github.com/OP-TEE/optee_os/pull/1669

The alias area is used to keep the physical pages used for paging accessible when populating the pages at new virtual addresses.

**Comment by TEE-OS** [comment]
Thanks for your reply, @jenswi-linaro . 
After viewing the changes in #1669 , I find that the pager of OP-TEE is changed a lot, especially the MMU related functions. Is there anyplace that I can download the OP-TEE patched by #1669?

**Comment by jenswi-linaro** [comment]
https://github.com/jenswi-linaro/optee_os/tree/large_tee_ram_va_size

I wouldn't agree that it has changed a lot, it's just a little more flexible with regards to translation tables.

**Comment by TEE-OS** [comment]
If `CFG_TEE_RAM_VA_SIZE `is defined as 1M, then the L2 translation table that maps the alias area is the same table that maps `CFG_TEE_RAM_START`,  so the `core_mmu_find_table()` will return correctly.
