### ISSUE TITLE
Inter TA Communication

### ISSUE THREAD

**Issue by sarju32** [OP-TEE/optee_os#1679]
Hi @MrVan  @jenswi-linaro @jbech-linaro @jforissier 

Currently working to port a RTOS application as OP-TEE TA. 
In the RTOS application, the communication between two tasks is achieved through following RTOS resources available.
1. Queues
2. Event

Would like to know how above can be achieved in TA of OPTEE OS?
Is TA a single monolithic code ?

Are threads, queues and events are available in OPTEE OS for TA? As far as my exploration in OPTEE documentation understanding these resources are not available. Please clarify.

**Comment by jenswi-linaro** [comment]
Regarding threads etc, see https://github.com/OP-TEE/optee_os/issues/1678

To me it sounds like you have a design that fits well into an RTOS. In TEE context are TAs passive components that requires normal world to drive things so a TA environment isn't really a good match against the environment of an entire RTOS.

**Comment by sarju32** [comment]
@jenswi-linaro I read it from a FAQ page of OP-TEE, https://www.op-tee.org/faq/
there is some concept TA2TA for doing parallel or multi tasks. How it can be done. 
Can't able to find any resources from online regarding the concept.
Any simple TA examples that shows about the usage of TA2TA interface.

**Comment by vchong** [comment]
See if Section 4.9 Internal Client API of the TEE Internal Core API Specification v.1.1.1 at https://www.globalplatform.org/specificationsdevice.asp helps.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
