### ISSUE TITLE
Booting OP-Tee on iMX6 Solo

### ISSUE THREAD

**Issue by serusako** [OP-TEE/optee_os#1685]
Hi,
OPTee documentation does not mention iMX6 Solo as supported platform, neither is iMX6 Dual and DualLite.
I have successfully booted OP-Tee on  iMX6 Dual and DualLite, but not on iMX6 Solo.
OP-Tee seems to hang in the following function cpu_mmu_enable() in proc_a32.S called from generic_entry_a32.S(390)
Perhaps there is a reason iMX6UL is supported, but iMX6S is not ?
Thanks,
Sergey

**Comment by serusako** [comment]
Since other iMX6 flavors are not currently in OP-Tee build configurations, here are changes I made to add them - including Solo

conf.mk
...
# Get SoC associated with the PLATFORM_FLAVOR
mx6ul-flavorlist = mx6ulevk
mx6q-flavorlist = mx6qsabrelite mx6qsabresd mx6qhmbedge
mx6d-flavorlist = mx6dhmbedge
mx6dl-flavorlist = mx6dlsabresd mx6dlhmbedge
mx6s-flavorlist = mx6shmbedge
...

and here is how tee.bin is built for Solo

~/optee_os$ make PLATFORM=imx-mx6shmbedge CFG_NS_ENTRY_ADDR=0x10820000 CFG_TEE_CORE_LOG_LEVEL=4 CFG_REE_FS=n CFG_RPMB_FS=y CFG_RPMB_TESTKEY=y CFG_TA_HELLO_WORLD=y DEBUG=1

**Comment by MrVan** [comment]
imx6solo almost same with imx6duallite, with major difference that solo is one core, duallite if dual core. I do not have a solo board, could you try this patch?
```
diff --git a/core/arch/arm/plat-imx/sub.mk b/core/arch/arm/plat-imx/sub.mk
index 90df123..81c5b7f 100644
--- a/core/arch/arm/plat-imx/sub.mk
+++ b/core/arch/arm/plat-imx/sub.mk
@@ -5,7 +5,7 @@ srcs-$(CFG_PL310) += imx_pl310.c
 srcs-$(CFG_PSCI_ARM32) += psci.c gpcv2.c
 cflags-psci.c-y += -Wno-suggest-attribute=noreturn
 
-ifneq (,$(filter y, $(CFG_MX6Q) $(CFG_MX6D) $(CFG_MX6DL)))
+ifneq (,$(filter y, $(CFG_MX6Q) $(CFG_MX6D) $(CFG_MX6DL) $(CFG_MX6S)))
 srcs-y += a9_plat_init.S imx6.c
 endif
 
```

**Comment by serusako** [comment]
Hello MrVan,
thank you for your reply. I have applied your patvh, you are correct I missed that in my code changes. This patch helps to address hang in proc_a32.S and code execution continues further, but then optee hangs somewhere else.

I have developed a workaround. It is not in optee, but rather in iMX6 Solo u-boot. I do not know why it makes a difference, but if iMX6 Solo u-boot is built with memory size 1 Gb then everything works fine.

**Comment by MrVan** [comment]
You need to decrease the memory that uboot used. To i.mx6, we usually make optee runs at high memory. When uboot is running, uboot will relocate itself to high memory. So you need to make sure there is no conflict between uboot and optee memory.  Check the uboot [patch](https://github.com/MrVan/u-boot/commit/503c4c87a1182b58331445e79f0067ed9285101a).
