### ISSUE TITLE
Secure mapping attribute is missing in core_mmu_map_pages.

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1686]
I find two problems:
1.   In core_mmu_divide_block,  if the section(page table) entry is an invalid entry, it will be divided into invalid page entries with secure attribute set in the page table entry by default.
2.   In core_mmu_map_pages, only the specified page entries are changed, but the secure attribute is set only in the page table entry and it is missing.

possible solution:
1.  Add return args in core_mmu_divide_block,  this arg returns if the divided block is a new empty block. 
2.  when the divided block is new, set the secure attribute in the page table entry.
3.  when the divided block is not new,  check the secure attribute conflict and if no conflict then set the page entries.

But i think add a new arg in core_mmu_divide_block is a little change, maybe we can introduce a new function to check whether it's a new block?
Any suggestion?
Thank you.

**Comment by jenswi-linaro** [comment]
I assume we're talking about the implementation in `/core/arch/arm/mm/core_mmu_v7.c`.

Another curious thing is that `core_mmu_divide_block()` is only called from `core_mmu_map_pages()` and if the section that is to be replaced with a l2 table contains a valid mapping, then core_mmu_map_pages() will panic later as the virtual addresses already holds a mapping.

Next problem is that `core_mmu_map_pages()` is only used to map non-secure shared memory so this function will always map non-secure memory as secure when not using LPAE.

So far I think that this code isn't actually used, it's just preparations for https://github.com/OP-TEE/optee_os/pull/1631 .

Given how `core_mmu_divide_block()` is used in practice I think this function is overkill.  `core_mmu_map_pages()` requires (indirectly) the entry to be populated with a finer grained table to be empty. Why not take the easy way and populate an empty finer grained table instead (with correct attributes)? At the same time we should add a check in `core_mmu_map_pages()` to see that we can map with the given security attribute at that address.

I propose to replace `core_mmu_divide_block()` with something like
```
bool core_mmu_add_new_table(struct core_mmu_table_info *tbl_info,
                            unsigned int idx, uint32_t attr);
```

Comments? @lorc?

**Comment by prime-zeng** [comment]
@jenswi-linaro  i think core_mmu_add_new_table is  really a good idea.
