### ISSUE TITLE
Discuss: introducing DECLARE_RT_SVC for ARM32

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#1688]
Checking the ATF code, there is DECLARE_RT_SVC for difference services, so I am thinking to introduce that in OP-TEE for ARM32.  Then we could also add SID or OEM services in ARM32 SM. Now there is a check in sm_from_nsec for PSCI, but if we could use the way in ATF which seems better and easy to implement SIP or OEM services.  Welcome comments.

**Comment by jenswi-linaro** [comment]
When it comes to the secure monitor this is the priority:
1. Don't add overhead for platforms that don't need it
2. Minimize overhead for the common case
3. Convenience versus amount of memory used
