### ISSUE TITLE
Why don't add the SRAM from __pageable_end to the end of SRAM to pager?

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#1689]
In the end of the `init_runtime()` function, the physical SRAM pages from `__pageable_start `to `__pageable_end `are added to the pager area that can be used by pager to map new pages.
```
tee_pager_add_pages((vaddr_t)__pageable_start,
		init_size / SMALL_PAGE_SIZE, false);
tee_pager_add_pages((vaddr_t)__pageable_start + init_size,
		(pageable_size - init_size) / SMALL_PAGE_SIZE, true);
```

Why don't add the SRAM pages from `__pageable_end `to the end of the SRAM `(CFG_TEE_RAM_START+CFG_TEE_RAM_PH_SIZE)`  to the pager area? Then the pager can leverage more SRAM memory to map pages.

**Comment by jenswi-linaro** [comment]
That's a valid point, especially now that we can page TAs too.

**Comment by TEE-OS** [comment]
What about add the following line of code in the end of init_runtime().
```
tee_pager_add_pages((vaddr_t)__pageable_end,
		(CFG_TEE_RAM_START+CFG_TEE_RAM_PH_SIZE - __pageable_end) / SMALL_PAGE_SIZE, true);
```

**Comment by jenswi-linaro** [comment]
Looks good, but we have to make sure that the memory is mapped also or it wouldn't help much.
See below https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/core_mmu.c#L94

**Comment by TEE-OS** [comment]
From the code and kernel linker script, it seems right. I will test it in a real environment to make sure that the code is correct.
