### ISSUE TITLE
Query: How to verify "TEEC_OpenSession()" with TEEC_LOGIN_APPLICATION login method?

### ISSUE THREAD

**Issue by ajithpv** [OP-TEE/optee_os#1690]
Hi,
I want to open a session with some level of security and it should not be TEEC_LOGIN_PUBLIC.
The close one which I'm looking for is TEEC_LOGIN_APPLICATION and I hope this one is already supporting and working in OP-TEE. 

But, I didn't get how one can verify it is actually working with TEEC_LOGIN_APPLICATION or with TEEC_LOGIN_PUBLIC since both have "connection data" as NULL.

So, I would like to get some example where the TEEC_OpenSession() login method is TEEC_LOGIN_APPLICATION instead of TEEC_LOGIN_PUBLIC and what will be the difference.

**Comment by jenswi-linaro** [comment]
Hi,

To be able to help you I need to know a bit more about what you trying to achieve.
What do you mean with "some level of security" and why is `TEEC_LOGIN_APPLICATION` better than `TEEC_LOGIN_PUBLIC` in your use case?

**Comment by ajithpv** [comment]
Thank you @jenswi-linaro for your quick reply.

I must say that, I'm still at a design phase and not started implementing the application(s). But, at this point of time, what I can say is that _the credentials generated for the application MUST only depend on the identity of the application program, and not the user running it. Also, we need to have a login method in our case._

Please let me know whether TEEC_LOGIN_APPLICATION is already supporting and working in OP-TEE.

**Comment by jenswi-linaro** [comment]
That's not supported in normal world, there's support for it in the secure world part though.
Note that the level of security provided by the supplied `connectionMethod` can never exceed the level of security in normal world, so from secure world point of view it's not secure.

The specification you cited also recommends:
>If a Trusted Application requires a static login credential then this can be passed by the Client Application using the standard Shared Memory mechanisms for data exchange.

**Comment by prime-zeng** [comment]
I think the `gpd.client.identity `can be used to support the TEEC_LOGIN_XXX rather then the `connectionMethod`, and as jens said , the security level will never exceed the normal world, but i think it's still useful,  the normal world has the kernel and userspace security level difference. My suggestion is to implement the `gpd.client.identity` in the tee driver which is relative more secure.

**Comment by jenswi-linaro** [comment]
@prime-zeng, yes that's a possibility but how can the kernel identify the application? We need to take upgrades of the application into account also. This seems like a problem that should be solved at a higher level, for instance at AOSP level.

**Comment by prime-zeng** [comment]
Agree, the essential problem is how the kernel identify the app, but from the OP-TEE point of view, we have to support passing the identity information from tee driver to the TA.

**Comment by jenswi-linaro** [comment]
Yes, we could have a hook in `optee_open_session()` or even `tee_ioctl_open_session()` if we first check `TEE_GEN_CAP_GP`. That's the easy part.
