### ISSUE TITLE
Makefile for TA

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1694]
Hi.

I would like to refactor my TA code that is currently in one big file into a couple of smaller ones. I had no problem working this out for the CA (i.e. in the host folder) but cannot seem to get it right for the TA. 

I currently have the file fim_ta.c and fim_ta.h that contains all my code. Here is my Makefile:

```   
    CFG_TEE_TA_LOG_LEVEL ?= 4

    CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL) -I$(TEEC_EXPORT)/include

    # The UUID for the Trusted Application
    BINARY=361142ae-ec3e-4576-8883-a6c0f6c6ec71

    include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
```

I have also updated the common.mk to include my fim file:

```   
...
FIM_PATH ?= $(ROOT)/fim
...
optee-os-clean-common: xtest-clean helloworld-clean fim-clean
...
FIM_COMMON_FLAGS ?= HOST_CROSS_COMPILE=$(CROSS_COMPILE_NS_USER)\
       TA_CROSS_COMPILE=$(CROSS_COMPILE_S_USER) \
       TA_DEV_KIT_DIR=$(OPTEE_OS_TA_DEV_KIT_DIR) \
       TEEC_EXPORT=$(OPTEE_CLIENT_EXPORT)
fim-common: optee-os optee-client 
       $(MAKE) -C $(FIM_PATH) $(FIM_COMMON_FLAGS)

FIM_CLEAN_COMMON_FLAGS ?= TA_DEV_KIT_DIR=$(OPTEE_OS_TA_DEV_KIT_DIR)

fim-clean-common:
      $(MAKE) -C $(FIM_PATH) $(FIM_CLEAN_COMMON_FLAGS) clean
...
filelist-tee-common: optee-client xtest helloworld fim

```

what would I need to add to, for example, have the code split into 6 files, fim_ta.c/h auth.c/h and files.c/h? I cannot seem to get the Makefile right no matter what I try and glean from the host/Makefile.

Thank you for any help given
Ursus

**Comment by jforissier** [comment]
Hi @ursus-the-bear,

You need to add all the source (`*.c`) files for your TA to `sub.mk` which has to be in the same directory as the TA Makefile (the one that has `BINARY=...` and `include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk`).
See for instance https://github.com/OP-TEE/optee_test/blob/master/ta/crypt/sub.mk.

**Comment by ursus-the-bear** [comment]
Thank you - will try it ASAP and report back here!

**Comment by ursus-the-bear** [comment]
Yip - that was it. Not sure why I missed it but thank you :)
