### ISSUE TITLE
Calling GPIO OP-TEE OS driver through TA

### ISSUE THREAD

**Issue by sarju32** [OP-TEE/optee_os#1695]
Hi,

We have a TA which main purpose is to get the status of GPIO status number from Pinpad(i.e) when Pinpad is pressed TA has to get the status of its GPIO number

We have a GPIO driver in OP-TEE core OS and we have registered the driver through **driver_init** call and its under core/drivers/ directory. Now driver is initialized and running.  But now we are stuck up with how to make a call to GPIO driver from the TA. I want to call **gpio_set_direction** function from driver to get the GPIO status 

Learned that from Dynamic TA to make a call to OP-TEE OS core its has go through like below flow..

**"TA function call -> libutee(tee_api_func_name.c) -> syscall(utee_syscalls_asm.S) -> SYSCALL_ENTRY table(arch_svc.c) -> call the respective syscall API"**
Is our understanding correct ?

We understood till it calls syscall API but can't able to figure out the flow that need to be done to make it through till final driver calls.

We cant able to find any examples. 

Any suggestions would be helpful. If you have any simple example which explains this, please share with us

**Comment by vchong** [comment]
The recommended way is to have your Dynamic TA communicate with a Pseudo TA using the Internal Client API (TA to TA communication) and have the Pseudo TA call the gpio functions. This way you don't need to mess with the syscalls and can use standard (GlobalPlatform) API calls from secure user space to secure kernel space (optee_os core). Pseudo TA is part of optee_os core so it can access the gpio functions directly.

Just curious, how are you preventing normal world from changing the GPIO status?

**Comment by sarju32** [comment]
Thanks for the quick response. Can you please share any examples thats shows the mechanism to call Dynamic TA to Pseudo TA through TA-to-TA interface.
I can able to find TA-to-TA communication in Dynamic TA, but cant find a one between Dynamic TA to Pseudo TA.

**Comment by vchong** [comment]
Don't think there are any examples here atm. Just refer to Section 4.9 of the GP TEE Internal Core API spec v1.1.
