### ISSUE TITLE
scanf, printf for floating point ? is FPU supported in OPTEE?

### ISSUE THREAD

**Issue by jeffy1009** [OP-TEE/optee_os#1697]
I think scanf, printf for float is not supported in OP-TEE, right?
Is floating point arithmetic allowed in OP-TEE?
We don't need absolute precision so we're thinking of implementing a simple one.

**Comment by jenswi-linaro** [comment]
OP-TEE doesn't have `scanf()`. `printf()` doesn't support floating point variables.
In Trusted Applications there's support for floating point (hard or soft depending on configuration) arithmetic, but still no support to print the variables.

**Comment by jeffy1009** [comment]
Thank you for your answers!
