### ISSUE TITLE
Semaphore, Thread and Mutex in Trusted Application

### ISSUE THREAD

**Issue by ranjithvs** [OP-TEE/optee_os#1699]
Hi all,
  
    I am porting some application from RTOS to Secure World. I wanted to know how we can do semaphore, thread and mutex handling or implementation in the Trusted Application (in TA side).

If any examples that will be a great help for me.

Thank you,

**Comment by jenswi-linaro** [comment]
Is this related to https://github.com/OP-TEE/optee_os/issues/1679
