### ISSUE TITLE
Timer support in OP-TEE

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1701]
Hi all:

For many security scenario, we need periodicly do same security checking job, or as the heartbeats of the secure world,  so the first choice is the periodic timer, and this is currently missing the OP-TEE, since the timer hardware is different from platform to platform,  to simplify the jobs, any suggestion about introduce a timer framework in the OP-TEE. 

Thanks.

**Comment by jenswi-linaro** [comment]
Sounds good. When the timer expires I suppose a function will be called in native interrupt context.

**Comment by MrVan** [comment]
@prime-zeng Would you mind give more details about checking security job periodicly? Just as @jenswi-linaro said, enable the native interrupt for the timer that assigned to secure world, when timer expires, the interrupt handler could be used for security checking job. Taking power things into consideration, suspend/resume also needs to be added cpu_suspend/cpu_resume of thread handlers if you are using ATF.

**Comment by igoropaniuk** [comment]
@prime-zeng 
what about ARM Generic Timer extension? (ARM core internal timer, not SoC Timer)
It's available starting  from cortex-a15, there is a PL1 physical timer, where registers are banked to provide Secure and Non-secure copies

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0438c/BABIGHII.html
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0438f/BABIGHII.html
https://stackoverflow.com/questions/25111804/arm-timer-interrupt-arm-arch-timer
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings/arm/arch_timer.txt

**Comment by prime-zeng** [comment]
The ARM Generic Timer can be a default choice of the hardware implemenation, and here we are talking about the general timer framework which lays on top of the hardware layer,  in fact, i don't i have idea about how the timer framework looks like, and do we need to provide posix timer syscall to TAs? 
And about the periodical job,   the runtime integrity check is typical usecase.

**Comment by jenswi-linaro** [comment]
I can't see any reason that a TA would need to access this, so no posix timer syscall to TAs.

**Comment by igoropaniuk** [comment]
@prime-zeng yeap, I got your idea, I just wanted to add that using ARM generic timer extension is more suitable then using SoC-specific timers, as it will definetely simplify timer framework implementation + enabling support of this framework on different SoCs
