### ISSUE TITLE
Query regarding OP-TEE OS execution from memory space > 4G (32 bit) on armv8 platforms

### ISSUE THREAD

**Issue by b49020** [OP-TEE/optee_os#1702]
I was looking at MMU for ARMv8 on OP-TEE OS. So I found following assert regarding check on ADDR space size:
**assert(max_va < CFG_LPAE_ADDR_SPACE_SIZE);**
Also CFG_LPAE_ADDR_SPACE_SIZE ?= (1ull << 32) in core/arch/arm/arm.mk file.
It seems that currently OP-TEE OS supports 32 bit address space for ARMv8.
So is there any plan to support 64 bit address space in armv8 for OP-TEE OS?

**Comment by jenswi-linaro** [comment]
We'd like to support running OP_TEE OS from addresses above 4G, but it's not something we're working actively with. Patches are welcome.

**Comment by b49020** [comment]
@jenswi-linaro Thanks for the info. Actually we are working on NXP's ARMv8 based platform support for OP-TEE. But DDR range carved out for secure memory on this platform lies in address range > 4G. So to support this we will try to add support for high memory range in OP-TEE.
