### ISSUE TITLE
Question: how to ioremap_nocache()?

### ISSUE THREAD

**Issue by dryvenn** [OP-TEE/optee_os#1709]
Hi everybody,
I've got a question regarding dynamic uncached MMU mappings:

On my board I have another CPU, totally different from the one running OP-TEE. It's a MIPS which doesn't even run Linux, but has access to the main memory. It has a higher security level than the main CPU.
I must communicate with it from optee_os, using a protocol I can't change, which relies on writing messages in a mailbox whose location isn't known at compile time.

1. How do I create/destroy uncached MMU mappings from optee_os in kernel mode?

Furthermore, I must create several mailboxes myself from optee_os. I thought about invoking malloc() and then simply pass the physical address of the buffer to the other processor. But the mailbox messages would be trapped in L1/L2 caches, which would compel me to flush every time I have a message to pass.

2. How do I create an uncached mapping for a piece of optee_os' own memory?

I've looked at include/mm/core_mmu.h, and the only things that remotely look like what I need are core_mmu_map_pages(),  but that requires to know the virtual address in advance, or core_mmu_add_mapping(), but I don't see an unmap counterpart.
I've also seen include/mm/mobj.h, but I couldn't figure out the purpose of this file.

Any help appreciated, thanks!

**Comment by jenswi-linaro** [comment]
Do you really need dynamic mapping/unmapping of uncached memory? Is the range of physical memory that can be used by the MIPS CPU completely unpredictable?

If static mapping isn't an option then I you'll need to add something yourself. This is something we'd like to have in OP-TEE, but haven't come around to implement yet.

**Comment by dryvenn** [comment]
Yes unfortunately, the location of the mailboxes is entirely at the discretion of the MIPS CPU. I mean in practice I could predict an address range because I know the architecture and the current setup, but a different setup would completely invalidate this.
Furthermore, if my optee_os starts creating those mailboxes, I would have to statically iomap its entire memory, and I'm not comfortable with that.

I can try implementing that myself. Any advice on how to proceed?

**Comment by jenswi-linaro** [comment]
I think starting with `core_mmu_add_mapping()` and enhancing it is the way to go. You'll need to add a `tee_mm_pool_t` to manage the virtual addresses assigned for `MEM_AREA_RES_VASPACE`.

**Comment by dryvenn** [comment]
Thanks @jenswi-linaro .

Unfortunately I don't have the time right now to do this properly. FYI, I ended up reserving a part of memory and statically IO-mapping it so that optee_os can create mailboxes within it.
