### ISSUE TITLE
setup Foundation Models-"4.2.2 Download and setup FVP"

### ISSUE THREAD

**Issue by haitao52198** [OP-TEE/optee_os#171]
killer@killer-VirtualBox:~/fvp$ ./setup_fvp_optee.sh
FVP must be downloaded first, please go to: 
  http://www.arm.com/products/tools/models/fast-models/foundation-model.php
When done, install it on this path:
  /home/killer/devel/fvp_optee/Foundation_Platformpkg
Then open this script (setup_fvp_optee.sh) and change the line from saying:
  SRC_FVP=     to      SRC_FVP=1
killer@killer-VirtualBox:~/fvp$ 

What's happened on my ubuntu14.04，I can't setup FVP,thanks you!

**Comment by jbech-linaro** [comment]
Hi,

What is the error message you are facing? Could you please paste that? The complete log would be good to have.

**Comment by vchong** [comment]
Hi Haitao,

Are you running setup_fvp_optee.sh and expecting it to setup FVP for you? The script is to setup OP-TEE to run on FVP. It does NOT setup FVP for you. You have to setup FVP first manually by yourself, as the message says, by going to http://www.arm.com/products/tools/models/fast-models/foundation-model.php, downloading it and then installing it on /home/killer/devel/fvp_optee/Foundation_Platformpkg. Then change "SRC_FVP=" to "SRC_FVP=1" in the file setup_fvp_optee.sh. Only after that, you should run setup_fvp_optee.sh.

**Comment by haitao52198** [comment]
@vchong  Yes,I'm trying to run setup_fvp_optee.sh,and then print these message,so I have chage the "SRC_FVP=" to "SRC_FVP=1" before manually setup FVP.I think I need to setup FVP first now.Thanks you!

**Comment by haitao52198** [comment]
@jbech-linaro  That is all the message,vchong's answer is very clearly.Thanks you all the same!
