### ISSUE TITLE
[Error] non-sec DDR configuration on I.MX6Q

### ISSUE THREAD

**Issue by 1000liview** [OP-TEE/optee_os#1710]
Hi,

When I run OP-TEE 2.5.0 on I.MX6Q, It has the booting error below.

INFO:    TEE-CORE: 
DEBUG:   [0x0] TEE-CORE:init_canaries:169: #Stack canaries for stack_tmp[0] with top at 0x4e0627f8
DEBUG:   [0x0] TEE-CORE:init_canaries:169: watch *0x4e0627fc
DEBUG:   [0x0] TEE-CORE:init_canaries:169: #Stack canaries for stack_tmp[1] with top at 0x4e062ef8
DEBUG:   [0x0] TEE-CORE:init_canaries:169: watch *0x4e062efc
DEBUG:   [0x0] TEE-CORE:init_canaries:169: #Stack canaries for stack_tmp[2] with top at 0x4e0635f8
DEBUG:   [0x0] TEE-CORE:init_canaries:169: watch *0x4e0635fc
DEBUG:   [0x0] TEE-CORE:init_canaries:169: #Stack canaries for stack_tmp[3] with top at 0x4e063cf8
DEBUG:   [0x0] TEE-CORE:init_canaries:169: watch *0x4e063cfc
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_abt[0] with top at 0x4e064538
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x4e06453c
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_abt[1] with top at 0x4e064d78
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x4e064d7c
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_abt[2] with top at 0x4e0655b8
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x4e0655bc
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_abt[3] with top at 0x4e065df8
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x4e065dfc
DEBUG:   [0x0] TEE-CORE:init_canaries:172: #Stack canaries for stack_thread[0] with top at 0x4e067e38
DEBUG:   [0x0] TEE-CORE:init_canaries:172: watch *0x4e067e3c
DEBUG:   [0x0] TEE-CORE:init_canaries:172: #Stack canaries for stack_thread[1] with top at 0x4e069e78
DEBUG:   [0x0] TEE-CORE:init_canaries:172: watch *0x4e069e7c
DEBUG:   [0x0] TEE-CORE:add_optee_dt_node:406: OP-TEE Device Tree node already exists!
ERROR:   [0x0] TEE-CORE: Panic at core/arch/arm/kernel/generic_boot.c:571 <get_memory>
ERROR:   [0x0] TEE-CORE: pc  0x4e004965
ERROR:   [0x0] TEE-CORE: pc  0x4e009d85
ERROR:   [0x0] TEE-CORE: pc  0x4e0041f9
ERROR:   [0x0] TEE-CORE: pc  0x4e00010c

When I check the commit history, the error happens due to "core: assign non-sec DDR configuration from DT (490c50dfdb33759ca0ba63526e8b173222b5568b)"
It seems that this commit works only on some specific board.
How can fix this commit to work on I.MX6Q board ? Kernel version is 4.1.15.

Thanks,
CHOLLIAN

**Comment by MrVan** [comment]
@1000liview Could you try this patch in Linux side, and see whether it fixes your issue?
```
        memory: memory {
                reg = <0x10000000 0x40000000>;
+               #address-cells = <1>;
+               #size-cells = <1>;
        };
```
