### ISSUE TITLE
Query regarding Queuing Multiple TAs

### ISSUE THREAD

**Issue by sarju32** [OP-TEE/optee_os#1713]
Hi @MrVan @jenswi-linaro @jbech-linaro @jforissier ,

**Would like to know how to register a Dynamic TAs or Pseudo TAs in a wait queue and wake
through RPC** 
We have multiple TAs. One TA will be in running state and other TAs will have to register for mutex and need to be added in a wait queue.
On a certain condition, the running TA have to wake the other waiting TAs in Queue through RPC. Is it possible through RPC ??
How the above task can be accomplished.
Any example if you can provide would be helpful

**Comment by jenswi-linaro** [comment]
Dynamic TAs doesn't have mutex or access to RPC.

**Comment by sarju32** [comment]
@jenswi-linaro . Thanks for quick response
Then what about implementing in Pesudo TAs .. I will create multiple PTAs.
From one main PTA I would like to wake other PTAs through RPC
Is this possible to do ??

**Comment by jenswi-linaro** [comment]
That's possible depending on what kind of events you're talking about. If the events are from an interrupt handler in secure world then there's a problem as interrupt handlers can't do RPC.

**Comment by sarju32** [comment]
@jenswi-linaro event ares not from interrupt handler. Its just normal conditional event.

I explain with our scenario example,
We have a pinpad module. Three task is there for Pinpad. 
In that one task will be polling for Key press(GPIO).  When a key press comes it has to wake the second task, which in turn wait for a similar event to occur, when it occurred then it has to wake the third one.
Similar like this we have to perform multiple tasks for Pinpad.

Found that wait_queue and mutex concepts is there in optee-core. Would like to know how to use it to accomplish the above task.
If you can provide some simple example, if not available a pesudo code will be help.

**Comment by jenswi-linaro** [comment]
There's examples under `/core`,  `grep -l condvar **/*.c` gives:
```
core/arch/arm/kernel/mutex.c
core/arch/arm/kernel/user_ta.c
core/arch/arm/kernel/wait_queue.c
core/arch/arm/mm/pgt_cache.c
core/kernel/tee_ta_manager.c
core/lib/libtomcrypt/src/tee_ltc_provider.c
```

**Comment by sarju32** [comment]
@jenswi-linaro Thanks for the info.
Correct me if I am wrong. 
condvar can be used in case of multiple threads for synchronization . How it can be useful in our case.

And I read "Thread handling"  in the documentation page that OP-TEE core has 2 threads
to run parallel jobs.
I would like to utilize that. 
I have two PTAs and one User TA. Whether its possible to run that two PTAs in thread 1(PTA1) and in thread 2(PTA2), then use condvar wait and signal functionality between that two PTAs 
This is possible ?
Can you please clarify me on this 
use condvar wait and signal functionality to

**Comment by jenswi-linaro** [comment]
@sarju32, yes it's be possible to use two PTAs as you describe.
