### ISSUE TITLE
DES3 Example for optee

### ISSUE THREAD

**Issue by ranjithvs** [OP-TEE/optee_os#1715]
Hi anyone have example program for DES3.

**Comment by jforissier** [comment]
Hi @ranjithvs,

See https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000.c and search for "DES3"/"des3".

**Comment by ranjithvs** [comment]
Other than xtest any other example is there.?

**Comment by jforissier** [comment]
Unfortunately, no :(
We'd like to add such simple examples to the https://github.com/linaro-swg/hello_world repo. Feel free ro contribute ;)

**Comment by uglym8** [comment]
If it is still relevant for anyone you can check the DES3 example mentioned in https://github.com/OP-TEE/optee_os/issues/3129
