### ISSUE TITLE
question: select several cryptographic engines at runtime

### ISSUE THREAD

**Issue by jlescher** [OP-TEE/optee_os#1717]
Hello everybody,

I have got a question regarding the crypto_ops interface.

My platform has several CPUs and dedicated hardware for crypto operations (des, aes, rc4, sha1, sha256 and hmac). Optee_os' accesses to the hardware ciphers are granted/denied by another CPU at runtime.
Therefore I am required to:
- be able to register/unregister hardware engines performing crypto ops
- fallback to the implementation of libtomcrypt when no hardware engine is available

The current API `tee_cryp_provider.h` does not suit very well this purpose.
So far, what we have come up with is:
- renaming the libtomcrypt's crypto_ops with objcopy in the library object
- writing our own crypto_ops with some functions redirecting to the renamed crypto_ops and others calling the hardware ciphers (depending on their availability).

Have you thought about this specific usecase?
Do you have plans for the crypto framework?

**Comment by jenswi-linaro** [comment]
Hi @jlescher 

We don't have any current plan to implement support for this. Patches are welcome! :-)

**Comment by ken08liu14** [comment]
I guess some "weak" and "alias" function would help so that you dont need to hack ops with objcopy.
@jlescher

**Comment by jlescher** [comment]
Hi @ken08liu14, the reason I needed to hack ops with objcopy was to avoid name collision between: my crypto_ops structure on one side and the libtomcrypt implementation of the crypto_ops on the other side.

To me, the ideal solution should look like:

```
// Tell the framework, that engine is able to perform algo
register_engine(algo, engine);

// Retrieve an engine to perform a given algo
engine = get_hash_engine(algo);
// Process
engine.get_ctx_size(...);
engine.ini(...);
```

Hi @jenswi-linaro, since I don't have time to work on this should I close the issue or let it pending?

**Comment by jenswi-linaro** [comment]
If nothing is going to happen, please close it.
