### ISSUE TITLE
Query regarding interrupt handling in OPTEE

### ISSUE THREAD

**Issue by kumarabekur** [OP-TEE/optee_os#1719]
Is there any example which explains interrupt handling in OPTEE OS.

**Comment by vchong** [comment]
https://github.com/OP-TEE/optee_os/blob/master/documentation/interrupt_handling.md?

**Comment by MrVan** [comment]
Following this quesiton, I have another one, is FIQ disabled when using fast smc call to arm32, gicv2? or FIQ is enabled when fast smc? thanks.

**Comment by etienne-lms** [comment]
hello @MrVan,
During fast smc calls, IRQ, FIQ and Async aborts are masked.
Note that this is also asserted on fast smc call exit, in **thread.c**:
```c
void thread_handle_fast_smc(struct thread_smc_args *args)
{
	thread_check_canaries();
	thread_fast_smc_handler_ptr(args);
	/* Fast handlers must not unmask any exceptions */
	assert(thread_get_exceptions() == THREAD_EXCP_ALL);
}
```

**Comment by MrVan** [comment]
Thanks @etienne-lms

**Comment by kumarabekur** [comment]
Thanks for responding quickly.
@vchong @etienne-lms I will try to eloborate my question. I want to implement GPIO driver in interrupt mode in OPTEE. How a GPIO driver driver can be implemented which will give interrupt when it goes from HIGH to LOW or LOW to HIGH. The query I have here is where should be the implementation for interrupt( I want it more preferably in OPTEE os). How I can implement interrupt handler for this one? whether handler for this one should be implemented in normal world and somehow I should pass it to secure world or directly in OPTEE I can handle this one. 
Thanks @MrVan for your following question. :)

**Comment by igoropaniuk** [comment]
Hello @kumarabekur, 

Regarding interrupt handling in OP-TEE OS, there is an example of ps2mouse driver https://github.com/OP-TEE/optee_os/commit/bd54116854a45710474e39b98f7972e552fc55c1#diff-b2f716c963cee37deab03f5f6f056117 (I guess it was added as an example, because it's not used anywhere), where you can find example code for registering secure interrupt handler.

There is also a Pseudo TA https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/pta/interrupt_tests.c with generic tests of raising/handling interrupts(PPI, SPI and SGI).

Hope it helps

BR,
Igor

**Comment by surendran90** [comment]
Hi ,

Have implemented gpio driver with IRQ mechanism(in optee).i'm using secure interrupts(interrupt handled in optee), registered interrupt handler using itr api's https://github.com/OP-TEE/optee_os/blob/master/core/kernel/interrupt.c in GPIO driver.
And followed the document https://github.com/OP-TEE/optee_os/blob/master/documentation/interrupt_handling.md?
interrupt handler function is not called, i doubt i'm missing something to get interrupts .Any pointers or suggestions?

**Comment by leesagacious** [comment]
wo C!
is here.
        itr_add(&d->itr_handler);
	itr_enable(serial_it);

**Comment by Raincode** [comment]
> Hello @kumarabekur,
> 
> Regarding interrupt handling in OP-TEE OS, there is an example of ps2mouse driver [bd54116#diff-b2f716c963cee37deab03f5f6f056117](https://github.com/OP-TEE/optee_os/commit/bd54116854a45710474e39b98f7972e552fc55c1#diff-b2f716c963cee37deab03f5f6f056117) (I guess it was added as an example, because it's not used anywhere), where you can find example code for registering secure interrupt handler.
> 
> There is also a Pseudo TA https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/pta/interrupt_tests.c with generic tests of raising/handling interrupts(PPI, SPI and SGI).
> 
> Hope it helps
> 
> BR,
> Igor

Please beware that this ps2mouse  example calls itr_enable with the pointer to the itr_handler struct as far as I can tell, instead of the it_num, so this does not seem to work in practice (itr_enable expects a size_t). See this line --->
```
itr_enable(&d->itr_handler);  // should probably pass itr_handler.it here?
```
