### ISSUE TITLE
Questions about TA Memory and TEE Threads

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1724]
I have a few questions related to heap memory usage by TA:

1) What is the limit of heap memory allowed per TA ? Where is this specified in OPTEE ?
2) From the documentation, it appears that a TA is assigned a thread when invoked from the normal world.
     Is each thread given a separate heap space, or is heap memory shared among all threads e.g. when multiple TAs have been invoked ?
 3) Is heap memory cleaned up upon TA return ? Also, depending on answer to question (2), is there a difference in heap clean up when one TA returns vs when all TAs have returned ?

If you can also point me to the relevant memory management files inside OPTEE, it would be helpful.

Thanks.

**Comment by etienne-lms** [comment]
Hello a2t2,

> 1. (_TA heap_)

Each instance of Trusted Application owns it private heap (and its private code/data/stack). This heap is provisioned by the TEE core when the TA is initially loaded. 

Each TA specifies its heap size at build time from macro `TA_DATA_SIZE` in their private **user_ta_header_defines.h**. 

There is no specific constraints on the TA heap size but the physical available memory and the TA address space size.

> 3. (__TA heap cleaning__)

While a TA instance is loaded (i.e a client holds an on-going opened session toward the TA), its heap is never cleared. When a TA instance is being destroyed (i.e the last opened session toward the TA is being closed), then the TA full memory is released after being cleared: see `user_ta_ctx_destroy()` in user_ta.c.

Note that while each TA owns its own heap, the TEE firmware ('core') also owns its own heap. This 'core' heap is not accessible from TAs.

> 2. (__TAs, heaps and TEE threads__)

No, TAs are not assigned threads. TAs and TEE threads have not much in common. When the REE invokes the TEE, optee assigns an TEE execution thread to the invocation request. When a client invokes a TA, a TA instance is created in the the TEE.

Hence, if the REE invokes a TA, optee will assign a TEE thread and then will invoke the TA through this TEE thread. When the invocation completes, the TEE thread is released, even if the TA instance remains loaded (for a later invocation). While the TA is invoked, another REE client can invoke the TEE: in this case another TEE thread will be allocated to handle the new invocation request.

There is no specific heap for TEE threads: they all rely on the common TEE 'core' heap.

TEE threads are used to track TEE invocation execution contexts when TEE needs to switch back to the REE before the invoked service is completed (forwarding a REE interrupt, calling a REE remote service, i.e secure storage access).

> If you can also point me to the relevant memory management files inside OPTEE, it would be helpful.

There are several memory management topics/support in optee: fmw memory, TAs memory, invocation memeref parameters, fmw paging, ... Which area are you interested in ? Most memory management sources are located in directory **core/arch/arm/mm/**.

**Comment by a2t2** [comment]
Hello etienne-lms,
Thank you for taking the time to write the response. I have a few follow up questions:

1) What is the definition of a TA instance ? What state is kept inside a TA instance ?
    What does it mean that a TA instance is "loaded" into a TEE thread ?

2) Where is TA instance state kept when a TA returns but the client session is not closed ? 

3) Based on your response, I am trying to understand how heap is made available to the TA; is the following true:
   a) The TEE core provides part of its heap when a new TA instance is created so that TA can use it as heap; the core keeps track of heap content assigned to a TA instance
   b) When there is a TEE invocation for a TA, the core will assign a TEE thread allowing execution of code from the TA; this allows the TA to access content in its assigned heap
   c) When the TA returns at the end of a command execution, the TA instance is saved (not sure where) and the TEE thread released. If the same TA is invoked a second time by REE, a new TEE thread is assigned for invocation; while TA code is executing in the assigned thread, the core allows TA to access its allocated heap (still part of the overall core heap), so TA can access stored heap data from previous invocation
   d) When the TA returns, the TEE thread is released, and when TA session is closed by client, the core releases the heap that was assigned to the TA

4) Is the following true:  When a TEE thread is assigned to execute a TA, the memory required for stack and static content is temporary and is associated with the thread; when the TA returns after a command execution, the stack and static memory is released because the TEE thread is released.

5) When REE invokes TEE, a TEE thread is assigned to the invocation. It seems TA invocation and TEE thread creation/allocation are separate concepts. Under what circumstances is TEE invocation not related to TA invocation ? Is forwarding interrupt from REE to be handled in TEE one such case ? Are there any others ?

I would request if you could point me to the following code:
1) TEE thread allocation for TEE invocation
2) TEE thread destroy when returning from TEE
3) Heap allocation for a TA
4) TA instance creation when TA is invoked
5) TA instance destroy when TA session is closed
6) TA instance contents 
7) TA instance loading into a TEE thread

Thank you very much for your help.

**Comment by etienne-lms** [comment]
That a lot of related questions :) I will hardly answer all without being confusing. Here are few info. In the hope it helps you.

First of all, note that there are 2 separated memory areas in the TEE:
- the 'core' memory area (grep for `..._TEE_RAM` in core/...). It stores the TEE 'core' heap, stacks, code and data. TEE executes in priviledge mode in the TEE_RAM.
- the 'TA' memory area (grep for `..._TA_RAM` in core/...): the memory reserved to TAs. It stores each loaded TA heap, stack, code/data. TEE executes in userland mode in the TA_RAM.

TEE threads:
- Yes, TEE threads and Trusted Application contexts are not correlated. When the REE invokes the TEE, the TEE assigns a thread (note that threads are assigned, not allocated: TEE embeds a fixed number of threads and if no thread is available, TEE asks REE to wait for a thread to be available).
- A TEE thread can be used either to invoke a Trusted Application, or to invoke a TEE service that is not related to a Trusted Application (we refer such services as 'pseudo TAs').
- A TEE thread is released only once the related invocation (TA or pseudo TA) is completed (successfully or not).
- Each TEE thread owns its own stack. But note that if the TEE invokes a TA, TEE will use the TA stack when entering the TA code (userland) and TEE thread stack when back in the 'core' (privileged land).
- TEE threads are useful when TEE executes in secure and need to call some service from the REE. In such case, TEE saves the TEE execution state in its executing thread and invokes the REE. When REE returns to TEE, TEE resumes its thread execution. This mechanism is referred as RPC in the TEE.
- There are 2 main RPC services invoked by the TEE:
1- Forwarding of a non secure interrupt (so-called 'foreign interrupts')
2- Invocation of a REE service (allocate shared memory, access REE filesystem, get REE time, ...)

Trusted Application:
- A TA instance is a execution context related to a binary application loaded in the userland of the TEE.
- Each TA execution context (TA instance) owns its private heap, stack, code/data memory.
- When one opens a session toward a TA, if the target TA does not already have a execution context, then TEE creates the execution context:
1- allocate TA context management structures in TEE_RAM.
2- allocate TA private memory in TA_RAM.
3- load TA binary code/data in TA_RAM.
Once done, TA instance is ready to be invoked.
- When all sessions toward a TA are closed, the TA is unloaded: allocated memory in TA_RAM is freed, TA context management structures in TEE 'core' heap (in TEE_RAM) are released. Note that a TA can claim a `keepAlive` property in which case the TA is never unloaded from the TEE (unless TEE fully resets).
- Memory owned by TA instances is not saved/restored as TAs are invoked. It is allocated at first invocation, accessed at each invocation, freed at TA instance destruction (TA unload). (Actually, there is a specific configuration of the TEE where memory is managed slightly differently: the pager mode. I did not elaborate on it in this discussion). 

Main code related to TEE threads can be found in core/arch/arm/kernel/thread.c.
Main code related to TAs can be found in core/arch/arm/kernel/user_ta.c.

**Comment by jforissier** [comment]
About TA instances: the GP Internal Core API specification version 1.1.2 sections 2.1.2
_"Instances, Sessions, Tasks, and Commands"_ and 2.1.6 _"Instance Types"_ might be useful to read.

**Comment by a2t2** [comment]
Based on your explanation, I am trying to do an experiment where I am trying to access data stored in TA heap from a different client. The TA has two commands: 

- test_one: saves some data in heap
- test_two: reads data from the heap

TA code:
```
static void *tmp_buf = 0;
static TEE_Result test_one(uint32_t param_types, TEE_Param params[4])
{
        (void)param_types;
        (void)params;

        IMSG("HelloWorld TA - First Invocation");

        tmp_buf = TEE_Malloc(sizeof(int), TEE_USER_MEM_HINT_NO_FILL_ZERO);

        if (!tmp_buf) {
                IMSG("Cannot malloc - out of memory");
        }
        else {

                int *p = (int *)tmp_buf;
                *p=1234;

                IMSG("Value saved in heap is 1234");
        }
}

static TEE_Result test_two(uint32_t param_types, TEE_Param params[4])
{
        (void)param_types;
        (void)params;

        IMSG("HelloWorld TA - Second Invocation");

        if (!tmp_buf) {

                IMSG("tmp_buf is zero");
        }
        else {

                int *p = (int *)tmp_buf;
                IMSG("Value read from heap is: %d", *p);
        }
}

```
I have two clients. The first client opens a session and invokes test_one, but does not close the session; I  use a while loop to keep the client running. The second client opens another session and invokes test_two.

Client 1 Code:
```
res = TEEC_InitializeContext(NULL, &ctx);
        if (res != TEEC_SUCCESS)
                errx(1, "TEEC_InitializeContext failed with code 0x%x", res);

res = TEEC_OpenSession(&ctx, &sess, &uuid,
                               TEEC_LOGIN_PUBLIC, NULL, NULL, &err_origin);
        if (res != TEEC_SUCCESS)
                errx(1, "TEEC_Opensession failed with code 0x%x origin 0x%x",
                        res, err_origin);

memset(&op, 0, sizeof(op));
 op.paramTypes = TEEC_PARAM_TYPES(
                        TEEC_NONE,
                        TEEC_NONE,
                        TEEC_NONE,
                        TEEC_NONE);
res = TEEC_InvokeCommand(&sess, TA_TEST_1, &op, &err_origin);
while (1) { }
TEEC_CloseSession(&sess);
TEEC_FinalizeContext(&ctx);
return 0;
```

Client 2 Code:
```
res = TEEC_InitializeContext(NULL, &ctx);
        if (res != TEEC_SUCCESS)
                errx(1, "TEEC_InitializeContext failed with code 0x%x", res);

res = TEEC_OpenSession(&ctx, &sess, &uuid,
                               TEEC_LOGIN_PUBLIC, NULL, NULL, &err_origin);
        if (res != TEEC_SUCCESS)
                errx(1, "TEEC_Opensession failed with code 0x%x origin 0x%x",
                        res, err_origin);

memset(&op, 0, sizeof(op));
 op.paramTypes = TEEC_PARAM_TYPES(
                        TEEC_NONE,
                        TEEC_NONE,
                        TEEC_NONE,
                        TEEC_NONE);
res = TEEC_InvokeCommand(&sess, TA_TEST_2, &op, &err_origin);
TEEC_CloseSession(&sess);
TEEC_FinalizeContext(&ctx);
return 0;

```
When test_two is invoked by the second client, I get the message "tmp_buf is zero" i.e. the invocation from second client cannot read the saved data in the TA heap. But if If I call both test_one and test_two from same client in sequence (keeping session opened between the two calls), then the test_two invocation can read saved heap data.

Code that calls test_one and test_two in sequence:
```
memset(&op, 0, sizeof(op));
op.paramTypes = TEEC_PARAM_TYPES(
                        TEEC_NONE,
                        TEEC_NONE,
                        TEEC_NONE,
                        TEEC_NONE);
res = TEEC_InvokeCommand(&sess, TA_TEST_1, &op, &err_origin);
res = TEEC_InvokeCommand(&sess, TA_TEST_2, &op, &err_origin);
TEEC_CloseSession(&sess);
TEEC_FinalizeContext(&ctx);
return 0;
```

Is this supposed to happen ? Based on your description, the heap for a loaded TA instance (with at least one open client session) is not released. Is my experiment setup the wrong way ?

Thanks.

**Comment by a2t2** [comment]
I think I realize my mistake. I think it may have to do with single vs multi instance TA.

**Comment by etienne-lms** [comment]
Exactly.
Try also your test with the TA_FLAG_KEEP_ALIVE (applies only to single instance TA) ?
Heap will be preserved over session closure. And if TA crashes, you will need to restart TEE to reach the TA again.

**Comment by a2t2** [comment]
I have one last question about TEE thread (then I will close this issue because it is getting too long). This question relates to this [scheduling question](https://github.com/OP-TEE/optee_os/issues/997) as well.

I tried a simple experiment using Hikey 620 (which has 8 cores), wherein I invoked the same TA (multi instance) 8 times, and used a while loop to block the TA command code each time. Since each TA invocation is assigned a thread by the core, I presume that 8 threads have been assigned by the OPTEE core. I cannot have a 9th session invoked. So my question is:

1) how are those 8 threads being managed by the core ? what does it mean that core depends on the Linux kernel for its scheduling ?
2) is the limit of number of sessions (like I couldn't open a 9th session) dependent on number of cores ? If yes, does that mean each TEE invocation uses 1 core ?
3) I also noticed that I could use the normal world terminal even after making 8 invocations into TEE ? Is that expected ? If so, why ?

Thank you for your time.

**Comment by etienne-lms** [comment]
Number of cores and number of thread is not really related.

The number of threads (defined from `CFG_NUM_THREADS`) is a matter of memory consumption. Aside the thread structure itself, each thread is provisioned with a 8kB stack which can be quite consuming on memory constrained systems.

When REE invokes the TEE, the TEE assigns a thread for the invocation. Until the invoked service completes (successfully or not), that TEE thread remains reserved to the related invocation. The TEE thread is released only once the invocation completes and TEE returns to REE with a status. Hence, if 2 cores invokes the TEE at the same time and TEE holds 2 free thread, both invocation will be proceeded.

Note that TEE can invokes the REE several times before it returns to REE with the initial invocation completed. For example consider the first time a TA is accessed, see below. You can see that a unique TEE thread is used while core switches several times between REE and TEE.
1. REE invokes the TEE to request openning a session toward a specific TA.
2. TEE assigned a thread for the execution of the service.
3. TEE invokes the REE to allocate non secure buffers to prepare the loading of the TA.
TEE suspends its running thread and invokes the REE with a memory allocation request.
When REE returns to TEE, TEE resumes its thread execution.
4. TEE invokes the REE to get the TA binary blob into the allocated non secure buffers.
TEE suspends its running thread and invokes the REE with a 'TA load' request.
When REE returns to TEE, TEE resumes its thread execution.
5. TEE loads the TA.
6. TEE invokes the REE to release the non secure buffers used to get the TA binary blob.
TEE suspends its running thread and invokes the REE with a memory release request.
When REE returns to TEE, TEE resumes its thread execution.
7. TEE opens a session towards the TA and get the request status
8. TEE release the TEE thread and finally returns to the REE with the open session status. 

While a TEE thread is being executed, it is possible that non secure interrupts occur. If so, the running TEE thread will suspend (context save), and TEE will invoke REE so that the later can catch the interrupt. Once in REE, the core executes in the context of the linux thread that initially invoked the TEE. REE can catch the interrupt and do what is wants to, eventually scheduling another linux thread. When REE schedules back the execution of the linux thread (that initially invoked the TEE), REE will invoke the TEE and on TEE side TEE will resume the TEE thread execution.

This has few consequences:
- REE can schedule out the TEE execution and schedule in some other process (actually any linux thread). This should answer question **3**.
- REE can return into a TEE thread on a core different from the one that executed the TEE thread before.
- Even on the single core, TEE can execute several TEE threads, based on linux kernel scheduling.

Regarding question **2**: the number of opened session is completely decorrelated to the number of thread or cores. In your setup, you failed to open a 9th session because you were running out of TEE thread for the 9th "open session" invocation: the 8 threads were already used as trapped in your TA.

**Comment by a2t2** [comment]
Thank you for your response.

**Comment by ryankumar** [comment]
what are the changes required if i compile the TA using c++ compiler ? in TA side what should be i change.

**Comment by ryankumar** [comment]
can we write TA in c++ ?

**Comment by jforissier** [comment]
@ryankunar if you would have spent a few seconds Googling "optee C++ ta" you would have found this: https://github.com/OP-TEE/optee_os/issues/1708 which should pretty much answer your question.

Besides, please refrain from discussing a totally unrelated topic in an existing Github issue. Thanks.

**Comment by a2t2** [comment]
Quick question related to RPC: The TEE invocation from normal world goes via the normal-world TEE driver. When the TEE makes a RPC call to the tee-supplicant, does the RPC flow go via the normal-world TEE driver as well ?

**Comment by a2t2** [comment]
Never mind .. I found a relevant picture in the secure storage [page](https://optee.readthedocs.io/en/latest/architecture/secure_storage.html). The answer should be yes.

**Comment by jforissier** [comment]
> Never mind .. I found a relevant picture in the secure storage [page](https://optee.readthedocs.io/en/latest/architecture/secure_storage.html). The answer should be yes.

Yes indeed, see https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/tee/optee/call.c?h=v5.8-rc4#n115.
