### ISSUE TITLE
OPTEE code for state saving during interrupt

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1725]
From the documentation at [link](https://github.com/OP-TEE/optee_os/blob/master/documentation/interrupt_handling.md) (case: Forward IRQ from secure world to normal world), OPTEE can save the state of a thread (being used by a TA to execute a command) to handle an interrupt in the normal world, and can later resume the saved state of the same thread. I am trying to look for the code in OPTEE that handles this part. 

Specifically:
1) OPTEE code that saves TA thread state when interrupt needs to be handled in the normal world
2) OPTEE code that finds and resumes execution of the saved TA thread (command) after interrupt handling is finished in the normal world

Can someone please help me by pointing me to the right code ?
Thank you.

**Comment by igoropaniuk** [comment]
Hi @a2t2,

check `foreign_intr_handler` in `core/arch/arm/kernel/thread_a32.S`  (https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread_a32.S#L463)

BR,
Igor
