### ISSUE TITLE
Purpose of THREAD_EXCP_FOREIGN_INTR checking in source

### ISSUE THREAD

**Issue by ken08liu14** [OP-TEE/optee_os#1726]
Hi there,

I am reading the code and found there would be checking of :

`assert(thread_get_exceptions() & THREAD_EXCP_FOREIGN_INTR);`

in thread_kernel_save_vfp() and thread_user_save_vfp();
I want to know the purpose of this code, does it mean that source needs to make sure vfp saving is only done while FOREIGN_INTR comes? How about svc(syscall of TA)/abort(PAGE fault) occurred ?

Thanks for your kindly reply.

-Ken

**Comment by jforissier** [comment]
Hi Ken,

No, `thread_get_exceptions()` returns the current exception mask. Maybe the name of the function is not very good...
So `assert(thread_get_exceptions() & THREAD_EXCP_FOREIGN_INTR)` means we make sure foreign exceptions are disabled.

**Comment by ken08liu14** [comment]
Thanks, Forissier.

I asked this question due to I tested on GICv3 (internal emulator) platform and this assert will be triggered while TA systemcall comes; and only in 32BIT optee; 64bit works fine; have not tried on hikey since we don't have a full env for that.
