### ISSUE TITLE
user_ta_header.o uses VFP register arguments

### ISSUE THREAD

**Issue by AllenSiao** [OP-TEE/optee_os#1727]
Hi, 

I linked a static library with user TA and encountered an error which is uses VFP register arguments. Then I changed the link setting as below:
static library:  -mtune=cortex-a53 -EL -mfloat-abi=softfp -mfpu=neon-fp-armv8
TA:  -mtune=cortex-a53 -EL -mfloat-abi=softfp -mfpu=neon-fp-armv8
optee_os/core/arch/arm/arm.mk: arm32-platform-cflags-hard-float ?= -march=armv8-a -mtune=cortex-a53 -EL -mfloat-abi=softfp -mfpu=neon-fp-armv8

And it can solve the most part of VFP errors but user_ta_head.o still apply mfloat-abi=hard. Is there any advise that how can I make  user_ta_head.o to apply mfloat-abi=softfp?

Thanks for your advise anyway.

**Comment by jenswi-linaro** [comment]
Generally it's a lot easier if you import the static library into the build system to make it part of your TA dev kit. That way you'll get correct compiler flags etc.

**Comment by AllenSiao** [comment]
Thanks for your answer, @jenswi-linaro

I found the solution, and the reason of compile fail is that I didn't apply the right make config.
