### ISSUE TITLE
Problems while run xtest with SDP

### ISSUE THREAD

**Issue by ken08liu14** [OP-TEE/optee_os#1731]
Hi there,

I am running xtest with SDP since we want to develop some secure app with it; but it keeps failing with PTA test.

The root cause is two places after some dig:
1.  since output buffer is SDP, it is nonsec and this check fails.
`	/* all non-secure memory references are hanlded by pTAs */`
`	if (mobj_is_nonsec(mobj))`
`		return true;`

2. va get fail on SDP mobjs.
`va = mobj_get_va(param->u[n].mem.mobj,`
`					 param->u[n].mem.offs);`

So is there something I missed or wrong ?
Thanks.

-Ken

**Comment by etienne-lms** [comment]
In current implementation of the SDP, pTAs can access to SDP memory only on request of a Trusted Application. Hence, the REE cannot invoke a pTA with a SDP memref parameter while a TA can.

In the `xtest --sdp-basic`, the 4 following cases are tested:
- REE invokes a TA with SDP memory reference parameters
- TA invokes a TA with SDP memory reference parameters
- TA invokes a pTA with SDP memory reference parameters
- REE invokes a pTA with SDP memory reference parameters (expected to fail)

Which case is failing on your setup ? The last one I expect.

Why this (no SDP support for REE->pTA) ? 
We don't see need for SDP services in the 'core' opened to the non secure wolrd.

And why does `mobj_get_va()` over a SDP memory reference ?
SDP memory is NOT default mapped to optee core. When REE invokes a pTA with a SDP memeref, the current code does not build the target buffer mapping. Hence `mobj_get_va()` return NULL.

Note that when a pTA is invoked by a TA, the TA already maps the target SDP memory, and the pTA will use this mapping to access the SDP buffer.

**Comment by ken08liu14** [comment]
Thanks for your detail answer and got it. Yes we failed at last one.

We do the fourth item directly since there are some problems in our ta; (it is loaded but invoke command not triggerred -- checking)

We want to save some hardware access only data in that; so it should be CA -> TA -> pTA, right?

And the other problem is that we want to set some hardware registers in TA; could we just call some map functions to map physical address in TA?

**Comment by etienne-lms** [comment]
> We want to save some hardware access only data in that; so it should be CA -> TA -> pTA, right?

Yes, with current implementation, you need to go through a TA with `TA_FLAG_SECURE_DATA_PATH`.

> And the other problem is that we want to set some hardware registers in TA;
> could we just call some map functions to map physical address in TA?

There is no real clean dynamic mapping support for the core (incl. pTA) in current optee. Hence what you can do is the map the target iomem statically in the core: `register_phys_mem(MEM_AREA_IO_SEC, FOO_BASE, FOO_SIZE);` and get at least once the valid address at run time `vbase = phys_to_virt(FOO_BASE, MEM_AREA_IO_SEC);`.

**Comment by ken08liu14** [comment]
Great, Thanks and close this issue.

**Comment by sliai** [comment]
Hi,
Now, I am testing the SDP , but the test is failed. 
My test case is xtest 1014, and the test is failed in first case TEST_NS_TO_TA.

As you said, the access flow should be  CA -> TA -> pTA. But in ta_sdp_basic.c (in optee_test), it move data directly in cmd_inject function:
	/* inject data */
	TEE_MemMove(params[sec_idx].memref.buffer,
		    params[ns_idx].memref.buffer,
		    params[sec_idx].memref.size);
It not call PTA to access data.

Is there any wrong in xtest?

**Comment by etienne-lms** [comment]
Do you have any error traces from the TEE or the TA ?

Note: `xtest -t regression 1014` is the same as `xtest --sdp-basic` but the later is a bit more verbose on REE side.

**Comment by sliai** [comment]
In TA, it is run to TEE_MemMove() in cmd_inject() function of ta_sdp_basic.c. then it cannot come back from this funciton.

**Comment by etienne-lms** [comment]
Strange. `TEE_MemMove()` is a simple memory copy. Could you enable the traces (`CFG_TEE_CORE_LOG_LEVEL=3` + `CFG_TEE_TA_LOG_LEVEL=3`) and you add some `MSG()` traces in the TA to trace the arguments to `TEE_MemMove()` ?

**Comment by sliai** [comment]
Now, I use juno to do this test and it can pass. So, there maybe some problems in my former platform: fvp. I will debug it later. 
Thanks your help.
