### ISSUE TITLE
Previous Work about Trusted User Interface on FVP

### ISSUE THREAD

**Issue by Gmanyoo** [OP-TEE/optee_os#1737]
Hello, I'm new to OPTEE. 

I heard there is a previous work about Trusted User Interface on FVP on OP-TEE Q&A ( https://www.op-tee.org/blog/op-tee-qa/ )  (Q: Currently is there any work on Trusted User Interface support?). 
I want to try this on my computer but I couldn't find any information about this issue. Please let me know if you have any information that I consultable.

Thank you so much :)

**Comment by jenswi-linaro** [comment]
The code is available here https://github.com/jenswi-linaro/optee_os/tree/tui-old2

**Comment by Gmanyoo** [comment]
Thank you so much :D
