### ISSUE TITLE
user TA with TEE_ERROR_BAD_FORMAT when load_head

### ISSUE THREAD

**Issue by AllenSiao** [OP-TEE/optee_os#1738]
Hi,

My user TA build with softfp, and os also build with softfp. When session created I faced the error: TEE_ERROR_BAD_FORMAT at load_head function as below: 
if (phdr0.p_type != PT_LOAD || phdr0.p_vaddr != 0)
    return TEE_ERROR_BAD_FORMAT;

My latest master commit is "commit c0c5d39".
What is happened?  

BRs

**Comment by jforissier** [comment]
Hi @AllenSiao ,

Please upgrade to latest master, or cherry-pick commit 1191e655c52e ("core: elf_load.c: do not require first segment to be PT_LOAD"), and let me know if that fixes the issue.

**Comment by AllenSiao** [comment]
Hi  jforissier,

It fixed the issue I encountered, thanks for your quickly help.

BRs

**Comment by jforissier** [comment]
You're welcome.
