### ISSUE TITLE
Problems compiling with openSSL 

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1745]
Hi,

I am trying to add openSSL encrypting to the client code but am getting this compile error:

     crypto.c:30:25: fatal error: openssl/pem.h: No such file or directory

crypto.c is my C file and I have the "openssl" directory where my crypto.c file is. My code cannot find the header files needed. The lines of code in my file are:

```C
// openSSL stuff
#include <openssl/pem.h>
#include <openssl/ssl.h>
#include <openssl/rsa.h>
#include <openssl/evp.h>
#include <openssl/bio.h>
#include <openssl/err.h>
```

I then checked how e.g. it was done using the tee_client_api.h file - there is a LOCAL_C_INCLUDES line in the Android.mk file. I created the same setup for the openssl directory - unfortunately that also did not work.

Finally I tried to copy the openssl directory everywhere I could think of, I couldn't get it to compile without errors. 

I have a test openSSL program running WITHOUT op-tee. The example is minimal but compiled and ran without any problem on the same machine as op-tee so I know that openssl is setup correctly.

So my question is this: how do I add the openssl header files so that I can compile correctly?

Thanking you in advance
Ursus

**Comment by ursus-the-bear** [comment]
OK, so I've been testing and found that the Android.mk file is not used when building for my architecture. I have added the -I to the Makefile file, this solves the problem for *my* c files, but not the openssl header files that all have <> in their code.

**Comment by ursus-the-bear** [comment]
Anybody who could be of some help please?

**Comment by levitte** [comment]
Use this: `-I/home/ursus/devel/optee/fim/includes`

**Comment by ursus-the-bear** [comment]
@levitte Thank you for the pointer but I already tried that - unfortunately it didn't work. I do not need to do that when compiling "outside" of op-tee -> by this I mean when creating a standalone. openssl installs all the header files into /usr/include/openssl so it should really find it by itself.

**Comment by jforissier** [comment]
Does `/home/ursus/devel/optee/fim/includes/openssl/pem.h` exist?

**Comment by jforissier** [comment]
To troubleshoot build with `V=1` then copy/paste the whole gcc line that fails. Replace `-c` by `-E` and remove `-o some/file.o`. And pipe the output into `| less` (or redirect it to a file: `>gcc.log`). This way you can follow what files are included by the preprocessor.

**Comment by ursus-the-bear** [comment]
Hi Jerome, yes, it does (did). I have since removed it as I did not need it for my test program that is at the same directory level as my CA. I have since found out that if I add 

    -I/usr/include

to the CFLAGS in the Makefile AND copy the file 

    opensslconf.h 

from the /usr/include/x86_64-linux-gnu/openssl dirctory to the /usr/include directory I can get the code to compile. 

This is very odd as I do not need this to compile otherwise... I add my test code tomorrow morning an report back here !

**Comment by ursus-the-bear** [comment]
@jforissier I added LDFLAGS += /home/ursus/devel/optee/fim/libs/libcrypto.a to the Makefile as well (after creating the libs directory and adding the libcrypto.a to it) - I am assuming this will add the library to my CA... am I right in assuming this?

**Comment by jforissier** [comment]
`-I/usr/include` should not be necessary for CAs unless we have added `-nostdinc` to the default flags (this would be a mistake, can you please check? I'm on my mobile phone right now ;))

**Comment by jforissier** [comment]
@ursus-the-bear about LDFLAGS: correct!

**Comment by ursus-the-bear** [comment]
@jforissier no, I did not add any flags. Just to be sure I checked all my Makefiles (CA, TA, and common.mk etc). If I remove the -I/usr/include I cannot compile.

**Comment by ursus-the-bear** [comment]
@jforissier ok, we are getting there slowly ... dammit - this shouldn't be this difficult should it 😊 

I have added:

    CFLAGS += -Wall -I../ta -I$(TEEC_EXPORT)/include -I/usr/include

and 

    LDFLAGS += /home/ursus/devel/optee/fim/libs/libcrypto.a

to the Makefile. When I now call openssl functions eg. 

```C 
*out_len = RSA_public_decrypt (in_len, (unsigned char *)in, (unsigned char *) out, rsa, RSA_PKCS1_PADDING);
```
I get a (linker) error: 

```
crypto.o: In function `encrypt_using_private_key':
crypto.c:(.text+0x40): undefined reference to `RSA_private_encrypt'
crypto.o: In function `decrypt_using_public_key':
crypto.c:(.text+0xb4): undefined reference to `RSA_public_decrypt'
crypto.o: In function `createRSA':
crypto.c:(.text+0x104): undefined reference to `BIO_new_mem_buf'
crypto.c:(.text+0x14c): undefined reference to `PEM_read_bio_RSA_PUBKEY'
crypto.c:(.text+0x16c): undefined reference to `PEM_read_bio_RSAPrivateKey'
collect2: error: ld returned 1 exit status
```
I thought that the LDFLAGS was supposed to take care of the linking for me? Any idea what I am missing? The libcrypto.a file is there and in the right place.

**Comment by jforissier** [comment]
If your makefile is inspired from https://github.com/OP-TEE/optee_test/blob/master/host/xtest/Makefile#L152 then it should work. LDFLAGS is not a magical keyword, it has to be added to the link command.

**Comment by ursus-the-bear** [comment]
@jforissier ok, I added $(LDFLAGS) to the compile line and then got the a lot of 

**dso_dlfcn.c:(.text+0x18): undefined reference to `dlopen'** errors, these I corrected by adding -ldl to the compile line. I have ended up with

	$(CC) $(LDADD) -o $@ $< MD5.o utils.o CA.o check_TA.o crypto.o $(LDFLAGS) -ldl

which now seems to compile. I will update my code and test tomorrow. Thank you for your help today 😊

**Comment by ursus-the-bear** [comment]
@jforissier @levitte thanks for the help - adding the -I/usr/include, $(LDFLAGS) and -ldl have corrected the problem. thank you very much for the help 👍

**Comment by genie2110** [comment]
@ursus-the-bear 
I am getting some linking issues when adding openSSL encrypting code to the client code , have used apis from below headers
#include <openssl/pem.h>
#include <openssl/ssl.h>
#include <openssl/rsa.h>
#include <openssl/evp.h>
#include <openssl/bio.h>



I get some compilation errors while compiling my client code

/master/usr/src/stand/common/sign.c:65: undefined reference to `BIO_new_mem_buf'
/usr/bin/ld: /master/usr/src/stand/common/sign.c:66: undefined reference to `PEM_read_bio_PUBKEY'
/usr/bin/ld: /master/usr/src/stand/common/sign.c:67: undefined reference to `EVP_PKEY_get1_RSA'
/usr/bin/ld: /master/usr/src/stand/common/sign.c:69: undefined reference to `RSA_size'
/usr/bin/ld: /master/usr/src/stand/common/sign.c:71: undefined reference to `RSA_public_decrypt'
/usr/bin/ld: start.o: in function `_start':
when I add LDFAGS+= -lcrypto -ldl and CFLAGS+=-I/master/usr/include to Makefile I get below err

/usr/bin/ld: /lib/libc.so.7: undefined reference to `__progname'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /master/usr/src/stand/efi/loader_4th
*** Error code 1

Please let me know if I am missing anything?

**Comment by ursus-the-bear** [comment]
sorry, but it has been so long since I looked at the code I just cannot help anymore 🙁 maybe jforissier can help - sorry

**Comment by jforissier** [comment]
> /usr/bin/ld: /lib/libc.so.7: undefined reference to `__progname'
> cc: error: linker command failed with exit code 1 (use -v to see invocation)
> *** Error code 1

This error doesn't seem related to OpenSSL. Did you compile your program with some libc that is different from the one you are using at runtime perhaps?

**Comment by kavithabk** [comment]
@ursus-the-bear thank you
@jforissier yes i am using libc from a different path..let me recompile and use from one place if that can be the issue...

**Comment by pkthapa** [comment]
Hello Everyone,

I get this linker error:
`openssl_rsa.cpp:(.text+0x4c9): undefined reference to `EVP_PKEY_CTX_set_rsa_keygen_bits'`

I have this link in my **Makefile**: `clang++ -Wall -std=c++17 openssl_rsa.cpp openssl_eddsa.cpp -lcrypto -lssl -ldl`

Am I missing something here?
