### ISSUE TITLE
TA encrypt, CA decrypt

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1749]
I am trying to encrypt in the TA and decrypt in the CA, no matter what I do I cannot get it to work. Could somebody please look at my code and tell me what I am doing wrong? I know it's a lot of code - sorry but I couldn't get it any shorter. Thank you. 

Here is my basic algorithm:

1. create some random text in the CA
1. send the text to the TA using shared memory
3. encrypt the text using the private key in the TA
4. send the encrypted text back to the CA using shared memory
5. decrypt the text using the public key
6. see if the sent and received text is the same

I have installed optee and openssl on my ubuntu server. I then used this example (http://hayageek.com/rsa-encryption-decryption-openssl-c/) to create an openSSL key and used the code in the CA. 

I then converted the private key into a format that I could use in the TA using the following command:
    
    openssl rsa -in priv_key -text

this gives me 3 arrays (modulus, public_key, private_key) that I can use in the TA to encrypt and decrypt data. Here is a bit more info regarding this what I did: https://github.com/OP-TEE/optee_os/issues/1677

I am using the exact same keys in the CA and TA. 

All well and good. I have test functions in the CA that can encrypt some text using the private key and can decrypt it again using the public key. I have similar code in the TA that does the same thing. As long as I stay in the same world my code works - if I try and encrypt in the TA and decrypt in the CA I cannot get the text decrypted!

I have tried to illustrate the program flow here:

1) send the text
2) it arrives in the TA
3) TA encrypts
4) CA receives correct encrypted text
5) CA cannot decrypt using the public key (I am only using one keypair in the CA and TA)

<img width="1244" alt="screen shot 2017-08-14 at 19 27 27" src="https://user-images.githubusercontent.com/5219580/29283452-0a34a120-8127-11e7-853f-7bc2ca7b6d10.png">

Here is the CA (abridged) code - I have removed anything that is not needed:

```C
void main (void) {
     char test_in [] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
     int test_in_len = strlen (test_in);

     char test_decrypted [512];
     int test_decrypted_len;

     TEEC_Result rc;
     TEEC_Context ctx;
     TEEC_Session sess;
     TEEC_Operation op;
     TEEC_SharedMemory field_in;
     TEEC_SharedMemory field_back;
     TEEC_SharedMemory dummy;
     TEEC_UUID uuid = FIM_TA_UUID;
     uint32_t err_origin;

     rc = TEEC_InitializeContext(NULL, &ctx);
     rc = TEEC_OpenSession(&ctx, &sess, &uuid, TEEC_LOGIN_PUBLIC, NULL, NULL, &err_origin);
     check_rc(rc, "TEEC_OpenSession", &err_origin);

     field_in.buffer = NULL;
     field_in.size = 256;
     field_in.flags = TEEC_MEM_INPUT;
     rc = TEEC_AllocateSharedMemory(&ctx, &field_in);
     check_rc(rc, "TEEC_AllocateSharedMemory for field_in", NULL);

     field_back.buffer = NULL;
     field_back.size = 256;
     field_back.flags = TEEC_MEM_OUTPUT;
     rc = TEEC_AllocateSharedMemory(&ctx, &field_back);
     check_rc(rc, "TEEC_AllocateSharedMemory for field_back", NULL);

     dummy.buffer = NULL;
     dummy.size = 1;
     dummy.flags = TEEC_MEM_INPUT;
     rc = TEEC_AllocateSharedMemory(&ctx, &dummy);
     check_rc(rc, "TEEC_AllocateSharedMemory for dummy parameter", NULL);

     /* Clear the TEEC_Operation struct */
     memset(&op, 0, sizeof(op));

     op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_WHOLE, TEEC_MEMREF_WHOLE,
                                      TEEC_MEMREF_WHOLE, TEEC_VALUE_OUTPUT);
     op.params[0].memref.parent = &field_in;
     op.params[1].memref.parent = &field_back;
     op.params[2].memref.parent = &dummy;
     op.params[3].value.a = 0;

     memcpy(field_in.buffer, test_in, test_in_len);
     field_in.size = test_in_len;
     rc = TEEC_InvokeCommand(&sess, TEST_ENCRYPT_IN_TA, &op, &err_origin);
     decrypt_using_public_key (CA_public_key_copy, (char *)field_back.buffer, field_back.size, test_decrypted, &test_decrypted_len);
     printf ("In string:                %s\n", test_in);
     printf ("Test in len:              %i\n", test_in_len);
     printf ("Encryted value:           %s\n", (char *) field_back.buffer);
     printf ("Encryted len:             %i\n", (int) field_back.size);
     printf ("Decrypted value:          %s\n", test_decrypted);
     printf ("Decrypted len:            %i\n", test_decrypted_len);
}

char CA_public_key_copy [] =
    "-----BEGIN PUBLIC KEY-----\n"
    "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL5c51/v1osjr5+lRPykmpQKyGdXMG0g\n"
    "S6Du1l8Hm0qYXc+azq6qqZvr39zeufw/VLKTfeKeKVJX1D28TImn6cUCAwEAAQ==\n"
    "-----END PUBLIC KEY-----\n";


// decrypt in string using the public key
BOOLEAN decrypt_using_public_key (char * public_key, char * in, int in_len, char * out, int * out_len) {

  RSA * rsa = createRSA ((unsigned char *) public_key, 1);
  *out_len = RSA_public_decrypt (in_len, (unsigned char *)in, (unsigned char *) out, rsa, RSA_PKCS1_PADDING);

  if (*out_len == -1)
    return FALSE;
  else
    return TRUE;

}

// create RSA object 
RSA *createRSA(unsigned char *key, int public) {
   RSA *rsa = NULL;
   BIO *keybio;
   keybio = BIO_new_mem_buf(key, -1);
   if (keybio == NULL) {
     printf("Failed to create key BIO");
     return 0;
   }
   if (public) {
     rsa = PEM_read_bio_RSA_PUBKEY(keybio, &rsa, NULL, NULL);
   } else {
     rsa = PEM_read_bio_RSAPrivateKey(keybio, &rsa, NULL, NULL);
   }
   if (rsa == NULL) {
     printf("Failed to create RSA");
   }
   return rsa;
}
```

and then the code in the TA

```C
static TEE_Result test_encrypt_ta(TEE_Param params[4]) {

  char * in = (char *)params[TEST_STRING].memref.buffer;
  int in_len = params[TEST_STRING].memref.size;

  char encrypted [512];
  int encrypted_len;

  encrypt_using_private_key (in, in_len, encrypted, &encrypted_len);
  memcpy(params[TEST_EN_DECRYPTED].memref.buffer, encrypted, encrypted_len);
  params[TEST_EN_DECRYPTED].memref.size = encrypted_len;
  params[TEST_RC_POS].value.a = ALL_OK;
  return TEE_SUCCESS;

}

BOOLEAN encrypt_using_private_key (char * in, int in_len, char * out, int * out_len) {

   TEE_Result ret = TEE_SUCCESS; // return code
 	TEE_ObjectHandle key = (TEE_ObjectHandle) NULL;
   TEE_Attribute rsa_attrs[3];
   void * to_encrypt = NULL;
   uint32_t cipher_len = 256;
   void * cipher = NULL;

   rsa_attrs[0].attributeID = TEE_ATTR_RSA_MODULUS;
 	rsa_attrs[0].content.ref.buffer = CA_modulus;
 	rsa_attrs[0].content.ref.length = SIZE_OF_VEC (CA_modulus);

 	rsa_attrs[1].attributeID = TEE_ATTR_RSA_PUBLIC_EXPONENT;
 	rsa_attrs[1].content.ref.buffer = CA_public_key;
 	rsa_attrs[1].content.ref.length = SIZE_OF_VEC (CA_public_key);

 	rsa_attrs[2].attributeID = TEE_ATTR_RSA_PRIVATE_EXPONENT;
 	rsa_attrs[2].content.ref.buffer = CA_private_key;
 	rsa_attrs[2].content.ref.length = SIZE_OF_VEC (CA_private_key);

   ret = TEE_AllocateTransientObject(TEE_TYPE_RSA_KEYPAIR, 1024, &key);
   ret = TEE_PopulateTransientObject(key, (TEE_Attribute *)&rsa_attrs, 3);
   to_encrypt = TEE_Malloc (in_len, 0);
   cipher = TEE_Malloc (cipher_len, 0);
 	TEE_MemMove(to_encrypt, in, in_len - 1);
   if (!perform_rsa_operation (key, TEE_MODE_ENCRYPT, to_encrypt, in_len, cipher, &cipher_len)) {
     DMSG("Encrypt failed : 0x%x", ret);
     return TEE_ERROR_BAD_PARAMETERS;
   }

   memcpy (out, cipher, cipher_len);
   *out_len = cipher_len;
   out[cipher_len] = '\0';
   DMSG("Return:          %s", out);
   DMSG("Return lenght:   %i", *out_len);

   return TRUE;
}

#define SIZE_OF_VEC(vec) (sizeof(vec) - 1)

uint8_t CA_modulus[] =
"\xbe\x5c\xe7\x5f\xef\xd6\x8b\x23\xaf\x9f\xa5\x44\xfc\xa4\x9a"
"\x94\x0a\xc8\x67\x57\x30\x6d\x20\x4b\xa0\xee\xd6\x5f\x07\x9b"
"\x4a\x98\x5d\xcf\x9a\xce\xae\xaa\xa9\x9b\xeb\xdf\xdc\xde\xb9"
"\xfc\x3f\x54\xb2\x93\x7d\xe2\x9e\x29\x52\x57\xd4\x3d\xbc\x4c"
"\x89\xa7\xe9\xc5";

uint8_t CA_public_key[] =
"\x01\x00\x01";

uint8_t CA_private_key[] =
"\x48\x30\x89\x19\xcb\xa5\x2b\xac\xc3\xcc\x21\xeb\x90\x77\x87"
"\x9b\x3e\x9f\x92\xf8\xf0\x87\x61\xa8\xec\x85\xc6\x4b\xd1\x61"
"\xa5\x9e\x8b\xc7\xa1\x5a\x72\xf0\x04\xc8\x04\x5d\x5e\x52\x18"
"\x5c\xd4\x68\x82\x21\x17\xdd\xa1\xcc\x42\x87\xe5\x84\xe1\x58"
"\x20\xc2\x03\x7d";


BOOLEAN perform_rsa_operation (TEE_ObjectHandle key, TEE_OperationMode mode,
    void *in_chunk, uint32_t in_chunk_len,
    void *out_chunk, uint32_t *out_chunk_len) {

  TEE_ObjectInfo info;
  TEE_OperationHandle handle = (TEE_OperationHandle) NULL;
  TEE_Result ret = TEE_SUCCESS;

  TEE_GetObjectInfo (key, &info);
  ret = TEE_AllocateOperation (&handle, TEE_ALG_RSAES_PKCS1_V1_5, mode, info.maxObjectSize);
  ret = TEE_SetOperationKey(handle, key);

  if (mode == TEE_MODE_ENCRYPT) {
    DMSG ("Encrypting values\n");
    ret = TEE_AsymmetricEncrypt (handle, (TEE_Attribute *)NULL, 0, in_chunk, in_chunk_len, out_chunk, out_chunk_len);
  }

  if (mode == TEE_MODE_DECRYPT) {
      DMSG ("Decrypting values\n");
      ret = TEE_AsymmetricDecrypt (handle, (TEE_Attribute *)NULL, 0, in_chunk, in_chunk_len, out_chunk, out_chunk_len);
  }

	TEE_FreeOperation(handle);
  return TRUE;
}

```

**Comment by ursus-the-bear** [comment]
Does anybody have an idea what is wrong here?

**Comment by etienne-lms** [comment]
I don't know much about the rsa formating numbers. Crosscheck this part.
Encrypting the same data from opssl and from the TA get diferrent results?

**Comment by ursus-the-bear** [comment]
@etienne-lms Thank you for taking the time to look at my problem 👍 

1. The RSA formatting numbers seem fine, I have rechecked then (the little there is to check).

2. No, encrypting in openssl (CA) and in the TA do not get me the same values (unless printf and DMSG are displaying the values differently). In the attached picture I encrypted the same value (ABCDEFGHIJKLMNOPQRSTUVWXYZ) in both the CA (in red) and the TA (in blue) and, as you can see the values displayed are not the same. I am using (what I think are) the same keys.  

Any other thoughts?

<img width="1309" alt="screen shot 2017-08-16 at 14 31 47" src="https://user-images.githubusercontent.com/5219580/29363700-4718c51a-8291-11e7-93c4-54e4cd8e7128.png">

**Comment by etienne-lms** [comment]
if the 2 environments do not produce the same content, i think the key materials are not the same in some ways. endianess ?

**Comment by ursus-the-bear** [comment]
@etienne-Ims Good point. I am running in QEMU on an Ubuntu decktop - I thought as both the CA and the TA are running in QEMU (2 terminals) they are the same. Am I wrong in my thinking?

**Comment by etienne-lms** [comment]
I think you are right: I would expect both CA and TA in LE. Yet both RSA implementation are quite well proven now, so there might be something bad with the key materials.

**Comment by ursus-the-bear** [comment]
@etienne-lms when you say "key materials" what do you mean exactly? I created the key using openSSL and the `openssl genrsa -out private.pem 2048` command. I then extracted the public key using the `openssl rsa -in private.pem -outform PEM -pubout -out public.pem` command. I then got the modulus etc. using the command `openssl rsa -in priv_key -text`. As far as I can see that is all perfect. I did do two things -> remove the leading 00 that openSSL has (when doing `openssl rsa -in priv_key -text`).

Would I still be able to encode and decode if I had a problem with the key? That is the thing that bugs me the most!

I did some further debugging and found the the error when I do a decrypt in the TA comes from this line:

    err = pkcs_1_v1_5_decode(tmp, x, LTC_PKCS_1_EME, modulus_bitlen, out, outlen, stat);

That means that it passes all the valid padding, length tests etc but then cannot decode - I debugged into the pkcs_1_v1_5_decode function and am getting multiple errors:

CRYPT_INVALID_PACKET always gets returned -> in the code I get 3 errors found:

	error 1: msg[0] != 0x00
	error 2: /* here was no octet with hexadecimal value 0x00 to separate ps from m. */
	error 3: if (*outlen < (msglen - (2 + ps_len + 1))) {

From this I deduced that maybe we did need a 0x00 before the public_key so tried with 

uint8_t CA_public_key[] =
"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
"\x00\x01\x00\x01”;

And also tried to put the 0x00 back into the private key and tried all permutations - no go!

Does this info help you any?

**Comment by ursus-the-bear** [comment]
Anybody else have an idea? @jforissier could you maybe weigh in? I have rechecked everything and I cannot find any errors. I have checked the 4000 regression tests but also haven't found anything that could help me!

**Comment by jforissier** [comment]
@ursus-the-bear can you post the full code please? Most convenient for me would be a fork of https://github.com/linaro-swg/hello_world. Use the master branch as a starting point and stick your code in it. Then give me the URL so that I can point hello_world in my QEMU environment to your own branch. I want to be able to `make run`, then invoke `hello_world` and see it fail. Hopefully I can troubleshoot from that.

**Comment by ursus-the-bear** [comment]
@jforissier thank you so much - you are a star 🥇 

I have never done a fork before but have given it a try. Here is my test code: https://github.com/ursus-the-bear/hello_world - I think I added you correctly? I have the same code in another private repo that I was using to test - RSA - I just added you there as well.

Thank you again, I am going out of my mind trying to find the error!

**Comment by ursus-the-bear** [comment]
@jforissier I forgot to say but the /bin that is created is called /bin/**rsa** - I have included the common.mk, qemuxxx.mk files to compile.

**Comment by jforissier** [comment]
@ursus-the-bear I can access your hello_world repo, I will try it tomorrow.

**Comment by ursus-the-bear** [comment]
@jforissier Thank you. If there is anything I can go to make it easier for you to debug please let me know!

**Comment by jforissier** [comment]
https://github.com/ursus-the-bear/hello_world/pull/1

**Comment by ursus-the-bear** [comment]
Thank you for the hello_world program. I am looking into it :o) have a great weekend!

**Comment by ranjithvs** [comment]
@ursus-the-bear I am having the issue.. Is it working for you. can you share the code..?

**Comment by ursus-the-bear** [comment]
@ranjithvs Yes, Jerome helped me and now it works perfectly :o) The code is attached - if you need any help with it just drop me a line.

[RSA.zip](https://github.com/OP-TEE/optee_os/files/1238029/RSA.zip)

I created my own RSA app as I did not want to replace the hello_world example -> I have included the .mk files (common.mk, qemu*.mk) -> search for RSA and copy those lines to your files.

**Comment by ranjithvs** [comment]
@ursus-the-bear @jforissier Thank you...Let me utilize your code....:)

**Comment by PedroRibeiro95** [comment]
@ursus-the-bear Hello, I'm trying to do the same thing (encrypt with private/decrypt with public). However, looking at the contents from your RSA.zip, it seems that you're doing the opposite (encrypt with public/decrypt with private). Is this correct? Thanks.

**Comment by ursus-the-bear** [comment]
Hi Pedro, you are correct, I made quite a mistake with my code. Here is the code that was corrected Jerome in the end. Hope it helps 😊 
[RSA.zip](https://github.com/OP-TEE/optee_os/files/1696344/RSA.zip)

**Comment by PedroRibeiro95** [comment]
Thanks @ursus-the-bear , I'll take a look at it!

**Comment by Xinyao90** [comment]
> ted Jerome in the end. Hope

@ursus-the-bear Hi, I've run your code for the four encryption processes: 1. local_encrypt_and_decrypt (); 2. local_encrypt_and_decrypt_in_secure_world (); 3. encrypt_in_secure_world (); 4. decrypt_in_secure_world ();
The results printed is not as expected.
For test 1 and 2, although both of them can encrypt and decrypt it to its original message, however, the encrypted message are different.
For test 3, and 4, both tests cannot decrypt to its original  message.

Is this the latest corrected code?

**Comment by ursus-the-bear** [comment]
Yes, that is the last bit of code that I had

**Comment by ursus-the-bear** [comment]
I assume you are using the code from the RSA.zip file (https://github.com/OP-TEE/optee_os/issues/1749#issuecomment-363179872)

**Comment by Xinyao90** [comment]
Yes, this is the code I'm using, it really helps me to get started! You can see in the attached screenshots for the four tests results. It has the issue I mentioned above. Could you give some suggestions? Thanks a lot!
![Screenshot from 2020-10-20 06-42-52](https://user-images.githubusercontent.com/7366993/96581625-b7578b80-129f-11eb-948f-6a3002b75ac3.png)
![Screenshot from 2020-10-20 06-43-44](https://user-images.githubusercontent.com/7366993/96581624-b7578b80-129f-11eb-9923-1447e8aa829b.png)
![Screenshot from 2020-10-20 06-52-17](https://user-images.githubusercontent.com/7366993/96582497-fe924c00-12a0-11eb-95ee-b33c6c96d2e3.png)
![Screenshot from 2020-10-20 06-52-59](https://user-images.githubusercontent.com/7366993/96582520-05b95a00-12a1-11eb-8ee8-8043893e852e.png)

**Comment by ursus-the-bear** [comment]
sorry but I no longer have access to the environment to see what the problem is. I haven't done any more work with TAs since doing my Masters, sorry!

**Comment by Xinyao90** [comment]
@jforissier Could you help me to take a look at the encryption/decryption discrepancy? I'm using the latest code author provided and revised by you.

**Comment by ursus-the-bear** [comment]
I had a quick look at the code and all seems ok, maybe there have been updates to the tooling and they are now using different en/decryption settings? I no longer have a Pi nor do I have OP/TEE installed anywhere - sorry!
