### ISSUE TITLE
TA flags in user_ta_header_defines.h

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1750]
OPTEE comes with a hello world TA, which has the following flags in the user_ta_header_defines.h:

`TA_FLAGS                    (TA_FLAG_MULTI_SESSION | TA_FLAG_EXEC_DDR)`

I wanted to ask where to find the set of all flags that can be used in the configuration. Is [this code](https://github.com/OP-TEE/optee_os/blob/c04e5c1de8303307c8ed95d7c6119cdef5488b9d/lib/libutee/include/user_ta_header.h#L34) indicating the whole list ?

Also, what is the meaning of the following flags:
> TA_FLAG_USER_MODE
> TA_FLAG_EXEC_DDR

**Comment by etienne-lms** [comment]
Yes, you point the right header file where TA property flags are defined.
Good spoting this part is missing in the docs.

At [line 58 from your reference](https://github.com/OP-TEE/optee_os/blob/c04e5c1de8303307c8ed95d7c6119cdef5488b9d/lib/libutee/include/user_ta_header.h#L58) you can see the property strings related to the flags. GPD TEE Internal Core API describes most of them ("gpd.ta.Xxx"). Few are optee extensions ("op-tee.xxxx").  For the 2 you pointed at, there are no string equivalence parseable from the TA.
* `TA_FLAG_USER_MODE` specifies your TA executes in secure userland. By definition in optee and TA is an application and hence executes in unprivileged level/mode. If you don't set it, optee kernel will act as if it is set.
* `TA_FLAG_EXEC_DDR` specifies that your TA executes in DDR. Hmm... it is mandated but useless and potentially false. In aimed at specifying some security level fr the TA execution memory (external/internal). As is it mandated, your TA shall set this flag where ever optee executes your TA.
