### ISSUE TITLE
Limit on dynamic TA binary (code) size 

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1751]
I wanted to ask if there is any limit on the binary size of a dynamic TA. The TA configuration header file allows STACK and HEAP sizes to be specified. I was wondering if OPTEE puts any limit on the size of the TA binary, because it will be loaded into memory when the TA instance is first created.

Thanks.

**Comment by vchong** [comment]
It's platform specific. Each platform allocates a certain amount of memory for TA RAM. E.g. [hikey](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/platform_config.h) has 15MB. If 1 TA uses up all of these, then there'll be no 'room' to run other TAs.

**Comment by a2t2** [comment]
If I have a TA, is it somehow possible to tell how much of that 15 MB is being utilized for that specific TA ? Thanks

**Comment by a2t2** [comment]
Also to double check with you, is the 15 MB limit on hikey for all TAs combined OR is it per TA ? Thanks

**Comment by vchong** [comment]
I'm not sure if there's a specific way to tell. I checked with one of the maintainers and was told you can get an estimate by adding the size of the TA itself and the stack. The heap is included in the size of the TA itself so no need to add it.

15MB limit is for all TAs combined. Secure world doesn't really have a lot of memory to spare.

**Comment by a2t2** [comment]
Okay thank you.
