### ISSUE TITLE
Print current time in TA

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1758]
I want to measure the time taken during my TA invocation. I want to do something similar to the following code which is using C in Linux:

```
#include <sys/time.h>
#include <stdio.h>
void main() {
                struct timeval start, end;
                gettimeofday(&start, NULL);  
                // Do some operation
                gettimeofday(&end, NULL);
                printf("start: %d secs, %d usecs\n",start.tv_sec,start.tv_usec);
                printf("end: %d secs, %d usecs\n",end.tv_sec,end.tv_usec);
}

```
What would be the equivalent of the above code in OPTEE TA  ?

Thanks.

**Comment by jforissier** [comment]
Hi @a2t2,

If millisecond resolution is enough, you can use `TEE_GetSystemTime(&t)` then use `t.seconds` and `t.millis`.

**Comment by a2t2** [comment]
Okay that should work. Thanks.

**Comment by a2t2** [comment]
I tried a case where I have two TAs. TA 1 invokes TA 2.

I tried using `TEE_GetSystemTime(&t)` before TA 1 invokes TA 2, and after invocation finishes. 

TEE_GetSystemTime(&time1);
// TA 1 invokes TA 2
TEE_GetSystemTime(&time2)

But it doesn't always help me because `time2` sometimes comes out to be less than `time1`and I get a negative difference. What is the reason for this ?
I see there is also a `TEE_GetTAPersistentTime` API. Is that the one applicable in this case ?
Please advice.

**Comment by vchong** [comment]
How are you actually calculating time differences? Refer to TEE_TIME_* macros in https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/include/utee_defines.h.

**Comment by a2t2** [comment]
I was just using `time2.millis - time1.millis`. I saw negative result twice. Rest of the time I saw positive difference.

**Comment by vchong** [comment]
It's not a negative result/difference. You need to consider wraparounds. After 1000 miliseconds, `t.millis` becomes 0 again and `t.seconds` is increased by 1. Yes, just use TEE_TIME_SUB which will take care of wraparounds for you.

**Comment by a2t2** [comment]
Okay thanks
