### ISSUE TITLE
I got some error when executed TA

### ISSUE THREAD

**Issue by prz999** [OP-TEE/optee_os#176]
Hi,

I got a error when I executed TA on my porting board. It is seems caused by multi-core running. Here is the error log. 

ERR [0x0] TEE-CORE:tee_pager_print_error_abort:101: data-abort at 0xfc053d6c
FSR 0x1008 PC 0xfc005434 TTBR0 0xFC06804A CONTEXIDR 0x0
CPUID 0x80000f01 DBGPCSR 0x0 CPSR 0x600001d3 (read from SPSR)
ERR [0x0] TEE-CORE:tee_pager_handle_abort:190: Unexpected page fault! Trap CPU
INFO: rcu_sched detected stalls on CPUs/tasks: { 1} (detected by 0, t=2102 jiffies, g=4294967196, c=4294967195, q=18)
Task dump for CPU 1:
hello_world     R running      0   720    705 0x00000000

I want to know have you ever see this problem before? 

Thanks,
Ruizhi

**Comment by prz999** [comment]
I has tested that this problem is happened when lock_global executed.

**Comment by jenswi-linaro** [comment]
Hi,

It looks like a synchronous external abort. Is memory mapped OK etc?

Regards,
Jens

**Comment by prz999** [comment]
Actually it can't work either if I closed the MMU. The address 0xfc053d6c can read OK on function lock_global. But the cpu_spin_lock executed will cause this problem.

**Comment by jenswi-linaro** [comment]
It sounds like some limitation in your hardware. Please check the hardware documentation to find out in which memory it can support exclusive access or if something else needs to be configured too before exclusive access can be supported.

**Comment by prz999** [comment]
Hi
