### ISSUE TITLE
SPI register read/write from PTA hangs the completes system. 

### ISSUE THREAD

**Issue by ajithpv** [OP-TEE/optee_os#1770]
I'm trying to make a SPI controller and SPI device interaction on a custom platform (not Hikey) and taking PL022 SPI source for HIkey as reference.

If I call the SPI controller registers (with either read32 or write32) from the `core/arch/arm/*/main.c`, then the registers can be read or write during the OP-TEE booting and then Linux will load after that.
But, the same register read or write is not working if I call it via PTA (after Linux boots and console comes up). If i call the read32/write32 to the SPI register from PTA, then the whole system will hangs and the only way to get out of it is to restart the platform.

I would like to tell you that, I have enabled the SPI in my Linux Device tree (dtb) and the clocks are actually taking from the Linux (clock support is not present for my platform yet in OP-TEE).
I'm using the below code for registering the SPI base in OP-TEE:
`register_phys_mem(MEM_AREA_IO_SEC, SPI_BASE, SPI_REG_SIZE); ` and using the below one to get the virtual address in OP-TEE:
`core_mmu_get_va(SPI_BASE, MEM_AREA_IO_SEC);`
also, I have confirmed that the virtual address is passing correctly when I call the register operation from TA (i.e., SPI virtual base address from OP-TEE boot and TA side register read SPI base are same).

May I know why this is happening since there is no clue shown on console regarding the hangs.

**Comment by jforissier** [comment]
Use `MEM_AREA_IO_NSEC` maybe? Just an idea, since you're saying the SPI is configured by Linux.

**Comment by ajithpv** [comment]
Thank you @jforissier for your suggestion.
I have tried the `MEM_AREA_IO_NSEC` but it didn't help me..Still, the same issue is coming.
May I know how to check the root cause if it didn't show any panic or clues at hanging OP-TEE?

**Comment by MrVan** [comment]
If after linux's boots up, you could not access SPI module, I think the clk to spi controller is powered off with linux runtime pm or unused clk disabled. You could pass clk_ignore_unused in bootargs to kernel to see whether it works. If still not works, try patch like https://github.com/OP-TEE/optee_os/pull/1729/commits/e2394a2c1fde2240b7e2645b34d7873eb56f5b29, the patch is for i.MX7D, but you could refer for 6UL.

**Comment by ajithpv** [comment]
@MrVan Thank you for your help. but, I'm a bit confused here.
AFAIK, Linux will disable the unused module clocks but I have enabled the SPI in my device tree with SPIDEV. Moreover, when I run the Linux SPI loop-back test(i.e. mxc_spi_test1.out) from unit_tests folder, it is working fine.
Anyway I will check this point and will update on the same.

**Comment by ajithpv** [comment]
@MrVan After removing the clock disabling routine from the probe function of SPI master, the hang issue got resolved.
By default, the probe function is enabling the clocks and then disabling it at the end.
Thank you very much
