### ISSUE TITLE
How OP-TEE CSU is controlled in i.MX6UL?

### ISSUE THREAD

**Issue by ajithpv** [OP-TEE/optee_os#1773]
I would like to know whether `init_csu` function is setting the CSU in i.MX6UL or the CSU settings are configuring in the U-boot itself.
From `core/arch/arm/plat-imx/imx6ul.c` what I understood is that, the CSU is granted to all the CSL modules and then locking it to avoid software changes afterwards. is that correct?

Whether the read and write should perform on the physical address or the virtual address? Since, I didn't see any virtual address mapping in the file, assuming that, the given CSU code is performing it on the physical address.
When I try to read the CSU from another module` init()`, then I'm getting `translation fault` with physical address!

**Comment by ajithpv** [comment]
@MrVan could you please give some hint?

**Comment by MrVan** [comment]
@ajithpv yes. Configure CSL and Lock it. CSL is not related to virtual/physical address. It is about master/pheriphial access permission. For example, you could configure OCOTP to be secure read/write, non-secure read. If want to access CSU in other modules, you need to register its memory into mmu, and use core_mmu_get_va to get the runtime address.

**Comment by ajithpv** [comment]
Thank you @MrVan for your reply.
I'm actually trying to see whether the CSU is set properly or not for a particular module.
For example, I want to know eCSPI1 have access permission which is setting through CSL18 register's [23:16] bits.
I hope registering CSU to MMU and take virtual address fro reading  this will shows the correct settings done for the CSL18.
PS: This check is to resolve the https://github.com/OP-TEE/optee_os/issues/1770
