### ISSUE TITLE
Question: About benchmark

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#1774]
# benchmark /usr/sbin/hisi_demo_client
1. Opening Benchmark Static TA...
2. Allocating per-core buffers, cores detected = 4
3. Starting origin host app /usr/sbin/hisi_demo_client ...
Dumping timestamps to /usr/sbin/hisi_demo_client.ts ...
===================================================================================================================
4. Done benchmark

# cat /usr/sbin/hisi_demo_client.ts 
0	161512948736	0xffffff800859357c	KMOD
0	161512953920	0x7e008a5f	CORE
0	161512958464	0xffffff800859359c	KMOD
1	696563878272	0xffffff800859357c	KMOD
1	696563905472	0xffffff800859359c	KMOD
1	696564008896	0xffffff800859357c	KMOD

Question:
 Why the time stamp between cpu0 and cpu1 is so different? 
 Is there anything I missed?

**Comment by igoropaniuk** [comment]
Hello @airbak,
Although ARM PMU cycle counters are enabled at the same time (on each core), still there are reasons that can cause such behavior:
1. First possible reason - power management: frequency scaling (reduced clock rate); or core was in wait-for-interrupt or wait-for-events state (PMU also doesn't count CPU cycles in these states), or basically one of the cores was just offline for some period of time.
2. ARM big.LITTLE. I'm not sure if we have any SoC (from the list, where OP-TEE is supported), that is based on this architecture, but having power-hungry fast cores with battery-saving and slower cores (and as a result running with lower frequency) can also explain this behavior.
3. "Collision" with linux kernel perf subsystem. That's an issue that we are facing now and trying to solve, when perf subsystem is used while running OP-TEE benchmarks (for examples, one of the counter was simply restarted). Currently, I'm working on on re-using it's kernel API (which is, frankly speaking, not so functional, as userspace, but anyway) for enabling and configuring PMUs.

Regarding your question about the tool for analyzing results - it's also in the sate of active development now.

Hope it helps,
Igor

**Comment by airbak** [comment]
Thanks for your reply :)
