### ISSUE TITLE
Questions about the ksan feature？

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1777]
@jenswi-linaro 
I noticed that the ksan feature is only claimed for the plat-vexpress-qemu_virt.  But i want to use it for my platform, is there any problem ,and how to enable it(I don't quite understand how the `CFG_CORE_SANITIZE_KADDRESS` is caculated)?

**Comment by jenswi-linaro** [comment]
There's no problem with using ksan on other platforms. There's only the catch with `CFG_ASAN_SHADOW_OFFSET`. There's a hint in `core/arch/arm/plat-vexpress/conf.mk` how to calculate it. If you don't get it right there's asserts in `init_asan()` that will catch it.

**Comment by prime-zeng** [comment]
Thank you,  i got it:  
` CFG_ASAN_SHADOW_OFFSET is calculated as:  (&__asan_shadow_start - (CFG_TEE_RAM_START / 8)`
I don't quite understand it,  for example,  CFG_TEE_RAM_START = 0x40000000,  &__asan_shadow_start  = 0x41000000,  and CFG_ASAN_SHADOW_OFFSET = 0x39000000 which is outside the op-tee's virtual memory space.

**Comment by prime-zeng** [comment]
@jenswi-linaro seems bug here?

**Comment by jenswi-linaro** [comment]
No, I think it's OK. The way `CFG_ASAN_SHADOW_OFFSET` is used isn't entirely intuitive. It's optimized to have an cheap calculation when using it, check `va_to_shadow()` in `core/kernel/asan.c`.

**Comment by prime-zeng** [comment]
@jenswi-linaro   Got it, thank you so much.
