### ISSUE TITLE
Problem of give up CPU in OPTEE_OS

### ISSUE THREAD

**Issue by pengcong8** [OP-TEE/optee_os#1779]
Dear sir:
     I have a question to ask you . And the question is :  Does it exist this kind of function that has the same function of Linux's usleep in optee_os . In Linux  kernel, when you used the function of  usleep in your codes, it will give up CPU when it called usleep . 
e.g
 void hello_world(void)
{
   printk(" nice to meet you !\n");
   usleep(100);  /** this process will give CPU ,and it let other process to occupy CPU and run **/
   printk(" all things go well !\n");
}
 thank you so much .

**Comment by pengcong8** [comment]
waiting for your answer , thanks

**Comment by jenswi-linaro** [comment]
I suppose `tee_time_wait()` does more or less that.

**Comment by pengcong8** [comment]
Dear jenswi-linaro:
        1. Does the process will give up CPU when it called tee_time_wait() in the codes ? 
        2. And  I also want to know  that tee_time_wait() can be used or not in TA(Trust Application -- Secure EL0 ) ? 
         thanks

**Comment by jenswi-linaro** [comment]
If you're in a TA then `tee_time_wait()` isn't available, instead you can use `TEE_Wait()`. Either function will result in `msleep_interruptible()` in the Linux kernel being called.

**Comment by pengcong8** [comment]
Dear jenswi-linaro: 
     TEE_Wait(100) stands for 100 seconds or microseconds ? thanks

**Comment by jenswi-linaro** [comment]
Yes

**Comment by pengcong8** [comment]
Dear sir :

**Comment by pengcong8** [comment]
Dear sir :  I mean it stands for 100 seconds or it stands for 100 microseconds , if i called function TEE_Wait(100) in TA. thanks

**Comment by jforissier** [comment]
@pengcong8 don't you have the GP Internal Core API Specification? You may download it from https://www.globalplatform.org/specificationsdevice.asp.
`TEE_Wait()` takes a number of milliseconds or `0xFFFFFFFF` `(TEE_TIMEOUT_INFINITE)` to wait forever (or more exactly: until cancellation).

**Comment by pengcong8** [comment]
thanks jforissier & jenswi-linaro. thank you so much .
