### ISSUE TITLE
REE FS just could be used by one TA

### ISSUE THREAD

**Issue by Yanjiong** [OP-TEE/optee_os#1780]
Hi Experts,

Since "dirfile.db.hash" in RPMB which hold a hash representing the state of REE FS is encrypted by tee_fs_fek_crypt and encryption done in tee_fs_fek_crypt will take current session's UUID as message param of do_hmac. So if TA A firstly write file to REE FS and then TA B trying to read file in REE FS will result in failure in hash check. 

I think this should be bug in current implementation. 

"dirfile.db.hash" in RPMB should not depends on any TA/PTA, the encryption of the file should be common to all TA/PTA.

BR.
Wang Yanjiong

**Comment by jenswi-linaro** [comment]
Hi,

I thought that was already taken care of by using `tee_rpmb_fs_raw_open()` (which supplies a uuid of only zeroes) when operating on that filename.
I haven't been able to reproduce the error. Do you have a test case that can reproduce the error?

Thanks,
Jens

**Comment by jforissier** [comment]
+1
I would expect xtest 6015 "Storage isolation" to fail, should we had an issue with the hash file encryption. Tested on QEMU with "make CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y".

**Comment by jenswi-linaro** [comment]
Yeah, I took it one step further and used `storage2_ta_uuid` for the first thread in 6016.

**Comment by Yanjiong** [comment]
I don't have a test case to reproduce but found the issue in my real use cases.

Hash file open by tee_rpmb_fs_raw_open() will use zeroes uuid, but when read/write, the fek will be encrypted/decrypted with current session uuid.

**Comment by airbak** [comment]
@jenswi-linaro , please help to solve it.
tee_rpmb_fs_raw_open() generate FEK with zeroes uuid, but encrypt_block() and decrypt_block() decrypt FEK with current uuid. 
TESTCASE: TA1 write fileA, TA2 write fileB, TA1 will read fileA failed because init_head_from_data() return TEE_ERROR_SECURITY.  dirf.db will recreate, then fileA and fileB will never be read again.
6015 and 6016 have not covered this scenes.

**Comment by jenswi-linaro** [comment]
@airbak, would you mind supplying the test case as code? Preferably as a pull request to https://github.com/OP-TEE/optee_test

**Comment by airbak** [comment]
@jenswi-linaro OK, I will pull request before this friday.

**Comment by airbak** [comment]
@jenswi-linaro 
https://github.com/OP-TEE/optee_test/pull/238
