### ISSUE TITLE
make: *** No rule to make target `toolchains'.  Stop.

### ISSUE THREAD

**Issue by guojie1689** [OP-TEE/optee_os#1781]
Hi Experts,

I follow the documentation prompts as follows
$ mkdir -p $HOME/devel/optee
$ cd $HOME/devel/optee
$ repo init -u https://github.com/OP-TEE/manifest.git -m ${TARGET}.xml [-b ${BRANCH}]
$ repo sync

$ cd build
$ make toolchains

But remind me this error :
gj@gj-VirtualBox:~/devel/optee/build$ make toolchains
make: *** No rule to make target `toolchains'.  Stop.

Please help me ，Thanks for your answers.

**Comment by jforissier** [comment]
Hi @guojie1689,

What ${TARGET}?

**Comment by guojie1689** [comment]
Hi @jforissier ：

Thanks . 

repo init -u https://github.com/OP-TEE/manifest.git -m default.xml

**Comment by jforissier** [comment]
Did `repo sync` succeed? You should have a `Makefile` and `toolchain.mk` under `build/`.

**Comment by guojie1689** [comment]
repo sync successed. 
toolchain.mk under build/.  but not find Makefile. 
Does the Makefile need to create it  myself?

**Comment by jforissier** [comment]
`cd build; ln -s qemu.mk Makefile`

But that should be taken care of automatically because of [this](https://github.com/OP-TEE/manifest/blob/master/default.xml#L36). You're not trying to build on Windows (cygwin/MinGW), are you?

**Comment by guojie1689** [comment]
Thanks . I'm build on Ubuntu system. I will try it .

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
