### ISSUE TITLE
Crash on imx6qsabrelite when boot optee os

### ISSUE THREAD

**Issue by tranhuanltv** [OP-TEE/optee_os#1782]
When I run optee os version 2.4.0 on my board imx6qsabrelite (2GB RAM) it working fine but when I switch to version 2.5.0 get this error: [0x0] TEE-CORE: Panic at core/arch/arm/kernel/generic_boot.c:567 <get_memory>. Do you guys have any ideas about this problem.

I make changes fixed ram size from 1GB -> 2GB:
platform_config.h:122 DRAM0_SIZE from 0x40000000 -> 0x80000000
platform_config.h:300 CFG_DDR_TEETZ_RESERVED_START from  0x4E000000 -> 0x8E000000

Build Script:
make PLATFORM=imx-mx6qsabrelite ARCH=arm CFG_TEE_CORE_LOG_LEVEL=4 DEBUG=1 CFG_BUILT_IN_ARGS=y CFG_PAGEABLE_ADDR=0 CFG_NS_ENTRY_ADDR=0x12000000 CFG_DT_ADDR=0x18000000 CFG_TEE_GDB_BOOT=y CFG_DT=y CFG_BOOT_SECONDARY_REQUEST=y CFG_PSCI_ARM32=y CFG_BOOT_SYNC_CPU=n CFG_MX6Q=y
mkimage -A arm -O linux -C none -a 0x8dffffe4 -e 0x8e000000 -d ./out/arm-plat-imx/core/tee.bin uTee

Log:
fatload usb 0:1 0x12000000 zImage;fatload usb 0:1 0x18000000 imx6q-sabrelite.dtb;fatload usb 0:1 0x20000000 uTee_2.5.0;setenv bootargs console=ttymxc1,115200 root=/dev/sda2 rootwait rw;bootm 0x20000000 - 0x18000000
reading zImage
5028504 bytes read in 278 ms (17.3 MiB/s)
reading imx6q-sabrelite.dtb
38546 bytes read in 31 ms (1.2 MiB/s)
reading uTee_2.5.0
417844 bytes read in 49 ms (8.1 MiB/s)
## Booting kernel from Legacy Image at 20000000 ...
   Image Name:
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    417780 Bytes = 408 KiB
   Load Address: 8dffffe4
   Entry Point:  8e000000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 18000000
   Booting using the fdt blob at 0x18000000
EHCI failed to shut down host controller.
   Loading Kernel Image ... OK
   Using Device Tree in place at 18000000, end 1800c691

Starting kernel ...

DEBUG:   [0x0] TEE-CORE:add_phys_mem:524: VCORE_UNPG_RX_PA type TEE_RAM_RX 0x8e000000 size 0x00064000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:524: VCORE_UNPG_RW_PA type TEE_RAM_RW 0x8e064000 size 0x0009c000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:524: CFG_TA_RAM_START type TA_RAM 0x8e100000 size 0x01e00000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:524: CFG_SHMEM_START type NSEC_SHM 0x8ff00000 size 0x00100000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:524: CONSOLE_UART_BASE type IO_NSEC 0x02100000 size 0x00200000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:524: GIC_BASE type IO_SEC 0x00a00000 size 0x00100000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:524: ANATOP_BASE type IO_SEC 0x02000000 size 0x00200000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:524: PL310_BASE type IO_SEC 0x00a00000 size 0x00200000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:537: Physical mem map overlaps 0xa00000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:524: SRC_BASE type IO_SEC 0x02000000 size 0x00200000
DEBUG:   [0x0] TEE-CORE:add_phys_mem:537: Physical mem map overlaps 0x2000000
DEBUG:   [0x0] TEE-CORE:verify_special_mem_areas:462: No NSEC DDR memory area defined
DEBUG:   [0x0] TEE-CORE:add_va_space:563: type RES_VASPACE size 0x00a00000
DEBUG:   [0x0] TEE-CORE:add_va_space:563: type SHM_VASPACE size 0x00a00000
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:690: type IO_SEC       va 0x8a700000..0x8a8fffff pa 0x00a00000..0x00bfffff size 0x00200000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:690: type IO_NSEC      va 0x8a900000..0x8aafffff pa 0x02100000..0x022fffff size 0x00200000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:690: type NSEC_SHM     va 0x8ab00000..0x8abfffff pa 0x8ff00000..0x8fffffff size 0x00100000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:690: type TA_RAM       va 0x8ac00000..0x8c9fffff pa 0x8e100000..0x8fefffff size 0x01e00000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:690: type RES_VASPACE  va 0x8ca00000..0x8d3fffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:690: type IO_SEC       va 0x8d400000..0x8d5fffff pa 0x02000000..0x021fffff size 0x00200000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:690: type SHM_VASPACE  va 0x8d600000..0x8dffffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:690: type TEE_RAM_RX   va 0x8e000000..0x8e063fff pa 0x8e000000..0x8e063fff size 0x00064000 (smallpg)
DEBUG:   [0x0] TEE-CORE:dump_mmap_table:690: type TEE_RAM_RW   va 0x8e064000..0x8e0fffff pa 0x8e064000..0x8e0fffff size 0x0009c000 (smallpg)
DEBUG:   [0x0] TEE-CORE:core_mmu_alloc_l2:249: L2 table used: 1/4
INFO:    TEE-CORE:
DEBUG:   [0x0] TEE-CORE:init_canaries:169: #Stack canaries for stack_tmp[0] with top at 0x8e08e7f8
DEBUG:   [0x0] TEE-CORE:init_canaries:169: watch *0x8e08e7fc
DEBUG:   [0x0] TEE-CORE:init_canaries:169: #Stack canaries for stack_tmp[1] with top at 0x8e08eef8
DEBUG:   [0x0] TEE-CORE:init_canaries:169: watch *0x8e08eefc
DEBUG:   [0x0] TEE-CORE:init_canaries:169: #Stack canaries for stack_tmp[2] with top at 0x8e08f5f8
DEBUG:   [0x0] TEE-CORE:init_canaries:169: watch *0x8e08f5fc
DEBUG:   [0x0] TEE-CORE:init_canaries:169: #Stack canaries for stack_tmp[3] with top at 0x8e08fcf8
DEBUG:   [0x0] TEE-CORE:init_canaries:169: watch *0x8e08fcfc
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_abt[0] with top at 0x8e090538
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x8e09053c
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_abt[1] with top at 0x8e090d78
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x8e090d7c
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_abt[2] with top at 0x8e0915b8
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x8e0915bc
DEBUG:   [0x0] TEE-CORE:init_canaries:170: #Stack canaries for stack_abt[3] with top at 0x8e091df8
DEBUG:   [0x0] TEE-CORE:init_canaries:170: watch *0x8e091dfc
DEBUG:   [0x0] TEE-CORE:init_canaries:172: #Stack canaries for stack_thread[0] with top at 0x8e093e38
DEBUG:   [0x0] TEE-CORE:init_canaries:172: watch *0x8e093e3c
DEBUG:   [0x0] TEE-CORE:init_canaries:172: #Stack canaries for stack_thread[1] with top at 0x8e095e78
DEBUG:   [0x0] TEE-CORE:init_canaries:172: watch *0x8e095e7c
ERROR:   [0x0] TEE-CORE: Panic at core/arch/arm/kernel/generic_boot.c:567 <get_memory>
ERROR:   [0x0] TEE-CORE: pc  0x8e0016dd
ERROR:   [0x0] TEE-CORE: pc  0x8e0195ed
ERROR:   [0x0] TEE-CORE: pc  0x8e00d78f
ERROR:   [0x0] TEE-CORE: pc  0x8e00d811
ERROR:   [0x0] TEE-CORE: pc  0x8e00d9b7
ERROR:   [0x0] TEE-CORE: pc  0x8e00da69
ERROR:   [0x0] TEE-CORE: pc  0x8e00db49
ERROR:   [0x0] TEE-CORE: pc  0x8e00010c

**Comment by MrVan** [comment]
Please cherry-pick 6dc18b3025fbd9d5d36fd0fefcbbeb3cb5fa3ac4 and try again.
