### ISSUE TITLE
How can I get optee_os v2.0.0?

### ISSUE THREAD

**Issue by FormerBuckeye** [OP-TEE/optee_os#1786]
Hi all,

I hope to know if there is a way I can optee v2.0.0's repo. Because when I used "repo sync", I only got the latest version of optee. 

If there is no way, can I just replace the current optee_os with optee_os v2.0.0 and build it inside /devel/optee folder?

Thanks.

**Comment by jforissier** [comment]
Checkout commit 7d0f731 of manifest.git and use the *_stable.xml file for the platform you want to build.

**Comment by FormerBuckeye** [comment]
Hi,

Thank you for your reply. I am new to OPTEE and could you tell me after I execute 
"repo init -u https://github.com/OP-TEE/manifest.git -m hikey_stable.xml",
how I can specify version 2.0.0 to be downloaded? 

Thanks!

**Comment by FormerBuckeye** [comment]
I got it, thanks!

**Comment by FormerBuckeye** [comment]
Hi,

I failed to make arm-tf becasue of one error:

*** No rule to make target '/home/penghui/devel/optee/toolchains/aarch64/lib/gcc/aarch64-linux-gnu/6.2.1/include/stddef.h', needed by 'out/arm/core/include/generated/.asm-defines.s'.  Stop.

I found that there is only version 4.9.1 in /aarch64-linux-gnu directory. How can I make 4.9.1 work?

**Comment by jforissier** [comment]
Error seems to be when building optee_os, not ARM-TF. Try `rm out/arm/core/include/generated/.asm-defines.s`, or `make clean` (looks like a leftover from a previous build attempt).

**Comment by FormerBuckeye** [comment]
Yeah, it works! Thanks!
