### ISSUE TITLE
Using OP-TEE in Android App

### ISSUE THREAD

**Issue by Makht916** [OP-TEE/optee_os#1791]
Hi,

I am working on a project in which I need to use/access OP-TEE in my android app. I have already setup AOSP + OP-TEE on hikey620 board but now I am confused how to use OP-TEE in android.  Do you guys any general guideline or mechanism for using OP-TEE in android? What do I need to do now to make this work?

Regards,

**Comment by vchong** [comment]
The OP-TEE and/or GlobalPlatform APIs are only available as C functions so you need to use JNI to call them from your android app. See https://www3.ntu.edu.sg/home/ehchua/programming/java/JavaNativeInterface.html for an intro to JNI. Once you're familiar with it, you can adapt/replace HelloJNI.c with whatever your Normal World client application is.

**Comment by Makht916** [comment]
Hi, 

I am trying to access OP-TEE Client API methods by JNI and NDK. Right now, I am just trying to include libteec.so in my android app so later I can use the TEE. What I did is to add the libteec.so location in Android.mk file but getting error. I tried all different possibility to include libteec in my Android project but failed. Below is my Android.mk file,

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libteec
LOCAL_SRC_FILES := /usr/local/home/hikey620/out/target/product/hikey/system/lib64/libteec.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/..
include $(PREBUILT_SHARED_LIBRARY)

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES := com_example_cispa_teetest_TEEClient.cpp
LOCAL_LDLIBS += -llog
LOCAL_MODULE := TEEClient
include $(BUILD_SHARED_LIBRARY)

Many thanks in advance.

Regards,

**Comment by Makht916** [comment]
Hi,

I am trying to access the tee_client_api in my android app. All the tee_client_api variable are available to me in my JNI function but when I access the TEEC_InitializeContext or any other method I am getting  **undefined reference to `TEEC_InitializeContext'** error. Below are the changes that I made to my app.

Android.mk
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := $(TARGET_ARCH_ABI)/libteec
LOCAL_SRC_FILES := /usr/local/home/hikey620/out/target/product/hikey/system/lib64/libteec.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := $(TARGET_ARCH_ABI)/libcrypto
LOCAL_SRC_FILES := /usr/local/home/hikey620/out/target/product/hikey/system/lib64/libcrypto.so
include $(PREBUILT_SHARED_LIBRARY)


include $(CLEAR_VARS)
CFG_TEEC_PUBLIC_INCLUDE = /usr/local/home/hikey620/external/optee_client/public/public

LOCAL_MODULE := TEEClient
LOCAL_SRC_FILES := com_example_cispa_teetest_TEEClient.cpp

include $(BUILD_SHARED_LIBRARY) 

JNI Code File:
#include<jni.h>
#include<string.h>
#include <err.h>
#include <stdio.h>
#include <tee_client_api.h>
#include<com_example_cispa_teetest_TEEClient.h>

JNIEXPORT jstring JNICALL Java_com_example_cispa_teetest_TEEClient_helloWorld
  (JNIEnv *env, jobject obj){

    TEEC_Result res;
    TEEC_Context ctx;
    TEEC_Session sess;
    TEEC_Operation op;
    TEEC_UUID uuid ;
    uint32_t err_origin;
    TEEC_InitializeContext(NULL,&ctx);
}

Regards,

**Comment by vchong** [comment]
This is really an android programming question rather than an op-tee issue. Not sure if there are any android experts here so the help you get might be limited. You can refer to https://github.com/OP-TEE/optee_test/blob/master/Android.mk for how to add libteec to Android.mk but the JNI part you'll probably have to figure out yourself since no one has really ever done that here. The user on https://github.com/OP-TEE/optee_os/issues/913 asked a similar question so you might be able to get some references on there as well.

**Comment by Makht916** [comment]
Hi, 
I am having a trouble adding the libteec into my project. I am using "https://github.com/OP-TEE/optee_test/blob/master/Android.mk" file to add the libteec but getting an error that "**include $(LOCAL_PATH)/ta/Android.mk**" not found which Android.mk file is this?

**Comment by vchong** [comment]
Please **refer** to the file to see how libteec is included (i.e. https://github.com/OP-TEE/optee_test/blob/master/Android.mk#L22), NOT use it as-is!

**Comment by Makht916** [comment]
Hi, 

I am getting "TEEC_EEROR_ITEM_NOT_FOUND" error when trying to initialize TEEC_InitializeContext(NULL,&ctx) on my hikey620. AOSP + OPTEE is already deployed on board so what will be possible cause of this error?

Regards,

**Comment by duduscript** [comment]
@Makht916 Hi, have you solved your problem? I'm now have the same problem with yours.

I don't know how to get libteec, is there any documents mention about it?
