### ISSUE TITLE
How to deal with eMMC CID changing when FFU

### ISSUE THREAD

**Issue by peifu** [OP-TEE/optee_os#1794]
Hi,

We heard from some eMMC providers that some fields of eMMC CID would be changed when doing eMMC FFU, such as PRV (Product revision) (CID[bit 55:48]). In that case, it seems we cannot use the whole CID to derive RPMB key.

How can we deal with this? Or did anyone else encounter this issue ? 

B.R.
-Peifu

**Comment by jforissier** [comment]
Hi @peifu,

I wasn't aware of this issue, but I think you're right. We should probably mask off PRV and CRC when deriving the key. Would you like to submit a patch? Thanks.

**Comment by peifu** [comment]
Hi  jforissier,

I create a fixing for this issue. Please have a review.

rpmb: mask off RPV/CRC fields in CID to derive rpmb key #1837
