### ISSUE TITLE
barrier is needed after writing a PTE and before using the mapping 

### ISSUE THREAD

**Issue by stuyoder** [OP-TEE/optee_os#1805]
I found this issue when testing the dynamic shared memory patches. A mapping was created for incoming message arguments (i.e. PTE was written), followed fairly quickly by a read of the memory. It appears the read got executed before the PTE write, resulting in a data abort.

Inserting a dsb() in core_mmu_set_entry_primitive() in core/arch/arm/mm/core_mmu_lpae.c after the PTE update:

   tbl[idx] = desc | pa;

...resolves the issue.

**Comment by stuyoder** [comment]
see https://github.com/OP-TEE/optee_os/pull/1796 for discussion on this

**Comment by etienne-lms** [comment]
Nice catch. A DSB seems missing here.

However, as discussed in #1796, the best place for the memory barrier are at hight level. Here, it appears that a DSB is missing in the function that mapps the registered shm. In this case, I think the `dsb` should be added in `mobj_mapped_shm_alloc()`, after it calls `core_mmu_map_pages()`, at [mobj.c#L571](https://github.com/OP-TEE/optee_os/blob/d720431cdf0060bfd6c3e3d078e747f9491d880d/core/arch/arm/mm/mobj.c#L571).

There is another place where registered dyn-shm are map: when a TA is invoked (and memref parameters mapped). But this code is safe against PTE sync.

**Comment by stuyoder** [comment]
Jen's suggestion in the pull request was to put the fix in core_mmu_map_pages().  I'm going to let you guy's who know the kernel internals to sort out where the fix is needed.

**Comment by jforissier** [comment]
Closing, as this has been addressed in https://github.com/OP-TEE/optee_os/pull/1827.
