### ISSUE TITLE
How to run my  ta and ca on andoid

### ISSUE THREAD

**Issue by bryan370210** [OP-TEE/optee_os#1809]
hi,
I've written a helloworld for test, and it can run in qemu correctly, 
now I have a hikey board, and the optee_android  have been flashed,
how can I run that helloworld‘s ta and ca  in that Android OS ? just copy them into the Android ？

**Comment by vchong** [comment]
> optee_android have been flashed

Which images did you use?

> how can I run that helloworld‘s ta and ca in that Android OS ? just copy them into the Android ？

If optee_android (the correct images) has been flashed, then helloworld's ta and ca should already be included and you can just run `tee_helloworld` from the console or adb shell. You can't copy files built for qemu directly into Android. They're not compatible.

**Comment by bryan370210** [comment]
I want to add my own ca and ta into Android, how can do that?

**Comment by vchong** [comment]
Follow the instructions in https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master to build optee_android for hikey. After step 3.4, before step 3.5, do below:

In `device/linaro/hikey/optee-packages.mk`, add:
```
PRODUCT_PACKAGES += name_of_your_ca
PRODUCT_PACKAGES += uuid_of_your_ta #e.g. 8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta
```

Then you can run `name_of_your_ca` from the console as root. Note that this is on the condition that you have the proper `Android.mk` file for your ca and ta. You can refer to the `Android.mk` file**s** in https://github.com/linaro-swg/hello_world.

**Comment by wxlqaz** [comment]
Hi, 
I have make a small modification in tee_helloworld program and follow the steps in  https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master.  In step 3.7, it only requires to compile 2266 files as that: [100% 2266/2266] host Executable: net_...test_osi_intermediates/net_test_osi32). However, it still needs to take long time (#### make completed successfully (49:19 (mm:ss)) ####) to finish that, so does it have some methods to minimize the time to make files? Thank you

**Comment by vchong** [comment]
It's probably taking a long time since it needs to recreate the `system.img`.
You can try just rebuilding the ca and ta, i.e.:
`make BLABLABLA tee_helloworld`
and
`make BLABLABLA 8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta`
but then you'll have to `adb push` them to board.

**Comment by bryan370210** [comment]
which are the target directories to push into ?

**Comment by wxlqaz** [comment]
adb push ~/hikey/out/target/product/hikey/optee/ta/8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta /system/lib/optee_armtz

adb push ~/hikey/out/target/product/hikey/system/bin/tee_helloworld /system/bin

**Comment by vchong** [comment]
@wxlqaz Thanks! Only slight a slight correction:

```
adb push <android build dir>/out/target/product/hikey/optee/ta/8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta /system/lib/optee_armtz

adb push <android build dir>/out/target/product/hikey/system/bin/tee_helloworld /system/bin
```

**Comment by bryan370210** [comment]
@vchong 
if I use this method below, is the source code  compiled automaticly in the progress of optee_android's compiling ?  if so , where should i put my source code ?


Follow the instructions in https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master to build optee_android for hikey. After step 3.4, before step 3.5, do below:

In device/linaro/hikey/optee-packages.mk, add:

PRODUCT_PACKAGES += name_of_your_ca
PRODUCT_PACKAGES += uuid_of_your_ta #e.g. 8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta

Then you can run name_of_your_ca from the console as root. Note that this is on the condition that you have the proper Android.mk files for your ca and ta. You can refer to the Android.mk files in https://github.com/linaro-swg/hello_world.

**Comment by vchong** [comment]
Anywhere under the android build dir should be fine, but to be safe, or to keep similar things together, put it under `<android build dir>/external`, i.e. same place where hello world is located.

**Comment by vchong** [comment]
And yes, the source code will be compiled in the process of optee_android's compiling.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
