### ISSUE TITLE
Is any page table integrity-protected?

### ISSUE THREAD

**Issue by xnadO** [OP-TEE/optee_os#1814]
I stumbled over one point in the slides from the BKK16-110. [http://connect.linaro.org/resource/bkk16/bkk16-110/](url)

On page 37 the speaker mentions 
> Each page integrity-protected using SHA-256 hash.

I cannot find the video with more information. So I would be happy to have some better technical insights. 

Let us assume that there is an adversary who attempts to manipulate the page table pointing to some shared memory address space. For example, the attacker changes normal OS page tables such that virtual addresses point to different physical addresses. This shouldn't work due to the integrity check, right?

Vice versa, when a Trusted App from the secure world access the shared memory, it has the guarantees  that the normal World accesses the same shared memory (as the integrity of the tables is preserved). Is this the correct conclusion?

Does the argumentation make sense?

Your help is much appreciated!

**Comment by jenswi-linaro** [comment]
Hi,

The integrity protections is only for pages which can be paged out by the pager in secure world. Page tables (translation tables) in neither secure nor non-secure world is covered by this.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
