### ISSUE TITLE
Issue: REE fs secure storage with RPMB

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#1833]
optee version 2.5
CFG_RPMB_FS=y has been set, and RPMB_EMU := 0 in tee-supplicant.

Issue:
Power down when writing FILE_A,  the FILE_A can not be read again.
From the size of dirf.db,  it change from 16384 to 136 after read FILE_A failed.
If set CFG_RPMB_FS=n,  no such issue.

LOG:

# ls -l /data/tee
-rw-------    1 root     root         16384 Jan  1 00:03 0
-rw-------    1 root     root         16384 Jan  1 00:03 dirf.db
# 
# hisi_demo_client 8
DEBUG:   [0x0] TEE-CORE:tee_ta_init_pseudo_ta_session:259: Lookup pseudo TA 8f194022-c9a2-11e6-9d9d-cec0c932ce01
DEBUG:   [0x0] TEE-CORE:tee_ta_init_user_ta_session:632: Lookup user TA 8f194022-c9a2-11e6-9d9d-cec0c932ce01 (early TA)
DEBUG:   [0x0] TEE-CORE:tee_ta_init_user_ta_session:632: Lookup user TA 8f194022-c9a2-11e6-9d9d-cec0c932ce01 (REE)
DEBUG:   [0x0] TEE-CORE:ta_load:317: ELF load address 0x101000
DEBUG:   [0x0] TEE-CORE:tee_rpmb_init:1201: RPMB: Syncing device information
DEBUG:   [0x0] TEE-CORE:tee_rpmb_init:1209: RPMB: RPMB size is 32*128 KB
DEBUG:   [0x0] TEE-CORE:tee_rpmb_init:1211: RPMB: Reliable Write Sector Count is 1
DEBUG:   [0x0] TEE-CORE:tee_rpmb_init:1242: RPMB INIT: Deriving key
INFO:    TEE-CORE: RPMB: Using generated key
DEBUG:   [0x0] TEE-CORE:tee_rpmb_init:1254: RPMB INIT: Verifying Key
DEBUG:   [0x0] TEE-CORE:tee_rpmb_verify_key_sync_counter:1102: Verify key returning 0x0
DEBUG:   [0x0] TEE-CORE:tee_rpmb_read:1330: Read 1 block at index 0
DEBUG:   [0x0] TEE-CORE:tee_rpmb_read:1330: Read 8 blocks at index 2
DEBUG:   [0x0] TEE-CORE:read_fat:1849: fat_address 0
DEBUG:   [0x0] TEE-CORE:tee_rpmb_read:1330: Read 8 blocks at index 2
DEBUG:   [0x0] TEE-CORE:dump_fh:1654: fh->filename=/dirfile.db.hash
DEBUG:   [0x0] TEE-CORE:dump_fh:1655: fh->rpmb_fat_address=512
DEBUG:   [0x0] TEE-CORE:dump_fh:1656: fh->fat_entry.start_address=4193792
DEBUG:   [0x0] TEE-CORE:dump_fh:1657: fh->fat_entry.data_size=32
DEBUG:   [0x0] TEE-CORE:read_fat:1849: fat_address 512
DEBUG:   [0x0] TEE-CORE:tee_rpmb_read:1330: Read 8 blocks at index 2
DEBUG:   [0x0] TEE-CORE:tee_rpmb_read:1330: Read 1 block at index 16382
DEBUG:   [0x0] TEE-CORE:tee_fs_crypt_block:316: Decrypt block #16382
[ta log] [ERR][demo_task_read_file][600] TEE_OpenPersistentObject failed, ret[0xffff0008]
[ta log] [DBG][test_storage_read][634] file[demo_task_file_name.txt] count[0x0] buf[0x0]
[ta log] [ERR][TA_InvokeCommandEntryPoint][1906] Invoke command[0x8] failed, ret[0xffff0008]
DEBUG:   [0x0] TEE-CORE:tee_ta_invoke_command:625: Error: ffff0008 of 4
[error] main: InvokeCommand failed, ReturnCode=0xffff0008, ReturnOrigin=0x4

^CDEBUG:   [0x0] TEE-CORE:tee_ta_close_session:378: tee_ta_close_session(0x3e55e7c0)
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:397: Destroy session
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:423: Destroy TA ctx

# 
# ls -l /data/tee
-rw-------    1 root     root         16384 Jan  1 00:03 0
-rw-------    1 root     root           136 Jan  1 00:00 dirf.db

**Comment by airbak** [comment]
@jenswi-linaro @jforissier 
please help to solve it , thanks.

**Comment by airbak** [comment]
When CFG_RPMB_FS is enable, open_dirh() will recreate dirf.db if tee_fs_dirfile_open(false, hashp, &ree_dirf_ops, dirh) failed.

The hash value in dirfile.db.hash and dirf.db must keep the same.  But in this testcase, power down during writing file, the hash in dirfile.db.hash had not been updated. 

In QEMU with RPMB_EMU = 1, this issue could not be reproduced, because the data in ddr will lost after power down. I suggest that RPMB_EMU save the data to a file, it may be more closer to the real equipment. 

Looking forward to your reply, @jenswi-linaro

**Comment by jenswi-linaro** [comment]
Please try this patch to tee-supplicant:
```
diff --git a/tee-supplicant/src/tee_supp_fs.c b/tee-supplicant/src/tee_supp_fs.c
index e2c71ee00194..94f4be818f9c 100644
--- a/tee-supplicant/src/tee_supp_fs.c
+++ b/tee-supplicant/src/tee_supp_fs.c
@@ -134,7 +134,7 @@ static int open_wrapper(const char *fname, int flags)
        int fd;
 
        while (true) {
-               fd = open(fname, flags, 0600);
+               fd = open(fname, flags | O_SYNC, 0600);
                if (fd >= 0 || errno != EINTR)
                        return fd;
        }
```

**Comment by airbak** [comment]
Thanks for your reply.
I had try this patch. The probability of these issue becomes smaller, but it still occurred.
I think if "write the hash value" is not an atomic operation, this issue will always occur.

**Comment by jenswi-linaro** [comment]
If the hash in `dirfile.db.hash` (residing in RPMB) hasn't been written when the power is lost, then the old hash vaule is supposed to be used instead. Since we haven't made any further changes in `dirf.db` that means that both the old and new versions should be intact and in this case the older version should be restored.

Without the `O_SYNC` flag I think that the kernel was caching `dirf.db` and when power was lost only some very old (more than two generations) version was in the file system.

So if `O_SYNC` had an impact either that part of the problem is removed and there's another atomicity problem in RPMB or perhaps the kernel isn't 100% true to `O_SYNC`. 

Widening the window between writing `dirf.db` and `dirfile.db.hash` this patch should give some indication:
```
diff --git a/core/tee/tee_ree_fs.c b/core/tee/tee_ree_fs.c
index 7b906ce8de2d..7fcf7128920e 100644
--- a/core/tee/tee_ree_fs.c
+++ b/core/tee/tee_ree_fs.c
@@ -502,6 +502,7 @@ static TEE_Result commit_dirh_writes(struct tee_fs_dirfile_dirh *dirh)
        res = tee_fs_dirfile_commit_writes(dirh, hash);
        if (res)
                return res;
+       tee_time_wait(100);
        return rpmb_fs_ops.write(ree_fs_rpmb_fh, 0, hash, sizeof(hash));
 }
 ```

If there isn't a clear indication with this delay you could perhaps experiment a little with different times to see if that has an impact. If there's still no clear indication I'd say that `O_SYNC` works and we have a problem in RPMB.

**Comment by airbak** [comment]
@jenswi-linaro  you are right. 
After add O_SYNC flag, the issue that init_head_from_data() return TEE_ERROR_SECURITY has been solved.
The problem of low probability should be caused by other reasons, I will do more tests to reproduce and report it later.
This issue should be closed, thank you very much.

**Comment by jforissier** [comment]
@airbak can you please open a PR for the tee-supplicant fix?

**Comment by airbak** [comment]
@jforissier @jenswi-linaro 
I have  opened  a PR https://github.com/OP-TEE/optee_client/pull/105.
I'm not sure whether it will affect secure storage performance.
