### ISSUE TITLE
Enable SDP [Secure Data Path] in QEMU.

### ISSUE THREAD

**Issue by pt6567** [OP-TEE/optee_os#1835]
I am trying to get started with SDP so that I can eventually use it my project. The final goal is to have a shared memory space between 2+ TAs which can be used to directly share data between them.

As a initial step, I want to run the sdp-basic test which is a part of xtest. I tried enabling SDP by adding "CFG_SECURE_DATA_PATH=y" to the OPTEE_OS_COMMON_FLAGS in qemu.mk. This did not workout as I am not able to see the --sdp-basic option in the help menu when I run xtest -h. 
I am using the master branch and default manifest.
As mentioned by @etienne-lms in #1819, SDP+xtest does run successfully on qemu. 

I would like to know what is the correct way to enable and use SDP on qemu. [ Eventually planning to run the project on hikey board ]

It would be great if you can point me to some relevant documentation as well if it exists. As of now I have referred to the [presentation](https://www.slideshare.net/linaroorg/bud17400-secure-data-path-with-optee), the basic sdp test case in xtest and some of the issues in this repo.
Thanks

**Comment by etienne-lms** [comment]
I think you only need to make sure optee_test is build after optee_os is built with`CFG_SECURE_DATA_PATH=y`. Try to remove the optee_test/out/ and rebuild/test (`make xtest && make run`).

**Comment by pt6567** [comment]
Hello @etienne-lms,
That worked! Thank you for taking the time to write the response :)
I have couple of more questions/scenarios regarding SDP. 

1. This is my understanding of how SDP works: 
CA registers sharedBuffer and send it as a param to TA1. TA1 saves some data to this and returns success/failure to CA. Now CA can pass the same sharedBuffer to TA2 and TA2 can access the data stored by TA1. TA2 can also invoke TA3 using TEE_InvokeTACommand() and pass the buffer as reference.  
We always need to pass the buffer as reference during invocation for SDP to work.
Is his correct?

2. Can we use SDP in the following a way?
CA registers a sharedBuffer and sends it to TA1[invoked with TA_FLAG_KEEP_ALIVE], TA1/CA sends it to TA2[again invoked with TA_FLAG_KEEP_ALIVE]. CA exits without deregistering the sharedBuffer and the TAs keep the buffer reference in their memory and use it as a shared buffer here after.
Is this possible? If not, can you suggest any other variation that can workout or I can look into? 

3. Is there any other mechanism by which we can have a shared memory space between 2+ TAs?

**Comment by etienne-lms** [comment]
1. yes
2. no, TA cannot access a sharedBuffer unless it is invoked with that sharedBuffer as invokation parameter.
3. no, only non-secure can register sharedBuffer.
4. no, there are no such service today.

**Comment by pt6567** [comment]
@etienne-lms Thanks for clearing my doubts.
