### ISSUE TITLE
SUGGESTION : We need the github wiki for OP-TEE

### ISSUE THREAD

**Issue by ajithpv** [OP-TEE/optee_os#1836]
Hi,
It would be better, if we make contents on github Wiki for getting all information under one umbrella. Already there is a dedicated tab present for Wiki inside -  [wiki](https://github.com/OP-TEE/optee_os/wiki) -  but no contents are existing.
I would like to know thought on this.

**Comment by jforissier** [comment]
Hi,

We have a documentation folder and I see no reason to move the doc to a separate git repository (which is what would happen if we were to use the github wiki feature, if I'm not mistaken).

**Comment by ajithpv** [comment]
If wiki is a separate git repo, then current documentation is the good option.
