### ISSUE TITLE
How to identify the boundary between pager and pageable sections?

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#1838]
I know that OP-TEE uses `KEEP_PAGER` macro to identify sections used by pager, and uses `-ffunction-sections, -fdata-sections, --gc-sections` options to include sections only used by pager. 

But I don’t know how OP-TEE exclude unused sections. For example, the function `thread_std_smc_entry` is include in pager, and it refers `__thread_std_smc_entry`. However, `__thread_std_smc_entry` is not include in pager ( I find that it is put into the pageable area). I find some comments of `__thread_std_smc_entry` function: _**Note: this function is weak just to make it possible to exclude it from the unpaged area.**_ How the weak attribute exclude the function from pager?

```
FUNC thread_std_smc_entry , :
UNWIND(	.fnstart)
UNWIND(	.cantunwind)
	/* Pass r0-r7 in a struct thread_smc_args */
	push	{r0-r7}
	mov	r0, sp
	bl	__thread_std_smc_entry
```

`void __weak __thread_std_smc_entry(struct thread_smc_args *args)
`

**Comment by jenswi-linaro** [comment]
When constructing the dependency graph we cut of certain branches with `core/arch/arm/kernel/link_dummies.c`.

**Comment by TEE-OS** [comment]
@jenswi-linaro get it, thanks.
