### ISSUE TITLE
alignment fault

### ISSUE THREAD

**Issue by tranhuanltv** [OP-TEE/optee_os#1841]
Hi I'm new to OPTEE. I don't know why this code crash on OPTEE, but on normal world it working well

int result = 0;
char buffer[256] = {0};
result = *(int *)(void *)(buffer + 1); // crash
result = *(int *)(void *)(buffer); // no problem

Log:
DEBUG:   [0x0] TEE-CORE:abort_handler:667: [abort] abort in User mode (TA will panic)
ERROR:   [0x0] TEE-CORE:
ERROR:   [0x0] TEE-CORE: User TA data-abort at address 0x100dc9 (alignment fault)
ERROR:   [0x0] TEE-CORE:  fsr 0x00000001  ttbr0 0x5008c04a  ttbr1 0x5008804a  cidr 0x1
ERROR:   [0x0] TEE-CORE:  cpu #0          cpsr 0x00000030
ERROR:   [0x0] TEE-CORE:  r0 0x00000001      r4 0x00100f80    r8 0x00000000   r12 0x500f8af8
ERROR:   [0x0] TEE-CORE:  r1 0x00000001      r5 0x00105365    r9 0x00000000    sp 0x00100db0
ERROR:   [0x0] TEE-CORE:  r2 0x0010df61      r6 0x00000000   r10 0x00000000    lr 0x001047a1
ERROR:   [0x0] TEE-CORE:  r3 0x00100dc9      r7 0x00100dc0   r11 0x00000000    pc 0x001037da
ERROR:   [0x0] TEE-CORE: Status of TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (0x50087b80) (active)
ERROR:   [0x0] TEE-CORE:  arch: arm  load address: 0x101000  ctx-idr: 1
ERROR:   [0x0] TEE-CORE:  stack: 0x100000 4096
ERROR:   [0x0] TEE-CORE:  region 0: va 0x100000 pa 0x5fb14000 size 0x1000
ERROR:   [0x0] TEE-CORE:  region 1: va 0x101000 pa 0x50100000 size 0xd000
ERROR:   [0x0] TEE-CORE:  region 2: va 0x10e000 pa 0x5010d000 size 0x3000
ERROR:   [0x0] TEE-CORE:  region 3: va 0x111000 pa 0x50110000 size 0xfa04000
ERROR:   [0x0] TEE-CORE:  region 4: va 0 pa 0 size 0
ERROR:   [0x0] TEE-CORE:  region 5: va 0 pa 0 size 0
ERROR:   [0x0] TEE-CORE:  region 6: va 0 pa 0 size 0
ERROR:   [0x0] TEE-CORE:  region 7: va 0 pa 0 size 0
ERROR:   [0x0] TEE-CORE: Call stack:
ERROR:   [0x0] TEE-CORE:  0x001037da
ERROR:   [0x0] TEE-CORE:  0x0010393f
ERROR:   [0x0] TEE-CORE:  0x0010534b
ERROR:   [0x0] TEE-CORE:  0x001053a3

**Comment by igoropaniuk** [comment]
@tranhuanltv 
On ARM-bases systems(in contrast of x86) you can't address a 32-bit word that is not aligned to a 4-byte boundary (actually that's what are you trying to do by casting pointer to `int *` and then dereferencing it)

**Comment by tranhuanltv** [comment]
@igoropaniuk: But it's still work on normal world which is the same architecture

**Comment by jforissier** [comment]
Try `make ... CFG_SCTLR_ALIGNMENT_CHECK=n`.

**Comment by igoropaniuk** [comment]
@tranhuanltv
Possible explanations https://jsolano.net/2012/09/06/arm-unaligned-data-access-and-floating-point-in-linux/

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins

**Comment by PedroRibeiro95** [comment]
Hello @jforissier 

> Try make ... CFG_SCTLR_ALIGNMENT_CHECK=n

Where do I run this? When compiling optee_os or the application itself?

Thanks.
