### ISSUE TITLE
Recent booting problems on HiKey960

### ISSUE THREAD

**Issue by Pentr** [OP-TEE/optee_os#1851]
Hi

 all,

I have some problems booting OP-TEE on my Hikey960 board. I followed the instructions under https://github.com/OP-TEE/build and I was able to build and flash (`make flash`) everything nicely.
However, when I boot the system it gets stuck with the following lines:

> [0.753291] hi3660-mbox e896b000.mailbox: Mailbox enabled
> [   21.773459] INFO: rcu_preempt detected stalls on CPUs/tasks:
> [   21.779191] 	5-...: (1 GPs behind) idle=135/140000000000000/0 softirq=21/22 fqs=2625 
> [   21.787109] 	(detected by 0, t=5252 jiffies, g=-289, c=-290, q=111)
> [   21.793448] Task dump for CPU 5:
> [   21.796706] swapper/0       R  running task        0     1      0 0x00000002
> [   21.803837] Call trace:
> [   21.806320] [<ffff00000808618c>] __switch_to+0x94/0xa8
> [   21.811513] [<0000000000000040>] 0x40

I attached the whole log file from the boot process. 
Any idea what could lead to those stalls on the CPU? I get the same error with the `make recovery` command.

Surprisingly I was able to run OP-TEE on the board only a few weeks ago. I also got some problem after `make flash`, some error with the BL2. However, a `make recovery` fixed the problem back then.
So could this problem maybe be caused by one of the more recent commits?

[boot.log](https://github.com/OP-TEE/optee_os/files/1345810/boot.log)

[Edit: fixed URL to build Git]

**Comment by vchong** [comment]
@Pentr We'll investigate and get back to you later. Thanks for the report!

**Comment by jforissier** [comment]
I'm seeing the same issue :(

**Comment by jforissier** [comment]
Looks like https://github.com/96boards-hikey/tools-images-hikey960 commit 92f365073cd812a8d8ca159b01f52dd6dd06d111 breaks the thing.
Workaround:
```
$ (cd tools-images-hikey960; git checkout 92f365073cd8^)
```
(thanks @vchong!)

**Comment by jforissier** [comment]
@Pentr feel free to try again and re-open the issue if it doesn't work for you.

**Comment by vchong** [comment]
@jforissier np thanks for testing!
