### ISSUE TITLE
Is there someone met xtest failure after 2.5.0 ?

### ISSUE THREAD

**Issue by KenLSoft** [OP-TEE/optee_os#1882]
We updated our optee_os on Juno into 2.5.0 and found some xtest failure:
Have you ever met this problem ?

LOG:

* regression_6009 Test TEE Internal API Persistent Object Enumeration Functions
o regression_6009.1 Storage id: 00000001
/junoxtest/workspace/css/optee/optee_test/host/xtest/regression_6000.c:1133: fs_next_enum(&sess, e, info, sizeof(info), id, sizeof(id)) has an unexpected value: 0x0 = TEEC_SUCCESS, expected 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND
  regression_6009.1 FAILED
o regression_6009.2 Storage id: 80000000
/junoxtest/workspace/css/optee/optee_test/host/xtest/regression_6000.c:1083: fs_create(&sess, file_00, sizeof(file_00), 0x00000002, 0, data_01, sizeof(data_01), &obj0, storage_id) has an unexpected value: 0xffff0003 = TEEC_ERROR_ACCESS_CONFLICT, expected 0x0 = TEEC_SUCCESS
  regression_6009.2 FAILED
  regression_6009 FAILED
 
* regression_6010 Test Storage
o regression_6010.1 Storage id: 00000001
o regression_6010.1.1 CreatePersistentObject AccessConflict
/junoxtest/workspace/css/optee/optee_test/host/xtest/regression_6000.c:1199: fs_create(&sess, file_00, sizeof(file_00), f, 0, data, sizeof(data), &o1, storage_id) has an unexpected value: 0xffff0003 = TEEC_ERROR_ACCESS_CONFLICT, expected 0x0 = TEEC_SUCCESS
  regression_6010.1.1 FAILED
o regression_6010.1.2 RestrictObjectUsage Panic
  regression_6010.1.2 OK
o regression_6010.1.3 SeekObjectData BadHandle
  regression_6010.1.3 OK
o regression_6010.1.4 SeekObjectData NotPersist
  regression_6010.1.4 OK
o regression_6010.1.5 SeekWriteRead
/junoxtest/workspace/css/optee/optee_test/host/xtest/regression_6000.c:1254: fs_create(&sess, file_00, sizeof(file_00), f, 0, data, sizeof(data), &o1, storage_id) has an unexpected value: 0xffff0003 = TEEC_ERROR_ACCESS_CONFLICT, expected 0x0 = TEEC_SUCCESS
  regression_6010.1.5 FAILED
o regression_6010.1.6 Rename Access Conflict
/junoxtest/workspace/css/optee/optee_test/host/xtest/regression_6000.c:1316: fs_create(&sess, file_00, sizeof(file_00), f, 0, data, sizeof(data), &o1, storage_id) has an unexpected value: 0xffff0003 = TEEC_ERROR_ACCESS_CONFLICT, expected 0x0 = TEEC_SUCCESS
  regression_6010.1.6 FAILED
o regression_6010.1.7 AllocPersistentObjectEnumerator + ResetPersistentObjectEnumerator
  regression_6010.1.7 OK

AND:

* regression_20001 Sanity Test Corrupt Meta Encrypted Key
o regression_20001.1 | filename: file_4097B , data size: 4097 byte(s)
/junoxtest/workspace/css/optee/optee_test/host/xtest/regression_20000.c:532: obj_create(&sess, filename, (sizeof(filename) / sizeof((filename)[0])), 0x00000002, 0, filedata, tv->data_len, &obj_id) has an unexpected value: 0xffff0003, expected 0x0
  regression_20001.1 FAILED
  regression_20001 FAILED

Anybody met this problem?

Thanks.
-Ken.

**Comment by vchong** [comment]
Have you tried deleting everything under `/data/tee` first before running the test?

**Comment by ken08liu14** [comment]
Let me try this.

It seems our xtest version is not updated with 2.5.0... rebasing now and will update you later.

Thanks.

**Comment by ken08liu14** [comment]
@vchong 
> Have you tried deleting everything under /data/tee first before running the test?
Tried, and it passed...
Why does this happen? Do we need to delete directories before xtest every time ?

**Comment by vchong** [comment]
Was it because of your xtest version or old files under `/data/tee`? I'm not sure of the exact reason, maybe the maintainers can offer more details, but i think sometimes if you're testing your own code and there are errors, or if you stop/cancel the tests midway, it can leave behind old/corrupted files under `/data/tee` that should have been removed at the end of the tests, and cause any subsequent tests to error out. Xtest probably assumes everything is clean at the beginning of the test.

**Comment by ken08liu14** [comment]
Just clean and do it again to check....
will erase file every time if this is the problem.

**Comment by jforissier** [comment]
@vchong correct. Indeed `xtest` assumes it starts from a clean state. If the tests are successful, the storage will be clean on exit. But if failures occur for any reason, it's not guaranteed.
