### ISSUE TITLE
OP-TEE boot flow

### ISSUE THREAD

**Issue by ranjithvs** [OP-TEE/optee_os#1887]
Dear All,
 
       I am working on i.MX6UL based platform for porting optee to secure world. Followed the link provided by Mr. Van http://mrvan.github.io/optee-imx6ul. It is working fine. I just had a doubt who will load the kernel image(zImage) is it u-boot or the OP-TEE OS. 

     Boot argument I am following :   `run loadfdt;run loadimage;fatload mmc 0:1 0x84000000 uTee;run mmcargs;bootm 0x84000000 - ${fdt_addr}; ` 

      I am curious to know , while building op-tee os we are passing CFG_NS_ENTRY_ADDR(load address of the kernel image)  to the OP-TEE OS. And to find out the flow, added prints in boot_jump_linux of u-boot in arch/arm/lib/bootm.c file, After this line kernel_entry(0, machid, r2); it is never coming back. 

      So anyone have better understanding about this flow, it will be helpful for my further development of Signature Verification of the Next Level. If u-boot loading both optee and zImage then need to do signature verification there itself. 
 
      Looking forward to your reply guys, @MrVan @jenswi-linaro @jbech-linaro @igoropaniuk @jforissier @etienne-lms  
      

Thanks in advance,
Ranjith Hebbar V S

**Comment by MrVan** [comment]
U-Boot will load TEE and zImage, so need to verify the two images in
U-Boot. `kernel_entry` will run into the address passed to bootm. When
optee returns back, it will directly runs into the load address of zImage
and continue booting kernel.

2017-10-17 12:18 GMT+08:00 ranjithvs <notifications@github.com>:

**Comment by ranjithvs** [comment]
I will appreciate Thanks for your inputs @MrVan. I will proceed...:)

**Comment by ranjithvs** [comment]
Dear All,
      I am working on i.MX6 UL based platform. I wants to use OP-TEE for signature verification for chain of trust. In my Flow ROM code verifies signature of SPL, SPL verifies signature of uTee Now I want to verify subsequent boot stages from OP-TEE that is u-boot image and kernel image. Is there any code in OP-TEE to do signature verification. While initializing OP-TEE I wants to do the validation of next level boot i.e, U-boot and zImage. @MrVan Your input for this is appreciated.

Thanks in advance,
Ranjith Hebbar V S

**Comment by jbech-linaro** [comment]
> Is there any code in OP-TEE to do signature verification

Yes, one concrete example is to have a look at where we are doing the signature checking when loading Trusted Applications (loaded from ree), [here](https://github.com/OP-TEE/optee_os/blob/30668b28176cc844037f535ed6d9bdb26557d2d7/core/arch/arm/kernel/ree_fs_ta.c#L136) is a good starting point.

**Comment by juppin** [comment]
Why not loading all with a signed fit image from authenticated SPL or U-Boot?

**Comment by ranjithvs** [comment]
@jbech-linaro I referred and has done my own implementation for authenticate image using libtomcrypto API's of SHA256 and RSA.

@juppin Now we are loading all the images from SPL and validating each subsequent image and maintaining chain of trust.

**Comment by dleymarie** [comment]
Dear all,

I'm working on a NXP SoC similar to imx7. We have a complete secure boot: bootloader U-Boot is loaded and authenticated by BootROM with HAB, then bootloader U-Boot loads and authenticate a FIT image which contains kernel/dtb. 
I'm adding currently op-tee to this FIT image.  I'm using this as input for generating FIT image:
`/*
 * XXXX Cortex-A7 FIT source file containing a single kernel and FDT blob
 */

/dts-v1/;

/ {
    description = "XXXX Cortex-A7 Linux XXXXX";
    #address-cells = <1>;

    images {
        kernel@1 {
            description = "XXXX Linux kernel";
            data = /incbin/("/home/..../Image");
            type = "kernel";
            arch = "arm";
            os = "linux";
            compression = "none";
            load = <0x80008000>;
            entry = <0x80008000>;
            hash@1 {
                algo = "sha256";
            };
        };
        fdt@1 {
            description = "XXXXX Device Tree blob";
            data = /incbin/("/home/.../myboard.dtb");
            type = "flat_dt";
            arch = "arm";
            load = <0x81000000>;
            compression = "none";
            hash@1 {
                algo = "sha256";
            };
        };
        optee@1 {
            description = "XXXX OP-TEE";
            data = /incbin/("/home/.../tee.bin");
            type = "tee";
            arch = "arm";
            os = "tee";
            compression = "none";
            load = <0x879FFFE4>;
            entry = <0x87A00000>;
            hash@1 {
                algo = "sha256";
            };
        };
    };

    configurations {
        default = "conf@1";
        conf@1 {
            description = "Boot BSRF Linux kernel";
            kernel = "kernel@1";
            fdt = "fdt@1";
            loadables = "optee@1";
            hash@1 {
                algo = "sha256";
            };
        };
    };
};
`
to load and start with U-Boot: bootm 85000000#conf@1
tee.bin has been compiled to chain load Linux kernel, so I'm expecting to have this flow:
BootROM -> U-Boot -> Optee -> Linux kernel
For the moment I have U-Boot which launches Linux kernel without optee. Optee image is right seen in FIT image.
U-Boot 2018.07 has been configured for optee:
CONFIG_OPTEE=y
CONFIG_OPTEE_LOAD_ADDR=0x87a00000
CONFIG_OPTEE_TZDRAM_SIZE=0x400000
CONFIG_OPTEE_TZDRAM_BASE=0x87a00000
CONFIG_BOOTM_OPTEE=y

How to modify U-boot to have the right boot flow ?

Thanks in advance,
D. Leymarie

**Comment by juppin** [comment]
Hello,

you have to exchange optee and the kernel image in your config section chainload the kernel image from optee os.

It should look like in your config sub node:

kernel = "optee@1";
loadables = "kernel@1";

**Comment by dleymarie** [comment]
Hello, @juppin 
I tested your suggestion and with an other modification in optee@1 for type changed for "tee" to "kernel", and it's working.  
`    optee@1 {
        description = "XXXX OP-TEE";
        data = /incbin/("/home/.../tee.bin");
        type = "kernel";
        arch = "arm";
        os = "tee";
        compression = "none";
        load = <0x879FFFE4>;
        entry = <0x87A00000>;
        hash@1 {
            algo = "sha256";
        };
    };
`
My system (Cortex-A7) now boots with FIT image including kernel, DTB and optee wtih the boot flow:
U-Boot -> OPTEE -> Kernel Linux

Thanks you a lot
D. Leymarie
