### ISSUE TITLE
How to build the .so file when I  use or call OP-TEE (GlobalPlatform) APIs from an Android (.apk) app

### ISSUE THREAD

**Issue by wxlqaz** [OP-TEE/optee_os#1888]
hi, I have installed the  AOSP+ optee operating system in hikey board as https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master. Now I wanna to install a android app which can call OP-TEE api.  I know the  https://www.op-tee.org/faq/#8-trusted-applications tells some thing about that,  but I still can not generate .so file since it tells us that some head file such as tee_clent_api.h is missing,  so how do I fix it, or does anyone who has finished it before can describe this procedure more specifically. 
Thanks!

**Comment by etienne-lms** [comment]
Maybe have a look at https://github.com/OP-TEE/optee_os/issues/913 and https://github.com/OP-TEE/optee_os/issues/1791.
