### ISSUE TITLE
secure storage physical file layout

### ISSUE THREAD

**Issue by wellsleep** [OP-TEE/optee_os#1894]
Hi guys,

I have a question about physical file layout on REE (android) side. Platform is Hikey 620, android 7.1 with OP-TEE 2.5.0.

According to [tee_ree_fs.c](https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_ree_fs.c), the file layout is
```
/*
	 * File layout
	 *
	 * phys block 0:
	 * tee_fs_htree_image vers 0 @ offs = 0
	 * tee_fs_htree_image vers 1 @ offs = sizeof(tee_fs_htree_image)
	 *
	 * phys block 1:
	 * tee_fs_htree_node_image 0  vers 0 @ offs = 0
	 * tee_fs_htree_node_image 0  vers 1 @ offs = node_size
	 * tee_fs_htree_node_image 1  vers 0 @ offs = node_size * 2
	 * tee_fs_htree_node_image 1  vers 1 @ offs = node_size * 3
	 * ...
	 * tee_fs_htree_node_image 61 vers 0 @ offs = node_size * 122
	 * tee_fs_htree_node_image 61 vers 1 @ offs = node_size * 123
	 *
	 * phys block 2:
	 * data block 0 vers 0
	 *
	 * phys block 3:
	 * data block 0 vers 1
	 *
	 * ...
	 * phys block 63:
	 * data block 61 vers 0
	 *
	 * phys block 64:
	 * data block 61 vers 1
	 *
	 * phys block 65:
	 * tee_fs_htree_node_image 62  vers 0 @ offs = 0
	 * tee_fs_htree_node_image 62  vers 1 @ offs = node_size
	 * tee_fs_htree_node_image 63  vers 0 @ offs = node_size * 2
	 * tee_fs_htree_node_image 63  vers 1 @ offs = node_size * 3
	 * ...
	 * tee_fs_htree_node_image 121 vers 0 @ offs = node_size * 122
	 * tee_fs_htree_node_image 121 vers 1 @ offs = node_size * 123
	 *
	 * ...
	 */
```
However based on the code, each phys block (4KB) could only contain 62 node_size (4096/66).
Hence in each phys block, there will only 31 `tee_fs_htree_node_image` structures.

Am I right? If I'm right, the phys block 1 and block 65 should have only have half number of the elements in the comment (for Hikey). Is the physical block size platform dependent? 

Thanks in advance,

**Comment by jenswi-linaro** [comment]
Yes, you're right there's only 31 `tee_fs_htree_node_image` structures.

No, the physical block size isn't really platform dependent.

**Comment by jforissier** [comment]
@wellsleep would you mind sending a patch for this? (pull request). Thanks!

**Comment by wellsleep** [comment]
Comment fixed . Close issue.
