### ISSUE TITLE
Can TA access the address in the normal world?

### ISSUE THREAD

**Issue by Tigerly** [OP-TEE/optee_os#1899]
Hello everyone,
According to the TEE document, it seems that the secure world has the highest authority and it can access all the resource in the normal world. Is it correct for op-tee?

I'm curious about if I run a program in the normal world, sending a variable's address (pointer) to the TA. Can TA directly access this variable which is in the normal world through the address?

Thanks in advance!

**Comment by jforissier** [comment]
Hi @Tigerly ,

No, it is not possible, because normal world memory is not mapped in the TA memory space.

**Comment by Tigerly** [comment]
@jforissier Thanks for replying!
I was wondering whether there are some way to to that.

Actually, I met a problem when passing a struct pointer variable (e.g. struct A* a) to the TA side.
The intuitive way is to use TEE shared memory, serialize the struct variable, and pass it.
However, the struct could be very complicated and nested.
e.g.,
Struct A {
  Struct B * b;
  char * c;
  int * d;
} a;
When serializing the struct variable (struct A* a), it is very hard to get each item's length (since its items are pointer that pointing to somewhere in memory). Therefore I cannot allocate the suitable space to serialize it.

Would it be possible to give me some suggestions about this issue?

Thanks in advance!

**Comment by etienne-lms** [comment]
hello @Tigerly. The main issue is that any parameters passed from REE to TEE must be verified by the TEE before being accessed. If your structure is specific, TEE would need a specific parser. This is also about protecting TA to insure its invocation parameters are safe and reliable.

Technically, I think TEE could map to TA the non-secure client userspace. But I don't think it is something OP-TEE will go to. GPD TEE specs specify up to 4 parameters for TA invocation, hence 4 memory buffer max. OP-TEE complies to this API.

**Comment by stuyoder** [comment]
It should be possible to register the memory you want to access with OP-TEE using TEEC_RegisterSharedMemory(), right?  Then the TA should be able to access it.

**Comment by Tigerly** [comment]
I have two follow-up questions:
If I want to send serialized data from REE to TEE, the shared memory is the only way to do that, am I correct?
I know the maximum number of parameters for TA invocation is 4, is there any other limitations for communicating with TEE?

**Comment by jforissier** [comment]
@Tigerly 
1. Yes
2. Not really.

**Comment by Tigerly** [comment]
@jforissier Got it, thank you so much!

**Comment by Tigerly** [comment]
I re-checked the GPD TEE specs about "Memory reference", It says:
"
A Memory Reference is a range of bytes which is actually shared for a particular operation. A Memory
Reference is described by either a TEEC_MemoryReference structure (see section 4.3.7) or a
TEEC_TempMemoryReference. It can specify:
1) A whole Shared Memory block.
2) A range of bytes within a Shared Memory block.
3) Or a pointer to a buffer of memory owned by the Client Application, in which case this buffer is
temporarily registered for the duration of the operation. This type of Memory Reference uses the
structure TEEC_TempMemoryReference.
"

It seems like 3) means that CA can send a variable's address (pointer) to the TA, and the TA can access that address owned by CA. Is my understanding correct? I was wondering whether op-tee support it?

Thanks!

**Comment by jenswi-linaro** [comment]
Yes and yes. However, it's implemented using a temporary buffer, but that's just an internal implementation detail it's the same to the client.
