### ISSUE TITLE
pseudo TA compilation error

### ISSUE THREAD

**Issue by anwaymukherjee** [OP-TEE/optee_os#1900]
Hello, I am trying to mimic stats.c to model a pseudo TA which performs floating point multiplication. The compilation process, however, generates an error "-mgeneral-regs-only incompatible with floating point code".  I suspect that OPTEE OS does not support floating point operations. What seems to be the problem? I am using OPTEE ver 2.4.x for this purpose.

**Comment by jenswi-linaro** [comment]
Floating point isn't generally supported in OP-TEE OS, it's supported inside user TAs though.
It's possible to enable temporarily in certain regions, we do that today for some assembly routines with uses NEON instructions. But there's a problem with compiling certain cflags with different compiler flags for this, the ABI may become incompatible for certain functions.

**Comment by jforissier** [comment]
Adding to @jenswi-linaro's answer: the crypto code may be configured to use the Cryptographic Extension (CE) instructions, which use the same set of registers (VFP) as floating-point or NEON code. It is an example of code that enables FP temporarily in the TEE core. Look for `CFG_WITH_VFP` and `thread_kernel_enable_vfp()`/`thread_kernel_disable_vfp()`.

**Comment by anwaymukherjee** [comment]
Thank you @jenswi-linaro and @jforissier for the prompt replies. Yes, I saw dynamic TAs can easily perform floating point operations, which I can not say for pTAs. Thanks for the heads up on crypto-extensions. I will certainly look into it.

**Comment by anwaymukherjee** [comment]
Okay here is what I found out. It seems like floating point multiplication does compile properly without the use of VFP trickery! I am, however, finding difficult to transfer the multiplication output from trusted side to the user space. I guess that is where I am getting "-mgeneral-regs-only incompatible with floating point code" error. Note: I am sending temp memory buffer from user side, compute floating points in pTA and bringing back the output through another temp mem buffer.
