### ISSUE TITLE
SNVS SRTC : Set/Get Time from OPTEE

### ISSUE THREAD

**Issue by sarju32** [OP-TEE/optee_os#1902]
Hi @MrVan @jforissier @jenswi-linaro 

I asked a query regarding implementing Set time functionality in i.MX SNVS RTC driver in optee in #1893 thread 

I would like to ask Why Set Time functionality is not added in that driver, any particular reason is there for not adding set time functionality ?

I wanted to disable SNVS RTC driver from Linux Normal World and do the Set/Get time in OPTEE itself.

My question now is by using current SNVS RTC driver I will be able to get the Date and Time,
I wanted to set time in OPTEE itself.

By just porting the Set functionality to SNVS RTC OPTEE driver is enough to set the time?
If I set the time from Trusted Application will it actually reflect on the hwclock ?

Please clarify me on this.

**Comment by MrVan** [comment]
OPTEE does not need calendar time, so no need to set time and not export
set time interface to linux side. In linux side, the snvs rtc drivers needs
to be updated to set an offset when setting time.

2017-10-27 1:37 GMT+08:00 sarju32 <notifications@github.com>:
