### ISSUE TITLE
memory map issue

### ISSUE THREAD

**Issue by zhupg** [OP-TEE/optee_os#1904]
Hi all:
I porting OPTEE 2.6.0 to a arm cortex-A53 platform, but it hang when mmu setup.
After I change the code in core/arch/arm/mm/core_mmu.c
```
static void init_mem_map(struct tee_mmap_region *memory_map, size_t num_elems)
             /* Mapping does not yet support sharing L2 tables */
             va = ROUNDUP(va, CORE_MMU_PGDIR_SIZE);
 #endif
-            map->va = va;
-            va += map->size;
+            map->va = map->pa;
         }
     }
```
it works.
It seems from OPTEE V2.0, virtual address is continues, then the problem appears. If I change back to flat memory configuration(virtual address equal to physical address), then the problem disappear.
I don't know why, would you please give me some advice?

**Comment by etienne-lms** [comment]
Maybe there is a piece of code in your platform (or in the core?) that uses the physical address without converting it into a virtual one is mmu is enabled, i.e https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/core_mmu.c#L1743.

**Comment by zhupg** [comment]
Thanks for your help, I think It is right because some driver still access the physical address.
Will close after try.
