### ISSUE TITLE
nsddr vs SDP memory range checking

### ISSUE THREAD

**Issue by ken08liu14** [OP-TEE/optee_os#1905]
Hello,
We are implementing secure data decryption features based on SDP on Juno; which needs big SDP memory size instead of default 0x400000 of default SDP test size.

So we use configured CFG_TEE_SDP_MEM_BASE and CFG_TEE_SDP_MEM_SIZE for SDP; it seems that system boot up with panic since memory range checking detected nsddr conflicts with SDP. 

This could be resolved by changing register_nsec_ddr(DRAM0_BASE, DRAM0_SIZE); since we don't want to keep private patches in our git repo; could we change CFG_TEE_SDP_MEM_TEST_SIZE into define-able by configure variable (needs to moved from optee shared memory area since it may be bigger than 0x400000; we could just put it before optee shared memory; and register nsddr with DDR0_BASE, DDR0_BASE + DDR0_SIZE - SDP_RESERVED_SIZE - OPTEE_RESERVED_SIZE) ?

Please help to comment; thanks.

-Ken

**Comment by etienne-lms** [comment]
Hi @ken08liu14,
`CFG_TEE_SDP_MEM_TEST_SIZE` hijacks a portion of the TEE reserved DRAM to test SDP. If you really need big buffers, I think you should not use this "sdp test memory" and set  `CFG_SECURE_DATA_PATH=y` and `CFG_TEE_SDP_MEM_BASE` / `CFG_TEE_SDP_MEM_SIZE` to you target area.

That said and looking at current implementation, there should be a way to carve out SDP memory from DRAM0/DRAM1 in generic code. Maybe this is the best way, like what is done when parsing/overwriting device tree, see `core_mmu_set_discovered_nsec_ddr()`. Although this would require some changes in the core.

Of course, changing `DRAM0_BASE`/`_SIZE` to exclude a SDP area is  more easy. Maybe another way could be to have them configurable from the build environment: `CFG_DRAM0_BASE`/`_SIZE`, `CFG_DRAM1_BASE`/`_SIZE`. This would allow you to override the default values. But this setup force SDP memory/ies to be a top or bottom of DRAM0 or DRAM1.

**Comment by ken08liu14** [comment]
Hi @etienne-lms,
I guess changing DRAM0_BASE to CFG_DRAM0_BASE is more easy since we don't want to get DT involved since we just need such a single feature.

Will create a patch for this and on plat-vexpress only for current; do you think it is OK ?

-Ken

**Comment by etienne-lms** [comment]
Ok.
