### ISSUE TITLE
i2C driver in OPTEE. 

### ISSUE THREAD

**Issue by kumarabekur** [OP-TEE/optee_os#1906]
Is there any i2c driver reference in OPTEE ?? I am using i.mx6ul custom board. @MrVan @jforissier @jenswi-linaro any example for this ?? :)

**Comment by MrVan** [comment]
I think no. You could may need to check i.MX SDK or uboot/linux as a
reference to write your own i2c driver. OT:what would you use i2c to do in
TEE?

2017-10-30 12:59 GMT+08:00 Keshava Kumar B <notifications@github.com>:
