### ISSUE TITLE
open session fail with TEEC_ERROR_SECURITY

### ISSUE THREAD

**Issue by AllenSiao** [OP-TEE/optee_os#1907]
Hi, 

I used the API: tee_client_open_session to open a session, then I got TEE result: TEEC_ERROR_SECURITY.  After traced the code, I found TA was panic at function: rsassa_verify(@tee_ltc_provider.c). Due to it returned TEE_ERROR_SIGNATURE_INVALID, so my host cannot open session successful. 

I am pretty sure that my host and TA worked, because they were tested at ARM for a long time. I just port them to a new platform but it is still ARM and I didn't modify the source code since they worked, then I faced the issue.

My optee version is 2.2. Could anyone give me any clue about this issue?

**Comment by AllenSiao** [comment]
As my personal fault, close the issue.

**Comment by tle-huu** [comment]
@AllenSiao What was your fault though?
