### ISSUE TITLE
gen_hashed_bin.py throw out 'expected one argument'

### ISSUE THREAD

**Issue by hiro086** [OP-TEE/optee_os#1911]
when I compile optee_os with
>make ARCH=arm PLATFORM=imx-mx6qsabresd CFG_BUILT_IN_ARGS=y CFG_PAGEABLE_ADDR=0 CFG_NS_ENTRY_ADDR=0x12000000 CFG_DT_ADDR=0x18000000 CFG_DT=y CFG_PSCI_ARM32=y DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4 CFG_BOOT_SYNC_CPU=n CFG_BOOT_SECONDARY_REQUEST=y CROSS_COMPILE=~/XXX_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-  

ERROR
> usage: gen_hashed_bin.py [-h] --arch {arm32,arm64} [--flags FLAGS] --init_size
                         INIT_SIZE [--init_load_addr_hi INIT_LOAD_ADDR_HI]
                         --init_load_addr_lo INIT_LOAD_ADDR_LO
                         --init_mem_usage INIT_MEM_USAGE --tee_pager_bin
                         TEE_PAGER_BIN --tee_pageable_bin TEE_PAGEABLE_BIN
                         --out OUT
gen_hashed_bin.py: error: argument --init_load_addr_hi: expected one argument
make: *** [out/arm-plat-imx/core/tee.bin] Error 2  

How can I fix it?

**Comment by jforissier** [comment]
Works for me, can you give more details on the optee_os version? Is it modified locally?
