### ISSUE TITLE
gdb debugging TA application

### ISSUE THREAD

**Issue by ademyankov** [OP-TEE/optee_os#1913]
I followed the procedure described in build/docs/debug.md and I can hit breakpoints in tee os but, I was not able to figure out how to debug TA itself. I tried to load symbols for TA app using add-symbol-file but I have problem to determine the address where to load symbols. If I use .text addr from readelf it doesn't work and I guess I know why because TA is loaded dynamically by tee-supplicant kernel driver. Is that right?

Can you please point me out what I am doing wrong and may be it will be a good idea to add a few lines into debug.md.

Thanks.

**Comment by etienne-lms** [comment]
You can enable a trace at TA load time to get the virtual base address for the binary:
```patch
--- a/core/arch/arm/kernel/user_ta.c
+++ b/core/arch/arm/kernel/user_ta.c
@@ -314,7 +314,9 @@ static TEE_Result ta_load(const TEE_UUID *uuid,
 		goto error_return;
 	}
 
-	DMSG("ELF load address 0x%x", utc->load_addr);
+	MSG("ELF load address 0x%x for %pUl",
+			utc->load_addr, (void *)&ta_head->uuid);
+
 	utc->ctx.flags = ta_head->flags;
 	utc->ctx.uuid = ta_head->uuid;
 	utc->entry_func = ta_head->entry.ptr64;
```

then use the gdb `add-symbol-file <path/to/ta/elf/file> <TA-load-address>`.

**Comment by ademyankov** [comment]
Thanks etienne-lms, sorry I should have been more specific. Actually, I have it enabled and I used that address but, most likely I am doing something wrong, coz' it still doesn't work.

So, let me give my way of doing it, maybe you will spot a miss step:
This is from readefl of my TA: 

```
Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .ta_head          PROGBITS        0000000000000000 010000 000020 00  WA  0   0  8
  [ 2] .text             PROGBITS        0000000000000020 010020 014248 00  AX  0   0  8
```
This is from 'Secure World' log:
`DEBUG:   [0x0] TEE-CORE:ta_load:316: ELF load address 0x40002000`

So I break on:
`(gdb) b tee_ta_invoke_command`

And then I add symbols at addrr 0x40012040 (ELF load addrr + .text address + .text off):
**BTW: I'have tried all combinations of addresses: 0x40002000, then with offset and without.**
```
(gdb) add-symbol-file /optee/ta/758ee8b4-f485-45fb-8fb03d0cc027b84a.elf 0x40012040
add symbol table from file "/optee/ta/758ee8b4-f485-45fb-8fb03d0cc027b84a.elf" at
        .text_addr = 0x40012040
```
if I do:
```
(gdb) info symbol 0x40012040
Atomix_JsonTest in section .text of /optee/ta/758ee8b4-f485-45fb-8fb03d0cc027b84a.elf
```
as you can see it points to some different address from one of my TA file.

So, finally, if I try to break:
```
(gdb) b TA_InvokeCommandEntryPoint
Breakpoint 2 at 0x400183d4: file ta_entry.c, line 217.
```
it won't. So `info symbol 0x40002000` confuses my the most, why does it shows something different then expected .text section.

Alright, any suggestions for me? I would be very much obliged...

**Comment by ademyankov** [comment]
Alright! I got it. So the `<address>` for `add-symbol-file` has to be 
`ELF load address 0x40002000 + .text Address` no offset involved, so it must be `0x40002020`
I though I have tried that case, most likely messed up somewhere.

Anyway, etienne-lms thanks a lot for involvement and a very timely communication!
Cheers!

**Comment by jforissier** [comment]
@ademyankov glad you could make it work! Would you mind adding a few lines to https://github.com/OP-TEE/build/blob/master/docs/debug.md#14-debug? There is no mention of TA debugging with GDB in this file and it is really lacking IMO.

**Comment by ademyankov** [comment]
Oh, absolutely! I'll do that with pleasure!

**Comment by jforissier** [comment]
Great, thanks.

**Comment by etienne-lms** [comment]
Actually, I would expect the gdb command to be:
`(gdb) add-symbol-file /optee/ta/758ee8b4-f485-45fb-8fb03d0cc027b84a.elf 0x40012000`
with the ELF load address being the one dumped by the TEE (no offset 0x20):
`DEBUG: [0x0] TEE-CORE:ta_load:316: ELF load address 0x40002000`
The ELF knows the .text and other sections virtual offset locations. I should test that back (it's been a while).
