### ISSUE TITLE
64 bit OPTEE porting issue

### ISSUE THREAD

**Issue by zhupg** [OP-TEE/optee_os#1914]
I am porting OPTEE to a ARM A53 platform accord to the document.
It works when compiling as 32 bit, but It hang when boot without any message when compiling as 64 bit.
I think there is something wrong before MMU setup.
Below is the platform configuration,
```
include core/arch/arm/cpu/cortex-armv8-0.mk
     
# 32-bit flags
core_arm32-platform-aflags      += -mfpu=neon
     
$(call force,CFG_GENERIC_BOOT,y)
$(call force,CFG_CACHE_API,y)
$(call force,CFG_PM_STUBS,y)
$(call force,CFG_SECURE_TIME_SOURCE_REE,y)
$(call force,CFG_WITH_ARM_TRUSTED_FW,y)
     
ta-targets = ta_arm32
     
ifeq ($(CFG_ARM64_core),y)
$(call force,CFG_WITH_LPAE,y)
ta-targets += ta_arm64
else 
$(call force,CFG_ARM32_core,y)
endif
     
CFG_NUM_THREADS ?= 4
CFG_WITH_STACK_CANARIES := y
     
CFG_WITH_UART ?= y
```
Is there anything should be configured special with ARM64? and could you please give me some advice?

**Comment by vchong** [comment]
Asked @jenswi-linaro about this. In your arm-tf code, check that you're setting `spsr` in the `entry_point_info` with `SPSR_64`.

**Comment by vchong** [comment]
@zhupg  Also, what does your memory map/layout look like?

**Comment by zhupg** [comment]
Thanks, this problem was fixed.
It is the problem that arm-tf set SPSR with SPSR_32.
