### ISSUE TITLE
How to craft a SMC

### ISSUE THREAD

**Issue by nikoskoutr** [OP-TEE/optee_os#1917]
Hello,

i would like to know how can I craft an SMC on my own that will call TAs that I have made, without using a CA. My goal is to learn how an SMC is structured and issued by the driver. I have root privileges on a hikey board with everything working.
On another matter, does the OP-TEE OS provide some default functionality I can call with SMCs?

I have read the code but I cannot grasp the full extent of the answer to my question.
Thank you for your time,
Nick

**Comment by lorc** [comment]
Hi @nikoskoutr,

There is header file `linux/arm-smccc.h` in linux. It defines `arm_smccc_smc()` function, which does actuall SMC invocation.
