### ISSUE TITLE
Return String from TA

### ISSUE THREAD

**Issue by Makht916** [OP-TEE/optee_os#1932]
Hello,

I am having a issue while returning the string value from TA. I have checked some previous FAQ question as well and following the correct guide line. And I am using OPTEE release "https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master".

My host code chunk is,

 memset(&op, 0, sizeof(op));
op.paramTypes = TEEC_PARAM_TYPES(TEEC_VALUE_INOUT, TEEC_MEMREF_TEMP_OUTPUT, TEEC_NONE, TEEC_NONE);
	op.params[0].value.a = 99;
	char ret[5]; //here I initialized the memory for output.
	op.params[1].tmpref.buffer = (void *)ret;
	op.params[1].tmpref.size = 5;

TA code chunk is,

static TEE_Result dec_value(uint32_t param_types,
	TEE_Param params[4])
{
	uint32_t exp_param_types = TEE_PARAM_TYPES(TEE_PARAM_TYPE_VALUE_INOUT,
						   TEE_PARAM_TYPE_MEMREF_OUTPUT,
						   TEE_PARAM_TYPE_NONE,
						   TEE_PARAM_TYPE_NONE);
	char ret_arg[] = "HELLO";
	DMSG("has been called");

	if (param_types != exp_param_types)
		return TEE_ERROR_BAD_PARAMETERS;

	IMSG("Got value: %u from NW", params[0].value.a);
	params[0].value.a--;
	IMSG("Decrease value to: %u", params[0].value.a);

	params[1].memref.buffer = (void *) ret_arg;
	params[1].memref.size = 5;
	IMSG("String : %s", (char *)params[1].memref.buffer); // it print the "HELLO" in SW logs
	return TEE_SUCCESS;
}

Now I am trying to get this value in NW as below,

const char* plain = (const char*)op.params[1].tmpref.buffer;

It give me some garbage value in NW world. What's wrong in my procedure?!

Many thanks in advance.

Regards,

**Comment by etienne-lms** [comment]
Your issue is that the TA tries to return to the client a memory buffer of its own private memory.
The output buffer parameters must be passed by the client to the TA, the TA should fill the buffer and then return to the TA. TA cannot replace the provided output buffer with another buffer.

Required changes in your TA:
```patch
 if (param_types != exp_param_types)
 	return TEE_ERROR_BAD_PARAMETERS;
 
 IMSG("Got value: %u from NW", params[0].value.a);
 params[0].value.a--;
 IMSG("Decrease value to: %u", params[0].value.a);
 
-params[1].memref.buffer = (void *) ret_arg;
+if (params[1].memref.size < 5)
+	return TEE_ERROR_BAD_PARAMETERS;
+memcpy(params[1].memref.buffer, ret_arg, 5);
 params[1].memref.size = 5;
 IMSG("String : %s", (char *)params[1].memref.buffer); // it print the "HELLO" in SW logs
 return TEE_SUCCESS;
```

**Comment by Makht916** [comment]
Hi,

Thanks for your prompt response. Yes, it is working now.  

Have a nice weekend.

Regards,
