### ISSUE TITLE
Calling optee driver from another driver

### ISSUE THREAD

**Issue by mkravchik** [OP-TEE/optee_os#1934]
Hi,
I want to issue a call to TA from a driver. I understand that I should do it via the optee driver. Could anyone provide a guidance on the proper way to do it?
Thanks a lot!

**Comment by jforissier** [comment]
Hi @mkravchik,

You need to use the interface in this commit: https://github.com/linaro-swg/linux/commit/7efd6cdca7a7
It is not (yet) in the upstream kernel, but if you're using the Linaro OP-TEE branch (https://github.com/linaro-swg/linux/tree/optee), you have it already.

**Comment by mkravchik** [comment]
Thanks a lot!
