### ISSUE TITLE
OPTEE dev issue

### ISSUE THREAD

**Issue by Cuixiaoxia198106** [OP-TEE/optee_os#1935]
1.	When TEE driver probe, It will get SHM configuration from TEE. and separate the share memory into private buffer and DMA buffer.
the private buffer is used by supplicant thread.  The buffer is used to copy TA data after signature verify pass. 
the DMA buffer is used by normal client thread, the buffer is used to copy data quickly. 
So, my question is what the share memory range is ? if it is too small. It must be failure. 

2.	Does the OPTEE OS support Lower Power Management  ?
3.	Does the OPTEE OS have own RTOS ? what’s the license. And does it support request reentry ?
4.	I saw there is no message verify in transfer, should it need?

**Comment by jenswi-linaro** [comment]
1. That's the memory used for communication between secure and non-secure world.

2. Yes, some platforms support suspend via PSCI

3. No RTOS, 2-clause BSD license

4. Don't understand the question, please rephrase/elaborate.

**Comment by Cuixiaoxia198106** [comment]
4. the  struct tee_ioctl_param is transferred from ree to tee, should we add some verification code for the params ?

**Comment by jenswi-linaro** [comment]
We do check those params quite a lot already. Anything in particular you have in mind?

**Comment by etienne-lms** [comment]
@Cuixiaoxia198106, note that structure tee_ioctl_param is not transferred straight from client application to the TEE. It is reformatted in the Linux kernel driver and formatted again in the TEE before reaching a trusted application.

**Comment by Cuixiaoxia198106** [comment]
@jenswi-linaro @etienne-lms if the parameters is delivered by linux kernel driver to TEE OS. I also don't find any checksum or other verification code to check the parameters integrity. 

other, if OPTEE OS is no RTOS, it doesn't support reentry, right ?

**Comment by Cuixiaoxia198106** [comment]
and OPTEE OS is a single thread ?

**Comment by jenswi-linaro** [comment]
What's the point of normal world checksumming something for secure world to verify? It's not something that secure world can trust any way.

OP-TEE OS is multi-threaded, but scheduled by normal world.

**Comment by Cuixiaoxia198106** [comment]
So, all arguments from REE is not trusted by tee. And how does tee get correct parameters from REE?

I don’t know how to design a firmware with mult thread without RTOS. Can you share ?

**Comment by jenswi-linaro** [comment]
If normal world supplied invalid/bad parameters to secure world that's a normal world problem.

Please check the documentation, https://github.com/OP-TEE/optee_os/blob/master/documentation/optee_design.md is a good start.

**Comment by Cuixiaoxia198106** [comment]
No. If REE issue correct parameters. There is also a choice to be modified by someone before tee receive it. So. I think a simple data integrity check is must. 

Ok. I will check it

**Comment by lorc** [comment]
@Cuixiaoxia198106, from OP-TEE point of view, all data that come from NW is untrusted. It even don't trust to own supplicant and own linux driver.

Which entity can modify parameters that com from REE? And if it can - what will stop it from calculation right checksum?

**Comment by Cuixiaoxia198106** [comment]
if it works under bad condition and those data might be modified by EMA or other, if TEE went to check the data integrity and discard the current request in case of bad data integrity, it might be a attack. i don't know if it can reduce the possible in real world.

**Comment by lorc** [comment]
Excuse me, but what is EMA?

**Comment by Cuixiaoxia198106** [comment]
ElectroMagneticAttack

**Comment by lorc** [comment]
Oh, I see. But then it can change state of OP-TEE itself. There is no difference in this case.

**Comment by Cuixiaoxia198106** [comment]
you can treat them as same case. but if it is with only small bits change, the way can prevent it. it can't stop the attack fully but it can ease it:-)
