### ISSUE TITLE
PTA/Interrupt handler RNG

### ISSUE THREAD

**Issue by Matombo** [OP-TEE/optee_os#1936]
Is there a function to get a (pseudo-)random value from within a pseudo-ta or an interrupt handler?

**Comment by jforissier** [comment]
`TEE_Result crypto_rng_read(void *buf, size_t blen);` or `crypto_ops.prng.read(void *buf, size_t blen);` if you don't have commit 36a063efe1f1 ("Replace struct prng_ops with function interface") yet.

Not sure about the validity of such a call in an interrupt handler, however.

**Comment by Matombo** [comment]
thanks, that worked for pseudo TA's, but sadly not for interrupt handler
