### ISSUE TITLE
OPTEE OS support mult-thread

### ISSUE THREAD

**Issue by Cuixiaoxia198106** [OP-TEE/optee_os#1940]
Hi All:
As TZ services request from REE in trap, if there is no REE interrupt happen, all requests should be deal with one by one... 
therefore, the mult-thread support only happen in case of there is REE task switch after TEE goes to response to REE interrupt, and the new active task request TEE service again .  am I right ?
in this case, how does OPTEE OS ensures the first TEE service recover context when REE come back to TEE ?

**Comment by jenswi-linaro** [comment]
You'll find the details at https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread.c#L524

Multiple cores can be active in OP-TEE at the same time also.
