### ISSUE TITLE
OP-TEE NS bit

### ISSUE THREAD

**Issue by ranjithvs** [OP-TEE/optee_os#1945]
Dear all,
  
    In my system u-boot boots op-tee and zImage. I just wanted to know where they are doing ns bit to 0 in optee and ns bit to 1 for kernel and ns-bit in u-boot? We know that OP-TEE should be in Secure (NS bit 0 ) in SCR in CP15 Register.?

Best Regards,
Ranjith Hebbar V S

**Comment by jforissier** [comment]
Hi @ranjithvs,

ARMv7 or ARMv8?

**Comment by ranjithvs** [comment]
It's ARMV7 based

**Comment by jforissier** [comment]
- When entering OP-TEE from SMC, NS bit is cleared here: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/sm/sm_a32.S#L176. If OP-TEE is entered due to a FIQ, it's cleared here: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/sm/sm_a32.S#L225.
- When returning to normal world, NS bit is set here: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/sm/sm_a32.S#L162

**Comment by etienne-lms** [comment]
@ranjithvs, I understand you are dealing with boot stage. Could you detail the u-boot load and boot process you expect? Start point is u-boot executes in secure state. If using a standard OP-TEE on an ARMv7, it is the OP-TEE that will switch the SCR[NS] bit at boot time and, as stated by @jforissier at each TEE entry from interrupts or SMCs.

Regarding the boot sequence, it could be:
- u-boot loads optee, dtb, linux to RAM;
- u-boot jumps to optee entry;
- optee runs the inits and jumps to non secure (Linux kernel) entry;
  => Here it is optee that sets SCR[N]=0/1
- Linux kernel boots.

Note that native u-boot currently does not support optee standard boot. Only some imx-omap do boot optee. The omap scheme is different i think, but you should ask maintainers:
- u-boot loads optee image(s) to RAM;
- u-boot jumps to optee entry
- optee runs the inits and jumps back to u-boot in non secure state.
  => Here it is also optee that sets SCR[N]=0/1
- Linux kernel boots.

Note that, as op-tee needs to load its TZ monitor, at  ARMv7 boot time, it is always op-tee that gets entered in secure state (NS=0) and will exits in non secure state (NS=1), mainly through generic optee code.

The Linux kernel boot setup (entrypoint + DTB address) can be hard code in optee . If you instrument a specific command in u-boot, you could pass these arguments through the core registers. See https://github.com/OP-TEE/optee_os/blob/2.6.0/core/arch/arm/kernel/generic_entry_a32.S#L215 for the hard coded `CFG_xxx` or entry arguments.

**Comment by ranjithvs** [comment]
@jforissier @etienne-lms Thank you guys for your detailed information. It helped me in better understanding...:)

**Comment by kumarabekur** [comment]
Hello @jforissier @etienne-lms 
I would like to know few more information about setting of NS bit.

1. In Default Uboot -> Linux boot-flow whether U-boot by default is in Secure state? In there any piece of code which is setting non secure state (NS = 1) in U-boot. ?

2. Suppose If I have boot-flow like SPL -> OPTEE -> Uboot -> Linux, where exactly I have to set NS bit? I am jumping to Uboot from OPTEE before _smc     #0_ in _core/arch/arm/kernel/generic_entry_a32.S_ . @jforissier pointed that setting of NS bit before it goes to non secure state is `https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/sm/sm_a32.S#L162` . In my case whether it should be disabled. ??

**Comment by etienne-lms** [comment]
hello,

> 1.

U-boot can be built to not modify the NS bit when booting Linux (or wahtever) or to set NS=1 when booting the dear kernel. This is driven from some u-boot configuration directives (@igoropaniuk surely knows the config names).

In the former case, u-boot can be booted in CPU secure state (if so, Linux will be booted in secure state) or u-boot can be booted in non secure state (if so, Linux will be booted in non secure state).

In the later case, u-boot must be booted in CPU secure state and will executes partly as secure and partly as non secure (tbc).

I don't know was is the u-boot "default" config.

> 2.

armv7/optee madates that:
- optee is booted (entered) with CPU is secure state
- optee exits its inits by jumping into a non secure image with the CPU set in non secure state.

So, if u-boot is booted after op-tee, OPTEE will set NS=1 before jumping to u-boot and u-boot must therefore execute in CPU non secure state. I don't think it is a good idea to (patch optee and) have a u-boot executing in secure state after op-tee has initialized.
