### ISSUE TITLE
Why there is no TEE_ClosePersistentObject func?

### ISSUE THREAD

**Issue by Yanjiong** [OP-TEE/optee_os#1951]
Hi Expert,

I'm wondering why there is no TEE_ClosePersistentObject func exist. 

From what I see in debug, the Persistent Object just be closed when the ta destroyed.

Maybe it's a good way to provide TEE_ClosePersistentObject func which could be called by user ta when the obj is not needed.

Thanks.

BR.
Wang Yanjiong

**Comment by jforissier** [comment]
Hi @Yanjiong ,

Just use `TEE_CloseObject()`.

**Comment by Yanjiong** [comment]
Got it, Thanks.

The TEE_CloseObject function closes an opened object handle. The object can be persistent or transient.
For transient objects, TEE_CloseObject is equivalent to TEE_FreeTransientObject .
