### ISSUE TITLE
About Trusted Storage in op-tee

### ISSUE THREAD

**Issue by Tigerly** [OP-TEE/optee_os#1954]
Hello,

I checked the op-tee's code and examples, and I found that there are several operations about trusted storage, such as TEE_CreatePersistentObject, TEE_OpenPersistentObject, TEE_WriteObjectData, etc.

Here are my questions:
1. what's the maximum size of the trusted storage for a TA?
2. If I create a persistent object with some data, then where does it be saved in the system?
3. How does is be stored? Does the persistent object be saved as an external file or just some data structure like hash table in memory?

Thanks in advance!

**Comment by jenswi-linaro** [comment]
1. There's no fixed upper limit
2. It's saved under `/data/tee/`
3. It's saved as a file in the filesystem

**Comment by jforissier** [comment]
> 1. There's no fixed upper limit
> 2. It's saved under `/data/tee/`
> 3. It's saved as a file in the filesystem

Just for the sake of completeness: true for the default configuration (when CFG_REE_FS=y). Otherwise, if using RPMB only, you are limited by  the size of the RPMB partition and the persistent objects are in RPMB not in the Linux filesystem.

**Comment by stuyoder** [comment]
Which boards supported by OP-TEE have RPMB?

(I could look through the specs for each supported board, but thought someone might have a quicker answer.  What boards do the OP-TEE developers use to test the RPMB storage feature?)

**Comment by jforissier** [comment]
HiKey has an eMMC chip, hence an RPMB partition. You can also use external eMMC chips on a microSD adapter.
But, the easiest for developers is to use the RPMB emulation in `tee-supplicant`. It is enabled by default, so that's what is used when you build optee with `CFG_RPMB_FS=y`.

**Comment by Tigerly** [comment]
@jforissier @jenswi-linaro Thanks for the explaining! It's very helpful.
I have a follow-up question, why the trusted storage provided by trusted zone is secure. I mean, if the data is saved in /data/tee/ in file system. Attackers having the root authority still can access it, right?
Or the /data/tee is a part of an independent area that is isolated by trusted zone?
Thanks in advance!

**Comment by etienne-lms** [comment]
hi @Tigerly.

When storing secure data in /data/tee, it means the TEE uses the "ree_fs" secure storage: secure data (objects) are encrypted and stored in a hash tree structure which binary content is written into REE file filesystem (/date/tee/...). The root hash node must be stored in some secure persistent storage (i.e an RMPB entry). Reading the /data/tee filetree file Linux cannot help one to discover the effective data content. Erasing or modifying /data/tee content will end in portions/all of secure data being corrupted and detected as so by the TEE when accessed. These are denial of service attacks to be considered.

Using "ree_fs" or not, one can also use the "rpmb_fs" secure storage. Secure data/objects are stored straight in the eMMC RPMB partition, nothing in the REE filesystem. Data is encrypted and the eMMC means insure rollback protection of the data. Yet, since TEE goes through REE to access the RPMB, corruption of data while passing through REE are D-o-S to be considered.

**Comment by jforissier** [comment]
Yes, root can cause a "denial of service" by deleting files, or modifying them. But, any modification is detected be cause authenticated encryption is used.
For more protection, you can use RPMB (`CFG_RPMB_FS=y` and optionally `CFG_REE_FS=n, see the code for details).

**Comment by coach-bin** [comment]
@jforissier @etienne-lms 
I have a question. What is the difference between 'CFG_RPMB_FS=y + **CFG_REE_FS=**y****' and 'CFG_RPMB_FS=y + **CFG_REE_FS=n**' in operation?

**Comment by jforissier** [comment]
@coach-bin please see https://optee.readthedocs.io/en/latest/architecture/secure_storage.html.

> 'CFG_RPMB_FS=y + CFG_REE_FS=y' 

In this case, the default storage for TAs is the REE FS, RPMB can be used if specified explicitly, RPMB is used for anti-rollback protection.

> 'CFG_RPMB_FS=y + CFG_REE_FS=n'

Secure storage is only stored in the REE FS. There is no anti-rollback protection.

**Comment by coach-bin** [comment]
Thanks for your answer, but it's quite strange. Could it be that you are thinking of the two in reverse?
In the case of that CFG_RPMB_FS is enabled, what I'm wondering is if there is any difference in behavior whether CFG_REE_FS is enabled or not

> > 'CFG_RPMB_FS=y + CFG_REE_FS=y'
> 
> In this case, the default storage for TAs is the REE FS, RPMB can be used if specified explicitly, RPMB is used for anti-rollback protection.

If CFG_RPMB_FS and CFG_REE_FS are enabled, you mean REE_FS has a higher priority? How can I explicitly specify to use RPMB in this case?

> > 'CFG_RPMB_FS=y + CFG_REE_FS=n'
> 
> Secure storage is only stored in the REE FS. There is no anti-rollback protection.

CFG_REE_FS=n, so secure storage is only stored in the PRMB partition and this should support anti-rollback protection

**Comment by jforissier** [comment]
> > > 'CFG_RPMB_FS=y + CFG_REE_FS=y'
> > 
> > 
> > In this case, the default storage for TAs is the REE FS, RPMB can be used if specified explicitly, RPMB is used for anti-rollback protection.
> 
> If CFG_RPMB_FS and CFG_REE_FS are enabled, you mean REE_FS has a higher priority?

Yes.

> How can I explicitly specify to use RPMB in this case?

Use `TEE_STORAGE_PRIVATE_RPMB` instead of `TEE_STORAGE_PRIVATE`.

> > > 'CFG_RPMB_FS=y + CFG_REE_FS=n'
> > 
> > 
> > Secure storage is only stored in the REE FS. There is no anti-rollback protection.
> 
> CFG_REE_FS=n, so secure storage is only stored in the PRMB partition and this should support anti-rollback protection

Correct. My mistake I read too quickly.
