### ISSUE TITLE
TEEC_OpenSession gives TEEC_ERROR_SECURITY on HiKey

### ISSUE THREAD

**Issue by psivasubramanian** [OP-TEE/optee_os#1958]
Hi,
I'm seeing the below issue while running 32bit TA(optee-test) on 64bit HiKey kernel and optee-os.

root@hikey-32:~# xtest 1004
Test ID: 1004
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# regression
#
######################################################
 
* regression_1004 Test User Crypt TA
/usr/src/debug/optee-test/2.4.0+gitAUTOINC+213ca8aaf4-r0/git/host/xtest/regression_1000.c:298: xtest_teec_open_session( &session, &crypt_user_ta_uuid, ((void *)0), &ret_orig) has an unexpected value: 0xffff000f = TEEC_ERROR_SECURITY, expected 0x0 = TEEC_SUCCESS
  regression_1004 FAILED

I'm able to confirm optee linux driver initialisation using "dmesg | grep optee" and device node /dev/tee0 or teepriv0. Also, able to run tee-supplicant binary without any error in the background. But sometimes getting "ERR [28303] TEES:load_ta:279:   TA not found" from it if TA uuid is not available in /lib/optee_armtz.

Version Info:
Yocto OE - 2.2
optee - 2.4.0
kernel - 4.9

Any pointers on what I am missing/wrong?

**Comment by vchong** [comment]
Are you getting error just for 1004 only? Have you tried other test numbers, or say the hello world test from https://github.com/linaro-swg/hello_world?

> But sometimes getting "ERR [28303] TEES:load_ta:279: TA not found" from it if TA uuid is not available in /lib/optee_armtz.

Yes, this is expected but it should be all the time. 'Sometimes' seems to indicate that you're possibly copying and deleting TA files from the file system?

**Comment by psivasubramanian** [comment]
> Are you getting error just for 1004 only? Have you tried other test numbers, or say the hello world test from https://github.com/linaro-swg/hello_world?

Thanks for your reply. I'm getting this error for most of the tests in optee-test.

> Yes, this is expected but it should be all the time. 'Sometimes' seems to indicate that you're possibly copying and deleting TA files from the file system?
It's coming always if TA corresponding to given uuid is not available.

**Comment by vchong** [comment]
You're welcome. So as advised on irc, please check use of `COMPILE_S_USER` in https://github.com/OP-TEE/build/blob/master/hikey.mk and https://github.com/OP-TEE/build/blob/master/common.mk and see if perhaps you can get more clues.

> It's coming always if TA corresponding to given uuid is not available.

Yes this is expected and nothing out of the ordinary.

**Comment by psivasubramanian** [comment]
As discussed on irc & hangouts, the issue vanished when I recompiled 64bit optee-os with TEE Core logs enabled & reflashed the fip.bin generated from the Yocto build.
