### ISSUE TITLE
Potential Memory Leak at `tee_fs_rpc_opendir` of `core/tee/tee_fs_rpc.c`

### ISSUE THREAD

**Issue by viennadd** [OP-TEE/optee_os#1960]
Hi all,

Our code scanner Pinpoint has reported a potential memory leak at the follow:
https://github.com/OP-TEE/optee_os/blob/24bb751635df538d8dae943a728c00941e0cd280/core/tee/tee_fs_rpc.c#L364-L381

the early return of `return TEE_ERROR_BAD_STATE; `  at line 380 will leak the memory block pointed by `dir` (line 364) , could someone have a look and see if it needs a patch ?

Best Regards,
Alex, Sourcebrella Inc.

**Comment by jforissier** [comment]
Hi @viennadd ,

Thanks for reporting. Indeed, line 380 looks wrong and line 384 also. Would you like to submit a pull request?

**Comment by viennadd** [comment]
@jforissier Sure, I update the `res` variable and change the statement from `return` to `goto err_exit` in line 380 & line line 384, you might want a double check on the PR.
