### ISSUE TITLE
Potential Double free in the older version of libtomcrypt

### ISSUE THREAD

**Issue by viennadd** [OP-TEE/optee_os#1962]
Hi all,

Our code scanner Pinpoint has reported a double free at https://github.com/OP-TEE/optee_os/blob/24bb751635df538d8dae943a728c00941e0cd280/core/lib/libtomcrypt/src/pk/dsa/dsa_import.c#L136-L158

if it follows the `goto LBL_ERR;` in line 150, tmpbuf will be freed again, seems the upstream of libtomcrypt have already fixed this issue.

Regards,
Alex, Sourcebrella Inc.

**Comment by jforissier** [comment]
Hi @viennadd,

Thanks for reporting this. Please note that `dsa_import.c` is not normally used by OP-TEE, so the bug cannot occur. Still, I'll pick up the upstream patch since we do have the file in our tree and some users might be using it in there private branches.

**Comment by viennadd** [comment]
@jforissier great job, I should close this issue then.
