### ISSUE TITLE
Using Undefined Behavior  to detect pointer arithmetic overflow in older version of libfdt

### ISSUE THREAD

**Issue by viennadd** [OP-TEE/optee_os#1967]
Hi all,

Our code scanner Pinpoint has reported an invalid testing for overflow in libfdt,
https://github.com/OP-TEE/optee_os/blob/b1469ba0bfd0371eb52bd50f5c52eeda7a8f5f1e/core/lib/libfdt/fdt.c#L77-L91

the following overflow detection is undefined behavior and might be discarded by compilers in different optimization levels[1].
```cpp
	if (p + len < p)
		return NULL;
```

this has been fixed in the upstream of libfdt: 
https://github.com/dgibson/dtc/commit/d0b3ab0a0f46ac929b4713da46f7fdcd893dd3bd#diff-842629fc73576aaea15c3de45cb95f93

Regards,
Alex, Sourcebrella Inc.

[1] Figure 4, [Towards Optimization-Safe Systems: Analyzing the Impact of Undefined Behavior](https://pdos.csail.mit.edu/papers/stack:sosp13.pdf)
![image](https://user-images.githubusercontent.com/3396288/33160200-3bceff1e-d055-11e7-9e95-806c43fa3130.png)

**Comment by jenswi-linaro** [comment]
Fix in https://github.com/OP-TEE/optee_os/pull/1969

**Comment by jenswi-linaro** [comment]
By the way, thanks for reporting. :-)

**Comment by viennadd** [comment]
seems I can close this issue now.
thanks @jenswi-linaro
