### ISSUE TITLE
Suspicious potential double free in ta_open() of ree_fs_ta.c

### ISSUE THREAD

**Issue by viennadd** [OP-TEE/optee_os#1968]
Hi,

Our code scanner Pinpoint has reported a potential double free in ta_open()
https://github.com/OP-TEE/optee_os/blob/b1469ba0bfd0371eb52bd50f5c52eeda7a8f5f1e/core/arch/arm/kernel/ree_fs_ta.c#L193-L246

`alloc_and_copy_shdr` could free shdr when return error, then it goes to label `error_free_payload`
```cpp
	res = alloc_and_copy_shdr(&shdr, ta, ta_size);
	if (res != TEE_SUCCESS)
		goto error_free_payload;
```

the implementation of `alloc_and_copy_shdr`, could free shdr when return error (line 75):
https://github.com/OP-TEE/optee_os/blob/b1469ba0bfd0371eb52bd50f5c52eeda7a8f5f1e/core/arch/arm/kernel/ree_fs_ta.c#L59-L79

then the label `error_free_payload` frees `shdr` again:
```cpp

error_free_payload:
	thread_rpc_free_payload(cookie, mobj);
error:
	free(hash_ctx);
	free(shdr);
	free(handle);
	return res;
```

Regards,
Alex, Sourcebrella Inc.

**Comment by jenswi-linaro** [comment]
Thanks for reporting, fix in https://github.com/OP-TEE/optee_os/pull/1970
