### ISSUE TITLE
Optee os can't startup base on ARM-ATF v1.1

### ISSUE THREAD

**Issue by sweetkeey** [OP-TEE/optee_os#197]
when I tested optee os with arm trusted firmware V1.1 (I utilized optee os tee.bin as bl32 image) on juno platform, I got an error:
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v1.1(debug):
NOTICE:  BL1: Built : 13:56:45, Feb 12 2015
INFO:    BL1: RAM 0x403a000 - 0x403d000
INFO:    Loading file 'bl2.bin' at address 0x4017000
INFO:    File 'bl2.bin' loaded: 0x4017000 - 0x401c008
NOTICE:  BL1: Booting BL2
INFO:    BL1: BL2 address = 0x4017000
INFO:    BL1: BL2 spsr = 0x3c5
NOTICE:  BL2: v1.1(debug):
NOTICE:  BL2: Built : 13:56:45, Feb 12 2015
INFO:    BL2: Loading BL3-1
INFO:    Loading file 'bl31.bin' at address 0x4023000
INFO:    File 'bl31.bin' loaded: 0x4023000 - 0x402c010
INFO:    BL2: Loading BL3-2
INFO:    Loading file 'bl32.bin' at address 0x6000000
INFO:    File 'bl32.bin' loaded: 0x6000000 - 0x605d3e0
INFO:    BL2: Loading BL3-3
INFO:    Loading file 'bl33.bin' at address 0x88000000
INFO:    File 'bl33.bin' loaded: 0x88000000 - 0x88280000
NOTICE:  BL1: Booting BL3-1
INFO:    BL1: BL3-1 address = 0x4023000
INFO:    BL1: BL3-1 spsr = 0x3cd
INFO:    BL1: BL3-1 params address = 0x4000200
INFO:    BL1: BL3-1 plat params address = 0xf1e2d3c4b5a6978
NOTICE:  BL3-1: v1.1(debug):
NOTICE:  BL3-1: Built : 13:56:46, Feb 12 2015
INFO:    BL3-1: Initializing runtime services
INFO:    BL3-1: Initializing BL3-2

stop here.why?

**Comment by vchong** [comment]
Did you build with FVP_TSP_RAM_LOCATION=tdram option based on https://github.com/OP-TEE/optee_os/blob/master/documentation/arm_trusted_firmware.md?

**Comment by ljmblueday** [comment]
My JUNO Board also stop same point. I build with commit 8f7de3fc92dbdfdc217b83403c64abc0bafb5d31

Author: Jens Wiklander <jens.wiklander@linaro.org>
Date:   Thu Dec 4 08:04:01 2014 +0100

    plat-vexpress: linking supports pagable tee.bin

    * Adds scripts to create a pagable tee.bin
    * Updates link script and link.mk to support pagable tee.bin
    * Binary format of tee.bin is changed from a raw format to a header
      followed by the binary data as described by the header. This requires
      updates in ARM-TF OP-TEE Dispatcher and QEMU virt bios.

    fvp:
    * Changes OP-TEE load address to start of TZDRAM_BASE

    Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
    Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jenswi-linaro** [comment]
The ARM-TF doesn't have support to load an OP-TEE binary with a header. Until main branch of ARM-TF has been updated to handle this please use this fork/branch instead: https://github.com/jenswi-linaro/arm-trusted-firmware/tree/optee_paged_141128

The setup script setup_fvp_optee.sh has been updated to use the fork/branch.
