### ISSUE TITLE
Query: Why do aflags add -mfpu=neon, but cflags not?

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#1972]
In conf.mk: core_arm32-platform-aflags	+= -mfpu=neon

Why do aflags add -mfpu=neon, but cflags not?
What is the use of this compilation option for assembly files?
Thanks!

**Comment by jenswi-linaro** [comment]
It's to allow usage of neon instruction in assembly. Perhaps there's some directive that could be used in each assembly file instead to avoid this, I haven't looked into it any deeper.

In C files we don't want it as it changes the ABI and the C compiler is allowed to access VFP registers any time.

**Comment by airbak** [comment]
Thanks for your reply : )

**Comment by jforissier** [comment]
> Perhaps there's some directive that could be used in each assembly file instead

`.fpu neon` I think:

```
$ diff -u <(echo | arm-linux-gnueabihf-gcc -S -xc -o - -) <(echo | arm-linux-gnueabihf-gcc -mfpu=neon -S -xc -o - -)
--- /dev/fd/63	2017-11-23 10:30:32.882519640 +0100
+++ /dev/fd/62	2017-11-23 10:30:32.882519640 +0100
@@ -1,6 +1,6 @@
 	.arch armv7-a
 	.eabi_attribute 28, 1
-	.fpu vfpv3-d16
+	.fpu neon
 	.eabi_attribute 20, 1
 	.eabi_attribute 21, 1
 	.eabi_attribute 23, 3
```

**Comment by jenswi-linaro** [comment]
Aha, that would be a nice cleanup to fix all the .S files and getting rid of the
```
core_arm32-platform-aflags	+= -mfpu=neon
```

**Comment by jforissier** [comment]
@jenswi-linaro I'll take care of that.

I noticed that some platforms have `arm32-platform-aflags += -mfpu-neon` (i.e., for all assembly files, not for the core only). I suspect it isn't on purpose, so it is a good opportunity to clarify.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/1976
