### ISSUE TITLE
Query: Some compile options for binscope  do not take effect

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#1973]
BinScope is a Microsoft verification tool that analyzes binaries to ensure that they have been built in compliance with Microsoft’s Security Development Lifecycle (SDL) requirements and recommendations.

When I add some compile options like follow, but it do not take effect.
BINSCOPE_CFLAGS += -Wl,-z,relro
BINSCOPE_CFLAGS += -Wl,-z,noexecstack 
core_arm32-platform-cflags     += $(BINSCOPE_CFLAGS)
arm32-platform-cflags     += $(BINSCOPE_CFLAGS)
core_arm32-platform-aflags	+= $(BINSCOPE_CFLAGS)
arm32-platform-aflags	+= $(BINSCOPE_CFLAGS)

binscope -a -f tee.elf  result:
* ReLocation Read-Only protection information:
  ReLocation Read-Only Feature:           No RELRO
* NX protection information:              
  NX Feature:                             Disable
  CPU Support NX:                         Yes

"ReLocation Read-Only Feature" is expected to "Part RELRO/Full RELRO".
 "NX Feature" is expected to "Enable".
I had tried to use these compile options on a simple C files, it toke effect.

Please help to analyze it, thanks!

**Comment by jenswi-linaro** [comment]
I'm not sure this makes much difference as OP-TEE is mapping itself as it likes.
The ELF file isn't even used when OP-TEE is loaded.

**Comment by airbak** [comment]
BinScope may not apply to tee.elf.
