### ISSUE TITLE
Met xtest segemation fault with linux driver support 2.5.0 + latest optee

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#1975]
Hi,

I am using linux driver that supporting 2.5.0 OP-TEE os to test latest optee os and met xtest segmentation fault.

Is this expected? latest optee os not compatible with 2.5.0 linux driver?

o regression_5006.12 InitializeContext_NotExistingTEE
  regression_5006.12 OK
o regression_5006.13 AllocateThenRegister_SameMemory
  regression_5006.13 OK
o regression_5006.14 AllocateSameMemory_twice
  regression_5006.14 OK
o regression_5006.15 RegisterSameMemory_twice
  regression_5006.15 OK
o regression_5006.16 Allocate_sharedMemory_32k
  regression_5006.16 OK
o regression_5006.17 Register_sharedMemory_32k
  regression_5006.17 OK
Segmentation fault (core dumped)

Thanks,
Peng.

**Comment by jenswi-linaro** [comment]
It should be compatible.
I'm suspecting the client header files, xtest and libteec out of sync.

Regards,
Jens

**Comment by MrVan** [comment]
Thanks Jens. It works.
