### ISSUE TITLE
Query regarding support for RSA 4K keys.

### ISSUE THREAD

**Issue by b49020** [OP-TEE/optee_os#1981]
As per below property from core/tee/tee_svc_cryp.c, it seems OP-TEE currently supports RSA keys of size upto 2K only.

        PROP(TEE_TYPE_RSA_KEYPAIR, 1, 256, 2048,
                sizeof(struct rsa_keypair),
                tee_cryp_obj_rsa_keypair_attrs),

Is there any plan to support RSA 4K keys?

**Comment by jforissier** [comment]
Hi @b49020,

I don't think so, but RSA keys larger than 2048 bits are certainly allowed by the GP specs, so patches are welcome ;-)

**Comment by b49020** [comment]
@jforissier Thanks for prompt reply.

**Comment by flowher** [comment]
4K keys are supported by mbedTLS, so after switch to new library, OP-TEE will get the support automagically, isn't ?

**Comment by b49020** [comment]
@flowher I don't think so as OP-TEE object structures currently support max 2K key size. This needs to be changed to 4K.

**Comment by flowher** [comment]
@b49020 ah, didn't realized that there is a limitation in optee. thnx
