### ISSUE TITLE
Questions about pseudo TA and memory

### ISSUE THREAD

**Issue by jenkin233** [OP-TEE/optee_os#1984]
Hi,
I am looking through the source code of op-tee lately,and I have a few following questions:
1.what mode is pseudo TA runs in? In the other words,is it running in user mode or kernel mode? 
2.In pTA, is there any method that I can use to get a memory block which can be executable.Because I want a memory to execute some code that will be loaded during run time. Is this possible?

Thanking you for any help given

**Comment by jforissier** [comment]
Hi @jenkin233,

> I am looking through the source code of op-tee lately,and I have a few following questions:
> 1.what mode is pseudo TA runs in? In the other words,is it running in user mode or kernel mode? 

Kernel mode.

> 2.In pTA, is there any method that I can use to get a memory block which can be executable.Because I want a memory to execute some code that will be loaded during run time. Is this possible?

No.

More about TAs: https://github.com/OP-TEE/optee_os/blob/master/documentation/optee_design.md#12-trusted-applications

**Comment by jenkin233** [comment]
Thanks for your quick reply. @jforissier For your answer, I think it's impossible because of the following reason: When a pTA want a memory block, it can use either _malloc or _calloc api. While these will alloc the memory  from heap, and the heap is not executable.  Is am right?

**Comment by jenkin233** [comment]
Thanks for your quick reply @jforissier . For your answer, I think it's impossible because when a pTA want a memory block, it can use either _malloc or _calloc api, while these will alloc memory from heap, and heap is not executable . Am I right?

**Comment by jforissier** [comment]
@jenkin233 correct.
