### ISSUE TITLE
2.5Mb TA application is failed to load.

### ISSUE THREAD

**Issue by ademyankov** [OP-TEE/optee_os#1989]
I had a working CA-TA applications so far (TA was around 400Kb). But, now I have a problem, after I included all the code needed for my TA application it grew up to 2.5Mb (debug build) and OP-TEE OS fails to load the app.

tee_entry_open_session
tee_ta_open_session
tee_ta_init_session

Function tee_ta_init_session fails inside tee_ta_manager.c:
```
540             res = tee_ta_init_session(err, open_sessions, uuid, &s);
541             if (res != TEE_SUCCESS) {
542                     DMSG("init session failed 0x%x", res);
543                     return res;
544             }
```
![image](https://user-images.githubusercontent.com/13845895/33632069-5ee93b2a-d9c1-11e7-8b24-4bcf9d797192.png)

user_ta_header_defines.h:
```
#define TA_STACK_SIZE   (0x20000)  // 128Kb
#define TA_DATA_SIZE    (0x500000) // 5Mb
```

**Q: What would you recommend to look into?**

**Comment by vchong** [comment]
Try increasing TA_STACK_SIZE instead.

**Comment by ademyankov** [comment]
Ok, problem solved. It looks like OPTEE-OS had some vital update so, I had to re-sync the repo and rebuild everything.
