### ISSUE TITLE
Running OPTEE on RPi3 Linaro vivid

### ISSUE THREAD

**Issue by Marwen10** [OP-TEE/optee_os#1990]
Hello,
I'm trying to use Linaro vivid as my rootfs to do some developping. But after booting up, When I launch 
$ tee-supplicant & 
I get : 
ERR [477] TEES:main:663: failed to find an OP-TEE supplicant device
when I run 
$ dmesg | grep optee
I get:
optee: probing for conduit method from DT
optee: initialized driver
any help is appreciated

**Comment by lorc** [comment]
Hi @Marwen10,

Can you please check that `/dev/tee0` and `/dev/teepriv0` exist in `/dev/` ?

Also, can you please run `id` to ensure that you are working as root?

**Comment by Marwen10** [comment]
Thanks @lorc,
The issue was that I didn't run tee-supplicant & as a root
Now it works greatly
Thank you very much
