### ISSUE TITLE
Adding Develop Guides for Dynamic load TAs

### ISSUE THREAD

**Issue by kevin-peng-hao** [OP-TEE/optee_os#1991]
I couldn't find any documents about how to develop TAs. Currently there is only a `hello_world` sample for reference but it might be to simple.
I personally met some questions how to build, how to add extra libraries to link, how to set TA properties, etc…
Also I fixed them by myself by researching, it would be much easier if there is a document on these topics.

**Comment by jforissier** [comment]
Hi @kevin-peng-hao ,

`hello_world` is obsolete now. The new repository for TA examples is https://github.com/linaro-swg/optee_examples. All detailed documentation should go there, patches are welcome ;-)
Maybe it would be useful to point to this project from the OP-TEE OS documentation folder (https://github.com/OP-TEE/optee_os/tree/master/documentation).

**Comment by kevin-peng-hao** [comment]
Great @jforissier , I read the docs quickly and I think most of the answers to my confusions can be answered. So don't hide the repository, let others know about it, haha :). It would be great help to starters of optee TA developers.

Thanks,
Kevin
