### ISSUE TITLE
Questions about TA return result

### ISSUE THREAD

**Issue by jenkin233** [OP-TEE/optee_os#1996]
Hi,all
As far as I know, CA and TA's communication is  implement through Share_Memory, which means when TA return results to CA, the results is placed in a place that a rich OS can touch. Under this circumstances ,I was wondering how OP-TEE can protect the result will not be  tampered by a malicious rich OS?
Thanking you for any help given.

**Comment by lorc** [comment]
There are no way to protect from RichOS, because CA works  in userspace. Sensitive data should never leave OP-TEE.
