### ISSUE TITLE
Isolation b/w TA

### ISSUE THREAD

**Issue by Makht916** [OP-TEE/optee_os#2006]
I have a question regarding isolation of TA within secure world. Is TA isolated within secure world or do we need some additional work to make this isolation among TAs.

Many thanks in advance.

Regards,

**Comment by jenswi-linaro** [comment]
Each TA is sandboxed in its own virtual memory space and can only access its own secure objects. The only way for a TA to communicate with the outside world is via either by being invoked (from non-secure or secure world) or by invoking another TA using the TEE Internal API functions.
