### ISSUE TITLE
How to get OPTEE source code against  Rockchip rk3399?

### ISSUE THREAD

**Issue by YumingMa** [OP-TEE/optee_os#2007]
I get source code against rk3399, but I can't find any OPTEE code in it, only see some .ko file.
https://gitlab.com/TeeFirefly/FireNow-Nougat/tree/e6ca6be9a7feb71a9d34f97956fe5b58faee7b7d/vendor/rockchip/common/security/optee

**Comment by lorc** [comment]
Hi @YumingMa,

According to `core/arch/arm/plat-rockchip/platform_config.h`, mainline OP-TEE supports only rk322x. 
So, you need to contact your vendor (T-Firefly, I suppose) and ask them, how they built OP-TEE for rk3399.

.ko file is a linux kernel module. I think, they built it from `drivers/tee/optee` in linux kernel tree. Linux part of optee is device-agnostic and should work on any platform that is supported by OP-TEE.

**Comment by YumingMa** [comment]
Thank you for your reponse!
I run "insmod optee.ko" and met the error that the version magic didn't match. They built it on linux 3.x.x，but I run it on linux 4.x.x. So I want to have got source code.

**Comment by lorc** [comment]
It should be included in your linux source. Check out the mentioned path (`drivers/tee/optee`).
If it is absent, you can try to backport OP-TEE driver from newer version. It has small set of dependencies, so I believe, it can be easily backported to any 4.x.x version of linux kernel.

**Comment by YumingMa** [comment]
I didn‘t find the OPTEE source in the following link. My surprise is that they don't  open source. I'm worried that they added a function for optee.ko or optee_armtz.ko.
https://gitlab.com/TeeFirefly/FireNow-Nougat/tree/e6ca6be9a7feb71a9d34f97956fe5b58faee7b7d/kernel/drivers

**Comment by YumingMa** [comment]
I found out the source code. Thank you! I will close it.

**Comment by mysticTot** [comment]
> I found out the source code. Thank you! I will close it.

Would you please share the source code link which you found
