### ISSUE TITLE
use "rand()" in TA

### ISSUE THREAD

**Issue by Tigerly** [OP-TEE/optee_os#2008]
Hello,
Now I'm trying to use "rand()" in TA. However, when I compile it, it always complains "undefined reference to `rand' ".

My compile command is like:
/home/optee/qemu-optee/toolchains/aarch32/bin/arm-linux-gnueabihf-ld.bfd -pie -T ./ta.lds -Map=./08430668-3463-4c83-9593-a18350f54b57.map --sort-section=alignment  ./ta.o ./user_ta_header.o  -L/home/optee/qemu-optee/optee_os/out/arm/export-ta_arm32/lib -lutee -lpng -lzlib -lutils -lmpa -o 08430668-3463-4c83-9593-a18350f54b57.elf

Did I miss to link some libraries?
Does op-tee support the "rand()" in TA?

Thanks in advance!

**Comment by lorc** [comment]
AFAIK, libutee does not provide `rand()`.  You can use  `TEE_GenerateRandom()` instead, as described in GlobalPlatform specs.

**Comment by Tigerly** [comment]
@lorc Thanks for replying! got it. BTW, op-tee also didn't support get system time? I include <sys/time.h> but it also complains the dependencies.

**Comment by lorc** [comment]
@Tigerly, again, there is `TEE_GetSystemTime()`. You really should check "TEE Internal Core API Specification" at GlobalPlatform site.

**Comment by Tigerly** [comment]
@lorc got it, thanks! Can I say that the TA running in the secure world cannot use common methods to get a random number and the system time? We can only rely on the TEE core API, right?

**Comment by Tigerly** [comment]
@lorc got it, thank you so much!!!
