### ISSUE TITLE
TA_CreateEntryPoint still called every time even TA set to single instance & keep alive

### ISSUE THREAD

**Issue by kevin-peng-hao** [OP-TEE/optee_os#2009]
I set the TA_FLAGS in user_ta_header_defines.h to:
```
(TA_FLAG_SINGLE_INSTANCE | \
TA_FLAG_MULTI_SESSION | \
TA_FLAG_INSTANCE_KEEP_ALIVE | \
TA_FLAG_EXEC_DDR)
```
But the `TA_CreateEntryPoint` is still called every time a CA opens session or invokes command.
But the global variable in TA works as expected, meaning the value of the variable is kept.
Is this expected? I thought `TA_CreateEntryPoint` should be called only once.

Thanks.

**Comment by jforissier** [comment]
Hi @kevin-peng-hao,

No, it's a bug. Table 4-6 in the GP Internal Core API spec (v1.1.2) clearly states that "[TA_CreateEntryPoint] is called once and only once in the life-time of the Trusted Application instance".

Can you please try https://github.com/OP-TEE/optee_os/pull/2010? Thanks!

**Comment by kevin-peng-hao** [comment]
Hi @jforissier ,

The TA_CreateEntryPoint 's behaviour is correct with #2010,
But should TA_DestroyEntryPoint not be called for keep alive TAs?

**Comment by jforissier** [comment]
Good. Would you please add your Acked-by: or Tested-by: to the pull request?

Regarding `TA_DestroyEntryPoint()`, indeed I think it should be called when the system is powered off or reset. But there is no code to do that currently.

**Comment by kevin-peng-hao** [comment]
Hi @jforissier 
Regarding `TA_DestroyEntryPoint()`, I'm saying that it should **NOT** be called until TEE shuts down for keep alive TAs.
The currently situation is that it's called every time a CA closes session.

**Comment by jforissier** [comment]
Hopefully all fixed in https://github.com/OP-TEE/optee_os/pull/2012.

**Comment by kevin-peng-hao** [comment]
All fixed, thanks.
BTW, what's the diffrerences between `Acked-by:` and `Tested-by:`

**Comment by vchong** [comment]
@kevin-peng-hao See https://www.kernel.org/doc/html/v4.12/process/submitting-patches.html#when-to-use-acked-by-and-cc and https://www.kernel.org/doc/html/v4.12/process/submitting-patches.html#using-reported-by-tested-by-reviewed-by-suggested-by-and-fixes.

**Comment by kevin-peng-hao** [comment]
@vchong thanks very much.
