### ISSUE TITLE
Confused about booting optee_os on FSL ls1021a

### ISSUE THREAD

**Issue by nradulovic** [OP-TEE/optee_os#2022]
Hello,

I'm trying to boot optee_os (version 2.6.0) on **ls1021a-twr** platform. I have trouble getting the information how the boot process goes on this platform. The closest information about boot I got from this link: http://mrvan.github.io/optee-imx6ul

Steps:
1. Compile and configure the u-boot to boot into secure mode preserving the chain of trust. The script is setup to load:
   * kernel @ `0x82000000`, 
   * DT @` 0x90000000` and 
   * optee.img at `0x8300000`

   The u-boot image is signed with burned chip keys and passes validation. I've checked the SecMon (Security Monitor) status register (just before bootm command) and it's internal state machine is in `Secure` state.
2. Compile and configure the linux kernel, generate: `make uImage LOADADDR=80008000`
3. Compile optee_os with: `make CFG_TEE_CORE_LOG_LEVEL=4 DEBUG=y CFG_NS_ENTRY_ADDR=80008000 CFG_DT_ADDR=90000000 PLATFORM=ls PLATFORM_FLAVOR=ls1021atwr`
4. Create optee_os image with `mkimage -A arm -O linux -C none -a 0xbc000000 -e 0xbc000000 -d tee.bin optee.img`. The tee.bin file is from `optee_os/out/arm/core` folder.
5. After loading each of the component on the u-boot command line to the addresses noted in step 1 I try booting the optee_os. After the optee_os boots it should boot non-secure Linux, right? To boot optee_os I use command: `bootm 0x8300000`

Unfortunately, nothing happens. Although the debug messages are enabled on optee_os make command line I can't see anything printed on the console. What am I doing wrong? Are my load/entry addresses correct?

**Comment by igoropaniuk** [comment]
Hi @nradulovic, 

I could be wrong, but seems you have specified wrong entry point address when running `mkimage` in Step 4. 

OP-TEE binary has a header in the beginning (https://github.com/OP-TEE/optee_os/blob/master/documentation/optee_design.md#partitioning-of-the-binary), which is supposed to be used as a complimentary information for bootloaders, so the entry point should be `${load_addr} + sizeof(struct optee_header)`.

If to follow the article of @MrVan (by the link you provided), entry point address is shifted by 0x1C bytes (= sizeof(struct optee_header)).

I guess proper mkimage invocation should be (I assume that load address you provided is correct):
```
$ mkimage -A arm -O linux -C none -a 0xbc000000 -e 0xbc00001c -d tee.bin optee.img
```

Hope it helps,

BR,
Igor

**Comment by nradulovic** [comment]
Hi @igoropaniuk 

Thanks for replying. You were right, there is a header at beginning of the binary. But, unfortunately still no progress.

I've analysed the documentation and disassembled the `tee.bin`. I have confirmed that the first valid instruction is really at `0x1c` offset. Also, I have confirmed that NX entry address, FDT address and pageable values are really hard-coded into the `tee.bin`.

```
tee.bin:     file format binary


Disassembly of section .data:

00000000 <.data>:
       0:	4554504f 	ldrbmi	r5, [r4, #-79]	; header magic
       4:	00000001 	andeq	r0, r0, r1 ; version, arch, flags
       8:	0003dfe8 	andeq	sp, r3, r8, ror #31 ; init_size
       c:	00000000 	andeq	r0, r0, r0 ; init load high address
      10:	bc000000 	stclt	0, cr0, [r0], {-0} ; init load low address
      14:	0006c000 	andeq	ip, r6, r0 ; memory usage
      18:	00000000 	andeq	r0, r0, r0 ; paged size
; This is the first valid instruction
      1c:	e59f5044 	ldr	r5, [pc, #68]	; 0x68 , hard-coded to 0x80008000
      20:	e3a04000 	mov	r4, #0 ; hard-coded to 0
      24:	e3a06209 	mov	r6, #-1879048192	; hard-coded to 0x90000000
      ...
      68:	80008000 	andhi	r8, r0, r0
```

I have corrected the mkimage command as you said but still nothing, no debug prints on console.

Also, I was using uImage kernel format. I am now loading zImage directly to address 0x80008000, u-boot commands:
 ```
load mmc 0:1 0x80008000 zImage
load mmc 0:1 0x90000000 ls1021a-twr.dtb
load mmc 0:1 0x83000000 optee.img
bootm 0x83000000
```

**Comment by nradulovic** [comment]
I see that this LS1021A-TWR platform is supported. I have the same board.

Maybe I need to configure the PCB switches in some specific way to make optee work?

**Comment by MrVan** [comment]
Try this `bootm 0x83000000 - 0x90000000`?

**Comment by nradulovic** [comment]
Hello,

Thanks for suggestion.

I've tried the alternate bootm format:

```
=> bootm 0x83000000 - 0x90000000
## Booting kernel from Legacy Image at 83000000 ...
   Image Name:   
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    253956 Bytes = 248 KiB
   Load Address: bc000000
   Entry Point:  bc00001c
   Verifying Checksum ... OK
## Flattened Device Tree blob at 90000000
   Booting using the fdt blob at 0x90000000
   Loading Kernel Image ... OK
   Using Device Tree in place at 90000000, end 90006dbc

Starting kernel ...
```

Unfortunately still no output from optee os. 

Can someone, please, provide the details about working combination of u-boot version and optee_os?

**Comment by MrVan** [comment]
Per my knowledge on i.MX op-tee, first build optee os with CFG_CORE_LOG_LEVEL=4, then see if any optee os log output. If still no log, need to use debugger to see where it panic. @b49020 may have some idea on this.

**Comment by b49020** [comment]
@nradulovic, please use attached user guide "ls1021atwr_optee_userguide" for OP-TEE on LS1021A-TWR. Also find attached u-boot and linux patches required as per user-guide.

Please let me know in case you find any issues.

[ls1021atwr_optee_userguide.log](https://github.com/OP-TEE/optee_os/files/1613815/ls1021atwr_optee_userguide.log)
[0001-fsl-ls1021atwr-enable-optee-support-v2017.05.txt](https://github.com/OP-TEE/optee_os/files/1613819/0001-fsl-ls1021atwr-enable-optee-support-v2017.05.txt)
[0002-arm-dt-OP-TEE-for-ls1021a-twr.txt](https://github.com/OP-TEE/optee_os/files/1613820/0002-arm-dt-OP-TEE-for-ls1021a-twr.txt)
[0001-Add-ls1021a_defconfig.txt](https://github.com/OP-TEE/optee_os/files/1613821/0001-Add-ls1021a_defconfig.txt)

**Comment by nradulovic** [comment]
Hello @b49020 ,

Using the guidelines you provided I have succeeded to boot optee os and Linux and get some output on the console. 

Software configuration is the following:
**u-boot** : git://git.denx.de/u-boot.git, tag v2017.05 + patches
**linux** : https://github.com/linaro-swg/linux, v4.12.0 + patches
**optee_os** : tag 2.6.0

NOTE: Your log file was referring to wrong NOR address. The .log file is using 67e20000, but after some searching through u-boot code I saw that the correct address is 63e20000. Please correct the line 36 to:

`tftp 81000000   $path/tee.bin;protect off all ; erase 63e20000 +$filesize ; cp.b 81000000 63e20000 $filesize;`

Now, I have another issues, but at least I have the console working. 

Thanks!

**Comment by b49020** [comment]
@nradulovic , if you read .log file carefully, it says "# Flash u-boot and tee binary from NOR flash bank 0 to bank 1:". So we have to program tee.bin to 67e20000 from bank0 (programming alternate bank). It you program from bank1 (programming current bank) then address is 63e20000. Both these flashing techniques are correct.
