### ISSUE TITLE
What is the root password for the rootfs (linaro-vivid-developer-20151215-114.tar.gz)?

### ISSUE THREAD

**Issue by aim2nasa** [OP-TEE/optee_os#2023]
5.7 Other root filesystems than initramfs based? (https://www.op-tee.org/docs/rpi3/#5-nfs-boot)

According to the above guide, I could successfully boot my raspberrypi with rootfs using linaro-vivid-developer-20151215-114.tar.gz.

Login attempt with user account and password linaro/linaro was successful.
However when I was trying to login as root, I failed though I tried many plausible passwords, something like linaro, optee etc.

What is the root password for this rootfs?

**Comment by jforissier** [comment]
Have you tried `sudo`?

**Comment by vchong** [comment]
Do you meaning logging into the GUI? Try logging in after setting a root password from the terminal using `sudo su` and `passwd` to see if that works?

Fyi you can also try using a newer rootfs from http://releases.linaro.org/debian/images/developer-arm64/latest.

**Comment by aim2nasa** [comment]
I tried root password "sudo" but didn't work.
Thanks for your suggestion though.

**Comment by aim2nasa** [comment]
When I boot using rootfs linaro-vivid-developer-20151215-114.tar.gz, it gives me CUI interface not GUI.
I can log in with linaro / linaro but not with root.

Also I tried to change my root password after login as "linaro" but sudo does not work because "linaro" has no sudo privilege (just like below).

"
linaro@linaro-developer:~$ sudo passwd root
sudo: /usr/bin/sudo must be owned by uio 0 and have the setuid bit set
linaro@linaro-developer:~$
"

So I think I need to know root password as long as I want to use this rootfs.

About the newer rootfs, I'll try. Thanks

**Comment by aim2nasa** [comment]
> Fyi you can also try using a newer rootfs from http://releases.linaro.org/debian/images/developer-arm64/latest.

I tried to boot up using the rootfs mentioned above (linaro-stretch-developer-20171109-88.tar.gz) just replacing rootfs linaro-vivid-developer-20151215-114.tar.gz I had been using.

But the boot up ended up in kernel panic.

![img_3118](https://user-images.githubusercontent.com/26228531/34346522-9faad5f8-ea3b-11e7-9983-11801ab417aa.jpg)

**Comment by aim2nasa** [comment]
Re-tested the above and I found that the above test has a problem.
I made a symbolic link to the rootfs and this was the casuse of the kernel panic.

`ln -s linaro-stretch-developer-20171108 rpi`

After not using symbolic link, I could boot up successfully and more over after I logged in, it was possible to set root password just like @vchong mentioned above.

Though I could not use root acoount with linaro-vivid-developer-20151215-114.tar.gz, it was possible with new rootfs linaro-stretch-developer-20171109-88.tar.gz.

So, I recommend to use linaro-stretch-developer-20171109-88.tar.gz.

![img_3119](https://user-images.githubusercontent.com/26228531/34346859-ac598822-ea3f-11e7-8889-7ca0887b0e68.jpg)

**Comment by vchong** [comment]
Great, thanks for the update! I think you can probably even just login as root (without password) from the very beginning. Also, I think if you want an image with GUI, try http://releases.linaro.org/debian/images/alip-arm64/latest.

**Comment by aim2nasa** [comment]
@vchong Thanks for your GUI rootfs.

I could download the rootfs you mentioned from the above link which was "linaro-jessie-alip-20161214-98.tar.gz" at the time of writing this.

I could boot up and see the GUI it provides but unfortunately keyboard and mouse didn't work at all.
When I investigated a bit, seemed that X configuration for those devices were missing in the file system. 

So I just get back to the CUI rootfs "linaro-stretch-developer-20171109-88.tar.gz" which is working great.

Thank you

**Comment by Marwen10** [comment]
With the two distributions you can login as root without the password with the command:
sudo -s

**Comment by vchong** [comment]
@aim2nasa @Marwen10 Thanks for the update/info!
