### ISSUE TITLE
OP-TEE not booting from SPL when compiled without CFG_DT in i.MX6UL

### ISSUE THREAD

**Issue by kumarabekur** [OP-TEE/optee_os#2024]
Hello There,
I am trying to boot OP-TEE using SPL (Secondary Program Loader - which is supported by community  [U-boot](https://github.com/Freescale/u-boot-fslc) ) . This image by default boots U-boot. The flow for this is SPL -> U-Boot -> OP-TEE -> Linux Now I am trying to have a flow like SPL -> OPTEE -> U-boot -> Linux . In this method, while building OPTEE I'm giving CFG_NS_ENTRY_ADDR as 0x87800000, which is load address of the U-boot. But OP-TEE is booting only when it is built with CFG_DT=y . But I am not expected to load DT because I am loading U-boot from OPTEE. If I build OP-TEE without CFG_DT, OP-TEE doen't boot at all. Is there any dependency in CFG_DT in order to OP-TEE to boot ? Any information about this will be helpful. :) @MrVan @jforissier @jenswi-linaro @igoropaniuk @etienne-lms 
Regards,
Keshava Kumar B

**Comment by igoropaniuk** [comment]
Hi @kumarabekur,

Theoretically it should be possible to boot OP-TEE built with CFG_DT=y from SPL.

Currently, mainline U-boot SPL beside loading legacy U-boot image also supports loading FIT images, so can put U-boot binary, tee.bin and all needed DTBs there (and you can provide all needed load addresses for each blob and appropriate load configuration). 

For example, this is how is done on some Allwinner SoCs based on armv8 (where they put both ATF + U-boot bin into one FIT image, based on configuration ATF is loaded before U-boot)
https://lists.denx.de/pipermail/u-boot/2016-February/245997.html

regarding support of loading FIT images from SPL:
https://lists.denx.de/pipermail/u-boot/2016-February/245997.html

Hope it helps
