### ISSUE TITLE
call TEE API functions in core drivers of OP-TEE

### ISSUE THREAD

**Issue by ranjithvs** [OP-TEE/optee_os#2028]
Dear All,

       I wants to do the signature verification in initialization of the OP-TEE. So I am trying to use TEE_AllocateTransientObject(TEE_TYPE_RSA_PUBLIC_KEY, 2048, &key); in core/arch/arm/kernel/generic_boot.c. I have included proper .h i.e,#include <tee_api.h> in core/arch/arm/kernel/generic_boot.c. Still I cannot use those functions why.?

Best Regards,
Ranjith Hebbar V S

**Comment by vchong** [comment]
The TEE_* functions are GlobalPlatform standard APIs and only available to TAs. You can't call them from optee_os core. TAs and core work on different exception layers.

**Comment by ranjithvs** [comment]
Add on to this, we are trying to do signature verification from OP-TEE to do the next level boot. So planning to override TEE functions (internal libtomcrypto) to make it available for OP-TEE core. So we can use those API's to do the signature verification using RSA and SHA256.

**Comment by jenswi-linaro** [comment]
There's an example of signature verification in `shdr_verify_signature()` (`core/crypto/signed_hdr.c`).
