### ISSUE TITLE
bug: TEE_GetPropertyAsBool(TEE_PROPSET_CURRENT_TA, "gpd.ta.singleInstance", &bool_val)

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#2029]
const struct user_ta_property ta_props[] = {
	{TA_PROP_STR_SINGLE_INSTANCE, USER_TA_PROP_TYPE_BOOL,
	 &(const bool){(TA_FLAGS & TA_FLAG_SINGLE_INSTANCE) != 0}},

In some compile, sizeof(bool) = 1.
In propget_get_ext_prop(), it use sizeof(uint32_t) = 4.
	case USER_TA_PROP_TYPE_BOOL:
		l = sizeof(uint32_t);

so memcpy(buf, ep->value, l) will overflow. 
Then the return value is wrong.

**Comment by jenswi-linaro** [comment]
Yes, you're right. I'll submit a PR.

**Comment by jenswi-linaro** [comment]
Hopefully fixed in https://github.com/OP-TEE/optee_os/pull/2033
Please let me know if it works with your compiler.

**Comment by airbak** [comment]
Thanks for your reply, it is OK.
