### ISSUE TITLE
OPTEE cannot able to boot U-boot in i.MX6UL.

### ISSUE THREAD

**Issue by kumarabekur** [OP-TEE/optee_os#2030]
I am trying to have customized boot flow in i.MX6UL board. I can able to boot OP-TEE from SPL (Secondary Program Loader) code. Now I want to switch to U-boot (U-boot is already loaded to DDR location _0x87800000_. While building OPTEE I have given _CFG_NS_ENTRY_ADDR=0x87800000_. So after OP-TEE is successfully loaded by SPL, I am expecting OP-TEE to jump to U-Boot .  I confirm that U-boot is loaded to DRAM.

But OP-TEE is hanging in 
`DEBUG:   [0x0] TEE-CORE:init_primary_helper:589: Primary CPU switching to normal world boot`

I was expecting OP-TEE would jump to U-boot , just like OP-TEE would jump to Linux in normal . Is there anything I am missing the trick here. 
This is continuation of the query I asked yesterday. I thought it is better to ask as a separate one
#2024 
Any information about this will be a great help in my development. 
@MrVan @jforissier @jenswi-linaro @igoropaniuk @etienne-lms

**Comment by MrVan** [comment]
@kumarabekur  Better to debug this using debugger. We have SPL FIT + TEE on i.MX8, but I did not try using SPL FIT + TEE on i.MX6. I suspect some system registers may not be accessible in non-secure world in uboot. But why not use uboot to directly boot OP-TEE?

**Comment by kumarabekur** [comment]
@MrVan I am developing some secure product where all the secure initializations should be done as soon as possible. So requirement is to boot OP-TEE before other images. So I am trying to boot OP-TEE first then U-boot.

**Comment by MrVan** [comment]
ok. Then you need to use SPL FIT, in the FIT image, you could include tee image and u-boot image. After SPL loaded FIT image, you could use SPL to authenticate the tee and uboot images. When uboot booting kernel, you could uboot to authencitate the kernel image.

**Comment by kumarabekur** [comment]
Thank you  @MrVan . 
I want to what will happen if I dont use `_CFG_NS_ENTRY_ADDR=0x80800000_` while building OPTEE. whether control will go back to SPL. 
In general, If I don't give `_CFG_NS_ENTRY_ADDR=0x80800000_` whether control will go back to the boot loader that booted it?? 
Is there anything I have to change in `core/arch/arm/kernel/generic_entry_a32.S` in-order it to go to bootloader again ??

**Comment by MrVan** [comment]
I think define CFG_NS_ENTRY_ADDR as the uboot entry is needed and simple for your case. Then your boot flow will be SPL->TEE->U-boot. To be honest, I did not try this. But I think it should work.

**Comment by kumarabekur** [comment]
Even I was thinking same. I thought just giving CFG_NS_ENTRY_ADDR as Uboot entry point(0x87800000) will jump to Uboot directly. But this is not the case. It hangs where it is supposed to jump to Uboot:
```

DEBUG:   [0x0] TEE-CORE:init_primary_helper:588: ********nsec_entry = 0x87800000
DEBUG:   [0x0] TEE-CORE:init_primary_helper:589: ********dtb_entry = 0x83000000
DEBUG:   [0x0] TEE-CORE:init_primary_helper:590: Primary CPU switching to normal world boot
```
For experimentation, I even tried following SPL->TEE->Linux. Even in this case, switching to Linux hangs in same place.

**Comment by MrVan** [comment]
For SPL->TEE->Uboot/Linux, you need a debugger to see where it stops. Currently I think there might be issues in i.mx uboot running in non-secure world, such as L2cache and some cp15 registers, you need use a debugger to debug.  For TEE->Linux, you need to enable earlyprintk and lowlevel debug to see where it hangs, also you may give a try to disable L2 in linux first.

**Comment by SimoneBongini** [comment]
@kumarabekur, are you able to resolve it?
