### ISSUE TITLE
data lost when data corrupt

### ISSUE THREAD

**Issue by zhupg** [OP-TEE/optee_os#2031]
Dear,
    As the data in tee file system is important generally, some of the data only can be written in factory production, so it is not acceptable that data lost if there is a error(TEE_ERROR_CORRUPT_OBJECT) occur(eg. software bug or attack).
    In consideration of seperation of mechanism and policy, it is better that operation system provide mechanism, and application provide policy. To this, OPTEE OS provides API to remove data, and application decides to whether delete data if there is error.
    In addition, it is not convenient to debug if data lost. Otherwise we can analysis data if data exist.
    Could you consider to not delete corrupt data?

**Comment by jenswi-linaro** [comment]
Deleting the corrupt files is required by the GP specification. If you can find a way of still being GP compliant we'll look at the patch. I can't promise anything a this stage though.

**Comment by zhupg** [comment]
Sorry that I didn't know it is required by GP, I have checked the specification, seems no good way to compliant GP and don't remove file.
