### ISSUE TITLE
query: question about TA2TA interface

### ISSUE THREAD

**Issue by gchww** [OP-TEE/optee_os#2032]
# background
I got some information form [https://www.optee.org/faq/#8-trusted-applications](https://www.optee.org/faq/#8-trusted-applications)
8. Trusted Applications->Is multi-threading supported in a TA?
there are lines

> "If you need to run tasks in parallel, then you should probably look into running two TAs or more simultaneously and then let them communicate with each other using the TA2TA interface."

# my questions are

1. I found no information of  TA2TA interface whether from gp internal api specification or the optee-os code. can you offer me more information about  the interface? 
2. TA running originates from CA running and loading, how to ensure that when TA _a_ calls service from TA _b_, TA _b_ is ready before ta _a_ calling?
3. TAs running in independent thread, are there any IPCs between them?
 
thanks

**Comment by vchong** [comment]
1. Section 4.9 Internal Client API
2. TA b running can originate from TA a, e.g. `TEE_OpenTASession`.
3. You can use the Internal Client API.

**Comment by gchww** [comment]
Thanks for your prompt reply.
