### ISSUE TITLE
SHA256hash of the kernel image in op-tee

### ISSUE THREAD

**Issue by ranjithvs** [OP-TEE/optee_os#2037]
Hi all,

      I am trying to get the sha256 hashing of the kernel image in op-tee core.
I am doing following steps but I am not getting the expected result. Can anyone please help me out to resolve.?
` hash_state hs;
    uint8_t digest[TEE_SHA256_HASH_SIZE];
    uint8_t i;
    uint32_t base;
    base = core_mmu_get_va(0x80800000, MEM_AREA_IO_SEC);
    sha256_init(&hs);
    sha256_process(&hs, (unsigned char *) base, 6735080); //6735080 size of the zImage binary
    sha256_done(&hs, digest);
    for( i=0;i< TEE_SHA256_HASH_SIZE; i++)
     {
       MSG("Buffer:%x\n",digest[i]);
    }`

Best Regards
Ranjith Hebbar

**Comment by jenswi-linaro** [comment]
Which platform are you trying this on? How can you know that the kernel is at this particular address? What seems to be the problem?
