### ISSUE TITLE
Why OP-TEE uses fixed Level 2 (L2) page table for thread

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#2038]
Hi everyone,

I see that OP-TEE fixes the size of  L2 page tables for thread: every thread is reserved 2 page tables, see the codes below. This setting would fix the size of virtual address space for threads, which would limit the size of TA. Why we don't allow dynamic allocation of L2 page tables for threads?

```
static struct pgt_parent pgt_parents[PGT_CACHE_SIZE / PGT_NUM_PGT_PER_PAGE];
/*
 * Reserve 2 page tables per thread, but at least 4 page tables in total
 */
#if CFG_NUM_THREADS < 2
#define PGT_CACHE_SIZE	4
#else
#define PGT_CACHE_SIZE	ROUNDUP(CFG_NUM_THREADS * 2, PGT_NUM_PGT_PER_PAGE)
#endif
```

**Comment by jenswi-linaro** [comment]
The page tables needs to be 1KiB or 4KiB aligned so we can't just allocate them with malloc.

**Comment by TEE-OS** [comment]
Thanks.
