### ISSUE TITLE
What does the AREA_TYPE_LOCK type area used for

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#2039]
Hi everyone,
I see that pager defines 3 types for protected area: RO, RW, LOCK. What's the type of LOCK used for?

```
enum area_type {
	AREA_TYPE_RO,
	AREA_TYPE_RW,
	AREA_TYPE_LOCK,
};

```

**Comment by jenswi-linaro** [comment]
`AREA_TYPE_LOCK` is used when a page needs to kept mapped until unmapped specifically. That's how the thread stacks are allocated for instance.

**Comment by TEE-OS** [comment]
Thanks.
