### ISSUE TITLE
OP-TEE not working on ARM Juno with Android.

### ISSUE THREAD

**Issue by hwithaar** [OP-TEE/optee_os#204]
I have been able to get the OP-TEE working on the Juno armv8 board for Linux.
I did build the OP-TEE parts under Android but get the following:
1: Loading kernel drivers goes ok.
2: Running tee_supplicant gives [ 1935.764795] armv7sec armv7sec.0: tee_supp_read: ERROR     
    Supplicant application NOT ready.
We use the same TFW images including the op-tee as BL32 as we did for Linux.

Does anyone has this working and could give me some hints?

**Comment by jbech-linaro** [comment]
Hi hwithaar,

Have you noticed that we recently merged a re-worked kernel driver? This merge contains major changes. I encourage that you make sure all three git's has been updated since there are inter-dependencies between the gits.

// Joakim

**Comment by hwithaar** [comment]
Hi Joakim,
Thanks for the update. I will build all with latest gits and post the results.

**Comment by hwithaar** [comment]
The problem of the supplicant error is resolved.
It was the name of the supplicant which must be tee-supplicant.
The Android makefile created a file name tee_supplicant.
