### ISSUE TITLE
Why udelay implementation does not rely on tee_time_get_sys_time() ?

### ISSUE THREAD

**Issue by b-allibert** [OP-TEE/optee_os#2040]
Hi everyone,

Looking at udelay() implementation ([core/arch/arm/kernel/delay.c](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/delay.c)) i'm wondering why it does not simply rely on tee_time_get_sys_time() ?
Actually, i'm looking at this because this code assumes ARM CNTPCT is present, which is true on ARMvx-A platforms but may not be for all ARM platforms.

```
void udelay(uint32_t us)
{
	uint64_t start, target;

	start = read_cntpct();
	target = read_cntfrq() / 1000000ULL * us;

	while (read_cntpct() - start <= target)
		;
}
```

**Comment by jenswi-linaro** [comment]
`udelay()` is mostly used when RPC is not possible.

**Comment by b-allibert** [comment]
OK, thanks for the clarification ; i thought only CNTPCT was registered as time_source, and did not realize that ree_time was too, my mistake. Sounds clear now.

However, how can that work on platforms that are not supporting CNTPCT then ? we might have a add some code here, right ? at least a way to discard hat `udelay()` call without going to the CNTPCT accesses... as far as i understand, we may come to a situation where `CFG_SECURE_TIME_SOURCE_CNTPCT` is set to `'n'` but `udelay()` still relies on it.

Please correct me if i'm wrong, thanks.

**Comment by jenswi-linaro** [comment]
Something will have to be done then.
