### ISSUE TITLE
How to port OP-TEE to ZCU102?

### ISSUE THREAD

**Issue by xyzheng010** [OP-TEE/optee_os#2041]
I'm trying to port OP-TEE to zcu102 and I would like to acquire some technical support. The newest version of OP-TEE if it supports the development board, I noticed that it is maintained by  v2.4.0. I must execute what instructions for  running OP-TEE on zcu102 and It will be better that I should git clone which version of OP-TEE to transplant. Thank you!

**Comment by duclongpl** [comment]
Hi @xyzheng010,

I deployed OP-TEE successful on zcu102 three months ago.
Which version that I used is:
+ optee-client version 2.5.0
+ optee-OS version 2.5.0
+ arm-trusted-firmware version v2017.1
So which step you got stuck ?

**Comment by xyzheng010** [comment]
Have you any other contact information?  WeChat、QQ and at ac. Can you speack chinese?  Thank you!

**Comment by mye-rutgers** [comment]
Hi @duclongpl,

May I know which Linux platform you used for the OPTEE deployment on ZCU102? Thank you!

Best Regards,
Mengmei

**Comment by Darshan1661** [comment]
i run out The package 2021.1-zcu102-release.tar.xz is a prebuilt board support package (BSP) from Xilinx that contains firmware and configuration files required to boot the ZCU102 Zynq UltraScale+ MPSoC board with OP-TEE
