### ISSUE TITLE
why does the waiter completion work ?

### ISSUE THREAD

**Issue by Cuixiaoxia198106** [OP-TEE/optee_os#2042]
Hi:
For the following function, if TEE is busy, optee will implement optee_cq_wait_for_completion to wait . 
but the w is local variable, each thread has own w to deal with.  therefor, how does the current thread block after execute  wait_for_completion(&w->c); in optee_cq_wait_for_completion ?

void optee_enable_shm_cache(struct optee *optee)
{
	struct optee_call_waiter w;

	/* We need to retry until secure world isn't busy. */
	optee_cq_wait_init(&optee->call_queue, &w);
	while (true) {
		struct arm_smccc_res res;

		optee->invoke_fn(OPTEE_SMC_ENABLE_SHM_CACHE, 0, 0, 0, 0, 0, 0,
				 0, &res);
		if (res.a0 == OPTEE_SMC_RETURN_OK)
			break;
		optee_cq_wait_for_completion(&optee->call_queue, &w);
	}
	optee_cq_wait_final(&optee->call_queue, &w);
}

**Comment by jenswi-linaro** [comment]
The comments in `optee_cq_wait_init()` and `optee_cq_wait_final()` describes what's going on. Did you read them?

**Comment by Cuixiaoxia198106** [comment]
sure... I read them.
but the "struct optee_call_waiter *w;" is local variable in function, I do not know how does other threads wait for it ?  what I understand is each threads has own stack to allocate W , so different thread does not block same W impossibly

**Comment by jenswi-linaro** [comment]
This local variable is registered in a linked list to allow other threads to find it when completing.

**Comment by Cuixiaoxia198106** [comment]
that's happen in optee_cq_wait_final functions.. 
what I want to know if current thread will block in wait_for_completion(&w->c);
