### ISSUE TITLE
build optee_os error

### ISSUE THREAD

**Issue by bryan370210** [OP-TEE/optee_os#2044]
Hi, I follwed the steps https://github.com/OP-TEE/optee_os/blob/master/documentation/build_system.md
       
     $ export PLATFORM=hikey
     $ make CFG_ARM64_core=y

errors:

make -C /home/optee2/build/../optee_os O=out/arm CROSS_COMPILE=" /home/optee2/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CROSS_COMPILE_core=" /home/optee2/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CROSS_COMPILE_ta_arm64=/home/optee2/build/../toolchains/aarch64/bin/aarch64-linux-gnu- CROSS_COMPILE_ta_arm32=/home/optee2/build/../toolchains/aarch32/bin/arm-linux-gnueabihf- CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=1 CFG_TEE_BENCHMARK=n PLATFORM=vexpress-qemu_virt
make[1]: Entering directory '/home/optee2/optee_os'
core/arch/arm/cpu/cortex-a15.mk:2: ******* CFG_ARM64_core is set to 'y' (from command line) but its value must be 'n'。**
make[1]: Leaving directory '/home/optee2/optee_os'
common.mk:300: recipe for target 'optee-os-common' failed**
make: *** [optee-os-common] Error 2

**Comment by jenswi-linaro** [comment]
`PLATFORM=vexpress-qemu_virt` doesn't support `CFG_ARM64_core=y`

**Comment by vchong** [comment]
@bryan370210 Looks like you might be mixing the instructions in https://github.com/OP-TEE/optee_os/blob/master/documentation/build_system.md (which works when run under the `optee_os` dir btw, and builds the binary for `optee_os` only) with https://github.com/OP-TEE/build (in which case you shouldn't just run `make CFG_ARM64_core=y`). For https://github.com/OP-TEE/build (which builds a full set of working images, not just the `optee_os` binary) for hikey, follow the instructions in https://github.com/OP-TEE/build/blob/master/docs/hikey.md.

**Comment by bryan370210** [comment]
@jenswi-linaro @vchong  thanks
