### ISSUE TITLE
Whether opteeos must work with ATF?

### ISSUE THREAD

**Issue by lchina77** [OP-TEE/optee_os#205]
Hi everyone,
    I want to make optee work on our  CA9*4 SoC  by referring to the codes for plat-stm.
But I find that some SMC requests  sent by the opteeos , such as TEESMC_OPTEED_RETURN_ENTRY_DONE ,  are not responded to by the opteeos self, but are dealt with in the ATF codes.

 To my knowledge , the ATF only work on ARM-v8.
 Is it correct?  
 If yes, how the opteeos work on ARM-v7 without the ATF? 
Do we need to write our own monitor codes to respond to the opteeos SMC requests?

Best Regards.

**Comment by jenswi-linaro** [comment]
On ARM-v7 OP-TEE OS has an integrated secure monitor (corresponding to Dispatcher in ARM-TF).

Please have a look in core/arch/arm32/sm/sm.c and core/arch/arm32/sm/sm_asm.S.

The SMC requests from secure world to the monitor are more like a way of returning to the monitor and telling why it returned. In v7 case are the values only used to distinguish between return from FIQ and other returns.

**Comment by lchina77** [comment]
Thanks a lot.
