### ISSUE TITLE
Enabling IMA in kernel

### ISSUE THREAD

**Issue by nutim** [OP-TEE/optee_os#2053]
Hi,
I installed optee on Raspberry pi 3. I tested all regression tests as mentioned in procedure using `xtest`. Everything is perfectly working. 

I just want to to know if I can enable IMA (Integrity Measurements architecture) in kernel. As per my knowledge optee-os uses its own kernel, if I compile new kernel it might not work. I have to use globalplatform too, so installing new kernel is not solution. could anyone please let me know if there are any alternatives to it. 

Thanks

Mallik

**Comment by vchong** [comment]
The rpi3 kernel source is https://github.com/linaro-swg/linux/commits/rpi3-optee-4.6. You can enable IMA and rebuild it. Or you can also try porting the op-tee patches to whatever kernel you're using - commits cd24a2e8f4da80bfbebd45a846ad5c067dbcd3e8 to 7d976fc52ae3f04618062967948e626166f1904a.

**Comment by nutim** [comment]
Thanks for the response.
