### ISSUE TITLE
Is the OP-TEE memory space limited in 4GB?

### ISSUE THREAD

**Issue by davidhuziji** [OP-TEE/optee_os#2056]
Hi,

I saw such a piece of code in optee_test repo.
```
/* pointers in 32-bit fields passed as an offset to ta_head */
extern const void *ta_head;
#define VAL2HANDLE(v) (void *)(uintptr_t)(v == TEE_HANDLE_NULL ? v : v + (uintptr_t)&ta_head)
#define HANDLE2VAL(h) (uint32_t)(h == TEE_HANDLE_NULL ? (uintptr_t)h : (uintptr_t)((uintptr_t)h - (uintptr_t)&ta_head))
```
As the above code shows, the pointers generated in secure world can be represented as a 32-bit offset to ta_head. It might imply that the available memory space for OP-TEE will be limited in 4GB. Is it correct?
Is it possible that the offset between pointers and ta_head in secure world exceeds 32 bits, for example in AArch64?

BTW, I'd like to know how much memory OP-TEE can use to allocate objects in TA/secure world?

Thank you in advance.

**Comment by jenswi-linaro** [comment]
Our largest test TAs currently allocates ~2MiB. Larger TAs will probably work, but as they are scaled up we'll run into different limits. With pager disabled the first limit will likely be the number of translation tables required. With pager enabled we'll probably run out of core heap first. So far the focus at least from my part has been more on scaling down than scaling up.

**Comment by davidhuziji** [comment]
Hi @jenswi-linaro,

Thank you.
Can I make a conclusion that _in short term_, OP-TEE OS can only deal with memory space less than 4GB?

**Comment by jenswi-linaro** [comment]
That's the current status, yes.

**Comment by davidhuziji** [comment]
Got it. Thank you @jenswi-linaro!
