### ISSUE TITLE
OP-TEE crypto implementation with pre-build OBJ

### ISSUE THREAD

**Issue by rangewang** [OP-TEE/optee_os#2057]
Hi all,
In the [documentation](https://github.com/OP-TEE/optee_os/blob/master/documentation/crypto.md) OP-TEE crypto implementation mention that :
_To add a new implementation, the default one in core/lib/libtomcrypt in ......_

But I'm no sure is possible to add new implement with pre-build format, like a object file(ex: crypto_xxx.o) as crypto implementation.
It just provide a header file as API to use. 

If it possible, how should I add OBJ path to the compiler ?

**Comment by jenswi-linaro** [comment]
I'd recommend compiling the crypto lib from source because it's important the compiler flags matches in all object files.

**Comment by rangewang** [comment]
@jenswi-linaro I don't have a source code that provide by vendor, but I don't find anyone else do that like me using the obj file as a crypto implement.
