### ISSUE TITLE
question about dynamic shmem

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#2069]
Hi,

I am looking into the dynamic shmem part. Just have a question, if no early ta, could the static configured CFG_SHMEM_START/SIZE be removed if dynamic shmem enabled? 

From optee driver probe, optee_config_shm_memremap will check OPTEE_SMC_GET_SHM_CONFIG, so CFG_SHMEM_START/END still needs to be defined in optee os.

Another point, could you help clarify priv_mgr and dmabuf_mgr? From driver code, when TEE_SHM_DMA_BUF set, the dmabuf_mgr will be used, and I only see TEE_IOC_SHM_ALLOC will use that flag.  But from tee-supplicant side, process_alloc will use register_local_shm or alloc_shm. If dynamic shm used, register_local_shm will used. So alloc_shm will have no chance to run.
Then if dynamic shm enabled, dmabuf_mgr will never be used, right? From kernel comment "pool manager for shared memory exported to user space" is for dmabuf_mgr. So I do not understand, when dmabuf_mgr will be used?
@jenswi-linaro @lorc Could you help answer?

Thanks.

**Comment by lorc** [comment]
Hi @MrVan,

Static configuration is needed for backwards compatibility. Thus, we still define `CFG_SHMEM_START`. 

Kernel driver can be patched to work without static mem at all (and it should be done to support virtualization)

The same applies for supplicant. Technically you can use new dynamic shm-capable supplicant with old OP-TEE that knows only about static SHM (or new OP-TEE does not know about physical DRAM mappings, so it falls back to static SHM). In those cases `alloc_shm` will be used, and this is why we hold `dmabuf_mgr` in linux driver.

**Comment by MrVan** [comment]
@Iorc Thanks for explaination. But from drivers/tee/optee/core.c, optee_config_shm_memremap could use OPTEE_SMC_SEC_CAP_DYNAMIC_SHM as a check condition to invoke `OPTEE_SMC_GET_SHM_CONFIG`, right? There is no reason to invoke `OPTEE_SMC_GET_SHM_CONFIG` for dynamic shm enabled optee os, I think. Another point is static shm kept for dynamic shm enabled system, is for early ta?

**Comment by etienne-lms** [comment]
Early tas do not necessarily need static shm.

I think the driver should always query the static shm but should not fail on `NOT_IMPLEMENTED` or `NOT_SUPPORTED`. There would be no registered `dma_buf_mgr` pool, [tee_shm.c/__tee_shm_alloc()](https://github.com/linaro-swg/linux/blob/6e954e2f2cbd412f7bc874bb9145f69713194e52/drivers/tee/tee_shm.c#L178) could nicely fail if so.
If the secure side does not support dyn shm, there would be no `private_mgr` pool neither. I guess optee driver should complain if it does not get at least a valid private pool manager.
