### ISSUE TITLE
Apt-get not found 

### ISSUE THREAD

**Issue by Christian56** [OP-TEE/optee_os#2075]
Hi,

I am trying to run OPTEE on Raspberry Pi 3.. I am able to get to the shell following the https://github.com/OP-TEE/build and can execute xtest. 
However I got the problem that the *apt-get* command is not found, when i try to install **atftpd** in order to boot via NFS and TFTP. So I'm not sure how to proceed

Best Regards,
Chris

**Comment by igoropaniuk** [comment]
Hi @Christian56,

you should install FTP server(for instance, *atftpd*) on your PC/some server etc, but not on RPi3 itself.

BR,
Igor
