### ISSUE TITLE
QEMU v7 build fails with "Error: invalid constant (c08) after fixup"

### ISSUE THREAD

**Issue by lorc** [OP-TEE/optee_os#2076]
I tried clean qemu_v7 build with instructions from https://github.com/OP-TEE/build.
OP-TEE build fails with the following  error:

>   AS      out/arm/core/arch/arm/sm/sm_a32.o
> core/arch/arm/sm/sm_a32.S: Assembler messages:
> core/arch/arm/sm/sm_a32.S:354: Error: invalid constant (c08) after fixup
> core/arch/arm/sm/sm_a32.S:356: Error: invalid constant (c09) after fixup
> core/arch/arm/sm/sm_a32.S:358: Error: invalid constant (c0e) after fixup
> core/arch/arm/sm/sm_a32.S:363: Error: invalid constant (c0f) after fixup
> mk/compile.mk:146: recipe for target 'out/arm/core/arch/arm/sm/sm_a32.o' failed

This is clearly caused by 
```
	mov	r3, #CORTEX_A8_PART_NUM
	cmp	r2, r3
	movne	r3, #CORTEX_A9_PART_NUM
	cmpne	r2, r3
	movne	r3, #CORTEX_A17_PART_NUM
	cmpne	r2, r3

```

Looks like assembler can't generate valid `mov` instructions with this large immediate values.

**Comment by jenswi-linaro** [comment]
Out of curiosity, which compiler are you using?

**Comment by lorc** [comment]
One that was shipped with `make toolchains`:

```
lorc:build/ (eed6aa9) $ make toolchains                                                                                                                                                                 [19:37:22]
Downloading gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf ...
Downloading gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu ...
Downloading gcc-linaro-aarch64-linux-gnu-4.9-2014.08_linux ...
make toolchains  18,18s user 4,24s system 10% cpu 3:24,92 total

```


```
lorc:build/ (eed6aa9) $ /home/lorc/mnt/ssd/optee_test/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-gcc  --version                                                                                [19:46:47]
arm-linux-gnueabihf-gcc (Linaro GCC 6.2-2016.11) 6.2.1 20161016
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by jenswi-linaro** [comment]
Fix in https://github.com/OP-TEE/optee_os/pull/2077

**Comment by lorc** [comment]
Replaced `mov` with `ldr` and it compiles now.

Should I push the patch?

**Comment by jenswi-linaro** [comment]
I've created a PR.

**Comment by lorc** [comment]
#2077 fixes the issue, so I'm closing it.
Thanks.
