### ISSUE TITLE
Android + OP-TEE on imx6Q sabre SD Board

### ISSUE THREAD

**Issue by jenkin233** [OP-TEE/optee_os#2078]
Hi,all
 I am new to port OP-TEE to i.mx6Q Sabre SD board. Now I want to build android + OP-TEE on my i.mx6q Sabre SD board ,where can I get help? 
Thanks,

**Comment by vchong** [comment]
Is there already an android build (without OP-TEE) for the board? I don't see it in google's repos.

**Comment by vchong** [comment]
Looks like maybe the source code is not upstream. There's a link to N source code @ https://www.nxp.com/support/developer-resources/run-time-software/i.mx-developer-resources/i.mx-6-i.mx-7-i.mx-8-series-software-and-development-tool-resources:IMX_SW but requires a login to access.

In any case, if you have access to the source code, you need to do something like [1] to `device/freescale/<path to i.mx6Q Sabre SD dir>`. However, please note that the patches in [1] are specific to hikey board and don't apply exactly to your board! You can only use it as a reference and make appropriate changes for your board. If not familiar with all the build systems involved, the learning curve can be a bit high.

As a side note, if approved, we plan to have a session on porting op-tee to hikey aosp at the next Linaro Connect at Hong Kong from Mar 19-23 [2], where some of the patches in [1] will be explained in a bit more detail, so it might be helpful if you can attend, or read/watch the slides/videos afterwards.

[1] https://github.com/vchong/device-linaro-hikey/compare/gmaster3...hikey-n-4.9
[2] http://connect.linaro.org
