### ISSUE TITLE
possibly dead lock

### ISSUE THREAD

**Issue by zhizhouzh** [OP-TEE/optee_os#2080]
Hi experts,

I met a dead lock issue, the log is shown as below:

> D/TC:1 pgt_alloc:527 Waiting for page tables
> D/TC:1 __wq_rpc:38 sleep thread 1 0x100069158 -2 core/arch/arm/mm/pgt_cache.c:529
> D/TC:0 __wq_rpc:38 sleep thread 0 0x1000695a8 1 core/kernel/tee_ta_manager.c:216
> D/TC:2 tee_ta_close_session:403 tee_ta_close_session(0x8fb40)
> D/TC:2 __wq_rpc:38 sleep thread 2 0x1000695a8 1 core/kernel/tee_ta_manager.c:216

It seems, one thread holds `&tee_ta_mutex` and tries to seize `&pgt_mu` by `condvar_wait(&pgt_cv, &pgt_mu);`. It's probably because of there is no enough pgt_cache entries, then this thread hangs itself to wait other thread to exit and to free pgt.

But on the other side, the other thread is waiting for `&tee_ta_mutex` in `tee_ta_close_session()`. But this lock is seized by the first thread. So this thread is not able to free pgt. Finally results dead lock.

Could anyone help to confirm it? Thanks!

**Comment by jenswi-linaro** [comment]
Thanks @zhizhouzh, your analysis is correct as far as I can tell. I'll try to fix this.

**Comment by jenswi-linaro** [comment]
Please test https://github.com/OP-TEE/optee_os/pull/2083 and tell if it fixes the deadlock.

**Comment by zhizhouzh** [comment]
Thanks, This issue does not reproduce any more with this patchset.

**Comment by jforissier** [comment]
Re-opening since the fix (https://github.com/OP-TEE/optee_os/pull/2083) causes stability issues, and was reverted (https://github.com/OP-TEE/optee_os/pull/2103).

**Comment by jenswi-linaro** [comment]
Unfortunately no.
