### ISSUE TITLE
Prime and generator values of DH key in TEE_DeriveKey()

### ISSUE THREAD

**Issue by davidhuziji** [OP-TEE/optee_os#2084]
Hi,

I'm trying to call `TEE_DeriveKey()` to generate a Diffie-Hellman key SharedSecret.
But I'm a little confused. Could you please tell me how to determine the the prime (_**p**_) and  generator (_**g**_) values in `TEE_DeriveKey()`?

During DH key pair generation in `TEE_GenerateKey()`, it is required to provide the _**p**_ and _**g**_ values. Thus I guess there is no built-in _**p**_ or _**g**_ inside OP-TEE OS.
As a result, how to make sure the both sides use the same set of _**p**_,  _**g**_?

Thank you.

**Comment by vchong** [comment]
You can see https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000_data.h#L4953-L4955 as an example.

**Comment by davidhuziji** [comment]
Hi @vchong , I'm sorry I cannot get your point.

But I find an example of TEE_DeriveKey() in optee_test [](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000.c#L4743).

In my very own understanding based on the above example, the process should be:
1. Allocate the derive operation _**op**_..
2. Set _**key**_ into _**op**_ by `TEE_SetOperationKey()`. The _**key**_ should contain information of _**p**_, _**g**_, local _**priv_key**_ and local _**pub_key**_.
3. Allocate another transient object handle _**sv**_ in type **TEE_TYPE_GENERIC_SECRET**.
4. Call `TEE_DeriveKey()` with _**op**_, _**sv**_ and remote _**pub_key**_ to derive the sharedsecret.

Is it correct?
Thank you.

**Comment by vchong** [comment]
Sorry. I thought you were asking how to generate `p` and `g`.
According to the GP spec, you don't need `p` and `g` in `TEE_DeriveKey()`, just the remote public key, as you've seen in the example. The process looks ok. Basically you can just follow the flow in test 4008 example you found above.

**Comment by davidhuziji** [comment]
Hi @vchong. It sounds strange to me. If the `p` and `g` is not provided, how can OP-TEE OS check if remote public key and local private key are generated based on the same `p` and `g`?
So does it imply that it should be guaranteed by TA caller and OP-TEE doesn't check it at all?

**Comment by vchong** [comment]
I mean you don't need to supply them explicitly as they're part of `params`.

**Comment by davidhuziji** [comment]
Sorry. Whose `params`?
I'd like to know, if I don't need to explicitly set them, where does `TEE_DeriveKey()` intend to get `p` and `g`?

**Comment by vchong** [comment]
See `derive_key_dh_prime` (`p`) and `derive_key_dh_base` (`g`) in https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000.c#L4774-L4778 and https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000_data.h#L5903-L5921.

**Comment by davidhuziji** [comment]
In the last links, the `p` and `g` are actually **_explicitly_** set into a TEE transient object handle. ;)

Furthermore, according to GP TEE internal API spec, the DH key pair object generated by `TEE_GenerateKey()` might not contain the `TEE_ATTR_DH_PRIME` or `TEE_ATTR_DH_BASE`. Thus I guess maybe it is better to explicitly set the `p` and `g` _explicitly_ for `TEE_DeriveKey()`.
Please correct me if I misunderstood you.

**Comment by vchong** [comment]
Right, so you don't have to set them again in `TEE_DeriveKey()`. The attributes are set as well in lines 4774-4778. These APIs are standard so we can't change them as we wish. It'll break compatibility for everyone else.

**Comment by davidhuziji** [comment]
Got it. Thank you @vchong so much.
Thanks a lot for your patience.

**Comment by vchong** [comment]
No problem. Good luck.
