### ISSUE TITLE
i.MX6 not booting with CFG_TEE_CORE_DEBUG

### ISSUE THREAD

**Issue by mbriand** [OP-TEE/optee_os#2087]
Hi,

I'm having issues booting boards based on i.MX6 SoCs  when CFG_TEE_CORE_DEBUG is enabled, since commit f2f36ec180c5.
                                                
The problem comes from plat_cpu_reset_late() function in core/arch/arm/plat-imx/imx6.c file, where we make a call to virt_to_phys(). I'm not sure this is a legit call as plat_cpu_reset_late() function is called before MMU initialization and so before the memory mappings are correctly setup.

https://github.com/OP-TEE/optee_os/blob/a83aec29b778db0b01b3e74ff69122f930bed050/core/arch/arm/plat-imx/imx6.c#L51

When CFG_TEE_CORE_DEBUG is not set, the call to virt_to_phys() still succeeds, as arm_va2pa_helper() still gives the correct value and check_va_matches_pa() doesn't do anything. But when CFG_TEE_CORE_DEBUG is set, check_va_matches_pa() triggers a panic, as no correct memory mapping is set (yet).

https://github.com/OP-TEE/optee_os/blob/a83aec29b778db0b01b3e74ff69122f930bed050/core/arch/arm/mm/core_mmu.c#L1632
                                                                        
I'm not sure what would be a good approach to fix this. I'm not even sure this does not come from me doing something wrong, as this change is four months old and I have not seen anyone with similar troubles. Maybe @mrvan or @yanyan-wrs have some thought to share ?

**Comment by leesagacious** [comment]
may be a problem with mmu .
