### ISSUE TITLE
Memory leak  in OP-TEE

### ISSUE THREAD

**Issue by lorc** [OP-TEE/optee_os#2095]
During testing 3.0.0-rc2 I observed memory leak on RCAR M3 and on QEMU V8.
There is test setup for QEMU V8:

optee_os: e9596d0 built with `CFG_WITH_STATS=y`
optee_client: 09b69af
optee_test: 692efd1
linux: 6e954e2
manifest:  4daa68044, qemu_v8.xml

Test invocation: `while xtest; do /mnt/tee-stats/out/tee-stats >> stats.txt; done;`
On fourth iteration xtest failed on test 6010:

> regression_6010.2.6 FAILED first error at /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:1314
> regression_6010.2.7 FAILED first error at /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:1327
> regression_6010.2.8 FAILED first error at /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:1334
> regression_6010.2.9 FAILED first error at /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:1349
> regression_6010.2.10 FAILED first error at /home/lorc/work/tee_dev/optee_test/host/xtest/regression_6000.c:1356
> regression_6010.2 FAILED
> regression_6010 FAILED
> 

Contents of `stats.txt`:

> HEAP: heap_size 66512 cur_alloc 8128 max_alloc 35936 fail 1 biggest_fail_size 268435456 biggest_fail_used 4992
> HEAP: heap_size 66512 cur_alloc 10432 max_alloc 41776 fail 2 biggest_fail_size 268435456 biggest_fail_used 4992
> HEAP: heap_size 66512 cur_alloc 12736 max_alloc 44016 fail 3 biggest_fail_size 268435456 biggest_fail_used 4992

Looks like 2304 bytes are leaked at every iteration.

**Comment by lorc** [comment]
Looks like test 1008 causes this leak.
Result of `while xtest 1008; do /mnt/tee-stats/out/tee-stats >> stats.txt; done;`:

>   regression_1008.3 OK
> o regression_1008.4 Load corrupt TA
> /home/lorc/work/tee_dev/optee_test/host/xtest/regression_1000.c:667: res has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0xffff000f = TEEC_ERROR_SECURITY
> /home/lorc/work/tee_dev/optee_test/host/xtest/regression_1000.c:749: load_corrupt_ta(c, __builtin_offsetof (struct shdr, img_size), 1) has an unexpected value: 0x0 = false, expected 0x1 = true
> /home/lorc/work/tee_dev/optee_test/host/xtest/regression_1000.c:667: res has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0xffff000f = TEEC_ERROR_SECURITY
> /home/lorc/work/tee_dev/optee_test/host/xtest/regression_1000.c:760: load_corrupt_ta(c, 3000, 1) has an unexpected value: 0x0 = false, expected 0x1 = true
> /home/lorc/work/tee_dev/optee_test/host/xtest/regression_1000.c:667: res has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0xffff000f = TEEC_ERROR_SECURITY
> /home/lorc/work/tee_dev/optee_test/host/xtest/regression_1000.c:761: load_corrupt_ta(c, 30000, 1) has an unexpected value: 0x0 = false, expected 0x1 = true
>   regression_1008.4 FAILED
>   regression_1008 FAILED

Contents of stats.txt:

> HEAP: heap_size 66512 cur_alloc 4320 max_alloc 15680 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 6624 max_alloc 15808 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 8928 max_alloc 18112 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 11232 max_alloc 20416 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 13552 max_alloc 22720 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 15856 max_alloc 25024 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 18160 max_alloc 27328 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 20480 max_alloc 29680 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 22752 max_alloc 31936 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 25088 max_alloc 34272 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 27392 max_alloc 36576 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 29696 max_alloc 38880 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 32032 max_alloc 41216 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 34304 max_alloc 43520 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 36608 max_alloc 45840 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 38944 max_alloc 48128 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 41312 max_alloc 50512 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 43616 max_alloc 52800 fail 0 biggest_fail_size 0 biggest_fail_used 0
> HEAP: heap_size 66512 cur_alloc 45952 max_alloc 55232 fail 0 biggest_fail_size 0 biggest_fail_used 0
>

**Comment by lorc** [comment]
I moved subcase 1008.4 "Load corrupt TA" into separate test and I can confirm, that it causes memory leak.

**Comment by lorc** [comment]
Looks like #2096 should fix the issue.

**Comment by jforissier** [comment]
@lorc thanks for taking the time to investigate this :+1:

**Comment by lorc** [comment]
No problem :)
