### ISSUE TITLE
Compiling issue with NEON intrinsics

### ISSUE THREAD

**Issue by MRagot** [OP-TEE/optee_os#2098]
Hello,

I'm using optee_os on a QEmu platform  :
`QEMUv8 | PLATFORM=vexpress-qemu_armv8a`, got it on January the 14th. Used manifest : `QEMUv8 | qemu_v8.xml`

I've tried two versions of the linaro toolchain (from https://releases.linaro.org/): 
-> one using "gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf"
-> another one using "gcc-linaro-7.2.1-2017.11-i686_arm-linux-gnueabihf" (latest according to Linaro)

I have no problem building Client Application (arm, 64bits) including arm_neon.h
But when I try building a Trusted Application (arm, 32bits) including arm_neon.h, i have some errors from gcc.

_My C file include arm_neon.h this way :_ 
`[...]`
`#define STR_TRACE_USER_TA "NEON_TA"`
`#include <tee_internal_api.h>`
`#include <tee_internal_api_extensions.h>`
`#include <arm_neon.h>`
`#include "neon_ta_ta.h"`
`[...] `

_I added those flags for GCC :_ 
`-mfpu=neon-vfpv4' '-mfloat-abi=hard'`

_The errors i get from GCC are :_ 
`In file included from neon_ta_ta.c:33:0:`
`[...]arm_neon.h:16914:1: error: section attribute not allowed for ‘({anonymous})’`
` vaeseq_u8 (uint8x16_t __data, uint8x16_t __key)`
`^~~~~~~~~`
`[...]arm_neon.h: In function ‘vaeseq_u8’:`
`[...]arm_neon.h:16914:1: error: parameter name omitted`
`In file included from [...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/tee_api.h:34:0,
                 from [...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/tee_internal_api.h:33,
                 from neon_ta_ta.c:30:`
`[...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/compiler.h:51:22: error: expected expression before ‘__attribute__’`
` #define __section(x) __attribute__((section(x)))`
`                      ^`
`In file included from neon_ta_ta.c:33:0:`
`[...]arm_neon.h:16916:10: error: too few arguments to function ‘__builtin_arm_crypto_aese’
   return __builtin_arm_crypto_aese (__data, __key);`
`          ^~~~~~~~~~~~~~~~~~~~~~~~~`
`[...]arm_neon.h: At top level:`
`[...]arm_neon.h:16924:1: error: section attribute not allowed for ‘({anonymous})’`
` vaesdq_u8 (uint8x16_t __data, uint8x16_t __key)`
` ^~~~~~~~~`
`[...]arm_neon.h: In function ‘vaesdq_u8’:`
`[...]arm_neon.h:16924:1: error: parameter name omitted`
`In file included from [...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/tee_api.h:34:0,
                 from [...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/tee_internal_api.h:33,
                 from neon_ta_ta.c:30:`
`[...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/compiler.h:51:22: error: expected expression before ‘__attribute__’`
` #define __section(x) __attribute__((section(x)))`
`                      ^`
`In file included from neon_ta_ta.c:33:0:`
`[...]arm_neon.h:16926:10: error: too few arguments to function ‘__builtin_arm_crypto_aesd’
   return __builtin_arm_crypto_aesd (__data, __key);`
`          ^~~~~~~~~~~~~~~~~~~~~~~~~`
`[...]arm_neon.h: At top level:`
`[...]arm_neon.h:16933:1: error: section attribute not allowed for ‘({anonymous})’`
` vaesmcq_u8 (uint8x16_t __data)`
` ^~~~~~~~~~`
`[...]arm_neon.h: In function ‘vaesmcq_u8’:`
`[...]arm_neon.h:16933:1: error: parameter name omitted`
`In file included from [...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/tee_api.h:34:0,
                 from [...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/tee_internal_api.h:33,
                 from neon_ta_ta.c:30:`
`[...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/compiler.h:51:22: error: expected expression before ‘__attribute__’`
` #define __section(x) __attribute__((section(x)))`
`                      ^`
`In file included from neon_ta_ta.c:33:0:`
`[...]arm_neon.h: At top level:`
`[...]arm_neon.h:16942:1: error: section attribute not allowed for ‘({anonymous})’`
` vaesimcq_u8 (uint8x16_t __data)`
` ^~~~~~~~~~~`
`[...]arm_neon.h: In function ‘vaesimcq_u8’:`
`[...]arm_neon.h:16942:1: error: parameter name omitted`
`In file included from [...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/tee_api.h:34:0,
                 from [...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/tee_internal_api.h:33,
                 from neon_ta_ta.c:30:`
`[...]qemu/tools/applib/optee_os/out/arm/export-ta_arm32/include/compiler.h:51:22: error: expected expression before ‘__attribute__’`
` #define __section(x) __attribute__((section(x)))`

I've tried several things in order to fix it... the only way I found getting my TA built is to comment the `vaeseq_u8(...)`, `vaesdq_u8(...)`, `vaesmcq_u8(...)`, `vaesimcq_u8(...)` fucntions directly in arm_neon.h.
And I don't think it is a good way to solve the problem :)

Is there some other way to get my TA build ?

Thanks.

**Comment by jenswi-linaro** [comment]
Hi,

It seems there's some conflicts with `export-ta_arm32/include/compiler.h`. Building TAs with `arm_neon.h` is not something that we're currently supporting. We're supporting "GP Internal Core API" for TAs. There's some limited C standard headers as well, we're adding those as we need them internally.

**Comment by MRagot** [comment]
Hi,
Thanks for your reply.
I understand that there is some conflict with arm_neon.h that prevent us from using some specific functions in it. I also understand that you are adding along support some to C standards headers (arm_neon.h is not covered yet).

Is there some way to use NEON intrinsics in TAs, including any specific Linaro headers i would have missed ?
Or, does using the "dirty" commenting trick i did would really not be recommended ?

**Comment by jenswi-linaro** [comment]
Doing modifications doesn't seem like a very convenient option, but I don't have any other recomendation at this stage.
