### ISSUE TITLE
libteec.so 32-bit does not communicate well with 64-bit kernel module

### ISSUE THREAD

**Issue by gabr1e11** [OP-TEE/optee_os#210]
Hi,

I'm compiling OP-TEE, Android flavor for the Juno board and I'm able to run the hello_world example. However when compiling hello_world in 32-bits and using libteec.so 32-bit version the TEE_OPEN_SESSION ioctl fails. I've checked and it seems to be a problem of a 32-bit client talking to a 64-bit driver. Are there any plans on supporting this combination?

Thanks in advance,
Roberto

**Comment by pascal-brand-st-dev** [comment]
Hello,

This is a known limitations. We plan to support it.
Unfortunately, we do not have any detailed plan on when it will be achieved.

Best regards,
Pascal.

**Comment by gabr1e11** [comment]
Hi Pascal,

Thanks for the prompt response. No good news for me then :)

Do you have an estimation of the amount of work it would take? Just to know if it would be worth it for me to work on that on my side, or wait for you guys.

Thanks again,
Roberto

**Comment by jbech-linaro** [comment]
@gabr1e11 I think it's worth for you to give it a try. We are currently discussing kernel upstreaming in general, so are focus is in another area. Start by having a look at the structures shared between secure and normal world (see mainly the data used in ioctl, open and release in the file_operations). @jforissier gave me a link the other day to a document in the Linux kernel docs that gives some good hints about what to think about when making changes like this. You'll find that document [here](https://www.kernel.org/doc/Documentation/ioctl/botching-up-ioctls.txt).

**Comment by gabr1e11** [comment]
@jbech-linaro many thanks for the heads up. Apparently our client once compiled for 64-bit kind of works (at least it does not crash). Anyway if I feel like I need to port the library/driver to 32 bit I'll let you know so we can sync up.

Thanks!

**Comment by gabr1e11** [comment]
@jbech-linaro Hi again! Still doing some work with OP-TEE and Juno and now I've stomped again against a 32/64 problem. Is there any news regarding this? Or some specific plans? Many thanks again for the info.

**Comment by jbech-linaro** [comment]
Hi @gabr1e11 , sorry for the very late reply, I've totally missed this. The following two pull requests will handle that problem and I think we are going to merge that soon.

* https://github.com/OP-TEE/optee_client/pull/35
* https://github.com/OP-TEE/optee_linuxdriver/pull/29

// Regards Joakim

**Comment by gabr1e11** [comment]
Hi @jbech-linaro, many thanks! I will eventually come back to OPTEE and this will really help.

**Comment by jbech-linaro** [comment]
@gabr1e11 , both patches I've mentioned above has now been merged. If that is working for you also, then I'd suggest that we close this particular issue. What do you think?

**Comment by gabr1e11** [comment]
@jbech-linaro I haven't tried those patches but I agree this can be closed. Thanks!
