### ISSUE TITLE
Fast call return format not consistent

### ISSUE THREAD

**Issue by Jean-Luc-R** [OP-TEE/optee_os#2107]
Hi all, 

When sending Fast calls to Op-TEE, it appears the format of the returned messages is not fully consistent:
(i.e. considering Op-TEE 2.6.0, or even 3.0.0 rcx, file core/arch/arm/include/sm/optee_smc.h)

1.	OPTEE_SMC_CALL_GET_OS_REVISION, OPTEE_SMC_CALL_GET_OS_UUID, OPTEE_SMC_CALLS_REVISION return values directly into [r0/w0] registers.
Some of the values returned today are equal to some standard error codes, e.g. MAJOR API version number is equal to OPTEE_SMC_RETURN_EBUSY

2.	Other SMC calls return first an error status into [r0/w0]

Impact: minimal, treatment of returned values of fast calls must be specific for fast-calls listed in point 1

Question: is there any plan to move toward an homogenous format of returned message for all fast calls?

**Comment by lorc** [comment]
Hi @Jean-Luc-R.

Return values for fast and standard calls are defined in ARM SMC Calling Convention. There is no way to change this and remain compatible with SMCCC.

**Comment by Jean-Luc-R** [comment]
Hi, Thank you for your fast feeback.
Reading chapter 5, I understand your point.
I close the issue.
Regards
Jean-Luc
