### ISSUE TITLE
mpalib does not check memory allocation failure

### ISSUE THREAD

**Issue by Jean-Luc-R** [OP-TEE/optee_os#2108]
Hi

In mpalib, the return code of the mpa_alloc_static_temp_var function is … rarely checked.
Impact: abort in kernel, in the case the mpa buffer _ltc_mempool_u32 is not dimensioned correctly.

Question: is there any plan to fix this?

**Comment by jenswi-linaro** [comment]
Hi,

I don't think anyone is working on this. Patches are welcome!
