### ISSUE TITLE
GP SE API support in OPTEE

### ISSUE THREAD

**Issue by peifu** [OP-TEE/optee_os#2110]
Hi,

There is a configuration flag CFG_SE_API for SE API in optee_os. It is used to enable or disable SE API support in OPTEE. I think this feature can work for the use case that an SE connected exclusively to the TEE. But for the use case that an SE connected to the REE, does OPTEE support it ? I think there should be some RPC commands to support this use case, right ?

B.R.

**Comment by jforissier** [comment]
Hi @peifu, I think you're right.

**Comment by peifu** [comment]
@jforissier, thanks for your confirmation.
Does OPTEE have any plan to support SE from REE ?

**Comment by jforissier** [comment]
Not that I know of, but as always "patches welcome", we will certainly review any proposal.

**Comment by peifu** [comment]
Got it. I will close the issue for now. Thanks.
