### ISSUE TITLE
query: memory leak can happen in authenc_init() function

### ISSUE THREAD

**Issue by Summer-ARM** [OP-TEE/optee_os#2112]
Dear All,

There may exist a memory leak issue in function verify_root() function in core/tee/fs_htree.c. 
https://github.com/OP-TEE/optee_os/blob/8a0dd845509128e41f0a47d9ed58f76a68c86ea0/core/tee/fs_htree.c#L457-L466

In authenc_init(), crypto_authenc_alloc_ctx() first is called to alloc memory for tee_gcm_state structure. However, if it fails in next crypto_authenc_init() or crypto_authenc_update_aad(), it will go to exit and only do crypto_authenc_final(). 
crypto_authenc_final() only reset the states and doesn't do the free job. 

The upper leverl:
https://github.com/OP-TEE/optee_os/blob/8a0dd845509128e41f0a47d9ed58f76a68c86ea0/core/tee/fs_htree.c#L541-L557
authenc_init() is called in verify_root(). If authenc_init() fails, verify_root() directly returns and dones't call crypto_authenc_free_ctx() to free memory which may has been allocated in authenc_init().

		      
Thanks in advance,
Summer

**Comment by jforissier** [comment]
Hi Summer, thanks for reporting this. So it seems the following should fix it, right?
```diff
diff --git a/core/tee/fs_htree.c b/core/tee/fs_htree.c
index 59693c23..ce7fb4a7 100644
--- a/core/tee/fs_htree.c
+++ b/core/tee/fs_htree.c
@@ -488,10 +488,12 @@ static TEE_Result authenc_init(void **ctx_ret, TEE_OperationMode mode,
                                        TEE_FS_HTREE_IV_SIZE);
 
 exit:
-       if (res == TEE_SUCCESS)
+       if (res == TEE_SUCCESS) {
                *ctx_ret = ctx;
-       else
+       } else {
                crypto_authenc_final(ctx, alg);
+               crypto_authenc_free_ctx(ctx, alg);
+       }
 
        return res;
 }
```

**Comment by Summer-ARM** [comment]
Hi Jérôme,
I think it is a good solution to solve one situation that if the failure happens in crypto_authenc_init() or crypto_authenc_update_aad().    

How about if the failure happens in crypto_authenc_alloc_ctx()? 
I know in tomcrypt, crypto_aes_gcm_alloc_ctx() and crypto_aes_ccm_alloc_ctx() only do calloc operation. So even the failure happens in crypto_authenc_alloc_ctx(), it will not cause memory leak.

But you know, we are now trying to integrate the mbedtls into the OPTEE.
In mbedtls, crypto_authenc_alloc_ctx not only allocate tee_gcm_state structure memory operation but also some other memory allocation and some parameters check.
So, I think, in order to avoid memory leak, it is better to free the ctx directly if the crypto_authenc_alloc_ctx() fails.
And other algo (like cipher, mac) also exists this issue. 

Will I push the fixed patch now or later together within mbedtls RFC #1885

**Comment by jenswi-linaro** [comment]
If the error happens in `crypto_authenc_alloc_ctx()` it's the responsibility of that function to free any allocated resources before returning an error.

**Comment by jenswi-linaro** [comment]
By the way, are anyone working on a fix for this problem now or should I start with it?

**Comment by jforissier** [comment]
@jenswi-linaro I would have expected @Summer-ARM to create a PR but it looks like we'll be better off doing it ourselves...

**Comment by Summer-ARM** [comment]
Hi @jforissier @jenswi-linaro 
I am doing this patch, maybe need one or two days to push this patch.
