### ISSUE TITLE
Questions about ECDSA public key attributes TEE_ATTR_ECC_PUBLIC_VALUE_X and TEE_ATTR_ECC_PUBLIC_VALUE_Y

### ISSUE THREAD

**Issue by davidhuziji** [OP-TEE/optee_os#2113]
Hi,

Could you please tell me how to set the `TEE_ATTR_ECC_PUBLIC_VALUE_X` and `TEE_ATTR_ECC_PUBLIC_VALUE_Y` attributes?

I checked some certificates with ECDSA public key. But I found out there is just a single octet string to represent the ECDSA public key. If I'd like to use this public key in TA, how should I convert this octet string into `TEE_ATTR_ECC_PUBLIC_VALUE_X` and `TEE_ATTR_EEC_PUBLIC_VALUE_Y`?

Thank you.

**Comment by jforissier** [comment]
Hi @davidhuziji,

It depends on the format of your certificate. One very common case is, X509 certificate with uncompressed public key. To get X and Y you just remove the first octet (`04` in the example below means uncompressed PK, see here: https://tools.ietf.org/html/rfc5480#section-2.2) and split the octet string in half:

```
$ : | openssl s_client -connect google.com:443 -cipher 'ECDHE-ECDSA-AES128-GCM-SHA256' -servername ssl.gstatic.com | openssl x509 -text -noout
...
Certificate:
    Data:
...
        Subject: C=US, ST=California, L=Mountain View, O=Google Inc, CN=*.google.com
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:dd:79:db:05:4a:9c:52:08:51:07:0c:1c:86:6e:
                    2d:e8:74:2e:00:ab:0f:2b:1f:bd:04:21:c1:7b:1a:
                    29:15:50:80:22:1d:d2:b9:fc:6b:35:0c:23:c4:92:
                    67:2d:b8:e2:37:72:24:9d:db:0d:12:32:a8:a0:c0:
                    2b:81:49:c1:e0
                ASN1 OID: prime256v1
                NIST CURVE: P-256
```

So, X would be `dd79db054a9c520851070c1c866e2de8742e00ab0f2b1fbd0421c17b1a291550` and Y would be `80221dd2b9fc6b350c23c492672db8e23772249ddb0d1232a8a0c02b8149c1e0` (I'm not entirely sure of the endianness, but you get the idea).

**Comment by davidhuziji** [comment]
Hi @jforissier 

Thanks a lot. It is reasonable.
By the way, could you please tell me which document officially address such a format in certificate?
Is it a common format in all certificates or a special one in X.509?

**Comment by jforissier** [comment]
RFC5480 is an update for X.509.

**Comment by davidhuziji** [comment]
Hi @jforissier. Thanks.
I finally find the standard [http://www.secg.org/sec1-v2.pdf](url) which defines this format. The section links in RFC5480 doesn't work. :P
