### ISSUE TITLE
How to use TEE return codes which are mapped to TEEC return codes?

### ISSUE THREAD

**Issue by davidhuziji** [OP-TEE/optee_os#2119]
Hi,

I just found out that some TEE return codes don't own their corresponding TEEC return code, such as `TEE_ERROR_MAC_INVALID`.

I'd like to know why those TEE return codes, such as `TEE_ERROR_MAC_INVALID`, are not mapped to a TEEC return code.
If I have to return `TEE_ERROR_MAC_INVALID` information from TA to CA, what TEE return value should TA function return?
If the TA function still returns `TEE_ERROR_MAC_INVALID`, which TEEC return code will be received by the corresponding CA function?

Thank you.

**Comment by jforissier** [comment]
Hi @davidhuziji ,

I can't really comment on the 'why', we would need to ask the people who defined the spec about the rationale ;-) In any case the values do not conflict, they are actually identical when they are defined on both sides (i.e., `TEEC_FOO` is the same as `TEE_FOO`). So it is not really problematic in practice.

if you return `TEE_ERROR_MAC_INVALID`, your CA will simply receive this value, i.e., 0xFFFF3071. It's just that there is no macro definition for that in the client API. You're free to define your own macro if you wish.

**Comment by davidhuziji** [comment]
Hi @jforissier Thanks a lot!
