### ISSUE TITLE
Embedded RSA Keypair on TA and cipher/decipher

### ISSUE THREAD

**Issue by PedroRibeiro95** [OP-TEE/optee_os#2123]
Hello, I want to embed a private key and corresponding certificate in a TA. The idea is to achieve mutual authentication between the TA and a remote client. To do so, the TA will start by ciphering a message using a private key, and sending the certificate alongside. The remote client will validate the certificate and decipher the message using the public key, cipher a new message with the public key and send it back to the TA. There are a few more details to the algorithm but they are irrelevant for what I'm asking.

I have essentially two questions:

1. How can I embed both private key and certificate on the TA (or at least the public key)?
2. How can I cipher using a RSA Private Key? From what I've seen in the GP API, I can only make a Transient Object hold a Public Key.

Thanks in advance!

**Comment by PedroRibeiro95** [comment]
To add to the question 2., is it possible to generate a deterministic KeyPair by providing a modulus and exponents? If so, how?

**Comment by jforissier** [comment]
Hi @PedroRibeiro95 ,

1. One option I can think of, is to generate the key pair in the TA using `TEE_GenerateKey()` and save it to secure storage for later re-use. Of course you should avoid embedding private keys as raw data arrays in the TA, unless you are certain that the TA will always be encrypted on the device!
2. You cannot encrypt with a RSA private key. As per Table 6-6: Key Pair Parts for Operation Modes, `TEE_MODE_ENCRYPT` uses the public part of the key pair. You should perhaps consider using `TEE_MODE_SIGN` instead (which does use the private key).
2.1. You can create a RSA key pair with `TEE_PopulateTransientObject()` with object type `TEE_TYPE_RSA_KEYPAIR` and attributes `TEE_ATTR_RSA_MODULUS`, `TEE_ATTR_RSA_PUBLIC_EXPONENT` and `TEE_ATTR_RSA_PRIVATE_EXPONENT`.

**Comment by PedroRibeiro95** [comment]
Hello @jforissier. Meanwhile I googled a bit more and found this issue #1749 with a very similar problem. Given that I cannot encrypt with a Private Key I'll need to change my protocol. Thanks a lot for the support. I'll close the issue now.
