### ISSUE TITLE
Some changes regarding to support mbedtls gcm

### ISSUE THREAD

**Issue by Summer-ARM** [OP-TEE/optee_os#2125]
Dear All,

I am from the open source software team in arm. As you know, our team are integrating mbedtls into OPTEE and I am in charge of gcm algo.
In mbedtls, gcm only supports to process the block size(16 bytes) of plain text and cipher text.
Another is that mbedtls gcm only process all the aad in one time, so we need to know the length of aad to allocate proper memory buffer to store the split aad data.
So, we would like make some changes in the following files: 
1. move the TEE_ALG_AES_GCM into upper groups(near TEE_ALG_AES_CCM) to set gcm as block algo:
https://github.com/OP-TEE/optee_os/blob/c0b2e931b395f098aa53912afa8b4f37cb339e1b/lib/libutee/tee_api_operations.c#L131-L156

2. pass aad_len to crypto_aes_gcm_init()
https://github.com/OP-TEE/optee_os/blob/c0b2e931b395f098aa53912afa8b4f37cb339e1b/core/crypto/crypto.c#L186-L207

Thanks in advance,
Summer

**Comment by jforissier** [comment]
Hi @Summer-ARM,

At first glance, both proposals sound reasonable to me.

**Comment by Summer-ARM** [comment]
Hi @jforissier,

Thanks for your comment.
I will refine my patch and then give a pull request :)

**Comment by jenswi-linaro** [comment]
> set gcm as block algo
Can't be done, AES-GCM is a stream cipher and Trusted Applications may depend on that.

**Comment by jforissier** [comment]
> Can't be done, AES-GCM is a stream cipher and Trusted Applications may depend on that.

Right. For some reason I thought the place mentioned by @Summer-ARM was only dealing with buffering. It's not the case and `xtest 4005` does fail with the proposed change.

**Comment by Summer-ARM** [comment]
OK, I got it.
I will discuss with my team member, and will think up a proper solution for us.

**Comment by Summer-ARM** [comment]
Hi guys,
If so, we need to pass dst_len parameter into crypto_aes_gcm_update_payload. That means the function prototype is:  
TEE_Result crypto_aes_gcm_update_payload(void *ctx, TEE_OperationMode mode, const uint8_t *src_date, size_t src_len, uint8_t *dst_data, size_t *dst_len)

To summerize:
1. we need to pass aad_len to crypto_aes_gcm_init()
2. pass dst_len parameter into crypto_aes_gcm_update_payload().

Is that OK from your side?

Regards,
Summer

**Comment by jenswi-linaro** [comment]
That you need to change `crypto_aes_gcm_update_payload()` sound like you're still going do to some internal buffering as the result otherwise always would have the same length as the input. I'm not sure that all our regression tests would pass with internal buffering.

I note that the changes you propose isn't because the cryptographic operation needs it, it's only due to limitations from your implementation. When looking at the implementation of `mbedtls_gcm_starts()` and `mbedtls_gcm_update()` I can't see any performance reasons for this limitation.

It would from OP-TEE point of view be more convenient if the limitations you've put to AES-GCM was removed so it could be integrated without further internal API changes in OP-TEE.

**Comment by Summer-ARM** [comment]
Hi @jenswi-linaro 
I have confirmed with mbedtls guys:
`mbedtls_gcm_starts()` is used to start the operation, and it should be called once. So we need to buffer aad data until we get the whole aad data to update.
`mbedtls_gcm_update()` Encrypts/decrypts using the given GCM context. Expects input to be a multiple of 16 bytes! Only the last call before mbedtls_gcm_finish() can be less than 16 bytes! Since the user may not pass a multiple of 16 bytes split payload data, we need to buffer it and return the actual dst_len to the user.
This is the issue we discussed: https://github.com/ARMmbed/mbedtls/issues/1369

Yes, you are right! In order to support mbedtls gcm features and pass the 4005, I comment the following two codes:
 https://github.com/OP-TEE/optee_test/blob/92c3442ee1fd13f1232ab572190a98da6cddc3ab/host/xtest/regression_4000.c#L2774-L2776

https://github.com/OP-TEE/optee_test/blob/92c3442ee1fd13f1232ab572190a98da6cddc3ab/host/xtest/regression_4000.c#L2787-L2789

I research the gcm document: http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf It doen't say what should do when the split payload data is less than 16 bytes. Do you know there is any document specifically point out what to do when the split payload data is less than block size? If so, could you please send me the link?

**Comment by jenswi-linaro** [comment]
Hi @Summer-ARM 

No I don't have a link, but what to do is quite intuitive. Also if you want to dig even deeper you can compare with what's to be done in counter mode with incomplete blocks, it's the same problem except that you don't need to worry about the hashing.

In `__gcm_update_payload()` at https://github.com/OP-TEE/optee_os/blob/master/core/crypto/aes-gcm.c#L186-L254 we're dealing with unaligned/incomplete blocks.

In `gcm_process()` at https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/encauth/gcm/gcm_process.c#L57-L174 you can see the same.

The trick is to encrypt the counter block when needed and then xor the bytes available until the block is complete. After that you can start over with next block. This doesn't change the algorithm, the result is exactly the same.

**Comment by edison-ai** [comment]
Hi @jenswi-linaro,
According to NIST document: http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf, we can see the description about CTR:
`For the OFB and CTR modes, the plaintext need not be a multiple of the block size. Let n and u denote the unique pair of positive integers such that the total number of bits in the message is (n-1)b+u, where 1≤ u≤ b. The plaintext consists of a sequence of n bit strings, in which the bit length of the last bit string is u, and the bit length of the other bit strings is b. The sequence is denoted P1, P2,…, Pn-1, P* , and the bit strings are called data blocks, although the last bit string,P* , may not be a complete block.`
We can find only last block may be a incomplete block. 
And I had researched some documents about GCM, but no one said it is a stream cipher.

**Comment by jenswi-linaro** [comment]
Sure, only the last block can be incomplete once everything is done as the blocks before obviously is completed before starting with the next block.

Do you think that users of GCM is mode are wrong to expect unbuffered encryption?

**Comment by edison-ai** [comment]
I suggest we use internal GCM now, and we will not push the patch to support mbedTLS GCM algo until we get a good solution for it.

**Comment by jenswi-linaro** [comment]
Sounds good.
