### ISSUE TITLE
 kernel missed the OP-TEE driver

### ISSUE THREAD

**Issue by j824737450** [OP-TEE/optee_os#2126]
Hi,
After linux boots up,:
root@arm:~# tee-supplicant &
root@arm:~# ERR [1034] TEES:main:663: failed to find an OP-TEE supplicant device
and then
root@arm:~# ls /dev/tee*
ls: cannot access /dev/tee*: No such file or directory
It's mentioned in #835 that "If you don't it means your kernel is missing the OP-TEE driver. See here: https://github.com/linaro-swg/linux/tree/optee."
But when I try to compile the kernel, "linux-optee" downloaded from the above address, there are some errors, like that
![1](https://user-images.githubusercontent.com/33032927/35851113-e8ed8b38-0b61-11e8-8687-85a788a8ab49.png)
How can I solve my problem?
Thank you!

**Comment by jenswi-linaro** [comment]
These days the OP-TEE driver is available in upstream kernels too. Perhaps using a recent upstream kernel version suits your need better.

Another source of unavailable `/dev/tee*` is a missing `optee` node in the device tree in use.
