### ISSUE TITLE
Execution of xtest is slow?

### ISSUE THREAD

**Issue by j824737450** [OP-TEE/optee_os#2129]
Hi,
It's two hours from beginning of xtest, and t's not over yet. Is this normal??? 
It's on the imx6q-sabrelite board. Like this:
![1](https://user-images.githubusercontent.com/33032927/35921298-3f25380e-0c55-11e8-8118-955909bf929a.jpg)
Thank you!

**Comment by jforissier** [comment]
Hi @j824737450 ,

No, it is not normal. `xtest` should run in a couple of minutes at most. Are you using the pager (`CFG_WITH_PAGER=y`)?

**Comment by j824737450** [comment]
I think I'm not using that. I just do as 
"make PLATFORM=imx-mx6qsabrelite ARCH=arm CFG_BUILT_IN_ARGS=y CFG_PAGEABLE_ADDR=0 CFG_NS_ENTRY_ADDR=0x12000000 CFG_DT_ADDR=0x18000000 CFG_DT=y CFG_PSCI_ARM32=y DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4 CFG_BOOT_SYNC_CPU=n CFG_BOOT_SECONDARY_REQUEST=y"

**Comment by jforissier** [comment]
OK. `CFG_WITH_PAGER` defaults to `n`. So it rules out this known issue: https://github.com/OP-TEE/optee_os/issues/2080.
Which test number hangs? Is the issue reproducible (sometimes/always...)?

**Comment by j824737450** [comment]
Sorry for the late reply.
I tried it a couple of times. And they are different. It hangs on like that:
![1](https://user-images.githubusercontent.com/33032927/35950248-9b201d58-0cb0-11e8-8c00-5b443202863f.jpg)
![2](https://user-images.githubusercontent.com/33032927/35950258-a5c27f8a-0cb0-11e8-9849-93162be4689f.jpg)
and It could be a dead cycle :
![3](https://user-images.githubusercontent.com/33032927/35950294-c6b6c5c0-0cb0-11e8-9aac-969167fb6eb0.jpg)

And every time I run the $tee-supplicant &, there will be that:
![4](https://user-images.githubusercontent.com/33032927/35950324-f331da2c-0cb0-11e8-81e4-6faa9c8bc68e.jpg)
![5](https://user-images.githubusercontent.com/33032927/35950330-f8bb6c7e-0cb0-11e8-948f-f56c8d40acc6.jpg)

**Comment by j824737450** [comment]
Sorry for the late reply, I think it may be caused by the instability of the root file system. I will change a root file system and then try. Thank you!
