### ISSUE TITLE
Creating directories and files in trusted application using TEE api

### ISSUE THREAD

**Issue by aim2nasa** [OP-TEE/optee_os#2136]
For some secure data I'm using, I'm trying to store it in files under the directory that I created.

As far as I know, there's no such a file system API(fopen, fwrite etc) in TEE spec.
Instead I could find persistent object functions something like TEE_CreatePersistentObject .

It seems like it's possible to store my data using TEE_CreatePersistentObject  when I create Trusted Application, similary just like using fwrite function.

But I'm not sure yet, if there's such a TEE API which allows me to create directory.
So far I couldn't find anyone.

Instead, I found one under "optee_os/core/include/tee/tee_svc_storage.h" which seems quite promising.
Using the above, I think it's possible to create directory that I wanted.
But I couldn't find the API in the GP standard document so far. (could be optee specific API, I'm not sure)

Please let me know my approach is on the right track .

Thanks in advance for any comments.

**Comment by etienne-lms** [comment]
Hello,
If a TA need to handle "secure files", then such files should be managed by the secure storage layer, and no be straight related to REE directories/files. 

If you need the TA to access secure files as in a filesystem, you could implement a library using the TEE persistent object (`TEE_CreatePersistentObject` and friends) to export some fopen/fread/... without bothering how the data are effectively eventually stored in the REE filesystem: this is the secure storage matter (current can be either ree_fs or rmpb_fs).

If the TA needs to access some non secure data, then maybe the TA client could access the file and provide the data to the TEE.

**Comment by aim2nasa** [comment]
thanks for your comments
