### ISSUE TITLE
Routing of ARM PSCI calls to a Trusted Application implementation

### ISSUE THREAD

**Issue by paswan-ms** [OP-TEE/optee_os#214]
Hi,
We're intending to utilize the OpTEE OS on the 32-bit ARM architecture and provide a Trusted Application implementation of PSCI. The ARM PSCI interface is defined at the SMC level and thus does not follow the Global Platform specifications. Therefore, we think we need to do the following:

1)	When the OpTEE OS is started automatically self-open a session targeting the PSCI Trusted Application (TA). This session is never closed and is used as the implicit session identification for all PSCI calls. Client originated session open & close targeting the PSCI TA is prohibited (blocked).
2)	Adjust the inbound vector handler to filter the PSCI SMC calls and call a conversion dispatch handler to convert the ARM PSCI SMC call into a TEESMC_CMD_INVOKE_COMMAND call utilizing the automatic PSCI TA session created above when the OS was started. The conversion dispatch handler remaps the ARM PSCI call registers and parameter definitions to a compliant TEESMC_CMD_INVOKE_COMMAND call targeting the PSCI TA.
3)	On completion of the PSCI TA call perform a similar outbound conversion to convert the TEESMC_CMD_INVOKE_COMMAND completion return parameters to match the ARM PSCI SMC specification.

This would serve as a template for being able have Trusted Applications in OpTEE handle externally specified SMC call API's.

Since we're starting from scratch with OpTEE, we'd be grateful for any insight on if we're heading in the right direction to solve this problem?
Thanks,
Paul.

**Comment by jenswi-linaro** [comment]
Hi Paul,

An easier approach would be to skip the TA concept completely when handling PSCI. There's a callback function which is called when an SMC is delivered to OP-TEE. This callback (plat_tee_entry() in plat-vexpress and main_tee_entry() in the others) currently handles only Trusted OS and Trusted Application SMCs, but can be extended to handle other SMCs too. Note that fastcalls (I guess all the PSCI SMCs are fastcalls) are treated a bit differently compared to normal calls. Fastcalls are served with IRQ and FIQ masked and the stack is not too big either.

Another reason to not having the PSCI code in a TA is that the code will need to execute in privileged mode and the dynamically loaded TAs executes in user mode. It is possible link TAs into OP-TEE which executes in privileged mode (example in core/arch/arm32/sta/), but that's a lot more complicated than handling the PSCI SMCs directly.

Regards,
Jens

**Comment by paswan-ms** [comment]
Thanks for the feedback. The main driver for going with a TA approach versus bare metal was to benefit from OpTEE thread & context management. In 64-bit ARM the use of different EL's provide context separation in hardware between ATF/PSCI and the TEE. With 32-bit ARM there isn't a separation between PSCI and the rest of TrustZone, leading us down a TA path for a PSCI implementation to gain it. I'll take a look at the code points you've suggested as possible entry-points into a PSCI direct implementation.
Thanks again for the input,
Paul.

**Comment by paswan-ms** [comment]
Closing out this issue - we're going with the approach you suggested.
Thanks,
Paul.
