### ISSUE TITLE
Translation fault

### ISSUE THREAD

**Issue by Marwen10** [OP-TEE/optee_os#2140]
Hello,
I wrote an TA that works fine for integrity verification. I wanted to run at boot, so I added a script to /etc/rc.local. It causes a translation fault, even though it can open a Tee session.
Here is the log:

FLOW:    USER-TA: tee_user_mem_alloc:343: Allocate: link:[0x400140a0], buf:[0x400140c0:32]
DEBUG:   USER-TA:TA_OpenSessionEntryPoint:80: HASH VERIFICATION!
[   20.875182] hash_verificati[866]: unhandled level 3 translation fault (11) at 0x7fc1bd4000, esr 0x92000007
[   20.885179] pgd = ffffffc03134f000
[   20.888722] [7fc1bd4000] *pgd=00000000332d5003, *pud=00000000332d5003, *pmd=000000003136f003, *pte=0000000000000000
[   20.899600] 
[   20.901157] CPU: 2 PID: 866 Comm: hash_verificati Not tainted 4.6.3-17583-g7d976fc #1
[   20.909246] Hardware name: Raspberry Pi 3 Model B (DT)
[   20.914596] task: ffffffc031a49a00 ti: ffffffc03326c000 task.ti: ffffffc03326c000
[   20.922349] PC is at 0x7f7aa0cd3c
[   20.925805] LR is at 0x7f7aade55c
[   20.929247] pc : [<0000007f7aa0cd3c>] lr : [<0000007f7aade55c>] pstate: 20000000
[   20.936898] sp : 0000007fc1bd2ea0
[   20.940360] x29: 0000007fc1bd2ea0 x28: 0000000000000000 
[   20.945881] x27: 0000000000000000 x26: 0000000000000000 
[   20.951449] x25: 0000000000000000 x24: 0000000000000000 
[   20.956977] x23: 0000000000000000 x22: 0000000000000000 
[   20.962493] x21: 0000000000400910 x20: 0000000000000000 
[   20.968056] x19: 0000000000401080 x18: 0000000000000000 
[   20.973586] x17: 0000007f7aaf0270 x16: 0000007f7aa0cc10 
[   20.979132] x15: 0000000000000450 x14: 0000000000000000 
[   20.984676] x13: 3164303239333866 x12: 000000006e6f6974 
[   20.990206] x11: 6163696669726576 x10: 5f687361682f7470 
[   20.995751] x9 : 697263732f656d6f x8 : 682f002f3d445750 
[   21.001266] x7 : 00382d4654552e43 x6 : 3d474e414c006164 
[   21.006812] x5 : 0000007f7ab23200 x4 : 0000007fc1bd40b3 
[   21.012345] x3 : 0000007f7ab23100 x2 : 00000000000000b0 
[   21.017862] x1 : 0000007fc1bd3fb3 x0 : 0000007f7ab23000 
[   21.023405] 
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:402: tee_ta_close_session(0x8483e40)
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:421: Destroy session

So 
1)what the cause of this ?
2)is there a thing to change in order to make it work ? like some instruction missing. 
thanks in advance

**Comment by Marwen10** [comment]
Actually, the problem seems to be more related to scheduling. As even if I use crontab when the system is up and running (and I can execute the app from command line) to execute the task every 10 minutes for example, I get the same error.

**Comment by jenswi-linaro** [comment]
Could it be linked to what the TA is doing and/or passed parameters?

**Comment by Marwen10** [comment]
It is apparently linked to the environment variables. As the environment is different from cron to an interactive shell. The weird thing is it doesn't even enters the user space application's main. I tried to correct the paths used without success. Is there something I should tell cron to look into ?
