### ISSUE TITLE
Passing uint8_t[] to TA

### ISSUE THREAD

**Issue by PedroRibeiro95** [OP-TEE/optee_os#2141]
Hello. I need to transfer an array of uint8_t (a public key modulus) to the TA for encryption. I tried using memref and memcopying the array to the buffer and then casting the void * on the TA side to uint8_t *, but it isn't working. The encryption is working if I hard code the modulus, so my problem is really to transfer it CA -> TA. Could you guys give a hand? Thanks!

**Comment by jforissier** [comment]
Hello,

What you are describing should work... Please see https://github.com/linaro-swg/optee_examples/blob/master/aes/ta/aes_ta.c#L225 and https://github.com/linaro-swg/optee_examples/blob/master/aes/host/main.c#L99. It should help.

**Comment by PedroRibeiro95** [comment]
This is really weird. I printed the hardcoded uint8_t array modulus that allows me to encrypt with sucess and the one I've sent from the CA which leads to a TEE_ERROR_BAD_PARAMETERS on TEE_AssymetricEncrypt. They're exactly the same. For some reason having a uint8_t[] and a uint8_t * is leading to different behaviour. Could this be a problem on LibTomCrypto?

**Comment by PedroRibeiro95** [comment]
Okay, I ended up resolving this problem. Casting from void * to uint8_t * was indeed working, but the sizeof of the vector is lost in the process. As such, when assigning the attributes to encrypting with TEE Asymmetric Encrypt by calculating the sizeof it would give the TEE_ERROR_BAD_PARAMETERS error.
