### ISSUE TITLE
building optee-os for MACCHIATObin?

### ISSUE THREAD

**Issue by fxlin** [OP-TEE/optee_os#2142]
We are interested in trying optee_os on MACCHIATObin (http://macchiatobin.net/), which has Marvell ARMADA 8040 SoC that is said to be supported by optee_os. Yet I couldn't find any instructions on building the whole stack for the board. Can anyone confirm that I can build optee_os for this board and share some pointers? Thanks!

**Comment by vchong** [comment]
Try contacting the Marvell board maintainer - https://github.com/OP-TEE/optee_os/blob/master/MAINTAINERS.md
