### ISSUE TITLE
TLS isocket implementation

### ISSUE THREAD

**Issue by vtcao297** [OP-TEE/optee_os#2146]
Hi, 

I'm curious if there is a roadmap plan for when the TEE_iSocket support for TLS will be implemented?

**Comment by jforissier** [comment]
Hi @vtcao297 ,

TLS support is in the to-do list but I'm not sure it appears in any roadmap yet. Which means, if you feel like working on it, do not hesitate, and we will certainly provide help and feedback.

**Comment by cezane** [comment]
Since TLS support is not implemented yet, is there support to ECDH operations in order to derive a shared secret key and use it to protect data during communication?

**Comment by jforissier** [comment]
Yes.

```
$ git grep ECDH lib/libutee/include/
lib/libutee/include/tee_api_defines.h: *     indicates ECDSA have the algorithm "0x41" and ECDH "0x42"
lib/libutee/include/tee_api_defines.h:#define TEE_ALG_ECDH_P192                       0x80001042
lib/libutee/include/tee_api_defines.h:#define TEE_ALG_ECDH_P224                       0x80002042
lib/libutee/include/tee_api_defines.h:#define TEE_ALG_ECDH_P256                       0x80003042
lib/libutee/include/tee_api_defines.h:#define TEE_ALG_ECDH_P384                       0x80004042
lib/libutee/include/tee_api_defines.h:#define TEE_ALG_ECDH_P521                       0x80005042
lib/libutee/include/tee_api_defines.h:#define TEE_TYPE_ECDH_PUBLIC_KEY            0xA0000042
lib/libutee/include/tee_api_defines.h:#define TEE_TYPE_ECDH_KEYPAIR               0xA1000042
lib/libutee/include/utee_defines.h:#define TEE_MAIN_ALGO_ECDH       0x42
```

**Comment by gagachang** [comment]
Hello, @jforissier 
Does latest OP-TEE support TLS socket?
Thanks!

**Comment by jforissier** [comment]
Hi @gagachang,
No, still not supported. I haven't heard of anyone working on it either.

**Comment by gagachang** [comment]
@jforissier , OK! Thank you for fast reply.
