### ISSUE TITLE
Hikey 960: Secure memory accessible from normal world EL1?

### ISSUE THREAD

**Issue by Pentr** [OP-TEE/optee_os#2148]
Hi,

I am running Linux / OP-TEE on a Hikey 960 board.

According to the hikey config file the secure memory is protected by a DDR controller and I assumed that the quoted memory ranges are the ones assigned to the secure world.

[https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/platform_config.h](url)

`#define TZSRAM_BASE		0x3F000000`
`#define TZSRAM_SIZE		CFG_CORE_TZSRAM_EMUL_SIZE`
`#define TZDRAM_BASE		0x3F200000`
`#define TZDRAM_SIZE		(14 * 1024 * 1024)`

However, in a Linux kernel module I am able to read from these areas using `ioremap()`.

`void __iomem *io = ioremap(TZDRAM_BASE, TZDRAM_SIZE);`
`unsigned int val = ioread32(io);`

I would actually expect some kind of exception here. What am I missing here? Is the DDR controller that should protect the secure memory from the normal world not configured?

**Comment by jforissier** [comment]
Hi @Pentr,

The comment applies to Hikey only, not to HiKey960. It should probably be updated.

Even on HiKey, memory protection is not part of upstream ARM-TF yet, it is in a Linaro branch: https://github.com/linaro-swg/arm-trusted-firmware/tree/hikey (see file: https://github.com/linaro-swg/arm-trusted-firmware/blob/hikey/plat/hikey/plat_security.c). The Linaro Hikey build environment (https://github.com/OP-TEE/manifest/blob/master/hikey.xml) uses upstream ARM-TF, not the Linaro branch anymore.

Finally, I have no idea how DDR may be protected on HiKey960 (TZASC or DDR controller details are undocumented).

**Comment by Pentr** [comment]
Thank you for your answer.
One last question though. Is the separation of the normal and secure world enforced  on one of the other boards supported by OP-TEE, like the Raspberry Pi 3?

**Comment by lorc** [comment]
Hi @Pentr,

I can say for OMAP/Jacinto boards and for RCAR Gen3 boards. Both this platforms support hardware protection of secure RAM. RCar Gen3 starter kits will be available soon for purchase.

**Comment by Pentr** [comment]
Alright, thanks!
