### ISSUE TITLE
Secure Monitor assembly comment explanation

### ISSUE THREAD

**Issue by maximouth** [OP-TEE/optee_os#2149]
Hi,

There is something strange into the file *sm_a32.S* locate here
[ optee_os/core/arch/arm/sm/sm_a32.S](https://github.com/OP-TEE/optee_os/blob/bda4804c8b796b40865d8b845961a91406d92614/core/arch/arm/sm/sm_a32.S)

at line 141, the comment says that  ```we're shifting r1-r4 from secure context into r0-r3 in non-secure context``` but when I read the assembly code it seems to be the opposite.

```
/*
	 * On FIQ exit we're restoring the non-secure context unchanged, on
	 * all other exits we're shifting r1-r4 from secure context into
	 * r0-r3 in non-secure context.
	 */
	add	r8, sp, #(SM_CTX_SEC + SM_SEC_CTX_R0)
	ldm	r8, {r0-r4}
	mov_imm	r9, TEESMC_OPTEED_RETURN_FIQ_DONE
	cmp	r0, r9
	addne	r8, sp, #(SM_CTX_NSEC + SM_NSEC_CTX_R0)
	stmne	r8, {r1-r4}
```

Is it me that don't understand the thing or not ?

Thank you in advance,
Maxime

PS: Pardon me for my English (French)..

**Comment by jenswi-linaro** [comment]
If `r9` isn't `TEESMC_OPTEED_RETURN_FIQ_DONE` then the shifting occurs by storing `{r1-r4}` in the non-secure context registers that will later be restored into `{r0-r3}`.
