### ISSUE TITLE
Translating normal world virtual addresses to physical addresses

### ISSUE THREAD

**Issue by matzedav** [OP-TEE/optee_os#2150]
Hey,

im trying to translate a normal world virtual address into a physical address to access from a PTA. I read the previous issues and tried something out like:
- take a valid virtual address from a NW program
- virt_to_phys()
- register_phys_mem()

but i get the following error by booting qemu_v8:
`DEBUG:   [0x0] TEE-CORE:check_pa_matches_va:1636: va 0xfffff243a8dc unmapped, expect 0xfffff243a8dc`
`ERROR:   [0x0] TEE-CORE: Panic at core/arch/arm/mm/core_mmu.c:1637 <check_pa_matches_va>`
`ERROR:   [0x0] TEE-CORE: Call stack:`
`ERROR:   [0x0] TEE-CORE:  0x000000000e108b14`

My code looks like:
`uint64_t phys_addr;`
`vaddr_t va_addr = 0xfffff243a8dc;`
`phys_addr = virt_to_phys((void *)va_addr);`

I tried to put this codesnippet above in my core_mmu.c` in the function `init_mem_map()` at the end. Am I missing something or is it the wrong place to translate the addresses?

Thank you for your help!

**Comment by etienne-lms** [comment]
In the context of a pTA,  `virt_to_phys()` cannot be use to convert a REE (Linux?) virtual address into a physical address. In it designed to convert virtual addresses in the secure world: the virtual addresses that are mapped in the pTA execution context.

**Comment by xnadO** [comment]
Is there any way to read a normal address in a context of a pTA or user TA? 

When i read other issues about that problem (especially #1249) i assumed that i can translate the virtual addresses to a physical addresses and add these addresses to TA mapping. So a static TA can access it.

**Comment by etienne-lms** [comment]
Technically, a pTA can convert a virtual address mapped in the core non secure state into a physical address. This services is not implemented. Check implementation of `arm_va2pa_helper()` in **core_mmu.c** as an example on how to convert secure mapped addresses. One can build an equivalent service for non secure mapped address if required.

Converting virtual address into physical is not supported in the TAs.

**Comment by jenswi-linaro** [comment]
Note that the shortcut @etienne-lms is suggesting only is available for ARMv7-A. For ARMv8-A it would need to be done entirely in software. I've heard someone talking about implementing this in ARM-TF as a runtime service, but I don't know if anything happened.

**Comment by lorc** [comment]
I doubt that this possible at all. Surely, you can do translation for **current** running process. But, due to RPCs, current running process can be any process. `tee-supplicant`, for example.

**Comment by jenswi-linaro** [comment]
Current running process is always the one doing the SMC to secure world, that should be the same as the client process.

**Comment by lorc** [comment]
Ah, yes. You are right. This is valid for linux. 
But, AFAIK, this is not defined nowhere in the protocol. So, other client implementation can work in completely different way.

**Comment by jenswi-linaro** [comment]
Agree
