### ISSUE TITLE
TA memory leak

### ISSUE THREAD

**Issue by ademyankov** [OP-TEE/optee_os#2154]
I couldn't find any memory support functions that can give me any information about heap space left for my TA. I have a problem that after multiple mallocs it finally gives me NULL meaning that there is no memory left.

Is there any mechanism I can use to monitor memory allocations and frees? Naturally, I cannot run valgrind on TA or hook it up into GDB.

Any suggestions?

**Comment by ademyankov** [comment]
I know how to debug TA using GDB. The problem is that GDB doesn't have any build-in facility to deal with memory leaks on its own. It can be done in combination with valgrind. Even though I cross-compiled valgrind for aarch64 it can be used for REE side only. Or better say, I couldn't figure out the way of hooking it up, in a config like: TA + valgrind (vgdb) + gdb.

Anyway, looks like your tip for `mdbg_check()` is exactly what I need right now. I'll check it out. Thanks.

**Comment by ademyankov** [comment]
It doesn't look easy to enable that stuff!

There is no comment around ENABLE_MDBG define, like how to use it and where to enable. And it looks like that thing is related to BGET memory allocator. There is no documentation on how to enable or use BGET.

I tried to change those settings in `optee_os/mk/config.mk`
```
# If y, enable memory leak detection feature in bget memory allocator.
CFG_TEE_CORE_MALLOC_DEBUG ?= y
CFG_TEE_TA_MALLOC_DEBUG ?= y
```
Then I get an linker error for my TA:
`undefined reference to `malloc'`

If try to define just ENABLE_MDBG macro, then I get
```
undefined reference to `mdbg_check'
undefined reference to `mdbg_malloc'
```
I have to dig harder into it...

**Comment by jforissier** [comment]
Hi @ademyankov,

> I tried to change those settings in `optee_os/mk/config.mk`
> ```
> # If y, enable memory leak detection feature in bget memory allocator.
> CFG_TEE_CORE_MALLOC_DEBUG ?= y
> CFG_TEE_TA_MALLOC_DEBUG ?= y
> ```
> Then I get an linker error for my TA:
> `undefined reference to `malloc'`

I suspect you TA was not re-linked against the new `libutils.a`. But you will also need this patch, which fixes a missing `-DENABLE_MBDG` when building TAs: https://github.com/OP-TEE/optee_os/pull/2157

Let us know if that works for you (and feel free to give your Tested-by: to PR 2157 if that works well).

**Comment by ademyankov** [comment]
Cool! It works now. And small thing to remember that `mdbg_check()` prints out info only with CFG_TEE_TA_LOG_LEVEL=3

**Comment by daojianxiaowuke** [comment]
> Hi @ademyankov,
> 
> > I tried to change those settings in `optee_os/mk/config.mk`
> > ```
> > # If y, enable memory leak detection feature in bget memory allocator.
> > CFG_TEE_CORE_MALLOC_DEBUG ?= y
> > CFG_TEE_TA_MALLOC_DEBUG ?= y
> > ```
> > 
> > 
> > Then I get an linker error for my TA:
> > `undefined reference to `malloc'`
> 
> I suspect you TA was not re-linked against the new `libutils.a`. But you will also need this patch, which fixes a missing `-DENABLE_MBDG` when building TAs: #2157
> 
> Let us know if that works for you (and feel free to give your Tested-by: to PR 2157 if that works well).

Hi @jforissier,
I've tried it in optee-3.11.0. It builds successfully but the TA memory leak check doesn't work.  I find TEE_Malloc in TA still  calls malloc() in debugging, instead of mdbg_xxx(). The following is my setings:
in mk/config.mk
CFG_TEE_CORE_MALLOC_DEBUG ?= n
CFG_TEE_CORE_LOG_LEVEL ?= 3
CFG_TEE_TA_MALLOC_DEBUG ?= y
CFG_TEE_TA_LOG_LEVEL ?= 3

in ta/ta.mk
ifeq ($(CFG_TEE_TA_MALLOC_DEBUG),y)
cppflags$(sm) += -DENABLE_MDBG=1
endif

in ta_dev_kit.mk
ifeq ($(CFG_TEE_TA_MALLOC_DEBUG),y)
cppflags$(sm) += -DENABLE_MDBG=1
endif

 Could you please give me any suggestion?
