### ISSUE TITLE
Invalid signature on AsymmetricVerifyDigest

### ISSUE THREAD

**Issue by Bolvach-BVM** [OP-TEE/optee_os#2156]
Greetings.

I have a CA and TA and I'm trying to create a mutual authentication protocol. As such, the CA uses openssl for encryption of data and signing it and sends it to the TA, which decrypts the data and verifies the signature using the Global Platform API. However, I'm running into some problems in the TA side, as the verification of the signature always fails. I've been troubleshooting and verified that the digest generated in both sides is the same. Given that encryption between both applications works, the problem also can't lie in the keys I'm using. As such, I'm completely clueless as to what the problem might be.

Following are the pieces of code on the CA and TA responsible for signing the data and verifying the signature, respectively.

On the CA:

```c
// create RSA object
RSA *createRSA(unsigned char *key, int public) {
   RSA *rsa = NULL;
   BIO *keybio;
   keybio = BIO_new_mem_buf(key, -1);
   if (keybio == NULL) {
      printf("==> Error: Failed to create key BIO");
      return 0;
   }
   if (public) {
      rsa = PEM_read_bio_RSA_PUBKEY(keybio, &rsa, NULL, NULL);
   } else {
      rsa = PEM_read_bio_RSAPrivateKey(keybio, &rsa, NULL, NULL);
   }
   if (rsa == NULL) {
      printf("==> Error: Failed to create RSA");
   }
   return rsa;
}

int sign_with_private_key(char * in, int in_len, char * out, int * out_len) {

	RSA * rsa;
	SHA_CTX sha_ctx = {0};
	unsigned char digest[SHA_DIGEST_LENGTH];
	unsigned char digest_hack[20];

	rsa = createRSA ((unsigned char *) private_key_app, 0);

	//Starts by digesting the input
	SHA1(in, in_len, digest);

	memcpy(digest_hack, digest, 20);

	//Signing
	RSA_sign(NID_sha1, (unsigned char *)digest_hack, 20, (unsigned char*)out, out_len, rsa);

	if (*out_len == -1) {
      return -1;
   } else {
      return 1;
   }
}
```

On the TA:
```c
int create_digest(const char * in, int in_len, char * out, int * out_len) {
   TEE_Result ret = TEE_SUCCESS; // return code
   TEE_OperationHandle handle = (TEE_OperationHandle) NULL;

   uint32_t message_len = in_len;
   void *message = NULL;

   uint32_t digest_len = 20;
   void *digest = NULL;

   message = TEE_Malloc(message_len, 0);
   digest = TEE_Malloc(digest_len, 0);

   TEE_MemMove(message, in, in_len);
   message_len = in_len;

   // Allocate the operation
   ret = TEE_AllocateOperation(&handle, TEE_ALG_SHA1, TEE_MODE_DIGEST, 0);
   if (ret != TEE_SUCCESS) {
      IMSG("ERROR: Digest allocate\n");
      return -1;
   }

   // Digest
   ret = TEE_DigestDoFinal(handle, message, in_len, digest, &digest_len);
   if (ret == TEE_ERROR_SHORT_BUFFER) {
      IMSG("ERROR: Digest final short buffer\n");
      return -1;
   }

   // clean up after yourself
   TEE_FreeOperation(handle);
   memcpy(out, digest, digest_len);

   *out_len = digest_len;

   // fin
   return 0;
}

int verify_signature(uint8_t * modulus, const char * in, int in_len, char * signature, int sign_len) {

  TEE_Result ret = TEE_SUCCESS; // return code
  TEE_ObjectHandle key = (TEE_ObjectHandle) NULL;
  TEE_Attribute rsa_attrs[2];
  TEE_OperationHandle handle = (TEE_OperationHandle) NULL;
  unsigned long int sizeofmod = 256; //hack because casting void * to uint8_t * leads to a sizeof of -1
  char digest[20] = {0};
  int digest_len;

  create_digest(in, in_len, digest, &digest_len);

  // modulus
  rsa_attrs[0].attributeID = TEE_ATTR_RSA_MODULUS;
  rsa_attrs[0].content.ref.buffer = modulus;
  rsa_attrs[0].content.ref.length = sizeofmod;
  // Public key
  rsa_attrs[1].attributeID = TEE_ATTR_RSA_PUBLIC_EXPONENT;
  rsa_attrs[1].content.ref.buffer = public_key;
  rsa_attrs[1].content.ref.length = SIZE_OF_VEC (public_key);

  // create a transient object
  ret = TEE_AllocateTransientObject(TEE_TYPE_RSA_PUBLIC_KEY, 2048, &key);
  if (ret != TEE_SUCCESS) {
    return TEE_ERROR_BAD_PARAMETERS;
  }

  // populate the object with your keys
  ret = TEE_PopulateTransientObject(key, (TEE_Attribute *)&rsa_attrs, 2);
  if (ret != TEE_SUCCESS) {
    return TEE_ERROR_BAD_PARAMETERS;
  }

  // Allocate the operation
  ret = TEE_AllocateOperation(&handle, TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_MODE_VERIFY, 2048);
  if (ret != TEE_SUCCESS) {
    return -1;
  }

  // set the key
  ret = TEE_SetOperationKey(handle, key);
  if (ret != TEE_SUCCESS) {
    TEE_FreeOperation(handle);
    return -1;
  }

  // encrypt
  ret = TEE_AsymmetricVerifyDigest(handle, (TEE_Attribute *)NULL, 0, digest, digest_len, signature, sign_len);
  if(ret == TEE_SUCCESS)
    IMSG("INIT: Success verifying signature!\n");
  else
    IMSG("INIT: Error verifying signature!\n");

  return 0;
}
```
I would very much appreciate if you could take a look at this. I suppose the problem is something really small but I'm just not seeing it.

**Comment by jforissier** [comment]
Hi @Bolvach-BVM,

If you are certain you got your key setup right (what is the value of `SIZE_OF_VEC(public_key)`? if your exponent is the usual `{0x01, 0x00, 0x01}` then it has to be 3), then the most likely problem I would imagine is with the format of the signature. Perhaps OpenSSL generates a signature in some specially encoded format? (ASN.1 etc.).

**Comment by Bolvach-BVM** [comment]
Hello @jforissier,

The keys are correct, considering I already use them sucessfully for encryption/decryption CA <-> TA. I mainly posted this because I was unsure if I was doing something wrong on the TA. I'm thinking, on the CA side, instead of using the signature call, to manually encrypt using the private key and then feed that as a signature to AsymmetricVerifyDigest. That, in theory, should work, right?

**Comment by jforissier** [comment]
I think it should (never tried it however).

**Comment by lorc** [comment]
Hu @Bolvach-BVM, I think you need to **decrypt** hash with the private key. This should produce signature. Receiver can **encrypt** this signature with public key to get the hash back. That could work, theoretically.  If there are no need for padding or somewhat like that.

**Comment by Bolvach-BVM** [comment]
Hello @jforissier ,
After further investigation, I discovered that openssl does indeed use ASN.1 for encoding. Is there any workaround I can take on the TA for this to work?

Hello @lorc,
I tried following your suggestion but it didn't work. I suppose it was related to padding.

**Comment by lorc** [comment]
@Bolvach-BVM, according to OpenSSL manual:

RSA_sign() signs the message digest m of size m_len using the private key rsa as specified in **PKCS#1 v2.0.** It stores the signature in sigret and the signature size in siglen. sigret must point to RSA_size(rsa) bytes of memory. Note that PKCS#1 adds meta-data, placing limits on the size of the key that can be used. See RSA_private_encrypt(3) for lower-level operations.

As I can see, you configure `TEE_AllocateOperation` with `TEE_ALG_RSASSA_PKCS1_V1_5_SHA1`.
So, OpenSSL uses v2.0 while TA uses v1.5. I believe, this causes your problem.

You can try `RSA_private_encrypt with `RSA_PKCS1_PADDING`. I think, this should do the trick.

**Comment by Bolvach-BVM** [comment]
@lorc you make a very good point. 

I actually have been trying to use ```RSA_private_encrypt``` via:

```c
RSA_private_encrypt(20, digest, signature, rsa, RSA_PKCS1_PADDING)
```
I can confirm that the digests being generated on the CA and the TA are _exactly_ the same and still ```AsymmetricVerifyDigest``` keeps failing.

**Comment by lorc** [comment]
@Bolvach-BVM, I vaguely remember problems with bytes order in public exponent. I encountered them on other system, when tried to export keys from one crypto engine and import it into another one.
Maybe, you are experiencing similar problem.

I think, best option there is to compare sources of OpenSSL and LibTomCrypt to ensure that they treat keys in the same way.

**Comment by Bolvach-BVM** [comment]
@lorc I'll probably look into that, but it seems weird as I can encrypt the communications CA <-> TA and decrypt them and it all works fine. I really only have problems on the signatures, which is why I'm finding this problem to be so mind-breaking.

**Comment by vchong** [comment]
@Bolvach-BVM If issue is resolved, it'd be nice if you could share the solution before closing so others with same the problem can reference this in the future. Thanks in advance!
