### ISSUE TITLE
Gprof with qemu

### ISSUE THREAD

**Issue by anwaymukherjee** [OP-TEE/optee_os#2158]
I am trying to profile the hello world application to understand the flow of execution. But after firing up qemu and running the executable, I could not find any profile data file inside /tmp/. I wounder what is the reason for this. This is what I found in the kernel log:
"__utee_gprof_init:159 gprof: could not allocate profiling buffer"

Could this be the reason? If yes, am I missing something?

Thanks

**Comment by jforissier** [comment]
> This is what I found in the kernel log:
> "__utee_gprof_init:159 gprof: could not allocate profiling buffer"
>
> Could this be the reason?

Yes. This line means that the `libutee` library, which contains the profiling code, needs some buffer size (here https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/arch/arm/gprof/gprof.c#L151-L163) that is bigger than the one that was put aside in the TA's `.bss` by the linker script (here: https://github.com/OP-TEE/optee_os/blob/master/ta/arch/arm/ta.ld.S#L94-L107).

I could not reproduce the issue with the upstream code. That is, I could build the QEMU OP-TEE stuff with `make -j9 CFG_TA_GPROF_SUPPORT=y CFLAGS_ta_arm32=-pg run`, and I get the following log on the secure console when I run `optee_example_hello_world`:

```
D/TC:0 tee_ta_init_pseudo_ta_session:293 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
D/TC:0 tee_ta_init_user_ta_session:637 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:0 tee_ta_init_user_ta_session:637 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:0 ta_load:317 ELF load address 0x103000
D/TC:0 tee_ta_init_pseudo_ta_session:293 Lookup pseudo TA 2f6e0d48-c574-426d-824e-40198cde5cac
D/TC:0 tee_ta_init_pseudo_ta_session:305 Open gprof
D/TC:0 tee_ta_init_pseudo_ta_session:319 gprof : 2f6e0d48-c574-426d-824e-40198cde5cac
D/TA:  TA_CreateEntryPoint:39 has been called
F/TA:  tee_user_mem_alloc:344: Allocate: link:[0x11a0a0], buf:[0x11a0b0:16]
D/TA:  TA_OpenSessionEntryPoint:68 has been called
I/TA:  Hello World!
D/TA:  inc_value:105 has been called
I/TA:  Got value: 42 from NW
I/TA:  Increase value to: 43
D/TC:0 tee_ta_close_session:403 tee_ta_close_session(0xe07fe70)
D/TC:0 tee_ta_close_session:422 Destroy session
I/TA:  Goodbye!
F/TA:  tee_user_mem_free:443: Free: link:[0x11a0a0], buf:[0x11a0b0:16]
D/TC:0 gprof_stop_pc_sampling:146 TA sampling stats: sample count=0 user time=207467 cntfrq=62500000 rate=0
D/TC:0 tee_ta_close_session:403 tee_ta_close_session(0xe07f430)
D/TC:0 tee_ta_close_session:422 Destroy session
D/TA:  TA_DestroyEntryPoint:50 has been called
D/TC:0 tee_ta_close_session:448 Destroy TA ctx
```

And there is indeed a file in `/tmp`:
```
root@Vexpress:/ ll /tmp
total 24
drwxr-xr-x    2 root     root             0 Feb 21 09:48 .
drwxrwxrwt   17 root     root           380 Feb 21 09:48 ..
-rw-------    1 root     root         22670 Feb 21 09:48 gmon-8aaaf200-2450-11e4-abe20002a5d5c51b.out
```


What I suggest is: enable the debug traces in `libutee.a` by building OP-TEE OS with `CFG_TEE_TA_LOG_LEVEL=3`. Then you will see how much gprof expects for its buffer. Then check how much is reserved in your TA. Maybe the formula in `ta.ld.S` is not quite right.

```
# Build command
$ make -j9 CFG_TA_GPROF_SUPPORT=y CFG_TEE_TA_LOG_LEVEL=3 CFLAGS_ta_arm32=-pg run
[...]
```
```
# QEMU NW console
root@Vexpress:/ optee_example_hello_world 
Invoking TA to increment 42
TA incremented value to 43
root@Vexpress:/ 
```
```
# QEMU secure console
D/TC:0 tee_ta_init_pseudo_ta_session:293 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
D/TC:0 tee_ta_init_user_ta_session:637 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:0 tee_ta_init_user_ta_session:637 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:0 ta_load:317 ELF load address 0x103000
I/TA:  gprof: initializing
D/TA:  __utee_gprof_init:155 TA text size: 45920, gprof buffer size: 62444
D/TC:0 tee_ta_init_pseudo_ta_session:293 Lookup pseudo TA 2f6e0d48-c574-426d-824e-40198cde5cac
D/TC:0 tee_ta_init_pseudo_ta_session:305 Open gprof
D/TC:0 tee_ta_init_pseudo_ta_session:319 gprof : 2f6e0d48-c574-426d-824e-40198cde5cac
D/TA:  TA_CreateEntryPoint:39 has been called
D/TA:  TA_OpenSessionEntryPoint:68 has been called
I/TA:  Hello World!
D/TA:  inc_value:105 has been called
I/TA:  Got value: 42 from NW
I/TA:  Increase value to: 43
D/TC:0 tee_ta_close_session:403 tee_ta_close_session(0xe07fe70)
D/TC:0 tee_ta_close_session:422 Destroy session
I/TA:  Goodbye!
D/TC:0 gprof_stop_pc_sampling:146 TA sampling stats: sample count=0 user time=134543 cntfrq=62500000 rate=0
D/TC:0 tee_ta_close_session:403 tee_ta_close_session(0xe07f430)
D/TC:0 tee_ta_close_session:422 Destroy session
D/TA:  TA_DestroyEntryPoint:50 has been called
D/TC:0 tee_ta_close_session:448 Destroy TA ctx
```
```
# Build console: check the reserved space for the gprof bufer in the TA
$ arm-linux-gnueabihf-nm optee_examples/hello_world/ta/8aaaf200-2450-11e4-abe2-0002a5d5c51b.elf | grep gprof_buf
00029063 B __gprof_buf_end
00019c70 B __gprof_buf_start
```

**Comment by anwaymukherjee** [comment]
Hi,

I followed your instructions. It seems like the buffer space allocation may not be the issue. Let me know whether I am reading it wrong.

Here is my kernel log O/P:

D/TC:0 tee_ta_init_user_ta_session:637 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:0 tee_ta_init_user_ta_session:637 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:0 ta_load:317 ELF load address 0x103000
I/TA:  gprof: initializing
D/TA:  __utee_gprof_init:155 TA text size: 47694, **gprof buffer size: 64856**
D/TC:0 tee_ta_init_pseudo_ta_session:293 Lookup pseudo TA 2f6e0d48-c574-426d-824e-40198cde5cac
D/TC:0 tee_ta_init_pseudo_ta_session:305 Open gprof
D/TC:0 tee_ta_init_pseudo_ta_session:319 gprof : 2f6e0d48-c574-426d-824e-40198cde5cac
D/TA:  TA_CreateEntryPoint:39 has been called
D/TA:  TA_OpenSessionEntryPoint:68 has been called
I/TA:  Hello World!
D/TA:  inc_value:105 has been called
I/TA:  Got value: 42 from NW
I/TA:  Increase value to: 43
D/TC:0 tee_ta_close_session:403 tee_ta_close_session(0xe07fe70)
D/TC:0 tee_ta_close_session:422 Destroy session
I/TA:  Goodbye!
D/TC:0 gprof_stop_pc_sampling:146 TA sampling stats: sample count=0 user time=226104 cntfrq=62500000 rate=0
D/TC:0 tee_ta_invoke_command:646 Error: ffff000a of 4
E/TA:  _gprof_write_buf:196 gprof: could not send gprof data (0xffff000a)
D/TC:0 tee_ta_invoke_command:646 Error: ffff000a of 4
E/TA:  _gprof_write_buf:196 gprof: could not send gprof data (0xffff000a)
D/TC:0 tee_ta_invoke_command:646 Error: ffff000a of 4
E/TA:  _gprof_write_buf:196 gprof: could not send gprof data (0xffff000a)
D/TC:0 tee_ta_invoke_command:646 Error: ffff000a of 4
E/TA:  _gprof_write_buf:196 gprof: could not send gprof data (0xffff000a)
D/TC:0 tee_ta_invoke_command:646 Error: ffff000a of 4
E/TA:  _gprof_write_buf:196 gprof: could not send gprof data (0xffff000a)
D/TC:0 tee_ta_invoke_command:646 Error: ffff000a of 4
E/TA:  _gprof_write_buf:196 gprof: could not send gprof data (0xffff000a)
D/TC:0 tee_ta_invoke_command:646 Error: ffff000a of 4
E/TA:  _gprof_write_buf:196 gprof: could not send gprof data (0xffff000a)
D/TC:0 tee_ta_invoke_command:646 Error: ffff000a of 4
E/TA:  _gprof_write_buf:196 gprof: could not send gprof data (0xffff000a)
D/TC:0 tee_ta_invoke_command:646 Error: ffff000a of 4
E/TA:  _gprof_write_buf:196 gprof: could not send gprof data (0xffff000a)
D/TC:0 tee_ta_close_session:403 tee_ta_close_session(0xe07f430)
D/TC:0 tee_ta_close_session:422 Destroy session
D/TA:  TA_DestroyEntryPoint:50 has been called
D/TC:0 tee_ta_close_session:448 Destroy TA ctx

Hence, gprof buffer size: 64856

Now, for the allocated buffer in TA:

anway@anway-Inspiron-7520:~/optee/build$ arm-linux-gnueabihf-nm ../optee_examples/hello_world/ta/8aaaf200-2450-11e4-abe2-0002a5d5c51b.elf | grep gprof_buf
000299cf B __gprof_buf_end
00019c70 B __gprof_buf_start
anway@anway-Inspiron-7520:~/optee/build

**Comment by anwaymukherjee** [comment]
Now, for the allocated buffer in TA:
/build$ arm-linux-gnueabihf-nm ../optee_examples/hello_world/ta/8aaaf200-2450-11e4-abe2-0002a5d5c51b.elf | grep gprof_buf
000299cf B __gprof_buf_end
00019c70 B __gprof_buf_start

**Comment by jforissier** [comment]
Size looks OK, and indeed you have no error "could not allocate profiling buffer".

Code 0xffff000a is TEE_ERROR_NOT_SUPPORTED so it looks like something was not re-built with gprof support. Try cleaning and re-building.

**Comment by anwaymukherjee** [comment]
Hello,

Took a bit of time to get back. Incidentally, the older version of OPTEE works seamlessly with gprof, while the new stable qemu branch fails to run gprof. I have tried quite a few times to build it without any success.
