### ISSUE TITLE
[HiKey] Android + op-tee suspend / resume and SPI sharing between the 2 worlds

### ISSUE THREAD

**Issue by ppeiffer** [OP-TEE/optee_os#2159]
Hi,

Here is more a question than an issue.
I have a setup running Android + OP-TEE on a HiKey board and I have a SPI device accessed by OP-TEE (so not Linux).
So all SPI config (init, conifg, start) is managed by "my" OP-TEE.

That works fine as long as I don't ask Linux world to go to suspend.
If I do this, when resuming the system, the SPI config is reset by Linux (because I let the SPI driver + PL022 driver in Linux kernel) meaning that my SPI config is lost on TEE side.

A quick fix is to disable SPI driver in Linux kernel, as I don't need it there. Suspend/resume works and I don't "loose" my SPI config on TEE side.

But I'm still wondering what is the right way to handle this ?
I understand that HiKey board being a development board, there is no hardware support for "secure-SPI" or any secure device whose access could be restricted to the secure world.
But anyway, in such cases what is the best way, if not the right way, to handle this ?
- Should I configure the SPI on Linux side and let TEE side only manage data transfert ? (It probably works but I don't think this is the right way ?)
- Or should protect TEE side from this, by providing kind of minimal Power Management support "a la linux" where in cpu_off_handler(), I save the SPI status and restore them during cpu_on_handler ?

Thanks,

P.

**Comment by lorc** [comment]
Hi @ppeiffer,

My opinion is that device should be exclusively used and managed by exactly one entity. So either it belongs to Linux or it belongs to OP-TEE.  Just imagine that it is really "secure" and Linux can't access it at all. 

So, as if  it is belongs to OP-TEE, then OP-TEE should manage its power state. 

Also, as Linux does not know that OP-TEE uses it, it can initiate transfer on its  own, which can interfere with OP-TEE transfers. Or Linux might want to reset controller state when OP-TEE does not expect this... So you'd better remove it from device tree, so Linux can't access it at all.

Things can become tricky if you want to use the same device in both Linux and OP-TEE... But as I understand, this is not your case.

**Comment by ppeiffer** [comment]
Ok, it makes sens, I'll remove SPI from Linux world.

Thanks !

P.
