### ISSUE TITLE
Translation fault in thread_irq_handler() reading value of thread_user_kcode_offset

### ISSUE THREAD

**Issue by jordanrh1** [OP-TEE/optee_os#2164]
After upgrading from 2.5.0 to 3.0.0 I'm seeing an occasional crash in OPTEE during OS boot. The platform is IMX6Q Sabre board. A data abort occurs when `thread_irq_handler()` tries to read the value of `thread_user_kcode_offset`. It looks like `thread_user_kcode_offset` is not mapped, but I cannot see the page tables so I'm not totally sure. The fault occurs on the instruction at `10a00558`:

```
10a00520 <thread_irq_handler>:
thread_irq_handler():
/home/jordanrh/optee_os/core/arch/arm/kernel/thread_a32.S:1004
10a00520:       f10c01c0        cpsid   aif
10a00524:       ee0d0f90        mcr     15, 0, r0, cr13, cr0, {4}
10a00528:       ee0d1f70        mcr     15, 0, r1, cr13, cr0, {3}
10a0052c:       ee1d0f30        mrc     15, 0, r0, cr13, cr0, {1}
10a00530:       e3100001        tst     r0, #1
10a00534:       0a00000c        beq     10a0056c <thread_irq_handler+0x4c>
10a00538:       e3c00001        bic     r0, r0, #1
10a0053c:       ee0d0f30        mcr     15, 0, r0, cr13, cr0, {1}
10a00540:       f57ff06f        isb     sy
10a00544:       ee120f30        mrc     15, 0, r0, cr2, cr0, {1}
10a00548:       e2400901        sub     r0, r0, #16384  ; 0x4000
10a0054c:       ee020f30        mcr     15, 0, r0, cr2, cr0, {1}
10a00550:       f57ff06f        isb     sy
10a00554:       e59f00c4        ldr     r0, [pc, #196]  ; 10a00620 <eret_to_user_mode+0x58>

10a00558:       e5900000        ldr     r0, [r0]        <--- Fault occurs here

10a0055c:       ee1c1f10        mrc     15, 0, r1, cr12, cr0, {0}
10a00560:       e0811000        add     r1, r1, r0
10a00564:       ee0c1f10        mcr     15, 0, r1, cr12, cr0, {0}
```

After the fault occurs and CPU goes to ABT mode, the MMU state is:
DFSR = 00000005 (Read . Translation/section)
DFAR = 10A337C0  (Address of thread_user_kcode_offset)

`thread_user_kcode_offset` is located in the BSS. Both `DFAR` and `R0` are consistent with this address.
```
10a337c0 g     O .bss   00000004 thread_user_kcode_offset
```

I can't read `10A337C0` with JTAG which seems consistent with fault, but I also can't read the translation tables.
```
TTBR0 = 10A5404A
TTBR1 = 10A5004A
```
There must be some kind of translation tables in effect, because I can see some code. Just poking around with JTAG it looks like the only mapped range is `0x10a00000 - 0x10a01000`. `0x10a00000` is the OPTEE load address.

I'm not sure why only one page is mapped, and I'm not sure whether thread_user_kcode_offset should be in this page.

**Comment by jenswi-linaro** [comment]
This relates to `CFG_CORE_UNMAP_CORE_AT_EL0` which is mainly used as a workaround for Meltdown, but it's by default always enabled as the overhead is minimal and it provides some additional security. With this enabled only one or two pages of OP-TEE core is `rx` mapped while in user mode. 

If you can provoke this problem easily with a debugger attached it would be helpful to know `LR_irq` and `CONTEXTIDR`.

Please try to add `write_contextidr(0)` in `core_init_mmu_regs()` (in `core/arch/arm/mm/core_mmu_v7.c`) and see if that helps.

**Comment by jordanrh1** [comment]
```
LR_irq = 10A0277A
CONTEXTIDR = C1C2F806
```

It doesn't look like `LR_irq` is pointing to valid code:
```
10a02744 <thread_set_exceptions>:
thread_set_exceptions():
/home/jordanrh/optee_os/core/arch/arm/kernel/thread.c:239
10a02744:       b538            push    {r3, r4, r5, lr}
10a02746:       4604            mov     r4, r0
read_cpsr():
/home/jordanrh/optee_os/core/arch/arm/include/arm32.h:506
10a02748:       f3ef 8500       mrs     r5, CPSR
thread_set_exceptions():
/home/jordanrh/optee_os/core/arch/arm/kernel/thread.c:243
10a0274c:       0783            lsls    r3, r0, #30
10a0274e:       d40a            bmi.n   10a02766 <thread_set_exceptions+0x22>
assert_have_no_spinlock():
/home/jordanrh/optee_os/core/arch/arm/include/kernel/spinlock.h:48
10a02750:       f01c fbfd       bl      10a1ef4e <have_spinlock>
10a02754:       b138            cbz     r0, 10a02766 <thread_set_exceptions+0x22>
10a02756:       4b08            ldr     r3, [pc, #32]   ; (10a02778 <thread_set_exceptions+0x34>)
10a02758:       2230            movs    r2, #48 ; 0x30
10a0275a:       4908            ldr     r1, [pc, #32]   ; (10a0277c <thread_set_exceptions+0x38>)
10a0275c:       4808            ldr     r0, [pc, #32]   ; (10a02780 <thread_set_exceptions+0x3c>)
10a0275e:       f008 f99d       bl      10a0aa9c <_assert_log>
10a02762:       f008 f9ad       bl      10a0aac0 <_assert_break>
thread_set_exceptions():
/home/jordanrh/optee_os/core/arch/arm/kernel/thread.c:247
10a02766:       01a4            lsls    r4, r4, #6
/home/jordanrh/optee_os/core/arch/arm/kernel/thread.c:246
10a02768:       f425 75e0       bic.w   r5, r5, #448    ; 0x1c0
/home/jordanrh/optee_os/core/arch/arm/kernel/thread.c:247
10a0276c:       f404 74e0       and.w   r4, r4, #448    ; 0x1c0
10a02770:       432c            orrs    r4, r5
write_cpsr():
/home/jordanrh/optee_os/core/arch/arm/include/arm32.h:514
10a02772:       f384 8f00       msr     CPSR_fsxc, r4
10a02776:       bd38            pop     {r3, r4, r5, pc}

10a02778:       10a2af10        .word   0x10a2af10       <-- LR points here
10a0277c:       10a2ae95        .word   0x10a2ae95

10a02780:       10a2b3e9        .word   0x10a2b3e9
```

**Comment by jordanrh1** [comment]
The issue has not repro'd again since I inserted `write_contextidr(0)` in `core_init_mmu_regs()`. Why does this fix the issue?

**Comment by jenswi-linaro** [comment]
Ah, nice. I noticed that `CONTEXTIDR` initial value is undefined and if it would happen to have the lowest bit set it would confuse the logic determining if the IRQ is while in userspace or not.

**Comment by jenswi-linaro** [comment]
Fixed by https://github.com/OP-TEE/optee_os/pull/2165
If you test it I can add a Tested-by tag if you like.

**Comment by jordanrh1** [comment]
Tested successfully on IMX6Q Sabre. Survived over 10 reboots without repro. Also tested IMX7 Dual successfully.

**Comment by jenswi-linaro** [comment]
Thanks, to add you're `Tested-by:` I need a mailaddress. It's a way of giving credits.

**Comment by jordanrh1** [comment]
jordanrh@microsoft.com

**Comment by jenswi-linaro** [comment]
Thanks, I'll add the tag.
