### ISSUE TITLE
ioctl question

### ISSUE THREAD

**Issue by maximouth** [OP-TEE/optee_os#2168]
Hi,

I have got a question about ioctl in OP-TEE.

When you call an *ioctl* in the user API with ``TEEC_InvokeCommand()`` or any other function, what is the entry point of the ioctl in the *secure OS* ?
I couldn't find any information about that in the documentation. Have you got a document about the ioctl in OP-TEE?

Thank you in advance.
Maxime

**Comment by lorc** [comment]
Hi @maximouth.

ioctl is the interface between clients and op-tee linux driver. OP-TEE OS itself does not receive any ioctls.

Interface between optee linux driver and OP-TEE OS  is defined in `optee_smc.h`  (SMC interface) `optee_msg.h` (command  buffers interface, which works  over SMC interface).

Probably you are looking for `entry_std.c` in OP-TEE OS. This is the entry point for calls like `InvokeCommand`.

**Comment by maximouth** [comment]
thank you for your answer :)

So when I am calling ``TEEC_InvokeCommand()`` the ioctl in it refers to the function ``entry_invoke_command()`` into ``entry_std.c`` .
Am i right?

**Comment by lorc** [comment]
Eventually, yes. There will be some processing in linux driver, and then it will invoke SMC which will lead to `entry_invoke_command()` call.

**Comment by igoropaniuk** [comment]
@maximouth just my two cents: look into `tee_ioctl`, if you want to understand what happens in tee/optee linux kernel kernel modules before reaching TEE.
```
static const struct file_operations tee_fops = {
	.owner = THIS_MODULE,
	.open = tee_open,
	.release = tee_release,
	.unlocked_ioctl = tee_ioctl,
	.compat_ioctl = tee_ioctl,
};
```
https://github.com/linaro-swg/linux/blob/optee/drivers/tee/tee_core.c#L674

**Comment by maximouth** [comment]
Oh thanks a lot, this will help me a lot!
have a great day :)

**Comment by maximouth** [comment]
Oh and I have one last question.
Where do you enter in the *secure monitor*, more specifictly, where do you call the ``SMC`` instruction ?

**Comment by jforissier** [comment]
Secure world may be entered from several locations (check TEE capabilities, setup shared memory...).
The invoke path goes through [`optee_do_call_with_arg()`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/tee/optee/call.c?h=v4.16-rc3#n124). There, `invoke_fn` is typically  [`optee_smccc_smc()`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/tee/optee/core.c?h=v4.16-rc3#n492).

**Comment by maximouth** [comment]
Okay, so when a client application want to use a Trusted App : 
-> ``TEEC_InvokeCommand()`` locate in ```tee_client_api.c```.
-> this will invoke an ``ioctl``,  locate ??.
-> this will call an SMC instruction locate in ```sm_as32.S```
-> then we are in secure world and we are in ??
-> and finally the ``entry_invoke_command()`` is call in ```user_ta_entry.c``` or ```entry_std.c``` to call ``TA_InvokeCommandEntryPoint()``.

sorry to bother you again.. I just want to be sure of what I am saying.

**Comment by igoropaniuk** [comment]
@maximouth 

Just to make everything clear, on ARMv7:

optee_client --> tee driver --> optee driver -> Secure Monitor --> OP-TEE OS core--> TA

1. **User application:** TEEC_InvokeCommand()
https://github.com/OP-TEE/optee_client/blob/master/libteec/src/tee_client_api.c#L555
Here `ioctl()` invocation occurs (it's right in TEEC_InvokeCommand implementation)
https://github.com/OP-TEE/optee_client/blob/master/libteec/src/tee_client_api.c#L600
2. **Linux Kernel/tee kmod:** ioctl is handled by tee_ioctl handler in `tee` kernel module, https://github.com/linaro-swg/linux/blob/optee/drivers/tee/tee_core.c#L674
3. **Linux Kernel/tee kmod:** Then we call `optee_infoke_func` of `optee` kernel module driver https://github.com/linaro-swg/linux/blob/optee/drivers/tee/tee_core.c#L674 (`tee` part),
https://github.com/linaro-swg/linux/blob/optee/drivers/tee/optee/call.c#L323 (`optee` `optee_infoke_func` implementation)
4. **Linux Kernel/optee kmod:** Then optee kmod: `optee_infoke_func()`->`optee_do_call_with_arg()`-> `__arm_smccc_smc()` (particular implementation of __arm_smcc_smc() you can find here https://github.com/linaro-swg/linux/blob/optee/arch/arm/kernel/smccc-call.S, which is a wrapper over `SMC` instruction)
5. **Secure Monitor**: handling of this SMC exception begins here https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/sm/sm_a32.S#L115
Here we save CPU context, perform some checks, if this SMC exception came from NormalWorld etc.
6. **OP-TEE OS Core**: and finally we get to `tee_entry_std()` https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/tee/entry_std.c#L517, which then calls `entry_invoke_command()`

**Comment by maximouth** [comment]
Wooh thank you.
I couldn't expect more than this.

thanks a lot. have a great day :D

**Comment by maximouth** [comment]
sorry to reopen this issue, but can you tell me if this is right or not ?

![appel_ta](https://user-images.githubusercontent.com/6785190/36858242-e5a22120-1d7a-11e8-82ba-f914a7c64719.png)

**Comment by jforissier** [comment]
The part between __arm_smccc_smc() and tee_entry_std() is not quite right. The `smc` instruction is called while the CPU is in non-secure kernel mode. It is a CPU instruction, not a function call. It makes the CPU change mode and branch to an exception vector. The details depend on the architecture (ARMv7, AArch32, Aarch64).

Also, `thread_enter_user_mode()` will not invoke the TA function directly, it will invoke `__utee_entry()` (in libutee.a) -> `entry_invoke_command()` -> `TA_InvokeCommandEntryPoint()`.

**Comment by lorc** [comment]
Partially. Secure Monitor works differently in case when there is ARM TF present or when OP-TEE uses own SM. In case of ARM TF, it initially handles all SMCs. OP-TEE only provides entry points to ARM TF, so ARM TF can call OP-TEE if it spots SMC than belongs to secure OS.

Also, main entry point to OP-TEE is in thread_a{32,64}.S. It is either `vector_std_smc_entry` or `vector_fast_smc_entry` depending on type of SMC call. `vector_std_smc_entry` calls `thread_handle_std_smc()` which allocates new thread which starts in `thread_std_smc_entry()` which calls `__thread_std_smc_entry()` which calls registered SMC handler. In most cases registered SMC handler is `tee_entry_std()`, but this is platform-dependent.

**Comment by maximouth** [comment]
Ok thank you :)
So this one is more like reality ?

![appel_ta](https://user-images.githubusercontent.com/6785190/36896218-0c7c5698-1e12-11e8-9748-dddecaf08684.png)

**Comment by lorc** [comment]
No quite. `vector_std_smc_entry()` and subsequent calls are in OP-TEE kernel. Secure Monitor is a separate entity. 
OP-TEE includes rudimentary Secure Monitor, which is often used on ARMv7 platforms. On never devices ARM TF is used.

 OP-TEE SM has own entry point `sm_smc_entry`. This is where call to SMC instruction lands. It then calls `sm_from_nsec()` which configures SM to exit into `vector_std_smc_entry()`. When SM exits into `vector_std_smc_entry()` it switches mode  from Secure Monitor (EL3) to Secure Supervisor (S-EL1), thus entering into OP-TEE kernel.

**Comment by maximouth** [comment]
![appel_ta](https://user-images.githubusercontent.com/6785190/36902731-d0ac568a-1e2b-11e8-8899-730f11cf6bf2.png)

so like this am I right ?

**Comment by lorc** [comment]
Yeah, something like that. I can't say for sure about "User Secure" part, because I'm not quite familiar with it. But all other parts are looking good.

**Comment by maximouth** [comment]
nice thank you!
have a good day then :)

**Comment by vchong** [comment]
Thanks for the flowcharts! They'll be helpful for many users.

**Comment by maximouth** [comment]
it's all yours :)

**Comment by maximouth** [comment]
Hello again,

I have got some update versions of the flowcharts if you want :)

But can you tell me if the last one seems ok please ?

Maxime
![appel_ta_reduce](https://user-images.githubusercontent.com/6785190/37458981-fda00586-2846-11e8-9b3e-0645fa471119.png)
![appel_ta_compress](https://user-images.githubusercontent.com/6785190/37458983-0176350e-2847-11e8-8edf-42ab08eac245.png)
![appel_ta_aller_retour](https://user-images.githubusercontent.com/6785190/37458990-07fc1c40-2847-11e8-9dbf-7db7a7a5348d.png)

**Comment by etienne-lms** [comment]
hello @maximouth,
This is a nice picture.... but please be careful. The flow, function names, register used etc.... may change in the future. This might be a precise picture of today's implementation but is so precise it is likely to become false in the future.

**Comment by akbarsaleemt** [comment]
Hi,
I have a doubt that how it find that this is optee trusted environment(Trust zone) or any other secure world

**Comment by maximouth** [comment]
Hi,
if you have a doubt, do the same things as I have done to make all of this.
Read the documentation in /OP-TEE/optee_os/documentation, and then go inside the code to follow every function call if you want to be sure of what the smc do. 

But as it was said, the function flow and the things done inside may have changed since I have done this.

**Comment by jbech-linaro** [comment]
Also, when exploring a new code base, my tip is to use GDB, set break points and look at the backtrace. For OP-TEE that is pretty easy to do for both kernel parts, as well as TEE core and TA's and if you are running GDB on the device itself, it's pretty easy to do the same for tee-supplicant and the host application. Just my 2 cents!

Btw, I'm closing this issue, since it's been thoroughly answered. Eventually I'll add a link to this particular post on our FAQ or so. Thanks @maximouth for your efforts!
