### ISSUE TITLE
Using more than 1Mb with TEE_Malloc

### ISSUE THREAD

**Issue by MRagot** [OP-TEE/optee_os#2178]
Hello,

I am writing a TA which needs big data blocks (more than 6Mb).
Invoking TEE_Malloc(...) for a size bigger than 32768 Kb fails.

Looking at the FAQ, it seems that having a 1Mb block with TEE_Malloc is easy modifying the user define TA header.
But, still, it will not be enough.
The FAQ indicates I have to change the MMU L1 mapping.

Is there some tutorial explaining how I can do that ?

Thanks.
Marcelin Ragot

**Comment by etienne-lms** [comment]
The size of the TA alloc pool is defined by your TA **user_ta_header_defines.h**: see `TA_DATA_SIZE`.

Note that the core firmware has a built_in max size for the memory available to TAs (and possibly few other internal stuff): check that `CFG_TA_RAM_SIZE` (**generated/conf.h**) is big enough on your platform for your TA needs. 

Maybe have a look at https://github.com/linaro-swg/optee_examples/blob/master/docs/TA_basics.md#5-ta-properties-basics, and feel free to comment if the info should be added/clarified in this doc.

**Comment by maxymedup** [comment]
Hi @etienne-lms,
Working on stable Qemu version with OP-TEE v3.0.0, I've tried several `TA_DATA_SIZE` configurations. Raising TA heap size up to 4MB triggers the following issue when TEE core initializes TA session: 

- Normal world:

```
root@Vexpress:/ optee_example_hello_world 
optee_example_hello_world: TEEC_Opensession failed with code 0xffff000c origin 0x3
```

- Secure world:

```
D/TC:0 tee_ta_init_pseudo_ta_session:293 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
D/TC:0 tee_ta_init_user_ta_session:637 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:0 tee_ta_init_user_ta_session:637 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
E/TC:0 alloc_pgt:281 5 page tables not available
D/TC:0 tee_ta_init_user_ta_session:644 res=0xffff000c
D/TC:0 tee_ta_open_session:563 init session failed 0xffff000c
```
Looks like the MMU reserves only 4 page tables of 1MB for the TA. I figured out updating `PGT_NUM_PGT_PER_PAGE` from 4 to 8 in pgt_cache.h allows me to set the TA heap size to at least 7MB (haven't tried more) with no error during `TEEC_Opensession` nor `TEE_Malloc` up to 7MB, as expected.

I'm not sure to fully understand the whole memory management system so is it the right way to do this ?

Thanks,
Maxyme

**Comment by maxymedup** [comment]
Any suggestion? 

#2090 is about allocating 10 MB and the answer was to increase the `CFG_NUM_THREADS` multiplier to 6 in **pgt_cache.h**.
But, #1523 had the same kind of issue (page tables not available) in the conext of Shared Memory, should I increase `CFG_NUM_THREADS` as well instead of the multiplier or `PGT_NUM_PGT_PER_PAGE`?

**Comment by etienne-lms** [comment]
Sorry for late reply.
No, do  not modify `PGT_NUM_PGT_PER_PAGE`. This reflect a cpu HW configuration that you cannot customize.

Indeed the current implementation of pgt_cache should be slightly reviewed to support big vmem for TAs when it is possible. Maybe start with some patch like proposed below. We will keep your issue open until we integrate a more clever fix.
```patch
--- a/core/arch/arm/include/mm/pgt_cache.h
+++ b/core/arch/arm/include/mm/pgt_cache.h
@@ -36,11 +36,15 @@ struct pgt {
 /*
  * Reserve 2 page tables per thread, but at least 4 page tables in total
  */
+#ifdef CFG_WITH_PAGER
 #if CFG_NUM_THREADS < 2
 #define PGT_CACHE_SIZE	4
 #else
 #define PGT_CACHE_SIZE	ROUNDUP(CFG_NUM_THREADS * 2, PGT_NUM_PGT_PER_PAGE)
 #endif
+#else
+#define PGT_CACHE_SIZE	32
+#endif /*CFG_WITH_PAGER*/
 
 SLIST_HEAD(pgt_cache, pgt);
 
```

**Comment by maxymedup** [comment]
Thanks, I'll try your patch until a fix is integrated in optee_os.

**Comment by etienne-lms** [comment]
Hi @maxymedup, please if it happens that you find a nice way to fix this, please feel free to propose it as a P-R.

The fact that "fixing" this issue is not complex but neither straightforward. OP-TEE is also designed to execute in small memories hence reserving page tables (by 4kB) may be expensive. We would need some platform configuration mean with a reasonable default value.
Proposals are welcome.
