### ISSUE TITLE
Downgrade Protection

### ISSUE THREAD

**Issue by nikoskoutr** [OP-TEE/optee_os#2179]
Hello,

I am investigating vulnerabilities of trusted execution environments. I have stumbled upon many "downgrade attacks", where attackers could install older versions of trusted applications, because the mechanism for rollback prevention was not used by the vendors of the devices.
Is there an implementation for rollback prevention? From what I have searched the signed header of TAs in OP-TEE does not have a version attribute.

Thank you for your insights,
Nick

**Comment by jenswi-linaro** [comment]
Actually there is a version field in the bootstrap TA format. This format is quite new. Together with `CFG_SECSTOR_TA=y` there is downgrade protection for installed TAs.

**Comment by nikoskoutr** [comment]
I see, thank you for your help!
Regards,
Nick
