### ISSUE TITLE
Questions about Shared Memory

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#2180]
I have the following questions about shared memory:

1) What is the difference between allocate and register shared memory ?

2) If I allocated a shared memory (type input) and invoked a TA, and then came back to the normal world, will the allocation stay in place until I destroy the context ? In other words, can I invoke the TA again using the previous allocated shared memory ?

3) Similar to question 2, if I allocate a shared memory (type output) and invoked a TA (which wrote something to the shared memory), and then came back to normal world, can I invoke the TA again so that it can write to the same shared memory ?

Also to double check, I'm assuming the benefit of shared memory is that only the address of the shared memory is passed between worlds instead of copying the buffer back and forth.

Thanks

**Comment by maximouth** [comment]
Hello :)

For the first point you can check this document section 3.2.4. Shared Memory it is well explain.

For the two others I will say yes for both, see the section 5.2 and 6 of the same document, you will see some examples about this.

The memory is allocate until you call the function ``TEEC_ReleaseSharedMemory``.

[TEE_Client_API_Specification-V1.0_c.pdf](https://github.com/OP-TEE/optee_os/files/1793423/TEE_Client_API_Specification-V1.0_c.pdf)
