### ISSUE TITLE
load elf files from NW an execute them in SW  

### ISSUE THREAD

**Issue by zatkh** [OP-TEE/optee_os#2183]
I am writing a code to load an arm64 executable binary (e.g elf format) from NW to SW and then execute it inside SW. Something similar to linux execve but in tz. I am not sure if I can implement it using optee?

**Comment by jforissier** [comment]
Hi @zatkh ,

What you are describing exists already, it's called a Trusted Application ;-) OP-TEE TAs are ELF binaries (with an additional header). They are typically loaded from NW and executed in SW.

If, however, you mean running a Linux executable unmodified in the OP-TEE OS environment, then it is not possible for several reasons. One reason is, OP-TEE OS system calls have nothing in common with the Linux ones. So, I don't see how OP-TEE could help you achieve what you are asking.

What problem are you trying to solve? What are you trying to accomplish? Sandboxing (isolation)? In this case, running a virtual machine would be the way to go.

**Comment by zatkh** [comment]
sorry I was not clear. I know optee loads ta elf files but my problem is about porting unmodified binaries in TZ. I was hoping to load untrusted elf files to a shared memory between sw and nw and then execute them but i think optee can not help me in this case.
