### ISSUE TITLE
Shared memory between TA and multiple clients

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#2185]
I have a requirement where multiple clients (hosts) have shared memory setup a with a TA. The TA is marked with the flags: 
>(TA_FLAG_SINGLE_INSTANCE | TA_FLAG_INSTANCE_KEEP_ALIVE | TA_FLAG_MULTI_SESSION | TA_FLAG_EXEC_DDR)

I am trying to make the following scenario work. Assume two clients for a moment, both using `TEEC_AllocateSharedMemory`. At first both clients inform the TA of the shared memory allocated and the TA keeps a copy of the buffer address (from `params.memref.buffer`) from both clients and saves it into static memory. Client1 uses the argument type TEEC_MEMREF_PARTIAL_INPUT and client2 uses TEEC_MEMREF_PARTIAL_OUTPUT.

Then later client 1 makes a request to the TA giving it some data via shared memory. I want the TA to be able to perform some computation on it and copy the result into the shared buffer address stored for client2. But it seems when TA tries to access the stored buffer address for client1 or client2, the TA panics and crashes.

>ERROR:   TEE-CORE: user TA data-abort at address 0x40200000 (translation fault)
ERROR:   TEE-CORE:  esr 0x92000006  ttbr0 0x100003f0710e0   ttbr1 0x00000000   cidr 0x0
ERROR:   TEE-CORE:  cpu #7          cpsr 0x20000100
ERROR:   TEE-CORE: x0  0000000040200000 x1  0000000040200000
ERROR:   TEE-CORE: x2  0000000000000000 x3  00000000ffffffff
ERROR:   TEE-CORE: x4  0000000000000001 x5  0000000040200000
ERROR:   TEE-CORE: x6  00000000ffffffff x7  0000000000000020
ERROR:   TEE-CORE: x8  0000000000000000 x9  0000000000000000
ERROR:   TEE-CORE: x10 000000004000851c x11 000000003f053680
ERROR:   TEE-CORE: x12 0000000040015000 x13 00000000400057b0
ERROR:   TEE-CORE: x14 0000000000000000 x15 0000000000000001
ERROR:   TEE-CORE: x16 000000003f00decc x17 0000000000000000
ERROR:   TEE-CORE: x18 0000000000000000 x19 00000000fffffff0
ERROR:   TEE-CORE: x20 0000000040005660 x21 0000000000000000
ERROR:   TEE-CORE: x22 0000000000000000 x23 0000000040015f82
ERROR:   TEE-CORE: x24 0000000000000073 x25 00000000400055c0
ERROR:   TEE-CORE: x26 00000000400054fc x27 0000000040005660
ERROR:   TEE-CORE: x28 000000000000002a x29 0000000040005300
ERROR:   TEE-CORE: x30 000000004000f694 elr 000000004000ef84
ERROR:   TEE-CORE: sp_el0 00000000400052d0
ERROR:   TEE-CORE: Status of TA 8aaaf200-2450-11e4-abe20002a5d5c51b (0x3f053d70) (active)
ERROR:   TEE-CORE: - load addr : 0x40006000    ctx-idr: 1
ERROR:   TEE-CORE: - code area : 0x3f200000 1130496
ERROR:   TEE-CORE: - stack: 0x3f314000 stack:22528
DEBUG:   [0x0] TEE-CORE:user_ta_enter:525: tee_user_ta_enter: TA panicked with code 0xdeadbeef
DEBUG:   [0x0] TEE-CORE:tee_ta_invoke_command:564:   => Error: ffff3024 of 3
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:318: tee_ta_close_session(0x3f053f20)
DEBUG:   [0x0] TEE-CORE:tee_ta_close_session:337:    ... Destroy session

I was trying to follow this [code](https://github.com/OP-TEE/optee_test/blob/a4653559d989d5006f67f4498be4cb090be12f79/host/xtest/xml/include/xml_datastorage_api.h#L778).

I want to ask:
1) when a client shares a buffer address from `TEEC_AllocateSharedMemory` with a TA, is the address valid in the TA only for the duration of command invocation ?

2) If answer to (1) is yes, then what would is a way to shared a buffer address with a  TA that remains valid for the TA even after the command has returned. I can keep the buffer address stored in TA memory using KEEP_ALIVE and want to access it later in a different command. Is the way used in this [question](https://github.com/OP-TEE/optee_os/issues/788) the way to do it ( `TEEC_RegisterSharedMemory` with argument type `TEEC_MEMREF_WHOLE`) ?

3) Is there a better way to achieve this requirement ?
> Client 1 --> input --> TA --> [some computation] --> output --> Client 2 

Right now I am using input shared memory from client1 and output shared memory from client 2. I want to avoid copying buffers back and worth, so I used shared memory. I was assuming client 2 in normal world would have to check status of shared memory to see if there is a result. 

4) I understand that there is a RPC mechanism used by OPTEE kernel, but I'm not sure if that can be used by a TA to invoke a random client in the normal world to give some result.

Thanks

**Comment by jenswi-linaro** [comment]
1. Yes
2. There's nothing in the specifications supporting this
3. I haven't tested this, but it could be worth trying to setup normal shared memory between client1 and client2 which you _after_ that register as shared memory. Note that for this to have the desired effect the "NEW SHM" patches has to be used in the kernel.

Each time a TA is invoked supplied memory parameters are mapped without any regard towards earlier mappings. This means that only what's supplied and memory parameters in a particular invoke is available. Depending on supplied parameters the parameters can be mapped using different addresses during different invoke.
