### ISSUE TITLE
Error while building the optee_test

### ISSUE THREAD

**Issue by vabbarap** [OP-TEE/optee_os#2186]
Hi,
I am trying to build the optee_test and ran these
/scratch/devel/optee/optee_test> % export TA_DEV_KIT_DIR=$PWD/../optee_os/out/arm-plat-zynqmp/export-ta_arm32
/scratch/devel/optee/optee_test> %  export TA_CROSS_COMPILE=$PWD/../toolchains/aarch32/bin/arm-linux-gnueabihf-
 /scratch/devel/optee/optee_test> %  export HOST_CROSS_COMPILE=$PWD/../toolchains/aarch32/bin/arm-linux-gnueabihf-
/scratch/devel/optee/optee_test> %  export TEEC_EXPORT=$PWD/../optee_client/out/export

In file included from /usr/include/sys/stat.h:106:0,
                 from /scratch/devel/optee/optee_test/host/xtest/install_ta.c:19:
/usr/include/bits/stat.h:106:31: error: expected identifier or ‘(’ before ‘[’ token
     __syscall_slong_t __unused[3];
                               ^
make[1]: *** [/scratch/devel/optee/optee_test/out/xtest/install_ta.o] Error 1

Thanks
Venkatesh

``

**Comment by vchong** [comment]
Duplicate: https://github.com/OP-TEE/optee_test/issues/265
