### ISSUE TITLE
query: android keymaster with optee

### ISSUE THREAD

**Issue by gchww** [OP-TEE/optee_os#2191]
I have ported optee on my android platform, now I need to accomplish keymaster ta on optee.
1. where can I get help on this topic if there are any reference or any other helpful information?
2. in android keymaster, it uses ocb ae(Authenticated Encryption) functions, but there is no ocb cipher in optee libtomcrypt,
a. is there any plan to add ocb in optee ?
b. which cipher I can use to replace ocb in keymaster?
c. any other advice on this?
thanks

**Comment by jbech-linaro** [comment]
Hi @gchww 

> where can I get help on this topic if there are any reference or any other helpful information?

AOSP keymaster is a work that just recently has been started from our side. It's in an early stage, so there is no code written so far (more in a study/design phase etc), but you will probably see code drops for this over the coming months or so. It's a pretty big task, so in case you are interested in helping out developing some parts of it we are more than happy involve you in this.


> in android keymaster, it uses ocb ae(Authenticated Encryption) functions, but there is no ocb cipher in optee libtomcrypt,

Are you sure about this, from what I've seen they only mention `AES-GCM` as an AE on their [page](https://source.android.com/security/keystore/features#primitives). Can you point me to the page where they say that `OCB` is required?

> a. is there any plan to add ocb in optee ?

Most likely not, since it is an patented algorithm/mode.

**Comment by jbech-linaro** [comment]
Ah, seconds after answering you I found
```
ocb.c
ocb_utils.cpp
ocb_utils.h
```
in one of their [releases](https://android.googlesource.com/platform/system/keymaster/+/android-8.1.0_r11). We have to figure out how to deal with this.

**Comment by jforissier** [comment]
> 2. in android keymaster, it uses ocb ae(Authenticated Encryption) functions, but there is no ocb cipher in optee libtomcrypt,

What about https://github.com/OP-TEE/optee_os/tree/master/core/lib/libtomcrypt/src/encauth/ocb?

**Comment by jbech-linaro** [comment]
> in android keymaster, it uses ocb ae(Authenticated Encryption) functions, but there is no ocb cipher in optee libtomcrypt,
> What about https://github.com/OP-TEE/optee_os/tree/master/core/lib/libtomcrypt/src/encauth/ocb?

I believe he is referring to the GP-spec, since this will be implemented as a TA (mainly I guess). I think they only define AES-GCM and AES-CCM. I don't think we have made an extensions to that so far.

**Comment by gchww** [comment]
@jforissier got it. My local copy(tag 2.5) is not the latest version. 
from another side, I am not sure whether there are any ocb related GP interfaces. As jbech saying, keymaster is a ta with GP interface. 
Another related question here, according to android requirement, the bootloader should tell the tee (in fact I think should be keymaster ta) os_version and os_patchlevel(needed in keymaster configure function with keymaster version 2) located in bootimage header before booting to linux, but linux kernel is not running now, how to load and run the ta to get the os_version and os_patchlevel parameters or are there any other ways to implement this requirement, do you have any advice? 
In fact, I did some work on keymater ta. Taking trusty keymaster as an reference, it reuse much code from android keymaster, looking simple and efficient, because trusty support cpp code. Optee does not support cpp code or cpp library, so I have to do much work on convert the cpp code to c code. not efficient.

**Comment by jbech-linaro** [comment]
This is not really help as, such, but these are my notes of what needs to be looked into:
```
- Certificates
  - Export: Public keys in x.509
  - Import: Pub/priv DER encoded PKCS#8 as well as raw bytes for symmetric keys.
- Asymmetric key generation
- Access control on keys
  - Authorization list attached to the key blob.
  - Keymaster_key_characteristics_t: divides the authorization list into software vs hardware forced.
- Version binding: Keys should be bound to a certain version of the system (Major/Minor).
  - Keys needs to be upgradable.
  - Boot image needs to contain the OS version and patch level. Must be passed to the TEE before the REE OS launches.
- Authorization Tags: More or less a list of all features supported.
- Crypto: All modes needed.
- Client binding: Bind a certain client app to a certain key.
- Expiration: Seems to rely on non-secure world, get impression that this is an optional feature.
- Root of Trust binding: HUK needs to play a role in all keys managed by Keymaster
- Standalone keys: Could this leverage Etienne's SKS work?
- Velocity: A way to limit how often a key can be used.
  - Timestamps tied to the key. Q: This would be secure time otherwise it’s not super useful.
  - Number of uses since boot: I.e, you can only use a key X times per boot.
- RNG re-seed: Seems like an optional thing. Can be used from NW to give entropy to the RNG in secure world.
- Attestation:
  - Rely on x.509 support.
  - ID attestation: Optional feature (use IMEI or similar as proof to hardware identity). Also needs factory provisioning.
- Gatekeeper <-> Keymaster <-> Fingerprint
  - Must share a secret key to authenticate message from one another, AuthToken HMAC key.
  - This must be generated every boot and shared with all three of them.
```

**Comment by gchww** [comment]
will you release it openly? and how to ?

**Comment by jbech-linaro** [comment]
> will you release it openly? and how to ?

Absolutely, if there is no requirement for NDA's, then we are always releasing everything in the open. In this particular case I'm not aware of any NDA's. How to? Published as patches here in the GitHub/OP-TEE project.

**Comment by gchww** [comment]
thank both of you @jbech-linaro and @jforissier .

**Comment by vchong** [comment]
@gchww as @jbech-linaro had mentioned earlier, if you're interested in contributing to the implementation of keymaster support on op-tee, please reach out and send an email to victor.chong@linaro.org and joakim.bech@linaro.org. Thanks!

**Comment by casionwoo** [comment]
@vchong 
Does keymaster working well on optee currently?
I'm working on optee with virtualization. and for the time being, xtest is working on both side.
and VMs are linux and android. I checked from Android side that keymaster and gatekeeper could have a connection but when I check keymaster_test, it failed a lot.

I want to ask that in your android + optee environment, does keymaster working well?

**Comment by vchong** [comment]
@casionwoo It's still WIP so no support currently on master. Which platform and Android version are you on? Anyway, if you don't have hardware backed keystore atm, you'll default to the software only implementation which doesn't pass all the tests. In any case, `keymaster_test` is old (V0). You should probably use `VtsHalKeymasterV3_0Target` instead.

**Comment by casionwoo** [comment]
@vchong 
I'm working on renesas platform and Android-Oreo version I'm using.
And BSP includes optee version 2.6.0

And I'm trying to test keymaster with **keymaster_test** and it failed a lot even though xtest success almost only 2 test failed.

That was the reason I asked keymaster is supported fully.
And can I ask where can I get **VtsHalKeymasterV3_0Target**?

**Comment by casionwoo** [comment]
@vchong 
I found this  [link](https://github.com/CypherOS/hardware_interfaces)

is it right? then can I ask how to build it?

**Comment by vchong** [comment]
> And I'm trying to test keymaster with keymaster_test and it failed a lot even though xtest success almost only 2 test failed.

`keymaster_test` and `xtest` are not related. They're 2 different 'things', at least at this point in time, so the results of one aren't indications for the results of the other.

> Do you think keymaster_test is suitable for 2.6.0 optee version?

As mentioned above, `keymaster_test` is old, so not suitable for use. Also as mentioned above, there's currently no keymaster support currently on master, so obviously not for 2.6.0. When master supports keymaster later in the future, you can maybe try to back-port the relevant patches from master onto 2.6.0 if you're stuck on 2.6.0, but if the patches don't apply cleanly, you'll have to resolve the differences.

> commit of keymaster is 9393e7ae8f8c5f4b9446eac98d76ff63786c1193

Where did you get your repo from? What's the git url/remote? It's not enough to just give a commit id! And there's no such commit for the `keymaster_test` repo upstream.

> And can I ask where can I get VtsHalKeymasterV3_0Target?

https://android.googlesource.com/platform/hardware/interfaces

> I found this link
> is it right? then can I ask how to build it? and which branch I can use?

No! Always use upstream (https://android.googlesource.com) or reliable mirrors if you know of any. You can't just use any arbitrary repo found online without knowing where it came from and what it's for! I don't know your platform so can't really tell you how to build it. Generally, e.g. for hikey, https://android.googlesource.com/platform/hardware/interfaces is included in the repo manifest and part of the AOSP source tree. The branch to use is also indicated in the manifest. If it's not built as part of the AOSP build, then the command to build it manually is generally `make <flags depending on your platform, if necessary> VtsHalKeymasterV3_0Target` from the root of the source tree.

Seems like you would first need to familiarize yourself with building AOSP for your platform, and how to add components to it if required.

**Comment by casionwoo** [comment]
@vchong 

I build vts in AOSP with **make vts -j** and tried **vts-tradefed** and **run vts-hal --module VtsHalKeymasterV3_0Target**
and here's logcat from keymaster (this is the command to see logcat **logcat -s "OpteeKeymaster" &**) 
![image](https://user-images.githubusercontent.com/3404383/43905356-3bc22b00-9bf1-11e8-92c3-44fb5c2e122b.png)

is it normal? and you said keymaster is WIP. do you have a same log for keymaster with me?

**Comment by jbech-linaro** [comment]
@casionwoo the work is WIP and @vchong  has been able to successfully run VTS standalone. Having that said, we are trying to stabilize things so that we can share it easily with others. We will hopefully have some available for others to try not too far into the future. So, to avoid spending time on figuring out issues, I think it is better if we wait until have shared a stable setup that we have tested a bit more in detail.

**Comment by casionwoo** [comment]
@jbech-linaro Yes it's worth for waiting @vchong.
Thanks

**Comment by vchong** [comment]
@casionwoo sorry for the delay and thank you for your patience! We made a presentation regarding keymaster and gatekeeper recently. Please see https://connect.linaro.org/resources/yvr18/yvr18-414 for details. Hope that helps.

**Comment by gchww** [comment]
@vchong
hi, victor, I tried the git command
“git clone https://github.com/linaro-swg/optee_android_manifest -b yvr18”
in the slides, but there is no branch named yvr18, so were there any changes on the branches ? or have I no permission to access the branch?
In addition, can you give more detailed information about the implementation, for example, where is the source code for the hal, which branch optee repository should use( I think maybe kmgk)? any dependencies on the linux driver commits?
thanks

**Comment by igoropaniuk** [comment]
Hi @gchww,

I guess you should use this one https://github.com/linaro-swg/optee_android_manifest/tree/optee_kmgk_3.3.0

Regards,
Igor

**Comment by vchong** [comment]
@gchww `yvr18` is a tag, not branch. You should still be able to clone it.
`optee_kmgk_3.3.0` is a branch. It's corresponding tag is `3.3.0`. They're newer than `yvr18`, although not by much.
Hal source code: https://github.com/linaro-swg/kmgk
The branch/tag/commit ID of op-tee repositories used can be found in the manifest. For `optee_kmgk_3.3.0`, it corresponds to the `3.3.0` tag also.
No extra dependencies on the driver other than the standard TEE one required for op-tee.

**Comment by jforissier** [comment]
@vchong are you sure you can use a tag with repo? I think I tried and it failed and I concluded that I had to create a branch with the same name as the tag for things to work easily. That is why I create such branches when I make OP-TEE releases, i.e, https://github.com/OP-TEE/manifest/branches.
My repo skills are limited though, so it's quite possible I'm missing something...

**Comment by vchong** [comment]
@jforissier In this case, the tag is just used to clone https://github.com/linaro-swg/optee_android_manifest to get the manifest. We're not `repo init`-ing directly on https://github.com/linaro-swg/optee_android_manifest, but to the official aosp manifest repo instead. E.g.

```
repo init -u https://android.googlesource.com/platform/manifest -b <some branch>
repo sync -m <the manifest we just git cloned>
```

**Comment by jforissier** [comment]
@vchong OK I see, thanks for explaining.

**Comment by vchong** [comment]
@jforissier you're welcome. Forgot to mention that the build script actually copies the cloned manifest to `.repo/manifests/` before `repo sync`-ing, so it's sort of used as a stable/release manifest. Maybe not the best/cleanest way to go about things but that's the way it is for now.
