### ISSUE TITLE
'eth0' in OP-TEE Rich OS missing

### ISSUE THREAD

**Issue by srjrjjr** [OP-TEE/optee_os#2194]
Dear All,

I am trying to get the device 'eth0' up and running so that I can connect my Host machine to QEMU for some client server Applications. Unfortunately although under "common.mk" there is a line:

```
QEMU_USERNET_ENABLE		?= y

	@if [ "$(QEMU_USERNET_ENABLE)" = "y" ]; then \
		echo "slink /etc/rc.d/S02_udhcp_networking /etc/init.d/udhcpc 755 0 0" \
		>> $(fl); \
	fi

```

Still, the device eth0 does not pop up on my client Emulator. Can someone please help?

Thanks.

**Comment by igoropaniuk** [comment]
Hello @srjrjjr 

Just FYI, this option enables SLiRP user networking, which has some limitations and probably won't fit in your setup:

* there is a lot of overhead so the performance is poor
* in general, ICMP traffic does not work (so you cannot use ping within a guest)
* on Linux hosts, ping does work from within the guest, but it needs initial setup by root
* the guest is not directly accessible from the host or the external network

Check  https://wiki.qemu.org/Documentation/Networking#User_Networking_.28SLIRP.29 for additional details

**Comment by srjrjjr** [comment]
Hi @igoropaniuk ,

To be honest the user networking mode is not what I want but I thought that should be the easiest to setup. My attempt to have a "tap" device has failed as I do not know where to place the scripts qemu-ifup and qemu-ifdown mentioned in https://en.wikibooks.org/wiki/QEMU/Networking.
OPTEE sources have a  "gen_rootfs" and "qemu" folder. I placed my scripts in gen_rootfs/etc/network/ and updates the filelist.txt. However I can#t get these scripts inside my QEMU image.

Could you point out some links regarding these or advise me from your experience?

Thanks
