### ISSUE TITLE
apt-get command not found

### ISSUE THREAD

**Issue by geetayadav** [OP-TEE/optee_os#2201]
Hi,
I have followed  https://github.com/OP-TEE/build to build OPTEE on Raspberry Pi 3. I can execute xtest. But I got the problem in installing anything else "apt-get command not found." Does it not support apt-get? Why?
Thanks 
Geeta

**Comment by jforissier** [comment]
Hi @geetayadav,

The root filesystem created by the OP-TEE build environment is quite minimal (uses busybox) and does not contain `apt` or `apt-get`.

**Comment by geetayadav** [comment]
Can we replace it with other rootfs?

**Comment by lorc** [comment]
You can use  any rootfs you want. Just build and install optee client there.
Also make sure to run `tee-supplicant` before calling any TAs.

**Comment by vchong** [comment]
See https://github.com/OP-TEE/build/blob/master/docs/rpi3.md#57-other-root-filesystems-than-initramfs-based for possibly helpful reference.

**Comment by geetayadav** [comment]
Thank you, I will follow it.
