### ISSUE TITLE
Including static libraries on a TA

### ISSUE THREAD

**Issue by PedroRibeiro95** [OP-TEE/optee_os#2202]
Hello,

For a TA I'm developing I'll need to add a static library, more specifically SQLite 3. I know that SQLite requires many libc functions that are not available on the Secure World (namely IO) and, as such, I'm trying to get it to compile by also linking the libraries containing those needed functions. When it compiles, the idea is for me to manually add the functions that I need by making use of the Global Platform API.

I already compiled libsqlite3.a for ARM. If I statically add it to the TA Makefile:

> LDADD += -lsqlite3 -L/home/pedro/devel/optee/optee_examples/HCEMobile/libs

I get the missing libc functions:

> /home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `dlclose@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `__fxstat64@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `utimes@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `strcmp@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `fchmod@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `free@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `close@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `readlink@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `memset@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `read@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `memmove@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `fcntl@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `getenv@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `getcwd@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `gettimeofday@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `__xstat64@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `strcspn@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `lseek64@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `fdatasync@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `mmap64@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `geteuid@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `malloc@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `ftruncate64@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `mkdir@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `munmap@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `dlsym@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `write@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `sysconf@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `memcmp@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `rmdir@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `dlerror@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `memcpy@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `strerror@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `posix_fallocate64@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `open64@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `time@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `strncmp@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `unlink@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `access@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `mremap@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `fchown@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `strlen@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `getpid@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `__lxstat64@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `localtime_r@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `qsort@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `realloc@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `dlopen@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `usleep@GLIBC_2.17'
/home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so: undefined reference to `__errno_location@GLIBC_2.17'

It also specifies which libraries I'm missing:

> /home/pedro/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: warning: libdl.so.2, needed by /home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so, not found (try using -rpath or -rpath-link)
/home/pedro/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: warning: libc.so.6, needed by /home/pedro/devel/optee/optee_examples/HCEMobile/libs/libsqlite3.so, not found (try using -rpath or -rpath-link)

By adding the libc and libdl libraries, as well as some other libraries required by these, to the Makefile:

> LDADD += -ldl -L/home/pedro/devel/optee/toolchains/aarch64/aarch64-linux-gnu/libc/usr/lib
LDADD += -lc -L/home/pedro/devel/optee/toolchains/aarch64/aarch64-linux-gnu/libc/lib
LDADD += -L/home/pedro/devel/optee/toolchains/aarch64/aarch64-linux-gnu/libc/usr/lib

The program almost compiles, but is unable to find some other libraries:

> /home/pedro/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: cannot find /lib/libc.so.6
/home/pedro/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: cannot find /usr/lib/libc_nonshared.a
/home/pedro/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: cannot find /lib/ld-linux-aarch64.so.1

I know it's not good practice to add much code to the TA, but for the scope of this work (and the time I have) I really just need the TA to compile. I feel like I'm really close to get this working but I'm probably missing some steps. I would appreciate if you could give me some guidance.

Best regards,
Pedro Ribeiro

**Comment by jforissier** [comment]
Hi @PedroRibeiro95 ,

I'm sorry to say, you think you're close but you're not. You're following the wrong path. You can't use most libraries that come with the compiler, because they're built for Linux. libc will ultimately invoke Linux system calls, so that won't work if the OS is not Linux. OP-TEE OS is not Linux, so that won't work. Moreover, TAs can't use shared libraries (.so) yet.
Your only chance of making this work is to modify sqlite3.c to call TEE_* instead of the POSIX file functions. For instance replace `open()` or `fopen()` with `TEE_OpenPersistentObject()` etc.

**Comment by PedroRibeiro95** [comment]
Hello @jforissier,

Thank you very much for your time. So I assume that even copying the missing functions to the TA would not work, correct?

**Comment by jforissier** [comment]
Correct.
