### ISSUE TITLE
Any method to disallow a PTA called from REE?

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#2206]
We hava a PTA provides device unique key to some TAs for encryption. For security consideration, we don't want REE to access the PTA to get the key. But in current optee design, it seems there's no TA flag or function we can use for PTA to ensure that ? I found check_client() func in tee_ta_manager.c, but it can't meet our requirement.

**Comment by jenswi-linaro** [comment]
The identity of the client is stored in the session struct. The PTA can check that sess->clnt_id.login is `TEE_LOGIN_TRUSTED_APP`.

**Comment by tiger20081015** [comment]
@jenswi-linaro Thanks for your reply, it works!
