### ISSUE TITLE
Compiling library using Global Platform API

### ISSUE THREAD

**Issue by Bolvach-BVM** [OP-TEE/optee_os#2209]
Hello,

I'm trying to add an external library to a TA and I had to change some calls in the source code to use the Global Platform's API. I'm now trying to compile the library, by linking it against libutee, and I'm getting an undefined reference to

> trace_level
trace_ext_prefix

Where are these supposedly defined?

Thank you.

**Comment by jforissier** [comment]
Hi @Bolvach-BVM,

These two symbols are defined by the TA itself, in file [`user_ta_header.c`](https://github.com/OP-TEE/optee_os/blob/master/ta/arch/arm/user_ta_header.c#L35-L37). This file is automatically added to the build of the main executable by the TA dev scripts.

What steps are you following to create you (static) library? It should be an archive (`libfoo.a`) and it should not cause any undefined references. You should link `libutee` etc. only with the main executable (TA), there is no need to add it to your library. In other words, your library Makefile should look like:
```
LIBNAME = libfoo
-include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
```
...and your `sub.mk` would be like:
```
global-incdirs-y += include
srcs-y += foo.c
```
HTH.

**Comment by Bolvach-BVM** [comment]
Hello @jforissier,

I'm trying to compile the library separately and then adding it to ta_dev_kit.mk. I'm doing this because compiling with the flags used by OP-TEE is not possible as the library does not follow ISO C. As such, I'm compiling the library using its Makefile, but altering it as to use aarch64 compiler and by linking it against libutee.
