### ISSUE TITLE
is Secure Storage resilient to TEE updates ?

### ISSUE THREAD

**Issue by b-allibert** [OP-TEE/optee_os#2210]
Hi,

I have a quick question about secure storage implementation (in case my Trusted Applications are using secure storage). If, at some point, I'd like to update the TEE to get latest OP-TEE features, will secure storage content still be accessible for these TAs after the TEE update ?
Assumptions : 
  - tee_otp_get_hw_unique_key() and tee_otp_get_die_id() implementations remain the same across this update.
  - the secure storage build configuration (CFG_REE_FS=y) for the 2 TEEs builds is the same.

Thanks
Regards
Bastien

**Comment by etienne-lms** [comment]
Hello Bastien,
Hmm.. embarrassing. Some version increase were compatible but it is likely that moving to 3.0.0 would break some old old 2.x. I could not tell,. You would need to update your database through some external ways (wrap state from old, unwrap state to new). But you are on your own for this.

> tee_otp_get_hw_unique_key() and tee_otp_get_die_id() ...

So same RoT for the secure storage. At least you could decrypt the database content...

> ... (CFG_REE_FS=y) ...

.. but ree_fs storage has recently evolved to ease rollback protection (and other?). So likely /data/tee/* content will not match when upgrading optee. You need a specific reprovisioning I think.

@jforissier, I am right?
