### ISSUE TITLE
How to run hello world example in QEMU

### ISSUE THREAD

**Issue by azizulhakim** [OP-TEE/optee_os#2211]
I was able to run op-tee on QEMU and all regression test was successful. How do I run one specific application on QEMU? For example, how do I run hello world example in QEMU?

**Comment by casionwoo** [comment]
Executing hello world example is just typing "optee_example_hello_world"

**Comment by azizulhakim** [comment]
Not sure how exactly to do that. Am I supposed to run two environments using **make run** and then run the executable from **/bin/** directory of trusted environment? Or should I run **make** in the _example_ directory and run the executable from there as regular executable file?

I tried both. In the first case, the executable was not in the **/bin/** directory. In second case, it gives **_file Exec format error_**.

**Comment by casionwoo** [comment]
Firstly, you should run optee project. So go to build directory and if your state is already build for project with **make** , then type just make run-only. otherwise **make all run** .
then two console would be poped up! one is for optee-os and the other is for linux.
(of course when the qemu is running, you should type **c** for continue VM)
then when boot of linux is done, you can type **optee_example_hello_world**
then you can see hello and bye log in optee-os console.

**Comment by gutouyu** [comment]
> Firstly, you should run optee project. So go to build directory and if your state is already build for project with **make** , then type just make run-only. otherwise **make all run** .
> then two console would be poped up! one is for optee-os and the other is for linux.
> (of course when the qemu is running, you should type **c** for continue VM)
> then when boot of linux is done, you can type **optee_example_hello_world**
> then you can see hello and bye log in optee-os console.

I'm still trying to figure out how to upload my own specific applications files, and compile then run it. Do u have any ideas how to do this? Thanks

**Comment by jbech-linaro** [comment]
> @gutouyu  I'm still trying to figure out how to upload my own specific applications files, and compile then run it. Do u have any ideas how to do this? Thanks

I've created a set of patches that takes [hello_world](https://github.com/linaro-swg/optee_examples/tree/master/hello_world) in [optee_examples](https://github.com/linaro-swg/optee_examples) and creates and deploys (to the root fs) a new ta (`my_new_ta`) from it. You can find the instructions [here](http://people.linaro.org/~joakim.bech/new_ta/readme.txt). After you've done what I've written there, you can see all changes needed to create a new TA by study the git log. Please also pay attention to the "FAQ question / answer" in there...

Regarding trying to compile TA's **inside** QEMU or similar, I just say **don't** do it (you're asking for problems by trying to do so)! Use the cross compiler in a regular setup and build the system (includes all TAs) as described in [build.git](https://github.com/OP-TEE/build).

**Comment by gutouyu** [comment]
> > @gutouyu  I'm still trying to figure out how to upload my own specific applications files, and compile then run it. Do u have any ideas how to do this? Thanks
> 
> I've created a set of patches that takes [hello_world](https://github.com/linaro-swg/optee_examples/tree/master/hello_world) in [optee_examples](https://github.com/linaro-swg/optee_examples) and creates and deploys (to the root fs) a new ta (`my_new_ta`) from it. You can find the instructions [here](http://people.linaro.org/~joakim.bech/new_ta/readme.txt). After you've done what I've written there, you can see all changes needed to create a new TA by study the git log. Please also pay attention to the "FAQ question / answer" in there...
> 
> Regarding trying to compile TA's **inside** QEMU or similar, I just say **don't** do it (you're asking for problems by trying to do so)! Use the cross compiler in a regular setup and build the system (includes all TAs) as described in [build.git](https://github.com/OP-TEE/build).

Wow！ I did as you suggest and it works! You just give what I'm looking for. Thanks very much. Now, I can focus on learning how to write TAs. :)

**Comment by kernelproj** [comment]
@azizulhakim I install Ubuntu on VMWare and install QEMU on it. Can u please let me know the steps to run op-tee on QEMU?

**Comment by jforissier** [comment]
@kernelproj see https://optee.readthedocs.io/en/latest/building/devices/qemu.html.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
