### ISSUE TITLE
tee_svc_cryp.c:3091: (error) Uninitialized variable: tlen

### ISSUE THREAD

**Issue by yyyledu** [OP-TEE/optee_os#2214]
In syscall_authenc_enc_final() this path:

	if (dlen < src_len) {
		res = TEE_ERROR_SHORT_BUFFER;
		goto out;
	}

can lead to uninitialized tlen stack content being copied to user space:

		res2 = tee_svc_copy_to_user(tag_len, &tlen, sizeof(*tag_len));

**Comment by jenswi-linaro** [comment]
Thanks, fix available in https://github.com/OP-TEE/optee_os/pull/2215
