### ISSUE TITLE
Is it possible to monitor rich os kernel from the trusted os

### ISSUE THREAD

**Issue by azizulhakim** [OP-TEE/optee_os#2218]
I just got an idea how to use op-tee to offload secured part of a computation to trusted environment. I am just wondering if it is possible to monitor the whole rich os environment from the trusted os? By monitor, I mean hypervisor style monitoring where the trusted os has full view of the rich os and can do any operation on it. Is it possible or if there is any example? The examples we have is bidirectional where the rich os application communicates with the trusted os. But I want some application to run on trusted os and the rich os is agnostic of its existence.

**Comment by casionwoo** [comment]
OP-TEE os is only supports security service to nen-secure side linux.
of course theoretically it's possible but optee doesn't supports monitoring feature now as far as i know.

**Comment by azizulhakim** [comment]
Got it. Thanks.
