### ISSUE TITLE
Does the GlobalPlatform support the notion of SVN bound HUK for SecureStorage?

### ISSUE THREAD

**Issue by vtcao297** [OP-TEE/optee_os#2219]
Does the GlobalPlatform spec for Secure Storage support key/data migration?  The usecase is that we want to bind the SSK or HUK to be bind to an SVN (Secure Version Number).  When the SVN is incremented during an update of OPTEE OS due to a feature update or vulnerability, the SSK would change and will no longer be able to decrypt the old persistent data unless there is some sort of migration feature.  Is this feature defined in the spec?  Or is the idea that the TA would have to manage this key migrate somehow?

**Comment by jenswi-linaro** [comment]
No, there's no support for key/data migration.
