### ISSUE TITLE
Compilation issue for qemu target

### ISSUE THREAD

**Issue by rdhobi** [OP-TEE/optee_os#2220]
I'm compiling OP-TEE for qemu target but compilation gives below error.

```
"  INSTALL out/arm/export-ta_arm32/host_include/types_ext.h
  INSTALL out/arm/export-ta_arm32/host_include/conf.h
  INSTALL out/arm/export-ta_arm32/host_include/conf.mk
  CHK     out/arm/conf.cmake
  UPD     out/arm/conf.cmake
  INSTALL out/arm/export-ta_arm32/host_include/conf.cmake
  INSTALL out/arm/export-ta_arm32/host_include/tee_fs_key_manager.h
  INSTALL out/arm/export-ta_arm32/host_include/fs_htree.h
  INSTALL out/arm/export-ta_arm32/host_include/signed_hdr.h
  INSTALL out/arm/export-ta_arm32/src/user_ta_header.c
  INSTALL out/arm/export-ta_arm32/src/ta.ld.S
  INSTALL out/arm/export-ta_arm32/keys/default_ta.pem
  INSTALL out/arm/export-ta_arm32/scripts/sign.py
  INSTALL out/arm/export-ta_arm32/scripts/symbolize.py
  GEN     out/arm/export-ta_arm32/mk/conf.mk
make[1]: Leaving directory '/data/TrustZone/QEMU_OPTEE/optee_os'
make[1]: *** buildroot: No such file or directory.  Stop.
common.mk:197: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2
```
Anyone has any idea?

**Comment by jenswi-linaro** [comment]
It looks like you need to do a `repo sync`.

**Comment by rdhobi** [comment]
I have sync code using below commands

```
repo init -u https://github.com/OP-TEE/manifest.git -m default.xml -b 2.5.0
repo sync
```

**Comment by jenswi-linaro** [comment]
Try to replace `default.xml` with `default_stable.xml`

**Comment by rdhobi** [comment]
I have tried to init repo using default_stable.xml but repo init failed with below error

> repo init -u https://github.com/OP-TEE/manifest.git -m default_stable.xml -b master
> Get https://gerrit.googlesource.com/git-repo/clone.bundle
> Get https://gerrit.googlesource.com/git-repo
> remote: Finding sources: 100% (5/5)
> remote: Total 5 (delta 0), reused 5 (delta 0)
> Unpacking objects: 100% (5/5), done.
> From https://gerrit.googlesource.com/git-repo
>    cf7c083..0f2e45a  master     -> origin/master
> Get https://github.com/OP-TEE/manifest.git
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
> curl: (22) The requested URL returned error: 404 Not Found
> Server does not provide clone.bundle; ignoring.
> remote: Counting objects: 545, done.        
> remote: Total 545 (delta 0), reused 0 (delta 0), pack-reused 545        
> Receiving objects: 100% (545/545), 132.16 KiB | 144.00 KiB/s, done.
> Resolving deltas: 100% (404/404), done.
> From https://github.com/OP-TEE/manifest
>  * [new branch]      2.5.0      -> origin/2.5.0
>  * [new branch]      2.5.0-rc1  -> origin/2.5.0-rc1
>  * [new branch]      2.5.0-rc2  -> origin/2.5.0-rc2
>  * [new branch]      2.6.0      -> origin/2.6.0
>  * [new branch]      master     -> origin/master
>  * [new tag]         1.0.0      -> 1.0.0
>  * [new tag]         1.0.0-rc1  -> 1.0.0-rc1
>  * [new tag]         1.0.0-rc2  -> 1.0.0-rc2
>  * [new tag]         1.0.1      -> 1.0.1
>  * [new tag]         1.1.0      -> 1.1.0
>  * [new tag]         2.0.0      -> 2.0.0
>  * [new tag]         2.1.0      -> 2.1.0
>  * [new tag]         2.2.0      -> 2.2.0
>  * [new tag]         2.3.0      -> 2.3.0
>  * [new tag]         2.4.0      -> 2.4.0
>  * [new tag]         2.5.0      -> 2.5.0
>  * [new tag]         2.6.0      -> 2.6.0
>  * [new tag]         3.0.0      -> 3.0.0
> fatal: manifest 'default_stable.xml' not available
> fatal: manifest default_stable.xml not found

I think default_stable.xml is missing from https://github.com/OP-TEE/manifest

**Comment by jenswi-linaro** [comment]
Yes, it seems to have been removed from master, but it's there in the 2.5.0 tag.

**Comment by rdhobi** [comment]
Resolved!! Thanks..
