### ISSUE TITLE
OP-TEE for i.MX6Q SDB

### ISSUE THREAD

**Issue by yilingxu** [OP-TEE/optee_os#2222]
I follow the "http://mrvan.github.io/optee-imx6q-sabresd" to install op-tee. 

after the system is boot, I run:
$ tee-supplicant &
$ xtest

and I get many many many:
TC:0 trace_syscall:128 syscall #33 (syscall_cryp_random_number_generate)

@MrVan Is this normal?

Thanks for your help.

**Comment by giorgiocicero** [comment]
Hi, I am experiencing the same behavior. Were you able to solve it?

**Comment by jenswi-linaro** [comment]
Try to set `CFG_TEE_CORE_LOG_LEVEL=3`
For details check `trace_syscall()` in `core/arch/arm/tee/arch_svc.c`.

**Comment by giorgiocicero** [comment]
Ok, thanks a lot. With those printings I was thinking it was hanging.

Now the xtest finished with:
15753 subtests of which 6 failed
68 test cases of which 4 failed
0 test case was skipped
TEE test application done!

Is there a kind of log file which I can use to investigate which are the failing ones?
I am using a Sabre Automotive board with an imx6q which is no officially supported, so I needed to port  OPTEE and uboot on that.
It could be nice to have a fully working environment, so we can add the board support in the mainline github. Do you agree?

**Comment by giorgiocicero** [comment]
I noticed that there are 6 failing tests belonging to the regression_6000 test (6003, 6004, 6008, 6009, 6010, 6016). Any suggestion on how to investigate the problem in order to fix it?

**Comment by MrVan** [comment]
@giorgiocicero What's error log? which tag including optee os/client/xtest are you using?

**Comment by giorgiocicero** [comment]
I am compiling optee os with  FG_BUILT_IN_ARGS=y CFG_PAGEABLE_ADDR=0 CFG_DT=y CFG_PSCI_ARM32=y DEBUG=y CFG_TEE_CORE_LOG_LEVEL=3 CFG_BOOT_SYNC_CPU=n CFG_BOOT_SECONDARY_REQUEST=y

while client and xtest with the default configuration.

Please find below the error logs.

**The following log is related to the regression test 6003.1**, which contains the same error even for regression test **6004**, **6008**, **6009**, so 4 out of 6 (unfortunately prints are a bit overlapped):

* regr/ession_6003 Test TEE_ReadObjectTC:0 tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA b689f2a7-8adf-477a-9f99-32e90c0ad0a2
D/TC:0 tee_ta_init_user_ta_session:632 Lookup user TA b689f2a7-8adf-477a-9f99-32e90c0ad0a2 (Secure Storage TA)
Data
o regression_6003.1 Storage id: 00000001
D/TC:0 tee_ta_init_user_ta_session:632 Lookup user TA b689f2a7-8adf-477a-9f99-32e90c0ad0a2 (REE)
D/TC:0 ta_load:317 ELF load address 0x103000
D/TC:0 tee_ta_invoke_command:648 Error: ffff0003 of 4
/home/giorgio/workspace/mm/latestD/TC:0 tee_ta_close_session:403 tee_ta_close_session(0x4e05d290)
_versioning/optee_test/host/xtestD/TC:0 tee_ta_close_session:422 Destroy session
/regression_6000.c:891: fs_createD/TC:0 tee_ta_close_session:448 Destroy TA ctx
(&sess, file_02, sizeof(file_02),D 0x00000002, 0, data_01, sizeof/(data_01), &obj, storage_id) haTC:0 tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA b689f2a7-8adf-477a-9f99-32e90c0ad0a2
s an unexpected value: 0xffff0003D/TC:0 tee_ta_init_user_ta_session:632 Lookup user TA b689f2a7-8adf-477a-9f99-32e90c0ad0a2 (Secure Storage TA)
 = TEEC_ERROR_ACCESS_CONFLICT, expected 0x0 = TEEC_SUCCESS
  regression_6003.1 FAILED

**The following log is related to regression test 6010.1.8 (same error as 6010.2.8):**
regression_6010.1.8 StartPersistentObjectEnumerator ItemNotFound
/home/giorgio/workspace/mm/latest_versioning/optee_test/host/xtest/regression_6000.c:1413: fs_start_enum(&sess, e, storage_id) has an unexpected value: 0x0 = TEEC_SUCCESS, expected 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND
  regression_6010.1.8 FAILED

**The following log is related to regression test 6016.1 (same error as 6016.2):**
/home/giorgio/workspace/mm/latest_versioning/optee_test/host/xtest/regression_6000.c:1658: fs_create(&sess, a->file_name, sizeof(a->file_name), 0x00000002, 0, data_01, sizeof(data_01), &obj, a->storage_id) has an unexpected value: 0xffff0003 = TEEC_ERROR_ACCESS_CONFLICT, expected 0x0 = TEEC_SUCCESS
  regression_6016.1 FAILED

**Comment by MrVan** [comment]
@giorgiocicero  Did you clean /data/tee before you run the test? I do not recall clearly it is /data/tee or /data/tee??. Does it fail every time?

xtest/client/optee os, so you are using the latest upstream code, right?

**Comment by giorgiocicero** [comment]
Yes, I am using the latest upstream code.
Sorry, but I did not know about the need of clearing the /data/tee folder. In fact, if I first remove all items inside that folder and then launch the test, all the tests are passed!

Thanks a lot for the rapid support @MrVan @jenswi-linaro
