### ISSUE TITLE
sharing shared memory allocated from private_mgr to user

### ISSUE THREAD

**Issue by casionwoo** [OP-TEE/optee_os#2223]
Hi,

I'm trying to ask something sharing shared memory with user space.

As far as i know, there are two memory allocation 
first, allocate from private_manager
second, dma_buf_manager

usually (I can't 100% sure), when you want to share smc message(command, return code etc..) linux optee driver and optee os, shared memory allocated from private_manager is used.

and sharing memory with tee-supplicant to use rpc, dma_buf_manager is used.
in this case, tee-supplicant could access to shared memory with file descriptor.

here's my question, I'm trying to access shared memory allocated from private_manager in user space.
but there's no api for getting file descriptor to be used with mmap function in user space.

is there any way to get some fd with private_manager?
thank you.

**Comment by jenswi-linaro** [comment]
Hi,

The point with the private_manager is that user space isn't able to access it as it could lead to security problems. Imagine user space modifying the argument structure after it has been initialized by the driver but before secure world has read it.
