### ISSUE TITLE
OP-TEE boot protocol 

### ISSUE THREAD

**Issue by Atomar25** [OP-TEE/optee_os#2232]
I would like to know what is the OP-TEE boot protocol on ARMv7 based SoC.
Does it follow the same protocol as used by zImage on ARM?

To be more clear with my query, Just like XEN uses specific boot protocol[1].
Do we have something similar for OP-TEE  as well?

[1]https://xenbits.xen.org/docs/4.9-testing/misc/arm/booting.txt

**Comment by jenswi-linaro** [comment]
We have several boot protocols, mostly SoC specific.

**Comment by Atomar25** [comment]
Ok, but if one has to load uTEE image from a bootloader(given that it could load zImage) other than U-boot for say.
What are changes it has to adapt as per OP-TEE boot protocol?

**Comment by jenswi-linaro** [comment]
It's probably easier to just walk through the code:
OP-TEE is entered at https://github.com/OP-TEE/optee_os/blob/d84eb122fea4a58b7a9c34d23770174e09651e36/core/arch/arm/kernel/generic_entry_a32.S#L240
`r0-r3,lr` are saved by the macro `bootargs_entry`.
`reset_primary()` uses the arguments in different stages.

**Comment by etienne-lms** [comment]
Hi @Atomar25, 
Current vanilla u-boot does not support booting optee but for few specific platforms (up to my knowledge). Are you using a specific platform? or willing to port to a new platform?

Point is that on 32bit machines there are 2 pieces to consider:
* optee binary image format and its boot arguments
* need to split the secure and non secure world

The former (image format and boot args) is quite generic, I mean the generic optee code provides several image formats and ways to provide the boot arguments. We can help on this (maybe adding some nice documentation). 

The later (split secure/non-secure world) is quite platform specific and depends on how your u-boot is booted. Basically, a u-boot being booted in cpu secure state should pre-load both secure (optee core) and non-secure (Linux kernel?) images before jumping into optee which will initialize secure world then jump in the preloaded non-secure image entry point. Current bootz/bootm/... does not support such a scheme.

**Comment by etienne-lms** [comment]
> I think I see what you mean by "u-boot does not support booting optee" , only OMAP platform has such functionality at the moment, right ?

Yes, I understood u-boot/OMAP supports booting optee from u- boot but with specific platform support: the u-boot executes in non-secure state.

> So, we were thinking if we can just replace zImage by "uTEE or tee.bin" and load and run TEE which in turns load zImage (as we mentioned CFG_NS_ENTRY_ADDR for zImage).

Be aware that optee is not a bootloader and has no generic implementation for loading images from some media into some memory.

**Comment by Atomar25** [comment]
Well, Yes I understood the fact that OP-TEE is not a boot-loader.

My point was loading and execution OP-TEE from a custom bootloader( other than u-boot) that doesn't support booting uImage and only allows zImage to boot from storage media.
Isn't that is different ?

**Comment by etienne-lms** [comment]
Optee build does not generate image files following the zImage format. Let me describe them -- ain't there some docs about it? :(

Assuming you plan to execute optee core in a quite big secure RAM (using `CFG_WITH_PAGER=n`, default config), optee build produces several image files for the bootladers.
* Bootloader can use **tee-pager_v2.bin**. This file is a raw Arm executable image (entrypoint is an Arm instruction).
Bootloader shall load the image in RAM and branch to (using some cpu 'branch' like instruction).
* Bootloader can use **tee.bin**. This is a formatted binary file. It stores a header structure followed by the **tee-pager_v2.bin** binary blob content.
Bootloader must parse the header, load appended binary blob (header provides the target load address), and branch to it.
* Or a bootloader can use the triplet **tee-header_v2.bin** + **tee-pager_v2.bin** + **tee-pageable_v2.bin**.
The first is a structure describing the 2 other images. The second... well same as above. The last, in your case (`CFG_WITH_PAGER=y`), will be empty, don't care about it.
Bootloader must load/parse the header image, load the second image in RAM (header provides the target load address), and branch to it.

Looks weird but flexible (?) for the several platform specific configurations (useful for platforms that need to enable `CFG_WITH_PAGER`).

In your case, even if not a zImage format, I am pretty confident your bootloader will be able to boot optee using the **tee-pager_v2.bin** image file: load in RAM and branch to.

**Comment by Atomar25** [comment]
@etienne-lms , Thanks a lot!

Managed to load and run OPTEE-OS from our custom bootloader using tee-pager_v2.bin. I have
few follow up queries though.

1). We are loading OPTEE-OS to an address 0x4e000000(from custome bootloader) which for imx platform defined as:

#define CFG_CORE_TZSRAM_EMUL_START  0x4E000000

OP-OSS(be it the uTee , tee.bin or  tee-pager_v2.bin) must be loaded at TZSRAM, can't it be loaded into normal DRAM?
Also, couldn't figure out (it this part of OCRAM) how 0x4E000000 is derived after looking at various RM available for IMX6

2). Right now, we are loading  tee-pager_v2.bin image but if one has to load tee.bin or the uTee,  bootloader has to have appropriate parser for parsing the OP-TEE specific(don't think u-boot has such a parser)?

Thanks
-Amit

**Comment by etienne-lms** [comment]
i fear i won't be able to help a lot on imx memory layout.

Loading **tee.bin** requires a parser since there is a structure to read/use (or a least skip :)
Loading **tee-pager_v2.bin** does not need any parsing: load and branch to. 
Loading **uTee**... i don't know...

Do you need to enable the optee pager support (`CFG_WITH_PAGER=y`)? It is used to execute optee TEE in a small RAM with some memory-paging-on-demand support. If not, do not bother with it. If yes, loading **tee-pager_v2.bin** is not sufficient and you will need more from your boot sequence.

**Comment by Atomar25** [comment]
No, we didn't enable CFG_WITH_PAGER=y and I guess default is no.
Though we had to make following change to memory node in DTS file for test apps to run.

 memory {
-               reg = <0x10000000 0x40000000>;
+               reg = <0x10000000 (0x40000000-0x4000000)>;
        };
