### ISSUE TITLE
Is there any mechanism to load the public key to TEE for TA validation

### ISSUE THREAD

**Issue by Sourabhharman** [OP-TEE/optee_os#2233]
Hi,
I've checked the OPTEE code for TA validation. I found that the TA is first load to the secure memory and then validated by the public key corresponding to the private key, which has been used for TA signing.
The TEE is getting the public key from the following path "keys/default_ta.pem". So, in current implementation, the public key is hardcoded after OPTEE build.

Is there any implementation, through which the public key could be loaded separately during runtime, to validate the TA?

**Comment by jenswi-linaro** [comment]
No there isn't any implementation for that.

**Comment by Sourabhharman** [comment]
Hi @jenswi-linaro ,
Thanks for your reply.

In the current implementation, if we need to change the RSA key-pair for TA signing and verification, we need to re-build the OPTEE.

Is there any security reason, due to which the public key is been hard-coded?

**Comment by jenswi-linaro** [comment]
There's as many ways to make a public key available as there's security architects.

We have hard-coded public key because it's an easy was of getting a public key in place in order to demonstrate something simple which will work on all platforms. It's expected that this is one thing that  vendors will override with their own favorite solution.

**Comment by akbarsaleemt** [comment]
Hi Team,
How to validate a TA application in optee

**Comment by jbech-linaro** [comment]
> How to validate a TA application in optee

It's in our FAQ: Go to optee.org --> FAQ and search for "How are Trusted Applications verified?"

**Comment by akbarsaleemt** [comment]
thank you
