### ISSUE TITLE
USB driver in secure world

### ISSUE THREAD

**Issue by jenkin233** [OP-TEE/optee_os#2240]
Hi all,
I want to implement a USB driver in secure world so that I can use USB peripherals when it's protected with TZPC. But I don't know how to start it,  is there any advice or material that I can refer to? 
Thanks.

**Comment by jenswi-linaro** [comment]
Registering an interrupt handler is demonstrated on QEMU virt v7 with `console_itr_cb()`. However, this is a very limited demo. For a full driver you'll need a way of waking up threads as a way of communicating with whatever USB device you have in mind.
