### ISSUE TITLE
Latest 3.1.0-rc1 can not boot on Juno

### ISSUE THREAD

**Issue by KenLSoft** [OP-TEE/optee_os#2242]
Hello,
I am trying latest tags on Juno; and just found that 3.1.0 boot up failed; while 3.0.0 works well. Here is the fail log:
D/TC:0 add_phys_mem:527 CFG_SHMEM_START type NSEC_SHM 0xfee00000 size 0x00200000
D/TC:0 add_phys_mem:527 CFG_TA_RAM_START type TA_RAM 0xff200000 size 0x00c00000
D/TC:0 add_phys_mem:527 VCORE_UNPG_RW_PA type TEE_RAM_RW 0xff045000 size 0x001bb
000
D/TC:0 add_phys_mem:527 VCORE_UNPG_RX_PA type TEE_RAM_RX 0xff000000 size 0x00045
000
D/TC:0 add_phys_mem:527 GICC_BASE type IO_SEC 0x2c000000 size 0x00200000
D/TC:0 add_phys_mem:527 GICD_BASE type IO_SEC 0x2c000000 size 0x00200000
D/TC:0 add_phys_mem:540 Physical mem map overlaps 0x2c000000
D/TC:0 add_phys_mem:527 CONSOLE_UART_BASE type IO_SEC 0x7fe00000 size 0x00200000
D/TC:0 verify_special_mem_areas:465 No NSEC DDR memory area defined
D/TC:0 add_va_space:566 type RES_VASPACE size 0x01400000
D/TC:0 add_va_space:566 type SHM_VASPACE size 0x02000000
D/TC:0 dump_mmap_table:699 type IO_SEC       va 0xfaa00000..0xfabfffff pa 0x2c00
0000..0x2c1fffff size 0x00200000 (pgdir)
D/TC:0 dump_mmap_table:699 type NSEC_SHM     va 0xfac00000..0xfadfffff pa 0xfee0
0000..0xfeffffff size 0x00200000 (pgdir)
D/TC:0 dump_mmap_table:699 type TA_RAM       va 0xfae00000..0xfb9fffff pa 0xff20
0000..0xffdfffff size 0x00c00000 (pgdir)
D/TC:0 dump_mmap_table:699 type RES_VASPACE  va 0xfba00000..0xfcdfffff pa 0x0000
0000..0x013fffff size 0x01400000 (pgdir)
D/TC:0 dump_mmap_table:699 type IO_SEC       va 0xfce00000..0xfcffffff pa 0x7fe0
0000..0x7fffffff size 0x00200000 (pgdir)
D/TC:0 dump_mmap_table:699 type SHM_VASPACE  va 0xfd000000..0xfeffffff pa 0x0000
0000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0 dump_mmap_table:699 type TEE_RAM_RX   va 0xff000000..0xff044fff pa 0xff00
0000..0xff044fff size 0x00045000 (smallpg)
D/TC:0 dump_mmap_table:699 type TEE_RAM_RW   va 0xff045000..0xff1fffff pa 0xff04
5000..0xff1fffff size 0x001bb000 (smallpg)
D/TC:0 core_mmu_entry_to_finer_grained:622 xlat tables used 1 / 5
D/TC:0 core_mmu_entry_to_finer_grained:622 xlat tables used 2 / 5

And then whole system freeze. Has anybody tried on Juno ?

**Comment by jenswi-linaro** [comment]
I've booted Juno. 
```
D/TC:0 add_phys_mem:526 CFG_SHMEM_START type NSEC_SHM 0xfee00000 size 0x00200000
D/TC:0 add_phys_mem:526 CFG_TA_RAM_START type TA_RAM 0xff200000 size 0x00c00000
D/TC:0 add_phys_mem:526 VCORE_UNPG_RW_PA type TEE_RAM_RW 0xff02f000 size 0x001d1000
D/TC:0 add_phys_mem:526 VCORE_UNPG_RX_PA type TEE_RAM_RX 0xff000000 size 0x0002f000
D/TC:0 add_phys_mem:526 GICC_BASE type IO_SEC 0x2c000000 size 0x00200000
D/TC:0 add_phys_mem:526 GICD_BASE type IO_SEC 0x2c000000 size 0x00200000
D/TC:0 add_phys_mem:539 Physical mem map overlaps 0x2c000000
D/TC:0 add_phys_mem:526 CONSOLE_UART_BASE type IO_SEC 0x7fe00000 size 0x00200000
D/TC:0 verify_special_mem_areas:464 No NSEC DDR memory area defined
D/TC:0 add_va_space:565 type RES_VASPACE size 0x00a00000
D/TC:0 add_va_space:565 type SHM_VASPACE size 0x02000000
D/TC:0 dump_mmap_table:698 type IO_SEC       va 0xfb400000..0xfb5fffff pa 0x2c000000..0x2c1fffff size 0x00200000 (pgdir)
D/TC:0 dump_mmap_table:698 type NSEC_SHM     va 0xfb600000..0xfb7fffff pa 0xfee00000..0xfeffffff size 0x00200000 (pgdir)
D/TC:0 dump_mmap_table:698 type TA_RAM       va 0xfb800000..0xfc3fffff pa 0xff200000..0xffdfffff size 0x00c00000 (pgdir)
D/TC:0 dump_mmap_table:698 type RES_VASPACE  va 0xfc400000..0xfcdfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0 dump_mmap_table:698 type IO_SEC       va 0xfce00000..0xfcffffff pa 0x7fe00000..0x7fffffff size 0x00200000 (pgdir)
D/TC:0 dump_mmap_table:698 type SHM_VASPACE  va 0xfd000000..0xfeffffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0 dump_mmap_table:698 type TEE_RAM_RX   va 0xff000000..0xff02efff pa 0xff000000..0xff02efff size 0x0002f000 (smallpg)
D/TC:0 dump_mmap_table:698 type TEE_RAM_RW   va 0xff02f000..0xff1fffff pa 0xff02f000..0xff1fffff size 0x001d1000 (smallpg)
D/TC:0 core_mmu_entry_to_finer_grained:622 xlat tables used 1 / 5
D/TC:0 core_mmu_entry_to_finer_grained:622 xlat tables used 2 / 5
I/TC:  
D/TC:0 init_canaries:176 #Stack canaries for stack_tmp[0] with top at 0xff05f7b8
D/TC:0 init_canaries:176 watch *0xff05f7bc
D/TC:0 init_canaries:176 #Stack canaries for stack_tmp[1] with top at 0xff05fdf8
D/TC:0 init_canaries:176 watch *0xff05fdfc
D/TC:0 init_canaries:176 #Stack canaries for stack_tmp[2] with top at 0xff060438
D/TC:0 init_canaries:176 watch *0xff06043c
D/TC:0 init_canaries:176 #Stack canaries for stack_tmp[3] with top at 0xff060a78
D/TC:0 init_canaries:176 watch *0xff060a7c
D/TC:0 init_canaries:176 #Stack canaries for stack_tmp[4] with top at 0xff0610b8
D/TC:0 init_canaries:176 watch *0xff0610bc
D/TC:0 init_canaries:176 #Stack canaries for stack_tmp[5] with top at 0xff0616f8
D/TC:0 init_canaries:176 watch *0xff0616fc
D/TC:0 init_canaries:177 #Stack canaries for stack_abt[0] with top at 0xff061f38
D/TC:0 init_canaries:177 watch *0xff061f3c
D/TC:0 init_canaries:177 #Stack canaries for stack_abt[1] with top at 0xff062778
D/TC:0 init_canaries:177 watch *0xff06277c
D/TC:0 init_canaries:177 #Stack canaries for stack_abt[2] with top at 0xff062fb8
D/TC:0 init_canaries:177 watch *0xff062fbc
D/TC:0 init_canaries:177 #Stack canaries for stack_abt[3] with top at 0xff0637f8
D/TC:0 init_canaries:177 watch *0xff0637fc
D/TC:0 init_canaries:177 #Stack canaries for stack_abt[4] with top at 0xff064038
D/TC:0 init_canaries:177 watch *0xff06403c
D/TC:0 init_canaries:177 #Stack canaries for stack_abt[5] with top at 0xff064878
D/TC:0 init_canaries:177 watch *0xff06487c
D/TC:0 init_canaries:179 #Stack canaries for stack_thread[0] with top at 0xff0668b8
D/TC:0 init_canaries:179 watch *0xff0668bc
D/TC:0 init_canaries:179 #Stack canaries for stack_thread[1] with top at 0xff0688f8
D/TC:0 init_canaries:179 watch *0xff0688fc
I/TC:  OP-TEE version: 3.1.0-rc1 #1 tor  5 apr 2018 20:21:47 UTC arm
```

**Comment by KenLSoft** [comment]
Hi,
Just update that I have found the problem; and prepared a patch; but I need to go through internal process so it could be ready in this week; if you guys think it is just piece of cake you could just create a patch yourself and merge it. :)

The problem is that MMU patch think CPU 0 is primary CPU while in my configuration I set CPU5 as primary CPU; while copying primary mapping table to other cores it copy a empty table from CPU0 to other cores; which fails the boot.

The root cause is here:
https://github.com/OP-TEE/optee_os/blob/0ab9388c0d553a6bb5ae04e41b38ba40cf0474bf/core/arch/arm/mm/core_mmu_lpae.c#L408

And solution would be use extra index to let copy table from get_core_pos() to round(get_core_pos() + 1, NB_CORES) for NB_CORES times.

Thanks.

**Comment by jenswi-linaro** [comment]
We can wait for your patch. By the way, I don't think you need an extra index. You could just skip the index returned by `get_core_pos()` in that loop (and obviously start from `0` instead of `1`).

**Comment by KenLSoft** [comment]
PR generated: [2270](https://github.com/OP-TEE/optee_os/pull/2270)

**Comment by KenLSoft** [comment]
Patches merged. Close it.
