### ISSUE TITLE
Normal world TEE driver for QNX

### ISSUE THREAD

**Issue by cxdinter** [OP-TEE/optee_os#2248]
Hi,
   I want to develop TEE client application in QNX environment. Is it possible?
   Is there any guide documents for how to develop TEE dirvers in normal world OS? (I am not sure the experience from Linux is still compatible or not)

**Comment by jenswi-linaro** [comment]
There's some documentation in https://github.com/OP-TEE/optee_os/blob/master/core/include/optee_msg.h, https://github.com/OP-TEE/optee_os/blob/master/core/include/optee_msg_supplicant.h and https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/include/sm/optee_smc.h

Perhaps it's possible to port the driver from the Linux kernel, reading that source will give an idea of what's needed at least.

**Comment by cxdinter** [comment]
thanks.

**Comment by embinxpakistan-max** [comment]
Did you make it work. I also want to write the secure services in qnx os
