### ISSUE TITLE
General information on RPC's involve in TA loading

### ISSUE THREAD

**Issue by Sourabhharman** [OP-TEE/optee_os#2251]
Hi, 
I am trying to understand the TA loading part when we are calling TEEC_OpenSession(), from the Client Application.
I checked the OPTEE source code, and come to some basic understanding that Tee-supplicant is loading the TA binary, in the allocated shared memory. After that OPTEE is copying it to the secure memory and validating the binary with its Public Key.

Furthermore, on analyzing the following Debug logs:
D/TC:0 tee_ta_init_user_ta_session:640 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:0 tee_ta_init_user_ta_session:640 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)

I come to know that there are lot of RPC's involving in doing this operation. 
These are the functions that i checked on:
Inside tee_ta_init_user_ta_session(), it is looking for the fields with the pointer "uta_store_list". For each field, ta_load() function is calling, which is calling the corresponding open() handler.

So, my doubt is: What is the significance of "struct uta_store_list"? From where did this is getting initialized? What is the significance of the operation handler "secstor_ta_open()"? Why it is needed and what exactly is it doing?

Thanks in Advance

**Comment by jenswi-linaro** [comment]
`uta_store_list` store list is populated using `tee_ta_register_ta_store()`. Each of the entries in `uta_store_list` represents a location where a TA can be found and serves as an abstraction of the TA storage. This makes the TA storage extendable and easy to customize.

**Comment by Sourabhharman** [comment]
Thanks @jenswi-linaro and @jforissier  for your replies. They were very helpful in understanding the TA loading process.

One more question I am having on understanding the OPTEE RPC calls. 
On looking at the linux TEE driver side, in the rpc handler function _optee_handle_rpc_(), I found that the OPTEE_SMC_RPC_FUNC_ALLOC function beginning of RPC's. Reading the Macro description, I come to know it allocates memory for RPC parameter passing. The memory is used to hold a **struct optee_msg_arg**.

Further on putting some debug inside __tee_shm_alloc(), i come to know, the size of the memory comes of varying size (sometime 224, 160 or 32 bytes). 

So, on what basis, the OPTEE is deciding the memory size for the RPC payload to be allocated? If possible, can you please point me the respective function inside OPTEE, where the size parameter is decided?

Thanks in Advance.
