### ISSUE TITLE
Questions about TEE_ATTR_DH_BASE parameter and DH derivation in OP-TEE

### ISSUE THREAD

**Issue by davidhuziji** [OP-TEE/optee_os#2252]
Hi,

I have some questions about `TEE_ATTR_DH_BASE` and DH derivation. Could you please help take a look?

**Question 1**
In my own understanding, DH parameters include `Prime` and `Generator`. But in TEE Internal API spec, there is only a `TEE_ATTR_DH_BASE`, rather than a `TEE_ATTR_DH_GENERATOR`. According to the description in Section 5.6.5,
> `TEE_InitRefAttribute(&attrs[1], TEE_ATTR_DH_BASE, &g, len);`

Thus it seems that `TEE_ATTR_DH_BASE` just refers to `Generator`. Is it correct?

**Question 2**
Assume that `TEE_ATTR_DH_BASE` describes the `Generator`.
According to [[RFC5114]](https://tools.ietf.org/html/rfc5114#page-4), the size of `Prime` should be the same as that of `Generator`, at least in 1024-bit/2048-bit MODP groups.
However, in [optee_test DH derivation test data](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000_data.h#L5918), the length of `TEE_ATTR_DH_BASE` parameter is much smaller than that of `Prime`. The length of `Prime` is close to that of Subprime.
It confuses me. How should I set the `TEE_ATTR_DH_BASE` in OP-TEE?

**Question 3**
I'm writing a 2018-bit MODP DH derivation module to communicate with another OpenSSL program.
I follow the steps in [optee_test](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000.c#L4616).
The exchange of DH parameters succeeds. The `Prime` and `Generator` values match in both sides.
However, my OP-TEE module always derives a different shared secret from that of OpenSSL module.
I wonder if there are some conflicts in `TEE_ATTR_DH_BASE` and `Generator`, between OP-TEE and OpenSSL. Could you please give me some suggestions?

Thank you in advance.

**Comment by davidhuziji** [comment]
Hi,

I find out the answer by myself.

There are four parameters to setup a local private DH key for derivation. Since I have to pass other parameters, I split those 4 parameters into 2 transfers. In first `TEE_InvokeTACommand()`,  the private part and public part are passed to TA. The private part and public part are used to initialize the first 2 elements in an previously allocated `TEE_Attribute` array. In the second `TEE_InvokeTACommand()`, the prime and generator parts are passed into TA. They are used to initialize the following 2 elements in that `TEE_Attribute` array. The `TEE_Attribute` array are finally used to initialize the DH local private key in TA.

However, it seems that the first 2 elements, which contain private part and public part, are corrupted and overwritten by the prime part and generator part.
After the local DH private key initialization, there are still 4 elements in DH private key. However, the values in `x` (private key) and `y`(public key) are overwritten by the prime and generator values.

I guess OP-TEE cannot support maintaining a `TEE_Attribute` array in two `TEE_InvokeCommand()` sessions. Thus parameters passed to initialize local DH private are incorrect.
However, if there is something wrong in the `TEE_Attribute`, OP-TEE OS should throw an error, rather than silently continue.

Finally, I allocate two temporary memory buffer in TA to hold the private part and public part of local DH private key, in first `TEE_InvokeCommand()`. Combine them with the prime data and generator data passed in the 2nd `TEE_InvokeCommand()` to initialize the `TEE_Attribute` together. It solves the problem.

**Comment by etienne-lms** [comment]
Thanks @davidhuziji for sharing your experience. 
I think the single step object creation is the good way. Yet, we should check if the GPD Api allows multi-step feeding of object attributes.
@jforissier can you keep this issue open until we state on Api or implementation?

**Comment by jforissier** [comment]
@davidhuziji 

> The private part and public part are used to initialize the first 2 elements in an previously allocated TEE_Attribute array.

How / where is the array allocated? (heap? global variable? stack?)
How are the elements initialized? (`TEE_InitValueAttribute()`? `TEE_InitRefAttribute()`?)

**Comment by davidhuziji** [comment]
Hi @jforissier , got it. Thx.

By the way, is it possible for OP-TEE to detect if the buffer pointer in `TEE_Attribute` is available or not?

**Comment by jforissier** [comment]
I think OP-TEE already checks the attributes as much as it can. The problem is, buffers are likely to be re-used between calls. So the address is still valid but points to some other information.

**Comment by davidhuziji** [comment]
OK. I understood. It is really a corner case here.
Thanks a lot for your time.
