### ISSUE TITLE
Implementing new crypto library

### ISSUE THREAD

**Issue by deebee-v2** [OP-TEE/optee_os#2259]
Hi all,

I am trying to implement a BSP crypto library separate to the provided libtomcrypt but I do not want to modify core optee-os files.

Is it possible to remove a library (like libtomcrypt) from the build without modifying `optee-os/core/core.mk`?

What is the best practice for adding a new crypto implementation?

Thanks!

**Comment by jenswi-linaro** [comment]
Some small changes may be needed, if they are generic and could be useful for other they would probably be accepted into the main OP-TEE git.

This PR is trying to do the same. https://github.com/OP-TEE/optee_os/pull/1885

**Comment by deebee-v2** [comment]
Hi @jenswi-linaro ,

> @deebee-v2 , please provide a pull request for that.

I'm new to the open source community so please excuse my ignorance. Should I push a commit to the #1885 PR or submit a separate PR for the master branch?

Thanks.

**Comment by jenswi-linaro** [comment]
Hi @deebee-v2 ,
No worries. Just create a separate PR.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/blob/master/documentation/github.md

**Comment by deebee-v2** [comment]
Thanks for the help!

PR here #2262
