### ISSUE TITLE
SSL_accept error on rpi3 with op-tee

### ISSUE THREAD

**Issue by srjrjjr** [OP-TEE/optee_os#2267]
Hi All,

I have been battling getting my Rpi3 with OP-TEE working. I just downloaded the latest stable branch and compiled the entire op-tee and got it working for my Raspberry Pi. I wrote an example SSL Server application with OpenSSL. I just modified the hello world example. It must be noted that this does nothing on the secure world. However I never succeed getting a client to connect to my server. At SSL_accept() call, the program crashes with a Segmentation fault as below:

I can provide more information if you need. Here is the error:

root@RPi3:/bin ./hello_world
[ 2397.557351] hello_world[167]: unhandled level 2 translation fault (11) at 0x00000010, esr 0x92000006
[ 2397.570336] pgd = ffffffc0342e9000
[ 2397.577419] [00000010] *pgd=0000000034d4e003, *pud=0000000034d4e003, *pmd=0000000000000000
[ 2397.589626]
[ 2397.594875] CPU: 3 PID: 167 Comm: hello_world Not tainted 4.6.3-17583-g7d976fc #2
[ 2397.606318] Hardware name: Raspberry Pi 3 Model B (DT)
[ 2397.615393] task: ffffffc03415ce00 ti: ffffffc0342c8000 task.ti: ffffffc0342c8000
[ 2397.626907] PC is at 0x7f91907a5c
[ 2397.634098] LR is at 0x7f91925684
[ 2397.641228] pc : [<0000007f91907a5c>] lr : [<0000007f91925684>] pstate: 80000000
[ 2397.652538] sp : 0000007ff1b196d0
[ 2397.659647] x29: 0000007ff1b196d0 x28: 00000000000000ab
[ 2397.668820] x27: 0000000000000001 x26: 0000000000000000
[ 2397.677949] x25: 0000000000000000 x24: 0000007f91927f68
[ 2397.687015] x23: 0000007f91924038 x22: 0000000000436540
[ 2397.696027] x21: 0000000000436567 x20: 0000000000436544
[ 2397.705060] x19: 00000000004353d0 x18: 000000008b81c93a
[ 2397.714051] x17: 0000007f91817080 x16: 0000007f9194c5c0
[ 2397.723009] x15: 000000000000080b x14: 000000000d186eb4
[ 2397.731959] x13: 0000000000000000 x12: 00000000070e0000
[ 2397.740917] x11: 0000000000360000 x10: 0101010101010101
[ 2397.749887] x9 : 00000000004326c0 x8 : 0000000000000000
[ 2397.758848] x7 : 0000000000000020 x6 : 0000000000436567
[ 2397.767819] x5 : 0000000000000e00 x4 : 0000000000000000
[ 2397.776773] x3 : c3f400b2e665cabc x2 : 0000000000000000
[ 2397.785744] x1 : 0000000000436567 x0 : 0000000000000000
[ 2397.794689]
Segmentation fault

Thanks a lot

**Comment by sahilnxp** [comment]
@srjrjjr Can you paste the snippet of the code here to show which call is resulting in segmentation fault ??
