### ISSUE TITLE
The return code of TEE_AsymmetricVerifyDigest() violates GP TEE API spec

### ISSUE THREAD

**Issue by davidhuziji** [OP-TEE/optee_os#2268]
Hi,

According to GP TEE internal Core API Specification Section 6.7.3 `TEE_AsymmetricVerifyDigest()`, the return code of `TEE_AsymmetricVerifyDigest()` is described as below.

> Return Code
>  TEE_SUCCESS: In case of success
>  TEE_ERROR_SIGNATURE_INVALID: If the signature is invalid

In OP-TEE, [crypto_acipher_ecc_verify](https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/tee_ltc_provider.c#L1689) is called to implement `syscall_asymm_verify()` for ECDSA type.
However, the return value of [crypto_acipher_ecc_verify](https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/tee_ltc_provider.c#L1689) is only `TEE_SUCCESS` or `TEE_ERROR_GENERIC`. It will never return `TEE_ERROR_SIGNATURE_INVALID`, even if the signature is invalid.
Finally, when the return code comes back to `TEE_AsymmetricVerifyDigest()`, it will always panic with `TEE_ERROR_GENERIC` if the signature verification doesn't succeed. 

As a result, when `TEE_AsymmetricVerifyDigest` panics, I cannot get any useful information to check if the signature itself is invalid or actually something else triggers the panic.

Could you please help adjust the return code in [crypto_acipher_ecc_verify](https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/tee_ltc_provider.c#L1689) to return a more specific error value?

**Comment by jforissier** [comment]
Hi @davidhuziji,

You are right. DSA and RSA have similar problems, too. This was discussed in https://github.com/OP-TEE/optee_os/pull/1732 but never fixed properly.

I have created https://github.com/OP-TEE/optee_os/pull/2269 to address this.

**Comment by davidhuziji** [comment]
Hi @jforissier,

Thx. I will close this thread then.
