### ISSUE TITLE
Increase shared memory size on Hikey

### ISSUE THREAD

**Issue by Kailiangying** [OP-TEE/optee_os#2271]
Hi, 

I am trying to increase the shared memory size on Hikey. We tried the suggested approach on #1523. The suggested approach can increase the shm size and TA cache size. It works on qemu. When we tried to increase the shared memory size on Hikey, following is what we have tried on hikey platform_config.h. 

`#define CFG_SHMEM_START		0x3E100000
#define CFG_SHMEM_SIZE		(15 * 1024 * 1024)`

I got TA panic. My question is how to increase the shared memory size on Hikey platform? Any other files we have to update except the platform_config.h? 
 
Thanks in advance.

**Comment by vchong** [comment]
I've never tried but you can maybe get 8MB using
```
#define CFG_SHMEM_START 0x3E000000
#define CFG_SHMEM_SIZE (8 * 1024 * 1024)
```

Anything more than that is complicated and messy and involves changing many other files across many other repos and reconfiguring memory protection etc etc.

**Comment by Kailiangying** [comment]
@jforissier @vchong , thanks for your reply. 
If I switch to dynamic shared memory, do I need to make any change to the OPTEE OS to increase the size of dynamic SHM?
Can you provide the TA code reference of how to use the dynamic shared memory?

Thanks a lot

**Comment by vchong** [comment]
Don't think so. Just allocation your memory/buffer in normal world and register it using `TEEC_RegisterSharedMemory`. You can try searching through code in `optee_test` for reference usage.

**Comment by pt6567** [comment]
For testing, we are passing data via shared memory to the TA, then creating a buffer inside TA using TEE_Malloc(), and then copying the data from shared memory to the TA buffer. (using the size of TA Buffer). Below are the observations.
#### Code:
```
============HOST==========
in_mem.buffer = data;
in_mem.size = shared_mem_size;
in_mem.flags = TEEC_MEM_INPUT;
tee_rv = TEEC_RegisterSharedMemory(&ctx, &in_mem);

=============TA================
data = TEE_Malloc(ta_buf_size,TEE_MALLOC_FILL_ZERO);
TEE_MemMove(data, params[1].memref.buffer, ta_buf_size);

```

#### Set TA_DATA_SIZE to 14 MB
```
==============================Config========================================== 
pgt_cache.h:
------------
#define PGT_CACHE_SIZE	32

Hikey platform_config.h:
------------------------
#define CFG_SHMEM_START		0x3E100000
#define CFG_SHMEM_SIZE		(15 * 1024 * 1024)  //15MB
#define CFG_TEE_RAM_VA_SIZE	(1024 * 1024)
TA_RAM effective: 15MB

TA preferences:
------------
#define TA_STACK_SIZE               (4 * 1024)
#define TA_DATA_SIZE                (14 * 1024 * 1024)

================================Result=========================================
TA crashed during TA Init.
DEBUG:   [0x0] TEE-CORE:tee_ta_init_static_ta_session:159:    Lookup for Static TA 8aaaf200-2450-11e4-abe20002a5d5c51b
DEBUG:   [0x0] TEE-CORE:init_session_with_signed_ta:614:    Load dynamic TA
DEBUG:   [0x0] TEE-CORE:tee_ta_open_session:477: init session failed 0xffff000c
DEBUG:   [0x0] TEE-CORE:tee_dispatch_open_session:127:   => Error: ffff000c of 3
```

#### Set TA_DATA_SIZE to 8MB and CFG_SHMEM_SIZE to 15MB
```
==============================Config========================================== 
pgt_cache.h:
------------
#define PGT_CACHE_SIZE	32

Hikey platform_config.h:
------------------------
#define CFG_SHMEM_START		0x3E100000
#define CFG_SHMEM_SIZE		(15 * 1024 * 1024)  //15MB
#define CFG_TEE_RAM_VA_SIZE	(1024 * 1024)
TA_RAM effective: 15MB

TA preferences:
---------------
#define TA_STACK_SIZE               (4 * 1024)
#define TA_DATA_SIZE                (8 * 1024 * 1024)

================================Result=========================================
14.9 MB SHM, 7.9 MB TA buffer ---------->  success
14.9 MB SHM, 8 MB TA buffer ----------> TA Failed while data copy. [ TA panicked with code 0xdeadbeef]
15 MB SHM, 7.9MB TA buffer ----------> host program crashed while registering share memory. [ffff000c: TEEC_ERROR_OUT_OF_MEMORY]

```

As per my understanding, Non-secure Shared memory can be increased by any X in the platform_config.h and it just effectively reducecs RAM avilable for normal world by X value.

- Is there any limit on X?
- Is there any way we can use more than 8MB via TEE_Malloc() inside TA? What changes are required?
