### ISSUE TITLE
DRM support in OP-TEE

### ISSUE THREAD

**Issue by Thekku** [OP-TEE/optee_os#2276]
DRM and HDCP is supported in OP-TEE? sorry for such a stupid question even I do not know how these are directly connected to OP-TEE other than normal crypto operations.

**Comment by lorc** [comment]
Hi @Thekku,

There is a SDP (Secure Data Path) support in OP-TEE. This mechanism can be used to implement DRM. But, I didn't heard  about any actual implementations of this.

**Comment by jforissier** [comment]
> But, I didn't heard about any actual implementations of this.

A number of DRM demos were presented at Linaro Connect in March in Hong Kong (HKG18). They were running on various platforms such as Arm Juno, TI X15, NXP i.MX8M or HiKey.

Photos are available on Flickr:
https://www.flickr.com/photos/linaroorg/39156779490/in/album-72157664795733267/
https://www.flickr.com/photos/linaroorg/27094837958/in/album-72157664795733267/
https://www.flickr.com/photos/linaroorg/27094838718/in/album-72157664795733267/
https://www.flickr.com/photos/linaroorg/27094837248/in/album-72157664795733267/

**Comment by Thekku** [comment]
@jforissier  Any reference implementation is available?

**Comment by jforissier** [comment]
@Thekku yes but only for Linaro members I think. @jbech-linaro / @vchong can you provide some advice?

**Comment by petegriffin** [comment]
@Thekku We have 2 OPTEE ClearKey reference solutions, one for Android and one for Chromium in Linux.

For Android you can follow the instructions here https://github.com/linaro-home/clearkeydrmplugin (which implies you have already followed the instructions here https://github.com/linaro-swg/optee_android_manifest.

For Chromium + OpenCDM + ClearKey the manifest is here https://github.com/linaro-home/lhg-oe-manifests. Also a blog post https://www.linaro.org/blog/lhg-updates-w3c-eme-solution-96boards-hikey-platform/ which documents the command line arguments required to start chromium. Note you will need to be building for a board like HiKey which already has OPTEE enabled in the build.

Also the slides that Victor linked to above is a good overview of what exists for both Android and Linux and has some nice diagrams about the architecture https://www.slideshare.net/linaroorg/hkg18203-overview-of-linaro-drm

We are also working on WPE browser plus OpenCDM & OP-TEE, but that isn't fully functional yet.

**Comment by Thekku** [comment]
Thank you all for the support

**Comment by aansari2408** [comment]
Good info! Is any decision on making it open source ?

**Comment by petegriffin** [comment]
Just to confirm, Playready is similar to Widevine. The Playready TA can only be distrusted to Linaro members who have also signed the Playready license agreements.
