### ISSUE TITLE
ECC Point to Octet string conversion in OP-TEE

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_os#2286]
![image](https://user-images.githubusercontent.com/27992285/39392609-a9d6bd70-4ad6-11e8-8fea-957375e9ebeb.png)

Hi All,

We are having a system as shown above in the picture.
Adding the support of ECC key in PKCS#11 library, Now PKCS#11 library represents the ECC Public Key point as octet string and TEE represent the ECC Public key point as (x,y) coordinates.

So take example when we are importing the ECC key in our token, we will pass the Octet string to PKCS#11 API and need to convert this into (x,y) form before creating an object in TEE.

Explored OP-TEE to some extent and didn't found any functions to convert from Octet to Point form.

There are 2 options for doing this:

- We can convert the octet to Point in PKCS#11 library but that needs to link the PKCS#11 library with OpenSSL, and I think that is not recommended to link PKCS#11 library with other libraries, because PKCS library is loaded dynamically in the application.

- Other thing I can think of is writing code for conversion either in PKCS library or on TEE Side.

Please suggest which way I should chose, or am I missing on something ?

Regards,
Sahil

**Comment by jbech-linaro** [comment]
> Please suggest which way I should chose, or am I missing on something ?

Hi Sahil, at this stage and if possible, then I think it is better convert it in normal world. Later on as @etienne-lms PKCS#11 work getting more mature, you could eventually get rid of the conversion and use the PKCS#11 library etc that he is working with.

**Comment by sahilnxp** [comment]
Thanks @jbech-linaro for information.
@etienne-lms  when is this PKCS#11 implemetation coming out ??

**Comment by etienne-lms** [comment]
hello. thanks thanks your patience.

Op-tee/pkcs#11 it is still in developement to get some good foundations. Fundamentals for supporting some pkcs#11 features need quite a lot of code and we are still maturing a work base that could stable enough for being (merged and) open to contributions.

The setup under development is pending in the 'sks' branches of [etienne-lms/optee_os](https://github.com/etienne-lms/optee_os) / [_client](https://github.com/etienne-lms/optee_client) / [_test](https://github.com/etienne-lms/optee_test): a Trusted Application, the Cryptoki lib interfatcing the TA and some op-tee regression tests.

Plan is to get the TA API reviewed (and upstreamed to optee_os) first (will bring also the optee_client and optee_test basics). I will open new P-Rs for that. Then will come basics for object (keys) manipulation.

**Comment by sahilnxp** [comment]
Thanks @etienne-lms for information.
We are also working on the PKCS#11 implementation based on OPTEE, we implemented Asymmetric operations (RSA Key generation, RSA Private Operations).
I can see in your code, you are currently working on Symmetric Cryptography.
Will be happy to review and contribute on this.

Since this requirement of ECC Point to Octet is very common and even libtomcrypt also gives the function ecc_ansi_x963_export()/import(), Don't you think Global Platform standard should define some Standard APIs for this ??

Just curious about one thing, Why this is being named as "Secure Key Services" because PKCS#11 doesn't work with only keys, also work with Ceritificates.

**Comment by etienne-lms** [comment]
For the ECC and GPD, I can't tell. If it is a matter of conversion, i guess GPD has no real presure to define an API for that. To look for the next TEE Internal Core API v1.2.
