### ISSUE TITLE
OP-TEE & VMSAv7 VE

### ISSUE THREAD

**Issue by jonpe960** [OP-TEE/optee_os#2287]
I'm trying to get a handle on the boot flow with OP-TEE and how the MMU is set up.

Some background details:

 o I'm working with the IMX6UL (ARMv7a VE)
 o Using a custom bootloader
 o Modified op-tee to enter HYP mode when leaving secure world

The main goal with my experiment is to evaluate how fast I can boot into a hypervisor and start a first, small, RTOS under the hypervisor while still retaining a secure boot chain and provide an op-tee backed secure world setup.

I've gotten this to work to some extent with OP-TEE and Xvisor. No virtual memory is configured by the bootloader, the MMU is not configured at all. I simply; load op-tee and xvisor into RAM, then set LR with the physical address of the Xvisor entry point and finally set PC with the entry point of OP-TEE. 

Now, I want to use seL4 in a similar fashion. I think seL4 expects virtual memory to be set up before entering the kernel (except if you use the elf-loader,  which I will not use).

I understand the concepts of different translation tables in different execution modes, however, I still have a number of things I do not understand:

 o When OP-TEE configures the MMU in secure state does that mean that the MMU is active when jumping to non-secure state and all memory access is translated by the MMU?

 o Should I configure a basic memory map accommodating the hypervisor before jumping to the op-tee entry-point?

 o Since the bootloader runs at the highest exception level can I still configure a memory layout for the HYP mode?

I realize that this is more of an armv7 architecture question and not so much OP-TEE related but I'm hoping that someone here can help me.

Thanks,
Jonas

**Comment by etienne-lms** [comment]
> o When OP-TEE configures the MMU in secure state does that mean that the MMU is active when jumping to non-secure state and all memory access is translated by the MMU?

No. MMU states and registers are banked and one does not impact the other. Secure side and non-secure kernel handle their Mmu independently.

> o Should I configure a basic memory map accommodating the hypervisor before jumping to the op-tee entry-point?

Optee init does not act on non-secure configuration. It is left as it is before entering optee. Unless some platform specific implements some explicit sequence.

> o Since the bootloader runs at the highest exception level can I still configure a memory layout for the HYP mode?

You should have the optee init to jump in non-secure Hypervisor state so that hypervisor installs itself, no? I think optee code shall be modified for that.

**Comment by jonpe960** [comment]
Thank you
