### ISSUE TITLE
i.MX6QP Normal World performance

### ISSUE THREAD

**Issue by dhollister0** [OP-TEE/optee_os#2288]
I have OPTEE running on our i.MX6QP-based device with a pseudo-TA -- everything came together surprisingly quickly!  But we discovered that the performance of Normal World is now noticeably slower.  My first clue was that boot time increased from 48 seconds to >60 seconds.  We also benchmarked our Android application and found it to be slow when running OPTEE.  It looks like OPTEE is correctly bringing all 4 cores online.

I have stopped invoking our TA, and as far as I can tell, I don't have any secure interrupts firing.  So I don't think I should be switching worlds at all.

I have 2 kernels on the device - the only difference between the two are the CONFIG options (CONFIG_ARM_PSCI=y, CONFIG_TEE=y, CONFIG_OPTEE=y) and I can switch boot modes in u-boot to either boot through OPTEE or not, which makes it easy to do comparisons.

My first thought was that the L2 cache configuration is different since it's now handled by OPTEE.  I noticed that the L2 cache double-linefill feature is disabled for all i.MX6Q, but the erratum was fixed on the i.MX6QP.  So I enabled it.  To my surprise, the performance got even worse!  So then I copied the L2 cache controller registers from a normal boot and put those values into OPTEE's platform_config.h (except for at least one bit having to do with Normal World), but I had the same results.  

In fact, I found that *disabling* the L2 cache resulted in better system performance when running OPTEE (and worse performance when booting without OPTEE).

Is this a known issue, or something to expect when running Linux in Normal World?

optee_os was built from commit 628a9a10

Thanks!

**Comment by MrVan** [comment]
@dhollister0 Besides the L2 Cache settings, you also need set ACTLR, perfetch needs to be opened. CHecking the value when linux boots in secure world, and set the value in OP-TEE. You will get a good a performance I think.
