### ISSUE TITLE
Use of cipher_update() for CTR cipher

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#2290]
I am looking at the [xtest code](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000.c#L2398) for CTR cipher.

I'm trying to understand the use of the call to ta_crypt_cmd_cipher_update() and in_incr. 
-> Can you tell why these are needed ? 
-> Is the call to update() tied to the output array being 2048 in size ? 
-> Is it possible to skip the call to cipher_update() and just call do_final() without using in_incr as well ?
-> Should update() be called once as done in the code, or several times ?
-> Since this is a CTR mode, is there an example for use of a counter ? Or it assumed the iv is nonce + counter ?
-> In the declaration of the test case, what is the reason for choosing the values 13 and 16 below for in_incr ?

       XTEST_CIPH_CASE(TEE_ALG_AES_CTR, TEE_TYPE_AES,
			ciph_data_aes_key1, ciph_data_128_iv1, 13,
			ciph_data_in1,
			ciph_data_aes_ctr_out1),

	XTEST_CIPH_CASE(TEE_ALG_AES_CTR, TEE_TYPE_AES,
			ciph_data_aes_key1, ciph_data_128_iv1, 13,
			ciph_data_in3,
			ciph_data_aes_ctr_out2),

	XTEST_CIPH_CASE(TEE_ALG_AES_CTR, TEE_TYPE_AES,
			ciph_data_aes_key1, ciph_data_128_iv1, 16,
			ciph_data_in3,
			ciph_data_aes_ctr_out2),

	XTEST_CIPH_CASE(TEE_ALG_AES_CTR, TEE_TYPE_AES,
			ciph_data_aes_key1, ciph_data_128_iv1, 16,
			ciph_data_in4,
			ciph_data_aes_ctr_out4)

Thanks

**Comment by a2t2** [comment]
How is the counter specified for encryption/decryption ? Is the IV consider the nonce + counter ?

**Comment by a2t2** [comment]
@jforissier Just to double check, this means OPTEE expects the host side to generate a nonce and a counter, then concatenate / XOR to generate the IV parameter. In the [diagram](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#/media/File:CTR_encryption_2.svg), the input on top of the "block cipher encryption" is the IV argument of the OPTEE AES CTR API i.e. nonce + counter ?
Thanks

**Comment by jforissier** [comment]
@a2t2 correct.

- The IV that comes from `TEE_CipherInit()` is passed to LibTomCrypt here: https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/tee_ltc_provider.c#L2008-L2010
- It is copied into `ctr->ctr[]` here: https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/modes/ctr/ctr_start.c#L97-L99
- Each time a block is encrypted, `ctr->ctr[]` is incremented, here: https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/modes/ctr/ctr_encrypt.c#L75-L80 (I'm ignoring the accelerated encryption path here but it's the same, it will increment `ctr->ctr[]`).
