### ISSUE TITLE
ROOTFS for Rpi3 with OP-TEE

### ISSUE THREAD

**Issue by srjrjjr** [OP-TEE/optee_os#2293]
Hi All,

The current Busybox v 1.24.0 that I downloaded  via branch rpi3_stable.xml via git seems to be a very minimal system with no gcc or gdb etc. Is there a more full fledged working rootfs? I tried to follow the instructions under : https://github.com/OP-TEE/optee_website/blob/5d58e8fdb4c395d2bb235acb782b01cdb7ce6261/docs/rpi3.md
However the section under RFS, i.e, doesn't really explain how to build a rootfs tarball or whcih one to use. Can someone share a link to such a rootfs and also explain how to get it working under Rpi3?

Thanks a lot in advance.

**Comment by jbech-linaro** [comment]
Hi @srjrjjr , true it is indeed a very minimal system. We are currently working with making things a bit more flexible by introducing buildroot, which in turn will make it easy to enable other developer tools. We are converting our setup's one by one, but RPi3 is still on the todo list (QEMU v7/v8, HiKey 620/960 and FVP have already been converted). Meanwhile waiting for the RPi3 setup to be converted you can try a prebuilt root fs like the one mentioned (Debian based Linaro rootfs) in the RPi3 docs. But with that you have to deploy the OP-TEE binaries in some way on your own (either by mounting the root fs with the SD-card, alternatively use NFS and copy files into the root fs shared over the network). Both possible, but we have no official instructions for how to do it ([this](https://github.com/jbech-linaro/build/blob/rpi_nic/rpi3.mk#L250-L264) is how I'm doing that in my own RPi3 NFS setup).

**Comment by srjrjjr** [comment]
Just a quick question. How can I use a "prebuilt rootfs"? I have downloaded the linaro rootfs(which is a tar.gz file). How can I run it in the current setup of OP-TEE Rpi3? Can you please provide some starting point?


Also, regarding the QEMU version, I had to switch to Rpi3 because I wanted to have a tcp Server running on QEMU talking to my tcp Client on host(addressed here: https://github.com/OP-TEE/optee_os/issues/2194). However with the QEMU, with tap device I was unable to get the QEMU to "talk" to the host. Is there a newer QEMU version which addresses this problem? Thanks

**Comment by jbech-linaro** [comment]
The secure side binaries like `optee.bin` (which basically is fip.bin) should be handled in the same way regardless how you are working with the root fs (i.e., those goes into the boot partition). For the root fs itself, check the output from `make img-help`, that describes how to untar/unzip all files into a mounted partition. You can do the same with a full prebuilt root fs. The only difference is that you would need to deploy the OP-TEE files on your own here, like tee-supplicant, libteec.so, TA's, example apps etc. Basically what is done automatically for the stripped down root fs that we are currently supporting (see [this](https://github.com/OP-TEE/build/blob/master/common.mk#L480-L541) make target).

**Comment by Christian56** [comment]
hi,
i followed the description about setting up the prebuild rootfs (https://github.com/OP-TEE/build/blob/master/docs/rpi3.md#57-other-root-filesystems-than-initramfs-based). However i got an error saying 
"Unable to mount root fs via NFS, trying floppy." and "Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(2,0)", when i use tar -xvf. After that i tried the same method like on img-help but my cpio command throws this error: 

*** Error in `cpio': realloc(): invalid pointer: 0x0000000000622280 ***
Any suggestions what I could have done wrong ? If it helps i can attach the whole output

**Comment by jbech-linaro** [comment]
> Any suggestions what I could have done wrong ?

I've seen this error multiple times and it has always been an issue on my local machine. Basically what kernel says is that it cannot find the root filesystem and therefore panics. In my cases it's been caused by for example, NFS server not started, path to the root fs not exported correctly by NFS (does `$ showmount localhost -e` give the paths expected?), wrong parameters in U-Boot when booting up using NFS (see https://github.com/OP-TEE/build/blob/master/rpi3/firmware/uboot.env.txt#L39 and Line 41).

**Comment by Christian56** [comment]
Thanks for the fast responds. I forgot to update the path to the rootfs on the NFS. 
``$ showmount localhost -e`` helped a lot :)
