### ISSUE TITLE
hw_get_random_byte(), query on return method  

### ISSUE THREAD

**Issue by jjoset** [OP-TEE/optee_os#2297]
I referring to hi16xx_rng.c for hardware RNG implementation. Wondering why hw_get_random_byte(void) function reads the 32 bit register and return as single byte at a time. Why it can't we pass the number of random number bytes to be read to the hw_get_random_byte() function. That is same arguments as GP core spec. Advantage we see are, we can avoid globals in the read function and also every call get a fresh random number from the hardware register.

**Comment by jforissier** [comment]
Hi @jjoset ,

`hw_get_random_byte()` returns only one byte because it is a convenient common interface towards all sorts of hardware RNGs. `plat-stm` reads 8 bytes at a time from its RNG ([`plat-stm/rng_support.c`](https://github.com/OP-TEE/optee_os/blob/3.1.0/core/arch/arm/plat-stm/rng_support.c#L72)). DRA7 reads 8 bytes, too ([`drivers/dra7_rng.c`](https://github.com/OP-TEE/optee_os/blob/3.1.0/core/drivers/dra7_rng.c#L75)). But Hi16xx only reads 4 bytes as you said.

> Advantage we see are, we can avoid globals in the read function

Why is that a problem?

> and also every call get a fresh random number from the hardware register.

What is the 'freshness' of a random number?

**Comment by Thekku** [comment]
Here I presume, the granularity of the random number in case HI16xx is 32bit. So two TAs are concurrently reading  4 bytes random number, there is a chance that each TA gets 2 bytes from one register read and the next 2 bytes from the next register read. If this is not breaking basic hardware random number concept, globals are not going to make any problem. @jjoset  how many bytes of random number are reading in your case?

**Comment by jjoset** [comment]
@jforissier 
1.Freshness I mean getting a  random number from hardware register every time, instead of sending already stored bytes from the function. 
2.The problem with globals will be concurrent access from two TA as @Thekku mentioned. The function returns part of random bytes to one TA and another part to different TA. 
@Thekku In my case the RNG data register is 32 bit.

**Comment by jforissier** [comment]
@jjoset 
1. I understand that, but why would a random number that has been stored in a buffer for some time be less good than one that is fresh out of the hardware register? (are RN like bread or flowers maybe? ;-))
2. As long as no value is returned twice, I fail to see how that could be a problem.

**Comment by jjoset** [comment]
@jforissier .Thanks for the answers.  Infact I meant to ask Can I expect byte level randomness from 32 bit random number register?

**Comment by jforissier** [comment]
@jjoset 

> In fact I meant to ask Can I expect byte level randomness from 32 bit random number register?

Indeed, I am assuming you can. Any deviation would be a weakness in the RNG implementation, as far as I can tell.

**Comment by jjoset** [comment]
Thank you so much for answers @jforissier. I will now close the issue.
