### ISSUE TITLE
Question: Is it possible to export platform specific services to user TAs?

### ISSUE THREAD

**Issue by deebee-v2** [OP-TEE/optee_os#2299]
Without going through libutee, is it possible for user TAs to access a service exported by a platform BSP? If so, what is the BKM for doing so?

**Comment by jbech-linaro** [comment]
No, not without doing anything. You'd need to write a library or something similar which exports the functions to the TA's. IIRC we have no BKM for BSP inclusion ATM.

**Comment by deebee-v2** [comment]
Ok thanks
