### ISSUE TITLE
Is it able to build OPTEE OS on open-hardware programmable SC4-HSM (with STM32F405RG processor)

### ISSUE THREAD

**Issue by imlibra** [OP-TEE/optee_os#2302]
SC4-HSM is an open-hardware programmable HSM based on STM32F405RG processor. Unlike development boards like rpi, it supports clear memory when every reprogramming occurred, or permanently ban for reprogramming.

**Comment by jbech-linaro** [comment]
Hi @imlibra , I'd say no. That is using a Cortex-M4 and OP-TEE is a TEE OS for class-A devices running the full stack, i.e., besides the TEE itself it also relies on a REE OS (like Linux for example).
