### ISSUE TITLE
Questions related to wifi activation on rpi3.

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#2307]
I built the latest source for rpi3 via repo (repo init -u https://github.com/OP-TEE/manifest.git -m rpi3.xml) and flashed it to micro SD.

I have successfully set up the wired LAN(eth0).
But I need to configure the current wireless situation, so I want to enable wifi on rpi3.

When I run ifconfig, eth0 is visible, but wlan0 is not visible.
Also, when I run the iwlist command used in RazBian, command not found is displayed.

Please let me know if someone know how to enable wifi in kernel currently being used by OPTEE.

**Comment by gitfineon** [comment]
There is a hint in the [README](https://github.com/linaro-swg/linux/blob/7d976fc52ae3f04618062967948e626166f1904a/README)
> 6. Builtin wifi(Needs /lib/firmware/brcm/* files from the raspbian image)

If you did follow this advice, but the kernel module is still missing you may take a look at the kernel config. Using the manifest you mentioned leads to the following configuration maintained by linaro-swg. 
* [bcmrpi3_defconfig](https://github.com/linaro-swg/linux/blob/7d976fc52ae3f04618062967948e626166f1904a/arch/arm64/configs/bcmrpi3_defconfig)
* and corresponding device tree source files and overlays

**Comment by SangsubLim** [comment]
hi @gitfineon 

I have copied the/lib/firmware/brcm/* files in raspbian image as you have told me, but still the driver is not loaded.
And I have seen defconfig, but I am a beginner and I am not sure what to add.
I will be glad if you can give me extra help.

If the driver is loaded normally, can you tell me how I can check it?
In ifconfig or iwconfig, nothing about the wireless LAN is missing.
Again, eth0 is working fine.

Thank you.

**Comment by gitfineon** [comment]
I'm not aware of the the rpi3 and its wifi, but you should be able to see the corresponding kernel module if it is loaded by typing `lsmod`. If the module is missing try to load is with `modprobe`.

Follow this https://github.com/raspberrypi/linux/issues/2132#issuecomment-317711870
it was one of the first google result i got.

The discussion states `brcmfmac` should be the module you are searching for.

Good luck!

**Comment by Christian56** [comment]
Have you solved the issue? I'm having the same problem. However when I insert a USB-WiFi adapter i can see the wlan0 interface. Still having a problem setting it up though. I added the etc/wpa_supplicant/wpa_supplicant.conf config file and added an entry in entry in /etc/network/interfaces but i getting a "no lease, failing" error.  
@SangsubLim I can only see the the interface in ifconfig -a not in the "usual" ifconfig  command. Can you use the iwconfig command ?
