### ISSUE TITLE
Porting OPTEE-OS on ARMv8            

### ISSUE THREAD

**Issue by Atomar25** [OP-TEE/optee_os#2308]
I have one query regarding OPTEE-OS port on ARMv8. All most all the OPTEE-OS port on ARMv8 has 
ATF that has both BL1 and BL2 stages implemented.

My query is there exist any port where ATF's BL1 and BL2 stages are not implemented (ATF has only BL31 stage implemented)?

Is it possible for ATF's BL31 stage to pass control to OPTEE-OS and return, is there such implementation exist already?

Thanks -Amit

**Comment by lorc** [comment]
Hi @Atomar25, yes this is perfectly fine. This is how ARM TF actually works with OP-TEE.

OP-TEE is considered as `bl32` in terms of ARM TF. BL31 boots it and manages with interactions with it. So, basically OP-TEE does not need BL1  and BL2 at all. BL3 is all what is needed.

**Comment by lorc** [comment]
Here is where OP-TEE (or another SPD - Secure Payload) initialized:

https://github.com/ARM-software/arm-trusted-firmware/blob/885ca54a75e14a63c375b5d12852dc7ef2c0b568/bl31/bl31_main.c#L106

So, actually, you just need to ensure that OP-TEE is placed in memory and BL31 is properly configured to boot it.

**Comment by Atomar25** [comment]
Thanks for the reply.

But I was wondering BL32 corresponds to NS-EL1 where OPTEE-OS runs at S-EL1, so ATF BL32 moves from NS-EL1 to S-EL1 ?

**Comment by lorc** [comment]
AFAIK, BL32 corresponds to Secure Payload (AKA S-EL1).

So, BL31 runs at EL3, BL32 runs at S-EL1 and BL33 runs at NS-EL1.

**Comment by Atomar25** [comment]
Ok, I should have made a distinction between BL33 and BL32.

I guess for SPD to be registered with ATF, it needs to be compiled with specific options.

**Comment by lorc** [comment]
Yes. This is done in platform configuration file. You need to enable `CFG_WITH_ARM_TRUSTED_FW` when you poring OP-TEE to a new platform.

**Comment by Atomar25** [comment]
Hello @Iorc ,  Defined CFG_WITH_ARM_TRUSTED_FW for my platform :$(call force,CFG_WITH_ARM_TRUSTED_FW,y) in conf.mk .

Wondering, if on ATF side as well, one needs to register SPD?

**Comment by lorc** [comment]
Hi, @Atomar25,

Yes, ARM TF supports multiple different SPDs, so you need to specify the one you want to use.

**Comment by Atomar25** [comment]
Thanks for your reply.

I provided opteed as SPD to ATF commandline but now I see this during boot

WARNING: No OPTEE provided by BL2 boot loader, Booting device without OPTEE initialization. SMC`s destined for OPTEE will return SMC_UNK
