### ISSUE TITLE
Cannot map memory by register_phys_mem()

### ISSUE THREAD

**Issue by bradlin** [OP-TEE/optee_os#2311]
Hi,

When I try to use register_phys_mem(MEM_AREA_IO_SEC, 0xFF011000, 0x2000),
I get a error in

_core_init_mmu_tables(){
     ....
	for (n = 1; n < NUM_L1_ENTRIES; n++) {
		if (!l1_xlation_table[0][n]) {
			user_va_idx = n;
			break;
		}
	}
     assert(user_va_idx != -1);
    ....
}_

The NUM_L1_ENTRIES is 4 by default. The region of mapped memory for these entries are 0 - 1GB, 1GB - 2GB ,  2GB - 3GB, 3GB - 4GB.

We have mapped 0x10200000 ~ 0x141fffff,  0x32800000 - 0x456fffff, 0x80000000 - 0x80007fff .
If I try to add mapping for 0xFF011000, it will use all entries and no free entry for user_va_idx.
It seems a limitation in my current config. Could you give me some hint about which configs can extend this?

**Comment by lorc** [comment]
I think you need to increase `CFG_LPAE_ADDR_SPACE_SIZE` to next power of 2.

**Comment by bradlin** [comment]
Hi Lorc,

Thanks for your help. It works on my platform.

I also find a data structure using the 32bit address and it will cause problem when I increase this config. I will change this to _uintptr_t load_addr_ in my platform.
_struct user_ta_ctx {
    ...
    uint32_t load_addr;
    ...
}_

**Comment by lorc** [comment]
Hi @bradlin,

I think in this case it is better to use `vaddr_t` instead of `uint32_t`. Also it will be good to add a check for 32bit TA.

**Comment by bradlin** [comment]
Hi @lorc,

I will do as your suggestion.
Thanks a lot.
