### ISSUE TITLE
Hikey 620: increase TA RAM in OP-TEE

### ISSUE THREAD

**Issue by maxymedup** [OP-TEE/optee_os#2313]
Hi, 

I'm trying to increase the TA RAM by allocating more physical memory to OP-TEE on Hikey 620 up to 64MB so that `TZDRAM_BASE = 0x3C000000` and `TZDRAM_SIZE = 0x4000000`.  I've followed this issue #1396 which is still open, and basically update the files accordingly in arm-trusted-firmware, optee_os, linux, OpenPlatformPkg. I can share the changes I've made if needed.

However, the board boot sequence get stuck after booting BL32 (OP-TEE) and switching back to Normal World, see the log hereafter:
```
D/TC:0 add_phys_mem:526 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x3c000000 size 0x00068000
D/TC:0 add_phys_mem:526 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x3c068000 size 0x00198000
D/TC:0 add_phys_mem:526 CFG_TA_RAM_START type TA_RAM 0x3c200000 size 0x03e00000
D/TC:0 add_phys_mem:526 CFG_SHMEM_START type NSEC_SHM 0x3be00000 size 0x00200000
D/TC:0 add_phys_mem:526 CONSOLE_UART_BASE type IO_NSEC 0xf7000000 size 0x00200000
D/TC:0 add_phys_mem:526 PMUSSI_BASE type IO_NSEC 0xf8000000 size 0x00200000
D/TC:0 add_phys_mem:526 PERI_BASE type IO_NSEC 0xf7000000 size 0x00200000
D/TC:0 add_phys_mem:539 Physical mem map overlaps 0xf7000000
D/TC:0 add_phys_mem:526 PMX0_BASE type IO_NSEC 0xf7000000 size 0x00200000
D/TC:0 add_phys_mem:539 Physical mem map overlaps 0xf7000000
D/TC:0 add_phys_mem:526 PMX1_BASE type IO_NSEC 0xf7000000 size 0x00200000
D/TC:0 add_phys_mem:539 Physical mem map overlaps 0xf7000000
D/TC:0 add_phys_mem:526 GPIO6_BASE type IO_NSEC 0xf7000000 size 0x00200000
D/TC:0 add_phys_mem:539 Physical mem map overlaps 0xf7000000
D/TC:0 add_phys_mem:526 SPI_BASE type IO_NSEC 0xf7000000 size 0x00200000
D/TC:0 add_phys_mem:539 Physical mem map overlaps 0xf7000000
D/TC:0 verify_special_mem_areas:470 SDP memory [3b800000 3bc00000]
D/TC:0 verify_special_mem_areas:470 NSEC DDR memory [0 3b000000]
D/TC:0 verify_special_mem_areas:470 NSEC DDR memory [40000000 80000000]
D/TC:0 add_va_space:565 type RES_VASPACE size 0x00a00000
D/TC:0 add_va_space:565 type SHM_VASPACE size 0x02000000
D/TC:0 dump_mmap_table:698 type IO_NSEC      va 0x35200000..0x353fffff pa 0xf7000000..0xf71fffff size 0x00200000
(pgdir)
D/TC:0 dump_mmap_table:698 type NSEC_SHM     va 0x35400000..0x355fffff pa 0x3be00000..0x3bffffff size 0x00200000
(pgdir)
D/TC:0 dump_mmap_table:698 type TA_RAM       va 0x35600000..0x393fffff pa 0x3c200000..0x3fffffff size 0x03e00000
(pgdir)
D/TC:0 dump_mmap_table:698 type RES_VASPACE  va 0x39400000..0x39dfffff pa 0x00000000..0x009fffff size 0x00a00000
(pgdir)
D/TC:0 dump_mmap_table:698 type IO_NSEC      va 0x39e00000..0x39ffffff pa 0xf8000000..0xf81fffff size 0x00200000
(pgdir)
D/TC:0 dump_mmap_table:698 type SHM_VASPACE  va 0x3a000000..0x3bffffff pa 0x00000000..0x01ffffff size 0x02000000
(pgdir)
D/TC:0 dump_mmap_table:698 type TEE_RAM_RX   va 0x3c000000..0x3c067fff pa 0x3c000000..0x3c067fff size 0x00068000
(smallpg)
D/TC:0 dump_mmap_table:698 type TEE_RAM_RW   va 0x3c068000..0x3c1fffff pa 0x3c068000..0x3c1fffff size 0x00198000
(smallpg)
D/TC:0 core_mmu_entry_to_finer_grained:632 xlat tables used 1 / 32
D/TC:0 core_mmu_entry_to_finer_grained:632 xlat tables used 2 / 32
I/TC:
D/TC:0 init_canaries:185 #Stack canaries for stack_tmp[0] with top at 0x3c0d5a38
D/TC:0 init_canaries:185 watch *0x3c0d5a3c
D/TC:0 init_canaries:185 #Stack canaries for stack_tmp[1] with top at 0x3c0d6278
D/TC:0 init_canaries:185 watch *0x3c0d627c
D/TC:0 init_canaries:185 #Stack canaries for stack_tmp[2] with top at 0x3c0d6ab8
D/TC:0 init_canaries:185 watch *0x3c0d6abc
D/TC:0 init_canaries:185 #Stack canaries for stack_tmp[3] with top at 0x3c0d72f8
D/TC:0 init_canaries:185 watch *0x3c0d72fc
D/TC:0 init_canaries:185 #Stack canaries for stack_tmp[4] with top at 0x3c0d7b38
D/TC:0 init_canaries:185 watch *0x3c0d7b3c
D/TC:0 init_canaries:185 #Stack canaries for stack_tmp[5] with top at 0x3c0d8378
D/TC:0 init_canaries:185 watch *0x3c0d837c
D/TC:0 init_canaries:185 #Stack canaries for stack_tmp[6] with top at 0x3c0d8bb8
D/TC:0 init_canaries:185 watch *0x3c0d8bbc
D/TC:0 init_canaries:185 #Stack canaries for stack_tmp[7] with top at 0x3c0d93f8
D/TC:0 init_canaries:185 watch *0x3c0d93fc
D/TC:0 init_canaries:186 #Stack canaries for stack_abt[0] with top at 0x3c0da038
D/TC:0 init_canaries:186 watch *0x3c0da03c
D/TC:0 init_canaries:186 #Stack canaries for stack_abt[1] with top at 0x3c0dac78
D/TC:0 init_canaries:186 watch *0x3c0dac7c
D/TC:0 init_canaries:186 #Stack canaries for stack_abt[2] with top at 0x3c0db8b8
D/TC:0 init_canaries:186 watch *0x3c0db8bc
D/TC:0 init_canaries:186 #Stack canaries for stack_abt[3] with top at 0x3c0dc4f8
D/TC:0 init_canaries:186 watch *0x3c0dc4fc
D/TC:0 init_canaries:186 #Stack canaries for stack_abt[4] with top at 0x3c0dd138
D/TC:0 init_canaries:186 watch *0x3c0dd13c
D/TC:0 init_canaries:186 #Stack canaries for stack_abt[5] with top at 0x3c0ddd78
D/TC:0 init_canaries:186 watch *0x3c0ddd7c
D/TC:0 init_canaries:186 #Stack canaries for stack_abt[6] with top at 0x3c0de9b8
D/TC:0 init_canaries:186 watch *0x3c0de9bc
D/TC:0 init_canaries:186 #Stack canaries for stack_abt[7] with top at 0x3c0df5f8
D/TC:0 init_canaries:186 watch *0x3c0df5fc
D/TC:0 init_canaries:188 #Stack canaries for stack_thread[0] with top at 0x3c0e1638
D/TC:0 init_canaries:188 watch *0x3c0e163c
D/TC:0 init_canaries:188 #Stack canaries for stack_thread[1] with top at 0x3c0e3678
D/TC:0 init_canaries:188 watch *0x3c0e367c
D/TC:0 init_canaries:188 #Stack canaries for stack_thread[2] with top at 0x3c0e56b8
D/TC:0 init_canaries:188 watch *0x3c0e56bc
D/TC:0 init_canaries:188 #Stack canaries for stack_thread[3] with top at 0x3c0e76f8
D/TC:0 init_canaries:188 watch *0x3c0e76fc
D/TC:0 init_canaries:188 #Stack canaries for stack_thread[4] with top at 0x3c0e9738
D/TC:0 init_canaries:188 watch *0x3c0e973c
D/TC:0 init_canaries:188 #Stack canaries for stack_thread[5] with top at 0x3c0eb778
D/TC:0 init_canaries:188 watch *0x3c0eb77c
D/TC:0 init_canaries:188 #Stack canaries for stack_thread[6] with top at 0x3c0ed7b8
D/TC:0 init_canaries:188 watch *0x3c0ed7bc
D/TC:0 init_canaries:188 #Stack canaries for stack_thread[7] with top at 0x3c0ef7f8
D/TC:0 init_canaries:188 watch *0x3c0ef7fc
I/TC:  OP-TEE version: 3.1.0-26-g317b185-dev #2 mercredi 9 mai 2018, 17:21:52 (UTC+0000) aarch64
D/TC:0 tee_ta_register_ta_store:610 Registering TA store: 'REE' (priority 10)
D/TC:0 tee_ta_register_ta_store:610 Registering TA store: 'Secure Storage TA' (priority 9)
D/TC:0 mobj_mapped_shm_init:562 Shared memory address range: 3a000000, 3c000000
F/TC:0 plat_prng_add_jitter_entropy:75 plat_prng_add_jitter_entropy: 0xD11E
D/TC:0 peripherals_init:148 enable LD021_1V8 source (pin 35) on LS connector
D/TC:0 spi_init:85 take SPI0 out of reset
D/TC:0 spi_init:93 PERI_SC_PERIPH_RSTDIS3: 0x0
D/TC:0 spi_init:102 PERI_SC_PERIPH_RSTSTAT3: 0xfffbfd3e
D/TC:0 spi_init:104 enable SPI clock
D/TC:0 spi_init:112 PERI_SC_PERIPH_CLKEN3: 0x0
D/TC:0 spi_init:115 PERI_SC_PERIPH_CLKSTAT3: 0x2402c1
D/TC:0 spi_init:126 configure gpio6 pins 0-3 as SPI
D/TC:0 spi_init:132 configure gpio6 pins 0-3 as nopull
I/TC:  Initialized
D/TC:0 init_primary_helper:885 Primary CPU switching to normal world boot
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x35000000
INFO:    SPSR = 0x3c9
```
At this stage UEFI is expected to start Grub and run Linux. 
Am I missing something or doing anything wrong?

Thanks in advance for your support.

**Comment by maxymedup** [comment]
I found what was missing thanks to maximum log level in UEFI and ARM-TF.

Actually, I got mislead by the Hikey Flash Device description in edk2/OpenPlatformPkg: UEFI (BL33) load address is `0x35000000` and size `0x000F0000`. However this is only the size of the Flash Device in RAM and it needs additional RAM following this range to load its internal modules, and these were overlapping the TZRAM. Changing the load address to `0x31000000` is working fine.

If you'd like I can submit a patch for Hikey 620, but keep in mind it will affects the 6 following repo from OPTEE, Linaro and 96Boads: 
- arm-trusted-firmware
- atf-fastboot
- build
- linux
- OpenPlatformPkg
- optee_os

**Comment by jbech-linaro** [comment]
> If you'd like I can submit a patch for Hikey 620, but keep in mind it will affects the 6 following repo from OPTEE, Linaro and 96Boads:

That would be great, but the tricky thing here is to sync it all, since there different maintainers for all the gits involved. Is there a hard dependency between all gits? Or would it be possible to send some of the patches separately?

**Comment by maxymedup** [comment]
Hi @jbech-linaro 

I had to modify constants in header files, linux device tree and Hikey flash descriptor. 

I believe with a top level build option we could select the 64 MB mapping or keep using the the default one in regular build. So I wouldn't say there is hard dependency, except that such an option must be carefully handled to make sure it's set in either in all modules or none. 

To do so we'll have to set the proper preprocessor option for Linux device tree and UEFI compilers, is it even possible?

**Comment by artorhem** [comment]
Hi @jbech-linaro 

I'm trying to increase the RAM on my Hikey board, and I am struggling with it. It'll be incredibly useful if you could share your patch.

**Comment by jbech-linaro** [comment]
@artorhem I have no patch for this. It is @maxymedup that has been working with this (and therefore have all the patches).

@maxymedup, I think keep using the default one in a regular build would be preferable. Regarding pre-processor options I don't dare to say much about it. If turns out to be doable and we have everything under a compile time flag, then it should be OK to merge this in pieces.

**Comment by maxymedup** [comment]
Hi,

Here are the patches for the 6 gits:
[patch_hikey_TZRAM_64MB.tar.gz](https://github.com/OP-TEE/optee_os/files/2075373/patch_hikey_TZRAM_64MB.tar.gz)

It's based on OPTEE v3.1 build for Hikey 620, without generic RAM layout. I've successfully implemented it in Hikey+AOSP build which embeds generic RAM layout so they are compatible and it should be easy to merge.

Basically I've added a top level Make option in build/hikey.mk called `CFG_TZRAM_SIZE ` to choose between the two mappings:
```
# TZ RAM size: 16 or 64 MB [default 16]
# In 64MB config HIKEY_TZRAM_64MB is defined
CFG_TZRAM_SIZE ?= 16
```
In case `CFG_TZRAM_SIZE=64` the option is cascaded to arm-trusted-firmware, atf-fastboot, linux, OpenPlatformPkg and optee_os in order to add `HIKEY_TZRAM_64MB` in the preprocessor options.

Most of time I managed update Hikey specific files only, expect for linux device tree where I had to modify Makefile.lib to append the option to the Device Tree Compiler's CPP flags.

One more thing, I'm using `CONFIG_ION_DUMMY_UNMAPPED_BASE=0x3b800000` instead of `0x3e800000 `in build/Kconfigs/hikey.conf but I don't know how to integrate this.

Feel free to comment and/or make some changes.
