### ISSUE TITLE
Is this a sizeof mismatch?

### ISSUE THREAD

**Issue by alezzdiki** [OP-TEE/optee_os#2330]
Hi all,
Coverity complains about a sizeof mismatch in calc_node_hash() @ fs_htree.c

https://github.com/OP-TEE/optee_os/blob/dc0f4ec2074a459f7bf6279e19dd3a68f86468f1/core/tee/fs_htree.c#L418

Then, it suggests " _Did you intend to use `sizeof (*meta)` instead of `sizeof (meta)`?_ "
Looking at the code I would think we should pass ` sizeof(*meta)`. What do you think?

Thanks

**Comment by jenswi-linaro** [comment]
It's looks like you're right. Do you want to supply a pull request fixing this or would you prefer if I did so?

**Comment by alezzdiki** [comment]
I would prefer you do it. Thanks
