### ISSUE TITLE
Connecting rpi via UART

### ISSUE THREAD

**Issue by Christian56** [OP-TEE/optee_os#2351]
Hi, 
Im having trouble setting the rpi with the uart up. I connected the rpi to the Computer via the USB2Uart calbe and try to communicate with it via "picocom -b 115200 /dev/ttyS0". However nothing happens. If i connect it to /dev/ttyUSB0 I can start the nfsboot and it boots fine, i guess. however afterwards it seems to get stuck as I cannot input any commands. I changed the inittab based on #1367 to 
ttyUSB0::askfirst:/bin/sh -sc ". /etc/profile" 
but im not sure if thats the right thing to do (doesnt seem to work anyway). 
I really would appreciate some help or any hints.

**Comment by jbech-linaro** [comment]
I was running my RPi3 two days ago, having that said I used my debian root fs, but I also have my old CPIO root fs laying around and there I have:
```bash
$ cat etc/inittab 
#
# /etc/inittab
#
::sysinit:/etc/init.d/rc.init
# ttyS0 used by RPi3
ttyS0::askfirst:/bin/sh -sc ". /etc/profile"
::ctrlaltdel:/sbin/poweroff
::shutdown:/etc/init.d/rc.shutdown
::restart:/sbin/init
```
But, it could be that it's a bit dated, since it's a while since I used that. But last time I used it, things where working as expected.

**Comment by Christian56** [comment]
my inittab looks the same now(changed ttyUSB0::askfirst:/bin/sh -sc ". /etc/profile" back because it didn't work). : 
```
$  cat inittab 
#
# /etc/inittab
#
::sysinit:/etc/init.d/rc.init
# ttyS0 used by RPi3

ttyS0::askfirst:/bin/sh -sc ". /etc/profile"
tty0::askfirst:/bin/sh -sc ". /etc/profile"
::ctrlaltdel:/sbin/poweroff
::shutdown:/etc/init.d/rc.shutdown
::restart:/sbin/init```

However I still can't access the RPI. Im sorry but I never used UART before so I'm not sure if im doing it right.  
```
$ sudo picocom -b 115200 /dev/ttyS0
picocom v1.7

port is        : /dev/ttyS0
flowcontrol    : none
baudrate is    : 115200
parity is      : none
databits are   : 8
escape is      : C-a
local echo is  : no
noinit is      : no
noreset is     : no
nolock is      : no
send_cmd is    : sz -vv
receive_cmd is : rz -vv
imap is        : 
omap is        : 
emap is        : crcrlf,delbs,

Terminal ready 
```

**Comment by Christian56** [comment]
So I reflashed my SD Card and updated the project. Now it works fine :). Im closing the issue now.
