### ISSUE TITLE
AES-CBC encryption/decryption error while sending input data every 64 bytes.

### ISSUE THREAD

**Issue by angelina-zhao** [OP-TEE/optee_os#2355]
I am using the optee-os with commit af8e04244a9233ce1f50d1febbd38acce77adc10, submitted on Jan. 15, 2018, (core: assert foreign interrupts are masked in get_core_pos())

In this version, I managed to use the AES APIs defined as cryptographic operations APIs to support AES-CBC operation from the normal world.  However, when sending the input data in multiple chunks, and when the individual chunk size is larger than 64 bytes, the AES-CBC decryption result is incorrect.

The detailed test case is:
1. Prepare a 240 bytes plain text A.
2. Start encryption.
    1. Prepare the cipher and call TEE_CipherInit() to start the encryption.
    2. Use TEE_CipherUpdate to feed the input ( plain text A).  the 240 bytes are send in four times 64bytes+64bytes+64bytes+48bytes)
    3. Call TEE_CipherDoFinal() to complete the operation, and get the encrypted text.
    4. Release all the resources for the encryption.
2. Start decryption.
    1. Prepare the cipher and call TEE_CipherInit() to start the decryption.
    2. Use TEE_CipherUpdate to feed the input ( plain text A).  the 240 bytes are send in four times 64bytes+64bytes+64bytes+48bytes)
    3. Call TEE_CipherDoFinal() to complete the operation, and get the result as plain text B.
    4. Release all the resources for the encryption.
3. Compare the plain text A and plain test B, and found that they are not same.

The difference between plain text A and plain text B is examined, and there is a pattern in it.
Since AES operation is processed in four chunks, the output is also in four chunks.

1. chunk1: 64 bytes (same between plain text A and B)
2. chunk2: 64 bytes.  The first 16 bytes differs, and the rest 48 bytes are same.
3. chunk3: 64 bytes.  The first 16 bytes differs, and the rest 48 bytes are same.
4. chunk4: 48 bytes.  The first 16 bytes differs, and the rest 32 bytes are same.

Additional tests on the same case show that:

1. AES-GCM, AES-ECB, AES-CTR mode are correct in this test.
2. For AES-CBC, if the sub-chunk is less than 64 bytes, the result is correct.  For example, if the 240 bytes are sent every 17 bytes (17 + 17 + 17 + 17 + 17 + 17 + 17 + 17 + 17 + 17 + 17 + 17 + 17 + 17 + 2 = 240), the plain text A and B are same.
3. For AES-CBC, the first chunk is always correct, even if the size of the chunk exceeds the 64 bytes.  For example, sending 240 bytes once, and the output is correct.

Is there any hint on this issue?  Thank you very much.

**Comment by jbech-linaro** [comment]
Hi @angelina-zhao , thanks for the detailed report. Without really having investigated I wonder if there could be any relation between this and what is mentioned in #2305 (even though you state that AES-CTR mode is correct for this case). In any case I think someone in the OP-TEE team has to look into this (better sooner than later).

**Comment by jforissier** [comment]
Hi @angelina-zhao ,

Are you using `CFG_CRYPTO_WITH_CE=y`? If so:
- Can you try with `CFG_CRYPTO_WITH_CE=n` and let us know if the test still fails?
- Is OP-TEE Aarch32 or Aarch64?

**Comment by angelina-zhao** [comment]
Yes, I am using the ARM Crypto Extension so I have CFG_CRYPTO_WITH_CE=y.  I will test with CFG_CRYPTO_WITH_CE=n case and come back as soon as I get the results.

I am using Aarch64 of OP-TEE. @jforissier

**Comment by jforissier** [comment]
Hi @angelina-zhao,

I cannot reproduce the issue with the latest OP-TEE and this simple [`xtest`](https://github.com/OP-TEE/optee_test) test case (encryption of 64 + 96 bytes, or 64 + 64 if I also trim the plain text and cipher text `ciph_data_aes_cbc_vect1_{p,c}tx`):
```diff
diff --git a/host/xtest/regression_4000.c b/host/xtest/regression_4000.c
index 75f8fa4..563eac7 100644
--- a/host/xtest/regression_4000.c
+++ b/host/xtest/regression_4000.c
@@ -2231,6 +2231,7 @@ static const struct xtest_ciph_case ciph_cases[] = {
                        ciph_data_aes_ctr_out4),
 
        XTEST_CIPH_CASE_AES_CBC(vect1, 11),
+       XTEST_CIPH_CASE_AES_CBC(vect1, 64),
 
        /* AES-CTS */
        XTEST_CIPH_CASE_AES_CTS(vect1, 13),
```

Does `xtest 4003` with the above patch applied pass on your platform?

Thanks.

**Comment by angelina-zhao** [comment]
I will get back to you as soon as I have tested with xtest 4003 with your patch.  thanks.

**Comment by angelina-zhao** [comment]
@jforissier 

I use XTEST 4003 with your patch, and can reproduce the CBC issue when ARM extension is used .  If use pure SW, XTEST 4003 can pass.

This is the result when running XTEST 4003 with CFG_CRYPTO_WITH_CE := y.  The byte 65 to byte 81 (16 bytes) differs:

o regression_4003.14 Cipher case 13 algo 0x10000110 line 2200        //$$$$$$$$$$$$$$$$$$$$$$$$$  error &&&&
vendor/asr/optee/optee_test/host/xtest/regression_4000.c:2396: out has an unexpected content:
Got
  43:69:70:68 65:72:20:62 6C:6F:63:6B 20:63:68:61  Cipher block cha
  69:6E:69:6E 67:20:28:43 42:43:29:20 69:73:20:61  ining (CBC) is a
  20:63:6F:6D 6D:6F:6E:20 63:68:61:69 6E:69:6E:67   common chaining
  20:6D:6F:64 65:20:69:6E 20:77:68:69 63:68:20:74   mode in which t
  **A5:91:70:FF DD:97:7A:BF 39:DF:88:43 E3:B7:51:08  ..p...z.9..C..Q.**
  6B:27:73:20 63:69:70:68 65:72:74:65 78:74:20:69  k's ciphertext i
  73:20:78:6F 72:65:64:20 77:69:74:68 20:74:68:65  s xored with the
  20:63:75:72 72:65:6E:74 20:62:6C:6F 63:6B:27:73   current block's
  20:70:6C:61 69:6E:74:65 78:74:20:62 65:66:6F:72   plaintext befor
  65:20:65:6E 63:72:79:70 74:69:6F:6E 2E:2E:2E:2E  e encryption....
Expected
  43:69:70:68 65:72:20:62 6C:6F:63:6B 20:63:68:61  Cipher block cha
  69:6E:69:6E 67:20:28:43 42:43:29:20 69:73:20:61  ining (CBC) is a
  20:63:6F:6D 6D:6F:6E:20 63:68:61:69 6E:69:6E:67   common chaining
  20:6D:6F:64 65:20:69:6E 20:77:68:69 63:68:20:74   mode in which t
  **68:65:20:70 72:65:76:69 6F:75:73:20 62:6C:6F:63  he previous bloc**
  6B:27:73:20 63:69:70:68 65:72:74:65 78:74:20:69  k's ciphertext i
  73:20:78:6F 72:65:64:20 77:69:74:68 20:74:68:65  s xored with the
  20:63:75:72 72:65:6E:74 20:62:6C:6F 63:6B:27:73   current block's
  20:70:6C:61 69:6E:74:65 78:74:20:62 65:66:6F:72   plaintext befor
  65:20:65:6E 63:72:79:70 74:69:6F:6E 2E:2E:2E:2E  e encryption....
  regression_4003.14 FAILED

Running XTEST 4003 with CFG_CRYPTO_WITH_CE := n pass the test.

Are you running the XTEST 4003 on the lasted code base?  I suspect whether my OPTEE version may not contain necessary fixes.  I am using [3.1.0-rc1]https://github.com/OP-TEE/optee_os/commits/3.1.0-rc1  which is updated on April 5th.

Thanks.

**Comment by jforissier** [comment]
Hi @angelina-zhao,
I probably won't have time to try 3.1.0-rc1 today or tomorrow, so in the mean time maybe you could try to update your environment to latest master?

**Comment by angelina-zhao** [comment]
@jforissier sure.  I will pull to the latest master and do test on that code base.

Thank you very much for your advice.

**Comment by jforissier** [comment]
@angelina-zhao I can reproduce the issue on master with a Aarch64 CE build (HiKey960 board). Sorry for the misleading comment above -- I think I had tested Aarch32 CE, which does not show the problem.

I will investigate and keep you posted.

**Comment by angelina-zhao** [comment]
@jforissier 

I have synchronized the libtomcrypt to latest master branch code and the problem still exist (as you mentioned above).

I have done further test, by changing the configuration in "core/lib/libtomcrypt/src/ciphers/sub.mk"
For ARM64_CE, by default, it is: aflags-aes_modes_armv8a_ce_a64.S-y += -DINTERLEAVE=4, which means: INTERLEAVE=4.
In this setting, XTEST 4003 will fail on XTEST_CIPH_CASE_AES_CBC(vect1, 64) only.

Changing it to: aflags-aes_modes_armv8a_ce_a64.S-y += -DINTERLEAVE=2.
In this setting, XTEST 4003 will fail on:
XTEST_CIPH_CASE_AES_CBC(vect1, 64)
XTEST_CIPH_CASE_AES_CTS(vect6, 17)
XTEST_CIPH_CASE_AES_CTS(vect6, 0x20)
XTEST_CIPH_CASE_AES_CTS(issue1203, 32)


And, if I remove this line in sub.mk, leaving INTERLEAVE undefined.  All test cases in Xtest 4003 can pass.  Hope this can give you some hint on narrowing down this issue.

Thanks.

**Comment by angelina-zhao** [comment]
It works.  So I should close this issue by clicking the "Close and comment" now?  or wait till the commit is merged?  Thanks.

**Comment by jforissier** [comment]
Thanks for reporting back. I have just merged the fix, so this issue can be closed now.
