### ISSUE TITLE
Open session why open TA ？

### ISSUE THREAD

**Issue by leesagacious** [OP-TEE/optee_os#2360]
HI 
    I am currently studying opentee， 
    There is a question, xtest open session, why opentee to load TA Two calls ？
`rpc_load(....)
{
   1 
   res = thread_rpc_cmd(OPTEE_MSG_RPC_CMD_LOAD_TA, 2, params);

   2 
   res = thread_rpc_cmd(OPTEE_MSG_RPC_CMD_LOAD_TA, 2, params);
}`

**Comment by jbech-linaro** [comment]
I don't understand the question, can you please try to clarify?

**Comment by jforissier** [comment]
I think I understand the question ;-)
The first call is to query the size of the TA, the second one actually loads it.

**Comment by jenswi-linaro** [comment]
And the rationale behind that is to have symmetry between the allocation and freeing of shared memory.
