### ISSUE TITLE
compiler.h __data definition breaks c++ iostream in aosp build env

### ISSUE THREAD

**Issue by vchong** [OP-TEE/optee_os#2365]
Hi,

If I include both `<iostream>` and `utee_defines.h` (which includes `compiler.h`) in a .cpp source file, I'll get errors like below:

```
In file included from external/libcxx/include/iostream:38:
In file included from external/libcxx/include/ios:216:
In file included from external/libcxx/include/__locale:15:
In file included from external/libcxx/include/string:470:
external/libcxx/include/string_view:204:34: error: expected '(' or '{'
        basic_string_view() _NOEXCEPT : __data (nullptr), __size(0) {}
                                        ^
out/target/product/hikey/optee/arm-plat-hikey/export-ta_arm64/host_include/compiler.h:41:17: note: expanded from macro '__data'
#define __data          __section(".data")
                        ^
out/target/product/hikey/optee/arm-plat-hikey/export-ta_arm64/host_include/compiler.h:40:22: note: expanded from macro '__section'
#define __section(x)    __attribute__((section(x)))
                        ^
```
```
In file included from external/libcxx/include/iostream:38:
In file included from external/libcxx/include/ios:216:
In file included from external/libcxx/include/__locale:15:
In file included from external/libcxx/include/string:470:
external/libcxx/include/string_view:214:5: error: expected '(' or '{'
                : __data(__s), __size(__len)
                  ^
out/target/product/hikey/optee/arm-plat-hikey/export-ta_arm64/host_include/compiler.h:41:17: note: expanded from macro '__data'
#define __data          __section(".data")
                        ^
out/target/product/hikey/optee/arm-plat-hikey/export-ta_arm64/host_include/compiler.h:40:22: note: expanded from macro '__section'
#define __section(x)    __attribute__((section(x)))
                        ^
```

https://android.googlesource.com/platform/external/libcxx/+/android-8.1.0_r29/include/string_view#204
https://android.googlesource.com/platform/external/libcxx/+/android-8.1.0_r29/include/string_view#214

Is there something that can be done here, or maybe I'm just not doing something properly?

Thanks

**Comment by jenswi-linaro** [comment]
`utee_defines.h` is only supposed to be used in secure world. For convenience of writing test cases we've made it available for xtest. Which defines is it that you need? Some of the defines would make sense to move to `tee_api_defines_extensions.h`.

**Comment by lorc** [comment]
Hi,

On 31 May 2018 at 19:36, vchong <notifications@github.com> wrote:
> Hi,
>
> If I include both <iostream> and utee_defines.h (which includes compiler.h)
> in a .cpp source file, I'll get errors like below:
>

As a workaround, you can try to include utee_defines.h in the end of includes.

> In file included from external/libcxx/include/iostream:38:
> In file included from external/libcxx/include/ios:216:
> In file included from external/libcxx/include/__locale:15:
> In file included from external/libcxx/include/string:470:
> external/libcxx/include/string_view:204:34: error: expected '(' or '{'
>         basic_string_view() _NOEXCEPT : __data (nullptr), __size(0) {}
>                                         ^
> out/target/product/hikey/optee/arm-plat-hikey/export-ta_arm64/host_include/compiler.h:41:17:
> note: expanded from macro '__data'
> #define __data          __section(".data")
>                         ^
> out/target/product/hikey/optee/arm-plat-hikey/export-ta_arm64/host_include/compiler.h:40:22:
> note: expanded from macro '__section'
> #define __section(x)    __attribute__((section(x)))
>                         ^
>
> In file included from external/libcxx/include/iostream:38:
> In file included from external/libcxx/include/ios:216:
> In file included from external/libcxx/include/__locale:15:
> In file included from external/libcxx/include/string:470:
> external/libcxx/include/string_view:214:5: error: expected '(' or '{'
>                 : __data(__s), __size(__len)
>                   ^
> out/target/product/hikey/optee/arm-plat-hikey/export-ta_arm64/host_include/compiler.h:41:17:
> note: expanded from macro '__data'
> #define __data          __section(".data")
>                         ^
> out/target/product/hikey/optee/arm-plat-hikey/export-ta_arm64/host_include/compiler.h:40:22:
> note: expanded from macro '__section'
> #define __section(x)    __attribute__((section(x)))
>                         ^
>
> https://android.googlesource.com/platform/external/libcxx/+/android-8.1.0_r29/include/string_view#204
> https://android.googlesource.com/platform/external/libcxx/+/android-8.1.0_r29/include/string_view#214
>
> Is there something that can be done here, or maybe I'm just not doing
> something properly?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
WBR Volodymyr Babchuk aka lorc [+380976646013]
mailto: vlad.babchuk@gmail.com

**Comment by vchong** [comment]
Thanks! Workaround works! Will work on moving stuffs to `tee_api_defines_extensions.h` in the future as necessary.
