### ISSUE TITLE
'make' only OPTEE in AOSP+OPTEE

### ISSUE THREAD

**Issue by wonn1e** [OP-TEE/optee_os#2366]
Currently, I have AOSP+OPTEE for HiKey(LeMaker version). I've followed this webpage from beginning.
[optee_android_manifest](https://github.com/linaro-swg/optee_android_manifest)

At the moment, I'm trying to add a very simple SMC call from kernel to OPTEE-os.
I'm sending the SMC call as fast-call thus, it's handled at **tee_entry_fast()** function.
The problem I have is that whenever I update my code in OPTEE, it is not reflected with the make command from the aforementioned website. 
```
make TARGET_BUILD_KERNEL=true TARGET_BOOTIMAGE_USE_FAT=true \
CFG_SECURE_DATA_PATH=y CFG_SECSTOR_TA_MGMT_PTA=y TARGET_TEE_IS_OPTEE=true \
TARGET_BUILD_UEFI=true
```
It specifically shows that it's for AOSP build, but for some reason, in order for my newly added SMC calls to be handled, I need to 'make ~~ clean' and rebuild again with the make command for AOSP. Without cleaning, the given make command will compile and produce a new 'build-...-.img', but the newly added code of OPTEE smc handler is not reflected.

Since I only need to compile OPTEE at the moment, I was wondering if there is any other 'make'  command to just compile the OPTEE world.

**Comment by vchong** [comment]
Delete these files/dirs:
```
out/dist
optee/optee_os/out
out/target/product/hikey/optee
out/target/product/hikey/kernel
out/target/product/hikey/hi6220-hikey.dtb
out/target/product/hikey/obj/kernel
out/target/product/hikey/boot*.img
```

Then re-run the 'make ~~' command from the aforementioned website.
Reflash `fip.bin` and boot image to your board.

**Comment by wonn1e** [comment]
Thank you @vchong 
This saved so much of my time.
