### ISSUE TITLE
Pager support for Trusted Applications

### ISSUE THREAD

**Issue by b49020** [OP-TEE/optee_os#2367]
Hi,

Does OP-TEE support pager for Trusted Applications? AFAIK pager support is available for OP-TEE OS.

Thanks,
Sumit

**Comment by jforissier** [comment]
Hi Sumit,

Yes, `CFG_PAGED_USER_TA`.

**Comment by b49020** [comment]
@jforissier  Thanks for the answer.
Does this TA pager works on similar lines as for OS i.e. if it uses SRAM to page TA from DRAM? If yes SRAM also need to be shared among TEE pager and TA pager.

**Comment by etienne-lms** [comment]
Yes. It is the same pager unit. One difference between core memory and TAs memory is that RAM pages in the TA memory can be paged out (encrypted/hashed and save in external RAM) when really missing space.

**Comment by b49020** [comment]
Thanks @etienne-lms

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
