### ISSUE TITLE
SE-API PCSC-Passthru Issues reading/writing memory between OPTEE and QEMU

### ISSUE THREAD

**Issue by jgrangethales** [OP-TEE/optee_os#2368]
I'm trying to get the PCSC passthru driver working for the SE-API. (https://github.com/OP-TEE/optee_os/blob/master/documentation/se_api_design.md)

I followed the instructions (doing a manual merge on qemu as the differences were too great).  The situation i have now, is that I can talk to a simulated javacard fine (have ATR transfer and APDU transfer) in the REE linux using the supplied driver (so I'm happy my setup is fine and the QEMU mods are working).

The problem I'm seeing is that when running the SE_api with the passthru_reader driver, I can't get data transferred between QEMU and OPTEE using the tx_addr and rx_addr registers.  The register data transfer works fine (i can write on the OPTEE side and see the correct behaviour on the QEMU side).   The problem is that if, say, I've put data into the address pointed to by PCSC_REG_READER_TX_ADDR, it is read as all zeroes on the QEMU side.  The reverse is true, if QEMU puts data into memory pointed to by the PCSC_REG_READER_RX_ADDR, then OPTEE reads it as all zeroes.

This means that reader/passthru_reader/reader.c:pcsc_reader_get_atr always returns zeroes (though of the expected length as the register transfer works!) and reader/passthru_reader/reader.c:pcsc_reader_transmit will always send an APDU containing only zeroes to the secure element and will only return zeroes back to OPTEE (I can see the APDU bytes going over the wire outside QEMU)

I'm running the cortex a5 vexpress on qemu, btw (default build)

My question is **am I missing some sort of memory mapping instruction** to ensure this transfer works (virt_to_phys() returns the same address as I put in) or should I be restricting the memory regions to ones that can be physically mapped (I don't understand enough about the memory management to make sensible comments I'm afraid)

**Comment by jenswi-linaro** [comment]
This is a feature we haven't tested/used in a long time. Since then has QEMU introduced enforcement of the ns-bit so secure memory only can be read if mapped as secure memory.

**Comment by jgrangethales** [comment]
Thanks for the response.  I appreciate this code is a bit old, but it would really help me to get the simulator up and running.
The memory for the registers, etc is registered in optee using register_phys_mem(MEM_AREA_IO_SEC, PCSC_BASE, 0x1000); - should i be doing the same for the area that contains the txrx buffers?  Is there anything I should be doing on the qemu side regarding mapping as secure memory?

**Comment by jenswi-linaro** [comment]
It could very well be that the device isn't able to read secure memory any longer due to this new enforcement of the ns-bit. On the other hand, I haven't looked into the simulator part of this so I could be completely mistaken.
