### ISSUE TITLE
Boot hangs at "Starting Kernel"

### ISSUE THREAD

**Issue by Bolvach-BVM** [OP-TEE/optee_os#2374]
Hello.

I'm trying to get OP-TEE on imx6q-sabresd. I follow the guide by @MrVan at http://mrvan.github.io/optee-imx6q-sabresd, but there are some steps that I'm not quite understanding:

1. I created two partitions: a FAT partition containing the zImage, imx6q-sabresd.dtb and uTee file; a ext4 partition containing OP-TEE Client and OP-TEE Xtest. I see that the ext4 partition needs to also contain the rootfs, where should I get it from?

2. In the guide there is a U-Boot command that I dont know what it means: "run mmcargs". What should I do at this point?

-------------------------------------------------------------------------

This is the log that hangs on the "Starting Kernel":

=> fatload mmc 0:2 0x12000000 zImage; fatload mmc 0:2 0x18000000 imx6q-sabresd.dtb; fatload mmc 0:2 0x20000000 uTee; bootm 0x20000000 - 0x18000000

reading zImage
8253680 bytes read in 467 ms (16.9 MiB/s)
reading imx6q-sabresd.dtb
49357 bytes read in 22 ms (2.1 MiB/s)
reading uTee
278580 bytes read in 42 ms (6.3 MiB/s)

Booting kernel from Legacy Image at 20000000...
Image Name:
Image Type: ARM Linux Kernel Image (uncompressed)
Data Size: 278516 Bytes = 272 KiB
Load Address: 4dffffe4
Entry Point: 4e000000
Verifying Checksum ... OK

Flattened Device Tree blob at 18000000
Booting using the fdt blob at 0x18000000
Loading Kernel Image ... OK

CACHE: Misaligned operation at range [4dffffe4, 4e043fe4]
Using Device Tree in place at 18000000, end 1800c3bd

Starting kernel ...

-------------------------------------------------------------------------

Sorry if these questions are already answered elsewhere, but I couldn't find them. I would appreciate if someone could point me in the right direction. Much appreciated.

**Comment by Amit-Radur** [comment]
Can you just try loading only uTee binary from u-boot prompt ?

=> fatload mmc 0:2 0x20000000 uTee;bootm 0x20000000

**Comment by Bolvach-BVM** [comment]
Hello @Amit-Radur. It gets stuck at "Starting kernel ...". I've also tried running this same uTee in a Nitrogen6X and I get the same result.

**Comment by Amit-Radur** [comment]
Hello, 

Can you share, how did you compile your uTee image ?

**Comment by Bolvach-BVM** [comment]
@Amit-Radur Hello, I checked again how to compile the uTee and saw that I missed a parameter. I will close this now.
