### ISSUE TITLE
ObjectInfo.ObjectSize = 0 when EC Key is imported.

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_os#2386]
I am importing a prime256v1 EC key generated by openssl into the OP-TEE.

Series of call while importing the key.

- TEE_AllocateTransientObject(TEE_TYPE_ECDSA_KEYPAIR, 256, &tObject);

- Made an array of TEE_Attributes (tee_attrs) and populated with following attributes:
TEE_ATTR_ECC_PRIVATE_VALUE
TEE_ATTR_ECC_PUBLIC_VALUE_X
TEE_ATTR_ECC_PUBLIC_VALUE_Y
TEE_ATTR_ECC_CURVE= TEE_ECC_CURVE_NIST_P256

- TEE_PopulateTransientObject(tObject, tee_attrs, tee_attr_count);

- Now get the Object Info by TEE_GetObjectInfo1(pObject, &objectInfo);
Then objectInfo.objectSize = 0 and objectInfo.maxObjectSize = 256.

But when I generate the prime256v1 ECC Key from OPTEE and get Object Info of object 
Then objectInfo.objectSize = 256 and objectInfo.maxObjectSize = 256.

After some debugging I found that while Populating attributes in object in OP-TEE we search for flag TEE_TYPE_ATTR_SIZE_INDICATOR in the attributes if found will add the size of that attribute in ObjectSize.

In Case of RSA, TEE_TYPE_ATTR_SIZE_INDICATOR flag is associated with TEE_ATTR_RSA_MODULUS
but in case of EC there is no attribute having this TEE_TYPE_ATTR_SIZE_INDICATOR  flag set that's why ObjectSize is not getting set in EC case.

Please check if it is a bug or intentional, because I am new to EC stuff and somewhere I read that size of EC key must not be equal to 256 (in case of P256), It can also be less that that.

If this is the case  then we should not be setting ObjectSize also when generating key in OPTEE.

Please check if my understanding is correct.

Thanks
Sahil

**Comment by jenswi-linaro** [comment]
This seems like a bug. However, exactly what is the key size in this case isn't clear to me. I suppose it's the curve number that needs to be translated.

**Comment by jforissier** [comment]
@jenswi-linaro +1
I see no specific details in the GlobalPlatform spec. Let's put the curve number in `objectSize`, at least it will be consistent with what happens when OP-TEE creates the key. @sahilnxp would you create a pull request?

**Comment by sahilnxp** [comment]
Yes, sure.
Will raise a pull request for this.
