### ISSUE TITLE
How optee_os switch to kernel

### ISSUE THREAD

**Issue by yilingxu** [OP-TEE/optee_os#2391]
Hi,

I'm learning the boot flows of optee on imx6q. From the source code, It seems the boot flow is ROM--->uboot--->optee-os--->kernel, am I right?

If I am right, how optee-os switch to kernel? Can anyone help me pointing out the exact function?

Thanks,

Yiling Xu

**Comment by MrVan** [comment]
@yilingxu Yes, we are using this flow, some others might be using ROM->SPL->OPTEE->U-Boot->Kernel. It is sm_smc_entry which functions the switch.

**Comment by yilingxu** [comment]
@MrVan Thanks for your reply, and I would like to confirm the execution flow I understand is right :

1. The entry function of op-tee OS is "_start", which is defined at generic_entry_a32.S?

2. In generic_entry_a32.S, at the end of function "reset_primary" and "reset_secondary", set smc #0, switch jump to function "sm_vect_table"(sm_a32.S) in monitor mode, then call function "sm_smc_entry" to start the linux kernel ?
3. If 2 is right, both "reset_primary" and "reset_secondary" jump to monitor mode, which starts the linux kernel indeed?

4. If I want to authenticate linux kernel before it starts, the authentication function should be put in "sm_smc_entry", before NS is set to 1? 

Too many questions, thanks.

Yiling Xu

**Comment by vsivanagulu** [comment]
is optee support barebox

**Comment by MrVan** [comment]
It's not optee support barebox. It is whether barebox support optee boot.

**Comment by vsivanagulu** [comment]
ok. @MrVan . 
is Barebox support optee boot or not for I.MX6 ULL.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
