### ISSUE TITLE
Performance of Trusted Application

### ISSUE THREAD

**Issue by Tigerly** [OP-TEE/optee_os#2392]
Hello,
I was wondering the performance of the application running in the secure world.
Suppose I have an application running in the normal world. Now, I want to move it to the secure world. I'm curious about whether the application running in the secure world is slower than in the normal world. In other words, whether the trusted os and hardware will slow down the performance?

Thanks in advance!

**Comment by jenswi-linaro** [comment]
Unless the TAs are paged you can expect more or less the same performance.

**Comment by Tigerly** [comment]
@jenswi-linaro Thank you so much for quickly replying. Would it be possible to explain more details, or give me some relevant documents to learn why the performance in the TEE is still good. Thanks!

**Comment by jenswi-linaro** [comment]
Loading of code and switch between secure and non-secure world will add some overhead. 
Caches etc are used also in secure mode, so there's no reason why the code should run slower.
If paging of TAs is enabled it's another story though.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
