### ISSUE TITLE
What does TEE_ALG_ECDSA_P192, TEE_ALG_ECDSA_P256 and other means ?

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_os#2398]
Came across following algorithms in TEE Specification.
TEE_ALG_ECDSA_P192, TEE_ALG_ECDSA_P224, TEE_ALG_ECDSA_P256,  TEE_ALG_ECDSA_P384, EE_ALG_ECDSA_P521

I am confused about these, if these should be related to the ECDSA Key size or SHA algorithms like in RSA
TEE_ALG_RSASSA_PKCS1_V1_5_SHA1, TEE_ALG_RSASSA_PKCS1_V1_5_SHA224 etc.

and if I need to implement ECDSA_SHA1 signing algorithm,
- With which algorithm should I create TEE_AllocateOperation(), or does it depend on the Key Size with which I am doing Signing ?

**Comment by sahilnxp** [comment]
Any comments ?

**Comment by jforissier** [comment]
Hi @sahilnxp,

For ECDSA with SHA1, you should pass `TEE_ALG_ECDSA_P192` to `TEE_AllocateOperation()`.
The algorithm identifiers have been modified as follows in the TEE Internal Core API v1.1.2:

```
          Table B-2, Deprecated Algorithm Identifiers
+---------------------------------------------------------------------------+
| Identifier in v1.1                  | Replacement Identifier              |
+---------------------------------------------------------------------------+
| ECDSA algorithm identifiers should be tied to the size of the digest, not |
| the key. The key size information is provided with the key material.      |
+---------------------------------------------------------------------------+
| TEE_ALG_ECDSA_P192*                 | TEE_ALG_ECDSA_SHA1                  |
| TEE_ALG_ECDSA_P224*                 | TEE_ALG_ECDSA_SHA224                |
| TEE_ALG_ECDSA_P256*                 | TEE_ALG_ECDSA_SHA256                |
| TEE_ALG_ECDSA_P384*                 | TEE_ALG_ECDSA_SHA384                |
| TEE_ALG_ECDSA_P521*                 | TEE_ALG_ECDSA_SHA512                |
+---------------------------------------------------------------------------+
```

We have not yet reflected these changes in OP-TEE.

**Comment by sahilnxp** [comment]
For ECDSA with SHA1, If I use TEE_ALG_ECDSA_P192 and send ec object of size other than 192 bits, It is giving me error that TEE_ERROR_NOT_SUPPORTED which should not be the case, It should be working with any object size.
I think, It is not taking any consideration of SHA algorithm as of now.

For now I think we need to pass the TEE_ALG_ECDSA_P192 if your ec object with which you are signing is of 192 bits and TEE_ALG_ECDSA_P256 for 256 bit ec object and so on.

This needs to be changed as already written
> ECDSA algorithm identifiers should be tied to the size of the digest, not the key. The key size information is provided with the key material.  

Please confirm if my understanding is correct.

**Comment by jforissier** [comment]
> For now I think we need to pass the TEE_ALG_ECDSA_P192 if your ec object with which you are signing is of 192 bits and TEE_ALG_ECDSA_P256 for 256 bit ec object and so on.

I believe you're correct. There has been some confusion in the GP specifications around ECDSA. The new identifiers will have different values and will be treated differently (with the constraint that digest size should be at least equal to key size). Sorry for the misleading comment.

**Comment by jforissier** [comment]
No plan AFAICT. Note that GP TEE Inernal Core API v1.2 is due to enter public review soon so it might be a good idea to base any API update on that version.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
