### ISSUE TITLE
How to boot optee on Colibri iMX6ull board?

### ISSUE THREAD

**Issue by rdhobi** [OP-TEE/optee_os#2405]
I'm following http://mrvan.github.io/optee-imx6ul for running optee on Colibri iMX6ullboard but didn't get success. I have followed below steps:

```
tftp 0x81000000 colibri-imx6ull/zImage
tftp 0x82000000 colibri-imx6ull/imx6ull-colibri-wifi-eval-v3.dtb
tftp 0x83000000 colibri-imx6ull/uTee
bootm 0x83000000 - 0x82000000
## Booting kernel from Legacy Image at 83000000 ...
   Image Name:   
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    258708 Bytes = 252.6 KiB
   Load Address: 9c0fffe4
   Entry Point:  9c100000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 82000000
   Booting using the fdt blob at 0x82000000
   Loading Kernel Image ... OK
CACHE: Misaligned operation at range [9c0fffe4, 9c13f2a4]
   Using Device Tree in place at 82000000, end 8200c61f
   Updating MTD partitions...

Starting kernel ...
```
Board is hanging after Starting kernel and got "**CACHE: Misaligned operation at range [9c0fffe4, 9c13f2a4]**" @MrVan: Can you please help?
I'm generatin uTee image using following command
`mkimage -A arm -O linux -C none -a 0x9c0fffe4 -e 0x9c100000 -d ./out/arm-plat-imx/core/tee.bin uTee`

How to decide load address and entry point while generating uTee image?

**Comment by rdhobi** [comment]
Any suggestion please?

**Comment by rdhobi** [comment]
Colibri iMX6ull has 512MB RAM so by executing following command have solved issue.
`mkimage -A arm -O linux -C none -a 0x9DFFFFE4 -e 0x9E000000 -d ./out/arm-plat-imx/core/tee.bin uTee`

**Comment by jsrc27** [comment]
Hi @rdhobi,

I'm trying to also boot OPTEE using the Colibri i.MX6ULL. I am still having some issues, do you recall the exact procedure you used? Did you use the u-boot and kernel sources in the blog post you followed? Or did you use the u-boot and kernel sources provided by Toradex for the Colibri i.MX6ULL hardware?

Anything you can recall would be appreciated.

**Comment by rdhobi** [comment]
> Hi @rdhobi,
> 
> I'm trying to also boot OPTEE using the Colibri i.MX6ULL. I am still having some issues, do you recall the exact procedure you used? Did you use the u-boot and kernel sources in the blog post you followed? Or did you use the u-boot and kernel sources provided by Toradex for the Colibri i.MX6ULL hardware?
> 
> Anything you can recall would be appreciated.

Can you please provide steps which you are following?
