### ISSUE TITLE
get the build time

### ISSUE THREAD

**Issue by leesagacious** [OP-TEE/optee_os#2406]
DMSG("!!!BOOT_INIT_TESTS ENDS, %s %s !!!!\n", __DATE__, __TIME__);

use of these two macros is not rigorous

Is there any other way to do it  ?

See your feedback

**Comment by jenswi-linaro** [comment]
There's already a printout for this, for example:
```
I/TC:  OP-TEE version: 3.1.0-146-gde86387555d6 #8 tis 19 jun 2018 10:25:17 UTC arm
```

**Comment by leesagacious** [comment]
HI : 
     error : Use of the 'DATE' macro makes the build non-deterministic

**Comment by leesagacious** [comment]
@jenswi-linaro   please answering this Question

**Comment by jbech-linaro** [comment]
Are you talking about `-Wdate-time`? I.e., that you don't get identical subsequent builds after running make twice in row? The error message could be disabled by `-Wno-error=date-time` (in https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/sub.mk). Alternatively you can build with a debug level such that IMSG are not included.

If that isn't sufficient, would you mind creating a patch for this that includes a CFG compile time flag that makes it possible to enable/disable this when needed. I.e., add a CFG around this?
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/generic_boot.c#L910

**Comment by leesagacious** [comment]
hi @jbech-linaro 
    I tried your method and it will not work

**Comment by jbech-linaro** [comment]
> hi @jbech-linaro
> I tried your method and it will not work

Which of them? How did you try it? Would you mind post some code and/or commands?

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
