### ISSUE TITLE
symbolize.py makes assumptions on cross compiler name

### ISSUE THREAD

**Issue by etienne-lms** [OP-TEE/optee_os#2408]
**symbolize.py** expect cross toolchain is **aarch64-linux-gcc-** for 64bit targets or **arm-linux-gnueabihf-** for 32bit target. Build environment using another toolchain must modify **symbolize.py** accordingly.

Could the script rely on `CROSS_COMPILE` if available?

At https://github.com/OP-TEE/optee_os/blob/3.1.0/scripts/symbolize.py#L102:
```python
        if 'ARM aarch64,' in output[0]:
            self._arch = 'aarch64-linux-gnu-'
        elif 'ARM,' in output[0]:
             self._arch = 'arm-linux-gnueabihf-'
```

**Comment by jforissier** [comment]
I agree, it would seem reasonable to take into account `CROSS_COMPILE`/`CROSS_COMPILE32`/`CROSS_COMPILE64` similar to what we have in https://github.com/OP-TEE/optee_os/blob/3.1.0/mk/config.mk#L20-L22.
