### ISSUE TITLE
Any plan to add a stand libc to TEE OS for TA?

### ISSUE THREAD

**Issue by junwua** [OP-TEE/optee_os#2411]
When i write a TA, need some stand libc functions, but  there is no libc in the opee-os.
And i find in another tee os MICROTRUST_TEE, add a uclibc. I try to add an uclibc to the 
opee-os/lib, compiling....

**Comment by jenswi-linaro** [comment]
There's no plans to provide a complete libc for TAs. However, when there's a need for another standard function we usually add it to libutils. We usually import sources from newlib since it has permissive license.

Code without a permissive license will not be accepted.

**Comment by jforissier** [comment]
uClibc is LGPL so it is not compatible with OP-TEE OS license-wise.

**Comment by junwua** [comment]
@jenswi-linaro  you mean if i need some functions, need add to libutils.
@jforissier  i find two libs, glibc, uclibc. we needn't all the function, some function can't
use and run in tee os. but we use the microtrust tee, it has all the uclibc, and support C++ too.
as you mean, the solve way is adding the functions which need use?
Thanks a lot.

**Comment by junwua** [comment]
Thanks, @jenswi-linaro & @jforissier

**Comment by junwua** [comment]
@jforissier  which branch use?  I find the optee_os has a newlib dir, what
version used?  thanks.
  remotes/origin/binutils-2_10-branch
  remotes/origin/binutils-2_11-branch
  remotes/origin/binutils-2_12-branch
  remotes/origin/binutils-2_13-branch
  remotes/origin/binutils-2_14-branch
  remotes/origin/binutils-2_15-branch
  remotes/origin/binutils-2_16-branch
  remotes/origin/binutils-2_17-branch
  remotes/origin/binutils-2_18-branch
  remotes/origin/binutils-2_19-branch

**Comment by junwua** [comment]
remotes/origin/cgf-dev-branch
  remotes/origin/cr-0x3b58
  remotes/origin/cr-0x5e6
  remotes/origin/cr-0x5ef
  remotes/origin/cr-0x5f1
  remotes/origin/cr-0x9b
  remotes/origin/cr-0x9c
  remotes/origin/cr-0x9d
  remotes/origin/cr-0x9e
  remotes/origin/csl-arm-20050325-branch
  remotes/origin/cv-branch
  remotes/origin/cv-branch-2
  remotes/origin/cv-post-1_7_9
  remotes/origin/cygnus
  remotes/origin/cygwin-1-1-4
  remotes/origin/cygwin-1-3-1
  remotes/origin/cygwin-1-3-10-1
  remotes/origin/cygwin-1-3-11-3
  remotes/origin/cygwin-1-3-12-1
  remotes/origin/cygwin-1-3-13-1
  remotes/origin/cygwin-1-3-13-2
  remotes/origin/cygwin-1-3-14-1
  remotes/origin/cygwin-1-3-15-1
  remotes/origin/cygwin-1-3-16-1
  remotes/origin/cygwin-1-3-17-1

**Comment by jenswi-linaro** [comment]
There's no particular version used in that directory. It would surprise me if there's been any significant change upstream to those files the last 5 years.

**Comment by junwua** [comment]
you mean just get the  master branch?
remotes/origin/HEAD -> origin/master

**Comment by junwua** [comment]
2016-12-22: newlib-2.5.0.tar.gz (17.9MB)
2016-10-25: newlib-2.4.0.20161025.tar.gz (17.9MB)
2016-09-23: newlib-2.4.0.20160923.tar.gz (17.9MB)
2016-05-27: newlib-2.4.0.20160527.tar.gz (17.8MB)
2016-03-29: newlib-2.4.0.tar.gz (17.6MB)
2016-02-26: newlib-2.3.0.20160226.tar.gz (17.7MB)
2016-01-04: newlib-2.3.0.20160104.tar.gz (17.7MB)
2015-10-23: newlib-2.2.0.20151023.tar.gz (17.6MB)
2015-09-24: newlib-2.2.0.20150924.tar.gz (17.5MB)
2015-08-24: newlib-2.2.0.20150824.tar.gz (17.5MB)
2015-07-23: newlib-2.2.0.20150723.tar.gz (17.5MB)
2015-06-23: newlib-2.2.0.20150623.tar.gz (17.5MB)
2015-05-26: newlib-2.2.0.20150526.tar.gz (17.5MB)
2015-04-23: newlib-2.2.0.20150423.tar.gz (17.5MB)
2015-03-23: newlib-2.2.0.20150323.tar.gz (17.4MB)
2015-02-25: newlib-2.2.0.20150225.tar.gz (16.7MB)
2015-01-19: newlib-2.2.0-1.tar.gz (16.6MB)
2014-12-18: newlib-2.2.0.tar.gz (16.5MB)
2013-12-23: newlib-2.1.0.tar.gz (16.2MB)
2012-12-20: newlib-2.0.0.tar.gz (15MB)

**Comment by junwua** [comment]
which year?  thanks.
2014-12-18: newlib-2.2.0.tar.gz (16.5MB)
2013-12-23: newlib-2.1.0.tar.gz (16.2MB)

**Comment by jenswi-linaro** [comment]
Latest release seems reasonable. The process for bringing in functions from newlib i a bit ad hoc.

**Comment by junwua** [comment]
we try to copy some files, but the include head file compile error.  lots of defines, macro
different. so need modify a lot.

**Comment by jenswi-linaro** [comment]
Header files are tricky, we're mostly doing implementations from scratch to match the C standard.

I can give better advice if you have a concrete example.

**Comment by junwua** [comment]
like  cdefs.h, the optee_os included  is very old.

**Comment by jenswi-linaro** [comment]
As far as I know there's no standard defining `sys/cdefs.h`. We would probably not have created that file at all today. I'd rather actually see it gone, but for the time being I guess some small changes could be acceptable if they solve a problem.

So if there's some small macro you need to have in `sys/cdefs.h` we can probably take that, but if it's more or less the entire newlib file then we need to start looking for other options.

**Comment by junwua** [comment]
How to add file attachment in the issue ?
I have a polarssl need to compile in a TA.

**Comment by junwua** [comment]
@jenswi  thank you , i have receive your mail.
we meet two problem, another is C++ TA compile, because
our ta has some cpp files.  we compile ok in microtrust tee os, we
try to move the ta to optee-os. 
 now i  know the solve way, first we solve the libc functions, it seems
just do some work. Thanks, all linaro.

**Comment by hisy2013** [comment]
@jenswi-linaro I want to add some libc standard function in tee for example fopen. Can you give me suggestion how to do it Thanks

**Comment by jbech-linaro** [comment]
> @jenswi-linaro I want to add some libc standard function in tee for example fopen. Can you give me suggestion how to do it Thanks

That is probably not a good idea. The TEE (just a Linux kernel) don't have any direct file access. The way to work with "files" in the TEE is to use the secure storage functionality, see `TEE_{Read/Write}ObjectData`, `TEE_{Create/Open}PersistentObject` and friends. If you insist on having `fopen`, then I would probably wrap the functions I mentioned in a `fopen` function in your TA. But it would still be hard to "mimic" a true `fopen` API. In general, I repeat `fopen` in the TEE is not a good idea.

**Comment by hisy2013** [comment]
@jbech-linaro I want to open a file (or devices) and operate it in TA.
