### ISSUE TITLE
why the gic not use the itr_handler flag ITRF_TRIGGER_LEVEL?

### ISSUE THREAD

**Issue by junwua** [OP-TEE/optee_os#2416]
Hi,  why the gic not use the itr_handler flag ITRF_TRIGGER_LEVEL?
set a gic irq, need add a gic irq num, irq Priority, irq group secure or non-secure,
irq sens Edge-triggered or Level-sensitive. but the gic function void gic_op_add
don't set the irq sens. but in the ATF code set,  when i add a gic irq, add the handle,
the handle cb always called, when i set the irq sens, it is ok. so, why?

**Comment by etienne-lms** [comment]
You are right. This should be added in the **gic.c** driver. If you have a proposal, do not hesitate to share.

**Comment by junwua** [comment]
ok, Thanks,  i just accord to the ATF code.
