### ISSUE TITLE
Documentation: Crypto: Links broken

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_os#2418]
While reading the Optee documentation, found 2 issues on crypto.md page.

1. Under [The crypto services [2]](https://github.com/OP-TEE/optee_os/blob/master/documentation/crypto.md#the-crypto-services-2)
> the system calls invoke a private abstraction layer: the Crypto API, which is declared in **crypto.h**

The link to crypto.h is broken.

2. Under [crypto_*() [3]](https://github.com/OP-TEE/optee_os/blob/master/documentation/crypto.md#crypto_-3)
>As shown above, families of algorithms can be disabled and **crypto.c** will provide default null implementations that will return TEE_ERROR_NOT_IMPLEMENTED.

The link to crypto.c is broken.

**Comment by jforissier** [comment]
Patch welcome.
