### ISSUE TITLE
Error: TEE_ERROR_OUT_OF_MEMORY   0xFFFF000C

### ISSUE THREAD

**Issue by Tigerly** [OP-TEE/optee_os#2420]
Hello,
I'm trying to send a byte array (size is about 8000 bytes) from REE to TEE.
So, on the client side (TEE), I try to allocate a shared memory by using TEEC_AllocateSharedMemory.

However, when running it, it always complains that the TEEC_AllocateSharedMemory causes out of memory (TEE_ERROR_OUT_OF_MEMORY   0xFFFF000C).

I set the enough stack and data size in the TA's user_ta_header_defines.h
#define TA_STACK_SIZE     (500 * 1024)
#define TA_DATA_SIZE        (500 * 1024)
but it doesn't work.

Also, if I set these two sizes too large, like 10* 1024*1024. The TEEC_OpenSession would be failed.

I run the TA on Docker with op-tee.

I was wondering how should I fix it?

Thanks in advance!

**Comment by sahilnxp** [comment]
TEEC_AllocateSharedMemory() doesn't get the memory from TA_STACK or TA_DATA segment.

This Shared Memory is managed by OP-TEE linux kernel driver.
OP-TEE Linux kernel driver makes an SMC to OP-TEE OS and get the information related to shared memory and then make pool for this.

There are 2 macros CFG_SHMEM_START and CFG_SHMEM_SIZE which is configured in platform_config.h of your platform.
May be you can check these macros if they are configured to right values.

@jbech-linaro @jforissier @jenswi-linaro please comment, if I am missing something.

**Comment by Tigerly** [comment]
Thanks!

I've tried to add below configuration into the **qemu-optee/bios_qemu_tz_arm/bios/platform_config.h** (I use docker to run op-tee environment)
#define CFG_SHMEM_START 0x3E000000
#define CFG_SHMEM_SIZE (8 * 1024 * 1024)

However, it still complains  0xFFFF000C - TEE_ERROR_OUT_OF_MEMORY error.

Is there anything wrong with my configuration?

**Comment by lorc** [comment]
Hi @Tigerly , could you please check if dynamic shared memory feature is enabled on your setup? 
Both OP-TEE and kernel driver should report about this during boot. 
Also, can you please share a snippet of code you use to allocate memory?
Also, did you tried smaller buffer size? Which size you were able to allocate?

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
