### ISSUE TITLE
How to compile ta with ISO C99?

### ISSUE THREAD

**Issue by Jamie-Cui** [OP-TEE/optee_os#2429]

**Comment by jforissier** [comment]
By using an ISO C99 compiler, I suppose.

**Comment by jenswi-linaro** [comment]
We're normally compiling with `-std=gnu99` (basically a super set of C99) in order to be able to use some extensions.

**Comment by Jamie-Cui** [comment]
Thanks for reply, some of my TA codes have mixed declarations and code which inflicts ISO C90 and when I compiled my code it shows:

~~~
ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
~~~

And also I have tried adding "cflags-my_ta.c-y += -std=gnu99"  in sub.mk, it doesn't work.

**Comment by jforissier** [comment]
Try `cflags-my_ta.c-y += -Wno-declaration-after-statement`.

**Comment by Jamie-Cui** [comment]
Thanks, it works!

**Comment by jforissier** [comment]
Even better: `cflags-remove-my_ta.c-y += -Wdeclaration-after-statement`.

**Comment by jenswi-linaro** [comment]
Or even better put the declarations were they belong... :-)

**Comment by jbech-linaro** [comment]
Maybe even time to start support "new" C-features that has been around for almost 20 years?

**Comment by jforissier** [comment]
> Maybe even time to start support "new" C-features that has been around for almost 20 years?

For optee_os at least, we want to keep the declarations at the beginning of blocks. It's just a matter of coding style (Linux kernel style). For TAs however, I wouldn't mind being a bit more permissive.

**Comment by alexisfrjp** [comment]
Linux kernel style is C11 now. Forget this pedantic useless old style that makes the code harder to read.

**Comment by jforissier** [comment]
@alexisfrjp do you have a link to support your claim? AFAICT the latest Linux kernel builds with [`-std=gnu89`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Makefile?h=v5.17-rc3#n514) as well as  [`-Wdeclaration-after-statement`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Makefile?h=v5.17-rc3#n936).

**Comment by alexisfrjp** [comment]
From 5.18, with `-std=gnu11 -Wno-shift-negative-value`, even better than C99.
https://lwn.net/ml/linux-kernel/CAHk-=wh97QY9fEQUK6zMVQwaQ_JWDvR=R+TxQ_0OYrMHQ+egvQ@mail.gmail.com/

**Comment by jenswi-linaro** [comment]
The kernel is still using -Wdeclaration-after-statement as far as I know.
