### ISSUE TITLE
boot sequence hanged after use IMSG

### ISSUE THREAD

**Issue by yilingxu** [OP-TEE/optee_os#2431]
Hi,

I want to see the value in register, so I "bl' to a function which achieve in C, and use IMSG to print the value, but the boot sequence hang after my function is called.

For example:
In generic_entry_a32.S:
mov	r0, r4		
mov	r1, r5		
mov	r2, r6		
bl  testfunc     //add my funciton
bl	generic_boot_init_primary
mov	r4, r0		

In generic_boot.c:
unsigned long testfunc(unsigned long pageable_part, unsigned long nsec_entry, unsigned long fdt){
	IMSG("testfunc %lu %lu %lu", pageable_part, nsec_entry, fdt);
	nsec_entry++;          //just make the parameter has been used, no means
	fdt++;                       // just make the parameter has been used, no means
	return pageable_part;         //ensure the r0 register not be changed
}

the boot sequence hanged when testfunc is called. 

But if I delete "IMSG("testfunc %lu %lu %lu", pageable_part, nsec_entry, fdt);" this line, the optee can boot normally.

Can anyone tell me why? And how can I read value in register?

Thanks!

Yiling Xu

**Comment by lorc** [comment]
Hi @yilingxu, this is because r1 and r2 are not preserved during function call.

**Comment by yilingxu** [comment]
Hi, @lorc, Thank you very much, after I change the code as follow, it works!
In generic_entry_a32.S:
	mov	r0, r4		
	mov	r1, r5		
	mov	r2, r6	
	bl  testfunc
	mov r1, r5
	mov r2, r6
	bl	generic_boot_init_primary
	mov	r4, r0

 So IMSG will rewrite in r1 and r2?

**Comment by lorc** [comment]
`IMSG` is a macro which will be expanded to actual debug print call. And yes, it might clobber r5 and r6 (any of r0-r15 actually). So your current code might fail if some function in debug print call path will alter values of r5 and r6. You might want to save them on stack or in r19-r28 (which are callee-saved). 
You need to check [ARMv8 ABI](http://infocenter.arm.com/help/topic/com.arm.doc.ihi0055b/IHI0055B_aapcs64.pdf). Section 5.1. It describes how registers are used for function calls and which registers will be preserved between calls.

**Comment by yilingxu** [comment]
@lorc Thank you.
