### ISSUE TITLE
data abort when accessing PTA from NW

### ISSUE THREAD

**Issue by zatkh** [OP-TEE/optee_os#2441]
I am getting the following error when invoking a function from my PTA. not sure what I am missing here.

D/TC:0 tee_ta_init_pseudo_ta_session:274 Lookup pseudo TA 4974b40c-fcb8-4f1e-9e0f-87c1b76d369b
D/TC:0 tee_ta_init_pseudo_ta_session:286 Open thello.pta
D/TC:0 tee_ta_init_pseudo_ta_session:300 thello.pta : 4974b40c-fcb8-4f1e-9e0f-87c1b76d369b
E/TC:0 
E/TC:0 Core data-abort at address 0x20 (translation fault)
E/TC:0  esr 0x96000006  ttbr0 0x0e178000   ttbr1 0x00000000   cidr 0x0
E/TC:0  cpu #0          cpsr 0x80000104
E/TC:0  x0  0000000000000000 x1  000000000e158620
E/TC:0  x2  00000000000005b8 x3  000000000e1142cc
E/TC:0  x4  0000000000000000 x5  000000000e146000
E/TC:0  x6  000000000e1460c8 x7  000000000e13e000
E/TC:0  x8  0000000000000070 x9  0000000000000000
E/TC:0  x10 0000000000000000 x11 0000000000000000
E/TC:0  x12 0000000000000000 x13 0000000000000000
E/TC:0  x14 0000000000000000 x15 0000000000000000
E/TC:0  x16 0000000000000000 x17 0000000000000000
E/TC:0  x18 0000000000000000 x19 0000000000000000
E/TC:0  x20 000000000e17c8e8 x21 000000000e16bce8
E/TC:0  x22 000000000e16bd50 x23 000000000e17c88c
E/TC:0  x24 0000000000000000 x25 0000000000000000
E/TC:0  x26 000000000e17c8b0 x27 00000000ffffffff
E/TC:0  x28 000000000e17c8e8 x29 000000000e17c720
E/TC:0  x30 000000000e1142d8 elr 000000000e114320
E/TC:0  sp_el0 000000000e17c720
E/TC:0 Call stack:
E/TC:0  0x000000000e114320
E/TC:0  0x000000000e104694
E/TC:0  0x000000000e115850
E/TC:0  0x000000000e1115f4
E/TC:0  0x000000000e108014
E/TC:0  0x000000000e102948
E/TC:0 Panic 'unhandled pageable abort' at core/arch/arm/kernel/abort.c:669 <abort_handler>
E/TC:0 Call stack:
E/TC:0  0x000000000e10adfc

**Comment by jforissier** [comment]
Hi @zatkh ,

> E/TC:0 Core data-abort at address 0x20 (translation fault)

You probably have a NULL pointer somewhere. 0x20 could be an offset into a structure.
Filter the stack dump through `./optee_os/scripts/symbolize.py -d optee_os/out/*/core` to get more info about where this is happening.

**Comment by zatkh** [comment]
Thanks, it was a stupid bug in my PTA entry point!
