### ISSUE TITLE
Endianness of Asymmetric Signature

### ISSUE THREAD

**Issue by Sourabhharman** [OP-TEE/optee_os#2442]
Hi,
Can anyone tell, is the signature returned by TEE_AsymmetricSignDigest() is little or big endian?

Thanks in Advance.

**Comment by jforissier** [comment]
Hi @Sourabhharman ,

The binary format of the output of `TEE_AsymmetricSignDigest()` depends on the algorithm. For PCKS#1 it should be an integer in big endian format, as far as I can tell.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
