### ISSUE TITLE
Nitrogen IMX6 quad booting

### ISSUE THREAD

**Issue by saidganim** [OP-TEE/optee_os#2443]
I am experiencing problem with jumping into normal world. When I boot Optee kernel sometimes it hangs on "Primary CPU switching to normal world boot" message, so it execute "smc #0" , and then nothing happens. I locate linux kernel at 0x12000000. In most cases linux is being booted. But I don't know why sometimes it doesn't boot. I am booting lInux kernel with earlyprintk option, I don't see anything from linux kernel being printed. Running the same linux kernel without optee works well.

I am using IMX6 quad Nitrogen6X board.

**Comment by MrVan** [comment]
@saidganim sometimes, do you mean with optee enabled, sometimes kernel could boot up, sometimes kernel fail to boot?

**Comment by saidganim** [comment]
@MrVan  I mean literally sometimes. It's random thing(once it boots, after rebooting with the same bootscript it doesn't, after several rebooting also boots well). It happens with kernel without optee driver.  If I try to boot kernel with optee driver it doesn't boot linux at all.

**Comment by saidganim** [comment]
I was using wrong config file for linux kernel. Thank you for help.
