### ISSUE TITLE
How to export HW-key based AES operation to User TA?

### ISSUE THREAD

**Issue by angelina-zhao** [OP-TEE/optee_os#2445]
Hello,

In my platform, there are HUK and SSK programmed in a hardware cipher, and the HUK/SSK are not accessible by the CPU.  I have provided a secure driver to expose this feature to all secure OS callers running in SEL1 on ARMv8.  However, there is a requirement that an user TA needs to use this feature to derive their keys from HUK/SSK.  User TA is running in SEL0, and must use SVC calls to trap into SEL1.

This brings one issue:
GP-TEE Internal API definition does not have an interface that can adapt to this use case.  Besides algorithm, key array and key size, there is not extra parameter to pass SSK or HUK information.  And these parameters are strictly checked in the OPTEE-OS crypto (ltc-provider.c) framework, before this call reaches my low level implementation which talks to the HW cipher.

I have two ideas but both seems to have shortcomings.

1.  To export this feature as a PTA.  In this way, User TA can use GP-TEE TA communication interface to communicate with the PTA.  But a PTA can also be accessed by REE client as long as the UUID is known, while I do not expect a REE client to use the SSK/HUK capability.

2. To implement a new SVC call for HUK/SSK AES cipher.  As AES has many modes (CBC, ECB, CTR and GCM, CCM ), I hope to take advantage of the existing OPTEE-OS framework to handle these difference, as after all the only difference is between "user provided key" and "hardware key HUK/SSK", and all other logics are same.

Do you have any better ideas on how to supporting hardware AES keys in OPTEE-OS?

1. The User TA can access this feature.
2. The REE client cannot access this feature.

Notice the HUK/SSK is not readable by the CPU, so User TA cannot read out the key and follow the standard GP-TEE internal APIs.

Thank you very much.

**Comment by jforissier** [comment]
Hello @angelina-zhao,

Your first idea sounds good I think. The shortcoming you mentioned (that the pTA could be accessed by a REE client) can be addressed by rejecting calls not coming from a TA. It is easy to do, see here for instance: https://github.com/OP-TEE/optee_os/blob/3.2.0/core/arch/arm/pta/system.c#L50-L54.

**Comment by jenswi-linaro** [comment]
The system PTA is actually a good place to put this feature.

**Comment by angelina-zhao** [comment]
Thank you very much @jforissier @jenswi-linaro 

I will follow the PTA approach to implement this.
