### ISSUE TITLE
Unhandled pageable abort (translation fault at map_cmd) on Juno r0

### ISSUE THREAD

**Issue by Emantor** [OP-TEE/optee_os#2446]
Hello,

with latest master I get the following abort on Juno:
[Logfile](https://paste.stratum0.org/?c95ce81d071161f9#cY72vpu/6wNyRDoFbSf+l9fjcGtYUqc6dDYsqE0fx3s=)
v4.17 kernel with the juno optee nodes, optee at  8a076f79.
Regression happens on the first `tee_entry_std` which tries to use dynamic shared memory while running optee_test.

I assume #2376 introduced this regression, have not looked deeper into it yet.

**Comment by Emantor** [comment]
Sure,

full log [here](https://paste.stratum0.org/?166547588dbdc823#bo/AADtMeK0p0nF8+Bhe5JixZtSwkDxbVYnSN423u9g=)

**Comment by lorc** [comment]
Hm, it looks quite strange. I created small patch that can help me debug this issue.

```
diff --git a/core/arch/arm/mm/core_mmu.c b/core/arch/arm/mm/core_mmu.c
index 1eeedcd..8412ca4 100644
--- a/core/arch/arm/mm/core_mmu.c
+++ b/core/arch/arm/mm/core_mmu.c
@@ -31,7 +31,7 @@
 #include "core_mmu_private.h"
 
 #ifndef DEBUG_XLAT_TABLE
-#define DEBUG_XLAT_TABLE 0
+#define DEBUG_XLAT_TABLE 1
 #endif
 
 #define SHM_VASPACE_SIZE       (1024 * 1024 * 32)
@@ -98,6 +98,7 @@ register_phys_mem_ul(MEM_AREA_TEE_ASAN, ASAN_MAP_PA, ASAN_MAP_SZ);
 register_phys_mem(MEM_AREA_TA_RAM, TA_RAM_START, TA_RAM_SIZE);
 register_phys_mem(MEM_AREA_NSEC_SHM, TEE_SHMEM_START, TEE_SHMEM_SIZE);
 
+static void dump_xlat_table(vaddr_t va, int level);
 static unsigned int mmu_spinlock;
 
 static uint32_t mmu_lock(void)
@@ -123,6 +124,7 @@ static bool _pbuf_intersects(struct memaccess_area *a, size_t alen,
 #define pbuf_intersects(a, pa, size) \
        _pbuf_intersects((a), ARRAY_SIZE(a), (pa), (size))
 
+
 static bool _pbuf_is_inside(struct memaccess_area *a, size_t alen,
                            paddr_t pa, size_t size)
 {
@@ -1419,6 +1421,7 @@ void core_mmu_map_region(struct tee_mmap_region *mm)
                        break;
                }
        }
+       dump_xlat_table(0x0, 1);
 }
 
 TEE_Result core_mmu_map_pages(vaddr_t vstart, paddr_t *pages, size_t num_pages,
```

Would you please share logs produced with this patch?

**Comment by Emantor** [comment]
Hi @lorc,

did you have time to look at the log yet? Do you need more information?

**Comment by lorc** [comment]
Hi @Emantor ,

Did you have time to gather logs? I can provide a patch instead of textual instructions if you wish

**Comment by Emantor** [comment]
Sorry for the late response:

I tried to reproduce the bug with the patch and couldn't reproduce. I took a look at my reflog again and one of my build scripts reset the branch to an earlier version. With the latest OP-TEE everything works.

Sorry for the noise, if i had posted a full log and verified the sha1 hash from the build I would have caught this way earlier.
