### ISSUE TITLE
X.509 parsing in TA

### ISSUE THREAD

**Issue by divneil** [OP-TEE/optee_os#2447]
Hi,

I am looking to parse the ECDSA key - compressed and uncompressed formats in TA. Is there APIs existing already for that? Basically, to do sign verification, I need X and Y in separate bignum buffers as TEE_InitRefAttribute is not having attribute to pass the key buffer as is.

**Comment by etienne-lms** [comment]
Hi @divneil, I am facing the same situation for pkcs11 development as an OP-TEE service where EC params and point can be DER formatted data.
The TEE Core Internal API (`TEE_xxx` functions) does not provide DER support. But the recently merged **libmbedtls** available to user TA could be of help. I have not done the port yet. I will share once I have something. Feel free to share knowledge if you find your way with.
Maybe one knows another even nicer DER converter that could be provided as a TA library...

**Comment by etienne-lms** [comment]
Reading back your title, it is worth mentioning that **libmbedtls** also provides x509 certificate support. Have a look.

**Comment by divneil** [comment]
Hi @etienne-lms. Thanks for sharing that mbedTLS is now available to UTA. It will take me some time to test the ECDSA - just beginning to setup the systems - but I am pretty sure its going to work. :)

So, is it safe to say mbedTLS will remain a software alternative for `TEE_xxx` APIs. (`TEE_xxx` as I understand could be implemented with hardware acceleration) or is there a plan to define an EL1 interface for mbedTLS too for hardware acceleration.

An off topic question, since, Global Platform TLS spec is not implemented, and with mbedTLS coming IN, is TLS supported? (I am unable see, how socket() call is mapped to TEE_iSocket interface for doing an RPC).

**Comment by etienne-lms** [comment]
> So, is it safe to say mbedTLS will remain a software alternative

Yes, as far as your own TA does not corrupt it self, the mbedtls looks a reliable sw crypto library for user TAs.

> is there a plan to define an EL1 interface for mbedTLS

You can have a look at https://github.com/OP-TEE/optee_os/pull/2345, tough work on getting mbedtls as an alternate crypto lib in OP-TEE core.


> and with mbedTLS coming IN, is TLS supported

No, mbedtls is the crypto library from Arm mbed suite. The TLS/SSL part of it is not integrated. OP-TEE does not include a secure nectwork stack, only the GPD APIs for standardizing client/service interfacing.

**Comment by divneil** [comment]
> Yes, as far as your own TA does not corrupt it self, the mbedtls looks a reliable sw crypto library for user TAs.

:). Actually, I was **not** wondering about the safe status of mbedTLS code. I was looking for info whether mbedTLS APIs will remain accessible for EL0 code, as I read somewhere the plan to replace libtomcrypt (EL1). So, from the comments so far, I am sure mbedTLS APIs will remain accessible.

> OP-TEE does not include a secure nectwork stack, only the GPD APIs for standardizing client/service interfacing.

I have a GPD spec for TLS, which defines the interface `TEE_tlsSocket`, so, I know that is not implemented. I thought with mbedTLS coming IN, some alternative is there.

Thanks for sharing all the info.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
