### ISSUE TITLE
Getting RSA Public Key

### ISSUE THREAD

**Issue by tesmnorth** [OP-TEE/optee_os#2450]
Hello,

Is it enough to getting TEE_ATTR_RSA_PUBLIC_EXPONENT and TEE_ATTR_RSA_MODULUS attributes for generating PUBLIC KEY in side of host app (C executable file or Android Application)?

Thanks

**Comment by jforissier** [comment]
Hi @tesmnorth,

The answer is yes.

**Comment by tesmnorth** [comment]
@jforissier  Thanks
