### ISSUE TITLE
core_mmu_add_mapping() and memcpy() in optee os

### ISSUE THREAD

**Issue by yilingxu** [OP-TEE/optee_os#2453]
I am doing secure boot on imx6q, so I need to check the Integrity of linux kernel. Since the size of linux kernel is large, so I want to split the kernel, and do hash256 several times. But it get wrong when do memcpy(), my code is as follow:

    #define SHA256_HASH_SIZE 32 
    #define KERNEL_SIZE 0x662680 
    #define BUF_MAX_SIZE 0xfa000 

	void kernel_hash(unsigned long phys_nsec_entry){

	TEE_Result ret, buf_size, left_bytes = KERNEL_SIZE;
	uint8_t kernel_hash[SHA256_HASH_SIZE];
	void *kernel_buf;

	ret = core_mmu_add_mapping(MEM_AREA_IO_NSEC, phys_nsec_entry, KERNEL_SIZE);
	kernel_buf = phys_to_virt(phys_nsec_entry, MEM_AREA_IO_NSEC); 

    buf_size = BUF_MAX_SIZE < left_bytes ? BUF_MAX_SIZE : left_bytes;
	memmove(kernel_buf, kernel_buf, buf_size);    //copy kernel(size of buf_size) to kernel_buf, and it works well
	ret = tee_hash_createdigest(TEE_ALG_SHA256, kernel_buf, buf_size, kernel_hash, sizeof(kernel_hash));     //do sha256

	kernel_buf = ((uint8_t *)kernel_buf) + buf_size;
	left_bytes -= buf_size;

	//if KERNEL_SIZE > BUF_MAX_SIZE, do sha256 severial times, and hash value V = hash(I||V)
	while(left_bytes > 0){
		uint8_t buf[buf_size+SHA256_HASH_SIZE];

		memcpy(buf, kernel_buf, buf_size);
		memcpy(buf+buf_size, kernel_hash, SHA256_HASH_SIZE);    // padding hash value to buf, it seems get wrong

		ret = tee_hash_createdigest(TEE_ALG_SHA256, buf, sizeof(buf), kernel_hash, sizeof(kernel_hash));

		kernel_buf = ((uint8_t *)kernel_buf) + buf_size; 
		left_bytes -= buf_size;
		buf_size = BUF_MAX_SIZE < left_bytes ? BUF_MAX_SIZE : left_bytes;
	  }
    }

The wrong message as: Core data-abort at address 0x4df745e0 (translation falut).

I have trapped here several days, can anyone help me? Thanks a lot.

Yiling Xu

**Comment by yilingxu** [comment]
@MrVan Hi, This is a good idea. In fact, I have achieved using uboot to authenticate optee, and as your suggestion, I can also use uboot to authenticate linux. 

But I still want to find out what's wrong with memcpy(), is memory space for optee limited?

**Comment by yilingxu** [comment]
@jenswi-linaro, I tried to small BUF_MAX_SIZE as 0x10000, and it doesn't work either.

**Comment by jenswi-linaro** [comment]
The stack is only 0x2000

**Comment by yilingxu** [comment]
@jenswi-linaro OK, Thanks a lot.

**Comment by yilingxu** [comment]
@jenswi-linaro Thanks a lot. And what is the size of heap, and where can I find these values?

**Comment by jenswi-linaro** [comment]
Default values for the heap are set at:
https://github.com/OP-TEE/optee_os/blob/0111b5f01677536ddec287e2e8f07f9287049a2d/mk/config.mk#L248-L249

Stack sizes are set at
https://github.com/OP-TEE/optee_os/blob/0111b5f01677536ddec287e2e8f07f9287049a2d/core/arch/arm/kernel/thread.c#L43-L68

**Comment by yilingxu** [comment]
@jenswi-linaro Thanks for your patience.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
