### ISSUE TITLE
Access to hardware in OP-TEE

### ISSUE THREAD

**Issue by elkoniu** [OP-TEE/optee_os#2456]
Hi, I am using OP-TEE on HiKey960 platform. I would like to connect to MIPI SCI camera from TEE. Correct me if I am wrong but it looks like I need to prepare "TEE driver" from scratch to do it? If there is any hardware abstraction layer in OP-TEE? I only saw some abstraction for serial communication for various boards.

Or the better solution is to access hardware from REE and then only pass critical data to TEE to manage it?

**Comment by lorc** [comment]
Hi @elkoniu ,

You are right. There is almost no HW abstractions and no drivers framework.

Solution depends on which level of security you want to achieve. Of course, it is  more secure to declare MIPI interface registers as secure memory and put driver into OP-TEE. But if you okay with idea that OP-TEE can possibly get not a real frame from a camera, then you can leave driver in REE.

**Comment by elkoniu** [comment]
Hi @lorc ,

Thank you for fast response. So the easiest solution will be "talk to the hardware" in REE, then pass data to TEE, do some secure "magic" on it and return result to REE.

But in case I would like to make driver in TEE it need to be "bare metal" one - based on direct access to SoC registers. Similar to existing OP-TEE serial drivers?

**Comment by jenswi-linaro** [comment]
Yes, it would be "bare metal".

**Comment by elkoniu** [comment]
Ok, last question then.
Looks like for development I will need full SoC documentation with registers and memory description. OP-TEE has list of reference devices like Raspberry or HiKey. If this mean that full documentation for those devices is available?

**Comment by jenswi-linaro** [comment]
Unfortunately no, the public documentation is limited.

**Comment by elkoniu** [comment]
If there is any OP-TEE supported device with full documentation then?

**Comment by elkoniu** [comment]
I found information that best choice now is HiKey620. Can someone confirm that or suggest another device?

**Comment by vchong** [comment]
@elkoniu HiKey620 doesn't have full documentation either. E.g. if you want to protect memory from REE access, the register info for those aren't available. The MIPI stuffs I'm not familiar with but looks like it might be available. See https://github.com/96boards/documentation/blob/master/consumer/hikey/hikey620/hardware-docs/Hi6220V100_Multi-Mode_Application_Processor_Function_Description.pdf section 3.4, which then points to http://www.synopsys.com/dw/ipdir.php?ds=mipi_dsi.

Also, not sure how easy it is to get a HiKey620 these days.
