### ISSUE TITLE
2 Questions about syscall_open_ta_session() @ tee_svc.c

### ISSUE THREAD

**Issue by kaih1** [OP-TEE/optee_os#2458]
1. This function is called to open a session on TA designated by "const TEE_UUID *dest".  Why it calls tee_ta_get_current_session(&sess) at the beginning? What is this sess?

2. The comment at the top of this function says "Called when a TA calls an OpenSession on another TA". How about a client app that needs to open a session? I tried to trace how a CA calls an open session and I find the following path:
user_ta_enter_open_session()
->user_ta_enter()
->thread_enter_user_mode()
->__thread_enter_user_mode()
->__utee_entry(UTEE_ENTRY_FUNC_OPEN_SESSION,...)
->entry_open_session()
->ta_header_add_session()
->TA_CreateEntryPoint()
->TEE_OpenTASession()
->utee_open_ta_session()
->syscall_open_ta_session()

Is this correct? If not, then how is CA opening a session? I only find one place that calls calloc(1,sizeof(struct tee_ta_session)), which is in tee_ta_init_session(), which called by tee_ta_open_session()<-syscall_open_ta_session()

**Comment by leesagacious** [comment]
hi  kaih : 

     [https://blog.csdn.net/leesagacious/article/details/80548735](url)

**Comment by xxxken** [comment]
sorry but this uninformative blog barely answers the question @leesagacious

**Comment by jenswi-linaro** [comment]
`sess` is a pointer the the current session, it contains information like the identity of the caller that created the session in the first place and also a pointer the context of the TA belonging to the session + some extra bookkeeping.

For normal world clients the corresponding function is `entry_open_session()`.  Note that `tee_ta_open_session()` also is called here.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
