### ISSUE TITLE
xtest Illegal Instruction

### ISSUE THREAD

**Issue by PedroRibeiro95** [OP-TEE/optee_os#2460]
Hello,

I'm running OP-TEE + Linux on i.MX6 Nitrogen6X. To do so, I had to disable CAAM on the Linux Kernel. I am able to boot, but if I try to run xtest I get an "Illegal Instruction" error. 
I also tried running a program I developed, and it is able to enter the TA and leave it, crashing then with the same error. However, during the time between it enters and leaves the TA it doesn't seem to do anything.

I would appreciate some guidance, thanks.

**Comment by leesagacious** [comment]
why disable CAAM on the linux kernel ?

**Comment by PedroRibeiro95** [comment]
Hello @leesagacious,

Because otherwise I could not boot. It was suggested by @MrVan in https://github.com/OP-TEE/optee_os/issues/2002

**Comment by MrVan** [comment]
@PedroRibeiro95 Only xtest trigger illegel instruction or other programs also has similar issue? Are you using 6Q or 6DL?

**Comment by saidganim** [comment]
@MrVan  6Q only xtest. I debugged the binary. SIGILL is raised by "udiv .." instruction.

**Comment by MrVan** [comment]
@saidganim  I did not try xtest on 6Q recently. udiv, this seems some instruction generated by toolchain could not be executed by i.MX6Q. Did you try softfloat?

**Comment by sdininno** [comment]
@PedroRibeiro95 ,
your problem is likely du to the addition of the openssl library libcrypto.a.
the illegal instruction is in _armv7_tick() that is supposed to check the availability of generic timer (imx6 is based on Cortex A9 so it does not have those).

to double check, you could simply remove the compilation of Mbedtls.
you can also use gdb on your target to see where the exception is happening.

if it is the case, then you should probably provide your own  libcrypto.a using OPTEE_OPENSSL_EXPORT flag.

**Comment by PedroRibeiro95** [comment]
@sdininno If I understood correctly, libcrypto is being compiled for armv7 and I need to recompile it for armv6, right?

**Comment by MrVan** [comment]
@jenswi-linaro @jforissier 
In libcrypto.a, 
```
315205 00000088 <_armv7_tick>:
315206   88:   ec510f1e        mrrc    15, 1, r0, r1, cr14
315207   8c:   e12fff1e        bx      lr
```
The mrrc inst is accessing CNTVCT, Virtual Count register. However this only exist on platforms has Generic Timers Extension. On i.MX6 with A9 core, we do not support generic timer extensions. So there is issues.

How do you suggest fix this issue?

**Comment by jforissier** [comment]
@MrVan

This libcrypto.a file in the crest source has always been a hack, that being said, perhaps we could find an implementation that does not rely on the virtual timer.

**Comment by saidganim** [comment]
@MrVan We recompiled openssl-1.0.2o with cross-compiler. It solved the problem. THank you all for help. @sdininno THank you, your comment was very helpful.

**Comment by jforissier** [comment]
FYI, should be fixed by https://github.com/OP-TEE/optee_test/pull/302 (the new library does not contain `_armv7_tick` with the CNTVCT access anymore).

**Comment by glneo** [comment]
@jforissier,
Just a minor clarification, _armv7_tick still does have the CNTVCT access, but this is okay as OpenSSL  sets up to handle SIGILL, this is how OpenSSL run-time detects features like these. The thing is, when people go to debug this they trap on this instruction, but it would have been caught and handled correctly had gdb not been attached. You have to continue to find the real culprit, which is the un-handled udiv in lh_insert().

I just wanted to point that out as it slowed me down in finding the real issue and it seems to be a common mistake (Google "_armv7_tick" and see how many people get stuck thinking that is their problem when debugging OpenSSL).

**Comment by jforissier** [comment]
@glneo when I disassembled the new library I could not find a `_armv7_tick` symbol, nor an `mrrc` instruction. Did I miss something?

**Comment by glneo** [comment]
@jforissier,

That function may be getting inlined, but the check is here and wrapped in a check for SIGILL:
https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/armcap.c#L157

My point is that the illegal instruction in _armv7_tick was not the problem with libcrypto.a. It is a minor point though as the new libcrypto.a solves the real problem, so this is a non-issue.

**Comment by saidganim** [comment]
@glneo  Thank you for your comment. It made the problem clear for me.

**Comment by jforissier** [comment]
@glneo got it: the check is _not_ there, because I have built the library for target `linux-generic32`. That is why there is no Arm-specific code.

**Comment by jforissier** [comment]
Closing because I think the issue has been addressed.
