### ISSUE TITLE
Does OP-TEE allows to load TA compiled by third party person having same key(default_ta.pem)?) 

### ISSUE THREAD

**Issue by rdhobi** [OP-TEE/optee_os#2462]
I have doubt that does OP-TEE allows to load TA compiled by third party person having same key(default_ta.pem) available in optee_os/keys? Is there any other security check apart from signature?

I have concern that If anyone gets default_ta.pem then he can compile and load TA and do malfunctioning.
Let me correct if i'm thinking in wrong direction.

**Comment by jenswi-linaro** [comment]
The only security check is the signature, everything else is just sanity checks. So the private key used to sign TAs has to be well protected. The one supplied in the OP-TEE tree is just a test key.

**Comment by rdhobi** [comment]
@jenswi-linaro : Thanks for reply.
