### ISSUE TITLE
mdelay() 

### ISSUE THREAD

**Issue by leesagacious** [OP-TEE/optee_os#2464]
hi : 
 If I want to delay , How to do ? 
 like  mdelay()  udelay()  in linux kernel

**Comment by jforissier** [comment]
Hi,

https://github.com/OP-TEE/optee_os/blob/3.2.0/core/arch/arm/include/kernel/delay.h#L32-L33

**Comment by sdininno** [comment]
@leesagacious @leesagacious , 
please note that this API will not work on CortexA9 based SoC (i.e i.MX6 and stm)
