### ISSUE TITLE
TEE_CreatePersistentObject for TEE_TYPE_DATA with attributes

### ISSUE THREAD

**Issue by vtcao297** [OP-TEE/optee_os#2468]
Hi,

Is it possible when creating a persistent object of TEE_TYPE_DATA storage type to have custom (user-defined) attributes?  the GP isn't very clear on whether this is allowed.  I want to store some metadata information to be used as blob versioning mechanism.

**Comment by etienne-lms** [comment]
Hell @vtcao297. At least OP-TEE does offer means to add custom attributes. You need to store them inside your data (or in a companion object) and handle them from your TA.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
