### ISSUE TITLE
Not getting debug prints after enabling TEE and TA logging.

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_os#2471]
I have changed mk/config.mk to enable the debug prints.
**CFG_TEE_CORE_LOG_LEVEL ?= 4
CFG_TEE_TA_LOG_LEVEL ?= 4**

I want to print the **curr_thread** in thread_alloc_and_run().
and I have put a debug print for that
EMSG("l->curr_thread= %d\n", l->curr_thread);

and ran the xtest 1005, got the following output but not the **curr_thread** debug print.
> root@localhost:~# xtest 1005
> Test ID: 1005
> Run test suite with level=0
> 
> TEE test application started with device [(null)]
> regression
> 
> regression_1005 Many sessions
> regression_1005 OK
> +-----------------------------------------------------
> Result of testsuite regression filtered by "1005":
> regression_1005 OK
> +-----------------------------------------------------
> 3 subtests of which 0 failed
> 1 test case of which 0 failed
> 73 test cases was skipped
> TEE test application done!
> root@localhost:~#

Any pointer what I am missing in this ?

**Comment by jforissier** [comment]
So you see any debug message from OP-TEE? If not, check your secure console configuration (UART).

**Comment by sahilnxp** [comment]
Was doing silly mistake, UART address was not correct.
Thanks @jforissier
