### ISSUE TITLE
CFG_UNWIND

### ISSUE THREAD

**Issue by leesagacious** [OP-TEE/optee_os#2472]
hi : 
the CFG_UNWIND . 
is this configuaration only relevant to the arm architecture ?
what is the meaning of his existence ?

**Comment by jforissier** [comment]
No, most architectures provide a way to unwind the call stack. This is architecture-specific, as you can see if you compare the ARMv7/ARMv8 Aarch32 implementation with the ARMv8 Aarch64 one.
