### ISSUE TITLE
I can not find encryption for secure storage.

### ISSUE THREAD

**Issue by ljmblueday** [OP-TEE/optee_os#248]
I think that encryption process is needed for making secure storage more secure.
I see the Linaro connect document(lcu14-306) about encryption of secure storage.
But I can not find encryption for secure storage at current git.

**Comment by jamescfkung** [comment]
The feature still in code review stage, please refer to [pull request 231](https://github.com/OP-TEE/optee_os/pull/231)

**Comment by pascal-brand-st** [comment]
#231 has been merged
