### ISSUE TITLE
How to synchronize an ISR with a thread in a PTA?

### ISSUE THREAD

**Issue by MHesham** [OP-TEE/optee_os#2486]
I have a situation where I want to implement a concurrent bounded queue in a PTA in which the PTA can always dequeue and get blocked when the queue is empty. Some device ISR is responsible to enqueue to that  queue whenever some device data arrives and hence unblock the waiting PTA thread if any.

I know how to use mutex and condvar to implement a concurrent bounded queue in OPTEE that is used in thread contexts only (i.e. enqueue and dequeue from thread context ONLY, no ISRs involved).. the part I can't figure out is how to allow an ISR to enqueue and hence signal the PTA thread to wake up and dequeue, since you can't use mutex or condvar in ISRs.

The more general question: How to synchronize an ISR with a thread in a PTA?

**Comment by lorc** [comment]
Actually, OP-TEE has no scheduler, so you can't  wake up anything. OP-TEE is scheduled solely by REE.

What you can do is to signal from ISR to REE in some platform-dependent way, so latter will invoke your PTA.  

Or you can move all your logic into ISR handler, by calling PTA code in irq handler context (if you can ensure that your PTA will not sleep).
