### ISSUE TITLE
Assertion triggered in BL1

### ISSUE THREAD

**Issue by NeatMonster** [OP-TEE/optee_os#2499]
Hello there,

I'm trying to build and use OP-TEE for my Hikey 620. I have followed the instructions located [here](https://github.com/OP-TEE/build/blob/master/README.md). I could build and flash without an issue, but when I try to boot the board, this is what is displayed on the UART:

```
INFO:    BL1: 0xf9810000 - 0xf9815000 [size = 20480]
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v1.4(debug):8608ac5
NOTICE:  BL1: Built : 16:34:46, Aug  3 2018
INFO:    BL1: RAM 0xf9810000 - 0xf9815000
WARNING: BL1: cortex_a53: errata workaround for 835769 was missing!
INFO:    BL1: cortex_a53: errata workaround for disable_non_temporal_hint was applied
INFO:    BL1: cortex_a53: errata workaround for 843419 was applied
INFO:    BL1: cortex_a53: errata workaround for 855873 was applied
INFO:    BL1: Loading BL2
ASSERT: plat/hisilicon/hikey/hikey_io_storage.c:204
```

Thank you in advance for your help.

**Comment by jforissier** [comment]
Hi @NeatMonster ,

It will probably not help much but that's a TF-A error, not an OP-TEE one.

**Comment by vchong** [comment]
Did you flash from recovery mode, using recovery.bin?
