### ISSUE TITLE
Secure Media Playback using OPTEE

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#2500]
I have a question about the secure media playback presentation based on OPTEE at this [link](http://hkg15.pathable.com/static/attachments/112702/1424379017.pdf?1424379017). 

The particular slide I want to ask about is slide 19. In that slide, various stages are shown for video playback and each stage is linked by arrows to a driver (V4L2 decode, V4L2 color-conv and GFX). Each of these is further connected to a different TA. I want to ask whether the different TA's are actually performing the video decoding stages and that the driver merely becomes a way to connect to the TA's. Also will the final processed video buffer be available in TA 5 ?

Thanks

**Comment by jbech-linaro** [comment]
I could be wrong here, but I think that is not what's been done in reality, I believe that they guys working with this have implemented everything in a single TA and that TA is mainly responsible for decrypting the encrypted and encoded video frames to a buffer accessible by the decoder. @petegriffin anything to add?

**Comment by a2t2** [comment]
@jbech-linaro Does the TA do the actual decoding of the video buffer as well ? In that case, the driver would just act as a layer to forward the decoding and decryption request to the TA.

**Comment by jbech-linaro** [comment]
> @jbech-linaro Does the TA do the actual decoding of the video buffer as well ?

I don't think that is the common case. Usually I think that after the TA has decrypted, then it hand over the buffer to a hardware decoder that has been configured (firewall, TZPC etc) in way such that it can access the decrypted but encoded frames (which is not accessible by non-secure side).

**Comment by a2t2** [comment]
@jbech-linaro Slide 19 has other stages as well like color-conv; are those also being done in hardware or are they done by TA are decryption ?

**Comment by jbech-linaro** [comment]
> ... are those also being done in hardware or are they done by TA after decryption ?
I would guess so (i.e., done by hardware). I believe that the TA's main duty is to decrypt encoded video into secure buffers in these types of setups and use cases. But, there is no strict rule about what you can put into a TA. It depends on many things, hardware capabilities, foot print, how "complicated" it is to use regular libraries with Trusted Applications etc.

**Comment by petegriffin** [comment]
Hi,

I wasn't actually aware of that presentation you referenced. I guess that was an early design that was considered, but not what has been implemented. Joakim was correct in reality today for Playready and Widevine there is a single TA which is responsible for doing the decryption. We are considering have a second TA for managing HDCP related things, but currently we've not implemented that.

The detailed setup can vary depending on the hardware of the SoC. But usually we have 3 secure heaps in a secure video playback use case. The DRM TA decrypts into the first secure heap 1 which is write accessible by secure world and read accessible by the video decoder hardware.

The video codec hardware reads from secure heap 1 and writes decompressed video frames to secure heap 2 (which is write accessible by video decode hardware and read accessible by display hardware only). Then display hardware reads from secure heap 2 and writes to secure heap 3 which is the final scan out buffer.

This slide deck https://connect.linaro.org/resources/hkg18/hkg18-113/ and http://connect.linaro.org.s3.amazonaws.com/hkg18/presentations/hkg18-408.pdf are for the two platforms (iMX8M and ARM Juno) which have this implemented based on Linaro components such as OP-TEE and Widevine / Playready TAs.

**Comment by a2t2** [comment]
@petegriffin  I have a few questions based on the two links you gave. 

From the second link:
slide 11 
	- are both the secure and non-secure bit stream part of non-secure 
            memory (green and orange arrows originate from the same point) ?
	- are the same VPU and GPU cores switching between non-secure and protected
          modes, or are there two copies of VPU and GPU ? (Confusion because slide
	  uses the word "protected mode")

 slide 13
	- is NSAID only used for restricting access to non-secure memory regions 
	  (the 8 regions belong in non-secure memory) ?
	- the table has a column "secure access" - does it mean to restrict access
          to non-secure memory region from secure mode of CPU core ?

 Also, from the two presentations, are domain ID and NSAID the same concept ? 

Thank you for your time.

**Comment by petegriffin** [comment]
@KenLSoft If you have time could you answer @a2t2 questions about your TZMP1 presentation?
