### ISSUE TITLE
Using tee_shm_register API from kernel module.

### ISSUE THREAD

**Issue by jjoset** [OP-TEE/optee_os#2501]
I am trying to implement kernel module using tee client API (CA is a kernel module). I am able to 
run  TA using Kernel APIs. Now I am thinking how can I use tee_shm_register() kernel API, because the addr parameter is mentioned as user space address. If any sample program for tee_shm_register() is there, would be good. 

From tee_drv.h 

tee_shm_register() - Register shared memory buffer
* @ctx:             Context that registers the shared memory
* @addr:            Address is userspace of the shared buffer
* @length:          Length of the shared buffer
* @flags:           Flags setting properties for the requested shared memory.

Thanks in advance

**Comment by jenswi-linaro** [comment]
I don't think you can supply a kernel address to `tee_shm_register()` as it's implemented today.  It would make sense to extend the function to be able to handle kernel addresses (patches are welcome!). In the meantime I think you're left with `tee_shm_alloc()` with `TEE_SHM_DMA_BUF` in the flags field for larger buffers of shared memory.

Perhaps @b49020 has some more ideas.

**Comment by b49020** [comment]
Agree with @jenswi-linaro.

@jjoset Following is an example code using `tee_shm_alloc()`:
```
struct tee_shm *shm_pool = NULL;
shm_pool = tee_shm_alloc(ctx, TA_POOL_SIZE, TEE_SHM_MAPPED | TEE_SHM_DMA_BUF);
if (IS_ERR(shm_pool)) {
        pr_err(PFX "tee_shm_alloc failed\n");
        return PTR_ERR(shm_pool);
}
tee_shm_free(shm_pool);
```

**Comment by b49020** [comment]
@jjoset AFAIK, `tee_shm_register()` provides underline kernel implementation for user-space TEE Client API: `TEEC_RegisterSharedMemory()`. For more details regarding this API, refer to [GlobalPlatform TEE Client API Specification v1.0](http://www.globalplatform.org/specificationsdevice.asp).

**Comment by jjoset** [comment]
OK. Now its clear. Thank you so much @b49020 . I will close the ticket now.
