### ISSUE TITLE
Porting tee supplicant into Kernel space

### ISSUE THREAD

**Issue by soso7885** [OP-TEE/optee_os#2502]
For some reasons, we're planning to port tee supplicant into Kernel space, we haven't experience like that if someone could give us some advice? please.

1. Is it possible?
2. Is any risk, trade-off or side effect of doing that?
3. Is any secure issue for that?
4. Is anyone can share the experience of that?

We welcome for any suggesting, thanks!

**Comment by jbech-linaro** [comment]
> Is it possible?

Probably yes.

> Is any risk, trade-off or side effect of doing that?

You loose the ability to work secure storage etc ([this](https://www.linuxjournal.com/article/8110) is a very old article, but I think that is still valid).

> Is any secure issue for that?

Not really, the trust model from TEE point of view is that we **do not** trust anything in normal world. I.e., we do not trust user space and we do not trust Linux kernel. So, you don't gain much but trying to do it in kernel.

> Is anyone can share the experience of that?

Do you need supplicant? Or are you asking about the need to be able to communicate with the TEE directly from the kernel? @jenswi-linaro posted a patch to the kernel mailinglist not that long ago which gives you functionality to talk to the TEE from kernel directly (other than just the TEE drivers/framework).

**Comment by HeJyunYan** [comment]
@soso7885 
You want tee-supplicant into kernel space, because some kernel drivers need to ask TA do something when STR?

**Comment by soso7885** [comment]
@HeJyunYan 
@soso7084
Yes, something like that.
In STR, Our driver in Linux Kernel needs to call TA, but in this moment, there is no TA in secure world, so we need to load again.
The difficult is the tee-supplicant in user space is frozen, so we figure out that try to port tee-supplicant into kernel space.

**Comment by jenswi-linaro** [comment]
What is STR?

**Comment by soso7885** [comment]
@jenswi-linaro 
Store to RAM, the user space application will be frozen before kthread in suspending and 
thawing after kthread in resuming.

**Comment by jenswi-linaro** [comment]
So the problem is that you may need to load a TA while user space is frozen?
Do you need to update secure storage too?

**Comment by soso7885** [comment]
@jenswi-linaro 
Yes, you got it, any suggestion? please

**Comment by jenswi-linaro** [comment]
Yes on both questions? Because if it's only to load a TA you can do that in advance and lock the TA in memory with just a flag. If it's updating secure storage (for rollback protection of something I assume) then it's more tricky.

**Comment by soso7885** [comment]
@jenswi-linaro 
Thanks for reply.
Unfortunately, it is a limitation on our platform.
One of the CA will clean all the memory while suspending.

**Comment by jenswi-linaro** [comment]
Other platforms may have a similar limitation so it could be of common interest to find a good solution to this problem. Right now I feel that I have only a small fraction of the information needed to come up with anything useful, but I'm pretty sure that moving tee-supplicant into the kernel will be something to regret in the long run.

Over the years we've made changes in tee-supplicant to handle new features in OP-TEE (needing synchronized updates of both secure world and linux user space). There has been changes to the kernel driver too, but those as far as I know have only been optional.

**Comment by soso7885** [comment]
@jenswi-linaro 
@jbech-linaro 
Thanks for reply !
