### ISSUE TITLE
Error while building OPTEE with BR2_PACKAGE_GSTREAMER

### ISSUE THREAD

**Issue by ArunSahu42** [OP-TEE/optee_os#2505]
I am trying to build OPTEE  with gstreamer library 
using the following command 
make BR2_PACKAGE_GSTREAMER=y -j2 and getting below error.
Please  help me for solving this issue.Thank you in advance

checking for FAMOpen in -lfam... no
configure: WARNING: *** FAM support will not be built (FAM library not found) ***
checking for getxattr in -lc... yes
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking for XATTR_NOFOLLOW... no
checking for LIBMOUNT... no
configure: error: *** Could not find libmount
package/pkg-generic.mk:211: recipe for target '/home/sahuuaru/Q8TEE/out-br/build/libglib2-2.56.1/.stamp_configured' failed
make[2]: *** [/home/sahuuaru/Q8TEE/out-br/build/libglib2-2.56.1/.stamp_configured] Error 1
Makefile:16: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/sahuuaru/Q8TEE/out-br'
common.mk:198: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2

**Comment by jforissier** [comment]
buildroot error, unrelated to OP-TEE?

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.

**Comment by ArunSahu42** [comment]
@jforissier  thank you and sorry for late reply.
It also worked for me.
