### ISSUE TITLE
Does optee_os supports RSA sign/verify using ARMv8 accelerated crypto accelerated instructions?

### ISSUE THREAD

**Issue by sourabhdasharman** [OP-TEE/optee_os#2507]
Hi,
I have checked the libtomcrypt crypto library implemented in optee_os. 
I found a couple of algorithm like SHA, AES, etc could be configured to be using ARMv8 accelerated instructions instead of software implementation by using CFG_CRYPTO_WITH_CE.

Is RSA algorithm implemented in libtomcrypt also supports ARMv8 accelerated instruction? If no, then is there any plan for supporting it in future optee release?
Thanks & Regards,
Sourabh

**Comment by jforissier** [comment]
Hi @sourabhdasharman ,

> I found a couple of algorithm like SHA, AES, etc could be configured to be using ARMv8 accelerated instructions instead of software implementation by using CFG_CRYPTO_WITH_CE.

Correct.

> Is RSA algorithm implemented in libtomcrypt also supports ARMv8 accelerated instruction?

No. To my knowledge, there is no ARMv8 instruction to help accelerate RSA (such as modular exponentiation).

**Comment by sourabhdasharman** [comment]
Hi @jforissier Thanks for the information.
