### ISSUE TITLE
Kernel Panic on "poweroff" iMX6UL with OP-TEE implimentation

### ISSUE THREAD

**Issue by vsivanagulu** [OP-TEE/optee_os#2510]
Hi all
I am getting "kernel panic" when poweroff command is executed.
We have successfully ported OP-TEE(3.2.0) with 4.8 kernel into our custom iMX6UL board and the xtest results look good too..
`+-----------------------------------------
16081 subtests of which 0 failed
74 test cases of which 0 failed
0 test case was skipped
TEE test application done! `
Even the "reboot" command fails with error msg: "Reboot failed -- System halted"
The kernel successfully shutdown and poweroff  when optee_os(tee.bin) is not loaded. Is there any optee api to call before shutdown which could have created this issue?

**Comment by vsivanagulu** [comment]
thanks @jenswi-linaro 
There seems to have no support for "arm,psci" in iMX6UL, However I raised a ticket in NXP support to enquire psci support. I'll update the status here once I get the response from NXP support.

**Comment by MrVan** [comment]
@vsivanagulu psci on i.MX6UL is support by NXP vendor optee, https://source.codeaurora.org/external/imx/imx-optee-os/

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
