### ISSUE TITLE
Redis as a TA

### ISSUE THREAD

**Issue by wozuo** [OP-TEE/optee_os#2514]
Hi everyone,

Is it possible to run an in-memory data store like for example Redis as a TA in OP-TEE OS?

Thanks

**Comment by wozuo** [comment]
Hey thanks for your quick reply. Redis uses a few libraries (https://github.com/antirez/redis/tree/unstable/deps) which are included in the project, and libc. Does the OP-TEE OS provide libc?

**Comment by jbech-linaro** [comment]
> Does the OP-TEE OS provide libc?

We have a [small subset of libc](https://github.com/OP-TEE/optee_os/tree/master/lib/libutils), we have imported things there when needed.

**Comment by wozuo** [comment]
Ok thank you for your time!
