### ISSUE TITLE
Can I play media contents in optee using qemu?

### ISSUE THREAD

**Issue by JohnyDev42** [OP-TEE/optee_os#2517]
I added mplayer package from the buildroot . I tried to play a video content using mplayer in normal world but it failed. Do I have to add any other thing to play a video in optee.

**Comment by jbech-linaro** [comment]
@ArunSahu42 , you should be aware that the default OP-TEE builds are development setups for OP-TEE pure development. Meaning that we are interested in that 
a) all OP-TEE component are playing nicely together and that are our test suite(s) are passing on a plain Linux system.
b) we easily can add other development tools to the root fs, like gdb, gcc, valgrind, strace etc to mention a few. 

For other things, we're of course happy if they are working or if other people makes them work. But we don't have bandwidth to maintain and ensure that everything else not related to OP-TEE is working in our setups. In those cases it is probably better trying to use a proper root files system from a known working Linux distro and then thereafter deploy the OP-TEE binaries. We used to have a "HiKey Debian" setup, but that had become a bit dated and once again we didn't have time to continue support it and therefore we that setup a couple of months ago.

Many of the users/companies of OP-TEE, they have done just what I mentioned, i.e., integrated OP-TEE on full Linux systems, Android builds, Yocto root fs etc.

So, I doubt you will get the video stuff to work with our development Buildroot root fs without having to enable lots of other packages, re-compile kernel with flags enabling various graphic related things etc.

**Comment by ArunSahu42** [comment]
Sorry for Asking such silly questions.As a begginner I dont know how I will proceed.From a couple of days I am exploring optee_os. Thanks for reply.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
