### ISSUE TITLE
Use of SDP in Secure DRM 

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#2518]
I found [slides](http://connect.linaro.org.s3.amazonaws.com/hkg18/presentations/hkg18-408.pdf) for secure DRM with OPTEE from different question asked.

In slide 20, it is mentioned that the SDP is used to copy a decrypted buffer from a crypto TA to a portion of NS memory not accessible to the AP. I am trying to find documentation on how SDP works and want to ask what role does SDP play in allowing TA to copy the decrypted buffer that non-secure OS cannot see it?

Thanks

**Comment by etienne-lms** [comment]
For the record, here are some references that may help to cache the picture.
* BUD17-400: Secure Data Path with OPTEE _(how ION is used for secure buffers)_
https://connect.linaro.org/resources/bud17/bud17-400/
* SAN19-107: Secure Data Path on Linux and NXP i.MX 8M _(a platform implementation of SDP)_
https://connect.linaro.org/resources/san19/san19-107/
* SAN19-507: HDCP and OP-TEE  _(as HDCP is can be part of the picture)_
https://connect.linaro.org/resources/san19/san19-507/
* YVR18-215: Update on OpenCDM _(SDP support in distributions)_
https://connect.linaro.org/resources/yvr18/sessions/yvr18-215/

And the one you referenced above:
* HKG18-408: A DRM solution using TZMP
https://connect.linaro.org/resources/hkg18/hkg18-408/
