### ISSUE TITLE
make toolchains fail;

### ISSUE THREAD

**Issue by ryankumar** [OP-TEE/optee_os#2521]

**Comment by ryankumar** [comment]
i am facing a problem on "make toolcahins " from last 1 week. The error is 

Downloading gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu ...
tar: /home/mahannee/Qemuv-7/build/../toolchains/gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
toolchain.mk:39: recipe for target 'aarch64' failed
make: *** [aarch64] Error 2

As i am a begginer ;i m unable to resolve this one.

**Comment by jforissier** [comment]
Download issue?
Try `make -n toolchains` and copy/paste the `curl` command without the `-s` (silent) argument. Like so:
```
curl -L https://releases.linaro.org/components/toolchain/binaries/6.2-2016.11/arm-linux-gnueabihf/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz -o /home/mahannee/Qemuv-7/build/../toolchains/gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu.tar.xz
```

**Comment by ryankumar** [comment]
when i am running above curl
curl -L
https://releases.linaro.org/archive/omponents/toolchain/binaries/6.2-2016.11/arm-linux-gnueabihf/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz
-o
/home/mahannee/Qemuv-7/build/../toolchains/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz

i am getting below error

 % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:--
--:--:--     0
curl: (51) SSL: certificate subject name (publishing-ap.linaro.org) does
not match target host name 'releases.linaro.org'

**Comment by jbech-linaro** [comment]
> when i am running above curl
> curl -L
> https://releases.linaro.org/archive/omponents/toolchain/binaries/6.2-2016.11/arm-linux-gnueabihf/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz
> -o

That's not surprising, you have `omponents` in the URL and you are referring to some archive. I.e., your URL is totally wrong. I tip is that if it doesn't work using commandline, just paste it in your webbrowser and you will see that you get a `404` or similar.

This works, I guarantee.
```bash
$ wget https://releases.linaro.org/components/toolchain/binaries/6.2-2016.11/arm-linux-gnueabihf/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz
```

But, what are you actually trying to do here.
```bash
$ git remote update
Fetching github
Fetching jbech
$ git checkout github/master 
HEAD is now at cc483d3 buildroot: optee_client: add ion group and set permissions on /dev/ion
$ make -j2 toolchains 
Downloading gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf ...
Downloading gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu ...
```
That works just as expected.

If that doesn't work on your side, then you must have an issue with firewalls or whatever.

**Comment by ryankumar** [comment]
@jbech-linaro thanks for your quick reply . i run your above command line but it's showing something which is error.

--2018-09-06 14:17:18--  https://releases.linaro.org/components/toolchain/binaries/6.2-2016.11/arm-linux-gnueabihf/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz
Resolving releases.linaro.org (releases.linaro.org)... 13.228.101.204
Connecting to releases.linaro.org (releases.linaro.org)|13.228.101.204|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name ‘releases.linaro.org’.
To connect to releases.linaro.org insecurely, use `--no-check-certificate'.


when i am trying to webbrowse that link it is showing "connection not secure"

**Comment by jbech-linaro** [comment]
Ok, well, I'm out of ideas.

**Comment by jforissier** [comment]
@ryankumar are you using a corporate proxy? They often act as firewalls and mess up with the secure connections, effectively making them non-secure.
Just add `--no-check-certificate` to the `curl` command in `toolchain.mk` and all should be good.

**Comment by jenswi-linaro** [comment]
I guess that means that you don't have "Let's Encrypt Authority X3" in your list of trusted CAs.

**Comment by ryankumar** [comment]
yes that may work but i copied toolchains from http://releases.linaro.org/components/toolchain/binaries/6.2-2016.11/aarch64-linux-gnu/.

but when i am running with "make run" it's comming new error

make -C /home/mahannee/Qemuv-7/build/../optee_os O=out/arm CFG_ARM64_core=y CROSS_COMPILE="/usr/bin/ccache /home/mahannee/Qemuv-7/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_core="/usr/bin/ccache /home/mahannee/Qemuv-7/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm64=/home/mahannee/Qemuv-7/build/../toolchains/aarch64/bin/aarch64-linux-gnu- CROSS_COMPILE_ta_arm32=/home/mahannee/Qemuv-7/build/../toolchains/aarch32/bin/arm-linux-gnueabihf- CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=1 CFG_TEE_BENCHMARK=n PLATFORM=vexpress-qemu_armv8a CFG_ARM64_core=y DEBUG=0 CFG_PM_DEBUG=0
make[1]: Entering directory '/home/mahannee/Qemuv-7/optee_os'
  CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
make[1]: *** No rule to make target '/home/mahannee/Qemuv-7/toolchains/aarch64/lib/gcc/aarch64-linux-gnu/6.2.1/include/stddef.h', needed by 'out/arm/core/include/generated/.asm-defines.s'.  Stop.
make[1]: Leaving directory '/home/mahannee/Qemuv-7/optee_os'
common.mk:380: recipe for target 'optee-os-common' failed
make: *** [optee-os-common] Error 2

**Comment by jforissier** [comment]
Leftovers from previous build. `rm -rf optee_os/out`.

**Comment by ryankumar** [comment]
in toolchain.mk i just added the below
"curl --insecure -L $(2) -o $(TOOLCHAIN_ROOT)/$(3).tar.xz; \"

and it was succesfully working for building toolchains. now i have no problem in "make toolchains" . now i am getting error in "make -j2" whatever i wrote in previous msg. so help me in this.

**Comment by jbech-linaro** [comment]
I've tested it as late as today and it's working fine now. Closing the ticket.
