### ISSUE TITLE
tee_shm_register with with kernel area memory to share data to TA

### ISSUE THREAD

**Issue by ncpsa** [OP-TEE/optee_os#2522]
Hi,
I want to share kernel area memory between kernel CA and TA. I have done the below.
 
- Register non secure RAM area to secure OS by using register_nsec_ddr() call.
- Avoided page pinning in tee_shm_register() from tee_shm.c

Now, I am observing crash inside optee for NULL dereference, while the register_shm() call.
Can anyone suggest, Is it really possible, if yes, could you provide some hints/guidelines?

Thanks in Advance.

Best Regards,

**Comment by jenswi-linaro** [comment]
This seems related to https://github.com/OP-TEE/optee_os/issues/2501
Does is answer your question?
