### ISSUE TITLE
Secondary CPU fails to come online after integrating optee

### ISSUE THREAD

**Issue by DorfilIkatu** [OP-TEE/optee_os#2523]
Hi,

I'm trying to port optee to a nxp imx7d platform. I've followed the porting guide to configure/build optee-os and I ported this patch to my u-boot: https://github.com/MrVan/uboot/commit/4f016adae573aaadd7bf6a37f8c58a882b391ae6 (I've changed OPTEE_ENTRY and TEE_RAM_SIZE in order to match my optee's configuration). 

After that, my image has booted almost successfully (secondary CPU fails to come online). But I've been able to develop a Trusted Application and to use that app with no problems.
Now I would like to solve the problem about the secondary CPU.

I've PSCI support enabled by default in the u-boot and in the kernel. So I disabled PSCI support on optee. (I already tried to do this in the other way, I mean disable PSCI on u-boot and in the kernel, and enable it on optee, but this gave me compile errors on the u-boot I couldn't solve).

- Is it possible that my problem is that the u-boot patch I mentioned early, just works with PSCI support disabled in the u-boot? If that is the case, what should I change in order to make it work with PSCI support on u-boot?  

- Trusted firmware-A is mandatory to successfully boot the secondary CPU?

- optee will try to run in all the CPUs, or just in the main one? I've set CFG_TEE_CORE_NB_CORE=2 in optee-os config.

Thanks in advance.

**Comment by MrVan** [comment]
@DorfilIkatu The U-Boot patch is not longer needed. If you are using ATF as what @bryanodonoghue did, @bryanodonoghue might have some ideas. If you are not using ATF, you need enable PSCI in Linux and OP-TEE to boot up secondary cores.

**Comment by bryanodonoghue** [comment]
Our port for the MX7S doesn't do any of the secondary core bring-up or mailboxing in ATF, so you'd have some work to do for the MX7D there.

**Comment by dleymarie** [comment]
I had to port OPTEE on a NXP SoC similar to imx7d (Dual Cortex-A7). 
The boot flow is BootROM -> U-Boot /Cortex-A7 core#0 -> OP-TEE -> Linux kernel

OP-TEE starts on core #0, 
it starts core#1, 
core#1 and core #0 sync, 
core #1 waits from Linux, 
core #0 gives control in Non secure mode to Linux kernel, 
Linux Kernel instead o starting core #1, does a SMC call to give start address of core#1 to optee,
Optee on core#1 gives control in Non secure mode to address given by Linux
Linux kernel (in non secure mode and in ARM mode) performs secondary_startup_arm: switching to thumb mode, some init, synchronise with core#0....

This has been made with optee_os 3.2.0 and kernel 4.9
This is a part of this work.
in optee platform directory for this SoC, 

main.c (extract)
```
#if defined(CFG_BOOT_SECONDARY_REQUEST)
void xxxxx_start_secondary_core(void)
{
        ...
}
#endif /* defined(CFG_BOOT_SECONDARY_REQUEST) */
...
void plat_cpu_reset_late(void)
{
        switch(get_core_pos()) {
                case 0:/* primary core */

#if defined(CFG_BOOT_SECONDARY_REQUEST)
                        xxxxx_start_secondary_core();
#endif /* defined(CFG_BOOT_SECONDARY_REQUEST) */
               break;
                case 1: /* secondary core */
.....
                break;
                default:
                        panic();
                break;
        }
}

```
in conf.mk (extract)

```
CFG_BOOT_SECONDARY_REQUEST ?= y
CFG_BOOT_SYNC_CPU ?= y
```

In linux kernel, I back-ported OPTEE driver and I selected OPTEE in configuration
```

diff --git a/arch/arm/mach-imx/platsmp.c b/arch/arm/mach-imx/platsmp.c
index 77430e9cfa4e..c62728b18a28 100644
--- a/arch/arm/mach-imx/platsmp.c
+++ b/arch/arm/mach-imx/platsmp.c
@@ -25,6 +25,15 @@

 #define SCU_STANDBY_ENABLE     (1 << 5)

+#ifdef CONFIG_OPTEE
+#include <linux/arm-smccc.h>
+
+#define OPTEE_SMC_CALLID_BOOT_SECONDARY       12
+#define OPTEE_SMC_BOOT_SECONDARY  \
+    ARM_SMCCC_CALL_VAL(ARM_SMCCC_FAST_CALL, ARM_SMCCC_SMC_32, \
+                ARM_SMCCC_OWNER_TRUSTED_OS, OPTEE_SMC_CALLID_BOOT_SECONDARY)
+#endif /* CONFIG_OPTEE */
+
 u32 g_diag_reg;
 static void __iomem *scu_base;

@@ -67,9 +76,27 @@ static int imx_boot_secondary(unsigned int cpu, struct task_struct *idle)

 static int xxxxx_boot_secondary(unsigned int cpu, struct task_struct *idle)
 {
-       imx_set_cpu_jump(cpu, xxxxx_secondary_startup);
-       imx_enable_cpu(cpu, true);
-
+#ifdef CONFIG_OPTEE
+    struct arm_smccc_res  res;
+       memset(&res, 0, sizeof(res));
+    arm_smccc_smc(OPTEE_SMC_BOOT_SECONDARY,                            /* SMC Function ID */
+                                 cpu,                                                                  /* Index of secondary core to boot */
+                                 0,                                                                    /* Upper 32 bits of a 64-bit Non-Secure world entry physical address */
+                                 virt_to_phys(secondary_startup_arm),  /* Lower 32 bits of a 64-bit Non-Secure world entry physical address */
+                                 0, 0, 0, 0,                                                   /* Not used */
+                                 &res);
+       /* Important note
+        * in return from OP-TEE, secondary core is in ARM mode but kernel is in Thumb mode,
+        * so we must use secondary_startup_arm entry instead of secondary_startup.
+        */
+       if (0 != res.a0) { /* if not OK */
+               imx_set_cpu_jump(cpu, xxxxx_secondary_startup);
+               imx_enable_cpu(cpu, true);
+       }
+#else /* CONFIG_OPTEE */
+               imx_set_cpu_jump(cpu, xxxxx_secondary_startup);
+               imx_enable_cpu(cpu, true);
+#endif
        return 0;
 }
 /
```*

**Comment by jbech-linaro** [comment]
> @KiirkH If not, should I back-port OPTEE driver as @dleymarie did?

I haven't actually payed attention to this on RPi3, but you are right, 2-4 doesn't come online. So, yes, it could be worth looking into doing something similar there. If you do, please submit pull requests so we can get it reviewed and merged also. Thanks!

**Comment by jbech-linaro** [comment]
@KiirkH , a patch enabling all cores on Rpi3 have been cherry-picked to our kernel fork, see https://github.com/linaro-swg/linux/commits/rpi3-optee-4.14 (and https://github.com/OP-TEE/build/issues/360).

**Comment by KiirkH** [comment]
Good news, thanks!
