### ISSUE TITLE
tee_ta_invoke_command:625 Error: ffff3024 of 3 - tee_user_ta_enter: TA panicked with code 0x0

### ISSUE THREAD

**Issue by cezane** [OP-TEE/optee_os#2532]
I am trying to derive an ECDH secret key. Below is the code I am using.

```c
struct rsa_session {
	TEE_OperationHandle op_handle;	/* Crypto operation */
	TEE_ObjectHandle key_handle; /* Key handle */
};

TEE_Result generate_secret_shared_key(void *session) {
	TEE_Result ret;
	size_t key_size = RSA_KEY_SIZE; //1024
	struct rsa_session *sess = (struct rsa_session *)session;
	struct rsa_session *ecdh_sess;

	ecdh_sess = TEE_Malloc(sizeof(ecdh_sess), 0);
	if (!ecdh_sess)
		return TEE_ERROR_OUT_OF_MEMORY;
	ecdh_sess->key_handle = TEE_HANDLE_NULL;
	ecdh_sess->op_handle = TEE_HANDLE_NULL;	

	ret = TEE_AllocateTransientObject(TEE_TYPE_GENERIC_SECRET, key_size, 
                                              &ecdh_sess->key_handle);
	if (ret != TEE_SUCCESS) {
		EMSG("\nFailed to alloc transient object handle: 0x%x\n", ret);
		return ret;
	}
	DMSG("\n==========ECDH Transient object allocated. ==========\n");

	ret = TEE_AllocateOperation(ecdh_sess->op_handle, TEE_ALG_ECDH_P256, 
                                      TEE_MODE_DERIVE, key_size);
	if (ret != TEE_SUCCESS) {
		EMSG("\nFailed to alloc operation handle : 0x%x\n", ret);
		return ret;
	}
	DMSG("\n==========ECDH Operation allocated successfully. ==========\n");

	ret = TEE_SetOperationKey(ecdh_sess->op_handle, ecdh_sess->op_handle);
	if (ret != TEE_SUCCESS) {
		EMSG("\nFailed to set key : 0x%x\n", ret);
		return ret;
	}
       DMSG("\n==========ECDH Operation key already set. ==========\n");

       return TEE_SUCCESS;
}
```

When I run, I am getting this error:
> D/TA:  RSA_get_public_key:166 
==========ECDH Transient object allocated. ==========
E/TC:? 0 
E/TC:? 0 TA panicked with code 0x0
E/TC:? 0 Status of TA 2bb620d9-3e83-463b-b261-987fa92c95ef (0xe171c90) (active)
E/TC:? 0  arch: aarch64  load address: 0x40005000 ctx-idr: 2
E/TC:? 0  stack: 0x40004000 4096
E/TC:? 0  region 0: va 0x40000000 pa 0xe100000 size 0x2000 flags ---R-X 
E/TC:? 0  region 1: va 0x40002000 pa 0xe174000 size 0x1000 flags ---RW- 
E/TC:? 0  region 2: va 0x40004000 pa 0xe318000 size 0x1000 flags rw-RW- 
E/TC:? 0  region 3: va 0x40005000 pa 0xe300000 size 0xd000 flags r-x--- [0]
E/TC:? 0  region 4: va 0x40012000 pa 0xe30d000 size 0xb000 flags rw---- [0]
E/TC:? 0  [0] 2bb620d9-3e83-463b-b261-987fa92c95ef @ 0x40005000
E/TC:? 0 Call stack:
E/TC:? 0  0x0000000040007cb4
E/TC:? 0  0x00000000400055c8
E/TC:? 0  0x0000000040005794
E/TC:? 0  0x000000004000a114
E/TC:? 0  0x000000000e102d1c
D/TC:? 0 unwind_stack_arm64:56 FP out of bounds 0
D/TC:? 0 user_ta_enter:312 tee_user_ta_enter: TA panicked with code 0x0
D/TC:? 0 tee_ta_invoke_command:625 Error: ffff3024 of 3

When debugging, I identified the problem is within `TEE_AllocateTransientObject`:
```c 
TEE_AllocateTransientObject (objectType=objectType@entry=2684354560, 
    maxKeySize=maxKeySize@entry=1024, object=object@entry=0x4001a078)
    at lib/libutee/tee_api_objects.c:206
206		res = utee_cryp_obj_alloc(objectType, maxKeySize, &obj);
(gdb) s
202	{
(gdb) n
206		res = utee_cryp_obj_alloc(objectType, maxKeySize, &obj);
(gdb) s
utee_cryp_obj_alloc () at lib/libutee/arch/arm/utee_syscalls_asm.S:65
65	        UTEE_SYSCALL utee_cryp_obj_alloc, TEE_SCN_CRYP_OBJ_ALLOC, 3
(gdb) s
```

I think it is strange because the code is printing the message `==========ECDH Transient object allocated. ==========`, which should be printed only if `TEE_AllocateTransientObject` had not failed. Any suggestion?

**Comment by jforissier** [comment]
Hi,

How does the gdb session you have copied show that `TEE_AllocateTransientObject()` has failed? Tracing ends as the function is about to enter kernel mode.

I'd say it is `TEE_AllocateOperation()` that is panicking. What does the "symbolized" call stack say? I wouldn't be surprised to see `TEE_AllocateOperation()` in there ;-)

**Comment by cezane** [comment]
You are right. My bad. =)

The error was `ecdh_sess->op_handle` instead of `&ecdh_sess->op_handle` in the `TEE_AllocateOperation` call.

Now, `TEE_AllocateOperation` is returning TEE_ERROR_NOT_SUPPORTED. According to Core API spec. v1.1.1, the key size for `TEE_TYPE_GENERIC_SECRET` can be:
> Multiple of 8 bits, up to 4096 bits. This type is intended for secret
data that has been derived from a cryptographic operation, but participates in a key derivation scheme.

This way, I used 1024, which is the RSA key size I am using for RSA key pair. Since the "RSA size" is the modulus length, I also tried 1024 / 8 for the key size value passed to `TEE_AllocateOperation`; both values failed with the same message:
> Failed to alloc operation handle : 0xffff000a

Debugging, I can see the following:
```c
53		switch (algorithm) {
(gdb) s
58				return TEE_ERROR_NOT_SUPPORTED;
(gdb) s
87			if (maxKeySize != 256)
(gdb) n
99			if (maxKeySize != 521)
(gdb) n
341	}
(gdb) n
RSA_get_public_key (session=session@entry=0x4001a090) at keyvault.c:169
169		if (ret != TEE_SUCCESS) {
(gdb) s
170			EMSG("\nFailed to alloc operation handle : 0x%x\n", ret);
(gdb) n
184	}

I am thinking if OPTEE has support to all the ECDH possible key sizes as specified. Would be those two values (256 and 521) the only possible key sizes implemented?

By the way, I noticed that OPTEE implementation is not updated yet with the last GP specification (Core API v1.1.1), since the new algorithm is `TEE_ALG_ECDH_DERIVE_SHARED_SECRET` instead of `TEE_ALG_ECDH_Pxxx__DERIVE_SHARED_SECRET`.

**Comment by cezane** [comment]
Another thing I am observing is that the algorithm name `TEE_ALG_ECDH_P256` is not GP compliant, since the previous version of the name, in the specification, was `TEE_ALG_ECDH_P256_DERIVE_SHARED_SECRET`; the updated one is just `TEE_ALG_ECDH_DERIVE_SHARED_SECRET`.

By the way, I think my thought was right, since I got success allocating operation using 256 as the key size. Now I am investigating the following error:

```c
161		ret = TEE_AllocateTransientObject(TEE_TYPE_ECDH_KEYPAIR, 256, &ecdh_sess->key_handle);
(gdb) s
TEE_AllocateTransientObject (objectType=2701131842, maxKeySize=maxKeySize@entry=256, 
    object=object@entry=0x4001a078) at lib/libutee/tee_api_objects.c:206
206		res = utee_cryp_obj_alloc(objectType, maxKeySize, &obj);
(gdb) s
202	{
(gdb) s
206		res = utee_cryp_obj_alloc(objectType, maxKeySize, &obj);
(gdb) s
utee_cryp_obj_alloc () at lib/libutee/arch/arm/utee_syscalls_asm.S:65
65	        UTEE_SYSCALL utee_cryp_obj_alloc, TEE_SCN_CRYP_OBJ_ALLOC, 3
```
This happens if I use `TEE_TYPE_ECDH_KEYPAIR` as the key type, as indicated in the GP Core API specification. I also tried using `TEE_TYPE_ECDH_PUBLIC_KEY`, but without success too. Any tip regarding this procedure?

**Comment by jforissier** [comment]
> I am observing is that the algorithm name TEE_ALG_ECDH_P256 is not GP compliant

`TEE_ALG_ECDH_P256` appears in the Internal Core API Specification v1.1 (June 2014), p.177. OP-TEE complies with 1.1, not the later updates (1.1.1 of June 2016 or 1.1.2 of November 2016).

Perhaps xtest 4009 can help you? It does use `TEE_MODE_DERIVE` with `TEE_ALG_ECDH_P256`:
https://github.com/OP-TEE/optee_test/blob/3.2.0/host/xtest/regression_4000.c#L4740
https://github.com/OP-TEE/optee_test/blob/3.2.0/host/xtest/regression_4000_data.h#L6964

**Comment by cezane** [comment]
@jforissier , in the latest specification there is the information I mentioned, that previous version was `TEE_ALG_ECDH_P256_DERIVE_SHARED_SECRET`. But, as you alerted me about OPTEE compliance with only the v1.1, I opened it and, for me, there is still something strange:

```c
TEE Internal Core API Specification – Public Release v1.1
Algorithm                                                 Possible Modes
TEE_ALG_DH_DERIVE_SHARED_SECRET                           TEE_MODE_DERIVE
TEE_ALG_ECDH_DERIVE_SHARED_SECRET (if supported)
```

I can see here in my code that `TEE_ALG_ECDH_DERIVE_SHARED_SECRET` is undefined and the supported algorithm is `TEE_ALG_ECDH_P256`, what seems different from the v1.1 specification. 

Another thing I observed is that neither the v.1.1 nor the v1.1.1 has the ECDH key sizes explicitly. They just mention: "If ECC is supported, then all the curve sizes defined in Table 6-14 MUST be supported." Then, you go to that table and do not find the key size information. I wil see if this code you suggested will help. Is there some planning to update OPTEE with the latest specification?

**Comment by cezane** [comment]
Unfortunately, I still can not understand why this code is not working:
```c
struct rsa_session {
	TEE_OperationHandle op_handle;	/* Crypto operation */
	TEE_ObjectHandle key_handle; /* Key handle */
};

TEE_Result RSA_get_public_key(void *session) {
	TEE_Result ret;
	size_t key_size = RSA_KEY_SIZE / 8;
	struct rsa_session *sess = (struct rsa_session *)session;
	struct rsa_session *ecdh_sess;

	ecdh_sess = TEE_Malloc(sizeof(ecdh_sess), 0);
	if (!ecdh_sess)
		return TEE_ERROR_OUT_OF_MEMORY;
	ecdh_sess->key_handle = TEE_HANDLE_NULL;
	ecdh_sess->op_handle = TEE_HANDLE_NULL;	

	ret = TEE_AllocateTransientObject(TEE_TYPE_ECDH_KEYPAIR, 256, &ecdh_sess->key_handle);
	if (ret != TEE_SUCCESS) {
		EMSG("\nFailed to alloc transient object handle: 0x%x\n", ret);
		return ret;
	}
	DMSG("\n==========ECDH Transient object allocated. ==========\n");

	ret = TEE_AllocateOperation(&ecdh_sess->op_handle, TEE_ALG_ECDH_P256, TEE_MODE_DERIVE, 256);
	if (ret != TEE_SUCCESS) {
		EMSG("\nFailed to alloc operation handle : 0x%x\n", ret);
		return ret;
	}
	DMSG("\n==========ECDH Operation allocated successfully. ==========\n");

	ret = TEE_SetOperationKey(ecdh_sess->op_handle, ecdh_sess->key_handle);
	if (ret != TEE_SUCCESS) {
		EMSG("\nFailed to set key : 0x%x\n", ret);
		return ret;
	}
       DMSG("\n==========ECDH Operation key already set. ==========\n");

	return TEE_SUCCESS;
}
```
We can see the problem is with `TEE_SetOperationKey`:
```c
E/TC:? 0 Call stack:
E/TC:? 0  0x0000000040007330 TEE_CopyObjectAttributes1 at optee_os/lib/libutee/tee_api_objects.c:349
E/TC:? 0  0x000000004000877c TEE_SetOperationKey at optee_os/lib/libutee/tee_api_operations.c:552
E/TC:? 0  0x0000000040005618 RSA_get_public_key at out-br/build/optee_examples-1.0/keyvault/ta/keyvault.c:175
```
But I think the operation handle and the key handle are set right, according to the specification: `TEE_TYPE_ECDH_KEYPAIR` for the key and `TEE_ALG_ECDH_P256` for the operation mode. Please let me know if I am understanding wrong and missing something.

**Comment by cezane** [comment]
Yet, if a try to generate an ECDH key pair, I got a `0xffff000a` panic message with the following code:

    ret = TEE_AllocateTransientObject(TEE_TYPE_ECDH_KEYPAIR, ECDH_KEY_SIZE, &ecdh_sess->key_handle);
	if (ret != TEE_SUCCESS) {
		EMSG("\nFailed to alloc transient object handle: 0x%x\n", ret);
		return ret;
	}
	DMSG("\n==========ECDH Transient object allocated. ==========\n");

	ret = TEE_GenerateKey(ecdh_sess->key_handle, ECDH_KEY_SIZE, (TEE_Attribute *)NULL, 0);
	if (ret != TEE_SUCCESS) {
		EMSG("\nGenerate key failure: 0x%x\n", ret);
		return ret;
	}
	DMSG("\n========== ECDH keys generated. ==========\n");


`ECDH_KEY_SIZE` is equal to 256. According to specification, this `0xffff000a` panic code is for `TEE_ERROR_NOT_SUPPORTED`, what makes me think if this operation is really supported. In case it is, the specification is very bad, since this kind of information is not clear. There is no ECDH key sizes clear... there is no ECDH good information regarding the deriving process, etc. I start to think how can it be possible that developers use this kind of technology with almost no documentation, since the specification is not well described and clear?

**Comment by cezane** [comment]
Does anyone have any suggestion?

**Comment by cezane** [comment]
The solution was provided by @sahilnxp in issue #2585 . Here is the code:

    TEE_Attribute curve_attr;

	ret = TEE_AllocateTransientObject(TEE_TYPE_ECDH_KEYPAIR, 256, &ecdh_sess->key_handle);
	if (ret != TEE_SUCCESS) {
		EMSG("\nFailed to alloc transient object handle: 0x%x\n", ret);
		return ret;
	}
	DMSG("\n==========ECDH Transient object allocated. ==========\n");

	TEE_InitValueAttribute(&curve_attr, TEE_ATTR_ECC_CURVE, TEE_ECC_CURVE_NIST_P256, sizeof(int));

	ret = TEE_GenerateKey(ecdh_sess->key_handle, ECDH_KEY_SIZE, &curve_attr, 1);
	if (ret != TEE_SUCCESS) {
		EMSG("\nGenerate key failure: 0x%x\n", ret);
		return ret;
	}
	DMSG("\n========== ECDH keys generated. ==========\n");
