### ISSUE TITLE
Clearkey in OPTEE

### ISSUE THREAD

**Issue by JohnyDev42** [OP-TEE/optee_os#2533]
Can anyone tell me how can I implement clearkey in optee ?

**Comment by jenswi-linaro** [comment]
Can you give some more details?

**Comment by ArunSahu42** [comment]
Actually I want to stream clearkey encrypted content in optee-os. For that what I have to do ? Is there any proper steps to add clearkey drm in optee

**Comment by psivasubramanian** [comment]
> Can anyone tell me how can I implement clearkey in optee ?

Hi @JohnyDev42 
Clearkey decryptor is already implemented in OPTEE and it's available in https://github.com/linaro-mmwg/meta-lhg/blob/morty/meta-lhg/recipes-security/optee/optee-aes-decryptor.bb. Hope that helps.

**Comment by JohnyDev42** [comment]
Thank you for the information.
