### ISSUE TITLE
The ARM-TF master V1.1 doesn't have support to load an OP-TEE binary

### ISSUE THREAD

**Issue by sweetkeey** [OP-TEE/optee_os#254]
when I tested optee os with ARM-TF master V1.1 (I utilized optee os tee.bin as bl32 image) on FVP,
and set Makefile:
  # Flags to generate the Chain of Trust
  GENERATE_COT		:= 1
  CREATE_KEYS		:= 1
  # Flags to build TF with Trusted Boot support
  TRUSTED_BOARD_BOOT	:= 1
  AUTH_MOD		:= polarssl
  
It stopped at "BL3-1: Initializing BL3-2",that's maybe something went wrong when OP-TEE was initializing.
When the ARM-TF which with TRUSTED_BOARD_BOOT can support to load an OP-TEE binary?
Please tell me Which files relates to? and how to analyse and solve this problem?
Too many thanks!

FVP terminal_0 log:
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v1.1(debug):
NOTICE:  BL1: Built : 17:03:10, Apr 20 2015
INFO:    BL1: RAM 0x4038000 - 0x403e000
INFO:    Using authentication module 'PolarSSL'
INFO:    Loading file 'bl2.crt' at address 0x4007000
INFO:    Skip reserving memory: 0x4007000 - 0x4007347
INFO:    File 'bl2.crt' loaded: 0x4007000 - 0x4007347
INFO:    Loading file 'bl2.bin' at address 0x4007000
INFO:    File 'bl2.bin' loaded: 0x4007000 - 0x401b018
NOTICE:  BL1: Booting BL2
INFO:    BL1: BL2 address = 0x4007000
INFO:    BL1: BL2 spsr = 0x3c5
NOTICE:  BL2: v1.1(debug):
NOTICE:  BL2: Built : 17:03:10, Apr 20 2015
INFO:    Using authentication module 'PolarSSL'
INFO:    Loading file 'trusted_key.crt' at address 0x4023000
INFO:    Skip reserving memory: 0x4023000 - 0x4023597
INFO:    File 'trusted_key.crt' loaded: 0x4023000 - 0x4023597
INFO:    Loading file 'bl31_key.crt' at address 0x4023000
INFO:    Skip reserving memory: 0x4023000 - 0x402345d
INFO:    File 'bl31_key.crt' loaded: 0x4023000 - 0x402345d
INFO:    Loading file 'bl31.crt' at address 0x4023000
INFO:    Skip reserving memory: 0x4023000 - 0x402335b
INFO:    File 'bl31.crt' loaded: 0x4023000 - 0x402335b
INFO:    Loading file 'bl32_key.crt' at address 0x4023000
INFO:    Skip reserving memory: 0x4023000 - 0x402345d
INFO:    File 'bl32_key.crt' loaded: 0x4023000 - 0x402345d
INFO:    Loading file 'bl32.crt' at address 0x4023000
INFO:    Skip reserving memory: 0x4023000 - 0x402335b
INFO:    File 'bl32.crt' loaded: 0x4023000 - 0x402335b
INFO:    Loading file 'bl33_key.crt' at address 0x4023000
INFO:    Skip reserving memory: 0x4023000 - 0x402345d
INFO:    File 'bl33_key.crt' loaded: 0x4023000 - 0x402345d
INFO:    Loading file 'bl33.crt' at address 0x4023000
INFO:    Skip reserving memory: 0x4023000 - 0x402335b
INFO:    File 'bl33.crt' loaded: 0x4023000 - 0x402335b
INFO:    BL2: Loading BL3-1
INFO:    Loading file 'bl31.bin' at address 0x4023000
INFO:    File 'bl31.bin' loaded: 0x4023000 - 0x402c010
INFO:    BL2: Loading BL3-2
INFO:    Loading file 'bl32.bin' at address 0x6000000
INFO:    File 'bl32.bin' loaded: 0x6000000 - 0x605d3e0
INFO:    BL2: Loading BL3-3
INFO:    Loading file 'bl33.bin' at address 0x88000000
INFO:    File 'bl33.bin' loaded: 0x88000000 - 0x88280000
NOTICE:  BL1: Booting BL3-1
INFO:    BL1: BL3-1 address = 0x4023000
INFO:    BL1: BL3-1 spsr = 0x3cd
INFO:    BL1: BL3-1 params address = 0x4000200
INFO:    BL1: BL3-1 plat params address = 0xf1e2d3c4b5a6978
NOTICE:  BL3-1: v1.1(debug):
NOTICE:  BL3-1: Built : 17:10:05, Apr 20 2015
INFO:    BL3-1: Initializing runtime services
INFO:    BL3-1: Initializing BL3-2

**Comment by pascal-brand-st-dev** [comment]
Is it a duplication of #197 ?

**Comment by vchong** [comment]
If this is related to #197 and you need Trusted Boot support which is not available on https://github.com/jenswi-linaro/arm-trusted-firmware/tree/optee_paged_141128, try cherry picking commit db4b9efe59b4f76e9680836a443158fde0f12e40 from that fork/branch onto your tree.

**Comment by jenswi-linaro** [comment]
I've rebased that patch in https://github.com/jenswi-linaro/arm-trusted-firmware/tree/optee_paged_armtf_v1.1

**Comment by sweetkeey** [comment]
Many thanks to pascal,vchong,jenswi.
It's a duplication of 197,Which's added Trusted Boot support.
We built with FVP_TSP_RAM_LOCATION=tdram option, add success on https://github.com/jenswi-linaro/arm-trusted-firmware/tree/optee_paged_141128
But We need Trusted Boot,so we need ARM-TF v1.1 with Trusted Boot support.

**Comment by pascal-brand-st** [comment]
This is related to https://github.com/ARM-software/tf-issues/issues/301, still to be solved.
