### ISSUE TITLE
Allocating more shared memory

### ISSUE THREAD

**Issue by jdeus** [OP-TEE/optee_os#2541]
Hello!

Using a Rpi, I'm trying to allocate ~90MB using either malloc or TEEC_AllocateSharedMemory.
What should I modify exactly ? I've tried fiddling around platform_config.h (directives below) but don't know what to modify exactly, and the boot process stops on "Initializing BL3-2".

platform_config.h
CFG_SHMEM_SIZE

user_ta_header_defines.h
TA_DATA_SIZE

Has anyone succeeded in allocating more than 4MB of memory ? How did you do it ?

**Comment by lorc** [comment]
Hi @jdeus,

Usually OP-TEE is very limited in memory, so I doubt you can significantly increase this buffer. Fortunately, OP-TEE supports dynamic shared memory. This is when application shares own memory with OP-TEE. I don't know if it is enabled on RPI, though. 

But there is another limitation in this case. 90MB buffer requires at least 180KB of heap to store page addresses + 45 pagetables to map it into TA address space. Usually, OP-TEE does not have so much resources. 

So, do you really need to allocate such big buffer? E.g. do you need whole buffer for one call? 
You can allocate this buffer in your application and then share required parts of it with OP-TEE, when you call your TA.

**Comment by jdeus** [comment]
That's a possibility indeed. However I really need to be able to allocate this amount from the TA. Is there a solution by modifying the memory layout ?

**Comment by lorc** [comment]
Generally it is possible, yes. But, it would require platform-specific changes into memory layout and some generic changes into MM code.

Unfortunately, there is no single parameter you can change and get it working.

**Comment by jdeus** [comment]
It would be great to have a how-to, lots of people seem to be interested! How about allocating more memory on Quemu ?
