### ISSUE TITLE
Qemu_v8 not starting

### ISSUE THREAD

**Issue by jdeus** [OP-TEE/optee_os#2543]
Hoy,

I'm currently trying to use it by following with qemu_v8 using Ubuntu 18.04.1.

When executing make run, I get the following error twice in a row. The UART windows **do not** appear.

_Error constructing proxy for org.gnome.Terminal:/org/gnome/Terminal/Factory0: Error calling StartServiceByName for org.gnome.Terminal: Timeout was reached_

Same problem using root.

Did anyone encounter such problem ?

**Comment by jforissier** [comment]
`sudo apt install gnome-terminal` maybe? Or perhaps you're missing some other component...

**Comment by jdeus** [comment]
I checked and gnome-terminal as well as all the dependencies listed on the build page are installed. What was the latest Ubuntu version you tried this one ?

**Comment by jdeus** [comment]
OK apparently it was as simple as:

chown YOUR_USER:YOUR_USER -R /root/devel/optee

Then make run succeeds and the two UART consoles open!

However when running tee-supplicant, I get the following error: ERR [1159] TSUP:main:663: failed to find an OP-TEE supplicant device

Any idea?

**Comment by jforissier** [comment]
I'm using Ubuntu 18.04 now, previously I was using 16.04.

**Comment by jdeus** [comment]
Reopening because this issue seems to happen randomly. Very difficult to get it to run. Sometimes requiring executing make build && make run 10 times in order to start it once.

**Comment by jbech-linaro** [comment]
@jdeus still an issue? Haven't heard anyone else reporting this.
