### ISSUE TITLE
Interrupt(FIQ) in monitor mode(aarch64)

### ISSUE THREAD

**Issue by wayling** [OP-TEE/optee_os#2544]
HI all,

I have one question about interrupt(optee aarch64).
If CPU runing in 'monitor mode(ATF)' and happen a interrupt(FIQ) in this case how handle??

Thanks!

**Comment by lorc** [comment]
@jenswi-linaro , I've seen interrupt handlers in ARM-TF (https://github.com/ARM-software/arm-trusted-firmware/blob/master/bl31/aarch64/runtime_exceptions.S#L116), so probably it handles them somehow. But don't know details.

@wayling, if you have question about ARM-TF (and not about OP-TEE builtin secure monitor), then it is better to ask at ARM-TF github page. I believe, they can answer to your question in detail.

**Comment by jenswi-linaro** [comment]
Yes, there's interrupt handlers in TF-A, but if I understand it correctly they are only used to enter EL3. If we're already at EL3 the interrupts will be masked as the stack used to handle the interrupt is used already.

I agree that it's good to check with the TF-A folks for this issue.

**Comment by wayling** [comment]
@lorc @jenswi-linaro 
Thanks!
