### ISSUE TITLE
Store Measurements into Secure Storage

### ISSUE THREAD

**Issue by Christian56** [OP-TEE/optee_os#2545]
Hi, 
I want to store the measurements done by the IMA into the secure storage of OP-TEE. I think it would be best to use this commit (https://github.com/linaro-swg/linux/commit/fc17132dbccc1d7ab18883c902d450877e561546)  and therefore don't use the default rpi fork (rpi3-optee-4.14) but the optee fork. 
Whats the best way to change the fork ? Is it enough to just edit the repo manifest file  ? 
Would you suggest a pseudo TA or a normal user TA for the purpose of storing the measurements?

**Comment by jforissier** [comment]
Hi @Christian56,

The commit you're mentioning will be in upstream kernel v4.20 (it is in linux-next already). It depends on other commits that are in v4.18 but not in our current rpi3 fork, which is based on 4.14 (rpi3-optee-4.14). So, the simplest option I think is to apply the patch on top of a v4.18 rpi3 branch. I've done just that.

Can you try this please?
```diff
diff --git a/rpi3.xml b/rpi3.xml
index 45ac4da..fb13d69 100644
--- a/rpi3.xml
+++ b/rpi3.xml
@@ -16,7 +16,7 @@
 
         <!-- linaro-swg gits -->
                  <!-- ARM Trusted Firmware, cannot use refs/tags, since we need current tip and that is not tagged  -->
-        <project path="linux"                name="linaro-swg/linux.git"                  revision="rpi3-optee-4.14" clone-depth="1" />
+        <project path="linux"                name="jforissier/linux.git"                  revision="wip/rpi3-optee-4.18" clone-depth="1" />
         <project path="optee_benchmark"      name="linaro-swg/optee_benchmark.git"/>
         <project path="optee_examples"       name="linaro-swg/optee_examples.git" />
 
```
If it works for you, I will create branch `rpi3-optee-4.18` in https://github.com/linaro-swg/linux.

**Comment by jforissier** [comment]
Regarding you question: pseudo vs normal TA, the usual answer is: if you can write a normal TA it is usually better, because a normal TA has less privileges (runs at S-EL0 rather than S-EL1).

If you need the TA to run early after boot (before `tee-supplicant` is started), then you can make it an "early TA", see `mk/config.mk`.

**Comment by Christian56** [comment]
hi @jforissier, 
So I tried to open a session to the early TA. However, that failed. Therefore i wanted to ask if i need to put the early TAs in a specific folder ? From what i read the tee core should look for the TA and load it. But im not sure in which function(just to ensure that the SW is already running and to look if the TA is found/loaded). 
I compiled the system with 
`make EARLY_TA_PATHS= >absolute path>`
Is that correct or do I need to give an relative path ? ( I guess i shouldn't matter)

**Comment by jforissier** [comment]
Hi @Christian56 ,

No need to put the TA in a specific location. You may use absolute or relative path (relative to the optee_os main Makefile). Did you give the path to the ELF file? It is the `.stripped.elf` file that you want, not the `.ta` file. First look at the build log and see if something differs from this (I'm using QEMU and the hello world example here, your app will have a different UUID obviously):
```
$ cd optee-qemu/build
$ make -j40 CFG_EARLY_TA=y
...
$ make EARLY_TA_PATHS=../out-br/build/optee_examples-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.stripped.elf
...
  GEN     out/arm/core/early_ta_8aaaf200-2450-11e4-abe2-0002a5d5c51b.c
  CC      out/arm/core/early_ta_8aaaf200-2450-11e4-abe2-0002a5d5c51b.o
...
```
Then at run time, watch for these debug traces:
```
...
I/TC: OP-TEE version: 3.2.0-79-g85771856 #5 Mon Oct  8 13:21:07 UTC 2018 arm
D/TC:0 0 tee_ta_register_ta_store:534 Registering TA store: 'REE' (priority 10)
D/TC:0 0 early_ta_init:226 Early TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b size 24503 (compressed, uncompressed 120200)
D/TC:0 0 tee_ta_register_ta_store:534 Registering TA store: 'early TA' (priority 5)
D/TC:0 0 tee_ta_register_ta_store:534 Registering TA store: 'Secure Storage TA' (priority 9)
...
D/TC:? 0 tee_ta_init_pseudo_ta_session:274 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
D/TC:? 0 load_elf:842 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (early TA)
D/TC:? 0 load_elf_from_store:810 ELF load address 0x103000
...
```
Compared with a "normal" (REE) TA, in this case running `xtest 4002`:
```
...
D/TC:? 0 tee_ta_init_pseudo_ta_session:274 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
D/TC:? 0 load_elf:842 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (early TA)
D/TC:? 0 load_elf:842 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
D/TC:? 0 load_elf:842 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (REE)
D/TC:? 0 load_elf_from_store:810 ELF load address 0x10b000
D/TC:? 0 tee_ta_init_user_ta_session:1021 Processing relocations in cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
...
```

HTH.

**Comment by Christian56** [comment]
Hi @jforissier, 

thanks for your fast reply.
So i don't get any confirmation from the build log. However I get 
```
...
I/TC:  OP-TEE version: 3.2.0-dev #5 So 7. Okt 21:09:09 UTC 2018 aarch64
D/TC:0 tee_ta_register_ta_store:534 Registering TA store: 'REE' (priority 10)
D/TC:0 early_ta_init:226 Early TA f4e750bb-1437-4fbf-8785-8d3580c34994 size 22202 (compressed, uncompressed 99696)
D/TC:0 tee_ta_register_ta_store:534 Registering TA store: 'early TA' (priority 5)
D/TC:0 tee_ta_register_ta_store:534 Registering TA store: 'Secure Storage TA' (priority 9)
D/TC:0 mobj_mapped_shm_init:559 Shared memory address range: 8800000, a800000 
....
```
So  it seems to be compiled correctly. But i dont seem to get a 

`D/TC:? 0 tee_ta_init_pseudo_ta_session:274 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b`
like you did. What seems suspicious, from my point of view, is this Info: 

```
D/TC:0 tee_ta_init_pseudo_ta_session:274 Lookup pseudo TA bb50e7f4-3714-bf4f-8785-8d3580c34994
D/TC:0 load_elf:842 Lookup user TA ELF bb50e7f4-3714-bf4f-8785-8d3580c34994 (early TA)
D/TC:0 load_elf:842 Lookup user TA ELF bb50e7f4-3714-bf4f-8785-8d3580c34994 (Secure Storage TA)
```
As it resembles my UUID quite a lot f4e750bb-1437-4fbf-8785-8d3580c34994. 
Is that a UUID  which is called usually ?

**Comment by jforissier** [comment]
@Christian56 indeed, your early TA is compiled and linked into the TEE binary properly. As you say, the problem seems related to UUID encoding. The value that is requested by the client application (in normal world) does not match what is available in secure world. It seems you have a discrepancy in the little/big endian encoding. Note how the bytes are swapped in the first part of the UUID which is expressed as integer quantities not as a byte array. Try swapping them!

**Comment by Christian56** [comment]
That helped a lot thanks :)
