### ISSUE TITLE
Spurious interrupts with GICv3

### ISSUE THREAD

**Issue by kurcha01-arm** [OP-TEE/optee_os#2548]
[3.2.0]
[xtest.txt](https://github.com/OP-TEE/optee_os/files/2396648/xtest.txt)
[xtest_t1.txt](https://github.com/OP-TEE/optee_os/files/2396651/xtest_t1.txt)

Hello,

I've been trying to use xtest to verify an OP-TEE setup on a ~~Foundation~~Base fast model.

When the tests run and one of them tries to call TEEC_OpenSession, it appears to crash the entire model. The test this occurs on is not always the same: sometimes it's regression 1001/1002, usually it's regression 1003. xtest isn't actually crashing when this happens: it's repeatedly and rapidly giving this output in terminal 1 (where my OP-TEE output is):

```
D/TC:0 0 gic_it_handle:401 ignoring interrupt 1022
D/TC:0 0 gic_it_handle:401 ignoring interrupt 1022
D/TC:0 0 gic_it_handle:401 ignoring interrupt 1022
D/TC:0 0 gic_it_handle:401 ignoring interrupt 1022
```

In GICv3, Interrupt 1022 is used for legacy operation and can be called when the device is in secure operation but there is a non-secure interrupt of sufficient priority that needs non-secure software to deal with it. This would explain the inconsistent place of failure: regression 1003 opens 6 contexts, regression 1001/1002 only open 1.

INTID 1022 is ignored by OP-TEE OS because it exceeds GIC_MAX_INT. In GICv1/v2 this was 1020, as in the code, however in GICv3 this is implementation defined. By using this patch:

```
diff --git a/core/drivers/gic.c b/core/drivers/gic.c
index 1cee46c..fc9e1e1 100644
--- a/core/drivers/gic.c
+++ b/core/drivers/gic.c
@@ -58,7 +58,11 @@
 #define ITARGETSR_FIELD_MASK	0xff
 
 /* Maximum number of interrups a GIC can support */
+#if defined(CFG_ARM_GICV3)
+#define GIC_MAX_INTS		65535
+#else
 #define GIC_MAX_INTS		1020
+#endif
 
 #define GICC_IAR_IT_ID_MASK	0x3ff
 #define GICC_IAR_CPU_ID_MASK	0x7

```
(as a temporary hack) I'm able to move past regression 1003 and pass some further tests.

This may be the end of the issue. Is GICv3 actively supported by OP-TEE OS? I can see the commit that added CFG_ARM_GICV3 was added fairly recently in 2.5.0

---

Once I get past regression 1003, other tests are still failing. This may be the same issue but I would guess it's an unrelated issue or my configuration.

```
######################################################
#
# regression
#
######################################################

* regression_1001 Core self tests
  regression_1001 OK

* regression_1002 PTA parameters
  regression_1002 OK

* regression_1003 Core internal read/write mutex
    Number of parallel threads: 6 (2 writers and 4 readers)
    Max read concurrency: 2
    Max read waiters: 1
    Mean read concurrency: 1.3125
    Mean read waiting: 1
  regression_1003 OK

* regression_1004 Test User Crypt TA
/home/kurcha01/scm/optee_test/host/xtest/regression_1000.c:441: xtest_teec_open_session( &session, &crypt_user_ta_uuid, ((void *)0), &ret_orig) has an unexpected value: 0xffff0005 = TEEC_ERROR_BAD_FORMAT, expected 0x0 = TEEC_SUCCESS
  regression_1004 FAILED

```
[snip]
```
+-----------------------------------------------------
917 subtests of which 378 failed
74 test cases of which 53 failed
0 test case was skipped
TEE test application done!
```
...and the failure is due to:
```
D/TC:0 tee_ta_init_user_ta_session:1019 Processing relocations in 873bcd08-c2c3-11e6-a937-d0bf9c45c61c
E/TC:0 tee_ta_init_user_ta_session:1042 Invalid TA flag(s) 0x3
```
Looking at lib/libutee/include/user_ta_header.h and core/arch/arm/kernel/user_ta.c, I don't see how this flag could be settable.

---

Other information which may help

1) I'm using the system guidance script:
wget https://community.arm.com/cfs-file/__key/communityserver-wikis-components-
files/00-00-00-00-10/1651.armplat_5F00_1807.py -O 1651.armplat_1807.py with this configuration:

```
# +-------------+--------------------------------------------------+
# | Workspace   | <Current Path>                                   |
# | Platform    | Armv8-A Base Platform with 64-bit software stack |
# | Type        | Build from source                                |
# | Environment | Linux kernel + filesystem                        |
# | Kernel      | latest-armlt                                     |
# | Filesystem  | OpenEmbedded Minimal                             |
# +-------------+--------------------------------------------------+
```

...and enabling the OPTEE-OS build by updating the scripts and forcing the configuration for Linux. I've also updated the Linux config file and dtb to enable TEE. This gives me /dev/tee0 and /dev/teepriv0 and I run tee-supplicant before xtest.

2) The header for the OP-TEE device is invalid:

INFO:    OPTEE ep=0x6000000
INFO:    OPTEE header info:
INFO:          magic=0xaa0003f3
INFO:          version=0xf4
INFO:          arch=0x3
INFO:          flags=0xaa02
INFO:          nb_images=0x1000ffc0
WARNING: Not a known TEE, use default loading options.
INFO:    Invalid OPTEE header, set legacy mode.

However it appears to load and this warning seems to be from my configuration or an arm-trusted-firmware issue.

[    2.776686] optee: probing for conduit method from DT.
[    2.776783] optee: revision 3.2 (53bf1c38)
[    2.777727] optee: initialized driver

3) I've tried this on releases 3.2.0 and 2.5.0 with the same output.

**Comment by jenswi-linaro** [comment]
If you pass `--arm-v8.0` to the model when starting, does that help?

**Comment by kurcha01-arm** [comment]
--arm-v8.0 doesn't show up in the --list_params output and gives me an error:
```
FVP_Base_RevC-2xAEMv8A: unrecognized option `--arm-v8.0'
```

**Comment by kurcha01-arm** [comment]
I'm sorry, I see my mistake now. I have been using the Base Model, not the Foundation Model. I got them confused.

As it's on the supported list, I will see if the Foundation Model will work.

I'm still interested in why GIC_MAX_INT is 1020 for GICv3 though, my patch seemed to fix some errors but seems 'too easy'.

Thanks

**Comment by pokitoz** [comment]
Which flags are you using to build ATF-A? Do you have the following:
```
SPD=opteed
ARM_TSP_RAM_LOCATION=tdram
FVP_USE_GIC_DRIVER=FVP_GICV3_LEGACY
```

**Comment by kurcha01-arm** [comment]
> FVP_USE_GIC_DRIVER=FVP_GICV3_LEGACY

This was the source of the issue. I did not need to use the patch for GIC_MAX_INT.

**Comment by jenswi-linaro** [comment]
Did you have to use `--arm-v8.0`?

**Comment by kurcha01-arm** [comment]
I don't know if you need `--arm-v8.0` for the Base model, @pokitoz found the necessary flag to pass the tests on the Foundation model before I got the Base model working.

**Comment by pokitoz** [comment]
One think I would like to add is that flag is marked as deprecated.
https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/user-guide.rst#414arm-fvp-platform-specific-build-options.

Maybe another solution should be find instead. Like using GIVv2 ?

The flag `--arm-v8.0` is present in the Foundation model but not in the FVP_Base_RevC one.

**Comment by jenswi-linaro** [comment]
We have one or two issues here. The first is GIC related, v2/v3/legacy.

Then there's the question of which ARM architecture is simulated. In the past I've noticed problems with ARM arch > 8.0 depending on dynamic shared memory usage and how the Linux kernel is compiled. I just wanted to check if it seemed that you where running into that issue too.

**Comment by soby-mathew** [comment]
@jenswi-linaro,
Just wanted to call out that TF-A intends to remove support for the deprecated GICV3_LEGACY driver in the upcoming 2.0 release as indicated [here ](https://github.com/ARM-software/tf-issues/issues/613).

To give some context, there are 3 GIC drivers in TF-A
1. GICv3  (driver files in  [drivers/arm/gic/v3](https://github.com/ARM-software/arm-trusted-firmware/tree/master/drivers/arm/gic/v3)).
2. GICv2 (driver files in  [drivers/arm/gic/v2](https://github.com/ARM-software/arm-trusted-firmware/tree/master/drivers/arm/gic/v2)).
3. GICv3_legacy (the [arm_gic.c](https://github.com/ARM-software/arm-trusted-firmware/blob/master/drivers/arm/gic/arm_gic.c) file)

The First 2 drivers only supports the GIC version it indicates. For example, the GICv3 driver will expect a GICv3 hardware (or model) and will only allow normal world and secure world software to execute in GICv3 mode.

The 3rd driver is deprecated because it allowed various assymetric GIC modes (For example, if executing on GICv3 hardware, it allowed Normal world to run in GICv3 mode and Secure world in GICv2 mode) which introduced many corner cases and hard-to-handle race scenarios. This driver was only maintained to allow TOSs/platforms to migrate to one of the GICv3/2 drivers.

**Comment by filiperinaldi** [comment]
> Then there's the question of which ARM architecture is simulated. In the past I've noticed problems with ARM arch > 8.0 depending on dynamic shared memory usage and how the Linux kernel is compiled. I just wanted to check if it seemed that you where running into that issue too.

FVP Base AEMv8A defaults to 8.0. Kurtis is not enabling other extensions.

**Comment by kurcha01-arm** [comment]
https://github.com/OP-TEE/build/blob/7372a5138f6aa9081a39009530fbb8b1a2123983/fvp.mk#L62

I'll reopen this as the builds are using this now-deprecated flag.

**Comment by b49020** [comment]
Hi All,

There seems to be an issue with GICv3 interrupt handling in OP-TEE. As per GICv3 spec, interrupt ID: 1022 in icc_iar0 could also mean that there is high priority group 1 interrupt. So group 1 secure interrupt (in case of GICv3) isn't acknowledged in OP-TEE currently. I have already proposed a patch [here](https://github.com/OP-TEE/optee_os/pull/2564/commits/940787821b32df816961e76f5492692f25a5d33a) to fix this. Do let me know if this fixes this issue too.

**Comment by jforissier** [comment]
@b49020 I can reproduce the same issue ("ignoring interrupt 1022") on FVP platform with GICv3 enabled (TF-A: `FVP_USE_GIC_DRIVER=FVP_GICV3`, and OP-TEE: `CFG_ARM_GICV3=y`).

And, I can confirm that your patch fixes it :). Could you please open a separate pull request with only that patch so that it can be reviewed and merged independently from the Synquacer stuff?

**Comment by b49020** [comment]
@jforissier Thanks for your confirmation. I will create a separate pull request for GICv3 fix.

**Comment by filiperinaldi** [comment]
@b49020's PR with the fix for this problem has been merged: https://github.com/OP-TEE/optee_os/pull/2650. @kurcha01-arm, this issue can be closed.

**Comment by kurcha01-arm** [comment]
Thanks everyone.
