### ISSUE TITLE
recipe for target 'edk2-common' failed

### ISSUE THREAD

**Issue by rahul-janani** [OP-TEE/optee_os#2550]
I am building the QEMU optee source code during this i got error i.e  

- bash: line 4: build: command not found
- common.mk:290: recipe for target 'edk2-common' failed
- make: *** [edk2-common] Error 127

How to resolve this issue and please give solution for this.

**Comment by cezane** [comment]
As @vchong mentioned [here](https://github.com/OP-TEE/optee_os/issues/1476), try:

    sudo apt install iasl

**Comment by rahul-janani** [comment]
I was installed that package still i am getting same error.Please tell me how to resolve this.

**Comment by cezane** [comment]
You can take a look here: https://github.com/OP-TEE/optee_os/issues/815

Also, I think it is better if you edit your question including more information (message lines).

**Comment by jbech-linaro** [comment]
QEMU is built and tested in all pull requests (https://travis-ci.org/OP-TEE/optee_os/pull_requests) , i.e., it's unlikely that it fails for more than a couple hours a day or so if there is a regression.
