### ISSUE TITLE
Benchmarks build problems

### ISSUE THREAD

**Issue by jdeus** [OP-TEE/optee_os#2551]
Hi,

Got some problems when building optee_benchmarks:

cd ~/devel/optee/optee_benchmark
make

First, had to modify benchmark_aux.h:

#include "tee_client_api.h"
#include "tee_bench.h"

Then:

cp /root/devel/optee/optee_client/out/export/include/tee_client_api.h /root/devel/optee/optee_benchmark
cp /root/devel/optee/optee_client/out/export/include/tee_bench.h /root/devel/optee/optee_benchmark
make

gcc -Wall -Wextra -Werror -I/include -I/include -I/root/devel/optee/optee_benchmark/out/libyaml/out/include -c benchmark_aux.c -o /root/devel/optee/optee_benchmark/out/benchmark_aux.o
gcc -lm -lteec -lyaml -lpthread -L/lib -L/root/devel/optee/optee_benchmark/out/libyaml/out/lib -o /root/devel/optee/optee_benchmark/out/benchmark /root/devel/optee/optee_benchmark/out/main.o /root/devel/optee/optee_benchmark/out/benchmark_aux.o
**/usr/bin/ld: cannot find -lteec**

### When building from the build dir:
cd ~/devel/optee/build
make benchmark-app-common

Output:
/root/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc -Wall -Wextra -Werror -I/root/devel/optee/build/../optee_client/out/export/include -I/root/devel/optee/build/../optee_client/libteec/include -I/root/devel/optee/optee_benchmark/out/libyaml/out/include -c main.c -o /root/devel/optee/optee_benchmark/out/main.o
test -d /root/devel/optee/optee_benchmark/out || mkdir -p /root/devel/optee/optee_benchmark/out
/root/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc -Wall -Wextra -Werror -I/root/devel/optee/build/../optee_client/out/export/include -I/root/devel/optee/build/../optee_client/libteec/include -I/root/devel/optee/optee_benchmark/out/libyaml/out/include -c benchmark_aux.c -o /root/devel/optee/optee_benchmark/out/benchmark_aux.o
/root/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc -lm -lteec -lyaml -lpthread -L/root/devel/optee/build/../optee_client/out/export/lib -L/root/devel/optee/optee_benchmark/out/libyaml/out/lib -o /root/devel/optee/optee_benchmark/out/benchmark /root/devel/optee/optee_benchmark/out/main.o /root/devel/optee/optee_benchmark/out/benchmark_aux.o
/root/devel/optee/toolchains/aarch64/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /root/devel/optee/optee_benchmark/out/libyaml/out/lib/libyaml.so when searching for -lyaml
/root/devel/optee/toolchains/aarch64/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../../../aarch64-linux-gnu/bin/ld: **skipping incompatible /root/devel/optee/optee_benchmark/out/libyaml/out/lib/libyaml.a** when searching for -lyaml
/root/devel/optee/toolchains/aarch64/bin/../lib/gcc/aarch64-linux-gnu/6.2.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lyaml
collect2: error: ld returned 1 exit status
Makefile:55: recipe for target '/root/devel/optee/optee_benchmark/out/benchmark' failed

**Comment by igoropaniuk** [comment]
@jdeus 
Benchmark app is built as a package implicitly within the `buildroot` target.
You just have to enable CFG_TEE_BENCHMARK  in `common.mk`
```
# default disable latency benchmarks (over all OP-TEE layers)
CFG_TEE_BENCHMARK               ?= y 
```

**Comment by jdeus** [comment]
That's exactly what I did, unfortunately it doesn't build and the benchmark binary is thus not included in the rootfs cpio

**Comment by igoropaniuk** [comment]
@jdeus 
If to follow your initial message, seems that you tried to build `benchmark-app-common` target instead of buildroot (`make benchmark-app-common`).
I have double checked the build today, and haven't faced any issues.

**Comment by jdeus** [comment]
OK some progress:

**Comment by igoropaniuk** [comment]
ok, seems I found out the root cause. When you initially tried to build `benchmark-app` directly by running `make` in `optee_benchmark`, it was built using default gcc toolchain installed in your system instead of the one in `toolchain` dir, as you didn't provide proper proper `CROSS_COMPILE` environment variable (and also you should have provided `TEEC_EXPORT`, that's why you faced this error message `benchmark_aux.h:31:28: fatal error: tee_client_api.h: No such file or directory`). 

As after this step libyaml compiled (as benchmark app depends on this lib) successfully for x86 architecture (because of wrong toolchain), linker didn't find proper arm version of libyaml library during invocation of `make benchmark-app-common` (your second attempt to build benchmark app from `build`).


This is what `file` shows for libyaml.so after you just run `make` in the `optee_benchmark`.
```
$ ~/work/linaro/reps/repo/qemu_default/optee_benchmark/libyaml$ file ../out/libyaml/out/lib/libyaml-0.so.2.0.5 
../out/libyaml/out/lib/libyaml-0.so.2.0.5: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=20844259425efebedce9e9d6006d4fa01803ec89, not stripped
```

**Comment by jdeus** [comment]
My fault there, when using the absolute path for the host app as argument to benchmark, it works (i.e. benmark /usr/sbin/binary).

The host and TA execute as expected, but I'm facing the same problem as #2553 : the ts file produced by benchmark is empty. 

**benchmark /usr/sbin/optee_example_load_call_unload_small 1 1**
[BencD/TC:0 tee_ta_init_session_with_context:459 Re-open TA 0b9a63b0-b4c6-4c85-a284-a228ef547b4e
hmark] D/TC:0 tee_ta_invoke_command:625 Error: ffff0006 of 4
INFO: 1. Opening Benchmark Static TA...D/TC:0 tee_ta_init_pseudo_ta_session:274 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5016f9b

D/TC:0 load_elf:842 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5016f9b (Secure Storage TA)
[Benchmark] INFO: 2. Allocating per-core buffers, cores detected = 4
[Benchmark] INFO: 3. Starting origin D/TC:0 load_elf:842 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5016f9b (REE)
host app /usr/sbin/optee_example_load_call_unload_small ...
[Benchmark] INFO: Dumping timestamps to /usr/sbin/optee_example_load_call_unload_small.ts ...
===================================================================================================================
Starting load_call_unload_small
LOAD_COUNT=1
CALL_COUNT=1
D/TC:0 load_elf_from_store:810 ELF load address 0x40305000
D/TC:0 tee_ta_init_user_ta_session:1019 Processing relocations in 8aaaf200-2450-11e4-abe2-0002a5016f9b
tcount=0 / 1Loading complete
Loading: LOAD_COUNT=1 TOTAL_D/TC:0 tee_ta_close_session:380 tee_ta_close_session(0x8485450)
TID/TC:0 tee_ta_close_session:399 Destroy session
CKS=1224D/TC:0 tee_ta_close_session:425 Destroy TA ctx
21.000000 TOTAL_TIME_SEC=0.122421 MEAN_TICKS=122421.000000 MEAN_TIME_SEC=0.122421 FIRST_TICKS=122421.000000 FIRST_TIME_SEC=0.122421
[BeD/TC:0 unregister_benchmark:155 Benchmark: Unregister benchmark ts buffer paddr = 0x0
nchmaD/TC:0 tee_ta_close_session:380 tee_ta_close_session(0x8485510)
rk]D/TC:0 tee_ta_close_session:399 Destroy session
 INFO: 4. Done benchmark

cat /usr/sbin/optee_example_load_call_unload_small.ts
**timestamps: []
...**
