### ISSUE TITLE
Support for HiKey 970

### ISSUE THREAD

**Issue by xumengwei** [OP-TEE/optee_os#2562]
Does optee support HiKey 970? If so, which target shall I use, HiKey or HiKey 960?

**Comment by jbech-linaro** [comment]
Hi @xumengwei ,

HiKey 970 is not supported. You find all officially supported devices in the list [here](https://github.com/OP-TEE/optee_os#3-platforms-supported).

**Comment by xumengwei** [comment]
Thanks for your reply @jbech-linaro . Any plan to support 970 since I found this chip is becoming quite popular nowadays?

**Comment by jbech-linaro** [comment]
As soon as someone in our team get hold of such a device, then I'm pretty sure we will add it. But if and when that will happen I cannot say for the moment. Having that said, we wouldn't mind if someone outside the core team submitted board support for this ([faq](https://github.com/OP-TEE/optee_website/blob/master/faq/README.md#how-do-i-port-op-tee-to-another-platform), [porting guidelines](https://github.com/OP-TEE/optee_os/blob/master/documentation/porting_guidelines.md)).

**Comment by xumengwei** [comment]
@jbech-linaro got it. Can I find the announcement about someone inside the group starts to porting it afterwards?

**Comment by jbech-linaro** [comment]
There is no easy way to do it, but if we do we will send pull request and then we can try to remember this particular issue and refer to that when submitting the PR.

**Comment by hugovincent** [comment]
Is there any update on this, now that the 970 boards are widely available?

**Comment by R-kismeti** [comment]
Can it be supported now？

**Comment by ya0guang** [comment]
> Can it be supported now？

I also want to know if it can be supported, since hikey 960 is very hard to purchase now.

**Comment by jforissier** [comment]
I have not heard of anyone running OP-TEE on a HiKey970, but perhaps you should ask on a HiKey970 forum (if that exists)?
It doesn't look like TF-A supports that board yet, which would be a prerequisite for OP-TEE.

**Comment by Myriad-Dreamin** [comment]
> I have not heard of anyone running OP-TEE on a HiKey970, but perhaps you should ask on a HiKey970 forum (if that exists)?
> It doesn't look like TF-A supports that board yet, which would be a prerequisite for OP-TEE.

there already exists a version of [arm-trusted-firmware](https://github.com/96boards-hikey/arm-trusted-firmware/tree/hikey970_v1.0) that can run on hikey-970


I have modified the `OP-TEE/build/hikey960.mk` to run aosp/linux over optee. And I found that:

+ It works well if I remove `BI32*` (`optee_os_header_v2_bin, optee_os_pager_v2_bin, optee_os_pageable_v2_bin`) arm-trusted-firmware flags. 
+ If I add `BI32*` flags and flash the compiled binaries into hikey, the serial console does not output anything.

It told me something went wrong when compiling optee. To compile optee, I only slightly modified `core/arch/arm/plat-hikey/platform_config.h` according to this [blog](https://www.96boards.org/blog/hikey970-mainlining-update-part1/) to continue. the blog says that:

> The Kirin970(Hi3670) SoC is just a superset of Hi3660 SoC with an added AI processing element.

So what else can I do (e.g. how to debug optee binaries) to let optee support hikey-970?

**Comment by henrydcase** [comment]
@Myriad-Dreamin did you progress any further?
