### ISSUE TITLE
Does OPTEE supports psci for imx6dl platform

### ISSUE THREAD

**Issue by Sourabhharman** [OP-TEE/optee_os#2565]
Hi,
We are porting optee on imx6dl target. As imx6 is ARM-v7, power management need to be handles by the OPTEE.
So I checked the imx support in OPTEE source, where I listed the files present inside: **core/arch/arm/plat-imx/pm/**
_cpuidle-imx7d.c 
gpcv2.c
 imx7_suspend.c 
pm-imx7.c 
psci.c  
psci-cpuidle-imx7.S  
psci-suspend-imx7.S_

As i cannot find any imx6 name specific file, so my doubt is like whether PSCI is supported for imx6 series of processors?

Thanks in Advance for an answer.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
