### ISSUE TITLE
"I/TC:  Dynamic shared memory is disabled"

### ISSUE THREAD

**Issue by jdeus** [OP-TEE/optee_os#2566]
Hi,

For some reason dynamic shared memory is now disabled and the message "I/TC:  Dynamic shared memory is disabled" is shown on boot.

What directives should be changed to enable shm?

**Comment by jenswi-linaro** [comment]
The kernel you're using doesn't have dynamic shared memory configured. Either because it's old or just because you haven't enabled it.

**Comment by jdeus** [comment]
That's strange because I used the same yesterday and didn't face this issue - shm was working properly. I didn't update the repo since then. I'm using the default platform_config for the rpi3 too. What should I check ?
