### ISSUE TITLE
TEE_BigIntAdd fails when dest=op

### ISSUE THREAD

**Issue by jdeus** [OP-TEE/optee_os#2577]
TEE_BigIntAdd fails when dest=op.

Example:

```
TEE_BigInt bintp;
TEE_BigInt bintone;

TEE_BigIntInit(&bintp, TEE_BigIntSizeInU32(1024)); // will set it to zero
TEE_BigIntInit(&bintone, TEE_BigIntSizeInU32(1024));

TEE_BigIntConvertFromS32(&bintone, 1);

for (int i = 0; i < 10; ++i) {
	TEE_BigIntAdd(&bintp, &bintp, &bintone);
}
```

Produces the following runtime error:

> D/TC:0 abort_handler:671 [abort] abort in User mode (TA will panic)
> E/TC:0
> E/TC:0 User TA data-abort at address 0x40711000 (translation fault)
> (redacted)

Expected: no failure

From TEE Internal Core API Specification 1.1.2.50:
> 8.8.1 TEE_BigIntAdd
> All or some of dest, op1, and op2 MAY point to the same memory region but SHALL point to the start address of a TEE_BigInt.

**Comment by jenswi-linaro** [comment]
Patches are welcome!

**Comment by jenswi-linaro** [comment]
I can't recreate the problem with the test code supplied. I've tried with both libmpa and the mbedtls bignum. Looking at the two implementations they seem to take care of this special special case.
