### ISSUE TITLE
OP-TEE Support on i.MX6 Quad SABRE SD Board

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#2584]
Hi experts,

Is there any document or instruction about how to deploy OP-TEE  on i.MX6 Quad SABRE SD Board with the original [Android 8.0 Rich OS](https://www.nxp.com/docs/en/user-guide/Android_User's_Guide.pdf)?

I checked the [build web page](https://github.com/OP-TEE/build) while I do not get anything specific about the i.MX6 board.

Any reference or suggestion is welcomed.

Simon

**Comment by jbech-linaro** [comment]
I'm not aware of any such instructions, maybe @OP-TEE/plat-imx knows?

**Comment by bryanodonoghue** [comment]
Nope - sorry
