### ISSUE TITLE
0xffff000a panic when trying to generate an ECDH key pair

### ISSUE THREAD

**Issue by cezane** [OP-TEE/optee_os#2585]
I am trying to generate an ECDH key pair. I am getting a `0xffff000a` panic message with the following code:
```c
ret = TEE_AllocateTransientObject(TEE_TYPE_ECDH_KEYPAIR, ECDH_KEY_SIZE, &ecdh_sess->key_handle);
if (ret != TEE_SUCCESS) {
	EMSG("\nFailed to alloc transient object handle: 0x%x\n", ret);
	return ret;
}
DMSG("\n==========ECDH Transient object allocated. ==========\n");

ret = TEE_GenerateKey(ecdh_sess->key_handle, ECDH_KEY_SIZE, (TEE_Attribute *)NULL, 0);
if (ret != TEE_SUCCESS) {
	EMSG("\nGenerate key failure: 0x%x\n", ret);
	return ret;
}
DMSG("\n========== ECDH keys generated. ==========\n");
```
`ECDH_KEY_SIZE` is equal to 256. According to specification, this `0xffff000a` panic code is for `TEE_ERROR_NOT_SUPPORTED`, what makes me think if this operation is really supported. In case it is, the specification is not so good, since this kind of information is not clear. There is no ECDH key sizes... there is no ECDH good information regarding the deriving process, etc. 

Can anyone help regarding this kind of operation?

**Comment by sahilnxp** [comment]
Hi @cezane 

I think you are missing the TEE_ATTR_ECC_CURVE to be passed in TEE_GenerateKey for generating ECDH Keypair.
It is mentioned in the Global Platform Internal API specification in TEE_GenerateKey API section.

![image](https://user-images.githubusercontent.com/27992285/47022195-915ff380-d17a-11e8-82f7-986fd97d5104.png)

I have successfully generate ECDSA Keyapir using following code.

```
TEE_Attribute curve_attr;
TEE_ObjectHandle *tObject;

TEE_AllocateTransientObject(TEE_TYPE_ECDSA_KEYPAIR, 256, tObject);
TEE_InitValueAttribute(&curve_attr, TEE_ATTR_ECC_CURVE,
			     TEE_ECC_CURVE_NIST_P256, sizeof(int));
TEE_GenerateKey(*tObject, 256, &curve_attr, 1);
```

**Comment by cezane** [comment]
Hello, @sahilnxp . Thank you a lot! It worked. I think the GP specification could be more detailed regarding these steps. :(

I have two doubts:

1. Why use the `TEE_InitValueAttribute` instead of `TEE_InitRefAttribute`? 
2. Why `sizeof(int)` is passed as the second value (`b`)?

Can you please explain me both?

**Comment by Raincode** [comment]
> Why sizeof(int) is passed as the second value (b)?

I wondered the same thing, and just passed `0`. I still didn't get any errors from that, so I assume `TEE_ATTR_ECC_CURVE` just looks at the first value (a) and ignores the second value (b), so the cleanest is probably just setting it to `0` IMHO. If anyone else has information about this, please do share.

**Comment by jforissier** [comment]
@Raincode correct, `.b` is not used when populating a `TEE_ATTR_ECC_CURVE` attribute. Setting it to `0` is probably best indeed.
