### ISSUE TITLE
Can a TA jump to normal world code ?

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#2588]
Lets say I have a memory region in non-secure world where I know a function exists and I give the address of the start of this function (say 0x1000) and function code size (say 100) to secure world. My question is whether secure world can (at run time) mark the memory region from 0x1000 to size 100 as secure, and then jump to that code ?

**Comment by jenswi-linaro** [comment]
The short answer is no.

**Comment by a2t2** [comment]
Is the 'no' because memory cannot be claimed at run time ? Can you provide some explanation if possible ? Thanks

**Comment by jenswi-linaro** [comment]
You can't just make some memory secure, lots of problems with caches etc. On a certain platform it may be possible but not in general. Also how do you know that the function is secure to execute?

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
