### ISSUE TITLE
Printing current time

### ISSUE THREAD

**Issue by PedroRibeiro95** [OP-TEE/optee_os#2589]
Hello, I'm trying to benchmark some functions I've written on a TA and I'm using the Time API to do so, with build/QEMU. I'm doing as described on https://github.com/OP-TEE/optee_os/issues/1758, and testing by using the following code:

```c
TEE_Time time1, time2, result;
TEE_GetSystemTime(&time1);
TEE_Wait(2000);
TEE_GetSystemTime(&time2);

TEE_TIME_SUB(time2, time1, result);

IMSG("TIME: %lu\n", (result.seconds / 1000) + result.millis);
```

The expected result should be that 2000 ms have passed between the first TEE_GetSystemTime and the second. However, the result printed is 95, which keeps incrementing everytime I try to run this code.

What am I doing wrong? Thank you.

**Comment by lorc** [comment]
I believe you want to multiply seconds by 1000, instead of dividing.

**Comment by PedroRibeiro95** [comment]
This is a case to say that the devil is in the details. Thank you very much @lorc.

**Comment by PedroRibeiro95** [comment]
This is a case to say that the devil is in the details. Thank you very much @lorc.
