### ISSUE TITLE
Secure Storage Protection

### ISSUE THREAD

**Issue by PedroRibeiro95** [OP-TEE/optee_os#2592]
Hello,

I'm writing my thesis and I need to explain how the persistent secure objects are stored in /data/tee. The goal of the system I implemented is to protect against rollback attacks.
https://github.com/OP-TEE/optee_os/blob/master/documentation/secure_storage.md cites the Global Platform's specification: "The Trusted Storage must provide a minimum level of protection against rollback attacks".

Could someone explain how OP-TEE implements this rollback protection? Thank you!

**Comment by jforissier** [comment]
Hi @PedroRibeiro95,

To benefit from rollback protection, OP-TEE has to be compiled with CFG_RPMB_FS=y. When it is the case, then both the RPMB-backed filesystem (TEE_STORAGE_PRIVATE_RPMB in the API) and the normal world filesystem (TEE_STORAGE_PRIVATE_REE) will benefit from rollback protection. For RPMB FS, it is obvious. As for the REE-backed FS, it automatically uses the RPMB FS when available to store the hash of the whole data store (using a Merkle tree more or less). As a result, if normal world tampers with the data, it will be detected.

**Comment by jenswi-linaro** [comment]
There's also a presentation at http://connect.linaro.org.s3.amazonaws.com/sfo17/Presentations/SFO17-309%20Secure%20storage%20updates.pdf

**Comment by PedroRibeiro95** [comment]
Thank you very much to the both of you. I'll close the issue now.

**Comment by bzhu5** [comment]
also, see this: https://lsseu2018.sched.com/event/G3LG
and this: https://android.googlesource.com/trusty/app/storage/
