### ISSUE TITLE
booting optee_os on rockchip rk3288 board

### ISSUE THREAD

**Issue by mysticTot** [OP-TEE/optee_os#2593]
Hi,
I'm trying to port optee os on rockchip rk3288 board. I've adopted rockchip rk322xx platform to support my board by using [this patch](https://patchwork.amarulasolutions.com/patch/7/).
when I try to boot optee os from u-boot command line I get **OPTEE verification error**. 
Usual boot flow for my board is:
`brom -> tpl -> spl -> u-boot-proper -> linux`

My u-boot configs includes:
```
CONFIG_OPTEE=y
CONFIG_OPTEE_LOAD_ADDR=0x04000000
CONFIG_BOOTM_OPTEE=y
```
and build uTee.optee image using
`./tools/mkimage -A arm -T kernel -O tee -C none -d ~/optee_os/optee.bin uTee.optee`

Here are my u-boot logs:
```=> ext4load mmc 1:1 0x04000000  uTee.optee
233792 bytes read in 14 ms (15.9 MiB/s)
=> bootm 0x04000000 
## Booting kernel from Legacy Image at 04000000 ...
   Image Name:   
   Image Type:   ARM Trusted Execution Environment Kernel Image (uncompressed)
   Data Size:    233728 Bytes = 228.3 KiB
   Load Address: f101fff7
   Entry Point:  f1020013
   Verifying Checksum ... OK
   Loading Kernel Image ... OK
OPTEE verification error:
        hdr=04000040 image=0x04000040 magic=0xe3a05702 tzdram 0x9d000000-0xa0000000 
        header lo=0xf1020013 hi=0xe1a07001 size=0x00039100 arch=0x00000040
        uimage params 0xf101fff7-0xf10590f7
subcommand not supported
exit not allowed from main input shell.
```
What am I doing wrong here. Please let me know
 @MrVan @jforissier @jenswi-linaro @igoropaniuk @etienne-lms

**Comment by mysticTot** [comment]
Hi,
I'm trying to port optee os on rockchip rk3288 board. I've adopted rockchip rk322xx platform to support my board by using [this patch](https://patchwork.amarulasolutions.com/patch/7/).

Rockchip RK3288  is ARM Cortex™-A17 Quad-core 1.6GHz board.

when I try to boot optee os from u-boot command line I get **OPTEE verification error**. 
Usual boot flow for my board is:
`brom -> tpl -> spl -> u-boot-proper -> linux`

My u-boot configs includes:
```
CONFIG_OPTEE=y
CONFIG_OPTEE_LOAD_ADDR=0x00008000
CONFIG_OPTEE_TZDRAM_SIZE=0x0200000
CONFIG_OPTEE_TZDRAM_BASE=0x00008000
CONFIG_BOOTM_OPTEE=y
```
Here are complete steps which I performed:
``` 
#optee build
$ make CFG_TEE_CORE_LOG_LEVEL=4 DEBUG=y CFG_NS_ENTRY_ADDR=0x02000000 CFG_PAGEABLE_ADDR=0 CFD_DT=y CFG_DT_ADDR=0x01f00000 PLATFORM=rockchip PLATFORM_FLAVOR=rk3288vyasa
$ ${CROSS_COMPILE}objcopy -O binary out/arm-plat-rockchip/core/tee.elf optee.bin

# u-boot steps
$ make vyasa-rk3288_defconfig
$ make -j4
$ ./tools/mkimage -A arm -T kernel -O tee -C none -d ~/optee_os/optee.bin uTee.optee

# after writing uboot image on sdcard and copying uImage, dtb and uTee.optee on ext4 single partion.
Here are the boot steps which I performed:
Scanning mmc 1:1...
37893 bytes read in 3 ms (12 MiB/s)
=> ext4load mmc 1:1 $kernel_addr_r uImage
8311360 bytes read in 367 ms (21.6 MiB/s)
=> iminfo $kernel_addr_r

## Checking Image at 02000000 ...
   Legacy image found
   Image Name:   Linux-4.17.11
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    8311296 Bytes = 7.9 MiB
   Load Address: 02000000
   Entry Point:  02000000
   Verifying Checksum ... OK
=>                                         

## Checking Image at 02000000 ...
   Legacy image found
   Image Name:   Linux-4.17.11
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    8311296 Bytes = 7.9 MiB
   Load Address: 02000000
   Entry Point:  02000000
   Verifying Checksum ... OK
=> ext4load mmc 1:1 $fdt_addr_r rk3288-vyasa.dtb
37893 bytes read in 6 ms (6 MiB/s)
=> printenv fdt_addr_r 
fdt_addr_r=0x01f00000
=> setenv bootargs 'console=ttyS2,115200n8 root=/dev/mmcblk0p2 rootwait'                    
=> ext4ls mmc 1:1
<DIR>       4096 .
<DIR>       4096 ..
<DIR>      16384 lost+found
<DIR>       4096 bin
<DIR>       4096 boot
<DIR>       4096 dev
<DIR>       4096 etc
<DIR>       4096 home
<DIR>       4096 lib
<DIR>       4096 media
<DIR>       4096 mnt
<DIR>       4096 proc
<DIR>       4096 run
<DIR>       4096 sbin
<DIR>       4096 sys
<SYM>          8 tmp
<DIR>       4096 usr
<DIR>       4096 var
          241984 uTee.optee
         8311360 uImage
           37893 rk3288-vyasa.dtb
=> ext4load mmc 1:1 0x00008000 uTee.optee 
241984 bytes read in 15 ms (15.4 MiB/s)
=> iminfo 0x00008000                                                    

## Checking Image at 00008000 ...
   Legacy image found
   Image Name:   
   Image Type:   ARM Trusted Execution Environment Kernel Image (uncompressed)
   Data Size:    241920 Bytes = 236.3 KiB
   Load Address: f101fff7
   Entry Point:  f1020013
   Verifying Checksum ... OK
=> bootm 0x00008000  
## Booting kernel from Legacy Image at 00008000 ...
   Image Name:   
   Image Type:   ARM Trusted Execution Environment Kernel Image (uncompressed)
   Data Size:    241920 Bytes = 236.3 KiB
   Load Address: f101fff7
   Entry Point:  f1020013
   Verifying Checksum ... OK
   Loading Kernel Image ... OK
OPTEE verification error:
        hdr=00008040 image=0x00008040 magic=0xe3a05402 tzdram 0x00008000-0x00208000 
        header lo=0xf1020013 hi=0xe1a07001 size=0x0003b100 arch=0x00000040
        uimage params 0xf101fff7-0xf105b0f7
subcommand not supported
exit not allowed from main input shell.
```
I'm not getting any clue about, what could be the issue?
 @MrVan @jforissier @jenswi-linaro @igoropaniuk @etienne-lms

**Comment by jbech-linaro** [comment]
+ @OP-TEE/plat-rockchip who maintains the Rockchip OP-TEE port.

**Comment by mysticTot** [comment]
>     * @OP-TEE/plat-rockchip who maintains the Rockchip OP-TEE port.

Hi @jbech-linaro, 
Thanks alot for your reply.
On MAINTAINERS file it is showing op-tee@rock-chips.com.

**Comment by mysticTot** [comment]
@JosephChen2017 would you please check this issue?

**Comment by jbech-linaro** [comment]
> On MAINTAINERS file it is showing [op-tee@rock-chips.com](mailto:op-tee@rock-chips.com).

That is also correct.

**Comment by mysticTot** [comment]
> Hi,
> I'm trying to port optee os on rockchip rk3288 board. I've adopted rockchip rk322xx platform to support my board by using [this patch](https://patchwork.amarulasolutions.com/patch/7/).
> 
> Rockchip RK3288 is ARM Cortex™-A17 Quad-core 1.6GHz board.
> 
> when I try to boot optee os from u-boot command line I get **OPTEE verification error**.
> Usual boot flow for my board is:
> `brom -> tpl -> spl -> u-boot-proper -> linux`
> 
> My u-boot configs includes:
> 
> ```
> CONFIG_OPTEE=y
> CONFIG_OPTEE_LOAD_ADDR=0x00008000
> CONFIG_OPTEE_TZDRAM_SIZE=0x0200000
> CONFIG_OPTEE_TZDRAM_BASE=0x00008000
> CONFIG_BOOTM_OPTEE=y
> ```
> 
> Here are complete steps which I performed:
> 
> ```
> #optee build
> $ make CFG_TEE_CORE_LOG_LEVEL=4 DEBUG=y CFG_NS_ENTRY_ADDR=0x02000000 CFG_PAGEABLE_ADDR=0 CFD_DT=y CFG_DT_ADDR=0x01f00000 PLATFORM=rockchip PLATFORM_FLAVOR=rk3288vyasa
> $ ${CROSS_COMPILE}objcopy -O binary out/arm-plat-rockchip/core/tee.elf optee.bin
> 
> # u-boot steps
> $ make vyasa-rk3288_defconfig
> $ make -j4
> $ ./tools/mkimage -A arm -T kernel -O tee -C none -d ~/optee_os/optee.bin uTee.optee
> 
> # after writing uboot image on sdcard and copying uImage, dtb and uTee.optee on ext4 single partion.
> Here are the boot steps which I performed:
> Scanning mmc 1:1...
> 37893 bytes read in 3 ms (12 MiB/s)
> => ext4load mmc 1:1 $kernel_addr_r uImage
> 8311360 bytes read in 367 ms (21.6 MiB/s)
> => iminfo $kernel_addr_r
> 
> ## Checking Image at 02000000 ...
>    Legacy image found
>    Image Name:   Linux-4.17.11
>    Image Type:   ARM Linux Kernel Image (uncompressed)
>    Data Size:    8311296 Bytes = 7.9 MiB
>    Load Address: 02000000
>    Entry Point:  02000000
>    Verifying Checksum ... OK
> =>                                         
> 
> ## Checking Image at 02000000 ...
>    Legacy image found
>    Image Name:   Linux-4.17.11
>    Image Type:   ARM Linux Kernel Image (uncompressed)
>    Data Size:    8311296 Bytes = 7.9 MiB
>    Load Address: 02000000
>    Entry Point:  02000000
>    Verifying Checksum ... OK
> => ext4load mmc 1:1 $fdt_addr_r rk3288-vyasa.dtb
> 37893 bytes read in 6 ms (6 MiB/s)
> => printenv fdt_addr_r 
> fdt_addr_r=0x01f00000
> => setenv bootargs 'console=ttyS2,115200n8 root=/dev/mmcblk0p2 rootwait'                    
> => ext4ls mmc 1:1
> <DIR>       4096 .
> <DIR>       4096 ..
> <DIR>      16384 lost+found
> <DIR>       4096 bin
> <DIR>       4096 boot
> <DIR>       4096 dev
> <DIR>       4096 etc
> <DIR>       4096 home
> <DIR>       4096 lib
> <DIR>       4096 media
> <DIR>       4096 mnt
> <DIR>       4096 proc
> <DIR>       4096 run
> <DIR>       4096 sbin
> <DIR>       4096 sys
> <SYM>          8 tmp
> <DIR>       4096 usr
> <DIR>       4096 var
>           241984 uTee.optee
>          8311360 uImage
>            37893 rk3288-vyasa.dtb
> => ext4load mmc 1:1 0x00008000 uTee.optee 
> 241984 bytes read in 15 ms (15.4 MiB/s)
> => iminfo 0x00008000                                                    
> 
> ## Checking Image at 00008000 ...
>    Legacy image found
>    Image Name:   
>    Image Type:   ARM Trusted Execution Environment Kernel Image (uncompressed)
>    Data Size:    241920 Bytes = 236.3 KiB
>    Load Address: f101fff7
>    Entry Point:  f1020013
>    Verifying Checksum ... OK
> => bootm 0x00008000  
> ## Booting kernel from Legacy Image at 00008000 ...
>    Image Name:   
>    Image Type:   ARM Trusted Execution Environment Kernel Image (uncompressed)
>    Data Size:    241920 Bytes = 236.3 KiB
>    Load Address: f101fff7
>    Entry Point:  f1020013
>    Verifying Checksum ... OK
>    Loading Kernel Image ... OK
> OPTEE verification error:
>         hdr=00008040 image=0x00008040 magic=0xe3a05402 tzdram 0x00008000-0x00208000 
>         header lo=0xf1020013 hi=0xe1a07001 size=0x0003b100 arch=0x00000040
>         uimage params 0xf101fff7-0xf105b0f7
> subcommand not supported
> exit not allowed from main input shell.
> ```
> 
> I'm not getting any clue about, what could be the issue?
> @MrVan @jforissier @jenswi-linaro @igoropaniuk @etienne-lms

Its failing at uboot end because of difference in header parameters
In [optee_verify_image()](http://git.denx.de/?p=u-boot.git;a=blob;f=lib/optee/optee.c;h=db92cd9af293ccf94b7c1aa0d316a0eb6f4501c9;hb=HEAD#l25)

hdr->magic  3818935298 != OPTEE_MAGIC 1163153487
hdr->version 0 != OPTEE_VERSION 1
tee_file_size = 3518002507 and tzdram_len = 2097152 image_len = 241920init_load_addr_hi = 0 and init_load_addr_lo = 48 tzdram_end = 1 tzdram_start = 32832.

Why some of these values [hardcode](http://git.denx.de/?p=u-boot.git;a=blob;f=include/tee/optee.h;h=9446928fd4896de4e728a3940c586e47315cad8f;hb=HEAD#l14) in uboot?

**Comment by bryanodonoghue** [comment]
Hi.

Is your binary loaded @ the right address ?

=> iminfo 0x00008000                                                    

## Checking Image at 00008000 ...
   Legacy image found
   Image Name:   
   Image Type:   ARM Trusted Execution Environment Kernel Image (uncompressed)
   Data Size:    241920 Bytes = 236.3 KiB
   *Load Address: f101fff7*
   *Entry Point:  f1020013*

Shouldn't your binary be loaded up near 0xf101fff7 - not 0x00008000 ?

**Comment by bryanodonoghue** [comment]
@mysticTot 
What is the address range you have reserved for TZDRAM ?

On my board it looks like this
U-Boot 2018.11-rc1-00070-g106db21c91-dirty (Oct 08 2018 - 18:17:54 +0100)

CPU:   Freescale i.MX7S rev1.2 800 MHz (running at 792 MHz)
CPU:   Extended Commercial temperature grade (-20C to 105C) at 49C
Reset cause: POR
Board: WARP7 in secure mode OPTEE DRAM **0x9e000000-0xa0000000**

If I interrogate the uTee.optee binary
~/Development/mbl-u-boot/tools/mkimage -l /run/media/deckard/73c0aaf6-fc7a-4539-8265-f562d8de8e18/development/linaro/mbl-optee_os/uTee.optee 
Image Name:   
Created:      Tue Sep  4 15:16:13 2018
Image Type:   ARM Trusted Execution Environment Kernel Image (uncompressed)
Data Size:    270748 Bytes = 264.40 KiB = 0.26 MiB
**Load Address: 9dffffe4**
**Entry Point:  9e000000**

You should confirm if the address range is **tzdram 0x00008000-0x00208000** or up @ **f101fff7**
It looks to me as if you haven't setup the TZDRAM range in u-boot correctly.

**Comment by mysticTot** [comment]
> @mysticTot
> What is the address range you have reserved for TZDRAM ?
> 
> On my board it looks like this
> U-Boot 2018.11-rc1-00070-g106db21c91-dirty (Oct 08 2018 - 18:17:54 +0100)
> 
> CPU: Freescale i.MX7S rev1.2 800 MHz (running at 792 MHz)
> CPU: Extended Commercial temperature grade (-20C to 105C) at 49C
> Reset cause: POR
> Board: WARP7 in secure mode OPTEE DRAM **0x9e000000-0xa0000000**
> 
> If I interrogate the uTee.optee binary
> ~/Development/mbl-u-boot/tools/mkimage -l /run/media/deckard/73c0aaf6-fc7a-4539-8265-f562d8de8e18/development/linaro/mbl-optee_os/uTee.optee
> Image Name:
> Created: Tue Sep 4 15:16:13 2018
> Image Type: ARM Trusted Execution Environment Kernel Image (uncompressed)
> Data Size: 270748 Bytes = 264.40 KiB = 0.26 MiB
> **Load Address: 9dffffe4**
> **Entry Point: 9e000000**
> 
> You should confirm if the address range is **tzdram 0x00008000-0x00208000** or up @ **f101fff7**

My tzdram range is 0x00008000-0x00208000. I'm not sure why is it showing up f101fff7.

**Here are my current uboot and optee configs:**
```

/* uboot configs */
CONFIG_OPTEE=y
CONFIG_OPTEE_LOAD_ADDR=0x00008000
CONFIG_OPTEE_TZDRAM_SIZE=0x0200000
CONFIG_OPTEE_TZDRAM_BASE=0x00008000
CONFIG_BOOTM_OPTEE=y

/* optee configs */
#define TEE_RAM_PH_SIZE         TEE_RAM_VA_SIZE
#define TEE_RAM_START           TZDRAM_BASE
#define TEE_RAM_VA_SIZE         (1024 * 1024)
#define TEE_RAM_SIZE            TEE_RAM_VA_SIZE

#define TA_RAM_START            (TEE_RAM_START + TEE_RAM_SIZE)
#define TA_RAM_SIZE             (1024 * 1024)
#define TEE_SHMEM_START         (TA_RAM_START + TA_RAM_SIZE)
#define TEE_SHMEM_SIZE          (1024 * 1024)

/* Location of trusted dram */
#define TZDRAM_BASE             0x00008000
#define TZDRAM_SIZE             (TEE_RAM_SIZE + TA_RAM_SIZE)
#define TEE_LOAD_ADDR           TZDRAM_BASE
```

> It looks to me as if you haven't setup the TZDRAM range in u-boot correctly.

I tried to learn from warp7 configs but i getting more confused
When I see warp7 optee configs they are like this:
**CFG_TZDRAM_START=(0x80000000 - 0x02000000 + 0x20000000)** which is 9E000000
**CFG_TZDRAM_SIZE=0x01e00000** which 30 MB


When I build uboot for  warp7, i found this:
**CONFIG_OPTEE_LOAD_ADDR=0x84000000
CONFIG_OPTEE_TZDRAM_SIZE=0x3000000
CONFIG_OPTEE_TZDRAM_BASE=0x9d000000**

why TZDRAM_BASE is not equal to CFG_TZDRAM_START ?

Am I missing something? please let me know

**Comment by mysticTot** [comment]
> @mysticTot
> 
> Can you run mkimage -l on your uTee.optee binary ?

Hi Bryan,
 

Here is output according to my new  TZDRAM_BASE  0x68400000.
```
./tools/mkimage -l uTEE.op 
Image Name:   
Created:      Fri Oct 12 14:25:22 2018
Image Type:   ARM Trusted Execution Environment Kernel Image (uncompressed)
Data Size:    233756 Bytes = 228.28 KiB = 0.22 MiB
Load Address: 683fffe4
Entry Point:  68400000
``` 
This time it is correct as per the tzram.

It was my mistake , i was using **tee.elf** because i saw it in [this commit ](https://github.com/OP-TEE/optee_os/commit/8c4a5a9a19e87b0b96b6add5e3adc23d877b06ed)8c4a5a9a19e87b0b96b6add5e3
 

Now, I used **~/optee_os/out/arm-plat-rockchip/core/tee.bin** with **mkimage** and now optee starts but hangs.
But uboot problem is fixed now.

Here is complete logs
```
=> ext4load mmc 1:1 $kernel_addr_r uImage
8311360 bytes read in 368 ms (21.5 MiB/s)
=> ext4load mmc 1:1 $fdt_addr_r rk3288-vyasa.dtb
37893 bytes read in 6 ms (6 MiB/s)
=> setenv bootargs 'console=ttyS2,115200n8 root=/dev/mmcblk0p1 rootwait' 
=> ext4ls mmc 1:1                                                       
<DIR>       4096 .
<DIR>       4096 ..
<DIR>      16384 lost+found
<DIR>       4096 bin
<DIR>       4096 boot
<DIR>       4096 dev
<DIR>       4096 etc
<DIR>       4096 home
<DIR>       4096 lib
<DIR>       4096 media
<DIR>       4096 mnt
          241920 optee.bin
<DIR>       4096 proc
           37893 rk3288-vyasa.dtb
<DIR>       4096 run
<DIR>       4096 sbin
<DIR>       4096 sys
         2992492 tee.elf
<SYM>          8 tmp
         8311360 uImage
<DIR>       4096 usr
          233792 uTee.optee
<DIR>       4096 var
          233820 myTee
=> ext4load mmc 1:1 0x04000000 myTee
233820 bytes read in 14 ms (15.9 MiB/s)
=> iminfo 0x04000000

## Checking Image at 04000000 ...
   Legacy image found
   Image Name:   
   Image Type:   ARM Trusted Execution Environment Kernel Image (uncompressed)
   Data Size:    233756 Bytes = 228.3 KiB
   Load Address: 683fffe4
   Entry Point:  68400000
   Verifying Checksum ... OK
=> bootm 0x04000000 - $fdt_addr_r   
## Booting kernel from Legacy Image at 04000000 ...
   Image Name:   
   Image Type:   ARM Trusted Execution Environment Kernel Image (uncompressed)
   Data Size:    233756 Bytes = 228.3 KiB
   Load Address: 683fffe4
   Entry Point:  68400000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK
hdr->magic = 1163153487 and OPTEE_MAGIC 1163153487
hdr->version = 1 and OPTEE_VERSION 1
tee_file_size = 233756 and tzdram_len = 2097152 image_len = 233756init_load_addr_hi = 0 and init_load_addr_lo = 54 tzdram_
end = 1 tzdram_start = 67108928## Flattened Device Tree blob at 01f00000
   Booting using the fdt blob at 0x1f00000
   Loading Device Tree to 0fff3000, end 0ffff404 ... OK
hdr->magic = 1163153487 and OPTEE_MAGIC 1163153487
hdr->version = 1 and OPTEE_VERSION 1
tee_file_size = 233756 and tzdram_len = 2097152 image_len = 233756init_load_addr_hi = 0 and init_load_addr_lo = 54 tzdram_
end = 1 tzdram_start = 67108928## Flattened Device Tree blob at 01f00000
   Booting using the fdt blob at 0x1f00000

Starting kernel ...

D/TC:0 0 add_phys_mem:539 TEE_SHMEM_START type NSEC_SHM 0x68600000 size 0x00100000
D/TC:0 0 add_phys_mem:539 TA_RAM_START type TA_RAM 0x68500000 size 0x00100000
D/TC:0 0 add_phys_mem:539 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x68431000 size 0x000cf000
D/TC:0 0 add_phys_mem:539 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x68400000 size 0x00031000
D/TC:0 0 add_phys_mem:539 ISRAM_BASE type IO_NSEC 0xff700000 size 0x00100000
D/TC:0 0 add_phys_mem:539 PERIPH_BASE type IO_SEC 0x10100000 size 0x22000000
D/TC:0 0 verify_special_mem_areas:477 No NSEC DDR memory area defined
D/TC:0 0 add_va_space:578 type RES_VASPACE size 0x00a00000
D/TC:0 0 add_va_space:578 type SHM_VASPACE size 0x02000000
D/TC:0 0 dump_mmap_table:711 type TEE_RAM_RX   va 0x68400000..0x68430fff pa 0x68400000..0x68430fff size 0x00031000 (smallp
g)
D/TC:0 0 dump_mmap_table:711 type TEE_RAM_RW   va 0x68431000..0x684fffff pa 0x68431000..0x684fffff size 0x000cf000 (smallp
g)
D/TC:0 0 dump_mmap_table:711 type SHM_VASPACE  va 0x68500000..0x6a4fffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type IO_SEC       va 0x6a500000..0x8c4fffff pa 0x10100000..0x320fffff size 0x22000000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type RES_VASPACE  va 0x8c500000..0x8cefffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type TA_RAM       va 0x8cf00000..0x8cffffff pa 0x68500000..0x685fffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type NSEC_SHM     va 0x8d000000..0x8d0fffff pa 0x68600000..0x686fffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type IO_NSEC      va 0x8d100000..0x8d1fffff pa 0xff700000..0xff7fffff size 0x00100000 (pgdir)
D/TC:0 0 core_mmu_alloc_l2:238 L2 table used: 1/4
```

**Comment by mysticTot** [comment]
By analyzing above logs,  I think I need to do some workaround on  [initial patch].(https://patchwork.amarulasolutions.com/patch/7/)
Uboot problem is solved now. 
So I'm closing this issue.
Thanks a lot @bryanodonoghue and everyone who participated.
