### ISSUE TITLE
I tried to display OS information in tee-svc.c file by using IMSG();

### ISSUE THREAD

**Issue by akbarsaleemt** [OP-TEE/optee_os#2598]
Hi Team,
I tried to display OS information in tee-svc.c file by using IMSG(); it displayed following are they correct or any other way.
OS name OPTEE
I/TC: OS version3.2.0-56-ga06857f9-dev
I/TC: OS manufacturer LINARO

Thankyou

**Comment by jbech-linaro** [comment]
Seems good to me? Do you expect anything else?
