### ISSUE TITLE
Which HMAC standard is TEE_MAC ?

### ISSUE THREAD

**Issue by Rusack** [OP-TEE/optee_os#2599]
I'd like to know which HMAC method is implemented through the TEE_MAC function family ?

**Comment by jbech-linaro** [comment]
It's done like [this](https://github.com/linaro-swg/optee_examples/blob/master/hotp/ta/hotp_ta.c#L33-L112).

**Comment by Rusack** [comment]
Thank you, I'll check that out

**Comment by jbech-linaro** [comment]
I missed one thing, you said "which" method. My link only points to how to do a HMAC SHA1. But if you open up the [GlobalPlatform Internal Core API specification](https://globalplatform.org/specs-library/?filter-committee=tee), you'll see all the available combinations. But it's the usual stuff, SHA1, SHA256 and so on.
