### ISSUE TITLE
Secure storage for Pseudo TA

### ISSUE THREAD

**Issue by kdy1029** [OP-TEE/optee_os#2600]
Hello,

I need secure storage for PTA, but OP-TEE core does not link with libutee.
Is there any way to save and load some files for PTA?

Thanks

**Comment by jenswi-linaro** [comment]
Yes, but you'll need to be very careful not to shoot yourself in the foot. There's a example of using secure storage in `core/tee/tadb.c`, start looking in `tadb_open()`.
