### ISSUE TITLE
map physical address to virtual address

### ISSUE THREAD

**Issue by yilingxu** [OP-TEE/optee_os#2601]
Background:
I want to use tee_hash_createdigest() function to verify my rootfs (initrd.gz). My rootfs is about 100M. To do this, I first need to change the physical address of rootfs to virtual address.

Question:
I use core_mmu_add_mapping() and phys_to_virt() to map physical address to virtual address. But the mapping failed. It seems my rootfs is too big and there are not enough reserved virtual space used for mapping.

I can split  rootfs into several parts, and calculate hash value of each part. But how can I reuse the virtual space(for example, when I calculate the hash value of second part, how can I reuse the virtual space of first part), and what's the size of virtual address?

Thanks a lot.

Yiling Xu

**Comment by yilingxu** [comment]
> In which environment are you trying this? Given that the rootfs is needed to boot the Linux kernel I suspect that we're talking about a boot loader, do you have more details?

I try this on optee_os, in secure world. Before boot linux kernel, I want to calculate the hash value of linux kernel and rootfs.

**Comment by jenswi-linaro** [comment]
OP-TEE isn't designed to be used in that way, it's not a boot loader. Why not calculate the hash in the boot loader instead and then ask OP-TEE to check that the hash matches some expected value. I assume that there's some secure storage which only OP-TEE can access and that's why OP-TEE is involved at all.

**Comment by yilingxu** [comment]
> OP-TEE isn't designed to be used in that way, it's not a boot loader. Why not calculate the hash in the boot loader instead and then ask OP-TEE to check that the hash matches some expected value. I assume that there's some secure storage which only OP-TEE can access and that's why OP-TEE is involved at all.

I want to do trust boot. The hash value should be stored in secure storage, and used for remote attestation after system boot up. If I calculate the hash in the boot loader, how can I store the hash value in secure storage, do you have any suggestion?

**Comment by jenswi-linaro** [comment]
I'm sorry, I can't help you with that.

**Comment by yilingxu** [comment]
> I'm sorry, I can't help you with that.

Ok, thanks, I will reconsider my design.

**Comment by jforissier** [comment]
Isn't this similar to the AVB use case in U-Boot?

**Comment by yilingxu** [comment]
> Isn't this similar to the AVB use case in U-Boot?

I'm working on Imx6q. Could you please give more details about AVB case?

**Comment by igoropaniuk** [comment]
@yilingxu 

Just a bit of links:
https://android.googlesource.com/platform/external/avb/+/master/README.md
https://connect.linaro.org/resources/hkg18/hkg18-124/
https://patchwork.ozlabs.org/cover/924738/ 
https://patchwork.ozlabs.org/cover/974462/

**Comment by yilingxu** [comment]
Hi,

I want to turn back to my original problem. I use core_mmu_add_mapping(MEM_AREA_RAM_NSEC, pa_entry, len) and phys_to_virt(pa_entry, MEM_AREA_RAM_NSEC) to translate the physical address to virtual address. The reserved virtual space can be used up since CFG_RESERVED_VASPACE_SIZE is define as 10M. When I don't need this mapping anymore, can I cancel the mapping for later use(just like malloc() and free() in C)?

Thanks,
Yiling Xu

**Comment by yilingxu** [comment]
Can  core_mmu_add_mapping() work with core_mmu_unmap_pages()? Or only core_mmu_map_pages() work with core_mmu_unmap_pages()? @jenswi-linaro

**Comment by jenswi-linaro** [comment]
>1.

core_mmu_unmap_pages() only works with core_mmu_map_pages(), and then only with certain memory types. You can check core_mmu_unmap_pages() yourself for which.

>2.

You can't unmap static region, you'll need to establish the temporary mapping with some other memory type.

**Comment by yilingxu** [comment]
I will close this issue because my original problem has been solved.

Thank you for all your help and replies!
