### ISSUE TITLE
Kernel space OP-TEE Client API

### ISSUE THREAD

**Issue by janek202** [OP-TEE/optee_os#2608]
Hello,

Are there any news, plans on kernel space Client API?

We have a client which needs key management in Trusted Application, which interacts with a UFS storage controller. When required, it would write some hardware registers accessible only from Secure World.

The controller needs to have its crypto keys rewritten after each wake up from suspend.
We can use the runtime pm framework in the kernel to get a callback when such event occurs.
But without an OP-TEE client in a kernel, we can’t access the Trusted App.

User space doesn’t seem to have a clean way to have a signal when wakeup happens, and it doesn’t prevent the system from accessing the storage before the keys are programmed.

Or maybe there is another way, we can handle it without a kernel space API?

Thanks,
Janek

**Comment by jbech-linaro** [comment]
We are waiting for people who are willing to a) review the patch b) saying that they are in need of or want to use something like this. So please, chime on on the patch-set.

https://patchwork.kernel.org/patch/10513611/

**Comment by Emantor** [comment]
The Internal TEE API is queue for 4.20 and already in [linux-next](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/tee?id=25559c22cef879c5cf7119540bfe21fb379d29f3).

**Comment by jbech-linaro** [comment]
> The Internal TEE API is queue for 4.20 and already in [linux-next](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/tee?id=25559c22cef879c5cf7119540bfe21fb379d29f3).

Uh, I've totally missed that, I should have known about it, thanks @Emantor !

**Comment by janek202** [comment]
That's great to hear! Thanks, looking forward to 4.20.
