### ISSUE TITLE
"core_mmu_alloc_l2" support for multiple L2 tables for small pages

### ISSUE THREAD

**Issue by paswan-ms** [OP-TEE/optee_os#261]
Hi,
We're working on an implementation for PSCI and have encountered a limitation in the implementation for this function. The use of the static "l2_offs" prevents more than one L2 allocation. The second call returns NULL which causes a fail later in OP-TEE. The library implementation requires 2 memory regions: 
1. Coherent Memory - configured as secure, device, size = 16KB 
2. Secure Monitor Stack Memory - configured as secure, normal, cached, size = 16KB
We have a work around for the limitation but it wastes megabytes of memory (because we need to keep things 1Meg aligned). Is there an existing recommended approach for handling this scenario?
Thanks,
Paul.

**Comment by jenswi-linaro** [comment]
Hi Paul,

I would have tried configuring with LPAE instead. I'm not 100% sure but I think it will work as expected. Another option is to fix `core_mmu_alloc_l2()` :-)

Regards,
Jens

**Comment by paswan-ms** [comment]
Thanks for the feedback, I've passed it along.
