### ISSUE TITLE
Extending QEMU OPTEE_Client

### ISSUE THREAD

**Issue by jiwonjoung** [OP-TEE/optee_os#2617]
I would like to tell QEMU  to build with gpsd (GPS daemon) so that when the NW boots, the gpsd file tree is accessible and available. How do you extend the OS_Client like this?

**Comment by jforissier** [comment]
Have you checked the buildroot configuration files? There is a flag: `BR2_PACKAGE_GPSD` etc., perhaps it's what you are looking for?

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.

**Comment by jiwonjoung** [comment]
This is not what I am looking for -- I am looking to incorporate my custom version of gpsd. So the more general question might be, how do I incorporate an existing complex application into the file system of OPTEE?
