### ISSUE TITLE
Why MEM_AREA_IO_(N)SEC is rounded up to CORE_MMU_PGDIR_SIZE?

### ISSUE THREAD

**Issue by rshanmu** [OP-TEE/optee_os#2620]
In init_mem_map(), if the core_mmu_phys_mem attribute is MEM_AREA_IO_NSEC/SEC, it is rounded up to CORE_MMU_PGDIR_SIZE. On ARMv8 with LPAE, this is 2MB region.

```
                if (m.type == MEM_AREA_IO_NSEC || m.type == MEM_AREA_IO_SEC) {
                        m.addr = ROUNDDOWN(m.addr, CORE_MMU_PGDIR_SIZE);
                        m.size = ROUNDUP(m.size + (mem->addr - m.addr),
                                         CORE_MMU_PGDIR_SIZE);
                }
```
Any reason why this is done? Reduce translation table size?

The second part of the question is, how is MEM_AREA_IO_NSEC and MEM_AREA_IO_SEC attributes are different when defining a IO region in OP-TEE MMU? Yes, the SECURE attribute is set for the later but these are IO regions (un-cached) visible/accessible from OP-TEE's address space.  What is the benefit of setting  it as SEC or NSEC?

This region's ROUNDDOWN(base) and ROUNDUP(size) most likely leads to defining a bigger region than the peripheral address space one intends to access. Hence, I want to understand this attribute's purpose.

Thanks in advance.

**Comment by jenswi-linaro** [comment]
> Any reason why this is done? Reduce translation table size?
Yes

MEM_AREA_IO_NSEC vs MEM_AREA_IO_SEC:
There's several issues to keep in mind here and I'm probably missing some. The secure and non-secure physical address spaces can in theory be separated, meaning that the same physical address can be hooked up to something different depending on the ns-bit. There's the visibility of the changes done at an address, even uncached accesses requires appropriate setup to get expected visibility (of ordering etc) on different cores.

**Comment by rshanmu** [comment]
Thanks for the clarifications.

> The secure and non-secure physical address spaces can in theory be separated, meaning that the same physical address can be hooked up to something different depending on the ns-bit.

OK. It makes sense.

> There's the visibility of the changes done at an address, even uncached accesses requires appropriate setup to get expected visibility (of ordering etc) on different cores.

As of today, only the NS-bit seems to be the difference between MEM_AREA_IO_SEC & NSEC regions. Rest of the attributes remains the same for both regions. 

As these MEM_AREA_IO_XXX regions are defined in platform_config.h (and if the physical IO address spaces are different on that platform), would it makes sense to club the IO region under either NSEC or SEC? It would reduce the table size. Is there are compelling justification to not to do this?

**Comment by jenswi-linaro** [comment]
The savings will not be that great, at most only a few entries in an already allocated page table.

Since it's the platform config that decides how the mapping is done it doesn't affect generic code. I'm not convinced it's a very good idea to make all device mappings secure. These things has a tendency to be more complicated than they look on the surface.

My concern is that the same device mapped region may potentially be accessed as both secure and non-secure at the same time since Normal world obviously has the region mapped as non-secure.

You probably need to check with Arm directly to get a straight answer on this.

**Comment by rshanmu** [comment]
Thanks for the inputs. I shall close this ticket.
