### ISSUE TITLE
Write data to Secure World

### ISSUE THREAD

**Issue by tesmnorth** [OP-TEE/optee_os#2621]
Hello,

I have signed message and I want to save this data to Secure World. 

I tried "`TEE_AllocateTransientObject(TEE_TYPE_DATA, sizeof(message), &transientMessage`)"
Then, It returns "`TEE_ERROR_NOT_SUPPORTED`" 

It is not possible to save any data to Secure side?

**Comment by jbech-linaro** [comment]
Hi @tesmnorth , please run and study the "Secure Storage" example [here](https://github.com/linaro-swg/optee_examples) and I'm sure you will figure out how to store data using secure storage from a Trusted Application.

**Comment by tesmnorth** [comment]
Thanks @jbech-linaro. I dont need to use TEE_AllocateTransientObject. It is done.
