### ISSUE TITLE
Short question: How to download FVP_Base AEMv8A-AEMv8A?

### ISSUE THREAD

**Issue by duduscript** [OP-TEE/optee_os#2626]
Hi all, I have view this website https://developer.arm.com/products/system-design/fixed-virtual-platforms many times, but I can not find a link to download or buy FVP_Base AEMv8A-AEMv8A?

**Comment by jbech-linaro** [comment]
@duduscript , on the URL you gave it says:
```
Download FVPs
To download FVPs you’ll need to log in to Arm Self Service and if you do not have an account you can register for one here. For reference you can also view the FVP End User Licence Agreement.
```
If I login as said there, then I see it as the first link (here is the direct link: https://silver.arm.com/browse/FE000-KT-00001).

**Comment by jforissier** [comment]
AFAIK, only the Foundation Model can be downloaded for free. Other Base Platforms may be evaluated then need a license.

**Comment by duduscript** [comment]
Hi @jbech-linaro, I download this package successfully and run setup script as manual, but I can not find model binary file in the directory it generated like Foundation Model or other packages.

**Comment by duduscript** [comment]
Hi @jforissier, it seems that I can not buy fvp online in my region, thank you.

**Comment by jforissier** [comment]
Hi @duduscript,

Sorry I don't know. Perhaps you should contact Arm directly.

**Comment by jbech-linaro** [comment]
Hi, I checked this a bit more and I think they've changed the name of the package and binaries. On @duduscript URL if you scroll down to `Armv8 Architecture FVPs`, then you will have a couple of different download links. I tried both of them who are **not** `M`-device. When running it, it looks like the same old FVP that we use to run, but the name of the binary etc have changed. So I believe that we need to update our [fvp.mk](https://github.com/OP-TEE/build/blob/master/fvp.mk#L188-L198) in build.git to reflect the new changes.

**Comment by jbech-linaro** [comment]
Actually, `FM000-KT-00035-r11p4-37rel0.tgz` on https://silver.arm.com/download/download.tm?pv=4436043&p=1238185 is the good old Foundation Platform. I tried our FVP setup with that and it works fine.

**Comment by duduscript** [comment]
This package works fine, thank you @jbech-linaro.
But I am a little confused by the name of fvp package. What is the difference between Armv8-A Base Platform FVP and Armv8-A Foundation Platform?

**Comment by duduscript** [comment]
Get it,  thank you @jenswi-linaro
