### ISSUE TITLE
How are Trusted Applications verified

### ISSUE THREAD

**Issue by akbarsaleemt** [OP-TEE/optee_os#2629]
Hi team,
    In optee_os/keys/ we have a key file how that key added to application and how it will verified. is there any flow for it for verifying application.

**Comment by jbech-linaro** [comment]
I have a pending pull request (#2043 since many months back) that might explains this, see [here](https://github.com/OP-TEE/optee_os/blob/d0a4cf89856eaec0618f14168ceb6fc335e2d3b0/documentation/optee_design.md#signature-verification-of-bootstrap-trusted-applications).
