### ISSUE TITLE
How to customize the rootfs when build optee all?

### ISSUE THREAD

**Issue by gutouyu** [OP-TEE/optee_os#2632]
I have built the optee software following instructions in `OPTEE/build`.  If I'm right, we are using buildroot to build the rootfs. But the default config only contains the smallest rootfs which doesn't have `apt gcc g++ python sudo dpkg`.

So my question is how to customize my rootfs if I want to use these softwares in the os-system(let's say python and gcc/g++, for example). Am I only supposed to modify `.config` in `out-br` directory? It seems to be the config-file for buildroot to use. But I can't confirm it is, any help will be much appreciated. 

The makefile is too complicated and I have lost in there. 🤣

**Comment by jbech-linaro** [comment]
Easiest is to simply add a new BR2_PACKAGE_  line you are going to use ....  like done for strace here:
https://github.com/OP-TEE/build/blob/master/common.mk#L228.

If you do that, re-run `make`, then buildroot will pick that up, download, compile and include that automatically for you.

**Comment by jforissier** [comment]
+1, and the final configuration file is in `out-br/.config`.

**Comment by gutouyu** [comment]
Wow! It works. I have successfully got python run. Thanks very much for replying me so patiently and quickly . I still have some confusions, looking forward to hear from you. 😆 
1. How to enable `apt-get`  I don't find it. (If I can use it, I can install libraries myself in the internal-os)
2. How to enable something that isn't in the configure scope, such as `pip` and I don't find the flag `BR2_PACKAGE_PIP`. 
3. If I want to compile some c-files in the compiled-os, do I need the `BR2_GCC_xxx` or `BR2_TOOLCHAIN_EXTERNAL_GCC_8`, what is the second  used for, it's set to by `y`? But I don't find something cross-compiler `arm-linux-xxx` in the compiled-os. And I think I only need gcc in the compiled-os, right?
4. What if I need some other version of gcc, because there is only 4.x version in the configure file?

Sorry for so many questions, just doing some projects with my graduate-classmates and we found you guys really have done an awesome work.  🚀

**Comment by SaraAdamTh** [comment]
@jbech-linaro I need to compile files on the built OS and tried adding BR2_PACKAGE_ GCC to the common.mk file but it didn't work. Is that possible? Do I need to any other configuration? I have read in builtroot documentation the it doesn't support compiling on target system https://buildroot.org/downloads/manual/manual.pdf#section.10.2
@gutouyu have you managed to add GCC package to the target OS ?

**Comment by jbech-linaro** [comment]
> @SaraAdamTh I have read in builtroot documentation that it doesn't support compiling on target system https://buildroot.org/downloads/manual/manual.pdf#section.10.2

Interesting, I didn't know that, I always use the cross compiler on my regular PC and move file to the root-fs when necessary. At least it's possible to run gdb on the device.

**Comment by gutouyu** [comment]
Thanks , Move on this project, just close this issue.

**Comment by DimJ** [comment]
@gutouyu  can you share your solution (about adding Python/GCC)?

Thanks in advance.
