### ISSUE TITLE
Is it possible to compile CA to some *.so files instead of an executable binary file?

### ISSUE THREAD

**Issue by gutouyu** [OP-TEE/optee_os#2633]
In optee_examples all CA examples do have a `main` func in `main.c`, and we build it to an executable binary file , then copy to the compiled-os(using buildroot).

Can I change the main.c file and `main` func, and compile it to some *.so library? I just want to load the  *.so file using python, and using python to call CA func which will call the TA func. 

If it can be done, what do I need to do specifically? Just change the CMakeLists.txt to output *.so file, right？(I have install python in the rootfs).  Any suggestions will be much appreciated. Thanks a lot.

**Comment by jenswi-linaro** [comment]
That can be done, the changes to CMakeLists.txt etc I leave to you to figure out.

**Comment by gutouyu** [comment]
> That can be done, the changes to CMakeLists.txt etc I leave to you to figure out.

Thanks a lot. I just change the CMakeLists.txt and it works.
