### ISSUE TITLE
OP-TEE trace levels

### ISSUE THREAD

**Issue by omihalac** [OP-TEE/optee_os#2635]
We were facing a problem when we tried to run optee_test suite having all logs disabled `CFG_TEE_TA_LOG_LEVEL=0`. It has to be said that this problem is reproducible with OP-TEE [v3.1.0](https://github.com/OP-TEE/optee_os/tree/3.1.0)  and is related to a special trace log implementation through `PB()`, `INMSG()` and `OUTMSG()` macros from `lib/libutee/tee_user_mem.c` file that didn’t exist anymore in more recent OP-TEE versions, responsible for that being the commit f6eaffba6b (“libutee: remove redundant malloc() layers”).

The root cause of the issue could be related to a wrong way of processing the log levels. The trace level is set through `trace_set_level()` with the input value `level` only in case it is placed within the min and max admitted values, when `TRACE_MIN=1` and `TRACE_MAX=4`, having `TRACE_MAX` otherwise. The situation we are investigating has `level=0` which is outside of normal usage case and makes the session to be initialized with maximum trace flow level (`TRACE_MAX=4`).

```
void trace_set_level(int level)
{
        if (((int)level >= TRACE_MIN) && (level <= TRACE_MAX))
                trace_level = level;
        else
                trace_level = TRACE_MAX;
}
```
Once global `trace_level` gets initialized with flow state (4), we got a lot of memory allocation traces all those coming from special macros listed above.

Now comes the question why OP-TEE doesn’t consider logs disabled state (`CFG_TEE_TA_LOG_LEVEL=0`) as inferior boundary, `TRACE_MIN` should be 0 instead. Once we set the `TRACE_MIN=0` (in ` trace_levels.h`) we get the expected behavior with all TA logs being disabled.

Is it there something that we might missed behind the decision to have `TRACE_MIN` initialized at error level (1) instead of being set to 0?

**Comment by jbech-linaro** [comment]
> @omihalac Now comes the question why OP-TEE doesn’t consider logs disabled state (`CFG_TEE_TA_LOG_LEVEL=0`) as inferior boundary, `TRACE_MIN` should be 0 instead. Once we set the `TRACE_MIN=0` (in ` trace_levels.h`) we get the expected behavior with all TA logs being disabled.

I have no good answer why it is like it is (probably because no-one never asked for total silence from OP-TEE), but I wouldn't mind having the ability to completely being able to remove all prints. If you have patches ready for this, please create a pull request.

**Comment by omihalac** [comment]
@jbech-linaro 
@cgellner

Thank you for your fast response. I proposed solution in [PR#2636](https://github.com/OP-TEE/optee_os/pull/2636) and hopefully everything would be alright. Looking forward to your feedback.
