### ISSUE TITLE
RSA key generation time

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#2637]
I  run OP-TEE on an i.mx6q platform, and find that it requires about 25 seconds to generate a 2048-bits RSA key. But it only requires about 6 seconds in Linux on the same platform.  What's the reason for OP-TEE to require so much time to generate a RSA key? Is it because that the random generator of OP-TEE is much slower?

**Comment by jforissier** [comment]
I don't know. It is not a platform-specific problem, because observe a similar behavior on HiKey960: `ssh-keygen` takes less than one second while `xtest 4007` (the 2048-bit RSA key generation subcase only) needs about 6 seconds.

**Comment by jenswi-linaro** [comment]
It's on my todo list to find the answer to this. However, I haven't started on that yet.

**Comment by jforissier** [comment]
@jenswi-linaro I would bet on the poor performance of the primality tests in libmpa. It's good that you happen to be working on using the mbedtls bignum implementation, with a bit of luck it will work much better :)

**Comment by jbech-linaro** [comment]
> @jforissier @jenswi-linaro I would bet on the poor performance of the primality tests in libmpa.

Pretty much what I concluded in [my investigation](https://projects.linaro.org/browse/SWG-347?focusedCommentId=62905&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-62905) (URL not accessible by non-Linaro folks).

**Comment by jforissier** [comment]
@TEE-OS please try again now that @jenswi-linaro's mbedtls patches have been merged (#2649). They make key generation 5-6 times faster for me (HiKey960) :)

**Comment by TEE-OS** [comment]
@jforissier Sorry for the late response. Yes, it is greatly improved now. Thanks a lot.
