### ISSUE TITLE
Non-secure/Secure OS Scheduling

### ISSUE THREAD

**Issue by anwaymukherjee** [OP-TEE/optee_os#2639]
After having gone through https://github.com/OP-TEE/optee_os/issues/1183, https://github.com/OP-TEE/optee_os/issues/1724 and https://github.com/OP-TEE/optee_os/issues/2168 , I have a couple of queries.

Lets say client application (A) has the typical open_context->open_session->invoke_func->close_session->close_context flow. Linux OS schedules A as a CFS thread.

What I have understood: Thread A calls smc, which gets mapped to a thread context in OP-TEE core and then TA loading and execution happens in the same context.

Q1. Does each step of open_context, open_session and invoke_func have separate TEE context, i.e., separate secure thread assignment (OP-TEE core) ? 

Q2. Does thread A spawn a new thread each time it encounters OP-TEE specific APIs ? From my understanding of linux tee driver, thread A (client application) is the only "context". OP-TEE core side private "thread context" and/or "TA context" are part of the same thread A

Q3. If thread A was CFS scheduled, would the TA execution (and open_context, open_session) code execution be also CFS scheduled?

Note: I seem to understand the TEE context and TA context from the discussion. Also, thread and process have been used interchangeably wrt Linux scheduler. Let me know if there is a issue with my understanding.

Expert inputs are always welcome.

**Comment by jenswi-linaro** [comment]
> Q1. Does each step of open_context, open_session and invoke_func have separate TEE context, i.e., separate secure thread assignment (OP-TEE core) ?

A thread in OP-TEE is acquired and held while processing a standard (yielding) call, for instance open_session or invoke_func. However, between those calls the thread is released and can be used by other requests.

> Q2. Does thread A spawn a new thread each time it encounters OP-TEE specific APIs ? From my understanding of linux tee driver, thread A (client application) is the only "context". OP-TEE core side private "thread context" and/or "TA context" are part of the same thread A

No threads are spawned in the driver. On the secure side in OP-TEE they are either used or free to be reused.

> Q3. If thread A was CFS scheduled, would the TA execution (and open_context, open_session) code execution be also CFS scheduled?

Yes, but there are mutexes which can cause priority inversion.

**Comment by anwaymukherjee** [comment]
Thank you so much @jenswi-linaro for the clarification. That was extremely helpful. I have one small follow-up Q wrt mutex. I am going to pen down my understanding on this. Let me know if I am on the right track.

I believe each service (the OP-TEE side) called for by the client side is wrapped within mutex borrowed from the generic pthread library. However, since the services mimic worker threads (wait queues) which are run as FIFO, I thought the mutex functions as barriers (albeit 1 thread context per barrier). 

I guess I don't quite understand the possibility of priority inversion arising from this. 

A) Do you mean in the non-secure side? In that case too, I think preemption during TEE execution is allowed in OP-TEE.

B) Do you mean separate OP-TEE services from 2 separate processes (CAs) gets interleaved and queued in waitQ (and gets to go FIFO) ?

A simple example execution would be much helpful.

**Comment by jenswi-linaro** [comment]
There's critical sections in OP-TEE (secure side) that are protected by mutexes. If a mutex is locked when a thread (T2) is trying to lock it there will be an RPC to normal world to wait for the mutex to become availble. Once the mutex is unlocked (by T1) there will be an RPC to normal world waking up the sleeping thread.

**Comment by anwaymukherjee** [comment]
Interesting information. Thank you for the prompt reply. Much help. 
I will need to go through it to understand it more.  If you don't mind, I am closing this thread.
