### ISSUE TITLE
Setting up a development environment

### ISSUE THREAD

**Issue by sungwoooo** [OP-TEE/optee_os#2640]
Hello,

I'm new to TEE and trying to make develop environment.
I have some questions about developing Trusted Application and TEE OS.

Q1. Regarding ARM Trusted Firmware or Cryptocell, Is there any documents of APIs for crypto functionalities which can be called by TEE OS?

Q2. What evaluation board and debugger should I choose for Q1's development? Hikey or Juno? J-link or Dstream? 
(I'm using DS-5 IDE)

I would appreciate it if anyone could answer my questions.

Thanks

**Comment by jenswi-linaro** [comment]
> Q1. Regarding ARM Trusted Firmware or Cryptocell, Is there any documents of APIs for crypto functionalities which can be called by TEE OS?

None that I'm aware of. You probably need to ask Arm about that.

> Q2. What evaluation board and debugger should I choose for Q1's development? Hikey or Juno? J-link or Dstream?

Depending on what you going to do you can get quite a bit done in QEMU. If you need to use DS-5 I think Foundation/Base model (FVP) or Juno are the best options.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
