### ISSUE TITLE
OPTEE-OS porting issue in mediatek processor

### ISSUE THREAD

**Issue by Sourabhharman** [OP-TEE/optee_os#2642]
Hi experts,
We are porting OPTEE-OS on mediatek MT6735.
It has **quad core A53 CPU**.
We got **ATF v1.0** from vendor. 
We started porting by adding optee dispatcher in the ATF.

So, OPTEE boot part was fine. Primary CPU get initialized and then the CPU handle is returned to ATF.
ATF then boots the kernel image (BL33). 
Now the problem here is, while in kernel we are getting stuck at boot time and getting some message like:

> [   29.021169] <0>-(0)[0:swapper/0]sched: cpu=0, [951569242 -> 1569242] -= min(951569242, 1*[950000000 -> 950000000])
> [   29.021175] <0>-(0)[0:swapper/0]sched: RT throttling inactivated cpu=0
> [   29.981172] <0>-(0)[86:hps_main]sched: cpu=0 rt_time 959424245 <-> runtime [950000000 -> 950000000], exec_task[86:hps_main], prio=2, exec_delta_time[10000770], clock_task[29981157686], exec_start[29971156916]
> [   29.981176] <0>-(0)[86:hps_main]sched: RT throttling activated
> [   30.021168] <0>-(0)[0:swapper/0]sched: cpu=0, [959450245 -> 9450245] -= min(959450245, 1*[950000000 -> 950000000])
> [   30.021174] <0>-(0)[0:swapper/0]sched: RT throttling inactivated cpu=0

It seems something like, CPU resource is not getting freed.

Can someone please help us on this?
Thanks in Advance.

**Comment by jbech-linaro** [comment]
Sorry, I have no good guess what that is about, seems to be unrelated to OP-TEE.

**Comment by jenswi-linaro** [comment]
This quite early in the kernel boot since the other CPUs hasn't been released yet. I suspect that it has something to do with PSCI and the corresponding DT configuration.

Does the kernel boot OK without any changes to the TF-A provided by the vendor?

**Comment by Sourabhharman** [comment]
Hi @jenswi-linaro 
Kernel boot is not OK. Perhaps it doesn't gives any crashes but it is getting stuck somewhere.

Secondary cores are getting initialized after kernel boot:

> D/HC:  generic_boot_cpu_on_handler:876 cpu 1: a0 0x0
> D/HC:  generic_boot_cpu_on_handler:876 cpu 2: a0 0x0
> D/HC:  generic_boot_cpu_on_handler:876 cpu 3: a0 0x0

We have also suspected that it has something to do with PSCI configuration but very hard to find out.

**Comment by jenswi-linaro** [comment]
Assuming that the system was booting OK before you made any changes.

If on the other hand the only changes you've made are in the TF-A dispatcher and the fact that you're loading OP-TEE then probably PSCI config is OK and it's something else that's wrong. Perhaps it's just memory getting overwritten by OP-TEE due to a broken memory configuration inside OP-TEE. I guess you need to try to break down the changes in smaller steps to identify where it goes wrong.

**Comment by moonhjh** [comment]
Hi Sourabhharman:

We are porting OPTEE-OS on mediatek MT6739,but OPTEE-OS can not start.

 I compile optee os,then merge tee-pager.bin with bl31.bin as tee.img，flash tee.img to device，the uart log stay at "BL31: Initializing BL32",  I guess optee os config is incorrect，Can you give me some suggestiones about optee os porting and debugging method on mediatek

**Comment by Sourabhharman** [comment]
Hi moonhjh,
Inside the optee dispatcher of ATF, check the SPSR register configuration properly, like which mode it is selecting SPSR_64 or SPSR_MODE32 as per as your optee configuration.

**Comment by moonhjh** [comment]
1、atf/v1.3/services/spd/opteed/opteed_main.c:
	_opteed_rw = OPTEE_AARCH64;
	opteed_init_optee_ep_state(optee_ep_info,
				opteed_rw,
				optee_ep_info->pc,
				&opteed_sp_context[linear_id]);_

2、optee out/conf.mk
_CFG_ARM64_core=y_

3、optee os compile
cd build
make -f mediatek.mk optee-os

**Comment by moonhjh** [comment]
Hi Sourabhharman:

1、atf/v1.3/services/spd/opteed/opteed_main.c:
opteed_rw = OPTEE_AARCH64;
opteed_init_optee_ep_state(optee_ep_info,
opteed_rw,
optee_ep_info->pc,
&opteed_sp_context[linear_id]);

2、optee out/conf.mk
CFG_ARM64_core=y

3、optee os compile
cd build
make -f mediatek.mk optee-os

I select 64 inside ATF and optee OS
