### ISSUE TITLE
Problem during Sessionstart

### ISSUE THREAD

**Issue by Christian56** [OP-TEE/optee_os#2659]
Hi, 
I'm having trouble to start a session from the CA to an TA. This TA is already called from the kernel which runs fine. However when i  try to access it from the CA i get an error:
`TEEC_Opensession failed with code 0xffff000d origin 0x3`
Based on TEE internal core api this should be a TEEC_ERROR_BUSY error. 
My assumption is that i somehow messed up the Flags for multiple sessions. Currently im using`#define TA_FLAGS (TA_FLAG_SINGLE_INSTANCE | TA_FLAG_INSTANCE_KEEP_ALIVE | TA_FLAG_MULTI_SESSION)`
But i have also remove everything except TA_FLAG_MULTI_SESSION and it didnt help. Any suggestions for a different approach?

**Comment by etienne-lms** [comment]
Looks strange to me.
With `TA_FLAGS=0` (or `TA_FLAGS=TA_FLAG_MULTI_SESSION`, see note below) you shouldn't get a busy state from `TEE_ORIGIN_TEE` (`0x3`). Try back and adding `EMSG()` traces in **tee_ta_manager.c** if possible (`_BUSY` is used at very few places, see `tee_ta_open_session()`).

Note: `TA_FLAG_MULTI_SESSION` without `TA_FLAG_SINGLE_INSTANCE` is meaningless: 
* Single _instance_ TA: TA is is loaded as a unique executable that gets all open session requests and related command invoke/session closure. The number of opened sessions is restricted to 1 unless `TA_FLAG_MULTI_SESSION` is set.
* Multi _instance_ TA: for each open session request a new TA executable is loaded. Each opened session is isolated from one another (yet few common resources as secure storage) => an instance cannot be busy. Unless I missed something...

**Comment by Christian56** [comment]
Hi @etienne-lms, 
thanks for the quick response. I found the error it seems to occur in the function "tee_ta_init_session_with_context"
```
	if (!(ctx->flags & TA_FLAG_MULTI_SESSION) && ctx->ref_count){
		EMSG("The error could appear here: flags %i,TA_FLAG_MULTI_SESSION %i , ref_count %i", ctx->flags, TA_FLAG_MULTI_SESSION, ctx->ref_count);
		return TEE_ERROR_BUSY;
	}
```
Output
```
Prepare E/TC:? 0 tee_ta_init_session_with_context:457 The error could appear here: flags 4,TA_FLAG_MULTI_SESSION 8 , ref_count 1
session D/TC:? 0 tee_ta_open_session:542 init session failed 0xffff000d
with the TA
optee_test: TEEC_Opensession failed with code 0xffff000d origin 0x3

```
However im unsure how to procede :/

**Comment by jforissier** [comment]
So `TA_FLAG_MULTI_SESSION` does not seem to be set, that might be the cause of the problem?

**Comment by etienne-lms** [comment]
`#define TA_FLAGS (TA_FLAG_SINGLE_INSTANCE | TA_FLAG_INSTANCE_KEEP_ALIVE | TA_FLAG_MULTI_SESSION)` is the right way. Check your build env, there is no reason why your TA should not be built with the `TA_FLAGS` you defined.
