### ISSUE TITLE
static TA examples

### ISSUE THREAD

**Issue by yilingxu** [OP-TEE/optee_os#2662]
Hi,

Are there any static TA examples?

It seems there were static TA examples at optee-os/core/arch/arm/sta/, but I cannot find them anymore.

Thanks.

Yiling Xu

**Comment by vchong** [comment]
https://github.com/OP-TEE/optee_os/tree/master/core/arch/arm/pta

They're now known as 'pseudo TAs'.

**Comment by yilingxu** [comment]
Thanks a lot. Since my problem has been solved, I will close this issue.
