### ISSUE TITLE
Panicked Keep Alive TA instances 

### ISSUE THREAD

**Issue by omihalac** [OP-TEE/optee_os#2671]
There would be a rather unclear topic to be further discussed with you about how the OP-TEE design is handling those cases when a TA instance which was created with the property `instanceKeepAlive`, panics from whatever reason.

In the default case of single instance – single session, when TA instance panics the corresponding session will be closed the instance's reference count will go to zero and OP-TEE will discard the instance.

The use case we (@cgellner and @agabbasov) are investigating is created by using multisession (`gpd.ta.multiSession ` set to `true`) single instance (`singleInstance ` set to `true`) with keep alive (`instanceKeepAlive` set to `true`) property active. Once the session which triggered the panic is closed (context is cleared) the rest of the sessions that are linked to the panicked TA cannot be closed by any means.

However, the system reacts as is described in the specification (1) Chapter 4.5 ` Trusted Application Configuration Properties` (2) and the disposal of the instance is inhibited by `TA_FLAG_INSTANCE_KEEP_ALIVE` setting. Therefore the panicked instance continues to exist and block all further use of the TA until the next reboot of the whole system.

On the other side in (1) Chapter 2.3.3 `Panics` (3) it clearly says that the core kills the panicking TA instance and close all sessions without any special reference for keep alive instances.

Could be whether consider a miss in the documentation regarding panicked keep alive TA instances or it makes sense to define a special handling for this case?

Meantime, we are working to create a series of test scenarios in optee_test suite that would reproduce this setup, but I have to know if this is the proper approach or the use cases simply are out of the scope in terms of Global Platform system specification.

[1] GPD_TEE_Internal_Core_API_Specification_v1.1.1

[2] `gpd.ta.instanceKeepAlive` - When this property is set to true, then the TA instance is terminated only when the TEE shuts down, which includes when the device goes through a system-wide global power cycle.

[3] When a Panic occurs, the Trusted Core Framework kills the panicking TA instance and does the following:
•	It discards all client entry point calls queued on the TA instance and closes all sessions opened by Clients.
•	It closes all resources that the TA instance opened, including all handles and all memory, and destroys the instance. Note that multiple instances can reference a common resource, for example an object. If an instance sharing a resource is destroyed, the Framework does not destroy the shared resource immediately, but will wait until no other instances reference the resource before reclaiming it.

**Comment by jforissier** [comment]
Hi @omihalac,

First of all, thanks for exposing the problem very clearly!

My feeling is, when a session panics, we should close all the other sessions and also destroy the instance, effectively returning to a "clean" state. It would be as if the first session invocation had not occurred yet.

Therefore, I would consider that point (2) is a miss in the specification. But perhaps I'm wrong. For instance, could it be a security risk if a keep-alive TA is allowed to be restarted even though the TEE itself has not restarted ?

I have sent an e-mail to the GP TEE Spec Working Group, hopefully they can clarify.

And FYI, I have checked the upcoming 1.2.0 specification and I see no difference.

**Comment by jforissier** [comment]
Update: I have exchanged a couple of e-mails with the GP TEE Spec WG, and we concluded that indeed, when the TA panics, the TEE should delete sessions/contexts/instances/whatever and allow the TA to be restarted from scratch the next time a client app invokes that particular TA.

@omihalac would you care to submit a pull request to fix this behavior? Thanks!

**Comment by omihalac** [comment]
@jforissier 

We will come up with a fix for the scenario(s) described above followed by a set of tests that would reproduce the cases in discussion.

**Comment by jbech-linaro** [comment]
@omihalac any updates?

**Comment by omihalac** [comment]
@jbech-linaro 

Apologize for the late reply, but unfortunately, it took more time that I initially expected and didn’t get a decent result in my opinion.

I got run into troubles when I tried to make a cleanup of the resources (sessions and context) in case of a panicked instance due to locking mechanisms inside the OPTEE software stack, knowledge that is still missing in my case.

I would like you to have a look over the following patches and maybe would be a good idea to get in sync about the implementation just before proposing a common acceptable PR.
Following the OPTEE-OS patch, I’ve been working to the corresponding tests in [optee_test](url
[optee_os_panicked_instance.zip](https://github.com/OP-TEE/optee_os/files/2821284/optee_os_panicked_instance.zip)
) that would eventually test the implementation, currently added in regression 1012 tests (maybe we could agree about placing them in OS related tests).

With the current implementation there is a change in overall system behavior, meaning that in case of an instance panicked all sessions connected and finally the entire context are closed. But the specification [1], Chapter 2.3.3 Panics is mentioned:

> From the client’s point of view, when a Trusted Application panics, the client commands MUST return the error TEE_ERROR_TARGET_DEAD with an origin value of TEE_ORIGIN_TEE until the session is closed.

This means that it shouldn’t clear out the session under which context  the panic was triggered, but it has to be specifically clear by the user. This contradicts to what we’ve discussed in the [comment](https://github.com/OP-TEE/optee_os/issues/2671#issuecomment-443723358) above.

I will appreciate your help in this matter and looking forward to your feedback.

[1] GPD_TEE_Internal_Core_API_Specification_v1.1.1
[2] [optee_os_panicked_instance.zip](https://github.com/OP-TEE/optee_os/files/2821285/optee_os_panicked_instance.zip)
[3] [optee_test_panicked_instance.zip](https://github.com/OP-TEE/optee_os/files/2821287/optee_test_panicked_instance.zip)

**Comment by omihalac** [comment]
@jbech-linaro

Do you have an update of this topic? Have you got a chance to look into the patch and its associated tests?

There are some contradictions in the specification that would be very useful to be cleared.

### Chapter 2.3.3 Panics 
> When a Panic occurs, the Trusted Core Framework kills the panicking TA instance and does the following:
> • It discards all client entry point calls queued on the TA instance and closes all sessions opened by Clients.
> • It closes all resources that the TA instance opened, including all handles and all memory, and destroys the instance. Note that multiple instances can reference a common resource, for example an object. If an instance sharing a resource is destroyed, the Framework does not destroy the shared resource immediately, but will wait until no other instances reference the resource before reclaiming it.

and
> From the client’s point of view, when a Trusted Application panics, the client commands MUST return the error TEE_ERROR_TARGET_DEAD with an origin value of TEE_ORIGIN_TEE until the session is closed.

against

> when the TA panics, the TEE should delete sessions/contexts/instances/whatever and allow the TA to be restarted from scratch the next time a client app invokes that particular TA.

mentioned before.

What we have done it was to make a full release of all resources (sessions, context, etc), but it seems that this approach is also breaking the specification since the system will never respond with `TEE_ERROR_TARGET_DEAD` in case of a panicked context. I'm afraid that we would need your support in more details about how this procedure should look like.

**Comment by jbech-linaro** [comment]
@omihalac first, thanks for putting something together and sorry for the delayed answer. Unfortunately I haven't had time to look into it yet, but I will try to not forget about. Having that said, it'd be easier it something was submitted as a regular pull request, so thing could be reviewed as any other patch for OP-TEE. But again, thanks for looking into this.

**Comment by omihalac** [comment]
@jbech-linaro 

Thank you for the reply. The idea behind keep maintaining the subject under an issue case instead of creating a standard PR was that the specification/latest updates from GlobalPlatform are  a bit contradictory in terms of how the system should react in case of a panic. 

However I will create in the shortest time a couple of pull requests in [optee_os](https://github.com/OP-TEE/optee_os) and its correspondence in [optee_test](https://github.com/OP-TEE/optee_test) where test case scenarios would be described.

**Comment by jbech-linaro** [comment]
Since I believe this has been resolved in https://github.com/OP-TEE/optee_os/pull/2993 (as continuation from https://github.com/OP-TEE/optee_os/pull/2838). I'm closing this issue. Thanks @omihalac and everyone else involved in this!
