### ISSUE TITLE
Linux kernel gets stuck while rebooting (Board: BD-SL-I.MX6)

### ISSUE THREAD

**Issue by h1994st** [OP-TEE/optee_os#2680]
Hi,

I'm using a development board, BD-SL-I.MX6, for TrustZone development. And I successfully run `optee_os` in my dev board.

I can run `xtest` after entering into Linux. All test cases provided by [optee_test](https://github.com/OP-TEE/optee_test) are passed. However, when I reboot the board, it gets stuck after enumerating the USB devices:

```
...
mmc0: SDHCI controller on 2198000.usdhc [2198000.usdhc] using ADMA
sdhci-esdhc-imx 219c000.usdhc: Got CD GPIO
mmc1: SDHCI controller on 219c000.usdhc [219c000.usdhc] using ADMA
mxc_vpu 2040000.vpu_fsl: VPU initialized
mxc_vdoa 21e4000.vdoa: i.MX Video Data Order Adapter(VDOA) driver probed
caam 2100000.caam: ERA source: CAAMVID.
caam 2100000.caam: AXI pipeline throttling enabled.
caam 2100000.caam: device ID = 0x0a16010000000000 (Era 4)
job rings = 2, qi = 0
caam_jr 2101000.jr0: failed to flush job ring 0
mmc1: host does not support reading read-only switch, assuming write-enable
mmc1: new high speed SDHC card at address e624
mmcblk1: mmc1:e624 AFGCC 14.8 GiB 
 mmcblk1: p1
usb 1-1: new high-speed USB device number 2 using ci_hdrc
hub 1-1:1.0: USB hub found
hub 1-1:1.0: 3 ports detected
usb 1-1.2: new low-speed USB device number 3 using ci_hdrc
...
```

In the device tree bindings, I do not add `psci`. If I add `psci` in the device tree bindings, the Linux Kernel cannot work at the first place, and it will not even print out any log information (with `earlyprintk` enabled and `loglevel` as 7). I'm not sure whether the above problem is related to `psci`. Does anyone have any ideas about this problem?

BTW,
Here is my development configuration:
- Board: [BD-SL-I.MX6](https://boundarydevices.com/product/sabre-lite-imx6-sbc/)
- U-Boot: maintained by Boundary Device, [link](https://github.com/boundarydevices/u-boot-imx6/tree/boundary-v2018.07)
- Linux Kernel: maintained by Boundary Device, [link](https://github.com/boundarydevices/linux-imx6/tree/boundary-imx_4.9.x_2.0.0_ga)
- optee_os: [commit, e7d51f42fd0d05bef6557c26d1428a4ea476e347](https://github.com/OP-TEE/optee_os/tree/e7d51f42fd0d05bef6557c26d1428a4ea476e347)
    - `make PLATFORM=imx-mx6qsabrelite ARCH=arm CFG_BUILT_IN_ARGS=y CFG_PAGEABLE_ADDR=0 CFG_NS_ENTRY_ADDR=0x10800000 CFG_DT_ADDR=0x13000000 CFG_DT=y CFG_PSCI_ARM32=n DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4 CFG_BOOT_SYNC_CPU=n CFG_BOOT_SECONDARY_REQUEST=y`

**Comment by jbech-linaro** [comment]
@OP-TEE/plat-imx , thoughts?

**Comment by bryanodonoghue** [comment]
I wouldn't bother debugging the reset + boot issue without first understanding why you can't boot with the PSCI nodes added.

How are you adding the PSCI nodes - into the DTB or a DTB overlay with OPTEE or hard-coding it into your DTB ?

If you are hard-coding - the first piece of advice is try not to do that but, the second suggestion is - check the values you are hard-coding.

And actually is this board closed i.e. is the secure-boot bit blown ?

**Comment by h1994st** [comment]
Hi @bryanodonoghue ,

> How are you adding the PSCI nodes - into the DTB or a DTB overlay with OPTEE or hard-coding it into your DTB ?

I add PSCI configuration into the *.dtsi files, all based on [this repo (BoundaryDevice Linux i.MX6 Kernel)](https://github.com/boundarydevices/linux-imx6/tree/boundary-imx_4.9.x_2.0.0_ga):

- `arch/arm/boot/dts/imx6q.dtsi`: add `enable-method = "psci"` for each cpu node

    ```
    cpus {
        ...
        cpu0: cpu@0 {
            ...
            enable-method = "psci";
            ...
        }
        ...
        cpu@1 {
            ...
            enable-method = "psci";
            ...
        }
        ...
    }
    ```

- `arch/arm/boot/dts/imx6qdl.dtsi`: add a psci node

    ```
    psci {
        compatible      = "arm,psci-0.2";
        method          = "smc";
    };
    ```

> And actually is this board closed i.e. is the secure-boot bit blown ?

I'm not sure about this. What do you mean "closed"?

---

"reset + boot" is quite annoying. I still have no idea about this.

Thanks!

**Comment by MrVan** [comment]
@h1994st  `CFG_DT=y CFG_PSCI_ARM32=n DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4 CFG_BOOT_SYNC_CPU=n CFG_BOOT_SECONDARY_REQUEST=y` you not define CFG_PSCI_ARM32, but as you said you added psci node in device tree, this will not work. You need enable PSCI_ARM32 when you build optee-os.

**Comment by h1994st** [comment]
@MrVan Yeah, that's the problem. Actually, I enabled `CFG_PSCI_ARM32` before while compiling `optee_os`, but still got the aforementioned "psci" issue.

Do you have any idea about the "reset + boot" issue? This blocks me for a while

**Comment by MrVan** [comment]
@h1994st Are u using wdog to do external reset or internal reset? If you are doing external reset to reset the pmic/board, there should be no issue.

**Comment by h1994st** [comment]
@MrVan I'm sorry that I'm not familiar about the watchdog. I just pressed a button on the board (i.e., the green button in the lower left corner of the following image). Is that external reset?

![BD-SL-I.MX6](https://1quxc51443zg3oix7e35dnvg-wpengine.netdna-ssl.com/wp-content/uploads/2012/05/BD-SL-iMX6.jpg)

**Comment by MrVan** [comment]
@h1994st I got confused (: I suppose the green key is reset key, then do you mean pressing the reset key, linux kernel could not start properly, as you said, usb emulation failed?

**Comment by h1994st** [comment]
@MrVan Yeah, after I pressed the green (reset) key, the Linux kernel could not start properly. By the way, the USB enumeration did not fail, the booting process got stuck after enumerating the USB devices.

**Comment by h1994st** [comment]
I forgot to initialize secondary CPUs, which leads to this issue.

The problem has been solved.

Thanks, everyone!

**Comment by ncpsa** [comment]
Hi @h1994st ,
I am also facing PSCI issue, when I enabled PSCI, the kernel is coming up.
How did you resolve the issue?
Could you help?
