### ISSUE TITLE
hikey960: xtest 2002 hangs (first seen with IBART)

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#2684]
`xtest 2002` randomly hangs on HiKey960.
Steps to reproduce:
- Build OP-TEE with:
  ```
  make CFG_RPMB_WRITE_KEY=y CFG_RPMB_FS=y CFG_SECURE_DATA_PATH=y CFG_WITH_PAGER=y CFG_LOCKDEP=y CFG_TEE_CORE_LOG_LEVEL=2
  ```
  (using manifest.git hikey960.xml)
- Run the following loop: 
  ```
  C=0; while [ $? -eq 0 -a $C -lt 500 ]; do echo "=== C=$C"; C=`expr $C + 1`; xtest 2002; done
  ```

At some point (might take a couple of times or up to 300 times), the test hangs, then the kernel reports a stuck CPU:
```
[  226.072851] rcu: INFO: rcu_preempt detected stalls on CPUs/tasks:
[  226.078967] rcu:     1-...0: (1 GPs behind) idle=cee/1/0x4000000000000000 softirq=35314/35316 fqs=2314
[  226.088099] rcu:     (detected by 4, t=5252 jiffies, g=65789, q=1583)
[  226.094278] Task dump for CPU 1:
[  226.097502] xtest           R  running task        0  6042   1738 0x00000002
[  226.104552] Call trace:
[  226.107006]  __switch_to+0x94/0xd0
[  226.110405]  0xffff8000bffc1000
```

This issue was first noticed in the IBART CI loop (on a HiKey620 board).

**Comment by jenswi-linaro** [comment]
I've managed to reproduces something similar to this on qemu (v7) in the same test case. All cores are in normal world idling, while the secure world threads are suspended. I'll try to fix that since I suspect it's easier to fix and may regardless affect this error.

**Comment by jforissier** [comment]
Fixed.
