### ISSUE TITLE
how to use exp() function in TAs

### ISSUE THREAD

**Issue by mofanv** [OP-TEE/optee_os#2687]
Hello,
Is there any way to use math functions like exp() in TAs?

TAs don't include math.h, and I know to add the math.h as a library seems not a easy work. The rand() function can be replaced by TEE_xxx. But how could I use other kinds of math functions?

Any help is appreciated.
Vincent

**Comment by mofanv** [comment]
Hello,
Is there any way to use math functions like exp() in TAs?

TAs don't include `math.h`, and I know to add the `math.h` as a library seems not a easy work. The `rand()` function can be replaced by `TEE_xxx`. But how could I use other kinds of math functions?

Any help is appreciated.
Vincent

**Comment by igoropaniuk** [comment]
@mofanv check TEE Arithmeticac API section in https://globalplatform.org/wp-content/uploads/2018/06/GPD_TEE_Internal_Core_API_Specification_v1.1.2.50_PublicReview.pdf

**Comment by jforissier** [comment]
@mofanv one option may be to add support for `<math.h>` / `libm.a` (at least partial support) using source from `newlib`, similar to what we do for `libc` (which is in OP-TEE's `libutils.a`).
https://github.com/bminor/newlib/tree/master/newlib/libm/math

**Comment by mofanv** [comment]
Many thanks for your helpful advice. It works now! I will close this issue.
