### ISSUE TITLE
Trying to parse an X509 cert and check its expiration date by libmbedtls in TA

### ISSUE THREAD

**Issue by Summersummer3** [OP-TEE/optee_os#2689]
I tried parse an X509 cert and check its expiration date by libmbedtls in TA. It's OK for X509 parsing while compile errors happened when I tried to enable the expiration date check.

I used these two functions in "lib/libmbedtls/library/x509.c" for such check, it requires `MBEDTLS_HAVE_TIME_DATE` defined to obtain the current time by `static int x509_get_current_time( mbedtls_x509_time *now )`:

`int mbedtls_x509_time_is_past( const mbedtls_x509_time *to )`
`int mbedtls_x509_time_is_future( const mbedtls_x509_time *from )`

So I defined `MBEDTLS_HAVE_TIME_DATE` and 'MBEDTLS_HAVE_TIME' in "lib/libmbedtls/include/mbedtls_config_uta.h"

While it seems errors happaned because the head file "time.h" is included in "lib/libmbedtls/include/mbedtls/platform_time.h", which actually requires the Linux head file (I guess).
 The included "time.h" may comes from  "lib/libutils/isoc/include/time.h", and it defines nothing but `typedef int64_t time_t;`

the err log:
![image](https://user-images.githubusercontent.com/11764207/49572845-9b7ec100-f977-11e8-97f4-88c4e9fb3972.png)

So my question is if such problems can be solved and get exact system time in `static int x509_get_current_time( mbedtls_x509_time *now )` . Or the only way is to get system time by  `void TEE_GetSystemTime(TEE_Time *time)` in "tee_api.c", then check the expiration date.

Our code:
```
    mbedtls_x509_crt_init(&cert);
    ret = mbedtls_x509_crt_parse(&cert, cert_ptr, cert_len);
    if (TM_OK != ret)
    {
        EMSG("cert parse failed, ret: 0x%X", (int)ret);
        return TM_ERROR;
    }
```

```
   if (mbedtls_x509_time_is_past(cert.valid_to)
        || mbedtls_x509_time_is_future(cert.valid_from))
    {
        EMSG("The certificate expiration date invalid");
        return TM_ERROR;
    }

```
Much thanks for reading !

**Comment by ammarsalman94** [comment]
It seems this issue was never resolved. Is there any solution or possible alternative? 

I am aware of `TEE_GetREETime(TEE_Time *time)` function, but that returns REE time, and it's formatted as epochs which need to be constructed into a `struct tm`. So far there are tons of issues linking to `mbedTLS` to get the time from there, and there does not seem to be any alternative to getting current time and date in tm format. You would think such a task should be simple... smh

**Comment by jenswi-linaro** [comment]
A problem with `TEE_GetREETime()` is that it's not secure so we can't trust it.

**Comment by ammarsalman94** [comment]
I am well aware. I am getting UTC time from an NMEA statement from a GPS sensor instead then I am using that to set a made up system clock which all in all adds complexity. REE cannot be trusted but currently, in emulated environments, it is the only way. 

Is there other hardware I am unaware of which can return epochs securely?
