### ISSUE TITLE
optee os Lock

### ISSUE THREAD

**Issue by yilingxu** [OP-TEE/optee_os#2694]
Hi,

I write a static TA, my code will crash some times. It seems happens during CPU switching (My imx6q board has four CPUs). The error message as follow:
```
INFO: rcu_preempt detected stalls on CPUs/tasks:
        3: (1 GPs behind) idle=47f/140000000000000/0 softirq=1270/1272 fqs=26
        (detected by 1, t=2278 jiffies, g=532, c=531, q=111)
```
My question are:
1. Is CPU switching lead to code crash?
2. If so, How I can solve this problem? Are there any Lock I can use to make my code finish running in one CPU?

Thanks.
Yiling Xu

**Comment by jforissier** [comment]
Hi @yilingxu ,

The message "rcu_preempt detected stalls" is not a crash (your code is still running). It means the CPU has spent too much time in secure world without returning to the Linux scheduler. See https://www.kernel.org/doc/Documentation/RCU/stallwarn.txt for details.

Have you enabled `CONFIG_PREEMPT` in the kernel? It should help. If you see this message with `CONFIG_PREEMPT=y,` it could be that interrupts have been masked for too long.

**Comment by yilingxu** [comment]
Hi @jforissier 

Thanks a lot. I have enabled CONFIG_PREEMPT in kernel. I will see why interrupts are masked for too long. But I wonder why this mistake sometimes occurs and sometimes not.
