### ISSUE TITLE
imx6q CAAM in optee

### ISSUE THREAD

**Issue by yilingxu** [OP-TEE/optee_os#2701]
Hi,

I'm working on imx6q. I need a secure storage to store secret key for remote attestation. After reading Security Reference Manual, I know CAAM module can fulfill my needs. So I need to enable CAAM module in optee. I see someone has asked a similar question [here](https://github.com/OP-TEE/optee_os/issues/1293). 

Has anyone working on CAAM in optee now?  @MrVan 
Yiling Xu

**Comment by jbech-linaro** [comment]
@OP-TEE/plat-imx anyone?

**Comment by bryanodonoghue** [comment]
AFAIK nobody has undertaken yet, the task of getting the CAAM to do something useful in OPTEE.

If you do go that direction please keep in-mind job-ring permissions

https://github.com/torvalds/linux/blob/master/arch/arm/boot/dts/imx7s.dtsi - one of the job-rings will have to be allocated to TZ and this will need to be agreed/communicated with/to the Linux kernel.

**Comment by MrVan** [comment]
https://source.codeaurora.org/external/imx/imx-optee-os/log/?h=imx_4.14.78_1.0.0_ga already has CAAM implemented. You could check. Need some restructure to make that upstream.

**Comment by yilingxu** [comment]
@MrVan Thanks for your contribution.

**Comment by Emantor** [comment]
@MrVan Are you actively working on upstreaming the changes yourself? If yes, this should be coordinated to not duplicate development effort.

**Comment by MrVan** [comment]
@Emantor It is on my todo list and would be started when I back from CNY holiday.

**Comment by yilingxu** [comment]
@MrVan I download code: imx_4.14.78_1.0.0_ga, and follow your direction http://mrvan.github.io/optee-imx6q-sabresd to boot my imx6q board(replace optee-os with imx_4.14.78_1.0.0_ga), but the boot sequence halt at Starting kernel ..., it seems optee os does not boot at all, do you have any suggestions?

Thanks.

**Comment by Emantor** [comment]
@yilingxu You'll need to add the correct nodes to your device tree configuration or use the linux-imx kernel from CodeAurora.

**Comment by yilingxu** [comment]
@Emantor, I get Linux kernel from https://github.com/MrVan/linux/tree/imx_4.1.15_2.0.0_ga, whose device tree is not complete?

Besides, I Tried the github/master branch in https://source.codeaurora.org/external/imx/imx-optee-os/?h=imx_4.14.78_1.0.0_ga, it boot normally. But the github/master branch does not have CAAM implemented.

**Comment by Emantor** [comment]
@yilingxu You will need the kernel from https://source.codeaurora.org/external/imx/linux-imx/log/?h=imx_4.14.78_1.0.0_ga , which is the same tag as used for the optee-imx repository.
The device tree changes can be found in the tree, its easiest to look at the commits for the `arch/arm/boot/dts/` directory.

**Comment by yilingxu** [comment]
I have changed uboot/optee os/linux to 4.14.78, but optee os still can't be boot. Here are my operations:
uboot 
1 download
git clone https://source.codeaurora.org/external/imx/uboot-imx -b rel_imx_4.14.78_1.0.0_ga
2 compile
make ARCH=arm mx6qsabresd_defconfig
CROSS_COMPILE=arm-linux-gnueabihf- make ARCH=arm
I can get u-boot-dtb.imx	  
3 install
sudo dd if=u-boot-dtb.imx of=/dev/sdb bs=512 seek=2 conv=sync conv=notrunc

optee os
1 download
git clone https://source.codeaurora.org/external/imx/imx-optee-os -b imx_4.14.78_1.0.0_ga
2 compile
CROSS_COMPILE=arm-linux-gnueabihf- make PLATFORM=imx-mx6qsabresd ARCH=arm CFG_BUILT_IN_ARGS=y CFG_PAGEABLE_ADDR=0 CFG_NS_ENTRY_ADDR=0x12000000 CFG_DT_ADDR=0x28000000 CFG_DT=y CFG_PSCI_ARM32=y DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4 CFG_BOOT_SYNC_CPU=n CFG_BOOT_SECONDARY_REQUEST=y
./mkimage -A arm -O linux -C none -a 0x13ffffc0 -e 0x14000000 -d out/arm-plat-imx/core/tee.bin uTee
(I also tried: 
./mkimage -A arm -O linux -C none -a 0x13ffffe4 -e 0x14000000 -d out/arm-plat-imx/core/tee.bin uTee
./mkimage -A arm -O linux -C none -a 0x14000000 -e 0x1400001c -d out/arm-plat-imx/core/tee.bin uTee
)
I can get uTee

linux kernel
1 download
git clone https://source.codeaurora.org/external/imx/linux-imx/ -b imx_4.14.78_1.0.0_ga
2 compile
make ARCH=arm imx_v7_defconfig
CROSS_COMPILE=arm-linux-gnueabihf- make ARCH=arm
I can get zImage, imx6q-sabresd.dtb

boot sequence:
tftp 0x12000000 zImage
tftp 0x28000000 imx6q-sabresd.dtb
tftp 0x30000000 uTee
bootm 0x30000000 - 0x28000000

boot log
U-Boot 2018.03-00924-g654088c-dirty (Feb 18 2019 - 18:39:03 +0800)

CPU:   Freescale i.MX6Q rev1.2 996 MHz (running at 792 MHz)
CPU:   Automotive temperature grade (-40C to 125C) at 21C
Reset cause: POR
Model: Freescale i.MX6 Quad SABRE Smart Device Board
Board: MX6-SabreSD
DRAM:  1 GiB
PMIC: PFUZE100! DEV_ID=0x10 REV_ID=0x21
MMC:   FSL_SDHC: 0, FSL_SDHC: 1, FSL_SDHC: 2
Loading Environment from MMC... OK
No panel detected: default to Hannstar-XGA
Display: Hannstar-XGA (1024x768)
In:    serial
Out:   serial
Err:   serial
switch to partitions #0, OK
mmc1 is current device
flash target is MMC:1
Net:   eth0: ethernet@02188000 [PRIME]
Fastboot: Normal
Normal Boot
Hit any key to stop autoboot:  0
=>
=> tftp 0x12000000 zImage
Using ethernet@02188000 device
TFTP from server 192.168.10.26; our IP address is 192.168.10.27
Filename 'zImage'.
Load address: 0x12000000
Loading: #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         #################################################################
         ##############
         3.9 MiB/s
done
Bytes transferred = 7391104 (70c780 hex)
=> tftp 0x28000000 imx6q-sabresd.dtb
Using ethernet@02188000 device
TFTP from server 192.168.10.26; our IP address is 192.168.10.27
Filename 'imx6q-sabresd.dtb'.
Load address: 0x28000000
Loading: ###########
         2.4 MiB/s
done
Bytes transferred = 53699 (d1c3 hex)
=> tftp 0x30000000 uTee
Using ethernet@02188000 device
TFTP from server 192.168.10.26; our IP address is 192.168.10.27
Filename 'uTee'.
Load address: 0x30000000
Loading: ##########################################################
         3.3 MiB/s
done
Bytes transferred = 292180 (47554 hex)
=> bootm 0x30000000 - 0x28000000
## Booting kernel from Legacy Image at 30000000 ...
   Image Name:
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    292116 Bytes = 285.3 KiB
   Load Address: 13ffffc0
   Entry Point:  14000000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 28000000
   Booting using the fdt blob at 0x28000000
   Loading Kernel Image ... OK
   kernel loaded at 0x13ffffc0, end = 0x140474d4
   Using Device Tree in place at 28000000, end 280101c2
switch to ldo_bypass mode!
## Transferring control to Linux (at address 14000000)...

Starting kernel ...

machid is 3980	//debug on uboot
r2 is 0x28000000	//debug on uboot

**Comment by MrVan** [comment]
@yilingxu you are using wrong uboot defconfig, mx6qsabresd_optee_defconfig should be used.

**Comment by Emantor** [comment]
@yilingxu I also had to disable the TZC, otherwise my board wouldn't boot with the optee-imx branch, e.g. CFG_TZC380=n, also to actually use the CAAM, you'll need CFG_IMXCRYPT=y.

**Comment by yilingxu** [comment]
Thanks to @jbech-linaro @MrVan and @Emantor, my optee os 4.14.78 boot successfully. My operations are summarized as follows:
 ## uboot:
1 download
git clone https://source.codeaurora.org/external/imx/uboot-imx -b rel_imx_4.14.78_1.0.0_ga
2 compile
make ARCH=arm mx6qsabresd_optee_defconfig
CROSS_COMPILE=arm-linux-gnueabihf- make ARCH=arm
_I can get u-boot-dtb.imx_
3 install
sudo dd if=u-boot-dtb.imx of=/dev/sdb bs=512 seek=2 conv=sync conv=notrunc

## optee os:
1 download
git clone https://source.codeaurora.org/external/imx/imx-optee-os -b imx_4.14.78_1.0.0_ga
2 compile
 CROSS_COMPILE=arm-linux-gnueabihf- make PLATFORM=imx-mx6qsabresd ARCH=arm CFG_BUILT_IN_ARGS=y CFG_PAGEABLE_ADDR=0 CFG_NS_ENTRY_ADDR=0x12000000 CFG_DT_ADDR=0x28000000 CFG_DT=y CFG_PSCI_ARM32=y DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4 CFG_BOOT_SYNC_CPU=n CFG_BOOT_SECONDARY_REQUEST=y CFG_IMXCRYPT=y
./mkimage -A arm -O linux -C none -a 0x13ffffe4 -e 0x14000000 -d out/arm-plat-imx/core/tee.bin uTee
_I can get uTee_

## linux kernel:
1 download
git clone https://source.codeaurora.org/external/imx/linux-imx/ -b imx_4.14.78_1.0.0_ga
2 compile
make ARCH=arm imx_v7_defconfig
CROSS_COMPILE=arm-linux-gnueabihf- make ARCH=arm
_I can get zImage, imx6q-sabresd.dtb_

## boot sequence:
tftp 0x12000000 zImage
tftp 0x28000000 imx6q-sabresd.dtb
tftp 0x30000000 uTee
bootm 0x30000000 - 0x28000000

**Comment by yilingxu** [comment]
@MrVan, I want to use CAAM in optee os to generate a blob for secure key storage, I read CAAM in optee os, and compares the code of CAAM in linux. 

sm_sore.c in Linux is used to generate a blob, but I can't find similar work in OPTEE. Are there any work in optee to generate a blob now?

**Comment by Emantor** [comment]
@yilingxu the current optee-imx branch does not support the BLOB and DEBLOB protocol.

**Comment by yilingxu** [comment]
I have achieved blob encapsulation and decapsulation in optee os 4.14.18. Thanks again for your help, and   I will close this issue.

**Comment by Emantor** [comment]
@yilingxu Do you intend to share your code for the blob de- and encapsulation?

**Comment by Emantor** [comment]
I just found a FSL_SEC (CAAM) implementation from Microsoft https://github.com/ms-iot/optee_os/commit/ab616627d2ef6c2dc9a1be4eb05a3bd35edb5e2c

**Comment by Sadort** [comment]
Hi @yilingxu , did you enable pager on imx6qsabresd? I'm confused about the loading address of tee-pager_v2.bin and tee-pageable_v2.bin, and the way of booting.
