### ISSUE TITLE
A bug in  probe_max_it

### ISSUE THREAD

**Issue by noe77777** [OP-TEE/optee_os#2719]
Hi There,

    I found a bug in  probe_max_it in 
(https://github.com/OPTEE/optee_os/blob/master/core/drivers/gic.c).
    
    This bug will cause our embedded linux receive unexpected interrupts during the boot stage.
    
```
 for (i = max_regs; i >= 0; i--) {
		uint32_t old_reg;
		uint32_t reg;
		int b;

		old_reg = read32(gicd_base + GICD_ISENABLER(i));
		write32(0xffffffff, gicd_base + GICD_ISENABLER(i));
		reg = read32(gicd_base + GICD_ISENABLER(i));
		write32(old_reg, gicd_base + GICD_ICENABLER(i)); <== This line won't restore old_reg value.
```                                                                         

      This bug can be fixed by one of two below modifications.
      The first one is:
         write32( ~old_reg, gicd_base + GICD_ICENABLER(i))
      The second one is 
         write32( old_reg, gicd_base + GICD_ISENABLER(i))

**Comment by jbech-linaro** [comment]
@noe77777 , I think you're right. Do you think you could create a pull request with the fix? Thanks!

**Comment by noe77777** [comment]
@jbech-linaro , thanks for your reply,  I will pull a request today, thanks.

**Comment by jbech-linaro** [comment]
Solved in: https://github.com/OP-TEE/optee_os/pull/2722, thanks! Closing the ticket!
