### ISSUE TITLE
memory access rights handling in optee

### ISSUE THREAD

**Issue by aspcn** [OP-TEE/optee_os#2730]
Hello,
Based on the TEE_PARAM_TYPE_MEMREF_* type, Do we need to check and set access rights for the buffer?.
I have seen default buffer attribute(which has all rights) is set inside tee_mmu_umap_add_param() for all the buffers without considering its direction(either input or output or both).
As per the current implementation, the function tee_mmu_check_access_rights() will never return TEE_ERROR_ACCESS_DENIED when we check TEE_MEMORY_ACCESS_WRITE or TEE_MEMORY_ACCESS_READ on buffers. Is that expected?
Can someone shed more light on this for more clarity?

Thank You!!

**Comment by aspcn** [comment]
Can anyone provide your comment please?

**Comment by jenswi-linaro** [comment]
It's the other way around, `tee_mmu_check_access_rights()` is used to check that the memory region can be accessed as expected. In the end it checks against how the memory is mapped.

**Comment by aspcn** [comment]
Thanks @jenswi-linaro  . I understood that point. When I checked the access rights using the function **tee_mmu_check_access_rights**, I was not getting the access rights as expected. When I further debugged , it is noticed that **tee_mmu_umap_add_param** function  is not setting attributes correctly, instead it is setting hard-coded attributes
uint32_t attr = TEE_MMU_UDATA_ATTR;
.
.
.mmu->regions[n].attr = attr;

**Comment by jenswi-linaro** [comment]
What's the problem with that?

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
