### ISSUE TITLE
How to add python to rootfs?

### ISSUE THREAD

**Issue by duduscript** [OP-TEE/optee_os#2731]
Hello,
I want to add python to rootfs, how can I do that? 
The plat I running is FVP, I want to run python in normal world and I find there is not a python binary. Should  I need to compile and build python with an opposite gcc version and then add it to rootfs?

**Comment by jforissier** [comment]
Hi,

Have you tried to enable `BR2_PACKAGE_PYTHON` or `BR2_PACKAGE_PYTHON3` in buildroot?
https://github.com/OP-TEE/build/blob/3.3.0/common.mk#L200-L242

**Comment by duduscript** [comment]
Thank you @jforissier, it works.
