### ISSUE TITLE
Is this a memory leak?

### ISSUE THREAD

**Issue by sticfeynman** [OP-TEE/optee_os#2738]
In the syscall_storage_obj_create(), it seems that the o->attr is not free() in the error handling part. o->attr might have been allocate in tee_svc_storage_init_file() when attr_o is not null.

**Comment by jforissier** [comment]
@sticfeynman I think you're right. Would you care to create a pull request?

**Comment by jforissier** [comment]
I'd like to consider this for the coming release, could you please create a PR? Thanks!
