### ISSUE TITLE
statically links wolfssl to TA

### ISSUE THREAD

**Issue by iovoi** [OP-TEE/optee_os#2740]
Hi

I am developing TAs using default configuration on OP-TEE for Qemu. Currently, I am trying to integrate wolfssl to my ta in optee to provide tls capability. I successfully compile wolfssl into libwolfssl.a. However, when I make the whole project and run qemu with make run, I got the following errors:

  CPP     out/ta.lds
  CC      out/tls_ta_app.o
  CC      out/user_ta_header.o
  LD      out/7aaaf200-2450-11e4-abe2-0002a5d5c51b.elf
./libwolfssl.a(src_libwolfssl_la-dh.o): In function `wc_DhGenerateKeyPair':
dh.c:(.text+0x5fe): undefined reference to `pow'
dh.c:(.text+0x60a): undefined reference to `log'
dh.c:(.text+0x612): undefined reference to `pow'
./libwolfssl.a(src_libwolfssl_la-ssl.o): In function `wolfSSL_read_internal':
ssl.c:(.text+0x28): undefined reference to `__errno_location'
./libwolfssl.a(src_libwolfssl_la-ssl.o): In function `wolfSSL_write':
ssl.c:(.text+0x6f0): undefined reference to `__errno_location'
./libwolfssl.a(src_libwolfssl_la-ssl.o): In function `wolfSSL_connect':
ssl.c:(.text+0x1904): undefined reference to `__errno_location'
./libwolfssl.a(src_libwolfssl_la-ssl.o): In function `wolfSSL_accept':
ssl.c:(.text+0x1b00): undefined reference to `__errno_location'
./libwolfssl.a(src_libwolfssl_la-random.o): In function `wc_GenerateSeed':
random.c:(.text+0x54e): undefined reference to `open'
random.c:(.text+0x55c): undefined reference to `open'
random.c:(.text+0x572): undefined reference to `read'
random.c:(.text+0x58c): undefined reference to `close'
./libwolfssl.a(src_libwolfssl_la-asn.o): In function `MatchBaseName':
asn.c:(.text+0x17e): undefined reference to `__ctype_tolower_loc'
./libwolfssl.a(src_libwolfssl_la-asn.o): In function `ValidateDate':
asn.c:(.text+0x12b6): undefined reference to `time'
asn.c:(.text+0x1316): undefined reference to `gmtime'
./libwolfssl.a(src_libwolfssl_la-asn.o): In function `wc_GetTime':
asn.c:(.text+0x13d6): undefined reference to `time'
./libwolfssl.a(src_libwolfssl_la-integer.o): In function `mp_read_radix':
integer.c:(.text+0x2f2e): undefined reference to `__ctype_toupper_loc'
./libwolfssl.a(src_libwolfssl_la-ecc.o): In function `wc_ecc_get_curve_idx_from_name':
ecc.c:(.text+0x13b8): undefined reference to `strncasecmp'
./libwolfssl.a(src_libwolfssl_la-internal.o): In function `MatchDomainName':
internal.c:(.text+0x201c): undefined reference to `__ctype_tolower_loc'
./libwolfssl.a(src_libwolfssl_la-internal.o): In function `LowResTimer':
internal.c:(.text+0x198a): undefined reference to `time'
...

I followed the instructions in [#1255](https://github.com/OP-TEE/optee_os/issues/1255) and put libwolfssl.a under the ta folder. Then I also added the following lines

sub.mk
libdirs += .
libnames += wolfssl
libdeps += libwolfssl.a

Makefile
LDFLAGS += -static -lm

Can anyone give me some pointers on how to solve this issue?

Thank you very much in advance!

**Comment by jenswi-linaro** [comment]
You need to compile the library in the environment provided by OP-TEE, using the same .h file and same compiler flags. Using different .h files and the error you see here isn't unexpected.

**Comment by iovoi** [comment]
Thank you for the quick response @jenswi-linaro . 

Suppose I have the source code for wolfssl as a separated folder under my working directory like below:

my-working-directory
├── arm-trusted-firmware
├── bios_qemu_tz_arm
├── build
├── buildroot
├── linux
├── optee_benchmark
├── optee_client
├── optee_examples
├── optee_os
├── optee_test
├── out
├── out-br
├── qemu
├── README.txt
├── soc_term
├── toolchains
└── wolfssl

How should I compile the source code in wolfssl folder using the OP-TEE environment?

Thank you very much!

**Comment by jforissier** [comment]
A static library is compiled like a TA, but instead of setting `BINARY=<uuid>` you set `LIBNAME=<name>` in the Makefile.

**Comment by jenswi-linaro** [comment]
I'm afraid there's no shortcuts here, you'll need to replace the existing make system as suggested by @jforissier .

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
