### ISSUE TITLE
Asymmetric decrypt with algorithm TEE_ALG_RSA_NOPAD returns mismatch data for some testcase

### ISSUE THREAD

**Issue by Sourabhharman** [OP-TEE/optee_os#2743]
Hi Crypto experts,
I have used the GPD internal API's TEE_AsymmetricEncrypt/TEE_AsymmetricDecrypt to encrypt the folowing data : 
char plaintext[ ] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09};

After encrypting the data with the algorithm TEE_ALG_RSA_NOPAD, I decrypt the cipher.
As a result, I am getting the following decrypted text:
0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09

Later I debugged the optee source and found that [at this point](https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/tee_ltc_provider.c#L582) the zero padding is being removed from the decrypted text.
Is this step in decrypt function is really necessary?
If so, then is there any way to get back correct decrypted data for my testcase explained above?

Thanks in Advance :)

**Comment by jforissier** [comment]
Hi @Sourabhharman,

I think this link provides a valid answer: https://stackoverflow.com/questions/37683385/decrypting-a-string-with-rsa-returns-additional-zeros-at-the-beginning

(basically and for the record in case the link breaks: NOPAD means you have to deal with padding yourself, the algorithm simply works on big numbers, and having OP-TEE strip the leading zeroes is as valid as padding the result with zeroes up to  the modulus size).

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
