### ISSUE TITLE
OP-TEE build and installation on the Raspberry Pi

### ISSUE THREAD

**Issue by Hacklog24** [OP-TEE/optee_os#2755]
Hi,
I'm new to OP-TEE and wanted to learn more about it by running it on a Raspberry Pi 3.
But something does not seem to work...
Here's the list of actions I just followed based on your build support page (https://github.com/OP-TEE/build):

   1) Installed the necessary dependencies;

   2) Installed repo;

    3) Got OP-TEE's code through repo;
         repo init -u https://github.com/OP-TEE/manifest.git -m rpi3.xml

    4) Got the toolchains;

    5) Ran the "make " command;

    6) Flashed an SD card with the commands shown in "make img-help"

    But once the procedure is finished and the card inserted into the raspberry, the red LED flashes and      nothing happens on the screen. Can someone help me please?

Ps: I’m using Raspberry Pi 3B+

Thank you very much
Best Regards,
Michelangelo

**Comment by Hacklog24** [comment]
Hi,
I’m using a LCD display connected to the Raspberry Pi. It’s wrong?

**Comment by Hacklog24** [comment]
Thank you very much for your help and sorry for the question. So, I will follow his advice hoping to solve. Thanks for the availability, you’re so kind.

 Thanks again.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered. Having that said, feel free to re-open the ticket if you have more to add to the ticket.

**Comment by Hacklog24** [comment]
Good morning,
I connected the uart cable between pc and raspberry, the serial port is seen by the system, but neither through minicom nor via putty on windows, I can run a test. Once I start minicom, I get only the command list, but I can not give an input. Can someone help me please?

PS: I followed the wiring instructions and software settings.

Thanks again.
