### ISSUE TITLE
xtest regression 1013.2 fails TEEC_ERROR_ITEM_NOT_FOUND

### ISSUE THREAD

**Issue by dleymarie** [OP-TEE/optee_os#2756]
Hello,
I ported OP-TEE n my platform: confidential NXP (ARM Cortex-A7 similar to iMX7). 
Memory configuration
#define DDR_OPTEE_RESERVED_SEC_SIZE		((4 * 1024 * 1024) + 0xa8000)
#define DDR_OPTEE_RESERVED_SHMEM_SIZE	(2 * 1024 * 1024)
#define TEE_RAM_VA_SIZE		(1 * 1024 * 1024)
#define TEE_RAM_PH_SIZE		TEE_RAM_VA_SIZE
#define TA_RAM_SIZE			(TZDRAM_SIZE - TEE_RAM_VA_SIZE)
#define DRAM_PHYS_SIZE		(128 * 1024 * 1024)

When I run xtest, I have some errors TEEC_ERROR_ITEM_NOT_FOUND in regression 1013.2.

`
* regression_1013 Test concurency with concurrent TA
o regression_1013.1 Using small concurrency TA
o regression_1013.1.1 Busy loop repeat 10000
  regression_1013.1.1 OK
o regression_1013.1.2 SHA-256 loop repeat 1000
  regression_1013.1.2 OK
o regression_1013.1.3 Busy loop repeat 10000
  regression_1013.1.3 OK
o regression_1013.1.4 SHA-256 loop repeat 1000
  regression_1013.1.4 OK
o regression_1013.1.5 Busy loop repeat 10000
  regression_1013.1.5 OK
o regression_1013.1.6 SHA-256 loop repeat 1000
  regression_1013.1.6 OK
o regression_1013.1.7 Busy loop repeat 10000
  regression_1013.1.7 OK
o regression_1013.1.8 SHA-256 loop repeat 1000
  regression_1013.1.8 OK
o regression_1013.1.9 Busy loop repeat 10000
  regression_1013.1.9 OK
o regression_1013.1.10 SHA-256 loop repeat 1000
  regression_1013.1.10 OK
o regression_1013.1.11 Busy loop repeat 10000
  regression_1013.1.11 OK
o regression_1013.1.12 SHA-256 loop repeat 1000
  regression_1013.1.12 OK
o regression_1013.1.13 Busy loop repeat 10000
  regression_1013.1.13 OK
o regression_1013.1.14 SHA-256 loop repeat 1000
  regression_1013.1.14 OK
o regression_1013.1.15 Busy loop repeat 10000
  regression_1013.1.15 OK
o regression_1013.1.16 SHA-256 loop repeat 1000
  regression_1013.1.16 OK
o regression_1013.1.17 Busy loop repeat 10000
  regression_1013.1.17 OK
o regression_1013.1.18 SHA-256 loop repeat 1000
  regression_1013.1.18 OK
o regression_1013.1.19 Busy loop repeat 10000
  regression_1013.1.19 OK
o regression_1013.1.20 SHA-256 loop repeat 1000
  regression_1013.1.20 OK
o regression_1013.1.21 Busy loop repeat 10000
  regression_1013.1.21 OK
o regression_1013.1.22 SHA-256 loop repeat 1000
  regression_1013.1.22 OK
o regression_1013.1.23 Busy loop repeat 10000
  regression_1013.1.23 OK
o regression_1013.1.24 SHA-256 loop repeat 1000
  regression_1013.1.24 OK
    Number of parallel threads: 3
    Mean concurrency: 2
  regression_1013.1 OK
o regression_1013.2 Using large concurrency TA
o regression_1013.2.1 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.1 FAILED
o regression_1013.2.2 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.2 FAILED
o regression_1013.2.3 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.3 FAILED
o regression_1013.2.4 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.4 FAILED
o regression_1013.2.5 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.5 FAILED
o regression_1013.2.6 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.6 FAILED
o regression_1013.2.7 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.7 FAILED
o regression_1013.2.8 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.8 FAILED
o regression_1013.2.9 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.9 FAILED
o regression_1013.2.10 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.10 FAILED
o regression_1013.2.11 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.11 FAILED
o regression_1013.2.12 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.12 FAILED
o regression_1013.2.13 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.13 FAILED
o regression_1013.2.14 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.14 FAILED
o regression_1013.2.15 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.15 FAILED
o regression_1013.2.16 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.16 FAILED
o regression_1013.2.17 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.17 FAILED
o regression_1013.2.18 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.18 FAILED
o regression_1013.2.19 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.19 FAILED
o regression_1013.2.20 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.20 FAILED
o regression_1013.2.21 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.21 FAILED
o regression_1013.2.22 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.22 FAILED
o regression_1013.2.23 Busy loop repeat 10000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1118: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.23 FAILED
o regression_1013.2.24 SHA-256 loop repeat 1000
/usr/src/debug/optee-test/3.3.0+gitAUTOINC+0953bf0abb-r0/git/host/xtest/regression_1000.c:1156: arg[n].res has an unexpected value: 0xffff0008 = TEEC_ERROR_ITEM_NOT_FOUND, expected 0x0 = TEEC_SUCCESS
  regression_1013.2.24 FAILED
    Number of parallel threads: 3
    Mean concurrency: 1
  regression_1013.2 FAILED
  regression_1013 FAILED
`
[optee-test-20180121.txt](https://github.com/OP-TEE/optee_os/files/2779032/optee-test-20180121.txt)

What is the meaning of this error ? Do I miss something in my portings

Thanks in advance for your help.

**Comment by jforissier** [comment]
Hi @dleymarie,

It could very well be an "out of memory" condition when loading the TA -- check the debug traces on the secure world console. FYI, the code `TEEC_ERROR_ITEM_NOT_FOUND` is returned instead of `TEE_ERROR_OUT_OF_MEMORY`, due to the fact that we look for TAs in several places, and any error causes the algorithm to skip to the next place; in the end "not found" is returned. Perhaps this could be improved a bit. The code is here: https://github.com/OP-TEE/optee_os/blob/3.3.0/core/arch/arm/kernel/user_ta.c#L840-L852.

If memory is a bit tight on your platform, you may try `CFG_CORE_BGET_BESTFIT=y`.

**Comment by dleymarie** [comment]
Hi @jforissier 

Thanks for your answer.
I tested with our suggestion:

make CFG_TEE_TA_LOG_LEVEL=3 CFG_TEE_CORE_LOG_LEVEL=3 CFG_CORE_BGET_BESTFIT=y

No changes: still same errors in xtest.
Attached output of xtest: 
[optee-xtest-test-regression-1013.txt](https://github.com/OP-TEE/optee_os/files/2783035/optee-xtest-test-regression-1013.txt)
Attached console output of optee kernel:
[optee-console-test-regression-1013.txt](https://github.com/OP-TEE/optee_os/files/2783040/optee-console-test-regression-1013.txt)

We are running with chain loading: U-Boot loads a FIT image with optee-os, linux kernel, linux dtb. U-Boot launches optee-os as Linux kernel, optee-os launches Linux kernel.

Thanks in advance for your help.

**Comment by jforissier** [comment]
> D/TC:? 1 load_elf:829 res=0xffff000c

This is `TEE_ERROR_OUT_OF_MEMORY` ;-)

**Comment by dleymarie** [comment]
Thanks !
I reserved 4 MiB for OP-TEE:
1 MiB for TEE 0x100000
>3 MiB for TA 0x3a8000
My board has only 128 MiB RAM. This RAM is used to run Linux/OP-TEE and has to be shared with another CPU (for ~3 MiB).
It should not be possible to increase easily size allocated to optee. Does we can live with this amount of RAM for optee ?

**Comment by dleymarie** [comment]
I see that test 1013.2 can be disabled with option CFG_PAGED_USER_TA.
What is the meaming of this option ?
Is it interesting to use this option on my configuration ?

**Comment by jforissier** [comment]
> I see that test 1013.2 can be disabled with option CFG_PAGED_USER_TA.
> What is the meaning of this option ?

`CFG_PAGED_USER_TA` (and `CFG_WITH_PAGER`, which it depends on) is used on platforms that have a moderate amount of SRAM, and a much larger amount of DRAM, and still want to be able to run secure code in the SRAM only for more security. Code and data will then be paged in and out of SRAM, encrypted and/or signed as needed.

The fact that `CFG_PAGED_USER_TA` disables 1013.2 is just because when this option is enabled there is not enough secure heap in the upstream platforms to run that particular test.

> Is it interesting to use this option on my configuration ?

I don't think so.

Perhaps we should use a more specific flag for disabling 1013.2, such as `CFG_XTEST_NO_1013_2`?

**Comment by dleymarie** [comment]
Thanks you for your advices. They were very useful.
