### ISSUE TITLE
out_of_place_write() return uninitialized value?

### ISSUE THREAD

**Issue by sticfeynman** [OP-TEE/optee_os#2760]
For the out_of_place_write() in tee_ree_fs.c, since the res is no initialized, is it possible somehow it takes the false branches of all the checks and it goes all the way down and return the uninitialized res?

**Comment by jforissier** [comment]
No.

**Comment by jbech-linaro** [comment]
Agree with Jerome, the current code seems legit, but ... for clarity and to avoid making this kind of mistake if the code changes slightly in the future, I wouldn't mind setting it to some default value.

**Comment by sticfeynman** [comment]
I notice that there is a statement in the README.md, i.e. Automatic variables should always be initialized.
It is properly a good practice to give it a default value.

**Comment by jbech-linaro** [comment]
@sticfeynman yes, we've just recently added that to the docs and we have a more in depth internal discussion regarding that. In the end we must make sure that all variables have a defined value to avoid ending up with potential security issues. If that needs to be done manually or by tools (compilers) is another question. But what we've seen is that it seems hard to trust compilers. So, by all means, feel free to submit a patch for this.
