### ISSUE TITLE
Race condition in wait queue code leads to NW lockup

### ISSUE THREAD

**Issue by lorc** [OP-TEE/optee_os#2761]
During debugging issue with NW lockup in IBART test for #2370 I have found race in wait queue handling.
Please take look at the log:

```
  7444:  [000097173013] D/TC:? 2 tee_ta_close_session:399 Destroy session
  7445:  *[000097176941] D/TC:? 0 tee_ta_close_session:380 tee_ta_close_session(0x3f03b890)
  7446:  *[000097180162] D/TC:? 2 tee_ta_close_session:425 Destroy TA ctx
  7447:  *[000097188617] D/TC:? 0 __wq_rpc:39 sleep thread 0 0x3f0121a8 -1
  7448:  *[000097195491] D/TC:? 2 __wq_rpc:39 wake  thread 0 0x3f0121a8 -3
  7449:  *[000097202467] D/TC:? 0 thread_rpc_cmd:1581 Thread RPC cmd 4
  7450:  *[000097209448] D/TC:? 2 thread_rpc_cmd:1581 Thread RPC cmd 4
```

I added timestamp printing, because due to contention, logs are printed out of order.
Timestamps are raw values from generic timer counter.

Please note that last message (`  7450:  *[000097209448] D/TC:? 2 thread_rpc_cmd:1581 Thread RPC cmd 4`) has earlier timestamp than previous one. 

So, trace messages should be printed in this order:

```
  7444:  [000097173013] D/TC:? 2 tee_ta_close_session:399 Destroy session
  7445:  *[000097176941] D/TC:? 0 tee_ta_close_session:380 tee_ta_close_session(0x3f03b890)
  7446:  *[000097180162] D/TC:? 2 tee_ta_close_session:425 Destroy TA ctx
  7447:  *[000097188617] D/TC:? 0 __wq_rpc:39 sleep thread 0 0x3f0121a8 -1
  7448:  *[000097195491] D/TC:? 2 __wq_rpc:39 wake  thread 0 0x3f0121a8 -3
  7450:  *[000097209448] D/TC:? 2 thread_rpc_cmd:1581 Thread RPC cmd 4
  7449:  *[000097202467] D/TC:? 0 thread_rpc_cmd:1581 Thread RPC cmd 4
```

As you can see, Thread 0 tries to sleep, but it gets instantly woken by Thread 2. Now, they both are racing to deliver their RPCs to the normal world. 

And it happens, that Thread 2 calls `OPTEE_RPC_WAIT_QUEUE_WAKEUP`  **before** Thread 0 delivers `OPTEE_RPC_WAIT_QUEUE_SLEEP`. So, Thread 0 gets blocked and there are no one, who can wake it up.

Please note that in this  lockup can happen even if there is no tight race between two cores.
In normal world thread that receives `OPTEE_RPC_WAIT_QUEUE_SLEEP` can be preempted right after return from SW, so it have no chance to block on completion, before thread that receives `OPTEE_RPC_WAIT_QUEUE_WAKEUP` signals to that completion.

I see only one way to fix this race: OP-TEE should introduce monotonically growing "tickets" that are sent along with `OPTEE_MSG_RPC_CMD_WAIT_QUEUE` calls. And if Normal World sees a ticket that is smaller than previous one - it does not tries to block on completion and returns immediately.

**Comment by jforissier** [comment]
Hi @lorc,

The messages are not out-of-order... 000097209448 > 000097202467.

This doesn't automatically mean the rest of your analysis is wrong however.

**Comment by lorc** [comment]
Ooop, yes, you are right. I looked only at last 3 digits :/

**Comment by lorc** [comment]
Actually, I came up with the easier fix: replace completion with semaphore in the Linux driver.

**Comment by jbech-linaro** [comment]
> Actually, I came up with the easier fix: replace completion with semaphore in the Linux driver.

Anything you want to send upstream / to Jens?

**Comment by jforissier** [comment]
> > Actually, I came up with the easier fix: replace completion with semaphore in the Linux driver.

> Anything you want to send upstream / to Jens?

I'd like to try it, too.

**Comment by jenswi-linaro** [comment]
I'm not convinced that's the problem. The `struct wq_entry` is allocated and initialized with `wq_entry_get()` which is used by both `wq_sleep()` and `wq_wakeup()`. So the order shouldn't matter here.

**Comment by lorc** [comment]
Apparently I was mistaken.

At first I tried simple workaround that delays any wakeups if there was recent suspend and it didn't helped.

Then I revisited documentation on completions in linux kernel I found that you can call `complete()` before `wait_for_completion()` and it would not block. 

So yeah, no race there. Sorry for the noise.
