### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by duduscript** [OP-TEE/optee_os#2765]
Hi all,
I am writing a CA but I am failed to build it, I need some crypt function so I just follow code in optee_test. I compile it successfully but failed to build it.

The log is as follows, I did add the path of xtest_helpers.h to CFLAGS. Do I need to add some other path to some other flags? This problem has bothered me all day.

-- Build files have been written to: /home/duduscript/optee_repo/out-br/build/optee_examples-1.0
>>> optee_examples 1.0 Building
PATH="/home/duduscript/optee_repo/out-br/host/bin:/home/duduscript/optee_repo/out-br/host/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/duduscript/.fzf/bin"  /usr/bin/make -j5  -C /home/duduscript/optee_repo/out-br/build/optee_examples-1.0/
[ 14%] Built target acipher
[ 28%] Built target display
[ 50%] Built target aes
[ 57%] Built target hotp
[ 64%] Building C object hello_world/CMakeFiles/hello_world.dir/host/main.c.o
[ 78%] Built target random
[ 92%] Built target secure_storage
/home/duduscript/optee_repo/out-br/build/optee_examples-1.0/hello_world/host/main.c:35:10: fatal error: xtest_helpers.h: No such file or directory
 #include <xtest_helpers.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [hello_world/CMakeFiles/hello_world.dir/host/main.c.o] Error 1
make[4]: *** [hello_world/CMakeFiles/hello_world.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [/home/duduscript/optee_repo/out-br/build/optee_examples-1.0/.stamp_built] Error 2
make[1]: *** [_all] Error 2
make[1]: Leaving directory `/home/duduscript/optee_repo/out-br'
make: *** [buildroot] Error 2

**Comment by duduscript** [comment]
Thank you @jbech-linaro ,
I am currently in vacation now and  I can not access the computer in my lab, I will try it two weeks later.

**Comment by jbech-linaro** [comment]
Alright, I'm closing the ticket, if you're still having issues/question, please just re-open the ticket.
