### ISSUE TITLE
Cannot obtain IP address for eth0 on RPI 3

### ISSUE THREAD

**Issue by jedichen121** [OP-TEE/optee_os#2767]
I was trying to setup NFS to use with raspberry pi 3 with build 3.3 following this [guide](https://github.com/OP-TEE/build/blob/master/docs/rpi3.md#5-nfs-boot). However, I couldn't obtain an IP address when using wired connection. I found issue #1367 and used `ifconfig eth0 up`, but still the `ifconfig` results showed no ip address. 

```
# ifconfig
eth0      Link encap:Ethernet  HWaddr B8:27:EB:DA:46:B7  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:201 (201.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

I also tried to edit the `/etc/network/interfaces` file, adding 
```
auto eth0
iface eth0 inet dhcp
```
It didn't help and I could see in the boot message showing
```
Starting network: Segmentation fault
FAIL
```
Using `ifup eth0` gave the same segmentation fault. 

Any help would be appreciated. Thank you.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
