### ISSUE TITLE
License of the linux and U-Boot OP-TEE Driver

### ISSUE THREAD

**Issue by Emantor** [OP-TEE/optee_os#2771]
While rebasing a testing patch for the Barebox bootloader to support OP-TEE, it was noticed that the file which includes the `struct optee_header` is BSD-2 clause licensed.
Looking into the kernel source files for the OP-TEE driver (/drivers/tee/optee), `optee_msg.h` and `optee_smc.h` are also licensed under the BSD-2 clause license. This contradicts the [The Linux kernel licensing rules](https://www.kernel.org/doc/html/latest/process/license-rules.html?highlight=license#linux-kernel-licensing-rules) which state that all files are either licensed under a GPL-2.0 license or may be dual licensed. The OP-TEE header files do not carry a dual licensing clause.
According to my understanding this results in a license incompatibility unless the kernel (in binary form) is explicitly shipped with the license information contained in the optee header files.

Furthermore I would like to know whether the information contained in the documentation is licensed under the BSD-2 clause license and the copyright for the `struct optee_header` definition is Linaros license, because the LICENSE file states that only source files are covered under the license thereafter.

Thank you

**Comment by jenswi-linaro** [comment]
It's a mistake, the BSD 2-clause licensed .h files in the Linux kernel and in U-Boot are supposed to be dual licensed.

Documentation, in which project?

**Comment by Emantor** [comment]
The documentation in (Optee Design)[https://github.com/OP-TEE/optee_os/blob/241593c54ee675a8351a98bbc92283151c11ac38/documentation/optee_design.md]

**Comment by jenswi-linaro** [comment]
I guess we should remove the word "source" at the line https://github.com/OP-TEE/optee_os/blob/3ec2cabcdcff388a0707f1cd27c02f78a690d421/LICENSE#L1

I don't see a problem with dual licensing those struct definitions. However, it will probably not be done inside the optee_os git.

Given that all the files in question are copyright Linaro I think the easiest way forward is for someone at Linaro to post the needed patches clarifying the license etc. @jbech-linaro, @jforissier, do you agree?

**Comment by jforissier** [comment]
@jenswi-linaro agreed with each and every point.

**Comment by Emantor** [comment]
Gentle ping, I'd like the dual license for the header definition to finish and upstream the bootloader patch.

**Comment by jforissier** [comment]
I can take care of this. To be clear, this is what is needed IIUC:

1. One patch for optee_os to remove the word "source" in optee_os/LICENSE ("each file" instead of "each source file")
2. One patch for the Linux kernel: `drivers/tee/optee/optee_{msg,smc}.h` should be `// SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)`
3. One patch for U-Boot, same as 2.

Correct?

@Emantor may I add your `Reported-by:` to the patches?

**Comment by Emantor** [comment]
Yes and I would like to suggest:
  
  4. provide the struct definitions in [Partitioning of the binary](https://github.com/OP-TEE/optee_os/blob/241593c54ee675a8351a98bbc92283151c11ac38/documentation/optee_design.md#partitioning-of-the-binary) under a dual license compatible with GPL2

**Comment by jenswi-linaro** [comment]
Thanks for taking care of this @jforissier

**Comment by jforissier** [comment]
> 2. One patch for the Linux kernel: `drivers/tee/optee/optee_{msg,smc}.h` should be `// SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)`
> 3. One patch for U-Boot, same as 2.

Actually, why would we want to dual-license the files in U-Boot? They are `BSD-2-Clause` and this sounds fine to me.

**Comment by jforissier** [comment]
Linux patch submitted: https://lore.kernel.org/patchwork/patch/1039990/

**Comment by Emantor** [comment]
And the patch has hit Linus tree, thanks a lot for your efforts.
