### ISSUE TITLE
xtest fail over NFS on RPI 3

### ISSUE THREAD

**Issue by jedichen121** [OP-TEE/optee_os#2773]
I'm trying to use NFS on Raspberry Pi 3 B. I was able to load the file system but couldn't run xtest anymore. During boot, tee-supplicant failed to load:
```
Starting tee-supplicant... ERR [91] TSUP:main:684: error tee_supp_fs_init
FAIL
```
The xtest would stuck at regression 1004. When killing xtest, the following error message showed:
```
regression_1004 Test User Crypt TA
D/TC:? 0 tee_ta_open_session:540 init session failed 0xffff0008
```
I'm using OP-TEE 3.2 and I checked the `tee_supp_fs.c` file is the same as the latest version. I was able to pin the problem to `if (mkdir(path, mode) != 0 && errno != EEXIST)` in `static int do_mkdir(const char *path, mode_t mode)` which returned -1 (path `/data`). But I'm not sure why this would fail. Is this a bug or was I using NFS in a wrong way? 

Thank you.

**Comment by lorc** [comment]
Hi @jedichen121. I'm using OP-TEE on NFS without any issues. But on different platform.
Can you try to create `/data` manually? E.g. `mkdir /data/`? From RPI side, of course.

**Comment by jedichen121** [comment]
When I generated the NFS file system using the `rootfs.cpio.gz`, the foler `/data` is already there, as well as `/data/tee`. I'm thinking of deleting these two folders and see if it can work, or just delete the `tee_supp_fs_init()` function. Since all it does is create the two folders, which are already there. 

I was also wondering whether `mkdir` failed because the folders were already there. But the same code runs perfect in SD card.

**Comment by jforissier** [comment]
@jedichen121 sounds like some permission problem, perhaps the NFS mount restricts the permissions somehow. What is `errno` after `mkdir` has failed? Or, instead of chasing `errno`, you may want to run `tee-supplicant` with `strace`.

**Comment by jedichen121** [comment]
I used the command in [rpi3.md](https://github.com/OP-TEE/build/blob/master/docs/rpi3.md#51-configure-nfs) to create the shared folder path. 
`/srv/nfs/rpi 192.168.1.0/24(rw,sync,no_root_squash,no_subtree_check)
`
I'll check the `errno` and report back later.

**Comment by jedichen121** [comment]
@jforissier Just like you said, the `errno` is `EACCES`: permission problem. 

My temporary work around is ignore the error from `tee_supp_fs_init()` (forcing the function to return 0) and then the xtest will run. However, there are still cases where it will fail:
```
20975 subtests of which 156 failed
89 test cases of which 22 failed
```
I also tried to run `tee-supplicant` with `strace` on NFS. But this time the `errno` value was `EEXIST`, which meant `mkdir` is actually running fine. Now when I ran `xtest`, the result was much better, but not perfect:
```
22017 subtests of which 2 failed
89 test cases of which 2 failed
```
The two failed were 
```
regression_1020 FAILED first error at regression_1000.c:1469
...
regression_4006.13 FAILED first error at regression_4000.c:4034
```

**Comment by jedichen121** [comment]
@jbech-linaro That would be awesome. 

I noticed there might be something wrong about editing [u-boot.env via UART](https://github.com/OP-TEE/build/blob/master/docs/rpi3.md#542-edit-u-bootenv-via-uart) in the doc. The parameter `serverip` does not work in my case. Instead, I used `nfsserverip`. The reference is [here](https://github.com/OP-TEE/build/blob/master/rpi3/firmware/uboot.env.txt#L39).

**Comment by jbech-linaro** [comment]
Some updates, the initial issue in the thread ...
```bash
Starting tee-supplicant... ERR [91] TSUP:main:684: error tee_supp_fs_init
FAIL
```

What happens is (from strace)
```bash
mkdirat(AT_FDCWD, "/data", 0700)        = -1 EACCES (Permission denied)
gettid()                                = 93
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(5, 1), ...}) = 0
ioctl(1, TCGETS, {B115200 opost isig icanon echo ...}) = 0
write(1, "ERR [93] TSUP:main:684: error te"..., 47ERR [93] TSUP:main:684: error tee_supp_fs_init
) = 47
openat(AT_FDCWD, "/data/tee/logs/teec.log", O_WRONLY|O_CREAT|O_APPEND, 0666) = -1 ENOENT (No such file or directory)
exit_group(1)                           = ?
```
I.e, permission issue as we've already touched. To me it looks like we should change to `root:tee` and `chmod 0770` on `/data`. That's what I did in my branch [1] I've added a patch [2] for that. With that tee-supplicant runs as expected.

```bash
+-----------------------------------------------------
22262 subtests of which 168 failed
93 test cases of which 20 failed
0 test cases were skipped
TEE test application done!
```

[1] https://github.com/jbech-linaro/build/commits/rpi3-nfs-fixes
[2] https://github.com/jbech-linaro/build/commit/c39dfe908ae88e0edc659b8c3d4275cef39e96d9

**Comment by jforissier** [comment]
Setting ownership of `/data` to `root:tee` doesn't sound right, because it is unrelated to `tee`. One could decide to use a different, existing parent directory to host the `tee` directory, for instance.

Besides, the QEMU platform works fine with these permissions:
https://github.com/OP-TEE/build/blob/3.4.0/br-ext/package/optee_client/optee_client.mk#L31-L34

...and with tee-supplicant running as `tee:tee`:
https://github.com/OP-TEE/build/blob/3.4.0/br-ext/package/optee_client/S30optee#L23

So, what is different with Rpi3? What are the ownership/permissions on `/data` and `/data/tee`? Do they exist before `tee-supplicant` is started? Is tee-supplicant run as `tee:tee`?

**Comment by jedichen121** [comment]
@jbech-linaro Thank you. I'll try it out. 
>```
> +-----------------------------------------------------
> 22262 subtests of which 168 failed
> 93 test cases of which 20 failed
> 0 test cases were skipped
> TEE test application done!
> ```
I saw in your previous [reply](https://github.com/OP-TEE/optee_os/issues/2773#issuecomment-459699704) the xtest did not pass all tests. Is this considered acceptable?

**Comment by jbech-linaro** [comment]
Holy smokes, no that's not acceptable. I must have starred me blind on something. I'm not at a computer now, but I suspect socket tests are failing, I'll dig into that next week.  Thanks for catching this big mistake.

**Comment by jbech-linaro** [comment]
I've tested various combinations:
1. Re-run xtest several times, xtest OK.
2. Re-boot and re-run several time, xtest OK.
3. rm -rf /data && reboot, xtest OK.

So I must have picked an old log from a wrong console when pasting the failing log.

**Comment by jedichen121** [comment]
I hate to say this, but I was not able to reproduce the xtest result over NFS. I created a new folder and fetched the latest code and rebuild from scratch. I've also tried to rerun xtest several teimes, reboot and rerun, and rm -rf /data and rerun. All produces the same result: 
```
22564 subtests of which 46 failed
93 test cases of which 9 failed
0 test cases were skipped
TEE test application done!
```
Some failed test cases include 1020, 4006, 6010, 6017 6018. I'm also not sure why the total number of test cases we run are different. Am I running some older version code? I've included all the latest git log commit for the folders I have. 

```
arm-trusted-firmware: 023bc019
firmware: 3fb63c4
optee_benchmark: ecba70dd
optee_client: 3f28557
optee_os: 4d22155
build: 43791be
linux: d639e3a
optee_test: 373386
buildroot: 339d55
optee_examples: db08da1
u-boot: aac0c29

```

**Comment by jedichen121** [comment]
@jbech-linaro Can you verify we are running the same version of codes? If software is the same and we are both using Raspberry pi 3B, why would the number of test cases be different? Thank you.

**Comment by jbech-linaro** [comment]
I'm sorry to say @jedichen121 , but it'll take some time until I have some spare time to fiddle with RPi3 again. I have other areas that I need to work with right now (most likely I won't try/use it until next release which is in April).

**Comment by jedichen121** [comment]
@jbech-linaro That's fine. Totally understand. I'm currently running linaro rootfs directly on SD card. Thanks to the help of @msa2 the xtest can pass all tests. If I got time to work on NFS and figured out the problem I'll let you know.
