### ISSUE TITLE
Looks like this error return will cause memory leak.

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_os#2776]
https://github.com/OP-TEE/optee_os/blob/3ec2cabcdcff388a0707f1cd27c02f78a690d421/core/arch/arm/kernel/ree_fs_ta.c#L141

I think code should be:
```
if (ta_size < SHDR_GET_SIZE(shdr) + sizeof(bs_hdr)) {
	res = TEE_ERROR_SECURITY;
	goto error_free_hash;
}
```

**Comment by jforissier** [comment]
@sahilnxp good catch! Would you create a PR?

**Comment by sahilnxp** [comment]
@jforissier  Creatd a pull request https://github.com/OP-TEE/optee_os/pull/2777
