### ISSUE TITLE
 when building qemu "qemu/out-br/build/host-acl-2.2.53/.stamp_downloaded' failed" I am getting this error

### ISSUE THREAD

**Issue by akbarsaleemt** [OP-TEE/optee_os#2782]
Hi Team,
 when building qemu "qemu/out-br/build/host-acl-2.2.53/.stamp_downloaded' failed" I am getting this error.
/***************************************************************************************************************/
make[1]: Leaving directory '/home/takkaakb/qemu/buildroot'
make[1]: Entering directory '/home/takkaakb/qemu/out-br'
umask 0022 && make -C /home/takkaakb/qemu/buildroot O=/home/takkaakb/qemu/out-br/. all
/usr/bin/make -j1 O=/home/takkaakb/qemu/out-br HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" silentoldconfig
  GEN     /home/takkaakb/qemu/out-br/Makefile
>>> host-acl 2.2.53 Downloading
--2019-01-31 09:48:11--  http://download.savannah.gnu.org/releases/acl/acl-2.2.53.tar.gz
Resolving download.savannah.gnu.org (download.savannah.gnu.org)... 209.51.188.200, 2001:470:142:5::200
Connecting to download.savannah.gnu.org (download.savannah.gnu.org)|209.51.188.200|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-01-31 09:48:13--  (try: 2)  http://download.savannah.gnu.org/releases/acl/acl-2.2.53.tar.gz
Connecting to download.savannah.gnu.org (download.savannah.gnu.org)|209.51.188.200|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-01-31 09:48:15--  (try: 3)  http://download.savannah.gnu.org/releases/acl/acl-2.2.53.tar.gz
Connecting to download.savannah.gnu.org (download.savannah.gnu.org)|209.51.188.200|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Giving up.

--2019-01-31 09:48:16--  http://sources.buildroot.net/acl/acl-2.2.53.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.25.211.19, 104.25.210.19, 2606:4700:20::6819:d313, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.211.19|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-01-31 09:48:17--  (try: 2)  http://sources.buildroot.net/acl/acl-2.2.53.tar.gz
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.211.19|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-01-31 09:48:19--  (try: 3)  http://sources.buildroot.net/acl/acl-2.2.53.tar.gz
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.211.19|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Giving up.

--2019-01-31 09:48:19--  http://sources.buildroot.net/acl-2.2.53.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.25.211.19, 104.25.210.19, 2606:4700:20::6819:d313, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.211.19|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-01-31 09:48:20--  (try: 2)  http://sources.buildroot.net/acl-2.2.53.tar.gz
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.211.19|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-01-31 09:48:22--  (try: 3)  http://sources.buildroot.net/acl-2.2.53.tar.gz
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.211.19|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Giving up.

package/pkg-generic.mk:135: recipe for target '/home/takkaakb/qemu/out-br/build/host-acl-2.2.53/.stamp_downloaded' failed
make[2]: *** [/home/takkaakb/qemu/out-br/build/host-acl-2.2.53/.stamp_downloaded] Error 1
Makefile:16: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/takkaakb/qemu/out-br'
common.mk:202: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2
/****************************************************************************************************/

Thank you,

**Comment by jbech-linaro** [comment]
Seems like either
a) Server was down
b) Your internet connection was down.

I suppose you did try just browse http://download.savannah.gnu.org/ and http://sources.buildroot.net/ and that worked OK? Since we are talking about two independent URLs, I'm pretty sure it is "b" that is the issue.

When you have connection again. Then before trying to rebuild again also do a
```bash
$ rm -rf /home/takkaakb/qemu/out-br
```
just to ensure that there are no files in some kind of intermediate state.

**Comment by akbarsaleemt** [comment]
OK. Thank you

**Comment by jbech-linaro** [comment]
I'd imagine that this is no longer an issue, so I'll close the ticket.
