### ISSUE TITLE
Attesting normal world binary

### ISSUE THREAD

**Issue by AlessandroVisintin** [OP-TEE/optee_os#2785]
Hi all,
for a project I would like to attest the binary of a function that resides in the normal world using a Trusted Application. The idea is basically to access from the secure world the memory location of the function and take an hash of the binary.

Could be also the function itself, once it is loaded for execution, that first calls a Trusted App passing a pointer for checking the loaded binary.

Is this somehow possible to do with OPTEE?
Already tried passing directly a pointer to the secure world but it resulted in a segmentation fault.

Thanks a lot.

**Comment by lorc** [comment]
Yes, I think it is possible to some extent. You can't pass pointer directly to OP-TEE but you can share portion of process's memory with OP-TEE with `TEEC_RegisterSharedMemory()` function. 

I never tried to share `.text` section but I can't see why this should not work.

**Comment by AlessandroVisintin** [comment]
Yeah it works, I have tried to register the area of memory in which the normal world puts a string of characters and I am able to print that string inside the Trusted Application. Now I should accomplish my task instead sharing the pointer to the function I am trying to attest the binary. I will try and let you know.

Thank a lot for the suggestion!

**Comment by AlessandroVisintin** [comment]
Alright, just changing the pointer to a function pointer I am able to see the binary of the function itself.
Thanks a lot again.
