### ISSUE TITLE
When I tried to build Qemu i got the following error usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory

### ISSUE THREAD

**Issue by akbarsaleemt** [OP-TEE/optee_os#2786]
Hi Team,
When I tried to build Qemu i got the following 
/******************************************************************************************************/
usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
           ^~~~~~~~~~~~~~~~
compilation terminated.
scripts/Makefile.build:197: recipe for target 'applets/applets.o' failed
make[4]: *** [applets/applets.o] Error 1
Makefile:372: recipe for target 'applets_dir' failed
make[3]: *** [applets_dir] Error 2
package/pkg-generic.mk:229: recipe for target '/home/takkaakb/QEMU/out-br/build/busybox-1.29.2/.stamp_built' failed
make[2]: *** [/home/takkaakb/QEMU/out-br/build/busybox-1.29.2/.stamp_built] Error 2
/****************************************************************************************/
thank you.

**Comment by jforissier** [comment]
http://lmgtfy.com/?q=fatal+error%3A+gnu%2Fstubs-32.h%3A+No+such+file+or+directory

https://stackoverflow.com/questions/7412548/error-gnu-stubs-32-h-no-such-file-or-directory-while-compiling-nachos-source

**Comment by jbech-linaro** [comment]
Just some additional comments. It's important that you install **all** prerequisites as stated in build.git and also, QEMU is the platform that is least likely to not work with OP-TEE since each and every pull request is built for and tested using QEMU on Travis (https://travis-ci.org/OP-TEE/optee_os/).
