### ISSUE TITLE
P2P protocol with trusted application

### ISSUE THREAD

**Issue by AlessandroVisintin** [OP-TEE/optee_os#2788]
Hi all,
I have to implement a P2P protocol using OPTEE as trusted base for securing some parts of it but I am finding some problems in understanding what I could place inside the secure world. For sure nobody outside the secure world must be able to read the messages exchanged by the p2p, so the data and the functions for reading/writing them must reside inside the secure world. Can I also place the client and the server inside the secure world? Is there a way for opening sockets inside of it and managing multiple connections (for the server part) ?

The best thing would be to place all the functions inside the secure world so the normal world would just need to start the p2p protocol and would be completely unaware of it.

Thanks in advance for the help.

**Comment by igoropaniuk** [comment]
@AlessandroVisintin

Here is an example of using sockets (as TCP/UDP clients) in a Trusted Application (unfortunately, there is no support for TLS sockets yet):
https://github.com/OP-TEE/optee_test/blob/master/ta/socket/ta_entry.c

> Can I also place the client and the server inside the secure world?

You can't change socket state to listeninng (based on the details of implementation I saw and information GlobalPlatform TEE_Sockets_API_v1.0.1 spec), so subsequently you can't accept new connections.
Also you need I/O event notification facility in TEE (like `epoll`, which doesn't exist in OP-TEE) to be able to handle effectively multiple connections.

**Comment by AlessandroVisintin** [comment]
Ok, thank you for the help. So right now OPTEE just supports opening socket inside the secure world, meaning that I could probably place the client inside of it. What about a mixed approach with the server placed in the normal world and the client inside the secure world? Is it feasible in your opinion? This setting could be good for my project because I just need to compel the client to work, while the server doesn't need any kind of protection.

**Comment by AlessandroVisintin** [comment]
Ok, thanks a lot again for your help. I will simply put the client in the normal world and compel it to run using another approach.
