### ISSUE TITLE
queries related some ECC curves supported (or not) in OPTEE

### ISSUE THREAD

**Issue by Sourabhharman** [OP-TEE/optee_os#2789]
Hi Crypto experts,
We have few queries related to the ECC curves supported.
Does OPTEE supports these curves: secp256r1, secp256k1, secp384r1, secp384k1 and curve25519?
Does secp256r1 & secp384r1 ( NIST/SECG curve over n bit prime field) is similar to optee supported curve TEE_ECC_CURVE_NIST_P256 & TEE_ECC_CURVE_NIST_P384 respectively?

I already refered to the thread https://github.com/OP-TEE/optee_os/issues/1988

Thanks in advance.

**Comment by jforissier** [comment]
Hi @Sourabhharman,

The curve parameters for  `TEE_ECC_CURVE_NIST_P256` and `TEE_ECC_CURVE_NIST_P384` are here: https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/pk/ecc/ecc.c#L111-L132
AFAICT, this is the "random" version of the curves (secp256r1 and secp384r1) and is what is required by the GlobalPlatform specification.

Curve25519 is not supported (yet).
