### ISSUE TITLE
Extending QEMU OPTEE_Client 

### ISSUE THREAD

**Issue by jiwonjoung** [OP-TEE/optee_os#2794]
#2617 

Reopening this issue 

Basically, I want to build OPTEE OS with my custom version of GPSD. 
This question might be rephrased to more generally ask, how can I modify the file system in the normal and secure worlds?

**Comment by jenswi-linaro** [comment]
If you're not integrating this in an already present system I'd suggest adding a local buildroot package to build and install GPSD along with everything else.
