### ISSUE TITLE
64-bit ARMv8 GICV3 OPTEE porting issue

### ISSUE THREAD

**Issue by vtcao297** [OP-TEE/optee_os#2795]
I'm trying to port OPTEE to work for a new SoC that is based on Cortex-A53 that has a GICV3 interrupt controller.  Using the latest OPTEE v3.4 release, A-TF 1.6 and U-Boot 2018.11, i'm able to have an application communicate with OPTEE TA using fine.  The issue comes about when Linux OS is executing, a simple xtest 1001 will stall it seems when doing a open optee session command with standard smc call. 

I traced it to the handle_interrupt_exception fiq_aarch64 routine in A-TF bl31 runtime_exception.S file where it seems to just continuously loop over and over again without being able to return from el3_exit.  From the  optee interrupt documentation, it states that:

"For ARM GICv3 mode, foreign interrupt is sent as FIQ which could be handled by either secure world (aarch32 Monitor mode or aarch64 EL3) or normal world. ARM GICv3 mode can be enabled by setting CFG_ARM_GICV3=y."

So my questions, is there something specific that i need to do in BL31 or normal world to handle this fiq interrupt from OPTEE?  I've been stuck on this issue for quite sometime and not sure how to move forward.  The SMC and interrupt handling seems to work fine in U-Boot.

I have enable CFG_GIC and CFG_ARM_GICV3 in OPTEE based on some other GICV3 platforms and have enabled GICV3 support in the Linux kernel.

**Comment by jforissier** [comment]
Hi @vtcao297,

I don't know much about GICv3, but this reminds me of commit: 41985789f3b.
I suppose something has to be done in TF-A  in order to forward the interrupt to OP-TEE.

**Comment by jenswi-linaro** [comment]
I guess you're not receiving/serving any secure interrupts in OP-TEE, you just want to forward non-secure interrupts to normal world. This is something that works in our FVP target. Perhaps you're missing something in the TF-A configuration?

**Comment by sandeepbrcm** [comment]
@vtcao297 
you can do it now by defining the irq numbers you want to be G1S   as                           PLAT_ARM_G1S_IRQ_PROPS    in platform_def.h   in TFA.

GICv3:
 while you are in op-tee (EL1S)
1. G1NS  interrupts ( all linux interrupts)  :  will come as FIQ  ie. elx_fiq  and will be routed back to linux/ree.  the case @jenswi-linaro  mentioned.
2. G0 interrupts ( all interrupts intended to be handled in EL3 eg:  SDEI spec) will be routed back to BL31.
3. G1S interrupts ( op-tee secure interrupts): will come as elx_irq and will be handled in optee.
1 and 2 works fine op-tee 3.3+ . for 3 you need to configure the desired interrupts to be actually G1S.

**Comment by vtcao297** [comment]
I have already done that prior and defined the G0 and G1S interrupt in A-TF for GICV3 like below based on the some of the example from the K3 and FVP platform.  Is there something else that could be missing?  Where does G1NS need to be defined?  BTW, does the OPTEE UBoot interface not generate G1NS interrupt because i was tracing through the optee smc calls in uBoot environments and not once does the handle_interrupt_exception fiq_aarch64 routine in A-TF bl31 runtime_exception.S get called for std_smc, but when running in linux handle_interrupt_exception fiq_aarch64 does get call and this is where it gets stuck.

#define PLATFORM_INTERRUPT_PROPS {							\
	/* G0 interrupts */											\
														\
	/* SGI0 */												\
	INTR_PROP_DESC(SOC_IRQ_SEC_SGI_0, GIC_HIGHEST_SEC_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_EDGE),		\
														\
	/* SGI6 */												\
	INTR_PROP_DESC(SOC_IRQ_SEC_SGI_6, GIC_HIGHEST_SEC_PRIORITY, INTR_GROUP0, GIC_INTR_CFG_EDGE),		\
														\
	/* G1S interrupts */											\
														\
	/* Timer */												\
	INTR_PROP_DESC(SOC_IRQ_SEC_PHY_TIMER, GIC_HIGHEST_SEC_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_LEVEL),	\
														\
	/* SGI1 */												\
	INTR_PROP_DESC(SOC_IRQ_SEC_SGI_1, GIC_HIGHEST_SEC_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_EDGE),		\
														\
	/* SGI2 */												\
	INTR_PROP_DESC(SOC_IRQ_SEC_SGI_2, GIC_HIGHEST_SEC_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_EDGE),		\
														\
	/* SGI3 */												\
	INTR_PROP_DESC(SOC_IRQ_SEC_SGI_3, GIC_HIGHEST_SEC_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_EDGE),		\
														\
	/* SGI4 */												\
	INTR_PROP_DESC(SOC_IRQ_SEC_SGI_4, GIC_HIGHEST_SEC_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_EDGE),		\
														\
	/* SGI5 */												\
	INTR_PROP_DESC(SOC_IRQ_SEC_SGI_5, GIC_HIGHEST_SEC_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_EDGE),		\
														\
	/* SGI7 */												\
	INTR_PROP_DESC(SOC_IRQ_SEC_SGI_7, GIC_HIGHEST_SEC_PRIORITY, INTR_GROUP1S, GIC_INTR_CFG_EDGE)		\
}

**Comment by sandeepbrcm** [comment]
looks like you only need G1NS which is configured by default in atf.  nothing to be done in op-tee though.  

you have some settings wrong in atf probably.  standard u-boot do not enable interrupts so you wont see fiq/irq.

**Comment by vtcao297** [comment]
Update:  It looks like the issue was in our pre-silicon simulator of our SOC.  The GIC-500 model wasn't handling interrupt handling correctly.  After some refactor of the GIC-500 model code, the issue is resolved.  Thanks everyone for the input and help.
