### ISSUE TITLE
Add some new libraries

### ISSUE THREAD

**Issue by fanguannan0706** [OP-TEE/optee_os#280]
Hi,
I'd like to add some new libraries to the optee, so I can build some trusted app using them. But I don't know how to do this.

**Comment by pascal-brand-st** [comment]
Best is to link your TA with your library. In the makefile of your TA, you should have something similar to

    include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk

Below including `ta_dev_kit.mk`, you can then add a directive similar to that one:

    ldargs-$(binary).elf += <mylib>

**Comment by jbech-linaro** [comment]
@fanguannan0706 is @pascal-brand-st recommendation sufficient for you? Can we close this issue?

**Comment by pascal-brand-st-dev** [comment]
@fanguannan0706 let me know if I can close the issue. Without any answer, I'll close it.

**Comment by fanguannan0706** [comment]
Ok,My questions are done, let's close it.
