### ISSUE TITLE
TEEC_opensession failed with 0xffff0008 on ls1012a

### ISSUE THREAD

**Issue by mofanv** [OP-TEE/optee_os#2817]
Hi Team,

I'm struggling with running an application on a Grapeboard (ls1012a) for several days.

I followed the instruction at this [Web](https://github.com/ms-iot/lsdk/blob/master/docs/grapeboard.md). I tried Optee examples like "hello_world", "random", etc, and all these examples worked. But my own application always breaks with 
```
TEEC_Opensession failed with code 0xffff0008 origin 0x3
```
`0xffff0008` refers to `ITEM_NOT_FOUND`. But I have checked many times that the `.ta` is under `/lib/optee_armtz`.

Before that, I have successfully run this application on Raspberry Pi 3. I used `cmake` to build it when building the Optee system.
For running it on Grapeboard, I need to `make` the application separately. The `makefile` in the `host` folder is as follows:

```
CC      ?= $(CROSS_COMPILE)gcc
LD      ?= $(CROSS_COMPILE)ld
AR      ?= $(CROSS_COMPILE)ar
NM      ?= $(CROSS_COMPILE)nm
OBJCOPY ?= $(CROSS_COMPILE)objcopy
OBJDUMP ?= $(CROSS_COMPILE)objdump
READELF ?= $(CROSS_COMPILE)readelf

LDFLAGS= -lm -pthread

OBJSCR = src/
EXECSCR = examples/
OBJ = .o  ..........   .o
EXECOBJ = .o  ........   .o
OBJS = $(addprefix $(OBJSCR), $(OBJ))
EXECOBJS = $(addprefix $(EXECSCR), $(EXECOBJ))

EXECMAIN = main.o

CFLAGS += -Wall -I../ta/include -I$(TEEC_EXPORT)/include -I./include
CFLAGS += -Iinclude/ -Isrc/ -Iexamples/  -I./src/ -I./examples/

#Add/link other required libraries here
LDADD += -lteec -L$(TEEC_EXPORT)/lib
#DEPS = $(wildcard src/*.h) inlcude/dark.h inlcude/main.h

BINARY = optee_example_dark

.PHONY: all
all: $(BINARY)

$(BINARY): $(EXECMAIN) $(EXECOBJS) $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS) $(LDADD)

$(OBJSCR)%.o: $(OBJSCR)%.c
		$(CC) $(CFLAGS) -c $< -o $@

$(EXECSCR)%.o: $(EXECSCR)%.c
		$(CC) $(CFLAGS) -c $< -o $@

%.o: %.c
		$(CC) $(CFLAGS) -c $< -o $@

.PHONY: clean
clean:
	rm -f $(OBJS) $(EXECOBJS) $(EXECMAIN) $(BINARY)
```

Codes in the CA side:
```
TEEC_Context ctx;
TEEC_Session sess;

void prepare_tee_session()
{
    TEEC_UUID uuid = TA_DARK_UUID;
    uint32_t origin;
    TEEC_Result res;

    /* Initialize a context connecting us to the TEE */
    res = TEEC_InitializeContext(NULL, &ctx);
    if (res != TEEC_SUCCESS)
    errx(1, "TEEC_InitializeContext failed with code 0x%x", res);

    /* Open a session with the TA */
    res = TEEC_OpenSession(&ctx, &sess, &uuid,
                           TEEC_LOGIN_PUBLIC, NULL, NULL, &origin);
    if (res != TEEC_SUCCESS)
    errx(1, "TEEC_Opensession failed with code 0x%x origin 0x%x",
         res, origin);
}

void terminate_tee_session()
{
    TEEC_CloseSession(&sess);
    TEEC_FinalizeContext(&ctx);
}

int main(int argc, char **argv)
{
    printf("Prepare session with the TA\n");
    prepare_tee_session();

    printf("start dark function\n");
    dark_main(argc, argv);

    terminate_tee_session();
    return 0;
}
```

Codes in the TA side:
```
TEE_Result TA_CreateEntryPoint(void)
{
    DMSG("has been called");

    return TEE_SUCCESS;
}

void TA_DestroyEntryPoint(void)
{
    DMSG("has been called");
}

TEE_Result TA_OpenSessionEntryPoint(uint32_t param_types,
                                    TEE_Param __maybe_unused params[4],
                                    void __maybe_unused **sess_ctx)
{
    uint32_t exp_param_types = TEE_PARAM_TYPES(TEE_PARAM_TYPE_NONE,
                                               TEE_PARAM_TYPE_NONE,
                                               TEE_PARAM_TYPE_NONE,
                                               TEE_PARAM_TYPE_NONE);

    DMSG("has been called");

    if (param_types != exp_param_types)
    return TEE_ERROR_BAD_PARAMETERS;

    /* Unused parameters */
    (void)&params;
    (void)&sess_ctx;

    return TEE_SUCCESS;
}

void TA_CloseSessionEntryPoint(void __maybe_unused *sess_ctx)
{
    (void)&sess_ctx; /* Unused parameter */
    IMSG("Goodbye!\n");
}
```

I have no clue about why the `ITEM_NOT_FOUND` error happened. Is this because of the Grapeboard platform or the makefile I used? 

Any comment is appreciated!
Thanks,
Vincent

**Comment by etienne-lms** [comment]
> TEEC_Opensession failed with code 0xffff0008 origin 0x3

This looks at lot like OP-TEE is not finding the trusted application binary file.
Make sure **tee-supplicant** really gets TAs from **/lib/optee_armtz** if you are sure the file is there. **/lib/optee_armtz** is the default path but it be can be modified when building **tee-supplicant**.

**Comment by jforissier** [comment]
+1 with what @etienne-lms said, but it might also be a different error later converted to NOT_FOUND. See the `load_elf()` function here: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/user_ta.c#L821.
This should probably be improved to help troubleshooting (for instance, return the first error code that is not NOT_FOUND).

Anyway, if you build OP-TEE with `CFG_TEE_CORE_LOG_LEVEL=3` you will see debug traces and the `DMSG()` at line 834 may help understand what happened.

**Comment by mofanv** [comment]
@etienne-lms @jforissier 
Thank you very much for your reply! I went deeper according to your suggestions. It seems because I configured too much trusted memory for the TA (1MB for `STACK_SIZE`, and 10MB for `DATA_SIZE`). After adjusting it to be smaller, the error is gone.

However, I really need that much memory. Can I configure the available memory size for TA on the ls1012a Grapeboard? It has 1GB RAM in total.  :)

**Comment by mofanv** [comment]
The reason is found.  I will open a new issue to ask the memory size, thanks a lot. :)

**Comment by a-lve** [comment]
hello，I also encountered the same problem, but the reduction of memory still cannot solve it，what's the reason,please

**Comment by peichao538** [comment]
I also encountered the same problem too, no use to reduce the memory, and have not found the problem.
