### ISSUE TITLE
SCATTERED_ARRAY_BEGIN get a null value

### ISSUE THREAD

**Issue by leesagacious** [OP-TEE/optee_os#2822]
in the following function 
static TEE_Result verify_pseudo_tas_conformance(void)
{
        .......
	const struct pseudo_ta_head *start =
		SCATTERED_ARRAY_BEGIN(pseudo_tas, struct pseudo_ta_head);
	const struct pseudo_ta_head *end =
		SCATTERED_ARRAY_END(pseudo_tas, struct pseudo_ta_head);
}
SCATTERED_ARRAY_BEGIN: get a null value,  why ?

**Comment by jforissier** [comment]
Either OP-TEE was configured with no pseudo-TA, or it is a bug.

**Comment by leesagacious** [comment]
Or he doesn't have a section to store them

**Comment by leesagacious** [comment]
sizeof(struct pseudo_ta) = 44   why ?
