### ISSUE TITLE
Can't run tee-supplicant with Linaro rootfs on RPi3

### ISSUE THREAD

**Issue by jedichen121** [OP-TEE/optee_os#2823]
I'm trying to run the Linaro rootfs with optee on raspberry pi 3. First of all, the link provided in [rpi3.md](https://github.com/OP-TEE/build/blob/master/docs/rpi3.md#57-other-root-filesystems-than-initramfs-based) does not work properly. So I choose the linaro-stretch-installer-20180416-89.tar.gz which is the newest in Linaro release. 

I copied xtest, tee-supplicant, libteec.so*, libcrypto.so*, libcrypt*, and *.ta to the rootfs and boot through NFS. The `tee-supplicant` didn't seem to run on start. When running it manually, it complains 
`version GLIBC_2.28 not found
`

As it turns out, the Linaro rootfs is using an older version, not 2.28. I tried to run a optee that is built with older toolchain. But the 3.2.0 failed to build as it complained couldn't find uboot.env and u-boot-rpi.bin (I asked one of my friends to build 3.2.0 from scratch and he got the same error). 

So I'm currently stuck on trying to use a Debian based rootfs with tee-supplicant. Any help would be appreciated. Thank you.

**Comment by jforissier** [comment]
Hi @jedichen121 ,

It looks like you should build the latest OP-TEE but with an older toolchain (6.2 should be fine).

**Comment by jbech-linaro** [comment]
In the more recent [rpi3 documentation](https://optee.readthedocs.io/building/devices/rpi3.html) (yet to be deployed) we've removed the section about running other rootfs than the default one.  It's still doable, but since we don't test this on regular basis and aren't the ones creating the other root fs (`linaro-stretch ....`), which also tends to move around often resulting in dead links, we've decided to just get rid of it to avoid confusion. People who are used to create their own root fs can probably figure this out on their own anyways.

**Comment by jedichen121** [comment]
@jforissier I thought about that but I'm not sure if anything would break by using an older toolchain. A lot have changed between 3.4.0 and 3.2.0. But I'll give it a try.

**Comment by msa2** [comment]
In another thread, ...
[build issue 335] (https://github.com/OP-TEE/build/issues/335)
... I solved the problem by compiling the tee cient side on rpi3 itself (using the linaro rootfs with additional installed packages). I found trying to mess with toolchain versions too complicated for me...

**Comment by jforissier** [comment]
@msa2 thanks for mentioning this, it is indeed another option that will ensure the proper libraries are used.

**Comment by jedichen121** [comment]
@msa2 You solution worked for me as well! Thank you so much!

Besides, did you get error message saying kernel module load fail while booting up with linaro rootfs? 
```
[FAILED] Failed to start Load Kernel Modules.
See 'systemctl status systemd-modules-load.service' for details.
systemd-modules-load.service: Failed with result 'exit-code'.
```
To install the modules, I just copied the `module_output` folder from optee build result directly to `rootfs/lib`. Not sure if you used the same way.

**Comment by mnwrhsn** [comment]
@jedichen121  If you are okay with 32 bit builds, there is a Github repo showing how to do that for Raspbian as NW.

https://github.com/benhaz1024/raspbian-tee
