### ISSUE TITLE
Possible missing mbedTLS flag for CSR support

### ISSUE THREAD

**Issue by pokitoz** [OP-TEE/optee_os#2829]
Hello !

I think there is a missing flag to mbedTLS configuration:
https://github.com/OP-TEE/optee_os/blob/master/lib/libmbedtls/include/mbedtls_config_uta.h

I am trying to use CSR library and currently I don't have access to some functions as the following define: `#define MBEDTLS_X509_CSR_WRITE_C`  is missing.

Is there any reason why this define was removed? In particular, MBEDTLS_PEM_WRITE_C and MBEDTLS_X509_CRT_WRITE_C are both enabled.

Thanks

**Comment by jenswi-linaro** [comment]
No specific reason why that flag isn't included. I guess it wasn't needed in the test cases we have.
Patches are welcome! :-)

**Comment by pokitoz** [comment]
Thanks for your reply. I will test and see if I can create a patch for this :)
