### ISSUE TITLE
Alignment related compilation error

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#2830]
I am have the following code in my TA:

```
struct data {
     int x;
     char y[640];
};

char *buf; // buf points to SDP memory reference passed by normal world
struct data * testdata = (struct data *)(buf + Offset)
```
I get the following compilation error:

> error: cast increases required alignment of target type [-Werror=cast-align]

I want to ask what is the correct way to handle this. I do need to access the memory pointed by buf using the type cast.
To contrast, if buf was allocated using `TEE_Malloc`, then the type cast is allowed.

**Comment by jenswi-linaro** [comment]
Casting as `(struct data *)(void *)(buf + Offset)` should take care of the warning, but you should really check that the pointer has correct alignment. Preferably before it's a `struct data` pointer as the C standard says that it's undefined behavior with not correctly aligned pointers.
