### ISSUE TITLE
When compiling QEMU i got following error

### ISSUE THREAD

**Issue by akbarsaleemt** [OP-TEE/optee_os#2834]
When compiling QEMU i got following error. But that file present in standard header files
/***************************************************************************************************/
/usr/include/x86_64-linux-gnu/bits/siginfo.h:76:14: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘.’ token
      __pid_t si_pid; /* Sending process ID  */
              ^~~~~~
/usr/include/x86_64-linux-gnu/bits/siginfo.h:83:10: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘.’ token
      int si_overrun; /* Overrun count.  */
          ^~~~~~~~~~
/usr/include/x86_64-linux-gnu/bits/siginfo.h:90:14: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘.’ token
      __pid_t si_pid; /* Sending process ID.  */
              ^~~~~~
/usr/include/x86_64-linux-gnu/bits/siginfo.h:98:14: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘.’ token
      __pid_t si_pid; /* Which child.  */
              ^~~~~~
/usr/include/x86_64-linux-gnu/bits/siginfo.h:108:12: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘.’ token
      void *si_addr; /* Faulting insn/memory ref.  */
            ^~~~~~~
/usr/include/x86_64-linux-gnu/bits/siginfo.h:120:15: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘.’ token
      long int si_band; /* Band event for SIGPOLL.  */
/*********************************************************************************/

Thank you.

**Comment by jbech-linaro** [comment]
https://optee.readthedocs.io/faq/faq.html#q-i-got-build-errors-running-latest-why
https://optee.readthedocs.io/faq/faq.html#how-are-you-testing-optee

Hope this helps for additional discussions.
