### ISSUE TITLE
Use Linux header files from OP-TEE PTA

### ISSUE THREAD

**Issue by mnwrhsn** [OP-TEE/optee_os#2840]
Hello, I am trying to write a pseudo TA and want to include standard Linix kernel header files (for instance, I want to access/iterate Linux system call table and process table from my PTA, given I know the address of those tables). Is there a way that I can use built-in Linux kernel functions say use of List iterators/#define variables etc.) from to the OP-TEE PTA? Any examples/pointers would be great.

**Comment by etienne-lms** [comment]
Assuming you have a TA API header file such as **[core/include/tee/lib/libutee/include/pta_gprof.h](https://github.com/OP-TEE/optee_os/tree/3.4.0/core/include/tee/lib/libutee/include/pta_gprof.h)** that defines TA UUID, commands IDs and command arguments ABI, maybe add this header file:
* inside **/path/to/linux/include/uapi/linux/optee_pta_\<mypta\>.h** for the Linux part.
* inside **/path/to/optee-os/core/include/tee/lib/libutee/include/pta_\<mypta\>.h** for the secure world.

In secure world use pTA API to implement your services.

In the non-secure world use the Linux OP-TEE kernel client API to invoke your pTA, see `tee_client_open_session()` and friends from Linux from **/path/to/linux/include/linux/tee_drv.h**.

**Comment by mnwrhsn** [comment]
Ok thanks sounds good. Let me try.
