### ISSUE TITLE
Question about TEE_CreatePersistentObject() API, where the secure data really stored?

### ISSUE THREAD

**Issue by cxdinter** [OP-TEE/optee_os#2846]
Hi,
   I konw this API is used for secure storage. But I don't know where the secure data is really stored in NAND flash ? (just NAND flash, without RPMB)
  Because the system will be upgraded by new versions, and most flash area will be erased and re-programmed. But the secure storage data cannot be erased or modified. So I want to know the exact place of secure data which stored by TEE_CreatePersistentObject() API.

  Please give me some guide, thank you in advance.

**Comment by etienne-lms** [comment]
Hi, @cxdinter,
This is optee_client matters. The base path for the secure storage files in the Linux filesystem depends on build sequence that sets `TEE_FS_PARENT_PATH`. See [1] in the optee_client implementation. And grep for `TEE_FS_PARENT_PATH` in the `Android.mk`, `Makefile`, `CMakeLists.txt` upon your build env.

Have a look at the nice reformatted documentation. The file paths are shown in [2]. Read also the whole secure storage article [3].

Assuming your platform locates the base directory at path `/path/to/data/tee`, this directory may be mounted on a specific partition, outside the partition(s) storing upgradeable files. Maybe there are other ways also.

[1] https://github.com/OP-TEE/optee_client/blob/3.4.0/tee-supplicant/src/tee_supp_fs.c#L122
[2] https://optee.readthedocs.io/architecture/secure_storage.html#tee-file-structure-in-linux-file-system
[3] https://optee.readthedocs.io/architecture/secure_storage.html

**Comment by jbech-linaro** [comment]
It's by default stored under `/data/` in the flash. For persistent storage you will need to use RPMB for example (that being said, eMMC is not available on all devices).

**Comment by cxdinter** [comment]
Hi, @etienne-lms  & @jbech-linaro 
     Fully understood!
     Thank you very much!
