### ISSUE TITLE
Using optee with Raspbian

### ISSUE THREAD

**Issue by benhaha** [OP-TEE/optee_os#2854]
I want using Optee with Raspbian.

There are two prerequisite:
  1. Raspbian is 32 bit (and I don't want to build another 64bit one when considering big workload).
  2. ATF now only support 64 bit target for Raspberry Pi 3.

I compiled all component as follow:
  * ATF 64bit
  * uboot 32bit
  * kernel 32bit with tee driver
  * tee-supplicant 32bit
  * optee os 32bit
When I run tee-supplicant, it open /dev/teepriv0(it presented in /dev) failed.

Because there has so many 64 <->32bit state transfer, and monitor run in different exception(privilege) level between ARMv7-32bit & ARMv8-64bit. 

So, if there has a best solustion ? I just want some tips which method is resonable.
Or, if there some big problems I'll not wasted my time.

Thanks.

**Comment by jenswi-linaro** [comment]
What you're describing should work, if it doesn't it's probably just something small.

What do you mean with "ATF now only support 64 bit target for Raspberry Pi 3"?

**Comment by benhaha** [comment]
@jenswi-linaro I mean code at arm trusted firmware:
arm-trusted-firmware/plat/rpi3/platform.mk
"AArch32 not supported on rpi3"

So，I must compile it as 64bit.

**Comment by jenswi-linaro** [comment]
EL3 is (where most of ATF is executing) require to execute in AArch64 by the architecture. Perhaps it's just the optee node missing in device tree?

**Comment by benhaha** [comment]
@jenswi-linaro I had add it in dts. 
 I will debug it tomorrow.

**Comment by benhaha** [comment]
Now all is OK.

tee application should be running as root user.
I boot system as root at user at previous project, so I forgot change user in Raspbian.

Sorry for that stupid mistake.

**Comment by Hacklog24** [comment]
@benhaha 
Hi,

could you share the whole process? You would be a great help! I would like to do the same to have a richer distribution. Thank you so much!!

**Comment by benhaz1024** [comment]
@Hacklog24  answered in your issue thread: https://github.com/OP-TEE/optee_os/issues/2875
