### ISSUE TITLE
when compile optee_os i get error.

### ISSUE THREAD

**Issue by luo1277127** [OP-TEE/optee_os#2858]
```bash
In file included from core/arch/arm/kernel/elf_load_dyn.h:9:0,
                 from core/arch/arm/kernel/user_ta.c:43:
lib/libutils/ext/include/speculation_barrier.h:505:2: error: #error "No fallback provided for load_no_speculate"
In file included from core/arch/arm/kernel/elf_load_private.h:9:0,
                 from core/arch/arm/kernel/elf_load_dyn.h:13,
                 from core/arch/arm/kernel/user_ta.c:43:
lib/libutils/ext/include/speculation_barrier.h:505:2: error: #error "No fallback provided for load_no_speculate"
In file included from core/arch/arm/kernel/elf_load_dyn.h:13:0,
                 from core/arch/arm/kernel/user_ta.c:43:
core/arch/arm/kernel/elf_load_private.h: In function 'copy_dyn':
core/arch/arm/kernel/elf_load_private.h:186:2: error: implicit declaration of function 'load_no_speculate_cmp' [-Werror=implicit-function-declaration]
core/arch/arm/kernel/elf_load_private.h:186:2: warning: nested extern declaration of 'load_no_speculate_cmp' [-Wnested-externs]
core/arch/arm/kernel/elf_load_private.h:186:2: warning: assignment makes pointer from integer without a cast [enabled by default]
core/arch/arm/kernel/elf_load_private.h: In function 'copy_sym':
core/arch/arm/kernel/elf_load_private.h:217:2: warning: assignment makes pointer from integer without a cast [enabled by default]
cc1: some warnings being treated as errors
make: *** [out/arm/core/arch/arm/kernel/user_ta.o] Error 1
```
I use the
```bash 
make ARCH=arm PLATFORM=hikey \
 CROSS_COMPILE=arm-linux-uclibcekeyabi-  \
 CROSS_COMPILE_ta_arm32=arm-linux-uclibceabi- \
 CFG_ARM32_core=y  CFG_ARM64_core=n CFG_TEE_BENCHMARK=n \
 CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=1
```
to compile

In file **speculation_barrier.h**,I'm not define the macro `#elif defined (__ARM_32BIT_STATE) && (defined (__thumb2__) || !defined (__thumb__))`，should I need define it ? how to define it ?

**Comment by jenswi-linaro** [comment]
Those defines should be set automatically by the compiler. Perhaps you're not using the correct compiler?
Adding `V=1` to the make command line should give a clue about that.

**Comment by luo1277127** [comment]
I get it，but now has this error 。

{standard input}: Assembler messages:
{standard input}:3020: Error: junk at end of line, first unrecognized character is `/'
{standard input}:3026: Error: junk at end of line, first unrecognized character is `/'
{standard input}:3085: Error: junk at end of line, first unrecognized character is `/'
{standard input}:3116: Error: junk at end of line, first unrecognized character is `/'

I can't resolve it ，how can I strip it ？

thanks！

**Comment by jbech-linaro** [comment]
What are you trying to achieve here? Do you have any special needs when building this? Can't you just build for HiKey as we have described in you [HiKey guidelines](https://optee.readthedocs.io/building/devices/hikey620.html#build-instructions)? That is what we run on our [automated testing](https://optee.mooo.com:5000/) and work as it should.
