### ISSUE TITLE
how is the performance of optee? Can I test it by using benchmark?

### ISSUE THREAD

**Issue by zheng010** [OP-TEE/optee_os#2859]

**Comment by jbech-linaro** [comment]
To some extent you can, the benchmark framework is a little bit crude, but can give you some figures of run time / switching time between different exception levels, please see:
https://optee.readthedocs.io/debug/benchmark.html

If you're interested in profiling TA's, then you can run gprof, please see:
https://optee.readthedocs.io/debug/gprof.html

**Comment by zheng010** [comment]
> To some extent you can, the benchmark framework is a little bit crude, but can give you some figures of run time / switching time between different exception levels, please see:
> https://optee.readthedocs.io/debug/benchmark.html
> 
> If you're interested in profiling TA's, then you can run gprof, please see:
> https://optee.readthedocs.io/debug/gprof.ht

**Comment by zheng010** [comment]
> To some extent you can, the benchmark framework is a little bit crude, but can give you some figures of run time / switching time between different exception levels, please see:
> https://optee.readthedocs.io/debug/benchmark.html
> 
> If you're interested in profiling TA's, then you can run gprof, please see:
> https://optee.readthedocs.io/debug/gprof.html

The
