### ISSUE TITLE
Peripheral access with OPTEE on Pi

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#2864]
I have been running OPTEE on Hikey and want to try some test using the Pi board. I saw the documentation at [link](https://optee.readthedocs.io/building/devices/rpi3.html). It contains the following warning:

> mechanisms and hardware required to implement secure boot, memory, peripherals or other secure functions are not available

The question I want to ask relates to how the OPTEE team made the TEE OS workable in Pi, specifically related to peripherals. The documentation states that there is UART support. 

If I had to add a new peripheral to TEE on a hikey, I would have add its driver to OPTEE and then also make sure that the hardware is protected using TZPC. Now in case of Pi, it seems there is no TZPC, so hardware cannot be secured, but in terms of accessing the hardware, will the step of adding a driver remain the same ? Or does the OPTEE Pi build somehow rely on the normal world drivers to access peripherals ? Does memory isolation between normal and secure world still hold ?

**Comment by nathan-menhorn** [comment]
nice answer
