### ISSUE TITLE
What security features does optee support? TA isolation, DEP/ASLR、PXN、CFI?

### ISSUE THREAD

**Issue by zheng010** [OP-TEE/optee_os#2865]

**Comment by jbech-linaro** [comment]
Hi,

TA isolation: Yes
DEP: No (x86 feature only?), having that said, we try to map things as non-executable if it's not necessary.
ASLR: Ongoing (search/look at the open pull requests here at GitHub).
CFI: Seems useful and is probably something we would like to add, but it's not used in OP-TEE right now. We have discussed other flags / compiler features that improves security, like `fstack-protector-strong`, `_FORTIFY_SOURCE` etc. 

If you've done anything for OP-TEE in this area, we would be more than happy to receive patches/pull requests.

**Comment by zheng010** [comment]
> Hi,
> 
> TA isolation: Yes
> DEP: No (x86 feature only?), having that said, we try to map things as non-executable if it's not necessary.
> ASLR: Ongoing (search/look at the open pull requests here at GitHub).
> CFI: Seems useful and is probably something we would like to add, but it's not used in OP-TEE right now. We have discussed other flags / compiler features that improves security, like `fstack-protector-strong`, `_FORTIFY_SOURCE` etc.
> 
> If you've done anything for OP-TEE in this area, we would be more than happy to receive patches/pull requests
PXN is not supported by optee?  is other security features supported? such as Image encryption, symbol table confusion...

**Comment by jbech-linaro** [comment]
First, you need to read a tutorial on have to post and format GitHub issues so your posts are readable, this might help: https://guides.github.com/features/mastering-markdown/

Next onto the issue itself. We have no page listing all security features, admittedly it would be a good idea to have that. For the moment I suggest that you read the [architecture](https://optee.readthedocs.io/architecture/index.html) page at our documentation. That will give an overview of what OP-TEE is and what kind of features you can find. The additional things you are mentioning aren't in OP-TEE as of today. We're continuously trying to strengthen OP-TEE, so hopefully we (or some external contributor) will be able to add this in the future.

**Comment by jforissier** [comment]
About PXN:
```
$ git grep -n PX core/arch/arm/mm/core_mmu_*
core/arch/arm/mm/core_mmu_lpae.c:105:#define PXN                        (1ull << 1)
core/arch/arm/mm/core_mmu_lpae.c:284:           a &= ~(TEE_MATTR_PX | TEE_MATTR_UX);
core/arch/arm/mm/core_mmu_lpae.c:286:   if (desc & UPPER_ATTRS(PXN))
core/arch/arm/mm/core_mmu_lpae.c:287:           a &= ~TEE_MATTR_PX;
core/arch/arm/mm/core_mmu_lpae.c:322:   if (a & (TEE_MATTR_PX | TEE_MATTR_PW))
core/arch/arm/mm/core_mmu_lpae.c:336:   if (!(a & (TEE_MATTR_PX | TEE_MATTR_UX)))
core/arch/arm/mm/core_mmu_lpae.c:338:   if (!(a & TEE_MATTR_PX))
core/arch/arm/mm/core_mmu_lpae.c:339:           desc |= UPPER_ATTRS(PXN);
core/arch/arm/mm/core_mmu_v7.c:104:#define SECTION_PXN                  (1 << 0)
core/arch/arm/mm/core_mmu_v7.c:342:                     a &= ~(TEE_MATTR_PX | TEE_MATTR_UX);
core/arch/arm/mm/core_mmu_v7.c:344:             if (desc & SECTION_PXN)
core/arch/arm/mm/core_mmu_v7.c:345:                     a &= ~TEE_MATTR_PX;
core/arch/arm/mm/core_mmu_v7.c:365:                     a &= ~(TEE_MATTR_PX | TEE_MATTR_UX);
core/arch/arm/mm/core_mmu_v7.c:407:     if (a & (TEE_MATTR_PX | TEE_MATTR_PW))
core/arch/arm/mm/core_mmu_v7.c:426:             if (!(a & (TEE_MATTR_PX | TEE_MATTR_UX)))
core/arch/arm/mm/core_mmu_v7.c:429:#ifdef CFG_HWSUPP_MEM_PERM_PXN
core/arch/arm/mm/core_mmu_v7.c:430:             if (!(a & TEE_MATTR_PX))
core/arch/arm/mm/core_mmu_v7.c:431:                     desc |= SECTION_PXN;
core/arch/arm/mm/core_mmu_v7.c:457:             if (!(a & (TEE_MATTR_PX | TEE_MATTR_UX)))
core/arch/arm/mm/core_mmu_v7.c:715:                             mm->attr & TEE_MATTR_PX ? "X" : "XN",
```

My understanding of lines 338 and 339 in core_mmu_lpae.c, as well as lines 430 and 431 in core_mmu_v7.c, is that that a region that is not marked as executable in the OP-TEE configuration (i.e., !(a & TEE_MATTR_PX)) is always mapped with PXN set.

**Comment by jbech-linaro** [comment]
> My understanding of lines 338 and 339 in core_mmu_lpae.c, as well as lines 430 and 431 in core_mmu_v7.c, is that that a region that is not marked as executable in the OP-TEE configuration (i.e., !(a & TEE_MATTR_PX)) is always mapped with PXN set.

Indeed and this kind of things  is what I had in mind when saying "_we try to map things as non-executable if it's not necessary._", so thanks for point to a location in the code as an example.
