### ISSUE TITLE
Trouble calling TA UUID, using TEE_OpenTASession()

### ISSUE THREAD

**Issue by Gerryyq** [OP-TEE/optee_os#2871]
Hi, 
I've written `TA 'A'` to store keys in secure storage, now I'm writing `TA 'B'` trying to retrieve the stored keys by `TA 'A'`. So if I'm not mistaken using `TEE_OpenTASession()` and call `TA 'A'` to retrieve the keys for `TA 'B'`. However, I get the follow error, as my UUID seems to be incorrectly read.
![Screenshot from 2019-03-09 13-27-36](https://user-images.githubusercontent.com/32240805/54070598-ca6d4180-429c-11e9-8c5e-450488fbb8b6.png)

In TA_B.h
```
#define TA_A_UUID { 0x21ed2e80, 0x7206, 0x449d, \
	{ 0x8c, 0x7a, 0xda, 0x78, 0xb5, 0x60, 0x39, 0x74} }
```
In TA_B_ta.c
```
static TEE_Result read_raw_object(uint32_t param_types, TEE_Param params[4], void *session)
{
	const uint32_t exp_param_types =
		TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT,
				TEE_PARAM_TYPE_MEMREF_OUTPUT,
				TEE_PARAM_TYPE_NONE,
				TEE_PARAM_TYPE_NONE);

	TEE_Result res;
	uint32_t test;
	TEE_UUID* UUID = TA_A_UUID;

	/*
	 * Safely get the invocation parameters
	 */
	if (param_types != exp_param_types)
		return TEE_ERROR_BAD_PARAMETERS;

//Open session with TA 'A'
TEE_OpenTASession(&UUID, 0, param_types, params, &session, &test);
	 if (res != TEE_SUCCESS) {
		 EMSG("\nTEE_OpenTASession failed\n");
	 }
//Ask TA 'A' to read object
res = TEE_InvokeTACommand(session, 0, 5, param_types, params, &test);
	 if (res != TEE_SUCCESS) {
		 EMSG("\nTEE_InvokeTACommand failed\n");
	 }

	TEE_CloseTASession(&session);
	return res;
}
```

Why does UUID called gives remaining zeros at the back, instead of the proper UUID?

**Comment by etienne-lms** [comment]
what is `SAMPLE_UUID`?

**Comment by Gerryyq** [comment]
> what is `SAMPLE_UUID`?

My bad, its actually TA_A_UUID, I forgot to change to TA_A_UUID, so others can better understand my problem. I've updated accordingly.

**Comment by jforissier** [comment]
s/TEE_UUID */TEE_UUID/ (local variable)?

**Comment by Gerryyq** [comment]
> s/TEE_UUID */TEE_UUID/ (local variable)?

Yes, I defined the value, in header file and declared it as a local variable, within the function only.

**Comment by jforissier** [comment]
s/a/b/ means replace a with b

**Comment by Gerryyq** [comment]
> s/a/b/ means replace a with b

Oh, I've got it! Thank you so much! :+1:
