### ISSUE TITLE
hikey960 4GB

### ISSUE THREAD

**Issue by NewDwarf** [OP-TEE/optee_os#2872]
Is hikey960 configuration fully compatible with a new version of hikey960 4GB RAM?

**Comment by jforissier** [comment]
Hi @NewDwarf,

Probably not "out if the box":
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/platform_config.h#L116

But it shouldn't be hard to adjust the settings for 4GB. There may be several places to tweak -- optee_os, edk2, arm-trusted-firmware, and perhaps the DT.

**Comment by NewDwarf** [comment]
@jforissier thanks! It looks like, it is already there for optee_os
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/platform_config.h#L131

**Comment by jforissier** [comment]
Huh, yes indeed ;-) And I'm supposed to be the main maintainer of HiKey960... :-o
My board is a 3GB so I just use the default config.

**Comment by NewDwarf** [comment]
Great. The ticket can be closed then.
