### ISSUE TITLE
Is optee os a microkernel structure? It is L4?

### ISSUE THREAD

**Issue by zheng010** [OP-TEE/optee_os#2873]

**Comment by jbech-linaro** [comment]
It has nothing to do with L4 and it's not a microkernel.

**Comment by zheng010** [comment]
Which structure is optee? Is it common kernel? Thank you!

**Comment by jbech-linaro** [comment]
https://optee.readthedocs.io/architecture/index.html

**Comment by Kunaly-liu** [comment]
Can we use L4 microkernels as Trusted OS instead of OpTEE OS

**Comment by etienne-lms** [comment]
A trusted OS is expected strongly isolated from the 'normal world'. One could use L4 in the secure side but that L4 would also need to be isolated from the normal world OS. OP-TEE uses the secure/non-secure hardware isolation of Arm and RiscV  to archive this goal. I don't know projects that ported L4 to such an environment.

Note also that a trusted OS exposing services (to normal world OS) also need well defined and well implemented interfaces. OP-TEE bases its interfaces on the GPD TEE API specifications. One developing a trusted OS based on L4 would also need to have well defined/implemented interfaces.

**Comment by Kunaly-liu** [comment]
> A trusted OS is expected strongly isolated from the 'normal world'. One could use L4 in the secure side but that L4 would also need to be isolated from the normal world OS. OP-TEE uses the secure/non-secure hardware isolation of Arm and RiscV to archive this goal. I don't know projects that ported L4 to such an environment.
> 
> Note also that a trusted OS exposing services (to normal world OS) also need well defined and well implemented interfaces. OP-TEE bases its interfaces on the GPD TEE API specifications. One developing a trusted OS based on L4 would also need to have well defined/implemented interfaces.

Thank you very much for your reply!!!  I am trying to use Fiasco microkernel as Trusted OS, and implementing adaptive interface is probably the most critical step.
