### ISSUE TITLE
Building OP-TEE on the rpi3 with Raspbian

### ISSUE THREAD

**Issue by Hacklog24** [OP-TEE/optee_os#2875]
Hello,

I already have OP-TEE on my raspberry pi but the configuration is very light. I need to install packages and have more flexibility. Is it possible to use OP-TEE in another distro, for example Raspbian? Is there a guide?

Thank you all!

**Comment by jbech-linaro** [comment]
Hi,

I think you find answer to the question [here](https://optee.readthedocs.io/building/devices/rpi3.html#what-is-expected-to-work) and [here](https://optee.readthedocs.io/building/devices/rpi3.html#buildroot). Having that said, if you [search the issues list](https://github.com/OP-TEE/optee_os/issues?utf8=%E2%9C%93&q=raspbian), you'll find a recent post where an engineer says that he has been able to run Raspian. He might be able to give advice.

**Comment by Hacklog24** [comment]
@jbech-linaro 
Thanks for the links but I have already followed all the points and seen the post on raspbian. I thought you had some guide about it. I will try to find a solution while waiting.

Thanks for the reply!

**Comment by Hacklog24** [comment]
@jbech-linaro 
Updating...
using raspbian (32 bit) on pi, is it possible to compile an example code for 64-bit OP-TEE? 
Thanks a lot

**Comment by jbech-linaro** [comment]
Yes it is, if you want to see how we are doing it, then you can have a look [here](https://github.com/OP-TEE/build/blob/master/rpi3.mk#L6-L9).

**Comment by Hacklog24** [comment]
@jbech-linaro

Thanks for the reply, but maybe I didn't understand correctly. I'm using raspbian on pi and I'd like to compile a "hello world" written in C, for example, making it executable within OP-TEE. Then compile the code as a 64-bit executable for OP-TEE, directly from the pi with raspbian which is a
32 bit. It's possible?

Maybe I will have misunderstood but the link indicates the compilation of OP-TEE, so should I modify it and compile it at 32 bit?

Sorry for the question...

**Comment by jbech-linaro** [comment]
When you are saying "executable within OP-TEE" are run referring to applications running in
* Non-secure world, user space?
or
* Secure world, user space? I.e., a Trusted Application?

The former (NW/user space) are plain Linux applications and has nothing to do with OP-TEE execution as such, i.e., that is an application just as any other application running in Linux. The only difference is that those uses API's that enables the communication with the TEE on secure side.

The latter (SW/user space) is what we call a Trusted Applications and that runs in secure user space. I.e., here it's more correct to say that it executes withing OP-TEE. For TA's you can build them as both 64- and 32-bit applications (refer to the two of the four flags I linked to in previous comment). 

Usually it's fine to run 32-bit applications on 64-bit "modes". But not the opposite. The same argument is generally true when it comes to running/switching between different exception levels. I.e., "64bit kernel / 64 bit user space" is fine, so is "64bit kernel / 32 bit user space". However "32 bit kernel and 64 bit user space", is probably not a good idea and might even be impossible to run on many architectures. If you follow this, then things should work, just compile the Linux application or the TA accordingly.

**Comment by Hacklog24** [comment]
@jbech-linaro 
Good evening,

thank you very much for the explanation. I meant the first of the two points, as a simple test and then make it secure through the specific API. I have already done this procedure but this time I wanted to create the executable directly from raspbian and run it in the Non-secure world.

**Comment by jbech-linaro** [comment]
> I wanted to create the executable directly from raspbian and run it in the Non-secure world.

To me that sounds like you just need to `apt-get` `gcc` within Raspian and compile your applications as any other program in Linux, or?

**Comment by Hacklog24** [comment]
Exactly, simple. Except that the executable is 32 bit and to run it in the Non-secure world, it should be 64.

**Comment by jbech-linaro** [comment]
Sorry, but I don't understand. Raspbian IIRC is only a 32-bit distro/OS? That means you will only compile 32-bit programs. Why do you need to deal with 64 bit programs?

**Comment by Hacklog24** [comment]
Yes, that's why I was wondering if it was possible to compile even 64-bit applications.

Because a simple 32-bit linux application does not run in the Non-secure world of OP-TEE, while 64-bit does.

**Comment by jbech-linaro** [comment]
I'm still having a hard time following your way of naming of things. Can we agree that OP-TEE in **non-secure** world is **either** a plain 32-bit **or** and plain 64-bit application **and** that there is **no** difference to any other program running in Linux user space?

* If your distro/OS is 32-bit, then compile OP-TEE non-secure world components as 32-bit applications.
* If your distro/OS is 64-bit, then compile OP-TEE non-secure world components either as
   * 32-bit applications (probably need some multiarch package for Arm gcc, i.e., something equivalent of the i386 packages that you need on x86).
   * or
   * 64-bit applications.

Anyhow, I haven't tried OP-TEE with Raspbian myself, which is one of the reasons why it's mentioned as "not supported" in our [official docs](https://optee.readthedocs.io/building/devices/rpi3.html#raspbian), so I could have missed or misunderstood something here that is obvious when you actually give it a try. If someone with a working solution have time and are willing to update the docs with up-to-date and working instructions for Raspbian + OP-TEE, that'd be great.

**Comment by Hacklog24** [comment]
Sorry for this.

Perfect, now it's very clear, thank you very much. Yes I read the doc but I wanted to try. If I can create a clean guide I'll ping you. Thanks for the help!

**Comment by benhaz1024** [comment]
@Hacklog24 @jbech-linaro 
you can refer: https://github.com/benhaz1024/raspbian-tee
I put all in this repo.

**Comment by jbech-linaro** [comment]
@benhaz1024 , cool, thanks!

**Comment by benhaz1024** [comment]
@jbech-linaro , I will update the repo to make it works better, but the princple is simple as it present
 currently.

**Comment by jbech-linaro** [comment]
Always good to have a starting point, much better than nothing :)

**Comment by Hacklog24** [comment]
@benhaz1024 
Thank you so much!

I tried the procedure but the two folders, boot and rootfs are empty...

**Comment by benhaz1024** [comment]
@Hacklog24 the Makefile will copy all generate file to this folder, do you build sucsess?

**Comment by Ruide** [comment]
> @Hacklog24 
> you can refer: https://github.com/benhaz1024/raspbian-tee
> I put all in this repo.

Very helpful, thanks for sharing!

**Comment by Hacklog24** [comment]
@benhaz1024 
Yes, no errors. The previously created folders are empty, including optee_armtz.
I noticed that the path to copy files to the folders (in the makefile) is incorrect or the components are missing.

**Comment by benhaz1024** [comment]
@Hacklog24  I test it on another PC, it works fine for me.
Please execute shell script & make at the "raspbian-tee/" directory.

when success, the output file seem as:
`
& tree raspbian-tee/out -L 4
raspbian-tee/out/
├── boot
│   ├── armstub8.bin
│   ├── bcm2710-rpi-3-b.dtb
│   ├── bcm2710-rpi-3-b-plus.dtb
│   ├── config.txt
│   ├── uboot.env
│   └── uImage
└── rootfs
    ├── bin
    │   └── tee-supplicant
    └── lib
        ├── libteec.so -> libteec.so.1
        ├── libteec.so.1 -> libteec.so.1.0
        ├── libteec.so.1.0
        ├── modules
        │   └── 4.14.98-v7
        └── optee_armtz

7 directories, 10 files
`

**Comment by Hacklog24** [comment]
@benhaz1024 
Thank you so much!

I'll try again. Thanks for the help.

**Comment by Hacklog24** [comment]
@benhaz1024 
Updating
I have all the files this time but when I turn on the pi the LED stays red. What could it be?

Thank you so much.

**Comment by niusenc** [comment]
@Hacklog24  Hi, I also wanted to run optee with Raspbian. I can successfully build the OPTEE, but when I copied files to SD card and boot the Pi, it can't successfully boot. My host machine is ubuntu 18.04. My main board is 3b+. Also, I was a little confused about the Raspbian 32 bit, since I did not find a 32 bit Raspbian. The Raspbian I use was download from https://www.raspberrypi.org/downloads/raspbian/, I use a full version.  Also, I am not sure about my toolchains. Can you tell me which toolchains do you use? Thanks
