### ISSUE TITLE
Can I create new threads inside the TA ?

### ISSUE THREAD

**Issue by Tigerly** [OP-TEE/optee_os#2876]
I was wondering whether OP-TEE supports creating new threads inside the TA (just like use pthread_create in Linux)?

Thanks in advance!

**Comment by jbech-linaro** [comment]
I think this is answered here:
https://optee.readthedocs.io/faq/faq.html?highlight=Pthreads#q-is-multi-threading-supported-in-a-ta

**Comment by Tigerly** [comment]
Thanks for the quickly reply!
