### ISSUE TITLE
number of arguments

### ISSUE THREAD

**Issue by jiwonjoung** [OP-TEE/optee_os#2877]
Hello, I am wondering why OPTEE only allows TAs to have up to 4 function parameters. 
Is there a way I can extend this ? 
Is the limit an engineering convenience of a structural limitation? 
Thanks!

**Comment by jbech-linaro** [comment]
It's an artifact coming from the [GlobalPlatform Client API specification](https://optee.readthedocs.io/architecture/globalplatform_api.html#tee-client-api). You can extend it by putting more parameters in another struct and then serialize the struct. It's requires a little bit more work, but it's a working solution.

**Comment by jiwonjoung** [comment]
What is the easiest way to serialize the struct? 
This seems quite nontrivial.

**Comment by jenswi-linaro** [comment]
There's no single solution that covers all. You could serialize it as ASN.1 or XDR etc, but that could be a bit much if it's just a simple struct you need to serialize.

We have one pragmatical solution in https://github.com/OP-TEE/optee_test/blob/895c5caa9070a134bc12acdc6d0ad0354aa1f644/host/xtest/xtest_helpers.c#L134

Note that this is a link into our test code. So it may not be suitable for production code, but it can perhaps give some ideas.
