### ISSUE TITLE
TEE_BigIntExpMod not found

### ISSUE THREAD

**Issue by AlessandroVisintin** [OP-TEE/optee_os#2880]
Hi all,
I was looking for the function TEE_BigIntExpmod() but I can't find it inside OP-TEE.

Is there an alternative way for calculating a modular exponentiation?

Thanks a lot.

**Comment by jenswi-linaro** [comment]
It's called `TEE_BigIntComputeFMM()` in the GP spec.

**Comment by AlessandroVisintin** [comment]
Maybe I am missing something, the function you mention calculates op1*op2 in fast modular representation but I need (op1^op2) mod op3  with ^ meaning exponentiation.

**Comment by jbech-linaro** [comment]
@AlessandroVisintin , I think the GP spec haven't defined any modular exponentiation for some reason (they've just specified add, sub, mul and inv + helper functions). Having that said, we have it TEE core and are using it when dealing with signatures, the functions/callstack is
```c
rsa_exptmod
exptmod
mbedtls_mpi_exp_mod
```
As it looks like right now, if you need modular exponentiation from a TA, then you need to write a pseudo TA also which can in turn call one of the functions above. In some cases we have [extended the GP spec](https://optee.readthedocs.io/architecture/globalplatform_api.html#extensions), but those are non-official extensions. Now when you are pinpointing this, I agree that this seems like a big gap in the GP spec.

**Comment by jforissier** [comment]
`TEE_BigIntExpmod()` was introduced in the GP TEE Internal Core API v1.2 which we haven't implemented (yet). Section 8.9.7.

**Comment by jbech-linaro** [comment]
> `TEE_BigIntExpmod()` was introduced in the GP TEE Internal Core API v1.2 which we haven't implemented (yet). Section 8.9.7.

Great! I wasn't aware of that, thanks for sharing this (which reminds me that I need to download that revision).

**Comment by AlessandroVisintin** [comment]
> `TEE_BigIntExpmod()` was introduced in the GP TEE Internal Core API v1.2 which we haven't implemented (yet). Section 8.9.7.

Yeah that's the GP I am using as reference. Sorry I thought current OP-TEE was based on that one.

Anyway it seems I have solved my problem by implementing the modular exponentiation by myself using the mbedtls library embedded inside the OS.

I needed to implement it because, oddly enough, the mbedtls equivalent for modular exponentiation (mbedtls_mpi_exp_mod) is not working and gives error when used inside OPTEE.

Anyway, I will try with the custom implementation so for now I close the issue.

Thanks a lot for the help, always fast and precise.

**Comment by jbech-linaro** [comment]
> Yeah that's the GP I am using as reference. Sorry I thought current OP-TEE was based on that one.

We're lagging a bit behind, sorry for that. OP-TEE current implements `TEE Internal Core API Specification v1.1.2 (GPD_SPE_010)`. Newer revisions is on our radar and at some point I guess that we will update our implementation to comply with those. Having that said, the delta between 1.1.x and 1.2 is not that big. At least I think that is what @jforissier told me in the past (he has looked into the delta).

**Comment by jforissier** [comment]
> OP-TEE current implements TEE Internal Core API Specification v1.1.2 (GPD_SPE_010)

No, v1.1. We still have the `uint32_t` size parameters everywhere for instance.

>  the delta between 1.1.x and 1.2 is not that big. 

Correct, if you ignore the new "Peripheral and Event APIs". There are new crypto algorithms, too (some ECC curves and Chinese algorithms).

See section 1.6 Revision History in v1.2, it is really well done.
