### ISSUE TITLE
How does OP-TEE define utee svc handler?

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#2888]
Hi there,

I'm trying to trace done what exactly done in OP-TEE kernel when I called TEE_CipherUpdate and my trace stops at `UTEE_SYSCALL utee_cipher_update, TEE_SCN_CIPHER_UPDATE, 5` of `utee_syscalls_asm.S`.
By check the OP-TEE docs, I find out that:

> The utee_* functions are declared in utee_syscalls.h and implemented in utee_syscalls_asm.S They are simple system call wrappers which use the SVC instruction to switch to the appropriate system service in the OP-TEE kernel.

However, I do not understand how does this wrapper connect to the real svc handler, or how does OP-TEE find the svc handler of `TEE_SCN_CIPHER_UPDATE`. Any explanation will be helpful, thank you.

Simon

**Comment by jforissier** [comment]
The syscall table is in https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/tee/arch_svc.c.

**Comment by SimonWan** [comment]
Got it, thanks.
