### ISSUE TITLE
DMSG can not display in 3.4.0

### ISSUE THREAD

**Issue by bryan370210** [OP-TEE/optee_os#2890]
after testing the  hello_world example in op_tee 3.4.0 ,I found the content in DMSG can not display  in the  qemu window, and it worked well in older version

**Comment by jforissier** [comment]
Hi @bryan370210,

Please make sure you have set `CFG_TEE_TA_LOG_LEVEL` to `3` or higher.

**Comment by bryan370210** [comment]
@jforissier 
it works, thankyou
