### ISSUE TITLE
CFG_PAGEABLE_ADDR not implemented on aarch64

### ISSUE THREAD

**Issue by mimok** [OP-TEE/optee_os#2891]
I would like to add pager support to ZynqMP platforms but I'm facing a problem with pager configuration. The macro `CFG_PAGEABLE_ADDR` is only implemented on aarch32. 

Is it normal? Do I have to use TF-A to pass the proper address to OP-TEE trough x0 (if it is possible)? I can't find any information in the documentation. For the moment, I patched the file `generic_entry_a64.s` to add the support of the macro.

Thank you in advance for your answer.

**Comment by etienne-lms** [comment]
Yes, it is normal. TF-A is the recommended bootloader (and more) and already passes pageable image location to OP-TEE at boot time (through CPU register `X4`). TF-A needs to boot OP-TEE from images `tee-header_v2.bin` / `tee-pager_v2.bin` / `tee-pageable_v2.bin`.

**Comment by mimok** [comment]
Ok, but in this case how can I specify the address when I build TF-A?

From what I see in TF-A repository, adding pager support would require to
update TF-A ZynqMP platform. There is no other way, do you confirm?

Le lun. 18 mars 2019 à 09:31, Etienne Carriere <notifications@github.com> a
écrit :

**Comment by etienne-lms** [comment]
I think this information is missing in the OP-TEE docs. Here is an overview. I hope it is short and clear.

In TF-A, as for v2.0, supporting OP-TEE boot mandates platform specific code. See for examples the Arm platforms [1] and [2], or the qemu platform [3] and [4].

First of all OP-TEE boot images are:
* `tee-header_v2.bin`: This image describes the OP-TEE images to be loaded. It define the number of boot images. For each image, header may define a load address. If header does not define a load address for an image, TF-A will default to the load address defined at build time (I.e. from [1] or [3]).
* `tee-pager_v2.bin`: This is the executable boot image: image entry point is its exact load address. 
The load address is defined in `tee-header_v2.bin` to the value `TEE_RAM_START` (possibly `CFG_TEE_LOAD_ADDR`) used at OP-TEE build time.
* `tee-pageable_v2.bin`: This image is generated by OP-TEE only when `CFG_WITH_PAGER=y`.
The load address is not defined by `tee-header_v2.bin`. TF-A is responsible for loading the image somewhere and passing this load address as OP-TEE boot arguments (CPU registers). Note that OP-TEE moves this image into a target location in secure RAM during its early boot. 

On TF-A side:
* platform source file `*_bl2_mem_params_desc.c` (arm [1], qemu [3]) defines the 3 OP-TEE boot images as `BL32_IMAGE_ID`, `BL32_EXTRA1_IMAGE_ID` and `BL32_EXTRA2_IMAGE_ID`. 
* platform source file `*_bl2_setup.c` (arm [2], qemu [4]) implements a call to `parse_optee_header()` when `BL32_IMAGE_ID` (`tee-header_v2.bin`) is loaded  to extract info on boot images extra1/2 images are loaded.

At boot time, the header image is loaded and its information saved, then images extra1, optionnaly extra2, are loaded accordingly. Last, TF-A invokes OP-TEE `pager` entry point and passes the load address of OP-TEE `pageable` image as boot argument.

[1] [TF-A v2.0 plat/arm/common/aarch64/arm_bl2_mem_params_desc.c#L106](https://github.com/ARM-software/arm-trusted-firmware/blob/v2.0/plat/arm/common/aarch64/arm_bl2_mem_params_desc.c#L106)
[2] [TF-A v2.0 plat/arm/common/arm_bl2_setup.c#L156](https://github.com/ARM-software/arm-trusted-firmware/blob/v2.0/plat/arm/common/arm_bl2_setup.c#L156)
[3] [TF-A v2.0 plat/qemu/qemu_bl2_mem_params_desc.c#L73](https://github.com/ARM-software/arm-trusted-firmware/blob/v2.0/plat/qemu/qemu_bl2_mem_params_desc.c#L73)
[4] [TF-A v2.0 plat/qemu/qemu_bl2_setup.c#L149](https://github.com/ARM-software/arm-trusted-firmware/blob/v2.0/plat/qemu/qemu_bl2_setup.c#L149)

**Comment by mimok** [comment]
Actually Xilinx uses its own bl2 named FSBL. It is in charge of various things including FPGA configuration and other similar stuff. I never heard of using ARM bl2 instead of FSBL.

ZynqMP platform does not even implement the two files which are pointed in your answer. I don't know what is best way to overcome this problem. Maybe I should ask the question on the TF-A 'issues' page.

**Comment by etienne-lms** [comment]
As of v3.4.0, `plat-zynqmp` [does not](https://github.com/OP-TEE/optee_os/blob/3.4.0/core/arch/arm/plat-zynqmp/platform_config.h#L36) support `CFG_WITH_PAGER=y` so you should not worry about the dual boot image case and the `tee-*_v2.bin` images.

If you want to port pager support in a `zynqmp` platform flavor, then you need to update your bootloader.
* Loader has 2 target images to load, not only one (platform with pager disabled can boot from single image `tee.bin`).
  TF-A BL2 uses a 3 image scheme: `tee-header_v2.bin` describes the 1 or 2 boot images.
  An alternate BL2 could load straight `tee-pager_v2.bin` and `tee-pageable_v2.bin` with hard coded load address/entry point.
* Your BL31 stage should also be update to pass _pageable_ image location in RAM as an OP-TEE boot argument. Note an alternative could be a P-R in optee_os to port `CFG_PAGEABLE_ADDR` in `generic_entry_a64.S`, something like:
```patch
--- a/core/arch/arm/kernel/generic_entry_a64.S
+++ b/core/arch/arm/kernel/generic_entry_a64.S
@@ -53,8 +53,16 @@
 	.endm
 
 FUNC _start , :
+#if defined(CFG_PAGEABLE_ADDR)
+	mov	x19, #CFG_PAGEABLE_ADDR
+#else
 	mov	x19, x0		/* Save pagable part address */
+#endif
+#if defined(CFG_DT_ADDR)
+	mov	x20, #CFG_PAGEABLE_ADDR
+#else
 	mov	x20, x2		/* Save DT address */
+#endif
 
 	adr	x0, reset_vect_table
 	msr	vbar_el1, x0
```

**Comment by mimok** [comment]
Thank you for your help. I will think about that.

I think modifying an existing bootloader or adding a new bootloader stage will be necessary as I need to relocate OP-TEE pager at the place of the FSBL (FSBL+TF-A use almost all the ZynqMP on-chip memory). Indeed, I don't want to execute pager in DRAM.
