### ISSUE TITLE
Compiling out of tree linux driver module for optee linux kernel?

### ISSUE THREAD

**Issue by msa2** [OP-TEE/optee_os#2893]
Not sure if this is documented somewhere. I need out of linux tree driver module, specifically

   https://github.com/hartkopp/can-isotp

and for rpi3. Any hints on best approach...

- embed it into linux source (have to construct Kconfig and matching Makefile from somewhere)
- try to compile externally on rpi3 (however, cannot figure how to install "kernel headers" -- without needing the full kernel source on rpi3)
- crosscompile it on host machine (but, don't know the proper crosscompile command for can-isotp makefile...)
- someother solution?

**Comment by jluebbe** [comment]
Compiling out-of-tree kernel modules is completely independent of OP-TEE support in Linux. The linked repository also documents how to compile it against the headers package.

**Comment by msa2** [comment]
Yes, there is https://github.com/linaro-swg/linux , but it's hard for me to find out

- what command creates "headers package" from linaro linux source tree?

"make headers/headers_install" seems to create some usr/include/ files.... but, how to install them on rpi3 file system so that I can compile the driver on rpi3? Just copying headers does not seem to be enough...

optee build does create /lib/modules/*/build into the rootfs it generates, but the "build" is symlink to the build source tree on the host machine, it does not work when installed on the target (rpi3). Brute force is of course, that I copy all of the Linux source tree to the rpi3... I was just hoping to avoid that...

**Comment by msa2** [comment]
As I am using NFS rootfs, I decided to test bind mount to make /lib/modules/*/build to point into my build directory. After little work, I managed to make the linux source tree visible on rpi3. However, this (or just copying the build tree) is not a working solution: the kernel module building process uses compiled executables from the build tree (./scripts/basic/...), and those are obviously of wrong architecture...

```
linaro@linaro-installer:~/can-isotp$ make
make -C /lib/modules/4.14.56-v8/build M=/home/linaro/can-isotp modules
make[1]: Entering directory '/lib/modules/4.14.56-v8/build'
  CC [M]  /home/linaro/can-isotp/net/can/isotp.o
/bin/sh: 1: scripts/basic/fixdep: Exec format error
scripts/Makefile.build:328: recipe for target '/home/linaro/can-isotp/net/can/isotp.o' failed
make[3]: *** [/home/linaro/can-isotp/net/can/isotp.o] Error 2
scripts/Makefile.build:587: recipe for target '/home/linaro/can-isotp/net/can' failed
make[2]: *** [/home/linaro/can-isotp/net/can] Error 2
Makefile:1522: recipe for target '_module_/home/linaro/can-isotp' failed
make[1]: *** [_module_/home/linaro/can-isotp] Error 2
make[1]: Leaving directory '/lib/modules/4.14.56-v8/build'
Makefile:21: recipe for target 'modules' failed
make: *** [modules] Error 2
```
I guess my only option is now to embed the can-isotp into source tree, cook up some Kconfig and just rebuild...

**Comment by msa2** [comment]
Again. in case anyone is interested, moving can-isotp into linux source tree and rebuilding produces a working can-isotp module: copy files from can-isotp

```
./can-isotp/net/can/isotp.c -> ./linux/drivers/net/can/can-isotp.c (note name change)
./can-isotp/include/uapi/linux/can/isotp.h -> ./linux/incude/linux/can/
```
Then modify Kconfig and Makefile:

```
$ git diff
diff --git a/drivers/net/can/Kconfig b/drivers/net/can/Kconfig
index ac4ff394b..d53b3fdf6 100644
--- a/drivers/net/can/Kconfig
+++ b/drivers/net/can/Kconfig
@@ -55,6 +55,14 @@ config CAN_DEV
          support. This is the standard library for CAN drivers.
          If unsure, say Y.
 
+config CAN_ISOTP
+       tristate "ISO 15765 CAN transport protocol"
+       ---help---
+         Protocol implements ISO 15765-2 data transfer over the CAN bus.
+
+         This driver can also be built as a module.  If so, the module
+         will be called can-isotp.
+
 if CAN_DEV
 
 config CAN_CALC_BITTIMING
diff --git a/drivers/net/can/Makefile b/drivers/net/can/Makefile
index 02b8ed794..5389a30da 100644
--- a/drivers/net/can/Makefile
+++ b/drivers/net/can/Makefile
@@ -6,6 +6,7 @@
 obj-$(CONFIG_CAN_VCAN)         += vcan.o
 obj-$(CONFIG_CAN_VXCAN)                += vxcan.o
 obj-$(CONFIG_CAN_SLCAN)                += slcan.o
+obj-$(CONFIG_CAN_ISOTP)                += can-isotp.o
 
 obj-$(CONFIG_CAN_DEV)          += can-dev.o
 can-dev-y                      += dev.o
```
Then the next 'make' in build nicely asks about 'CAN_ISOTP' module, and accepts 'm' (module) answer. And, this should produce 'can-isotp.ko' module.

**Comment by msa2** [comment]
Issue can be closed, although "out of tree compilation" problem was not solved.
