### ISSUE TITLE
I tried to print proccess id in TA but i got error

### ISSUE THREAD

**Issue by akbarsaleemt** [OP-TEE/optee_os#2897]
I tried with getpid() in Ta side but its not compiling . Is there any API to print process id in secure application.

Thanks
Akbar

**Comment by jenswi-linaro** [comment]
`getpid()` isn't supported. What do you expect that `getpid()` should return?

**Comment by akbarsaleemt** [comment]
I need process ID of TA application.

Thankyou
akbar

**Comment by jenswi-linaro** [comment]
There is no such thing in secure world. Or do you mean the pid of the client talking to the TA? You'd need to use getpid() in normal world then.

**Comment by akbarsaleemt** [comment]
No I dont need PID of client applicatio which is talking to ta. But I have a doubt If we run  ca application in normal world its automatically connected to Ta in secure world based on uuid. But these two ta and ca are two different processes or single process.

Thankyou,
Akbar

**Comment by jiwonjoung** [comment]
What other syscalls are unsupported in addition to getpid?  
Are all syscalls unsupported? If so, why?

**Comment by jenswi-linaro** [comment]
> Are all syscalls unsupported? If so, why?

OP-TEE isn't Linux (or even trying to be posix like) so it has its own syscalls.
