### ISSUE TITLE
When build QEMU source code i got following error

### ISSUE THREAD

**Issue by akbarsaleemt** [OP-TEE/optee_os#2898]
/usr/include/x86_64-linux-gnu/bits/siginfo.h:349:3: error: redeclaration of enumerator ‘SIGEV_SIGNAL’
   SIGEV_SIGNAL = 0,  /* Notify via signal.  */
   ^~~~~~~~~~~~
../../host/aarch64-buildroot-linux-gnu/sysroot/usr/include/bits/sigevent-consts.h:29:3: note: previous definition of ‘SIGEV_SIGNAL’ was here
   SIGEV_SIGNAL = 0,  /* Notify via signal.  */
   ^~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/bits/siginfo.h:351:3: error: redeclaration of enumerator ‘SIGEV_NONE’
   SIGEV_NONE,   /* Other notification: meaningless.  */
   ^~~~~~~~~~
../../host/aarch64-buildroot-linux-gnu/sysroot/usr/include/bits/sigevent-consts.h:31:3: note: previous definition of ‘SIGEV_NONE’ was here
   SIGEV_NONE,   /* Other notification: meaningless.  */
   ^~~~~~~~~~
/usr/include/x86_64-linux-gnu/bits/siginfo.h:353:3: error: redeclaration of enumerator ‘SIGEV_THREAD’
   SIGEV_THREAD,   /* Deliver via thread creation.  */
   ^~~~~~~~~~~~
../../host/aarch64-buildroot-linux-gnu/sysroot/usr/include/bits/sigevent-consts.h:33:3: note: previous definition of ‘SIGEV_THREAD’ was here
   SIGEV_THREAD,   /* Deliver via thread creation.  */
   ^~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/bits/siginfo.h:356:3: error: redeclaration of enumerator ‘SIGEV_THREAD_ID’
   SIGEV_THREAD_ID = 4  /* Send signal to specific thread.  */
   ^~~~~~~~~~~~~~~
../../host/aarch64-buildroot-linux-gnu/sysroot/usr/include/bits/sigevent-consts.h:36:3: note: previous definition of ‘SIGEV_THREAD_ID’ was here
   SIGEV_THREAD_ID = 4  /* Send signal to specific thread.
   ^~~~~~~~~~~~~~~
In file included from include/libbb.h:52,
                 from include/busybox.h:8,
                 from applets/applets.c:9:
/usr/include/x86_64-linux-gnu/sys/wait.h:162:23: error: unknown type name ‘__WAIT_STATUS’; did you mean ‘ADJ_STATUS’?
 extern __pid_t wait3 (__WAIT_STATUS __stat_loc, int __options,
                       ^~~~~~~~~~~~~
                       ADJ_STATUS
/usr/include/x86_64-linux-gnu/sys/wait.h:168:38: error: unknown type name ‘__WAIT_STATUS’; did you mean ‘ADJ_STATUS’?
 extern __pid_t wait4 (__pid_t __pid, __WAIT_STATUS __stat_loc, int __options,
                                      ^~~~~~~~~~~~~
                                      ADJ_STATUS
scripts/Makefile.build:197: recipe for target 'applets/applets.o' failed
make[4]: *** [applets/applets.o] Error 1
Makefile:372: recipe for target 'applets_dir' failed
make[3]: *** [applets_dir] Error 2
package/pkg-generic.mk:229: recipe for target '/home/takkaakb/qemu/out-br/build/busybox-1.29.2/.stamp_built' failed
make[2]: *** [/home/takkaakb/qemu/out-br/build/busybox-1.29.2/.stamp_built] Error 2
Makefile:16: recipe for target '_all' failed

Thankyou,
Akbar

**Comment by etienne-lms** [comment]
These 2 log lines when building busybox look stranges:
```
/usr/include/x86_64-linux-gnu/bits/siginfo.h:356:3: error: redeclaration of enumerator ‘SIGEV_THREAD_ID’
../../host/aarch64-buildroot-linux-gnu/sysroot/usr/include/bits/sigevent-consts.h:36:3: note: previous definition of ‘SIGEV_THREAD_ID’ was here
```
Why looking into host `/usr/include/x86_64-linux-gnu`. Check your environment. Where this path comes from?

**Comment by etienne-lms** [comment]
by the way, looking into other issues I saw this [thread](https://github.com/OP-TEE/optee_os/issues/2834#issuecomment-465877979).
Maybe you should follow @jbech-linaro's advise and start from here:
https://optee.readthedocs.io/faq/faq.html#q-i-got-build-errors-running-latest-why

**Comment by wamserma** [comment]
Close in favour of https://github.com/OP-TEE/optee_os/issues/2834?
