### ISSUE TITLE
OPtee privilege switching

### ISSUE THREAD

**Issue by yilingxu** [OP-TEE/optee_os#2901]
Hi,
 
I'm working on imx6q, I use csu to control caam work in secure world, but not work in non-secure world. On the boot sequence, it's ok for optee os to use caam, but after system running, after CA switch to PTA, PTA can not use caam anymore? What's wrong?

My caam control code as follow:
const struct csu_setting csu_setting_imx6[] = {
	{13, 0xFF0033},		/* Protect ROMCP */
	{16, 0x330033},		/* Protect TZASC */
	{17, 0x3300FF},		/* Portect CAAM,make caam work in optee only, add by myself */
	{26, 0xFF0033},		/* Protect OCRAM */
	{(-1), 0},
};

Thanks,
Yiling Xu

**Comment by yilingxu** [comment]
It seems this problem is not about privilege. Once I disable caam in non-secure world, caam can not work in PTA(secure world) anymore.

I have roll back csu_setting_imx[] to:
const struct csu_setting csu_setting_imx6[] = {
{13, 0xFF0033},	/* Protect ROMCP /
{16, 0x330033},	/ Protect TZASC /
{26, 0xFF0033},	/ Protect OCRAM */
{(-1), 0},
};

And PTA stop at hal_jr_read_nbSlotAvailable() in do_jr_enqueue(). Do you have any idea? @MrVan

**Comment by MrVan** [comment]
@yilingxu Did you reserve a job ring for OP-TEE?

**Comment by yilingxu** [comment]
I don't change any caam code in OP-TEE .  And caam can work normally in optee os before linux (normal world) boot.

What's mean of "reserve a job ring for OP-TEE"? All job rings are configured to work for linux after linux boot?
I see hal_cfg_setup_nsjobring() function is used to configure job rings to NS world, I have tried to comment this function, but the PTA still not work.

**Comment by yilingxu** [comment]
I disable caam in linux by setting the device tree like this:
`crypto: caam@2100000 {
                compatible = "fsl,sec-v4.0";
                #address-cells = <1>;
                #size-cells = <1>;
                reg = <0x2100000 0x10000>;
                ranges = <0 0x2100000 0x40000>;
                interrupt-parent = <&intc>; /* interrupts = <0 92 0x4>; */
                clocks = <&clks IMX6QDL_CLK_CAAM_MEM>,
                     <&clks IMX6QDL_CLK_CAAM_ACLK>,
                     <&clks IMX6QDL_CLK_CAAM_IPG>,
                     <&clks IMX6QDL_CLK_EIM_SLOW>;
                clock-names = "mem", "aclk", "ipg", "emi_slow";
                **secure-status = "okay";
                status = "disabled";**
                sec_ctrl: ctrl@0 {
                    /* CAAM Page 0 only accessible */
                    /*    by secure world */
                    compatible = "fsl,sec-v4.0-ctrl";
                    reg = <0x2100000 0x1000>;
                    secure-status = "okay";
                    status = "disabled";
                };

                sec_jr0: jr0@1000 {
                    compatible = "fsl,sec-v4.0-job-ring";
                    reg = <0x1000 0x1000>;
                    interrupts = <GIC_SPI 105 IRQ_TYPE_LEVEL_HIGH>;
                };

                sec_jr1: jr1@2000 {
                    compatible = "fsl,sec-v4.0-job-ring";
                    reg = <0x2000 0x1000>;
                    interrupts = <GIC_SPI 106 IRQ_TYPE_LEVEL_HIGH>;
                };
            };
`

**Comment by Emantor** [comment]
If you disable the CAAM in the device tree, the Linux kernel disables the clock for the CAAM and OP-TEE can no longer access it.

**Comment by yilingxu** [comment]
@Emantor I enable CAAM in the device tree, but disable CONFIG_CRYPTO_DEV_FSL_CAAM, 
CONFIG_CRYPTO_DEV_FSL_CAAM_SM, CONFIG_CRYPTO_DEV_FSL_CAAM_SM_TEST, CONFIG_CRYPTO_DEV_FSL_CAAM_SECVIO in Linux， the OP-TEE still can not access CAAM.

Whether after I enable CAAM clock in OP-TEE, the OP-TEE can use CAAM without rely Linux?

**Comment by Emantor** [comment]
You have to enable the CAAM in the kernel, otherwise the clock driver will turn the clocks of because there are no active consumers. The simplest solution is to enable the CAAM but disabling the access to the jobs rings. You can also add a `return 0` into the CAAM probe function after the clocks have been activated. That way the kernel does not access the CAAM, but enables the clocks.

**Comment by yilingxu** [comment]
@Emantor Thanks for your reply, I soved my problem.
 I disable CONFIG_CRYPTO_DEV_FSL_CAAM_JR, and add a return 0 into the CAAM probe function after the clocks have been activated.
