### ISSUE TITLE
Memory address problem on Hikey960 4GB version

### ISSUE THREAD

**Issue by ultracold273** [OP-TEE/optee_os#2905]
Hi,

I'm using optee os on my Hikey960 board with a 4GB RAM. When I was running a sample trusted application from optee_examples (e.g., hello_world), I got error message like this:
```log
E/TC:4 0 tee_entry_std:554 Bad arg address 0x219b9c000
hello_world: TEEC_Opensession failed with code 0xffff000e origin 0x2
```
It seems the address checking in the `tee_entry_std` function failed. Tracing back, I discovered the optee os considers the address 0x219b9c000 does not locate inside the non-secure ddr address space which is checked by `pbuf_is_special_mem` function.

Refering to the [SoC manual of Hi3660](https://github.com/96boards/documentation/raw/master/consumer/hikey/hikey960/hardware-docs/HiKey960_SoC_Reference_Manual.pdf), saying that if a 4GB DDR is connected, the address ranges 0--3.5G and 4G--4.5G are specified as the accessible 4GB DRAM space in Section 2.9.

The linux kernel seems to map the higher 512MB DRAM to the physical address from `0x200000000` to `0x21FFFFFFF`, which is not recognized by optee os as legitimate address. I noticed that in the hikey platform header files (`plat-hikey/platform_config.h`) only `0x0 - 0x3DFFFFFF` and `0x40000000 - 0xDFFFFFFF` are defined as non secure memory address. I am wondering whether it needs to be modified to support the memory allocated in the higher end of DRAM.

Thank you.

**Comment by jenswi-linaro** [comment]
You're right, in your case you need to add mappings for those high addresses too. Since it's an address above 4GB you need to make sure that `paddr_t` is large enough. The easiest way is to compile OP-TEE for AArch64, which I believe you've already done.

**Comment by ultracold273** [comment]
Thanks. The issue is solved.
