### ISSUE TITLE
Possible better error handling  in open_dirh?

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#2907]
Hi, 
recently I met below issue:
1. I  use persist storage API to create a file A;
2. A stress test is used to open->write->close the file.  It also did some other operations.
Sometimes I found the file A couldn't be found. The function TEE_OpenPersistentObject returns TEE_ERROR_ITEM_NOT_FOUND. However, with debug, I found the file A still exists. It's because the dirf.db file is changed as below(CFG_RPMB_FS is set to n in my environment):

To get the file,  first we should get dirf.db file with open_dirh(). The implementation of this function is:
```
542 static TEE_Result open_dirh(struct tee_fs_dirfile_dirh **dirh)
543 {
544 >---if (!tee_fs_dirfile_open(false, NULL, &ree_dirf_ops, dirh))
545 >--->---return TEE_SUCCESS;                                                                                                                                                                                     
546 >---return tee_fs_dirfile_open(true, NULL, &ree_dirf_ops, dirh);
547 }
```
In line 544, there's no check of return value of tee_fs_dirfile_open, whenever opening dirf.db fails, line 546 is called to create a new dirf.db. It's reasonable to do this for cases like the dirf.db doesn't exist, but in my case, the return value of tee_fs_dirfile_open is TEE_ERROR_OUT_OF_MEMORY while the dirf.db actually still exists.  If we insist to create new dirf.db in this case, there's no info of previously created file A, and TEE_OpenPersistentObject returns TEE_ERROR_ITEM_NOT_FOUND. 

I think maybe we can have a better error handling to distinct different return values of tee_fs_dirfile_open. Just creating a new dirf.db will make old files inaccessible and only telling user the item can't be found is quite hard to debug. For return value like TEE_ERROR_OUT_OF_MEMORY , maybe we can give more hints and leave the TA user to decide what to do (In my case I fixed this issue by increasing heap size). What do you guys think? Thanks in advance!

**Comment by jforissier** [comment]
Hi @tiger20081015,

I agree, I think `tee_fs_dirfile_open(true, ...);` should be called only if the error code at line 544 was `TEE_ERROR_ITEM_NOT_FOUND`. Otherwise, just return the error code.
Would you please create a patch?

**Comment by tiger20081015** [comment]
@jforissier OK, I'll submit a patch later.

**Comment by tiger20081015** [comment]
@jforissier , sorry for submitting the patch so late. Please help to review. Thanks!
https://github.com/OP-TEE/optee_os/pull/3148

**Comment by jbech-linaro** [comment]
I'm closing the ticket, issue resolved, thanks for the contribution @tiger20081015 !
