### ISSUE TITLE
--pad-to

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#2909]
@yanyan-wrs @jenswi-linaro 

Any idea why https://github.com/OP-TEE/optee_os/commit/2e28652235a4 is needed? Thanks.

**Comment by vchong** [comment]
Found this: https://github.com/OP-TEE/optee_os/issues/1071

**Comment by jenswi-linaro** [comment]
Thanks @vchong 
@jforissier is it clear?

**Comment by jforissier** [comment]
Yep, clear, thanks a lot!

It would have been better to explain this in the commit message :-/ Most of the time, it is easy to figure out "what" a commit does, but it is often quite hard or impossible to found out "why" without external information.

FYI, clang's `llvm-objcopy` does not support `--pad-to` so we'll need to find another way.
