### ISSUE TITLE
Using fingerprint hardware with OPTEE

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#2910]
I want to ask a question related to interfacing fingerprint sensor with OPTEE. Global Platform's specification "Biometrics API v1.0 | GPD_SPE_042" provides description of how TA's can use the fingerprint hardware. I have two questions:

1. Does the latest version of OPTEE have the Peripheral API layer ?
2. Does the latest version of OPTEE have the required driver support to interface with fingerprint hardware ? Also which specific fingerprint hardware are supported for testing ?

Thanks

**Comment by jbech-linaro** [comment]
> 1. Does the latest version of OPTEE have the Peripheral API layer ?

No, that hasn't been implemented yet and I'm uncertain when if/when it will happen.

> 2. Does the latest version of OPTEE have the required driver support to interface with fingerprint hardware ?

Usually things like fingerprint sensor etc communicate over SPI/I2C or something like that. We do have SPI support in OP-TEE, but not I2C support.

> Also which specific fingerprint hardware are supported for testing ?

We haven't tried using fingerprint readers with OP-TEE.

**Comment by a2t2** [comment]
Would it be possible the following this with the OPTEE on hikey ?
https://www.adafruit.com/product/751 

It says TTL serial, so would UART be applicable ?

**Comment by a2t2** [comment]
Are all the OPTEE drivers listed in this folder: 
https://github.com/OP-TEE/optee_os/tree/master/core/drivers  ?
