### ISSUE TITLE
Automatically run of a rotine when optee_os boots.

### ISSUE THREAD

**Issue by MaXwEllDeN** [OP-TEE/optee_os#2918]
Greetings dear fellows.

I was wondering if it is possible to start a routine automatically when the secure world boots, while ensuring the normal booting process.

I know that Unix-based systems take advantage of the scheduler to maintain multiple processes and threads. What does the secure_world do after the normal boot process? It just hangs on and waits for a TA call? Is there a way to run both my new routine and ta handling simultaneously?

For example, i would like to have a led blinking controlled by the secure-side of optee just before my device boot.

I thought about creating a pseudo-TA and invoke it periodically from rich os with a init file. It happens that for my condition case this routine must be run independently of the normal world.

Thanks!

**Comment by lorc** [comment]
OP-TEE is managed only by Normal World.

You can try to setup secure timer interrupt and do you work in the interrupt handle. In this case you'll have no thread context. But maybe it is okay for your use case.

**Comment by MaXwEllDeN** [comment]
Thank you for your reply, @lorc. I'm currently studying more about this secure timer and trying to figure out how it works.
