### ISSUE TITLE
QEMU HOTP Error

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#2922]
Hi there,

I recently updated my QEMU with OPTEE-OS 3.4.0 by following the [instruction](https://optee.readthedocs.io/building/gits/build.html) with `qemu_v8` configuration and branch `-b 3.4.0`.

When I run the pre-built examples, I find that HOTP example cannot be passed.
The HOST prints:
`hotp: TEEC_Opensession failed with code 0xffff3024 origin 0x3`
The TA prints:
`E/TA:  assertion '!((vaddr_t)data & (POOL_ALIGN - 1))' failed at lib/libutils/ext/mempool.c:134 in mempool_alloc_pool()`

Is there any idea to make this example works?

Thanks.

Simon

**Comment by jforissier** [comment]
Hi @SimonWan,

I can confirm I see the same failure here with 3.4.0, and updating optee_os to latest master fixes the issue. I have not tried to identified which commit fixes the problem however.

**Comment by jbech-linaro** [comment]
This was a bug, fixed in https://github.com/OP-TEE/optee_os/pull/2792 there's also more info.

**Comment by SimonWan** [comment]
The master branch works, thank you.

**Comment by SimonWan** [comment]
By the way, any idea when you might release another stable version that can patch this issue? @jbech-linaro @jforissier

**Comment by jforissier** [comment]
Version 3.5.0 is planned for end of April.
