### ISSUE TITLE
Question for real-time

### ISSUE THREAD

**Issue by tregua87** [OP-TEE/optee_os#2930]
Dear all,

I am approaching ARM TrustZone and Real-Time OSes.

in short, my question is: is it possible to include OP-TEE in a Real-Time OS, such as [this](https://github.com/Forty-Tw0/RaspberryPi-FreeRTOS)?

As far as I understood, OP-TEE itself does not have a task scheduler, this part is due to the untrusted word (that's also why it is prone to DOS, doesn't it?).

To my understanding, it should be possible to use an RTOS as an untrusted word and then invoke trusted functions from there.

Maybe this has been already developed but I am not aware.

Anybody faced this problem before?

Cheers.

**Comment by jforissier** [comment]
Hi @tregua87 ,

> I am approaching ARM TrustZone and Real-Time OSes.

> in short, my question is: is it possible to include OP-TEE in a Real-Time OS, such as this?

Certainly.

> As far as I understood, OP-TEE itself does not have a task scheduler, this part is due to the untrusted word

Correct.

>  (that's also why it is prone to DOS, doesn't it?).

Yes.

> To my understanding, it should be possible to use an RTOS as an untrusted word and then invoke trusted functions from there.

Exactly. I believe some people have been using OP-TEE with VxWorks, but I don't have any details. Perhaps someone can speak up.

**Comment by tregua87** [comment]
Thank @jforissier 

Currently, I am working on Raspberry Pi 3, that's why I pointed FreeRTOS (but maybe there are better solutions).

I am finding a lot of papers that describe this merging, but I lack open-source projects.

My need is building new things on top of such OSes. Not reinvent the wheel (if possible).

**Comment by jforissier** [comment]
I would suggest you look at the Linux driver (drivers/tee/optee), which is obviously where the normal world OS interfaces with OP-TEE. This should help you identify what is needed to have OP-TEE work with FreeRTOS. Then as a second step you may need to port the GlobalPlatform TEE Client API (libteec), that is, if you need to have user-space client applications (not sure how this applies to FreeRTOS). Note that there is a kernel client API in the Linux driver, perhaps you don't need more that that.

**Comment by tregua87** [comment]
Thanks!
I will look into that :)
Cheers.
