### ISSUE TITLE
No outputs in SecureWorld (TA or PTA) IMSG/DMSG

### ISSUE THREAD

**Issue by Mika9131** [OP-TEE/optee_os#2931]
Hi everyone,

i recently setup OP-TEE on qemu and everything seems to work as it should.
except im getting no outputs from the examples in SW despite including trace.h in the examples. 

i tryed first the examples without any changes. like i mentioned they getting executed but im getting no output i.e. when i run the hello word example, it doesnt print out "hello" or "goodbye".
what could cause this problem?

I apologize for my bad english. 
also this is my first issue im posting hope i did everything right.

hello world example output NW:

`# optee_example_hello_world 
Invoking TA to increment 42
TA incremented value to 43
`
hello world example output SW:

`D/TC:? 0 tee_ta_init_pseudo_ta_session:280 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
D/TC:? 0 load_elf:877 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:? 0 load_elf:877 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE [buffered])
D/TC:? 0 load_elf_from_store:845 ELF load address 0x40005000
D/TC:? 0 tee_ta_init_user_ta_session:1067 Processing relocations in 8aaaf200-2450-11e4-abe2-0002a5d5c51b
D/TC:? 0 tee_ta_close_session:398 csess 0xe165460 id 5
D/TC:? 0 tee_ta_close_session:417 Destroy session
D/TC:? 0 tee_ta_close_session:443 Destroy TA ctx
`

**Comment by jforissier** [comment]
Hi @Mika9131,

It looks like you may be missing `CFG_TEE_TA_LOG_LEVEL=2` (or higher), but it should be the default value in the build Makefiles... Please double check.

**Comment by Mika9131** [comment]
Hi @jforissier,
i double checked most of the ta Makefiles and the `CFG_TEE_TA_LOG_LEVEL=` was set on all of them 4. 
so i tryed various numbers like 2 and 3 still didnt changed anything. Still no output.
Since your response didnt include a "?" i even tryed it without it.

ta Makefile Hello World:
`CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)

# The UUID for the Trusted Application
BINARY=8aaaf200-2450-11e4-abe2-0002a5d5c51b

-include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk

ifeq ($(wildcard $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk), )
clean:
	@echo 'Note: $$(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk not found, cannot clean TA'
	@echo 'Note: TA_DEV_KIT_DIR=$(TA_DEV_KIT_DIR)'
endif`

**Comment by Mika9131** [comment]
Just found the issue that causes this inconvenience.
It is not enough to set the `CFG_TEE_TA_LOG_LEVEL ?= 4` in the TA Makefiles. 
In `/optee_os/mk/` there is a file named `config.mk`.
That file contains pre configured configuration Value's, where the `CFG_TEE_TA_LOG_LEVEL` was set on `1`
Just Changed it to 4 and everything works as it should. 

Also i dont know why its defaultly set on 1.

**Comment by jforissier** [comment]
`:=` instead of `?=` would probably work.
