### ISSUE TITLE
documentation: user guide to mention each CFG_xxx options.

### ISSUE THREAD

**Issue by sandeepbrcm** [OP-TEE/optee_os#2935]
Suggestion:  It would be great to have a doc where we can add each CFG_XXX introduced to the
code. Guidelines on the usage of the CFG_XXX.

**Comment by jforissier** [comment]
> Suggestion: It would be great to have a doc where we can add each CFG_XXX introduced to the
code.

I think the best place to describe each and every `CFG_xxx` is in the code itself (mk/config.mk, mainly). This is the best way to avoid discrepancies between the code and the documentation.

> Guidelines on the usage of the CFG_XXX.

On this, I agree. Guidelines could include, describing the most important options, provide sensible values, explain the relationships between options, which one are useful for debugging, the ones that impact the memory layout, which ones relate to security etc.

**Comment by etienne-lms** [comment]
+1, few guidelines there would help.
