### ISSUE TITLE
recipe for target 'optee-os-common' failed

### ISSUE THREAD

**Issue by Varsha-a** [OP-TEE/optee_os#2941]
Hi,
I am trying to setup optee on my 64-bit linux machine ,I am having an issue when I try to do make ,Below is the error I am getting.

```bash
make -C /home/varsha/optee/build/../optee_os O=out/arm CFG_ARM64_core=y CROSS_COMPILE="/usr/bin/ccache /home/varsha/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_core="/usr/bin/ccache /home/varsha/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm64=/home/varsha/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu- CROSS_COMPILE_ta_arm32=/home/varsha/optee/build/../toolchains/aarch32/bin/arm-linux-gnueabihf- CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=0 CFG_TEE_BENCHMARK=n PLATFORM=rpi3
make[1]: Entering directory '/home/varsha/optee/optee_os'
CHK out/arm/conf.mk
CHK out/arm/include/generated/conf.h
make[1]: *** No rule to make target '/home/user/optee/toolchains/aarch64/lib/gcc/aarch64-linux-gnu/8.2.1/include/stddef.h', needed by 'out/arm/core/include/generated/.asm-defines.s'. Stop.
make[1]: Leaving directory '/home/varsha/optee/optee_os'
common.mk:394: recipe for target 'optee-os-common' failed
make: *** [optee-os-common] Error 2
```

It will be really great if some one could help.

Thanks,
Varsha

**Comment by jforissier** [comment]
Hi @Varsha-a,

Try `rm -rf optee_os/out`.

**Comment by Varsha-a** [comment]
Hey yes tried that , below is error I am getting

make -C /home/varsha/optee/build/../optee_os O=out/arm CFG_ARM64_core=y CROSS_COMPILE="/usr/bin/ccache /home/varsha/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_core="/usr/bin/ccache /home/varsha/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm64=/home/varsha/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu- CROSS_COMPILE_ta_arm32=/home/varsha/optee/build/../toolchains/aarch32/bin/arm-linux-gnueabihf- CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=0 CFG_TEE_BENCHMARK=n PLATFORM=rpi3
make[1]: Entering directory '/home/varsha/optee/optee_os'
  CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
ccache: error: execv of /home/varsha/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc failed: Exec format error
mk/compile.mk:232: recipe for target 'out/arm/core/include/generated/.asm-defines.s' failed
make[1]: *** [out/arm/core/include/generated/.asm-defines.s] Error 1
make[1]: Leaving directory '/home/varsha/optee/optee_os'
common.mk:394: recipe for target 'optee-os-common' failed
make: *** [optee-os-common] Error 2

**Comment by jforissier** [comment]
> ccache: error: execv of /home/varsha/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc failed: Exec format error

Your Linux distribution is 32-bit I suppose? The cross-compiler is a 64-bit executable (x86_64).

**Comment by aliongit** [comment]
> Hi @Varsha-a,
> 
> Try `rm -rf optee_os/out`.

Hi, I'm getting such error, and have tried this command but the error is remaining, I'm using 64bit ubuntu :
`~/optee/bin/build$ make all run
make -C /home/ali/optee/bin/build/../optee_os O=out/arm CROSS_COMPILE="/usr/bin/ccache /home/ali/optee/bin/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CROSS_COMPILE_core="/usr/bin/ccache /home/ali/optee/bin/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CROSS_COMPILE_ta_arm64="/usr/bin/ccache /home/ali/optee/bin/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm32="/usr/bin/ccache /home/ali/optee/bin/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=1 CFG_TEE_BENCHMARK=n PLATFORM=vexpress-qemu_virt
make[1]: Entering directory '/home/iona/optee/bin/optee_os'
  CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
make[1]: *** No rule to make target '/home/iona/optee/bin/toolchains/aarch32/lib/gcc/arm-linux-gnueabihf/8.3.0/include/stdbool.h', needed by 'out/arm/core/include/generated/.asm-defines.s'.  Stop.
make[1]: Leaving directory '/home/iona/optee/bin/optee_os'
common.mk:380: recipe for target 'optee-os-common' failed
make: *** [optee-os-common] Error 2`, need help fg
