### ISSUE TITLE
How to include pbc library in OP-TEE TA？

### ISSUE THREAD

**Issue by 1064620496** [OP-TEE/optee_os#2947]
I want to use pbc libray in ta，but don‘t know how to realize it.I have compiled with qemu_v8 and finished xtest.

**Comment by jbech-linaro** [comment]
See this: https://optee.readthedocs.io/faq/faq.html#q-how-do-i-link-a-library-into-a-trusted-application

**Comment by 1064620496** [comment]
> See this: https://optee.readthedocs.io/faq/faq.html#q-how-do-i-link-a-library-into-a-trusted-application

I have read this and had a try. But I still want to know whether what I need to do is to generate a libpbc.a and libgmp.a(pbc depends on gmp)with a cross compiler(I don't know which compiler to use) and  put it in a directory near ta.c and change the sub.mk as the link says.

**Comment by jbech-linaro** [comment]
Ok, I thought you asked in general terms how to add/compile/use a library from a TA. I have no experience with the libraries that you are referring to, so I'm afraid I cannot help. Having that said, you should use the same cross compiler that you are using when compiling the TA's.

**Comment by 1064620496** [comment]
> Ok, I thought you asked in general terms how to add/compile/use a library from a TA. I have no experience with the libraries that you are referring to, so I'm afraid I cannot help. Having that said, you should use the same cross compiler that you are using when compiling the TA's.

lib/libgmp.a(lt43-set_str.o): In function `__gmpz_set_str':
set_str.c:(.text+0x50): undefined reference to `__ctype_b_loc'
lib/libgmp.a(assert.o): In function `__gmp_assert_header':
assert.c:(.text+0x20): undefined reference to `stderr'
assert.c:(.text+0x28): undefined reference to `stderr'
assert.c:(.text+0x38): undefined reference to `fprintf'
assert.c:(.text+0x68): undefined reference to `fprintf'


> Ok, I thought you asked in general terms how to add/compile/use a library from a TA. I have no experience with the libraries that you are referring to, so I'm afraid I cannot help. Having that said, you should use the same cross compiler that you are using when compiling the TA's.

lib/libgmp.a(lt43-set_str.o): In function `__gmpz_set_str':
set_str.c:(.text+0x50): undefined reference to `__ctype_b_loc'
lib/libgmp.a(assert.o): In function `__gmp_assert_header':
assert.c:(.text+0x20): undefined reference to `stderr'
assert.c:(.text+0x28): undefined reference to `stderr'
assert.c:(.text+0x38): undefined reference to `fprintf'
assert.c:(.text+0x68): undefined reference to `fprintf'
when using the gmp in ta ,I can't make successfully, I think the library is against GobalPlatform TEE Core Internal API.

**Comment by 1064620496** [comment]
> Ok, I thought you asked in general terms how to add/compile/use a library from a TA. I have no experience with the libraries that you are referring to, so I'm afraid I cannot help. Having that said, you should use the same cross compiler that you are using when compiling the TA's.

when using the gmp in ta ,I can't make successfully, I think the library is against GobalPlatform TEE Core Internal API.

**Comment by jenswi-linaro** [comment]
From the errors it looks like you've used a different setup (.h files belonging to some other libc etc) when compiling `libgmp.a` compared to normal TA build environment.

**Comment by vascoguita** [comment]
In the link bellow you may find a port of the PBC library to OP-TEE:
https://github.com/vascoguita/optee_pbc

But first you must install the port of the GMP library to OP-TEE:
https://github.com/vascoguita/optee_gmp

Instructions to accomplish this are provided in the above repositories.

To include it in a TA just add the following lines to your Makefile:

```
LDADD += $(TA_DEV_KIT_DIR)/lib/pbc.a
LDADD += $(TA_DEV_KIT_DIR)/lib/libgmp.a
```
