### ISSUE TITLE
invoke TA from a shared library

### ISSUE THREAD

**Issue by mnwrhsn** [OP-TEE/optee_os#2951]
Hello,

I am trying to trap some I/O calls (say `read`, `write`, `ioctl`, etc) from a NW application -- the idea is to trap that system calls and invoke a TA session say using `LD_PRELOAD`. I am wondering is there any way that I can initiate TA session as a shared library (say without any main function as in the hello_world examples) and compile host TA file as `.so` object? What changes I need in the host Makefile then? Any help/pointer would be really appreciated.

**Comment by jiwonjoung** [comment]
Yes, this should be possible. You only need the stuff between InitializeContext and FinalizeContext to trigger a context switch. You just need to figure out how to compile your shared library with the TEE APIs.

**Comment by mnwrhsn** [comment]
Ok, sounds good. Let me try.

**Comment by mnwrhsn** [comment]
Hello, I am trying to implement TA as a shared library and use `LD_PRELOAD` to wrap some system call. For now, let's consider the simple example: https://catonmat.net/simple-ld-preload-tutorial-part-two

Based on the suggestions above, I modified the hello_world OPTEE example as follows:

```
FILE *fopen(const char *path, const char *mode) {
        printf("In our own fopen, opening %s\n", path);
        FILE *(*original_fopen)(const char*, const char*);

        original_fopen = dlsym(RTLD_NEXT, "fopen");
	
        call_secure_routine();
	return (*original_fopen)(path, mode);

}
```
where `call_secure_routine()` is exactly same in the `main()` of the hello_world example. I also modified the `Makefile` for the client as (rest is same as in the hello world):

```
LDADD += -fPIC -shared -ldl # for shared library
```

When I run the NW app `prog` with `LD_PRELOAD` to TA-Client (`rt_io_sec_client` here), e.g., : `LD_PRELOAD=/bin/rt_io_sec_client ./prog`, I got the following output (and error):

```
Calling the fopen() function...
In our own fopen, opening test.txt
prog: TEEC_InitializeContext failed with code 0xffff0008
```

Any thoughts?

**Comment by jbech-linaro** [comment]
`0xffff0008` is `TEE_ERROR_ITEM_NOT_FOUND`? You have the TA in place? It has the correct UUID?

**Comment by jforissier** [comment]
Note that the error code can be misleading because almost all errors end up with this code. IMO this should be fixed but we couldn't reach an agreement in https://github.com/OP-TEE/optee_os/pull/2847 :(

**Comment by mnwrhsn** [comment]
Sorry I suppose the TA in place correctly (I can see the *ta) in `/lib/optee_armtz`. If I run the NW client a general program (say with `main()` and without `-fPIC` flag etc.) it runs completely fine. I suppose the problem is due to make it as a shared library?
