### ISSUE TITLE
protobuf error in QEMU build

### ISSUE THREAD

**Issue by jiwonjoung** [OP-TEE/optee_os#2960]
I am receiving many protobuf errors in q build for QEMU v7. 
This is out of the box and I have installed the protobuf library. 
I see the first error saying libprotobuf-lite.so.9 was not found and indeed I  have libprotobuf-lite.so.18. How can I update the build to use libprotobuf-lite.so.18? 

'NOTE: cross-compilers enabled:  'arm-linux-gnueabihf-gcc'
make -C /home/tee/build/../qemu
make[1]: Entering directory '/home/tee/qemu'
  GEN     config-host.h
	CHK version_gen.h
  GEN     trace/generated-tcg-tracers.h
  GEN     trace/generated-helpers-wrappers.h
  GEN     trace/generated-helpers.h
  GEN     trace/generated-helpers.c
  GEN     module_block.h
  CC      block.o
  LINK    qemu-nbd
  LINK    qemu-img
  LINK    qemu-io
  GEN     arm-softmmu/config-target.h
  GEN     trace/generated-helpers.c
  LINK    arm-softmmu/qemu-system-arm
/usr/bin/ld: warning: libprotobuf-lite.so.9, needed by //usr/lib/x86_64-linux-gnu/libmirclient.so.9, not found (try using -rpath or -rpath-link)
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteInt64(int, long, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytes(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::MessageLite::SerializeAsString[abi:cxx11]() const'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::MessageLite::ParseFromArray(void const*, int)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedOutputStream::~CodedOutputStream()'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteDouble(int, double, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::VerifyVersion(int, int, char const*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBool(int, bool, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteUInt32(int, unsigned int, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::StringTypeHandlerBase::Delete(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::StringOutputStream::StringOutputStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteMessage(int, google::protobuf::MessageLite const&, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `vtable for google::protobuf::internal::FunctionClosure0'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `typeinfo for google::protobuf::MessageLite'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::ReadString(google::protobuf::io::CodedInputStream*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::FunctionClosure0::~FunctionClosure0()'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::MessageLite::SerializeToArray(void*, int) const'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize32Fallback(unsigned int)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedInputStream::ReadLittleEndian64Fallback(unsigned long*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::InitEmptyString()'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::MessageLite::~MessageLite()'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::Closure::~Closure()'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedInputStream::ReadVarint64Fallback(unsigned long*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedInputStream::BytesUntilLimit() const'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::StringOutputStream::~StringOutputStream()'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::empty_string_once_init_'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::ReadBytes(google::protobuf::io::CodedInputStream*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::MessageLite::ParseFromString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::StringTypeHandlerBase::New[abi:cxx11]()'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32(unsigned int)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedOutputStream::CodedOutputStream(google::protobuf::io::ZeroCopyOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedInputStream::ReadTagFallback()'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteEnum(int, int, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedOutputStream::WriteRaw(void const*, int)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Swap(google::protobuf::internal::RepeatedPtrFieldBase*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::OnShutdown(void (*)())'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::DoNothing()'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::GoogleOnceInitImpl(long*, google::protobuf::Closure*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedOutputStream::VarintSize64(unsigned long)'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedInputStream::ReadLittleEndian32Fallback(unsigned int*)'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::MessageLite::SerializeWithCachedSizesToArray(unsigned char*) const'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::internal::empty_string_[abi:cxx11]'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedInputStream::PopLimit(int)'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::MessageLite::InitializationErrorString[abi:cxx11]() const'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteInt32(int, int, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedInputStream::ReadVarint32Fallback(unsigned int*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::ShutdownProtobufLibrary()'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteSInt32(int, int, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::WriteFloat(int, float, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `typeinfo for google::protobuf::Closure'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::internal::WireFormatLite::SkipField(google::protobuf::io::CodedInputStream*, unsigned int, google::protobuf::io::CodedOutputStream*)'
//usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3: undefined reference to `google::protobuf::io::CodedInputStream::PushLimit(int)'
//usr/lib/x86_64-linux-gnu/libmirclient.so.9: undefined reference to `google::protobuf::internal::LogMessage::operator<<(char const*)'
collect2: error: ld returned 1 exit status
Makefile:199: recipe for target 'qemu-system-arm' failed
make[2]: *** [qemu-system-arm] Error 1
Makefile:483: recipe for target 'subdir-arm-softmmu' failed
make[1]: *** [subdir-arm-softmmu] Error 2
make[1]: Leaving directory '/home/tee/qemu'
Makefile:81: recipe for target 'qemu' failed
make: *** [qemu] Error 2
root@beirut:/home/tee/build# '

**Comment by jbech-linaro** [comment]
I've never seen this issue. I'm about to do a QEMU v7 build for the 3.5.0 release, so let me get back to you in a moment when I've done so.

Side note, I have `libprotobuf-lite.so.10` in `/usr/lib/x86_64-linux-gnu/libprotobuf.so.10` on my machine. It might be that there is a dependency to a library that we haven't in the [pre-reqs](https://optee.readthedocs.io/building/aosp/aosp.html#prerequisites)?

**Comment by jbech-linaro** [comment]
@jiwonjoung , I've just tried a QEMU v7 setup from scratch using latest. No build issues and xtest works as expected (see https://github.com/OP-TEE/optee_os/pull/2937#issuecomment-485783712).

Having that said, can you try to get the libproto-buf package for the distro that you are using and see if that makes any difference?

**Comment by jiwonjoung** [comment]
turned out to be because of conflicting installation. solved by uninstalling and building protobuf fresh from source! thanks!!
