### ISSUE TITLE
(shared) memory: questions

### ISSUE THREAD

**Issue by piachristel** [OP-TEE/optee_os#2964]
Hi!

While reading the doc/issues and developing TA's, I am facing some theoretical questions related to (shared) memory. I would be very glad about some answers! Thanks in advance!

1. 
Each **TA context** has a small L1 translation table and therefore 32MiB main memory available (see https://optee.readthedocs.io/architecture/core.html#mmu).
Does **TA context** refer to the `TEEC_Context` returned by the `TEEC_InitializeContext` function?

2.
question "Q: What’s the maximum size for heap and stack? Can it be changed?" (https://optee.readthedocs.io/faq/faq.html) states:
> there are 32MB DDR dedicated for OP-TEE. 1MB for TEE RAM and 1MB for PUB RAM, this leaves 30MB for Trusted Applications. In the Trusted Applications, you set TA_STACK_SIZE and TA_DATA_SIZE. Typically, we set stack to 2KB and data to 32K.

a. Does this 32MB DDR correspondent to the 32MiB in 1.?
b. `TA_STACK_SIZE` + `TA_DATA_SIZE` = 30 MB or is `TA_STACK_SIZE` + `TA_DATA_SIZE` just a part of the `TA_RAM (30 MB)`?
c. Is the `Shared Memory` part of  `TA_STACK_SIZE` + `TA_DATA_SIZE`?

3.
According to https://optee.readthedocs.io/architecture/trusted_applications.html#ree-filesystem-ta:
> REE filesystem TA's are stored in the untrusted REE filesystem (decrypted, but signed) and are passed to the OP-TEE core by the tee-supplicant.
> Secure Storage TA binary is encrypted and integrity protected and stored in untrusted REE filesystem (flash memory).

Is the Secure Storage TA also loaded by the tee-supplicant?

4.
Once the TA is loaded, is it stored in the `Shared Memory`?

5.
One TA A can call another TA B by using the Internal Client API (section 4.9 of TEE Internal Core API Specification Version 1.1). Does the TA B get loaded into `Shared Memory` by calling `TEE_OpenTASession`?

**Comment by jenswi-linaro** [comment]
> Does TA context refer to the TEEC_Context returned by the TEEC_InitializeContext function?

No, it's rather related to `TEEC_Session`.

> What’s the maximum size for heap and stack? Can it be changed?

Maximum size depends on several factors so it's hard to tell what's the maximum. Yes, it can be changed.

> Does this 32MB DDR correspondent to the 32MiB in 1.?

No


> TA_STACK_SIZE + TA_DATA_SIZE

Yes, those are just part of `TA_RAM.

> Is the Shared Memory part of TA_STACK_SIZE + TA_DATA_SIZE?

No, that's something else.

> Is the Secure Storage TA also loaded by the tee-supplicant?

Yes, indirectly since tee-supplicant also loads Secure Storage data.

> Once the TA is loaded, is it stored in the Shared Memory?

No, but REE filesystem TA's are temporarily stored in shared memory while being copied into secure memory.

> Does the TA B get loaded into Shared Memory by calling TEE_OpenTASession?

Only as a way of copying it into secure memory.

**Comment by piachristel** [comment]
Thanks for your prompt answer!
I have some follow-up questions...

1.& 2.a So `TEEC_Session` uses a small 32 MiB translation table which does not relate to the 32 MB DDR dedicated to OP-TEE. The usage of this 32 MB DDR is clear and is described in `question "Q: What’s the maximum size for heap and stack? Can it be changed?" (https://optee.readthedocs.io/faq/faq.html)`... but what does the 32MiB translation table map then?
2.b. OK
2.c. Where does the `Shared Memory`then belong to? Isn't it part of the 32 MB DDR stack at all?
3. OK
4.&5. The `Secure Memory`you are talking about, does it refer to `TEE RAM` or `TA RAM`? If not, to what then? And is there a restriction of how much secured memory is available?

**Comment by jenswi-linaro** [comment]
> what does the 32MiB translation table map then?

It maps only as much as is needed, this way more than one TA can be loaded at a time.

> Where does the Shared Memory then belong to?

It can either be memory registered with `TEEC_RegisterSharedMemory()` from calling user space process or it can be memory from a static pool of shared memory `NSEC_SHM`.

> The Secure Memory you are talking about, does it refer to TEE RAM or TA RAM?

In this case it's `TA_RAM`

> And is there a restriction of how much secured memory is available?

That depends on the platform.

**Comment by piachristel** [comment]
Thanks!
So if I have understood you correctly, the `Shared Memory` not part of `DDR stack (PUB RAM, TEE RAM, TA RAM)`?

**Comment by jenswi-linaro** [comment]
Shared memory is part of DDR, possibly PUB RAM depending on configuration.

**Comment by piachristel** [comment]
Does `TEE_CloseTASession` (Internal Client API, section 4.9 of TEE Internal Core API Specification Version 1.1) remove the TA copy in the Secured Memory (`TA RAM`)?

**Comment by jenswi-linaro** [comment]
It's the same principle regardless if the session is opened from another TA or from non-secure world. Yes, the memory is freed when the last open session connected to a context are closed.

**Comment by piachristel** [comment]
Thanks so much!
