### ISSUE TITLE
Opening Context in OPTEE-OS

### ISSUE THREAD

**Issue by pokitoz** [OP-TEE/optee_os#2965]
From Global Platform API (TEE_Client_API_Specification-V1.0_c) `TEEC_InitializeContext` takes as an argument the name of the TEE or if specified NULL, it will take the default.

Is this set for multiple TEE and used when multiple TEE-OS instances are running (virtualization)?
How can I get the name of the TEE running on my machine in the case of OPTEE-OS?

In the document it is written: 

> The number of concurrent contexts which may exist is implementation-defined, and may additionally depend on run-time resource constraints

How many Context can be opened concurrently and is there a way to restrict the number of concurrent contexts in OPTEE-OS ?

Thanks!

**Comment by etienne-lms** [comment]
> Is this set for multiple TEE and used when multiple TEE-OS instances are running (virtualization)?

Could be, or could also be used by a client to check the TEE-OS is the expected one.

> How can I get the name of the TEE running on my machine in the case of OPTEE-OS?

It is "optee-tz", see https://github.com/OP-TEE/optee_client/blob/3.4.0/libteec/src/tee_client_api.c#L86.

> How many Context can be opened concurrently and is there a way to restrict the number of concurrent contexts in OPTEE-OS ?

There is no way to limit that number in current OP-TEE. The current limit is related to the memory available in client (I.e Linux OS) to allocate a context reference.

**Comment by pokitoz** [comment]
Thanks for your reply !
