### ISSUE TITLE
Trying to compile optee_examples

### ISSUE THREAD

**Issue by jiwonjoung** [OP-TEE/optee_os#2968]
Hello, I am trying to compile optee_examples based on this example: https://optee.readthedocs.io/building/gits/optee_examples/optee_examples.html?highlight=optee_examples

However,am getting a strange error in tee_api_types.h . 
```
expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__aligned’
 typedef uint32_t TEE_BigIntFMMContext __aligned(__alignof__(void *));
```
Is there some compiler option that I am failing to set? 
Here is the full error: 
```
jiwon@calcifer:/research/optee/optee_examples/hello_world/ta$ make     CROSS_COMPILE=arm-linux-gnueabihf-     PLATFORM=vexpress-qemu_virt     TA_DEV_KIT_DIR=/research/optee/optee_os/out/arm/export-ta_arm32 CFLAGS=-Wfatal-errors
  CC      hello_world_ta.o
In file included from /home/jiwon/research/optee/optee_os/out/arm/export-ta_arm32/include/tee_api.h:13:0,
                 from /home/jiwon/research/optee/optee_os/out/arm/export-ta_arm32/include/tee_internal_api.h:10,
                 from hello_world_ta.c:28:
/home/jiwon/research/optee/optee_os/out/arm/export-ta_arm32/include/tee_api_types.h:171:39: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__aligned’
 typedef uint32_t TEE_BigIntFMMContext __aligned(__alignof__(void *));
```

**Comment by jbech-linaro** [comment]
There is one issue in the docs, I have a patch for [it](https://github.com/jbech-linaro/optee_docs/commit/601828443dd637905281e841b5b2fdb3815686ca), do as what I've described in that patch. With that everything works as it should, I've just tried it by following the instructions. See my log file [here](http://ix.io/1H9I).

Have you exported the toolchain to the PATH? What does `which arm-linux-gnueabihf-gcc` say?
