### ISSUE TITLE
Vendor property best practices and tee_otp_get_die_id

### ISSUE THREAD

**Issue by dmcilvaney** [OP-TEE/optee_os#2969]
This will be a bit of walk back in history.

### Rationale
We would like to generate a secret seed value for our TPM TA which is dependent on hardware and will always be re-derived in the event RPMB is cleared. This value should be distinct between TAs (hence also hashing the TA's UUID).

### vendor_props
I would like to make use of a vendor specific property (actually the same one as in 9161df5004527bdc9616dd4956c972a50893dc95). Is this still considered the ideal way to do this? My implementation replaces tee_otp_get_die_id() with tee_otp_get_hw_unique_key() but otherwise follows the same pattern.

In the existing implementation: https://github.com/OP-TEE/optee_os/blob/e61fc00f9643fb55f2b19d1168d86b9b15d8d9c9/core/arch/arm/plat-vexpress/vendor_props.c#L32 it looks like `uint32_t bin[...] ` is mapping onto the `prop_value` union https://github.com/OP-TEE/optee_os/blob/64a5011e3774c8664fefc6dff966d0096cdd56d7/lib/libutee/tee_api_property.c#L52 (removed in ff857a3ae7de6d1c5929af477a32407bdf10e69d). I'm assuming that the `binary` member of the union never made it upstream, and hence setting bin[0] equal to the length of the buffer is meaningless and the correct way of representing the size of the returned binary is via the `size_t *blen` parameter?

### tee_otp_get_die_id()  vs.  tee_otp_get_hw_unique_key():
I wasn't able to find a description of the expected behaviour of these functions. The HUK is quite self-explanatory and we get it from the iMX6 CAAM, but tee_otp_get_die_id() is more confusing.

What is the expected behaviour of tee_otp_get_die_id? The weak implementation fills out the buffer to any desired length, and no attempt is made to check how much data might be returned by a real implementation. Does this imply that a real implementation must pad out the buffer to the requested size in a deterministic fashion?

Is there any direction on what type of data should be returned by this function (ie production run #, CPU type, etc.? How unique should it be across a set of devices?). If our platform does not have a suitable source of data, are there significant issues leaving the weak implementation in place? An alternative for us might be to take half of HUK and use it since tee_otp_get_hw_unique_key() only consumes half of the available data.

**Comment by jenswi-linaro** [comment]
I think we're all a bit rusty when it comes to vendor_props. Your guess is as good as mine.

`tee_otp_get_die_id()` does indeed seem a bit strange. I think the weak implementation should be replaced with something useful and would only be overridden if the platform has a special need. Basing it on `tee_otp_get_hw_unique_key()` seems like a good idea. I'll propose something in a PR.

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/optee_os/pull/2970

**Comment by dmcilvaney** [comment]
Thanks Jens, I appreciate you having a look.

#2970 looks solid, although I'm going to go ahead and split our source of HW ID into two 16 byte chunks and derive the die ID from the second half of that.

I'll also see about putting in an update the existing vexpress `vendor_prop.c` next time we look at upstreaming.
