### ISSUE TITLE
xtest fails when both CFG_REE_FS and CFG_RPMB_FS set to y

### ISSUE THREAD

**Issue by vchong** [OP-TEE/optee_os#2972]
- stock qemu v8 build from build.git repo sync-ed today
- the only change is to the flags above
- xtest ok when only one of the two set to y

**Comment by vchong** [comment]
Hrm.. ok on hikey though?
https://github.com/OP-TEE/optee_os/pull/2973
https://optee.mooo.com:5000/logs/OP-TEE/optee_os/2973/273968443/3b612e56c9b9d808754b0ef342c5c1666efb7f38#01-hikey6220-test

**Comment by jforissier** [comment]
Have you set `CFG_RPMB_WRITE_KEY=y`? ;-)

Regarding IBART, I don't remember where one can find the build flags (which is why I think the build scripts should be in optee_os like Travis or Shippable but that's a separate issue that I know is being considered by @jbech-linaro). But I'm quite sure RPMB is enabled by default.

**Comment by vchong** [comment]
> Have you set CFG_RPMB_WRITE_KEY=y? ;-)

Thanks! That was it.

> Regarding IBART, I don't remember where one can find the build flags (which is why I think the build scripts should be in optee_os like Travis or Shippable but that's a separate issue that I know is being considered by @jbech-linaro). But I'm quite sure RPMB is enabled by default.

Found them here: https://github.com/jbech-linaro/ibart/blob/master/jobdefs/examples/hikey6220.yaml#L37

Do you want to default `CFG_RPMB_FS` to `y` in `optee_os`, i.e. #2973?

**Comment by vchong** [comment]
> Do you want to default CFG_RPMB_FS to y in optee_os, i.e. #2973?

I guess this won't do since it won't work without `CFG_RPMB_WRITE_KEY=y` which we don't want to set as default so please ignore the question.
