### ISSUE TITLE
how to measure memory usage of the TA

### ISSUE THREAD

**Issue by mofanv** [OP-TEE/optee_os#2975]
Hello,

We have developed an application that runs in both normal and trusted sides. During the evaluation, I want to measure the memory usage of the Client Application and the Trusted Application separately. I was using the file `proc/<pid>/stat` to check CPU time and memory usage, but this memory usage seems to include both CA and TA.

Can I **only** measure the **memory usage** of the TA or the CA? And I'm also confusing that, if the TZ only trusts the signed application, even the OS doesn't have access to the enclave on memory, so how the OS know the memory usage of the TA? Any suggestion would be appreciated.

Many thanks,
Fan

**Comment by jenswi-linaro** [comment]
The size of the TA is not included in `proc/<pid>/stat`.

**Comment by mofanv** [comment]
> The size of the TA is not included in `proc/<pid>/stat`.

Hi @jenswi-linaro , thanks for your reply.

I'd like to make it clearer. What I want to measure is the real-time memory usage in TrustZone. For example, the default size of TrustZone is 16 MiB. My TA may only use around half of it. Is there any way to measure the actual memory cost of my TA?

**Comment by jenswi-linaro** [comment]
The easiest way is probably to add some prints in OP-TEE. If you trigger an abort in the TA you'll get a report of used memory too, but I guess it may not be what you're looking for since the TA is killed after that.

**Comment by varder** [comment]
There is a xtest command that might be helpful
```
# xtest --stats --alloc
Pool:                Heap
Bytes allocated:                       10632
Max bytes allocated:                   57664
Size of pool:                          71760
Number of failed allocations:          1
Size of larges allocation failure:     792
Total bytes allocated at that failure: 57600

Pool:                
Bytes allocated:                       0
Max bytes allocated:                   0
Size of pool:                          0
Number of failed allocations:          0
Size of larges allocation failure:     0
Total bytes allocated at that failure: 0

Pool:                Secure DDR
Bytes allocated:                       573440
Max bytes allocated:                   573440
Size of pool:                          11534336
Number of failed allocations:          0
Size of larges allocation failure:     0
Total bytes allocated at that failure: 0

Pool:                
Bytes allocated:                       0
Max bytes allocated:                   0
Size of pool:                          0
Number of failed allocations:          0
Size of larges allocation failure:     0
Total bytes allocated at that failure: 0
```
