### ISSUE TITLE
Sanity of DRM stub (TUI)

### ISSUE THREAD

**Issue by foreverska** [OP-TEE/optee_os#2978]
So I'm fairly familiar with previous work with secure display esp in this project (ie the removed PL110 work).  Also the state of art (ie KNOX-esque implementations) as well the SoA/future seen in Imagination PowerVR (and similar) GPU HW VM.  So I think this development comes at a weird time but could stand as a model for more constrained processors (ie without fancy GPUs).  Not to mention a model from QEMU based development (ie PL11X/virtio-gpu/ramfb).

Does it make any sense to write a DRM driver for the Linux kernel where instead of accessing directly with the hardware it interfaces a stub for an OP-TEE TA containing a GPU driver?  The interface of which could probably mimic DRM pretty closely.  Then from the secure side TAs can draw over these requests from the rich environment.

From my time with ARMv8-M I know there is some overhead here but I wasn't sure if there was other more compelling practicality concerns of this idea.

**Comment by jbech-linaro** [comment]
Hi Adam,

> Does it make any sense to write a DRM driver for the Linux kernel where instead of accessing directly with the hardware it interfaces a stub for an OP-TEE TA containing a GPU driver? The interface of which could probably mimic DRM pretty closely. Then from the secure side TAs can draw over these requests from the rich environment.

The idea is interesting, but I have two concerns. The first is to move down all the GPU related stuff to secure side increases the footprint on that side, i.e., more code means a greater risk of security bugs. The second part is to be able to convince Linux kernel people that this is a good idea. Kernel already "owns" the GPU, so for builds who would incorporate something like you've proposed would need to either fully give away the GPU to the secure side or still share it with Linux kernel in some way. This is probably one of those things that better start out as a prototype and if it gets the job done, then try to promote it at conferences etc and talk to various maintainers who might be affected by it.

**Comment by foreverska** [comment]
Hi Joakim

I deeply agree on code size concerns.  PL11X/RamFB a single programmer can write in a couple hundred lines and understand the effect of all of them but those are simplistic devices.  From a pure security perspective this idea dies somewhere around there.  Maybe someone can formally prove a more advanced driver.  I still think best case we will see driver code in TA but with HW VMs the TA can choose what to support rather than supporting everything for the sake of REE.

In the end I'm not sure the Linux guys will ever accept it.  I think there's a case to prototype it. If it exists as a patch in a branch of this or another project for a few years, it helps people develop concepts for TUI in vanilla Linux and is eventually replaced by ubiquitous security aware GPUs I think there might be value.
