### ISSUE TITLE
registers cannot be set after enabling the mmu

### ISSUE THREAD

**Issue by sanxingcn** [OP-TEE/optee_os#2980]
In the function main_init_gic of main.c ，I use phys_to_virt_io to convert physical addresses to virtual addresses。In addition, I registered the physical address at the beginning of main.c.As follows.
------------------------------------------------------------------------
	gicc_base = (vaddr_t)phys_to_virt_io(GICC_BASE);
	gicd_base = (vaddr_t)phys_to_virt_io(GICD_BASE);
-------------------------------------------------------------------------
        #ifdef GIC_BASE
        register_phys_mem(MEM_AREA_IO_SEC, GIC_BASE, CORE_MMU_DEVICE_SIZE);
        #endif
-------------------------------------------------------------------------
However, the system stucked when I wrote a value to the register。
Any help would be appreciated. Thank you.

**Comment by Emantor** [comment]
One common case for stuck systems is that the clocks for the destination device are not enabled. The transaction on the bus can never complete and will block the whole system. Which device are you working on?

**Comment by sanxingcn** [comment]
@Emantor  I 'm working on rock-chip  3399. I can write registers before I enable the MMU.

**Comment by Emantor** [comment]
Looking at the `plat-rockchip` folder, the rk3399 is not an officially supported platform. Maybe additional setup is required for the rk3399 before the MMU can be enabled.

**Comment by sanxingcn** [comment]
I replaced phys_to_virt_io with phys_to_virt, and then the problem is solved.
