### ISSUE TITLE
Adding static library to TA

### ISSUE THREAD

**Issue by piachristel** [OP-TEE/optee_os#2984]
I have tried to link a static library to a TA (based on the hints of the issues related to that topic and to the documentation (https://optee.readthedocs.io/faq/faq.html?highlight=link%20library#q-how-do-i-link-a-library-into-a-trusted-application).

1. 
I have added the library `add` to the `ta/library` dir. Then in `ta/library/add` I have created the static library with
```
aarch64-linu-gnu-gcc -c *.c
ar -cvq mylib.a *.o
```
And then copied the mylib.a file into the `ta/library`dir.

2.
In `ta/sub.mk`, I have added:
```
libdirs += library/
libnames += mylib
libdeps += libmylib.a
```

3.
In `ta/Makefile` 
below `CPPFLAGS...`, I have added:
`LDFLAGS += -static`
and below `-include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk`, I have added:
`ldargs-$(binary).elf += mylib`

4.
But then running `make buildroot` gives the following error:
```
make[3]: Nothing to be done for 'all'.
Building /home/ubuntu/optee-project/out-br/build/optee_examples-1.0/hello_world_lib/ta/Makefile
make[3]: *** No rule to make target 'libmylib.a', needed by 'out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.elf'.  Stop.
package/pkg-generic.mk:229: recipe for target '/home/ubuntu/optee-project/out-br/build/optee_examples-1.0/.stamp_built' failed
make[2]: *** [/home/ubuntu/optee-project/out-br/build/optee_examples-1.0/.stamp_built] Error 2
Makefile:16: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/ubuntu/optee-project/out-br'
common.mk:201: recipe for t
```
I have tried different options for `mylib` in `ldargs-$(binary).elf +=`.
But none of it helped.
What am I missing?

**Comment by dmcilvaney** [comment]
I spent some time getting a library linked in a few months ago. Only difference I see in the sub.mk is the libdeps. Try changing `libdeps += libmylib.a` to `libdeps += library/libmylib.a`.

**Comment by piachristel** [comment]
Thanks!
