### ISSUE TITLE
Qemu DMA Transfer

### ISSUE THREAD

**Issue by foreverska** [OP-TEE/optee_os#2985]
I am writing a Qemu fw_cfg driver against the virt machine for optee_os as part of a larger project.   The first day checking signatures and enumerating files went great.  However, I have been debugging DMA transfers for three days.  The assumption I am currently operating under is QEMU does not recognize secure RAM as ram or an IO device so it fails to do the DMA transfer.  Please, someone correct me if I'm wrong there.

So the next step is to try this operation against normal ram.  Is there a way to malloc normal RAM from an optee_os driver?

Is there a reason the virt machine doesn't have a portion of RAM for OPTEE_OS/TA use?  Or does it and I'm missing something?

**Comment by jenswi-linaro** [comment]
My knowledge of QEMU internals is very limited, so take my speculations with a grain of salt. The secure RAM is only allowed secure accesses, perhaps you're DMA transfer isn't doing a secure access?

> Is there a way to malloc normal RAM?

You can use `thread_rpc_alloc_payload()` for testing purposes. For best result you should compile OP-TEE with `CFG_CORE_DYN_SHM=n` if you're on latest (after 3.5.0 release) or `CFG_DYN_SHM_CAP=n` if you on something before the 3.5.0 release.

> Is there a reason the virt machine doesn't have a portion of RAM for OPTEE_OS/TA use?

The secure RAM is RAM as far as OP-TEE is concerned.

**Comment by foreverska** [comment]
It's the DMA access built into FW_CFG.  It may not search secure memory ever.  We're probably on equal footing as to the internals of QEMU so your guess is as good as mine there.  Twelve calls down the stack and I lose context.

Are you sure about thread_rpc_alloc_payload?  The system locks up when I call this function.  This development work is inside the kernel as a "service."  Don't know if that makes a difference.

Yea... there are a couple unknowns.  Is secure ram a special device not subject to DMA (where normal ram with a secure flag can be DMAed), is the secure flag stopping DMA or does the DMA not search secure memory?  A secure section of normal ram would help here but I get it.

**Comment by foreverska** [comment]
Okay so I more or less figured this out.

I moved the secure memory to the insecure memory map.  Obviously this degrades the system but works as a proof of the issue.  It works perfectly, I can DMA "secure" memory from FW_CFG.  So I'm lead to believe that FW_CFG searches for DMA memory in it's own memory space.

If that's true I think FW_CFG needs to be moved to secure memory in these scenarios.  If a secure device is configured using FW_CFG you wouldn't want nonsecure to have access to that.  You would want to give a TA a chance to validate access to FW_CFG.  Similarly a TA would want to validate memory passed to drivers from NS via FW_CFG are in NS memory so as not to accidentally leak secure memory.

Correct me if I'm wrong somewhere.
