### ISSUE TITLE
VFS: Cannot open root device "ubi0:rootfs" on IMX6ULL

### ISSUE THREAD

**Issue by sumitgajjar-19** [OP-TEE/optee_os#2997]
Hello,

I'm using IMX6ULL module with following:
- Linux kernel version : 4.9.144-2.8.5+g5758a8e
- OPTEE branch master with commit ID : 1a4fa97dca1dd980b615f7e8355a3fbeed4b4509

Issue:
- I'm not able to load Root filesystem when using OPTEE, when not using OPTEE just booting Linux kernel from u-boot bootloader it's able to load the Root filesystem.

I've attached the failure log.
[Failure.log](https://github.com/OP-TEE/optee_os/files/3165136/Failure.log)

Thanks and Regards,
Sumit Gajjar

**Comment by jforissier** [comment]
Hi @sumitgajjar-19,

It would be interesting to compare the boot log with a successful one, to try and understand why the kernel does not find the boot device.

**Comment by sumitgajjar-19** [comment]
Hello @jforissier,

Please find the logs for success case booting kernel without OPTEE.
[Success.log](https://github.com/OP-TEE/optee_os/files/3165622/Success.log)

**Comment by jforissier** [comment]
I'd say the interesting part in the kernel boot log is when the nand driver initializes.

Success.log:
```
[    0.973774] nand: device found, Manufacturer ID: 0xc2, Chip ID: 0xdc
[    0.980217] nand: Macronix MX30LF4G28AC
[    0.984190] nand: 512 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 112
[    0.992754] gpmi-nand 1806000.gpmi-nand: mode:5 ,failed in set feature.
[    0.999929] Bad block table found at page 262080, version 0x01
[    1.006531] Bad block table found at page 262016, version 0x01
[    1.012951] nand_read_bbt: bad block at 0x000000f80000
[    1.018825] 5 ofpart partitions found on MTD device gpmi-nand
[    1.024742] Creating 5 MTD partitions on "gpmi-nand":
[    1.029888] 0x000000000000-0x000000080000 : "mx6ull-bcb"
[    1.036523] 0x000000080000-0x000000200000 : "u-boot1"
[    1.042736] 0x000000200000-0x000000380000 : "u-boot2"
[    1.048827] 0x000000380000-0x000000400000 : "u-boot-env"
[    1.055231] 0x000000400000-0x000020000000 : "ubi"
[    1.073141] gpmi-nand 1806000.gpmi-nand: driver registered.
```
Failure.log:
```
[    0.980468] nand: device found, Manufacturer ID: 0xc2, Chip ID: 0xdc
[    0.986912] nand: Macronix MX30LF4G28AC
[    0.990888] nand: 512 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 112
[    0.999432] gpmi-nand 1806000.gpmi-nand: mode:5 ,failed in set feature.
[    1.006585] Bad block table found at page 262080, version 0x01
[    1.013200] Bad block table found at page 262016, version 0x01
[    1.019601] nand_read_bbt: bad block at 0x000000f80000
[    1.026575] gpmi-nand 1806000.gpmi-nand: driver registered.
```

So, there is something the kernel doesn't like on the nand flash ("Bad block"). What is it that the bootloader is doing with the NAND at the beginnig? There are differences here, too. In Success.log, we can see "Erasing NAND..." and "Writing to NAND..." which are not in Failure.log.

I don't know your setup so I can't say much more I guess, but I hope it helps!

**Comment by sumitgajjar-19** [comment]
Hi @jforissier,

In u-boot(bootloader) previously I have made changes according to my application that's the reason there is the difference in u-boot log, so now I have removed all my changes and I'm using u-boot with below version and branch:
- u-boot version : 2016.11-2.8.5
- u-boot commit : 02735f400478c6e9afc432fda1149abef630657c
- u-boot branch : 2016.11-toradex

Also, I've updated the logs by removing all my changes in u-boot and using above u-boot version.
[Success.log](https://github.com/OP-TEE/optee_os/files/3171464/Success.log)
[Failure.log](https://github.com/OP-TEE/optee_os/files/3171465/Failure.log)

Also, @MrVan may you please help me with the same?

Thanks and Regards,
Sumit Gajjar

**Comment by MrVan** [comment]
@sumitgajjar-19 I have no idea about the kernel not detect the mtd parts (:  does OP-TEE loaded from nand?

**Comment by sumitgajjar-19** [comment]
Hi @MrVan,

Right now actually I'm loading OPTEE from TFTP at 0x83000000 address, using below command following boot command:

- tftp 0x81000000 colibri-imx6ull/zImage ;tftp 0x82100000 colibri-imx6ull/imx6ull-colibri-eval-v3.dtb ;tftp 0x83000000 colibri-imx6ull/uTee
- run setup; setenv bootargs ${defargs} ${ubiargs} ${setupargs} ${vidargs}; echo Booting from NAND...; ubi part ubi && bootm 0x83000000 - 0x82100000

Thanks and Regards,
Sumit Gajjar
