### ISSUE TITLE
tee_obj_attr_to_binary() function use.

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_os#3004]
From code it looks like there are 2 uses of tee_obj_attr_to_binary() function:
TEE_Result tee_obj_attr_to_binary(struct tee_obj *o, void *data, size_t *data_len)
- To get size of attributes of object in data_len when data is sent as NULL.
- To convert attributes of object in binary form, place it in buffer pointed by data and attribute size in data_len.

If there is only above 2 uses of function, I don't understand the reason of its use here at 2 following places:
- https://github.com/OP-TEE/optee_os/blob/34050c203f4dc255af9cf77d6c89b4e0e793d081/core/tee/tee_svc_storage.c#L311 

- https://github.com/OP-TEE/optee_os/blob/34050c203f4dc255af9cf77d6c89b4e0e793d081/core/tee/tee_svc_storage.c#L966

because in both functions syscall_storage_obj_open() and syscall_storage_obj_seek(), data pointer is sent as NULL and attr_size is not used further in this function.

Please correct me if I am wrong.

**Comment by jenswi-linaro** [comment]
This seems to be a leftover from 879237aee0d08dee2c636e1fadefc842ccf5905e ("core: FS: remove fop->seek()". Those calls can probably be removed.

**Comment by sahilnxp** [comment]
@jenswi-linaro Raised a pull request removing these functions.
