### ISSUE TITLE
overflow in RPMB file system

### ISSUE THREAD

**Issue by zhupg** [OP-TEE/optee_os#3012]
Hi,
  There is overflow in RPMB file system if the rpmb_size_mult is equal to 128, that means the RPMB size is 16MB.

		if (MUL_OVERFLOW(dev_info.rpmb_size_mult,
				 RPMB_SIZE_SINGLE / RPMB_DATA_SIZE,
				 &rpmb_ctx->max_blk_idx)) {
			res = TEE_ERROR_BAD_PARAMETERS;
			goto func_exit;
		}

**Comment by jforissier** [comment]
Hi @zhupg,

Thanks for reporting. You are right, this code is wrong, because `max_blk_idx` is `uint16_t`. We need to check for overflow differently. I would suggest this (but maybe there are other options):
```C
	uint32_t nblocks = 0;

	nblocks = dev_info.rpmb_size_mult * (RPMB_SIZE_SINGLE / RPMB_DATA_SIZE);
	if (nblocks > 65536) {
		res = TEE_ERROR_BAD_PARAMETERS;
		goto func_exit;
	}
	rpmb_ctx->max_blk_idx = nblocks - 1;
```

Do you want to create a pull request? Or we can do it if you prefer.

**Comment by jenswi-linaro** [comment]
I don't get it, what's wrong with `MUL_OVERFLOW()`?

**Comment by jforissier** [comment]
@jenswi-linaro we're trying to store `65536` in a `uint16_t` (128 * (128 * 1024)  /  256).

**Comment by jenswi-linaro** [comment]
I get it, thanks. By the way, I think we should still use `MUL_OVERFLOW()` for the new multiplication even if it's not possible to overflow with it. It's easier and more safe that way than explaining in a comment why `MUL_OVERFLOW()` isn't needed right now.

**Comment by jforissier** [comment]
@jenswi-linaro fair enough!

**Comment by jforissier** [comment]
...but note we will still need to check manually for `nblocks > 65536`.

**Comment by jenswi-linaro** [comment]
We could do
```C
if (MUL_OVERFLOW(dev_info.rpmb_size_mult,
                 RPMB_SIZE_SINGLE / RPMB_DATA_SIZE, &nblocks) ||
    SUB_OVERFLOW(nblocks, 1, &rpmb_ctx->max_blk_idx) {
        res = TEE_ERROR_BAD_PARAMETERS;
        goto func_exit;
}

**Comment by zhupg** [comment]
@jforissier Please create the pull request, thank you.

**Comment by jforissier** [comment]
@zhupg sure. If you want me to add your `Reported-by:` tag to the commit, please write it here (you don't have to, but it's fair to credit people).

**Comment by zhupg** [comment]
@jforissier ok, thanks.
Reported-by: Pengguang Zhu <zpghao@163.com>
