### ISSUE TITLE
How to build PTA

### ISSUE THREAD

**Issue by zcchai-iotex** [OP-TEE/optee_os#3024]
I am trying to build a PTA , but stuck with the "TA not found " issue. 

I started with a very simple test case. I didn't even add my own pTA, but cloned the Hello World examples, with updated UUID as STATS_UUID (for existing PTA core/arch/arm/pta/stats.c). So I believe the PTA should already be in my OPTEE_OS image.

However, when I run my CA, there was error: 
"
ERR [3684] TEES:load_ta:273:   TA not found
optee_plist: TEEC_Opensession failed with code 0xffff0008 origin 0x3
"
I know there should be some error for directly calling STATE PTA, but should not  be "TA not found" error, right? Looks like tee-supplicant treat this request as normal TA request.
 
There are other questions regarding to PTA ：
1. Do I need to rebuild optee client(tee-supplicant) after I add new file in core/arch/arm/pta/ ?
2. Besides adding new file in core/arch/arm/pta, and updating the sub.mk file, any other updates need?
3. Is there any way I can check we a PTA is built into the OPTEE kernel? I know a normal TA could be checked under /lib/optee_armtz, how about PTA?
BTW, I notice there are other term, static TA, is that the same as PTA?

Thanks in advance

**Comment by jforissier** [comment]
Hi @zcchai-iotex,

> cloned the Hello World examples, with updated UUID as STATS_UUID

You may as well use `xtest --stats` as the client.

> So I believe the PTA should already be in my OPTEE_OS image.

Yes, should be the default on many platforms, but please make sure `CFG_WITH_STATS=y` (`grep CFG_WITH_STATS optee_os_out/*/conf.mk`).

> should not be "TA not found" error, right? 

Check the TEE core traces (CFG_TEE_CORE_DEBUG=3), you will see what UUID is requested and can double check it is correct.

> 1. Do I need to rebuild optee client(tee-supplicant) after I add new file in core/arch/arm/pta/ ?

No, it is the TEE core (tee*.bin) that needs to be rebuilt.

> 2. ... any other updates need?

No.

> 3. Is there any way I can check we a PTA is built into the OPTEE kernel?

You may check that the object file is present in the build directory, that should be a good indication. Maybe we should add a debug trace on boot (enumerate all PTAs, like we do for early TAs).

> BTW, I notice there are other term, static TA, is that the same as PTA?

Yes. We don't use "static" anymore because it is somewhat misleading and unclear.

**Comment by zcchai-iotex** [comment]
Hi @jforissier ,
Thanks for your prompt response. Those tricks do help.
I checked out the build directory ./out/arm-plat-ls/core/arch/arm/pta, expecting to find stats.o. But the stats.o is missing.

So it turns out that  CFG_WITH_STATS is not defined in NXP LS platform configure file: core/arch/arm/plat-ls/conf.mk . (But that configure option does show up in most other platforms)

Adding a line  CFG_WITH_STATS ?= y solved the issue.

**Comment by jforissier** [comment]
@zcchai-iotex glad I could help :)

> So it turns out that CFG_WITH_STATS is not defined in NXP LS platform configure file: core/arch/arm/plat-ls/conf.mk . (But that configure option does show up in most other platforms)

IMO, it does not make much sense that `CFG_WITH_STATS ?= y` is defined per-platform for a majority of platforms. Perhaps it would be better to have `CFG_WITH_STATS ?= y` in `mk/config.mk` and leave it to some platforms to do `CFG_WITH_STATS ?= n` if they do not want it in their default build?

**Comment by etienne-lms** [comment]
Looking at `CFG_TEE_CORE_EMBED_INTERNAL_TESTS`, it is default enabled. So I agree with you that `CFG_WITH_STATS` could also be default enable from `mk.config.mk`.
