### ISSUE TITLE
session use in op_attr_bignum_to_user()

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_os#3025]
Got a doubt in attribute operation function op_attr_bignum_to_user().

In other attributes function like op_attr_value_to_user() and op_attr_secret_value_to_user() we are getting the session from tee_ta_get_current_session() which is further used for checking memory permission.

I am not able to understand why we need to pass the session in op_attr_bignum_to_user(), why can't we get the session the same way as done in op_attr_value_to_user() and op_attr_secret_value_to_user().

**Comment by jenswi-linaro** [comment]
The session pointer is actually passed to all of `op_attr_bignum_to_user()`, `op_attr_value_to_user()` and `op_attr_secret_value_to_user()`, but it's only `op_attr_bignum_to_user()` which uses it.

Yes, we could skip passing the session pointer and read it with `tee_ta_get_current_session()` when needed. However, the session pointer is already read in `syscall_cryp_obj_get_attr()` and that's the only caller of that function so it's no overhead to pass that pointer.

**Comment by sahilnxp** [comment]
Just a suggestion for function prototype simplification, we should remove **struct tee_ta_session sess** from to_user function prototype of **struct attr_ops**, because no other function in **struct attr_ops** is taking other argument other than pointers and size.
