### ISSUE TITLE
Memory check in tee_mm_alloc

### ISSUE THREAD

**Issue by youssefesmat** [OP-TEE/optee_os#304]
Hello,

I am having a little trouble understanding this check in tee_mm_alloc():

```c
if (((entry->offset << pool->shift) - pool->lo) < size)
```

This is a snippet from the larger:

```c
	if (pool->flags & TEE_MM_POOL_HI_ALLOC) {
		if (((entry->offset << pool->shift) - pool->lo) < size)
			/* out of memory */
			return NULL;
	} else {
		if (((entry->offset << pool->shift) - pool->lo) < size)
			/* out of memory */
			return NULL;
		if ((((entry->offset + entry->size) << pool->shift) + size) >
		    (pool->hi - pool->lo))
			/* out of memory */
			return NULL;
	}
```

Consider the case where TEE_MM_POOL_HI_ALLOC is *not* set and entry->offset is 0 and pool->lo is also 0 this check will always cause the function to return NULL.

Also, isn't entry->offset an offset from pool->lo and not an absolute address? This would generally mean that entry->offset is much smaller than pool->lo causing it to wrap since this is uint32_t.

Your input is much appreciated.

**Comment by jenswi-linaro** [comment]
Hi,

You're right, that code is broken. It doesn't look right when TEE_MM_POOL_HI_ALLOC is set either.

Yes entry->offset is an offset from pool->lo, or rather (entry->offset << pool->shift) is the relative address from pool->lo. 

Regards,
Jens

**Comment by youssefesmat** [comment]
Hello,

Thank you for reviewing the change in pull request #308.
I believe there is also an issue in this line in tee_mm_init (tee_mm.c:52):
```c
pool->entry->offset = ((hi - lo - 1) >> shift) + 1;
```
This is using the paramters hi and lo and then rounding up by one block. I believe this should use the rounded pool->hi and pool->lo instead of the parameters, or else you can end up with an offset that is past the end of the segment. 

Thanks,
Youssef
