### ISSUE TITLE
How to put my own TA binary into client

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/optee_os#3042]
Hello,

I tried to build my own TA in `$(ROOT)/myFolder` of OP-TEE 3.5.0, and I was successful.

But I want to learn how I can put the "BINARY of ca" into rootfs of client side, such as `/usr/bin`, where the optee_examples exist. And also the way to put the TA BINARY file into `/lib/optee_armtz`.

I found that before OP-TEE 3.4.0, I might write some code at the bottom (rootfs part) of `build/common.mk` to achieve my goal. But in 3.5.0 that part of the code is deleted.
I think this is because we use buildroot to build TAs into client, is that right?

I am a beginner of OP-TEE. Any help/pointer would be appreciated. Thanks!

**Comment by jforissier** [comment]
Hello @gagachang ,

You are correct, the client applications are now taken care of (installed into the root FS) by buidroot.

I think the simplest solution for you is to move your application code (both TA and CA) under `optee_examples`. Just copy one example, such as [`hello_world`](https://github.com/linaro-swg/optee_examples/tree/master/hello_world), into a new folder such as `my_app` and modify the files as needed to rename the application. The build should take care of it automatically thanks to this code: https://github.com/linaro-swg/optee_examples/blob/master/CMakeLists.txt#L28-L33.

**Comment by jbech-linaro** [comment]
I'm closing the ticket because it has been answered. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
