### ISSUE TITLE
How to build Hikey960_AOSP_OPTEE with 4G RAM

### ISSUE THREAD

**Issue by fengleichn** [OP-TEE/optee_os#3043]

**Comment by fengleichn** [comment]
i use this command to build projects
```
git clone https://github.com/linaro-swg/optee_android_manifest
./sync-p-hikey960.sh
./build-p-hikey960.sh
```
and modify /optee/optee_os/core/arch/arm/plat-hikey/conf.mk
CFG_DRAM_SIZE_GB ?= 3 to CFG_DRAM_SIZE_GB ?= 4

**Comment by fengleichn** [comment]
but CFG_DRAM_SIZE_GB=3  from ./out files ,
such as :
```
./out/arm-plat-hikey/include/generated/conf.h 
./out/arm-plat-hikey/export-ta_arm64/host_include/conf.mk:67:CFG_DRAM_SIZE_GB=3
```

**Comment by vchong** [comment]
Yes, sorry. The makefile dependency on the optee/fip build target isn't very complete yet although improvement is coming. Please delete the `optee_os` `out` dir and rebuild.

**Comment by fengleichn** [comment]
I can build build Hikey960+AOSP+ OPTEE with 4G RAM by delete optee_os build out dir and rebuild
