### ISSUE TITLE
Freeze OPTEE OS when change optee's revision number

### ISSUE THREAD

**Issue by PratikGajera** [OP-TEE/optee_os#3047]
Hello,

I am building optee os image for imx6ull board with the following details.

Kernel version: v4.19.x
U-boot version: v2016.11.x

OPTEE OS revision number:

R1: 1a4fa97dca1dd980b615f7e8355a3fbeed4b4509
R2: b8fa2c7da0e43b4619a44e21a3268f8e7ebd659d

Compilation: 

make V=1 PLATFORM=imx-mx6ulevk ARCH=arm CFG_PAGEABLE_ADDR=0 CFG_NS_ENTRY_ADDR=0x81000000 CFG_DT_ADDR=0x82000000 CFG_DT=y DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4

mkimage -A arm -O linux -C none -a 0x9DFFFFE4 -e 0x9E000000 -d ./out/arm-plat-imx/core/tee.bin uTee

optee os is working fine with R1 revision. If I change revision from R1 to R2, then optee os freezes on my screen at line "Starting kernel ..." and log here.

U-Boot 2016.11-2.7.4+g1b121c6 (May 24 2019 - 18:11:39 +0530)

CPU:   Freescale i.MX6ULL rev1.0 69 MHz (running at 396 MHz)
CPU:   Industrial temperature grade (-40C to 105C) at 45C
Reset cause: POR
DRAM:  480 MiB
NAND:  512 MiB
MMC:   FSL_SDHC: 0
Video: 640x480x18
In:    serial
Out:   serial
Err:   serial
Model: Toradex Colibri iMX6ULL 512MB Wi-Fi / Bluetooth IT V1.0A, Serial# 03073136
Net:   FEC0
Press '*' key to stop autoboot:  0 
Booting OP-TEE from NAND...
ubi0: default fastmap pool size: 200
ubi0: default fastmap WL pool size: 100
ubi0: attaching mtd1
ubi0: attached by fastmap
ubi0: fastmap pool size: 200
ubi0: fastmap WL pool size: 100
ubi0: attached mtd1 (name "mtd=4", size 508 MiB)
ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
ubi0: good PEBs: 4059, bad PEBs: 5, corrupted PEBs: 0
ubi0: user volume: 4, internal volumes: 1, max. volumes count: 128
ubi0: max/mean erase counter: 17/7, WL threshold: 4096, image sequence number: 0
ubi0: available PEBs: 0, total reserved PEBs: 4059, PEBs reserved for bad PEB handling: 75
Read 0 bytes from volume kernel to 81000000
No size specified -> Using max size (5472864)
Read 0 bytes from volume optee to 84000000
No size specified -> Using max size (270844)
Read 0 bytes from volume dtb to 82000000
No size specified -> Using max size (39436)
Booting kernel from Legacy Image at 84000000 ...
   Image Name:   
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    270780 Bytes = 264.4 KiB
   Load Address: 9dffffe4
   Entry Point:  9e000000
   Verifying Checksum ... OK
 Flattened Device Tree blob at 82000000
   Booting using the fdt blob at 0x82000000
   Loading Kernel Image ... OK
CACHE: Misaligned operation at range [9dffffe4, 9e0421a4]
   Using Device Tree in place at 82000000, end 8200ca0b
   Updating MTD partitions...

Starting kernel ...

I am stuck over here, please help me.

Thanks,
PG

**Comment by jenswi-linaro** [comment]
I doubt it's b8fa2c7 which is the culprit. Perhaps you can bisect to the problematic commit?

**Comment by PratikGajera** [comment]
@jenswi-linaro, thanks for quick response.

It may be problem in this revision number "b8fa2c7da0e43b4619a44e21a3268f8e7ebd659d". 
Before I am checking latest revision of optee os, Please provide me build step, if other than over here http://mrvan.github.io/optee-imx6ul.
What are the changes required in u-boot and kernel for booting optee os. (like a allocate RAM for optee, enable optee driver in kernel, etc)
Just,  I want to confirm at my side, if missing something.

Thanks,
PG

**Comment by jenswi-linaro** [comment]
I've never booted an IMX platform myself so you know more about building for IMX than me. Given that you booted the last release OK the instruction are probably up to date.

@MrVan, do you want to add anything?

**Comment by PratikGajera** [comment]
Hi,
@MrVan, please help me, if something missing.

I have one query that how we can calculate uTee image load address and entry address. Any specification? In which case entry and load address change?

mkimage -A arm -O linux -C none -a 0x9DFFFFE4 -e 0x9E000000 -d ./out/arm-plat-imx/core/tee.bin uTee

**Comment by jbech-linaro** [comment]
Entry: `arm-linux-gnueabihf-readelf -h ./out/arm/core/tee.elf` ?

Then for IMX devices, they use the generic memory layout file, by digging into that and look at values, you can probably figure it out also.
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/include/mm/generic_ram_layout.h

**Comment by PratikGajera** [comment]
Thanks for quick response. Yes, I understood everything about load and entry point address. How can calculate it.

I am try to boot up optee on imx6ull board, then getting below logs. Now, optee is not stuck at "Starting kernel....", but getting below error. Please suggest me, what I am doing wrong here.

ubi0: default fastmap pool size: 200
ubi0: default fastmap WL pool size: 100
ubi0: attaching mtd1
ubi0: attached by fastmap
ubi0: fastmap pool size: 200
ubi0: fastmap WL pool size: 100
ubi0: attached mtd1 (name "mtd=4", size 508 MiB)
ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
ubi0: good PEBs: 4059, bad PEBs: 5, corrupted PEBs: 0
ubi0: user volume: 4, internal volumes: 1, max. volumes count: 128
ubi0: max/mean erase counter: 17/7, WL threshold: 4096, image sequence number: 0
ubi0: available PEBs: 0, total reserved PEBs: 4059, PEBs reserved for bad PEB handling: 75
Read 0 bytes from volume kernel to 81000000
No size specified -> Using max size (5472864)
Read 0 bytes from volume optee to 84000000
No size specified -> Using max size (258636)
Read 0 bytes from volume dtb to 82000000
No size specified -> Using max size (39436)
## Booting kernel from Legacy Image at 84000000 ...
   Image Name:   
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    258572 Bytes = 252.5 KiB
   Load Address: 9dffffe4
   Entry Point:  9e000000
   Verifying Checksum ... OK
 Flattened Device Tree blob at 82000000
   Booting using the fdt blob at 0x82000000
   Loading Kernel Image ... OK
CACHE: Misaligned operation at range [9dffffe4, 9e03f224]
   Using Device Tree in place at 82000000, end 8200ca0b
   Updating MTD partitions...

Starting kernel ...

D/TC:0 0 add_phys_mem:536 TEE_SHMEM_START type NSEC_SHM 0x9fe00000 size 0x00200000
D/TC:0 0 add_phys_mem:536 TA_RAM_START type TA_RAM 0x9e100000 size 0x01d00000
D/TC:0 0 add_phys_mem:536 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x9e03f000 size 0x000c1000
D/TC:0 0 add_phys_mem:536 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x9e000000 size 0x0003f000
D/TC:0 0 add_phys_mem:536 ROUNDDOWN(IRAM_BASE, CORE_MMU_DEVICE_SIZE) type TEE_COHERENT 0x00900000 size 0x00100000
D/TC:0 0 add_phys_mem:536 AIPS3_BASE type IO_SEC 0x02200000 size 0x00100000
D/TC:0 0 add_phys_mem:536 AIPS2_BASE type IO_SEC 0x02100000 size 0x00100000
D/TC:0 0 add_phys_mem:536 AIPS1_BASE type IO_SEC 0x02000000 size 0x00100000
D/TC:0 0 add_phys_mem:536 ANATOP_BASE type IO_SEC 0x02000000 size 0x00200000
D/TC:0 0 add_phys_mem:549 Physical mem map overlaps 0x2000000
D/TC:0 0 add_phys_mem:536 GIC_BASE type IO_SEC 0x00a00000 size 0x00100000
D/TC:0 0 add_phys_mem:536 CONSOLE_UART_BASE type IO_NSEC 0x02000000 size 0x00200000
D/TC:0 0 verify_special_mem_areas:474 No NSEC DDR memory area defined
D/TC:0 0 add_va_space:575 type RES_VASPACE size 0x00a00000
D/TC:0 0 add_va_space:575 type SHM_VASPACE size 0x02000000
D/TC:0 0 dump_mmap_table:708 type IO_SEC       va 0x98c00000..0x98cfffff pa 0x02100000..0x021fffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:708 type IO_SEC       va 0x98d00000..0x98efffff pa 0x02000000..0x021fffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:708 type IO_SEC       va 0x98f00000..0x98ffffff pa 0x00a00000..0x00afffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:708 type IO_NSEC      va 0x99000000..0x991fffff pa 0x02000000..0x021fffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:708 type NSEC_SHM     va 0x99200000..0x993fffff pa 0x9fe00000..0x9fffffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:708 type TA_RAM       va 0x99400000..0x9b0fffff pa 0x9e100000..0x9fdfffff size 0x01d00000 (pgdir)
D/TC:0 0 dump_mmap_table:708 type TEE_COHERENT va 0x9b200000..0x9b2fffff pa 0x00900000..0x009fffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:708 type RES_VASPACE  va 0x9b300000..0x9bcfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0 0 dump_mmap_table:708 type IO_SEC       va 0x9be00000..0x9befffff pa 0x02200000..0x022fffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:708 type SHM_VASPACE  va 0x9bf00000..0x9defffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0 0 dump_mmap_table:708 type TEE_RAM_RX   va 0x9e000000..0x9e03efff pa 0x9e000000..0x9e03efff size 0x0003f000 (smallpg)
D/TC:0 0 dump_mmap_table:708 type TEE_RAM_RW   va 0x9e03f000..0x9e0fffff pa 0x9e03f000..0x9e0fffff size 0x000c1000 (smallpg)
D/TC:0 0 core_mmu_alloc_l2:238 L2 table used: 1/4
I/TC: 
D/TC:0 0 init_canaries:166 #Stack canaries for stack_tmp[0] with top at 0x9e06b0f8
D/TC:0 0 init_canaries:166 watch *0x9e06b0fc
D/TC:0 0 init_canaries:167 #Stack canaries for stack_abt[0] with top at 0x9e066938
D/TC:0 0 init_canaries:167 watch *0x9e06693c
D/TC:0 0 init_canaries:169 #Stack canaries for stack_thread[0] with top at 0x9e068978
D/TC:0 0 init_canaries:169 watch *0x9e06897c
D/TC:0 0 init_canaries:169 #Stack canaries for stack_thread[1] with top at 0x9e06a9b8
D/TC:0 0 init_canaries:169 watch *0x9e06a9bc
E/TC:0 0 
E/TC:0 0 Core data-abort at address 0x9b300004
E/TC:0 0  fsr 0x00000008  ttbr0 0x9e05c06a  ttbr1 0x9e05c06a  cidr 0x0
E/TC:0 0  cpu #0          cpsr 0x600001f3
E/TC:0 0  r0 0x9b300000      r4 0x82000000    r8 0x9df2d809   r12 0x00000000
E/TC:0 0  r1 0x9b300000      r5 0x9b300000    r9 0x9bf0aeb8    sp 0x9e06af20
E/TC:0 0  r2 0x00010000      r6 0x82000000   r10 0x84000040    lr 0x9e004c5f
E/TC:0 0  r3 0x9b300000      r7 0x00000000   r11 0x00000000    pc 0x9e013ea6
D/TC:0 0 get_fault_type:602 [abort] Unhandled fault!
E/TC:0 0 
E/TC:0 0 Core data-abort at address 0x9b300004
E/TC:0 0  fsr 0x00000008  ttbr0 0x9e05c06a  ttbr1 0x9e05c06a  cidr 0x0
E/TC:0 0  cpu #0          cpsr 0x600001f3
E/TC:0 0  r0 0x9b300000      r4 0x82000000    r8 0x9df2d809   r12 0x00000000
E/TC:0 0  r1 0x9b300000      r5 0x9b300000    r9 0x9bf0aeb8    sp 0x9e06af20
E/TC:0 0  r2 0x00010000      r6 0x82000000   r10 0x84000040    lr 0x9e004c5f
E/TC:0 0  r3 0x9b300000      r7 0x00000000   r11 0x00000000    pc 0x9e013ea6
D/TC:0 0 get_fault_type:602 [abort] Unhandled fault!
E/TC:0 0 
E/TC:0 0 Core data-abort at address 0x9b300004
E/TC:0 0  fsr 0x00000008  ttbr0 0x9e05c06a  ttbr1 0x9e05c06a  cidr 0x0
E/TC:0 0  cpu #0          cpsr 0x600001f3
E/TC:0 0  r0 0x9b300000      r4 0x82000000    r8 0x9df2d809   r12 0x00000000
E/TC:0 0  r1 0x9b300000      r5 0x9b300000    r9 0x9bf0aeb8    sp 0x9e06af20
E/TC:0 0  r2 0x00010000      r6 0x82000000   r10 0x84000040    lr 0x9e004c5f
E/TC:0 0  r3 0x9b300000      r7 0x00000000   r11 0x00000000    pc 0x9e013ea6
D/TC:0 0 get_fault_type:602 [abort] Unhandled fault!
E/TC:0 0 
E/TC:0 0 Core data-abort at address 0x9b300004
E/TC:0 0  fsr 0x00000008  ttbr0 0x9e05c06a  ttbr1 0x9e05c06a  cidr 0x0
E/TC:0 0  cpu #0          cpsr 0x600001f3
E/TC:0 0  r0 0x9b300000      r4 0x82000000    r8 0x9df2d809   r12 0x00000000
E/TC:0 0  r1 0x9b300000      r5 0x9b300000    r9 0x9bf0aeb8    sp 0x9e06af20
E/TC:0 0  r2 0x00010000      r6 0x82000000   r10 0x84000040    lr 0x9e004c5f
E/TC:0 0  r3 0x9b300000      r7 0x00000000   r11 0x00000000    pc 0x9e013ea6
D/TC:0 0 get_fault_type:602 [abort] Unhandled fault!
E/TC:0 0 
E/TC:0 0 Core data-abort at address 0x9b300004
E/TC:0 0  fsr 0x00000008  ttbr0 0x9e05c06a  ttbr1 0x9e05c06a  cidr 0x0
E/TC:0 0  cpu #0          cpsr 0x600001f3
E/TC:0 0  r0 0x9b300000      r4 0x82000000    r8 0x9df2d809   r12 0x00000000
E/TC:0 0  r1 0x9b300000      r5 0x9b300000    r9 0x9bf0aeb8    sp 0x9e06af20
E/TC:0 0  r2 0x00010000      r6 0x82000000   r10 0x84000040    lr 0x9e004c5f
E/TC:0 0  r3 0x9b300000      r7 0x00000000   r11 0x00000000    pc 0x9e013ea6
D/TC:0 0 get_fault_type:602 [abort] Unhandled fault!

**Comment by PratikGajera** [comment]
Hi,
Any update on above log?

**Comment by PratikGajera** [comment]
issue has been resolved by modifying tzasc controller configuration.
Thanks to all who has helped me over here.
