### ISSUE TITLE
Hardware random numbers

### ISSUE THREAD

**Issue by jonsmirl** [OP-TEE/optee_os#3054]
I noticed that only three platforms have implement access to the hardware random number generator.  If a TA is going to be used to replace a crypto security chip it needs to get hardware random numbers not pseudo ones. If the hardware RNG is not used these pseudo RNG sequences are too predictable and basically ruin the whole crypto security model.

BTW - if there is no way to salt the pseudo RNG every implementation is going to generate the same string of 'random' numbers.

What can be done to encourage more vendors to implement hardware RNG support?

Is there an API to tell if optee is using a pseudo RNG? that way crypto security code can refuse to run. This is also needed for closed source implementations (like Rockchip) where you can't look and see what the code is doing.

Could the software RNG be removed from optee so that the vendors are forced to implement hardware RNG?

jonsmirl@ares:/home/aosp/digipi/optee/optee_os$ grep -r hw_get_random_byte *
core/include/rng_support.h:uint8_t hw_get_random_byte(void);
core/crypto/rng_hw.c:		b[n] = hw_get_random_byte();
core/drivers/dra7_rng.c:uint8_t hw_get_random_byte(void)
core/drivers/hi16xx_rng.c:uint8_t hw_get_random_byte(void)
core/arch/arm/plat-stm/rng_support.c:uint8_t hw_get_random_byte(void)
mk/config.mk:# Otherwise, you need to implement hw_get_random_byte() for your platform

/ PRNG configuration
/ If CFG_WITH_SOFTWARE_PRNG is enabled, crypto provider provided
/ software PRNG implementation is used.
/ Otherwise, you need to implement hw_get_random_byte() for your platform
CFG_WITH_SOFTWARE_PRNG ?= y

**Comment by jbech-linaro** [comment]
> Is there an API to tell if optee is using a pseudo RNG? that way crypto security code can refuse to run. 

No.

> This is also needed for closed source implementations (like Rockchip) where you can't look and see what the code is doing.

Right, normally it's up to the SoC/OEM to decide whether to use software based RNG or leveraging some crypto IP for that. But in cases like Rockchip, it's impossible to know. One could quite easily implement a PTA function that gives a true/false whether it's software or hardware based (tied to the compile time flag `CFG_WITH_SOFTWARE_PRNG`). Another way to achieve this would be to introduce another property [2].

In general, we encourage device manufacturers to leverage hardware if possible, see [1]. 
[1] https://optee.readthedocs.io/architecture/porting_guidelines.html#hardware-crypto-ip
[2] https://optee.readthedocs.io/architecture/trusted_applications.html?ta-properties#ta-properties
