### ISSUE TITLE
Data exchange between two Trusted Applications 

### ISSUE THREAD

**Issue by Hacklog24** [OP-TEE/optee_os#3056]
Hi,

Is there a way to exchange data between two trusted applications that run in the secure world? For example, an application to exchange messages but no one outside the secure world must be able to read the messages exchanged. I read from the documentation that there is no support for TLS sockets yet. How could I do?

Thank you!

**Comment by vchong** [comment]
See '4.9 Internal Client API' section of the TEE Internal Core API Specification v1.1 under https://globalplatform.org/specs-library.

**Comment by Hacklog24** [comment]
@vchong 
Thank you! I'll take a look.

**Comment by Hacklog24** [comment]
@vchong 
Hello,
I was editing the example "hello_world" and I wanted to ask you something, what are the steps to recompile ta? Because there are no problems in recompiling the host part.

thanks a lot!

**Comment by vchong** [comment]
@Hacklog24 how are you doing your compilation right now for the host part and other components, e.g. optee_os, optee_client, etc?

**Comment by Hacklog24** [comment]
@vchong
I'm using raspbian with optee support on rpi3, as shown here https://github.com/benhaz1024/raspbian-tee
Now, I would like to make some changes to an example, how could I do?

Thank you so much.

**Comment by vchong** [comment]
@Hacklog24 I don't know how the raspbian or your build system works.
You can see the manual steps to build a TA here: https://github.com/linaro-swg/hello_world/blob/master/build_ta_helloworld_qemu.sh

If you look at the script, you can see that you need to build `optee_os` and `optee_client` first, in order to set `TA_DEV_KIT_DIR` and `TEEC_EXPORT` properly.

You can also look at https://github.com/OP-TEE/build/blob/master/rpi3.mk which builds all the components required to run an initramfs system on the rpi3. It's not raspbian though.

**Comment by Hacklog24** [comment]
@vchong
Thanks for all the tips!
Do I have to run the script on qemu and then take back the executable to Raspberry or can I do it directly from rpi3?

**Comment by jbech-linaro** [comment]
You're looking for instructions that can be found in the official documentation:
https://optee.readthedocs.io/building/gits/optee_examples/optee_examples.html#build-instructions

Deployment can be done in different ways. The most basic and cumbersome way for RPI3 devices is to physically remove the uSD-card, put it in a computer, mount it, copy the new files and do the rest in reverse. An alternative would be to just `scp` the binaries ... or use [NFS](https://optee.readthedocs.io/building/devices/rpi3.html#nfs-boot) which is my way of doing stuff when I'm working with the RPi3.

>  or can I do it directly from rpi3?

Avoid doing that, it only complicates things. You cross compilers as stated in our docs.

**Comment by Hacklog24** [comment]
@vchong  @jbech-linaro
Thank you for the help!

so I have to follow this procedure https://optee.readthedocs.io/building/gits/optee_examples/optee_examples.html#build-instructions on a linux distribution and then follow one of the steps to bring the executable onto the Raspberry?

**Comment by vchong** [comment]
You're welcome.

Yes, I think that's what @jbech-linaro meant.

**Comment by Hacklog24** [comment]
@vchong
Thanks again!!

**Comment by Hacklog24** [comment]
@vchong 
Hi,
In the "hello_world" example if I make changes to the TA part, for example multiply instead of increasing a value, once the executable is recompiled and launched, the code always does the same operation. Why?
For the host part, changes are visible.

Thanks!

**Comment by jbech-linaro** [comment]
> the code always does the same operation. Why?

You haven't updated the TA-file on the device (which is found at `/lib/optee_armtz/the-uuid-for-the-hello-world-ta.ta`).

**Comment by Hacklog24** [comment]
@jbech-linaro 
thanks for the reply, I did it but now I get

optee_example_my_ta_test: TEEC_Opensession failed with code 0xffff3024 origin 0x3

I am using your script to generate an example, modify it, compile and take back the binary and uuid.ta on the raspberry, run and get this.

**Comment by jbech-linaro** [comment]
You've probably already checked this, but if not ... `0xffff3024 = TEE_ERROR_TARGET_DEAD` and `origin = 3 (TEE_ORIGIN_TEE)` so if you grep for that in `optee_os` you will see that there aren't that many locations where that can happen. Put some debug prints around those so see what is going on or alternatively build and run your TA in QEMU, so you can [attach GDB and see what is going on](https://optee.readthedocs.io/building/devices/qemu.html#gdb-secure-world).

**Comment by Hacklog24** [comment]
@jbech-linaro 
I made other attempts but no solution. 
Do you have any advice on what it could be? I have checked many times that the .ta is under /lib/optee_armtz.

**Comment by jbech-linaro** [comment]
Zip the source code and email it to me (you'll find my email in `git log`).

**Comment by Hacklog24** [comment]
@jbech-linaro 
Done. Thank you!!

**Comment by jbech-linaro** [comment]
> @jbech-linaro
> Done. Thank you!!

I've replied to the email. Basically, your code works fine, I saw no issue at all when running it in QEMU. To be sure that your files has been correctly moved to the sd-card, you can try to check the sha1-sum. I.e.,

On the hardware
```bash
sha1sum /lib/optee_armtz/4d6bbba6-4e7c-4926-8603-c94b6a887690.ta
```

and on the PC
```bash
$ sha1sum <my_ta_test>/ta/4d6bbba6-4e7c-4926-8603-c94b6a887690.ta
```
The SHA-1 hash should be the same from both. If, not, then you've either failed to move the files, or made them out of sync.

**Comment by Hacklog24** [comment]
@jbech-linaro 
Hi,
first of all I really want to thank you for all the support. It's fantastic! For the multiplication, you're right, I returned to an initial version with no changes just to test. 

Unfortunately I checked, they are the same but I still get the same error.

**Comment by Hacklog24** [comment]
@jbech-linaro 
Hi,
just to understand where the error is. I compiled optee_os so:

make \
    CFG_TEE_BENCHMARK=n \
    CFG_TEE_CORE_LOG_LEVEL=3 \
    CROSS_COMPILE=arm-linux-gnueabihf- \
    CROSS_COMPILE_core=arm-linux-gnueabihf- \
    CROSS_COMPILE_ta_arm32=arm-linux-gnueabihf- \
    CROSS_COMPILE_ta_arm64=aarch64-linux-gnu- \
    DEBUG=1 \
    O=out/arm \
    PLATFORM=rpi3

is that right? Thank you!
