### ISSUE TITLE
remote attestation for OP-TEE

### ISSUE THREAD

**Issue by Tigerly** [OP-TEE/optee_os#3057]
Hello,

I read a paper about TEE: "Trusted Execution Environment: What It Is, and What It Is Not"
https://ieeexplore.ieee.org/abstract/document/7345265
It says the TEE "shall be able to provide remote attestation that proves its trustworthiness for third-parties". 

I'm curious about whether OP-TEE provides such remote attestation? If it does, how can we use this feature to attest its trustworthiness.

Thanks in advance!

**Comment by jbech-linaro** [comment]
> I'm curious about whether OP-TEE provides such remote attestation? If it does, how can we use this feature to attest its trustworthiness.

Not as of now unfortunately, but IIRC GlobalPlatform have worked on specifications that are supposed to address remote attestation. In the OP-TEE team we have also had a glance at OTrP which also touches attestation [here](https://tools.ietf.org/id/draft-ietf-teep-opentrustprotocol-03.html#rfc.section.12) and [here](https://tools.ietf.org/id/draft-ietf-teep-opentrustprotocol-03.html#rfc.section.14.3). Having that said, we've put that work on hold and it's uncertain if/when we will pick it up again.

We've also recently touched this from firmware TPM point of view, i.e., running a TPM implementation in the TEE, see "BKK19-215 - TPM in TEE (slides, video)" [here](https://optee.readthedocs.io/general/presentations.html).

**Comment by Tigerly** [comment]
Thanks! It's very helpful!

**Comment by bzhu5** [comment]
FYI - Remote Attestation Procedures (WIP) could be considered? 
https://datatracker.ietf.org/wg/rats/about/
