### ISSUE TITLE
OPTEE Benchmark memory allocation error

### ISSUE THREAD

**Issue by SimonLever90** [OP-TEE/optee_os#3073]
Hi,

we are currently setting up OPTEE for Xilinx ZynqMP Ultrascale. To get more detailed information about the system's performance we where planing to run the OPTEE internal Benchmarking app from the following repository:

https://github.com/linaro-swg/optee_benchmark

In the Linux kernel we enabled support for Dynamic Shared Memory and compiled the Benchmark application for the system. Now whenever we try to use Benchmark to get timing information the application crashes with the following output:

> [Benchmark] INFO: 1. Opening Benchmark Static TA...
> D/TC:1 0 core_mmu_entry_to_finer_grained:652 xlat tables used 3 / 5
> D/TC:? 0 tee_ta_init_pseudo_ta_session:276 Lookup pseudo TA 0b9a63b0-b4c6-4c85-a284-a228ef547b4e
> D/TC:? 0 tee_ta_init_pseudo_ta_session:289 Open benchmark.ta
> D/TC:? 0 tee_ta_init_pseudo_ta_session:303 benchmark.ta : 0b9a63b0-b4c6-4c85-a284-a228ef547b4e
> F/TC:? 0 plat_prng_add_jitter_entropy:73 plat_prng_add_jitter_entropy: 0xC36F
>  Benchmark] INFO: 2. Allocating per-core buffers, cores detected E/TC:=?  40
> alloc_benchmark_buffer(): trying to all allocate 3144 bytes of data
> E/TC:? 0 alloc_benchmark_buffer:76 Benchmark: can't create mobj for timestamp buffer, out of memory : 3144 
> D/TC:? 0 tee_ta_invoke_command:625 Error: ffff000c of 4
> [Benchmark] ERROR: TEEC_InvokeCommand: 0xffff000c
> 

After some debugging we found out that the error occurs during allocation of the shared memory. The Pseudo TA tries to allocate shared memory using the function `thread_rpc_alloc_global_payload`:
```
struct mobj *thread_rpc_alloc_global_payload(size_t size)
{
        return thread_rpc_alloc(size, 8, OPTEE_RPC_SHM_TYPE_GLOBAL);
}
```
The function tries to allocate shared memory of type global which is defined:
`#define OPTEE_RPC_SHM_TYPE_GLOBAL  2`

Now this call is processed in the Linux kernel TEE driver in the function `handle_rpc_func_cmd_shm_alloc` within the `rpc.c` file of the linux systems TEE driver:

```
switch (arg->params[0].u.value.a) {
case OPTEE_MSG_RPC_SHM_TYPE_APPL:                // = 0
        shm = cmd_alloc_suppl(ctx, sz);
        break;
case OPTEE_MSG_RPC_SHM_TYPE_KERNEL:             // = 1
        shm = tee_shm_alloc(ctx, sz, TEE_SHM_MAPPED);
        break;
default:                                       // <- error occurs here, no type global
        arg->ret = TEEC_ERROR_BAD_PARAMETERS;
        return;
}
```
According to the header files, Global Shared Memory is supposed to be accessible from both, Linux user space as well as Linux kernel space. Now we have been searching for a fitting version of the TEE kernel driver that implements the described feature of global shared memory, but  we haven't been able to find any implementation of the given feature.

Now here is the question: Are there missing sources for the implementation of the Global Shared Memory or are we facing another issue?

Thank you in advance

**Comment by jforissier** [comment]
Hi @SimonLever90,

First of all, thank you for the very detailed report!

The "benchmark" tool depends on a few driver patches that are not upstream. Please see https://github.com/linaro-swg/linux/commits/optee. Either you could build that branch, or you could cherry-pick the needed patches ("OP-TEE Benchmark" and "tee: support of allocating DMA shared buffers" should be enough I think).

**Comment by SimonLever90** [comment]
Hi @jforissier ,

thank you for your help, we were able get the tool running now.
Is there any reason why these patches are not part of the mainline kernel?

But now we are facing another issue. We didn't get any timestamps out of the Tee client. After setting CFG_TEE_BENCHMARK=y, which is supposed to enable the benchmarking feature in the Tee client, compilation fails with the following error: 
`libteec.so: undefined reference to `pthread_mutex_trylock'`
The function is called in the method `bm_timestamp` within the file "teec_benchmark.c".
Maybe we are still missing something in the kernel driver?

Also we are having a hard time to interpret the result of the benchmark. We are getting three events on the first core (kmodule - core - kmodule), and then there are a lot of events on the second core which only occur at the kmodule benchmark point:

```

- core: 1
  counter: 572162112
  address: 0xffffff80087ab520
  component: kmodule
- core: 1
  counter: 572162560
  address: 0x6002b98c
  component: core
- core: 1
  counter: 572162944
  address: 0xffffff80087ab540
  component: kmodule
- core: 2
  counter: 594351040
  address: 0xffffff80087ab520
  component: kmodule
- core: 2
  counter: 594367744
  address: 0xffffff80087ab540
  component: kmodule
...
```
I will also attach the file. According to your documentation the counter is counting clock cycles of the CPU, so we can calculate the runtime now. The two timestamps out of the kmodule file we found to come from the `optee_do_call_with_arg` method in "drivers/tee/optee/call.c". Now in the core we found the benchmark stamps in the `entry_invoke_command` method within "entry_std.c" file. 

There are also two timestamps available in the code but we only see a single event from the core component in the results. And why do we have so many events from the kmodule benchmark point? How can we find the actual roundtrip of the application?

Thank you for your help!

[optee_example_hello_world.txt](https://github.com/OP-TEE/optee_os/files/3275301/optee_example_hello_world.txt)

**Comment by jbech-linaro** [comment]
> Also we are having a hard time to interpret the result of the benchmark.

I believe this was on @igoropaniuk todo-list a while ago, but he moved on to another job, so this has been put on hold.

**Comment by ghost11235** [comment]
By any chance are you building this with petalinux?
I am actually going through setting up benchmarking right now with the ultra96 board. I have been able to get all xtest to pass and and examples (except storage) to work without benchmarking. After benchmarking is enabled example TA's don't compile correctly as they are trying to link pthread. (trying not to modify make files) I will be opening up a ticket and probably referencing this as i will have to deal with the same issues here once i get the TA's back to building. If you are using petalinux and have already overcome this problem, any information would be helpful. Thanks

**Comment by ArcTropics** [comment]
Hello @ghost11235,

yes exactly we are using a Petalinux 2018.3, and it seems to be the exact same issue.
Unfortunately we couldn't find a solution so far. Will get my hands to it soon and post here if we find a way.

**Comment by SimonLever90** [comment]
Hello @ghost11235,

yes exactly we are using a Petalinux 2018.3, and it seems to be the exact same issue.
Unfortunately we couldn't find a solution so far. Will get my hands to it soon and post here if we find a way.

**Comment by ghost11235** [comment]
Hello @SimonLever90 

I am still fairly new to PetaLinux and Kernel/git patching process so i am probably missing something.
I have gone through getting and applying patches however now i get compiler errors on the tee drivers. (probably missing a patch) 

generating patch:
```
git clone https://github.com/linaro-swg/linux.git
cd linux
git format-patch -1 3a18529c95f76b827c379cef33eaa3ed6e37d3c7 --stdout > ./patch/0001-OP-TEE-Benchmark.patch && \
git format-patch -1 2cb2fcabd32b4dec3d401c1d944f6d7a08f8fbc7 --stdout > ./patch/0002-OP-TEE-Benchmark-support-of-allocating-DMA-shared-buffers.patch && \
git format-patch -1 afaf7f64f74dd8a16690e1d94017f839cc7df1a9 --stdout > ./patch/0003-OP-TEE-Benchmark-support-of-allocating-DMA-shared-buffers.patch
``` 

After that i navigate to to the Xlnx source and push patches:
```
git remote add linaro_linux https://github.com/linaro-swg/linux.git
git fetch linaro_linux
git am -3 ~/repo/linux/patch/0001-OP-TEE-Benchmark.patch
git am -3 ~/repo/linux/patch/0002-OP-TEE-Benchmark-support-of-allocating-DMA-shared-buffers.patch
git am -3 ~/repo/linux/patch/0003-OP-TEE-Benchmark-support-of-allocating-DMA-shared-buffers.patch
```
once the merge conflicts are taken care of i then generate xlnx Patch:
```
git format-patch -3
```
These patch files then get moved to the ```project-spec/meta-user/recipes-kernel/linux/linux-xlnx/```
I then modify the ```linux-xlnx_%.bbappend``` to look for the patch files.

After this i get the following compiler errors/warnings(some i tried to over ride):
```
|   CC      drivers/tee/optee/rpc.o
repo/peta-op-tee3/xilinx-ultra96-reva-2018.2/build/tmp/work-shared/ultra96-zynqmp/kernel-source/drivers/tee/optee/rpc.c:316:36: warning: 'struct optee_call_ctx' declared inside parameter list will not be visible outside of this definition or declaration
|  static void free_pages_list(struct optee_call_ctx *call_ctx)
|                                     ^~~~~~~~~~~~~~
repo/peta-op-tee3/xilinx-ultra96-reva-2018.2/build/tmp/work-shared/ultra96-zynqmp/kernel-source/drivers/tee/optee/rpc.c: In function 'free_pages_list':
repo/peta-op-tee3/xilinx-ultra96-reva-2018.2/build/tmp/work-shared/ultra96-zynqmp/kernel-source/drivers/tee/optee/rpc.c:318:14: error: dereferencing pointer to incomplete type 'struct optee_call_ctx'
|   if (call_ctx->pages_list) {
|               ^~
repo/peta-op-tee3/xilinx-ultra96-reva-2018.2/build/tmp/work-shared/ultra96-zynqmp/kernel-source/drivers/tee/optee/rpc.c:319:3: error: implicit declaration of function 'optee_free_pages_list'; did you mean 'free_pages_list'? [-Werror=implicit-function-declaration]
|    optee_free_pages_list(call_ctx->pages_list,
|    ^~~~~~~~~~~~~~~~~~~~~
|    free_pages_list
repo/peta-op-tee3/xilinx-ultra96-reva-2018.2/build/tmp/work-shared/ultra96-zynqmp/kernel-source/drivers/tee/optee/rpc.c: At top level:
repo/peta-op-tee3/xilinx-ultra96-reva-2018.2/build/tmp/work-shared/ultra96-zynqmp/kernel-source/drivers/tee/optee/rpc.c:326:37: warning: 'struct optee_call_ctx' declared inside parameter list will not be visible outside of this definition or declaration
|  void optee_rpc_finalize_call(struct optee_call_ctx *call_ctx)
|                                      ^~~~~~~~~~~~~~
repo/peta-op-tee3/xilinx-ultra96-reva-2018.2/build/tmp/work-shared/ultra96-zynqmp/kernel-source/drivers/tee/optee/rpc.c: In function 'optee_rpc_finalize_call':
repo/peta-op-tee3/xilinx-ultra96-reva-2018.2/build/tmp/work-shared/ultra96-zynqmp/kernel-source/drivers/tee/optee/rpc.c:328:18: error: passing argument 1 of 'free_pages_list' from incompatible pointer type [-Werror=incompatible-pointer-types]
|   free_pages_list(call_ctx);
|                   ^~~~~~~~
repo/peta-op-tee3/xilinx-ultra96-reva-2018.2/build/tmp/work-shared/ultra96-zynqmp/kernel-source/drivers/tee/optee/rpc.c:316:13: note: expected 'struct optee_call_ctx *' but argument is of type 'struct optee_call_ctx *'
|  static void free_pages_list(struct optee_call_ctx *call_ctx)
|              ^~~~~~~~~~~~~~~
```

I then cleaned an rebuilt getting an additional error:
```
make[5]: *** No rule to make target 'drivers/tee/optee/shm_pool.o', needed by 'drivers/tee/optee/optee.o'.  Stop.
| make[5]: *** Waiting for unfinished jobs....
|   CC      drivers/tee/optee/supp.o
```


If you have any ideas or corrections please let me know.
Thanks in advance.

**Comment by SimonLever90** [comment]
Hello @ghost11235 ,

yes it looks like you are missing patches. First of all you need to apply some patches to activate dynamic shared memory as described here:

https://patchwork.ozlabs.org/patch/849155/

This enables dynamic shared memory for the kernel in general. I have extracted the neccessary patches from this repository: 

https://git.linaro.org/people/jens.wiklander/linux-tee.git

Therefor I format patches for all the commits in the history of the branch `tee-drv-dyn-shm+fixes`, beginning from tag v.15-rc3. This gives me patches for the following 19 commits:

```
2018-01-09 | tee: shm: Potential NULL dereference calling tee_shm_register()tee-drv-dynamic-shm+fixes-for-v4.16tee-drv-dyn-shm+fixes | Dan Carpenter
2017-12-28 | tee: shm: don't put_page on null shm->pages | Colin Ian King
2017-12-28 | tee: shm: make function __tee_shm_alloc static | Colin Ian King
2017-12-28 | tee: optee: check type of registered shared memory | Jens Wiklander
2017-12-28 | tee: add start argument to shm_register callback | Jens Wiklander
2017-12-15 | tee: shm: inline tee_shm_get_id()tee-drv-dynamic-shm-for-v4.16 | Volodymyr Babchuk
2017-12-15 | tee: use reference counting for tee_context | Volodymyr Babchuk
2017-12-15 | tee: optee: enable dynamic SHM support | Volodymyr Babchuk
2017-12-15 | tee: optee: add optee-specific shared pool implementation | Volodymyr Babchuk
2017-12-15 | tee: optee: store OP-TEE capabilities in private data | Volodymyr Babchuk
2017-12-15 | tee: optee: add registered buffers handling into RPC calls | Volodymyr Babchuk
2017-12-15 | tee: optee: add registered shared parameters handling | Volodymyr Babchuk
2017-12-15 | tee: optee: add shared buffer registration functions | Volodymyr Babchuk
2017-12-15 | tee: optee: add page list manipulation functions | Volodymyr Babchuk
2017-12-15 | tee: optee: Update protocol definitions | Volodymyr Babchuk
2017-12-15 | tee: shm: add page accessor functions | Volodymyr Babchuk
2017-12-15 | tee: shm: add accessors for buffer size and page offset | Volodymyr Babchuk
2017-12-15 | tee: add register user memory | Jens Wiklander
2017-12-15 | tee: flexible shared memory pool creation | Jens Wiklander
```
Apply these patches to the linux kernel and set the following config symbols to activate Shared Memory and Benchmark:

+#Activate shared memory allocations out of secure world
+TEE_SHM_REGISTER=y
+CONFIG_OPTEE_BENCHMARK=y

If everything works out you should see "Dynamic Shared Memory is enabled" at the Petalinux boot process. 

For the activation of the DMA shared buffers i used the repository mentioned by @jforissier:
https://github.com/linaro-swg/linux/commits/optee

and extracted the neccessary patches by using `git log -- drivers/tee include/linux/tee_drv.h include/uapi/linux/tee.h`

Which gives me the following 6 commits which i formatted as patches and applied to the kernel:

```
 * afaf7f64f74d tee: support of allocating DMA shared buffers **not for mainline**
 * 2cb2fcabd32b tee: support of allocating DMA shared buffers **not for mainline**
 * 89659d354639 tee: fix unbalanced context refcount in register shm from fd
 * 4647f4240814 tee: optee: optee_bench.h: remove useless include **not for mainline**
 * 3a18529c95f7 OP-TEE Benchmark **not for mainline**
 * 5ce0134162f1 tee: new ioctl to a register tee_shm from a dmabuf file descriptor
```

So, in total I applied 25 Patches to the petalinux kernel in order to get the benchmark framework running.

I hope that helps,
kind regards!

**Comment by jbech-linaro** [comment]
> For the activation of the DMA shared buffers i used the repository mentioned by @jforissier:
> https://github.com/linaro-swg/linux/commits/optee

FYI, I would guess that it should be sufficient to cherry-pick patches from this git only. This **is** the official OP-TEE Linux kernel fork where we keep all patches, both the ones that can be found upstream (kernel.org) and patches that are in the works.

**Comment by ghost11235** [comment]
@SimonLever90 Thank you for the detailed information.
I was also missing TEE_SHM_REGISTER=y 

Below is the patches including the consolidated merges of ```tee-drv-dyn-shm``` and ```tee-drv-dyn-shm+fixes``` from https://github.com/linaro-swg/linux/commits/optee :
```
git format-patch -1 afaf7f64f74dd8a16690e1d94017f839cc7df1a9 --stdout  > ./patch/0008-Benchmark.patch && \
git format-patch -1 2cb2fcabd32b4dec3d401c1d944f6d7a08f8fbc7 --stdout  > ./patch/0007-Benchmark.patch && \
git format-patch -1 89659d3546399628780b8707e0d1feebcd5c014a --stdout  > ./patch/0006-Benchmark.patch && \
git format-patch -1 4647f424081481b9e43d7162530c6fb30faa5282 --stdout  > ./patch/0005-Benchmark.patch && \
git format-patch -1 3a18529c95f76b827c379cef33eaa3ed6e37d3c7 --stdout  > ./patch/0004-Benchmark.patch && \
git format-patch -1 5ce0134162f14ee7b75d9b9e55de95a42ab0a93f --stdout  > ./patch/0003-Benchmark.patch && \
git format-patch -1 ffdc98c4f25b1f4fb96cd9190917b53a760f3fec --stdout  > ./patch/0002-Benchmark.patch && \
git format-patch -1 bad19e0d0460564a067f901b6848c0cc0c403c52 --stdout  > ./patch/0001-Benchmark.patch
```
Currently my build is compiling and i will post back here once it is tested.

**Comment by ghost11235** [comment]
Hello  @jbech-linaro , 
I have not made any real progress on the ultra96 board enabling the benchmark framework, i am still having the issue documented above. 
I now have switched gears to using a RPI 3B and am having the following issue:

```
# benchmark optee_example_asign 256 hello
[Benchmark] INFO: 1. Opening Benchmark Static TA
D/TC:? 0 tee_ta_init_pseudo_ta_session:280 Lookup pseudo TA 0b9a63b0-b4c6-4c85-a284-a228ef547b4e
D/TC:? 0 tee_ta_init_pseudo_ta_session:293 Open benchmark.ta
D/TC:? 0 tee_ta_init_pseudo_ta_session:307 benchmark.ta : 0b9a63b0-b4c6-4c85-a284-a228ef547b4e
D/TC:? 0 tee_ta_init_session_with_context:477 Re-open TA 0b9a63b0-b4c6-4c85-a284-a228ef547b4e
D/TC:? 0 get_benchmark_memref:120 Benchmark: Sending back timestamp buffer paddr = 0x0
...
[Benchmark]  INFO: 2. Allocating per-core buffers, cores detected = 4
D/TC:? 0 tee_ta_close_session:398 csess 0x1015fa10 id 2
D/TC:? 0 tee_ta_close_session:417 Destroy session
D/TC:? 0 alloc_benchmark_buffer:92 Benchmark: allocated timestamp buffer, addr = 0x10801000
D/TC:? 0 tee_ta_init_session_with_context:477 Re-open TA 0b9a63b0-b4c6-4c85-a284-a228ef547b4e
D/TC:? 0 get_benchmark_memref:120 Benchmark: Sending back timestamp buffer paddr = 0x8001000
D/TC:? 0 tee_ta_close_session:398 csess 0x1015f950 id 2
D/TC:? 0 tee_ta_close_session:417 Destroy session
[Benchmark] INFO: ts buffer paddr = 134221824, size = 3144
[Benchmark] ERROR: Failed to get realpath: 0x00000001
```

The asign CA/TA is a modified acipher to use ECDSA i get the same error on acipher and hello world.
If i attempt to rerun the benchmark i get the following:

```
 benchmark optee_example_hello_world
[Benchmark] INFO: 1. Opening Benchmark Static TA
D/TC:? 0 tee_ta_init_session_with_context:477 Re-open TA 0b9a63b0-b4c6-4c85-a284-a228ef547b4e
D/TC:? 0 tee_ta_init_session_with_context:477 Re-open TA 0b9a63b0-b4c6-4c85-a284-a228ef547b4e
D/TC:? 0 get_benchmark_memref:120 Benchmark: Sending back timestamp buffer paddr = 0x8001000
D/TC:? 0 tee_ta_close_session:398 csess 0x10161870 id 3
D/TC:? 0 tee_ta_close_session:417 Destroy session
...
[Benchmark] INFO: 2. Allocating per-core buffers, cores detected = 4
E/TC:? 0 alloc_benchmark_buffer:56 Benchmark: timestamp buffer was already registered
D/TC:? 0 tee_ta_invoke_command:673 Error: ffff0007 of 4
D/TC:? 0 tee_ta_close_session:398 csess 0x10161950 id 2
D/TC:? 0 tee_ta_close_session:417 Destroy session
[Benchmark] ERROR: TEEC_InvokeCommand: 0xffff0007
``` 

Thanks

**Comment by ghost11235** [comment]
I also get the same error in the default qemu environment.
```
# optee_example_hello_world
Invoking TA to increment 42
TA incremented value to 43
# benchmark optee_example_hello_world
[Benchmark] INFO: 1. Opening Benchmark Static TA...
[Benchmark] INFO: 2. Allocating per-core buffers, cores detected = 2
[Benchmark] INFO: ts buffer paddr = 2145386496, size = 1576

[Benchmark] ERROR: Failed to get realpath: 0x00000001

# benchmark optee_example_hello_world
[Benchmark] INFO: 1. Opening Benchmark Static TA...
[Benchmark] INFO: 2. Allocating per-core buffers, cores detected = 2
[Benchmark] ERROR: TEEC_InvokeCommand: 0xffff0007
```

**Comment by jbech-linaro** [comment]
@ghost11235 , you might have found an issue/bug. It's been quite a while since we had anyone looking into the benchmark framework. So the likelihood that there is a need for an update is probably pretty high. I'll try to put this on the to-do list for things to look into in the future. Unfortunately this will probably take some time, since everyone in the team are already working on other things.
