### ISSUE TITLE
Issue in TEEC_opensession after optee migration

### ISSUE THREAD

**Issue by Sourabhharman** [OP-TEE/optee_os#3077]
Hi all,
Currently we have done some migration from OPTEE v3.0.0 to v3.3.0.
On calling the TEEC_Opensession(), we were getting the error like:
E/TC:? 0 tee_ta_open_session:586 Failed. Return error 0x40004d40
F/TC:? 0 plat_prng_add_jitter_entropy:74 plat_prng_add_jitter_entropy: 0x35
hello_world: TEEC_Opensession failed with code 0x40004d40 origin 0x4

The error code was different from the GP error.
On debugging the issue we found that the error is return from __thread_enter_user_mode().
On further debugging we found that the execution flow wasn't reaching the __utee_entry() function of TA. So we looked on the history of the commits in OPTEE.
We found [this commit changes](https://github.com/OP-TEE/optee_os/commit/e13d1040f35ce8388807c9381fe04584d131eb3d#diff-e6156ff4c0b1f724cf0abea9c0bc2383).

We revert the changes in line 527 to the old one, and build and executed our OPTEE. So, this time it worked.

>  -store_xregs sp, THREAD_CORE_LOCAL_X0, 0, 3
>  -isb			mov_imm	x0, SMCCC_ARCH_WORKAROUND_1
>  -smc	#0
>  -load_xregs sp, THREAD_CORE_LOCAL_X0, 0, 3
>
>  +ic	iallu	
>  +isb
> 

As the commit description give some idea about the changes is for arch64 CVE workaround.
Can anyone give some more detail about the changes and what purpose the smc calls are serving in the workaround? What could be the possible reason of the error code 0x40004d40 returned due to TA failure? If we revert the changes as above, is there any major security risk or vulnerability?

**Comment by jenswi-linaro** [comment]
Perhaps ARM Trusted Firmware needs to be updated too?
