### ISSUE TITLE
optee os hang on imx6 solo

### ISSUE THREAD

**Issue by vasujois** [OP-TEE/optee_os#3088]
Hi,

I am trying to boot optee os on my platform (imx6 solo). I have followed the below procedure:

1. I have change the uboot like this : gd->ram_size = imx_ddr_size() - CONFIG_TEE_RAM_SIZE;
2. added TEE_RAM_SIZE=0x2000000 in CONFIG_SYS_EXTRA_OPTIONS in uboot
3. took optee os from latest master and built uTee like this: 
  
> make PLATFORM=imx PLATFORM_FLAVOR=mx6shmbedge CFG_TEE_CORE_LOG_LEVEL=3 CFG_BOOT_SYNC_CPU=n CFG_NS_ENTRY_ADDR=0x12000000 CFG_DT_ADDR=0x18000000 CFG_DT=y
> mkimage -A arm -O linux -C none -a 0x8dffffe4 -e 0x8e000000 -d out/arm-plat-imx/core/tee.bin uTee

4. I got uTee (size is about 264.4 KB).
5. I have kept zImage, dtb and uTee on emmc of my board.
6. I am trying to load like this below:
> ext4load mmc 0:1 0x12000000 zImage
> ext4load mmc 0:1 0x18000000 sme-d5-bsht.dtb
> ext4load mmc 0:1 0x20000000 uTee
> bootm 0x20000000 - 0x18000000

But, it is hanging  like this:

=> bootm 0x20000000 - 0x18000000
   Booting kernel from Legacy Image at 20000000 ...
   Image Name:
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    270780 Bytes = 264.4 KiB
   Load Address: 8dffffe4
   Entry Point:  8e000000
   Verifying Checksum ... OK
   Flattened Device Tree blob at 18000000
   Booting using the fdt blob at 0x18000000
   Loading Kernel Image ... OK
   Using Device Tree in place at 18000000, end 1800e606

Starting kernel ...

Can you please help regarding this issue..?

Thanks and Regards
VJ

**Comment by PratikGajera** [comment]
@vasujois, Have you configured tzasc driver for executing secure OS on DRAM?

**Comment by vasujois** [comment]
@PratikGajera : Can you please tell me how can i do that..?

**Comment by vasujois** [comment]
The issue is resolved.
