### ISSUE TITLE
is it possible to have vendor specific std calls

### ISSUE THREAD

**Issue by sandeepbrcm** [OP-TEE/optee_os#3089]
I want to have a SOC specific secure service that can be called from linux driver and the said service apparently might take long enough to cause scheduling blackout to linux if handled as EL3 runtime service Or as OP-TEE fast_smc.
Options are to use SPM (overkill for the purpose as of now). 
Or extend std_smc as follows.

```
void __weak  plat_std_smc_handler(struct thread_smc_args *smc_args)
{
    if  smc_args->arg0  is vendor specific then
         **thread_set_foreign_intr(true);**   /* allow linux interrupts  */  
           plat_handle_smc
    else
       tee_entry_std(smc_args);
}
```
I have not given it a try, just want to get a feedback if there are other implications I am missing.

**Comment by jenswi-linaro** [comment]
Yes, it's possible. I'd recommend taking a look at pseudo TAs first though.

**Comment by etienne-lms** [comment]
Platform defines the std_smc entry in their `main.c`, like below, they all register generic `tee_entry_std()`.
```C
static const struct thread_handlers handlers = {
	.std_smc = tee_entry_std,
	.fast_smc = tee_entry_fast,
	(...)
```
Platform can define a local handler that calls `tee_entry_std()` for generic standard SMCs. This is an easy way to catch non-fastcall platform specific SMCs.

That said, consider Jens recommendation. Using a PTA invoked by your Linux kernel driver through the OP-TEE kernel TEE API will help you define a clean interface for your service, based on TEE sessions/commands/params.

**Comment by sandeepbrcm** [comment]
Thanks, looks like eventually will go with PTA based approach. For now exploring all possible options.

A slightly unrelated query.
Just wondering, the services provided by PTA are also available to user space (linux client app EL0).
Is there a way I can enforce some restrictions.
 eg:  service from a PTA I want to invoke only from Secure EL0  dynamic TA and 
 normal world should not be able to invoke those. 

user app request service - ->TEE load dynamic TA (may be from encrypted storage) -
--> TA invokes commands from PTA
But user app should not be able to invoke services from the PTA.

**Comment by jenswi-linaro** [comment]
Yes, that should be possible to check with the new login type introduced by @b49020  in https://lists.linaro.org/pipermail/tee-dev/2019-June/001007.html (see also https://github.com/OP-TEE/optee_os/pull/3082)
This of course work in progress, but I guess we'll add something like that in the end.

**Comment by etienne-lms** [comment]
Note a PTA can check if it has been invoked from a TA (trusted app) or a CA (linux app). See for example https://github.com/OP-TEE/optee_os/blob/3.5.0/core/arch/arm/pta/system.c#L49.
A PTA could also access the UUID of the TA that invokes it and allow only target TA UUIDs.

**Comment by sandeepbrcm** [comment]
Thanks a lot for the explanations, I got a fair idea of the available constructs.
