### ISSUE TITLE
Integrity check & encryption of early TA

### ISSUE THREAD

**Issue by piachristel** [OP-TEE/optee_os#3095]
### TA types
a.  In section _2.10.3 of optee-doc_, there are 3 types of TA described. Early TA are not enabled by default. **So I assume the REE filesystem TA and not the Secure Storage TA are the default TA?** 

### Integrity check of early TA's
b. According to _2.7.8 in optee-doc_ each TA is signed by a private key. 
The tee-supplicant then verifies this signature when loading any TA of type _REE filesystem TA_ (_2.10.3 in optee-doc_).
**If a TA of type _early TA_ is used, does the integrity check happen at boot time via secure boot? Or is no integrity check enabled in this case?**

### Encryption of early TA's
c. **TA of type _early TA_ do never leave the secure world and therefore there is no need to encrypt them, right?**

Thanks for clarification :).

**Comment by etienne-lms** [comment]
> **TA types**

OP-TEE core looks for a target TA in this ordering:
* First look into early TA sections. Bypassed in `CFG_EARLY_TA` is disable.
Image of such TAs is located in a read-only data sections of the OP-TEE core firmware image.
These are built-in OP-TEE core.
* Then look into secure storage. Bypassed in `CFG_SECSTOR_TA` is disable.
Image of such TAs is located in the OP-TEE secure storage. One must have previously provision these TAs. OP-TEE can do this provisioning, thanks to bootstrap TA, based on TAs stored in REE filesystem.
* Last look into REE filesystem. Bypassed in `CFG_REE_FS_TA` is disable.

> **Integrity check of early TA's**

Early TAs are not specifically integrity checked when loaded. They are part of the OP-TEE core firmware, hence when boot checks (possibly decrypts) OP-TEE core image, the process cover the whole OP-TEE core image, including early TAs.

> **Encryption of early TA's**

Early TAs are not specifically encrypted. They are simply part of OP-TEE core image which may or may not be encrypted, depending on the platform.

**Comment by piachristel** [comment]
Thanks for the explanation @etienne-lms .
