### ISSUE TITLE
Check on the wrong object?

### ISSUE THREAD

**Issue by sticfeynman** [OP-TEE/optee_os#3096]
Hi,
There are comments in several places in syscall_cryp_derive_key(),i.e.
```
/* Requested size must fit into the output object's buffer */
```
but the following statements seem check on the input object's buffer.
IMO, it should go like
if (okm_len > ~~ik~~ sk->alloc_size) {

Do I miss anything?

**Comment by jenswi-linaro** [comment]
It does look a bit weird. @jforissier?

**Comment by jforissier** [comment]
I agree it does not look right. At first glance the suggested change looks OK, but I'd like to have a test case to make sure the check is correct and useful. We have xtest 8001 for extended key derivation, which could serve as a basis.

**Comment by jbech-linaro** [comment]
@jforissier , @sticfeynman , worth continue working with this? Sounds like it is.

**Comment by jforissier** [comment]
@jbech-linaro I think so.
