### ISSUE TITLE
Access Denied when trying to open a PTA

### ISSUE THREAD

**Issue by lmarti95** [OP-TEE/optee_os#3098]
Hello,

I have a TA and a pseudo TA and when I try to open a TASession to access the pseudo TA from the TA i get a result back which is: TEE_ERROR_ACCESS_DENIED. Can you help me what could cause this error?
Here is my code:

	TEE_Result res;

	TEE_UUID uuid = PTA_UUID;

	uint32_t cancellationRequestTimeout = TEE_TIMEOUT_INFINITE;

	TEE_TASessionHandle sess;

	uint32_t returnOrigin = TEE_ORIGIN_TRUSTED_APP;

	res = TEE_OpenTASession(&uuid, cancellationRequestTimeout, 
		param_types, params, &sess, &returnOrigin);

**Comment by lmarti95** [comment]
I put this line : `srcs-y += pta.c` into the wrong if and that caused the problem.

**Comment by lmarti95** [comment]
Also I changed this line in the program:
`res = TEE_OpenTASession(&uuid, cancellationRequestTimeout, 
		0, NULL, &sess, &returnOrigin);`

**Comment by lmarti95** [comment]
Actually I think the issue was with the params[1].memref.size, as that was set to 0x1000

**Comment by PratikGajera** [comment]
@lmarti95, Have you solved this issue?

**Comment by lmarti95** [comment]
Yes, the params[1].memref.size was too large.
