### ISSUE TITLE
The implementation about the property access function

### ISSUE THREAD

**Issue by sticfeynman** [OP-TEE/optee_os#3108]
Hi,
The TEE_GetPropertyAsString() and TEE_GetPropertyAsBinaryBlock() are not allowed the null-valued valueBuffer. There seems not an elegant way to apply the paradigm, i.e. 
1. query the size of the property value
2. get the property value with the exact-sized buffer

Is it possible to change the implementation that accepts the null-valued valueBuffer and reports the least necessary buffer size in the valueBufferlen argument?

**Comment by etienne-lms** [comment]
I think you're right. Nothing in the GPD TEE specification seems to prevent the change you propose. Could you propose a P-R for that?

**Comment by jbech-linaro** [comment]
@sticfeynman , I'll remove the "stale" label, since I believe this is something worth continue working with. Do you have time to create a patch for it?
