### ISSUE TITLE
Adjust TA Memory Size

### ISSUE THREAD

**Issue by PeterVanNostrand** [OP-TEE/optee_os#3109]
Hello all, I am attempting to run a Trusted Application which needs a significant amount of memory. Currently, I have the following statements defined in `user_ta_header_defines.h`
```c
#define TA_STACK_SIZE  (1 * 1024 * 1024)
#define TA_DATA_SIZE   (10 * 1024 * 1024)
```
However, when I try to run the Trusted Applicaiton I experience this error message
>tee_ta_open_session:588 init session failed 0xffff000c

This seems to indicate that OP-TEE could not allocate enough memory for the TA. Judging from the documentation, this seems to be because I need to "[adjust TA’s MMU L1 table](https://optee.readthedocs.io/faq/faq.html#q-whats-the-maximum-size-for-heap-and-stack-can-it-be-changed)"

How would I go about doing this? I attempted to increase the `PGT_CACHE_SIZE` in `pgt_cache.h` as described in [this](https://github.com/OP-TEE/optee_os/issues/2090) issue by changing `CFG_NUM_THREADS * 2` to `CFG_NUM_THREADS * 8` to allow for overhead ([pgt_cache.h:42](https://github.com/ForgeRock/optee-os/blob/c0b2e931b395f098aa53912afa8b4f37cb339e1b/core/arch/arm/include/mm/pgt_cache.h#L42)). I also tried settting `#define PGT_CACHE_SIZE	32` as described in [this](https://github.com/OP-TEE/optee_os/issues/2178) issue, but ran into the same error with both. Any pointers on what changes I need to make to OP-TEE to allow for such a large memory allocation?

Thanks for your help

**Comment by etienne-lms** [comment]
Hi @PeterVanNostrand,
I gave this a try and I think increase `PGT_CACHE_SIZE` value should fix your issue. I managed to load the hello_world TA from optee_examples with 10MB heap and 1MB stack.
Looks like `PGT_CACHE_SIZE` should not depend only on number of thread. Maybe platforms should be able to define `PGT_CACHE_SIZE` value (I.e. `CFG_PGT_CACHE_MIN`).

**Comment by PeterVanNostrand** [comment]
@etienne-lms Thanks for the reply. It's interesting you got that working, I tried editing the `PGT_CACHE_SIZE` size as I described in my original comment and I'm trying this now
```c
# define PGT_CACHE_SIZE 64
```
What value did you use for this define? Also what units are this in, B/KB/number of pagetables?

**Comment by etienne-lms** [comment]
`PGT_CACHE_SIZE` value is a number of MMU page tables, not a memory area size.
- armv8-a/LPAE platforms need 1 MMU table per 2MByte of mapped memory.
- 32bit MMU platforms need 1 MMU table per 1MByte of mapped memory.

`PGT_CACHE_SIZE` should state how many MMU tables can be used to execute TAs concurrently.

Default value (in `pgt_cache.h`) expects at least 2 MMU tables per thread which allows up to 4 MByte (LPAE) or 2MB (32bit MMU) of virtual memory per TA that executes concurrently.

If a single TA expects a wider virtual memory range of N MBytes, `PGT_CACHE_SIZE` shall be at least:
* `(CFG_NUM_THREADS - 1) * 2 + N/2` for 64bit MMU (LPAE)
* `(CFG_NUM_THREADS - 1) * 2 + N` for 32bit MMU

If several TAs can execute concurrently and each expect several Mbytes of virtual memory, then `PGT_CACHE_SIZE` should be big enough to cover the concurrent mapping of TAs. Note `CFG_NUM_THREADS` gives the number of TAs that can be invoked concurrently.

Considering your platform (RPi3): `CFG_WITH_PAGER` is disabled, `CFG_TEE_RAM_VA_SIZE=7MB`.
These MMU tables are statically allocated, see `pgt_init()`. I would not expect build issues with big value as far as OP-TEE virtual memory range is large enough. If it is not, you may need to increase `CFG_TEE_RAM_VA_SIZE`.

**Comment by PeterVanNostrand** [comment]
Thanks for the help. So assuming I'm running an armv8a configuration with `CFG_NUM_THREADS = 4`, then if I wanted to allocate 11MB stack+heap to my TA I would set `PGT_CACHE_SIZE` to `(4 - 1) * 2 + 11/2 = 12`. Let's say 14 for overhead. Since this is larger than `CFG_TEE_RAM_VA_SIZE`, I replaced `CFG_TEE_RAM_VA_SIZE = 0x00700000` with `CFG_TEE_RAM_VA_SIZE = 0x02000000`, this should make the virtual address size 32MB. Except now I'm getting an error
```bash
Panic 'TEE_RAM can't fit in secure_only' at core/arch/arm/mm/core_mmu.c:1022 <core_init_mmu_map>
```
Does this mean that the TEE is now trying to request more secure memory than my device supports? Any advice you could provide would be much appreciated.

**Comment by PeterVanNostrand** [comment]
After some experimentation, it seems like the maximum amount of ram that the TA can request is 7 MB before I encounter this error: 
>tee_ta_open_session:588 init session failed 0xffff000c

As you suggested I then increased the `CFG_TEE_RAM_VA_SIZE` from `0x00700000` to `0x00A00000` in [rpi3-conf.mk](https://github.com/OP-TEE/optee_os/blob/d2c717b23e63e07a3c05dbbdd6af62117480920d/core/arch/arm/plat-rpi3/conf.mk#L9). I also set `CFG_NUM_THREADS = 1` and `PGT_CACHE_SIZE = 5` so that the single TA should be able to span all 10MB. Despite this I have still not been able to exceed 7MB successfully. Are there any other configuration settings related to the RAM size that would be forcing this cap? Thanks again.

**Comment by jenswi-linaro** [comment]
I guess you need to get your hands dirty and debug it. If you try to test it with OP-TEE in QEMU instead it should be fairly easy to find out where it goes wrong with GDB.

**Comment by etienne-lms** [comment]
@PeterVanNostrand,  I've tested back on 3.6.0 tag with platform `qemu_virt`. 
qemu currently has 13MByte of secure TA_RAM. Based on this, i changed optee_examples hello_world TA to use 9MByte of heap (`TA_DATA_SIZE`) and 2MByte of stack (`TA_STACK_SIZE`).

Considering standard test TAs and this TA >11MByte, I forced `PGT_CACHE_SIZE` value and checked the TA was successfully loaded.  and LPAE (64bit) MMU.
* with 32bit MMU (`CFG_WITH_LPAE=n`, default for qemu_virt, 1 MMU table per 1MB):
  `#define PGT_CACHE_SIZE    12` is ok to get TA loaded.
* with 64bit MMU (`CFG_WITH_LPAE=y`, 1 table per 2MB):
  `#define PGT_CACHE_SIZE    6` is ok to get TA loaded.
