### ISSUE TITLE
How can I rebuild specific optee (ex. 2.6.0) released in the past?

### ISSUE THREAD

**Issue by aim2nasa** [OP-TEE/optee_os#3120]
Mostly I've been working under optee 2.6 and recently upgraded to 3.5 successfully.

To specify 3.5, I used the following repo command like,
`repo init -u https://github.com/OP-TEE/manifest.git -m rpi3.xml -b 3.5.0`

It seemed quite alright but when I try to recreate optee(2.6.0) binary with `-b 2.6.0` option,
I faced build error which I couldn't experience before.

IMO, several changes after the 2.6 could possibly affect the build, 
so the above mentioned method is not good enough for my purpose, I assume.

How can I exactly rebuild the previously released optee suite such as release 2.6.0 (on 27 Oct 2017)?

**Comment by jbech-linaro** [comment]
Hi, you do like this: https://optee.readthedocs.io/building/gits/build.html#stable-releases-prior-to-op-tee-v3-1-v1-0-0-to-v3-0-0

**Comment by aim2nasa** [comment]
This is exactly what I've been missing.
Clear explanations.
Great!

**Comment by aim2nasa** [comment]
> Hi, you do like this for old releases (prior to 3.1):
> https://optee.readthedocs.io/building/gits/build.html#stable-releases-prior-to-op-tee-v3-1-v1-0-0-to-v3-0-0
> 
> And after 3.1 to current:
> https://optee.readthedocs.io/building/gits/build.html#stable-releases

This is exactly what I've been missing.
Clear explanations.
Great! Thank you
