### ISSUE TITLE
Optee TA or SW side log how to see?

### ISSUE THREAD

**Issue by aminul112** [OP-TEE/optee_os#3121]
Hello all,

This is my first post regarding OPTEE. 

I am using a chipset with Optee OS version 3.0. When I run test application it executes fine.
 
Here is the client side log
#optee_example_hello_world
Invoking TA to increment 42
TA incremented value to 43

Regarding TA side log, I tried with #dmesg command, but I can not see anything.
Can someone tell me how I can see TA or SW side log?

I the Makefile of hello_world TA, I can see below lines

CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)

**Comment by jbech-linaro** [comment]
Right, just as you see the non-secure debug prints in the UART when running the command, you will also see the secure side debug prints when the flags you're referring to has the correct level (4 is most verbose, 1 is least verbose). Ensure that this flag has been set when build and you'll see the secure side debug prints.

**Comment by aminul112** [comment]
hi @jbech-linaro jbech-linaro

I have checked the flag is 4. 

When I run #optee_example_hello_world  SW log and NW log will come at the same time? I can see only NW log.

Will SW log come with 'dmesg' comamnd?

**Comment by jbech-linaro** [comment]
> hi @jbech-linaro jbech-linaro
> 
> I have checked the flag is 4.
> 

Great!

> When I run #optee_example_hello_world SW log and NW log will come at the same time? I can see only NW log.
>

Some platforms use different UARTs, one for NW and one for SW. Some share the UART. For the latter prints will be intermingled. As an example, I spend most of my OP-TEE development time using QEMU and there we have separate UARTs for the prints. I.e., I have two consoles, one with non-secure prints and one with secure prints. Here is an example from a host/TA application I'm working with right now:

**Non secure UART**
```bash
# oemcrypto_v15 
[OEC] OEMCrypto initialized
[OEC] Creating/adding session: 0x00000001
[OEC] Init session ptr: 0x283e0
TEEC_InvokeCommand (OPTEE_WV_CREATEUSAGETABLEHEADER) failed with code 0xffff0003 origin 0x4
[OEC] Close session: 0x00000001
[OEC] OEMCrypto terminated
```
**Secure UART**
```bash
...
D/TA:  TA_CreateEntryPoint:14 has been called
D/TA:  TA_OpenSessionEntryPoint:34 has been called (no impl.)
D/TA:  ta_wv_oec_create_usage_table_header:106 Creating Usage Table Header
D/TA:  oec_create_usage_table_header:239 Usage Table Header not yet created
...
I/TA: invoked command 61, return 0xffff0003
...
D/TA:  TA_CloseSessionEntryPoint:40 has been called (no impl.)
D/TA:  TA_DestroyEntryPoint:25 has been called
...
D/TC:? 0 tee_ta_close_session:515 Destroy session
```

 
> Will SW log come with 'dmesg' comamnd?

No, it's not on the dmesg, just regular UART output.

**Comment by aminul112** [comment]
@jbech-linaro 
I have found this CFG_TEE_CORE_LOG_LEVEL  value are '1' in below 2 files.
...../optee-examples/1.0-r0/recipe-sysroot/usr/include/optee/export-user_ta_arm32/host_include/conf.h
...../optee-examples/1.0-r0/recipe-sysroot/usr/include/optee/export-user_ta_arm32/host_include/conf.mk

are these 2 values are important to show TA log?

Do I need to change the value of CFG_TEE_CORE_LOG_LEVEL to 4 and build something?

**Comment by aminul112** [comment]
if CFG_TEE_TA_LOG_LEVEL value is 4 during compilation of Optee OS, then I can see TA or Secure side log.
