### ISSUE TITLE
Possible bug in core_mmu_add_mapping

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#3124]
Currently TCR_EL1 register is only set in init stage, suppose in init stage all physical memory registered is in 0-4G, the IPS bits (bit34~32) is set 0. Later if a physical address 0x100000000 is dynamically mapping with core_mmu_add_mapping, as 0x100000000 is higher than 4G, the IPS bits of TCR_EL1 register should be updated to 0x1. Otherwise the below panic occurs:
    
    E/TC:00 check_pa_matches_va:1805 va 0x82a00000 maps 0x100000000, expect 0x0
    
I Fixed the issue above after adding change below:

```
diff --git a/core/arch/arm/mm/core_mmu.c b/core/arch/arm/mm/core_mmu.c
index 1eeedcd..16211d1 100644
--- a/core/arch/arm/mm/core_mmu.c
+++ b/core/arch/arm/mm/core_mmu.c
@@ -1631,6 +1631,9 @@ bool core_mmu_add_mapping(enum teecore_memtypes type, paddr_t addr, size_t len)
        /* Make sure the new entry is visible before continuing. */
        dsb_ishst();
 
  +   /* Update tcr register with maximum physical address change. */
  +   core_mmu_set_max_pa(map->pa + map->size);
  +
        return true;
 }
```

What do you guys think? If you agree with me, I'll submit this patch later. Thanks in advance!

**Comment by tiger20081015** [comment]
Guys, any feedback?

**Comment by jbech-linaro** [comment]
Sounds reasonable to me (btw it's summer time and many people in the core team is on vacation, so expect delayed answers to both questions as well as feedback in pull requests).

**Comment by jenswi-linaro** [comment]
Good catch. However, I'd prefer calling `core_mmu_set_max_pa()` before `set_region()` to make sure `TCR_EL1` is updated before a larger physical address might be used. MMU is enabled so speculation can occur.

**Comment by tiger20081015** [comment]
@jenswi-linaro ,yes, it's more reasonable. I'll submit a patch to fix this bug.

**Comment by tiger20081015** [comment]
@jbech-linaro , patch submitted, pls help to review. thx!
https://github.com/OP-TEE/optee_os/pull/3146

**Comment by jbech-linaro** [comment]
I'm closing the ticket, since your patch in #3146 fixes this, thanks for the contribution @tiger20081015 !
