### ISSUE TITLE
No module named 'elftools' 

### ISSUE THREAD

**Issue by vivinamartins16** [OP-TEE/optee_os#3126]
Hey all!

So, I was building the latest (3.6.0) OP-TEE image for Qemu (v8) on Ubuntu 18.04 and got the following error message:

`Traceback (most recent call last):
  File "scripts/gen_ldelf_hex.py", line 12, in <module>
    from elftools.elf.elffile import ELFFile
ModuleNotFoundError: No module named 'elftools'
mk/subdir.mk:158: recipe for target 'out/arm/core/ldelf_hex.c' failed
make[1]: *** [out/arm/core/ldelf_hex.c] Error 1
`

I did a quick search in recent commits and found out the gen_ldelf_hex.py file was updated recently for python3.
I have python3 in my host machine and also the elftools. 
What am I missing to sucessfully build the latest version of OP-TEE?

- clean image coming directly from repo
- no addition of packages in the common.mk file
- followed the step-by-step provided in [here](https://optee.readthedocs.io/building/gits/build.html#get-and-build-the-solution)

Thanks for any help!

**Comment by Emantor** [comment]
Hi, you need to install `python3-pyelftools` using:
```
sudo apt-get install python3-pyelftools
```

**Comment by vivinamartins16** [comment]
Thanks! That worked just fine ;)
