### ISSUE TITLE
when building /home/OP-TEE/out-br, fail to connect www.samba.org

### ISSUE THREAD

**Issue by penpendandan** [OP-TEE/optee_os#3127]
Hi Team,
when building OP-TEE environment, I am getting a error:  "[/home/OP-TEE/out-br/build/host-ccache-3.6/.stamp_downloaded] Error 1" 
the logs are as follows
```
>>> host-ccache 3.6 Downloading
--2019-07-14 12:18:19--  https://www.samba.org/ftp/ccache/ccache-3.6.tar.xz
Resolving www.samba.org (www.samba.org)... 144.76.82.148, 2a01:4f8:192:486::2:3
Connecting to www.samba.org (www.samba.org)|144.76.82.148|:443... failed: Connection timed out.
Connecting to www.samba.org (www.samba.org)|2a01:4f8:192:486::2:3|:443... failed: Network is unreachable.
--2019-07-14 12:20:27--  http://sources.buildroot.net/ccache/ccache-3.6.tar.xz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.25.211.19, 104.25.210.19, 2606:4700:20::6819:d313, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.211.19|:80... failed: Connection timed out.
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.210.19|:80... failed: Connection timed out.
Connecting to sources.buildroot.net (sources.buildroot.net)|2606:4700:20::6819:d313|:80... failed: Network is unreachable.
Connecting to sources.buildroot.net (sources.buildroot.net)|2606:4700:20::6819:d213|:80... failed: Network is unreachable.
--2019-07-14 12:24:43--  http://sources.buildroot.net/ccache-3.6.tar.xz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.25.211.19, 104.25.210.19, 2606:4700:20::6819:d213, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.211.19|:80... failed: Connection timed out.
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.210.19|:80... failed: Connection timed out.
Connecting to sources.buildroot.net (sources.buildroot.net)|2606:4700:20::6819:d213|:80... failed: Network is unreachable.
Connecting to sources.buildroot.net (sources.buildroot.net)|2606:4700:20::6819:d313|:80... failed: Network is unreachable.
make[2]: *** [/home/OP-TEE/out-br/build/host-ccache-3.6/.stamp_downloaded] Error 1
make[1]: *** [_all] Error 2
make[1]: Leaving directory `/home/OP-TEE/out-br'
make: *** [buildroot] Error 2
```
I have downloaded and intalled  "ccache-3.6.tar.xz" manually. But it does not work.  I want to know where this shell scripe of downloading ccache-3.6.tar.xz and how I can skip it. Thanks!

**Comment by vchong** [comment]
I think you've downloaded and installed it for your local PC while the OP-TEE build is actually building it for the board. The samba server could be ok by now, but if not, try commenting out the `BR_CCACHE=y` line in `build/br-ext/configs/optee_generic`.

**NOTE**: It's summer time and many people in the core team is on vacation, so expect delayed answers to both questions as well as feedback in pull requests!

**Comment by penpendandan** [comment]
vchong, thanks for your reply. However, there is another problem: fail to connect  download.savannah.gnu.org, the log is as follows:
`
>> host-attr 2.4.48 Downloading
--2019-07-15 08:22:15--  http://download.savannah.gnu.org/releases/attr/attr-2.4.48.tar.gz
Resolving download.savannah.gnu.org (download.savannah.gnu.org)... 209.51.188.200, 2001:470:142:5::200
Connecting to download.savannah.gnu.org (download.savannah.gnu.org)|209.51.188.200|:80... failed: Connection timed out.
Connecting to download.savannah.gnu.org (download.savannah.gnu.org)|2001:470:142:5::200|:80... failed: Network is unreachable.
--2019-07-15 08:24:22--  http://sources.buildroot.net/attr/attr-2.4.48.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.25.211.19, 104.25.210.19, 2606:4700:20::6819:d213, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.211.19|:80... failed: Connection timed out.
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.210.19|:80... failed: Connection timed out.
Connecting to sources.buildroot.net (sources.buildroot.net)|2606:4700:20::6819:d213|:80... failed: Network is unreachable.
Connecting to sources.buildroot.net (sources.buildroot.net)|2606:4700:20::6819:d313|:80... failed: Network is unreachable.
--2019-07-15 08:28:39--  http://sources.buildroot.net/attr-2.4.48.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.25.210.19, 104.25.211.19, 2606:4700:20::6819:d313, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.210.19|:80... failed: Connection timed out.
Connecting to sources.buildroot.net (sources.buildroot.net)|104.25.211.19|:80... failed: Connection timed out.
Connecting to sources.buildroot.net (sources.buildroot.net)|2606:4700:20::6819:d313|:80... failed: Network is unreachable.
Connecting to sources.buildroot.net (sources.buildroot.net)|2606:4700:20::6819:d213|:80... failed: Network is unreachable.
make[2]: *** [/home/OP-TEE/out-br/build/host-attr-2.4.48/.stamp_downloaded] Error 1
make[1]: *** [_all] Error 2
make[1]: Leaving directory `/home/OP-TEE/out-br'
make: *** [buildroot] Error 2
`
And I can not find some setting like BR_ATT in build/br-ext/configs/, so how can I skip it? Thanks!

**Comment by vchong** [comment]
Sounds like a network issue on your side. It's not likely the sites are all down at the same time. Do you have a firewall blocking certain sites or download operations?

> And I can not find some setting like BR_ATT in build/br-ext/configs/

Not `BR_ATT`, just `BR2_CCACHE`. See https://github.com/OP-TEE/build/blob/master/br-ext/configs/optee_generic#L1. Sorry I also made a typo above (`BR_CCACHE` instead of `BR2_CCACHE`) which has been fixed.

**Comment by penpendandan** [comment]
yes, I found the firewall blocks the sites.  I have chosen to build these packages offline. Thanks very much!

**Comment by vchong** [comment]
You're welcome. I'm going to close this now but feel free to reopen or open a new issue if needed.
