### ISSUE TITLE
[hikey960] failed to flash and recovery

### ISSUE THREAD

**Issue by mofanv** [OP-TEE/optee_os#3128]
Hi,

To flash OPTEE on a Hikey 960, I followed [uart-adapter-board](https://optee.readthedocs.io/building/devices/hikey960.html#uart-adapter-board) and bought a 96 board UART. But seems my computer cannot connect Hikey board.

For `sudo make flash`, it stays at `waiting for device`.
For `sudo make recovery`, it stays at `download adress 0x200000`.

The UART message did not show `Android Fastboot mode`, and it only showed `boot mode is 4`.

Do I need to have another usb cable, i.e. with a Type-C OTG on the original board, in order to flash the OPTEE?

Thank you very much!

**Comment by vchong** [comment]
Yes, the Type-C cable is your fastboot connection.

**NOTE**: It's summer time and many people in the core team is on vacation, so expect delayed answers to both questions as well as feedback in pull requests!

**Comment by mofanv** [comment]
Thanks! will try
