### ISSUE TITLE
Secure Boot on QEMU

### ISSUE THREAD

**Issue by vivinamartins16** [OP-TEE/optee_os#3131]
Hi all!

1. I read the secure boot section here https://optee.readthedocs.io/architecture/secure_boot.html?highlight=secure%20boot and the user guide here: https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/getting_started/user-guide.rst

2. Downloaded mbedtls from arm's repo to my op-tee directory

3. My arm flags are as it follows:
```
ARM_TF_FLAGS ?= \
	BL32=$(OPTEE_OS_HEADER_V2_BIN) \
	BL32_EXTRA1=$(OPTEE_OS_PAGER_V2_BIN) \
	BL32_EXTRA2=$(OPTEE_OS_PAGEABLE_V2_BIN) \
	BL33=$(EDK2_BIN) \
	MBEDTLS_DIR=$(ARM_TF_PATH)/mbedtls \
	PLAT=qemu \
	ARM_TSP_RAM_LOCATION=tdram \
	BL32_RAM_LOCATION=tdram \
	PLAT=qemu \
	TRUSTED_BOARD_BOOT=1 \
	GENERATE_COT=1 \
	ARM_ROTPK_LOCATION=devel_rsa \
	ROT_KEY=$(ARM_TF_PATH)/plat/arm/board/common/rotpk/arm_rotprivk_rsa.pem \
	LOG_LEVEL=$(ARM_TF_LOGLVL)
```
4. My target platform is qemu - armv8 

5. My output on the secure world is:
```
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v2.0(release):v2.0-507-g34efb683
NOTICE:  BL1: Built : 17:17:19, Jul 15 2019
INFO:    BL1: RAM 0xe04e000 - 0xe058000
INFO:    Using crypto library 'mbed TLS'
INFO:    BL1: Loading BL2
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=6 at address 0xe01b000
WARNING: Failed to determine the size of the image id=6 (-2)
ERROR:   Failed to load BL2 firmware.
```
\- QUESTION: why did it failed on BL2? did I miss something?

Thanks!

**Comment by vivinamartins16** [comment]
Just an update:
- When I build with the above configs on qemu, I sse the following output (during build):

Trusted Boot Firmware BL2: offset=0x1F0, size=0x113B8, cmdline="--tb-fw"
EL3 Runtime Firmware BL31: offset=0x115A8, size=0x7070, cmdline="--soc-fw"
Secure Payload BL32 Extra1 (Trusted OS Extra1): offset=0x18618, size=0x51370, cmdline="--tos-fw-extra1"
Secure Payload BL32 Extra2 (Trusted OS Extra2): offset=0x69988, size=0x0, cmdline="--tos-fw-extra2"
Non-Trusted Firmware BL33: offset=0x69988, size=0x200000, cmdline="--nt-fw"
Trusted key certificate: offset=0x269988, size=0x60E, cmdline="--trusted-key-cert"
SoC Firmware key certificate: offset=0x269F96, size=0x4DA, cmdline="--soc-fw-key-cert"
Non-Trusted Firmware key certificate: offset=0x26A470, size=0x4EA, cmdline="--nt-fw-key-cert"
Trusted Boot Firmware BL2 certificate: offset=0x26A95A, size=0x46F, cmdline="--tb-fw-cert"
SoC Firmware content certificate: offset=0x26ADC9, size=0x430, cmdline="--soc-fw-cert"
Non-Trusted Firmware content certificate: offset=0x26B1F9, size=0x440, cmdline="--nt-fw-cert"

when it finishes, i find the secure world terminal stuck with the error described previously:

WARNING: Failed to determine the size of the image id=6 (-2)
ERROR: Failed to load BL2 firmware.

What else do I need to do?

**Comment by vchong** [comment]
Quick check of your arm flags shows that you're missing `SPD=opteed`, as confirmed by your build output, i.e. no line like `Secure Payload BL32 (Trusted OS): offset=0x155D2, size=0x1C, cmdline="--tos-fw"`.

**Comment by vivinamartins16** [comment]
Thanks @vchong ! I must have deleted it mistakenly, but I added it back and got the same error.

- Here's the build output:
```
...
Built build/qemu/release/bl1.bin successfully
...
Built build/qemu/release/bl2.bin successfully
...
Built build/qemu/release/bl2.bin successfully
...
Built tools/cert_create/cert_create successfully

NOTICE:  CoT Generation Tool: Built : 14:04:55, Jul 17 2019
NOTICE:  Target platform: TBBR Generic
NOTICE:  Creating new key for 'Trusted World key'
NOTICE:  Creating new key for 'Non Trusted World key'
NOTICE:  Creating new key for 'SCP Firmware Content Certificate key'
NOTICE:  Creating new key for 'SoC Firmware Content Certificate key'
NOTICE:  Creating new key for 'Trusted OS Firmware Content Certificate key'
NOTICE:  Creating new key for 'Non Trusted Firmware Content Certificate key'

Built certificates successfully
Certificates can be found in ./build/qemu/release

  HOSTCC  fiptool.c
  HOSTCC  tbbr_config.c
  HOSTLD  fiptool

Built fiptool successfully

Trusted Boot Firmware BL2: offset=0x268, size=0x115E0, cmdline="--tb-fw"
EL3 Runtime Firmware BL31: offset=0x11848, size=0x7070, cmdline="--soc-fw"
Secure Payload BL32 (Trusted OS): offset=0x188B8, size=0x1C, cmdline="--tos-fw"
Secure Payload BL32 Extra1 (Trusted OS Extra1): offset=0x188D4, size=0x51370, cmdline="--tos-fw-extra1"
Secure Payload BL32 Extra2 (Trusted OS Extra2): offset=0x69C44, size=0x0, cmdline="--tos-fw-extra2"
Non-Trusted Firmware BL33: offset=0x69C44, size=0x200000, cmdline="--nt-fw"
Trusted key certificate: offset=0x269C44, size=0x60E, cmdline="--trusted-key-cert"
SoC Firmware key certificate: offset=0x26A252, size=0x4DA, cmdline="--soc-fw-key-cert"
Trusted OS Firmware key certificate: offset=0x26A72C, size=0x4E8, cmdline="--tos-fw-key-cert"
Non-Trusted Firmware key certificate: offset=0x26AC14, size=0x4EA, cmdline="--nt-fw-key-cert"
Trusted Boot Firmware BL2 certificate: offset=0x26B0FE, size=0x46F, cmdline="--tb-fw-cert"
SoC Firmware content certificate: offset=0x26B56D, size=0x430, cmdline="--soc-fw-cert"
Trusted OS Firmware content certificate: offset=0x26B99D, size=0x4CE, cmdline="--tos-fw-cert"
Non-Trusted Firmware content certificate: offset=0x26BE6B, size=0x440, cmdline="--nt-fw-cert"

Built build/qemu/release/fip.bin successfully
```


- Here's the error:

```
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v2.0(release):v2.0-507-g34efb683
NOTICE:  BL1: Built : 14:04:51, Jul 17 2019
INFO:    BL1: RAM 0xe04e000 - 0xe058000
INFO:    Using crypto library 'mbed TLS'
INFO:    BL1: Loading BL2
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=6 at address 0xe01b000
WARNING: Failed to determine the size of the image id=6 (-2)
ERROR:   Failed to load BL2 firmware.

```

**Comment by vchong** [comment]
@vivinamartins16 I was able to reproduce the problem and make it work. First, plat qemu has its own `ROT_KEY` defined in `plat/qemu/platform.mk` so the build flags can just be:
```
ARM_TF_FLAGS ?= \
        BL32=$(OPTEE_OS_HEADER_V2_BIN) \
        BL32_EXTRA1=$(OPTEE_OS_PAGER_V2_BIN) \
        BL32_EXTRA2=$(OPTEE_OS_PAGEABLE_V2_BIN) \
        BL33=$(EDK2_BIN) \
        PLAT=qemu \
        ARM_TSP_RAM_LOCATION=tdram \
        BL32_RAM_LOCATION=tdram \
        SPD=opteed \
        DEBUG=$(ARM_TF_DEBUG) \
        LOG_LEVEL=$(ARM_TF_LOGLVL) \
        MBEDTLS_DIR=$(ARM_TF_PATH)/../mbedtls \
        TRUSTED_BOARD_BOOT=1 \
        GENERATE_COT=1
```

Next, since plat qemu doesn't use `fip.bin` directly, we need to create symlinks to all the certs (.crt files) in `arm-trusted-firmware/build/qemu/{debug,release}/` to `out/bin/` so that qemu can find them, otherwise we see load error above.

```
> ll out/bin/*.crt
lrwxrwxrwx 1 john.doe primary 110 Jul 18 09:02 out/bin/nt_fw_content.crt -> ../../arm-trusted-firmware/build/qemu/debug/nt_fw_content.crt
lrwxrwxrwx 1 john.doe primary 106 Jul 18 09:02 out/bin/nt_fw_key.crt -> ../../arm-trusted-firmware/build/qemu/debug/nt_fw_key.crt
lrwxrwxrwx 1 john.doe primary 111 Jul 18 09:02 out/bin/soc_fw_content.crt -> ../../arm-trusted-firmware/build/qemu/debug/soc_fw_content.crt
lrwxrwxrwx 1 john.doe primary 107 Jul 18 09:02 out/bin/soc_fw_key.crt -> ../../arm-trusted-firmware/build/qemu/debug/soc_fw_key.crt
lrwxrwxrwx 1 john.doe primary 102 Jul 18 09:01 out/bin/tb_fw.crt -> ../../arm-trusted-firmware/build/qemu/debug/tb_fw.crt
lrwxrwxrwx 1 john.doe primary 111 Jul 18 09:01 out/bin/tos_fw_content.crt -> ../../arm-trusted-firmware/build/qemu/debug/tos_fw_content.crt
lrwxrwxrwx 1 john.doe primary 107 Jul 18 09:01 out/bin/tos_fw_key.crt -> ../../arm-trusted-firmware/build/qemu/debug/tos_fw_key.crt
lrwxrwxrwx 1 john.doe primary 108 Jul 18 09:00 out/bin/trusted_key.crt -> ../../arm-trusted-firmware/build/qemu/debug/trusted_key.crt
```

**NOTE**: mbedtls tag used is 2.16.0

**Comment by vivinamartins16** [comment]
Thank you @vchong ! It worked perfectly!

- Here's my output:

```
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v2.0(release):v2.0-507-g34efb683
NOTICE:  BL1: Built : 09:27:08, Jul 18 2019
INFO:    BL1: RAM 0xe04e000 - 0xe058000
INFO:    Using crypto library 'mbed TLS'
INFO:    BL1: Loading BL2
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=6 at address 0xe01b000
INFO:    Image id=6 loaded: 0xe01b000 - 0xe01b46f
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=1 at address 0xe01b000
INFO:    Image id=1 loaded: 0xe01b000 - 0xe02c5e0
NOTICE:  BL1: Booting BL2
INFO:    Entry point address = 0xe01b000
INFO:    SPSR = 0x3c5
NOTICE:  BL2: v2.0(release):v2.0-507-g34efb683
NOTICE:  BL2: Built : 09:27:09, Jul 18 2019
INFO:    Using crypto library 'mbed TLS'
INFO:    BL2: Doing platform setup
INFO:    BL2: Loading image id 3
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=7 at address 0xe040000
INFO:    Image id=7 loaded: 0xe040000 - 0xe04060e
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=9 at address 0xe040000
INFO:    Image id=9 loaded: 0xe040000 - 0xe0404da
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=13 at address 0xe040000
INFO:    Image id=13 loaded: 0xe040000 - 0xe040430
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=3 at address 0xe040000
INFO:    Image id=3 loaded: 0xe040000 - 0xe047070
INFO:    BL2: Loading image id 4
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=10 at address 0xe100000
INFO:    Image id=10 loaded: 0xe100000 - 0xe1004e8
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=14 at address 0xe100000
INFO:    Image id=14 loaded: 0xe100000 - 0xe1004ce
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=4 at address 0xe100000
INFO:    Image id=4 loaded: 0xe100000 - 0xe10001c
INFO:    OPTEE ep=0xe100000
INFO:    OPTEE header info:
INFO:          magic=0x4554504f
INFO:          version=0x2
INFO:          arch=0x1
INFO:          flags=0x0
INFO:          nb_images=0x1
INFO:    BL2: Loading image id 21
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=21 at address 0xe100000
INFO:    Image id=21 loaded: 0xe100000 - 0xe151370
INFO:    BL2: Skip loading image id 22
INFO:    BL2: Loading image id 5
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=11 at address 0x60000000
INFO:    Image id=11 loaded: 0x60000000 - 0x600004ea
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=15 at address 0x60000000
INFO:    Image id=15 loaded: 0x60000000 - 0x60000440
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=5 at address 0x60000000
INFO:    Image id=5 loaded: 0x60000000 - 0x60200000
NOTICE:  BL1: Booting BL31
INFO:    Entry point address = 0xe040000
INFO:    SPSR = 0x3cd
NOTICE:  BL31: v2.0(release):v2.0-507-g34efb683
NOTICE:  BL31: Built : 09:27:11, Jul 18 2019
INFO:    ARM GICv2 driver initialized
INFO:    BL31: Initializing runtime services
INFO:    BL31: Initializing BL32
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x60000000
INFO:    SPSR = 0x3c5
ArmVirtGetMemoryMap: Dumping System DRAM Memory Map:
	PhysicalBase: 0x40000000
	VirtualBase: 0x40000000
	Length: 0x42100000
UEFI firmware (version  built at 14:24:53 on Jul 12 2019)
PlatformPeim: PL011 UART @ 0x9000000

```

**Comment by vchong** [comment]
You're welcome. Would be nice though if someone can figure out how to get rid of the `WARNING: Firmware Image Package header check failed.`

**Comment by 21212124** [comment]
help me
![errorTF](https://user-images.githubusercontent.com/30496643/67940594-4c1b3200-fbd4-11e9-9445-0ce5b4961f1d.PNG)

**Comment by jbech-linaro** [comment]
> help me

You forgot the "make toolchains" step?

**Comment by 21212124** [comment]
yes, sorry

**Comment by jbech-linaro** [comment]
> yes, sorry

No problem. Having said that and based on your questions here and in other threads I get the impression that you're not reading the instructions carefully enough. Prerequisites are important and so are all the initial build steps. Since it looks like you're playing with QEMU v8, I'd recommend you to start with trying to setup a [clean OP-TEE QEMU v8 setup](https://optee.readthedocs.io/en/latest/building/devices/qemu.html#id3) and run xtest. When that is working, then take the next step and explore other things (like the chain of trust that you're playing with in #3358). It's always easier to start from a known, good and stable state.

**Comment by vxfury** [comment]
> @vivinamartins16 I was able to reproduce the problem and make it work. First, plat qemu has its own `ROT_KEY` defined in `plat/qemu/platform.mk` so the build flags can just be:
> 
> ```
> ARM_TF_FLAGS ?= \
>         BL32=$(OPTEE_OS_HEADER_V2_BIN) \
>         BL32_EXTRA1=$(OPTEE_OS_PAGER_V2_BIN) \
>         BL32_EXTRA2=$(OPTEE_OS_PAGEABLE_V2_BIN) \
>         BL33=$(EDK2_BIN) \
>         PLAT=qemu \
>         ARM_TSP_RAM_LOCATION=tdram \
>         BL32_RAM_LOCATION=tdram \
>         SPD=opteed \
>         DEBUG=$(ARM_TF_DEBUG) \
>         LOG_LEVEL=$(ARM_TF_LOGLVL) \
>         MBEDTLS_DIR=$(ARM_TF_PATH)/../mbedtls \
>         TRUSTED_BOARD_BOOT=1 \
>         GENERATE_COT=1
> ```
> 
> Next, since plat qemu doesn't use `fip.bin` directly, we need to create symlinks to all the certs (.crt files) in `arm-trusted-firmware/build/qemu/{debug,release}/` to `out/bin/` so that qemu can find them, otherwise we see load error above.
> 
> ```
> > ll out/bin/*.crt
> lrwxrwxrwx 1 john.doe primary 110 Jul 18 09:02 out/bin/nt_fw_content.crt -> ../../arm-trusted-firmware/build/qemu/debug/nt_fw_content.crt
> lrwxrwxrwx 1 john.doe primary 106 Jul 18 09:02 out/bin/nt_fw_key.crt -> ../../arm-trusted-firmware/build/qemu/debug/nt_fw_key.crt
> lrwxrwxrwx 1 john.doe primary 111 Jul 18 09:02 out/bin/soc_fw_content.crt -> ../../arm-trusted-firmware/build/qemu/debug/soc_fw_content.crt
> lrwxrwxrwx 1 john.doe primary 107 Jul 18 09:02 out/bin/soc_fw_key.crt -> ../../arm-trusted-firmware/build/qemu/debug/soc_fw_key.crt
> lrwxrwxrwx 1 john.doe primary 102 Jul 18 09:01 out/bin/tb_fw.crt -> ../../arm-trusted-firmware/build/qemu/debug/tb_fw.crt
> lrwxrwxrwx 1 john.doe primary 111 Jul 18 09:01 out/bin/tos_fw_content.crt -> ../../arm-trusted-firmware/build/qemu/debug/tos_fw_content.crt
> lrwxrwxrwx 1 john.doe primary 107 Jul 18 09:01 out/bin/tos_fw_key.crt -> ../../arm-trusted-firmware/build/qemu/debug/tos_fw_key.crt
> lrwxrwxrwx 1 john.doe primary 108 Jul 18 09:00 out/bin/trusted_key.crt -> ../../arm-trusted-firmware/build/qemu/debug/trusted_key.crt
> ```
> 
> **NOTE**: mbedtls tag used is 2.16.0


Similar problem, but No "Built tools/cert_create/cert_create successfully" and no *crt files generated:
Trusted Boot Firmware BL2: offset=0x128, size=0x6410, cmdline="--tb-fw"
EL3 Runtime Firmware BL31: offset=0x6538, size=0x7070, cmdline="--soc-fw"
Secure Payload BL32 (Trusted OS): offset=0xD5A8, size=0x1C, cmdline="--tos-fw"
Secure Payload BL32 Extra1 (Trusted OS Extra1): offset=0xD5C4, size=0x59380, cmdline="--tos-fw-extra1"
Secure Payload BL32 Extra2 (Trusted OS Extra2): offset=0x66944, size=0x0, cmdline="--tos-fw-extra2"
Non-Trusted Firmware BL33: offset=0x66944, size=0x200000, cmdline="--nt-fw".

**Comment by vxfury** [comment]
Here is the output:
NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v2.2(debug):
NOTICE:  BL1: Built : 03:31:31, Nov  7 2019
INFO:    BL1: RAM 0xe04e000 - 0xe056000
VERBOSE: BL1: cortex_a57: CPU workaround for 806969 was not applied
WARNING: BL1: cortex_a57: CPU workaround for 813419 was missing!
VERBOSE: BL1: cortex_a57: CPU workaround for 813420 was not applied
VERBOSE: BL1: cortex_a57: CPU workaround for 814670 was not applied
WARNING: BL1: cortex_a57: CPU workaround for 817169 was missing!
INFO:    BL1: cortex_a57: CPU workaround for disable_ldnp_overread was applied
WARNING: BL1: cortex_a57: CPU workaround for 826974 was missing!
WARNING: BL1: cortex_a57: CPU workaround for 826977 was missing!
WARNING: BL1: cortex_a57: CPU workaround for 828024 was missing!
WARNING: BL1: cortex_a57: CPU workaround for 829520 was missing!
WARNING: BL1: cortex_a57: CPU workaround for 833471 was missing!
WARNING: BL1: cortex_a57: CPU workaround for 859972 was missing!
INFO:    BL1: cortex_a57: CPU workaround for cve_2017_5715 was applied
INFO:    BL1: cortex_a57: CPU workaround for cve_2018_3639 was applied
INFO:    BL1: Loading BL2
VERBOSE: Using Memmap
WARNING: Firmware Image Package header check failed.
VERBOSE: Trying alternative IO
WARNING: Failed to obtain reference to image id=1 (-2)
ERROR:   Failed to load BL2 firmware.

**Comment by vchong** [comment]
Tested this today and everything works as expected.

```
1. wget "repo" from Google and store it in $HOME/bin for example
2. $ mkdir foo
3. $ cd foo
4. $ repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml
5. $ repo sync -j4 --no-clone-bundle
6. $ cd build
7. edit qemu_v8.mk and set TF_A_TRUSTED_BOARD_BOOT ?= y
8. $ make -j`nproc` toolchains
9. $ make -j`nproc`
```

**Comment by vchong** [comment]
Also edit common.mk and set DEBUG ?= 1 after 7 and before 8.
