### ISSUE TITLE
Support for a new platform

### ISSUE THREAD

**Issue by ashwinnirantar** [OP-TEE/optee_os#3132]
Hi, 

I have ported OP-TEE to one of the boards I was working on. OP-TEE Version 3.3 works perfectly. Is there a way by which I can get the board I was working on to be one of the officially supported platforms for OP-TEE? Or do I need to have Linaro's membership for that?

Thanks.

**Comment by vchong** [comment]
Yes. Just submit a pull request (PR). Please see https://optee.readthedocs.io/general/contribute.html for details. No membership required.

**Comment by ashwinnirantar** [comment]
Thank you!
