### ISSUE TITLE
API to add mapping for physical address in TA

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#3133]
Hi, 
I want to map a region of physical address(accessed only in secure world) in TA, is currently any API can do this? Or the only way is to use a PTA converting the PA and then passing the VA  to TA? In the later case,  If I use core_mmu_add_mapping, seems there's no API to unmap the PA?
I also see there's vm_map function,  is it better than core_mmu_add_mapping in this case? Thx!

**Comment by vchong** [comment]
**NOTE**: It's summer time and many people in the core team is on vacation, so expect delayed answers to both questions as well as feedback in pull requests!

> is currently any API can do this?

No. Please see https://github.com/OP-TEE/optee_os/issues/1810 for a previously related thread.

> Or the only way is to use a PTA converting the PA and then passing the VA to TA?

I guess but it doesn't sound safe though.

> In the later case, If I use core_mmu_add_mapping, seems there's no API to unmap the PA? I also see there's vm_map function, is it better than core_mmu_add_mapping in this case?

Sorry but I'm not familiar with these so please wait till the others in the core team return from their summer break.

**Comment by jenswi-linaro** [comment]
Since it's TA specific mapping you should probably base the new function on `vm_map()`. That will add it as a mapping for a specific user TA context.

**Comment by tiger20081015** [comment]
@jenswi-linaro , thanks for the hint. 

Could you pls give some more detailed info about how to use vm_map? I looked into the function today, but I'm quite confused about setting up a mobj struct for a user specified physical memory as a parameter. Do I have to add a new memory type like CORE_MEM_TEE_RAM? It seems mobj_phys_alloc can only get memory from CORE_MEM_TEE_RAM/CORE_MEM_TA_RAM/CORE_MEM_NSEC_SHM/CORE_MEM_SDP_MEM. 

Thanks in advance.

**Comment by tiger20081015** [comment]
@jenswi-linaro ,thanks for your hint. I wrote a PTA using vm_map(). The core function is:
```
279 extern const struct mobj_ops mobj_phys_ops;
280 static TEE_Result map_paddr_to_user_ta(struct user_ta_ctx *utc, paddr_t pa, size_t len)
281 {                                                                                                                                                                                                               
282 >---TEE_Result res = TEE_SUCCESS;
283 >---struct mobj *mobj = NULL;
284 >---vaddr_t va = 0;
285 >---paddr_t b;
286 >---const uint32_t prot = TEE_MATTR_PRW | TEE_MATTR_URW | TEE_MATTR_PERMANENT;
287 >---struct mobj_phys *moph;
288 
289 >---moph = calloc(1, sizeof(*moph));
290 >---if (!moph)
291 >--->---return NULL;
292 
293 >---moph->battr = CORE_MEM_USER_SPC_MEM;
294 >---moph->cattr = TEE_MATTR_CACHE_CACHED;
295 >---moph->mobj.size = len;
296 >---moph->mobj.ops = &mobj_phys_ops;
297 >---moph->pa = pa;
298 >---moph->va = 0;
299 
300 >---mobj = &(moph->mobj);
301 
302 >---res = vm_map(utc, &va, len, prot, mobj, offs);
303 >---if (res)
304 >--->---EMSG("vm_map error, res = 0x%x", res);
305 
306 >---return res;
307 }
```
However, I need to modify some open source code to implement it:
a. Added a new memory type " CORE_MEM_USER_SPC_MEM" to indicate the physical memory range set by user ta;
b. Move struct mobj_phys from mobj.c to mobj.h so that PTA can refer to it;
c. Based on the same reason in item b, I  export mobj_phys_ops in my PTA.

Although the function works successfully, is there any more standard operation to minims the change to open source code? Currently change looks quite ugly. And is there any kernel API to unmap the address mapped by vm_map? Thanks!

**Comment by jenswi-linaro** [comment]
Mappings established with `vm_map()` can be removed with `vm_unmap()`.

With the information at hand I can't give any good advice on how to integrate it better.
