### ISSUE TITLE
Kernel API: Passing struct to user TA using shared memory

### ISSUE THREAD

**Issue by tech-drv** [OP-TEE/optee_os#3134]
Hi folks,

I'm currently working on a kernel module which uses the tee driver kernel api to invoke a function in my user TA. Invoking a function using value parameters works fine but I need to pass a struct as a parameter. I think I need shared memory for this.
I thought it may works this way in general:

1. Allocation of shared memory
2. Memcopy my_struct to the allocated shared memory
3. Pass address of shared memory as parameter
4. Read from shared memory in TA

Maybe it sounds a bit naive to you, but I'm quite new to optee and can't find documentation on how to do this using the kernel API.

I found #2501 and know that I have to use `tee_shm_alloc`. 
Allocation of shared memory using `tee_shm_alloc` just works fine but I don't know how to copy my struct to the shared memory using the returned `struct tee_shm`.

This is how my code currently looks like:
```
shm = tee_shm_alloc(ctx, sizeof(struct my_struct), TEE_SHM_MAPPED | TEE_SHM_DMA_BUF);
    if (IS_ERR(shm)) {
        printk("tee_shm_alloc failed\n");
        return PTR_ERR(shm);
}
....
/*How to copy my struct to shared memory here? */
...
invokeParams[0].attr = TEE_IOCTL_PARAM_ATTR_TYPE_MEMREF_INPUT;
invokeParams[0].u.memref.shm = shm;
invokeParams[0].u.memref.size = sizeof(struct my_struct);
invokeParams[0].u.memref.shm_offs = 0;
```

I thought I could simply do
```
struct my_struct *mstr = NULL;
    mstr = (struct my_struct*)params[0].memref.buffer;
```
to access the struct in my TA afterwards. 
Optee driver: linaro-swg/linux (branch-optee-v4.18-20181105).
Optee_os version: 3.0.0
Platform: Juno r1
TA type: REE filesystem TA

I would really appreciate any help. Thanks in advance.

**Comment by tech-drv** [comment]
Looks like `memcpy(shm->kaddr,&mystr,sizeof(struct my_struct));` did the job. 
I tried it two days ago and I'm not sure why it didn't worked then. Maybe I've changed something while experimenting. 
I'll leave this issue open because I'm not sure if using memcpy is considered best practice in this case.

**Comment by vchong** [comment]
@tech-drv Looks ok to me. `memref.buffer` isn't available in the kernel APIs.
@b49020 Do you have any comments?

**Comment by b49020** [comment]
@tech-drv you need to use `tee_shm_get_va` to get a virtual address for shm buffer as follows:

```
mstr = tee_shm_get_va(shm, 0);
    if (IS_ERR(mstr)) {
        printk("tee_shm_get_va failed\n");
        return PTR_ERR(shm);
}
```
BTW, you could refer to `https://github.com/torvalds/linux/blob/master/drivers/char/hw_random/optee-rng.c` for detailed usage.

**Comment by tech-drv** [comment]
@vchong @b49020 Thanks!

**Comment by Noufalp90** [comment]
> Looks like `memcpy(shm->kaddr,&mystr,sizeof(struct my_struct));` did the job.
> I tried it two days ago and I'm not sure why it didn't work then. Maybe I've changed something while experimenting.
> I'll leave this issue open because I'm not sure if using memcpy is considered best practice in this case.

Hi, can you please tell me how could I access/use this shared memory from my Trusted or Pseudo trusted application?
