### ISSUE TITLE
ImportError: No module named 'resource'

### ISSUE THREAD

**Issue by PratikGajera** [OP-TEE/optee_os#3137]
Dear Team,

I am building latest optee os (v3.6.0) for imx6ull board and getting build time error:

NOTE: I have installed required packages as suggested on (https://github.com/jforissier/docker_optee_os_ci/commit/f397f10bb1d9).

> mkdir -p out/arm-plat-imx/core
> scripts/gen_ldelf_hex.py --input out/arm-plat-imx/ldelf/ldelf.elf --output out/arm-plat-imx/core/ldelf_hex.c
> Traceback (most recent call last):
>   File "scripts/gen_ldelf_hex.py", line 12, in <module>
>     from elftools.elf.elffile import ELFFile
>   File "/home/pratik/.local/lib/python3.5/site-packages/elftools/elf/elffile.py", line 10, in <module>
>     import resource
> ImportError: No module named 'resource'
> mk/subdir.mk:158: recipe for target 'out/arm-plat-imx/core/ldelf_hex.c' failed
> make: *** [out/arm-plat-imx/core/ldelf_hex.c] Error 1

Even, resource module is available in my system. I have tested though one python demo application. 
Please suggest me, any configuration missing here.

Thanks,
PG

**Comment by vchong** [comment]
Try `pip install python-resources`.

**Comment by PratikGajera** [comment]
@vchong, thanks for your suggestion. I have tried to build OPTEE with installing "resources" module, but still getting same error. Also, resources package is available in my system "/home/pratik/.local/lib/python3.5/site-packages/".

**Comment by jbech-linaro** [comment]
@PratikGajera any success or still an issue? I cannot recall that I've seen a need for the `resource` module in other setups. However, if it is needed, then we should add it to the [Prerequisites](https://optee.readthedocs.io/building/prerequisites.html).

**Comment by gitgonewithwind** [comment]
my host is  opensuse-42.3 and installed pip install python-resources
but it's still error:
---------
| Traceback (most recent call last):
|   File "scripts/gen_ldelf_hex.py", line 12, in <module>
|     from elftools.elf.elffile import ELFFile
| ImportError: No module named 'elftools'

**Comment by gitgonewithwind** [comment]
done 

pip install pyelftools

**Comment by jbech-linaro** [comment]
> done

As in not an issue any longer?
