### ISSUE TITLE
Guidelines for new drivers

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#3140]
I want to ask for new drivers that could potentially be added in core/drivers folder, does OPTEE or GP recommend any specific structure or guideline ?

**Comment by vchong** [comment]
@a2t2 I don't see any specifics in https://optee.readthedocs.io. GP only specifies the higher level APIs but not really the lower level implementations. I think the best way forward is to reference an existing driver that's closest to your needs. E.g. for UARTS see pl011.c, IO drivers - pl061_gpio.c or pl022_spi.c, interrupts - gic.c.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
