### ISSUE TITLE
Can't link against libmbedtls

### ISSUE THREAD

**Issue by MaXwEllDeN** [OP-TEE/optee_os#3141]
Hello, fellows.

I'm trying to execute an SSL client using [this application](https://github.com/ARMmbed/mbedtls/blob/master/programs/ssl/ssl_client1.c) as a sketch, but I'm getting some undefined reference errors.

```
build/optee_examples-1.0/ztp_ssl_client/ta/ztp_ssl_client_ta.c:103: undefined reference to `mbedtls_net_init'
build/optee_examples-1.0/ztp_ssl_client/ta/ztp_ssl_client_ta.c:104: undefined reference to `mbedtls_ssl_init'
build/optee_examples-1.0/ztp_ssl_client/ta/ztp_ssl_client_ta.c:105: undefined reference to `mbedtls_ssl_config_init'
```
I've already tried to follow the recommendations [here](https://optee.readthedocs.io/building/trusted_applications.html#sub-mk-directives), but no success.

`ta/sub.mk`
```
global-incdirs-y += include
srcs-y += ztp_ssl_client_ta.c

libnames += mbedtls
libdirs += lib/libmbedtls
libdeps += $(ta-dev-kit-dir$(sm))/lib/libmbedtls.a

```
Command entry point:

```
static TEE_Result cmd_get_timestamp(uint32_t param_types,
				TEE_Param params[4])
{
	const uint32_t exp_param_types =
		TEE_PARAM_TYPES(TEE_PARAM_TYPE_NONE,
				TEE_PARAM_TYPE_NONE,
				TEE_PARAM_TYPE_NONE,
				TEE_PARAM_TYPE_NONE);


	if (param_types != exp_param_types)
		return TEE_ERROR_BAD_PARAMETERS;

    int ret = 1, len;
    int exit_code = MBEDTLS_EXIT_FAILURE;
    mbedtls_net_context server_fd;
    uint32_t flags;
    unsigned char buf[1024];
    const char *pers = "ssl_client1";

    mbedtls_entropy_context entropy;
    mbedtls_ctr_drbg_context ctr_drbg;
    mbedtls_ssl_context ssl;
    mbedtls_ssl_config conf;
    mbedtls_x509_crt cacert;

    /*
     * 0. Initialize the RNG and the session data
     */
    mbedtls_net_init( &server_fd );
    mbedtls_ssl_init( &ssl );
    mbedtls_ssl_config_init( &conf );
    mbedtls_x509_crt_init( &cacert );
    mbedtls_ctr_drbg_init( &ctr_drbg );

    DMSG("\n  . Seeding the random number generator...");

    mbedtls_entropy_init( &entropy );

	return TEE_SUCCESS;
}
```

Any clues on what I'm doing wrong here?

Thank you for your attention.

**Comment by jforissier** [comment]
Hi @MaXwEllDeN,

My guess is the functions you're trying to use are not int OP-TEE's version of libmbedtls.

**Comment by MaXwEllDeN** [comment]
Hello @jforissier, thank you for replying so quickly.

I'm not sure if it really is, but i have checked the library files and seems that these funcions that i'm trying to use have at least a simple scope implemented [here](https://github.com/OP-TEE/optee_os/blob/3d3b05918ec9052ba13de82fbcaba204766eb636/lib/libmbedtls/mbedtls/library/net_sockets.c#L139), [here](https://github.com/OP-TEE/optee_os/blob/3d3b05918ec9052ba13de82fbcaba204766eb636/lib/libmbedtls/mbedtls/library/ssl_tls.c#L6838) and [here](https://github.com/OP-TEE/optee_os/blob/3d3b05918ec9052ba13de82fbcaba204766eb636/lib/libmbedtls/mbedtls/library/ssl_tls.c#L9008). 

I'm right?

**Comment by MaXwEllDeN** [comment]
Hi, I just realized that the libraries had to be enabled in the config file `lib/libmbedtls/include/mbedtls_config_uta.h` by adding the following defines:

```
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_SSL_PROTO_SSL3
#define MBEDTLS_NET_C

```

Also, I didn't even need to change the sub.mk the way I posted, probably because this linking is done in other Makefile.

Finally, I'm now getting some include errors and I think that in order to advance I must port the remaining functions to OPTEE.

```
  CC      out/arm/ta_arm32-lib/libmbedtls/mbedtls/library/net_sockets.o
lib/libmbedtls/mbedtls/library/net_sockets.c:84:10: fatal error: sys/socket.h: No such file or directory
 #include <sys/socket.h>
          ^~~~~~~~~~~~~~
```
