### ISSUE TITLE
Multiple TA Instances in OP-TEE

### ISSUE THREAD

**Issue by TheFrozenDuck** [OP-TEE/optee_os#3142]
I read through the OP-TEE documentation and the the underlying specification of the GlobalPlatform and got 2 questions regarding spawning multiple instances:. 

##### Parallelization
The initialization of an instance is sequential as per GP specification (2.1.3 Sequential Execution of Entry Points). What happens to this requirement of being sequential afterwards? Do the newly spawned instances run parallel?

##### Memory
OP-TEE has two kinds of L1 translation tables, the one mapping up to 4GB one and multiple smaller ones mapping up to 32MB. Does creating a new instance take the memory away from the big one, or does a new instance gets its own big L1 table, etc.?

**Comment by jforissier** [comment]
Hi @TheFrozenDuck,

> **Parallelization**

Yes, multiple instance TAs run in parallel. Try for example several instances of `xtest --aes-perf &`. The same TA is used, it is a multiple instance TA.

**Comment by TheFrozenDuck** [comment]
What about the memory? Is the 4GB split for each instance, etc.?

On one hand the documentation states that the big translation table maps 4GB (which still could be potentially programmatically increased as e.g. the referenced ARM Cortex a-53's TTBR1 register can be changed to 64 bit).

On the other hand the first answer in Issue #1724 stats that the heap is only limited by the physical memory,

**Comment by vchong** [comment]
@TheFrozenDuck Based on https://optee.readthedocs.io/architecture/core.html?highlight=translation#translation-tables, it seems like there's only 1 4GB table.

**Note**: It's summer time and many people in the core team is on vacation, so expect delayed answers to both questions as well as feedback in pull requests!

**Comment by TheFrozenDuck** [comment]
That's answers my question, I'll close this now. 

Sorry for the formulation, in the retrospective it sounds pressuring.
