### ISSUE TITLE
Infinite loop in possibly unused code

### ISSUE THREAD

**Issue by justin-chadwell-arm** [OP-TEE/optee_os#3143]
Recently, on a project that uses some code from Optee OS, we ran into a Coverity scan issue in `__aeabi_imod` [here](https://github.com/OP-TEE/optee_os/blob/beb065df6ee53d014366068a138ccdb780b733d0/lib/libutils/isoc/arch/arm/arm32_aeabi_divmod.c#L145). The function appears to loop forever whenever `denominator` is not a power of two.

![coverity_screenshot](https://user-images.githubusercontent.com/52453205/61637468-7e40fd80-ac8f-11e9-8aee-9a5be2db91a8.png)

Upon further inspection, it appears that this function is not used anywhere, and not documented anywhere, and does not appear even in web searches, unlike some of the other functions in the same file. It seems like this function would be safe to remove?

**Comment by vchong** [comment]
@justin-chadwell-arm

**NOTE**: It's summer time and many people in the core team is on vacation, so expect delayed answers to both questions as well as feedback in pull requests!

From the comment `/* in case modulo of a power of 2 */` it looks like maybe the function is only supposed to be called for that case. Perhaps we can add a check or assert for that. As for removing it, looks like `__aeabi_uimod` isn't used anywhere as well and not sure if the core developers want to keep it (them) for future use, so let's wait for their comments.

**Comment by jenswi-linaro** [comment]
The function is documented in http://infocenter.arm.com/help/topic/com.arm.doc.ihi0043d/IHI0043D_rtabi.pdf

I don't think we should remove the function, rather fix it.

**Comment by justin-chadwell-arm** [comment]
Just had a quick look through the pdf: while other `__aeabi_*` functions are documented there, I can't see any reference to `__aeabi_imod` or `__aeabi_uimod` or `imod` and `uimod` in general.

**Comment by jenswi-linaro** [comment]
That was curios. I guess this code was based on some older version of the specification.
A pull request to remove the functions not needed by the specification is welcome.
