### ISSUE TITLE
Why not to invalidate the dcache before enable it.

### ISSUE THREAD

**Issue by jeffrey4913** [OP-TEE/optee_os#3145]
Hi ,
I am concerned that why there is no invalidate dcache opeation before enable it in the file proc_a64.S

**Comment by jenswi-linaro** [comment]
For AArch64 OP-TEE is initialized at S-EL1. TF-A or some other EL3 firmware has already invalidated the dcache.

**Comment by jeffrey4913** [comment]
Hi,
Thanks for your reply.
I means that before enabling dcache, why not invalidate it. When enable Icache, will invalidate it.
![image](https://user-images.githubusercontent.com/16753720/62192442-36fdef80-b3a8-11e9-8b19-302735f5d0b1.png)

**Comment by jenswi-linaro** [comment]
The icache is different. I don't know if it's strictly needed to be invalidated here or not, but it's very cheap to do here.

**Comment by jeffrey4913** [comment]
Yes, but is's a risk here if there is dirty data in the cache line.
