### ISSUE TITLE
Invoke PTA function from interrupt context

### ISSUE THREAD

**Issue by tech-drv** [OP-TEE/optee_os#3147]
Hi Folks,

Is there a way to spawn or retrieve a secure thread in interrupt context?
I am developing a PTA with `TA_FLAG_INSTANCE_KEEP_ALIVE` flag. One of the functions should be triggered by an interrupt.
I've registered the interrupt according to #2925 which works fine. 
Is there any way I can use some client like API (e.g. open_session, invoke_command, ...)?
Currently, my interrupt handler doesn't really do anything:
```
static enum itr_return itr_handler(struct itr_handler *handler __unused)
{
	IMSG("Invoked interrupt handler");
        /* Invoke TA function here*/
	return ITRR_HANDLED;
}
```

I'm using master branch at  e260ea8
I would be very happy about any kind of help.
Thanks

**Comment by lorc** [comment]
Unfortunately, no. OP-TEE is scheduled only by Normal World. It can't (and probably should not) create threads by its own, because this will interfere with NW scheduling.

The best option for now is to periodically poll your PTA from Normal World to check if there any work present.

**Comment by tech-drv** [comment]
@lorc Ok, thanks! I thought it isn't possible as of desing of optee but I wanted to ensure this.Polling my PTA from Normal World works without any Problems.
