### ISSUE TITLE
can I use the c lilbrary in ta?

### ISSUE THREAD

**Issue by tulipper** [OP-TEE/optee_os#3150]
Hello there
I need to do some complex computing, so I want to use the c library such as the math library for computing exponent function and the  standard library for dynamic memory allocating. So I want to konw is there any way to use the c library, or Is there any Alternatives to achieve the same goal?
Thank you in anvance.

**Comment by jforissier** [comment]
Hi @tulipper,

The C library in OP-TEE is `libutils.a`, it is a stripped down libc which is not meant to cover everything in the standard, but we do add things there from time to time. As you can see in the code, we usually pick functions from newlib.

There is no `libm` in OP-TEE however. Perhaps we could consider adding it.

Feel free to propose patches.

**Comment by tulipper** [comment]
Thank  you @jforissier 
Are the header files located in the /optee_os/out/arm-plat-hikey/export-ta_arm64/include ?
but this folder has no math.h
> There is no libm in OP-TEE however. Perhaps we could consider adding it.
does this mean I can not use the memory allocate function such as malloc()? but the folder mention above contains malloc.h
I don't konw the branch exactly, I clone the optee from the android_optee repo [here](https://github.com/linaro-swg/optee_android_manifest)

**Comment by vchong** [comment]
> Are the header files located in the /optee_os/out/arm-plat-hikey/export-ta_arm64/include ?

Yes

> but this folder has no math.h

Right. As mentioned earlier, there's no `libm`.

> does this mean I can not use the memory allocate function such as malloc()? but the folder mention above contains malloc.h

How is `malloc()` related to `libm`? Anyway, in a TA, it's better to use GP Internal Core APIs like `TEE_Malloc()` and friends. For math, there's a set of TEE Arithmetical API you can look at to see if they satisfy your needs or not.

> I don't konw the branch exactly, I clone the optee from the android_optee repo here

Master branch is used, although an older snapshot of it. The C library stuffs don't change that often though afaik.

**Comment by tulipper** [comment]
Thank you vchong
sorry, I made a mistake. I thought the libm is related to the memory, a stupid mistake. Thank you for your advice.

**Comment by vchong** [comment]
You're welcome @tulipper and no worries. Good luck and please close the issue if your question is answered.
