### ISSUE TITLE
function calls for PTA same as TA from Normal world?

### ISSUE THREAD

**Issue by alekarasma** [OP-TEE/optee_os#3153]
Hello All,

I am implementing PTA in optee core and will call this PTA directly from Normal world.
So to invoke PTA, Do I have to use same function call as it is use to invoke TA from normal world as given below
TEEC_Result TEEC_InitializeContext(const char *name, TEEC_Context *context);
TEEC_Result TEEC_InvokeCommand(TEEC_Session *session,
			       uint32_t commandID,
			       TEEC_Operation *operation,
			       uint32_t *returnOrigin);
I referred following thread
https://github.com/OP-TEE/optee_os/issues/3122

but there @jbech-linaro has given example in which execution is from CA--->TA--->PTA.
Can I directly call PTA from above functions?

Any help would be really appreciated, thank you.

Asma

**Comment by jenswi-linaro** [comment]
Yes, you can call CA-->PTA. It's up to the PTA if it permits normal world calls, if nothing special is done it's normally permitted.

**Comment by alekarasma** [comment]
Thanks, i tried and its working. I will close the issue.
