### ISSUE TITLE
Concern on MMU LPAE

### ISSUE THREAD

**Issue by jeffrey4913** [OP-TEE/optee_os#3161]
Hi,
I am reading core_mmu_lpae implentation now.
I have an concern in the function core_mmu_entry_to_finer_grained:
![image](https://user-images.githubusercontent.com/16753720/62192693-a542b200-b3a8-11e9-8dba-448f4422080f.png)
In the line810, when the `*entry` is not null, means that is's a block description, 
And we want to split it into smaller page,right?
If so, in line 814/815 maybe like this:
new_table[i] = pa | attr | BLOCK_DESC;
pa += 1 << block_size_on_next_lvl;

Look forward to your reply!

**Comment by etienne-lms** [comment]
Seems you found something here. Indeed your proposal looks fine to me.

That said, this function is currently used only to map memory with small pages on a virtual memory range that is not yet mapped, hence `*entry` is always null at line 810 and buggy instruction block never called. I wonder if we should really want this function to replace an existing mapping.

All in one, I think either this function should panic if applied on an existing mapping (`*entry != 0`) or it should properly remap the area with a high descriptor level (with the corrections you suggest).

@jenswi-linaro,  @lorc, your thoughts?

**Comment by lorc** [comment]
Hmmm, yes, looks like there is a bug there.

Indeed, there should be `new_table[i] = pa | attr | BLOCK_DESC;`

Also we need either to rename `block_size_on_next_lvl` to `block_shift_on_next_lvl` or declare it as `1 << (L1_XLAT_ADDRESS_SHIFT - tbl_info->level * XLAT_TABLE_ENTRIES_SHIFT));`

It is working only because right now we always put right entries after shattering the larger block.

@jeffrey4913, you could submit patch that fixes that if you want to.
Or, if you prefer, I can make the patch.

**Comment by jeffrey4913** [comment]
Hi All,
Thanks for your reply.
I will make a patch request for this issue.

**Comment by jeffrey4913** [comment]
Hi,
I make a pull requrest, but there is one item error, i don't know how to do it.
Something like i don't add description there.
![image](https://user-images.githubusercontent.com/16753720/62288888-efeb2980-b48f-11e9-9110-946346cc59c3.png)

**Comment by jforissier** [comment]
Your commit text does not follow the expected format:

```
Commit subject
[empty line]
Commit description
[empty line]
Signed-of-by: Your RealName <your@email.address>
```

**Comment by jeffrey4913** [comment]
I think i follow the format:
![image](https://user-images.githubusercontent.com/16753720/62290163-3b530700-b493-11e9-80bc-f1ca9bbb8bf1.png)

**Comment by jbech-linaro** [comment]
When I'm checking out your patch I get
```patch
commit b532ba41dfeb46b81fa887dc10201295d3e50e1c (HEAD -> github_pr_3164)
Author: jeffrey <363929442@qq.com>
Date:   Thu Aug 1 10:59:41 2019 +0800

    core: arm: core_mmu_lpae.c: fix searching for appropriate page table level issue
    Declare block_size_on_next_lvl as
        1 << (L1_XLAT_ADDRESS_SHIFT - tbl_info->level * XLAT_TABLE_ENTRIES_SHIFT));
    Change new_table to BLOCK_DESC
    
    Signed-off-by: jeffrey <363929442@qq.com>
```
I.e., empty line missing between subject and the commit message. On your image above I admit that it doesn't look like that. But, both Travis and I see it when checking out the patch. Have you changed the commit message, but forgot to push?

**Comment by jeffrey4913** [comment]
Thanks, I will try it.
