### ISSUE TITLE
Booting optee on xilinx zc702

### ISSUE THREAD

**Issue by eloysu205** [OP-TEE/optee_os#3162]
Hello, 
i am trying to boot optee on zc702 and using optee version 3.3.0. The boot process freezes after outputting "Primary CPU switching to normal world boot". The console information is: 

```D/TC:0 0 add_phys_mem:539 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x3e000000 size 0x0006e000
D/TC:0 0 add_phys_mem:539 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x3e06e000 size 0x00092000
D/TC:0 0 add_phys_mem:539 TA_RAM_START type TA_RAM 0x3e100000 size 0x01e00000
D/TC:0 0 add_phys_mem:539 TEE_SHMEM_START type NSEC_SHM 0x3ff00000 size 0x00100000
D/TC:0 0 add_phys_mem:539 CONSOLE_UART_BASE type IO_NSEC 0xe0000000 size 0x00200000
D/TC:0 0 add_phys_mem:539 GIC_BASE type IO_SEC 0xf8f00000 size 0x00100000
D/TC:0 0 add_phys_mem:539 PL310_BASE type IO_SEC 0xf8f00000 size 0x00200000
D/TC:0 0 add_phys_mem:552 Physical mem map overlaps 0xf8f00000
D/TC:0 0 add_phys_mem:539 SLCR_BASE type IO_SEC 0xf8000000 size 0x00100000
D/TC:0 0 add_phys_mem:539 GPIO_BASE type IO_NSEC 0x43c00000 size 0x00100000
D/TC:0 0 verify_special_mem_areas:477 No NSEC DDR memory area defined
D/TC:0 0 add_va_space:578 type RES_VASPACE size 0x00a00000
D/TC:0 0 add_va_space:578 type SHM_VASPACE size 0x02000000
D/TC:0 0 dump_mmap_table:711 type TEE_RAM_RX   va 0x3e000000..0x3e06dfff pa 0x3e000000..0x3e06dfff size 0x0006e000 (smallpg)
D/TC:0 0 dump_mmap_table:711 type TEE_RAM_RW   va 0x3e06e000..0x3e0fffff pa 0x3e06e000..0x3e0fffff size 0x00092000 (smallpg)
D/TC:0 0 dump_mmap_table:711 type SHM_VASPACE  va 0x3e100000..0x400fffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type IO_SEC       va 0x40100000..0x402fffff pa 0xf8f00000..0xf90fffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type RES_VASPACE  va 0x40300000..0x40cfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type TA_RAM       va 0x40d00000..0x42afffff pa 0x3e100000..0x3fefffff size 0x01e00000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type NSEC_SHM     va 0x42b00000..0x42bfffff pa 0x3ff00000..0x3fffffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type IO_NSEC      va 0x42c00000..0x42cfffff pa 0x43c00000..0x43cfffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type IO_NSEC      va 0x42d00000..0x42efffff pa 0xe0000000..0xe01fffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:711 type IO_SEC       va 0x42f00000..0x42ffffff pa 0xf8000000..0xf80fffff size 0x00100000 (pgdir)
D/TC:0 0 core_mmu_alloc_l2:238 L2 table used: 1/4
I/TC: 
D/TC:0 0 init_canaries:164 #Stack canaries for stack_tmp[0] with top at 0x3e09a838
D/TC:0 0 init_canaries:164 watch *0x3e09a83c
D/TC:0 0 init_canaries:164 #Stack canaries for stack_tmp[1] with top at 0x3e09af78
D/TC:0 0 init_canaries:164 watch *0x3e09af7c
D/TC:0 0 init_canaries:165 #Stack canaries for stack_abt[0] with top at 0x3e09b7b8
D/TC:0 0 init_canaries:165 watch *0x3e09b7bc
D/TC:0 0 init_canaries:165 #Stack canaries for stack_abt[1] with top at 0x3e09bff8
D/TC:0 0 init_canaries:165 watch *0x3e09bffc
D/TC:0 0 init_canaries:167 #Stack canaries for stack_thread[0] with top at 0x3e09e038
D/TC:0 0 init_canaries:167 watch *0x3e09e03c
D/TC:0 0 init_canaries:167 #Stack canaries for stack_thread[1] with top at 0x3e0a0078
D/TC:0 0 init_canaries:167 watch *0x3e0a007c
I/TC: OP-TEE version: 3.3.0-dev #1 Tue Jul 30 09:29:27 UTC 2019 arm
D/TC:0 0 tee_ta_register_ta_store:534 Registering TA store: 'REE' (priority 10)
D/TC:0 0 tee_ta_register_ta_store:534 Registering TA store: 'Secure Storage TA' (priority 9)
D/TC:0 0 mobj_mapped_shm_init:702 Shared memory address range: 3e100000, 40100000
E/TC:0 0 plat_rng_init:354 Warning: seeding RNG with zeroes
I/TC: Initialized
D/TC:0 0 init_primary_helper:937 Primary CPU switching to normal world boot
```  
After analyze of the **generic_entry_a32.S**, in the console there should be another output such as "**Secondary CPU Switching to normal world boot**", but it is missing. Then i added some debug codes into **generic_entry_a32.S** to find out, where is it exactly been stopped.

- In **LOCAL_FUNC reset_primary**:
```
    /* release secondary boot cores and sync with them */
    cpu_is_ready
    bl debug /* console output: position 1*/
    flush_cpu_semaphores
    bl debug /* console output: position 2*/
    wait_secondary
    bl debug /* console output: position 3*/
```
_flush_cpu_semaphores_ is executed. The program stops at _wait_secondary_.

- Then in **LOCAL_FUNC reset_secondary**:
```
    bl core_init_mmu_regs
    bl debug /* console output: position 6*/
    bl cpu_mmu_enable
    bl debug /* console output: position 7*/
```
_core_init_mmu_regs_ is executed, but the program freezes during the execution of _cpu_mmu_enable_.

Any idea how to solve this?

**Comment by eloysu205** [comment]
Update: after using JTAG and enable linux kernel low level debug config _CONFIG_DEBUG_LL_ and so we have confirmed that the problem is linux kernel try to access SLCR as described in [https://github.com/OP-TEE/optee_os/issues/1478#issuecomment-339602897](https://github.com/OP-TEE/optee_os/issues/1478#issuecomment-339602897). 
The exact problem is in kernel "drivers/clk/zynq/clkc.c", it tries to access such as **ARM PLL Control**, **DDR PLL Control**, etc., which can only be accessed in secure world. 
So, how to solve this problem? I have thought about to use SMC call and to handle such calls in secure world, is that a right direction? or other possible solution?

**Comment by alwyas** [comment]
Hi @eloysu205, I am also using zync 7000 board, but I am stuck with how to integrate optee to a linux image that can be boot from the board. Do you have some advice on this or useful instructions on how to build and create optee image for zync 7000? Thanks!

**Comment by LIKEJMJJ** [comment]
Hello, now I have the same problem with you, and I would like to ask you how you solved it then. Could you please give me some guidance?

**Comment by LIKEJMJJ** [comment]
![T}J ICSTJ~J$DP`EEJNM7H1](https://user-images.githubusercontent.com/37587541/112435626-f377a680-8d7f-11eb-9df7-08088e6e4cc9.png)

**Comment by anubhavi2k17** [comment]
Hi @eloysu205, I am also using zync 7000 board, but I am stuck with how to integrate optee to a linux image that can be boot from the board. Do you have some advice on this or useful instructions on how to build and create optee image for zync 7000? Thanks!

**Comment by anubhavi2k17** [comment]
Hi @LIKEJMJJ , I am also using zync 7000 board, but I am stuck with how to integrate optee to a linux image that can be boot from the board. Do you have some advice on this or useful instructions on how to build and create optee image for zync 7000? Thanks!
