### ISSUE TITLE
Failed to find an available port: Address already in use

### ISSUE THREAD

**Issue by penpendandan** [OP-TEE/optee_os#3173]
hello,
team, I want to build two optee+qemu development in a computer, I have change the ports of secure and normal in qemu_v8.mk. However, it is failed to find an available port. The log is as follows.
`cd /home/zouchengshuai/OP-TEE/build/../out/bin && /home/zouchengshuai/OP-TEE/build/../qemu/aarch64-softmmu/qemu-system-aarch64 \
        -nographic \
        -serial tcp:localhost:55322 -serial tcp:localhost:55323 \
        -smp 2 \
        -s -S -machine virt,secure=on -cpu cortex-a57 \
        -d unimp -semihosting-config enable,target=native \
        -m 1057 \
        -bios bl1.bin \
        -initrd rootfs.cpio.gz \
        -kernel Image -no-acpi \
        -append 'console=ttyAMA0,38400 keep_bootcon root=/dev/vda2' \
        -fsdev local,id=fsdev0,path=/home/zouchengshuai/OP-TEE/build/..,security_model=none -device virtio-9p-device,fsdev=fsdev0,mount_tag=host -netdev user,id=vmnic -device virtio-net-device,netdev=vmnic
QEMU 3.0.93 monitor - type 'help' for more information
(qemu) qemu-system-aarch64: -s: Failed to find an available port: Address already in use
make[1]: *** [run-only] Error 1
make[1]: Leaving directory `/home/zouchengshuai/OP-TEE/build'
make: *** [run] Error 2
`
Thanks!

**Comment by jbech-linaro** [comment]
You need to change ports here

https://github.com/OP-TEE/build/blob/master/qemu_v8.mk#L166-L171

in one of your two instances if you want to run them simultaneous.

**Comment by penpendandan** [comment]
yeah, I have changed it in all palace. The changed contents in qemu_v8.xml is as follows:
` run-only:
     ln -sf $(ROOT)/out-br/images/rootfs.cpio.gz $(BINARIES_PATH)/
    $(call check-terminal)
    $(call run-help)
    $(call launch-terminal,55322,"Normal World")
    $(call launch-terminal,55323,"Secure World")
    $(call wait-for-ports,55322,55323)
 cd $(BINARIES_PATH) && $(QEMU_PATH)/aarch64-softmmu/qemu-system-aarch64 \
        -nographic \
        -serial tcp:localhost:55322 -serial tcp:localhost:55323 \
        -smp $(QEMU_SMP) \
        -s -S -machine virt,secure=on -cpu cortex-a57 \
      -d unimp -semihosting-config enable,target=native \
        -m 1057 \
         -bios bl1.bin \
         -initrd rootfs.cpio.gz \
        -kernel Image -no-acpi \
       -append 'console=ttyAMA0,38400 keep_bootcon root=/dev/vda2' \
         $(QEMU_EXTRA_ARGS)
`

**Comment by jbech-linaro** [comment]
Then I have no idea what could go wrong. Maybe stale soc_term processes?

**Comment by vchong** [comment]
@penpendandan Did you manage to resolve your issue? I'd the same problem and nothing seemed to help, but it just sort of went away a couple of days later.

**Comment by penpendandan** [comment]
Hello,
I don't solve this problem. Did you just modify the ports of normal world and secure world? Does it run well now?





At 2019-08-11 22:50:01, "vchong" <notifications@github.com> wrote:


@penpendandan Did you manage to resolve your issue? I'd the same problem and nothing seemed to help, but it just sort of went away a couple of days later.

**Comment by jforissier** [comment]
`-s` binds port 1234 for `gdb`, you can't run two instances with `-s`.

**Comment by penpendandan** [comment]
Do you modify it in qemu_v8.xml？？






At 2019-08-11 22:56:41, "Jérôme Forissier" <notifications@github.com> wrote:


-s binds port 1234 for gdb, you can't run two instances with -s.

**Comment by vchong** [comment]
> Did you just modify the ports of normal world and secure world? Does it run well now?

Modifying the terminal ports didn't work for me either. It runs well now with no changes. But I was using a shared machine and with only a single Qemu instance. I guess per @jforissier's comments above someone else was using Qemu with `-s` on the machine at the same time as I was. For your case maybe you can try removing `-s` in `qemu_v8.mk` in addition to also changing the terminal ports.

**Comment by penpendandan** [comment]
ok，thanks！




At 2019-08-11 23:12:48, "vchong" <notifications@github.com> wrote:


Did you just modify the ports of normal world and secure world? Does it run well now?

Modifying the terminal ports didn't work for me either. It runs well now with no changes. But I was using a shared machine and with only a single Qemu instance. I guess per @jforissier's comments above someone else was using Qemu with -s on the machine at the same time as I was. For your case maybe you can try removing -s in qemu_v8.mk in addition to also changing the terminal ports.

**Comment by michelangeloagorini** [comment]
Same problem here. I've changed normal world and secure world ports in qemu.mk, but i'm still unable to run the second instance. Has someone solved it?

**Comment by vchong** [comment]
Try killing any previous qemu processes if they're still running, including all the gnome-terminal or xterm sessions.

**Comment by michelangeloagorini** [comment]
> Try killing any previous qemu processes if they're still running, including all the gnome-terminal or xterm sessions.

thanks for the quick reply. Unfortunately this doesn't fix my problem. 
"qemu-system-arm: -s: Failed to find an available port: Address already in use" when i run the second instance. Any other suggestions?

**Comment by jenswi-linaro** [comment]
I suppose @vchong missed the "second instance" part. If  you need to run multiple instance of qemu you must make sure to use different ports, or none at all, for gdb to connect to. Check the manual page for the `-s` option.

**Comment by michelangeloagorini** [comment]
> I suppose @vchong missed the "second instance" part. If you need to run multiple instance of qemu you must make sure to use different ports, or none at all, for gdb to connect to. Check the manual page for the `-s` option.

You were right. After removing "-s" option in qemu.mk, i am able to run the second instance. thank you!

**Comment by osman880** [comment]
> 
> 
> `-s` binds port 1234 for `gdb`, you can't run two instances with `-s`.

It works, thankss

**Comment by StephenRKraemer** [comment]
> hello, team, I want to build two optee+qemu development in a computer, I have change the ports of secure and normal in qemu_v8.mk. However, it is failed to find an available port. The log is as follows. `cd /home/zouchengshuai/OP-TEE/build/../out/bin && /home/zouchengshuai/OP-TEE/build/../qemu/aarch64-softmmu/qemu-system-aarch64 \ -nographic \ -serial tcp:localhost:55322 -serial tcp:localhost:55323 \ -smp 2 \ -s -S -machine virt,secure=on -cpu cortex-a57 \ -d unimp -semihosting-config enable,target=native \ -m 1057 \ -bios bl1.bin \ -initrd rootfs.cpio.gz \ -kernel Image -no-acpi \ -append 'console=ttyAMA0,38400 keep_bootcon root=/dev/vda2' \ -fsdev local,id=fsdev0,path=/home/zouchengshuai/OP-TEE/build/..,security_model=none -device virtio-9p-device,fsdev=fsdev0,mount_tag=host -netdev user,id=vmnic -device virtio-net-device,netdev=vmnic QEMU 3.0.93 monitor - type 'help' for more information (qemu) qemu-system-aarch64: -s: Failed to find an available port: Address already in use make[1]: *** [run-only] Error 1 make[1]: Leaving directory `/home/zouchengshuai/OP-TEE/build' make: *** [run] Error 2 ` Thanks!

I switched the network from "Shared" to "Bridged" and this seems to help.

**Comment by YogzZ** [comment]
You can start the first Qemu console with the default configuration. Then modify the following configuration for the second Qemu console:
```diff
diff --git a/qemu_v8.mk b/qemu_v8.mk
index f9aa590..131b362 100644
--- a/qemu_v8.mk
+++ b/qemu_v8.mk
@@ -428,14 +428,14 @@ run-only:
        ln -sf $(ROOT)/out-br/images/rootfs.cpio.gz $(BINARIES_PATH)/
        $(call check-terminal)
        $(call run-help)
-       $(call launch-terminal,54320,"Normal World")
-       $(call launch-terminal,54321,"Secure World")
-       $(call wait-for-ports,54320,54321)
+       $(call launch-terminal,54330,"Normal World")
+       $(call launch-terminal,54331,"Secure World")
+       $(call wait-for-ports,54330,54331)
        cd $(BINARIES_PATH) && $(QEMU_BUILD)/aarch64-softmmu/qemu-system-aarch64 \
                -nographic \
-               -serial tcp:localhost:54320 -serial tcp:localhost:54321 \
+               -serial tcp:localhost:54330 -serial tcp:localhost:54331 \
                -smp $(QEMU_SMP) \
-               -s -S -machine virt,secure=on,mte=$(QEMU_MTE),gic-version=$(QEMU_GIC_VERSION),virtualization=$(QEMU_VIRT) \
+               -gdb tcp::54333 -S -machine virt,secure=on,mte=$(QEMU_MTE),gic-version=$(QEMU_GIC_VERSION),virtualization=$(QEMU_VIRT) \
                -cpu $(QEMU_CPU) \
                -d unimp -semihosting-config enable=on,target=native \
                -m $(QEMU_MEM) \

```

The point is to change three port numbers: `Normal World`, `Secure World`, `GDB`.
