### ISSUE TITLE
IMA in secure world

### ISSUE THREAD

**Issue by vivinamartins16** [OP-TEE/optee_os#3175]
Hey all!

Does anyone have any information if it is possible to have IMA inside secure world?

When I setup IMA in the kconfigs, I can see it being loaded in the normal world. Since the secure world has another OS, can I use IMA only inside of it?

IMA gives a HUGE overhead but since the only part that matters to my use case is the secure world, I can reduce the overhead by using IMA only in the secure OS.

Does OP-TEE provide any support to this?

Thanks in advance!

**Comment by jbech-linaro** [comment]
> Hey all!
> 
> Does anyone have any information if it is possible to have IMA inside secure world?

Possible yes, but as you've already figure out we haven't got anything in the upstream tree. I'm aware of one big SoC vendor who have implemented it with OP-TEE (but haven't upstreamed it for whatever reason).

> When I setup IMA in the kconfigs, I can see it being loaded in the normal world. Since the secure world has another OS, can I use IMA only inside of it?
> 

We have discussed this in the past and from my understanding of IMA it has typically been used in conjunction with a TPM. So as I see it there are two viable approaches to use IMA with a TEE. Either you add TPM functionality in the TEE. With that it "should" be seamless to use IMA. The other way would be rewrite the IMA framework/driver so they can use a TEE directly. With that approach one could fully ignore TPM and just add the necessary functionality in TA for example. From Linaro point of view it looks like there is vague interest in IMA, so I don't believe we will see any work coming from Linaro regarding this (at least not in the close future).

> IMA gives a HUGE overhead but since the only part that matters to my use case is the secure world, I can reduce the overhead by using IMA only in the secure OS.
> 
> Does OP-TEE provide any support to this?
> 

Short answer, no!

**Comment by vivinamartins16** [comment]
> Possible yes, but as you've already figure out we haven't got anything in the upstream tree. I'm aware of one big SoC vendor who have implemented it with OP-TEE (but haven't upstreamed it for whatever reason).

Oh, I see. Thanks!


> We have discussed this in the past and from my understanding of IMA it has typically been used in conjunction with a TPM. So as I see it there are two viable approaches to use IMA with a TEE. Either you add TPM functionality in the TEE. With that it "should" be seamless to use IMA. The other way would be rewrite the IMA framework/driver so they can use a TEE directly. With that approach one could fully ignore TPM and just add the necessary functionality in TA for example. From Linaro point of view it looks like there is vague interest in IMA, so I don't believe we will see any work coming from Linaro regarding this (at least not in the close future).

Yes, I was considering your first option. But found it not so viable given the overhead of the measurements in normal world.  Maybe the second approach but I'm not sure yet, I'll give it some more thoughts.
Thanks for the detailed explanation :-)
