### ISSUE TITLE
Card reader module documentation

### ISSUE THREAD

**Issue by alekarasma** [OP-TEE/optee_os#3176]
Hello Team,

I was going through optee os. When I found the folder **passthru_reader** under **optee-os/core/tee**.

I have two questions about it.
1. Do we have any documentation of the implementation?
2. Why it has been developed under os/core/tee and not core/drivers, As I guess it is some kind of card driver. basically, I would like to know the significance of implementing it under os/core/tee.

As I read https://optee.readthedocs.io/architecture/file_structure.html?
![image](https://user-images.githubusercontent.com/42671939/62444733-ace7c980-b7a1-11e9-91d4-cac24b40f712.png)

Didnt understand much, Generic Tee files. Could someone please elaborate?

Thanks,
Asma

**Comment by jbech-linaro** [comment]
Hi,

That is an old feature (GP Secure Element) that never really was used by anyone, so after being there for years unused, we decided to get rid of it (see commit e147a447ccc06a6eca7caeddae22dec06c168d19). 

> 1. Do we have any documentation of the implementation?

If you go one commit before the one above, you'll find the docs at `documentation/se_api_design.md`.

> 2\. Why it has been developed under os/core/tee and not core/drivers, As I guess it is some kind of card driver. basically, I would like to know the significance of implementing it under os/core/tee.

This is one of the first thing being added to the TEE back in ~2014-2015. `core/drivers` would probably be more appropriate at least for parts of the implementation.

> Didnt understand much, Generic Tee files. Could someone please elaborate?

These are generic files part of the TEE core functionality.

**Comment by alekarasma** [comment]
Thanks @jbech-linaro .
So if I understand it correctly. Implementation of my driver under OS/core/tee/ rather than core/drivers/ wont make any difference.
