### ISSUE TITLE
How to link shared libraries to TA?

### ISSUE THREAD

**Issue by Ashwinfosec** [OP-TEE/optee_os#3178]
How do I link shared libraries to any Trusted Application? 

Specifically I want to include the library "libasound.so" to my TA. I tried the solutions recommended https://optee.readthedocs.io/faq/faq.html#q-how-do-i-link-a-library-into-a-trusted-application here in Question related to the same - How do I link a library into a Trusted Application?

**Comment by jforissier** [comment]
You can't. `libasound.a` depends on services (system calls) from the Linux OS, whereas TAs run on top of the OP-TEE OS. Two different worlds really (no pun intended!).

**Comment by Ashwinfosec** [comment]
Oh yes that's right! I'm sorry. Thanks for your prompt response though :)
