### ISSUE TITLE
An  Undefined TEEC_Result

### ISSUE THREAD

**Issue by tulipper** [OP-TEE/optee_os#3179]
Hello there
I added a new command in the TA, but when I invoke it the the CA through the corresponding commandID, the returned the TEEC_Result is 0xffff3024, and the ReturnOrigin=0x3. I look up the GlobalPlatform Device Technology TEE Client API Specification, there has no such a TEEC_Result.
My platform is hikye960, and I use the AOSP+OPTEE [1]
Here is the output from the optee os:
                       
`D/TC:? 0 tee_ta_init_pseudo_ta_session:276 Lookup pseudo TA 34b1c7a2-45f7-11e9-3
D/TC:? 0 load_elf:827 Lookup user TA ELF 34b1c7a2-45f7-11e9-b210-d663bd873d93 ()
D/TC:? 0 load_elf:827 Lookup user TA ELF 34b1c7a2-45f7-11e9-b210-d663bd873d93 ()
D/TC:? 0 load_elf:827 Lookup user TA ELF 34b1c7a2-45f7-11e9-b210-d663bd873d93 ()
D/TC:? 0 load_elf_from_store:795 ELF load address 0x40015000                    
D/TC:? 0 tee_ta_init_user_ta_session:1017 Processing relocations in 34b1c7a2-453
D/TC:6 0 abort_handler:618 [abort] abort in User mode (TA will panic)           
E/TC:6 0                                                                        
E/TC:6 0 User TA data-abort at address 0x40015000 (write permission fault)      
E/TC:6 0  esr 0x9200004f  ttbr0 0x600003f0ba0c0   ttbr1 0x00000000   cidr 0x0   
E/TC:6 0  cpu #6          cpsr 0x80000100                                       
E/TC:6 0  x0  00000000400146c0 x1  0000000040013490                             
E/TC:6 0  x2  0000000000000040 x3  0000000000000900                             
E/TC:6 0  x4  0000000040013d90 x5  0000000040014fc0                             
E/TC:6 0  x6  0000000000001200 x7  0000000000000000                             
E/TC:6 0  x8  0000000000000000 x9  0000000000000166                             
E/TC:6 0  x10 000000004001858c x11 000000003f04dc64                             
E/TC:6 0  x12 0000000000000000 x13 0000000040014780                             
E/TC:6 0  x14 0000000000000000 x15 0000000000000000                             
E/TC:6 0  x16 000000003f0c20d8 x17 0000000000000000                             
E/TC:6 0  x18 0000000000000000 x19 0000000040013490                             
E/TC:6 0  x20 00000000400146c0 x21 00000000400146d0                             
E/TC:6 0  x22 00000000400146c0 x23 000000000000000a                             
E/TC:6 0  x24 000000003f099940 x25 000000003f0986a0                             
E/TC:6 0  x26 000000003f0c2330 x27 000000000000000a                             
E/TC:6 0  x28 0000000040014788 x29 0000000040013450                             
E/TC:6 0  x30 0000000040015858 elr 00000000400155c0                             
E/TC:6 0  sp_el0 0000000040013450                                               
E/TC:6 0 Status of TA 34b1c7a2-45f7-11e9-b210-d663bd873d93 (0x3f0988c0) (active)
E/TC:6 0  arch: aarch64  load address: 0x40015000 ctx-idr: 6                    
E/TC:6 0  stack: 0x40004000 67584                                               
E/TC:6 0  region 0: va 0x40000000 pa 0x3f000000 size 0x2000 flags ---R-X        
E/TC:6 0  region 1: va 0x40002000 pa 0x3f09c000 size 0x1000 flags ---RW-        
E/TC:6 0  region 2: va 0x40004000 pa 0x3f2d0000 size 0x11000 flags rw-RW-       
E/TC:6 0  region 3: va 0x40015000 pa 0x3f27f000 size 0xe000 flags r-x--- [0]    
E/TC:6 0  region 4: va 0x40023000 pa 0x3f28d000 size 0x43000 flags rw---- [0]   
E/TC:6 0  region 5: va 0x40067000 pa 0x3ee01000 size 0x1000 flags rw-RW-        
E/TC:6 0  [0] 34b1c7a2-45f7-11e9-b210-d663bd873d93 @ 0x40015000                 
E/TC:6 0 Call stack:                                                            
E/TC:6 0  0x00000000400155c0                                                    
E/TC:6 0  0x00000000400153cc                                                    
E/TC:6 0  0x0000000040015774                                                    
E/TC:6 0  0xfffffffffffffffc                                                    
D/TC:? 0 user_ta_enter:315 tee_user_ta_enter: TA panicked with code 0xdeadbeef  
D/TC:? 0 tee_ta_invoke_command:625 Error: ffff3024 of 3                         
D/TC:? 0 tee_ta_close_session:380 tee_ta_close_session(0x3f099940)              
D/TC:? 0 tee_ta_close_session:399 Destroy session                               
D/TC:? 0 tee_ta_close_session:425 Destroy TA ctx                                

`
Could someone tell how this error comes and how to fix this?
Anything is appreciated! Thanks in advance.

[1][https://github.com/linaro-swg/optee_android_manifest](url)

**Comment by jforissier** [comment]
Hi @tulipper ,

Your TA has crashed, the code is defined [here](https://github.com/OP-TEE/optee_client/blob/16e5304f92691221613dbc88b0baa91245d073c5/public/tee_client_api.h#L187).
You may use [symbolize.py](https://optee.readthedocs.io/debug/abort_dumps.html) to help debugging.
