### ISSUE TITLE
Optee TA  Log how to see?(CFG_TEE_TA_LOG_LEVEL ?= 4)

### ISSUE THREAD

**Issue by fengleichn** [OP-TEE/optee_os#3180]
HI team, 

I test optee on Hikey960+AOSP.
I add " CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)"  in Makefile

I can see some OP-TEE log use UART.
such as 

but  I can not see TA log in UART
I add log  such as :
"DMSG("TA_DestroyEntryPoint");"
DMSG("TA_OpenSessionEntryPoint \n");

but I can not see it witch  TA is added

can you help to solve this problem?

**Comment by fengleichn** [comment]
add " CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)" in  TA Makefile

**Comment by Emantor** [comment]
You probably want to set `CFG_TEE_CORE_LOG_LEVEL`, which enables logging for the OP-TEE core kernel.

**Comment by fengleichn** [comment]
TEE log is this:

`D/TC:? 0 load_elf:827 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:? 0 load_elf:827 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:? 0 load_elf_from_store:795 ELF load address 0x40005000
D/TC:? 0 tee_ta_init_user_ta_session:1017 Processing relocations in 8aaaf200-2450-11e4-abe2-0002a5d5c51b
D/TC:? 0 tee_ta_close_session:380 tee_ta_close_session(0x3f099550)
D/TC:? 0 tee_ta_close_session:399 Destroy session
D/TC:? 0 tee_ta_close_session:425 Destroy TA ctx`

**Comment by vchong** [comment]
For AOSP, do it in `device/linaro/hikey/optee-packages.mk`.
Something like this:
```
diff --git a/optee-packages.mk b/optee-packages.mk
index e204f66e..ea2d87f1 100644
--- a/optee-packages.mk
+++ b/optee-packages.mk
@@ -3,6 +3,7 @@ OPTEE_PLATFORM_FLAVOR ?= $(TARGET_DEVICE)
 OPTEE_CFG_ARM64_CORE ?= y
 OPTEE_TA_TARGETS ?= ta_arm64
 OPTEE_OS_DIR ?= optee/optee_os
+OPTEE_EXTRA_FLAGS ?= CFG_TEE_CORE_LOG_LEVEL=3 CFG_TEE_TA_LOG_LEVEL=3
 BUILD_OPTEE_MK := $(OPTEE_OS_DIR)/mk/aosp_optee.mk
 
 # OP TEE client library and service
```

**Comment by fengleichn** [comment]
Thinks for you help
