### ISSUE TITLE
Dropped version info from TA binaries

### ISSUE THREAD

**Issue by etienne-lms** [OP-TEE/optee_os#3192]
Me to blame...
While reviewing https://github.com/OP-TEE/optee_os/pull/2832, I suggested to remove argument `--version` from script `sign.mk` (I falsely though it was introduced by the P-R, my fault. This popped to my mind while looking at https://github.com/OP-TEE/optee_os/pull/3191).

Actually this version info was useful in that it tagged TA binaries with a versioning information used when loading TAs in the secure storage, preventing rollback install of older version of the TA, see [check_install_conflict()](https://github.com/OP-TEE/optee_os/blob/3.6.0/core/arch/arm/pta/secstor_ta_mgmt.c#L32-L34)).

Below a test with 2 binaries of TA **os_test** from **optee_test** versioned 0 and 1:
```bash
$ xtest --install-ta /lib/optee_armtz/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.ta-version_is_0
Installing "/lib/optee_armtz/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.ta-version_is_0"
Installing TAs done
$ xtest --install-ta /lib/optee_armtz/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.ta-version_is_1
Installing "/lib/optee_armtz/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.ta-version_is_1"
Installing TAs done
$ xtest --install-ta /lib/optee_armtz/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.ta-version_is_0
Installing "/lib/optee_armtz/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.ta-version_is_0"
xtest: install_ta: TEEC_InvokeCommand: 0xffff0003 err_origin 0x4
$ 
```

Would you be ok we restore this feature in `sign.py`?

By the way, I wonder if we should also change core to allow only strict version increase:
```patch
--- a/core/arch/arm/pta/secstor_ta_mgmt.c
+++ b/core/arch/arm/pta/secstor_ta_mgmt.c
@@ -30,7 +30,7 @@ static TEE_Result check_install_conflict(const struct shdr_bootstrap_ta *bs_ta)
 		return res;
 
 	prop = tee_tadb_ta_get_property(ta);
-	if (prop->version > bs_ta->version)
+	if (prop->version >= bs_ta->version)
 		res = TEE_ERROR_ACCESS_CONFLICT;
 
 	tee_tadb_ta_close(ta);
```

**Comment by jenswi-linaro** [comment]
Good catch @etienne-lms, we should bring back the version argument and also document its purpose a bit more.

I'm not so sure about strict version increase though, it will make development a bit of a mess while still not providing significant increase in security. It's still up the one signing the TAs to decide which version number is used for signing.

**Comment by jforissier** [comment]
> Good catch @etienne-lms, we should bring back the version argument and also document its purpose a bit more.

+1, the reason why removing it passed the review step is clearly because its purpose was misunderstood (to me at least -- I thought it was the version number for the format of the header).

**Comment by etienne-lms** [comment]
ok, i'll push something...

**Comment by wamserma** [comment]
> Good catch @etienne-lms, we should bring back the version argument and also document its purpose a bit more.

Yes, this definitely needs better documentation. I dropped it from the script at @etienne-lms suggestion as it seemed to be unused in OP-TEE..

Regarding the strict version increase: Keep this to a separate PR and consider teh case of reinstalling an unmodified TA. This might trigger an error unless some extra code is added to do binary comparison upon version match.

**Comment by wamserma** [comment]
> ok, i'll push something...
> **(edited: #3194)**

Ok, so this is probably closed by https://github.com/OP-TEE/optee_os/pull/3194

**Comment by etienne-lms** [comment]
yes, I think it is. I close the issue.
