### ISSUE TITLE
Ftrace feature enhancements

### ISSUE THREAD

**Issue by b49020** [OP-TEE/optee_os#3202]
Just creating a placeholder issue to have discussions regarding further `ftrace` feature enhancements.

**Comment by b49020** [comment]
Continue discussion from here: https://github.com/OP-TEE/optee_os/pull/3181#issuecomment-521176552

@jforissier 
> Yes, or any reason why the TA is put to sleep in NW (taking a mutex, waiting for tee-supplicant...)

Ok I see. But wouldn't that provide useful info to user that a particular syscall is taking long time that needs to be looked into. If its `TEE_Wait` syscall then user is already aware of expected sleep time.

**Comment by ghost11235** [comment]
@b49020 
The developer should be aware of the ```TEE_wait``` but would still need to take it into account for the overall performance timing and it would be easier to trace/account for if it was captured with all the syscalls. If possible it could be a separate CFG to enabled or disabled ```TEE_wait``` for ```_mcount``` capture.

**Comment by ghost11235** [comment]
A feature that would be nice to have is the ability to change when ```ftrace``` sends the ```RPC/ftrace.out``` file. This would make a single trace to be across multiple ```.out``` files that then would be merged into one file. Maybe have it on TA session return/Destroy session. I know i am having to increase the buffer to sizes above 5 times the default to get a full trace. There is going to be a point, especially in constrained systems, where you may not have any more memory to give the  ```CFG_FTRACE_BUF_SIZE``` and it will just overwrite what is there.

**Comment by b49020** [comment]
@ghost11235 
> The developer should be aware of the TEE_wait but would still need to take it into account for the overall performance timing and it would be easier to trace/account for if it was captured with all the syscalls.

Yeah I mean to say to capture time spent for every syscall in the `ftrace` graph. BTW, thanks for your input.

> Maybe have it on TA session return/Destroy session.

Its already done per session basis. You would have a new `.out` file for every session (open/close).

**Comment by ghost11235** [comment]
@b49020 
 I may be missing something in my understanding or in my build.

> Its already done per session basis. You would have a new `.out` file for every session (open/close).

Currently for my build i believe it is only returning a ```.out``` on ```destroy_context Destroy TA ctx``` to the normal world. So i am only seeing the file/data being sent to the supplicant when the CA/TA is finished running. 
On big TA's this requires a really big ```CFG_FTRACE_BUF_SIZE``` as the buffer must hold all the trace data till the end. Internally ```ftrace``` may be logging the data to the buffer on a session basis but will get overwritten and losse the beginning of the trace if the buffer is not large enough; as it is not being flushed/sent to the normal world by rpc.

Specifically i would like to see the data sent to the normal world on``` tee_ta_close_session:516 Destroy session```. This would allow ```CFG_FTRACE_BUF_SIZE``` to overall be smaller and only need to be the size of the largest session. This means that 1 trace would have a file for every CA TA function call or TA session. After the TA completes, ```ctx``` has been issued and final data has been sent to the supplicant it then could concatenate them together into one file.

Also i did notice i have to run at least one TA once before any of the following TA's will be traced.

**Comment by b49020** [comment]
@ghost11235 
> I may be missing something in my understanding or in my build.

Have a look at `destroy_session` API here: https://github.com/OP-TEE/optee_os/blob/c3d61baa2e324dab3d3de3650020e1d932e59b85/core/kernel/tee_ta_manager.c#L277

> So i am only seeing the file/data being sent to the supplicant when the CA/TA is finished running.

It may be possible that your CA opens a single session with TA.

> Also i did notice i have to run at least one TA once before any of the following TA's will be traced.

Can you elaborate this issue with an example?

**Comment by ghost11235** [comment]
@b49020 

> It may be possible that your CA opens a single session with TA.

You are correct the CA only opens a single session. So i what i would be looking for at least from a CA side would be the possibility to configure ```ftrace``` to write/rpc the trace information when the TA returns the  ```TEE_Result``` or on ```destroy_session```.  For this test TA/CA(basically ```optee_example_acipher```) i can modify it for testing purposes to open an close a session for every ```TEEC_InvokeCommand``` to make the ```CFG_FTRACE_BUF_SIZE``` smaller. However this may not be possible on actual TA/CA.

There is also the other added complexity of TA to TA communication. Where there is a CA->TA->TA trace that may occur. This may require instrumentation and initialization from ```TEE_OpenTASession``` which may already be captured by the ```tee_ta_manager``` instrumentation. But i am unsure of this as of now.

Thanks

**Comment by b49020** [comment]
@ghost11235 

> So i what i would be looking for at least from a CA side would be the possibility to configure ftrace to write/rpc the trace information when the TA returns the TEE_Result or on destroy_session.

Are you looking for `.out` file for every `TEEC_InvokeCommand`? I think that would be an overkill for tracing framework. Can you share size constraints for your platform?

- Limited non-secure shared memory?
- Limited TA secure memory? As ftrace buffer (size: `CFG_FTRACE_BUF_SIZE`) is allocated from TA `.bss` section, so size of TA shouldn't be a problem here.

> There is also the other added complexity of TA to TA communication. Where there is a CA->TA->TA trace that may occur. This may require instrumentation and initialization from TEE_OpenTASession which may already be captured by the tee_ta_manager instrumentation. But i am unsure of this as of now.

You should get a similar `ftrace-<uuid>.out` file for a session opened via internal TA client interface.

**Comment by ghost11235** [comment]
@b49020 

> Are you looking for `.out` file for every `TEEC_InvokeCommand`?

Yes, i would like the option to switch between having the ```.out``` generated on every ```TEEC_InvokeCommand``` or on the session which is currently how it is done now.

> Can you share size constraints for your platform?

I can not give specifics other than in some of our cases the constrained system may only have ~4-8KB (usually less) in either shared or secure memory free. So if we have 4 TAs running together each one may only be able to have 2KB of space for the trace. Just on the one TA trace with 4 functions in one session it required over 8KB of space to collect the entire trace.
We will still also need to take into account space needed for system tracing once it is added.

**Comment by b49020** [comment]
@ghost11235 
> We will still also need to take into account space needed for system tracing once it is added.

Yeah I am currently looking at this aspect only as size of system trace seems to be quite large. I will try to add a configuration option to have `.out` for every `TEEC_InvokeCommand`.

**Comment by ghost11235** [comment]
@b49020 

Thank you for looking into this.

Will system traces be able to be enabled and disabled by their own config flag?
Similar to ```CFG_TA_FTRACE_SUPPORT``` along the lines of ```CFG_CORE_FTRACE_SUPPORT```.

With system ```ftrace``` will its depth/detail be limited with its own config flag or by ```CFG_TEE_LOG_LEVEL```?

**Comment by b49020** [comment]
@ghost11235 

Please have a look at PR: https://github.com/OP-TEE/optee_os/pull/3225.
