### ISSUE TITLE
Use of HUK

### ISSUE THREAD

**Issue by michpappas** [OP-TEE/optee_os#3204]
Hi, looking through the sources, it looks like the HUK is only used in the context of secure storage. Can you please confirm whether this is correct?

**Comment by etienne-lms** [comment]
As per 3.6.0, `tee_otp_get_hw_unique_key()` is only called by `huk_subkey_derive()` which derives keys from the HUK. `huk_subkey_derive()` is called from:
- PTA system on command `PTA_SYSTEM_DERIVE_TA_UNIQUE_KEY`. TAs can request HUK derivation, see example in https://github.com/OP-TEE/optee_test/blob/3.6.0/ta/crypt/derive_key_taf.c#L21. 
- `tee_rpmb_key_gen()` to generate a RPMB key
- `tee_fs_init_key_manager()` to generate the key used to secure the REE_FS content.

**Comment by michpappas** [comment]
Thanks for confirming
