### ISSUE TITLE
scripts/pem_to_pub.py uses Python2 on Debian

### ISSUE THREAD

**Issue by broonie** [OP-TEE/optee_os#3213]
Attempting to build OP-TEE on current releases of Debian fails as scripts/pem_to_pub.py fails to find the crypto library. Unfortunately the script uses '/usr/bin/env python' which is Python 2 but Debian has deprecated this so there is no Python 2 package for the library. Since other bits of the build seem to assume Python 3 it looks like the simplest fix would be to change the script to use Python 3.

**Comment by broonie** [comment]
A similar issue appears to exist in sign.py.

**Comment by Emantor** [comment]
Related to https://github.com/OP-TEE/optee_os/pull/3187, I need to look into the `symbolize.py` script and fix that.

**Comment by jbech-linaro** [comment]
@broonie as @Emantor said, we're about to update all scripts to Python3. Until quite recent OP-TEE has been relying on Python 2.

I've been using Debian myself for a long time for OP-TEE development and my workaround so far has been to init a dummy path that symlinks to Python 2.

```bash
export PATH=$HOME/devel/init:$PATH
```

Where `$HOME/devel/init` contains:
```bash
$ ls -l
total 0
lrwxrwxrwx 1 jbech jbech 16 Jan 24  2018 python -> /usr/bin/python2
```

But, I hope that the transition from Python 2 to Python 3 will be completed soon so we can avoid hacks like this.

**Comment by broonie** [comment]
I just applied local patches changing the offending scripts to use python3 in the #! which *seems* fine (though I can't actually get an OP-TEE binary that does anything other than fail silently when executed on my systems so perhaps not).

**Comment by Emantor** [comment]
#3187 should have fixed that.

**Comment by broonie** [comment]
The comment from github-actions says I can remove the stable label it's applied but I'm not seeing any UI for that :(

**Comment by Emantor** [comment]
Since #3187 has been merged, `pem_to_pub.c` uses python3 on current master. IMO this issue can be closed.

**Comment by jbech-linaro** [comment]
> The comment from github-actions says I can remove the stable label it's applied but I'm not seeing any UI for that :(

"_... or add a comment saying that you would like to have the label removed_ ". It's only admins who can remove the label. But as @Emantor says, issue has been resolved, to this could be closed, agree?

**Comment by broonie** [comment]
It looks like it AFAICT, not clear why this didn't get closed with the comment when the fix was done. I would recommend changing the notice the bot puts in to make sure that people know they might not have permission to clear the label.

**Comment by jbech-linaro** [comment]
> It looks like it AFAICT, not clear why this didn't get closed with the comment when the fix was done.

Ideally the one fixing the issue adds a "Fixes #nbr" in the commit message and then it'll be closed automatically. If that isn't done, then it becomes a shared responsibility between maintainer, patch submitter and issue reporter to close it. In the beginning of the project, we as maintainers could keep track of things like that on our own, but nowadays there is too much happening, so maintainers cannot keep track of it all, which is one of the reasons why we enabled the bot. I.e., it's helps us bring attention to important things and cleaning up in general. There are a few more comments and justifications in the commit that introduced this (https://github.com/OP-TEE/optee_os/commit/8e08d8e1a901493a290be76adc452f7abd597854). I'm closing it now.

> I would recommend changing the notice the bot puts in to make sure that people know they might not have permission to clear the label.

I think the bot message is pretty clear, either you find out that you can remove the label on your own ... or you add a comment asking for it to be removed, simple as that.

**Comment by broonie** [comment]
On Mon, Jan 13, 2020 at 04:29:41AM -0800, Joakim Bech wrote:

> > I would recommend changing the notice the bot puts in to make sure that people know they might not have permission to clear the label.

> I think the bot message is pretty clear, either you find out that you can remove the label on your own ... or you add a comment asking for it to be removed, simple as that.

The problem is the time spent determining if the reason you can't
remove the label on your own is bad UX in github or if it's just
something you can't do at all.

**Comment by jbech-linaro** [comment]
Got it, would you mind do me a favor and update the bot text so it makes sense to you (and others)? It's here where one would need to make the changes:
* https://github.com/OP-TEE/optee_os/blob/master/.github/workflows/stale_issue.yml#L13
* https://github.com/OP-TEE/optee_os/blob/master/.github/workflows/stale_pr.yml#L13

**Comment by broonie** [comment]
On Mon, Jan 13, 2020 at 06:33:55AM -0800, Joakim Bech wrote:
> Got it, would you mind do me a favor and update the bot text so it makes sense to you (and others)? It's here where one would need to make the changes:
> * https://github.com/OP-TEE/optee_os/blob/master/.github/workflows/stale_issue.yml#L13
> * https://github.com/OP-TEE/optee_os/blob/master/.github/workflows/stale_pr.yml#L13

I'll try, I'll need to check out the process for approvals for
contributions to OP-TEE we have internaly so it may take some
time.
