### ISSUE TITLE
Platform Support

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#3217]
I have a question about the platform support provided by OPTEE. On the page for [AOSP](https://optee.readthedocs.io/building/aosp/aosp.html), I only see Hikey devices listed on top of the page. If I look at the [build](https://optee.readthedocs.io/building/gits/build.html#get-and-build-the-solution), I see a different manifest file being used. 

My question is that whether AOSP + OPTEE is only supported on Hikey boards and whether for the devices listed on the [build](https://optee.readthedocs.io/building/gits/build.html#get-and-build-the-solution) page the support provided is Linux + OPTEE ?

Thanks

**Comment by jbech-linaro** [comment]
It's only HiKey that is supported for AOSP builds. Note that there are SoC vendors who have provided OP-TEE support for AOSP on they own pages (NXP is one of them), so if you have a certain device I'd check the device vendors page also.

The things mentioned at build.git are used to build "OP-TEE developer setup's". Those are plain Linux builds with a stripped down setup aiming to be able to successfully run xtest.
