### ISSUE TITLE
How to crypto a file of REE using functions of TEE?

### ISSUE THREAD

**Issue by lcs100** [OP-TEE/optee_os#3220]
Hello everybody.
I renctly work on optee and try to protect some files using optee.
These files means some important files in app.
So is there anyway to protect these files?

**Comment by jforissier** [comment]
Hi @lcs100,

You can find encryption examples in the `optee_examples` repository.

**Comment by lcs100** [comment]
thanks @jforissier 
It seems that TEE cannot access directly files of REE.The only way to encrypt is pass the file content as an argument to TEE.

**Comment by jforissier** [comment]
Correct.
