### ISSUE TITLE
ECDSA verify signture failed.

### ISSUE THREAD

**Issue by yeban207** [OP-TEE/optee_os#3227]
hi, 
I'm using ECDSA for key generation, signature and signature verification.
1. The key generate is SUCCESS， with params p, x, y.
2. then I sign the msg (sha256) successfully with params p, x, y and TEE_ECC_CURVE_NIST_P256
3. I verify the sigture failed with params  x, y, curve, the return codes is 0xffff3072 (TEE_ERROR_SIGNATURE_INVALID).
 And the log shows:
TEE-CORE: der_decode_sequence_multi failed
[0x0] TEE-CORE:ecc_verify:1932: ecc_verify ltc_res 0x7, ltc_stat 0x0.

Could you help me? or provide a demo ECDSA key generate，sign， verify signture, thanks!

**Comment by jforissier** [comment]
Hi @yeban207,

Perhaps I am missing something, but I am surprised that `der_decode_sequence_multi()` is called in your test. ECC verification is supposed to be done by [`crypto_acipher_ecc_verify()`](https://github.com/OP-TEE/optee_os/blob/1f3b11151257/core/lib/libtomcrypt/ecc.c#L300) which calls [`ecc_verify_hash_raw()`](https://github.com/OP-TEE/optee_os/blob/1f3b11151257/core/lib/libtomcrypt/src/pk/ecc/ecc_verify_hash.c#L74). It is a custom function in LibTomCrypt, specific to OP-TEE, which does not apply DER decoding to the signature contrary to [`ecc_verify_hash()`](https://github.com/OP-TEE/optee_os/blob/1f3b11151257/core/lib/libtomcrypt/src/pk/ecc/ecc_verify_hash.c#L193).

Have you modified the code?

**Comment by yeban207** [comment]
hi @jforissier ,

Your are right.  Someone had modified the code, and I resume the code,  it works ok.

thanks.
