### ISSUE TITLE
Can one TA compute hash or checksum of another TA?

### ISSUE THREAD

**Issue by vivinamartins16** [OP-TEE/optee_os#3234]
Hi all!

I know that, from [this issue](https://github.com/OP-TEE/optee_os/issues/2006) TAs are isolated from one another. I also know that, before being loaded, all TAs are checked for signature and headers. 

Is it possible for one TA to compute hash or checksum of another TA?

Use case: I build sensors with my TAs. One of the TAs in the sensor is responsible for checking the integrity of all other TAs in TEE by comparing their current hash with the original, production hash. With this, I want to detect a TA which was signed and has the proper uuid but left production with the wrong code.

Thanks in advance!

**Comment by jforissier** [comment]
Hi @vivinamartins16,

> Is it possible for one TA to compute hash or checksum of another TA?

Currently, no. But one way to do it would be to implement a [PTA](https://optee.readthedocs.io/architecture/trusted_applications.html#pseudo-trusted-applications) (pseudo-TA) and use the [`user_ta_store`](https://github.com/OP-TEE/optee_os/blob/master/core/include/kernel/user_ta_store.h) interface. See for instance how TAs are open [here](https://github.com/OP-TEE/optee_os/blob/c96bced4504bd39ff8ccc57a21d29fa97aff4506/core/arch/arm/pta/system.c#L237).

**Comment by vivinamartins16** [comment]
Thank you @jforissier! I think this should solve my issue.
Just one quick question: in line 30 from user_ta_store.h I read:
> "* Return the tag or hash of the TA binary. Used to uniquely.."
How can I choose between tag or hash? How to set this?

Thank you once again!

**Comment by vivinamartins16** [comment]
Solved the tag issue. Closing now. ;)
