### ISSUE TITLE
How to retrieve last PC and stack ptr on returning from S-EL0

### ISSUE THREAD

**Issue by FulcronZ** [OP-TEE/optee_os#3238]
I'm porting Secure Partition Manager ([SPM][SPM]) from TF-A to OP-TEE.  
SPM is basically a sandbox to run a Secure Partition (SP), which basically is a bare-metal secure application, in S-EL0. 

TEE TAs have a fixed entry point to arbitrate to TEE API functions e.g. "OpenSession" and "InvokeCmd". On the other hand, SPs do not have a fixed entry point. They resume from their last PC. 

Is there a way to retrieve last PC and stack pointer on returning from S-EL0?  
So that an SP can re-entry with an updated PC and stack.  
I'm currently looking at [`thread_enter_user_mode()`][thread_enter_user_mode]

[SPM]: https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/about/docs/components/secure-partition-manager-design.rst
[thread_enter_user_mode]: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread.c#L1194

**Comment by lorc** [comment]
Hello, @FulcronZ, 

I believe, this is the generic ARM question. You can refer to chapter D.10 of ARM Architecture Reference Manual ARMv8 (DDI 0487B.a).

Basically, upon returning from EL0, PC will be stored in `ELR_EL0`. Stack pointer will be `SP_EL0`.

**Comment by FulcronZ** [comment]
Thanks for the hint @lorc. 

A TA returns to OP-TEE by using SVC system calls. An SVC call is handled by [`tee_svc_handler()`][tee_svc_handler]. The handler uses [`tee_svc_syscall_table()`][tee_svc_syscall_table] to serve. 

I will check if I could tap those registers upon returning.  

[tee_svc_handler]: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/tee/arch_svc.c#L177
[tee_svc_syscall_table]: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/tee/arch_svc.c#L48

**Comment by FulcronZ** [comment]
I think I could make use of [`struct thread_user_mode_rec`][thread_user_mode_rec].  

```c
#ifdef ARM64
struct thread_user_mode_rec {
	uint64_t exit_status0_ptr;
	uint64_t exit_status1_ptr;
	uint64_t x[31 - 19]; /* x19..x30 */
};
#endif /*ARM64*/
```

To achieve this issue, I have to: 

* On leaving to S-EL0
    * add `exit_pc_ptr` and `exit_sp_ptr` into the struct
    * add the above parameters to `__thread_enter_user_mode()`
* On returning from S-EL0
    * assign return values in `tee_svc_sys_return_helper()`
        * `regs->x3 = regs->elr;`
        * `regs->x4 = regs->sp_el0;`
    * retrieve the values in the above function in `thread_unwind_user_mode()`
    * store the values in `exit_pc_ptr` and `exit_sp_ptr` in `thread_unwind_user_mode()`

I wonder if this sounds. 

[thread_user_mode_rec]: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread_private.h#L59

**Comment by FulcronZ** [comment]
Not working on this item anymore. Close.
