### ISSUE TITLE
Write large data into secure storage

### ISSUE THREAD

**Issue by xiaxinkai** [OP-TEE/optee_os#3243]
Please help me. Thank you in advance.
I'm running optee_os 3.5 on raspberry pi 3b.
I can run [optee_examples](https://github.com/linaro-swg/optee_examples) normally.
Now I want to write 10M data to the secure storage(REE FS).
So I modified the example code [secure_storage](https://github.com/linaro-swg/optee_examples/tree/master/secure_storage).
From the normal world, I pass 512K data to secure world in 1 time, in the secure world I use TEE_WriteObjectData to write the same data 20 times to 1 file "object#1".
But I found I can only write 3 times 512K data to file "object#1", then TA panicked with code 0xffff000c. 0xffff000c means TEEC_ERROR_OUT_OF_MEMORY.
file "object#1" max size seems to be 3.2M.
Are there any limits or configs for the data size written to secure storage?

## Below is my program log:
```
@nutshell:/data/vendor/tee # optee_example_secure_storage
Prepare D/TC:? 0 tee_ta_init_pseudo_ta_session:273 Lookup pseudo TA f4e750bb-1437-4fbf-8785-8d3580c34994
session with the TA
D/TC:? 0 load_elf:842 Lookup user TA ELF f4e750bb-1437-4fbf-8785-8d3580c34994 (Secure Storage TA)
D/TC:? 0 load_elf:842 Lookup user TA ELF f4e750bb-1437-4fbf-8785-8d3580c34994 (REE)
D/TC:? 0 load_elf_from_store:810 ELF load address 0x40005000
D/TC:? 0 tee_ta_init_user_ta_session:1029 Processing relocations in f4e750bb-1437-4fbf-8785-8d3580c34994

Test on object "object#1"
- Create and load object in the TA secure storage
I/TA: TEE_CreatePersistentObject Success
I/TA: TEE_WriteObjectData Success, count: 0
I/TA: TEE_WriteObjectData Success, count: 1
I/TA: TEE_WriteObjectData Success, count: 2
E/TC:? 0
E/TC:? 0 TA panicked with code 0xffff000c
E/TC:? 0 Status of TA f4e750bb-1437-4fbf-8785-8d3580c34994 (0x1016d720) (active)
E/TC:? 0  arch: aarch64  load address: 0x40005000 ctx-idr: 2
E/TC:? 0  stack: 0x40004000 4096
E/TC:? 0  region 0: va 0x40000000 pa 0x10100000 size 0x2000 flags ---R-X
E/TC:? 0  region 1: va 0x40002000 pa 0x10170000 size 0x1000 flags ---RW-
E/TC:? 0  region 2: va 0x40004000 pa 0x10816000 size 0x1000 flags rw-RW-
E/TC:? 0  region 3: va 0x40005000 pa 0x10800000 size 0xb000 flags r-x--- [0]
E/TC:? 0  region 4: va 0x40010000 pa 0x1080b000 size 0xb000 flags rw---- [0]
E/TC:? 0  region 5: va 0x4001c000 pa 0x8001000 size 0x81000 flags rw-RW-
E/TC:? 0  [0] f4e750bb-1437-4fbf-8785-8d3580c34994 @ 0x40005000
E/TC:? 0 Call stack:
E/TC:? 0  0x0000000040007830
E/TC:? 0  0x0000000040005164
E/TC:? 0  0x0000000040007c18
E/TC:? 0  0x0000000010102d14
D/TC:? 0 unwind_stack_arm64:56 FP out of bounds 0
D/TC:? 0 user_ta_enter:312 tee_user_ta_enter: TA panicked with code 0xffff000c
D/TC:? 0 tee_ta_invoke_command:625 Error: ffff3024 of 3
Command WRITE_RAD/TC:? 0 tee_ta_close_session:380 tee_ta_close_session(0x1016d780)
W failedD/TC:? 0 tee_ta_close_session:399 Destroy session
: 0xffffD/TC:? 0 tee_ta_close_session:425 Destroy TA ctx
3024 / 3
Command WRITE_RAW failed: 0xffff3024 / 3
optee_example_secure_storage: Failed to create an object in the secure storage
1|@nutshell:/data/vendor/tee # ls -alh
total 1.7M
drwx------ 2 0 0 4.0K 1970-01-01 00:02 .
drwx------ 3 0 0 4.0K 1970-01-01 00:00 ..
-rw------- 1 0 0 4.1K 1970-01-01 00:00 0
-rw------- 1 0 0 3.2M 1970-01-01 00:02 1
-rw------- 1 0 0  16K 1970-01-01 00:02 dirf.db
```

**Comment by jenswi-linaro** [comment]
The amount of memory available in the heap is the main limitation for how large a secure object can be handled in secure storage. The code maintaining the Merkle tree could be optimized to only have the current needed nodes in memory and free the rest, that would allow much larger files. But you may very well run into some other limits also. Secure storage is primarily designed to hold small objects like keys, hashes and counters.

**Comment by xiaxinkai** [comment]
@jenswi-linaro thank you for your answer.
>Secure storage is primarily designed to hold small objects like keys, hashes and counters.
I think the direction of what I'm working on may be wrong. I will change my direction.
I close the issue.

**Comment by xiaxinkai** [comment]
@jenswi-linaro Thank you for your answer.
>The amount of memory available in the heap is the main limitation for how large a secure object can be handled in secure storage.

To increase the heap size, what value should I increase? 
CFG_CORE_HEAP_SIZE? or TA_DATA_SIZE?

**Comment by jenswi-linaro** [comment]
`CFG_CORE_HEAP_SIZE`

**Comment by xiaxinkai** [comment]
@jenswi-linaro Thank you for you answer.

I have modified CFG_CORE_HEAP_SIZE from 64K to 512K. It seems that nothing changed. 
After I modified CFG_CORE_HEAP_SIZE from 64K to 512K, I thougt file "object#1" max size should be larger. Am I wrong?

>From the normal world, I pass 512K data to secure world in 1 time, in the secure world I use TEE_WriteObjectData to write the same data 20 times to 1 file "object#1".
But I found I can only write 3 times 512K data to file "object#1", then TA panicked with code 0xffff000c. 0xffff000c means TEEC_ERROR_OUT_OF_MEMORY.
file "object#1" max size seems to be 3.2M.

**Comment by jenswi-linaro** [comment]
So it's something else that limits the size. I guess you need to get your hand dirty and debug that, it shouldn't be too hard to find the source of that error code. You could try using `CFG_CORE_DUMP_OOM=y` to get a stack trace on each failed malloc, but I'm not sure that it's malloc that's failing given the large heap.

**Comment by xiaxinkai** [comment]
@jenswi-linaro thanks you again. I will try to debug it.

**Comment by xiaxinkai** [comment]
Thanks. I have divide my large data to small pieces(1M each). It's OK.
So I close this issue.

**Comment by xiaxinkai** [comment]
@jenswi-linaro
>CFG_CORE_HEAP_SIZE
You are right.

>I have modified CFG_CORE_HEAP_SIZE from 64K to 512K. It seems that nothing changed.
Why nothing changed? Beacuse I made a serious mistake, there is no target for optee_os to make, like "make optee_os", so in fact I didn't compile my changes to the board rom image.
Now I use "make xtest" to make optee_os to be updated in the rom, I can write large data into secure storage(REE FS).

Thank you very much.

**Comment by TaihuLight** [comment]
@jenswi-linaro
Could I store a large file size of more than 512Mb into secure storage space by modifying CFG_CORE_HEAP_SIZE？
