### ISSUE TITLE
How to call into TEE from Uboot?

### ISSUE THREAD

**Issue by karmen27** [OP-TEE/optee_os#3248]
Hi，all
	I am working on a project that I need to call into TEE from uboot to do some cipher task. Is there any API like tee_client_api can be called within the uboot?
And, whether I need to porting a driver like optee_driver to implement this API or not, if so, where I can get it? Does Linaro open it or other projects?
Thank you very much in advance.

**Comment by vchong** [comment]
You can refer to functions in https://github.com/u-boot/u-boot/blob/master/include/tee.h. Example usage here: https://github.com/u-boot/u-boot/blob/master/test/dm/tee.c.

**Comment by karmen27** [comment]
Thanks a lot, @vchong.
