### ISSUE TITLE
QEMU cannot connect to network.

### ISSUE THREAD

**Issue by lcs100** [OP-TEE/optee_os#3249]
Hello everyone!
I recently do some tests on OPTEE with qemu.
But qemu optee seems can not connect to network.just like this:
`Welcome to Buildroot, type root or test to login
buildroot login: root
# ping baidu.com
PING baidu.com (39.156.69.79): 56 data bytes
^C
--- baidu.com ping statistics ---
104 packets transmitted, 0 packets received, 100% packet loss
# ping 10.0.2.2
PING 10.0.2.2 (10.0.2.2): 56 data bytes
64 bytes from 10.0.2.2: seq=0 ttl=255 time=9.723 ms
64 bytes from 10.0.2.2: seq=1 ttl=255 time=4.499 ms
64 bytes from 10.0.2.2: seq=2 ttl=255 time=2.395 ms
64 bytes from 10.0.2.2: seq=3 ttl=255 time=2.090 ms
64 bytes from 10.0.2.2: seq=4 ttl=255 time=2.022 ms
64 bytes from 10.0.2.2: seq=5 ttl=255 time=2.276 ms
^C
--- 10.0.2.2 ping statistics ---
6 packets transmitted, 6 packets received, 0% packet loss
round-trip min/avg/max = 2.022/3.834/9.723 ms
`
OPTEE qemu seems cannot connect to outside network.WHY?thank you.

**Comment by jbech-linaro** [comment]
I'm not sure, but I think it's only a local network between the host and the client. Then also, I guess that the routing and DNS probably isn't configured.

**Comment by jforissier** [comment]
https://optee.readthedocs.io/building/devices/qemu.html?highlight=Slirp#networking

**Comment by lcs100** [comment]
Thank in advnace:)
