### ISSUE TITLE
Query: Is there any way to move the PTA'a from core/arch/arm/pta to different location in OPTEE

### ISSUE THREAD

**Issue by sddev-coder** [OP-TEE/optee_os#3250]
This is just query: I am looking for moving the PTAs from /core/arch/arm/pta folder. and build it at some other location and link it with optee.
Is there any way to do that? or reference available which I can look?

**Comment by jforissier** [comment]
Hi @sddev-coder,
Short answer: no. I have not heard about such a setup. PTAs are so closely tied to the TEE core that trying to split them away is probably a bad idea that will come bite you sooner or later...

**Comment by FulcronZ** [comment]
Hi @sddev-coder 

optee_os doesn't have out-of-tree build support as in EDK2 yet. EDK2 can work multiple trees at the same time to create a UEFI image. A normal setup for EDK2 is [edk2][edk2], [edk2-platforms][edk2-platforms] and [edk2-non-osi][edk2-non-osi]. 

If you want to build platform-specific PTAs, you can put them under your target platform. Take a look at DeveloperBox's [RNG PTA][rng_pta]. 

[edk2]: https://github.com/tianocore/edk2
[edk2-platforms]: https://github.com/tianocore/edk2-platforms
[edk2-non-osi]: https://github.com/tianocore/edk2-non-osi
[rng_pta]: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-synquacer/rng_pta.c
