### ISSUE TITLE
Adding hardware accelerated crypto

### ISSUE THREAD

**Issue by Koneeee1** [OP-TEE/optee_os#3251]
Hello,

i am working with OPTEE running on the Zynq zcu102 board (arm cortex a53) inside a Petalinux environment.
The goal is to integrate the hardware acceleration inside OPTEE, following the guideline set in the [crypto documentation](https://optee.readthedocs.io/architecture/crypto.html?highlight=hardware#the-crypto-services).

The [Xilinx crypto API ](https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/64749783/ZynqMP+AES+Driver) is working with sys/socket.h. My understanding is that OPTEE does not provide a socket library at the moment.
So I am trying to implement the hardware acceleration on a lower level, using the xilsecure library (the library for the boards crypto peripherals), but I don't know how to link it inside the optee-os repository.
The xilsecure documentation assumes the Xilinx SDK work environment, but adding OPTEE to the SDK also sounds difficult.

Does anyone have experience with using the optee-os project inside a board environment?

Kind regards,
Konrad

**Comment by jenswi-linaro** [comment]
Hi @Koneeee1,

A similar exercise is currently being performed starting with https://github.com/OP-TEE/optee_os/pull/3228 (hashes). Other pull request will follow adding more algorithms.

Cheers,
Jens

**Comment by Koneeee1** [comment]
That looks interesting!
I am trying to do a research project on a smaller scale. Right now I am trying to work out the makefile syntax used in the project. In the [documentation](https://optee.readthedocs.io/building/gits/optee_os.html) it doesn't really specify if it's possible to add library dependencies into the lib directories.
For my project I wanted to add the hardware libraries (libxil.a) inside my alternative libtomcrypt implementation. Is there a way to add the necessary flags (-I, -L, -l) to the sub.mk?

**Comment by Koneeee1** [comment]
Thank you, that looks promising

**Comment by Koneeee1** [comment]
So right now I have implemented the hardware access inside a pseudo trusted application. The PTA provides the memory acccess to the peripheral and also includes a test routine doing a single aes encryption round. The PTA is located under core/arch/arm/ and I gave it a random UUID.
I'd now like to use the routine I wrote inside libtomcrypt. For that I would need to use the API defined in libutee (TEE_OpenTASession, TEE_InvokeTACommand, TEE_CloseTASession) but I am not sure how to link libutee. Can you explain the steps necessary? 
Right now I added 
libdirs += $(ta-dev-kit-dir)/lib
libnames += utee
libdeps += $(ta-dev-kit-dir)/lib/libutee.a
to the sub.mk, but I am not sure if libutee is compiled previous to libtomcrypt.

Kind regards

**Comment by etienne-lms** [comment]
hello @Koneeee1,
The picture is sightly different. You would register you HW driver in the optee core crypto API. This way, both core and TA crypto operations relying on the common internal crypto API will use your driver for your supported algorithm. This is on-going `drvcrypt` development.

https://github.com/OP-TEE/optee_os/pull/3259 is finalizing now. It shows registration of a hash processors (md5/sha*) in the crypto API. Check how it calls `drvcrypt_register()` (thru `drvcrypt_register_hash()`), to register its hash driver.
#3259 will likely be followed but other P-Rs for registering other crypto algorithms. Stay tune, feel free to participate to discussions.

**Comment by Koneeee1** [comment]
So as a start I pretty much merged the work done in the NXP-hash patch and the xilinx hardware API. I removed the RNG module, the hal and the jobring driver.
To test my setup I am calling the driver from inside the hello_word_ta example:
`        
        // Hashing abc, Expecting "a9993e364706816aba3e25717850c26c9cd0d89d"
        char hash[64] = {0};
        uint32_t hash_len = 64;

        TEE_OperationHandle operation = (TEE_OperationHandle)NULL;
        TEE_Result ret;

        ret = TEE_AllocateOperation(&operation, TEE_ALG_SHA1, TEE_MODE_DIGEST, 0);
        ret = TEE_DigestDoFinal(operation, sha1msg, 3, hash, &hash_len);
        TEE_FreeOperation(operation);
`
When I look at the debug log, during startup I see the registration of the SHA1 Module
D/TC:0 0 crypto_driver_init:18 crypto_driver_init
D/TC:0 0 caam_hash_init:638 caam_hash_init
D/TC:0 0 drvcrypt_register:16 Registering module id 0 with 0x0x60026cb8

When I execute the hello_word_ta I see the following debug log, which looks to me like the hash_alloc gets called 3 times (which should probably not happen?) before it crashes with TEE_ERROR_CORRUPT_OBJECT.
Do you have any idea on how I could further debug the error?

D/TC:? 0 drvcrypt_hash_alloc_ctx:18 hash alloc_ctx algo 0x50000004
D/TC:? 0 caam_hash_allocate:599 caam_hash_allocate
D/TC:? 0 mem_alloc:97 alloc 96 bytes of type 1
D/TC:? 0 mem_alloc:166 alloc returned 0x60069d50 -> 0x60069d68
D/TC:? 0 drvcrypt_hash_alloc_ctx:27 hash alloc_ctx ret 0x0
D/TC:? 0 do_allocate_intern:213 do_allocate_intern
D/TC:? 0 do_allocate_intern:216 Allocate Context (0x0x60069d68)
D/TC:? 0 mem_alloc:97 alloc 80 bytes of type 3
D/TC:? 0 read_cacheline_size:57 System Cache Line size = 32 bytes
D/TC:? 0 mem_alloc:152 alloc 0x60069ca0 0x60069cc0 160 vs 80
D/TC:? 0 mem_alloc:166 alloc returned 0x60069ca0 -> 0x60069cc0
D/TC:? 0 mem_alloc:97 alloc 40 bytes of type 3
D/TC:? 0 read_cacheline_size:57 System Cache Line size = 32 bytes
D/TC:? 0 mem_alloc:152 alloc 0x60069c30 0x60069c60 96 vs 40
D/TC:? 0 mem_alloc:166 alloc returned 0x60069c30 -> 0x60069c60
D/TC:? 0 mem_alloc:97 alloc 64 bytes of type 2
D/TC:? 0 read_cacheline_size:57 System Cache Line size = 32 bytes
D/TC:? 0 mem_alloc:152 alloc 0x60069ba0 0x60069bc0 128 vs 64
D/TC:? 0 mem_alloc:166 alloc returned 0x60069ba0 -> 0x60069bc0
D/TC:? 0 caam_cpy_block_src:430 Current buffer is 0 (64) bytes
D/TC:? 0 caam_cpy_block_src:430 Current buffer is 34 (64) bytes
D/TC:? 0 do_free_intern:192 Free Context (0x0x60069d68)
D/TC:? 0 drvcrypt_hash_alloc_ctx:18 hash alloc_ctx algo 0x50000004
D/TC:? 0 caam_hash_allocate:599 caam_hash_allocate
D/TC:? 0 mem_alloc:97 alloc 96 bytes of type 1
D/TC:? 0 mem_alloc:166 alloc returned 0x60069af0 -> 0x60069b08
D/TC:? 0 drvcrypt_hash_alloc_ctx:27 hash alloc_ctx ret 0x0
D/TC:? 0 do_allocate_intern:213 do_allocate_intern
D/TC:? 0 do_allocate_intern:216 Allocate Context (0x0x60069b08)
D/TC:? 0 mem_alloc:97 alloc 80 bytes of type 3
D/TC:? 0 read_cacheline_size:57 System Cache Line size = 32 bytes
D/TC:? 0 mem_alloc:152 alloc 0x60069a40 0x60069a60 160 vs 80
D/TC:? 0 mem_alloc:166 alloc returned 0x60069a40 -> 0x60069a60
D/TC:? 0 mem_alloc:97 alloc 40 bytes of type 3
D/TC:? 0 read_cacheline_size:57 System Cache Line size = 32 bytes
D/TC:? 0 mem_alloc:152 alloc 0x600699d0 0x60069a00 96 vs 40
D/TC:? 0 mem_alloc:166 alloc returned 0x600699d0 -> 0x60069a00
D/TC:? 0 mem_alloc:97 alloc 64 bytes of type 2
D/TC:? 0 read_cacheline_size:57 System Cache Line size = 32 bytes
D/TC:? 0 mem_alloc:152 alloc 0x60069940 0x60069960 128 vs 64
D/TC:? 0 mem_alloc:166 alloc returned 0x60069940 -> 0x60069960
D/TC:? 0 caam_cpy_block_src:430 Current buffer is 0 (64) bytes
D/TC:? 0 caam_cpy_block_src:430 Current buffer is 34 (64) bytes
D/TC:? 0 do_free_intern:192 Free Context (0x0x60069b08)
D/TC:? 0 mem_alloc:97 alloc 96 bytes of type 1
D/TC:? 0 mem_alloc:166 alloc returned 0x60069700 -> 0x60069718
D/TC:? 0 drvcrypt_hash_alloc_ctx:27 hash alloc_ctx ret 0x0
D/TC:? 0 crypto_hash_alloc_ctx:28 crypto_hash_alloc_ctx with algo 0x50000004 called drvcrypt_hash_alloc_ctx which returned with 0x00000000
D/TC:? 0 do_allocate_intern:213 do_allocate_intern
D/TC:? 0 do_allocate_intern:216 Allocate Context (0x0x60069718)
D/TC:? 0 mem_alloc:97 alloc 80 bytes of type 3
D/TC:? 0 read_cacheline_size:57 System Cache Line size = 32 bytes
D/TC:? 0 mem_alloc:152 alloc 0x60069650 0x60069680 160 vs 80
D/TC:? 0 mem_alloc:166 alloc returned 0x60069650 -> 0x60069680
D/TC:? 0 mem_alloc:97 alloc 40 bytes of type 3
D/TC:? 0 read_cacheline_size:57 System Cache Line size = 32 bytes
D/TC:? 0 mem_alloc:152 alloc 0x600695e0 0x60069600 96 vs 40
D/TC:? 0 mem_alloc:166 alloc returned 0x600695e0 -> 0x60069600
D/TC:? 0 mem_alloc:97 alloc 64 bytes of type 2
D/TC:? 0 read_cacheline_size:57 System Cache Line size = 32 bytes
D/TC:? 0 mem_alloc:152 alloc 0x60069550 0x60069580 128 vs 64
D/TC:? 0 mem_alloc:166 alloc returned 0x60069550 -> 0x60069580
D/TC:? 0 caam_cpy_block_src:430 Current buffer is 0 (64) bytes
D/TC:? 0 caam_cpy_block_src:430 Current buffer is 34 (64) bytes
D/TC:? 0 do_free_intern:192 Free Context (0x0x60069718)
D/TC:? 0 system_open_ta_binary:239 res=0xf0100001
D/TC:? 0 tee_ta_invoke_command:771 Error: f0100001 of 4
E/LD:  init_elf:238 sys_open_ta_bin(8aaaf200-2450-11e4-abe2-0002a5d5c51b)
E/TC:? 0 init_with_ldelf:229 ldelf failed with res: 0xf0100001
D/TC:? 0 tee_ta_close_session:497 csess 0x6006ab60 id 1
D/TC:? 0 tee_ta_close_session:516 Destroy session

**Comment by etienne-lms** [comment]
There are several debug flags available through `CFG_CAAM_DBG`, see [core/arch/arm/plat-imx/crypto_conf.mk](https://github.com/OP-TEE/optee_os/commit/2d7a8964dfcbe6c3494a0889831818dd8f153f4a#diff-addf31153a9c4fdd55622c35bb9b9e91). Maybe you ported these. It's hard to blindly guess what could have happen.

**Comment by Koneeee1** [comment]
So just to clear up my mistake, I didn't realize that the TA uses SHA256 during its initialization, which wasn't implemented yet. I just added the default libtomcrypt implementation back in and can now continue testing Sha1.
