### ISSUE TITLE
How can TA invoke UART on Hikey 960 ?

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#3252]
I have setup a branch (AOSP + OPTEE) for the Hikey 960 board. I see that the optee_os/core/drivers/ folder has the serial driver pl011.c. The Hikey 960 has two UARTs on its low speed header.

I want to ask:
- how can I send / receive data over UART from TA code ?  Which API should I use ?
- Is there any test code you have that shows how TA can send / receive data using UART ?

**Comment by vchong** [comment]
A regular (user mode) TA has no access to low level functions like IO. You can write a pseudo-TA instead and call UART functions from the invoked commands. See https://optee.readthedocs.io/architecture/trusted_applications.html#pseudo-trusted-applications for details.
