### ISSUE TITLE
About trusted storage RPMB in op-tee

### ISSUE THREAD

**Issue by zhengxun** [OP-TEE/optee_os#3263]
Hello,

I checked the op-tee's code and documentation. According to GlobalPlatform Trusted Storage Requirement, if you compil with "CFG_REE_FS=y", each TA only access to its own storage space . 

Here are my questions:

1. If you only using "CFG_RPMB_FS=y",  the TA can only access to its own storage space, right ?

2. When using "CFG_REE_FS = y" and "CFG_RPMB_FS = y", the secure data store in /data/tee includes dirf.db and private data? So, what files can be stored in RPMB?

**Comment by zhengxun** [comment]
Hi @jforissier,
Thank you for the explanation! Actually, I have another question about this issue[#1954](https://github.com/OP-TEE/optee_os/issues/1954). @etienne-lms commented that using "ree_fs" or "rpmb_fs" as a secure storage for the normal world, data could be corrupted, causing a denial of service attack. 

1. Why not access storage directly in secure world, can it solve D-O-S attacks? 
2. If the above question is "yes", do you have any suggestions for this implementation?

**Comment by jbech-linaro** [comment]
> 1. Why not access storage directly in secure world, can it solve D-O-S attacks?

Technically it's doable, but most devices use a single (e)MMC and Linux kernel expects that it has full ownership and authority of the flash memory. Therefore one has to go via Linux kernel interfaces when using flash. From security point of view we can integrity protect and encrypt the data. This means that data looks like garbled data and if someone tamper with it, secure side will detect that. But, as you said, the major downside is the DOS attack.

This way of kernel "owning" the flash will not change. So the only other way I could see is if there was a second (secure) flash that was only accessible by secure side. But I'm unaware of such devices.

**Comment by zhengxun** [comment]
Hi @jbech-linaro 
Thank you for your detailed explanation!
