### ISSUE TITLE
u-boot: tee_open_session() and SHM_ALLOC

### ISSUE THREAD

**Issue by a21152** [OP-TEE/optee_os#3269]
When calling tee_open_session() from u-boot, the parameters structure is allocated via the generic malloc() via __tee_shm_add:

	rc = __tee_shm_add(dev, OPTEE_MSG_NONCONTIG_PAGE_SIZE, NULL,
			   OPTEE_MSG_GET_ARG_SIZE(num_params), TEE_SHM_ALLOC,
			   shmp);

This was not working for me because the memory allocated was not part of the reserved shared memory pool known to optee-os. I wonder why u-boot is handling TEE_SHM_ALLOC with a regular malloc(). Shouldn't u-boot query optee reserved shm memory range and allocate from that range?

**Comment by jenswi-linaro** [comment]
U-Boot depends on OP-TEE compiled with `CFG_CORE_DYN_SHM=y`, and also that OP-TEE is aware of all non-secure memory.

Two things to check:
- Are there changes to `optee_probe()` in `drivers/tee/optee/core.c`
- OP-TEE doesn't know all non-secure memory
