### ISSUE TITLE
adjust linker script to support offline and online signing

### ISSUE THREAD

**Issue by wamserma** [OP-TEE/optee_os#3275]
Currently offline signing requires the user to adjust 
https://github.com/OP-TEE/optee_os/blob/master/ta/arch/arm/link.mk
which is not convenient, see https://github.com/OP-TEE/optee_docs/pull/11#discussion_r296602983

Fixing this will probably incur some wider ranging changes to the build process. A possible solution might be to always make the signing step explicit, even when a private key is available in the OP-TEE OS source tree.

**Comment by wamserma** [comment]
Hey @github-actions please remove the stale label. This is still TBD.

**Comment by jforissier** [comment]
@wamserma done!

**Comment by wamserma** [comment]
Hey @github-actions please remove the stale label. This is still TBD.
Needs also some discussion with the maintainers.

**Comment by jenswi-linaro** [comment]
@wamserma, can you give a summary of the current state. Have any progress been done etc.

**Comment by wamserma** [comment]
@jenswi-linaro I haven't put any work in this yet.

Commonly I just build the `.stripped.elf` then do the signing with (two) direct calls to the signing script and offline signing.
