### ISSUE TITLE
How to get a TA into the filesystem that is used when booting QEMU?

### ISSUE THREAD

**Issue by MALATTAR** [OP-TEE/optee_os#328]
Hi,
I tried to test opTee using QEMU emulator.
I built the hellow_world example provided by Jens Wiklander (lcu14_optee_hello_world).
I modified  gen_rootfs/filelist-tee.txt  in order to push the executable and the TA into /bin and /lib/teets repecitvely. Then, I called  update_rootfs.sh  to regenerate the filesystem.
Eventhough filesystem.cpio.gz  (which I think it is the image of the filesystem that it is called when kernel is launched) contains the TA and the hellow-world executable, but the loaded kernel module for OP-TEE  does not contain the TA nor the executable !!!
Have you any idea about this problem?

Regards,
MALATTAR

**Comment by jbech-linaro** [comment]
Hi @MALATTAR ,

For QEMU you also need to run the script `build_bios.sh`. Since the bios uses the file `filesystem.cpio.gz`.

We are aware that the current setup is a bit hard to use, you really need to know in which order to build things. We are going to change this very soon to instead make use of makefiles entirely to take care of the dependencies like this. To get an idea of how it will look in the future you could have a sneak peak here: https://github.com/jbech-linaro/build

Regards,
// Joakim

**Comment by MALATTAR** [comment]
Hi Joakim,
Thanks for answering me.
I lauch ./build in order to update the filesystem...
hello_world was pushed into /bin, but /lib/teetz was deleted...
In addition, supplicant is also disappeared !!!
So, I decided to re-install the hall environment (using setup_qemu_optee.sh)
Everything was going well untill I had the following error:
.......
Check crosscompiler ... OK
gen_init_cpio ... OK
It appears we're missing a busybox git, cloning it.
Cloning into 'busybox'...
fatal: unable to connect to busybox.net:
busybox.net[0: 140.211.167.224]: errno=Connection timed out
busybox.net[1: 140.211.167.224]: errno=Connection timed out
Failed. ABORTING.

What is the address of cloning busybox?

Regards,
MALATTAR

**Comment by zzm7000** [comment]
Since the order of calling those scripts is important, you can try to simply use build.sh without thinking about the order. It works on my machine.

**Comment by MALATTAR** [comment]
I resolved the proble but after doing different things:
- reinstalling opTee on qemu.... here there was a problem concerning cloning Busybox (which is found in generate-cpio-rootfs.sh). I think the address of cloning is no more valide. The solution was to download Busybox and build it inside gen_rootfs
- I launched the normal world, secure workd and the qemu monitor.... using serial_0.sh, serial_1.sh and run_qemu.sh respectively. However, there was an error in loading the normal world... some files/and folder are not found. The solution was, to update rootfs by using  update_rootfs.sh such that I used filelist-final.txt instead of filelist-tee.txt to generat the rootfs. Of course, I copied some parts of filelist-tee.txt into filelist-final.txt before launching the script. The copied parts concern the tee-supplicant, optee_armtz and other files. At the end, I executed build_bios.sh script in order to update the filesystem. 

So, there is a chance that filelist-tee.txt is not correctly generated during the installation, or I missed something during the installation......

**Comment by jbech-linaro** [comment]
@MALATTAR , Oh, I didn't know that the URL to busybox has been changed. Other than that, the file pointing out the files to be stored in the root fs is the filelist-tee.txt. You can of course modify it to use the other file if you want to. We have some improvement to this coming soon. As you can see [here](https://github.com/jbech-linaro/build/blob/master/qemu.mk#L93-L113) this is something that will handle autoupdates of the filelist-tee.txt. That will handle TA's and xtest, kernel driver and client libraries (as longs as they are on the path specified by the scripts in use). But, hold out the clone and build scripts will be updated or replaced soon I'd guess.

@zzm7000 yes, you are right, the fail-safe way is to simply run `build.sh`.

**Comment by vchong** [comment]
Just verified "git clone git://busybox.net/busybox.git" in generate-cpio-rootfs.sh works fine.
