### ISSUE TITLE
Run ta before normal world starts

### ISSUE THREAD

**Issue by Cowboy555** [OP-TEE/optee_os#3280]
Hello, we want to use optee to make an ftpm. So we need to start our ftpm before starting rich os, so that it can measure rich os like a physical TPM.
Through issues #666, we know that static ta can be run right after the start of secure world and before the run of normal world, which meets our startup needs. But through issues #1085, we know that a static TA isn't a proper TA, it's rather a TA like interface. So, can a static TA start measuring rich os before the normal world starts? Or we need to change the startup mode of optee to create a dynamic ta to complete our work. 
The information in this area is really too small, and the static ta example on github is also 404.

**Comment by jbech-linaro** [comment]
Hi @Cowboy555 , I did some [work](https://github.com/jbech-linaro/manifest/tree/ftpm) with fTPM for my [fTPM session](https://youtu.be/-uR_oUp0wPE) at Linaro Connect (BKK19). I encountered the same issues as you're describing here. Regarding the TA's, you can compile a regular TA as a "[early TA](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#early-ta)", so you don't have to run it as a [PTA](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#pseudo-trusted-applications). Having said that, to do measurements, there are problems that needs to be resolved. Before the TEE is running, boot binaries must measure themselves and then later provide the measurement to the TEE. I elaborate a bit around that in my session [here](https://youtu.be/-uR_oUp0wPE?t=1656).

> The information in this area is really too small, and the static ta example on github is also 404.

What information is missing? And which GitHub example is 404? With more details we can fix the things.

**Comment by jbech-linaro** [comment]
P.s., note that even if you can run a normal TA as early TA, there are still things that cannot be done. Remember that we still rely on the tee-supplicant for some services (secure storage is one of them). So depending on the use case things might work or not.

**Comment by Cowboy555** [comment]
Thank you for your answer. The reason why I didn't find the example is because I don't know that the static ta has been renamed. It is now called pseudo ta and its example is currently in core/pta.

**Comment by jbech-linaro** [comment]
> It is now called pseudo ta and its example is currently in core/pta

So, isn't that working?

**Comment by Cowboy555** [comment]
Sorry, we haven't started our practice yet, we are still in the planning stage.
The current plan is that we only complete the metrics after tee startup. Before the file system starts, we put the PCR value in the safe world memory and store it when it needs to be persisted.
Our question now is whether our ftpm needs persistent initialization data, so we have to add a separate file system to our ta.

**Comment by vivinamartins16** [comment]
Hey @Cowboy555 ! I did some work on that issue too. I think you could also take a look at [these two TAs](https://github.com/microsoft/MSRSec). 

Also, I agree with you regarding the lack of information on boot measurements and boot-related interactions with the TEE and TAs/PTAS.

I was successfull building IMA measurements in Normal world. I'm not sure this is relevant to your use case (to ours it wasn't since we always assume normal world as un-trusted, so no need for security there) but maybe you can give it a shot.

Hope you are successful! And keep us posted ;) I'd like to hear how your implementation turned out!

**Comment by railabouni** [comment]
> P.s., note that even if you can run a normal TA as early TA, there are still things that cannot be done. Remember that we still rely on the tee-supplicant for some services (secure storage is one of them). So depending on the use case things might work or not.

Hi @jbech-linaro, can you please elaborate on that? I think that @Cowboy555 idea should work right? 
"The current plan is that we only complete the metrics after tee startup. Before the file system starts, we put the PCR value in the safe world memory and store it when it needs to be persisted."
This can help measuring the bootup of the RICH OS ... afterwards, the file system is on and we can go back to the using secure storage through rich OS.

Question: why isn't there a way for OP-TEE to communicate directly with secure storage, without the need of rich OS?
I'm also digging into the technical details of implementing an fTPM in TrustZone to measure the rich OS in normal world, and I'm also curious to know if you had any success @Cowboy555 
Thank you!

**Comment by Loveself7070** [comment]
I want maximum protection for the governor.

**Comment by jbech-linaro** [comment]
> > P.s., note that even if you can run a normal TA as early TA, there are still things that cannot be done. Remember that we still rely on the tee-supplicant for some services (secure storage is one of them). So depending on the use case things might work or not.
> 
> Hi @jbech-linaro, can you please elaborate on that? I think that @Cowboy555 idea should work right? "The current plan is that we only complete the metrics after tee startup. Before the file system starts, we put the PCR value in the safe world memory and store it when it needs to be persisted." This can help measuring the bootup of the RICH OS ... afterwards, the file system is on and we can go back to the using secure storage through rich OS.
> 

Certainly that could work and that is an idea that we've explored (@apalos might be able to share more information about it).

> Question: why isn't there a way for OP-TEE to communicate directly with secure storage, without the need of rich OS? 

It depends on the capabilities and device. An embedded device, mobile phone and similar devices often use an eMMC and there it's the OS (Linux etc) who has taken the ownership of the eMMC. So, to avoid concurrency issues, we have to go via the main OS to read/write things to eMMC (including RPMB). There is nothing really preventing you from using the eMMC before the main OS is up an running. But, that comes with other challenges. You need drivers in various boot binaries, you'll need to make sure that there is no concurrency issues between boot binaries if more than one of them try to use the eMMC at the same time. U-boot have RPMB support, to give one example.

The other approach would have to have a dedicated flash to secure side, but that is something that you don't come across very often.

**Comment by railabouni** [comment]
@jbech-linaro thank you fo the great info you've previously provided!

> Our question now is whether our ftpm needs persistent initialization data, so we have to add a separate file system to our ta.

well, that's also a great question: assuming that we compile our fTPM TA as an early TA, does this TA need persistent initialization data which must be retrieved from RPMB for example (such as hierarchies) before RICH OS and tee-supplicant are up?

is this something that you guys @Cowboy555 @jbech-linaro @apalos have explored?

thank you!

**Comment by graziadonghia** [comment]
@jbech-linaro I am currently trying [you implementation](https://github.com/jbech-linaro/manifest/tree/ftpm?tab=readme-ov-file) of the fTPM in OP-TEE, but since it is not aligned with the current OP-TEE version (4.3.0), I cannot even build it. On what version of OP-TEE is your project based?
