### ISSUE TITLE
cannot DMSG float or double in TA

### ISSUE THREAD

**Issue by xiaxinkai** [OP-TEE/optee_os#3286]
Dear Team:

I want to output float or double in TA.
for example:

DMSG("(3.1 is %f", 3.1);

I got output:
"3.1 is f"

Now, optee os do not support %f format?

**Comment by jenswi-linaro** [comment]
Correct, `%f` or any other floating point format is not supported.

**Comment by xiaxinkai** [comment]
@jenswi-linaro Thank you very much!
