### ISSUE TITLE
Core crash in xtest 1013 (Hikey, pager)

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3296]
I have observed occasional IBART crashes in `xtest 1013`, such as the one discussed [here](https://github.com/OP-TEE/optee_os/pull/3268#issuecomment-532598986). The crashes can be reproduced by running `xtest 1013` in a loop with pager enabled.

This issue looks very similar to #794, I guess it's just because some memory page happens not to be mapped when it should whatever the reason.

**Comment by jforissier** [comment]
I came across this Linux patch: [Revert "arm64: Remove unnecessary ISBs from set_{pte, pmd, pud}"](https://patchwork.kernel.org/patch/11116933/). I'm wondering if we might be missing some `isb()` calls and if it could explain the crashes.

So I tried throwing a few `isb()` calls in the pager code wherever we have a `dsb_ishst()`, but that did not fix the issue. Are we missing  `dsb*()` and/or `isb()` in other places of memory management perhaps?

**Comment by jforissier** [comment]
To reproduce on HiKey:
```
$ make -j10 CFG_RPMB_WRITE_KEY=y CFG_RPMB_FS=y CFG_SECURE_DATA_PATH=y CFG_WITH_PAGER=y CFG_TEE_CORE_LOG_LEVEL=2 CFG_LOCKDEP=y CFG_CORE_MBEDTLS_MPI=y
hikey $ C=1; while [ $? -eq 0 ]; do echo C=$C; xtest 1013 >/dev/null; C=`expr $C + 1`; done
```

It can take some time before the crash happens (in my testing: C=2; C=15; C=7; C=26).

**Comment by jenswi-linaro** [comment]
I'm quite sure that this has been stable before. Would it be possible to bisect it?

**Comment by jforissier** [comment]
> Would it be possible to bisect it?

Sure. I'll try.
But I'm starting to suspect a race condition between `tee_tadb_open()` and `tee_tadb_close()`.

**Comment by jforissier** [comment]
First finding: bisected to 28c75dbebc49 ("hikey: increase core heap size to 192 kB") which is obviously not the root cause, but it looks like this commit causes a tremendous amount of paging (`time xtest 1013` increases from 1.7s to 53.7s!). @vchong are you using the pager with VTS? If not, perhaps the size should not be increased when the pager is enabled.

**Comment by vchong** [comment]
@jforissier pager isn't used in AOSP builds so it's ok

**Comment by jforissier** [comment]
Second finding: crash is reproducible **without** pager.

**Comment by jforissier** [comment]
Third finding: if I get rid of the refcount and only use the mutex unconditionally, the test is rock solid.

So, it must be that the refcount + mutex are not used properly, or that our refcount implementation has a bug or is improper for this kind of use. For instance our atomic operations use `__ATOMIC_RELAXED` and I think that's no good because it does not prevent potentially problematic reordering of some memory accesses (when conditionally taking the mutex for instance). But I could not make things work even with `__ATOMIC_SEQ_CST` so there must be something else.

TBH, I don't think that trying to avoid taking the mutex is a worthwhile optimization. I'll run some comparisons and we'll see.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/3304

**Comment by jenswi-linaro** [comment]
> TBH, I don't think that trying to avoid taking the mutex is a worthwhile optimization.

Agree

**Comment by jforissier** [comment]
Closing since #3304 is merged.
