### ISSUE TITLE
TA memory calloc() problem

### ISSUE THREAD

**Issue by xiaxinkai** [OP-TEE/optee_os#3297]
Dear Team:
@jenswi-linaro 

Thank you in advance, please help me.

I'm using Raspberry Pi 3b to develop program.

Problem:
I can use TEE_Malloc(56M) to get memory in 1 time. So the memory of TA is enough to me.
As I know, TEE_Malloc is implemented by malloc or calloc, finally it calls bget.
But I found, when I use calloc() to get many pieces of small size memory, the last some memory pieces calloc() failed.

Even though I increase the CFG_TZDRAM_SIZE to 128M (I can TEE_Malloc(110M) in one time), I get the same result.
So, Are there any configs to limit the amount or number of small memory?

----------------------------------------------------------------------------------------------
Enviroment:
optee_client version: 3.5.0
optee_os version: 3.5.0 (v3.6.0 needs python3 for compiling, so I can not use v3.6.0 now)
optee_examples version: latest

Following is my config:

(1)optee_os\mk\config.mk
CFG_TEE_TA_LOG_LEVEL ?= 4
CFG_TEE_TA_MALLOC_DEBUG ?= y
(2)optee_os\core\arch\arm\plat-rpi3\conf.mk
CFG_TZDRAM_SIZE ?= 0x04000000
CFG_TEE_RAM_VA_SIZE ?= 0x00200000
(3)optee_os\core\arch\arm\include\mm\pgt_cache.h
#ifdef CFG_WITH_PAGER
#if CFG_NUM_THREADS < 2
#define PGT_CACHE_SIZE	4
#else
#define PGT_CACHE_SIZE	ROUNDUP(CFG_NUM_THREADS * 2, PGT_NUM_PGT_PER_PAGE)
#endif
#else
#define PGT_CACHE_SIZE	32
#endif /*CFG_WITH_PAGER*/
(4)optee_examples\darknetp\ta\include\user_ta_header_defines.h
#define TA_STACK_SIZE			(1 * 1024 * 1024)
#define TA_DATA_SIZE			(60 * 1024 * 1024)

**Comment by etienne-lms** [comment]
My apologies but I don't understand the issue. Do you mean that, assuming malloc pool is above 50MB, for example:
`ptr = calloc(1024 * 1024, 50);` succeeds but
`for (i=0; i<1024*1024; i++) { ptr[i] = malloc(50); }` fails to allocate all expected buffers?

**Comment by xiaxinkai** [comment]
@etienne-lms Thank you for your reply.
The problem maybe memory fragmentation,
Temporarily, I can not explain how to reproduce the problem.
Now I reduce the memory amount I need to use, it's OK.
So I close this issue temporarily.
When I must solve this issue next time, I will reopen it.
Thank you!
