### ISSUE TITLE
Add an early TA

### ISSUE THREAD

**Issue by 1flurry** [OP-TEE/optee_os#3305]
Hi,

I want to run ta before normal world starts, so I try to use Early TA. I have added EARLY_TA_PATH in optee_os/mk/config.mk. However, when I run 'make all', there is an error: 'No rule to make target'. 

How can I solve that?  Could you please help with the process.

Thanks!
1flurry

**Comment by jforissier** [comment]
Hi @1flurry ,

1. It's `EARLY_TA_PATHS` with an `S`
2. Does the file exist? Path needs to be relative to the `optee_os` directory, or absolute.

**Comment by 1flurry** [comment]
Hi

> Hi @1flurry ,
> 
> 1. It's `EARLY_TA_PATHS` with an `S`
> 2. Does the file exist? Path needs to be relative to the `optee_os` directory, or absolute.

Yes, I'm using an absolute path just like this:
EARLY_TA_PATHS = "/home/optee11/out-br/build/optee_examples-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.stripped.elf"

I'm sure that the file exists. But there still is an error like this:
make[1]: Entering directory `/home/optee11/optee_os'
  CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
make[1]: *** No rule to make target `"../out-br/build/optee_examples-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.stripped.elf"', needed by `out/arm/core/early_ta_8aaaf200-2450-11e4-abe2-0002a5d5c51b.c'.  Stop.

**Comment by jforissier** [comment]
> I'm sure that the file exists. 

And I'm pretty sure it does not :open_mouth:  (at the time when `optee_os` is built at least).

Please note, the TA has to be there before you build `optee_os`. So there is a circular dependency here: you need to build `optee_os` to build the TA dev kit which is needed to built the TA which is needed to build `optee_os`, as explained here: https://github.com/OP-TEE/optee_os/blob/3.6.0/mk/config.mk#L247-L253

```
make optee-os CFG_EARLY_TA=y && \
make optee-examples CFG_EARLY_TA=y && \
make optee-os EARLY_TA_PATHS = "/home/optee11/out-br/build/optee_examples-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.stripped.elf"
```

**Comment by 1flurry** [comment]
> > I'm sure that the file exists.
> 
> And I'm pretty sure it does not 😮 (at the time when `optee_os` is built at least).
> 
> Please note, the TA has to be there before you build `optee_os`. So there is a circular dependency here: you need to build `optee_os` to build the TA dev kit which is needed to built the TA which is needed to build `optee_os`, as explained here: https://github.com/OP-TEE/optee_os/blob/3.6.0/mk/config.mk#L247-L253
> 
> Try this:
> 
> ```
> make optee-os CFG_EARLY_TA=y && \
> make optee-examples CFG_EARLY_TA=y && \
> make optee-os EARLY_TA_PATHS = "/home/optee11/out-br/build/optee_examples-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.stripped.elf"
> ```

OK, I will try it. Thank you very much!

**Comment by farhadhussain** [comment]
In 3.7.0 It seems Early TA is not loaded and executed. Could you please explain how Early TA get loaded in 3.7.0.

**Comment by jforissier** [comment]
Hi @farhadhussain ,

The early TA mechanism has not changed, but the code used to load the user space TAs has changed (`ldelf` was introduced). Perhaps your TA has some specific things that make the new ELF loader unhappy.
Can you try to run your TA as a "normal" one? (that is, put the .ta file in the REE FS). If it still crashes at the same place, it will rule out the early TA mechanism itself.

FWIW, here is a quick test I did on master (QEMU). Shows that the `xtest` crypto TA works fine as an early TA.

```
[Build]

$ make -j10 CFG_EARLY_TA=y
$ make -j10 CFG_EARLY_TA=y EARLY_TA_PATHS=../out-br/build/optee_test-1.0/ta/crypt/out/cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.stripped.elf run

[Non-secure console]

$ xtest 4002

[Secure console]

I/TC: OP-TEE version: 3.8.0-103-gce94efef (gcc version 8.3.0 (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36))) #1 Fri 06 Mar 2020 09:19:58 AM UTC arm
D/TC:0 0 init_primary_helper:1171 Executing at offset 0xdc0f000 with virtual load address 0x1bd0f000
D/TC:0 0 check_ta_store:636 TA store: "early TA"
D/TC:0 0 check_ta_store:636 TA store: "Secure Storage TA"
D/TC:0 0 check_ta_store:636 TA store: "REE"
D/TC:0 0 early_ta_init:254 Early TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b size 122419 (compressed, uncompressed 307256)
D/TC:0 0 mobj_mapped_shm_init:447 Shared memory address range: 1c000000, 1e000000
D/TC:0 0 gic_it_set_cpu_mask:251 cpu_mask: writing 0xff to 0x1ea00828
D/TC:0 0 gic_it_set_cpu_mask:253 cpu_mask: 0xff
D/TC:0 0 gic_it_set_prio:266 prio: writing 0x1 to 0x1ea00428
I/TC: Initialized
D/TC:0 0 init_primary_helper:1184 Primary CPU switching to normal world boot
D/TC:0   psci_cpu_on:211 core pos: 1: ns_entry 0x40102620
D/TC:1   init_secondary_helper:1208 Secondary CPU Switching to normal world boot
D/TC:1   tee_entry_exchange_capabilities:101 Dynamic shared memory is enabled
D/TC:1 0 core_mmu_alloc_l2:278 L2 table used: 5/5
D/TC:? 0 tee_ta_init_pseudo_ta_session:284 Lookup pseudo TA 7011a688-ddde-4053-a5a9-7b3c4ddf13b8
D/TC:? 0 tee_ta_init_pseudo_ta_session:297 Open device.pta
D/TC:? 0 tee_ta_init_pseudo_ta_session:311 device.pta : 7011a688-ddde-4053-a5a9-7b3c4ddf13b8
D/TC:? 0 tee_ta_close_session:499 csess 0x1bdc0dd0 id 1
D/TC:? 0 tee_ta_close_session:518 Destroy session
D/TC:? 0 tee_ta_init_pseudo_ta_session:284 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
D/TC:? 0 load_ldelf:704 ldelf load address 0x104000
D/LD:  ldelf:134 Loading TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
D/TC:? 0 tee_ta_init_pseudo_ta_session:284 Lookup pseudo TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 tee_ta_init_pseudo_ta_session:297 Open system.pta
D/TC:? 0 tee_ta_init_pseudo_ta_session:311 system.pta : 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 system_open_ta_binary:251 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (early TA)
D/TC:? 0 system_open_ta_binary:254 res=0x0
D/LD:  ldelf:169 ELF (cb3e5ba0-adf1-11e0-998b-0002a5d5c51b) at 0x114000
```
