### ISSUE TITLE
Hikey960 is not connecting to WiFi

### ISSUE THREAD

**Issue by vivinamartins16** [OP-TEE/optee_os#3306]
Hey all!

After following the steps from [readthedocs](https://optee.readthedocs.io/en/stable/building/gits/build.html#get-and-build-the-solution), I got a 3.6.0 version of OP-TEE in my hikey960.
Everything is fine (xtest and all) except that I no longer have any network interface.
That is, when running cat /etc/network/interfaces I get:
```
# interface file auto-generated by buildroot
auto lo
iface lo inet loopback
```
When I run # udhcpc I get: 

```
udhcpc: SIOCGIFINDEX: No such device
```
Upon restart, I get:

```
# /etc/init.d/S40network restart

Stopping network: ifdown: interface wlan0 not configured
OK
Starting network: Successfully initialized wpa_supplicant
nl80211: 'nl80211' generic netlink not found
Failed to initialize driver 'nl80211'
wlan0: Unsupported driver 'nl80211'
FAIL
```

How can I turn my wlan0 on?

p.s: I tried to update the interface conf file but no success. I suspect it has something to do with buildroot but honestly, I have no idea where to look.

p.s.2: I also tried to add following packages (with no success either): WPA_SUPPLICANT, WPA_SUPPLICANT_NL80211.

**Comment by jforissier** [comment]
Hi @vivinamartins16,

There are a number of things that need to be done in order to enable Wi-Fi: some kernel config, some buildroot config, and then some more configuration files. I managed to get it working though.

I'm still running a few tests to make sure I am not enabling more things than necessary, and I'll post something tomorrow. Stay tuned!

**Comment by jforissier** [comment]
https://github.com/OP-TEE/build/pull/386

**Comment by SilvaMatteus** [comment]
Thanks, @jforissier.

**Comment by vivinamartins16** [comment]
Thank you @jforissier!

**Comment by vivinamartins16** [comment]
Just an update: it didn't work for me until I add the following lines to common.mk:
```
BR2_PACKAGE_LINUX_FIRMWARE = y
BR2_PACKAGE_LINUX_FIRMWARE_TI_WL18XX = y
BR2_PACKAGE_WPA_SUPPLICANT = y
BR2_PACKAGE_WIRELESS_REGDB = y
```
for some reason, those lines in the hikey960.mk file didn't build with buildroot.

**Comment by jforissier** [comment]
@vivinamartins16 that's surprising. I don't see why you need to do that, it worked for me. I hope I can get more feedback on #386 to avoid merging something that does not work! ;-)

**Comment by jforissier** [comment]
I cloned the whole HiKey960 tree from scratch (`hikey960.xml`) then checked out build.git PR#386 (`56ec191 hikey960: enable Wi-Fi") and everything built fine.
```
$ mkdir tmp; cd tmp
$ repo init -u https://github.com/OP-TEE/manifest.git -m hikey960.xml
[...]
$ repo sync -j20
[...]
$ cd build
$ make toolchains
[...]
$ make -j10
[...]
$ find out-br/target -name wpa_supplicant -o -name regulatory.db -o -name wl18xx-fw-4.bin
out-br/target/usr/sbin/wpa_supplicant
out-br/target/lib/firmware/regulatory.db
out-br/target/lib/firmware/ti-connectivity/wl18xx-fw-4.bin
```

**Comment by SilvaMatteus** [comment]
@jforissier, it worked here.

Building from scratch,  I got a Wi-Fi connection working fine.

Thank you.

**Comment by jforissier** [comment]
@SilvaMatteus thanks for the feedback.
