### ISSUE TITLE
Hikey960 efuse driver for OP-TEE

### ISSUE THREAD

**Issue by vivinamartins16** [OP-TEE/optee_os#3307]
Hey all,

I'm having trouble migrating from RPi3 to Hikey960. I see in the schematics indications of efuses on page 5 and 12 (also in the Reference Manual, page 15 and 49) but no indication is given neither on how to access them, or how to burn them.

In OP-TEE there's a "place-holder" for HUK (which is not necessarily my main focus as of right now), but I see nothing on code related to efuses - only for imx6 boards.

Can anyone give me some hints on where to look or some similar implementation of an efuse driver for Hikey960?

Thanks in advance!

**Comment by vchong** [comment]
@vivinamartins16 As already mentioned in https://discuss.96boards.org/t/how-to-configure-efuses, efuse related info hasn't been made available to the public by the vendor.

**Comment by vivinamartins16** [comment]
Thanks @vchong !
