### ISSUE TITLE
gdb support in Trusted Applications

### ISSUE THREAD

**Issue by kurcha01-arm** [OP-TEE/optee_os#3308]
An older version of the repo contained instructions on how to debug with gdb. They were removed in this patch:
https://github.com/OP-TEE/optee_os/commit/76a5c33c9f65446e4b584ec7aaf16be96daf6b30

Now that the docs are on readthedocs, the debug section doesn't have any information about using gdb:
https://optee.readthedocs.io/en/latest/debug/index.html

Is gdb usable/supported for Trusted Applications?

**Comment by jbech-linaro** [comment]
I suppose [this](https://optee.readthedocs.io/en/latest/building/devices/qemu.html#gdb-secure-world) is what you are looking for. Having that said, that is fore TEE core and not TA's. But debugging TA's works fine on QEMU with GDB. Turn off ASLR when building. Load TA symbols and set then the breakpoint at the entry point and you're good to go.

For my own sake I've written a python plugin to gdb that makes life easier for me. Not you if it's useful or not, but you'll find it [here](https://github.com/Jyx/configs/blob/master/gdb-optee.py) (and some videos and instructions [here](http://people.linaro.org/~joakim.bech/optee-gdb-plugin/) showing it in action).

**Comment by kurcha01-arm** [comment]
Thanks Joakim,

I've added symbols from the [uuid].elf file and tried adding breakpoints but running the program (i.e. the Normal World program) doesn't stop when those functions are called in the TA. I tried disabling ASLR (on the build machine and the test machine?) but got the same results.

The interface between the NW program and the TA made me wonder if having a breakpoint in the TA wouldn't stop the NW program.

I've seen older versions of the docs that mention an offset for loading the symbols, relative to the .text section and load address of the [uuid].elf file. If that's needed then it might explain what I'm seeing but I'll need to change my setup to get the load address. The QEMU addresses in your plugin don't work for my hardware.

**Comment by jbech-linaro** [comment]
> The interface between the NW program and the TA made me wonder if having a breakpoint in the TA wouldn't stop the NW program.

I've never seen that happen.

> I've seen older versions of the docs that mention an offset for loading the symbols, relative to the .text section and load address of the [uuid].elf file. If that's needed then it might explain what I'm seeing but I'll need to change my setup to get the load address. 

Right, I think the offset always is `0x00000020`. In another script I use this ...

```bash
	# Grab the .text offset
	TA_TEXT_OFFSET=`readelf -S ${TA_FILE} | grep text | head -1 | awk '{print "0x"$5}'`
	# Add it to the load address
	TA_LOAD_ADDRESS=$((${TA_TEXT_OFFSET} + ${LOAD_ADDRESS}))
	echo "   add-symbol-file ${TA_FILE} `printf '0x%08x\n' ${TA_LOAD_ADDRESS}`"
```

> The QEMU addresses in your plugin don't work for my hardware.

With `LOAD_ADDRESS` set correctly (which varies a bit between builds) the above should work. I usually run a TA once and pay attention to the debug print on secure side that tells the load address. Then on subsequent runs it will still be the same, so that's the one that I use.

**Comment by kurcha01-arm** [comment]
Oddly this still isn't working for me. The debug output gives me:

```
D/TC:? 0 load_elf_from_store:791 ELF load address 0x40005000
```

And readelf on the TA ELF gives me:
```
Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .ta_head          PROGBITS         0000000000000000  00010000
       0000000000000020  0000000000000000  WA       0     0     8
  [ 2] .text             PROGBITS         0000000000000020  00010020
       000000000002604c  0000000000000000  AX       0     0     4
```
i.e. 0x00000020? (objdump gives me the same)

So my TA_LOAD_ADDRESS should be 0x40005020. But doing:

```
add-symbol-file [elf] 0x40005020
```
Then setting the breakpoints on functions I know are called (using the debug output on the secure side) still doesn't make it break. ASLR is still disabled. Have I made a mistake?

**Comment by jbech-linaro** [comment]
Everything looks correct to me.

> (I'm using the base fast model now)

Oh, I see. I've never tried GDB with fast model. I've only used it with QEMU (rock solid) and HiKey and Raspberry Pi 3, both with OpenOCD (a bit flaky).

**Comment by kurcha01-arm** [comment]
OK, I'll assume the FVP doesn't work then. Thankfully there are other ways of debugging for it.

Do you know if needing to change the load address is OP-TEE/TrustZone specific or if it's just something I didn't know about gdb?
