### ISSUE TITLE
Run OP-TEE application without sudo

### ISSUE THREAD

**Issue by Hacklog24** [OP-TEE/optee_os#3310]
Hi,
Is it possible to run an op-tee application such as "optee_example_hello_world" without sudo?

Thank you all!

**Comment by jforissier** [comment]
Hi @Hacklog24,

Yes, it is possible. For instance with [QEMU](https://optee.readthedocs.io/en/latest/building/devices/qemu.html):
```
Welcome to Buildroot, type root or test to login
buildroot login: test
$ id
uid=1001(test) gid=1003(test) groups=1001(teeclnt),1002(ion),1003(test)
$ optee_example_hello_world
Invoking TA to increment 42
TA incremented value to 43
$ 
```

**Comment by Hacklog24** [comment]
Hi @jforissier,

thank you! I'm using a Raspbian with OP-TEE support (https://github.com/benhaz1024/raspbian-tee) where I first load the driver and then run the application:

$ sudo tee-supplicant &
$ sudo optee_example_hello_world

Could there be a way to run without sudo? For example by changing the permissions of /dev?

**Comment by jforissier** [comment]
> Could there be a way to run without sudo? For example by changing the permissions of /dev?

Yes, exactly. Please check the permissions that we use with QEMU:
- https://github.com/OP-TEE/build/blob/master/br-ext/package/optee_client/optee_client.mk#L22-L31
- https://github.com/OP-TEE/build/blob/master/br-ext/package/optee_client/S30optee#L9-L51

We have used two user accounts, `tee` and `teeclnt`, but that's just one way of doing it.
