### ISSUE TITLE
Management of cancellation mask kept accross tasks

### ISSUE THREAD

**Issue by c-auger** [OP-TEE/optee_os#3313]
The GP Internal API specification states that the default for TA entry point is to have cancellation requests masked.

```
By default, tasks created to handle a TA entry point have cancellation masked, so that a TA does not have to cope with the effects of cancellation requests.
```
(Section 4.10.2 and 4.10.3)

I have my own implementation of the specification, and on it, I observed a difference in behavior concerning masking requests when running your tests.

In my interpretation, each time an entry point is called, the cancellation mask should be reset (active), whatever its value was at the end of previous entry point on the same session.

But when I read your test 1009, I see this kind of code:

```
TEE_Result TA_OpenSessionEntryPoint(uint32_t nParamTypes,
				    TEE_Param pParams[4],
				    void **ppSessionContext)
{
	(void)nParamTypes;
	(void)pParams;
	(void)ppSessionContext;
	DMSG("TA_OpenSessionEntryPoint");
	TEE_UnmaskCancellation();
	return TEE_SUCCESS;
}
<…>
TEE_Result TA_InvokeCommandEntryPoint(void *pSessionContext,
				      uint32_t nCommandID, uint32_t nParamTypes,
				      TEE_Param pParams[4])
{
	(void)pSessionContext;

	switch (nCommandID) {
<…>
	case TA_OS_TEST_CMD_WAIT:
		return ta_entry_wait(nParamTypes, pParams);
<…>
	default:
		return TEE_ERROR_BAD_PARAMETERS;
	}
}
```
(`optee_test/ta/os_test/os_test.c`)

```
TEE_Result ta_entry_wait(uint32_t param_types, TEE_Param params[4])
{
	TEE_Result res = TEE_SUCCESS;
	(void)param_types;

	printf("ta_entry_wait: waiting %d\n", (unsigned int)params[0].value.a);
	/* Wait */
	res = TEE_Wait(params[0].value.a);

	return res;
}
```
(`optee_test/ta/os_test/os_test.c`)

Thus, my implementation will always fail on test 1009 since the `TEE_UnmaskCancellations()` is called in `TA_OpenSessionEntryPoint()` but not in `TA_InvokeCommandEntryPoint()`.

As `TA_OpenSessionEntryPoint()` and `TA_InvokeCommandEntryPoint()` are two separate entry points, I think that the cancellation mask should be reset (active) between them.

Additionally, from my point of view, `TEE_UnmaskCancellations()` should be called just before `TEE_Wait()` inside of `TA_InvokeCommandEntryPoint()`.

**Comment by jenswi-linaro** [comment]
Do you know GPs interpretation of this? Mind that OP-TEE is passing the GP test suite.

**Comment by c-auger** [comment]
I know this, and all tests of GP test suite pass, because they call `TEE_UnmaskCancellations()` in the same entry point as `TEE_Wait()`, and this is conform to both my and OPTEE's understanding of GP specification.

The test which does not pas is `regression_1009` which is not part of GP test suite. This test follows a different pattern than GP test suite. The pattern that `regression_1009` follows does not conform to my understanding of the specification.

**Comment by jenswi-linaro** [comment]
It seems that the specification isn't completely clear on this, so it would be interesting to hear how GP thinks it should be interpreted.

**Comment by c-auger** [comment]
If you can contact them, please do so. The mail provided on the specification does not work (I have several comments to send them concerning several inconsistencies, such as for the seek function which now takes an unsigned integer as argument, and which behavior is stated to depend on whether or not that argument is negative).

**Comment by jforissier** [comment]
@c-auger I may be wrong but I don't think GP will consider requests from non-members anyways.
I can't find any public email address in the GP specs. I found secretariat@globalplatform.org in a white paper, though. Clearly not a technical point of contact :-/

**Comment by c-auger** [comment]
I was talking about `TEE Internal Core API Specification 1.2.1` which is a public release. On page 14, there is some paragraph:

```
If you are implementing this specification and you think it is not clear on something:
  1. Check with a colleague.
And if that fails:
  2. Contact GlobalPlatform at TEE-issues-GPD_SPE_010_v1.2.2@globalplatform.org
```

This mail address would seem adequate to me for technical point of contact if it did not return an error on my mailbox.

**Comment by jforissier** [comment]
Ah, that's interesting, it must be a new thing they are putting in place because it's not in the 1.2 version.
