### ISSUE TITLE
Multi instance support within secure storage?

### ISSUE THREAD

**Issue by limchacha** [OP-TEE/optee_os#3314]
I ask about Secure Storage.

I'm currently trying to use the Secure Storage feature of OPTEE.
In my project, there are several Linux applications and one TA.
That is, each CA calls openseesion and invoke command to one TA.
The current TA attribute is set to Multi-instance. (Multi-session is also set, but I know this is ignored.)

E/TA:  Property Name = gpd.ta.singleInstance, Property Value = false
E/TA:  Property Name = gpd.ta.multiSession, Property Value = true
E/TA:  Property Name = gpd.ta.instanceKeepAlive, Property Value = false

In the above situation, when CA_1 stores a file named "KeyA" in Secure Storage, it wants to prevent CA_2 from reading or overwriting "KeyA".
The code I used in TA is:

- Save
	TEE_ObjectHandle o = TEE_HANDLE_NULL;

	res = TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE_REE, 
									fName, 
									FILE_NAME_MAX_LEN, 
									TEE_DATA_FLAG_ACCESS_READ | TEE_DATA_FLAG_ACCESS_WRITE | TEE_DATA_FLAG_OVERWRITE | TEE_DATA_FLAG_ACCESS_WRITE_META,
									0,
									params[1].memref.buffer, 
									params[1].memref.size, 
									&o);

- Read
	TEE_ObjectHandle o = TEE_HANDLE_NULL;

	res = TEE_OpenPersistentObject(TEE_STORAGE_PRIVATE_REE, 
							fName, 
							FILE_NAME_MAX_LEN, 
							TEE_DATA_FLAG_ACCESS_READ,
							&o);

	res = TEE_ReadObjectData(o, params[1].memref.buffer, params[1].memref.size, &read_bytes);

Even though I did not use the SHARED option, the stored data is accessible from a CA other than the stored CA.

Can I isolate file access using a single TA as a multi-instance?

Is there a way to configure TA separately for each CA?

**Comment by jenswi-linaro** [comment]
Secure protects against concurrent accesses from multi-instance TAs to the same object, but there are no other way of keeping the different instances of the TA apart.

Currently there doesn't exist a standardized way of identifying different clients in normal world as the client identity always is the same (with the exception of certain recent kernel requests).

If you need to create object specific to a client you need to supply something client specific to the TA. One option could be to extend the usage of `connectionMethod` and `connectionData` in `TEEC_OpenSession()`, but that could be tricky to get upstream depending on how useful your use case seems to be to others. So the easiest way forward for you would probably be to just supply something directly by the client.
