### ISSUE TITLE
Missing LTC fix (AES rounds check)?

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3322]
I'm surprised that optee_os master does not have https://github.com/libtom/libtomcrypt/commit/7b4a5c1dcf2803e9c6cbcbc2458db9317e6fb8ca ("check range in _rijndael_ecb_ functions"). The patch was merged in upstream LTC on September 4. Should we cherry-pick it?

**Comment by jbech-linaro** [comment]
> Should we cherry-pick it?

Yes, this should also be in the 3.7.0 release. I'll do the cherry-pick dance with this patch too. Stay tuned!

**Comment by jbech-linaro** [comment]
https://github.com/OP-TEE/optee_os/pull/3324 for import branch, will post for master once we've merged the one for the import branch.

**Comment by jbech-linaro** [comment]
https://github.com/OP-TEE/optee_os/pull/3325 for master.

**Comment by jforissier** [comment]
All good, merged, thanks!
