### ISSUE TITLE
Specification for OP-TEE?

### ISSUE THREAD

**Issue by Yvesyingyi** [OP-TEE/optee_os#3323]
Hello!

As a school project, I would like to go through a formal code review with a proof assistant ([Isabelle](https://en.wikipedia.org/wiki/Isabelle_(proof_assistant))) to verify the safetyness of OP-TEE. The whole process should be pretty similiar to [the proofs of seL4 kernel](https://github.com/seL4/l4v). But as of now, I don't have a clear image of how to define "secure" or "trusted" in the context of the project, nor did I find any list that specifies each of the security goals for OP-TEE. Are there any specifications for the project so that I can build my proof for? Any help is appreciated.

**Comment by jbech-linaro** [comment]
Hi @Yvesyingyi , I'm afraid that you're out of luck here. All documentation that we have can be found at https://optee.readthedocs.io. Please note that OP-TEE implements a couple of different GlobalPlatform specifications. You'll find those here: https://optee.readthedocs.io/en/latest/architecture/globalplatform_api.html

Unfortunately I don't really know what kind of other information we could provide at this point.

**Comment by Yvesyingyi** [comment]
Thank you Bech! I'll take a look at GlobalPlatform specifications.
