### ISSUE TITLE
Secure dirver read/write HW register cause core data-abort.

### ISSUE THREAD

**Issue by karmen27** [OP-TEE/optee_os#3326]
Hi, all
	I am working on a project that implements a cipher driver, which needs to config some register.
However, I face this issue when I try to write a uint32_t value into a register.
I have tried  #3236 , #1343, to register a base_address of HW, like this 
register_phys_mem(MEM_AREA_IO_SEC, CIPHERHWA_BASE, 0x1000);
or this 
register_phys_mem(MEM_AREA_IO_NSEC, CIPHERHWA_BASE, 0x1000);
but all of those didn’t work. 
CIPHERHWA_BASE is a base address that is 0xFA500000.
Part of log as below:
E/TC:0 0 Core data-abort at address 0xfa500808 (translation fault)
E/TC:0 0  esr 0x96000045  ttbr0 0xbd09e000   ttbr1 0x00000000   cidr 0x0
E/TC:0 0  cpu #0          cpsr 0x60000104
E/TC:0 0  x0  00000000fa500808 x1  0000000000000000
E/TC:0 0  x2  00000000bd041a94 x3  00000000bd0a4ed5
E/TC:0 0  x4  00000000bd0a4dc0 x5  0000000000000001
E/TC:0 0  x6  00000000bd06e948 x7  0000000000000000
E/TC:0 0  x8  0000000000000000 x9  0000000000000000
E/TC:0 0  x10 0000000000000000 x11 0000000000000000
E/TC:0 0  x12 0000000000000000 x13 0000000000000000
E/TC:0 0  x14 0000000000000000 x15 0000000000000000
E/TC:0 0  x16 0000000000000000 x17 0000000000000000
E/TC:0 0  x18 0000000000000000 x19 0000000000000000
E/TC:0 0  x20 0000000000000000 x21 0000000000000000
E/TC:0 0  x22 0000000000000000 x23 0000000000000000
E/TC:0 0  x24 0000000000000000 x25 0000000000000000
E/TC:0 0  x26 0000000000000000 x27 0000000000000000
E/TC:0 0  x28 0000000000000000 x29 00000000bd0a5010
E/TC:0 0  x30 00000000bd041e68 elr 00000000bd041b24
E/TC:0 0  sp_el0 00000000bd0a5000
E/TC:0 0 Call stack:
E/TC:0 0  0x00000000bd041b24
E/TC:0 0  0x00000000bd0218b8
E/TC:0 0  0x00000000bd021a54
E/TC:0 0  0x00000000bd006934
E/TC:0 0  0x00000000bd027ffc
E/TC:0 0  0x00000000bd01f51c
E/TC:0 0  0x00000000bd01fba0
E/TC:0 0  0x00000000bd00bf34
E/TC:0 0  0x00000000bd002970
E/TC:0 0 Panic 'unhandled pageable abort' at core/arch/arm/kernel/abort.c:640 <abort_handler>
E/TC:0 0 Call stack:
E/TC:0 0  0x00000000bd012434

So please someone could help me thank you very much.

**Comment by jforissier** [comment]
Hi @karmen27 ,

Can you see a mapping is effectively created in the debug log? Please check and/or post the lines containing add_phys_mem and dump_mmap_table, right after boot. They have "debug" severity so you need to build with CFG_TEE_CORE_LOG_LEVEL=3 or higher.

**Comment by jenswi-linaro** [comment]
From the abort it looks like you using the physical address directly, you need to translate it into a virtual address first. IO addresses are normally not identity mapped.

**Comment by karmen27** [comment]
Hi, @jforissier 
Thanks your answer. 
Yes, I have checked that mapping is effective.

**Comment by karmen27** [comment]
Hi, @jenswi-linaro 
yes, you are right. I try to access the physical address directly. It's work when I convert it into a virtual address and access to the virtual address.
Thanks for your help.
