### ISSUE TITLE
Tune the mempool size

### ISSUE THREAD

**Issue by 1flurry** [OP-TEE/optee_os#3328]
Hi：
I want to test RSA's signature function. But when I run the test function，there is an error in NW：
    TEEC_InvokeCommand failed: 0xffff302
And SW shows that：   
    mempool_alloc:197 Failed to allocate 544 bytes, please tune the pool size
So how can I tune the pool size？Could you please help with the process.？
Thanks！
1flurry

**Comment by jforissier** [comment]
Hi @1flurry ,

Perhaps you need to increase `LTC_VARIABLE_NUMBER` in `core/lib/libtomcrypt/mpa_desc.c` or `MPI_MEMPOOL_SIZE` in `core/lib/libtomcrypt/mpi_desc.c`, depending on whether you are using one or the other.

It could also be that you have changed something and you now have a memory leak.

**Comment by 1flurry** [comment]
OK，I will have a try.
Thank you very much！
