### ISSUE TITLE
NO /dev/tee* device in technexion pico-pi-imx7 board in yocto project  

### ISSUE THREAD

**Issue by gitgonewithwind** [OP-TEE/optee_os#3332]
I have opened an issue here:  https://github.com/TechNexion/edm-yocto-bsp/issues/22
but nobody to answer me, so I open here again:
In yocto local.conf I added:  DISTRO_FEATURES_append=" optee"
IMAGE_INSTALL_append = " optee-client-imx optee-os-imx-tn optee-test-imx"
and
config CONFIG_OPTEE in kernel config,but I still can not find the device /dev/tee ?

any suggestion? how can I do? individually to build kernel,boot and rootfs? 
Thanks

error:

ls /dev/tee*
ls: cannot access '/dev/tee*': No such file or directory
fortress:/usr/include# xtest
Run test suite with level=0

TEE test application started with device [(null)]
Failed to open TEE context: 0xffff0008
fortress:/usr/include# tee-supplicant
ERR [576] TEES:main:663: failed to find an OP-TEE supplicant device
fortress:/usr/include#

**Comment by jforissier** [comment]
Hi @gitgonewithwind ,

Does `dmesg | grep optee` return something? I suspect the OP-TEE driver is not probed because the `optee` node may be missing from your DTB, see [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v5.4-rc3&id=14e21cb8f811).

**Comment by gitgonewithwind** [comment]
@jforissier 
Thank you for your reply so soon.
nothing return.

---------
fortress:/home/myuser# dmesg | grep optee                                       
fortress:/home/myuser# 


--------------
one more question: do you know pico-pi-imx7 board support optee?

I find the git log in meta-edm-bsp-release ,showing that "Currently, only NXP EVK boards support OPTEE OS"

Author: Richard Hu <richard.hu@technexion.com>
Date:   Fri Aug 31 13:18:05 2018 +0800

    patches: optee-os-imx: update patch to avoid build failure
    
    Currently, only NXP EVK boards support OPTEE OS.
    If a new board isn't supported by OPTEE OS, the new recipe will assign a default
    supported board name by SOC type to pass it to build OPTEE to avoid build failure.

**Comment by gitgonewithwind** [comment]
> Hi @gitgonewithwind ,
> 
> Does `dmesg | grep optee` return something? I suspect the OP-TEE driver is not probed because the `optee` node may be missing from your DTB, see [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v5.4-rc3&id=14e21cb8f811).


@jforissier 
if my board missing DTB, I need patch the DTB in my board own dts file NOT exactly same as your link file  hi6220-hikey.dts ? 
if that let me try to patch my onw dts file.

**Comment by gitgonewithwind** [comment]
@jforissier 
I find in my board  file imx7d-pico-qca_pi.dts  including: imx7d.dtsi 
in imx7d.dtsi , I find 
163                 ocram_optee {
164                         compatible = "fsl,optee-lpm-sram";
165                         reg = <0x00180000 0x8000>;
166                         overw_reg = <&ocrams_ddr 0x00904000 0x1000>,
167                                         <&ocram 0x00905000 0x1b000>,
168                                         <&ocrams 0x00900000 0x4000>;
169                         overw_clock = <&ocrams &clks IMX7D_OCRAM_CLK>;
170                 };

so Maybe the issue is not here?

**Comment by jforissier** [comment]
> if my board missing DTB, I need patch the DTB in my board own dts file NOT exactly same as your link file hi6220-hikey.dts ?

Correct.

> in imx7d.dtsi , I find
> 163 ocram_optee {
> 164 compatible = "fsl,optee-lpm-sram";
> 165 reg = <0x00180000 0x8000>;
> 166 overw_reg = <&ocrams_ddr 0x00904000 0x1000>,
> 167 <&ocram 0x00905000 0x1b000>,
> 168 <&ocrams 0x00900000 0x4000>;
> 169 overw_clock = <&ocrams &clks IMX7D_OCRAM_CLK>;
> 170 };

No, this is different. This seems to be a node used by some downstream OP-TEE driver.
You need to add the node: `/firmware/optee`, exactly like so:
```
/ {
	...
	firmware {
		optee {
			compatible = "linaro,optee-tz";
			method = "smc";
		};
	};
	...
};
```

**Comment by jforissier** [comment]
@gitgonewithwind I'm sorry but I realize what I said is just wrong :-/

The `optee` node is normally added by OP-TEE itself during its initialization, and before the Linux kernel is booted.

Do you see any message from OP-TEE on the secure UART?

**Comment by gitgonewithwind** [comment]
@jforissier 
Thank you so much.
I am going to try.
I will submit my results

**Comment by gitgonewithwind** [comment]
> @gitgonewithwind I'm sorry but I realize what I said is just wrong :-/
> 
> The `optee` node is normally added by OP-TEE itself during its initialization, and before the Linux kernel is booted.
> 
> Do you see any message from OP-TEE on the secure UART?

which is he secure UART?
I do not find any words including "optee"  from my minicom terminal?

**Comment by gitgonewithwind** [comment]
> @gitgonewithwind I'm sorry but I realize what I said is just wrong :-/
> 
> The `optee` node is normally added by OP-TEE itself during its initialization, and before the Linux kernel is booted.
> 
> Do you see any message from OP-TEE on the secure UART?

you mean I do NOT need patch my dts?
where is the secure UART?  I do not find any words including "optee" from my normal minicom terminal except tee-supplicant to output word: optee?


In my understanding if  after adding 
DISTRO_FEATURES_append=" optee"
IMAGE_INSTALL_append = " optee-client-imx optee-os-imx-tn optee-test-imx"

the yocto wuold auto reconfig CONFIG_OPTEE in kernel config, but it DID NOT, I patched it by myself. so I think maybe the board company TechNexion's porting is wrong somewhere. I asked them  the my first posting link, but nobody to answer to me.

**Comment by jforissier** [comment]
> which is the secure UART?

It is platform-specific, but by default it is the same as the non-secure console. You can set it in the DTB, in `/secure-chosen/stdout-path`, see [secure.txt](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings/arm/secure.txt?h=v5.4-rc3).
Make sure OP-TEE is built with CFG_TEE_CORE_LOG_LEVEL=2 or more (use 3 for debug traces).
In case you don't know you can check your DT at runtime in the sysfs pseudo-filesystem, typically under `/sys/firmware/devicetree/base`.

**Comment by jforissier** [comment]
> you mean I do NOT need patch my dts?

Correct. You should not need to patch it.

> the yocto should auto reconfig CONFIG_OPTEE in kernel config,

Sorry but I don't know the Yocto environment and even less the one that you are using :-(

**Comment by gitgonewithwind** [comment]
@jforissier 
Thank you so much.
let me keep searching.
anybody any more ideas ?

**Comment by jenswi-linaro** [comment]
> The optee node is normally added by OP-TEE itself during its initialization, and before the Linux kernel is booted

Not entirely true, this is platform dependent. Right now I think it's only the QEMU ports (v8 and v7 virt) which are doing this. So yes, you need to modify/replace you DTB of the `firmware/optee` isn't there already.

**Comment by jforissier** [comment]
>> The optee node is normally added by OP-TEE itself during its initialization, and before the Linux >> kernel is booted

> Not entirely true, this is platform dependent.

Inded, you're right. It's rather inconvenient :-/

**Comment by gitgonewithwind** [comment]
> > The optee node is normally added by OP-TEE itself during its initialization, and before the Linux kernel is booted
> 
> Not entirely true, this is platform dependent. Right now I think it's only the QEMU ports (v8 and v7 virt) which are doing this. So yes, you need to modify/replace you DTB of the `firmware/optee` isn't there already.

-----
so you mean I still need add at dts like this:
/ {
	...
	firmware {
		optee {
			compatible = "linaro,optee-tz";
			method = "smc";
		};
	};
	...
};



the company a Technexion engineer tell me they idn't add custom config for PICO-IMX7 in OP-TEE yet. so the yocto source code  do not support it. I think there are a lot of work to do  in the yocto project for me. it's not simply to modify the dts ,isn't it?

**Comment by gitgonewithwind** [comment]
I config kernel  is like below, and I checked file dtb  included root dts file   imx7d.dtsi in which I find the optee config, but I still  can not find  /dev/tee* 

and I want to know how to porting u-boot source code? 

any idea?



kernel config:
======
# TEE drivers
#
CONFIG_OPTEE=y

#
# Firmware Drivers
#



dtsi:
=====

               ocram_optee {
                        compatible = "fsl,optee-lpm-sram";
                        reg = <0x00180000 0x8000>;
                        overw_reg = <&ocrams_ddr 0x00904000 0x1000>,
                                        <&ocram 0x00905000 0x1b000>,
                                        <&ocrams 0x00900000 0x4000>;
                        overw_clock = <&ocrams &clks IMX7D_OCRAM_CLK>;
                };



===
fortress:/home/myuser# ls /dev/tee*                                             
ls: cannot access '/dev/tee*': No such file or directory
