### ISSUE TITLE
Secure Boot Hikey960 - how it works?

### ISSUE THREAD

**Issue by vivinamartins16** [OP-TEE/optee_os#3338]
Hey all!

I am trying to setup OP-TEE 3.7.0 on my hikey960 with TBB (Trusted Board Boot) support. In my MakeFile I set the TF-A flags for that:
```
TF_A_FLAGS ?= \
	BL32=$(OPTEE_OS_HEADER_V2_BIN) \
	BL32_EXTRA1=$(OPTEE_OS_PAGER_V2_BIN) \
	BL32_EXTRA2=$(OPTEE_OS_PAGEABLE_V2_BIN) \
	BL33=$(EDK2_BIN) \
	SCP_BL2=$(MCUIMAGE_BIN) \
	DEBUG=$(DEBUG) \
	PLAT=hikey960 \
	SPD=opteed \
        MBEDTLS_DIR=$(TF_A_PATH)/../mbedtls/ \
        TRUSTED_BOARD_BOOT=1 \
        GENERATE_COT=1
```
All my .bin and .crt were created. So far, so good.
The problem is, when I boot the board, I don't see any ARM trusted Firmware indications that TBB is being executed (Like in RPI3, where it states when each BL is verified). Instead, I get:

```
hikey960 boarid:5301 xloader use UART6
scsysstat_value[0].
clear reset source
last_keypoint0,reboot_type0
secdbg not DCU.
SecDbgVer exit

 xloader chipid is: 0x36600110, start at 355ms.
Build Date: Dec  6 2017, 15:31:59
[clock_init] ++
hikey960 [hikey960_clk_init]
hi3660 [clk_setup]
[clock_init] --
storage type is UFS
ufs retry: 6 count v_tx:0 v_rx:0
ufs set v_tx:0 v_rx:0
Hikey960[5301] no need avs_init.
ddr ft:0xf20332a3,mode:1 target:4
UceLdOk

...

iomcu_subsys_init
boot_c0 PROFILE 4
slave0 irq0:0x00000014
NOTICE:  BL2: v2.0(release):v2.0-507-g34efb683
NOTICE:  BL2: Built : 11:25:31, Oct 22 2019
NOTICE:  ufs: H**** device must set VS_DebugSaveConfigTime 0x10
NOTICE:  BL2: Booting BL31
NOTICE:  BL31: v2.0(release):v2.0-507-g34efb683
NOTICE:  BL31: Built : 11:25:31, Oct 22 2019
D/TC:0 0 add_phys_mem:576 TEE_SHMEM_START type NSEC_SHM 0x3ee00000 size 0x00200000
D/TC:0 0 add_phys_mem:576 TA_RAM_START type TA_RAM 0x3f200000 size 0x00e00000
D/TC:0 0 add_phys_mem:576 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x3f05e000 size 0x001a2000
D/TC:0 0 add_phys_mem:576 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x3f000000 size 0x0005e000
D/TC:0 0 add_phys_mem:576 ROUNDDOWN(0xFFF32000, CORE_MMU_PGDIR_SIZE) type IO_NSEC 0xffe00000 size 0x00200000
D/TC:0 0 verify_special_mem_areas:520 SDP memory [3e800000 3ec00000]
```

tl,dr; **Question**: Is this the expected output for TBB?

**Comment by vchong** [comment]
I haven't tried this myself but from the original TBB PR (https://github.com/ARM-software/arm-trusted-firmware/pull/1555), `SAVE_KEYS=1` was included in the flags. This wasn't used for hikey620 and rpi3, but you might want to try it anyway just to see if it makes a difference. Also, did you redo the recovery process (e.g. `make recovery`) after the build?

**Comment by vchong** [comment]
So I got some logs from a colleague (see attached). You might need to increase the log level and then look for something like `Loading image id=7` which corresponds to `TRUSTED_KEY_CERT_ID` in `include/common/tbbr/tbbr_img_def.h` to confirm TBB is executing.

![picturemessage_ccnsdpk1 w1p](https://user-images.githubusercontent.com/7334750/67449843-832e9800-f656-11e9-942e-2065af280a63.png)
![picturemessage_dzcrm1xb hmv](https://user-images.githubusercontent.com/7334750/67449844-832e9800-f656-11e9-9f56-b14bf3d7284d.png)
![picturemessage_zs0a3xju vyl](https://user-images.githubusercontent.com/7334750/67449848-83c72e80-f656-11e9-9361-79545c4770f1.png)
![picturemessage_hkcdkggc pbn](https://user-images.githubusercontent.com/7334750/67449846-83c72e80-f656-11e9-9903-a7c5dfed4ff2.png)
![picturemessage_5qhv5aad tns](https://user-images.githubusercontent.com/7334750/67449842-832e9800-f656-11e9-8114-ec363ad11d05.png)

**Comment by vivinamartins16** [comment]
Thanks @vchong ! That will help me a lot! 
Indeed, I never set the `SAVE_KEYS=1` - it must be the problem.
And no, I didn't run the `make recovery` again after build, but I will try it and post here the results.

Thanks!

**Comment by vivinamartins16** [comment]
Hey @vchong ! It worked perfectly! Thanks ;)

**Comment by vchong** [comment]
@vivinamartins16 You're welcome, but do you mind explaining what worked? `SAVE_KEYS=1` or `make recovery` or both?

**Comment by vivinamartins16** [comment]
> @vivinamartins16 You're welcome, but do you mind explaining what worked? `SAVE_KEYS=1` or `make recovery` or both?

Sure! No problem! `SAVE_KEYS=1` did the job. 
I believe something went wrong with `make recovery`, so I just added the flag and rebuild in another Hikey, completely clean, and it worked without make recovery at all.
I didn't test `make recovery` again, since it worked without it.

**Comment by vchong** [comment]
Ok. Thanks for the explanation! Glad you got it to work.
