### ISSUE TITLE
Panic 'Failed to spread pgdir on small tables' 

### ISSUE THREAD

**Issue by karmen27** [OP-TEE/optee_os#3339]
Panic 'Failed to spread pgdir on small tables' at core/arch/arm/mm/core_mmu.c:1521 <core_mmu_map_pages>

Hi, all
	I was suffering the above issue when I trying to use a buffer to do some work in TEE.
After doing some tests, I have found that the buffer size is too large, which is about 15M. it works when I reduced the buffer size to 8M. 
So I want to know where I can configure the shared memory size. 
And I have tried to do some changes, such as change the TEE_SHMEM_START and TEE_SHMEM_SIZE, but it doesn’t work well.
register_phys_mem(MEM_AREA_NSEC_SHM, TEE_SHMEM_START, TEE_SHMEM_SIZE);
or the other place to configure the table/pgdir size?
Someone could help me or give me some hints, thank you very much.

**Comment by jenswi-linaro** [comment]
Do you get any "xlat tables used xx / xx" in the log?
Any way, you could try increasing `MAX_XLAT_TABLES`.
If that doesn't work, try to figure out where `core_mmu_entry_to_finer_grained()` fails by narrowing it down with prints etc.

**Comment by karmen27** [comment]
@jenswi-linaro yes, I have tried to define MAX_XLAT_TABLES equal to 8, but it doesn't work, I will post the whole log after I do some test again.

**Comment by karmen27** [comment]
@jenswi-linaro 
Sorry for replying later, logs as below.
D/TC:0 0 tee_entry_std:572 arg->params[0].u.rmem.shm_ref = bc7806e0, arg->params[0].u.rmem.size = f48000
D/TC:? 0 entry_invoke_command:376 enter
D/TC:? 0 tee_ta_invoke_command:651 enter
D/TC:? 0 pseudo_ta_enter_invoke_cmd:187 enter
D/TC:0 0 mobj_reg_shm_inc_map:656 enter
D/TC:0 0 core_mmu_map_pages:1495 enter
D/TC:0 0 core_mmu_entry_to_finer_grained:808 xlat tables used 5 / 8
D/TC:0 0 core_mmu_entry_to_finer_grained:808 xlat tables used 6 / 8
D/TC:0 0 core_mmu_entry_to_finer_grained:808 xlat tables used 7 / 8
D/TC:0 0 core_mmu_entry_to_finer_grained:808 xlat tables used 8 / 8
E/TC:0 0 Panic 'Failed to spread pgdir on small tables' at core/arch/arm/mm/core_mmu.c:1522 <core_mmu_map_pages>
E/TC:0 0 Call stack:
E/TC:0 0  0x00000000bd012b48
E/TC:0 0  0x00000000bd0277bc
E/TC:0 0  0x00000000bd016788
E/TC:0 0  0x00000000bd01d788
E/TC:0 0  0x00000000bd006b48
E/TC:0 0  0x00000000bd006fb8
E/TC:0 0  0x00000000bd029060
E/TC:0 0  0x00000000bd01fdd0
E/TC:0 0  0x00000000bd02054c
E/TC:0 0  0x00000000bd00c648
E/TC:0 0  0x00000000bd002970

**Comment by karmen27** [comment]
In addition, tee_shm_register() is ok when I define CFG_CORE_HEAP_SIZE ?= 131072 in conf.mk. If not, it will failed during tee_shm_register().

**Comment by karmen27** [comment]
I have tried to increase MAX_XLAT_TABLES until 12, it is run well. thank you @jenswi-linaro . I will close this issue.
