### ISSUE TITLE
 TypeError: unsupported operand type(s) for %: 'bytes' and 'int'

### ISSUE THREAD

**Issue by gitgonewithwind** [OP-TEE/optee_os#3343]
I try to comiple verion(SRCREV="f398d4923da875370149ffee45c963d7adb41495")  optee in opensuse-42.3  but error:
I did not find solution on internet? need update python?
thanks.

.........................

Traceback (most recent call last):
|   File "scripts/gen_ldelf_hex.py", line 103, in <module>
|     main()
|   File "scripts/gen_ldelf_hex.py", line 94, in main
|     emit_load_segments(elffile, outf)
|   File "scripts/gen_ldelf_hex.py", line 48, in emit_load_segments
|     outf.write(b'const uint8_t ldelf_data[%d]' % round_up(load_size, 4096))
| TypeError: unsupported operand type(s) for %: 'bytes' and 'int'
| mk/subdir.mk:158: recipe for target '/opt/oe/configs/imx7/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/optee-os-imx-tn/git-r0/build.mx7dpico_mbl/core/ldelf_hex.c' failed
| make: *** [/opt/oe/configs/imx7/edm_yocto/build-x11-pico-imx7/tmp/work/cortexa7hf-neon-poky-linux-gnueabi/optee-os-imx-tn/git-r0/build.mx7dpico_mbl/core/ldelf_hex.c] Error 1

**Comment by jbech-linaro** [comment]
This is a Yocto build, something that [we (as core team) don't really do](https://optee.readthedocs.io/en/latest/building/gits/build.html#how-do-i-build-using-aosp-openembedded). But most likely it's a missing Python package. Please ensure that you have all [prerequisites](https://optee.readthedocs.io/en/latest/building/prerequisites.html) installed before trying to build OP-TEE.

**Comment by gitgonewithwind** [comment]
@jbech-linaro  thanks. I am going to do

**Comment by gitgonewithwind** [comment]
fixed close

**Comment by gitgonewithwind** [comment]
done. thanks
