### ISSUE TITLE
trusted root 

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3345]
What is trusted root or how can I know what is the trusted root of secure boot, secure storage or trusted applications?

**Comment by wamserma** [comment]
Please have a look at this presentation. It has also links for further reading at the end.
https://de.slideshare.net/linaroorg/secure-boot-on-arm-systems-building-a-complete-chain-of-trust-upon-existing-industry-standards-using-opensource-firmware-sfo17201
