### ISSUE TITLE
Secure provisioning of keys and TAs into OP TEE secure storage

### ISSUE THREAD

**Issue by mtuple** [OP-TEE/optee_os#3346]
I have some keys and some TAs with sensitive IP that have to be provisioned into secure storage. I'm trying to find a way to do this securely (with a linux REE). 

Since secure storage uses device-specific keys, we cannot pre-encrypt them off-device.

In production, the entire firmware will be copied into an eMMC as a binary blob. A special, one-time bootloader would then configure any functions (e.g. secure boot) that use device specific keys on first boot; however, since OP TEE requires the TEE supplicant for access to storage, this doesn't really work for OP TEE provisioning. 

Are there any standard practices for secure provisioning into OP TEE secure storage? or any options from similar use cases that you could suggest?

For reference I'm on AArch64, OP TEE is stored-encrypted in a dedicated partition on the eMMC (using hardware-protected keys) and executed fully in TZSRAM (no pager).

Thanks

**Comment by b49020** [comment]
@mtuple Have a look at PR: https://github.com/OP-TEE/optee_os/pull/3340 that adds support for pre-encrypted REE-FS TAs.

> For reference I'm on AArch64, OP TEE is stored-encrypted in a dedicated partition on the eMMC (using hardware-protected keys) and executed fully in TZSRAM (no pager).

In this case, you can have the TA decryption key embedded into encrypted OP-TEE binary which can allow your provisioning TA to be encrypted. And then you can have your secrets embedded into provisioning TA that you would like to provision into the secure storage.

**Comment by mtuple** [comment]
Thanks @b49020 , We ended up doing something very similar. Encrypt TAs using a key that is stored with the OP TEE binary, but rather than use them directly, use a pseudo TA to decrypt and then install them as normal secure storage TAs. This way we don't have to touch any existing OP TEE code.
