### ISSUE TITLE
About the __aeabi_xxxx in optee_os

### ISSUE THREAD

**Issue by sticfeynman** [OP-TEE/optee_os#3350]
Hi,
I found the implementation was not ideal in optee_os, to put it into perspective, the performance of those in libgcc.a is much better. This deficiency reveals remarkably in the RSA key-pair generation process. I wounder why the replacement is necessary when libgcc.a is already involved in the linkage of tee.elf.
And, is it possible to add a link to libgcc.a as well in ta_dev_kit.mk?

**Comment by sticfeynman** [comment]
Just thinking out loud, I can realize the reason avoiding using those higher level C APIs. For those ARM's EABI things, i.e. these compiler helpers, I would say, it's advisable to use the native (I guess they are supported by ARM) even for the bare-metal environment. 
I see your some "could depend on running in a non-bare metal". In my case, it needs a raise() implementation which is used in __aeabi_idiv0 and __aeabi_ldiv0 that is described in "4.3.2 Division by zero" in ARM's runtime ABI document. I recall these two functions are both weak in libgcc.a and it's quite easy to implement them by following the suggestions in the official document. For me, I just put a panic() statement (TEE_Panic() in the user mode) in the raise().
From my limited experience, it's very likely to stick to one TEE's toolcahin and let REE one by project's choice.

**Comment by jenswi-linaro** [comment]
@jforissier @sticfeynman, yes I think it was to be a bit more flexible with which toolchain was used to compile OP-TEE, just as the Linux kernel can be compiled with a Linux user mode toolchain. 

However, if there's a performance penalty we shouldn't do it. Or at least it should be possible to use the `libgcc.a` functions instead when using a bare metal toolchain.
