### ISSUE TITLE
How to run hello world example in QEMU 

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3355]
i do not understand why not see Hello world! and goobye in te segure wold.
what is wrong?
![normal_World](https://user-images.githubusercontent.com/30496643/67767213-704e0600-fa50-11e9-8469-4f3379e02931.PNG)
![secure_world](https://user-images.githubusercontent.com/30496643/67767214-70e69c80-fa50-11e9-8897-ddc2488481b6.PNG)

**Comment by jforissier** [comment]
Perhaps you need `CFG_TEE_TA_LOG_LEVEL=2`.

**Comment by 21212124** [comment]
its correct, thanks
