### ISSUE TITLE
secure boot

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3356]
To enable the authentication framework, the following steps should be followed according to **user-guide.rst**. For more details about the authentication framework, please see **auth-framework.rst** and **trusted-board-boot.rst**.

What steps should be followed?

**Comment by Emantor** [comment]
Secure boot always depends on the board you are using, i.e. for NXP boards you need to look into High Assurance Boot (HAB). Other vendors provide more or less publibly available information.

**Comment by 21212124** [comment]
i am use arm_v8 on qemu. where can I find the steps to compile TR-A?

**Comment by Emantor** [comment]
The links in OP-TEEs docs are broken, I send out a pull request to fix this. Meanwhile you can find the referenced files at the https://github.com/ARM-software/arm-trusted-firmware/tree/master/docs directory and its subfolders.

**Comment by 21212124** [comment]
thanks!

**Comment by 21212124** [comment]
thanks!
