### ISSUE TITLE
There is no rule to build the objective

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3358]
i do not understand the error when execute qemu (make run)
![Error](https://user-images.githubusercontent.com/30496643/67939012-f1cca200-fbd0-11e9-9062-e41a0ec2beb4.PNG)

i use qemu_v8
i following these instructions: 
[https://trustedfirmware-a.readthedocs.io/en/latest/getting_started/user-guide.html#building-tf-a](https://trustedfirmware-a.readthedocs.io/en/latest/getting_started/user-guide.html#building-tf-a)
My arm flags are as it follows:

`ARM_TF_FLAGS ?= \`
	`BL32=$(OPTEE_OS_HEADER_V2_BIN) \`
	`BL32_EXTRA1=$(OPTEE_OS_PAGER_V2_BIN) \`
	`BL32_EXTRA2=$(OPTEE_OS_PAGEABLE_V2_BIN) \`
	`BL33=$(EDK2_BIN) \`
	`MBEDTLS_DIR=$(ARM_TF_PATH)/mbedtls \`
	`PLAT=qemu \`
	`ARM_TSP_RAM_LOCATION=tdram \`
	`BL32_RAM_LOCATION=tdram \`
	`SPD=opteed \`
	`TRUSTED_BOARD_BOOT=1 \`
	`GENERATE_COT=1 \`
	`ARM_ROTPK_LOCATION=devel_rsa \`
	`ROT_KEY=$(ARM_TF_PATH)/plat/arm/board/common/rotpk/arm_rotprivk_rsa.pem`

**Comment by jbech-linaro** [comment]
> i do not understand the error.

Neither do I, but on the other hand I don't speak Italian? :) What are you actually trying to do? You've just pasted a random build error with no other context.

What device? What instructions are you following? What was the command that triggered the error?

Btw, instead of posting screenshots, please just pipe the build log to a file and paste the file at some pastebin like service (https://paste.ubuntu.com or https://bpaste.net to give two examples).
```
$ make 2>&1 | tee build.log
```

**Comment by 21212124** [comment]
this is the execution code:

[https://bpaste.net/show/roca2](url)

**Comment by jbech-linaro** [comment]
Thanks for the log, now I just need answers to:

1. What device?
2. What instructions are you following?
3. What was the command that triggered the error?
3.1. Was is the first line in the log you linked to? I.e., you actually manually crafted that long line?

**Comment by 21212124** [comment]
1.- i use qemu_v8
2.- [https://trustedfirmware-a.readthedocs.io/en/latest/getting_started/user-guide.html#building-tf-a](url)
3.- when execute qemu (make run)
   3.1.-I added this code:
`MBEDTLS_DIR=$(ARM_TF_PATH)/mbedtls \`
`SPD=opteed \`
`TRUSTED_BOARD_BOOT=1 \`
`GENERATE_COT=1 \`
`ARM_ROTPK_LOCATION=devel_rsa \`
`ROT_KEY=$(ARM_TF_PATH)/plat/arm/board/common/rotpk/arm_rotprivk_rsa.pem`

**Comment by vchong** [comment]
Please read #3131 again carefully. You don't have all the right flags set.

**Comment by jbech-linaro** [comment]
> 1.- i use qemu_v8

Ok and you have had a full OP-TEE QEMU v8 solution up and running without modifications? I.e., where xtest passed?

> 2.- https://trustedfirmware-a.readthedocs.io/en/latest/getting_started/user-guide.html#building-tf-a
> 3.- when execute qemu (make run)
> 3.1.-I added this code:
> `MBEDTLS_DIR=$(ARM_TF_PATH)/mbedtls \`
> `SPD=opteed \`
> `TRUSTED_BOARD_BOOT=1 \`
> `GENERATE_COT=1 \`
> `ARM_ROTPK_LOCATION=devel_rsa \`
> `ROT_KEY=$(ARM_TF_PATH)/plat/arm/board/common/rotpk/arm_rotprivk_rsa.pem`

So, you want to run TF-A **with OP-TEE** and root of trust and chain of trust enabled? Or are you only interested in testing it for TF-A? For the former, I believe our [Secure boot](https://optee.readthedocs.io/en/latest/architecture/secure_boot.html#armv8-a-using-the-authentication-framework-in-tf-a) instructions should work. There has also been discussions related to this in [other threads recently](https://github.com/OP-TEE/optee_os/issues?utf8=%E2%9C%93&q=is%3Aissue+GENERATE_COT+). There are a couple of questions already asked about this that also have some solutions (#3131 is probably of interest).

**Comment by jbech-linaro** [comment]
> I believe our [Secure boot](https://optee.readthedocs.io/en/latest/architecture/secure_boot.html#armv8-a-using-the-authentication-framework-in-tf-a) instructions should work.

If that is not the case, then we'd appreciate patches to optee_docs that resolves the discrepancy.

**Comment by jforissier** [comment]
> Neither do I, but on the other hand I don't speak Italian? :)

Definitely not Italian. Spanish I would say ;-)

**Comment by jbech-linaro** [comment]
> Definitely not Italian. Spanish I would say ;-)

Neither do I speak Spanish, so they're both "same same but different" to me :)

**Comment by 21212124** [comment]
these are my new flags:
`TF_A_FLAGS ?= \`
	`BL32=$(OPTEE_OS_HEADER_V2_BIN) \`
	`BL32_EXTRA1=$(OPTEE_OS_PAGER_V2_BIN) \`
	`BL32_EXTRA2=$(OPTEE_OS_PAGEABLE_V2_BIN) \`
	`BL33=$(EDK2_BIN) \`
	`PLAT=qemu \`
	`ARM_TSP_RAM_LOCATION=tdram \`
	`BL32_RAM_LOCATION=tdram \`
	`SPD=opteed \`
	`DEBUG=$(TF_A_DEBUG) \`
	`LOG_LEVEL=$(TF_A_LOGLVL) \`
	`MBEDTLS_DIR=$(TF_A_PATH)/../mbedtls \`
	`ARM_ROTPK_LOCATION=devel_rsa \`
	`ROT_KEY=$(TF_A_PATH)/plat/arm/board/common/rotpk/arm_rotprivk_rsa.pem \`
	`TRUSTED_BOARD_BOOT=1 \`
	`GENERATE_COT=1`
i too create symlinks to all the certs (.crt files) in arm-trusted-firmware/build/qemu/{debug,release}/ to out/bin/ 

but i have this error:
[https://bpaste.net/show/bklmo](url)

**Comment by vchong** [comment]
Did you download mbedtls? What's the location/path of it?

**Comment by 21212124** [comment]
yes.  
/home/iv/op-tee/mbedtls

now,  i have this error:
[https://bpaste.net/show/73fl4](url)

**Comment by vchong** [comment]
If you refer back to #3131 again, you'll see that the final flags used are:
```
ARM_TF_FLAGS ?= \
        BL32=$(OPTEE_OS_HEADER_V2_BIN) \
        BL32_EXTRA1=$(OPTEE_OS_PAGER_V2_BIN) \
        BL32_EXTRA2=$(OPTEE_OS_PAGEABLE_V2_BIN) \
        BL33=$(EDK2_BIN) \
        PLAT=qemu \
        ARM_TSP_RAM_LOCATION=tdram \
        BL32_RAM_LOCATION=tdram \
        SPD=opteed \
        DEBUG=$(ARM_TF_DEBUG) \
        LOG_LEVEL=$(ARM_TF_LOGLVL) \
        MBEDTLS_DIR=$(ARM_TF_PATH)/../mbedtls \
        TRUSTED_BOARD_BOOT=1 \
        GENERATE_COT=1
```

This [comment](https://github.com/OP-TEE/optee_os/issues/3131#issuecomment-512715131) specifically says that "**plat qemu has its own ROT_KEY defined in plat/qemu/platform.mk**", so `ARM_ROTPK_LOCATION` and `ROT_KEY` are **NOT** required. Not sure if these unnecessary flags are causing the errors or not though. Now, if you still get an error after using the flags above then sorry, not sure what the new problem is, but they worked ~3+ months ago.

Also, it would be nice if you can attach logs in English next time please so that we don't have to run the translator just to try to help you.

**Comment by 21212124** [comment]
these are my new flags:
`TF_A_FLAGS ?= \`
	`BL32=$(OPTEE_OS_HEADER_V2_BIN) \`
	`BL32_EXTRA1=$(OPTEE_OS_PAGER_V2_BIN) \`
	`BL32_EXTRA2=$(OPTEE_OS_PAGEABLE_V2_BIN) \`
	`BL33=$(EDK2_BIN) \`
	`PLAT=qemu \`
	`ARM_TSP_RAM_LOCATION=tdram \`
	`BL32_RAM_LOCATION=tdram \`
	`SPD=opteed \`
	`DEBUG=$(TF_A_DEBUG) \`
	`LOG_LEVEL=$(TF_A_LOGLVL) \`
	`MBEDTLS_DIR=$(TF_A_PATH)/../mbedtls \`
	`TRUSTED_BOARD_BOOT=1 \`
	`GENERATE_COT=1`

But i have this error:
![errorBL2](https://user-images.githubusercontent.com/30496643/68107549-80993180-fee5-11e9-9ef7-e07dede8cec1.PNG)

**Comment by vchong** [comment]
That's the same error as #3131 again. Are the symlinks still there?

**Comment by 21212124** [comment]
yes
![enlaceSimbolico](https://user-images.githubusercontent.com/30496643/68123548-9cb0c900-ff0d-11e9-9b84-4d35502108fc.PNG)

**Comment by 21212124** [comment]
when make run i have this error:
![makeRUN](https://user-images.githubusercontent.com/30496643/68127603-7cd1d300-ff16-11e9-90ee-70a7b38a213c.PNG)

how i can solve it?

**Comment by 21212124** [comment]
It is success secure boot on qemu?
![Secureboot](https://user-images.githubusercontent.com/30496643/68130073-04214580-ff1b-11e9-8a96-576009860bc5.PNG)

**Comment by 21212124** [comment]
I found the error (https://github.com/OP-TEE/optee_os/issues/3358#issuecomment-549258697). is when I enable this line: **TRUSTED_BOARD_BOOT=1**


why does that happen?

**Comment by vchong** [comment]
Tested this today and everything works as expected.

```
1. wget "repo" from Google and store it in $HOME/bin for example
2. $ mkdir foo
3. $ cd foo
4. $ repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml
5. $ repo sync -j4 --no-clone-bundle
6. $ cd build
7. edit qemu_v8.mk and set TF_A_TRUSTED_BOARD_BOOT ?= y
8. edit common.mk and set DEBUG ?= 1 
9. $ make -j`nproc` toolchains
10. $ make -j`nproc`
```
