### ISSUE TITLE
hangs at core_mmt_set_user_map when executing hello_world demo

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#336]
Hi, 

I am porting optee_os to a single core cortex-A7 r0p5 soc. When I executing hello_world demo, it hangs at:
<pre><code>
	if (map) {
		write_ttbr0(map->ttbr0);  --->ttbr0 is 9c16c46a, i use 0x9c100000 as the entry for optee_os
		isb();
		write_contextidr(map->ctxid);  ---> seems it hangs here in function core_mmu_set_user_map,  When "Load dynamic TA", no LPAE.
	} else {
</code></pre>
The tee-supplicant can work, the driver modules in linux also loaded successfully.
Did I miss something when porting optee_os?

Thanks.

**Comment by MrVan** [comment]
When `blx r3` which is the instruction which cause system hangs. Seems this is cache or mmu set issue. Still have no clear idea. 
<code><pre>
movw r3, #35e5
movt r3, #9c10
blx r3 --> system hangs
<code></pre>

**Comment by jenswi-linaro** [comment]
Without LPAE ttbr0 is only supposed to cover low address (<= 32 MiB), perhaps TTBCR.N isn't 7.

**Comment by MrVan** [comment]
Hi Jens,

I have found the root cause. Actually TTBCR.N is 7. We should first clear the tbl_info.table before fill mmu entries. From my debug info, the first entry is leaved and not set. So when set ttbr0, it corrupts system and hangs. After the following piece of code, all is fine.
<code><pre>
diff --git a/core/arch/arm/mm/core_mmu_v7.c b/core/arch/arm/mm/core_mmu_v7.c
index 0ea0da3..10ed12b 100644
--- a/core/arch/arm/mm/core_mmu_v7.c
+++ b/core/arch/arm/mm/core_mmu_v7.c
@@ -379,6 +379,13 @@ static paddr_t populate_user_map(struct tee_mmu_info *mmu)
        tbl_info.shift = SECTION_SHIFT;
        tbl_info.num_entries = TEE_MMU_UL1_NUM_ENTRIES;
 
+       /*
+        * Need to clear the table before use, because there maybe junk
+        * data at tlb_info.table, which may corrupt system when set ttbr0
+        */
+       memset(tbl_info.table, 0x00,
+              sizeof(unsigned long) * tbl_info.num_entries);
+
        region.pa = 0;
        region.va = va_range_base;
        region.attr = 0;
<code></pre>

**Comment by pascal-brand-st** [comment]
Fix in #342
