### ISSUE TITLE
* Storage of a large file in TA using Secure Storage API *

### ISSUE THREAD

**Issue by zineb-creator** [OP-TEE/optee_os#3360]
Hello !
i want to know if we can store a large file (54M) in TA using Secure storage API .
Thank you!!

**Comment by jbech-linaro** [comment]
I don't think there's a technical limitation, but it'd take a long time to read/write 54MB with our current solution.

**Comment by zineb-creator** [comment]
it must be subdivided while read/write ? am i right ,

**Comment by jbech-linaro** [comment]
I can't remember the limits for parameters, buffers etc, but you're probably right that you have to split it up into several calls.

**Comment by jenswi-linaro** [comment]
@zineb-creator, I think 54 meg is a bit too large. You will probably run out of heap since all the nodes of the Merkle tree is kept in memory at the same time. As a future optimization we could reduce the number of nodes kept in memory to be able to handle larger files.

**Comment by wamserma** [comment]
@zineb-creator A much better approach would be to generate a random key using the TEE and only pass the file (in chunks) through the TA for authenticated encryption, storing the ciphertext as a regular file in the REE. Only store the key for the file in the Secure Storage.
Mind that the performance of this approach may still be much lower than what you would get compared to doing the encryption/decryption in the REE.
