### ISSUE TITLE
no input signal from HDMI

### ISSUE THREAD

**Issue by sungwoooo** [OP-TEE/optee_os#3362]
I'm trying to connect hikey960 to my dell monitor with HDMI but there is no input signal.
(uart adapter is not prepared yet)

I have downloaded AOSP-OPTEE master branch and built it successfully by following the guide below.
https://optee.readthedocs.io/en/latest/building/aosp/aosp.html

Before building, I added "BOARD_KERNEL_CMDLINE += video=HDMI-A-1:1920x1080@60" in BoardConfig.mk

After flashing, I changed the mode of hikey960 (on/off/off) but there is no HDMI input signal.

Is there solution for this problem??

Thanks.

**Comment by sungwoooo** [comment]
I have tried for 2 days and got to know that it is hard to find the compatible monitor and setting.
I'll add something if I got another information.

**Comment by vchong** [comment]
@sungwoooo Sorry for late reply. The current hikey960 P build (https://optee.readthedocs.io/en/latest/building/aosp/aosp.html, https://github.com/linaro-swg/optee_android_manifest/tree/master) isn't working atm. Also, there's only AOSP P build for hikey960 right now, not master, so not sure what you built exactly.

You can try an older build (https://github.com/linaro-swg/optee_android_manifest/tree/3.4.2) and see if it works. That said, the OP-TEE AOSP build mainly tests for OP-TEE functions, i.e. command line only, so the monitor isn't really used/tested that much and as you said, it's hard to find a compatible monitor, so you might still see the same issue with 3.4.2 if your monitor isn't compatible.
