### ISSUE TITLE
Which DTS file is used in qemu-armv8 version of optee-os?

### ISSUE THREAD

**Issue by Cowboy555** [OP-TEE/optee_os#3363]
Hello, I want to use the device tree to reserve a piece of memory, but I can't find which device tree file is used by the qemu-armv8 version of optee-os. Please help me.

**Comment by jforissier** [comment]
Hi @Cowboy555 ,

The device tree is created by QEMU at run time. See `hw/arm/virt.c`, there is a call to `create_fdt()` and devices are later added to the tree.

**Comment by Cowboy555** [comment]
Thx~
