### ISSUE TITLE
xtest 1006 setjmp()/longjmp() crash with GCC6.2 and ftrace

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3364]
xtest 1006 crashes in the setjmp()/longjmp() test when function tracing is enabled
in OP-TEE and activated in the TA, and GCC 6.2 is used to build the TA libraries
(all other things are built with GCC 8.3 including the TA itself).
The test runs fine in the unmodified environment (GCC 8.3 used everywhere).

To reproduce:

0. Use QEMU build environment from https://github.com/OP-TEE/manifest/
1. Apply the following patch to be able to build the TA libraries with a different
cross-compiler:

```diff
diff --git a/common.mk b/common.mk
index dcb04a1..e1a3fee 100644
--- a/common.mk
+++ b/common.mk
@@ -365,12 +365,13 @@ endef
 ################################################################################
 # OP-TEE
 ################################################################################
+AARCH32_CROSS_COMPILE2 ?= $(AARCH32_CROSS_COMPILE)
 OPTEE_OS_COMMON_FLAGS ?= \
        $(OPTEE_OS_COMMON_EXTRA_FLAGS) \
        CROSS_COMPILE=$(CROSS_COMPILE_S_USER) \
        CROSS_COMPILE_core=$(CROSS_COMPILE_S_KERNEL) \
        CROSS_COMPILE_ta_arm64="$(CCACHE)$(AARCH64_CROSS_COMPILE)" \
-       CROSS_COMPILE_ta_arm32="$(CCACHE)$(AARCH32_CROSS_COMPILE)" \
+       CROSS_COMPILE_ta_arm32="$(CCACHE)$(AARCH32_CROSS_COMPILE2)" \
        CFG_TEE_CORE_LOG_LEVEL=$(CFG_TEE_CORE_LOG_LEVEL) \
        DEBUG=$(DEBUG) \
        CFG_TEE_BENCHMARK=$(CFG_TEE_BENCHMARK)
```

2. Build and run with:
  $ rm -rf ../out-br/build/optee_test-1.0; make -j10 CFG_FTRACE_SUPPORT=y CFG_TA_MCOUNT=y AARCH32_CROSS_COMPILE2=path/to/gcc6.2/bin/arm-linux-gnueabihf- run

$ xtest 1006

[Output on secure console]
```
TA time 0.000
TA time 1.062
D/TC:1 0 abort_handler:524 [abort] abort in User mode (TA will panic)
E/TC:? 0
E/TC:? 0 User TA prefetch-abort at address 0x0 (translation fault)
E/TC:? 0  fsr 0x00000005  ttbr0 0x0e19206a  ttbr1 0x0e18806a  cidr 0x2
E/TC:? 0  cpu #1          cpsr 0x60000110
E/TC:? 0  r0 0x00000000      r4 0x00115780    r8 0x00000000   r12 0x00115658
E/TC:? 0  r1 0x00000001      r5 0x0011fb8c    r9 0x00000000    sp 0x001156a0
E/TC:? 0  r2 0x00000000      r6 0x60000110   r10 0x00000000    lr 0x00000000
E/TC:? 0  r3 0x00000000      r7 0x00000000   r11 0x001156bc    pc 0x00000000
E/LD:  Status of TA 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b
E/LD:   arch: arm
E/LD:  region  0: va 0x00102000 pa 0x0e300000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x00104000 pa 0x0e302000 size 0x00a000 flags r-xs (ldelf)
E/LD:  region  2: va 0x0010e000 pa 0x0e30c000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x0010f000 pa 0x0e30d000 size 0x003000 flags rw-s (ldelf)
E/LD:  region  4: va 0x00112000 pa 0x0e310000 size 0x001000 flags r--s
E/LD:  region  5: va 0x00113000 pa 0x0e444000 size 0x003000 flags rw-s (stack)
E/LD:  region  6: va 0x0011b000 pa 0x00001000 size 0x024000 flags r-xs [0]
E/LD:  region  7: va 0x0013f000 pa 0x00025000 size 0x10f000 flags rw-s [0]
E/LD:  region  8: va 0x00266000 pa 0x00000000 size 0x003000 flags r-xs [1]
E/LD:  region  9: va 0x00269000 pa 0x00002000 size 0x002000 flags rw-s [1]
E/LD:  region 10: va 0x00300000 pa 0x40a67570 size 0x001000 flags rw-- (param)
E/LD:   [0] 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b @ 0x0011b000
E/LD:   [1] ffd2bded-ab7d-4988-95ee-e4962fff7154 @ 0x00266000
E/LD:  Call stack:
E/LD:   0x00000000
```

**Comment by jforissier** [comment]
See https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Using_ld_the_GNU_Linker/expressions.html#EXPRESSION-SECTION

**Comment by b49020** [comment]
> xtest 1006 crashes in the setjmp()/longjmp() test when function tracing is enabled
in OP-TEE and activated in the TA, and GCC 6.2 is used to build the TA libraries
(all other things are built with GCC 8.3 including the TA itself).

Interesting scenario. Will try to reproduce.

**Comment by jforissier** [comment]
> Interesting scenario.

Yeah, I don't have much clue yet. I noticed that `setjmp_a32.S` get compiled in thumb mode, but forcing arm mode does not seem to fix the issue.

> Will try to reproduce.

Thanks!

**Comment by jforissier** [comment]
> forcing arm mode does not seem to fix the issue

Actually, yes it does. I erroneously just added `.arm` directives at first, that was not accounting for `#ifdef __thumb2__`. The following patch works for me:

```diff
diff --git a/lib/libutils/isoc/arch/arm/sub.mk b/lib/libutils/isoc/arch/arm/sub.mk
index 1e11502f..5648b806 100644
--- a/lib/libutils/isoc/arch/arm/sub.mk
+++ b/lib/libutils/isoc/arch/arm/sub.mk
@@ -18,6 +18,7 @@ cflags-remove-arm32_aeabi_shift.c-y += -pg
 endif

 srcs-$(CFG_ARM32_$(sm)) += setjmp_a32.S
+aflags-setjmp_a32.S-$(CFG_FTRACE_SUPPORT) += -marm  # no thumb
 srcs-$(CFG_ARM64_$(sm)) += setjmp_a64.S

 ifeq ($(CFG_TA_FLOAT_SUPPORT),y)
```

TBH, the `setjmp_a32.S` file is a bit messy, perhaps we should simplify it for arm mode only?

**Comment by jforissier** [comment]
@b49020 https://github.com/OP-TEE/optee_os/pull/3365

**Comment by jenswi-linaro** [comment]
How come the `__thumb2__` define is set?
All `_a32.S` files are supposed to be assembled in ARM mode.

**Comment by b49020** [comment]
> How come the __thumb2__ define is set?

Since we don't set mode in `aflags`, toolchain will pick up the default mode configured during toolchain build time. It seems that by default `-mthumb` is set for toolchain releases from Linaro but in case of toolchain releases from Arm, by default `-marm` is set. You can check this via following test:

```
arm-linux-gnueabihf-gcc -frecord-gcc-switches test.c -o test
readelf -p .GCC.command.line test
```

That's the reason for `__thumb2__` being defined for GCC 6.2 and NOT defined for GCC 8.3.

So ideally we should configure either of mode for `aflags` as well to get away from this toolchain ambiguity. BTW, in case of `ftrace` we definitely need `-marm` to be set.

> All _a32.S files are supposed to be assembled in ARM mode.

I agree here to configure default mode as `-marm` as its always possible for user to override in `sub.mk` in case user wants to write assembly code in thumb mode.

**Comment by jforissier** [comment]
Fix merged, closing this issue.
