### ISSUE TITLE
GPROF with QEMU

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3366]
Do I have to run it in the normal world? Where does `gprof <ta_uuid>.elf gmon-<ta_uuid>.out` run?
![gprof1](https://user-images.githubusercontent.com/30496643/68387879-a7629c80-015f-11ea-9bf6-9a8b41ccc057.PNG)

Do I have to run it in the root directory? 
![gprof3](https://user-images.githubusercontent.com/30496643/68388681-7edba200-0161-11ea-8d2b-36e128987313.PNG)

Any suggestions @jforissier ?

**Comment by jforissier** [comment]
Hi @21212124,

The `gprof` command is not installed in the target root FS, therefore you should run it on your PC. You can easily transfer the `.out` file to your build environment by sharing a folder with QEMU as documented here: https://github.com/OP-TEE/build/blob/3.7.0/common.mk#L33-L36

For example:
```
## On the build system
$ make -j10 make -j10 CFG_TA_GPROF_SUPPORT=y CFLAGS_ta_arm32=-pg QEMU_VIRTFS_ENABLE=y run
## In QEMU
# mkdir /tmp/mypc
# mount -t 9p -o trans=virtio host /tmp/mypc
# cp /tmp/*.out /tmp/mypc
## Back on the build system
$ gprof out-br/build/optee_examples-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.elf gmon-8aaaf200-2450-11e4-abe2-0002a5d5c51b.out
```

Which version of OP-TEE are you using? I tried the above steps on latest master, but I get a core data-abort. It looks like gprof doesn't work anymore :-/

**Comment by 21212124** [comment]
OP-TEE - version 3.7.0 (2019-10-18)

**Comment by jforissier** [comment]
> I tried the above steps on latest master, but I get a core data-abort. It looks like gprof doesn't work anymore :-/

https://github.com/OP-TEE/optee_os/issues/3370

**Comment by 21212124** [comment]
He followed in his footsteps for arm64 and obtained this result:
[https://bpaste.net/show/sfemq](url)
It seems to work well.

**Comment by jforissier** [comment]
> It seems to work well.

Right, arm64 (QEMU v8 as we call it) does not crash for either.

**Comment by 21212124** [comment]
Hi @jforissier 

I am using GPROF but I don't have any timestamp.
Why don't the time records appear?

Thanks


Flat profile:

Each sample counts as inf seconds.
 no time accumulated

  %   cumulative   self              self     total           
 time   seconds   seconds    calls  Ts/call  Ts/call  name    
  0.00      -nan     -nan       36     -nan     -nan  memcpy
  0.00      -nan     -nan       27     -nan     -nan  __vsnprintf
  0.00      -nan     -nan       27     -nan     -nan  vsnprintk
  0.00      -nan     -nan       20     -nan     -nan  snprintk
  0.00      -nan     -nan       20     -nan     -nan  strlen
  0.00      -nan     -nan        7     -nan     -nan  trace_ext_puts
  0.00      -nan     -nan        7     -nan     -nan  trace_printf
  0.00      -nan     -nan        7     -nan     -nan  trace_vprintf
  0.00      -nan     -nan        7     -nan     -nan  utee_log
  0.00      -nan     -nan        3     -nan     -nan  bget
  0.00      -nan     -nan        3     -nan     -nan  memset
  0.00      -nan     -nan        3     -nan     -nan  raw_malloc_return_hook.constprop.21
  0.00      -nan     -nan        3     -nan     -nan  ta_header_get_session
  0.00      -nan     -nan        3     -nan     -nan  ta_header_remove_session
  0.00      -nan     -nan        3     -nan     -nan  trace_ext_get_thread_id
  0.00      -nan     -nan        2     -nan     -nan  __utee_entry
  0.00      -nan     -nan        2     -nan     -nan  from_utee_params
  0.00      -nan     -nan        2     -nan     -nan  to_utee_params
  0.00      -nan     -nan        1     -nan     -nan  TEE_Free
  0.00      -nan     -nan        1     -nan     -nan  TEE_Malloc
  0.00      -nan     -nan        1     -nan     -nan  _TEE_MathAPI_Init
  0.00      -nan     -nan        1     -nan     -nan  __utee_gprof_fini
  0.00      -nan     -nan        1     -nan     -nan  bgetr
  0.00      -nan     -nan        1     -nan     -nan  bgetz
  0.00      -nan     -nan        1     -nan     -nan  bpool
  0.00      -nan     -nan        1     -nan     -nan  brel
  0.00      -nan     -nan        1     -nan     -nan  calloc
  0.00      -nan     -nan        1     -nan     -nan  free
  0.00      -nan     -nan        1     -nan     -nan  malloc
  0.00      -nan     -nan        1     -nan     -nan  malloc_add_pool
  0.00      -nan     -nan        1     -nan     -nan  mempool_alloc_pool

**Comment by jforissier** [comment]
I don't know. The code uses `read_cntpct()` to get timestamps, perhaps it does not work on your platform?
gprof works on master on QEMU at least.

**Comment by 21212124** [comment]
@jforissier  I am using Qemu_v8 with OP-TEE version 3.9.0 (2020-04-22)

**Comment by jforissier** [comment]
> @jforissier I am using Qemu_v8 with OP-TEE version 3.9.0 (2020-04-22)

OK, I have not tried QEMUv8. I might when I have more time.
