### ISSUE TITLE
RPMB write requests: tee_rpmb_resp_unpack_verify

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#3368]
I need some help to understand the key_mac validation done by TEE on the response to a write request.

I am handling the response in U-boot and the current u-boot upstream code is missing a number of things which I have added by following up on what is done by the Linux supplicant emulator -  ioctl_emu_get_write_result (things like updating the message type, the write counter, the op result..). 

However I am not quite sure how to handle the mac since as AFAIU on validation, the TEE code calculates a mac on the response data against its _context_ key (and uboot doesnt have knowledge of this key).
If you could let me know if I am misunderstanding anything that would be much appreciated.

Incidentally, I can write and read RPBM using u-boot just by setting the key_mac to NULL on this line therefore bypassing the validation on return.
https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_rpmb_fs.c#L1329

Which also leads to a question: since regardless of the validation result, the write indeed happened and RPMB was written, is doing that validation confirming that this RPMB entry was just corrupted and needs to be corrected?

thanks

**Comment by jenswi-linaro** [comment]
> I am handling the response in U-boot and the current u-boot upstream code is missing a number of things which I have added by following up on what is done by the Linux supplicant emulator - ioctl_emu_get_write_result (things like updating the message type, the write counter, the op result..).

What are you trying to do, an RPMB emulator in U-Boot supplicant?

**Comment by ldts** [comment]
Sorry if I wasn't clear Jens; no, this is a proper interface between uboot and the tee (uboot accessing a AVB look alike TA, so not an emulation).

To provide some  reference, this is the uboot function code that can actually work with AVB (the upstream code is not functional on the platform I am testing (imx7) due to cache alignment issues and wrong data on the response frame

````
static int rpmb_route_write_req(struct mmc *mmc, struct s_rpmb *req,
				unsigned short req_cnt, struct s_rpmb *rsp,
				unsigned short rsp_cnt)
{
	ALLOC_CACHE_ALIGN_BUFFER(struct s_rpmb, req_frame, req_cnt);
	ALLOC_CACHE_ALIGN_BUFFER(struct s_rpmb, rsp_frame, 1);
	unsigned long wcount;
	int ret;

	memcpy(req_frame, req, sizeof(struct s_rpmb) * req_cnt);

	ret = mmc_set_blockcount(mmc, req_cnt, 1);
	if (ret)
		return ret;

	ret = send_write_mult_block(mmc, req_frame, req_cnt);
	if (ret)
		return ret;

	ret = mmc_set_blockcount(mmc, 1, 0);
	if (ret)
		return ret;

	memset(rsp_frame, 0, sizeof(*rsp));
	rsp_frame->request = cpu_to_be16(RPMB_REQ_READ_DATA);
	ret = send_write_mult_block(mmc, rsp_frame, 1);
	if (ret)
		return ret;

	ret = mmc_set_blockcount(mmc, 1, 0);
	if (ret)
		return ret;

	ret = send_read_mult_block(mmc, rsp_frame, 1);
	if (ret)
		return ret;

	ret = mmc_rpmb_get_counter(mmc, &wcount);
	if (ret)
		return ret;

	/* update the response frame the counter (should have incremented) */
	rsp_frame->request = cpu_to_be16(RPMB_RESP_WRITE_DATA);
	rsp_frame->write_counter = cpu_to_be32(wcount);
	rsp_frame->address = req_frame->address;

	memcpy(rsp, rsp_frame, sizeof(*rsp));

	return 0;
}

````

with this code in uboot, AVB read/write to RPMB does work as long as I comment out the line mentioned above to validate the write response request on TEE.

So I am just wondering what could I be missing (I am working under the assumption that the TEE code must be correct)

**Comment by jenswi-linaro** [comment]
In the usage of RPMB from OP-TEE U-Boot is just a relayer, it passes on the received frames to RPMB and returns the frames RPMB responds with.

U-Boot does not need to know the RPMB key, in fact it shouldn't know the key because then RPMB isn't secure from OP-TEE point of view.

At the end of `rpmb_route_write_req()` you're writing into the response frame, it will make the MAC invalid unless you're writing what's already there. You should not need to update the counter etc via an extra call to `mmc_rpmb_get_counter()`.

**Comment by ldts** [comment]
Yes I  was wondering about that as well (just retested, and yes you are correct)
I was able to read/write as well using the original functions with the cache alignment fixes (see below)

However this _still_ requires that validation requested in tee_rpmb_write_blk after the invoke sets key_mac = NULL (otherwise there are MAC validation error raised)

would you know why?

````
static int rpmb_route_write_req(struct mmc *mmc, struct s_rpmb *req,
				unsigned short req_cnt, struct s_rpmb *rsp,
				unsigned short rsp_cnt)
{
	ALLOC_CACHE_ALIGN_BUFFER(struct s_rpmb, req_frame, req_cnt);
	ALLOC_CACHE_ALIGN_BUFFER(struct s_rpmb, rsp_frame, 1);
	unsigned long wcount;
	int i, ret;

	memcpy(req_frame, req, sizeof(struct s_rpmb) * req_cnt);

	ret = mmc_set_blockcount(mmc, req_cnt, 1);
	if (ret)
		return ret;

	ret = send_write_mult_block(mmc, req_frame, req_cnt);
	if (ret)
		return ret;

	ret = mmc_set_blockcount(mmc, 1, 0);
	if (ret)
		return ret;

	memset(rsp_frame, 0, sizeof(*rsp));
	rsp_frame->request = cpu_to_be16(RPMB_REQ_STATUS);
	ret = send_write_mult_block(mmc, rsp_frame, 1);
	if (ret)
		return ret;

	ret = mmc_set_blockcount(mmc, 1, 0);
	if (ret)
		return ret;

	ret = send_read_mult_block(mmc, rsp_frame, 1);
	if (ret)
		return ret;

	memcpy(rsp, rsp_frame, sizeof(*rsp));

	return 0;
}

static int rpmb_route_read_req(struct mmc *mmc, struct s_rpmb *req,
			       unsigned short req_cnt, struct s_rpmb *rsp,
			       unsigned short rsp_cnt)
{
	ALLOC_CACHE_ALIGN_BUFFER(struct s_rpmb, rsp_frame, rsp_cnt);
	ALLOC_CACHE_ALIGN_BUFFER(struct s_rpmb, req_frame, 1);
	int ret;

	memcpy(req_frame, req, sizeof(struct s_rpmb));

	ret = mmc_set_blockcount(mmc, 1, 1);
	if (ret)
		return ret;

        ret = send_write_mult_block(mmc, req_frame, 1);
        if (ret)
		return ret;

	ret = mmc_set_blockcount(mmc, rsp_cnt, 0);
	if (ret)
		return ret;

        ret = send_read_mult_block(mmc, rsp_frame, rsp_cnt);
	if (ret)
		return ret;

	memcpy(rsp, rsp_frame, rsp_cnt * sizeof(struct s_rpmb));

	return 0;
}
````

**Comment by ldts** [comment]
argh, please discard this whole issue. because I was working around some other issue (key initialization problem due to the CID being returned by uboot to TEEnot being properly aligned) and introduced those hacks in the write function, clearly the MAC was complaining. I reverted optee and it is all good now. I will close this issue now. Sorry I wasted your time Jens!

**Comment by jenswi-linaro** [comment]
OK, good that you found the issue.

**Comment by ldts** [comment]
yes, thanks for your comments (made me rethink everything again). Once I am done I'll post some things on uboot and probably on TEE too (we have a new feature that allows the TEE to 1) extend the dts it receives from SPL for uboot with the TEE info while also 2) generates an overlay for the kernel that uboot will boot. I think it is useful.
