### ISSUE TITLE
No rule to make target '/home/kiran/DEVEL/OP-TEE/build/../mbedtls/library/asn1parse.c', needed by 'build/qemu/release/libmbedtls/asn1parse.o'.  Stop.

### ISSUE THREAD

**Issue by vxfury** [OP-TEE/optee_os#3369]
CROSS_COMPILE="/usr/bin/ccache /home/kiran/DEVEL/OP-TEE/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" make -C /home/kiran/DEVEL/OP-TEE/build/../trusted-firmware-a BL32=/home/kiran/DEVEL/OP-TEE/build/../optee_os/out/arm/core/tee-header_v2.bin BL32_EXTRA1=/home/kiran/DEVEL/OP-TEE/build/../optee_os/out/arm/core/tee-pager_v2.bin BL32_EXTRA2=/home/kiran/DEVEL/OP-TEE/build/../optee_os/out/arm/core/tee-pageable_v2.bin BL33=/home/kiran/DEVEL/OP-TEE/build/../edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/FV/QEMU_EFI.fd PLAT=qemu ARM_TSP_RAM_LOCATION=tdram BL32_RAM_LOCATION=tdram SPD=opteed DEBUG=0 LOG_LEVEL=30 MBEDTLS_DIR=/home/kiran/DEVEL/OP-TEE/build/../mbedtls TRUSTED_BOARD_BOOT=1 GENERATE_COT=1 all fip
make[1]: Entering directory '/home/kiran/DEVEL/OP-TEE/trusted-firmware-a'
Including services/spd/opteed/opteed.mk
make[1]: *** No rule to make target '/home/kiran/DEVEL/OP-TEE/build/../mbedtls/library/asn1parse.c', needed by 'build/qemu/release/libmbedtls/asn1parse.o'.  Stop.
make[1]: Leaving directory '/home/kiran/DEVEL/OP-TEE/trusted-firmware-a'

**Comment by vxfury** [comment]
Addtional information:
qemu_v8

**Comment by vchong** [comment]
Tested this today and everything works as expected.

```
1. wget "repo" from Google and store it in $HOME/bin for example
2. $ mkdir foo
3. $ cd foo
4. $ repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml
5. $ repo sync -j4 --no-clone-bundle
6. $ cd build
7. edit qemu_v8.mk and set TF_A_TRUSTED_BOARD_BOOT ?= y
8. $ make -j`nproc` toolchains
9. $ make -j`nproc`
```

**Comment by vchong** [comment]
Also edit common.mk and set DEBUG ?= 1 after 7 and before 8.
