### ISSUE TITLE
optee_os brel() performance issue

### ISSUE THREAD

**Issue by EddyPeng0916** [OP-TEE/optee_os#3374]
void brel(buf, poolset, wipe) api comes from optee_os/lib/libutils/isoc/bget.c

If previous buffer is free (Could be over 3MB according to the heap size define), this function will combine current buffer with previous free buffer before release it.

In wipe = true case, memset a buffer which combine with previous free buffer will take much longer than clean a small buffer.

Should it do memset current allocate buffer before combine with previous free buffer?

**Comment by jenswi-linaro** [comment]
Yes, I think that would be better.

**Comment by jforissier** [comment]
@EddyPeng0916 do you have a fix that you could share perhaps?
