### ISSUE TITLE
Compiled a new directory

### ISSUE THREAD

**Issue by 1flurry** [OP-TEE/optee_os#3380]
Hi, everyone!
I want to create a new directory just like optee_examples or optee_client, and when I execute the 'make run' command in build directory, this directory can be compiled.
Could you please tell me how can I do it?
Thanks!
1flurry

**Comment by jbech-linaro** [comment]
Hi @1flurry , we have all those changes in https://github.com/OP-TEE/build. For device specifics you find it in <device_name>.mk and for things that are common you find that in common.mk. Then depending on target (secure side or non-secure side). You might have to deal with Buildroot also, see the "br-ext" folder in build.git. There you see various examples of how we've been able to deploy files to the root fs.

**Comment by 1flurry** [comment]
> Hi @1flurry , we have all those changes in https://github.com/OP-TEE/build. For device specifics you find it in <device_name>.mk and for things that are common you find that in common.mk. Then depending on target (secure side or non-secure side). You might have to deal with Buildroot also, see the "br-ext" folder in build.git. There you see various examples of how we've been able to deploy files to the root fs.

Hi, I create a new directory named optee_rap2 and follow the optee_test to make changes in the build directory, but the following error occurred when I execute the 'make run' command: 
br-ext/package/optee_rap2/optee_rap2.mk:29: *** optee_rap2 has local site method, but `OPTEE_RAP2_SITE` is not defined.  Stop.

The contents of optee_rap2.mk are as follows:
  1 OPTEE_RAP2_VERSION = 1.0
  2 OPTEE_RAP2_SOURCE = local
  3 OPTEE_RAP2_SITE = $(BR2_PACKAGE_OPTEE_RAP2_SITE)
  4 OPTEE_RAP2_SITE_METHOD = local
  5 OPTEE_RAP2_INSTALL_STAGING = YES
  6 #OPTEE_RAP2_DEPENDENCIES = optee_client openssl host-python-pycrypto
  7 OPTEE_RAP2_SDK = $(BR2_PACKAGE_OPTEE_RAP2_SDK)
  8 OPTEE_RAP2_CONF_OPTS = -DOPTEE_RAP2_SDK=$(OPTEE_RAP2_SDK)
  9
 10 define OPTEE_TEST_BUILD_TAS
 11     @$(foreach f,$(wildcard $(@D)/ta/Makefile), \
 12         echo Building $f && \
 13             $(MAKE) CROSS_COMPILE="$(shell echo $(BR2_PACKAGE_OPTEE_RAP2_CROSS_COMPILE))" \
 14             O=out TA_DEV_KIT_DIR=$(OPTEE_RAP2_SDK) \
 15             $(TARGET_CONFIGURE_OPTS) -C $(dir $f) all &&) true
 16 endef
 17
 18 define OPTEE_TEST_INSTALL_TAS
 19     @$(foreach f,$(wildcard $(@D)/ta/out/*.ta), \
 20         mkdir -p $(TARGET_DIR)/lib/optee_armtz && \
 21         $(INSTALL) -v -p  --mode=444 \
 22             --target-directory=$(TARGET_DIR)/lib/optee_armtz $f \
 23             &&) true
 24 endef
 25
 26 OPTEE_RAP2_POST_BUILD_HOOKS += OPTEE_RAP2_BUILD_TAS
 27 OPTEE_RAP2_POST_INSTALL_TARGET_HOOKS += OPTEE_RAP2_INSTALL_TAS
 28
 29 $(eval $(cmake-package))

Could you please tell me how can I deal with it? Thanks!
