### ISSUE TITLE
When TA is running on Core1，then in Normal world ，Core2、Core3、……CoreN are still running or  stopped like Core1？

### ISSUE THREAD

**Issue by chenlifu2015** [OP-TEE/optee_os#3381]
Hi，Experts
     I'm confused about when cpu has four or more cores and enabled SMP in linux，while TA is  running on one of them，let`s say it is core1，in this time，nothing else can run on that core in normal world，right？But I am not sure other cores  are still running or stopped like core1？
    Any information is appreciated!
   
Lifu

**Comment by jenswi-linaro** [comment]
When secure world is entered non-secure interrupts are enabled as soon as possible. This means that Linux is still in charge of scheduling. A single core can only have one execution context active at the same time (ignoring hyperthreading etc) so while core1 is doing something in secure world that's what's done with that core. However, if a non-secure timer interrupt is raised on that core OP-TEE will suspend the context and exit to normal world. During this exit the Linux kernel can schedule another task. So time spent in secure world is accounted on the non-secure task which does executes the smc instruction. 

See also https://optee.readthedocs.io/en/latest/architecture/core.html#interrupt-handling

**Comment by chenlifu2015** [comment]
hi,jenswi
    thanks for your apply, so return to my question, normal world on core1  will stop when TA is running on this core(if there are not any interrupts happened), other cores will still keep running on the same time,right?

**Comment by jenswi-linaro** [comment]
Yes, but the stop will look just like a function call.

**Comment by chenlifu2015** [comment]
@jenswi-linaro thank you for the detailed explanation.
