### ISSUE TITLE
Debugging with VS Code

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3382]
i can`t to connect with VS.

`make -j8 run GDBSERVER=y`
`(qemu) c`
Normal world: 
`gdbserver :12345 optee_example_hello_world`

then F5 to debug in the VS Code:
[launch.json](https://bpaste.net/show/7cpf4)

but you won't get connect to VS code, any suggestions @jforissier  ?

**Comment by jforissier** [comment]
HI @21212124 ,

I don't us VS Code so no idea. Have you tried the command line as described in https://optee.readthedocs.io/en/latest/building/devices/qemu.html#gdb-normal-world?

**Comment by 21212124** [comment]
It was to test VS, however, that works correctly.

**Comment by dmcilvaney** [comment]
We did a bit of work to support VS code debugging for Open Enclave (TEE abstraction layer). The OP-TEE support is slowly making its way into OE (currently without VSCode extension). The extension works reasonably well and includes the requires *.json files to configure F5 debugging of OP-TEE with GDB.

https://github.com/openenclave/openenclave/tree/feature.new_platforms/new_platforms/vscode-extension/assets/standaloneSolutionTemplateFolder/.vscode

I've based some of my debugging on this to some success (sometimes it doesn't break in properly on the first try and I need to restart the debug session). I can't offer any detailed support but its a good starting point.
