### ISSUE TITLE
Is there any recommanded open source math library for OP-TEE? 

### ISSUE THREAD

**Issue by HeJyunYan** [OP-TEE/optee_os#3390]
I want to use math functions (such as sin, cos,...) to implement my trusted application.
Is there any recommanded open source math library for OP-TEE?
Thanks.

**Comment by jenswi-linaro** [comment]
I'd start looking in newlib (https://sourceware.org/newlib/)

**Comment by HeJyunYan** [comment]
okay.   I'll check newlib. Thanks
