### ISSUE TITLE
loading dynamic libraries in normal world application

### ISSUE THREAD

**Issue by nageshshamnur** [OP-TEE/optee_os#3391]
Hi All,
   I am trying to write my own CA and TA and i am using QEMU v7 environment for my test. I want to know how to load the dynamic libraries which my CA is referencing. When i run my application in normal world, it asks for the path of the dynamic library. I have copied the dependent dynamic library in the below exported path and set LD_LIBRARY_PATH to that.
export LD_LIBRARY_PATH=/mnt/host/out-br/host/arm-buildroot-linux-gnueabihf/sysroot/lib

but in my regular UART which i am using to debug using gdb, i found that the dynamic library symbols are not loaded. 
![image](https://user-images.githubusercontent.com/41421560/68762224-c370ad00-063b-11ea-9044-1439e6ba8a32.png)
Kindly help me with this issue

**Comment by nageshshamnur** [comment]
set solib-search-path solved this problem

**Comment by jforissier** [comment]
Should this be added to the doc?

**Comment by nageshshamnur** [comment]
yes, i feel it needs to be added to optee documentation.
