### ISSUE TITLE
Does OPTEE-OS copy a payload into its local memory?

### ISSUE THREAD

**Issue by casionwoo** [OP-TEE/optee_os#3393]
Hello, I'm trying to understand how OP-TEE handles payloads.
I'm considering TOCTOU vulnerability when OP-TEE OS wants to load a file or data etc.
First, it will ask Linux to allocated some memory within shared memory(I'm using static shared memory).
Second, it asks Linux to load the payloads into the allocated shared memory.

Once the Linux loads the payload and returns back from RPC, how OP-TEE is handling the payload? Does it copy to its local memory? Or let the TA directly access the shared memory?

**Comment by jenswi-linaro** [comment]
At some places in the code it's kept in non-secure memory but making sure to only read it once using a `READ_ONCE()` macro among other things. At other places it's copied into secure memory before parsing etc.

**Comment by casionwoo** [comment]
With the macro, the compiler guarantees the base address is accessed only once.
However, how can you guarantee the payload is corrupted by other malicious threads?
Consider the following scenario:

Let's say the base address of the payload starts from 0x08301000 and the size is 0x2000.
the `READ_ONCE()` macro would mark this base address to be read once.
How about if the malicious thread tries to modify 0x08302000(which is not marked by the `READ_ONCE()` macro)?

**Comment by jbech-linaro** [comment]
@casionwoo , we will update the docs with guidance around this to tell what is in secure memory vs in shared memory. But if you are unsure and to be on the safe side, you can always play safe by copy (and verify) your in-data to secure memory (stack or heap) before using it.

**Comment by jenswi-linaro** [comment]
`READ_ONCE()` doesn't mark anything, it just makes sure that the compiler doesn't emit instructions that reads the address multiple times. You can see an example at:
https://github.com/OP-TEE/optee_os/blob/8800b01d9f13a104b1c042de0c2106dedac38547/core/arch/arm/kernel/thread_optee_smc.c#L101-L117

**Comment by casionwoo** [comment]
@jenswi-linaro , yes you are right.
Compiler do now emit any instruction which tries to read the address. But my question is still valid.
How can the op-tee os guarantee the payload is not modified by other malicious thread? The thread is possible to read or write the middle of the payload.

**Comment by casionwoo** [comment]
@jbech-linaro thanks for your reply.
I wanted to know whether copying the payloads from shared memory to secure memory is under TA’s responsibility or under OP-TEE OS.

**Comment by jenswi-linaro** [comment]
By another malicious thread I assume you mean a non-secure one. OP-TEE cannot guard against that, but by only reading once it will guard against TOCTOU. The pieces which are read from non-secure memory are either stored securely or never touched again.

**Comment by casionwoo** [comment]
@jenswi-linaro yes, you are right that I was talking about the non-secure malicious thread.
Also, I was meaning a payload as something like TA or files read and loaded through RPC. 

The `READ_ONCE()` macro seems to rely on compiler not to emit any load instruction regarding a specific address. To my knowledge, the macro is only valid within OP-TEE(between other OP-TEE threads) that OP-TEE and Linux kernel are built separately as a different `compilation unit` even though it's the same compiler. (Correct me if I'm wrong)

I learned that in the case of TA, OP-TEE copy from non-secure shared memory to secure memory. Furthermore, if a TA is implemented to use SDP(secure data path), OP-TEE support to copy the data from non-secure shared memory to secure memory. However, I can't find any copying code from non-secure shared memory to secure memory except loading TA and SDP. 

I think to be protected normal payloads(not TA and not SDP case) from TOCTOU, copying to secure memory from non-secure shared memory is necessary. What do you think?

**Comment by nhchenfeng** [comment]
> @jenswi-linaro yes, you are right that I was talking about the non-secure malicious thread. Also, I was meaning a payload as something like TA or files read and loaded through RPC.
> 
> The `READ_ONCE()` macro seems to rely on compiler not to emit any load instruction regarding a specific address. To my knowledge, the macro is only valid within OP-TEE(between other OP-TEE threads) that OP-TEE and Linux kernel are built separately as a different `compilation unit` even though it's the same compiler. (Correct me if I'm wrong)
> 
> I learned that in the case of TA, OP-TEE copy from non-secure shared memory to secure memory. Furthermore, if a TA is implemented to use SDP(secure data path), OP-TEE support to copy the data from non-secure shared memory to secure memory. However, I can't find any copying code from non-secure shared memory to secure memory except loading TA and SDP.
> 
> I think to be protected normal payloads(not TA and not SDP case) from TOCTOU, copying to secure memory from non-secure shared memory is necessary. What do you think?

I think it's right

**Comment by nhchenfeng** [comment]
I think optee needs methods like copy_from_secure copy_to_nsecure
