### ISSUE TITLE
can user TA use smc to access a SiP service in BL31?

### ISSUE THREAD

**Issue by vtcao297** [OP-TEE/optee_os#3395]
Hi,

For a user TA that I'm designing, i want to hand off an operation to a SiP service that is handled in our BL3.1.  I see something similar is done in the ARM platform code using OPTEE_SMC_CALL_VAL macro.  Is this possible do to in a user TA?

**Comment by jenswi-linaro** [comment]
No, user TAs can't execute an SMC instruction. I will need to be trampolined via OP-TEE core in S-EL1, typically in a pseudo TA.

**Comment by vtcao297** [comment]
Okay i see, so will need to have a small pseudo TA to call the SMC out to the BL31 SiP Service and the user TA can call into that pseudo TA to jumpstart.  Thanks Jens.
