### ISSUE TITLE
Secure UUID

### ISSUE THREAD

**Issue by zineb-creator** [OP-TEE/optee_os#3397]
hello,

i would like to know if we can generate a secure UUID without using _the ITU-T UUID generator at http://www.itu.int/ITU-T/asn1/uuid.html_

thank you!!

**Comment by jforissier** [comment]
Hello,

Personally when I need a UUID I just type `uuidgen`.

**Comment by zineb-creator** [comment]
@jforissier 
Thank you for the answer however i wonder if someone was able to find out the uuid of the TA , he will be able  to communicate with it . am i right ?

**Comment by jforissier** [comment]
Maybe, but why would it be a problem? TA security does not depend on UUIDs being secret.

**Comment by zineb-creator** [comment]
But being able to communicate with a TA if we have her UUID it's not a security breach ?

**Comment by jbech-linaro** [comment]
> But being able to communicate with a TA if we have her UUID it's not a security breach ?

You as a TA developer have to make precautions to verify that the in-data is what you expect. In some cases that is easy, in other cases not. UUID is not secret and the TA should be resilient against UUID abuse. I.e, it shall not crash, it shall not happily accept any data.

**Comment by jforissier** [comment]
About access control: if the service that the TA provides needs to be restricted in any way then it is the responsibility of the TA to implement a suitable mechanism. For instance, implement authentication via signatures or challenge/response. It really depends on the use case.
The GlobalPlatform defines a "login method" parameter in `TEEC_OpenSession()`, which could be used in theory to filter out callers based on their user ID or group IDs for instance but OP-TEE does not implement that. Relying on this information would imply that the normal world kernel is trusted, but we usually avoid to make this assumption.

**Comment by zineb-creator** [comment]
thank you for these informations !!
