### ISSUE TITLE
tee_shm_alloc()  shm dma buffer from linux kernel failing

### ISSUE THREAD

**Issue by vtcao297** [OP-TEE/optee_os#3402]
Hi,

I'm running into an issue with one of kernel CA -> TA.  We are using tee_shm_alloc() function with TEE_SHM_MAPPED|TEE_SHM_DMA_BUF, but the call to tee_client_invoke_func() will return from OPTEE OS with a 0xffff0006 error code.  I traced to set_tmem_param() so i thought it was due to perhaps the address is not defined but i confirmed that the address range is registered with register_dynamic_shm() so the shm buffer pa is well within the range registered.  I'm not sure why this happening as i do have CFG_DYN_SHM_CAP enabled.

D/TC:? 0 set_tmem_param:76 pa=0x4f6370000                                                                                         
D/TC:? 0 set_tmem_param:105 Failed w/ TEE_ERROR_BAD_PARAMETERS                                                                                
[  153.656023] i2c_designware 20220000.i2c: controller timed out                                                   
[  153.661814] send: SUBMIT_COMMAND invoke error: 0xffff0006                             
[  153.671162] send: session_id=0x1                                                                                                     
D/TC:? 0 tee_ta_close_session:398 csess 0x801d1970 id 1                                                            
D/TC:? 0 tee_ta_close_session:417 Destroy session                                                                  
D/TA:  __utee_entry:220 session_id=0x858480x                                                                       
D/TA:  TA_CloseSessionEntryPoint:254 Close Session Entry      

I'm using optee 3.5 release w/ linux kernel 5.3 release.  Any help would be appreciated.

**Comment by b49020** [comment]
@vtcao297 Its a known bug in upstream now, fix patch is already posted here: https://lkml.org/lkml/2019/11/8/278

**Comment by jforissier** [comment]
@jenswi-linaro should the patch be posted as a PR in https://github.com/linaro-swg/linux?

It is of course fine (and best) to have patches upstream first, but the problem is I can't rebase our linaro-swg/linux branch "optee" now because upstream won't boot on my HiKey960 (https://github.com/linaro-swg/linux/issues/69).

**Comment by jenswi-linaro** [comment]
>  @jenswi-linaro should the patch be posted as a PR in https://github.com/linaro-swg/linux?

@jforissier, yes. I think there's more patches upstream which we're missing.
Is it OK for you to take care of those I would you rather that I did that?

**Comment by jforissier** [comment]
I can do it no problem. Thanks.

**Comment by jforissier** [comment]
@jenswi-linaro 

> https://www.spinics.net/lists/arm-kernel/msg769170.html

Is it me or there is something wrong? I can't find tag tee-fixes-for-v5.4.

**Comment by jforissier** [comment]
> @jenswi-linaro
> 
> > https://www.spinics.net/lists/arm-kernel/msg769170.html
> 
> Is it me or there is something wrong? I can't find tag tee-fixes-for-v5.4.

Nevermind. git fetch'ed and found it now. Sorry for the noise.

**Comment by jenswi-linaro** [comment]
> Nevermind. git fetch'ed and found it now. Sorry for the noise.

Good that you found it, you got me worried there for a while.

**Comment by jforissier** [comment]
Well for the record, I initially added your repo as a new remote and did a plain `git fetch <remote>`. Got lots of stuff, including branches and tags, but tee-fixes-for-v5.4 was not there. Then I ran `git fetch --tags <remote>` and the tag appeared. PEBKAC!

**Comment by vtcao297** [comment]
Hi @b49020, i tried out your patch it it resolved the issue I was seeing, however it's now failing much earlier in the execution flow, in particular tee_shm_alloc() fails to return valid memory buffer.  

Tracing it further in optee core code, register_shm()->msg_param_mobj_from_noncontig()->mobj_reg_shm_alloc()

E/TC:? 0 mobj_reg_shm_alloc:501 index[0], addr= 0x4f8f60000
D/TC:? 0 core_pbuf_is:1090 CORE_MEM_NON_SEC, pbuf = 0x4f8f60000
D/TC:? 0 core_pbuf_is:1093 is_nsec = 1, pbuf_inside = 0
E/TC:? 0 mobj_reg_shm_alloc:501 index[0], addr= 0x4f64da000
D/TC:? 0 core_pbuf_is:1090 CORE_MEM_NON_SEC, pbuf = 0x4f64da000
D/TC:? 0 core_pbuf_is:1093 is_nsec = 1, pbuf_inside = 0
E/TC:? 0 mobj_reg_shm_alloc:501 index[1], addr= 0x5a1ef0277d410000
D/TC:? 0 core_pbuf_is:1090 CORE_MEM_NON_SEC, pbuf = 0x5a1ef0277d410000
D/TC:? 0 core_pbuf_is:1093 is_nsec = 0, pbuf_inside = 0
E/TC:? 0 mobj_reg_shm_alloc:510 Fail core_pbuf_is()
E/TC:? 0 msg_param_mobj_from_noncontig:155 Failed mobj_reg_shm_alloc
E/TC:? 0 register_shm:472 Failed to register dynamic shmmem
[  156.543092] probe: tee_shm_alloc failed
E/TC:0 0 mobj_reg_shm_alloc:501 index[0], addr= 0x4f8f60000
D/TC:0 0 core_pbuf_is:1090 CORE_MEM_NON_SEC, pbuf = 0x4f8f60000
D/TC:0 0 core_pbuf_is:1093 is_nsec = 1, pbuf_inside = 0
D/TC:? 0 tee_ta_close_session:398 csess 0x801d1970 id 1

As you can see from the log, at index[1], seems there is this address that comes out of nowhere 0x5a1ef0277d410000 which is not within the ns_mem range defined, but odd thing is the platform doesn't even have this much memory.

**Comment by b49020** [comment]
@vtcao297 Ah, I see the fix that I posted worked only for memory allocated upto single page (4096 bytes) via `tee_shm_alloc()` but didn't work for size > 4096 bytes. The reason being `optee_shm_register()` expected pages to be passed as an array of page pointers but in the fix that I posted, pages were passed as an array of contiguous pages. So following change should correctly pass pages as per expectation:

```
diff --git a/drivers/tee/optee/shm_pool.c b/drivers/tee/optee/shm_pool.c
index 0332a53..f0d9539 100644
--- a/drivers/tee/optee/shm_pool.c
+++ b/drivers/tee/optee/shm_pool.c
@@ -28,8 +28,20 @@ static int pool_op_alloc(struct tee_shm_pool_mgr *poolm,
        shm->size = PAGE_SIZE << order;
 
        if (shm->flags & TEE_SHM_DMA_BUF) {
+               unsigned int nr_pages = 1 << order, i;
+               struct page **pages;
+
+               pages = kzalloc(sizeof(pages) * nr_pages, GFP_KERNEL);
+               if (!pages)
+                       return -ENOMEM;
+
+               for (i = 0; i < nr_pages; i++) {
+                       pages[i] = page;
+                       page++;
+               }
+
                shm->flags |= TEE_SHM_REGISTER;
-               rc = optee_shm_register(shm->ctx, shm, &page, 1 << order,
+               rc = optee_shm_register(shm->ctx, shm, pages, nr_pages,
                                        (unsigned long)shm->kaddr);
        }

```

I will post this fix on mailing list. Can I have your `Reported-by:` and `Tested-by:` tags?

**Comment by vtcao297** [comment]
Hi @b49020,

I verified the patch and it fixed the issue i was experiencing.

Reported-by: Vincent Cao <vincent.t.cao@intel.com>
Tested-by: Vincent Cao <vincent.t.cao@intel.com>
