### ISSUE TITLE
running TCP server in REE

### ISSUE THREAD

**Issue by nageshshamnur** [OP-TEE/optee_os#3404]
Hi All,
  I am using optee v3.5.0 on QEMU v7 with custom built CA/TA. I am running a TCP server (using IP 127.0.0.1:4433) on CA in REE and i am trying to connect to this TCP server from my host machine client application. Once the server is started on REE-CA, when i do netstat for this listening port, i am unable to find it due to which my connection is failing.
   Do i need to create a TAP interface for my QEMU setup so that i can connect to my CA ? can i get the steps to the same?
  I tried looking into optee documentation, tests and examples, but couldn't find any material on the same.

**Comment by nageshshamnur** [comment]
thanks Jérôme Forissier for the kind reply. For timebeing, i had used the port 12345 which was otherwise added for gdbserver and the conection went through. But however, i am stack at the next step.

I am running simple tcp_server on optee-REE on QEMU v7 and tcp_client on host machine. I found that after one message exchange, TCP server on optee-REE is resetting the connection.

![image](https://user-images.githubusercontent.com/41421560/68935861-4d954e80-07bf-11ea-88c7-f7a5ad1c3f20.png)

**Comment by jforissier** [comment]
Maybe try running strace on your server and possibly add debug traces.

**Comment by nageshshamnur** [comment]
so to isolate the problem, I ran both server and client on OPTEE-REE and it works as expected, the connection is not getting reset by either client or server.
