### ISSUE TITLE
system lock-up when optee-os reads CAAM, i.MX6 DualLite

### ISSUE THREAD

**Issue by RNNord2** [OP-TEE/optee_os#3405]
Hi.
I'm working for a project using optee (version 3.7.0) on i.MX6 DualLite. We're facing a system lock-up when optee-os reads from CAAM during xtest regresssion tests. 

We're using the boot flow ROM code -> U-boot SPL -> optee-os -> U-boot -> Linux kernel. When configuring optee-os to use the Fortuna PRNG, the full xtest regression test suite passes without failures. When configuring optee-os to use CAAM RNG however, the entire system hangs when trying to get a random number from the RNG during xtest regression_1004. 

I followed a call chain that ends up with crypto_rng_read -> do_rng_read ....... caam_hal_jr_read_nbslot_available -> io_caam_read32. By creating trace console printouts, I've found that the system hangs when trying to do "return *(volatile uint32_t *)addr" in the io_read32 function. 'addr' in this call is the virtual address 0x53101014. That's within an address range mapped by optee-os as:

D/TC:0 0 dump_mmap_table:751 type IO_SEC       va 0x53000000..0x531fffff pa 0x02000000..0x021fffff size 0x00200000 (pgdir)

I should add that optee-os successfully runs io_caam_read32 with the same address argument during initialization when the system boots up.

Does anyone have any idea in which direction to start looking for the root cause of this issue?

**Comment by Emantor** [comment]
https://github.com/OP-TEE/optee_os/pull/3349

**Comment by RNNord2** [comment]
Thank you. Indeed, that was a good place to start looking regarding this issue.

Since I'm not sure we will need CAAM exposed to the Linux kernel at all, I tried to remove the CAAM driver from Linux (by disabling CONFIG_CRYPTO_HW in kernel menuconfig). I also removed the caam section ("caam@2100000") from the device tree passed on to the kernel. I hoped that this would prevent the kernel from taking down the CAAM clocks, leaving CAAM usable for optee-os. However, I'm still getting the same system hang as described initially within io_caam_read32 during xtest regression_1004. 

My Linux kernel version is 4.14.149 if that matters.

**Comment by Emantor** [comment]
It's not a problem of the linux CAAM driver, the linux clk driver will turn off unused clocks which do not have a consumer. A possible workaround is a dummy CAAM driver which will request the clocks but do nothing otherwise.

@clementfaure may have more information on the intended NXP fixes to the kernel to make this work.
