### ISSUE TITLE
why my optee-os can run any normal executable code? 

### ISSUE THREAD

**Issue by gitgonewithwind** [OP-TEE/optee_os#3406]
Hi everyone,
I use TechNexion  imx-pico-pi board.  using yocto source code https://github.com/ARMmbed/mbed-os
xtest works well, optee_examples work well.
xtest:
..
24078 subtests of which 0 failed                                                
95 test cases of which 0 failed                                                 
0 test cases were skipped 
...
-----------------------------
In my understanding,  in optee-os , if executable code is no  signature, I CAN NOT run  in the optee-os. but I compile any executable code  as normal, it still can run! so the optee security is not useful?
Is my understanding  wrong?
I read the optee guide, I do not know how to use it. I am going to try to compile some Trusted Applications . but it look like any code can run in optee-os? why we need Trusted Applications ?

help me!
Thank you very much.

**Comment by jbech-linaro** [comment]
To give a full answer would require a long answer, but the short answer is that the early boot firmware shall implement secure boot, i.e. everything is signed and verified. Then as you've probably seen, all Trusted Applications are also signed and verified upon loading them.

Based on you questions, it seems like you need to study the TrustZone concept as such a bit more in detail to understand how TrustZone is (supposed to) working. [This](http://infocenter.arm.com/help/topic/com.arm.doc.prd29-genc-009492c/PRD29-GENC-009492C_trustzone_security_whitepaper.pdf) old whitepaper from Arm gives a good introduction to the concepts.

**Comment by gitgonewithwind** [comment]
> To give a full answer would require a long answer, but the short answer is that the early boot firmware shall implement secure boot, i.e. everything is signed and verified. Then as you've probably seen, all Trusted Applications are also signed and verified upon loading them.
> 
> Based on you questions, it seems like you need to study the TrustZone concept as such a bit more in detail to understand how TrustZone is (supposed to) working. [This](http://infocenter.arm.com/help/topic/com.arm.doc.prd29-genc-009492c/PRD29-GENC-009492C_trustzone_security_whitepaper.pdf) old whitepaper from Arm gives a good introduction to the concepts.
------------------------
Thanks

I want to know that in optee-os , can I prevent  the other people's executable  code to run in my optee-os? for my testing  it seems that any normal   executable code can run int it. that means any other company's code can run in my company's board. is it right?
for my understanding now, the TA only can run in optee-os, If somebody copy my TA to run in other normal board, it does work!. so the optee-os can prevent my company's code not to be copied by the other companies . right?

**Comment by jbech-linaro** [comment]
> I want to know that in optee-os , can I prevent the other people's executable code to run in my optee-os? for my testing it seems that any normal executable code can run int it. that means any other company's code can run in my company's board. is it right?

No, you sign the code, you own the keys that verifies the signature. If someone else try to fake a rouge Trusted Application or create another TA, then the TEE core will refuse to load it, since the signature is invalid.

> for my understanding now, the TA only can run in optee-os, If somebody copy my TA to run in other normal board, it does work!.

Yes and no ... I theory it'd be possible, but in practice it's not possible, since the TA would need to implement the entire TEE Internal API in normal world. Still, that wouldn't be the same as what is on the secure side, since secure side owns secrets that aren't accessible from non-secure side (Hardware Unique Key etc as an example).

> so the optee-os can prevent my company's code not to be copied by the other companies . right?

If it is copyright that you want to protect, then, sure anyone with access to the TA can reverse engineer it. However, Sumit is working on adding a feature to deal with that issue, please see https://github.com/OP-TEE/optee_os/pull/3340 regarding that.

**Comment by gitgonewithwind** [comment]
Thank you @jbech-linaro 
I am confused at here: I compile a normal executable code (NOT TA). I scp into the optee-os. It still  can  run in optee!
so is that a functional for optee-os? can it run any NOT TA code ?

**Comment by gitgonewithwind** [comment]
sorry @jbech-linaro 
I posted wrong before. I modified:

or my understanding now, the TA only can run in optee-os, If somebody copy my TA to run in other normal board, it does not work!(sorry wrong before should be: it does not work! ). so the optee-os can prevent my company's code not to be copied by the other companies . right?

**Comment by gitgonewithwind** [comment]
@jbech-linaro 
sorry to bother again
your answer Here:

my Question:
I want to know that in optee-os , can I prevent the other people's executable code to run in my optee-os? for my testing it seems that any normal executable code can run int it. that means any other company's code can run in my company's board. is it right?
your answer:
No, you sign the code, you own the keys that verifies the signature. If someone else try to fake a rouge Trusted Application or create another TA, then the TEE core will refuse to load it, since the signature is invalid.
-----
but for my testing, I compiled a code as normal,(NOT TA), and I copied (scp) into the optee-os, It was running!
I am confused at here. in my understanding. the optee-os only can running TA apps, why can it run any normal code?

**Comment by wamserma** [comment]
@gitgonewithwind 
It seems you are confusing the regular OS on your system and OP-TEE. These are running side-by-side and OP-TEE is not a full OS by itself. Unless you have made an elaborate setup on the OP-TEE side your `scp` was most likely to the regular OS.
Under most circumstances, OP-TEE loads a TA from the regular OS and executes it, if it is properly signed. This also means, TAs can be copied, signed with another key and used on another system.
To defend against "code theft" you need to install your TAs into secure storage.

**Comment by gitgonewithwind** [comment]
@wamserma  thanks. let me read more to understand how to install my TAs into secure storage.

**Comment by jforissier** [comment]
@gitgonewithwind currently you have two options to encrypt your TAs:
- Use `xtest --install-ta`. The TA(s) will be encrypted by OP-TEE with a random key (kept in secure storage) and stored in the REE FS.
- Recently, support was added to encrypt the TA at the same time they are signed. See commit 2de17fda.

**Comment by gitgonewithwind** [comment]
@jforissier  thanks. we saw your updated source code to  2de17fd . so I am updating my yocto to it or higher. but I can not pass the compiling in yocto. therefore I passed the issue here:  https://github.com/OP-TEE/optee_os/issues/3441#issuecomment-559787248

now In my understanding: for "code theft"  I have to choose : 1 . as @wamserma said To defend against "code theft" you need to install your TAs into secure storage
2. commit 2de17fd
am I right?

Thank you for you reply soon.

**Comment by gitgonewithwind** [comment]
@jforissier  sorry to bother you again.
I used a different uuid   to build optee_example_hello_world by my yocto toolchain. and copy optee_example_hello_world and ta into optee-os.  and run xtest --install, yes, optee_example_hello_world is running well.

so I copy optee_example_hello_world and TA to the second  board  from the first board which I always was running: xtest --install (same kind production we will use). I did not copy them from my host machine that I build them.

it is still running well in the second board.

In my understanding before, the code running in the first board should not run in the second board.
Am I wrong for my understanding?

**Comment by jforissier** [comment]
@gitgonewithwind the installed (encrypted) TA is in `/data/tee`, not in `/lib/optee_armtz`.

The original TA is not modified by the installation process. If you copy `/lib/optee_armtz/$UUID.ta` to another board, it will run with no error because it is not the board-specific one.

After `xtest --install /lib/optee_armtz/$UUID.ta`, you should `rm /lib/optee_armtz/$UUID.ta`. Then check that `optee_example_hello_world` still works (it should). If you have enabled debug traces (`CFG_TEE_CORE_LOG_LEVEL=3`) you will see that the TA is loaded from `(Secure Storage TA)` rather than `(REE)`.

After `xtest --install` the encrypted TA is in `/data/tee/0.ta` and there is no way you can manage to run this file on a different board if you copy it.

**Comment by gitgonewithwind** [comment]
@jforissier  Thank you so much. I got it and tested it. worked perfectly !
have a good day.
now I know the whole steps.
thanks again.

**Comment by jforissier** [comment]
@gitgonewithwind you're welcome! I suppose we can close this issue now.
