### ISSUE TITLE
function register_phys_mem, its use and significance?

### ISSUE THREAD

**Issue by alekarasma** [OP-TEE/optee_os#3409]
Hello Everyone,

I am implementing  ICC SIM driver in optee for IMX6UL. Previously I have done keypad driver which is working fine. My driver detects card insertion and removal, but ATR stuff is not working. 

while I was going through example drivers I found the following memory registration being done.
register_phys_mem(MEM_AREA_IO_SEC, UART1_BASE, 0x1000);

I have not done anything like this in my driver, which might be the reason for not working, I am not sure.

My concerns are,
Why is the significance of using register_phys_mem function?
Is it compulsory to use, If yes, In which scenarios?
Where Can I find function explanation? Is there any document which explains what is the purpose of this function and Similarly other functions defined in OPTEE core?

Any help is appreciated!!!.

Thanks & Regards,
Asma

**Comment by jforissier** [comment]
Hi @alekarasma ,

> register_phys_mem(MEM_AREA_IO_SEC, UART1_BASE, 0x1000);

This declaration will map 4 KiB of memory at physical address `UART1_BASE` so that you can use it later. You can use `phys_to_virt()` or `phys_to_virt_io()` to obtain the VA.

**Comment by alekarasma** [comment]
Thanks @jforissier .
Is there any document which explain this function and also few other functions in optee core?

**Comment by jforissier** [comment]
No, do you think the usage in the code in not self-explanatory?

**Comment by alekarasma** [comment]
@jforissier 

To be honest when I clicked at the function definition, I understood it is for reserving memory. 

But my question is, Is it necessary?. Because Last time when I implemented keypad driver in optee for imx6 I didnt use these function. So it created confusion for me, how come it worked for keypad and not working for SIM driver.

So If you can help me to confusion would be helpful. 
Is it necessary to reserve memory for every peripheral we are implementing in optee and playing with data instead of linux(e.g keypad, sim, I2C , SPI etc)?

Regards,
Asma

**Comment by jforissier** [comment]
> But my question is, Is it necessary?

Yes.

> how come it worked for keypad and not working for SIM driver.

Maybe you were lucky and the addresses for keypad fell in the range of a region already registered for another device? The granularity of `register_phys_mem()` is `SMALL_PAGE_SIZE` if I'm not mistaken (and `CORE_MMU_PGDIR_SIZE` for `register_phys_mem_pgdir()`).

**Comment by alekarasma** [comment]
Ok. Thanks @jforissier
