### ISSUE TITLE
understanding abort information in secure world

### ISSUE THREAD

**Issue by mofanv** [OP-TEE/optee_os#3411]
Hello team,

I'm trying to obtain the memory usage of my TA in TrustZone. To do that, I trigger an abort in the TA (as the following code), but I cannot understand the abort information in the secure world. More specifically,
1. what is `arch: arm load address: 0x203000`.
2. what is `stack: 0x102000 1050624`.
3. what is `region 0: va 0x100000 pa 0xe100000` and etc.
4. by using whether one,  I can compute the memory usage of TA in TrustZone (secure memory).

Sorry that I'm not familiar with the system architecture. Could you please help to ask the questions? any help is appreciated.

Thanks,
Fan

```
Abort!
E/TC:? 0 
E/TC:? 0 TA panicked with code 0x0
E/TC:? 0 Status of TA 7fc5c039-0542-4ee1-80af-b4eab2f1998d (0xe171f00) (active)
E/TC:? 0  arch: arm  load address: 0x203000 ctx-idr: 2
E/TC:? 0  stack: 0x102000 1050624
E/TC:? 0  region 0: va 0x100000 pa 0xe100000 size 0x1000 flags ---R-X 
E/TC:? 0  region 1: va 0x102000 pa 0xed21000 size 0x101000 flags rw-RW- 
E/TC:? 0  region 2: va 0x203000 pa 0xe300000 size 0x1e000 flags r-x--- [0]
E/TC:? 0  region 3: va 0x221000 pa 0xe31e000 size 0xa03000 flags rw---- [0]
E/TC:? 0  region 4: va 0xd00000 pa 0x6a815560 size 0x1000 flags rw-RW- 
E/TC:? 0  [0] 7fc5c039-0542-4ee1-80af-b4eab2f1998d @ 0x203000
E/TC:? 0 Call stack:
E/TC:? 0  0x00212900
E/TC:? 0  0x0020f601
E/TC:? 0  0x0020723f
E/TC:? 0  0x00207385
E/TC:? 0  0x0021286f
E/TC:? 0  0x002128cf
D/TC:? 0 user_ta_enter:311 tee_user_ta_enter: TA panicked with code 0x0
D/TC:? 0 tee_ta_invoke_command:625 Error: ffff3024 of 3
```

**Comment by jforissier** [comment]
Hello @mofanv,

> Hello team,
> 
> I'm trying to obtain the memory usage of my TA in TrustZone. To do that, I trigger an abort in the TA (as the following code), but I cannot understand the abort information in the secure world. More specifically,
> 
> 1. what is `arch: arm load address: 0x203000`.

`arm` tells that it is a 32-bit TA (a 64-bit one would show `aarch64`)

> 2. what is `stack: 0x102000 1050624`.

Virtual address and size of the stack

> 3. what is `region 0: va 0x100000 pa 0xe100000` and etc.

The memory mappings for the TA, showing which regions of virtual addresses are available to the TA and which physical address they map too, as well as the access permissions. If a region maps a binary (TA executable or data or shared library), it shows it too.

> 4. by using whether one,  I can compute the memory usage of TA in TrustZone (secure memory).

Depends on what you call "memory usage". The mappings can help, but with the version of OP-TEE you are using, they will essentially be constant. If you're trying to monitor the heap allocations inside your TA (how much is used by `TEE_Malloc()` calls), then I would suggest adding debug traces to the API.

**Comment by mofanv** [comment]
@jforissier , many thanks for your reply!

One quick question:
Do you mean with the latest version of OP-TEE (or another version), it is possible to use mapping information, such as `region 0: va 0x100000 pa 0xe100000`, to calculate how memory mappings for the TA? Which version of OP-TEE I should use?

**Comment by jforissier** [comment]
No. The mappings have changed a bit with the introduction of `ldelf`, and it is possible for a TA to request additional mappings are run time, but for most TAs it does not change things fundamentally.

`region 0: va 0x100000 pa 0xe100000 size 0x1000` means that `0x1000` bytes of memory (4 KiB) starting at physical address `0xe100000` are accessible at virtual address `0x100000`.

If your general question is "how much RAM does my TA use?", then the answer is the sum of all mapping sizes: `0x1000 + 0x101000 + 0x1e000 + 0xa03000 + 0x1000 = 0xb24000 = 11408 KiB = 11.1 MiB`.

**Comment by mofanv** [comment]
Many thanks for your detailed answers!
