### ISSUE TITLE
OP-TEE use micro kernel

### ISSUE THREAD

**Issue by luke923** [OP-TEE/optee_os#3414]
OP-TEE not support micro kernel, and we want to use a micro kernel like SEL4 to instead of OP-TEE kernel, can you give me some advice?

**Comment by jenswi-linaro** [comment]
I don't understand the question. OP-TEE isn't a micro kernel, but you want a micro kernel instead? I guess that rules out OP-TEE.

**Comment by luke923** [comment]
@jenswi-linaro yes，I want micro kernel instead，This is just an idea， Is it possible to achieve？

**Comment by jenswi-linaro** [comment]
No, it would require quite a bit of work.
