### ISSUE TITLE
Not able to recieve memory buffer but only size from PTA to host application

### ISSUE THREAD

**Issue by alekarasma** [OP-TEE/optee_os#3415]
Hello All,

I have written a driver in OPTEE, now I want to receive data from the driver through PTA to Normal world.

I wrote host application which is trying to first write data and then read processed data from driver through PTA. 

Here is my Host code snippet.
 ```
uint8_t capdu[100], rapdu[100];

uint8_t *rapdu_data;
...
....
rapdu_data = rapdu;
op.params[0].tmpref.buffer = sim_rcv_buffer.capdu;
  op.params[0].tmpref.size = sim_rcv_buffer.size;
  op.params[1].tmpref.buffer = rapdu_data;
  op.params[1].tmpref.size = sizeof(rapdu);

	op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_OUTPUT,
					 TEEC_NONE, TEEC_NONE);

  tee_res = TEEC_InvokeCommand(&session, PTA_EMV_COMMAND , &op, &ret_orig);
```

PTA code snippet

```
static TEE_Result emv_send_command(uint32_t type, TEE_Param p[TEE_NUM_PARAMS])
{
	TEE_Result ret;
	struct emv_reader_ops *fops;
	uint8_t rapdu[EMV1_MAX_MESSAGE_SIZE];
        size_t rapdu_size;
	uint32_t size;

uint32_t exp_pt = TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT,
			TEE_PARAM_TYPE_MEMREF_OUTPUT,
			TEE_PARAM_TYPE_NONE,
			TEE_PARAM_TYPE_NONE);

    if (exp_pt != type) {
		MSG("bad parameter types.\n");
		return TEE_ERROR_BAD_PARAMETERS;
	}

	fops = emv_reader->ops;
	size = p[0].memref.size;
	p[1].memref.buffer = rapdu;

	
	ret = fops->send_command((uint8_t *)p[0].memref.buffer , size, (uint8_t *)p[1].memref.buffer, &rapdu_size);

	if(ret != TEE_SUCCESS)
		return ret;

	MSG("%d %d %d %d\n", rapdu[0], rapdu[1], rapdu[2], rapdu_size);  //debug print to see data
	p[1].memref.size = rapdu_size;
	return TEE_SUCCESS;
}
```

I checked through debug code, whatever I am sending through host is being received by the driver, the Driver is processing that data and sending new data as well.  I printed recieved valuesfrom driver in PTA as shown above, I can see values in PTA , but these values are not sent to host application , only buffer size is being sent to host correctly.

Could somebody please tell me whats wrong I am doing? Is there any mistake in host application?
I have referred example code as well like xtest.

Regards,
Asma

**Comment by jforissier** [comment]
Hi @alekarasma ,

Your `rapdu` buffer is on the stack. Therefore it becomes invalid as soon as the `emv_sens_command()` function returns; you cannot use a pointer to this buffer.

Instead, you need to allocate memory for `p[1].memref` in the client application and have the TA copy your data into `p[1].memref` directly. See [`optee_examples/random`](https://github.com/linaro-swg/optee_examples/tree/3.7.0/random) for instance ([here](https://github.com/linaro-swg/optee_examples/blob/3.7.0/random/host/main.c#L79-L82) and [here](https://github.com/linaro-swg/optee_examples/blob/3.7.0/random/ta/random_example_ta.c#L67-L86)).

**Comment by alekarasma** [comment]
@jforissier ,

1. which rapdu buffer are you talking about, one in host application or PTA?
---> In PTA
ret = **fops->send_command((uint8_t *)p[0].memref.buffer , size, (uint8_t *)p[1].memref.buffer, &rapdu_size);**

I am directly copying data in p[1].memref.

2. In PTA rapdu  I am getting data, which is referenced to p[1].memref. That means p[1].memref has got the data in the TA. If it has got data, that means it should also reflect in host application. But I dont see that happening here. 

Sorry, I didnt get what exactly I am missing in your answer.

I will go through random generator once again. Is there anything more I can have a look at.

**Comment by jforissier** [comment]
I'm talking about the PTA. You're not copying data directly into `p[1].memref.buffer`, you're overwriting the pointer with `p[1].memref.buffer = rapdu;`.

**Comment by alekarasma** [comment]
You are right. Changed that and it worked. Thanks much @jforissier .
