### ISSUE TITLE
OP-TEE system call interface using AFL

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3417]
How do they apply the patches to the OP-TEE build system, client library and OS?
what is there to do?

@jbech-linaro

**Comment by jbech-linaro** [comment]
I've not been involved in that directly, but I'll be moderating a webinar with Riscure where this will be discussed. Feel free to join that webinar (and ask questions there).
https://www.linaro.org/events/webinar-running-a-fuzzing-tool-in-op-tee/

**Comment by 21212124** [comment]
Do you know by chance what steps to follow to integrate OPTEE_FUZZER with the OPTEE project?

Thanks!

**Comment by jbech-linaro** [comment]
Answer still the same unfortunately, the takeaway is that it is complicated at this point in time. There are lots of invasive changes. Please have a look at Riscure's presentation from Linaro Connect in September this year: https://www.youtube.com/watch?v=7bYAwaJ7WZw .
