### ISSUE TITLE
user_ta_ctx field load_addr stays zero

### ISSUE THREAD

**Issue by userid0x0** [OP-TEE/optee_os#3419]
Hi,
since the rework for ldelf being a user mode loader the user_ta_ctx field load_addr stays zero. Compare commit d1911a85142da16fef5ebdcdac0348d29ce37cd8  .
I noticed that the parameter is not passed from ldelf via struct ldelf_arg.
The register is useful to detect the load offset for a TA ELF file when using a JTAG probe.
Is this a bug or intention?

**Comment by userid0x0** [comment]
Appendix:
I am aware that ldelf holds a linked list main_elf_queue containing the main TA and it's library.
But both load offsets (ldelf nor ta) are stored in Op-Tee anymore.
A possible workaround is right now to use the function pointer
  user_ta_ctx -> entry_func
for a simple detection of the TA memory space and to traverse then through the struct vm_region in order to find the elf loading offset (field vm_region -> va and vm_region -> size).
Theoretically the same method may be used for ldelf itself
  user_ta_ctx -> dl_entry_func
. I am asking myself if there is a smarter way to detect the load-offsets, without those iterations in order to load the TA elf file and all library elf files.

**Comment by jenswi-linaro** [comment]
I've been thinking a bit about OP-TEE awareness myself. There's a few load addresses to keep track of:
1. ldelf, can be found via dl_entry_func as you say
2. main ELF of TA, can perhaps be calculated with entry_func - e_entry of ELF
3. all the dynamic libraries, I guess main_elf_queue in ldelf needs to be traversed

To make it easier for the debugger we could consider keeping track of the dynamic libraries in user_ta_ctx too, with a config flag of course.

**Comment by jforissier** [comment]
> To make it easier for the debugger we could consider keeping track of the dynamic libraries in user_ta_ctx too, with a config flag of course.

Agreed, but on the other hand ldelf reports the load addresses with `DMSG()` already, isn't it good enough for debugging?

**Comment by jforissier** [comment]
As a first trivial step I suggest we remove the unused `load_addr`: https://github.com/OP-TEE/optee_os/pull/3424

**Comment by userid0x0** [comment]
> Agreed, but on the other hand ldelf reports the load addresses with DMSG() already, isn't it good enough for debugging?
Well when you are writing an awareness I do not expect that the user needs to enter an address printed on the console.
On the other hand, when using a debug probe the idea is not to use printf. Just consider a product at the last product cycle and you want to debug/troubleshoot an TA without recompiling your code.

I would appreciate a simple list that holds all "elfs" mapped into a TA space part of the kernel.
But thats only a wish.

In the meanwhile I have now a development version of an awareness using the entry_func and dl_entry_func and thus I am not relying on load_addr.
But for loading e.g. all libs this means that someone needs to
  1) detect a TA "memory space"
  2) detect ldelf offset - load the ldelf symbols
  3) traverse main_elf_queue 
  4) detect library offsets - load library symbols
. The troublesome thing is that 2) as well as 4) might need user interaction as the elf searchpath needs to be queried from the end-user.
