### ISSUE TITLE
Secure Storage 

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3426]
Where they are in OP-TEE Hardware Unique Key (HUK) and a
constant string using HMAC-SHA256?

Where are they stored?
@jbech-linaro @jforissier 

Thanks!

**Comment by jbech-linaro** [comment]
https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html#hardware-unique-key

Regarding the constant string, it works as a salt.

**Comment by 21212124** [comment]
Is there something similar for the trusted application?

**Comment by jbech-linaro** [comment]
> Is there something similar for the trusted application?

Yes, I've introduced a PTA to get a TA (and device) unique key not that long ago, see this: https://github.com/OP-TEE/optee_os/commit/a30ddda9e48886e96696b130bfb8d9228fe589d9

**Comment by 21212124** [comment]
What is stubbed HUK? Is divided? why is it not safe?

The HUK key is saved as zeros in the software, it is rigth?

I have read this: https://github.com/OP-TEE/optee_os/issues/987#issuecomment-242292696
