### ISSUE TITLE
Can I build OP-TEE into MT7623A platform

### ISSUE THREAD

**Issue by amelroua** [OP-TEE/optee_os#3429]
I have MediaTek MT7623A Board that supports trustzone and I need to port optee to it but I cannot find the suitable manifest to build optee.

**Comment by jforissier** [comment]
Hi @amelroua ,

We used to have manifests for MT8173-EVB, see in https://github.com/OP-TEE/manifest/blob/3.0.0/. Perhaps it can help as a starting point. But please take a look at other board manifests in the master branch, because we now prefer to use Buildroot to build the root FS.

**Comment by amelroua** [comment]
Thanks for your response but the link doesn't work and in the last version OP-TEE documentation I found that MT8173-EVB manifest doesn't exist. So, I cannot figure out which manifest can be adopted for my MT7623A board.

**Comment by jforissier** [comment]
Fixed the link, sorry.

**Comment by amelroua** [comment]
Thanks, this manifest can be used for all Mediatek boards?

**Comment by jforissier** [comment]
Probably not. As I said, starting point.

**Comment by amelroua** [comment]
Have you any idea how to proceed to use OP-TEE in my board?
