### ISSUE TITLE
TEE OS improvement for memory map

### ISSUE THREAD

**Issue by hankyang7622** [OP-TEE/optee_os#3436]
Hi all

Currently we use OP-TEE v2.5 and we met some question as below:
1. We want to have large the memory for dynamic svp memory management mechanism. Does optee os support dynamic map / umap for memory region?
2. How to unmaping memory region of core_mmu_add_mapping?

thanks!!

**Comment by jenswi-linaro** [comment]
1:
I guess "svp" stands for Secure Video Path. In the OP-TEE source we're using "sdp" instead which stands for Secure Data Path, same thing different name. However, SDP only deals with static memory configuration, that is, the physical memory ranges are static. The memory itself is mapped dynamically when passed as parameters to a TA.

2:
There's no way of doing that. In later versions of OP-TEE we have dynamic shared memory registration and mapping, but that only covers non-secure memory.

To handle dynamic SDP memory some extension will be needed, patches are welcome.

**Comment by hankyang7622** [comment]
Thanks your help.
By the way, would you have plan to support dynamic map / umap for SDP in the future?

thanks!!

**Comment by jenswi-linaro** [comment]
> By the way, would you have plan to support dynamic map / umap for SDP in the future?

None that I'm aware of, but this is an open source project where anyone can participate...

**Comment by hankyang7622** [comment]
I have no question and I close the issue.
