### ISSUE TITLE
make error cannot find -lteec

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3439]
Any idea how to solve this error?

https://github.com/Riscure/optee_fuzzer/issues/2#issue-529885990

**Comment by jbech-linaro** [comment]
Hi @21212124 , please post the question at a single location and where it makes most sense. For the fuzzer it's the Riscure/optee_fuzzer that makes most sense. I'm closing this issue so let's continue the discussion on your other ticket, thanks!
