### ISSUE TITLE
[Question] Significance of TEEC_AllocateSharedMemory v.s. using temp memref

### ISSUE THREAD

**Issue by Raincode** [OP-TEE/optee_os#3440]
Hello,

I am working with OP-TEE and TAs and have looked at optee-examples as well as searched the web. However, I cannot find any example in optee-examples explicitly using shared memory.

What is the effective difference between the following approaches of passing a data buffer from CA to TA (ignoring the fact only the shared memory has write access)? I omitted boilerplate code for brevity.

```c
// More or less pseudo-code
TEEC_SharedMemory sharedBuf = {0};
char* heapBuf = NULL;

// local buffer
char localBuf[] = "HELLO";
int bufSize = sizeof(localBuf);

// buffer on heap
heapBuf = (char*)malloc(bufSize);
memcpy(heapBuf, localBuf, bufSize);

// explicit shared memory buffer
TEEC_AllocateSharedMemory(&ctx, &sharedBuf);

// prepare paramTypes
op.paramTypes = TEEC_PARAM_TYPES(
    TEEC_MEMREF_TEMP_INPUT,
    TEEC_MEMREF_WHOLE,
    TEEC_MEMREF_TEMP_INPUT,
    TEEC_NONE
);
op.params[0].tmpref.buffer = localBuf;
op.params[0].tmpref.size = bufSize;
op.params[1].memref.parent = &sharedBuf;
op.params[1].memref.size = bufSize;
op.params[2].tmpref.buffer = heapBuf;
op.params[2].tmpref.size = bufSize ;

// invoke some command
TEEC_InvokeCommand(&sess, TA_FOO_CMD_DO_SOMETHING, &op, &err_origin);

free(heapBuf);
TEEC_ReleaseSharedMemory(&sharedBuf);
```

My understanding is the following:
1. localBuf and heapBuf reside inside the normal non-secure RAM partition (e.g. using TZASC)
2. sharedBuf resides within the OP-TEE shared-memory (non-secure) partition

However, since the shared memory location must be passed via params with each invocation as well, I do not understand the significance of using TEEC_AllocateSharedMemory, v.s. simply passing a local buffer or a malloc'ed one. In all three cases, I am able to successfully read the memory contents from within my TA.

What are the use-cases that would explicitly require using the shared memory mechanism (v.s. temp memref to CA-owned memory)?

Thank you very much in advance for your insights!

**Comment by Raincode** [comment]
Hi again,

The distinction shown above is still not clear to me. Does nobody seriously know, or is there a problem with my question?

I would appreciate a short reply or feedback. Thank you!

**Comment by jenswi-linaro** [comment]
You find the answer (zero copy) in the section "3.2.4. Shared Memory" in TEE Client API Specification Version 1.0 (https://globalplatform.org/specs-library/tee-client-api-specification/).

**Comment by Raincode** [comment]
Hi,

thank you for the hint! I somehow missed that, and it explains exactly what I asked.

I gather that using a tempref will call ReigsterSharedMemory and ReleaseSharedMemory in the background, as I have not done that and it still worked. I think this is one of the aspects which is confusing for me.

> [...] a buffer of memory owned by the Client Application, in which case the buffer is temporarily registered by the TEE Client API for the duration of the operation being performed. This is called a Temporary Memory Reference.

As far as I'm concerned this question is solved. Thank you for your support.
