### ISSUE TITLE
in yocto, build optee-os,  ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by gitgonewithwind** [OP-TEE/optee_os#3441]
I tried updated commit for optee-os in yocto , ubuntu 16.04  hardware host(not virtulbox) 

commit d77929ec2243b789b58b718d7cd50da87cd9cf97
Author: Sumit Garg <sumit.garg@linaro.org>

Date:   Wed Nov 27 21:01:27 2019 +0530

    core: ftrace: dump core load address to support ASLR
    
    Additionally dump core address in ftrace buffer to support syscall
    tracing in case TEE core ASLR is enabled.
    
    Signed-off-by: Sumit Garg <sumit.garg@linaro.org>
    Reviewed-by: Jerome Forissier <jerome@forissier.org>
    [jf: s/Load address @/TEE load address @/]
    Signed-off-by: Jerome Forissier <jerome@forissier.org>

error:

ERROR: optee-os-3.3.0+gitAUTOINC+d77929ec22-r0 do_compile: oe_runmake failed
ERROR: optee-os-3.3.0+gitAUTOINC+d77929ec22-r0 do_compile: Function failed: do_compile (log file is located at /home/rnd2/work/TechNexion/imx7/mbl-manifest/build/tmp/work/imx7d_pico_mbl-oe-linux-gnueabi/optee-os/3.3.0+gitAUTOINC+d77929ec22-r0/temp/log.do_compile.11917)
ERROR: Logfile of failure stored in: /home/rnd2/work/TechNexion/imx7/mbl-manifest/build/tmp/work/imx7d_pico_mbl-oe-linux-gnueabi/optee-os/3.3.0+gitAUTOINC+d77929ec22-r0/temp/log.do_compile.11917
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 8 CFG_DT=y LDFLAGS= LIBGCC_LOCATE_CFLAGS=--sysroot=/home/rnd2/work/TechNexion/imx7/mbl-manifest/build/tmp/work/imx7d_pico_mbl-oe-linux-gnueabi/optee-os/3.3.0+gitAUTOINC+d77929ec22-r0/recipe-sysroot NOWERROR=1 PLATFORM=imx-mx7dpico_mbl CFG_TEE_CORE_LOG_LEVEL=1 CROSS_COMPILE_ta_arm32=arm-oe-linux-gnueabi- CFG_ARM32_core=y CFG_PAGEABLE_ADDR=0 CROSS_COMPILE_core=arm-oe-linux-gnueabi- ta-targets=ta_arm32 CFG_TEE_CORE_NB_CORE=2 CFG_BOOT_SECONDARY_REQUEST=y all CFG_TEE_TA_LOG_LEVEL=0
|   CHK     out/arm-plat-imx/conf.mk
|   GEN     out/arm-plat-imx/core/ta_pub_key.c
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/sys/types.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/sys/queue.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/sys/cdefs.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/signal.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/stdint.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/memory.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/strings.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/string.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/assert.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/wchar.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/setjmp.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/stdlib.h
| Traceback (most recent call last):
|   File "scripts/pem_to_pub_c.py", line 61, in <module>
|     main()
|   File "scripts/pem_to_pub_c.py", line 24, in main
|     from Crypto.PublicKey import RSA
| ModuleNotFoundError: No module named 'Crypto'
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/inttypes.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/time.h
| mk/subdir.mk:160: recipe for target 'out/arm-plat-imx/core/ta_pub_key.c' failed
| make: *** [out/arm-plat-imx/core/ta_pub_key.c] Error 1
| make: *** Waiting for unfinished jobs....
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/malloc.h
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/stdio.h
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/rnd2/work/TechNexion/imx7/mbl-manifest/build/tmp/work/imx7d_pico_mbl-oe-linux-gnueabi/optee-os/3.3.0+gitAUTOINC+d77929ec22-r0/temp/log.do_compile.11917)
ERROR: Task (/home/rnd2/work/TechNexion/imx7/mbl-manifest/build/conf/../../layers/meta-linaro/meta-optee/recipes-security/optee/optee-os_git.bb:do_compile) failed with exit code '1'

**Comment by jbech-linaro** [comment]
If you are using latest Ubuntu, then
```bash
$ apt-get install python3-pycryptodome
```

If you are running Ubuntu 16.04 (and probably earlier), then
```bash
$ apt-get install python3-pip
$ python3 -m pip install --user pycryptodome
```

**Comment by gitgonewithwind** [comment]
@jbech-linaro  thanks   I am comping in yocto. later I will install them if can not pass ( I  installed before to try ???)

I was confuse that why  I  compile optee-os out of the yocto, it passed after installed something at here  https://github.com/OP-TEE/optee_os/issues/3418 
 why can not pass in yocto ? 
I clean it at all, and compile it from beginning in yocto. 
Tomorrow morning, I can get the results.

**Comment by wamserma** [comment]
@gitgonewithwind From you post above I see that you are using OP-TEE 3.3 and that you are missing the pycrpto library. This should be added to the build dependencies of the OP-TEE BitBake file (and any recipes that build TAs)

```
DEPENDS += "python-native python-pycrpyto-native"
```

**Comment by gitgonewithwind** [comment]
@wamserma thank you very much for your reply.  
I tried  DEPENDS += "python-native python-pycrpyto-native", but error: it seemd in my yocto source code not their receipts, I will add it.
Nothing PROVIDES 'python-pycrpyto-native' (but /home/rnd2/work/TechNexion/imx7/mbl-manifest/build/conf/../../layers/meta-linaro/meta-optee/recipes-security/optee/optee-os_git.bb DEPENDS on or otherwise requires it). Close matches:
  python-pycrypto-native
  python3-pycrypto-native
  python-pycryptodome-native



 another question: the below is my bb file for optee-os_%.bbappend,  before I update optee-os to the newest master version, I used tag 3.6.0( directly it is from Mbed),you can see it that I commented it. 
new I update it to newest master version. and I check it my yocto downloading source code git log. it's the newest commit d77929ec2243b789b58b718d7cd50da87cd9cf97, but why it is OP-TEE 3.3 ? I should be OP-TEE 3.7.0 or higher?

----------------------------------------------                 

DEPENDS += " u-boot-tools-native python3-pyelftools-native  python3-cryptography python-native python-pycrpyto-native"
SRCREV = "2de17fda55d2d902123e25b1036cd6ae00b7ea77"
DEPENDS_append_raspberrypi3-mbl = " arm-aarch64-toolchain-native "
SRCREV = "2de17fda55d2d902123e25b1036cd6ae00b7ea77"
SRCREV = "2de17fda55d2d902123e25b1036cd6ae00b7ea77"

inherit python3native
...
LICENSE = "BSD-2-Clause"

# MBL_OPTEE_VERSION should be updated to match version pointed to by SRCREV
#MBL_OPTEE_VERSION = "3.6.0"

#SRCREV="f398d4923da875370149ffee45c963d7adb41495"
#SRC_URI="git://github.com/OP-TEE/optee_os.git;protocol=https;nobranch=1 \
#file://0001-allow-setting-sysroot-for-libgcc-lookup.patch \
#file://0004-remove-extra-param-from-print_stack_arm64.patch \
#"
SRC_URI="git://github.com/OP-TEE/optee_os.git;protocol=https;branch=master"
#SRCREV = "2de17fda55d2d902123e25b1036cd6ae00b7ea77"
SRCREV = "d77929ec2243b789b58b718d7cd50da87cd9cf97"
....

**Comment by gitgonewithwind** [comment]
> If you are using latest Ubuntu, then
> 
> ```shell
> $ apt-get install python3-pycryptodome
> ```
> 
> If you are running Ubuntu 16.04 (and probably earlier), then
> 
> ```shell
> $ apt-get install python3-pip
> $ python3 -m pip install --user pycryptodome
> ```

I tried. can not pass compilation. some error.

**Comment by jforissier** [comment]
Le ven. 29 nov. 2019 à 14:54, gitgonewithwind <notifications@github.com> a
écrit :

> @wamserma <https://github.com/wamserma> thank you very much for your
> reply.
> I tried DEPENDS += "python-native python-pycrpyto-native"
>
Spelling mistake.

>

**Comment by gitgonewithwind** [comment]
@jforissier  I corrected the spelling. my  DEPENDS in .bbappend file is below, but the original error is till there. I need take time to fix. calm down! 
=======
DEPENDS += " u-boot-tools-native python3-pyelftools-native  python3-cryptography python-native python-pycrypto-native python-pycryptodome"
SRCREV = "2de17fda55d2d902123e25b1036cd6ae00b7ea77"
DEPENDS_append_raspberrypi3-mbl = " arm-aarch64-toolchain-native "

inherit python3native

LICENSE = "BSD-2-Clause"

# MBL_OPTEE_VERSION should be updated to match version pointed to by SRCREV
#MBL_OPTEE_VERSION = "3.6.0"

#SRCREV="f398d4923da875370149ffee45c963d7adb41495"
#SRC_URI="git://github.com/OP-TEE/optee_os.git;protocol=https;nobranch=1 \
#file://0001-allow-setting-sysroot-for-libgcc-lookup.patch \
#file://0004-remove-extra-param-from-print_stack_arm64.patch \
#"
SRC_URI="git://github.com/OP-TEE/optee_os.git;protocol=https;branch=master"
#SRCREV = "2de17fda55d2d902123e25b1036cd6ae00b7ea77"
SRCREV = "d77929ec2243b789b58b718d7cd50da87cd9cf97"


error:
Traceback (most recent call last):
|   File "scripts/pem_to_pub_c.py", line 61, in <module>
|     main()
|   File "scripts/pem_to_pub_c.py", line 24, in main
|     from Crypto.PublicKey import RSA
| ModuleNotFoundError: No module named 'Crypto'
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/unistd.h
| mk/subdir.mk:160: recipe for target 'out/arm-plat-imx/core/ta_pub_key.c' failed
|   INSTALL out/arm-plat-imx/export-ta_arm32/include/sys/types.h
| make: *** [out/arm-plat-imx/core/ta_pub_key.c] Error 1

**Comment by vchong** [comment]
> @jforissier I corrected the spelling. my DEPENDS in .bbappend file is below, but the original error is till there. I need take time to fix. calm down!

Dude, **NOT(!)** the proper thing to say to people helping to check your work and trying fix your errors!

**Comment by gitgonewithwind** [comment]
@vchong  Thanks. I mean I need calm down by myself.
Thank you very much for every one.
 I fixed the issue using below DEPENDS (sorry forget python3). there is another issue again. let me try to fix it. if I can not fix it, I will post again(sorry to bother you)
Have a good weekend

DEPENDS += " u-boot-tools-native python3-pyelftools-native  python3-cryptography python3-native python3-pycrypto-native python3-pycryptodome"

**Comment by gitgonewithwind** [comment]
hi all ,
I fixed this issue using below DEPENDS in yocto  optee-os.bb_append file.
thank you all very much for your kind help. 
now I  can compile optee-examples TA and host  by my built yocto toolchains  separately(not in yocto). later I will use the yocto toolchains to build my company's TA separately. I only have the last step  to need to learn: how to run the optee-examples TA  in optee?(now host /usr/bin/optee_example_hello_world is running, sorry I am not clear about the TA and the host code ) I will do it next Monday.

have a good weekend. Thanks again


optee-os.bb_append file :    
#need 0001-allow-setting-sysroot-for-libgcc-lookup.patch from Mbed for yocto build , otherwise  error arm-oe-linux-gnueabi-ld.bfd: cannot find libgcc.a: No such file or directory


...
DEPENDS += " u-boot-tools-native python3-pyelftools-native python3-native python3-pycrypto-native"
SRC_URI="git://github.com/OP-TEE/optee_os.git;protocol=https;branch=master \
        file://0001-allow-setting-sysroot-for-libgcc-lookup.patch \   
"
#SRCREV = "2de17fda55d2d902123e25b1036cd6ae00b7ea77"
SRCREV = "d77929ec2243b789b58b718d7cd50da87cd9cf9

**Comment by jforissier** [comment]
@gitgonewithwind when you run `/usr/bin/optee_example_hello_world`, the corresponding TA is started automatically by OP-TEE.

**Comment by gitgonewithwind** [comment]
> @gitgonewithwind when you run `/usr/bin/optee_example_hello_world`, the corresponding TA is started automatically by OP-TEE.

-
Thank you very much for your reply so soon.
you mean, after I use the yocto toolchains to build my company's TA  and host. I copy the host and TA in the optee-os (TA in ./lib/optee_armtz/). and only run the host code? that's all? I almost done?

**Comment by wamserma** [comment]
@gitgonewithwind Yes, you copy your host binary wherever you like and your .ta to `./lib/optee_armtz/`. The `.elf` is an intermediate build result of the TA (the TA before it is signed) and not needed on the final system.
It helps to think of host/TA as some sort of Client/Server architecture using RPC calls. The RPC endpoint (TA) is discovered by its UUID, the different commands of the TA are defined in `TA/include/*.h`. Study the source of the hello world example, then copy it, change the UUID in the header file and the Makefile, test it and then gradually modify it towards your own application.

**Comment by gitgonewithwind** [comment]
@wamserma  thank you so much. I got it for this point.

you  answered me at here: https://github.com/OP-TEE/optee_os/issues/3406 
for my final application,  I need to "To defend against "code theft" you need to install your TAs into secure storage' . is that another step ? it's different with my upper question? 
thank you have a good weekend.

**Comment by wamserma** [comment]
@gitgonewithwind Installing into secure storage is a different step and done once your system is running, so nothing you would do during your Yocto build.
If you are building a read-only RootFS, you need to use option 2. (`sign-enc` python script), otherwise once your target is up and running in a trusted environment, you install the TA.
(Or you can use another TA to create a secure communications channel to some server of yours, download the actual TA and install it).

As your Yocto issues seem to be solved, would you mind closing this issue?

**Comment by gitgonewithwind** [comment]
@wamserma 
thank you I got some idea.
please close the issue.
I need learn more next week.

**Comment by jforissier** [comment]
@wamserma thanks for helping out ;-)

**Comment by vchong** [comment]
> If you are running Ubuntu 16.04 (and probably earlier), then
> 
> $ apt-get install python3-pip
> $ python3 -m pip install --user pycryptodome

**NOTE**: This did **NOT** work. Need to also install `pycryptodomex` (not a typo).

**Comment by jbech-linaro** [comment]
> **NOTE**: This did **NOT** work. Need to also install `pycryptodomex` (not a typo).

On what env? Ubuntu 16.04? I used the 16.04 Docker image. That might be different to the "true" image?

**Comment by vchong** [comment]
> On what env/distro? Ubuntu 16.04? I used the 16.04 Docker image. That might be different to the "true" image?

'did NOT work' sounded a bit strong and I was in the middle of changing the text to 'might NOT work in all cases' when you posted your comment. : s

I was using the 16.04 Docker image too, but the build servers in ci.linaro.org have this issue too which was what started this investigation. The build servers might be docker images too though, depending on the builds iinm. Not sure if the source of the docker image might be a factor as well or not.

**Comment by gitgonewithwind** [comment]
when I posted the issue, I used commit SRCREV = "d77929ec2243b789b58b718d7cd50da87cd9cf9" (you can find before)
It worked well.


but today I did another duty today morning. I tried use the updated commit .  it  did not work!
I tried add  something in my yocto bb file  like below, but It still did not work. I gave up and rolled back.
DEPENDS += " u-boot-tools-native python3-pyelftools-native python3-cryptography python3-native python3-pycryptodome python-pycryptodome "


when build Not in yocto, for the updated  commit,  pycryptodome need 8.9.xx version. not 13.xx version . passed!
