### ISSUE TITLE
IMX6ULL Hangs When Changing RAM Size

### ISSUE THREAD

**Issue by Zephyrus29** [OP-TEE/optee_os#3442]
Hi, 

I've got a device running an IMX6ULL that previously had 128MB of RAM that I'm upgrading to 1GB. I've configured it in U-Boot, and loading Linux during the programming process seems to have no problems, but when I boot again using OP-TEE, I get a hang after the message "Primary CPU switching to normal world boot".

I've set CFG_DDR_SIZE=0x40000000 rather than the 0x08000000 I had before.

I have no problems if I lower the amount of memory in U-Boot, indeed merely lowering the number of RAM rows in the config register back to what I had before causes no problems, but anything greater causes the hang.  

Is there any other settings that needs to be changed? I'm thinking it's an OP-TEE problem due to there being no problems if I boot without it.

**Comment by jenswi-linaro** [comment]
Since U-Boot usually relocates to top of RAM perhaps OP-TEE uses some of that RAM?

**Comment by Emantor** [comment]
You should also check whether U-Boot still loads the kernel to the correct address, since OP-TEE will jump to this address after initialization.

**Comment by Zephyrus29** [comment]
Thanks for the help, I updated my version of op-tee and that seemed to make it happy. Must have been some bug in the release I was working off that has been fixed. 

All my PTA's are broken, but that's a different issue.
