### ISSUE TITLE
Secure IO (network card, spi and uart)

### ISSUE THREAD

**Issue by h-bar** [OP-TEE/optee_os#3448]
Does the OP-TEE (or ARM trustzone) provide true secure IO on the network card, SPI, UART, and other hardware IO interfaces? 

I read the Global platform API about isocket and found i2c and UART headers in optee_os source code. Do these implementations only work as APIs for TAs to use those HW interfaces or these implementations actually guarantee securities while accessing those HW interfaces (Namely normal world application/OS cannot access the HW interfaces that are being used by a TA)?

Thanks!

**Comment by jforissier** [comment]
> Does the OP-TEE (or ARM trustzone) provide true secure IO on the network card, SPI, UART, and other hardware IO interfaces?

Generally speaking, yes.
 
> I read the Global platform API about isocket and found i2c and UART headers in optee_os source code. Do these implementations only work as APIs for TAs to use those HW interfaces

There is no API in OP-TEE for TAs to access hardware peripherals directly. They can be accessed by the TEE core (kernel) via secure or non-secure memory-mapped registers, typically.

iSocket functions called by TAs go to the normal world (`tee-supplicant`). 

> or these implementations actually guarantee securities while accessing those HW interfaces (Namely normal world application/OS cannot access the HW interfaces that are being used by a TA)?

Whether a device is secure or not depends on the configuration done by OP-TEE drivers or by other secure firmware (TF-A for instance). So it depends on the platform.

> Thanks!

**Comment by h-bar** [comment]
So if we use hikey 960 with OPTEE (which uses TF-A as secure firmware), we could configure the device so that TA applications can have a secure way to communicate with IO devices, so that normal world application or OS cannot know or modify the content of the communication. Is that correct?

**Comment by jforissier** [comment]
@h-bar yes, that is correct. We **could** do it, if we had the reference documentation explaining how to protect memory and peripherals from Normal World access. It usually means configuring some sort of memory and bus firewall (Arm TZASC / TZPC for instance). Personally I have no information on how to do that with the HiKey960 :-/

**Comment by h-bar** [comment]
@jforissier Thanks so much! Do you mind to provide me any information on how to do that on any other device that you have worked on?

**Comment by vchong** [comment]
Here are some code samples but not necessarily devices we've worked on or have information to. Most, if not all, of these seem TZASC (memory regions) related only and not really sure how they'd specifically translate to IOs, or if even at all.

https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-imx/drivers/tzc380.c
http://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/tree/plat/arm/common/arm_tzc400.c
http://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/tree/plat/arm/common/arm_tzc_dmc500.c
http://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/tree/plat/layerscape/common/ls_tzc380.c
http://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/tree/plat/arm/board/juno/juno_tzmp1_def.h
http://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/tree/plat/layerscape/board/ls1043/include/soc_tzasc.h

**Comment by h-bar** [comment]
@vchong thank you!
