### ISSUE TITLE
about optee-os user address space

### ISSUE THREAD

**Issue by louisjohn0416** [OP-TEE/optee_os#345]
what confused me is that why optee-os user space use mapping address started from 1M by
TEE_DDR_VLOFFSET to 1 ? why not started from 0 ?

**Comment by jenswi-linaro** [comment]
We don't have that define any longer. But we still leave address 0 inaccessible for a TA to catch NULL dereferences.

**Comment by louisjohn0416** [comment]
OK, thanks a lot !

**Comment by louisjohn0416** [comment]
Another thing, is there any armv8 soc which supporting trustzone you can recommend for me ?
thanks a lot.

**Comment by jenswi-linaro** [comment]
I recommend the HiKey board, https://www.96boards.org/products/ce/hikey/
