### ISSUE TITLE
Can‘t run normal world on  ARMv8 FVP base model

### ISSUE THREAD

**Issue by PandaQ2014** [OP-TEE/optee_os#3450]
I was trying to run optee on fvp base model with following parameters.
``` Makefile
run-only:
	@cd $(FOUNDATION_PATH); \
	$(FOUNDATION_PATH)/models/Linux64_GCC-6.4/FVP_Base_RevC-2xAEMv8A \
	-C bp.secure_memory=1 \
	--data "$(TF_A_PATH)/build/fvp/$(TF_A_BUILD)/bl1.bin"@0x0 \
	--data "$(TF_A_PATH)/build/fvp/$(TF_A_BUILD)/fip.bin"@0x8000000 \
```
But I was unable to start linux as this figure shows. 
![图片](https://user-images.githubusercontent.com/18640371/70133918-044f6500-16c2-11ea-8517-ebcf55420f55.png)

Could you please offer me some advice about this problem, thank you!

**Comment by jbech-linaro** [comment]
The only thing I can see is that you have a more recent version than I have. I'm (still) using,
```bash
<...>/models/Linux64_GCC-4.9] 
$ ./Foundation_Platform --version
ARM V8 Foundation Platformr0p0 (platform build 11.4.37)
Copyright 2017 ARM Limited.
All Rights Reserved.
```
Might be that you've identified a regression on newer models that no-one else have tried yet. I don't have time to try anything on my side, but. I would try to ensure that the FVP build/run instructions are followed at the [FVP OP-TEE documentation](https://optee.readthedocs.io/en/latest/building/devices/fvp.html) and then eventually try to downgrade FVP and see if that makes any difference. If it does, then we have pin-pointed the problem and we could continue investigation from there.

**Comment by PandaQ2014** [comment]
Yes, I have run optee successfully on FVP foundation version with the help of this documentation. But I need to run optee on FVP base version, because I want to use TZC400 which is only simulated by FVP base version. 
Now bl1 ~ bl32 can boot up as expected, but normal world is blocked in uefi shell, and the linux kernel is not booted.
Maybe I have missed some necessary parameters to start FVP, do you have any advice?

**Comment by jenswi-linaro** [comment]
The base model takes different command parameters if I remember correctly. You may need a different DTB also. Perhaps https://trustedfirmware-a.readthedocs.io/en/latest/plat/arm/fvp/index.html has something useful for you.

**Comment by PandaQ2014** [comment]
I have solved this problem under your advice.
Here is my start parameters of FVP base model,
``` makefile
run-only:
	@cd $(FOUNDATION_PATH); \
	$(FOUNDATION_PATH)/models/Linux64_GCC-4.9/FVP_Base_RevC-2xAEMv8A \
	-C pctl.startup=0.0.0.0 		\
	-C bp.secure_memory=1			\
	-C bp.tzc_400.diagnostics=1  		\
	-C cluster0.NUM_CORES=4 				\
	-C cluster1.NUM_CORES=4 				\
	-C cache_state_modelled=1 				\
	--data "$(TF_A_PATH)/build/fvp/$(TF_A_BUILD)/bl1.bin"@0x0 		\
	--data "$(TF_A_PATH)/build/fvp/$(TF_A_BUILD)/fip.bin"@0x8000000 	\
	-C bp.virtioblockdevice.image_path="$(BOOT_IMG)"
```
What's more, I replace DTB file "foundation-v8-gicv3-psci.dtb" with "fvp-base-revc.dtb"  and add 
``` 
        firmware {
                optee {
                        compatible = "linaro,optee-tz";
                        method = "smc";
                };
        }; 
```
in its dts file based your answer in https://github.com/OP-TEE/optee_os/issues/735 , and finally it works.
Thank you for your help!

**Comment by jbech-linaro** [comment]
> I have solved this problem under your advice.

If you have time and feel for it, feel free to add a section about this in our documentation, somewhere at [FVP page](https://optee.readthedocs.io/en/latest/building/devices/fvp.html). In any case, glad that you've managed to get it working!

**Comment by PandaQ2014** [comment]
> If you have time and feel for it, feel free to add a section about this in our documentation, somewhere at [FVP page](https://optee.readthedocs.io/en/latest/building/devices/fvp.html).

Ok, I will try 😃
