### ISSUE TITLE
non-secure external DT found

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3452]
What does this error mean?

![non-secure external DT found](https://user-images.githubusercontent.com/30496643/70138927-a86ce800-1691-11ea-9ef4-8c85f7cdca2e.PNG)

**Comment by jbech-linaro** [comment]
I'm almost sure that it means that TEE core didn't find any non-secure external Device Tree.

For some reason on your device/setup there is no DT-blob passed to to the TEE (here probably: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/generic_entry_a32.S#L520). Goofed around with `CFG_DT_ADDR`? https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/generic_entry_a32.S#L187-L191
