### ISSUE TITLE
Clarification needed: Rollback protection & compromised tee-supplicant

### ISSUE THREAD

**Issue by crtxcr** [OP-TEE/optee_os#3454]
Reading and writing to the secure storage ultimately passes the tee-supplicant, which lives in the untrusted REE. I have consulted the documentation regarding secure storage, but I am not sure what happens in the following scenario, which is relevant for an application I am writing. It's possible it has already been discussed (but I haven't found anything on that), or that the answer is obvious.

Scenario: Malicious tee-supplicant reports success, but never wrote the data

- TA reads a counter value from a persistent object (application specific data object). Let's assume the counter value is "4". 
- TA increments the counter value, now "5". Then TA wants to save that new value to the secure storage. 
- That data passes the tee-supplicant (protected by certain cryptography). However, a malicious tee-supplicant service simply can report to the secure world that the data has been written, when it actually wasn't. The malicious tee-supplicant service simply would not write anything to the RPMB (and REE FS), but simply report to the secure world that the data was successfully written. 
- TA (maybe a different instance of it) reads data from the persistent object. It therefore gets the old data, and thus the counter value of "4". 

So in this case, stricly speaking no data was rolled back - it simply wasn't updated and old data was presented to the secure world by an attacker. This is not a rollback as far as the storage itself is concerned, however an old state has been presented to the TA by an attacker.

Would the secure storage implementation of OPTEE always detect such an attack or is it up to the TA to figure out a mechanism to do that? (e. g. by caching old values and compared the just read values. But the only way to do that in a way safe from a compromised tee-supplicant is to keep it in memory, which maybe isn't that simple for multi-instance TAs, and also does not survive reboots etc.).

**Comment by jforissier** [comment]
> The malicious tee-supplicant service simply would not write anything to the RPMB (and REE FS), but simply report to the secure world that the data was successfully written.

Assuming RPMB is enabled, that should be detected by the OP-TEE because RPMB has its own write counter, so you cannot replay data. RPMB responses are encrypted and authenticated, so they can't be faked either.
