### ISSUE TITLE
why  in  TA code no printf output and how to disable  [-Werror=implicit-function-declaration]

### ISSUE THREAD

**Issue by gitgonewithwind** [OP-TEE/optee_os#3456]
hi I tried to add printf in hello_world_ta.c, but there was no output in minicom terminal,but why in main.c , I can find the printf output  "Invoking TA to increment 42"

and I tried to and the system function in TA to touch a file for test(I add header file too), but warning as error happened, can not pass compilation. how to remove the Werror? I tried a few ways to do ,but can not. it seems I can not add any functions in it(only I can add printf, there is no complain,but no output. I tried to add sleep(3) and header to test too)

and I do not find   DMSG("has been called"); in hello_worl_ta.c otput too.
Thanks.

 -----

hello_world_ta.c:158:3: error: implicit declaration of function ‘system’ [-Werror=implicit-function-declaration]

system("touch test.txt");
   ^~~~~~
hello_world_ta.c:158:3: warning: nested extern declaration of ‘system’ [-Wnested-externs]
cc1: some warnings being treated as errors

**Comment by jforissier** [comment]
- `printf()` in a TA sends output to the secure console, not the Linux non-secure one.
- The `system()` and `sleep()` functions are not available to TAs.

**Comment by gitgonewithwind** [comment]
@jforissier  so 1. no way to find the printf() output in TA?
                        2. my company's application code has  system() ,sleep() ..functions , how can I replace them in TA? anyway, I am learning and understand how to write the TA.  in my understanding, I put my company's application code into TA, so I can protect my code to be stolen.

**Comment by jforissier** [comment]
1. The secure console is the terminal where you can see all the OP-TEE messages. Where exactly, it depends on the platform. QEMU for instance has two terminals, one for normal world, one for secure world. HiKey and HiKey960 send the secure output to the same UART. What platform are you using?

2. `sleep()` can be replaced by `TEE_Wait()`. There is no replacement for `system()`.

**Comment by gitgonewithwind** [comment]
@jforissier  Thank you very much for you replace so soon

my board is  imx-mx7dpico_mbl    (TechNexion imx7-pico-pi)

**Comment by jforissier** [comment]
OK, I don't know this board specifically, but I see in the code that the secure console is initially set to UART5 (address 0x30A70000). Do you have a serial adapter connected to this UART? You should see the OP-TEE messages there upon boot.
I also see that OP-TEE on this platform uses the device tree (CFG_DT=y), so check the `/secure-chosen/stdout-path` and `/chosen/stdout-path` nodes. These nodes can change the output as described here: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings/arm/secure.txt?h=v5.5-rc1#n56.

The functions that you can use in a TA are the TEE Internal Core API v1.1 (see the GlobalPlatform specification), plus some functions from libc mainly. You can find the complete list in the include folder of the build directory: `optee_os/out/*/export-ta_*/include/*`

**Comment by gitgonewithwind** [comment]
@jforissier  thank you very much.
 let's me check the datasheet about the board to find  the Uart5.

**Comment by gitgonewithwind** [comment]
@jforissier  I checked the datasheet.  the UART5 is connected to   the usb debug port for this board.
I always use it. but no output.    only output host code info:
Invoking TA to increment 42                                                     
TA incremented value to 43
   (https://s3.us-east-2.amazonaws.com/technexion/documentation/pico-pi-imx7-rev-b1.pdf      page 17 ,49)
I do not find the /secure-chosen/stdout-path and /chosen/stdout-path nodes

**Comment by gitgonewithwind** [comment]
@jforissier  sorry to bother you again.
1. I checked my secure console  is uart5. which is same as the the normal console. but no output.
2. I do not know the meaning at here you mentioned. do you mean if I change it in DTS, I can find the output? I added the below in imx7d-pico.dts, but no output.

+        chosen {
+                stdout-path = &uart5;
+        };

&uart5 {
        pinctrl-names = "default";
        pinctrl-0 = <&pinctrl_uart5>;
        assigned-clocks = <&clks IMX7D_UART5_ROOT_SRC>;
        assigned-clock-parents = <&clks IMX7D_PLL_SYS_MAIN_240M_CLK>;
        status = "okay";
+        secure-status = "okay";
};


https://git.kernel.org/pub/scm/linux/ke
rnel/git/torvalds/linux.git/tree/Documentation/devicetree/bindings/arm/secure.txt?h=v5.5-rc1#n56.

3. do I need set  CFG_TEE_CORE_LOG_LEVEL or CFG_TEE_TA_LOG_LEVEL to some value?
current the CFG_TEE_CORE_LOG_LEVEL is 1 when build optee-os.

Thank you very much for reply very soon.

**Comment by jforissier** [comment]
Set `CFG_TEE_CORE_LOG_LEVEL=2` and you should see the OP-TEE banner (version etc.). You don't need to change the DT I think.
You may want to set `CFG_TEE_TA_LOG_LEVEL=2` too, although I think it should not affect `printf()`.

**Comment by gitgonewithwind** [comment]
@jforissier  I set CFG_TEE_CORE_LOG_LEVEL=4 in optee-os (for me in yocto). there are a lot of info display, but still  no printf() and DMSG(). output.  currently I set CFG_TEE_TA_LOG_LEVEL=0 in TA Makefile in hello_world

let try to find where to set CFG_TEE_TA_LOG_LEVEL=2  in TA make or somewhere in optee-os building.
do you mean I set CFG_TEE_TA_LOG_LEVEL=2 in TA Makefile in hello_world

...

D/LD:  ldelf:169 ELF (8e4a565e-036b-4b44-bf7a-17e829b3727e) at 0x10e000                                                                    
F/TC:? 0 trace_syscall:127 syscall #6 (syscall_close_ta_session)                                                                           
D/TC:? 0 tee_ta_close_session:499 csess 0x9e069560 id 1                                                                                    
D/TC:? 0 tee_ta_close_session:518 Destroy session                                                                                          
Invoking TA to increment 42                                                                                                                
D/TC:? 0 tee_ta_close_session:499 csess 0x9e069978 id 1                                                                                    
TA incremented value to 43                                                                                                                 
D/TC:? 0 tee_ta_close_session:518 Destroy session                                                                                          
D/TC:? 0 destroy_context:298 Destroy TA ctx (0x9e069938)
...

**Comment by jforissier** [comment]
Set `CFG_TEE_TA_LOG_LEVEL=2` for the TEE core and the TA as well.

The log variables are documented here: https://github.com/OP-TEE/optee_os/blob/master/mk/config.mk#L44-L58

**Comment by gitgonewithwind** [comment]
@jforissier  thank you very much.
I found the location to change the CFG_TEE_TA_LOG_LEVEL in yocto.
printf() and DMSG()  output works well.
please close the issue.
thanks again,
Have a good night.

**Comment by jforissier** [comment]
Glad you got it working!
