### ISSUE TITLE
Qemu v8: loading a statically linked library

### ISSUE THREAD

**Issue by MQuaresma** [OP-TEE/optee_os#3458]
I'm developing a qualified digital signature TA that needs to create a CSR inside the secure environment. To do this I'm using mbed-tls, however, since OP-TEE OS only compiles one module of the ARM-mbed TLS library, I need to statically link the X509 and crypto module.
This much I've managed to achieve however, this leads to a pretty big binary which, when loaded, ends up using more memory than it's allowed for the code region. As this is due to the static libraries, increasing the stack or heap size doesn't help. Is there anything I'm missing?
Here are the headers:
```
#include<mbedtls/x509.h>
#include<mbedtls/x509_csr.h>
#include<mbedtls/pk.h>
```
and linker flags:
```
libnames += mbedx509 mbedcrypto
```
I'm using.

**Comment by jenswi-linaro** [comment]
We're doing some CSR stuff in `optee_test/ta/crypt/mbedtls_taf.c` so at least partial support is already available. I'd recommend adding whatever options are needed in `optee_os/ lib/libmbedtls/include/mbedtls_config_uta.h`.

**Comment by MQuaresma** [comment]
Thanks, defining `MBEDTLS_X509_CSR_WRITE_C` solved the problem! I had looked into that header file but though the flags should be changed somewhere else.
