### ISSUE TITLE
Cannot find symbol __init_end when building optee_os

### ISSUE THREAD

**Issue by glneo** [OP-TEE/optee_os#3459]
I'm doing the build with:
`make PLATFORM=ti-am43xx build/core/tee.bin`
But get:
`Cannot find symbol __init_end`
Looks like that symbol is only defined if CFG_WITH_PAGER is defined, which is not used for this platform.

Also I'm seeing:
`Warning: build/core/tee.bin is deprecated`
What is the new equivalent for this binary?

Andrew

**Comment by vchong** [comment]
Hi Andrew,

You need #3425 and #3430.

> What is the new equivalent for this binary?

Not 100% sure the proper way to go about this but you might be able to get away with `cat tee-header_v2.bin tee-pager_v2.bin > tee_v2.bin`. The maintainers will probably have better ideas.

Cheers

**Comment by glneo** [comment]
I'm on latest master, which seems to have both of those PRs, but still see the issue.

Also, what reason do we have to deprecate the v1 image format. We only have support v1 baked into our ROM, (well a ROM patch, but that is TI signed and not going to be updated).

**Comment by jenswi-linaro** [comment]
Build error hopefully fixed in https://github.com/OP-TEE/optee_os/pull/3464

**Comment by vchong** [comment]
> Also, what reason do we have to deprecate the v1 image format. We only have support v1 baked into our ROM, (well a ROM patch, but that is TI signed and not going to be updated).

Not sure the reason but fyi "the files (images) can still be generated by supplying the complete output path as a target to make." Re: https://github.com/OP-TEE/optee_os/commit/b526f8f7f70806f6f76725c8f2733d97d6426093.

**Comment by jenswi-linaro** [comment]
With the introduction of the v2 format the old v1 format became redundant. To reduce maintenance and the baggage we'd like to get rid of the v1 format at some point. Deprecating its use is the first step. We'll keep it supported until it can be safely removed. It's good to know that TI has a strong dependency towards the v1 format.

**Comment by glneo** [comment]
Fixed by #3464
