### ISSUE TITLE
Generating - not appending- a new DTB overlay

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#3470]
When **CFG_EXTERNAL_DTB_OVERLAY** is enabled, OP-TEE is capable of appending but also generating new overlays containing psci and reserved-memory fragments.

Appending occurs when OP-TEE is provided a DTB overlay at **CFG_DT_ADDR** or passed in **arg2**. Otherwise it defaults to generation.

We noticed that the reserved-memory fragments on any newly generated overlay defaults the node's _#address-cells_ and _#size-cells_ to 2.

Should these properties be made available via some CFG_  instead? 

thanks

Would something like the following be an acceptable solution?
foundriesio/meta-lmp@3a5fa04

**Comment by ldts** [comment]
Would something like the following be an acceptable solution?

https://github.com/foundriesio/meta-lmp/pull/124/commits/3a5fa042371ca4187030db1ace207300130f80c8

**Comment by jenswi-linaro** [comment]
> We noticed that the reserved-memory fragments on any newly generated overlay defaults the node's _#address-cells_ and _#size-cells_ to 2.


I don't see where the default values are assigned. Can you give a pointer to the code, please?


> Should these properties be made available via some CFG_ instead?

What is the problem you're solving?
Would it be OK to default to `sizeof(long)` instead or perhaps `sizeof(paddr_t)`, depending on the problem?
I don't mind a few extra config flags, but if there's an easier working solution I'd prefer that since it's less work for everyone.

**Comment by ldts** [comment]
sorry yes, add_res_mem_dt_node(...) gets the #size-cells and #address-cells from a previous overlay passed in CFG_DT_ADDR or arg2. 

When no overlay is provided -we are just generating a new one from scratch - those functions will default to 2 for both properties; this is not proper for 32 bit architectures hence why I think that a CFG_option is probably the easiest solution.

**Comment by jenswi-linaro** [comment]
> ...this is not proper for 32 bit architectures...

I'm sorry, this is not obvious to me. Can you elaborate please?

**Comment by ldts** [comment]
right, so #address-cells indicates how many cells (32 bit values) are needed to form the base address part in the reg property. 

Systems running on 32 bits do not need 64 bit addresses (2 cells)..therefore on such systems (arm) an overlay that describes reserved-memory fragments using 64 bit addresses is not correct (certainly is not standard, not sure if there can be some weird scenario that justifies this).

My point is rather than defaulting to a compiled in value (2 cells), we give the choice to the user to overload such a default value via CFG

**Comment by jenswi-linaro** [comment]
> Systems running on 32 bits do not need 64 bit addresses...

Even with LPAE?

So `sizeof(paddr_t) / sizeof(uint32_t)` should most likely give the desired `#address-cells`. See:
https://github.com/OP-TEE/optee_os/blob/15ba8c1f4c9e41016104425e94dad2eedf2b38fd/lib/libutils/ext/include/types_ext.h#L20-L32

If that still doesn't solve your issue please create a PR with the needed config variables.

**Comment by jenswi-linaro** [comment]
Given that you just created #3481 I guess you've determined that `sizeof(paddr_t) / sizeof(uint32_t)` isn't good enough. Would you mind explaining how, to help me understand?

**Comment by ldts** [comment]
hello @jenswi-linaro : I don't think I can fully answer that question but your proposal has a wider reach as it affects the behavior for all users under all circumstances whereas mine still defaults to 2 cells unless explicitly requested.  Also your proposal is not clear enough for me to comment since I am not quite sure where would you add this change:.

1) For example are you suggesting you will post that proposal to libfdt and default to that new construct instead of the hard-coded value of 2?  libfdt from what I could read followed the IEEE 1275 recommendation on that subject: "if #address-cells is missing it should be treated as equal to 2" so I don't think that would prosper.

2) Assuming that your question looks up to my implementation to replace the CONFIG with this instead I thought the discussion would be better had in my PR and not here? Anyways, as far as I am concerned, sure I could replace the config with what you suggest, that sounds very reasonable to me as it addresses the issue that we see during the imx7ulp new overlay generation.  And it has the advantage of making sure OP-TEE's LPAE configuration matches that of the overlay user.
Please let me know if you prefer doing this instead of the config and I will amend it.

Also may I suggest that we update libfdt to a more recent release? 1.4.1 is already over five years old so we could be missing some fixes (ie . https://github.com/dgibson/dtc/commit/b8d6eca78210952c6d93235c38ebd5836d6409c4#diff-0aeab6f3f34641516118a2778bbdc55d )

**Comment by jforissier** [comment]
> Also may I suggest that we update libfdt to a more recent release? 1.4.1 is already over five years old 

We can certainly upgrade, but note that OP-TEE master currently uses 1.4.6+ [1], not 1.4.1. This version is about 2 years old now. I'm adding this item to my to-do list, but feel free to propose a PR if you'd like to get it done in a specific timeframe :)

[1] 1.4.6-9 according to [this commit](https://github.com/OP-TEE/optee_os/commit/01d6a9da) although I could not find such a tag in the [DTC repo](https://github.com/dgibson/dtc).

**Comment by ldts** [comment]
ah sorry yes you are right (it was upgraded not that long ago - I missed that one)!

Btw, may I ask you to test the imx7ulp watchdog again whenever and if you can find some time?- we fixed it in our platform but required uboot/linux and certainly optee changes. Of course if you cant I understand, not a problem.

but if you do, mind adding the following and validating the reboot? I suspect that what you see upstream is just a reset due to an access violation in optee. with the change below you should see a countdown of ~8 seconds before reset.

if you dont see the countdown I will send a fix but to save everyones time I want to make sure it is not due to the ip version I am using.

diff --git a/core/drivers/imx_wdog.c b/core/drivers/imx_wdog.c
index 83f461c2..76e118f2 100644
--- a/core/drivers/imx_wdog.c
+++ b/core/drivers/imx_wdog.c
@@ -61,7 +61,7 @@ void imx_wdog_restart(void)
        io_write32(wdog_base + WDOG_CS, val | WDOG_CS_EN);

        io_write32(wdog_base + WDOG_CNT, UNLOCK);
-   io_write32(wdog_base + WDOG_TOVAL, 1000);
+ io_write32(wdog_base + WDOG_TOVAL, 8000);
        io_write32(wdog_base + WDOG_CNT, REFRESH);
 #else
        if (ext_reset)
@@ -83,8 +83,9 @@ void imx_wdog_restart(void)
        io_write16(wdog_base + WDT_WCR, val);
 #endif

-   while (1)
-           ;
+ while (1) {
+         EMSG("counting - 0x%x\n", io_read32(wdog_base + WDOG_CNT));
+ }
 }

**Comment by ldts** [comment]
can anyone add a bug label to this issue please? currently op-tee is generating invalid properties so I think it is probably a good idea to add it to some todo list.

**Comment by jforissier** [comment]
@ldts FYI https://github.com/OP-TEE/optee_os/pull/3563.
