### ISSUE TITLE
TEE_OperationInfo.digestLength is always 0

### ISSUE THREAD

**Issue by crtxcr** [OP-TEE/optee_os#3471]
```
	TEE_OperationHandle ophandle;
	TEE_AllocateOperation(&ophandle, TEE_ALG_SHA256, TEE_MODE_DIGEST, 0);

	TEE_OperationInfo opinfo;
	TEE_GetOperationInfo(ophandle, &opinfo);
```
From Spec, 6.2.3:
> digestLength : For a MAC, AE, or Digest digest, describes the number of bytes in the digest or tag

After this code, I expect opinfo.digestLength to contain the bytes required to store a SHA256 hash (32). But it is 0 for me.

In fact, I can't see anywhere in the code where digestLength is being set: 
https://github.com/OP-TEE/optee_os/search?q=digestLength&unscoped_q=digestLength

Maybe it was just forgotten?

**Comment by jforissier** [comment]
Hi @crtxcr,

Thanks for reporting this. I think it is an oversight indeed. `.digestLength` should probably be set by `TEE_AllocateOperation()` in `lib/libutee/tee_api_operations.c`. Would you propose a patch for this?

Thanks.

**Comment by crtxcr** [comment]
Hi,

In general I can provide a patch for this, but I am not sure when I can find time to do it as I'll be quite busy for the following months.

**Comment by crtxcr** [comment]
Reopening, will provide a patch around March.
