### ISSUE TITLE
no module named cryptodome

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3472]
Any idea about this error? i´m trying compile the last version.
(command: $make -j `nproc` )

![error](https://user-images.githubusercontent.com/30496643/70797921-e1017580-1da5-11ea-9bb2-6d945d3d59e6.PNG)

**Comment by jbech-linaro** [comment]
Hi, known issue, missing Python package, please see https://github.com/OP-TEE/build/issues/401 for more info.
