### ISSUE TITLE
how can I   defend against "code theft" ,there a lot  of functions in my company's app code which can not support in  TEE Internal Core API .

### ISSUE THREAD

**Issue by gitgonewithwind** [OP-TEE/optee_os#3474]
Hi all, 
sorry to bother again.
I want to put my company's app code in the the TA (for example,I simply insert  my code in  hello_world_ta.c).
but now I know  we only can use TEE Internal Core API functions in TA or some std c libs,right? so I can not pass the compilation(for example, I need UDP, websocket ...  library ..) , for example, the below header files can not find in optee_os/out/*/export-ta_*/include/*. It looks like  we only can write some simple or small  TA code?

How  can I defend against "code theft"? or can I directly hide my app executable code(NOT TA) in secure storage ?
if possible, where can I find the guide?

.........
TA can not support below header and functions in them:

//#include <netinet/in.h>
//#include <poll.h>
//#include <math.h>

//#include <arpa/inet.h>

//#include <linux/if_packet.h>

//#include <sys/ioctl.h>
#include <sys/ioctl.h>

**Comment by jbech-linaro** [comment]
In `optee_os.git`, do:
```bash
$ find lib/ -name "*.h"
```
Based on the output there you can figure out what you **can** and what you **cannot** do. Most likely the stuff you're asking about is, **or** would be expected to be found the `lib/libutils/isoc/include/` folder.  But, that is just a subset of normal libc functions. I.e., a far from complete list of files/functions. Historically we've added/imported things into that folder when a) we have seen the need for it b) it isn't too invasive/complex that we believe it'll affect the security itself.

**Comment by gitgonewithwind** [comment]
@jbech-linaro  Thank you very much for your reply.
I need more libraries for my app code. how  can I do ? Can I add the library's source code which  is not  included by the   optee internal API? 
It looks like that it is  impossible  to  change my app code to TA because of missing many head files.

**Comment by jbech-linaro** [comment]
Two options
1. Import needed h-files / libraries into the optee_os project and send a pull request for that here on GitHub.
2. Import needed h-files / libraries into the optee_os project and keep a fork for yourself.

As you can see both starts with the same, the latter part is whether you think it is useful for others and the project itself. I.e., if you think that the files and libraries that you import are useful to other OP-TEE developers, then by all means submit a pull request for it. You are helping the community by doing so.

**Comment by gitgonewithwind** [comment]
@jbech-linaro  thanks.
if possible, for beginning, I choose No. 2.
1.so I want to know I need Import source code (not only header files but also all source code ,right?) to some where in optee_os project, right?  
2. DO NOT need change the source code ,right? just simply to put the source in the optee_os project?
3.it look like it's a heavy  duty.

4. let's check the optee_os library folder structures to find  how to import and where to import.  DO you have a guide for this kind of porting?

Thanks.

**Comment by jbech-linaro** [comment]
> 1.so I want to know I need Import source code (not only header files but also all source code ,right?) to some where in optee_os project, right?

Yes

> 2. DO NOT need change the source code ,right? just simply to put the source in the optee_os project?

You probably need to add both c and h files, they most often goes hand in hand.

> 3.it look like it's a heavy duty.

Depends, in some cases we've just copied files from for example newlib into optee_os without having to do many if any modifications. But if you're using a big library then it can be a lot of work.

> 4. let's check the optee_os library folder structures to find how to import and where to import. DO you have a guide for this kind of porting?

Unfortunately not, we only have a short description of it [here](https://optee.readthedocs.io/en/latest/architecture/libraries.html). But have a look at other libraries and h-files have been added (use git blame and git log). This commit
```patch
commit a97bc4a084f1292c3a2cfd0c4593183b2f873e67
Author: Jens Wiklander <jens.wiklander@linaro.org>
Date:   Fri May 18 15:49:22 2018 +0200

    libmbedtls: configure and compile mbedtls
```
might also be a good example.

**Comment by gitgonewithwind** [comment]
@jbech-linaro  Thanks.
let me try to do.
have  a good day.

**Comment by gitgonewithwind** [comment]
@jbech-linaro  sorry to brother you again
I do not knowe where I can find the correct .c source code.
for exampe, I need dirent.h   header file. I can copy from toolchains folder: ./aarch32/arm-linux-gnueabi/libc/usr/include/bits/dirent.h ( I also can copy from my yocto toolchain I made by yocto compilation, the fiels almost are same)

but in the header file dirent.h, there is  a function opendir: 

extern DIR *opendir (const char *__name) __nonnull ((1));

it looks like I need .c file opendir.c 

where can I find the correct  one .c source code?

where you import them, where do you get from?  for exmaple, where are from the .c files always included in optee_os/lib/libutils/isoc/newlib/*.c   ?

thanks



for exmaple in my yocto build foder , I found the below. which one is correct or no one is correct.


find . -name opendir.c
./tmp/work/x86_64-nativesdk-oesdk-linux/nativesdk-m4/1.4.18-r0/m4-1.4.18/tests/opendir.c
./tmp/work/x86_64-nativesdk-oesdk-linux/nativesdk-gettext/0.19.8.1-r0/gettext-0.19.8.1/gettext-tools/gnulib-lib/opendir.c
./tmp/work/x86_64-nativesdk-oesdk-linux/nativesdk-glibc/2.29-r0/git/dirent/opendir.c
./tmp/work/x86_64-nativesdk-oesdk-linux/nativesdk-glibc/2.29-r0/git/sysdeps/mach/hurd/opendir.c
./tmp/work/x86_64-nativesdk-oesdk-linux/nativesdk-glibc/2.29-r0/git/sysdeps/posix/opendir.c
./tmp/work/x86_64-nativesdk-oesdk-linux/nativesdk-pseudo/1.9.0+gitAUTOINC+3fa7c853e0-r0/git/ports/unix/guts/opendir.c
./tmp/work/x86_64-nativesdk-oesdk-linux/nativesdk-pseudo/1.9.0+gitAUTOINC+3fa7c853e0-r0/package/usr/src/debug/nativesdk-pseudo/1.9.0+gitAUTOINC+3fa7c853e0-r0/git/ports/unix/guts/opendir.c
./tmp/work/x86_64-nativesdk-oesdk-linux/nativesdk-pseudo/1.9.0+gitAUTOINC+3fa7c853e0-r0/packages-split/nativesdk-pseudo-src/usr/src/debug/nativesdk-pseudo/1.9.0+gitAUTOINC+3fa7c853e0-r0/git/ports/unix/guts/opendir.c
./tmp/work/x86_64-nativesdk-oesdk-linux/gdb-cross-canadian-arm/8.2.1-r0/gdb-8.2.1/gdb/gnulib/import/opendir.c

**Comment by jbech-linaro** [comment]
> @jbech-linaro sorry to brother you again
> I do not know where I can find the correct .c source code.
> ...

Sorry, I don't know the answers to this myself. I would basically have to do the same exercise on my side to be able give you a good answer.

**Comment by gitgonewithwind** [comment]
@jbech-linaro 
Thank you very much for your kind reply so soon
I keep researching and waiting for your answers.

**Comment by jbech-linaro** [comment]
> I keep researching and waiting for your answers.

I hope I didn't give false impression that I was going to investigate. Even though I'd be happy to help out, I don't have time to dig into this.

**Comment by gitgonewithwind** [comment]
that's fine. let me try to find the solution.
if anyone knows, please tell me.
thanks

**Comment by gitgonewithwind** [comment]
it look like the source code from glibc ?

**Comment by gitgonewithwind** [comment]
hi
I tried to add glibc dirent code in optee_os lib to support optee API can operate directory. I did lots of work to build it.  with comand line:
 but there is a error:
CHK     out/arm/core/include/generated/imx_pm_asm_defines.h
  CC      out/arm/ldelf-lib/dirent/opendir.o
In file included from ../glibc/include/limits.h:124,
                 from ../glibc/sysdeps/pthread/allocalim.h:20,
                 from ../glibc/include/alloca.h:24,
                 from ../glibc/stdlib/stdlib.h:568,
                 from ../glibc/include/stdlib.h:6,
                 from ../glibc/include/atomic.h:48,
                 from ../glibc/sysdeps/nptl/lowlevellock.h:22,
                 from ../glibc/sysdeps/nptl/libc-lockP.h:33,
                 from ../glibc/sysdeps/nptl/libc-lock.h:184,
                 from ../glibc/sysdeps/posix/dirstream.h:23,
                 from ../glibc/include/dirent.h:3,
                 from lib/dirent/opendir.c:18:
lib/libutils/isoc/include/limits.h:27: error: "MB_LEN_MAX" redefined [-Werror]
 #define MB_LEN_MAX 1

------
that means: the original optee_os source code , there is a header file at  lib/libutils/isoc/include/limits.h

but when I add glibc dirent folder in optee_os/lib/dirent. I also include another limits.h in glibc. 
how can i remove one?
anyone, any help?
thanks.



-------




~/work/optee_os$ make FG_TEE_BENCHMARK=n     CFG_TEE_CORE_LOG_LEVEL=3     CROSS_COMPILE=arm-linux-gnueabi-     CROSS_COMPILE_core=arm-linux-gnueabi-     CROSS_COMPILE_ta_arm32=arm-linux-gnueabi-     CROSS_COMPILE_ta_arm64=aarch64-linux-gnu-     DEBUG=1     O=out/arm     PLATFORM=imx-mx7dpico_mbl
-----
my sub.mk in optee_os/lib/dirent

incdirs-y +=../usr/include
srcs-y += opendir.c
srcs-y += closedir.c
srcs-y += readdir.c
srcs-y += readdir_r.c
srcs-y += rewinddir.c
srcs-y += seekdir.c
srcs-y += telldir.c
srcs-y += scandir.c
srcs-y += alphasort.c
srcs-y += versionsort.c
srcs-y += getdents.c
srcs-y += getdents64.c
srcs-y += dirfd.c
srcs-y += readdir64.c
srcs-y += readdir64_r.c
srcs-y += scandir64.c
srcs-y += alphasort64.c
srcs-y += versionsort64.c
srcs-y += fdopendir.c
srcs-y += scandirat.c
incdirs-y +=../usr/include
srcs-y += opendir.c
srcs-y += closedir.c
srcs-y += readdir.c
srcs-y += readdir_r.c
srcs-y += rewinddir.c
srcs-y += seekdir.c
srcs-y += telldir.c
srcs-y += scandir.c
srcs-y += alphasort.c
srcs-y += versionsort.c
srcs-y += getdents.c
srcs-y += getdents64.c
srcs-y += dirfd.c
srcs-y += readdir64.c
srcs-y += readdir64_r.c
srcs-y += scandir64.c
srcs-y += alphasort64.c
srcs-y += versionsort64.c
srcs-y += fdopendir.c
srcs-y += scandirat.c
cflags-y += -c -std=gnu11 -fgnu89-inline  -g -O2 -Wall -Wno-unused-parameter -Wno-cast-align -Wno-redundant-decls -Wwrite-strings -Wundef -Werror -fmerge-all-constants -frounding-math -fno-stack-protector -Wstrict-prototypes -Wold-style-definition -fmath-errno   -fPIC   -ftls-model=initial-exec      -I../glibc/include   -I../glibc/sysdeps/unix/sysv/linux/arm/le  -I../glibc/sysdeps/unix/sysv/linux/arm  -I../glibc/sysdeps/arm/nptl  -I../glibc/sysdeps/unix/sysv/linux/include -I../glibc/sysdeps/unix/sysv/linux  -I../glibc/sysdeps/nptl  -I../glibc/sysdeps/pthread  -I../glibc/sysdeps/gnu  -I../glibc/sysdeps/unix/inet  -I../glibc/sysdeps/unix/sysv  -I../glibc/sysdeps/unix/arm  -I../glibc/sysdeps/unix  -I../glibc/sysdeps/posix  -I../glibc/sysdeps/arm/le/armv7/multiarch  -I../glibc/sysdeps/arm/armv7/multiarch  -I../glibc/sysdeps/arm/le/armv7  -I../glibc/sysdeps/arm/armv7  -I../glibc/sysdeps/arm/armv6t2  -I../glibc/sysdeps/arm/armv6  -I../glibc/sysdeps/arm/le  -I../glibc/sysdeps/arm/include -I../glibc/sysdeps/arm  -I../glibc/sysdeps/wordsize-32  -I../glibc/sysdeps/ieee754/flt-32  -I../glibc/sysdeps/ieee754/dbl-64  -I../glibc/sysdeps/ieee754  -I../glibc/sysdeps/generic -I../glibc -I../glibc/libio -I../dirent -I/home/rnd2/work/optee_os/lib/glibc_sub -D_LIBC_REENTRANT -include /home/rnd2/work/optee_os/lib/glibc_sub/libc-modules.h -DMODULE_NAME=libc -include ../include/libc-symbols.h  -DPIC -DSHARED     -DTOP_NAMESPACE=glibc

**Comment by gitgonewithwind** [comment]
please open it again.


I added a dirent folder in lib and modified something, but link error:
I think the  reference exist there, but why error happened.



CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
  LD      out/arm/ldelf/ldelf.elf
out/arm/ldelf/main.o: In function `print_to_console':
/home/rnd2/work/optee_os/ldelf/main.c:28: undefined reference to `trace_vprintf'
out/arm/ldelf/main.o:(.ARM.exidx.text.print_to_console+0x0): undefined reference to `__aeabi_unwind_cpp_pr1'
out/arm/ldelf/main.o: In function `dump_ta_state':

**Comment by jforissier** [comment]
What are you trying to do with the `dirent` functions? I mean, when you call `opendir()` in your TA, what do you expect it will do?
1. Open a directory in secure storage? The problem is, there is no such thing as directories in secure storage. TA can only access "persistent objects" which are similar to files, but all the files are in the same "directory" for a given TA. You can enumerate objects with ` TEE_GetNextPersistentObject()` etc.
2. Open a directory in the normal world (Linux)? This won't work either I'm afraid, because TAs currently don't have access to the normal world filesystem. If it is what you are trying to do, then maybe you could do it in the client application instead?

**Comment by gitgonewithwind** [comment]
@jforissier 
I just discussed with my manager. 
Can I do like below:
1. encrypt the app executable binary code first.
2. use   client application send the encrypted binary to TA
3. use TA decrypt the  encrypted binary  to normal binary.
4. send back normal binary to client in RAM and run it ????

thank you very much.

**Comment by jforissier** [comment]
@jforissier it should work.

**Comment by gitgonewithwind** [comment]
thanks. I am reading the aes example which is encrypt and decrypt in same code  . now I need separate  and save one fixed public key  to somewhere to encrypt my binary in all my boards.
TA only decrypt it.
any idea?
