### ISSUE TITLE
Does optee-os have time-out mechanism to ensure that executing will not stall into ta code?

### ISSUE THREAD

**Issue by louisjohn0416** [OP-TEE/optee_os#348]
i got that ta timeout value, said TEE_TIMEOUT_INFINITE, from this piece of code:
res = tee_ta_open_session(&res_orig, &s, &tee_open_sessions, &in->uuid,
            clnt_id, TEE_TIMEOUT_INFINITE, param);

does this mean ta can infinitely trap into its own code without any timeout mechanism ?

**Comment by jenswi-linaro** [comment]
Yes, and even if a timeout is specified it's only an advice. The TA can still refuse to timeout/cancel.

**Comment by louisjohn0416** [comment]
thanks very much, one more question: a normal world cpu execute "smc" to request secure world do something for it, is it the same cpu entering secure world to process it or it could assign other cpu to do
it in secure world ?

**Comment by jenswi-linaro** [comment]
Yes, it's the same CPU. It's similar to how the "svc" instruction works from user space.

**Comment by louisjohn0416** [comment]
thank you !
