### ISSUE TITLE
Questions about dynamic shared buffer

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#3482]
Hi, I have some questions about dynamic shared memory:
1.  From https://optee.readthedocs.io/en/latest/architecture/core.html?highlight=dynamic%20share%20memory#shared-memory, it mentions "OP-TEE supports two kinds of shared memory areas: a **mandatory** area for contiguous buffers an optional extra memory areas for noncontiguous buffers." So does it mean static shared memory is a must even if dynamic shared memory is enabled?

2.  How could opteeos to support dynamic shared memory besides setting CFG_CORE_DYN_SHM? It seems register_ddr(addr, size) should be used to generate phys_ddr_overall to tell opteeos the range of the dynamic shared memory. But what's the difference from phys_ddr_overall from phys_nsec_ddr? Does phys_ddr_overall also include other types of memory like secure memory? 
Why phys_nsec_ddr and phys_ddr_overall can't be defined together? 

```
1047 >-------/* Platform cannot define nsec_ddr && overall_ddr */
1048 >-------assert(phys_nsec_ddr_begin == phys_nsec_ddr_end);
```

Thanks.

**Comment by lorc** [comment]
Hi @tiger20081015,

I believe we need to update documentation. With the latest patches to linux kernel driver static shared buffer is no longer mandatory. At least from client side. And it indeed can work only with dynamic  shared memory.

>  It seems register_ddr(addr, size) should be used to generate phys_ddr_overall to tell opteeos the range of the dynamic shared memory. 

If I remember right, `phys_ddr_overall` defines whole DDR ranges, how DRAM controller see them, i.e. both secure and non-secure. `phys_nsec_ddr` defines only non-secure DDR range. This is where dynamic  shared buffer can be found.

**Comment by tiger20081015** [comment]
hi, @lorc 
I still have some questions with your answers:
1. "With the latest patches to linux kernel driver...", can you point the patch name? We now use kernel 4.19 and want to check if it supports the feature. 
2. as you mentioned, if phys_ddr_overall defines whole DDR ranges, then what's the purpose of the below code in function core_mmu_set_discovered_nsec_ddr? In my understanding, with the execution of below code, only the static shared memory area(NSEC_SHM) will be removed, and discovered_nsec_ddr_start may even points to the secure ddr area? It's quite confusing since from the name, "discovered_nsec_ddr_start" seems should only point to the non secure ddr range. 

```
 379 >-------for (map = static_memory_map; core_mmap_is_end_of_table(map); map++) {
 380 >------->-------if (map->type == MEM_AREA_NSEC_SHM)
 381 >------->------->-------carve_out_phys_mem(&m, &num_elems, map->pa, map->size);
 382 >------->-------else
 383 >------->------->-------check_phys_mem_is_outside(m, num_elems, map);
 384 >-------}
 385 
 386 >-------discovered_nsec_ddr_start = m;
 387 >-------discovered_nsec_ddr_nelems = num_elems;
```
