### ISSUE TITLE
load_no_speculate_fail() usage

### ISSUE THREAD

**Issue by jenswi-linaro** [OP-TEE/optee_os#3490]
I'd like to explore what's possible to do with  load_no_speculate_fail(). Below we're loading an element element from an array of structs. An advantage of this compared to https://github.com/OP-TEE/optee_os/pull/3484 is that it uses a cheaper barrier `csdb` if it's implemented.

Comments?

``` diff
--- a/core/arch/arm/tee/arch_svc.c
+++ b/core/arch/arm/tee/arch_svc.c
@@ -14,6 +14,7 @@
 #include <kernel/user_ta.h>
 #include <mm/tee_mmu.h>
 #include <string.h>
+#include <speculation_barrier.h>
 #include <tee/tee_svc.h>
 #include <tee/arch_svc.h>
 #include <tee/tee_svc_cryp.h>
@@ -218,6 +219,7 @@ bool user_ta_handle_svc(struct thread_svc_regs *regs)
 	size_t scn;
 	size_t max_args;
 	syscall_t scf;
+	struct syscall_entry *sc_table = (void *)tee_svc_syscall_table;
 
 	COMPILE_TIME_ASSERT(ARRAY_SIZE(tee_svc_syscall_table) ==
 				(TEE_SCN_MAX + 1));
@@ -232,10 +234,9 @@ bool user_ta_handle_svc(struct thread_svc_regs *regs)
 		return true; /* return to user mode */
 	}
 
-	if (scn > TEE_SCN_MAX)
-		scf = (syscall_t)syscall_not_supported;
-	else
-		scf = tee_svc_syscall_table[scn].fn;
+	scf = *load_no_speculate_fail(&sc_table[scn].fn, &sc_table[0].fn,
+				      &sc_table[TEE_SCN_MAX].fn,
+				      &syscall_not_supported);
 
 	ftrace_syscall_enter(scn);

```

**Comment by jforissier** [comment]
An obvious downside is that it's a bit harder to read than `SPECULATION_SAFE_VALUE()`, but not that much actually.
What's the performance difference? I'd be curious to see the numbers reported by ftrace. Maybe the impact varies depending on the CPU. WIth Hikey960 we have two kinds of Cortex cores (A-53 and A-73), so it would be interesting to run a test on both.

**Comment by jenswi-linaro** [comment]
> An obvious downside is that it's a bit harder to read than SPECULATION_SAFE_VALUE(), but not that much actually.

Yes, once you've seen it used a couple of times it's a lot easier read. The macros themselves would benefit quite a lot from a few examples because they aren't very readable.

> What's the performance difference?

I'm not sure if it's measurable with ftrace directly. We could construct a special case where a few thousand dummy syscalls are done with interrupts masked.

**Comment by jforissier** [comment]
> I'm not sure if it's measurable with ftrace directly. We could construct a special case where a few thousand dummy syscalls are done with interrupts masked.

One syscall should be enough, since ftrace records timestamps for each function. But you're probably right about interrupts, either mask them or run the same test a few times to get consistent results.

**Comment by jenswi-linaro** [comment]
Ftrace is bound to affect speculation so I don't think we'll get a good measurement.

**Comment by jforissier** [comment]
> Ftrace is bound to affect speculation so I don't think we'll get a good measurement.

Maybe. Another option would be to read the CNTPCT directly in the `user_ta_handle_svc()` function around the things we want to compare. Perhaps using assembly even.
