### ISSUE TITLE
recipe for target 'optee-os-common' failed

### ISSUE THREAD

**Issue by aliongit** [OP-TEE/optee_os#3493]
Hi, I am trying to emulate optee on qemu, _After installation of QEMU and OP-TEE_, when I try to run I get the below error, and have tried the command expressed in issue #2941 & issue #672 but the error is remaining, I'm using 64bit ubuntu :
**~/optee/bin/build$ make all run**
`make -C /home/aliongit/optee/bin/build/../optee_os O=out/arm CROSS_COMPILE="/usr/bin/ccache /home/aliongit/optee/bin/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CROSS_COMPILE_core="/usr/bin/ccache /home/aliongit/optee/bin/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CROSS_COMPILE_ta_arm64="/usr/bin/ccache /home/aliongit/optee/bin/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm32="/usr/bin/ccache /home/aliongit/optee/bin/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" `**CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=1 CFG_TEE_BENCHMARK=n PLATFORM=vexpress-qemu_virt**
**make[1]:** `Entering directory '/home/aliongit/optee/bin/optee_os'`
`CHK out/arm/conf.mk`
`CHK out/arm/include/generated/conf.h`
**make[1]:**` *** No rule to make target '/home/aliongit/optee/bin/toolchains/aarch32/lib/gcc/arm-linux-gnueabihf/8.3.0/include/stdbool.h',` `needed by 'out/arm/core/include/generated/.asm-defines.s'. Stop.` **make[1]:** `Leaving directory '/home/aliongit/optee/bin/optee_os'`
**common.mk:380:** recipe for target **'optee-os-common'** failed
**make:** *** `[optee-os-common] Error 2`, I've Updated my toolchains.mk file and redownload the toolchains multiple times, _but the error is still remaining!_

**Comment by jforissier** [comment]
Hi,

Does the file `/home/aliongit/optee/bin/toolchains/aarch32/lib/gcc/arm-linux-gnueabihf/8.3.0/include/stdbool.h` exist? Have you tried clearing the compiler cache (`ccache -C`)?

**Comment by aliongit** [comment]
> Hi,
> 
> Does the file `/home/aliongit/optee/bin/toolchains/aarch32/lib/gcc/arm-linux-gnueabihf/8.3.0/include/stdbool.h` exist? Have you tried clearing the compiler cache (`ccache -C`)?

Thanks for reply, 
The only folder existing in dir `/home/aliongit/optee/bin/toolchains/aarch32/lib/gcc/arm-linux-gnueabihf/` is `6.2.1` and `/include/stdbool.h` exists in it. should I download package `8.3.0` instead?

**Comment by jforissier** [comment]
`make toolchains` should have downloaded the proper files. I tried yesterday and it worked...

**Comment by aliongit** [comment]
Thanks a lot for the help provided, my build of optee has occured another error and i prefer to ask it in another issue.

**Comment by ademyankov** [comment]
I got the same issue on a pristinely clean ubuntu system (18.04.4), newly checked out repo: qemu_v8.xml

**make toolchains** - does not pull anything into aarch32; it creates the folder but it's empty.

```
toolchains$ ld
total 267084
drwxrwxr-x 2      4096 Feb  4 14:39 aarch32
drwxrwxr-x 9      4096 Feb  4 14:40 aarch64
-rw-rw-r-- 1 272029648 Feb  4 14:40 gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz
-rw-rw-r-- 1   1454080 Feb  4 14:39 gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz
```

**make run**

```
build$ make run
make -C /home/ad/projects/optee/build/../optee_os O=out/arm CFG_ARM64_core=y CROSS_COMPILE="/usr/bin/ccache /home/ad/projects/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_core="/usr/bin/ccache /home/ad/projects/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm64="/usr/bin/ccache /home/ad/projects/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm32="/usr/bin/ccache /home/ad/projects/optee/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=0 CFG_TEE_BENCHMARK=n PLATFORM=vexpress-qemu_armv8a CFG_ARM64_core=y DEBUG=0
make[1]: Entering directory '/home/ad/projects/optee-3.8.0/optee_os'
  CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
  CHK     out/arm/core/include/generated/asm-defines.h
  CC      out/arm/ta_arm32-lib/libdl/dlfcn.o
ccache: error: execv of /home/ad/projects/optee/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-gcc failed: No such file or directory
mk/compile.mk:157: recipe for target 'out/arm/ta_arm32-lib/libdl/dlfcn.o' failed
make[1]: *** [out/arm/ta_arm32-lib/libdl/dlfcn.o] Error 1
make[1]: Leaving directory '/home/ad/projects/optee-3.8.0/optee_os'
common.mk:396: recipe for target 'optee-os-common' failed
make: *** [optee-os-common] Error 2
```

**Comment by ademyankov** [comment]
Ok, I fixed the issue on my side. For some reason the **sha1** for gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz was invalid. After deleting the folder and re-doing **make toolchains** it works.

I still cannot build it :) some issue with **Cryptodome** module :) but I guess it's a different story... have to dig it more...

```
make[1]: Entering directory '/home/ad/projects/optee-3.8.0/optee_os'
  CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
  CHK     out/arm/core/include/generated/asm-defines.h
  CHK     out/arm/conf.cmake
  CHK     out/arm/export-ta_arm32/mk/conf.mk
  CHK     out/arm/export-ta_arm64/mk/conf.mk
  SIGN    out/arm/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta
Traceback (most recent call last):
  File "out/arm/export-ta_arm32/scripts/sign_encrypt.py", line 258, in <module>
    main()
  File "out/arm/export-ta_arm32/scripts/sign_encrypt.py", line 131, in main
    from Cryptodome.Signature import pss
ModuleNotFoundError: No module named 'Cryptodome'
ta/arch/arm/link.mk:100: recipe for target 'out/arm/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta' failed
make[1]: *** [out/arm/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta] Error 1
make[1]: Leaving directory '/home/ad/projects/optee-3.8.0/optee_os'
common.mk:396: recipe for target 'optee-os-common' failed
make: *** [optee-os-common] Error 2
```

**Comment by ademyankov** [comment]
Yeap. Found it. https://github.com/OP-TEE/build/issues/401

**Comment by Sayli2107** [comment]
> Hi,
> 
> Does the file `/home/aliongit/optee/bin/toolchains/aarch32/lib/gcc/arm-linux-gnueabihf/8.3.0/include/stdbool.h` exist? Have you tried clearing the compiler cache (`ccache -C`)?

hi @jforissier ,
I need help regarding this case.

I am also getting same error:

make -C /home/pi/shadow-box/build/../optee_os O=out/arm CFG_ARM64_core=y CROSS_COMPILE="/usr/bin/ccache /home/pi/shadow-box/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_core="/usr/bin/ccache /home/pi/shadow-box/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm64=/home/pi/shadow-box/build/../toolchains/aarch64/bin/aarch64-linux-gnu- CROSS_COMPILE_ta_arm32=/home/pi/shadow-box/build/../toolchains/aarch32/bin/arm-linux-gnueabihf- CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=0 CFG_TEE_BENCHMARK=n PLATFORM=rpi3
make[1]: Entering directory '/home/pi/shadow-box/optee_os'
  CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
ccache: error: execv of /home/pi/shadow-box/build/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc failed: Exec format error
mk/compile.mk:228: recipe for target 'out/arm/core/include/generated/.asm-defines.s' failed
make[1]: *** [out/arm/core/include/generated/.asm-defines.s] Error 1
make[1]: Leaving directory '/home/pi/shadow-box/optee_os'
common.mk:301: recipe for target 'optee-os-common' failed
make: *** [optee-os-common] Error 2


I run ccache -c ; but path you mentioned doesn't exit : /home/aliongit/optee/bin/toolchains/aarch32/lib/gcc/arm-linux-gnueabihf/8.3.0/include/stdbool.h 

will you please put your words regarding this? It will be great help.
