### ISSUE TITLE
use of large memory crash on RPI 3

### ISSUE THREAD

**Issue by ncugit-sec** [OP-TEE/optee_os#3495]
I'm using Raspberry Pi 3 Model B and follow the instructions to build
the only thing I add is some buildroot packages

the problem came when I allocated a large block of memory in normal world and tried to invoke command or open session or whatever related to secure world caused the system to crash
p.s. it still left 100+MB after allocation
even if i freed the memory before invoking secure world still cause the problem
I also tested it on QEMU but it didn't cause this problem

Any idea what cause this to happen and how to solve it, thanks!

p.s. my code is modified from hello_world example
here is some related code
```
memset(&op, 0, sizeof(op));
op.paramTypes = TEEC_PARAM_TYPES(TEEC_VALUE_INOUT, TEEC_NONE,
					 TEEC_NONE, TEEC_NONE);
op.params[0].value.a = 42;
// added code
int *data = malloc(sizeof(int) * 1024*1024 * 180);
for(int x = 0; x < 1024*1024*n; x++)
	data[x] = 1;
printf("allocated\n");
scanf("%d", &n);
if(n)
	free(data);
printf("freed\n");
printf("Invoking TA to increment %d\n", op.params[0].value.a);
res = TEEC_InvokeCommand(&sess, TA_HELLO_WORLD_CMD_INC_VALUE, &op,
				 &err_origin);
// crashed here
```
error msg
```
[   40.930194] smsc95xx 1-1.1:1.0 eth0: Failed to read reg index 0x00000114: -110
[   40.943321] smsc95xx 1-1.1:1.0 eth0: Error reading MII_ACCESS
[   40.954913] smsc95xx 1-1.1:1.0 eth0: MII is busy in smsc95xx_mdio_read
[   40.967231] smsc95xx 1-1.1:1.0 eth0: Failed to read MII_BMSR
[   49.122123] mmc0: timeout waiting for hardware interrupt.
```

memory usage
```
             total       used       free     shared    buffers     cached
Mem:        906716     760684     146032         44        428       3008
-/+ buffers/cache:     757248     149468
Swap:            0          0          0

```

**Comment by jenswi-linaro** [comment]
There seems to be a conflict in the usage of some physical memory. Perhaps the kernel uses some physical memory which OP-TEE in secure world was supposed to have exclusive access to.

I'd recommend checking the memory description in DTB against what OP-TEE is using.

**Comment by ncugit-sec** [comment]
So currently there is no 
any mechanism to prevent this from happening?
It seems to be a serious problem if we can't make good use of all of memory.
I'm not familiar with the kernel, so maybe I'll do more research if necessary in the future.

**Comment by jenswi-linaro** [comment]
Your system is misconfigured, likely in the DTB.

**Comment by ncugit-sec** [comment]
But I build the system followed the instructions from 
https://optee.readthedocs.io/en/latest/building/gits/build.html#build
step by step and didn't configure anything else
Is it correct that we need to configure anything additionally before building from the git?

**Comment by jbech-linaro** [comment]
FYI, I've started doing the regression testing on RPI3b for the upcoming 3.8.0 release. I'll let you know if I face the same issues as you're facing.

**Comment by jbech-linaro** [comment]
No build regression and no test regressions found on RPi3 using what is the latest versions on master branches as of today.
```bash
NOTICE:  BL1: v2.0(debug):v2.0-580-g023bc019e
NOTICE:  BL1: Built : 12:20:47, Jan  7 2020
...
NOTICE:  BL2: v2.0(debug):v2.0-580-g023bc019e
NOTICE:  BL2: Built : 12:20:47, Jan  7 2020
...
NOTICE:  BL31: v2.0(debug):v2.0-580-g023bc019e
NOTICE:  BL31: Built : 12:20:47, Jan  7 2020
...
I/TC: OP-TEE version: 3.7.0-135-gabfd092a (gcc version 8.3.0 (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36))) #1 Tue Jan  7 11:20:31 UTC 2020 aarch64
...
[    0.000000] Linux version 4.14.56-v8 (jbech@debby) (gcc version 8.3.0 (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36))) #1 SMP PREEMPT Tue Jan 7 12:22:14 CET 2020
...
# xtest
...
24352 subtests of which 0 failed
96 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
