### ISSUE TITLE
scripts/kconfig/merge_config.sh: No such file or directory

### ISSUE THREAD

**Issue by aliongit** [OP-TEE/optee_os#3501]
Hi, I'm trying to build optee, but this error occures in _**common.mk**_ file:
```
bash: line 1: scripts/kconfig/merge_config.sh: No such file or directory
common.mk:268: recipe for target '/home/aliongit/optee/bin/build/../linux/.config' failed
make: *** [/home/aliongit/optee/bin/build/../linux/.config] Error 127
```

saying no such file exitsts in `scripts/kconfig/merg_config.sh`.
I located the file and it is available in dir: `/home/aliongit/optee/bin/u-boot/scripts/kconfig/merge_config.sh`
but the file **common.mk** addresses defected!

**Comment by jbech-linaro** [comment]
What setup are you trying to build? Would you mind paste the entire clone **and** build log at some [paste service](https://www.google.com/search?q=+paste+service)?

**Comment by aliongit** [comment]
> What setup are you trying to build? Would you mind paste the entire clone **and** build log at some [paste service](https://www.google.com/search?q=+paste+service)?

I am trying optee-qemu build on ubuntu 18.04 Here you are, the [build log](https://psty.io/p?q=d7b0a)

**Comment by jbech-linaro** [comment]
Do you have a linux folder? And btw, you shouldn't run this with sudo. Try to clean it all and rebuild without sudo. Pay attention to that you'll now have build artifacts that are owned by root, so you'll have to clean using root also (or `chown` all files to your username).

**Comment by aliongit** [comment]
> Do you have a linux folder? And btw, you shouldn't run this with sudo. Try to clean it all and rebuild ...

Oh, yes. I've tried the commands with `sudo` and now I tried `sudo chown -R aliongit optee` to return the ownership of folder optee to my id `aliongit`. but the error is still remaining : 
```
aliongit@ubuntu:~/optee/bin/build$ make all run
```
```
bash: line 1: scripts/kconfig/merge_config.sh: No such file or directory
common.mk:268: recipe for target '/home/aliongit/optee/bin/build/../linux/.config' failed
make: *** [/home/aliongit/optee/bin/build/../linux/.config] Error 127
```
I have a linux folder in `optee/bin/linux `but it is empty!

**Comment by jbech-linaro** [comment]
> I have a linux folder in `optee/bin/linux `but it is empty!

Ok, then your clone step (repo sync) probably have failed for some reason. Try `repo sync -d` and verify that the linux git also will be cloned.

**Comment by aliongit** [comment]
Thanks so much. It solved the issue above, but another error occurs in `repo sync -d` that `build` repo fails to sync and it would be better to ask the question in a new issue.
regards!

**Comment by jbech-linaro** [comment]
Sure, feel free to close this one and then take the sync issues in another thread. But if you play around with syncing please save the log file also so we have something to look at.
