### ISSUE TITLE
error: Cannot checkout OP-TEE/build.git

### ISSUE THREAD

**Issue by aliongit** [OP-TEE/optee_os#3502]
Hi,
I've an issue syncing the repository with `repo sync -d` and I get the following error:
```
Aborting
error: build/: OP-TEE/build.git checkout 1e8d0b5a2b383834d09e3dfc5a9216fcef557a24 
error: Cannot checkout OP-TEE/build.git

error: Exited sync due to checkout errors
Failing repos:
build
```
and my [sync log is HERE!](https://pastr.io/view/twHw8mCBHaF)

**Comment by jbech-linaro** [comment]
It seems like you have local changes to the hikey960.mk file and those are not committed and therefore the sync fails.

**Comment by aliongit** [comment]
> It seems like you have local changes to the hikey960.mk file and those are not committed and therefore the sync fails.

Maybe I changed the file, so i deleted it and resynchronized and it worked, thanks!
