### ISSUE TITLE
suggest add crc for rpmb secure store

### ISSUE THREAD

**Issue by hisping** [OP-TEE/optee_os#3506]
read data success but decrypted data is incorrect if we replace emmc or cpu, i think rpmb fs need add crc to check data.

**Comment by Emantor** [comment]
How does a crc help in this case? If the shared key between eMMC and CPU becomes mismatched, there is no recovery path and the decrypted data error indicates the same error as a crc checksum failure.

**Comment by hisping** [comment]
we do not need recovery , just check data and return error code ,  do not return success when read data.

**Comment by Emantor** [comment]
Looking into the source code, unless `CFG_RPMB_FS_NO_MAC` is set, OP-TEE will return `TEE_ERROR_SECURITY` instead of `TEE_SUCCESS` while verifying the eMMCs response. https://github.com/OP-TEE/optee_os/blob/ce50e716c5895e01795691d5c10c3ac736456d30/core/tee/tee_rpmb_fs.c#L826-L840
