### ISSUE TITLE
warning syscall rseq not implemented

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3507]
Does this warning have any influence on the normal operation of the system?

`<stdin>:1335:2: warning: #warning syscall rseq not implemented [-Wcpp]`

**Comment by jforissier** [comment]
1. Posting screen captures instead of copying and pasting the text is annoying
2. It is a Linux build warning and I have no idea what it means, have you tried to Google it? Or looked at the script that generates it?
