### ISSUE TITLE
Changing normal world kernel

### ISSUE THREAD

**Issue by lmarti95** [OP-TEE/optee_os#3508]
Hello,
My question is that can normal world kernel be changed or is it specific to OP-TEE? And if yes, what interfaces does it need to provide?
Thank you,
Márton

**Comment by jforissier** [comment]
Hello Márton,

You can use any kernel, provided that it has the OP-TEE driver of course (`drivers/tee/*`). The driver code is essentially all upstream, in the standard Linux kernel. You can check the history of OP-TEE code in the kernel here: https://github.com/linaro-swg/linux/blob/optee/upstream-tee-subsys-patches.txt

If you want to use an older kernel with a recent OP-TEE you might need to backport a few patches though.
