### ISSUE TITLE
Can ldelf dynamically be disabled?

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#3511]
Hi, currently we're upgrading opteeos to 3.7, and we found the ro data is bigger than that in 3.5 version for 48K due to ldelf_data. I read the patch commit message and it seems that ldelf is used for TA to dynamically load libraries. Can this feature be disabled dynamically since our platform is sensitive to memory usage?

**Comment by jforissier** [comment]
Hi @tiger20081015 ,

> [...] it seems that ldelf is used for TA to dynamically load libraries. 

Not only libraries. ldelf is used to load the main executable, too.

> Can this feature be disabled dynamically [...]?

No, it cannot. We didn't see a need for that, and it would have been hard to maintain two similar (but different) pieces of code that does the same thing (the kernel space and user space ELF loaders).

Do you have more details on why RO data are bigger by 48K? This seems quite large to me for just ldelf data.

**Comment by tiger20081015** [comment]
Hi, @jforissier 

> Hi @tiger20081015 ,
> 
> > [...] it seems that ldelf is used for TA to dynamically load libraries.
> 
> Not only libraries. ldelf is used to load the main executable, too.

Do you mean now the TA itself is also loaded by ldelf?

> > Can this feature be disabled dynamically [...]?
> 
> No, it cannot. We didn't see a need for that, and it would have been hard to maintain two similar (but different) pieces of code that does the same thing (the kernel space and user space ELF loaders).
> 
> Do you have more details on why RO data are bigger by 48K? This seems quite large to me for just ldelf data.

Yes, from the tee.map file, I found the extra 48K comes from out/arm-plat-finch/core/ldelf_hex.c， in which defines an array ldelf_data with 48K size.
```
 26875  .rodata.ldelf_data
 26876                 0x81070000     0xc000 out/arm-plat-finch/core/ldelf_hex.o 48K
 26877                 0x81070000                ldelf_data
```

```
   4 const uint8_t ldelf_data[49152] __aligned(4096) = {
   5 >-------0x54, 0x40, 0x8f, 0xe2, 0x50, 0x50, 0x9f, 0xe5,
   6 >-------0x50, 0x60, 0x9f, 0xe5, 0x04, 0x50, 0x85, 0xe0,
   ...
```
the ldelf_hex.c is generated by below command in core/sub.mk:
```
 19 recipe-ldelf = scripts/gen_ldelf_hex.py --input $(out-dir)/ldelf/ldelf.elf \                                                                                                                            
 20 >------->------->---------output $(sub-dir-out)/ldelf_hex.c
```
What's the purpose of this ldelf_data? Used to parse loaded programs?

**Comment by jforissier** [comment]
> Hi, @jforissier
> 
> > Hi @tiger20081015 ,
> > > [...] it seems that ldelf is used for TA to dynamically load libraries.
> > 
> > 
> > Not only libraries. ldelf is used to load the main executable, too.
> 
> Do you mean now the TA itself is also loaded by ldelf?

Yes.

> 
> > > Can this feature be disabled dynamically [...]?
> > 
> > 
> > No, it cannot. We didn't see a need for that, and it would have been hard to maintain two similar (but different) pieces of code that does the same thing (the kernel space and user space ELF loaders).
> > Do you have more details on why RO data are bigger by 48K? This seems quite large to me for just ldelf data.
> 
> Yes, from the tee.map file, I found the extra 48K comes from out/arm-plat-finch/core/ldelf_hex.c， in which defines an array ldelf_data with 48K size.

Ah, yes, it is in fact the whole ldelf executable code + data, which is embedded in the TEE core.

> What's the purpose of this ldelf_data? Used to parse loaded programs?

Exactly. Prior to the introduction of ldelf, the TAs were parsed by kernel code. Now it's done in user space instead.

**Comment by tiger20081015** [comment]
@jforissier , 
thanks for your prompt answers! No more questions.
