### ISSUE TITLE
Does ARM TrsutZone provide the necessary security mechanisms to OP-TEE?

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3516]
Does ARM TrsutZone provide the necessary security mechanisms to OP-TEE as a BL1 in a secure ROM? Does the arm provide a HUK or is a TPM needed? If the TPM is changed to another, is the boot performed or blocked?
How does OP-TEE verify that it is safe?

**Comment by Emantor** [comment]
No, ARM TrustZone does only specify the secure mode, HUK and possibly RAM protection are per SoC implementations done by the vendors. RPI for example does not have the necessary hardware to protect secure data in RAM.
TPM is a higher level concept, OP-TEE does not implement drivers for TPMs (yet?).
To really secure the secure data stored on your platform you'll also need to use the verified boot method of your chosen SoC vendor. I'll be giving a talk on this at FOSDEM in early February, [talk](https://fosdem.org/2020/schedule/event/optee/).

**Comment by 21212124** [comment]
So you can't use a rpi with trustzone as secure storage? Can't use a TPM as a secure ROM as the trusted root of a TF-A?

And from what I understand, using a TPM with OP-TEE is useless, right?

Thanks @Emantor

**Comment by Emantor** [comment]
> So you can't use a rpi with trustzone as secure storage? 

One can use TrustZone with the RPI, however all memory allocated to OP-TEE will be readable by Linux.

> Can't use a TPM as a secure ROM as the trusted root of a TF-A?

I don't really get what you are trying to say here. one could use a TPM to authenticate OP-TEE, however this would need to be done by an already authenticated bootloader which in turn requires support from the boot ROM.

> And from what I understand, using a TPM with OP-TEE is useless, right?

Not necessarily useless, it depends on your use case. If you can come up with a use case where using a TPM with OP-TEE mitigates an attack scenario, it is fine to use a TPM.

**Comment by 21212124** [comment]
>I don't really get what you are trying to say here. one could use a TPM to authenticate OP-TEE, however this would need to be done by an already authenticated bootloader which in turn requires support from the boot ROM.

What I'm trying to say is that if I want a secure boot, I need a trust root. If Raspberry Pi cannot provide that trusted root, can I use a TPM?


Thanks for your answers @Emantor

**Comment by jbech-linaro** [comment]
> What I'm trying to say is that if I want a secure boot, I need a trust root. If Raspberry Pi cannot provide that trusted root, can I use a TPM?

Yes an external TPM can always be used. Just enable the driver(s) in Linux and use a TSS stack and you're good to go. You can run all sort of scenarios, TPM only, TruztZone only, mix them both, run a firmware TPM in the TrustZone etc. It all depends on what your use cases are and what your hardware is capable of. Raspberry Pi devices should be seen as development devices used to do just that, i.e., development. They aren't and cannot be configured in a secure manner by general audience. I imagine that Broadcom engineers can do a bit more, but not the general audience.

**Comment by 21212124** [comment]
Can I ask you two questions @jbech-linaro

1.- If OP-TEE needs TrustZone to work, what security mechanisms does TrustZone provide OP-TEE with respect to secure boot, secure storage and TA? Or does it only provide hardware isolation? For example, does OP-TEE use cryptography from TrustZone?

2.- Do you know any platform where you can use OP-TEE on Linux and that has TrustZone or that complies with a PSA certificate?

**Comment by jbech-linaro** [comment]
> 1.- If OP-TEE needs TrustZone to work, what security mechanisms does TrustZone provide OP-TEE with respect to secure boot, secure storage and TA? Or does it only provide hardware isolation? For example, does OP-TEE use cryptography from TrustZone?

TrustZone is a technology, OP-TEE is a Trusted Execution Environment that make use of TrustZone and at the same time makes TrustZone usable. I.e., there is relation in both directions. So I think your question is invalid. Without a TEE ... TrustZone isn't very much. TrustZone itself doens't have secure store, doesn't have crypto etc. TrustZone gives the chip the ability to switch modes to run in a secure and in a non-secure mode. TrustZone also is bus aware, i.e., you can do secure transactions to peripheral, memory areas etc. But the actual software features that people normally relate to, those are coming from the TEE itself.

> 2.- Do you know any platform where you can use OP-TEE on Linux and that has TrustZone

Yes, these: https://optee.readthedocs.io/en/latest/general/platforms.html

> or that complies with a PSA certificate?

No, I'm unware of any PSA ready platforms. Not sure if Arm have a list of that publicly somewhere.

**Comment by wamserma** [comment]
> Not sure if Arm have a list of that publicly somewhere.

Here: https://www.psacertified.org/certified-products/
