### ISSUE TITLE
xtest 6016 hangs (HiKey, pager)

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3518]
Reproducing IBART failure observed [here](https://optee.mooo.com:5000/logs/OP-TEE/optee_test/384/358500523/e495908f7b8304413b154560e7271fb3bc949ea8#end-01-hikey6220-test).

- Source code:
  - optee_os master @ commit c0c57c8fa583 ("symbolize.py: fix stack dump of TEE core with pager") plus the following patch (adds stack dumps)
  ```diff
  diff --git a/core/arch/arm/kernel/unwind_arm64.c b/core/arch/arm/kernel/unwind_arm64.c
  index 5b775021..898a5cca 100644
  --- a/core/arch/arm/kernel/unwind_arm64.c
  +++ b/core/arch/arm/kernel/unwind_arm64.c
  @@ -31,6 +31,7 @@
   
   #include <arm.h>
   #include <kernel/linker.h>
  +#include <kernel/spinlock.h>
   #include <kernel/tee_misc.h>
   #include <kernel/tee_ta_manager.h>
   #include <kernel/thread.h>
  @@ -120,17 +121,22 @@ void print_stack_arm64(int level, struct unwind_state_arm64 *state,
   	} while (unwind_stack_arm64(state, stack, stack_size));
   }
   
  +static unsigned int stack_dump_lock = SPINLOCK_UNLOCK;
  +
   void print_kernel_stack(int level)
   {
   	struct unwind_state_arm64 state;
   	uaddr_t stack = thread_stack_start();
   	size_t stack_size = thread_stack_size();
  +	uint32_t old_itr_status;
   
   	memset(&state, 0, sizeof(state));
   	state.pc = read_pc();
   	state.fp = read_fp();
   
  +	old_itr_status = cpu_spin_lock_xsave(&stack_dump_lock);
   	print_stack_arm64(level, &state, stack, stack_size);
  +	cpu_spin_unlock_xrestore(&stack_dump_lock, old_itr_status);
   }
   
   #endif
  diff --git a/core/arch/arm/kernel/wait_queue.c b/core/arch/arm/kernel/wait_queue.c
  index c9b1b060..2d7ef901 100644
  --- a/core/arch/arm/kernel/wait_queue.c
  +++ b/core/arch/arm/kernel/wait_queue.c
  @@ -39,6 +39,7 @@ void __weak __wq_rpc(uint32_t func, int id, const void *sync_obj 
  __maybe_unused,
 
 	struct thread_param params = THREAD_PARAM_VALUE(IN, func, id, 0);
   
  +	DPRINT_STACK();
   	ret = thread_rpc_cmd(OPTEE_RPC_CMD_WAIT_QUEUE, 1, &params);
   	if (ret != TEE_SUCCESS)
   		DMSG("%s thread %u ret 0x%x", cmd_str, id, ret);
    ```
  - optee_test from https://github.com/OP-TEE/optee_test/pull/384 ("regression 4006: add test cases for SM2 PKE", needed so that `xtest 4006 has the SM2 tests)
- Build command:
  ```
  $ make -j10 CFG_RPMB_WRITE_KEY=y CFG_RPMB_FS=y CFG_WITH_PAGER=y CFG_TEE_CORE_LOG_LEVEL=3 CFG_LOCKDEP=y
  ```
- Test commands `xtest 4006; xtest 6016`
- Full "symbolized" log [here](https://pastebin.com/k87mTxGc).

It looks like threads 0, 1, and 3 are blocked on the FS lock by thread 2 which also owns the FS lock and is waiting for something to happen in `get_pool()` in `core/lib/libutils/ext/mempool.c`.

Any idea how to fix this? could the FS lock be released prior to calling `get_pool()` maybe?

**Comment by jenswi-linaro** [comment]
> Any idea how to fix this? could the FS lock be released prior to calling get_pool() maybe?

I think it's the other way around, the FS lock must not be acquired while owning the mempool. The mempool is used for some small temporary memory in REE FS. Normally `ree_fs_mutex` is acquired first and then from time to time is the mempool used. However, mempool is also used when doing certain bignum operations. The mempool is reference counted with matching `mempool_alloc()` and `mempool_free()`. The first `mempool_alloc()` of a thread acquired exclusive access to the mempool for that thread and the last `mempool_free()` releases the mempool for some other thread to use it.

This allocation scheme was introduced with 0e3f6d6bb28b ("core: REE FS: temporary block allocation").

I'd prefer if we could find out who's owning the mempool while acquiring `ree_fs_mutex` as reverting the patch above introduces other problems.

**Comment by jforissier** [comment]
Thanks for reminding me how the mempool works :wink: now everything is clear: the SM2 code leaves bignums allocated and therefore the thread keeps ownership of the memory pool.
Fix in https://github.com/OP-TEE/optee_os/pull/3524.

**Comment by jenswi-linaro** [comment]
Good to hear, I was worried that we had a much more difficult problem.
