### ISSUE TITLE
Calling a Client Application through network?

### ISSUE THREAD

**Issue by MALATTAR** [OP-TEE/optee_os#352]
Hello,
I would like to perform the following architecture:
Applicaton <- network (using e.g., socket) -> CA (running on rich OS) <-> TA (running on Secure OS)
The goal is to make the functions of a TA available through a network for test purposese.

I am using opTEE over QEMU so my question is:
Is there a network support for the rich OS or not?

Regards,
MALATTAR

**Comment by jenswi-linaro** [comment]
Hi,

You mean if there's network support in QEMU? This depends on which options you give QEMU when starting. In our examples there's no network support enabled as far as I can tell.

Regards,
Jens

**Comment by MALATTAR** [comment]
Hi,
So, if I will understand you, the rich OS should have network support if the used QEMU (as an emulator) supports network?
In this case, I should search how to have network support on QEMU, right?

Regards,
MALATTAR

**Comment by jenswi-linaro** [comment]
Yes
