### ISSUE TITLE
Probably a bug in core_mmu_set_discovered_nsec_ddr

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#3521]
Hi, it seems there's a bug in core_mmu_set_discovered_nsec_ddr:
```c
 378 >-------for (map = static_memory_map; core_mmap_is_end_of_table(map); map++) {                                                                                                                        
 379 >------->-------if (map->type == MEM_AREA_NSEC_SHM)
 380 >------->------->-------carve_out_phys_mem(&m, &num_elems, map->pa, map->size); 
 381 >------->-------else
 382 >------->------->-------check_phys_mem_is_outside(m, num_elems, map);           
 383 >-------}
```
In line 378,  core_mmap_is_end_of_table(map) defines as below, which always returns false and the lines 379 to 382 can never be executed. 
```c
static inline bool core_mmap_is_end_of_table(const struct tee_mmap_region *mm)
{
	return mm->type == MEM_AREA_END;
}
```
I think the fix patch should be:

` for (map = static_memory_map; !core_mmap_is_end_of_table(map); map++) {`

Pls help to confirm my finding. Thanks!

**Comment by jenswi-linaro** [comment]
It looks like a bug.

**Comment by tiger20081015** [comment]
@jenswi-linaro ,
thanks, I submitted a pull request: #3526, please help review it. thanks.
