### ISSUE TITLE
TCR_EL1.IPS always 0 on master 

### ISSUE THREAD

**Issue by jenswi-linaro** [OP-TEE/optee_os#3529]
Since commit 520860f658be ("core: generic_entry: add enable_mmu()") `TCR_EL1.IPS` has always been initialized to `0` limiting the physical memory space to 32 bits. This is not enough on Juno, FVP and probably a few other platforms.

Prior to 520860f658be ("core: generic_entry: add enable_mmu()") `TCR_EL1.IPS` was calculated and even updated later in the boot flow to automatically cover the needed physical address space. But now it's calculated before MMU is enabled and once MMU it's kept in read only memory.

Updating `TCR_EL1.IPS` when needed isn't trivial as it may need to be synced to multiple CPUs so it's preferable to assign it once early and then keep it unchanged. A problem with this is that in that past we discovered the value based on applied mappings, but now we need some other mechanism.

It's not unreasonable to assume that each platform knows roughly the largest physical address that needs to be mapped, so we can hardcode a value at compile time. But the question is how to supply that value. We already have
```
# Enables support for larger physical addresses, that is, it will define
# paddr_t as a 64-bit type.
CFG_CORE_LARGE_PHYS_ADDR ?= n
```
Which is implicit in AArch64 (or even ignored). On the other hand, it's only in AArch64 that we need to initialize `TCR_EL1.IPS`. The following limits are interesting to identify with the current reference manual:
```
32 bits, 4GB.
36 bits, 64GB.
40 bits, 1TB.
42 bits, 4TB.
44 bits, 16TB.
48 bits, 256TB.
52 bits, 4PB.
```

We could add a `CFG_CORE_MAX_PHYS_ADDR_IN_GB` which defaults to `4`, but perhaps there's better way. @jforissier what do you think?

During runtime we'll need to check at appropriate places that physical addresses are within limits.

**Comment by jforissier** [comment]
A compile-time option seems reasonable to me. Linux uses names based on the bit size of the physical addresses, i.e.: `CONFIG_ARM64_PA_BITS`. Perhaps we should follow the same model?
```
# Physical address size
# 32 bits, 4GB.
# 36 bits, 64GB.
# (etc.)
CFG_CORE_ARM64_PA_BITS ?= 32
CFG_CORE_ARM64_PA_BITS_$(CFG_CORE_ARM64_PA_BITS) ?= y
```

**Comment by jenswi-linaro** [comment]
Yes, that's better. Although I think we can skip `CFG_CORE_ARM64_PA_BITS_$(CFG_CORE_ARM64_PA_BITS)`, there's no need to check the existence of a special value like that. I'll propose something based on this.

**Comment by jforissier** [comment]
> Although I think we can skip `CFG_CORE_ARM64_PA_BITS_$(CFG_CORE_ARM64_PA_BITS)`

I thought maybe it would be more convenient to test in the code, but maybe not actually ;-)

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/optee_os/pull/3531
