### ISSUE TITLE
Invokes bcm PTA within user TA

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/optee_os#3532]
Hello,

I have some questions about bcm PTA (pseudo TA) on raspberry pi 3 model B+.
In brief, I want to set the GPIO value from my user TA.
Some issues showed that the flow would be TA -->PTA --> BCM GPIO driver.

I found that there are some PTAs in `core/pta/bcm/` used to call the bcm drivers.
However, I didn't find the header file about these bcm PTAs in `lib/libutee/include/` directory.
There are only some header files about `core/pta` and `core/pta/tests`.

Here are my questions:
Should I need to write a header file like `lib/libutee/include/pta_socket.h`, and include it into my user TA?
Or I can directly copy the UUID of bcm PTAs into my user TA, and call `TEE_InvokeTACommand()`.

Please correct me if I am wrong, thank you.

**Comment by jforissier** [comment]
Hi @gagachang,

> However, I didn't find the header file about these bcm PTAs in `lib/libutee/include/` directory.

Not all PTAs have include files indeed. Perhaps we should fix that. Also, having the header files in `lib/libutee` is not very intuitive IMO.

> Or I can directly copy the UUID of bcm PTAs into my user TA, and call `TEE_InvokeTACommand()`.

Yes that will work of course.

**Comment by gagachang** [comment]
Hi @jforissier,

Thanks for your reply, it's really helpful!

Can I ask you more questions?
I traced the code about the socket PTA, and found that there is a `lib/libutee/tee_socket_pta.c` file.
The `tee_socket_pta.c` seems to be used to prepare the TEE parameters, and invoke the real socket PTA.

When the user TA invokes the bcm_gpio PTA, here are my questions:
Should I need to write a C file which works like `tee_socket_pta.c` and put it in `lib/libutee/` ?
Which means user TA can ignore the preparation of TEE parameters, and just invokes this C file.

Or the above step could be skipped,  we need to prepare the TEE parameters in user TA, and invoke `TEE_OpenTASession(...)`.
I wonder that if there is a standard about the flow of invoking the PTA from the user TA.

Thank you!

**Comment by jforissier** [comment]
Hi @gagachang,

> Should I need to write a C file which works like `tee_socket_pta.c` and put it in `lib/libutee/` ?

No. The socket use case is a bit special because it exposes its own interface in `libutee`.

> Or the above step should be skipped, we need to prepare the TEE parameters in user TA, and invoke `TEE_OpenTASession(...)`.

Yes. That's what I would do I think.

**Comment by gagachang** [comment]
Hi @jforissier ,

I am very thankful for your help.
I followed your suggestions and implemented my user TA successfully.

However, when I tried to build the optee_os, some compile errors happened.
When I traced the error, I discovered `core/arch/arm/plat-bcm` and `core/arch/arm/plat-rpi3` directories.
It seems that some identifiers used in `bcm_gpio.c` are only defined in `plat-bcm/platform_config.h`.
So the identifiers aren't defined with my rpi3 platform.

Are there any differences between the two platforms?
If they are compatible, what should I do to solve the problems.

Thank you!

**Comment by jforissier** [comment]
@gagachang ,

I don't know if the Raspberry Pi 3 is compatible with `bcm_gpio.c`. Maybe it is, in which case you just need to define the proper addresses in `core/arch/arm/plat-rpi3/platform_config.h.
If it is not compatible, then you can't use this GPIO driver and need to write a new one.
To answer these questions, you would need the technical reference manuals I suppose.

**Comment by gagachang** [comment]
Hi @jforissier ,

I wrote a new GPIO driver for Pi 3b+ and implemented some basic functions (set/get direction, value).
And I can set the value of a gpio pin from CA now, I'm truly grateful for your help!

Maybe I will create some PRs if I implement the rest functions (set/get interrupt).
Thanks for your help.
