### ISSUE TITLE
[RFC] Device Tree Fixups

### ISSUE THREAD

**Issue by Emantor** [OP-TEE/optee_os#3533]
Currently changes to the device tree from within OP-TEE work okay if OP-TEE ist started before the kernel is loaded. However if OP-TEE is to be started as early as possible in a pre-bootloader environment (U-Boot SPL, TF-A, barebox PBL, …), the device tree is either passed on in downstream environments or manual entries of the required nodes is necessary. This also limits the platform to load exactly one devicetree, which is passed through all layers until it is booted by the kernel. This is often not desirable, especially in environments where bootloader or pre-bootloader updates are not possible, but the kernel requires updates to the device tree.

To rectify this problem I propose the following solution:
1. Change all functions which change the device tree to register themselves with a fixup handler
2. Use this fixup handler to apply the required changes to the booted device tree
3. Add a new SMC handler which passes a device tree to OP-TEE and reapplies the fixups.

This way OP-TEE can apply the fixups to other device trees besides the initial one passed on start.

**Comment by jforissier** [comment]
Sounds reasonable.

> 3. Add a new SMC handler which passes a device tree to OP-TEE and reapplies the fixups.

Would the TA interface be too complex? If acceptable we could implement the service as a pseudo TA. This way there is no need to reserve any SMC.

**Comment by Emantor** [comment]
> Would the TA interface be too complex? If acceptable we could implement the service as a pseudo TA. This way there is no need to reserve any SMC.

No, I just forgot that this can also be implemented as a PTA.

**Comment by jenswi-linaro** [comment]
So neither having OP-TEE modifying a supplied DT or generating/updating a DT overlay can cover your use case? We need yet another way?

**Comment by Emantor** [comment]
The device tree overlays would fit, I'll investigate this and reopen here if it does not fit. Thanks!
