### ISSUE TITLE
Question: Secure storage in virtualized environment

### ISSUE THREAD

**Issue by mkieronski** [OP-TEE/optee_os#3536]
Hello,

We are currently implementing optee on virtualized environment. Now we struggle to decide how to organize secure storage, especially RPMB partition sharing between two guest os. I have question sregarding this topic from optee-os perspective.
1. Is is possible to share one RPMB partition between two guest os? I assume in this case some virtualized driver will be implemented to mediate device access.
2. Is it possible to run only one supplicant instance (for example in hypervisor host) which will serve requests from both vms?

**Comment by jbech-linaro** [comment]
@lorc , your insights are probably valuable here.

**Comment by jenswi-linaro** [comment]
See also this mail thread. https://lists.linaro.org/pipermail/tee-dev/2020-January/001413.html

**Comment by lorc** [comment]
Hello @mkieronski ,

Right now only simplest solution, which is REE FS is supported and no HW can be shared between OP-TEE instances. As @jenswi-linaro  and @jbech-linaro mentioned, I started the discussion in the tee-dev mailing list. There are some ideas, but that's all. If you wish to invest some efforts into this - that would be great.

> Is it possible to run only one supplicant instance (for example in hypervisor host) which will serve requests from both vms?

Well, this is not the case for Xen, but theoretically might work for KVM. Anyways, it is not supported right now. Also, I'm not aware of KVM-based mediator at all.,

**Comment by mkieronski** [comment]
Hi @lorc ,

Thanks for your answer.
We use QNX hypervisor, which is quite similar in concept to KVM.
If we decide to implement one supplicant running on hypervisor host, do you see any changes required in optee-os or guest kernel optee driver?

We have eMMC that supports only one RPMB partition.
In case of paravirtualized approach. How do you see idea of spliting one RPMB Partition into parts and giving exclusive access to guest domains?
