### ISSUE TITLE
Question: how to get peer information from session at TA side ?

### ISSUE THREAD

**Issue by vxfury** [OP-TEE/optee_os#3539]
I'd like to provide some command only for another TA, how to judge where the invoking come from , REE or TEE ?

**Comment by vxfury** [comment]
Found it. FYI:
``` C
TEE_PropSetHandle h = TEE_HANDLE_NULL;
TEE_Result res = TEE_AllocatePropertyEnumerator(&h);
TEE_StartPropertyEnumerator(h, TEE_PROPSET_CURRENT_CLIENT);
TEE_Identity v = {};
res = TEE_GetPropertyAsIdentity(h, NULL, &v);
if (res != TEE_SUCCESS || v.login != TEE_LOGIN_TRUSTED_APP) {
	DEBUG("TEE_GetPropertyAsIdentity returned 0x%x, Identity: 0x%X\n", res, v.login);
	TEE_FreePropertyEnumerator(h);
	return TEE_ERROR_ACCESS_DENIED;
}
TEE_FreePropertyEnumerator(h);
```

**Comment by jforissier** [comment]
Thanks for posting the solution :+1:

**Comment by bansalcheryl** [comment]
> ```c
> TEE_PropSetHandle h = TEE_HANDLE_NULL;
> TEE_Result res = TEE_AllocatePropertyEnumerator(&h);
> TEE_StartPropertyEnumerator(h, TEE_PROPSET_CURRENT_CLIENT);
> TEE_Identity v = {};
> res = TEE_GetPropertyAsIdentity(h, NULL, &v);
> if (res != TEE_SUCCESS || v.login != TEE_LOGIN_TRUSTED_APP) {
> 	DEBUG("TEE_GetPropertyAsIdentity returned 0x%x, Identity: 0x%X\n", res, v.login);
> 	TEE_FreePropertyEnumerator(h);
> 	return TEE_ERROR_ACCESS_DENIED;
> }
> TEE_FreePropertyEnumerator(h);
> ```

Can we use TEE_Identity to validate a TA in a PTA too? or this is available only at TA level?

**Comment by jforissier** [comment]
@bansalcheryl 

> Can we use TEE_Identity to validate a TA in a PTA too? or this is available only at TA level?

In a PTA it's different. You can find useful code in https://github.com/OP-TEE/optee_os/blob/3.16.0/core/pta/system.c#L313-L327 and https://github.com/OP-TEE/optee_os/blob/3.16.0/core/pta/scmi.c#L132-L143 for example. To summarize (untested but should be about right...):

```C
struct ts_session *s = ts_get_calling_session();
if (s) {
	/* Called from Secure World */
	if (is_user_ta_ctx(s->ctx)) {
		/* Caller is a user TA, otherwise it is a PTA */
	}
	/* UUID of caller is in s->ts_ctx.uuid */
} else {
	/* Called from Normal World */
	struct tee_ta_session *ta_s = to_ta_session(ts_get_current_session());
	/* Identity of caller (login, UUID) is in ta_s->clnt_id */
}
```
