### ISSUE TITLE
Arm emulator in Qemu

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3540]
Qemu is able to emulate TrustZone right? It can be debugged to see how it works, for example TrustZone Protection Controller (TZPC), TrustZone Address Space Controller (TZASC) or The TrustZone Memory Adapter (TZMA). How the NS bit changes, etc.

I mean, can you verify how the security mechanisms that TrustZone implements work and how it interacts with OP-TEE?

**Comment by jenswi-linaro** [comment]
I'm not sure about the TZPC, TZASC or TZMA. I think it's a static configuration. However, secure memory cannot be read or modified by normal world etc. I don't recall what happens if normal world tries to read secure memory, it could get only zeroes as result.
