### ISSUE TITLE
Possible a bug in core_mmu_set_max_pa?

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#3542]
Hi, I recently found a bug in our platform, the path is:

1.  In PTA,  we run core_mmu_add_mapping(MEM_AREA_IO_SEC, 0x100000000, 0x4) on CPU 0, which calls core_mmu_set_max_pa and updates the CPU 0's tcr_el1 IPS bits from 0x0 to 0x1 to support 64G physical memory;
2.  After step1, cpu0  switches to REE and when goes back to TEE, the cpu changes from cpu0 to cpu1. cpu1 then calls phys_to_virt(0x100000000, MEM_AREA_IO_SEC) and meets below panic because its tcr_el1 IPS is not updated as CPU0 does in step 1, so it still only supports 4G memory. 

_E/TC:00 Panic at core/arch/arm/mm/core_mmu.c:1748 <check_pa_matches_va>
ERROR:   [0x0] TC: Panic at core/arch/arm/mm/core_mmu.c:1748 <check_pa_matches_va>
E/TC:00 Call stack:
E/TC:00  0x0000000080029bf0_

To fix it I roughly think maybe we can raise SGI in core_mmu_set_max_pa to notify other online CPUs to update their IPS bits in tcr_el1. Do you think it's doable or have a better solution? Thanks.

**Comment by jenswi-linaro** [comment]
We've recently changed the way `TCR_EL1.IPS` is configured.

With 4518cdc1ff64 ("core: arm64: introduce CFG_CORE_ARM64_PA_BITS") `TCR_EL1.IPS` is now statically configured by the platform.

To fix your issue, configure `CFG_CORE_ARM64_PA_BITS` with a suitable value in the platform config.

**Comment by tiger20081015** [comment]
Thanks, the patch fixed my issue.
