### ISSUE TITLE
apply OPTEE to raspbian

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#3557]
I am trying to apply OPTEE to raspbian by referring to the links below.

- https://github.com/OP-TEE/optee_os/issues/2854
- https://github.com/OP-TEE/optee_os/issues/2875
-  https://github.com/benhaz1024/raspbian-tee

Some people say it worked, but I'm not booting up. I hope someone solves my problem.
My development environment and procedures are as follows.

- Host OS : ubuntu 16.04
- Cross Build Toolchain
  gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu.tar.xz
  gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf.tar.xz
- Hardware : Raspberry pi3 B+
- Raspbian : 2019-09-26-raspbian-buster-lite.img
- MicroSD : 8GB

1. Flasing Raspbian into MicroSD 
$ sudo dd bs=4M if=2019-09-26-raspbian-buster-lite.img of=/dev/sdd status=progress conv=fsync

I checked that the Razbian boots and runs normally in this state for an intermediate inspection.

2. download benhaz1024/raspbian-tee 
$ git clone https://github.com/benhaz1024/raspbian-tee.git

3. config your cross build toolchain at config.mk
$ vi config.mk
  export CROSS_COMPILE := /home/work/raspbian-tee/toolchains/aarch32/bin/arm-linux-gnueabihf-
	export CROSS_COMPILE_AARCH64 := /home/work/raspbian-tee/toolchains/aarch64/bin/aarch64-linux-gnu-

4. download all packages and build
$ ./prepare-env.sh
$ make patch
$ make

5. confirm out folder results
All the same output as the capture screen at https://github.com/gagachang/raspbian-tee/tree/add_xtest#build was in the out folder.

6. Install
https://github.com/gagachang/raspbian-tee/tree/add_xtest#install
I copied the results from out to MicroSD with raspbian installed.

$ sudo mount /dev/sdd1 /media/sdd1
$ sudo cp -rf ./out/boot/* /media/sdd1

$ sudo mount /dev/sdd2 /media/sdd2
$ sudo cp -rf ./out/rootfs/* /media/sdd2

$ sudo umount /dev/sdd1
$ sudo umount /dev/sdd2

7. rpi3 Booting
I inserted the microSD that I worked on above into my Target (rpi3 b+) and then tried booting it up, and it's not working.
In HDMI connected to the monitor, only gradient screens are displayed, and nothing is output from uart. 

I don't know what's wrong with me.
Please help me if anyone is successful.

**Comment by jbech-linaro** [comment]
Since it's nothing that is officially supported in OP-TEE, it's hard for us to give any good advice, it's probably better to file a question at https://github.com/benhaz1024/raspbian-tee.

**Comment by niusenc** [comment]
@SangsubLim  Hi, did you solve this problem? I also met the same problem.
