### ISSUE TITLE
How Can I or Can printf out the Aes key in TA code

### ISSUE THREAD

**Issue by gitgonewithwind** [OP-TEE/optee_os#3570]
hi I encrypt my binary code in host and decrypt it in TA  as below:
1.encrypt the app executable binary code first.
2.use client application send the encrypted binary to TA
3.use TA decrypt the encrypted binary to normal binary.
4.send back normal binary to client in RAM and run it ????
 
so I need a fixed key  for encrypty in host and a fixed key for decrypt in TA
I am reading  the optee_examples/aes code, 
I want to know 

How Can I or Can I printf out the Aes key in TA code ?

Thanks

**Comment by jforissier** [comment]
You can use `printf()` in your TA (you need `#include <stdio.h>` like in a normal Linux application).
Another option is `IMSG()` / `DMSG()` which can be enabled selectively based on the value of `CFG_TEE_TA_LOG_LEVEL`.

**Comment by gitgonewithwind** [comment]
@jforissier  
sorry, the printf works well for my code now .I mean  where is the key stored in code ?  or we can not find the key in the code?

 I add printf in aes_ta.c ,it print out a5a5a5a5a5a5a5 ...   it's dummy key not the true key




/*
 * Process command TA_AES_CMD_SET_KEY. API in aes_ta.h
 */
static TEE_Result set_aes_key(void *session, uint32_t param_types,
				TEE_Param params[4])
{
	const uint32_t exp_param_types =
		TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT,
				TEE_PARAM_TYPE_NONE,
				TEE_PARAM_TYPE_NONE,
				TEE_PARAM_TYPE_NONE);
	struct aes_cipher *sess;
	TEE_Attribute attr;
	TEE_Result res;
	uint32_t key_sz;
	char *key;

	/* Get ciphering context from session ID */
	DMSG("Session %p: load key material", session);
	sess = (struct aes_cipher *)session;

	/* Safely get the invocation parameters */
	if (param_types != exp_param_types)
		return TEE_ERROR_BAD_PARAMETERS;

	key = params[0].memref.buffer;
	key_sz = params[0].memref.size;
	int i;
		printf("\nkey_ta1=\n");
		for(i=0;i<key_sz;i++)
			printf("%x",key[i]);

		printf("\n");


	if (key_sz != sess->key_size) {
		EMSG("Wrong key size %" PRIu32 ", expect %" PRIu32 " bytes",
		     key_sz, sess->key_size);
		return TEE_ERROR_BAD_PARAMETERS;
	}

	/*
	 * Load the key material into the configured operation
	 * - create a secret key attribute with the key material
	 *   TEE_InitRefAttribute()
	 * - reset transient object and load attribute data
	 *   TEE_ResetTransientObject()
	 *   TEE_PopulateTransientObject()
	 * - load the key (transient object) into the ciphering operation
	 *   TEE_SetOperationKey()
	 *
	 * TEE_SetOperationKey() requires operation to be in "initial state".
	 * We can use TEE_ResetOperation() to reset the operation but this
	 * API cannot be used on operation with key(s) not yet set. Hence,
	 * when allocating the operation handle, we load a dummy key.
	 * Thus, set_key sequence always reset then set key on operation.
	 */

	TEE_InitRefAttribute(&attr, TEE_ATTR_SECRET_VALUE, key, key_sz);

	TEE_ResetTransientObject(sess->key_handle);
	res = TEE_PopulateTransientObject(sess->key_handle, &attr, 1);
	if (res != TEE_SUCCESS) {
		EMSG("TEE_PopulateTransientObject failed, %x", res);
		return res;
	}

	TEE_ResetOperation(sess->op_handle);
	res = TEE_SetOperationKey(sess->op_handle, sess->key_handle);
	//int i;
		printf("\nkey_ta2=\n");
		for(i=0;i<key_sz;i++)
			printf("%x",key[i]);

**Comment by jforissier** [comment]
> @jforissier
> sorry, the printf works well for my code now .I mean where is the key stored in code ? or we can not find the key in the code?
> 
> I add printf in aes_ta.c ,it print out a5a5a5a5a5a5a5 ... it's dummy key not the true key
> 

In the AES example, this value comes from here:
https://github.com/linaro-swg/optee_examples/blob/3.8.0/aes/host/main.c#L177-L178

**Comment by gitgonewithwind** [comment]
@jforissier 
I got it now. AES use same key for encrypt and decrypt.  I  was wrong to think it's rsa using different keys for encrypt and decrypt

**Comment by gitgonewithwind** [comment]
in optee_examples/aes code , I can not encrypt the bigger file whose size is bigger than 1M ?
any help?
./optee_example_aes                       
fsize=1622988                                                                   
Prepare session with the TA                                                     
D/TA:  TA_OpenSessionEntryPoint:407 Session 0x123250: newly allocated           
Prepare encode operation                                                        
D/TA:  alloc_resources:124 Session 0x123250: get ciphering resources            
Load key in TA                                                                  
D/TA:  set_aes_key:240 Session 0x123250: load key material                      
                                                                                
key_ta1=                                                                        
a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5                                                
                                                                                
key_ta2=                                                                        
a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5                                                
                                                                                
key1=                                                                           
a5a5a5a5a5a5a5a5a5a5a5a5aD/TA:  reset_aes_iv:321 Session 0x123250: reset initiar
5a5a5a5                                                                         
Reset ciphering operation in TA (provides the initial vector)                   
Encode buffer from TA                                                           
optee_example_aes: TEEC_InvokeCommand(CIPHER) faileD/TA:  TA_CloseSessionEntryPn
d 0xffff000c origin 0x1

**Comment by etienne-lms** [comment]
The shm (`CFG_SHMEM_SIZE`) default size is 2MByte and crypto test allocates an input buffer and an output buffer, Maybe check `CFG_SHMEM_SIZE`.

**Comment by jforissier** [comment]
@etienne-lms isn't `libteec` supposed to use dynamic shared memory when supported (`CFG_CORE_DYN_SHM=y`) [1]? And therefore not use the reserved shm pool? (which could then be disabled via `CFG_CORE_RESERVED_SHM=n` since patch 8aeb6c94).

[1] https://github.com/OP-TEE/optee_client/blob/3.8.0/libteec/src/tee_client_api.c#L749-L761

**Comment by etienne-lms** [comment]
Ho! that's true @jforissier, I forgot about dyn-shm.
Sorry @gitgonewithwind. Check `CFG_CORE_RESERVED_SHM` and you Linux kernel version for shm registering support. If dynamic-shm is enabled, there should not be such restriction on shared memory buffer sizes.

**Comment by gitgonewithwind** [comment]
thank you @jforissier @etienne-lms 
I will do that if I need later.
now I remove  -g option when I compile my app. the size is about 5K. I think 1M is enough for it now.


Thank you very much for you kind help. now I almost finish my current project for pico-imx7-technexion  board.

some days late I will try  Imx8 MAAXboard which does not support  in optee_os now. I will ask your help again.
