### ISSUE TITLE
Set/Get interrupt operations in GPIO driver

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/optee_os#3572]
Hello,

I have some questions about a GPIO driver.
I am writing a GPIO driver for the Raspberry Pi 3 model b+ platform.
According to `core/include/gpio.h`, it seems that we need to implement six basic operations.
However, when I was implementing the `set/get_interrupt()`, I didn't know which register should I set.

I have read the [BCM2837 datasheet](https://cs140e.sergio.bz/docs/BCM2837-ARM-Peripherals.pdf) page 96-100.
The registers related to GPIO interrupt are GPEDS, GPREN, GPFEN, GPHEN, GPLEN, GPAREN, GPAFEN.

Should I set the above registers?
Or I need to set the ARM Interrupt registers on datasheet page 112.

Sorry for my first time to practice implementing a device driver.
Any suggestions would be greatly appreciated.
Thank you!

**Comment by vchong** [comment]
You're right. It's not exactly clear what registers to change to enable/disable interrupts on GPIO pins. Perhaps the maintainer of the Broadcom ns3 platform (@sandeepbrcm) can comment?
