### ISSUE TITLE
Should OPTEE handle asynchronous data aborts?

### ISSUE THREAD

**Issue by a21152** [OP-TEE/optee_os#3576]
When compiled with ARM32, OPTEE is handling unmasking asynchronous data aborts.

see: https://github.com/OP-TEE/optee_os/blame/master/core/arch/arm/kernel/thread.c#L1206

While with ARM64, it seems async. data aborts are masked via SPSR.

This seems to be a regression caused by https://github.com/OP-TEE/optee_os/commit/a702f5e71e791925251574339bd60c29cca5547d, where read_spsr() should probably have been read_cpsr().

That said I have two questions:

1. Could you please confirm this analysis?
2. Should we enable TEE to handle async data aborts in general? If we do, it means whenever we switch from S.EL1 to S.EL0, we could potentially crash the target TA, forcing it even a keep-alive TA to be killed, thus defeating the keep-live feature. The cause of async aborts usually come from hardware or non-secure code.

Thanks, Ali

**Comment by jenswi-linaro** [comment]
Yes, I think that asynchronous data aborts are unmasked in ARM32, in fact they are so for ARM64 too. However, I think that asynchronous data aborts are ignored by OP-TEE so TAs are not terminated etc.

I'm not sure what is the best course of action here. Given that we ignore asynchronous data aborts it would make sense to never unmask them to begin with.

**Comment by a21152** [comment]
Async data aborts are masked upon TEE-entry via init_regs().

ARM32: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread.c#L330
ARM64: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread.c#L363

I don't think they are ignored if unmasked because data aborts are trapped in __thread_dabort_handler ()https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread_a32.S#L535 and eventually calls handle_user_ta_panic(https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/abort.c#L330).

The reason async data aborts are eventually unmasked is because https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread.c#L1213, where `read_spsr()` is supposed to be `read_cpsr()`. This appears to be a typo from https://github.com/OP-TEE/optee_os/commit/a702f5e71e791925251574339bd60c29cca5547d.

**Comment by jenswi-linaro** [comment]
You're right about the spsr. `get_fault_type()` was supposed to ignore external aborts, but it seems that's only the case when paging is enabled. You're welcome to submit the needed fixes in a PR or I can fix it if you prefer that. Please let me know.

**Comment by a21152** [comment]
Thanks for the confirmation and clarification Jens. I will submit a fix.

**Comment by a21152** [comment]
This is actually my first PR on github. Let me know if things don't look right.

https://github.com/OP-TEE/optee_os/pull/3589

**Comment by a21152** [comment]
In particular, it seems I don't have permission to link the PR with the issue. Could you please help?

**Comment by jforissier** [comment]
> In particular, it seems I don't have permission to link the PR with the issue. Could you please help?

What kind of link do you have in mind?
Just mentioning the PR number here, as you did, is enough to create a link. Check the PR now, you will see this issue is mentioned.

You can also add a `Fixes: ` tag to you patch, with the URL of this page if you wish.

**Comment by a21152** [comment]
I was trying to link the issue with the PR because on the right it still shows:

```
Linked pull requests
Successfully merging a pull request may close this issue.

None yet
```

Updated `Fixes`.

**Comment by jforissier** [comment]
@a21152 I had not noticed this possibility ;-) we don't use it.

**Comment by jbech-linaro** [comment]
> @a21152 I had not noticed this possibility

Neither have I, and I'm usually pretty good at picking up GitHub features :)
