### ISSUE TITLE
ftrace: assertion failed in TEE core

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3580]
On QEMU:
```
make -j10 CFG_FTRACE_SUPPORT=y CFLAGS_ta_arm32="-O0 -pg" run
```
```
$ xtest 4002
...
E/TC:? 0 assertion '!res' failed at core/arch/arm/kernel/user_ta.c:571 <user_ta_dump_ftrace>
```

`mobj->size` was 6368, which `vm_unmap()` does not like.

**Comment by jforissier** [comment]
`git bisect` points to cffe74d2446b078ec6c20c69f33f146a4312bac3:

```
cffe74d2446b078ec6c20c69f33f146a4312bac3 is the first bad commit
commit cffe74d2446b078ec6c20c69f33f146a4312bac3
Author: Jens Wiklander <jens.wiklander@linaro.org>
Date:   Tue Jan 21 18:15:01 2020 +0100

    core: fix assigned size of struct mobj_reg_shm
    
    Prior to this patch a struct mobj_reg_shm was initialized with num_pages
    * SMALL_PAGE_SIZE without taking page_offset into account. This patch
    fixes that by subtracting the result of the multiplication above with
    page_offset.
    
    Acked-by: Jerome Forissier <jerome@forissier.org>
    Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

:040000 040000 095ecbc6291848e799619aac607bdcd7e79ec900 432e41bd37d8fd209d86375f028a059eae01567c M	core
```

**Comment by jenswi-linaro** [comment]
We have two options to go forward with, either we relax the alignment requirement in `vm_unmap()` or we'll round up the size before calling `vm_unmap()`. I think I'd prefer the latter, but if we do that I think we should impose the same strict alignment on `vm_map()` for consistency. My reasoning is that without the strict alignment check on the size (and va) in `vm_unmap()` we may unintentionally unmap stuff that shouldn't be unmapped.

What do you think?

**Comment by jforissier** [comment]
@jenswi-linaro there are pros and cons with both approaches, however the POSIX `mmap()` and `munmap()` do not impose restrictions on the size. It makes sense of course because `mmap()` may optionally read data from a file, and therefore one may need to specify the size with byte precision. We obviously don't have this requirement, but still, I would think it is a bit less error-prone to behave like the POSIX interface.

**Comment by jenswi-linaro** [comment]
Makes sense, I'll fix.

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/optee_os/pull/3583
