### ISSUE TITLE
Time Taken for SMC into TEE

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#3581]
I want to ask whether the size of arguments used in TA invocation have any affect in the time taken to make the SMC call.

Case A: Client invokes TA and sends 1 argument of size 1 byte
Case B: Client invokes TA and sends 1 argument of size 500 bytes

Will time taken to invoke TA be the same in both cases OR will case A be faster than case B ?

Thanks

**Comment by jenswi-linaro** [comment]
If the only difference is a 1 or 500 bytes pre-registered/allocated buffer it's not expected that there will be any time difference.

If the 1 byte case uses value parameters instead it might be slightly faster, but I would measure it carefully before taking it for granted.

**Comment by a2t2** [comment]
1 byte uses value parameter.
500 byte cases uses memref parameter.

Is there any documentation available that indicates any kind of time difference ?

**Comment by jenswi-linaro** [comment]
> Is there any documentation available that indicates any kind of time difference ?

None I'm aware of.
