### ISSUE TITLE
optee on iMX8M Mini

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3586]
Hi,
Anyone have any idea of the steps to follow to implement opt in imx8m?
I have already read the manuals but I have no concrete results.

Thanks.

**Comment by Raincode** [comment]
Hi,

I assume you have a functional Yocto environment to build an image for your board?

AFAIK, you need U-Boot SPL to load OP-TEE which is then started by BL31. However, i.MX 8M uses U-Boot SPL by default. You just need to make sure packagegroup-fsl-optee is included in your IMAGE_INSTALL. In my experience, this automatically achieved if COMBINED_FEATURES contains "optee".

[community.nxp.com](community.nxp.com) might have some useful information as well.

**Comment by igoropaniuk** [comment]
Hi @21212124,

just a bit more details to what @Raincode already mentioned.
Not sure about the downstream U-boot fork from NXP, but in the mainline U-boot for iMX8MM EVK the boot sequence is:

BootROM-> SPL -> SPL loads DDR firmware -> SPL loads FIT image (contains: TF-A binary; U-boot proper; U-boot DTB;) -> TF-A -> U-boot proper.

You really don't need to play with Yocto/OE staff just to check if OP-TEE is loaded, you can just generate read-to-flash imx image (with U-boot, TF-A etc.) by building in the mainline U-boot. What you can do:

1. Build OP-TEE for iMX8MM (`imx8mm-evk` flavor).
2. Fetch and build TF-A by following steps in https://github.com/u-boot/u-boot/blob/master/board/freescale/imx8mm_evk/README, but also provide params for OP-TEE BL32:
```
 make PLAT=imx8mm
	NEED_BL32=yes \
	BL32=$(OPTEE_BIN) \
	BL32_EXTRA1=$(OPTEE_BIN_EXTRA1) \
	BL32_EXTRA2=$(OPTEE_BIN_EXTRA2) \	
	SPD=opteed \ 
	BL32_BASE=<bl32_base_address> bl31
```
`BL32_BASE` you can find in https://github.com/u-boot/u-boot/blob/master/arch/arm/mach-imx/mkimage_fit_atf.sh

3. Put bl31.bin and tee.bin to u-boot build directory.
4. Follow next steps from https://github.com/u-boot/u-boot/blob/master/board/freescale/imx8mm_evk/README to get the final ready-to-flash `flash-bin`.
