### ISSUE TITLE
[RFC]: Add support for passing boot event logs to a TPM

### ISSUE THREAD

**Issue by javieralso-arm** [OP-TEE/optee_os#3596]
In case a system needed to implement Measured Boot it would be necessary the use of a TPM, which could be implemented either as a discrete chip or a secure service (e.g, through OPTEE). 

If using the latter option, the TPM service will certainly not be ready during the early stages of the boot process (BL1 and BL2), so it will be necessary to keep a TPM event log in secure memory by the early bootloaders so it could be extended at a later time, as soon as the TPM Service is ready. 

It is very unlikely that the address of the event log in secure memory and its size will be known at build time, therefore a mechanism to pass that information to the TA is needed. 

In order to add support for this, I would propose the following changes (already implemented in my local branch): 

1. Use the DTB to pass the event log information (address in secure memory and size) to OPTEE so it can read that information at boot up and keep it internally. The secure memory address for the event log could be then zeroed on the DTB to avoid propagating it to non-secure memory, if needed.

2. Extend the TEE internal API interface with a new call to get a copy of the event log as well as its size. OPTEE will copy the log into a buffer passed by the TA through that interface. 

This way, OPTEE can receive the event log parameters dynamically from the early bootloaders and provide access to the TPM event log to the TA if needed.

**Comment by jforissier** [comment]
Hi @javieralso-arm,

1. Yes, I don't know how you did it, but it could be a `reg` property in a new node under `/secure-chosen` for instance.
2. A new function may not even be needed. The service should typically be implemented as a pseudo TA (because we prefer not to add new syscalls) -- the "system" PTA is a good candidate (`core/pta/system.c`). Then the measurement TA can call the PTA directly. Unless we expect several users of this interface, it's not really worth adding a function to `libutee` IMO.

**Comment by jbech-linaro** [comment]
@javieralso-arm , this has been briefly discussed in the past with some of your colleagues at Arm and I think the consensus was that the most plausible solution was more or less what you've proposed in here. I'd be happy to see [RFC] code for this in OP-TEE and the other boot loaders in use before loading/running OP-TEE.

PTA approach as suggested by Jerome seems to make most sense in this case.

**Comment by javieralso-arm** [comment]
Thank you very much for your feedback, @jforissier and @jbech-linaro 

I didn't actually consider the option of a PTA (I'm still quite new on OPTEE and wasn't very sure that would be a good option) but I will definitely give it a try.

What I actually did was to implement my system call in tee_internal_api_extensions (although only one client would make use of it). This system call would accept a buffer where optee would copy the event log as well as a pointer to a size parameter.

If I understood properly, @jforissier' suggestion is pretty much the same, but implementing my functionality inside the system PTA rather than as a system call, right?

Cheers,
Javier

**Comment by jbech-linaro** [comment]
> If I understood properly, @jforissier' suggestion is pretty much the same, but implementing my functionality inside the system PTA rather than as a system call, right?

Yes, exactly!

**Comment by javieralso-arm** [comment]
Perfect!!

Then I will update my implementation as well as the tests I already added to optee_tests

**Comment by javieralso-arm** [comment]
Hi @jforissier 

I started pull request #3603 with my changes implementing the support for the TPM service as a PTA command, as suggested by you.

I added some tests on optee_test and seems to be working fine.

Cheers,
Javier

**Comment by javieralso-arm** [comment]
Patch for this merged, so closing.

Thanks,
Javier
