### ISSUE TITLE
IMX6ul optee CAAM driver for encryption not giving consistent results

### ISSUE THREAD

**Issue by alekarasma** [OP-TEE/optee_os#3604]
Hello Everyone,

I am using imx6ul optee caam driver for crypto stuff in my project.
For testing the ouput, I am sending 8 bytes of data and 8 bytes of key as input, encryption algo as DES_ECB_NOPAD.

Function sequence I am calling is :

1. crypto_cipher_alloc_ctx -------> do_allocate(caam_cipher.c)
2. crypto_cipher_init   --------> do_init (caam_cipher.c)
3. crypto_cipher_update -----> do_update (caam_cipher.c)
4. crypto_cipher_free_ctx ----->do_free (caam_cipher.c)

The problem I am facing is, I dont get consistent result, i.e sometimes I get encrypted ouput (1 out of 4 run) and sometimes instead of 0's (3 out of 4).

Is there anything I have to take care for Initialisation? Or I have to wait for any signal for encryption to complete. 

I appreciate any help, any kind of pointers to search for.

Regards,
Asma

**Comment by Emantor** [comment]
Correct me if I am wrong, but aren't you missing a call to `cyrpto_cipher_final()`?

**Comment by alekarasma** [comment]
You are right @Emanator. I didnt add it because in caam_cipher.c nothing is being done in final call.
Code snippet as shown below.

> 
/**
 * @brief   Finalize of the cipher operation
 *
 * @param[in] ctx    Caller context variable
 * @param[in] algo   Algorithm ID of the context
 */
static void do_final(void *ctx __unused, enum imxcrypt_cipher_id algo __unused)
{
}

>

**Comment by Raincode** [comment]
One thing to check may be that the caam job ring is disabled in the Linux device tree / not somehow being used by Linux. For example, on my i.MX 8MQ if I want to enable OP-TEE, I have to remove the CAAM Jr it uses from the Linux device tree by adding `disabled = "true"` or so to the node:

```
diff --git a/fsl-imx8mq.dtsi b/fsl-imx8mq.dtsi
index cd908ba..6bd03cb 100644
--- a/fsl-imx8mq.dtsi
+++ b/fsl-imx8mq.dtsi
@@ -1420,6 +1420,7 @@
 			 compatible = "fsl,sec-v4.0-job-ring";
 			 reg = <0x1000 0x1000>;
 			 interrupts = <GIC_SPI 105 IRQ_TYPE_LEVEL_HIGH>;
+			 status = "disabled";
 		};
 
 		sec_jr1: jr1@2000 {
```

This is just a wild guess by me, no guarantees it has remotely anything to do with your problem...

**Comment by Emantor** [comment]
> You are right @emanator. I didnt add it because in caam_cipher.c nothing is being done in final call.
> Code snippet as shown below.
There is no `caam_cipher.c` file within upstream OP-TEE. Looking into it upstream currently only implements hash functions, not symmetric encryption functions. The definitions for the descriptors are there, but no implementations are available.

**Comment by jforissier** [comment]
@Raincode please note -- you have used the wrong user tag :open_mouth: the correct one is @Emantor

**Comment by alekarasma** [comment]
Oops sorry for that :).

@Emantor looks like its been removed from OPteeOs.
@Raincode  My system is not freezing at all. But when I disabled in device tree at that time it is getting stuck because optee do check if it is enabled or not and set the status as required.

There is something more, I will trey to search in Secure Manual of i.Mx.

**Comment by Raincode** [comment]
Just another idea....

I don't know the state for imx6, but for imx8 there is a cryptodev module for GNU/Linux which exports symmetric crypto and hashing operations from CAAM. The OpenSSL library can leverage this cryptodev engine to access the CAAM operations.

Perhaps it is possible to try encrypting some data in GNU/Linux+OpenSSL through CAAM and see if the same problem exists? This might help narrowing down the issue.

**Comment by alekarasma** [comment]
thanks @Raincode @Emantor @jforissier 

But now it looks like altogether a different issue. 

This is my structure to send data to PTA and get data out of PTA.

> **Host App:**
> #define MAX_BUFFER_SIZE     1024
> #define MAX_KEY_SIZE            24
>
> typedef struct {
>   uint8_t key_size;
>   uint8_t key[MAX_KEY_SIZE];                       /*Key Size*/
>   uint16_t data_size;
>   uint8_t in_data[MAX_BUFFER_SIZE];	        /* Plain data input buffer */
>   uint8_t out_data[MAX_BUFFER_SIZE];         /* Encrypted/Decrypted data output buffer*/
>   uint8_t trigger;
> } _crypto_data_t;
> 
> 
>  op.params[1].tmpref.buffer = crypto_data.in_data;
>   op.params[1].tmpref.size = sizeof(data);
>   op.params[2].tmpref.buffer = crypto_data.out_data;
>   op.params[2].tmpref.size = sizeof(data);
>   op.params[3].value.a = crypto_data.trigger;
> 
>   op.paramTypes = TEEC_PARAM_TYPES(TEEC_VALUE_OUTPUT, TEEC_MEMREF_TEMP_INPUT,
> 					 TEEC_MEMREF_TEMP_OUTPUT, TEEC_VALUE_INPUT);
>  tee_res = TEEC_InvokeCommand(&session, PTA_DES_DPA_ENCRYPT, &op, &ret_orig);
> 
>
>
>  **In PTA:**
>  static TEE_Result des_dpa_encrypt(void *pSessionContext  __unused, uint32_t type, 			
> 											TEE_Param p[TEE_NUM_PARAMS])
> {
> 	uint32_t exp_pt = TEE_PARAM_TYPES(TEE_PARAM_TYPE_VALUE_OUTPUT,
> 								TEE_PARAM_TYPE_MEMREF_INPUT,
> 								TEE_PARAM_TYPE_MEMREF_OUTPUT,
> 								TEE_PARAM_TYPE_VALUE_INPUT);
> 
> 	TEE_Result ret;					
> 	
> 	if (exp_pt != type) {
> 		MSG("bad parameter types.\n");
> 		return TEE_ERROR_BAD_PARAMETERS;
> 	}
> 
> 	DMSG("trigger type = %d", p[3].value.a);
> 
> 	dpa_trigger_enable(p[3].value.a == TRIGGER_2);
> 
> 	ret = crypto_cipher_update(cipher_ctx, encrypt_algo, ENCRYPTION_MODE, true, \
> 					p[1].memref.buffer, p[1].memref.size, p[2].memref.buffer );
> 
> 	if (ret != TEE_SUCCESS)
> 		goto exit;
> 
> 	return ret;
> 
> exit:
> 	crypto_cipher_free_ctx(cipher_ctx, encrypt_algo);
> 	return ret;
> 
> }
> 
> 
> 

Output data is as shown in the above msgs .

**But when I defined out data variable as local in PTA itself as shown below, it works perfectly fine.**

> static TEE_Result des_dpa_encrypt(void *pSessionContext  __unused, uint32_t type, 			\
> 											TEE_Param p[TEE_NUM_PARAMS])
> {
> 	uint32_t exp_pt = TEE_PARAM_TYPES(TEE_PARAM_TYPE_VALUE_OUTPUT,
> 								TEE_PARAM_TYPE_MEMREF_INPUT,
> 								TEE_PARAM_TYPE_MEMREF_OUTPUT,
> 								TEE_PARAM_TYPE_VALUE_INPUT);
> 
> 	TEE_Result ret;		
> 	**uint8_t out_data[1024];**
> 	
> 	if (exp_pt != type) {
> 		MSG("bad parameter types.\n");
> 		return TEE_ERROR_BAD_PARAMETERS;
> 	}
> 
> 	DMSG("trigger type = %d", p[3].value.a);
> 
> 	dpa_trigger_enable(p[3].value.a == TRIGGER_2);
> 
> 	**ret = crypto_cipher_update(cipher_ctx, encrypt_algo, ENCRYPTION_MODE, true, \
> 					p[1].memref.buffer, p[1].memref.size, out_data );**
> 	
> 	uint16_t length = 0;
> 			while(length++ != p[1].memref.size)
> 					MSG("%x", out_data[length]);
> 	
> 	p[2].memref.buffer = out_data[0];
> 
> 	if (ret != TEE_SUCCESS)
> 		goto exit;
> 
> 	return ret;
> 
> exit:
> 	crypto_cipher_free_ctx(cipher_ctx, encrypt_algo);
> 	return ret;
> 
> }


It looks like a memory relate issue, Can some one please help me pointing out what am I doing wrong?

Thanks & Regards,
Asma

**Comment by jforissier** [comment]
Where is `crypto_data` defined? What is `sizeof(data)`? Where do you print the output buffer?

**Comment by alekarasma** [comment]
It is defined as global variable in host application:
_crypto_data_t crypto_data;

And then printed in host application as below:
 ```
op.params[1].tmpref.buffer = crypto_data.in_data;
op.params[1].tmpref.size = sizeof(data);
op.params[2].tmpref.buffer = crypto_data.out_data;
op.params[2].tmpref.size = sizeof(data);
op.params[3].value.a = crypto_data.trigger;

> /*Send command to encrypt data*/
>   tee_res = TEEC_InvokeCommand(&session, PTA_DES_DPA_ENCRYPT, &op, &ret_orig);
> 
>   if (tee_res != TEEC_SUCCESS) {
> 		  fprintf(stderr, "Failed to open TEE InvokeCommand: 0x%" PRIx32 "\n",
> 								tee_res);
> 		goto close; 
> 	} 
> 
>   out_data_size =  op.params[2].tmpref.size;
>   printf("Encrypted data is :");
> 
>   for(i= 0; i < out_data_size; i++)
>     printf("%x ", crypto_data.out_data[i]);
> 

```
 
When I send the reference of output data from host application as memref parameter as shown, I get inconsistent result.

however If I create a local variable array for output reference as below in PTA for cipher operation, it works perfectly fine.
```
static TEE_Result des_dpa_encrypt(void *pSessionContext __unused, uint32_t type,
TEE_Param p[TEE_NUM_PARAMS])
{
uint32_t exp_pt = TEE_PARAM_TYPES(TEE_PARAM_TYPE_VALUE_OUTPUT,
TEE_PARAM_TYPE_MEMREF_INPUT,
TEE_PARAM_TYPE_MEMREF_OUTPUT,
TEE_PARAM_TYPE_VALUE_INPUT);

TEE_Result ret;
TEE_Result ret;
uint8_t out_data[1024];

if (exp_pt != type) {
MSG("bad parameter types.\n");
return TEE_ERROR_BAD_PARAMETERS;
}

DMSG("trigger type = %d", p[3].value.a);

dpa_trigger_enable(p[3].value.a == TRIGGER_2);

ret = crypto_cipher_update(cipher_ctx, encrypt_algo, ENCRYPTION_MODE, true,
p[1].memref.buffer, p[1].memref.size, out_data );

uint16_t length = 0;
while(length++ != p[1].memref.size)
MSG("%x", out_data[length]);

p[2].memref.buffer = out_data[0];

if (ret != TEE_SUCCESS)
goto exit;
```

Do I have to do any kind memory allocation for PTA because the buffer is 1Kbyte?


Regards,
Asma

**Comment by jforissier** [comment]
Looks OK. Have you tried `malloc()` + `TEEC_RegisterSharedMemory()` instead of a global buffer?

**Comment by alekarasma** [comment]
I tried dynamic memory allocation but with same result. I have not tried TEEC_RegisterSharedMemory(), will have a look.

**Comment by alekarasma** [comment]
I tried TEEC_RegisterSharedMemory(), but still It did not work.
