### ISSUE TITLE
Execute ROM functions from an OP-TEE PTA

### ISSUE THREAD

**Issue by Zephyrus29** [OP-TEE/optee_os#3605]
Hi, as my part of the update process for my application, I want to use some of the boot ROM functions on the IMX6. To do so, I've mapped the boot ROM table using core_mmu_add_mapping with the MEM_AREA_IO_NSEC mem type. This lets me get the pointer to the function I want, but when I try to map it an execute it, I get a read permission fault. If I don't map it, I get a translation fault. 

What is the correct way, if any, of executing one of these functions?

**Comment by jenswi-linaro** [comment]
See if you can map it as `MEM_AREA_TEE_RAM_RX` instead.

**Comment by Zephyrus29** [comment]
Thanks for your help @jenswi-linaro , that lets me execute the function. 

Unfortunately the function promptly has a translation fault because it attempts to access one of the IO registers directly (0x020d801c). Mapping it doesn't change anything as I'd expect.  Looks like I'm going to have to use my back up plan of re-implementing the function in op-tee. Hopefully a good lesson for anyone trying to do the same thing in the future.
