### ISSUE TITLE
Linking external SO files in host side in optee-example

### ISSUE THREAD

**Issue by deekshith565** [OP-TEE/optee_os#3617]
Hi,

Can anyone help me in linking external .so files to main.c(host part) file in optee examples(i.e CA or user space), I tried but could not succeed.

Suppose for example in hello_world example, inside main if I want to use some external APIs of my own, I have libX.so file, I created include file inside /hello_world/host/include and added header files there of libX.so
Now I modified hello_world/CMakeLists.txt as below,

target_link_libraries (${PROJECT_NAME} PRIVATE teec PUBLIC X)
I'm stuck here, i tried few things but nothing helps
I get below error:

lib/gcc/arm-linux-gnueabihf/8.2.1/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lX

Kindly help!

**Comment by jforissier** [comment]
Hi,

This is a CMake question and I don't have much expertise with CMake... but I would think you have not declared your external library properly.

```cmake
add_library(foo SHARED IMPORTED)
set_property(TARGET foo PROPERTY IMPORTED_LOCATION /path/to/libfoo.so)
