### ISSUE TITLE
about SE

### ISSUE THREAD

**Issue by angusmart** [OP-TEE/optee_os#362]
Q1:OP-TEE designed SE  accessed directly in TEE, or indirectly accessed via REE? 
Q2:SE's drivers is in TEE, or REE?  optee_os whether support for driving development？ 
Q3:if support, how to developed optee_os drivers? the drivers is added in optee_os/core/drivers just like gic or uart?

**Comment by m943040028** [comment]
Q1. We can directly access SE in OP-TEE
Q2. SE drivers in TEE, but currently only QEMU emulated SE device is supported
Q3. Please refer to `core/tee/se/reader/passthru_reader` as example, you need to implement callbacks in `core/include/tee/se/reader/interface.h`

**Comment by angusmart** [comment]
why other platform SE device is not supported, and when other platform SE device will be supported？

**Comment by m943040028** [comment]
1. no real hardware to test
2. contribution is welcomed

**Comment by jbech-linaro** [comment]
@angusmart @pascal-brand-st-dev I think we have answered this and the discussion has stopped. Can we close this issue?

**Comment by pascal-brand-st-dev** [comment]
According to me, all the information has been provided and we can close this issue. @angusmart  let me know if it is not the case. Without any answer, I'll close the issue.
