### ISSUE TITLE
optee with Automotive Grade Linux on rpi3 

### ISSUE THREAD

**Issue by hklee93** [OP-TEE/optee_os#3628]
Hi, I've been trying to combine optee with Automotive Grade Linux (AGL) on rpi3. Thanks to https://github.com/benhaz1024/raspbian-tee, I successfully checked that optee works with AGL. Now one issue I'm facing is that when I put pure AGL on rpi3 (without optee), I normally see the following GUI on the screen.

https://www.96boards.org/assets/blog/agl-aff354dd567581ab1a6b0c07a38a9b0ba1bb66d2eab5a2b956bf93138ccd48eb.jpg
(img from https://www.96boards.org/blog/agl-on-dragonboard410c-part1/)

However, as soon as I put optee along with AGL, I don't see that GUI, but rather it stays at the booting screen (after rainbow screen) with the following lines. 

_[	21.773144] Bluetooth: HCI UART driver ver 2.3
[	21.777909] Bluetooth: HCI UART protocol H4 registered  
[	21.783272] Bluetooth: HCI UART protocol Three-wire (H5) registered  
[	21.814435] Bluetooth: HCI UART protocol Broadcom registered  
[	21.971751] Bluetooth: RFCOMM TTY layer initialized  
[	21.986261] Bluetooth: RFCOMM socket layer initialized  
[	21.991673] Bluetooth: RFCOMM ver 1.11  
(Blinking cursor here)_

At this point, I can connect to its shell using the following command
``$ sudo picocom -b 115200 /dev/ttyUSB2``
When I connect, it shows that I'm definitely running AGL

_Automotive Grade Linux 6.99.5 raspberrypi3 ttyS0_

_raspberrypi3 login: root
raspberrypi3:~# uname -a
Linux raspberrypi3 4.14.98-v7 #1 SMP Wed Feb 19 11:49:52 CST 2020 armv7l armv7l armv7l GNU/Linux_

Is this what others are complaining about the lack of HDMI support? I've seen the official doc mentioning the use of the official pi display. If I use that screen, could I see the AGL GUI on the screen? Or is this happening because I've overwritten files? Sorry about the messy question. I'm not quite familiar with manipulating all these booting related files.

**Comment by hklee93** [comment]
FYI, these are newly added files (besides tee-related files):
/boot/armstub8.bin
/boot/uboot.env
/root/lib/modules/4.14.98-v7/*

These are overwritten files:
/boot/bcm2710-rpi-3-b.dtb
/boot/bcm2710-rpi-3-b-plus.dtb
/boot/config.txt
/boot/uImage

**Comment by jbech-linaro** [comment]
> Is this what others are complaining about the lack of HDMI support? I've seen the official doc mentioning the use of the official pi display. If I use that screen, could I see the AGL GUI on the screen? Or is this happening because I've overwritten files? Sorry about the messy question. I'm not quite familiar with manipulating all these booting related files.

You're mixing apples and oranges. The reason why we have in the doc that we don't support HDMI, is simply because our root file system doesn't have all the necessary drivers and no configuration for it. I.e., our setup is is a stripped down root file system meant to be used over an UART to be able to run xtest.

If you have all drivers, enable them correctly, then I'm sure HDMI will work. But as said, that is nothing we've done here in the official OP-TEE for Rpi3 builds. Probably better ask benhaz1024 who has created the unofficial port for Raspbian.

Having said that, I wouldn't mind seeing patches sent here that makes it possible to run Raspbian from the official tree.

**Comment by hklee93** [comment]
@jbech-linaro  Thanks for replying! I actually noticed today that dmesg was throwing bunch of failure messages. I'll take a look at it again tomorrow morning and see if I can ask narrow down questions related to building optee.
