### ISSUE TITLE
Switch to secure world from external Linux module

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/optee_os#3631]
Hello,

I am implementing a **linux module** that some functions of this module may switch to the _secure world_ to do something.
(e.g. the initialization of a hello world linux module may act as a CA, and invokes a TA in the _secure world_ to `IMSG("Hello");` )
Does it make sense to do this trick?

If the external module can do that,
are there any exported kernel symbols from OP-TEE linux driver, that external modules can directly use?
Or external modules need to invoke **tee-supplicant** and let the supplicant accomplish it.

Your suggestion will be greatly appreciated.
Thank you in advance.

**Comment by jforissier** [comment]
Hi @gagachang,

I think this is what you want: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=25559c22cef8.

**Comment by gagachang** [comment]
Hi @jforissier ,

That's exactly what I want, thank you very much!!
