### ISSUE TITLE
OP-TEE OS overrides GIC configurations done in TF-A BL31

### ISSUE THREAD

**Issue by Raincode** [OP-TEE/optee_os#3633]
Hello,

I have been familiarizing myself with the whole Arm/TrustZone/GICv3 interrupt architecture and doing some basic tests with BL31 and OP-TEE OS interrupt handling.

It appears that in the function `void gic_init(struct gic_data *gd, vaddr_t gicc_base __maybe_unused, vaddr_t gicd_base)` from the file `core/drivers/gic.c` completely overrides the GIC configuration for every single interrupt, disabling them, marking them as non-pending and especially setting them as non-secure.

Since BL31 is executed prior to OP-TEE OS and already configures the GIC, I personally find this default action not very sensible (it took me way longer than I care to admit to figure this out :D).

May I suggest removing the following code or at least making it opt-in? Is there a reason interrupts are configured in this way which I am missing?

```
for (n = 0; n <= gd->max_it / NUM_INTS_PER_REG; n++) {
	/* Disable interrupts */
	write32(0xffffffff, gd->gicd_base + GICD_ICENABLER(n));

	/* Make interrupts non-pending */
	write32(0xffffffff, gd->gicd_base + GICD_ICPENDR(n));

	/* Mark interrupts non-secure */
	if (n == 0) {
		/* per-CPU inerrupts config:
                       * ID0-ID7(SGI)   for Non-secure interrupts
                       * ID8-ID15(SGI)  for Secure interrupts.
                       * All PPI config as Non-secure interrupts.
		 */
		write32(0xffff00ff, gd->gicd_base + GICD_IGROUPR(n));
	} else {
		write32(0xffffffff, gd->gicd_base + GICD_IGROUPR(n));
	}
}
```

Cheers!

**Comment by jenswi-linaro** [comment]
Feel free to propose a PR. Keep in mind that this should work on ARMv7 too.

**Comment by Raincode** [comment]
My workaround was simply commenting out this for-loop. However, I cannot attest to this not having any side effects which I haven't noticed. I do know that BL31 runs `gicv3_distif_init` which performs `gicv3_spis_config_defaults` and `gicv3_rdistif_init` which performs `gicv3_ppi_sgi_config_defaults` (however, this configures all SGI/PPI as non-secure).

Therefore, my proposal would entail removing the default-configuration step for GIC from OP-TEE OS (things like enabling/disabling interrupts, configuring priorities etc.) and documenting that Trusted Firmware BL31 is assumed to fully initialize the GIC and provide the default configuration at boot.

So the question is whether there are any "essential" configurations of the GIC which OP-TEE OS relies on, and consequently would have to be added to TF-A if OP-TEE OS is present.

---

For example, OP-TEE OS configures

>ID8-ID15(SGI)  for Secure interrupts.

`io_write32(gd->gicd_base + GICD_IGROUPR(0), 0xffff00ff);`

While BL31

> /* Treat all SGIs/PPIs as G1NS by default. */

`gicr_write_igroupr0(gicr_base, ~0U);`
