### ISSUE TITLE
Access control from Linux to OP-TEE TA's

### ISSUE THREAD

**Issue by vesajaaskelainen** [OP-TEE/optee_os#3642]
While thinking on how pkcs11 TA should be handled in the OS side (and for some other features) there seems to be a need to authorize different key objects based on either group or by user.

I believe everything described below is doable and I am willing to do necessary changes but I want to get approval for what method to use. I have already in my previous life implemented solution for other TEE implementation with slightly different semantics but for similar purpose.

Global Platform TEE specification does give guidelines on how this should be done in REE.

From Linux user space application/library should issue `TEEC_OpenSession` with `TEEC_LOGIN_*` depending what kind of authorization is wanted from REE and what information should be provided by REE to TEE.

On user space only thing that gets some value from is `TEEC_LOGIN_GROUP` (and `TEEC_LOGIN_GROUP_APPLICATION`) indicating what group ID should be used.

Now when the request gets to the kernel it should differentiate operation depending on login request.

When `TEEC_LOGIN_USER` is requested it should auto-inject current user to OP-TEE open session call.

When `TEEC_LOGIN_GROUP` is requested it should verify that current user is member of given group ID.

Now with `TEEC_LOGIN_*_APPLICATION` we have a slight problem. What to use as a application identifier. One possibility could be SMACK's my label (eg. application launcher calls `smack_SetMyLabel`) as also envisioned in Tizen's Smack [notes.](https://wiki.tizen.org/Security/Tizen_2.X_Smack_Developer_Guide) This probably should be some kernel configure switch that selects what kind of application ID should be used so that different systems gets served properly.

Now we have a next question on how to encode this information to OP-TEE call.

GlobalPlatforms TEE specification does indicate that it should be one UUID from REE to TEE. For user and group we could probably encode them easily as UUID but application brings a bit of a problem.

TEE specification requires that these should be persistent and not to change on different boots. One possibility would be to encode user/group/application information as a UUIDv5. For this we need to have namespace key and data to be hashed.

We would need to allocate UUID for namespace key and then agree on how the data should be formatted.

Example what it could be:

For TEEC_LOGIN_USER:
`user=<uid>`
For TEEC_LOGIN_GROUP:
`group=<gid>`
For TEEC_LOGIN_APPLICATION:
`app=<smack my label>`
For TEEC_LOGIN_USER_APPLICATION:
`user=<uid>:app=<smack my label>`
For TEEC_LOGIN_GROUP_APPLICATION:
`group=<gid>:app=<smack my label>`

Now there are some problems with Linux user space API:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/tee.h?h=v5.6-rc3#n204

Defines `__u8 clnt_uuid[TEE_IOCTL_UUID_LEN];` which it probably should not be doing. And there is no place to pass group ID as required by the TEE specification. Also there is no possibility to pass custom connectionData that is supported by TEE specification. We could abuse the UUID field in here but I am not sure that is the right thing to do.

Now if we look at SMC call gate data for open session:

https://github.com/OP-TEE/optee_os/blob/master/core/include/optee_msg.h#L272

It does include `param[1].u.value.a-b uuid of Client` which should be good enough for the purpose.

So actual changes might be small -- so the real problems are Linux user space API and how to deal with that and then how to format client ID UUID from REE to TEE.

**Comment by jenswi-linaro** [comment]
> While thinking on how pkcs11 TA should be handled in the OS side (and for some other features) there seems to be a need to authorize different key objects based on either group or by user.

Do you have an example when it's needed?

> 
> I believe everything described below is doable and I am willing to do necessary changes but I want to get approval for what method to use. I have already in my previous life implemented solution for other TEE implementation with slightly different semantics but for similar purpose.

Sounds good!

> 
> Global Platform TEE specification does give guidelines on how this should be done in REE.
> 
> From Linux user space application/library should issue `TEEC_OpenSession` with `TEEC_LOGIN_*` depending what kind of authorization is wanted from REE and what information should be provided by REE to TEE.
> 
> On user space only thing that gets some value from is `TEEC_LOGIN_GROUP` (and `TEEC_LOGIN_GROUP_APPLICATION`) indicating what group ID should be used.

I suppose you mean __or__ since only one of them can be supplied at a time.

> 
> Now when the request gets to the kernel it should differentiate operation depending on login request.
> 
> When `TEEC_LOGIN_USER` is requested it should auto-inject current user to OP-TEE open session call.
> 
> When `TEEC_LOGIN_GROUP` is requested it should verify that current user is member of given group ID.

Agree

> 
> Now with `TEEC_LOGIN_*_APPLICATION` we have a slight problem. What to use as a application identifier. One possibility could be SMACK's my label (eg. application launcher calls `smack_SetMyLabel`) as also envisioned in Tizen's Smack [notes.](https://wiki.tizen.org/Security/Tizen_2.X_Smack_Developer_Guide) This probably should be some kernel configure switch that selects what kind of application ID should be used so that different systems gets served properly.

OK, as long as we don't exclude other schemes.

> 
> Now we have a next question on how to encode this information to OP-TEE call.
> 
> GlobalPlatforms TEE specification does indicate that it should be one UUID from REE to TEE. For user and group we could probably encode them easily as UUID but application brings a bit of a problem.
> 
> TEE specification requires that these should be persistent and not to change on different boots. One possibility would be to encode user/group/application information as a UUIDv5. For this we need to have namespace key and data to be hashed.
> 
> We would need to allocate UUID for namespace key and then agree on how the data should be formatted.
> 
> Example what it could be:
> 
> For TEEC_LOGIN_USER:
> `user=<uid>`
> For TEEC_LOGIN_GROUP:
> `group=<gid>`
> For TEEC_LOGIN_APPLICATION:
> `app=<smack my label>`
> For TEEC_LOGIN_USER_APPLICATION:
> `user=<uid>:app=<smack my label>`
> For TEEC_LOGIN_GROUP_APPLICATION:
> `group=<gid>:app=<smack my label>`
> 

Makes sense.

> Now there are some problems with Linux user space API:
> 
> https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/tee.h?h=v5.6-rc3#n204
> 
> Defines `__u8 clnt_uuid[TEE_IOCTL_UUID_LEN];` which it probably should not be doing. And there is no place to pass group ID as required by the TEE specification. Also there is no possibility to pass custom connectionData that is supported by TEE specification. We could abuse the UUID field in here but I am not sure that is the right thing to do.

I think that `clnt_uuid` should be considered just a fixed size buffer when holds data to be interpreted in combination with `clnt_login`. The name of the field may be a bit problematic, but I think we'll just have to live with that. Documentation (in the .h file) can be updated to help here.

When it comes to custom connectionData, if the `clnt_uuid` buffer is large enough it can be used.

When looking at the code I noticed that https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/tee/optee/call.c#n236 copies the wrong field. Which is a bit fortunate as there's no other checks on what's put in that field. 
Since the login method is a generic GP thing we should verify and/or populate the `clnt_uuid` field in 
tee_ioctl_open_session() if the device has the `TEE_GEN_CAP_GP` capability, else ignored.

> 
> Now if we look at SMC call gate data for open session:
> 
> https://github.com/OP-TEE/optee_os/blob/master/core/include/optee_msg.h#L272
> 
> It does include `param[1].u.value.a-b uuid of Client` which should be good enough for the purpose.
> 
> So actual changes might be small -- so the real problems are Linux user space API and how to deal with that and then how to format client ID UUID from REE to TEE.

Agree

**Comment by vesajaaskelainen** [comment]
>> While thinking on how pkcs11 TA should be handled in the OS side (and for some other features) there seems to be a need to authorize different key objects based on either group or by user.

>Do you have an example when it's needed?

We have two use cases.

1)

With pkcs11 TA our use case is that during device manufacturing we will provision X509 TLS Client Certificate (device ceritficate) for the device. Access for this certificate's private key operations should be protected so that only specific applications can access it. So this probably would be modeled with Linux group in the REE side. For this we need to enforce the authorization in Linux kernel and then provide the information to TEE that this is now selected "scope" for the key.

Then other processes in the system should still have possibility to protect their own private keys with TEE services. Eg. they will still have access to make TEE call but all TEE services must filter out unauthorized callers. Previously we had access control in Linux kernel for all operations.

2)

Application crypto. Eg. there are times when there is a need to protect some data so that it will be stored encrypted while in rest and also stay in backups of the device but can only be opened in this particular device (when proper application is making the call).

In here app requests to protect the data either with UID/GID/Smack's app label or such and then encrypted version is stored in eMMC. This can then be backed up if needed. When application wants to open the data then it uses same protection mechanism and ask to decrypt the data.

In this case the ACL operation must happen in Linux kernel and in Application Crypto TA.

>> On user space only thing that gets some value from is TEEC_LOGIN_GROUP (and TEEC_LOGIN_GROUP_APPLICATION) indicating what group ID should be used.

> I suppose you mean or since only one of them can be supplied at a time.

Yes.

> I think that clnt_uuid should be considered just a fixed size buffer when holds data to be interpreted in combination with clnt_login. The name of the field may be a bit problematic, but I think we'll just have to live with that. Documentation (in the .h file) can be updated to help here.

> When it comes to custom connectionData, if the clnt_uuid buffer is large enough it can be used.

Ok. Let's try how it works and see how it needs to be documented.

> When looking at the code I noticed that https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/tee/optee/call.c#n236 copies the wrong field. Which is a bit fortunate as there's no other checks on what's put in that field.
Since the login method is a generic GP thing we should verify and/or populate the clnt_uuid field in
tee_ioctl_open_session() if the device has the TEE_GEN_CAP_GP capability, else ignored.

Ok. Let's see what kind of code this generates.

I take that the approach is OK, so I will prepare a code for it so that we can all have a look how it would look like in different code bases.

**Comment by vesajaaskelainen** [comment]
@jenswi-linaro I have now test code available here:
https://github.com/vesajaaskelainen/optee_client/tree/optee-login-checks
https://github.com/vesajaaskelainen/linux/tree/optee-login-checks
https://github.com/vesajaaskelainen/optee_test/tree/optee-login-checks

Optee_client changes are quite simple.

Most logic lies in Linux kernel as needed to add UUIDv5 code there. There is no implementation for Smack in this code now.

Added also new session tests to optee_test. There could be even more tests but would need advice on how user switching and handling different groups permissions tests should be implemented in a way that xtest does not get broken on different setups ;). They could perhaps be split as special test suite that is not normally executed.

When I was rebasing the codes to latest versions for some reason regression_1018 test is failing.  Seems to be rather new test. Don't see why it would fail with any of my changes.

I was testing the code in Xilinx Zynq MPSoC zcu102 qemu in yocto and also ran them on qemu_v8 in your buildroot test environment (before rebasing thou). It seems mpsoc support is broken in master but was able to bisect that --- will create another issue for that.

How does the code look like?

@etienne-lms I was thinking that this kind of functionality is needed for pkcs11 ta and to separate different users/groups to have own private keys. Could you also check this out and give feedback how it could complement pkcs11 support? I was thinking that pkcs11 uri could include optional login method and optional group membership argument.

**Comment by etienne-lms** [comment]
I think the code looks nice. Since it defines a format for credentials information between CAs and TAs. This should be discussed, agreed on and described in the docs. 

Could you create a P-R in OP-TEE repos ([os](https://github.com/OP-TEE/optee_os)/[client](https://github.com/OP-TEE/optee_client)/[linux](https://github.com/linaro-swg/linux)) for these changes? Use "[RFC] " as prefix for the P-R names if you feel it is appropriate. It will be easier for anyone to make some comments.

As for pkcs11, do you think about constraining some API functions as `C_Login()` or `C_SetPIN()` to  have a logged session between CA and TA to operate?

**Comment by vesajaaskelainen** [comment]
Sorry it took a while as this pandemia thing is eating lots of energy and time.

I have now gone thru of your comments. Thanks for those.

I force pushed the changes and created a PR to have a clean start. Please do add future comments to the PRs itself.

I left NIL UUID there to emphase that they really are NIL UUID's for public login. This also leaves less possibility that unknown uuid is passed on.

Then comment about shash allocation. I was thinking it was better to only do once so there is no problem on finding the sha1 functionality but perhaps the overhead is not that bad so now it is within uuid_v5 implementation.

I have run tests in yocto+zcu102+qemu and also in buildroot+qemu_v8. Those unrelated tests are still failing on zcu102+qemu but on buildroot all tests pass..

Now about linux kernel PR. Shouldn't this go to upstream kernel instead?

Now how this would be handled with PKCS11 API I do not yet have view how that should be. I was thinking that perhaps in PKCS11 URI format that at least some HSMs seems to use could be one way. OP-TEE PKCS11 engine needs to somehow be aware what kind of login is being done and to capture group id's -- either in numeric form or in textual form and then perhaps translate that to numeric form.

I believe we also need to capture login method and client UUID when we are generating the secrets in TA so that they can be access checked when accessing the secrets later.

I do not see usage for PIN as such in our use cases.

**Comment by vesajaaskelainen** [comment]
About the `uid` and `gid` string generation for `Client UUID` in kernel... I was thinking that perhaps it is better to remove zero padding in there just in case we one day have 64 bit uid/gid or it might even be UUID. Originally I was thinking that it is better to have consistent memory usage but perhaps it is not so big deal in this case.

**Comment by vesajaaskelainen** [comment]
Updated Linux kernel patches by removing padding and also adjusted group handling code to be hopefully more namespace friendly.

Updated also optee-test and optee-client PRs.

**Comment by jforissier** [comment]
Have you created a PR in https://github.com/linaro-swg/linux? I can't find it.

**Comment by vesajaaskelainen** [comment]
> Have you created a PR in https://github.com/linaro-swg/linux? I can't find it.

Now done. I hope it was correct branch to make PR against?

**Comment by vesajaaskelainen** [comment]
I have changed `user` and `group` in UUIDv5 unction to `uid` and `gid` respectively according to the comments.

Here is updated schema:

```
For TEEC_LOGIN_USER:
uid=<uid>
For TEEC_LOGIN_GROUP:
gid=<gid>
For TEEC_LOGIN_APPLICATION:
app=<smack my label>
For TEEC_LOGIN_USER_APPLICATION:
uid=<uid>:app=<smack my label>
For TEEC_LOGIN_GROUP_APPLICATION:
gid=<gid>:app=<smack my label>
```

Rebased all PR's and also addressed received commits. Now it seems that xtest passes fully without any failures (seems rebase helped).
