### ISSUE TITLE
Questions about shared interrupt

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#3645]
Hi,  we met a shared interrupt with several different handlers. One of the handler must be handled in optee since it needs to access secure registers, for others we want to handle them in REE. How can we handle this? I think out below resolutions and can you give me some advice?
1. Set the interrupt as IRQ,  for the handler must be handled in optee,  call fast smc to access secure registers in opteeos in REE irq handler. Is it doable except for adding an extra command in fast smc?
2. Set the interrupt as FIQ,  for the cases want to be handled in REE,  can I call thread_rpc_cmd to switch to REE in shared interrupt handler? If it's possible, is the irq/fiq still unmasked after switching to REE? If so, maybe there's scheduling problem?

Looking forward to your replies.

**Comment by jenswi-linaro** [comment]
Option 2 will not work, option 1 is OK. It's a bit odd configuration, but if that's what you have to work with... Adding new commands in fast smc shouldn't be a problem as long as you don't try to take any mutexes or do RPC and so on.

**Comment by tiger20081015** [comment]
@jenswi-linaro， 
Could you give more details why option 2 can't work? I looked into the optee doc and it said when an IRQ occurred in opteeos, it will be forwarded to REE via SMC. Why I can't use thread_rpc_cmd in fiq interrupt handler to do the similar thing? Thanks.

**Comment by jenswi-linaro** [comment]
You can't do leave secure world for RPC from FIQ context.

**Comment by Raincode** [comment]
Hello,

I just had a spontaneous idea, but I'm not sure if it makes any sense for the use-case:

Handle the secure shared interrupt inside the secure world, clear it, and then use a separate software generated non-secure interrupt which is handled by the REE which basically treats this interrupt as if it was the original one?

Discussing IRQ/FIQ can be different depending on GICv2 or GICv3.

**Comment by etienne-lms** [comment]
Hi, I think it's the best solution for you use-case.

**Comment by tiger20081015** [comment]
@Raincode , thanks.  I think it's doable. 
@etienne-lms , for "the best solution for your use-case", do you mean @Raincode 's suggestion?

**Comment by etienne-lms** [comment]
Yes, I agree with comment https://github.com/OP-TEE/optee_os/issues/3645?email_token=AEYQOJQFECFDSQDRS7JTQ3LRG5RGVA5CNFSM4LABZEYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOO7DWA#issuecomment-594391276 from @Raincode.
Rephrased, I think secure OP-TEE native interrupt (fiq or irq) should be handler in secure Core which may rise a non-secure interrupt for the non-secure OS.

**Comment by tiger20081015** [comment]
thanks your guys, topic closed.

**Comment by tiger20081015** [comment]
@Raincode @etienne-lms @jenswi-linaro , 
I used itr_raise_pi to raise peripheral interrupt to non-secure world, but met below assert in gic_it_set_pending:
+       /* Assigned to group0 */
+       assert(!(read32(gd->gicd_base + GICD_IGROUPR(idx)) & mask));

It seems peripheral interrupt can only be set as secure interrupt? Do you happen to know why there's such limitation?

**Comment by tiger20081015** [comment]
BTW, the reason why I didn't use SGI is in linux interrupt handling, it seems doesn't support dynamic IPI allocation, someone has wrote a patch but it's not up streamed(https://github.com/Xilinx/linux-xlnx/commit/ed4fa7e4096b08850e0b9c319dc2f7e0e55e4599). So I wonder if raising SPI can resolve this issue.

**Comment by etienne-lms** [comment]
Regarding the assertion `/* Assigned to group0 */` mentioned above, i think it could be removed.
@jforissier, @jenswi-linaro, why can't secure world raise a non-secure SPI or PPI?

Using a SGI mandates changes in the arm gic in kernel. I don't know if it is easy to allocate an `irq` for each secure SGI and let platform register `irq` handler over. Likely touchy.
Otherwise, yes, should use a SPI.

**Comment by Raincode** [comment]
@tiger20081015  I wish I could help out, but I simply lack the embedded expertise... I invisioned that you can just implement a service routine and register it to handle the SGI within GNU/Linux. Since SGI (in my understanding) are meant for software components to communicate with each other, I assumed this would be fairly simple to accomplish (but I guess I was wrong)...

**Comment by jenswi-linaro** [comment]
Agree with @etienne-lms, the assert can probably be removed. However, a more clean solution would be to use SGI instead. The Linux kernel already uses the 8 which has been assigned to normal world. OP-TEE still uses none of the 8 assigned to normal world. We could donate at least one SGI to normal world which could be used for this purpose.

This will require changes at the Linux side too, hopefully it's not too hard to describe it in device tree. Another thing to keep in mind is that we might want to use this new SGI to signal other events too so if possible we should try to make it somewhat extendable or generic.

**Comment by tiger20081015** [comment]
@Raincode @etienne-lms thanks for your replies. 
@jenswi-linaro , so I guess no matter which solution we use, the /* Assigned to group0 */  code should be removed ? There seems no reason to add this limitation.

**Comment by etienne-lms** [comment]
@tiger20081015, feel free to create a P-R.

**Comment by tiger20081015** [comment]
@etienne-lms @jenswi-linaro , I made a pull request here: https://github.com/OP-TEE/optee_os/pull/3686. Please help to review. thanks.

**Comment by tiger20081015** [comment]
close the issue since patch has already merged. Thanks for your guys's suggestions!
