### ISSUE TITLE
[Question] Utilizing Downgrade Attack Protection for TAs

### ISSUE THREAD

**Issue by Raincode** [OP-TEE/optee_os#3651]
Hello,

I have a few short questions for clarification in reference to [this question](https://github.com/OP-TEE/optee_os/issues/2179):

1. Is my understanding correct that OP-TEE generally supports protection against downgrade attacks, if and only if the TA is installed via the respective PTA and uses the bootstrap TA header format which includes a version, and there must be a RPMB to reliably install TAs (at least for the `dirf.db` containing metadata including the version)? 

2. The install command looks for an already installed TA with the same uuid, if one is found, it ensures the version of the new TA to be installed is not lower than the installed version, i.e., rollback protection is done at the installation stage of TAs to secure storage? Or does OP-TEE OS check the version field before loading a TA, too?

3. Is the following configuration generally sufficient to demonstrate downgrade attack protection:

Compile optee-os with
`CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y CFG_SECSTOR_TA=y`
then use
`xtest --install-ta [...]`
to install the required TA to RPMB and delete the old copy inside the REE FS. optee-client is thereby running RPMB emulation.

The reason I am asking all these questions is I tried executing and/or installing a TA compiled with a lower `TA_VERSION` in `user_ta_header_defines.h`, and it was possible without any issues. Therefore, I am trying to find my error.

Thank you in advance!

**Comment by jforissier** [comment]
Hi @Raincode,

1. Yes
2. Both. The install command does check for downgrade ([here](https://github.com/OP-TEE/optee_os/blob/3.8.0/core/pta/secstor_ta_mgmt.c#L83-L84)), and OP-TEE also "remembers" the highest version it has run and prevents older versions from running ([here](https://github.com/OP-TEE/optee_os/blob/3.8.0/core/arch/arm/kernel/ree_fs_ta.c#L492)).
3. Yes, this configuration should be OK unless I'm missing something... not sure what went wrong during your tests. You could add debug traces in the installation and TA loading paths perhaps (the locations I mentioned above).

**Comment by Raincode** [comment]
Hi @jforissier,

thank you for clarifying this for me. I missed/was not yet aware of the check in `ree_fs_ta.c`. Upon inspecting the source code, it seems my older OP-TEE version does not include the version check when loading the TA. However, the installation PTA does already include the `check_install_conflict`.

I will verify my setup and try it again this afternoon... I am expecting an error when attempting to install an older version of a TA. But it may be possible that my issue is simpling not running a recent version of OP-TEE.
