### ISSUE TITLE
[Question] Get the remaining size of RPMB

### ISSUE THREAD

**Issue by RomainLaniece** [OP-TEE/optee_os#3652]
Hi,

I'm writing a TA to manage read and write into a RPMB (4MB).
I'm writing block of data inside (16KB), each new one is supposed to replace the previous one.
I currently did 3 "write", and reading the RPMB is always returning the last 16KB I wrote inside.
I tried to read the 2 previous blocks by using TEE_SeekObjectData, but it seems that I can only use this API to browse the last written block (my 3rd one).

My question is : how can I know the remaining size of the RPMB ? Or is there a way from the TA to retrieve the write counter of the RPMB ?

Thanks,
Best Regards,
Romain.

**Comment by jforissier** [comment]
Hello @RomainLaniece,

TAs use the TEE Internal Core API (the `TEE_*` functions), and it should not matter whether the secure storage is RPMB or something else. The exposed API is the same. There is a file system underneath, which may use the non-secure OS storage or RPMB or both (as described in https://optee.readthedocs.io/en/latest/architecture/secure_storage.html). Although, some limits may be different (RPMB partition size for instance).

Therefore:
1. You may want to reproduce your test case with different FS configurations (CFG_REE_FS=y CFG_RPMB_FS=n ; CFG_REE_FS=y CFG_RPMB_FS=y ; CFG_REE_FS=n CFG_RPMB_FS=y). It can help in case there is a bug in the implementation
2. You can't read the RPMB counter in the TA.

I suspect you are not using the API properly. Care to share some code?

**Comment by RomainLaniece** [comment]
Hi,

Thanks for your answer ^^
I understand we can't read any properties from the rpmb, no problem.
When you say that I may not use the API properly, it sounds that something in my first post seems to not be ok for you, may I know what it is ? Is my interpretation of the TEE_SeekObjectData() not right and it should work differently with the RPMB ?

Best Regards,
Romain

**Comment by jforissier** [comment]
> When you say that I may not use the API properly, it sounds that something in my first post seems to not be ok for you, may I know what it is ?

Not at all :wink:

> Is my interpretation of the TEE_SeekObjectData() not right and it should work differently with the RPMB ?

No, it should work as described in the spec :wink: whether or not RPMB is used.

**Comment by RomainLaniece** [comment]
Ok, thanks.
it seems you answered all of my questions :)
I close this ticket.
