### ISSUE TITLE
Creating a shared memory region between kernel address space and optee

### ISSUE THREAD

**Issue by divneil** [OP-TEE/optee_os#3658]
Hi,

I am looking to create a shared region of memory between kernel driver and optee_os.

After looking at the kernel code for creating shared memory in `drivers/tee/`, my understanding is that, we first create a `shm` structure based on `get_user_pages_fast()` and pass that to optee to create the mapping in TrustZone. So, userspace memory is shared across.

Do you have a reference to do that for kernel address space? 

Regards,
Divneil

**Comment by jenswi-linaro** [comment]
There's a driver at https://github.com/torvalds/linux/blob/master/drivers/char/hw_random/optee-rng.c which does that.

**Comment by divneil** [comment]
Thanks @jenswi-linaro. From a quick scan of the code, seems like I should close the ticket. :)
