### ISSUE TITLE
[Question] Clarification on TA Secure Communication / mbedTLS

### ISSUE THREAD

**Issue by Raincode** [OP-TEE/optee_os#3659]
Hello,

I once more am trying to wrap my around something, and figured I would quickly ask here before I dive into the source code (as a trade-off, I would consider writing some little parts of documentation on the subjects, in case this is desired):

OP-TEE OS includes the mbedTLS library. Furthermore, it implements the GlobalPlatform’s Socket API v1.0. Does this mean OP_TEE OS includes its own network stack? Or does it somehow send data to the normal world, where it is processed through the Linux stack?

Is my assumption correct, that OP-TEE OS + mbedTLS can be used to create a secure communication channel to external devices from within a TA, without the REE being able to disclose the data sent or undetectedly tamper with it?

**Comment by jforissier** [comment]
Hi @Raincode,


> OP-TEE OS includes the mbedTLS library. Furthermore, it implements the GlobalPlatform’s Socket API v1.0. Does this mean OP_TEE OS includes its own network stack? 

No.

> Or does it somehow send data to the normal world, where it is processed through the Linux stack?

Yes.

> Is my assumption correct, that OP-TEE OS + mbedTLS can be used to create a secure communication channel to external devices from within a TA, without the REE being able to disclose the data sent or undetectedly tamper with it?

Yes. And mbedTLS is irrelevant here -- the TA may use it or it may use the TEE Internal Core API crypto functions (which are implemented in the TEE core with LibTomCrypt by default or with mbedTLS if selected).

One thing to note: if I'm not mistaken, the GP Socket API only provides the TCP/UDP client side, not server.

**Comment by Raincode** [comment]
Hi @jforissier,

thank you for the quick reply.

I just read somewhere that the GP Socket API does not support TLS, but I wasn't aware one could enable mbedTLS as the back-end for this socket API.

>> Or does it somehow send data to the normal world, where it is processed through the Linux stack?
>
> Yes.

In that case, is the tee-supplicant again used to actually send the data via Linux, or is this directly handled by the OP-TEE driver? Once I have a rough architectural understanding, I will probably figure out the rest of the details on my own.

Thank you!

**Comment by jforissier** [comment]
> Hi @jforissier,
> 
> thank you for the quick reply.

np :)
 
> I just read somewhere that the GP Socket API does not support TLS, but I wasn't aware one could enable mbedTLS as the back-end for this socket API.

GP **does** support TLS, see GPD_SPE_103 "TEE Sockets API Specification Annex C: TLS
Specification of TEE Sockets API Specification". OP-TEE does not implement it however.

> In that case, is the tee-supplicant again used to actually send the data via Linux, 

Yes.

**Comment by Raincode** [comment]
Thanks for the clarification @jforissier.

If any implementation-specific questions remain, I will probably find the answers in recent sources.
