### ISSUE TITLE
gdb TA application in imx8 board

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3660]
Hi,

Can the TA application be debugged on the imx8m board? with gdbserver?
I try to load the tee.elf symbols into gdb but it doesn't recognize them. How can I do it?

Thanks

**Comment by jbech-linaro** [comment]
I've been trying to figure out this myself, but from my understanding it requires JTAG. NXP folks seems to use Lauterbach.

You cannot run a gdbserver for TA debugging on any device. gdbserver only works for non-secure side debugging.
