### ISSUE TITLE
ftrace TA panic

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3666]
Hi,

I try to run ftrace like this:
`make CFG_TA_MCOUNT = y CFLAGS_ta_arm64 = -pg run`

I have modified the file mk / config.mk:
`CFG_FTRACE_SUPPORT = y`.
But when I enable `CFG_ULIBS_MCOUNT =y `and `CFG_SYSCALL_FTRACE = y` the TA goes into a panic.

```
D/LD:  ldelf:169 ELF (8aaaf200-2450-11e4-abe2-0002a5d5c51b) at 0x40019000
F/TC:? 0 trace_syscall:127 syscall #6 (syscall_close_ta_session)
D/TC:? 0 tee_ta_close_session:499 csess 0xe1ab030 id 1
D/TC:? 0 tee_ta_close_session:518 Destroy session
D/TC:1 0 abort_handler:524 [abort] abort in User mode (TA will panic)
E/TC:? 0 
E/TC:? 0 User TA undef-abort at address 0x40019d58
E/TC:? 0  esr 0x6232f801  ttbr0 0x200000e1ba020   ttbr1 0x00000000   cidr 0x0
E/TC:? 0  cpu #1          cpsr 0x80000000
E/TC:? 0  x0  000000004003c5e0 x1  000000000e10a3b8
E/TC:? 0  x2  000000004003c5e0 x3  0000000000000000
E/TC:? 0  x4  000000000e10a3b8 x5  0000000040019378
E/TC:? 0  x6  0000000000000000 x7  000000000e1ab830
E/TC:? 0  x8  000000000e1ab834 x9  00000000000011e4
E/TC:? 0  x10 00000000000000ab x11 0000000000000000
E/TC:? 0  x12 0000000000000000 x13 000000004003df80
E/TC:? 0  x14 0000000000000000 x15 0000000000000000
E/TC:? 0  x16 000000000e11d85c x17 0000000000000000
E/TC:? 0  x18 0000000000000000 x19 0000000000000000
E/TC:? 0  x20 0000000000000000 x21 000000000e19c300
E/TC:? 0  x22 0000000000000700 x23 0000000000000000
E/TC:? 0  x24 0000000000000000 x25 0000000000000000
E/TC:? 0  x26 0000000000000000 x27 0000000000000000
E/TC:? 0  x28 0000000000000000 x29 000000004003def0
E/TC:? 0  x30 000000004001a0f0 elr 0000000040019d58
E/TC:? 0  sp_el0 000000004003dee0
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/TC:1 0 Dead canary at end of 'stack_abt[3]'
E/TC:1 0 Panic at core/arch/arm/kernel/thread.c:194 <thread_check_canaries>
E/TC:1 0 TEE load address @ 0xe100000
E/TC:1 0 Call stack:
E/TC:1 0  0x000000000e110404
```

What steps must I take? The optee version is 3.7

Thanks

**Comment by jforissier** [comment]
Hi @21212124,

`undef-abort` sounds like the TA is not allowed to access `CNTPCT` (ftrace uses it to record a timestamp).
Could be due to TF-A, there is an option to save timer state that needs to be enabled: `NS_TIMER_SWITCH`. See [here](https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/commit/?h=integration&id=43f999a7e35db5bdbb5af6dfc7efc46f6ecab443).

**Comment by 21212124** [comment]
@jforissier Now in the normal world this is running continuously:

> [ 2345.801670] rcu: INFO: rcu_preempt detected stalls on CPUs/tasks:
> [ 2345.807464] rcu:     1-...0: (0 ticks this GP) idle=966/1/0x4000000000000000 softirq=2288/2288 fqs=284809 
> [ 2345.815296] rcu:     (detected by 0, t=572434 jiffies, g=3545, q=38)
> [ 2345.821340] Task dump for CPU 1:
> [ 2345.826654] optee_example_h R  running task        0  1590   1588 0x0000000a
> [ 2345.838194] Call trace:
> [ 2345.838800]  __switch_to+0xb8/0x1a8
> [ 2345.839563]  0xffff800041661b80
> [ 2408.821572] rcu: INFO: rcu_preempt detected stalls on CPUs/tasks:
> [ 2408.825736] rcu:     1-...0: (0 ticks this GP) idle=966/1/0x4000000000000000 softirq=2288/2288 fqs=292642 
> [ 2408.833811] rcu:     (detected by 0, t=588189 jiffies, g=3545, q=39)
> [ 2408.835359] Task dump for CPU 1:
> [ 2408.846708] optee_example_h R  running task        0  1590   1588 0x0000000a
> [ 2408.852771] Call trace:
> [ 2408.853481]  __switch_to+0xb8/0x1a8
> [ 2408.854288]  0xffff800041661b80
> [ 2471.841170] rcu: INFO: rcu_preempt detected stalls on CPUs/tasks:
> [ 2471.845321] rcu:     1-...0: (0 ticks this GP) idle=966/1/0x4000000000000000 softirq=2288/2288 fqs=300458 
> [ 2471.852938] rcu:     (detected by 0, t=603944 jiffies, g=3545, q=40)
> [ 2471.862034] Task dump for CPU 1:
> [ 2471.862910] optee_example_h R  running task        0  1590   1588 0x0000000a
> [ 2471.872315] Call trace:
> [ 2471.872858]  __switch_to+0xb8/0x1a8
> [ 2471.873582]  0xffff800041661b80
