### ISSUE TITLE
Normal world general performance drop

### ISSUE THREAD

**Issue by RNNord2** [OP-TEE/optee_os#3670]
Hi. I'm running op-tee 3.7.0, U-boot 2019.07 and Linux 4.14.149 on i.MX6 SOLO and i.MX6 DualLite. The boot order is SPL -> optee-os -> U-boot -> Linux. 

After boot, I'm running a very simple performance test bzipping a large file. The time consumption of that task is up ~50% on the DualLite and ~100% on the SOLO when including optee-os, compared to just booting SPL -> U-boot -> Linux.

I have read #2288, but would need some more detailed information if that issue is related to the finding I'm describing here. 

The initial question is if the observed performance drop of the bzip2 operations is expected or if it indicates something is wrongly configured.

**Comment by RNNord2** [comment]
The Linux kernel needed a patch to unlock the caches. Closing.

**Comment by Emantor** [comment]
@RNNord2 Do you have a link to the patch?

**Comment by RNNord2** [comment]
@Emantor 
https://source.codeaurora.org/external/imx/linux-imx/commit/?h=imx_4.14.98_2.3.0&id=d6f6f7e13e62065ac1a9543eb0e675c565576c98
https://source.codeaurora.org/external/imx/linux-imx/commit/?h=imx_4.14.98_2.3.0&id=46a30aca7f5cbbb7f3f952634c7ebcb63014d520
https://source.codeaurora.org/external/imx/linux-imx/commit/?h=imx_4.14.98_2.3.0&id=b57eebc86bfe383c3bb80c21faba8b9e605e2f9e

**Comment by Emantor** [comment]
Thanks!
