### ISSUE TITLE
Aarch64: how to preserve TPIDR_EL0?

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3679]
Hi,

I am trying to introduce some C++ support for TAs, and for that I would like to keep the usual toolchains: `arm-linux-gnueabihf-` and `aarch64-linux-gnu-`. I'm almost there, but not quite :wink:

In a nutshell, the toolchain assumes a Linux environment with some support for thread-related features (because it is *not* built with `--disable-threads`). I chose to proceed with this thread-enabled toolchain because it does not seem to be too hard to support, and it would be a preparatory step for multi-threaded TAs later (MT TAs have been mentioned/requested a couple of time).

The problem I'm facing is I need to preserve the TPIDR_EL0 register when entering/leaving a TA. Where should I do this? `thread_enter_user_mode()` and `set_ctx_regs()` seem to be the right place to restore the register, but where should I save it?

Thanks!

**Comment by jenswi-linaro** [comment]
Yes, you can initialize it in `thread_enter_user_mode()` and `set_ctx_regs()`, but it needs to be preserved when the thread is suspended too. For instance during RPC.

So before `thread_state_suspend()` is called something is needed to save TPIDR_EL0. You should probably save and restore TPIDR_EL0 in `el0_svc()` too. You should probably try to manage it together with sp_el0.

**Comment by jforissier** [comment]
Thanks, I got it working now :+1:
