### ISSUE TITLE
InvokeCommand() 0xffff000c out of memory from libuteec

### ISSUE THREAD

**Issue by liurenju** [OP-TEE/optee_os#3685]
Hi,

I encountered an extremely interesting bug. I wrote a static TA, and I also wrote a normal world application. When the first time the normal world application calls into the static TA, everything works fine and properly and exits successfully.

However, if I re-execute the normal world program, a failure raises in InvokeCommand() with error 0xffff000c (out of memory) and origin 0x1 (i.e. libutee). I further dig into the details, it seems that it fails with res = TEEC_AllocateSharedMemory(ctx, shm) because shm_fd = ioctl(fd, TEE_IOC_SHM_REGISTER, &data); fails. 

Do you guys have any ideas where I can fix the problem? One of guess is that the shared buffer is too large (100 Kb), but the program has no complaints when it is executed the first time since OS boots. Thanks for the help.

I'm using hikey960.

**Comment by liurenju** [comment]
Does anyone have an idea on this?

**Comment by jforissier** [comment]
Hi @liurenju,

> One of guess is that the shared buffer is too large (100 Kb)

Well, instead of guessing you could perhaps use a debugger or add debug traces to figure out what's happening?
