### ISSUE TITLE
Keeping state data between commands in one session

### ISSUE THREAD

**Issue by GlovePuppet** [OP-TEE/optee_os#3691]
In my application I want the same TA to serve multiple normal world applications, each with their own session. Each application will issue several commands to the TA during a session, I want the TA to hold on to some state information between commands.

The state data should be private to a session and not accessible by the normal world application. How to do this?

**Comment by jforissier** [comment]
You can allocate session data on the heap (`malloc()`) and use the `void *` parameter of `TA_OpenSessionEntryPoint()` and `TA_CloseSessionEntryPoint()`.
