### ISSUE TITLE
Testing Trusted Applications regarding Memory Leaks

### ISSUE THREAD

**Issue by sto-vec** [OP-TEE/optee_os#3694]
Hello OP-TEE Team, 
I am currently working on a dynamic trusted application and everything works as expected. Thank you for the good manual!
Recently I start thinking about testing my trusted application and some questions came up. I build the qemu environment as described and i use this setup for testing the whole system (host application and trusted application together). 
But how is it possible to test the trusted application regarding memory leaks? Normally, I use valgrind for this. How can i use valgrind (or any other memory testing tool) on a trusted application inside the secure world? What is your approach testing trusted applications?
Thanks.

**Comment by jbech-linaro** [comment]
> How can i use valgrind (or any other memory testing tool) on a trusted application inside the secure world? What is your approach testing trusted applications?

Simple answer is you can't or at least we have no known ways how to do it. I agree that It'd be great to have something like Valgrind for testing TA's.

**Comment by sto-vec** [comment]
Thank you for the fast response. 
For unit tests of the TA i start mocking the internal TEE API with cmocka. Maybe I can build something with the mocked TEE API and valgrind. 
It won't be as good as a direct valgrind test but maybe close enough to have a better feeling...

**Comment by jenswi-linaro** [comment]
For OP-TEE Core I'm sometimes compiling with `CFG_TEE_CORE_MALLOC_DEBUG=y` and adds a `mdbg_check(1);` at some strategic place.

For a TA that would be `CFG_TEE_TA_MALLOC_DEBUG=y`, I think you'll need to recompile the TA dev-kit. Then you could add a `mdbg_check(1)` when returning from an invoke or something. If you take the list of print and compare that with earlier invokes you should be able to tell if there's a leak. Also just going through the list might give clues.

**Comment by sto-vec** [comment]
Thanks. That is a good idea. I haven't thought about malloc debug yet. Worth a closer look i guess.
