### ISSUE TITLE
Question about Secure Device Trees

### ISSUE THREAD

**Issue by javieralso-arm** [OP-TEE/optee_os#3696]
Hi all,

As can be read on [Secure and Non-Secure Device Trees](https://optee.readthedocs.io/en/latest/architecture/device_tree.html#secure-and-non-secure-device-trees) section in OP-TEE documentation:

> Boot loader stages may load a device tree structure in secure memory for the benefit of the secure world only. Such device tree blob shall be located in secure memory. Secure world could use its content but **this is currently not implemented in the latest OP-TEE release.**

Is there any plan to implement this anytime soon?

Thank you very much.

Best regards,
Javier

**Comment by jbech-linaro** [comment]
> Is there any plan to implement this anytime soon?

Not really, but Linaro together with Linaro members are running various Device Tree work/improvements. It might be worth bringing it up in that context.

**Comment by javieralso-arm** [comment]
Thanks @jbech-linaro . I'm closing this.

Regards,
Javier
