### ISSUE TITLE
Upgrade Mbed TLS

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3699]
The version of Mbed TLS used in OP-TEE is based off version 2.16.0 released on December 24, 2018. Several bugfix releases have been pushed since, latest being 2.16.5 (released on February 25, 2020). It is time to upgrade.

**Comment by jforissier** [comment]
Wondering if we should upgrade to:
1. 2.16.5 (latest bugfix release on the branch we're using already)
2. 2.21.0 (latest release without a "weird" name)
3. 2.22.0d0 (looks like this one is the beginning of a new feature branch and perhaps not deemed stable yet?)

I am leaning towards (2.).

**Comment by jbech-linaro** [comment]
No strong opinion, "2" sounds good, at least we're going in the right direction.

Speaking about upgrades, quite a few git's we are using have become rather old.
Buildroot: Feb 2019
QEMU: Nov 2018
U-Boot: July 2018
EDK2: July 2018

So, if someone have some time leftover, upgrading those to something more recent would be a useful exercise.

**Comment by jforissier** [comment]
> No strong opinion, "2" sounds good, at least we're going in the right direction.

:+1: I'll do "2" then.

> Speaking about upgrades, quite a few git's we are using have become rather old.
> Buildroot: Feb 2019
> QEMU: Nov 2018
> U-Boot: July 2018
> EDK2: July 2018
>
> So, if someone have some time leftover, upgrading those to something more recent would be a useful exercise.

Yep. Quick comment regarding a Buildroot upgrade: I gave it a quick try as I wanted to try GCC 9.2 (our Buildroot does not support >8.x). I met a conflict with the BR2_OPTEE_CLIENT package which is now upstream, so perhaps we need to rename our local package. Nothing too complex I suppose.

**Comment by jbech-linaro** [comment]
Regarding BR: This https://github.com/OP-TEE/build/pull/374 is probably a good start.

**Comment by jforissier** [comment]
While rebasing our `lib/libmbedtls/mbedtls` onto upstream version 2.21.0, I noticed something  annoying. Compared to 2.16.0, they (Arm) moved the crypto code to a submodule: `mbedtls/crypto`. It [happened in 2.19.0](https://github.com/ARMmbed/mbedtls/blob/5e7d6fd/ChangeLog#L284-L286). But then [they changed their mind](https://github.com/ARMmbed/mbedtls/blob/5e7d6fd/ChangeLog#L14-L15).
Therefore I don't think it is a good idea to rebase onto 2.21.0.

I propose to use 2.18.1 (July 2019) instead, until a new release is available with the new-old layout.

**Comment by jforissier** [comment]
Quite a bit of confusion here, sorry about that, anyways the truth is this separate Mbed Crypto thing is indeed a thing of the past: https://github.com/ARMmbed/mbedtls/issues/3064.

**Comment by jbech-linaro** [comment]
> Mbed Crypto thing is indeed a thing of the past

Yes, we got an update in a TrustedFirmware meeting and this was an idea that didn't turn out well, so the decision was to go back how it used to be. FYI, there is now a read-only mirror here https://git.trustedfirmware.org/tls/mbed-tls.git/ which at some point in the future will become the official tree and when that happens the GitHub MbedTLS will become a read only mirror. However, we're not there yet.
