### ISSUE TITLE
TEE device files

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#3702]
What is the difference between /dev/optee_armtz and /dev/tee[0-9]?
Currently, i understand that the user space applications should talk to /dev/tee[0-9] so as to access the TEE sub-system?

Where does /dev/optee_armtz come into picture here?

**Comment by jforissier** [comment]
> What is the difference between /dev/optee_armtz 

Where do you see such a device?

**Comment by gagachang** [comment]
There are two tee drivers in my QEMU and rpi3 platforms : `/dev/tee0` and `/dev/teepriv0`.
I have read an article depicts that `/dev/tee0` is used for the normal world client applications,
and `/dev/teepriv0` is used for RPCs from the secure world and tee-supplicant in the normal world.

Is that right?

**Comment by saddy-muchu** [comment]
> 
> 
> > What is the difference between /dev/optee_armtz
> 
> Where do you see such a device?

Maybe i got confused.
So, if i'm not wrong, there are only two possible interfaces to the tee device namely /dev/tee[0-9] and /dev/teepriv[0-9].

is that right?

**Comment by jforissier** [comment]
@saddy-muchu yes. `/dev/tee[0-9]` is for clients (CA), `/dev/teepriv[0-9]` is for `tee-supplicant`.

**Comment by saddy-muchu** [comment]
> 
> 
> @saddy-muchu yes. `/dev/tee[0-9]` is for clients (CA), `/dev/teepriv[0-9]` is for `tee-supplicant`.

OK.
Thanks a lot
