### ISSUE TITLE
Running Python on normal and secure worlds

### ISSUE THREAD

**Issue by mmicu** [OP-TEE/optee_os#3708]
Hi! I do not have so much experience with op-tee, but I was able to run the examples by using QEMU. I'd like to move my Python application into the secure world, but I saw that it could be very tricky. For this reason, I was thinking about [pure embedding](https://docs.python.org/2/extending/embedding.html#pure-embedding).

I see that a TA application application must be written in C, however I cannot translate the entire Python application in C. Considering that I am using QEMU, how can I install the Python libraries and header files in both normal and secure worlds?

Thanks for your help.

**Comment by jbech-linaro** [comment]
@mmicu , sorry, that's a dead end. It's C that is the language (soon [C++](https://github.com/OP-TEE/optee_os/pull/3693) and some folks have been able to use [Rust](https://connect.linaro.org/resources/san19/san19-513/)).

**Comment by mmicu** [comment]
Thanks for your reply, @jbech-linaro. Why is it a dead end in your opinion? Once you produce the shared library, you could use it as an additional dependency.

Unfortunately, it's a Python REST service with several dependencies, and it would be very difficult to translate it into C.

**Comment by jbech-linaro** [comment]
> Why is it a dead end in your opinion?

Ok, it's software we're talking about, so in theory it's all doable. But, there is no such support as of today, there are no plans of doing something like that. So, that means that you'll have to spend all needed time to get this sorted on your own. Maintainers etc can of course help reviewing code and be part of other related discussions. So, if you have the time and will to invest in that, by all means, feel free to do so and then in the end you submit it as a "request for comment".

The downside with introducing some kind of "Python" support in secure side is that you also increase the attack surface, so that is something to consider as part of doing that.

**Comment by mmicu** [comment]
Thanks for your suggestions. However, from a more general point of view, how can I add new dependencies to the system (e.g. Python, curl, etc.). Where should I start? Is there any kind of documentation?

**Comment by jbech-linaro** [comment]
> Thanks for your suggestions. However, from a more general point of view, how can I add new dependencies to the system (e.g. Python, curl, etc.). Where should I start? Is there any kind of documentation?

When it comes to importing standard C stuff, we've been taking it from newlib for example and we've put that [here](https://github.com/OP-TEE/optee_os/tree/master/lib/libutils/isoc/newlib) for example. When we've imported other libraries, like mbedTLS, we've put that [here](https://github.com/OP-TEE/optee_os/tree/master/lib/libmbedtls). LibFTD on the other hand ended up [here](https://github.com/OP-TEE/optee_os/tree/master/core/lib/libfdt).

There are no instructions, but I'd start looking at the above ones and then probably try to put whatever code (pay attention to license!) you want to import and add that probably to `optee_os/lib/...`. After that I guess it's about updating all makefiles, so you actually can build and use the library/code that you've imported.

**Comment by TephrocactusMYC** [comment]
Hi, is anyone still considering porting Python to OP-TEE? 

I have some ideas that might allow basic Python scripts to run in OP-TEE (of course, they should be at a toy level). If anyone is still considering this, I will start working on it soon. Anyone interested in this is welcome to reach out to me.

However, as @jbech-linaro have mentioned, this could lead to security issues (possibly very serious), so such development may not be practically meaningful.
