### ISSUE TITLE
Key-length for ECC Curves in OP-TEE

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#3709]
OP-TEE supports various ECC Curves.
TEE_ECC_CURVE_NIST_P192 is one of the curve.
The TEE Internal Core API 1.2.1 version specification mentions that:
"For all elliptic curve elements, the size parameter represents the length, in bits, of the base field"

How do i interpret the above statement for the above curve? 
What does base-field mean?

**Comment by jforissier** [comment]
Hi @saddy-muchu,

If I'm not mistaken, it is the size in bits of the prime number that serves as a base for the field. In other words, `TEE_ECC_CURVE_NIST_P192` describe ECC in a field Fp with p being a 192-bit prime number defined by the NIST.

**Comment by saddy-muchu** [comment]
> 
> 
> Hi @saddy-muchu,
> 
> If I'm not mistaken, it is the size in bits of the prime number that serves as a base for the field. In other words, `TEE_ECC_CURVE_NIST_P192` describe ECC in a field Fp with p being a 192-bit prime number defined by the NIST.

So, does this mean 192 bits is the key length?

**Comment by jforissier** [comment]
> > Hi @saddy-muchu,
> > If I'm not mistaken, it is the size in bits of the prime number that serves as a base for the field. In other words, `TEE_ECC_CURVE_NIST_P192` describe ECC in a field Fp with p being a 192-bit prime number defined by the NIST.
> 
> So, does this mean 192 bits is the key length?

Short answer: yes.

https://security.stackexchange.com/a/60932

**Comment by saddy-muchu** [comment]
> 
> 
> > > Hi @saddy-muchu,
> > > If I'm not mistaken, it is the size in bits of the prime number that serves as a base for the field. In other words, `TEE_ECC_CURVE_NIST_P192` describe ECC in a field Fp with p being a 192-bit prime number defined by the NIST.
> > 
> > 
> > So, does this mean 192 bits is the key length?
> 
> Short answer: yes.
> 
> https://security.stackexchange.com/a/60932

This article explained it all.
Thanks a lot.
