### ISSUE TITLE
ldelf crash when load TA with .rel.text not empty

### ISSUE THREAD

**Issue by Kztpia** [OP-TEE/optee_os#3711]
hi,
    I'm trying to migrate some TA  to 3.7. But ldelf crashes with "write permission fault" when loading new TA.
    I found the reason why ldelf crash and a work around. try to find a better solution here.

# Why ldelf crashed:

My TA have a none empty .rel.text segment. so ldelf trys to modify .text as .rel.text required when loading the TA. But .text is read-only and ldelf just mapped this segment without write permission. So ldelf ends up trying to modifying non-writable .text and crashs with "write permission fault"

# Work around for now:

Modify TA head and .ld.s, makes it looks like a "legacy TA" that ldelf will always copy, not map, every segments. Then ldelf can modify .text segments without a "write permission fault".

# A simple way to reproduce this failure:

-  In any TA, add 
```
user-ta-adldd+=$(path-to)/crtbegin.o
```
in sub.mk. 
-  readelf -a ${compiled-TA} should contains .rel.text segment witch have relocation info about symbol in .text. And ldelf will crash  with "write permission fault" when loading this TA.
-  I only tested crtbegin.o from gcc-arm-none-eabi-5_4-2016q3 to reproduce this failure, but i think one from other version should also be able to reproduce this failure.

**Comment by jforissier** [comment]
Hi @Kztpia 

As you said, `crtbegin.o` contains text relocations (TEXTREL) because it is not built with the "position independent" switch (`-fPIC`). `ldelf` expects position independent code.

Can you try `crtbeginS.o` instead?

**Comment by Kztpia** [comment]
hi @jforissier 
crtbeginS.o is not available in my current toolchain.  Switching to other toolchain come with dozens of compile issues, mostly some low level cpp symbol not defined. building TA with cpp sources is another problem, there are already issues discussing about it and patches working on this, i will try to walk through those first.

Let's come back  to this panic.
So OPTEE is not supposed to load and run a non-position independent TA (as lease at 3.7.0),  therefore the recommended solution for this panic is to clear out all (TEXTREL) in TA ?

**Comment by jenswi-linaro** [comment]
OP-TEE has never supported anything by position independent TAs, but it has probably worked until we started with ldelf. The reason it doesn't work with ldelf is that TA code pages are shared between TAs so they cannot be updated. It would be possible to update ldelf to avoid this restriction, but it might be more trouble that what it's worth. I recommend compiling everything position independent to avoid relocations in code pages.

**Comment by jforissier** [comment]
@Kztpia 
> building TA with cpp sources is another problem, there are already issues discussing about it and patches working on this, i will try to walk through those first.

If you are referring to https://github.com/OP-TEE/optee_os/pull/3693, then please do not hesitate to try it and give your feedback, it definitely needs more testing!
In that PR, you will notice that I have not added `crtbegin.o` to the link command, which is probably incorrect (my test cases were working without it).

**Comment by Kztpia** [comment]
I will try to avoid relocations in code pages. Thanks for the help.

@jforissier Working on somethings else now, gonna try  #3693 later, thanks!
