### ISSUE TITLE
communicate  between pta 

### ISSUE THREAD

**Issue by icesigma** [OP-TEE/optee_os#3712]
Hi,
I am trying to let pTA1 invoke pTA2 but I got some trouble. 
First of all, I follow pta example to program pTA1 code.I got the message like the folloing:
```
 undefined reference to `TEE_OpenTASession'
 undefined reference to `TEE_InvokeTACommand'
 undefined reference to `TEE_CloseTASession'
```
Although I included tee_api.h in pTA1 but I realized something about pTA communication.
I read some information from internet. The pTA seems can not use tee_api. Am I right?
If it's true, I don't know how to achieve this idea.
Could someone guide me how to do this or any suggestion?

**Comment by jforissier** [comment]
Hi @icesigma,

> The pTA seems can not use tee_api. Am I right?

Correct. In your case, pTA1 and pTA2 already share the same memory space (the TEE core), so you can call pTA2 directly.

**Comment by jenswi-linaro** [comment]
Keep synchronization in mind if accessing shared data.

**Comment by icesigma** [comment]
Hi @jforissier 
     Thank you so much for the speedy reply. 

Here, I have a question. If I pTA2 is not ready, does pTA1 have any means to trigger  pTA2  installation to memory ?

Hi @jbech-linaro 
       Thanks for your friendly reminder. I'll keep it in mind.

**Comment by jforissier** [comment]
> Here, I have a question. If I pTA2 is not ready, does pTA1 have any means to trigger pTA2 installation to memory ?

A pseudo-TA is linked with the TEE core so it is not "installed to memory", it is loaded at the same time the TEE binary is loaded. It is similar to any other part of the TEE kernel, such as a driver for instance. So "pTA2 is not ready" cannot happen.

**Comment by etienne-lms** [comment]
My 2 cents: consider a PTA as a TEE Core services exposed through a GPD TA like API (open/close session, invoke command). That is the only common things between a TA and a PTA.

**Comment by icesigma** [comment]
Hi @jforissier 
> A pseudo-TA is linked with the TEE core so it is not "installed to memory", it is loaded at the same time the TEE binary is loaded. It is similar to any other part of the TEE kernel, such as a driver for instance. So "pTA2 is not ready" cannot happen.

Thank you so much for your clear and unambiguous explanations on my question . They have helped me tremendously. 

Hi @etienne-lms 
>My 2 cents: consider a PTA as a TEE Core services exposed through a GPD TA like API (open/close session, invoke command). That is the only common things between a TA and a PTA.

I probably understand what you mean. 

Hi Both
Lastly, I confirm what I got on this discussion.
A pseudo-TA could be considered as a Tee kernel service.
Thus, they can communicate to each other directly.
And then pTA is not like TA to be executed on user space 
so it does not use the tee_api (through syscall procedure).
Am I right?

**Comment by jforissier** [comment]
@icesigma totally right, yes :+1:

**Comment by icesigma** [comment]
> @icesigma totally right, yes 👍

Hi @jforissier 
    Thank you so much. Let me deeply understand pta how it works. I'll close this issue tomorrow or administrator can help me close it too.  

Hi everyone 
Thank you all for your participation
