### ISSUE TITLE
i2c driver in optee freezes 

### ISSUE THREAD

**Issue by alekarasma** [OP-TEE/optee_os#3723]
Hello Everyone,

I have ported imx-i2c driver from Linux to Optee. Once the driver is called to start communication. First, it tries to read I2C->IFDR (Fractional divider) and the kernel freezes. Nothing can be done after that.

Is there any configuration I need to do, to make I2C driver work in Optee.
My Linux kernel rev is: 4.19.35-00021-g9a6e1ef226ac-dirty
Optee rev: 3.8

To debug more I adder small function in the i2c-driver in Optee and call it through driver_init initcall. It perfectly read the values as shown. I think this is because the kernel is not up yet.
![image](https://user-images.githubusercontent.com/42671939/78323898-01587880-75bf-11ea-8369-00cb364a1beb.png)

But if same is done through TA it calls the PTA which calls the i2c driver, the driver tries to read the register value of I2C->IFDR and freezes there, nothing cant be done further.
![image](https://user-images.githubusercontent.com/42671939/78324329-1f72a880-75c0-11ea-898f-910ee22da0dd.png)

Can you please provide any pointers to configure driver correctly in Optee, or I have to do any changes in device tree?

Looking forward to your reply?

Regards,
Asma

**Comment by Emantor** [comment]
I2C-imx implements runtime resume and suspend by disabling the clocks and re-enabling them if I2C is needed. IMO this is not the correct way to implement I2C via OP-TEE. It might be a lot easier to write a PTA and small kernel driver which connects the OP-TEE kernel interface with the I2C driver infrastructure and let the kernel handle the communication, at least for devices which support authenticated communication. This way you won't run into runtime clock issues.

**Comment by alekarasma** [comment]
@Emantor 

I am not sure if I understand your answer properly. What do you mean by 

> write a PTA and small kernel driver which connects the OP-TEE kernel interface with the I2C driver infrastructure and let the kernel handle the communication.

I have already written PTA and I2C driver in Optee. PTA called I2C driver to initialize, in which case it starts by reading by IFDR (Fractional divider )register and freezes.

I am not sure what do further about it?
Do we have any example or snippet, that I can follow?

Regards,
Asma

**Comment by Emantor** [comment]
I don't have any example, just an idea. Instead of using the I2C directly, hand off the communication to the kernel and let it send the I2C messages. This way you don't need to implement i2c within OP-TEE and solve the runtime pm problem at the same time. Of course this requires some kind of authenticated channel between OP-TEE and your I2C device.

**Comment by jforissier** [comment]
@alekarasma We do something similar to what @Emantor is proposing for RPMB, perhaps you can give a look. When OP-TEE needs to access the device it delegates to normal world. There is no RPMB driver in secure world, which solves the device sharing problem. OP-TEE requests are sent to NW via what we call the "RPC" mechanism. In this case, and for various reasons, read and write requests are sent to user space (`tee-supplicant`) via the OP-TEE driver, which then uses the RPMB block device (`/dev/mmc*`). But perhaps for i2c there is no need to involve `tee-supplicant` and the RPC can be handled by the OP-TEE linux driver itself.

**Comment by alekarasma** [comment]
@Emantor You were correct i2c runtime suspend for power management was causing i2c to freeze.
If I remove it, it works perfectly fine.

Thank you.

**Comment by ldts** [comment]
um, I have also just ported the driver (took the one from u-boot instead). Since op-tee controls the iomux and clocks in the driver (the driver runs before u-boot and linux) I am not affected by runtime PM..at least not yet, might have some bugs still. I am running on imx8mm trying to control a secure element in an i2c bus (pretty standard thing)

**Comment by DevendraDevadiga** [comment]
> @Emantor You were correct i2c runtime suspend for power management was causing i2c to freeze.
> If I remove it, it works perfectly fine.
> 
> Thank you.

Dear Ashma,
 Please can you share the changes you have done for fixing hang issue when try to read/write I2C Frequency Divider Register ?
I am also facing the same issue as you faced.
Thanks and Regards,
Devendra
