### ISSUE TITLE
Bigint and bignum

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#3724]
What is the difference between bigint and bignum in OP-TEE?
I see that the TEE attributes(say TEE_ATTR_ECC_PUBLIC_VALUE_X)  are bignum's.
 In OP-TEE, what do bigint's store?

**Comment by jforissier** [comment]
Hi @saddy-muchu ,

They are mostly the same.
- `TEE_BigInt` is the GP API type used to represent storage space for big integers. See the GP TEE Internal Core API (v1.2.1 section 8.3.1).
- The internal representation used by OP-TEE is `mbedtls_mpi` (the typed defined by the Mbed TLS library)
- `struct bignum *` is an opaque type used in the OP-TEE core.

```
(struct bignum *) -> [n * TEE_BigInt]
                      ^^^^^^^^^^^^^^
                        mbedtls_mpi
```

**Comment by saddy-muchu** [comment]
> 
> 
> Hi @saddy-muchu ,
> 
> They are mostly the same.
> 
>     * `TEE_BigInt` is the GP API type used to represent storage space for big integers. See the GP TEE Internal Core API (v1.2.1 section 8.3.1).
> 
>     * The internal representation used by OP-TEE is `mbedtls_mpi` (the typed defined by the Mbed TLS library)
> 
>     * `struct bignum *` is an opaque type used in the OP-TEE core.
> 
> 
> ```
> (struct bignum *) -> [n * TEE_BigInt]
>                       ^^^^^^^^^^^^^^
>                         mbedtls_mpi
> ```

Thank you for the information.
