### ISSUE TITLE
PKCS11 Support

### ISSUE THREAD

**Issue by sto-vec** [OP-TEE/optee_os#3727]
Hello OP-TEE Team,
i noticed that currently a lot of work is ongoing on the pkcs11 implementation. Since i am interested in this feature i had a closer look on it.  
I managed to load the libckteec with the openssl engine using the libp11 from OpenSC. But as soon as I try to generate a RSA key with the openssl engine support the TA panics. 
Further investigations brought up that I need to initialize the pkcs11. How is the TA initialized using the pkcs11 interface? Also i could not find the implementation for the key generation. What is the current status for key generation and signing (RSA and ED25519)?
Thank you. 
Best regards
Tobias

**Comment by Emantor** [comment]
Which version of the implementation are you using? Current master does not yet support enough of the PKCS11 API to contain keys. Also please post the TA panic if on master. For a more complete implementation you'll want to look at @etienne-lms OP-TEE repository, specifically https://github.com/etienne-lms/optee_os/pull/21. Note that you'll also need his OP-TEE client implementation.

**Comment by sto-vec** [comment]
Thanks.
Yes i am using the current master. The error code in the TA is:
`
E/TA:  assertion 'id >= 0 && id < TOKEN_COUNT' failed at ta/pkcs11/src/pkcs11_token.c:59 in get_token_id()
E/TC:? 0 
E/TC:? 0 TA panicked with code 0xffff0000
E/LD:  Status of TA fd02c9da-306c-48c7-a49c-bbd827ae86ee
E/LD:   arch: arm
`
As I wrote it seems the PKCS11 is not initialized at all. 
I will have a look on the repository. @etienne-lms Is this all coming into the OP-TEE master?

**Comment by etienne-lms** [comment]
Hi @sto-vec. 

> As I wrote it seems the PKCS11 is not initialized at all.

Indeed, as @Emantor pointed out, current implementation of pkcs11 TA in OP-TEE/optee_os does not offer any useful service yet...

> @etienne-lms Is this all coming into the OP-TEE master?

Let's say we plan to propose a TA providing PKCS#11 services within the OP-TEE project and that we have a work base in [1]/[2]/[3] for that purpose. They are quite a lot a code to review and cleanup to get this TA more mature.

If you want to contribute, feel free to either help on next coming PKCS#11 related P-Rs  in OP-TEE/optee_os.
You can also  contribute by creating P-Rs on [1]/[2]/[3] for enhancing this work base.

[1] https://github.com/etienne-lms/optee_os/tree/sks-to-pkcs11
[2] https://github.com/etienne-lms/optee_client/tree/sks-to-pkcs11
[3] https://github.com/etienne-lms/optee_test/tree/upgrade-for-pkcs11

**Comment by sto-vec** [comment]
Hi @etienne-lms 
thanks for the links and information. 
I am running your code in the qemu setup. Also I build a suitable openssl engine pkcs11. The libckteec.so is also loaded correctly. Unfortunately, when I try to generate a RSA key the engine is not used at all. 
Here is what I have been trying so far:
`OpenSSL> engine dynamic -pre SO_PATH:/usr/lib/engines-1.1/pkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/usr/lib/engines-1.1/libckteec.so.0.1.0`
`(dynamic) Dynamic engine loading support`
`[Success]: SO_PATH:/usr/lib/engines-1.1/pkcs11.so`
`[Success]: ID:pkcs11`
`[Success]: LIST_ADD:1`
`[Success]: LOAD`
`[Success]: MODULE_PATH:/usr/lib/engines-1.1/libckteec.so.0.1.0`
`Loaded: (pkcs11) pkcs11 engine`
`OpenSSL> genrsa -engine pkcs11 -out priv_key.pem 2048`
`engine "pkcs11" set.`
`Generating RSA private key, 2048 bit long modulus (2 primes)`
On the secure side the relevant TA is not loaded at all. Do you have any further idea?
Thank you.

**Comment by etienne-lms** [comment]
Hi @sto-vec, sorry i forgot to answer you.
I did not try to use **openssl** straight with the pkcs11 TA. I run some tests using `pkcs11-tool` and **openssh** tools (thanks @Emantor), like:
```bash
$ pkcs11-tool --module /usr/lib/libckteec.so --init-token --label testtoken --so-pin 12341234
$ pkcs11-tool --module /usr/lib/libckteec.so --label testtoken --login --so-pin 12341234 --init-pin --pin 12341234
$ pkcs11-tool --module /usr/lib/libckteec.so --label testtoken --login --pin 12341234 --keypairgen --label testkey --key-type rsa:2048
```
and
```bash
$ ssh-keygen -D /usr/lib/libckteec.so -e > my-device-authorized_keys
$ ssh-agent /bin/sh && ssh-add -s /usr/lib/libckteec.so
```

**Comment by sto-vec** [comment]
Hi @etienne-lms thank you. I will close the issue.
