### ISSUE TITLE
How can I enable CAAM for Nitrogen6q Sabrelite?

### ISSUE THREAD

**Issue by ChangMinPark** [OP-TEE/optee_os#3734]
Hi, 

I'm trying to enable CAAM on Nitrogen6q-sabrelite board.
On the board, I'm currently running AOSP, Linux kernel, and OPTEE OS. 

According to the commit (https://github.com/OP-TEE/optee_os/commit/97c7050cc266c3cac8b4f00f801a820a257fde47), it seems that CAAM support for Nitrogen6q-sabrelite is currently not available. PLATFORM config name for the board is **_imx-mx6qsabrelite_**, and it's not there on the list. Even on the build configuration (.../plat-imx/conf.mk), CAAM is currently disabled.

1. Is there anyone who already enabled CAAM module on Nitrogen6q sabrelite?
2. To enable the CAAM module by myself, what will be the steps that I need to go through?
3. Will there be any modification needed in Linux kernel?

Thank you!

**Comment by Emantor** [comment]
Hello,

> I'm trying to enable CAAM on Nitrogen6q-sabrelite board.
> On the board, I'm currently running AOSP, Linux kernel, and OPTEE OS.
> 
> According to the commit ([97c7050](https://github.com/OP-TEE/optee_os/commit/97c7050cc266c3cac8b4f00f801a820a257fde47)), it seems that CAAM support for Nitrogen6q-sabrelite is currently not available. PLATFORM config name for the board is **_imx-mx6qsabrelite_**, and it's not there on the list. Even on the build configuration (.../plat-imx/conf.mk), CAAM is currently disabled.
> 
>     1. Is there anyone who already enabled CAAM module on Nitrogen6q sabrelite?
Yes.
>     2. To enable the CAAM module by myself, what will be the steps that I need to go through?
Compile the OP-TEE OS with `CFG_NXP_CAAM=y`.
>     3. Will there be any modification needed in Linux kernel?
Yes, since the linux driver can't correctly probe the CAAM, it will disable the clocks. You'll need a dummy driver which keeps the clocks enabled. See https://github.com/OP-TEE/optee_os/issues/3405 and https://github.com/OP-TEE/optee_os/pull/3349. @clementfaure said NXP has a solution in the works for this, but not ETA has been posted so far.

**Comment by clementfaure** [comment]
Hello,
As @Emantor said, the current CAAM driver in Linux Kernel is not "Optee aware" and this cause the Linux CAAM driver initialization to fail and disable the CAAM clocks.
I talked to Horia Geantă. He is the CAAM driver maintainer. He still plans to upstream patches to make the CAAM driver compatible with Optee.

**Comment by ChangMinPark** [comment]
@Emantor,
Thanks, I was actually facing the same issue that one guy had in this post: #3710, overlapping memory with normal world when I'm trying with Linux. If it's just for QEMU platform as you mentioned on the post, I'm about to try reverting what https://github.com/OP-TEE/optee_os/commit/4f562c571b01ea38974018164ecf02385503ffd5 commit did. 

@clementfaure,
Thank you! I will try as the posts that you mentioned to solve CAAM issue on Linux.
