### ISSUE TITLE
[OPTEE-OS 3.7][REE FS] use of dirfile hash.

### ISSUE THREAD

**Issue by omasse-linaro** [OP-TEE/optee_os#3735]
Working on integration of OPTEE-OS 3.7 on NXP imx8mq with RPMB enabled.
So REE FS use a hash storage to store dirfile hash.
It seems that if the Secure REE FS is deleted from the Linux filesystem, the RPMB hash database will be unable to match with a new REE secure storage.

As a consequence, when looking for TA in secure storage to be loaded, the hash tree is unable to find the hash value stored in RPMB.
Result is a TEE_ERROR_SECURITY when opening a TA session.

In the code, init_head_from_data called from tee_fs_htree_open is getting a hash from RPMB (commit b4b1a20cc70996dc21004c4b5c173a4ef3d545fa).
However, the tee_fs_htree do not have a htree_node with correct hash value.

To reproduce the issue:
1. OPTEE configuration with CFG_RPMB_FS=y and CFG_REE_FS=y
2. boot the device and run xtest
3. Remove file in /data/tee (or /data/vendor/tee on Android)
4. reboot the device
5. run xtest
Result : Opening a TA will look for binary in Secure Storage which fail with TEE_ERROR_SECURITY.

Does it means that RPMB partition must be reset if the REE FS content is cleaned ?

**Comment by jbech-linaro** [comment]
When wiping the REE FS, it'll have the same effect as someone trying to tamper with the device. I.e., that's the reason why you see `TEE_ERROR_SECURITY`. So far so good. From usability and robustness point of view, things probably could be improved. Right now one would need to backup the merkle tree before wiping the REE FS and then later restore it again (with the files that we're tied to it).

> Does it means that RPMB partition must be reset if the REE FS content is cleaned ?

I think so.

**Comment by jenswi-linaro** [comment]
> > Does it means that RPMB partition must be reset if the REE FS content is cleaned ?
> 
> I think so.

It should be enough to remove `dirfile.db.hash` from RPMB.

**Comment by omasse-linaro** [comment]
> > > Does it means that RPMB partition must be reset if the REE FS content is cleaned ?
> > 
> > 
> > I think so.
> 
> It should be enough to remove `dirfile.db.hash` from RPMB.

yes, but how optee can decide to remove the  `dirfile.db.hash`  without compromising the security ?

**Comment by jenswi-linaro** [comment]
> yes, but how optee can decide to remove the `dirfile.db.hash` without compromising the security ?

It cannot, so that will have to be part of some production or rescue tool.

**Comment by omasse-linaro** [comment]
ok thanks for clarification.

**Comment by omasse-linaro** [comment]
Does this behavior should be also present on  OPTEE-OS version 3.2 ?
If yes, we do not face the issue with this version.

**Comment by jenswi-linaro** [comment]
It looks like it should be the same for 3.2.
