### ISSUE TITLE
HUK (hw unique key) vs. xtest

### ISSUE THREAD

**Issue by RNNord2** [OP-TEE/optee_os#3739]
Hi. I'm successfully building OP-TEE OS, client and test for an i.MX6 target. The full xtest suite runs without errors on the target. However, as soon as I modify tee_otp_get_hw_unique_key() to return anything else than just zeroes, xtest fails. I did this simple test:

`__weak TEE_Result tee_otp_get_hw_unique_key(struct tee_hw_unique_key *hwkey)
{
    memset(&hwkey->data[0], 1, sizeof(hwkey->data));
    return TEE_SUCCESS;
}`

Then OP-TEE OS, client and xtest (including TAs) were re-built, and as far as I have been able to confirm I have the correct dependencies when building OP-TEE test as:

TA_DEV_KIT_DIR=$OPTEE_OS_ROOT/out/arm-plat-imx/export-ta_arm32
OPTEE_CLIENT_EXPORT=$OPTEE_CLIENT_ROOT/out/export/usr 

The output from xtest is:

* regression_1001 Core self tests
  regression_1001 OK

* regression_1002 PTA parameters
  regression_1002 OK

* regression_1003 Core internal read/write mutex
    Number of parallel threads: 6 (2 writers and 4 readers)
    Max read concurrency: 2
    Max read waiters: 2
    Mean read concurrency: 1.3875
    Mean read waiting: 1.0125
  regression_1003 OK

* regression_1004 Test User Crypt TA
[_my op-tee test root_]/host/xtest/regression_1000.c:442: xtest_teec_open_session( &session, &crypt_user_ta_uuid, ((void *)0), &ret_orig) has an unexpected value: 0xf0100001 = TEE_ERROR_CORRUPT_OBJECT, expected 0x0 = TEEC_SUCCESS
  regression_1004 FAILED

(A lot of errors of the same type follows)

Any hint what might be going wrong here? As I will later implement getting a proper HUK from caam, I guess xtest will fail in the same way as in the test described here.

The version of all OP-TEE parts is 3.7.0.

**Comment by Emantor** [comment]
> Any hint what might be going wrong here? As I will later implement getting a proper HUK from caam, I guess xtest will fail in the same way as in the test described here.

There is already a PR for this, see https://github.com/OP-TEE/optee_os/pull/3608.

**Comment by RNNord2** [comment]
@Emantor Thank you for the PR hint, I will have a closer look. Previously I have just made some tests reading HUK through caam using selected code from NXPs OP-TEE OS repository. 

But isn't caam HUK reading and the xtest problem described above different issues? I thought that the implementation of tee_otp_get_hw_unique_key() could basically return anything as the HUK. If you would like to just have a hard coded key in the code, it should work (even if it obviously would be a really bad idea from security point of view) and xtest should pass, or am I missing something here? 

If not really sure if this question belongs to OP-TEE OS or OP-TEE test, so I'm sorry if it's at the wrong place.

**Comment by Emantor** [comment]
What are the build flags for your OP-TEE? Is 3.7.0 a checkout of the upstream repository or a downstream variant?

**Comment by RNNord2** [comment]
The OP-TEE OS 3.7.0 used is 'almost' the original upstream one. The only changes I have are:

- fdt_address_cells() and fdt_size_cells() modified to return 1 (to align with my fdt).

- added my own flavor to mx6dl-flavorlist in core/arch/arm/plat-imx/conf.mk, and:

ifneq (,$(filter $(PLATFORM_FLAVOR),myboardflavor))
CFG_DDR_SIZE = 0x40000000
CFG_UART_BASE = UART5_BASE
CFG_NS_ENTRY_ADDR = 0x17800000
CFG_WITH_PAGER = n
CFG_PAGEABLE_ADDR = 0
CFG_TZC380 = y
CFG_DT = y
CFG_DT_ADDR = 0x15000000
CFG_REE_FS = y
CFG_NXP_CAAM = n
CFG_EXTERNAL_DTB_OVERLAY = y
CFG_TEE_CORE_LOG_LEVEL = 0
CFG_TEE_CORE_DEBUG = n
CFG_TEE_TA_LOG_LEVEL = 0
CFG_CRYPTO_DRIVER_DEBUG = n
endif

**OP-TEE OS is built with:**
OPTEE_PLATFORM="imx"
OPTEE_FLAVOR="myboardflavor"
COMPILER_PREF=arm-linux-gnueabihf-
make PLATFORM=${OPTEE_PLATFORM}-${OPTEE_FLAVOR} clean
make PLATFORM=${OPTEE_PLATFORM}-${OPTEE_FLAVOR} \\ 
CROSS_COMPILE=${COMPILER_PREF} \\
ARCH=arm \\
LDFLAGS= \\
CFLAGS= \\
TA_SIGN_KEY=keys/default_ta.pem \\

**OP-TEE client** is original (upstream) 3.7.0 and built without any added flags.

**OP-TEE test** is original (upstream) 3.7.0 and built with:
export CROSS_COMPILE=arm-linux-gnueabihf-
export CROSS_COMPILE_TA=arm-linux-gnueabihf-
export CROSS_COMPILE_HOST=arm-linux-gnueabihf-
export TA_DEV_KIT_DIR=$OPTEE_OS_ROOT/out/arm-plat-imx/export-ta_arm32
export OPTEE_CLIENT_EXPORT=$OPTEE_CLIENT_ROOT/out/export/usr
arch=ARM make clean
arch=ARM make COMPILE_NS_USER=32

**Comment by Emantor** [comment]
Ah, The TEE FS Key is generated using the HUK, If you have previously stored data on the device with a different HUK, the entry table for stored files is encrypted and authenticated against the previous HUK. Wipe the data off the device before rerunning the tests with a different HUK.

**Comment by RNNord2** [comment]
@Emantor , great, wiping the contents of /data/tee on the target device made the trick. Thank you for your help, much appreciated. Now when this works, I can go back to enabling CAAM and get the HUK from there.

**Comment by 21212124** [comment]
@RNNord2  Can you explain how you can see the HUK on your board? my board is imx8m mini

**Comment by 21212124** [comment]
Hi @RNNord2,
Can you explain how you can see the HUK on your board? (my board is imx8m mini)

**Comment by Emantor** [comment]
To see the HuK with the current pull request you'll need to set `CFG_DBG_CAAM_TRACE=0x800` (to enable bit ten of the CAAM tracing which corresponds to the MKVB module). Note that the HuK will only be unique on a locked (HAB booted) device, since open devices use a test key which is the same across devices.

**Comment by RNNord2** [comment]
@Emantor , thanks for replying.

**Comment by 21212124** [comment]
@Emantor thanks, 
I am using the yocto project to create an image, do you know if it can also be configured?

**Comment by Emantor** [comment]
@21212124 You'll need to modify the recipe which creates your OP-TEE binary, take care to also include the pull request either via patches or using git.
