### ISSUE TITLE
TEE_GenerateKey with DSA SHALL accect domain parameters

### ISSUE THREAD

**Issue by mazhenke** [OP-TEE/optee_os#3746]
Hi,

From GlobalPlatform Technology TEE Internal Core API Specification, the function
**TEE_GenerateKey**
**SHALL** accept the following domain parameters:
1. TEE_ATTR_DSA_PRIME
2. TEE_ATTR_DSA_SUBPRIME
3. TEE_ATTR_DSA_BASE

But from OP-TEE OS code:
*syscall_obj_generate_key --> tee_svc_obj_generate_key_dsa --> crypto_acipher_gen_dsa_key --> dsa_make_key*
The DSA generate key doesn't accept the upper domain parameters, instead, the implementation generates them.

attached description in GP TEE Internal Core API Specification.
![image](https://user-images.githubusercontent.com/16829846/79097505-877c7800-7d92-11ea-9306-4b328ab6513f.png)

The OP-TEE OS code is from:
branch: **master**
HEAD: 
commit ee4d15901475dda07111ea1cc545d8b23ca6da1b (HEAD -> master, origin/master, origin/HEAD)
Author: Etienne Carriere <etienne.carriere@st.com>
Date:   Wed Apr 8 18:18:06 2020 +0200

**Comment by jforissier** [comment]
Hi @mazhenke,

Thanks for reporting this. I think you are right. The call to `dsa_make_key()` looks incorrect, we should call `dsa_generate_key()` instead.

Would you mind creating a PR?

**Comment by mazhenke** [comment]
Hi @jforissier ,

Sure, I will create a Pull request on this issue.

But recently I am too busy so that maybe I can't provide the complete patch shortly..

**Comment by jforissier** [comment]
@mazhenke I can take care of it if you prefer. It does not seem difficult. I have a question though.

Do you know how one is supposed to generate the `(p, q, g)` parameters (that is,  `TEE_ATTR_{PRIME, SUBPRIME,BASE}` as they are called in the GP spec)? LibTomCrypt has a function for that purpose (`dsa_generate_pqg()`) but I don't see that the GP API has that. Are they supposed to be pre-computed and embedded in the TA?

I'm asking because we would basically be replacing:
```
dsa_make_key()
{
        dsa_generate_pqg();
        dsa_generate_key();
}
```
...with `dsa_generate_key()` called on pre-computed `(p, q, g)`.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/3754

**Comment by mazhenke** [comment]
Hi @jforissier ,

Sorry for late response. I see your patch, appreciate for your quick response, 赞!

For the generating of (p, q, g), from spec:
https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf

![image](https://user-images.githubusercontent.com/16829846/79541272-199abe00-80bc-11ea-9cb0-6847d6a4e840.png)

I **guess** the (p, q, g) parameters are something similar to the curve/groups parameters (p, a, b, g, n) in ECDSA, that means, they are generated by one trusted third party and are distributed to the DSA sign/verify users. Unlike ECDSA, the (p, q, g) parameters in DSA are not limited to several groups(SECP192R1, SECP521R1, ...), but are infinite groups of (p, q, g). So in TEE Internal APIs, GP doesn't define the APIs of generating (p, q, g) parameters of DSA, like that GP doesn't define the APIs of generating curve/groups parameters (p, a, b, g, n) of ECDSA.

This is just my option, for your reference.

**Comment by jforissier** [comment]
@mazhenke makes sense, thanks.
