### ISSUE TITLE
Accessing Peripheral address from user TA

### ISSUE THREAD

**Issue by ravisankar197** [OP-TEE/optee_os#3758]
Hello all,
     I am trying access peripheral address from user TA to read the register data. Is there 
any feasible to access directly from user TA or is need to write OP-TEE driver ?
     For experiment purpose, In host side, I am trying with mmap of peripheral and registering
 the memory(TEEC_RegisterSharedMemory)  with flag TEEC_MEMREF_WHOLE and sending to TA.  But here  does this means only memory has shared between client and TA or memory will copy from client region to TA region?

**Comment by jenswi-linaro** [comment]
I'd recommend writing an OP-TEE driver.

**Comment by ravisankar197** [comment]
Thanks for the suggestion.

Experiment result: It seems like memory is copying to TA region. 
  Can anybody explain what the difference between TEEC_MEMREF_TEMP_INOUT 
  and TEEC_MEMREF_WHOLE type? I cannot able to understand clearly.

**Comment by jenswi-linaro** [comment]
> Experiment result: It seems like memory is copying to TA region.

I depends on shared memory configuration, that is, if you're using dynamic shared memory or allocating from a fixed pool and if you're using `TEEC_MEMREF_TEMP_*`.

> Can anybody explain what the difference between TEEC_MEMREF_TEMP_INOUT
and TEEC_MEMREF_WHOLE type? I cannot able to understand clearly.

You can start by skimming through https://globalplatform.org/specs-library/tee-client-api-specification/

`TEEC_MEMREF_TEMP_*` buffer are always temporary, this is, they are set up and teared down for each invokation.
`TEEC_MEMREF_WHOLE` uses a previously allocated and registered memory buffer, they are also a simplification of `TEEC_MEMREF_PARTIAL_*`.
