### ISSUE TITLE
How to make Hikey960 run debian OS include OPTEE

### ISSUE THREAD

**Issue by kouzili77** [OP-TEE/optee_os#3759]
Dears,

I'm kind of new to trustzone/optee... Recent days I successully build optee on my hikey960 4G version and pass the xtest. However, the current linux kenerl is extremely minimize and I even have no idea to transfer my host binary to the borad! My possible development may be like this: Firstly code and compile a TA together with the whole optee and flash it to hikey960. Then I may invoke the TA many times, only editing the host codes for data gethering or analysis purposes. That's why I need SSH, apt...whcih means, a debian OS.

I know you previously offered the hikey_debian manifest for hikey620, and recent months a rp3 user asked about debian and received the response of exchanging the rootfs and mannually adding the libteec.so*, libcrypto.so*, libcrypt*, *.ta, etc. I really got confused why it works, where are these files, when to do(after make the optee or before), how to get the rootfs(is it the one from 96Boards named rootfs-linaro-stretch-developer-hikey-20200320-44.img.gz?)

I really appreciate it if anyone offers me help. Ideas, comments about fesibility, links are all helpful! 

Thankyou!!!

Btw I notice that the linux kernel with optee environment is flashed into boot partition while in the 96Board's tutorial, boot only contains grub and the debian OS is flashed into system partition. Isn't it strange? What's the aim of it?

**Comment by jbech-linaro** [comment]
Like you concluded it's a bit tricky to figure out how to deploy images not already configured. Personally and depending what I'm doing I go between.
- Adding `BR2_PACKAGE_xyz` to `common.mk` in `build.git`. if it's something already supported in Buildroot, then I just recompile and it'll be in your rootfs. For example you can enable SSH with dropbear (`BR2_PACKAGE_DROPBEAR`).
- If I'm running QEMU, then I typically build with `QEMU_VIRTFS_ENABLE=y`, then I mount up the folder in QEMU with `mkdir -p /host && mount -t 9p -o trans=virtio host /host`. After that I can use use whatever I have on my host PC compiled to run on Armv7 or v8. This is my favorite setup, since most often if doing non-secure and TA development, I don't even have to reboot QEMU, I just symlink to the files on the host and then recompile them and run them directly in QEMU without having to do anything.
- If you have an AOSP build, then you can use adb.

Regarding the old HiKey Debian build, I do think that it was a nice and easy way to install packages etc. Using something like that is still doable. I had a rootfs with apt management enabled for my Raspberry Pi 3 builds for a long time. I.e., something that I used together with NFS for RPi3. However, I think that I lost that when I had a harddrive crash.

Maybe this gave some ideas?

**Comment by kouzili77** [comment]
Dear jbech,

Thank you so much. I can use ssh now which really reduces my pain. After my deepper understanding about this project, I now know how buildroot works on my board and how optee repositories are applied into rootfs and merged into an image. 

I notice that one can adding project-specific packages through the tutorial of buildroot, so the more suitable way is to build my own specific linux os for hikey based on buildroot(embedded with optee) instead of including optee into debian. Right?

Now I'm thinking if I manage to generate a larger rootfs and make the $(BOOT_IMG) bigger than 64M, I need to do those stpes:

`${SGDISK} -n 7:0:+64M -t 7:EF00 -u 7:d3340696-9b95-4c64-8df6-e6d4548fba41 -c 7:"boot" ${TEMP_FILE}` in generate_ptable.sh

`mformat -i $(BOOT_IMG) -n 64 -h 255 -T 131072 -v "BOOT IMG" -C ::` in hikey960.mk

For those two lines, change 64 into a bigger one.

May I ask is there any step I ignore? @jbech-linaro

**Comment by liuyunli** [comment]
@kouzili77  you said that "Recent days I successully build optee on my hikey960 4G version and pass the xtest", could you tell me the way how you do that. I can not find your contacts, can you send information to my mailbox "994605959@qq.com" ? Thank you very much.

**Comment by kouzili77** [comment]
Discuss here can be better since someone may view your problem and get help. You'd better show your question here or create a new issue. During my building of Hikey960+OPTEE(buildroot based), I followed the tutorial given by [optee.readthedocs.io](url) and the only issuse I encountered was solved by Issue#3083: "HiKey960: fix for 4G boards and support 6G boards " @liuyunli

**Comment by liuyunli** [comment]
@kouzili77  thank you very much for you advice. it really works.  I successully build optee on my hikey960 4G version and pass the xtest. And also  i met the same thing with you  that transfter the TA file use ssh. Could you share your progress?

**Comment by liuyunli** [comment]
@kouzili77  a way to transfer file from pc to hikey960 is to use xmodem by execute "rx file.xx". you can check the link:  https://github.com/OP-TEE/optee_os/issues/966

do you hava a plan to port aosp&optee to hikey960?  I've never  successed to do this before

**Comment by kouzili77** [comment]
@liuyunli 
Thx!
> @kouzili77 a way to transfer file from pc to hikey960 is to use xmodem by execute "rx file.xx". you can check the link: #966
Till now I get 3 methods:
Given by jbech-linaro, add dropbear (BR2_PACKAGE_DROPBEAR) package flag in common.mk so you get a built-in ssh sever running after boot.

Busybox rx via serial, I don't try it and it may not be as good as the ssh.

Alternatively, edit the rootfs file pack it into .img and then flash it.

> do you hava a plan to port aosp&optee to hikey960? I've never successed to do this before

Currently not

**Comment by liuyunli** [comment]
@kouzili77  how do you connect hikey960 via ssh ?  usb_to_rj45 or wlan ?  It seems that usb_to_rj45  not works on my board.

**Comment by kouzili77** [comment]
> @kouzili77 how do you connect hikey960 via ssh ? usb_to_rj45 or wlan ? It seems that usb_to_rj45 not works on my board.

@liuyunli WIFI. just make hikey to be in the same local area network with your host then just ssh via its LAN ip

I achieve this by let the host run a hotspot using USB wifi adapter. In common, if the host and hikey use the same wireless network offered by a router is also OK

**Comment by ZineddineOuldimam** [comment]
>     After that I can use use whatever I have on my host PC compiled to run on Armv7 or v8.
Hi @jbech-linaro 
I want to execute a **make** command inside the qemu on shared program from the host to guest. I can access to the folder from qemu. However the make command is not found in the normal word 

`# make`
`-sh: make: not found`

**Comment by jbech-linaro** [comment]
> > ```
> > After that I can use use whatever I have on my host PC compiled to run on Armv7 or v8.
> > ```
> 
> 
> Hi @jbech-linaro
> 
> I want to execute a **make** command inside the qemu on shared program from the host to guest. I can access to the folder from qemu. However the make command is not found in the normal word
> 
> 
> `# make`
> 
> `-sh: make: not found`

The "build-essentials" isn't installed I suppose? Buildroot is configured to have the bare necessities to be able to run xtest. Everything else people need for the developer setup has to be enabled by setting various BR flags etc.

**Comment by ZineddineOuldimam** [comment]
Thank you for your answer . How can I  install "build-essentials" ?

**Comment by jbech-linaro** [comment]
> Thank you for your answer . How can I install "build-essentials" ?

I don't know, never tried it. If I would have, then I would have searched/grep'd for config flags in Buildroot and tried that ones that seem to make sense.

**Comment by ZineddineOuldimam** [comment]
Thank you very much. I add `BR2_PACKAGE_MAKE ?= y` in **optee/build/common.mk** and make command now is working. For other packages, the file **optee/out-br/.config** is helpful to find them quickly.
