### ISSUE TITLE
 Panic at core/arch/arm/mm/core_mmu_lpae.c:366  TA_RAM  address

### ISSUE THREAD

**Issue by liuyunli** [OP-TEE/optee_os#3763]
use optee_os 3.8.0 branch and my board is hikey950-4G。
after modify optee_os\core\arch\arm\plat-hikey\conf.mk from CFG_DRAM_SIZE_GB ?= 3 to CFG_DRAM_SIZE_GB ?= 4, the building is success. but after flash to the board, log show bootup is panic. below is the log:
"
iomcu_subsys_init
boot_c0 PROFILE 4
slave0 irq0:0x00000004
slave1 irq0:0x00000004
NOTICE:  BL2: v2.0(release):v2.0-507-g34efb68
NOTICE:  BL2: Built : 09:33:27, Apr 14 2020
NOTICE:  BL2: Booting BL31
NOTICE:  BL31: v2.0(release):v2.0-507-g34efb68
NOTICE:  BL31: Built : 09:33:29, Apr 14 2020
D/TC:0 0 get_aslr_seed:1309 Warning: no ASLR seed
D/TC:0 0 add_phys_mem:581 TEE_SHMEM_START type NSEC_SHM 0x3ee00000 size 0x002000                                                                                00
D/TC:0 0 add_phys_mem:581 TA_RAM_START type TA_RAM 0x3f200000 size 0x00e00000
D/TC:0 0 add_phys_mem:581 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x3f063000 size 0x001                                                                                9d000
D/TC:0 0 add_phys_mem:581 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x3f000000 size 0x000                                                                                63000
D/TC:0 0 add_phys_mem:581 ROUNDDOWN(0xFFF32000, CORE_MMU_PGDIR_SIZE) type IO_NSE                                                                                C 0xffe00000 size 0x00200000
D/TC:0 0 verify_special_mem_areas:525 SDP memory [3e800000 3ec00000]
D/TC:0 0 verify_special_mem_areas:525 NSEC DDR memory [200000000 220000000]
D/TC:0 0 verify_special_mem_areas:525 NSEC DDR memory [40000000 e0000000]
D/TC:0 0 verify_special_mem_areas:525 NSEC DDR memory [0 3e000000]
D/TC:0 0 add_va_space:620 type RES_VASPACE size 0x00a00000
D/TC:0 0 add_va_space:620 type SHM_VASPACE size 0x02000000
D/TC:0 0 dump_mmap_table:732 type IO_NSEC      va 0x3ae00000..0x3affffff pa 0xff                                                                                e00000..0xffffffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type TA_RAM       va 0x3b000000..0x3bdfffff pa 0x3f                                                                                200000..0x3fffffff size 0x00e00000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type NSEC_SHM     va 0x3c000000..0x3c1fffff pa 0x3e                                                                                e00000..0x3effffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type SHM_VASPACE  va 0x3c200000..0x3e1fffff pa 0x00                                                                                000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type RES_VASPACE  va 0x3e400000..0x3edfffff pa 0x00                                                                                000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type TEE_RAM_RX   va 0x3f000000..0x3f062fff pa 0x3f                                                                                000000..0x3f062fff size 0x00063000 (smallpg)
D/TC:0 0 dump_mmap_table:732 type TEE_RAM_RW   va 0x3f063000..0x3f1fffff pa 0x3f                                                                                063000..0x3f1fffff size 0x0019d000 (smallpg)
E/TC:0 0 Panic at core/arch/arm/mm/core_mmu_lpae.c:366 <check_nsec_ddr_max_pa>
E/TC:0 0 TEE load address @ 0x3f000000
E/TC:0 0 Call stack:
E/TC:0 0  0x000000003f00b6ac
"

I found the mmap_table of TA_RAM maybe wrong, i think the value maybe 0x3f200000  not 0x3b000000. Can any one help me to resolve it ? Thanks  very much.

**Comment by liuyunli** [comment]
resloved by  Issue#3083: "HiKey960: fix for 4G boards and support 6G boards "

**Comment by deekshith565** [comment]
E/TC:00 0 Panic at core/arch/arm/mm/core_mmu_lpae.c:371 <check_nsec_ddr_max_pa>

I am having same issue but in our platform, I tried all things but didn't help, can anyone help me.

Our platform is in version 3.5.0 and now while migrating to 3.8.0 I'm getting above error, kindly help.
