### ISSUE TITLE
Secure storage on RPMB from uboot

### ISSUE THREAD

**Issue by ruchi393** [OP-TEE/optee_os#3768]
Hi,

IIUC, in uboot , for testing communication with a TA in OPTEE , only avb command support is available. Apart from that, there is no other way for platforms to test if access from UBOOT to OPTEE TA works fine. 

For platforms not enabling AVB, I suggest adding a simple test_rpmb_obj  in ta folder in optee which does the following :
1. Create a persistent object based on name of the variable and value passed from uboot command
2. Read and return back the value to uboot for the above variable.

Two commands can be added on uboot:
tee_rpmb_read <var_name> <value>
tee_rpmb_write <var_name> <len to read>

This is similar to what is achieved by avb write_pvalue and avb read_pvalue command. But saves the trouble platform owner gets into when trying to test basic path from uboot to optee and tests rpmb.

Please let me know your views/other ideas to help simplify this testing from uboot. 

Is this the right approach or should I think about adding PTA for testing the same. Do let me know your views on the same.

Regards,
Ruchika

**Comment by jenswi-linaro** [comment]
Hi Ruchika,

To help me understand the problem better. What is the difference between using another TA compared to using the AVB TA? What is the problem with enabling AVB?

Cheers,
Jens

**Comment by ruchi393** [comment]
Hi Jens,

Enabling AVB has a lot of dependencies - CMD AVB has a dependency on AVB_VERIFY which further has dependency on FASTBOOT , LIBAVB and PARTITION_UUID;s.

Given below are all CONFIGS which I had to enable to just get the avb command working

+CONFIG_UDP_FUNCTION_FASTBOOT=y
+CONFIG_ANDROID_BOOT_IMAGE=y
+CONFIG_USB_FUNCTION_FASTBOOT=y
+CONFIG_FASTBOOT_BUF_SIZE=0x10000000
+CONFIG_FASTBOOT_FLASH=y
+CONFIG_FASTBOOT_FLASH_MMC_DEV=0
+CONFIG_FASTBOOT_CMD_OEM_FORMAT=y
+
+CONFIG_LIBAVB=y
+CONFIG_AVB_VERIFY=y
+CONFIG_CMD_AVB=y

+CONFIG_OPTEE_TA_AVB=y

My platform is neither using FASTBOOT nor Android verified boot. So enabling a bunch of configs just to test communication with uboot seems an overkill to me. Also , apart from avb read_pvalue and avb write_pvalue other commands do not hold any significance for non AVB users. 

I was looking for an easier and generic way to test stuff.

Regards,
Ruchika

**Comment by jenswi-linaro** [comment]
Thanks, now I remember enabling AVB was a bit painful. What do you think about reusing the AVB TA for testing?

**Comment by ruchi393** [comment]
That is a good idea. I can create a new command on uboot and at the backend use the AVB TA. I will give that a try. 

Regards,
Ruchika

**Comment by jenswi-linaro** [comment]
:+1:

**Comment by ldts** [comment]
yeah, @ruchi393 we wrote a TA and a u-boot command to access RPMB that dont have all the AVB dependencies.

https://github.com/foundriesio/u-boot/blob/2019.10%2Bfio/cmd/fiovb.c 
https://github.com/foundriesio/optee_os/tree/3.6.0%2Bfio/ta/fiovb

if might help you basing off this one

**Comment by ruchi393** [comment]
Patches sent on uboot mailing list for adding the command optee_rpmb read_pvalue/write_pvalue

**Comment by etienne-lms** [comment]
[patchwork link](https://patchwork.ozlabs.org/project/uboot/patch/20200422171826.139753-1-ruchika.gupta@nxp.com/)
