### ISSUE TITLE
ASLR doesn't work with Clang

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3772]
OP-TEE master hangs on boot (no display at all) on QEMUv8 when built with Clang (9.x or 10.0.0, it doesn't matter). The culprit is `CFG_CORE_ASLR=y`. I have not investigated further.

**Comment by jforissier** [comment]
Now I see what's happening. `stack_tmp_export` is NULL, so we initialize `sp` to zero which triggers a synchronous exception quite rapidly of course.

The root cause is, there is an `R_AARCH64_RELATIVE` relocation on this symbol, which sounds somewhat incorrect to begin with since it is used before we have processed relocations (and before MMU is turned on). By chance (or by convention?) GCC populates the `stack_tmp_export` location with the "correct" value, that is: the expected final value it should have when the executable is mapped at its preferred load address. But guess what... Clang leaves it to zero.

@jenswi-linaro any idea how we should deal with that?

**Comment by jforissier** [comment]
Clang (`ld.lld`) behavior confirmed: https://reviews.llvm.org/D42797

The following patch works:

```diff
diff --git a/core/arch/arm/kernel/link.mk b/core/arch/arm/kernel/link.mk
index 72c21dfc..6b057f64 100644
--- a/core/arch/arm/kernel/link.mk
+++ b/core/arch/arm/kernel/link.mk
@@ -11,7 +11,7 @@ AWK    = awk

 link-ldflags  = $(LDFLAGS)
 ifeq ($(CFG_CORE_ASLR),y)
-link-ldflags += -pie -z notext -z norelro
+link-ldflags += -pie -z notext -z norelro $(ldflag-apply-dynamic-relocs)
 endif
 link-ldflags += -T $(link-script-pp) -Map=$(link-out-dir)/tee.map
 link-ldflags += --sort-section=alignment
diff --git a/mk/clang.mk b/mk/clang.mk
index cdff9b7f..1549ea39 100644
--- a/mk/clang.mk
+++ b/mk/clang.mk
@@ -40,6 +40,8 @@ comp-cflags-warns-clang := -Wno-language-extension-token \
 libgcc$(sm)    := $(shell $(CC$(sm)) $(CFLAGS$(arch-bits-$(sm))) $(comp-cflags$(sm)) \
                        -print-libgcc-file-name 2> /dev/null)

+ldflag-apply-dynamic-relocs := --apply-dynamic-relocs
+
 # Define these to something to discover accidental use
 CC             := false
 CPP            := false
```

**Comment by jenswi-linaro** [comment]
Yeah, I noticed that the RELA relocations already had the expected value so OP-TEE depends on that in order to skip one pass of RELA relocations.

**Comment by jforissier** [comment]
@jenswi-linaro OK that's fine so the above patch makes sense after all, I will open a PR and document why the flag is needed. Thanks for the feedback.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/3791
