### ISSUE TITLE
TA open session failed because of tee_rpmb_init

### ISSUE THREAD

**Issue by chinaluke** [OP-TEE/optee_os#3773]
Hi,

environment:
       optee version 3,7
       CFG_REE_FS=y, CFG_RPMB_FS=y, and RPMB_EMU := 0 in tee-supplicant.

Issue:
        I implement my own tee_rpmb_key_gen().
        To initialze the rpmb_key, I use NA to send rpmb_key to optee_os and encrypt the rpmb_key in optee_os. After that, I will save the encrypted data to flash. 
        Then I encountered a chicken-and-egg problem. From the following log, It seems that I can not open session when rpmb_key is not ready.
        Could you please give us some pointers, thanks! 

log: 
	NA: init context
	NA: open session
	D/TC:? 0 tee_ta_init_pseudo_ta_session:280 Lookup pseudo TA cb71e0c9-260c-48e8-b0dd-36c95d3cadba
	D/TC:? 0 load_ldelf:707 ldelf load address 0x104000
	D/LD:  ldelf:134 Loading TA cb71e0c9-260c-48e8-b0dd-36c95d3cadba
	D/TC:? 0 tee_ta_init_session_with_context:572 Re-open TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
	D/TC:? 0 system_open_ta_binary:239 Lookup user TA ELF cb71e0c9-260c-48e8-b0dd-36c95d3cadba (Secure Storage TA)
	D/TC:? 0 tee_rpmb_read:1357 RAW addr:0 ,data:48658e00, len:80
	D/TC:? 0 tee_rpmb_read:1377 read once addr:0 ,data:48658e00, len:80
	D/TC:? 0 tee_rpmb_init:1120 RPMB INIT: Deriving key
	I/TC: RPMB: Using keybox key
	E/TC:? 0 tee_rpmb_key_gen:284 rpmb_key not burned, burn it before use rpmb storage
	E/TC:? 0 tee_rpmb_init:1126 RPMB INIT: Deriving key failed with error 0xffffffff
	D/TC:? 0 system_open_ta_binary:242 res=0xffffffff
	D/TC:? 0 tee_ta_invoke_command:772 Error: ffffffff of 4
	E/LD:  init_elf:259 sys_open_ta_bin(cb71e0c9-260c-48e8-b0dd-36c95d3cadba)
	E/TC:? 0 init_with_ldelf:229 ldelf failed with res: 0xffffffff
	D/TC:? 0 tee_ta_close_session:498 csess 0x486594c8 id 1
	D/TC:? 0 tee_ta_close_session:517 Destroy session
	D/TC:? 0 destroy_context:297 Destroy TA ctx (0x48659488)
	D/TC:? 0 tee_ta_close_session:498 csess 0x486591c0 id 1
	D/TC:? 0 tee_ta_close_session:517 Destroy session
	E/TC:? 0 tee_ta_open_session:727 Failed. Return error 0xffffffff

**Comment by jforissier** [comment]
Hi @chinaluke ,

Given [this](https://github.com/OP-TEE/optee_os/blob/3.8.0/core/pta/system.c#L255) and [this](https://github.com/OP-TEE/optee_os/blob/3.8.0/core/tee/tee_rpmb_fs.c#L1098-L1104), I think that your `tee_rpmb_key_gen()` function needs to return `TEE_ERROR_STORAGE_NOT_AVAILABLE` when called for the first time (and it doesn't have a key to return).

**Comment by chinaluke** [comment]
Hi @jforissier ,

Thank you very much!
