### ISSUE TITLE
Which REE OS should be used for raspberry pi with TEE(optee)?

### ISSUE THREAD

**Issue by aliamal** [OP-TEE/optee_os#3785]
Hi,
I'm trying to test TAs in optee; but which **OS** is recommended to be used in raspberry pi as **REE**, to communicate with optee normally, **raspbian**, **ubuntu mate** etc.?

**Comment by jbech-linaro** [comment]
If you are new to OP-TEE and want to explore it, then give [QEMU v7 a try](https://optee.readthedocs.io/en/latest/faq/faq.html#faq-try-optee). No need for any particular hardware in that setup and you can do the same as on real hardware (mostly). This works on a regular computer running Ubuntu, Debian etc. Probably any Linux distro as long as you sort out the dependencies. For Ubuntu we have sorted out all that in terms of a set of [prerequisites](https://optee.readthedocs.io/en/latest/building/prerequisites.html#prerequisites).

If you insist on using RPi3, then there are no "REE OS" in our official builds (I guess you refer to a distro). It's just a Linux kernel running on with stripped down root files system (read [this](https://optee.readthedocs.io/en/latest/building/devices/rpi3.html#what-is-expected-to-work) for more details about that). I know that there are some unofficial builds out there if you do a Google search for it that have been able to enable and run Raspbian together with OP-TEE). But as mentioned, this is not officially supported, so we cannot help out with whatever it takes to get that to work.

**Comment by aliamal** [comment]
thank you;
