### ISSUE TITLE
Mismatch between Secure Storage documentation and code

### ISSUE THREAD

**Issue by Vitolog** [OP-TEE/optee_os#3787]
Reading the following documentation
https://optee.readthedocs.io/en/latest/architecture/secure_storage.html
seems SSK is a 128bit value and FEK is encrypted with AES-ECB using SSK.

But reading the code seems SSK is a 256bit value and HMAC-SHA256(SSK,FEK) is used for storing FEK.
Could you please confirm?
Thanks

**Comment by jforissier** [comment]
Hi @Vitolog ,

> But reading the code seems SSK is a 256bit value

Correct. The doc is wrong here.

> and HMAC-SHA256(SSK,FEK) is used for storing FEK.

No, AES-ECB(TSK, FEK) is used. And TSK = HMAC-SHA256(SSK, UUID).

**Comment by Vitolog** [comment]
HI @jforissier,
you're right: my fault!
We're talking about AES_256_ECB for FEK ecncryption, right?

**Comment by Vitolog** [comment]
Before closing the issue, I have another question:

- FEK (File Encryption Key) is a 128bit random number?

- If yes, is it padded in order to be encrypted with AES_256_ECB using TSK as key?

**Comment by jforissier** [comment]
> Before closing the issue, I have another question:
> 
> * FEK (File Encryption Key) is a 128bit random number?

Yes.

> * If yes, is it padded in order to be encrypted with AES_256_ECB using TSK as key?

No.

**Comment by Vitolog** [comment]
So if the FEK is 128bits and the block size for AES_256_ECB is 256bits, wich is the value of remaining 128bits? Is the plaintext bock 0x00||...||0x00||FEK?

**Comment by jforissier** [comment]
AES block size is 128 bits even with a 256-bit key.
