### ISSUE TITLE
Use UART1 as secure I/O on imx6q Sabre Lite

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/optee_os#3789]
Hello,

I want to access some peripherals through **UART1** on the **imx6q Sabre Lite board** as secure I/O.
According to [default configures on the imx boards](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-imx/conf.mk#L248), the default OP-TEE's console is through UART2.

I first referenced [#2438](https://github.com/OP-TEE/optee_os/issues/2438), then I disabled the UART1 in the device tree, there is no `/dev/ttymxc0` in Linux.
To test UART1, I wrote a Pseudo TA, the code in PTA is :
```C
1. static struct imx_uart_data uart1_data;            // global variable
2. imx_uart_init(&uart1_data, UART1_BASE);            // in PTA's open_session()
3. uart1_data.chip.ops->getchar(&uart1_data.chip);    // call the imx_uart driver operation to get data
```

Also, I register the address of UART1 as non-secure memory area into OP-TEE in `plat-imx/main.c`:
```C
register_phys_mem_pgdir(MEM_AREA_IO_NSEC, UART1_BASE, CORE_MMU_PGDIR_SIZE);
```
However, the system hangs when `getchar()` is called.
Could somebody help me with this problem?

Any suggestions would be appreciate.
Thanks.

**Comment by Emantor** [comment]
AFAIR OP-TEE does not do any UART initialization itself. Additionally, the Linux kernel will disable the clocks since the UART is unused from its point of view and it assumes full control over the i.MX Clock Control Module. You may need to hack a small kernel module to keep the clocks enabled.
If you channel supports any kind of encryption, you could also write a driver for the kernel which abstracts communication between the UART and your TA.

**Comment by gagachang** [comment]
Hi @Emantor , thanks for reply.

Actually I tried to enable the UART1 in dtb first. And the board can communicate with my computer through both UART1 and UART2 (default console) in normal world Linux.
The board can receive some messages from my computer through UART1.

However, when I called TA and PTA to `getchar()` from UART1, the system still hangs. And I can't type anything on my computer's terminal.
BTW, I found that UART1's parent is aips-bus (AIPS1), and this bus address is registered into OP-TEE as `MEM_AREA_IO_SEC` [here](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-imx/main.c#L90). But I register the UART1's address as `MEM_AREA_IO_NSEC`.
Do you think that the problem is from here?
Thank you.

**Comment by gagachang** [comment]
I found that the UART's clock is still disabled in OP-TEE even if I enabled **uart1** in dtb.
OP-TEE hangs in an infinite loop when `imx_uart_getchar()` driver call is executed.
I modified the driver to print some messages to seek the problem :

```C
static int imx_uart_getchar(struct serial_chip *chip)
{	
	vaddr_t base = chip_to_base(chip);

	while (io_read32(base + UTS) & UTS_RXEMPTY) {
		DMSG("UCR1_UARTCLKEN = %d", io_read32(base + UCR1) & UCR1_UARTCLKEN);
		if (!(io_read32(base + UCR1) & UCR1_UARTEN))
			return;
	}

	return (io_read32(base + URXD) & URXD_RX_DATA);
}
```

The log showed that `UCR1_UARTCLKEN` is **0**, but `UCR1_UARTEN` is **1** and caused the loop.
I will make an intensive study of this.

**Comment by Emantor** [comment]
The `enabled` property within the device tree tells the kernel that it can use the device, runtime power management of the i.MX serial code will still enable and disable the clocks dynamically if the device isn't used by the kernel.

**Comment by gagachang** [comment]
Hi, @Emantor 
Thanks for explanation.
I have no idea why OP-TEE can use **UART2** as it's serial console but **UART1** is unusable for my PTA.
Would you give me some suggestions about how to fix it?

**Comment by Emantor** [comment]
I think there are multiple possible pitfalls here:
1. The OP-TEE imx uart init function does not do any baudrate setup and expects this to be done by the bootloader
2. The kernel can disable UARTs on its own via the bits or via clocks, but I have not looked into the clock tree.
3. The imx uart write and read functions do not ensure that the UART is enabled.

I would start by looking at the state of the UART when trying to access it and than modify the kernel or OP-TEE to ensure that the UART is in a usable state when trying to use it.
