### ISSUE TITLE
Is this a BUG in mbedtls_mpi_shrink in lib/libmbedtls/mbedtls/library/bignum.c?

### ISSUE THREAD

**Issue by mazhenke** [OP-TEE/optee_os#3790]
Hi,

I found that the mbedtls_mpi_shrink implementation is different from mbedtls (https://github.com/ARMmbed/mbedtls)

This is the mbedtls_mpi_shrink in our OP-TEE:
![image](https://user-images.githubusercontent.com/16829846/80190062-3f890b00-8646-11ea-864f-777176208c9c.png)

This is the mbedtls_mpi_shrink in mbedtls with branch mbedtls-2.22.0:
![image](https://user-images.githubusercontent.com/16829846/80191087-cd192a80-8647-11ea-85e6-dd6a34686ffc.png)

Be careful about the calloc size:
1. OP-TEE: nblimbs * ciL
2. mbedtls-2.22.0: i * ciL

In OP-TEE implementation, if nblimbs < X->n, there will be data loss.

And I noticed that there is one comment in OP-TEE:
![image](https://user-images.githubusercontent.com/16829846/80191409-3e58dd80-8648-11ea-92bd-940c61dba1c1.png)

Could someone help to explain it? Thanks!

OP-TEE code at Head:
commit 02b4d42ac4f717041ed1ee66a1e7f0d3f640366f (HEAD -> master, origin/master, origin/HEAD)
Author: Etienne Carriere <etienne.carriere@linaro.org>
Date:   Wed Apr 22 17:06:31 2020 +0200

    ta: pkcs11: set default token serial number based on token ID
    
    With this change, token serial number is string "0...0000000<N>" over
    16 characters, led with '0' and ending with token ID decimal value.
    
    It is common for the client application to decide the slot to use
    based on the token serial number. Therefore change the default value
    to be based on the token ID to avoid having the same serial numbers
    on every token.
    
    Co-developed-by: Ricardo Salveti <ricardo@foundries.io>
    Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
    Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
    Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
    Acked-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>
    [jf: cast sizeof() to int in snprintf() with field with specifier '*']
    Signed-off-by: Jerome Forissier <jerome@forissier.org>

**Comment by jforissier** [comment]
Hi @mazhenke,

I don't know this part of the code very well, but I think you are right. @jenswi-linaro can you confirm?

I traced this local change back to commit 782fddd10ccb ("libmbedtls: add mbedtls_mpi_init_mempool()") which is present in our import branch `import/mbedtls-2.6.1`, in other words since the beginning (Mbedtls 2.6.1 is the first version we used in OP-TEE).

**Comment by jforissier** [comment]
About the comment you're mentioning, it comes from upstream: https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.22.0/library/bignum.c#L164

**Comment by jenswi-linaro** [comment]
Agree, it looks like we should update to use `i` instead. Must be something we've overlooked when upgrading at some point.

**Comment by jforissier** [comment]
@mazhenke would you like to create a pull request for this? Or I can take care of it if you prefer. In this case you may also give me a `Reported-by: Your Name <your_email_address>` if you wish, then I can add it to the patch (no obligation).

**Comment by mazhenke** [comment]
@jforissier Sorry that I am not familiar with OP-TEE's coding style and patch merge mechanism. So could you please help to submit a path to fix this? Thanks a lot!

You can add this report info to path if you wish:

**Reported-by: Zhenke Ma <zhenke.ma@armchina.com>**

Thanks!

**Comment by jforissier** [comment]
@mazhenke sure, thanks for reporting.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/3813
