### ISSUE TITLE
RFC linux i2c access, integration of a secure element (crypto device on i2c bus)

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#3793]
Below I have simple implementation that allows op-tee to access devices on the i2c bus via linux ( pre-allocating a buffer in the kernel to send/receive the bus traffic).

I also wrote an i2c driver for TEE (imx) to control the SE on the bus before linux is ready.

1. Is this code below something that you would consider merging -in which case I'll submit a patch in the coming days- or does the architecture expects the user to write a TA for this or access the bus somewhat differently?

This is part of a larger integration task of an i2c crypto device (SE050) and associated library for which I have another question. I ported the a ~30K LOC to op-tee (with its original coding standards) from NXP. 

1. Could such a library be accepted without a rewrite if I were to submit a patch? The integration to TEE only touched some minor elements on the library to be able to pull and merge future versions (the access to i2c and other bits here and there). As I said It will be a bit over 30K LOC and contains code shared with other operating systems..

```
#define I2C_BUFFER_SIZE			PAGE_SIZE
static struct mobj *mobj;

TEE_Result tee_i2c_transfer(TEE_I2C *request)
{
	size_t processed = 0;
	TEE_Result res;
	void *va;

	if (!request || request->bufferLen > I2C_BUFFER_SIZE) {
		EMSG("bad input parameters ");
		return TEE_ERROR_BAD_PARAMETERS;
	}

	if (!mobj) {
		mobj = thread_rpc_alloc_kernel_payload(I2C_BUFFER_SIZE);
		if (!mobj)
			return TEE_ERROR_BAD_PARAMETERS;
	}

	va = mobj_get_va(mobj, 0);
	assert(va);

	/* write operation */
	if (!request->mode)
		memcpy(va, request->buffer, request->bufferLen);

	struct thread_param params[] = {
		[0] = THREAD_PARAM_VALUE(IN, request->mode, request->bus, request->chip),
		[1] = THREAD_PARAM_MEMREF(INOUT, mobj, 0, request->bufferLen),
		[2] = THREAD_PARAM_VALUE(OUT, processed, 0, 0),
	};

	res = thread_rpc_cmd(OPTEE_MSG_RPC_CMD_I2C_TRANSFER, ARRAY_SIZE(params), params);
	if (res != TEE_SUCCESS)
		return res;

	/* read operation */
	if (request->mode)
		memcpy(request->buffer, va, request->bufferLen);

	return res;
}
```

The relevant kernel patch to drivers/tee/rpc.c

```
 static void handle_rpc_func_cmd_i2c_transfer(struct tee_context *ctx,
 					     struct optee_msg_arg *arg)
 {
 	struct i2c_client client;
 	struct i2c_adapter *adap;
 	struct tee_shm *shm;
 	int ret;
 
 	if (arg->num_params != 3)
 		goto bad;
 
 	adap = i2c_get_adapter(arg->params[0].u.value.b);
 	if (!adap)
 		goto bad;
 
 	snprintf(client.name, I2C_NAME_SIZE, "i2c%d", adap->nr);
 	client.addr = arg->params[0].u.value.c;
 	client.adapter = adap;
 
 	shm = (struct tee_shm *)(unsigned long)arg->params[1].u.tmem.shm_ref;
 
 	if (arg->params[0].u.value.a) {
 		ret = i2c_master_recv(&client, shm->kaddr,
 				      arg->params[1].u.tmem.size);
 	} else {
 		ret = i2c_master_send(&client, (char *) shm->kaddr,
 				      arg->params[1].u.tmem.size);
 	}
 
 	if (ret >= 0) {
 		arg->params[2].u.value.a = ret;
 		arg->ret = TEEC_SUCCESS;
 	} else {
 		arg->ret = TEEC_ERROR_COMMUNICATION;
 	}
 
 	i2c_put_adapter(adap);
 
 	return;
 bad:
 	arg->ret = TEEC_ERROR_BAD_PARAMETERS;
 }
```

@Emantor ^^ (we talked about something like this a few weeks ago)

fyi I am using this code with xtest where I validated (sha-perf/aes-perf) the RNG, HMAC and AES ECB enc/dec on the SE050 using imx8mm LPDDR4 - in the process of validating the other crypto operations.

**Comment by ldts** [comment]
@Emantor ^^ (we talked about something like this a few weeks ago)

**Comment by jluebbe** [comment]
This looks much less complex than sharing a I²C controller between Linux and OP-TEE. I wonder if the identification of the bus/controller should happen via DT path or alias (instead of just the number).

**Comment by ldts** [comment]
hi @jluebbe not sure what you mean? this is actually working code that shares the i2c bus controller initialized and configured by Linux (with runtime pm and the rest). Is quite simple hence why I am raising the question here...IMO it should be merged.

The  op-tee native i2c driver just can not  work once Linux boots and runtime pm in operation; the op-tee native i2c driver is certainly useful - and I use it as well- earlier during boot when the boot sequence is for instance SPL-> OP-TEE -> UBOOT -> LINUX...then we dont need libtomcrypt (that is my working environment btw)

In my code, once Linux is up and running, op-tee stops using its native i2c driver and uses this trampoline above instead.

**Comment by ldts** [comment]
hi @jforissier could you comment please? should I submit the i2c support patch or is there a better alternative?
if you could also comment on the question about the [SE050](https://bit.ly/2KQesIO) integration into op-tee I'd appreciate that as well.

**Comment by jforissier** [comment]
@ldts sorry for the late reply. Here is my opinion.

- Having a native i2c driver in OP-TEE certainly sounds useful and not out of place in a secure OS, so don't hesitate to open a PR
- Similarly, the "i2c via Linux" thing sounds reasonable to me (we have a similar mechanism already for RPMB, actually even more complex since it goes via `tee-supplicant`)
- As for importing the crypto element library, it can be considered too, especially if it can be shared by several platform flavors. [We know how to deal with that](https://optee.readthedocs.io/en/latest/building/gits/optee_os.html#import-branches), consider for instance Mbed TLS or LibTomCrypt. The fact that the original code doesn't follow the OP-TEE coding style is not really an issue. Careful about the licensing terms of the library, though!

**Comment by ldts** [comment]
@jforissier ok thanks.will send the two i2c drivers soon (and will submit the kernel bit of the i2c trampoline once the op-tee bit is merged).
