### ISSUE TITLE
Panic in TEE_BigIntConvertToOctetString() with ECC

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#3794]
I already have an ECC private key generated(i.e. it's attributes are already populated). Now, i'm trying to extract it's corresponding public key(X,Y of the public key are stored as octet-strings). To do this, i've done the following(i'll try to explain it via pseudo code):

1)i'm trying to read the X,Y attributes via: TEE_GetObjectBufferAttribute(key_handle,attribute_id,*buffer, size); where "buffer" is storing the attributes  and "size" (size_x and size_y) is the corresponding size of those attributes.

If i'm not wrong, this buffer will have the bignum/bigint variants of X,Y rite?

What is the size that is returned by TEE_GetObjectBufferAttribute()?Is it the same as what TEE_BigIntGetBitCount() returns? or is it the ECC public key size?

2)allocating the buffers for octet_string_x and octet_string_y as:
octet_string_x = TEE_Malloc(size_x, TEE_MALLOC_FILL_ZERO);
octet_string_y = TEE_Malloc(size_y, TEE_MALLOC_FILL_ZERO);

3)allocating and initializing the bignums for X,Y as:
TEE_BigInt *bignum_x = NULL;
TEE_BigInt *bignum_y = NULL;

bignum_x = (TEE_BigInt *)TEE_Malloc(size_x, TEE_MALLOC_FILL_ZERO);
TEE_BigIntInit(bignum_x, size_x);

bignum_y = (TEE_BigInt *)TEE_Malloc(size_y, TEE_MALLOC_FILL_ZERO);
TEE_BigIntInit(bignum_y, size_y);

4)calling the convert to octet string function as:
TEE_BigIntConvertToOctetString(octet_string_x, &octet_string_x_len, bignum_x);
TEE_BigIntConvertToOctetString(octet_string_x, &octet_string_x_len, bignum_x);

Step4 resulted in a panic.

Currently, what i am suspecting is that the allocated octet-string is not enough to store the bigint.
i'm not sure if TEE_BigIntGetBitCount(bignum_x) would help me in retrieving the size of the bigint's so that i could allocate a sufficient octet-string buffer.

i already had a look into https://github.com/OP-TEE/optee_os/issues/658 
But it doesn't help with my use-case

**Comment by jforissier** [comment]
Hi @saddy-muchu,

> 1)i'm trying to read the X,Y attributes via: TEE_GetObjectBufferAttribute(key_handle,attribute_id,*buffer, size); where "buffer" is storing the attributes and "size" (size_x and size_y) is the corresponding size of those attributes.
> 
> If i'm not wrong, this buffer will have the bignum/bigint variants of X,Y rite?

No, if I'm not mistaken you will directly get the result as an octet string.
 
> What is the size that is returned by TEE_GetObjectBufferAttribute()?Is it the same as what TEE_BigIntGetBitCount() returns? or is it the ECC public key size?

It returns the minimal size in bytes needed for the buffer to hold the requested value. Typically, if you don't know the size in advance, you can call the function twice. First with `buffer == NULL` to get the size, the function will return `TEE_ERROR_SHORT_BUFFER` and return the size. Then you allocate a buffer of this size and call the function again to obtain the value. The function should return `TEE_SUCCESS`.

**Comment by saddy-muchu** [comment]
> 
> 
> Hi @saddy-muchu,
> 
> > 1)i'm trying to read the X,Y attributes via: TEE_GetObjectBufferAttribute(key_handle,attribute_id,*buffer, size); where "buffer" is storing the attributes and "size" (size_x and size_y) is the corresponding size of those attributes.
> > If i'm not wrong, this buffer will have the bignum/bigint variants of X,Y rite?
> 
> No, if I'm not mistaken you will directly get the result as an octet string.
> Meaning, i don't really have to use TEE_BigIntConvertToOctetString() function.
> > What is the size that is returned by TEE_GetObjectBufferAttribute()?Is it the same as what TEE_BigIntGetBitCount() returns? or is it the ECC public key size?
> 
> It returns the minimal size in bytes needed for the buffer to hold the requested value. Typically, if you don't know the size in advance, you can call the function twice. First with `buffer == NULL` to get the size, the function will return `TEE_ERROR_SHORT_BUFFER` and return the size. Then you allocate a buffer of this size and call the function again to obtain the value. The function should return `TEE_SUCCESS`.

OK

**Comment by saddy-muchu** [comment]
> 
> 
> Hi @saddy-muchu,
> 
> > 1)i'm trying to read the X,Y attributes via: TEE_GetObjectBufferAttribute(key_handle,attribute_id,*buffer, size); where "buffer" is storing the attributes and "size" (size_x and size_y) is the corresponding size of those attributes.
> > If i'm not wrong, this buffer will have the bignum/bigint variants of X,Y rite?
> 
> No, if I'm not mistaken you will directly get the result as an octet string.
> 

> Meaning, i don't really have to call TEE_BigIntConvertToOctetString()?

> > What is the size that is returned by TEE_GetObjectBufferAttribute()?Is it the same as what TEE_BigIntGetBitCount() returns? or is it the ECC public key size?
> 
> It returns the minimal size in bytes needed for the buffer to hold the requested value. Typically, if you don't know the size in advance, you can call the function twice. First with `buffer == NULL` to get the size, the function will return `TEE_ERROR_SHORT_BUFFER` and return the size. Then you allocate a buffer of this size and call the function again to obtain the value. The function should return `TEE_SUCCESS`.

> OK
