### ISSUE TITLE
ldelf asserts on shared library built with Clang 10

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3802]
I met an issue with Clang 10 and the `os_test` TA (used by `xtest 1006` among others). `os_test` is linked with the `os_test_lib` shared library, and `ldelf` fails to map the shared lib. The error is:
```
E/LD:  assertion 'seg->flags & PF_W' failed at ldelf/ta_elf.c:552 in adjust_segments()
```
The library is like so:
```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000001c0 0x00000000000001c0  R      0x8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000001110 0x0000000000001110  R      0x1000
  LOAD           0x0000000000001110 0x0000000000002110 0x0000000000002110
                 0x0000000000000340 0x0000000000000340  R E    0x1000
  LOAD           0x0000000000001450 0x0000000000003450 0x0000000000003450
                 0x0000000000000130 0x0000000000000130  RW     0x1000
  LOAD           0x0000000000001580 0x0000000000004580 0x0000000000004580
                 0x0000000000000030 0x0000000000000030  RW     0x1000
  DYNAMIC        0x0000000000001458 0x0000000000003458 0x0000000000003458
                 0x0000000000000120 0x0000000000000120  RW     0x8
  GNU_RELRO      0x0000000000001450 0x0000000000003450 0x0000000000003450
                 0x0000000000000130 0x0000000000000bb0  R      0x1
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x0
```

While with Clang 9 it is like so:
```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x00000000000001c0 0x00000000000001c0  R      0x8
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000001110 0x0000000000001110  R      0x1000
  LOAD           0x0000000000002000 0x0000000000002000 0x0000000000002000
                 0x0000000000000340 0x0000000000000340  R E    0x1000
  LOAD           0x0000000000003000 0x0000000000003000 0x0000000000003000
                 0x0000000000000130 0x0000000000000130  RW     0x1000
  LOAD           0x0000000000004000 0x0000000000004000 0x0000000000004000
                 0x0000000000000030 0x0000000000000030  RW     0x1000
  DYNAMIC        0x0000000000003008 0x0000000000003008 0x0000000000003008
                 0x0000000000000120 0x0000000000000120  RW     0x8
  GNU_RELRO      0x0000000000003000 0x0000000000003000 0x0000000000003000
                 0x0000000000000130 0x0000000000001000  R      0x1
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x0
```

So the main difference is the VA for the PT_LOAD segments are always paged-aligned with Clang9 while they are not with Clang 10. I can see that this "overlap" case is partially handled but I don't understand why we require the segment be writable to proceed?

I would very much like to fix `ldelf` rather than the library, because I think fixing the library would require writing a linker script, and at the moment we don't have such a script which is good in my opinion (avoid adding to much complexity and restrictions on the TA format).

@jenswi-linaro opinion? Thanks!

**Comment by jenswi-linaro** [comment]
Which of the segments is it that is causing this assert()?

"Case 2" is supposed to handle the case where the same page in the elf is needed at two different addresses. Perhaps first as a R/O page with the first bytes, and then as a R/W page with the last bytes. To avoid aliasing we're allocating a new writable page and initialize it with the page from the original page.

Here I'm not sure what we're facing yet.

**Comment by jforissier** [comment]
It is the 2nd segment:
```
D/LD:  adjust_segments:510 prev_seg: vaddr=0x0 memsz=0x1110 offset=0x0
D/LD:  adjust_segments:512 seg: vaddr=0x2110 memsz=0x340 offset=0x1110
E/LD:  assertion 'seg->flags & PF_W' failed at ldelf/ta_elf.c:555 in adjust_segments()
```

**Comment by jenswi-linaro** [comment]
I think that removing the assert() should make it work. For clarity we should rename `remapped_writeable` to just `remapped`.

**Comment by jenswi-linaro** [comment]
We may need to do something about this "remapped" situation to ensure that it's only as few pages as possible, that is, the two overlapping that are handled like this.

**Comment by jforissier** [comment]
> I think that removing the assert() should make it work. For clarity we should rename `remapped_writeable` to just `remapped`.

With the assert removed it goes further but then:
```
E/LD:  check_range:201 .dynstr/STRTAB 0x0 out of range
```
We're reading garbage when we parse the dynamic segment, which does not seem to be mapped where we think it should be.

**Comment by jenswi-linaro** [comment]
Ouch, it seems we need to reevaluate some assumptions about the segments. This new clang seems to fill up the pages in the binary file as much as possible.

**Comment by jforissier** [comment]
> This new clang seems to fill up the pages in the binary file as much as possible.

Exactly. The size of the file `libos_test.stripped.so` is 29280 bytes with Clang9, and only 6832 bytes with Clang10!

**Comment by jenswi-linaro** [comment]
There we have it. Do you feel up to the task of fixing this or should I take care of it? It would be nice to have this sorted before the release, but I guess there's no real urgency.

**Comment by jforissier** [comment]
> There we have it. Do you feel up to the task of fixing this or should I take care of it? 

You read my mind :wink: I don't feel comfortable at all touching this mapping code... so if you could take care of it it would be great.

> It would be nice to have this sorted before the release, but I guess there's no real urgency.

Agreed. Our Clang support is still experimental.

**Comment by jbech-linaro** [comment]
> > It would be nice to have this sorted before the release, but I guess there's no real urgency.
> 
> Agreed. Our Clang support is still experimental.

Yes and no (to urgency), AOSP have completely got rid of GCC, however the optee_os.git can still be treated a bit different since it's firmware, so it's "OK" to build it on your own with GCC. But there are discussions (very recent) about setting up mirrors in AOSP for all optee-gits, so that an AOSP + OP-TEE build should be a bit more user friendly and coherent.

**Comment by jforissier** [comment]
@jbech-linaro good to know, so I guess at some point we should run a Clang config in our CI, too? I mean run `xtest`, not just do some compile-testing like we have in Shippable already.

I have done a few tests and as far as I can tell, currently everything should work well with Clang 9, the only exception being `CFG_WITH_PAGER=y` which needs some special flags/hacks to use the GCC linker. Then when this issue is fixed, Clang 10 should work equally well, and Clang 11 even better (no hack needed even with pager enabled).

**Comment by jbech-linaro** [comment]
I could setup a clang toolchain for one of the two jobs I'm running in IBART. Either QEMU or HiKey. In fact I can add another job if needed, but every new job adds ~10 minute run-time. Right now it'd be possible, the queue isn't filling up. But we should try to keep it around 30 minute, not much more than that.

**Comment by jforissier** [comment]
Removing the stale label.

There is a workaround other than adding a linker script: use the `-z separate-loadable-segments` [linker flag](https://manpages.debian.org/experimental/lld-10/ld.lld-10.1.en.html#separate-loadable-segments) when creating the shared library. However this is not supported by all linkers and therefore we would have to introduce a mechanism to add it only when supported.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/3898

**Comment by jforissier** [comment]
Removing the stale label because it would be nice to improve this thing. No urgency since a workaround was committed.

**Comment by jforissier** [comment]
Closing since workaround was merged.
