### ISSUE TITLE
Getting a optee project onto a board

### ISSUE THREAD

**Issue by zacchaeusliang** [OP-TEE/optee_os#3803]
I got the ta application to compile and all the approprate files have been generated. 
I have a few questions. 

i get an error where the ta dev kit is not found is that ok the binary was generated 
I used this command to get build for my hikey would it work because i'm not building for qemu
make \
>     CROSS_COMPILE=arm-linux-gnueabihf- \
>     PLATFORM=hikey\
>     TA_DEV_KIT_DIR=/home/zack-optee/optee_os/out/arm/export-ta_arm32

also where do it put the compiled files?

**Comment by jbech-linaro** [comment]
https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-do-i-port-op-tee-to-another-platform

**Comment by zacchaeusliang** [comment]
sorry i had more to write and i committed early

**Comment by zacchaeusliang** [comment]
i'm not looking port the os to another platform

**Comment by Raincode** [comment]
> 
> Q: Where should I put my compiled Trusted Application on the device?
> 
>         /lib/optee_armtz, that is the default location where tee-supplicant will look for Trusted Applications.
> 

CA goes into /usr/bin

I personally suggest trying hello_world from optee_examples to troubleshoot, since it should build and run without errors.
