### ISSUE TITLE
 load dynamic TA failure from REE

### ISSUE THREAD

**Issue by icesigma** [OP-TEE/optee_os#3805]
Hi , 
    I am trying to execute TA such as optee_example_hello_world but I got the failure like the following:
```
/ # optee_example_hello_world
    D/OPTEE:? thread 0 tee_ta_init_pseudo_ta_session:284 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
    D/OPTEE:? thread 0 load_ldelf:704 ldelf load address 0x102000
    F/OPTEE:? thread 0 trace_syscall:127 syscall #1 (syscall_log)
    D/LD:  ldelf:134 Loading TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
    F/OPTEE:? thread 0 trace_syscall:127 syscall #5 (syscall_open_ta_session)
    D/OPTEE:? thread 0 tee_ta_init_pseudo_ta_session:284 Lookup pseudo TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
    D/OPTEE:? thread 0 tee_ta_init_pseudo_ta_session:297 Open system.pta
    D/OPTEE:? thread 0 tee_ta_init_pseudo_ta_session:311 system.pta : 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
    F/OPTEE:? thread 0 trace_syscall:127 syscall #7 (syscall_invoke_ta_command)
    F/OPTEE:? thread 0 trace_syscall:127 syscall #7 (syscall_invoke_ta_command)
    D/OPTEE:? thread 0 system_open_ta_binary:249 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
    D/OPTEE:? thread 0 system_open_ta_binary:253 res=0xf0100003
    D/OPTEE:? thread 0 system_open_ta_binary:249 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
    F/OPTEE:? thread 0 plat_prng_add_jitter_entropy:72 0x41
    D/OPTEE:? thread 0 system_open_ta_binary:253 res=0x0
    F/OPTEE:? thread 0 trace_syscall:127 syscall #7 (syscall_invoke_ta_command)
    F/OPTEE:? thread 0 trace_syscall:127 syscall #33 (syscall_cryp_random_number_generate)
    F/OPTEE:? thread 0 trace_syscall:127 syscall #7 (syscall_invoke_ta_command)
    F/OPTEE:? thread 0 trace_syscall:127 syscall #7 (syscall_invoke_ta_command)
    F/OPTEE:? thread 0 trace_syscall:127 syscall #7 (syscall_invoke_ta_command)
    F/OPTEE:? thread 0 trace_syscall:127 syscall #7 (syscall_invoke_ta_command)
    D/OPTEE:? thread 0 tee_ta_invoke_command:773 Error: f0100003 of 4
    F/OPTEE:? thread 0 trace_syscall:127 syscall #1 (syscall_log)
    E/LD:  copy_section_headers:785 sys_copy_from_ta_bin
    E/OPTEE:? thread 0 init_with_ldelf:233 ldelf failed with res: 0xf0100003
    D/OPTEE:? thread 0 tee_ta_close_session:498 csess 0x9d06dd40 id 1
    D/OPTEE:? thread 0 tee_ta_close_session:518 Destroy session
    D/OPTEE:? thread 0 destroy_context:298 Destroy TA ctx (0x9d06dd00)
    D/OPTEE:? thread 0 tee_ta_close_session:498 csess 0x9d06d960 id 1
    D/OPTEE:? thread 0 tee_ta_close_session:518 Destroy session
    E/OPTEE:? thread 0 tee_ta_open_session:728 Failed. Return error 0xf0100003
optee_example_hello_world: TEEC_Opensession failed with code 0xf0100003 origin 0x3
```
Here,
I got the error 0xf0100003 which means TEE_ERROR_STORAGE_NOT_AVAILABLE.
Accordinfg to messages (E/LD:  copy_section_headers:785 sys_copy_from_ta_bin) ,I follow this message to get the thought.
I used squashfs to be file system type .
Does it possible mean tee-supplicant open xxx.ta and transferred header to make it be failure ? If yes, have any idea to fix it to let header  formate match Tee-os needs under squashfs  format keeping ?

**Comment by jbech-linaro** [comment]
Squashfs from what I understand is a readonly filesystem, so for general usage I would imagine OP-TEE would complain quite a bit. The entire secure storage needs writable storage. However, I cannot see why hello world would fail, that TA in itself doesn't do any storage operations. @jenswi-linaro , does the new ELF loader to any kind of storage?

**Comment by jenswi-linaro** [comment]
The error is likely due to this call
https://github.com/OP-TEE/optee_os/blob/8731e19cf6fc48c86cbdcd63a6ca85c49a701f2c/core/arch/arm/kernel/ree_fs_ta.c#L494

**Comment by icesigma** [comment]
Hi @jenswi-linaro 
     Thanks for your reply,  I confirmed TEE_ERROR_STORAGE_NOT_AVAILABLE is from below function.  
https://github.com/OP-TEE/optee_os/blob/8731e19cf6fc48c86cbdcd63a6ca85c49a701f2c/core/arch/arm/kernel/ree_fs_ta.c#L341

But I still have no idea why.  Could you give me some advice?

**Comment by jenswi-linaro** [comment]
The TA verification expects to save the TA version number in secure storage. If secure storage isn't available, then it fails.

**Comment by icesigma** [comment]
Hi @jenswi-linaro 
       I have a question for that. If just load TA from REE, does it still need to save TA version on REE?  I thought load TA from REE that it just sent TA bin to TEE OS without writing any data on REE. 
I mean that it only save TA not to offer sescure storage function.
It seems odd to me. Do you have any document I could reference? 
Thus, for this topic,  I got some answer.
if filesystem is squashfs type, I can not use dynamic TA . Maybe I can use early TA instead of that. And then it must can not to be secure storage even though it provides only read function.
Have I got that right?

**Comment by jenswi-linaro** [comment]
A bootstrap TA has a version number which is checked and updated as needed in order to prevent a rollback attack. You can sign the TA as a legacy TA (which doesn't have a version number) instead and the problem should be avoided. A bit less secure though.

**Comment by icesigma** [comment]
Hi @jenswi-linaro 
     You mean I just remove  version code defined below.
https://github.com/linaro-swg/optee_examples/blob/master/hello_world/ta/user_ta_header_defines.h#L53

Load ta from REE will ignore version updating process. If yes, I'll try it.

**Comment by jenswi-linaro** [comment]
No, that's not the one. You'll need to update the sign script `scripts/sign_encrypt.py` to be able to produce a legacy signed TA.

**Comment by icesigma** [comment]
Hi @jenswi-linaro 
    Thanks for helping me. This sign process I never start to understand so I have to spend some time to study first.
