### ISSUE TITLE
TA VA space enlarging

### ISSUE THREAD

**Issue by Kztpia** [OP-TEE/optee_os#3814]
hi,
   how can i enlarge ta va space?
   I have a TA need to deal with large amount of data,  i found that my TA cannot access virtual address larger than 0x8000000. 
   I tried some modification on TTCCR_N_VALUE in core/arch/arm/mm/core_mmu_v7.c. 
   It seems that i can reduce va space from 0x8000000 to 0x4000000 by modifying it to 6
   but cannot enlarge va space by modifying it to a number less than 5.

# I test my modification in this way:
```
    1.modify TTCCR_N_VALUE
    2.add " core_init_mmu_map_dyn" 
      after "core_mmu_create_user_map" is called 
      in "tee_mmu_set_ctx"
      in core/arch/arm/mm/tee_mmu.c ,
      to manually map  mostly whole va space (like 0x2000000~)
    3.in a helloworld ta, read 0x2000000, 0x200ffe00, 0x2100000,0x21ffe00 .....
    4.data abort occure when ta access an address beyond va space
```

my test result is like:
       |  TTCCR_N_VALUE   | data-abort when accessing  |
|  ----  | ----  |
| 3 | 0x8000000 |
| 4 | 0x8000000 |
| 5  | 0x8000000 |
| 6  | 0x4000000 |

Maybe there is a hard coded limit besides TTCCR_N_VALUE that make TA VA space cannot be larger than 0x8000000?

**Comment by jenswi-linaro** [comment]
We have always used only `TTBCR_N_VALUE` set to `7` so there may very well be unintended limitations when decreasing that value.

**Comment by Kztpia** [comment]
@jenswi-linaro 
any helper functions for ul1 table debug? i found a "dump_xlat_table" in core_mmu.c, but it seems it only print L1 and L2 table, UL1 table not included

**Comment by jenswi-linaro** [comment]
> any helper functions for ul1 table debug? i found a "dump_xlat_table" in core_mmu.c, but it seems it only print L1 and L2 table, UL1 table not included

I'm afraid you're on your own there.

**Comment by Kztpia** [comment]
I used some legacy codes to do the manually mapping. Those codes hard coded a limit of 0x8000000 and I didn't notice it.
After removing that limit, TTCCR_N_VALUE works perfectly as expected.
