### ISSUE TITLE
normal world not booting after OPTEE integration on imx6dl

### ISSUE THREAD

**Issue by ncpsa** [OP-TEE/optee_os#3816]
Hello Team,
Hope everyone is good and safe.
I am doing OPTEE porting on IMX6DL platform. OPTEE is up and running, but OPTEE is not switching back to normal world kernel.
If I make SMC call as dummy from Normal world, then kernel is booting, But failing in PSCI & secondary core enabling since call will not reach to OPTEE.
I have seen PSCI 0.2 support in drivers/firmware/psci.c file as well as I have added psci compatible in dtb.
What could be an issue here? could anyone help?

Thanks in Advance.

Regards,

**Comment by ncpsa** [comment]
Hello Guys,
Could anyone help here?
Kernel hangs in PSCI calls, seems SMC is stuck somewhere, it is not reaching secure monitor.

Thanks in Advance.

**Comment by MrVan** [comment]
@ncpsa  Try only booting one cpu and enable earlyprintk. Then try booting secondary cpus.

**Comment by Thekku** [comment]
@MrVan  With one core it is booting, but none of the SMC call (either get psci version or secondary core enable ) is not reaching to OPTEE. Enabled the configs 
CONFIG_TEE=y
CONFIG_OPTEE=y
CONFIG_ARM_PSCI_FW=y
CONFIG_HAVE_ARM_SMCCC=y

Any reason for SMC call not working ? Any other configs is missing?
