### ISSUE TITLE
Get page in OP-TEE by physical address from NWD

### ISSUE THREAD

**Issue by anisyanka** [OP-TEE/optee_os#3822]
Hello!
In my test-project i need to calculate sha256 for some non-secure memory range.
My NWD is the Linux kernel.

For this task i have written linux kernel module. The one sends physical address and length of continiously range for sha256 calculation to optee with help SMC-interface. It looks like:
```
uint32_t optee_protect_range(insigned long pa, unsigned long pa_len);
uint32_t optee_unprotect_range(insigned long pa);
```
When i get this range into optee core, i need to map memory to kernel. I use this API for it:
```
bool core_mmu_add_mapping(enum teecore_memtypes type, paddr_t addr, size_t len);
```
After this Linux kernel timer will trig op-tee for re-calculation sha256.
But when i want to unproctect some memory range, i have to un-map previously mapped region, but it seems, that OP-TEE has no API to dynamic un-mapping?

I have found this information into:
https://github.com/OP-TEE/optee_os/issues/1343
https://github.com/OP-TEE/optee_os/issues/2453

That's why i want to use this API for my task:
```
TEE_Result core_mmu_map_pages(vaddr_t vstart, paddr_t *pages, size_t num_pages, enum teecore_memtypes memtype);
void core_mmu_unmap_pages(vaddr_t vstart, size_t num_pages);
```

But I can't understand how should i get VA and page by PA from NWD.
Is there API like `phys_to_page()` into op-tee ?

Best regards.

**Comment by jenswi-linaro** [comment]
Something seems to be missing here. Why do you need to protect and map the memory in order to calculate a sha256? Why do secure world need to be involved at all?

**Comment by anisyanka** [comment]
Thank you for reply. 

I want to try to check integrity some of pieces of Linux kernel during runtime. For example: crypto keys or certificates. 

Like in LKRG project(https://www.openwall.com/lkrg/), but in TEE side.

**Comment by anisyanka** [comment]
In optee I use tomcrypt library to calculate hash and I need to use virtual addresses,  but how can I get the one? 

I think that one can find real page by real physical address and than use optee API to map a page.

**Comment by etienne-lms** [comment]
Maybe your linux kernel can register the virtual buffer as shared memory into TEE and then invoke the SHA service providing the shared memory reference.
OP-TEE linux driver will take care of virt-to-phys conversion before registering the shared memory buffer.
OP-TEE (secure) core will map the buffer when SHA service is invoked and unmap the buffer once SHA service invocation completes.

**Comment by anisyanka** [comment]
@etienne-lms, thank you for your advice.
Yes, it seems will work, but it requires a lot of refactoring of my current version of code :) But, it doesn't matter. 

Current version of "sha-service"  is two new APIs (protect/unprotect) in optee driver. The APIs only for linux kernel modules and the one use separate function-id into SMC call.

OP-TEE linux driver uses `static int tee_ioctl_shm_register(...)` to register shared memory. Currently i can't use this API directly.

I think about un-map ability into OP-TEE.
Maybe we need to do new API to un-map memory regions?
Maybe refactoring of the `core_mmu_add_mapping()` for dynamic mapping/un-mapping ability, or it is a bad idea?

**Comment by etienne-lms** [comment]
> OP-TEE linux driver uses static int tee_ioctl_shm_register(...) to register shared memory. Currently i can't use this API directly.

Any reason why?

> Current version of "sha-service" is two new APIs (protect/unprotect) in optee driver. The APIs only for linux kernel modules and the one use separate function-id into SMC call.

I don't catch. Do you need this service from Linux kernel land or userland?
You should be able to register shared memory from both worlds: `TEEC_RegisterSharedMemory()` in userland, `tee_shm_register()` in kernel land.

As for a new specific TEE service, strongly prefer implementing it through a TA (or PTA) rather than introducing new SMC function IDs. This simplifies many things among which memory reference arguments.

**Comment by anisyanka** [comment]
> Do you need this service from Linux kernel land or userland?

I need it from kernel land. I will try to use `tee_shm_register()`.

>  implementing it through a TA (or PTA)

Thank you, I will try.
