### ISSUE TITLE
TEEC_Opensession failed with code 0xffff0000 origin 0x3 - (TA will panic)

### ISSUE THREAD

**Issue by sckulkarni246** [OP-TEE/optee_os#3825]
Hello OP-TEE team,

**Platform:** sam
**optee-os commit**: a58c4d706d2333d2b21a3eba7e2ec0cb257bca1d

**Background:**
I recently added a static library to my TA by adding the .a static library to export-ta_arm32/lib and adding libnames and libdeps to export-ta_arm32/mk/ta_dev_kit.mk

**Error:**
<pre>D/TC:? 0 tee_ta_init_pseudo_ta_session:284 Lookup pseudo TA 213fa7f3-4c52-4018-9114-7fdd
D/TC:? 0 load_ldelf:703 ldelf load address 0x104000
D/LD:  ldelf:134 Loading TA 213fa7f3-4c52-4018-9114-7fdc2677833d
D/TC:? 0 tee_ta_init_session_with_context:573 Re-open TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 system_open_ta_binary:257 Lookup user TA ELF 213fa7f3-4c52-4018-9114-7fdc2677833d (Secure Storage TA)
D/TC:? 0 system_open_ta_binary:260 res=0xffff0008
D/TC:? 0 system_open_ta_binary:257 Lookup user TA ELF 213fa7f3-4c52-4018-9114-7fdc2677833d (REE)
D/TC:? 0 system_open_ta_binary:260 res=0x0
D/TC:0 0 abort_handler:524 [abort] abort in User mode (TA will panic)
E/TC:? 0 
E/TC:? 0 User TA data-abort at address 0x12cc40 (write permission fault)
E/TC:? 0  fsr 0x0000080f  ttbr0 0x3008a459  ttbr1 0x30084059  cidr 0x2
E/TC:? 0  cpu #0          cpsr 0x60000130
E/TC:? 0  r0 0x00000008      r4 0x0010e088    r8 0x0010e0b0   r12 0x00000000
E/TC:? 0  r1 0x00143000      r5 0x0010d7a8    r9 0x00000000    sp 0x00103ee8
E/TC:? 0  r2 0x0012b699      r6 0x0010d7a4   r10 0x00000000    lr 0x001074b1
E/TC:? 0  r3 0x0012cc40      r7 0x00103ef0   r11 0x00000000    pc 0x00107780
E/TC:? 0  region  0: va 0x00100000 pa 0x30000000 size 0x001000 flags ---R-X
E/TC:? 0  region  1: va 0x00102000 pa 0x30100000 size 0x002000 flags rw-RW-
E/TC:? 0  region  2: va 0x00104000 pa 0x30102000 size 0x00a000 flags r-x---
E/TC:? 0  region  3: va 0x0010e000 pa 0x3010c000 size 0x001000 flags rw-RW-
E/TC:? 0  region  4: va 0x0010f000 pa 0x3010d000 size 0x003000 flags rw-RW-
E/TC:? 0  region  5: va 0x00112000 pa 0x30110000 size 0x001000 flags r--R--
E/TC:? 0  region  6: va 0x00113000 pa 0x30132000 size 0x001000 flags rw-RW-
E/TC:? 0  region  7: va 0x00122000 pa 0x30111000 size 0x015000 flags r-xR--
E/TC:? 0  region  8: va 0x00137000 pa 0x30126000 size 0x00c000 flags rw-RW-
E/TC:? 0 init_with_ldelf:228 ldelf panicked
D/TC:? 0 tee_ta_close_session:499 csess 0x30081988 id 1
D/TC:? 0 tee_ta_close_session:518 Destroy session
D/TC:? 0 destroy_context:298 Destroy TA ctx (0x30081948)
D/TC:? 0 tee_ta_close_session:499 csess 0x30081580 id 1
D/TC:? 0 tee_ta_close_session:518 Destroy session
E/TC:? 0 tee_ta_open_session:728 Failed. Return error 0xffff0000</pre>

Issues referred to before posting new issue:
Issue 3577 - https://github.com/OP-TEE/optee_os/issues/3577 

**Readelf output of TA:**
<pre>There are 32 section headers, starting at offset 0x5fbf4:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .ta_head          PROGBITS        00000000 001000 000020 00   A  0   0  8
  [ 2] .text             PROGBITS        00000020 001020 011c0a 00  AX  0   0  4
  [ 3] .rodata           PROGBITS        00011c2c 012c2c 00119a 00   A  0   0  4
  [ 4] .gnu.hash         GNU_HASH        00012dc8 013dc8 000020 04   A  7   0  4
  [ 5] .ARM.extab        PROGBITS        00012de8 013de8 000acc 00   A  0   0  4
  [ 6] .ARM.exidx        ARM_EXIDX       000138b4 0148b4 0007b8 00  AL  2   0  4
  [ 7] .dynsym           DYNSYM          0001406c 01506c 000040 10   A  8   3  4
  [ 8] .dynstr           STRTAB          000140ac 0150ac 000012 00   A  0   0  1
  [ 9] .hash             HASH            000140c0 0150c0 00001c 04   A  7   0  4
  [10] .dynamic          DYNAMIC         00015000 016000 000090 08  WA  8   0  4
  [11] .got              PROGBITS        00015090 016090 000048 04  WA  0   0  4
  [12] .rel.text         REL             000150d8 0160d8 000078 08  AI  7   2  4
  [13] .rel.got          REL             00015200 016200 000078 08  AI  7  11  4
  [14] .data             PROGBITS        00015278 016278 000094 00  WA  0   0  4
  [15] .bss              NOBITS          0001530c 01630c 00b10c 00  WA  0   0  4
  [16] .debug_info       PROGBITS        00000000 01630c 00ad86 00      0   0  1
  [17] .debug_abbrev     PROGBITS        00000000 021092 002309 00      0   0  1
  [18] .debug_aranges    PROGBITS        00000000 0233a0 000590 00      0   0  8
  [19] .debug_macro      PROGBITS        00000000 023930 01591c 00      0   0  1
  [20] .debug_line       PROGBITS        00000000 03924c 007f89 00      0   0  1
  [21] .debug_str        PROGBITS        00000000 0411d5 014364 01  MS  0   0  1
  [22] .comment          PROGBITS        00000000 055539 000055 01  MS  0   0  1
  [23] .ARM.attributes   ARM_ATTRIBUTES  00000000 05558e 000033 00      0   0  1
  [24] .arm_vfe_header   PROGBITS        00000000 0555c4 000004 00      0   0  4
  [25]                   PROGBITS        00000000 0555c8 000bd4 00      0   0  1
  [26] .debug_frame      PROGBITS        00000000 05619c 003364 00      0   0  4
  [27] .rel.dyn          REL             00015150 016150 0000b0 08   A  7   0  4
  [28] .debug_ranges     PROGBITS        00000000 059500 000230 00      0   0  8
  [29] .symtab           SYMTAB          00000000 059730 0044c0 10     30 825  4
  [30] .strtab           STRTAB          00000000 05dbf0 001ee4 00      0   0  1
  [31] .shstrtab         STRTAB          00000000 05fad4 00011d 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  y (purecode), p (processor specific)

Elf file type is DYN (Shared object file)
Entry point 0x378
There are 5 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  EXIDX          0x0148b4 0x000138b4 0x000138b4 0x007b8 0x007b8 R   0x4
  LOAD           0x001000 0x00000000 0x00000000 0x140dc 0x140dc R E 0x1000
  LOAD           0x016000 0x00015000 0x00015000 0x0030c 0x0b418 RW  0x1000
  DYNAMIC        0x016000 0x00015000 0x00015000 0x00090 0x00090 RW  0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RWE 0x10

 Section to Segment mapping:
  Segment Sections...
   00     .ARM.exidx 
   01     .ta_head .text .rodata .gnu.hash .ARM.extab .ARM.exidx .dynsym .dynstr .hash 
   02     .dynamic .got .rel.text .rel.got .data .bss .rel.dyn 
   03     .dynamic 
   04     

Relocation section &apos;.rel.text&apos; at offset 0x160d8 contains 15 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
0000ac40  00000017 R_ARM_RELATIVE   
0000ac44  00000017 R_ARM_RELATIVE   
0000ac48  00000017 R_ARM_RELATIVE   
0000b34c  00000017 R_ARM_RELATIVE   
0000b350  00000017 R_ARM_RELATIVE   
0000b354  00000017 R_ARM_RELATIVE   
0000b7cc  00000017 R_ARM_RELATIVE   
0000b7e4  00000017 R_ARM_RELATIVE   
0000be00  00000017 R_ARM_RELATIVE   
0000be04  00000017 R_ARM_RELATIVE   
0000be08  00000017 R_ARM_RELATIVE   
0000be0c  00000017 R_ARM_RELATIVE   
0000c10c  00000017 R_ARM_RELATIVE   
0000c110  00000017 R_ARM_RELATIVE   
0000c114  00000017 R_ARM_RELATIVE   

Relocation section &apos;.rel.got&apos; at offset 0x16200 contains 15 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
000150a4  00000017 R_ARM_RELATIVE   
000150cc  00000017 R_ARM_RELATIVE   
000150a0  00000017 R_ARM_RELATIVE   
000150a8  00000017 R_ARM_RELATIVE   
000150bc  00000017 R_ARM_RELATIVE   
0001509c  00000017 R_ARM_RELATIVE   
000150b4  00000017 R_ARM_RELATIVE   
000150c0  00000017 R_ARM_RELATIVE   
000150c8  00000017 R_ARM_RELATIVE   
000150d0  00000017 R_ARM_RELATIVE   
000150d4  00000017 R_ARM_RELATIVE   
000150b0  00000017 R_ARM_RELATIVE   
000150b8  00000017 R_ARM_RELATIVE   
000150ac  00000017 R_ARM_RELATIVE   
000150c4  00000017 R_ARM_RELATIVE   

Relocation section &apos;.rel.dyn&apos; at offset 0x16150 contains 22 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
0001527c  00000017 R_ARM_RELATIVE   
00015284  00000017 R_ARM_RELATIVE   
00015288  00000017 R_ARM_RELATIVE   
00015290  00000017 R_ARM_RELATIVE   
00015294  00000017 R_ARM_RELATIVE   
0001529c  00000017 R_ARM_RELATIVE   
000152a0  00000017 R_ARM_RELATIVE   
000152a8  00000017 R_ARM_RELATIVE   
000152ac  00000017 R_ARM_RELATIVE   
000152b4  00000017 R_ARM_RELATIVE   
000152b8  00000017 R_ARM_RELATIVE   
000152c0  00000017 R_ARM_RELATIVE   
000152c4  00000017 R_ARM_RELATIVE   
000152cc  00000017 R_ARM_RELATIVE   
000152d0  00000017 R_ARM_RELATIVE   
000152d8  00000017 R_ARM_RELATIVE   
000152dc  00000017 R_ARM_RELATIVE   
000152e4  00000017 R_ARM_RELATIVE   
000152ec  00000017 R_ARM_RELATIVE   
000152f0  00000017 R_ARM_RELATIVE   
000152fc  00000017 R_ARM_RELATIVE   
00015300  00000017 R_ARM_RELATIVE</pre>

Any pointers on how I can proceed ahead? I referred to issue 3577 as that had a similar error however it seems that was due to having init_array in the elf file. I am not using C++ and don't have init_array in the elf.

Regards,
Shashank

**Comment by jforissier** [comment]
Hello @sckulkarni246,

It looks like your TA has "text relocations" which is not supported (and is usually a "bad thing"). It typically happens when some code is not compiled with `-fPIC`, and later linked into a relocatable executable (such as an OP-TEE TA). Can you please check how your static library is compiled?

FYI a similar issue was reported in https://github.com/OP-TEE/optee_os/issues/3711.

**Comment by sckulkarni246** [comment]
Hello @jforissier ,

Thank you for your reply - I will check on this and update you here.

Regards,
Shashank

**Comment by sckulkarni246** [comment]
Hello @jforissier ,

I received an updated library from the backend team (I am just an application developer). I checked the md5sum of both and they are different so replaced old one with this library and did a build again.
However, the issue is exactly the same with the same offset (0xac40). To ensure that fPIC was indeed used, I did an objdump of the old and the new elf. I do see a difference (FPIC) in the buildattributes.

Old library:
`000959c t BuildAttributes$$THM_ISAv4$ARM_ISAv7$X$E$P$J$Z$K$B$S$PE$MPE$A:L22UL41UL21$X:L11$S22US41US21$IEEE1$IW$USESV6$~STKCKD$USESV7$~SHL$OTIME$ROPI$EBA8$REQ8$PRES8$EABIv2
000095ba t 
000095d4 t 
00009614 t BuildAttributes$$THM_ISAv4$ARM_ISAv7$X$E$P$J$Z$K$B$S$PE$MPE$A:L22UL41UL21$X:L11$S22US41US21$IEEE1$IW$USESV6$~STKCKD$USESV7$~SHL$OSPACE$ROPI$EBA8$PRES8$EABIv2`

New library:
`0000959c t 
0000959c t BuildAttributes$$THM_ISAv4$ARM_ISAv7$X$E$P$J$Z$K$B$S$PE$MPE$A:L22UL41UL21$X:L11$S22US41US21$IEEE1$IW$USESV6$~STKCKD$USESV7$~SHL$OTIME$ROPI$EBA8$FPIC$INDIRECT$REQ8$PRES8$EABIv2
000095ba t 
000095d4 t 
00009614 t BuildAttributes$$THM_ISAv4$ARM_ISAv7$X$E$P$J$Z$K$B$S$PE$MPE$A:L22UL41UL21$X:L11$S22US41US21$IEEE1$IW$USESV6$~STKCKD$USESV7$~SHL$OSPACE$ROPI$EBA8$FPIC$INDIRECT$PRES8$EABIv2`

Also, the readelf output still has the .rel.text section. See output below.
<pre>There are 32 section headers, starting at offset 0x5fdd8:

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .ta_head          PROGBITS        00000000 001000 000020 00   A  0   0  8
  [ 2] .text             PROGBITS        00000020 001020 011c08 00  AX  0   0  4
  [ 3] .rodata           PROGBITS        00011c28 012c28 00119a 00   A  0   0  4
  [ 4] .gnu.hash         GNU_HASH        00012dc4 013dc4 000020 04   A  7   0  4
  [ 5] .ARM.extab        PROGBITS        00012de4 013de4 000acc 00   A  0   0  4
  [ 6] .ARM.exidx        ARM_EXIDX       000138b0 0148b0 0007b8 00  AL  2   0  4
  [ 7] .dynsym           DYNSYM          00014068 015068 000040 10   A  8   3  4
  [ 8] .dynstr           STRTAB          000140a8 0150a8 000012 00   A  0   0  1
  [ 9] .hash             HASH            000140bc 0150bc 00001c 04   A  7   0  4
  [10] .dynamic          DYNAMIC         00015000 016000 000090 08  WA  8   0  4
  [11] .got              PROGBITS        00015090 016090 000048 04  WA  0   0  4
  [12] .rel.text         REL             000150d8 0160d8 000078 08  AI  7   2  4
  [13] .rel.got          REL             00015200 016200 000078 08  AI  7  11  4
  [14] .data             PROGBITS        00015278 016278 000094 00  WA  0   0  4
  [15] .bss              NOBITS          0001530c 01630c 00b10c 00  WA  0   0  4
  [16] .debug_info       PROGBITS        00000000 01630c 00ad86 00      0   0  1
  [17] .debug_abbrev     PROGBITS        00000000 021092 002309 00      0   0  1
  [18] .debug_aranges    PROGBITS        00000000 0233a0 000590 00      0   0  8
  [19] .debug_macro      PROGBITS        00000000 023930 01591c 00      0   0  1
  [20] .debug_line       PROGBITS        00000000 03924c 007f89 00      0   0  1
  [21] .debug_str        PROGBITS        00000000 0411d5 014364 01  MS  0   0  1
  [22] .comment          PROGBITS        00000000 055539 000055 01  MS  0   0  1
  [23] .ARM.attributes   ARM_ATTRIBUTES  00000000 05558e 000039 00      0   0  1
  [24] .arm_vfe_header   PROGBITS        00000000 0555c8 000004 00      0   0  4
  [25]                   PROGBITS        00000000 0555cc 000d80 00      0   0  1
  [26] .debug_frame      PROGBITS        00000000 05634c 0032b4 00      0   0  4
  [27] .rel.dyn          REL             00015150 016150 0000b0 08   A  7   0  4
  [28] .debug_ranges     PROGBITS        00000000 059600 000230 00      0   0  8
  [29] .symtab           SYMTAB          00000000 059830 0044d0 10     30 826  4
  [30] .strtab           STRTAB          00000000 05dd00 001fb9 00      0   0  1
  [31] .shstrtab         STRTAB          00000000 05fcb9 00011d 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  y (purecode), p (processor specific)

Elf file type is DYN (Shared object file)
Entry point 0x378
There are 5 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  EXIDX          0x0148b0 0x000138b0 0x000138b0 0x007b8 0x007b8 R   0x4
  LOAD           0x001000 0x00000000 0x00000000 0x140d8 0x140d8 R E 0x1000
  LOAD           0x016000 0x00015000 0x00015000 0x0030c 0x0b418 RW  0x1000
  DYNAMIC        0x016000 0x00015000 0x00015000 0x00090 0x00090 RW  0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RWE 0x10

 Section to Segment mapping:
  Segment Sections...
   00     .ARM.exidx 
   01     .ta_head .text .rodata .gnu.hash .ARM.extab .ARM.exidx .dynsym .dynstr .hash 
   02     .dynamic .got .rel.text .rel.got .data .bss .rel.dyn 
   03     .dynamic 
   04     

Relocation section &apos;.rel.text&apos; at offset 0x160d8 contains 15 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
0000ac40  00000017 R_ARM_RELATIVE   
0000ac44  00000017 R_ARM_RELATIVE   
0000ac48  00000017 R_ARM_RELATIVE   
0000b34c  00000017 R_ARM_RELATIVE   
0000b350  00000017 R_ARM_RELATIVE   
0000b354  00000017 R_ARM_RELATIVE   
0000b7cc  00000017 R_ARM_RELATIVE   
0000b7e4  00000017 R_ARM_RELATIVE   
0000be00  00000017 R_ARM_RELATIVE   
0000be04  00000017 R_ARM_RELATIVE   
0000be08  00000017 R_ARM_RELATIVE   
0000be0c  00000017 R_ARM_RELATIVE   
0000c10c  00000017 R_ARM_RELATIVE   
0000c110  00000017 R_ARM_RELATIVE   
0000c114  00000017 R_ARM_RELATIVE   

Relocation section &apos;.rel.got&apos; at offset 0x16200 contains 15 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
000150a4  00000017 R_ARM_RELATIVE   
000150cc  00000017 R_ARM_RELATIVE   
000150a0  00000017 R_ARM_RELATIVE   
000150a8  00000017 R_ARM_RELATIVE   
000150bc  00000017 R_ARM_RELATIVE   
0001509c  00000017 R_ARM_RELATIVE   
000150b4  00000017 R_ARM_RELATIVE   
000150c0  00000017 R_ARM_RELATIVE   
000150c8  00000017 R_ARM_RELATIVE   
000150d0  00000017 R_ARM_RELATIVE   
000150d4  00000017 R_ARM_RELATIVE   
000150b0  00000017 R_ARM_RELATIVE   
000150b8  00000017 R_ARM_RELATIVE   
000150ac  00000017 R_ARM_RELATIVE   
000150c4  00000017 R_ARM_RELATIVE   

Relocation section &apos;.rel.dyn&apos; at offset 0x16150 contains 22 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
0001527c  00000017 R_ARM_RELATIVE   
00015284  00000017 R_ARM_RELATIVE   
00015288  00000017 R_ARM_RELATIVE   
00015290  00000017 R_ARM_RELATIVE   
00015294  00000017 R_ARM_RELATIVE   
0001529c  00000017 R_ARM_RELATIVE   
000152a0  00000017 R_ARM_RELATIVE   
000152a8  00000017 R_ARM_RELATIVE   
000152ac  00000017 R_ARM_RELATIVE   
000152b4  00000017 R_ARM_RELATIVE   
000152b8  00000017 R_ARM_RELATIVE   
000152c0  00000017 R_ARM_RELATIVE   
000152c4  00000017 R_ARM_RELATIVE   
000152cc  00000017 R_ARM_RELATIVE   
000152d0  00000017 R_ARM_RELATIVE   
000152d8  00000017 R_ARM_RELATIVE   
000152dc  00000017 R_ARM_RELATIVE   
000152e4  00000017 R_ARM_RELATIVE   
000152ec  00000017 R_ARM_RELATIVE   
000152f0  00000017 R_ARM_RELATIVE   
000152fc  00000017 R_ARM_RELATIVE   
00015300  00000017 R_ARM_RELATIVE  </pre>

The hello-world example runs correctly for me so the issue is definitely with this library. I did an objdump on the hello world TA elf and found symbols like utee_open_ta_session, etc. I then decided to provide the same arguments that optee-os uses for building the libutee.a to my backend team so that they can use the same and build the library that I need. However, due to my lack of knowledge on reading complex Makefiles, I am not able to find the exact place where libutee.a gets built. 

Could you help me with locating the place where libutee gets built so that I will pass the same to my backend team? Also, there was an error with the mfloat-abi flag that I suppressed using --noinhibit-exec - does the OPTEE by default use mfloat-abi=hard?

Regards,
Shashank

**Comment by sckulkarni246** [comment]
Hi @jforissier ,

Another info in case it is relevant - the objdump of hello world doesn't have any build attributes in it like I shared in the previous comment for my library. Is there something fundamentally wrong with the way the library may be getting built by the backend team?
This is a company IP so I am not able to share more info about the code with you - excuse me for this.

Do let me know if more info is needed.

Regards,
Shashank

**Comment by jforissier** [comment]
> I then decided to provide the same arguments that optee-os uses for building the libutee.a to my backend team

With this command you can see what flags are used when building `libutee.a`:
```
$ make V=1 | grep 'tee_api_objects\.o'
```

> Also, there was an error with the mfloat-abi flag that I suppressed using --noinhibit-exec

Huh, this sounds **bad**.

> - does the OPTEE by default use mfloat-abi=hard?

Yes, but you should be able to use mfloat-abi=soft by setting `CFG_TA_ARM32_NO_HARD_FLOAT_SUPPORT=y`.

**Comment by jforissier** [comment]
And BTW just to confirm, I'm quite sure it won't work unless you can get rid of the `.rel.text` section, so you need to focus on that.

**Comment by jforissier** [comment]
One other thing: perhaps your team should consider using the OP-TEE "TA dev kit" to build their library, because it will normally set all the needed flags automatically. For example see the `optee_test` project is built. Unfortunately no example of a static library, only a dynamic one but if you change `SHLIBNAME` to `LIBNAME` here: https://github.com/OP-TEE/optee_test/blob/3.8.0/ta/os_test_lib/Makefile#L5 it will build a `.a` static library.

**Comment by sckulkarni246** [comment]
Hi @jforissier ,

Thank you for the response. I will get back to you with updates on this issue.

Regards,
Shashank

**Comment by sckulkarni246** [comment]
Hi @jforissier ,

I have an update for you. I have been given access to some of the source code to be added to the OPTEE. I also have the makefile to build the static library for the same. However, I noticed that the source code contains both C code (*.c) and assembly code (*.S) that does some calculations/processing using the ARM registers (r0, r1,..., lr, sp, pc,..). **Will assembly be a problem?**

I plan to do the below:

- Add the entire source code (say libmycustom/) to optee/lib
- Add a sub.mk inside it similar to the one inside libmbedtls or one of the existing ones

**Is there an official guide/reference issue for adding external source code to optee/lib, generating a static lib and compiling it?** I traversed the issues with several keywords but could not find info in this regard.

Regards,
Shashank

**Comment by jforissier** [comment]
Hi @sckulkarni246,

>  **Will assembly code be a problem?**

I don't think so.

> **Is there an official guide/reference issue for adding external source code to optee/lib, generating a static lib and compiling it?**

I'm afraid there is none :-/ But it shouldn't be that hard. Indeed you have two options.
1. Use the TA development environment. You already are working with it since you are developing a TA I suppose? Well you can do as if your library was a TA but replace `BINARY=<uuid>` with `LIBNAME=libfoo` in the Makefile. This will tell the build system to create a static library and you should obtain `libfoo.a`.
2. If you prefer to try and build your library in the `optee_os` source tree, then the smallest example I can give is the patch adding libdl: https://github.com/OP-TEE/optee_os/commit/c96bced450.

**Comment by sckulkarni246** [comment]
Hi @jforissier ,

Thank you for your support in this regard. I was delayed a bit as I had to port a lot of assembly code from armasm to GNU. I have been able to generate a static library and use it with a TA.
I may run into other issues but I am going ahead and closing this issue. 

> Use the TA development environment. You already are working with it since you are developing a TA I suppose? Well you can do as if your library was a TA but replace BINARY=<uuid> with LIBNAME=libfoo in the Makefile. This will tell the build system to create a static library and you should obtain libfoo.a.

This was the process I followed.

**Comment by jforissier** [comment]
@sckulkarni246 glad it worked out.

**Comment by fakhruddinbabor7** [comment]
When im giving command darknetp , im getting following error:
platform: QEMUv8

# darknetp 
Prepare session with the TA
darknetp: TEEC_Opensession failed with code 0xffff000c origin 0x3

I tried with hello_world and it was working fine.

**Comment by jforissier** [comment]
@fakhruddinbabor7

> I tried with hello_world and it worked fine.

So, you must be doing something wrong.

Please do not re-use existing issues for new questions unless you are reasonably certain that they are related.

**Comment by fakhruddinbabor7** [comment]
@jforissier 
Thanks for your reply. I'm getting exactly same error that matches with this issue header. That's why I thought to discuss it here. Surprisingly I'm getting correct output for **hello_world** program and when I'm giving **"darknetp"** command , it was giving me the above mentioned error. 

This is the output from the terminal:

D/TC:? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA 7fc5c039-0542-4ee1-80af-b4eab2f1998d
D/TC:? 0 ldelf_load_ldelf:96 ldelf load address 0x80006000
D/LD:  ldelf:134 Loading TS 7fc5c039-0542-4ee1-80af-b4eab2f1998d
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF 7fc5c039-0542-4ee1-80af-b4eab2f1998d (early TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF 7fc5c039-0542-4ee1-80af-b4eab2f1998d (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF 7fc5c039-0542-4ee1-80af-b4eab2f1998d (REE)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0
E/TC:? 0 alloc_pgt:147 7 page tables not available
E/LD:  populate_segments:836 sys_map_zi
E/TC:? 0 ldelf_init_with_ldelf:131 ldelf failed with res: 0xffff000c
D/TC:? 0 tee_ta_open_session:717 init session failed 0xffff000c


Any idea how can I proceed from this point!

**Comment by fakhruddinbabor7** [comment]
Okay ... I got it solved by reducing  TA_DATA_SIZE to 5 MB. I randomly tried that and it worked. Thanks .
