### ISSUE TITLE
Commit broke example for Xilinx zynqmp boards

### ISSUE THREAD

**Issue by voegelit** [OP-TEE/optee_os#3828]
Hi all
I'm working with an soc from xilinx and I'm currently trying the different possibilities with trustzone, atf and optee. I just found that one of the recent commits (c706c2449b50bbfa62528ee515a7ac07fec98769) broke the example for xilinx boards [(https://optee.readthedocs.io/en/latest/building/devices/zynqmp.html)](https://optee.readthedocs.io/en/latest/building/devices/zynqmp.html).

I followed the guidlines in the example from the link and I get the following error, the full error log is attached ([log.txt](https://github.com/OP-TEE/optee_os/files/4580337/log.txt)):
`|   File "scripts/gen_ldelf_hex.py", line 68`
`|     print(f'RO load segment found after RW one(s) (m={n})')`
`|                                                          ^`
`| SyntaxError: invalid syntax`

When I clone the optee_os repo localy and revert commit c706c2449b50bbfa62528ee515a7ac07fec98769, the project compiles without an error.

I'm not familiarized enough with the optee project to tell if the example is out of date or the commit introduced a bug. Would be nice if anybody could have a look into this.

Best regards
Tobias

**Comment by Emantor** [comment]
Hi,

> `| File "scripts/gen_ldelf_hex.py", line 68`
> `| print(f'RO load segment found after RW one(s) (m={n})')`
> `| ^`
> `| SyntaxError: invalid syntax`

This is an error related to your python version, I don't remember the exact major version where this was added, but I think it was python3.6.

**Comment by jforissier** [comment]
> Hi,
> 
> > `| File "scripts/gen_ldelf_hex.py", line 68`
> > `| print(f'RO load segment found after RW one(s) (m={n})')`
> > `| ^`
> > `| SyntaxError: invalid syntax`
> 
> This is an error related to your python version, I don't remember the exact major version where this was added, but I think it was python3.6.

Indeed: https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals
My mistake. I shouldn't have used this syntax. I will propose a fix shortly.

@voegelit sorry for the inconvenience.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/3832

**Comment by voegelit** [comment]
I checked my python version and apparently petalinux (the utility from xilinx) still uses python 2.7.
Thank you @jforissier for the fast fix of my issue.

**Comment by jforissier** [comment]
> I checked my python version and apparently petalinux (the utility from xilinx) still uses python 2.7.

Weird it works at all, because all the OP-TEE scripts start with `#!/bin/env python3`.

> Thank you @jforissier for the fast fix of my issue.

np :)
