### ISSUE TITLE
Confused on OP-TEE initcall functions

### ISSUE THREAD

**Issue by ElonZhang0328** [OP-TEE/optee_os#3845]
In OP-TEE OS, service_init/service_init_late is early than driver_init/driver_init_late. In my opinion, services generally rely on drivers, so is it more reasonable that make driver init before service?

For example, tee_fs_init_key_manager call huk_subkey_derive() and huk_subkey_derive() rely on tee_otp_get_hw_unique_key() which depends on OTP driver. OTP must be initizlized at the very beginning to make all otp related functions work well.

RNG and crypto drivers also have the same problem.

**Comment by angelina-zhao** [comment]
@jenswi-linaro @ElonZhang0328
Do you have any conclusion on this?

I met the same issue as described above, as tee_otp_get_hw_unique_key() is called in service but the unique key is saved in OTP and the OTP driver (which is registered in driver_init()) is not ready yet.

Can I register my OTP driver in service_init() to solve this confliction?  Is there any side-effect to do so?

Thanks.
