### ISSUE TITLE
Wierd memcpy size calculation in Hacl_EC_Point_copy()

### ISSUE THREAD

**Issue by sander-visser** [OP-TEE/optee_os#3846]
Why isnt the body of Hacl_EC_Point_copy() just:

memcpy(output, input, 10 * sizeof(uint64));

**Comment by sander-visser** [comment]
in 3rd party code everest and everest/legacy

**Comment by jforissier** [comment]
What?

**Comment by sander-visser** [comment]
> in 3rd party code everest and everest/legacy

Since in third party code (that might not even be in use - have not checked) maybe the wierd size calculation should be accepted as is?

**Comment by jbech-linaro** [comment]
Could you please point is to the problem in our code base? If not, please ask the one owning the code you are referring to.

**Comment by sander-visser** [comment]
sorry the wierd size check is in 3rd party lib to mbedtls of a version never than that in optee-os:

https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.22.0/3rdparty/everest/library/Hacl_Curve25519.c#L412
