### ISSUE TITLE
Curve length and Hash length in ECDSA

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#3848]
The file lib/libutee/include/tee_api_defines.h binds ECDSA to the key-length i.e. we have the define
as TEE_ALG_ECDSA_P192.

But, TEE internal core API spec 1.1.1 and 1.2.1 mention that:
"ECDSA algorithm identifiers should be tied to the size of the digest, not the key" 

Hence, the core spec renames TEE_ALG_ECDSA_P192 to TEE_ALG_ECDSA_SHA1.

Is this a bug in tee_api_defines.h or the core spec?

Does this mean, we can use SHA1 only with 192 bit ECC key and not with other key lengths(i.e. 224, 256, 384, 521)?

**Comment by jforissier** [comment]
Hi @saddy-muchu,

> The file lib/libutee/include/tee_api_defines.h binds ECDSA to the key-length i.e. we have the define
> as TEE_ALG_ECDSA_P192.

Correct.

> But, TEE internal core API spec 1.1.1 and 1.2.1 mention that:
> "ECDSA algorithm identifiers should be tied to the size of the digest, not the key"
> 
> Hence, the core spec renames TEE_ALG_ECDSA_P192 to TEE_ALG_ECDSA_SHA1.

True.

> Is this a bug in tee_api_defines.h or the core spec?

Neither ;-) It's just that in this regard OP-TEE implements spec v1.1, not v1.1.1 or later unfortunately.

> Does this mean, we can use SHA1 only with 192 bit ECC key and not with other key lengths(i.e. 224, 256, 384, 521)?

No, you can use SHA-1 with any ECC curve as shown here: https://github.com/OP-TEE/optee_test/blob/3.8.0/host/xtest/regression_4000.c#L3980-L3982

**Comment by saddy-muchu** [comment]
> 
> 
> Hi @saddy-muchu,
> 
> > The file lib/libutee/include/tee_api_defines.h binds ECDSA to the key-length i.e. we have the define
> > as TEE_ALG_ECDSA_P192.
> 
> Correct.
> 
> > But, TEE internal core API spec 1.1.1 and 1.2.1 mention that:
> > "ECDSA algorithm identifiers should be tied to the size of the digest, not the key"
> > Hence, the core spec renames TEE_ALG_ECDSA_P192 to TEE_ALG_ECDSA_SHA1.
> 
> True.
> 
> > Is this a bug in tee_api_defines.h or the core spec?
> 
> Neither ;-) It's just that in this regard OP-TEE implements spec v1.1, not v1.1.1 or later unfortunately.
> The value of TEE_ALG_ECDSA_P192 is 0x70001041 and that of TEE_ALG_ECDSA_SHA1 is 0x70001042 (according to spec v1.1.1 and v1.2.1). They differ in their values because as you mentioned OP-TEE implements spec v1.1. 

This is intended. 
am i correct?
> > Does this mean, we can use SHA1 only with 192 bit ECC key and not with other key lengths(i.e. 224, 256, 384, 521)?
> 
> No, you can use SHA-1 with any ECC curve as shown here: https://github.com/OP-TEE/optee_test/blob/3.8.0/host/xtest/regression_4000.c#L3980-L3982

**Comment by jforissier** [comment]
> The value of TEE_ALG_ECDSA_P192 is 0x70001041 and that of TEE_ALG_ECDSA_SHA1 is 0x70001042 (according to spec v1.1.1 and v1.2.1). They differ in their values because as you mentioned OP-TEE implements spec v1.1.

No, they differ in value because the person who implemented this in OP-TEE thought that it was better not to follow the spec which was somewhat inconsistent -- see this comment: https://github.com/OP-TEE/optee_os/blob/3.8.0/lib/libutee/include/tee_api_defines.h#L181-L191

> This is intended.
> am i correct?

Yes, although probably not a good idea IMO.

**Comment by saddy-muchu** [comment]
> 
> 
> > The value of TEE_ALG_ECDSA_P192 is 0x70001041 and that of TEE_ALG_ECDSA_SHA1 is 0x70001042 (according to spec v1.1.1 and v1.2.1). They differ in their values because as you mentioned OP-TEE implements spec v1.1.
> 
> No, they differ in value because the person who implemented this in OP-TEE thought that it was better not to follow the spec which was somewhat inconsistent -- see this comment: https://github.com/OP-TEE/optee_os/blob/3.8.0/lib/libutee/include/tee_api_defines.h#L181-L191

OK. 
Thank you.

> > This is intended.
> > am i correct?

> Yes, although probably not a good idea IMO.

Any plan to use the defines from the latest spec in OP-TEE anytime in the future?

**Comment by jforissier** [comment]
> Any plan to use the defines from the latest spec in OP-TEE anytime in the future?

No, not to my knowledge, but feel free to propose patches.

**Comment by saddy-muchu** [comment]
> Any plan to use the defines from the latest spec in OP-TEE anytime in the future?

Sure.
Thanks for clearing my doubts.
