### ISSUE TITLE
Using OPTEE with Raspbian

### ISSUE THREAD

**Issue by niusenc** [OP-TEE/optee_os#3849]
Hi, I want to build OPTEE to Raspbian.  I compile the optee as follows:

Host machine: ubuntu18.04
Cross build toolchain:
     gcc-linaro-6.1.1-2016.08-i686_arm-linux-gnueabihf
     gcc-linaro-6.1.1-2016.08-x86_64_aarch64-linux-gnu
Hardware: Raspberry pi3 B+
Raspbian: Raspbian Buster with desktop

I followed all steps which are mentioned in https://github.com/benhaz1024/raspbian-tee. 

I can successfully get https://github.com/gagachang/raspbian-tee/blob/master/doc/raspbian-tee-output.jpg. 

Then I copied files to my SD card:
    $ cp ./out/boot/* /media/user/boot
    $ sudo cp -r ./out/rootfs/* /media/user/rootfs

But after I boot my pi, it does not work correctly. The screen only displays gradient color. I met the same problem as https://github.com/OP-TEE/optee_os/issues/3557. I tried with 3B and 3B+, both of them didn't work.  Can anyone give some suggestions?

Thanks.

**Comment by niusenc** [comment]
I will close this question since I already fixed the problem. The solution is, try to use an old version of Raspbian OS, I use 2018-11-13-raspbian-stretch and it works fine.

**Comment by iitKD** [comment]
Hi, since you have compiled raspbian with OPtee, can you please list out the steps need to be followed.
I am not able to follow above steps in https://github.com/benhaz1024/raspbian-tee.
Please thank you.

**Comment by iitKD** [comment]
HI do you have links to the 2018-11-13-raspbian-stretch , please if you can reply it will help a lot.
