### ISSUE TITLE
GCM encryption failed with large buffer (error: TEE_ERROR_ACCESS_DENIED)

### ISSUE THREAD

**Issue by jpmiceli** [OP-TEE/optee_os#3861]
I've a TA which performs GCM encoding/decoding. The data to cypher are sent from TEE (Linux) and shm mem.  It is working fine with small buffer.
With large buffer (inbuf & outbuf lenght is set to 512K), I got `TEE_ERROR_ACCESS_DENIED` error
logs:
```
F/TC:? 0 trace_syscall:127 syscall #37 (syscall_authenc_enc_final)
F/TC:? 0 trace_syscall:127 syscall #2 (syscall_panic)
E/TC:? 0 
E/TC:? 0 TA panicked with code 0xffff0001
```

I'd like to use large buffer to decrease cypher processing time as mush as possible. 

I've done some experiments:
* Some behavior is working fine with a **pTA**
* Same issue with optee in 32bit or 64bit targets 
* The maximum size for inbuf & outbuf is 1024 bytes (only tested on 32bit target)

It seems to be a memory/mmu related issue. 
* Any idea from where this limitation comes ? It is which memory area
* Is it possible know the limit ? 
* Is it possible to configure Optee or TA to make it work with large ?

Here is a part of the TA src code as reference:
```
buf_sz = params[0].memref.size;
inbuf  = params[0].memref.buffer;
outbuf = inbuf + buf_sz;
tag    = inbuf + 2*buf_sz + ASF_IV_SZ;

ret = TEE_AEEncryptFinal(op_handle, inbuf, buf_sz, outbuf, &buf_sz, tag, &tag_sz);
```

**Comment by jforissier** [comment]
Hi @jpmiceli ,


> Here is a part of the TA src code as reference:
> 
> ```
> buf_sz = params[0].memref.size;
> inbuf  = params[0].memref.buffer;
> outbuf = inbuf + buf_sz;
```
That's wrong. OP-TEE will map parameters into the TA's address space based on the size parameter. You can't lie about the size of the buffers ;-) You could allocate a buffer twice as large as the input data plus the tag size, and copy the data into the first half.

But, note that you don't even need a bigger buffer than the input data (except for the tag, which you may handle either with over-allocation at the end of the input data, or as a separate parameter: `params[1]`). Indeed, you can encrypt in place, which I would recommend. The GP spec says "The buffers srcData and destData SHALL be either completely disjoint or equal in their starting positions."

**Comment by jpmiceli** [comment]
Hi @jforissier ,

thanks for the explanation. I test it right away

**Comment by jpmiceli** [comment]
OK shm management was the issue. 

Thanks for the support
