### ISSUE TITLE
Quick question regarding compiling TA application

### ISSUE THREAD

**Issue by liurenju** [OP-TEE/optee_os#3862]
Hi,

I'm trying to write a TA application. Let's say it has ta.c, and foo.c, where ta.c needs the foo.o to be compiled. Can anyone tell me how I should write the sub.mk?

Do I have to compile foo.c as a static library libfoo.a, and then use #901 to add libfoo.a as the external library to ta.c? Is there a way to declare the dependency of ta.c as foo.o in the sub.mk such that I don't need to write an external library? Thanks.

**Comment by etienne-lms** [comment]
Look at pkcs11 TA [sub.mk](https://github.com/OP-TEE/optee_os/blob/master/ta/pkcs11/src/sub.mk), build a TA binary from several C source files.

**Comment by jforissier** [comment]
To complement @etienne-lms's answer: `sub.mk` is a Makefile so in addition to the variable declarations you may also add custom rules.

For the particular case of generated source files, we have a mechanism in `optee_os` which works also for TAs. Here is an example:

```make
srcs-y += foo.c

gensrcs-y += ta-c
produce-ta-c = ta.c
depends-ta-c = $(sub-dir-out)/foo.o
recipe-ta-c = $(sub-dir)/gen_ta_c.sh $(sub-dir-out)/foo.o $(sub-dir-out)/ta.c
```

In the above example, `ta.c` is generated from `foo.o` by `gen_ta_c.sh` and `ta.c` is automatically added to the TA source file list.
