### ISSUE TITLE
Evolution of Linux kernel TEE bus with new use-cases coming up

### ISSUE THREAD

**Issue by b49020** [OP-TEE/optee_os#3863]
In continuation of discussion [here](https://github.com/OP-TEE/optee_os/pull/3840#issuecomment-627771232).

**Comment by muvarov** [comment]
Proposed ftpm patch: https://raw.githubusercontent.com/muvarov/meta-ledge/zeus_ftpm_on_tee_bus/meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0008-tpm_ftpm_tee-register-driver-on-tee-bus.patch

Proposed optee patch: 
https://raw.githubusercontent.com/muvarov/meta-ledge/zeus_ftpm_on_tee_bus/meta-ledge-bsp/recipes-kernel/linux/linux-ledge/0009-optee-move-drivers-initialization-after-tee-supplica.patch

**Comment by jenswi-linaro** [comment]
Who's responsible for keeping track of the ABIs provided by the different TAs (or UUIDs) on which various kernel driver depends on?

**Comment by b49020** [comment]
I would say its the kernel driver itself listing the invoke commands and corresponding params definitions. So if any new SP needs to implement a corresponding TA device then it should adhere to corresponding kernel driver ABI.

**Comment by jenswi-linaro** [comment]
It's the responsibility of the SPs to review all driver in question and make sure that all their TAs, new and old, don't clash with the kernels expectations?

I assume that the main kernel tree is the reference. Would vendor trees need to be taken into account too?

**Comment by b49020** [comment]
> It's the responsibility of the SPs to review all driver in question and make sure that all their TAs, new and old, don't clash with the kernels expectations?

Yes.

> I assume that the main kernel tree is the reference. Would vendor trees need to be taken into account too?

Yes mainline kernel tree should be the only reference. I think vendor trees should be left to their own vendor specific TAs. This is another reason why we shouldn't bind any TA specific information in OP-TEE core as it should be able to support both mainline and vendor kernels.

**Comment by jenswi-linaro** [comment]
You're right, this is not a problem that OP-TEE core can solve.

It sucks a bit though, because it seems fragile.
