### ISSUE TITLE
sign_encrypt.py: Issue with pycryptodome

### ISSUE THREAD

**Issue by ldebieve** [OP-TEE/optee_os#3865]
Hi all,

I'm currently trying to build OPTEE OS master branch.
Using the Python3.6 or Python3.8, I'm facing an issue with the sign_encrypt.py script.

I've no pre-install pycrypto library installed and the cryptodome is installed to Crypto folder.
Looking into the script sign_encrypt.py, it looks for a Cryptodome class.

It seems that when pycrypto is installed first, pycryptodome seems to be installed in a Cryptodome folder.

Is it a known issue or just an personal environment issue?

Thanks
Lionel

**Comment by jbech-linaro** [comment]
Hi @ldebieve , indeed this is known and "has been fixed". The thing is that Linux distros are all in different state in the transition of Python version and packages, so we have unfortunately ended up in a situation where it's hard to come up with a bulletproof solution working across all Linux distros.

See discussion around it in these threads ([thread1](https://github.com/OP-TEE/optee_os/issues?q=pycryptodome), [thread2](https://github.com/OP-TEE/build/issues?q=is%3Aissue+pycryptodome+)). Ubuntu 18.04 with correct packages installed as described in the documentation shall work.

**Comment by etienne-lms** [comment]
Thanks @jbech-linaro.
Maybe https://github.com/OP-TEE/optee_os/issues/3624 guidance in bitbake recipes can help to fix the issue.

**Comment by ldebieve** [comment]
Thanks @jbech-linaro
I'll try this and close this thread.

**Comment by ldebieve** [comment]
Confirmed OK, sorry for the noise.
BR
