### ISSUE TITLE
i.MX6ULZ: booting on USB Armory Mk2

### ISSUE THREAD

**Issue by gsora** [OP-TEE/optee_os#3868]
Hi,
I'm trying to get OP-TEE booted on the USB Armory Mk2, my version uses a i.MX6ULZ SoC, with 512 MB RAM.

I'm paging @MrVan since it seems they're the i.MX6UL/ULL maintainer.

The boot flow I would like to achieve is U-Boot -> OP-TEE -> Linux kernel.

I'm using:
 - Linux 5.4.38 (config [here](https://github.com/f-secure-foundry/usbarmory/blob/master/software/kernel_conf/mark-two/usbarmory_linux-5.4.config), I added OP-TEE settings though)
 - [this](https://github.com/f-secure-foundry/usbarmory/blob/master/software/kernel_conf/mark-two/imx6ulz-usbarmory.dts) dtb
 - U-Boot 2019.7

I patched OP-TEE to get more debug output in the following way:

```patch
--- a/core/arch/arm/plat-imx/conf.mk
+++ b/core/arch/arm/plat-imx/conf.mk
@@ -276,6 +276,8 @@ endif
 ifneq (,$(filter $(PLATFORM_FLAVOR),mx6ulevk mx6ullevk mx6ulzevk))
 CFG_DDR_SIZE ?= 0x20000000
 CFG_NS_ENTRY_ADDR ?= 0x80800000
+CFG_UART_BASE ?= UART2_BASE
+CFG_DT_ADDR=0x82000000
 endif

```

To build OP-TEE I'm running:

```
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- PLATFORM=imx-mx6ulzevk ARCH=arm CFG_PAGEABLE_ADDR=0 CFG_NS_ENTRY_ADDR=0x80800000 CFG_DT_ADDR=0x82000000 CFG_DT=y DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4
```

To create a U-Boot-friendly TEE image: 

```
./mkimage -A arm -O linux -C none -a 0x9DFFFFE4 -e 0x9E000000  -d ~/optee_os/out/arm-plat-imx/core/tee.bin uTee
```

where the `mkimage` command comes from the same U-Boot codebase that's running on the device.

Then, to run it on the board I execute the following commands:

```
ext2load mmc 1:1 0x84000000 /boot/uTee
ext2load mmc 1:1 0x82000000 /boot/imx6ulz-usbarmory.dtb
ext2load mmc 1:1 0x80800000 /boot/zImage-tee;
bootm 0x84000000 - 0x82000000
```

While OP-TEE seem to start up fine, it hangs when switching to the normal world:

```
=> ext2load mmc 1:1 0x84000000 /boot/uTee; ext2load mmc 1:1 0x82000000 /boot/imx6ulz-usbarmory.dtb; ext2load mmc 1:1 0x80800000 /boot/zImage-tee;
374740 bytes read in 33 ms (10.8 MiB/s)
19930 bytes read in 20 ms (972.7 KiB/s)
6617632 bytes read in 300 ms (21 MiB/s)
=> bootm 0x84000000 - 0x82000000
## Booting kernel from Legacy Image at 84000000 ...
   Image Name:   
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    374676 Bytes = 365.9 KiB
   Load Address: 9dffffe4
   Entry Point:  9e000000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 82000000
   Booting using the fdt blob at 0x82000000
   Loading Kernel Image ... OK
   Loading Device Tree to 9f568000, end 9f56fdd9 ... OK

Starting kernel ...

D/TC:0 0 get_aslr_seed:1305 Cannot find /secure-chosen
D/TC:0 0 add_phys_mem:585 TEE_SHMEM_START type NSEC_SHM 0x9fe00000 size 0x00200000
D/TC:0 0 add_phys_mem:585 TA_RAM_START type TA_RAM 0x9e100000 size 0x01d00000
D/TC:0 0 add_phys_mem:585 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x9e059000 size 0x000a7000
D/TC:0 0 add_phys_mem:585 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x9e000000 size 0x00059000
D/TC:0 0 add_phys_mem:585 ROUNDDOWN(IRAM_BASE, CORE_MMU_PGDIR_SIZE) type TEE_COHERENT 0x00900000 size 0x00100000
D/TC:0 0 add_phys_mem:585 ROUNDDOWN(0x02200000, CORE_MMU_PGDIR_SIZE) type IO_SEC 0x02200000 size 0x00100000
D/TC:0 0 add_phys_mem:585 ROUNDDOWN(0x02100000, CORE_MMU_PGDIR_SIZE) type IO_SEC 0x02100000 size 0x00100000
D/TC:0 0 add_phys_mem:585 ROUNDDOWN(0x02000000, CORE_MMU_PGDIR_SIZE) type IO_SEC 0x02000000 size 0x00100000
D/TC:0 0 add_phys_mem:585 ROUNDDOWN(0x020C8000, CORE_MMU_PGDIR_SIZE) type IO_SEC 0x02000000 size 0x00200000
D/TC:0 0 add_phys_mem:599 Physical mem map overlaps 0x2000000
D/TC:0 0 add_phys_mem:585 ROUNDDOWN(0x00A00000, CORE_MMU_PGDIR_SIZE) type IO_SEC 0x00a00000 size 0x00100000
D/TC:0 0 add_phys_mem:585 ROUNDDOWN((0x021E8000), CORE_MMU_PGDIR_SIZE) type IO_NSEC 0x02100000 size 0x00200000
D/TC:0 0 verify_special_mem_areas:529 NSEC DDR memory [80000000 9e000000]
D/TC:0 0 add_va_space:625 type RES_VASPACE size 0x00a00000
D/TC:0 0 add_va_space:625 type SHM_VASPACE size 0x02000000
D/TC:0 0 dump_mmap_table:732 type NSEC_SHM     va 0x98c00000..0x98dfffff pa 0x9fe00000..0x9fffffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type TA_RAM       va 0x98e00000..0x9aafffff pa 0x9e100000..0x9fdfffff size 0x01d00000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type IO_SEC       va 0x9ac00000..0x9acfffff pa 0x02200000..0x022fffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type IO_SEC       va 0x9ad00000..0x9adfffff pa 0x02100000..0x021fffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type IO_NSEC      va 0x9ae00000..0x9affffff pa 0x02100000..0x022fffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type IO_SEC       va 0x9b000000..0x9b1fffff pa 0x02000000..0x021fffff size 0x00200000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type IO_SEC       va 0x9b200000..0x9b2fffff pa 0x00a00000..0x00afffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type TEE_COHERENT va 0x9b300000..0x9b3fffff pa 0x00900000..0x009fffff size 0x00100000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type RES_VASPACE  va 0x9b400000..0x9bdfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type SHM_VASPACE  va 0x9bf00000..0x9defffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0 0 dump_mmap_table:732 type TEE_RAM_RX   va 0x9e000000..0x9e058fff pa 0x9e000000..0x9e058fff size 0x00059000 (smallpg)
D/TC:0 0 dump_mmap_table:732 type TEE_RAM_RW   va 0x9e059000..0x9e0fffff pa 0x9e059000..0x9e0fffff size 0x000a7000 (smallpg)
D/TC:0 0 core_mmu_alloc_l2:264 L2 table used: 1/5
I/TC: 
D/TC:0 0 init_canaries:164 #Stack canaries for stack_tmp[0] with top at 0x9e0836f8
D/TC:0 0 init_canaries:164 watch *0x9e0836fc
D/TC:0 0 init_canaries:165 #Stack canaries for stack_abt[0] with top at 0x9e07ed38
D/TC:0 0 init_canaries:165 watch *0x9e07ed3c
D/TC:0 0 init_canaries:167 #Stack canaries for stack_thread[0] with top at 0x9e080d78
D/TC:0 0 init_canaries:167 watch *0x9e080d7c
D/TC:0 0 init_canaries:167 #Stack canaries for stack_thread[1] with top at 0x9e082db8
D/TC:0 0 init_canaries:167 watch *0x9e082dbc
I/TC: Non-secure external DT found
I/TC: Switching console to device: /soc/aips-bus@2100000/serial@21e8000
I/TC: OP-TEE version: 3.9.0-rc1-6-gc3682b1c-dev (gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)) #1 sab 16 mag 2020, 14:13:25, UTC arm
D/TC:0 0 paged_init_primary:1174 Executing at offset 0 with virtual load address 0x9e000000
D/TC:0 0 check_ta_store:635 TA store: "Secure Storage TA"
D/TC:0 0 check_ta_store:635 TA store: "REE"
D/TC:0 0 mobj_mapped_shm_init:446 Shared memory address range: 9bf00000, 9df00000
E/TC:0 0 plat_rng_init:188 Warning: seeding RNG with zeroes
D/TC:0 0 imx_wdog_base:140 path: /soc/aips-bus@2000000/wdog@20bc000
I/TC: Initialized
D/TC:0 0 paged_init_primary:1188 Primary CPU switching to normal world boot
```

To me, it seems like OP-TEE does initialize fine, but somehow it cannot jump to the Linux kernel even though the NS addresses are fine.

AFAIU there's no need to modify the device tree beforehand, since OP-TEE does modify it automatically: is this assumption right?

What could I do to debug this strange behavior?

Thank you.

**Comment by gsora** [comment]
The default config for OP-TEE does contain `CFG_PSCI_ARM32=y`, the kernel config does not though.

**Comment by gsora** [comment]
I originally followed @MrVan's [notes](https://mrvan.github.io/optee-imx6ul) on how to run on i.MX6UL, although I had to modify uTee addresses to fit my board.

Could having OP-TEE and the Linux kernel writing on the same UART interfere with the boot process?

Is using both mainline Linux kernel and U-Boot okay? Or we should still use vendor-specific forks?

**Comment by gsora** [comment]
By making my way into IMX's U-Boot (the one on codeaurora), after enabling bootm-specific commands for optee, this happens:

```
## Booting kernel from Legacy Image at 84000000 ...
   Image Name:   
   Image Type:   ARM Trusted Execution Environment Kernel Image (uncompressed)
   Data Size:    374676 Bytes = 365.9 KiB
   Load Address: 9dffffe4
   Entry Point:  9e000000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK
OPTEE verification error:
	hdr=84000040 image=0x84000040 magic=0x4554504f tzdram 0x00000000-0x00000000 
	header lo=0x9e000000 hi=0x00000000 size=0x0005b794 arch=0x00000000
	uimage params 0x9dffffe4-0x9e05b778
```

Maybe I'm building the image wrong?

**Comment by gsora** [comment]
Further (printf-driven) investigation, the execution does stop at `smc #0`.

**Comment by jenswi-linaro** [comment]
> Maybe I'm building the image wrong?

The print suggests so at least.

>Further (printf-driven) investigation revealed that the execution does stop at smc #0

`smc #0` in OP-TEE or U-Boot?

**Comment by gsora** [comment]
> The print suggests so at least.

That error only shows up when compiling u-boot-imx, after fine tuning some optee-specific parameters it went away.

> smc #0 in OP-TEE or U-Boot?

In OP-TEE.

**Comment by jenswi-linaro** [comment]
> > smc #0 in OP-TEE or U-Boot?
> 
> In OP-TEE.

I assume that's the `smc #0` at the end of `reset_primary()` in `core/arch/arm/kernel/generic_entry_a32.S`

With that the secure monitor is entered and the non-secure state restored and entered.
Maybe there's something wrong with the non-secure entry address?

**Comment by gsora** [comment]
Yes, it's the smc call in `reset_primary()`: sorry, should've been more precise.

> Maybe there's something wrong with the non-secure entry address?

I'm not sure.

The `mx6ulzevk` platform defines `CFG_NS_ENTRY_ADDR=0x80800000`, so I expected OP-TEE to "just work" with its configuration, considering this device is almost completely identical to a i.MX6ULZ eval board (same amount of RAM, no special hardware of notice onboard).

At this point I'm at a loss of options.

Does OP-TEE requires a special kernel/U-Boot patch?

I know for sure it needs a reserved memory area entry, a firmware entry and a PSCI entry in the device tree, but AFAIU from reading the boot process code, those are added dynamically.

**Comment by jenswi-linaro** [comment]
> Does OP-TEE requires a special kernel/U-Boot patch?

None that I'm aware of. In `init_sec_mon()` you can check the register state which will be used when entering normal world. I suppose the most interesting one is `nsec_ctx->mon_lr`.

**Comment by gsora** [comment]
> I suppose the most interesting one is nsec_ctx->mon_lr.

That address matches the one where I'm loading the kernel image with `ext2load`, so it should jump no problem.

Maybe the issue is in the linux kernel itself?

Sadly I'm not equipped with a JTAG debugger to do step by step execution :/

**Comment by jenswi-linaro** [comment]
> It is probably the linux kernel doing some strange stuff, rebuilding OP-TEE and assigning the U-Boot entry point address as the NS_ADDR (just to see if something would happen), an "undefined instruction" error appears, so it's actually jumping to the address and trying to execute code.

Hmm, if that happens then U-Boot has executed long enough to initialize VBAR if I understand it correctly. It seems you're on to something at least.

**Comment by gsora** [comment]
Progress!

After enabling almost every possible Linux kernel serial debugging option, this error appears when booting:

```
Uncompressing Linux... done, booting the kernel.

Error: invalid dtb and unrecognized/unsupported machine ID
  r1=0x00000000, r2=0x00000000
Available machine support:

ID (hex)	NAME
ffffffff	Generic DT based system
ffffffff	Freescale i.MX6 Ultralite (Device Tree)

Please check your kernel config and/or bootloader.
```

**Comment by etienne-lms** [comment]
Hi, the machine ID should be passed by OP-TEE Core to NS entry through boot argument register `R1`. OP-TEE Core is expected to get `R1` set by the bootloader, U-Boot in your case. Core propagates `R1` when reaching NS image entry point.

**Comment by gsora** [comment]
Yup, that's what I expected.

Booting Linux from U-Boot does work and I can see r1 and r2 hold correct values (the booting process ends successfully too) but somehow they get zeroed out when OP-TEE jumps to Linux.

I'll try and debug this issue later today.

**Comment by gsora** [comment]
Interestingly enough, v3.8.0 does set `r1` and `r2` correctly, although it does not continue booting.

**Comment by gsora** [comment]
Somehow, I managed to get even *more* output from the kernel (I'm a novice, turns out you have to specify `earlyprintk` __and__ enable the appropriate bit in the kernel config) and looks like there's some kind of corruption going on:

```
Booting Linux on physical CPU 0x0
Linux version 4.19.123 (gsora@BFG) (gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)) #3 PREEMPT Tue May 19 21:22:57 CEST 2020
CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c53c7d
CPU: div instructions available: patching division code
CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
OF: fdt: Machine model: F-Secure USB armory Mk II
bootconsole [earlycon0] enabled
Memory policy: Data cache writeback
Kernel panic - not syncing: ERROR: Failed to allocate 0x00002000 bytes below 0x00000000.

CPU: 0 PID: 0 Comm: swapper Not tainted 4.19.123 #3
Hardware name: Freescale i.MX6 Ultralite (Device Tree)
[<c010d6e0>] (unwind_backtrace) from [<c010b4a8>] (show_stack+0x10/0x14)
[<c010b4a8>] (show_stack) from [<c0123ca8>] (panic+0xf8/0x26c)
[<c0123ca8>] (panic) from [<c080f55c>] (memblock_alloc_base+0x30/0x38)
[<c080f55c>] (memblock_alloc_base) from [<c0805488>] (early_alloc_aligned+0xc/0x24)
[<c0805488>] (early_alloc_aligned) from [<c0805c08>] (paging_init+0x344/0x5e4)
[<c0805c08>] (paging_init) from [<c0803498>] (setup_arch+0x68c/0x930)
[<c0803498>] (setup_arch) from [<c0800964>] (start_kernel+0x7c/0x418)
[<c0800964>] (start_kernel) from [<00000000>] (  (null))
Rebooting in 5 seconds..
Reboot failed -- System halted
```

By telling linux where the memory starts (`0x80000000`) I successfully booted a kernel along with my userspace.

I suspect there's something going on in the DT manipulation done by OP-TEE, I'll do more research tomorrow.
