### ISSUE TITLE
make V=1

### ISSUE THREAD

**Issue by thinhlevinh** [OP-TEE/optee_os#387]
I met this error, how can  I solve it
/bin/bash: armv7-linux-gcc: command not found
make: *** [out/arm-plat-stm/core/arch/arm/kernel/tee_ta_manager.o] Error 127

**Comment by jbech-linaro** [comment]
Hi @thinhlevinh you probably forgot to set the correct platform, please see the instructions [here](https://github.com/OP-TEE/optee_os#3-platforms-supported) to choose the platform and then please also install the [correct toolchain](https://github.com/OP-TEE/optee_os#411-get-the-compiler). If you follow the instructions in the [README.md](https://github.com/OP-TEE/optee_os/blob/master/README.md) file, then you should be able to get it to work.

// Joakim

**Comment by thinhlevinh** [comment]
Thank you very much. 
I will build it with Qemu

**Comment by jbech-linaro** [comment]
Then I recommend that you follow the instructions [here](https://github.com/OP-TEE/optee_os/blob/master/README.md#44-qemu).

**Comment by thinhlevinh** [comment]
Oh thank you for your help

**Comment by thinhlevinh** [comment]
I want to run  hello_word TA in Qemu. Please help me out.
I followed the steps to build OTEE with Qemu
https://github.com/OP-TEE/optee_os#44-qemu
it works well. 
After that I go to next guide by using below link
 https://github.com/OP-TEE/optee_client
but when I run "make"
it appears this error:"
~/devel/optee_client# make
Building libteec.so
Building tee-supplicant
make --directory=tee-supplicant --no-print-directory
make[1]: Nothing to be done for `all'.
mkdir -p out/export/lib out/export/include out/export/bin
cp out/libteec/libteec.so* out/export/lib
cp out/tee-supplicant/tee-supplicant out/export/bin
cp public/*.h out/export/include
Rootfs copy cannot be done because ROOTFS_DIR is not defined
"
please help me to make the enviroment parameter correctly, maybe I get stuck with it
