### ISSUE TITLE
Use optee avb ta in uboot, but can not find optee device

### ISSUE THREAD

**Issue by chenlifu2015** [OP-TEE/optee_os#3872]
hi,experts
    Recently, I want to init the optee os driver and avb ta in uboot, so I add tee dir(tee/) and optee subdir in tee/   and other nessasery files. Also I have defined the relative MARCO:CONFIG_OPTEE、CONFIG_TEE、CONFIG_CMD_AVB、CONFIG_ARM_SMCCC，after built and flash the uboot.bin to board successfully， I enter the uboot cmd line, and enter :
    avb init 0
    avb verify
  second cmd executed failed，so I add some logs，it seems like I  can not find the device of tee.log is as follows:
  Enter tee_find_device
  Enter find fisrt device
  Enter uclass_get, id is 66
  After uclass_get
  Can not find tee device
 I trace the code and I find that I am failed in the function:uclass_find_first_device(called  by tee_find_device)，function body is as follows（debug log is added by myself， I think normal situation should print the log：After list_empty too） 
int uclass_find_first_device(enum uclass_id id, struct udevice **devp)
{
        struct uclass *uc;
        int ret;

        *devp = NULL;
        ret = uclass_get(id, &uc);
        if (ret)
                return ret;
        printf("After uclass_get\n");
        if (list_empty(&uc->dev_head))
                return 0;
        printf("After list_empty\n");
        *devp = list_first_entry(&uc->dev_head, struct udevice, uclass_node);

        return 0;
}
 And I am sure I have add the tee uclass driver and uboot optee driver in the code，because I have find the symbol in the u-boot.map:
  .u_boot_list_2_driver_2_optee
                0x00000000800bd270       0x78 drivers/tee/optee/built-in.o
                0x00000000800bd270                _u_boot_list_2_driver_2_optee
 .u_boot_list_2_uclass_2_tee
                0x00000000800be370       0x80 drivers/tee/built-in.o
                0x00000000800be370                _u_boot_list_2_uclass_2_tee

so how can I find the tee device, can you help me, thanks a alot!

**Comment by igoropaniuk** [comment]
Hi @chenlifu2015 , seems you forgot to add optee node to U-Boot device tree.

Take a look hw it's done on Hikey: https://gitlab.denx.de/u-boot/u-boot/-/blob/master/arch/arm/dts/hi6220-hikey.dts#L35

**Comment by chenlifu2015** [comment]
hi，@igoropaniuk,thanks for your apply, I have added the optee node to the device tree(imx8qm-mek.dts):
   #include "fsl-imx8qm.dtsi"

/ {
        model = "Freescale i.MX8QM MEK";
        compatible = "fsl,imx8qm-mek", "fsl,imx8qm";

        chosen {
                bootargs = "console=ttyLP0,115200 earlycon=lpuart32,0x5a060000,115200";
                stdout-path = &lpuart0;
        };

        firmware {
                optee {
                        compatible = "linaro,optee-tz";
                        method = "smc";
                };
        };

   but I got the same err log, I think the reason is the optee uboot driver is not  binded to tee uclass driver,so the dev_head member in the  struct uclass is NULL, so I can not get a valid device in the uclass_find_first_device function.

struct uclass {
	void *priv;
	struct uclass_driver *uc_drv;
	struct list_head dev_head;
	struct list_head sibling_node;
};
int uclass_find_first_device(enum uclass_id id, struct udevice **devp)
{
	struct uclass *uc;
	int ret;

	*devp = NULL;
	ret = uclass_get(id, &uc);
	if (ret)
		return ret;
        /*I exit here, so the devp is always null*/
	if (list_empty(&uc->dev_head))
		return 0;

	*devp = list_first_entry(&uc->dev_head, struct udevice, uclass_node);

	return 0;
}

**Comment by MrVan** [comment]
driver not get probed?
