### ISSUE TITLE
TEE_GetPropertyAsBinaryBlock() call generates a panic()

### ISSUE THREAD

**Issue by jpmiceli** [OP-TEE/optee_os#3876]
Hi all,

My TA uses `USER_TA_PROP_TYPE_BINARY_BLOCK` properties. I try to get this properties during the  TA session session opening, but it results in a panic.

code as reference:

```
static uint8_t buf[32];

TEE_Result TA_OpenSessionEntryPoint()
{
   uint32_t size = 32;
   res = TEE_GetPropertyAsBinaryBlock(TEE_PROPSET_CURRENT_TA, "gp.ta.my_property", buf, &size);

  return TEE_SUCCESS;
}
```

Strange fact, if the `size` variable is not initialized, no panic.

Any ideas on what I did wrong ?
Thanks for your help

**Comment by etienne-lms** [comment]
From the code snippet, if the property exists for the TA and fits in 32 bytes or less, I see no reason for your TA to panic. 

It is hard to guess what happens when `size` is not set. It shall be initialized.
Here also you should check the value of `res` instead of always returning `TEE_SUCCESS`.

A way to use `TEE_GetPropertyAsBinaryBlock()` is to first call it with `size = 0`, to get the property byte size, then call it again with the expected `size`, and well sized `buf` reference, for example:
```c
static uint8_t buf[32];

TEE_Result TA_OpenSessionEntryPoint( uint32_t ptypes, TEE_Param params[4], void** session_ctx)
{
    uint32_t size = 0;

    res = TEE_GetPropertyAsBinaryBlock(TEE_PROPSET_CURRENT_TA, "gp.ta.my_property", buf, &size);
    if (res != TEE_ERROR_SHORT_BUFFER || size > sizeof(buf)) {
        /*
         * Maybe property is not found? check res == TEE_ERROR_ITEM_NOT_FOUND
         * Maybe property is bigger than 32 bytes?
         */
        goto error;
    }

    res = TEE_GetPropertyAsBinaryBlock(TEE_PROPSET_CURRENT_TA, "gp.ta.my_property", buf, &size);
    if (res != TEE_SUCCESS) {
        /* Unexpected error */
        goto error;
    }

    // now you can get property value from buf.
   ...
}
```
I hope this may help you.

**Comment by jpmiceli** [comment]
@etienne-lms Thanks for your answer.

> Here also you should check the value of res instead of always returning TEE_SUCCESS.

I did it in my current code.

I tried you solution. I get a panic at the second call of TEE_GetPropertyAsBinaryBlock().


Optee version 3.6.0
Current test code snippet:
```
	IMSG("== First call to TEE_GetPropertyAsBinaryBlock ====");

	/* Get AES communication key */
	res = TEE_GetPropertyAsBinaryBlock(TEE_PROPSET_CURRENT_TA, "gp.ta.com_key", aes_com_key, &key_size);
	if (res != TEE_ERROR_SHORT_BUFFER || key_size > sizeof(aes_com_key)) {
		EMSG("ASF - Strange, res: %x, size: %d",  res, key_size);
		return TEE_ERROR_GENERIC;
	}

	IMSG("== TEE_GetPropertyAsBinaryBlock, got size: %d, res: %x ====", key_size, res);

	res = TEE_GetPropertyAsBinaryBlock(TEE_PROPSET_CURRENT_TA, "gp.ta.com_key", aes_com_key, &key_size);
	if (res != TEE_SUCCESS) {
		EMSG("ASF - Retrieve of asf communication key failed");
		return res;
	}
```

logs (TA & core logs set to level 4):
```
I/TA: == First call to TEE_GetPropertyAsBinaryBlock ====
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
I/TA: == TEE_GetPropertyAsBinaryBlock, got size: 32, res: ffff0010 ====
F/TC:? 0 trace_syscall:127 syscall #2 (syscall_panic)
E/TC:? 0 
E/TC:? 0 TA panicked with code 0x0
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:  Status of TA 6aca96ec-d0a4-11e9-bb65-2a2ae2dbcce4
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:   arch: arm
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:  region  0: va 0x00102000 pa 0x2e300000 size 0x002000 flags rw-s (ldelf)
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:  region  1: va 0x00104000 pa 0x2e302000 size 0x007000 flags r-xs (ldelf)
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:  region  2: va 0x0010b000 pa 0x2e309000 size 0x001000 flags rw-s (ldelf)
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:  region  3: va 0x0010c000 pa 0x2e30a000 size 0x002000 flags rw-s (ldelf)
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:  region  4: va 0x0010e000 pa 0x2e30c000 size 0x001000 flags r--s
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:  region  5: va 0x0010f000 pa 0x00001000 size 0x011000 flags r-xs [0]
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:  region  6: va 0x00120000 pa 0x00012000 size 0x00c000 flags rw-s [0]
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:  region  7: va 0x0012c000 pa 0x2e32a000 size 0x001000 flags rw-s (stack)
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:   [0] 6aca96ec-d0a4-11e9-bb65-2a2ae2dbcce4 @ 0x0010f000
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:  Call stack:
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:   0x001153f8
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:   0x00111048
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:   0x0010f4e0
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:   0x00115c2c
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:   0x0010f5d0
F/TC:? 0 trace_syscall:127 syscall #1 (syscall_log)
E/LD:   0x0010f5ec
D/TC:? 0 user_ta_enter:164 tee_user_ta_enter: TA panicked with code 0x0
D/TC:? 0 tee_ta_close_session:497 csess 0x2e16b970 id 1
D/TC:? 0 tee_ta_close_session:516 Destroy session
D/TC:? 0 destroy_context:297 Destroy TA ctx (0x2e16b930)
E/TC:? 0 tee_ta_open_session:726 Failed. Return error 0xffff3024
```

**Comment by etienne-lms** [comment]
Hello @jpmiceli,
I've played a bit with the `TEE_GetPropertyAsBinaryBlock()`.
It seems that there is an issue when property is defined with `USER_TA_PROP_TYPE_BINARY_BLOCK`: to retrieve the property (as a binary block), you must provide a buffer that is at least 1 byte larger than the expected size, which is not we one should expected. The following code works:
```c
size_t size = 0;
size_t alloced_size = 0;
uint8_t *buf = NULL;

/* Retrieve property byte length */
res = TEE_GetPropertyAsBinaryBlock(TEE_PROPSET_CURRENT_TA, "gp.ta.my_property",
				   &buf, // HACK: &buf here to not provide a NULL ref.
				   &size);
if (res != TEE_ERROR_SHORT_BUFFER)
	TEE_Panic(res);

/* HACK: alloc 1 more byte than needed */
alloced_size = size + 1;
buf = TEE_Malloc(alloced_size, 0);

/* Retrieve property data */
size = alloced_size;
res = TEE_GetPropertyAsBinaryBlock(TEE_PROPSET_CURRENT_TA, "gp.ta.my_property",
				   buf, &size);
if (res != TEE_SUCCESS || size != (alloced_size - 1)) {
	EMSG("get prop data %"PRIx32" %zu", res, size);
	TEE_Panic(res);
}

DHEXDUMP(buf, size);
```
The above implementation allocates the destination buffer. Of course, if you know the property size, you are not enforced to allocate the destination buffer.

I think **libutee/tee_api_property.c** is to blame for that. I will submit the following patch to optee_os:
```patch
@@ -100,8 +100,8 @@ static TEE_Result propget_get_ext_prop(const struct user_ta_property *ep,
 		 */
 		l = *len;
 		if (!base64_dec(ep->value, strlen(ep->value), buf, &l) &&
-		    (l <= *len))
+		    (l < *len))
 			return TEE_ERROR_GENERIC;
 		if (*len < l) {
 			*len = l;
 			return TEE_ERROR_SHORT_BUFFER;
```

**Comment by jforissier** [comment]
> ```c
> res = TEE_GetPropertyAsBinaryBlock(TEE_PROPSET_CURRENT_TA, "gp.ta.my_property",
> 				   &buf, // HACK: &buf here to not provide a NULL ref.
> 				   &size);
> ```

You should be able to provide a NULL value for `buf`, otherwise it's a bug in our implementation (`(buf, size)` is `[outbuf]` in the GP spec).

**Comment by etienne-lms** [comment]
Well well well...
Looking back, I think I've investigated and tested a wrong path. I'll check again...

**Comment by etienne-lms** [comment]
I'm almost done with the required fixes. I'm testing it and need to consider all cases: I plan some changes in optee_test for that. 
I'll update P-R https://github.com/OP-TEE/optee_os/pull/3886 as soon as possible.

**Comment by etienne-lms** [comment]
Hi @jpmiceli. This issue should be addressed by #3886.
See also few added tests from https://github.com/OP-TEE/optee_test/pull/432.

**Comment by jpmiceli** [comment]
Hi @etienne-lms,

I will integrated these changes and test it.

Thanks for your help

**Comment by etienne-lms** [comment]
Thanks for your feedback.

**Comment by jpmiceli** [comment]
Hi all,

What is the correct use of this API ? In my case, I know and expect the `properties` to be 32 bytes. What size should be my buffer 32 or 32 +1 ? 

Same question regarding `size` parameter, as input (to check to buffer size) and output ?

Thanks
J-P

**Comment by etienne-lms** [comment]
Hi @jpmiceli.

The expected behavior for `TEE_GetPropertyAsBinaryBlock()` is:
- Argument `value_len` as an input argument AND an output argument (hence argument is a pointer).
- As input argument: it provides the byte size of the buffer provided as argument `value`.
- As output: reports the effective byte size of the binary block property.
- If input value of `*value_len` is lower than the property effective size, the function returns `TEE_ERROR_SHORT_BUFFER` and `*value_len` output value gives you the expected size.
- If input value of `*value_len` is higher or equal to the property effective size, the function returns `TEE_SUCCESS` and `*value_len` output value give the property effective size.

Assuming we rely on #3886 (I hope it is finalized soon), you can provide a buffer of 32 bytes if you know the property fits in 32 bytes.

Without  #3886 fix in optee_os sources, a workaround is to provide a buffer slightly larger than the expected size, 1 byte larger is sufficient according to me.

**Comment by jpmiceli** [comment]
Hi @etienne-lms, all,

Thanks for the explanation. It was my understanding, just wanted to be 100% sure :-).

I integrated #3886 in my environment and tested it on my both platform I've. It is working fine.

Thanks for your support

**Comment by jpmiceli** [comment]
PS: I will wait #3886 to be closed before closing this issue.

**Comment by etienne-lms** [comment]
Fine.
If you provide your Tested-by tag (`Tested-by FULL-NAME <EMAIL>`) I can add it to #3886 commits.

**Comment by jpmiceli** [comment]
@etienne-lms  I put a Tested by in #3886
