### ISSUE TITLE
crypto: deleting keys

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#3879]
Some crypto devices (NXP SE050) present the capability of storing the private keys in non volatile memory.  For those devices, the private keys stored in persistent storage (sks database) are no more than references to the actual  keys in the device NVM.

Currently when deleting a key, SKS only has to delete the object from its database; for keys stored in external devices - where the sks key is just a reference- sks would have to access the device to proceed with the key deletion.

Is there any work in progress to support this requirement? or a simple API that we should be using to extend the current behaviour?

I believe that the interface in tee_svc_storage.c:syscall_storage_obj_del is too late since I do need to know the actual private key that is being deleted with the object and I dont think I can retrieve it anymore at that point. am I wrong?

**Comment by jenswi-linaro** [comment]
> Is there any work in progress to support this requirement? or a simple API that we should be using to extend the current behaviour?

None I'm aware of.

> I believe that the interface in tee_svc_storage.c:syscall_storage_obj_del is too late since I do need to know the actual private key that is being deleted with the object and I dont think I can retrieve it anymore at that point. am I wrong?

Via `struct tee_obj` you should be able to access all information you need.

**Comment by ldts** [comment]
Are you saying that I can retrieve the actual key in the op-tee function **syscall_storage_obj_del**? because the way I see it that is not possible.  I am a bit confused that you think I can retrieve the key from a struct tee_obj no matter where (I guess I am misunderstanding your point). 

if you could confirm that this is true that would be awesome (I have already spent two days looking at this code and I see no feasible way of doing it from that sycall - which has the tee_obj that you say will allow me to access the keys)

Notice that this is important since otherwise I believe we will need a new syscall to handle the request to actual crypto for deletion - something I'd prefer to avoid hence why I'd appreciate some guidance on this.

**Comment by ldts** [comment]
basically something like this will work since it allows me to scan for the watermarks to my keyids; so adding an interface to crypto (instead of the direct call that I am prototyping below) would be sufficient....

although the scanning bit is nasty IMO

```
 const struct tee_file_operations *tee_svc_storage_file_ops(uint32_t storage_id)
 {
 
@@ -504,6 +506,8 @@ TEE_Result syscall_storage_obj_del(unsigned long obj)
        struct tee_ta_session *sess;
        struct tee_obj *o;
        struct user_ta_ctx *utc;
+ uint8_t data[1024];
+ size_t len;
 
        res = tee_ta_get_current_session(&sess);
        if (res != TEE_SUCCESS)
@@ -520,6 +524,11 @@ TEE_Result syscall_storage_obj_del(unsigned long obj)
        if (o->pobj == NULL || o->pobj->obj_id == NULL)
                return TEE_ERROR_BAD_STATE;
 
+ len = o->info.dataSize;
+ res = o->pobj->fops->read(o->fh, o->info.dataPosition, data, &len);
+ if (res == TEE_SUCCESS)
+         se050_delete_persistent_key(data, len);
+
        res = o->pobj->fops->remove(o->pobj);
        tee_obj_close(utc, o);
```

**Comment by jenswi-linaro** [comment]
You obviously have a bunch of out of tree patches which you're working with. Perhaps you should direct your questions to the author of those patches.

**Comment by ldts** [comment]
what are you referring to? what information are you missing in this thread to be able to provide with guidance?

**Comment by ldts** [comment]
@clementfaure you maintain the crypto interface so maybe I should be posting the question to you directly? please let me know if you need additional information but the idea is to be able to delete private keys stored in crypto devices at the time the public keys are removed from storage. Should the removal be done in two separate steps, or should we allow storage to access crypto for deletion?

**Comment by jenswi-linaro** [comment]
> what are you referring to? what information are you missing in this thread to be able to provide with guidance?

`se050_delete_persistent_key()` is not a function in mainline OP-TEE. Now I realize that this function is perhaps part of that crypto driver/library that you mentioned some time ago in some issue or PR.

**Comment by ldts** [comment]
ok so you are referring to my work then and you misunderstood the example, that is ok: that is a new function that I am doing that illustrates how to handle the issue that I described since AFAICS there is no way to know the location of the key. Anyhow I am wondering if it should be a generic crypto interface (obviously not the hack I put there) and delegate the search to the crypto layer.

for reference I integrated the SE050 stack (~30K LOCK of userspace code) and did the necessary adapters to support crypto (plus two i2c drivers).

if you are interested the work is here https://github.com/ldts/optee_os/commits/se050; however it is irrelevant to the discussion really and not that interesting (is just work...)

**Comment by jenswi-linaro** [comment]
I expect that the needed bookkeeping is done in `struct tee_obj` or some struct that can be found via this struct. We don't have infrastructure for what you're describing so you'll need to add something that you think makes sense. I don't expect that any new syscall will be needed. If it's possible to take advantage of the driver/crypto_api that @clementfaure and others are adding that's a nice bonus.
