### ISSUE TITLE
Failure for QEMU build

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#3882]
Steps followed:
1)mkdir -p <optee-project>
2)cd <optee-project>
3)repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml -b 3.9.0
4)repo sync -j4 --no-clone-bundle
5)make -j2 toolchains
6)make -j `nproc` --> fails with below log:

  CC      drivers/net/ethernet/amd/xgbe/xgbe-pci.o
  CC      drivers/net/mii.o
drivers/net/phy/mdio-xgene.c:466:1: fatal error: error writing to /tmp/ccc9KVDs.s: No space left on device
 MODULE_LICENSE("GPL");
 ^~~~~~
compilation terminated.
scripts/Makefile.build:265: recipe for target 'drivers/net/phy/mdio-xgene.o' failed
make[4]: *** [drivers/net/phy/mdio-xgene.o] Error 1
scripts/Makefile.build:503: recipe for target 'drivers/net/phy' failed
make[3]: *** [drivers/net/phy] Error 2
make[3]: *** Waiting for unfinished jobs....
  AR      drivers/mtd/nand/spi/built-in.a
drivers/mmc/host/dw_mmc-exynos.c:603:1: fatal error: error writing to /tmp/ccuT4mU4.s: No space left on device
 MODULE_ALIAS("platform:dwmmc_exynos");
 ^~~~~~
compilation terminated.
scripts/Makefile.build:265: recipe for target 'drivers/mmc/host/dw_mmc-exynos.o' failed
make[4]: *** [drivers/mmc/host/dw_mmc-exynos.o] Error 1
scripts/Makefile.build:503: recipe for target 'drivers/mmc/host' failed
make[3]: *** [drivers/mmc/host] Error 2
drivers/mtd/spi-nor/spi-nor.c:5379:1: fatal error: error writing to /tmp/ccmuNA9N.s: No space left on device
 MODULE_DESCRIPTION("framework for SPI NOR");
 ^~~~~~
compilation terminated.
scripts/Makefile.build:503: recipe for target 'drivers/mmc' failed
make[2]: *** [drivers/mmc] Error 2
make[2]: *** Waiting for unfinished jobs....
scripts/Makefile.build:265: recipe for target 'drivers/mtd/spi-nor/spi-nor.o' failed
make[4]: *** [drivers/mtd/spi-nor/spi-nor.o] Error 1
scripts/Makefile.build:503: recipe for target 'drivers/mtd/spi-nor' failed
make[3]: *** [drivers/mtd/spi-nor] Error 2
make[3]: *** Waiting for unfinished jobs....
  CC      drivers/mtd/nand/core.o
  AR      drivers/mtd/tests/built-in.a
  CC      drivers/net/ethernet/apm/xgene/xgene_enet_hw.o
  CC      drivers/net/ethernet/amd/xgbe/xgbe-debugfs.o
scripts/Makefile.build:265: recipe for target 'drivers/net/ethernet/amd/xgbe/xgbe-pci.o' failed
make[6]: *** [drivers/net/ethernet/amd/xgbe/xgbe-pci.o] Error 1
make[6]: *** Waiting for unfinished jobs....
  AR      drivers/net/ethernet/aquantia/built-in.a
  AR      drivers/mtd/nand/raw/built-in.a
  AR      drivers/net/ethernet/arc/built-in.a
  CC      drivers/mtd/nand/bbt.o
  AR      drivers/net/ethernet/atheros/built-in.a
  CC      drivers/net/ethernet/apm/xgene/xgene_enet_sgmac.o
  AR      drivers/net/ethernet/aurora/built-in.a
  CC      drivers/net/ethernet/broadcom/bgmac.o
  CC      drivers/net/ethernet/apm/xgene/xgene_enet_xgmac.o
scripts/Makefile.build:503: recipe for target 'drivers/net/ethernet/amd/xgbe' failed
make[5]: *** [drivers/net/ethernet/amd/xgbe] Error 2
scripts/Makefile.build:503: recipe for target 'drivers/net/ethernet/amd' failed
make[4]: *** [drivers/net/ethernet/amd] Error 2
make[4]: *** Waiting for unfinished jobs....
  CC      drivers/net/ethernet/broadcom/bgmac-platform.o
  AR      drivers/mtd/nand/built-in.a
scripts/Makefile.build:503: recipe for target 'drivers/mtd' failed
make[2]: *** [drivers/mtd] Error 2
  CC      drivers/net/ethernet/apm/xgene/xgene_enet_main.o
scripts/Makefile.build:265: recipe for target 'drivers/net/ethernet/apm/xgene/xgene_enet_hw.o' failed
make[6]: *** [drivers/net/ethernet/apm/xgene/xgene_enet_hw.o] Error 1
make[6]: *** Waiting for unfinished jobs....
drivers/net/ethernet/broadcom/bgmac-platform.c: In function ‘bgmac_nicpm_speed_set’:
drivers/net/ethernet/broadcom/bgmac-platform.c:133:3: warning: this statement may fall through [-Wimplicit-fallthrough=]
   netdev_err(net_dev, "Unsupported speed. Defaulting to 1000Mb\n");
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/broadcom/bgmac-platform.c:135:2: note: here
  case SPEED_1000:
  ^~~~
  AR      drivers/net/ethernet/broadcom/built-in.a
scripts/Makefile.build:503: recipe for target 'drivers/net/ethernet/apm/xgene' failed
make[5]: *** [drivers/net/ethernet/apm/xgene] Error 2
scripts/Makefile.build:503: recipe for target 'drivers/net/ethernet/apm' failed
make[4]: *** [drivers/net/ethernet/apm] Error 2
scripts/Makefile.build:503: recipe for target 'drivers/net/ethernet' failed
make[3]: *** [drivers/net/ethernet] Error 2
scripts/Makefile.build:503: recipe for target 'drivers/net' failed
make[2]: *** [drivers/net] Error 2
Makefile:1693: recipe for target 'drivers' failed
make[1]: *** [drivers] Error 2
make[1]: Leaving directory '/home/sadiqhm/playground/optee_qemu/linux'
common.mk:278: recipe for target 'linux-common' failed
make: *** [linux-common] Error 2

**Comment by saddy-muchu** [comment]
My bad.
It seems to be a disk space issue on my host system.

**Comment by jforissier** [comment]
> Not sure if this is because of a low disk space issue on my host system.

Yes, the error message says so:
```
drivers/net/phy/mdio-xgene.c:466:1: fatal error: error writing to /tmp/ccc9KVDs.s: No space left on device
```
