### ISSUE TITLE
[QA] Confused with OPTEE_MSG_RPC_CMD_SHM_ALLOC . is shm->p and mobj->va should be the same one ?

### ISSUE THREAD

**Issue by sunnybird** [OP-TEE/optee_os#3883]
I add some log at tee_supplicant.c #alloc_shm and #register_local_shm to print shm->p
```
DMSG("shm->p = %p",shm->p);
```
then,
I add some log at thread_optee_smc.c #get_rpc_alloc_res to print mobj->va
```
DMSG("get_rpc_alloc_res mobj->va=%p", mobj_get_va(mobj,0));
```
I run optee-os and optee-client on qemu_v8 . i find that shm->p is different with mobj->va. so i confued.  

**is shm->p and mobj->va should be the same one ?**

```
optee-client log:
DBG [190] TSUP:register_local_shm:370: shm->p = 0x305ec720
```  
```
optee-os log:
D/TC:? 0 get_rpc_alloc_res:555 get_rpc_alloc_res mobj->va=0xf004720
```

**Comment by jenswi-linaro** [comment]
No, they don't have to be the same. In fact it's not very likely that they ever are since they are from different translations regimes. Note that the lower 12 bits are the same though, since the smallest unit is 4kB.

**Comment by sunnybird** [comment]
thanks . i  get it .
