### ISSUE TITLE
How to config CFG_TZC400 at qemu_v8 platfrom

### ISSUE THREAD

**Issue by sunnybird** [OP-TEE/optee_os#3887]
I find that qemu_v8 does not config TZASC .
why?

**Comment by jforissier** [comment]
Does the QEMU `virt` platform support TZASC?

**Comment by sunnybird** [comment]
@jforissier 
Is it essential to config TZASC for optee-os ?  what decide whether to config TZASC ?
thanks.

**Comment by vchong** [comment]
@sunnybird TZASC isn't essential for development platforms but nice to have to test, check or verify memory protection. Not every platform supports it though. See [1] for more related info.

[1] https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html?highlight=tzasc#memory-firewalls-tzasc

**Comment by sunnybird** [comment]
@vchong i have one question.
1. optee used TZASC to guarantee the data safety. in my knowledge. if the platfom does not support TZASC. how to ensure data security. 
Is my understanding wrong?

**Comment by jenswi-linaro** [comment]
The security state of the memory and devices is hard code into the QEMU virt model.
