### ISSUE TITLE
fatal: unable to auto-detect email address

### ISSUE THREAD

**Issue by promach** [OP-TEE/optee_os#3889]
I am trying to follow the installation steps from https://optee.readthedocs.io/en/latest/faq/faq.html, but I have the following error.

```
$ sudo apt-get install [pre-reqs]
$ mkdir optee-qemu && cd optee-qemu
$ repo init -u https://github.com/OP-TEE/manifest.git
$ repo sync
$ cd build
$ make toolchains -j2
$ make run
QEMU console:         (qemu) c
Normal world shell:   # xtest
```

> rog@rog-GL502VMK:\~/Downloads/optee_os/optee-qemu$ git config user.email "myemail@hotmail.com"
> rog@rog-GL502VMK:\~/Downloads/optee_os/optee-qemu$ repo init -u https://github.com/OP-TEE/manifest.gitrepo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.
> 
> ... A new version of repo (2.5) is available.
> ... New version is available at: /home/rog/Downloads/optee_os/optee-qemu/.repo/repo/repo
> ... The launcher is run from: /usr/bin/repo
> !!! The launcher is not writable.  Please talk to your sysadmin or distro
> !!! to get an update installed.
> 
> 
> Traceback (most recent call last):
>   File "/home/rog/Downloads/optee_os/optee-qemu/.repo/repo/main.py", line 628, in <module>
>     _Main(sys.argv[1:])
>   File "/home/rog/Downloads/optee_os/optee-qemu/.repo/repo/main.py", line 602, in _Main
>     result = run()
>   File "/home/rog/Downloads/optee_os/optee-qemu/.repo/repo/main.py", line 595, in <lambda>
>     run = lambda: repo._Run(name, gopts, argv) or 0
>   File "/home/rog/Downloads/optee_os/optee-qemu/.repo/repo/main.py", line 264, in _Run
>     result = cmd.Execute(copts, cargs)
>   File "/home/rog/Downloads/optee_os/optee-qemu/.repo/repo/subcmds/init.py", line 522, in Execute
>     self._ConfigureUser(opt)
>   File "/home/rog/Downloads/optee_os/optee-qemu/.repo/repo/subcmds/init.py", line 381, in _ConfigureUser
>     name = self._Prompt('Your Name', mp.UserName)
>   File "/home/rog/Downloads/optee_os/optee-qemu/.repo/repo/project.py", line 1026, in UserName
>     self._LoadUserIdentity()
>   File "/home/rog/Downloads/optee_os/optee-qemu/.repo/repo/project.py", line 1039, in _LoadUserIdentity
>     u = self.bare_git.var('GIT_COMMITTER_IDENT')
>   File "/home/rog/Downloads/optee_os/optee-qemu/.repo/repo/project.py", line 3411, in runner
>     (self._project.name, name, p.stderr))
> error.GitError: manifests var: 
> *** Please tell me who you are.
> 
> Run
> 
>   git config --global user.email "you@example.com"
>   git config --global user.name "Your Name"
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.
> 
> fatal: unable to auto-detect email address (got 'rog@rog-GL502VMK.(none)')
> 
> rog@rog-GL502VMK:\~/Downloads/optee_os/optee-qemu$ 
>

**Comment by sunnybird** [comment]
have you set git user.email and user.name ? to confirm
```
 git config --get user.email
 git config --get user.name
``

**Comment by promach** [comment]
```
rog@rog-GL502VMK:~/Downloads/optee_os/optee-qemu$ git config --get user.email
myemail@hotmail.com
rog@rog-GL502VMK:~/Downloads/optee_os/optee-qemu$ git config --get user.name
rog
rog@rog-GL502VMK:~/Downloads/optee_os/optee-qemu$ 
```

**Comment by jbech-linaro** [comment]
Maybe worth paying attention to this line also.
```
rog@rog-GL502VMK:~/Downloads/optee_os/optee-qemu$ repo init -u https://github.com/OP-TEE/manifest.gitrepo: warning: Python 2 is no longer supported; Please upgrade to Python 3.6+.
```

**Comment by promach** [comment]
> ./.repo/repo/repo init -u https://github.com/OP-TEE/manifest.git

that python version warning will go away if I just run the above command, but the email check error persists

**Comment by jbech-linaro** [comment]
Oki, sorry for not being able to help you. This runs in our automated testing for both QEMU and HiKey several times a day and we haven't seen that issue.

**Comment by promach** [comment]
When I try to bypass the email and username check, I have the following error :

>   File "/home/rog/Downloads/optee_os/optee-qemu/.repo/repo/project.py", line 3412, in runner
>     r = p.stdout
> AttributeError: 'GitCommand' object has no attribute 'stdout'

```
    def __getattr__(self, name):
      """Allow arbitrary git commands using pythonic syntax.

      This allows you to do things like:
        git_obj.rev_parse('HEAD')

      Since we don't have a 'rev_parse' method defined, the __getattr__ will
      run.  We'll replace the '_' with a '-' and try to run a git command.
      Any other positional arguments will be passed to the git command, and the
      following keyword arguments are supported:
        config: An optional dict of git config options to be passed with '-c'.

      Args:
        name: The name of the git command to call.  Any '_' characters will
            be replaced with '-'.

      Returns:
        A callable object that will try to call git with the named command.
      """
      name = name.replace('_', '-')

      def runner(*args, **kwargs):
        cmdv = []
        config = kwargs.pop('config', None)
        for k in kwargs:
          raise TypeError('%s() got an unexpected keyword argument %r'
                          % (name, k))
        if config is not None:
          for k, v in config.items():
            cmdv.append('-c')
            cmdv.append('%s=%s' % (k, v))
        cmdv.append(name)
        cmdv.extend(args)
        p = GitCommand(self._project,
                       cmdv,
                       bare=self._bare,
                       gitdir=self._gitdir,
                       capture_stdout=True,
                       capture_stderr=True)
        #if p.Wait() != 0:
        #  raise GitError('%s %s: %s' %
        #                 (self._project.name, name, p.stderr))
        r = p.stdout
        if r.endswith('\n') and r.index('\n') == len(r) - 1:
          return r[:-1]
        return r
      return runner
```

**Comment by promach** [comment]
it seems like using --global option when setting the values of value and name solved the problem

**Comment by jbech-linaro** [comment]
Glad you got it sorted, thanks for mentioning the solution.
