### ISSUE TITLE
Performance issue on sunxi-sun50i_a64 platform 

### ISSUE THREAD

**Issue by jpmiceli** [OP-TEE/optee_os#3890]
I'm facing performance issue with `sunxi-sun50i_a64` platform.

I'm doing GCM ciphering of buffers of ~1.8Mbit sliced in 512k _packets_. Each packet is sent to `Optee` for encryption. 

The encryption duration is **~13 seconds** on sunxi platform. 

Same test in qemu/vexpress platform: the encryption duration is only **~3 seconds**. It still is slow, but expected as it is a virtual environment.    

I also did some tests in Linux in Sunxi platform (1.8Mbits buffer):
* AES CBC 256, using openssl lib: 20ms 
* GCM, using libtomcrypt as in optee: ~2 seconds. Still slow but much faster than in optee

Some more info:
* Linux is in 32bits on both platforms 
* Optee is 64bits on Sunxi and 32bits on vexpress platforms
* GCM used 256bits key

Any suggestions or idea about the root cause of this issue ?

Thanks for your help

**Comment by jforissier** [comment]
Hi @jpmiceli,

No idea what could be wrong, perhaps you can throw a few debug trace with timestamps (`read_cntpct()`) at strategic places? Or enable ftrace as explained here: https://optee.readthedocs.io/en/latest/debug/ftrace.html#ftrace.

**Comment by jpmiceli** [comment]
Hi @jforissier,

Thanks for your support, I missed `ftrace` feature... I tried it and it worked just fine in qemu/vexpress. In Merdia, I got a panic with `TEE_ERROR_TARGET_DEAD` error code. I've not investigated on this issue yet.

**Comment by jpmiceli** [comment]
Hi all,

I've done some performances test in Linux/REE directly, using `OpenSSL` & `libtomcrypt`. It appears  that `libtomcrypt` perf as not good on this SUNXI platform.

So, I play with `CFG_CRYPTO_AES_GCM_FROM_CRYPTOLIB` crypto config:

* `CFG_CRYPTO_AES_GCM_FROM_CRYPTOLIB = y` gave the result presented above (really bad performances) 
* `CFG_CRYPTO_AES_GCM_FROM_CRYPTOLIB = n`: Encryption/decryption test failed.

I've made no changes in the TA code. Is there any reason `CFG_CRYPTO_AES_GCM_FROM_CRYPTOLIB = n` to not work (it is the default configuration)

Thanks for your support

**Comment by jforissier** [comment]
Hi @jpmiceli ,

> Is there any reason `CFG_CRYPTO_AES_GCM_FROM_CRYPTOLIB = n` to not work (it is the default configuration)

No, it shouldn't fail. What is the problem exactly? Does `xtest 4005` pass?

**Comment by jpmiceli** [comment]
Hi @jforissier,

Oups, I forgot to describe the error, sorry...

An Tag error is triggered at decryption (code: 0xffff3071 == TEE_ERROR_MAC_INVALID). I checked the buffer content and it is ok.

**Comment by jpmiceli** [comment]
I didn't port `xtest` on my environment.

**Comment by jpmiceli** [comment]
Hi all,

I'm back on this performance issue. 
Is there an easy way to check if the `caches` are enabled on my platform ? 

Thanks for your help
J-P

**Comment by jenswi-linaro** [comment]
Caches are normally enabled. To make certain check `SCTLR`. Memory is normally mapped as normal cached memory, but to make certain that's the case you could dump you're translation tables by setting `DEBUG_XLAT_TABLE` to `1` in `core/arch/arm/mm/core_mmu_lpae.c`.

**Comment by jpmiceli** [comment]
Hi @jenswi-linaro,

Thanks for the proposal.

I read back `SCTLR` and caches are correctly enabled. I will continue my investigation

**Comment by jpmiceli** [comment]
Hi @jenswi-linaro,

`SCTLR` shows that the Instruction and data caches are well enabled.

About `DEBUG_XLAT_TABLE`, what is the meaning of the MMU flags ?

Thanks for your help
J-P

**Comment by jenswi-linaro** [comment]
> `SCTLR` shows that the Instruction and data caches are well enabled.

OK

> 
> About `DEBUG_XLAT_TABLE`, what is the meaning of the MMU flags ?

Which MMU flags?

**Comment by jpmiceli** [comment]
Hi @jenswi-linaro,

I meant how to read the info provided by 'DEBUG_XLAT_TABLE` ? It seems that the last value printed is flags, non ?

Thanks for your help
J-P

**Comment by jenswi-linaro** [comment]
As it says at: https://github.com/OP-TEE/optee_os/blob/d2bd4bdb4e102d937045656b3aab401221742ea7/core/include/mm/tee_mmu_types.h#L72
It's the TEE_MATTR_* defines. In your case you're mostly interested in:
``` C
#define TEE_MATTR_CACHE_MASK    0x7
#define TEE_MATTR_CACHE_SHIFT   12
/* These are shifted TEE_MATTR_CACHE_SHIFT */
#define TEE_MATTR_CACHE_NONCACHE 0
#define TEE_MATTR_CACHE_CACHED  1

**Comment by jpmiceli** [comment]
Hi @jenswi-linaro,

Thanks for the info.
