### ISSUE TITLE
optee os will hang up after linux warm boot...

### ISSUE THREAD

**Issue by rock369** [OP-TEE/optee_os#3893]
Hello experts:
Because i porting OPTEE OS on ArmV7  platform. 
My boot flow is Uboot--> optee--> linux
Now we  do a soft reboot in Linux, the optee will hang up

assertion 'poolset->freelist.ql.flink->ql.blink == &poolset->freel                                                             ist' failed at lib/libutils/isoc/bget.c:1063 <bpool>

it was happened  100%  after Linux soft reboot(we use reboot commad to restart system ).
My question:
Does I need do something during Linux Soft reboot, for example, release OPTEE buffer or something?  

![image](https://user-images.githubusercontent.com/42917432/83018323-adff2580-a057-11ea-965b-23d2a096309d.png)

**Comment by jforissier** [comment]
> assertion 'poolset->freelist.ql.flink->ql.blink == &poolset->freelist' failed at lib/libutils/isoc/bget.c:1063

This looks like some memory corruption occured in the heap. Perhaps you can add some more debugging info around this `assert()`, for example print the pointer values or dump the memory around the problematic pointers?

**Comment by rock369** [comment]
Hello
I check my code it is my coding error. I do not free memory.  It is not OPTEE problem.
Please close it.
