### ISSUE TITLE
How to config CFG_TZDRAM_BASE & CFG_TZDRAM_SIZE ，CFG_SHEME_START&CFG_SHEME_SIZE

### ISSUE THREAD

**Issue by sunnybird** [OP-TEE/optee_os#3897]
we can config CFG_TZDRAM_BASE & CFG_TZDRAM_SIZE ，CFG_SHEME_START&CFG_SHEME_SIZE at plat-xxx/conf.mk , but how can i get this value ?

**Comment by etienne-lms** [comment]
> but how can i get this value ?

Do you mean "how to choose the values for these config switches?"
If so, have a look at [generic_ram_layout.h](https://github.com/OP-TEE/optee_os/blob/3.9.0/core/arch/arm/include/mm/generic_ram_layout.h).
Values depend on the memory layout of your platform.

**Comment by sunnybird** [comment]
@etienne-lms 
to ensure the value of CFG_TZDRAM_BASE and CFG_SHEME_START，I need to know about the memory layout of my platform. right ?
