### ISSUE TITLE
Understanding RPMB Authentication Key

### ISSUE THREAD

**Issue by tzewantp** [OP-TEE/optee_os#3900]
Dear Team,

I would like to check whether my understanding of the writing of the RPMB authentication key is correct. 

I have referred to the following issues - (https://github.com/OP-TEE/optee_os/issues/3555) and (https://github.com/OP-TEE/optee_os/issues/975), and wish to obtain some more insights.

Whenever a TA is run, it calls tee_rpmb_init(), which in turns call tee_rpmb_key_gen().  This function, tee_rpmb_key_gen() will then generate the authentication key for the RPMB. Being a shared key, a set is written to the TEE key manager.  At this same time (when tee_rpmb_init is called), the tee-supplicant is invoked to write this same shared key to the RPMB in the eMMC. It does so through the normal world, since only the normal world has the eMMC driver.  
 
Thank you for your time.

Kind regards.

**Comment by Emantor** [comment]
Note that the Key is only sent to the tee-supplicant to write to the eMMC if `CFG_RPMB_WRITE_KEY` is set to `y`. This should be done in a factory or setup environment to ensure that the key can't be extracted while within the Linux environment. Production deployments should always set `CFG_RPMB_WRITE_KEY` to `n` to ensure that OP-TEE does not pass the RPMB key to the normal world.
This also means that you'll need to OP-TEE version if you want to deploy OP-TEE in production, one with `CFG_RPMB_WRITE_KEY` set and one as the final running version on your device.

**Comment by tzewantp** [comment]
Thanks @Emantor for your explanation. I have taken note that 2 OP-TEE versions are needed.

**Comment by sys-temd** [comment]
@Emantor If RPMB AuthKey is also stored in RPMB block, how is it secured against physically extracting key from eMMC?

**Comment by Emantor** [comment]
> @Emantor If RPMB AuthKey is also stored in RPMB block, how is it secured against physically extracting key from eMMC?

The eMMC stores the RPMB key and denies any read access. The RPMB key is not stored within the RPMB partition itself, but rather by a mechanism specific to the eMMC. The eMMC does not provide any access to the RPMB key.
