### ISSUE TITLE
ARMv8 assembler question

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3903]
I am testing OP-TEE built with Clang 10.0.0 on HiKey. I experienced a TEE core panic (data alignmenf fault) and I don't understand the reason.

The crash dump:
```
E/TC:5 0 Core data-abort at address 0x3f04f004 (alignment fault)
E/TC:5 0  esr 0x96000021  ttbr0 0x200003f0ac0a0   ttbr1 0x00000000   cidr 0x0
E/TC:5 0  cpu #5          cpsr 0x80000004
E/TC:5 0  x0  0000000040011fa8 x1  000000003f088f08
E/TC:5 0  x2  000000003f01af0c x3  0000008000010100
E/TC:5 0  x4  000000003f067736 x5  0000000000000030
E/TC:5 0  x6  000000000000002d x7  0000000000000000
E/TC:5 0  x8  000000003f055280 x9  000000003f04f000
E/TC:5 0  x10 000000003f0b7dbf x11 0000000000000000
E/TC:5 0  x12 00000000fffffff8 x13 0000000000000008
E/TC:5 0  x14 000000003f0691cf x15 0000000000000000
E/TC:5 0  x16 000000003f0b7d0d x17 000000003f0b7f40
E/TC:5 0  x18 000000003f0691aa x19 000000003f088f08
E/TC:5 0  x20 0000000000000025 x21 000000003f04f000
E/TC:5 0  x22 000000003f089030 x23 0000000040011fa8
E/TC:5 0  x24 000000003f088f08 x25 000000003f062193
E/TC:5 0  x26 00000000f0100003 x27 000000003f067511
E/TC:5 0  x28 000000003f069690 x29 000000003f0b7f60
E/TC:5 0  x30 000000003f01db40 elr 000000003f00595c
E/TC:5 0  sp_el0 000000003f0b7f60
E/TC:5 0 TEE load address @ 0x3f000000
E/TC:5 0 Core data-abort at address 0x3f04f004 .debug_loc+323588 (alignment fault)
E/TC:5 0 Call stack:
E/TC:5 0  0x000000003f00595c find_early_ta at optee_os/core/arch/arm/kernel/early_ta.c:28
E/TC:5 0  0x000000003f01db3c system_open_ta_binary at optee_os/core/pta/system.c:259
E/TC:5 0  0x000000003f006320 pseudo_ta_enter_invoke_cmd at optee_os/core/arch/arm/kernel/pseudo_ta.c:199
E/TC:5 0  0x000000003f01c62c tee_ta_invoke_command at optee_os/core/kernel/tee_ta_manager.c:761
E/TC:5 0  0x000000003f02242c syscall_invoke_ta_command at optee_os/core/tee/tee_svc.c:885
E/TC:5 0  0x000000003f01532c tee_svc_do_call at optee_os/core/arch/arm/tee/arch_svc_a64.S:141
E/TC:5 0  0x000000003f008a44 thread_svc_handler at optee_os/core/arch/arm/kernel/thread.c:1378
E/TC:5 0  0x000000003f0040c0 el0_svc at optee_os/core/arch/arm/kernel/thread_a64.S:639
```

The C source code:
```
$ awk 'NR==23,NR==32{print NR" "$0}' core/arch/arm/kernel/early_ta.c
23 static const struct early_ta *find_early_ta(const TEE_UUID *uuid)
24 {
25      const struct early_ta *ta;
26
27      for_each_early_ta(ta)
28              if (!memcmp(&ta->uuid, uuid, sizeof(*uuid)))
29                      return ta;
30
31      return NULL;
32 }
```

The disassembly (`out/arm/core/tee.dmp`):
```
3f005958: f3 03 01 aa                   mov     x19, x1
; /home/jerome/work/optee_repo_hikey/optee_os/core/arch/arm/kernel/early_ta.c:28
3f00595c: a9 42 40 f8                   ldur    x9, [x21, #4]
3f005960: aa c2 40 f8                   ldur    x10, [x21, #12]
3f005964: 0b 30 40 a9                   ldp     x11, x12, [x0]
3f005968: 29 01 0b ca                   eor     x9, x9, x11
3f00596c: 4a 01 0c ca                   eor     x10, x10, x12
3f005970: 29 01 0a aa                   orr     x9, x9, x10
3f005974: 09 01 00 b4                   cbz     x9, #32 <early_ta_open+0x6c>
```

So the culprit would be `ldur    x9, [x21, #4]` with `x21 == 0x3f04f000`. At first glance, this is indeed a unaligned 64-bit access (although we do have `-mstrict-align`), looks weird.
So I tried to find some information on `ldur` and alignment, found this: https://stackoverflow.com/questions/52894765. If this is true the compiler would be in its right to use this instruction with `-mstrict-align`. But then why is the HiKey crashing? And if this is wrong, then why would Clang emit this instruction?

:confused:

**Comment by etienne-lms** [comment]
Is it a side effect of lgcc addons that is outside clang tooclhain and maybe was built without `-mstrict-align`?

**Comment by jforissier** [comment]
> Is it a side effect of lgcc addons that is outside clang tooclhain and maybe was built without `-mstrict-align`?

Interesting idea. I'll check.

About `ldur`: I double checked the Arm ARM, there doesn't seem to be anything special with this instruction regarding alignment checks. `SCTLR.A == 1` means "All instructions that load or store one or more registers have an alignment check that the address being accessed is aligned to the size of the data element(s) being accessed.". So the StackOverflow answer seems to be BS :-/

**Comment by jforissier** [comment]
I have a reduced test case...

```C
/* clang --target=aarch64-linux-gnu -Os -mstrict-align -S test.c -o test.S */
extern char *g;
int memcmp(const void *s1, const void *s2, unsigned long n);

int f(void *c)
{
	return memcmp(g, c, 16);
}
```

...generates:
```
f:                                      // @f
// %bb.0:
	adrp	x8, g
	ldr	x10, [x8, :lo12:g]
	ldr	x9, [x0]
	ldr	x8, [x10]
...
```
Those `ldr` instructions can't be correct, can they???
:open_mouth: :confused:

**Comment by jenswi-linaro** [comment]
It look very strange to me.

**Comment by jforissier** [comment]
I will ask on the LLVM mailing list. Thanks for the feedback.

**Comment by jforissier** [comment]
http://lists.llvm.org/pipermail/llvm-dev/2020-June/141979.html

**Comment by jforissier** [comment]
Clang bug confirmed, see http://lists.llvm.org/pipermail/llvm-dev/2020-June/141985.html.

Present in 9.0.1 and 10.0.0. Will be fixed in 11.0.0 and possibly 10.0.1.

In the mean time, a workaround is to disable alignment check  (`CFG_SCTLR_ALIGNMENT_CHECK=n`). I will create a PR. Note that setting the default to `n` will also help usage of external libraries by TAs as mentioned in the C++ RFC PR (see patch "[Disable alignment check by default](https://github.com/OP-TEE/optee_os/pull/3693/commits/67d0310184ac91d7aa0916abcc9204e4d007b9d1)").

**Comment by jenswi-linaro** [comment]
Default should always be `y` or this option will become useless. Alternatively the poor platforms still at `y` will have to deal with all problems introduced by others.

**Comment by jforissier** [comment]
> Default should always be `y` or this option will become useless. Alternatively the poor platforms still at `y` will have to deal with all problems introduced by others.

IMO the option is effectively useless already. Why would we need it since all the ARMv7 and ARMv8 CPUs support unaligned access natively? In which situation is `y` better than `n`? It is just causing problems I think.

**Comment by jenswi-linaro** [comment]
I checked the ARMv8-A ARM. Roughly summarized it's normal LDR and STR instructions that can do unaligned accesses on normal cached memory, other instructions and memory types will still need well aligned addresses.

I assume that the default for most compilers is to assume `SCTLR.A=0` it simplifies configuration of the compiler. I'm fine with making `CFG_SCTLR_ALIGNMENT_CHECK=n` the default, it will likely not affect platforms choosing to keep `y` that much. By the way, the Linux kernel also uses `SCTLR.A=0`.

I think we should let platform maintainers have a say first before we switch though, if nothing else to make sure that they notice that the default will change.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/3909
