### ISSUE TITLE
[QA] Detail introduction for "ldelf start" 

### ISSUE THREAD

**Issue by sunnybird** [OP-TEE/optee_os#3904]
according to https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#loading-and-preparing-ta-for-execution and optee-os source code,I get some knowledge about "Loading and preparing TA for execution"  call flow.
but , i can not understand the who start ldelf? who can explain the call flow for ldelf?

**Comment by jforissier** [comment]
Hi @sunnybird,

Please see https://github.com/OP-TEE/optee_os/blob/3.9.0/core/arch/arm/kernel/user_ta.c functions `load_ldelf()` and `init_with_ldelf()`.

**Comment by sunnybird** [comment]
@jforissier 
thank you for your response.
I have some ideas about :

1. with call chain `tee_ta_init_user_ta_session -> load_ldelf` , when call `load_ldelf`, will set `user_ta_enter_open_session` as a callback. when ldelf has been load , will call `user_ta_enter_open_session->init_with_ldelf` to load TA binaray.

2. But, what happend when call `load_ldelf` ? , this still a confused issue. in other words,  how  optee-os core communiate with **ldelf** at https://github.com/OP-TEE/optee_os/tree/3.9.0/ldelf

**Comment by jforissier** [comment]
The `ldelf` binary is linked with the TEE binary in the `.rodata` section. The symbol name is `ldelf_data`. There you can find ldelf code + data. The OP-TEE OS core maps this in user space memory and switches to user mode to call it.

**Comment by xyzhao2018** [comment]
But in 3.12, it is different with 3.9, which introduced the syscall in ldelf. 
The syscall table is static const struct syscall_entry ldelf_syscall_table[]
Why use syscall here? 
Because there is already a syscall table, static const struct syscall_entry tee_svc_syscall_table[]. 
How does OPTEE know which syscall will be called as they have the same syscall number?

**Comment by jforissier** [comment]
@xyzhao2018 the description in commit baa5161d50da ("core: ldelf: implement separate syscalls for ldelf") gives some answers, especially on how the proper syscall table is selected. Perhaps @balint-dobszay-arm can give more context as to why this change is beneficial including future use cases maybe.

**Comment by jenswi-linaro** [comment]
Both TAs and SPs are loaded with Ldelf, but TAs and SPs doesn't have the same syscalls. We needed a way for ldelf to access the needed services independent of which type of binary is loaded.

**Comment by xyzhao2018** [comment]
Excuse me, what does "SP" mean here? Thanks.

**Comment by balint-dobszay-arm** [comment]
It stands for Secure Partition, defined by Arm Firmware Framework for Armv8-A.
https://developer.arm.com/documentation/den0077/a
