### ISSUE TITLE
Secure Monitor in ARMv8 architecture

### ISSUE THREAD

**Issue by 21212124** [OP-TEE/optee_os#3907]
Hi,
I want to know a little more about the secure monitor.
Why should the Secure Monitor be located within ATF?
ATF has a Test Secure Payload Dispatcher (TSPD) dispatcher but to interact with the OP-TEE OS do we need OPTEED? why?

**Comment by jenswi-linaro** [comment]
The secure monitor has to be executed at exception level EL3, which happens to be the level used by TF-A. Entry/exit of S-EL1 is not standardized (if you disregard the newly released FF-A https://developer.arm.com/docs/den0077/latest) so each Trusted OS has their own way of doing it.
