### ISSUE TITLE
helloword

### ISSUE THREAD

**Issue by thinhlevinh** [OP-TEE/optee_os#391]
Hello,
It is me again. I found this error. How can I solve it?

In FVP terminal_0

![screenshot from 2015-07-08 00 23 37](https://cloud.githubusercontent.com/assets/11614352/8558882/e7acb110-2507-11e5-96c3-15336779cd77.png)

**Comment by jforissier** [comment]
Hello,

Most probably your root filesystem (`filesystem.cpio.gz`) does not contain the Trusted App binary. It should be `/lib/optee_armtz/8aaaf200-2450-11e4-abe20002a5d5c51b.ta`.
You can fix this by updating `setup_fvp.sh`: add the following line, around line 242:
```
file /lib/optee_armtz/8aaaf200-2450-11e4-abe20002a5d5c51b.ta <path_to_your_TA>/8aaaf200-2450-11e4-abe20002a5d5c51b.ta 444 0 0
```
Then delete `gen_rootfs/filelist-tee.txt` and run `setup_fvp_optee.sh` again. This should re-generate `filesystem.cpio.gz`.

**Comment by thinhlevinh** [comment]
Thank you very much. It worked

Best,

**Comment by crispy-penguin** [comment]
Hi, I have exactly the same problem, but I installed OP-TEE with android repo sync (https://github.com/OP-TEE/manifest/blob/master/README.md) and I cannot locate any setup script for the filesystem.cpio.gz. I have ONCE managed to push files to normal world by editing filelist-tee.txt or filelist-final.txt but I fail to replicate it again (upload/bake in more files). 
Any ideas how to add files to update the filesystem?
Kind regards, 
Crispy

**Comment by crispy-penguin** [comment]
I have found that during make run all (qemu) this executes
cat /root/devel/optee/gen_rootfs/filelist-final.txt /root/devel/optee/gen_rootfs/filelist-tee.txt > /root/devel/optee/gen_rootfs/filelist.tmp
cd /root/devel/optee/gen_rootfs; \
    /root/devel/optee/linux/usr/gen_init_cpio /root/devel/optee/gen_rootfs/filelist.tmp | gzip > /root/devel/optee/gen_rootfs/filesystem.cpio.gz

and new filesystem is created, but adding file /lib/optee_armtz/<myfile> <myFileOnHost> 444 0 0 does nothing.

**Comment by jbech-linaro** [comment]
Hi @crispy-penguin ,

To get a TA (or any file included) in `filesystem.cpio.gz`, the source location (your harddrive on your PC) must be stated and you must also state the destination path on the device which on QEMU are located here `/lib/optee_armtz`. On my setup it lists the following TA's
```
root@Vexpress:/ ls -al /lib/optee_armtz/
total 724
drwxr-xr-x    2 root     root           180 Aug 19 06:31 .
drwxr-xr-x    5 root     root           120 Aug 19 06:31 ..
-r--r--r--    1 root     root        239132 Aug 11 19:43 5b9e0e40-2636-11e1-ad9e0002a5d5c51b.ta
-r--r--r--    1 root     root         87656 Aug 11 19:43 706f6574-7765-6469-77656e6942656665.ta
-r--r--r--    1 root     root         77332 Aug 11 19:43 b689f2a7-8adf-477a-9f9932e90c0ad0a2.ta
-r--r--r--    1 root     root         68148 Aug 11 19:43 c3f6e2c0-3548-11e1-b86c0800200c9a66.ta
-r--r--r--    1 root     root        116208 Aug 11 19:43 cb3e5ba0-adf1-11e0-998b0002a5d5c51b.ta
-r--r--r--    1 root     root         69664 Aug 11 19:43 d17f73a0-36ef-11e1-984a0002a5d5c51b.ta
-r--r--r--    1 root     root         69456 Aug 11 19:43 e6a33ed4-562b-463a-bb7eff5e15a493c8.ta
```

Having that said, the helper makefiles in [build.git](https://github.com/OP-TEE/build) does a search for `*.ta`-files in the folder where the built TA's will be stored. See [this](https://github.com/OP-TEE/build/blob/master/qemu.mk#L209-L210) link. So, that means if you automatically want to have your TA's included you must also make sure that your helloworld.ta could be found on that link. But for just a single TA I believe it is easier just to put the paths to the file hardcoded directly to [qemu.mk](https://github.com/OP-TEE/build/blob/master/qemu.mk#L204) under the `filelist-tee` target. If you do so, then you will have it included everytime automatically if you are using the helper makefiles from the build.git. The exact syntax are stated in @jforissier answer above.

By the way, the target `make run` will update `filesystem.cpio.gz` for you, that is the typical target I'm using myself.

// Regards Joakim
