### ISSUE TITLE
when is op-tee first aware that the normal world is running

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#3910]
I am in the process of upstreaming two I2C drivers: one of them OP-TEE native #3896 , the other one residing in the OP-TEE core and being just a trampoline to the kernel #3905.

The native driver is needed to access a crypto device before the normal world is ready; the trampoline, once the normal world is up.

Do we currently have a way to signal this situation? The way I am currently working with this requirement is as seen in this code snippet
https://github.com/ldts/optee_os/commit/ad24418aef9030168a8d0eadbd9991c540fab519#diff-9cde25a2a3220120099bb41d47ec0bd3R51 

Something achieved via
https://github.com/ldts/optee_os/commit/9822569b07fc8302b3fb3284d0898ac2a84f3cda

Is there a more reasonable way to register for such condition (ie, normal world ready).

**Comment by jenswi-linaro** [comment]
We could add a special initcall (see core/include/initcall.h) like `early_boot_final()` which could be called just before exiting to normal world. That should allow the driver to reconfigure itself.

**Comment by ldts** [comment]
ah, ok thanks. should I have a go or this falls better into maintainers tasks?

**Comment by etienne-lms** [comment]
If willing to propose something, you can get inspiration from https://github.com/OP-TEE/optee_os/pull/3608/commits/fd1f410b2178b91008bee9f83c27e43396df8262.

**Comment by ldts** [comment]
just not sure where to trigger these early_boot_final calls from? before exiting init_primary_helper?

**Comment by etienne-lms** [comment]
I think it is a good start point. Much much is done from there to secure monitor.
From there, maybe an exit sequence could unmap the iomem.

**Comment by ldts** [comment]
yes, just adding an early_boot_final is perfect. thanks @jenswi-linaro ;  I submitted #3917

@etienne-lms should we hold #3896 until this PR in merged and I can add the initcall to unmap its memory as you suggest? or should we do this after this PR?

**Comment by etienne-lms** [comment]
If you're P-R depends on #3917, current #3910 obviously need to wait #3917 is merged.

Another way could be you add the change from #3917 inside this P-R, as initial change/commit so that you get everything from this P-R, as @Emantor did in [#3608](https://github.com/OP-TEE/optee_os/pull/3608/commits).
