### ISSUE TITLE
Disabling the Keymaster TA

### ISSUE THREAD

**Issue by lud0v1c** [OP-TEE/optee_os#3911]
Hello,

I'm working with a Rock960 board, specifically v1.3, and Android 9 (revision 50), which ships with OP-TEE. I have never worked with a TEE before, and for my thesis I need to run this AOSP build _without_ relying on a hardware backed Keymaster - the Keymaster Trusted Application. In theory disabling the TA should force Android to rely on a purely software implementation, which I'm trying to do.

I've combed through some services and device.mk files, but commenting out the references doesn't seem to have an effect. Looking at **rockchip/common/security/optee/optee.mk** I see the rules for copying the already built TA's but just deleting the Keymaster TA won't work.

**Comment by vchong** [comment]
@lud0v1c This isn't a build we did or maintain, so the suggestions below might not work. Best to go to rockchip for support if that happens. Anyway, a search online reveals https://www.96boards.org/documentation/consumer/rock/build/aosp.md.html. Are these the instructions you're following? Did you run `repo init -u https://github.com/96rocks/manifests.git -b rock960-box-9.0 -m rock960-release.xml` for your build? If so, then try removing all the lines have `libRkTeeKeymaster.so` and `libRkTeeGatekeeper.so` under `vendor/rockchip/common/`.

If you've run a build before but never cleaned, then those files will remain in your `out` dir and have to be removed as well. Not sure what the exact path is, but it'd be something like `out/target/product/rock960/vendor/*`.

**Comment by andyzsh68** [comment]
>  In theory disabling the TA should force Android to rely on a purely software implementation, which I'm trying to do.

AFAIK，on android 9, there is no default build-in software km() , you should build the software km  and add it to system manually. Maybe you can get a try. @lud0v1c

**Comment by lud0v1c** [comment]
@vchong Thanks, I will try that. Yes that is the build I'm using, it's the only one that will work on this board unfortunately (for AOSP).
@andyzsh68 Hmm it's still present in the code, and libsoftkeymaster/libsoftkeymasterdevice are still being built and included in the final image, so I imagine I can still use them. Perhaps forcing my way in the KM code itself will work.
