### ISSUE TITLE
Interrupt handling of OPTEE

### ISSUE THREAD

**Issue by kouzili77** [OP-TEE/optee_os#3915]
Hi, kindly guys!

I'm a little confused about the interrupt handling in the OPTEE framework. In the doc, you mentioned terms like secure interrupt and non-secure interrupt. Intuitively, I can understand that secure interrupt should be handled by Monitor or OPTEE OS and non-secure interrupt should be handled by the rich world. Thus, when the core is in the secure world, IPIs (Inter Processor Interrupt) like Linux scheduling or smp_function_call should be handled by Linux in rich world so that triggering the world switching.

And my confusion is, how about PPI (Private Peripheral Interrupt) like high-resolution timer (the arm local timer per-core)? Who would deal with the next_event_setting for the local timer? Secure Monitor or OPTEE? Does OPTEE mask this kind of interrupt? When the core is running in the secure world, who would handle the local timer interrupt? Rich or Secure World?

Anyone's ideas would be greatly helpful!
Thx!

**Comment by kouzili77** [comment]
I mean, none secure timer. the CNTP_EL0 :)

**Comment by jenswi-linaro** [comment]
I assume that those interrupts are configured as non-secure so they will be handled by normal world.

**Comment by kouzili77** [comment]
@jenswi-linaro Thx for your reply!

So interesting is that local timer interrupt seems cannot interrupt the secure world. In the rich world, I manually force the local timer to periodically invoke interrupt in a high frequency and I can observe that in rich os. However my customized interrupt handler function stops being invoked just after the `optee_smccc_smc()` and appears again just after the secure world finish TA execution( around the timing when Linux invoke `optee_rpc_finalize_call()` )

This is how I observed and currently, I have no idea about why it is~

Should it be an issue in the ATF area? Any ideas from you guys would be helpful! Thx :)

**Comment by jenswi-linaro** [comment]
CNTP is saved and restored with `NS_TIMER_SWITCH` in TF-A. Normally you can't rely on normal world using that while the CPU is in secure world.

**Comment by kouzili77** [comment]
> 

> CNTP is saved and restored with `NS_TIMER_SWITCH` in TF-A. Normally you can't rely on normal world using that while the CPU is in secure world.

Right answer! I see the part of the code for saving and restoring CNTP in TF-A. 

Thank you so much jenswi!
