### ISSUE TITLE
-Wconversion warnings when calling reg_pair_to_64(...)

### ISSUE THREAD

**Issue by jbech-linaro** [OP-TEE/optee_os#3918]
By coincidence I stumbled on an [article](https://interrupt.memfault.com/blog/best-and-worst-gcc-clang-compiler-flags#-wconversion) about compiler flags and out of curiosity I enabled `-Wconversion`, which generates a [fair bit of warnings](http://ix.io/2okW) when enabled in OP-TEE. I thought I wanted to give a try to get rid of some of them. However I'm puzzled about how to best resolve the issue in places where we're calling `reg_pair_to_64(...)` [1], for example here:
https://github.com/OP-TEE/optee_os/blob/769d857b9cbf2cbfef1c4d3f64a2b8658ee73d9e/ldelf/sys.c#L87

`va` in that function is a `vaddr_t *va`, which is a typedef for `uintptr_t`. So, it's either 32- or 64-bit, depending on the platform you're compiling for. So, the warning [2] seems legit, we're squeezing in a 64-bit value into a 32-bit value when compiling for a 32-bit platform. The question is how to best resolve this? Changing the parameter `va` here and in many other places to an `uint64_t` doesn't seem like the right approach, casting to a `uint32_t` is also wrong for more than one reason. Should we split up `vaddr_t` into something similar to what we've done with `paddr_t` for `ILP32` and `CFG_CORE_LARGE_PHYS_ADDR`?

I want to hear other peoples opinion here, do you agree with my reasoning and do you have a proposal on how this could be fixed.

[1] https://github.com/OP-TEE/optee_os/blob/956765e24f70d186931d42e79f0a801019085b99/lib/libutils/ext/include/util.h#L152-L155

[2] 
```make
ldelf/sys.c: In function ‘sys_map_zi’:                                                                                                                            
ldelf/sys.c:87:35: warning: conversion from ‘uint64_t’ {aka ‘long long unsigned int’} to ‘uint32_t’ {aka ‘unsigned int’} may change value [-Wconversion]          
   *va = reg_pair_to_64(params.vals[2], params.vals[3]);
```

**Comment by jenswi-linaro** [comment]
`vaddr_t` is the size of pointers that can be used. It doesn't make sense to make it any larger, then we would only get warnings when converting a `vaddr_t` to a regular pointer.

The thing with assigning return value of `reg_pair_to_64()` to a `vaddr_t` is deliberate. We silently ignore the upper 32 bits if `vaddr_t` is a 32-bit value since the upper 32 bits are supposed to be zero and there's nothing sensible to do with the anyway.

Perhaps it's possible to add some special attribute to `vaddr_t` so we don't get this warning for this type. Or we could add a `reg_pair_to_vaddr()`. I'm not sure that the latter is enough, but perhaps it's good enough that we only have a few cases left for `vaddr_t`.

**Comment by jbech-linaro** [comment]
> `vaddr_t` is the size of pointers that can be used. It doesn't make sense to make it any larger, then we would only get warnings when converting a `vaddr_t` to a regular pointer.

Agree.

> The thing with assigning return value of `reg_pair_to_64()` to a `vaddr_t` is deliberate.

Yes, it is, but from a compiler point of view we're doing something "wrong". I played around with adding a macro wrapping the existing call. The below seems to take care of it. I had to cast the reg-parameters to `uint32_t` also, since we have a couple of places where these also are 64-bit values (`sys_map_zi(...)` and a handful more places). I believe these also implicitly have upper bits to zero(?), if not, then we probably have bug. Not sure if this is an approach that makes sense as such. It gets rid of the warnings and with a comment explaining the magic in the macro and why we're doing it, it might be sufficient?

I've tried it on QEMU v7, v8. Warnings are gone and xtest seems to pass with no regressions.

```diff
diff --git a/lib/libutils/ext/include/util.h b/lib/libutils/ext/include/util.h
index 378c0ce9..6092f99d 100644
--- a/lib/libutils/ext/include/util.h
+++ b/lib/libutils/ext/include/util.h
@@ -149,7 +149,9 @@
        }))
 
 #ifndef __ASSEMBLER__
-static inline uint64_t reg_pair_to_64(uint32_t reg0, uint32_t reg1)
+#define reg_pair_to_64(reg0, reg1) \
+       (_reg_pair_to_64((uint32_t)reg0, (uint32_t)reg1) & UINTPTR_MAX)
+static inline uint64_t _reg_pair_to_64(uint32_t reg0, uint32_t reg1)
 {
        return (uint64_t)reg0 << 32 | reg1;
 }
```

**Comment by jenswi-linaro** [comment]
This patch will cause problems when you expect a true 64-bit value from `reg_pair_to_64()` regardless of the pointer width. I'd prefer leaving `reg_pair_to_64()` as it is and add a `reg_pair_to_vaddr()` to take care of the `vaddr_t` assignment problems.

For the rest we may just have to do what's needed on a case by case basis.

**Comment by jbech-linaro** [comment]
> This patch will cause problems when you expect a true 64-bit value from `reg_pair_to_64()` regardless of the pointer width.

I'm probably missing something, on a true 64-bit platform it'd return a full 64-bit value, all bits since `UINTPTR_MAX` is 0xffffffffffffffff? And on a 32-bit platform it'll return a 32-bit value since `UINTPTR_MAX` is 0xffffffff? But based on your comment, I probably have missed something?

**Comment by jenswi-linaro** [comment]
Even on 32-bit platforms it can make sense to use 64-bit values. The global_handle in FF-A is one such thing that I'm using this function for in https://github.com/OP-TEE/optee_os/pull/3908.

The name of the function would also be missleading if it doesn't return a 64-bit value, better to have a name that reflects what it does instead of hiding it.

**Comment by jbech-linaro** [comment]
> Even on 32-bit platforms it can make sense to use 64-bit values. The global_handle in FF-A is one such thing that I'm using this function for in #3908.

Agree, but in this particular function we're either using 64-bit or 32-bit. It's not that we sometimes expect a 32-bit value and sometimes a 64-bit value, when running on 32-bit platforms. Here we always expects one of them (the former), when running a 32-bit platform.

> The name of the function would also be missleading if it doesn't return a 64-bit value, better to have a name that reflects what it does instead of hiding it.

Yes, the macro name would need to be changed, but the function itself would still be correct.

I think I'll drop this for now, it was a side track that I had no plans to work with and just stumbled upon by coincidence. Thanks for the feedback.
