### ISSUE TITLE
About plat_prng_add_jitter_entropy  Error message

### ISSUE THREAD

**Issue by rock369** [OP-TEE/optee_os#3920]
Hello :
 I don't know the error message. it will happen frequency in my platform.
but i only  call RPC to sync Ree time in my CA. and I will record Ree time in my TEE OS. 

 FMSG("0x%02X", (int)acc & ((1 << (bytes * 8)) - 1));
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 what is the meaning?

void plat_prng_add_jitter_entropy(enum crypto_rng_src sid, unsigned int *pnum)
{
......
	if (bytes) {
		FMSG("0x%02X", (int)acc & ((1 << (bytes * 8)) - 1));
		crypto_rng_add_event(sid, pnum, (uint8_t *)&acc, bytes);
	}
}

**Comment by jforissier** [comment]
`FMSG()` is not an error. It is used to print very verbose debug messages.

**Comment by rock369** [comment]
Thanks
