### ISSUE TITLE
Incomplete call stack on core panic

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3921]
Sometimes we have crashes like the following:
```
I/TC: OP-TEE version: 3.8.0-368-gfa8faf27 (clang version 10.0.0) #5 Fri May 29 09:51:03 UTC 2020 aarch64
D/TC:0 0 paged_init_primary:1178 Executing at offset 0 with virtual load address 0x3f000000
D/TC:0 0 check_pa_matches_va:2113 va 0x3b000000 maps 0x3f200000, expect 0x0
E/TC:0 0 Panic at core/arch/arm/mm/core_mmu.c:2114 <check_pa_matches_va>
E/TC:0 0 TEE load address @ 0x3f000000
E/TC:0 0 Call stack:
E/TC:0 0  0x000000003f011fc8
```

Normally we should have a full call stack dump, but we see only one address.
The reasons is apparently due to `print_kernel_stack()` calling `thread_stack_start()` and `thread_stack_size()` which assumes a valid thread context. But in the above case it seems the code is using the temporary stack for core 0. Therefore the unwinding code considers that the stack pointer is outside the stack and refuses to unwind.

It looks like we need some `stack_start()` / `stack_size()` functions that work in all cases.

**Comment by jenswi-linaro** [comment]
Makes sense.

**Comment by jforissier** [comment]
@jenswi-linaro there is something else. `thread_init_boot_thread()` marks thread 0 as active but doesn't switch stack. So if a panic occurs shortly after, we find an active thread and believe that the stack is `stack_thread[0]` while in fact it is `stack_tmp[0]`.

**Comment by jenswi-linaro** [comment]
We can set `THREAD_CLF_TMP` in `thread_core_local[0].flags` and use the flags field to determine which stack is supposed to be in use.

**Comment by jforissier** [comment]
Addressed in https://github.com/OP-TEE/optee_os/pull/3922.
