### ISSUE TITLE
IMSG can't output double format variable

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/optee_os#3927]
Hello,

I tried to output some float or double variables by `IMSG()`.
But I got some strange outputs, for example:
```C
double a = 3.0, b = 4.0;

IMSG("a = %lf, b = %lf", a, b);        // It printed: a = f, b = f
```

When I want to convert double to string in TA, I also found that using `snprintf()` will get the same result.
Are there any other functions to accomplish this?
Thanks.

**Comment by etienne-lms** [comment]
oups... sorry, bad hint.  Actually `%f` is not supported.
see **lib/libutils/ext/snprintk.c** in optee_os.

**Comment by gagachang** [comment]
@etienne-lms , Got it! Thank you for replying.
I'll try to convert the double to integer first.

**Comment by hzcyf** [comment]
Hi gagachang, Why close this if it is still not supported?

**Comment by jbech-linaro** [comment]
> Hi gagachang, Why close this if it is still not supported?

It would still be closed automatically by our bot if there is not activity on the thread. However, in some cases we do add a "label" like "enhancement", "bugfix" etc, then it won't be closed automatically. For this one it sounds like a candidate would be "enhancement".
