### ISSUE TITLE
How to unwind a stack with mixed arm32 instruction and thumb instrustions?

### ISSUE THREAD

**Issue by angelina-zhao** [OP-TEE/optee_os#3928]
I am using optee os v3.5 on an ARMv7 processor.  While compiling the optee os in 32 bits mode, thumb instructions are generated by default.

In case of panic() is triggered, unwind_stack_arm32() is called.  However, the unwind_stack_arm32() fails to unwind the stack.  Sometimes it reports the wrong PC address, or sometimes it traps to an endless loop, keeping printing the same PC address.

I reviewed the codes and found that unwind_stack_arm32() went through the stack using state->registers[SP] values which was ARM-style frame pointers, and I assumed that unwind_stack_arm32() might be not able to handle thumb instrustions.

I did an experiment in which I compiled the optee os with pure arm instrustions (without thumb instructions), and in this case, panic() gave the correct stack backtrace.

Since thumb instruction can save the rooms for both storage and memory, I prefer to using the thumb instructions during the build.  So, how to unwind a stack with mixed arm32 instruction and thumb instrustions with optee os?

Thank you very much.

**Comment by jenswi-linaro** [comment]
I'm afraid stack unwind is only supported for arm32 at the moment. If you can get it to work with mixed mode we'd be interested in the patches.

**Comment by angelina-zhao** [comment]
Thanks for the quick confirmation.
I plan to look more further into this, and if I succeed, I will come back and update it here.

Should I close this issue right now?  Or leave it opened so I can update my further findings under this topic in the future?

**Comment by jforissier** [comment]
@angelina-zhao thanks. You may leave this opened, no problem. Older issues are flagged then closed automatically anyway.

Now regarding the unwind issue... may I propose that we simply remove the thumb code altogether? I don't think we have much of it, do we? Does it make a big difference in code size? What is the advantage of keeping it?

**Comment by etienne-lms** [comment]
with `CFG_WITH_PAGER=y`, code size is of importance in Core.
Applies also to TAs with `CFG_PAGED_USER_TA=y`.

**Comment by jforissier** [comment]
@etienne-lms true.

**Comment by angelina-zhao** [comment]
> @angelina-zhao thanks. You may leave this opened, no problem. Older issues are flagged then closed automatically anyway.
> 
> Now regarding the unwind issue... may I propose that we simply remove the thumb code altogether? I don't think we have much of it, do we? Does it make a big difference in code size? What is the advantage of keeping it?

Here comes the details of the thumb impact on the code size.  It turns out that with thumb instructions we can save about 20% in code size.

ARM32 instruction only: code size is 1180016B.
Program Header:
0x70000001 off    0x000cd448 vaddr 0x810bd448 paddr 0x810bd448 align 2**2
         filesz 0x000039b0 memsz 0x000039b0 flags r--
    LOAD off    0x00010000 vaddr 0x81000000 paddr 0x81000000 align 2**16
         filesz 0x000c7fb0 memsz 0x0011c7c0 flags rwx
   STACK off    0x00000000 vaddr 0x00000000 paddr 0x00000000 align 2**4
         filesz 0x00000000 memsz 0x00000000 flags rwx
private flags = 5000202: [Version5 EABI] [soft-float ABI] [has entry point]

Thumb and ARM32 combined: code size 952256B
Program Header:
0x70000001 off    0x00095448 vaddr 0x81085448 paddr 0x81085448 align 2**2
         filesz 0x00003e20 memsz 0x00003e20 flags r--
    LOAD off    0x00010000 vaddr 0x81000000 paddr 0x81000000 align 2**16
         filesz 0x00090fb0 memsz 0x000e87c0 flags rwx
   STACK off    0x00000000 vaddr 0x00000000 paddr 0x00000000 align 2**4
         filesz 0x00000000 memsz 0x00000000 flags rwx
private flags = 5000202: [Version5 EABI] [soft-float ABI] [has entry point]

**Comment by angelina-zhao** [comment]
I trigger a panic() in my own PTA, and track the unwind process with debug message.

The calling stack should be :
1. prink_kernel_stacks
2. do_panic
3. invoke_command
4. tee_ta_manager.c:760
res = sess->ctx->ops->enter_invoke_cmd(sess, cmd, param, err);

The unwind fails at 3->4, while the LR value is incorrect when returns from unwind_exec_insn().

The ASM code shows that 4->3 use blx, while the rest calls (3->2, 2->1) are using bl.

In user manual, it says that both of them will save the PC to LR, and the only difference is blx may change the ARM state between thumb and arm32.

Is there any any suggestion on this?  Thanks.

**Comment by jenswi-linaro** [comment]
It is expected that the `blx` instruction is used when making a call via a function pointer.
By the way, I looked a bit closer at the unwind code and it seems that both ARM and Thumb mode should work. Of course that doesn't change the fact that it doesn't work for you.

Maybe the unwind data for `invoke_command()` isn't interpreted correctly by `unwind_stack_arm32()` or perhaps `print_kernel_stack()` isn't initializing `struct unwind_state_arm32 state` correctly.

You can check the unwind data with `readelf -u tee.elf`.

**Comment by angelina-zhao** [comment]
sorry for the late reply.

I did more experiments and got more information.

I wrote my PTA and call panic() in the invoke_command callback.  Then, after the Linux is boot up, I use CA to trigger the invoke command which lead to the panic().

Here is the ASM for the invoke command function.  The LR is saved in stack, and the SP decreased for 48, and set r7 = SP + 24, which means the r7 equals to (original SP - 24).

810266e0 <invoke_command>:
invoke_command():
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/pta/asr/pta_rtc.c:64
810266e0:	b580      	push	{r7, lr}
810266e2:	b08c      	sub	sp, #48	; 0x30
810266e4:	af06      	add	r7, sp, #24
810266e6:	60f8      	str	r0, [r7, #12]
810266e8:	60b9      	str	r1, [r7, #8]
810266ea:	607a      	str	r2, [r7, #4]
810266ec:	603b      	str	r3, [r7, #0]
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/pta/asr/pta_rtc.c:65
810266ee:	2306      	movs	r3, #6
810266f0:	f6cf 73ff 	movt	r3, #65535	; 0xffff
810266f4:	617b      	str	r3, [r7, #20]
read_lr():
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/arch/arm/include/arm32.h:257
810266f6:	4673      	mov	r3, lr
810266f8:	613b      	str	r3, [r7, #16]
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/arch/arm/include/arm32.h:258
810266fa:	693b      	ldr	r3, [r7, #16]
invoke_command():
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/pta/asr/pta_rtc.c:70
810266fc:	9304      	str	r3, [sp, #16]
810266fe:	68bb      	ldr	r3, [r7, #8]
81026700:	9303      	str	r3, [sp, #12]
81026702:	2346      	movs	r3, #70	; 0x46
81026704:	9302      	str	r3, [sp, #8]
81026706:	f240 0360 	movw	r3, #96	; 0x60
8102670a:	f2c8 1309 	movt	r3, #33033	; 0x8109
8102670e:	9301      	str	r3, [sp, #4]
81026710:	f240 031c 	movw	r3, #28
81026714:	f2c8 1309 	movt	r3, #33033	; 0x8109
81026718:	9300      	str	r3, [sp, #0]
8102671a:	2301      	movs	r3, #1
8102671c:	2201      	movs	r2, #1
8102671e:	2146      	movs	r1, #70	; 0x46
81026720:	f240 0060 	movw	r0, #96	; 0x60
81026724:	f2c8 1009 	movt	r0, #33033	; 0x8109
81026728:	f04e fc7c 	bl	81075024 <trace_printf>
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/pta/asr/pta_rtc.c:72
8102672c:	2300      	movs	r3, #0
8102672e:	f240 0260 	movw	r2, #96	; 0x60
81026732:	f2c8 1209 	movt	r2, #33033	; 0x8109
81026736:	2148      	movs	r1, #72	; 0x48
81026738:	f240 003c 	movw	r0, #60	; 0x3c
8102673c:	f2c8 1009 	movt	r0, #33033	; 0x8109
81026740:	f7fa f9a4 	bl	81020a8c <__do_panic>
81026744 <is_emmc_boot>:
is_emmc_boot():

The unwind instrustion is listed below.  It set the SP as r7 + 24 and then restore the r7 and R14(LR).   Comparing to the above calculation, original SP = r7 + 24.  So it seems correct that this unwind operation should restore the correct LR.

0x810266e0 <invoke_command>: @0x810a47a8
  Compact model index: 1
  0x97      vsp = r7
  0x05      vsp = vsp + 24
  0x84 0x08 pop {r7, r14}
  0xb0      finish
  0xb0      finish

But, the real unwind process gives the following result:

E/TC:? 0 invoke_command:70 invoke_command 70, cmd = 0xe0351002, lr = 0x81002731
E/TC:1 0 Panic at core/pta/asr/pta_rtc.c:72 <invoke_command>
ERROR:   [0x0] TC: Panic at core/pta/asr/pta_rtc.c:72 <invoke_command>
E/TC:1 0 Call stack:
E/TC:1 0  0x81008b9d
E/TC:1 0  0x81020c83
E/TC:1 0  0x81026745
E/TC:1 0  0x00000000

I assume that 0x81008b9d refers to the print_kernel_stack(), as:
81008b9c <print_kernel_stack>:

0x81020c83 refers to the function call in  panic.c as:
81020c7e:	f7e7 ff8d 	bl	81008b9c <print_kernel_stack>
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/kernel/panic.c:43
81020c82:	2200      	movs	r2, #0

0x81026745 refers to the panic() call in invoke_command as:
81026740:	f7fa f9a4 	bl	81020a8c <__do_panic>
81026744 <is_emmc_boot>:
is_emmc_boot():

However, the unwind failed here, while the correct LR should be 0x81002731, which is printed in my PTA, using EMSG.
E/TC:? 0 invoke_command:70 invoke_command 70, cmd = 0xe0351002, lr = 0x81002731

This is where the invoke_command callback is called, which use "blx r4".
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/arch/arm/kernel/pseudo_ta.c:195
8100271a:	6bbb      	ldr	r3, [r7, #56]	; 0x38
8100271c:	681b      	ldr	r3, [r3, #0]
8100271e:	6a9c      	ldr	r4, [r3, #40]	; 0x28
81002720:	68fb      	ldr	r3, [r7, #12]
81002722:	6b98      	ldr	r0, [r3, #56]	; 0x38
81002724:	687b      	ldr	r3, [r7, #4]
81002726:	681a      	ldr	r2, [r3, #0]
81002728:	f107 0318 	add.w	r3, r7, #24
8100272c:	68b9      	ldr	r1, [r7, #8]
8100272e:	47a0      	blx	r4
81002730:	63f8      	str	r0, [r7, #60]	; 0x3c

my PTA source code is:
static TEE_Result invoke_command(void *pSessionContext __unused,
				 uint32_t nCommandID,
				 uint32_t type __unused,
				 TEE_Param pParams[4] __unused)
{
	int teerst = TEE_ERROR_BAD_PARAMETERS;
	EMSG("%s %d, cmd = 0x%x, lr = 0x%x\n", __func__, __LINE__, nCommandID, read_lr());

	panic();
	return teerst;
}

It seems that unwind can handle "BL" command but failed on "BLX".  or maybe the stack is corrupted...how to confirm this?
Do you have any idea on this?

[tee_dmp.txt](https://github.com/OP-TEE/optee_os/files/4952831/tee_dmp.txt)
[unwind.txt](https://github.com/OP-TEE/optee_os/files/4952819/unwind.txt)
[tee_elf.zip](https://github.com/OP-TEE/optee_os/files/4952981/tee_elf.zip)

**Comment by jenswi-linaro** [comment]
Nice deep dive there. I'd recommend testing this on QEMU virt and break with gdb in the panic. Both to be able to single step and inspect the data but also to compare with the output from the `bt` command in gdb.

**Comment by angelina-zhao** [comment]
I assuem I have root-caused my issue, but I don't know whether it is a corner case in thumb compiler.

When the C code is:

static TEE_Result invoke_command(void *pSessionContext __unused,
				 uint32_t nCommandID,
				 uint32_t type __unused,
				 TEE_Param pParams[4] __unused)
{
	int teerst = TEE_ERROR_BAD_PARAMETERS;
	EMSG("%s %d, cmd = 0x%x\n", __func__, __LINE__, nCommandID);
	panic();

	switch (nCommandID) {
	case CMD_COUNTER_TEST:
		EMSG("CMD_ALARM_TEST is not implemented");
		teerst = TEE_ERROR_NOT_IMPLEMENTED;
		break;
	case CMD_ALARM_TEST:
		EMSG("CMD_ALARM_TEST is not implemented");
		teerst = TEE_ERROR_NOT_IMPLEMENTED;
		break;
	case CMD_1HZ_TEST:
		EMSG("CMD_1HZ_TEST is not implemented");
		teerst = TEE_ERROR_NOT_IMPLEMENTED;
		break;
	default:
		teerst = TEE_ERROR_BAD_PARAMETERS;
		break;
	}

	return teerst;
}

The ASM is:
810266e0 <invoke_command>:
invoke_command():
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/pta/asr/pta_rtc.c:63
810266e0:	b580      	push	{r7, lr}
810266e2:	b08a      	sub	sp, #40	; 0x28
810266e4:	af04      	add	r7, sp, #16
810266e6:	60f8      	str	r0, [r7, #12]
810266e8:	60b9      	str	r1, [r7, #8]
810266ea:	607a      	str	r2, [r7, #4]
810266ec:	603b      	str	r3, [r7, #0]
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/pta/asr/pta_rtc.c:64
810266ee:	2306      	movs	r3, #6
810266f0:	f6cf 73ff 	movt	r3, #65535	; 0xffff
810266f4:	617b      	str	r3, [r7, #20]
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/pta/asr/pta_rtc.c:69
810266f6:	68bb      	ldr	r3, [r7, #8]
810266f8:	9303      	str	r3, [sp, #12]
810266fa:	2345      	movs	r3, #69	; 0x45
810266fc:	9302      	str	r3, [sp, #8]
810266fe:	f240 0354 	movw	r3, #84	; 0x54
81026702:	f2c8 1309 	movt	r3, #33033	; 0x8109
81026706:	9301      	str	r3, [sp, #4]
81026708:	f240 031c 	movw	r3, #28
8102670c:	f2c8 1309 	movt	r3, #33033	; 0x8109
81026710:	9300      	str	r3, [sp, #0]
81026712:	2301      	movs	r3, #1
81026714:	2201      	movs	r2, #1
81026716:	2145      	movs	r1, #69	; 0x45
81026718:	f240 0054 	movw	r0, #84	; 0x54
8102671c:	f2c8 1009 	movt	r0, #33033	; 0x8109
81026720:	f04e fc7c 	bl	8107501c <trace_printf>
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/pta/asr/pta_rtc.c:70
81026724:	2300      	movs	r3, #0
81026726:	f240 0254 	movw	r2, #84	; 0x54
8102672a:	f2c8 1209 	movt	r2, #33033	; 0x8109
8102672e:	2146      	movs	r1, #70	; 0x46
81026730:	f240 0030 	movw	r0, #48	; 0x30
81026734:	f2c8 1009 	movt	r0, #33033	; 0x8109
81026738:	f7fa f9a8 	bl	81020a8c <__do_panic>

8102673c <is_emmc_boot>:
is_emmc_boot():
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/pta/asr/pta_asr_sys_service.c:39
8102673c:	b580      	push	{r7, lr}
8102673e:	b082      	sub	sp, #8
81026740:	af00      	add	r7, sp, #0


Here, I notice that there is no extra instructions after "81026738:	f7fa f9a8 	bl	81020a8c <__do_panic>", so when the unwind() comes here with PC = 8102673d, find_index() returns the wrong index for the next function (is_emmc_boot() here), thus leading to incorrect unwind table data.  As I expect the unwind instructions for invoke_command() will be used, but actually the unwind instructions for is_emmc_boot() is used.

My fix is eliminating the __no_return definition for panic(), and then there will always be serveral extra instructions after __do_panic, and make sure find_index() returns the correct unwind table.

However, I don't think this is a good way.  And I checked other function calls to __do_panic(), there will be serveral extra instrustions after the call, before next function comes, such as:

/home/angelinazhao/my_work_b/atf_finch/optee_os/core/arch/arm/kernel/thread.c:438
81003dfe:	2300      	movs	r3, #0
81003e00:	f64a 3264 	movw	r2, #43876	; 0xab64
81003e04:	f2c8 1208 	movt	r2, #33032	; 0x8108
81003e08:	f44f 71db 	mov.w	r1, #438	; 0x1b6
81003e0c:	f64a 0070 	movw	r0, #43120	; 0xa870
81003e10:	f2c8 1008 	movt	r0, #33032	; 0x8108
81003e14:	f01c fe3a 	bl	81020a8c <__do_panic>
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/arch/arm/kernel/thread.c:439
81003e18:	3720      	adds	r7, #32
81003e1a:	46bd      	mov	sp, r7
81003e1c:	bd80      	pop	{r7, pc}
81003e1e:	bf00      	nop

81003e20 <copy_a0_to_a3>:
copy_a0_to_a3():
/home/angelinazhao/my_work_b/atf_finch/optee_os/core/arch/arm/kernel/thread.c:444
81003e20:	b480      	push	{r7}
81003e22:	b085      	sub	sp, #20 

Do you have any suggestion on this?  Is it a compiler corner case, or I use the panic() incorrectly?  Thanks.

**Comment by jforissier** [comment]
Hi @angelina-zhao ,

Thanks for posting your detailed analysis.

> Here, I notice that there is no extra instructions after "81026738: f7fa f9a8 bl 81020a8c <__do_panic>",

That seems correct to me, at least I don't see any reason why the compiler would add instructions after this call since it is known it can not return.

> so when the unwind() comes here with PC = 8102673d, find_index() returns the wrong index for the next function

Perhaps the PC value is wrong? Should it be 0x81026738, i.e., the address of the branch instruction instead? Where does this value (0x8102673d) come from?

**Comment by jenswi-linaro** [comment]
It looks like this problem could occur with tail called functions too. In those cases the stack pointer and registers has been restored, but we may still find some other function. Or perhaps the compiler inserts some guard in such cases?

**Comment by angelina-zhao** [comment]
> Hi @angelina-zhao ,
> 
> Thanks for posting your detailed analysis.
> 
> > Here, I notice that there is no extra instructions after "81026738: f7fa f9a8 bl 81020a8c <__do_panic>",
> 
> That seems correct to me, at least I don't see any reason why the compiler would add instructions after this call since it is known it can not return.
> 
> > so when the unwind() comes here with PC = 8102673d, find_index() returns the wrong index for the next function
> 
> Perhaps the PC value is wrong? Should it be 0x81026738, i.e., the address of the branch instruction instead? Where does this value (0x8102673d) come from?

More exactly, when cpu reaches 81026738: f7fa f9a8 bl 81020a8c <__do_panic>, it save the 8102673d in to LR, and then branch to __do_panic().

In the unwind process, LR is restored from the stack, which is 8102673d.  Later, 8102673d is used to look for the unwind index, and in this case, it matches the 8102673d to the next function <8102673c <is_emmc_boot>>, instead of the correct function invoke_command().

**Comment by jenswi-linaro** [comment]
So an LR that cannot be used for returning is saved since the compiler knows it will never be needed any way.
One part of the problem is that it's an unconditional `panic()` which results in dead code that is optimized away. Normally you'd have some dynamic `if` check so there would be no dead code.

Why are you using `panic()` in this way? Is it some debugging technique? If so, perhaps we could add a special function that doesn't have the `__no_return` attributes.

**Comment by angelina-zhao** [comment]
I have tried an approach for the fix for my device (armv7), please help to comment whether this is a good way.

In unwind_stack_arm32(), find_index() is called using state->registers[PC]:
state->start_pc = state->registers[PC];
index = find_index(state->start_pc, exidx, exidx_sz);

In unwind_tab(), the PC is usually updated from LR, as:
state->registers[PC] = state->registers[LR];

So, I assume that find_index() actually use the value of LR as function address to search for the index, while it should use the value of PC (according to its original purpose).  This is why a __no_return function may leading to unwind error as the LR points to the next function.

My fix is to minus 1 for the function address in find_index,which means (LR - 1) is used as function address to search for the index.  In this way, find_index() can locate the correct index:
// addr & ~0x1 is to clear the bit 0 for thumb instrustions, and -1 to get the (LR - 1) address for the search.
addr = (addr & ~0x1) - 1;

After this fix, the print_kernel_stack() function should be modified as well, as here the PC is hardcoded to the correct PC, not LR:
state.registers[PC] = (uint32_t)print_kernel_stack;

Since in my fix, the find_index() assume the addr should be the LR, passing "print_kernel_stack" to it will also cause error.  So I adjust the state.registers[PC] to simulate a fake LR, as:
state.registers[PC] = (uint32_t)print_kernel_stack + 4;

This fix works for my case, and I attach the patch here.  Hopes there is more official solution...

[temp_fix_diff.txt](https://github.com/OP-TEE/optee_os/files/4964103/temp_fix_diff.txt)

**Comment by angelina-zhao** [comment]
> So an LR that cannot be used for returning is saved since the compiler knows it will never be needed any way.
> One part of the problem is that it's an unconditional `panic()` which results in dead code that is optimized away. Normally you'd have some dynamic `if` check so there would be no dead code.
> 
> Why are you using `panic()` in this way? Is it some debugging technique? If so, perhaps we could add a special function that doesn't have the `__no_return` attributes.

using panic() here is another story. 

I originally debug the console driver in panic mode, and so I pick up one PTA, and add panic() to produce a valid test case of my console driver.  And then, I encouter this issue, in which the panic() cannot backtrace the stack correctly...

one more question is, it seems the values in the callstack is acutally LR, not the exact PC.  For example:

ERROR:   [0x0] TC: Panic at core/pta/asr/pta_rtc.c:72 <invoke_command>
E/TC:1 0 Call stack:
E/TC:1 0  0x81008e4d
E/TC:1 0  0x81020f37
E/TC:1 0  0x8102695d
E/TC:1 0  0x810029d1
E/TC:1 0  0x810228c3
E/TC:1 0  0x81013169
E/TC:1 0  0x8101338d
E/TC:1 0  0x8101332b
E/TC:1 0  0x81005699
E/TC:1 0  0x810056cb
E/TC:1 0  0x8100628c

and take "E/TC:1 0  0x810029d1" as example, it points to the next instruction of the "blx r4".  Is this an expected behavior?  I have expected that 810029cf here .

810029ce:	47a0      	blx	r4
810029d0:	63f8      	str	r0, [r7, #60]	; 0x3c

**Comment by jenswi-linaro** [comment]
I guess what is the correct address is debatable. What we're printing the the way out of there (because that's what was recorded) while you're looking for the way into there. Normally this means just an offset in the address and for debugging purposes it should be good enough. Trying to instead calculate the calling address is a bit more tricky and we'd like to keep it as simple as possible while still being useful.

The workaround you have above looks OK. We should be able apply something like that. By the way, don't you think that using '- 2' instead of the masking and '- 1' should be OK?

**Comment by angelina-zhao** [comment]
> I guess what is the correct address is debatable. What we're printing the the way out of there (because that's what was recorded) while you're looking for the way into there. Normally this means just an offset in the address and for debugging purposes it should be good enough. Trying to instead calculate the calling address is a bit more tricky and we'd like to keep it as simple as possible while still being useful.
> 
> The workaround you have above looks OK. We should be able apply something like that. By the way, don't you think that using `- 2` instead of the masking and `- 1` should be OK?

I understand about the stack backtrace print design, thanks for your explaination.

For "-2" instead of "mask plus -1", it sounds that -2 should works as well, since ARM32 and ARM64 instructions are more than 2 bytes, and thumb instructions will have bit0 = 1 (thus -2 is also ok).

Will you considering provide an official fix in later release (eg., in a better way)?  Or, I can submit mine as a contribution to this project?

**Comment by jenswi-linaro** [comment]
> For "-2" instead of "mask plus -1", it sounds that -2 should works as well, since ARM32 and ARM64 instructions are more than 2 bytes, and thumb instructions will have bit0 = 1 (thus -2 is also ok).

:+1: 

> 
> Will you considering provide an official fix in later release (eg., in a better way)? Or, I can submit mine as a contribution to this project?

A contribution would be most welcome! :-)

**Comment by tiger20081015** [comment]
> I guess what is the correct address is debatable. What we're printing the the way out of there (because that's what was recorded) while you're looking for the way into there. Normally this means just an offset in the address and for debugging purposes it should be good enough. Trying to instead calculate the calling address is a bit more tricky and we'd like to keep it as simple as possible while still being useful.
> 
@jenswi-linaro, I agree that in most cases it's good enough. But sometimes it's quite confusing.  for example, line 100 causes a data abort because address 0 is accessed.  But with current unwind design, the call stack actually tells me it's line 101. I think it maybe it's not very friendly, at least as far as I know in linux kernel the panic point is precise.    
```
100>------io_write32(0, rng_base + RNG_SEED_VAL);   //
101>------val = io_read32(rng_base + RNG_CTRL);
102>------val |= CTRL_RNG_SEED_EN;             
```        

I did a rough change as below and it seems able to dump the precise positions. Do you think the change is acceptable?
```
 80 @@ -437,8 +453,12 @@ void print_stack_arm32(int level, struct unwind_state_arm32 *state,
 81  {
 82  >------trace_printf_helper_raw(level, true, "Call stack:");
 83  >------do {
 84 +>------//>-----trace_printf_helper_raw(level, true, " 0x%08" PRIx32,
 85 +>------//>----->------->------->-------state->registers[PC]);
 86  >------>-------trace_printf_helper_raw(level, true, " 0x%08" PRIx32,
 87 ->------>------->------->------->-------state->registers[PC]);
 88 +>------>------->------->------->-------((state->registers[PC] & ~0x1) - 2));                                                                                                                           
 89  >------} while (unwind_stack_arm32(state, exidx, exidx_sz, stack, stack_size));
 90  }
```
By the way, when data aborts, I found there were 2 dump stacks, one is for data_abort and the other is for the panic in data_abort. I think the panic dump in data_abort is not very useful. Can we just replace the panic just with while(1)? Thanks in advance. 

```
 33 diff --git a/core/arch/arm/kernel/abort.c b/core/arch/arm/kernel/abort.c
 34 index 33db5f4..2bce94b 100644
 35 --- a/core/arch/arm/kernel/abort.c
 36 +++ b/core/arch/arm/kernel/abort.c
 37 @@ -539,7 +539,8 @@ void abort_handler(uint32_t abort_type, struct thread_abort_regs *regs)
 38  >------>-------if (!handled) {
 39  >------>------->-------if (!abort_is_user_exception(&ai)) {
 40  >------>------->------->-------abort_print_error(&ai);                                                                                                                                                 
 41 ->------>------->------->-------panic("unhandled pageable abort");
 42 +>------>------->------->-------while(1);
 43  >------>------->-------}
 44  >------>------->-------DMSG("[abort] abort in User mode (TA will panic)");
 45  >------>------->-------save_abort_info_in_tsd(&ai);
```

**Comment by jenswi-linaro** [comment]
@tiger20081015, feel free to propose something in a pull request. Since you're talking about to different things it should probably be two different pull requests to avoid getting stuck on unrelated discussions.
