### ISSUE TITLE
PR#3620 - ELF initialization via .init_array doesn't work

### ISSUE THREAD

**Issue by ademyankov** [OP-TEE/optee_os#3930]
Hi, 
   @jforissier, I finally was able to get back to my TA and wanted to move to 3.9.0. I see that you implemented the [PR#3620](https://github.com/OP-TEE/optee_os/pull/3620) to support DT_INIT_ARRAY and DT_FINI_ARRAY.

Well, I am still having trouble to have my ctors to be executed.

I tried both C++ and C way in my TA entry point file, but none seems to work.
```
static void __attribute__((constructor)) marpal_ta_init_ctor(void) {
    DMSG("marpal_ta_init_ctor...");
}

class A {
public:
    A() { DMSG("ctor: A::A()"); }
    ~A() { DMSG("dtor: A::~A()"); }
};

static A instance = A();
```

I suspected that something might be off with my build environment and I modified hello world application with a simple constructor function.
```
static void __attribute__((constructor)) hello_world_ta_ctor(void) {
    DMSG("*** hello_world_ta_ctor...");
}
```
It does not work either.

Also, I haven't noticed any changes to LDS scripts for 3.9.0. For my application, I am using ta.lds from the hello world sample.

**Q1.** Do I have to add any special sauce into the script to enable the support?

I also looked into the [tests](https://github.com/OP-TEE/optee_test/pull/394/commits/b7559fa13f3c59ad65d01aa9b993d4bc8ec5a766) for this PR, and I glanced through the code itself, but I couldn't find any special sauce that I might be missing.

**Q2.** Any clues?

**optee branch**: 3.9.0
**platform**: qemu_v8

**Comment by jforissier** [comment]
Hi @ademyankov ,

> I suspected that something might be off with my build environment and I modified hello world application with a simple constructor function.
> 
> ```
> static void __attribute__((constructor)) hello_world_ta_ctor(void) {
>     DMSG("*** hello_world_ta_ctor...");
> }
> ```
> 
> It does not work either.

Well it does work for me :confused: 

```
D/LD:  ldelf:169 ELF (8aaaf200-2450-11e4-abe2-0002a5d5c51b) at 0x4005c000
D/TC:? 0 tee_ta_close_session:499 csess 0xe17c050 id 1
D/TC:? 0 tee_ta_close_session:518 Destroy session
D/TA:  hello_world_ta_ctor:34 *** hello_world_ta_ctor...
D/TA:  TA_CreateEntryPoint:43 has been called
D/TA:  TA_OpenSessionEntryPoint:72 has been called
I/TA: Hello World!
```

- First the obvious thing... did you forget to set `CFG_TEE_TA_LOG_LEVEL=3`? so that you would not see the debug trace?
- Is there a `hello_world_ta_ctor` symbol in the TA, and a?
  ```
  $ egrep "(hello_world_ta_ctor|INIT_ARRAY)" out-br/build/optee_examples-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.dmp
    INIT_ARRAY           0x000000000000c148
    INIT_ARRAYSZ         0x0000000000000008
  0000000000000020 l     F .text  00000020 hello_world_ta_ctor
  0000000000000020 hello_world_ta_ctor:
  ```

**Comment by jforissier** [comment]
@ademyankov please note this: https://github.com/OP-TEE/optee_os/blob/3.9.0/ta/arch/arm/link.mk#L37-L46.

**Comment by ademyankov** [comment]
@jforissier yes `CFG_TEE_TA_LOG_LEVEL=3` is set.

The hello_world app I build does not have the INIT_ARRAY segment and naturally, hello_world_ta_ctor function is omitted.

**Comment by jforissier** [comment]
OK. You're not using Clang with optimization enabled, by chance? Because http://lists.llvm.org/pipermail/llvm-dev/2020-June/142192.html.

**Comment by ademyankov** [comment]
No, it's gnu gcc:
`aarch64-linux-gnu-gcc (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36)) 8.3.0`

**Comment by jforissier** [comment]
Uh, then I don't know. Have you tried cloning/building a QEMUv8 build environment from scratch? Then you simple `hello_world_ta_ctor()` example should really work...

**Comment by ademyankov** [comment]
I just checked out the entire repo w/ 3.9.0 branch like yesterday. Everything is built from scratch.

**Comment by ademyankov** [comment]
Ok, I got **hello_world** working. Not sure what was the reason, maybe my environment was off, but at least now I got ctor in the binary.
```
egrep "(hello_world_ta_ctor|INIT_ARRAY)" 8aaaf200-2450-11e4-abe2-0002a5d5c51b.dmp
  INIT_ARRAY           0x000000000000c468
  INIT_ARRAYSZ         0x0000000000000008
00000000000001a0 l     F .text  000000000000003c hello_world_ta_ctor
00000000000001a0 <hello_world_ta_ctor>:
hello_world_ta_ctor():
```

**Comment by ademyankov** [comment]
Ok, I got it working for my TA as well! Thanks, @jforissier for your help! --dynamic_list linker flag and the list file was the key to get it working.

**Comment by jforissier** [comment]
Glad you got it working. I'd like to be able to get rid of that `--dynamic_list` option, this is internal stuff that should be better hidden. But I can't see how at the moment.
