### ISSUE TITLE
Suspend To RAM support

### ISSUE THREAD

**Issue by Thekku** [OP-TEE/optee_os#3933]
Hi ,
For supporting S2R (Suspend To RAM) feature in the system, anything needs to be adapted on the optee side. Or it will be completely taken care by Linux as linux is controlling the scheduling.

Thanks

**Comment by Emantor** [comment]
Suspend 2 RAM usually requires a platform specific implementation, at least to my knowledge. One example is `plat-imx`, take a look at the `core/arch/arm/plat-imx/pm/imx7_suspend.c` file and the associated files in this directory to see how suspend is implemented for i.MX7.
