### ISSUE TITLE
tee_client_invoke_func() failed after Linux update to v5.4 kernel

### ISSUE THREAD

**Issue by jpmiceli** [OP-TEE/optee_os#3938]
Hi all,

I had a working environment based on optee_os v3.6 and Linux kernel 4.19.

Since kernel update to version 5.4,  `tee_client_invoke_func()` call fails with `TEE_ERROR_BAD_PARAMETERS` error.

After quick debug, the issue is raised during parameters checking  in optee_os (`set_tmem_param()`).

Is it a known issue ? Should I have to update/align optee_os() to use it with kernel 5.4 ?  

Thanks for your help
J-P

**Comment by jforissier** [comment]
Hi @jpmiceli ,

Not, not a known issue. In principle you should be able to update the kernel without updating anything else (`optee_os` in particular). I fail to see what could be wrong with your configuration. I would suggest bisecting the `drivers/tee` folder to identify the commit that changed the behavior (`git bisect start -- drivers/tee`, `git bisect good`/`bad` etc.).

**Comment by jpmiceli** [comment]
Hi @jforissier ,

Thanks for your support. I will continue the investigation

**Comment by jpmiceli** [comment]
Hi all,

I found the issue. It was an error in the kernel update. Sorry...
