### ISSUE TITLE
Can TA connect to MySQL database?

### ISSUE THREAD

**Issue by jiangbinghua** [OP-TEE/optee_os#3942]
When TA trusted application adds external libmysqlclient library to makefile file in Ta directory, it indicates that symbols cannot be added and format cannot be recognized. What is the reason? I want to connect TA to MySQL database.

**Comment by jforissier** [comment]
Hi @jiangbinghua ,

There is no MySQL database in secure world, so there is no libmysqlclient library for OP-TEE TAs.
