### ISSUE TITLE
How about add Kconfig to optee_os?

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#395]
How about add Kconfig to optee_os? Use xx_defconfig or make menuconfig to choose CONFIG_xx.

**Comment by jforissier** [comment]
Hello MrVan,
Technically, it would probably be a good idea, the problem is that Kconfig is licensed under GPL, which is not compatible with OP-TEE's license. So should we need such a mechanism, we would have to re-implement it from scratch.

**Comment by jbech-linaro** [comment]
Right, we actually had this up as a proposal when the project started, but as Jerome says we unfortunately cannot use it.
