### ISSUE TITLE
libgcc.a not found when building OPTEE on ZCU102

### ISSUE THREAD

**Issue by mye-rutgers** [OP-TEE/optee_os#3950]
Hello,

I am currently trying to deploy OPTEE on ZCU102. The petalinux was installed successfully. However, when I used "make -f zynqmp.mk" from OPTEE build repo to build the system, the errors were shown below. I would truly appreciate it if anyone could provide any guidance or suggestions to solve the issue.

Thank you!

Best Regards,
Mengmei

```
| aarch64-xilinx-linux-ld.bfd: cannot find libgcc.a: No such file or directory
| make: *** [ldelf/link.mk:54: out/arm-plat-zynqmp/ldelf/ldelf.elf] Error 1
| make: *** Waiting for unfinished jobs....
| ERROR: oe_runmake failed
| WARNING: /home/petalinux20182/Research/petalinux/zcu102-2018.2/build/tmp/work/aarch64-xilinx-linux/optee-os/latest+gitAUTOINC+f208f17a1f-r0/temp/run.do_compile.20311:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at /home/petalinux20182/Research/petalinux/zcu102-2018.2/build/tmp/work/aarch64-xilinx-linux/optee-os/latest+gitAUTOINC+f208f17a1f-r0/temp/log.do_compile.20311)
ERROR: Task (/home/petalinux20182/Research/petalinux/zcu102-2018.2/project-spec/meta-user/recipes-bsp/optee-os/optee-os.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3086 tasks of which 2255 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/petalinux20182/Research/petalinux/zcu102-2018.2/project-spec/meta-user/recipes-bsp/optee-os/optee-os.bb:do_compile
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
ERROR: Failed to build project
zynqmp.mk:91: recipe for target 'petalinux-build' failed
make: *** [petalinux-build] Error 255
```

**Comment by mye-rutgers** [comment]
The solution is posted in [here](https://forums.xilinx.com/t5/Embedded-Linux/libgcc-a-not-found-when-building-OPTEE-on-ZCU102/m-p/1121532#M43341).

**Comment by jenswi-linaro** [comment]
Thanks for sharing the solution.

**Comment by AsmX0r** [comment]
Hey @mye-rutgers,

I know this issue is closed for a couple of months now, but I'm facing the exact same issue when following the official documentation (https://optee.readthedocs.io/en/latest/building/devices/zynqmp.html). The thread you linked in your last comment does not directly address the issue with libgcc.a (it seems you stated it did not work there).

Could you please share the steps you have done to fix the issue (if you remember what have been done)? :)

Many thanks!

**Comment by mengmeiye** [comment]
Hi @AsmX0r,

Unfortunately, I don't remember the detailed steps, since I didn't continue this project at that time for other reasons. Sorry about that.

Best Regards,
Mengmei

**Comment by mye-rutgers** [comment]
Hi @AsmX0r,

Unfortunately, I don't remember the detailed steps, since I didn't continue this project at that time for other reasons. Sorry about that. 

Best Regards,
Mengmei

**Comment by AsmX0r** [comment]
The steps to build on that board are now provided in [this issue](https://github.com/OP-TEE/optee_os/issues/4485#issuecomment-803025139).
