### ISSUE TITLE
Accessing SPI using OPTEE-TA

### ISSUE THREAD

**Issue by noufalp** [OP-TEE/optee_os#3957]
Hi,
I am trying to implement SPI support using OPTEE on Hikey960 platform. I have following queries about the implementation.
    1. Can I use non secure Client APIs(Or exported of driver API function) from non secure kernel modules? Instead of using usermode client application, i would like to use kernel module in non secure side.
    2. Is there any document or readme available for implementing SPI support in OP-TEE ?rd

Regards
Noufal P

**Comment by noufalp** [comment]
Hi @vchong  
As per your comments, [https://github.com/OP-TEE/optee_os/issues/3578]. I had gone through this link, are you telling that Hikey960 wont support SPI using OPTEE-TA?

**Comment by vchong** [comment]
@noufalp Not directly from a regular TA since it doesn't have access to core (optee_os) functions. You need to create a PTA [1] and 'call' into it from your CA.

[1] https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html?highlight=pseudo#pseudo-trusted-applications

**Comment by noufalp** [comment]
Thank you @vchong  for the quick reply.  Then by referring stats.c file, it is like direct call from CA using  `TEEC_InvokeCommand()` API and corresponding invoke command function should be defined in the PTA. Am I correct? 

Also can you please provide me information about calling TEE Client API from Kernel module?

**Comment by gagachang** [comment]
@noufalp ,

You can reference this, it's a kernel module to get entropy from OP-TEE.

https://github.com/linaro-swg/linux/blob/optee/drivers/char/hw_random/optee-rng.c

**Comment by vchong** [comment]
@noufalp Yes, you're correct.

2nd question answered by @gagachang - thanks!

**Comment by noufalp** [comment]
@gagachang  thank you for your comment. We are planning to use PTA on OPTEE side since our requirement is to access SPI through OP-TEE. 
I referred the `core/pta/stats.c` for the implementation of PTA, but it was seen that only invoke_command API implementation is found. What about the  open_context() and open_session() APIs called form the user client application? and its corresponding implementation in the PTA? . If we check TA application(hello_world example), we can see two function definition, `TA_CreateEntryPoint()` and `TA_OpenSessionEntryPoint()`.

**Comment by vchong** [comment]
You can see at the bottom of `stats.c`. If needed, just implement in the file itself and register the functions via something like below. Else they'll just not be called in `pseudo_ta.c`. Iinm.

```
pseudo_ta_register(.uuid = STATS_UUID, .name = TA_NAME,
		   .flags = PTA_DEFAULT_FLAGS,
		   .invoke_command_entry_point = invoke_command,
		   .open_session_entry_point = your_func1,
		   .close_session_entry_point = your_func2,
		   .create_entry_point = your_func3,
		   .destroy_entry_point = your_func4);
```

[1] https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/pseudo_ta.c

**Comment by noufalp** [comment]
Thank you for your comments. Now i would like to add SPI support using pseudo TA. Is there any reference for the implementation for SPI? Can I refer this link [](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/main.c).

**Comment by vchong** [comment]
You need to support SPI on the hikey960 platform first. Just add the code as mentioned here [#3578], which is based on the '[hikey spi support](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/main.c)' you mentioned above. Or better yet, add them and submit a PR here for review. Then your PTA invoke_commands can call the SPI APIs/functions as necessary.

**Comment by noufalp** [comment]
Yea got it. So i need to add file like [this ](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/main.c)and define SPI APIs based on my requirement. Where should I add my SPI custom APIs for testing pupose? can I add it in PTA?

**Comment by noufalp** [comment]
I have gone through the code you mentioned and understood the initialization sequence. I also found a file [spi test code](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/spi_test.c) and defined an API to test the SPI communication. So my doubt is, can I call this spi_test() function defined from the Pseudo trusted application???

**Comment by vchong** [comment]
> So i need to add file like this

'This' file already exists. Why add it?

> define SPI APIs based on my requirement

Yes.

> Where should I add my SPI custom APIs for testing pupose? can I add it in PTA?

As you've mentioned, there's already an spi test code file. If you need more or something different, you can add them in the file or another new file if you prefer. Probably easier to just add to the existing file.

> can I call this spi_test() function defined from the Pseudo trusted application???

Yes, you've got it.

**Comment by Noufalp90** [comment]
Hi @gagachang I have my own module in the kernel meant for one of the external SPI device. I would like to add OP-TEE support for this module where I will be performing core SPI transactions. So can I use open session and invoke command APIs directly from my module to access Pseudo TA?

**Comment by gagachang** [comment]
Hi, @Noufalp90 , Sorry, I didn't try it (kernel module -> PTA).
I have tried to access GPIO in OP-TEE through **user-space CA -> TA -> PTA -> GPIO driver**.
Maybe you can test that way on QEMU first.

**Comment by noufalp** [comment]
@vchong Hi i have modified the code as mentioned at [#3578](https://github.com/OP-TEE/optee_os/issues/3578). But am not seeing any prints from the main.c file in the boot log.

**Comment by noufalp** [comment]
Hi @vchong I have modified the `./optee/optee_os/core/arch/arm/plat-hikey/main.c` file as mentioned at [#3578 ](https://github.com/OP-TEE/optee_os/issues/3578), but am not seeing any console prints from the main.c file on boot log.

**Comment by noufalp** [comment]
@vchong is there any configuration to be done for getting prints from core files?

**Comment by vchong** [comment]
@noufalp Sorry for the delay. How are you building? You need to set `CFG_TEE_CORE_LOG_LEVEL=3 CFG_TEE_TA_LOG_LEVEL=3` to see debug logs.

**Comment by noufalp** [comment]
@vchong Thank you.
Issue was related to the  `PLATFORM_FLAVOR_hikey` MACRO used in main.c that was commenting the whole code. Now I am using  `PLATFORM_FLAVOR_hikey960` MACRO inside main.c, and setting this flag during build. Now SPI loopback is working fine for Hikey960

**Comment by vchong** [comment]
@noufalp You're welcome. Glad you got it to work. Will close this now. Thanks.
