### ISSUE TITLE
Question Regarding Context Switch Between REE and TEE

### ISSUE THREAD

**Issue by mye-rutgers** [OP-TEE/optee_os#3963]
Hello,

I am wondering if OPTEE supports proactive context switches for both REE and TEE. Based on my current understanding, TA in OPTEE is a passive application that needs to wait for requests from the host to conduct the requested operations. Are there any commands or function calls to support the workflow as the figure shown below? Thank you!

<img width="502" alt="context_switch" src="https://user-images.githubusercontent.com/42823376/86534563-41bde000-bea7-11ea-88f2-2703e69ad0a0.png">

**Comment by vchong** [comment]
See https://github.com/OP-TEE/optee_os/pull/3673 for details.

**Comment by mye-rutgers** [comment]
Thank you!

**Comment by mye-rutgers** [comment]
Hello,

I have another question regarding the context switches. Ecall (i.e., TEE_InvokeTACommand) and Ocall (i.e., TEE_InvokeCACommand) are the function calls that pass the input parameters and return the output results. If I would like to conduct a simple context switch with context pointers only (e.g., SMC() as shown in the figure) to switch between the REE and TEE, how could I do that? I am looking for an SMC() function/command, because it could save time/energy consumption if there is no need to pass parameters and return results for some context-switch cases in the example shown below. Thank you! 

<img width="523" alt="smc" src="https://user-images.githubusercontent.com/42823376/86537806-b7ce4100-bebf-11ea-91a2-f2f034b5e103.png">

**Comment by jenswi-linaro** [comment]
TAs and Linux user space are not allowed to use the SMC instruction directly. Allowing that could lead to user mode corrupting kernel mode. In a full context switch from Linux user space to a TA is as you've noted a complex operation. Only skipping the parameter passing/checks should hardly make much difference.

**Comment by mye-rutgers** [comment]
I see. Thank you so much for your clarification.
