### ISSUE TITLE
Flashing Hikey960 using flash-all.sh script hangs

### ISSUE THREAD

**Issue by noufalp** [OP-TEE/optee_os#3970]
Hi Team,

I have successfully built AOSP+OPTEE and copied all the new *.img images to the `device/linaro/hikey/installer/hikey960/` folder. and run the scripts as mentioned at [aosp build and flash](https://optee.readthedocs.io/en/latest/building/aosp/aosp.html#aosp). But my flashing is stuck after 
```
=== Flasing ATF/UEFI...
flashing_atf_uefi () 
```
Can you please help to resolve this issue?

Regards
Noufal P

**Comment by vchong** [comment]
@noufalp For future references, please post AOSP+OPTEE related issues to https://github.com/linaro-swg/optee_android_manifest/issues/new.

Which branch of the repo did you use for the build? Are there no other errors during flashing? Can you post the full flash log?

**Comment by noufalp** [comment]
Hi @vchong  am using 3.8.3 branch. Please find the full log below,

`=== android out dir:./device/linaro/hikey/installer/hikey960/../../../../..//out/target/product/hikey960
android out imgdir:./device/linaro/hikey/installer/hikey960/../../../../..//out/target/product/hikey960
flashing recovery images.. please wait ~10 seconds
Config name: ./device/linaro/hikey/installer/hikey960/config
Port name: /dev/ttyUSB0
0: Image: ./device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img Downalod Address: 0x20000
1: Image: ./device/linaro/hikey/installer/hikey960/hisi-sec_uce_boot.img Downalod Address: 0x6a908000
2: Image: ./device/linaro/hikey/installer/hikey960/recovery.bin Downalod Address: 0x1ac00000
Serial port open successfully!
Start downloading ./device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img@0x20000...
file total size 99584
downlaod address 0x20000
Finish downloading
Start downloading ./device/linaro/hikey/installer/hikey960/hisi-sec_uce_boot.img@0x6a908000...
file total size 23680
downlaod address 0x6a908000
Finish downloading
Start downloading ./device/linaro/hikey/installer/hikey960/recovery.bin@0x1ac00000...
file total size 1179648
downlaod address 0x1ac00000
Finish downloading
sleep 10
skip setting a unique serial number for now
flashing all other images
=== Checking partition table version...
fastboot erase reserved
< waiting for any device >
erasing 'reserved'...
FAILED (remote: Check device console.)
finished. total time: 0.001s
=== Partition table is 512KB aligned.
=== Upgrading to 1MB aligned version...
upgrading_ptable_1mb_aligned ()
target reported max download size of 134217728 bytes
sending 'xloader' (151 KB)...
OKAY [  0.038s]
writing 'xloader'...
OKAY [  0.285s]
finished. total time: 0.323s
target reported max download size of 134217728 bytes
sending 'ptable' (196 KB)...
OKAY [  0.207s]
writing 'ptable'...
OKAY [  0.016s]
finished. total time: 0.223s
target reported max download size of 134217728 bytes
sending 'fastboot' (3346 KB)...
OKAY [  0.145s]
writing 'fastboot'...
FAILED (remote: No such partition.)
finished. total time: 0.146s
rebooting into bootloader...
OKAY [  0.001s]
finished. total time: 3.019s
=== Flasing ATF/UEFI...
flashing_atf_uefi ()`

**Comment by noufalp** [comment]
Hi @vchong am using 3.8.3 branch
And full log is as below,
```
=== android out dir:./device/linaro/hikey/installer/hikey960/../../../../..//out/target/product/hikey960
android out imgdir:./device/linaro/hikey/installer/hikey960/../../../../..//out/target/product/hikey960
flashing recovery images.. please wait ~10 seconds
Config name: ./device/linaro/hikey/installer/hikey960/config
Port name: /dev/ttyUSB0
0: Image: ./device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img Downalod Address: 0x20000
1: Image: ./device/linaro/hikey/installer/hikey960/hisi-sec_uce_boot.img Downalod Address: 0x6a908000
2: Image: ./device/linaro/hikey/installer/hikey960/recovery.bin Downalod Address: 0x1ac00000
Serial port open successfully!
Start downloading ./device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img@0x20000...
file total size 99584
downlaod address 0x20000
Finish downloading
Start downloading ./device/linaro/hikey/installer/hikey960/hisi-sec_uce_boot.img@0x6a908000...
file total size 23680
downlaod address 0x6a908000
Finish downloading
Start downloading ./device/linaro/hikey/installer/hikey960/recovery.bin@0x1ac00000...
file total size 1179648
downlaod address 0x1ac00000
Finish downloading
sleep 10
skip setting a unique serial number for now
flashing all other images
=== Checking partition table version...
fastboot erase reserved
< waiting for any device >
erasing 'reserved'...
FAILED (remote: Check device console.)
finished. total time: 0.001s
=== Partition table is 512KB aligned.
=== Upgrading to 1MB aligned version...
upgrading_ptable_1mb_aligned ()
target reported max download size of 134217728 bytes
sending 'xloader' (151 KB)...
OKAY [  0.038s]
writing 'xloader'...
OKAY [  0.285s]
finished. total time: 0.323s
target reported max download size of 134217728 bytes
sending 'ptable' (196 KB)...
OKAY [  0.207s]
writing 'ptable'...
OKAY [  0.016s]
finished. total time: 0.223s
target reported max download size of 134217728 bytes
sending 'fastboot' (3346 KB)...
OKAY [  0.145s]
writing 'fastboot'...
FAILED (remote: No such partition.)
finished. total time: 0.146s
rebooting into bootloader...
OKAY [  0.001s]
finished. total time: 3.019s
=== Flasing ATF/UEFI...
flashing_atf_uefi ()
```

**Comment by vchong** [comment]
In `flash-all.sh` at around line 139, you will see lines like below. Remove the `upgrading_ptable_1mb_aligned` line and try again please.

```
        echo ${ECHO_PREFIX}"Partition table is 512KB aligned."
        echo ${ECHO_PREFIX}"Upgrading to 1MB aligned version..."
        upgrading_ptable_1mb_aligned -> DELETE THIS LINE
        echo ${ECHO_PREFIX}"Flasing ATF/UEFI..."
        flashing_atf_uefi
```

**Comment by vchong** [comment]
Btw, this build has issues booting to the home/gui screen. You can refer to https://github.com/OP-TEE/build/issues/418#issuecomment-622349786 for more details and workaround.

**Comment by noufalp** [comment]
Hi @vchong I have commented and now it is hanging at "flashing l-loader" ( Added a print to identify the location)
```
echo "flashing l-loader"
fastboot flash fastboot "${INSTALLER_DIR}"/l-loader.bin
```
Flashing log is given below.
```
=== android out dir:./device/linaro/hikey/installer/hikey960/../../../../..//out/target/product/hikey960
android out imgdir:./device/linaro/hikey/installer/hikey960/../../../../..//out/target/product/hikey960
flashing recovery images.. please wait ~10 seconds
Config name: ./device/linaro/hikey/installer/hikey960/config
Port name: /dev/ttyUSB0
0: Image: device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img Downalod Address: 0x20000
1: Image: device/linaro/hikey/installer/hikey960/hisi-sec_uce_boot.img Downalod Address: 0x6a908000
2: Image: device/linaro/hikey/installer/hikey960/recovery.bin Downalod Address: 0x1ac00000
Serial port open successfully!
Start downloading device/linaro/hikey/installer/hikey960/hisi-sec_usb_xloader.img@0x20000...
file total size 99584
downlaod address 0x20000
Finish downloading
Start downloading device/linaro/hikey/installer/hikey960/hisi-sec_uce_boot.img@0x6a908000...
file total size 23680
downlaod address 0x6a908000
Finish downloading
Start downloading device/linaro/hikey/installer/hikey960/recovery.bin@0x1ac00000...
file total size 1179648
downlaod address 0x1ac00000
Finish downloading
sleep 10
skip setting a unique serial number for now
flashing all other images
=== Checking partition table version...
fastboot erase reserved
< waiting for any device >
erasing 'reserved'...
OKAY [  0.005s]
finished. total time: 0.005s
=== Partition table is 1MB aligned. Flashing ATF/UEFI...
flashing_atf_uefi ()
target reported max download size of 134217728 bytes
sending 'ptable' (24 KB)...
OKAY [  0.036s]
writing 'ptable'...
OKAY [  0.002s]
finished. total time: 0.038s
target reported max download size of 134217728 bytes
sending 'xloader' (151 KB)...
OKAY [  0.037s]
writing 'xloader'...
OKAY [  0.283s]
finished. total time: 0.320s
rebooting into bootloader...
OKAY [  0.000s]
finished. total time: 3.014s
flashing l-loader
```

**Comment by noufalp** [comment]
Hi Team,

After following [this](https://discuss.96boards.org/t/hikey960-boot-process-bl2-error/5611/7?u=noufal), my issues are resolved.
Thank you.

**Comment by vchong** [comment]
@noufalp Sorry for the late reply. All the `fastboot reboot-bootloader` statements in `flash-all.sh` need to be removed. I've fixed in the latest [temp](https://github.com/linaro-swg/optee_android_manifest/tree/master-dirty) master build. Glad you managed to figure it out anyway.
