### ISSUE TITLE
How can TA identify a calling is from TEE or REE? 

### ISSUE THREAD

**Issue by bqiu728** [OP-TEE/optee_os#3971]
Hi,
I've meet a problem that there is a case that I need to identify the calling is from TEE or REE.
For example, when open_session is called, the TA need to know who is calling, TEE or REE？

thanks

**Comment by gagachang** [comment]
I found the code in socket PTA, maybe it is one of the solutions.

https://github.com/OP-TEE/optee_os/blob/master/core/tee/socket.c#L222

**Comment by jenswi-linaro** [comment]
See section 4.6 Client Properties in GlobalPlatform TEE Internal Core API Specification v1.1.1, `gpd.client.identity`.

**Comment by bqiu728** [comment]
> 
> 
> See section 4.6 Client Properties in GlobalPlatform TEE Internal Core API Specification v1.1.1, `gpd.client.identity`.

thanks

**Comment by bqiu728** [comment]
> 
> 
> I found the code in socket PTA, maybe it is one of the solutions.
> 
> https://github.com/OP-TEE/optee_os/blob/master/core/tee/socket.c#L222

thanks
