### ISSUE TITLE
While running xtest after enabling RPMB secure storage, getting error 0xffff000f = TEE_ERROR_SECURITY 

### ISSUE THREAD

**Issue by jaingaurav2712** [OP-TEE/optee_os#3972]
Working on OPTEE-OS 3.8 on NXP LX2 with RPMB enabled.

**How To reproduce the issue:**

OPTEE configuration with CFG_RPMB_FS=y and CFG_REE_FS=y
Compile tee-supplicant with RPMB_EMU  := 0
boot the device to linux.
copy xtest and tee-supplicant 
run xtest

Result : Opening a User TA will look for binary in Secure Storage which fail with error
tee_ta_open_session:728 Failed. Return error 0xffff000f

Attaching detailed log.
[xtest_rpmb_failure.log](https://github.com/OP-TEE/optee_os/files/4923656/xtest_rpmb_failure.log)

**Comment by jforissier** [comment]
All looks good o the RPMB side (the key is good, blocks can be decrypted, the file system can be accessed). The problem could be releated to the protection of the secure storage containers in the normal world filesystem (anti-rollback protection). In other words, I think `dirfile.db.hash` in RPMB does not reflect the current state of the files in `/data/tee`, meaning the files were modified by something other than the OP-TEE core. Unfortunately there are no debug traces in `core/tee/tee_ree_fs.c` to confirm this hypothesis, maybe you can add some.

If I'm right, the only way to restore a working environment would be to rebuild OP-TEE with `CFG_RPMB_RESET_FAT=y`, which should clear the RPMB filesystem on startup.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/3988

**Comment by jaingaurav2712** [comment]
Thanks Jérôme.
After rebuild OPTEE with CFG_RPMB_RESET_FAT=y. I am able to run xtest with only 1 failure.

I also added logs in core/tee/tee_ree_fs.c and core/tee/fs_htree.c
you are right about dirfile.db.hash in RPMB does not reflect the current state of the files in /data/tee
TEE_ERROR_SECURITY is coming while comparing dirfile.db.hash with hash tree root node

Currently I am analyzing why /data/tee gets updated.

I am attaching the Xtest Pass logs after enabling CFG_RPMB_RESET_FAT=y
[xtest_rpmb_pass.log](https://github.com/OP-TEE/optee_os/files/4964413/xtest_rpmb_pass.log)

25186 subtests of which 1 failed
96 test cases of which 1 failed
0 test cases were skipped
TEE test application done!

**Comment by jforissier** [comment]
@jaingaurav2712 that's good. The remaining error is TEE_ERROR_OUT_OF_MEMORY, so it is a transient/dynamic thing. Perhaps you can get rid of it by increasing `CFG_CORE_HEAP_SIZE`.

**Comment by jaingaurav2712** [comment]
@jforissier I checked the TEE_ERROR_OUT_OF_MEMORY Error. This error is coming when storage id is TEE_STORAGE_PRIVATE_RPMB. while writing 6th block of block_size 1024 we get TA panicked with code 0xffff000c.

is there a way we could check how much size we have in emmc RPMB secure storage?

**Comment by jforissier** [comment]
It is true that `TEE_ERROR_OUT_OF_MEMORY` can indicate two different kinds of errors: memory allocation issue (RAM) or RPMB filesystem full. Perhaps we should return a different error when the FS is full and/or add more debug traces.

Anyway, you can try to set `CFG_TEE_CORE_LOG_LEVEL=4`. Then you should see `dump_fat:` debug traces, hopefully it helps you figure out what's in the RPMB storage.

**Comment by jaingaurav2712** [comment]
@jforissier Attaching the logs after enabling CFG_TEE_CORE_LOG_LEVEL=4.
[rpmb_6018.3_outOfMemory.log](https://github.com/OP-TEE/optee_os/files/5021997/rpmb_6018.3_outOfMemory.log)

**Comment by jaingaurav2712** [comment]
@jforissier Attaching the logs after enabling CFG_TEE_CORE_LOG_LEVEL=4.
[rpmb_6018.3_outOfMemory.log](https://github.com/OP-TEE/optee_os/files/5040057/rpmb_6018.3_outOfMemory.log)
