### ISSUE TITLE
New Static Library - mix of assembly and C code - how to change assembler flags?

### ISSUE THREAD

**Issue by sckulkarni246** [OP-TEE/optee_os#3974]
Hello folks,

I am working on porting assembly code library from armasm syntax to the Linaro compiler. The end goal is to build a library that can be used by TAs.

I get a bunch of errors that read:
`... Error: thumb conditional instruction should be in IT block ...`

Some results from stackoverflow suggest to try adding some flags to the assembler like so:
`-Wa,-mimplicit-it=thumb`

I would like to try it out but not sure where the assembler flags are located - where should I make these changes to test my build?

Regards,
Shashank

**Comment by jenswi-linaro** [comment]
You can try setting `aflags-y` in the `sub.mk` used for you library.

**Comment by sckulkarni246** [comment]
That helps @jenswi-linaro . Closing this issue.

Regards,
Shashank
