### ISSUE TITLE
wolfssl compilation error 

### ISSUE THREAD

**Issue by geneva1** [OP-TEE/optee_os#3980]
I am trying to compile [wolfssl](https://github.com/wolfSSL/wolfssl/) for optee qemu ARM architecture.

I found [a wolfssl developer write-up](https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fm.blog.naver.com%2FPostView.nhn%3FblogId%3Dhw5773%26logNo%3D221319208008%26proxyReferer%3Dhttps%3A%252F%252Fwww.google.com%252F) about it and followed the instructions there.

However, I have this mfloat-abi error   [fatal error: gnu/stubs-soft.h: No such file or directory](https://stackoverflow.com/questions/49139125/fatal-error-gnu-stubs-soft-h-no-such-file-or-directory)

Why ?

    make[1]: Entering directory '/home/rog/Documents/optee-qemu/optee_os'
      CHK     out/arm/conf.mk
      CHK     out/arm/include/generated/conf.h
      CC      out/arm/core/pta/secstor_ta_mgmt.o
    In file included from out/arm/core/include/features.h:452,
                     from out/arm/core/include/pthread.h:21,
                     from out/arm/core/include/wolfssl/wolfcrypt/wc_port.h:160,
                     from out/arm/core/include/wolfssl/wolfcrypt/types.h:30,
                     from out/arm/core/include/wolfssl/wolfcrypt/logging.h:33,
                     from out/arm/core/include/wolfssl/ssl.h:35,
                     from core/pta/secstor_ta_mgmt.c:22:
    out/arm/core/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-soft.h: No such file or directory
     # include <gnu/stubs-soft.h>
               ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    make[1]: *** [mk/compile.mk:148: out/arm/core/pta/secstor_ta_mgmt.o] Error 1
    make[1]: Leaving directory '/home/rog/Documents/optee-qemu/optee_os'
    make: *** [common.mk:378: optee-os-common] Error 2
    rog@rog-GL502VMK:~/Documents/optee-qemu/build$ cd ../
    rog@rog-GL502VMK:~/Documents/optee-qemu$
    rog@rog-GL502VMK:~/Documents/optee-qemu$ grep -rinIe "mfloat-abi"
    u-boot/arch/nds32/config.mk:18:PLATFORM_RELFLAGS += -fno-common -mrelax -mno-ext-fpu-dp -mfloat-abi=soft
    u-boot/arch/arm/lib/asm-offsets.s:26:@ -mno-unaligned-access -mfloat-abi=soft -mtune=generic-armv7-a -mfpu=neon
    u-boot/lib/asm-offsets.s:26:@ -mno-unaligned-access -mfloat-abi=soft -mtune=generic-armv7-a -mfpu=neon
    out-br/build/libopenssl-1.1.1a/Configurations/15-android.conf:193:        # -march and/or -mfloat-abi flags. NDK defaults to armv5te.
    out-br/build/host-python-2.7.15/Modules/_ctypes/libffi/ChangeLog:3552:    -mfloat-abi defaults to 'softfp' instead of 'soft'. To work around this
    out-br/build/host-python-2.7.15/Modules/_ctypes/libffi/ChangeLog.libffi-3.1:1665: and compiler options include -mfloat-abi=hard.
    out-br/build/host-python-2.7.15/Modules/_ctypes/libffi/ChangeLog.libffi-3.1:2130: for -mfloat-abi=softfp to work.
    out-br/build/host-gmp-6.1.2/configure:4269:        gcc_cflags_fpmode="-mfloat-abi=softfp" ;;
    out-br/build/host-gmp-6.1.2/configure:4271:        gcc_cflags_fpmode="-mfloat-abi=hard" ;;
    out-br/build/host-gmp-6.1.2/configure.ac:611:        gcc_cflags_fpmode="-mfloat-abi=softfp" ;;
    out-br/build/host-gmp-6.1.2/configure.ac:613:        gcc_cflags_fpmode="-mfloat-abi=hard" ;;
    ^C
    rog@rog-GL502VMK:~/Documents/optee-qemu$
    rog@rog-GL502VMK:~/Documents/optee-qemu/build$ cat ../optee_os/out/arm/core/include/gnu/stubs.h
    /* This file is automatically generated.

    This file selects the right generated file of `__stub_FUNCTION' macros
    based on the architecture being compiled for.  */
 
    #if !defined __ARM_PCS_VFP
    # include <gnu/stubs-soft.h>
    #endif
    #if defined __ARM_PCS_VFP
    # include <gnu/stubs-hard.h>
    #endif
    rog@rog-GL502VMK:~/Documents/optee-qemu/build$ 

When I use `../toolchains/aarch64/aarch64-linux-gnu/libc/usr/include/gnu/stubs.h` instead of `../toolchains/aarch32/arm-linux-gnueabihf/libc/usr/include/gnu/stubs.h`, I have different error though.

```
rog@rog-GL502VMK:~/Documents/optee-qemu/build$ cp ../toolchains/aarch64/aarch64-linux-gnu/libc/usr/include/gnu/stubs.h ../optee_os/out/arm/core/include/gnu/
rog@rog-GL502VMK:~/Documents/optee-qemu/build$ make
make -C /home/rog/Documents/optee-qemu/build/../optee_os O=out/arm PLATFORM=vexpress-qemu_virt CROSS_COMPILE="/usr/bin/ccache /home/rog/Documents/optee-qemu/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CROSS_COMPILE_core="/usr/bin/ccache /home/rog/Documents/optee-qemu/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CROSS_COMPILE_ta_arm64="/usr/bin/ccache /home/rog/Documents/optee-qemu/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm32="/usr/bin/ccache /home/rog/Documents/optee-qemu/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=1 CFG_TEE_BENCHMARK=n
make[1]: Entering directory '/home/rog/Documents/optee-qemu/optee_os'
  CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
  CC      out/arm/core/pta/secstor_ta_mgmt.o
In file included from out/arm/core/include/features.h:452,
                 from out/arm/core/include/pthread.h:21,
                 from out/arm/core/include/wolfssl/wolfcrypt/wc_port.h:160,
                 from out/arm/core/include/wolfssl/wolfcrypt/types.h:30,
                 from out/arm/core/include/wolfssl/wolfcrypt/logging.h:33,
                 from out/arm/core/include/wolfssl/ssl.h:35,
                 from core/pta/secstor_ta_mgmt.c:22:
out/arm/core/include/gnu/stubs.h:5:10: fatal error: bits/wordsize.h: No such file or directory
 #include <bits/wordsize.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [mk/compile.mk:148: out/arm/core/pta/secstor_ta_mgmt.o] Error 1
make[1]: Leaving directory '/home/rog/Documents/optee-qemu/optee_os'
make: *** [common.mk:378: optee-os-common] Error 2
rog@rog-GL502VMK:~/Documents/optee-qemu/build$ find ../ -name "stubs.h"
../out-br/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/gnu/stubs.h
../toolchains/aarch32/arm-linux-gnueabihf/libc/usr/include/gnu/stubs.h
../toolchains/aarch64/aarch64-linux-gnu/libc/usr/include/gnu/stubs.h
../linux/tools/testing/selftests/bpf/gnu/stubs.h
../optee_os/out/arm/core/include/gnu/stubs.h
../optee_os/out/arm/core/include/stubs.h
rog@rog-GL502VMK:~/Documents/optee-qemu/build$ 

```

**Comment by jenswi-linaro** [comment]
The problem seems to be that Wolfssl is configured to expect a Linux user space environment. In OP-TEE OS mode you cannot use floating point registers in a normal way. If there's a way to configure Wolfssl for bare metal without floating point I think it would be easier to use that as a starting point.

**Comment by danielinux** [comment]
@wolfSSL expects a POSIX compliant libC only when it's built using `configure`/`make`. The recommended setup for compiling on non-POSIX embedded environment is by using `WOLFSSL_USER_SETTINGS` and providing `user_settings.h` with the desired configuration.

Please see https://www.wolfssl.com/docs/wolfssl-manual/ch2/ and in particular section 2.4 "Building in a non-standard environment".

Also, please have a look at @dgarske 's comment in https://github.com/wolfSSL/wolfssl/issues/3143.

Thanks,

-- 
Daniele (wolfSSL)
