### ISSUE TITLE
Ftrace debug translation error

### ISSUE THREAD

**Issue by kouzili77** [OP-TEE/optee_os#3983]
Dear all,
I can manage to get the ftrace debug file *.out. see [https://optee.readthedocs.io/en/latest/debug/ftrace.html](url)

However when I translate it by `cat ftrace-<ta_uuid>.out | ./optee_os/scripts/symbolize.py -d <ta_uuid>.elf -d tee.elf`,

It can partly work but showing question marks instead of function names.

![image](https://user-images.githubusercontent.com/54700513/87850884-24b4f280-c926-11ea-9b6e-ef21ea06168a.png)

I counter this error both on qemuv8 and hikey960 with the latest optee version.

May I know it there anything I ignored?

**Comment by jforissier** [comment]
Please check the paths: `-d path/to/tee.elf -d path/to/ta.elf`. The files need to be accessible from the current directory.

**Comment by kouzili77** [comment]
That it!
Thx jforissier! :)
