### ISSUE TITLE
OPTEE client API in the Linux kernel module

### ISSUE THREAD

**Issue by Noufalp90** [OP-TEE/optee_os#3985]
Hi Team,
I was working on OPTEE-OS SPI implementation on Hikey960 board past two weeks. Now using user space client application, am able to communicate with SPI. Now my requirement is to use already existing Linux kernel module and use Client APIs from the Kernel module to access SPI. I was referring to [this](https://github.com/linaro-swg/linux/blob/optee/drivers/char/hw_random/optee-rng.c) link, but here they are adding new module for the OPTEE access. 
Can you please help me with modifying existing custom kernel module to add OPTEE support?

Regards
Noufal

**Comment by jenswi-linaro** [comment]
https://github.com/linaro-swg/linux/blob/optee/drivers/char/hw_random/optee-rng.c is a good example for in kernel client API. It's different from GP TEE Client API, but so is the environment where it's used.

**Comment by Noufalp90** [comment]
@jenswi-linaro  Thank you
