### ISSUE TITLE
Passing pointer to PTA from  Linux kernel module(CA)

### ISSUE THREAD

**Issue by Noufalp90** [OP-TEE/optee_os#3990]
Hi team, 
I have successfully implemented a PTA to access SPI from the secure world. No i would like to pass two pointers from the client linux module to the PTA where where SPI operation is performed. (TX pointer is used to pass transmit data to SPI and RX pointer is used for SPI receive data).
 
Am able to do SPI transfer using values (param[0].u.value.a and param[0].u.value.b). Now instead of using values, i would like to use pointers.

**Comment by Noufalp90** [comment]
Hi

Anyone knows about this?

**Comment by gagachang** [comment]
Maybe use this.
https://github.com/linaro-swg/linux/blob/master/include/linux/tee_drv.h#L60

**Comment by Noufalp90** [comment]
Thank you @gagachang , 
Is there any document about how to create, use shared memory both in kernel client module and pseudo application?

**Comment by b49020** [comment]
> Is there any document about how to create, use shared memory both in kernel client module and pseudo application?

- Use [this](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/tee_drv.h#n317) API to allocate shared memory in kernel client module
- Use [this](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/linux/tee_drv.h#n333) API to register shared memory in kernel client module

pseudo TA shared memory handling remains the same whether its a kernel client module or a user-space client application.

**Comment by Noufalp90** [comment]
@b49020  Thank you.

TA shared memory handling is same means we have to use for e.g. params[0].memref.buffer for getting buffer pointer and params[0].memref.size for size.

**Comment by b49020** [comment]
@Noufalp90 yes.

**Comment by Noufalp90** [comment]
@b49020  thank you. Following aremy code
`    /* allocate shared memory for tx data */
    tx_shm_pool = tee_shm_alloc(ctx, 1024, TEE_SHM_MAPPED | TEE_SHM_DMA_BUF);
    if(IS_ERR(tx_shm_pool))
    {
        slog(" tx shm pool alloc failed\n");
        return -1;
    }
    /* copy tx buffer to shared memory */
    memcpy((u8 *)tx_shm_pool->kaddr, tx_buf, len);

    param[0].attr = TEE_IOCTL_PARAM_ATTR_TYPE_MEMREF_INOUT;
    param[0].u.memref.shm = tx_shm_pool;
    param[0].u.memref.size = len;
    param[0].u.memref.shm_offs = 0;

    ret = tee_client_invoke_func(ctx, &inv_arg, param);
`

Is it okay? or should i need to use tee_shm_register() API also?

**Comment by Noufalp90** [comment]
It is success. But if I do following code in my Linux kernel module to copy buffer, am getting error as `Internal error: Accessing user space memory outside uaccess.h routines: 96000045 [#1] PREEMPT SMP`

```
    read_data = tee_shm_get_va(rx_shm_pool, 0);
    if(IS_ERR(read_data))
    {
        slog("getting rx buff failed\n");
        ret = -1;
    }
    memcpy(rx_buf, read_data, len);
```
Here memcpy() API is throwing me error

**Comment by Noufalp90** [comment]
Hi, Everyone

I have found out the issue with `memcpy()`. If the `len` of the copy is <=4, then copy is success. In my case, size of the `rx_buf` is 5, but still am observing the error if `len` is 5. Thank you for your help.
