### ISSUE TITLE
TEEC_opensession failed with 0xffff3024

### ISSUE THREAD

**Issue by purplep2** [OP-TEE/optee_os#3997]
Hi,

I am new to OP-TEE and am trying to run an application created on rpi3.
I am able to compile and run the examples "hello world" and "random" provided, but running my own application fails with

`TEEC_Opensession failed with code 0xffff3024 origin 0x3`

What does this error code mean, and how can I resolve it?

**Comment by jforissier** [comment]
Hi,
```
lib/libutee/include/tee_api_defines.h:#define TEE_ERROR_TARGET_DEAD             0xFFFF3024
```
It means your TA has panicked or crashed.

**Comment by purplep2** [comment]
Hi,

Thanks for the reply. What does this TEE_ERROR_TARGET_DEAD mean, and what might be some probable reasons for this error to occur?

**Comment by jforissier** [comment]
Most probable causes are (1) you passed an invalid argument to a TEE Internal Core API function and (2) a memory access violation occurred (bad pointer). In both cases, the TEE core stops the execution of the TA and returns this error code.
You should add debug traces in your TA such as `DMSG("Blah blah");` and build your TA with `CFG_TEE_TA_LOG_LEVEL=3`. The watch for output on the secure console.
