### ISSUE TITLE
Build race on conf.mk

### ISSUE THREAD

**Issue by rossburton** [OP-TEE/optee_os#3999]
```
echo sm := ta_arm64 > TOPDIR/build/tmp/work/qemuarm64-yoe-linux-musl/optee-os/3.8.0+gitAUTOINC+023e33656e-r0/build/export-ta_arm64/mk/conf.mk.tmp
/bin/bash: TOPDIR/build/tmp/work/qemuarm64-yoe-linux-musl/optee-os/3.8.0+gitAUTOINC+023e33656e-r0/build/export-ta_arm64/mk/conf.mk.tmp: No such file or directory
```

My guess is that as this is a heavily parallel build, this write to `export-ta_arm64/mk/conf.mk.tmp` happened before `export-ta_arm64/mk` was created.

The full log is available at https://errors.yoctoproject.org/Errors/Details/424504/.

**Comment by jforissier** [comment]
Hi @rossburton,

Thanks for reporting this. I think the following patch should fix the issue:

```diff
diff --git a/ta/ta.mk b/ta/ta.mk
index 918880f4a..646bba733 100644
--- a/ta/ta.mk
+++ b/ta/ta.mk
@@ -190,6 +190,7 @@ define mk-file-export
 .PHONY: $(conf-mk-file-export)
 $(conf-mk-file-export):
 	@$$(cmd-echo-silent) '  CHK    ' $$@
+	$(q)mkdir -p $$(dir $$@)
 	$(q)echo sm := $$(sm-$(conf-mk-file-export)) > $$@.tmp
 	$(q)echo sm-$$(sm-$(conf-mk-file-export)) := y >> $$@.tmp
 	$(q)($$(foreach v, $$(ta-mk-file-export-vars-$$(sm-$(conf-mk-file-export))), \
```

Can you try it perhaps? (that is, if the issue was easily reproducible in the first place).

**Comment by rossburton** [comment]
I'm struggling to replicate the failure in isolation by causing that rule to run on its own, but that looks like what I imagined the fix would be!

**Comment by rossburton** [comment]
Found the correct runes to cause it to fail, and yes that patch fixes it.

**Comment by rossburton** [comment]
Will you be able to commit that, or should I prepare a pull request?

**Comment by jforissier** [comment]
> Will you be able to commit that, or should I prepare a pull request?

https://github.com/OP-TEE/optee_os/pull/4000

Please feel free to give a Reported-by: or Tested-by: if you wish.
