### ISSUE TITLE
OPTEE loading in Juno R1

### ISSUE THREAD

**Issue by gabr1e11** [OP-TEE/optee_os#400]
Hi,

I'm trying to bring to life a Juno board R1 with OPTEE. I've followed the instructions to generate the fip.bin file with OPTEE as the BL32 image using opteed support in ARM-TF, however when booting I see ERROR:   Error initializing runtime service opteed_fast.

Investigating I found the problem is:

WARNING:   No OPTEE provided by BL2 boot loader, Booting device without OPTEE initialization. SMC`s de      stined for OPTEE will return SMC_UNK

On the creation of the fip.bin file this is the output:

./tools/fip_create/fip_create --dump --bl2 ./build/juno/release/bl2.bin --bl30 $JUNO_ROOT/src/bl30.bin --bl31 ./build/juno/release/bl31.bin --bl32 $JUNO_ROOT/OPTEE/optee_os/out/arm32-plat-vexpress/core/tee.bin --bl33 $JUNO_ROOT/firmware/edk2/Build/ArmJuno/RELEASE_GCC49/FV/BL33_AP_UEFI.fd fip.bin
Firmware Image Package ToC:
---------------------------
- Trusted Boot Firmware BL2: offset=0x100, size=0x3008
  file: './build/juno/release/bl2.bin'
- SCP Firmware BL3-0: offset=0x3108, size=0xB864
  file: 'linaro-android/src/bl30.bin'
- EL3 Runtime Firmware BL3-1: offset=0xE96C, size=0x6010
  file: './build/juno/release/bl31.bin'
- Secure Payload BL3-2 (Trusted OS): offset=0x1497C, size=0x41140
  file: 'linaro-android/OPTEE/optee_os/out/arm32-plat-vexpress/core/tee.bin'
- Non-Trusted Firmware BL3-3: offset=0x55ABC, size=0xF0000
  file: 'linaro-android/firmware/edk2/Build/ArmJuno/RELEASE_GCC49/FV/BL33_AP_UEFI.fd'
---------------------------

I've tried to find more information but I couldn't. Any hint?

Thanks in advance,
Roberto

**Comment by vchong** [comment]
Are you using https://github.com/ARM-software/arm-trusted-firmware?
If yes, can you try https://github.com/linaro-swg/arm-trusted-firmware (optee_paged_armtf_v1.1 branch) instead?

**Comment by gabr1e11** [comment]
HI vchong,

Many thanks for the prompt response. I've been checking the branch and the problems is I'm using arm-trusted-firmware commit 57e56bb with a patch on top from another party, and it seems they are quite different. I may try to apply the patch manually but I'm not sure yet.

Thanks for the reply. If I try the one you suggested I will let you know.

Kind regards,
Roberto

**Comment by vchong** [comment]
You also can try cherry-picking commit 74efa34641672c420760a683896d6519116b0f5b onto your branch to see if that works, if that's easier.

**Comment by gabr1e11** [comment]
It seems the master branch has moved all juno related files to plat/arm/board/juno and left the common files under plat/arm. I can see some similarities but I don't think I can fix it without knowing what I'm doing. The conflict files are:

	both modified:      plat/arm/common/arm_bl31_setup.c
	deleted by us:      plat/fvp/aarch64/fvp_common.c
	deleted by us:      plat/fvp/include/platform_def.h
	deleted by us:      plat/juno/aarch64/juno_common.c
	deleted by us:      plat/juno/include/platform_def.h

Any hint on any approach to tackle this? Many thanks.

**Comment by vchong** [comment]
Refer to https://github.com/linaro-swg/arm-trusted-firmware/commit/74efa34641672c420760a683896d6519116b0f5b#diff-458cae56af442eb352d33c1071fba500

Make sure the additions to bl31_fvp_setup.c go into arm_bl31_setup.c.
Make sure the additions to fvp_common.c and juno_common.c go into plat/arm/board/common/board_css_common.c. You'll have to change MAP_TSP_SEC_MEM to it's corresponding term/name in board_css_common.c.
Make sure the changes to both platform_def.h files go into include/plat/arm/common/arm_def.h

WARNING: This has not been tested! Please let us know if it works for you.

**Comment by gabr1e11** [comment]
Hi Victor,

I've applied manually the patches and after fixing some mismatches I think I manage to port them.

However the problem I'm hitting is of a different kind. Examining the ARM trusted firmware code I saw how to enable debugging.The OPTEE OS image I have is about 275KB, but the Juno R1 board I have has a limit of 256KB, that is why I cannot load the OS. Is this something known or am I doing something wrong?

Kind regards,
Roberto

**Comment by gabr1e11** [comment]
Nevermind, I realized that ARM TF has changed the variable to control the TSP location to ARM_TSP_RAM_LOCATION. Now it is loaded in dram, but the OS does not load. Will start debugging that. I will also test ARM TF without the patches you gave me as I feel I don't need those. I'll come back here to post the results.

**Comment by gabr1e11** [comment]
I tried different things but I'm facing an strange issue now. I can load the BL3-2 image, I can load the kernel modules, but if I run tee-supplicant the kernel panics. Just wondering if you know of this behavior. I'm trying to debug this but currently have no UART cable to debug what is happening on the secure OS. Could this be something related to the kernel modules and using the kernel 3.10?

**Comment by vchong** [comment]
See below for what's being done to the kernel build for Juno, especially the patch.
https://github.com/OP-TEE/optee_os/blob/master/scripts/setup_juno_optee.sh#L158
HTH

**Comment by gabr1e11** [comment]
I've applied the .dts file patch (was an easy one), but the .config is much more complicated. The kernel versions are too different. I may try just to fusion both config files and hope for the best!

Right now I see I can load OP-TEE os properly. I was having an issue because I was using CG_TEE_CORE_LOG_LEVEL=4 which seemed to be a lot. Now the board boots properly but still crashes when I run tee-supplicant. The problem seems to be:

BUG: failure at OPTEE/optee_linuxdriver/core/tee_supp_com.c:130/tee_supp_read()!

Does this ring a bell?

I will try increasing the log level a bit and see if I can see something, although it seems to be a driver issue.

**Comment by gabr1e11** [comment]
After fighting against a driver .open that was not being called I realized that the script I was using was pointing to the Linaro kernel headers and not the one I'm currently using *sigh*.

To summarize I had to change PLAT_TSP_LOCATION to ARM_TS_RAM_LOCATION for my version of ARM TF (57e56bb), although I have to use the d6d47ed version of OPTEE-OS. Latest client, driver and Hello World work fine with 3.10 kernel.

Anyhow I've learned a lot about OPTEE internals. Many, many thanks for the support and sorry for the hassle.

**Comment by vchong** [comment]
"I will also test ARM TF without the patches you gave me as I feel I don't need those."

Hi.. just curious what patches you were referring to and if you ended up using them or not?

**Comment by gabr1e11** [comment]
I meant both linaro-swg/arm-trusted-firmware@74efa34#diff-458cae56af442eb352d33c1071fba500 and
https://github.com/OP-TEE/optee_os/blob/master/scripts/setup_juno_optee.sh#L158. First one I succesfully ported to the version 57e56bb of ARM TF, and for the second one I could easyly add the juno.dts change bat not the kernel config as it was too complex. Anyway it seems that the main problem was the RAM location of the OPTEE-OS.

Please, let me know if you have further questions.

**Comment by neil1899** [comment]
hi Roberto
maybe， i met the same issue with you. when i run tee_supplicant on Android 5.1.
it failed.
But, I have change RAM location of the OPTEE-OS.

such as
static const mmap_region_t gxbb_mmap[] = {
	{KERNEL_BASE,	KERNEL_BASE, KERNEL_SIZE,
		MT_MEMORY | MT_RW | MT_NS },

	{ DRAM_BASE,		DRAM_BASE,	DRAM_SIZE,
		MT_MEMORY | MT_RW | MT_NS },
	{ DEVICE0_BASE,		DEVICE0_BASE,	DEVICE0_SIZE,
		MT_DEVICE | MT_RW },
	{ TZRAM_BASE,	TZRAM_BASE,	TZRAM_SIZE,
		MT_DEVICE | MT_RW | MT_SECURE },
	{ DEVICE1_BASE,	DEVICE1_BASE, DEVICE1_SIZE,
		MT_DEVICE | MT_RW | MT_SECURE },
	{ DEVICE2_BASE,	DEVICE2_BASE, DEVICE2_SIZE,
		MT_DEVICE | MT_RW | MT_SECURE },
	{0}
};

can you help me?

thanks in advance
Neil

**Comment by gabr1e11** [comment]
Hi Neil,

I don't know the internals of ARM-TF, so I cannot compare with your code. Are you using ARM-TF as a base for your implementation?

What I did is just define ARM_TSP_RAM_LOCATION=dram when compiling ARM-TF. That triggers an specific mapping for the mmap_region_t structure of the BL2 image. However I do not know why that specific mapping works.

About the tee-supplicant crash it basically came from the fact that I was using two different kernel versions to compile the driver and the supplicant/client library. Make sure you only use the kernel that you want. If it still crashes the problem may be caused by another reason.

Kind regards,
Roberto

**Comment by neil1899** [comment]
hi roberto

thanks so much,i will check agagin.
