### ISSUE TITLE
Question: memcpy or memmove or TEE_MemMove?

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#4001]
Hello all,

So, currently for copying memory buffer contents, we use TEE_MemMove in the TA code.
I had a look into the manpage for memcpy and also the TEE core spec about TEE_MemMove.

So, memcpy() doesn't handle the scenario where we have overlapping memory regions and it leads to undefined behaviour.
On the other hand, memmove() and TEE_MemMove do handle the above scenario. 

Hence, i would like to know the difference between memmove and TEE_MemMove?

Can we use memmove instead of TEE_MemMove() in the TA code?

**Comment by jforissier** [comment]
Hi @saddy-muchu,

> Hence, i would like to know the difference between memmove and TEE_MemMove?

`TEE_MemMove()` is the [same as `memmove()`](https://github.com/OP-TEE/optee_os/blob/3.9.0/lib/libutee/tee_api.c#L301-L304).

> Can we use memmove instead of TEE_MemMove() in the TA code?

Yes.

**Comment by saddy-muchu** [comment]
> 
> 
> Hi @saddy-muchu,
> 
> > Hence, i would like to know the difference between memmove and TEE_MemMove?
> 
> `TEE_MemMove()` is the [same as `memmove()`](https://github.com/OP-TEE/optee_os/blob/3.9.0/lib/libutee/tee_api.c#L301-L304).
> 
> > Can we use memmove instead of TEE_MemMove() in the TA code?
> 
> Yes.

Thank you
