### ISSUE TITLE
Adding macro to TA

### ISSUE THREAD

**Issue by bqiu728** [OP-TEE/optee_os#4002]
Hi, 
I've tried to add a macro for a personal TA.  I did it like that:
In ta/Makefile:
```
CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL) -DQBQ
```

where QBQ is the macro I want to add.
but when i do `make buildroot V=1`, I can not find this maro in compile window.

Is there anything I did wrong?

**Comment by jforissier** [comment]
Hi @bqiu728,

Please try `CPPFLAGS_ta_arm32 := -DQBQ` instead, or `CPPFLAGS_ta_arm64 := -DQBQ` is you are building a 64-bit TA.

In my opinion the example is wrong. Using `CPPFLAGS` for TAs is incorrect because it can conflict with flags intended for the host (Linux applications). For TAs we need something more specific, hence the `_ta_arm32` and `_ta_arm64` variants.

So, I think we should remove the `CPPFLAGS` in the example makefiles. I will create a PR.

**Comment by jforissier** [comment]
https://github.com/linaro-swg/optee_examples/pull/75

**Comment by jforissier** [comment]
And regarding `CFG_TEE_TA_LOG_LEVEL`, see also https://github.com/OP-TEE/optee_os/pull/4003.

**Comment by bqiu728** [comment]
> 
> 
> [linaro-swg/optee_examples#75](https://github.com/linaro-swg/optee_examples/pull/75)

Thanks, it works.

However, is CPPFLAGS really not used? I've seen it is used in compile.mk, such as:
`comp-cppflags-$2 = $$(filter-out $$(CPPFLAGS_REMOVE) $$(cppflags-remove) \
				 $$(cppflags-remove-$$(comp-sm-$2)) \
				 $$(cppflags-remove-$2), \
		      $$(nostdinc$$(comp-sm-$2)) $$(CPPFLAGS)\
		      $$(addprefix -I,$$(incdirs$$(comp-sm-$2))) \
		      $$(addprefix -I,$$(incdirs-lib$$(comp-lib-$2))) \
		      $$(addprefix -I,$$(incdirs-$2)) \
		      $$(cppflags$$(comp-sm-$2)) \
		      $$(cppflags-lib$$(comp-lib-$2)) $$(cppflags-$2)) \
		      -D__FILE_ID__=$$(subst -,_,$$(subst /,_,$$(subst .,_,$1)))
`

**Comment by jforissier** [comment]
> However, is CPPFLAGS really not used? I've seen it is used in compile.mk,

You're right. I took a closer look and indeed CPPFLAGS is used when building TAs. The problem here is that CPPFLAGS is overridden by Buildroot so the value you set in your TA Makefile is ignored. Here are the relevant parts of the makefiles:

```
build/br-ext/package/optee_examples_ext/optee_examples_ext.mk-11-     @$(foreach f,$(wildcard $(@D)/*/ta/Makefile), \
build/br-ext/package/optee_examples_ext/optee_examples_ext.mk-12-             echo Building $f && \
build/br-ext/package/optee_examples_ext/optee_examples_ext.mk-13-                     $(MAKE) CROSS_COMPILE="$(shell echo $(BR2_PACKAGE_OPTEE_EXAMPLES_EXT_CROSS_COMPILE))" \
build/br-ext/package/optee_examples_ext/optee_examples_ext.mk-14-                     O=out TA_DEV_KIT_DIR=$(OPTEE_EXAMPLES_EXT_SDK) \
build/br-ext/package/optee_examples_ext/optee_examples_ext.mk:15:                     $(TARGET_CONFIGURE_OPTS) -C $(dir $f) all &&) true

buildroot/package/Makefile.in:262:TARGET_CONFIGURE_OPTS = \
buildroot/package/Makefile.in:292:	CPPFLAGS="$(TARGET_CPPFLAGS)" \

buildroot/package/Makefile.in:161:TARGET_CPPFLAGS += -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64
```
