### ISSUE TITLE
Question: Shared memory size between linux and optee

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#4005]
Hello all,

I wanted to know what is the maximum shared memory size that is currently configured for exchange of data between linux and optee.

Is it documented anywhere?

Say, max shared memory size is 1MB, and if an application configures max shared memory "chunk size" as 450KB, does it mean that if three TA's are doing parallel processing of data, then one of the TA would run out of memory (because  450KB *3 > 1MB)?

**Comment by jforissier** [comment]
Hi @saddy-muchu ,

> I wanted to know what is the maximum shared memory size that is currently configured for exchange of data between linux and optee.
> 
> Is it documented anywhere?

Please see https://optee.readthedocs.io/en/latest/architecture/core.html#shared-memory.

> Say, max shared memory size is 1MB, and if an application configures max shared memory "chunk size" as 450KB, does it mean that if three TA's are doing parallel processing of data, then one of the TA would run out of memory (because 450KB *3 > 1MB)?

Yes. Should it be a problem, `CFG_CORE_DYN_SHM=y` would be a nice way of avoiding the issue. With current OP-TEE it is not mandatory to have a reserved shared memory (i.e., you can set `CFG_CORE_RESERVED_SHM=n CFG_CORE_DYN_SHM=y` as mentioned in commit 6e934fb4866c578ea8f020e207aaa5b7bf196cf6).

**Comment by saddy-muchu** [comment]
Hi @jforissier ,

I don't see a configuration for dynamic(non-contiguous) or reserved(contiguous) shared memory in my current OP-TEE. I'm using 3.1.0

**Comment by jforissier** [comment]
Dynamic shared memory was introduced in 3.6.0:
```
$ git blame mk/config.mk | grep CFG_CORE_DYN_SHM
37a6b7177 (Jens Wiklander         2019-04-18 08:56:31 +0200 505) CFG_CORE_DYN_SHM ?= y
$ git describe 37a6b7177
3.5.0-9-g37a6b717
```

**Comment by saddy-muchu** [comment]
OK.
i guess i need to think of alternatives in order to allow more TA's to process the data parallely by doing some modifications to the chunk size.

Thanks for the information

**Comment by sunnybird** [comment]
@saddy-muchu 
i have some ideas about the issue, you can change CFG_SHMEM_SIZE into 0x00200000 ( 2M)  or more big . it mabey can load three TA.
by the way,
i still confused with CFG_SHMEM_START . what decide the value of CFG_SHMEM_START?

**Comment by zhaoshuli1548** [comment]
@sunnybird do you get it?(CFG_SHMEM_START)
