### ISSUE TITLE
qemu monitor cannot input “c” command.

### ISSUE THREAD

**Issue by penpendandan** [OP-TEE/optee_os#4006]
Hi, guys!
I have compiled the OP-TEE project according to the documents. The two terminals, normal world and secure world, has appeared. 
However, I cannot input "c" command in monitor. Please tell me how to fix it! Thanks!

the log in Normal World is as follows:

```
listening on port 54320
soc_term: accepted fd 4
```

the log in secure world is as follows:

 `listening on port 54321`

the log in the monitor is：

ln -sf /home/OP-TEE/build/../out-br/images/rootfs.cpio.gz /home/OP-TEE/build/../out/bin/
```
* QEMU is now waiting to start the execution
* Start execution with either a 'c' followed by <enter> in the QEMU console or
* attach a debugger and continue from there.
*
* To run OP-TEE tests, use the xtest command in the 'Normal World' terminal
* Enter 'xtest -h' for help.

```

**Comment by jforissier** [comment]
Hi,

Have you modified the port numbers in `$(call wait-for-ports,54320,54321)` perhaps?

**Comment by penpendandan** [comment]
I have modified the port numbers, but the monitor can‘t still input.

**Comment by jforissier** [comment]
Then I don't know.

**Comment by penpendandan** [comment]
Hi, teamer,
cd build
make check
I find the error as follow:
`make[1]: Leaving directory `/home/OP-TEE/soc_term'
expect qemu-check.exp --  || \
        (if [ "" ]; then \
                echo "== $PWD/serial0.log:"; \
                cat serial0.log; \
                echo "== end of $PWD/serial0.log:"; \
                echo "== $PWD/serial1.log:"; \
                cat serial1.log; \
                echo "== end of $PWD/serial1.log:"; \
        fi; false)
Starting QEMU...no such variable
    (read trace on "::env(QEMU)")
    invoked from within
"spawn $::env(QEMU) -nographic -monitor none -machine virt -machine secure=on -cpu cortex-a15 -smp $::env(QEMU_SMP) -d unimp -semihosting-config enable..."
    (file "qemu-check.exp" line 45)
make: *** [check] Error 1
` 
so what's the QEMU variable?

**Comment by jforissier** [comment]
Should be set here: https://github.com/OP-TEE/build/blob/3.9.0/qemu.mk#L195
