### ISSUE TITLE
Proposal to add the GPIO controller base address in struct gpio_ops operations

### ISSUE THREAD

**Issue by manishtomar1** [OP-TEE/optee_os#4007]
Since there can be many number of GPIO controllers in an SoC.
But as of now, if I understand correctly there is no way in gpio_ops operation to distinguish between different controllers.
Checked the pl061_gpio.c, they are also getting the base address with some internal calculations.

So we propose to add one more argument base_addr, in struct gpio_ops operations, so that we need not to do any calculations to find the base address of controllers.

**New struct gpio_ops will look like this:**

`struct gpio_ops {`
        `enum gpio_dir (*get_direction)(vaddr_t base_addr, unsigned int gpio_pin);`
        `void (*set_direction)( vaddr_t base_addr , unsigned int gpio_pin, enum gpio_dir direction);`
        `enum gpio_level (*get_value)(vaddr_t base_addr, unsigned int gpio_pin);`
        `void (*set_value)(vaddr_t base_addr, unsigned int gpio_pin, enum gpio_level value);`
        `enum gpio_interrupt (*get_interrupt)(vaddr_t base_addr, unsigned int gpio_pin);`
        `void (*set_interrupt)(vaddr_t base_addr, unsigned int gpio_pin,`
               ` enum gpio_interrupt ena_dis);`
`};`

Please share your views on this.

**Comment by jenswi-linaro** [comment]
I'd prefer supplying `struct gpio_chip *chip` instead of `vaddr_t base_addr` like we're doing in `core/include/drivers/serial.h`.

**Comment by vchong** [comment]
@manishtomar1 Per https://github.com/OP-TEE/optee_os/pull/2926#issuecomment-484951197: "For pl011 and pl022, the base address seems to be fixed and so is passed as a member in the container struct, while for pl061, the base address is based on the bank which contains the pin, so it's derived from the pin number", so you'll have to do the calculations either way.

**Comment by sahilnxp** [comment]
![image](https://user-images.githubusercontent.com/27992285/89095205-3c41b000-d3e9-11ea-86b4-9bf542b7e56d.png)

@vchong  Above Snippet is from NXP LX2160A-RDB Reference Manual CCSR map, It has 4 GPIOs and for each base address is fixed.
If I understood correctly, there is no concept of banks and we cannot deduce the base address from pin numbers in this case.

**Comment by vchong** [comment]
@sahilnxp So gpio.h has to be able to accommodate all supported platforms, of which each determination of the base address is different. If you need support for this, you can do as @jenswi-linaro suggested, e.g. in nxp_gpio.h, define:
```
struct nxp_gpio_data {
    struct gpio_chip chip;
    vaddr_t base_addr;
}
```

See pl011.h and pl011.c for references.

**Comment by sahilnxp** [comment]
@vchong Yes, we are going to do in this way as suggested by you and @jenswi-linaro.

Thanks
Sahil Malhotra

**Comment by ruchi393** [comment]
@sahilnxp , to manage multiple GPIO controllers you may want to maintain a list of such nxp_gpio_chip (instead of struct nxp_gpio_data)

You can check core/include/drivers/bcm_gpio.h which is a similar example where they have 2 gpio controllers.

**Comment by sahilnxp** [comment]
@ruchi393 Thanks for suggestion.
Yes, we can do that also, but I think this responsibility of maintaining list of different controllers will lie with GPIO controller user for now.
