### ISSUE TITLE
Port for Ultra96 V2

### ISSUE THREAD

**Issue by elias-vd** [OP-TEE/optee_os#4015]
Does anyone had done a port to the Ultra96 V2? 

Kind regards and thanks in advance

**Comment by janoslim** [comment]
Hello, @elias-vd 

I am currently trying porting optee on ultra96-v2,
Did you succeed in porting the optee on the ultra96 board? If so, can I get some advice?

Thank you.

**Comment by elias-vd** [comment]
unfortunately not :(
