### ISSUE TITLE
Add an instruction to busybox

### ISSUE THREAD

**Issue by hayannoon** [OP-TEE/optee_os#4018]
Hi!!!
I ported optee_os to my hikey960 board successfully.
And I wanted to execute "taskset" instruction. but my board couldn't recognize the instruction.
So I searched the reason then I think that I should modify busybox/menuconfig. 
but, in my busybox directory, there is not menuconfig file.

So, How can I use "taskset" instruction in my board? 
help me please....

**Comment by jenswi-linaro** [comment]
The easiest would be to find out which config variable (`BR2_PACKAGE_xxx`) that is needed to be set to `y` and add such a line to `build/br-ext/configs/optee_generic`.

**Comment by hayannoon** [comment]
> The easiest would be to find out which config variable (`BR2_PACKAGE_xxx`) that is needed to be set to `y` and add such a line to `build/br-ext/configs/optee_generic`.

I didn't find the config variable for "taskset". but I tested the way using BR2_PACKAGE_SUDO and BR2_PACKAGE_GCC. 
then I recompiled and flashed into my board. but the board couldn't recognize "sudo" and "gcc". how can i add the instruction set?

**Comment by etienne-lms** [comment]
@hayannoon, as @jenswi-linaro said, the rootfs is built from Buildroot. Checkout the packages supported by Buildroot to see if you can embed some tools (gcc, sudo, ...) or libraries. As Jens said, set related `BR2_*` config switches in `build/br-ext/configs/optee_generic` and rebuild.
