### ISSUE TITLE
How RPMB key generation works

### ISSUE THREAD

**Issue by Vitolog** [OP-TEE/optee_os#4019]
I would understand better how RPMB key generetion works and how some "corner cases" are managed.

1. RPMB pre-shared key internally generated by TA is obtained from eMMC CID, hence unique for each eMMC...right?

1. How TA knows if the pre-shared is already generated and shared with the eMMC after a reboot?

1. The RPMB is automatically generated by the TA or a command from a client in normal world is needed in order to start the key generation?

1. If CFG_RPMB_WRITE_KEY is left y in a production build, the pre-shared key is sent in normal world at each reboot?

**Comment by jenswi-linaro** [comment]
> I would understand better how RPMB key generetion works and how some "corner cases" are managed.
> 
>     1. RPMB pre-shared key internally generated by TA is obtained from eMMC CID, hence unique for each eMMC...right?

This part is hidden from the TA. But yes, that key is unique for each eMMC among other things.

> 
>     2. How TA knows if the pre-shared is already generated and shared with the eMMC after a reboot?

The management is hidden from the TA.

> 
>     3. The RPMB is automatically generated by the TA or a command from a client in normal world is needed in order to start the key generation?

The key is automatically generated.

> 
>     4. If CFG_RPMB_WRITE_KEY is left y in a production build, the pre-shared key is sent in normal world at each reboot?

Yes, normal world could trick secure world into believing that no key has been programmed. Then secure world would decide to try to program one which would be sent in clear text.

**Comment by jforissier** [comment]
Hi @Vitolog,

> 3. The RPMB is automatically generated by the TA or a command from a client in normal world is needed in order to start the key generation?

The RPMB key is automatically generated and programmed into the RPMB device when `CFG_RPMB_WRITE_KEY=y`. Typically you would build a special version of OP-TEE with this flag set and run it at the factory. Later, this CFG flag is not needed anymore and the TEE core will detect that the key is programmed in the RPMB device [here](https://github.com/OP-TEE/optee_os/blob/3.9.0/core/tee/tee_rpmb_fs.c#L1148) in `tee_rpmb_init()`. So, the deployed OP-TEE **must** be built **without** this flag (otherwise it would be a security vulnerability as mentioned by Jens).

**Comment by Vitolog** [comment]
Thanks for your replies.
For what I've seen:

- At boot time the write counter value is requested by TA to eMMC

- The returned data is verified with returned HMAC and RPMB key internally generated by TA at boot time

- If the verification fails (e.g. wrong data received or no data received....could you confirm this happens in both cases?)  the TA tries to re-write the key if CFG_RPMB_WRITE_KEY=y, otherwise TA goes in TEE_ERROR_BAD_STATE

If my understandig is correct, an attacker could: 

1. generate a verification failure on the eMMC-SoC bus or directly in REE

1. Force TA to re-send the RPMB key (if CFG_RPMB_WRITE_KEY=y) and sniff it

In this way an attacker is able to forge valid packets to be written to RPMB partition.
If the RPMB partition is used by secure storage TA, all data stored are encrypted. In this case I see two possible scenario:

1. An attacker writes garbage data on RPMB partition generating a denial-of-service

1. An attacker re-writes previously dumped valid encrypted data (I'm not so sure about this point if it is true or not)

Is my understanding correct?

**Comment by jenswi-linaro** [comment]
> Thanks for your replies.
> For what I've seen:
> 
>     * At boot time the write counter value is requested by TA to eMMC

It isn't the TA itself that requests this, but it could trigger OP-TEE OS to do this.

> 
>     * The returned data is verified with returned HMAC and RPMB key internally generated by TA at boot time

Again, it's not the TA that does this. It is OP-TEE OS that does this as part of the service to the TA.

> 
>     * If the verification fails (e.g. wrong data received or no data received....could you confirm this happens in both cases?)  the TA tries to re-write the key if CFG_RPMB_WRITE_KEY=y, otherwise TA goes in TEE_ERROR_BAD_STATE

No, key rewrite cannot be triggered once OP-TEE OS is has established correct communication with the RPMB. What error code the TA will see I can't tell without testing.

> 
> 
> If my understandig is correct, an attacker could:
> 
>     1. generate a verification failure on the eMMC-SoC bus or directly in REE
> 
>     2. Force TA to re-send the RPMB key (if CFG_RPMB_WRITE_KEY=y) and sniff it

Yes that's possible if done at the correct moment and OP-TEE is compiled with CFG_RPMB_WRITE_KEY=y.

> 
> 
> In this way an attacker is able to forge valid packets to be written to RPMB partition.
> If the RPMB partition is used by secure storage TA, all data stored are encrypted. In this case I see two possible scenario:
> 
>     1. An attacker writes garbage data on RPMB partition generating a denial-of-service
> 
>     2. An attacker re-writes previously dumped valid encrypted data (I'm not so sure about this point if it is true or not)
> 
> 
> Is my understanding correct?

Yeah, once you have the RPMB key the security of RPMB is gone. So this key must be protected by avoiding CFG_RPMB_WRITE_KEY=y.

**Comment by Vitolog** [comment]
Thanks for your replies.
One question: why the solution proposed in [2887](https://github.com/OP-TEE/optee_os/issues/2887) hasn't been integrated in mainline?

**Comment by jenswi-linaro** [comment]
> Thanks for your replies.
> One question: why the solution proposed in [2887](https://github.com/OP-TEE/optee_os/issues/2887) hasn't been integrated in mainline?

No PR has been proposed. It's been a while since I looked into that discussion so I can't recall if we ever agreed that it was good or not.
