### ISSUE TITLE
Panic at core/arch/arm/mm/core_mmu_lpae.c:371 <check_nsec_ddr_max_pa>

### ISSUE THREAD

**Issue by deekshith565** [OP-TEE/optee_os#4025]
I'm recently migrating our optee_os version 3.5.0 to 3.8.0, compilation is success but I'm getting below error during boot 

**M/TC: Enter check_nsec_ddr_max_pa check_nsec_ddr_max_pa
"E/TC:00 0 Panic at core/arch/arm/mm/core_mmu_lpae.c:366 <check_nsec_ddr_max_pa>"**

I checked all address with 3.5.0 but nothing helped, can someone help me with the issue

**Comment by forissier** [comment]
Hi @deekshith565 ,

Perhaps you need `CFG_CORE_LARGE_PHYS_ADDR=y`? Although it should be no different in 3.5.0 and 3.8.0.
Have you tried to print the parameters of `core_mmu_check_end_pa()`?

**Comment by jforissier** [comment]
Hi @deekshith565 ,

Perhaps you need `CFG_CORE_LARGE_PHYS_ADDR=y`? Although it should be no different in 3.5.0 and 3.8.0.
Have you tried to print the parameters of `core_mmu_check_end_pa()`?

**Comment by deekshith565** [comment]
@jforissier yes I checked, 3.5.0 and 3.8.0 both I verified, same
I'm getting error from core_mmu_check_max_pa(), below is where it is returning 0

```
#if defined(ARM64)
return pa <= (BIT64(CFG_CORE_ARM64_PA_BITS) - 1);
```
from prints I see below 
pa = 0 (i.e, end_pa from core_mmu_check_end_pa)
CFG_CORE_ARM64_PA_BITS = 36
BIT64(CFG_CORE_ARM64_PA_BITS) = 0

**Comment by jenswi-linaro** [comment]
It looks like the `BIT64()` somehow is broken and works with 32-bit values instead.
Problem with the toolchain or out of tree changes related to `BIT64()`?

**Comment by deekshith565** [comment]
I'm using below toolchain:

gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu/bin
gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/bin

**out of tree changes related to BIT64()?** 
I didn't get what this means.

**Comment by jenswi-linaro** [comment]
> **out of tree changes related to BIT64()?**
> I didn't get what this means.

Do you have any changes on top of `3.8.0`?
`git diff --stat 3.8.0` is empty?

**Comment by deekshith565** [comment]
Ok the issue is resolved our pa bit size is 40, so with
CFG_CORE_ARM64_PA_BITS = 40,  it worked 

Can anyone share yocto recipes file for 3.8.0 versions of optee_os, optee_client and optee_test

**Comment by deekshith565** [comment]
Thanks for the support closing issue as it is resolved.
