### ISSUE TITLE
Question: Measuring time taken by TEE_MemMove

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#4029]
Hello,

i've written a sample trusted application so as to compare the performance between memcpy() and TEE_MemMove().
I hit a dead end as i won't be able to use the api's like clock_gettime() etc from the time.h header of libc.

Is there any method i could use to measure the time taken by memcpy() and TEE_MemMove() in the trusted application?

**Comment by jforissier** [comment]
Hello @saddy-muchu,

If your platform supports CNTPCT ("Counter-timer Physical Count Register"), you may use `uint64_t read_cntpct()` from `<arm_user_sysreg.h>`. If needed, `uint32_t read_cntfrq()` will return the timer frequency so that you can convert counter ticks to seconds.

**Comment by saddy-muchu** [comment]
i'm currently on an old OP-TEE 3.1.0.
I guess the header <arm_user_sysreg.h> isn't available in 3.1.0

**Comment by jforissier** [comment]
Here are the files.

[arm_user_sysreg.h.txt](https://github.com/OP-TEE/optee_os/files/5063326/arm_user_sysreg.h.txt)
[arm32_user_sysreg.h.txt](https://github.com/OP-TEE/optee_os/files/5063324/arm32_user_sysreg.h.txt)
[arm64_user_sysreg.h.txt](https://github.com/OP-TEE/optee_os/files/5063325/arm64_user_sysreg.h.txt)

**Comment by saddy-muchu** [comment]
Thanks a lot for the files.
So, basically i could do something like:

..................
uint64_t memcpy_time = 0;
uint64_t memmove_time = 0;

memcpy(dest_buf, src_buf, num_bytes);
memcpy_time = read_cntpct();

memmove(dest_buf, src_buf, num_bytes);
memmove_time = read_cntpct();
........................

Please correct me if i'm wrong or if i'm missing something.

**Comment by jforissier** [comment]
No, it should be:
```C
uint64_t t1, t2, memcpy_time, memmove_time;

t1 = read_cntpct();
memcpy(dest_buf, src_buf, num_bytes);
t2 = read_cntpct();
memcpy_time = t2 - t1;

t1 = read_cntpct();
memmove(dest_buf, src_buf, num_bytes);
t2 = read_cntpct();
memmove_time = t2 - t1;
```

**Comment by saddy-muchu** [comment]
Thank you.

Looks like i'm ending up in a panic due to the usage of read_cntpct().
I'm currently using a renesas H3 starterkit. It's based on ARM V8.

How can i proceed w.r.t this?

**Comment by jforissier** [comment]
> Thank you.
> 
> Looks like i'm ending up in a panic due to the usage of read_cntpct().
> 
> "perf_test: TEEC_InvokeCommand failed with code 0xffff3024 origin 0x3"
> 0xffff3024 is "TEE_ERROR_TARGET_DEAD" with an error origin from TEE

You probably just need to enable access to CNTPCT from EL0 like so: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread.c#L1062-L1067

> 
> I'm currently using a renesas H3 starterkit. It's based on ARM V8.
> 
> How can i proceed w.r.t this?
> could i use this: https://optee.readthedocs.io/en/latest/debug/ftrace.html#ftrace as the last option as the function trace also prints the function's time on the LHS?

Yes but the code might be hard to backport to your version (3.1.0).

**Comment by saddy-muchu** [comment]
> 
> 
> > Thank you.
> > Looks like i'm ending up in a panic due to the usage of read_cntpct().
> > "perf_test: TEEC_InvokeCommand failed with code 0xffff3024 origin 0x3"
> > 0xffff3024 is "TEE_ERROR_TARGET_DEAD" with an error origin from TEE
> 
> You probably just need to enable access to CNTPCT from EL0 like so: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread.c#L1062-L1067
> Or how about TEE_GetSystemTime()?

**Comment by jforissier** [comment]
> > You probably just need to enable access to CNTPCT from EL0 like so: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread.c#L1062-L1067
> 
> I don't have that timer register in my platform.
OK.

> How about TEE_GetSystemTime()?

Has a minimum resolution of 1 Ms in any case, and on your platform without CNTPCT it will get the time from the REE if I remember correctly, so it will be extraordinarily imprecise 😮

**Comment by saddy-muchu** [comment]
Yes, I feared that.
Then looks like I don't have any other choice in order to get a precise time measurement without the involvement of REE :(

**Comment by saddy-muchu** [comment]
So, i was trying to query the value of the property "gpd.tee.systemTime.protectionLevel" so as to know the clock source as below:

    TEE_Result res = TEE_SUCCESS;
    uint32_t protection_level;
    res = TEE_GetPropertyAsU32(TEE_PROPSET_CURRENT_CLIENT,
                                                  (char *)"gpd.tee.systemTime.protectionLevel",
                                                  &protection_level);

    if (res == TEE_SUCCESS) {
        DMSG("returned success and protection_level = %d\n", protection_level);
    }

But i end up in TEE_ERROR_ITEM_NOT_FOUND. Maybe the API is not able to find the property string.

**Comment by jforissier** [comment]
> So, i was trying to query the value of the property "gpd.tee.systemTime.protectionLevel" so as to know the clock source as below:
> 
> ```
> TEE_Result res = TEE_SUCCESS;
> uint32_t protection_level;
> res = TEE_GetPropertyAsU32(TEE_PROPSET_CURRENT_CLIENT,

You need to use `TEE_PROPSET_TEE_IMPLEMENTATION` here.

>                                               (char *)"gpd.tee.systemTime.protectionLevel",
>                                               &protection_level);
> 
> if (res == TEE_SUCCESS) {
>     DMSG("returned success and protection_level = %d\n", protection_level);
> }
> ```
> 
> But i end up in TEE_ERROR_ITEM_NOT_FOUND. Maybe the API is not able to find the property string.
> 
> If i'm not wrong, if the CNTPCT timer register is used via read_cntpct(), then protection_level=1000 and hence linux or REE is never involved during the time calculation i.e the time calculation is purely based on the OPTEE controlled secure timer.
> Am i correct?

Yes. There are config flags for this: `CFG_SECURE_TIME_SOURCE_CNTPCT` and `CFG_SECURE_TIME_SOURCE_REE`. You can see some platforms enabling one or the other depending on whether or not they have CNTPCT.

> 
> Also, i tried to get the memcpy_time as follows:
> 
> TEE_Time start, stop;
> uint64_t memcpy_time;
> 
> TEE_GetSystemTime(&start);
> memcpy(obuf, ibuf, ibuf_size);
> TEE_GetSystemTime(&stop);
> memcpy_time = stop.millis - start.millis;
> 
> TA panics as TEE_GetSystemTime() returns with TEE_ERROR_TARGET_DEAD error code.
> Same is the case with TEE_GetTAPersistentTime() too :(
> Panic seems to be from OP-TEE core and not the TA as error origin is 0x3.

That's bad. Does you platform pass the `xtest` suite successfully? That would be a good start. `xtest 1006` tests the "basic OS features" including the properties and time APIs.

**Comment by saddy-muchu** [comment]
> 
> 
> > So, i was trying to query the value of the property "gpd.tee.systemTime.protectionLevel" so as to know the clock source as below:
> > ```
> > TEE_Result res = TEE_SUCCESS;
> > uint32_t protection_level;
> > res = TEE_GetPropertyAsU32(TEE_PROPSET_CURRENT_CLIENT,
> > ```
> 
> You need to use `TEE_PROPSET_TEE_IMPLEMENTATION` here.


Thanks for the correction.
I end up in a protection level of 1000. But, usage of this property should end up in a protection level of 100 rite?
I'm a little confused here.

> > ```
> >                                           (char *)"gpd.tee.systemTime.protectionLevel",
> >                                           &protection_level);
> > ```
> > 
> > 
> > if (res == TEE_SUCCESS) {
> > DMSG("returned success and protection_level = %d\n", protection_level);
> > }
> > ```
> > 
> > But i end up in TEE_ERROR_ITEM_NOT_FOUND. Maybe the API is not able to find the property string.
> > 
> > If i'm not wrong, if the CNTPCT timer register is used via read_cntpct(), then protection_level=1000 and hence linux or REE is never involved during the time calculation i.e the time calculation is purely based on the OPTEE controlled secure timer.
> > Am i correct?
> > ```
> 
> Yes. There are config flags for this: `CFG_SECURE_TIME_SOURCE_CNTPCT` and `CFG_SECURE_TIME_SOURCE_REE`. You can see some platforms enabling one or the other depending on whether or not they have CNTPCT.

Thanks for the information. This is really helpful.

> > Also, i tried to get the memcpy_time as follows:
> > TEE_Time start, stop;
> > uint64_t memcpy_time;
> > TEE_GetSystemTime(&start);
> > memcpy(obuf, ibuf, ibuf_size);
> > TEE_GetSystemTime(&stop);
> > memcpy_time = stop.millis - start.millis;
> > TA panics as TEE_GetSystemTime() returns with TEE_ERROR_TARGET_DEAD error code.
> > Same is the case with TEE_GetTAPersistentTime() too :(
> > Panic seems to be from OP-TEE core and not the TA as error origin is 0x3.
> 
> That's bad. Does you platform pass the `xtest` suite successfully? That would be a good start. `xtest 1006` tests the "basic OS features" including the properties and time APIs.

Maybe i need to setup my build environment accordingly for XTEST to run on OP-TEE 3.1.0. I'll get back to you with results.

**Comment by jforissier** [comment]
> > > So, i was trying to query the value of the property "gpd.tee.systemTime.protectionLevel" so as to know the clock source as below:
> > > ```
> > > TEE_Result res = TEE_SUCCESS;
> > > uint32_t protection_level;
> > > res = TEE_GetPropertyAsU32(TEE_PROPSET_CURRENT_CLIENT,
> > > ```
> > 
> > 
> > You need to use `TEE_PROPSET_TEE_IMPLEMENTATION` here.
> 
> Thanks for the correction.
> I end up in a protection level of 1000. But, usage of this property should end up in a protection level of 100 rite?

Yes. 2cdaaacb. Perhaps you platform sets `CFG_SECURE_TIME_SOURCE_CNTPCT=y` when in fact it should set `CFG_SECURE_TIME_SOURCE_REE=y`? That would explain the 1000 and the panic with `TEE_GetSystemTime()`.

**Comment by saddy-muchu** [comment]
So, we set gpd.tee.systemTime.protectionLevel to 1000 when the time source
is the physical count register (CNTPCT), that is, when CFG_SECURE_TIME_SOURCE_CNTPCT=y. 

When the time source is REE (CFG_SECURE_TIME_SOURCE_REE=y), then gpd.tee.systemTime.protectionLevel is 100.

Am i right?

My platform sets CFG_SECURE_TIME_SOURCE_CNTPCT=y. 
So, TEE_GetSystemTime() in my case is using the OPTEE secure timer instead of the REE timer.

**Comment by jforissier** [comment]
> So, we set gpd.tee.systemTime.protectionLevel to 1000 when the time source
> is the physical count register (CNTPCT), that is, when CFG_SECURE_TIME_SOURCE_CNTPCT=y.
> 
> When the time source is REE (CFG_SECURE_TIME_SOURCE_REE=y), then gpd.tee.systemTime.protectionLevel is 100.
> 
> Am i right?

Yes.

> My platform sets CFG_SECURE_TIME_SOURCE_CNTPCT=y.
> So, TEE_GetSystemTime() in my case is using the OPTEE secure timer instead of the REE timer.

Yes. Which is wrong if your platform cannot use CNTPCT as you said above.

**Comment by saddy-muchu** [comment]
> > My platform sets CFG_SECURE_TIME_SOURCE_CNTPCT=y.
> > So, TEE_GetSystemTime() in my case is using the OPTEE secure timer instead of the REE timer.
> 
> Yes. Which is wrong if your platform cannot use CNTPCT as you said above.

OK.

My platform passes the xtest suite too.
Any extra settings need to be done from the TA side to use the TEE time API's?

**Comment by jforissier** [comment]
> My platform passes the xtest suite too.

:confused: You said `TEE_GetSystemTime()` panics in your TA, yet `xtest 1006` calls `TEE_GetSystemTime()`. Weird.

**Comment by saddy-muchu** [comment]
> 
> 
> > My platform passes the xtest suite too.
> 
> 😕 You said `TEE_GetSystemTime()` panics in your TA, yet `xtest 1006` calls `TEE_GetSystemTime()`. Weird.

I used a very old tag of optee-test i.e. 3.1.0 as my current optee-os is 3.1.0
Not sure if the Time API's are tested as part of the test-suite in this tag version.

**Comment by jforissier** [comment]
> I used a very old tag of optee-test i.e. 3.1.0 as my current optee-os is 3.1.0
> Not sure if the Time API's are tested as part of the test-suite in this tag version.

It is.
```
optee_test ((3.1.0))$ cat -n ta/os_test/os_test.c | sed '495,506!d'
   495  static TEE_Result test_time(void)
   496  {
   497          TEE_Result res;
   498          TEE_Time t;
   499          TEE_Time sys_t;
   500
   501          static const TEE_Time null_time = { 0, 0 };
   502          static const TEE_Time wrap_time = { UINT32_MAX, 999 };
   503
   504          TEE_GetSystemTime(&sys_t);
   505          printf("system time %u.%03u\n", (unsigned int)sys_t.seconds,
   506                 (unsigned int)sys_t.millis);
```

**Comment by saddy-muchu** [comment]
Yes.
Looks like.

I guess i'm hunting ghosts right now.
There should be something wrong with my TA.

Thanks for your time and prompt responses.
I learnt a lot through this discussion.
