### ISSUE TITLE
TEE_CacheFlush() api returns with TEE_ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#4036]
I've enabled the TA_FLAG_CACHE_MAINTENANCE flag for my TA.
Still ending up in this error code.

Any hints as to why this could happen?

Thanks.

**Comment by saddy-muchu** [comment]
Btw, my OPTEE-SDK doesn't have a CFG_CACHE_API entry at all in the conf.mk file.
Could this be the reason?

**Comment by Emantor** [comment]
If `CFG_CACHE_API` is not `y`, the syscall will always return `TEE_ERROR_NOT_SUPPORTED`, done in `core/include/tee/svc_cache.h`. OP-TEE needs to be recompiled with `CFG_CACHE_API` to access the cache functions.

**Comment by saddy-muchu** [comment]
OK.

Thanks for the information.
