### ISSUE TITLE
get_va_width()

### ISSUE THREAD

**Issue by Master-Chi** [OP-TEE/optee_os#4037]
in core/arch/arm/mm/core_mmu.c
static unsigned int get_va_width(void)
{
        if (IS_ENABLED(ARM64))
                return 64 - __builtin_ctzll(CFG_LPAE_ADDR_SPACE_SIZE);
        else
                return 32;
}
I think maybe
return __builtin_ctzll(CFG_LPAE_ADDR_SPACE_SIZE);
is right

thanks

**Comment by jforissier** [comment]
Hi @Master-Chi,

I agree. @jenswi-linaro?

**Comment by jenswi-linaro** [comment]
Agree, perhaps combined with:
``` C
COMPILE_TIME_ASSERT(IS_POWER_OF_TWO(CFG_LPAE_ADDR_SPACE_SIZE));
```

**Comment by jforissier** [comment]
@Master-Chi would you mind creating a pull request with this fix?

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/4042
