### ISSUE TITLE
Build error when using public TA_SIGN_KEY

### ISSUE THREAD

**Issue by marksaenger** [OP-TEE/optee_os#4038]
Hello,

I've read the documentation regarding TA_SIGN_KEY and offline signing here [https://optee.readthedocs.io/en/latest/building/trusted_applications.html#signing-of-tas](https://optee.readthedocs.io/en/latest/building/trusted_applications.html#signing-of-tas) but I'm still a little confused on the best practices for production purposes.

The documentation explicitly states that the `default_ta.pem` private key should be replaced with a **public** key since the private part of the key should not be built in to optee-os.  The private key would then be stored offline and used for signing the TAs.  That all makes sense.  The part where I am having issues is when I go to setting TA_SIGN_KEY to point to a different key in the Makefile.  I set that variable to point to a **public** key and I get an error in the build process that complains about the key not having a private part to it when it goes to sign some TAs, which makes sense.  The one TA that failed was avb which I don't think I need.  Is it expected to remove all of the pre-bundled TAs that we won't use so that the build procedure only builds the operating system and therefore doesn't hit this issue?  How do I go about doing that?  I can't seem to find the area that builds the TA's in optee-os/ta.  In my head I want to build optee-os and any TAs separately so that it's more clear when I sign the TAs offline using the private key.

**Comment by jforissier** [comment]
Hi @marksaenger,

> Is it expected to remove all of the pre-bundled TAs that we won't use so that the build procedure only builds the operating system and therefore doesn't hit this issue? How do I go about doing that? I can't seem to find the area that builds the TA's in optee-os/ta

Here: https://github.com/OP-TEE/optee_os/blob/3.10.0-rc1/Makefile#L97

**Comment by marksaenger** [comment]
> Hi @marksaenger,
> 
> > Is it expected to remove all of the pre-bundled TAs that we won't use so that the build procedure only builds the operating system and therefore doesn't hit this issue? How do I go about doing that? I can't seem to find the area that builds the TA's in optee-os/ta
> 
> Here: https://github.com/OP-TEE/optee_os/blob/3.10.0-rc1/Makefile#L97

Awesome, thank you!  Do you suggest removing this section of the Makefile or setting `CFG_WITH_USER_TA` to `n`?  This variable is used in a lot more places so I'm unsure of the ramifications of doing that.

**Comment by jforissier** [comment]
> Do you suggest removing this section of the Makefile

As a short-term workaround, yes. But I think we need a more flexible solution. In-tree TAs (as we call them) should probably be all built by default (for easier compile testing/regression testing) but we should also be able to select which ones we want individually. To makes things more complex, when TA_SIGN_KEY is defined we can only compile up to the `.elf` file (`.stripped.elf` actually) and not up to the `.ta`. And we need to consider `CFG_IN_TREE_EARLY_TAS` which allows to specify which in-tree TAs (`.stripped.elf` files) are embedded into the TEE binary...

> or setting `CFG_WITH_USER_TA` to `n`?

Certainly not, doing so would disable support for user space TAs altogether! :wink:

**Comment by marksaenger** [comment]
> As a short-term workaround, yes. But I think we need a more flexible solution. In-tree TAs (as we call them) should probably be all built by default (for easier compile testing/regression testing) but we should also be able to select which ones we want individually. To makes things more complex, when TA_SIGN_KEY is defined we can only compile up to the `.elf` file (`.stripped.elf` actually) and not up to the `.ta`. And we need to consider `CFG_IN_TREE_EARLY_TAS` which allows to specify which in-tree TAs (`.stripped.elf` files) are embedded into the TEE binary...

Ok that all makes sense.  But when TA_SIGN_KEY is defined (public key only) then the sign.py script produces an error.  It seems to me that maybe it should be a warning at most?  That way at least the .stripped.elf in-tree TAs are built but still need to be signed as a last step.  Or maybe if TA_SIGN_KEY points to anything other than the default_ta.pem it triggers a different path more suited for production.  Still pretty new to all of this so just thinking off the top of my head.

> Certainly not, doing so would disable support for user space TAs altogether! wink

Ah! Yes that is definitely not what I want.
