### ISSUE TITLE
With CFG_CRYPTOLIB_NAME=mbedtls, TEE_GenerateKey with DH can't guarantee the private value x bits

### ISSUE THREAD

**Issue by mazhenke** [OP-TEE/optee_os#4041]
Hi,

When CFG_CRYPTOLIB_NAME=mbedtls,  function **crypto_acipher_gen_dh_key** in **lib/libmbedtls/core/dh.c** can't guarantee that the generated DH private key (dhm.X) has exactly **xbits** in the function paramter. This is because the mbedtls funcion mbedtls_dhm_make_public generates private key within [2, P - 2], and doesn't take paramter **xbits**.

Do we plan to modify mbedtls function mbedtls_dhm_make_public to meet the OP-TEE's requirment?

Thanks,
Zhenke

**Comment by jenswi-linaro** [comment]
That's not completely accurate, `mbedtls_dhm_make_public()` takes an `xbytes` parameter instead of `xbits`. It's not as precise, but it might be good enough for conformance.

I'm not aware of any plans to modify `mbedtls_dhm_make_public()`. If we're going to do this we should aim at fixing upstream first.

**Comment by mazhenke** [comment]
This will cause **xtest -t regression 4007 -l 15** randomly failure:

_[2020-08-18 15:27:18] o regression_4007_dh.10 Generate DH key 832 bits - Private bits = 416
[2020-08-18 15:27:18] /data/zhema01/local_work/dev2/optee_test/host/xtest/regression_4000.c:4512: Expression "out_size == key_size / 8" (51 == 52) is false
[2020-08-18 15:27:18]   regression_4007_dh.10 FAILED
[2020-08-18 15:27:18] o regression_4007_dh.11 Generate DH key 896 bits - Private bits = 0
[2020-08-18 15:27:18]   regression_4007_dh.11 OK_

The fail is because bignumebr dhm.X has one byte 0x00 at MSB.

**Comment by jenswi-linaro** [comment]
OK, I see the problem. Mbedtls takes it as maximum number of bytes while GP expects this number.

We should still start by engaging with upstream to get their input too.

**Comment by jforissier** [comment]
In my opinion the check on the generated key size is bogus and this is silly too: https://github.com/OP-TEE/optee_os/blob/3.10.0/core/lib/libtomcrypt/src/pk/dh/dh_make_key.c#L119-L121. By forcing the MSB to 1 we loose one bit of key size.

**Comment by jforissier** [comment]
The following patch seems to fix the issue, I don't know if it would be acceptable for upstream: https://github.com/jforissier/optee_os/commit/mbedtls-dh-x_size.

**Comment by jenswi-linaro** [comment]
I think it might be worth a shot with the patch above (once fixed up). At least we could start a discussion with it. What do you think @jforissier ?

**Comment by jforissier** [comment]
https://github.com/ARMmbed/mbedtls/issues/3839

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/4215 and https://github.com/OP-TEE/optee_test/pull/465.
