### ISSUE TITLE
lmbench

### ISSUE THREAD

**Issue by hayannoon** [OP-TEE/optee_os#4045]
I want to run lmbench in my hikey960 board.
So, I set menuconfig and got lmbench-3.0-a9. But, When I build the kernel, 

ERROR: architecture for "/bin/lmbench-3.0-a9/bin/i586/lib_tcp.o" is "Intel 80386", should be "AArch64"
ERROR: architecture for "/bin/lmbench-3.0-a9/bin/i586/lib_udp.o" is "Intel 80386", should be "AArch64"
ERROR: architecture for "/bin/lmbench-3.0-a9/bin/i586/lib_unix.o" is "Intel 80386", should be "AArch64"
ERROR: architecture for "/bin/lmbench-3.0-a9/bin/i586/lib_stats.o" is "Intel 80386", should be "AArch64"
ERROR: architecture for "/bin/lmbench-3.0-a9/bin/i586/lib_timing.o" is "Intel 80386", should be "AArch64"
ERROR: architecture for "/bin/lmbench-3.0-a9/bin/i586/lib_debug.o" is "Intel 80386", should be "AArch64"
ERROR: architecture for "/bin/lmbench-3.0-a9/bin/i586/getopt.o" is "Intel 80386", should be "AArch64"
ERROR: architecture for "/bin/lmbench-3.0-a9/bin/i586/lib_sched.o" is "Intel 80386", should be "AArch64"
ERROR: architecture for "/bin/lmbench-3.0-a9/bin/i586/msleep" is "Intel 80386", should be "AArch64"
ERROR: architecture for "/bin/lmbench-3.0-a9/bin/i586/flushdisk" is "Intel 80386", should be "AArch64"
.....
This error appeard. I think this lmbench files are for intel micro processor.
How can i use this lmbench in the arm64 micro processor?

**Comment by Emantor** [comment]
How does this relate to OP-TEE?
