### ISSUE TITLE
How to get/melloc a physical continuous memory in optee-os core?

### ISSUE THREAD

**Issue by bqiu728** [OP-TEE/optee_os#4046]
Hi,
I'm trying to realize a hardware backed DMA like driver, which need me to allocte a physical continuous memory.
Can I use malloc or is there any other way?

thanks

**Comment by jenswi-linaro** [comment]
`malloc()` should normally give physically contiguous memory, so it should be OK.

**Comment by bqiu728** [comment]
> 
> 
> `malloc()` should normally give physically contiguous memory, so it should be OK.

thanks
