### ISSUE TITLE
RPMB issue in OP-TEE 3.8.0

### ISSUE THREAD

**Issue by elliotmtx** [OP-TEE/optee_os#4055]
I'm migrating OP-TEE from version 3.5.0 to 3.8.0, where I see issue with RPMB(eMMC), all my xtest test cases are failing with TEEC_ERROR_SECURITY, through prints I see memcmp is failing from init_head_from_data() in core/tee/fs_htree.c.  if(idx) return TEE_ERROR_SECURITY; in below code is where I am getting error.

````
static TEE_Result init_head_from_data(struct tee_fs_htree *ht,
				      const uint8_t *hash)
{
	TEE_Result res;
	int idx;

	if (hash) {
		for (idx = 0;; idx++) {
			res = rpc_read_node(ht, 1, idx, &ht->root.node);
			if (res != TEE_SUCCESS)
				return res;

			if (!memcmp(ht->root.node.hash, hash,
				    sizeof(ht->root.node.hash))) {
				res = rpc_read_head(ht, idx, &ht->head);
				if (res != TEE_SUCCESS)
					return res;
				break;
			}

			if (idx)
				return TEE_ERROR_SECURITY`
```

I enabled CFG_RPMB_RESET_FAT flag and this worked(on some boards after deleting /data/tee)
and **on same boards**(that is once after doing with this flag enable) now with CFG_RPMB_RESET_FAT flag disable also it is working, so basically I observed to do this reset once per board.

So what I want to understand is 
1. is this reset mandatory to do? 
2. are there any structure changes from 3.5.0 to 3.8.0 which is causing issue? 
3. will there be any left over from previous version in FAT and /data/tee that need to be cleared, that is why with reset flag it is working?  

Kindly help me understand.

**Comment by jenswi-linaro** [comment]
I don't think this should be needed. However, if you're sometimes trying to run without `CFG_RPMB_FS=y` you may get out of sync with the REE FS hash stored in RPMB.

In the code above both top hashes are checked against the provided one, and none matched. Note that this function is used when opening both the `dirf.db` object and the ones with a plain number. If it's `dirf.db` that fails then there's a mismatch with the hash in RPMB, else there's some other corruption.
