### ISSUE TITLE
Is there any side-effect to register an OTP driver in service_init()?

### ISSUE THREAD

**Issue by angelina-zhao** [OP-TEE/optee_os#4058]
https://github.com/OP-TEE/optee_os/issues/3845#issue-613942350

@jenswi-linaro @ElonZhang0328
Do you have any conclusion on above issue, as I see there is no update and the issue is closed?

I met the same issue as described above, as tee_otp_get_hw_unique_key() is called in service but the unique key is saved in OTP and the OTP driver (which is registered in driver_init()) is not ready yet.

Can I register my OTP driver in service_init() to solve this confliction?  Is there any side-effect to do so?

Thanks.

**Comment by jforissier** [comment]
> Can I register my OTP driver in service_init() to solve this confliction? Is there any side-effect to do so?

Yes, it should be fine in my opinion. In fact there is no strict definition of what is a "service" vs. what is a "driver". The names simply map to different numbers in the initcall sequence. These names are supposed to help pick the proper level in general, but sometimes you need to deal with dependencies for your platform such as the one you are mentioning here.

**Comment by angelina-zhao** [comment]
Thank you very much for you suggestions.  I will follow this rule to arrange my components.
