### ISSUE TITLE
【QA】How to use eSE on optee-os?

### ISSUE THREAD

**Issue by sunnybird** [OP-TEE/optee_os#4059]
I intent to use eSE on optee-os . but i can not find some manual.

**Comment by jenswi-linaro** [comment]
We had support for Secure Elements a few years ago, but the code was never widely used and has since been removed.

**Comment by etienne-lms** [comment]
What's eSE?
Do you refer to embedded Secure Element, some kind of TPM like chip?
If so, OP-TEE does not yet provide such support but contributions are welcome :)

As for OP-TEE documentation, see http://optee.readthedocs.io.

**Comment by sunnybird** [comment]
> What's eSE?
> Do you refer to embedded Secure Element, some kind of TPM like chip?
> If so, OP-TEE does not yet provide such support but contributions are welcome :)
> 
> As for OP-TEE documentation, see http://optee.readthedocs.io.

yes ，i will do some research .
