### ISSUE TITLE
How are TAs loaded under the hood?

### ISSUE THREAD

**Issue by xiangmingyuan** [OP-TEE/optee_os#4062]
Dear OPTEE maintainer group,

I'm working on a project with OPTEE. I need to compile and sign my own TA on one device and run that TA on another board. I read [this part](https://optee.readthedocs.io/en/latest/building/trusted_applications.html#offline-signing-of-tas) about offline signing TAs. I followed these instructions to sign a TA, and I've acquired a `<uuid>.ta`. However, I'm a little confused about how to run the `<uuid>.ta` that I signed manually on my board. How do I unpack the signed TA and run it?

Besides, I observe that there are some unsigned [example TAs](https://github.com/linaro-swg/optee_examples) in `/usr/bin/` and signed example TAs in `/lib/optee_armtz` on my board. Why do we need the unsigned example TAs? I assume we can use the signed ones to run the example TAs.

Thanks for your response,
Mingyuan

**Comment by etienne-lms** [comment]
**optee_examples** basically builds 2 binaries per example: a Linux application binary and a TA binary.
The Linux applications are stored in **/usr/bin** and the TAs in **/lib/optee_armtz/**.
Only the TAs are signed.
Using **optee_examples**, you can execute the Linux example applications from a Linux shell. It will invokes the related example TA.
By storing a signed TA in **/lib/optee_armtz/**, OP-TEE is able to find/authenticate/load it in the secure world when this TA is being invoked.

**Comment by xiangmingyuan** [comment]
Hi etienne-lms,

Thanks for your response! I'm closing this issue.

Thanks again,
Mingyuan

**Comment by xiangmingyuan** [comment]
Hi OPTEE maintainer group,

Sorry to bother you again. While I play with some TAs, I find that any Linux application can call a TA as long as it provides the correct `<uuid>` of that TA. So, I'm wondering whether this will bring some potential security problems.

For example, I have a TA that manipulates a piece of data that is stored safely in the [secure storage](https://optee.readthedocs.io/en/latest/architecture/secure_storage.html). Since any Linux application can call this TA. Malicious programs will pollute that data. 

What're your opinions on this example? Do I misinterpret how optee os works?

Thanks,
Mingyuan

**Comment by jforissier** [comment]
Hi @xiangmingyuan,

> Hi OPTEE maintainer group,
> 
> Sorry to bother you again. While I play with some TAs, I find that any Linux application can call a TA as long as it provides the correct `<uuid>` of that TA. So, I'm wondering whether this will bring some potential security problems.

It could, depending on the use case ;-)

> For example, I have a TA that manipulates a piece of data that is stored safely in the [secure storage](https://optee.readthedocs.io/en/latest/architecture/secure_storage.html). Since any Linux application can call this TA. Malicious programs will pollute that data.
> 
> What're your opinions on this example? Do I misinterpret how optee os works?

Yes, you're correct. You could perhaps address this issue by using a login method different from `TEE_LOGIN_PUBLIC`. This way you could restrict the usage of your TA from a client application running with a specific user ID or group ID.

For this you need OP-TEE 3.9.0 or later, and Linux kernel 5.8 or later (the particular commit is [e33bcbab16d1](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e33bcbab16d1) ("tee: add support for session's client UUID generation")).
Please check the test case in https://github.com/OP-TEE/optee_test/pull/406 for how this can be used.

**Comment by xiangmingyuan** [comment]
Hi @jforissier ,

Thanks for your clarification! I'll try this feature.

Thanks,
Mingyuan
