### ISSUE TITLE
How to use hardware crypt driver to replace default libtomcrypt?

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#4068]
Hi, our platform want to use hardware to implement crypt related operations. The default crypt lib of optee is tomcrypt, and we currently hacked the tee_ltc_reg_alg function, using our "se_aes_desc" to replace default "aes_desc".

```
155 static void tee_ltc_reg_algs(void)
156 {
157
158 #if defined(CFG_ASR_SECENG)
159 >-------register_cipher(&se_aes_desc);
160 #else
161 >-------register_cipher(&aes_desc);
162 #endif
       ...
      }
```

Is there a more decent way to do this without changing the tomcrpyt open source code? It seems for the hash, opteeos current provides drvcrypt_register function to replace libtomcrypt's default implementation. But for other algorithms like AES, there's no such way to hook?  Thanks in advance for your suggestions.

**Comment by Emantor** [comment]
On latest OP-TEE you should use the generic crypto driver interface, found at `core/drivers/crypto/crypto_api`, take a look at the CAAM driver as an example.

**Comment by tiger20081015** [comment]
@Emantor, Thanks! My optee version on hand is a bit old so I didn't notice the latest version has already implemented the hooks for other algorithms. No more questions.
