### ISSUE TITLE
Credential Management by OP-TEE

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#4076]
I wanted to know how does TA verify the credentials of the client in the rich OS (linux users and groups) that has requested for the session?

What are TEE_LOGIN_USER, TEE_LOGIN_GROUP, TEE_LOGIN_PUBLIC in the above context?

**Comment by jenswi-linaro** [comment]
That TA or OP-TEE cannot, instead they have to rely on the Linux kernel. That means that it cannot be trusted more than you trust the Linux kernel in this context.

For the kernel part it was recently added in the patches
https://github.com/torvalds/linux/commit/c5b4312bea5d ("tee: optee: Add support for session login client UUID generation")
https://github.com/torvalds/linux/commit/e33bcbab16d1 ("tee: add support for session's client UUID generation")

**Comment by jforissier** [comment]
Let me add that the TA can obtain the client UUID by calling `TEE_GetPropertyAsIdentity(TEE_PROPSET_CURRENT_CLIENT, ""gpd.client.identity"", &identity);`. Please refer to `xtest` 1027 and 1028 for examples of how to check for a specific user or group id. Note that in `xtest` most of the verification work is done in the client application, but in a real world scenario you would likely check everything inside the TA.

**Comment by saddy-muchu** [comment]
Does this mean that the client UUID has inherent information of all the credentials of the client application? which is later verified by the linux kernel and finally passed on to OP-TEE and then to the TA?

**Comment by jforissier** [comment]
@saddy-muchu yes

**Comment by saddy-muchu** [comment]
OK.
I got a little confused looking at the structure of TEEC_UUID from the client spec
