### ISSUE TITLE
RPMB storage corruption with incorrect head.attr_size

### ISSUE THREAD

**Issue by lucy496** [OP-TEE/optee_os#4077]
With Optee 3.5.0 with CFG_RPMB_FS=y (real eMMC device) and CFG_REE_FS=y configs enabled, from tee_svc_storage_read_head(), head is getting updated. The output of head.attr_size return with some garbage value, as resulting in Object corrupt.

File: core/tee/tee_svc_storage.c
 ```
/* read head */
        bytes = sizeof(struct tee_svc_storage_head);
        res = fops->read(o->fh, 0, &head, &bytes);
        if (res != TEE_SUCCESS) {
                if (res == TEE_ERROR_CORRUPT_OBJECT)
                        EMSG("Head corrupt");
                goto exit;
        }

        if (ADD_OVERFLOW(sizeof(head), head.attr_size, &tmp)) {
                res = TEE_ERROR_OVERFLOW;
                goto exit;
        }
        MSG("tmp = %u, sizeof(head) = %u,  head.attr_size = %u", tmp, sizeof(head),  head.attr_size);
        if (tmp > size) {
                res = TEE_ERROR_CORRUPT_OBJECT; // error returned from here.
                goto exit;
        }
```
Logs: 
tmp = 394433625, sizeof(head) = 24,  head.attr_size = 394433601
syscall_storage_obj_open:314 Object corrupt

I have 5 objects in RPMB and with multiple retry the corruption is observed on different objects, it is not always consistent with same object.
Please help in identifying why the head.attr_size going wrong.

**Comment by Emantor** [comment]
This was probably fixed by ced8449a7b86edba37977de3bae83b783db0b36c.
