### ISSUE TITLE
Disable PL310 before jumping to Linux?

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#4079]
All,

Could we switch to disable PL310 here before jumping to non-secure world? And let non-secure world to enable L2 cache?

"
590 #ifdef CFG_PL310_LOCKED
591 #ifdef CFG_PL310_SIP_PROTOCOL
592 #error "CFG_PL310_LOCKED must not be defined when CFG_PL310_SIP_PROTOCOL=y"
593 #endif
594         /* lock/invalidate all lines: pl310 behaves as if disable */
595         bl      pl310_base
596         bl      arm_cl2_lockallways
597         bl      pl310_base
598         bl      arm_cl2_cleaninvbyway
599 #endif
"

**Comment by jenswi-linaro** [comment]
Are you reenabling PL310 via this SIP protocol? I'm not sure I fully understand what you're proposing, could you make a pull request instead?
It looks like this could be fine too though. @etienne-lms, what do you think?

**Comment by Emantor** [comment]
According to the [PL310 TRM](https://developer.arm.com/documentation/ddi0246/a/functional-overview/trustzone-support-in-the-cache-controller), the control register to enable PL2 can only be written with an access tagged as secure. AFAICS this would require a call from the kernel into OP-TEE to reenable the PL310.

**Comment by etienne-lms** [comment]
Agree that PL310 enable/disable must be done on secure side and that Linux expects to be booted cache off. To prevent need for a specific service, optee generic boot leaves the PL310 enable/line-locked/invalidated and Linux is expected to unlock all lines when booting so to get a functional L2 cache. Looking in Linux cache-lx20.c (it's been  a while) I saw [such reference](https://elixir.bootlin.com/linux/v5.8/source/arch/arm/mm/cache-l2x0.c#L645) but the generic sequence does not unlock the line (on when the [cache was off](https://elixir.bootlin.com/linux/v5.8/source/arch/arm/mm/cache-l2x0.c#L866)).

I agree OP-TEE could be change to disable (or not enable) PL310 during its boot and enable it only upon a request from non-secure world.
With a boot sequence like " ...-> optee -> u-boot -> linux", what if u-boot also expects PL310 support?

**Comment by sdininno** [comment]
I am not really in favor of allowing Linux (or non secure world ) to have a control on when the L2 Cache can be enabled.
Currently on i.MX we have added code to unlock the ways in the l2x driver , this Change however has been rejected by Russell some time ago.

i think the proper design is for code running on non-secure world not to expect outer cache to be off by default.
it has been a while but if i remember correctly on i.MX (cortex A9 based) the issue with PL310 is not really with Linux.
the OS itself cope well with PL310 being enabled (and actually the l2x driver is designed to check if the controller is already enabled).
The issue we have on i.MX is with the decompressor that maps the memory with outer cache attribute enable when it has no routine to perform outer cache management.

**Comment by MrVan** [comment]
@sdininno The linux side will use write_sec to trap to OP-TEE to handle L2 enable. This is to drop the lock/unlock and make every part upstream.
