### ISSUE TITLE
TEE_MACInit panics when using des3 112bit key

### ISSUE THREAD

**Issue by seungeun2** [OP-TEE/optee_os#408]
Hi,

Has anybody tested DES3 using 112bit key?

I have tested on juno but it doesn't seem to work.

To be specific, I was testing MAC API and TEE_MACInit panicked when using des3 112bit key.

I tried to find out what went wrong and I found that DES3 only allows a key of length, 24 bytes (24 * 7 = 168 bits) rejecting any other key length.

in core/lib/libtomcrypt/src/ciphers/des.c

int des3_setup(const unsigned char *key, int keylen, int num_rounds, symmetric_key *skey)
{

...

    if (keylen != 24) {
        return CRYPT_INVALID_KEYSIZE;
    }

...

}

My question here is..
is this a bug  or 112 bit key is not supported just yet?

**Comment by pascal-brand-st-dev** [comment]
You are right. MAC_DES3 are not tested with 112bits key. It looks like we have an issue in there. I'll update the code with this.

Note that cipher are correctly tested with DES3 112bits key (let me know if you face anything wrong with it).

I'll propose a patch early next week. Thanks to have pointed it.

**Comment by pascal-brand-st-dev** [comment]
@seungeun2 A fix is proposed in #410.

**Comment by seungeun2** [comment]
@pascal-brand-st 
I tested symmetric cipher with DES3 112 bit key and it seems to work properly.
Thanks!
