### ISSUE TITLE
Fail to sign TAs offline

### ISSUE THREAD

**Issue by xiangmingyuan** [OP-TEE/optee_os#4081]
Hi OPTEE group,

Sorry for the long post, I'll try to condense my problem and how I try to solve it (unsuccessfully).

When I try to sign TAs offline, following the instructions from [tutorial in the optee doc](https://optee.readthedocs.io/en/latest/building/trusted_applications.html#offline-signing-of-tas), I got the following error:
```
Traceback (most recent call last):
  File "sign_encrypt.py", line 258, in <module>
    main()
  File "sign_encrypt.py", line 254, in main
    }.get(args.command, 'sign_encrypt_ta')()
  File "sign_encrypt.py", line 241, in stitch_ta
    if verifier.verify(h, sig):
  File "/usr/lib/python3/dist-packages/Cryptodome/Signature/pss.py", line 160, in verify
    _EMSA_PSS_VERIFY(msg_hash, em, modBits-1, mgf, sLen)
  File "/usr/lib/python3/dist-packages/Cryptodome/Signature/pss.py", line 311, in _EMSA_PSS_VERIFY
    raise ValueError("Incorrect signature")
ValueError: Incorrect signature
```
After I received this error, I went a little deeper and tried to solve this problem. At first, I thought this was due to different signature schemes, pkcs1 and pss. In particular, the `sign_encrypt.py` script uses pss to sign and verify, but in the tutorial, it tells me to sign the digest with pkcs1 padding (the second step). However, I still cannot offline sign the TAs, even if I unify the signature schemes. I'll list the different results that I got in the following when I use pss or pkcs1 to sign.

### If I use pkcs1 scheme to sign and verify in the `sign_encrypt.py`
I have to replace the `pss`, [here](https://github.com/OP-TEE/optee_os/blob/master/scripts/sign_encrypt.py#L239), with `pkcs1_15` (and import it as well). After that I can get rid of the `ValueError("Incorrect signature")` exception, but my console prints `ERROR:sign_encrypt.py:Verification failed, ignoring given signature.`. This is because the [verify() function](https://github.com/OP-TEE/optee_os/blob/master/scripts/sign_encrypt.py#L240) returns a `None`. I read the [source file](https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Signature/pkcs1_15.py#L86) of the `verify()` function, and I find that there is no return for this function. So, I suppose if the `verify()` doesn't raise any exceptions, the signature is signed correctly. Besides, I check the signature using openssl as following:
```
$ base64 --decode 8aaaf200-2450-11e4-abe2-0002a5d5c51b.sig > sigfile
$ base64 --decode 8aaaf200-2450-11e4-abe2-0002a5d5c51b.dig | \
$        openssl pkeyutl -verify -inkey /home/mingyuan/Documents/optee/optee_os/keys/default_ta.pem \
$        -pkeyopt digest:sha256 -pkeyopt rsa_padding_mode:pkcs1 -sigfile sigfile
```
I receive the `Signature Verified Successfully` from my console. Hence, I bypass the [if statement](https://github.com/OP-TEE/optee_os/blob/master/scripts/sign_encrypt.py#L240-L242) to write the `<uuid>.ta` file. However, I encounter the `TEE_ERROR_SECURITY` when I run this ta. See below:
```
# optee_example_hello_world
optee_example_hello_world: TEEC_Opensession failed with code 0xffff000f origin 0x3
```
I think this is because the optee os cannot verify the signature as the secure world console prints:
```
D/TC:? 0 system_open_ta_binary:257 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:? 0 system_open_ta_binary:260 res=0xffff0008
D/TC:? 0 system_open_ta_binary:257 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:? 0 system_open_ta_binary:260 res=0xffff000f
D/TC:? 0 tee_ta_invoke_command:788 Error: ffff000f of 4
E/LD:  init_elf:438 sys_open_ta_bin(8aaaf200-2450-11e4-abe2-0002a5d5c51b)
E/TC:? 0 init_with_ldelf:233 ldelf failed with res: 0xffff000f
D/TC:? 0 tee_ta_close_session:501 csess 0xe1c84cd0 id 1
D/TC:? 0 tee_ta_close_session:520 Destroy session
D/TC:? 0 destroy_context:299 Destroy TA ctx (0xe1c84c88)
D/TC:? 0 tee_ta_close_session:501 csess 0xe1c84820 id 1
D/TC:? 0 tee_ta_close_session:520 Destroy session
E/TC:? 0 tee_ta_open_session:743 Failed. Return error 0xffff000f
```

### If I change the padding scheme to pss when signing the TA
I have to replace the `-pkeyopt rsa_padding_mode:pkcs1` with `-pkeyopt rsa_padding_mode:pss` when I sign the digest with openssl. This time, I get the `ValueError("Incorrect signature")` exception as the beginning, though the openssl still returns a `Signature Verified Successfully` when I verify the signature as above. Also, If I bypass the if statement as above, I receive the same `TEE_ERROR_SECURITY` error.

BTW, I list the commands that I use for offline signing TAs here for reference.
```
$ python3 sign_encrypt.py digest --key /home/mingyuan/Documents/optee/optee_os/keys/default_ta.pem \
$        --uuid 8aaaf200-2450-11e4-abe2-0002a5d5c51b --in ~/Documents/optee/out-br/build/optee_examples_ext-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.stripped.elf
$ base64 --decode 8aaaf200-2450-11e4-abe2-0002a5d5c51b.dig | \
$        openssl pkeyutl -sign -inkey /home/mingyuan/Documents/optee/optee_os/keys/default_ta.pem \
$        -pkeyopt digest:sha256 -pkeyopt rsa_padding_mode:pkcs1 | \
$        base64 > 8aaaf200-2450-11e4-abe2-0002a5d5c51b.sig
$ python3 sign_encrypt.py stitch --key /home/mingyuan/Documents//optee/optee_os/keys/default_ta.pem \
$        --uuid 8aaaf200-2450-11e4-abe2-0002a5d5c51b --in ~/Documents/optee/out-br/build/optee_examples_ext-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.stripped.elf
```

Would you mind helping me with this problem? Is this a bug, or I didn't use the correct way to sign TAs offline.

Thanks,
Mingyuan

**Comment by jforissier** [comment]
Hi @xiangmingyuan,

Thanks for the detailed description, I am not familiar with the offline signing process but CC @wamserma who contributed this code.

**Comment by wamserma** [comment]
Hi @xiangmingyuan,

thanks for reporting this. Looking at the [history of `sign_encrypt.py`](https://github.com/OP-TEE/optee_os/commit/ababd72d2fd76cb2ded8e202b49db28d6545f6eb#diff-a36c76de917d1a5a06e2a4f6d9b3c3a2) @jenswi-linaro changed the signing scheme from PKCS#1.5 to PSS (sidenote: we could use either: https://eprint.iacr.org/2018/855) but the documentation has not been updated.

Looking at commit 2139aa8c314f8aeb3c87203abb88741844332f28, OP-TEE requires a salt length equal to the hash length for PSS, so you should also use settings like `-pkeyopt rsa_pss_saltlen:digest` and `-pkeyopt rsa_mgf1_md:sha256` when signing with OpenSSL. Looking at the code, OP-TEE still should accept TAs with PKCS#1.5 signatures, so you can also try the [old signing script](https://github.com/OP-TEE/optee_os/blob/2de17fda55d2d902123e25b1036cd6ae00b7ea77/scripts/sign_encrypt.py).

Lastly: ensure that compiling you public key into OP-TEE worked properly.

**Comment by xiangmingyuan** [comment]
Hi @wamserma ,

Thanks for your help! The offline signing works after adding `-pkeyopt rsa_pss_saltlen:digest` and `-pkeyopt rsa_mgf1_md:sha256` while signing with openssl.

However, there is a small bug in the `sign_encrypt.py` script (as I mentioned above). When I use the `stitch` flag, the `sign_encrypt.py` script will raise an error that says `ERROR:sign_encrypt.py:Verification failed, ignoring given signature` even if the signature is correct. As far as I understand, the [`verify()` function](https://github.com/OP-TEE/optee_os/blob/master/scripts/sign_encrypt.py#L240) returns a `None` when the signature is correct. ([source file from the pss module](https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Signature/pss.py#L116)) So, we can fix this by removing the `if` statement. The `verify()` function will raise an exception when the signature is incorrect.

I can submit a commit to fix this if you think what I observe is correct.

Thanks,
Mingyuan

**Comment by wamserma** [comment]
Hi @xiangmingyuan,

a fix/PR is highly appreciated. To keep the intentions of the script, it#s probably best to just convert the `if/else` into a  `try/except ValueError`. Bonus points if the stitch function would accept both, PSS and PKCS#1.5 signatures.

I will take care of the documentation update.

**Comment by xiangmingyuan** [comment]
Hi @wamserma ,

I've submitted a fix. It will be appreciated if you can help review my code.

Thanks,
Mingyuan
