### ISSUE TITLE
[rpc_io_i2c] This patch does need to modify linux dirver code ?

### ISSUE THREAD

**Issue by sunnybird** [OP-TEE/optee_os#4097]
I read the [rpc_io_i2c.c](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/rpc_io_i2c.c) , I want to know the linux dirver how to handle **OPTEE_RPC_CMD_I2C_TRANSFER**

**Comment by etienne-lms** [comment]
See https://lkml.org/lkml/2020/8/14/256.
See also related fixup https://github.com/OP-TEE/optee_os/pull/4085.
