### ISSUE TITLE
Hikey960 ctest failed

### ISSUE THREAD

**Issue by mofanv** [OP-TEE/optee_os#4104]
Hi,

I face a weird problem after flashing Hikey960 with buildroot and optee based on https://optee.readthedocs.io/en/latest/building/gits/build.html#get-and-build-the-solution. 

Run `xtest` will lead to:
```
# xtest
Run test suite with level=0

TEE test application started with device [(null)]
######################################################
#
# regression
#
######################################################
 
* regression_1001 Core self tests
E/TC:6 0 std_smc_entry:186 Bad arg address 0x216487000
regression_1000.c:241: res has an unexpected value: 0xffff000e = TEEC_ERROR_COMMUNICATION, expected 0x0 = TEEC_SUCCESS
Segmentation fault

```

Run `ps aux | grep tee-supplicant`:
```
  251 tee      /usr/sbin/tee-supplicant -d /dev/teepriv0
  279 root     grep tee-supplicant
```

Run `tee-supplicant -d`:
```
ERR [280] TSUP:main:704: failed to find an OP-TEE supplicant device
```

I have tried several branches from `3.5.0` to `3.9.0`, all failed with same errors. Both `make flash` and `make recovery` are the same. Before this, I have aosp+optee on this hikey960 and it works very well (And before aosp+optee, I have buildroot+optee and it works).

Do you have any clues?  thanks in advance.  

Best,
Fan

**Comment by jenswi-linaro** [comment]
This is likely due to the kernel sharing memory with OP-TEE which OP-TEE isn't aware of.

**Comment by mofanv** [comment]
@jenswi-linaro , thanks for reminding. Just figure it out, the bad arg address is a old problem with setting the `DRAM`. In `optee_os/core/arch/arm/plat-hikey/conf.mk`, simply changing `CFG_DRAM_SIZE_GB ?= 3` to `CFG_DRAM_SIZE_GB ?= 4` fix my problem.
