### ISSUE TITLE
rpmb: Wrong block index check in tee_rpmb_req_pack() ?

### ISSUE THREAD

**Issue by snst** [OP-TEE/optee_os#4113]
Regarding https://github.com/OP-TEE/optee_os/blob/be041efc5f7f866089c0eb4f019661aefdcb4ff9/core/tee/tee_rpmb_fs.c#L574

I think `rpmb_ctx->max_blk_idx `contains the index of the last block which can be accessed.
So the following check will fail if I write to the last block?

>			if ((*rawdata->blk_idx + nbr_frms) >
>			    rpmb_ctx->max_blk_idx) {
>				res = TEE_ERROR_GENERIC;
>				goto func_exit;
>			}

Shouldn't it be like this?

>			if ((*rawdata->blk_idx + nbr_frms - 1) >
>			    rpmb_ctx->max_blk_idx) {
>				res = TEE_ERROR_GENERIC;
>				goto func_exit;
>			}

**Comment by jforissier** [comment]
Hi @snst ,

https://github.com/OP-TEE/optee_os/pull/4143
