### ISSUE TITLE
ta prebuilt

### ISSUE THREAD

**Issue by neil1899** [OP-TEE/optee_os#412]
hi，all
I found when i build the ta, it will prebuild the bin of faked_armv7_uta_signed_header.bin.
i don't know what the bin's role?

I found when the optee_os load ta from rpc, it will analyze the head of *.ta, it contains two types of data structure. one is kta_signed_header_t and the other is ta_head_t. 

which the bin matchs the data structure?

thanks so much!

**Comment by neil1899** [comment]
@jenswi-linaro can u help me?

**Comment by pascal-brand-st-dev** [comment]
The .ta file is made of
- a fake .bin, used to check the TA (hash,...). It corresponds to the `kta_signed_header_t` type. This is an attempt of TA signature checking. Note that this is under rework right now (see #396)
- followed by the code of the TA. It corresponds to the `ta_head_t` type

**Comment by neil1899** [comment]
Dear @pascal-brand-st-dev:

if it is possible, can you share the codes which generate the fake*.bin with me? 

I can't find it under the optee_os.

thanks so much!

**Comment by pascal-brand-st-dev** [comment]
You can find it in https://github.com/OP-TEE/optee_test/blob/master/ta/prebuilt/faked_armv7_uta_signed_header.bin

**Comment by neil1899** [comment]
Dear @pascal-brand-st-dev 
thanks for your answer. but I don't know the content of the bin?

**Comment by neil1899** [comment]
maybe，I have fix my problem.

thanks so much!
