### ISSUE TITLE
QEMU CFG_ULIBS_SHARED=y: alloc_pgt:147 5 page tables not available

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#4128]
optee_os 3.10.0-77-g3b354b19, QEMU.

```
$ make CFG_ULIBS_SHARED=y run

# xtest 1010
...
o regression_1010.10 Invalid memory access 5 with 1024 bytes memref
regression_1000.c:500: TEEC_InvokeCommand(&session, 10, &op, &ret_orig) has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0xffff3024 = TEE_ERROR_TARGET_DEAD
regression_1000.c:505: TEEC_InvokeCommand(&session, 10, &op, &ret_orig) has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0xffff3024 = TEE_ERROR_TARGET_DEAD
  regression_1010.10 FAILED

E/TC:? 0 alloc_pgt:147 5 page tables not available
E/TC:? 0 alloc_pgt:147 5 page tables not available
```

PGT_CACHE_SIZE (= 4 because CFG_NUM_THREADS=2) seems insufficient. Setting it to 5 avoids the issue, as well as:
```
$ make CFG_ULIBS_SHARED=y CFG_NUM_THREADS=1  # OK
$ make CFG_ULIBS_SHARED=y CFG_NUM_THREADS=3  # OK
```

**Comment by jenswi-linaro** [comment]
`5` is an unfortunate number if LPAE isn't enabled. You should probably use something like
``` C
ROUNDUP(5, PGT_NUM_PGT_PER_PAGE)
```
instead. I suspect that the increase isn't needed with LPAE. Setting this number isn't easy as it depends on many factors. To name a few, LPAE, TA_ASLR, size of TA, size of memrefs passed to TA, and now apparently CFG_ULIBS_SHARED too. The reason I choose something based on the number of threads is that I took that as an indicator on how large the system might be.

**Comment by jforissier** [comment]
Correct, there is no issue with LPAE (QEMUv8). Thanks for the suggestion.

**Comment by jforissier** [comment]
> ```c
> ROUNDUP(5, PGT_NUM_PGT_PER_PAGE)
> ```

Hmmm... that would always be equal to 5 since `PGT_NUM_PGT_PER_PAGE` is either 1 (LPAE) or 4 (non-LPAE).
I suppose you meant `ROUNDUP(CFG_NUM_THREADS * 2, 5)`?

I will create a PR soon.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/4129
