### ISSUE TITLE
can not start the normal world linux

### ISSUE THREAD

**Issue by nicolaspippo** [OP-TEE/optee_os#414]
hi,
I tried to build OP-TEE using FVP,I run the setup_fvp_optee.sh,and it seems everything should have been cloned and built,it displayed OP-TEE and FVP setup completed,but when I run run_foundation.sh,in FVP terminal_0,it displayed:

ERROR : Did not get the Device tree blob(not found),
Linux boot loader error(not found)"

could anyone tell me what I may do wrong ,or give me some hints that I can check out.
thank you.

**Comment by jenswi-linaro** [comment]
Do you have a `fdt.dtb` in the directory from where you're running the Foundation Model?

**Comment by haswell123** [comment]
Maybe you need to delete them and try it again.

**Comment by nicolaspippo** [comment]
yes,I have it in Foundation_Platformpkg directory,it link to optee_linuxdriver/fdts/fvp-foundation-gicv2-psci.dtb(6.8KB),is that correct?
I have tried several times,and every time the result are the same.

**Comment by haswell123** [comment]
yes，the link address is correct.maybe this problem is not at here. may i know your linux distribution?

**Comment by nicolaspippo** [comment]
ubuntu 14.04 LTS Desktop 64bit
by the way,I delete the fdt.dtb,the result is the same.Is fdt.dtb doesn't work?

**Comment by haswell123** [comment]
ok,i also use ubuntu .but i did not meet such a problem.the fast models i used is FM000-KT-00035-r9p2-28rel0.tgz  ,.hope you can  resolve this annoying problem.

**Comment by nicolaspippo** [comment]
i used the same  fast models,
i try another way to find out what cause the problem ,
thank you for your help.

**Comment by haswell123** [comment]
great .congratulations！

**Comment by nicolaspippo** [comment]
sorry for my poor English,
i will try  another way to solve the problem,
i have not solve it now ....

**Comment by nicolaspippo** [comment]
hi,haswell123,
could you send me the setup_fvp_optee.sh you successed and tell the ubuntu version you use?
my email : 497299323@qq.com
thank you .

**Comment by nicolaspippo** [comment]
ok,I solved this problem temporary,
it could not find fdt.dtb automatically,but you can  add  fdt.dtb path in boot manager,then it can start.
but i still don't kown why it can not find fdt.dtb automatically,
could anyone tell me why ?

**Comment by jbech-linaro** [comment]
@nicolaspippo fdt.dtb should be put in the `Foundation_Platformpkg` folder as a symlink to the correct device tree blob. On my FVP setup it's like this:

```
jbech@salmon ~/devel/fvp_optee/Foundation_Platformpkg
$ ls -al fdt.dtb 
lrwxrwxrwx 1 jbech jbech 80 Jul  2 15:26 fdt.dtb -> /home/jbech/devel/fvp_optee/optee_linuxdriver/fdts/fvp-foundation-gicv2-psci.dtb
```

Please check if that solves the problem and let us know if we can close this issue or not.

**Comment by pascal-brand-st-dev** [comment]
@nicolaspippo  let me know if I can close the issue. Without any answer, I'll close the it.

**Comment by nicolaspippo** [comment]
root@ubuntu:~/devel/fvp_optee/Foundation_Platformpkg# ls -al fdt.dtb
lrwxrwxrwx 1 root root 74 Jul 27 15:11 fdt.dtb -> /root/devel/fvp_optee/optee_linuxdriver/fdts/fvp-foundation-gicv2-psci.dtb

this is mine,i think it's right, i don't know why it could not find fdt.dtb automatically,but i can add fdt.dtb path in boot manager,and  start the linux
you can close the issue now
