### ISSUE TITLE
How to use 8MG shared memory on rpi3

### ISSUE THREAD

**Issue by Hanseungkyun** [OP-TEE/optee_os#4140]
How to use 8MB or more shared memory?
or how to use dynamic shared memory(for large size shared memory)?
From what I understand, dynamic shared memory allocates heap from TEE region to malloc and registers that region as shared memory. But I don't know how to use it and I can't find an example either.

-----------------------------------------------
P.S
The optee version I use is out of date and doesn't support dynamic SHM. I solved the problem in another way. Thank you.

**Comment by ruchi393** [comment]
For dynamic shared memory, the support is enabled via CFG_CORE_DYN_SHM.  You can use register_dynamic_shm() to  define an address range that can be used as shared memory.
