### ISSUE TITLE
RSA encryption TA in rpi3

### ISSUE THREAD

**Issue by Xinyao90** [OP-TEE/optee_os#4145]
Hi,

I'm trying to cross-compile the provided code from ubuntu to rpi3 with reference from [https://github.com/OP-TEE/optee_os/issues/1749](url) and [https://github.com/OP-TEE/optee_os/issues/1745](url), the provided code by author @ursus-the-bear [RSA.zip](https://github.com/OP-TEE/optee_os/files/5369791/RSA.zip) .

I can compile and run the code without OPTEE in my local ubuntu machine with no problem for function local_encrypt_and_decrypt () in main.c. However, if I compile it with commend $ make -j `nproc` under directory ~/optee-project/build, there is error message show as below:

/home/heidi/optee-project/toolchains/aarch64/bin/../lib/gcc/aarch64-linux-gnu/8.3.0/../../../../aarch64-linux-gnu/bin/ld: CMakeFiles/optee_example_RSA.dir/host/main.c.o: in function `main':
main.c:[ 57%] Built target optee_example_acipher
(.text.startup+0x14): undefined reference to `local_encrypt_and_decrypt'
collect2: error: ld returned 1 exit status

In addition to deleting build.sh, I've also modified the RSA/host/Makefile according to my local installed openssl library as:

CC      = $(CROSS_COMPILE)gcc
LD      = $(CROSS_COMPILE)ld
AR      = $(CROSS_COMPILE)ar
NM      = $(CROSS_COMPILE)nm
OBJCOPY = $(CROSS_COMPILE)objcopy
OBJDUMP = $(CROSS_COMPILE)objdump
READELF = $(CROSS_COMPILE)readelf

OBJS = main.o \
       test.o \
       crypto.o

CFLAGS += -Wall -I../ta -I$(TEEC_EXPORT)/include -I./include -I/usr/include/openssl/

LDADD += -lteec -L$(TEEC_EXPORT)/lib
LDFLAGS += /home/heidi/openssl-1.0.1g/libcrypto.a

BINARY=optee_example_rsa

.PHONY: all
all: $(BINARY)

$(BINARY): $(OBJS)
	$(CC) $(LDADD) -o $@ $< test.o crypto.o $(LDFLAGS) -ldl

.PHONY: clean
clean:

Thanks a lot,
Heidi

**Comment by Xinyao90** [comment]
I've figured out instead of Makefile, CMakeLists.txt is the file I should edit for cross-compilation. 
However, I got the error as below. Still need some help here.

/home/heidi/optee-project/toolchains/aarch64/bin/../lib/gcc/aarch64-linux-gnu/8.3.0/../../../../aarch64-linux-gnu/bin/ld: /home/heidi/openssl-1.0.1g/libcrypto.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status

This is the CMakeLists.txt for my RSA application: 

`project (optee_example_RSA C)

set (SRC host/main.c)

add_executable (${PROJECT_NAME} ${SRC})

target_include_directories(${PROJECT_NAME}
			   PRIVATE ta/include
			   PRIVATE include
			   PRIVATE /home/heidi/openssl-1.0.1g/include)

target_link_libraries (${PROJECT_NAME} 
				PRIVATE teec 
				PRIVATE /home/heidi/openssl-1.0.1g/libcrypto.a)

install (TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_BINDIR})`

**Comment by jforissier** [comment]
What architecture is your `libcrypto.a`? It needs to be Aarch64.

**Comment by Xinyao90** [comment]
@jforissier Yes, set the openssl to be Aarch64 solves the problem. This really made my day. Thanx!
