### ISSUE TITLE
ASLR code question

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#4151]
I don't understand these lines: https://github.com/OP-TEE/optee_os/blob/3.10.0/core/arch/arm/kernel/entry_a32.S#L505-L511

I understand that this code does `cached_mem_end = &cached_mem_end + load_offset` but I think it should do `cached_mem_end += load_offset`. Is this lacking an indirection: `ldr r2, [r2]`?

**Comment by jenswi-linaro** [comment]
If you look at the disassembled code you see that it's really:
``` C
ldr     r2, [pc, #88]
add     r2, r2, r0
str     r2, [pc, #80]
```
so there's no indirection missing.

**Comment by jforissier** [comment]
Right, I am clearly mixing up `label` and `=label`. Thanks for the clarification.
