### ISSUE TITLE
TEEC_RequestCancellation

### ISSUE THREAD

**Issue by Master-Chi** [OP-TEE/optee_os#4157]
Hi Optee community,
    I am using xtest ion my board, case 1009.3(TA waits 2s and using TEEC_RequestCancellation in 500ms to cancel TA) failed.
TEEC_RequestCancellation didn't work, task still finished with TEEC_SUCCESS. Is there any configuration may masks the action? How should I debug the peoblem?
     Sorry for bothering

**Comment by jenswi-linaro** [comment]
That test case creates another thread which is supposed to cancel the invoke in the first thread. Perhaps the newly created thread doesn't execute in time? You could try to add a debug print in `entry_cancel()` in `core/arch/arm/tee/entry_std.c` to see if it's reached before or after the invoke (`entry_invoke_command()`) returns.

**Comment by Master-Chi** [comment]
thx, problem solved. CFG_NUM_THREADS were configured to 1 before.

**Comment by jforissier** [comment]
@Master-Chi are you using a linux kernel with `CONFIG_PREEMPT=y`?

**Comment by Master-Chi** [comment]
@jforissier  yes, is the configuration a problem for optee-os or optee_test?

**Comment by jforissier** [comment]
No, on the contrary I would think that `CFG_NUM_THREADS=1` should work except perhaps (not sure) when kernel preempt is disabled.
I verified that `xtest 1009` runs fine with `CFG_NUM_THREADS=1` on our QEMU setup.

**Comment by Master-Chi** [comment]
@jforissier Em...if you set CFG_TEE_CORE_NB_CORE=1 &  CFG_NUM_THREADS=1, 1009 is still work fine?

**Comment by jforissier** [comment]
Sorry I was wrong... `CFG_NUM_THREADS=1` does not work whatever the number of cores. Maybe it's expected, but it seems a bit weird to me because if the OP-TEE thread is sleeping it should be back to normal world. On the client side we always have two threads (one blocked, one cancelling). Why the cancelling thread could not re-use the OP-TEE thread and re-enter OP-TEE to signal cancelation? But I did not look at the code so there could be good reasons why things are like that.

**Comment by jenswi-linaro** [comment]
When OP-TEE waits with a thread it is suspended and cannot be re-used for anything.
Doing the kind of optimization you're suggesting sounds a bit odd especially since the cure is easy enough.

**Comment by jforissier** [comment]
@jenswi-linaro OK, re-using the thread would not make much sense indeed, the context has to be preserved somewhere.
Perhaps cancellation could be handled differently and not require a thread to begin with?

> Doing the kind of optimization you're suggesting sounds a bit odd especially since the cure is easy enough.

You're probably right :)
