### ISSUE TITLE
Before TEE OS is loaded, can we allocate memory space in TEE？

### ISSUE THREAD

**Issue by penpendandan** [OP-TEE/optee_os#4159]
Before TEE OS is loaded, can we allocate memory space in TEE？If can，how can we do it？

**Comment by penpendandan** [comment]
Before TEE OS is loaded, can we allocate memory space in TEE？If can， how can we do it？

**Comment by jenswi-linaro** [comment]
What do you mean by "allocate memory space in TEE"?
Before OP-TEE is loaded there's not much you can do with it.
