### ISSUE TITLE
Problems related to crypto_acipher_rsaes_encrypt()

### ISSUE THREAD

**Issue by xiangmingyuan** [OP-TEE/optee_os#4160]
Hi OPTEE group,

We're developing an application that needs to use the RSA encryption/decryption part from the os side, which needs to call  [crypto_acipher_rsaes_encrypt()](https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/rsa.c#L386).

From the source code of the `crypto_acipher_rsaes_encrypt()`, if we use an initialized `dst_len`, we have to call this function twice. We only obtain correct `dst_len` in the first time. See following ([github link](https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/rsa.c#L402-L407)):
```
	if (*dst_len < mod_size) {
		*dst_len = mod_size;
		res = TEE_ERROR_SHORT_BUFFER;
		goto out;
	}
	*dst_len = mod_size;
```
Why is this if statement needed? I assume we can update the `dst_len` in the first time we call 
 `crypto_acipher_rsaes_encrypt()`.

Thanks,
Mingyuan

**Comment by jforissier** [comment]
Hi @xiangmingyuan ,

`*dstlen` must be set to the size of your output buffer on entry. When the function returns it is set to the actual size of the encrypted data. Use a big enough buffer and you will not need to call the function twice.

**Comment by xiangmingyuan** [comment]
Hi @jforissier ,

Thanks for your help. So, the `dst_len` should be the size of `dst` that we allocate, right?

Mingyuan

**Comment by jforissier** [comment]
Yes, correct.

**Comment by xiangmingyuan** [comment]
Thanks for your help!
