### ISSUE TITLE
Do /dev/tee and /dev/teepriv use the same major device number?

### ISSUE THREAD

**Issue by yw-kim** [OP-TEE/optee_os#4161]
I am an engineer studying optee_os.
My name is Yaewon.

I have a question about Supplicant device node. 

Do /dev/tee and /dev/teepriv use the same major device number?

As far as I can tell, it appears to be using the same Major device number. (tee_core.c in tee linux kernel driver)

**Comment by jforissier** [comment]
Hi @yw-kim,

The answer is yes.
```
$ ls -l /dev/tee*
crw-rw----    1 root     teeclnt   247,   0 Oct 15 11:59 /dev/tee0
crw-rw----    1 root     tee       247,  16 Oct 15 11:59 /dev/teepriv0
```

**Comment by yw-kim** [comment]
Thank you! Jerome.
