### ISSUE TITLE
build op-tee for rk3328

### ISSUE THREAD

**Issue by Dvergatal** [OP-TEE/optee_os#4164]
Hi there, i was trying to build my own op-tee os on rk3328 and according to #2994 ElonZhang0328 comment, for that i need to add a platform define called like rk3328 and implement the platform related code referring to rk3328 TRM. The platform define was easy to add, but still i don't know if i have got it correctly written:
```mk
ifeq ($(PLATFORM_FLAVOR),rk3328)
include core/arch/arm/cpu/cortex-armv8-0.mk
$(call force,CFG_TEE_CORE_NB_CORE,4)

CFG_TZDRAM_START ?= 0x30000000
CFG_TZDRAM_SIZE  ?= 0x02000000
CFG_SHMEM_START  ?= 0x32000000
CFG_SHMEM_SIZE   ?= 0x00400000
endif
```

According to [http://opensource.rock-chips.com/images/9/97/Rockchip_RK3328TRM_V1.1-Part1-20170321.pdf](url) this SoC supports GIC400 which is GICv2 and op-tee by default uses it. And what about TZDRAM and SHMEM? I could not find it in the pdf file.

The platform related code is a more complicated stuff. What i saw in op-tee_os there are files in plat-rockchip directory. I suppouse that i need to add platform_rk3328.c with these two methods register_phys_mem_pgdir and platform_secure_ddr_region. But i don't know how. Can anybody help me writting it or point me to what i should look for in the TRM document?

**Comment by jforissier** [comment]
Hi @Dvergatal ,

TZDRAM and SHMEM are OP-TEE specific things, they depend on the layout of the physical address space that you want to use in your system.

TZDRAM is secure memory, it should normally be protected from Normal World access by a memory firewall. `plat-rockchip` has `platform_secure_ddr_region()` for this, you need to implement it based on the hardware. But it should be OK to ignore this function at first.

SHMEM s a fixed (reserved) range of memory shared between Normal World and Secure World. It is not mandatory to define this range; instead you can configure OP-TEE to always dynamically map Normal World memory buffers by setting `CFG_CORE_RESERVED_SHM=n`.

So you have some flexibility when choosing the values. But you need to take into account other components such as bootloader, TF-A, UEFI, Linux kernel. OP-TEE can create reserved-memory nodes in a DT for Linux to use.

**Comment by Dvergatal** [comment]
So i need to have some technical informations from the hardware producer to implement this function?

**Comment by jforissier** [comment]
For `platform_secure_ddr_region()`, I think so, yes.

**Comment by Dvergatal** [comment]
Yes that is what i was thinking about. But i haven't found anything about this secure region in the rockchip 3328 technical documentation...

**Comment by Emantor** [comment]
AFAIK rockchip requires an NDA for the security reference manual (or however its called in their case), maybe @mmind has more information whether there are docs at all.

**Comment by jforissier** [comment]
There is apparently some relevant code in Trusted Firmware, perhaps it can help: https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/tree/plat/rockchip/rk3328/drivers/soc/soc.c

**Comment by Dvergatal** [comment]
Thanks a lot guys:] Currently i have compiled it for rk3399 because this board we have also. More over i discovered that it needs at least gcc-7. Now i was thinking about that what ElonZhang0328 said in #4115 : 

> 
> 
> Hi @jonsmirl
V1.1.0 OP-TEE component are used on the RK3328 board but V3.3.0 on RK1808 board. So if you want to run OP-TEE V2.0 on RK3328(as https://github.com/etienne-lms/optee_os/tree/sks/ta/secure_key_services is unavailabe on V1.1.0 OP-TEE), some porting work should be done as below:
1.Rebuid bl32.bin using upstream optee_os and pack the binary to trust.img as @JosephChen2017 described. And i think there is no need to rebuild bl31.elf.
2.Enable CONFIG_TEE and CONFIG_OPTEE in linux kernel to enable the new version optee linux driver.
3.Build the upstream optee_client to get tee-supplicant daemon and libteec.so. And build optee_test to get the test CA/TA and build you own CA/TA.

I can't see bl32.bin anywhere. What i see is 
''' bash
~/linux-sdk/optee_os# find out -name "*.bin"
out/arm/core/tee-pageable_v2.bin
out/arm/core/tee-pager_v2.bin
out/arm/core/tee.bin
out/arm/core/tee-header_v2.bin
'''
and i dunno which one should i use? More over i see that SKS TA is already in the repository because i saw PKCS#11 Cryptoki Api headers and i was woundering how i install TA to already installed optee instance?

**Comment by Dvergatal** [comment]
I think i can close this issue and open a new one for rk3399.

**Comment by TaihuLight** [comment]
@Dvergatal Could you solved the problem of installing OP-TEE on RK3399? Which issue is the new one?
