### ISSUE TITLE
Compilation error with GCC10 in optee-test after support for C++ is added

### ISSUE THREAD

**Issue by davidson-k** [OP-TEE/optee_os#4166]
Hi,

I'm using GCC10 to compile optee_os and optee_test.  After this [commit](https://github.com/OP-TEE/optee_test/commit/1a205ae33440f603e0579155505ce48215169e58) in optee_test, I'm seeing the below error.

`aarch64-poky-linux-ld.bfd: /home/davkum01/work/tc0/yocto/build-poky/tmp-poky/work/tc0-poky-linux/optee-test/3.10.0+gitAUTOINC+8f7ffdb72b-r0/recipe-sysroot/usr/lib/aarch64-poky-linux/10.1.0/libgcc.a(lse-init.o): in function `init_have_lse_atomics':
/usr/src/debug/libgcc/10.1.0-r0/gcc-10.1.0/build.aarch64-poky-linux.aarch64-poky-linux/libgcc/../../../../../../../work-shared/gcc-10.1.0-r0/gcc-10.1.0/libgcc/config/aarch64/lse-init.c:44: undefined reference to `__getauxval'
/home/davkum01/work/tc0/yocto/build-poky/tmp-poky/work/tc0-poky-linux/optee-test/3.10.0+gitAUTOINC+8f7ffdb72b-r0/recipe-sysroot/usr/include/optee/export-user_ta/mk/link.mk:108: recipe for target '/home/davkum01/work/tc0/yocto/build-poky/tmp-poky/work/tc0-poky-linux/optee-test/3.10.0+gitAUTOINC+8f7ffdb72b-r0/build/ta/os_test/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.elf' failed`

A similar issue for the C files were already fixed in optee-os in this [commit](https://github.com/OP-TEE/optee_os/commit/b836bfb07cfeadda4a1d90227ffbf9cec14a726d#diff-0500d05a2754e818d86f055b8ec91e78325925a3a010641a1f34569ba6a7716b)

I believe something similar have to be done in optee-os for compiling C++ sources in optee-test.

I have tried adding the -mno-outline-atomics to the cxxflags and cppflags, but it didn't help.  I suspect the issue is because of the cxx_tests.cpp.

**Comment by jforissier** [comment]
Hi @davidson-k,

Please see https://github.com/OP-TEE/optee_os/pull/4154.

**Comment by davidson-k** [comment]
Thanks for the quick reply, I will follow up on that.  Closing this now.

**Comment by davidson-k** [comment]
Lets have this open until the mentioned pull request is merged or a similar pull request that can address the issue is merged.

I have applied the changes mentioned in this pull request and it can solve the issue.

**Comment by davidson-k** [comment]
That Pull request was merged and it can solve the issue.  Thanks
