### ISSUE TITLE
About Linux optee driver version

### ISSUE THREAD

**Issue by Master-Chi** [OP-TEE/optee_os#4168]
Hi Optee community,
   When i use repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml -b 3.9.0, 
   linux: 9823b2 (which develope upon v5.7-rc6.)
   optee_os: 3.9.0
   optee_client: 3.9.0
   optee_test: 3.9.0

   But in my project, linux is developed upon v4.9
   is v4.9 linux repo compatible with repo below?
   optee_os: 3.9.0
   optee_client: 3.9.0
   optee_test: 3.9.0

   Is that necessary to update my driver/tee/optee to 9823b2 or driver/tee/optee in v4.9 is fine?

   Sorry for bothering

**Comment by etienne-lms** [comment]
Have a look at https://github.com/linaro-swg/linux/blob/optee/upstream-tee-subsys-patches.txt. It should help you to run latest OP-TEE on older Linux kernels.

**Comment by jforissier** [comment]
Generally speaking, a newer linux driver should always be compatible with an older OP-TEE. Upgrading the kernel should never break things.

**Comment by Master-Chi** [comment]
@jforissier 
But I am using and older Linux(v4.9) with new OPTEE(3.9). Is that compatible? My target is pass all xtest. I found a lot of failed items. I am not sure the failure result form my configuration or the version incompatibility mentioned before.

**Comment by etienne-lms** [comment]
Indeed some of the xtest regression tests depend on features implemented in optee kernel driver.
I would expect latest **optee_os** & **optee_client** do comply with an old Linux kernel but more recent driver features (i.e. null memref) obviously can't be successfully tested from latest **optee_test**. Also there are some corner cases tested by xtest that only a recent optee driver can catch. For those an old linux driver may not behave as recent xtest would expect.

To get `xtest` to succeed you would need to either disable some tests (`xtest -x <test-id>`) or backport required optee driver patches based on [upstream-tee-subsys-patches.txt](https://github.com/linaro-swg/linux/blob/optee/upstream-tee-subsys-patches.txt).

**Comment by jenswi-linaro** [comment]
> But I am using and older Linux(v4.9) with new OPTEE(3.9). Is that compatible? My target is pass all xtest. I found a lot of failed items. I am not sure the failure result form my configuration or the version incompatibility mentioned before.

That is trickier since we're only having xtest work with the latest on all the OP-TEE gits (optee_os, optee_client and optee_test) and generally the latest on https://github.com/linaro-swg/linux/tree/optee. Sometimes we have config options and/or probing to skip tests in order to be a bit relaxed with the kernel.

You could consider cherry-picking all the changes listed in https://github.com/linaro-swg/linux/blob/optee/upstream-tee-subsys-patches.txt that you think makes sense. With those in place it might work.

**Comment by Master-Chi** [comment]
@etienne-lms @jenswi-linaro Got it, I have two choice now. 
1. Using optee_os & optee_client & optee_test in v3.9.0 and cherry-picking patches in upstream-tee-subsys-patches.txt.
2. using optee_os & optee_client & optee_test in v3.0.0 witch is more compatible with linux v4.9.
From your perspective， which is more easier?
Thanks very much

**Comment by jenswi-linaro** [comment]
I'd recommend option 1 because it's easier to maintain and easier to update since you're no too far from upstream.

**Comment by Master-Chi** [comment]
Thx for your suggestion, i will try it
