### ISSUE TITLE
optee test 1013

### ISSUE THREAD

**Issue by Master-Chi** [OP-TEE/optee_os#4171]
Hi ,optee community,
   I have some trouble while using optee test (v3.9.0) + optee_os(v3.9.0)
   case 1013.1  Using small concurrency TA pass.
   case 1013.2  Using large concurrency TA failed with errno 0xffff000c TEEC_ERROR_OUT_OF_MEMORY
   CFG_WITH_PAGER is n in my optee os config, and 1013 thread is 2. If 1013 thread num is 1, 1013.2 test pass.
   I have questions:
   1. Why 1013.2 failed while thread num > 1
   2. Why TA 5ce0c432-... load three times, first time pseudo TA, then user TA (Secure Storage TA), fianlly user TA(REE)

  Thank you very much

**Comment by jforissier** [comment]
> 2. Why TA 5ce0c432-... load three times, first time pseudo TA, then user TA (Secure Storage TA), fianlly user TA(REE)

The TA is not loaded three times. TA can be stored in different places so these debug traces just show where the TEE is looking for the TA. It is finally found in the REE FS.

**Comment by jforissier** [comment]
> Hi ,optee community,
> I have some trouble while using optee test (v3.9.0) + optee_os(v3.9.0)
> case 1013.1 Using small concurrency TA pass.
> case 1013.2 Using large concurrency TA failed with errno 0xffff000c TEEC_ERROR_OUT_OF_MEMORY

You may try to increase `CFG_CORE_HEAP_SIZE` for example `CFG_CORE_HEAP_SIZE=131072` (128KB).

**Comment by Master-Chi** [comment]
Thx for reply, the error generated when sys_map_zi in populate_segments(in ldelf) mapping memory. 
But am not sure which result in error, heap size or shm size. 
I increase heap size to 524288(512KB) and shm 0x400000(4MB), still  tee_ta_invoke_command: Error: ffff000c of 4.
when CFG_WITH_PAGER = n in arm64,  how much tzdram/shm/heap is required at least？
Is there any other suggestion?

**Comment by Master-Chi** [comment]
I increase Tee core va size to 8MB and TA va size to 8MB, problem solved. thx a lot

**Comment by jenswi-linaro** [comment]
> I increase Tee core va size to 8MB and TA va size to 8MB, problem solved. thx a lot

Good that you found something that works. However, I don't think it's the `CFG_TEE_RAM_VA_SIZE` that is the culprit you can probably restore that to previous value. Regarding "TA va size" which config/define are you referring to?
