### ISSUE TITLE
Multiple OP-TEE TEE support?

### ISSUE THREAD

**Issue by cgshep** [OP-TEE/optee_os#4175]
Hi all,

Is it possible to launch two OP-TEE instances simultaneously currently? And, if so, what is the current level of support? I mention it as the GlobalPlatform specifications support the launching of multiple TEEs and the OP-TEE docs say:

>  Portability - the TEE aims at being easily pluggable to different architectures and available HW and has to support various setups such as multiple client OSes or multiple TEEs.

**Comment by jbech-linaro** [comment]
Hi, I guess the closest we have related to that today is this: https://optee.readthedocs.io/en/latest/architecture/virtualization.html

I think the comment you'r referring to is that we didn't want to lock ourselves into Arm only, however as OP-TEE has evolved it's clear that it has become an Arm only thing.
