### ISSUE TITLE
Question: Reducing secure storage block size

### ISSUE THREAD

**Issue by yaziza** [OP-TEE/optee_os#4182]
Hi there, 

i have two questions regarding OP-TEE trusted storage implementation and keys handling:

1. Can the minimal block size of secure storage encrypted files be reduced ? Using 16kb for storing e.g. small symmetric keys does not scale well. I was not able to identify where this values comes from and why ?

2. Is it guaranteed that the call to **TEE_MemFill** is not optimized away by the compiler ?

**Comment by jforissier** [comment]
Hi @yaziza ,

> 1. Can the minimal block size of secure storage encrypted files be reduced ? Using 16kb for storing e.g. small symmetric keys does not scale well. I was not able to identify where this values comes from and why ?

Which secure storage implementation are you referring to? `tee_ree_fs.c` defines a 4096 byte `BLOCK_SIZE` while `tee_rpmb_fs.c` has `RPMB_DATA_SIZE` equal to 256 bytes. The REE FS block size can probably be adjusted.

> 2. Is it guaranteed that the call to **TEE_MemFill** is not optimized away by the compiler ?

Yes, why not? The compiler has no knowledge about the semantics of `TEE_MemFill()`.
