### ISSUE TITLE
Increasing CORE_MMU_PGDIR_SHIFT/LEVEL

### ISSUE THREAD

**Issue by janhoogerbrugge** [OP-TEE/optee_os#4189]
Hi,

I would like to read the entire DRAM memory from a pseudo TA in order to implement a security feature. So I added:

register_phys_mem(MEM_AREA_RAM_NSEC, CFG_DRAM_BASE, CFG_DDR_SIZE);

If CFG_DDR_SIZE is more than 1GB then the system crashes when it boots:

E/TC:0 0 assertion 'user_va_idx != -1' failed at core/arch/arm/mm/core_mmu_lpae.c:517 <core_init_mmu>
E/TC:0 0 Panic at core/kernel/assert.c:28 <_assert_break>
E/TC:0 0 Call stack:
E/TC:0 0  0x0000000056009e18

I guess that the 1GB limitation is due to these two defines:

#define CORE_MMU_PGDIR_SHIFT    21
#define CORE_MMU_PGDIR_LEVEL    3

Two to the power of (21 + 9) is 1G where the 9 is coming from the number of bits to index a page table.

So the solution could be to use this:

#define CORE_MMU_PGDIR_SHIFT   30
#define CORE_MMU_PGDIR_LEVEL   4

If I do this then I gets lots of compiler warnings about integer overflows. Therefore I changed:

#define CORE_MMU_PGDIR_SIZE             (1 << CORE_MMU_PGDIR_SHIFT)

to

#define CORE_MMU_PGDIR_SIZE             (1L << CORE_MMU_PGDIR_SHIFT)

After that the warnings are gone but I get an error because the '1L' is used in linker script kern.ld.S.

Is there an easy way to increase the mapable memory space? 

Regards,
Jan.

**Comment by jforissier** [comment]
Hi @janhoogerbrugge ,


> If I do this then I gets lots of compiler warnings about integer overflows. Therefore I changed:
> 
> #define CORE_MMU_PGDIR_SIZE (1 << CORE_MMU_PGDIR_SHIFT)

This line doesn't exist anymore in `master`. `CORE_MMU_PGDIR_SIZE1` is now `BIT(CORE_MMU_PGDIR_SHIFT)`, see commit bd265fd08. I suspect this should make it work for you (the linker should be fine with the new definition).

**Comment by janhoogerbrugge** [comment]
Hi Jerome,

Thanks.

I changed the define of CORE_MMU_PGDIR_SIZE to BIT64(CORE_MMU_PGDIR_SHIFT). If I would have used BIT instead of BIT64 then the result would be guaranteed the same as before. This modification works fine. However if I increase PGDIR_SHIFT/LEVEL like this to make a larger mapping possible:

#define CORE_MMU_PGDIR_SHIFT    30
#define CORE_MMU_PGDIR_LEVEL    4

Then the system crashes as follows when it boots:

E/TC:0 0 assertion 'm.addr || !core_mmu_type_to_attr(m.type)' failed at core/arch/arm/mm/core_mmu.c:859 <init_mem_map>
E/TC:0 0 Panic at core/kernel/assert.c:28 <_assert_break>
E/TC:0 0 Call stack:
E/TC:0 0  0x0000000056009e18

Any idea why it crashes like this? Is there still an integer overflow somewhere? There are no compiler warnings. Has anybody else tried to increase these values?

Regards,
Jan

**Comment by jenswi-linaro** [comment]
You should not change `CORE_MMU_PGDIR_SHIFT` and friends, they tell the hardware properties of the translation tables. Instead I suspect that you need to increase `CFG_LPAE_ADDR_SPACE_BITS`. You may need to do some extra tricks to make sure that you map the memory with the largest possible granularity or you'll waste quite a bit of memory for the translation tables.

**Comment by jforissier** [comment]
@janhoogerbrugge note that `CFG_LPAE_ADDR_SPACE_BITS` was introduced very recently by cc8fda93. You may want to backport this commit in case you don't have it, or set the old config instead (`CFG_LPAE_ADDR_SPACE_SIZE`).

**Comment by janhoogerbrugge** [comment]
Hi Jerome and Jens,

I already discovered the rename of CFG_LPAE_ADDR_SPACE_SIZE to CFG_LPAE_ADDR_SPACE_BITS ;-).

When I increase the variable by 16 times and also increase CORE_MMU_L1_TBL_OFFSET then register_phys_mem(MEM_AREA_RAM_NSEC, ...) works for 2GB but if I increase it to 3GB I get this crash at boot time:

image offset 0x8000, pagesize 0x200, ivt offset 0x0
E/TC:0 0 Panic 'Can't divide MMU entry' at core/arch/arm/mm/core_mmu.c:1487 <core_mmu_map_region>
E/TC:0 0 Call stack:
E/TC:0 0  0x0000000056009e18

Is this because the depth of the address translation is not deep enough?

I will also do some debugging to investigate this.

In core_mmu_entry_to_finer_grained (which causes the "can't divide' assert), I see 'tbl_info->level >= 3'. Is the '3' something that should be parameterized?

Jens mentioned mapping with larger granularity. Are super/huge pages supported?

**Comment by jenswi-linaro** [comment]
You don't give us much to work with. Based on what I've seen so far I guess that you're running out of translation tables.

**Comment by janhoogerbrugge** [comment]
Indeed. I increased MAX_XLAT_TABLES and now it works fine.

Thanks guys!
