### ISSUE TITLE
Build fails with QEMU build.sh

### ISSUE THREAD

**Issue by murasesyuka** [OP-TEE/optee_os#419]
it was generate from the setup_qemu_optee.sh.
and run build.sh was fail at optee_test.

because used optee_test is old.

https://github.com/OP-TEE/optee_os/blob/master/scripts/setup_qemu_optee.sh#L71

latest optee_os is changed API. 
therefore optee_test need to include this commit.

https://github.com/OP-TEE/optee_test/commit/50657b7d0a11d8eda857134df59177e72917b5de

**Comment by pascal-brand-st-dev** [comment]
We are currently changing the way environments are imported. We are now using *android-like* manifest and build. Please have a look at https://github.com/OP-TEE/manifest/blob/master/README.md. It will guide you to retrieve qemu environment using this new way.

Note that setup scripts are obsolete, and will be removed soon.

**Comment by murasesyuka** [comment]
Hi pascal-brand-st-dev.

 I check repo and manifest, thanks for information.
