### ISSUE TITLE
How to delete the secure storage TA

### ISSUE THREAD

**Issue by xiangmingyuan** [OP-TEE/optee_os#4198]
Hi OPTEE group,

Is there a way to delete [secure storage TA](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#secure-storage-ta)?

We can install a TA to secure storage by calling a [pta](https://github.com/OP-TEE/optee_os/blob/master/core/pta/secstor_ta_mgmt.c#L40). However, I don't find any API to delete the installed TA. I do find one related function, [`tee_tadb_ta_delete()`](https://github.com/OP-TEE/optee_os/blob/master/core/tee/tadb.c#L588), but it seems that this function is not exposed to the TA side. Does this mean we have to implement a GP API to use this function?

Thanks,
Mingyuan

**Comment by jenswi-linaro** [comment]
You can expose that function via the `secstor_ta_mgmt` TA which handles `PTA_SECSTOR_TA_MGMT_BOOTSTRAP` to install TAs. But I suppose you'll need some way of checking if a TA is allowed to be uninstalled.

**Comment by xiangmingyuan** [comment]
Hi @jenswi-linaro ,

Thanks for your help! Adding the delete operation to `secstor_ta_mgmt` TA seems like a good option. We'll implement this feature. BTW, thanks for your reminder of checking the TA before uninstalling.

Thanks,
Mingyuan
