### ISSUE TITLE
Architecture i386 End Of Life

### ISSUE THREAD

**Issue by Artuurodrt** [OP-TEE/optee_os#4200]
$ sudo dpkg --add-architecture i386
$ sudo apt-get updat

When I try to enable installation of i386 architecture packages and update the package managers database a bunch of errors are displayed. 

http://ports.ubuntu.com/dists/bionic/main/binary-i386/Packages  404  Not Found [IP: 2001:67c:1360:8001::24 80]
http://ports.ubuntu.com/dists/bionic-updates/main/binary-i386/Packages  404  Not Found [IP: 2001:67c:1360:8001::24 80]
http://ports.ubuntu.com/dists/bionic-security/main/binary-i386/Packages  404  Not Found [IP: 2001:67c:1360:8001::24 80]
http://ports.ubuntu.com/dists/bionic-backports/main/binary-i386/Packages  404  Not Found [IP: 2001:67c:1360:8001::24 80]

What can I do if Architecture i386 is no longer available?

**Comment by jbech-linaro** [comment]
Hi @Artuurodrt , this is a good question. I've seen for a while that it seems to be harder and harder to enable i386 on various distros. I'm not sure if there is a plan similar to what the Python community did a while ago when "retiring" the 2.x Python.

What distro are you running? Ubuntu 20.xy?

I think this is a question that the OP-TEE core team needs to investigate and discuss a bit more in detail. I'm going to bring this up with Linaro OP-TEE engineers as well as TrustedFirmware.

In the meantime the best way forward is probably to use Docker or something similar and base the builds on an older Ubuntu version (18.04 seems pretty stable). I have a couple of branches for running OP-TEE Docker at GitHub page. The most up-to-date one is the a 16.04 with "caching" enabled (ccache, repo forest stored outside the Docker image on my host machine). You can find that branch [here](https://github.com/jbech-linaro/docker_optee/tree/cached-ubuntu-16.04). That might be useful as a basis for what you need.

**Comment by jforissier** [comment]
Why the `i386` packages are needed in the first place? From https://optee.readthedocs.io/en/latest/building/prerequisites.html#prerequisites I can see that we have `libc6:i386 libstdc++6:i386 libz1:i386` but I do not remember why they are required (dependencies for what?).

@Artuurodrt if you ignore the above errors and install only the non-`i386` packages, do you get build errors?

**Comment by Artuurodrt** [comment]
I installed the non-i386 packages without any error but after installing toolchains ($ make toolchains) when I want to start the build by running " $ make ", the following error is displayed


make -C /home/eduardo/devel/optee/build/../optee_os O=out/arm CFG_ARM64_core=y PLATFORM=rpi3 CROSS_COMPILE="/usr/bin/ccache /home/eduardo/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_core="/usr/bin/ccache /home/eduardo/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm64="/usr/bin/ccache /home/eduardo/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm32="/usr/bin/ccache /home/eduardo/devel/optee/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=0 CFG_TEE_BENCHMARK=n
make[1]: Entering directory '/home/eduardo/devel/optee/optee_os'
  CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
  CC      out/arm/core/include/generated/.asm-defines.s
ccache: error: execv of /home/eduardo/devel/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-gcc failed: Exec format error
mk/compile.mk:245: recipe for target 'out/arm/core/include/generated/.asm-defines.s' failed
make[1]: *** [out/arm/core/include/generated/.asm-defines.s] Error 1
make[1]: Leaving directory '/home/eduardo/devel/optee/optee_os'
common.mk:441: recipe for target 'optee-os-common' failed
make: *** [optee-os-common] Error 2

any ideas?

**Comment by jforissier** [comment]
Are you trying to build OP-TEE on the Raspberry itself perhaps? This is not (yet) supported. Only cross-compilation on a x86_64 machine is supported.

**Comment by Artuurodrt** [comment]
Yes I am trying to follow https://optee.readthedocs.io/en/latest/building/devices/rpi3.html#build-instructions guide

**Comment by jforissier** [comment]
Which Linux distribution are you running on your PC?

**Comment by jforissier** [comment]
Oh I see it is Ubuntu Bionic (18), it's a bit old but it used to work fine. I would be surprised if Ubuntu had deprecated and removed i386 package. Network issue perhaps? I see IPv6 addresses in your log, maybe try to disable IPv6.

**Comment by Artuurodrt** [comment]
Package i386 is no longer available http://ports.ubuntu.com/dists/bionic/main/

According to the documentation OP-TEE is supported in Raspberry Pi 3 so I am confused now that you mention that is supported with cross-compilation. I don't find where this is mentioned in the "Build instructions"

**Comment by jforissier** [comment]
OP-TEE is always cross compiled. All platforms.

**Comment by Artuurodrt** [comment]
Ok I think I understand now the problem, I can use the Buildroot environment to build a custom Linux system (with OP-TEE) that I can put on the Raspberry Pi right?

**Comment by jbech-linaro** [comment]
FYI I did a QEMU v7 build in clean Docker environment based on Ubuntu 20.04 where I removed all the i386 packages. It compiled with no issues. I couldn't run QEMU, since the old setup forwarding X11 wasn't working any longer. But ... the problem here was a build issue. So, it might be that we no longer need the i386 packages.

I can't remember exactly why we needed them. But I have vague memory that it was some of the other software we were building who needed them. I.e., not OP-TEE directly.

**Comment by jenswi-linaro** [comment]
> I can't remember exactly why we needed them. But I have vague memory that it was some of the other software we were building who needed them. I.e., not OP-TEE directly.

It was the toolchains we used back then. At some point they obviously dropped the i386 dependency.

**Comment by jbech-linaro** [comment]
Not sure if this is useful to anyone, but I've updated my Docker images to use Ubuntu 20.04 now. Here is the [standard](https://github.com/jbech-linaro/docker_optee/tree/ubuntu-20.04) version with no caching (slow) and here is the [cached](https://github.com/jbech-linaro/docker_optee/tree/cached-ubuntu-20.04) version (fast if you have  ccache, repo and Buildroot mirrors locally).

In both of these I have removed the i386 packages (package list for [standard](https://github.com/jbech-linaro/docker_optee/blob/ubuntu-20.04/Dockerfile#L14-L60) and [cached](https://github.com/jbech-linaro/docker_optee/blob/cached-ubuntu-20.04/Dockerfile#L14-L60)). On my Debian machine, this all works as expected, no build issues, xtests runs to completion with no regressions.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_docs/pull/89
