### ISSUE TITLE
CA- Input paramter validation

### ISSUE THREAD

**Issue by aj700** [OP-TEE/optee_os#4203]
Not an issue, more of a question....

hej, as a part of writing some unittest cases, I noticed
`TEEC_InitializeContext(NULL, 0)` yields error code 0xffff0006 <- gives more meaning
&
`TEEC_InitializeContext(NULL, -1)` yields error code 0xffff0008. I was expecting 0xffff0006, so looked into it more.
In an ideal world sanitizing params from callee scales better, but its a tricky situation with negative values here, I totally agree.

can share an OPTEE generic suggestion on sanitizing the parameters from the caller?
thnx.

**Comment by etienne-lms** [comment]
Hi @aj700. Yes please, feel free to create a P-R and discuss this.
