### ISSUE TITLE
eMMC and Secure Write Protection

### ISSUE THREAD

**Issue by Vitolog** [OP-TEE/optee_os#4209]
JESD84-B51 Standard describes a functionality supported by eMMc (5.1) called "Secure Write Protect Mode".
This fuctionality could be useful to protect/unprotect eMMC memory partitions: it could be done sending  authenticated commands (commands based on RPMB mechanism).
Are these commands (0x0006 and 0x0007) supported by OP-TEE?

**Comment by jenswi-linaro** [comment]
> Are these commands (0x0006 and 0x0007) supported by OP-TEE?

No, they are currently not supported by OP-TEE.
