### ISSUE TITLE
Status of any work to bring OPTEE up to Global Platform TEE Internal Core Specification 1.2

### ISSUE THREAD

**Issue by dougsteed** [OP-TEE/optee_os#4217]
I am curious of the status of the work (if any) to bring OPTEE up to Global Platform TEE Internal Core Specification v1.2. In particular, I'm interested in support for the algorithms X25519 and Ed25519. The version of LibTomCrypt in OPTEE does support these algorithms but they are not currently exposed in the TEE API, as they are in v1.2 of the GP API. It appears as though the relevant support in mbedtls is an ongoing development.

I saw mention of the API v1.2 in [another issue](https://github.com/OP-TEE/optee_os/issues/4017) which stated: 
>With https://projects.linaro.org/browse/LOC-342 we're updating to GlobalPlatform TEE Internal Core API Specification v1.2.1.

but after reading the Linaro issue, it seems this may be referring only to the minimum changes needed to implement the GP test suite.

**Comment by jforissier** [comment]
Hi @dougsteed ,

I am not aware of anyone working on this, but it would be good to have.

**Comment by jenswi-linaro** [comment]
Regarding
> With https://projects.linaro.org/browse/LOC-342 we're updating to GlobalPlatform TEE Internal Core API Specification v1.2.1.

It turned out that v1.2.1 would be some extra work as the test TAs in the GP test suite didn't target that version.

Update to v1.2.1 would be welcome. There's a few macros added in v1.2 that make it easier to manage compatibility with different versions of the API from a TA point of view.
