### ISSUE TITLE
How to set up TZC400 in qemu?

### ISSUE THREAD

**Issue by xiangmingyuan** [OP-TEE/optee_os#4224]
Hi OPTEE group,

I read from the [doc](https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html#memory-firewalls-tzasc) that we can use TZC400 to protect DRAM, however, I don't know how to configure it. There is no definition of `TZC400_BASE`, which is needed to initialize tzc400; see [here](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-vexpress/main.c#L131).

PS: I do find a [`TZC400_BASE`](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-vexpress/platform_config.h#L22) for FVP, but I don't know the exact address that I should use for qemu.

Thanks,
Mingyuan

**Comment by xiangmingyuan** [comment]
Hi OPTEE group,

I read from the [doc](https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html#memory-firewalls-tzasc) that we can use TZC400 to protect DRAM, however, I don't know how to configure it. There is no definition of `TZC400_BASE`, which is needed to initialize tzc400; see [here](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-vexpress/main.c#L131).

PS: I do find a [`TZC400_BASE`](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-vexpress/platform_config.h#L22) for FVP, but I don't know the exact address that I should use for qemu.

Thanks,
Mingyuan

**Comment by jenswi-linaro** [comment]
Hi @xiangmingyuan,

I don't think that the QEMU model has a TZC400. The security settings are hard coded in the model if I have understood it correctly.

**Comment by xiangmingyuan** [comment]
Hi @jenswi-linaro ,

Thanks for your help!

Mingyuan
