### ISSUE TITLE
Cannot link libtomcrypt library in trusted application

### ISSUE THREAD

**Issue by Xinyao90** [OP-TEE/optee_os#4228]
Hi,

I'm trying to use libtomcrypt library in RSA encryption in my CA. In my local machine, I can successfully compile and run my code with the command:  
_$gcc LibTomCrypt.c -o LibTomCrypt -ltomcrypt_

Here is my application's CMakeLists.txt file:
```
project (optee_example_RSA C)

set (SRC host/main.c)

add_executable (${PROJECT_NAME} ${SRC})

target_include_directories(${PROJECT_NAME}
			   PRIVATE ta/include
			   PRIVATE include
			   PRIVATE /home/heidi/libtomcryptfiles/include)

target_link_libraries (${PROJECT_NAME} 
				PRIVATE teec 
				PRIVATE -L/home/heidi/libtomcryptfiles/libcrypto.a -ltomcrypt)

install (TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_BINDIR})
```

However, if I try to cross-compile it from X86 to AArch64 architecture, with command _"$make -j `nproc`"_, it gives error as below:
```
/home/heidi/optee-project/toolchains/aarch64/bin/../lib/gcc/aarch64-linux-gnu/8.3.0/../../../../aarch64-linux-gnu/bin/ld: cannot find -ltomcrypt
collect2: error: ld returned 1 exit status
```

Any suggestions?

Thanks

**Comment by jforissier** [comment]
Hi @Xinyao90,

What do you not understand in `ld: cannot find -ltomcrypt` ? 🤔

**Comment by Xinyao90** [comment]
Hi @jforissier ,
I can link libtomcrypt library and compile code successfully on my local machine with $gcc LibTomCrypt.c -o LibTomCrypt -ltomcrypt. However, I have trouble linking libtomcrypt library in my CA. How can I fix it? Any suggestions on modifying the CMakeLists.txt or install libcrypto.a in a different path?

**Comment by jenswi-linaro** [comment]
I assume you're cross compiling the application. That means that the library must be available for the cross compiler to find also. Perhaps you can update the buildroot (if that's what you're using) configuration to compile LibTomCrypt too.

**Comment by Xinyao90** [comment]
@jenswi-linaro Yes, I'm cross-compiling the application from Ubuntu to rpi3. Could you let me know how to update the buildroot config to compile LibTomCrypt?

**Comment by etienne-lms** [comment]
Buildroot supports  libtomcrypt package. Note however that it is currently built (when enabled) only as a static library (**libtomcrypt.a**), see [Buildroot **libtomcrypt.mk**](https://git.buildroot.net/buildroot/tree/package/libtomcrypt/libtomcrypt.mk?h=2020.08#n13).
To enable the package, you can add `BR2_PACKAGE_LIBTOMCRYPT=y` in OP-TEE build **./br-ext/configs/optee-generic**
or you can simply run OP-TEE build with `make BR2_PACKAGE_LIBTOMCRYPT=y all`.

**Comment by Xinyao90** [comment]
@etienne-lms Thanks a lot, I've linked the libtomcrypt library, and now there is no compilation error. However, at runtime, it appears segmentation fault. I can compile and run the RSA encryption and decryption code on my local Ubuntu machine without error using the command $gcc libtomcrypt.c -o libtomcrypt -ltomcrypt , but cannot run it with OPTEE. Here is my code. Any suggestions? Really appreciate it.
[RSA.zip](https://github.com/OP-TEE/optee_os/files/5627772/RSA.zip)

**Comment by etienne-lms** [comment]
Maybe check your libtc integration is properly configured and initialized in your client application. I think your issue is not related to OP-TEE as you are building a Linux application, not a TA.
