### ISSUE TITLE
TEE logger architecture

### ISSUE THREAD

**Issue by anisyanka** [OP-TEE/optee_os#4230]
Hi,

In [this](https://github.com/OP-TEE/optee_client/issues/219) issue I mentioned that we have a working logger in optee-os.
We have implemented one with the help of a new RPC. Our approach is similar to [this PR](https://github.com/OP-TEE/optee_os/pull/810).
But a logger based on RPCs has a few complications mentioned in the PR linked above:
 - Large amount of messages can lead to memory fragmentation, because RPCs call alloc/free functions often.
 - It is impossible to use the logger from other RPC routines and from interrupt handlers.

To avoid these issues we propose to use statically allocated circular buffers shared between REE and TEE.
We assume that in shared memory we have N buffers and a table with descriptions of their current state.
A descriptor consists of the following fields:
 - Buffer number [0 – N-1].
 - Buffer state (see below).
 - Physical address of the buffer.
 - Size of the buffer.
 - Write index (w_idx). It's an offset into the buffer indicating where TEE must write the next log message.
 - Read index (r_idx). It's an offset into the buffer indicating where REE must read the next log message.

![tee-logger](https://user-images.githubusercontent.com/33737815/100458332-a5ee7400-30d4-11eb-8eda-3a0d04dc5e2d.png)

Each of the N buffers can be assigned to a CPU core; a core will work with its respectible assigned buffer.
Every buffer has one of the three possible states:
1. state=0: the buffer is not assigned to any core.
2. state=1: the buffer is assigned to a core and the core might work with the buffer at any time.
3. state=2: the buffer is full or has no place for more log strings. This means that a core must find a new buffer for logging.
State 0 --> 1 is changed only by TEE.
State 1 --> 2 is changed only by TEE.
State 2 --> 0 is changed only by REE.

#### How does TEE write log messages?
When a core in TEE is going to log a message for the first time, it takes the tee-descriptor-array-spinlock
to get acess to the descriptor table. The core finds a buffer with `state=0` and changes it to `state=1`. Also the core
saves the buffer's number to a per-cpu variable "current buffer index". Here we have to release tee-descriptor-array-spinlock.
After this the core may work with the chosen buffer. It means that we don't have to care about concurrent writes
to a buffer from several cores because every core will have its own per-cpu buffer.

After this logic the core will work with the circular buffer all the time except for one case — when SGI is needed (see below about it).
If there is no free buffers to save new messages, TEE will increment a per-cpu counter of dropped/skipped log records.
Developers might increase the number of buffers, based on the counter, because it is assumed that N is chosen
based on the expected system load. If the skipped records counter goes above zero, it will be a sign for the developers to increase N.
By default N=2*number-of-cpus.
Also we assume there will be a global TEE variable "log records" with atomic access to increment.
Current value must be saved to the buffer together with a log string.
That's why a log entry in a shared buffer will look as:
```
    <record index> | <cpu number> | <null-terminated log string>.
```
When a message is successfully saved to a buffer, TEE updates `w_idx` for the buffer.

#### How does REE read log messages?
We assume that the optee linux driver has to export a new device file in devfs (e.g. "/dev/opteelog") to get access
to the log buffers from userspace. We also assume that there will be a special script to easily read log messages from
the file:
1. Userspace script calls `read("/dev/opteelog")`.
2. Read operation handler in the driver falls asleep in `wait_for_completion_interruptible()`.
3. Something triggers `complete()`. See below about these triggers.
4. Read operation handler in the driver wakes up and copies all available log messages from the shared buffers to the userspace:
 4.1. Find a buffer with `state=1` or `state=2`.
 4.2. Take ree-descriptor-array-spinlock.
 4.3. Read data from current `r_idx` to current `w_idx`.
 4.4. Update `r_idx`.
 4.5. Release the ree-descriptor-array-spinlock.
5. Userspace script: spawns new reader thread, sorts new data in old thread and saves it to a log file.

#### Concurrent access
We assume that:
- Every particular core works with its own buffer.
- Only TEE writes anything to shared circular buffers.
- Only TEE changes `w_idx`.
- Only REE reads anything from the buffers.
- Only REE changes `r_idx`.
In this case, situations with concurrent access to descriptor table from different worlds are excluded.
Access to the descriptor table only from REE or only from TEE is managed by spinlocks.

#### Difficulties in using this approach
1. High load logging, when buffers fill up very quickly. We must have a mechanism to prevent overflow.
2. Low load logging, when buffers fill up very slowly. We must have a mechanism to periodically read the buffers.
3. Because each core can write logs to its own buffer, the task of restoring the sequence of log messages arises.
We must have a mechanism for sorting log messages.

#### High load logging
This case can lead to data loss, because shared buffers are circular and finite.
To control it we can use SGI to generate interrupts to ask REE to flush log buffers.
If `w_idx` of a buffer overtakes `r_idx` it means that REE has no time to read the buffer. It means that
there is no available space for new log strings. In this case a CPU must assign to itself a new available buffer:
1. Set `state=2`. It means that eventually REE will set `state=0`. Also it means that this buffer can't be assigned to any other core.
2. Generate SGI.
3. Take tee-descriptor-array-spinlock.
4. Assign a new buffer to the current cpu. After this we can log new messages to the new buffer.
5. Release tee-descriptor-array-spinlock.
6. Once SGI-handler in optee-linux-driver is called on any core, it just calls `complete()`.
7. Once the sleeping thread wakes up on any core, it reads all available data and changes `state` from 2 to 0.
After this the buffer can be assigned by TEE to any core again.

#### Low load / normal logging
In normal (not stress) logging shared buffers won't overfill. They will work just like circular buffers without SGI.
In this case we need a mechanism to periodically read data from the shared buffers.
To control it we have to add a timer in optee-linux-driver. The timer will periodically call `complete()` and it will wake up
threads sleeping for `read()`.

#### Sorting of log messages
In userspace after reading a new portion of data we can sort the log entries by the
record index to restore the right order of log messages.

We want to discuss the proposed design and to start implementing it.
What do you think about it?

Thank you!

**Comment by jenswi-linaro** [comment]
Why one ringbuffer per core? Which problem are you trying to solve? With a combined buffer we wouldn't have to sort the log entries later.
What if it's not acceptable to drop log entries? I can see situations where we'd like to have a complete log.
How can we differentiate between high/normal/low load logging? It seems easier with a single design.
The SGI problem isn't very easy to solve, it's probably the hardest part.

**Comment by anisyanka** [comment]
@jenswi-linaro, thank you for the reply!

>Why one ringbuffer per core? Which problem are you trying to solve? With a combined buffer we wouldn't have to sort the log entries later.

If we will use only one common ringbuffer, we will be forced to use spinlocks. We want to avoid any possible message loss
and locking in TEE, because of following reasons:

1) Locks potentially can affect the Linux scheduling
2) If we want to debug some kind of race condition with logging, adding of locks can be equal to adding some synchronization in code, so race will not be reproduced
3) Also locking  model  lead us to following situation:
For example, if we have one buffer and we are in a situation when we need SGI (the buffer is almost full), we should act like this:
```sh
   - lock()
   - generate SGI (this just sets some flags in the ARM GIC)
   - release()
```
After this we mustn't write any new log messages until REE reads the buffer, because we really don't know when Linux
handles the SGI. And in TEE we can't define the end of SGI handling in Linux. Maybe we can add a new SMC to notify
TEE about this, but in this case all cores in TEE, which wanted to log something, would be waiting for this notification.
But it's not so great, because this can happen in an interrupt handler in TEE. That's why we propose to use per-cpu buffers.

>What if it's not acceptable to drop log entries? I can see situations where we'd like to have a complete log.

It seems there are no ideal solutions that allow to not lose some entries besides TEE locking.
But my point is that dropping some log entries is better than locking.
And also we don't drop log entries silently. We increment their counter and we can, for example,
generate a panic to notify developers that they need to increase the count of ringbuffers (N).
In this case each developer can adjust N to suit their needs.

>How can we differentiate between high/normal/low load logging?

Could you please clarify your question? I'm not sure I understood you right there.
I mentioned this logger cases:
```
High load case- buffers are fully filled, and buffers switch performed, then REE notified by SGI 
Low load case- buffers do not filled till the end, and REE takes data by timer
```
so their difference is how REE gets notified - by timer or by SGI, and this is performed transparently to user depending on the load.
For example if you want to log the work of some rare service, it will be about "low load logging".

**Comment by jenswi-linaro** [comment]
I like this idea and I think we should compare it with our current log framework to make sure this solution becomes an improvement in all aspects where it can.

> > Why one ringbuffer per core? Which problem are you trying to solve? With a combined buffer we wouldn't have to sort the log entries later.
> 
> If we will use only one common ringbuffer, we will be forced to use spinlocks. We want to avoid any possible message loss
> and locking in TEE, because of following reasons:
> 
> 1. Locks potentially can affect the Linux scheduling

Yes, but the size of the windows we're talking about here is so small that it can only be a noticeable problem if there's a race condition under investigation. We have plenty of other places where locks are held.

> 2. If we want to debug some kind of race condition with logging, adding of locks can be equal to adding some synchronization in code, so race will not be reproduced

Even a shared counter can affect that (see implementation of `atomic_inc32()`), in fact the method (indicating contention in the next log entry) used in the current log framework is likely more helpful.

> 3. Also locking  model  lead us to following situation:
>    For example, if we have one buffer and we are in a situation when we need SGI (the buffer is almost full), we should act like this:
> 
> ```shell
>    - lock()
>    - generate SGI (this just sets some flags in the ARM GIC)
>    - release()
> ```
> 
> After this we mustn't write any new log messages until REE reads the buffer, because we really don't know when Linux
> handles the SGI. And in TEE we can't define the end of SGI handling in Linux. Maybe we can add a new SMC to notify
> TEE about this, but in this case all cores in TEE, which wanted to log something, would be waiting for this notification.
> But it's not so great, because this can happen in an interrupt handler in TEE. That's why we propose to use per-cpu buffers.

With multiple ringbuffers you only make this problem less likely to occur, but it can still occur. Worst case looks like all cores busy serving secure interrupts and flooding the log from the interrupt handler. With this normal world will be starved and in the end we may deadlock. Here's two options either we drop logs entries or temporarily disables the interrupts causing the flooding. The latter isn't too easy, and it may also be only a theoretical problem. So here I'd agree to drop log entries, but perhaps only the ones where non-secure interrupts are masked. We can probably tweak this further.

The advantage with a single ringbuffer is a less complicated setup. How about starting with this and extend it later if needed?

> 
> > What if it's not acceptable to drop log entries? I can see situations where we'd like to have a complete log.
> 
> It seems there are no ideal solutions that allow to not lose some entries besides TEE locking.
> But my point is that dropping some log entries is better than locking.

I don't agree. With locking you can actually tell which logs would have been potentially overlapping and that might give a clue to why the problem disappears with logs enabled. I don't think there is one solution that will always be the best. So far it has worked quite well with the current approach with a big lock. We can add a config option to allow dropping log entries also from normal contexts where non-secure interrupts are not masked.

> And also we don't drop log entries silently. We increment their counter and we can, for example,
> generate a panic to notify developers that they need to increase the count of ringbuffers (N).
> In this case each developer can adjust N to suit their needs.

This is a last resort as instead of solving the problems ourselves we leave it to each developer to sort out.

> 
> > How can we differentiate between high/normal/low load logging?
> 
> Could you please clarify your question? I'm not sure I understood you right there.
> I mentioned this logger cases:
> 
> ```
> High load case- buffers are fully filled, and buffers switch performed, then REE notified by SGI 
> Low load case- buffers do not filled till the end, and REE takes data by timer
> ```
> 
> so their difference is how REE gets notified - by timer or by SGI, and this is performed transparently to user depending on the load.
> For example if you want to log the work of some rare service, it will be about "low load logging".

How do you determine the load?

To me it sounds like you're going to poll the buffers from normal world and if that rate isn't high enough you're going to send SGIs until situation improves. For long periods of time there will be no log entries at all and the polling will be a waste of time.

**Comment by kkarasev** [comment]
> For long periods of time there will be no log entries at all and the polling will be a waste of time.

Putting aside single- vs. multi- buffer approaches for a while, how about poll log entries only when leaving SWd and resort to SGI for the high load cases or when logging from interrupt handlers? In this case there will be no useless polls by timeout and we'll guarantee that log entries from interrupts still will be delivered.

**Comment by a-rybakov** [comment]
> Putting aside single- vs. multi- buffer approaches for a while, how about poll log entries only when leaving SWd and resort to SGI for the high load cases or when logging from interrupt handlers? In this case there will be no useless polls by timeout and we'll guarantee that log entries from interrupts still will be delivered.

Polling log buffers when leaving SWD sounds good, I suppose this can be performed for the core released. But SGI for logging from interrupt handlers looks overkill - in worst case for each interruprt delivered to SWd we will send SGI to NWd. So looks like for this case polling by timer still needed, for smoothing the load.

**Comment by jenswi-linaro** [comment]
Maybe we're starting in the wrong end here. First we need to know what we want from this. My top priority is that it's reliable, if you don't get out the logs you need then it's useless for debugging sudden crashes or panics. Another thing that also would be of great help would be to be able to mix the OP-TEE log with the kernel log in the same timeline. Sometimes when debugging it's hard to tell which event happened first.

Performance is great, but we can't sacrifice the corner cases.

What are you looking for here?

**Comment by anisyanka** [comment]
> > > How can we differentiate between high/normal/low load logging?
> > 
> > 
> > Could you please clarify your question? I'm not sure I understood you right there.
> > I mentioned this logger cases:
> > ```
> > High load case- buffers are fully filled, and buffers switch performed, then REE notified by SGI 
> > Low load case- buffers do not filled till the end, and REE takes data by timer
> > ```
> > 
> > 
> > so their difference is how REE gets notified - by timer or by SGI, and this is performed transparently to user depending on the load.
> > For example if you want to log the work of some rare service, it will be about "low load logging".
> 
> How do you determine the load?

There is no exact way to determine the load. We can only assume the future load.
Each developer decides for himself how much he will load the system with logs.
Other words, one developer might use `DMSG()/IMSG()` very rare, but other one vice versa.
We should be ready to any situations.

> Another thing that also would be of great help would be to be able to mix the OP-TEE log
with the kernel log in the same timeline.

Great idea, thank you!
We'll figure out how to implement it.

> My top priority is that it's reliable, if you don't get out the logs you need then it's useless
for debugging sudden crashes or panics.

I agree with you. The log system has to be as reliable as possible. But I still don't see an ideal solution.
Based on the discussion above, we have several moments, which should to be discussed to get logger in OP-TEE:

##### 1. single- VS multi- buffer approaches
1.1) Single buffer case means using spinlock over entire operation on buffer — while we copying data
(which size in common case is undeterminated), and updating meta-information.
So in this case we will spend more time under lock and more affect on synchronization and perfomance.
Update single atomic and then independently copy data to per-cpu buffer looks like less-intrusive way to organise logging.

1.2) Actually single- or multi- buffer approaches are very similar.
In multibuffers case we propose to generate the SGI, when a core has filled own ring buffer and buffer-switching is needed.
We propose to adjust the buffer count (N) by developers based on future system load.
But how to select N value? And who should do it?
In singlebuffer case we have the almost same questions. We need to generate SGI, when the buffer still not full.
If we don't do this, then we can't write next log entries to the buffer, because we have to be sure, that REE got all data.
Otherwise, we can overwrite the old log entries. Other words we have to do it, when OP-TEE fills half of the buffer?
Or 3/4 of the buffer? How to determine a threshold, when we need to generate SGI?

Both these approaches are not reliable, when we face with the worst case (all cores log something in TEE and the buffer(s)
is(are) almost full). Seems, that multibuffer case looks more reliable, because it reduces probability of this.

##### 2. Periodic polling the buffer(s) with a Linux timer VS flushing the buffer(s) when leaving SWd
Periodic polling with the timer looks redundant, that's why we really can flush the buffer(s), when leaving SWd,
but what about logging from secure interrupts? How mentioned above we can generate SGI every times,
when logging from IRQs. I think this will not affect performance, because logging from IRQs is rare case,
because interrupt handlers must be as fast as possible. I think that logging from an interrupt is only justified,
when we want to log some kind of error. But still, each developer decides on his own.

**Comment by jenswi-linaro** [comment]
> > How do you determine the load?
> 
> There is no exact way to determine the load. We can only assume the future load.
> Each developer decides for himself how much he will load the system with logs.
> Other words, one developer might use `DMSG()/IMSG()` very rare, but other one vice versa.
> We should be ready to any situations.

Exactly, it has to be dealt with at runtime. It doesn't have to be there from the beginning. Having some idea about right now might be good so the design can be extended in this direction.

> 
> > Another thing that also would be of great help would be to be able to mix the OP-TEE log
> > with the kernel log in the same timeline.
> 
> Great idea, thank you!
> We'll figure out how to implement it.
> 
> > My top priority is that it's reliable, if you don't get out the logs you need then it's useless
> > for debugging sudden crashes or panics.
> 
> I agree with you. The log system has to be as reliable as possible. But I still don't see an ideal solution.

We'll get there or close enough. :-)

> Based on the discussion above, we have several moments, which should to be discussed to get logger in OP-TEE:
> 
> ##### 1. single- VS multi- buffer approaches
> 1.1) Single buffer case means using spinlock over entire operation on buffer — while we copying data
> (which size in common case is undeterminated), and updating meta-information.
> So in this case we will spend more time under lock and more affect on synchronization and perfomance.
> Update single atomic and then independently copy data to per-cpu buffer looks like less-intrusive way to organise logging.

Based on experience with the current log framework which holds a lock for magnitudes of longer time this hasn't been a problem. So this is not a critical feature. We could make the design extendable in this direction later on.

> 
> 1.2) Actually single- or multi- buffer approaches are very similar.
> In multibuffers case we propose to generate the SGI, when a core has filled own ring buffer and buffer-switching is needed.
> We propose to adjust the buffer count (N) by developers based on future system load.
> But how to select N value? And who should do it?
> In singlebuffer case we have the almost same questions. We need to generate SGI, when the buffer still not full.
> If we don't do this, then we can't write next log entries to the buffer, because we have to be sure, that REE got all data.
> Otherwise, we can overwrite the old log entries. Other words we have to do it, when OP-TEE fills half of the buffer?
> Or 3/4 of the buffer? How to determine a threshold, when we need to generate SGI?
> 
> Both these approaches are not reliable, when we face with the worst case (all cores log something in TEE and the buffer(s)
> is(are) almost full). Seems, that multibuffer case looks more reliable, because it reduces probability of this.

I disagree, in fact to me it seems to be the opposite. A single buffer make better use of the memory so it takes a little longer before it's exhausted.

> 
> ##### 2. Periodic polling the buffer(s) with a Linux timer VS flushing the buffer(s) when leaving SWd
> Periodic polling with the timer looks redundant, that's why we really can flush the buffer(s), when leaving SWd,
> but what about logging from secure interrupts? How mentioned above we can generate SGI every times,
> when logging from IRQs. I think this will not affect performance, because logging from IRQs is rare case,
> because interrupt handlers must be as fast as possible. I think that logging from an interrupt is only justified,
> when we want to log some kind of error. But still, each developer decides on his own.

I think we need to forget SGIs at this stage. We currently don't have support in OP-TEE for that. We'll get it at some stage in some configurations, but there's no point in trying to force it here. Some polling will be needed until then, it should preferably be done inside tee-supplicant since I guess that's where actual processing will be done.

So we must make sure that there's room enough for logging in interrupt handlers and other sections where RPC isn't permitted or even possible since we have no way of notifying normal world that there's work to be done. We're also hogging the CPU and perhaps no other is available so Normal world can only process the buffer once we're past this section. Let's call this non-blocking logging.

In a normal thread state where normal world can be notified, what shall be done when the buffer is full? We could make an RPC which doesn't return until a part of the buffer has been emptied and try again. If we set the threshold at 75% of the buffer there should be plenty of room for non-blocking logging. If blocking isn't acceptable in some configurations we may need a config variable for that, but perhaps we can wait with that until it's a real problem.

I'd like to start with something that is as simple as possible, but extensible. ABIs should be prepared for this. Let's say that we add an RPC to register a shared memory buffer as a log buffer. Tee-supplicant will then know to check that buffer for logs. If there's another RPC register shared memory it may fail at this stage, but later with support for multiple buffer it will succeed. For tee-supplicant it doesn't matter which core is writing in which buffer, it will just pull out the logs from all known buffers.

What buffer size to start with? 16Kb seems reasonable to me. We can make this configurable if you think it's important. Keep in mind that the logging should work with any buffer size. Two degradations can occur with a too small buffer, normal logging blocks more often and non-blocking logging sometimes needs to drop logs.

**Comment by anisyanka** [comment]
> I'd like to start with something that is as simple as possible, but extensible.

Ok, I agree.
Let's do the development in two steps.

#### Stage 1. Simple implementation. Non-blocking logging.
  - Add a new RPC to register a shared memory buffer as a log buffer.
    For now we will allow to register only one log buffer.
  - Add a new supplicant thread which will pull out the logs from all known buffers.
  - Add a new RPC to trigger NWd to flush the buffers.

#### Stage 2. Improving the simple implementation.
 - Allow to register more than one log buffer with the help of the RPC.
 - Add SGI support in OPTEE.
 - Move polling to the OPTEE kernel driver.
 - Add a feature to mix optee log with the kernel log in the same timeline. (optional feature).
 - Add a script to sort SWd logs if several buffers are used.  (optional feature).

If I haven't forgotten anything, we can temporarily freeze the discussion and
start development from stage 1 step by step. As soon as it's ready, I will open RFC pull requests.

**Comment by jenswi-linaro** [comment]
Sounds good.
