### ISSUE TITLE
[DOC] Porting guide

### ISSUE THREAD

**Issue by maroueneboubakri** [OP-TEE/optee_os#4231]
Hi,

Is there a document which helps porting OP-TEE to another architecture  (not ARM) ? 
Thank you :) 

Regards
Maro

**Comment by jenswi-linaro** [comment]
I'm afraid not. Which architecture do you have in mind?

**Comment by maroueneboubakri** [comment]
@jenswi-linaro  Thank you for your quick reply, the arch is RISC-V.

**Comment by jenswi-linaro** [comment]
Do you intend to run it on a dedicated CPU or does RISC-V have some suitable special privilege level?

**Comment by maroueneboubakri** [comment]
We are experimenting both use-cases.  RISC-V has 4 privilege mode. 
To enable TEE, the hardware should has at least a user mode and privileged mode. 
The plan is to run seL4 on the machine mode (to run as a Secure Monitor) and in top of that we could have a Linux and/or OP-TEE running in the supervisor mode. We could have a physical memory speration between Linux and OP-TEE. So, running OP-TEE like on a dedicated CPU is fine for us as a starting point. If there is any  useful documentation that would be highly appreciated.

**Comment by jenswi-linaro** [comment]
The seL4 setup would be similar to the EL3 setup used in Armv8, at least from operating system point of view.
The documentation we have is available at https://optee.readthedocs.io/en/latest/ . Perhaps you've already seen that.
Since we only have OP-TEE on Arm platforms today what goes into `/core` versus `/core/arch/arm` is not very clear. I suspect that quite a bit could be moved from `/core/arch/arm` to `/core`, but in some cases we'd need to copy only portions of files.

By the way, do you think it would be possible to run it all on QEMU, the full package with seL4, OP-TEE and Linux?

**Comment by jforissier** [comment]
> Since we only have OP-TEE on Arm platforms today

Someone mentioned this to me a while ago, but it doesn't seem to be maintained recently: https://01.org/op-tee-ia, https://github.com/op-tee-ia.

**Comment by maroueneboubakri** [comment]
> The seL4 setup would be similar to the EL3 setup used in Armv8, at least from operating system point of view.
> The documentation we have is available at https://optee.readthedocs.io/en/latest/ . Perhaps you've already seen that.
> Since we only have OP-TEE on Arm platforms today what goes into `/core` versus `/core/arch/arm` is not very clear. I suspect that quite a bit could be moved from `/core/arch/arm` to `/core`, but in some cases we'd need to copy only portions of files.
> 
> By the way, do you think it would be possible to run it all on QEMU, the full package with seL4, OP-TEE and Linux?

It is feasible since there is a full RISC-V support on QEMU, but we need to think how seL4 could be used to manage RISC-V PMP entries, and dispatch between Linux and OP-TEE. We could forget about seL4 for now and focus on OP-TEE.

**Comment by maroueneboubakri** [comment]
> > Since we only have OP-TEE on Arm platforms today
> 
> Someone mentioned this to me a while ago, but it doesn't seem to be maintained recently: https://01.org/op-tee-ia, https://github.com/op-tee-ia.

It seems that some reverse engineering skills are needed to understand what should be ported.
But I think having an architecture porting guide. Do you think that we could start a draft on that ?

**Comment by jenswi-linaro** [comment]
> > The seL4 setup would be similar to the EL3 setup used in Armv8, at least from operating system point of view.
> > The documentation we have is available at https://optee.readthedocs.io/en/latest/ . Perhaps you've already seen that.
> > Since we only have OP-TEE on Arm platforms today what goes into `/core` versus `/core/arch/arm` is not very clear. I suspect that quite a bit could be moved from `/core/arch/arm` to `/core`, but in some cases we'd need to copy only portions of files.
> > By the way, do you think it would be possible to run it all on QEMU, the full package with seL4, OP-TEE and Linux?
> 
> It is feasible since there is a full RISC-V support on QEMU, but we need to think how seL4 could be used to manage RISC-V PMP entries, and dispatch between Linux and OP-TEE. We could forget about seL4 for now and focus on OP-TEE.

That's good, it means that it will be easier to check the we don't break things. Back to the OP-TEE part. You'll need to replicate more or less everything from `/core/arch/arm` into `/core/arch/riscv`. During that process you may find things that would make more sense to have directly under `/core` as architecture independent code.

I think you should try to keep the code structure and everything under `/core/arch/riscv` similarly organized as under `/core/arch/arm`. This will make it easier to identify and extract common code later on. Another advantage is that those of us who are familiar with Arm will not become completely lost, it will also make it easier to keep consistent documentation.

Then there's the protocol used to communicate with normal world (Linux). I think it would be good to stay as close as possible to what we're using today, that would allow you to reuse almost the entire driver just replacing the smc call with the Risc-V counterpart.

For the architecture porting guide, what level of details are you expecting? I guess it's something that can be filled in while doing this exercise.

**Comment by maroueneboubakri** [comment]
Thanks @jenswi-linaro, It seems that an effort is needed to sort-out common code.
Do you think that the best approach is to create a fork like what Intel did or create a PR here and start adding support step-by-step ?

**Comment by jenswi-linaro** [comment]
PRs here to add support step by step would be the best, or you'll risk a permanent fork or difficult rebasing.
