### ISSUE TITLE
GDB / GCC / QEMU: TA debugging with code built with GCC 9.2 doesn't always work

### ISSUE THREAD

**Issue by jbech-linaro** [OP-TEE/optee_os#4233]
I'm preparing a deck and demo(s) for the Linaro OP-TEE monthly meeting taking place later this week. When cross checking my various use cases I noticed that optee_example TA's triggers my breakpoints, but not the TA's in optee_test. After a rather long debug/bisect session it seems like the problem is narrowed down to the GCC 8.3 vs 9.2.

OP-TEE Version | Manifest | GCC/GDB | OK/NOK | Comment 
------------ | ------------- | ------------- | ------------- | -------------
tip/master | QEMU v7 | 9.2 | NOK | `TA_InvokeCommandEntryPoint` not triggered (xtest TA), `info symbol <address>` gives weird offset (+356). But the same function triggers if I'm running optee_example TA's.
3.8 release | QEMU v7 |  8.3 | OK | Breakpoint triggered (`info symbol <address>` gives `TA_InvokeCommandEntryPoint+16`)
3.10 release | QEMU v7 |  8.3 | OK | Breakpoint triggered (`info symbol <address>` gives `TA_InvokeCommandEntryPoint+16`)
3.11 release | QEMU v7 |  9.2 | NOK | `TA_InvokeCommandEntryPoint` not triggered (xtest TA), `info symbol <address>` gives weird offset (+356). But the same function triggers if I'm running optee_example TA's.
tip/master | QEMU v7 |  8.3 | OK | Buildroot and build.git stepped down so we can build with GCC 8.3. Breakpoint triggered (`info symbol <address>` gives `TA_InvokeCommandEntryPoint+16`)

The issue has been replicated on a second computer and Jens as well has been able to replicate the issue. Right now we don't have any good why we're seeing this issue. We suspect TA size might affect it, since optee_example TA's are rather small compared to the ones in xtest (crypt is the one I've been using for my tests).

Created this issue so we track this somewhere and to expose it to more people who might facing this issue or who might understand the cause for it.

**Comment by jenswi-linaro** [comment]
It seems that the offset is gdb trying to skip the function prologue. I suspect that it's around here it happens:
https://github.com/bminor/binutils-gdb/blob/b7bbf3c81afce9721f602cdecceac8124beeb421/gdb/symtab.c#L3988-L4008

For GCC 9 https://gcc.gnu.org/gcc-9/changes.html mentions `-ftree-switch-conversion` and it looks like that could relate to this. Any way, if `b my_function` give a too large offset, try ` b *(my_function)` instead.

**Comment by jbech-linaro** [comment]
FYI, just tried with the [10.2 version](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads) and breakpoints seems to trigger as expected again in that version. Hence https://github.com/OP-TEE/build/pull/491.
