### ISSUE TITLE
Clang, pager, ASLR: core crash during xtest 1013

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#4234]
Master branch with https://github.com/OP-TEE/optee_os/pull/4229, Clang 11, pager enabled on QEMUv8. Build command: `make COMPILER=clang CFG_WITH_PAGER=y run`.

```
$ xtest 1013
...
E/TC:0   Core prefetch-abort at address 0xee7ca508 (translation fault)
E/TC:0    esr 0x86000007  ttbr0 0x0e125000   ttbr1 0x00000000   cidr 0x0
E/TC:0    cpu #0          cpsr 0x800003c4
E/TC:0    x0  0000000000000000 x1  0000000000000000
E/TC:0    x2  0000000000000001 x3  0000008000000000
E/TC:0    x4  00000000ee8083d8 x5  00000000ee808448
E/TC:0    x6  00000000ee788f52 x7  0000000000000004
E/TC:0    x8  0000000000000000 x9  00000000ee78d8a0
E/TC:0    x10 0000000000000004 x11 0000000000000001
E/TC:0    x12 0000000000000000 x13 0000000000000001
E/TC:0    x14 0000000000000000 x15 00000000ee808690
E/TC:0    x16 00000000ee8083e0 x17 00000000ee788f08
E/TC:0    x18 0000000000000020 x19 00000000ee78caa0
E/TC:0    x20 00000000ee8083e0 x21 00000000ffff0005
E/TC:0    x22 00000000ffff0000 x23 000000003d821800
E/TC:0    x24 0000000000000000 x25 0000000000000000
E/TC:0    x26 0000000000000000 x27 00000000ee7c59a3
E/TC:0    x28 00000000ee7b4440 x29 00000000ee8083f0
E/TC:0    x30 00000000ee7ca508 elr 00000000ee7ca508
E/TC:0    sp_el0 00000000ee79a930
E/TC:0   TEE load address @ 0xee775000
E/TC:0   Core prefetch-abort at address 0xee7ca508 .debug_loc+349448 (translation fault)
E/TC:0   Call stack:
E/TC:0    0x00000000ee7ca508 thread_rpc at optee_os/core/arch/arm/kernel/thread_optee_smc_a64.S:197
E/TC:0   Panic 'abort outside thread context' at core/arch/arm/kernel/abort.c:532 <abort_handler>
E/TC:0   TEE load address @ 0xee775000
E/TC:0   Call stack:
E/TC:0    0x00000000ee77b6ec print_kernel_stack at optee_os/core/arch/arm/kernel/unwind_arm64.c:80
E/TC:0    0x00000000ee781508 __do_panic at optee_os/core/kernel/panic.c:26
E/TC:0    0x00000000ee77a4e0 abort_handler at optee_os/core/arch/arm/kernel/abort.c:532
E/TC:0    0x00000000ee77827c el1_sync_abort at optee_os/core/arch/arm/kernel/thread_a64.S:732
```

I noticed that `__thread_enter_user_mode` is **not** in `unpaged.o` although it should be (`DECLARE_KEEP_PAGER __thread_enter_user_mode` in `core/arch/arm/kernel/thread_a64.S`).
```
$ nm out/arm/core/unpaged.o | grep __thread_enter_user_mode
0000000000013004 D ____keep_pager___thread_enter_user_mode
```

With GCC 9.2 for comparison:
```
$ nm out/arm/core/unpaged.o | grep __thread_enter_user_mode
0000000000000004 N ____keep_pager___thread_enter_user_mode
0000000000000380 T __thread_enter_user_mode
```

**Comment by jenswi-linaro** [comment]
Maybe there's some problem with how clang garbage collects while linking.

**Comment by jforissier** [comment]
> Maybe there's some problem with how clang garbage collects while linking.

Possibly, yes. Forcing the symbols into `unpaged_entries.txt` directly (instead of via the `____keep_pager_*` entries) makes the issue go away. I.e., this patch:
```diff
 diff --git a/core/arch/arm/kernel/link.mk b/core/arch/arm/kernel/link.mk
index 4ce1daad..15075fcb 100644
--- a/core/arch/arm/kernel/link.mk
+++ b/core/arch/arm/kernel/link.mk
@@ -48,7 +48,7 @@ cleanfiles += $(link-out-dir)/unpaged_entries.txt
 $(link-out-dir)/unpaged_entries.txt: $(link-out-dir)/all_objs.o
        @$(cmd-echo-silent) '  GEN     $@'
        $(q)$(NMcore) $< | \
-               $(AWK) '/ ____keep_pager/ { printf "-u%s ", $$3 }' > $@
+               $(AWK) '/ ____keep_pager/ { printf "-u%s ", $$3; gsub(/____keep_pager_/,"",$$3); printf "-u%s ", $$3 }' > $@

 unpaged-ldargs = -T $(link-script-dummy) --no-check-sections --gc-sections
 unpaged-ldadd := $(objs) $(link-ldadd) $(libgcccore)
```

**Comment by jenswi-linaro** [comment]
I don't see any harm in doing so instead. I suppose we need to do the same thing for the `____keep_init_*` entries.

By the way, did it work for any of the `____keep_pager_*` symbols?

**Comment by jforissier** [comment]
> I don't see any harm in doing so instead. I suppose we need to do the same thing for the `____keep_init_*` entries.

Not really needed, the symbols are where expected, but for consistency perhaps.

> By the way, did it work for any of the `____keep_pager_*` symbols?

Yes, it somewhat works in C files, for example `mobj_reg_shm_get_pa` is in `unpaged.o` when `DECLARE_KEEP_PAGER(mobj_reg_shm_get_pa);` is used but is not present otherwise. Other symbols are there with or without the declaration, which is a bit weird but perhaps they are pulled due to subtle dependencies.

The issue is with assembler files it seems: `__thread_enter_user_mode` and `thread_rpc` are not in `unpaged.o` although they are declared "keep" and produce a `____keep_pager_*` symbol. What is more surprising, the other assembly symbols that have `DECLARE_KEEP_PAGER()` are included even without a "keep" declaration: `cpu_on_handler`, `thread_init_vbar` and `thread_vector_table`. I'm trying to understand what is different and perhaps write a reproducer.

**Comment by jenswi-linaro** [comment]
> > I don't see any harm in doing so instead. I suppose we need to do the same thing for the `____keep_init_*` entries.
> 
> Not really needed, the symbols are where expected, but for consistency perhaps.

Not needed at this time, but perhaps a problem waiting to surface.

> 
> > By the way, did it work for any of the `____keep_pager_*` symbols?
> 
> Yes, it somewhat works in C files, for example `mobj_reg_shm_get_pa` is in `unpaged.o` when `DECLARE_KEEP_PAGER(mobj_reg_shm_get_pa);` is used but is not present otherwise. Other symbols are there with or without the declaration, which is a bit weird but perhaps they are pulled due to subtle dependencies.
> 
> The issue is with assembler files it seems: `__thread_enter_user_mode` and `thread_rpc` are not in `unpaged.o` although they are declared "keep" and produce a `____keep_pager_*` symbol. What is more surprising, the other assembly symbols that have `DECLARE_KEEP_PAGER()` are included even without a "keep" declaration: `cpu_on_handler`, `thread_init_vbar` and `thread_vector_table`. I'm trying to understand what is different and perhaps write a reproducer.

It seems there's an underlying issue that we don't see.

**Comment by jforissier** [comment]
> It seems there's an underlying issue that we don't see.

Well, I had to add debug traces to `ld.lld` to finally understand why the `.text.__thread_enter_user_mode` section would be garbage-collected despite the reference introduced by `DECLARE_KEEP_PAGER __thread_enter_user_mode` :open_mouth: Luckily Clang is not that hard to build, you just have to be patient because there are 3000+ C++ files to compile... Anyway, see https://github.com/OP-TEE/optee_os/pull/4237.

I am quite happy with the above fix, but I am thinking perhaps we can simplify the `DECLARE_KEEP_*` mechanism a bit and not depend on the dependency (!) of `__keep_*_<symbol>` on `<symbol>`. I will give it a try tomorrow.

**Comment by jforissier** [comment]
> I am quite happy with the above fix, but I am thinking perhaps we can simplify the `DECLARE_KEEP_*` mechanism a bit and not depend on the dependency (!) of `__keep_*_<symbol>` on `<symbol>`. I will give it a try tomorrow.

Quick follow-up on this: my idea didn't work because `DECLARE_KEEP_*` can be applied to static variables, in other words: local symbols. Adding `-u<symbol>` to the link inserts `<symbol>` as an undefined symbol in the symbol table at the beginning of the link phase, then the linker will try to resolve it in the object files; it will not find anything if `<symbol>` only points to one or more local symbols.

Closing this issue since the crash has been resolved.
