### ISSUE TITLE
Discussion on OP-TEE GPIO Direction 

### ISSUE THREAD

**Issue by manishtomar1** [OP-TEE/optee_os#4238]
GPIO direction is defined in core/include/gpio.h as below:
enum gpio_dir {
    GPIO_DIR_OUT ,
    GPIO_DIR_IN
};

But with NXP SoC, the direction is opposite to that of already defined gpio dir enum:
0-31
DRn Direction. Indicates whether a pin is used as an input or an output.
00000000000000000000000000000000b - The corresponding pin is an input.
00000000000000000000000000000001b - The corresponding pin is an output.

For our SoCs, we defined the gpio directions as below:
enum gpio_test_direction {
        GPIO_TEST_DIR_IN,
        GPIO_TEST_DIR_OUT
};

But it is not good to keep 2 enums for same purpose, so we thought of discussing this on forum.

To comply with the generic gpio.h (from core/include/gpio.h), we have two proposals:

1. Proposal to change the generic enum definition
    - Upstream changes in generic header file
    - No Code changes required for NXP SoC

2. Use existing generic gpio.h (Code changes required in NXP SoC patch support)
    - Write wrapper function for direction change API
   
Please suggest which proposal is well adaptable?

**Comment by vchong** [comment]
Iirc this was done to mirror TF-A [1]. Don't you have issues on TF-A as well? Is the reverse condition specific to your platform only? All NXP platforms? Other platforms too?

@sandeepbrcm Would you like to comment for your platform as well?

[1] https://github.com/ARM-software/arm-trusted-firmware/blob/master/include/export/drivers/gpio_exp.h#L12

**Comment by vchong** [comment]
So I took a deeper look into this and it doesn't seem like an issue. Both `pl061_gpio.c` and `bcm_gpio.c` have the same 'reversed' register setting as yours, i.e. 0 for input and 1 for output, and the function to set direction is, in pseudo code form:

```
if (dir == GPIO_DIR_OUT)
	//set the appropriate register bit
else
	//clear the appropriate register bit
```

For setting and clearing a bit, usually an enum is not defined but rather the BIT() macro is used instead. If you prefer to or must use an enum for your platform then you might have to go with proposal #2.
