### ISSUE TITLE
setup_fvp_optee.sh Issue

### ISSUE THREAD

**Issue by crispy-penguin** [OP-TEE/optee_os#424]
Hi everyone, 
I have been trying to install setup_fvp_optee script for last 12 hours and still no luck. I have installed new distro of Debian only to see if something on my previous distro was wrong, but I still get the same error. The error occures while running tb_conv.c in function ‘test_BigInt_getsetOctetString’. 
Thanks for help,
Crispy
Here is the console dump. 

_________________________________________________________________
 CC      /root/devel/fvp_optee/out/optee_test/ta/os_test/ta_entry.o
  CC      /root/devel/fvp_optee/out/optee_test/ta/os_test/tb_addsub.o
  CC      /root/devel/fvp_optee/out/optee_test/ta/os_test/tb_cmp.o
  CC      /root/devel/fvp_optee/out/optee_test/ta/os_test/tb_conv.o
tb_conv.c: In function ‘test_BigInt_getsetOctetString’:
tb_conv.c:114:8: error: passing argument 2 of ‘TEE_BigIntConvertFromOctetString’ discards ‘const’ qualifier from pointer target type [-Werror]
  res = TEE_BigIntConvertFromOctetString(a, os1, sizeof(os1), 1);
        ^
In file included from /root/devel/fvp_optee/optee_os/out/arm-plat-vexpress/export-user_ta/include/tee_internal_api.h:32:0,
                 from ./include/testframework.h:31,
                 from tb_conv.c:28:
/root/devel/fvp_optee/optee_os/out/arm-plat-vexpress/export-user_ta/include/tee_api.h:365:12: note: expected ‘uint8_t *’ but argument is of type ‘const uint8_t *’
 TEE_Result TEE_BigIntConvertFromOctetString(TEE_BigInt *dest,
            ^
tb_conv.c:123:8: error: passing argument 2 of ‘TEE_BigIntConvertFromOctetString’ discards ‘const’ qualifier from pointer target type [-Werror]
  res = TEE_BigIntConvertFromOctetString(b, os3, sizeof(os3), 1);
        ^
In file included from /root/devel/fvp_optee/optee_os/out/arm-plat-vexpress/export-user_ta/include/tee_internal_api.h:32:0,
                 from ./include/testframework.h:31,
                 from tb_conv.c:28:
/root/devel/fvp_optee/optee_os/out/arm-plat-vexpress/export-user_ta/include/tee_api.h:365:12: note: expected ‘uint8_t *’ but argument is of type ‘const uint8_t *’
 TEE_Result TEE_BigIntConvertFromOctetString(TEE_BigInt *dest,
            ^
  CC      /root/devel/fvp_optee/out/optee_test/ta/os_test/tb_div.o
  CC      /root/devel/fvp_optee/out/optee_test/ta/os_test/tb_fmm.o
cc1: all warnings being treated as errors
/root/devel/fvp_optee/optee_os/out/arm-plat-vexpress/export-user_ta/mk/compile.mk:141: recipe for target '/root/devel/fvp_optee/out/optee_test/ta/os_test/tb_conv.o' failed
make[2]: *** [/root/devel/fvp_optee/out/optee_test/ta/os_test/tb_conv.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/root/devel/fvp_optee/optee_test/ta/os_test'
Makefile:37: recipe for target 'ta' failed
make[1]: *** [ta] Error 2
make[1]: Leaving directory '/root/devel/fvp_optee/optee_test/ta'
Makefile:27: recipe for target 'ta' failed
make: *** [ta] Error 2
make: Leaving directory '/root/devel/fvp_optee/optee_test'

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

  WARNING: Symbol version dump ./Module.symvers
           is missing; modules will have no dependencies and modversions.

  CC [M]  /root/devel/fvp_optee/optee_linuxdriver/armtz/tee_tz_drv.o
In file included from <command-line>:0:0:
././include/linux/kconfig.h:4:32: fatal error: generated/autoconf.h: No such file or directory
 #include <generated/autoconf.h>
                                ^
compilation terminated.
scripts/Makefile.build:257: recipe for target '/root/devel/fvp_optee/optee_linuxdriver/armtz/tee_tz_drv.o' failed
make[2]: *** [/root/devel/fvp_optee/optee_linuxdriver/armtz/tee_tz_drv.o] Error 1
scripts/Makefile.build:402: recipe for target '/root/devel/fvp_optee/optee_linuxdriver/armtz' failed
make[1]: *** [/root/devel/fvp_optee/optee_linuxdriver/armtz] Error 2
Makefile:1380: recipe for target '_module_/root/devel/fvp_optee/optee_linuxdriver' failed
make: *** [_module_/root/devel/fvp_optee/optee_linuxdriver] Error 2
/root/devel/fvp_optee/update_rootfs.sh: line 4: cd: /root/devel/fvp_optee/gen_rootfs: No such file or directory
/root/devel/fvp_optee/update_rootfs.sh: line 5: gen_init_cpio: command not found
/root/devel/fvp_optee/build_device_tree_files.sh: line 4: /root/devel/fvp_optee/linux/scripts/dtc/dtc: No such file or directory
OP-TEE and FVP setup completed.

**Comment by pascal-brand-st-dev** [comment]
This comes from non-aligned versions between optee_os and optee_test. Rebasing on master on these 2 gits should solve your problem.

Indeed, we are currently changing the way environments are imported. We are now using android-like manifest and build. Please have a look at https://github.com/OP-TEE/manifest/blob/master/README.md. It will guide you to retrieve fvp environment using this new way. Please let us know if you still face issues with this new way of proceeding.

Note that setup scripts are obsolete, and will be removed soon.

**Comment by crispy-penguin** [comment]
Hi,
thanks for the reply. I have tried the android-like way, but no success so far.  While running "repo sync" curl is complaining about the URL. 
curl:  (22) The requested URL returned error : 404 Not found
Server does not provide clone.bundle; ignoring. 
This happens for every git project EXCEPT linaro-swg/soc_term (poject linux.git) (the big 947MB one).
Qemu download also works fine. 

But every other project ends with this error 
_________________________________________________________________________
Receiving objects: 100% (656/656), 1.17 MiB | 421.00 KiB/s, done.
Resolving deltas: 100% (386/386), done.
From https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux
   cbfe8fa..8400935  master     -> linux/master
Fetching projects:  81% (9/11)  Fetching project qemu.git
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring.
___________________________________________________________________________
I have noticed that https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux indeed  returns 404. 
I believe that https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git was the meant URL, but I am not sure. 
Any ideas what went wrong? 
Since I am using Qemu, the repo init I used was :
"repo init -u https.//github.com/OP-TEE/manifest.git -m default.xml"

**Comment by pascal-brand-st-dev** [comment]
Server does not provide clone.bundle; ignoring

I have the same warnings on my side, and they do not prevent me extracting all gits. Is this warning a "killer"?

**Comment by crispy-penguin** [comment]
My apologies, it is normal behaviour. I was missing some libraries, causing the qemu to crash. Android way works beautifully.
