### ISSUE TITLE
optee_os version dependency with kernel

### ISSUE THREAD

**Issue by vtcao297** [OP-TEE/optee_os#4245]
Hello optee maintainers,

Is there a version dependency between which version of OPTEE OS will work for which kernel?

We are currently running OPTEE v3.8 release and are in the process of trying to rebase our kernel to 5.10 LTS rc4 release and we are seeing a crash dump

[  OK  ] Started TEE Supplicant.
[   11.943583] optee: PTA_CMD_GET_DEVICES invoke function err: ffff0009
[   11.950168] ------------[ cut here ]------------
[   11.954807] WARNING: CPU: 1 PID: 33 at drivers/tee/optee/core.c:226 optee_bu8
[   11.954826] CPU: 1 PID: 33 Comm: kworker/1:1 Not tainted 5.10.0-rc4-intel-st1
[   11.980593] Hardware name: XXXXXXXXXXXXX
[   11.980614] Workqueue: optee_bus_scan optee_bus_scan
[   11.990366] pstate: 80400005 (Nzcv daif +PAN -UAO -TCO BTYPE=--)
[   11.996371] pc : optee_bus_scan+0x24/0x38
[   12.000380] lr : optee_bus_scan+0x14/0x38
[   12.004473] sp : ffffffc013a13da0
[   12.007786] x29: ffffffc013a13da0 x28: ffffffc0135a6000
[   12.014571] x27: ffffffc0138cbcd8 x26: ffffff84303415c8
[   12.019885] x25: 0000000000000000 x24: ffffff8433a81b18
[   12.025209] x23: 0000000000000000 x22: fffffffebfeb1800
] [   12.030523] x21: ffffff847f99bdc0 x20: ffffff84301f5400
[   12.035993] x19: ffffff8433a81b10 x18: 0000000000000002
[   12.041303] x17: 0000000000000000 x16: 0000000000000000
[   12.046622] x15: 0000000000000001 x14: 0000000
[   12.055668] x13: 00000000000001c6 x12: 0000000000000000
[   12.060982] x11: 0000000000000223 x10: 0000000000000960
[   12.066291] x9 : 0000000000000000 x8 : ffffff843036fb80
[   12.071607] x7 : ffffff8000000000 x6 : 0000000000000001
[   12.076939] x5 : ffffff843036fb00 x4 : ffffff847f99f6a0
[   12.082428] x3 : 0000000000242b01 x2 : ffffff843036f900
[   12.087741] x1 : aef04125fa9bcc00 x0 : 00000000ffffffea
[   12.093053] Call trace:
[   12.094450] systemd[1]: Starting Load Kernel Modules...
[   12.095512]  optee_bus_scan+0x24/0x38
[   12.104422]  process_one_work+0x1b4/0x470
[   12.104431]  worker_thread+0x4c/0x3f8
[   12.112127]  kthread+0x140/0x160
[   12.115371]  ret_from_fork+0x10/0x30
[   12.118946] ---[ end trace 8b613f10669cf2a2 ]---

**Comment by jenswi-linaro** [comment]
This is a warning and not a crash if I understand it correctly. It does look a bit scary and is excessive IMO, but it's only a way of reporting that the requested function (PTA_CMD_GET_DEVICES_SUPP) isn't compiled into OP-TEE. This was added in a later release. Perhaps @b49020 can give some more background.

**Comment by vtcao297** [comment]
yup this seems to be the case, i've identified the required cherry-picked patch to resolve the issue.  Thank you.

**Comment by dongvoduy** [comment]
Hi vtcao297,
Currently, I have the error same you.
Please ask for me how to I can fix the error. Thank you very much.
