### ISSUE TITLE
Optee output in the TA side on raspberry 3B

### ISSUE THREAD

**Issue by AnBacklights** [OP-TEE/optee_os#4246]
I'm applying optee into raspberry 3B. I want to see the output in the TA side (security world).How can i config?
On raspberry,I first run _tee-supplicant_ ,then I run my custom _CA_. Now I can only see the CA ouput,but can not see the TA output.

**Comment by jbech-linaro** [comment]
Hi, you shouldn't have to do anything. Just compile and run any TA that has prints enabled and it should show up on the UART. You can cross check the log level flags `CFG_TEE_TA_LOG_LEVEL`, if it's set to "1" (`cd optee_os && rgrep CFG_TEE_TA_LOG_LEVEL`), then raise to a more verbose level. I suggest 3 (`TRACE_DEBUG`).

**Comment by AnBacklights** [comment]
Thanks for your reply.I have got the output in the TA side.I will close this issue.
