### ISSUE TITLE
[RFC] Using __attribute__((constructor)) in OP-TEE core?

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#4250]
@etienne-lms

During the [Linaro SCMI meeting](https://collaborate.linaro.org/display/SCMI) today, a question was raised about the possible use of `__attribute__((constructor))` in OP-TEE. The use case would be the integration of an external library that uses the attribute. OP-TEE has [`<initcall.h>`](https://github.com/OP-TEE/optee_os/blob/3.11.0/core/include/initcall.h) for this purpose, but would it be possible to support the attribute in addition to initcalls?

I checked the code and thought about it. In fact it is already supported when `CFG_CORE_SANITIZE_KADDRESS=y`, but the problem is, constructors are run quite early in the boot sequence (`init_primary() -> init_runtime() -> init_asan() -> init_run_constructors()`). That's before the heap is initialized for instance. So there are not many things that can be done in such a constructor. And fundamentally, the meaning of "constructor" isn't well defined in this case since there is no `main()` function in OP-TEE.

So, all in all, I don't think it makes much sense unless we can clarify and resolve the potential conflict with ASAN.

**Comment by jenswi-linaro** [comment]
Thanks for the summary. I agree with your conclusion.

**Comment by etienne-lms** [comment]
Yes, thanks a lot @jforissier for investigating this.
From your description I also agree it would be quite confusing or hacky to support `constructor` attribute for early-but-not-that-early initialization sequences. We'll find another way to address this initcall issue when embedding SCP-firmware in OP-TEE Core.

Thanks again for the investigation and for creating this github Issue to serve as reference.

**Comment by jforissier** [comment]
@etienne-lms np, I'm closing this for now.
