### ISSUE TITLE
TZC DRAM region determination

### ISSUE THREAD

**Issue by rvdgracht** [OP-TEE/optee_os#4252]
Hi,

I'm trying to boot optee on my custom board but I've run into an issue.
My board has an imx6q processor which uses the full/maximum addressable memory space.
so in my case:
CFG_DRAM_BASE = 0x10000000
CFG_DDR_SIZE = 0xF0000000

However the tzc_auto_configure() routine in core/drivers/tzc380.c can't cope with that.
It's unable to properly divide my memory into regions.

Log output:
...
D/TC:0 0 call_initcalls:21 level 4 tee_fs_init_key_manager()
D/TC:0 0 call_initcalls:21 level 5 imx_configure_tzasc()
E/TC:0 0 assertion 'region < tzc.num_regions' failed at core/drivers/tzc380.c:182 <tzc_configure_region>
E/TC:0 0 Panic at core/kernel/assert.c:28 <_assert_break>
E/TC:0 0 TEE load address @ 0xfe000000
E/TC:0 0 Call stack:
E/TC:0 0  0xfe008051
E/TC:0 0  0xfe01412d
E/TC:0 0  0xfe013211
E/TC:0 0  0xfe010859
E/TC:0 0  0xfe010a53
E/TC:0 0  0xfe00df65
E/TC:0 0  0xfe015601
E/TC:0 0  0xfe03d543
E/TC:0 0  0xfe007d65
E/TC:0 0  0xfe03d5ad
E/TC:0 0  0xfe0001c0

I looked into this and found that for my soc:
tzc.addr_width = 32
tzc.num_regions = 8

The current implementation creates the following region map:
1) 0x10000000 - 0x7FFFFFFFF  ( 8 subregions with size 0x10000000 **with first one masked out/disabled**)
2) 0x80000000 - 0xBFFFFFFF ( region_size = 0x40000000 )
3) 0xC0000000 - 0xDFFFFFFF ( region_size = 0x20000000 )
4) 0xE0000000 - 0xEFFFFFFF ( region_size = 0x10000000 )
5) 0xF0000000 - 0xF7FFFFFF  ( region_size = 0x08000000 )
6) 0xF8000000 - 0xFBFFFFFF  ( region_size = 0x04000000 )
7) 0xFC000000 - 0xFDFFFFFF  ( region_size = 0x02000000 )
8) 0xFE000000 - 0xFEFFFFFF  ( region_size = 0x01000000 )
-- ASSERT --

It can never get to 0xFFFFFFFF (CFG_DRAM_BASE + CFG_DDR_SIZE)

I'm not accustomed with the TZC and certainly no expert, so please
correct me If I'm wrong here, but can't we accomplish the proper
setup like so? 
1) 0x10000000 - 0x1FFFFFFF ( region_size = 0x10000000 )
2) 0x20000000 - 0x3FFFFFFF ( region_size = 0x20000000 )
3) 0x40000000 - 0x7FFFFFFF ( region_size = 0x40000000 )
4) 0x80000000 - 0xFFFFFFF ( region_size = 0x80000000 )

**Comment by Emantor** [comment]
> I looked into this and found that for my soc:
> tzc.addr_width = 32
> tzc.num_regions = 8
> 
> The current implementation creates the following region map:
> ```
>     1. 0x10000000 - 0x7FFFFFFFF  ( 8 subregions with size 0x10000000 **with first one masked out/disabled**)

This looks weird, subregions for `0x100000000` are 512MB, so we shouldn't use a subregions here because we will not cover `0x10000000-0x20000000`, however your map indicates otherwise.

>     2. 0x80000000 - 0xBFFFFFFF ( region_size = 0x40000000 )
>     3. 0xC0000000 - 0xDFFFFFFF ( region_size = 0x20000000 )
>     4. 0xE0000000 - 0xEFFFFFFF ( region_size = 0x10000000 )
>     5. 0xF0000000 - 0xF7FFFFFF  ( region_size = 0x08000000 )
>     6. 0xF8000000 - 0xFBFFFFFF  ( region_size = 0x04000000 )
>     7. 0xFC000000 - 0xFDFFFFFF  ( region_size = 0x02000000 )
>     8. 0xFE000000 - 0xFEFFFFFF  ( region_size = 0x01000000 )
>        -- ASSERT --
> ```


We probably reset the pow after finding a region. This way we can search for the region size again with a different start address.

What the code should probably do is:
```
0x10000000-0x80000000 (region size 2GiB, first subregion disabled)
0x80000000-0xfffffffffffff (region size 2GiB, last subregion disabled)
… (configuration for secure world follows here)
```

> It can never get to 0xFFFFFFFF (CFG_DRAM_BASE + CFG_DDR_SIZE)
> 
> I'm not accustomed with the TZC and certainly no expert, so please
> correct me If I'm wrong here, but can't we accomplish the proper
> setup like so?

The code tries to apply the subregion principle as well, thats why your first region size is bigger.

**Comment by Emantor** [comment]
Please try https://github.com/OP-TEE/optee_os/pull/4253

**Comment by rvdgracht** [comment]
> This looks weird, subregions for 0x100000000 are 512MB, so we shouldn't use a subregions here because we will not cover 0x10000000-0x20000000, however your map indicates otherwise.

At that time pow = 31, region_size = 0x80000000 and address = 0x10000000

since (address % region_size) = 0x10000000 the code attempts to cover the area with subregions.
sub_region_size = region_size / 8 = 0x10000000 (256M)

sub_address = (address / region_size) * region_size;
that makes sub_address = 0; 
And because (sub_address + area <= address) is true, the first subregion is disabled.

**Comment by rvdgracht** [comment]
> Please try #4253

Looks good!
Now 2 regions are created by the 'cover area using severla subregions' routing.
Only the second region has a disabled subregion (the last one) which is as expected.

D/TC:0 0 tzc_dump_state:337 TZC380 configuration:
D/TC:0 0 tzc_dump_state:339 security_inversion_en 0
D/TC:0 0 tzc_dump_state:345 
D/TC:0 0 tzc_dump_state:346 region 1
D/TC:0 0 tzc_dump_state:349 region_base: 0x0000000010000000
D/TC:0 0 tzc_dump_state:351 region sp: f
D/TC:0 0 tzc_dump_state:353 region size: 1e
D/TC:0 0 tzc_dump_state:345 
D/TC:0 0 tzc_dump_state:346 region 2
D/TC:0 0 tzc_dump_state:349 region_base: 0x0000000090000000
D/TC:0 0 tzc_dump_state:351 region sp: f
D/TC:0 0 tzc_dump_state:353 region size: 1e

**Comment by Emantor** [comment]
> > Please try #4253
> 
> Looks good!
> […]

I have turned the Draft PR into a full PR, you can provide your `Tested-by:` if you want too :+1:
