### ISSUE TITLE
TEE_CopyOperation issue fails the TEE_ALG_AES_CTS cipher

### ISSUE THREAD

**Issue by hejunzju** [OP-TEE/optee_os#4263]
I tested TEE_CopyOperation() based on xtest for ciphers nowadays (see xtest patch in the end).

(don't know why TEE_CopyOperation() call was not applied to test cases for algorithms other than digest and MAC in the original xtest code, though GP hasn't limited TEE_CopyOperation() to digest/MAC only in the TEE Internal API Spec...)

It is found the TEE_ALG_AES_CTS cipher always failed in decrypting the last two blocks on the dst ctx then, while encryption is always fine. After dug the TEE code for a bit deeper, I found the problem exists in the following function:
    optee_os/core/crypto/aes-cts.c:cts_copy_state().

Where, the operation mode was not copied, which was set in the TEE_CipherInit() function. As a result, the dst ctx lived with a default operation mode of 0, that is TEE_MODE_ENCRYPT. This well explains the problem mentioned above.

Moreover, I find there is something else missing too in the optee_os/core/tee/tee_svc_cryp.c:syscall_cryp_stat_copy() function. That is the ctx_finalize of the tee_cryp_state structure is not copied. The ctx_finalize pointer is supposed to be set by TEE_CipherInit(), TEE_AEInit(), ...
The good news is a NULL ctx_finalize would not make much difference for now as either crypto_cipher_final() or crypto_authenc_final() is NOP in the present implementation. But, thing might change if people uses his own crypto implementation for instead.

Absolutely, all these issues could be mitigated by placing one TEE_CipherInit()/TEE_AEInit() call on to the dst ctx in prior to the TEE_CopyOperation() call. However, neither document nor sample code says that yet. And besides, this method would introduce additional restriction on to the TEE_CopyOperation() when using it for cipher, AE, and probable others so that people tends to dislike it. So, I'd wish we could fix them completely in the TEE_CopyOperation() function. How do you think?

```
diff --git a/host/xtest/regression_4000.c b/host/xtest/regression_4000.c
index a061dc1..24b20ac 100644
--- a/host/xtest/regression_4000.c
+++ b/host/xtest/regression_4000.c
@@ -2593,11 +2593,12 @@ static void xtest_tee_test_4003(ADBG_Case_t *c)
 {
 	TEEC_Session session = { };
 	TEE_OperationHandle op = TEE_HANDLE_NULL;
+	TEE_OperationHandle op2 = TEE_HANDLE_NULL;
 	TEE_ObjectHandle key1_handle = TEE_HANDLE_NULL;
 	TEE_ObjectHandle key2_handle = TEE_HANDLE_NULL;
 	uint8_t out[2048] = { };
 	size_t out_size = 0;
-	size_t out_offs = 0;
+	size_t out_offs = 0, out_offs2 = 0;
 	uint32_t ret_orig = 0;
 	size_t n = 0;
 
@@ -2649,6 +2650,12 @@ static void xtest_tee_test_4003(ADBG_Case_t *c)
 				op_key_size)))
 			goto out;
 
+		if (!ADBG_EXPECT_TEEC_SUCCESS(c,
+			ta_crypt_cmd_allocate_operation(c, &session, &op2,
+				ciph_cases[n].algo, ciph_cases[n].mode,
+				op_key_size)))
+			goto out;
+
 		if (!ADBG_EXPECT_TEEC_SUCCESS(c,
 			ta_crypt_cmd_allocate_transient_object(c, &session,
 				ciph_cases[n].key_type, key_size,
@@ -2718,8 +2725,13 @@ static void xtest_tee_test_4003(ADBG_Case_t *c)
 			ADBG_EXPECT_COMPARE_UNSIGNED(c, out_size, ==,
 				ciph_cases[n].in_incr);
 
+		if (!ADBG_EXPECT_TEEC_SUCCESS(c,
+			ta_crypt_cmd_copy_operation(c, &session, op2, op)))
+			goto out;
+
 		out_offs += out_size;
 		out_size = sizeof(out) - out_offs;
+		out_offs2 = out_offs;
 
 		if (!ADBG_EXPECT_TEEC_SUCCESS(c,
 			ta_crypt_cmd_cipher_do_final(c, &session, op,
@@ -2734,10 +2746,31 @@ static void xtest_tee_test_4003(ADBG_Case_t *c)
 		(void)ADBG_EXPECT_BUFFER(c, ciph_cases[n].out,
 					 ciph_cases[n].out_len, out, out_offs);
 
+		/* test on the copied op2 */
+		out_size = sizeof(out) - out_offs2;
+
+		if (!ADBG_EXPECT_TEEC_SUCCESS(c,
+			ta_crypt_cmd_cipher_do_final(c, &session, op2,
+				ciph_cases[n].in + ciph_cases[n].in_incr,
+				ciph_cases[n].in_len - ciph_cases[n].in_incr,
+				out + out_offs2,
+				&out_size)))
+			goto out;
+
+		out_offs2 += out_size;
+
+		(void)ADBG_EXPECT_BUFFER(c, ciph_cases[n].out,
+					 ciph_cases[n].out_len, out, out_offs2);
+
+
 		if (!ADBG_EXPECT_TEEC_SUCCESS(c,
 			ta_crypt_cmd_free_operation(c, &session, op)))
 			goto out;
 
+		if (!ADBG_EXPECT_TEEC_SUCCESS(c,
+			ta_crypt_cmd_free_operation(c, &session, op2)))
+			goto out;
+
 		Do_ADBG_EndSubCase(c, NULL);
 	}
 out:
```

**Comment by jenswi-linaro** [comment]
Thanks for the report @hejunzju, easy to follow. I'm going to update the test code with this and the suggested fixes in OP-TEE OS. If you wish to be mentioned in the commit message with a `Suggested-by: xxx xxx <xxx@xxx.xxx>` please supply name and some email address. It's OK to remain anonymous too, but then I cannot give you any attributions.

**Comment by hejunzju** [comment]
It's my pleasure! Thanks for the prompt support! Here is my profile.
Tony He <tony.he@armchina.com>

**Comment by jenswi-linaro** [comment]
Created https://github.com/OP-TEE/optee_test/pull/472 and https://github.com/OP-TEE/optee_os/pull/4268

**Comment by hejunzju** [comment]
@jenswi-linaro
There is one more issue regarding to the AE in the present TEE_CopyOperation() implementation, where the ae_tag_len is NOT copied. It will lead to AE decryption error on the copied context.

Here is the patch:
```
diff --git a/lib/libutee/tee_api_operations.c b/lib/libutee/tee_api_operations.c
index e85b1bc1..d2b4efd9 100644
--- a/lib/libutee/tee_api_operations.c
+++ b/lib/libutee/tee_api_operations.c
@@ -746,6 +746,7 @@ void TEE_CopyOperation(TEE_OperationHandle dst_op, TEE_OperationHandle src_op)
 	dst_op->info.handleState = src_op->info.handleState;
 	dst_op->info.keySize = src_op->info.keySize;
 	dst_op->operationState = src_op->operationState;
+	dst_op->ae_tag_len = src_op->ae_tag_len;
 
 	if (dst_op->buffer_two_blocks != src_op->buffer_two_blocks ||
 	    dst_op->block_size != src_op->block_size)
```
The xtest test code patch has been posted under the thread [OP-TEE/optee_test#472](https://github.com/OP-TEE/optee_test/pull/472)

**Comment by jenswi-linaro** [comment]
@hejunzju, I'm sorry but that patch doesn't compile:
```
lib/libutee/tee_api_operations.c: In function ‘TEE_CopyOperation’:
lib/libutee/tee_api_operations.c:742:8: error: ‘struct __TEE_OperationHandle’ has no member named ‘ae_tag_len’
  742 |  dst_op->ae_tag_len = src_op->ae_tag_len;
      |        ^~
lib/libutee/tee_api_operations.c:742:29: error: ‘struct __TEE_OperationHandle’ has no member named ‘ae_tag_len’
  742 |  dst_op->ae_tag_len = src_op->ae_tag_len;
```

**Comment by hejunzju** [comment]
@jenswi-linaro
The patch I posted earlier was generated based on a bit outdated code. Apologize for any trouble.
I just checked the most updated code. The issue is still there and the patch you proposed is absolutely right~

**Comment by hejunzju** [comment]
@jenswi-linaro I think we can close this issue now. Thanks
