### ISSUE TITLE
compat ioctl

### ISSUE THREAD

**Issue by jiangpeifu** [OP-TEE/optee_os#427]
Hello,

Is there any plan to support compat ioctl for 32-bit CA working with 64-bit Linux kernel driver? 

Thanks.
Peifu

**Comment by pascal-brand-st-dev** [comment]
optee_linuxdriver is under restructuring right now, to be part of Linux Kernel (cf. https://lkml.org/lkml/2015/7/8/346). We will of course consider 32bits client on 64bits kernel, but we have no current plan to have it in optee_linuxdriver.

**Comment by jbech-linaro** [comment]
@jiangpeifu , Aijun have proposed patches for this. Most likely we will integrate those to the project soon. You will find the pull requests [here](https://github.com/OP-TEE/optee_linuxdriver/pull/29) and [here](https://github.com/OP-TEE/optee_client/pull/35). So please stay tuned.

**Comment by jiangpeifu** [comment]
@jbech-linaro, Thanks a lot. It is a good news for me.

**Comment by pascal-brand-st** [comment]
Duplicated of #210
