### ISSUE TITLE
se050: add shippable support

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#4276]
To build se050 support in OP-TEE a path to the external PlugAndTrust repository [1] and the corresponding built library (arm/arm64) is required.

Would it be acceptable if @foundries we provided/maintained both of these so se050 can be added to shippable?

[1] https://github.com/foundriesio/plug-and-trust

**Comment by jforissier** [comment]
> Would it be acceptable if @foundries we provided/maintained both of these so se050 can be added to shippable?

Certainly. What do you have in mind? We could easily download (`wget`) a prebuilt library at the beginning of the Shippable script.

**Comment by jforissier** [comment]
Something like that (untested):
```diff
diff --git a/.shippable.yml b/.shippable.yml
index 2da7782d..83bc275e 100644
--- a/.shippable.yml
+++ b/.shippable.yml
@@ -20,8 +20,10 @@ build:
     - function upload_cache() { if [ ! -e .uploaded ]; then echo Uploading cache && tar c -C /root .ccache | gzip -1 | ssh $SCP_OPT shippable@shippable-cache.forissier.org "cat >ccache-$PROJ.tar.gz" && touch .uploaded || echo Nevermind; fi; }
     - function check_upload_cache() { NOW=$(date +%s); if [ $(expr $NOW - $START) -gt 3000 ]; then upload_cache; fi; }
     - function _make() { make -j$(getconf _NPROCESSORS_ONLN) -s O=out $* && ccache -s && ccache -z && check_upload_cache; }
+    - function download_plug_and_trust() { curl https://example.com/path/to/plug_and_trust.tar.gz | tar xz - -C /root || (rm -rf /root/plug_and_trust; echo Nervermind); }
 
     - download_cache
+    - download_plug_and_trust
     - ccache -z
 
     - _make
@@ -108,6 +110,7 @@ build:
     - _make PLATFORM=imx-mx8mqevk
     - _make PLATFORM=imx-mx8qxpmek
     - _make PLATFORM=imx-mx8qmmek
+    - if [ -d /root/plug_and_trust ]; then _make PLATFORM=imx-xyz CFG_NXP_SE05X_PLUG_AND_TRUST=/root/plug_and_trust ...; fi
     - _make PLATFORM=k3-j721e
     - _make PLATFORM=k3-j721e CFG_ARM64_core=y
     - _make PLATFORM=k3-am65x
```

In order to test this you may use https://shippable.com/ and register your own OP-TEE fork on GitHub. Then every time you push to a branch it will trigger a build. You don't even need to create a PR here first. Note that the `download_cache` and `upload_cache` steps will likely fail due to authentication errors, but it shouldn't matter much. Just move the `_make` line up in first position so you don't have to wait for the other platforms to build.

If something doesn't work and you would like to debug interactively, a good option is to run the Docker image directly on your PC. For example:
```
$ docker run -t -i --rm jforissier/optee_os_ci_clangbuilt bash
root@d1f5a20f8f97:/# cd
root@d1f5a20f8f97:~# git clone https://github.com/OP-TEE/optee_os
Cloning into 'optee_os'...
remote: Enumerating objects: 47296, done.
remote: Total 47296 (delta 0), reused 0 (delta 0), pack-reused 47296
Receiving objects: 100% (47296/47296), 22.43 MiB | 626.00 KiB/s, done.
Resolving deltas: 100% (32757/32757), done.
root@d1f5a20f8f97:~# cd optee_os
root@d1f5a20f8f97:~/optee_os# make -s -j10
root@d1f5a20f8f97:~/optee_os# ls -l out/arm-plat-vexpress/core/tee.elf
-rwxr-xr-x 1 root root 4682744 Dec 16 20:25 out/arm-plat-vexpress/core/tee.elf
root@d1f5a20f8f97:~# exit
exit
```

**Comment by ldts** [comment]
ok. thanks for all the details!

**Comment by ldts** [comment]
@jforissier https://github.com/OP-TEE/optee_os/pull/4279

**Comment by ldts** [comment]
closing now. thanks
