### ISSUE TITLE
Remove no more use mapping like external DT 

### ISSUE THREAD

**Issue by cneveux** [OP-TEE/optee_os#4278]
At the end of the boot the external DT is released but its region is kept in the static memory mapping array and in the MMU TLB    entries.

When using Dynamic Shared Memory, it might result in having a double MMU mapping of the physical area (used temporarily for the external DT). Indeed, OS re-use this area to pass Non-Secure buffer to OPTEE remapping it as Non-Secure memory area that is cacheable whereas external DT was mapped as non cacheable.

Consequently when calling functions to get properties of a dynamic shared buffer (allocated in the old external DT area):
- `core_mmu_get_type_by_pa()` with a PA address that was used for the external DT it returns the memory type `MEM_AREA_EXT_DT`
- `core_vbuf_is(CORE_MEM_CACHED, ...)` to know if virtual area is cacheable or not, it will return false but it's a buffer in dynamic shared memory (which is cacheable).
    
Other point that `core_mmu_add_mapping()` is keeping a `tee_mmap_region` of type `MEM_AREA_RES_VASPACE` with a size 0 when all VA reserved space is used.

**Comment by etienne-lms** [comment]
> When using Dynamic Shared Memory, it might result in having a double MMU mapping of the physical area ... cacheable whereas external DT was mapped as non cacheable.

This is indeed bad. Extrernal DT should have a temp mapping, i.e. in `RES_VASPACE`, unmapped once it's released before non-secure is booted.
