### ISSUE TITLE
signed_ta test

### ISSUE THREAD

**Issue by neil1899** [OP-TEE/optee_os#428]
hi all：

when i use the sign.py build the optee_test ta, i found a build error:

  File "/usr/local/lib/python2.7/dist-packages/pyasn1-0.1.8-py2.7.egg/pyasn1/type/univ.py", line 742, in _verifyComponent
    raise error.PyAsn1Error('Component value is tag-incompatible: %r vs %r' % (value, t))
pyasn1.error.PyAsn1Error: Component value is tag-incompatible: ObjectIdentifier('1.2.840.113549.1.9.16.2.35') vs Any()
make[2]: *** [/mnt/fileroot/wei.nie/optee/optee_test/out/ta/create_fail_test/c3f6e2c0-3548-11e1-b86c0800200c9a66.ta] Error 1

@jenswi-linaro i use your python, can you help me fix it?

thanks

**Comment by neil1899** [comment]
hi,all
who can give me some suggestions

thanks

**Comment by jforissier** [comment]
Hello @neil1899, did you manage to solve the issue? I'm not sure what is going on with your setup, maybe some tools are not installed properly or are the wrong version.
FWIW, I checked I could build the `signed_ta` branches on my laptop, please see the log at http://pastebin.com/TFXvmtvk. I'm using Ubuntu 15.04 (x86_64) with the default `python` command (2.7.9) and the default `arm-linux-gnueabihf-gcc` cross-compiler.

**Comment by neil1899** [comment]
I have fix this bug,

I change the sign.py 

diff --git a/scripts/sign.py b/scripts/sign.py
index cfd32e1..4235c1b 100755
--- a/scripts/sign.py
+++ b/scripts/sign.py
@@ -268,7 +268,7 @@ cms_id_dummy = univ.ObjectIdentifier('1.2.3.4.5')
 
 def get_attr(attr_type, attr_value):
        attr_values = cms_attr_values()
-       attr_values.setComponentByPosition(0, attr_value)
+       attr_values.setComponentByPosition(0, attr_value, False)
 
        attr = cms_attribute()
        attr.setComponentByName('attrType', attr_type)

my python version is 2.7.3
ubuntu 12.04

**Comment by neil1899** [comment]
and the default arm-linux-gnueabihf-gcc cross-compiler.

**Comment by jenswi-linaro** [comment]
Hi @neil1899,

The patch got garbled by github, but as I read it you've added a `False` parameter to the call to setComponentByPosition() to avoid checking constraints of the value.

`get_attr()` is used at many places doing this change could hide other problems.

This is still only prof of concept until we've decided how to move forward with the format of signed TAs.

**Comment by jbech-linaro** [comment]
@neil1899 @jenswi-linaro , this issue isn't relevant any longer I guess? We should use what was merged a day ago (on our master-branch). Can we close this issue?

**Comment by neil1899** [comment]
ok, thanks so much
