### ISSUE TITLE
Question about uncached memory

### ISSUE THREAD

**Issue by matthewchae** [OP-TEE/optee_os#4282]
Hi, I have a question about using the memory in OP-TEE.

1. How can I allocate the memory to the device memory in the cache attribute? 
    Is the register_phys_mem() correct?
2. How can I allocate aligned memory like using __aligned(64)?
3. How can I allocate contiguous memory?

Thanks in advance.

**Comment by jenswi-linaro** [comment]
> Hi, I have a question about using the memory in OP-TEE.
> 
> 1. How can I allocate the memory to the device memory in the cache attribute?
>    Is the register_phys_mem() correct?

Yes, make sure that you give the correct memory type, `MEM_AREA_IO_NSEC` or `MEM_AREA_IO_SEC` depending on what you need.

> 2. How can I allocate aligned memory like using __aligned(64)?

Currently there's no convenient way of doing that. 

> 3. How can I allocate contiguous memory?

Allocations from the heap gives contiguous memory, but the heap is normally quite small so large allocation may fail.

**Comment by matthewchae** [comment]
Thanks bunch.
