### ISSUE TITLE
What's the useful about DECLARE_KEEP_PAGER and DECLARE_KEEP_INIT ?

### ISSUE THREAD

**Issue by breakisx** [OP-TEE/optee_os#4285]

**Comment by jenswi-linaro** [comment]
In case pager is enabled (https://optee.readthedocs.io/en/latest/architecture/core.html#pager) it make sure that the function and its dependencies ends up the right part of the binary.

**Comment by breakisx** [comment]
@jenswi-linaro Thank you very much. I will learn the document carefully, after that, to read the code. ^_^
