### ISSUE TITLE
Can different threads on the same CPU in non-secure world call the Trust Service at the same time

### ISSUE THREAD

**Issue by jeffrey4913** [OP-TEE/optee_os#4287]
Dear Expert,
I know that the OPTEE have no  scheduling by itself and depend on linux scheduling.
I want to know if different threads on the same CPU in non-secure world can call the Trust Service at the same time.
eg: Non-secure world thread(thread_A) call open_session, then run into seucre world, at this time, a non-secure timer interrupt occured. So switch to non-secure world to hanlde the timer interrupt and non-secure os schedule to another thread(thread_B) at the same core. At this time, can thread_B call into secure world?

**Comment by jenswi-linaro** [comment]
Yes that's possible. If you have only a single CPU you can see that quite often depending on the workload.

**Comment by jeffrey4913** [comment]
Thanks for your reply.
Is the secure world context of thread_A saved when thread_B call into secure world? 
I means when thread_B run in the secure world,    timer interrupt is occured, then schedle to thread_A, Can thread_A continue execution of the last run context?

**Comment by etienne-lms** [comment]
Yes, thread_A would safely resume from where it was suspended.
In optee_os, thread_A was suspended when the timer interrupt was caught by secure world right before invoking back non-secure world.

**Comment by jeffrey4913** [comment]
ok,thanks
