### ISSUE TITLE
Reading a byte from PL011 UART

### ISSUE THREAD

**Issue by warraagal** [OP-TEE/optee_os#4295]
In the file _core/drivers/pl011.c_:

```
static int pl011_getchar(struct serial_chip *chip)
{
	vaddr_t base = chip_to_base(chip);
	while (!pl011_have_rx_data(chip))
		;
	return io_read32(base + UART_DR) & 0xff;
}
```
Please help me understand why 32 bits are read and then masked to give a byte instead of simply reading a byte.
Can the 24 bits that have been read and then discarded be re-read somehow ? Because if not, then doesn't this approach throw away potentially important data ?

**Comment by etienne-lms** [comment]
Hello @warraagal , 
`char` being a byte it make sense `pl011_getchar()` returns a byte.

**Comment by Emantor** [comment]
> In the file _core/drivers/pl011.c_:
> 
> ```
> static int pl011_getchar(struct serial_chip *chip)
> {
> 	vaddr_t base = chip_to_base(chip);
> 	while (!pl011_have_rx_data(chip))
> 		;
> 	return io_read32(base + UART_DR) & 0xff;
> }
> ```
> 
> Please help me understand why 32 bits are read and then masked to give a byte instead of simply reading a byte.
> Can the 24 bits that have been read and then discarded be re-read somehow ? Because if not, then doesn't this approach throw away potentially important data ?

According to the [documentation](https://developer.arm.com/documentation/ddi0183/g/programmers-model/register-descriptions/data-register--uartdr), the upper data bits contain error bits. My guess is that these have been foregone for a simpler UART implementation within OP-TEE.

Note also that according to the reference documentation I linked, the register size is only 16 bits, so `io_read16` would be the correct read function, but apparently the PL011 allows 32 bit access for all registers and nulls/discards the unused bits.

**Comment by warraagal** [comment]
@etienne-lms I wasn't questioning why a byte is being returned. I was trying to understand why a 32 bit word is being read when you only need to return a byte. Why not just read a byte ?
@Emantor thank you for your answer. I understand now. I was confused because in EDK2, only a byte is read ([PL011Uart.c](https://github.com/96boards-hikey/edk2/blob/hikey/ArmPlatformPkg/Drivers/PL011Uart/PL011Uart.c#L382), [PL011UartLib.c](https://github.com/tianocore/edk2/blob/272a1db63a09087ce3da4cf44ec7b758611ff1ed/ArmPlatformPkg/Library/PL011UartLib/PL011UartLib.c#L452)). I wanted to know why OPTEE does it differently. I realize now that I should RTFM carefully.

**Comment by etienne-lms** [comment]
@warraagal: if register can be accessed as a 32b, then current `io_read32(base + UART_DR) & 0xff` is fine.
If some archi mandate 8bit or 16bit access, we should implement something like what has been done for ns16550 in 1eacd17ce4.
