### ISSUE TITLE
PKCS#11  init_persistent_db panics when there are no object UUIDS to read

### ISSUE THREAD

**Issue by rvdgracht** [OP-TEE/optee_os#4303]
persistent_token.c: init_persistent_db()

When the db file is successfully opened the token_persistent_main and token_persistent_objs is read. So far so good.

Then the TA tries to read all objects UUIDs. This is without checking if there are any. In my case they haven't been
written before so db_objs->count = 0

```
	size += db_objs->count * sizeof(TEE_UUID);
	ptr = TEE_Realloc(db_objs, size);
	if (!ptr)
		goto error;

	db_objs = ptr;
	size -= sizeof(*db_objs);
	res = TEE_ReadObjectData(db_hdl, db_objs->uuids, size, &size);
	if (res || size != (db_objs->count * sizeof(TEE_UUID)))
		TEE_Panic(0);
```

Steps to reproduce:
 - Create a new token. Make sure there are no associated objects (new device or apply this PG: `https://github.com/OP-TEE/optee_os/pull/4300/commits/c248490a4943333d7e7c9254adff209521b0024e` and re-init)
 - Reboot without adding an object.
 - Next time the TA boots you'll get a 

> TA panicked with code 0xffff0001  -> TEE_ERROR_ACCESS_DENIED

This is propagated from TEE_ReadObjectData() since _utee_storage_obj_read returned the error.

I believe it can be worked around by making the above code snippet conditional with:

```
if (db_objs->count > 0) {
    $SNIPPET
}
```

The re-alloc without additional size and read with size=0 make no sense.

However I'm not sure since I get an TEE_ERROR_ACCESS_DENIED error. Can someone confirm this?

**Comment by etienne-lms** [comment]
I fully agree with you. Your fix look appropriate. Can you create a P-R or should we?

**Comment by rvdgracht** [comment]
Created a PR #4305. 

I've added a second patch in it with a minor change for consistency.
