### ISSUE TITLE
How to keep the System from hanging up

### ISSUE THREAD

**Issue by zbyboom** [OP-TEE/optee_os#4304]
We are trying to fuzz the optee os in order to find the vulnerability of it. We now meet a problem as follows. When the TEE core detects a fatal error and decides to hang the system because there is no way to proceed safely. However, it will make our testing unable to  run. I wonder if there is any way to keep the system from hanging up.

**Comment by vchong** [comment]
On return from TEEC_InvokeCommand(), if result == TEEC_ERROR_TARGET_DEAD, a TEEC_CloseSession() -> TEEC_OpenSession() should 'bring back the connection', if the context is still 'alive'. Would that work in your case?

**Comment by etienne-lms** [comment]
If fuzzing optee_os Core makes it panicking It's hard to recover from that, and hard to reliably safely return to the caller.
It is like if you expect Linux kernel resumes from a oops.
At most you can collect optee_os traces for analysis but it is likely optee can't be reboot without rebooting Linux/REE too.
I've quickly gone through [OP-TEE fuzzing webinar](https://www.linaro.org/events/webinar-running-a-fuzzing-tool-in-op-tee/) and @MartijnB [optee_fuzzer](https://github.com/Riscure/optee_fuzzer) but found nothing about.

**Comment by jforissier** [comment]
I think the most practical approach is to fix the bugs that cause panics ;-) I mean, one after another.

**Comment by jbech-linaro** [comment]
There are cases in the GP spec that mandates that you should panic. I.e., in some cases it's by design. For fuzzing purposes. One could eventually temporarily hack it to return instead of panic. However, when doing so, then you'll alter the regular flow. For other bugs that makes the TEE break, I agree with @jforissier , that is a bug that should should be (reported and/or) fixed. I see that happening when fuzzing as one of the goals with running a fuzzer.

**Comment by zbyboom** [comment]
Thank you for your reply. I think your opinion is&nbsp;convincing. We will try to fix them!






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Joakim Bech"<notifications@github.com&gt;; 
发送时间: 2021年1月7日(星期四) 下午4:58
收件人: "OP-TEE/optee_os"<optee_os@noreply.github.com&gt;; 
抄送: "qq"<1026128956@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OP-TEE/optee_os] How to keep the System from hanging up (#4304)





 
There are cases in the GP spec that mandates that you should panic. I.e., in some cases it's by design. For fuzzing purposes. One could eventually temporarily hack it to return instead of panic. However, when doing so, then you'll alter the regular flow. For other bugs that makes the TEE break, I agree with @jforissier , that is a bug that should should be (reported and/or) fixed. I see that happening when fuzzing as one of the goals with running a fuzzer.

**Comment by jforissier** [comment]
> There are cases in the GP spec that mandates that you should panic. 

For TAs I agree, here I was talking about the TEE core only. I don't see any reason it should ever panic whatever the input data during fuzzing.

**Comment by etienne-lms** [comment]
Indeed, core should not panic :) and core panics hide bug(s).
Does fuzzing find bugs without having the target to crash?

**Comment by jbech-linaro** [comment]
Crashing when running fuzzers is always a challenge, no matter the target. When reading about fuzzing evaluations it often starts with lots of crashes, then those gets fixed and then the "real" fuzzing can continue.

**Comment by etienne-lms** [comment]
You mean
... then the "real" fuzzing can continue until the next crash founds something.
or 
... then the "real" fuzzing can continue and report findings without facing crashes.
?

**Comment by jbech-linaro** [comment]
> You mean ...

Fuzzing is not only about finding crashes, it's more about finding call flow sequences that shouldn't be possible. I.e., with bad parameters you can enter code sections that you weren't supposed to. I can but that doesn't necessarily have to imply a crash. It could also, return error messages and in worst case "OK" (when it shouldn't).

**Comment by etienne-lms** [comment]
ok, i think I get the idea. thanks.
