### ISSUE TITLE
Minimal sanity test TA for U-Boot case

### ISSUE THREAD

**Issue by igoropaniuk** [OP-TEE/optee_os#4308]
I've stumbled upon multiple messages/complaints in U-Boot ML that optee driver in U-Boot isn't covered with any tests, except indirect cases like tests for `avb` command, which uses optee to read/store persistent storage values

Fortunately there were multiple attempts already to add minimal coverage, like @ruchi393 patch for testing RPMB requests from OP-TEE in `bcc6c574525("cmd: optee_rpmb command for read/write of rpmb from optee")` which was introduced after initial discussion in https://github.com/OP-TEE/optee_os/issues/3768.

I think building some minimal test commands over AVB TA makes sense, but we're limited to it's functionality (as initially this TA was supposed to be used for AVB case only). Considering that limitation, introduction of a minimal sanity test TA, which can be used to test optee client api in U-Boot (validation of memrefs, reverse rpc calls etc) makes more sense in long term perspective,  as new tests can be added (for example, to cover new RPC reverse calls, like `OPTEE_MSG_RPC_CMD_I2C_TRANSFER`, that @ldts is working on now in this [u-boot patch).](https://patchwork.ozlabs.org/project/uboot/patch/20210106183828.12404-1-jorge@foundries.io/). Also it won't have so much dependencies as AVB, for example, as the main purpose of this TA will be testing tee/op-tee API.

What I suggest to do (and ready start working on that):
1. Add U-Boot-test TA, which can cover minimal test cases, that can be borrowed from https://github.com/OP-TEE/optee_test/blob/master/ta/os_test/ta_entry.c#L57, like checking param integrity(`TA_OS_TEST_CMD_PARAMS`, `TA_OS_TEST_CMD_BASIC`, `TA_OS_TEST_CMD_NULL_MEMREF_PARAMS` etc), RPC reverse call tests, minimal persistent storage tests.

2. Introduce new `optee_test` command in U-Boot (extending @ruchi393 has already added) to be able to run this tests on both real HW and sandbox setup using U-Boot pytest suite. Add tests to [https://gitlab.denx.de/u-boot/u-boot/-/tree/master/test/py/tests](https://gitlab.denx.de/u-boot/u-boot/-/tree/master/test/py/tests)

3. Extend existing [TEE sandbox driver](https://gitlab.denx.de/u-boot/u-boot/-/blob/master/drivers/tee/sandbox.c) in U-Boot, adding an emulation of this u-boot-test TA for sandbox case.

I'm looking forward for you comments, at least understand if this idea is even sane :)

**Comment by etienne-lms** [comment]
Hi Igor,
I think u-boot expects sandbox stuff to mainly test framework/drivers in a emulated environment, so u-boot sandbox test should not mandated a effective OP-TEE and a related TA.
That said, having generic OP-TEE test means in U-Boot repo would be nice.

**Comment by igoropaniuk** [comment]
>  I think u-boot expects sandbox stuff to mainly test framework/drivers in a emulated environment, so u-boot sandbox test should not mandated a effective OP-TEE and a related TA.

that's correct, but tests in https://gitlab.denx.de/u-boot/u-boot/-/tree/master/test/py/tests should be successfully  run on both real HW and sandbox, which implies same behavior for drivers on real HW and in emulated environment/

**Comment by ruchi393** [comment]
> I've stumbled upon multiple messages/complaints in U-Boot ML that optee driver in U-Boot isn't covered with any tests, except indirect cases like tests for `avb` command, which uses optee to read/store persistent storage values
> 
> Fortunately there were multiple attempts already to add minimal coverage, like @ruchi393 patch for testing RPMB requests from OP-TEE in `bcc6c574525("cmd: optee_rpmb command for read/write of rpmb from optee")` which was introduced after initial discussion in #3768.
> 
> I think building some minimal test commands over AVB TA makes sense, but we're limited to it's functionality (as initially this TA was supposed to be used for AVB case only). Considering that limitation, introduction of a minimal sanity test TA, which can be used to test optee client api in U-Boot (validation of memrefs, reverse rpc calls etc) makes more sense in long term perspective, as new tests can be added (for example, to cover new RPC reverse calls, like `OPTEE_MSG_RPC_CMD_I2C_TRANSFER`, that @ldts is working on now in this [u-boot patch).](https://patchwork.ozlabs.org/project/uboot/patch/20210106183828.12404-1-jorge@foundries.io/). Also it won't have so much dependencies as AVB, for example, as the main purpose of this TA will be testing tee/op-tee API.
> 
> What I suggest to do (and ready start working on that):
> 
> 1. Add U-Boot-test TA, which can cover minimal test cases, that can be borrowed from https://github.com/OP-TEE/optee_test/blob/master/ta/os_test/ta_entry.c#L57, like checking param integrity(`TA_OS_TEST_CMD_PARAMS`, `TA_OS_TEST_CMD_BASIC`, `TA_OS_TEST_CMD_NULL_MEMREF_PARAMS` etc), RPC reverse call tests, minimal persistent storage tests.
> 2. Introduce new `optee_test` command in U-Boot (extending @ruchi393 has already added) to be able to run this tests on both real HW and sandbox setup using U-Boot pytest suite. Add tests to https://gitlab.denx.de/u-boot/u-boot/-/tree/master/test/py/tests
> 3. Extend existing [TEE sandbox driver](https://gitlab.denx.de/u-boot/u-boot/-/blob/master/drivers/tee/sandbox.c) in U-Boot, adding an emulation of this u-boot-test TA for sandbox case.
> 
> I'm looking forward for you comments, at least understand if this idea is even sane :)

Sounds like a good idea to me.
