### ISSUE TITLE
embdata in tee.bin

### ISSUE THREAD

**Issue by Master-Chi** [OP-TEE/optee_os#4309]
Hi Optee community,
   I am confused with the funtion of embdata in tee.bin. It seems achieved from relocation table of tee.elf, but i do not understand 
   how to use it or who use it?

Sorry for bothering

**Comment by jenswi-linaro** [comment]
Here's some clues:
https://github.com/OP-TEE/optee_os/blob/1a27b197d8b16ef2d4dab8d205f359627b6f0232/core/arch/arm/include/kernel/boot.h#L11-L32

It's used during boot when initializing paging and also ASLR. It's designed to be extensible.

**Comment by Master-Chi** [comment]
thanks a lot
