### ISSUE TITLE
"ignoring interrupt 0" while load dynamic ta

### ISSUE THREAD

**Issue by yangpeng1113** [OP-TEE/optee_os#4316]
Hi
     I run optee-os 3.9 in board with armv8 chips. I have a problem recently when I excute dynamic ta load with hello world ta and ca. Detail log is as follows:
     ===================  detail logs while loading dynamic ta   ======================
    optee_example_hello_world
    D/TC:? 0 tee_ta_init_pseudo_ta_session:284 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
    D/TC:? 0 load_ldelf:703 ldelf load address 0x80006000
    D/LD:  ldelf:134 TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
    D/TC:? 0 tee_ta_init_pseudo_ta_session:284 Lookup pseudo TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
    D/TC:? 0 tee_ta_init_pseudo_ta_session:297 Open system.pta
    D/TC:? 0 tee_ta_init_pseudo_ta_session:311  system.pta : 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
    D/TC:? 0 tee_ta_init_pseudo_ta_session:284 Lookup pseudo TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
    D/TC:? 0 system_open_ta_binary:257 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b(Secure Storage TA)
    D/TC:? 0 0 gic_it_handle:403 ignoring interrupt 0
    D/TC:? 0 0 gic_it_handle:403 ignoring interrupt 0
    D/TC:? 0 0 gic_it_handle:403 ignoring interrupt 0
    D/TC:? 0 0 gic_it_handle:403 ignoring interrupt 0
    D/TC:? 0 0 gic_it_handle:403 ignoring interrupt 0
    D/TC:? 0 0 gic_it_handle:403 ignoring interrupt 0
    D/TC:? 0 0 gic_it_handle:403 ignoring interrupt 0
    D/TC:? 0 0 gic_it_handle:403 ignoring interrupt 0
    D/TC:? 0 0 gic_it_handle:403 ignoring interrupt 0
    ……    ……    ……

    there are continuous log print as "ignoring interrupt 0" from uart, but I don't know how it happens
    
     Thanks a lot.

**Comment by jenswi-linaro** [comment]
It looks like the interrupt controller isn't configured correctly. Perhaps you need to install a handler for the interrupt or maybe the uart could be configured to not raise any interrupts. This depends on how your platform is configured.
