### ISSUE TITLE
For generating LLVM bitcode of OPTEE OS

### ISSUE THREAD

**Issue by dengpeiyao0515** [OP-TEE/optee_os#4320]
Hello there,

Recently I have been trying to generate a LLVM bitcode file to find system call sequences' dependencies. In this way, I need an **executable** file after compiling OPTEE OS, just like Linux would give a `vmlinux` after compiling the linux kernel. My question is: does the compilation of OPTEE OS generate an executable file as Linux does? 

Thank you for your time.

Kind regards,

**Comment by jforissier** [comment]
Hi @dengpeiyao0515,

What you're looking for is probably `$(out-dir)/core/tee.elf`.

**Comment by dengpeiyao0515** [comment]
Thank you for your reply! That makes sense.
I still have another question: when I tried to use wllvm(https://github.com/travitch/whole-program-llvm) to run command 
```
CC=wllvm make
extract-bc tee.elf
```
in the `extract-bc tee.elf`, there was an error saying 
```
WARNING:Could not find ".llvm_bc" ELF section in "/home/aim/workspace/dengpeiyao/optee_os-llvm/optee_os/out/arm-plat-vexpress/core/tee.elf", so skipping this entry.
```
I am wondering that have you ever tried to extract bitcode file from it or what kind of toolkits you recommend to do so instead of wllvm? Thank you again!

**Comment by jforissier** [comment]
> ```
> CC=wllvm make
> ```
I doubt `CC=wllvm` has any effect on the `optee_os` build. For OP-TEE the compiler is set via `CROSS_COMPILE{,32,64}=...` and (optionally) `COMPILER=clang`.

> I am wondering that have you ever tried to extract bitcode file from it or what kind of toolkits you recommend to do so instead of wllvm? Thank you again!

No, I have no idea about it.

**Comment by dengpeiyao0515** [comment]
Would it be possible to modify makefiles so it can support `wllvm` As a compiler.

**Comment by vchong** [comment]
Does `wllvm` work like `clang`? If so, not sure if it might work, but maybe try `make COMPILER=wllvm`.

**Comment by jforissier** [comment]
> Does `wllvm` work like `clang`? If so, not sure if it might work, but maybe try `make COMPILER=wllvm`.

For `make COMPILER=wllvm` to work one would need to create `mk/wllvm.mk` similar to `mk/clang.mk`.

**Comment by dengpeiyao0515** [comment]
Thank you for your suggestions and I have altered the original `mk/clang.mk` a little bit so it can compile with `-emit-llvm` to extract LLVM bitcode file.  
The way I modified it:
`CPP$(sm)	:= $(ccache-cmd)clang --target=$(clang-target) -E`
in **clang.mk** to
`CPP$(sm)	:= $(ccache-cmd)clang --target=$(clang-target) -E -emit-llvm`
i just got `out/arm-plat-vexpress/core/arch/arm/kernel/.**user_ta.o.bc**` for file `core/arch/arm/kernel/user_ta.c`. The  problem is that: how can I get llvm bitcode file for **every** .c file instead of the single user_ta.c？
Cheers.

**Comment by jforissier** [comment]
Have you tried `make clean` (or `rm -rf out`)?

**Comment by jforissier** [comment]
Oh and `$(CPP$(sm))` is not the compiler, it is the pre-processor.

**Comment by dengpeiyao0515** [comment]
i have tried `make clean`.
i was wondering if `CC$(sm)` is the compiler, but when i added `-emit-llvm` to `CC$(sm)` as
`CC$(sm) := $(ccache-cmd)clang --target=$(clang-target) -emit-llvm`
i got this error:
```
  GEN     out/arm-plat-vexpress/core/include/generated/arm32_sysreg.h
  GEN     out/arm-plat-vexpress/core/include/generated/arm32_sysreg.S
  CHK     out/arm-plat-vexpress/conf.mk
  UPD     out/arm-plat-vexpress/conf.mk
  CHK     out/arm-plat-vexpress/include/generated/conf.h
  UPD     out/arm-plat-vexpress/include/generated/conf.h
  CC      out/arm-plat-vexpress/core/include/generated/.asm-defines.s
  CHK     out/arm-plat-vexpress/core/include/generated/asm-defines.h
  UPD     out/arm-plat-vexpress/core/include/generated/asm-defines.h
  CC      out/arm-plat-vexpress/core/arch/arm/kernel/user_ta.o
llvm-objcopy: error: 'out/arm-plat-vexpress/core/arch/arm/kernel/user_ta.o': The file was not recognized as a valid object file
mk/compile.mk:159: recipe for target 'out/arm-plat-vexpress/core/arch/arm/kernel/user_ta.o' failed
make: *** [out/arm-plat-vexpress/core/arch/arm/kernel/user_ta.o] Error 1
make: *** Deleting file 'out/arm-plat-vexpress/core/arch/arm/kernel/user_ta.o'
```

**Comment by jforissier** [comment]
Yes `CC` is the compiler and if you change the output format from ELF object to something else you will need to change other things in the build. `llvm-objcopy` expects a `.o` file. Use `make V=1` to see the commands.
