### ISSUE TITLE
HiKey, RPMB: xtest gp_30346 hangs board 

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#4323]
Testing 3.12.0-rc1-3-g2a7b4219 on HiKey.

Build command: `make -j10 CFG_REE_FS=n CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y CFG_TEE_CORE_LOG_LEVEL=4 CFG_CORE_HEAP_SIZE=135168 CFG_ENABLE_EMBEDDED_TESTS=y`.

`xtest gp_30346` hangs the board with no further message on the console and the heartbeat LED remains stuck on or off.

Log file: [log.txt](https://github.com/OP-TEE/optee_os/files/5809626/log.txt)

**Comment by jforissier** [comment]
Reverting cd799689 and 64c6d291 fixes the issue.

**Comment by jenswi-linaro** [comment]
I can reproduce this on QEMU v7.
The error happens at https://github.com/OP-TEE/optee_os/blob/783c1515c2f9b22497651dee269cd849fd908a56/core/tee/tee_rpmb_fs.c#L2435
Where `rd_size` is larger than `offset`. @etienne-lms do you want to fix this or shall I? If I'm fixing it I'll memset the entire buffer first each time instead to keep things simple.

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/optee_os/pull/4331 should take care of this.

**Comment by jforissier** [comment]
> #4331 should take care of this.

It does, thanks! Closing.
