### ISSUE TITLE
Many GP tests fail with CFG_CORE_DYN_SHM=n

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#4324]
Testing 3.12.0-rc1-4-g17c32c05 on HiKey, with the GP test suite. Found an issue which is also reproducible with QEMUv8 (I have not tried QEMU). The log below is "copypasted" from QEMUv8.

Build command: `make -j10 CFG_CORE_DYN_SHM=n GP_PACKAGE=/path/to/TEE_Initial_Configuration-Test_Suite_v2_0_0_2-2017_06_09.7z`

```
$ xtest gp_10048
Test ID: gp_10048
Run test suite with level=0

TEE test application started over default TEE instance
######################################################
#
# regression+gp
#
######################################################

* gp_10048 de-12-60
gp_10000.c:896: TEEC_InvokeCommand(SESSION01, 0xFFFF0002u, OPERATION01, &ret_orig) has an unexpected value: 0xffff000e, expected 0x0
gp_10000.c:896: ret_orig has an unexpected value: 0x2, expected 0x4
  gp_10048 FAILED
+-----------------------------------------------------
Result of testsuite regression+gp filtered by "gp_10048":
gp_10048 FAILED first error at gp_10000.c:896
+-----------------------------------------------------
14 subtests of which 2 failed
1 test case of which 1 failed
2276 test cases were skipped
TEE test application done!
$ 
```
Several other GP tests fail, all with the same error it seems. `0xffff000e` is `TEE_ERROR_COMMUNICATION`.

**Comment by jenswi-linaro** [comment]
In this case the TA is invoked with a buffer with size 0x2000 before the TA returns it sets that buffer size to 0x2328.
With `CFG_CORE_DYN_SHM=n` the memory buffer is passed as a temporary memory reference while with `CFG_CORE_DYN_SHM=y` it's instead a registered memory reference. So with `CFG_CORE_DYN_SHM=n` we error out with the check at:
https://github.com/linaro-swg/linux/blob/436d15c681f41d15ff26adc5d6bc29c757188185/drivers/tee/optee/core.c#L84-L92

I suppose we need to remove that check for the tests to pass. However, first we must check carefully in the driver so we don't introduce a security problem with this. I recommend that we keep this as is for this release as we have a workaround (`CFG_CORE_DYN_SHM=y`).

**Comment by jforissier** [comment]
@jenswi-linaro thanks for investigating this, I had indeed identified it was a size issue because all GP tests in category [1] failed while all tests in category [2] are OK.

I agree with you to not address this in this release, it is not a regression anyways (I think this scenario has never been tested previously, with the older GP test suite).

For future reference: the behavior is specified in the GP TEE Internal Core API specification v1.1, table 4-9 "Interpretation of params[i] when Trusted Application Entry Point Returns" and section 4.3.6.4 "Memory Reference and Memory Synchronization". In a nutshell the operation is expected to succeed, and:
> [...] no data is guaranteed to be synchronized with the client. However, the client will receive the new value of size. The Trusted Application can typically use this feature to tell the client that the Memory Reference was too small [...]

[1] "1 parameter, TEEC_MEMREF_WHOLE, From TEEC_AllocateSharedMemory, Shared memory flag TEEC_MEM_OUTPUT set, Updated size is larger than original size"
[2] "1 parameter, TEEC_MEMREF_WHOLE, From TEEC_AllocateSharedMemory, Shared memory flag TEEC_MEM_OUTPUT set, Updated size is less than or equal to original size"

**Comment by jforissier** [comment]
> So with `CFG_CORE_DYN_SHM=n` we error out with the check at:
> https://github.com/linaro-swg/linux/blob/436d15c681f41d15ff26adc5d6bc29c757188185/drivers/tee/optee/core.c#L84-L92
> 
> I suppose we need to remove that check for the tests to pass. However, first we must check carefully in the driver so we don't introduce a security problem with this. I recommend that we keep this as is for this release as we have a workaround (`CFG_CORE_DYN_SHM=y`).

Following up on this. I can confirm that removing the above check fixes the issues (`xtest` with GP package, tested on QEMUv8). The driver doesn't seem to be using the size after it has been updated by the TEE side so it would seem safe? At least that is my understanding but I might have missed something.

**Comment by jenswi-linaro** [comment]
From user space it looks safe. This function is also used when converting RPC:s destined for tee-supplicant, but it looks safe there too.

**Comment by jforissier** [comment]
Thanks for double-checking. How can we proceed with this? Would you like me to send a patch to the LKML? With a Suggested-by you perhaps (since you identified the fix)?

**Comment by jenswi-linaro** [comment]
That sounds good to me.

**Comment by jforissier** [comment]
https://lkml.org/lkml/2021/3/22/411

**Comment by jforissier** [comment]
The Linux kernel [patch](https://lkml.org/lkml/2021/3/22/411) is on its way upstream. It is currently in [linux-next](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/log/drivers/tee/optee) and is expected in kernel v5.13.

**Comment by jforissier** [comment]
> The Linux kernel [patch](https://lkml.org/lkml/2021/3/22/411) is on its way upstream. It is currently in [linux-next](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/log/drivers/tee/optee) and is expected in kernel v5.13.

Patch was [merged](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/tee?h=v5.13-rc1&id=c650b8dc7a7910eb25af0aac1720f778b29e679d) in kernel v5.13-rc1.
