### ISSUE TITLE
Could you help prefetch abort in armv7 platform?

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#4334]
hi, recently we met a prefetch abort in optee stress test(we use thumb instruction for opteeos in our armv7 platform):

![image](https://user-images.githubusercontent.com/35290009/104671637-1f8c0100-5719-11eb-8918-9e37061d72ae.png)

The instructions near prefetch abort are:

```
81002e74 <timeout_elapsed>:
81002e74:       b590            push    {r4, r7, lr}
81002e76:       b083            sub     sp, #12
81002e78:       af00            add     r7, sp, #0
81002e7a:       e9c7 0100       strd    r0, r1, [r7]
81002e7e:       f7ff ffad       bl      81002ddc <read_cntpct>
81002e82:       460a            mov     r2, r1
81002e84:       4601            mov     r1, r0
81002e86:       e9d7 3400       ldrd    r3, r4, [r7]
```
Per my understanding, the prefetch abort is usually caused by inaccessible memory for instruction.  But in the log there are something that hard to explain, could you please give me some help?

1.  The abort instruction " bl 81002ddc" aims to jump to  0x81002ddc, but the panic log shows the prefetch abort address is 0x81002e80.  Is it possible because the instruction  "bl  81002ddc" is modified to  "bl 0x81002e80"?  In our platform, we have already found ddr hardware 1 bit flip issue before. But the hex value for "bl 0x81002e80" is 0xF7FFFFFF,  too many different bits compared to  0xf7ffffad...

2. From the log "translation fault" and far register value 0x5, it should be a first-level translation fault. But in our platform we only reserve 1MB for optee core, thus there's only one first level entry.  I think if there's anything wrong in first level page table, then the panic call stack log can't be printed out since the prefetch abort handler also can't be executed? Or maybe there's something wrong with the TLB since at this stage the first level page table entry is probably resides in TLB? 
 
Looking forward to your reply. Many thanks in advance!

**Comment by jenswi-linaro** [comment]
A prefetch abort happens on the instruction being fetched so in this case it looks like it's fetching the `bl` instruction itself that is causing the abort. Given that the instruction before was fetched successfully I think something has happened in between. Perhaps an interrupt? Or more specifically a non-secure interrupt. That is a bit complicated and normal world can even have returned with a different core. Why that should cause such a problem I don't know.

It is interesting that the abort is reported properly.

Hmm, `0x81002e80` is the second part of the instruction at `0x81002e7e`. When a thumb instruction is spanning two pages we can sometimes see an abort for the second part of the instruction. Here we're still within that same page. Perhaps it's a cacheline boundary? I don't know why that should be a problem. Perhaps there's some inconsistency with mappings and what's in the cache? In that case that a previously executable memory range has turned not executable but without the needed i-cache invalidation and barriers?

That's all I can think of for the moment.

**Comment by tiger20081015** [comment]
@jenswi-linaro , many thanks for your analysis. We ran the same test last weekend and found an undefined instruction abort as below. For this issue, we suspect it's related to some hardware issue, like DDR 1 bit flip or cache inconsistency. 

![image](https://user-images.githubusercontent.com/35290009/104978012-e9fa5700-5a3b-11eb-8df5-aeb8b72f5170.png)


However, in current panic log, the instruction code of undefined instruction is not printed so we can't make sure of our suspect. @jenswi-linaro , do you think the instructions near PC should be printed,  just similar as the linux kernel does?  And is there any tool like crash to analyze optee panic?

_linux kernel's panic log:_
_[  278.454257] c1 965 (secrtctest) Unable to handle kernel paging request at virtual address 0530f00d
[  278.463551] c1 965 (secrtctest) pgd = 353b6c4c
[  278.463558] c1 965 (secrtctest) [0530f00d] *pgd=00000000
...
[  279.025123] c1 965 (secrtctest) Exception stack(0xc0fedfa8 to 0xc0fedff0)
[  279.044063] c1 965 (secrtctest) dfa0:                   0052b3ec 0052b3ec 0053f160 0053f718 0053f580 2e0ee800
[  279.061051] c1 965 (secrtctest) dfc0: 0052b3ec 0052b3ec 0053f160 0000000b 0053f160 0053f718 0053f580 b6f23900
[  279.082497] c1 965 (secrtctest) dfe0: 0052b620 be82f86c 0049c701 b6e3d2f8
[  279.101681] c1 965 (secrtctest) Code: e7931100 e0842001 e0825185 e0820008 (e5953004)   **//Print out instrctions near PC**_

**Comment by jenswi-linaro** [comment]
I'm afraid this is all we have. You should be able to add some code yourself to dump a few interesting instructions.

**Comment by tiger20081015** [comment]
@jenswi-linaro , yes, I can add the code by myself.   Just suggesting maybe the optee open source code can also have this feature to help debug similar issues in future :).

**Comment by tiger20081015** [comment]
We've found the root cause of the issue. It's because the CPU's voltage is not high enough with heavy loadings. We can reproduce the issue easily if we intentionally decrease the voltage. Thanks for your help!
