### ISSUE TITLE
Is it Possible to get TA output without UART cable connected ?

### ISSUE THREAD

**Issue by zhaoxuyang13** [OP-TEE/optee_os#4336]
I'm applying optee into raspberry 3B+, and try to debug a TA.
however, my UART cable(TTL-to-USB) seems to be broken.
My question is, can I see the output of TA (DMSG/IMSG or so) without physically connect with UART cable? 
or is it easy to redirect TA output to be seen by a ssh terminal.(maybe ignore the security issues when debugging)

**Comment by etienne-lms** [comment]
TA traces are currently printed together with OP-TEE Core traces.
If you can see `IMSG()`/`EMSG()`/... traces from the Core then it should be possible to see TA traces.

To get TA trace, build optee_os with `CFG_TEE_CORE_TA_TRACE=y` & `CFG_TEE_TA_LOG_LEVEL`>0, 
and build TAs with `CFG_TEE_TA_LOG_LEVEL` > 0

**Comment by jforissier** [comment]
@etienne-lms true but I suspect @zhaoxuyang13 has the same problem with core traces, he probably accesses the RPi via ssh.
The logging framework currently being discussed elsewhere might help eventually but I see no other short term solution.

**Comment by zhaoxuyang13** [comment]
Thanks for your reply :),  
I solved the UART issue ( broken cable. ehh), and I can see the *MSG from UART connection now.

the framework you mentioned seems a bit heavy, maybe I'll check them out later.
