### ISSUE TITLE
How can I add newlib C to a TA?

### ISSUE THREAD

**Issue by friedrich12** [OP-TEE/optee_os#4337]
Is there anyway I can add the C library to a TA? I need to use the math functions and file functions like fopen().

**Comment by jforissier** [comment]
The C library in OP-TEE is contained in `libutils`. Many functions are imported from newlib already, so you could perhaps add more here: https://github.com/OP-TEE/optee_os/tree/master/lib/libutils/isoc/newlib.

The math functions are probably not too hard to add. As for file functions (`fopen()` etc.), it is a different story. TAs should normally use the GP API for secure storage. Perhaps POSIX functions could be developed on top, but the "filesystem" is different so it is not trivial (no directory hierarchy for instance).

**Comment by friedrich12** [comment]
Would it be possible to build a POSIX file system on top of the GP API?

**Comment by jforissier** [comment]
Probably.

**Comment by friedrich12** [comment]
Would it be possible to use FUSE (Filesystem in Userspace) in optee?

**Comment by friedrich12** [comment]
I ported the rest of the math functions [here](https://github.com/friedrich12/optee-fun/tree/main/examples/sod/ta/newlib) and implemented the File IO in memory.
