### ISSUE TITLE
Reason for hiding unhiding pages

### ISSUE THREAD

**Issue by mwerensteijn** [OP-TEE/optee_os#4338]
Hi contributors,

What is the reason that OP-TEE hides and unhides the pages in pagefault handler tee_pager_handle_fault?
If I understand correctly the page is still in memory but only unmapped.
 
Is this for security reasons? making the page inaccessible?

Thanks!

**Comment by etienne-lms** [comment]
`tee_pager_handle_fault()` is part of the Pager feature of OP-TEE. It is enabled only if `CFG_WITH_PAGER=y`. It is used only for platforms with a small secure RAM. Pager implements a kind of memory swapping mechanism between secure and non-secure memory, using hidden pages among other things.
Some information in OP-TEE pager documentation: https://optee.readthedocs.io/en/latest/architecture/core.html#pager
The doc does not describe the paging strategy, it's mainly in `tee_pager_handle_fault()`. Valid pages are sometime hidden (unmaped but content preserved) to help finding less accessed pages and get them paged out first (moved to non-secure RAM).

**Comment by mwerensteijn** [comment]
> Valid pages are sometime hidden (unmaped but content preserved) to help finding less accessed pages and get them paged out first (moved to non-secure RAM).

That was the answer I was looking for!
Thanks @etienne-lms !
