### ISSUE TITLE
SE050: store SCP03 set of keys in RPMB.  CFG_RPMB_RESET_FAT 

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#4339]
The SCP03 keys used to encrypt the I2C communications between OP-TEE and the I2C SE050 device should be pushed to persistent storage (preferably RPMB). I am in the process of delivering this set of changes.
The only issue I see is that CFG_RPMB_RESET_FAT - when enabled - could delete these keys and brick the SE050 and there would be no coming back from this operation.

I have been toying with the idea of being able to read back the keys from RPMB before reinitializing it (resetting the FAT) but the whole thing gets really messy and difficult to maintain.

I was wondering, is CFG_RPMB_RESET_FAT a common use case or only used under some critical circumstances? Perhaps we should just disable CFG_RPMB_RESET_FAT when CFG_SE05X is enabled? any thoughts?

**Comment by jenswi-linaro** [comment]
Is it possible to derive the needed keys from the HUK instead?

**Comment by ldts** [comment]
yes, you are right.
so before closing the board - ie while we still use the development HUK - we can default to using the pre-programed keys (burnt in the SE050 and compiled into OP-TEE). once the HUK is available (board closed), we could execute the SCP03 key provisioning and set these HUK derived keys into the SE050.
awesome. thanks!

**Comment by jenswi-linaro** [comment]
I guess you're now aware of `huk_subkey_derive()`. I suppose we should add another identifier to `enum huk_subkey_usage`.

**Comment by ldts** [comment]
yes, was just doing that.

**Comment by ldts** [comment]
@jenswi-linaro fjyi I have implemented to this requirement on this PR https://github.com/foundriesio/optee_os/pull/35 (using our legacy implementation of the OP-TEE support).

Will update upstream as soon as we transition to fully use the coming OP-TEE release. Will close this issue in a little bit

**Comment by ldts** [comment]
Just merged yesterday.
closing now.
