### ISSUE TITLE
How to increase the number of syscall arguments?

### ISSUE THREAD

**Issue by xiangmy** [OP-TEE/optee_os#4341]
Dear OPTEE group,

Is there a way to increase the number of syscall arguments on 64-bit optee? The following is how I changed it though it doesn't work.
+ Modify the [`TEE_SVC_MAX_ARGS`](https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/include/tee_syscall_numbers.h#L86) to 9
+ [utee_syscalls_a64.S](https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/arch/arm/utee_syscalls_a64.S#L14) in line 14
   - `.if \num_args > TEE_SVC_MAX_ARGS || \num_args > 8` => `.if \num_args > TEE_SVC_MAX_ARGS || \num_args > 9`
+ [utee_syscalls_a32.S](https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/arch/arm/utee_syscalls_a32.S#L40) in line 40
   - `add     r5, sp, #(4 * 4)` => `add     r5, sp, #(5 * 4)`

Any advice on how I should proceed?

Thanks,
Mingyuan

**Comment by jenswi-linaro** [comment]
I'd advise against increasing it, it's more trouble than what it's worth. It's not likely that this is something we'd accept upstream.

It's likely much easier to pass a few parameters in a struct instead.

If you still want to pursue this you need to do something like what we're doing for armv7 (a32) taking the AArch64 calling convention into account (roughly, first 8 parameters in register and the rest on the stack).

**Comment by xiangmy** [comment]
Hi @jenswi-linaro ,

Thanks for your reply! The only reason why I don't want to pass a struct is that adding a struct for this syscall only would be a little 'ugly'. However, this seems to be my only option. Altering the assembly would be quite troublesome especially when I don't know well about the optee under the hood.

Thanks,
Mingyuan
