### ISSUE TITLE
TEE device file permissions

### ISSUE THREAD

**Issue by marksaenger** [OP-TEE/optee_os#4344]
Hopefully a simple question.  I'm in the process of hardening my system by reducing permissions where possible and is there a configuration somewhere to change the permissions of `/dev/tee0` and `/dev/teepriv0`?  Right now they are both by default set to user and group `root:root` with permissions 0600.  I've seen in some places that the group should be `tee` and `teeclnt` but I'm not sure where to change that.

**Comment by jenswi-linaro** [comment]
We're just creating those in the kernel with whatever values that results in. A quick google query "udev change permissions device" yields among other things:
https://www.thegeekdiary.com/how-to-configure-device-file-owner-group-with-udev-rules/

**Comment by jforissier** [comment]
It depends on the Linux distribution. In our test environment we use Buildroot and we have an init script to take care of that, see https://github.com/OP-TEE/build/blob/3.12.0/br-ext/package/optee_client_ext/S30optee.

**Comment by marksaenger** [comment]
Thanks all.  I should have specified I'm using Yocto to build our Linux distro.  Is it important that these permissions be set before starting `tee-supplicant`?

**Comment by jforissier** [comment]
> Is it important that these permissions be set before starting `tee-supplicant`?

Yes, because `tee-supplicant` opens `/dev/teepriv0`.

**Comment by marksaenger** [comment]
So in my case since I'm using `systemd` to manage `tee-supplicant` and if I use a `udev` rules script to set the permissions, I should be careful to guarantee the device is created before `tee-supplicant` starts correct?

Just from some quick googling it looks like I can add the following to my rules script to ensure proper ordering:
`... TAG+="systemd", ENV{SYSTEMD_WANTS}+="tee-supplicant.service"`

I realize this is probably outside the scope of optee-os but in your experience is the recommended way to do this?  It looks like your buildroot init script takes the role of `systemd` to manage `tee-supplicant` so just looking for some good practices here with `systemd`.

**Comment by jforissier** [comment]
> So in my case since I'm using `systemd` to manage `tee-supplicant` and if I use a `udev` rules script to set the permissions, I should be careful to guarantee the device is created before `tee-supplicant` starts correct?

Yes, correct. Sorry I don't know systemd so I can't say how to do this properly.

**Comment by marksaenger** [comment]
> Yes, correct. Sorry I don't know systemd so I can't say how to do this properly.

Not a problem, thanks for the help!

**Comment by marksaenger** [comment]
@jforissier Slightly related to my previous question: I managed to set all of my permissions to mimic your suggestions and I'm hitting an issue with the data store permissions.  My data store is in a slightly different location, let's call it `/mydata/tee` by setting `CFG_TEE_FS_PARENT_PATH` and I have `/mydata/tee` permissions set to `tee:tee` / `0770`.  This results in the following errors when running my client application:

```
E/LD:  init_elf:259 sys_open_ta_bin ...
E/TC:? 0 init_with_ldelf:229 ldelf failed with res: 0xffff0000
E/TC:? 0 tee_ta_open_session:727 Failed. Return error 0xffff0000
TEEC_Opensession failed with code 0xffff0000 origin 3
```

However, after I modify the parent folder `/mydata` uid:gid to `root:tee` (previously set to `root:root`) everything works fine.  For some context these are the rest of my relevant permissions:
`/dev/teepriv0`: `root:tee` / `0660`
`/dev/tee0`: `root:teeclnt` / `0660`
`tee-supplicant` running as user `tee`
Client application accessing secure storage is part of group `teeclnt`

Maybe I'm just misunderstanding Linux permissions, but I'm not sure why in this case my parent data store folder needs to be in group `tee` for this to work as long as `/mydata/tee` is set correctly.

**Comment by jforissier** [comment]
Hello @marksaenger,

I can't see anything wrong with your config. Could you run tee-supplicant with `strace` so we can see what's happening with the filesystem access? To do that, kill `tee-supplicant` then run `strace -o supp.log -u tee -f /usr/sbin/tee-supplicant -d /dev/teepriv0 &`. Try running your client app again, then check the content of `supp.log` and look for `/mydata`.

With our default test environment we have:
```
143   mkdir("/data", 0700)              = -1 EEXIST (File exists)
143   stat64("/data", {st_mode=S_IFDIR|0755, st_size=60, ...}) = 0
143   mkdir("/data/tee", 0700)          = -1 EEXIST (File exists)
143   stat64("/data/tee", {st_mode=S_IFDIR|0770, st_size=40, ...}) = 0
143   mkdir("/data/tee/", 0700)         = -1 EEXIST (File exists)
143   stat64("/data/tee/", {st_mode=S_IFDIR|0770, st_size=40, ...}) = 0
143   openat(AT_FDCWD, "/data/tee//dirf.db", O_RDWR|O_SYNC|O_LARGEFILE) = -1 ENOENT
143   openat(AT_FDCWD, "/data/tee//dirf.db", O_RDONLY|O_SYNC|O_LARGEFILE) = -1 ENOENT
143   ioctl(3, TEE_IOC_SUPPL_SEND, 0x76e1ad78) = 0
141   <... ioctl resumed>, 0x7e93cb90)  = 0
143   ioctl(3, TEE_IOC_SUPPL_RECV <unfinished ...>
141   openat(AT_FDCWD, "/data/tee//dirf.db", O_RDWR|O_CREAT|O_TRUNC|O_SYNC|O_LARGEFILE, 0600) = 5
```

The `EEXIST` and `ENOENT` errors are expected, because `tee-supplicant` checks if `/data/tee` exists and creates them if they don't, then it creates `/data/tee/dirf.db` (after calling into the TEE) at which point the secure storage is pretty much ready.
Any other error code however (`EPERM` in particular) would not be OK.

**Comment by marksaenger** [comment]
Thanks @jforissier, very helpful.

I'm seeing this

```
55    mkdirat(AT_FDCWD, "/mydata", 0700) = -1 EEXIST (File exists)
55    newfstatat(AT_FDCWD, "/mydata", {st_mode=S_IFDIR|0770, st_size=0, ...}, 0) = 0
755   mkdirat(AT_FDCWD, "/mydata/tee", 0700) = -1 EACCES (Permission denied)
```

and as expected when I change the group of `/mydata` to `tee` I get the following:

```
866   mkdirat(AT_FDCWD, "/mydata", 0700) = -1 EEXIST (File exists)
866   newfstatat(AT_FDCWD, "/mydata", {st_mode=S_IFDIR|0770, st_size=0, ...}, 0) = 0
866   mkdirat(AT_FDCWD, "/mydata/tee", 0700) = -1 EEXIST (File exists)
866   newfstatat(AT_FDCWD, "/mydata/tee", {st_mode=S_IFDIR|0770, st_size=0, ...}, 0) = 0
866   mkdirat(AT_FDCWD, "/mydata/tee/", 0700) = -1 EEXIST (File exists)
866   newfstatat(AT_FDCWD, "/mydata/tee/", {st_mode=S_IFDIR|0770, st_size=0, ...}, 0) = 0
866   openat(AT_FDCWD, "/mydata/tee//dirf.db", O_RDWR|O_SYNC) = 5
```

**Comment by jforissier** [comment]
I think the proper solution is to have the folders correctly setup (with the proper permissions) from the start, even before `tee-supplicant` is started.

**Comment by marksaenger** [comment]
The folders are already setup on boot and don't change at any point so not sure what else to change but I can try a few things.

A couple of things though:

1. Any concern with my log using `mkdirat` instead of `mkdir`?  Looking at the `man` page seems to suggest they should behave the same way when using `AT_FDCWD`.
2. When I run `tee-supplicant` with the arguments `-d /dev/teepriv0` it returns immediately so I typically run it without arguments so it can find the device automatically.  Any concern there?

**Comment by jforissier** [comment]
> The folders are already setup on boot and don't change at any point so not sure what else to change but I can try a few things.
> 
> A couple of things though:
> 
>     1. Any concern with my log using `mkdirat` instead of `mkdir`?  Looking at the `man` page seems to suggest they should behave the same way when using `AT_FDCWD`.

I don't think there is a problem with this.

>     2. When I run `tee-supplicant` with the arguments `-d /dev/teepriv0` it returns immediately so I typically run it without arguments so it can find the device automatically.  Any concern there?

This is slightly misleading, `/dev/teepriv0` is not an argument to `-d`. Instead `-d` stands for "daemon(ize)", with this flag the process will fork and run in the background. It is fine to let `tee-supplicant` find its device.

Back to the `strace` log:

> ```
> 55    mkdirat(AT_FDCWD, "/mydata", 0700) = -1 EEXIST (File exists)
> 55    newfstatat(AT_FDCWD, "/mydata", {st_mode=S_IFDIR|0770, st_size=0, ...}, 0) = 0
> ```
At this point, does `/mydata/tee` exist? If yes, what are its permissions?
> ```
> 755   mkdirat(AT_FDCWD, "/mydata/tee", 0700) = -1 EACCES (Permission denied)
> ```

**Comment by jforissier** [comment]
> The folders are already setup on boot and don't change at any point so not sure what else to change but I can try a few things.

If you have this before starting `tee-supplicant`:
```
drwxr-xr-x root:root /mydata
drwxrwx--- tee:tee /mydata/tee 
```
...then it should work. It is the default config we use for testing (except with `/data` rather than `/mydata`) as configured by the startup script I linked above.

**Comment by marksaenger** [comment]
Found the issue.  `/mydata` permissions were set to `0770`.  Changed it to `0755` and everything seems to work well now.  Thanks for the help!

**Comment by jforissier** [comment]
> Found the issue. `/mydata` permissions were set to `0770`. Changed it to `0755` and everything seems to work well now. Thanks for the help!

Hmmmm... you probably don't want this folder to be writable by all users... A 0 in last position is correct.

**Comment by marksaenger** [comment]
`0755` would be `rwxr-xr-x` so not writable by everyone correct?  And just thinking about this more I think it makes sense that the parent folder `/data` should be at least readable and executable by everyone.  `tee-supplicant` tries to create the folder `/data/tee` and since it is run by user `tee` it needs to be at least `r-x` by everyone otherwise we would get the `EACCES (Permission denied)` as I mentioned above right?
