### ISSUE TITLE
Assert: "Unknown rel_dyn info" in tee_ta_init_reldyn

### ISSUE THREAD

**Issue by paswan-ms** [OP-TEE/optee_os#435]
Hi,
After including OpenSSL in a TA the resultant TA fails to load in OpTEE, hitting this assert. We have other TA's in use that have been working fine, but this TA has become by far the largest now at around 835Kb in size. I'm investigating if this is a runtime problem or a linker script problem with finding and parsing the table and wondered if anyone intimately familiar with how this is done sees an obvious error?
Thanks,
Paul.

The runtime state at the point of failure:
`ERR TEE-CORE:tee_ta_init_reldyn:297: Unknown rel_dyn info 0x10202`
`ERR TEE-CORE:tee_ta_init_reldyn:300: rel_dyn 0x2afd1c, saddr 0x2a2e94, n 52872, rd_size 0xd010, exec 0x200050`
`ERR TEE-CORE:tee_ta_init_reldyn:303: nbr_func 0x5, ro_size 0xafe54, rw_size 0xeabc, zi_size 0x43db, rdg_size 0xd01011d0`
`DBG TEE-CORE:tee_ta_init_reldyn:304: assertion failed`

The linker output state is:
` *(SORT(.rela.*))`
                `0x000afe54                PROVIDE (linker_RO_sections_size, (end_of_RO_sections - start_of_RO_sections))`
                `0x0000eabc                linker_RW_sections_size = (end_of_RW_sections - start_of_RW_sections)`
                `0x000043db                ZI_sections_size = (end_of_ZI_sections - start_of_ZI_sections)`
                `0x00000001                ASSERT ((ZI_sections_size <= 0xfffff), Too large ZI_sections_size)`
                `0x002043db                linker_res_funcs_ZI_sections_size = (0x200000 + ZI_sections_size)`
                `0x000011d0                GOT_sections_size = (end_of_GOT_sections - start_of_GOT_sections)`
                `0x0000d010                rel_sections_size = (end_of_rel_data_section - start_of_rel_data_section)`
                `0x00000000                rela_sections_size = (end_of_rela_data_section - start_of_rela_data_section)`
                `0x00000001                ASSERT ((rela_sections_size == 0x0), Can't handle nonzero rela_sections_size)`
                `0x00000001                ASSERT ((GOT_sections_size <= 0xffff), Too large GOT_sections_size)`
                `0x00000001                ASSERT ((rel_sections_size <= 0xffff), Too large rel_sections_size)`
                `0xd01011d0                linker_rel_dyn_GOT = ((rel_sections_size << 0x10) + GOT_sections_size)`

TA Binary state:
Inside the .ta file itself, the first entry appears to be at offset 0xA2FE8 and the last at 0xAFE68

**Comment by paswan-ms** [comment]
Analyzing the binary files, this appears to be a linker/binary generation anomaly. The last few entries of the rel. dyn. table switch from info 0x17 to 0x02 (I'm suspecting this means the table encoding is different for these entries). It doesn't appear to be related to the actual symbol definitions themselves - there are a mix of symbols from various modules of the TA that fall in these last few entries with the 0x02 moniker.

**Comment by jenswi-linaro** [comment]
Hi Paul,

It looks like we need to add support for type 0x02 relocations. Unfortunately it looks like we need to know if it's a thumb function or something else. This information isn't included in the current binary format, but we're currently investigating loading the TAs as proper ELF files instead and then it will be available.

As I understand it this relocation can be emitted for certain code constructions. I guess it's due to some limitation in the linker.

Regards,
Jens

**Comment by paswan-ms** [comment]
Thanks for the reply. According to the ARM docs, this type of relocation is based on an offset into a symbol section that I haven't yet figured out how to find. There is also a note in the doc hinting that these shouldn't be present in our scenario so maybe there something wrong with the link that's causing these entries to be improperly handled.

"The type of the relocation. This field substantially divides the relocations into Static and Dynamic relocations. Static relocations are processed by a static linker; they are normally either fully resolved or used to produce dynamic relocations for processing by a post-linking step or a dynamic loader. A well formed image will have no static relocations after static linking is complete, so a post-linker or dynamic loader will normally only have to deal with dynamic relocations."

**Comment by jenswi-linaro** [comment]
This kind of code should be supported in TAs, I'm surprised we haven't run into this before. 

I found an interesting link https://sourceware.org/bugzilla/show_bug.cgi?id=16163 that sheds some light on this issue.

I guess we'll just have to deal with this relocation type too.

**Comment by paswan-ms** [comment]
It should be possible, however this type of relocation is based off an offset into a symbol table segment and I'm having some trouble figuring out how to get at that table because the TA header information does not contain a pointer to it. I suspect this is the symbol table segment:

` [10] .dynsym           DYNSYM          000c4f80 0ccf80 004830 10   A 11   3  4`

All of this information is properly in the ELF format as you noted, so maybe ELF is the way to go...

**Comment by jenswi-linaro** [comment]
By the way, I have experimental support for this in https://github.com/jenswi-linaro/optee_os/tree/abs_reloc building on the TA as ELF commit.

**Comment by paswan-ms** [comment]
Cool, thanks. To confirm that I don't have a local tools issues, were you able to reproduce the generation of the relocation using functions pointers in the same way?
Our fork is a little way behind the OpTEE master and contains our RPMB work so I'll try and roll forward to latest and put the ELF work into it to try it out.
Paul.

**Comment by jenswi-linaro** [comment]
In almost the same way. It turned out that I needed to both store a pointer to an external function and then also call the external function directly.

**Comment by paswan-ms** [comment]
Resolving this issue since the code is incorporated.
Thanks,
Paul.
