### ISSUE TITLE
Translation tables

### ISSUE THREAD

**Issue by lijun0314** [OP-TEE/optee_os#4356]
Hi all!
I have a few questions about Translation tables in MMU:
1. The small translation tables which is 32MB are assigned per thread, can we change the size to more than 32MB? 
2. I want to change the TA_DATA_SIZE to more than 32MB, can this be done?  If yes, what guidelines should I follow? If no, why? 

Now, I have changed the TA_DATA_SIZE to 29MB, and I want more size in my project. It would be great if you can point me to some relevant documentation or information. 
Thanks!

**Comment by lijun0314** [comment]
As this issue explained, https://github.com/OP-TEE/optee_os/issues/2964#issuecomment-486076210
> > What’s the maximum size for heap and stack? Can it be changed?
> 
> Maximum size depends on several factors so it's hard to tell what's the maximum. Yes, it can be changed.
> 
> > Does this 32MB DDR correspondent to the 32MiB in 1.?
> 
> No
> 
Here, does the "No" mean that 32MB DDR is not related to the translation table which is also 32MiB? If yes, if I want to change the OP-TEE size. the size can be 32MB DDR, 40MB DDR, 64MB DDR, or more, this is only depended on the platform which I use, right?

**Comment by jenswi-linaro** [comment]
If LPAE is available on your platform you could try that instead. With LPAE the virtual memory range is roughly 1GB.

If your only option is the Armv7 short descriptor format you need to adjust `TTBCR_N_VALUE` (set it to 6 instead for instance). With some luck that should be enough. We haven't tested changing that value so perhaps there's some unexpected side effects that has to be taken care of. Eventual problems should at least be contained in `core/arch/arm/mm/core_mmu_v7.c`.

**Comment by lijun0314** [comment]
@jenswi-linaro Thanks for your reply.
I changed TA_DATA_SIZE to greater than 32MB and move to the next step.
