### ISSUE TITLE
Use TZASC to isolate a region for secure world 

### ISSUE THREAD

**Issue by James567** [OP-TEE/optee_os#4359]
Hi all!
I'm trying to boot optee on my STM32MP157C-DK2 board .
I have a few questions about TZASC and arm-trusted-firmware :
     1. I want to define a new region for secure world to use , and Normal world have no permission to use
     2. Is it possible to define  a new region in `arm-trusted-firmware/plat/st/stm32mp1/stm32mp1_def.h`  and  configure in `arm- 
         trusted-firmware/plat/st/stm32mp1/stm32mp1_security.c` ?

Thanks!

**Comment by etienne-lms** [comment]
Hi @James567,

I guess this should be asked in TF-A forum. Yet, yes, you could do that from TF-A. Actually, if you want this DDR memory area to be statically mapped in optee (i.e. using `register_phys_mem()`) and accessed early during op-tee core inits, then yes, TZASC should be configured before optee boots, hence from TF-A.

An alternate way could be to configure TZASC for your extra area from optee **plat-stm32mp1/plat_tzc400.c** (`init_stm32mp1_tzc()`) and dynamically map it afterward. But maybe optee's dynamic mapping is less suitable to your needs.

In any case, don't forget to update u-boot and Linux DTs so that your area is tagged reserved, so that non-secure world to not mistakenly use that memory area.

**Comment by James567** [comment]
@etienne-lms  Thanks for your reply.
I decide to try your way , but i could not find where to update u-boot . 
Can you give me some suggest?
Thanks!

**Comment by James567** [comment]
Hi @etienne-lms,
I  try to reserved my extra erea memory in `linux/arch/arm/boot/dts/stm32mp157c-dk2.dts`.
`reserved-memory {
		optee_memory: optee@0xde000000 {
			reg = <0xde000000 0x02000000>;
			no-map;
		};
		secure_memory: secure@0xddf00000 {
			reg = <0xddf00000 0x00100000>;
			no-map;
		};
	};`
but i got error like:
` DTC     arch/arm/boot/dts/stm32mp157c-dk2.dtb
Error: arch/arm/boot/dts/stm32mp157c-dk2.dts:98.1-8 Label or path secure not found
FATAL ERROR: Syntax error parsing input tree
make[2]: *** [scripts/Makefile.lib:285: arch/arm/boot/dts/stm32mp157c-dk2.dtb] Error 1
make[1]: *** [Makefile:1240: stm32mp157c-dk2.dtb] Error 2`

 Thanks. @etienne-lms

**Comment by Emantor** [comment]
`Error: arch/arm/boot/dts/stm32mp157c-dk2.dts:98.1-8 Label or path secure not found`
Line 98 contains the error, which says that the label `secure` could not be found. This is correct, the `optee` node was defined in one of the DTSI files, however there is no `secure` node defined anywhere. Reserved-memory areas do not need to be enabled explicitly, the documentation for all the properties used can be found inside the linux kernel source tree in the `Documentation/devicetree/bindings` directory.

**Comment by etienne-lms** [comment]
so can @James567  use the below ?
```
	reserved-memory {
		optee_memory: optee@de000000 {
			reg = <0xde000000 0x02000000>;
			no-map;
		};
		secure_memory: @ddf00000 {
			reg = <0xddf00000 0x00100000>;
			no-map;
		};
	};
```
Note @James567, i've understood there should be no 0x prefix in _index_ in the _foo_@_index_ node names.

**Comment by James567** [comment]
> so can @James567 use the below ?
> 
> ```
> 	reserved-memory {
> 		optee_memory: optee@de000000 {
> 			reg = <0xde000000 0x02000000>;
> 			no-map;
> 		};
> 		secure_memory: @ddf00000 {
> 			reg = <0xddf00000 0x00100000>;
> 			no-map;
> 		};
> 	};
> ```
> 
> Note @James567, i've understood there should be no 0x prefix in _index_ in the _foo_@_index_ node names.

Ok , I modified the format of the code.
THANKS.

**Comment by James567** [comment]
> ```
> Error: arch/arm/boot/dts/stm32mp157c-dk2.dts:98.1-8 Label or path secure not found
> ```
> 
> Line 98 contains the error, which says that the label `secure` could not be found. This is correct, the `optee` node was defined in one of the DTSI files, however there is no `secure` node defined anywhere. Reserved-memory areas do not need to be enabled explicitly, the documentation for all the properties used can be found inside the linux kernel source tree in the `Documentation/devicetree/bindings` directory.

I found optee was defined in `stm32mp151.dtsi`
```
firmware {
		optee: optee {
			compatible = "linaro,optee-tz";
			method = "smc";
			status = "disabled";
		};
	};
```
but I only want to reserved an extra area for optee , which kind of node should I define?

**Comment by Emantor** [comment]
> > ```
> > Error: arch/arm/boot/dts/stm32mp157c-dk2.dts:98.1-8 Label or path secure not found
> > ```
> > 
> > 
> > Line 98 contains the error, which says that the label `secure` could not be found. This is correct, the `optee` node was defined in one of the DTSI files, however there is no `secure` node defined anywhere. Reserved-memory areas do not need to be enabled explicitly, the documentation for all the properties used can be found inside the linux kernel source tree in the `Documentation/devicetree/bindings` directory.
> 
> I found optee was defined in `stm32mp151.dtsi`
> 
> ```
> firmware {
> 		optee: optee {
> 			compatible = "linaro,optee-tz";
> 			method = "smc";
> 			status = "disabled";
> 		};
> 	};
> ```
> 
> but I only want to reserved an extra area for optee , which kind of node should I define?

The reserved-memory node should already take care of this.

**Comment by James567** [comment]
@Emantor thanks for your reply

**Comment by James567** [comment]
Hi @Emantor 
I reserved a memory region : ``` 0xda000000 - 0xda0fffff ``` from dts and add a region in TF-A .
I register it  in ``` optee_os/core/arch/arm/mm/core_mmu.c ``` and use ``` mobj_phys_alloc() ``` to allocate a buffer,  but i got error like below:
```
E/TC:1 0 tzc_it_handler:19 TZC permission failure
*D/TC:0   gic_it_handle:403 ignoring interrupt 1023
*E/TC:1 0 dump_fail_filter:414 Overlap violation on filter 0
E/TC:1 0 dump_fail_filter:420 Permission violation on filter 0
E/TC:1 0 dump_fail_filter:425 Violation @0xda000060, secure privileged read, AXI ID 4a8
E/TC:1 0 Panic

```  

can you give me some suggestion?

Thanks!

**Comment by James567** [comment]
I found that I redefined the same area .
