### ISSUE TITLE
Is the type of TEE_ECC_CURVE_SM2 curve in OP-TEE consistent with that of NID_sm2p256v1 curve in gmssl?

### ISSUE THREAD

**Issue by jiangbinghua** [OP-TEE/optee_os#4365]
hello！
The SM2 public keys X and Y generated in OP-TEE cannot be generated public key by gmssl interface。
How to use gmssl interface to generate public key according to X and Y parameters generated in OP-TEE？
Thanks！

**Comment by jforissier** [comment]
I don't know much about GmSSL but assuming it implements SM2 as per the specifications, then it should be compatible with OP-TEE's SM2 implementation. The curve parameters [in GmSSL](https://github.com/guanzhi/GmSSL/blob/master/crypto/ec/ecp_sm2p256.c#L118-L139) and [in OP-TEE](https://github.com/OP-TEE/optee_os/blob/3.12.0/core/lib/libtomcrypt/src/pk/ecc/ecc.c#L436-L446) look identical at least.

**Comment by jiangbinghua** [comment]
The curve parameters in GmSSL and in OP-TEE is identical，but using the x, y parameters of OP-TEE to generate public key with gmssl interface，an error is prompted。
OP-TEE generate secret key interface:
crypto_acipher_alloc_ecc_keypair( )
crypto_acipher_gen_ecc_key( )
Do you need other processing to generate the secret key?

**Comment by jiangbinghua** [comment]
Signing message with secret key generated by TEE，and then verify signature.but tips for signature verification: TEE_ERROR_SIGNATURE_INVALID       0xFFFF3072
Why is this mistake?

**Comment by jforissier** [comment]
Did you sign the correct buffer? SM2 signature is applied on a digest value computed from the message and various parameters (curve parameters, user ID and public key):
```
digest = SM3(SM3(ENTLA || IDA || a || b || xG || yG || xA || yA) || message)
signature = SM2_SIGN(digest, ...)
```
See the test case in optee_test: [gmt_003_part5_a2_ptx[]](https://github.com/OP-TEE/optee_test/blob/3.12.0/host/xtest/regression_4000_data.h#L7830-L7838). This buffer is hashed with SM3 [here](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000.c#L3596-L3598) then the signature is computed [here](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000.c#L3965-L3967) and verified [here](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_4000.c#L4007-L4010).
