### ISSUE TITLE
how to get MTK SoC developing board

### ISSUE THREAD

**Issue by angusmart** [OP-TEE/optee_os#437]
We found optee os had been porting to MediaTek MT8173 EVB Board，we prepare porting ATF(arm trusted firmware) and optee into a new SoC platform（armv8 architecture，trustzone supported），and we had contacted to MTK sales，but no respond；

whether MTK8783 trustzone supported? and how do you get the MT8173 EVB Board ?
Could you tell me how to get MTK SoC EVB Board as soon as possible？

**Comment by m943040028** [comment]
If you want to get a platform for OP-TEE development, you can get a Hikey board (https://www.96boards.org/products/ce/hikey/). It's an ARMv8-based board and is already integrated with OP-TEE and ATF (https://github.com/OP-TEE/manifest#5-hikey).

**Comment by xlyu** [comment]
Maybe it's more useful to ask this question at https://community.arm.com. There are some people working in sales or marketing.
