### ISSUE TITLE
SM2 keypair generation

### ISSUE THREAD

**Issue by jiangbinghua** [OP-TEE/optee_os#4372]
Signing message with secret key generated by TEE，and then verify signature.but tips for signature verification: TEE_ERROR_SIGNATURE_INVALID 0xFFFF3072
Why is this mistake?
This is the interface I call:
crypto_acipher_alloc_ecc_keypair( )
crypto_acipher_gen_ecc_key( )
How do I generate a secret keypair?

**Comment by jforissier** [comment]
> Signing message with secret key generated by TEE，and then verify signature.but tips for signature verification: TEE_ERROR_SIGNATURE_INVALID 0xFFFF3072
> Why is this mistake?
> This is the interface I call:
> crypto_acipher_alloc_ecc_keypair( )
> crypto_acipher_gen_ecc_key( )

Yes, these functions can be used to generate an SM2 key pair with key_type = TEE_TYPE_SM2_DSA_KEYPAIR. What makes you think TEE_ERROR_SIGNATURE_INVALID is caused by an invalid key pair? You can perhaps check that the key pair generated by crypto_acipher_gen_ecc_key() is valid by using external tools or write a test program. But, I rather suspect a mistake in the signing procedure.

**Comment by jiangbinghua** [comment]
I replace x, y and d in xtest with the key pair generated by TEE,Run signature successfully,but run verify failed.

**Comment by jforissier** [comment]
ZA in gmt_003_part5_a2_ptx contains xA and yA, did you re-compute it?

**Comment by jiangbinghua** [comment]
Sorry，I didn't do that，how can I recalculate it？

**Comment by jiangbinghua** [comment]
I know this: 
/* a */
        0xFF, 0xFF, 0xFF, 0xFE, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
        0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFC,
        /* b */
        0x28, 0xE9, 0xFA, 0x9E, 0x9D, 0x9F, 0x5E, 0x34, 0x4D, 0x5A, 0x9E, 0x4B,
        0xCF, 0x65, 0x09, 0xA7, 0xF3, 0x97, 0x89, 0xF5, 0x15, 0xAB, 0x8F, 0x92,
        0xDD, 0xBC, 0xBD, 0x41, 0x4D, 0x94, 0x0E, 0x93,
        /* xG */
        0x32, 0xC4, 0xAE, 0x2C, 0x1F, 0x19, 0x81, 0x19, 0x5F, 0x99, 0x04, 0x46,
        0x6A, 0x39, 0xC9, 0x94, 0x8F, 0xE3, 0x0B, 0xBF, 0xF2, 0x66, 0x0B, 0xE1,
        0x71, 0x5A, 0x45, 0x89, 0x33, 0x4C, 0x74, 0xC7,
        /* yG */
        0xBC, 0x37, 0x36, 0xA2, 0xF4, 0xF6, 0x77, 0x9C, 0x59, 0xBD, 0xCE, 0xE3,
        0x6B, 0x69, 0x21, 0x53, 0xD0, 0xA9, 0x87, 0x7C, 0xC6, 0x2A, 0x47, 0x40,
        0x02, 0xDF, 0x32, 0xE5, 0x21, 0x39, 0xF0, 0xA0,
but I don't know IDA.

**Comment by jiangbinghua** [comment]
I use the secret key generated by gmssl instead of the secret key in xtest,and run discovery successful!but I don't recalculate gmt_003_part5_a2_ptx.Why?

**Comment by jforissier** [comment]
IDA is defined in http://www.gmbz.org.cn/upload/2018-07-24/1532401863206085511.pdf Annex A:
"Suppose the ASCII encoding of 𝐼𝐷𝐴 is 31323334 35363738 31323334 35363738. 
𝐸𝑁𝑇𝐿𝐴 = 0080."

**Comment by xinwei2** [comment]
I also meet with this SM2 key generation issue.
The SM2 key pair I generated using OPTEE OS 3.15.0 is:

######Get private key success! value is:
A86A5CB868423BE1B2B5EF7CBD500CD3E6EFD81CF3BB16ADA74985BFC17B8E1F
######Get x_value success! value is:
717720C5A97CB312F56A58D208DBBD3A829FE8BE3E30C4117C46BA6DC456C4F6
######Get y_value success! value is:
F041A44B7FFB31733C65CBEA9AB2864078D449CE79A0BBA03DAC99127E63ACC9

I use openssl to verify this keypair, found it is not on SM2 curve, but is on ecc-secp-256 curve.

**Comment by xinwei2** [comment]
[sm_test.zip](https://github.com/OP-TEE/optee_os/files/8214090/sm_test.zip)
This is the openssl code I use to verify the keypair.

**Comment by xinwei2** [comment]
[sm2_generation.zip](https://github.com/OP-TEE/optee_os/files/8214134/sm2_generation.zip)
This is the code I use to generate SM2 keypair in TA and print it.

**Comment by hallowsman** [comment]
> [sm2_generation.zip](https://github.com/OP-TEE/optee_os/files/8214134/sm2_generation.zip) 这是我用来在 TA 中生成 SM2 密钥对并打印的代码。

通过ca调用ta 实现国密sm2算法的demo您这边有吗？？？方便分享一下吗
