### ISSUE TITLE
Hello, I am new to optee and wanted to enable optee os from trusted firmware. How to enable OPTEE through BL32 in trusted firmware? Thank you.

### ISSUE THREAD

**Issue by kurundkar123** [OP-TEE/optee_os#4375]

**Comment by jenswi-linaro** [comment]
You need to compile TF-A with support for OP-TEE. See for instance:
https://github.com/OP-TEE/build/blob/9c609007b049d066da620b675d27669c111eed90/fvp.mk#L64-L79

You can start with following the instructions at https://optee.readthedocs.io/en/latest/building/devices/fvp.html to see something that's known to work.

**Comment by kurundkar123** [comment]
Thank you. I want to port optee into the new platform which is based on armv8 I have created the files as stated in https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html#porting-guidelines
But I couldn't able to figure out how to compile those files and build optee please help me regarding this.
