### ISSUE TITLE
spin lock detection

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#4376]
Hi,  I read the latest spin lock code and found when deadlock occurs, it will only print message like "func:line possible spinlock deadlock reminder xxx".  It seems there's no record for the current owner or calling stack of the spin lock and this maybe not very continent for debug. Do you have any other method to debug deadlock or is there any plan to improve the spin lock detection? I saw there's lockdep detection, but it seems only for mutex lock? Many thanks!

**Comment by jforissier** [comment]
>  I saw there's lockdep detection, but it seems only for mutex lock?

Correct.

**Comment by tiger20081015** [comment]
@jforissier, thanks. So currently for spinlock debugging,  the message "func:line possible spinlock deadlock reminder xxx" maybe is the only info we have?

**Comment by jforissier** [comment]
Yes. Perhaps you can use stack helper functions such as `print_kernel_stack()` or `unw_get_kernel_stack()` at some specific points in your code to help understand the issue.

**Comment by tiger20081015** [comment]
Understood. Thanks for your reply.
