### ISSUE TITLE
__attribute__((constructor)) doesn't work w/ OP-TEE 3.12.0

### ISSUE THREAD

**Issue by ademyankov** [OP-TEE/optee_os#4377]
Hi folks,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;While trying to upgrade my TA from OP-TEE 3.9.0 (GCC-8.3.0 toolchain) to OP-TEE 3.12.0 (GCC-9.2.1) I noticed that the support for `__attribute__((constructor))` does not work anymore. I checked w/ 3.11.0; it does not work either.

Is that a known issue? Or the support was postponed for some reason? I hope the support was not canceled!?

**Comment by jforissier** [comment]
Hi @ademyankov,

> Is that a known issue? Or the support was postponed for some reason? I hope the support was not canceled!?

No, this is supposed to work, and in fact it's working here and with the same toolchain as yours (QEMU, xtest 1023):
```
$ xtest 1023
[...]
* regression_1023 Test ELF initialization (.init_array)
  regression_1023 OK


I/TC: OP-TEE version: 3.12.0 (gcc version 9.2.1 20191025 [...])
[...]
D/TA:  os_test_shlib_init:16 os_test_global=2
D/TA:  os_test_init:1294 os_test_global=21
[...]
D/TA:  os_test_shlib_dl_init:16 os_test_global=213
```

Are you rebuilding your TA with OP-TEE 3.12.0, or are you using the old binary? The internal mechanism used to process constructors/destructors has changed after 3.9.0, and this might have introduced a regression with older TAs. Please see commit 01b02a16.

**Comment by ademyankov** [comment]
@jforissier thanks for letting me know about the changes in the mechanism. I will have to figure out what has changed in the built environment, maybe I have to modify my linker script. And, yes, I rebuild everything with the new version's toolchain, headers, and libs.

**Comment by ademyankov** [comment]
Yeap! That was the case; `dyn_list` and accordingly, the `LDS` has changed. Thanks, @jforissier for pointing out the changes. That helped a lot! All works now!
