### ISSUE TITLE
https://git.linaro.org/people/christoffer.dall/qemu.git does not exist anymore

### ISSUE THREAD

**Issue by zzm7000** [OP-TEE/optee_os#438]
It seems https://git.linaro.org/people/christoffer.dall/qemu.git which is used in ./setup_qemu_optee.sh does not exist anymore.

**Comment by jforissier** [comment]
Indeed, we'll fix that. You may use https://github.com/linaro-swg/qemu.git instead.

**Comment by pascal-brand-st-dev** [comment]
We are currently changing the way environments are imported. We are now using android-like manifest and build. Please have a look at https://github.com/OP-TEE/manifest/blob/master/README.md. It will guide you to retrieve qemu environment using this new way.

Note that setup scripts are obsolete, and will be removed soon.

**Comment by zzm7000** [comment]
Thanks for the info and fixing the problem for the current version.
