### ISSUE TITLE
RFC: PRNG: improving the entropy of the Fortuna PRNG

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#4392]
There is value in increasing the PRNG randomness by feeding it with additional sources of entropy. 

Since the Fortuna algorithm is designed to be resistant against "injection" attacks in those sources, I propose we use the REE as  an additional source of entropy (ie, add an addtional RPC message).

This should help us leverage the support that many REE have for hardware random number generators without having to implement all those drivers in the TEE.

Note that this is not just for a one time seeding....this is to have a source of entropy feeding the entropy accumulator

**Comment by jforissier** [comment]
That doesn't sound like a bad idea :)

**Comment by ldts** [comment]
ok, I'll put something together for discussion

**Comment by igoropaniuk** [comment]
Should be pretty easy to implement: one additional RPC call and `get_random_bytes_arch()` invocation in optee driver RPC call handler.

**Comment by ldts** [comment]
yeah..that is what I was trying to explain last week...

**Comment by jenswi-linaro** [comment]
Sounds useful. :-)

**Comment by ldts** [comment]
I am not sure how best to inject the entropy. Is overriding plat_prng_add_jitter_entropy still the recommended way for doing this?

**Comment by jenswi-linaro** [comment]
Adding another RPC for this is for one option. Another is to occasionally (or everytime?) supply some entropy in struct optee_msg_arg. @pad, @ret and/or @ret_origin could if not 0 carry entropy. Perhaps only using @pad and giving it a suitable name would be the cleanest.

**Comment by ldts** [comment]
yes I think that is better than plat_prng_add_jitter_entropy. thanks!

**Comment by jenswi-linaro** [comment]
There's no need to involve RPC. We could call `crypto_rng_add_event()` in `__tee_entry_std()` instead.

**Comment by ldts** [comment]
ok. I suppose also there is not much value on checking the return value of the CMD; maybe just check if the pad/entropy field is different from zero before adding it should be sufficient.

**Comment by ldts** [comment]
https://github.com/OP-TEE/optee_os/pull/4394

**Comment by ldts** [comment]
This is what I tested on the kernel side

```
diff --git a/drivers/tee/optee/call.c b/drivers/tee/optee/call.c
index c7e25e77222a..c3cfacf3d644 100644
--- a/drivers/tee/optee/call.c
+++ b/drivers/tee/optee/call.c
@@ -7,6 +7,7 @@
 #include <linux/err.h>
 #include <linux/errno.h>
 #include <linux/mm.h>
+#include <linux/random.h>
 #include <linux/slab.h>
 #include <linux/tee_drv.h>
 #include <linux/types.h>
@@ -177,6 +178,7 @@ static struct tee_shm *get_msg_arg(struct tee_context *ctx, size_t num_params,
        int rc;
        struct tee_shm *shm;
        struct optee_msg_arg *ma;
+ size_t len;

        shm = tee_shm_alloc(ctx, OPTEE_MSG_GET_ARG_SIZE(num_params),
                            TEE_SHM_MAPPED);
@@ -195,6 +197,10 @@ static struct tee_shm *get_msg_arg(struct tee_context *ctx, size_t num_params,

        memset(ma, 0, OPTEE_MSG_GET_ARG_SIZE(num_params));
        ma->num_params = num_params;
+
+ len = get_random_bytes_arch(&ma->entropy, sizeof(ma->entropy));
+ if (len != sizeof(ma->entropy))
+         ma->entropy = 0;
        *msg_arg = ma;
 out:
        if (rc) {
diff --git a/drivers/tee/optee/optee_msg.h b/drivers/tee/optee/optee_msg.h
index 7b2d919da2ac..db3d768d1556 100644
--- a/drivers/tee/optee/optee_msg.h
+++ b/drivers/tee/optee/optee_msg.h
@@ -193,7 +193,7 @@ struct optee_msg_arg {
        u32 func;
        u32 session;
        u32 cancel_id;
-   u32 pad;
+ u32 entropy;
        u32 ret;
        u32 ret_origin;
        u32 num_params;
```

**Comment by ldts** [comment]
this adds ~17usec to `get_msg_arg` on imx6ull
