### ISSUE TITLE
Question: OP-TEE vs. TF-A when use it as a secure monitor

### ISSUE THREAD

**Issue by minkwns** [OP-TEE/optee_os#4398]
Dear OP-TEE developers,

Hello, I am an undergrduate student studying about boot sequence of ARM arch & TrustZone.
If I understood it correctly, I can use OP-TEE and TF-A both as a secure monitor(BL31).  

So I wonder about which one is better to use. 
Is there pros and cons of them in terms of security, convenience and whatever ? 

Sincerely, 

Junbeom Wi

**Comment by jforissier** [comment]
Hi @minkwns,

BL31 is TF-A, running at EL3. OP-TEE is BL32, running at SEL1.

**Comment by minkwns** [comment]
Hi @jforissier , 
Thank you for your kind reply. 

Then, Is Using TF-A more safer than using OP-TEE as a secure monitor in terms of security?
I meant I understood that EL3 is more safer because of its privilege.

**Comment by jforissier** [comment]
TF-A and OP-TEE are just parts of a complete architecture. This picture shows how various components are loaded and at which EL they execute: https://community.arm.com/resized-image/__size/2080x0/__key/communityserver-blogs-components-weblogfiles/00-00-00-37-98/7802.Figure-1.png
BL31 runs at EL3, it is meant for very specific purposes such as switching between Normal World and Secure World and dealing with some interrupts. OP-TEE runs at SEL1 and plays the role of an Operating System which makes it possible to execute Trusted Applications in Secure World (at SEL0). So you don't chose TF-A *or* OP-TEE; you need both.

**Comment by minkwns** [comment]
@jforissier 
Okay, each secure monitors act different role! Thanks!!

(If I understood correctly, close this issue. THANKS)

**Comment by jenswi-linaro** [comment]
Just one clarification. The secure monitor in OP-TEE is only used on ARMv7 systems (or on a ARMv8 system with EL3 in AArch32, but that's not very common).

**Comment by jforissier** [comment]
Yes, and that is `core/arch/arm/sm`.

**Comment by minkwns** [comment]
@jenswi-linaro @jforissier Oh, I understood. Thanks!
