### ISSUE TITLE
Question: secure storage app from U-boot

### ISSUE THREAD

**Issue by AntonioSanta** [OP-TEE/optee_os#4399]
Hello,
I would like to use OP-TEE's secure storage from U-boot.
Is there a tutorial or an example or docs I could follow to understand how to do this ?
I found something in the /drivers folder of U-boot sources but not a lot of explanations and I am missing how and where the TA part of the app is implemented and located.

thank you

**Comment by jenswi-linaro** [comment]
There's an example with Android Verified Boot in https://github.com/u-boot/u-boot/blob/master/cmd/avb.c and https://github.com/u-boot/u-boot/blob/master/common/avb_verify.c

The AVB TA is available at https://github.com/OP-TEE/optee_os/tree/master/ta/avb

The TA is compiled into OP-TEE as an early TA  (see https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#early-ta) to keep things simple.

**Comment by AntonioSanta** [comment]
thank you.
Where does OP-TEE store the persistent objects created by the TA driven from U-boot ?
I mean, if the RootFS has not yet been loaded, where is the location of OP-TEE secure storage that U-boot can read and write ?

**Comment by jenswi-linaro** [comment]
It's using RPMB. U-Boot forwards the RPMB from secure world to the eMMC driver.
