### ISSUE TITLE
Building OP-TEE for QEMU on Ubuntu 18.04

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#4408]
i'm following the page https://optee.readthedocs.io/en/latest/building/gits/build.html#get-and-build-the-solution

But, when i do repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml -b 3.12.0, i get the below error:
fatal: Cannot get https://gerrit.googlesource.com/git-repo/clone.bundle
fatal: error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

i've installed "repo" via, sudo apt-get install repo.
However, the repo init works on ubuntu 16.04.

Any means to get around this issue?

**Comment by jforissier** [comment]
Hi,

Are you behind a corporate firewall perhaps? I suspect some kind of network/proxy configuration issue.

**Comment by saddy-muchu** [comment]
Actually I'm using the same proxy addresses for Ubuntu 16.04 too.
