### ISSUE TITLE
Question about multi instance TA

### ISSUE THREAD

**Issue by HouYuu** [OP-TEE/optee_os#4414]
Hi experts,
    I have read the latest optee document and i have one question about multi instance TA:
    Q: Whether the two instance TAs can run on different CPU core in parallel when two REE threads invoke one TA at a same time?

**Comment by jenswi-linaro** [comment]
Yes that's possible. If it really happens or not is up to the scheduler in normal world.

**Comment by HouYuu** [comment]
> Yes that's possible. If it really happens or not is up to the scheduler in normal world.

Thanks for your comment.  
But i have another question about that, how the two instance TAs work if there is a single CPU core？

**Comment by jenswi-linaro** [comment]
It's up to the scheduler to decide, they can very well be executed with interleaved CPU time.

**Comment by HouYuu** [comment]
Thank you. 
Thanks for your time.
