### ISSUE TITLE
How does multi instance TAs work (virtualization and OP-TEE)?

### ISSUE THREAD

**Issue by HouYuu** [OP-TEE/optee_os#4417]
Hi experts,
There is a question when i read the discussion on [#1019](https://github.com/OP-TEE/optee_os/issues/1019), 
it is clear that single instance per VM when multiple VMs want to open session to the same TA(single instance TAs), 
but how about the multi instance TAs? Whether the TA(multi instance TAs) works like one instance per VM or one TA for each VM?

**Comment by etienne-lms** [comment]
Each instance of a multiinstance TAs is related to a specific opened session. So with or w/o multiplen VMs, a multi-instance TA works one TA for each session, whatever VM the session relates to.

**Comment by HouYuu** [comment]
> Each instance of a multiinstance TAs is related to a specific opened session. So with or w/o multiplen VMs, a multi-instance TA works one TA for each session, whatever VM the session relates to.

So if VM0 opens session 0 of multi instance TAs and session 1 of TA opened by VM1, the instance 0 (for session 0) works at TEE instance for VM0 and the instance 1 works at TEE instance for VM1, am i right?

**Comment by etienne-lms** [comment]
As far as the TAs are concerned, yes. OP-TEE will identify the VM (upon non-secure hypervisor information) and track the right TA instance for the right client VM.
That said, I can't tell how far TA instances 0 and 1 can identify the VM o their client.
