### ISSUE TITLE
TA floating point linker errors

### ISSUE THREAD

**Issue by paswan-ms** [OP-TEE/optee_os#442]
Since I rolled forward to the latest OpTEE I have a TA that uses floating point that's now hitting floating point linker issues:

`openssl-0.9.8zb/crypto/rand/md_rand.c:318: undefined reference to "__aeabi_dcmplt"`

Online reports of this sort of issue point to a missing lgcc directive to include libgcc in the linker command. I see that this was explicitly removed in the commit "User TA: remove libgcc from link in devkit", https://github.com/OP-TEE/optee_os/commit/82defca2edec79f785a355497931628801e512c6

Is there a recommended way to properly compile/link floating point support into a TA?
Thanks,
Paul.

**Comment by pascal-brand-st-dev** [comment]
Hello Paul,

I think a short-term solution is to add manually the libgcc link locally in your TA, with something similar to:

    include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
    ldargs-$(binary).elf += $(libgcc$(sm))

Then I think that the long-term solution would be to implement floating-point support as part of the libutils integrated in optee_os, as it is currently done for division support (https://github.com/OP-TEE/optee_os/tree/master/lib/libutils/isoc/arch/arm)

Regards,
Pascal.

**Comment by paswan-ms** [comment]
Thanks for the reply. I added libcc back and that resolved the missing symbols.
Paul.
