### ISSUE TITLE
How to use certificate chain to verify national secret certificate?

### ISSUE THREAD

**Issue by jiangbinghua** [OP-TEE/optee_os#4422]
Hello!
The certificate chain failed to use the interface
'mbedtls_x509_crt_parse_der' when verifying the national secret certificate. What interface should be called?

Thanks!

**Comment by jiangbinghua** [comment]
Can TA link to external OpenSSL library?OpenSSL library has the interface to verify the national secret certificate.

**Comment by jforissier** [comment]
In theory, yes, if you can build a version of OpenSSL that does not pull things that do not exist in the OP-TEE user space environment (for example `fopen()` etc.). I tried a similar exercise long ago. It required changing quite a lot of code in OpenSSL even after disabling things via configuration macros ("no file" etc.).

MBed TLS is available for TAs to use and I see no reason it would not work... perhaps you found a bug?

**Comment by jiangbinghua** [comment]
Mbed TLS doesn't seem to support national secret algorithm(SM2).

**Comment by jenswi-linaro** [comment]
There is one example with `test_8102()` in xtest where `ta_entry_mbedtls_check_cert()` is called to verify a certificate. Looking at the code may give you some idea.

**Comment by jiangbinghua** [comment]
I used TA_ entry_ mbedtls_ check_ Cert (), but it seems to work with Sha certificates, not SM2 certificates.

**Comment by vchong** [comment]
Just fyi there are SM2 related PRs @ https://github.com/ARMmbed/mbedtls/search?q=sm2&type=issues.

**Comment by jenswi-linaro** [comment]
> I used TA_ entry_ mbedtls_ check_ Cert (), but it seems to work with Sha certificates, not SM2 certificates.

OK, it looks like you found the answer yourself for now.

**Comment by jiangbinghua** [comment]
> > 我使用了TA_ entry_ mbedtls_ check_ Cert（），但它似乎适用于Sha证书，而不是SM2证书。
> 
> 好的，看来您现在已经找到答案了。
What I need is national secret Certificate (SM2 certificate) verification, but OP-TEE only found non national secret Certificate (sha256 certificate) verification.

**Comment by jiangbinghua** [comment]
> > I used TA_ entry_ mbedtls_ check_ Cert (), but it seems to work with Sha certificates, not SM2 certificates.
> 
> OK, it looks like you found the answer yourself for now.

What I need is national secret Certificate (SM2 certificate) verification, but OP-TEE only found non national secret Certificate (sha256 certificate) verification.
