### ISSUE TITLE
Aperiodic "segmentation fault" message in IBART when running xtest 1033 (tee-supplicant plugin test)

### ISSUE THREAD

**Issue by anisyanka** [OP-TEE/optee_os#4425]
I moved discussion of this problem from https://github.com/OP-TEE/optee_os/pull/4403#issuecomment-785035958 to here.

There is some strange behavior during execution of the test sometimes. For example - https://optee.mooo.com:5000/logs/OP-TEE/optee_os/4410/577146745/ffcc5ec42c627edf555766a8c0963cd205d4e664#end-01-hikey6220-test.
The bug has random character and appears not so frequent.

For now, I have no ideas why this happens. The code looks good.
I try to catch the bug to get a core dump file.

**Comment by anisyanka** [comment]
I tried to run plugin tests in a endless cycle:
```bash
while true; do xtest 33; done
```
However, I haven’t encountered any errors. 

Then I tried to exclude them:
```bash
while true; do xtest -x 33; done
```
But I still haven’t encountered any errors.

@jforissier, is there the ability to get ssh access to optee CI? (particular for HiKey device, where the bug was found)
Or maybe there are other ways how to get optee CI in my local machine?
If I had the access, I would try to catch the bug to get a core dump file.
And then if there were gdb and valgrin in the optee CI setup, i would try to locale the bug.

**Comment by jforissier** [comment]
@anisyanka thanks for looking into this. I'm not aware of a way to troubleshoot on the CI machine (IBART), but I do have a HiKey board so I can try and reproduce the issue myself. I'll keep you posted.

**Comment by jforissier** [comment]
Quick update... I have not been able to reproduce the issue with my HiKey board yet, and found nothing with Valgrind. My board is a 2 GB RAM / 8 GB flash version however, slightly different from the IBART one.
I'm starting to think the best thing we can do is configure IBART to generate a core file on segfault (`ulimit -c unlimited`), then save this core file as well as the unstripped xtest and plugin binaries from the buildroot folder (`out-br/build/optee_test_ext-1.0/host/xtest/xtest` and `out-br/build/optee_test_ext-1.0/host/supp_plugin/f07bfc66-958c-4a15-99c0-260e4e7375dd.plugin.so`).
