### ISSUE TITLE
Check obj->link.le_prev before LIST_REMOVE in cleanup_persistent_object

### ISSUE THREAD

**Issue by secondgear7300** [OP-TEE/optee_os#4428]
optee_os/ta/pkcs11/src/object.c/create_objects can bail and call cleanup_persistent_object before LIST_INSERT_HEAD. In this case, obj->link.le_prev will remain null and ta will crash because of LIST_REMOVE.
It is better to check like
if (obj->link.le_prev != NULL)
  LIST_REMOVE(obj, link);

**Comment by etienne-lms** [comment]
Nice catch!
I think I understand. `cleanup_persistent_object()` should know if the reference is in the list (destroying an existing object) or not (cancelling a object creation). Or maybe we should change `create_object()` to reference the handle in a dummy list from where it would safely be removed.
Would you have ideas to address this?

**Comment by secondgear7300** [comment]
I think checking the existence of reference before referring to it is a common practice. Maybe it should be in the LIST_REMOVE as default. Not a huge fan of dummy list idea. It will solve this issue but could not avoid other similar misuses of LIST_REMOVE.

**Comment by etienne-lms** [comment]
I though a bit and I really prefer the dummy list. There are very few place creating a object reference.

As for testing reference initialization from  `cleanup_presistent_object()`, it should rely on a generic `LIST_IS_REFERENCED()` or like macro. The function should not deal with list internals.

Do you want to create a P-R to propose a fix?

**Comment by secondgear7300** [comment]
Why not put the reference check inside LIST_REMOVE macro? Any particular reason to against it?
```
#define	LIST_REMOVE(elm, field) do {					\
	QUEUEDEBUG_LIST_OP((elm), field)				\
	if ((elm)->field.le_next != NULL)				\
		(elm)->field.le_next->field.le_prev =			\
		    (elm)->field.le_prev;
	if ((elm)->field.le_prev != NULL)			\
	       *(elm)->field.le_prev = (elm)->field.le_next;			\
	QUEUEDEBUG_LIST_POSTREMOVE((elm), field)			\
} while (/* CONSTCOND */0)
```
If you want to insist on the dummy list idea, feel free to propose a pr since you are more clear about it. And is there a way for me to review?

**Comment by jforissier** [comment]
@secondgear7300 `LIST_REMOVE()` is a standard BSD macro (https://github.com/NetBSD/src/blob/trunk/sys/sys/queue.h#L276-L283), I see no reason to change it. It is only valid to call `LIST_REMOVE()` with `elm` being in a list, and in this case `(elm)->field.le_prev` is necessarily non-NULL being either the previous element or the list head.

**Comment by jforissier** [comment]
Any proper fix for this? Note, I don't think it is a good idea to access LIST macro internals like mentioned here: https://github.com/OP-TEE/optee_os/blob/3.12.0/ta/pkcs11/src/object.c#L111-L122.

**Comment by etienne-lms** [comment]
I agree.
@secondgear7300 ,can you follow up this P-R or do you prefer we take hand on it?

**Comment by secondgear7300** [comment]
Please go ahead take hand on it. I am not very clear about the fix for https://github.com/OP-TEE/optee_os/blob/3.12.0/ta/pkcs11/src/object.c#L111-L122.

**Comment by etienne-lms** [comment]
I've created https://github.com/OP-TEE/optee_os/issues/4428 to address @jforissier's comment (https://github.com/OP-TEE/optee_os/issues/4428#issuecomment-811692895).
