### ISSUE TITLE
Normal World Memory Access From Secure World

### ISSUE THREAD

**Issue by vicibe** [OP-TEE/optee_os#4430]
Hi,

Much like in #1343, I am trying to implement the ability to scan all of normal world memory from the secure world. I tried using ```register_phys_mem``` and it worked for small chunks of memory but my goal is to access all NS mem from secure side so I want to map the entire memory as a shared region but whenever I try that, I get a kernel panic.
I am using the qemu v7 virt platform for my testing.

From what I've found, it seems the qemu virt platform's RAM ranges from 0x40000000-0x80000000 (1G) so I added ```register_phys_mem(MEM_AREA_NSEC_SHM, 0x40000000, 0x80000000);``` to core_mmu.c, but this leads to a kernel panic (in ```carve_out_phys_mem()``` right after the ```core_is_buffer_outside``` call) on the secure side when booting.

My questions are:
1. Am I mapping the appropriate memory ranges for my platform?
2. It seems the```nsec_shared``` array in core_mmu.c needs to be modified to include the memory ranges I'm interested in monitoring, is my thinking correct?

If there is something I'm misunderstanding, I would appreciate if someone could shed some light on it.
Thanks in advance!

**Comment by jenswi-linaro** [comment]
`register_phys_mem(MEM_AREA_NSEC_SHM, TEE_SHMEM_START, TEE_SHMEM_SIZE);` is only intended to map that small shared memory pool. What you're trying to do is something quite different.
One option is find an unused range in the translation tables and map all memory there. But this depends on the amount of physical memory isn't too large.
Another option could be to again find a suitable find a suitable free place in the translation tables and map a large piece of the physical memory, do whatever you're supposed to do and and remap another piece of physical memory and repeat until done.
In both cases you'll need to do some rather low level translation table manipulations, but I suppose you'll end up doing that in one way or the other regardless.

**Comment by vicibe** [comment]
@jenswi-linaro Thanks for the quick response.

Is what was described in [#1343](https://github.com/OP-TEE/optee_os/issues/803#issuecomment-230334746) no longer applicable to the newer commits?

Also what is the purpose of the ```nsec_shared``` array in core_mmu.c? because it seems I can add an entry to cover the memory range I'm interested in without issue. Does it only specify which memory ranges one is allowed to map shared memory or does it have other notable consequences?

**Comment by jenswi-linaro** [comment]
> Is what was described in [#803](https://github.com/OP-TEE/optee_os/issues/803#issuecomment-230334746) no longer applicable to the newer commits?

It depends, it's a bit of a hack and can work in some configurations. The problem here is that since OP-TEE is instructed to use this as the shared memory pool it tries to remove that from the DTB (since the QEMU platform is configured to use DTB) so the kernel doesn't use it directly. Instead it's supposed to be mapped later on when the driver is probed. This will obviously not work.

> Also what is the purpose of the `nsec_shared` array in core_mmu.c? because it seems I can add an entry to cover the memory range I'm interested in without issue. Does it only specify which memory ranges one is allowed to map shared memory or does it have other notable consequences?

That's just a way of letting `core_pbuf_is()` know that this memory is non-secure. `core_pbuf_is()` is used at various places to check what kind of memory we're using. Usually to make sure that we're not tricked into using secure memory instead of non-secure memory.

**Comment by vicibe** [comment]
> It depends, it's a bit of a hack and can work in some configurations. The problem here is that since OP-TEE is instructed to use this as the shared memory pool it tries to remove that from the DTB (since the QEMU platform is configured to use DTB) so the kernel doesn't use it directly. Instead it's supposed to be mapped later on when the driver is probed. This will obviously not work.
> 
Are there any other methods, directly supported or not, for accessing regions of NS memory from Secure world (i.e, granting read permissions to the optee core) apart from your earlier suggestion?

Also by "driver", you are referring to the optee client-side driver?

**Comment by jenswi-linaro** [comment]
> > It depends, it's a bit of a hack and can work in some configurations. The problem here is that since OP-TEE is instructed to use this as the shared memory pool it tries to remove that from the DTB (since the QEMU platform is configured to use DTB) so the kernel doesn't use it directly. Instead it's supposed to be mapped later on when the driver is probed. This will obviously not work.
> 
> Are there any other methods, directly supported or not, for accessing regions of NS memory from Secure world (i.e, granting read permissions to the optee core) apart from your earlier suggestion?

Not unless yet another way is invented.

> Also by "driver", you are referring to the optee client-side driver?

Yes, the Linux kernel driver which it normally is.

**Comment by vicibe** [comment]
Would it be possible to bypass op-tee by modifying memory permissions in the trusted firmware source? From my understanding it might be possible to configure TZASC to allow this.

I'm sure there are some issues that will arise w/ op-tee compatibility if such changes are made, though I am not familiar enough with trusted firmware to foresee them. At this point, I am just trying to gauge if it's a path worth pursing. Would you have an idea of the level of involvement something like that would require?

**Comment by jenswi-linaro** [comment]
> Would it be possible to bypass op-tee by modifying memory permissions in the trusted firmware source? From my understanding it might be possible to configure TZASC to allow this.

Sure, you don't even need to touch the TZASC. It's just a matter of mapping the memory.

> 
> I'm sure there are some issues that will arise w/ op-tee compatibility if such changes are made, though I am not familiar enough with trusted firmware to foresee them. At this point, I am just trying to gauge if it's a path worth pursing. Would you have an idea of the level of involvement something like that would require, if possible?

Either way should work. I guess the amount of work should be more or less the same.

**Comment by vicibe** [comment]
> > Is what was described in [#803](https://github.com/OP-TEE/optee_os/issues/803#issuecomment-230334746) no longer applicable to the newer commits?
> 
> It depends, it's a bit of a hack and can work in some configurations. The problem here is that since OP-TEE is instructed to use this as the shared memory pool it tries to remove that from the DTB (since the QEMU platform is configured to use DTB) so the kernel doesn't use it directly. Instead it's supposed to be mapped later on when the driver is probed. This will obviously not work.
> 
I want to explore the possibility of stopping that device tree modification from occurring, can you point me towards where this is implemented in the source code?

**Comment by jenswi-linaro** [comment]
It happens in `core/arch/arm/kernel/boot.c` in `add_res_mem_dt_node()`.
