### ISSUE TITLE
Panic related to gic->max_it

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#4435]
Hi, our platform supports 160 interrupts and recently we met a gic panic when enabling interrupt id 159, which seems related to gic->max_it. 

_422 static void gic_op_enable(struct itr_chip *chip, size_t it)
423 {
424 >-------struct gic_data *gd = container_of(chip, struct gic_data, chip);
425 
**426 >-------if (it >= gd->max_it)
427 >------->-------panic();**                     //panic here_

From the function probe_max_it(),  it seems that gic->max_it refers to the largest interrupt id gic can support. For example, if max_it is 159, it means the total interrupts number gic can support is 160 and the largest interrupt id is 159(gic->max_it).

But from gic_it_handle and gic_op_enable,  it looks like only interrupt id less than 159 can be handled?Then how to do with interrupt id 159? Or did I miss something? Thanks. 

_392 void gic_it_handle(struct gic_data *gd)
393 {
394 >-------uint32_t iar;
395 >-------uint32_t id;
396 
397 >-------iar = gic_read_iar(gd);
398 >-------id = iar & GICC_IAR_IT_ID_MASK;
399
**400 >-------if (id < gd->max_it)
401 >------->-------itr_handle(id);**
 ..._

**Comment by jenswi-linaro** [comment]
`probe_max_it()` tries to determine that largest support interrupt id. Perhaps the function could be improved? Are you sure the id 159 is correct? Sometimes there's an offset between the system interrupt ID and what's programmed in the controller.

**Comment by tiger20081015** [comment]
I think 159 is correct. It's the real hardware interrupt id in our platform, and we will plus 32 to it for gic controller.  If we hack gd->max_it to (gd->max_it + 1), the interrupt can work correctly. 

For the improvement ,  if we assume gd->max_it is the largest support interrupt id, how about changing functions like gic_it_handle, gic_op_add, gic_op_disable...as below?

14 void gic_it_handle(struct gic_data *gd)
415 {
416 >-------uint32_t iar;
417 >-------uint32_t id;
...
422 >------ **if (id < gd->max_it) // change to if (id <= gd->max_it)**
423 >------->-------itr_handle(id);
...
}

**Comment by jenswi-linaro** [comment]
Yes, I believe you're right. It seems like an off by one error.
Do you want to make a pull request to fix this, or would you rather I take care of it?

**Comment by tiger20081015** [comment]
My pleasure to fix it. I'll submit a patch later. Thanks for your prompt reply!

**Comment by tiger20081015** [comment]
@jenswi-linaro , please help review https://github.com/OP-TEE/optee_os/pull/4450, thanks.
