### ISSUE TITLE
Missing NULL pointer check in TEE_OpenPersistentObject

### ISSUE THREAD

**Issue by snst** [OP-TEE/optee_os#4440]
Hi,

I think there is a NULL pointer check missing for parameter _TEE_ObjectHandle *object_ in TEE_OpenPersistentObject.

https://github.com/OP-TEE/optee_os/blob/16c13b4d7043d48a117ce13f818b43bbff208f08/lib/libutee/tee_api_objects.c#L396

br
stefan

**Comment by jforissier** [comment]
Hi @snst,

You're right, it looks like we're missing a `__utee_check_out_annotation(object, sizeof(*object));` there. Care to create a PR?
Thanks.

**Comment by snst** [comment]
fixed with: https://github.com/OP-TEE/optee_os/commit/2138a6f8e4ea51f92bf671df0e857f586534c280#diff-44a122074ac5c15181d8834ee27105420073a0b9a207e3cc8dbce165162aec1a
