### ISSUE TITLE
3DES CMAC supported key sizes dilemma

### ISSUE THREAD

**Issue by uglym8** [OP-TEE/optee_os#4443]
Hey guys,

I'd like to get your opinion on the following case (it might lead to the changes of the current 3DES CMAC implementation):

I added 3DES CMAC support to OP-TEE some time ago (almost everything was already
there actually, in tomcrypt and mbedTLS respectively):
https://github.com/OP-TEE/optee_os/pull/4381

I was recently challenged by my fellow engineer about the supported key
sizes and I don't have enough data to back up my point.

Let me explain (I'll use key sizes with parity bits from now on).

My current understanding is that TDEA CMAC supports 3 keys (K1-K2-K3) and 2 keys
(K1-K2-K1).
If, for instance, I need to use 2 key TDEA CMAC what I'm doing (as a consumer of
this implementation not as an author) at the moment is just copying K1 to K3 and
have K1-K2-K1 192 bit long 3DES key.
My fellow engineer challenges this implementation by saying that he should not
be obliged to do it himself and that this implementation of 3DES CMAC is wrong
(not wrong, but incomplete).
Unfortunately, I don't have any sound proof that this is not the case.

I checked mbedTLS implementation and it also supports only 192-bit 3DES keys, so
for my case I need to do exactly the same (copying K1 to K3) before I'm able to
calculate 3DES CMAC.

I also checked Nettle, which states in its documention that
"As a 112 bit key is large enough to make brute force attacks impractical, some
applications uses a “two-key” variant of triple-DES. In this mode, the same key
bits are used for the first and the last DES box in the pipe, while the middle
box is keyed independently. The two-key variant is believed to be secure, i.e.
there are no known attacks significantly better than brute force. "

I've got two options atm:
1) modify TDEA CMAC implementation in a way that if 128 bit keys are supplied,
	it will transparently copy K1 to K3 by itself without requiring a user
	to do anything at all.
	It could be implemented by I don't think that this is the right thing to
	do tbh.
2) allow only 192 bits keys to be used for TDEA CMAC.
Right now a user can pass 128 bit keys but he gets incorrect result as keys are
not automatically transformed to 192 bit representation.

But as I said I can't prove that this is the right choice (limiting the key
size) as my opponent states that this would be incomplete solution as he 
thinks that he doesn't have to copy anything in case of 128 bit keys.

What do you think?

Thanks in advance.

P.S. I also asked mbedTLS guys for their opinion
https://github.com/ARMmbed/mbedtls/issues/4195

**Comment by jforissier** [comment]
Hi,

> I've got two options atm:
> 
>     1. modify TDEA CMAC implementation in a way that if 128 bit keys are supplied,
>        it will transparently copy K1 to K3 by itself without requiring a user
>        to do anything at all.
>        It could be implemented by I don't think that this is the right thing to
>        do tbh.
> 
>     2. allow only 192 bits keys to be used for TDEA CMAC.
>        Right now a user can pass 128 bit keys but he gets incorrect result as keys are
>        not automatically transformed to 192 bit representation.

There is a footnote in the TEE Internal Core API Spec that reads "Triple DES SHALL be understood as Encrypt-Decrypt-Encrypt mode with two or three keys." but that does not give much information about the format of the key.

I could not find a test case for this in the GP test suite either (`TEE_Initial_Configuration-Test_Suite_v2_0_0_2-2017_06_09.7z`).

Why do you think option 1 is bad? It sounds pretty good to me from a user perspective at least...

**Comment by uglym8** [comment]
@jforissier, thanks a lot for your prompt reply.
I'll create a PR implementing the first approach then.

**Comment by jenswi-linaro** [comment]
Note that we have the function `get_des2_key()` in `core/lib/libtomcrypt/des2_key.h` to deal with this.

**Comment by uglym8** [comment]
@jenswi-linaro, thank you for the suggestion

**Comment by jforissier** [comment]
> Note that we have the function `get_des2_key()` in `core/lib/libtomcrypt/des2_key.h` to deal with this.

I don't see a similar thing in the MBed TLS implementation. In other words, `core/lib/libtomcrypt/{ecb,cbc}.c` seem to take care of the 128 bit key properly but `lib/libmbedtls/core/des3_{ecb,cbd}.c` seem to behave differently. I think we need a test in `xtest` and we need to make sure the behavior is the same in both cases.
