### ISSUE TITLE
Is Curve25519 support in optee available ?

### ISSUE THREAD

**Issue by asad2408** [OP-TEE/optee_os#4444]
Dear All,
Can you please confirm "is there support for Curve25519 in optee ?"

if it's not there " do we have any plan date to support it ?"

**Comment by jforissier** [comment]
> Dear All,
> Can you please confirm "is there support for Curve25519 in optee ?"

No, not supported.
 
> if it's not there " do we have any plan date to support it ?"

I'm not aware of any plan. Last time I check there was better support for 25519 in LibTomCrypt than in MBed TLS, so an implementation over LTC shouldn't be too hard.

**Comment by jforissier** [comment]
Forgot to add the usual conclusion: "patches welcome" :wink:

**Comment by ldts** [comment]
> Forgot to add the usual conclusion: "patches welcome" :wink: 

there is support for it in the SE50 though (just need this device on an I2C port)
