### ISSUE TITLE
Secure Storage: Can an impersonate TA access the storage of another TA by reusing its UUID?

### ISSUE THREAD

**Issue by JamesMenetrey** [OP-TEE/optee_os#4447]
Dear OP-TEE developers,

I read the well-documented wiki page about the secure storage of OP-TEE, mostly the crypto part about the keys generation. Before diving into the details, I just would like to summarize my understanding:

- Secure Storage Key (SSK) is device-bound;
- Trusted Application Storage Key (TSK) is TA-bound, by UUID;
- the UUID of a TA can be extracted from its binary;
- File Encryption Key (FEK) is file-bound;
- A file is encrypted and decrypted using FEK and TSK, based on [this schema](https://optee.readthedocs.io/en/latest/architecture/secure_storage.html#meta-data-encryption-flow).

Assuming the summary is correct, what would prevent a malicious developer to reuse the UUID of a given TA (since it is public) to access its secure storage? As a result, the derivation of TSK would be the same, since `TSK = HMAC(SSK, TA_UUID)`. As a result, I can recover FEK using TSK from the encrypted FEK, by applying `AES_dec(encrypted_FEK, TSK)`.

Thanks!

**Comment by etienne-lms** [comment]
True, the one who signs the TAs can hack into any TA or replace UUIDs.
The owner of the TA authen key must be trustful.
Some PKI for delegated TA authentication would be nice. Patches and proposals are welcome.

**Comment by JamesMenetrey** [comment]
Hey @etienne-lms,

Thanks for your fast reply! My next question is: can a malicious person with OS privileges may change the public key (the one mentioned [here](https://optee.readthedocs.io/en/latest/building/trusted_applications.html#signing-of-tas)) to run its compromised TAs? In other words, if the OS is compromised, would it defeat the code signing and enables the execution of untrusted TAs?

Thanks!

**Comment by etienne-lms** [comment]
If Linux (more generically non-secure OS) is compromised, no secret shall still leak from OP-TEE secure firmware and its TAs.
This is realized by the RoT and CoT that ends in OP-TEE relying on a public keys it trusts.
Embedding the public inside OP-TEE code firmware make it as trustful as the fmw itself. This is a way.

**Comment by JamesMenetrey** [comment]
Thanks for the insights! Last set of questions regarding this topic:

 - Is the firmware resilient to hardware attacks? In particular, I'm thinking of turning off the device, patching OP-TEE to change that public key (since SSK is not bound to the OP-TEE code). Is there any built-in mechanism to prevent this type of attack, or should I rely on additional security measures, such as disk encryption?
 - Finally, is there an article or documentation about the threat model of OP-TEE (so I can refer to it for such further questions)?

Again, thanks for your time!

**Comment by etienne-lms** [comment]
> Is the firmware resilient to hardware attacks? In particular, I'm thinking of turning off the device, patching OP-TEE to change that public key (since SSK is not bound to the OP-TEE code). Is there any built-in mechanism to prevent this type of attack, or should I rely on additional security measures, such as disk encryption?

Corrupting OP-TEE image in disk/flash/... prior boot time should be detected by the boot stages when authenticating booted images. As done in TF-A (TTBR).

Corruption of OP-TEE memory at execution is more problematic :) . A platform embedding OP-TEE should also have some  means to protect the secure memory where OP-TEE executes.

Disk encryption would not really help. Prefer rely on a secure boot scheme using image authentication by boot stages and memory firewalling/scrambling/encryption among other HW isolation and tamper resilient tricks.

> Finally, is there an article or documentation about the threat model of OP-TEE (so I can refer to it for such further questions)?

Lots of threats since lots of service provided by OP-TEE. I have no specific link in mind :(
Maybe one around may help...

**Comment by jforissier** [comment]
>     * Finally, is there an article or documentation about the threat model of OP-TEE (so I can refer to it for such further questions)?

Nothing specific about OP-TEE but general things applicable to GlobalPlatform-compliant TEEs can be found in the TEE Protection Profile document: https://globalplatform.org/specs-library/tee-protection-profile-v1-3/.

**Comment by JamesMenetrey** [comment]
Dear @etienne-lms and @jforissier,

Thank you very much for all these details! I learned a lot of details related to OP-TEE and secure boot!

Have a great weekend!
Cheers
