### ISSUE TITLE
Can complete OPTEE solution run in SRAM? How about OPTEE memory footprint?

### ISSUE THREAD

**Issue by thomas-coding** [OP-TEE/optee_os#4449]
On our platform, there is only SRAM ,and no DDR, so we need to run the complete optee + linux in SRAM, is this feasible? If so, how much memory does optee core need (the platform is arm arch32).

If  can, I want to verify it on QEMU first. How do I configure it?

Thanks.

**Comment by jenswi-linaro** [comment]
It depends on how much SRAM you have. But I guess the answer is will be no.

**Comment by thomas-coding** [comment]
Got it~
Thanks
