### ISSUE TITLE
generated ec Key to PEM

### ISSUE THREAD

**Issue by Greekee** [OP-TEE/optee_os#4454]
Hello,
is there a way to convert a new generated ECDSA Keypair into the pem format (maybe private and public), so that I can output the public pem part to the real world application?
And if not, have can I achieve this in the "easiest" way?

**Comment by jforissier** [comment]
Hi @Greekee,

There is no way to do what you're asking using the GP APIs, however you should be able to achieve your goal with a few MBed TLS function calls. I have not tried myself but that could work:
- Create a `mbedtls_rsa_context` with yur keypair or public key with `mbedtls_rsa_import()/mbedtls_rsa_import_raw()/mbedtls_rsa_complete()`, see https://tls.mbed.org/kb/development/how-to-fill-rsa-context-from-n-e-p-and-q
- Create a `mbedtls_pk_context` from the above with `mbedtls_pk_setup()` and `memcpy()`, see https://forums.mbed.com/t/write-rsa-public-key-top-pem/4524/2
- Finally use `mbedtls_pk_write_key_pem()` to generate the PEM.

**Comment by Greekee** [comment]
tank you for your fast response.

I already thought that there is no easy API. I also tried arpund with MBed TLS, but not very successfull

Maybe I'm missing something, or doing something completle wrong.

Striped down I'm doing the following, generating a key, get the private, and public values.
Create the MBed context parse the values and try to write the pem.
But for the private PEM I get the error.

```
TEE_InitValueAttribute(&curv_attr, TEE_ATTR_ECC_CURVE, TEE_ECC_CURVE_NIST_P256, 0);
TEE_GenerateKey(key, keysize, &curv_attr, 1);
TEE_GetObjectBufferAttribute(key, TEE_ATTR_ECC_PRIVATE_VALUE, priv, &priv_len);
TEE_GetObjectBufferAttribute(key, TEE_ATTR_ECC_PUBLIC_VALUE_X, X, &X_len);
TEE_GetObjectBufferAttribute(key, TEE_ATTR_ECC_PUBLIC_VALUE_Y, Y, &Y_len);

mbedtls_pk_context pk;
mbedtls_pk_init(&pk);

mbedtls_pk_setup(&pk, mbedtls_pk_info_from_type(MBEDTLS_PK_ECKEY));
mbedtls_ecp_keypair *pk_pair = mbedtls_pk_ec(pk);

mbedtls_ecp_group_init(&pk_pair->grp);
mbedtls_ecp_group_load(&pk_pair->grp, MBEDTLS_ECP_DP_SECP256K1);
mbedtls_ecp_point_init(&pk_pair->Q);
mbedtls_mpi_init(&pk_pair->d);

mbedtls_mpi_read_binary(&pk_pair->d, priv, priv_len);
mbedtls_mpi_read_binary(&pk_pair->Q.X, X, X_len);
mbedtls_mpi_read_binary(&pk_pair->Q.Y, Y, Y_len);
mbedtls_mpi_lset(&pk_pair->Q.Z, 1);

unsigned char buf[500];
mbedtls_pk_write_pubkey_pem(&pk, buf, sizeof(buf));
printf("%s\n\n", buf);
mbedtls_pk_write_key_pem(&pk, buf, sizeof(buf));
printf("%s\n\n", buf);
```
```
E/TC:? 0 
E/TC:? 0 User mode data-abort at address 0x10f5bc (write permission fault)
E/TC:? 0  fsr 0x0000080f  ttbr0 0x24067859  ttbr1 0x24060059  cidr 0x2
E/TC:? 0  cpu #0          cpsr 0x60000130
E/TC:? 0  r0 0x00110c38      r4 0x00000000    r8 0x000001f4   r12 0xfffd3950
E/TC:? 0  r1 0x0010f5c0      r5 0x0010f5d0    r9 0x00110c38    sp 0x0010f5a8
E/TC:? 0  r2 0x0000162f      r6 0x0010f5c0   r10 0x00110c4c    lr 0x00115245
E/TC:? 0  r3 0x00000000      r7 0x00110cac   r11 0x00110c8c    pc 0x0011eefa
E/LD:  Status of TA 4e42242e-1a71-493b-a10e-9ae4d2550988
E/LD:   arch: arm
E/LD:  region  0: va 0x00102000 pa 0x24100000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x00104000 pa 0x24102000 size 0x006000 flags r-xs (ldelf)
E/LD:  region  2: va 0x0010a000 pa 0x24108000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x0010b000 pa 0x24109000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x0010f000 pa 0x2410d000 size 0x001000 flags r--s
E/LD:  region  5: va 0x00110000 pa 0x24138000 size 0x001000 flags rw-s (stack)
E/LD:  region  6: va 0x00115000 pa 0x00001000 size 0x01b000 flags r-xs [0]
E/LD:  region  7: va 0x00130000 pa 0x0001c000 size 0x00f000 flags rw-s [0]
E/LD:   [0] 4e42242e-1a71-493b-a10e-9ae4d2550988 @ 0x00115000
E/LD:  Call stack:
E/LD:   0x0011eefa

```

**Comment by Greekee** [comment]
No I'm not developing with QEMU, just directly for the ARM target and testing there, which wasn't a problem until now.

**Comment by jforissier** [comment]
I see. Don't you have more addresses in the call stack dump? You could use `scripts/symbolize.py`.

**Comment by Greekee** [comment]
No, the dump I posted is all what I get.
What do you mean with scripts/symbolize.py
