### ISSUE TITLE
Fast development work flow for PTA and core

### ISSUE THREAD

**Issue by AsmX0r** [OP-TEE/optee_os#4455]
Hi there!

I'm interested in the development of a PTA. For my regular TAs, I usually start QEMU with `make run` once and then mount the host file system and perform copy of my compiled TA into the REE FS each time I need to verify my progress. Hence, the development work flow goes fairly fast.

What is the work flow you recommend for developing PTA and more generally when you apply changes to the OP-TEE core? Regarding the PTA, I think a working work flow is to run `make optee-os` then `make run`, which is sensibly longer than regular TA development.

Do you guys have a faster way of building and testing PTA?

Thanks!

**Comment by etienne-lms** [comment]
`make optee-os && make run-only`

**Comment by AsmX0r** [comment]
Thanks!
