### ISSUE TITLE
Access TA after BL32 (Optee) has booted, but before BL33 (U-boot) is booting inside TF-A

### ISSUE THREAD

**Issue by EchtPeter** [OP-TEE/optee_os#4456]
Hello

I want to access my TA after BL32 has booted but before BL33 boots. I managed to get access to my TA inside U-boot, Kernel and regular application. The TA which I want to access is compiled as an early TA. Maybe there is an "easy" way to do is, because we are still in the secure world. My question is: Is there an easy way?

Also I found out the drivers in the U-boot and Kernel uses SMC do access the TA. Is there a possibility that I have to create my own SMC and then trigger it to get access to my TA?

What I ultimately want is to Hash over u-boot and save it into the TA memory. 

Thanks in advance!

**Comment by jenswi-linaro** [comment]
Who is going to call the TA?

**Comment by EchtPeter** [comment]
I want to call my TA while I‘m still inside trusted firmware. So I can hash over U-boot (before the trusted firmware hands over control to u-boot) and save it inside my TA.

**Comment by jenswi-linaro** [comment]
Entering a TA in this way is not something that's normally supported. I'm afraid there's no easy way of doing this. 

This sounds like yet another approach to measured boot.

**Comment by EchtPeter** [comment]
Yes basically I do measured boot. Isn’t there a work around like having shared memory between TAs and Trusted firmware. (Because they are both running the secure world)

Like the TF does save the measurement in Ram at a pre determine address and the TA access it as soon it can be called?

**Comment by jenswi-linaro** [comment]
There's a thing with `tpm_get_event_log()` and friends in `core/kernel/tpm.c` where some buffer initialized by TF-A is picked up by OP-TEE allowing a TPM TA to get the TPM event log when it's started. Perhaps you can find a way to piggyback on that?

**Comment by EchtPeter** [comment]
Yeah! Thank you.

What I did is basically inside TF-A I made a global array like so
`char array [0x200] = {};`
Then I read out the address which the array is stored with
`printf("%p", (void*) &array);`
Which after multiple compiles seems to never change the address. (Because there is no malloc in TF-A???)
After that I changed the address inside the `conf.mk` file to the array address.
`CFG_TPM_LOG_BASE_ADDR ?= 0xe0233ec `

I also had to change two lines in Optee_os code. For whatever reason make would not do this:
`make EARLY_TA_PATHS=/path/to/my/earlyTA  CFG_CORE_TPM_EVENT_LOG=y CFG_DT=n run`
It would always complain that `CFG_DT` has to be `=y`
```c
static void get_tpm_phys_params(void *fdt __maybe_unused,
				paddr_t *addr, size_t *size)
{
+	*size = CFG_TPM_MAX_LOG_SIZE;
+	*addr = CFG_TPM_LOG_BASE_ADDR;
#ifdef CFG_DT
	int node = 0;
	const char *dt_tpm_match_table = {
		"arm,tpm_event_log",
	};

	if (!fdt) {
		EMSG("TPM: No DTB found");
		return;
	}

	node = fdt_node_offset_by_compatible(fdt, -1, dt_tpm_match_table);

	if (node < 0) {
		EMSG("TPM: Fail to find TPM node %i", node);
		return;
	}

	if (read_dt_tpm_log_info((void *)fdt, node, addr, size) < 0) {
		EMSG("TPM: Fail to retrieve DTB properties from node %i",
		     node);
		return;
	}
#else
	*size = CFG_TPM_MAX_LOG_SIZE;
	*addr = CFG_TPM_LOG_BASE_ADDR;
#endif /* CFG_DT */
}
```
So I added those lines. (Not clean but gets the job done.)
To access the array I used the code in xtest1024 inside my Early TA and it works.

Again thank you for giving me that hint with that! @jenswi-linaro
