### ISSUE TITLE
[RPMB]: Erase of the allocated block

### ISSUE THREAD

**Issue by divneil** [OP-TEE/optee_os#4458]
Hello,

I am looking for a solution to erase RPMB partition.
As I understand, erase commands don't work on RPMB, so, the option left is to either:

- over-write full partition: 
  o This will require access to eMMC hardware in optee-os for directly issuing the write command.
  o A block write(=partition size) will be required to over-write the partition to 0s or 1s.

OR
- over-write the existing objects: 
  o This will require scanning the existing objects from the RPMB fs
  o Selective issue of write commands per object
  o It seems that a write of an object may not necessarily over-write the same write block next time due to wear levelling.

Can you please help with any reference code or pointers to help me kick-start. In your opinion, what could potentially be a workable solution?

Regards,
Divneil

**Comment by jforissier** [comment]
Hi @divneil,

RPMB does have an ERASE command (CMD38) with many options. Depending on you exact needs, you could probably implement the proper command in OP-TEE.

**Comment by jforissier** [comment]
You're right, I totally missed that, sorry. What are you trying to accomplish? Make the partition empty, without any particular requirement on the actual erasure of the data in the un-allocated blocks? Or do you want to make sure the data are irrecoverable?

- For the first use case, you can find some code guarded by `CFG_RPMB_RESET_FAT` in `rpmb_fs_setup()` which will simply reset the file allocation table on startup: https://github.com/OP-TEE/optee_os/blob/3.12.0/core/tee/tee_rpmb_fs.c#L2041-L2082.
- If you need to really scrub the blocks, then calling `tee_rpmb_write_blk()` in a loop to write zeros or ones or whatever should do the trick I think.

**Comment by divneil** [comment]
> You're right, I totally missed that, sorry. What are you trying to accomplish? Make the partition empty, without any particular requirement on the actual erasure of the data in the un-allocated blocks? Or do you want to make sure the data are irrecoverable?

No worries. I am trying to scrub the full RPMB partition so that any data is irrecoverable.

> * For the first use case, you can find some code guarded by `CFG_RPMB_RESET_FAT` in `rpmb_fs_setup()` which will simply reset the file allocation table on startup: https://github.com/OP-TEE/optee_os/blob/3.12.0/core/tee/tee_rpmb_fs.c#L2041-L2082.
> * If you need to really scrub the blocks, then calling `tee_rpmb_write_blk()` in a loop to write zeros or ones or whatever should do the trick I think.

Thanks for the pointer. I will take a day or two to look into `tee_rpmb_write_blk()`. If it takes more time for me to come back, I will close the ticket for time being.

**Comment by divneil** [comment]
Does `tee_rpmb_write()` calculates block_index always on `fat_address`? `fs_par->fat_start_address` starts from 512, so, first 2 indexes (0 and 1) are never written to. Is there any particular reason for this?

I am calling `tee_rpmb_write_blk()` with blk_idx = 0 till `rpmb_ctx->max_blk_idx` (inclusive). I hope this does the scrubbing.

**Comment by jforissier** [comment]
> Does `tee_rpmb_write()` calculates block_index always on `fat_address`? `fs_par->fat_start_address` starts from 512, so, first 2 indexes (0 and 1) are never written to. Is there any particular reason for this?

Block 0 contains `struct rpmb_fs_partition`, see `rpmb_fs_setup()`. Block 1 is not used as far as I can tell.

> I am calling `tee_rpmb_write_blk()` with blk_idx = 0 till `rpmb_ctx->max_blk_idx` (inclusive). I believe this completes the scrubbing.

I think so.

**Comment by divneil** [comment]
> Block 0 contains `struct rpmb_fs_partition`, see `rpmb_fs_setup()`. Block 1 is not used as far as I can tell.

Thanks for the info. I am observing a side effect after scrubbing (tried both from idx = 0 and idx = 2). 
I am unable to recreate a persistent object in RPMB partition. I will try it on a newer optee-os version, but I guess that won't fix this problem.
