### ISSUE TITLE
How to mark multiple secure memory regions as MEM_AREA_TEE_RAM?

### ISSUE THREAD

**Issue by xiangmy** [OP-TEE/optee_os#4460]
Hi OPTEE group,

If I have several ranges of addresses for secure memory which are protected by TZC, is it necessary to mark each of them as [`MEM_AREA_TEE_RAM`](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/include/mm/core_mmu.h#L88)  when I [register](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/include/mm/core_mmu.h#L222-L225) them? The problem is that only one memory area can be marked as `MEM_AREA_TEE_RAM` in my understanding, otherwise, [`check_mem_map()`](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/core_mmu.c#L1125-L1165) will panic. Or, can TZSRAM/TZDRAM stride across different memory regions? (not sure about this) So, is it okay that I set my secure memory regions as `MEM_AREA_RAM_SEC` instead of `MEM_AREA_TEE_RAM`, or are there some better options?

Thanks,
Mingyuan

**Comment by etienne-lms** [comment]
Hello @xiangmingyuan,

TEE_RAM is where OP-TEE core executes (with its heap, stacks, ...).  Core is built as a monolithic firmware that executes in a contiguous RAM. So TEE_RAM shall be a contiguous piece of RAM.
Core also runs TAs. These can be loaded at another physical address range (or next to TEE_RAM is preferred). It's called TA_RAM. Currently OP-TEE supports a single contiguous TA_RAM. But patches are welcome to consider more TA_RAMs.

If the several secure RAM you want to use in OP-TEE are extra RAM you want to simply map and read/write to, that register them as cacheable secure RAM, that is `MEM_AREA_RAM_SEC` as you mention.

**Comment by xiangmy** [comment]
Hi @etienne-lms ,

Thanks for the reply! So, the TA and TEE have two pieces of **contiguous** RAM which don't need to be aside, right?

> If the several secure RAM you want to use in OP-TEE are extra RAM you want to simply map and read/write to, that register them as cacheable secure RAM, that is MEM_AREA_RAM_SEC as you mention.

In this case, how can I manage and use these secure RAM? Do I just register them and leave everything to the `optee os`?

BTW, for RAM that is cacheable, I cannnot use it (which is strange). The following is a piece of my memmap printed in uefi shell:

```
Shell> memmap
Type       Start            End              # Pages          Attributes
Available  0000000080000000-00000000CFFFFFFF 0000000000050000 000000000000000E
Available  0000002000000000-000000237FFFFFFF 0000000000380000 000000000000000F
```
I can map `0000000080000000-00000000CFFFFFFF` but fail to map `0000002000000000-000000237FFFFFFF`. The full details of attricbutes can be found [here](https://github.com/torvalds/linux/blob/2c405d1ab8b3103df2df541aaacc2113dc6c9fac/include/linux/efi.h#L93-L126).

Thanks,
Mingyuan

**Comment by James567** [comment]
Hi @xiangmy 
I am also doing similar experiments .
when I register like below :
``` 
register_phys_mem(MEM_AREA_RAM_SEC, SECURE_MEM_START, SECURE_MEM_SIZE);

 ```
i got error message like:
```
check_phys_mem_is_outside:344 Non-sec mem (0xc0000000:0x1e000000) overlaps map (type 12 0xd8000000:0x100000)
Panic

```
Do you have any suggest?

Thanks,
James

**Comment by xiangmy** [comment]
Hi @James567 

> ```
> check_phys_mem_is_outside:344 Non-sec mem (0xc0000000:0x1e000000) overlaps map (type 12 0xd8000000:0x100000)
> Panic
> ```
Never encounter this error before. I suppose maybe you overlap two regions? (`0xc0000000:0x1e000000` and `0xd8000000:0x100000`).

The problem I'm facing is how to use these memory regions. As @etienne-lms indicates above, there is only one TA RAM and one core RAM. So, I'm working on adding more TA_RAMs to the system.

Thanks,
Mingyuan

**Comment by James567** [comment]
> The problem I'm facing is how to use these memory regions. As @etienne-lms indicates above, there is only one TA RAM and one core RAM. So, I'm working on adding more TA_RAMs to the system.
> 
> Thanks,
> Mingyuan

I found this issue #1347 ,  hope it helps.
