### ISSUE TITLE
USER_TA_PROP_TYPE_BINARY_BLOCK & base64 encoding

### ISSUE THREAD

**Issue by paswan-ms** [OP-TEE/optee_os#447]
I'm adding a Microsoft specific property that is a 32-byte binary blob implemented using the same pattern as the UTEE_PROP_TEE_DEV_ID. For the other defined properties the data is returned in binary form, however for the binary blob format the definition is different:

	USER_TA_PROP_TYPE_BINARY_BLOCK,	/* zero terminated base64 coded string */

As far as I can tell, there's no prior use of this format in OpTEE (there are no default properties that use it). The base64 functions are included in libutee but not in OpTEE kernel. It looks like I have two options:

1) Bring in base64_enc from libutee into the OpTEE kernel and then use that to encode the blob.
2) Switch the implementation of USER_TA_PROP_TYPE_BINARY_BLOCK to transfer in raw binary form instead of base64 form.

Was there a specific reason that the binary format was implemented as base64 rather than raw binary?

Thanks,
Paul.

**Comment by jenswi-linaro** [comment]
The GP specification says that binary blocks should be base64 encoded, no other reason.

I would prefer if we transferred the property as raw data in the syscall interface (to avoid adding a base64 encoder in TEE Core) and base64 encoded it in secure user space. The base64 encoding would typically occur in the `get()` function of the property.

/Jens

**Comment by paswan-ms** [comment]
OK, thanks. I've defined a new prop_value entry below that has worked OK but I still need to update the string get to do the encode now (that I missed until you mentioned it above):

    struct prop_value {
	    enum user_ta_prop_type type;
	    union {
		    bool bool_val;
		    uint32_t int_val;
		    TEE_UUID uuid_val;
		    TEE_Identity identity_val;
		    char str_val[PROP_STR_MAX];
            struct {
                size_t len;
                uint8_t val[PROP_BIN_MAX];
            } binary;
	    } u;
    };

Thanks,
Paul.

**Comment by pascal-brand-st** [comment]
Implemented in https://github.com/OP-TEE/optee_os/pull/656
