### ISSUE TITLE
Question: How does Tee core verify Early TA?

### ISSUE THREAD

**Issue by woodrow-shen** [OP-TEE/optee_os#4473]
Hi,

I'm reading this commit (https://github.com/OP-TEE/optee_os/commit/d0c636148b3a) to understand the Early TA details and I notice that `EARLY_TA_PATHS=path/to/<uuid>.stripped.elf` which is using stripped ELF file. Is the stripped ELF already signed by the private key or not? If it's not signed yet, does it mean Early TAs will be raw binaries which are embedded into Tee core due to core will be signed via fiptool or similar way? Or Early TAs will still be signed somewhere?

Thanks,

**Comment by etienne-lms** [comment]
Early TAs are stored inside core image hence are signed and authenticated together with OP-TEE core image(s) by the secure bootloader.

**Comment by woodrow-shen** [comment]
Thx for answer :)
