### ISSUE TITLE
Panic occurs during optee startup

### ISSUE THREAD

**Issue by carrionbent** [OP-TEE/optee_os#4474]
I’m upgrade OPTEE OS from 3.2 to 3.6.0 on MTK 2712 platform, but failed to boot up, and the following information was printed，could someone help？

BL2 Build Time: Mar 16 2021 03:20:17
verify fit conf sig: tee_a
verify fit conf sig: bl33_a
LK run time: 472739 (us)
jump to next ep 0x42ff6000, arg (0x43200000)
[LIB] HW ENC
[LIB] HW ENC
[LIB] HW ENC
[teeloader] tl jump to atf!
[ATF](0)[0.474585]INFO:    LK is AArch64
[ATF](0)[0.475035]INFO:    mmap atf buffer : 0x44e00000, 0x40000
[ATF](0)[0.475769]INFO:    mmap atf buffer (force 2MB aligned): 0x44e00000, 0x200000
[ATF](0)[0.476725]INFO:    mmap log store buffer (force 2MB aligned): 0x43e00000, 0x200000
[ATF](0)[0.485240]INFO:    abnormal_boot: 0x0, cflag: 0x0
[ATF](0)[0.491306]INFO:    mt_log_setup
[ATF](0)[0.491729]INFO:     -buf_addr: 0x44e00100
[ATF](0)[0.492278]INFO:     -buf_size: 0x29f00
[ATF](0)[0.492795]INFO:     -write_pos: 0x44e00100
[ATF](0)[0.493355]INFO:     -read_pos: 0x44e00100
[ATF](0)[0.493904]INFO:     -atf_buf_lock: 0x0
[ATF](0)[0.494421]INFO:     -log_buf_end : 0x44e29fff
[ATF](0)[0.495013]INFO:     -ATF_EXCEPT_BUF_SIZE_PER_CPU : 0x1000
[ATF](0)[0.495735]INFO:     -ATF_EXCEPT_BUF_SIZE : 0xa000
[ATF](0)[0.496370]INFO:     -PLATFORM_CORE_COUNT : 0xa
[ATF](0)[0.496973]INFO:     -atf_except_write_pos_per_cpu[0]: 0x44e32000
[ATF](0)[0.497770]INFO:     -atf_except_write_pos_per_cpu[1]: 0x44e33000
[ATF](0)[0.498567]INFO:     -atf_except_write_pos_per_cpu[2]: 0x44e34000
[ATF](0)[0.499364]INFO:     -atf_except_write_pos_per_cpu[3]: 0x44e35000
[ATF](0)[0.500161]INFO:     -atf_except_write_pos_per_cpu[4]: 0x44e36000
[ATF](0)[0.500958]INFO:     -atf_except_write_pos_per_cpu[5]: 0x44e37000
[ATF](0)[0.501755]INFO:     -atf_except_write_pos_per_cpu[6]: 0x44e38000
[ATF](0)[0.502552]INFO:     -atf_except_write_pos_per_cpu[7]: 0x44e39000
[ATF](0)[0.503348]INFO:     -atf_except_write_pos_per_cpu[8]: 0x44e3a000
[ATF](0)[0.504145]INFO:     -atf_except_write_pos_per_cpu[9]: 0x44e3b000
[ATF](0)[0.504943]INFO:     -crash_flag : 0x41544641
[ATF](0)[0.505524]INFO:     -crash_log_addr : 0x44e2a000
[ATF](0)[0.506149]INFO:     -crash_log_size : 0x8000
[ATF](0)[0.506757]INFO:    ATF log service is registered (0x44e00000, aee:0x44e3c000)
[ATF](0)[0.507677]NOTICE:  BL31: v1.6(debug):REL_AS22LAVN1AAE7ME_3.0.2-R-20201127.0314-3-ga1cf21c
[ATF](0)[0.508743]NOTICE:  BL31: Built : 03:20:18, Mar 16 2021
[ATF](0)[0.509435]INFO:    SPM_POWERON_CONFIG_SET_0x10006000=0x1
[ATF](0)[0.510144]INFO:    BYPASS_SPMC_0x10006c5c=0x0
[ATF](0)[0.510735]INFO:    [spmc_init]change to SPMC mode !!!
[ATF](0)[0.511436]WARNING: Using deprecated integer interrupt array in gicv2_driver_data_t
[ATF](0)[0.512410]WARNING: Please migrate to using an interrupt_prop_t array
[ATF](0)[0.513250]INFO:    ARM GICv2 driver initialized
[ATF](0)[0.513889]INFO:    ptr = 0x4300fcd8, len = 2021
[ATF](0)[0.514504]INFO:    BL31: Initializing runtime services
[ATF](0)[0.515202]INFO:    BL31: Initializing BL32
D/TC:0 0 add_phys_mem:576 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x45000000 size 0x0006d000
D/TC:0 0 add_phys_mem:576 VCORE_UNPG_RO_PA type TEE_RAM_RO 0x4506d000 size 0x0001b000
D/TC:0 0 add_phys_mem:576 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x45088000 size 0x00178000
D/TC:0 0 add_phys_mem:576 TA_RAM_START type TA_RAM 0x45200000 size 0x00e00000
D/TC:0 0 add_phys_mem:576 TEE_SHMEM_START type NSEC_SHM 0x46000000 size 0x01000000
D/TC:0 0 add_phys_mem:576 ROUNDDOWN(0x11002000, CORE_MMU_PGDIR_SIZE) type IO_NSEC 0x11000000 size 0x00200000
D/TC:0 0 add_phys_mem:576 ROUNDDOWN((((0x10000000) + 0x510000)+0x10000), CORE_MMU_PGDIR_SIZE) type IO_SEC 0x10400000 size 0x00400000
D/TC:0 0 add_phys_mem:576 ROUNDDOWN((((0x10000000) + 0x510000)+0), CORE_MMU_PGDIR_SIZE) type IO_SEC 0x10400000 size 0x00400000
D/TC:0 0 add_phys_mem:589 Physical mem map overlaps 0x10400000
D/TC:0 0 add_phys_mem:576 ROUNDDOWN(((0x10000000) + 0x220000), CORE_MMU_PGDIR_SIZE) type IO_SEC 0x10200000 size 0x00200000
D/TC:0 0 add_phys_mem:576 TRNG_BASE type IO_NSEC 0x1020f000 size 0x00000020
D/TC:0 0 add_phys_mem:576 INFRACFG_AO_BASE type IO_NSEC 0x10001000 size 0x00001000
D/TC:0 0 add_phys_mem:576 DEVAPC_AO_BASE type IO_SEC 0x1000e000 size 0x00001000
D/TC:0 0 add_phys_mem:576 DEVAPC_PD_BASE type IO_SEC 0x10207000 size 0x00001000
D/TC:0 0 add_phys_mem:589 Physical mem map overlaps 0x10207000
D/TC:0 0 add_phys_mem:576 PERICFG_BASE_ADDR type IO_NSEC 0x10003000 size 0x00001000
D/TC:0 0 add_phys_mem:576 EMI_MPU_BASE type IO_NSEC 0x1020e000 size 0x00001000
D/TC:0 0 add_phys_mem:576 GPT_BASE type IO_NSEC 0x10008000 size 0x000000a0
D/TC:0 0 verify_special_mem_areas:514 No NSEC DDR memory area defined
D/TC:0 0 add_va_space:615 type RES_VASPACE size 0x00a00000
E/TC:0 0 add_va_space:618 Out of entries (14) in memory_map
E/TC:0 0 Panic at core/arch/arm/mm/core_mmu.c:619 <add_va_space>
E/TC:0 0 Call stack:
E/TC:0 0  0x000000004500f7b0

**Comment by jenswi-linaro** [comment]
It looks like you need to increase `CFG_MMAP_REGIONS`.
If you're upgrading, why not go for the latest? 3.6.0 is a bit old that too. Is there something in the lastest you'd like to avoid? If so, perhaps we can make it configurable and optional?

**Comment by carrionbent** [comment]
Thank you for your reply, I have made a lot of changes on the basis of version 3.2.0. If upgrade to the latest version, there will be a lot of work. Maybe I will upgrade to the latest version later
