### ISSUE TITLE
How OPTEE gic support GICV3 when affinity routing enabled

### ISSUE THREAD

**Issue by Chengweiadp** [OP-TEE/optee_os#4475]
I found OPTEE interrupt framework is implemented through GIC Distributor controlling, for example write GICD_SGIR to raise SGI, but according to GICV3 specification, GICD_SGIR is used only when affinity routing is not enabled. When affinity routing is enabled, this register is RES0. There is similar situation about the PPI operations. I tested the interfaces with a GIC(GIC600) enabled affinity routing, result is SGI and PPI function not correct.
         Is there any simple way to support GICV3 with affinity routing enabled? If no, does Linaro have any plan to support it in the future

**Comment by jenswi-linaro** [comment]
I'm not aware of work planned for the interrupt framework in OP-TEE. This is evolved in the way that features has been added as they where needed. Patches are welcome! :-)
