### ISSUE TITLE
Better call memzero_explicit in op_attr_secret_value_clear?

### ISSUE THREAD

**Issue by snst** [OP-TEE/optee_os#4476]
Hi!

What do you think, would it not be better to call memzero_explicit instead of memset?

https://github.com/OP-TEE/optee_os/blob/c95980b13c3a229435d29c52a65183523d2ac99e/core/tee/tee_svc_cryp.c#L658

br
stefan

**Comment by jforissier** [comment]
Hi @snst,

I doubt the compiler would optimize out this `memset()` call, but `memzero_explicit()` would certainly make sense here. Do you want to create a PR?
