### ISSUE TITLE
How to generate ephemeral secret key used in SM2 secret key exchange protocol?

### ISSUE THREAD

**Issue by jiangbinghua** [OP-TEE/optee_os#4479]
Hello!
How do I generate the secret key and ephemeral secret key needed in SM2 secret key exchange protocol? Is there a connection between secret key and ephemeral secret key?

**Comment by jforissier** [comment]
Hello @jiangbinghua,

I'm assuming you are writing a TA so you are using the GP API. If you're writing kernel mode code (pseudo TA for example) that would be different.

- The secret key can be generated with `TEE_GenerateKey()` :
```C
TEE_ObjectHandle keyh;
TEE_Result res;

res = TEE_AllocateTransientObject(TEE_TYPE_SM2_KEP_KEYPAIR, 256, &keyh);
if (res) {
        /* Error handling */
}
res = TEE_GenerateKey(keyh, 256, NULL, 0);
if (res) {
        /* Error handling*/
}
```
- The ephemeral secret key is any random number in [1, n-1] n being the order of the base point of the SM2 curve (n = FFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFF7203DF6B21C6052B53BBF40939D54123). So in a TA you may use `TEE_GenerateRandom()` with a 32-byte buffer then use the `TEE_BigInt*()` functions to make sure the value is in the expected range.
