### ISSUE TITLE
Error while building OP-TEE on QEMU

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#4480]
I'm using Ubuntu 18.04
Command used: repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml -b 3.12.0
i've installed all the required packages by following https://optee.readthedocs.io/en/latest/building/prerequisites.html#prerequisites

i could see the following error log:

> Get https://gerrit.googlesource.com/git-repo/clone.bundle
> Get https://gerrit.googlesource.com/git-repo
> remote: Counting objects: 7, done
> remote: Finding sources: 100% (123/123)
> remote: Total 123 (delta 49), reused 123 (delta 49)
> Receiving objects: 100% (123/123), 134.55 KiB | 5.38 MiB/s, done.
> Resolving deltas: 100% (49/49), completed with 12 local objects.
> From https://gerrit.googlesource.com/git-repo
>    ceba2dd..511a0e5  main       -> origin/main
>    b64bec6..511a0e5  stable     -> origin/stable
>  * [new tag]         v2.13      -> v2.13
>  * [new tag]         v2.13.1    -> v2.13.1
>  * [new tag]         v2.13.2    -> v2.13.2
>  * [new tag]         v2.13.3    -> v2.13.3
>  * [new tag]         v2.13.4    -> v2.13.4
>  * [new tag]         v2.13.5    -> v2.13.5
>  * [new tag]         v2.13.6    -> v2.13.6
>   File "/home/sadiqhm/ADIT/optee_qemu/.repo/repo/main.py", line 79
>     file=sys.stderr)
>         ^
> SyntaxError: invalid syntax

Could anyone help me solve this issue please?

**Comment by jforissier** [comment]
Hi @saddy-muchu,

What does `python --version` report ? 2.something or 3.something?

**Comment by saddy-muchu** [comment]
In older python console: 

> >>> import sys
> >>> print("we have an error {}", file=sys.stderr)
>   File "<stdin>", line 1
>     print("we have an error {}", file=sys.stderr)
>                                      ^
> SyntaxError: invalid syntax

in python3 console:

> >>> import sys
> >>> print("we have an error {}", file=sys.stderr)
> we have an error {}

So, looks like i'm ending up in the older python being used instead of python3

**Comment by saddy-muchu** [comment]
python --version reports 2.7.17

**Comment by jforissier** [comment]
That's what I thought, then try `sudo apt install python3`. This should get you further (then other Py3 packages might be needed but we'll see).

**Comment by saddy-muchu** [comment]
yes, i have python3 too "in addition" to the older python
i checked whether this repo init works on ubuntu 16.04. It indeed does work(here python --version returns 2.7.12)

but i can't use 16.04 as i'm not able to install pre-required packages (hence switched to 18.04)

**Comment by jforissier** [comment]
To make `python3` the default you can simply uninstall `python2` (assuming you don't need it for other projects).

**Comment by saddy-muchu** [comment]
But this would remove google's repo tool too.
installing it back via "sudo apt-get install repo" will additional install python 2.7 package again

**Comment by jforissier** [comment]
Don't use repo install by apt. Instead: https://source.android.com/setup/develop#installing-repo

**Comment by saddy-muchu** [comment]
i guess removing python2 isn't an option as google's repo tool doesn't completely work with python3

**Comment by saddy-muchu** [comment]
@jforissier  thanks for the pointer
Anyway, i'll close this issue as this isn't really OP-TEE specific

**Comment by jforissier** [comment]
> i guess removing python2 isn't an option as google's repo tool doesn't completely work with python3

Not true. I have only Python 3 on my laptop (Ubuntu 20.04).

> Anyway, i'll close this issue as this isn't really OP-TEE specific

True :)

**Comment by saddy-muchu** [comment]
i was able to get around with the repo tool issue.
now i face below error when "make -j2 toolchains" is executed:
make -j2 toolchains

> Downloading gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf ...
> Downloading gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu ...
> tar: /home/sadiqhm/ADIT/optee_qemu/build/../toolchains/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz: Cannot open: No such file or directory
> tar: Error is not recoverable: exiting now
> bash: line 0: cd: /home/sadiqhm/ADIT/optee_qemu/build/../toolchains/aarch32/bin: No such file or directory
> toolchain.mk:36: recipe for target 'aarch32' failed
> make: *** [aarch32] Error 1
> make: *** Waiting for unfinished jobs....
> tar: /home/sadiqhm/ADIT/optee_qemu/build/../toolchains/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz: Cannot open: No such file or directory
> tar: Error is not recoverable: exiting now
> bash: line 0: cd: /home/sadiqhm/ADIT/optee_qemu/build/../toolchains/aarch64/bin: No such file or directory
> toolchain.mk:40: recipe for target 'aarch64' failed
> make: *** [aarch64] Error 1
>

**Comment by saddy-muchu** [comment]
Basically, it isn't able to fetch and put the tarball in the required directory
