### ISSUE TITLE
Xilinx ZCU102 building issues ( cannot find libgcc.a)

### ISSUE THREAD

**Issue by AsmX0r** [OP-TEE/optee_os#4485]
Hello!

I'm currently working on a board Xilinx ZCU102 and I'm trying to compile OP-TEE for it. I have thoroughly followed [the official documentation](https://optee.readthedocs.io/en/latest/building/devices/zynqmp.html) and I'm facing a similar issue raised by [this issue](https://github.com/OP-TEE/optee_os/issues/3950), I get the error `aarch64-xilinx-linux-ld.bfd: cannot find libgcc.a` while executing the command `make -f zynqmp.mk`. I have applied the recommendation of [the linked thread](https://forums.xilinx.com/t5/Embedded-Linux/libgcc-a-not-found-when-building-OPTEE-on-ZCU102/m-p/1121532#M43341) of the previously mentioned issue referenced as the solution, but it did not work, which the original author seems to also indicates in that external thread. I have contacted the author of the issue in the related issue, but since it has been raised a couple of months ago, this person does not have any track of the resolution of the compilation error.

Here is a breakdown of my steps to bring more lights on where the issue is encountered. Based on [the official documentation](https://optee.readthedocs.io/en/latest/building/devices/zynqmp.html), I have completed all the steps successfully before `make -f zynqmp.mk`. My current setup is Ubuntu 16.04, with Petalinux 2018.2, with the latest version of OP-TEE. I execute the following commands, which are part of `make -f zynqmp.mk`:

- `make -f zynqmp.mk petalinux-create`
- Execute the recommended procedure to include gcc into Petalinux, as mentioned in [the external link](https://forums.xilinx.com/t5/Embedded-Linux/libgcc-a-not-found-when-building-OPTEE-on-ZCU102/m-p/1121532#M43341) of the previously mentioned issue. Everything behaves as mentioned.
- `make -f zynqmp.mk petalinux-config`
- `make -f zynqmp.mk petalinux-build`; this is where the error is raised. I have attached a more comprehensive log at the end of the issue to have more insights.

I know this may be hard for you to diagnosis the issue, since it seems to be bound to Petalinux. This is why it would be great if @ricardosalveti (listed as maintainer of the board) could give me some tips on that issue. :)

Many thanks for your help!

```
$ make -f zynqmp.mk petalinux-build
[INFO] building project
[INFO] sourcing bitbake
INFO: bitbake petalinux-user-image
Loading cache: 100% |##############################################################################################################################################################################| Time: 0:00:00
Loaded 3448 entries from dependency cache.
Parsing recipes: 100% |############################################################################################################################################################################| Time: 0:00:03
Parsing of 2559 .bb files complete (2512 cached, 47 parsed). 3453 targets, 138 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
Initialising tasks: 100% |#########################################################################################################################################################################| Time: 0:00:07
Checking sstate mirror object availability: 100% |#################################################################################################################################################| Time: 0:00:06
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: optee-os-latest+gitAUTOINC+e55ecd1308-r0 do_compile: oe_runmake failed
ERROR: optee-os-latest+gitAUTOINC+e55ecd1308-r0 do_compile: Function failed: do_compile (log file is located at /home/ubuntu/petalinux-optee/zcu102-2018.2/build/tmp/work/aarch64-xilinx-linux/optee-os/latest+gitAUTOINC+e55ecd1308-r0/temp/log.do_compile.20302)
ERROR: Logfile of failure stored in: /home/ubuntu/petalinux-optee/zcu102-2018.2/build/tmp/work/aarch64-xilinx-linux/optee-os/latest+gitAUTOINC+e55ecd1308-r0/temp/log.do_compile.20302
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 32 comp-cflagscore=--sysroot=/home/ubuntu/petalinux-optee/zcu102-2018.2/build/tmp/work/aarch64-xilinx-linux/optee-os/latest+gitAUTOINC+e55ecd1308-r0/recipe-sysroot CROSS_COMPILE=aarch64-xilinx-linux- CROSS_COMPILE_core=aarch64-xilinx-linux- CROSS_COMPILE_ta_arm64=aarch64-xilinx-linux- PLATFORM=zynqmp-zcu102 CFG_ARM64_core=y CFG_ARM32_core=n CFG_USER_TA_TARGETS=ta_arm64 CFG_TEE_CORE_LOG_LEVEL=2 CFG_TEE_CORE_DEBUG=n DEBUG=0
|   GEN     out/arm-plat-zynqmp/core/include/generated/arm32_sysreg.h
|   GEN     out/arm-plat-zynqmp/core/include/generated/arm32_sysreg.S
|   CHK     out/arm-plat-zynqmp/conf.mk
|   GEN     out/arm-plat-zynqmp/core/ta_pub_key.c
|   AR      out/arm-plat-zynqmp/ldelf-lib/libunw/libunw.a
|   AR      out/arm-plat-zynqmp/lib/libunw/libunw.a
|   UPD     out/arm-plat-zynqmp/conf.mk
|   INSTALL out/arm-plat-zynqmp/export-ta_arm64/mk/compile.mk

  [..a lot of INSTALL/CC cropped..]
  
|   CPP     out/arm-plat-zynqmp/ta/trusted_keys/ta.lds
|   CHK     out/arm-plat-zynqmp/core/include/generated/asm-defines.h
|   AR      out/arm-plat-zynqmp/ldelf-lib/libutee/libutee.a
|   AR      out/arm-plat-zynqmp/ldelf-lib/libutils/libutils.a
|   AR      out/arm-plat-zynqmp/ta_arm64-lib/libdl/libdl.a
|   AR      out/arm-plat-zynqmp/ta_arm64-lib/libutee/libutee.a
|   INSTALL out/arm-plat-zynqmp/export-ta_arm64/lib/libdl.a
|   UPD     out/arm-plat-zynqmp/core/include/generated/asm-defines.h
|   LD      out/arm-plat-zynqmp/ldelf/ldelf.elf
|   INSTALL out/arm-plat-zynqmp/export-ta_arm64/lib/libutee.a
|   CC      out/arm-plat-zynqmp/core/arch/arm/kernel/user_ta.o
|   CC      out/arm-plat-zynqmp/core/arch/arm/kernel/ldelf_loader.o
|   CC      out/arm-plat-zynqmp/core/arch/arm/kernel/ree_fs_ta.o
|   CC      out/arm-plat-zynqmp/core/arch/arm/kernel/secstor_ta.o
| aarch64-xilinx-linux-ld.bfd: cannot find libgcc.a: No such file or directory
|   CC      out/arm-plat-zynqmp/core/arch/arm/kernel/tee_time.o
| make: *** [ldelf/link.mk:54: out/arm-plat-zynqmp/ldelf/ldelf.elf] Error 1
| make: *** Waiting for unfinished jobs....
|   CC      out/arm-plat-zynqmp/core/arch/arm/kernel/pseudo_ta.o
|   CC      out/arm-plat-zynqmp/core/arch/arm/kernel/rpc_io_i2c.o
|   CC      out/arm-plat-zynqmp/core/arch/arm/kernel/otp_stubs.o
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/ubuntu/petalinux-optee/zcu102-2018.2/build/tmp/work/aarch64-xilinx-linux/optee-os/latest+gitAUTOINC+e55ecd1308-r0/temp/log.do_compile.20302)
ERROR: Task (/home/ubuntu/petalinux-optee/zcu102-2018.2/project-spec/meta-user/recipes-bsp/optee-os/optee-os.bb:do_compile) failed with exit code '1'
```

EDIT: the related log file (/home/ubuntu/petalinux-optee/zcu102-2018.2/build/tmp/work/aarch64-xilinx-linux/optee-os/latest+gitAUTOINC+e55ecd1308-r0/temp/log.do_compile.20302) can be found [here](https://pastebin.com/CpaxU4ng).

**Comment by ricardosalveti** [comment]
This might be related to the OE environment. Do you have https://git.yoctoproject.org/cgit/cgit.cgi/meta-arm/tree/meta-arm/recipes-security/optee/optee-os/0006-allow-setting-sysroot-for-libgcc-lookup.patch applied on your optee-os recipe?

You would need that patch + build flags as set at https://git.yoctoproject.org/cgit/cgit.cgi/meta-arm/tree/meta-arm/recipes-security/optee/optee.inc#n22.

**Comment by ricardosalveti** [comment]
Also see issue #4188.

**Comment by AsmX0r** [comment]
Dear @ricardosalveti,

Many thanks for your fast reply and your great advices! I have not realized that Xilinx OS was based on Yocto/OE and did not apply that patch. Once applied and the related build flag set, I could complete the compilation phase! Awesome!

To summarize the compilation phase, here are the step to do:

1. Edit the files `~/petalinux-optee/build/zynqmp/optee-os/optee-os.bb` and `~/petalinux-optee/build/zynqmp/optee-os/optee-os.bb` to add the line `EXTRA_OEMAKE_append = " LIBGCC_LOCATE_CFLAGS=--sysroot=${STAGING_DIR_HOST}"` after the other `EXTRA_OEMAKE_append` assignments.
2. `make -f zynqmp.mk`; this will fail because of the libgcc.a file missing
3. Apply the following patch to two building files with the commands below.
```
diff --git a/mk/gcc.mk b/mk/gcc.mk
index adc77a24..81bfa78a 100644
--- a/mk/gcc.mk
+++ b/mk/gcc.mk
@@ -13,11 +13,11 @@ nostdinc$(sm)   := -nostdinc -isystem $(shell $(CC$(sm)) \
            -print-file-name=include 2> /dev/null)
 
 # Get location of libgcc from gcc
-libgcc$(sm)    := $(shell $(CC$(sm)) $(CFLAGS$(arch-bits-$(sm))) \
+libgcc$(sm)    := $(shell $(CC$(sm)) $(LIBGCC_LOCATE_CFLAGS) $(CFLAGS$(arch-bits-$(sm))) \
            -print-libgcc-file-name 2> /dev/null)
-libstdc++$(sm) := $(shell $(CXX$(sm)) $(CXXFLAGS$(arch-bits-$(sm))) $(comp-cxxflags$(sm)) \
+libstdc++$(sm) := $(shell $(CXX$(sm)) $(LIBGCC_LOCATE_CFLAGS) $(CXXFLAGS$(arch-bits-$(sm))) $(comp-cxxflags$(sm)) \
            -print-file-name=libstdc++.a 2> /dev/null)
-libgcc_eh$(sm) := $(shell $(CXX$(sm)) $(CXXFLAGS$(arch-bits-$(sm))) $(comp-cxxflags$(sm)) \
+libgcc_eh$(sm) := $(shell $(CXX$(sm)) $(LIBGCC_LOCATE_CFLAGS) $(CXXFLAGS$(arch-bits-$(sm))) $(comp-cxxflags$(sm)) \
            -print-file-name=libgcc_eh.a 2> /dev/null)
 
 # Define these to something to discover accidental use
```

```sh
$ patch -d /path/to/zcu102-2018.2/build/tmp/work/aarch64-xilinx-linux/optee-os/latest+gitAUTOINC+e55ecd1308-r0/git/mk/ < [patch-file]
$ patch -d  /path/to/zcu102-2018.2/build/tmp/work/aarch64-xilinx-linux/optee-os/latest+gitAUTOINC+e55ecd1308-r0/git/out/arm-plat-zynqmp/export-ta_arm64/mk/ < [patch-file]
```
4. Finally, execute `make -f zynqmp.mk petalinux-build petalinux-package`.

Alternatively, one can edit the files in step (1) to change the OP-TEE build git repo with the patch to the files in (3) already applied.

@ricardosalveti Did you manage to use an up-to-date version of Petalinux (assuming you use it) and a more recent version of Ubuntu to build it? It seems the `zyncmp.mk` is written in a way that is locked for Petalinux 2018.2.

Many thanks again for your help!
Cheers

**Comment by ricardosalveti** [comment]
> @ricardosalveti Did you manage to use an up-to-date version of Petalinux (assuming you use it) and a more recent version of Ubuntu to build it? It seems the `zyncmp.mk` is written in a way that is locked for Petalinux 2018.2.

Not a petalinux user, so probably best to report to Xilinx.

We do use optee-os with OE (gatesgarth and master), so might be a matter of just updating petalinux.

Should we close the issue?

**Comment by AsmX0r** [comment]
> We do use optee-os with OE (gatesgarth and master), so might be a matter of just updating petalinux.

Out of curiosity, does Petalinux provide any benefits compared to using Yocto? I'm not linked to Petalinux, I'm using it because it is the one recommended by Xilinx, but in the case Yocto provides the same (or better) features/support, I would be interested to switch to it, since Petalinux 2018.2 is pretty old. Do you know if there is a guide to compile OP-TEE with Yocto and run it on the Xilinx ZCU102?

> Should we close the issue?

Sure! I'm closing the issue. Thanks again for your help!

**Comment by ricardosalveti** [comment]
> > We do use optee-os with OE (gatesgarth and master), so might be a matter of just updating petalinux.
> 
> Out of curiosity, does Petalinux provide any benefits compared to directly using Yocto? I'm not linked to Petalinux, I'm using it because it is the one recommended by Xilinx, but in the case Yocto provides the same (or better) features/support, I would be interested to switch to it, since Petalinux 2018.2 is pretty old. Do you know if there is a guide to compile OP-TEE with Yocto and run it on the Xilinx ZCU102?

Have a look at https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18841883/Yocto, meta-petalinux is just a distro layer, you can define your own and have a similar build and flashing mechanism as used by petalinux.

**Comment by yamak** [comment]
Hi @AsmX0r 
I have applied your step but I get the same error.I am using op-tee 3.11.0 and Petalinux 2018.2
Here are my steps:

1. Run `make -f zynqmp.mk petalinux-create`  command.
2. Append  the line `IMAGE_INSTALL_append = " gcc"` to end of /home/yusuf/petalinux-optee/zcu102-2018.2/project-spec/meta-user/recipes-core/images/petalinux-image.bbappend file.
3. Add the line` @petalinux-config -p $(PRJ_PATH) -c rootfs` to recipe in zynqmp.mk file and enable gcc in menuconfig screen.
4. Add the line EXTRA_OEMAKE_append = " LIBGCC_LOCATE_CFLAGS=--sysroot=${STAGING_DIR_HOST}" after the other EXTRA_OEMAKE_append assignments
5. Run the `make -f zynqmp.mk petalinux-build` command and get `libgcc.a` error.
6. Apply your patch to gcc.mk files.
7. Run again the `make -f zynqmp.mk petalinux-build` command.

But I get same error. Where am I doing wrong?
