### ISSUE TITLE
Compiling OP-TEE 3.12 with Clang 10.0.0

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#4486]
Clang 9.0.1 (the current one being used for OP-TEE compilation) doesn't use the ubuntu 18.04 tarball.
But, Clang 10.0.0 indeed has the ubuntu 18.04 x86_64 

So, can i use 10.0.0 for the compilation as i am using Ubuntu 18.04 host?

The reason for this question is, when i do a "make -j2 clang-toolchains" with the default 9.0.1 being used in "../build/get_clang.sh", my ubuntu 18.04 crashes!!

**Comment by Hussain1811** [comment]
Btw, in ../build/toolchain.mk, how is the target "clang-toolchains" being built?
we just issue "make -j2 toolchains" right?

or "clang-toolchains" isn't built by default at all?

**Comment by jforissier** [comment]
Hi @Hussain1811,

> So, can i use 10.0.0 for the compilation as i am using Ubuntu 18.04 host?

Yes

> The reason for this question is, when i do a "make -j2 clang-toolchains" with the default 9.0.1 being used in "../build/get_clang.sh", my ubuntu 18.04 crashes!!

Really? What kind of crash?

> Btw, in ../build/toolchain.mk, how is the target "clang-toolchains" being built?
> we just issue "make -j2 toolchains" right?
>
> or "clang-toolchains" isn't built by default at all?

`clang-toolchains` is not built by default.

**Comment by Hussain1811** [comment]
My Ubuntu is just stuck.
So, we use GCC for compilation and CLANG is just an option given to the users?

**Comment by jforissier** [comment]
> So, we use GCC for compilation and CLANG is just an option given to the users?

Correct.

**Comment by Hussain1811** [comment]
Thank you @jforissier
