### ISSUE TITLE
Xtest "Failed to open TEE context:" Error (Qemu)

### ISSUE THREAD

**Issue by yamak** [OP-TEE/optee_os#4488]
Hello Everyone,
I am working on ZCU102 board and trying to build OP-TEE for it.
I applied steps in issue #4485  but it didn't work.

Here are my steps:

1. Run make -f zynqmp.mk petalinux-create command.
2. Add the line EXTRA_OEMAKE_append = " LIBGCC_LOCATE_CFLAGS=--sysroot=${STAGING_DIR_HOST}" after the other EXTRA_OEMAKE_append assignments
3. Run the 'make -f zynqmp.mk petalinux-config' command
4. Run the make -f zynqmp.mk petalinux-build command and get libgcc.a error.
5. Apply following patch  
```
diff --git a/mk/gcc.mk b/mk/gcc.mk
index adc77a24..81bfa78a 100644
--- a/mk/gcc.mk
+++ b/mk/gcc.mk
@@ -13,11 +13,11 @@ nostdinc$(sm)   := -nostdinc -isystem $(shell $(CC$(sm)) \
            -print-file-name=include 2> /dev/null)
 
 # Get location of libgcc from gcc
-libgcc$(sm)    := $(shell $(CC$(sm)) $(CFLAGS$(arch-bits-$(sm))) \
+libgcc$(sm)    := $(shell $(CC$(sm)) $(LIBGCC_LOCATE_CFLAGS) $(CFLAGS$(arch-bits-$(sm))) \
            -print-libgcc-file-name 2> /dev/null)
-libstdc++$(sm) := $(shell $(CXX$(sm)) $(CXXFLAGS$(arch-bits-$(sm))) $(comp-cxxflags$(sm)) \
+libstdc++$(sm) := $(shell $(CXX$(sm)) $(LIBGCC_LOCATE_CFLAGS) $(CXXFLAGS$(arch-bits-$(sm))) $(comp-cxxflags$(sm)) \
            -print-file-name=libstdc++.a 2> /dev/null)
-libgcc_eh$(sm) := $(shell $(CXX$(sm)) $(CXXFLAGS$(arch-bits-$(sm))) $(comp-cxxflags$(sm)) \
+libgcc_eh$(sm) := $(shell $(CXX$(sm)) $(LIBGCC_LOCATE_CFLAGS) $(CXXFLAGS$(arch-bits-$(sm))) $(comp-cxxflags$(sm)) \
            -print-file-name=libgcc_eh.a 2> /dev/null)
 
 # Define these to something to discover accidental use
```
to 
```
~/petalinux-optee/zcu102-2018.2/build/tmp/work/aarch64-xilinx-linux/optee-os/latest+gitAUTOINC+4451b84e50-r0/git/out/arm-plat-zynqmp/export-ta_arm64/mk/gcc.mk 
~/petalinux-optee/zcu102-2018.2/build/tmp/work/aarch64-xilinx-linux/optee-os/latest+gitAUTOINC+4451b84e50-r0/git/mk/gcc.mk
```
files.

6. Run again the `make -f zynqmp.mk petalinux-build` command.

But I get 

> aarch64-xilinx-linux-ld.bfd: cannot find libgcc.a: No such file or directory

error same as in issue  #4485 .
Where am I doing wrong?
Thanks for your help.

**Comment by yamak** [comment]
Hi,
It didn't work because I didn't add the line LIBGCC_LOCATE_CFLAGS=--sysroot=${STAGING_DIR_HOST} to optee-client.bb and optee-test.bb.When I added that line to these file, It worked. 
But When I run xtest on Qemu, I am getting following error:

> Run test suite with level=0
> 
> TEE test application started over default TEE instance
> Failed to open TEE context: 0xffff0008
> 
Why am I getting such an error. Is this error about QEMU?
How can I solve this problem?

Many thanks for your helps.

PS: Because Issue is change, I changed the title.

**Comment by jforissier** [comment]
`0xffff0008` is `TEE_ERROR_ITEM_NOT_FOUND`. Is `tee-supplicant` running? If not, start it with `/usr/sbin/tee-supplicant -d` (root user or some more appropriate user depending on your environment).

**Comment by yamak** [comment]
Yes, tee-supplicant is running. I run xtest after the 'tee-supplicant -d'. Could this error caused by the QEMU platform?

**Comment by yamak** [comment]
> `0xffff0008` is `TEE_ERROR_ITEM_NOT_FOUND`. Is `tee-supplicant` running? If not, start it with `/usr/sbin/tee-supplicant -d` (root user or some more appropriate user depending on your environment).

Yes, tee-supplicant is running. I run xtest after the 'tee-supplicant -d'. Could this error caused by the QEMU platform?

**Comment by jforissier** [comment]
Sorry, I don't understand what you are trying to do. First you mention building for ZCU102 and now you're talking about QEMU.
The official QEMU development environment for OP-TEE is described at https://optee.readthedocs.io/en/latest/building/devices/qemu.html.

**Comment by yamak** [comment]
> Sorry, I don't understand what you are trying to do. First you mention building for ZCU102 and now you're talking about QEMU.
> The official QEMU development environment for OP-TEE is described at https://optee.readthedocs.io/en/latest/building/devices/qemu.html.

I don't have a zcu102 yet. However, I will run my development on physical zcu102 a few weeks later. So I am trying to boot optee on QEMU now.
I applied build steps mentioned following link:

https://optee.readthedocs.io/en/latest/building/devices/zynqmp.html

In the last step, system is booted on QEMU.
But when I run xtest, I am getting error mentioned earlier

**Comment by jforissier** [comment]
So you are using QEMU to emulate a zcu102 board? I've never done that so I'm afraid I can't help.

**Comment by vesajaaskelainen** [comment]
I have been running both QEMU with ZCU102 board and also got it running on real hardware. But not using petalinux just our own variant of Yocto. I needed to patch there and there to get things working also with real hardware -- qemu has been working for me for couple of years now (my main op-tee development tooling). For OP-TEE I am following the master.

I needed to update Xilinx release level to 2020.2 in the process to get all bits and pieces to some better level -- unfortunately meta-xilinx is a bit mess. And with Vitis 2020.2 ... well it needs a bit more work.

Basically I am using MACHINE="zcu102-zynqmp" and then runqemu. -- thou needed to update the machine.

Observe to kernel messages to see that you have optee driver enabled and configured it in device tree.
```
[    5.189252] optee: probing for conduit method.
[    5.190154] optee: revision 3.12 (5c428147)
[    5.207868] optee: initialized driver
```

Make sure you set ATF_MEM_SIZE, BL32_MEM_BASE, BL32_MEM_SIZE in machine. and then in qemu config make sure you load tee.elf. Then you need to modify also ATF building to have those defined and also specify SPD=opteed.

I am not able to assist much for next week or so (away) -- but after that I need to get start integrating things in our end too so can see if there are other tips that can be given. Please note that I target newer yocto releases and not petalinux.
