### ISSUE TITLE
For storage strategies of system calls

### ISSUE THREAD

**Issue by dengpeiyao0515** [OP-TEE/optee_os#4489]
Hi,

I have already collected system calls' argument, which are all represented by hex formats. Do you have any suggestions to convert those hex numbers to human-readable formats? For example, in the attached figure, it shows those hex numbers can be converted to several lines of C code. 
![0 (1)](https://user-images.githubusercontent.com/74812838/111968681-642a8300-8b34-11eb-8e52-2a00b463cbc3.png)

Thank you very much for your time and help!

Many thanks,

**Comment by etienne-lms** [comment]
There is a `DHEXDUMP()` macro that dumps a buffer in byte. If you need some equivalent with an char representation, maybe you can implement another macro for that. Contributions are welcome, feel free to create a P-R.
