### ISSUE TITLE
How to write our own TA and run it on QEMU?

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#4490]
Wanted to know the steps that could be used to compile a TA and copy the .ta file to /lib/optee_artmz/ in the QEMU.
Later, i would like to execute it and see what's going on in the OP-TEE console.

i am aware that optee_examples could be directly run via "optee_example_*"

**Comment by jenswi-linaro** [comment]
This is one of the purposes of optee_optexample, to serve as an example of an end to end solution with a TA.

**Comment by Hussain1811** [comment]
So, basically i should write a TA under optee_examples directory and later issue "make run" from build directory?

**Comment by jenswi-linaro** [comment]
That's one way of doing it. I should help if you go through those make files and try to figure out what's going on. If there's step which are hard to figure out perhaps a few comments could be added to make the examples more helpful.

Ideally you should in the end be able to make a new setup independent of the optee_examples git, but until then just building on that git might be an option.

**Comment by sunnybird** [comment]
i have some ideas about this issue 
1. add "QEMU_VIRTFS_ENABLE := y" to qemu_v8.mk
2. make -f qemu_v8.mk qemu-clean
3. make -f qemu_v8.mk qemu
4. make -f qemu_v8.mk run-only
then , you will login in qume as root
run " df " at terminal of qume , you will find /mnt/host
this folder links to optee dir .
so , you can put your own ta bin into optee dir , then copy it to /lib/optee_artmz/ from /mnt/host

**Comment by Hussain1811** [comment]
Hello @sunnybird,

Thank you for your suggestion.
i tried your steps - it works.

But i don't see the /mnt/host mount point
