### ISSUE TITLE
aslr, canot booting with CFG_CORE_ASLR

### ISSUE THREAD

**Issue by lxxstone** [OP-TEE/optee_os#4496]
Hi all,
I encountered some problems when opening CFG_CORE_ASLR on my board with 3.12，

The seed value I set is 0，and then modified this judgment
core/arch/arm/mm/core_mmu.c
```
-       if (IS_ENABLED(CFG_CORE_ASLR) && seed) {
+       if (IS_ENABLED(CFG_CORE_ASLR)) {
```

The code enters reset_primary, and then jumps to relocate addr after calling enale_mmu. It all looks normal
```
        ...
#ifdef CFG_CORE_ASLR
	bl	relocate
#endif

	bl	__get_core_pos
	bl	enable_mmu
        ...
```

Then something strange happened, the runtime .text segment was at 0x96xxxxxx, but the other segments such as .bss and .data were still at 0x16xxxxxx，so I could not access any variables.
![image](https://user-images.githubusercontent.com/3895109/112130774-c9997500-8c03-11eb-9531-547bd80afc2b.png)
![image](https://user-images.githubusercontent.com/3895109/112130821-d6b66400-8c03-11eb-8405-1ed3e571026e.png)
![image](https://user-images.githubusercontent.com/3895109/112130891-e635ad00-8c03-11eb-88b2-56e164a43e12.png)
Any suggestions?

Thanks

**Comment by jenswi-linaro** [comment]
Is this a problem with your debugger or a crash?

**Comment by lxxstone** [comment]
Hi @jenswi-linaro ,
My debugger is trace32, it has been working normally. 
I use it to single-step debug until enable_mmu is normal.

After completing the remap, if optee access the data in the .bss or .data section, data abort will be triggered.

**Comment by jenswi-linaro** [comment]
.bss and .data are supposed to be moved together with .text. If that doesn't happen something is very wrong.
Some debuggers (notably gdb) doesn't understand that it's more than just the .text segment that has been moved.

**Comment by lxxstone** [comment]
The problem has been found,
On our platform, TEE_RAM_START and __text_start are not pointing to the same address, so embdata is not placed in the correct position during relocation.
Would it be better to replace TEE_RAM_START with __text_start in entry.S?

There are also two doubts,
 Why embdata is introduced?
 and why gen_tee_bin.py does not directly put embdata after _end, but between .text and .bss ?

**Comment by jenswi-linaro** [comment]
> The problem has been found,
> On our platform, TEE_RAM_START and __text_start are not pointing to the same address, so embdata is not placed in the correct position during relocation.
> Would it be better to replace TEE_RAM_START with __text_start in entry.S?

It might be possible, or if you could add the needed offset to `TEE_RAM_START`

> 
> There are also two doubts,
> Why embdata is introduced?

As a somewhat generic container for both hashes for paging and relocation information. This is supposed to be consumed during the boot.

> and why gen_tee_bin.py does not directly put embdata after _end, but between .text and .bss ?

Because we don't want to pad the binary with zeroes.

**Comment by lxxstone** [comment]
Got it, thanks very much for your reply.
