### ISSUE TITLE
setup_fvp_optee.sh have erroneous description

### ISSUE THREAD

**Issue by curtyang** [OP-TEE/optee_os#450]
"SRC_GEN_ROOTFS=https://github.com/jbech-linaro/gen_rootfs.git" is erroneous description,Click on this link,Page Display"this is not web page you are looking for".Trouble experts to solve this problem,thanks a lot.

**Comment by vchong** [comment]
You can replace it with https://github.com/linaro-swg/gen_rootfs.git, but please note that we are currently changing the way environments are imported. We are now using android-like manifest and build. Please have a look at https://github.com/OP-TEE/manifest/blob/master/README.md. It will guide you to retrieve fvp environment using this new way. Please let us know if you still face issues with this new way of proceeding.

Note that setup scripts are obsolete, and will be removed soon.

**Comment by curtyang** [comment]
@vchong ,thanks a lot, I will try~

**Comment by jbech-linaro** [comment]
@curtyang @pascal-brand-st-dev it seems like we have answered this, so can we close this issue?

**Comment by pascal-brand-st** [comment]
Closing as obsolete script `setup_fvp_optee.sh` has been removed.

**Comment by curtyang** [comment]
@jbech-linaro ok
