### ISSUE TITLE
OP-TEE OS 3.11.0 Hangs at opteed_enter_sp on Cold Boot

### ISSUE THREAD

**Issue by nathan-menhorn** [OP-TEE/optee_os#4501]
When building OP-TEE 3.11.0 for the xilinx zynqmp device (ZCU111) in conjunction with PetaLinux 2019.2, the board successfully boots for a cold boot. However, when performing a warm-reset from Linux, the boot hangs in the function **opteed_enter_sp** after https://github.com/ARM-software/arm-trusted-firmware/blob/eeb77da64684424ef275330e3e15d8350ecc1b07/services/spd/opteed/opteed_helpers.S#L42 which should return from EL3 into SEL1 (OP-TEE OS). OP-TEE OS is hung up and never returns so that the boot never finishes.

**Comment by billyburly** [comment]
I additionally see this hang consistently on some ZCU111 boards on cold boot. On others I am able to work around this by powering off the device for 5 seconds.
