### ISSUE TITLE
hanging in init_primary_helper:928 Primary CPU switching to normal world boot

### ISSUE THREAD

**Issue by LIKEJMJJ** [OP-TEE/optee_os#4502]
![T}J ICSTJ~J$DP`EEJNM7H1](https://user-images.githubusercontent.com/37587541/112434265-55371100-8d7e-11eb-9689-4457081744e7.png)
I use a Zynq 7000 series board, which is ZC706.Use it to port the optee.The process is as follows: u-boot starts optee, and then optee starts Linux.Now my problem is that the optee has started successfully and started returning to the normal world, but it seems to be stuck on returning.By adding debug code, I get the process finally stuck here in SMC #0.I have tried many ways but could not solve it. I am very confused. I hope you can help me.Both U-Boot and Linux are downloaded from Xilinx's GitHub and are the latest versions. Optee OS uses version 3.3.0.

**Comment by jenswi-linaro** [comment]
With the `SMC #0` OP-TEE exits and bl32 at EL3 is entered via the exception vector.

**Comment by LIKEJMJJ** [comment]
Sorry, the development board I'm using is an ARMv7 architecture.'ve looked at many of the same problems, but none of them solved my problem.

I want to know whether this flow(u-boot->optee->Linux)is correct and feasible?

Is there any special requirement for the optee to return the normal world address?The address I currently give is the load address of the Linux image

**Comment by jenswi-linaro** [comment]
Linux is a bit picky about what's passed in r0-r3 if I remember correctly. So my guess is that you're crashing really early during Linux initialization. You can override the `init_sec_mon()` function to set assign the needed values in r0-r3 in nsec_ctx.

**Comment by LIKEJMJJ** [comment]
You mean that the optee has switched to the normal world and has passed the value to Linux.But Linux crashes on startup, so it stays stuck?

**Comment by LIKEJMJJ** [comment]
I'm sorry, I'm a beginner, so I don't know enough about this. so I'm looking forward to your guidance. Thank you very much

**Comment by jenswi-linaro** [comment]
> You mean that the optee has switched to the normal world and has passed the value to Linux.But Linux crashes on startup, so it stays stuck?

Yes, that's likely. Especially if you haven't put anything useful in r0-r3.

**Comment by etienne-lms** [comment]
Assuming you know where U-Boot loads Linux kernel image and its DTB, you can statically define these addresses in OP-TEE at build time so that OP-TEE provides them to Linux at boot time. Build optee_os with:
`CFG_NS_ENTRY_ADDR=<your-kernel-entry-address>`
`CFG_DT_ADDR=<your-kernel-DTB-load-address>`
I hope it helps.

**Comment by LIKEJMJJ** [comment]
![image](https://user-images.githubusercontent.com/37587541/112958804-65cbfa80-9175-11eb-8a71-7545accc24bd.png)

I have tried the above two addresses, but still stuck in the same location.I have now added more debug code and finally found that the process is stuck in the same position as the above image.

Sm_a32. S  write_scr r0

**Comment by LIKEJMJJ** [comment]
Does this have anything to do with the optee version?I tried to load the device tree before Optee3.5, but failed to load the device with Optee3.5 and later versions.
E/TC:0 0 init_external_dt:930 Invalid Device Tree at 0x2fff9000: error -9
E/TC:0 0 Panic at core/arch/arm/kernel/generic_boot.c:931 <init_external_dt>
E/TC:0 0 Call stack:
E/TC:0 0  0x3e005ba5

**Comment by LIKEJMJJ** [comment]
the command I used to compile Optee3.5.0:
make PLATFORM=zynq7k CROSS_COMPILE="ccache arm-linux-gnueabihf-" ARCH=arm CFG_TEE_CORE_LOG_LEVEL=4 CFG_DT=y CFG_NS_ENTRY_ADDR=0x03000000 CFG_DDR_SIZE=0x40000000 CFG_DT_ADDR=0x2fff9000 CFG_TZDRAM_START=0x3E000000 CFG_TZDRAM_SIZE=0x01F00000
This is the command I used to compile Optee3.3.0:
make PLATFORM=zynq7k CROSS_COMPILE="ccache arm-linux-gnueabihf-" ARCH=arm CFG_TEE_CORE_LOG_LEVEL=4 CFG_DT=y CFG_NS_ENTRY_ADDR=0x03000000 CFG_DDR_SIZE=0x40000000 CFG_DT_ADDR=0x2fff9000

**Comment by LIKEJMJJ** [comment]
Load DTB, zImage, uTee and start tee on u-boot:
mmcinfo; fatload mmc 0 0x3000000 zImage ; fatload mmc 0 0x2fff9000 zynq-zc706.dtb ; setenv bootargs earlyprintk console=ttyPS0,115200 root=/dev/mmcblk0p2 rw rootwait ; fatload mmc 0 0x3E000000 uTee ; bootm 0x3E000000 - 0x2fff9000

**Comment by jenswi-linaro** [comment]
In the picture above, does `db_test()` change `r0`?

**Comment by LIKEJMJJ** [comment]
I don't think so. It simply prints a string

**Comment by LIKEJMJJ** [comment]
And I tried version 3.4.0 of Optee and it was stuck in the same place.I didn't add db_test() in optee3.4.0

**Comment by jenswi-linaro** [comment]
I'm sorry, I can't help you any further.

**Comment by LIKEJMJJ** [comment]
I'm still very grateful to you

**Comment by LIKEJMJJ** [comment]
> I'm sorry, I can't help you any further.
Now it's pretty clear that write_scr r0 is a problem. After a series of debugging, I found that write_scr could not write scr.ns =1 to the SCR register.It feels like you don't have write permission

**Comment by LIKEJMJJ** [comment]
> Assuming you know where U-Boot loads Linux kernel image and its DTB, you can statically define these addresses in OP-TEE at build time so that OP-TEE provides them to Linux at boot time. Build optee_os with:
> `CFG_NS_ENTRY_ADDR=<your-kernel-entry-address>`
> `CFG_DT_ADDR=<your-kernel-DTB-load-address>`
> I hope it helps.

Now it's pretty clear that write_scr r0 is a problem. After a series of debugging, I found that write_scr could not write scr.ns =1 to the SCR register.It feels like you don't have write permission

**Comment by jenswi-linaro** [comment]
Sounds like you not in `hyp` mode any longer. Only `hyp` mode can set an previously cleared scr.ns bit.

**Comment by LIKEJMJJ** [comment]
> Sounds like you not in `hyp` mode any longer. Only `hyp` mode can set an previously cleared scr.ns bit.

![image](https://user-images.githubusercontent.com/37587541/114141601-679b7800-9944-11eb-9a68-50a5bb88a3ef.png)
I am in Monitor Mode now. Can't I reset scr.ns in this Mode?

**Comment by LIKEJMJJ** [comment]
Are there any special considerations when compiling optee?

**Comment by jenswi-linaro** [comment]
Sorry, I meant `mon` mode instead of `hyp` mode.
