### ISSUE TITLE
What is CFG_SECSTOR_TA compile option?

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#4503]
May i know what is the need for this compile option?
i understand that the persistent objects are stored encrypted in the linux file system. 
Is it solely due to this option? or does this option have some other meaning?

Reason for asking: i would like to reduce the size of the OP-TEE i'm using by disabling this compile option.

**Comment by jforissier** [comment]
Hi @Hussain1811 ,

`CFG_SECSTOR_TA` enables the installation of Trusted Apps in an encrypted form in the Linux FS and with some kind of anti-rollback protection. This feature uses persistent objects (= TEE secure storage), not the opposite. In other words you can safely disable `CFG_SECSTOR_TA` and still use persistent objects as defined by the GP API in your TAs.

**Comment by Hussain1811** [comment]
Hi @jforissier,

So, TA.DB and dirf.db are the same?
if not, how are they different?

**Comment by jforissier** [comment]
No, they serve totally different purposes. `ta.db` contains metadata related to the TAs installed with the `CFG_SECSTOR_TA` feature, while `dirf.db` contains metadata related to the persistent objects.

**Comment by Hussain1811** [comment]
Ah! OK
So, if I don't use CFG_SECSTOR_TA for the OP-TEE, then my TA running in this OP-TEE wont be a part of TA.DB right?

**Comment by jforissier** [comment]
Correct. There won't even be a `ta.db` to begin with.

**Comment by Hussain1811** [comment]
Ok
Thanks for clarifying my doubts.
