### ISSUE TITLE
RSA Public Exponent check

### ISSUE THREAD

**Issue by cneveux** [OP-TEE/optee_os#4506]
Hello @jenswi-linaro,

The function `check_pub_rsa_key()` in the `core/tee/tee_svc_cryp.c` is used to check that RSA public exponent is an odd bignumber.
There is a bug in this function when checking that bignumber is odd.
According to the bignumber definition, the MSB is the byte 0 of the buffer and LSB the latest byte in the buffer.

This part of code is checking the MSB and not the LSB
```c
	if (!(bin_key[0] & 1)) /* key must be odd */
		return TEE_ERROR_BAD_PARAMETERS;
```
It should be
```c
	if (!(bin_key[n-1] & 1)) /* key must be odd */
		return TEE_ERROR_BAD_PARAMETERS;
```
Unfortunately (or not), all xtest are using the 65537 public exponent where in fact MSB=LSB=0x01.
If you check the public exponent 65538, the function doesn't return an error whereas LSB=0x02 is even.

Could you confirm this is a bug or I misinterpret the bignumber?

**Comment by jenswi-linaro** [comment]
@cneveux I believe you're right. Well spotted. Do you want to make a pull request to fix this or should I?

**Comment by cneveux** [comment]
@jenswi-linaro You can do if you have time. If not let me know I'll do it.

**Comment by jenswi-linaro** [comment]
No problem. Thanks for reporting.
https://github.com/OP-TEE/optee_os/pull/4507
