### ISSUE TITLE
two CA concurrently InvokeCommand cause one CA to hang

### ISSUE THREAD

**Issue by zhaoxuyang13** [OP-TEE/optee_os#4521]
I write a demo TA, and CA.
TA: hello-world program, just increment input parameter .  with TA_FLAG: `TA_FLAG_MULTI_SESSION` , `TA_FLAG_SINGLE_INSTANCE`.
CA: call INVOKE_COMMAND in a infinite while loop.

1. when I run one CA(call it C1), it invoke the increment command perfectly.

2. then I run another CA(call it C2),which is the same as the first, calling INVOKE_COMMAND in a infinite while loop.
    C2 hang, even after I stop C1.

I wonder whether I set the TA flag wrong, or it is a bug ? 

I post some of my code below.  Thanks.
**TA**
```
static TEE_Result inc_value(uint32_t param_types,
	TEE_Param params[4])
{
	uint32_t exp_param_types = TEE_PARAM_TYPES(TEE_PARAM_TYPE_VALUE_INOUT,
						//    TEE_PARAM_TYPE_MEMREF_INOUT,
						   TEE_PARAM_TYPE_NONE,
						   TEE_PARAM_TYPE_NONE,
						   TEE_PARAM_TYPE_NONE);
	static int call_count = 0;
	if (param_types != exp_param_types)
		return TEE_ERROR_BAD_PARAMETERS;
	call_count ++ ;
	if(call_count % 500 == 0)
		IMSG("calling count: %d\n", call_count);
	params[0].value.a++;
	return TEE_SUCCESS;
}
```
**CA**
```
int main(void)
{
	TEEC_Result res;
	TEEC_Context ctx;
	TEEC_Session sess;
	TEEC_Operation op;
	TEEC_UUID uuid = TA_OPS_UUID;
	uint32_t err_origin;

	/* Initialize a context connecting us to the TEE */
	res = TEEC_InitializeContext(NULL, &ctx);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_InitializeContext failed with code 0x%x", res);

	/*
	 * Open a session to the "hello world" TA, the TA will print "hello
	 * world!" in the log when the session is created.
	 */
	res = TEEC_OpenSession(&ctx, &sess, &uuid,
			       TEEC_LOGIN_PUBLIC, NULL, NULL, &err_origin);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_Opensession failed with code 0x%x origin 0x%x",
			res, err_origin);

	/*
	 * Execute a function in the TA by invoking it, in this case
	 * we're incrementing a number.
	 *
	 * The value of command ID part and how the parameters are
	 * interpreted is part of the interface provided by the TA.
	 */

	/* Clear the TEEC_Operation struct */
	memset(&op, 0, sizeof(op));
	printf("session opened\n");
	/*
	 * Prepare the argument. Pass a value in the first parameter,
	 * the remaining three parameters are unused.
	 */
	op.paramTypes = TEEC_PARAM_TYPES(TEEC_VALUE_INOUT, TEEC_NONE,// TEE_PARAM_TYPE_MEMREF_INOUT,
					 TEEC_NONE, TEEC_NONE);
	op.params[0].value.a = 42;
	char ch[100];
	scanf("%s",ch); // wait for two CA's openSession is done. then start invoking command

	for(int i = 0;i  <= 1000000; i ++ ){
	        if(i % 100 == 0) {
		        printf("i: %d, value of a: %d\n", i, op.params[0].value.a);
	        }
	        res = TEEC_InvokeCommand(&sess, TA_OPS_CMD_INC_VALUE, &op,
				         &err_origin);
	        if (res != TEEC_SUCCESS)
		        errx(1, "TEEC_InvokeCommand failed with code 0x%x origin 0x%x",
			        res, err_origin);
	}
	TEEC_CloseSession(&sess);
	TEEC_FinalizeContext(&ctx);
	return 0;
}
```

**Comment by jforissier** [comment]
Hi @zhaoxuyang13,

This sounds very much like https://github.com/OP-TEE/optee_os/issues/4471 which was just fixed in https://github.com/OP-TEE/optee_os/pull/4514 (commit https://github.com/OP-TEE/optee_os/commit/c571b3fd4956d70c8f4435f94d64c7e36c25885d).

**Comment by zhaoxuyang13** [comment]
After updating to the newer commit, the problem is solved. Thanks!
I still have some question though. 
when I have 2 CAs concurrently invoking command to one single TA (or invoking command to two TAs when i remove TA_FLAG SINGLE_INSTANCE flag). 
a lot of 
```
D/TC:? 1 __wq_rpc:38 wake  thread 0 0x1015ff38
D/TC:? 1 __wq_rpc:38 sleep thread 1 0x1015ff38
```
appear in my uart port. and the performance of InvokingCommnad drop drastically. (over 10x) (compared with one CA calling one TA)
May I ask, is this an expected behaviour?  and how can I improve the performance?

**Comment by jenswi-linaro** [comment]
The with a single instance TA all the requests are serialized resulting in these debug prints which probably makes up the lion part of the lost time. If you turn off debug prints there should be a big increase in performance.

**Comment by zhaoxuyang13** [comment]
thanks, I will try.
