### ISSUE TITLE
Does TA get MMU support?

### ISSUE THREAD

**Issue by janoslim** [OP-TEE/optee_os#4522]
Hello,

I just found that the same operation in NA and TA have different execution time,
I just tried matrix muliplication and found that matmul in TA just slower than NA about 10 times.

I am guessing that  the reason for slowing down is virtual address access time slow down,
Thus, i wonder that TA get MMU support, or can i get a tip for investigate the reason of this issue?
+ I am using stm32mp157-dk2 board.
Thank you.

**Comment by jenswi-linaro** [comment]
Interesting observation. What is "NA"?
The virtual memory access shouldn't be slower in a TA than anywhere else. How is this matmul implemented?

**Comment by janoslim** [comment]
Hello, @jenswi-linaro

What i mean by NA means normal world application.
During analysing DarknetZ(https://github.com/mofanv/darknetz) whose main concept is the Running deep neural network in Trusted application, and I noticed that the same GEMM (general matmul) is quite slower when it runs at TA.
The matmul source is here,  https://github.com/mofanv/darknetz/blob/master/ta/gemm_TA.c
And i modified gemm in normal world same with TA, to compare them fairly.
I just make a memcpy test and i noticed that memory access in TA is slower 10 times than NA, and this get greater changes when memory size get bigger.
I am guessing some reasons as hypothesis,
1. page table size in TA is smaller than NA,
2. no mmu support in TA,
3. some encryption & decryption operation exists while accessing trusted application memory,

However, I'm a beginner at optee, so I have difficulty where I can get the rationale for my hypothesis. 
Therefore, I posted an issue because I was wondering if I could get a hint.

Thank you!

**Comment by jenswi-linaro** [comment]
Now it get it. The platform you're using has paging enabled since it's running in secure SRAM only. The lower performance isn't completely unexpected, especially for memory intensive operations. So pages are decrypted and encrypted while the TA is running.

@etienne-lms may have a bit more to say about this.

**Comment by janoslim** [comment]
@jenswi-linaro Thank you for your reply.
You mean that the paging of TA memory in Secure SRAM only? differentiate with NA paging.
And is there hardware side encryption and decryption of TA pages? If it is true, Would you give me a reference to notice such informations of optee configure. Thank you!!

**Comment by etienne-lms** [comment]
> You mean that the paging of TA memory in Secure SRAM only? differentiate with NA paging.

If your optee_os builds with `CFG_WITH_PAGER=y` and `CFG_PAGER_USER_TA=y` then TAs executes in an internal RAM that may be small, or not. If really small, optee_os Core needs to swap memory from/to secure internal RAM to/from less secure external DDR. Pager efficiency depends on internal RAM size and TA virtual memory size and how the TA accesss its memory. It can be dramatically slow (for example, try **xtest 1006** with CFG_TA_BGET_TEST=y is see).

Doc here https://optee.readthedocs.io/en/latest/architecture/core.html?highlight=pager#pager. You may not find the information you look for in that doc.

NA paging, if talking about Linux kernel, usually deals with swapping RAM to/from disk, which can be slow but usually less impacts REE, unless many NA processes do execute at the same time with very big memory area accesses. So OP-TEE paging and Linux swapping are not the same features.

**Comment by janoslim** [comment]
@etienne-lms  Thank you!! I'm getting now.
