### ISSUE TITLE
How hard would it be to add another board to OP-TEE OS?

### ISSUE THREAD

**Issue by friedrich12** [OP-TEE/optee_os#4528]
What would I have to do to add another board to OP-TEE OS? I really want to add the PINE-64 LTS board.

**Comment by etienne-lms** [comment]
Hello @friedrich12,
Best is to start from an existing platform and from porting guidelines doc [1].
Unless one comes to you with an existing port for PINE-64 LTS :)

If something is not clear or wrong in [1], feel free to open an issue in [optee_docs](https://github.com/OP-TEE/optee_docs/issues) or even create a P-R in that repo to propose changes/fixes in the documentation.

[1] https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html
