### ISSUE TITLE
Keep TA state across different sessions

### ISSUE THREAD

**Issue by loblik** [OP-TEE/optee_os#4530]
Is there a way to keep some TA state across sessions?

I would like limit usage of some TA functionality to early boot. The idea was to set some TA variable from bootloader which would prevent operating system later from using this functionality.

**Comment by etienne-lms** [comment]
You could make your TA "keep alive": its instance (context, data) remains even when there is no open session toward it, until OP-TEE Core shuts down.
This allows a client to open/invoke/close a session at boot time and another client open/invoke/close sessions at runtime, talking to the same instance for example. After a cold boot, TA instance is created the first time a client opens a session toward to TA.

An alternate scheme could be to save some state data of the TA in a persistent storage (secure storage/persistent objects). Maybe overkilling if only passing a boot-stage-done state between the sessions.

**Comment by loblik** [comment]
That's what I kind of expected. For persistent approach I would probably need some unique information to identify different boots.

Anyway I gave more background in #4531 . Thanks for clarifying.
