### ISSUE TITLE
AVB TA lock state

### ISSUE THREAD

**Issue by loblik** [OP-TEE/optee_os#4531]
I wanted to use AVB TA to support our verified boot. It's not exactly the Android verified boot, but still we need to store rollback indexes and device lock state. So reusing AVB seems right. But what bothers me is unlock mechanism.

Currenlty it seems anyone with access to TA can unlock the device. So if rich OS gets compromised the device can be unlocked and verified boot disabled. I thought it would make sense to keep verified boot enabled even if rich OS is compromised, as it prevents an attacker doing persistent changes.

AVB 2.0 doc only says:
> The device must only allow state transitions (e.g. from LOCKED to UNLOCKED or UNLOCKED to LOCKED) after asserting physical presence of the user. If the device has a display and buttons this is typically done by showing a dialog and requiring the user to confirm or cancel using physical buttons.

I can think of two approaches to mitigate this.

1) Allow unlocking only from bootloader (using some internal TA state). Bootloader usually has smaller attack surface then full OS.
2) Unlocking done using some challenge signing and verification with public key embedded in TEE.

Would some modifications to current AVB TA be accepted, even if it's not directly mandated by AVB documentation?

Does anyone have a  clue how others who don't use Android are dealing with this? Maybe some more generic TA than AVB could be implemented?

**Comment by jenswi-linaro** [comment]
> Would some modifications to current AVB TA be accepted, even if it's not directly mandated by AVB documentation?

It depends on the change of course, but I think it's worth trying. We may end up with another config flag for this, but if it's useful for others it should be OK.
