### ISSUE TITLE
optee not support ECC 256K1  

### ISSUE THREAD

**Issue by lialvin** [OP-TEE/optee_os#4540]
optee support ecc 256r1  and sm2 ， but  ECC256K1 is very important  .  why  not support ECC 256K1 .  It is need in bitcoin, eth ,etc.

**Comment by jforissier** [comment]
Hi @lialvin,

OP-TEE mainly supports algorithms and curves defined in the GlobalPlatform TEE Internal Core API. I don't think 256K1 is specified by GP. I see that version 1.3 specifies the following 256 bit curves: `TEE_ECC_CURVE_NIST_P256`, `TEE_ECC_CURVE_BSI_P256r1`, `TEE_ECC_CURVE_BSI_P256t1`, `TEE_ECC_CURVE_25519` and `TEE_ECC_CURVE_SM2`. OP-TEE currently implements only `TEE_ECC_CURVE_NIST_P256` and `TEE_ECC_CURVE_SM2`.

 That being said, 256K1 could certainly be added as an extension. Patches are welcome ;-)
