### ISSUE TITLE
Is the SM2 secret key exchange algorithm in optee consistent with that in gmssl

### ISSUE THREAD

**Issue by jiangbinghua** [OP-TEE/optee_os#4541]
I take four pairs of secret keys(A have two pairs of secret keys, B have two pairs of secret keys) in the SM2 secret key exchange program of gmssl as input parameters, and run SM2 secret key exchange in optee, and the shared secret keys are inconsistent.
Is the SM2 secret key exchange algorithm in optee consistent with that in gmssl

**Comment by jforissier** [comment]
Hi @jiangbinghua,

I don't know about gmssl but OP-TEE is supposed to implement the SM2 standard properly, yes. Have you passed proper values for `TEE_ATTR_SM2_KEP_USER`, `TEE_ATTR_SM2_ID_INITIATOR` and `TEE_ATTR_SM2_ID_RESPONDER`? They end up in `struct sm2_kep_params` passed to `crypto_acipher_sm2_kep_derive()`.

**Comment by jiangbinghua** [comment]
Thank you for your reply!
