### ISSUE TITLE
Stack unwind info missing in tee.elf

### ISSUE THREAD

**Issue by userid0x0** [OP-TEE/optee_os#4544]
Hi,
I noticed the Stack/Frame info is missing in the `tee.elf` e.g. using Optee-3.12.
Using Optee-3.8/3.1 the Stack/Frame (`.debug_frame`) info is available .

I tested GCC 8 / 9 / 10 . Any ideas?

**Comment by jforissier** [comment]
Hi @userid0x0,

Which platform are you looking at? On a QEMU (Armv7) build I see this:
```
$ grep debug_frame ../optee_os/out/arm/core/tee.dmp
 23 .debug_frame  00015a58  00000000  00000000  00408774  2**2
00000000 l    d  .debug_frame   00000000 .debug_frame
```
Compiler is GCC 9.2.

**Comment by userid0x0** [comment]
Hi,
I am using ARMv8 at the moment. I debugged a bit further. As the optee-core is position independent, only the `.eh_frame` is generated by GCC. The `.eh_frame` is set to `DISCARD` in `core/arch/arm/kernel/kern.ld.S` .

I did a quick test using 3.12 .
```
  export PLATFORM=vexpress-fvp
  export CROSS_COMPILE64=aarch64-linux-gnu-
  export CROSS_COMPILE32=arm-linux-gnueabihf-
  make CFG_ARM64_core=y -j4
  aarch64-linux-gnu-readelf -e out/arm-plat-vexpress/core/tee.elf
  -> no .debug_frame no .eh_frame .
```
I now patched the `out/arm-plat-vexpress/core/kern.ld`, added the following block
```
.eh_frame : {
  KEEP(*(.eh_frame))
}
```
and removed `.eh_frame` from the DISCARD block. Then I re-ran the linker command from the makefile log (I will not add the complete line here).
The debugger (TRACE32) detects then the Frame info again e.g. `sYmbol.List.FRAME` is not empty anymore.
```
                     P:06001980--06001983|RET:X30 CFA:SP+0x0
                     P:06001984--0600198F|RET:X30 CFA:SP+0x20 X29:*CFA-0x20 X30:*CFA-0x18
                     P:06001990--060019BF|RET:X30 CFA:SP+0x20 X19:*CFA-0x10 X20:*CFA-0x8 X29:*CFA-0x20 X30:*CFA-0x18
                     P:060019C0--060019C3|RET:X30 CFA:SP+0x0
                     P:060019C4--060019CB|RET:X30 CFA:SP+0x20 X19:*CFA-0x10 X20:*CFA-0x8 X29:*CFA-0x20 X30:*CFA-0x18
                     P:060019CC--0600338F|
                     P:06003390--0600347B|RET:X30 CFA:SP+0x0
                     P:0600347C--0600347F|
                     P:06003480--060037E7|RET:X30 CFA:SP+0x0
....
```
I am not so much a linker expert, but `.eh_frame` is now set to 'loadable' in the section table (afaik it's the runtime unwinding info). I do not know what to do with `.rela.eh_frame`.

I assume this could be conveniently prevented using a two stage linking process + a gnu debuglink.
*  `tee.elf` the regular file w/o `.eh_frame` and debug info
*  `tee.debug.elf` full file
Using `objcopy --add-gnu-debuglink=tee.debug.elf tee.elf` you can set the debuglink. GDB and other debuggers will then load the debug info from `tee.debug.elf` when loading `tee.elf`.
.

**Comment by jforissier** [comment]
That's interesting. A few thoughts...

- Why do you need `.eh_frame` in the ELF file during debugging? Is there something that does not work when this section is not present?
- Since `.eh_frame` contains unwinding information, how come our unwinder work without it? (we do get call stack dumps on abort/panic etc. when `CFG_UNWIND=y`). I think the answer is that we just assume "regular" Aarch64 frames (x29/x30 pushed onto the stack on function entry) and that is enough to print the call stack.
- Given that `.eh_frame` doesn't seem to be needed at runtime, I'd rather keep it in the DISCARD block, especially since it's quite big (59 KB in my experience on QEMUv8).
- The debuglink is a nice trick (didn't know about that!) but I'd rather not introduce a new file should be avoided if possible.
- This `.eh_frame` section is apparently equivalent to `.ARM.exidx` and `.ARM.extab` on 32-bit Arm. Could we handle it the same way? That is, not discard it in the linker script but skip it in `scripts/gen_tee_bin.py` instead?

**Comment by userid0x0** [comment]
> Why do you need `.eh_frame` in the ELF file during debugging? Is there something that does not work when this section is not present?

It helps a debugger to unwind the callstack/backtrace. Furthermore it contains information how initial parameters are put onto the stack (GCC only). As you see in the above listing the compiler generates proper information how the stack is structured on every program location.
> Since `.eh_frame` contains unwinding information, how come our unwinder work without it? (we do get call stack dumps on abort/panic etc. when `CFG_UNWIND=y`). I think the answer is that we just assume "regular" Aarch64 frames (x29/x30 pushed onto the stack on function entry) and that is enough to print the call stack.

That's a common heuristic. But why not use the compiler generated info when using an external probe?
The compiler knows best what he did.
Of course there are other approaches like function prolog scanning to detect the layout of the callstack.

> Given that `.eh_frame` doesn't seem to be needed at runtime, it needs to be removed from the runtime binaries, especially since it's quite big (59 KB in my experience on QEMUv8).

Agree with that. That's why I brought the idea of splitting the files.
A proof that it's not 'required/referenced' by the code is that the linker throws it away when linking with `--gc-sections`.

> The debuglink is a nice trick

You are welcome.
> This `.eh_frame` section is apparently equivalent to `.ARM.exidx` and `.ARM.extab` on 32-bit Arm. Could we handle it the same way?

You catched me. No idea, I can try to do some research.
> That is, not discard it in the linker script but skip it in `scripts/gen_tee_bin.py` instead?

Well as I said, `.eh_frame` is marked as loadable in the section table. Becomes also part of the program headers.
If someone tries to load optee from the elf-file he will then load the `.eh_frame` into memory.
Sometimes I like to do that, stop at entry point, load code from elf-file to patch the code without recompile. (Didn't do that with OPTEE yet.)
This will not happen with the other approach.

**Comment by jforissier** [comment]
> > This `.eh_frame` section is apparently equivalent to `.ARM.exidx` and `.ARM.extab` on 32-bit Arm. Could we handle it the same way?
> 
> You catched me. No idea, I can try to do some research.

Hmmm sorry, forget about that...
 
> > That is, not discard it in the linker script but skip it in `scripts/gen_tee_bin.py` instead?

...because I said something wrong here. `.ARM.exidx` and `.ARM.extab` ARE included in the final binary (i.e., they are NOT discarded by `scripts/gen_tee_bin.py`). They are needed to dump call stacks at runtime.

> Well as I said, `.eh_frame` is marked as loadable in the section table. Becomes also part of the program headers.
> If someone tries to load optee from the elf-file he will then load the `.eh_frame` into memory.
> Sometimes I like to do that, stop at entry point, load code from elf-file to patch the code without recompile. (Didn't do that with OPTEE yet.)
> This will not happen with the other approach.

Yeah it sounds reasonable indeed. But that means that `tee.debug.elf` would not reflect the actual binary, I mean its program header would include `.eh_frame` as `PT_LOAD` right? Does this mean the debugger primarily uses `tee.elf` but then when it needs to find something not in `tee.elf` it looks in `tee.debug.elf`?

**Comment by jenswi-linaro** [comment]
It might be possible to add
```
.eh_frame : {
  KEEP(*(.eh_frame))
}
```
just before that `DISCARD` section. I don't think it will affect the binary produced by `scripts/gen_tee_bin.py`.

**Comment by userid0x0** [comment]
I did a short test, with 
* `tee_with_eh_frame.elf` the tee.elf with .eh_frame as discussed
* `tee1.elf` classic GNU-Debuglink approach
* `tee2.elf` objcopy trick removing `.eh_frame` (must be the last section in file)

```
cp ../out/arm-plat-vexpress/core/tee.elf tee_with_eh_frame.elf

cp tee_with_eh_frame.elf tee1.elf
aarch64-linux-gnu-objcopy --only-keep-debug tee1.elf tee1.debug.elf
aarch64-linux-gnu-strip -g tee1.elf
aarch64-linux-gnu-objcopy --add-gnu-debuglink=tee1.debug.elf tee1.elf
ls -lh tee1.elf
ls -lh tee1.debug.elf

aarch64-linux-gnu-objcopy --remove-section .eh_frame tee_with_eh_frame.elf tee_no_eh_frame.elf
cp tee_with_eh_frame.elf tee2.debug.elf
cp tee_no_eh_frame.elf tee2.elf
aarch64-linux-gnu-strip -g tee2.elf
aarch64-linux-gnu-objcopy --add-gnu-debuglink=tee2.debug.elf tee2.elf
ls -lh tee2.elf
ls -lh tee2.debug.elf
```
Result:
```
-rwxr-xr-x 1 ? ? 661K Apr  9 12:19 tee1.elf
-rwxr-xr-x 1 ? ? 3.8M Apr  9 12:19 tee1.debug.elf
-rwxr-xr-x 1 ? ? 598K Apr  9 12:19 tee2.elf
-rwxr-xr-x 1 ? ? 4.2M Apr  9 12:19 tee2.debug.elf
```
* tee2.elf is indeed smaller than tee1.elf.
* I checked TRACE32, when loading tee2.elf the `.eh_frame` section is not loaded to memory, but loaded into the debugger maintenance
* I have no idea how to proof that `.eh_frame` is used by GDB - any ideas?

**Comment by jforissier** [comment]
@jenswi-linaro I think you're right. The following worked for me (QEMUv8 runs OK, TEE binary size unchanged, bigger `tee.elf` with `.eh_frame`):
```diff
diff --git a/core/arch/arm/kernel/kern.ld.S b/core/arch/arm/kernel/kern.ld.S
index 27ebb3dd..ff131f57 100644
--- a/core/arch/arm/kernel/kern.ld.S
+++ b/core/arch/arm/kernel/kern.ld.S
@@ -424,9 +424,20 @@ SECTIONS
 	ASSERT(SIZEOF(.rela) == 0, "Relocation entries not expected")
 #endif
 
+
+	/*
+	 * Aarch64: include the .eh_frame section for use by debuggers. This
+	 * section is not used by the TEE core at runtime.
+	 * By putting it here, scripts/gen_tee_bin.py can discard it and keep
+	 * tee.bin/tee-pager_v2.bin snaller.
+	 */
+	.eh_frame : {
+		KEEP(*(.eh_frame))
+	}
+
 	/DISCARD/ : {
 		/* Strip unnecessary stuff */
-		*(.comment .note .eh_frame .interp)
+		*(.comment .note .interp)
 		/* Strip meta variables */
 		*(__keep_meta_vars*)
 	}
```

@userid0x0 would that work for you?

**Comment by userid0x0** [comment]
Of course.

**Comment by jforissier** [comment]
> Of course.

Cool. Would you like to create a PR or do you prefer I do it? If you do it, perhaps you can better explain the reason why (the TRACE32 thing) but it's up to you.

**Comment by userid0x0** [comment]
What do you mean by PR?

**Comment by jforissier** [comment]
Pull request: https://github.com/OP-TEE/optee_os/pulls

**Comment by userid0x0** [comment]
Let me postpone that till next week. I did further research. I checked why my bare-metal compiler doesn't generate `.eh_frame` but the linux variant does.
When I set `-fno-unwind-tables -fno-asynchronous-unwind-tables` when compiling with aarch64-linux-gnu- I get `.debug_frame` instead of `.eh_frame`. -> Possibly no tricks the linker script/binary conversion required.

**Comment by jforissier** [comment]
@userid0x0 sure, thanks.

**Comment by userid0x0** [comment]
One more question. Does OP-Tee use the `.eh_frame` section at all?
* `kern.ld.S` sets DISCARD `.eh_frame`
* `ta.ld.S` sets KEEP `.eh_frame`
* `ldelf.ld.S` tries to links `.eh_frame`
. So the question is should the generation of the section be prevented centrally (using `arm64-platform-cflags-generic`) what will affect TA's, Optee-Core, LDELF?

**Comment by jforissier** [comment]
TEE core (kern.ld.S) and ldelf don't need `.eh_frame` at runtime. TAs might need it in case C++ is used.

**Comment by userid0x0** [comment]
So my suggestion is:
* set `.eh_frame` to DISCARD for core & ldelf in the linker scripts
* disable generation for `.eh_frame` for core & ldelf -> enables the generation of `.debug_frame` using cflags
* don't touch TA's as these might run C++
Does this make sense?

**Comment by userid0x0** [comment]
Op-Tee core and ldelf use `core-platform-cflags`. 
```diff
diff --git a/core/arch/arm/arm.mk b/core/arch/arm/arm.mk
index c62da6c1..38150cf2 100644
--- a/core/arch/arm/arm.mk
+++ b/core/arch/arm/arm.mk
@@ -141,6 +141,8 @@ arm32-platform-aflags-no-hard-float ?=
 
 arm64-platform-cflags-no-hard-float ?= -mgeneral-regs-only
 arm64-platform-cflags-hard-float ?=
+# Prevent generation of .eh_frame, will produce .debug_frame when CFG_DEBUG_INFO=y
+arm64-platform-cflags-no-eh-frame := $(call cc-option,-fno-unwind-tables) $(call cc-option,-fno-asynchronous-unwind-tables)
 arm64-platform-cflags-generic := -mstrict-align $(call cc-option,-mno-outline-atomics,)
 
 ifeq ($(DEBUG),1)
@@ -179,6 +181,7 @@ core-platform-cppflags += $(arm64-platform-cppflags)
 core-platform-cflags += $(arm64-platform-cflags)
 core-platform-cflags += $(arm64-platform-cflags-generic)
 core-platform-cflags += $(arm64-platform-cflags-no-hard-float)
+core-platform-cflags += $(arm64-platform-cflags-no-eh-frame)
 core-platform-aflags += $(arm64-platform-aflags)
 else
 core-platform-cppflags += $(arm32-platform-cppflags)
 ```

Optionally delete the `.eh_frame` from `ldelf.elf`, is no functional change as `--gc-sections` deletes the section anyway.
```diff
diff --git a/ldelf/ldelf.ld.S b/ldelf/ldelf.ld.S
index 2fda5065..0017bfa3 100644
--- a/ldelf/ldelf.ld.S
+++ b/ldelf/ldelf.ld.S
@@ -29,7 +29,6 @@ SECTIONS {
 	}
         .plt : { *(.plt) }
 
-	.eh_frame : { *(.eh_frame) }
 	.rodata : {
 		*(.gnu.linkonce.r.*)
 		*(.rodata .rodata.*)
@@ -82,5 +81,5 @@ SECTIONS {
 	.data : { *(.data .data.* .gnu.linkonce.d.*) }
 	.bss : { *(.bss .bss.* .gnu.linkonce.b.* COMMON) }
 
-	/DISCARD/ : { *(.interp) }
+	/DISCARD/ : { *(.interp) *(.eh_frame .eh_frame.*) }
 }
```
