### ISSUE TITLE
Xilinx ZCU102 hanging on BL31

### ISSUE THREAD

**Issue by AsmX0r** [OP-TEE/optee_os#4547]
Hello,

I'm currently working on a board Xilinx ZCU102, and I'm trying to boot that board using an SD card with OP-TEE (latest). For that matter, I followed the OP-TEE documentation regarding this board and applied the recommendations in my previous question (#4485). As such, I'm using Petalinux 2018.2 on Ubuntu 16.04. I could successfully flash the SD card (and added the files _BOOT.BIN_ and _image.ub_ in the bootable partition, as well as _dd_ the file _roofs.ext4_ on the second partition).

When I'm booting the board, the boot process is hanging after the logs attached at the end of this issue. Since not much information is provided during the startup, I compiled with the additional flags `CFG_TEE_CORE_LOG_LEVEL=4` and  `CFG_TEE_CORE_DEBUG=y` to gather more insights. Unfortunately, this does not bring more details and report the same information.

At this point, I'm stuck since I have no error message to search for. @ricardosalveti, did you face a similar issue while booting this board with your setup (I know it varies compared to the one documented tho)?

Many thanks for your help!

```
Xilinx Zynq MP First Stage Boot Loader
Release 2018.2   Apr  9 2021  -  15:04:37
NOTICE:  ATF running on XCZU9EG/silicon v4/RTL5.1 at 0xfffea000
NOTICE:  BL31: Secure code at 0x60000000
NOTICE:  BL31: Non secure code at 0x10080000
NOTICE:  BL31: v2.0(release):v2.0
NOTICE:  BL31: Built : 14:47:25, Apr  9 2021
```

**Comment by vesajaaskelainen** [comment]
You may have better luck getting your tooling updated to 2020.2 level.

Wrote something on the topic here:
https://github.com/OP-TEE/optee_os/issues/4488#issuecomment-816819987

**Comment by ricardosalveti** [comment]
Yes, there are some relevant differences in vivado and atf that might be relevant here.

We also use 2020.2 (and no petalinux, we got our own yocto-based distro at https://github.com/foundriesio/meta-lmp / https://docs.foundries.io/latest/reference-manual/linux/linux.html), so might be better for you to upgrade to a newer bsp if possible.

**Comment by AsmX0r** [comment]
Many thanks for your answers.

@vesajaaskelainen I would love to upgrade my tooling to the latest version and I think this is the next step. I wanted to first try a known working environment, but it is apparently not so easy to set up, even with the docs. Do you have any open source repo where I could see your patches or environment to quickly set up a working environment with OP-TEE and the board by chance?

@ricardosalveti The repos of Foundries seem great! May I use them to just compile OP-TEE with the compatibility with my board (I can see Zynq is not referenced here: https://docs.foundries.io/latest/reference-manual/linux/linux-supported.html)?

**Comment by ricardosalveti** [comment]
> Many thanks for your answers.
> 
> @vesajaaskelainen I would love to upgrade my tooling to the latest version and I think this is the next step. I wanted to first try a known working environment, but it is apparently not so easy to set up, even with the docs. Do you have any open source repo where I could see your patches or environment to quickly set up a working environment with OP-TEE and the board by chance?

You might be able to use the upstream optee os build scripts/system as well, check https://github.com/OP-TEE/build
 
> @ricardosalveti The repos of Foundries seem great! May I use them to just compile OP-TEE with the compatibility with my board (I can see Zynq is not referenced here: https://docs.foundries.io/latest/reference-manual/linux/linux-supported.html)?

You should, we use meta-xilinx-bsp and also officially support builds for uz3eg-iocc (zynqmp). Main difference for your target is that the hdf and resulted dtb will be different from what we use. One example of the built artifacts: https://ci.foundries.io/projects/lmp/builds/1260/uz3eg-iocc/

**Comment by linnj** [comment]
Hi, I'm trying to baseline optee with the ZCU102 board also.  Please excuse my newbie-ness and maybe dumb questions.  The documentation is a bit limited or I'm missing something in it and please point me to it if that's the case.  I am loading the bl32.elf file into memory which I question rather than the bin file which appears to have some python post processing done on it.  I'm not able to make the bin file work and it's likely user error on my part.

Right now I'm able to build it bl32.elf get it to run using xtest by commenting out the code in entry_a64.S that does the copy of the boot_embdata as it causes an exception.  I'm thinking bl32.bin is the answer but don't have the details to make it work yet as ATF does not seem to find it when I use it loaded at my normal memory address.

Thanks for any hints,
John
