### ISSUE TITLE
How to add files to the rootfs?

### ISSUE THREAD

**Issue by zm290293817** [OP-TEE/optee_os#455]
Hi, all:
I want to add some files to the rootfs of OP-TEE to test the KVM project. Can someone tell me how to do this? And ,does the OP-TEE support the NFS?

Thanks.

**Comment by vchong** [comment]
Look at https://github.com/linaro-swg/gen_rootfs.
Add your files to filelist.txt, and make sure they're in the proper location relative to the gen_rootfs dir as root.
Then run generate-cpio-rootfs.sh <target>.
Not sure about NFS.

**Comment by zm290293817** [comment]
@vchong OK，thank you.

**Comment by jbech-linaro** [comment]
@vchong already answered, but just to give you some more information you can also have a look [here](https://github.com/OP-TEE/build/blob/master/qemu.mk#L150-L170). It might look complicated at a first glance, but indeed it's rather simple. It is just collecting files and put them in filelist-tee.txt, just as described by vchong.

@zm290293817 @pascal-brand-st can we close this issue?

**Comment by pascal-brand-st-dev** [comment]
According to me, all the information has been provided and we can close this issue. @zm290293817 let me know if it is not the case. Without any answer, I'll close the issue.

**Comment by zm290293817** [comment]
@jbech-linaro  @pascal-brand-st-dev , sorry, i will close this.
