### ISSUE TITLE
Build with CFG_PKCS11_TA fails

### ISSUE THREAD

**Issue by alenik-sha512** [OP-TEE/optee_os#4550]
Hello,

I downloaded all the OPTEE repositories with the repo tool (default.xml) and tried to build the OPTEE (QEMU) with the following command (I found it in the following presentation, page 7 - [link](https://static.linaro.org/connect/lvc21/presentations/lvc21-215.pdf)):

`make run CFG_PKCS11_TA=y`

However the build fails with the following error:

```
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o: in function `xtest_pkcs11_test_1001':
pkcs11_1000.c:(.text+0x83c): undefined reference to `ADBG_EnumTable_CK_RV'
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o: in function `xtest_pkcs11_test_1002':
pkcs11_1000.c:(.text+0xf94): undefined reference to `ADBG_EnumTable_CK_RV'
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o: in function `test_set_pin':
pkcs11_1000.c:(.text+0x1308): undefined reference to `ADBG_EnumTable_CK_RV'
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o: in function `xtest_pkcs11_test_1003':
pkcs11_1000.c:(.text+0x1d9c): undefined reference to `ADBG_EnumTable_CK_RV'
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o: in function `test_create_destroy_single_object':
pkcs11_1000.c:(.text+0x1f68): undefined reference to `ADBG_EnumTable_CK_RV'
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o:pkcs11_1000.c:(.text+0x20e8): more undefined references to `ADBG_EnumTable_CK_RV' follow
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o: in function `__adbg_test_case_1000':
pkcs11_1000.c:(.text.startup+0x5c): undefined reference to `ADBG_Suite_pkcs11'
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o: in function `__adbg_test_case_1001':
pkcs11_1000.c:(.text.startup+0xc8): undefined reference to `ADBG_Suite_pkcs11'
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o: in function `__adbg_test_case_1002':
pkcs11_1000.c:(.text.startup+0x134): undefined reference to `ADBG_Suite_pkcs11'
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o: in function `__adbg_test_case_1003':
pkcs11_1000.c:(.text.startup+0x1a0): undefined reference to `ADBG_Suite_pkcs11'
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o: in function `__adbg_test_case_1004':
pkcs11_1000.c:(.text.startup+0x20c): undefined reference to `ADBG_Suite_pkcs11'
/home/an/work/2021/security/projects/optee/git2/toolchains/aarch32/bin/../lib/gcc/arm-none-linux-gnueabihf/9.2.1/../../../../arm-none-linux-gnueabihf/bin/ld: CMakeFiles/xtest.dir/pkcs11_1000.c.o:pkcs11_1000.c:(.text.startup+0x278): more undefined references to `ADBG_Suite_pkcs11' follow
collect2: error: ld returned 1 exit status
make[5]: *** [host/xtest/CMakeFiles/xtest.dir/build.make:499: host/xtest/xtest] Error 1
make[4]: *** [CMakeFiles/Makefile2:136: host/xtest/CMakeFiles/xtest.dir/all] Error 2
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [package/pkg-generic.mk:250: /home/an/work/2021/security/projects/optee/git2/out-br/build/optee_test_ext-1.0/.stamp_built] Error 2
make[1]: *** [Makefile:23: _all] Error 2
make[1]: Leaving directory '/home/an/work/2021/security/projects/optee/git2/out-br'
make: *** [common.mk:294: buildroot] Error 2
```

Then I built the OPTEE without the PKCS11 flag from above (so just the comand `make run`) and PKCS11 functionality is there?! The `libckteec.so` library is there, `pkcs11-tool` works without any problems.

Is the flag `CFG_PKCS11_TA=y` necessary?

Regards,
Aleksandar

**Comment by etienne-lms** [comment]
`CFG_PKCS11_TA=y` enables pkcs11 tests in **xtest** (optee_test). Currently not more.

**Comment by alenik-sha512** [comment]
Hi Etienne,

thats clarifies some things, but why does the build fail then? Where are the ADBG_xxx functions implemented and why does the OPTEE OS cannot find them?

**Comment by etienne-lms** [comment]
It looks like  optee_test was built with `CFG_PKCS11_TA=y` but optee_os was built without `CFG_PKCS11_TA=y`.
Maybe rebuild optee_os and optee_test (buildroot target):
`make optee-os buildroot CFG_PKCS11_TA=y`

**Comment by etienne-lms** [comment]
I think we could fix your issue from CMakefile, 
```patch
--- a/host/xtest/CMakeLists.txt
+++ b/host/xtest/CMakeLists.txt
@@ -103,6 +103,7 @@ if (CFG_SECURE_DATA_PATH)
 endif()
 
 if (CFG_PKCS11_TA)
+       add_compile_options(-DCFG_PKCS11_TA)
        list (APPEND SRC pkcs11_1000.c)
 endif()
 
```

Makes sense to you?

**Comment by alenik-sha512** [comment]
Yep, that solves it. Thanks. I'll close the issue now.

**Comment by etienne-lms** [comment]
@alenik-sha512: I could add you as reporter and tester for the change in https://github.com/OP-TEE/optee_test/pull/504
```
Reported-by: Aleksandar Xxxxx <xxx@yyy.zzz>
Tested-by: Aleksandar Xxxxx <xxx@yyy.zzz>
```
If you want so (you deserves the credits), please provide the identity I should use (real name + mail addres, as per [contribute](https://optee.readthedocs.io/en/latest/general/contribute.html#contribute) doc).

**Comment by qq8512852** [comment]
when I run the command "xtext -t pkcs11" on 3.12.0 (QEMU) , after make CFG_PKCS11_TA=y. The problem "ERR [283] LT:ckteec_invoke_init:305: TEEC open session failed ffff0008 from 3" make me confused.

**Comment by jforissier** [comment]
> when I run the command "xtext -t pkcs11" on 3.12.0 (QEMU) , after make CFG_PKCS11_TA=y. The problem "ERR [283] LT:ckteec_invoke_init:305: TEEC open session failed ffff0008 from 3" make me confused.

The TA is not found. Since you're using 3.12.0 you probably need to add build.git commit [3.12.0-5-gd77eb5e](https://github.com/OP-TEE/build/commit/d77eb5e).

**Comment by qq8512852** [comment]
> 
 Thanks. 
I have tried to make 3.17.0 on QEMU. It works smoothly.
However, I complied the 3.18.0 to raspberry pi 3, the same problem happened.
**"ckteec_invoke_init:304: TEEC open session failed ffff0008 from 3"**
I will follow your tips to fix it.

**Comment by qq8512852** [comment]
> > > when I run the command "xtext -t pkcs11" on 3.12.0 (QEMU) , after make CFG_PKCS11_TA=y. The problem "ERR [283] LT:ckteec_invoke_init:305: TEEC open session failed ffff0008 from 3" make me confused.
> > 
> > 
> > The TA is not found. Since you're using 3.12.0 you probably need to add build.git commit [3.12.0-5-gd77eb5e](https://github.com/OP-TEE/build/commit/d77eb5e).
> 
> Hi, the program(3.18.0) run in Rpi3 met the same problem. I fount the "fd02c9da-306c-48c7-a49c-bbd827ae86ee.ta" lost. How can I fix it?

Do some print. I find the problem on the variable (OPTEE_OS_EXT_SDK). On the rpi3 the aarch64 be used to compile. So the OPTEE_OS_EXT_SDK point to "../optee_os/out/arm/export-ta_arm64". But actually the related ta("fd02c9da-306c-48c7-a49c-bbd827ae86ee.ta") is compiled in ../optee_os/out/arm/export-ta_arm32. So just change the path to fix it.

**Comment by etienne-lms** [comment]
Could you create a P-R to share the fix?

**Comment by qq8512852** [comment]
> Could you create a P-R to share the fix?

of course. Give me some time, please. I need to do some deep research. Now my solution is just  a temporary one.

**Comment by jforissier** [comment]
Setting `CFG_USER_TA_TARGET_pkcs11=ta_arm64` could help.

**Comment by qq8512852** [comment]
> Setting `CFG_USER_TA_TARGET_pkcs11=ta_arm64` could help.

“make CFG_PKCS11_TA=y CFG_USER_TA_TARGET_pkcs11=ta_arm64”
It's working. 
Thanks for your help.
![image](https://user-images.githubusercontent.com/15918325/181174454-005d9a9a-68bb-4e76-96c1-6bf4cdaf72ca.png)
