### ISSUE TITLE
How to share data with QEMU V8

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#4553]
I am trying to study optee using QEMU V8.

I configured and operated the optee environment using the information in the link below, but there is a problem of data sharing between the host and QEMU.
I am working on ubuntu 18.04, and the details that I have performed are as follows.

https://optee.readthedocs.io/en/latest/building/prerequisites.html#prerequisites
$ sudo dpkg --add-architecture i386
$ sudo apt-get update

$ sudo apt-get install android-tools-adb android-tools-fastboot autoconf \
        automake bc bison build-essential ccache cscope curl device-tree-compiler \
        expect flex ftp-upload gdisk iasl libattr1-dev libcap-dev \
        libfdt-dev libftdi-dev libglib2.0-dev libhidapi-dev libncurses5-dev \
        libpixman-1-dev libssl-dev libtool make \
        mtools netcat python-crypto python3-crypto python-pyelftools \
        python3-pycryptodome python3-pyelftools python-serial python3-serial \
        rsync unzip uuid-dev xdg-utils xterm xz-utils zlib1g-dev

https://optee.readthedocs.io/en/latest/building/devices/qemu.html?highlight=qemu#qemu-v8
$ repo init -u https://github.com/OP-TEE/manifest.git -m **qemu_v8.xml**
$ repo sync -j12
$ cd build
$ make toolchains
$ make -j12
$ make run-only

cd /home6/work/build/../out/bin && /home6/work/build/../qemu/build/aarch64-softmmu/qemu-system-aarch64 \
        -nographic \
        -serial tcp:localhost:54320 -serial tcp:localhost:54321 \
        -smp 2 \
        -s -S -machine virt,secure=on -cpu cortex-a57 \
        -d unimp -semihosting-config enable,target=native \
        -m 1057 \
        -bios bl1.bin \
        -initrd rootfs.cpio.gz \
        -kernel Image -no-acpi \
        -append 'console=ttyAMA0,38400 keep_bootcon root=/dev/vda2' \
        -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,max-bytes=1024,period=1000 -netdev user,id=vmnic -device virtio-net-device,netdev=vmnic
qemu-system-aarch64: -semihosting-config enable,target=native: warning: short-form boolean option 'enable' deprecated
Please use enable=on instead
QEMU 5.2.50 monitor - type 'help' for more information
(qemu) c

I confirmed that two xwindows (normal world, secure world) appear in this state. After that, I connected to the root account on the normal world and ran xtest. As shown in the figure below, I confirmed that the results of xtest are normal.

---------------------------------------
25803 subtests of which 0 failed
92 test cases of which 0 failed
0 test cases were skipped
TEE test application done!

I proceeded by referring to the contents below for data file transfer between the host and QEMU.

https://optee.readthedocs.io/en/latest/building/devices/qemu.html?highlight=qemu#host-guest-folder-sharing

$ make QEMU_VIRTFS_ENABLE=y QEMU_USERNET_ENABLE=y run

When I execute the above command, the following error occurs.

...
make run-only
make[1]: Entering directory '/home6/work/build'
ln -sf /home6/work/build/../out-br/images/rootfs.cpio.gz /home6/work/build/../out/bin/

* QEMU is now waiting to start the execution
* Start execution with either a 'c' followed by <enter> in the QEMU console or
* attach a debugger and continue from there.
*
* To run OP-TEE tests, use the xtest command in the 'Normal World' terminal
* Enter 'xtest -h' for help.

/usr/bin/xterm: cannot load font "-Misc-Fixed-bold-R-*-*-13-120-75-75-C-60-ISO8859-1"
/usr/bin/xterm: cannot load font "-Misc-Fixed-bold-R-*-*-13-120-75-75-C-60-ISO8859-1"
/usr/bin/xterm: cannot load font "-Misc-Fixed-medium-R-*-*-13-120-75-75-C-120-ISO10646-1"
/usr/bin/xterm: cannot load font "-Misc-Fixed-medium-R-*-*-13-120-75-75-C-120-ISO10646-1"
/usr/bin/xterm: cannot load font "-Misc-Fixed-bold-R-*-*-13-120-75-75-C-120-ISO10646-1"
/usr/bin/xterm: cannot load font "-Misc-Fixed-bold-R-*-*-13-120-75-75-C-120-ISO10646-1"
/usr/bin/xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
/usr/bin/xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
cd /home6/work/build/../out/bin && /home6/work/build/../qemu/build/aarch64-softmmu/qemu-system-aarch64 \
        -nographic \
        -serial tcp:localhost:54320 -serial tcp:localhost:54321 \
        -smp 2 \
        -s -S -machine virt,secure=on -cpu cortex-a57 \
        -d unimp -semihosting-config enable,target=native \
        -m 1057 \
        -bios bl1.bin \
        -initrd rootfs.cpio.gz \
        -kernel Image -no-acpi \
        -append 'console=ttyAMA0,38400 keep_bootcon root=/dev/vda2' \
        -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,max-bytes=1024,period=1000 -fsdev local,id=fsdev0,path=/home6/work/build/..,security_model=none -device virtio-9p-device,fsdev=fsdev0,mount_tag=host -netdev user,id=vmnic -device virtio-net-device,netdev=vmnic
qemu-system-aarch64: -semihosting-config enable,target=native: warning: short-form boolean option 'enable' deprecated
Please use enable=on instead
QEMU 5.2.50 monitor - type 'help' for more information
(qemu) qemu-system-aarch64: -device virtio-9p-device,fsdev=fsdev0,mount_tag=host: 'virtio-9p-device' is not a valid device model name
Makefile:197: recipe for target 'run-only' failed
make[1]: *** [run-only] Error 1
make[1]: Leaving directory '/home6/work/build'
Makefile:191: recipe for target 'run' failed
make: *** [run] Error 2

I also checked the contents of the link below, but it is still not working. Although two xwindows are visible, an error occurs as above.

https://github.com/OP-TEE/optee_os/issues/3901
$ make -j8 QEMU_VIRTFS_ENABLE=y run

For reference, I have also followed the answer in the link below, but other kinds of errors are occurring. 
https://github.com/OP-TEE/optee_os/issues/4490

If you know what to do in this situation, please answer.

**Comment by jforissier** [comment]
Hi @SangsubLim ,

I think dependencies are missing on you build host. See https://github.com/nvdla/vp/issues/6#issuecomment-359705065.

**Comment by SangsubLim** [comment]
Hi @jforissier,

Thanks for your help. After installing the two packages below, I tried again and confirmed that it worked.
libattr1-dev, libcap-ng-dev
Thank you.

**Comment by saleh-unikie** [comment]
I have a similar problem when running the Qemu-v7
`~/Projects/op-tee/build$ make QEMU_VIRTFS_ENABLE=y QEMU_USERNET_ENABLE=y run`

Then I will see this error:
`QEMU 6.0.0 monitor - type 'help' for more information
(qemu) qemu-system-arm: -device virtio-9p-device,fsdev=fsdev0,mount_tag=host: 'virtio-9p-device' is not a valid device model name
make[1]: *** [Makefile:177: run-only] Error 1
make[1]: Leaving directory '/home/saleh/Projects/op-tee/build'
make: *** [Makefile:165: run] Error 2
`

Two new terminal are opened but qemu console has terminated.
I have installed libattr1, libattr1-dev and libcap-ng-dev on my Ubuntu 20, but it didn't solve the problem.

**Comment by jforissier** [comment]
`rm -rf ../qemu/build` maybe?

**Comment by saleh-unikie** [comment]
Yes it worked, thank you :)
