### ISSUE TITLE
How to check the time taken for a TA to be loaded into OP-TEE?

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#4558]
So, i have disabled the CFG_SECSTOR_TA option.
Now, i would like to measure the time taken for a trusted application to be loaded into OP-TEE.
It would be great if i get some hints as to where i can start.

If i'm not wrong, now the TA loading should be faster than for the case when CFG_SECSTOR_TA was enabled by default because if this option is disabled, then OP-TEE won't check whether that particular TA is indeed present in the TA.DB or not before loading -  right?

**Comment by Hussain1811** [comment]
So, basically the TEE supplicant loads the TA from linux file system (/lib/optee_armtz) and puts it into OP-TEE OS.
I'm just wondering if we could measure the time taken by the TEE supplicant somehow.

**Comment by etienne-lms** [comment]
TA image is loaded in RAM from [`ldelf_syscall_open_bin()`](https://github.com/OP-TEE/optee_os/blob/3.12.0/core/kernel/ldelf_syscalls.c#L139) where `binh->op->open(uuid, &binh->h);` does the binary loading once found in one of the storage: early tas, db installed tas, ree tas (from _/lib/optee_armtz_).

You could measure time before/after and get the diff, with something like the below. This would exclude the ELF loading part, done after `ldelf_syscall_open_bin()` completes.
I'm a bit unsure about when `CFG_ULIBS_SHARED=y`, when dependency libs image shall also be loaded.

```c
#include <kernel/delay.h>

static unsigned int arm_cnt_cnt2us(uint64_t cnt)
{
	return (cnt * 1000000ULL) / read_cntfrq();
}

void some_function(void)
{
	uin64_t start = 0;
	uin64_t end = 0;

	start = read_cntpct();
	{ some processing }
	end = read_cntpct();

	IMSG("time spent in microseconds: %u", arm_cnt_cnt2us(end - start));
}

**Comment by Hussain1811** [comment]
Actually, i'm using OP-TEE 3.1 where i don't seem to see ldelf_syscall_open_bin()
