### ISSUE TITLE
QEMU Setup

### ISSUE THREAD

**Issue by lordqwerty** [OP-TEE/optee_os#456]
In [setup_qemu_optee.sh](https://github.com/OP-TEE/optee_os/blob/master/scripts/setup_qemu_optee.sh#L41) line 41, when running the script it appears that Christoffer Dall repository no longer exists.

Has it been removed or renamed? I noticed that Christoffer Dall has another [arm-qemu](https://git.linaro.org/people/christoffer.dall/qemu-arm.git) repo, is this the same or different?

Thank you for any light you might be able to shine on the subject. 
Cheers!

Jorden

**Comment by vchong** [comment]
You can replace it with https://github.com/linaro-swg/qemu.git, but please note that we are currently changing the way environments are imported. We are now using android-like manifest and build. Please have a look at https://github.com/OP-TEE/manifest/blob/master/README.md. It will guide you to retrieve qemu environment using this new way. Please let us know if you still face issues with this new way of proceeding.

Note that setup scripts are obsolete, and will be removed soon.

**Comment by jbech-linaro** [comment]
The script has been removed now. @lordqwerty @pascal-brand-st-dev can we close this issue?

**Comment by lordqwerty** [comment]
Happy for it to be closed.

Cheers.
