### ISSUE TITLE
Linking libutee to pseudo TA code-base

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#4562]
The root of the pseudo TA folder has a sub.mk file.
Can we somehow link libutee here?
But, libutee is a static library and not a dynamic one. Hence, a little confused.

**Comment by Hussain1811** [comment]
OK.
Thanks for the information.
But, the reason for asking is, I would like to use the time APIs(Ex: TEE_GetSystemTime) to measure the time taken by an operation being executed inside the pseudo TA.

**Comment by jforissier** [comment]
Then you need to figure out which function inside the TEE core implements `TEE_GetSystemTime()`. That would be `syscall_get_time()`.

**Comment by Hussain1811** [comment]
Sure.
Thanks a lot :)
I'll give it a try.
