### ISSUE TITLE
Is there a way to give different permissions to different Linux process to invoke TA

### ISSUE THREAD

**Issue by noe77777** [OP-TEE/optee_os#4563]
Hi OP-TEE maintainers,

  If we want to give only some specific Linux processes permission to invoke a specific TA,
  and we only can modify OP-TEE or Trusted Firmware source code, is there any way to implement 
  it?   
  Thanks.

**Comment by jenswi-linaro** [comment]
The best would be to let the TA check that the calling client application has authenticated itself with `TEEC_LOGIN_GROUP`. Note that you're relying on the kernel to check that it's using the correct group.

**Comment by noe77777** [comment]
HI @jenswi-linaro ,

  Thanks for your information.
  We will trace code to find out how to utilize TEEC_LOGIN_GROUP.
