### ISSUE TITLE
Early TA/ User Space TA/ Pseudo TA - Which is loaded into OP-TEE first?

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#4565]
It would be great if i get some pointers w.r.t order in which these Trusted Applications are loaded into OP-TEE.

**Comment by jforissier** [comment]
Early TAs and Pseudo TAs are part of the OP-TEE binary so they are available immediately after boot. Early TAs run in user space, Pseudo TA run in kernel space. Regular user space TAs are stored in the REE filesystem, they are loaded on demand by `tee-supplicant` so the Rich OS has to be up and running.

**Comment by Hussain1811** [comment]
So, basically the order is Early TA --> Pseudo TA ---> Regular user space TA's

Meaning, if i enable/disable the CFG_SECSTOR_TA compile option, then there won't be any difference w.r.t the time taken to load a pseudo or early TA into OP-TEE because this option only checks whether the "regular user space TA's" are present in TA.DB or not. 
This option basically has nothing to do with pseudo TA's or Early TA's.

However, the loading of regular user space TA's would be faster if CFG_SECSTOR_TA is disabled as there is no additional time spent to check whether the TA is present in the TA.DB or not.

Am i correct?

**Comment by jforissier** [comment]
> Am i correct?

Yes, 100%.

**Comment by Hussain1811** [comment]
> 
> 
> > Am i correct?
> 
> Yes, 100%.

OK - Thanks

I was finding it a bit difficult to trace the code where this aspect (the sequence of loading TA's) is reflected.

**Comment by etienne-lms** [comment]
Few additional info, in case it helps someone. Links below refer to optee_os release 3.12.0.

The ordering for finding target TA is driven from 2 main places:
1st from [`tee_ta_init_session()`](https://github.com/OP-TEE/optee_os/blob/3.12.0/core/kernel/tee_ta_manager.c#L670):
* case TA instance already loaded => just use the TA instance
* case TA is the StMM service (StMM specific case) => get StMM image from Core binary.
* case TA is a PTA (Core PTA service) => no binary to load.
* else: look for a TA binary from a TA store (case `tee_ta_init_user_ta_session()` is called). This is the 2nd place.

For this 2nd place, the magic is done by [`ldelf_syscall_open_bin()`](https://github.com/OP-TEE/optee_os/blob/3.12.0/core/kernel/ldelf_syscalls.c#L155): it looks into the registered TA stores for a matching TA.
TA stores are registered through macro [`REGISTER_TA_STORE(priority)`](https://github.com/OP-TEE/optee_os/blob/3.12.0/core/include/kernel/ts_store.h#L56). TA stores of low priority value are search first:
* Early TA binaries case, see [early_ta.c#L36](https://github.com/OP-TEE/optee_os/blob/3.12.0/core/arch/arm/kernel/early_ta.c#L36). Depends on `CFG_EARLY_TA=y`.
Priority = 2. 
* TA binaries installed in OP-TEE secure storage, see [secstor_ta.c#L80](https://github.com/OP-TEE/optee_os/blob/3.12.0/core/arch/arm/kernel/secstor_ta.c#L80). Depends on `CFG_SECSTOR_TA=y`.
Priority = 4.
* TA binaries in REE files (i.e. _/lib/optee_armtz/_), see [ree_fs_ta.c#L517](https://github.com/OP-TEE/optee_os/blob/3.12.0/core/arch/arm/kernel/ree_fs_ta.c#L517) or [ree_fs_ta.c#L653](https://github.com/OP-TEE/optee_os/blob/3.12.0/core/arch/arm/kernel/ree_fs_ta.c#L653) (case `CFG_REE_FS_TA_BUFFERED=y`).
Priority = 9

**Comment by Hussain1811** [comment]
Hello @etienne-lms ,

The information was magical.
Thanks a lot for the detailed response.

I shall be closing this issue.

**Comment by mardyr** [comment]
Following into that after more than two years. I am looking into the code I cannot figure out how you've entered  [ldelf_syscall_open_bin()](https://github.com/OP-TEE/optee_os/blob/3.12.0/core/kernel/ldelf_syscalls.c#L155), from `tee_ta_init_user_ta_session`. Only way to call it is via `ldelf_syscall_table` which called in `scall_handle_ldelf`. I though that is could be used inside `ldelf_init_with_ldelf` but here I cannot see any usage

**Comment by etienne-lms** [comment]
@mardyr, ldelf syscalls are defined in [`scall.c`](https://github.com/OP-TEE/optee_os/blob/4.0.0/core/kernel/scall.c#L130-L143). `ldelf_syscall_open_bin()` for the core part, and [_ldelf/syscalls_asm.S_](https://github.com/OP-TEE/optee_os/blob/4.0.0/ldelf/syscalls_asm.S) for the userland part.
`tee_ta_init_user_ta_session()` loads a TA in secure userland memory: to do so it first loads a ELF loader image in the TA memory and executes it. The ELF loader image issues syscalls, as `LDELF_OPEN_BIN`, to get the TA image be loaded etc...
