### ISSUE TITLE
Is there a plan to support build CPP TA with clang toolchain?

### ISSUE THREAD

**Issue by orzzz0815** [OP-TEE/optee_os#4566]
Hi OP-TEE maintainers,

We have some CPP TAs in our platform and use clang toolchain. But it seems to not support using clang toolchain to build CPP TA. We would like to know that do you have a plan for supporting build CPP TA with Clang. Or it is too hard to fix the problems which is mention in [be3bc46](https://github.com/OP-TEE/optee_os/commit/be3bc461c686e7d610e7dad46452ed70b580fb6c).

**Comment by jforissier** [comment]
Hi @orzzz0815,

I am not aware of any plan at the moment, and I haven't tried to build C++ TA code with Clang either so I have no idea how complex it would be to support it. Feel free to try and discuss any issue you may meet here on GitHub.

**Comment by orzzz0815** [comment]
Hi @jforissier 
Thanks for your prompt reply.
We may try to work on it.
