### ISSUE TITLE
Signed ELF TA PR memory corruption

### ISSUE THREAD

**Issue by paswan-ms** [OP-TEE/optee_os#457]
I'm encountering a memory corruption problem using the signed ELF TA PR. 
The open session successfully loads the TA and opens the session but a subsequent invoke command finds the session list data (ta_session) is corrupt - i.e. the session list data is OK in the open session call to ta_header_get_session but in the next invoke command it's corrupted.  This is true even if all the TA does is print a debug message in all it's top level entry points. I only see this with the "big TA" that has ~1Mb ELF and ~540Kb of BSS and ABS32 relocs (none of which are being called, however). The overwriting data is freed normal-world shared memory that previously contained the load TA image. I'm investigating and will report back if I find the issue.

Update: The faulting address is TA user address 0x34e3d0 with a load addr: 0x200000 and code area 0x8100000. The corrupt data content is physical data that is located at 0x874e3d0 (0x8700000 is the normal world shared memory block base). I'm now investigating if there is something wrong with the MMU mapping for the 2nd megabyte of the TA address space that contains most of the BSS for this TA. Is this sort of issue familiar to anyone or hint at an obvious configuration error?
Thanks,
Paul.

**Comment by paswan-ms** [comment]
This does look to be a problem with calculating the MMU map. The open session call sets this map:
`DBG TEE-CORE:set_region:360: va=0x100000,size=0x0,attr=0x0`
`DBG TEE-CORE:set_region:360: va=0x100000,size=0x100000,attr=0x151b1`
`DBG TEE-CORE:set_region:363: idx=0x1,pa=0x8300000`
`DBG TEE-CORE:set_region:360: va=0x200000,size=0x0,attr=0x0`
`DBG TEE-CORE:set_region:360: va=0x200000,size=0x200000,attr=0x153b1`
`DBG TEE-CORE:set_region:363: idx=0x2,pa=0x8100000`
`DBG TEE-CORE:set_region:363: idx=0x3,pa=0x8200000`
`DBG TEE-CORE:set_region:360: va=0x400000,size=0x1c00000,attr=0x0`
`DBG TEE-CORE:set_region:363: idx=0x5,pa=0x100000`
`...`

...but the subsequent call to invoke command sets this map:

`DBG TEE-CORE:set_region:360: va=0x100000,size=0x0,attr=0x0`
`DBG TEE-CORE:set_region:360: va=0x100000,size=0x100000,attr=0x151b1`
`DBG TEE-CORE:set_region:363: idx=0x1,pa=0x8300000`
`DBG TEE-CORE:set_region:360: va=0x200000,size=0x0,attr=0x0`
`DBG TEE-CORE:set_region:360: va=0x200000,size=0x200000,attr=0x153b1`
`DBG TEE-CORE:set_region:363: idx=0x2,pa=0x8100000`
`DBG TEE-CORE:set_region:363: idx=0x3,pa=0x8200000`
`DBG TEE-CORE:set_region:360: va=0x400000,size=0xfff00000,attr=0x0`
**`DBG TEE-CORE:set_region:360: va=0x300000,size=0x100000,attr=0x51b1`**
**`DBG TEE-CORE:set_region:363: idx=0x3,pa=0x8700000`**
`DBG TEE-CORE:set_region:360: va=0x400000,size=0x1c00000,attr=0x0`
`DBG TEE-CORE:set_region:363: idx=0x4,pa=0x0`
`DBG TEE-CORE:set_region:363: idx=0x5,pa=0x100000`
`...`
...where it looks like a duplicate VA entry is being set for the top 1Mb of the TA space mapping it to the wrong PA.

**Comment by jenswi-linaro** [comment]
Thanks Paul, that looks like a correct fix. Do you want to create a PR for this or should I do it?

**Comment by paswan-ms** [comment]
Submitted: https://github.com/OP-TEE/optee_os/pull/459
