### ISSUE TITLE
QEMU supports early TA?

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#4570]
I am going to do a study on Early TA.
I configured the environment with qemu_v8 and confirmed that xtest works well.
In order to learn about Early TA, I am looking at the materials below and other people's questions.
https://github.com/OP-TEE/optee_os/commit/d0c636148b3a

https://github.com/OP-TEE/optee_os/issues/4565
https://github.com/OP-TEE/optee_os/issues/4399
https://github.com/OP-TEE/optee_os/issues/3357

From my understanding, it seems that Early TA is included in OPTEE OS differently from REE Filesystem TA, and RPMB is essential.
https://github.com/OP-TEE/optee_os/issues/4399#issuecomment-781294931

Q1) Can RPMB work in QEMU V8? If not, I would like to ask if it is possible with RPI3+.
If it becomes RPMB, is it possible to configure Early TA? 

Q2) Where is the sample or test code of Early TA?
I want to learn based on the part called by Uboot and the part handled by SecureOS. 

Q3) Is it possible to develop REE Filesystem TA first, and then convert it to Ealry TA?

Q4) Finally, after Linux Booting is finished, is it possible to call Early TA from CA?
Looking at the data and codes I have seen, I think Ealry TA is also possible because it appears to be one of several TAs. 

Thank you for always helping.

**Comment by jforissier** [comment]
Hi @SangsubLim ,

> From my understanding, it seems that Early TA is included in OPTEE OS differently from REE Filesystem TA, and RPMB is essential.

No, RPMB and early TA are unrelated.

> Q1) Can RPMB work in QEMU V8? If not, I would like to ask if it is possible with RPI3+.
> If it becomes RPMB, is it possible to configure Early TA?

RPMB does work with QEMUv8 (it is emulated in `tee-supplicant` actually, all platforms use this emulation by default for testing). but as I said, unrelated and not needed for early TAs.

> Q2) Where is the sample or test code of Early TA?
> I want to learn based on the part called by Uboot and the part handled by SecureOS.

Any TA can be embedded as an early TA. However depending on how early you need to execute it, some services might or might not be available to OP-TEE (such as the Linux driver and `tee-supplicant`). That is where U-Boot might be involved. But it is very specific cases.
 
> Q3) Is it possible to develop REE Filesystem TA first, and then convert it to Ealry TA?

Yes.

> Q4) Finally, after Linux Booting is finished, is it possible to call Early TA from CA?
> Looking at the data and codes I have seen, I think Ealry TA is also possible because it appears to be one of several TAs.

Yes, for example:

```
build $ make -j10 && make -j10 EARLY_TA_PATHS=../out-br/build/optee_examples_ext-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.stripped.elf run

QEMU 5.2.50 monitor - type 'help' for more information  
(qemu) c

Welcome to Buildroot, type root or test to login
buildroot login: test
$ optee_example_hello_world
Invoking TA to increment 42
TA incremented value to 43
$ 

D/LD:  ldelf:134 Loading TS 8aaaf200-2450-11e4-abe2-0002a5d5c51b
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (early TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0
D/LD:  ldelf:168 ELF (8aaaf200-2450-11e4-abe2-0002a5d5c51b) at 0x4003d000
```

**Comment by SangsubLim** [comment]
Hi @jforissier ,

I think your answers have solved my many questions.
What I'm trying to do is call Early TA from uboot.
There is no specific case, but I want to do something in Secure World before the Linux Kernel loads. In other words, there will be no tee-supplicant.
For example, it may be to access a specific partition and verify the signature.
Perhaps such a feature exists in AVB (android verified boot).

Many of the questions here and your answers made me understand. There seems to be only one thing I am curious about now.
Based on qemu v8, this is how to call Ealry TA in uboot.
There seems to be no related part in the example or test provided by optee. Or it seems I haven't found it yet.

I am grateful once again for the responses from you and others.

**Comment by jforissier** [comment]
> Many of the questions here and your answers made me understand. There seems to be only one thing I am curious about now.
> Based on qemu v8, this is how to call Ealry TA in uboot.
> There seems to be no related part in the example or test provided by optee.

Correct.

> I was suddenly curious while writing, where is the boot code(such as uboot) in QEMU v8?

[`qemu_v8.xml`](https://github.com/OP-TEE/manifest/blob/3.12.0/qemu_v8.xml) does not use U-Boot, it uses UEFI (Tianocore EDK2) instead. [`default.xml`](https://github.com/OP-TEE/manifest/blob/3.12.0/default.xml), which is QEMU for Arm-v7, does use U-Boot however.

> I have just started studying armv8 and QEMU.
> If it is impossible to call TA before uboot on QEMU, I would like to ask if it is possible in rpi3 B+.

It should be possible to replace TF-A and EDK2 with U-Boot, or you could use QEMU (v7).

> As far as I know, AArch64's boot steps are as follows.
> I think BL2 is the bootcode here. If so, does TF-A play the uboot role in aarch64?

No, BL2 is just a part of TF-A responsible for loading the BL3-* binaries.

>     * Boot Loader stage 1 (BL1) AP Trusted ROM
> 
>     * Boot Loader stage 2 (BL2) Trusted Boot Firmware
> 
>     * Boot Loader stage 3-1 (BL3-1) EL3 Runtime Firmware
> 
>     * Boot Loader stage 3-2 (BL3-2) Secure-EL1 Payload (optional)
> 
>     * Boot Loader stage 3-3 (BL3-3) Non-trusted Firmware

In our current QEMUv8 environment, BL1, BL2 and BL3-1 are provided by TF-A. BL3-2 is OP-TEE, and BL3-3 is EDK2. See [here](https://github.com/OP-TEE/build/blob/3.12.0/qemu_v8.mk#L67-L71). For QEMU it is the same except BL3-3 is U-Boot, see [here](https://github.com/OP-TEE/build/blob/3.12.0/qemu.mk#L54-L58).

**Comment by SangsubLim** [comment]
Thank you @jforissier jforissier.

As you suggested, I will try first in QEMU v7.
Your answer was very helpful.
