### ISSUE TITLE
Can SGI be used for secure-to-nonsecure communication?

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#4576]
Hi, in our platform there's no secure console exists, to print the error log in opteeos, we implement a log buffer that stores the log.  When function returns from opteeos, the REE will print it out.  

_u32 optee_do_call_with_arg(struct tee_context *ctx, phys_addr_t parg)
{
...
150 >-------while (true) {
151 >------->-------struct arm_smccc_res res;
152 
153 >------->-------optee->invoke_fn(param.a0, param.a1, param.a2, param.a3,
154 >------->------->------->------- param.a4, param.a5, param.a6, param.a7,
155 >------->------->------->------- &res);
156 
157 #ifdef CONFIG_OPTEE_VIRTUAL_UART
158 >------->-------{                                                                                                                                                                                       
159 >------->------->-------char *buf = NULL;
160 >------->------->-------buf = get_msg_from_tee();
161 >------->------->-------if (buf)
162 >------->------->------->-------pr_alert("%s", buf);           //print out the optee log buf
163 >------->-------}
164 #endif
...
}_

However, the solution doesn't work for the log in secure interrupt context. 

So we consider to use SGI to solve the issue as below:
1.  In secure interrupt, EMSG will trigger a SGI to current cpu;
2.  When exits from secure interrupt, the cpu will switch to REE to handle the SGI;
3.  In REE SGI handler, the cpu print the log buffer. 

I'm not sure if there's any better mechanism in opteeos can solve it? Or is there any risk in my design? Any suggestion is really appreciated!

BTW, there seems a similar design raised in 2014:  https://patchwork.kernel.org/project/linux-omap/patch/79CD15C6BA57404B839C016229A409A83EDAD1B8@DBDE04.ent.ti.com/

**Comment by jenswi-linaro** [comment]
Hi @tiger20081015,
I've just started working on an asynchronous notification mechanism from OP-TEE in secure world to Linux in normal world. It will take a few more weeks before I have code worth sharing. I'm not going to use a SGI, instead I'll use an unused SPI which I will trigger by setting corresponding bit in `ISPENDRx`.

**Comment by tiger20081015** [comment]
Thanks @jenswi-linaro, Looking forward to your patches.  
Just curious, what's your consideration of using unused SPI instead of SGI?

**Comment by jenswi-linaro** [comment]
Doing it via a SGI in the Linux kernel would take a lot of time and energi and I still doubt I'd be able to pull it off, at least for arm32.
If you look at how SGIs are handle on arm32 you see that adding another SGI dynamically will not be easy. The easy part is writing the code, the hard part is to get it accepted.

With SPI on the other hand it's just a matter of finding an unused SPI in the system and then configure Linux to use that, not much different from other drivers. SPI is good enough for this purpose, at least for now.

**Comment by tiger20081015** [comment]
Thanks for your prompt answer. I understood now.

**Comment by tiger20081015** [comment]
Hi, @jenswi-linaro, 
Happy New Year! 
I saw recently you'd submitted below patch, is it the one you mentioned "an asynchronous notification mechanism from OP-TEE in secure world to Linux in normal world." in this list? Does the linux side also need the supportive patches? Thanks. 

commit c2d449482de098f1c894b94f338440e5a327813d
Author: Jens Wiklander <jens.wiklander@linaro.org>
Date:   Tue Apr 20 18:29:12 2021 +0200

    core: add asynchronous notifications
    
    Adds support for asynchronous notifications from secure world to normal
    world. This allows a design with a top half and bottom half type of
    driver where the top half runs in secure interrupt context and a
    notifications tells normal world to schedule a yielding call to do the
    bottom half processing.

**Comment by jenswi-linaro** [comment]
Hi @tiger20081015,

The Linux patches are on their way upstream, planned for the 5.17 kernel. See the git pull request https://lore.kernel.org/all/20211213102359.GA1638682@jade/T/

**Comment by tiger20081015** [comment]
I see, many thanks!
