### ISSUE TITLE
How FIQ is handled after it's forwarded from ATF?

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#4584]
Hi,  I have one question for FIQ handling: 
Taking GICV3 for example, when a FIQ occurs in normal world and is forwarded to opteeos by ATF, how the FIQ handler is called? 

1. From the optee doc,  it looks like after switching to optee, since the FIQ is still active, gic will trigger a secure IRQ with the same interrupt number and cpu jumps to vbar_el1+irq_offset to handle it?  
![image](https://user-images.githubusercontent.com/35290009/116527097-e4e75680-a90c-11eb-9ce2-043eb0b2d156.png)

2. But in ATF,  before it forwards a FIQ to opteeos, it sets the return address to optee_vectors->fiq_entry.  And the comment mentioned this is a synchronously handling, so after switching to optee, the  optee_vectors->fiq_entry will handle the FIQ directly, no GIC irq will be trigged?
```
	 77 static uint64_t opteed_sel1_interrupt_handler(uint32_t id,                                        
	 78 >------->------->------->------->-------    uint32_t flags,                                       
	 79 >------->------->------->------->-------    void *handle,                                         
	 80 >------->------->------->------->-------    void *cookie)  
		…
	 99 >------ -cm_set_elr_el3(SECURE, (uint64_t)&optee_vectors->fiq_entry);      
	100 >-------cm_el1_sysregs_context_restore(SECURE);                                               
	101 >-------cm_set_next_eret_context(SECURE);                                                         
	102                                                                                                   
	103 >-------/*                                                                                        
	104 >------- * Tell the OPTEE that it has to handle an FIQ (synchronously).                           
	105 >------- * Also the instruction in normal world where the interrupt was                           
	106 >------- * generated is passed for debugging purposes. It is safe to                              
	107 >------- * retrieve this address from ELR_EL3 as the secure context will                          
	108 >------- * not take effect until el3_exit().                                                      
	109 >------- */                                                                                       
	110 >-------SMC_RET1(&optee_ctx->cpu_ctx, read_elr_el3());
```
I'm quite confused with one is the correct way. Can someone help to explain? Thanks.

**Comment by jenswi-linaro** [comment]
That part of the documentation seems to be a bit out of date. Currently are all secure interrupts occurring in normal world delivered via the Secure Monitor (Armv7) or the OP-TEE Dispatchers at EL-3 (Armv8) synchronously as described in the comment above. 

Here's the corresponding Armv7 code:
https://github.com/OP-TEE/optee_os/blob/0ae917ec14351993187bb8aa82c05c0180da3ee7/core/arch/arm/sm/sm_a32.S#L199-L246

**Comment by tiger20081015** [comment]
@jenswi-linaro , thanks for your answer.  Yet I still have some questions:
1.  when optee is handling the delivered FIQ from ATF or secure monitor, is FIQ masked and no FIQ can be triggered? Otherwise, per my understanding,  when SCR_NS changes from 1 to 0,  since the FIQ is still active,  GIC should re-trigger an interrupt in optee?
2.  If a non-secure interrupt occurring in secure world and forwarded to normal world, is it also handled synchronously? Or GIC re-triggers an IRQ interrupt in normal world? If it's the latter case, why makes the difference? 
Thanks!

**Comment by jenswi-linaro** [comment]
> 1. when optee is handling the delivered FIQ from ATF or secure monitor, is FIQ masked and no FIQ can be triggered? Otherwise, per my understanding,  when SCR_NS changes from 1 to 0,  since the FIQ is still active,  GIC should re-trigger an interrupt in optee?

A interrupts are masked when entering OP-TEE, so we've not getting another exception. However, if interrupts where to be unmasked we'd get an exception, but then we'd also trash our stack since we're using the same stack for synchronous entry and secure interrupt handling.

> 2. If a non-secure interrupt occurring in secure world and forwarded to normal world, is it also handled synchronously? Or GIC re-triggers an IRQ interrupt in normal world? If it's the latter case, why makes the difference?
>    Thanks!

In this case it's an asynchronous delivery handled by the normal world OS as any other non-secure interrupt.

**Comment by tiger20081015** [comment]
Thanks. So it seems the blow chart is also a bit old and should change "FIQ unmasked" to "FIQ masked" when optee "process received FIQ".  
![image](https://user-images.githubusercontent.com/35290009/116657677-6b5d7000-a9c1-11eb-97d3-8161f0087920.png)

**Comment by jenswi-linaro** [comment]
Yes, that's correct. The picture is from before we made the slight redesign to make room for ARMv8.

**Comment by tiger20081015** [comment]
"but then we'd also trash our stack since we're using the same stack for synchronous entry and secure interrupt handling".
Just curious, why not use different stacks for them so that the handling of forwarded FIQ can align with that of the asynchronous IRQ in normal world? With the change,  I think it can also reduce the coupling between ATF and secureos?

**Comment by jenswi-linaro** [comment]
I don't see what difference that would make except a bit more complicated and that we'd waste a few more kB of memory.
We still depend on a dispatcher in TF-A.

**Comment by tiger20081015** [comment]
@jenswi-linaro  Got it, thanks for your patient replies. No more questions.
