### ISSUE TITLE
how to use "tomcrypt" in TA?

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#4589]
I learned about OPTEE KeyMaster through the link below.
https://connect.linaro.org/resources/yvr18/sessions/yvr18-414/

I have a question while studying OPTEE KeyMaster on QEMU v7.
KeyMaster TA used the following two pseudo TAs.
-RNG_Entropy
-ASN1_Parser

I am going to change the two pseudo TAs to Early TA.
I understood pseudo TA and Early TA as follows through OPTEE documentations.

What they have in common is that they can run before Linux Kernel is loaded.
The difference is that pseudo TA can use optee_os functions directly, but early TA operates at user level.
Therefore, in Early TA, use GP Internal API or add optee_os system call. Or it seems possible to make a separate pseudo TA and use it.

RNG_Entropy in KeyMaster only has the function to update rng seed, but this function has the same function in system pta, so I used "PTA_SYSTEM_ADD_RNG_ENTROPY".

The problem I'm facing is ASN1_Parser. There is an error that cannot find the tomcrypt header file during the build process.
I searched optee_os/out/arm/export-ta_arm32, but the tomcrypt.h file did not exist.
Instead, I checked that the mbedtls header files existed.

ASN1_Parser is using tomcrypt for ASN1 processing, and I have looked at the document below to understand the crypto system in OPTEE.
https://optee.readthedocs.io/en/latest/architecture/crypto.html#overview

In this situation, my question is:
1) Why does OPTEE support two cryptos (tomcrypt, mbedtls)?
What I'm expecting seems to be using tomcrypt for crypto functions within optee_os. 
And mbedtls is used by many developers, so the api will be familiar. In other words, it seems to be provided for the convenience of TA developers.

2) Since there are only mbedtls in optee_os/out/arm/export-ta_arm32, can't tomcrypto be used when developing Ealry or REE TA?
If so, I think I have to change the parts of libtomcrypt used in pseudo TA (ASN1_Parser) to mbedtls.
For reference, I do not want to create a separate pseudo TA or modify optee_os.

BR,

**Comment by jforissier** [comment]
Hello @SangsubLim,

> I learned about OPTEE KeyMaster through the link below.
> https://connect.linaro.org/resources/yvr18/sessions/yvr18-414/
> 
> I have a question while studying OPTEE KeyMaster on QEMU v7.
> KeyMaster TA used the following two pseudo TAs.
> -RNG_Entropy
> -ASN1_Parser
> 
> I am going to change the two pseudo TAs to Early TA.
> I understood pseudo TA and Early TA as follows through OPTEE documentations.
> 
> What they have in common is that they can run before Linux Kernel is loaded.

Yes.

> The difference is that pseudo TA can use optee_os functions directly, but early TA operates at user level.

Yes.

> Therefore, in Early TA, use GP Internal API or add optee_os system call. Or it seems possible to make a separate pseudo TA and use it.

Yes.

> RNG_Entropy in KeyMaster only has the function to update rng seed, but this function has the same function in system pta, so I used "PTA_SYSTEM_ADD_RNG_ENTROPY".

OK.

> The problem I'm facing is ASN1_Parser. There is an error that cannot find the tomcrypt header file during the build process.
> I searched optee_os/out/arm/export-ta_arm32, but the tomcrypt.h file did not exist.
> Instead, I checked that the mbedtls header files existed.

Correct. User TAs can use MBed TLS but not LibTomCrypt.
 
> ASN1_Parser is using tomcrypt for ASN1 processing, and I have looked at the document below to understand the crypto system in OPTEE.
> https://optee.readthedocs.io/en/latest/architecture/crypto.html#overview
> 
> In this situation, my question is:
> 
>     1. Why does OPTEE support two cryptos (tomcrypt, mbedtls)?

For historical reasons. Initially, LibTomCrypt was the only crypto library in OP-TEE. Then MBed TLS was added for TAs, and some time after the possibility was given to use it also inside the OS (TEE core) for people who prefer to use only one library.

>        What I'm expecting seems to be using tomcrypt for crypto functions within optee_os.

`optee_os`  uses LibTomCrypt by default, but it can be configured to use MBed TLS instead with `CFG_CRYPTOLIB_NAME=mbedtls CFG_CRYPTOLIB_DIR=lib/libmbedtls`.

>        And mbedtls is used by many developers, so the api will be familiar. In other words, it seems to be provided for the convenience of TA developers.

Right.

>     2. Since there are only mbedtls in optee_os/out/arm/export-ta_arm32, can't tomcrypto be used when developing Ealry or REE TA?

Not at the moment.

>        If so, I think I have to change the parts of libtomcrypt used in pseudo TA (ASN1_Parser) to mbedtls.

Yes, it is one option. The other option would be to modify optee_os to build LibTomCrypt for user space too, like is done for MBed TLS. It shouldn't be too hard I think, but given that MBed TLS is certainly more popular than LibTomCrypt as you said, there is no reason to do it unless someone asks for it.

>        For reference, I do not want to create a separate pseudo TA or modify optee_os.

OK, then using MBed TLS in your TA for everything that is not provided by the GlobalPlatform APIs seems to be the only valid choice.

**Comment by vchong** [comment]
> https://connect.linaro.org/resources/yvr18/sessions/yvr18-414

This presentation is relatively old.

> I have a question while studying OPTEE KeyMaster on QEMU v7.

The KeyMaster TA isn't really written to work with QEMU. It only works on the HiKey960 AOSP build currently. Are you writing your own normal world client application on QEMU to test the KeyMaster TA?

> -RNG_Entropy

This has been replaced with the System pTA.

> -ASN1_Parser

This has been replaced with libmbedtls in the KeyMaster TA itself.

> I am going to change the two pseudo TAs to Early TA.

What's your objective for doing so? If you're trying to learn more about Early or pseudo TA, the KeyMaster TA isn't really a suitable choice.

**Comment by SangsubLim** [comment]
Hello @jforissier,

Thank you all the time for your comments.
This is of great help to newbies like me.


Hello @vchong,
I have seen several presentations on Linaro connect, among which I am interested in keymaster and am working on it.
For reference, I downloaded the source code through the URL below.
$ git clone https://github.com/linaro-swg/optee_android_manifest -b lcr-ref-hikey
$ cd optee_android_manifest
$ ./sync.sh -v p -bm pinned-manifest-stable_yvr18.xml

After that, I checked the keymaster contents in device/linaro/kmgk.

Can you please tell me where to look to see what you said above?
To ask a more specific question, I would like to see the code of Keymaster combined with the ANS1 parser.

As you said, this was developed by hikey. But I only have rpi3, imx6q, and qemu. I tried configuring the android+optee environment on these chipsets but failed due to my lack of knowledge.

So, first of all, I want to learn from the keymaster TA on QEMU. After that, we plan to configure the development environment on the normal world side. (Purchase hikey or port android+optee, etc.)

In your opinion I learn a lot. Thank.In your opinion I learn a lot. Thank.

**Comment by vchong** [comment]
> $ git clone https://github.com/linaro-swg/optee_android_manifest -b lcr-ref-hikey
> $ cd optee_android_manifest
> $ ./sync.sh -v p -bm pinned-manifest-stable_yvr18.xml

Do this instead:
```
https://github.com/linaro-swg/optee_android_manifest -b 3.12.0
cd optee_android_manifest
./sync-p-hikey960.sh
./build-p-hikey960.sh
```

> After that, I checked the keymaster contents in device/linaro/kmgk.
> 
> Can you please tell me where to look to see what you said above?
> To ask a more specific question, I would like to see the code of Keymaster combined with the ANS1 parser.

After `sync-p-hikey960.sh` above, if you check `device/linaro/kmgk` again, you will be able to see in the source code usage of `PTA_SYSTEM_ADD_RNG_ENTROPY`. You can also refer to `mbedtls_proxy.c` for ASN1 parsing code using libmbedtls APIs. The ASN1 pTA isn't used anymore.

> As you said, this was developed by hikey. But I only have rpi3, imx6q, and qemu. I tried configuring the android+optee environment on these chipsets but failed due to my lack of knowledge.

Currently there is only AOSP + OP-TEE build on the HiKey960 platform. The other platforms don't even have an AOSP build, at least not under https://github.com/OP-TEE or https://github.com/linaro-swg. How are you configuring the android+optee environment on these chipsets?

> So, first of all, I want to learn from the keymaster TA on QEMU. After that, we plan to configure the development environment on the normal world side. (Purchase hikey or port android+optee, etc.)

As mentioned above, there's no AOSP + OP-TEE build for QEMU. The hikey boards are EOL and probably impossible to purchase anymore online. This is a dilemma we're currently facing as well - trying to find the next suitable replacement board.

If it's just for learning, I supposed you can still build the keymaster TA for QEMU, and write your own normal world client application to invoke the commands for the TA, but it's not trivial to figure out what data and information need to be sent to the TA for proper processing. You can also, as you said, port android+optee to other platforms, but this is not trivial either for newbies.

If you're just looking to learn about some secure key services/management framework, an alternative is PKCS11 that is currently being integrated into OP-TEE. This doesn't require AOSP so you can run it on most, if not all, the platforms available here. The documentation and code readability are a lot better too since it's dealing with a much smaller codebase compared to AOSP. For more details, see https://connect.linaro.org/resources/lvc21/lvc21-215 for a start.
 
> In your opinion I learn a lot. Thank.

You're welcome. Not sure how helpful this is but hopefully you still get something out of it.

**Comment by SangsubLim** [comment]
Hello @vchong,

Thank you for sharing your valuable content. It's helping me a lot.
Source download and build have been completed using the URL information you gave me.

I have an additional question.
As far as I know, android keymaster is closely related to AVB (Android verified boot).
In the case of ANS1 Parser TA that I saw before, it was written as a pseudo TA, and the attestation function inside it seemed to be related to AVB.
In other words, during the booting process, I understood that the bootloader calls ANS1 Parser TA to perform a verified boot.
And I confirmed that hikey board uses bootloader as edk2.
For reference, I've only used uboot. I'm new to edk2 now :)

The keymaster you worked on doesn't seem to be a psuedo TA.
Are you operating with Early TA? This is because I think it will be accessible from the Bootloader.

I can't debug because I don't have a hikey board, but I want to check the code and get a rough flow. 
Thank you for your answer.

And the content of PKCS #11 you gave me is very interesting. When I finish learning about Keymaster and AVB, I will study that part as well.
Thank you for sharing good information. 

BR,

**Comment by vchong** [comment]
> Thank you for sharing your valuable content. It's helping me a lot.
> Source download and build have been completed using the URL information you gave me.

You're welcome. Good to know.

> I have an additional question.
> As far as I know, android keymaster is closely related to AVB (Android verified boot).
> In the case of ANS1 Parser TA that I saw before, it was written as a pseudo TA, and the attestation function inside it seemed to be related to AVB.
> In other words, during the booting process, I understood that the bootloader calls ANS1 Parser TA to perform a verified boot.
> And I confirmed that hikey board uses bootloader as edk2.
> For reference, I've only used uboot. I'm new to edk2 now :)
> 
> The keymaster you worked on doesn't seem to be a psuedo TA.
> Are you operating with Early TA? This is because I think it will be accessible from the Bootloader.

The ASN1 Parser pTA isn't used for AVB. You can find the AVB Early TA here: https://github.com/OP-TEE/optee_os/tree/master/ta/avb. Uboot calls this AVB TA. Edk2 doesn't I think, at least not on the hikey* platforms. Afaik we don't do AVB on hikey*.

> Could you tell me where is the part of edk2 calling keymaster?

Edk2 doesn't. The keymaster TA is only 'called' when the AOSP keymaster service starts as part of the kernel init process.

> And this keymaster you worked on seems to be done with vts. Right?

Sorry, not sure what you mean. We do test it with the VtsHalKeymasterV3_0TargetTest test suite if that's what you're referring to.

**Comment by SangsubLim** [comment]
Thanks for your sincere answer.

**Comment by SangsubLim** [comment]
@vchong,

I am analyzing the contents of the optee keymaster you gave me.
After I've finished analyzing this, I think I might be able to use it in a project within my company.
I'm checking the SW license for what you've been working on.
When I check the code, it seems to be Apache 2.0.
  And what action should I take if I use some of your work?

As far as I know, in the case of Apache 2.0, it is only necessary to make sure that it is an Apache license and a notice to the original author (linaro).
When I use your code, do I have to separately notify you of changes, etc.?

It seems that the referenced contents are the host contents related to optee_keymaster and the files in the TA.

Thanks a lot for your help.

**Comment by vchong** [comment]
@SangsubLim Sorry but it seems best for you to consult with your legal department since we're not really in a position here to provide advice in matters related to the law.
