### ISSUE TITLE
yocto zeus branch toolchains compile optee_example code ,ModuleNotFoundError: No module named 'Crypto' 

### ISSUE THREAD

**Issue by gitgonewithwind** [OP-TEE/optee_os#4590]
Hi I play the maaxboard and iwave in yocto zeus branch, there is the same error. (maaxbaord sumo branch worked well,but zeus branch not work)
a few months ago , I posted the same issue here: https://github.com/OP-TEE/optee_os/issues/4374
I though I found the solutions, and I closed it. 
but actually, I did not find it. I play maaxboard yocto zeus branck , the issue is still there. and I recall my iwave board, the issue is still here.
so I thought I was wrong before. the issue is still there.
any help? Thank you.

--

 I am playing imx8qm -iwave  and maaxboard board for yocto zeus branch

I use yocto toolchains to cross compile optee_example code,

error happened:(maaxbaord sumo branch worked well).

from Crypto.Signature import PKCS1_v1_5

ModuleNotFoundError: No module named 'Crypto'

but I find in toolchain folder, the Crypto folder is there: 

./sysroots/aarch64-poky-linux/usr/lib/python3.7/site-packages/Crypto

It seems the compiler can not find it ?

I have added :

IMAGE_INSTALL_append +=" python3-pycryptodome " in local.conf

any help?

About 2 year ago,I posted a similar question #3441 but that was in yocto bitbake process in early, could not generate the yocto image.
Today I play another board, I can build the image and the toolchain, the new issue is the toolchain compiler can not find the 'Crypto'

Thank you.

error:

aarch64-poky-linux-gcc  -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/opt/fsl-imx-xwayland/5.4-zeus/sysroots/aarch64-poky-linux -o optee_example_aes main.o -lteec -L/opt/fsl-imx-xwayland/5.4-zeus/sysroots/aarch64-poky-linux/usr//lib

make[1]: Leaving directory '/opt/oe/iw/iw-5.4.24/optee_examples/aes/host'

make -C ta CROSS_COMPILE="aarch64-poky-linux-" LDFLAGS=""

make[1]: Entering directory '/opt/oe/iw/iw-5.4.24/optee_examples/aes/ta'

  CC      aes_ta.o

  CC      user_ta_header.o

  CPP     ta.lds

  LD      5dbac793-f574-4871-8ad3-04331ec17f24.elf

  OBJDUMP 5dbac793-f574-4871-8ad3-04331ec17f24.dmp

  OBJCOPY 5dbac793-f574-4871-8ad3-04331ec17f24.stripped.elf

  SIGN    5dbac793-f574-4871-8ad3-04331ec17f24.ta

Traceback (most recent call last):

  File "/usr/local/optee/sysroots/aarch64-poky-linux/usr/include/optee/export-user_ta_arm64//scripts/sign.py", line 78, in

    main()

  File "/usr/local/optee/sysroots/aarch64-poky-linux/usr/include/optee/export-user_ta_arm64//scripts/sign.py", line 31, in main

    from Crypto.Signature import PKCS1_v1_5

ModuleNotFoundError: No module named 'Crypto'

/usr/local/optee/sysroots/aarch64-poky-linux/usr/include/optee/export-user_ta_arm64/mk/link.mk:60: recipe for target '5dbac793-f574-4871-8ad3-04331ec17f24.ta' failed

make[1]: *** [5dbac793-f574-4871-8ad3-04331ec17f24.ta] Error 1

make[1]: Leaving directory '/opt/oe/iw/iw-5.4.24/optee_examples/aes/ta'

Makefile:9: recipe for target 'all' failed

make: *** [all] Error 2

**Comment by lorc** [comment]
Hi,

we had similar problem. I fixed this by providing pycryptodome for optee recipe:

https://github.com/xen-troops/meta-xt-images/commit/22bc4e2694818e1779fa2eb7312914d81dd8ae70

You can't use this patch as is, because it is made for our internal build system. But at least it should guide you.

**Comment by gitgonewithwind** [comment]
@lorc 
thank you very much.  I checked my optee-imx/optee-os.imx.inc, actually, there is no DEPENDS_append = " python3-pycryptodome-native python3-pyelftools-native"

I thought it had. I did not read it carefully

let me add it and test

-
# Copyright (C) 2019-2020 NXP

require recipes-security/optee-imx/optee-os_3.2.0.imx.bb

LIC_FILES_CHKSUM = "file://LICENSE;md5=c1f21c4f72f372ef38a5a4aee55ec173"

inherit python3native
DEPENDS_remove = "python-pycrypto-native"
DEPENDS_append = " python3-pycrypto-native python3-pyelftools-native"

# The recipe uses Machine overrides variable
# to select the suitable OP-TEE Platform Flavor.
# The reason is that from an OP-TEE point of view there
# are no differences between for example a imx8mnddr4evk
# and a imx8mnevk MACHINE. In this example, the PLATFORM_FLAVOR
# defined is imx8mnevk, the other MACHINE derivatives
# are just using the original one.
PLATFORM_FLAVOR_mx8mn           = "mx8mnevk"
PLATFORM_FLAVOR_mx8qxp          = "mx8qxpmek"
PLATFORM_FLAVOR_mx8mp           = "mx8mpevk"
PLATFORM_FLAVOR_mx8dx           = "mx8dxmek"
PLATFORM_FLAVOR_mx8dxl          = "mx8dxlevk"
PLATFORM_FLAVOR_mx8phantomdxl   = "mx8qxpmek"

OPTEE_CORE_LOG_LEVEL ?= "1"
OPTEE_TA_LOG_LEVEL ?= "0"

EXTRA_OEMAKE_remove = "NOWERROR=1 \
                       CFG_SECURE_DATA_PATH=y \
                       CFG_TEE_SDP_MEM_BASE=0xCC000000 \
                       CFG_TEE_SDP_MEM_SIZE=0x02000000 \
                       CFG_TEE_SDP_NONCACHE=y \
                      "

EXTRA_OEMAKE += "CFG_WERROR=y \
                       CFG_TEE_CORE_LOG_LEVEL=${OPTEE_CORE_LOG_LEVEL} \
                       CFG_TEE_TA_LOG_LEVEL=${OPTEE_TA_LOG_LEVEL} \
                      "

do_compile () {
    unset LDFLAGS
    export CFLAGS="${CFLAGS} --sysroot=${STAGING_DIR_HOST}"
    oe_runmake -C ${S} all
}

**Comment by gitgonewithwind** [comment]
after I added  it in optee_os recipe, could not pass the bitbake the image, the error seems can not sign ta ?
 
inherit python3native
DEPENDS_remove = "python-pycrypto-native"
#DEPENDS_append = " python3-pycrypto-native python3-pyelftools-native"
DEPENDS_append = " python3-pycryptodome-native python3-pyelftools-native"


bitbake lite-image
Loading cache: 100% |########################################################################################################################################################################################################| Time: 0:00:01
Loaded 4677 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.44.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "maaxboard-ddr4-2g-sdcard"
DISTRO               = "fsl-imx-wayland-lite"
DISTRO_VERSION       = "5.4-zeus"
TUNE_FEATURES        = "aarch64 cortexa53 crc crypto"
TARGET_FPU           = ""
meta                 
meta-poky            = "HEAD:cba967414370e195d109353e51510bd829aa86c3"
meta-oe              
meta-multimedia      
meta-python          = "HEAD:9e60d30669a2ad0598e9abf0cd15ee06b523986b"
meta-freescale       = "HEAD:c2a0d924f6200eea1fb1d1b61e7420ea5da2f8fb"
meta-freescale-3rdparty = "HEAD:dbcc686f52c3c84db8cb86aa8973a4e373651b98"
meta-freescale-distro = "HEAD:ca27d12e4964d1336e662bcc60184bbff526c857"
meta-maaxboard       = "zeus:4acadd49b4458ed8566991fdb37ab932e93c58b4"
meta-bsp             
meta-sdk             
meta-ml              = "HEAD:752a48385974cbc458c1fcc2e0c8c3f47730914c"
meta-browser         = "HEAD:5f365ef0f842ba4651efe88787cf9c63bc8b6cb3"
meta-rust            = "HEAD:a012a1027defe28495f06ed522a7a82bdd59a610"
meta-gnome           
meta-networking      
meta-filesystems     = "HEAD:9e60d30669a2ad0598e9abf0cd15ee06b523986b"
meta-qt5             = "HEAD:b8bcf8cb576d072f435a0177375e54424f67d1c9"
meta-python2         = "HEAD:231c3d74cfcf734c3415e86ea8dd97f73ddced9d"
common               
meta-touch           = "<unknown>:<unknown>"

WARNING: /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/sources/meta-imx/meta-bsp/recipes-kernel/linux/linux-imx_5.4.bb:do_compile is tainted from a forced run                                                                | ETA:  0:00:03
Initialising tasks: 100% |###################################################################################################################################################################################################| Time: 0:00:07
Sstate summary: Wanted 20 Found 1 Missed 19 Current 2685 (5% match, 99% complete)
NOTE: Executing Tasks
NOTE: Setscene tasks completed
ERROR: optee-os-3.7.0.imx-r0 do_compile: oe_runmake failed
ERROR: optee-os-3.7.0.imx-r0 do_compile: Execution of '/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/temp/run.do_compile.2539' failed with exit code 1:
make: Entering directory '/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/git'
  CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/conf.mk
  CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/conf.cmake
  CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/export-ta_arm64/mk/conf.mk
  CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/include/generated/conf.h
  GEN     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/core/unpaged_entries.txt
  GEN     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/core/init_entries.txt
  SIGN    /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta
Traceback (most recent call last):
  File "scripts/sign.py", line 234, in <module>
    main()
  File "scripts/sign.py", line 149, in main
    sig_len = ceil_div(key.size() + 1, 8)
TypeError: size() takes 0 positional arguments but 1 was given
ta/arch/arm/link.mk:83: recipe for target '/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta' failed
make: *** [/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta] Error 1
make: Leaving directory '/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/git'
WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/temp/log.do_compile.2539
Log data follows:
| DEBUG: Executing python function autotools_aclocals
| DEBUG: SITE files ['endian-little', 'bit-64', 'arm-common', 'arm-64', 'common-linux', 'common-glibc', 'aarch64-linux', 'common']
| DEBUG: Python function autotools_aclocals finished
| DEBUG: Executing shell function do_compile
| NOTE: make -j 8 PLATFORM=imx PLATFORM_FLAVOR=mx8mqevk CROSS_COMPILE=aarch64-poky-linux- CROSS_COMPILE64=aarch64-poky-linux- LDFLAGS= O=/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk CFG_WERROR=y CFG_TEE_CORE_LOG_LEVEL=1 CFG_TEE_TA_LOG_LEVEL=0 -C /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/git all
| make: Entering directory '/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/git'
|   CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/conf.mk
|   CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/conf.cmake
|   CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/export-ta_arm64/mk/conf.mk
|   CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/include/generated/conf.h
|   GEN     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/core/unpaged_entries.txt
|   GEN     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/core/init_entries.txt
|   SIGN    /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta
| Traceback (most recent call last):
|   File "scripts/sign.py", line 234, in <module>
|     main()
|   File "scripts/sign.py", line 149, in main
|     sig_len = ceil_div(key.size() + 1, 8)
| TypeError: size() takes 0 positional arguments but 1 was given
| ta/arch/arm/link.mk:83: recipe for target '/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta' failed
| make: *** [/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta] Error 1
| make: Leaving directory '/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/git'
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/temp/run.do_compile.2539' failed with exit code 1:
| make: Entering directory '/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/git'
|   CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/conf.mk
|   CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/conf.cmake
|   CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/export-ta_arm64/mk/conf.mk
|   CHK     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/include/generated/conf.h
|   GEN     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/core/unpaged_entries.txt
|   GEN     /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/core/init_entries.txt
|   SIGN    /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta
| Traceback (most recent call last):
|   File "scripts/sign.py", line 234, in <module>
|     main()
|   File "scripts/sign.py", line 149, in main
|     sig_len = ceil_div(key.size() + 1, 8)
| TypeError: size() takes 0 positional arguments but 1 was given
| ta/arch/arm/link.mk:83: recipe for target '/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta' failed
| make: *** [/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/build.mx8mqevk/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta] Error 1
| make: Leaving directory '/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/work/maaxboard_ddr4_2g_sdcard-poky-linux/optee-os/3.7.0.imx-r0/git'
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/sources/meta-imx/meta-bsp/recipes-security/optee-imx/optee-os_3.7.0.imx.bb:do_compile) failed with exit code '1'

**Comment by lorc** [comment]
Oh, I just noticed that you are using OP-TEE 3.7. It is quite old version and I believe it used Python2 back then. So you probably would need python2 version of those packages. Also, on some older OP-TEE versions path to python was hardcoded, so it used host python. That means that you maybe need to install required python packages to your system, rather than modify yocto recipe.

**Comment by gitgonewithwind** [comment]
@lorc 
Thank you very much. 
finally, I have found the solutions. I did  it 2 years ago for imx7 board. I remember again.
do not need to modify the recipe.
the toolchain does not include the Crypto package
just manually copy Crypto to toolchain(I do not know how to modify somewhere in the compilation process to copy directly to make it)


sudo cp -r /home/rnd2/work/maaxboard/zeus/imx-yocto-bsp/maaxboard/build/tmp/sysroots-components/x86_64/python3-pycrypto-native/usr/lib/python3.7/site-packages/Crypto  /opt/fsl-imx-wayland-lite/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/lib/python3.7/site-packages/.
