### ISSUE TITLE
RSA key generate with LibTomcrypt failed if public exponent is more than 8 bytes

### ISSUE THREAD

**Issue by cneveux** [OP-TEE/optee_os#4591]
A RSA key can be generated by specifying a public exponent e between 65537 (included) and 2^256 (excluded).
It's look like that libtomcrypt is limiting the public exponent to long value (65737 upto 2^64 - 1)

In case a RSA public exponent is more than a long integer, the libtomcrypt `rsa_make_key()` function get a public exponent value corresponding to the most significant last long integer.
If this last long integer is odd, RSA key generation is returning OK but in logic RSA key generated is wrong because the public exponent used to generate the key is wrong.
Whereas if the last long integer is even, the `rsa_make_key()()` function returns a bad parameter error.

I didn't check if mdebTLS has the same limitation.

Ex with libtomcrypt:
Set e[11]={0x10, 0xFF, 0x07, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05}
`rsa_make_key()` will get e=4351 ("{0x10, 0xFF}"} as parameter and generate a RSA with success.

Set e[11]={0x10, 0x02, 0x07, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05}
`rsa_make_key()` will get e=4098 ("{0x10, 0x02}"} as parameter and returns bad parameter error.

Because of libtomcrypt limitation, the RSa key generate must return an error if public exponent is more than 64 bits.

What I noticed is that function `get_int()` in the core/lib/libtomcrypt/mpi_desc.c is not correct as well because it doesn't check if the bignumber is more than 64 bits. If this is the case, it return the most significant long of the bignumber

**Comment by jforissier** [comment]
Hello @cneveux,

Thanks for reporting this.

>  It's look like that libtomcrypt is limiting the public exponent to long value (65737 upto 2^64 - 1)

Given that `e` is of type `long` in `rsa_make_key()`:
```C
int rsa_make_key(prng_state *prng, int wprng, int size, long e, rsa_key *key);
```
...I suspect that the limitation is 2^31 - 1 with 32-bit builds, isn't it?

> Because of libtomcrypt limitation, the RSa key generate must return an error if public exponent is more than 64 bits.

I agree (well, it seems the condition is if the public exponent does not fit in a `long int` actually).

> I didn't check if mdebTLS has the same limitation.

If you have a test case at hand, it is easy to test, just add `CFG_CRYPTOLIB_NAME=mbedtls CFG_CRYPTOLIB_DIR=lib/libmbedtls` to the build flags.

**Comment by cneveux** [comment]
Hello @jforissier 

You're right, I missed to say that I tested on 64 bits platform (qemuv8).
So yes, in general `long` variable are 32 bits on 32 bits architecture. Hence LibTomcrypt limitation is depending of the `sizeof(long)`

I checked the mbedTLS function `crypto_acipher_gen_rsa_key()` implementation in lib/libmbedtls/core/rsa.c file and:
- regardless the core architecture 32 or 64 bits, the public exponent is limited to 32 bits only.
- in case a public exponent given in keypair parameter `e` is more than 4 bytes, the `mbedtls_mpi_write_binary()` function used to get the unsigned 32 bits value of `e` bignumber return a value 0. Hence the function `mbedtls_rsa_gen_key()` is called with `e=0` and this function return MBEDTLS_ERR_RSA_BAD_INPUT_DATA.

In both cases the public exponent "overflow" must be verified before converting the bignumber to a long or 32 bits unsigned int. The question is how to know that this error is due to library limitation.

**Comment by jforissier** [comment]
> The question is how to know that this error is due to library limitation.

What do you mean? Do you mean it's not good for the TA to receive TEE_ERROR_BAD_PARAMETERS in this case? That would seem adequate to me. Assuming it is:

- The MBed TLS implementation looks fine since MBEDTLS_ERR_RSA_BAD_INPUT_DATA gets translated to TEE_ERROR_BAD_PARAMETERS
- As for the LibTomCrypt variant, how about this:
  ```diff
  diff --git a/core/lib/libtomcrypt/rsa.c b/core/lib/libtomcrypt/rsa.c
  index 1199d1fb..b443deee 100644
  --- a/core/lib/libtomcrypt/rsa.c
  +++ b/core/lib/libtomcrypt/rsa.c
  @@ -153,6 +153,8 @@ TEE_Result crypto_acipher_gen_rsa_key(struct rsa_keypair *key, size_t key_size)
   	long e;
   
   	/* get the public exponent */
  +	if (mp_count_bits(key->e) > (int)(8 * sizeof(e) - 1))
  +		return TEE_ERROR_BAD_PARAMETERS;
   	e = mp_get_int(key->e);
   
   	/* Generate a temporary RSA key */
  ```

**Comment by cneveux** [comment]
Getting a TEE_ERROR_BAD_PARAMETERS because of a library implementation limitation compared to the RSA standard for me is not a good indication. In one case we can get a success with tomcrypt and not with mbedtls for the same public exponent. And in the case of a driver like the CAAM, we can respect the RSA standard with a public exponent upto 256 bits.

What is the Global Platform recommendation in this case? 
Do we have to have the TA knowing the limitation using the CFG_CRYPTOLIB_NAME as reference? 
The application is the requester of the RSA key generation giving a public exponent and the application doesn't know what library or driver is doing the RSA key generation.

**Comment by jforissier** [comment]
> Getting a TEE_ERROR_BAD_PARAMETERS because of a library implementation limitation compared to the RSA standard for me is not a good indication. In one case we can get a success with tomcrypt and not with mbedtls for the same public exponent. And in the case of a driver like the CAAM, we can respect the RSA standard with a public exponent upto 256 bits.

I agree.

> What is the Global Platform recommendation in this case?

As per the spec, only three things are possible: return TEE_SUCCESS, return TEE_ERROR_BAD_PARAMETER, or panic the TA.

> Do we have to have the TA knowing the limitation using the CFG_CRYPTOLIB_NAME as reference?

No, I would not recommend that.

> The application is the requester of the RSA key generation giving a public exponent and the application doesn't know what library or driver is doing the RSA key generation.

I agree.

The good news is, it seems trivial to modify LibTomCrypt to support larger exponents: pass `e` as a big number (`void *` type) and use it directly instead of `tmp3`. See https://github.com/OP-TEE/optee_os/blob/3.13.0/core/lib/libtomcrypt/src/pk/rsa/rsa_make_key.c#L50. We could introduce a new function `make_rsa_key2()` for example.

Would you like to try that and propose the change in upstream LTC to get some feedback?

**Comment by cneveux** [comment]
@jforissier 

Good, I'll try to proposed a patch to LTC quickly.
I'll follow up on this issue to add the result of LTC patch.

**Comment by cneveux** [comment]
Libtomcrypt patch has been merged https://github.com/libtom/libtomcrypt/pull/569#event-4844300952

**Comment by jforissier** [comment]
@cneveux great, I'll cherry-pick the patch into our LTC import branch and into master today (hopefully).

**Comment by jforissier** [comment]
> @cneveux great, I'll cherry-pick the patch into our LTC import branch and into master today (hopefully).

Done.

**Comment by cneveux** [comment]
@jforissier, good, thanks you. I'll submit optee patch to use this new API

**Comment by cneveux** [comment]
I'm closing the issue as PR #4674 merged fix libtomcrypt RSA key generation
