### ISSUE TITLE
How to modify max available memory for TEE_Malloc?

### ISSUE THREAD

**Issue by scotthuang1989** [OP-TEE/optee_os#4592]
I need  create a memmory buffer to store hash value (32 bytes) in memory. So I cal TEE_Malloc to allocate memory;  `TEE_Malloc `will return  error if  I try to allocate memory for 1500 hash value `TEE_Malloc(1500*32)`, If I call  `TEE_Malloc(1500*32)` many times, it will return error after several times . If I only allocate memory for 1000 hash value `TEE_Malloc(1000*32)`, it will return success.

So I guess there is a limitation on how many memory I can allocate.  Can I modify this limitation?

**Comment by vchong** [comment]
Try increasing `TA_DATA_SIZE` in `user_ta_header_defines.h`. [1]

[1] https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html?highlight=ta_data_size#heap-size

**Comment by scotthuang1989** [comment]
@vchong   TA_DATA_SIZE is 32*1024 in all the TA examples in  [optee_examples](https://github.com/linaro-swg/optee_examples), I change it to  (32 * 102400), which is 100 times.  TA is still work fine!.  What is the limitation of this value?  if I change to 32 * 102400 (or even bigger),  will it cause any bugs?

**Comment by vchong** [comment]
> @vchong TA_DATA_SIZE is 32*1024 in all the TA examples in [optee_examples](https://github.com/linaro-swg/optee_examples), I change it to (32 * 102400), which is 100 times. TA is still work fine!. What is the limitation of this value? if I change to 32 * 102400 (or even bigger), will it cause any bugs?

It's platform specific and depends on how much is allocated for TA RAM. You might be able to figure it out from the `platform_config.h` file for your platform.

**Comment by jforissier** [comment]
> @vchong TA_DATA_SIZE is 32*1024 in all the TA examples in [optee_examples](https://github.com/linaro-swg/optee_examples), I change it to (32 * 102400), which is 100 times. TA is still work fine!.

Are you sure your TA was rebuilt successfully and actually used in your test? :open_mouth:

**Comment by scotthuang1989** [comment]
yes. memory allcoation is successful. I set the allocated memory to zero and  everything is ok.

**Comment by scotthuang1989** [comment]
> > @vchong TA_DATA_SIZE is 32*1024 in all the TA examples in [optee_examples](https://github.com/linaro-swg/optee_examples), I change it to (32 * 102400), which is 100 times. TA is still work fine!. What is the limitation of this value? if I change to 32 * 102400 (or even bigger), will it cause any bugs?
> 
> It's platform specific and depends on how much is allocated for TA RAM. You might be able to figure it out from the `platform_config.h` file for your platform.

I check `platform_config.h`,  here are some relevant config:

`#define DRAM0_BASE		0x40000000

#define DRAM0_SIZE		0x80000000`

**Comment by vchong** [comment]
> > > @vchong TA_DATA_SIZE is 32*1024 in all the TA examples in [optee_examples](https://github.com/linaro-swg/optee_examples), I change it to (32 * 102400), which is 100 times. TA is still work fine!. What is the limitation of this value? if I change to 32 * 102400 (or even bigger), will it cause any bugs?
> > 
> > 
> > It's platform specific and depends on how much is allocated for TA RAM. You might be able to figure it out from the `platform_config.h` file for your platform.
> 
> I check `platform_config.h`, here are some relevant config:
> 
> `#define DRAM0_BASE 0x40000000
> 
> #define DRAM0_SIZE 0x80000000`

Is this mediatek? Can't really tell just from the `platform_config.h`. The platform is orphaned too, i.e. no longer under maintenance. Maybe check your boot logs for something like below:

```
D/TC:0   add_phys_mem:565 TEE_SHMEM_START type NSEC_SHM 0x3ee00000 size 0x00200000
D/TC:0   add_phys_mem:565 TA_RAM_START type TA_RAM 0x3f200000 size 0x00e00000
D/TC:0   add_phys_mem:565 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x3f06d000 size 0x00193000
D/TC:0   add_phys_mem:565 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x3f000000 size 0x0006d000
D/TC:0   add_phys_mem:565 ROUNDDOWN(0xFFF32000, CORE_MMU_PGDIR_SIZE) type IO_NSEC 0xffe00000 size 0x00200000
```

**Comment by scotthuang1989** [comment]
> > > > @vchong TA_DATA_SIZE is 32*1024 in all the TA examples in [optee_examples](https://github.com/linaro-swg/optee_examples), I change it to (32 * 102400), which is 100 times. TA is still work fine!. What is the limitation of this value? if I change to 32 * 102400 (or even bigger), will it cause any bugs?
> > > 
> > > 
> > > It's platform specific and depends on how much is allocated for TA RAM. You might be able to figure it out from the `platform_config.h` file for your platform.
> > 
> > 
> > I check `platform_config.h`, here are some relevant config:
> > `#define DRAM0_BASE 0x40000000
> > #define DRAM0_SIZE 0x80000000`
> 
> Is this mediatek? Can't really tell just from the `platform_config.h`. The platform is orphaned too, i.e. no longer under maintenance. Maybe check your boot logs for something like below:
> 
> ```
> D/TC:0   add_phys_mem:565 TEE_SHMEM_START type NSEC_SHM 0x3ee00000 size 0x00200000
> D/TC:0   add_phys_mem:565 TA_RAM_START type TA_RAM 0x3f200000 size 0x00e00000
> D/TC:0   add_phys_mem:565 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x3f06d000 size 0x00193000
> D/TC:0   add_phys_mem:565 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x3f000000 size 0x0006d000
> D/TC:0   add_phys_mem:565 ROUNDDOWN(0xFFF32000, CORE_MMU_PGDIR_SIZE) type IO_NSEC 0xffe00000 size 0x00200000
> ```

 @vchong here is the log.

> D/TC:0 add_phys_mem:521 TEE_SHMEM_START type NSEC_SHM 0xfd200000 size 0x00c00000
> D/TC:0 add_phys_mem:521 TA_RAM_START type TA_RAM 0xfc200000 size 0x01000000
> D/TC:0 add_phys_mem:521 VCORE_UNPG_RW_PA type TEE_RAM_RW 0xfc04c000 size 0x001b4000
> D/TC:0 add_phys_mem:521 VCORE_UNPG_RX_PA type TEE_RAM_RX 0xfc000000 size 0x0004c000
> D/TC:0 add_phys_mem:521 GIC_BASE type IO_SEC 0x29800000 size 0x00600000
> D/TC:0 add_phys_mem:521 TZC1_BASE type IO_SEC 0x28200000 size 0x00200000
> D/TC:0 add_phys_mem:521 TZC0_BASE type IO_SEC 0x28200000 size 0x00200000
> D/TC:0 add_phys_mem:534 Physical mem map overlaps 0x28200000
> D/TC:0 add_phys_mem:521 CONSOLE_UART_BASE type IO_NSEC 0x28000000 size 0x00200000
> D/TC:0 add_phys_mem:521 SMX_DMA_BASE type IO_SEC 0x29800000 size 0x00200000
> D/TC:0 add_phys_mem:534 Physical mem map overlaps 0x29800000
> D/TC:0 add_phys_mem:521 SMX_BASE_ADDR type IO_SEC 0x28200000 size 0x00200000
> D/TC:0 add_phys_mem:534 Physical mem map overlaps 0x28200000
