### ISSUE TITLE
rk3399 u-boot build failed when building SPL

### ISSUE THREAD

**Issue by janoslim** [OP-TEE/optee_os#4595]
Hello, 

I tried to build op-tee for rk3399(rock960), especially u-boot,
when I run make, I encountered error below, 

```
...
  CC      spl/common/spl/spl_mmc.o
  CC      spl/common/spl/spl_atf.o
  AS      spl/common/spl/spl_optee.o
./arch/arm/include/asm/unified.h: Assembler messages:
./arch/arm/include/asm/unified.h:12: Error: unknown pseudo-op: `.syntax'
common/spl/spl_optee.S:11: Error: operand 1 must be an integer register -- `mov pc,r3'
```

I think that this error is about architectural difference between armv8 and armv7,
Could I get a help for this error?

I followed this guide. https://github.com/u-boot/u-boot/blob/master/doc/README.rockchip

I enabled "Support OP-TEE Trusted OS" option in menuconfig, is that the problem?
![image](https://user-images.githubusercontent.com/73945390/117328693-d54cac80-aece-11eb-86a0-0aa8da16f719.png)

Thank you.

**Comment by sprhawk** [comment]
@janoslim Hi, how did you fix this ?
