### ISSUE TITLE
error "api uid mismatch"

### ISSUE THREAD

**Issue by GrandChariot** [OP-TEE/optee_os#4600]
Hi! I'm trying to run OP-TEE on rock960(rk3399).
I'm using das u-boot tpl&spl.
I made u-boot.itb file with my bl31.elf file(from arm trusted firmware), and I'm using linux kernel version 4.4.
However, xtest always fails with message "Failed to open TEE context: 0xffff0008"

I think this is deeply relevant to the error message in booting log
[    1.645457] optee: probing for conduit method from DT.
[    1.646405] optee: api uid mismatch
But I don't know why this problem occurs.

Also, I/TC and D/TC messages do not appear at all at boot time. Maybe there's something wrong with my OP-TEE bootloader(bl31, bl32).
I would greatly appreciate your help in this matter.

**Comment by jenswi-linaro** [comment]
I could be that OP-TEE hasn't been loaded by TF-A. Perhaps even the OP-TEE Dispatcher hasn't been compiled into TF-A.

**Comment by GrandChariot** [comment]
@jenswi-linaro Thank you for your comment!

I found that OP-TEE version > 3.8.0 has a very different boot process.
So I tried with OP-TEE version 3.7.0, and it successfully initialized the driver.
[    1.649940] optee: probing for conduit method from DT.
[    1.651481] optee: initialized driver

However, still many of xtest are failed.
947 subtests of which 405 failed
102 test cases of which 77 failed
0 test cases were skipped

Also, optee_example_hello_world fails with message:
# optee_example_hello_world 
E/LD:  init_elf:259 sys_open_ta_bin(8aaaf200-2450-11e4-abe2-0002a5d5c51b)
E/TC:? 0 init_with_ldelf:229 ldelf failed with res: 0xffff000f
E/TC:? 0 tee_ta_open_session:727 Failed. Return error 0xffff000f
optee_example_hello_world: TEEC_Opensession failed with code 0xffff000f origin 0x3

I'm using optee-os version 3.7.0 but optee-client version is 3.9.0.
Will this be a problem?
Or is it a problem that my kernel is too old? My kernel is version 4.4.
Can you tell me what's wrong with my OP-TEE? That would be very helpful.

**Comment by GrandChariot** [comment]
@jenswi-linaro Thank you very much for your reply.

After lowering all optee_os versions to 3.7.0, xtest works fine.

Thank you again.
