### ISSUE TITLE
optee-os compilation error for x509 and how to enable x509 module support in the optee os core

### ISSUE THREAD

**Issue by hardik-patel9** [OP-TEE/optee_os#4605]
Hello All,

Please find the error as per below,
 
 GEN     /core/ldelf_hex.c
  AR      /core/lib/libfdt/libfdt.a
  ****AR      /core/lib/libtomcrypt/libtomcrypt.a****
  AR      /core-lib/libutils/libutils.a
  LD      /ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.elf
  LD      /ta/pkcs11/fd02c9da-306c-48c7-a49c-bbd827ae86ee.elf
  LD      /ta/trusted_keys/f04a0fe7-1f5d-4b9b-abf7-619b85b4ce8c.elf
  OBJDUMP /ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.dmp
  OBJCOPY /ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.stripped.elf
  OBJDUMP /ta/pkcs11/fd02c9da-306c-48c7-a49c-bbd827ae86ee.dmp
  OBJCOPY /ta/pkcs11/fd02c9da-306c-48c7-a49c-bbd827ae86ee.stripped.elf
  OBJDUMP /ta/trusted_keys/f04a0fe7-1f5d-4b9b-abf7-619b85b4ce8c.dmp
  OBJCOPY /ta/trusted_keys/f04a0fe7-1f5d-4b9b-abf7-619b85b4ce8c.stripped.elf
  SIGN    /ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.ta
  SIGN    /ta/pkcs11/fd02c9da-306c-48c7-a49c-bbd827ae86ee.ta
  SIGN    /ta/trusted_keys/f04a0fe7-1f5d-4b9b-abf7-619b85b4ce8c.ta
  CC      /core/ldelf_hex.o
  LD      /core/all_objs.o
out/core/pta/services.o: In function `invoke_command':
optee-os/core/pta/services.c:67: undefined reference to `mbedtls_x509_crt_init'
optee-os/core/pta/services.c:68: undefined reference to `mbedtls_pk_init'
optee-os/core/pta/services.c:69: undefined reference to `mbedtls_x509write_crt_init'
optee-os/core/pta/services.c:70: undefined reference to `mbedtls_x509_csr_init'
core/arch/arm/kernel/link.mk:43: recipe for target 'out/arm/core/all_objs.o' failed

I need to create an x509 certificate inside OP-TEE OS core. To do this I am using x509 module API's which are available in the mbedTLS library.
I have created a pseudo TA inside core/pta directory and try to invoke the x509 module API's from it.
The pta file looks like:
#include <mbedtls/aes.h>
#include <mbedtls/bignum.h>
#include <mbedtls/sha1.h>
#include <mbedtls/sha256.h>
#include <mbedtls/x509_crt.h>
#include <mbedtls/x509_csr.h>
#include <mbedtls/x509.h>
#include <stdio.h>
#include <string.h>
#include <tee_internal_api.h>
/*
 * Trusted Application Entry Points
 */
static TEE_Result invoke_command(void *psess __unused,
                                 uint32_t cmd, uint32_t ptypes,
                                 TEE_Param params[TEE_NUM_PARAMS])
{                                                                                                                                                                                     
        TEE_Result res = TEE_SUCCESS;
        mbedtls_mpi serial = { };
        mbedtls_x509_crt issuer_crt = { };
        mbedtls_pk_context issuer_key = { };
        mbedtls_x509write_cert crt = { };
        mbedtls_x509_csr csr = { };
        size_t sz = 0;

        mbedtls_mpi_init(&serial);
        mbedtls_x509_crt_init(&issuer_crt);
        mbedtls_pk_init(&issuer_key);
        mbedtls_x509write_crt_init(&crt);
        mbedtls_x509_csr_init(&csr);
}

Note:- we are able to compile mbedtls_mpi_init but not mbedtls_x509_crt_init
We Tried to compile only one function from x509_crt.c file:-
* Function - mbedtls_mpi_init is present in ib/libmbedtls/mbedtls/library/bignum.c file which is compilable.
* Function - mbedtls_x509_crt_init is present in lib/libmbedtls/mbedtls/library/x509_crt.c file which is not compilable.

 Below are the two changes added x509 for  in lib/libmbedtls/core/sub.mk file as per below,
1.Added x509 files same like other component files using CFG_CRYPTO_ECC configuration
            ifneq ($(CFG_CRYPTO_DSA),y)
            srcs-$(call cfg-one-enabled, CFG_CRYPTO_RSA  CFG_CRYPTO_DH \
                                         CFG_CRYPTO_ECC) += bignum.c
            srcs-$(call cfg-one-enabled, CFG_CRYPTO_RSA  CFG_CRYPTO_DH \
                                         CFG_CRYPTO_ECC) += x509_crt.c
            endif
             
            Added x509_crt.c file in lib/libmbedtls/sub.mk in the OBJS_CRYPTO part as 
               SRCS_CRYPTO += bignum.c
               **SRCS_CRYPTO += x509_crt.c** 
2. Enable into the source
   Also added the x509 module for including it in compilation of optee core as 
   srcs-y += $(addprefix mbedtls/library/, $(SRCS_CRYPTO))
   **srcs-y += $(addprefix mbedtls/library/, $(SRCS_X509))** 

Please suggest and help us to enable x509 module support in the optee os core ,

Thanks and Regards,
Hardik Patel

**Comment by jforissier** [comment]
Hi @hardik-patel9,

Sorry for the late repy. Did you finally manage to build your PTA? In any case you are on the right track. The TEE core doesn't use many of the MBed TLS functions and therefore some source files are not included in the build. As a result, pseudo-TAs are also limited in what they can use. User space TAs, on the contrary, have access to many more functions via the `libmbedtls.a` library.

The solution is to add the needed files to `lib/libmbedtls/sub.mk` and also the corresponding config flags to `lib/libmbedtls/include/mbedtls_config_kernel.h`. As a quick check I tried the following which builds fine (QEMU):
```diff
diff --git a/core/pta/stats.c b/core/pta/stats.c
index a1dfc6c3..2b2dfa15 100644
--- a/core/pta/stats.c
+++ b/core/pta/stats.c
@@ -12,6 +12,10 @@
 #include <string_ext.h>
 #include <malloc.h>
 
+#include <mbedtls/x509_crt.h>
+#include <mbedtls/x509_csr.h>
+#include <mbedtls/x509.h>
+
 #define TA_NAME		"stats.ta"
 
 #define STATS_UUID \
@@ -145,6 +149,18 @@ static TEE_Result invoke_command(void *psess __unused,
 				 uint32_t cmd, uint32_t ptypes,
 				 TEE_Param params[TEE_NUM_PARAMS])
 {
+	mbedtls_mpi serial = { };
+	mbedtls_x509_crt issuer_crt = { };
+	mbedtls_pk_context issuer_key = { };
+	mbedtls_x509write_cert crt = { };
+	mbedtls_x509_csr csr = { };
+
+	mbedtls_mpi_init(&serial);
+	mbedtls_x509_crt_init(&issuer_crt);
+	mbedtls_pk_init(&issuer_key);
+	mbedtls_x509write_crt_init(&crt);
+	mbedtls_x509_csr_init(&csr);
+
 	switch (cmd) {
 	case STATS_CMD_PAGER_STATS:
 		return get_pager_stats(ptypes, params);
diff --git a/lib/libmbedtls/include/mbedtls_config_kernel.h b/lib/libmbedtls/include/mbedtls_config_kernel.h
index cd4d975d..243ae218 100644
--- a/lib/libmbedtls/include/mbedtls_config_kernel.h
+++ b/lib/libmbedtls/include/mbedtls_config_kernel.h
@@ -117,6 +117,20 @@
 #endif
 #endif
 
+#define MBEDTLS_PK_C
+#define MBEDTLS_PK_PARSE_C
+#define MBEDTLS_PK_WRITE_C
+#define MBEDTLS_OID_C
+#define MBEDTLS_ASN1_PARSE_C
+#define MBEDTLS_ASN1_WRITE_C
+#define MBEDTLS_X509_CRT_PARSE_C
+#define MBEDTLS_X509_CRT_WRITE_C
+#define MBEDTLS_X509_CSR_PARSE_C
+#define MBEDTLS_X509_CSR_WRITE_C
+#define MBEDTLS_X509_CREATE_C
+#define MBEDTLS_X509_CHECK_KEY_USAGE
+#define MBEDTLS_X509_USE_C
+
 #endif /*CFG_CRYPTOLIB_NAME_mbedtls*/
 
 #include <mbedtls/check_config.h>
diff --git a/lib/libmbedtls/sub.mk b/lib/libmbedtls/sub.mk
index c7d0a24b..9c7a8f5e 100644
--- a/lib/libmbedtls/sub.mk
+++ b/lib/libmbedtls/sub.mk
@@ -3,7 +3,7 @@ global-incdirs-y += mbedtls/include
 
 # OBJS_CRYPTO from make file
 SRCS_CRYPTO :=
-ifneq ($(sm),core)
+ifeq (1,1)
 SRCS_CRYPTO += aes.c
 SRCS_CRYPTO += aesni.c
 SRCS_CRYPTO += arc4.c
@@ -118,7 +119,7 @@ SRCS_TLS += ssl_ticket.c
 SRCS_TLS += ssl_tls.c
 
 srcs-y += $(addprefix mbedtls/library/, $(SRCS_CRYPTO))
-srcs-$(sm-$(ta-target)) += $(addprefix mbedtls/library/, $(SRCS_X509))
+srcs-y += $(addprefix mbedtls/library/, $(SRCS_X509))
 srcs-$(sm-$(ta-target)) += $(addprefix mbedtls/library/, $(SRCS_TLS))
 
 cflags-lib-y += -Wno-redundant-decls
```

Build with `make CFG_CRYPTOLIB_NAME=mbedtls CFG_CRYPTOLIB_DIR=lib/libmbedtls`.

Hope this helps.

**Comment by hardik-patel9** [comment]
thanks @jforissier  I will look into it and will get back to you,thanks for reverting it

**Comment by ldts** [comment]
@jforissier thanks for all the detail :) this works as expected...really nice.
We might need to enable this for QCOM - need X.509 signature/key parsing for[ PAS ](https://github.com/OP-TEE/optee_os/pull/7721)
