### ISSUE TITLE
Translation Fault when loading TA due to hash table contents

### ISSUE THREAD

**Issue by niej** [OP-TEE/optee_os#4613]
Hi,

When I debugging translation fault, I see there is hashtab difference in my yocto build and original build, hashtab[0] specifically. Value in original build is 1. While yocto build is 0 and introduce invalid access in bucket[hash % nbuckets]  of resolve_sym_helper()  because hash % nbuckets become very large number. Do you have suggestions on build option?

contents of dump with: aarch64-linux-gnu-objdump -s MY_TA.stripped.elf
yocto build:
> Contents of section .hash:
>  e6f0 00000000 03000000 00000000 00000000  ................
>  e700 00000000    

Original build:
> Contents of section .hash:
>  d568 01000000 03000000 00000000 00000000  ................
>  d578 00000000 00000000    

I am using the 3.10 and patches from psa-development branch. But these shall not impact this issue because related code is far older than these commits.
$ git log --oneline ldelf/ta_elf_rel.c
b609848f ldelf: arm32: support R_ARM_NONE relocations
9d224046 ldelf, libutee: add minimal Thread Local Storage support
fe684948 ldelf: arm64: support R_AARCH64_TLS_TPREL relocations
c88ba125 ldelf: arm: support R_ARM_TLS_DTPMOD32 and R_ARM_TLS_DTPOFF32 relocations
cf830b2b ldelf: add support for weak symbols
bb8cd6f0 ldelf: __resolve_sym(): support STT_NOTYPE

**Comment by jforissier** [comment]
Hi @niej ,

That's interesting. So in your case `nbucket` == 0 and `nchain == 3` (I am using the terminology of the [ELF spec](https://docs.oracle.com/cd/E19683-01/817-3677/6mj8mbtc9/index.html#chapter6-48031)). This does not make much sense to me, could this be a compiler/linker bug?

**Comment by niej** [comment]
Hi @jforissier ,

I have the same suspect with you and had thought the gcc 10 in yocto is too new. Then I tried gcc 8.2 in yocto build, but with no luck. This should be yocto related issue because I see no issue without yocto. So I am trying to find whether some compiler/linker option is needed to fix the hash content. I already use " -Wl,--hash-style=both -Wl,--build-id=none " to fix missing hash style and fix sp_header section position.

Please comments if you have any idea. Thanks!

**Comment by jforissier** [comment]
I have no idea what's happening here. Perhaps you can try the below patch, it should help in case `nbuckets == 0` is a valid case. BTW, which version of OP-TEE are you using?
```diff
diff --git a/ldelf/ta_elf_rel.c b/ldelf/ta_elf_rel.c
index 6c6f9d01..4c1fc0d0 100644
--- a/ldelf/ta_elf_rel.c
+++ b/ldelf/ta_elf_rel.c
@@ -93,6 +93,9 @@ static TEE_Result resolve_sym_helper(uint32_t hash, const char *name,
 	uint32_t *chain = &bucket[nbuckets];
 	size_t n = 0;
 
+	if (!nbuckets)
+		return TEE_ERROR_ITEM_NOT_FOUND;
+
 	if (elf->is_32bit) {
 		Elf32_Sym *sym = elf->dynsymtab;
 ```

**Comment by niej** [comment]
@jforissier ,

Thanks! This solution fix my issue so far. Will validate the TA working status and close this ticket later.

**Comment by jforissier** [comment]
> @jforissier ,
> 
> Thanks! This solution fix my issue so far. Will validate the TA working status and close this ticket later.

OK. I would still like to understand if a fix is needed in the master branch. Which version of OP-TEE are you using? Would you be able to reproduce the issue in the [QEMU test environment](https://optee.readthedocs.io/en/latest/building/devices/qemu.html#id3)? For instance by changing the toolchain (`toolchains/aarch64/bin`), compiler flags (`make CFLAGS_ta_arm64=xyz`) or TA linker flags (`make LDADD=xyz`).

> This change just impact the loading performance and does not impact functionality, right?

Right. Since all symbol resolutions always happens at load time in ldelf (as opposed to late binding -- I'm excluding `dlopen()` stuff here), if the TA starts running properly then it means everything should be OK.

**Comment by niej** [comment]
I am using the 3.10 and patches from psa-development branch. The issue should be related to yocto, because I ever tested gcc 10 and gcc 8.2 in yocto build and normal build. The GCC version does not impact the issue, while the build environment impact it. 

I ever tested with this build enviroment and no bug with it, which is similiar with qemu.
repo init -u https://git.trustedfirmware.org/OP-TEE/manifest.git -b psa-development -m psa-sp-fvp.xml

If you have any flags for compiler and flags suggestions, I can have a try to check whether I can reproduce the issue outside the yocto.

**Comment by jforissier** [comment]
> If you have any flags for compiler and flags suggestions, I can have a try to check whether I can reproduce the issue outside the yocto.

I would expect that suggestion to come from you since you are using yocto which apparently is causing issues with its flags... ;-)

**Comment by niej** [comment]
I already tried to align the compiler/linker flags that I can find for the 2 cases. Maybe there are some hidden flags in yocto I did not find. Because I do not know how to dump all flags inversely. I can only check what flags are used in code. Will update this if I know what's wrong with yocto build.

**Comment by niej** [comment]
Already dump all flags I can find in yocto, but still not reproduce the issue outside yocto. Close this for now.
Thanks support from jforissier!
