### ISSUE TITLE
[optee_hello world] skipping incompatible /usr/local/lib/libteec.a when searching for lteec 

### ISSUE THREAD

**Issue by ZineddineOuldimam** [OP-TEE/optee_os#4615]
Hi, 
I'm running optee on linux 20.04 (64 bits) with qemu_v7. I could not run hello world host application.

I followed all the steps in [build](https://optee.readthedocs.io/en/latest/building/gits/build.html) page in the documentation. I installed optee_os and optee_client successfully, and I exported all variables. However, when I type **make** command in **optee/optee_examples/hello_world/host** I get the following error: **skipping incompatible /usr/local/lib/libteec.a when searching for lteec**. (see the picture below)

![hellowrorld_hostapplication](https://user-images.githubusercontent.com/32750717/118473299-18e2ba00-b70a-11eb-840e-4892c1c92dc9.png)

I tried solutions menitiond in [issue#8](https://github.com/jenswi-linaro/lcu14_optee_hello_world/issues/8) and [issue#14](https://github.com/linaro-swg/hello_world/issues/14) and it does not resolve the problem.

Note: when I run Qemu V7 and I launch hello world in normal world, it works fine (see the picture below).
![qemu](https://user-images.githubusercontent.com/32750717/118473390-331c9800-b70a-11eb-823d-012ede00929c.png)

Please help me

**Comment by etienne-lms** [comment]
Following [build](https://optee.readthedocs.io/en/latest/building/gits/build.html) documentation, you're not really expected to run `make` from **optee_examples/hello_world/host/**.  
You would rather do something like `cd build`, then `make all`  or `make run`
(possibly `make buildroot run` to rebuild _optee_examples_ (and _optee_test_) and run qemu/armv7 with).

**Comment by ZineddineOuldimam** [comment]
Thanks Mr. etienne-lms for your answer.
when I run hello world with qemu/armv7, it works with no problem. However, I'm wondering how can I run hello world example or another application in my linux  (without qemu_v7 and without any platform)? Is it possible ?

**Comment by etienne-lms** [comment]
hello_world application expects a library (libteec) than talks with OP-TEE through an optee Linux driver.
On you host machine, there is likely no OP-TEE and no optee Linux driver, so hello_world will not work.

You would need at least an OP-TEE emulation on your host PC.

Qemu does such  emulation: it emulates an Arm marchine and runs optee, linux, etc... (incl. optee_hello_world) inside this emulation.

**Comment by ZineddineOuldimam** [comment]
Okey, I understand now. thak you very much.

I have another question please. I use OP-TEE and I want to integrate it with the [PX4](https://px4.io/) flight stack to run trusted applications. So, I have external modules (PX4 modules) run on my linux (writing in C++). Some of these modules are trusted modules and other modules are not. I want to execute truseted modules on optee secure world inside the qemu_v7. How can I realise a such work ? I appreciate any help

**Comment by ZineddineOuldimam** [comment]
Okey, I understand now. thak you very much.
