### ISSUE TITLE
Implicit behavior of pair of core_mmu_add_mapping() / phys_to_virt()

### ISSUE THREAD

**Issue by a-rybakov** [OP-TEE/optee_os#4616]
Hello!

I was faced with implicit behavior of a pair of functions - core_mmu_add_mapping() and phys_to_virt(), which are commonly used together to map some hardware registers across optee_os. 

Here is an example — imagine that we need to map two sets of hw-registers which are placed in two regions - rgn0 and rgn1.

rgn0 has phys addr is 0x110000 and a length of 0x10000
rgn1 has phys addr is 0x1e0000 and a length of 0xf0000

![gh_1](https://user-images.githubusercontent.com/57431665/118474561-e0e07480-b713-11eb-9bbf-be2731d60c00.png)

We use the standard way — use core_mmu_add_mapping() to create the mappings and then call phys_to_virt() to get their virtual addresses: -

core_mmu_add_mapping(MEM_AREA_RAM_NSEC, 0x110000, 0x10000)
va0 = phys_to_virt(0x110000,  MEM_AREA_RAM_NSEC)

core_mmu_add_mapping(MEM_AREA_RAM_NSEC, 0x1e0000, 0xf0000)
va1 = phys_to_virt(0x1e0000,  MEM_AREA_RAM_NSEC)

And it is quite expected for va0 and v1 to point at memory that look like this:

![gh_2](https://user-images.githubusercontent.com/57431665/118474625-efc72700-b713-11eb-917a-18d1bf7aeb42.png)

But, unfortunately, actually we have the following situation:

![gh_3](https://user-images.githubusercontent.com/57431665/118474646-f5bd0800-b713-11eb-8a33-798b5a5d40d4.png)

The cause of this is a round up/down to the granule size of 0x100000 in core_mmu_add_mapping(). The requested physical address ranges are rounded to [0x100000 — 0x200000] and [0x100000 — 0x300000], and then the established virtual mappings have an overlap in their physical «counterparts». So, the first established virtual mapping contains translation both for 0x110000, and 0x1e0000. Therefore the following phys_to_virt() calls will only return virtual addresses va0 and va1 — from the first established mapping. This is illustrated in the following picture: 

![gh_4](https://user-images.githubusercontent.com/57431665/118474687-ffdf0680-b713-11eb-9901-c57942650193.png)

The first virtual mapping will be created, for example, as: pa=[0x100000-0x200000] va=[0x40500000-0x40600000], and the second: pa=[0x100000-0x300000] va=[0x40600000-0x40800000]. 

So, after phys_to_virt() calls we will have va0=0x40510000, va1=0x405e0000 (instead of 0x406e0000  that it’s actually mapped by the second request of core_mmu_add_mapping()).

This is an unpleasant situation, because:
* No errors are returned from the called functions
* No translation faults will be raised on acceses to a «wrong» va1, because it is followed by a correct mapping
* At the start of va1 we will see the correct data, but later in the mapping we will encounter garbage RAM contents. This behavior is unexpected and the resulting errors can be hard to debug.
* The rounding up/down behavior and the mappings seem correct by themselves — I suppose it isn`t forbidden, in general, to have different virtual mappings for the same physical addresses.

To avoid such situations, I propose a quite simple solution — we should return the virtual address of an established (found) mapping,from core_mmu_add_mapping() and not simply a boolean success/error value. This will tell the caller the actual address that is to be used. This change also don`t break the current logic, and it simplifies the code a bit (please see the pull request #4617 ). 

Another possible approach is to change phys_to_virt() (or to create new function like phys_to_virt_safe()) by adding a third argument — size, and try to return the virtual address only if the corresponding mapping contains a suitable amount of physical pages.

**Comment by jenswi-linaro** [comment]
Thanks for the detailed description of the problem. It make sense to add a `phys_to_virt_safe()` function too. We may even want to rename the present function `phys_to_virt()` to `phys_to_virt_unsafe()` in another commit.

Or perhaps we should just change the present `phys_to_virt()` function to take a size argument too. What do others think?

**Comment by a-rybakov** [comment]
Change current phys_to_virt() to take size argument seems reasonable to prevent similar problems in future. I will prepare the corresponding patch in another commit to check for the possible hidden issues.

**Comment by jenswi-linaro** [comment]
> Change current phys_to_virt() to take size argument seems reasonable to prevent similar problems in future. I will prepare the corresponding patch in another commit to check for the possible hidden issues.

Thanks
