### ISSUE TITLE
[optee and px4] integrate optee with an external application

### ISSUE THREAD

**Issue by ZineddineOuldimam** [OP-TEE/optee_os#4618]
Hi, 

I'm using OP-TEE and I want to integrate it with the [PX4](https://px4.io/) flight stack to run trusted applications. So, I have external modules (PX4 modules) run on my linux (writing in C++). Some of these modules are trusted modules and other modules are not. I want to execute non-trusted modules on normal world and trusted modules on secure world inside the qemu_v7. How can I realise such a work (as shown in the figure below) ?

![px4_on_emulator](https://user-images.githubusercontent.com/32750717/118479849-cad1b480-b711-11eb-8dd5-dd37d2be607e.png)

 I appreciate any help.

**Comment by jforissier** [comment]
Hi @ZineddineOuldimam,

I know nothing about PX4 but I suggest you look at the OP-TEE example applications at https://github.com/linaro-swg/optee_examples. Maybe you can port your trusted modules to run as Trusted Applications, with a non-trusted module being the client to these applications.

**Comment by ZineddineOuldimam** [comment]
Thanks @jforissier for your reply. Indeed, I could run my non-trusted modules on PX4 and trusted modules on OP-TEE, and I established a SSH connection between them. That means, my host is the PX4 which is running on my local machine (Linux OS), and the guest is the OP-TEE which is running on qemu virtual machine inside my local machine.
