### ISSUE TITLE
Needed Memory area for loading op-tee pager

### ISSUE THREAD

**Issue by janoslim** [OP-TEE/optee_os#4622]
Hello,

I tried to load op-tee with pager on rk3399, which has 192kb embedded sram.
when I build optee with the version 3.7.0, the error occurs,

```
......
  CPP     out/arm/core/kern.ld
  LD      out/arm/core/tee.elf
aarch64-linux-gnu-ld.bfd: OP-TEE can't fit init part into available physical memory
make: *** [core/arch/arm/kernel/link.mk:158: out/arm/core/tee.elf] error 1
```

and i found that this error occurs with following code blocks of core/arch/arm/kernel/kern.ld.S

```
	ASSERT(TEE_LOAD_ADDR >= TEE_RAM_START,
		"Load address before start of physical memory")
	ASSERT(TEE_LOAD_ADDR < (TEE_RAM_START + TEE_RAM_PH_SIZE),
		"Load address after end of physical memory")
	ASSERT(__tmp_hashes_end < (TEE_RAM_VA_START + TEE_RAM_PH_SIZE),
		"OP-TEE can't fit init part into available physical memory")
	ASSERT((TEE_RAM_VA_START + TEE_RAM_PH_SIZE - __init_end) >
		SMALL_PAGE_SIZE, "Too few free pages to initialize paging")

```
Link: https://github.com/janoslim/optee_os/blob/softgent-pkcs11/core/arch/arm/kernel/kern.ld.S
and I found that TEE_RAM_VA_START is start address of SRAM, and TEE_RAM_PH_SIZE is 192kb,

then, the reason I guess is that the needed ram exceed 192kb,
and I tried to reduce dram size and it seems there is no effect for needed ram size,

so, How can I reduce needed ram size to run pager on this?

Thank you!

**Comment by jenswi-linaro** [comment]
I think 192kB a bit on the small side. We have already tried to make the pager as small as possible. You could try to reduce the heap a bit and also try setting `CFG_CORE_UNMAP_CORE_AT_EL0=n` and `CFG_CORE_ASLR=n`.

**Comment by janoslim** [comment]
Thank you @jenswi-linaro

I understood that if the pager is enabled, it is possible to use embedded SRAM as a cache of the DRAM area, but I wonder how could the size of the SRAM be insufficient and wonder why TEE_RAM_START was chosen as the starting address for sram, not dram.  Does the bin of the pager work separately from the bin of the op-tee?

And if it is possible, could I get a tip on the calculation about the memory area that the pager needs? This will be a great help for me.

Thank you a lot.

**Comment by janoslim** [comment]
Thank you @etienne-lms 

when I build tee for rk3399, when i tried all things to minimize the binary, It becomes, 

```
RAM Usage        FF8C0000 - FF937000 size 00077000 476 KiB 119 pages
.text            FF8C0000 - FF8C76D0 size 000076D0  29 KiB
.rodata          FF8C76D0 - FF8C8558 size 00000E88   3 KiB
*hole*           FF8C8558 - FF8C9000 size 00000AA8   2 KiB
.data            FF8C9000 - FF8CB6A8 size 000026A8   9 KiB
.got             FF8CB6A8 - FF8CB978 size 000002D0   0 KiB
*hole*           FF8CB978 - FF8CB980 size 00000008   0 KiB
.bss             FF8CB980 - FF8CE630 size 00002CB0  11 KiB
.heap1           FF8CE630 - FF8CF000 size 000009D0   2 KiB
.nozi            FF8CF000 - FF8DCBC0 size 0000DBC0  54 KiB
.heap2           FF8DCBC0 - FF8ED000 size 00010440  65 KiB
.text_init       FF8ED000 - FF8F3920 size 00006920  26 KiB
.rodata_init     FF8F3920 - FF8F4038 size 00000718   1 KiB
*hole*           FF8F4038 - FF8F5000 size 00000FC8   3 KiB
.rodata_pageable FF8F5000 - FF9007FC size 0000B7FC  45 KiB
*hole*           FF9007FC - FF900800 size 00000004   0 KiB
.text_pageable   FF900800 - FF937000 size 00036800 218 KiB
```
and when I reduce heap size It becomes 192kb slightly but I don't think  It would work fine.
It seems that using pager on rk3399 has a hardware constraint.

Thanks a lot with your kind reply. It is really a big help.
