### ISSUE TITLE
fail to set breakpoints. for example

### ISSUE THREAD

**Issue by murasesyuka** [OP-TEE/optee_os#463]
plat_tee_entry() is not exists now?
example try. but fail.

```
$ ./gcc-linaro-arm-none-eabi-4.9-2014.09_linux/bin/arm-none-eabi-gdb -q
(gdb) optee
SIGTRAP is used by the debugger.
Are you sure you want to change it? (y or n) [answered Y; input not from terminal]
0x00000000 in ?? ()
(gdb) b plat_tee_entry
Function "plat_tee_entry" not defined.
Make breakpoint pending on future shared library load? (y or [n]) n
```

https://github.com/OP-TEE/optee_os/blob/master/documentation/debug.md

> Now it is time to set the breakpoints. For example
> 
> ```
> (gdb) b plat_tee_entry
> Breakpoint 1 at 0x7df104d6: file core/arch/arm/plat-vexpress/plat_tee_func.c, line 42.
> ```

**Comment by jforissier** [comment]
It's called `tee_entry()` now. The code was refactored in https://github.com/OP-TEE/optee_os/commit/82f6147.
Thanks for reporting, I will update the documentation.

**Comment by murasesyuka** [comment]
thanks for the reply. I try it.

**Comment by murasesyuka** [comment]
success it. thank you.
