### ISSUE TITLE
connect from host to qemu via SSH

### ISSUE THREAD

**Issue by ZineddineOuldimam** [OP-TEE/optee_os#4634]
Hi, 

I added `BR2_PACKAGE_DROPBEAR ?= y ` to `common.mk` in **optee/build** . I can connect from normal world to host machine via ssh. However, I can not connect from host to normal world. Even ping never works from host machine to qemu.

Can you help me please

**Comment by ZineddineOuldimam** [comment]
After a long research, I found the easiest solution. Here are the steps : 
1. Go to the file `optee/build/common.mk ` in your host machine and add the following lines: 
```
BR2_PACKAGE_DROPBEAR ?= y
BR2_TARGET_GENERIC_ROOT_PASSWD ?= root
```
In the first line, we installed the DROPBEAR package to enable ssh protocol in the normal world. In the second line, we changed the password to `root` of the root to enable connection via ssh from host.

2. In `optee/build/common.mk ` always, slide down to `QEMU / QEMUv8` part and in `QEMU_EXTRA_ARGS` variable, enable the host forwarding to ssh protocol like this :
```
QEMU_EXTRA_ARGS +=\
	-netdev user,id=vmnic,hostfwd=tcp::12345-:22  -device virtio-net-device,netdev=vmnic
```

3. Last step, in your host machine, connect to the normal world with the following command :
`ssh root@localhost -p12345` . Tape `root` as a password to login and here we go.

**Comment by jforissier** [comment]
@ZineddineOuldimam glad you finally got it working! Thanks for sharing the solution here. That said, how about you create a PR in `build.git` to add the missing parts to `common.mk`? That would certainly be helpful to others in the future.
