### ISSUE TITLE
[vfp] ta panic when interrupted by fiq

### ISSUE THREAD

**Issue by lxxstone** [OP-TEE/optee_os#4635]
When I used the VFP directive in TA, I ran into a strange problem.
I have a floattest in my TA
```
int16_t floattest(short v)
{
    int16_t b = 0;
    b = v * 0.1f;
    return b;
}
```
To prevent the compiler from optimizing my instructions, I added an extra code
```
	while(1){
		test = floattest(test);
		if(test!=1){
			test = test*10;
		}else{
			test = 99;
			EMSG("vfp test=%x",test);
		}
	}
```
b = v * 0.1f; with -mfloat-abi=softfp -mfpu=neon-fp-armv8
The corresponding assembly looks like this
```
     1d8:	eeb8 8ac8 	vcvt.f32.s32	s16, s16
     1dc:	ee28 8a28 	vmul.f32	s16, s16, s17
     1e0:	eebd 8ac8 	vcvt.s32.f32	s16, s16
     1e4:	ee18 3910 	vmov.f16	r3, s16
     1e8:	b21b      	sxth	r3, r3
```
When I ran the test, Panic appeared

```
E/TC:2_0 User TA undef-abort at address 0x400041e4
E/TC:2_0  fsr 0x00000000  ttbr0 0x1637f040  ttbr1 0x00000000  cidr 0x0
E/TC:2_0  cpu #2          cpsr 0x00000130
E/TC:2_0  r0 0x0003a5a0      r4 0x00000000    r8 0x00000000   r12 0x00000004
E/TC:2_0  r1 0x00000018      r5 0x4000aa50    r9 0x40003f54    sp 0x40003f28
E/TC:2_0  r2 0x00000000      r6 0x4000aa30   r10 0x1633b598    lr 0x400041d9
E/TC:2_0  r3 0x0003a5a0      r7 0x40003f64   r11 0x00000000    pc 0x400041e4
E/TC:2_0  arch: arm  load address: 0x40004000 ctx-idr: 2
E/TC:2_0  stack: 0x40003000 4096
E/TC:2_0 Call stack:
E/TC:2_0  0x400041e4
E/TC:2_0 DFAR: 00000000
E/TC:2_0 DFSR: 00000000
E/TC:2_0 IFAR: 00000000
E/TC:2_0 IFSR: 00000000
```

When I turn off the fiq response, test TA won't panic.

So I have a couple of questions:
When a TA is interrupted to the kernel by FIQ, does the VFP of TA not have a save/restore mechanism?
Do these two functions restore and save the NS kernel's VFP?
```
thread_lazy_save_ns_vfp()
thread_lazy_restore_ns_vfp()
```
Do I need to do **thread_kernel_save_vfp**() before switching to the ns kernel, and then do **thread_kernel_restore_vfp**() when resume ta?
Or I need to add function to save-restore TA's VFP context?

**Comment by jenswi-linaro** [comment]
That's a bit surprising, it is supposed to work automatically.

**Comment by lxxstone** [comment]
With this patch, the problem has been fixed.
https://github.com/OP-TEE/optee_os/commit/405c67d37d3d82d824f4bff042928219a45fa43e
thanks very much.
