### ISSUE TITLE
Using GlobalPlatform API

### ISSUE THREAD

**Issue by saleh-unikie** [OP-TEE/optee_os#4636]
I am working on a project based on op-tee. In my project I am going to use GlobalPlatform APIs which are defined in optee-os. following the hello_world example, i tried to include the TA_DEV_KIT_DIR into my project, but it didn't help me.

it is a part of CMakeLists.txt of my project:

`add_library(${target_lib} STATIC  ${SOURCE_FILES})

target_include_directories(	${target_lib} PRIVATE
	${OPTEESDK}/optee_os/out/arm/export-ta_arm64/include/
)`

But seems it is not the correct way to include the GlobalPlatform API of op-tee project into the my project.
Can anyone help me to know how can I add optee-os libraries into CmakeLists.txt properly?

**Comment by saleh-unikie** [comment]
Let me ask the question in a more clear format!

What I need is to include these two header file into my source code:
`#include <tee_internal_api.h>
#include <tee_internal_api_extensions.h>`

but Adding this line to my CMakeLists.txt doesn't work:
`target_include_directories( ${target_lib} PRIVATE
${optee_path}/optee_os/out/arm/export-ta_arm64/include/
)`

What can I do?

**Comment by etienne-lms** [comment]
Note that in _OP-TEE/build.git_ we currently do not build TAs from CMake. CMake is used only for the _host/_ applications.

For examples, for optee_examples (respectively optee_test), we use CMake file build the Linux client application (host/...) [1] (resp. [3]) and we use raw Makefiles to build the TAs [2] (resp. [4]). These later Makefiles get the SDK path straight from caller
with TA_DEV_KIT_DIR=/path/to/optee/devkit/export/.

In the hope this may help you despite it does not answer your question.

[1] https://github.com/OP-TEE/build/blob/3.13.0/br-ext/package/optee_examples_ext/optee_examples_ext.mk#L30
[2] https://github.com/OP-TEE/build/blob/3.13.0/br-ext/package/optee_examples_ext/optee_examples_ext.mk#L13
[3] https://github.com/OP-TEE/build/blob/3.13.0/br-ext/package/optee_test_ext/optee_test_ext.mk#L71
[4] https://github.com/OP-TEE/build/blob/3.13.0/br-ext/package/optee_test_ext/optee_test_ext.mk#L34

**Comment by saleh-unikie** [comment]
Thanks for your help. @etienne-lms 
Yes, it needs writing makefile instead of CMake in the current status of the project.

Anyway I could find an opensource project, where they have used OpTee apis using cmake, actually the optee_os and optee_client are built during building the whole project in this project, it can give some ideas about how to use it:
https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/OP-TEE/Introduction.md
