### ISSUE TITLE
Set a virtual address to CFG_TZDRAM_START

### ISSUE THREAD

**Issue by super119** [OP-TEE/optee_os#4637]
Can we set a virtual address to CFG_TZDRAM_START?
The reason is that, the TZDRAM physical address might change, and using a fixed virtual address is easier(since the VA space is quite large).
I took a quick look at entry_a64.S and core_mmu.c, it seems that this is not supported yet?
Trusty supports this from the very beginning:
https://android.googlesource.com/trusty/lk/common/+/master/arch/arm64/start.S#37

Thanks for any comments.

**Comment by jenswi-linaro** [comment]
You're right it's not supported. In which cases does the physical load address of OP-TEE change? When the secure memory is repartitioned on a particular platform?

Any way, patches are welcome. :-)

**Comment by super119** [comment]
Thanks for the reply. Yes, there are multiple scenarios for a specific platform which may have different physical addresses for TrustOS. For example: board flashing and coldboot. When flashing the board, not all boot components are needed. So our strategy is the address of TrustOS is always calculated dynamically (according to which boot components are getting used). This also helps when the boot components change despite it doesn't happen often.
In addition, this "dynamic calculating" logic helps when there are bad blocks in DRAM. Bootloaders can isolate the bad blocks according to the boot parameters. In this case, the physical address for TrustOS may change as well.
Anyway, I think a dynamic approach for TZDRAM_BASE is better. Trusty does the memory mapping of TZDRAM between the VA(hardcoded in the build file) and the PA(got from the PC register -- it's the PA of the "_start" function actually) at the beginning. So will you have a plan to support that if this sounds good?

**Comment by jenswi-linaro** [comment]
I can review it if you can supply the patches.

**Comment by super119** [comment]
I see. Thanks again. This issue can be closed now.
