### ISSUE TITLE
Ask a TEE startup process question?

### ISSUE THREAD

**Issue by danielcug2020** [OP-TEE/optee_os#4638]
![image](https://user-images.githubusercontent.com/63640355/119488632-5e982600-bd8d-11eb-9260-211276a73444.png)

Question:
1. We find that optee changed the init flow from "dcache_clean_range" to "dcache_cleaninv_range" at line 163 in "generic_entry_a64.S" since optee_os 3.8. So why does it need to be flushed back to the DDR at line 163?  just only invalid the cache is OK?
2. We met a bug: The old ATF（AFT 1.1 ）load the optee_os(v3.9.0), the "dcache_cleaninv_range" function flushed the dirty data in the cache back to DDR after the TEE bss section cleared(at line 130).As a result, the device will be paniced
3. Is there a good solution to fix this bug without upgrading the ATF?

we dicussed this bug in our team:
陈勇(00437306)2021-05-25 16:57
@Jerome FORISSIER  If the cache is enable by ATF and if it is dirty, the "dcache_cleaninv_range" shall flush dirty cache to DDR. Which means the bss shall be coverd by the dirty cache. 
陈勇(00437306)2021-05-25 17:02
So as i unstand , the TEE initialization flow is based on that "ATF SHOULD not enable the cache " , is that right ?
Jerome FORISSIER(00273349)2021-05-25 17:02
No, it is the responsibility of TF-A (ATF ;-)) to flush its own ranges on the cache if needed
either not enable cache, or flush it prior to switching to OP-TEE
Jerome FORISSIER(00273349)2021-05-25 17:03
OP-TEE only touches its own memory ranges is the idea here I think
(well it is my understanding of this code)
陈勇(00437306)2021-05-25 17:04
we find that optee changes the init flow from "dcache_clean_range" to "dcache_cleaninv_range". 
陈勇(00437306)2021-05-25 17:05
And i also meet the same problem in the ATF in the seconday - core boot-up flow
Jerome FORISSIER(00273349)2021-05-25 17:06
I don't know this code well :-/ are you saying you need to change code in OP-TEE?
陈勇(00437306)2021-05-25 17:08
Nop . I just want to know whether the optee have some special requirements for ATF before load it. 
陈勇(00437306)2021-05-25 17:09
And i think it is fair enough that "ATF should keeep the OPTEE cache clean " before run optee. 
Jerome FORISSIER(00273349)2021-05-25 17:09
Got it, yes I think it is the requirement.
陈勇(00437306)2021-05-25 17:10
BUT now we find some old version ATF do not clean the cache. 
Jerome FORISSIER(00273349)2021-05-25 17:11
It is a bug in ATF 
陈勇(00437306)2021-05-25 17:13
So maybe as the platform implement, I should not assume the original ATF do that work for me. 
陈勇(00437306)2021-05-25 17:14
It is an expensive bug for my team. We lost almost one month to find it 
Jerome FORISSIER(00273349)2021-05-25 17:24
 sorry to hear that... yes cache bugs are hard to find
刘丹(00311821)2021-05-25 17:26
So why does it need to be flushed back to the DDR in "163 LINE"?  just only invalid the cache is OK?  
Jerome FORISSIER(00273349)2021-05-25 17:30
it is op-tee memory at this point
Jerome FORISSIER(00273349)2021-05-25 17:35
hmmmm you are right I don't think clean is needed here, I don't really understand why we would clean
Jerome FORISSIER(00273349)2021-05-25 17:36
the guy who knows this part very well is jenswi-linaro on GitHub, I suggest you ask on https://github.com/OP-TEE/optee_os/issues if you want to be sure

**Comment by danielcug2020** [comment]
@jenswi-linaro

**Comment by jenswi-linaro** [comment]
The description of the commit making this change explains it quite well:
```
commit ba8c25ac259aec163cb63da1bbfe19128a0ae724
Author: Andrew F. Davis <afd@ti.com>
Date:   Mon Jan 13 17:18:10 2020 -0600

    core: generic_entry_a64.S: use CIVAC over IVAC to clean cache data
    
    After moving some initial sections around in memory we clean out the new
    data and invalidate the cache so it can be seen by other cores when they
    enable caches. The instruction used was invalidate; on most systems this
    will behave the same as clean/invalidate, but on some with L3 caches this
    can cause the just written data to be invalidated. Use the
    clean+invalidate to prevent this on such systems.
    
    Signed-off-by: Andrew F. Davis <afd@ti.com>
    Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

By the way, what is the problem with causing a writeback into DDR? OP-TEE owns this memory.

**Comment by jforissier** [comment]
@jenswi-linaro wouldn't dcache_clean_range() be enough?

**Comment by jenswi-linaro** [comment]
Now when I look at the code it seems that we do depend on the cache not having any stale entries so we might just as well drop this call. Note that there's another `dcache_cleaninv_range()` after the MMU has been enabled, that one I think we've always had.

**Comment by danielcug2020** [comment]
> The description of the commit making this change explains it quite well:
> 
> ```
> commit ba8c25ac259aec163cb63da1bbfe19128a0ae724
> Author: Andrew F. Davis <afd@ti.com>
> Date:   Mon Jan 13 17:18:10 2020 -0600
> 
>     core: generic_entry_a64.S: use CIVAC over IVAC to clean cache data
>     
>     After moving some initial sections around in memory we clean out the new
>     data and invalidate the cache so it can be seen by other cores when they
>     enable caches. The instruction used was invalidate; on most systems this
>     will behave the same as clean/invalidate, but on some with L3 caches this
>     can cause the just written data to be invalidated. Use the
>     clean+invalidate to prevent this on such systems.
>     
>     Signed-off-by: Andrew F. Davis <afd@ti.com>
>     Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
> ```
> 
> By the way, what is the problem with causing a writeback into DDR? OP-TEE owns this memory.

After "clean+invalid" the cache at line 163 ,the TEE bss section data （such as "static void *crypt_algo[CRYPTO_MAX_ALGO];" in drvcrypt.c）will be set an abnormal value，which will lead to an exception in the subsequent startup process.

**Comment by jenswi-linaro** [comment]
Aha, I see. So the problem is that the cache indeed contains stale entries.

I believe that for any other platform the cache doesn't contain stale entries or perhaps only in a way that it's not noticed. If that wasn't the case we'd a variant of the error you're seeing. So solve this I propose:
1. We replace the call to dcache_cleaninv_range() with a call to dcache_inv_range()
2. We make this call optional, default disabled

With this we'd require the OP-TEE loader to hand over with without stale entries in the cache, which is quite reasonable and easy for a loader to do and in practice it seems that almost all do. For platforms where the cache have stale entries we have a workaround, it will hopefully not interfere with platforms which has a L3 cache.

What do you think? Does it make any sense?

**Comment by danielcug2020** [comment]
> Aha, I see. So the problem is that the cache indeed contains stale entries.
> 
> I believe that for any other platform the cache doesn't contain stale entries or perhaps only in a way that it's not noticed. If that wasn't the case we'd a variant of the error you're seeing. So solve this I propose:
> 
> 1. We replace the call to dcache_cleaninv_range() with a call to dcache_inv_range()
> 2. We make this call optional, default disabled
> 
> With this we'd require the OP-TEE loader to hand over with without stale entries in the cache, which is quite reasonable and easy for a loader to do and in practice it seems that almost all do. For platforms where the cache have stale entries we have a workaround, it will hopefully not interfere with platforms which has a L3 cache.
> 
> What do you think? Does it make any sense?

Yes, I agree with your suggestion.

**Comment by jenswi-linaro** [comment]
@glneo are you OK with this too?
