### ISSUE TITLE
How to use TEEC_RegisterSharedMemory to register bigger buffer , e. g. 4MB?

### ISSUE THREAD

**Issue by sunzc** [OP-TEE/optee_os#4639]
I'm using optee-v3.9 on hikey960, with `CFG_CORE_DYN_SHM=y`. My client application(CA) needs a big buffer(say 4MB) to communicate with TA. I tried several ways of allocating shared buffer, but all failed when buffer size is bigger than 2MB:

- use TEEC_MEMREF_TEMP_INOUT
```
op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INOUT, TEEC_NONE, TEEC_NONE, TEEC_NONE);
op.params[0].tmpref.buffer = input_buf;
op.params[0].tmpref.size = 4*1024*1024;/*4MB*/
```

- use TEEC_RegisterSharedMemory 
```
shm.size = 4*1024*1024;
shm.flags = TEEC_MEM_INPUT|TEEC_MEM_OUTPUT;
res = TEEC_RegisterSharedMemory(&ctx, &shm);
```
How to allocate a single big(4MB) shared memory for CA and TA to communicate ? I was assuming it can be quite elastic with the dynamic shared buffer feature(CFG_CORE_DYN_SHM=y), but do not know how to make best use of it from client application. Besides changing CFG_SHMEM_SIZE in the optee os, any other suggestions?

Thanks!
- Zc

**Comment by jenswi-linaro** [comment]
The temporary memory reference should probably be avoided for such large buffers.

You could try `TEEC_AllocateSharedMemory()` too. Did `TEEC_RegisterSharedMemory()` fail or was it `TEEC_InvokeCommand()` that failed?

**Comment by sunzc** [comment]
I tried TEEC_RegisterShareMemory() with 1MB, it succeed, 1.5MB succeed, and 2MB, but failed. The TEEC_RegisterSharedMemory failed with 0xffff000c(OUT_OF_MEMORY), not the TEEC_InvokeCommand() that failed.

I was assuming TEEC_AllocateSharedMemory() would be limited by CFG_SHMEM_SIZE(2MB by default), and TEEC_RegisterSharedMemory() would be not limited by this size limit as it dynamically register a chunk of memory to be accessed by TEE, but it seems there is still a size limit for dynamically shared memory.

Eventually I tried increase the CFG_SHMEM_SIZE to  0x00800000, and it worked. I can use 8MB shared memory.

So my question is how does `CFG_CORE_DYN_SHM=y` (dynamically shared memory) help TEE client application to use bigger shared memory?

**Comment by etienne-lms** [comment]
I would expect also CFG_CORE_DYN_SHM=y to be not bound to limits but the platform resources here.
Could you point out which optee_os/core function returns TEE_ERROR_OUT_OF_MEMORY? Which memory pool gets exhausted?

**Comment by sunzc** [comment]
Now I moved on with CFG_SHMEM_SIZE set as 0x00800000, so I do not run into the TEE_ERROR_OUT_OF_MEMORY problem. Before that, what I can observe is that with buffer size grows over 2MB, TEEC_RegisterShareMemory() starts to fail, not sure about which one of the optee_os/core function.

**Comment by etienne-lms** [comment]
You're on optee 3.9.0. Which Linux kernel and optee patches (in [upstream-tee-subsys-patches.txt](https://github.com/linaro-swg/linux/blob/branch-optee-v5.9-20210426/upstream-tee-subsys-patches.txt)) do you use?
Are you sure dynamic shared memory capability is found at boot time? Check the debug traces in Linux ([end of `optee_probe()`](https://elixir.bootlin.com/linux/v5.4/source/drivers/tee/optee/core.c#L644)) and optee_os ([`tee_entry_exchange_capabilities()`](https://elixir.bootlin.com/op-tee/3.9.0/source/core/arch/arm/tee/entry_fast.c#L102))
Optee: `D/TC:0   tee_entry_exchange_capabilities:102 Dynamic shared memory is enabled`
Linux: `[    3.005093] optee: dynamic shared memory is enabled`

**Comment by etienne-lms** [comment]
You can fetch some pools statistics with `xtest --stats --alloc`.

**Comment by sunzc** [comment]
I got "xtest TEEC_OpenSession: res 0xffff0008 err_orig 0x3"(ITEM_NOT_FOUND) when I run `xtest --stats --alloc`.
