### ISSUE TITLE
Build OPTEE on BD-SL-i.MX6

### ISSUE THREAD

**Issue by niusenc** [OP-TEE/optee_os#4640]
Hi all,
I am trying to build OPTEE on BD-SL-i.MX6. I follow this link: https://yilingxu.github.io/OP-TEE-on-i.MX-6Quad-SABRE-SD
But I met a problem, in step 7, it says "Copy all file in out/export to the rootfs of the target board". However, I did not find and rootfs in my SD card or compiled files. Do I need to download rootfs from somewhere? 

Thanks in advance

**Comment by saleh-unikie** [comment]
rootfs means your root file system, so here I think it means copy the files to the "/" location of your target
