### ISSUE TITLE
en/decryption of pager of TA pages

### ISSUE THREAD

**Issue by janoslim** [OP-TEE/optee_os#4643]
Hello,

I am willing to customize op-tee to use embedded SRAM area usefully for TA that reserving SRAM area only to TA pages, and optee kernel pages reside on DRAM. I wonder manually fixing linker script would works.
And I also wonder when user TA page is encrypted/decrypted when page changing.
I noticed that tee_pager_handle_fault() handles page fault for TA, however I failed to find where the encryption process defined inside optee source code. Could I get some advice for looking through the optee pager?
And lastly I wonder optee kernel utilize hardware crypto accelerator for pager, since I am using stm32mp157C-dk2 board which has crypto accelerator but It is hard to find where using it :(

Thank you for reading my issue:)

**Comment by etienne-lms** [comment]
> I am willing to customize op-tee to use embedded SRAM area usefully for TA that reserving SRAM area only to TA pages, and optee kernel pages reside on DRAM. I wonder manually fixing linker script would works.

Note it is not recommended to have TAs in SRAM and Core (kernel) in DDR on stm32mp1. DRR is less secure than SRAM. If OP-TEE Core runs in DDR, there is no real reason to run TAs in SRAM.

> Could I get some advice for looking through the optee pager?

Pageable memory is referenced by fobj, https://github.com/OP-TEE/optee_os/blob/3.13.0/core/arch/arm/mm/tee_pager.c#L43.
They represent memory objects. Pager calls `fobj_load_page()` to gets a paged page being loaded and `fobj_save_page()` to get the page swapped out. I think the encryption/decryption instructions you are looking for can be found in [fobj.c#L82](https://github.com/OP-TEE/optee_os/blob/3.13.0/core/mm/fobj.c#L82) (3.13.0).

> And lastly I wonder optee kernel utilize hardware crypto accelerator for pager...

Interesting. Must consider multithreading/SMP. Patches are welcome.

> ... It is hard to find how to use it :(

Sorry.

**Comment by janoslim** [comment]
Thank you for your answer @etienne-lms !!

For more information of the last question, I noticed that there is a OP-TEE crypto driver for stm32mp157C-dk2, as mentioned here(https://wiki.st.com/stm32mpu/wiki/CRYP_internal_peripheral), and I failed to find the clue for CRYP driver of OP-TEE.

As far as i know, crypto ISA extension for arm is updated since armv8-a, and I somehow confused for what crypto hw of stm32mp157 and how to use it.

Your reply is very helpful to me. Thank you very much.

**Comment by etienne-lms** [comment]
> the Arm® Cortex®-A7 secure core to be controlled in OP-TEE by the CRYP OP-TEE driver

Right, hmm, that's false. There is no STM32 CRYP driver in OP-TEE I apology :(
Current stm32mp1 does not use CRYP and HASH (hashing hw accel.) support in pager.
Patches are welcome, of course.

**Comment by janoslim** [comment]
Thank you for your advice. becomes a big help.
