### ISSUE TITLE
Questions about PersistentObject.

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#4645]
When I call 'TEE_WriteObjectData' to save(write) data over 2MB in a persistent object, the program always calls 'tee_panic'. 
How can I save more data at once?

**Comment by etienne-lms** [comment]
you likely have a error code printed out with the panic trace like `TA panicked with code 0xXXXXXX`.
That should help understanding where why it panicked. Use also `CFG_UNWIND=y`.
