### ISSUE TITLE
Overflow in core_mmu_init_ta_ram

### ISSUE THREAD

**Issue by ldebieve** [OP-TEE/optee_os#4646]
Hi All,

I'm facing an issue using my ST board 157C-EV1. This board (ARMv7 based) is using 1GB DDR size.
I'm using OP-TEE in DDR (no pager) and putting the core at the DDR end:
`CFG_TZDRAM_START = End of DDR - TZDRAM_SIZE`
Which means the TA_RAM will be from 0xFF****** to 0xFFFFFFFF

With this mapping, entering into the `core_mmu_init_ta_ram` it result on an issue:
	`pe = virt_to_phys((void *)(e - 1)) + 1;`

Here, the **pe return 0** because paddr_t  is defined as _unsigned long_.
pe is later used by `tee_mm_init` which is waiting for hi and low memory address.

I've for now workaround is using the `CFG_CORE_LARGE_PHYS_ADDR` but assuming that it increase the size of my final binary.

Should that be reworked to use a size rather than a end address?

BR

**Comment by jenswi-linaro** [comment]
Good to hear that `CFG_CORE_LARGE_PHYS_ADDR` helped. Some increase is expected with this option, but I believe it shouldn't be too bad. So if you wish to run without `CFG_CORE_LARGE_PHYS_ADDR` might be more a matter of principle.

Anyway, I think we can agree that it is at least a bit annoying with this limitation. But there's a risk this is only one of several places that needs to be fixed. If you'd like to try fixing this I can help reviewing the patches.

**Comment by ldebieve** [comment]
Hi @jenswi-linaro,

OK, Will do, just checking that enabling `CFG_CORE_LARGE_PHYS_ADDR` also shows that a build issue occurred with `LOG_LEVEL=4` and `PAGE=y`.
```
core/arch/arm/mm/tee_pager.c:1379:10: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
 1379 |          (void *)(ai->va & ~SMALL_PAGE_MASK));
```

Working on that an pushing a patch for review.

Thanks for feedback.
Lionel
