### ISSUE TITLE
Communication between TAs in OPTEE

### ISSUE THREAD

**Issue by rafagameiro** [OP-TEE/optee_os#4647]
Hi!

I'm programming some TAs to later run them on top of OP-TEE, but I wanted to have a centralized TA that would receive the requests from the Normal World and then call the correspondent TA's function.
Is there any way I can do for this centralized TA call the functions in the respective TAs? 
From a programming point of view, I would say I need a header file with the functions I want/can call from a TA, but since we're talking about OP-TEE and Secure World I'm not sure if it is that simple.

Best Regards

**Comment by jforissier** [comment]
Hi @rafagameiro,

If I understand correctly, you want to call a TA from another TA, right? In this case, it is the "internal client API" that you're looking for: `TEE_OpenTASession()`, `TEE_CloseTASession()` and `TEE_InvokeTACommand()`. See this code for example: https://github.com/OP-TEE/optee_test/blob/3.13.0/ta/tpm_log_test/ta_entry.c#L14-L33.

**Comment by rafagameiro** [comment]
Yes, that's the objective! 

Actually another question, based on the optee_examples, the TAs have the `TA_OpenSessionEntryPoint()` and `TA_DestroySessionEntryPoint()`. I'll assume that those are use for the calls from the Normal World, right? And in that case, I must implement the `TEE_OpenTASession()` and `TEE_CloseTASession()`, correct?

**Comment by jforissier** [comment]
> Yes, that's the objective!
> 
> Actually another question, based on the optee_examples, the TAs have the `TA_OpenSessionEntryPoint()` and `TA_DestroySessionEntryPoint()`. I'll assume that those are use for the calls from the Normal World, right?

Yes, but not only. They are called when the TA is invoked from Secure World too. 

> And in that case, I must implement the `TEE_OpenTASession()` and `TEE_CloseTASession()`, correct?

`TEE_OpenTASession()` in Secure World is equivalent to `TEEC_OpenSession()` in Normal World. They are implemented in `libutee` for TAs to use.

**Comment by rafagameiro** [comment]
Ok I understand then. In that case I just to use as was described in the example you provided.
Thank you for the help!
I'll now close the issue

Best Regards
