### ISSUE TITLE
optee aes encrypt failed!

### ISSUE THREAD

**Issue by gitgonewithwind** [OP-TEE/optee_os#4652]
hi all,

I am playing maaxboard (yocto-zues branch） 
I use optee example code  aes to encrypt my excutable code and decrypt it to run . before it worked well in  yocto-sumo branch.
I write a small a.c source to printf hello world and generate a.out . and use aes to encrypt it . It work well too.
but when I change my app STM.out (size :740448 less than 1M) ,I can not encrypt it.

debug as follow,  How I can do?(xtest passed, 5dbac793-f574-4871-8ad3-04331ec17f24.ta  installed, so a.out can work)
Thanks.

./optee_example_aes_encrypt
fsize=740448
Prepare session with the TA
Prepare encode operation
Load key in TA
Reset ciphering operation in TA (provides the initial vector)
Encode buffer from TA
E/TC:? 0 
E/TC:? 0 TA panicked with code 0xffff000c
E/LD:  Status of TA 5dbac793-f574-4871-8ad3-04331ec17f24
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0xfe200000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0xfe202000 size 0x007000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000d000 pa 0xfe209000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x4000e000 pa 0xfe20a000 size 0x003000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40011000 pa 0xfe20d000 size 0x001000 flags r--s
E/LD:  region  5: va 0x40012000 pa 0x00001000 size 0x00e000 flags r-xs [0]
E/LD:  region  6: va 0x40020000 pa 0x0000f000 size 0x00c000 flags rw-s [0]
E/LD:  region  7: va 0x4002c000 pa 0xfe228000 size 0x001000 flags rw-s (stack)                                          
E/LD:  region  8: va 0x4002e000 pa 0xe58cc010 size 0x0b5000 flags rw-- (param)                                          
E/LD:  region  9: va 0x400e3000 pa 0xdd971010 size 0x0b5000 flags rw-- (param)                                          
E/LD:   [0] 5dbac793-f574-4871-8ad3-04331ec17f24 @ 0x40012000                                                           
E/LD:  Call stack:                                                                                                      
E/LD:   0x0000000040014b70                                                                                              
E/LD:   0x00000000400123f0                                                                                              
E/LD:   0x000000004001647c                                                                                              
E/LD:   0x0000000040012414                                                                                              
E/LD:   0x00000000fe0046b0                                                                                              
optee_example_aes_encrypt: TEEC_InvokeCommand(CIPHER) failed 0xffff3024 origin 0x3

**Comment by lubing521** [comment]
It may be no enough memory for your case  that  error code  0xffff000c by return.

**Comment by gitgonewithwind** [comment]
> It may be no enough memory for your case that error code 0xffff000c by return.
@lubing521 
Thank you very much for your reply 
How can I do?
Do I need kill apps to release more memory?


I changed aes/host/main.c #define AES_TEST_BUFFER_SIZE    2097152//4096.  from 4096 to 2M or 3M. it does not work.  my encryt file <1M(900K) . it seems I only  can encryt 20K file

**Comment by gitgonewithwind** [comment]
I changed CFG_CORE_HEAP_SIZE from 64k to 128 K, it can encrypt 100K file. so if I need to encrypt (or decrypt)  900K (<1M)seperately, I need to change CFG_CORE_HEAP_SIZE  to 1M?

I tried to change CFG_CORE_HEAP_SIZE  to 4M 
error shows TEE_RAM_VA_SIZE  is small. but I do not know where to change TEE_RAM_VA_SIZE

any help?

**Comment by wamserma** [comment]
Instead of increasing the heap, try incremental encryption/decrpytion.
