### ISSUE TITLE
TA in OPTEE waveup by a secure interrupt?

### ISSUE THREAD

**Issue by norman-yang** [OP-TEE/optee_os#4653]
I am wondering if I can issue a secure interrupt to waveup a TA for service. From OPTEE architecture, it seems need a REE side software to handle the interrupt and call associated TA to process it. I am not sure if the understanding is correct? Any comments are preciated. Thanks in advance.

**Comment by jenswi-linaro** [comment]
No, not today. With https://github.com/OP-TEE/optee_os/pull/4601 we'll have a some building blocks that could be used in such a design.

**Comment by norman-yang** [comment]
Looking forward to the update.
