### ISSUE TITLE
Cancel ongoing TA operation from PTA context

### ISSUE THREAD

**Issue by 0ddc0de** [OP-TEE/optee_os#4655]
Looking at #2995, I see that CAs cannot forcefully terminate ongoing operations of TAs.
Is there a straightforward way to cancel an ongoing operation of a TA from a PTA context?
And if that's not the case, could you recommend a way on how to terminate a TA from a PTA context?
For future reference: #1753 might be related to this.

Thanks in advance!

**Comment by jenswi-linaro** [comment]
There isn't a straightforward way to do this. A TA can be in three different states while still alive, running in secure user space, processing a syscall in secure privileged mode, doing RPC in normal world. So there are a few cases to cover. I don't know the best way to implement this, but it should at least try to reuse or hook into the code doing the fatal abort handling.
