### ISSUE TITLE
May I use other storage as secure storage?

### ISSUE THREAD

**Issue by Alan0106** [OP-TEE/optee_os#4657]
Hi

I only see the introduction of eMMC in Secure storage. So is the source code of RPMB.
I want to ask that is it possible use other storage like UFS as secure storage. If yes, do we need to change a lot of source code for using other secure storage.

**Comment by jforissier** [comment]
Hi @Alan0106,

How is the UFS RPMB partition exposed to user space by the Linux kernel? With some luck it could be mostly identical to what eMMC does (`/dev/mmcblk0rpmb`), in which case it would be trivial to adjust `tee-supplicant` to open the UFS device instead of the eMMC one.

**Comment by Alan0106** [comment]
Hi

I am still studying about UFS. I think that it can be only modify the path of node in tee-supplicant.
I also found some discussion about UFS here.
Is there some examples can let me reference
