### ISSUE TITLE
imx_csu: protecting the imx_rngb

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#4658]
@clementfaure just to make sure we track this pending feature - if you recall. some months ago - while up-streaming the rngb support- these changes to protect the rngb when in use by OP-TEE were left pending (I did submit several proposals, including one that would provide runtime configuration of the CSU vs the current static one).
if anyone could confirm that this will happen that would be great (the current situation could conflict with Linux accessing the rngb)

**Comment by ldts** [comment]
@MrVan please could you or any of the plat-imx maintainers follow up on the commitment made to deliver this.

**Comment by ldts** [comment]
jfyi @jenswi-linaro this doesnt feel right.

**Comment by jenswi-linaro** [comment]
@clementfaure or @MrVan, please respond.

**Comment by clementfaure** [comment]
Hi @jenswi-linaro,
We haven't made enough progress on this CSU task to submit a PR right now. We gave other tasks higher priority unfortunately.
@ldts Feel free to submit a patch to lock the RNGB in the CSU if you want to do it right now. I will give my `Acked-by`.

**Comment by ldts** [comment]
ok posted the version reviewed by @Emantor
