### ISSUE TITLE
TEEC_InvokeCommand Performance Issue: back-and-forth time increase linearly when TA_DATA_SIZE increases 

### ISSUE THREAD

**Issue by sunzc** [OP-TEE/optee_os#4665]
I find one performance issue with `TEEC_InvokeCommand()`. I test `TEEC_InvokeCommand` with a DO-NOTHING command to evaluate the plain **CA/TA world switching** overhead. When I set TA_DATA_SIZE to 1MB, the overhead is about 0.1 ms, however, when I set `TA_DATA_SIZE` to 100MB (My OP-TEE OS's secure memory is resized to 128MB), the overhead is about 6 ms (amazingly!). The TA does actually nothing, it simply returns on the DO-NOTHING command.

 Can anyone who is familiar with the internals explain a little bit why it happens and whether this is optimizable? 

Thanks!
- Ethan

**Comment by jenswi-linaro** [comment]
I guess that's the time needed to map 100MB. The obvious optimization would be to make it smaller. ;-)
You could try mapping using larger pages, perhaps using the 2 MB sections instead.

**Comment by sunzc** [comment]
Does the TEE OS remap the 100MB again and again for each command execution? I did the test of running multiple  TEEC_InvokeCommand(DO-NOTHING)  commands within a single context/session.

**Comment by jenswi-linaro** [comment]
Yes

**Comment by sunzc** [comment]
Got it. But is it really necessary to remap for each cmd? Why not cache the mapping and only remap when necessary? Or is there any security issue behind it?

**Comment by jenswi-linaro** [comment]
The TA handling is designed primarily for TAs with a size less than perhaps 1MB. With that is the overhead of mapping it again each time acceptable, or it has at least never been considered as a problem.

Here's a good starting point:
https://github.com/OP-TEE/optee_os/blob/d0c232c90ff5d08555a598045cc02d69020d80c8/core/arch/arm/mm/core_mmu.c#L1848-L1874

**Comment by sunzc** [comment]
Thank you for the information!
