### ISSUE TITLE
Why do we need to register NS memory when dynamic shared memory is enabled?

### ISSUE THREAD

**Issue by super119** [OP-TEE/optee_os#4667]
My understanding is that, when using dynamic shared memory, the optee driver in Linux kernel allocates NS memory blocks and registers them to OPTEE. If so why does OPTEE try to find out the NS shared memory blocks when booting -- the function "discover_nsec_memory" does that. And if no memory blocks are registered, the dynamic shared memory functionality will be disabled:
```
#if defined(CFG_CORE_DYN_SHM)
        dyn_shm_en = core_mmu_nsec_ddr_is_defined();
        if (dyn_shm_en)
                args->a1 |= OPTEE_SMC_SEC_CAP_DYNAMIC_SHM;
#endif
```

**Comment by super119** [comment]
Checked the codes again and it seems that the only reason that we should register NS memory is to check whether the NS memory block which kernel provides is valid or not. That also explains why "register_dynamic_shm" is deprecated and "register_ddr" should be used instead -- the OPTEE needs to know the PA address space which kernel uses so that it can validate the address which kernel sends to it.
Is my understanding right here?

**Comment by lorc** [comment]
Yes. This is right. Kernel might trick OP-TEE to access addresses that are not non-secure memory. For example, this might be other secure memory regions, used by, say, ARM TF or MMIO regions.
 
Thus, we need to explicitly tell OP-TEE where non-secure RAM is located.

**Comment by super119** [comment]
Thanks a lot Iorc. Closing the issue.
