### ISSUE TITLE
Booting optee-os with VIRTUALIZATION on rk3399

### ISSUE THREAD

**Issue by banyefengchen** [OP-TEE/optee_os#4676]
I am trying to get op-tee with VIRTUALIZATION 3.13 to run on a ibox rk3399 board. So far:

- I have TF-A 2.4 on BL31
- OPTEE 3.13 on BL32
-

If CFG_VIRTUALIZATION is not set, it can boot optee-os. But if CFG_VIRTUALIZATION=y , optee will stop somewhere, the log :
 

```
Load uboot, ReadLba = 4000
Load OK, addr=0x200000, size=0xe94e4
RunBL31 0x40000 @ 106604 us
NOTICE:  BL31: v2.4(release):v2.4-602-g38b7c9c65-dirty
NOTICE:  BL31: Built : 02:16:02, May 21 2021
D/TC:0   get_aslr_seed:1361 Bad fdt: -9
D/TC:0   add_phys_mem:564 TEE_SHMEM_START type NSEC_SHM 0x0a400000 size 0x00400000
D/TC:0   add_phys_mem:564 TZDRAM_BASE type SEC_RAM_OVERALL 0x08400000 size 0x02000000
D/TC:0   add_phys_mem:564 VCORE_NEX_RW_PA type NEX_RAM_RW 0x08466000 size 0x00018000
D/TC:0   add_phys_mem:564 VCORE_UNPG_RW_PA type TEE_RAM_RO 0x0847e000 size 0x00182000
D/TC:0   add_phys_mem:564 VCORE_UNPG_RO_PA type TEE_RAM_RO 0x0844f000 size 0x00017000
D/TC:0   add_phys_mem:564 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x08400000 size 0x0004f000
D/TC:0   add_phys_mem:564 ROUNDDOWN((0xF8000000 + 0x06E00000), CORE_MMU_PGDIR_SIZE) type IO_SEC 0xfee00000 size 0x00200000
D/TC:0   add_phys_mem:564 ROUNDDOWN((0xF8000000 + 0x071A0000), CORE_MMU_PGDIR_SIZE) type IO_NSEC 0xff000000 size 0x00200000
D/TC:0   add_phys_mem:564 ROUNDDOWN((0xF8000000 + 0x07330000), CORE_MMU_PGDIR_SIZE) type IO_SEC 0xff200000 size 0x00200000
D/TC:0   add_va_space:604 type RES_VASPACE size 0x00a00000
D/TC:0   add_va_space:604 type SHM_VASPACE size 0x02000000
D/TC:0   dump_mmap_table:711 type TEE_RAM_RX   va 0x08400000..0x0844efff pa 0x08400000..0x0844efff size 0x0004f000 (smallpg)
D/TC:0   dump_mmap_table:711 type TEE_RAM_RO   va 0x0844f000..0x08465fff pa 0x0844f000..0x08465fff size 0x00017000 (smallpg)
D/TC:0   dump_mmap_table:711 type NEX_RAM_RW   va 0x08466000..0x0847dfff pa 0x08466000..0x0847dfff size 0x00018000 (smallpg)
D/TC:0   dump_mmap_table:711 type TEE_RAM_RO   va 0x0847e000..0x085fffff pa 0x0847e000..0x085fffff size 0x00182000 (smallpg)
D/TC:0   dump_mmap_table:711 type RES_VASPACE  va 0x08600000..0x08ffffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0   dump_mmap_table:711 type SHM_VASPACE  va 0x09000000..0x0affffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0   dump_mmap_table:711 type SEC_RAM_OVERALL va 0x0b000000..0x0cffffff pa 0x08400000..0x0a3fffff size 0x02000000 (pgdir)
D/TC:0   dump_mmap_table:711 type NSEC_SHM     va 0x0d000000..0x0d3fffff pa 0x0a400000..0x0a7fffff size 0x00400000 (pgdir)
D/TC:0   dump_mmap_table:711 type IO_SEC       va 0x0d400000..0x0d5fffff pa 0xfee00000..0xfeffffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:711 type IO_NSEC      va 0x0d600000..0x0d7fffff pa 0xff000000..0xff1fffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:711 type IO_SEC       va 0x0d800000..0x0d9fffff pa 0xff200000..0xff3fffff size 0x00200000 (pgdir)
D/TC:0   core_mmu_entry_to_finer_grained:753 xlat tables used 1 / 5
D/TC:0   core_mmu_entry_to_finer_grained:753 xlat tables used 2 / 5
```

How can i boot the optee-os while CFG_VIRTUALIZATION is set.

**Comment by banyefengchen** [comment]
the log optee-os without VIRTUALIZATION:
`Load uboot, ReadLba = 4000
Load OK, addr=0x200000, size=0xe94e4
RunBL31 0x40000 @ 115552 us
NOTICE:  BL31: v2.4(release):v2.4-602-g38b7c9c65-dirty
NOTICE:  BL31: Built : 02:16:02, May 21 2021
D/TC:0   get_aslr_seed:1361 Bad fdt: -9
D/TC:0   add_phys_mem:564 TEE_SHMEM_START type NSEC_SHM 0x0a400000 size 0x00400000
D/TC:0   add_phys_mem:564 TA_RAM_START type TA_RAM 0x08600000 size 0x01e00000
D/TC:0   add_phys_mem:564 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x08465000 size 0x0019b000
D/TC:0   add_phys_mem:564 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x08400000 size 0x00065000
D/TC:0   add_phys_mem:564 ROUNDDOWN((0xF8000000 + 0x06E00000), CORE_MMU_PGDIR_SIZE) type IO_SEC 0xfee00000 size 0x00200000
D/TC:0   add_phys_mem:564 ROUNDDOWN((0xF8000000 + 0x071A0000), CORE_MMU_PGDIR_SIZE) type IO_NSEC 0xff000000 size 0x00200000
D/TC:0   add_phys_mem:564 ROUNDDOWN((0xF8000000 + 0x07330000), CORE_MMU_PGDIR_SIZE) type IO_SEC 0xff200000 size 0x00200000
D/TC:0   add_va_space:604 type RES_VASPACE size 0x00a00000
D/TC:0   add_va_space:604 type SHM_VASPACE size 0x02000000
D/TC:0   dump_mmap_table:711 type TEE_RAM_RX   va 0x08400000..0x08464fff pa 0x08400000..0x08464fff size 0x00065000 (smallpg)
D/TC:0   dump_mmap_table:711 type TEE_RAM_RW   va 0x08465000..0x085fffff pa 0x08465000..0x085fffff size 0x0019b000 (smallpg)
D/TC:0   dump_mmap_table:711 type SHM_VASPACE  va 0x08600000..0x0a5fffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0   dump_mmap_table:711 type RES_VASPACE  va 0x0a600000..0x0affffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0   dump_mmap_table:711 type TA_RAM       va 0x0b000000..0x0cdfffff pa 0x08600000..0x0a3fffff size 0x01e00000 (pgdir)
D/TC:0   dump_mmap_table:711 type NSEC_SHM     va 0x0ce00000..0x0d1fffff pa 0x0a400000..0x0a7fffff size 0x00400000 (pgdir)
D/TC:0   dump_mmap_table:711 type IO_SEC       va 0x0d200000..0x0d3fffff pa 0xfee00000..0xfeffffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:711 type IO_NSEC      va 0x0d400000..0x0d5fffff pa 0xff000000..0xff1fffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:711 type IO_SEC       va 0x0d600000..0x0d7fffff pa 0xff200000..0xff3fffff size 0x00200000 (pgdir)
D/TC:0   core_mmu_entry_to_finer_grained:753 xlat tables used 1 / 5
D/TC:0   core_mmu_entry_to_finer_grained:753 xlat tables used 2 / 5
I/TC: 
I/TC: No non-secure external DT
D/TC:0 0 get_console_node_from_dt:70 No console directive from DTB
I/TC: OP-TEE version: 3.13.0-35-g2b632aed-dev (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #1 Fri May 21 09:01:31 UTC 2021 aarch64
I/TC: Primary CPU initializing
D/TC:0 0 boot_init_primary_late:1240 Executing at offset 0 with virtual load address 0x8400000
D/TC:0 0 call_initcalls:21 level 1 register_time_source()
D/TC:0 0 call_initcalls:21 level 1 teecore_init_pub_ram()
D/TC:0 0 call_initcalls:21 level 3 mobj_mapped_shm_init()
D/TC:0 0 mobj_mapped_shm_init:434 Shared memory address range: 8600000, a600000
D/TC:0 0 call_initcalls:21 level 3 platform_init()
D/TC:0 0 platform_secure_ddr_region:35 protecting region 1: 0x8400000-0xa400000
D/TC:0 0 call_initcalls:21 level 3 check_ta_store()
D/TC:0 0 check_ta_store:418 TA store: "Secure Storage TA"
D/TC:0 0 check_ta_store:418 TA store: "REE"
D/TC:0 0 call_initcalls:21 level 3 init_user_ta()
D/TC:0 0 call_initcalls:21 level 3 verify_pseudo_tas_conformance()
D/TC:0 0 call_initcalls:21 level 3 tee_cryp_init()
D/TC:0 0 call_initcalls:21 level 4 tee_fs_init_key_manager()
D/TC:0 0 call_initcalls:21 level 6 mobj_init()
D/TC:0 0 call_initcalls:21 level 6 default_mobj_init()
D/TC:0 0 call_finalcalls:40 level 1 release_external_dt()
I/TC: Primary CPU switching to normal world boot
`

**Comment by lorc** [comment]
Hi @banyefengchen,

You need to make some changes to this platform, so it can run with virtualization support enabled. At least you to mark with `__nex_bss` all global variables in `main.c`. Basically, you need changes similar to those commits:

https://github.com/OP-TEE/optee_os/commit/ea80a74dbcf0da9963c84dbe74e672c16e64a45d

https://github.com/OP-TEE/optee_os/commit/88d4bbda90da42e3006d9af1f25d0e51388773c8

**Comment by banyefengchen** [comment]
hi @lorc  
I marked all global variables with _nex_bss in  main.c : 

The change  is "static struct gic_data gic_data → static struct gic_data gic_data __nex_bss;"

But optee_os still stop at the same place.
Should I change other things?

this is the main.c :
'''
static struct gic_data gic_data __nex_bss;

#if defined(CFG_EARLY_CONSOLE)
static struct serial8250_uart_data early_console_data;
register_phys_mem_pgdir(MEM_AREA_IO_NSEC,
			CFG_EARLY_CONSOLE_BASE, CFG_EARLY_CONSOLE_SIZE);
#endif

register_phys_mem_pgdir(MEM_AREA_IO_SEC, GIC_BASE, GIC_SIZE);

void main_init_gic(void)
{
	vaddr_t gicc_base = 0;
	vaddr_t gicd_base = 0;

#if !defined(CFG_ARM_GICV3)
	gicc_base = (vaddr_t)phys_to_virt(GICC_BASE, MEM_AREA_IO_SEC);
	if (!gicc_base)
		panic();
#endif

	gicd_base = (vaddr_t)phys_to_virt(GICD_BASE, MEM_AREA_IO_SEC);
	if (!gicd_base)
		panic();

	/* Initialize GIC */
	gic_init(&gic_data, gicc_base, gicd_base);
	itr_init(&gic_data.chip);
}

void main_secondary_init_gic(void)
{
	gic_cpu_init(&gic_data);
}

void console_init(void)
{
#if defined(CFG_EARLY_CONSOLE)
	/*
	 * Console devices can vary a lot between devices and
	 * OP-TEE will switch to the DT-based real console later,
	 * based on DT-devices and the systems chosen node.
	 * So early console is only needed for early debugging.
	 */
	serial8250_uart_init(&early_console_data,
			     CFG_EARLY_CONSOLE_BASE,
			     CFG_EARLY_CONSOLE_CLK_IN_HZ,
			     CFG_EARLY_CONSOLE_BAUDRATE);
	register_serial_console(&early_console_data.chip);
#endif
}
'''

**Comment by a-daydream** [comment]
hi @lorc 
       I had the same problem while I  booting optee-os with VIRTUALIZATION on rk3399.
       Then as you said, I  mark with __nex_bss all global variables in main.c . 
       But I can not find  CFG_DRAM_BASE and CFG_DDR_SIZE in rk3399's reference material. So I can not register_dynamic_shm as this commit :[88d4bbd](https://github.com/OP-TEE/optee_os/commit/88d4bbda90da42e3006d9af1f25d0e51388773c8) 
       
     Then , I try to disable dynamic share memory by set CFG_CORE_DYN_SHM=n, but it does not work. I stop at
 `D/TC:1   tee_entry_exchange_capabilities:102 Dynamic shared memory is disabled
[    2.028198] optee: capabilities mismatch`
     I tried to find how to disable dynamic shared memory in linux tee driver , but I did not find how to disable it.
     So how can I fix this problem without konwing the CFG_DRAM_BASE  and CFG_DDR_SIZE ?

**Comment by lorc** [comment]
Hi. 

Sorry for late response. We had long holidays in here.

Well, you not need `CFG_DRAM_BASE` and `CFG_DDR_SIZE` exactly. What you really need is to tell OP-TEE ranges of non-secure DRAM on your board. This will allow you to use dynamic shared memory which is required if you want to use virtualization in OP-TEE.

On RCAR (https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-rcar/main.c#L49) for example, we have multiple definitions for all DRAM banks, which then are registered using `register_ddr` macro.

You can get this ranges for your board either from documentation or from Device Tree.

**Comment by a-daydream** [comment]
Hi @lorc ,
    Thanks for your response. I finally found DRAM ranges on my board from documentation and registered in the code.
    Then I finally booting optee os with virtualization  successfully.
    Thank you very much for you technical support.

**Comment by lorc** [comment]
Hi @a-daydream,

I glad to hear that you managed to make it work. May I ask you to create pull request with the changes? Looks like there is a high demand for virtualization on this platform :-)

**Comment by a-daydream** [comment]
Hi, @lorc 
     Sure, it's ok. I already created a pull request for this changes.
