### ISSUE TITLE
Running an application in S-EL0 before exiting to the non-secure world

### ISSUE THREAD

**Issue by i-nevo** [OP-TEE/optee_os#4677]
Hi, 
I would like to run an application in S-EL0 after OPTEE finished its initialization, but before exiting to normal (non-secure) world. 
From what I've read here, User TAs run in S-EL0, but must be loaded using a file-system that is available only after Rich-OS is up, while Static/Pseudo TAs can run before exiting to normal world for the first time but cannot run in S-EL0.
Is there a way to run my own application in S-EL0 before exiting to normal world for the first time?
Thanks in advance.

**Comment by jforissier** [comment]
Hi @i-nevo,

Yes, what you're looking for is called "early TA". See [here](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#early-ta).

**Comment by i-nevo** [comment]
Hi Jérôme,
Thanks for the fast response.
If I understood correctly the answers in #666, early TAs cannot run in user space (S-EL0). Can they?

**Comment by jenswi-linaro** [comment]
An early TA executes in S-EL0 so that part is covered. But in the current design they only do so when being called from normal world.

**Comment by jforissier** [comment]
#666 is a very old question (2016), back when early TA didn't exist.

**Comment by i-nevo** [comment]
And if called from ATF before normal world started, will the Early TA run in S-EL0 or in S-EL1?

**Comment by jforissier** [comment]
Early TAs **always** run at S-EL0.

**Comment by i-nevo** [comment]
Thanks.
