### ISSUE TITLE
xtest regression_4006 Failed when enable mbedtls with CRT 

### ISSUE THREAD

**Issue by lubing521** [OP-TEE/optee_os#4678]
I run xtest failed on qemu_v8 platform when  enable mbedtls with CRT in optee-os。

my config as below
```
user@host048-ubuntu-1804:~/work_opteeos/optee_os$ git diff ./
diff --git a/lib/libmbedtls/include/mbedtls_config_kernel.h b/lib/libmbedtls/include/mbedtls_config_kernel.h
index cd4d975..2e23646 100644
--- a/lib/libmbedtls/include/mbedtls_config_kernel.h
+++ b/lib/libmbedtls/include/mbedtls_config_kernel.h
@@ -82,7 +82,7 @@

 #if defined(CFG_CRYPTO_RSA)
 #define MBEDTLS_RSA_C
-#define MBEDTLS_RSA_NO_CRT
+//#define MBEDTLS_RSA_NO_CRT
 #endif

 #if defined(CFG_CRYPTO_RSA) || defined(CFG_CRYPTO_ECC)
diff --git a/mk/config.mk b/mk/config.mk
index ba06d3a..c12b3a0 100644
--- a/mk/config.mk
+++ b/mk/config.mk
@@ -21,7 +21,7 @@ CROSS_COMPILE ?= arm-linux-gnueabihf-
 CROSS_COMPILE32 ?= $(CROSS_COMPILE)
 CROSS_COMPILE64 ?= aarch64-linux-gnu-
 COMPILER ?= gcc
-
+CFG_WITH_STATS ?= y
 # For convenience
 ifdef CFLAGS
 CFLAGS32 ?= $(CFLAGS)
@@ -55,13 +55,13 @@ CFG_TEE_CORE_DEBUG ?= y
 # 2: error + warning
 # 3: error + warning + debug
 # 4: error + warning + debug + flow
-CFG_TEE_CORE_LOG_LEVEL ?= 1
+CFG_TEE_CORE_LOG_LEVEL ?= 3

 # TA log level
 # If user-mode library libutils.a is built with CFG_TEE_TA_LOG_LEVEL=0,
 # TA tracing is disabled regardless of the value of CFG_TEE_TA_LOG_LEVEL
 # when the TA is built.
-CFG_TEE_TA_LOG_LEVEL ?= 1
+CFG_TEE_TA_LOG_LEVEL ?= 3

 # TA enablement
 # When defined to "y", TA traces are output according to
@@ -78,7 +78,7 @@ CFG_TEE_CORE_TA_TRACE ?= y
 #   $ make CFG_TEE_TA_MALLOC_DEBUG=y CFG_TEE_TA_LOG_LEVEL=3
 # - To debug TEE core allocations: build OP-TEE with:
 #   $ make CFG_TEE_CORE_MALLOC_DEBUG=y CFG_TEE_CORE_LOG_LEVEL=3
-CFG_TEE_CORE_MALLOC_DEBUG ?= n
+CFG_TEE_CORE_MALLOC_DEBUG ?= y
 CFG_TEE_TA_MALLOC_DEBUG ?= n
 # Prints an error message and dumps the stack on failed memory allocations
 # using malloc() and friends.
@@ -579,8 +579,8 @@ CFG_TA_MBEDTLS_SELF_TEST ?= y
 # It's also possible to configure to use mbedtls instead of tomcrypt.
 # Then the variables should be assigned as "CFG_CRYPTOLIB_NAME=mbedtls" and
 # "CFG_CRYPTOLIB_DIR=lib/libmbedtls" respectively.
-CFG_CRYPTOLIB_NAME ?= tomcrypt
-CFG_CRYPTOLIB_DIR ?= core/lib/libtomcrypt
+CFG_CRYPTOLIB_NAME ?= mbedtls
+CFG_CRYPTOLIB_DIR ?= lib/libmbedtls

 # Not used since libmpa was removed. Force the value to catch build scripts
 # that would set = n.
```
Test log as below:
```
# 
# xtest 4006
Test ID: 4006
Run test suite with level=0

TEE test application started over default TEE instance
######################################################
#
# regression
#
######################################################
 
* regression_4006 Test TEE Internal API Asymmetric Cipher operations
o regression_4006.1 Asym Crypto case 0 algo 0x60000030 line 2728
regression_4000.c:3900: ta_crypt_cmd_asymmetric_decrypt(c, &session, op, ((void *)0), 0, out_enc, out_enc_size, out, &out_size) has an unexpected value: 0xffff0006 = TEEC_ERROR_BAD_PARAMETERS, expected 0x0 = TEEC_SUCCESS
  regression_4006.1 FAILED
  regression_4006 FAILED
+-----------------------------------------------------
Result of testsuite regression filtered by "4006":
regression_4006.1 FAILED first error at regression_4000.c:3900
regression_4006 FAILED
+-----------------------------------------------------
36 subtests of which 1 failed
1 test case of which 1 failed
91 test cases were skipped
TEE test application done!


D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
D/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
D/LD:  ldelf:134 Loading TS cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (REE)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0
D/LD:  ldelf:168 ELF (cb3e5ba0-adf1-11e0-998b-0002a5d5c51b) at 0x40079000
D/TC:? 0 tee_ta_invoke_command:823 Error: ffff0006 of 4
D/TC:? 0 tee_ta_close_session:512 csess 0x9a115530 id 1
D/TC:? 0 tee_ta_close_session:531 Destroy session
D/TC:? 0 destroy_context:308 Destroy TA ctx (0x9a1154a0)
```

**Comment by jenswi-linaro** [comment]
Yes?

**Comment by lubing521** [comment]
> Yes?

Is my problem not clearly described?

**Comment by jenswi-linaro** [comment]
It fails when you made a change to the MbedTLS configuration. Given the context it seems the easiest and most obvious solution is to back out that change.

**Comment by lubing521** [comment]
> It fails when you made a change to the MbedTLS configuration. Given the context it seems the easiest and most obvious solution is to back out that change.

Thank you for your prompt reply.
In my usage scenario，I need enable MbedTLS , and also support CRT.

enable CRT by config as below.

```
 #if defined(CFG_CRYPTO_RSA)
 #define MBEDTLS_RSA_C
-#define MBEDTLS_RSA_NO_CRT
+//#define MBEDTLS_RSA_NO_CRT
 #endif
```
but ,it does,t not work. how can I do ?

**Comment by jenswi-linaro** [comment]
I suppose you need to find out where it goes wrong. If the test case can work with CRT, etc.

**Comment by lubing521** [comment]
> I suppose you need to find out where it goes wrong. If the test case can work with CRT, etc.

Thank you for your suggestions.
I try find out and fix it.

**Comment by lubing521** [comment]
I found that xtest 4006 will test  without crt parameters  and with crt parameters.
tomcrypt and mbedtls in optee-os deal with diffrence ways. 

1. tomcrypt  will do rsa_exptmod  when xtest 4006  without crt parameters,so no affect after test process.
2. embedtls which enable CRT will check CRT parameters in function rsa_check_context, it will return MBEDTLS_ERR_RSA_BAD_INPUT_DATA when xtest 4006 without crt parameters, so xtest 4006 run fail.
@jenswi-linaro

**Comment by jenswi-linaro** [comment]
So it seems that if CRT is enabled for MbedTLS those parameters becomes always mandatory instead of just used if available.
That's likely the reason why CRT was disabled in the OP-TEE integration to begin with. In the GlobalPlatform TEE Internal Core API those parameters are optional and being compliant with the specification is a priority.

One way of dealing with this error could be to modify MbedTLS so makes the CRT parameters optional if compiled without `MBEDTLS_RSA_NO_CRT`. But I believe this should be handled upstream in the MbedTLS project first.

**Comment by lubing521** [comment]
> So it seems that if CRT is enabled for MbedTLS those parameters becomes always mandatory instead of just used if available.
> That's likely the reason why CRT was disabled in the OP-TEE integration to begin with. In the GlobalPlatform TEE Internal Core API those parameters are optional and being compliant with the specification is a priority.
> 
> One way of dealing with this error could be to modify MbedTLS so makes the CRT parameters optional if compiled without `MBEDTLS_RSA_NO_CRT`. But I believe this should be handled upstream in the MbedTLS project first.

Thanks your prompt reply.

Keymaster vts need  mbedtls witch CRT in optee-os if  we choose Mebdtls in optee-os for project.

Keymaste vts will run fail when enable mbedtls without CRT in optee -os. but tomcrypt OK.

**Comment by jenswi-linaro** [comment]
> Keymaster vts need mbedtls witch CRT in optee-os if we choose Mebdtls in optee-os for project.

It is a bit surprising since CRT is just an optimization if I recall correctly. Perhaps it's some test case that checks if invalid CRT parameters are rejected?

> Keymaste vts will run fail when enable mbedtls without CRT in optee -os. but tomcrypt OK.

That's good to know.

**Comment by lubing521** [comment]
> > Keymaster vts need mbedtls witch CRT in optee-os if we choose Mebdtls in optee-os for project.
> 
> It is a bit surprising since CRT is just an optimization if I recall correctly. Perhaps it's some test case that checks if invalid CRT parameters are rejected?
> 
> > Keymaste vts will run fail when enable mbedtls without CRT in optee -os. but tomcrypt OK.
> 
> That's good to know.

**Comment by lubing521** [comment]
https://github.com/OP-TEE/optee_os/pull/4698/files @jenswi-linaro 
This is my current solution.
