### ISSUE TITLE
Use MBEDTLS via Android Keymaster VTS

### ISSUE THREAD

**Issue by liushiwei007** [OP-TEE/optee_os#4681]
1), Because of business requirements, I use MBEDTLS as the encryption library
```
diff --git a/mk/config.mk b/mk/config.mk
-CFG_CRYPTOLIB_NAME ?= tomcrypt
-CFG_CRYPTOLIB_DIR ?= core/lib/libtomcrypt
+CFG_CRYPTOLIB_NAME ?= mbedtls
+CFG_CRYPTOLIB_DIR ?= lib/libmbedtls
```
2), This change will result in Andoird Keymaster VTS EncryptionOperationsTest, RsaPkcs1Success and EncryptionOperationsTest, RsaOaepSuccess probabilistic failure.The reason is that random modification of the ciphertext causes probabilistic failure of the decryption logic in judging the relationship between ciphertext and key size.
lib/libmbedtls/mbedtls/library/rsa.c
```
mbedtls_rsa_private
    MBEDTLS_MPI_CHK( mbedtls_mpi_read_binary( &T, input, ctx->len ) );
    if( mbedtls_mpi_cmp_mpi( &T, &ctx->N ) >= 0 )
    {
        ret = MBEDTLS_ERR_MPI_BAD_INPUT_DATA;
        goto cleanup;
    }
```
3), In the same scenario, the tomcrypt return value is eventually converted to TEE_ERROR_BAD_PARAMETERS,and then pass the test.But mbedtls converted to TEE_ERROR_BAD_STATE,this then causes panic to return the function TEE_AsymmetricDecrypt.

4), Return value conversion logic:
MBEDTLS_ERR_MPI_BAD_INPUT_DATA（mbedtls_rsa_private）--> MBEDTLS_ERR_RSA_PRIVATE_FAILED + MBEDTLS_ERR_MPI_BAD_INPUT_DATA （mbedtls_rsa_private）--> TEE_ERROR_BAD_STATE(get_tee_result ,lib/libmbedtls/core/rsa.c)

**Comment by liushiwei007** [comment]
I added a transformation relation to get_tee_result and analyzed the logic of other calls to mbedtls_rsa_private function. This modification will not affect the original logic. Is this an appropriate modification method?

diff --git a/lib/libmbedtls/core/rsa.c b/lib/libmbedtls/core/rsa.c
index 674985f3..0d302ad5 100644
--- a/lib/libmbedtls/core/rsa.c
+++ b/lib/libmbedtls/core/rsa.c
@@ -22,6 +22,8 @@ static TEE_Result get_tee_result(int lmd_res)
        switch (lmd_res) {
        case 0:
                return TEE_SUCCESS;
+       case MBEDTLS_ERR_RSA_PRIVATE_FAILED +
+                       MBEDTLS_ERR_MPI_BAD_INPUT_DATA:
        case MBEDTLS_ERR_RSA_BAD_INPUT_DATA:
        case MBEDTLS_ERR_RSA_INVALID_PADDING:
        case MBEDTLS_ERR_PK_TYPE_MISMATCH:

**Comment by vchong** [comment]
@liushiwei007 Are you using our keymaster TA or your own? Can't you handle this on the keymaster TA side? E.g. something like

```
if (error == TEE_ERROR_BAD_PARAMETERS || error == TEE_ERROR_BAD_STATE)
    return KM_ERROR_UNKNOWN_ERROR
```

**Comment by liushiwei007** [comment]
The process has not yet gone to the keymaster. It panic at Internal Core API
TEE_AsymmetricDecrypt
{
...
    res = _utee_asymm_operate(operation->state, ua, paramCount, srcData,
                  srcLen, destData, &dl);
    *destLen = dl;

    if (res != TEE_SUCCESS &&
        res != TEE_ERROR_SHORT_BUFFER &&
        res != TEE_ERROR_BAD_PARAMETERS)
        TEE_Panic(res);

...
}
if the error is TEE_ERROR_BAD_STATE ,it will Panic. so I need to change the error code to TEE_ERROR_BAD_PARAMETERS before returning to user mode(In the same scenario, the tomcrypt return value is TEE_ERROR_BAD_PARAMETERS, Just like you said, it change to KM_ERROR_UNKNOWN_ERROR at Keymaster TA ), But I'm not sure my modifications are appropriate

**Comment by vchong** [comment]
> The process has not yet gone to the keymaster. It panic at Internal Core API

Oops sorry I missed that.

> if the error is TEE_ERROR_BAD_STATE ,it will Panic. so I need to change the error code to TEE_ERROR_BAD_PARAMETERS before returning to user mode(In the same scenario, the tomcrypt return value is TEE_ERROR_BAD_PARAMETERS, 

Will need the core maintainers views on this. @jforissier @jenswi-linaro @etienne-lms what do you think? We have a situation here where calling into `optee_os` returns different/inconsistent error codes depending on whether `libtomcrypt` or `libmbedtls` is used. Is the above patch acceptable?

**Comment by jforissier** [comment]
> Will need the core maintainers views on this. @jforissier @jenswi-linaro @etienne-lms what do you think? We have a situation here where calling into `optee_os` returns different/inconsistent error codes depending on whether `libtomcrypt` or `libmbedtls` is used.

That's not a good thing...

> Is the above patch acceptable?

Looks OK to me, yes. @liushiwei007 can you please open a PR?

**Comment by liushiwei007** [comment]
Yes.@jforissier this is my PR https://github.com/OP-TEE/optee_os/pull/4684
