### ISSUE TITLE
Testing I2C Driver in i.MX8MQ

### ISSUE THREAD

**Issue by DevendraDevadiga** [OP-TEE/optee_os#4692]
Hi,
I am trying to work on I2C driver. I enabled the below driver (3.10 version I2C driver).
https://github.com/OP-TEE/optee_os/blob/3.10.0/core/drivers/imx_i2c.c
And written the CA,TA and PTA.

Below is log:

_iwg33m_8m:/ # optee_example_imx_i2c_test
D/TC:0 tee_ta_init_pseudo_ta_session:274 Lookup pseudo TA 0b10a472-b314-11eb-8529-0242ac130003
D/TC:0 tee_ta_init_pseudo_ta_session:286 Open imx_i2c_api_pta.pta
D/TC:0 tee_ta_init_pseudo_ta_session:300 imx_i2c_api_pta.pta : 0b10a472-b314-11eb-8529-0242ac130003
D/TC:0 create_ta:221 create entry point for pseudo TA "imx_i2c_api_pta.pta"
F/TC:0 plat_prng_add_jitter_entropy:74 plat_prng_add_jitter_entropy: 0x97C3
      Generic I2C TEST APPLICATION
         Press 1 for I2C INIT
         Press 2 for I2C SLAVE SET
         Press 3 for I2C READ
         Press 4 for I2C WRITE
         Press 5 for I2C XFER
         Press 6 to EXIT
         Please Enter The Option
1
         ENTER I2C BUS NUMBER :
2
         ENTER I2C BAUD RATE (in bps) :
400000
D/TC:0 invoke_command:248 command entry point for pseudo ta "imx_i2c_api_pta.pta"
E/TC:0 pta_imx_i2c_init:160 PTA: pta_imx_i2c_init start_

After sometimes system is rebooting. Attached the complete log for reference.

I want to understand what is the flow/step for initializing the I2C driver.
Below is my understanding:
1) "i2c_init" - driver_init(i2c_init);: As called in driver init, this function will execute first during OP-TEE boot.
Through CA,TA and PTA:-
2) Then call "imx_i2c_init()" by passing the bus id and baud rate (e.g. 400000).
3) Call "imx_i2c_probe" with bus id and slave address.
4) If read/write operation required, call "imx_i2c_write()" followed by "imx_i2c_read" by passing bus id, slave address, rx/tx buffere based on read/write operation and length of bytes to read/write.

Above mentioned steps are proper ?
When I tried above steps, getting hang in "imx_i2c_init()" function where write operation to IFDR register is done. 
i.e   "imx_i2c_init()"->"i2c_set_bus_speed()"->"i2c_set_prescaler()"->"i2c_io_write8(bid, IFDR, p->prescaler);"

Any idea why I am getting hang issue here? I need to do any configuration before calling this function? I disabled the I2C driver in Linux side.
Clock related any configuration I need to be done in OP-TEE side?

Thanks and Regards,
Devendra
 
[i2c_hang_issue.txt](https://github.com/OP-TEE/optee_os/files/6687039/i2c_hang_issue.txt)

**Comment by ldts** [comment]
hi  @DevendraDevadiga  what is your SoC?

**Comment by ldts** [comment]
btw what I suspect you might be experiencing is Linux disabling some clocks since you are not enabling it in the kernel.

**Comment by DevendraDevadiga** [comment]
> btw what I suspect you might be experiencing is Linux disabling some clocks since you are not enabling I2C in the kernel.

Yes, you are correct.
I had disabled the runtime pm suspend in Linux I2C driver and enabled the I2C driver in Linux.
_static struct platform_driver i2c_imx_driver = {
        .probe = i2c_imx_probe,
        .remove = i2c_imx_remove,
        .driver = {
                .name = DRIVER_NAME,
                **.pm = NULL,**
                .of_match_table = i2c_imx_dt_ids,
        },
        .id_table = imx_i2c_devtype,
};_

Now I am able to read/write the I2C data. In I2C driver I already added the support for i.MX8MQ.
With CA,TA and PTA, I2C read/write operation is working properly. Attached the test log.

Thank you for your support.
[i2c_working_after_pm_suspend_disable_in_linux.txt](https://github.com/OP-TEE/optee_os/files/6692457/i2c_working_after_pm_suspend_disable_in_linux.txt)

**Comment by DevendraDevadiga** [comment]
> hi @DevendraDevadiga what is your SoC?
> from the log it seems you are using iMX8MQ so the driver shouldnt even build.
> 
> if you are indeed using iMX8MQ use this driver instead
> https://github.com/foundriesio/optee_os/blob/3.10%2Bfio/core/drivers/imx_i2c.c
> 
> will try to find some time to post it upstream.
> 
> btw is your TA in U-boot or Linux? if you need OP-TEE i2c support in linux is much better to just use the rpc i2c service...you dont need the imx_i2c driver then (and since rpc_i2c integrates with Linux you dont need to disable the support in the kernel, on the contrary you need to enable it)

With respect to "rpc i2c service", how I can call I2C API ?
example I have a CA application, how I can call I2C read/write operation from my host/trusted application ?
Please can you provide me a sample example ?
