### ISSUE TITLE
Verify Digital SIgnature made from TA

### ISSUE THREAD

**Issue by rafagameiro** [OP-TEE/optee_os#4693]
Hi!

I'm trying to develop an Application that will send a nonce to a TA, the TA will generate an hash, append the nonce, and sign everything. After the sign, the TA sends back the signed digest and the CA should verify the signature and check if the sent nonce is the same as the one it send.

I already checked that OP-TEE OS offers functions to sign and verify the signature in the Secure World, but is it also possible to verify and sign signatures in the Normal World side?

Best Regards

**Comment by jenswi-linaro** [comment]
> I already checked that OP-TEE OS offers functions to sign and verify the signature in the Secure World, but is it also possible to verify and sign signatures in the Normal World side?

OP-TEE doesn't provide any such interfaces for Normal World. There are quite a few third party crypto libraries available which should be able to handle this.

**Comment by jforissier** [comment]
> > I already checked that OP-TEE OS offers functions to sign and verify the signature in the Secure World, but is it also possible to verify and sign signatures in the Normal World side?
> 
> OP-TEE doesn't provide any such interfaces for Normal World. There are quite a few third party crypto libraries available which should be able to handle this.

Yes, for example the `xtest` program uses OpenSSL for certificate verification, see [here](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_8100.c#L15-L20).

**Comment by rafagameiro** [comment]
Okok I was hoping OP-TEE would have some API for the sign and verification on the Normal World, but looking at it, it makes more sense to use third-party applications. Thank you for the answer!

Additionaly, if I may reuse this issue, would it be possible to explain, our provide some pointer that could explain, what is the TEE_Attribute defined in Asymmetric sign function, and how should I set one?

**Comment by jforissier** [comment]
> Additionaly, if I may reuse this issue, would it be possible to explain, our provide some pointer that could explain, what is the TEE_Attribute defined in Asymmetric sign function, and how should I set one?

See the GlobalPlatform TEE Internal Core API spec, table 6-8. In the OP-TEE implementation, that's only for the salt length when algorithm is `TEE_ALG_RSASSA_PKCS1_PSS_MGF1_XXX`.

**Comment by rafagameiro** [comment]
Ok ok in my case I'm trying to use RSA with another padding so I might not need it then. 
Either way I can still check the link out in case I get more questions.
Since I don't have nothing more to ask I'll close this issue.

Once again, Thank you for the help!
