### ISSUE TITLE
Questions regarding RPMB.

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#4696]
I am learning optee on QEMU v8.
https://github.com/OP-TEE/optee_os/issues/3555
I have seen the above question and expect that it will be possible to check the basic operation of RPMB in OPTEE system by setting RPMB_EMU := 1 in tee-supplicant.
Of course, CONFIG related to RPMB in OPTEE OS will be activated as follows.
CFG_RPMB_FS ?= y
CFG_RPMB_FS_DEV_ID ?= 12
CFG_RPMB_FS_RD_ENTRIES ?= 8
CFG_RPMB_FS_CACHE_ENTRIES ?= 0
CFG_RPMB_WRITE_KEY ?= y
                                                   
When building as above, I wonder if I can experience RPMB on QEMU.

Additionally, I have the following questions:
I'm looking at something related to KeyMaster from Linaro.
KeyMaster stores the secret key in TEE_STORAGE_PRIVATE at TA_CreateEntryPoint.
I think that the most ideal way to store the secret key is to store it in the fuse area that is accessible only in the secure world, but it is impossible if this is not supported, so I am researching various methods.

Checking rpmb.c, it seems that the RPMB KEY is injected into emmc using the command RPMB_MSG_TYPE_REQ_AUTH_KEY_PROGRAM.
I know that this key is OTP (One Time Programmable) same as fuse. I also recognized that this work should be carried out in the factory.

What I am curious about is whether the RPMB key injected from the factory can be loaded during actual operation.
If this is possible, I try to create the keymaster's secret key by doing some additional work after loading the RPMB key at TA_CreateEntryPoint.

What I am curious about is whether the RPMB key injected from the factory can be loaded during actual operation.
If this is possible, I try to create the keymaster's secret key by doing some additional work after loading the RPMB key at TA_CreateEntryPoint.

Each device must have a unique key, so I will try to use the RPMB key.
Of course, there is a way to inject each device's unique secret key into TEE_STORAGE_PRIVATE at the factory, but I am looking for a way to utilize RPMB this time.

As a last question, RPMB key seems to be called AUTH key. I wonder how AUTH is handled.
Maybe emmc RPMB FS calculates HMAC and saves it? If so, is HMAC calculation done in RPMB FS in emmc even when loading? 

BR,

**Comment by jforissier** [comment]
Hi @SangsubLim,

> I am learning optee on QEMU v8.
> #3555
> I have seen the above question and expect that it will be possible to check the basic operation of RPMB in OPTEE system by setting RPMB_EMU := 1 in tee-supplicant.

Yes, note it is the default value.

> Of course, CONFIG related to RPMB in OPTEE OS will be activated as follows.
> CFG_RPMB_FS ?= y

Yes

> CFG_RPMB_FS_DEV_ID ?= 12

Ignored when RPMB_EMU == 1

> CFG_RPMB_FS_RD_ENTRIES ?= 8
> CFG_RPMB_FS_CACHE_ENTRIES ?= 0

OK, those two are performance-related settings and are the default values.

> CFG_RPMB_WRITE_KEY ?= y

Yes

> 
> When building as above, I wonder if I can experience RPMB on QEMU.

Yes. The simplest method to run the RPMB code is use the QEMU (or QEMUv8) environment, then run
```
$ make -j10  CFG_REE_FS=n CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y run
...
Welcome to Buildroot, type root or test to login
buildroot login: test
$ xtest 6001
...
```

All tests in the range 6000- are storage tests. With `CFG_REE_FS=n CFG_RPMB_FS=y` you make sure the Normal World file system is not used for secure storage (only RPMB is used). Check the secure console for debug traces. If you want even more trace, you may use `CFG_RPMB_FS_DEBUG_DATA=y`.

> Additionally, I have the following questions:
> I'm looking at something related to KeyMaster from Linaro.
> KeyMaster stores the secret key in TEE_STORAGE_PRIVATE at TA_CreateEntryPoint.
> I think that the most ideal way to store the secret key is to store it in the fuse area that is accessible only in the secure world, but it is impossible if this is not supported, so I am researching various methods.

"Ideal" depends on your criteria ;-)

> 
> Checking rpmb.c, it seems that the RPMB KEY is injected into emmc using the command RPMB_MSG_TYPE_REQ_AUTH_KEY_PROGRAM.

Correct.

> I know that this key is OTP (One Time Programmable) same as fuse. I also recognized that this work should be carried out in the factory.

Correct.

> What I am curious about is whether the RPMB key injected from the factory can be loaded during actual operation.

No. More exactly: the key cannot be retrieved from the RPMB device. It is write-only. Therefore, OP-TEE needs to either store it securely somewhere, or derive it at boot time from a Root-of-Trust.

> If this is possible, I try to create the keymaster's secret key by doing some additional work after loading the RPMB key at TA_CreateEntryPoint.
> 
> What I am curious about is whether the RPMB key injected from the factory can be loaded during actual operation.
> If this is possible, I try to create the keymaster's secret key by doing some additional work after loading the RPMB key at TA_CreateEntryPoint.
> 
> Each device must have a unique key, so I will try to use the RPMB key.
> Of course, there is a way to inject each device's unique secret key into TEE_STORAGE_PRIVATE at the factory, but I am looking for a way to utilize RPMB this time.
> 
> As a last question, RPMB key seems to be called AUTH key. I wonder how AUTH is handled.
> Maybe emmc RPMB FS calculates HMAC and saves it? If so, is HMAC calculation done in RPMB FS in emmc even when loading?

As soon as a key is programmed into the RPMB partition, all commands sent by OP-TEE to the RPMB controller are signed, and similarly the responses sent by the controller to OP-TEE are signed too. There is a counter in each write operation to prevent replay attacks.

**Comment by SangsubLim** [comment]
@jforissier,
I think I will be able to take the direction of my analysis correctly because you have given me a clear answer and sufficient explanation.
I am learning a lot here and I am always grateful to you.
