### ISSUE TITLE
I2C4 Support missing in "imx_i2c" driver for i.MX8 case.

### ISSUE THREAD

**Issue by DevendraDevadiga** [OP-TEE/optee_os#4700]
Dear Sir,
I2C4 support is missing in above patch.
I think below changes we can add.

core/arch/arm/plat-imx/registers/imx8m.h

#if defined(CFG_MX8MM) || defined(CFG_MX8MQ)
...
**#define I2C4_BASE 0X30A50000**

core/drivers/imx_i2c.c
static struct io_pa_va i2c_bus[**4**] = {
....
**#if defined(I2C4_BASE)
[2] = { .pa = I2C4_BASE, },
#endif,**
};

static struct imx_i2c_clk {
..
} i2c_clk = {
.base.pa = CCM_BASE,
.i2c = { I2C_CLK_CGR(1), I2C_CLK_CGR(2), I2C_CLK_CGR(3), **I2C_CLK_CGR(4)**, },
};

static struct imx_i2c_mux {
struct io_pa_va base;
struct imx_i2c_mux_regs {
....
} i2c[ARRAY_SIZE(i2c_bus)];
} i2c_mux = {
.base.pa = IOMUXC_BASE,
.i2c = {...,
**.{ .scl_mux = I2C_MUX_SCL(4), .scl_cfg = I2C_CFG_SCL(4),
.scl_inp = I2C_INP_SCL(4), .sda_mux = I2C_MUX_SDA(4),
.sda_cfg = I2C_CFG_SDA(4), .sda_inp = I2C_INP_SDA(4), }** },
};

"core/arch/arm/plat-imx/registers/imx8m-crm.h"
#define CCM_CCRG_I2C1 23
#define CCM_CCRG_I2C2 24
#define CCM_CCRG_I2C3 25
**#define CCM_CCRG_I2C4 26**
#define I2C_CLK_CGR(__x) CCM_CCRG_I2C##__x

Thanks and Regards,
Devendra Devadiga

**Comment by jenswi-linaro** [comment]
Please create a pull request instead. You can add a "RFC" prefix to the title if it's more a start of a discussion than a final proposal.
