### ISSUE TITLE
How do I add programs to busybox?

### ISSUE THREAD

**Issue by friedrich12** [OP-TEE/optee_os#4707]
I am trying to add ssh to my optee build. How can I do this?

**Comment by jforissier** [comment]
Hello @friedrich12,

Which platform are you using? QEMU? Do you mean ssh client or server?
This could help: https://github.com/OP-TEE/build/commit/9c609007b049d066da620b675d27669c111eed90

**Comment by friedrich12** [comment]
STM32MP1 157 dk2

**Comment by jforissier** [comment]
OK then I think my suggestion still applies to https://github.com/OP-TEE/build/blob/master/stm32mp1.mk.

**Comment by friedrich12** [comment]
I also need iwconfig. Is that also included?

**Comment by friedrich12** [comment]
Thanks for the help. I just needed to add BR2_PACKAGE_IW=y to the list.
