### ISSUE TITLE
i met a build error.

### ISSUE THREAD

**Issue by ningzhenyu** [OP-TEE/optee_os#471]
I tried to run this in qemu and I followed your instructions.

STEP1  get source code using.

repo init -u https://github.com/OP-TEE/manifest.git -m default.xml
repo sync

STEP2  go to build directory and make toolchains.

STEP3 "make all run".

When I tried to execute the "make all run", a error was shown.
/bin/sh: 1: /home/zhenyu/devel/optee/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-gcc: not found.

I did make the toolchains, and I checked the directory "/home/zhenyu/devel/optee/build/../toolchains/aarch32/bin", file "arm-linux-gnueabihf-gcc" exists. And then I tried to execute the file directly, it shows as following:
bash: /home/zhenyu/devel/optee/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-gcc: No such file or directory

Would you please tell me how I can solve this?

**Comment by vchong** [comment]
Sounds like you're lacking 32-bit support on a 64-bit machine.
Assuming you're on Ubuntu, try:
$ sudo apt-get update
$ sudo dpkg --add-architecture i386
$ sudo apt-get install libc.so.6:i386

If that doesn't help,
$ ldd /home/zhenyu/devel/optee/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-gcc
You'll get a list of libraries/dependencies.
$ sudo apt-get install <all missing libraries/dependencies for above>

**Comment by ningzhenyu** [comment]
Yes, i'm on an ubuntu 14.04 64-bit machine.
Thanks for your reply. I tried both solutions, but they didn't works. According to your first solution, I found another solution by google.
sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0
sudo apt-get install lib32stdc++6

and these seem works, at least it is now compiling~

**Comment by pascal-brand-st-dev** [comment]
@ningzhenyu Can we close the issue?

**Comment by ningzhenyu** [comment]
@pascal-brand-st-dev Sure~
