### ISSUE TITLE
Regarding FEK

### ISSUE THREAD

**Issue by jingdlu** [OP-TEE/optee_os#4711]
I'd like to know why the length of FEK in OP-TEE is 128bits? With current implementation, we have to use AES GCM 128 or AES CBC 128 to encrypt/decrypt data.
If we expand FEK to 256bits, then we can use AES GCM 256. Can we change the length of FEK to 256bits?

Thanks

**Comment by jforissier** [comment]
Hello @jingdlu,

I suppose 128 bits were considered enough at the time the code was written. Do you think it is not safe now? It should be possible to change the FEK size. One thing to keep in mind though, is backwards compatibility. For such a change to reach upstream, we would need to stay compatible with existing secure storage.

**Comment by jingdlu** [comment]
Thanks @jforissier for your reply.

Yes, in most cases AES GCM 128 is deprecated and it's not enough safe.
I have changed FEK length to 256 and it seems that everything is OK. What do you mean by backwards compatibility? Does existing secure storage depend on 128 bits FEK?

Thanks

**Comment by jenswi-linaro** [comment]
> Yes, in most cases AES GCM 128 is deprecated and it's not enough safe.

Do you have any reference on this?

> I have changed FEK length to 256 and it seems that everything is OK. What do you mean by backwards compatibility? Does existing secure storage depend on 128 bits FEK?

There's a few fields in the file header that use the FEK size. So if you change the size of FEK you change those headers.

**Comment by jforissier** [comment]
> > Yes, in most cases AES GCM 128 is deprecated and it's not enough safe.
> 
> Do you have any reference on this?

Note, the GlobalPlatform Cryptographic Algorithm Recommendations v2.0 (GP_TEN_053) published this month (June 2021) mentions AES-CCM with AAD and AES-GCM with AAD in the "Recommended" and "Recommended PQC" categories.
- "Recommended" means "Should be used for future (near/long-term) products / specifications", with 128 bits of security or more.
- "Recommended PQC" means "Suggested for post quantum use" but key size is yet unspecified (TBD).

**Comment by jingdlu** [comment]
Thank you guys for your suggestion and information.
