### ISSUE TITLE
Error occurred during RSA key generation.

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#4714]
Hello,
I wrote the following RSA Key generation code in optee QEMU v7.

```
TEE_Result RSA_KEYGEN(uint32_t param_types,	TEE_Param params[4]) {
	const uint32_t key_size = 1024;
	TEE_ObjectHandle obj_h = TEE_HANDLE_NULL;
	TEE_Result res = TEE_SUCCESS;
	TEE_Attribute *attrs_in = NULL;
	uint32_t attrs_in_count = 1;
	const uint8_t pub_exp[] = { 0x03 };
	const uint8_t pub_exp[] = { 0x01, 0x00, 0x01};

	res = TEE_AllocateTransientObject(TEE_TYPE_RSA_KEYPAIR, key_size, &obj_h);

	if(res != TEE_SUCCESS) {
		DMSG("Failed TEE_AllocateTransientObject :: res[%x]", res);
		return res;
	}

	attrs_in = TEE_Malloc(sizeof(TEE_Attribute), TEE_MALLOC_FILL_ZERO);

	if (!attrs_in) {
		EMSG("Failed to allocate memory ");
		res = TEE_ERROR_OUT_OF_MEMORY;
		goto EXIT;
	}

	TEE_InitRefAttribute(attrs_in, TEE_ATTR_RSA_PUBLIC_EXPONENT, (void *) &pub_exp, sizeof(pub_exp));

	res = TEE_GenerateKey(obj_h, key_size, attrs_in, attrs_in_count);

	if (res != TEE_SUCCESS) {
		EMSG("Failed to generate key via TEE_GenerateKey, res = %x", res);
		goto EXIT;
	}

EXIT:
	if(attrs_in) {
		TEE_Free(attrs_in);
	}

	TEE_FreeTransientObject(obj_h);
	return res;
}
```

The following error occurs when executing the above code.

> E/TA:  RSA_KEYGEN:185 Failed to generate key via TEE_GenerateKey, res = ffff0006

After checking a bit more, it seems that TEE_ERROR_BAD_PARAMETERS occurred because there was a problem with the TEE_ATTR_RSA_PUBLIC_EXPONENT during the TEE_GenerateKey process.
In the code above, if pub_exp is set to 65537 as shown below, it works without error.
`const uint8_t pub_exp[] = { 0x01, 0x00, 0x01};`

Upon further inspection, I think it may be related to this.
https://github.com/OP-TEE/optee_os/pull/4507
https://github.com/OP-TEE/optee_os/commit/338b123ee66ca6694372564000226549c99806b1

I checked the NIST document written in the comment.
https://csrc.nist.gov/publications/detail/sp/800-56b/rev-2/final
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Br2.pdf

> 6.2.1 Definition of a Key Pair
> 2. The public exponent e shall be an odd integer that is selected prior to the generation of p and q such that:
> 65,537 ≤ e < 2^256

Judging from the above phrase, the value of "TEE_ATTR_RSA_PUBLIC_EXPONENT" works at 65537 and does not work when set to 3.

Am I understanding correctly?

**Comment by jforissier** [comment]
Hello @SangsubLim,

> Am I understanding correctly?

Yes. The GlobalPlatform TEE Internal Core API specification says "Key generation SHALL follow the rules defined in [NIST SP800-56B].", the check reflects this requirement.

**Comment by SangsubLim** [comment]
Hello @jforissier,

Thank you for your quick and easy-to-understand answers every time.
Have a good day.

**Comment by SangsubLim** [comment]
Hello @jforissier,

Sorry, but I have one more question.
When the above code is modified as shown below, the key is normally generated.
`const uint8_t pub_exp[] = { 0x01, 0x00, 0x01};`

However, if the following is done, "CRYPT_INVALID_ARG" error occurs in rsa_make_key().
`const uint8_t pub_exp[8] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01};`

Upon checking, the value of the parameter e in rsa_make_key is output as 0.


In the past, 0x00 could be added in front, but has this been changed?

`const uint8_t pub_exp[] = { 0x01, 0x00, 0x01};`
In the case of the above, the value of parameter e in rsa_make_key is output as 65537.

**Comment by jforissier** [comment]
> In the past, 0x00 could be added in front, but has this been changed?

I don't remember such as change and I think leading zeroes had better be accepted, because the GP spec doesn't say they are forbidden, but I'm not sure it is a real issue in practice.

**Comment by SangsubLim** [comment]
Thank you for answer. :)
