### ISSUE TITLE
Secure DRAM extension with OP-TEE Pager... out of memory error(TA only)

### ISSUE THREAD

**Issue by GrandChariot** [OP-TEE/optee_os#4718]
Hello

I am using STM32MP1 boards.
I tried to increase the Secure DRAM size of the OP-TEE with the Pager on.
I changed the address value of Secure DDR at conf.mk and the cache size at pgt_cache.h. I also changed ARM Trusted Firmware or U-Boot settings appropriately, and as a result, it was successfully booted. In addition, xtest was all successful.
However, if I try to run only user TA, it stops by throwing out of memory error (0xffff000c). Which code should I touch more? Is it because I didn't touch the tee_pager_add_um_area() function or something like that?

Below is an error message.

E/LD:  populate_segments:830 sys_map_zi
E/TC:? 0 ldelf_init_with_ldelf:121 ldelf failed with res: 0xffff000c

**Comment by jenswi-linaro** [comment]
If xtest passes then you're able to load small and midsize TAs. Perhaps you could start from one of the test TAs that already loads successfully?

**Comment by GrandChariot** [comment]
All other optee examples are well executed.

But the TA I want to implement is not small. It is probably bigger than mid-size.
The TA was originally allocated 6MB, but I wanted to use more than that, so I increased the Secure memory but failed.
With Pager turned off, Secure DRAM was successfully raised to 128 MiB, and the TA was successfully allocated and executed 80 MiB.
But it doesn't work well with the pager on.

**Comment by jenswi-linaro** [comment]
Paging an 80 MiB TA might be a bit much for the pager. Actually it's a bit much anyway since a TA is mapped again for each invoke and this may add a bit overhead than desired.
OP-TEE is designed for small TAs and works for mid-size TAs, but as sizes are increased one can expect different bottlenecks. Some of these bottlenecks might not be very hard to fix, but others may need a change in the software architecture.

**Comment by GrandChariot** [comment]
Thank you. I understand what you mean.
I think I can reduce the memory that my user TA uses until it is about 20MiB or less.
Is it possible to use this much? If possible, what should I do? 6MiB memory is still too small.

**Comment by jenswi-linaro** [comment]
If things works it's only a matter of tradeoff with performance. If you find the performance acceptable then I suppose there's nothing more to be done.

If not, then that's where the fun begins... I'm already aware of some undesired overhead when invoking a very large TA, this might be the biggest problem at the moment. With some work it should be possible to reuse old translation tables so they don't need to be initialized again, at bit like how translation tables covering paged regions are treated.

**Comment by GrandChariot** [comment]
Thank you for your answer. It was helpful to understand.

I definitely need a bigger Secure Memory than I do now. So I'll try to succeed in any way.

I will close this issue. Thank you!
