### ISSUE TITLE
storage a Cryptographic key as a persistent object

### ISSUE THREAD

**Issue by nicolaspippo** [OP-TEE/optee_os#472]
hi,

     In Chap. 5 of GPD_TEE_Internal_Core_API_Specification_v1.1.pdf, I noticed the sentence “A persistent object can be a Cryptographic Key Object, a Cryptographic Key-Pair Object, or a Data Object” and tried to store a key object (e.g. RSA key pair) using Persistent Object Functions. But it failed. 
     I’m wondering if the persistent storage of key objects was realized in optee and if so, how could I store a key using Persistent Object Functions and then use the key to encrypt and decrypt data. I would be pretty honored to get some hints or suggestion from u~

**Comment by pascal-brand-st-dev** [comment]
Basic persistent tests can be found in https://github.com/OP-TEE/optee_test/, in `xtest 6000`, with TA `storage`

Then, chapter 5 of the also states

    A transient object can be uninitialized, in which case it is an object container allocated with a 
    certain object type and maximum size but with no attributes. A transient object becomes initialized 
    when its attributes are populated. Note that persistent objects are always created initialized. This 
    means that when the TA wants to generate or derive a persistent key, it has to first use a transient 
    object then write the attributes of a transient object into a persistent object

**Comment by pascal-brand-st** [comment]
@nicolaspippo Can we close this issue? Without any answer, we will close it.

**Comment by vincent95905** [comment]
Hi,

I have nearly the same problem as nicolaspippo.
I generate an AES key and store it as a PersistentObject in data/tee
I'm trying to retrieve the key with ReadObjectData but it doesn't work.
I have already checked the documentation and try different things but nothing works.
I think I have the wrong approach to retrieve the key. Any idea ?

Thanks
