### ISSUE TITLE
OP-TEE for x86

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#4724]
We need hardware support i.e. ARM trusted firmware so that OPTEE can run.
Can we bring up OPTEE on an x86 architecture (AMD/INTEL) too?
If yes - what could be the approaches?

**Comment by jforissier** [comment]
I know of this project: https://github.com/op-tee-ia/optee_os which doesn't seem to be active anymore, but you may want to try and contact the authors.

**Comment by Hussain1811** [comment]
Seems to be some sort of mirror from the mainline OPTEE with more focus on x86. Thanks for the pointer.

Can we think of some hardware virtualization sort of implementations too?

**Comment by jforissier** [comment]
https://01.org/op-tee-ia/overview does mention virtualization. Basically, one VM for normal world and one for secure world if I got it right.

**Comment by Hussain1811** [comment]
Thanks for the information.
I shall close this issue.
