### ISSUE TITLE
TEE_MACCompareFinal fail with NIST test vector

### ISSUE THREAD

**Issue by josebeo2016** [OP-TEE/optee_os#4725]
1. I have a test vector which is:
```
Count = 94
Klen = 32 
Mlen = 48
Tlen = 10
Key = 7cfc086d10659d7cb9247208358dd82c03b8dbd8233223231df218e2448f4a79
Msg = a3af8f99703a601086c2a1ffe55fde4c2c4153dbff8d6601ab68743c0d50d021b0b3099535ba6c40f866ca3ff0df7c19
Mac = 9d713a1944b8eb649584
```
from NIST CMACAESgen256.rsp
After input the test vector into TEE_MACCompareFinal, I got TEE_ERROR_MAC_INVALID

I try to investigate TEE_MACCompareFinal() source code, It's seem like there is something wrong with the following code:

```
if (operation->operationState != TEE_OPERATION_STATE_ACTIVE) {
		res = TEE_ERROR_BAD_PARAMETERS;
		goto out;
	}

	res = TEE_MACComputeFinal(operation, message, messageLen, computed_mac,
				  &computed_mac_size);
	if (res != TEE_SUCCESS)
		goto out;

	if (computed_mac_size != macLen) {
		res = TEE_ERROR_MAC_INVALID;
		goto out;
	}

	if (consttime_memcmp(mac, computed_mac, computed_mac_size) != 0) {
		res = TEE_ERROR_MAC_INVALID;
		goto out;
	}
```

The function compares the computed_mac_size to the macLen before comparing the memory of the two buffers. In our case, if we input the custom mac's length, e.g., Tlen = 10, then the function always return invalid.

**Comment by jenswi-linaro** [comment]
The `TEE_MACComputeFinal()` expects a certain length of the computed MAC, not a user supplied one. This has been our interpretation of the GlobalPlatform specification and as far as I know this is also what the GlobalPlatform tests expect. The GP tests are more about the API than the algorithms so it has quite few test vectors for some algorithms and may perhaps have some blind spots.

It might be worth checking with GP if the behaviour you're looking for is expected to be supported by the TEE Internal Core API Specification.

**Comment by josebeo2016** [comment]
> The `TEE_MACComputeFinal()` expects a certain length of the computed MAC, not a user supplied one. This has been our interpretation of the GlobalPlatform specification and as far as I know this is also what the GlobalPlatform tests expect. The GP tests are more about the API than the algorithms so it has quite few test vectors for some algorithms and may perhaps have some blind spots.
> 
> It might be worth checking with GP if the behaviour you're looking for is expected to be supported by the TEE Internal Core API Specification.

Thank you for your fast reply.
Following the NIST test vector, the verifying mac length (TLen) sometimes could be less than the full size of the computed mac length by the API. It will be nice if we can make it more flexible in checking the _macLen_. For instance, if the _macLen_ less than the computed_mac_size then compare in range of the 0->_macLen_.

**Comment by jenswi-linaro** [comment]
> Following the NIST test vector, the verifying mac length (TLen) sometimes could be less than the full size of the computed mac length by the API. It will be nice if we can make it more flexible in checking the _macLen_. For instance, if the _macLen_ less than the computed_mac_size then compare in range of the 0->_macLen_.

This is a standardized API so we must be careful to not break with the standard when adding flexibility. That's why I think we should check with GP first. @jforissier, what do you think?

**Comment by vchong** [comment]
Fwiw I had to do the same thing recently when implementing one of the PKCS11 mechanisms so as a workaround called `TEE_MACComputeFinal(..full len)` and `TEE_MemCompare(..partial length)` directly in the TA itself without the length comparison.

**Comment by vchong** [comment]
> Fwiw I had to do the same thing recently when implementing one of the PKCS11 mechanisms so as a workaround called `TEE_MACComputeFinal(..full len)` and `TEE_MemCompare(..partial length)` directly in the TA itself without the length comparison.

There is a length check though to make sure it's not 0 or greater than the hash size.

**Comment by josebeo2016** [comment]
> This is a standardized API so we must be careful to not break with the standard when adding flexibility. That's why I think we should check with GP first. @jforissier, what do you think?

TEE Internal Core API Specification v1.2.5 does not mention any rules for the macLen should be.

> > Fwiw I had to do the same thing recently when implementing one of the PKCS11 mechanisms so as a workaround called `TEE_MACComputeFinal(..full len)` and `TEE_MemCompare(..partial length)` directly in the TA itself without the length comparison.
> 
> There is a length check though to make sure it's not 0 or greater than the hash size.

You're right,  `0 < macLen <= computed_mac_size `
And I did the same method for temporary solution.

**Comment by jforissier** [comment]
> > Following the NIST test vector, the verifying mac length (TLen) sometimes could be less than the full size of the computed mac length by the API. It will be nice if we can make it more flexible in checking the _macLen_. For instance, if the _macLen_ less than the computed_mac_size then compare in range of the 0->_macLen_.
> 
> This is a standardized API so we must be careful to not break with the standard when adding flexibility. That's why I think we should check with GP first. @jforissier, what do you think?

I like the idea of giving a bit more flexibility, and the GP spec doesn't seem to forbid that (and I found no specific test in the GP suite either), but I agree we need to be careful. I will try to get feedback from GP.

**Comment by jenswi-linaro** [comment]
Thanks @jforissier

**Comment by jforissier** [comment]
For reference, the test case mentioned above can be found on the NIST page [Cryptographic Algorithm Validation Program](https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/CAVP-TESTING-BLOCK-CIPHER-MODES), section "Test Vectors", in the Zip file [cmactestvectors.zip](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/mac/cmactestvectors.zip) [CMAC Test Vectors (SP 800-38B)], file CMACGenAES256.rsp.

**Comment by jforissier** [comment]
I have proposed a resolution for this, although I am still waiting for feedback from the GP TEE Spec WG. Frankly, I think the current wording of the spec does allow what I propose, and the text that describes the panic case: "if input data exceeds the maximum length for the algorithm" is a hint that less than that maximum length should be allowed (otherwise they probably would have written "is different from").

**Comment by josebeo2016** [comment]
> I have proposed a resolution for this, although I am still waiting for feedback from the GP TEE Spec WG. Frankly, I think the current wording of the spec does allow what I propose, and the text that describes the panic case: "if input data exceeds the maximum length for the algorithm" is a hint that less than that maximum length should be allowed (otherwise they probably would have written "is different from").

Then the implementation of TEE_MACCompareFinal may have an unintended rule: invalid when the length is different (not mentioned about panic)

**Comment by jforissier** [comment]
So, ultimately the answer to this question is "not supported", "TA needs to deal with it", see https://github.com/OP-TEE/optee_os/pull/4735#issuecomment-876298090.
