### ISSUE TITLE
Question: how to use Early TA?

### ISSUE THREAD

**Issue by JensVankeirsbilck** [OP-TEE/optee_os#4729]
I'm pretty new to OPTEE. I understand that it's normal functionality is for non-secure applications to request secure services, called TAs. I'm more interested in independent time-triggered TAs, which might be coming in a later version OPTEE according to #4601 .

Currently I'm investigating early TAs and how to use them. I was able to build OPTEE for Qemuv7 and to configure the Hello World TA from OPTEE-examples as an early TA. From the secure terminal, I see that OPTEE finds the .elf file as an early TA. I just don't understand now how to use this early TA. I can't seem to find information on this. How do I now launch / call / use the early TA?

**Comment by etienne-lms** [comment]
An early TA is a standard TA but that its binary image is found inside OP-TEE core image, not externally to secure world (in which case TA binary image would need to be authenticated). Therefore, a client application can invoke as early TA the same way as any client application invoke a TA: open a session towards TA UUID and invoke command in the session context.

Your case is slightly different as you expect OP-TEE secure world calls the TA from its own, not from a non-secure client. There no such existing examples, sorry. However, technically, OP-TEE core could create a TA execution env from its own and call the TA, without non-secure initiating the session.

Yet remember that OP-TEE secure world is currently scheduled from the non-secure world. So your TA, even is not invoked from non-secure, will rely on non-secure for its scheduling. Maybe your TA could be initially invoked from a non-secure entity (from boot stage or from Linux initialization), if not needed prior non-secure world initialization.

**Comment by JensVankeirsbilck** [comment]
Thanks for your answers @etienne-lms .
If I understand you correctly: I could open a session using the TA UUID and invoke a command from within the OP-TEE core, but this would be to no avail, as the command will not be executed, since it needs to be scheduled by the non-secure world, which has no idea the command has been invoked.

I'll investigate invoking the TA from boot stage or linux initialization.

**Comment by etienne-lms** [comment]
Core could invoke a TA command on his own and have it properly executed. For example, if the TA uses no resource that rely on some RPC service, then OP-TEE can even run the TA even before non-secure world has booted.

Once non-secure world has booted, OP-TEE threads are exclusively assigned when non-secure invokes OP-TEE with a threaded context. This is how non-secure scheduler can reschedule a OP-TEE secure thread.

**Comment by rafagameiro** [comment]
Hi everyone!

I have been trying to create an Early TA in order for the TA execute a function at system startup. I already got the building process of an Early TA given this comment https://github.com/OP-TEE/optee_os/issues/3305#issuecomment-536439735, but I got confused with the last step. Since the Early TA is part of OP-TEE core internal files, it means that every time I want to rebuild my TA I'll have to rebuild OP-TEE , and if I have a board, flush the new OP-TEE build into it, right?

Best Regards

**Comment by jenswi-linaro** [comment]
> Since the Early TA is part of OP-TEE core internal files, it means that every time I want to rebuild my TA I'll have to rebuild OP-TEE , and if I have a board, flush the new OP-TEE build into it, right?

Correct

**Comment by rafagameiro** [comment]
> > Since the Early TA is part of OP-TEE core internal files, it means that every time I want to rebuild my TA I'll have to rebuild OP-TEE , and if I have a board, flush the new OP-TEE build into it, right?
> 
> Correct

If that's the case, for example, I'm trying to run my Early TA on rpi3. 
So far I followed the commands I mentioned that are on the comment https://github.com/OP-TEE/optee_os/issues/3305#issuecomment-536439735 and the OP-TEE OS successfully regenerated the files. But now I was wondering if there was any make command, on build or another directory, that would update the out directory that has all the files that are needed to be flushed into rpi3.

**Comment by jenswi-linaro** [comment]
Then you should have the TA embedded in the OP-TEE binary, so just flash that one as usual and you should be good to go.

**Comment by rafagameiro** [comment]
I don't I got what you meant.
After I run the `make EARLY_TA_PATHS="/path/to/ta.stripped.elf"` its true that in the OP-TEE OS directory, on a specific directory I get a .c and .o files of my TA, but I don't know what to do with them. I assume that I should place them somewhere in the filesystem of my RPI3, and then put my TA as usual in the TA default location? If yes, where should be the location where I have to put the .c and .o files?

**Comment by jforissier** [comment]
Have you read https://github.com/OP-TEE/optee_os/blob/master/mk/config.mk#L305? The .o is linked inside tee.elf.

**Comment by rafagameiro** [comment]
> Have you read https://github.com/OP-TEE/optee_os/blob/master/mk/config.mk#L305? The .o is linked inside tee.elf.

I read the config file, but I think I did not understand that the tee.elf contained my TA .o file. But it seems I'm still doing something wrong.

I tried to generate the OPTEE-OS and updated the boot and root FS, and then flush them to the RPI3 memory, but during the boot process I don't see my TA being loaded, and when I try to call some command it says that the TA does not exists. As previously said, I did the commands that are in this comment https://github.com/OP-TEE/optee_os/issues/3305#issuecomment-536439735, but maybe I might need more commands?

**Comment by jforissier** [comment]
> The .o is linked inside tee.elf.

Sorry I should have written "the TA is linked inside tee.elf", because at this stage the .o doesn't matter, it is the whole executable (`<uuid>.stripped.elf`) given as `EARLY_TA_PATHS=path/to/<uuid>.stripped.elf` that is used.
Indeed your TA should be visible during the boot like so (early_ta_init line below):

```
[Example on QEMU platform]
$ make -j10
$ make -j10 EARLY_TA_PATHS=../out-br/build/optee_examples_ext-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.stripped.elf run
[On secure console]
I/TC: OP-TEE version: 3.14.0-8-g49dbb9ef (gcc version 10.2.1 20201103 (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16))) #3 Thu Jul 29 12:57:42 UTC 2021 arm
I/TC: Primary CPU initializing
D/TC:0 0 boot_init_primary_late:1245 Executing at offset 0x715b8000 with virtual load address 0x7f6b8000
D/TC:0 0 call_initcalls:21 level 1 register_time_source()
D/TC:0 0 call_initcalls:21 level 1 teecore_init_pub_ram()
D/TC:0 0 call_initcalls:21 level 3 mobj_mapped_shm_init()
D/TC:0 0 mobj_mapped_shm_init:439 Shared memory address range: 7f900000, 81900000
D/TC:0 0 call_initcalls:21 level 3 check_ta_store()
D/TC:0 0 check_ta_store:408 TA store: "early TA"
D/TC:0 0 check_ta_store:408 TA store: "Secure Storage TA"
D/TC:0 0 check_ta_store:408 TA store: "REE"
D/TC:0 0 call_initcalls:21 level 3 early_ta_init()
D/TC:0 0 early_ta_init:56 Early TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b size 29691 (compressed, uncompressed 75492)
```

If the early_ta_init line is not there, check the build log of the "make EARLY_TA_PATHS=..." command. There should be a line similar to this:
```
  GEN     out/arm/core/early_ta_8aaaf200-2450-11e4-abe2-0002a5d5c51b.c
  CC      out/arm/core/early_ta_8aaaf200-2450-11e4-abe2-0002a5d5c51b.o
```
(with the UUID of your TA of course). If you don't have it, double check the path you give as EARLY_TA_PATHS.

**Comment by rafagameiro** [comment]
Exactly, I would expect that while running OP-TEE I would see some line like the early_ta_init, but I did not find it.
However, while I was running the "make EARLY_TA_PATHS=..." command I did see the GEN and CC lines indicating that my TA was indeed processed.
That's why I can assume that I might have missed some intermediate or final step that prevented my OP-TEE build from launching my Early TA

**Comment by rafagameiro** [comment]
> It looks like you're not running the TEE binary that you expect (flashing issue?). Check the build timestamp in the `OP-TEE version` line perhaps.

I would need to check that in what file? 
Regarding the TEE binary file, tee.elf specifically, in the Makefile I don't see it being use, but again I might be wrong and it's in fact being called on another sub file

**Comment by jforissier** [comment]
Several binaries are created from `tee.elf` (the `*.bin` files). They are usually combined with other firmware (TF-A etc.) before being flashed onto the board. I don't know much about the RPi3 specifics, the doc is here: https://optee.readthedocs.io/en/latest/building/devices/rpi3.html.
The OP-TEE version and build timestamp are shown at boot time on the secure console, like so:
```
I/TC: OP-TEE version: 3.14.0-8-g49dbb9ef (gcc version 10.2.1 20201103 (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16))) #3 Thu Jul 29 12:57:42 UTC 2021 arm
```

**Comment by rafagameiro** [comment]
> Several binaries are created from `tee.elf` (the `*.bin` files). They are usually combined with other firmware (TF-A etc.) before being flashed onto the board. I don't know much about the RPi3 specifics, the doc is here: https://optee.readthedocs.io/en/latest/building/devices/rpi3.html.

Ahh okok if that's the case then its ok, because that's exactly what the build process is doing. I uses some of the .bin files to combine with the TF-A and then I flush it to the board.

> The OP-TEE version and build timestamp are shown at boot time on the secure console, like so:
> 
> ```
> I/TC: OP-TEE version: 3.14.0-8-g49dbb9ef (gcc version 10.2.1 20201103 (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16))) #3 Thu Jul 29 12:57:42 UTC 2021 arm
> ```

Unfortunately I could not find the OP-TEE Version line, but instead I found the Linux Version, though I don't know if finding one and not the other is good or bad:

```
[    0.000000] Linux version 5.4.83-v8 (edge@thinkpad) (gcc version 10.2.1 20201103 (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16))) #1 SMP PREEMPT Tue Jul 27 18:57:33 WEST 2021
```

**Comment by rafagameiro** [comment]
Sorry I did not catch the entire execution so I could not find the OP-TEE Version, but after running it again I found it:
```
I/TC: OP-TEE version: 3.14.0-9-g2d603acd (gcc version 10.2.1 20201103 (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16))) #2 Tue Jul 27 18:40:56 UTC 2021 aarch64
```

**Comment by rafagameiro** [comment]
Also, regarding this execution snippet: 
> ```
> [Example on QEMU platform]
> $ make -j10
> $ make -j10 EARLY_TA_PATHS=../out-br/build/optee_examples_ext-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.stripped.elf run
> [On secure console]
> I/TC: OP-TEE version: 3.14.0-8-g49dbb9ef (gcc version 10.2.1 20201103 (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16))) #3 Thu Jul 29 12:57:42 UTC 2021 arm
> I/TC: Primary CPU initializing
> D/TC:0 0 boot_init_primary_late:1245 Executing at offset 0x715b8000 with virtual load address 0x7f6b8000
> D/TC:0 0 call_initcalls:21 level 1 register_time_source()
> D/TC:0 0 call_initcalls:21 level 1 teecore_init_pub_ram()
> D/TC:0 0 call_initcalls:21 level 3 mobj_mapped_shm_init()
> D/TC:0 0 mobj_mapped_shm_init:439 Shared memory address range: 7f900000, 81900000
> D/TC:0 0 call_initcalls:21 level 3 check_ta_store()
> D/TC:0 0 check_ta_store:408 TA store: "early TA"
> D/TC:0 0 check_ta_store:408 TA store: "Secure Storage TA"
> D/TC:0 0 check_ta_store:408 TA store: "REE"
> D/TC:0 0 call_initcalls:21 level 3 early_ta_init()
> D/TC:0 0 early_ta_init:56 Early TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b size 29691 (compressed, uncompressed 75492)
> ```

It seems my OP-TEE only presents this lines:
```
D/TC:0 0 call_initcalls:21 level 3 check_ta_store()
D/TC:0 0 check_ta_store:408 TA store: "Secure Storage TA"
D/TC:0 0 check_ta_store:408 TA store: "REE"
```
and it does present nothing about the Early TA, is it possible that I did not setup the OP-TEE to search of Early TAs, or something similar?

**Comment by jforissier** [comment]
> Sorry I did not catch the entire execution so I could not find the OP-TEE Version, but after running it again I found it:
> 
> ```
> I/TC: OP-TEE version: 3.14.0-9-g2d603acd (gcc version 10.2.1 20201103 (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16))) #2 Tue Jul 27 18:40:56 UTC 2021 aarch64
> ```

Then you can compare this with the output of e.g.,:
```
$ strings out/arm/core/tee.elf | grep Toolchain
```
...which should show the same version string, confirming that the TEE binary flashed on your board is indeed the one you recompiled.

**Comment by jforissier** [comment]
> Also, regarding this execution snippet:
> 
> > ```
> > [Example on QEMU platform]
> > $ make -j10
> > $ make -j10 EARLY_TA_PATHS=../out-br/build/optee_examples_ext-1.0/hello_world/ta/out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.stripped.elf run
> > [On secure console]
> > I/TC: OP-TEE version: 3.14.0-8-g49dbb9ef (gcc version 10.2.1 20201103 (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16))) #3 Thu Jul 29 12:57:42 UTC 2021 arm
> > I/TC: Primary CPU initializing
> > D/TC:0 0 boot_init_primary_late:1245 Executing at offset 0x715b8000 with virtual load address 0x7f6b8000
> > D/TC:0 0 call_initcalls:21 level 1 register_time_source()
> > D/TC:0 0 call_initcalls:21 level 1 teecore_init_pub_ram()
> > D/TC:0 0 call_initcalls:21 level 3 mobj_mapped_shm_init()
> > D/TC:0 0 mobj_mapped_shm_init:439 Shared memory address range: 7f900000, 81900000
> > D/TC:0 0 call_initcalls:21 level 3 check_ta_store()
> > D/TC:0 0 check_ta_store:408 TA store: "early TA"
> > D/TC:0 0 check_ta_store:408 TA store: "Secure Storage TA"
> > D/TC:0 0 check_ta_store:408 TA store: "REE"
> > D/TC:0 0 call_initcalls:21 level 3 early_ta_init()
> > D/TC:0 0 early_ta_init:56 Early TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b size 29691 (compressed, uncompressed 75492)
> > ```
> 
> It seems my OP-TEE only presents this lines:
> 
> ```
> D/TC:0 0 call_initcalls:21 level 3 check_ta_store()
> D/TC:0 0 check_ta_store:408 TA store: "Secure Storage TA"
> D/TC:0 0 check_ta_store:408 TA store: "REE"
> ```
> 
> and it does present nothing about the Early TA, is it possible that I did not setup the OP-TEE to search of Early TAs, or something similar?

That's is really weird, providing EARLY_TA_PATHS should automatically enable the early TA support code (`CFG_EARLY_TA=y`). Can you please check if this feature is enabled in your build?
```
$ grep EARLY_TA out/arm/conf.mk
CFG_EARLY_TA=y
CFG_EARLY_TA_COMPRESS=y
```

**Comment by rafagameiro** [comment]
> That's is really weird, providing EARLY_TA_PATHS should automatically enable the early TA support code (`CFG_EARLY_TA=y`). Can you please check if this feature is enabled in your build?
> 
> ```
> $ grep EARLY_TA out/arm/conf.mk
> CFG_EARLY_TA=y
> CFG_EARLY_TA_COMPRESS=y
> ```

I printed it and the output is the same you have, so I would assume the Early TA would execute

**Comment by rafagameiro** [comment]
@jforissier I don't if it is related to, but I also have an hikey960 board and I tried to see if I could builde the OP-TEE with my Early TAs. I run the ```make optee-os CFG_EARLY_TA=y```and it worked, just fine. Obviously I know that this command is not enough to build the entire system, but it was one of the steps in the comment I already mentioned (https://github.com/OP-TEE/optee_os/issues/3305#issuecomment-536439735). 
However, when I tried to run the exact same command on RPI3 build I got this error:

```
/home/edge/Documents/Programming/thesis/optee_rpi3/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: out/arm/core/kernel/early_ta.o: in function `early_ta_open':
/home/edge/Documents/Programming/thesis/optee_rpi3/optee_os/core/kernel/early_ta.c:32: undefined reference to `emb_ts_open'
/home/edge/Documents/Programming/thesis/optee_rpi3/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: out/arm/core/kernel/early_ta.o:(.scattered_array_ta_stores_1_2+0x10): undefined reference to `emb_ts_get_size'
/home/edge/Documents/Programming/thesis/optee_rpi3/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: out/arm/core/kernel/early_ta.o:(.scattered_array_ta_stores_1_2+0x18): undefined reference to `emb_ts_get_tag'
/home/edge/Documents/Programming/thesis/optee_rpi3/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: out/arm/core/kernel/early_ta.o:(.scattered_array_ta_stores_1_2+0x20): undefined reference to `emb_ts_read'
/home/edge/Documents/Programming/thesis/optee_rpi3/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: out/arm/core/kernel/early_ta.o:(.scattered_array_ta_stores_1_2+0x28): undefined reference to `emb_ts_close'
```
Note that in this case I re-downloaded the OP-TEE RPI3 repository.
I don't know if it is directly related with the fact that the system did not seem to run or try to detect any Early TA, but at least is a difference between the two building process.

**Comment by jforissier** [comment]
@jellesels-arm is this correct? https://github.com/OP-TEE/optee_os/blob/3.14.0/mk/config.mk#L326-L331

Shouldn't it be a dependency like this?
```diff
  ifneq ($(EARLY_TA_PATHS)$(CFG_IN_TREE_EARLY_TAS),)
  $(call force,CFG_EARLY_TA,y)
- $(call force,CFG_EMBEDDED_TS,y)
  else
  CFG_EARLY_TA ?= n
  endif
+ ifeq ($(CFG_EARLY_TA),y)
+ $(call force,CFG_EMBEDDED_TS,y)
+ endif
```

**Comment by jellesels-arm** [comment]
Wouldn't this result in the same? Or is there a situation where CFG_EARLY_TA can be set without EARLY_TA_PATHS or CFG_IN_TREE_EARLY_TAS being set?

________________________________________

**Comment by jforissier** [comment]
> Wouldn't this result in the same? Or is there a situation where CFG_EARLY_TA can be set without EARLY_TA_PATHS or CFG_IN_TREE_EARLY_TAS being set?

Yes, this situation pushed a bit further: https://github.com/OP-TEE/optee_os/blob/3.14.0/mk/config.mk#L315-L318. That is if you run `make CFG_EARLY_TA=y`, not only building the `ta_dev_kit` but also the TEE core. It still makes sense because many core object files can then be generated and not compiled again in the second round of building (when EARLY_TA_PATHS is given).

Even if this use case isn't terribly convincing, there is still a logical dependency between `CFG_EARLY_TA` and `CFG_EMBEDDED_TS` if I understand correctly, as shown by the link error.

**Comment by jellesels-arm** [comment]
Okay makes sense, let me create a PR for this

**Comment by jforissier** [comment]
@jellesels-arm thanks!

**Comment by jellesels-arm** [comment]
@jforissier The PR is here: https://github.com/OP-TEE/optee_os/pull/4782
