### ISSUE TITLE
Permanent Storage in External Memory 

### ISSUE THREAD

**Issue by Chengde3** [OP-TEE/optee_os#473]
i want to save the data and key derived permanently but after rebooting, they disappeared. 
    (Function used: TEE_CreatePersistentObject)
    i suppose it was because optee saved these data in RAM.
    So is there a method to save the key or other data in external memory?
    would be glad to receive your reply, lots of thx

**Comment by pascal-brand-st-dev** [comment]
A persistent object remains after a DestroyContext().

I suspect that your rootfs is not saved after reboot. This is the behavior on qemu. To check this, you can simply try, outside the TEE:

    touch toto.txt
    reboot
    check toto.txt is still there

**Comment by jamescfkung** [comment]
@Chengde3 What does external memory refer to? DDR, flash device or other storage device?
OP-TEE store persistent objects in linux file system. Path is /data/tee/. If you mount /data on a flash device, I think all persistent objects should be there after reboot.

**Comment by Chengde3** [comment]
@jamescfkung    we use hikey board and could u please tell how to mount /data on a flash device or emmc? i'm not quite clear about that

**Comment by jamescfkung** [comment]
@Chengde3 I'm not familiar with Hikey, but I think in general, you can change /etc/fstab to do that automatically when system is booting. This is a frequently asked question by Linux users, you might be able to get more useful information by google.

**Comment by pascal-brand-st** [comment]
@Chengde3 Can we close the issue?

**Comment by Chengde3** [comment]
@pascal-brand-st ok, thx~
