### ISSUE TITLE
Question about mobj ref_count

### ISSUE THREAD

**Issue by ZheTingLiu** [OP-TEE/optee_os#4747]
Hello,

I am confusing about some code flow. 
1. Line 151 ```mobj_with_fobj_alloc``` will set ref_count of mobj to 1.
2. In ```vm_map_pad```,  if code fail at line 278 and go to line 329, it will do ```mobj_put```.
3. Then Line 157 does ```mobj_put``` again,

After setp 2, the ref_count will be 0. Step 3 decreases it again, does it assert in ```refcount_dec```?
https://github.com/OP-TEE/optee_os/blob/203ee23d005b2cec2f21b5de334c5a246be32599/core/pta/system.c#L151-L161
https://github.com/OP-TEE/optee_os/blob/d5ad7ccf818dc8516f2abe9e3262955c91a03627/core/mm/vm.c#L278-L280
https://github.com/OP-TEE/optee_os/blob/d5ad7ccf818dc8516f2abe9e3262955c91a03627/core/mm/vm.c#L329-L332

**Comment by etienne-lms** [comment]
Hello @ZTingLiu,
I think you're right.
`mobj_put(reg->mobj)` in _vm.c_ line 330 balances `mobj_get(mobj);` at line 287 and therefore should not be called when `mobj_get_cattr(mobj, &cattr)` fails.

Do you want to create a P-R to fix this issue?

**Comment by ZheTingLiu** [comment]
Hi @etienne-lms,

I have created a P-R #4750 .
