### ISSUE TITLE
Implementation for LED Status changing when switch from Non-Secure World to Secure World and vice versa.

### ISSUE THREAD

**Issue by DevendraDevadiga** [OP-TEE/optee_os#4748]
Dear Team,

I have to implement LED status changing when switching Non-Secure to Secure or vice versa.
The LED can only be accessed by secure world. This we can achieve by configuring CSU for that specific GPIO.
But which is the best place to add LED toggle code in OP-TEE?
Currently I am working on i.MX8MQ which is Armv8 and Arm-Trusted-Firmware is used.

In Armv7 case I know the NS bit clear will happen in this place:
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/sm/sm_a32.S#L176

But in Armv8 case where this NS bit toggle happening? Is in Arm-Trusted-Firmware ? Please can you refer me source file and line number as above ?

As in Armv7, for Armv8 case also this NS bit toggling may happen in assembly code (.S file). 

If I want change LED status just after the NS bit clear, can we implement a c function for LED status toggle and call like below:

_**_bl	toggle_secure_led_**_
Is this a proper way ?

Similarly in what all other places/files I need to add this function like FIQ entry, IRQ entry? 

I want to know in source code, where switching from Secure world to Non-Secure world is happening i.e set the NS bit and I want to OFF the LED status there.

Like this LED indication feature is implemented in any of refernce board's OP-TEE source like Hikey, Raspberry ?

Why OP-TEE can't provide this option in orginal code like with a macro CFG_SECURE_LED_STATUS and if enabled just after NS bit clear, this function should call ?
In .S file:
_**_bl	toggle_secure_led_**_

In board file like "core/arch/arm/plat-imx/main.c"
_void toggle_secure_led()
{
#ifdef SECURE_LED_STATUS
/* do LED toggle */
#endif
}_

Thanks and Regards,
Devendra

**Comment by lorc** [comment]
Hi @DevendraDevadiga ,

In case of ARMv8 NS bit is toggled by ARM Trusted Firmware. As EL3 is always secure, you can toggle your LED in entry/exit points of ARM TF. If you want to toggle LED only when OP-TEE is running, you can do this either from ARM TF side (take a look at `opteed`) or in the OP-TEE entry/exit points.

Besides, don't forget that your SoC have multiple cores. so there can be cases when multiple cores change secure state simultaneously. You need reference counter or multiple LEDs to correctly display secure state of all cores. Also, bear in mind that  in most cases time spent in secure state is very short (I'd say it always shorter than 10ms), so human eye may not perceive such short LED pulses.

**Comment by sunnybird** [comment]
hi @DevendraDevadiga .
you can add your LED driver into ATF( 
arm-trusted-firmware).the tagged code should add at opteed_smc_handler(https://github.com/ARM-software/arm-trusted-firmware/blob/master/services/spd/opteed/opteed_main.c)
