### ISSUE TITLE
optee_linuxdriver porting

### ISSUE THREAD

**Issue by LIKEJMJJ** [OP-TEE/optee_os#4752]
I want to port optee_linuxdriver into linux4.9.37 which can support optee_os version >= 3.13.0 ,how can I achive it

**Comment by sunnybird** [comment]
the linux 4.14.240 has support optee driver code.
so, you need copy driver/tee to your linux codebase. then build it . 
if you can find /dev/tee0 and /dev/teepriv0 at your device, it means the optee driver is ok.
