### ISSUE TITLE
Question: How to access OP-TEE private key

### ISSUE THREAD

**Issue by rafagameiro** [OP-TEE/optee_os#4755]
Hi!

I'm trying to access the default_ta.pem file that contains a RSA private, so that I can use it in my sign operation.
I noticed that something similar (more related to certificate file access) was achieved in OP-TEE Tests [1] regression 81xx
I would like to know if it is possible for my TA, at runtime, to read the content of the default_ta.pem file.
If yes, could you please provide with some example so that I could understand the process and do it on my side?

Best Regards

[1] https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_8100.c

**Comment by jenswi-linaro** [comment]
No, this is generally not possible. Allowing any TA to access the private key it was signed with would normally be a security problem.

**Comment by rafagameiro** [comment]
Ok I understand then, thank you!

Also, if I may reuse this issue, @jenswi-linaro, I would like to know if you could give me your opinion regarding my problem.
I'm trying to have a TA that has private key in the Secure World, and a public key in the Normal World so that I could do sign/verify operations between worlds. The ideal, would consist in using a key, or used by OP-TEE itself, or derived/authenticated by OP-TEE, since I'm considering the OP-TEE to be the only secure component in my all setup.

Since I can't use the private RSA key, stored in default_ta.pem, another option (although not that secure) would be to have the keypair statically stored in an header file and load it when I needed. But as I mentioned, it's not the most safe solution, and I would not have guarantees that the used key would be considered safe by OP-TEE itself.
Another option that I can see, is to use the TEE_GenerateKey() function to generate a key pair and then store it in the secure storage. In this case, I would not have the public key already in the Normal World, and I would have to send it to Normal World, at least once.
Considering this, is there any option that would allow me to generate/derive/use an authenticated keypair by OP-TEE throughout my TA execution?

Once again, thank you for your time.

Best Regards

**Comment by jenswi-linaro** [comment]
Depending on the details in your use case you may be able to use the following:
`TEE_GenerateKey()` can be used to generate a key which can then be stored in secure storage so it's always available to the TA. I suppose normal world could request the public part of the key.

This will give a key that is static once the system has been initialized.

**Comment by rafagameiro** [comment]
yes, considering the fact that having a statically defined keypair in the header file is not the best practice, I think the option where I get a keypair generated by OP-TEE might be the best option, at least for now. 

But if that's the case @jenswi-linaro, at the moment it is not possible to generate/have a key that has some authentication from OP-TEE, and before runtime its public key is in the Normal World right?

**Comment by jenswi-linaro** [comment]
> But if that's the case @jenswi-linaro, at the moment it is not possible to generate/have a key that has some authentication from OP-TEE, and before runtime its public key is in the Normal World right?

Do you mean before the system has booted for the first time? If it's in later boots you could have saved the public key somewhere in normal world when the key was generated if needed.

**Comment by rafagameiro** [comment]
Yes, I was hoping I could have already a public key in the Normal World before the first boot, and a private key in the Secure World. And ideally, the keypair was generated or obtained through OP-TEE, which would give it some form of trustability since it was created by, what I consider given this TA development, a Trusted Component.

However, since it does not seem to have any method to do what I intend to at the moment, I guess my best option would be to generate a keypair on the first boot and store it on Secure Storage. Then, all subsequent boots would use the keypair to the sign operation and verification.

**Comment by rafagameiro** [comment]
@jenswi-linaro I'm sorry for the extra question, but I'm facing a problem regarding your sugestion.

I followed your indication and I'm trying to generate a keypair using TEE_GenerateKey() and then I'm sending to the Normal World the public Exponent and Modulus to recreate the public key. The public key recreation, as the verify function, are being done in Java since I faced some problems while trying to link openssl libraries to my CA. I'm passing my public exponent as a normal number and my modulus encoded in base64.

My problem is, when I recreate the key and try to verify the signature is says the signature is invalid. I can only assume the problem is related to how I'm sending the public exponent and modulus, since I have this key as a PEM file in the Normal World, and when loading it into memory and verifying the signature it works just fine. 

So my question would be, in what format should I send to the Normal World the public exponent and modulus?

**Comment by jforissier** [comment]
`TEE_ATTR_RSA_MODULUS` and `TEE_ATTR_RSA_EXPONENT` are of `bignum` type (as per the GP specification) so `TEE_GetObjectBufferAttribute()` will return them in big-endian binary format. If your Java interface can easily manipulate this format (which I suppose is the case) then you should probably send them this way to Normal World.

**Comment by rafagameiro** [comment]
yes yes I'm using those same attribute constants and the function to extract the parameters from the public key. 
Regarding the public exponent I don't think any problem can come from it since I'm getting in the Normal World the expected result.
 
Now about the modulus, as I said I'm using base64 to encode the retrieved from value from the TEE_GetObjectBufferAttribute() function and them decode it on the Java interface. With what you are saying, I assume that I should instead use its original big-endian binary format and then try to properly read it the Normal World, so that I could recreate the public key successfully?

**Comment by jforissier** [comment]
> yes yes I'm using those same attribute constants and the function to extract the parameters from the public key.
> Regarding the public exponent I don't think any problem can come from it since I'm getting in the Normal World the expected result.

OK
 
> Now about the modulus, as I said I'm using base64 to encode the retrieved from value from the TEE_GetObjectBufferAttribute() function and them decode it on the Java interface. With what you are saying, I assume that I should instead use its original big-endian binary format and then try to properly read it the Normal World, so that I could recreate the public key successfully?

Both should work, but base64 adds nothing in this case. I would recommend you dump and compare the modulus in the TA and in the Java code that receives it and especially check endianness.

**Comment by rafagameiro** [comment]
> > Now about the modulus, as I said I'm using base64 to encode the retrieved from value from the TEE_GetObjectBufferAttribute() function and them decode it on the Java interface. With what you are saying, I assume that I should instead use its original big-endian binary format and then try to properly read it the Normal World, so that I could recreate the public key successfully?
> 
> Both should work, but base64 adds nothing in this case. I would recommend you dump and compare the modulus in the TA and in the Java code that receives it and especially check endianness.

I just used base64 but I was afraid I could lose some bytes while trying to send the information between worlds. If you say that base64 adds nothing then I can remove that conversion. And also, since I'm currently not checking the endianness of the received modulus, that might be related to the problem I'm facing. I'll try to check that and then comment here what were my results.

**Comment by rafagameiro** [comment]
I found the solution!
Either you use base64 or not to move the data between worlds, when inside the Java Program execution to successfully load the modulus you have to use the BigInteger constructor that receives the sign-magnitude as an argument:
`new BigInteger(-1, modulus);`

Since this issue was solve I'll close it.
Thank you very much for the assistance!
