### ISSUE TITLE
Problem in refcount with atomic_cas_uint

### ISSUE THREAD

**Issue by i-nevo** [OP-TEE/optee_os#4760]
Hi,
I have a strange problem when trying to run the Hello-World test TA: During the initialization of the TA session, there is a call to `refcount_inc` (file refcount.c) and this call never returns. There is a loop in this routine which turns out to be infinite since the call to `atomic_cas_uint` always returns false. Adding prints to this routine I noticed that although initially both `r->val` & `oval` have the same value (1), after the first call to `atomic_cas_uint` (which returns false) the value of `oval` changes to something garbage-like and from this point on the loop never ends.
I suspect that something is wrong with the implementation of `atomic_cas_uint`. It actually calls `__atomic_compare_exchange_n` which, if I understand correctly, has compiler dependent implementation.
I use gcc-arm-8.2-2019.01-x86_64-aarch64-linux-gnu as my cross-compiler, is there a problem with it? Should I use another cross-compiler?
Could it be a mismatch between the compiler and the ARM version I use? I use Cortex-A75, but if I set the CPU Architecture to cortex-a75 (in cortex-armv8-0.mk) compilation fails with error message "unrecognized argument in option '-mcpu=cortex-a75'" so I use cortex-a73 which is the closest supported CPU Architecture. If that's the problem, how can I set the required architecture to Cortex-A75?

Thanks in advance for your help.

**Comment by jenswi-linaro** [comment]
I would have checked the generated machine code of `refcount_inc()` to see that the instructions for `atomic_cas_uint()` makes sense. It is very likely that they do. As far as I know the Arm version shouldn't matter here.

Myself I've never experienced a problem like the one you're describing with this function. Are you running on some new platform? Perhaps there's something special with the memory in which OP-TEE is executing?

**Comment by i-nevo** [comment]
Hi,
Thanks for the fast response.
I looked in the assembler code generated from refcount_inc, and I didn't see there anything suspicious. I run the OPTEE on a proprietary new platform, but I don't think it has some special properties. The memory used by the OPTEE is just normal SRAM.
I add the obj_dump of the refcount_inc in case someone will see something interesting there:
```
00000180000148c4 <refcount_inc>:
        return __compiler_atomic_load(p);
 180000148c4:   b9400001        ldr     w1, [x0]
        unsigned int nval;
        unsigned int oval = atomic_load_uint(&r->val);

        while (true) {
                nval = oval + 1;

 180000148c8:   11000423        add     w3, w1, #0x1
                /* r->val is 0, we can't do anything more. */
                if (!oval)
                        return false;
 180000148cc:   34000141        cbz     w1, 180000148f4 <refcount_inc+0x30>
        return __compiler_compare_and_swap(p, oval, nval);
 180000148d0:   885ffc02        ldaxr   w2, [x0]
 180000148d4:   6b01005f        cmp     w2, w1
 180000148d8:   54000061        b.ne    180000148e4 <refcount_inc+0x20>  // b.any
 180000148dc:   88047c03        stxr    w4, w3, [x0]
 180000148e0:   7100009f        cmp     w4, #0x0
 180000148e4:   2a0203e1        mov     w1, w2

                if (atomic_cas_uint(&r->val, &oval, nval))
                        return true;
 180000148e8:   54ffff01        b.ne    180000148c8 <refcount_inc+0x4>  // b.any
                /*
 180000148ec:   52800020        mov     w0, #0x1                        // #1
                 * At this point atomic_cas_uint() has updated oval to the
                 * current r->val.
                 */
        }
}
 180000148f0:   d65f03c0        ret
 180000148f4:   52800000        mov     w0, #0x0                        // #0
 180000148f8:   17fffffe        b       180000148f0 <refcount_inc+0x2c>
```

**Comment by jenswi-linaro** [comment]
These exclusive instructions requires an exclusive monitor implemented for the memory. Perhaps there's some quirk with the SRAM? It's not entirely unheard of.

**Comment by i-nevo** [comment]
Thanks.
It indeed appears to be a bug in the SRAM implementation on the virtual environment that emulates our platform.
I close this issue.
