### ISSUE TITLE
How to enlarge the ta ram more than 4G?

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#4763]
I want to process big data but I found that tee ram + ta ram <= 4G. How to enlarge the size of the ram.

**Comment by jenswi-linaro** [comment]
We have this pull request https://github.com/OP-TEE/optee_os/pull/4762 .
That should take care of virtual memory address space part of the problem.
There's one more problem and that's how to map that much memory. You'll need to tweak the value of `PGT_CACHE_SIZE` and probably the size of the heap and `MAX_XLAT_TABLES` too. You're likely to run into some other limitation too.

Please bear in mind that OP-TEE is designed to be small and to keep a somewhat small attack surface. This is part of the security strategy.

**Comment by YogzZ** [comment]
Thank you for your suggestion~
