### ISSUE TITLE
OP-TEE SKS

### ISSUE THREAD

**Issue by rafagameiro** [OP-TEE/optee_os#4765]
Greetings,

I have come across a presentation Linaro did some years ago [1]. I have been trying to create an TA that generates an attestation proof of a set of components developed by me. To ensure trustability over this attestation service, I thought I could use this presented SKS to possibly generate a keypair, and perform the sign operation that I need to generate the attestation proof.

I searched for this SKS on OP-TEE OS, OP-TEE Client , and OP-TEE Tests, but I did not found any TA that explicitly said it was the SKS that was referred in the said presentation. The only possible comparisons I found were the TEE_AsymmetricSignDigest and other functions, derived from GP internal API, and the TA PKCS#11.

My Question is, does this SKS still exists, and if yes, where could I find it.
If not, does one of the above mentioned libraries is a SKS "replacement"? If yes, which one?

Best regards

[1] https://pt.slideshare.net/linaroorg/hkg18402-build-secure-key-management-services-in-optee

**Comment by ruchi393** [comment]
SKS is now called PKCS#11 and is available as PKCS#11 TA. 

You can also find more details in https://connect.linaro.org/resources/lvc21/lvc21-215/

**Comment by rafagameiro** [comment]
Thank you very much for the fast reply!

Since at the moment my setup consists in a AOSP+OP-TEE, and in the link you provided the presentation was in this year I was starting to assume the PKCS#11 TA did not exists in my system. However, after I check the files I found the TA.
Since it has been already an year since the last update to the AOSP+OP-TEE repository, is it possible that some major changes occurred, or the TA is identically the same?

**Comment by vchong** [comment]
I think you're using the 3.13 release of OP-TEE? The TA will be from that release as well since it's part of optee_os.

**Comment by rafagameiro** [comment]
Actually I checked now and it seems I'm using the 3.12.0 version, so it explains why I already have the pkcs11 TA.
Would it be advisable to upgrade to version 3.13?

**Comment by rafagameiro** [comment]
I checked the different version, and it seems the 3.13 has much more functions that the version I had in my system setup. So it might be better to update it.
Also, I noticed by reading the TA files, but at the moment the only asymmetric keypair that can be generated is for EC algorithms right?

**Comment by ruchi393** [comment]
Yes, for RSA , PR is in review

**Comment by rafagameiro** [comment]
Ok Thank you very much, that's all I needed to know for now. 
Since at the moment the TA does not support keypair generation for RSA it might be better to use the functions based on GP internal API.
