### ISSUE TITLE
Question: Identity Mapping of Arbitrary RAM

### ISSUE THREAD

**Issue by joroec** [OP-TEE/optee_os#4767]
Hi,
First of all, thanks for the great open-source project, which fosters open TEE systems programming! I enjoy it a lot.

A somewhat special question has arisen for me and I am curious what the fastest solution would look like, so maybe you can help.

I want to **identity** map an arbitrary region of RAM to the OP-TEE kernel. Using a PTA and the API provided by `arch/arm/mm/core_mmu.c` I was able to map some portions of the NS-DRAM to high virtual addresses chosen by OP-TEE. However, a mapping that is not an identity mapping is not suitable in my case.

Thus, I wonder how to identity map a portion of RAM. I assume one would need to insert a new first-level page table and a second-level page table, since the virtual addresses might not be covered by O-TEE's mapping yet.
As I cannot find an API to add new page tables or insert new identity maps, I ask you to elaborate on which steps are required to achieve such a mapping with the least effort.

Thank you very much!

Best regards,
Jonas

**Comment by jenswi-linaro** [comment]
You have a few corner cases to overcome. In case CFG_CORE_ASLR is enabled you may have a conflict with the present mapping of OP-TEE core. You may also have a conflict with the selected user mode range. You have already been looking in one of the right files for helper functions. You may find some more in arch/arm/mm/core_mmu_lpae.c or core/arch/arm/mm/core_mmu_v7.c. But I'm afraid you must be ready to do quite a bit yourself too.
