### ISSUE TITLE
Increase TA/TEE RAM size 

### ISSUE THREAD

**Issue by DevendraDevadiga** [OP-TEE/optee_os#4768]
Dear Team,

We had implemented secure display and used 1920x1080 resolution display.
For CA and TA, refered the below test app:
https://github.com/jforissier/secvideo_demo/tree/master/app

I am able to write the test.bin (Image with 2MB) successfully and oly 1/4th of Display is covered by LCD (Becuase 8MB image is required in our case we used 1920x1080 resolution display. (1920*1080*32/8).

But when I tried to write the image file with 8MB, app will be able to write the image till 2MB and after that crash is happening.

Below is the crash log:

_F/TC:? 0 trace_syscall:132 syscall #71 (syscall_framebuffer_update)
D/TC:3 0 abort_handler:524 [abort] abort in User mode (TA will panic)
E/TC:? 0 
E/TC:? 0 User TA undef-abort at address 0x4005c334
E/TC:? 0  esr 0x02000000  ttbr0 0x20000bc4a0060   ttbr1 0x00000000   cidr 0x0
E/TC:? 0  cpu #3          cpsr 0x40000100
E/TC:? 0  x0  000000004005ee4a x1  0000000000000720
E/TC:? 0  x2  0000000000000003 x3  0000000000000001
E/TC:? 0  x4  000000004005f2fc x5  0000000000000000
E/TC:? 0  x6  ffffffffffffffff x7  0000000040014e60
E/TC:? 0  x8  0000000000000047 x9  0000000000000001
E/TC:? 0  x10 0000000000000000 x11 0000000000000000
E/TC:? 0  x12 0000000000000000 x13 0000000040014f80
E/TC:? 0  x14 0000000000000000 x15 0000000000000020
E/TC:? 0  x16 00000000bc4309a4 x17 0000000000000000
E/TC:? 0  x18 0000000000000000 x19 0000000040014ea0
E/TC:? 0  x20 0000000000224000 x21 0000000040068440
E/TC:? 0  x22 0000000040014ea0 x23 0000000000004000
E/TC:? 0  x24 0000000000000001 x25 0000000000000000
E/TC:? 0  x26 0000000000000000 x27 0000000000000000
E/TC:? 0  x28 0000000000000000 x29 0000000040014e20
E/TC:? 0  x30 0000000040053148 elr 000000004005c334
E/TC:? 0  sp_el0 0000000040014e20
D/TC:3 0 abort_handler:524 [abort] abort in User mode (TA will panic)
E/TC:? 0 dump_state_ldelf_dbg:415 ldelf dump function panicked
E/TC:? 0 
E/TC:? 0 User TA undef-abort at address 0x4000aaa4
E/TC:? 0  esr 0x02000000  ttbr0 0x20000bc4a0060   ttbr1 0x00000000   cidr 0x0
E/TC:? 0  cpu #3          cpsr 0x00000100
E/TC:? 0  x0  000000004000c66b x1  000000004000c65e
E/TC:? 0  x2  0000000000000023 x3  000000004000c6d9
E/TC:? 0  x4  0000000000000000 x5  0000000000000000
E/TC:? 0  x6  0000000000000000 x7  0000000000000000
E/TC:? 0  x8  0000000000000000 x9  0000000000000000
E/TC:? 0  x10 0000000000000000 x11 0000000000000000
E/TC:? 0  x12 0000000000000000 x13 0000000040005e80
E/TC:? 0  x14 0000000000000000 x15 0000000000000000
E/TC:? 0  x16 0000000000000000 x17 0000000000000000
E/TC:? 0  x18 0000000000000000 x19 0000000040005e80
E/TC:? 0  x20 000000004000e158 x21 0000000040012ec0
E/TC:? 0  x22 0000000000000000 x23 0000000000000000
E/TC:? 0  x24 0000000000000000 x25 0000000000000000
E/TC:? 0  x26 0000000000000000 x27 0000000000000000
E/TC:? 0  x28 0000000000000000 x29 0000000040005e50
E/TC:? 0  x30 00000000400062a4 elr 000000004000aaa4
E/TC:? 0  sp_el0 0000000040005e50
E/TC:? 0  region  0: va 0x0000000040000000 pa 0x00000000bc402000 size 0x002000 flags ---R-X
E/TC:? 0  region  1: va 0x0000000040002000 pa 0x00000000bc492000 size 0x001000 flags ---RW-
E/TC:? 0  region  2: va 0x0000000040004000 pa 0x00000000bc600000 size 0x002000 flags rw-RW-
E/TC:? 0  region  3: va 0x0000000040006000 pa 0x00000000bc602000 size 0x008000 flags r-x---
E/TC:? 0  region  4: va 0x000000004000e000 pa 0x00000000bc60a000 size 0x001000 flags rw-RW-
E/TC:? 0  region  5: va 0x000000004000f000 pa 0x00000000bc60b000 size 0x004000 flags rw-RW-
E/TC:? 0  region  6: va 0x0000000040013000 pa 0x00000000bc60f000 size 0x001000 flags r--R--
E/TC:? 0  region  7: va 0x0000000040014000 pa 0x00000000bc62d000 size 0x001000 flags rw-RW-
E/TC:? 0  region  8: va 0x0000000040050000 pa 0x00000000bc610000 size 0x011000 flags r-xR--
E/TC:? 0  region  9: va 0x0000000040061000 pa 0x00000000bc621000 size 0x00c000 flags rw-RW-
D/TC:? 0 user_ta_enter:166 tee_user_ta_enter: TA panicked with code 0xdeadbeef
D/TC:? 0 destroy_ta_ctx_from_session:313 Remove references to context (0xbc48fd70)
D/TC:? 0 destroy_context:298 Destroy TA ctx (0xbc48fd70)
Invoke CLEAR_SCREEN command (coloD/TC:? 0 tee_ta_close_session:498 csess 0xbc48fdd0 id 1
D/TC:? 0 tee_ta_close_session:518 Destroy session
r=0x007cfc00)..._ 

What may be the possible reason for this ?

I tried to increase TA_DATA_SIZE to 1920 * 1080 * 4. That time I am getting error like:
E/TC:? 0 alloc_pgt:149 5 page tables not available

I tied to increase the PGT_CACHE_SIZE also but not working properly.
Please can you suggest me to solve this issue ?
Thanks and Regards,
Devendra

**Comment by DevendraDevadiga** [comment]
I am using OPTEE version 3.10.0.

**Comment by sunnybird** [comment]
hi @DevendraDevadiga 
have you increase the CFG_TZDRAM_SIZE at optee_os/core/arch/arm/plat-vexpress/conf.mk ?

**Comment by DevendraDevadiga** [comment]
Dear Sir,
Thanks for your reply.

In our case the memory layout is as below:

![image](https://user-images.githubusercontent.com/36186082/127477060-66cd877d-23cf-4993-b6e2-845442c3346a.png)

I am working on i.MX8MQ platform. We used total 60MB, in that 28MB as TZDRAM, 18MB fo Secure buffer and 16MB for shared memory.
But for TA or TEE didn't modified any memory layout. We used generic memory layout for TEE_RAM or TA_RAM. 
How I can increase the TEE_RAM ? From the log below I came to know that TEE_RAM is only 2MB. Is this the issue for our application to crash ?



D/TC:0   get_aslr_seed:1344 Bad fdt: -9
D/TC:0   add_phys_mem:585 **TEE_SHMEM_START** type NSEC_SHM **0xbe000000** size **0x02000000**
D/TC:0   add_phys_mem:585 **TA_RAM_START** type TA_RAM **0xbc600000** size **0x01a00000**
D/TC:0   add_phys_mem:585 VCORE_UNPG_RW_PA type **TEE_RAM_RW** **0xbc463000** size **0x0019d000**
D/TC:0   add_phys_mem:585 VCORE_UNPG_RX_PA type **TEE_RAM_RX** **0xbc400000** size **0x00063000**
D/TC:0   add_phys_mem:585 ROUNDDOWN(((((((0x40000000 - 0x3C00000 + 0x80000000) + 0x01c00000) - 2 * 0x800000)) & ~((__typeof__((((0x40000000 - 0x3C00000 + 0x80000000) + 0x01c00000) - 2 * 0x800000)))(2 * 0x800000) - 1)) + 0x800000), CORE_MMU_PGDIR_SIZE) ty
D/TC:0   add_phys_mem:585 ROUNDDOWN((((((0x40000000 - 0x3C00000 + 0x80000000) + 0x01c00000) - 2 * 0x800000)) & ~((__typeof__((((0x40000000 - 0x3C00000 + 0x80000000) + 0x01c00000) - 2 * 0x800000)))(2 * 0x800000) - 1)), CORE_MMU_PGDIR_SIZE) type IO_SEC 0xb
D/TC:0   add_phys_mem:585 ROUNDDOWN(0x30320000, CORE_MMU_PGDIR_SIZE) type IO_SEC 0x30200000 size 0x00400000
D/TC:0   add_phys_mem:585 ROUNDDOWN(0x38800000, CORE_MMU_PGDIR_SIZE) type IO_SEC 0x38800000 size 0x00200000
D/TC:0   add_phys_mem:585 ROUNDDOWN(0x30360000, CORE_MMU_PGDIR_SIZE) type IO_SEC 0x30200000 size 0x00400000
D/TC:0   add_phys_mem:599 Physical mem map overlaps 0x30200000
D/TC:0   add_phys_mem:585 ROUNDDOWN((0x30860000), CORE_MMU_PGDIR_SIZE) type IO_NSEC 0x30800000 size 0x00400000
D/TC:0   add_phys_mem:585 TZASC_BASE type IO_SEC 0x32f80000 size 0x00010000
D/TC:0   verify_special_mem_areas:529 NSEC DDR memory [be400000 c0000000]
D/TC:0   verify_special_mem_areas:529 NSEC DDR memory [40000000 bc400000]
D/TC:0   add_va_space:625 type RES_VASPACE size 0x00a00000
D/TC:0   add_va_space:625 type SHM_VASPACE size 0x02000000
D/TC:0   dump_mmap_table:732 type NSEC_SHM     va 0xb4800000..0xb67fffff pa 0xbe000000..0xbfffffff size 0x02000000 (pgdir)
D/TC:0   dump_mmap_table:732 type IO_SEC       va 0xb6a00000..0xb6bfffff pa 0xbd800000..0xbd9fffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:732 type IO_SEC       va 0xb6c00000..0xb6dfffff pa 0xbd000000..0xbd1fffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:732 type **TA_RAM**       va 0xb6e00000..0xb87fffff pa **0xbc600000..0xbdffffff** size **0x01a00000** (pgdir)
D/TC:0   dump_mmap_table:732 type IO_SEC       va 0xb8a00000..0xb8bfffff pa 0x38800000..0x389fffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:732 type IO_NSEC      va 0xb8c00000..0xb8ffffff pa 0x30800000..0x30bfffff size 0x00400000 (pgdir)
D/TC:0   dump_mmap_table:732 type IO_SEC       va 0xb9000000..0xb93fffff pa 0x30200000..0x305fffff size 0x00400000 (pgdir)
D/TC:0   dump_mmap_table:732 type SHM_VASPACE  va 0xb9400000..0xbb3fffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0   dump_mmap_table:732 type RES_VASPACE  va 0xbb600000..0xbbffffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0   dump_mmap_table:732 type IO_SEC       va 0xbc3f0000..0xbc3fffff pa 0x32f80000..0x32f8ffff size 0x00010000 (smallpg)
D/TC:0   dump_mmap_table:732 type **TEE_RAM_RX**   va 0xbc400000..0xbc462fff pa **0xbc400000..0xbc462fff** size **0x00063000** (smallpg)
D/TC:0   dump_mmap_table:732 type **TEE_RAM_RW**   va 0xbc463000..0xbc5fffff pa **0xbc463000..0xbc5fffff** size **0x0019d000** (smallpg)
D/TC:0   core_mmu_entry_to_finer_grained:761 xlat tables used 1 / 7
D/TC:0   core_mmu_entry_to_finer_grained:761 xlat tables used 2 / 7
D/TC:0   core_mmu_entry_to_finer_grained:761 xlat tables used 3 / 7

Any configuration is wrong ?
Please can you help me on this issue ?
Thanks and Regards,
Devendra

**Comment by DevendraDevadiga** [comment]
Any suggestions?
What may be the possible reason for secure display application failure when I used 8MB image file ?

**Comment by DevendraDevadiga** [comment]
Any suggestions for this issue?

**Comment by StephQAZ** [comment]
> Any suggestions for this issue?

hello, have you fixed your problem?

**Comment by StephQAZ** [comment]
> Any suggestions for this issue?

hello, have you fixed your problem?

**Comment by TaihuLight** [comment]
I try to increase TA memory size  #https://github.com/OP-TEE/optee_os/issues/4768 #https://github.com/OP-TEE/optee_os/issues/2833 #https://github.com/OP-TEE/optee_os/issues/2079 by setting the parameters including 
`CFG_TZDRAM_SIZE=0x04000000 CFG_TEE_RAM_VA_SIZE=0x00400000 CFG_DRAM1_BASE=0x430000000 CFG_SHMEM_SIZE=0x01800000  CFG_SHMEM_SIZE=0x00800000`
when building OP-TEE. i.e.,  `make PLATFORM=hikey-hikey960 CFG_TZDRAM_SIZE=0x04000000 CFG_TEE_RAM_VA_SIZE=0x00400000 CFG_DRAM1_BASE=0x430000000 CFG_SHMEM_SIZE=0x01800000  CFG_SHMEM_SIZE=0x00800000`.   But, it does not work for adding them into 'make'. I must modify it in the source code 
`optee_os/core/arch/arm/plat-hikey/conf.mk` and `optee_os/core/arch/arm/plat-hikey/platform_config.h` to make it work.
How to fix this issue?
@DevendraDevadiga @jforissier @https://github.com/mofanv
