### ISSUE TITLE
How can I get virtual address of a physical address.

### ISSUE THREAD

**Issue by ningzhenyu** [OP-TEE/optee_os#477]
I used op-tee as my environment, and based on that, I am trying to understand how the two worlds switches.

I didn't use the APIs you provided for TAs. Instead, I wrote a linux module and execute a smc instruction when the module is initing. I find the smc handler your wrote, and add some test codes in "__thread_std_smc_entry(optee_os/core/arch/arm/kernel/thread.c)" function. In this test codes(I think these codes should running in secure world), I tried to access the kernel image. From some other document, I guess the kernel image should be in physical memory starting from 0x00008000. Then, how can I get the virtual address of this physical address?

**Comment by jenswi-linaro** [comment]
The short answer is you can't, that memory isn't mapped in secure world.

**Comment by ningzhenyu** [comment]
@jenswi-linaro 
emmm, i guessed the answer. As I am not able to write a complete "mm" module by myself, is it possible for me to just make some slight modifications to your "mm" module to achieve this?
I found some relative functions like "tee_mmu_kmap_helper", "tee_mmu_kmap_pa2va_helper", but I guess I can not directly use them.

**Comment by jenswi-linaro** [comment]
Apologies for the delay. I hope you've found out by now that the tee_mmu_kmap_helper() would help here.

**Comment by jbech-optee-adm** [comment]
I will close this issue due to inactivity, please re-open in case you have additional questions or comments.
