### ISSUE TITLE
what's the relationship between 'struct pgt' and 'struct core_mmu_table_info'?

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#4773]
When I study the source code of OP-TEE, I am always not clear about the role of these two structures in the code.

**Comment by jenswi-linaro** [comment]
`struct core_mmu_table_info` is describing the translation table when manipulating it with the helper functions `core_mmu_*`.
`struct pgt` is used to manage allocation of translation pages needed to map a TA and its parameters. This involves waiting for translation tables to become available if there's a temporary shortage.

**Comment by YogzZ** [comment]
Thank you for your answer. There are some other problems:

1. Why do we free the `fobj` after allocating the `fobj` and some areas in [https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/tee_pager.c#L2010](url). Will `area->fobj` become NULL？
2. In [https://github.com/OP-TEE/optee_os/blob/7213740b1447c9a3f38a7b7e81b27c719696642e/core/arch/arm/mm/tee_pager.c#L401](url), all the phy_address of `pt->tbl_info` in tzsram are set to 0. In [https://github.com/OP-TEE/optee_os/blob/7213740b1447c9a3f38a7b7e81b27c719696642e/core/arch/arm/mm/tee_pager.c#L254](url), how to find `core_mmu_table_info` according to `pa`?
3. Is `pager_tables` just used for initialization and translation of `pa`? `pager_area` is used to record the va area in ddr, and `pmem` uses the va in alias to replace the va in ddr. Is that correct?

**Comment by jenswi-linaro** [comment]
> Thank you for your answer. There are some other problems:
> 
> 1. Why do we free the `fobj` after allocating the `fobj` and some areas in [https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/tee_pager.c#L2010](url). Will `area->fobj` become NULL？

I assume you're referring to the `fobj_put()` at line 2017 just after the call to tee_pager_add_core_region(). That's not a free, that a refcount decrease since the fobj now belong to the region, note the `fobj_get()` in tee_pager_add_core_region().

> 2. In [https://github.com/OP-TEE/optee_os/blob/7213740b1447c9a3f38a7b7e81b27c719696642e/core/arch/arm/mm/tee_pager.c#L401](url), all the phy_address of `pt->tbl_info` in tzsram are set to 0. In [https://github.com/OP-TEE/optee_os/blob/7213740b1447c9a3f38a7b7e81b27c719696642e/core/arch/arm/mm/tee_pager.c#L254](url), how to find `core_mmu_table_info` according to `pa`?

What's the connection between those two?

> 3. Is `pager_tables` just used for initialization and translation of `pa`? `pager_area` is used to record the va area in ddr, and `pmem` uses the va in alias to replace the va in ddr. Is that correct?

I don't understand that question. The pager is quite complicated so if you want to understand it you must be prepared to spend some time with the code. The answer you're looking for is there in the code. Good starting points are `tee_pager_handle_fault()` and the non-static functions called early during boot.

**Comment by YogzZ** [comment]
Yes, it's complicated and interesting. Sorry for asking some wrong questions. If possible, I want to keep this issues so that I can ask you for help later : )

**Comment by YogzZ** [comment]
What are the effects of `tee_pager_hide_pages` and `tee_pager_unhide_page` in `tee_pager_handle_fault`?

**Comment by etienne-lms** [comment]
`tee_pager_hide_pages()` is used to unmap pageable pages but with their content and mapping resources fully preserved. If such a paged is later accessed, restoring its mapping is quite quick (only need to enable back its mapping, no need to reload its content since it was preserved). 
`tee_pager_unhide_page()` restores the mapping of a hidden page.

This page hiding sequence is useful in to the pager to help finding the least accessed pageable pages. When pager needs a new physical page, it may need to page-out an already used page. When so, it is more efficient to page-out a page that is not accessed often as paging-in a page may take a bit a time (find a physical page, reload the virtual page content etc...).

**Comment by etienne-lms** [comment]
Note that the pager (`CFG_WITH_PAGER=y`) is a quite specific configuration of OP-TEE, needed only with OP-TEE is expected to run a small secure RAM. See https://optee.readthedocs.io/en/latest/architecture/core.html?highlight=pager#pager.
Most OP-TEE platforms do not enable `CFG_WITH_PAGER`.

**Comment by YogzZ** [comment]
Thank you for your professional answer. My original intention was to use the pager on a device with a large ram...

**Comment by YogzZ** [comment]
When I set `CFG_WITH_PAGER=y`, op-tee stop in [https://github.com/janoslim/optee_os/blob/3.11.0/core/arch/arm/kernel/boot.c#L442](url). Why can not `memmove`?

**Comment by YogzZ** [comment]
Does Pager really not support for ARM64？

**Comment by etienne-lms** [comment]
> Does Pager really not support for ARM64？

It does. You should be able to build platform qemu_v8 with `CFG_WITH_PAGER=y` and successfully boot and run `xtest`.

> Why can not memmove?

I suggest you add some debug traces before the `memmove()` instruction to see source address, destination address and byte size. Maybe i'll see some unexpected value that could explain the behavior.

**Comment by YogzZ** [comment]
I try to print `(paged_store + init_size)`, `phys_to_virt(pageable_part)` and `pageable_size`.

> D/TC:0   add_va_space:597 type SHM_VASPACE size 0x02000000
D/TC:0   dump_mmap_table:709 type NSEC_SHM     va 0xf4600000..0xf51fffff pa 0xff200000..0xffdfffff size 0x00c00000 (pgdir)
D/TC:0   dump_mmap_table:709 type TA_RAM       va 0xf5400000..0xf81fffff pa 0xfc400000..0xff1fffff size 0x02e00000 (pgdir)
D/TC:0   dump_mmap_table:709 type IO_SEC       va 0xf8400000..0xf89fffff pa 0x29800000..0x29dfffff size 0x00600000 (pgdir)
D/TC:0   dump_mmap_table:709 type IO_SEC       va 0xf8c00000..0xf8dfffff pa 0x28200000..0x283fffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:709 type IO_NSEC      va 0xf8e00000..0xf8ffffff pa 0x28200000..0x283fffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:709 type IO_NSEC      va 0xf9000000..0xf91fffff pa 0x28000000..0x281fffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:709 type RES_VASPACE  va 0xf9200000..0xf9bfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0   dump_mmap_table:709 type SHM_VASPACE  va 0xf9e00000..0xfbdfffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0   dump_mmap_table:709 type TEE_RAM_RX   va 0xfc000000..0xfc020fff pa 0xfc000000..0xfc020fff size 0x00021000 (smallpg)
D/TC:0   dump_mmap_table:709 type TEE_RAM_RW   va 0xfc021000..0xfc05afff pa 0xfc021000..0xfc05afff size 0x0003a000 (smallpg)
D/TC:0   dump_mmap_table:709 type TEE_RAM_RX   va 0xfc05b000..0xfc06ffff pa 0xfc05b000..0xfc06ffff size 0x00015000 (smallpg)
D/TC:0   dump_mmap_table:709 type PAGER_VASPACE va 0xfc070000..0xfc3fffff pa 0x00000000..0x0038ffff size 0x00390000 (smallpg)
D/TC:0   core_mmu_entry_to_finer_grained:765 xlat tables used 1 / 10
D/TC:0   core_mmu_entry_to_finer_grained:765 xlat tables used 2 / 10
D/TC:0   core_mmu_entry_to_finer_grained:765 xlat tables used 3 / 10
E/TC:0   console_init:273 enter c code(pl011)
I/TC: OP-TEE 3.12.0 (09:52:16 Aug 10 2021)
I/TC: Pager is enabled. Hashes: 4064 bytes
D/TC:0 0 init_runtime:443 paged_store + init_size: 0xf5408000
D/TC:0 0 init_runtime:444 pageable_part: 0xf9200000
D/TC:0 0 init_runtime:445 pageable_size 520192

**Comment by YogzZ** [comment]
I found the program stop at the loop in [https://github.com/OP-TEE/optee_os/blob/master/lib/libutils/isoc/newlib/memmove.c#L132](url)

**Comment by YogzZ** [comment]
the type of `pageable_part` is `RES_VASPACE`.

**Comment by etienne-lms** [comment]
You should check the physical address of (`pageable_part: 0xf9200000`). Check  what it relates to and where it is mapped in RES_VASPACE. It looks strange. The usual scheme (AFAICT) is bootloader loads pager's pagestore in a memory mapped from core's `static_memory_map` and [boot.c#L442](https://github.com/janoslim/optee_os/blob/3.11.0/core/arch/arm/kernel/boot.c#L442) moves these into a definitive location allocated in TA_RAM.

**Comment by YogzZ** [comment]
I try this on qemu and it's easy to work. But it's not going well on my arm64 development board. The `pa` of `pageable_part` is `'0'`. 

Could this be because I used the simulated sram address on the development board? 

Or need to enable other configs on the development board? 

Or is it the problem of ATF firmware configuration?

**Comment by YogzZ** [comment]
In tee, the value of `pageable_part` is always `0`. So I checked the ATF part of the code: `pageable_part` is read from  `optee_ep_info` in BL32 firmware. Is this a problem with bl32.bin? But bl32.bin is generated by compiling OPTEE OS. So the problem returned to OPTEE. . .

**Comment by YogzZ** [comment]
After opening the `pager` and compiling TEE OS, I only updated `pager_v2.bin` in the flash. Could these errors be caused by not updating `pageable_v2.bin`?

**Comment by etienne-lms** [comment]
> In tee, the value of pageable_part is always 0. 

It looks like your TF-A does not properly pass this information to OP-TEE at boot time. The physical address (as seen by OP-TEE) is expected from register X0 at when OP-TEE boots. I seems your issue in rather in TF-A.

> After opening the pager and compiling TEE OS, I only updated pager_v2.bin in the flash. Could these errors be caused by not updating pageable_v2.bin?

After rebuild optee_os, the 3 images (tee-header_v2.bin, tee-pager_v2.bin and tee-pageable_v2.bin) must be update is flash. If not, you'll likely end up with troubles.

**Comment by YogzZ** [comment]
Hello! I'm back with some questions~

When I open `pager` on imx6q. The OP-TEE always stop at `core/kernel/pm.c:27 <verify_cb_args>`. I try to find the code near the wrong location, and the order is: `csu_init`  (imx_csu.c) -> `register_pm_driver_cb` -> `verify_cb_args`. 

I found `csu_init` set `handle` to `NULL` and pass it to `verify_cb_args`. Is this a bug or a problem with my configuration?

The function `csu_init` is different between (I use: [https://source.codeaurora.org/external/imx/imx-optee-os/](url)) and [https://github.com/OP-TEE/optee_os](url). 

The function 'csu_init' I use is as follows:
> static TEE_Result csu_init(void)
{
	csu_configure();
	register_pm_driver_cb(pm_enter_resume, NULL);
	return TEE_SUCCESS;
}
driver_init(csu_init);

And the error log is as follows：
> F/TC:0 0 tee_pager_handle_fault:1437 Mapped 0x14065000 -> 0x1404f000
F/TC:0 0 tee_pager_handle_fault:1437 Mapped 0x14047000 -> 0x14050000
F/TC:0 0 tee_pager_handle_fault:1437 Mapped 0x14061000 -> 0x14051000
F/TC:0 0 tee_pager_handle_fault:1437 Mapped 0x14059000 -> 0x14052000
F/TC:0 0 tee_pager_handle_fault:1437 Mapped 0x14066000 -> 0x14053000
D/TC:0 0 csu_init:124 3
D/TC:0 0 verify_cb_args:20 0x140079bd 0x1406e885 0x0
E/TC:0 0 verify_cb_args:26 PM callbacks mandates unpaged arguments: 0x1406e885 0x0
E/TC:0 0 Panic at core/kernel/pm.c:27 <verify_cb_args>
E/TC:0 0 Call stack:
E/TC:0 0  0x14002fed

**Comment by YogzZ** [comment]
I print the content in the if sentence of `verify_cb_args`: `if (1 && (!0 || (0 && !0)))`, 
and the no `pager` is `if (1 && (!1 || (0 && !1)))`.

**Comment by etienne-lms** [comment]
Please, prefer open a new issue for this request.

**Comment by etienne-lms** [comment]
Note: if your question relates to  https://source.codeaurora.org/external/imx/imx-optee-os/ implementation, I should get better answers from codeaurora project maintainers (https://www.codeaurora.org/projects/i-mx).

**Comment by YogzZ** [comment]
OK~
