### ISSUE TITLE
HUK - definition

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#4774]
hi
What are the OP-TEE requirements to accept a HUK driver for a platform? Aside from its uniqueness, what else do you consider before merging? ie, its secrecy perhaps or nothing else?
TIA

**Comment by jenswi-linaro** [comment]
I'm not sure we have any strict requirements. It should of course be more useful than the default implementation, but that bar shouldn't be hard to pass. :-)

In general I'd say that it should be secure enough that it could be used in a real product. It can be quite painful to change the way the HUK is calculated once a platform is deployed so it would make sense to do the best that can be done with the platform from the beginning.
