### ISSUE TITLE
How to Use Crypto Algorithem Implemented by ARM Instruction

### ISSUE THREAD

**Issue by Guo-Jiawei** [OP-TEE/optee_os#4775]
Hi, I want to write a TA to implement crypto algorithems by ARM instruction. 

How to invoke the codes in  "optee_os\core\arch\arm\crypto\"?

How to add new crypto algorithems writen by ARM instructions?

**Comment by jenswi-linaro** [comment]
> Hi, I want to write a TA to implement crypto algorithems by ARM instruction.
> 
> How to invoke the codes in "optee_os\core\arch\arm\crypto"?

You can't, that code is meant to execute at S-EL1. I suppose you can copy the source and after some fixing up compile it in a TA.

> 
> How to add new crypto algorithems writen by ARM instructions?

In your TA?
