### ISSUE TITLE
Calling PTA from optee_os core

### ISSUE THREAD

**Issue by JensVankeirsbilck** [OP-TEE/optee_os#4776]
Using the code from #2925 I am able to periodically launch a task (albeit in interrupt context). 
The code for this is now split over 2 files
* secPhyTimer.c, which is my secure timer driver and is located at optee_os/core/drivers 
* periodicTask.c, which is the task and is located at optee_os/core/kernel

On the other hand, I built a PTA which eventually will serve as an interface to some I/O peripherals. The code for, the now dummy, the PTA is contained in
* myPTA.c, which is the implementation of the PTA and is located at optee_os/core/pta
* pta_myPTA.h, which is the header file of the PTA and is located at optee_os/libutee/include (since all header files for the existing PTAs seem to be located here, I put my header file in here)

[myPeriodicTask.zip](https://github.com/OP-TEE/optee_os/files/6900640/myPeriodicTask.zip)

I now want to call my PTA from the periodic task, but when inserting the calls to `TEE_OpenTASession`, `TEE_InvokeTACommand` and `TEE_CloseTASession` I get compiler errors stating "undefined reference to" those 3 functions. I did include the 2 necessary headers, `tee_internal_api.h` and `tee_internal_api_extensions.h` , so I'm confused to why I get these errors. I need to call those methods to interact with my (or any) PTA, as far as I understand the documentation.

Is it just not allowed to call/interact with a PTA from the optee_os core? 

PS: I'm using the QEMUv7 build of OPTEE, which was set up using the steps described in the documentation https://optee.readthedocs.io/en/latest/building/devices/qemu.html .
PPS: I'm very well aware that this time-triggered/periodic functionality without REE/Linux interaction is not what OPTEE is meant for, but the decision to use OPTEE was made above my head, so now I'm trying to figure out the best/cleanest way to get this to work within OPTEE.

**Comment by jenswi-linaro** [comment]
> Is it just not allowed to call/interact with a PTA from the optee_os core?

Yes, the're no need to call like that. You can use direct function calls instead.

> PPS: I'm very well aware that this time-triggered/periodic functionality without REE/Linux interaction is not what OPTEE is meant for, but the decision to use OPTEE was made above my head, so now I'm trying to figure out the best/cleanest way to get this to work within OPTEE.

Note that https://github.com/OP-TEE/optee_os/pull/4601 is going in this direction. There's also some documentation at https://optee.readthedocs.io/en/latest/architecture/core.html#notifications

**Comment by JensVankeirsbilck** [comment]
> Yes, the're no need to call like that. You can use direct function calls instead.

To make sure I understand you correctly: you mean not using a PTA and just create a _normal_ interface, which i can call directly? 

> Note that #4601 is going in this direction. There's also some documentation at https://optee.readthedocs.io/en/latest/architecture/core.html#notifications

I was not aware that #4601 was already merged and available to use. I'll read the documentation and experiment with the notification system. Thanks to point this out.

**Comment by jenswi-linaro** [comment]
> > Yes, the're no need to call like that. You can use direct function calls instead.
> 
> To make sure I understand you correctly: you mean not using a PTA and just create a _normal_ interface, which i can call directly?

Yes

> 
> > Note that #4601 is going in this direction. There's also some documentation at https://optee.readthedocs.io/en/latest/architecture/core.html#notifications
> 
> I was not aware that #4601 was already merged and available to use. I'll read the documentation and experiment with the notification system. Thanks to point this out.

It's not merged yet, it's still under discussion. We'll only merge this once the kernel part has reach an agreement.

**Comment by JensVankeirsbilck** [comment]
Thanks very much for your answers! I'll first work in creating the requested functionality as best as I can using a secure timer and a _normal_ interface and I'll try to keep track of #4601 .
