### ISSUE TITLE
Question: GDB: How to figure out the tee.elf load address?

### ISSUE THREAD

**Issue by ademyankov** [OP-TEE/optee_os#4778]
**Hi folks,**

I am trying to debug the TA on OP-TEE 3.14.

I have done it before a long time ago on OP-TEE 3.4 and I didn't have any problem then using the following [guideline](https://github.com/ForgeRock/optee-build/blob/master/docs/debug.md#15-debugging-ta).

Before it was not a problem because the **tee.elf** was a statically linked library and simply doing **symbol-file ./tee.elf** worked fine. But now, the **tee.elf** is a dynamically linked library and I have to use **add-symbol-file [file] [addr]** to load the symbols at the correct address to set the breakpoint at **thread_enter_user_mode**, where then I will be able to figure out the load address of my TA.

**Q1:** How to figure out the **tee.elf** load address?

**Q2:** Is there a way to hardcode or somehow fix the **TA** or **tee.elf** load address for debug purposes?

I found a workaround, but it is very troublesome. I have to print out the address of the TA function, then set the breakpoint at the address, run the code, when it hits the breakpoint only then I can load up the symbols of the TA. It gets the job done since the load address of TA changes rarely and it alternates between 2-3 values all the time. I just have a set of breakpoints for different addresses. But as you can imagine it's a very tiresome approach.

**Thanks,
Alex.**

**Comment by jforissier** [comment]
Hello @ademyankov,

I think what you're after is essentially `CFG_CORE_ASLR=n` and/or `CFG_TA_ASLR=n`. By setting these configs you will disable the randomization of the load address of the TEE core and/or the TAs.

There is some documentation at https://optee.readthedocs.io/en/latest/building/devices/qemu.html#gdb-secure-world, it does mention `CFG_CORE_ASLR=n` but is otherwise lacking a bit and would probably benefit greatly from some updates ;-)

@jbech-linaro has created a nice presentation which I can't readily find a link to :-/

Finally here is what I keep in my local `~/.gdbinit` to debug OP-TEE on QEMUv8, hopefully it will help you.
```
define optee_v8
        # Debugging TEE core without ASLR (CFG_CORE_ASLR=n)
        symbol-file ~/work/optee_repo_qemu_v8/optee_os/out/arm/core/tee.elf

        # Note: to debug TEE core with CFG_CORE_ASLR=y:
        # 1. Use the normal symbol-file command above and break *after* init_mem_map()
        #    For example: b check_mem_map
        # 2. Get load address from debug message:
        #    D/TC:0   init_mem_map:1103 Mapping core at 0x28288000 offs 0x1a188000
        #add-symbol-file ~/work/optee_repo_qemu_v8/optee_os/out/arm/core/tee.elf 0x28288000

        # TA/library debugging
        # Set CFG_TA_ASLR=n
        # Check for message:
        # D/LD:  ldelf:168 ELF (5b9e0e40-2636-11e1-ad9e-0002a5d5c51b) at 0x40014000
        # Re-run and use load address shown by OP-TEE + 0x20 (= start of .text; first PT_LOAD is .ta_header)
        #add-symbol-file ~/work/optee_repo_qemu_v8/out-br/build/optee_test_ext-1.0/ta/os_test/out/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.elf 0x40014020

        # ldelf debugging
        # Get load address from debug message:
        # D/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
        #add-symbol-file ~/work/optee_repo_qemu_v8/optee_os/out/arm/ldelf/ldelf.elf 0x40006000

        target remote localhost:1234
end
```

**Comment by jbech-linaro** [comment]
> @jbech-linaro has created a nice presentation which I can't readily find a link to :-/

It can be found [here](https://docs.google.com/presentation/d/1NEBZPrYqnjV55NOkJp_XQ7nGlOwDRuFb7z6cGO0Iboo/edit).

**Comment by ademyankov** [comment]
Yep! That's everything I need. Thanks, @jforissier and @jbech-linaro!
