### ISSUE TITLE
crypto_bignum_allocate(): Why not allocate from the mempool?

### ISSUE THREAD

**Issue by a21152** [OP-TEE/optee_os#4779]
https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/mpi_desc.c#L751

Why does it malloc() from the core heap here instead of mbedtls_mpi_mempool?

**Comment by a21152** [comment]
Is the pool dedicated to scratch use only?

**Comment by etienne-lms** [comment]
I think you found the answer, the pool is sized for the supported TEE operations, not for the amount of possible bignum objects the TEE may allocate.

**Comment by a21152** [comment]
Ahh, thanks for confirming.
