### ISSUE TITLE
Is OPTEE position independent?

### ISSUE THREAD

**Issue by jingdlu** [OP-TEE/optee_os#4784]
Can I load OPTEE to any address for running? Or only can run from the address defined in link script?

Thanks

**Comment by etienne-lms** [comment]
OPTEE currently mandates being booted at the physical addressed it is built to boot from, most likely its load address. This comes from that OPTEE currently mandates an identity mapping (virt addr = phys addr) of some of its section (those involved in OP-TEE early initialization).

**Comment by jforissier** [comment]
Right.

We might not be very far from supporting this however, because the TEE core is relocatable and is relocated on boot when ASLR is enabled so it is only the early initialization that needs to be changed as you said @etienne-lms.

See #4637 where this has been discussed a bit already.

**Comment by jingdlu** [comment]
Thanks for the reply.
