### ISSUE TITLE
About A80 board

### ISSUE THREAD

**Issue by fanguannan0706** [OP-TEE/optee_os#479]
Hi,
I want to try OP-TEE on A80 board, and I find there are some kinds of boards, like CC-A80, Pro A80 Kit, A80 pcDuino8 (Beta), A80 OptimusBoard. I want to know which one can support OP-TEE?

**Comment by jbech-linaro** [comment]
@fanguannan0706 we have tried to get an answer by forwarding your question to Allwinner, but we haven't heard anything from them so far. Is there a special reason why you want to use the Allwinner board? If not, then I'd suggest to try Hikey instead. That is available, open and OP-TEE is running on it also and even though both A80 and Hikey are supported, we use Hikey primarily.

**Comment by murasesyuka** [comment]
@jbech-linaro there is one Question.

Hikey 32bit build is do not use ArmTrustedFirmware?
now I have a reference plat-sunxi(A80) for armv7 without ATF.

**Comment by vchong** [comment]
@murasesyuka HiKey is an armv8 64-bit platform and hence uses ARM-TF. I believe there's no 32-bit build.

**Comment by jforissier** [comment]
Let me try to give more details, hopefully I won't get this wrong.
* OP-TEE on HiKey uses ARM Trusted Firmware.
* EL3 is ARM TF secure monitor, and always runs in Aarch64 execution mode.
* Secure EL1 is OP-TEE OS, and can be either Aarch32 or Aarch64. To build 64-bit binary, use `make CFG_ARM64_core=y CROSS_COMPILE=aarch64-linux-gnu-gcc`.
* Secure EL0 is for the Trusted Applications and OP-TEE's user-mode libraries (libutils.a, libutee.a, libmpa.a). Only Aarch32 is supported for now.
* Non-secure EL1 (linux kernel and OP-TEE driver) is typically Aarch64 but may be Aarch32, too.
* Non-secure EL0 (user mode applications) may also be either Aarch64 (if the kernel is Aarch64) or Aarch32 (if the kernel is Aarch32 or Aarch64). Note that the current OP-TEE [client] (https://github.com/OP-TEE/optee_client) and [driver] (https://github.com/OP-TEE/optee_linuxdriver) do not support mixed-mode non-secure side, i.e., no Aarch32 application on top of an Aarch64 kernel. The new [generic driver] (https://lkml.org/lkml/2015/8/19/111) will support such a mode, however.

**Comment by murasesyuka** [comment]
thank you for reply. and info.

**Comment by pascal-brand-st** [comment]
@fanguannan0706 Can we close the issue?

**Comment by fanguannan0706** [comment]
Ok,of course.
