### ISSUE TITLE
optee boot

### ISSUE THREAD

**Issue by kola-hash** [OP-TEE/optee_os#4791]
I use uboot to load ATF, optee and linux, the current printed information is as follows, Linux cannot be started, I really don’t understand what is wrong, and I don’t know how to solve this bug, can any friends help me? 

print information：

I/TC: Primary CPU switching to normal world boot
rc:1679169708
INFO:    opteed-init: Finished
INFO:    BL32 Initialized
INFO:    bl31_1
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x44080000
INFO:    SPSR = 0x3c5
INFO:    bl31_2
INFO:    bl31_3
I/TC: Secondary CPU 1 initializing
I/TC: Secondary CPU 1 switching to normal world boot

**Comment by etienne-lms** [comment]
Hello @kola-hash.
From the trace you provide, Linux kernel has booted. One can see that thanks message "Secondary CPU 1 ..." as secondary CPU is booted only once Linux as performed few initialization.
Try to enable your Linux kernel's earlyprintk, you should see some helpful Linux trace messages.

**Comment by etienne-lms** [comment]
True, the following message is emited by OP-TEE:
> I/TC: Secondary CPU 1 initializing
I/TC: Secondary CPU 1 switching to normal world boot

However, this message comes when secondary core(s) is/are booted which happens during Linux initialization; from a Linux request. Quite early but not that early. If Linux did not start to initialize, you would not see these traces.

**Comment by jforissier** [comment]
Like Etienne said. @kola-hash the log you have shown is the secure console, please check also the normal world console output.

**Comment by kola-hash** [comment]
> Like Etienne said. @kola-hash the log you have shown is the secure console, please check also the normal world console output.

The current state is that the primary core can return to the normal world, and ATF can also obtain the entry address of Linux, but no information is printed after the bl31_main function finishes running. It should be to start Linux, but the actual situation does not start. I don't know why

**Comment by etienne-lms** [comment]
> you mean the linux kernel have started initializing？

I believe so, yes.

>  (...) and then the program has no other print information

Try to enable earlyprintk in Linux. 
You need some config switches in Linux kernel configuration: `CONFIG_DEBUG_LL=y CONFIG_EARLY_PRINTK=y`.
Maybe also platform specific `CONFIG_xxx` (maybe `CONFIG_DEBUG_UART_PHYS=xxx` or `CONFIG_xxx_DEBUG_UART=y`). Check you Linux kernel support.

You also need to add `earlyprintk` to the cmdline passed to Linux kernel.

With Linux earlyprink enabled, you'll likely see some Linux traces:
```patch
 (...)
 I/TC: Primary CPU switching to normal world boot
 rc:1679169708
 INFO: opteed-init: Finished
 INFO: BL32 Initialized
 INFO: BL31: Preparing for EL3 exit to normal world
 INFO: Entry point address = 0x44080000
 INFO: SPSR = 0x3c5
+[    x.xxxxxx] (...) 
+[    x.xxxxxx] Kernel command line: (...) earlyprintk (...)
+[    x.xxxxxx] (...)
+[    x.xxxxxx] smp: Bringing up secondary CPUs ...
 I/TC: Secondary CPU 1 initializing
 I/TC: Secondary CPU 1 switching to normal world boot
+[    x.xxxxxx]  (...)
+[    x.xxxxxx] smp: Brought up x node, X CPUs
+[    x.xxxxxx]  (...)
```

**Comment by kola-hash** [comment]
> > you mean the linux kernel have started initializing？
> 
> I believe so, yes.
> 
> > (...) and then the program has no other print information
> 
> Try to enable earlyprintk in Linux.
> You need some config switches in Linux kernel configuration: `CONFIG_DEBUG_LL=y CONFIG_EARLY_PRINTK=y`.
> Maybe also platform specific `CONFIG_xxx` (maybe `CONFIG_DEBUG_UART_PHYS=xxx` or `CONFIG_xxx_DEBUG_UART=y`). Check you Linux kernel support.
> 
> You also need to add `earlyprintk` to the cmdline passed to Linux kernel.
> 
> With Linux earlyprink enabled, you'll likely see some Linux traces:
> 
> ```diff
>  (...)
>  I/TC: Primary CPU switching to normal world boot
>  rc:1679169708
>  INFO: opteed-init: Finished
>  INFO: BL32 Initialized
>  INFO: BL31: Preparing for EL3 exit to normal world
>  INFO: Entry point address = 0x44080000
>  INFO: SPSR = 0x3c5
> +[    x.xxxxxx] (...) 
> +[    x.xxxxxx] Kernel command line: (...) earlyprintk (...)
> +[    x.xxxxxx] (...)
> +[    x.xxxxxx] smp: Bringing up secondary CPUs ...
>  I/TC: Secondary CPU 1 initializing
>  I/TC: Secondary CPU 1 switching to normal world boot
> +[    x.xxxxxx]  (...)
> +[    x.xxxxxx] smp: Brought up x node, X CPUs
> +[    x.xxxxxx]  (...)
> ```

Will it enter opee again during the Linux boot process?

**Comment by kola-hash** [comment]
> Like Etienne said. @kola-hash the log you have shown is the secure console, please check also the normal world console output.
I refer to the boot process of rpi3. When the primary core returns to the normal world and starts to jump to uboot to execute, optee will print some information again. Why? Is it possible to enter optee again? When the secondary cores return to the normal world, some TA information will be printed before starting Linux. Why? 
I guess, if there is no optee driver in Linux, will it not be able to complete Linux startup even if optee is successfully started? 
How can I be sure that Optee has been successfully started? 

The rpi3 print information as follows:

I/TC: Primary CPU switching to normal world boot
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x11000000
INFO:    SPSR = 0x3c9


U-Boot 2019.01-00093-gaac0c29 (Mar 31 2021 - 22:21:45 +0800)

DRAM:  948 MiB
RPI 3 Model B+ (0xa020d3)
MMC:   mmc@7e202000: 0, sdhci@7e300000: 1
Loading Environment from FAT... OK
In:    serial
Out:   serial
Err:   serial
Net:   No ethernet found.
starting USB...
USB0:   scanning bus 0 for devices... 4 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0
16706048 bytes read in 695 ms (22.9 MiB/s)
## Flattened Device Tree blob at 01000000
   Booting using the fdt blob at 0x1000000
   reserving fdt memory region: addr=0 size=1000
   Loading Device Tree to 000000003af3d000, end 000000003af473a4 ... OK

Starting kernel ...

I/TC: Secondary CPU 1 initializing
I/TC: Secondary CPU 1 switching to normal world boot
I/TC: Secondary CPU 2 initializing
I/TC: Secondary CPU 2 switching to normal world boot
I/TC: Secondary CPU 3 initializing
I/TC: Secondary CPU 3 switching to normal world boot
D/TC:3   tee_entry_exchange_capabilities:102 Dynamic shared memory is disabled
D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA 7011a688-ddde-4053-a5a9-7b3c4ddf13b8
D/TC:? 0 tee_ta_init_pseudo_ta_session:312 Open device.pta
D/TC:? 0 tee_ta_init_pseudo_ta_session:329 device.pta : 7011a688-ddde-4053-a5a9-7b3c4ddf13b8
D/TC:? 0 tee_ta_close_session:514 csess 0x1017ab30 id 1
D/TC:? 0 tee_ta_close_session:533 Destroy session
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.4.83-v8 (anna@anna-virtual-machine) (gcc version 9.2.1 20191025 (GNU Toolchain for the A-profile Architecture 9.2-2019.12 (arm-9.10))) #1 SMP PREEMPT Wed Mar 31 20:56:00 CST 2021
[    0.000000] Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
[    0.000000] printk: debug: ignoring loglevel setting.

**Comment by kola-hash** [comment]
> > you mean the linux kernel have started initializing？
> 
> I believe so, yes.
> 
> > (...) and then the program has no other print information
> 
> Try to enable earlyprintk in Linux.
> You need some config switches in Linux kernel configuration: `CONFIG_DEBUG_LL=y CONFIG_EARLY_PRINTK=y`.
> Maybe also platform specific `CONFIG_xxx` (maybe `CONFIG_DEBUG_UART_PHYS=xxx` or `CONFIG_xxx_DEBUG_UART=y`). Check you Linux kernel support.
> 
> You also need to add `earlyprintk` to the cmdline passed to Linux kernel.
> 
> With Linux earlyprink enabled, you'll likely see some Linux traces:
> 
> ```diff
>  (...)
>  I/TC: Primary CPU switching to normal world boot
>  rc:1679169708
>  INFO: opteed-init: Finished
>  INFO: BL32 Initialized
>  INFO: BL31: Preparing for EL3 exit to normal world
>  INFO: Entry point address = 0x44080000
>  INFO: SPSR = 0x3c5
> +[    x.xxxxxx] (...) 
> +[    x.xxxxxx] Kernel command line: (...) earlyprintk (...)
> +[    x.xxxxxx] (...)
> +[    x.xxxxxx] smp: Bringing up secondary CPUs ...
>  I/TC: Secondary CPU 1 initializing
>  I/TC: Secondary CPU 1 switching to normal world boot
> +[    x.xxxxxx]  (...)
> +[    x.xxxxxx] smp: Brought up x node, X CPUs
> +[    x.xxxxxx]  (...)
> ```

I refer to the boot process of rpi3. When the primary core returns to the normal world and starts to jump to uboot to execute, optee will print some information again. Why? Is it possible to enter optee again? When the secondary cores return to the normal world, some TA information will be printed before starting Linux. Why? 
I guess, if there is no optee driver in Linux, will it not be able to complete Linux startup even if optee is successfully started? 
How can I be sure that Optee has been successfully started? 

The rpi3 print information as follows:

I/TC: Primary CPU switching to normal world boot
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x11000000
INFO:    SPSR = 0x3c9


U-Boot 2019.01-00093-gaac0c29 (Mar 31 2021 - 22:21:45 +0800)

DRAM:  948 MiB
RPI 3 Model B+ (0xa020d3)
MMC:   mmc@7e202000: 0, sdhci@7e300000: 1
Loading Environment from FAT... OK
In:    serial
Out:   serial
Err:   serial
Net:   No ethernet found.
starting USB...
USB0:   scanning bus 0 for devices... 4 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0
16706048 bytes read in 695 ms (22.9 MiB/s)
## Flattened Device Tree blob at 01000000
   Booting using the fdt blob at 0x1000000
   reserving fdt memory region: addr=0 size=1000
   Loading Device Tree to 000000003af3d000, end 000000003af473a4 ... OK

Starting kernel ...

I/TC: Secondary CPU 1 initializing
I/TC: Secondary CPU 1 switching to normal world boot
I/TC: Secondary CPU 2 initializing
I/TC: Secondary CPU 2 switching to normal world boot
I/TC: Secondary CPU 3 initializing
I/TC: Secondary CPU 3 switching to normal world boot
D/TC:3   tee_entry_exchange_capabilities:102 Dynamic shared memory is disabled
D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA 7011a688-ddde-4053-a5a9-7b3c4ddf13b8
D/TC:? 0 tee_ta_init_pseudo_ta_session:312 Open device.pta
D/TC:? 0 tee_ta_init_pseudo_ta_session:329 device.pta : 7011a688-ddde-4053-a5a9-7b3c4ddf13b8
D/TC:? 0 tee_ta_close_session:514 csess 0x1017ab30 id 1
D/TC:? 0 tee_ta_close_session:533 Destroy session
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.4.83-v8 (anna@anna-virtual-machine) (gcc version 9.2.1 20191025 (GNU Toolchain for the A-profile Architecture 9.2-2019.12 (arm-9.10))) #1 SMP PREEMPT Wed Mar 31 20:56:00 CST 2021
[    0.000000] Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
[    0.000000] printk: debug: ignoring loglevel setting.

**Comment by etienne-lms** [comment]
> I refer to the boot process of rpi3. When the primary core returns to the normal world and starts to jump to uboot to execute, optee will print some information again. Why? Is it possible to enter optee again? When the secondary cores return to the normal world, some TA information will be printed before starting Linux. Why?
I guess, if there is no optee driver in Linux, will it not be able to complete Linux startup even if optee is successfully started?

Sorry I don't understand the question.
The rpi3 traces above reflect the following boot sequence:

>
> _TF-A/BL2 has already loaded TF-A/BL31, OP-TEE and U-Boot images (no trace!)_
> _TF-A/BL31 has called OP-TEE initialization (no trace!)._
> ```bash
> I/TC: Primary CPU switching to normal world boot
> ```
> _The above OP-TEE core info trace (`I/TC: `) shows OP-TEE has initialized and returns to TF-A/BL31_
> ```bash
> INFO: BL31: Preparing for EL3 exit to normal world
> INFO: Entry point address = 0x11000000
> INFO: SPSR = 0x3c9
> ```
> _TF-A/BL31 is now booting the non-secure wolrd: U-Boot_
> ```bash
> U-Boot 2019.01-00093-gaac0c29 (Mar 31 2021 - 22:21:45 +0800)
> DRAM: 948 MiB
> RPI 3 Model B+ (0xa020d3)
> (...)
> Starting kernel ...
> 
> ```
> _For here, Linux boots but console driver is not yet probed. No trace._
> _Linux requests secondary core to boot up (no trace since not console device yet)._
> _Secondary core boots up, reaches OP-TEE init that end with trace:_
> ```
> I/TC: Secondary CPU 1 initializing
> I/TC: Secondary CPU 1 switching to normal world boot
> I/TC: Secondary CPU 2 initializing
> I/TC: Secondary CPU 2 switching to normal world boot
> I/TC: Secondary CPU 3 initializing
> I/TC: Secondary CPU 3 switching to normal world boot
> ```
> _Then Linux probes optee driver and exchanges capabilities with OP-TEE._
> _We only see OP-TEE traces:_
> ```
> D/TC:3 tee_entry_exchange_capabilities:102 Dynamic shared memory is disabled
> ```
> _Then Linux optee driver enumerates some OP-TEE services (through device.pta):_
> _Again we only see the OP-TEE traces:_
> ```
> D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA 7011a688-ddde-4053-a5a9-7b3c4ddf13b8
> D/TC:? 0 tee_ta_init_pseudo_ta_session:312 Open device.pta
> D/TC:? 0 tee_ta_init_pseudo_ta_session:329 device.pta : 7011a688-ddde-4053-a5a9-7b3c4ddf13b8
> D/TC:? 0 tee_ta_close_session:514 csess 0x1017ab30 id 1
> D/TC:? 0 tee_ta_close_session:533 Destroy session
> ```
> _At some point, the console device is probed and Linux kernel prints out traces from its log message buffer:_
> ```
> [ 0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]`
> [ 0.000000] Linux version 5.4.83-v8 (anna@anna-virtual-machine) (gcc version 9.2.1 20191025 (GNU Toolchain for the A-profile Architecture 9.2-2019.12 (arm-9.10))) #1 SMP PREEMPT Wed Mar 31 20:56:00 CST 2021`
> [ 0.000000] Machine model: Raspberry Pi 3 Model B Plus Rev 1.3`
> (...)
> ```
> _Liunx and OP-TEE are up and ready._

I hope the description above is clear.

>
> How can I be sure that Optee has been successfully started?

From your initial log (see below) we see a secondary core has booted hence I think Linux has started to boot.

> ```bash
> I/TC: Primary CPU switching to normal world boot
>```
> _Primary core has completed OP-TEE initialization, it returns to TF-A/BL31:_
> ```bash
> rc:1679169708
> INFO: opteed-init: Finished
> INFO: BL32 Initialized
> INFO: bl31_1
> INFO: BL31: Preparing for EL3 exit to normal world
> INFO: Entry point address = 0x44080000
> INFO: SPSR = 0x3c5
> INFO: bl31_2
> INFO: bl31_3
> 
>```
> _TF-A/BL31 now branches primary boot core to Linux entry. During its init, Linux enables secondary core which reaches OP-TEE init, hence the below OP-TEE trace_
> ```bash
> I/TC: Secondary CPU 1 initializing
> I/TC: Secondary CPU 1 switching to normal world boot
> ```
> _Secondary core now is expected to reach Linux secondary core entry point. BL31 should route this execution (PSCI sequence)_

Why don't you see Linux traces?
Maybe Linux simply fails to output traces to the console device but has successfully booted.
Or maybe Linux primary boot core (and likely also the secondary boot core) is stuck somewhere in the Linux kernel init sequence before console device probing. In the later case, you would get more info with Linux LL_DEBUG & earlyprintk.
