### ISSUE TITLE
optee os porting

### ISSUE THREAD

**Issue by kola-hash** [OP-TEE/optee_os#4794]
Hi everybody~
I’m porting Optee to the hi3559av100 platform recently. I have encountered a few questions and would like to ask everyone to help me answer them. 
1. Is the device tree required to start optee?
2. how do I set bl32_ep->spsr ? Is it correct according to the following statement? 
    bl32_ep->spsr = SPSR_64(MODE_EL1, MODE_SP_ELX, DISABLE_ALL_EXCEPTIONS);
3. Do I need to define the assembly function for platform initialization by myself? 
    I modified it by referring to the platform hi3519av100 which is officially supported by Optee. I saw that hi3519av100 not only includes main.c sub.mk platform_config.h conf.mk, but also hi3519av100_plat_init.S psci.c. What is the role of these two files, is it a function that must be defined by myself?

**Comment by jforissier** [comment]
Hello @kola-hash,

1. No, DT is not required. Some platforms do not use DT at all, for example HiKey960:
    ```
    $ make -j10 -s PLATFORM=hikey-hikey960
    $ grep -w CFG_DT out/arm-plat-hikey/conf.mk
    CFG_DT=n
    $
    ```
    Using DT is convenient if you want to re-use drivers based on DT, for example `core/kernel/console.c` will parse the `secure-chosen` and `chosen` nodes in DT to find out which UART to use. But it is not mandatory.
2. I don't know ;)
3. Platform initialization code (as in `hi3519av100_plat_init.S`) is really platform-specific... it depends on what needs to be done when entering the secure OS. If you need to do things not yet done by TF-A it can be useful. But not mandatory.
    As for PSCI, it is the Power State Coordination Interface, you need to implement these functions only if lower level firmware uses PSCI for power state management, I think it is a 32-bit only thing since the config name is `CFG_PSCI_ARM32` in OP-TEE but I will let other people who know this better comment further.

**Comment by etienne-lms** [comment]
3. I confirm @jforissier's feedback: **psci.c** and `CFG_PSCI_ARM32=y` 32bit architecture matters.

**Comment by kola-hash** [comment]
> 1. I confirm @jforissier's feedback: **psci.c** and `CFG_PSCI_ARM32=y` 32bit architecture matters.

so  64bit doesn't need right??
