### ISSUE TITLE
How to add the gcov option to ta

### ISSUE THREAD

**Issue by KFcghost** [OP-TEE/optee_os#4796]
My tests are stored in the opte_example directory.
In one test, I want to add a code coverage test to the TA.
So I modified the Makefile and sub.mk of TA and added the -lgcov option as follows:

//sub.mk
global-incdirs-y += include
srcs-y += hello_world_ta.c
cflags-hello_world_ta.c-y += -lgcov

//Makefile
CFLAGS += -fprofile-arcs -ftest-coverage
LDFLAGS+=-p -g -fprofile-arcs -ftest-coverage

I also modified the CMakeList.txt file in the parent directory to add compilation options and link libraries as follows:
//CMakeLists.txt
add_definitions(-fprofile-arcs -ftest-coverage)
target_link_libraries (${PROJECT_NAME} PRIVATE teec -fprofile-arcs -ftest-coverage)

When the gcno file is generated under out-br, but the gcda file cannot be generated after running, what should I do?

**Comment by jforissier** [comment]
Hi @KFcghost,

Sorry, `gcov` is not implemented for TAs.

**Comment by KFcghost** [comment]
> Hi @KFcghost,
> 
> Sorry, `gcov` is not implemented for TAs.

Thank you for your reply. Is there any way TA can test code coverage?

**Comment by jforissier** [comment]
> Thank you for your reply. Is there any way TA can test code coverage?

Not that I know of.

**Comment by KFcghost** [comment]
> > Thank you for your reply. Is there any way TA can test code coverage?
> 
> Not that I know of.

Thanks again for your reply.
