### ISSUE TITLE
OPTEE boot

### ISSUE THREAD

**Issue by kola-hash** [OP-TEE/optee_os#4799]
I would like to ask about the problem that the cpu returns to the normal world to start Linux after optee is started. 
1、If the Linux kernel does not have an optee driver and tee_supplicant, can Linux be successfully started after tee is initialized?
2、 Why does optee print the information after the main core returns to the normal world and ATF has read the Linux mirror information? Has the cpu returned to optee again? 
3、How can I tell if Optee has been successfully started? When the bl32_init function is executed and successfully returns to bl31_main, does this mean that optee has been started normally?

**Comment by kola-hash** [comment]
4、The Linux version I use is 4.9.37, this version does not support optee driver, is there any way to solve this problem?

**Comment by kola-hash** [comment]
> 1: Yes
> 2: What information, "Secondary CPU xx switching to normal world boot"?
> 3: The most accurate way is by probing OP-TEE, but looking in the logs may be an option too while developing.
> 4: It is possible to cherry-pick the needed patches
> 
> ```shell
> git log --oneline drivers/tee include/uapi/linux/tee.h include/linux/tee_drv.h
> ```
> 
> on a recent kernel tree or perhaps the v4.19 stable tree should give an idea where to start.
The current print information is that the secondary core returns to the normal world, but the console is stuck here and no information is printed. I don’t know if optee has been successfully started, and I’m not sure where the program has been executed now. My Linux kernel  is configured as arm64, there is no early_printk function
Can the information printed according to the following optee indicate that optee has been successfully started?


The print information as follows :
D/TC:0   add_phys_mem:565 TEE_SHMEM_START type NSEC_SHM 0x61000000 size 0x00400000
D/TC:0   add_phys_mem:565 TA_RAM_START type TA_RAM 0x64500000 size 0x01c00000
D/TC:0   add_phys_mem:565 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x641bc000 size 0x00344000
D/TC:0   add_phys_mem:565 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x64160000 size 0x0005c000
D/TC:0   add_phys_mem:565 TEE_RAM_START type TEE_RAM_RO 0x64100000 size 0x00060000
D/TC:0   add_phys_mem:565 ROUNDDOWN((0x1F101000), CORE_MMU_PGDIR_SIZE) type IO_SEC 0x1f000000 size 0x00400000
D/TC:0   add_phys_mem:565 ROUNDDOWN((0x1F102000), CORE_MMU_PGDIR_SIZE) type IO_SEC 0x1f000000 size 0x00400000
D/TC:0   add_phys_mem:578 Physical mem map overlaps 0x1f000000
D/TC:0   add_phys_mem:565 SYS_CTRL_BASE type IO_SEC 0x12020000 size 0x00010000
D/TC:0   add_phys_mem:565 CPU_CRG_BASE type IO_SEC 0x12010000 size 0x00010000
D/TC:0   add_phys_mem:565 BOOTSRAM_BASE type IO_SEC 0x08000000 size 0x00010000
D/TC:0   add_phys_mem:565 CONSOLE_UART_BASE type IO_NSEC 0x12100000 size 0x00001000
D/TC:0   add_va_space:604 type RES_VASPACE size 0x00a00000
D/TC:0   add_va_space:604 type SHM_VASPACE size 0x02000000
D/TC:0   dump_mmap_table:722 type NSEC_SHM     va 0x5ec00000..0x5effffff pa 0x61000000..0x613fffff size 0x00400000 (pgdir)
D/TC:0   dump_mmap_table:722 type IO_SEC       va 0x5f000000..0x5f3fffff pa 0x1f000000..0x1f3fffff size 0x00400000 (pgdir)
D/TC:0   dump_mmap_table:722 type SHM_VASPACE  va 0x5f400000..0x613fffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0   dump_mmap_table:722 type RES_VASPACE  va 0x61600000..0x61ffffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0   dump_mmap_table:722 type TA_RAM       va 0x62300000..0x63efffff pa 0x64500000..0x660fffff size 0x01c00000 (smallpg)
D/TC:0   dump_mmap_table:722 type IO_NSEC      va 0x640cf000..0x640cffff pa 0x12100000..0x12100fff size 0x00001000 (smallpg)
D/TC:0   dump_mmap_table:722 type IO_SEC       va 0x640d0000..0x640dffff pa 0x12020000..0x1202ffff size 0x00010000 (smallpg)
D/TC:0   dump_mmap_table:722 type IO_SEC       va 0x640e0000..0x640effff pa 0x12010000..0x1201ffff size 0x00010000 (smallpg)
D/TC:0   dump_mmap_table:722 type IO_SEC       va 0x640f0000..0x640fffff pa 0x08000000..0x0800ffff size 0x00010000 (smallpg)
D/TC:0   dump_mmap_table:722 type TEE_RAM_RO   va 0x64100000..0x6415ffff pa 0x64100000..0x6415ffff size 0x00060000 (smallpg)
D/TC:0   dump_mmap_table:722 type TEE_RAM_RX   va 0x64160000..0x641bbfff pa 0x64160000..0x641bbfff size 0x0005c000 (smallpg)
D/TC:0   dump_mmap_table:722 type TEE_RAM_RW   va 0x641bc000..0x644fffff pa 0x641bc000..0x644fffff size 0x00344000 (smallpg)
D/TC:0   core_mmu_entry_to_finer_grained:754 xlat tables used 1 / 8
D/TC:0   core_mmu_entry_to_finer_grained:754 xlat tables used 2 / 8
D/TC:0   core_mmu_entry_to_finer_grained:754 xlat tables used 3 / 8
D/TC:0   core_mmu_entry_to_finer_grained:754 xlat tables used 4 / 8
D/TC:0   core_mmu_entry_to_finer_grained:754 xlat tables used 5 / 8
I/TC:
I/TC: OP-TEE version: Unknown (gcc version 6.3.0 (HC&C V1R3C00SPC200B005_20190606)) #1 2021年 08月 17日 星期二 09:24:21 UTC aarch64
I/TC: Primary CPU initializing
D/TC:0 0 boot_init_primary_late:1245 Executing at offset 0 with virtual load address 0x64160000
D/TC:0 0 call_initcalls:21 level 1 register_time_source()
D/TC:0 0 call_initcalls:21 level 1 teecore_init_pub_ram()
D/TC:0 0 call_initcalls:21 level 3 mobj_mapped_shm_init()
D/TC:0 0 mobj_mapped_shm_init:440 Shared memory address range: 5f400000, 61400000
D/TC:0 0 call_initcalls:21 level 3 check_ta_store()
D/TC:0 0 check_ta_store:408 TA store: "Secure Storage TA"
D/TC:0 0 check_ta_store:408 TA store: "REE"
D/TC:0 0 call_initcalls:21 level 3 verify_pseudo_tas_conformance()
D/TC:0 0 call_initcalls:21 level 3 tee_cryp_init()
D/TC:0 0 call_initcalls:21 level 4 tee_fs_init_key_manager()
D/TC:0 0 call_initcalls:21 level 6 mobj_init()
D/TC:0 0 call_initcalls:21 level 6 default_mobj_init()
I/TC: Primary CPU switching to normal world boot
INFO:    opteed-init: Finished
INFO:    BL32 Initialized
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x44080000
INFO:    SPSR = 0x3c5
I/TC: Secondary CPU 1 initializing
I/TC: Secondary CPU 1 switching to normal world boot

**Comment by jenswi-linaro** [comment]
That looks like a normal boot in secure world. Note that the two lines:
```
I/TC: Secondary CPU 1 initializing
I/TC: Secondary CPU 1 switching to normal world boot
```
Is printed because the kernel requested CPU 1 to be brought up, typically via PSCI. So it's not triggered by the OP-TEE driver.

**Comment by kola-hash** [comment]
> That looks like a normal boot in secure world. Note that the two lines:

But why is it stuck in this position? Can these printed messages indicate that optee has been successfully started?

**Comment by kola-hash** [comment]
> That looks like a normal boot in secure world. Note that the two lines:
> 
> ```
> I/TC: Secondary CPU 1 initializing
> I/TC: Secondary CPU 1 switching to normal world boot
> ```
> 
> Is printed because the kernel requested CPU 1 to be brought up, typically via PSCI. So it's not triggered by the OP-TEE driver.
Another problem is that the soc I used has 5 cores, but here only two cores return to the normal world. Why is this?

**Comment by jenswi-linaro** [comment]
It looks like OP-TEE has initialized successfully. There are only a few instructions left to execute after that last line was printed so most likely is the CPU hanging somewhere else. Perhaps in TF-A.

**Comment by LIKEJMJJ** [comment]
sb
