### ISSUE TITLE
Interrupt driven TA

### ISSUE THREAD

**Issue by i-nevo** [OP-TEE/optee_os#4803]
Hi,
I'm trying to make a TA that is interrupt driven, i.e. it is loaded and initialized normally by calling the host executable under Linux and leaving the session open. I want this TA to perform some specific commands in response to secure interrupts.
I managed to define the required interrupts as EL1-S and registered an handler under OPTEE that is triggered by them. I now want to call a specific TA command and I tried to call the same routine that is used when calling from the non-secure world (e.g. `tee_ta_invoke_command`), using the same session that was assigned when first calling this TA from Linux. This doesn't work and I get assertions due to missing thread ID and trying to retrieve the same thread used when creating the session fails too.
Is there a simple way to build an interrupt driven TA? Can the TA commands be invoked from an interrupt handler?
Thanks in advance for your help.

**Comment by jenswi-linaro** [comment]
A TA cannot be invoked from an interrupt handler. Is there a particular reason why you need to do it from an interrupt handler?
There's some work ongoing to implement notifications, https://optee.readthedocs.io/en/latest/architecture/core.html#notifications, which may help a bit.

**Comment by i-nevo** [comment]
Hi,
Thanks for the fast response.
The system we are working on needs a trusted application to handle some HW events reported by interrupts. It seems that using non-secure interrupts that will be handled in Linux and trigger the "normal" mechanism of invoking a command through the tee-supplicant, ATF & OPTEE takes too much time for our RT needs. An EL1-S interrupt cuts most of the overhead time and seems fast enough for our needs.
I found that if I store the session & the thread ID used when creating the TA session (through Linux) I can use them to call directly the `enter_invoke_cmd` handler stored in the session and reach the TA Entry-Point in EL0-S. 
It's a bit of a "dirty" solution, but it works.

**Comment by jenswi-linaro** [comment]
> I found that if I store the session & the thread ID used when creating the TA session (through Linux) I can use them to call directly the `enter_invoke_cmd` handler stored in the session and reach the TA Entry-Point in EL0-S.
> It's a bit of a "dirty" solution, but it works.

I guess it works by luck and that secure world likely is otherwise idle.

**Comment by i-nevo** [comment]
So, if I understand it correctly, OPTEE doesn't support the handling of secured interrupts in EL0-S by a TA.

**Comment by jenswi-linaro** [comment]
That's correct.

**Comment by i-nevo** [comment]
Hi,
I'm coming back to this issue after some time of playing with this concept and trying various ways to use OPTEE for our needs.
We need a way to run a Real-Time (i.e. low latency) functionality that is interrupt driven in the secure world while controlling its ability to access secured resources. It seems to us that this functionality must run in EL0-S mode and the triggering must be a secure interrupt. As I wrote before, storing the session & thread info when creating the TA session and using them in the secure interrupt handler to invoke a TA command, seems to work for us, but you wrote it's probably just "luck" that nothing goes wrong. 
Is there a way to make sure nothing goes wrong with our improvised solution? What if we never call the TA directly from Linux (after it is loaded and initialized) and all its commands are invoked only by secure interrupts?
Can we limit the thread creating the TA session to run only for this specific TA (so each TA has its own OPTEE thread) thus preventing conflicts?
Are there other ways to reduce the OPTEE overhead when running TAs so it's a bit more Real-Time?

**Comment by etienne-lms** [comment]
An big issue is, I think, when running your interrupt context TA, OP-TEE core needs to use a resources protected by a mutex. If the resource access is locked, the system may deadlock.

**Comment by jenswi-linaro** [comment]
I agree, and I can't see any way around it either.
Does this interrupt handler really have to execute at S-EL0?
