### ISSUE TITLE
ECDSA Key Generation

### ISSUE THREAD

**Issue by rafagameiro** [OP-TEE/optee_os#4805]
Hi!

I'm trying to create a TA that generates a signature using the ECDSA P256 cryptography and sends the result back to the Normal World. The TA in specific was already used with other cryptographic schemes (RSA PKCS 1.5) and it seemed to work just fine. Now, while I was trying to use the ECDSA cryptography I couldn't generate the keypair.
I noticed that in this issue https://github.com/OP-TEE/optee_os/issues/3227, parameters were used to generate the key. Since the error I got while trying to generate the keypair was a TEE_ERROR_ITEM_NOT_FOUND, should I assume that I need those same parameters, p, x, and y if I want to successfully generate my keypair?

Best Regards

**Comment by jforissier** [comment]
Hi @rafagameiro,

According to the GP TEE Internal Core API spec, for `TEE_TYPE_ECDSA_KEYPAIR` you need to provide `TEE_ATTR_ECC_CURVE` and the `TEE_GenerateKey()` function generates `TEE_ATTR_ECC_PUBLIC_VALUE_X`, `TEE_ATTR_ECC_PUBLIC_VALUE_Y` and `TEE_ATTR_ECC_PRIVATE_VALUE`.

**Comment by rafagameiro** [comment]
Yes, it seems I was missing the Curve attribute to generate the keypair. Thank you!!
I'll try to be more careful and consult the GP TEE Internal Core API documentation when using these functions.

Since the issue was solve, I'll close it then
