### ISSUE TITLE
'register_pm_driver_cb' and 'pager'

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#4808]
When I open 'pager' on imx6q, OP-TEE initialization program always stops at `register_pm_driver_cb() -> register_pm_cb() -> verify_cb_args()` and call panic.

I think there is a high probability that `is_unpaged((void *)(vaddr_t)pm_hdl->callback) == 0` in `verify_cb_args()` causes the panic.

How to move `pm_hdl->callback` to an unpaged area?

**Comment by etienne-lms** [comment]
Use `DECLARE_KEEP_PAGER()` macro to ensure the function and its dependencies are in unpaged sections.
See for example [_stm32_etzpc.c_](https://github.com/OP-TEE/optee_os/blob/3.14.0/core/drivers/stm32_etzpc.c#L244).

**Comment by YogzZ** [comment]
It's very useful~
Thank you!
