### ISSUE TITLE
Mapping HW resources for TA

### ISSUE THREAD

**Issue by i-nevo** [OP-TEE/optee_os#4809]
Hi,
I try to build a TA that needs to access a mapped HW resource, but the TA panics when trying to access the resource address.
I tried using:
- `register_phys_mem(MEM_AREA_RES_VASPACE, RESOURCE_ADDRESS_BASE, RESOURCE_ADDRESS_SIZE);`
- `register_phys_mem(MEM_AREA_IO_SEC, RESOURCE_ADDRESS_BASE, RESOURCE_ADDRESS_SIZE);`
- `register_phys_mem(MEM_AREA_TA_VASPACE, RESOURCE_ADDRESS_BASE, RESOURCE_ADDRESS_SIZE);`
but none of them worked. How can I let the TA access the address range of this resource?
Thanks in advance.

**Comment by jforissier** [comment]
Hi @i-nevo, `register_phys_mem()` is for kernel space (S-EL1 i.e. OP-TEE core). There is currently no mechanism to map physical memory into TA VA space as far as I know.

**Comment by jforissier** [comment]
One option for you may be to write a pseudo-TA (PTA) and call it from your TA.
