### ISSUE TITLE
about TEE_Malloc

### ISSUE THREAD

**Issue by neil1899** [OP-TEE/optee_os#481]
hi，
in my *.ta, I want to TEE_Malloc（400*1024,0）， but it failed.
so I change the main.c of （platform-***）
#ifdef CFG_TEE_MALLOC_START
		a = CFG_TEE_MALLOC_START;
		s = CFG_TEE_MALLOC_SIZE;
#else

I define the CFG_TEE_MALLOC_SIZE 4*1024*1024. But, it also failed.

How can i do this case?

thanks in advance!

**Comment by pascal-brand-st-dev** [comment]
On all platforms but plat-sunxi, you should try to modify HEAP_SIZE defined in platform_config.h

On plat-sunxi, please have a look at kern.lds.S, and update the size at `teecore_heap_start` and `teecore_heap_end`

**Comment by neil1899** [comment]
hi, pascal:
my platform is similar as plat-sunxi, but when i change the teecore_heap_start and teecore_heap_end to
	teecore_heap_start = .;
	. += 0x300000 /*3M*/;
	teecore_heap_end = .;

it failed too.

**Comment by neil1899** [comment]
and I have change the size of TEE_RAM_SIZE to 4M

**Comment by jenswi-linaro** [comment]
The size of the heap for a TA is controlled by `TA_DATA_SIZE` in `user_ta_header_defines.h`. So far you've changed the heap used internally by the trusted OS.

**Comment by neil1899** [comment]
hi，jenswi

thanks so much！

**Comment by neil1899** [comment]
hi，jenswi：
I have change my #define TA_DATA_SIZE                (3 * 1024 * 1024) 3M

it still has some problem：

when i called TEE_AllocateOperation： it occurs that
ERR USER-TA:_assert_log:36: Assertion 'bn->prevfree == b->bh.bsize' failed at lib/libutils/isoc/bget.c:645
ERR TEE-CORE:tee_svc_sys_return_helper:192: TA panicked with code 0xffff0000 usr_sp 0x100520 usr_lr 0x20e391

I think it failed at op = TEE_Malloc(sizeof(*op), 0);

**Comment by neil1899** [comment]
algorithm is TEE_ALG_HMAC_SHA256, mode is TEE_MODE_MAC， maxKeySize is 192

**Comment by jenswi-linaro** [comment]
It looks like you have a overrun in a previously malloced buffer.

**Comment by neil1899** [comment]
hi，jenswi
what is the max size of TA_DATA_SIZE? what decides it?
thanks in advance?

**Comment by jenswi-linaro** [comment]
The total needed virtual memory space (stack, code, data, heap, parameters) has to fit in the range returned by core_mmu_get_user_va_range(). For v7 translation tables it's 31 MiB. There could be some other limitation but this one is the most explicit at least. We're usually never above 1 MiB of heap for TAs.

**Comment by neil1899** [comment]
hi，jenswi：
I do a test in my ta code，before i call TEE_AllocateOperation，
i call this function  TEE_Malloc（400 * 1024）， it can succeed。but TEE_AllocateOperation failed。op = TEE_Malloc(sizeof(*op), 0); can't succeed。I don‘t know why？

thanks in advance

**Comment by neil1899** [comment]
even if i don't call TEE_Malloc (400 *1024), TEE_AllocateOperation failed too. I think the size of op < 400*1024.

**Comment by jenswi-linaro** [comment]
If it always fails with
```
ERR USER-TA:_assert_log:36: Assertion 'bn->prevfree == b->bh.bsize' failed at lib/libutils/isoc/bget.c:645
```
I guess you have a corrupted heap for some reason.

**Comment by neil1899** [comment]
thanks so much, I have fix this bug, it's my ta fault.

**Comment by neil1899** [comment]
Dear all：
I found， if i change TA_DATA_SIZE in user_ta_header_defines.h, in my CA if i use the api TEEC_AllocateSharedMemory, invoke command error
log is ：

ERR [-146646036] TEEC:TEEC_InvokeCommand:412: Function returns with [-65529]
TEEC_InvokeCommand ERROR!

thanks in advance!

**Comment by neil1899** [comment]
because my CA is 32bit,so i have do the memset sharememory datastruct.
