### ISSUE TITLE
Xilinx ZynqMP, eFuse access

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#4810]
Hi,

The Zynqmp platform provides access to eFUSE registers via [TF-A ](https://github.com/Xilinx/arm-trusted-firmware/blob/master/plat/xilinx/zynqmp/pm_service/pm_api_sys.c#L1617)(which then uses IPI to the PMU perform the read/write operations).

When securing a board, some of those eFUSEs need to be written and while the documented process involves using a JTAG device for doing this, it would be very convenient to use u-boot and a TA to perform those operations.

Now, for that use case we have two options
1. have OP-TEE smc into TF-A 
2. have OP-TEE duplicate the IPI code from TF-A.

IMO smc into TF-A is a better choice (ie for maintainability reasons) but before going ahead we'd appreciate your input as we plan to upstream this functionality. any thoughts? which option would you rather merge (if any)?

**Comment by jenswi-linaro** [comment]
Doing SMC into TF-A sounds good to me.

**Comment by ldts** [comment]
awesome. thanks @jenswi-linaro
