### ISSUE TITLE
OPTEE Cryptographic Operations are very slow

### ISSUE THREAD

**Issue by vinethak** [OP-TEE/optee_os#4814]
Hello,
I am using OPTEE to generate keys, sign and verify for ECDSA - secp256r1 - SHA256 on iMX6 UL Controller.
The input file is 400 bytes.
The operations are successful, however, all three take more than 5 seconds each to complete the execution. This is not acceptable for my application.
If I execute a TA which does nothing inside and immediately returns in response to a command sent by CA; it takes about the 300ms. Therefore, my conclusion is that the cryptographic operations related functions that are used in my TA are consuming much time, especially, TEE_GenerateKey(), TEE_AsymmetricSignDigest(), TEE_AsymmetricVerifyDigest().
Any ideas?

**Comment by jenswi-linaro** [comment]
TEE_GenerateKey() is known to take quite a lot of time. It takes longer than what one may expect, but we've never been able to pinpoint the root cause.

**Comment by vinethak** [comment]
> TEE_GenerateKey() is known to take quite a lot of time. It takes longer than what one may expect, but we've never been able to pinpoint the root cause.

Thanks. Is there any reference timing available for iMX6 controller for key generation, signing and verifying for secp256r1 curve? Can anybody share their experience about the execution time?

**Comment by hannandor** [comment]
On 8/25/21 12:53 PM, vinethak wrote:
>
>     TEE_GenerateKey() is known to take quite a lot of time. It takes
>     longer than what one may expect, but we've never been able to
>     pinpoint the root cause.
>
> Thanks. Is there any reference timing available for iMX6 controller 
> for key generation, signing and verifying for secp256r1 curve? Can 
> anybody share their experience about the execution time?
>

Generating keys needs good RNG data. Depending of the system it could 
take longer time to have the proper random data to generate keys.

Regards,
    Nandor
