### ISSUE TITLE
How to get the result from TEE_DeriveKey()

### ISSUE THREAD

**Issue by matthew-chae** [OP-TEE/optee_os#4820]
Hi,

I need your help.
I'm calling the TEE_DeriveKey() API. I'm wondering How to get the return value.
I can find the below explanation.
-> On completion the derived key is placed into the TEE_ATTR_SECRET_VALUE attribute of the derivedKey 4414 handle.
For me, it's not enough to grasp the point.
How to get the result from TEE_ObjectHandle?
Can I get more detailed information?

Thanks,
Matthew

**Comment by jforissier** [comment]
Hello @matthew-chae,

You need to use `TEE_GetObjectBufferAttribute()`.

**Comment by matthew-chae** [comment]
Thank you. It's very helpful.
