### ISSUE TITLE
Usage of buffer after TEE_CheckMemoryAccessRights

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#4821]
I have a buffer privately allocated in the TA.
I access it as:

> res = TEE_CheckMemoryAccessRights(TEE_MEMORY_ACCESS_READ,
>                                                               buf,
>                                                               bufsize);

Later, i perform a write operation to this buffer as below:

> uint8_t byte_val = 30;
> TEE_MemFill(buf, byte_val, bufsize);

As the buffer is read-only, performing a memfill on this buffer is invalid and hence there should be some error being returned from TA end right?

**Comment by jforissier** [comment]
Hi,

How do you now the buffer is read-only? Why should it be? How did you allocate it? With `TEE_CheckMemoryAccessRights(TEE_MEMORY_ACCESS_READ, ...)` you checked that it is readable, not that it is not writable.

**Comment by Hussain1811** [comment]
There doesn't seem to be an explicit flag for not writable

**Comment by jforissier** [comment]
But there is one for writable.

**Comment by Hussain1811** [comment]
Yes - that's true.
My test is basically to set the read flag and trying to perform a write on the buffer and seeing what happens.

**Comment by jforissier** [comment]
There is a misunderstanding: `TEE_CheckMemoryAccessRights()` checks the access rights, it doesn't set them.

**Comment by Hussain1811** [comment]
Ah - right
Thanks for the clarification.

Is there any way i can set the access rights on a buffer?

**Comment by jforissier** [comment]
No, it depends on the type of memory. For example, heap memory (`malloc()`/`TEE_Malloc()`) has RW access, same for the global variables in a C program (the `.bss` and `.data` sections) except when they are `const`, in which case the memory is read-only (`.rodata` section). The stack is obviously RW too.

**Comment by Hussain1811** [comment]
Yes.
That clears my doubts.
Shall be closing this issue.
Thanks.
