### ISSUE TITLE
The proper way to store data in the shared memory

### ISSUE THREAD

**Issue by matthew-chae** [OP-TEE/optee_os#4823]
Hello,

I need your advice. I'm trying to send the data from user space in Linux to Optee.
The data from userspace has been stored in the array(user_salt).
My question is how to store this data in the shared memory.

I wrote the following. 
In order to save the data in the shared memory, is the way that data is stored at the shm->kaddr proper?
Otherwise, can I get some ideas?

memcpy((char *)shm->kaddr, user_salt, MASTER_KEY_SZ);

param[0].attr = TEE_IOCTL_PARAM_ATTR_TYPE_MEMREF_INOUT;
param[0].u.memref.shm = shm; 
param[0].u.memref.size = MASTER_KEY_SZ;
param[0].u.memref.shm_offs = 0;

ret = tee_client_invoke_func(ctx, &inv_arg, param);

**Comment by jenswi-linaro** [comment]
The code above looks like kernel code while you talk about sharing data from Linux user space.

**Comment by matthew-chae** [comment]
I'm sorry for making some confusion.

My goal is below.
Salt from user space -> Kernel -> Optee.

My question is how to store the delivered data in the shared memory at the kernel space.
(The salt from user space is already stored in the user_salt  array.)
Is below correct or which way is the proper?
memcpy((char *)shm->kaddr, user_salt, MASTER_KEY_SZ);

**Comment by jenswi-linaro** [comment]
Depending of use case the proper way may very well be to do it all in user space.

**Comment by matthew-chae** [comment]
Thank you for this.
