### ISSUE TITLE
Linux breakdown with TZC open

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#4827]
When I fill the memory of Linux with TZC open, the Linux always breakdown at last. How can I solve the problem?

**Comment by jenswi-linaro** [comment]
I'm not sure I understand the issue. Is it related to OP-TEE?

**Comment by YogzZ** [comment]
Thank you for your prompt reply. This is indeed a problem in the category of UEFI and Linux, but there are too few cases where one computer runs multiple systems and restricts the memory area. 

I hope to find a solution to this problem in the OP-TEE community.

Sorry to trouble everyone in the community :)
