### ISSUE TITLE
TEE_Malloc api called with zero buffer size

### ISSUE THREAD

**Issue by athomasj** [OP-TEE/optee_os#4831]
Hi, I have a query for the behavior when TEE_Malloc API is called when size requested is zero.

The GPD_TEE_Internal_Core_API spec says that the returned buffer pointer is expected to be non-NULL and the TA should panic if the buffer is accessed for read/write.
Could anyone help to understand what is the expected behavior when we try to write to the buffer (with code like -> buf[0] = 2; or with TEE_MemFill)

Thanks

**Comment by jenswi-linaro** [comment]
A `0` size will internally be translated to at least size `1` which later is rounded up to nearest `2 * sizeof(long)` in `bget()`. So an access as you describe will go unnoticed.

**Comment by athomasj** [comment]
Okay. 
So do we need to actually care about when the spec says "TA should panic on accessing this buffer", or ignore the statement?

**Comment by jenswi-linaro** [comment]
**SHOULD** indicates a recommendation, so it's not a requirement. We can pass certification without this.
I wouldn't say that we ignore it, we've just not prioritized it. Feel free to propose a PR to fix this.

**Comment by athomasj** [comment]
Thank you for the clarification.

**Comment by Sadiq1811** [comment]
Hello @jenswi-linaro,
Sorry for commenting on a closed issue.

Could you please check https://github.com/OP-TEE/optee_os/pull/4834?

**Comment by athomasj** [comment]
re-opening this PR as some changes are proposed by @Sadiq1811

**Comment by athomasj** [comment]
Closing as the patch for this was merged. PR link -> https://github.com/OP-TEE/optee_os/pull/4834
