### ISSUE TITLE
Context Switch performance overhead

### ISSUE THREAD

**Issue by rafagameiro** [OP-TEE/optee_os#4835]
Hi!

I have been trying to measure the performance of some TAs I developed, from a Normal World and Secure World perspective. I started by registering the time spent to finish a set of operations, requested from the Normal World, and then did the same but from the Secure World.

I was expecting to have a lower times by executing the commands from the Secure World but the results turned out to be pretty much the same, which leaves to the question: Should I not observe the weight of the Context Switch overhead during the tests?
Since the results were identical I though of the following: the commands I am doing consists in calling a TA, and the TA will communicate with a series of other TAs through the `TEE_OpenTASession`, `TEE_InvokeTACommand` and `TEE_CloseTASession`. Is it possible that establishing this "communication channels" between the TAs, and switching the execution context between them, I'm creating some overhead that is mitigating the one generated by the Context Switch?

Please give your opinion regarding this matter.

Best Regards

**Comment by jenswi-linaro** [comment]
> Hi!
> 
> I have been trying to measure the performance of some TAs I developed, from a Normal World and Secure World perspective. I started by registering the time spent to finish a set of operations, requested from the Normal World, and then did the same but from the Secure World.

Switching world on especially ARMv7 doesn't take that many instructions so depending on how you're measuring it may not stand out that much. 

> 
> I was expecting to have a lower times by executing the commands from the Secure World but the results turned out to be pretty much the same, which leaves to the question: Should I not observe the weight of the Context Switch overhead during the tests?

You could try invoking a pseudo TA instead to avoid the added time to switch into another TA context. Perhaps you'll be able to observe some world switching overhead compared to when a user TA calls this TA. 

> Since the results were identical I though of the following: the commands I am doing consists in calling a TA, and the TA will communicate with a series of other TAs through the `TEE_OpenTASession`, `TEE_InvokeTACommand` and `TEE_CloseTASession`. Is it possible that establishing this "communication channels" between the TAs, and switching the execution context between them, I'm creating some overhead that is mitigating the one generated by the Context Switch?

If you measure the combined time for all these three operations then will the time needed for `TEE_OpenTAsession()` dominate. You should try to isolate `TEE_InvokeTACommand()` to get better accuracy.

**Comment by jenswi-linaro** [comment]
By the way, it would be interested to see the numbers you come up with. This is a question that pops up from time to time so it might even be worth adding something at https://optee.readthedocs.io/en/latest/ once there's a well understood result.

**Comment by rafagameiro** [comment]
> Switching world on especially ARMv7 doesn't take that many instructions so depending on how you're measuring it may not stand out that much.

I'm currently using an hikey960 board to run the tests and observe the results, and if I'm not mistaken the architecture is ARMv8, so it might not be because of that.

> You could try invoking a pseudo TA instead to avoid the added time to switch into another TA context. Perhaps you'll be able to observe some world switching overhead compared to when a user TA calls this TA.

I'm not sure I understood this. You mean the "main" TA that would communicate with the other TAs should be replaced by a pseudo TA so that I could observe better the context switch effects?


> If you measure the combined time for all these three operations then will the time needed for `TEE_OpenTAsession()` dominate. You should try to isolate `TEE_InvokeTACommand()` to get better accuracy.

Ok in that case I will try measure this way

**Comment by jenswi-linaro** [comment]
> > You could try invoking a pseudo TA instead to avoid the added time to switch into another TA context. Perhaps you'll be able to observe some world switching overhead compared to when a user TA calls this TA.
> 
> I'm not sure I understood this. You mean the "main" TA that would communicate with the other TAs should be replaced by a pseudo TA so that I could observe better the context switch effects?

When invoking a pseudo TA from a TA there's not really a context switch involved so you should be able to tell other overhead apart in this way. Same thing if you invoke a pseudo TA from normal world, you avoid the extra switch into a user TA so you can see the overhead of the world switch here.

**Comment by rafagameiro** [comment]
> When invoking a pseudo TA from a TA there's not really a context switch involved so you should be able to tell other overhead apart in this way. Same thing if you invoke a pseudo TA from normal world, you avoid the extra switch into a user TA so you can see the overhead of the world switch here.

With this, should I assume that there is a context switch similar mechanism between TAs? Even in the Secure World?

**Comment by jenswi-linaro** [comment]
> > When invoking a pseudo TA from a TA there's not really a context switch involved so you should be able to tell other overhead apart in this way. Same thing if you invoke a pseudo TA from normal world, you avoid the extra switch into a user TA so you can see the overhead of the world switch here.
> 
> With this, should I assume that there is a context switch similar mechanism between TAs? Even in the Secure World?

Yes, just as there's a context switch between processes in for instance Linux.

**Comment by rafagameiro** [comment]
I see, and by using a pseudo TA I could prevent the context switch between both the Normal and Secure World, and the Secure World TAs, right? 
If that's the case, how could I generate a pseudo-ta, and where should I place it in OP-TEE so that it could be called just like a User TA would?

**Comment by jenswi-linaro** [comment]
> I see, and by using a pseudo TA I could prevent the context switch between both the Normal and Secure World, and the Secure World TAs, right?

Using a pseudo TA only avoids the context switch to a user mode TA.

> If that's the case, how could I generate a pseudo-ta, and where should I place it in OP-TEE so that it could be called just like a User TA would?

See https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#pseudo-trusted-applications
