### ISSUE TITLE
How to enable/use pthreads on OPTEE OS?

### ISSUE THREAD

**Issue by abhinandanudupa** [OP-TEE/optee_os#4836]
Hello!
Currently I am working on a project which requires threads to work in OPTEE OS.
As a dependency of my compiled library, I need POSIX threads ( _libpthreads_ ) to be available on the OPTEE OS to run.

So far I have compiled the C Standard from newlib for the Math function and other dependencies but this one is yet to be resolved.

Can I get an idea on how I could get POSIX threads to work on OPTEE? Do I have to edit certain OPTEE flags and do other changes? Or should I just just compile the C Standard Library (static) from GNU with pthreads and and link it to my program?

`
pthread_mutex_unlock'
pthread_mutex_lock
pthread_mutex_init
pthread_create
getrlimit
pthread_setaffinity_np
`
These are just a few functions that I would need. Also mostly using just one TA should be the easiest to do, so I plan to have one TA spawning threads - if it is even remotely possible.

**Comment by jenswi-linaro** [comment]
> Hello!
> Currently I am working on a project which requires threads to work in OPTEE OS.
> As a dependency of my compiled library, I need POSIX threads ( _libpthreads_ ) to be available on the OPTEE OS to run.

I assume you mean in the TAs not in OP-TEE Core.

> 
> So far I have compiled the C Standard from newlib for the Math function and other dependencies but this one is yet to be resolved.
> 
> Can I get an idea on how I could get POSIX threads to work on OPTEE? Do I have to edit certain OPTEE flags and do other changes? Or should I just just compile the C Standard Library (static) from GNU with pthreads and and link it to my program?
> 
> `pthread_mutex_unlock' pthread_mutex_lock pthread_mutex_init pthread_create getrlimit pthread_setaffinity_np`
> These are just a few functions that I would need. Also mostly using just one TA should be the easiest to do, so I plan to have one TA spawning threads - if it is even remotely possible.

This might not be as straightforward as you originally thought. We've collected some thoughts on the matter in this linked document. https://docs.google.com/document/d/1a8usDgYcB5JCJTHM6oCfDK4r6laVoJmTZA4Du6OnyqU/edit?usp=sharing

**Comment by abhinandanudupa** [comment]
Sorry for the vagueness, but I think getting it in the OPTEE Core would be suited for our project.
Thank you for the response.

**Comment by jenswi-linaro** [comment]
We have thread synchronization in OP-TEE Core see `core/include/kernel/mutex.h`.

**Comment by abhinandanudupa** [comment]
Will look in to it

**Comment by abhinandanudupa** [comment]
Thank you.

**Comment by abhinandanudupa** [comment]
> We have thread synchronization in OP-TEE Core see `core/include/kernel/mutex.h`.

Thank you, I solved some of my issues.
