### ISSUE TITLE
An improper locking bug(e.g., deadlock) on the lock ltc_ecc_fp_lock

### ISSUE THREAD

**Issue by ycaibb** [OP-TEE/optee_os#4840]
Hi, developers, thank you for your checking. It seems the lock **ltc_ecc_fp_lock** is not released correctly when **cache_entry == NULL** in the function **ltc_ecc_fp_save_state**?

https://github.com/OP-TEE/optee_os/blob/203ee23d005b2cec2f21b5de334c5a246be32599/core/lib/libtomcrypt/src/math/fp/ltc_ecc_fp_mulmod.c#L1419-L1441

Best,

**Comment by jenswi-linaro** [comment]
I agree, this doesn't look right. Would you mind supplying a pull request to fix the issue?

**Comment by ycaibb** [comment]
@jenswi-linaro I would love to. I will create a PR soon.

**Comment by ycaibb** [comment]
I made a PR. Please take a look.

Also, I am reporting this to the upstream.
