### ISSUE TITLE
A question about kernel panic

### ISSUE THREAD

**Issue by matthew-chae** [OP-TEE/optee_os#4841]
Hi,

I'd like to ask for some help.
I hope to derive the key using TEE_DeriveKey().
To do that, I set up something required like following.

        res = TEE_AllocateTransientObject(TEE_TYPE_GENERIC_SECRET, TA_DERIVED_KEY_MAX_SIZE * 8,
					  &hkey);
	if (res != TEE_SUCCESS)
		goto out_op;
	attr[0].attributeID = TEE_ATTR_HKDF_IKM;
	attr[0].content.ref.buffer = (void *)ta_unique_key;
	attr[0].content.ref.length = TA_DERIVED_KEY_MAX_SIZE;
	attr[1].attributeID = TEE_ATTR_HKDF_SALT;
	attr[1].content.ref.buffer = (void *)hkdf_salt;
	attr[1].content.ref.length = salt_size;
	attr[2].attributeID = TEE_ATTR_HKDF_INFO;
	attr[2].content.ref.buffer = (void *)key_info;
	attr[2].content.ref.length = key_info_size;

	/* 4. Populate/assign the attributes with the key object */
	res = TEE_PopulateTransientObject(hkey, (TEE_Attribute *)&attr, 3);

However, it result in kernel panic and the reason is the "Items not found".
What did I make something wrong?
Can I get some ideas?

E/TC:? 0 
E/TC:? 0 TA panicked with code 0xffff0008
E/LD:  Status of TA 78911928-eb1e-427f-87dd-f28158156f28
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0x00500000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0x00502000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000e000 pa 0x0050a000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x4000f000 pa 0x0050b000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40013000 pa 0x0050f000 size 0x001000 flags r--s
E/LD:  region  5: va 0x40014000 pa 0x00528000 size 0x005000 flags rw-s (stack)
E/LD:  region  6: va 0x40019000 pa 0x00c01000 size 0x001000 flags rw-- (param)
E/LD:  region  7: va 0x4007f000 pa 0x00001000 size 0x010000 flags r-xs [0]
E/LD:  region  8: va 0x4008f000 pa 0x00011000 size 0x008000 flags rw-s [0]
E/LD:   [0] 78911928-eb1e-427f-87dd-f28158156f28 @ 0x4007f000
E/LD:  Call stack:
E/LD:   0x00000000400818a4
E/LD:   0x000000004007f4cc
E/LD:   0x00000000400864b4
E/LD:   0x000000004007f77c
D/TC:? 0 user_ta_enter:177 tee_user_ta_enter: TA panicked with code 0xffff0008

Thanks in advance

**Comment by etienne-lms** [comment]
I think the implementation expects `TEE_TYPE_HKDF_IKM` as key type identifier, not `TEE_TYPE_GENERIC_SECRET`.

**Comment by matthew-chae** [comment]
Thank you for your help. I tried as your recommendation. But, the result is the same.
I run the below code at this time. Nothing has been changed.
Can I get some more help?

	TEE_OperationHandle op_handle = TEE_HANDLE_NULL;
	TEE_ObjectHandle hkey = TEE_HANDLE_NULL;
	uint8_t huk_key[TA_DERIVED_KEY_MAX_SIZE] = { };
	TEE_Attribute attr[3] = { };

	res = TEE_AllocateOperation(&op_handle, TEE_ALG_HKDF_SHA512_DERIVE_KEY, TEE_MODE_DERIVE,
				    DERIVED_MASTER_KEY_MAX_SIZE * 8);
	if (res != TEE_SUCCESS)
		return res;

	res = derive_ta_unique_key(huk_key, sizeof(huk_key), NULL, 0);
	if (res) {
		EMSG("derive ta unique key failed: returned %#"PRIx32, res);
		goto out_op;
	}

	res = TEE_AllocateTransientObject(TEE_TYPE_HKDF_IKM, DERIVED_MASTER_KEY_MAX_SIZE * 8,
					  &hkey);
	if (res != TEE_SUCCESS)
		goto out_op;

	attr[0].attributeID = TEE_ATTR_HKDF_IKM;
	attr[0].content.ref.buffer = (void *)ta_unique_key;
	attr[0].content.ref.length = TA_DERIVED_KEY_MAX_SIZE;
	attr[1].attributeID = TEE_ATTR_HKDF_SALT;
	attr[1].content.ref.buffer = (void *)hkdf_salt;
	attr[1].content.ref.length = salt_size;
	attr[2].attributeID = TEE_ATTR_HKDF_INFO;
	attr[2].content.ref.buffer = (void *)key_info;
	attr[2].content.ref.length = key_info_size;

	/* 4. Populate/assign the attributes with the key object */
	res = TEE_PopulateTransientObject(hkey, attr, 3);
	if (res != TEE_SUCCESS)
		goto out_key;


Thanks,
Matthew

**Comment by etienne-lms** [comment]
The implementation seems to expect attribute `TEE_ATTR_HKDF_OKM_LENGTH`: see [`get_hkdf_params()`](https://github.com/OP-TEE/optee_os/blob/3.14.0/core/tee/tee_svc_cryp.c#L2712).

**Comment by etienne-lms** [comment]
by the way, note that you're facing a TA panic, not a kernel panic as the issue title suggests.

**Comment by matthew-chae** [comment]
Hi, 

Thank you for your help. 
I tried this as your recommendation, but the result is the same.
I added the code like following.

	attr[0].attributeID = TEE_ATTR_HKDF_IKM;
	attr[0].content.ref.buffer = (void *)ta_unique_key;
	attr[0].content.ref.length = TA_DERIVED_KEY_MAX_SIZE;
	attr[1].attributeID = TEE_ATTR_HKDF_SALT;
	attr[1].content.ref.buffer = (void *)hkdf_salt;
	attr[1].content.ref.length = salt_size;
	attr[2].attributeID = TEE_ATTR_HKDF_INFO;
	attr[2].content.ref.buffer = (void *)hkdf_info;
	attr[2].content.ref.length = hkdf_info_size;
	attr[3].attributeID = TEE_ATTR_HKDF_OKM_LENGTH;
	attr[3].content.value.a  = 64;
	attr[3].content.value.b  = 0;

	res = TEE_PopulateTransientObject(hkey, attr, 4);
	if (res != TEE_SUCCESS)
		goto out_key;

And your recommendation comes from TEE_ERROR_BAD_PARAMETERS.
My error results from 0xffff0008.
Can I get more help? I really appreciate your help.

BTW, you're correct. This is the TA panic.
Sorry for making confusion.

**Comment by matthew-chae** [comment]
Hi again,

I have another question based on your guide.

If TEE_TYPE_HKDF_IKM is selected instead of TEE_TYPE_GENERIC_SECRET.
Below code triggers TEE_Panic in the TEE_DeriveKey().
	if (key_info.objectType != TEE_TYPE_GENERIC_SECRET)
		TEE_Panic(0);

Can you give me some guide?

Thanks,
Matthew

**Comment by jforissier** [comment]
Input key shall be `TEE_TYPE_HKDF_IKM`, output key shall be `TEE_TYPE_GENERIC_SECRET`.

There are HKDF tests in xtest and they pass so maybe you can use them as a reference (there is no SHA512 test though).
https://github.com/OP-TEE/optee_test/blob/3.14.0/host/xtest/regression_8000.c#L313-L446 `xtest 8001`

**Comment by matthew-chae** [comment]
It was very helpful. I appreciate your help.
