### ISSUE TITLE
OP-TEE Allocated Space

### ISSUE THREAD

**Issue by rafagameiro** [OP-TEE/optee_os#4848]
Greetings,

I have an AOSP + OP-TEE system setup on my hikey960 and I was wondering if I could measure the allocated space by OP-TEE.
I tried the android tool dumpsys [1], and I saw one process, `android.hardware.gatekeeper@1.0-service.optee`, that should have some relation with OP-TEE but I can't confirm if it is the OP-TEE system itself. 
Is there currently any way to figure out the allocated space by OP-TEE, given this system setup?

Best Regards

[1] https://developer.android.com/studio/command-line/dumpsys

**Comment by etienne-lms** [comment]
OP-TEE uses 2 secure memory areas called TEE_RAM and TA_RAM. See [generic_ram_layout.h (3.14.0)](https://github.com/OP-TEE/optee_os/blob/3.14.0/core/arch/arm/include/mm/generic_ram_layout.h#L62) for details.

TEE_RAM stores OP-TEE core. check `./scripts/mem_usage.py path/to/tee.elf` to get the values.

TA_RAM stores other secure memory objects as TAs memories and some temporary buffers.
You can use `xtest --stats --alloc` to see OP-TEE core heap allocation level and TA_RAM allocation level.

End the end, the memory used depends on the TAs and usecases.

**Comment by rafagameiro** [comment]
But considering my setup, how should I be able to use the mem_usage on the tee.elf, or even call the xtest? Its just that when I start the board, the system automatically boots into Android and I can only observe the logs from Secure World through the UART component.

**Comment by etienne-lms** [comment]
You mean you use an OP-TEE image you have no control one nor access to its related ELF file, build env etc...?
I think you need to ask your OP-TEE provider for the information you're asking for.

**Comment by rafagameiro** [comment]
After the system AOSP + OP-TEE is flushed into my board, as far as I can remember, I can only access its files using adb. I could also try to access the files before the system compilation, but of course I would not be able to get the desired occupancy space.

**Comment by vchong** [comment]
@rafagameiro Did you not buy the UART serial mezzanine board [1]? You need that to access the console. With it, you can also setup ADB for 'remote' access. If you already have access to ADB, you can just run `adb shell` from a PC terminal to access the console of your board 'remotely'.

[1] https://www.96boards.org/product/uartserial

**Comment by rafagameiro** [comment]
Ahh yes yes you are right, I completely forgot about the console that I can access with the UART component. And through that console I can access the xtest I assume? And what about the mem_usage script? Is it also included in the OP-TEE files or do I have to include it myself?

**Comment by vchong** [comment]
The `mem_usage.py` script is run from the build or host machine, i.e. your PC. Try this from the root of your build dir:
`./optee/optee_os/scripts/mem_usage.py optee/optee_os/out/arm-plat-hikey/core/tee.elf`

`xtest` is run from the console or adb shell.

**Comment by rafagameiro** [comment]
I was to successfully get both the TEE_RAM and TA_RAM!
Using the `mem_usage.py` script, as you referred @vchong, I got the TEE_RAM and using the `xtest --stats --alloc`, like you said @etienne-lms , to get the TA allocated space (TA_RAM)

Considering the question was answered, I'll now close this issue.
Thank you for the help!
