### ISSUE TITLE
Can OP-TEE call/use ARM-TF somehow?

### ISSUE THREAD

**Issue by loblik** [OP-TEE/optee_os#4849]
I have a following situation. There is TRNG device used by ARM-TF. I understand there is a platform service in ARM-TF which rich system like Linux uses to get entropy.

Is there some interface which can be used to expose these devices/services to OP-TEE too? Or how is this solved in general when multiple execution environemnts needs access to some device?

**Comment by jenswi-linaro** [comment]
There's an SMC interface https://developer.arm.com/documentation/den0098/latest

**Comment by loblik** [comment]
I know. I was asking if OP-TEE can aslo use this ARM-TF device somehow? I thought only normal world can do SMC.

**Comment by jenswi-linaro** [comment]
Secure world does SMC too.

**Comment by loblik** [comment]
Thanks. Is there some example in the source? All I can grep seems to be "server" code (SMC handling in OP-TEE).

Maybe just to give some more context. iMX8 has CAAM subsystem which implements TRNG. If I want to have access to TRNG also from normal world using that standard SMC interface I have two options I guess:

1) Have CAAM TRNG driver in OP-TEE and "route" SMC calls from ARM-TF to OP-TEE.
2) Have CAAM TRNG driver in ARM-TF and use standard SMC interface also from OP-TEE.

Currently for older iMX platforms both ARM-TF and OP-TEE have some CAAM code.

Is there some prefered way in upstream how to do this? I mean where these platform drivers should be in case both worlds need access?

**Comment by jforissier** [comment]
I think OP-TEE calling into TF-A (ARM-TF) is quite reasonable. Related: https://github.com/OP-TEE/optee_os/issues/4810 and https://github.com/OP-TEE/optee_os/pull/4873 which introduces a SMC call wrapper.

**Comment by jenswi-linaro** [comment]
Note that we already have a `thread_smccc()` doing this too.
