### ISSUE TITLE
Where to buy ST and TI development board?

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#485]
Hi, 
I want to buy some development boards which support OP-TEE. I invest all the development boards supported by OP-TEE, and know how to buy almost all of them. However, I don't find any information where to buy the STiH310/h410/h416 and the TI DRA7xx development boards.

Can anybody tell me how to buy the ST and TI development boards that supported by OP-TEE?

**Comment by pascal-brand-st-dev** [comment]
Unfortunately, the purpose of the ST boards is not for development.

If you want to get a platform for OP-TEE development, you can get a Hikey board (https://www.96boards.org/products/ce/hikey/). It's an ARMv8-based board and is already integrated with OP-TEE and ATF (https://github.com/OP-TEE/manifest#5-hikey).

**Comment by jamescfkung** [comment]
Since many people ask where to buy a development board supporting OP-TEE, should we add a shopping guide in OP-TEE OS main page?

**Comment by pascal-brand-st-dev** [comment]
Right, we can add a note in https://github.com/OP-TEE/optee_os#3-platforms-supported. @jamescfkung do you want to write it?

**Comment by jamescfkung** [comment]
Finished and submitted PR #487
