### ISSUE TITLE
How to enlarge single TA's RAM > 1G ?

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#4852]
According to issue #4762, I enlarge the address space to 44 bits, and the total ram of TA can be set over 4G. Thanks for your efforts!

But I find the ram of a single TA is always limited to 1G, Are there any methods to solve this problem?

**Comment by jenswi-linaro** [comment]
User mappings are currently only using one L1 entry, this corresponds to 1G of virtual address space. To increase that you'd need to expand this to use multiple L1 entries.

**Comment by jiangbinghua** [comment]
Which part of the code represents the user mapping space, and how should I modify it to make a single TA memory greater than 1G

**Comment by YogzZ** [comment]
@jenswi-linaro Hi, thank you for your answer, could you tell me where the file can I change the L1 entry number of user mappings?

**Comment by jenswi-linaro** [comment]
There's not a single place and the code currently assumes that only a single entry is used. A starting point could be `core_mmu_get_user_va_range()` in `core/arch/arm/mm/core_mmu_lpae.c`.

**Comment by YogzZ** [comment]
Thank you! Jens.
