### ISSUE TITLE
Relation between CFG_TEE_CORE_LOG_LEVEL & CFG_TEE_TA_LOG_LEVEL

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#4855]
I am compiling OPTEE with CFG_TEE_CORE_LOG_LEVEL=1.
I have a TA compiled with CFG_TEE_TA_LOG_LEVEL ?= 4.

I only see error logs (if any) from my TA and not the other debug (IMSG, DMSG, FMSG) logs.
To solve this and get the highest verbosity level (i.e. all IMSG, DMSG, FMSG) from my TA, i need to recompile the OPTEE with CFG_TEE_CORE_LOG_LEVEL=4?

If yes, this seems to be a bit of a hard-linked dependency right i.e. should both config settings be in sync? Reason for asking is, i don't want many logs from the TEE core just for the purpose of getting many logs from the TA.

**Comment by etienne-lms** [comment]
`CFG_TEE_CORE_LOG_LEVEL` defines OP-TEE core log level and does not affect TA traces.
There is a switch in core that must be enabled to get TA traces:  `CFG_TEE_CORE_TA_TRACE=y` (default value).

On TA side, you need to consider `CFG_TEE_TA_LOG_LEVEL` configuration at 2 places: when building your TA and when building the TA dev_kit from optee_os, specifically when building **libutee**.
This switch sets the TA log level supported in **libutee** which your TA will rely on, so if a log level is disabled in **libutee**, a TA cannot emit a trace for that level even if the TA was built with the max `CFG_TEE_TA_LOG_LEVEL=4`.

**Comment by Sadiq1811** [comment]
CFG_TEE_CORE_TA_TRACE is set to 'y' for me.
Also, i have `CFG_TEE_TA_LOG_LEVEL ?= 2` in ta_dev_kit.mk ==> is this the setting you were talking about?

**Comment by Hussain1811** [comment]
CFG_TEE_CORE_TA_TRACE is set to 'y' for me.
Also, i have CFG_TEE_TA_LOG_LEVEL ?= 2 in ta_dev_kit.mk ==> is this the setting you were talking about?

**Comment by etienne-lms** [comment]
> Also, i have CFG_TEE_TA_LOG_LEVEL ?= 2 in ta_dev_kit.mk ==> is this the setting you were talking about?

Yes...
However not that, actually, I was wrong. My apologies.
I looked back in the trace code and here is the status (stands for all 3.x.0 release tags, up to now):

* When ta_dev_kit (more precisely libutils) is built from  optee_os with `CFG_TEE_TA_LOG_LEVEL=0`, TA will never emit trace messages from `xMSG()` macros: `trace_printf()` implementation is stubbed.

* When ta_dev_kit is built with `CFG_TEE_TA_LOG_LEVEL` higher than 0:
  *  the OP-TEE OS TA libraries do use **this** log level 
  * TAs emit traces (using `xMSG()` macros) with the log level set by `CFG_TEE_TA_LOG_LEVEL` value when TA is built.

So building optee_os with `CFG_TEE_TA_LOG_LEVEL=1` and building your TA with `CFG_TEE_TA_LOG_LEVEL=3` will make the your TA implementation to emit error/info/debug trace messages.

**Comment by jforissier** [comment]
@etienne-lms do you think this comment could be improved a bit?
https://github.com/OP-TEE/optee_os/blob/3.14.0/mk/config.mk#L60-L64
Or perhaps your explanation should be in the OP-TEE doc?

**Comment by etienne-lms** [comment]
I think the description in **mk/config.mk** is fine and short: it summaries my above comment in few words.
I should have pointed this this description :)
Do you think OP-TEE docs deserves more details?

**Comment by jforissier** [comment]
> Do you think OP-TEE docs deserves more details?

Let's hear what @Hussain1811 has to say. @Hussain1811 hopefully you can finally get your traces, then if you think some step is not well documented feel free to propose a doc update (https://optee.readthedocs.io/en/latest/ source project is https://github.com/OP-TEE/optee_docs/). Perhaps how/where to define the `CFG_TEE_TA_LOG_LEVEL` definition is not clear and needs to be clarified. For example using ?=` in a Makefile will not override the default value if it appears after the point where the default value is defined; it should either be set before or with `:=` or `=`. Or perhaps something is not rebuilt as you would expect and some cleaning is required when changing the trace level.

**Comment by Hussain1811** [comment]
Hello @jforissier,
Hello @etienne-lms ,

ta_dev_kit is indeed built with CFG_TEE_TA_LOG_LEVEL higher than 0. 
Also, i have set CFG_TEE_TA_LOG_LEVEL to 3 with := and = too in my TA makefile.

Still i don't get any logs from the TA except for the EMSG.

One thing i forgot to mention is that i am not using an ARM based OPTEE. Maybe that's where the difference lies.

**Comment by jenswi-linaro** [comment]
> One thing i forgot to mention is that i am not using an ARM based OPTEE. Maybe that's where the difference lies.

Yes, that should be worth checking. By the way, which architecture is it? Is it a closed source fork?

**Comment by etienne-lms** [comment]
I strongly believe your issue is related to your build environment.
Maybe try `override CFG_TEE_TA_LOG_LEVEL := 3` in your TA Makefile.

**Comment by jforissier** [comment]
> I strongly believe your issue is related to your build environment.
> Maybe try `override CFG_TEE_TA_LOG_LEVEL := 3` in your TA Makefile.

...or pass `CFG_TEE_TA_LOG_LEVEL=3` to the make command line (should take precedence over everything)

**Comment by etienne-lms** [comment]
> ...or pass CFG_TEE_TA_LOG_LEVEL=3 to the make command line (should take precedence over everything)

Unless the goal was to have `CFG_TEE_TA_LOG_LEVEL=1` for the OP-TEE user TA libs (libutils, libutee, ...) and `CFG_TEE_TA_LOG_LEVEL=3` for the target TA internal implementation.

**Comment by jforissier** [comment]
> > ...or pass CFG_TEE_TA_LOG_LEVEL=3 to the make command line (should take precedence over everything)
> 
> Unless the goal was to have `CFG_TEE_TA_LOG_LEVEL=1` for the OP-TEE user TA libs (libutils, libutee, ...) and `CFG_TEE_TA_LOG_LEVEL=3` for the target TA internal implementation.

You're right. My suggestion assumes building the TA only. `override` is probably a good thing to try.

**Comment by Hussain1811** [comment]
It was indeed an issue with my build environment.
I wasn't pointing to the updated optee-os TA libraries during the compilation of my TA

**Comment by Hussain1811** [comment]
> > One thing i forgot to mention is that i am not using an ARM based OPTEE. Maybe that's where the difference lies.
> 
> Yes, that should be worth checking. By the way, which architecture is it? Is it a closed source fork?

An x86 OPTEE infact.
Yes - it's closed source.
