### ISSUE TITLE
Use API related to Persistent-Object in PTA

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#4858]
When I use API related to PersistentObject in PTA, it cannot work. So I try to use `syscall_storage_` to replace `TEE_xxxxPersistentObject`, but it also cannot work and it stops in the `is_user_ta_ctx(ctx)`. Would you give me some suggestions?

**Comment by jenswi-linaro** [comment]
The only thing TA in a PTA is that the interface looks like a TA from the outside. The code executes as any other code in OP-TEE privileged (core) code. The normal TA interfaces are not available. For an example of how secure storage can be used in OP-TEE core see the function `check_update_version()` in `core/kernel/ree_fs_ta.c`.

**Comment by YogzZ** [comment]
Thank you for your answer~ It's very useful.
