### ISSUE TITLE
Porting OP-TEE to NVidia Xavier-NX

### ISSUE THREAD

**Issue by goxul** [OP-TEE/optee_os#4862]
Hi,

Thank you for the work you're doing with OP-TEE, I'm learning a lot. 

I, currently, have a [Jetson Xavier NX](https://www.nvidia.com/en-in/autonomous-machines/embedded-systems/jetson-xavier-nx/) board with me, and I'd like to port OP-TEE to this. I saw the datasheet and it mentioned this:

>Full implementation of ARMv8.2 ISA compliant architecture including: 
    o ARMv8 TrustZone 
    
So I guess I should be able to configure OP-TEE on this board. Now, my questions are:

1.  How difficult a task would this be? I've never done something like this before, and nor do I have any specific knowledge of embedded devices. I understand the `platform_config.h`and  'conf.mk' quite a bit, but the 'main.c' seems pretty cryptic and different for every platform.  I just want a minimal system up and running so that I can run the `optee_hello_world` example and modify it according to my needs.  
2. I've gone through the FAQ and looked at the code of the other platforms as well. I see that all of them contain `conf.mk`, `main.c`, `platform_config.h' and `sub.mk'. However, some of them also contain other files (for eg, the `plat-hikey` folder contains `hikey_peripherals.h` and `spi_test.c`). Some of them also contain references to drivers which are platform-specific - would these files be proprietary? Also, how would I know if I need them or not i.e can I make do with just the four files which are common to all the folders?
3. Even if I do end building it, would the setup be similar to the QEMU build where I'd get a `buildroot' login system with minimal setup? (as @jbech-linaro mentions here in [#139](https://github.com/OP-TEE/optee_docs/issues/139) of optee_docs). I ask because there is another software that I'd like to install which runs on Linux, so I would need to install some other packages (like Python, make and some other dependencies).

Thanks for your time!

**Comment by jenswi-linaro** [comment]
> I, currently, have a [Jetson Xavier NX](https://www.nvidia.com/en-in/autonomous-machines/embedded-systems/jetson-xavier-nx/) board with me, and I'd like to port OP-TEE to this. I saw the datasheet and it mentioned this:
> 
> > Full implementation of ARMv8.2 ISA compliant architecture including:
> > o ARMv8 TrustZone
> 

It looks like the hardware is capable of running OP-TEE, but there might things in firmware that prevents you from doing a successful port. For instance:
1. Will likely need to be able to modify the firmware at EL3
2. Perhaps some other software is already used at S-EL1 which some other part of the software stack can't do without.
3. Depending on how the hardware is fused you may need some special private key in order to recompile and update EL3 and S-EL1.

> So I guess I should be able to configure OP-TEE on this board. Now, my questions are:
> 
> 1. How difficult a task would this be? I've never done something like this before, and nor do I have any specific knowledge of embedded devices. I understand the `platform_config.h`and  'conf.mk' quite a bit, but the 'main.c' seems pretty cryptic and different for every platform.  I just want a minimal system up and running so that I can run the `optee_hello_world` example and modify it according to my needs.

I'd recommend trying to update the firmware at EL3 first. For instance by adding a debug print, just to see that you're able to change something. Porting OP-TEE to a new platform is usually not that hard, but I guess it depends on where you're starting from.

> 2. I've gone through the FAQ and looked at the code of the other platforms as well. I see that all of them contain `conf.mk`, `main.c`, `platform_config.h' and `sub.mk'. However, some of them also contain other files (for eg, the `plat-hikey` folder contains `hikey_peripherals.h` and `spi_test.c`). Some of them also contain references to drivers which are platform-specific - would these files be proprietary? Also, how would I know if I need them or not i.e can I make do with just the four files which are common to all the folders?

Those four files should be a good start. Depending on the type of UART you may need to add another UART driver.

> 3. Even if I do end building it, would the setup be similar to the QEMU build where I'd get a `buildroot' login system with minimal setup? (as @jbech-linaro mentions here in [#139](https://github.com/OP-TEE/optee_docs/issues/139) of optee_docs). I ask because there is another software that I'd like to install which runs on Linux, so I would need to install some other packages (like Python, make and some other dependencies).

The buildroot setup we're using is primarily used for testing OP-TEE.

**Comment by ricardosalveti** [comment]
On another note, Jetson JetPack 5.0 is expected to have OP-TEE support (https://forums.developer.nvidia.com/t/jetson-software-roadmap-for-2h-2021-and-2022/177724).

**Comment by goxul** [comment]
In case someone reaches here in the future, the [developer version](https://developer.nvidia.com/jetpack-sdk-50dp) of Jetpack 5.0 was released, which uses OP-TEE has the default secure world OS.

**Comment by jforissier** [comment]
@goxul thanks for the update :+1:
