### ISSUE TITLE
Panic while checking code-execution aspect

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#4863]
The TEE internal api specification mentions that, there SHOULD NOT be code execution for the following blocks:
All blocks returned by TEE_Malloc or TEE_Realloc --> heap
All the local and global non-const C variables --> stack, data, bss
All const local or global C variables --> stack, data, bss

So, i tried to simulate this via a function pointer logic. for a memory block returned by TEE_Malloc() (i.e. heap)
Pseudo code:
```
void (*code_exec_func_ptr)(void) = NULL;
uint8_t code_stack[] = { 0xfe, 0xeb };
buf = TEE_Malloc(bufsize, TEE_MALLOC_FILL_ZERO);
if (!buf) {
        EMSG("No memory available");
        return TEE_ERROR_OUT_OF_MEMORY;
    }
 
 DMSG("Checking code execution for heap memory");
 code_exec_func_ptr = (void(*)(void))buf;
 TEE_MemMove(buf, code_stack, sizeof(code_stack));
 DMSG("before function pointer");
 /* calling the function pointer here */
 code_exec_func_ptr();
 DMSG("after function pointer");
```

But, i end up in a TA panic (not sure if it's a kernel panic or a TA panic)

Environment: QEMU 3.13

**Comment by Hussain1811** [comment]
Logs on secure console:
> D/TA:  ta_entry_call_memaccess_pass_by_val:244 Checking code execution for heap memory
> D/TA:  ta_entry_call_memaccess_pass_by_val:247 before function pointer
> D/TC:1 0 abort_handler:531 [abort] abort in User mode (TA will panic)
> E/TC:? 0 
> E/TC:? 0 User mode prefetch-abort at address 0x8012b500 (read permission fault)
> E/TC:? 0  esr 0x8200000f  ttbr0 0x200000e18d020   ttbr1 0x00000000   cidr 0x0
> E/TC:? 0  cpu #1          cpsr 0x20000100
> E/TC:? 0  x0  0000000000000000 x1  0000000000000047
> E/TC:? 0  x2  0000000000000000 x3  0000000080016380
> E/TC:? 0  x4  0000000000000001 x5  0000000000000000
> E/TC:? 0  x6  ffffffffffffffff x7  00000000800163a0
> E/TC:? 0  x8  0000000000000001 x9  0000000080130500
> E/TC:? 0  x10 0000000000000000 x11 0000000000000000
> E/TC:? 0  x12 0000000080016318 x13 000000000000000a
> E/TC:? 0  x14 00000000ffffffff x15 0000000000000020
> E/TC:? 0  x16 000000006fe17a30 x17 0000000000000000
> E/TC:? 0  x18 0000000000000000 x19 0000000080048c6d
> E/TC:? 0  x20 0000000080048000 x21 000000008012b500
> E/TC:? 0  x22 0000000080048c6d x23 0000000000000001
> E/TC:? 0  x24 0000000000000015 x25 0000000000000000
> E/TC:? 0  x26 0000000000000000 x27 0000000000000000
> E/TC:? 0  x28 0000000000000000 x29 0000000080016670
> E/TC:? 0  x30 000000008003c748 elr 000000008012b500
> E/TC:? 0  sp_el0 0000000080016670
> E/LD:  Status of TA 1638864a-5b96-4d50-921a-1a2a82fa4216
> E/LD:   arch: aarch64
> E/LD:  region  0: va 0x80004000 pa 0x0e300000 size 0x002000 flags rw-s (ldelf)
> E/LD:  region  1: va 0x80006000 pa 0x0e302000 size 0x008000 flags r-xs (ldelf)
> E/LD:  region  2: va 0x8000e000 pa 0x0e30a000 size 0x001000 flags rw-s (ldelf)
> E/LD:  region  3: va 0x8000f000 pa 0x0e30b000 size 0x004000 flags rw-s (ldelf)
> E/LD:  region  4: va 0x80013000 pa 0x0e30f000 size 0x001000 flags r--s
> E/LD:  region  5: va 0x80014000 pa 0x0e406000 size 0x003000 flags rw-s (stack)
> E/LD:  region  6: va 0x8003b000 pa 0x00001000 size 0x011000 flags r-xs [0]
> E/LD:  region  7: va 0x8004c000 pa 0x00012000 size 0x0e5000 flags rw-s [0]
> E/LD:   [0] 1638864a-5b96-4d50-921a-1a2a82fa4216 @ 0x8003b000
> E/LD:  Call stack:
> E/LD:   0x000000008012b500
> E/LD:   0x0000000080040b14
> E/LD:   0x000000008003d778
> D/TC:? 0 user_ta_enter:176 tee_user_ta_enter: TA panicked with code 0xdeadbeef
> D/TC:? 0 destroy_ta_ctx_from_session:324 Remove references to context (0x6fe807f8)
> D/TC:? 0 destroy_context:308 Destroy TA ctx (0x6fe807e0)
> D/TC:? 0 tee_ta_close_session:512 csess 0x6fe80840 id 1
> D/TC:? 0 tee_ta_close_session:531 Destroy session
>

**Comment by jforissier** [comment]
> But, i end up in a TA panic (not sure if it's a kernel panic or a TA panic)

It is a TA panic as mentioned in the debug message from the TEE Core(`D/TC`):
```
D/TC:1 0 abort_handler:531 [abort] abort in User mode (TA will panic)
```

This is the expected behavior, the TA has crashed.

Note that we have a few tests for invalid memory accesses in `xtest`, see here: https://github.com/OP-TEE/optee_test/blob/3.14.0/ta/os_test/os_test.c#L986-L1018 and here: https://github.com/OP-TEE/optee_test/blob/3.14.0/host/xtest/regression_1000.c#L854-L858. But there is no test for executing a memory buffer returned by `TEE_Malloc()` yet.

**Comment by Hussain1811** [comment]
Alright - thanks for pointing them out.
So, with the above pseudo code, can we conclude that code-execution of a memory buffer is happening (ideally it shouldn't as per spec) and hence we end up in a panic?

**Comment by jforissier** [comment]
**Attempt** to execute is happening, is caught by the TEE, which prevents actual execution from happening as per the spec.

**Comment by Hussain1811** [comment]
I was wondering whether TEE_ERROR_ACCESS_DENIED needs to be returned instead of ending up in a panic

**Comment by jforissier** [comment]
Trying to execute memory returned by `TEE_Malloc()` is an incorrect usage of the API. It is a "programmer error" that I think falls into the first item in section 2.3.3 Panics: "1. A Panic SHALL be raised when the implementation detects an avoidable programmer error and there is no specifically defined error code which covers the problem."

Besides, how could `TEE_ERROR_ACCESS_DENIED` be returned? By which function?

**Comment by Hussain1811** [comment]
I was basically thinking from a high level perspective. "SHOULD NOT allow code execution" seems like something should not have access to execute. Maybe returning an errno from the optee linux driver back to linux userspace?
Besides, in addition to memory returned by TEE_Malloc(), i tried to execute bss/data/stack memory -- ending up in a panic here too.

**Comment by Hussain1811** [comment]
Alright.
This clarifies my doubts.
Thanks.
