### ISSUE TITLE
Viewing IMSG, EMSG prints

### ISSUE THREAD

**Issue by vinethak** [OP-TEE/optee_os#4865]
Hallo,

Is there a way to divert the IMSG and EMSG prints towards the standard linux log file.
I want to be able to see these messages somewhere in the  non-secure environment.
I do not have a serial port to in my board.

Thanks.

**Comment by etienne-lms** [comment]
Sorry, there ain't.
IMSG(), EMSG() and friends all send trace messages to the OP-TEE console. All platforms currently supported in OP-TEE do route console traces to a UART-like driver. You would need to implement a RAM buffer console driver in OP-TEE and a mechanism for Linux kernel to retrieve them. Not straightforward. This has been somewhat discussed in the past but I can't find back an pointer.
