### ISSUE TITLE
Reducing the time for invoking a TA command

### ISSUE THREAD

**Issue by i-nevo** [OP-TEE/optee_os#4869]
Hi,
We try to implement a TA that is required to respond to real-time events as fast as possible. We see that when invoking a command in the TA, it takes about about 60K CPU instructions until we reach the TA handling routine, where about 90% of the instructions are from routine `vm_set_ctx` called from routine `update_current_ctx`. This happens also when there is just one active TA and the thread handles it exclusively.
I think that this mechanism can be more efficient if in the case of a single session the thread keeps the context of this session instead of deleting it when the TA finishes executing the invoked commend.
I tried avoid calling `vm_set_ctx` when there's no session in the thread session-stack (in routine `update_current_ctx`) so the thread context remains on consecutive TA commands and it seems to work and reduces the TA latency by 90%. 
Is that a safe solution to the TA latency, or am I missing here something?
Is there a better way to reduce the TA latency?

Thanks in advance.

**Comment by etienne-lms** [comment]
Keeping TA context loaded when there is only 1 TA running makes sense IMO. Maybe there are ways to extend that when several TAs are running. Can you create an RFC pull request to share your changes?

**Comment by i-nevo** [comment]
Please look at https://github.com/OP-TEE/optee_os/pull/4891
