### ISSUE TITLE
how to use the 'mdbg_check(1)' in TA 

### ISSUE THREAD

**Issue by Song-175** [OP-TEE/optee_os#4876]
Hi,
I'm a total beginner in OPTEE and I would like to use the <code>mdbg_check(1)</code> on the TA side.

to do that, I followed the instruction about OPTEE as below
https://github.com/OPTEE/optee_os/blob/master/mk/config.mk#L72

1. put the <code>mdbg_check(1)</code> command on dedicated place(like below malloc or calloc).
2. <code>make clean</code> before build optee and rebuild optee with the option below
<code>make CFG_TEE_TA_MALLOC_DEBUG=y CFG_TEE_TA_LOG_LEVEL=3</code>

and run the training session with my model.
but I could not find I/TC message generated by mdbg_check.

to mitigate this problem and apply the mdbg_check command in my code, I checked these pages: 
https://github.com/OP-TEE/optee_os/pull/2157
https://github.com/OP-TEE/optee_os/issues/2154
https://github.com/OP-TEE/optee_os/issues/3694

if any other instruction or proper way to use <code>mdbg_check(1)</code>, plz let me know.
Thanks in advance.

**Comment by jforissier** [comment]
Hi @Song-175,

It works for me. Test case ([QEMU](https://optee.readthedocs.io/en/latest/building/devices/qemu.html#build-instructions), note: a [fix](https://github.com/OP-TEE/optee_os/pull/4877) for `optee_test` is needed):
```diff
diff --git a/hello_world/ta/hello_world_ta.c b/hello_world/ta/hello_world_ta.c
index 2423b30..7a29fd1 100644
--- a/hello_world/ta/hello_world_ta.c
+++ b/hello_world/ta/hello_world_ta.c
@@ -30,6 +30,8 @@
 
 #include <hello_world_ta.h>
 
+#include <stdlib.h>
+
 /*
  * Called when the instance of the TA is created. This is the first call in
  * the TA.
@@ -60,6 +62,7 @@ TEE_Result TA_OpenSessionEntryPoint(uint32_t param_types,
 		TEE_Param __maybe_unused params[4],
 		void __maybe_unused **sess_ctx)
 {
+	void * p;
 	uint32_t exp_param_types = TEE_PARAM_TYPES(TEE_PARAM_TYPE_NONE,
 						   TEE_PARAM_TYPE_NONE,
 						   TEE_PARAM_TYPE_NONE,
@@ -80,6 +83,13 @@ TEE_Result TA_OpenSessionEntryPoint(uint32_t param_types,
 	 */
 	IMSG("Hello World!\n");
 
+	p = malloc(100);
+	IMSG("After malloc(100)");
+	mdbg_check(1);
+	free(p);
+	IMSG("After free()");
+	mdbg_check(1);
+
 	/* If return value != TEE_SUCCESS the session will not be created. */
 	return TEE_SUCCESS;
 }
```

```
build (master)$ m -rf ../optee_os/out/ ../out-br/build/optee*
build (master)$ make -j10 CFG_TEE_TA_MALLOC_DEBUG=y CFG_TEE_TA_LOG_LEVEL=2 run
...
==========
Welcome to Buildroot, type root or test to login
buildroot login: test
$ optee_example_hello_world
Invoking TA to increment 42
TA incremented value to 43
$
==========
I/TA: Hello World!
I/TA: After malloc(100)
I/TA: buffer: 100 bytes hello_world_ta.c:86
I/TA: buffer: 16 bytes lib/libutee/tee_api.c:407
I/TA: buffer: 12 bytes lib/libutils/ext/mempool.c:101
I/TA: buffer: 8 bytes lib/libutils/isoc/bget_malloc.c:808
I/TA: After free()
I/TA: buffer: 16 bytes lib/libutee/tee_api.c:407
I/TA: buffer: 12 bytes lib/libutils/ext/mempool.c:101
I/TA: buffer: 8 bytes lib/libutils/isoc/bget_malloc.c:808
I/TA: Got value: 42 from NW
I/TA: Increase value to: 43
==========
```

Please check `nm <your_TA_uuid>.elf | grep mdbg_malloc` and `nm libutils.a | grep mdbg_malloc` to make sure the function is present.

**Comment by Song-175** [comment]
Thanks for the quality response.

I tried what you explained, I think there is no mdbg_malloc function in libutils.a.
(I haven't checked the elf file cus I can not find my TA UUID yet. )

To re-link the libutils.a with CFG_TEE_TA_MALLOC_DEBUG, I heard that I have to compile(build) the TA with the option <code> make CFG_TEE_TA_MALLOC_DEBUG=y CFG_TEE_TA_LOG_LEVEL=3 </code> 

I checked this: https://github.com/OP-TEE/optee_os/pull/2157/commits/a77c3b30a065cad4200f4dfff7b53c80bd06c777
and I fixed the minor difference of my code with yours

but while build TA, I got errors below (ran 'make clean' optee before build it)

<pre>
<code>
/home/<OPTEE Folder>/optee_os/out/arm/export-ta_arm64/mk/link.mk:116: recipe for target 'out/7fc5c039-0542-4ee1-80af-b4eab2f1998d.elf' failed
make[3]: *** [out/7fc5c039-0542-4ee1-80af-b4eab2f1998d.elf] Error 1
package/pkg-generic.mk:247: recipe for target '/home/<OPTEE Folder>/out-br/build/optee_examples_ext-1.0/.stamp_built' failed
make[2]: *** [/home/<OPTEE Folder>/out-br/build/optee_examples_ext-1.0/.stamp_built] Error 2
Makefile:23: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/<OPTEE Folder>/out-br'
common.mk:311: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2
</code>
</pre>

When I tried to build without the option (just <code>make -j16 run</code>), I can not see any errors or problems. OPTEE works well but I can not use mdbg_check(1) as you expect.

I'm really sorry if I'm bothering you with minor errors that can be easily fixed. Thank you for your time.

Cheers

**Comment by jforissier** [comment]
Hi @Song-175,

> but while build TA, I got errors below (ran 'make clean' optee before build it)
> ```
> /home//optee_os/out/arm/export-ta_arm64/mk/link.mk:116: recipe for target 'out/7fc5c039-0542-4ee1-80af-b4eab2f1998d.elf' failed
> make[3]: *** [out/7fc5c039-0542-4ee1-80af-b4eab2f1998d.elf] Error 1
> package/pkg-generic.mk:247: recipe for target '/home//out-br/build/optee_examples_ext-1.0/.stamp_built' failed
> make[2]: *** [/home//out-br/build/optee_examples_ext-1.0/.stamp_built] Error 2
> ```

Please check the lines before these ones. You cut the useful information ;)

**Comment by Song-175** [comment]
Hi @jforissier 

oops I missed these parts of errors.

<pre>
<code>
/home/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: /home/optee/out-br/build/optee_examples_ext-1.0/darknetz/ta/convolutional_layer_TA.c:146: undefined reference to `mdbg_calloc'
/home/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: out/convolutional_layer_TA.o:/home/optee/out-br/build/optee_examples_ext-1.0/darknetz/ta/convolutional_layer_TA.c:147: more undefined references to `mdbg_calloc' follow
</code>
</pre>

Sorry for the inconvenience 
Cheers

**Comment by jforissier** [comment]
@Song-175 no worries. Clearly, your `libutils.a` is lacking the `mdbg_*()` functions.
Try `make optee-os CFG_TEE_TA_MALLOC_DEBUG=y; nm ../optee_os/out/arm/export-ta_arm64/lib/libutils.a | grep mdbg_`. You should see something similar to this:
```
0000000000000ce4 T mdbg_calloc
0000000000000e84 T mdbg_check
...
```

**Comment by Song-175** [comment]
HI @jforissier 

thanks for the response, I tried what you told me and I got the followings

<pre>
<code>
nm ~/opteeqemu/optee_os/out/arm/export-ta_arm64/lib/libutils.a | grep calloc
0000000000000940 T calloc
                                U calloc
0000000000000114 T mempool_calloc
</code>
</pre>

I got nothing when I tried <code> | grep mdbg_ </code>.
It seems that <code>CFG_TEE_TA_MALLOC_DEBUG=y</code> option doesn't work while compile.

I will check more related commits regarding 'ta_dev_kit.mk' and 'config.mk'.
Thanks for the help 

Cheers

**Comment by Song-175** [comment]
Hi again @jforissier 

I tried install new OPTEE in different environment and I finally got mdbg_calloc in libutils.a
<pre>
<code>
nm ~/opteeqemu/optee_os/out/arm/export-ta_arm64/lib/libutils.a | grep mdbg_
0000000000000a24 t gen_mdbg_free.constprop.0
0000000000000944 t gen_mdbg_realloc_unlocked.constprop.0
0000000000000ce4 T mdbg_calloc
0000000000000e84 T mdbg_check
0000000000000000 t mdbg_get_footer
0000000000000c30 T mdbg_malloc
0000000000000db4 T mdbg_memalign
0000000000000db0 T mdbg_realloc
                 U mdbg_malloc
                 U mdbg_malloc
                 U mdbg_calloc
                 U mdbg_malloc
</code>
</pre>

but while compile ta with <code> make CFG_TEE_TA_MALLOC_DEBUG=y CFG_TEE_TA_LOG_LEVEL=3 run </code>
encountered similar error like before:

<pre>
<code>
/tmp/dgboter/bbs/build04--cen7x86_64/buildbot/cen7x86_64--aarch64-none-linux-gnu/build/src/gcc/libgcc/unwind-dw2-fde.c:440: undefined reference to `malloc'
/home/song/opteeqemu/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: /tmp/dgboter/bbs/build04--cen7x86_64/buildbot/cen7x86_64--aarch64-none-linux-gnu/build/src/gcc/libgcc/unwind-dw2-fde.c:443: undefined reference to `malloc'
/home/song/opteeqemu/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: /home/song/opteeqemu/toolchains/aarch64/bin/../lib/gcc/aarch64-none-linux-gnu/10.2.1/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame':
/tmp/dgboter/bbs/build04--cen7x86_64/buildbot/cen7x86_64--aarch64-none-linux-gnu/build/src/gcc/libgcc/unwind-dw2-fde.c:136: undefined reference to `malloc'
/home/song/opteeqemu/build/../toolchains/aarch64/bin/aarch64-linux-gnu-ld.bfd: /home/song/opteeqemu/toolchains/aarch64/bin/../lib/gcc/aarch64-none-linux-gnu/10.2.1/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame_table':
/tmp/dgboter/bbs/build04--cen7x86_64/buildbot/cen7x86_64--aarch64-none-linux-gnu/build/src/gcc/libgcc/unwind-dw2-fde.c:184: undefined reference to `malloc'
/home/song/opteeqemu/optee_os/out/arm/export-ta_arm64/mk/link.mk:116: recipe for target 'out/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.elf' failed
</code>
</pre>

It seems to be recognized that malloc cannot be found because malloc has been replaced by mdbg_malloc.

When I tried the <code> nm ~/opteeqemu/optee_os/out/arm/export-ta_arm64/lib/libutils.a | grep malloc </code>, it shows only 
'mdbg_malloc' without 'malloc' : 

<pre>
<code>
$ nm ~/opteeqemu/optee_os/out/arm/export-ta_arm64/lib/libutils.a | grep malloc 
bget_malloc.o:
0000000000000f48 T malloc_add_pool
0000000000001030 T malloc_buffer_is_within_alloced
0000000000001128 T malloc_buffer_overlaps_heap
0000000000000000 d malloc_ctx
0000000000000bf8 T malloc_get_stats
0000000000000be0 T malloc_reset_stats
0000000000000c30 T mdbg_malloc
00000000000001f8 t raw_malloc_return_hook.constprop.0
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
                 U mdbg_malloc
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
                 U mdbg_malloc
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
                 U mdbg_malloc
0000000000000000 n wm4.malloc.h.15.97a2259a69cdbd2b6d276b1a4c49ab43
</code>
</pre>

I didn't change any code in OPTEE OS, no additional model or algorithm was applied in OPTEE. 
Compiling without any option (just <code>make run</code>, the 'malloc' exist in 'libutils.a' file. 

Please let me know if you have any advice or suggestions on this issue.

Cheers

**Comment by jforissier** [comment]
Please check https://github.com/OP-TEE/optee_os/pull/4877 (I mentioned that I met the issue above).

**Comment by Song-175** [comment]
Hi @jforissier,
Thank you for the help. 

It works perfectly as I expected with the exact output.
Appreciated.
