### ISSUE TITLE
System stopped when accessing peripheral banked register through syscall

### ISSUE THREAD

**Issue by janoslim** [OP-TEE/optee_os#4885]
Hello,

I am currently making driver on optee for CRYP of stm32mp157c-dk2 board which is crypto peripheral on cpu bus.
And I refer to linux driver source code already implemented.

for accessing reserved register address, I added following line in main.c
`register_phys_mem_pgdir(MEM_AREA_IO_NSEC, CRYP1_BASE, SMALL_PAGE_SIZE);`

and get access the address by,
`stm32_cryp_base = (vaddr_t)phys_to_virt(STM32_REG_BASE, MEM_AREA_IO_NSEC);`

and i make syscall through libutee in file arch_svc.c
`SYSCALL_ENTRY(syscall_stm32_cryp_init),
`
and in utee_syscalls_asm.S
`UTEE_SYSCALL _utee_stm32_cryp_init, TEE_SCN_CRYP_STM32_INITIALIZE, 3`

And i succussfully call syscall, by utee,
However, in syscall handler, system stopped when I access the register address I mentioned above.
(No kernel panic log or something but in few seconds log printed,
```
[   42.162947] rcu: INFO: rcu_sched detected stalls on CPUs/tasks:
[   42.167423] rcu: 	0-...0: (0 ticks this GP) idle=c4a/1/0x40000000 softirq=155/155 fqs=1050 
[   42.175755] 	(detected by 1, t=2102 jiffies, g=-819, q=21)
[   42.181234] Sending NMI from CPU 1 to CPUs 0:
```
)

I wonder what is the problem.

Thank you!!

Additionally, I added interrupt handler by following,
```
static struct itr_handler stm32_cryp_itr_handler = {
	.it = STM32MP1_IRQ_STM32_CRYP,
	.handler = stm32_cryp_it_handler,
};
......
itr_add(&stm32_cryp_itr_handler);
itr_enable(stm32_cryp_itr_handler.it);

static enum itr_return stm32_cryp_it_handler(struct itr_handler *handler __unused)
{
	DMSG("stm32_cryp_it_handler Called");
	STM32_CRYP_IRQ_STATUS = stm32_cryp_read(CRYP_MISR);

	/* Output FIFO IRQ: read data */
	// handle data...

	return ITRR_HANDLED;
}
```
I wonder what is required more to enable GIC interrupt.

Thank you alot.

**Comment by etienne-lms** [comment]
I think your issue is due to `stm32_cryp_it_handler()` being "pageable", as stm32mp1 enables OP-TEE pager.
Try add this:
```patch
 static enum itr_return stm32_cryp_it_handler(struct itr_handler *handler __unused)
 {
 	DMSG("stm32_cryp_it_handler Called");
 	STM32_CRYP_IRQ_STATUS = stm32_cryp_read(CRYP_MISR);
 
 	/* Output FIFO IRQ: read data */
	// handle data...
 
 	return ITRR_HANDLED;
 }
+DECLARE_KEEP_PAGER(stm32_cryp_it_handler);
```


For info, I think you should have the CRYP assigned to secure world.
Call `stm32mp_register_secure_periph_iomem(CRYP1_BASE);` at stm32_cryp driver init
and update iomem mapping:
```patch
-register_phys_mem_pgdir(MEM_AREA_IO_NSEC, CRYP1_BASE, SMALL_PAGE_SIZE);
+register_phys_mem_pgdir(MEM_AREA_IO_SEC, CRYP1_BASE, SMALL_PAGE_SIZE);
 (...)
-stm32_cryp_base = (vaddr_t)phys_to_virt(STM32_REG_BASE, MEM_AREA_IO_NSEC);
+stm32_cryp_base = (vaddr_t)phys_to_virt(STM32_REG_BASE, MEM_AREA_IO_SEC);

```

**Comment by janoslim** [comment]
@etienne-lms Thank you for your advice!

I just wonder what is register_phys_mem_pgdir for, because there are two register_phys_mem_pgdir() for both MEM_AREA_IO_NSEC and MEM_AREA_IO_SEC. and its accessability, such as is it okay for optee to access NSEC area?

**Comment by etienne-lms** [comment]
`register_phys_mem_pgdir(pa, size, MEM_AREA_IO_NSEC)` declares a static memory mapping for non-secure iomem.
`register_phys_mem_pgdir(pa, size, MEM_AREA_IO_SEC)` declares a static memory mapping for secure iomem.

When using CRYP1 in secure world, the SoC security hardening (firewalls) should forbid non-secure world from reaching CRYP1 iomem and resources. When so, your OP-TEE CRYP1 driver must access CRYP1 iomem with secure attribute, hence getting the virtual address of the secure mapped CRYP1 iomem: `phys_to_virt(STM32_REG_BASE, MEM_AREA_IO_SEC);`.

**Comment by janoslim** [comment]
Thank you!
