### ISSUE TITLE
How to directly access specific PA in MEM_AREA_DDR_OVERALL region after MMU enabled?

### ISSUE THREAD

**Issue by ChrisChi11** [OP-TEE/optee_os#4887]
In former version, plat-ls register their DRAM with register_dynamic_shm(), which set the region with MEM_AREA_RAM_NSEC.
I can directly access specific PA by core_add_mapping() first then use  core_mmu_get_va() to get the mapped VA.

After change my op-tee to version 3.13.
I found plat-ls used register_ddr() MACRO to set the DRAM region instead, which sets the region with  MEM_AREA_DDR_OVERALL attribute.
I wonder if I still want to access specific PA address in DRAM directly, how could I get its VA since core_add_mapping() not support this attribute?

**Comment by jenswi-linaro** [comment]
You can try the same technique as in `set_tmem_param()` with `CFG_CORE_RESERVED_SHM`, in `core/tee/entry_std.c`.
