### ISSUE TITLE
Is there any implementations of TMF(TEE Management Framework) in OP-TEE

### ISSUE THREAD

**Issue by helloworld2019** [OP-TEE/optee_os#4888]
Dear Mr @jenswi-linaro . 
  I am new to TEE and OPTEE. Recently I saw the content of TMF(TEE Management Framework) in the GP specification. Searching for related keywords such as TMF, SD, rootSD in the source code, I don't seem to have any relevant content. So, I want to ask if there is any implementation of TMF in OP-TEE. If not, does the developer need to implement the TMF function based on the functions provided by the existing OPTEE? For example, put a privileged "PTA" in OP-TEE to implement TMF? Thank you in advance for your help.

**Comment by jenswi-linaro** [comment]
OP-TEE doesn't support TMF yet. Some groundwork has been done, see `core/tee/tadb.c` which maintains a DB with TAs. Yes, I expect that some PTA will be needed. One thing to keep in mind is that the involved signatures should probably be kept so installed TAs can be verified with those each time a TA is loaded.
