### ISSUE TITLE
Question about Encrypted TAs

### ISSUE THREAD

**Issue by lxxstone** [OP-TEE/optee_os#4893]
Hi all,
I have carefully read the details of [[RFC] Add Framework to Support ree-FS Encrypted TAs](https://github.com/OP-TEE/optee_os/pull/3340) discussed here. There are several issues I would like to discuss with you again:
The scene：
Our TA has been developed by several third parties, and aes GCM key will be exposed when we export link.mk to them. Using the same key for encryption allows a third party to decrypt all ta's on this platform, and they also have the private key we export for signing.Then they can do whatever they want to the other ta, which is obviously not safe.What's more, the exported things may inadvertently leak out.

Q1.tee holds a private key and then exports the public key to encrypt the TA's AES key which is generated randomly at compile time.Then use the public key to encrypt the AES key and put the ciphertext into the TA header.This seems to be more secure, but it will increase overhead as an RSA decryption on our platform will take approximately 9ms. Any other suggestions?

Q2.Is the signature just to prevent the TA from being tampered with, or is it considered that the TA signed with this key is authenticated? We have some ideas to make the ta signature key randomly generated, then encrypt the public key used for verify signature with the public key exported to ta developer and put the ciphertext into the TA header. Any suggestions?

Q3.shdr_verify_signature () only verifies the signatures and hashes in the TA header. Will ldelf evaluate the hash again when loading the TA?

**Comment by jenswi-linaro** [comment]
@b49020, do you have any comments to this?

**Comment by lxxstone** [comment]
@b49020 Thank you for explaining my question in detail, so that I can understand the details of this part more clearly. I will sort it out according to some ideas you provided. If there is any doubt, I will come to ask again.
