### ISSUE TITLE
mutex_trylock() failed with assertion with itr_handler

### ISSUE THREAD

**Issue by janoslim** [OP-TEE/optee_os#4906]
Hello experts,

Currently I am implementing CRYP driver for stm32mp157c, and for reseach purpose i disabled pager and load optee on DRAM. I call mutex_trylock in interrupt handler to get lock.

My interrupt handler,
```
static enum itr_return stm32_cryp_it_handler(struct itr_handler *handler __unused)
{
	uint32_t CRYP_SR_VALUE = stm32_cryp_read(CRYP_SR);
	uint32_t STM32_CRYP_IRQ_STATUS = stm32_cryp_read(CRYP_MISR);

	/* Output FIFO IRQ: read data */
	if (STM32_CRYP_IRQ_STATUS & MISR_OUT)
	{
		if (CRYP_SR_VALUE & SR_OFFU)
		{
			// disable interrupt
			stm32_cryp_write(CRYP_IMSCR, 0);

			if (!mutex_trylock(&context_lock)) {
				DMSG("Lock Acquire Failed");
				return ITRR_HANDLED;
			}
.............

```
and i got error,
```
E/TC:0   assertion 'thread_get_id_may_fail() != THREAD_ID_INVALID' failed at core/arch/arm/kernel/mutex.c:134 <__mutex_trylock>
E/TC:0   Panic at core/kernel/assert.c:28 <_assert_break>
```
The reason why I got this error was that I suspected that a translation fault would occur when interleupt handler approached the vaddr area of the user TA before enabling the CFG_TEE_CORE_DEBUG option. 
firstly i got translation fault, when accessing data that given by userTA from my custom syscall. 
The strange thing is that if it is a translation fault, as far as I know, it is an error that occurs when mmu fails to map, but there is an error in the middle of the program running. For example, while accessing repeatedly the same vaddr area received from the TA to test the CRYP, a translation fault occurred in the middle.
I think this is a problem with spurious interrupt, so when setting up my interrupt during booting, I mask interrupt only cpu core #0, and experiment after deactivating cpu#1, however translation fault still occurred.

I wonder what thread_get_id_may_fail() is for, and I want to make clear that in op-tee, optee kernel (or interrupt handler running on optee) can access usrTA's vaddr directly?

Thank you

**Comment by jforissier** [comment]
Hi @janoslim,

You cannot use a mutex in an interrupt handler. Mutexes can only be used in a thread context. If you need to protect data from concurrent access by another core, you should use a spinlock instead (`kernel/spinlock.h`).

As for accessing the address space of a user TA from an interrupt context, it seems quite dangerous to me because how can you be sure that the TA is mapped at that time? That could very well be the cause of the translation faults you're seeing.

**Comment by janoslim** [comment]
Thank you! It seems working

**Comment by janoslim** [comment]
Hello @jforissier, I reopened this thread with one more question about kernel accessing userTA's heap area.
I found that kernel api (copy_to_user(), copy_from_user()) also accessing vaddr directly in kernel mode, and I wonder what is safe way to access user data while I need to copy(stream) user's data to kernel, kernel to user.
Always thank you a lot for your kind answers.

**Comment by janoslim** [comment]
Hello @jenswi-linaro ,
Firstly I am sorry for re-reopening this thread again. I just wonder how to make available for interrupt to access user TA’s heap data by address given by TA since syscall(thread context) is available. I checked ttbr however they do not changed. And also interrupt do not directly make translation fault but sometimes it works fine but sometimes invoke fault. Thanks for your kind attentions.
