### ISSUE TITLE
sunxi-sun50i_a64: Spurious interrupt triggered after FIQ 

### ISSUE THREAD

**Issue by panda-balarka** [OP-TEE/optee_os#4920]
I was able to resolve issue #4910 (Suxi a64 was missing handling for GIC `itr_ops` definition and platform defines to compile the same) leading to NULL ptr reference when `itr_chip->ops->add` was called in `itr_add` API under interrupt.c.

After adding and configuring the timer1 for 1s interrupt on the device, my dynamic TA returns control to the normal world and the interrupt is raised at 1s as expected, working on the secure side in interrupt context. However, immediately after this, there is a spurious interrupt that is raised and this happens in a loop.
I added a print statement in the `it_handle` API and I see that the interrupt is raised as expected with `id=51` (timer1 int num for sun50i_a64) and then there are 2-3 interrupts that trigger with `id=1023`. As expected the API now prints "ignoring interrupt" and my device is stuck in a loop. 

I clear the itr pending for my timer in its interrupt handler and I understand that `itr_handle` does a read of the `GIC_IAR` register which should acknowledge the interrupt and then clear the same by writing to `eior` register to handle the GIC side, which is also happening. The GIC manual is a little overwhelming in this regard and I was very confused. I understand that `itr_add` on the secure side maps the itr to FIQ in GICv2 and we have the interrupt happening as expected. But after the first itr_handle, I'm stuck in a loop.

Does this have to do something with the flags attribute in the `itr_handle` struct? What does `ITRF_SHARED` mean and why is it used? Additionally, I have mapped the TIMER address as `MEM_AREA_IO_NSEC` since the timer is shared. 

Any inputs are much appreciated. Thank you!

**Comment by jenswi-linaro** [comment]
`ITRF_SHARED` is used when two devices share the same interrupt line. That way you can have register two handlers and the one finding the triggering device can return `ITRR_HANDLED`.
