### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by CamilleZxt** [OP-TEE/optee_os#4921]
We measured the CPU usage when the program used TEE and found that the CPU usage was lower than when the program did not use TEE.

So I have the following questions:

1.Whether the CPU usage measured in the REE includes the CPU usage of the TA.
2.How to measure the CPU usage of the TA?

**Comment by jenswi-linaro** [comment]
> We measured the CPU usage when the program used TEE and found that the CPU usage was lower than when the program did not use TEE.
> 
> So I have the following questions:
> 
> 1.Whether the CPU usage measured in the REE includes the CPU usage of the TA.

That depends on how you measure, normally I guess it would be included since the secure world is scheduled by the normal world.

> 2.How to measure the CPU usage of the TA?

Perhaps you can find something useful here https://optee.readthedocs.io/en/latest/debug/index.html
