### ISSUE TITLE
all secondary CPUs offline after resuming from suspend

### ISSUE THREAD

**Issue by jjoset** [OP-TEE/optee_os#4925]
Hello,

I am facing a problem with resume after suspend in OPTEE. The target will go to suspend and after the
time is elapsed, the system will wake up, but only primary CPU is online. All secondary cores are offline. We use rtc/rtc0/wakealarm  command  to test wake up. The logs message after resuming is below. The optee version used 3.3.0. 
Thanks in advance

cj§Lgeneric_boot_cpu_on_handler:972 cpu 1: a0 0x0
init_secondary_helper:957 Secondary CPU Switching to normal world boot
generic_boot_cpu_on_handler:972 cpu 4: a0 0x0
init_secondary_helper:957 Secondary CPU Switching to normal world boot
generic_boot_cpu_on_handler:972 cpu 2: a0 0x0
init_secondary_helper:957 Secondary CPU Switching to normal world boot
[   59.208741] Modules linked in:
[   59.208741] CPU: 0 PID: 295 Comm: sh Not tainted 4.19.133 
[   59.208741] pstate: 40000085 (nZcv daIf -PAN -UAO)
[   59.208741] pc : check_pll_off+0x1c8/0x2b8
[   59.208741] lr : check_pll_off+0x1c8/0x2b8
[   59.208741] sp : ffffff80093bb8d0
[   59.208741] x29: ffffff80093bb8d0 x28: ffffff80088ce020
[   59.208741] x27: fffffffffffff000 x26: ffffffc0fa649d00
[   59.208741] x25: ffffff800876fbb0 x24: ffffff8008a0d6c8
[   59.208741] x23: ffffff8008b82dc0 x22: ffffff80088cdbf8
[   59.208741] x21: ffffff800889b1c0 x20: 0000000000000000
[   59.208741] x19: 0000000000000000 x18: 0000000000000001
[   59.208741] x17: 0000000000000001 x16: 0000000000000007
[   59.208741] x15: ffffffffffffffff x14: 6c65735f74726175
[   59.208741] x13: 0000000000000000 x12: ffffff8008aeb000
[   59.208741] x11: ffffff8008a2f000 x10: ffffff8008aeb130
[   59.208741] x9 : 0000000000000000 x8 : ffffff8008af3560
[   59.208741] x7 : 0000000000000000 x6 : 000000002ecdb888
[   59.208741] x5 : 0000000000000000 x4 : ffffffc0fff3f7d0
[   59.208741] x3 : ffffffc0fff3f7d0 x2 : 7e5b62fb981b6d00
[   59.208741] x1 : 0000000000000000 x0 : 0000000000000024
[   59.208741] Call trace:
[   59.208741]  check_pll_off+0x1c8/0x2b8
[   59.208741]  clkchk_syscore_suspend+0x14/0x20
[   59.208741]  syscore_suspend+0x84/0x2f0
[   59.208741]  suspend_enter+0xc0/0x688
[   59.208741]  suspend_devices_and_enter+0x198/0x3c0
[   59.208741]  pm_suspend+0x3ec/0x660
[   59.208741]  state_store+0x90/0x100
[   59.208741]  kobj_attr_store+0x14/0x28
[   59.208741]  sysfs_kf_write+0x5c/0x78
[   59.208741]  kernfs_fop_write+0xf0/0x200
[   59.208741]  __vfs_write+0x60/0x178
[   59.208741]  vfs_write+0xb8/0x1d0
[   59.208741]  ksys_write+0x74/0xe8
[   59.208741]  __arm64_sys_write+0x24/0x30
[   59.208741]  el0_svc_common.constprop.0+0x98/0x160
[   59.208741]  el0_svc_handler+0x34/0x90
[   59.208741]  el0_svc+0x8/0xc
[   60.222137] CPU1: failed to come online
[   60.222145] CPU1: failed in unknown state : 0x0
[   61.246102] CPU2: failed to come online
[   61.246109] CPU2: failed in unknown state : 0x0
[   62.270135] CPU3: failed to come online
[   62.270142] CPU3: failed in unknown state : 0x0
root@[   60.222137] CPU1: failed to come online
 [ 61.246102] CPU2: failed to come online
 [ 62.270135] CPU3: failed to come online
2021 Sep 23 15:06:35 CPU1: failed to come online
2021 Sep 23 15:06:35 CPU2: failed to come online
2021 Sep 23 15:06:35 CPU3: failed to come online
2021 Sep 23 15:06:35 CPU1: failed to come online
2021 Sep 23 15:06:35 CPU2: failed to come online
2021 Sep 23 15:06:35 CPU3: failed to come online

Thanks,

**Comment by jenswi-linaro** [comment]
It looks like you're doing a cold boot on the secondaries. I'd expect the EL3 would save and restore the CPU registers so the OP-TEE involvement should be minimal.

**Comment by jjoset** [comment]
Hi @jenswi-linaro 

Thanks for the reply.
But on the same hardware, ATF without optee , suspend and resume is working fine with all cores comes online after resume.

I tried to enable this config variable CFG_BOOT_SECONDARY_REQUEST, which I think only supports 32 bit.
Is opteed SPD have any role in this?, 

Thanks,
Jose
