### ISSUE TITLE
A problem for creating a static lib by using ta_dev_kit.mk

### ISSUE THREAD

**Issue by sticfeynman** [OP-TEE/optee_os#4928]
Hi,
I got this error "The 'o' modifier is only applicable to the 'x' operation" while I tried to create a static library by using the ta_dev_kit.mk. I was using the LLVM toolchain. There is one more -o option of the AR command in the ta_dev_kit.mk comparing with that in lib.mk.
Can you remove this -o in ta_dev_kit.mk or any advice?

**Comment by jenswi-linaro** [comment]
I'm not sure what the `-o` option is supposed to do there. If removing it fixes you problem please make a pull request to have it removed. Perhaps we can add a test for this in xtest too.

**Comment by sticfeynman** [comment]
It does fix my problem by remove the -o. But I also notice that it seems work fine with the -o by using gnu-ar.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/4934
