### ISSUE TITLE
setup_juno_optee: unable to find pre-built binaries

### ISSUE THREAD

**Issue by pascal-brand-st-dev** [OP-TEE/optee_os#493]
`setup_juno_optee.sh` links to http://community.arm.com/docs/DOC-8401 to get pre-built binaries. Unfortunately, this link does not contain the binaries anymore

**Comment by vchong** [comment]
Can we use juno's fip.bin and ARM-TF's fip_create tool to insert tee.bin (bl32 image) into it? But that means refactoring the makefile.

Juno's fip.bin can be found here:
http://releases.linaro.org/components/kernel/uefi-linaro/latest/release/juno/
http://releases.linaro.org/members/arm/openembedded/juno-lsk/latest/
http://releases.linaro.org/openembedded/juno-lsk/latest/ (there should be one here too but is missing for the latest release)

Not sure what the differences are between the three.

**Comment by jbech-optee-adm** [comment]
We have stated in https://github.com/OP-TEE/optee_os#43-arm-juno-board that the current setup is broken and we also have a Jira story for this internally, therefore I will close this issue.
