### ISSUE TITLE
interrupt on Rpi3

### ISSUE THREAD

**Issue by JensVankeirsbilck** [OP-TEE/optee_os#4930]
Using https://optee.readthedocs.io/en/latest/building/devices/rpi3.html I was able to build optee for my Rpi 3b+. Xtest reported all tests OK, so the build fully works.
Using #1496 I was able to drive an LED on GPIO pin 18.

Now, I wanted to make the LED blink, by toggling it based on timer interrupts. As timer I just wanted to use the timer provided by OPTEE, so the code looks like this:

```

#include <drivers/rpi_gpio_test.h>
#include <kernel/timer.h>
#include <kernel/interrupt.h>
#include <initcall.h>

#define IT_SEC_TIMER 29 // not sure about this number, to be figured out later
#define TIMER_PERIOD_MS 10

void myPeriodicTask(void){
	togglePin18();
}

static enum itr_return myTimer_itr_Handler(struct itr_handler *h __unused)
{
	/* Reset timer for next FIQ */
	generic_timer_handler(TIMER_PERIOD_MS);

	/* Execute periodic task */
	myPeriodicTask();

	return ITRR_HANDLED;
}

static struct itr_handler myTimer_itr = {
	.it = IT_SEC_TIMER,
	.handler = myTimer_itr_Handler,
};
KEEP_PAGER(myTimer_itr);

static TEE_Result initPeriodicTask(void){
	
	itr_add(&myTimer_itr);
	itr_enable(IT_SEC_TIMER);
	
	/* Enable timer FIQ  */
	generic_timer_start(TIMER_PERIOD_MS);
		
	return TEE_SUCCESS;
} 

service_init(initPeriodicTask);
```

 When running this code, however, I get the error `Core data-abort at address 0x0 (translation fault)` . Simply using DMSG statements, I was able to find out this error is triggered when executing the instruction `itr_chip->ops->add(itr_chip, h->it, h->flags);` found in interrupt.c
Since error states `address 0x0` I think it means that a null-pointer exception occurs when interacting with `itr_chip` . According to that source file (interrupt.c), `itr_chip` is set by calling `itr_init`. However, this function is never called for the Rpi3. 

So does this mean interrupts are not supported within OPTEE on the Rpi3? (I've used interrupts and the itr_ interface before on the QEMUv7 version, so I know that's the flow that needs to be followed)

**Comment by StephQAZ** [comment]
@JensVankeirsbilck Hello, have you succeeded on rpi3?

**Comment by JensVankeirsbilck** [comment]
@StephQAZ I have not tried any further, so I have not succeeded.

**Comment by StephQAZ** [comment]
> 
Thank you for your reply. Rpi3 doesn't have GIC, maybe there's no solution
