### ISSUE TITLE
OPTEE SQLite Support

### ISSUE THREAD

**Issue by vinethak** [OP-TEE/optee_os#4944]
Hallo,
I am interesting in porting "sqlite-amalgamation-3360000" as Secure Database for TA application.
For OPTEE, I could see that in version "OP-TEE - version 2.2.0" SQLite backend is available.
However, I am not able to find much information about the capabilities of this backend. Can anybody explain or point to the right documentation?
What would be the difference between using this feature and porting SQLite as part of TA itself?
Also, is there any way to find out which OPTEE version I am using? E.g from the source code of OPTEE OS or from exported include/optee directory?
Many thanks.

**Comment by YogzZ** [comment]
Hi, Vinethak:

Are you still working on this problem now?
