### ISSUE TITLE
porting to armv8 cortex-A32 issue

### ISSUE THREAD

**Issue by Chengweiadp** [OP-TEE/optee_os#4961]
I'm porting OPTEE-OS to armv8 cortex-A32, with ATF(BL1 and BL2) and set Linux to be the REE OS. According to Linux kernel arm boot document, "CPUs which include support for the virtualization extensions can be entered in HYP mode in order to enable the kernel to make full use of these extensions", I overwrite weak function "void init_sec_mon(unsigned long nsec_entry)" in OPTEE, set nsec_ctx->mon_spsr to CPSR_MODE_HYP | CPSR_FIA, but after the overwrite, BL33 (Uboot) boot success, Linux kernel hang up at the begining, without any log output. my question is :
1.  Should I overwrite init_sec_mon to set BL33 cpu mode to hypervisor?
2.  If answer of question 1 is yes, what should I do solve the Linux kernel hang up problem

**Comment by jenswi-linaro** [comment]
Given that U-Boot succeeded I'd say that you've managed to enter normal world OK. I can't help you with the kernel hang problem.

**Comment by Chengweiadp** [comment]
Got it, thanks a lot any way
