### ISSUE TITLE
Q&A: how to maintain the user space memory mapping for Single Instance TA

### ISSUE THREAD

**Issue by xyzhao2018** [OP-TEE/optee_os#4963]
Dear Sir or Madam, 

One question want to consult you about Single Instance TA. 
From the code, the user space mapping is bound with Thread. 
When one thread load TA, it will build up the user space memory mapping for this TA and save the ttbr0 and asid. 
But when switch to other thread, the ttbr0 and asid will be changed accordingly, so the user space mapping is changed. 
So for Single Instance TA, how to guarantee other thread can see the memory mapping of this TA? 

Thanks. 
Shirley

**Comment by jenswi-linaro** [comment]
The user space mapping of a TA is kept in `struct user_mode_ctx` which is part of TA context. The translation tables are re-created from this each time a TA is about to be mapped.
