### ISSUE TITLE
crypto api - rsa decrypt

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#4971]
The RSA decrypt API does not support variable length buffers as required by some PKCS#11 implementations - ie, those not always allocating a valid buffer of zero length.

Since the size of the required decrypted output buffer can not be calculated by the API but by the drivers instead, modifying this API requires inspecting the different clients/drivers to make sure that functionality is not broken as decryption needs to run.

This should have been implemented under https://github.com/OP-TEE/optee_os/commit/8bddeb8511ba0d00a18bb603bfd816825adea3f1 but at the time of the change, I only checked for the API returning SHORT_BUFFER hence why I didnt notice this use case (it would be the driver, not the API returning the short buffer error)

DRVCRYPT_RSA_OAEP --> inspecting the code, it seems to me that for this cipher CAAM supports variable length buffers
DRVCRYPT_RSA_PKCS_V1_5 --> but I dont think it does. Does anyone/maintainer know?

```
diff --git a/core/drivers/crypto/crypto_api/acipher/rsa.c b/core/drivers/crypto/crypto_api/acipher/rsa.c
index 94261919f..160ade8a0 100644
--- a/core/drivers/crypto/crypto_api/acipher/rsa.c
+++ b/core/drivers/crypto/crypto_api/acipher/rsa.c
@@ -205,7 +205,7 @@ TEE_Result crypto_acipher_rsaes_decrypt(uint32_t algo, struct rsa_keypair *key,
        struct drvcrypt_rsa *rsa = NULL;
        struct drvcrypt_rsa_ed rsa_data = { };
 
-   if (!key || !msg || !cipher || !msg_len || (!label && label_len)) {
+ if (!key || !cipher || !msg_len || (!label && label_len)) {
                CRYPTO_TRACE("Parameters error (key @%p)\n"
                             "(msg @%p size %zu bytes)\n"
                             "(cipher @%p size %zu bytes)\n"
@@ -219,8 +219,10 @@ TEE_Result crypto_acipher_rsaes_decrypt(uint32_t algo, struct rsa_keypair *key,
        if (rsa) {
                /* Prepare the encryption data parameters */
                if (algo == TEE_ALG_RSAES_PKCS1_V1_5) {
                        rsa_data.rsa_id = DRVCRYPT_RSA_PKCS_V1_5;    <------ will probably break
                } else {
                        rsa_data.rsa_id = DRVCRYPT_RSA_OAEP;
                        rsa_data.hash_algo = TEE_INTERNAL_HASH_TO_ALGO(algo);

```

**Comment by ldts** [comment]
The SE050 driver would have to change to support this. 
I am trying to find out what does the CAAM driver will need.

**Comment by ldts** [comment]
just so this is captured for future planing the current crypto API implementation doesnt support with the pkcs#11 specification for variable length buffers. 

Fortunately, the op-tee pkcs#11 implementation does work around it by always allocating extra memory which ultimately hides the API problem.

**Comment by anta5010** [comment]
@ldts could you point me to the work around you mentioned? 
In our code we firstly call C_Decrypt with a NULL pointer and 0 data length to get a required buffer size, allocate a buffer and call C_Decrypt second time with the correct buffer size.
If I build op-tee pkcs11 TA with a software backend then I don't see any issue. But, if I build it with with the crypto driver backend the first call fails.
