### ISSUE TITLE
About Hardware Unique Keys.

### ISSUE THREAD

**Issue by alifilhan0** [OP-TEE/optee_os#4982]
I am currently attempting to implement OP-TEE on a MediaTek MT6735/MT6737 based device which is almost identical to OrangePi 4G IoT. I have the BSP release and it has ATF, Trusty TEE sources and some drivers of related to MTK crypto. But what I attempt to do is use this trusted OS on the hardware. And finally, use a open source boot chain on this SoC, changing everything to open source except the preloader which I don't have much access to.

So straight to cryptography, What I came accross is that the HUK is stubbed and it is not documented on how to access the SoC specific key from OTP memory. But I am not concerned about the security vulnerablities of a stubbed HUK. I would just want to know how to change the HUK to a custom one so that I can use it. Can anyone please inform me about this underlaying HUK deriving structure if the key is stubbed? How is it done?

**Comment by jenswi-linaro** [comment]
If you don't care about the security of the stubbed HUK, why try to change it to use some other hardcoded value?

By the way, the function you're looking for is tee_otp_get_hw_unique_key(), just provide another implementation of this that doesn't set the data to all zeroes.

**Comment by alifilhan0** [comment]
Thank you for the info. Actually I just wanted to learn more about the function which derieves the root key(no matter frok HW OTP memory or just a written key in a header) and how it is involved in generating the next keys by code.

**Comment by alifilhan0** [comment]
One more thing, if I want to use libtomcrypt as a crypto library, can I directly use it without any other additions? R adding something devuce specific is required?

**Comment by jenswi-linaro** [comment]
Both libtomcrypt and mbedtls works without any devices specific actions.

Regarding HUK derivations. This should give a good picture:
https://github.com/OP-TEE/optee_os/blob/4ed45027f507fb7693ff43b01b9c3299d5440eb0/core/include/kernel/huk_subkey.h#L40-L57

The implementation of huk_subkey_derive() isn't very complicated, it's just a matter of MACing some data with the HUK as the input key.

**Comment by alifilhan0** [comment]
This seems useful for my purpose. Thanks a lot
