### ISSUE TITLE
change TA_DATA_SIZE issue

### ISSUE THREAD

**Issue by neil1899** [OP-TEE/optee_os#499]
hi,all
if i change the TA_DATA_SIZE in user_ta_header.h, I change to 1M, but 32K is ok

the code is:
static TEEC_Result allocshm(TEEC_Context *ctx,
					TEEC_SharedMemory *shm, uint32_t size,
					uint32_t flags)
{
	shm->flags = flags;
	shm->size = size;
	return TEEC_AllocateSharedMemory(ctx, shm);
}

	if (allocshm(&ctx, &shm, 128, TEEC_MEM_OUTPUT) != TEEC_SUCCESS) {  
	  	return TEEC_ERROR_GENERIC;
	}

	op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_PARTIAL_OUTPUT,       TEEC_VALUE_INOUT,
					 TEEC_NONE, TEEC_NONE);
	op.started = 1;  
	op.params[0].memref.parent = &shm;
	op.params[0].memref.offset = 0;
	op.params[0].memref.size = shm.size;

it can't work well:

ERR [-148145172] TEEC:TEEC_InvokeCommand:412: Function returns with [-65529]
tee_helloworld: TEEINF USER-TA:TA_CloseSessionEntryPoint:97: Goodbye!
C_InvokeCommand failed with code 0xffff0007 origin 0x4

thanks in advance!

**Comment by neil1899** [comment]
it also happend data abort:

user TA data-abort at address 0x1
 fsr 0x00000001  ttbr0 0x0537046a  ttbr1 0x0536c06a  cidr 0x1
 cpu #0          cpsr 0x20000130
 r0 0x0556f7b8      r4 0x0020a1fd    r8 0x00000000   r12 0x00209e08
 r1 0x00000042      r5 0x0020ba9c    r9 0x00000000    sp 0x00100788
 r2 0x00280003      r6 0x00000130   r10 0x00000000    lr 0x002026f1
 r3 0x00000001      r7 0x00100790   r11 0x00000000    pc 0x0020023c
Status of TA 8aaaf200-2450-11e4-abe20002a5d5c51b (0x556fa68)
- load addr : 0x200000    ctx-idr: 1     (active)
- code area : 0x5a00000 2097152
- stack: 0x5c00000 stack:2048
ERR TEE-CORE:tee_user_ta_enter:752: USER_TA_FUNC_INVOKE_COMMAND End -53212!
ERR TEE-CORE:tee_user_ta_enter:787: tee_user_ta_enter End -53212!
[  653.997484@0] misc opteearmtz00: _update_client_tee_cmd: id 0 type 14
[  654.003872@0] misc opteearmtz00: _update_client_tee_cmd: id 1 type 3
[  654.010186@0] misc opteearmtz00: _update_client_tee_cmd: a=0000002a, b=00000000
[  654.017431@0] misc opteearmtz00: _update_client_tee_cmd: id 2 type 0
[  654.023705@0] misc opteearmtz00: _update_client_tee_cmd: id 3 type 0
voking TA to increment 42
ERR [-147334164] TEEC:TEEC_InvokeCommand:412: Function returns with [-53212]
tee_helloworld: TEEC_InvokeCommand failed with code 0xffff3024 origin 0x3

**Comment by jenswi-linaro** [comment]
It looks like this need to be fixed, but I can't do it in the nearest weeks.

Contributions are welcome! :-)

**Comment by neil1899** [comment]
hi, jenswi:
thank so much, i will try my best. according to your reply, it's a existent bug in current branch, right?

**Comment by jenswi-linaro** [comment]
Assuming you where testing on current branch, yes.

**Comment by neil1899** [comment]
Dear jenswi:
I have a question, where i can config that protect my heap space size. 

I found a issue,

when i add session, it's OK.
ERR USER-TA:ta_header_add_session:132: ta_header_add_session itr->session_id 89586816

but when i do the invode command:
ERR USER-TA:ta_header_get_session:88: itr->session_id 2621443
ERR USER-TA:ta_header_get_session:89: session_id 89586816
the data of ta_session list maybe is tampered by other.

**Comment by jenswi-linaro** [comment]
This looks vaguely familiar, are you sure you're using latest on master?

**Comment by neil1899** [comment]
I'am not working on the latest commit of master branch. Could you help me find which commit fix this bug?

**Comment by neil1899** [comment]
on my local code, the latest commit is 
commit 263d1505ad6ecf38dca1dc76438fd9d90f256e09
Author: Cedric Chaumont <cedric.chaumont@st.com>
Date:   Thu Jul 2 23:19:06 2015

    GP11 : Time functions fix/panic reason
    
    Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>
    Reviewed-by: Pascal Brand <pascal.brand@linaro.org>
    Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
    Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (STM boards)
    Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (ARM Juno board)

**Comment by neil1899** [comment]
core: correct TA virtual address mapping calculation  ? this one is right?

I try to cherry-pick this commit, now the CA runs OK

**Comment by jenswi-linaro** [comment]
Yes that's probably the one.

**Comment by neil1899** [comment]
thanks so much!
