### ISSUE TITLE
Running optee OS on top of sel4?

### ISSUE THREAD

**Issue by TanelDettenborn** [OP-TEE/optee_os#4990]
Wondering if it is possible/feasible to run optee os on top of sel4?

**Comment by jenswi-linaro** [comment]
Not out of the box today. It sounds interesting though. What exactly did you have in mind?

**Comment by TanelDettenborn** [comment]
Do you have any initiatives towards Sel4?

I have been looking optee code and wondering if it would be "portable" to sel4. perhaps rewriting some parts of optee or developing a layer between sel4/optee. So nothing too exact in mind, yet.

**Comment by jenswi-linaro** [comment]
What relation would you have between sel4 and OP-TEE? Are you still running on Arm? Are you going to use TrustZone or will this be a normal world thing?

**Comment by sunnybird** [comment]
i have think this idea before.
now, optee run at Monolithic Kernel，
the sel4 is a popular Micro Kernel system.  so, sel4 can provide more security core kernel. 
i guess to implement optee + sel4 architecture . first , we need porting  sel4,then rewrite optee's kernel.
