### ISSUE TITLE
Adding certficates and passwords into OPTEE Secure Storage

### ISSUE THREAD

**Issue by NoxiousFly** [OP-TEE/optee_os#4997]
I want to store certificates, passwords and pem files in OPTEE secure storage . It seems like OPTEE secure storage using `/data/tee`  as default path . 

- As per my analysis, It is recommended that TAs always go through the TEE_*object*() API Functions to access their own secure persistent object. 
- What are the ways to place the files in secure storage? Can I place the files while build OPTEE_OS
- Is there any way to copy the files directly into secure storage path . 
- Could you please share any examples to copy the files directly into secure storage path.

**Comment by jenswi-linaro** [comment]
> * As per my analysis, It is recommended that TAs always go through the TEE__object_() API Functions to access their own secure persistent persistent object.

Correct

> * What are the ways to place the files in secure storage? Can I place the files while build OPTEE_OS
> * Is there any way to copy the files directly into secure storage path .

That's generally not possible since the protection of the object depends on secrets only available in the hardware while executing. It sounds like the creation of these objects is something that you need to do while producing the unit in factory.

This is likely a class of problem that many face, but I'm not sure if we can find a generic solution to this since it seems to be tied closely with how the units are produced in the factory. What does others think?

**Comment by etienne-lms** [comment]
I agree with @jenswi-linaro. Provisioning secrets in TEE depends on the provisioning tools, possibly specific environment (HSM permissions, ...) which OP-TEE project has no view of.
A way could be to have 2 versions of the TA (same UUID). During production, install TA version 1 and invoke it: it would load the secrets in secure storage (bound to TA UUID/device HUK), then install the TA version 2: the one for the end device, designed to only read/use the secrets. For TA installation, I would recommend the scheme used by `xtest --install-ta`.

**Comment by NoxiousFly** [comment]
My aim is to place the certificates and PEM files, while building or booting the image. 

> During production, install TA version 1 and invoke it: it would load the secrets in secure storage (bound to TA UUID/device HUK), then install the TA version 2:

I hope installation of TA could be done only after boots my image into a board. Then where can I add these certificates before TA load this into secure storage.

**Comment by b49020** [comment]
Another approach could be to just leverage [encrypted TAs](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#ree-fs-ta-formats) in order to carry the secrets before they are installed into OP-TEE secure storage.

**Comment by NoxiousFly** [comment]
Hi @b49020 , 

Do I need to keep my secret files (PEM, certificates) inside encrypted TA?
I couldn't found any examples regarding file handling in TA's . Could you please provide any link to it.

**Comment by b49020** [comment]
> Do I need to keep my secret files (PEM, certificates) inside encrypted TA?

Yes, until those are provisioned into OP-TEE secure storage.

> I couldn't found any examples regarding file handling in TA's . Could you please provide any link to it.

I would suggest you to go through "Section: 5.9 Data Stream Access Functions" in [GP TEE Internal Core APIs](https://globalplatform.org/specs-library/tee-internal-core-api-specification/).

**Comment by NoxiousFly** [comment]
@b49020 

I have made some changes with optee_example secure_storage code and able to install TA and create persistent object. 
I have added `CFG_ENCRYPT_TA ?= y` in TA's makefile and getting build error from sign_encrypt.py like "TypeError: Only byte strings can be passed to C code".

In link.mk  https://github.com/OP-TEE/optee_os/blob/203ee23d005b2cec2f21b5de334c5a246be32599/ta/arch/arm/link.mk#L14

```
it is mentioned like 
# Note that a user of this TA encryption feature needs to provide
# encryption key and its handling corresponding to their security
# requirements
```

Can i have any example code to achieve this?

**Comment by NoxiousFly** [comment]
Hi @b49020 ,

Is there is any support available to install encrypted TA inside secure storage? If available , could you please share the method.
It seems like only `BOOTSTRAP_TA` can be installed in secure storage.

**Comment by b49020** [comment]
> Is there is any support available to install encrypted TA inside secure storage? If available , could you please share the method.

Although, it should be doable but I would like to understand the motivation for this change. If the TA is already encrypted then what additional benefit do you see by installing it in secure storage? BTW, secure storage internally would again encrypt and store it in REE-FS storage only.

**Comment by NoxiousFly** [comment]
@b49020 Thanks for the explanation. I get it now.
