### ISSUE TITLE
Decryption content not same as source content for TEE_ALG_AES_CBC_NOPAD

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#5005]
I have a source buffer which is of block length in size. Later, i encrypt (init-->update->final) and decrypt (init-->update-->final) it using TEE_ALG_AES_CBC_NOPAD. But, decrypted content and the original source content don't match (confirmed via ADBG_EXPECT_BUFFER(....))
This happens for 128bit, 192bit and 256bit key lengths.

However, everything seems to be fine for TEE_ALG_AES_ECB_NOPAD for the same scenario.

Could anyone please let me know if i am missing anything here?
Software used: OPTEE QEMU version 3.13

**Comment by jenswi-linaro** [comment]
So it's one block you encrypting and decrypting? Are you sure the supplied IV is correct?

**Comment by Hussain1811** [comment]
yes - it is one block length data (16bytes)
iv length being used: 16 bytes

**Comment by jenswi-linaro** [comment]
And you're sure the IV isn't corrupted between the two operations?

**Comment by Hussain1811** [comment]
printed the IV after enc_final and before dec_init ---> (i)
printed the IV after dec_final ---> (ii)

both (i) and (ii) are same

**Comment by jenswi-linaro** [comment]
Note that the input IVs should be the same in both cases. Perhaps it's easier to try this out with some online encryption site.

**Comment by jforissier** [comment]
https://github.com/linaro-swg/optee_examples/tree/master/aes could help, too. You can try it in CBC mode by changing one line in `host/main.c`.

**Comment by Hussain1811** [comment]
OK - i tried out the optee example as suggested by @jforissier with TA_AES_ALGO_CBC.
Seems to be working fine.

Looks like there is some issue in my test.

Thanks for the support.

**Comment by Hussain1811** [comment]
Actually, i looked at it a bit-further.

https://github.com/linaro-swg/optee_examples/tree/master/aes  doesn't seem to be doing TEE_CipherDoFinal() and hence it seems to pass.
Even if i comment the part where i eventually call TEE_CipherDoFinal() in my test, then my test passes too.

Could this be some inconsistency with TEE_CipherDoFinal()?

**Comment by Hussain1811** [comment]
Could anyone please help me with this doubt?

**Comment by jforissier** [comment]
What is the length of the data you pass to `TEE_CipherDoFinal()`?

**Comment by Hussain1811** [comment]
16 bytes (which is block-length)

**Comment by Hussain1811** [comment]
is this the correct input data that i am using?

**Comment by jforissier** [comment]
Without a reproducer I can't figure out if you are using the API in an incorrect way, or if there is a bug in OP-TEE. Please provide a patch against optee_examples/aes that shows what you believe is incorrect behavior.

**Comment by Hussain1811** [comment]
diff --git a/aes/host/main.c b/aes/host/main.c
index 93a999d..44b6ccd 100644
--- a/aes/host/main.c
+++ b/aes/host/main.c
@@ -35,7 +35,7 @@
 /* For the UUID (found in the TA's h-file(s)) */
 #include <aes_ta.h>
 
-#define AES_TEST_BUFFER_SIZE   4096
+#define AES_TEST_BUFFER_SIZE   16
 #define AES_TEST_KEY_SIZE      16
 #define AES_BLOCK_SIZE         16
 
@@ -85,7 +85,7 @@ void prepare_aes(struct test_ctx *ctx, int encode)
                                         TEEC_VALUE_INPUT,
                                         TEEC_NONE);
 
-       op.params[0].value.a = TA_AES_ALGO_CTR;
+       op.params[0].value.a = TA_AES_ALGO_CBC;
        op.params[1].value.a = TA_AES_SIZE_128BIT;
        op.params[2].value.a = encode ? TA_AES_MODE_ENCODE :
                                        TA_AES_MODE_DECODE;
diff --git a/aes/ta/aes_ta.c b/aes/ta/aes_ta.c
index b259a01..61178f3 100644
--- a/aes/ta/aes_ta.c
+++ b/aes/ta/aes_ta.c
@@ -329,6 +329,7 @@ static TEE_Result reset_aes_iv(void *session, uint32_t param_types,
 static TEE_Result cipher_buffer(void *session, uint32_t param_types,
                                TEE_Param params[4])
 {
+    TEE_Result res = TEE_SUCCESS;
        const uint32_t exp_param_types =
                TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT,
                                TEE_PARAM_TYPE_MEMREF_OUTPUT,
@@ -356,9 +357,18 @@ static TEE_Result cipher_buffer(void *session, uint32_t param_types,
        /*
         * Process ciphering operation on provided buffers
         */
-       return TEE_CipherUpdate(sess->op_handle,
+       res = TEE_CipherUpdate(sess->op_handle,
                                params[0].memref.buffer, params[0].memref.size,
                                params[1].memref.buffer, &params[1].memref.size);
+       if (res == TEE_SUCCESS) {
+           DMSG("update is successfull");
+           res = TEE_CipherDoFinal(sess->op_handle, params[0].memref.buffer, params[0].memref.size,
+                                params[1].memref.buffer, &params[1].memref.size);
+

**Comment by Hussain1811** [comment]
diff --git a/aes/host/main.c b/aes/host/main.c
index 93a999d..44b6ccd 100644
--- a/aes/host/main.c
+++ b/aes/host/main.c
@@ -35,7 +35,7 @@
 /* For the UUID (found in the TA's h-file(s)) */
 #include <aes_ta.h>
 
-#define AES_TEST_BUFFER_SIZE   4096
+#define AES_TEST_BUFFER_SIZE   16
 #define AES_TEST_KEY_SIZE      16
 #define AES_BLOCK_SIZE         16
 
@@ -85,7 +85,7 @@ void prepare_aes(struct test_ctx *ctx, int encode)
                                         TEEC_VALUE_INPUT,
                                         TEEC_NONE);
 
-       op.params[0].value.a = TA_AES_ALGO_CTR;
+       op.params[0].value.a = TA_AES_ALGO_CBC;
        op.params[1].value.a = TA_AES_SIZE_128BIT;
        op.params[2].value.a = encode ? TA_AES_MODE_ENCODE :
                                        TA_AES_MODE_DECODE;
diff --git a/aes/ta/aes_ta.c b/aes/ta/aes_ta.c
index b259a01..61178f3 100644
--- a/aes/ta/aes_ta.c
+++ b/aes/ta/aes_ta.c
@@ -329,6 +329,7 @@ static TEE_Result reset_aes_iv(void *session, uint32_t param_types,
 static TEE_Result cipher_buffer(void *session, uint32_t param_types,
                                TEE_Param params[4])
 {
+    TEE_Result res = TEE_SUCCESS;
        const uint32_t exp_param_types =
                TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT,
                                TEE_PARAM_TYPE_MEMREF_OUTPUT,
@@ -356,9 +357,18 @@ static TEE_Result cipher_buffer(void *session, uint32_t param_types,
        /*
         * Process ciphering operation on provided buffers
         */
-       return TEE_CipherUpdate(sess->op_handle,
+       res = TEE_CipherUpdate(sess->op_handle,
                                params[0].memref.buffer, params[0].memref.size,
                                params[1].memref.buffer, &params[1].memref.size);
+       if (res == TEE_SUCCESS) {
+           DMSG("update is successfull");
+           res = TEE_CipherDoFinal(sess->op_handle, params[0].memref.buffer, params[0].memref.size,
+                                params[1].memref.buffer, &params[1].memref.size);

with this patch, i am able to reproduce the issue.
Normal world log:
```
# optee_example_aes 
Prepare session with the TA
Prepare encode operation
Load key in TA
Reset ciphering operation in TA (provides the initial vector)
Encode buffer from TA
Prepare decode operation
Load key in TA
Reset ciphering operation in TA (provides the initial vector)
Decode buffer from TA
Clear text and decoded text differ => ERROR
```
Secure World Log:
```
D/TA:  TA_OpenSessionEntryPoint:404 Session 0x4007b470: newly allocated
D/TA:  alloc_resources:124 Session 0x4007b470: get ciphering resources
D/TA:  set_aes_key:240 Session 0x4007b470: load key material
D/TA:  reset_aes_iv:308 Session 0x4007b470: reset initial vector
D/TA:  cipher_buffer:341 Session 0x4007b470: cipher buffer
D/TA:  cipher_buffer:364 update is successfull
D/TA:  cipher_buffer:368 return code of do-final:0x0
D/TA:  alloc_resources:124 Session 0x4007b470: get ciphering resources
D/TA:  set_aes_key:240 Session 0x4007b470: load key material
D/TA:  reset_aes_iv:308 Session 0x4007b470: reset initial vector
D/TA:  cipher_buffer:341 Session 0x4007b470: cipher buffer
D/TA:  cipher_buffer:364 update is successfull
D/TA:  cipher_buffer:368 return code of do-final:0x0
D/TC:? 0 tee_ta_close_session:512 csess 0xaa338840 id 1
D/TC:? 0 tee_ta_close_session:531 Destroy session
D/TA:  TA_CloseSessionEntryPoint:414 Session 0x4007b470: release session
D/TC:? 0 destroy_context:308 Destroy TA ctx (0xaa3387e0)
```

**Comment by jforissier** [comment]
```diff
@@ -356,9 +357,18 @@ static TEE_Result cipher_buffer(void *session, uint32_t param_types,
        /*
         * Process ciphering operation on provided buffers
         */
-       return TEE_CipherUpdate(sess->op_handle,
+       res = TEE_CipherUpdate(sess->op_handle,
                                params[0].memref.buffer, params[0].memref.size,
                                params[1].memref.buffer, &params[1].memref.size);
+       if (res == TEE_SUCCESS) {
+           DMSG("update is successfull");
+           res = TEE_CipherDoFinal(sess->op_handle, params[0].memref.buffer, params[0].memref.size,
+                                params[1].memref.buffer, &params[1].memref.size);
```
You're processing the same data twice. You should pass `NULL` and `0` instead of `params[0].memref.buffer` and `params[0].memref.size`.

**Comment by Hussain1811** [comment]
But passing NULL, 0 to TEE_CipherDoFinal() returns TEE_ERROR_SHORT_BUFFER

**Comment by Hussain1811** [comment]
ooops - yes you are right
i guess my doubts are cleared.
Thanks.
