### ISSUE TITLE
Accessing SPI-NOR Flash from Secure OS(OP-TEE).

### ISSUE THREAD

**Issue by sjena24** [OP-TEE/optee_os#5008]
Hi,
I am trying to access SPI-NOR Flash from OPTEE for Marvell OcteonTX2 ARMv8 based platform. We are able to port ATF and OPTEE on the target and able to test OPTEE example application. We now want to secure SPI-NOR Flash, where we can store encrypted data which should be accessible only from Secure side TA application. We have implemented io_storage(read/write etc.) APIs to access NOR Flash in ATF. I have following queries about how to access the NOR Flash from Secure OS(OPTEE),

1. Is this possible to use the implemented Marvell OcteonTX2 spi driver APIs in ATF to access NOR Flash from OPTEE?
2. Do we have to write SPI-NOR driver and PTA in OPTEE also to access and perform read/write operations?   
3. Is there any document available for implementing SPI-NOR support in OP-TEE ?

Regards,
Satya Ranjan

**Comment by jenswi-linaro** [comment]
> * Is this possible to use the implemented Marvell OcteonTX2 spi driver APIs in ATF to access NOR Flash from OPTEE?

I suppose you could expose an SMC interface for that, but that would require the driver to reside in BL31, the resident part of TFA.

> * Do we have to write SPI-NOR driver and PTA in OPTEE also to access and perform read/write operations?

I expect that you'd provide this as normal secure storage to the TAs so no need for a PTA at least.

> * Is there any document available for implementing SPI-NOR support in OP-TEE ?

None I've heard of. We try to collect all documentation at https://optee.readthedocs.io/en/latest/

**Comment by lorc** [comment]
Hi,

I'm also interested in this topic, because Renesas HW has similar arrangement. They have separate FLASH memory that is connected either via SPI or HyperFlash interface and is accessible only by Secure World.

They have working setup in their own branch: https://github.com/renesas-rcar/optee_os/tree/rcar_gen3_3.8.0/core/arch/arm/plat-rcar/drivers

Problem is that it is not upstreamable in a current state. And I'm interested in generic way to access such "private" storage, that can became part of mainline OP-TEE.

As I see it, we need another implementation for `tee_file_operations`, like ones in `tee_svc_storage.c`, which can work with SPI flash. Also we need some file system that knows about wear leveling, like JFFS2. Plus, it will be nice to keep in mind virtualization support...

So, this looks like a big project, and I'm happy that other platforms besides Renesas RCAR have similar use cases for SPI Flash.

**Comment by jenswi-linaro** [comment]
> > > * I suppose you could expose an SMC interface for that, but that would require the driver to reside in BL31, the resident part of TFA.
> 
> Okay, Does that mean implementing the SMC interface will allow OPTEE TA to access the NOR Flash device via ATF. If that is the case, Can you please share some reference for implementing SMC interface or available resources to achieve this.

https://developer.arm.com/documentation/den0028/latest
If this is a good idea or not remains to be seen. I don't want to make a recommendation.
I'd check @lorc's approach first.

> > > * I expect that you'd provide this as normal secure storage to the TAs so no need for a PTA at least.
> 
> Yes, we want to use the SPI-NOR Flash as a normal secure storage where we can store the keys accessible to TAs. Also, if PTA is not needed, is it possible for TA to directly access the NOR Flash device (accessing keys) in OPTEE. It seems any access to the SPI device can only be done via PTAs as per the comment by @jbech-linaro in the issue, #3184

If this is only going to be used as proper secure storage for TAs there's no need for a PTA.

**Comment by lorc** [comment]
It is working, indeed, but I doubt that this is the correct approach. 

At least, it can answer to some of your questions. If you are interested in implementing some generic interface that can benefit multiple platforms, I can participate in it's design.

**Comment by sunnybird** [comment]
only for customized and fast  usecase，not  generic and perfect. you can copy the driver code from atf to optee , then register some RT or XT physical address. and expose read or write interface to TA via system call . the DMSG function maybe is a good example.

**Comment by sjena24** [comment]
Hi @lorc,
The code looks more specific to RENESAS platform which might not be upstreamable. We can just take it as a reference tough. Since there are other platform with similar requirements, having a generic interface sounds good to me too.

As per @sunnybird's suggestion, exposing read/write interface in OPTEE to TA can be done but instead of copying the atf spi-nor code to optee, can we still resuse the existing code in ATF with SMC interface.
Is there any reference code on how to do that?

Otherwise, porting atf spi-nor code to optee seems only way to access flash at the moment.

Regards,
Satya Ranjan

**Comment by lorc** [comment]
Hi @sjena24 ,

> The code looks more specific to RENESAS platform which might not be upstreamable. 

Totally agree. This is why I'm looking for a more generic interface.

> As per @sunnybird's suggestion, exposing read/write interface in OPTEE to TA can be done but instead of copying the atf spi-nor code to optee, can we still resuse the existing code in ATF with SMC interface.

Well, I'm not sure that we should expose it directly to TA.  As for using SMC, you can use `thread_smccc()` function to issue SMC to ARM TF. You will need to allocate SMC IDs and provide  SMC handler for those IDs on ATF side.
