### ISSUE TITLE
TEE_ERROR_ITEM_NOT_FOUND on Opening a Session

### ISSUE THREAD

**Issue by TheFrozenDuck** [OP-TEE/optee_os#5016]
Following the issue #4898 I added the kernel API for the OP-TEE and recently built the 3.13.0 tag using the manifest provided by **linaro-swg**. I added an extra module in `core/pta`, as proposed here [1], and built a kernel module to connect to the TA but I always get the return value `TEE_ERROR_ITEM_NOT_FOUND` on calling `tee_client_open_session` using following code:

```c
    int ret = 0;

    // prepare to open an OP-TEE context
    struct tee_ioctl_invoke_arg inv_arg;
    struct tee_param param[4];

    memset(&inv_arg, 0, sizeof(inv_arg));
    memset(&param, 0, sizeof(param));
    struct tee_context *context = tee_client_open_context(NULL, optee_ctx_match, NULL, NULL);

    if (IS_ERR(context)) {
        printk("[*] Failed to open a context.");
        return -1;
    }

    // prepare to open an OP-TEE session
    struct tee_ioctl_open_session_arg sess_arg;
    memset(&sess_arg, 0, sizeof(sess_arg));
    memcpy(sess_arg.uuid, uuid, TEE_IOCTL_UUID_LEN);
    sess_arg.clnt_login = TEE_IOCTL_LOGIN_PUBLIC;
    sess_arg.num_params = 0;

    ret = tee_client_open_session(context, &sess_arg, NULL);

    if ((ret < 0) || (sess_arg.ret != 0)) {
        printk("[*] Failed to open a session.");
        printk("[*] return: '%d' error: '%d'.",sess_arg.ret, ret);
        tee_client_close_context(context);
        return -1;
    }
    ...

```
I modified the variable `uuid` to either contain the UUID of my TA or the TA defined in `core/pta/stats.c` but neither can be found.

[1] https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#pseudo-trusted-applications

**Comment by TheFrozenDuck** [comment]
I double checked and also implemented the calls with `UUID_INIT` and `export_uuid` and sadly it still fails. I eventually noticed that my TA does not seem to load properly, as I was able to reach the system.pta.

I added my TA using following patch:

```
--- a/core/pta/custom.c
+++ b/core/pta/custom.c
@@ -0,0 +1,466 @@
...
...
...
+pseudo_ta_register(.uuid = TA_UUID, .name = "custom.pta",
+                   .flags = PTA_DEFAULT_FLAGS,
+                   .invoke_command_entry_point = TA_InvokeCommandEntryPoint);
\ No newline at end of file
diff --git a/core/pta/sub.mk b/core/pta/sub.mk
index e01c50e4..3ba93376 100644
--- a/core/pta/sub.mk
+++ b/core/pta/sub.mk
@@ -1,5 +1,6 @@
 subdirs-$(CFG_TEE_CORE_EMBED_INTERNAL_TESTS) += tests

+srcs-y += custom.c
 srcs-$(CFG_TEE_BENCHMARK) += benchmark.c
 srcs-$(CFG_DEVICE_ENUM_PTA) += device.c
 srcs-$(CFG_TA_GPROF_SUPPORT) += gprof.c
```

Is there anything I forgot to configure? The documentation [1] does not have much more information other than using **stats.c** as model. I checked the compilation log and my TA seems to be atleast part of the build process.

[1] https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#pseudo-trusted-applications

**Comment by TheFrozenDuck** [comment]
Would applying this patch [1] show if my TA is loaded/usable?

[https://discuss.96boards.org/t/how-to-view-log-for-optee/8751/2]

**Comment by TheFrozenDuck** [comment]
I was able to produce the logs. When trying to call my TA, following log is produced:

```
D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA 23d6a7fa-55a3-48a6-bdf2-e32fe11b9e10
D/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
D/TC:? 0 ldelf_syscall_open_bin:143 Lookup user TA ELF 23d6a7fa-55a3-48a6-bdf2-e32fe11b9e10 (early TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:143 Lookup user TA ELF 23d6a7fa-55a3-48a6-bdf2-e32fe11b9e10 (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:143 Lookup user TA ELF 23d6a7fa-55a3-48a6-bdf2673167] init: CRea)d socket '/dev/socket/pdx/system/vr/display/manager', mode 666, user 1000, group 1003
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff0008
D/TC:? 0 tee_ta_open_session:718 init session failed 0xffff0008
```
This corresponds with the UUID I use and is defined like this:

```
#define TA_UUID{0x23d6a7fa, 0x55a3, 0x48a6, \
{0xbd, 0xf2, 0xe3, 0x2f, 0xe1, 0x1b, 0x9e, 0x10}}
```

**Comment by TheFrozenDuck** [comment]
I would like to **grep** for some strings to verify that my TA has been built into the image. Which file contains the build OP-TEE core?

**Comment by TheFrozenDuck** [comment]
I was not able to proceed yet. I still get the error and I still would like to `grep` for the strings.

**Comment by TheFrozenDuck** [comment]
@jforissier I think I found the problem that caused the executables to be missed. Apparently the build system does not pick up the newly added PTA without deleting quite a lot of files. A comment of @vchong [1] helped me to resolve it. Would it be possible to add a notice to the documentation that addresses this to the documentation? Maybe under the Tricks and Tips [2]?

[1] https://github.com/OP-TEE/optee_os/issues/2366#issuecomment-393730040
[2] https://optee.readthedocs.io/en/latest/building/gits/build.html#tips-and-tricks

**Comment by jforissier** [comment]
@TheFrozenDuck to be honest I don't know the Android build system very well, could this issue be fixed in the build system rather than simply documented? If the new TEE is not used after being built it is simply a bug IMO.

**Comment by TheFrozenDuck** [comment]
I do not have too much insight into the build system either. I think it kind of works as supposed, as otherwise problems would have complained about it already. Do you have someone in mind by chance that could be asked in this case?

**Comment by vchong** [comment]
What does your `device/linaro/hikey/build/tasks/build_uefi.mk` file look like? So the AOSP build system is really big with thousands of targets, but not really supposed to build firmware/bootloader since it's really a user space build. It was kind of 'spliced' in anyway as a convenience for users, so probably not all the build dependencies were captured. We should be moving away from this and instead just use the `fip.bin` from [1]. It should be relatively easier to maintain, more reliable and less error-prone.

[1] https://optee.readthedocs.io/en/latest/building/devices/hikey960.html#build-instructions
To build just `fip.bin`, run `make arm-tf`.

**Comment by TheFrozenDuck** [comment]
Sorry for the late answer. I will look into it and update you tomorrow.
