### ISSUE TITLE
pkcs#11: ECDH1_DERIVE missing

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#5019]
Could I get some background information as to why the support for asymmetric derivation wasnt merged into the current pkcs#11 ta? Having most of the current functionality been imported from the previous SKS implementation I am wondering why was this left behind. 
Was there any fundamental problem with it or is just due to timing/resource limitations?

I'd appreciate some info before putting the work - or if you have the code already on some branch please let me know.
thanks

**Comment by ruchi393** [comment]
@vesajaaskelainen had submitted the PR for ECDSA, so he will be the best person to answer this. From Linaro's end, we don't have anyone working on it.

**Comment by ruchi393** [comment]
Yes, you can track this under - https://linaro.atlassian.net/browse/TS-6

**Comment by etienne-lms** [comment]
> > (...) asymmetric derivation wasnt merged into the current pkcs#11
> (...) PR for ECDSA (...)

What you expect is ECDH, not ECDSA. It is not net implemented at upstream. Contributions are welcome. SKS is (I think) a good basis for that feature.

**Comment by vesajaaskelainen** [comment]
Do you have use case where you are using it?

I have that code probably in my devel branch.

Only issue I recall that was missing was to have different public key formats being supported.

But it would help to have real use case so we have proper test that can be also replicated with another set of tooling too.

**Comment by ldts** [comment]
@vesajaaskelainen, yes we do ...nothing obscure though; something like this would suffice:

**create the keys**
pkcs11-tool --module /usr/lib/libckteec.so.0.1 --keypairgen --key-type EC:prime256v1 --id 01 --label tls --token-label fio --pin 87654321
pkcs11-tool --module /usr/lib/libckteec.so.0.1 --keypairgen --key-type EC:prime256v1 --id 02 --label tls2 --token-label fio --pin 87654321

**then just:**
pkcs11-tool --module /usr/lib/libckteec.so.0.1 --read-object --type pubkey --id 02 --token-label fio --pin 87654321 -o /tmp/pub.der
pkcs11-tool --module /usr/lib/libckteec.so.0.1 --derive -m **ECDH1-DERIVE** --id 01 --label tls --token-label fio --pin 87654321 --input-file /tmp/pub.der --output-file /tmp/bytes

**Comment by ldts** [comment]
> > > (...) asymmetric derivation wasnt merged into the current pkcs#11
> > > (...) PR for ECDSA (...)
> 
> What you expect is ECDH, not ECDSA. It is not net implemented at upstream. Contributions are welcome. SKS is (I think) a good basis for that feature.

yes I was aware of all of the above (it is ECDH, it is not implemented upstream and sks is a good functional basis). I was wondering why wasn't it merged along with the other code from SKS - just making sure there is no fundamental issue other than time before working on it.

seems that @vesajaaskelainen might have already invested the time?

**Comment by vesajaaskelainen** [comment]
Do you have some protocol or so where you use this?... Protocols like TLS today have ephemeral keys where PKCS11 is not in the picture at all.

Mainly interested in real life use cases where these are needed:
- CKM_ECDH1_DERIVE
- CKM_ECDH1_COFACTOR_DERIVE
- CKM_ECMQV_DERIVE

I understand your example call is the first one.

The key import stuff is doable so I don't think that is a big thing. If one can do some cross functional testing setup test eg. service X here and then we have device with OP-TEE communicating with it or so would be the best.

If one just matches to like softhsm2 functionality or so we can make sure that similar operation passes but then we are missing real uses so both could be operating incorrectly.

Or if you know good test suite that can be ran that would also do.

We can also invent own tests but then we are mercy on how well we were able to review them.

**Comment by ldts** [comment]
yes do we use int in one of our internal tools. 

I already implemented the changes and validated with the NXP SE050 and SE051 elements so it is good enough ATM. Once I remove the rough edges to the implementation I'll send a PR - probably after the holiday season.

thanks for the comments.

**Comment by ldts** [comment]
will try to post the patch before 3.16 is out.
