### ISSUE TITLE
TEE API: Generate Random Numbers From Seeds

### ISSUE THREAD

**Issue by whatement** [OP-TEE/optee_os#5026]
How to generate random numbers from seeds？
In tee_api.h, I only found this fuction:
`/* Cryptographic Operations API - Random Number Generation Functions */`
`void TEE_GenerateRandom(void *randomBuffer, uint32_t randomBufferLen);`

I saw `optee_os/core/crypto/rng_fortuna.c` , How can I use them?

Thanks for your reply.

**Comment by jforissier** [comment]
Hello @whatement,

There is no API to generate weak pseudo-random numbers in a Trusted Application. Such numbers generated from a seed are not suitable for cryptographic use because they can be predicted. What are you trying to accomplish?
Note that the code in `rng_fortuna.c` is not available to TAs, it is in the TEE core (kernel).

**Comment by whatement** [comment]
Hello @jforissier , Thanks for your reply.

I need some symmetric random numbers to fill data.
I will find another way to accomplish it.

THanks.

**Comment by jforissier** [comment]
> I need some symmetric random numbers to fill data.

What is it?

**Comment by whatement** [comment]
A demand of Party A.
Anyway, thanks a lot, :).

**Comment by etienne-lms** [comment]
@whatement, FYI there is an OP-TEE extension allowing a TA to inject a seed to OP-TEE's RNG. Once done,  you can get random number using the standard GPD TEE API function`TEE_GenerateRandom()`. I think it should do what you expect to (crosscheck my assumption, I may be wrong :)

An example of how to add entropy OP-TEE's RNG can be found from the pkcs11 TA implementation, see local function [`seed_rng_pool()`](https://elixir.bootlin.com/op-tee/3.15.0/source/ta/pkcs11/src/pkcs11_token.c#L1484).
