### ISSUE TITLE
Behaviour of AES, DES, DES3 with invalid IV buffers

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#5039]
**1)**I was trying to test the behaviour of AES, DES, DES3 algorithms with some invalid IV length buffers of 64 bytes and 7 bytes.
Below are my observations:
```
algo	        src_data	key	Invalid iv	 observed
AES-ECB	=blk_len	128	64	         **TEE_SUCCESS**
AES-ECB	=blk_len	128	7	         **TEE_SUCCESS**
AES-ECB	=blk_len	192	64	         **TEE_SUCCESS**
AES-ECB	=blk_len	192	7	         **TEE_SUCCESS**
AES-ECB	=blk_len	256	64	         **TEE_SUCCESS**
AES-ECB	=blk_len	256	7	         **TEE_SUCCESS**
```

```
algo	        src_data	Invalid iv	observed
DES-ECB	=blk_len	64	         **TEE_SUCCESS**
DES-ECB	=blk_len	7	         **TEE_SUCCESS**
```

However, the TEE_CipherInit() operation using AES-CBC, AES-CTR, AES-CTS, AES-XTS, DES-CBC, DES3-ECB, DES3-CBC algorithms return the correct result of TEE_ERROR_TARGET_DEAD

So, shouldn't TEE_CipherInit() return TEE_ERROR_TARGET_DEAD for AES-ECB and DES-ECB too?

**2)**One more observation by using IV_buf=NULL and IV_len=0:

```
algo	               src_data	Invalid iv	observed
DES3-ECB	=blk_len	NULL	**TEE_ERROR_TARGET_DEAD**
```

However, the TEE_CipherInit() operation using  AES-CBC, AES-CTR, AES-CTS, AES-XTS, DES-CBC, DES3-CBC algorithms return the correct result of TEE_ERROR_TARGET_DEAD and using AES-ECB, DES-ECB TEE_CipherInit() operation returns the correct result of TEE_SUCCESS (as ECB mode doesn't need an IV at all).

So, shouldn't TEE_CipherInit() return TEE_SUCCESS for DES3-ECB too?

Environment used: OPTEE 3.15 on QEMU V8

**Comment by Hussain1811** [comment]
One more finding w.r.t using a valid IV buffer of length 8bytes for DES3-ECB, DES3-CBC with key-length=168bits and src_buffer_len=block_length (i.e. 16bytes) ----> TEE_CipherInit() fails with TEE_ERROR_TARGET_DEAD

is this expected?

**Comment by Hussain1811** [comment]
Could anyone help me with this doubt?

**Comment by manishkanal1** [comment]
Anyone able to respond to this? please help us resolve this issue. looks like a bug.

**Comment by jforissier** [comment]
> 1) I was trying to test the behaviour of AES, DES, DES3 algorithms with some invalid IV length buffers 
> So, shouldn't TEE_CipherInit() return TEE_ERROR_TARGET_DEAD for AES-ECB and DES-ECB too?

As you mentioned, ECB mode does not use an IV. The GlobalPlatform spec says "IV required: No" for the algorithms that use this mode (Table 6-6b). It also mentions "Panic Reasons: If the Initialization Vector does not have the length required by the algorithm".

From the above I think there is no strong requirement for an implementation to panic if an IV is passed for ECB, but I guess it would be acceptable too, and perhaps even desirable. I'll be happy to review and test any patch doing that.

> 2) One more observation by using IV_buf=NULL and IV_len=0:
> So, shouldn't TEE_CipherInit() return TEE_SUCCESS for DES3-ECB too?

I am quite surprised you got a panic with no IV and DES3-ECB. This case is supposed to be tested in `xtest 4003` (see [here](https://github.com/OP-TEE/optee_test/blob/3.15.0/host/xtest/regression_4000.c#L2082-L2087)), isn't it?

**Comment by Hussain1811** [comment]
> > 1. I was trying to test the behaviour of AES, DES, DES3 algorithms with some invalid IV length buffers
> >    So, shouldn't TEE_CipherInit() return TEE_ERROR_TARGET_DEAD for AES-ECB and DES-ECB too?
> 
> As you mentioned, ECB mode does not use an IV. The GlobalPlatform spec says "IV required: No" for the algorithms that use this mode (Table 6-6b). It also mentions "Panic Reasons: If the Initialization Vector does not have the length required by the algorithm".
> 
> From the above I think there is no strong requirement for an implementation to panic if an IV is passed for ECB, but I guess it would be acceptable too, and perhaps even desirable. I'll be happy to review and test any patch doing that.
> https://github.com/OP-TEE/optee_os/pull/5087

**Comment by Hussain1811** [comment]
> I am quite surprised you got a panic with no IV and DES3-ECB. This case is supposed to be tested in `xtest 4003` (see [here](https://github.com/OP-TEE/optee_test/blob/3.15.0/host/xtest/regression_4000.c#L2082-L2087)), isn't it?
i agree with you. The no IV case indeed seems to be tested there.
But, the calltrace shows that there is a panic with 0xffff0007 (i.e. TEE_ERROR_BAD_STATE). Below is my call-trace:
```
D/LD:  ldelf:168 ELF (b725c6e8-1cba-4c68-94b0-968f4eb1a4fb) at 0x8006e000
E/TC:? 0 
E/TC:? 0 TA panicked with code 0xffff0007
E/LD:  Status of TA b725c6e8-1cba-4c68-94b0-968f4eb1a4fb
E/LD:   arch: aarch64
E/LD:  region  0: va 0x80004000 pa 0x0e300000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x80006000 pa 0x0e302000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x8000e000 pa 0x0e30a000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x8000f000 pa 0x0e30b000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x80013000 pa 0x0e30f000 size 0x001000 flags r--s
E/LD:  region  5: va 0x80014000 pa 0x0e407000 size 0x003000 flags rw-s (stack)
E/LD:  region  6: va 0x8006e000 pa 0x00001000 size 0x012000 flags r-xs [0]
E/LD:  region  7: va 0x80080000 pa 0x00013000 size 0x0e5000 flags rw-s [0]
E/LD:   [0] b725c6e8-1cba-4c68-94b0-968f4eb1a4fb @ 0x8006e000
E/LD:  Call stack:
E/LD:   0x0000000080072810
E/LD:   0x000000008006e958
E/LD:   0x000000008006e1c0
E/LD:   0x0000000080074ab0
E/LD:   0x000000008006eb6c
D/TC:? 0 user_ta_enter:176 tee_user_ta_enter: TA panicked with code 0xffff0007
```

**Comment by Hussain1811** [comment]
> One more finding w.r.t using a valid IV buffer of length 8bytes for DES3-ECB, DES3-CBC with key-length=168bits and src_buffer_len=block_length (i.e. 16bytes) ----> TEE_CipherInit() fails with TEE_ERROR_TARGET_DEAD
> 
> is this expected?

Same calltrace as above for this case too.
TEE client spec says bad-state means "Operation is not valid in the current state".
Could this be because operation class is not `TEE_OPERATION_CIPHER` or if the operation state is not one of `TEE_OPERATION_STATE_INITIAL `/ `TEE_OPERATION_STATE_ACTIVE`?

**Comment by manishkanal1** [comment]
@jforissier any response to the inputs provided by @Hussain1811

**Comment by Hussain1811** [comment]
> > I am quite surprised you got a panic with no IV and DES3-ECB. This case is supposed to be tested in `xtest 4003` (see [here](https://github.com/OP-TEE/optee_test/blob/3.15.0/host/xtest/regression_4000.c#L2082-L2087)), isn't it?
> 
> i agree with you. The no IV case indeed seems to be tested there. But, the calltrace shows that there is a panic with 0xffff0007 (i.e. TEE_ERROR_BAD_STATE). Below is my call-trace:
> 
> ```
> D/LD:  ldelf:168 ELF (b725c6e8-1cba-4c68-94b0-968f4eb1a4fb) at 0x8006e000
> E/TC:? 0 
> E/TC:? 0 TA panicked with code 0xffff0007
> E/LD:  Status of TA b725c6e8-1cba-4c68-94b0-968f4eb1a4fb
> E/LD:   arch: aarch64
> E/LD:  region  0: va 0x80004000 pa 0x0e300000 size 0x002000 flags rw-s (ldelf)
> E/LD:  region  1: va 0x80006000 pa 0x0e302000 size 0x008000 flags r-xs (ldelf)
> E/LD:  region  2: va 0x8000e000 pa 0x0e30a000 size 0x001000 flags rw-s (ldelf)
> E/LD:  region  3: va 0x8000f000 pa 0x0e30b000 size 0x004000 flags rw-s (ldelf)
> E/LD:  region  4: va 0x80013000 pa 0x0e30f000 size 0x001000 flags r--s
> E/LD:  region  5: va 0x80014000 pa 0x0e407000 size 0x003000 flags rw-s (stack)
> E/LD:  region  6: va 0x8006e000 pa 0x00001000 size 0x012000 flags r-xs [0]
> E/LD:  region  7: va 0x80080000 pa 0x00013000 size 0x0e5000 flags rw-s [0]
> E/LD:   [0] b725c6e8-1cba-4c68-94b0-968f4eb1a4fb @ 0x8006e000
> E/LD:  Call stack:
> E/LD:   0x0000000080072810
> E/LD:   0x000000008006e958
> E/LD:   0x000000008006e1c0
> E/LD:   0x0000000080074ab0
> E/LD:   0x000000008006eb6c
> D/TC:? 0 user_ta_enter:176 tee_user_ta_enter: TA panicked with code 0xffff0007
> ```

@jforissier  I debugged further.
The panic is emitted from https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/ecb.c#L57
Any input as to why it could end up here?

**Comment by Hussain1811** [comment]
i was able to solve the panic issue (DES3-ECB with IV=NULL) by using a key of length 192 bits for DES3.
But, using key-length of 168 bits for DES3 results in a panic.

Am i missing something or is this expected?

**Comment by jforissier** [comment]
> i was able to solve the panic issue (DES3-ECB with IV=NULL) by using a key of length 192 bits for DES3. But, using key-length of 168 bits for DES3 results in a panic.
> 
> Am i missing something or is this expected?

Table 5-9 for TEE_TYPE_DES3 the Possible Key Sizes column mentions "128 or 192 bits including the parity bits. This gives effective key sizes of 112 or 168 bits." That could be the reason.

**Comment by Hussain1811** [comment]
Thanks @jforissier 
closing the issue
