### ISSUE TITLE
RPC_FS: how to get a ree file size

### ISSUE THREAD

**Issue by BabaYB** [OP-TEE/optee_os#5049]
I wanna read a file which is stored in linux filesystem, and want to get the file size at first
When I searched the optee_os v3.2  and  found no API to do that.
And found rpc_fs_lseek in an older version, but which is removed now.

So why we removed that and what can we do now.

thanks,
Yiping

**Comment by etienne-lms** [comment]
Hi, optee is not expected expose linux posix files internally. It rather manipulates objects possibly stored as file in a Linux filesystem. If you need optee core side to expose a posix-file-like API (to drivers? TAs?), this should be specifically implemented.

Secure non-volatile data of optee should not be stored in linux files but rather in optee_os secstor (secure storage) subsystem.

**Comment by BabaYB** [comment]
All right, thanks @etienne-lms
