### ISSUE TITLE
bget_malloc.c is thre any chance to make use of generic spinlock functions ? 

### ISSUE THREAD

**Issue by maroueneboubakri** [OP-TEE/optee_os#5058]
Actually `malloc_lock()` and `malloc_unlock()` in  `bget_malloc.c` call respectively ` cpu_spin_lock_xsave()` and `cpu_spin_unlock_xrestore() `which are defined and implemented in arch specific folder.  Moving `spinlock.h`, where these functions are implemented, to `core/include/kernel` seems not a good idea. Putting the first milestone towards a new architecture involves then implementing these functions at the very beginning. This is indeed required but, this way we will end having a very big first commit difficult to review. 

Does splitting `spinlock.h` to 2 parts, abstract functions go in `core/include/kernel/spinlock.h` and architecture-specific implementation in `core/arch/$(ARCH)/include/kernel/spinlock.h` work ? for sure we cant have 2 files with same name, spinlock_private.h ?
 
Doing the same for `thread.h` and `core_mmu.h` would result to a big work.

Do you have any suggestion ? @jforissier @jenswi-linaro @etienne-lms

**Comment by etienne-lms** [comment]
Looking at `spinlock.h`, it seems to me it could move to `core/include/kernel/`, as well as `spin_lock_debug.c`.

`spinlock.h` requires `thread_foreign_intr_disabled()`, `thread_mask_exceptions(THREAD_EXCP_ALL)` and `thread_unmask_exceptions()`. They could be declared in by the generic `thread.h`.

`spin_lock_debug.c` needs to increase/decrase/read field `locked_count` from the core thread context. There could be generic API functions for that purpose in `core/include/kernel/thread.h`.

If splitting **thread.h** header file, my 2 cents (to prevent update in many existing source files that include **kernel/thread.h**): 
maybe use a known arch filename e.g. **core/arch/arm/include/kernel/thread_arch.h**
and add `#include <kernel/thread_arch.h>` from generic **core/include/kernel/thread.h**.

For `thread.h` and `core_mmu.h`, there is more work to split architecture specific APIs from generic APIs.

**Comment by jenswi-linaro** [comment]
Splitting **thread.h** will be interesting. Etienne's suggestions sounds like a good start.
