### ISSUE TITLE
TEE_MACCompareFinal issue

### ISSUE THREAD

**Issue by ydonghyuk** [OP-TEE/optee_os#5063]
Hello,

I am verifying the sign/verify operation of HMAC (sha2_256) using OPTEE-based linaro-kmgk keymaster.
There is a confusion in the verification process, so I ask for your opinion.

More specifically, it is an operation method of the TEE_MACCompareFinal function.

- condition
 1/ algorithm: HMAC
 2/ digest: SHA2_256

- Test process
 1/ generate key (192bit)
 2/ sign (mac length: 160bit)
 3/ verify

- Result
 TEE_ERROR_MAC_INVALID

We confirmed that the test passed with the patch below.
However, we wonder why the truncated MAC is not being verified and what issue was there.

```
diff --git a/lib/libutee/tee_api_operations.c b/lib/libutee/tee_api_operations.c
index 4323e985..368fac56 100644
--- a/lib/libutee/tee_api_operations.c
+++ b/lib/libutee/tee_api_operations.c
@@ -1265,12 +1265,7 @@ TEE_Result TEE_MACCompareFinal(TEE_OperationHandle operation,
        if (res != TEE_SUCCESS)
                goto out;

-       if (computed_mac_size != macLen) {
-               res = TEE_ERROR_MAC_INVALID;
-               goto out;
-       }
-
-       if (consttime_memcmp(mac, computed_mac, computed_mac_size) != 0) {
+       if (consttime_memcmp(mac, computed_mac, macLen) != 0) {
                res = TEE_ERROR_MAC_INVALID;
                goto out;
        }
```

Thanks & Regards

**Comment by vchong** [comment]
@ydonghyuk I've moved this to linaro-swg/kmgk#29 for better tracking. We'll take a look and reply back over there asap. Will close this now.

**Comment by ydonghyuk** [comment]
> @ydonghyuk I've moved this to [linaro-swg/kmgk#29](https://github.com/linaro-swg/kmgk/issues/29) for better tracking. We'll take a look and reply back over there asap. Will close this now.

Ok, thanks
