### ISSUE TITLE
Saving Program Crash Information Trusted side

### ISSUE THREAD

**Issue by esaurimentocronico** [OP-TEE/optee_os#5064]
HI Everyone,

i have been working on optee_os and i have a question for you all. What i would like to do is to save information about a program crash. More especially i noticed when a program in Normal World had crashed then  the corresponding Trusted side, which is running in the Secure World, closed the session and destroyed it. Before that, i need to save the information about program crash in the Trusted side. I’m assuming there’s a library that sends a signal to the trusted application in order to get to close the trusted side after a program in Normal World crashed (is it right ?).
 
So my question are:
- How this process is handled in optee os? I 
-  Which file (if it exists) could i look at ?
- 
Thank you.

**Comment by jenswi-linaro** [comment]
There's no crash information sent to the secure side. When a process in Linux is killed all its file descriptors are closed. So when the open TEE device file descriptor is closed then all sessions opened on file descriptor are closed.

What you probably have to do is to install a crash handler in the process itself or by using a helper process which monitors your process and later can pass on the collected crash information.

**Comment by esaurimentocronico** [comment]
> 

Thank you for your answer. I am not interested in crash information in the secure side, because i have a shadow stack which is running there as a TA. But when the program, which is running in Normal World, crashed i lost that information. So i am interested in sending that information,which are collect by my TA, before the session is closed. Therefore i was wondering how the TA  is closed when the program in Normal World crashed in order to modify that process by sending infomation before the session is closed. I hope i was clear enough about my goal, if not, please just let me know

**Comment by jenswi-linaro** [comment]
You have at least two options. You can configure the TA as `TA_FLAG_INSTANCE_KEEP_ALIVE` so the next time you open a session to the TA the state is still there provided that the system isn't rebooted. Another option is to save eventual state which hasn't been retrieved in secure storage when the TA is notified that it's about to be shut down.

**Comment by esaurimentocronico** [comment]
> 

i got it for the first one. About the second one in particular how  `the TA is notified that it's about to be shut down` ?

Thank you

**Comment by jenswi-linaro** [comment]
TA_CloseSessionEntryPoint() is called when a session is close and TA_DestroyEntryPoint() is called when the TA is about to be lose its context.

**Comment by esaurimentocronico** [comment]
> 

Thank you so much!

**Comment by esaurimentocronico** [comment]
Hi, following your advise i used the TA_DestroyEntryPoint() to print some information i was interested in. However when a `SIGSEGV` occurs, the TA does not call the TA_DestroyEntryPoint() therefore the TA does not terminate correctly.
Following an example:

![problem](https://user-images.githubusercontent.com/64956187/148761937-98e8f459-a37a-46bf-a587-987f0e32dbcd.png)

Now my question are:

- How can i handle that ? 
- Can I force the application to close correctly and call the TA_DestroyEntryPoint() when a `SIGSEGV` occurs ? If yes, how ?

**Comment by jenswi-linaro** [comment]
This is a known problem in the kernel driver. One workaround is to compile OP-TEE with `CFG_PREALLOC_RPC_CACHE=n`. I'm working on a fix for this. I plan to post something in the next few weeks.

**Comment by esaurimentocronico** [comment]
OK, thank you so much once again. Can you let me know when you do it please? I’m really interested about that.

**Comment by jenswi-linaro** [comment]
Keep an eye on the `TEE TrustedFirmware <op-tee@lists.trustedfirmware.org>` list and you'll see it.

**Comment by esaurimentocronico** [comment]
Hi, mr @jenswi-linaro 

Has the problem been fixed ?
Moreover i was reading the TEE Internal Core API Specification, and i was wondering if it's possible to open a socket from TA to a remote server i found nothing about it.

Thank you

**Comment by jenswi-linaro** [comment]
> Has the problem been fixed ? 

This is currently under review, see
https://lore.kernel.org/lkml/20220301194830.3557578-1-jens.wiklander@linaro.org/T/

> Moreover i was reading the TEE Internal Core API Specification, and i was wondering if it's possible to open a socket from TA to a remote server in order to send information out the TA to be analyzed. I found nothing about that.

That's covered in TEE Sockets API Specification,
https://globalplatform.org/specs-library/tee-sockets-api-specification/
OP-TEE currently has support for unencrypted TCP and UDP sockets.

**Comment by esaurimentocronico** [comment]
> > Has the problem been fixed ?
> 
> This is currently under review, see https://lore.kernel.org/lkml/20220301194830.3557578-1-jens.wiklander@linaro.org/T/
> 
> > Moreover i was reading the TEE Internal Core API Specification, and i was wondering if it's possible to open a socket from TA to a remote server in order to send information out the TA to be analyzed. I found nothing about that.
> 
> That's covered in TEE Sockets API Specification, https://globalplatform.org/specs-library/tee-sockets-api-specification/ OP-TEE currently has support for unencrypted TCP and UDP sockets.

Thank you for your reply. I still got an error in opening TEE_Socket. A netcat instance is listening on port 1443 in localhost and following my snippet of code which is supposed to open a tcp socket:

```
char* address = "127.0.0.1";
uint16_t port = 1443;
char *message = "Hello world!";

TEE_Result open_socket(char *addr, uint16_t port){
	uint32_t protocolError;
	TEE_tcpSocket_Setup tcpSetup;
	TEE_Result openErrTcp;
	TEE_Result send_message;
	TEE_iSocketHandle tcpCtx;

	tcpSetup.ipVersion = TEE_IP_VERSION_DC;
	tcpSetup.server_addr = addr;
	tcpSetup.server_port = port;
	
	//open tcp socket
	openErrTcp = TEE_tcpSocket->open(&tcpCtx, &tcpSetup, &protocolError);
	
	if (openErrTcp != TEE_SUCCESS){
		IMSG("Failed to open() TCP, error: %#010x ", openErrTcp);
		IMSG("protocolError: %#010x\n", protocolError);
		if (openErrTcp == TEE_ERROR_BAD_PARAMETERS) IMSG("Bad parameters.\n");
		if (openErrTcp == TEE_ERROR_COMMUNICATION) IMSG("Unable to connect.\n");
		if (openErrTcp == TEE_ISOCKET_ERROR_TIMEOUT) IMSG("Connection timeout\n");
		if (openErrTcp == TEE_ERROR_COMMUNICATION) IMSG("Error in communication\n");
		if (openErrTcp == TEE_ISOCKET_ERROR_PROTOCOL && protocolError == TEE_ISOCKET_ERROR_HOSTNAME) IMSG("Unknown hostname.\n");
		
		return openErrTcp;
	}
	uint32_t lenght = (uint32_t) (strlen(message));
	send_message = TEE_tcpSocket->send(&tcpCtx,message,lenght,10);
	if(send_message == TEE_SUCCESS) IMSG("Message Sent\n");

	TEE_tcpSocket->close(tcpCtx);
	return openErrTcp;
}	
```

When i run it in optee_os i got the following output ta side:
```

D/TC:? 0 tee_ta_close_session:531 Destroy session
I/TA: TA_CloseSessionEntryPoint hash been called
D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA 3b996a7d-2c2b-4a49-a896-e1fb5766d2f4
D/TC:? 0 tee_ta_init_pseudo_ta_session:312 Open socket
D/TC:? 0 tee_ta_init_pseudo_ta_session:329 socket : 3b996a7d-2c2b-4a49-a896-e1fb5766d2f4
D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 tee_ta_init_pseudo_ta_session:312 Open system.pta
D/TC:? 0 tee_ta_init_pseudo_ta_session:329 system.pta : 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 tee_ta_invoke_command:823 Error: ffff000e of 4
I/TA: Failed to open() TCP, error: 0xffff000e 
I/TA: protocolError: 0000000000
I/TA: Unable to connect.
I/TA: Error in communication
D/TA:  TA_DestroyEntryPoint:272 TA_DestroyEntryPoint has been called
D/TC:? 0 destroy_context:308 Destroy TA ctx (0xa73b3c60)
D/TC:? 0 tee_ta_close_session:512 csess 0xa73b2fc0 id 1
D/TC:? 0 tee_ta_close_session:531 Destroy session
D/TC:? 0 tee_ta_close_session:512 csess 0xa73b2e98 id 2
D/TC:? 0 tee_ta_close_session:531 Destroy session
```
Can you help me please ?
