### ISSUE TITLE
RPMB capacity

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#5068]
I have a short doubt on the code-snippet https://github.com/OP-TEE/optee_test/blob/master/host/xtest/regression_6000.c#L1685
May i know on what basis were "num_blocks", "block-size", "block" chosen? is it defined in the RPMB spec somewhere?

**Comment by jforissier** [comment]
Hi @Hussain1811,

The values used for num_blocks and block_size are not directly related to RPMB, at least not to some numbers in some specification. They were just chosen for the test to pass with the default configurations we use to test OP-TEE (RPMB emulation in tee-supplicant). The blocks are not RPMB blocks - they are just chunks of data written and read by the TA.

**Comment by Hussain1811** [comment]
Alright - thanks for the clarification.
