### ISSUE TITLE
RISC-V port

### ISSUE THREAD

**Issue by maroueneboubakri** [OP-TEE/optee_os#5074]
How to proceed to start pushing RISC-V port ? Would be possible to have a separate branch ? What about the CI ?

**Comment by jenswi-linaro** [comment]
A problem with a branch is that it can get outdated compared to the master branch and result in merge conflicts when merging back to master. I'd rather take it on master piece by piece. It this stalls for more than a year (long enough, too long?) for some reason we may have to decide what to do with the incomplete port. If we find it too incomplete we way very well decide to just remove it.

The first commit touching on `core/arch/riscv` should ideally compile. I guess we can be flexible with the early commits if needed, given that nothing for RISC-V has been compiled so far.

For CI it it might be best to keep that as a separate check. I hope we have room for another check in Azure. At some point we'll want to have boot tests in CI too, but that can wait a little.

**Comment by jforissier** [comment]
> A problem with a branch is that it can get outdated compared to the master branch and result in merge conflicts when merging back to master. I'd rather take it on master piece by piece. It this stalls for more than a year (long enough, too long?) for some reason we may have to decide what to do with the incomplete port. If we find it too incomplete we way very well decide to just remove it.

Agreed.
 
> The first commit touching on `core/arch/riscv` should ideally compile. I guess we can be flexible with the early commits if needed, given that nothing for RISC-V has been compiled so far.

Yes, as long as the new code doesn't introduce any issue with current users, it's OK. I'd rather avoid too much code churn though, in other words try to avoid to introduce things in one commit and change them completely later. I suppose you already have a somewhat working port of OP-TEE to RISC-V, so it shouldn't be too difficult.

> For CI it it might be best to keep that as a separate check. I hope we have room for another check in Azure. At some point we'll want to have boot tests in CI too, but that can wait a little.

We can easily add one or more build checks to the `build_all` job. I could install the required cross-compiler(s) in the Docker image, then after the Arm builds we could create a new section for RISC-V, set `CROSS_COMPILE{32,64}` and `ARCH` as needed and run `make PLATFORM=...` or whatever. That would take a few seconds or minutes maximum.

As for the boot tests, we can write a new job similar to the `QEMUv8_check` job. We have 4 jobs currently in the Azure script, one is quick (code style check), and we can have up to 10 jobs running in parallel for the whole project. Excess jobs are simply queued.
