### ISSUE TITLE
Reserve 1MB of memory for boot log in QEMUv8

### ISSUE THREAD

**Issue by DevendraDevadiga** [OP-TEE/optee_os#5078]
Hi,

I am working on QEMUv8 with OP-TEE OS 3.15.

Currently memory for QEMUv8 is as below and using generic layout:

#0e00.0000 0e0f.ffff] is reserved to early boot
CFG_TZDRAM_START ?= 0x0e100000
CFG_TZDRAM_SIZE  ?= 0x00f00000
#SHM chosen arbitrary, in a way that it does not interfere
#with initial location of linux kernel, dtb and initrd.
CFG_SHMEM_START ?= 0x42000000
CFG_SHMEM_SIZE  ?= 0x00200000
#When Secure Data Path is enable, last MByte of TZDRAM is SDP test memory.
CFG_TEE_SDP_MEM_SIZE ?= 0x00400000

But I want to reserve another 1MB memory as secure.
I tried as below
CFG_SHMEM_START ?= 0x42000000
CFG_SHMEM_SIZE  ?= 0x00200000
CFG_CUSTOM_REQ_MEM_SIZE ?= 0x100000
CFG_CUSTOM_REQ_MEM_START = (CFG_SHMEM_START - CFG_CUSTOM_REQ_MEM_SIZE)

So CFG_CUSTOM_REQ_MEM_START is : 0x41F00000

In main.c file I tried to add this memory as secure but OP-TEE is not booting completely and just stops after displaying memory information.
I tried as below:
register_phys_mem_pgdir(MEM_AREA_IO_SEC, CFG_CUSTOM_REQ_MEM_START, CFG_CUSTOM_REQ_MEM_SIZE)
I tried by adding MEM_AREA_NSEC_SHM also but still it's stopping.

Please can you help me on this?
I need to do any changes in ATF or Linux also?
@etienne-lms @jenswi-linaro 
I checked this commit, any changes in Linux DTS or ATF is done when configuring secure memory?
https://github.com/OP-TEE/optee_os/commit/03314a3a69b8465e4cb6377115a0baa5e38112b1#diff-1cd02f34daacb13bd8dfb29f7ddcd401a0cf4bf624d926487786ed16984879d6

And I want to know how Linux will come to secure region are reserved for OP-TEE? I know for some platform it's done in Linux DTS with memory reserved keyword.
For QEMUv8 also similar changes done? If yes can send me Linux source code path corresponding to this?

Regards,
Devendra

**Comment by DevendraDevadiga** [comment]
Hi,

Here I got memory map details of QEMUv8 we used.

https://github.com/qemu/qemu/blob/master/hw/arm/virt.c#L132

Here DDR RAM is not used I think.
First 128MB of flash memory is used.

**Comment by DevendraDevadiga** [comment]
Yes, for qemu armv7 case here I modified and added extra 1MB of memory and used that for storing secure boot log.
https://github.com/qemu/qemu/blob/master/hw/arm/virt.c#L158
Changed as below:
- [VIRT_SECURE_MEM] =         { 0x0e000000, 0x01000000 },
+    [VIRT_SECURE_MEM] =         { 0x0e000000, 0x01100000 },

And in here I added as below:
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-vexpress/conf.mk#L92
CFG_TZDRAM_START ?= 0x0e100000
CFG_TZDRAM_SIZE  ?= 0x00f00000
CFG_BOOT_LOG_START ?= (CFG_TZDRAM_START + CFG_TZDRAM_SIZE)
CFG_BOOT_LOG_SIZE ?= 0x100000

In main.c I added as below and it's working fine for qemu armv7 case.
register_phys_mem_pgdir(MEM_AREA_IO_SEC, CFG_BOOT_LOG_START, CFG_BOOT_LOG_SIZE);

It's working fine. Now have try same for QEMUv8 case.
But but conf.mk for armv8 case it's not mentioned properly the values of CFG_TZDRAM_START and CFG_TZDRAM_SIZE. I am checking this one.

**Comment by jenswi-linaro** [comment]
To me it looks like we have identical memory configuration for armv7 and armv8 except for CFG_SHMEM_START.
