### ISSUE TITLE
Does OP-TEE make any assumption about LD version? 

### ISSUE THREAD

**Issue by xyzhao2018** [OP-TEE/optee_os#5084]
We compiled OP-TEE with gcc 10.2.0, but found ELF populate segment error when loading specific ta, ffd2bded-ab7d-4988-95ee-e4962fff7154.ta during xTest 1006 case. 
We found if using ld v2.30, the case pass, for ld v>2.34, failed. 
The failed reason is offset check error during ELF populating segment. 
After checking the elf content, we found v2.34 generated more segment sections than v2.30 as below. 

For v2.30
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x000000000000a9cc 0x000000000000a9cc  R E    0x1000
  LOAD           0x000000000000ae78 0x000000000000be78 0x000000000000be78
                 0x00000000000003a8 0x00000000000003c0  RW     0x1000
  DYNAMIC        0x000000000000ae88 0x000000000000be88 0x000000000000be88
                 0x0000000000000160 0x0000000000000160  RW     0x8
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RWE    0x10
  GNU_RELRO      0x000000000000ae78 0x000000000000be78 0x000000000000be78
                 0x0000000000000188 0x0000000000000188  R      0x1
For v2.34
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000000026b8 0x00000000000026b8  R      0x1000
  LOAD           0x0000000000003000 0x0000000000003000 0x0000000000003000
                 0x0000000000006bfe 0x0000000000006bfe  R E    0x1000
  LOAD           0x000000000000a000 0x000000000000a000 0x000000000000a000
                 0x00000000000016fc 0x00000000000016fc  R      0x1000
  LOAD           0x000000000000be78 0x000000000000ce78 0x000000000000ce78
                 0x00000000000003a8 0x00000000000003c0  RW     0x1000
  DYNAMIC        0x000000000000be88 0x000000000000ce88 0x000000000000ce88
                 0x0000000000000160 0x0000000000000160  RW     0x8
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RWE    0x10
  GNU_RELRO      0x000000000000be78 0x000000000000ce78 0x000000000000ce78
                 0x0000000000000188 0x0000000000000188  R      0x1

The additional LOAD result in offset calculation different during adjustment, so it result in offset check failed in binh_copy_to(). 
if (offs_bytes < binh->offs_bytes) {
		return TEE_ERROR_BAD_STATE;
	}

So does OP-TEE have any assumption about LD version? 
Any comments about this issue? Thanks.

**Comment by jforissier** [comment]
Hello @xyzhao2018,

Which toolchain is it? I don't have any issue with the Arm GCC 10.2 cross compiler (the one downloaded by [`toolchain.mk`](https://github.com/OP-TEE/build/blob/495dc6a/toolchain.mk#L54-L55)):
```
$ ~/work/toolchains-gcc10.2/aarch64/bin/aarch64-linux-gnu-ld --version | head -1
GNU ld (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16)) 2.35.1.20201028
```
There is no precise assumption about the version of LD in OP-TEE, but for simplicity the TA loader (ldelf) does assume a few things regarding the format of the ELF file. In this case, perhaps the TA loader needs to be updated to accept the output generated by your linker, or perhaps the fix needs to be done in the TA linker script (`ta/arch/arm/ta.ld.S`).

**Comment by xyzhao2018** [comment]
Thanks for your feedback, we have found the solution that don't split the PT_LOAD segment.
