### ISSUE TITLE
Is there a way to share some keys/data between TAs?

### ISSUE THREAD

**Issue by bansalcheryl** [OP-TEE/optee_os#5092]

**Comment by jforissier** [comment]
Not directly but you can share data thanks to TA-to-TA communication (`TEE_InvokeTACommand()`).

**Comment by bansalcheryl** [comment]
Is there a way to create a persistent object and share between TAs?
In case of TA-to-TA communication, how is the TA lifetime managed? and is there a way to connect two pre-launched TAs instead of parent-child TAs?

**Comment by jenswi-linaro** [comment]
> Is there a way to create a persistent object and share between TAs?

Only if they have the same UUID, that is, different instances of a TA shares storage.

> In case of TA-to-TA communication, how is the TA lifetime managed?

In the usual way with open and close session.

> and is there a way to connect two pre-launched TAs instead of parent-child TAs? like creating a pseudo TA and keeping the data with it, and multiple TA saving/taking it from pseudo TA

Sure, I don't see why you'd need a pseudo TA though.

**Comment by bansalcheryl** [comment]
Thanks for the help.
So two pre-launched TAs can also connect through TA Internal APIs, in which case a new instance of the TA will be created? 
The sequence will be open TA session, invoke TA command (get the shared data) and close TA session. Is that right?

**Comment by jenswi-linaro** [comment]
> Thanks for the help. So two pre-launched TAs can also connect through TA Internal APIs, in which case a new instance of the TA will be created?

That depends on the TA flags, if it's a single-instance multi-session TA then the original instance will be used instead.

> The sequence will be open TA session, invoke TA command (get the shared data) and close TA session. Is that right?

Sure, you can also keep the session open depending on the use case.

**Comment by bansalcheryl** [comment]
Thank you for support @jenswi-linaro @jforissier :)
I have a few questions regarding PTA, can a PTA spawn threads? and should we be adding a pta if we are adding a driver in Optee OS? and is there a development guide on adding a driver in Optee OS?

**Comment by jenswi-linaro** [comment]
> I have a few questions regarding PTA, can a PTA spawn threads?

No

> and should we be adding a pta if we are adding a driver in Optee OS?

I guess that depends on the driver and how you're going to interact with it.

> and is there a development guide on adding a driver in Optee OS?

This is what we have https://optee.readthedocs.io/en/latest/ , but I'm afraid there isn't much about drivers.
We usually try to provide an abstract interface. Take a look at core/include/drivers/serial.h for instance.

**Comment by bansalcheryl** [comment]
Thank you @jenswi-linaro for the response. I'll look into it.

**Comment by bansalcheryl** [comment]
Hi
Can we do TEE_Identity check in PTA? 
Also is there is a coding guideline defined for Optee OS and CA-TA?

**Comment by jenswi-linaro** [comment]
> Hi Can we do TEE_Identity check in PTA?

``` C
struct ts_session *s;
struct tee_ta_session *ta_s;

s = ts_get_calling_session();
if (!is_user_ta_ctx(s->ctx))
     goto err;
ta_s = to_ta_session(s);
/* ta_s->clnt_id holds the client identity */
```

Also is there is a coding guideline defined for Optee OS and CA-TA?

For OP-TEE OS https://optee.readthedocs.io/en/latest/general/coding_standards.html

**Comment by bansalcheryl** [comment]
Thank you @jenswi-linaro :)

**Comment by bansalcheryl** [comment]
Is there a way to share data between multiple instances of same TA?

So I want to spawn multiple threads in a TA waiting for commands which are to be handled in parallel, and as I understand, multiple sessions won't provide a way as the commands are still blocking, right? and TA cannot spawn threads?
So only option is multiple instances but can they share data? If not, only way to do it is to keep a separate TA which acts as the data store?

**Comment by jforissier** [comment]
> So I want to spawn multiple threads in a TA waiting for commands which are to be handled in parallel, and as I understand, multiple sessions won't provide a way as the commands are still blocking, right?

Correct.

> and TA cannot spawn threads?

Correct. TA are single threaded.

> So only option is multiple instances but can they share data?

Yes, multiple instances should work. To share data, you may use secure storage which is per-TA. So each instance of the same TA is able to read/write the same persistent objects.

> If not, only way to do it is to keep a separate TA which acts as the data store?

A separate TA is another way but maybe more complex.

**Comment by bansalcheryl** [comment]
> Yes, multiple instances should work. To share data, you may use secure storage which is per-TA. So each instance of the same TA is able to read/write the same persistent objects.
> 
> >

So, even if all the sessions are closed, will the persistent object be available to the sessions which are opened later? Assuming this is a Multi-Instance TA

**Comment by jforissier** [comment]
> So, even if all the sessions are closed, will the persistent object be available to the sessions which are opened later? Assuming this is a Multi-Instance TA

Yes. A persistent object is similar to a file, it is stored in secure storage (in the Linux filesystem or in RPMB depending on how OP-TEE is configured and which storage ID the TA uses). Even when the device is rebooted, the persistent objects remain.

**Comment by bansalcheryl** [comment]
> So in this case, all the commands in a session will be sequential but all the sessions will be handled in parallel right?

Is that the case @jforissier ?

**Comment by jforissier** [comment]
> Thank you @jforissier So in this case, [...] all the sessions will be handled in parallel right?

Yes

>  all the commands in a session will be sequential

No, if I'm not mistaken any command can enter the PTA at any time when `TA_FLAG_CONCURRENT` is set (in case the CA is multi-lthreaded).

**Comment by bansalcheryl** [comment]
Ok, I went through the code and it seems any command from any session can be processed in parallel.
Thanks for helping out @jforissier :)
