### ISSUE TITLE
OP-TEE EC Signature curve specification

### ISSUE THREAD

**Issue by rafagameiro** [OP-TEE/optee_os#5114]
Hi everyone,

I'm currently developing a TA to do some ECDSA signature and I was wondering which curve is OP-TEE using, because my objective would be to verify the signature on the Normal World side and to do that I would need the curve specification.
I know that OP-TEE uses the GlobalPlatform specifications, but unfortunately I haven't been able to find any information regarding this matter.
Does any of you know which curves are bring used during EC sign?
If not, could someone provide with some pointer or contact to GP so that I can ask them directly?

Best Regards

**Comment by jforissier** [comment]
Hi @rafagameiro,
The supported curves are NIST P192, P224, P256, P384 and P521. See https://github.com/OP-TEE/optee_os/blob/3.15.0/lib/libutee/include/tee_api_defines.h#L284-L290.

**Comment by rafagameiro** [comment]
Great!
Thank you very much for the help @jforissier  !!
Given the question was answered I'll close this issue
