### ISSUE TITLE
duplicate CFG_MMU_V7_TTB at plat-imx/conf.mk

### ISSUE THREAD

**Issue by murasesyuka** [OP-TEE/optee_os#512]
it a trivial matter. duplicate CFG_MMU_V7_TTB.

https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-imx/conf.mk#L7..L17

**Comment by pascal-brand-st-dev** [comment]
Do not hesitate to contribute. Pascal.

**Comment by murasesyuka** [comment]
I see. make a PR.
