### ISSUE TITLE
Define SDP memory area in embedded DTB

### ISSUE THREAD

**Issue by omasse-linaro** [OP-TEE/optee_os#5133]
As an improvement, could it be possible to define the Secure Data Path memory region in an embedded dtb instead of the scattered array ?
Probably something like that:
```
	sdp_mem {
		compatible = "optee_sdp";
		region = <0x8C000000 0x02000000>;
	}
```

This memory region would not rely on a core_mmu_phys_mem structure definition, but a dtb one.

**Comment by jenswi-linaro** [comment]
Adding stuff to DT takes a bit of consideration. We don't want to define our own standard in secure world.
Is there anything already defined that can be used for this purpose?

**Comment by omasse-linaro** [comment]
I do not thing that something has already been defined for SDP in DT. But what about reserved memory which could be used to define the SDP memory ?
`	reserved-memory {
		#address-cells = <1>;
		#size-cells = <1>;

		sdp_mem {
			compatible = "optee-sdp";
			reg = <0xCC000000 0x02000000>;
		};
	};
`

**Comment by jforissier** [comment]
@omasse-linaro yes it is done in linaro-swg/linux branch [optee](https://github.com/linaro-swg/linux/tree/optee), see for instance commit https://github.com/linaro-swg/linux/commit/2a766ee9fe7cfd63cf011337663e45ed35fa56fd (plus the `no-map` property is added in a subsequent commit).

**Comment by omasse-linaro** [comment]
> Edit 2 Given that the ION/dmabuf code on which SDP was based has been modified/removed upstream (see discussion [here](https://github.com/linaro-swg/linux/issues/91)), I'm not sure discussing DT for SDP even makes sense until a proper implementation supported upstream is proposed.

@jforissier you are right, optee-test should rely on DMA buff heaps to test SDP in Kernel 5.10 and more.
@jbech-linaro  confirm us that @ruchi393 has this on the roadmap.

in the meantime, optee-os could use DT to define SDP.

**Comment by jbech-linaro** [comment]
> @jbech-linaro confirm us that @ruchi393 has this on the roadmap.

Yes, fixing SDP is on @ruchi393 roadmap, but it has lower priority for the moment IIRC.

**Comment by omasse-linaro** [comment]
Please find a first draft of the modifications here https://github.com/OP-TEE/optee_os/pull/5149

**Comment by jenswi-linaro** [comment]
So far we have managed to avoid defining our own bindings in OP-TEE, instead we've been able to reuse already established bindings. With this you're proposing something new. I'm not sure of the best way of doing such a thing. Are we sure there is nothing to reuse?
If not: How should it be reviewed? Who should review it?
