### ISSUE TITLE
 How does host access the service of normal world

### ISSUE THREAD

**Issue by gaojunjie03** [OP-TEE/optee_os#5137]
I started an HTTP service on normal world, port 8080

How do I access the HTTP service on the host machine? Even if I set hostfwd (- netdev user, id = vmnic, hostfwd = TCP:: 8080 -: 8080), curl cannot access the HTTP service

**Comment by jforissier** [comment]
Hello @gaojunjie03,

This is a question more related to QEMU than OP-TEE so perhaps you should ask on a QEMU forum. I can only recommend you double check your command line:

> (- netdev user, id = vmnic, hostfwd = TCP:: 8080 -: 8080)

Try `-netdev user,id=vmnic,hostfwd=tcp::8080-:8080`.
