### ISSUE TITLE
Can 64bit OPTEE-OS work properly with 32bit kernel?

### ISSUE THREAD

**Issue by tiehichi** [OP-TEE/optee_os#5138]
Hi Everyone,

I'm debugging OPTEE OS on a MediaTek platform, OPTEE OS is 64-bit but linux kernel is 32-bit, will they work properly? I tried to run xtest and it does communicate with TA, but it always causes a random kernel panic, I'm not sure what the problem is caused by.
Can anyone give me some advice?

By the way, all CAs including tee-supplicate and xtest are 32-bit programs, and all TAs are 64-bit programs

**Comment by jenswi-linaro** [comment]
It's probably not tested on a regular basis, but it is supposed to work.

**Comment by tiehichi** [comment]
Hi @jenswi-linaro 

Thanks for your reply, I'm sure it was caused by a memory issue, 64-bit TA does work fine with 32-bit CA.
