### ISSUE TITLE
pkcs11 aes_cbc padding questions

### ISSUE THREAD

**Issue by cmcgcc** [OP-TEE/optee_os#5142]
We are trying to use PKCS11_CKM_AES_CBC_PAD for encryption. But it failed without padding by ourselves.
I did not see any padding implementation in the TA source code.
Did I miss anything? Or is it still under development?

And is aes gcm also in the road map?

Thanks

**Comment by etienne-lms** [comment]
The implementation is bugged. From 3.16.0-rc1:
https://github.com/OP-TEE/optee_os/blob/a5ea52c21e0de82830dbf3beaa95895b2697deb5/ta/pkcs11/src/processing_symm.c#L70

GPD TEE API spec does not define AES CBC pad operation. It seems the TA should be changed to state CKM_AES_CBC_PAD is not supported. Do you want to propose a fix?
@jforissier, could you tag this issue as a **bug**?

As for AES GCM, there is no one working on that up to my knowledge. There are implementation studies (e.g. [here](https://github.com/etienne-lms/optee_os/blob/sks-to-pkcs11/ta/pkcs11/src/processing_aes.c)) but nothing yet was submitted to the upstream. Contributions are welcome.

**Comment by jforissier** [comment]
> @jforissier, could you tag this issue as a **bug**?

Done.

**Comment by etienne-lms** [comment]
@cmcgcc, while looking at this, i made this [change](https://github.com/OP-TEE/optee_os/pull/5154). It is fine to you?

**Comment by cmcgcc** [comment]
@etienne-lms @jforissier  I made a draft pull request for encryption padding. Let me know your thoughts. Thanks.
https://github.com/OP-TEE/optee_os/pull/5239
