### ISSUE TITLE
Wrong Key-usage value for AES-XTS

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#5148]
Spec mentions the following:
_requiredKeyUsage: A bit vector that describes the necessary bits in the object usage for
TEE_SetOperationKey or TEE_SetOperationKey2 to succeed without panicking. Set to 0 for a
digest operation. If multiple keys are required by this type of operation, then this value SHALL be set
to 0._

But, i get the values `TEE_USAGE_ENCRYPT `and `TEE_USAGE_DECRYPT` after allocating encryption and decryption op-handles for AES-XTS algorithm.

Is this a bug?

**Comment by jenswi-linaro** [comment]
It is unexpected. Would you be able to dig into the code a bit?

**Comment by Hussain1811** [comment]
Basically occurs over here: https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_operations.c#L141
We might need to reset to 0 after this block.
Shall i propose a patch?

**Comment by jenswi-linaro** [comment]
It is reset at:
https://github.com/OP-TEE/optee_os/blob/9e8852d7958570dc92d5d54322d088fbcab6326d/lib/libutee/tee_api_operations.c#L399-L402

**Comment by Hussain1811** [comment]
Oh yes!
i missed this.

This seems to be an environment issue at my end.
Closing the issue.
