### ISSUE TITLE
pkcs11 missing ec_point in sign init when using an imported ec keypair

### ISSUE THREAD

**Issue by StevenCai-Gallagher** [OP-TEE/optee_os#5165]
Hi Everyone,

I am trying to import an OpenSSL generated EC keypair into the trust store, and then use the keypair to do sign/verify. 

After creating a public key object and a private key object, I get the "Missing EC_POINT attribute" error message when I am doing the c_signinit. It seems TEE_PopulateTransientObject requires public x/y values, so it will try to load the ec_point attribute from the private key object in load_tee_ec_key_attrs() when it tries to do signature initialization. But the ec_piont attribute can not be put from the template into the attributes, which attributes were used to create the private key object. It will be filtered, even though I add an ec_point attribute in the template for private key object creating. 

I wonder if I misunderstand something? If not, I don't know if we can add pkcs11_cka_ec_point in ec_private_key_opt_or_null[].

Thank you.

**Comment by vesajaaskelainen** [comment]
If one just looks at the code one could believe that following is incorrect:
https://github.com/OP-TEE/optee_os/blob/master/ta/pkcs11/src/processing_ec.c#L373-L381

Eg. it should not load public key values from private key as per PKCS#11 specs.

But this seems to be a bit more complex issue:
https://github.com/OP-TEE/optee_os/blob/master/ta/pkcs11/src/processing_ec.c#L533-L540

Gives indication that OP-TEE's internal functions require us to provide EC point.

Now we should not import them as it could be wrong -- but I suppose we should calculate EC points X & Y when we import the private key -- but that gets hairy as we have utilized TEE Internal Core API for that and now that is in mix of things.

We have the code of course for that:
https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/pk/ecc/ecc_make_key.c#L64-L67

But it is a bit far away... and crosses crypto api layer.

We do have `lib/libmbedtls` that we could perhaps link the TA with. We could perhaps utilize DER parser from there too.

Now need to ponder this a bit -- @etienne-lms / @ruchi393 any opinions how should we handle this?

**Comment by vesajaaskelainen** [comment]
I was thinking about this and is it overkill to get external math lib involved? It would feel better to use external math lib as then it would be maintained.

One option I was thinking that perhaps we could add in `processing_ec.c`'s curve list the other curve parameters so we could calculate with GP's TEE Arithmetic API math functions the public key out of provided private key and store that also in object.

This way we would match the spec and private key was anyway provided form untrusted side so I don't think that would be that bad compromise.

Only overhead we have is that we have extra curve information in the TA. But TA has plenty of code memory available. Then again also the extra mathlib in TA would not matter that much -- its just about the choice.

**Comment by etienne-lms** [comment]
As you mentioned, a TA can link to mbedtls. It can be used if needed and it maintained.
For sure, we prefer to use  GPD TEE APIs when possible for compliance and for portability of HW crypto assistance where applicable.

**Comment by StevenCai-Gallagher** [comment]
Hi @vesajaaskelainen @etienne-lms 

Just wondering if this issue will be fixed. Thank you.

**Comment by vesajaaskelainen** [comment]
@StevenCai-Gallagher as of issue I believe it should be fixed -- so lets keep the bug open.

As a general recommendation -- it is always better to generate the key pair in the device.

**Comment by Steven-Cai** [comment]
@vesajaaskelainen 
Thanks for your recommendation. Yeah. For the new keys, we will generate the key pair in the device. But we have to import some legacy keys as well for backward compatible.

**Comment by StevenCai-Gallagher** [comment]
@vesajaaskelainen 
Thanks for your recommendation. Yeah. For the new keys, we will generate the key pair in the device. But we have to import some legacy keys as well for backward compatible.

**Comment by vesajaaskelainen** [comment]
keep-alive

**Comment by jforissier** [comment]
@vesajaaskelainen @etienne-lms should this be tagged as a bug? (bugs do not become stale).

**Comment by etienne-lms** [comment]
+1 for bug

**Comment by etienne-lms** [comment]
Can close. Addressed in https://github.com/OP-TEE/optee_os/pull/6204.
