### ISSUE TITLE
Question: KVM based virtualization support

### ISSUE THREAD

**Issue by sohhas** [OP-TEE/optee_os#5170]
Hey folks!

Does OP-TEE currently supports KVM(+ QEMU) based virtualization or do you have plans to support it?
I can see the PR #4844 is related to Xen hypervisor, but it is not clear to me yet how to add support for KVM. Do we need KVM TEE mediator or could this be solved in some other way (e.g. device pass through or adding optee driver to qemu) ?

I would really appreciate your insight. Thanks!

**Comment by lorc** [comment]
Hi @sohhas,

OP-TEE API is hypervisor-independent. I implemented support in Xen, because we are using Xen in our projects.

I believe, that something very similar needs to be done in KVM as well. This means that yes, you need mediator which will translate requests from VM to OP-TEE.

**Comment by sohhas** [comment]
Thanks @lorc!

So if I understand correctly, the current infrastructure in OP-TEE core should already support KVM (provided there is a mediator)?

Also since Xen is a bit different compared to (KVM + QEMU) architecture, would it be possible to support virtual client APIs with a TEE device on qemu? By using shared memory mechanism or vsock, the TEE device would pass the context between the guest APIs and the host CAs. I am also trying to think of ways to avoid making changes to KVM.

**Comment by lorc** [comment]
> So if I understand correctly, the current infrastructure in OP-TEE core should already support KVM (provided there is a mediator)?

Yes. There is absolutely nothing Xen-specific in the OP-TEE code.

> I am also trying to think of ways to avoid making changes to KVM

My intention was to avoid any changes in the VM code, so Xen is doing all hard work. But in your case, yes, of course you can omit KVM from the equation. There are some caveats though:

1. Security. Your host will see all operations with OP-TEE. But host anyways can introspect the whole VM memory, so this is not a big problem. (In Xen setup, only Xen can access guest memory directly, and we are working towards very small, secure Dom0 based on Zephyr to ensure that Dom0 will don't do anything bad).

2. Performance. OP-TEE requires real physical addresses to access shared memory. I don't know if KVM allows you to get PA for VM memory. But I suppose, it does.  If there is no way to share VM memory to OP-TEE (remember, you need to lock buffers being shared), then you will need to bounce buffers back and forth.

3. New transport. Currently OP-TEE supports raw SMCI calls and FFA. If I got this right, both will not suit you (but @jenswi-linaro  can correct me there), so you will need to implement a new transport. vsock, or something similar, as you said.

4. Security. Again. As I said, OP-TEE can access all physical memory. You need to be very careful to ensure that VM can't trick OP-TEE to read-write memory that is not accessible to VM already.

**Comment by sohhas** [comment]
Hi @lorc 
Can you give pointer to the documentation or the latest source code for the hypervisor mediator?
I cannot find the changes in Xen upstream? Thanks!

**Comment by sohhas** [comment]
never mind, I think I found it under  /xen/arch/arm/tee
