### ISSUE TITLE
Renaming pers-obj with obj_id_len=0 results in panic

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#5171]
I have allocated a TA private new object ID buffer of length zero and later invoked `TEE_RenamePersistentObject()` with this buffer and size=0.
But, i end up in a panic.

On debugging, i found out that the panic is due to https://github.com/OP-TEE/optee_os/blob/master/core/mm/vm.c#L1257
The spec mentions the following though:
_newObjectID, newObjectIDLen: A buffer containing the new object identifier. The identifier
contains arbitrary bytes, including the zero byte. The identifier length SHALL be less than or equal to
TEE_OBJECT_ID_MAX_LEN and can be zero. The buffer containing the new object identifier cannot
reside in shared memory._

So, if i am not wrong, i should be expecting a success for my use-case?

Environment: 3.13 OPTEE-QEMU

**Comment by jforissier** [comment]
Hello @Hussain1811,

Your test case seems to be valid as per the spec but honestly I find it weird to allow the creation of anonymous persistent objects. This makes little sense in practice. And to make matters worse, the same text (_"The identifier length [...] can be zero"_) is not used in the description of `TEE_CreatePersistentObject()` and `TEE_OpenPersistentObject()`. So, should a zero-size name be allowed for all three functions or only for `TEE_RenamePersistentObject()`?

In any case, if we decide to "fix" this we need to be very careful about the possible side-effects. Do you have a patch?

**Comment by Hussain1811** [comment]
Hello @jforissier,

Any particular reason why we call them "Anonymous" persistent objects?
If i'm not wrong, the object ID is a known value (to be precise, it's a buffer filled with all zeroes)

**Comment by jforissier** [comment]
We're talking about `newObjectIDLen == 0` which means empty buffer, hence no name. That is why I am calling them "anonymous". The bytes in `objectID` do not matter when length is zero.

**Comment by jenswi-linaro** [comment]
An empty name is still a name, I mean it's not supposed to be possible to have more than one object with an empty name.

**Comment by Hussain1811** [comment]
Got it @jforissier and @jenswi-linaro 
From my perspective, we could disallow anonymous persistent objects for all three.

Your opinion?

**Comment by jforissier** [comment]
> An empty name is still a name, I mean it's not supposed to be possible to have more than one object with an empty name.

True, and we can certainly implement this semantic.

**Comment by Hussain1811** [comment]
Got it @jforissier @jenswi-linaro 
I don't have a patch currently though.

Need to think of this.

**Comment by Hussain1811** [comment]
Well, i tried. I guess i am missing some intricate details w.r.t the code and hence not able to provide a patch for this.
By the way, can this issue be tagged as a bug?

**Comment by manishkanal1** [comment]
@jforissier I tend to agree with @Hussain1811 that this should be tagged as a bug. We do not have enough expertise on the OPTEE_OS to provide a patch for this.

**Comment by jforissier** [comment]
@manishkanal1 @Hussain1811 I have added the bug label. I'll take a closer look at it when I have time.

**Comment by jforissier** [comment]
Please see https://github.com/OP-TEE/optee_os/pull/5188. @Hussain1811 feel free to give a `Reported-by: Your name <your email address>` if you would like to be credited for the discovery :)
