### ISSUE TITLE
Adding asynchronous notification interrupt to Device Tree may be incomplete

### ISSUE THREAD

**Issue by rdelien** [OP-TEE/optee_os#5176]
The - very welcome - [addition](https://github.com/OP-TEE/optee_os/commit/c2d449482de098f1c894b94f338440e5a327813d) of a notification interrupt for Op-Tee events to Linux Userland seems to offer two options:
1. The interrupt properties are added to the target's Device Tree by the developer
2. If the interrupt properties are not found in the Device Tree, Op-Tee patches the Device tree by adding the properties itself.

This PR applies to the second option.

When Op-Tee patches the Device tree in [.../core/arch/arm/kernel/boot.c:add_optee_dt_node()](https://github.com/OP-TEE/optee_os/commit/c2d449482de098f1c894b94f338440e5a327813d#diff-f0f9f95ba43bbb92d7031302e719183f6dba05bf9f86fb517d4b191d86a6f09eR732), it adds an `interrupts` property, but does not add an `interrupt-parent` property.
At least on the i.MX6(ul), a missing interrupt-parent makes the interrupt driver revert to trying to hook a GPIO interrupt, and fail with an -ENXIO in the best case, or succeed in hooking an inappropriate interrupt in the worst case.

Even though I prefer the very elegant feature to have Op-Tee to patch its interrupt into the Device Tree, and hence having a single point of definition for these properties, I don't think it will be easy to add an `interrupt-parent` property, because it is a numbered reference, and looking up that number can be hard to do.

**Comment by jenswi-linaro** [comment]
> When Op-Tee patches the Device tree in [.../core/arch/arm/kernel/boot.c:add_optee_dt_node()](https://github.com/OP-TEE/optee_os/commit/c2d449482de098f1c894b94f338440e5a327813d#diff-f0f9f95ba43bbb92d7031302e719183f6dba05bf9f86fb517d4b191d86a6f09eR732), it adds an `interrupts` property, but does not add an `interrupt-parent` property.

QEMU is the primary target for this.
