### ISSUE TITLE
Problem with the ARM Juno booting

### ISSUE THREAD

**Issue by aminusamine** [OP-TEE/optee_os#519]
Hello, 

i want to use an ARM Juno i have to install OPTEE. Unfortunately, when i plug a USB 3.0 usb stick with ext3/ext4 format i have the following traces : 

ext4 : 

[    4.004845]  sda: sda1
[    4.009631] sd 0:0:0:0: [sda] Attached SCSI removable disk
[    4.072965] EXT3-fs (sda1): error: couldn't mount because of unsupported optional features (240)
[    4.084337] EXT2-fs (sda1): error: couldn't mount because of unsupported optional features (240)
[    4.110636] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
[    4.118262] VFS: Mounted root (ext4 filesystem) readonly on device 8:1.
[    4.126529] devtmpfs: error mounting -2

ext3 : 

[    3.555042]  sda: sda1
[    3.561781] sd 0:0:0:0: [sda] Attached SCSI disk
[    3.655607] kjournald starting.  Commit interval 5 seconds
[    3.655935] EXT3-fs (sda1): mounted filesystem with writeback data mode
[    3.655965] VFS: Mounted root (ext3 filesystem) readonly on device 8:1.
[    3.657694] devtmpfs: error mounting -2

Can anyone help me to boot up my ARM Juno card please. 
Thank you very much

PS : I took two different usb sticks. 1 transend and 1 sandisk with the same problems

**Comment by jenswi-linaro** [comment]
Hi,

The problem seems to be related to the USB stick. I've been using a SanDisk Cruzer Blade 32GB without problems. I've seen USB sticks that doesn't seem to work with Juno, fortunately I tried with a working USB stick first.

Regards,
Jens

**Comment by aminusamine** [comment]
Thanks for the answer.

Just to be more precise, you format you usb stick into ext3 or ext4 format that's all ? Or you do any other operation on it ?

**Comment by jenswi-linaro** [comment]
I can't remember, I don't think it matters. I've been using one of the Linaro disk images.

Your log is a bit different than the one I got with a faulty USB stick, I don't think it got far enough to even find the partition.

**Comment by aminusamine** [comment]
Sorry but i didn't understand what you answered. 

what do you put into the usb stick ? A linux Image or you put it with no file inside ?

**Comment by jenswi-linaro** [comment]
I think I did dd (see https://community.arm.com/docs/DOC-10804) something like an uncompressed `juno.img.bz2` from https://releases.linaro.org/android/reference-lcr/juno/latest/
But it's a long time ago so it's probably different now.

**Comment by aminusamine** [comment]
Last question please, is the usb stick you use a 2.0 or 3.0 because i saw on the installation tutorial that there is some problems with 2.0 USB sticks ?

**Comment by jenswi-linaro** [comment]
My USB stick is 3.0.

**Comment by jbech-optee-adm** [comment]
Question has been answered, please re-open in case you have additional questions.
