### ISSUE TITLE
Using initialized trans-obj as an attr in TEE_CreatePersistentObject() results in panic

### ISSUE THREAD

**Issue by Sadiq1811** [OP-TEE/optee_os#5190]
I am using an initialized trans-obj (`TEE_AllocateTransientObject` + `TEE_PopulateTransientObject`) as an attribute parameter for `TEE_CreatePersistentObject()`. The attribute is basically an AES 128bit key.
But i end up in a panic with `TEE_ERROR_BAD_STATE` error code.

Environment: OPTEE version 3.13 on QEMU

Any further information about this?
Is there such a test in the GP test-suite? I don't seem to find one in the traditional XTEST.

**Comment by jforissier** [comment]
Hello @Sadiq1811,

There is a similar test in `xtest 6013` here: https://github.com/OP-TEE/optee_test/blob/3.13.0/host/xtest/regression_6000.c#L1422-L1444, see the TA code here: https://github.com/OP-TEE/optee_test/blob/3.13.0/ta/storage/storage.c#L431-L453. `TEE_PopulateTransientObject()` is not used though ; instead `TEE_GetObjectInfo1()` is used on the key handle.

Can you try this test please? I did not find any other test for `TEE_CreatePersistentObject()` with attributes in `xtest` and neither in the GP test suite (`TEE_Initial_Configuration-Test_Suite_v2_0_0_2-2017_06_09.7z`).

**Comment by Sadiq1811** [comment]
This is what is mentioned in the spec:
_A transient object becomes initialized when its attributes are populated._

_The attributes of the newly created persistent object are taken from attributes, which can be another persistent object or an initialized transient object._

So, i would assume that even with a `TEE_AllocateTransientObject + TEE_PopulateTransientObject` combination, the creation of a persistent key shall work.

**Comment by jforissier** [comment]
- In the above code (xtest 6013), `TEE_GetObjectInfo1()` is used to check that the object attributes are the same in the transient object and the persistent object. It doesn't help create the persistent object.
- You mentioned transferring object handles from TA1 to TA2 via CA. You cannot do this! The GP spec mentions in 2.4 Opaque Handles: "A handle is only valid in the context of the TA instance that creates it". In other words, object handles are like Linux file descriptors if you wish.

**Comment by Sadiq1811** [comment]
> * You mentioned transferring object handles from TA1 to TA2 via CA. You cannot do this! The GP spec mentions in 2.4 Opaque Handles: "A handle is only valid in the context of the TA instance that creates it". In other words, object handles are like Linux file descriptors if you wish.

is it possible to keep the common stuff in a SHILIB TA (aka `SHLIBUUID`)?

**Comment by jforissier** [comment]
> is it possible to keep the common stuff in a SHILIB TA (aka `SHLIBUUID`)?

You mean common code? Yes, of course. But note, it doesn't change anything wrt. object handles. They are still valid only within the instance of the TA that creates or opens them. Whether or not this TA uses shared libraries it doesn't matter.

**Comment by Sadiq1811** [comment]
Thanks for the clarifications.
Shall be closing the issue.
