### ISSUE TITLE
ftrace does not work because mobj_get_cattr function fails

### ISSUE THREAD

**Issue by zhanlej** [OP-TEE/optee_os#5198]
I found that the performance is very poor when using the RSA interface of OPTEE CORE, so I want to locate where the performance bottleneck is. I tried to open the ftrace function of OPTEE by referring to the [ftrace documentation](https://optee.readthedocs.io/en/latest/debug/ftrace.html), but I encountered some problems, which are described as follows:

I am using a chip from TI, and TI provides ti-optee-os modified based on optee_os. Although there are some differences between the two code bases, the core logic of OPTEE should not be modified, because the bl32 compiled by me using github's optee_os can also run normally.

Hardware version: TI TDA4
OPTEE OS version: [ti-optee-os tag ti2020.00](https://git.ti.com/cgit/optee/ti-optee-os/tag/?h=ti2020.00) (similar to version 3.8.0)
OPTEE CLIENT version: [ti-optee-client tag ti2020.00](https://git.ti.com/cgit/optee/ti-optee-client/tag/?h=ti2020.00)
OPTEE OS compilation parameters:

```
O=out/arm 
CFG_ARM64_core=y 
CROSS_COMPILE="/usr/bin/ccache /opt/gw-gcc/gcc/bin/aarch64-none-linux-gnu-" 
CROSS_COMPILE_core="/usr/bin/ccache /opt/gw-gcc/gcc/bin/aarch64-none-linux-gnu-" 
CROSS_COMPILE_ta_arm64="/usr/bin/ccache /opt/gw-gcc/gcc/bin/aarch64-none-linux-gnu-" 
CROSS_COMPILE_ta_arm32="/usr/bin/ccache /home/zlj/WorkSpace/icode/baidu/adu/tee_security/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" 
CFG_TEE_CORE_LOG_LEVEL=3 
CFG_TEE_TA_LOG_LEVEL=1 
DEBUG=1 
ta-targets=ta_arm64 
CFG_TEE_BENCHMARK=n 
CFG_TEE_TA_MALLOC_DEBUG=y 
CFG_FTRACE_SUPPORT=y 
CFG_ULIBS_MCOUNT=y 
CFG_TA_MCOUNT=y 
CFG_FTRACE_BUF_SIZE=100000  
PLATFORM=k3-j721e 
CFG_ARM64_core=y 
```

After compiling and burning to the device using the above compilation parameters, I did not find any ftrace related files in the /tmp/ directory of REE.

At first I thought it was the problem of ti-optee-client, but by looking at the code I found that **CFG_FTRACE_SUPPORT ?= y** in **config.mk** is enabled by default.

So I try to add some printing in ti-optee-os to find the problem, the modification record can be viewed: https://github.com/zhanlej/ti-optee-os/commit/6a455cb1e46a450a37671db66b210af9e463c0a2

The final location to the log is as follows:

```
D/TC:? 0 tee_ta_init_pseudo_ta_session:284 Lookup pseudo TA 8ffff200-2450-11e4-abe2-0002a5d5c51b
E/TC:? 0 set_ta_ctx_ops:643 
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_phys_get_cattr:78 
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_phys_get_cattr:78 
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_with_fobj_get_cattr:587 
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_with_fobj_get_cattr:587 
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_with_fobj_get_cattr:587 
D/TC:? 0 load_ldelf:725 ldelf load address 0x40006000
D/LD:  ldelf:134 Loading TA 8ffff200-2450-11e4-abe2-0002a5d5c51b
D/TC:? 0 tee_ta_init_pseudo_ta_session:284 Lookup pseudo TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 tee_ta_init_pseudo_ta_session:297 Open system.pta
D/TC:? 0 tee_ta_init_pseudo_ta_session:311 system.pta : 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_with_fobj_get_cattr:587 
D/TC:? 0 system_open_ta_binary:249 Lookup user TA ELF 8ffff200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:? 0 system_open_ta_binary:253 res=0xffff0008
D/TC:? 0 system_open_ta_binary:249 Lookup user TA ELF 8ffff200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:? 0 system_open_ta_binary:253 res=0x0
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_with_fobj_get_cattr:587 
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_with_fobj_get_cattr:587 
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_with_fobj_get_cattr:587 
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_with_fobj_get_cattr:587 
E/LD:  ldelf:163 
E/LD:  ldelf:165 
D/LD:  ldelf:171 ELF (8ffff200-2450-11e4-abe2-0002a5d5c51b) at 0x40030000
D/TC:? 0 tee_ta_close_session:512 csess 0x9e8a7170 id 1
D/TC:? 0 tee_ta_close_session:532 Destroy session
E/TC:? 0 tee_ta_close_session:544 
E/TC:? 0 destroy_session:281 
E/TC:? 0 destroy_session:283 
E/TC:? 0 destroy_session:286 
E/TC:? 0 init_with_ldelf:258 CFG_FTRACE_SUPPORT
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_phys_get_cattr:78 
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_phys_get_cattr:78 
D/TC:? 0 tee_ta_init_session_with_context:590 Re-open TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 tee_ta_init_session_with_context:590 Re-open TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_with_fobj_get_cattr:587 
D/TC:? 0 tee_ta_close_session:512 csess 0x9e8a63a0 id 1
D/TC:? 0 tee_ta_close_session:532 Destroy session
E/TC:? 0 tee_ta_close_session:544 
E/TC:? 0 destroy_session:281 
E/TC:? 0 destroy_session:283 
E/TC:? 0 destroy_session:286 
E/TC:? 0 entry_close_session:352 
D/TC:? 0 tee_ta_close_session:512 csess 0x9e8a7970 id 1
D/TC:? 0 tee_ta_close_session:532 Destroy session
E/TC:? 0 tee_ta_close_session:544 
E/TC:? 0 destroy_session:281 
E/TC:? 0 destroy_session:283 
E/TC:? 0 destroy_session:286 
E/TC:? 0 destroy_session:289 
E/TC:? 0 destroy_session:292 
E/TC:? 0 destroy_session:295 
E/TC:? 0 user_ta_dump_ftrace:496 
E/TC:? 0 user_ta_dump_ftrace:508 
E/TC:? 0 user_ta_dump_ftrace:515 blen:1372, 0x55c
E/TC:? 0 user_ta_dump_ftrace:521 pl_sz:4096, 0x1000
E/TC:? 0 user_ta_dump_ftrace:523 
E/TC:? 0 user_ta_dump_ftrace:530 
E/TC:? 0 user_ta_dump_ftrace:535 mobj->size:65536
E/TC:? 0 mobj_get_cattr:66 
E/TC:? 0 mobj_get_cattr:69 
E/TC:? 0 vm_map_pad:255 res:0xffff0000
E/TC:? 0 user_ta_dump_ftrace:539 res:0xffff0000
```

Through the log **"E/TC:? 0 mobj_get_cattr:69"** and [code](https://github.com/zhanlej/ti-optee-os/commit/6a455cb1e46a450a37671db66b210af9e463c0a2#diff-02e9ac538787ee02a9c08eef060ac1dccb1092911ea232088276d1f4c180cb2aR69), it can be located that **mobj->ops->get_cattr** is not found in the **mobj_get_cattr** function. Since I don't know enough about the core OPTEE code, this is the problem I can find.

```c
static inline TEE_Result mobj_get_cattr(struct mobj *mobj, uint32_t *cattr)
{
	EMSG("");    // line 66
	if (mobj && mobj->ops && mobj->ops->get_cattr)
		return mobj->ops->get_cattr(mobj, cattr);
	EMSG("");    // line 69
	return TEE_ERROR_GENERIC;
}
```

In addition, I use the same compilation parameters based on **optee_os 3.16.0**, and add some debug log: https://github.com/zhanlej/optee_os/commit/ed5e2e51726f47c38f64ffb6f1f87a7eb4bfd8a5, the compiled bl32 phenomenon is the same, the log is as follows:

```
D/TC:? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA 8ffff200-2450-11e4-abe2-0002a5d5c51b
E/TC:? 0 mobj_get_cattr:80 
E/TC:? 0 mobj_get_cattr:80 
E/TC:? 0 mobj_get_cattr:80 
E/TC:? 0 mobj_get_cattr:80 
E/TC:? 0 mobj_get_cattr:80 
D/TC:? 0 ldelf_load_ldelf:95 ldelf load address 0x40006000
D/LD:  ldelf:134 Loading TS 8ffff200-2450-11e4-abe2-0002a5d5c51b
E/TC:? 0 mobj_get_cattr:80 
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF 8ffff200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF 8ffff200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0
E/TC:? 0 mobj_get_cattr:80 
E/TC:? 0 mobj_get_cattr:80 
E/TC:? 0 mobj_get_cattr:80 
E/TC:? 0 mobj_get_cattr:80 
D/LD:  ldelf:168 ELF (8ffff200-2450-11e4-abe2-0002a5d5c51b) at 0x4008f000
E/TC:? 0 mobj_get_cattr:80 
E/TC:? 0 mobj_get_cattr:80 
D/TC:? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 tee_ta_init_pseudo_ta_session:309 Open system.pta
D/TC:? 0 tee_ta_init_pseudo_ta_session:326 system.pta : 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
D/TC:? 0 tee_ta_init_session_with_context:607 Re-open TA 3a2f8978-5dc0-11e8-9c2d-fa7ae01bbebc
E/TC:? 0 mobj_get_cattr:80 
D/TC:? 0 tee_ta_close_session:512 csess 0x9e8a84d0 id 1
D/TC:? 0 tee_ta_close_session:531 Destroy session
D/TC:? 0 tee_ta_close_session:512 csess 0x9e8a9910 id 1
D/TC:? 0 tee_ta_close_session:531 Destroy session
E/TC:? 0 mobj_get_cattr:80 
E/TC:? 0 mobj_get_cattr:83 
E/TC:? 0 vm_map_pad:281 res:0xffff0000
```

Please help me explain the reason for this phenomenon.

**Comment by jforissier** [comment]
Hello @zhanlej,

I tried running `xtest` with mostly the same configuration flags as yours, on QEMUv8 (https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8), and it worked as expected, so I could not investigate more. 
```
$ make -j10 CFG_TEE_CORE_LOG_LEVEL=3  CFG_TEE_TA_LOG_LEVEL=1 ta-targets=ta_arm64 CFG_TEE_TA_MALLOC_DEBUG=y CFG_FTRACE_SUPPORT=y CFG_ULIBS_MCOUNT=y CFG_TA_MCOUNT=y CFG_FTRACE_BUF_SIZE=100000 run

$ xtest 4002
[...]
$ ls -l /tmp
total 140
-rw-r--r--    1 tee      tee          99369 Mar  4 10:31 ftrace-cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.out
-rw-r--r--    1 root     root         28756 Mar  4 10:31 messages
-rw-r--r--    1 root     root            27 Mar  4 10:31 resolv.conf
-rw-r--r--    1 root     root           219 Mar  4 10:31 udhcpc.log
$
```

It looks like the issue is happening when the TA tries to send the ftrace buffer to Normal World (tee-supplicant). Maybe try reducing `CFG_FTRACE_BUF_SIZE`. There is probably a bug somewhere.

**Comment by b49020** [comment]
@zhanlej 

> Maybe try reducing CFG_FTRACE_BUF_SIZE. There is probably a bug somewhere.

It may well be due to platform specific shared memory constraints. Have you enabled dynamic shared memory or just relying on fixed reserved shared memory approach?

**Comment by zhanlej** [comment]
@jforissier @b49020 thank you for your reply.

> I tried running xtest with mostly the same configuration flags as yours, on QEMUv8 (https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8), and it worked as expected, so I could not investigate more.

I use version 3.16.0 of optee_os with no problems on QEMU, but it doesn't work properly on my hardware.

> It looks like the issue is happening when the TA tries to send the ftrace buffer to Normal World (tee-supplicant). Maybe try reducing CFG_FTRACE_BUF_SIZE. There is probably a bug somewhere.

I set CFG_FTRACE_BUF_SIZE=4096 the result has no change

> It may well be due to platform specific shared memory constraints. Have you enabled dynamic shared memory or just relying on fixed reserved shared memory approach?

Sorry I don't know where to set the shared memory configuration you said, please tell me the location

**Comment by b49020** [comment]
@zhanlej After looking more closely at your logs, it looks like you are hitting this problem with static shared memory approach. Following is an untested patch, give it a try if it solves your problem:

```
diff --git a/core/mm/mobj.c b/core/mm/mobj.c
index d91ff4b8..024c10c1 100644
--- a/core/mm/mobj.c
+++ b/core/mm/mobj.c
@@ -397,6 +397,17 @@ static bool mobj_shm_matches(struct mobj *mobj __unused, enum buf_is_attr attr)
        return attr == CORE_MEM_NSEC_SHM || attr == CORE_MEM_NON_SEC;
 }
 
+static TEE_Result mobj_shm_get_cattr(struct mobj *mobj, uint32_t *cattr)
+{
+       if (!cattr)
+               return TEE_ERROR_GENERIC;
+
+       /* All shm objects are mapped as normal cached memory */
+       *cattr = TEE_MATTR_CACHE_CACHED;
+
+       return TEE_SUCCESS;
+}
+
 static void mobj_shm_free(struct mobj *mobj)
 {
        struct mobj_shm *m = to_mobj_shm(mobj);
@@ -418,6 +429,7 @@ __weak __relrodata_unpaged("mobj_shm_ops") = {
        .get_va = mobj_shm_get_va,
        .get_pa = mobj_shm_get_pa,
        .get_phys_offs = mobj_shm_get_phys_offs,
+       .get_cattr = mobj_shm_get_cattr,
        .matches = mobj_shm_matches,
        .free = mobj_shm_free,
        .get_cookie = mobj_shm_get_cookie,

```

**Comment by jenswi-linaro** [comment]
You could try increasing `STACK_TMP_SIZE`.

**Comment by b49020** [comment]
@zhanlej 

> The detailed modifications are as follows:

Glad that it worked for you with these modifications. Feel free to create an OP-TEE PR with following:

`Suggested-by: Sumit Garg <sumit.garg@linaro.org>`

> Why doesn't this problem exist on QEMU?

Qemu is running with dynamic shared memory enabled, you would see below kernel message on Qemu but not on your platform:

`[    2.614007] optee: dynamic shared memory is enabled`

So if you need to enable dynamic shared memory on your platform as well, you need to enable it as described [here](https://github.com/OP-TEE/optee_os/blob/master/mk/config.mk#L589) along with registering non-sec DRAM spaces with OP-TEE as an example [here](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-vexpress/main.c#L39).

> But the final generated ftrace.out only shows the last stack, it seems that a lot of content is ignored

It looks like there is gap in understanding ftrace config options. For more details refer [here](https://optee.readthedocs.io/en/latest/debug/ftrace.html#usage) but summary is:

OP-TEE OS ftrace options:
```
CFG_FTRACE_SUPPORT=y
CFG_ULIBS_MCOUNT=y
CFG_SYSCALL_FTRACE=y
```

TA ftrace options:
```
CFG_TA_MCOUNT=y
CFG_FTRACE_BUF_SIZE=100000
```

**Comment by jforissier** [comment]
>> Why doesn't this problem exist on QEMU?

> Qemu is running with dynamic shared memory enabled,

Indeed, I can confirm the same issue is observed if we set `CFG_CORE_DYN_SHM=n` on QEMU so this case definitely needs fixing.

**Comment by zhanlej** [comment]
> You could try increasing `STACK_TMP_SIZE`.

@jenswi-linaro Thank you for your reply, but OPTEE still crashes after modifying **STACK_TMP_SIZE=16384**. Do you have any other suggestions?

@b49020 

> Feel free to create an OP-TEE PR with following: `Suggested-by: Sumit Garg <sumit.garg@linaro.org>`

ok i will create a PR

> So if you need to enable dynamic shared memory on your platform as well, you need to enable it as described here along with registering non-sec DRAM spaces with OP-TEE as an example here.

I'm lacking knowledge about dynamic shared memory, so I don't really understand the meaning of these configurations right now, it may be improved in the future.

> It looks like there is gap in understanding ftrace config options. For more details refer here but summary is:

I understand what these config options mean. My real problem is when I set CFG_ULIBS_MCOUNT=y there is too little information in ftrace-*.out . I would like to see more complete optee os call stack information. Initially I suspected it was because the value of CFG_FTRACE_BUF_SIZE was too small, causing insufficient memory to log the information. After I increased the value of CFG_FTRACE_BUF_SIZE the contents of the ftrace-*.out records did not increase.

Is there a way to increase the info of the optee os call stack in ftrace-*.out

**Comment by jforissier** [comment]
> My real problem is when I set CFG_ULIBS_MCOUNT=y there is too little information in ftrace-.out .

If some function calls seem to be missing, reducing the optimization level may help. Try setting `CFG_CC_OPT_LEVEL=0` when building OP-TEE (this will apply to the TA libraries) and `CFLAGS_ta_arm32=-O0 -pg` (will be used when compiling TA code).

> After I increased the value of CFG_FTRACE_BUF_SIZE the contents of the ftrace-.out records did not increase.

Try cleaning the TA, in particular remove the file `out/ta.lds` which might not be generated again when CFG_FTRACE_BUF_SIZE is changed (if it contains `2048 : 0;` near the end then it has kept the default value).
