### ISSUE TITLE
OP-TEE on Allwinner a80 (CubieBoard 4)

### ISSUE THREAD

**Issue by KurSh** [OP-TEE/optee_os#520]
Hello,
 We are using CubieBoard 4 based on A80,  and we have ported op-tee linux driver on the lichee kernel (based on 3.4) and prepared android image using manual form optee_os.   But it seems not enough a  copy tee.bin to the "lichee/tools/pack/chips/sun9iw1p1/bin"...  as proposed in the doc.
After the porting drivers, we try to build supplicant and hello world app,  insmod for drivers seems fine:

insmod /system/vendor/modules/optee.ko
[ 1902.968878] TEE Core Framework initialization (ver 1:0.1)

insmod /system/vendor/modules/optee_armtz.ko
[ 1915.583721] TEE armv7 Driver initialization
[ 1915.591387] tz_tee_probe: name="armv7sec", id=0, pdev_name="armv7sec.0"
[ 1915.598921] TEE core: Alloc the misc device "opteearmtz00" (id=0)
[ 1915.609068] TEE Core: Register the misc device "opteearmtz00" (id=0,minor=39)

Then we starting supplicant, board going to infinite loop. Please advice us how we can make sure that optee_os (tee.bin) loaded properly (or tried to loaded, but for example we need some additional work by porting on our board).

---
Best regards,
Shamil

**Comment by jbech-linaro** [comment]
It isn't that easy that you simply forgot the "&" after tee-supplicant? I.e, Instead of:
`tee-supplicant`

you should type
`tee-supplicant &`

(tee-supplicant is a never ending process just sitting in a main loop waiting for messages).

**Comment by KurSh** [comment]
Our problem the same as described in the  https://github.com/OP-TEE/optee_linuxdriver/issues/32 ticket.  It may be because we use a different version of SDK than described  in the op-tee docs and tee.bin not present on board. May you upload somewhere used  Allwiner a80 SDK, or maybe some patches for it?

**Comment by KurSh** [comment]
Hello all. We try to load tee.bin manually  from u-boot console and have following error:
fatload mmc 2:1 0x9c000000 tee.bin
go 0x9c000000  
## Starting application at 0x9C000000 ...
ERR TEE-CORE:map_memarea:618: va 0x800000 conflicts with user ta address!

**Comment by vchong** [comment]
Aren't you supposed to load tee.bin before u-boot?

**Comment by KurSh** [comment]
May be, we try to load the same way as a Freescale MX6UL EVK board.  For loading before u-boot, we need to investigate how to A80 boot0 loader is worked. We tied load tee.bin insted u-boot, but have message about "ERROR! NOT find the head of uboot", because boot0 code check u-boot header..

**Comment by vchong** [comment]
There's now a maintainer for the a80 platform. Perhaps he can help. Also please share the solution when there's one. Thanks.
https://github.com/OP-TEE/optee_os/blob/master/MAINTAINERS.md#maintainers-in-the-op-tee-project

**Comment by jbech-linaro** [comment]
@KurSh we have been talking to Allwinner and the answer was unfortunately that the devices sold to the general public are locked down on the secure side and therefore you cannot use those for secure side development. We've added a comment clarifying this in the README.md now:
https://github.com/OP-TEE/optee_os#45-allwinner-a80

Sorry for the inconvenience we might have caused by not having accurate information in our documentation.

**Comment by KurSh** [comment]
@vchong  @jbech-linaro 
Thank for help, we will try contact with Allwinner.
