### ISSUE TITLE
Hardcoded path causes TA errors if building OP-TEE with Yocto

### ISSUE THREAD

**Issue by pm1992** [OP-TEE/optee_os#5200]
https://github.com/OP-TEE/optee_os/blob/839dadc26ee3188ae5127981c0651126058faa75/ta/ta.mk#L176

Based on OP-TEE's documentation:

_optee_os comes with a default private key in its source to facilitate easy development, testing, debugging and QA. Never deploy an optee_os binary with this key in production. **Instead replace this key as soon as possible with a public key and keep the private part of the key offline**, preferably on an HSM._

Normally this is done by swapping keys/default_ta.pem in the optee-os source with a new one

However when building OP-TEE with Yocto, The optee-os source directory isn't readily accessible. The source directory gets deleted often if recipes are cleaned. So its not practical to keep copying over a new default_ta.pem for rebuilds.

There's a variable called $(TA_SIGN_KEY) which contains the path to the default_ta.pem file. The default value is ` $(TA_SIGN_KEY) = keys/default_ta.pem`

With Yocto, you can use EXTRA_OEMAKE line to override TA_SIGN_KEY with a new path and default_ta.pem file. 

`EXTRA_OEMAKE += "TA_SIGN_KEY=/new_key_path/default_ta.pem"`

The problem is while other .mk files in the optee-os source reference the new $(TA_SIGN_KEY), the variable here is still hardcoded to keys/default_ta.pem in optee-os' source

So Yocto will build OP-TEE and the image fine. But upon start-up, The TA's return **E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff000f”.** probably because the public and private keys become mismatched.

The solution for me was to patch this line to `ta-keys = $(TA_SIGN_KEY)`. This solves all the errors.

**Comment by jforissier** [comment]
Hi @pm1992,

Thanks for the detailed explanation. I think you're right, this line `ta-keys = keys/default_ta.pem` should be `ta-keys = $(TA_SIGN_KEY)`. In addition I noticed that `TA_SIGN_KEY` is uselessly set in `mk/lib.mk` so this should be cleaned up too. I will open a PR.

**Comment by jforissier** [comment]
Thinking a bit more about it... do we really want to export the `$(TA_SIGN_KEY)` file to the TA SDK? (the file in `ta-keys` is copied). I would expect things to work without this change provided that `TA_SIGN_KEY` is set both during optee_os build and TA build. Could you please check which key is used during (1) optee_os build and (2) TA build?
