### ISSUE TITLE
Can I add optee patch to old kernel version?

### ISSUE THREAD

**Issue by thangnt11** [OP-TEE/optee_os#5202]
I need to add optee-rng driver to kernel version 4.4.3. There are some relate patch (add TEE bus device enumeration support, add bus driver framework for TEE based devices), i added them and build success but there is run error "Device enumeration pseudo TA not found" when open session on __optee_enumerate_devices function (https://github.com/torvalds/linux/blob/master/drivers/tee/optee/device.c).
I suspect that patch is only working on new kernel version or i need change something on kernel driver?

**Comment by jforissier** [comment]
Hi @thangnt11,

"Device enumeration pseudo TA not found" suggests that something is missing on the OP-TEE side, namely `CFG_DEVICE_ENUM_PTA=y`. Which version of OP-TEE are you using?

**Comment by thangnt11** [comment]
> Hi @thangnt11,
> 
> "Device enumeration pseudo TA not found" suggests that something is missing on the OP-TEE side, namely `CFG_DEVICE_ENUM_PTA=y`. Which version of OP-TEE are you using?

Thank you for your suggestion. OP-TEE version is too old and it don't have more patch relate to Pseudo TA. I'm trying to add patch for checking.

**Comment by thangnt11** [comment]
I tried to apply some patch below for Pseudo TA:
synquacer: Add DeveloperBox platform support 
https://github.com/renesas-rcar/optee_os/commit/901acff441bf4513f4eb70ee9bfb49536d42969d
synquacer: Set default number of threads to 8
https://github.com/renesas-rcar/optee_os/commit/74a41cfac8c066718b8d36f3de448d2c23180ef2
synquacer: Enable secure timer interrupt framework 
https://github.com/renesas-rcar/optee_os/commit/5b60351fd02a7b17ccff8c897154491258891ffb
synquacer: Add RNG pseudo TA 
https://github.com/renesas-rcar/optee_os/commit/a5d528c7e54fd7726230483bd4cd5c4786d7703f
synquacer: rng-pta: Add rng info invoke command
https://github.com/renesas-rcar/optee_os/commit/6e0800cfcd590d55182c93c764398ce97375e7bf
synquacer: Enable rng-pta as kernel device
https://github.com/renesas-rcar/optee_os/commit/bbdbec2ecfd0251c54c48eedb73f8585035990f8
core: pta: Add device pseudo TA
https://github.com/renesas-rcar/optee_os/commit/0b611081804ad802343983018731d41aecd8240b

However, error happen:
[    0.884848] [OP-TEE][17.005000][1]D/TEE-CORE:  tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA 7011a688-ddde-4053-a5a9-7b3c4ddf13b8
[    0.884880] [OP-TEE][17.005000][1]D/TEE-CORE:  tee_ta_init_user_ta_session:632 Lookup user TA 7011a688-ddde-4053-a5a9-7b3c4ddf13b8 (Secure Storage TA)
[    0.884945] [OP-TEE][17.005000][1]D/TEE-CORE:  tee_ta_init_user_ta_session:637 res=0xffff000c
[    0.884989] optee: optee_enumerate_devices  Device enumeration pseudo TA not found
[    0.884992] [OP-TEE][17.005000][1]D/TEE-CORE:  tee_ta_open_session:564 init session failed 0xffff000c

**Comment by thangnt11** [comment]
Dear jforissier,
Could you please help me for answer the below question:
What happen when kernel driver call to tee_client_open_session()?
What can lead to TEEC_ERROR_OUT_OF_MEMORY error?
Thank you

**Comment by thangnt11** [comment]
I would like share optee-os verion.
It is OP-TEE - version 3.1.0

**Comment by jforissier** [comment]
> However, error happen:
> [ 0.884848] [OP-TEE][17.005000][1]D/TEE-CORE: tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA 7011a688-ddde-4053-a5a9-7b3c4ddf13b8

Here the "device enumeration" PTA should be found since if you added it properly (commit "core: pta: Add device pseudo TA")...

> [ 0.884880] [OP-TEE][17.005000][1]D/TEE-CORE: tee_ta_init_user_ta_session:632 Lookup user TA 7011a688-ddde-4053-a5a9-7b3c4ddf13b8 (Secure Storage TA)

...and therefore this line should not appear.

> [ 0.884945] [OP-TEE][17.005000][1]D/TEE-CORE: tee_ta_init_user_ta_session:637 res=0xffff000c

`TEEC_ERROR_OUT_OF_MEMORY` usually means... "out of memory" ;-) In this context, I think it is not enough heap memory in the TEE core. You can try to increase `CFG_CORE_HEAP_SIZE` (at the expense of reducing the TA memory), but I recommend focusing on why the pseudo TA lookup failed first. 

>  What happen when kernel driver call to tee_client_open_session()?

Secure World is entered, OP-TEE OS tries to load the TA or pseudo-TA with the requested UUID.

**Comment by thangnt11** [comment]
I checked again commit "core: pta: Add device pseudo TA", it is correct. i don't understand why tee_ta_context_find() function return NULL. Could you please give me suggestion for this?

**Comment by jforissier** [comment]
Add debug traces or use a debugger. I can't see any other option.

**Comment by thangnt11** [comment]
Do you know how to confirm device PTA is registered successful or not and when invoke_command is called?

**Comment by thangnt11** [comment]
tee_ta_context_find - Find TA in session list based on a UUID
"core: pta: Add device pseudo TA" -> i don't understand why this commit add TA to session list. Could you please help me for explain this?

**Comment by jforissier** [comment]
@thangnt11 the pseudo-TA is registered by this line: https://github.com/OP-TEE/optee_os/blob/3.16.0/core/pta/device.c#L95. The line adds the UUID into a special data structure in the TEE binary. So whenever a request comes for this UUID, OP-TEE should find it and output a trace similar to this:
```
D/TC:? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA 7011a688-ddde-4053-a5a9-7b3c4ddf13b8
D/TC:? 0 tee_ta_init_pseudo_ta_session:309 Open device.pta
D/TC:? 0 tee_ta_init_pseudo_ta_session:326 device.pta : 7011a688-ddde-4053-a5a9-7b3c4ddf13b8
D/TC:? 0 tee_ta_close_session:511 csess 0xba7f79a0 id 1
D/TC:? 0 tee_ta_close_session:530 Destroy session
```
The caller of this PTA is [`__optee_enumerate_devices()`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/tee/optee/device.c?h=v5.17-rc8#n89) in the Linux driver.

**Comment by thangnt11** [comment]
Thank you for your explain. I fixed device PTA register issue. It relate to scattered array patch, i removed it and change device.c source that not using SCATTERED_ARRAY_FOREACH.
Now, new issue happen when invoke function PTA_CMD_GET_DEVICES from kernel driver.
optee_enumerate_devices -> get_devices -> tee_client_invoke_func -> optee_invoke_func ->  optee_do_call_with_arg -> optee->invoke_fn() (device hang up in here)
It is seem optee-os don't return or hang up but i don't know how to debug it. Could you please let me know which function is called when optee->invoke_fn()?

**Comment by thangnt11** [comment]
Dear jforissier,
I have a question about TEE_GenerateRandom API. 
What happen when utee_cryp_random_number_generate is called? I don't see where utee_cryp_random_number_generate function is implemented.

**Comment by jforissier** [comment]
> Dear jforissier, I have a question about TEE_GenerateRandom API. What happen when utee_cryp_random_number_generate is called? I don't see where utee_cryp_random_number_generate function is implemented.

`utee_crypt_random_number_generate()` is a system call wrapper written in assembly. It calls `syscall_cryp_random_number_generate()`.
