### ISSUE TITLE
Questions about cache operations for shared buffer 

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#5210]
Hi, when reading tee shared buffer code, I noticed it is mapped as cacheable both in REE and TEE(see code below). However, I'm quite confused since there seems no cache maintance operations when exchanges the shared buffer between each other.  Won't it cause data inconsistent or do I miss something? Could you please guide me where the cache operations are in REE and TEE ? Thanks in advance. 

```
REE: 
drivers/tee/optee/core.c:
435 static struct tee_shm_pool *
436 optee_config_shm_memremap(optee_invoke_fn *invoke_fn, void **memremaped_shm) {
...
474 >-------va = memremap(paddr, size, MEMREMAP_WB);                                                  
475 >-------if (!va) {                                                                                
476 >------->-------pr_err("shared memory ioremap failed\n");                                         
477 >------->-------return ERR_PTR(-EINVAL);                                                          
478 >-------}


TEE:
632 uint32_t core_mmu_type_to_attr(enum teecore_memtypes t)
...
658 >-------case MEM_AREA_NSEC_SHM: 
659 >------->-------return attr | TEE_MATTR_PRW | cached;
```
...

**Comment by jenswi-linaro** [comment]
As long as the memory is mapped as non-secure in secure world it should be OK.

**Comment by tiger20081015** [comment]
@jenswi-linaro , thanks for your quick reply. Could you please explain more details?  Do you suppose the cache type is either VIPT non-aliasing or PIPT, so no cache operation is need? Otherwise, although the shared buffered is mapped as non-secure in TEE, it has different memory mappings in REE and TEE. Without cache flush opeartion, I think we can't ensure the latest data is seen by each other. It may still in the cache line rather than in DDR.

**Comment by lorc** [comment]
AFAIK, ARMv8 virtual memory architecture guarantees cache coherency if the same memory page is mapped with the same Memory Type, Shareability and Cacheability attributes. Check out Section B2.8 of ARM Architecture Reference Manual.

**Comment by tiger20081015** [comment]
@lorc，thanks. But how about armv7？Some of their cache type is VIVT, in that case cache operations should be added?

**Comment by jenswi-linaro** [comment]
I believe that's only icache and we never map non-secure memory as executable.
