### ISSUE TITLE
Generated SM2 keypair is actually on ecc-secp-256 curve

### ISSUE THREAD

**Issue by xinwei2** [OP-TEE/optee_os#5211]
I meet with this SM2 key generation issue.
The SM2 key pair I generated using OPTEE OS 3.15.0 is:

######Get private key success! value is:
A86A5CB868423BE1B2B5EF7CBD500CD3E6EFD81CF3BB16ADA74985BFC17B8E1F
######Get x_value success! value is:
717720C5A97CB312F56A58D208DBBD3A829FE8BE3E30C4117C46BA6DC456C4F6
######Get y_value success! value is:
F041A44B7FFB31733C65CBEA9AB2864078D449CE79A0BBA03DAC99127E63ACC9

I use openssl to verify this keypair, found it is not on SM2 curve, but is on ecc-secp-256 curve. 
When using this keypair to sign and verify message, the signature will be generated, but verify will fail.

**Comment by xinwei2** [comment]
[sm_test.zip](https://github.com/OP-TEE/optee_os/files/8214214/sm_test.zip)
This is the openssl code I use to verify the keypair.

**Comment by xinwei2** [comment]
[sm2_generation.zip](https://github.com/OP-TEE/optee_os/files/8214218/sm2_generation.zip)
This is the code I use to generate SM2 keypair in TA and print it.

**Comment by xinwei2** [comment]
The similar issue was discussed before, but no conclusion. [https://github.com/OP-TEE/optee_os/issues/4372](url)

**Comment by jforissier** [comment]
Hello @xinwei2,

Thanks for the detailed description. I found the bug in `_ltc_ecc_generate_keypair()` and I am testing a patch. I will open a PR soon.
