### ISSUE TITLE
C++ TA ELF OS_ABI problem with LLVM's libc++

### ISSUE THREAD

**Issue by XiangyiXuWashU** [OP-TEE/optee_os#5213]
Hi:
I try to write a C++ TA by following the idea in https://github.com/OP-TEE/optee_os/pull/3693. My toolchain is  aarch64-linux-gnu (not using clang). Then I link TA's *.c and *.cpp file with libc++.a library, before that libc++ is build with aarch64-linux-gnu. OP-TEE fails to load the elf file.  I find the ELF file's OSABI value is UNIX - GNU rather than ELFOSABI_NONE. Therefore, OP-TEE fails to parse the ELF file.

Here is the log:
D/TC:? 0 ldelf_syscall_open_bin:143 Lookup user TA ELF 86faaeb3-8dac-49ab-8b04-1ad1155e1a2c (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:143 Lookup user TA ELF 86faaeb3-8dac-49ab-8b04-1ad1155e1a2c (REE)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0
E/LD:  init_elf:461 Cannot parse ELF
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff0005
D/TC:? 0 tee_ta_open_session:718 init session failed 0xffff0005

The cpptest.cpp file is very simple, just "std::cout << "C++ TA is running" << std::endl;". By using "readelf -h cpptest.o" to check the cpp object, OS/ABI is UNIX - System V,  and the .c file's OS/ABI is also UNIX - System V. However, .elf file's OS/ABI is UNIX - GNU. So the e64_parse_ehdr fails to parse ELF because of ehdr->e_ident[EI_OSABI] != ELFOSABI_NONE. I have no idea which link option determine the  OS/ABI value in the final link step, and how to force the ELF's OS/ABI equal to UNIX - System V.

$ readelf -h cpptest.o
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          378088 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           64 (bytes)
  Number of section headers:         213
  Section header string table index: 212

$ readelf -h 86faaeb3-8dac-49ab-8b04-1ad1155e1a2c.elf
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 03 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - GNU
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0x3d14
  Start of program headers:          64 (bytes into file)
  Start of section headers:          1018600 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         5
  Size of section headers:           64 (bytes)
  Number of section headers:         20
  Section header string table index: 19

**Comment by jforissier** [comment]
Hello @XiangyiXuWashU,

I have not met this issue before. I suspect the OS/ABI value comes from something in your libstdc++.a. Can you run `readelf -h libstdc++.a | egrep "(File|OS)"` to check its content?
I have found this interesting discution: https://stackoverflow.com/a/2770984 and also https://sourceware.org/glibc/wiki/GNU_IFUNC. Hope that helps.

**Comment by XiangyiXuWashU** [comment]
Hello [jforissier]:

**Comment by jforissier** [comment]
> The File: libc++.a(string.cpp.o) and File: libc++.a(locale.cpp.o) are UNIX - GNU, other are UNIX - System V.

OK, so `string.cpp` and `locale.cpp` seem to have something special that causes the ABI to be switched to UNIX - GNU.

**Comment by XiangyiXuWashU** [comment]
string.cpp: https://github.com/llvm/llvm-project/blob/main/libcxx/src/string.cpp
locale.cpp: https://github.com/llvm/llvm-project/blob/main/libcxx/src/locale.cpp

**Comment by jforissier** [comment]
I see nothing suspicious in the source code. Can you share how you build libcxx?

**Comment by XiangyiXuWashU** [comment]
#!/bin/bash

export CXX=path to aarch64-linux-gnu-g++

cmake -D LIBCXX_ENABLE_SHARED=OFF \
      -D LIBCXX_ENABLE_THREADS=OFF \
      -D HAVE_LIBCXXABI=ON
make

**Comment by jforissier** [comment]
@XiangyiXuWashU try adding `-DCMAKE_CXX_FLAGS=-fno-gnu-unique` when building `libcxx.a`.

**Comment by XiangyiXuWashU** [comment]
@jforissier 
It works! Thank you so much! I have tested C++ vector/set/unordered_map, it works well. But I could only use printf to print out the log. When I used std::cout, it caused abort in User mode.

cpptest.cpp:
#include <iostream>
#include <vector>

using namespace std;

extern "C"  void cpptest();
void cpptest(void)
{
    vector<int> arr;
    arr.push_back(1);

    printf("print with c: arr[0] = %d\n", arr[0]);
    cout << "print with c++" << arr[0] << endl;
}

TA Log: 
print with c: arr[0] = 1
D/TC:0 0 abort_handler:533 [abort] abort in User mode (TA will panic)
E/TC:? 0 
E/TC:? 0 User mode data-abort at address 0xffffffffffffffe8 (translation fault)
E/TC:? 0  esr 0x92000004  ttbr0 0x200000e539000   ttbr1 0x00000000   cidr 0x0
E/TC:? 0  cpu #0          cpsr 0x00000100
E/TC:? 0  x0  ffffffffffffffe8 x1  0000000080119c18
E/TC:? 0  x2  000000000000000e x3  0000000000000000
E/TC:? 0  x4  0000000000000000 x5  fffffffffffffff0
E/TC:? 0  x6  0000000000000000 x7  00000000800fcb46
E/TC:? 0  x8  0000000000000001 x9  0000000000000008
E/TC:? 0  x10 7fffffffffffffdf x11 00000000ffffffff
E/TC:? 0  x12 0000000000000000 x13 0000000080014f80
E/TC:? 0  x14 0000000000000000 x15 0000000000000000
E/TC:? 0  x16 000000000e2088a4 x17 0000000000000000
E/TC:? 0  x18 0000000000000000 x19 0000000000000000
E/TC:? 0  x20 0000000080119c18 x21 000000000000000e
E/TC:? 0  x22 0000000000000003 x23 0000000080014e60
E/TC:? 0  x24 00000000800fcb47 x25 0000000000000000
E/TC:? 0  x26 0000000000000000 x27 0000000000000000
E/TC:? 0  x28 0000000000000000 x29 0000000080014da0
E/TC:? 0  x30 0000000080021c10 elr 0000000080036cb4
E/TC:? 0  sp_el0 0000000080014da0
E/LD:  Status of TA 86faaeb3-8dac-49ab-8b04-1ad1155e1a2c
E/LD:   arch: aarch64
E/LD:  region  0: va 0x80004000 pa 0x0e900000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x80006000 pa 0x0e902000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x8000e000 pa 0x0e90a000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x8000f000 pa 0x0e90b000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x80013000 pa 0x0e90f000 size 0x001000 flags r--s
E/LD:  region  5: va 0x80014000 pa 0x0ea16000 size 0x001000 flags rw-s (stack)
E/LD:  region  6: va 0x8001e000 pa 0x00001000 size 0x0f1000 flags r-xs [0]
E/LD:  region  7: va 0x8010f000 pa 0x000f2000 size 0x015000 flags rw-s [0]
E/LD:   [0] 86faaeb3-8dac-49ab-8b04-1ad1155e1a2c @ 0x8001e000
E/LD:  Call stack:
E/LD:   0x0000000080036cb4
E/LD:   0x0000000080021c0c
E/LD:   0x00000000800219b4
E/LD:   0x0000000080021900
E/LD:   0x0000000080025de8
E/LD:   0x0000000080021d50
D/TC:? 0 user_ta_enter:177 tee_user_ta_enter: TA panicked with code 0xdeadbeef
D/TC:? 0 destroy_ta_ctx_from_session:324 Remove references to context (0xe3d2728)
D/TC:? 0 destroy_context:308 Destroy TA ctx (0xe3d2710)

**Comment by jforissier** [comment]
> @jforissier
> It works! Thank you so much! I have tested C++ vector/set/unordered_map, it works well. 

That's good news :)

> But I could only use printf to print out the log. When I used std::cout, it caused abort in User mode.

Please use `optee_os/scripts/symbolize.py` to annotate the dump. See https://optee.readthedocs.io/en/latest/debug/abort_dumps.html. After the `-d` flag you should pass the directory where you TA `.elf` file can be found (or the file itself).

You may have to rebuild `libc++.a` in debug mode (`-DCMAKE_BUILD_TYPE=debug`) to get more information from the call stack.

What other libraries are you using? For `libc++.a` to work, it should use the OP-TEE C library (`libutils.a`) and not any other libc obviously.

**Comment by XiangyiXuWashU** [comment]
@jforissier 
I use libc++/libunwind/libc++abi/musl c which is mention by [HernanGatta](https://github.com/HernanGatta) https://github.com/OP-TEE/optee_os/pull/3693. By the way, is that symbolize.py a static elf file analyzing tool? When I run the command symbolize.py -d, it's stuck.

**Comment by jforissier** [comment]
> I use libc++/libunwind/libc++abi/musl c which is mentioned by [HernanGatta](https://github.com/HernanGatta) https://github.com/OP-TEE/optee_os/pull/3693. libutils.a is not linked for TA.

`libutee.a` provides `printf()`, `puts()` and `putchar()` which are all based on `trace_ext_puts()`, which simply calls the syscall wrapper `_utee_log()` (the syscall is `syscall_log()`). In order to get `cout` to work, you may have to modify libcxx or musl.

> When I run the command symbolize.py -d, it's stuck.

You need to copy/paste the stack dump. Or you can also run `cat dump.txt | ./optee_os/scripts/symbolize.py -d ...`.

**Comment by XiangyiXuWashU** [comment]
@jforissier 
Thanks for your instruction! symbolize.py is really useful. When I call std::cout, calling stack indicated it's crashed at if (__os.good()). Do you mean I need to modify libcxx's ostream to call syscall  _utee_log() to get cout to work.

[llvm: libcxx\include\ostream](https://github.com/llvm/llvm-project/blob/main/libcxx/include/ostream)
template <class _CharT, class _Traits>
basic_ostream<_CharT, _Traits>::sentry::sentry(basic_ostream<_CharT, _Traits>& __os)
    : __ok_(false),
      __os_(__os)
{
    if (__os.good())    ====================> data abort here!!!
    {
        if (__os.tie())
            __os.tie()->flush();
        __ok_ = true;
    }
}

**Comment by jforissier** [comment]
> @jforissier Thanks for your instruction! symbolize.py is really useful. When I call std::cout, calling stack indicates it's crashed at if (__os.good()). Do you mean I need to modify libcxx's ostream to call syscall _utee_log() to get cout to work?

Possibly, yes, but I can't say for sure. Using LLVM's libc++ with other GCC (g++) libraries seems a bit dangerous to me since there is no guarantee that they will be compatible, but if libc++.a only depends on simple C functions to interface with the OS, then it may be possible. It seems to be the case since you have some code running already ;-)

Perhaps try to understand why you have this data abort on `__os.good()`. Some initialization issue perhaps? GDB may help here. For example with QEMU you would do:
```
$ cd build
$ make CFG_TA_ASLR=n run  # Do not type 'c' at the QEMU prompt
$ ../toolchains/aarch64/bin/aarch64-linux-gnu-gdb
(gdb) target remote localhost:1234
(gdb) add-symbol-file path/to/ta.elf <load_address + 0x20>  # obtain load_address from the OP-TEE debug message:
                                                            # "D/LD:  ldelf:168 ELF (<UUID>) at 0x40014000"
(gdb) b some_function
(gdb) c
```
