### ISSUE TITLE
How to pass initialized "TEE_Attribute" struct from TA to CA and vice-versa?

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#5216]
I want to call a TA command from CA which initializes a reference attribute by using the `TEE_InitRefAttribute() `function. Then, i would like to pass this initialized attribute structure back to the CA from TA.

Now, i want to use the above initialized attribute structure and call yet another TA command and pass it to the TA so that it can be used as an input for `TEE_PopulateTransientObject()`.

Any method i can use to pass this structure back and forth?
(I was thinking typecasting could be an option but that would be dangerous)

If i'm not wrong, i think there is such a use-case in xtest with the usage of `pack_attrs()` (used on CA) and `unpack_attrs()` (used on TA) functions. But, i wanted to give a try without using these functions.

**Comment by Hussain1811** [comment]
Sample Code:
CA:
```
bool test_init_ref_attr(ADBG_Case_t *c, TEEC_Session *sess, uint32_t *key_attr, TEEC_Operation op,
                        uint32_t exp_init_ref_attr_res)
{
    TEEC_Result res = TEEC_ERROR_GENERIC;
    uint32_t ret_orig = 0;
    bool result = false;
    uint32_t init_ref_attr_cmd = 0;

    init_ref_attr_cmd = combine_module_and_test_cmd(CRYPTO_COMMON, TA_CRYPTO_INIT_REF_ATTR);
    Do_ADBG_Log("\n TEEC_InvokeCommand:0x%X", init_ref_attr_cmd);

    res = TEEC_InvokeCommand(sess, init_ref_attr_cmd, &op, &ret_orig);
    result = ADBG_EXPECT_TEEC_RESULT(c, exp_init_ref_attr_res, res);
    if (result == false)
        Do_ADBG_Log("TA invoke command to init the reference attribute returned with origin:%d", ret_orig);
    else
        *key_attr = op.params[2].value.a;

    return result;
}
```
TA:
```
TEE_Result ta_entry_call_crypto_init_ref_attr(uint32_t param_types, TEE_Param params[4])
{
    TEE_Attribute key_attr;
    uint8_t *key = NULL;
    uint32_t key_len = 0;
    uint32_t attr_id = 0;

    uint32_t exp_param_types = TEE_PARAM_TYPES(TEE_PARAM_TYPE_VALUE_INPUT, TEE_PARAM_TYPE_MEMREF_INPUT,
                                               TEE_PARAM_TYPE_NONE, TEE_PARAM_TYPE_NONE);

    FMSG("entering");

    if (param_types != exp_param_types) {
        EMSG("Unexpected parameters have been provided to TA");
        return TEE_ERROR_BAD_PARAMETERS;
    }

    attr_id = params[0].value.a;
    key = params[1].memref.buffer;
    key_len = params[1].memref.size;

    TEE_InitRefAttribute(&key_attr, attr_id, key, key_len);

    params[2].value.a = key_attr;

    FMSG("exiting");

    return TEE_SUCCESS;
}
```

**Comment by jenswi-linaro** [comment]
The `TEE_Attribute` struct contains pointers to it must be serialized in some way to be passed via shared memory. Take a look in the PKCS#11 lib, https://github.com/OP-TEE/optee_client/blob/master/libckteec/src/serialize_ck.c, for another example.

**Comment by Hussain1811** [comment]
Thank you.
This answers some of my questions.
