### ISSUE TITLE
NXP i.MX8M Mini won't load optee-os

### ISSUE THREAD

**Issue by mullroy** [OP-TEE/optee_os#5218]
Good day,
 I've got a Forlinx SOM with 2GB DDR4 RAM & 8GB eMMC. I'm manually building u-boot for the NXP i.MX8M mini processor.
The code used are all from source.codeaurora.com, tag: lf-5.10.72-2.2.0
kernel:             https://source.codeaurora.org/external/imx/linux-imx/refs/tags
uboot-imx:       https://source.codeaurora.org/external/imx/uboot-imx/refs/tags
imx-atf:            https://source.codeaurora.org/external/imx/imx-atf/refs/tags?h=github.com/master
imx-mkimage: https://source.codeaurora.org/external/imx/imx-mkimage/
imx-optee-os:  https://source.codeaurora.org/external/imx/imx-optee-os/

The security fuses are already set on the CPU. It boots a signed u-boot image, verifies the kernel signature and boots linux successfully.
I would like to enable the encryption feature of the CPU. OP-TEE-os has access to the encryption engine of the CPU, which needs to
sign DEK.BLOB in order to finish the preparation of the encrypted u-boot image. For the signed u-boot image OP-TEE was optional. 

I've followed the two steps to enable OP-TEE as suggested by the NXP forums:
1) Enable optee in ATF:
$ make PLAT=imx8mm BUILD_BASE=build-optee SPD=opteed bl31

2) Build optee-os
ARCH=arm CFG_TEE_CORE_LOG_LEVEL=4 CFG_TEE_TA_LOG_LEVEL=3 CROSS_COMPILE64=${CROSS_COMPILE} CFLAGS="--sysroot=${SDKTARGETSYSROOT}" LDFLAGS= CFG_NXPCRYPT=y CFG_GEN_DEK_BLOB=y source ./scripts/nxp_build.sh imx-mx8mmevk

I've re-build u-boot with OP-TEE support:
    CONFIG_HAS_CAAM=y
    CONFIG_IMX_OPTEE=y
    CONFIG_FSL_CAAM=y
    CONFIG_SYS_FSL_SEC_COMPAT_4=y
    CONFIG_SYS_FSL_SEC_COMPAT=4
    CONFIG_SYS_FSL_SEC_LE=y
    CONFIG_CMD_DEKBLOB=y    
    CONFIG_IMX_OPTEE_DEK_ENCAP=y
    CONFIG_BOOTM_OPTEE=y
    CONFIG_OPTEE_LOAD_ADDR=0xbe000000

    optee-os: core/arch/arm/plat-imx/platform_config.h: OPTEE size set to 32MB
    CONFIG_OPTEE_TZDRAM_SIZE=0x02000000

    conf.mk: 
       CFG_TZDRAM_START ?= ($(CFG_DRAM_BASE) - 0x02000000 + $(CFG_DDR_SIZE))
       = 0x40000000        - 0x02000000 + 0x80000000
       = 0xBE000000                 
    CONFIG_OPTEE_TZDRAM_BASE=0xBE000000

I've used mkimage to assemble the u-boot binary, which was subsequently signed. The CPU boots the u-boot
image, which shows that the verification passed. I've added additional debug "NOTICE" entries to ATF to follow
the boot progress. As soon as the code branches to OP-TEE the boot process stops without further debug output
on the console.

I've noticed in opteed_setup() that the rw, pageable_part and mem_limit values passed to the function
were all 0x00. I don't know if this is a hint that somewhere some data was lost?

Is the Cortex M4 suppose to print any debug logs on its console as it executes the trusted environment?

Any help to solve this problem will be much appreciated.

Regards,
Mullroy

[u-boot_optee_debug.txt](https://github.com/OP-TEE/optee_os/files/8248112/u-boot_optee_debug.txt)

**Comment by mullroy** [comment]
Good day,

I see in the imx-optee-os/build.imx-mx8mmevk/conf.mk file that the DRAM size & base address are defined:
        CFG_TZDRAM_SIZE=0x01c00000
        CFG_TZDRAM_START=(0x40000000 - 0x02000000 + 0x80000000)

I've subsequently adapted the u-boot config to reflect these values:
    CONFIG_OPTEE_TZDRAM_SIZE=0x01c00000
    CONFIG_OPTEE_TZDRAM_BASE=0xbe000000


In the imx-atf project inside plat/imx/imx8m/imx8mm/imx8mm_bl31_setup.c the bl32_image_ep_info
structure is populated. The project is build for 'SPD=opteed', but there is a second define in the
source code which affects the arguments that are populated. If 'SPD_trusty' is not set, the BL32_SIZE
and BL32_BASE is not set.

#if defined(SPD_opteed) || defined(SPD_trusty)
        /* Populate entry point information for BL32 */
        SET_PARAM_HEAD(&bl32_image_ep_info, PARAM_EP, VERSION_1, 0);
        SET_SECURITY_STATE(bl32_image_ep_info.h.attr, SECURE);
        bl32_image_ep_info.pc = BL32_BASE;
        bl32_image_ep_info.spsr = 0;

        /* Pass TEE base and size to bl33 */
        bl33_image_ep_info.args.arg1 = BL32_BASE;
        bl33_image_ep_info.args.arg2 = BL32_SIZE;

#ifdef SPD_trusty
        bl32_image_ep_info.args.arg0 = BL32_SIZE;
        bl32_image_ep_info.args.arg1 = BL32_BASE;
#else
        /* Make sure memory is clean */
        mmio_write_32(BL32_FDT_OVERLAY_ADDR, 0);
        bl33_image_ep_info.args.arg3 = BL32_FDT_OVERLAY_ADDR;
        bl32_image_ep_info.args.arg3 = BL32_FDT_OVERLAY_ADDR;
#endif

In the attached log file in the first post the FDT overlay address mismatches the adres of the flattened device
tree in the flash.bin.

**Comment by mullroy** [comment]
Good day,
Is optee-os executed in 32bit or 64 bit mode? 
'rw' is initialised from bl32_image_ep_info.args.arg2, 
but bl32_image_ep_info.args.arg2 is never set in the code.
The default of 0x0 matches AARCH64

in imx-atf/services/spd/opteed/opteed_common.c
        rw is evaluated if OP-TEE was compiled for:  OPTEE_AARCH32 || OPTEE_AARCH64
        optee_entry_point->args.arg0 = pageable_part;
        optee_entry_point->args.arg1 = mem_limit;
        optee_entry_point->args.arg2 = dt_addr;

Regardless if pageable_part & mem_limit is 0x00 (The default when SPD_trusty is not defined)
or patched to be 0xbe000000 (TZ DRAM BASE) & 0x2000000 (TZ DRAM SIZE)
or if rw is set to 32 or 64 bit, OP-TEE does not run. Execution stops at opteed_enter_sp()

**Comment by jenswi-linaro** [comment]
> Good day, Is optee-os executed in 32bit or 64 bit mode? 'rw' is initialised from bl32_image_ep_info.args.arg2, but bl32_image_ep_info.args.arg2 is never set in the code. The default of 0x0 matches AARCH64

On a 64-bit platform OP-TEE is normally configured for 64-bit mode, but 32-bit mode is also possible on most platforms.

> 
> in imx-atf/services/spd/opteed/opteed_common.c rw gets evaluated if OP-TEE was compiled for: OPTEE_AARCH32 || OPTEE_AARCH64 optee_entry_point->args.arg0 = pageable_part; optee_entry_point->args.arg1 = mem_limit; optee_entry_point->args.arg2 = dt_addr;
> 
> Regardless if pageable_part & mem_limit is 0x00 (The default when SPD_trusty is not defined) or patched to be 0xbe000000 (TZ DRAM BASE) & 0x2000000 (TZ DRAM SIZE) or if rw is set to 32 or 64 bit, OP-TEE does not run. Execution stops at opteed_enter_sp()

The code you're testing with isn't upstream code from OP-TEE point of view. I don't know how far imx-optee-os has deviated from upstream. Perhaps the @OP-TEE/plat-imx maintainer can help.

**Comment by mullroy** [comment]
Good day,

Thank you for the reply. The @OP-TEE/plat-imx link resolves to https://github.com/orgs/OP-TEE/teams/plat-imx , which
gives a 404/Not Found error.
Is there another way to navigate to the imx team?

Regards,

**Comment by mullroy** [comment]
Good day,

I saw under pull requests a request made 2 days ago for the NXP i.MX6 & i.MX7 by Clément Faure
(clementfaure), with bio description: Embedded software engineer @NXP OP-TEE maintainer for i.MX

I think this is my guy: engineer @NXP OP-TEE maintainer for i.MX

I´ll contact him.

Regards,

**Comment by clementfaure** [comment]
Hi @mullroy, I received your email.
Your issue is a bit off topic for the OPTEE-OS upstream Github repo.
I will assist you by replying to your email.

@jenswi-linaro Is there anything we can do to restore @OP-TEE/plat-imx ? I don't receive any notification

**Comment by jforissier** [comment]
The @OP-TEE/plat-imx link works for me... @clementfaure you weren't notified because you weren't registered as a member of that team. I have added you.

**Comment by clementfaure** [comment]
@jforissier I've received the invite! Thanks!

**Comment by clementfaure** [comment]
Hi @jforissier 
You can close the issue. The answer has been provided outside of this thread.
