### ISSUE TITLE
plat-zynq: SCU

### ISSUE THREAD

**Issue by b-bub** [OP-TEE/optee_os#522]
Hello,

i try to port optee_os to a Zynq platform.
So, i cloned plat-stm because it's a Cortex-A9, too.
I only edited platform_config.h, so far.

Unfortunately, my system crashes when setting up SCU addresses in tz_a9init.S : _boot_late_primary_cpu.
My guess is, that the SCU start & end addresses are wrong.

Looking at plat-stm/platform_config.h the SCU addresses (CPU_PORT_FILT_START, CPU_PORT_FILT_END) are set to the DRAM0 address range, aye?
So, i try the same with my DRAM0 address range, but fail.

Right after setting the SCU addresses i access the UART register with the following code, to get some debug output.
The CPU crashes then with the STR instruction.
> mov r0, #'D'            // Load character
> movw r1, #0x1000
> movt r1, #0xE000
> orr r1, r1, #0x30       // TX FIFO register
> str r0, [r1]            // Write character to UART

I also checked the Zynq TRM (ug585, v1.10) Chapter 29 'OCM' which gives example settings for SCU. But, i fail with these too.

I guess i just don't really understand SCU address settings. The examples in Zynq TRM do not follow the logic as in plat-stm.

Can anybody throw light on this topic for me, please?
What's the purpose of SCU?
Is setting the SCU addresses really that easy as in plat-stm?
If so, why the hell shouldn't this work on Zynq?

Thanks

**Comment by jenswi-linaro** [comment]
Hi,

You can read about the SCU in Cortex™-A9 MPCore® Technical Reference Manual (http://infocenter.arm.com/help/topic/com.arm.doc.ddi0407i/index.html). There also seems to be some information about it in the TRM you reference.

Regards,
Jens

**Comment by b-bub** [comment]
Thanks for answer Jens.

I already read the Cortex-A9 mp TRM.
Unfortunately, it doesn' t make any remarks about allowed or incorrect settings for the SCU addresses.
As i understand from ARM TRM, SCU is a simple address filter which shouldn't be that complicated, is it?

**Comment by jenswi-linaro** [comment]
That's right. Depending on how the system boots you may not even need to touch it.

**Comment by b-bub** [comment]
Ok,
can you go a little bit more in detail about "depending on how the system boots", please?
Do you mean, when i only use one CPU, instead of both CPU0 and CPU1?

**Comment by jenswi-linaro** [comment]
It depends on the boot architecture. If we compare with ARMv8 using ARM-TF then this is something you would expect ARM-TF (the loader) to initialize instead of the Trusted OS.

If a SCU needs to be initialized and the piece of software loading OP-TEE doesn't do it then I guess you need to do it in OP-TEE.

In this case you need to check whatever documentation is relevant for your platform to see what the Trusted OS need to initialize.

**Comment by b-bub** [comment]
Well, my current boot-process sure is a possible source of error.

Since ARM TF is not available for ARMv7, I load tee.bin with U-Boot.
tee.bin then resets the CPUs and stuff again before reinitializing. So, i thought this would be ok...

As stated before, i cloned from plat-stm which is a Cortex-A9, too.
Does anybody know details about plat-stm boot-process?
Is there any chance to get in contact with them?

**Comment by jbech-linaro** [comment]
@b-bub , plat-stm devices are not publicly available (see [here](https://github.com/OP-TEE/optee_os#3-platforms-supported)), so we cannot give any details about the boot process for that device. I would advise that you send your implementation as a "Request For Comment" pull request (RFC: plat-zynq support) instead and then we can review and discuss that part as a separate item.

**Comment by jbech-optee-adm** [comment]
plat-zynq is not (officially) supported and therefore we cannot give precise answers since we are unfamiliar with this platform. Based on this and little activity on this issue I will close this issue. Please feel free to re-open in case you have additional comments.
