### ISSUE TITLE
Key-usage not updated with TEE_USAGE_EXTRACTABLE for attributes with public protection level

### ISSUE THREAD

**Issue by Sadiq1811** [OP-TEE/optee_os#5222]
Steps to reproduce:
1)Allocate op-handle with alg=TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA256; max_key_size=4096; mode=TEE_MODE_ENCRYPT
2)alloc trans obj with above max_key_size; type=TEE_TYPE_RSA_PUBLIC_KEY
3)initialize the attributes i.e. TEE_ATTR_RSA_MODULUS and TEE_ATTR_RSA_PUBLIC_EXPONENT
4)populate the transient object
5)set the operation key
6)check the key-usage value via TEE_GetOperationInfo()

NOTE: I didn't check for other attributes and algs though

**Comment by jforissier** [comment]
Hi @Sadiq1811,

>  6)check the key-usage value via TEE_GetOperationInfo()

Do you mean `operationInfo.requiredKeyUsage` doesn't have the `TEE_USAGE_EXTRACTABLE` bit set? If so, why should it be set?

**Comment by Sadiq1811** [comment]
I was wondering if it should be "always" set for public attributes (Table 6-15 in TEE Internal Spec) so as to completely satisfy the meaning of `TEE_USAGE_EXTRACTABLE`.

**Comment by jforissier** [comment]
`TEE_USAGE_EXTRACTABLE` is an object usage flag. It applies to key objects, not to individual attributes, so I don't see what you mean. Care to provide a complete test case?

**Comment by Sadiq1811** [comment]
Thanks for the clarification.
I guess we are in sync now.
