### ISSUE TITLE
Obtaining a TCP server inside a TA with TLS

### ISSUE THREAD

**Issue by gorgonical** [OP-TEE/optee_os#5251]
Hello,

I am building a research project where a TA needs to communicate securely with a remote host over TCP. I understand from #4075 that TLS support is not present, but can be achieved by gluing the GP sockets API to the mbedtls system. I believe I understand how to do this and have a nearly complete implementation of this.

However, my TA must act as a server and listen for incoming connections. I don't think this is possible with the current API or I don't understand it correctly, since the GP TCP socket API does not show any connection management. 

On the assumption that the `open()` call with a TCP iSocket is meant to connect to a listening TCP socket, I have an idea but would really appreciate guidance:

1. A TCP socket listens in the untrusted CA.
2. When the remote client wants to establish a connection, it connects to the CA's listening socket. At the same time, the remote client establishes a TCP socket listening on a different port.
3. The CA invokes a TA command that causes the TA to attempt to connect to the remote client's TCP socket.
4. Acting as the TLS server, the remote client and TA establish a secure connection.

The main problem is the inversion of security. Am I misunderstanding how TCP sockets work in `libutee`? I have looked around the various git repositories associated with OP-TEE and can't find exactly what happens in Linux when a TCP socket is `open()`ed. If there is some way I can open a listening TCP socket in the TA, or perhaps use the untrusted CA to "hand off" the socket upon connection by the remote host, that would also suffice.

My fallback solution is currently to break "recommended practice" and have the remote host directly use RSA (or similar) encryption to produce a chunked payload only the TA can decrypt. Then the untrusted CA can receive it and hand it off to the TA without compromising security.

Thanks

**Comment by jenswi-linaro** [comment]
How a remote client communicates with the CA is not covered by the GP standards that OP-TEE uses. 

When an iSocket is opened we end up in tee_socket_open() in tee-supplicant.
https://github.com/OP-TEE/optee_client/blob/5a69d55d65966c098ee1acce56bcd660f0de917b/tee-supplicant/src/tee_socket.c#L260-L261

An iSocket open always results in a call to `connect()` inside tee-supplicant.

In my opinion the iSocket API is mostly useful when you have a simple setup where the TA need to connect to some server without involving the CA. In your case it seems that the CA/TA setup is the part being the server while the other end roams. It looks like the iSocket API doesn't cover your use-case in a convenient way.

It seems that the fallback solution is less complicated. You could even run a TLS stream over such a channel.

**Comment by gorgonical** [comment]
@jenswi-linaro Thank you very much for your fast reply. I was very stressed at the time and your exceptional reply speed was very helpful. It is now clear the tee-supplicant isn't designed to act as a socket server for the TA. I did go ahead and implement pubkey encryption in chunks, with the CA acting as the host of the listening socket, passing the ciphertext blob to the TA to be decrypted securely.

I wonder if there is a valuable use-case for socket ```bind()``` and ```listen()``` to be supported by the supplicant/TA?

**Comment by jenswi-linaro** [comment]
> I wonder if there is a valuable use-case for socket `bind()` and `listen()` to be supported by the supplicant/TA?

In my opinion it seems rather limited because it becomes much more complicated.
