### ISSUE TITLE
question about TEEC_LOGIN_USER.

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#5257]
Hello,

I'm looking at xtest 1027.
In this test, "TEEC_LOGIN_USER" is used for Open Session in CA.
And when the TA receives the Invoke Command, it reads the CA's UUID information using "TEE_PROPSET_CURRENT_CLIENT".

What I am curious about here is how the CA registers its UUID to the TA side.
It's probably done through the TZ Driver, but I can't find the part that transmits to the TZ Driver or Secure in the CA code.
So I don't know how to read client info in TA.

At this time, I know that the CA's UUID uses SHA after combining the UID with the global variable "client_uuid_linux_ns".
For reference, the code I'm looking at right now is "xtest_tee_test_1027".
I would be grateful if anyone who knows would reply.

**Comment by jenswi-linaro** [comment]
The CA UUID is sent over when opening the session. You can see some of it in optee_open_session() in the file drivers/tee/optee/call.c in the Linux kernel.

**Comment by SangsubLim** [comment]
@jenswi-linaro ,
Thank you! :)
