### ISSUE TITLE
Question about RPMB_key

### ISSUE THREAD

**Issue by Yuki711** [OP-TEE/optee_os#5258]
Hi,

I currently started to use OP-TEE, and I would like to integrate the use of RPMB in my project (I only tested REE_FS). I am working with an NXP board and I already flashed a Yocto image thanks to eMMC.
I found that to activate RPMB storage, I have to set 'CFG_RPMB_FS=y' and 'CFG_RPMB_WRITE_KEY=y' into optee-os.

But before doing that, I would like to check the value of my HUK (Hardware Unique Key).
Could someone help me to get this key value before writing RPMB_key ?

Thanks

**Comment by jforissier** [comment]
Hi @Yuki711,

When `CFG_RPMB_WRITE_KEY=y`, the key is printed on the secure console with log level "debug", therefore make sure you also set `CFG_TEE_CORE_LOG_LEVEL=3` (or more). If you can see the debug message on OP-TEE boot (`D/TC ...`) then you're good to go. This line prints the RPMB key: https://github.com/OP-TEE/optee_os/blob/3.16.0/core/tee/tee_rpmb_fs.c#L1076

Note that the RPMB key is derived from the HUK but it is not equal to the HUK. For that, function [`tee_rpmb_key_gen()`](https://github.com/OP-TEE/optee_os/blob/3.16.0/core/tee/tee_rpmb_fs.c#L311-L334) calls [`huk_subkey_derive()`](https://github.com/OP-TEE/optee_os/blob/3.16.0/core/kernel/huk_subkey.c#L61-L107) which uses the HUK [here](https://github.com/OP-TEE/optee_os/blob/3.16.0/core/kernel/huk_subkey.c#L78).

Finally, note that you can also use a [hard-coded test key](https://github.com/OP-TEE/optee_os/blob/3.16.0/core/tee/tee_rpmb_fs.c#L283-L290) by setting `CFG_RPMB_TESTKEY=y`.

**Comment by ricardosalveti** [comment]
> I currently started to use OP-TEE, and I would like to integrate the use of RPMB in my project (I only tested REE_FS). I am working with an NXP board and I already flashed a Yocto image thanks to eMMC. I found that to activate RPMB storage, I have to set 'CFG_RPMB_FS=y' and 'CFG_RPMB_WRITE_KEY=y' into optee-os.
> 
> But before doing that, I would like to check the value of my HUK (Hardware Unique Key). Could someone help me to get this key value before writing RPMB_key ?

What is the NXP SoC used here?

In order to generate a unique key you will have to first fuse and close the device and then make sure all the options related to it in OP-TEE are enabled (if based on CAAM or DCP, for example).

**Comment by Yuki711** [comment]
> Hi @Yuki711,
> 
> When `CFG_RPMB_WRITE_KEY=y`, the key is printed on the secure console with log level "debug", therefore make sure you also set `CFG_TEE_CORE_LOG_LEVEL=3` (or more). If you can see the debug message on OP-TEE boot (`D/TC ...`) then you're good to go. This line prints the RPMB key: https://github.com/OP-TEE/optee_os/blob/3.16.0/core/tee/tee_rpmb_fs.c#L1076
> 
> Note that the RPMB key is derived from the HUK but it is not equal to the HUK. For that, function [`tee_rpmb_key_gen()`](https://github.com/OP-TEE/optee_os/blob/3.16.0/core/tee/tee_rpmb_fs.c#L311-L334) calls [`huk_subkey_derive()`](https://github.com/OP-TEE/optee_os/blob/3.16.0/core/kernel/huk_subkey.c#L61-L107) which uses the HUK [here](https://github.com/OP-TEE/optee_os/blob/3.16.0/core/kernel/huk_subkey.c#L78).
> 
> Finally, note that you can also use a [hard-coded test key](https://github.com/OP-TEE/optee_os/blob/3.16.0/core/tee/tee_rpmb_fs.c#L283-L290) by setting `CFG_RPMB_TESTKEY=y`.

Hi, 

Thank you for your reply.
I already set 'CFG_TEE_CORE_LOG_LEVEL=3', but I don't think I saw the RPMB_key on my TeraTerm Terminal. Do I have to write a specific command to 'generate' this key and print it?

**Comment by Yuki711** [comment]
> > I currently started to use OP-TEE, and I would like to integrate the use of RPMB in my project (I only tested REE_FS). I am working with an NXP board and I already flashed a Yocto image thanks to eMMC. I found that to activate RPMB storage, I have to set 'CFG_RPMB_FS=y' and 'CFG_RPMB_WRITE_KEY=y' into optee-os.
> > But before doing that, I would like to check the value of my HUK (Hardware Unique Key). Could someone help me to get this key value before writing RPMB_key ?
> 
> What is the NXP SoC used here?
> 
> In order to generate a unique key you will have to first fuse and close the device and then make sure all the options related to it in OP-TEE are enabled (if based on CAAM or DCP, for example).

Hi, 

I am using an iMX8M Quad EVK. I think my HUK is based on CAAM.
I am not really an expert so what do you mean by 'fuse and close the device'?  Could you tell me the steps to do that in order to get the HUK please?

Thank you!

**Comment by ricardosalveti** [comment]
> I am using an iMX8M Quad EVK. I think my HUK is based on CAAM. I am not really an expert so what do you mean by 'fuse and close the device'? Could you tell me the steps to do that in order to get the HUK please?

That is part of the process when enabling secure boot (you can find more at https://docs.foundries.io/latest/reference-manual/security/secure-boot-imx-habv4.html).

But what you need to be careful is that the HUK is only really unique when the device is in a secure state, and that is only done after fused and booting a signed and trusted image. You can still generate a HUK on open devices, but that key will be a test one, and not really secure (this is important as the RPMB key is a write once process).

If you write the RPMB key with the device still open (not fused) and later fuse and close your device, you will get a different HUK as a consequence, and the RPMB key won't match.

**Comment by Yuki711** [comment]
> > I am using an iMX8M Quad EVK. I think my HUK is based on CAAM. I am not really an expert so what do you mean by 'fuse and close the device'? Could you tell me the steps to do that in order to get the HUK please?
> 
> That is part of the process when enabling secure boot (you can find more at https://docs.foundries.io/latest/reference-manual/security/secure-boot-imx-habv4.html).
> 
> But what you need to be careful is that the HUK is only really unique when the device is in a secure state, and that is only done after fused and booting a signed and trusted image. You can still generate a HUK on open devices, but that key will be a test one, and not really secure (this is important as the RPMB key is a write once process).
> 
> If you write the RPMB key with the device still open (not fused) and later fuse and close your device, you will get a different HUK as a consequence, and the RPMB key won't match.

Hi @ricardosalveti, 

Thank you for your reply. I read the documentation you linked, but I don't think I want to fuse and close my device because I am developping on my board (not at commercial issue).

I only want to be sure that HUK!=0 before setting 'CFG_RPMB_WRITE_KEY=y'. I assume that I have to make dure that CAAM is enabled first?
