### ISSUE TITLE
Does OP-TEE always enable NEON instruction while running vfp?

### ISSUE THREAD

**Issue by Neal-liu** [OP-TEE/optee_os#5260]
According to commit c9add4ac01f5 ("core: arm32: enable NEON with .fpu directive rather than compile flag"), does
OP-TEE always enable NEON with vfp?
If no, is there any other ways to disable NEON with vfp?

From on my understanding, ARMv7 supports different combinations based on vendor implementation options.
- VFP only
- VFP + NEON

Thank you in advance for your attention to this matter.

**Comment by Neal-liu** [comment]
Hi @jenswi-linaro @jforissier @etienne-lms,

Sorry for bothering you, would you mind to give us some clues for this issue?

**Comment by jenswi-linaro** [comment]
It looks like OP-TEE assumes either VFP+NEON or none configured with `CFG_WITH_VFP`.

**Comment by Neal-liu** [comment]
Do you imply that there is no way to disable NEON if the ARMv7 platforms only support VFP instead of VFP+NEON?

**Comment by jenswi-linaro** [comment]
That's what it looks like. I don't suppose it's hard to make it more flexible.

**Comment by Neal-liu** [comment]
Is it acceptable to create a configure `CFG_WITH_NEON` to make vfp_a32.S more flexible?
```
diff --git a/core/arch/arm/kernel/vfp_a32.S b/core/arch/arm/kernel/vfp_a32.S
index 00a55e17..e1da4b70 100644
--- a/core/arch/arm/kernel/vfp_a32.S
+++ b/core/arch/arm/kernel/vfp_a32.S
@@ -5,7 +5,9 @@

 #include <asm.S>

+#ifdef CFG_WITH_NEON
        .fpu    neon
+#endif

 /* void vfp_save_extension_regs(uint64_t regs[VFP_NUM_REGS]); */
 FUNC vfp_save_extension_regs , :
```

`CFG_WITH_NEON` would be set to `y` by default.

If yes, I can send a PR.

**Comment by jenswi-linaro** [comment]
The `.fpu    neon` is just to have the assembler accept whatever instructions we have in that .S file. If that is all you have in mind, then I guess it works already without that change. I had the impression that it's actually the registers available which is the critical thing here, but it's long ago since I last looked at this.

**Comment by Neal-liu** [comment]
Sorry for my misunderstanding.

VFPv3 and VFPv4 implementations provide 32 double-precision registers. However, when NEON unit is not present, the top sixteen registers (D16-D31) become optional. Which is mentioned in [Option to specify the FPU](https://developer.arm.com/documentation/den0018/a/Compiling-NEON-Instructions/GCC-command-line-options/Option-to-specify-the-FPU).

Which should be:
```
diff --git a/core/arch/arm/kernel/vfp_a32.S b/core/arch/arm/kernel/vfp_a32.S
index 00a55e17..ef2b4ca9 100644
--- a/core/arch/arm/kernel/vfp_a32.S
+++ b/core/arch/arm/kernel/vfp_a32.S
@@ -10,14 +10,18 @@
 /* void vfp_save_extension_regs(uint64_t regs[VFP_NUM_REGS]); */
 FUNC vfp_save_extension_regs , :
        vstm    r0!, {d0-d15}
+#ifdef CFG_WITH_NEON
        vstm    r0, {d16-d31}
+#endif
        bx      lr
 END_FUNC vfp_save_extension_regs

 /* void vfp_restore_extension_regs(uint64_t regs[VFP_NUM_REGS]); */
 FUNC vfp_restore_extension_regs , :
        vldm    r0!, {d0-d15}
+#ifdef CFG_WITH_NEON
        vldm    r0, {d16-d31}
+#endif
        bx      lr
 END_FUNC vfp_restore_extension_regs
```

`CFG_WITH_NEON ?= y` could be defined at `core/arch/arm/arm.mk`
Platform owner can decide it based on their SoC architecture.

**Comment by jenswi-linaro** [comment]
OK, makes sense. Feel free to propose this in a pull request.

**Comment by Neal-liu** [comment]
I provide another solution to make it more flexible, please check PR #5285 for more details.
Thanks

**Comment by Neal-liu** [comment]
Problem solved with https://github.com/OP-TEE/optee_os/pull/5285, thanks for your time.
