### ISSUE TITLE
Xilinx ZCU102 hangs on BL31 on OP-TEE 3.16.0

### ISSUE THREAD

**Issue by abhkr24** [OP-TEE/optee_os#5264]
Hello. I want to upgrade my OP-TEE setup to the latest (3.15.0 or above) to include pkcs11 TA.
I was able to boot 3.7.0 with the below:
- Copy tee.bin as bl32.elf
- ARM_TRUSTED_FIRMWARE_MAKE_OPTE += BL32=tee-header_v2.bin\
				  BL32_EXTRA1=$(XILINX_ATF_OPTEE_TEE_PAGER_BIN)\
				  BL32_EXTRA2=$(XILINX_ATF_OPTEE_TEE_PAGABLE_BIN)\
				  SPD=opteed
And I have bl32.elf in the final boot.bif. Which completes my traditional boot sequence of BL31(ATF) -> BL32(OP-TEE) -> BL33(U-Boot) -> Kernel.

However, the same flow does not seem to work for 3.15.0. It hangs at the BL31 stage:
Xilinx Zynq MP First Stage Boot Loader
Release 2020.2   Apr  12 2022  -  00:00:00
.
.
.
Authentication Enabled
Header validation/authentication successful
PMU Firmware 2020.2     Apr 12 2022   00:00:00
PMU_ROM Version: xpbr-v8.1.0-0
NOTICE:  ATF running on XCZU2EG/silicon v4/RTL5.1 at 0x1000
NOTICE:  BL31: v2.2(release):reproducible
NOTICE:  BL31: Built : 00:00:00, Apr  12 2022

Is there any change in the way op-tee 3.16.0 is built? Many thanks for your response.

**Comment by ricardosalveti** [comment]
Can you test with the OP-TEE tee-pager_v2.bin binary? I don't use FSBL (SPL instead), and I can confirm that loading tee-pager_v2.bin (3.15/3.16) works fine on the zynqmp devices I got (after changing ATF to build with SPD=opteed, which you already added).

**Comment by abhkr24** [comment]
@ricardosalveti Testing now. I will update here once I test the build.

**Comment by abhkr24** [comment]
Unfortunately, this did not solve my problem :( 
What is weird is that when using tee-pager_v2.bin for bl32, my board does not boot up. 
(Also, for 3.7.0 op-tee I am using _**tee.elf**_ as bl32.elf and not tee.bin)

**Comment by abhkr24** [comment]
It turns out y bif generator does not go too well with a .bin file. So I cannot directly add tee-pager_v2.bin as bl32 in my boot.bif. Is there a way to convert tee-pager_v2.bin to an _elf_ ? I tried using objcopy with _-O elf64-littleaarch64 -B arm_
But that does not seem to include all sections. @ricardosalveti would you know if any other flags are needed while converting the bin to an elf?
