### ISSUE TITLE
Check return value of crypto syscalls before assigning buffer pointers

### ISSUE THREAD

**Issue by Sadiq1811** [OP-TEE/optee_os#5268]
Hello,
https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_operations.c#L1655 is assigned without checking if res is `TEE_SUCCESS`
Same applies to the following:
(i) https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_operations.c#L1692
(ii) https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_operations.c#L1730
(iii) https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_operations.c#L815
(iv) https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_operations.c#L1039
(v) https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_operations.c#L1232
(vi) https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_operations.c#L1525

**Comment by jenswi-linaro** [comment]
In some cases there's an updated value on error, for example with a short buffer.

**Comment by Sadiq1811** [comment]
Okay.
So if i'm not wrong, this assignment is fine?

**Comment by etienne-lms** [comment]
@jenswi-linaro, as you mentioned, `TEE_SUCCESS` and `TEE_ERROR_SHORT_BUFFER` are expected to return an update buffer size value but I don't think only error code should do so. From the listed pointers, it looks like
https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_operations.c#L1655
and https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_operations.c#L1692
would need to be fixed to not update the respective `*destlen` value when the error code is `TEE_ERROR_BAD_PARAMETERS`.

**Comment by jenswi-linaro** [comment]
I believe we already have these checks in the syscall implementation.

**Comment by Sadiq1811** [comment]
@jenswi-linaro you mean the check being done is https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_svc_cryp.c#L3730 ?

**Comment by jenswi-linaro** [comment]
Yes, we must do it there anyway to make sure that we don't leak junk.

**Comment by Sadiq1811** [comment]
Sure, thanks for the clarification.
Shall be closing this issue.
