### ISSUE TITLE
rockchip-rk3399 build error

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#5270]
On current master:

```
$ make -s PLATFORM=rockchip-rk3399
core/arch/arm/plat-rockchip/main.c: In function ‘main_init_gic’:
core/arch/arm/plat-rockchip/main.c:29:29: error: ‘GICC_BASE’ undeclared (first use in this function); did you mean ‘GIC_BASE’?
   29 |         gic_init(&gic_data, GICC_BASE, GICD_BASE);
      |                             ^~~~~~~~~
      |                             GIC_BASE
```

**Comment by jforissier** [comment]
@lorc I just gave a quick look, prior to 608016966 `gic_init()` would be called with a NULL VA when `CFG_ARM_GICV3 != y`, but now it takes a PA which may not be NULL AFAICT so what's the fix?

This platform should probably be added to the CI build, too.

**Comment by jenswi-linaro** [comment]
This PR https://github.com/OP-TEE/optee_os/pull/5265 is relevant too.

**Comment by jforissier** [comment]
@lorc no worries, these things happen especially when CI is lacking -- you can't be expected to build all platforms manually.

>  I can see, most platform define `GICC_BASE` even if it is not used.

I'll do that, thanks.

@jenswi-linaro 

> The PR #5265 is relevant too.

Thanks for the reminder. I'll take it in the release too.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/5271
