### ISSUE TITLE
Question about how to reference the Openssl library

### ISSUE THREAD

**Issue by capgeorge** [OP-TEE/optee_os#5278]
Hello, I just started to learn the development of Optee recently.
 In my plan, I will use functions from the OpenSSL library to implement an elliptic curve encryption algorithm that has been proven outside of Optee.
However, when I put the modified code into the CA and TA, I get an error at compile time  : " <openssl/ec.h>:no such file or directory>,I'm sure I have OpenSSL installed correctly on my computer.
How do I correctly reference openSSL library functions to make my code run ?
Thank you in advance

**Comment by jforissier** [comment]
Hello @capgeorge,

The short answer to your question is "it depends..." on your build environment. Assuming you're building for the QEMUv8 target as explained in https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8, here is how you can add OpenSSL to the "Hello World" example application:

In `build`:
```diff
diff --git a/br-ext/package/optee_examples_ext/optee_examples_ext.mk b/br-ext/package/optee_examples_ext/optee_examples_ext.mk
index b4bbf42..18456e0 100644
--- a/br-ext/package/optee_examples_ext/optee_examples_ext.mk
+++ b/br-ext/package/optee_examples_ext/optee_examples_ext.mk
@@ -3,7 +3,7 @@ OPTEE_EXAMPLES_EXT_SOURCE = local
 OPTEE_EXAMPLES_EXT_SITE = $(BR2_PACKAGE_OPTEE_EXAMPLES_EXT_SITE)
 OPTEE_EXAMPLES_EXT_SITE_METHOD = local
 OPTEE_EXAMPLES_EXT_INSTALL_STAGING = YES
-OPTEE_EXAMPLES_EXT_DEPENDENCIES = optee_client_ext host-python3-pycryptodomex host-python-cryptography
+OPTEE_EXAMPLES_EXT_DEPENDENCIES = optee_client_ext host-python3-pycryptodomex host-python-cryptography openssl
 OPTEE_EXAMPLES_EXT_SDK = $(BR2_PACKAGE_OPTEE_EXAMPLES_EXT_SDK)
 OPTEE_EXAMPLES_EXT_CONF_OPTS = -DOPTEE_EXAMPLES_SDK=$(OPTEE_EXAMPLES_EXT_SDK)
 ```
In `optee_examples`:
```diff
diff --git a/hello_world/CMakeLists.txt b/hello_world/CMakeLists.txt
index 937b8cf..11cb5da 100644
--- a/hello_world/CMakeLists.txt
+++ b/hello_world/CMakeLists.txt
@@ -8,6 +8,9 @@ target_include_directories(${PROJECT_NAME}
 			   PRIVATE ta/include
 			   PRIVATE include)
 
-target_link_libraries (${PROJECT_NAME} PRIVATE teec)
+set(OPENSSL_USE_STATIC_LIBS TRUE)
+find_package(OpenSSL REQUIRED)
+
+target_link_libraries (${PROJECT_NAME} PRIVATE teec OpenSSL::Crypto)
 
 install (TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_BINDIR})
```

As for the TA, you can't use OpenSSL. There is no version of that library ported to the OP-TEE TA environment that I know of. You may use MBed TLS instead (which is readily available with OP-TEE).

**Comment by capgeorge** [comment]
Thank you very much for your help. By the way, I am using Qemuv7

**Comment by jforissier** [comment]
> By the way, I am using Qemuv7

It is very similar so what I said should be applicable, too.

**Comment by capgeorge** [comment]
Thank you. I think I get it
