### ISSUE TITLE
Questions about GetObjectValueAttribute

### ISSUE THREAD

**Issue by capgeorge** [OP-TEE/optee_os#5287]
Hello!    I recently started learning OPTEE, trying to write a program in TA that generates sm2 key pairs and encrypts with them.   It worked fine at first, but when I added the GetObjectValueAttribute () function and tried to print the generated key information on the TA console, it gave an error code 0xFFFF0006,  This means the parameter is wrong, I don't understand where the problem is, could you help me to check it?    Thank you very much!

And this is the code in question  
`

TEE_Result SM2_create_key_pair(void *session) 
{
	TEE_Result ret;
	size_t key_size = SM2_KEY_SIZE;
	unsigned char pri_key[32];
	struct sm2_session *sess = (struct sm2_session *)session;
	TEE_Attribute attr;

	ret = TEE_AllocateTransientObject(TEE_TYPE_SM2_PKE_KEYPAIR, key_size, &sess->key_handle);
	if (ret != TEE_SUCCESS) {
		EMSG("\nFailed to alloc transient object handle: 0x%x\n", ret);
		return ret;
	}
	DMSG("\n========== Transient object allocated. ==========\n");

	ret = TEE_GenerateKey(sess->key_handle, key_size, (TEE_Attribute *)NULL, 0);
	if (ret != TEE_SUCCESS) {
		EMSG("\nFailed to generate keys: 0x%x\n", ret);
		return ret;
	}
	DMSG("\n========== Keys generated. ==========\n");

	ret=TEE_GetObjectValueAttribute(sess->key_handle,TEE_ATTR_ECC_PRIVATE_VALUE,&attr.content.value.a,(uint32_t *)NULL);
	if (ret != TEE_SUCCESS) {
		EMSG("\nFailed to get pri_key value: 0x%x\n", ret);
		return ret;
	}
	DMSG("\n========== Get Key Information to attrs. ==========\n");

	memcpy(pri_key,attr3.content.value.a,key_size);
	DMSG("\n========== Pri_key1 is : %s ==========\n",pri_key);
	return ret;
}

`

**Comment by jforissier** [comment]
Hello @capgeorge,

You need to use `TEE_GetObjectBufferAttribute()` to get the private key. It will return a 256 bit value (32 bytes).

**Comment by capgeorge** [comment]
Thanks. I'll try it back @jforissier

**Comment by capgeorge** [comment]
Hello, I tried to replace it with TEE_GetObjectBufferAttribute(), but it still doesn't work properly.The TA console output is“0 TA panicked with code 0x0”

**Comment by jforissier** [comment]
Please try this code: https://github.com/OP-TEE/optee_os/issues/5211#issuecomment-1062822582.
It should work. Remove the call to `TEE_InitValueAttribute();` because it is incorrect. Make sure you are using the latest version of OP-TEE.

**Comment by capgeorge** [comment]
Thanks. I'll try it back @jforissier

**Comment by capgeorge** [comment]
It worked. Thank you very much for your help
