### ISSUE TITLE
Questions about TEE_InitRefAttribute()

### ISSUE THREAD

**Issue by capgeorge** [OP-TEE/optee_os#5290]
Hello! I recently started learning OPTEE, trying to write a program in TA that use sm2 key pairs sent by CA to create an SM2 key pair object handle. I'm just imaitating what GPD_TEE_Internal_Core_API_Specifiction_V1.2 gave me(code below).But the TA console gave an error code 0xFFFF0008, This means the item not found, I don't understand where the problem is, could you help me to check it? Thank you very much!

```
        TEE_Attribute attrs[3];
        TEE_AllocateTransientObject(TEE_TYPE_SM2_PKE_KEYPAIR, key_size, &sess->key_handle);
	TEE_InitRefAttribute(&attrs[0],TEE_ATTR_ECC_PUBLIC_VALUE_X,pub_key_x,pub_key_x_len);
	TEE_InitRefAttribute(&attrs[1],TEE_ATTR_ECC_PUBLIC_VALUE_Y,pub_key_y,pub_key_y_len);
	TEE_InitRefAttribute(&attrs[2],TEE_ATTR_ECC_PRIVATE_VALUE,pri_key,pri_key_len);
	TEE_GenerateKey(sess->key_handle,SM2_KEY_SIZE,attrs,sizeof(attrs)/sizeof(TEE_Attribute));
```

**Comment by capgeorge** [comment]
By the way , the example given in GPD_TEE_Internal_Core_API_Specifiction_V1.2 is:
```
TEE_Attrbute attrs[3];
TEE_InitRefAttribute(&attrs[0],TEE_ATTR_DH_PRIME,&p,len);
TEE_InitRefAttribute(&attrs[1],TEE_ATTR_DH_BASE,&g,len);
TEE_InitValueAttribute(&attrs[2],TEE_ATTR_DH_X_BITS,xBits,0);
TEE_GenerateKey(key,1024,attrs,sizeof(attrs)/sizeof(TEE_Attribute));
```

**Comment by etienne-lms** [comment]
> (...) But the TA console gave an error code 0xFFFF0008 (...)

`TEE_GenerateKey()` expects no attribute parameters for `TEE_TYPE_SM2_KEP_KEYPAIR`. See TEE Internal Core API spec v1.2, Table 5-12: TEE_GenerateKey Parameters:
"TEE_TYPE_SM2_KEP_KEYPAIR | No parameter is required"

If you want to create a TEE key object in a TA from an already generated key, then you need to use `TEE_PopulateTransientObject()`, not `TEE_GenerateKey()` in the sequence above.



> By the way , the example given in GPD_TEE_Internal_Core_API_Specifiction_V1.2 is:
> (...)

This is an example for related to a DH key, not an SM2 key.

**Comment by capgeorge** [comment]
Thanks. I'll try it back @etienne-lms
