### ISSUE TITLE
operations before Normal world starts

### ISSUE THREAD

**Issue by AntonioSanta** [OP-TEE/optee_os#5294]

**Comment by lorc** [comment]
Are you sure that this is OP-TEE responsibility?

Bear in mind, that there is ARM Trusted Firmware, which boots before OP-TEE. As far as I know, ATF already have means to check binaries before booting them.

**Comment by gagachang** [comment]
If the operations are only for boot stage of secure world, implements them in platform specific folder is enough.
You can just invoke the operations in platform initialization.

If the operations need to be available for both secure world and normal world,
how about implementing the operations as a driver, and writing a TA or PTA as a interface to use them?
The platform initialization in secure world can invoke the driver, and the normal world invokes the TA or PTA to use that driver.

**Comment by AntonioSanta** [comment]
thank you for the replies.
Suppose I want/need to go on with this on OP-TEE
If  the operations I need to do before the normal world starts are just to decrypt a secure object that is in the REE file system under /data/tee and use it, what is the driver to call from the platform code of OP-TEE ? Can OP-TEE read the FS partition on eMMC where /data/tee is located before the normal world starts up ?

**Comment by gagachang** [comment]
Hi @AntonioSanta 

ASAIK, REE file system is mounted after normal world starts.
That is to say, OP-TEE can't access file which is in REE file system before normal world mounts it...

**Comment by AntonioSanta** [comment]
I think it would be possible with some modifications, adding to OP-TEE the required capabilities. That is true also for RPMB as it requires the normal world driver for eMMC controller, as they say on the docs.

**Comment by gagachang** [comment]
It seems you need eMMC driver and file system library.
How about let ATF handles it?
As @lorc said, ATF has eMMC drivers, but it seems you still need file system library to access FS partition.
Maybe let your secure object be part of binary instead of file?

**Comment by jforissier** [comment]
U-Boot has an RPMB driver for OP-TEE.

**Comment by AntonioSanta** [comment]
I'd need to read secure object before U-Boot starts, if doing that from ATF, how can I let a secure object be part of binary instead of file ? where is this done. I'd need to simplify the object format in order to be able to read and decrypt it from ATF.

**Comment by jenswi-linaro** [comment]
If it's read-only access then you could just define another binary blob to keep in the FIP.
It seems that this is more of a TF-A problem than a OP-TEE problem so you'd probably get better help on the TF-A mailing list.
