### ISSUE TITLE
updating for faked_armv7_uta_signed_header.bin 

### ISSUE THREAD

**Issue by angusmart** [OP-TEE/optee_os#530]
we cloned new version optee os and arm-trusted-firmware, and runing in the juno board. when we run the hello world test, and get TEEC_ERROR_SECURITY error in tee_ta_load_header().
whether  faked_armv7_uta_signed_header.bin is too old?
and we are not found new version faked_armv7_uta_signed_header.bin in github.

**Comment by vchong** [comment]
The faked signed header has been replaced with real TA signing. See:
https://github.com/OP-TEE/optee_os/pull/302
https://github.com/OP-TEE/optee_os/pull/396
https://github.com/OP-TEE/optee_os/pull/445

**Comment by jbech-optee-adm** [comment]
@vchong gave a proper answer, closing this issue.
