### ISSUE TITLE
Security of RPMB_KEY

### ISSUE THREAD

**Issue by abhkr24** [OP-TEE/optee_os#5312]
Hello,

My question is similar to the one in #5258
My test board is a zcu102 Xilinx board. I have written PPK0 and PPK1 eFuse. I have CFG_RPMB_WRITE_KEY=y set in optee os.
I know that tee_otp_get_hw_unique_key is the function that ultimately gets the HUK to generate the RPMB key. 
The docs mention this: 

> To allow Secure Storage to operate securely on your platform, you must define implementations in your platform code for:
> 
> void tee_otp_get_hw_unique_key(struct tee_hw_unique_key *hwkey);
> 
> int tee_otp_get_die_id(uint8_t *buffer, size_t len);

But the function for zynqmp already has some implementation: https://github.com/OP-TEE/optee_os/blob/ddb245f324ba2f4238a039f922c9c261064ae2a7/core/drivers/zynqmp_huk.c#L23

which basically does this - 	 The HUK is the SHA-256 DNA eFUSE string AES-GCM encrypted with the PUF KEK using the DNA eFUSE string as the IV.
1. So, am I correct to understand that I do not need to modify anything here for zynqmp? 
2. If question 1 is true, then the function above uses Device DNA eFuse which is written at manufacturing. Is there any other eFuse that I need to set?
3. If question 1 is faluse, the eFuses are accessible from richOS. How does this secret key get generated if we are using the PPK0 eFuse and how does the secret key remain secret? We have access to the eFuse and the function that generates a key from the eFuse - which means the key is easily generatable.
4. Do we need to write the RPMB key by ourselves to the mmc or does optee_os take care of this?

Thanks in advance!

**Comment by jenswi-linaro** [comment]
1-3: Your guess is as good a mine
4: OP-TEE can do that with CFG_RPMB_WRITE_KEY. Note that with CFG_RPMB_WRITE_KEY it's trivial for normal world to trick OP-TEE into revealing the secret key for RPMB.

**Comment by jenswi-linaro** [comment]
Once the key is programmed, make sure that OP-TEE is compiled with CFG_RPMB_WRITE_KEY=n and you should be safe.

**Comment by abhkr24** [comment]
If I compile OP-TEE with CFG_RPMB_WRITE_KEY=n, then should I follow a separate mechanism to write the RPMB key to eMMC as outlined [here](https://github.com/OP-TEE/optee_os/issues/4019#issuecomment-670399576)? 
If someone has access to the eFuses, would it be trivial to generate the RPMB key or is there a secret recipe?

**Comment by jenswi-linaro** [comment]
> If I compile OP-TEE with CFG_RPMB_WRITE_KEY=n, then should I follow a separate mechanism to write the RPMB key to eMMC as outlined [here](https://github.com/OP-TEE/optee_os/issues/4019#issuecomment-670399576)? 

Yes

> If someone has access to the eFuses, would it be trivial to generate the RPMB key or is there a secret recipe?

Yes, for some level of trivial.

**Comment by abhkr24** [comment]
@jenswi-linaro So if in my environment, if the fuses are accessible from Linux, RPMB is not really secure. Correct?
Even for REE FS to be secure, we would need some form of HUK that is not accessible from Linux for it to be truly secure. Otherwise, anyone could generate the keys with a few attempts and be able to access the data. Correct?

**Comment by ricardosalveti** [comment]
In this case linux would have to follow the same process as done by optee (DNA eFUSE string AES-GCM encrypted with the PUF KEK), which at that point depends really on your threat model.

**Comment by ldts** [comment]
to get the HUK you would need to AES-GCM encrypt the PUF KEK. Make sure the PUF KEK is accessible (there is a provisioning tool for that that you should be getting from Xilinx).

**Comment by ldts** [comment]
https://github.com/OP-TEE/optee_os/commit/1d23b02e1ce5665e6552ebd9f8d67883a405cc4e all is explained in the commit and in the PR if you check them

**Comment by ldts** [comment]
some more info here https://docs.foundries.io/latest/reference-manual/security/authentication-xilinx.html#secure-storage-rpmb-using-the-puf
