### ISSUE TITLE
Is there any other feasible way to operate files in REE disk

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#5318]
In addition to the secure storage function, is there any other way for TEE to operate the files in the disk on the REE side?

Can I write a PTA to call some core code, like: tee_fs_rpc_write_init, tee_fs_rpc_truncate ... ?
Does this bring some security risks?

**Comment by jenswi-linaro** [comment]
You can do that from a PTA. Some care will be needed to avoid overwriting files used for secure storage.

**Comment by YogzZ** [comment]
This method works. Thank you for your help.
