### ISSUE TITLE
about secure storage 

### ISSUE THREAD

**Issue by angusmart** [OP-TEE/optee_os#532]
when i invoke function TEE_CreatePersistentObject(), it returns error. and the log as follows:

>`DBG TEE-CORE:read_one_block:721: block_path:40F437826895E41194FA0002A5D5C51B/.31323334353637/block0.1`
>`ERR TEE-CORE:write_one_block:852: Failed to read block`
>`DBG USER-TA:call_gp_rsa_sha1_signature_interface:248: TEE_CreatePersistentObject failed! res: 0xf0100001`

and i found the /data/tee/40F437826895E41194FA0002A5D5C51B/.31323334353637/ folder have no file 'block0.1'

**Comment by m943040028** [comment]
Hi @angusmart , could you test it again with update-to-date optee_os? If the issue is still exist, please provide the full log.

**Comment by jbech-optee-adm** [comment]
Due to inactivity I'm closing the issue, please re-open if you have follow up questions.
