### ISSUE TITLE
Question about TEE_AsymmetricEncrypt()

### ISSUE THREAD

**Issue by capgeorge** [OP-TEE/optee_os#5321]
Hello!  I tried to complete a custom key pair to achieve SM2 encryption and decryption code function in TA side, it was running very well.  But when I took the encrypted result out for decryption, the program panicked (code 0xffff0006), as if because the ciphertext format was not correct.  I wonder if there are any additional formatting requirements for TEE_AsymmetricEncrypt() and TEE_AsymmetricDecrypt() used by OPTEE?  How to use TEE_AsymmetricDecrypt() to decrypt a ciphertext with a known key?

**Comment by capgeorge** [comment]
In my previous attempts, it didn't break when I called TEE_AsymmetricDecrypt() directly to decrypt the result of using the function TEE_AsymmetricEncrypt(),  But I have a problem when I use a string to copy the ciphertext and input it as inbuf TEE_AsymmetricDecrypt(). Through the console output I make sure that the TA end receives the same string. What's the reason?

**Comment by capgeorge** [comment]
Ok, I think the question can be changed to: when selecting sm2-pKE as the algorithm to use, what ciphertext format should be entered by TEE_AsymmetricEncrypt()?

**Comment by jforissier** [comment]
There is no specific format. Asymmetric encryption operates on raw buffers (address, length). The input message is a sequence of bytes which can have any value, and same for the encrypted output. Perhaps you are corrupting the data when manipulating them as character strings? Try to dump the data with `DHEXDUMP(ptr, size);` (clean and rebuild TA with `CFG_TEE_TA_LOG_LEVEL=3`).

**Comment by capgeorge** [comment]
Okay, I'll try it.Thanks for your help! @jforissier

**Comment by capgeorge** [comment]
By the way, how do I use DHEXDUMP(ptr, size)? I can't find it in the GPD_TEE_Internal_Core_API manual @jforissier

**Comment by jforissier** [comment]
It's an OP-TEE specific macro. https://github.com/OP-TEE/optee_os/blob/master/lib/libutils/ext/include/trace.h#L92-L97
You need to `#include <trace.h>`/

**Comment by capgeorge** [comment]
I tried the examples you provided here https://github.nmiku.com/OP-TEE/optee_os/issues/4788, but unfortunately nothing changed. I confirm that I have included <trace.h>, but DHEXDUMP () still doesn't work. I think the problem is that I didn't set “build it with CFG_TEE_TA_LOG_LEVEL=3”,and I wonder how. Sorry, but my data sources are really too few.

**Comment by jforissier** [comment]
When I build for QEMU I do "rm -rf ../out-br/build/optee* ; make -j10 CFG_TEE_TA_LOG_LEVEL=3 run" to make sure TAs are re-built.

**Comment by capgeorge** [comment]
Thank you! By the way, could you please tell me where can I get some common information during the development of OPTEE?
