### ISSUE TITLE
How to run U-boot with enabled caches when loaded after OPTEE-OS

### ISSUE THREAD

**Issue by RNNord2** [OP-TEE/optee_os#5325]
Hi. I used to work with development of an I.MX6 system booting ROM code -> U-boot SPL -> OPTEE-OS -> U-boot -> Linux. U-boot is started with caches off. Now there is an issue that U-boot execution takes to long time (it performs verified boot procedures), so the systems user wants U-boot to run with caches enabled to speed things up. Is there an established method how to do this when using the described boot order? I guess that U-boot have to ask OPTEE-OS to enable the caches? Any guiding to the proper approach to do this is appreciated. The system currently runs OPTEE-OS 3.7.0 and U-boot 2019.07, but upgrades to OPTEE 3.13 and U-boot 2021.07 is close ahead (if that makes any difference).

**Comment by jenswi-linaro** [comment]
I assume you're talking about the external L2 cache. It's actually already enabled at (unless configured with CFG_PL310_SIP_PROTOCOL=y)
https://github.com/OP-TEE/optee_os/blob/8df917f918c5b0b14b92965e198a03868cc9fd26/core/arch/arm/kernel/entry_a32.S#L495-L499

**Comment by RNNord2** [comment]
Thanks for the reply. I will have to check how CFG-PL310 and CFG_PL310_SIP_PROTOCOL are set in our current set-up. But in U-boot we have CONFIG_SYS_ICACHE_OFF, CONFIG_SYS_DCACHE_OFF and CONFIG_SYS_L2CACHE_OFF all set. If I remember correctly, we had issues with having these caches enabled in U-boot because U-boot tried to do some settings not allowed by OP-TEE OS loaded before U-boot.

So, how would be the proper way, with regards to config parameters, to make U-boot run with enabled caches when OP-TEE OS is loaded before U-boot?

**Comment by RNNord2** [comment]
To summarize and close this thread: U-boot should be able to run with enabled caches (CONFIG_SYS_ICACHE_OFF=n, CONFIG_SYS_DCACHE_OFF=n and CONFIG_SYS_L2CACHE_OFF=n) even if OP-TEE OS is loaded and started up before U-boot?

For PL310 related config parameters in OP-TEE, I have:
CFG_PL310_LOCKED=y
CFG_PL310_SIP_PROTOCOL is not set
CFG_PL310=y

**Comment by jenswi-linaro** [comment]
Sure

**Comment by RNNord2** [comment]
This is what happens when starting U-boot after OP-TEE OS, and U-boot configured with CONFIG_SYS_ICACHE_OFF=n, CONFIG_SYS_DCACHE_OFF=n and CONFIG_SYS_L2CACHE_OFF=n:

![image](https://user-images.githubusercontent.com/57798837/170059491-9ee76365-59da-4784-a662-ab3237c5d9ab.png)

The unit resets repeatedly.

**Comment by jenswi-linaro** [comment]
I expect that U-Boot can't touch the configuration registers for the external cache, but it should be able to do cache maintenance. Since you've locked all the cache lines of the external cache I suppose you could just as well compile U-Boot with `CONFIG_SYS_L2CACHE_OFF=y`.

By the way, if you get a data abort it's worth looking at DFAR for the address access that caused it.

**Comment by RNNord2** [comment]
It turns out that we can run with CONFIG_SYS_DCACHE_OFF=n and CONFIG_SYS_ICACHE_OFF=n in U-boot which results in a significant decrease in U-boot execution time. It is not possible to set CONFIG_SYS_L2CACHE_OFF=n however (PL310-access prohibited by OP-TEE OS?), but as @jenswi-linaro suggests, U-boot might as well keep CONFIG_SYS_L2CACHE_OFF=y, especially if the L2 cache is already enabled in OP-TEE OS as suggested above.
