### ISSUE TITLE
query: supporting GCM mode in PKCS11 TA

### ISSUE THREAD

**Issue by ubisun** [OP-TEE/optee_os#5333]
Hello, I have a simple query about PKCS11 TA.

As I know, the Secure Key Service was ported to OPTEE mainline as [Closed Issue#4283](https://github.com/OP-TEE/optee_os/issues/4283)

When I try to find whether AES-GCM mode is supported by PKCS11 TA, I noticed that it isn't supported.
But, the origin [Secure Key Service Github](https://github.com/ricardosalveti/optee-sks) has it.

Is there any reason that GCM mode isn't supported by PKCS11 TA in current mainline?

**Comment by etienne-lms** [comment]
It's not been ported at that time because GCM support was of a lower priority. If you need this algorithm, please feel free to create a P-R to implement it, based on previous SKS work or not, up to you. We will be happy to review it and eventually add that support to the pkcs11 TA.
