### ISSUE TITLE
How to create a CA-TA model

### ISSUE THREAD

**Issue by shumeigiku** [OP-TEE/optee_os#5343]
Hi all,

I am learning how to create a CA-TA model with the provided example (https://github.com/linaro-swg/optee_examples)
Now I build the binary of CA and TA of a HelloWorld, and the binary libs of optee_client. 
The REE runs a Linux v4.9, with the binary of CA and lib of optee_client (libteec.so, libckteec.so) under the root directory.
The TEE runs a OP-TEE, but without the Helloworld TA.

Now I want to execute the Helloworld CA, then I wish the TA can reply something. I think I may address the following troubles:
1. How to link the Helloworld CA with the lib of optee_client under the REE?
2. How to integrate the Helloworld TA binary into the OP-TEE? Should I re-write one and compile it into the raw OP-TEE? Or can it be dynamically located into the OP-TEE?

Sincerely,
shumeigiku

**Comment by etienne-lms** [comment]
> 1. How to link the Helloworld CA with the lib of optee_client under the REE?

Helloworld application (CA) build process links it with libteec (from [_CmakeList.txt_](https://github.com/linaro-swg/optee_examples/blob/master/hello_world/CMakeLists.txt#L11), [_Makefile_](https://github.com/linaro-swg/optee_examples/blob/3.17.0/hello_world/host/Makefile#L11-L13) or [_Android.mk_](https://github.com/linaro-swg/optee_examples/blob/master/hello_world/Android.mk#L12)). At runtime, if libteec.so is embedded in the rootfs, _optee_example_hello_world_ should link to it automatically.

> How to integrate the Helloworld TA binary into the OP-TEE? Should I re-write one and compile it into the raw OP-TEE? Or can it be dynamically located into the OP-TEE?

The easiest way is the copy the TA binary file (for helloworld: _8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta_) into your rootfs  directory _/lib/optee_armtz/_. It will be found and loaded into OP-TEE secure world when one opens a session toward the TA, as stated in to documentation's [FAQ](https://optee.readthedocs.io/en/latest/faq/faq.html?highlight=optee_armtz#q-where-should-i-put-my-compiled-trusted-application-on-the-device).

If you build OP-TEE from OP-TEE/manifest (see https://optee.readthedocs.io/en/latest/building/index.html), optee_examples CAs and TAs should all be embedded into the target rootfs (e.g. _/usr/lib/optee_example_xxx_ and _/lib/optee_armtz/xxxxx.ta_).

Another way to embed a TA into OP-TEE is at build time. Once your TA is built, you can set the path of the TA ELF file in config switch `EARLY_TA_PATHS` and build optee_os with. The TA binary will be embedded into OP-TEE core image and found there when one opens a session toward the TA.

**Comment by shumeigiku** [comment]
> If you build OP-TEE from OP-TEE/manifest (see https://optee.readthedocs.io/en/latest/building/index.html), optee_examples CAs and TAs should all be embedded into the target rootfs (e.g. _/usr/lib/optee_example_xxx_ and _/lib/optee_armtz/xxxxx.ta_).

Thanks for your reply!
But it seems that I don't have the "/lib/optee_armtz", maybe neither the OPTEE driver in rootfs.
My Linuxv4.9 is downloaded from (https://github.com/torvalds/linux), how can I use the OPTEE lib and driver in REE?

**Comment by shumeigiku** [comment]
> > If you build OP-TEE from OP-TEE/manifest (see https://optee.readthedocs.io/en/latest/building/index.html), optee_examples CAs and TAs should all be embedded into the target rootfs (e.g. _/usr/lib/optee_example_xxx_ and _/lib/optee_armtz/xxxxx.ta_).
> 
> Thanks for your reply! But it seems that I don't have the "/lib/optee_armtz", maybe neither the OPTEE driver in rootfs. My Linuxv4.9 is downloaded from (https://github.com/torvalds/linux), how can I use the OPTEE lib and driver in REE?

I recently change a general linux kernel as v5.3.0, with the following configs

# CONFIG_FPGA is not set
# CONFIG_FSI is not set
CONFIG_TEE=y

#
# TEE drivers
#
CONFIG_OPTEE=y
CONFIG_OPTEE_SHM_NUM_PRIV_PAGES=1
# end of TEE drivers

But I still cannot find the /lib/optee_armtz. Also, I cannot find the /dev/tee0.
Can someone help me?

**Comment by jenswi-linaro** [comment]
I'd recommend starting from something known to work, for instance https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8
