### ISSUE TITLE
Sending data via socket fails and hangs the TA

### ISSUE THREAD

**Issue by psiquo** [OP-TEE/optee_os#5346]
Hi,

I'm developing an application using Optee-OS, what I'm trying to do is to send data over a socket to monitor a running program.

I've followed the example at [https://github.com/OP-TEE/optee_test/blob/master/ta/socket/ta_entry.c#L144](https://github.com/OP-TEE/optee_test/blob/master/ta/socket/ta_entry.c`)

and it resulted in the following:
```C
static TEE_Result ta_entry_tcp_open(){

	TEE_Result res = TEE_ERROR_GENERIC;
	struct sock_handle h = { };
	TEE_tcpSocket_Setup setup = { };

	uint32_t *protocolErr;

	setup.ipVersion = TEE_IP_VERSION_DC;
	setup.server_port = 8080;
	setup.server_addr = "172.17.0.1";
	if (!setup.server_addr)
		return TEE_ERROR_OUT_OF_MEMORY;

	h.socket = TEE_tcpSocket;
	res = h.socket->open(&h.ctx, &setup, &protocolErr);
	//free(setup.server_addr);
	if (res == TEE_SUCCESS) {
		/*
			* 	TEE_Result (*send)(TEE_iSocketHandle ctx, const void *buf, uint32_t *length, uint32_t timeout);
		*/
		IMSG("[*]SOCKET OPENED!!!!!!!!!!!!!\n");	
		}
	char message[] = "message";
	uint32_t size = 8;
	TEE_Result send_res = h.socket->send(&h.ctx, message,&size, 0);
	if(send_res == TEE_SUCCESS) IMSG("Sent data\n");

	return res;
}
```

The problem is the following: the socket opens properly but no data is sent and the TA hangs ( I've tried to change the timeout from 0 to other values but the behavior is the same).

I've looked through the documentation but I haven't found anything relevant, does anyone know what I'm doing wrong?

Output of netcat:
![Screenshot from 2022-05-20 15-57-47](https://user-images.githubusercontent.com/33759674/169568759-23037548-21b6-458f-9500-fa344eb80cb9.png)

Output of the TA:
![Screenshot from 2022-05-20 15-53-35](https://user-images.githubusercontent.com/33759674/169568764-94ebaaba-518f-4336-a213-f74ef91cc128.png)

**Comment by esaurimentocronico** [comment]
Hi Optee group, based on my previous thread https://github.com/OP-TEE/optee_os/issues/5250 i am interested in it too because i have been still having the same problem.

Thank you

**Comment by jenswi-linaro** [comment]
The socket stuff ends up in https://github.com/OP-TEE/optee_client/blob/master/tee-supplicant/src/tee_socket.c
You could try to add a few prints in that file to see what's going on. You may need to kill tee-supplicant and start it again without the -d switch to get output on the console.

**Comment by hallowsman** [comment]
@psiquo 请问这个问题最后是怎么解决的呢？？

**Comment by hallowsman** [comment]
The problem is the following: the socket opens properly but no data is sent and the TA hangs 我遇到的现象和这个一样

**Comment by hallowsman** [comment]
请问这个问题最后是怎么解决的？
