### ISSUE TITLE
ftpm_tee_probe failed when trying to create a session

### ISSUE THREAD

**Issue by kuldeepmarker-eaton** [OP-TEE/optee_os#5347]
HI, I am trying to execute fTPM as a TA in OPTEE. I have build the fTPM as a TA using a yocto recipe. I am using OPENSTLINUX distro and my boad is stm32mp157f-dk2. I have configured the kernel config to enable TPM_FTPM_TEE driver and also the fTPM TA is getting build and I can see it in /lib/optee_armtz folder. I have also modified the device tree for the board to create an entry for tpm@0. When I boot the board I am getting below logs where in the TEE_CLIENT_OPEN_SESSION failed.

[   35.656290] Bluetooth: hci0: BCM43430A1 'brcm/BCM43430A1.hcd' Patch
[   35.724523] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   35.900595] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   36.179999] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   36.290162] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Feb 16 2020 22:39:24 version 7.45.98.97 (r724416 CY) FWID 01-bf41ed64
[   36.324120] Bluetooth: hci0: BCM4343WA1 37.4MHz Murata Type-1DX BT4.2-0093
[   36.329791] Bluetooth: hci0: BCM43430A1 (001.002.009) build 0395
E/LD:  init_elf:437 sys_open_ta_bin(bc50d971-d4c9-42c4-82cb-343fb7f37896)
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff000c
[   36.409300] ftpm-tee tpm@0: ftpm_tee_probe: tee_client_open_session failed, err=ffff000c
[   36.416048] ftpm-tee: probe of tpm@0 failed with error -22
[   36.783842] cs42l51 0-004a: Cirrus Logic CS42L51, Revision: 01

I have checked the return code and it says that TEEC_OUT_OF_MEMORY. I have configured the size of #define CFG_TZDRAM_SIZE 0x01e00000. So could you please help me out here.

**Comment by jforissier** [comment]
Hello @kuldeepmarker-eaton,

I suspect `tee-supplicant` is not yet running when the kernel tries to open a session to the fTPM TA, and therefore the TA cannot be loaded from the root fs. I also think `TEEC_OUT_OF_MEMORY` is misleading; OP-TEE is probably trying to allocate some buffer with the help of `tee-supplicant` at that point.

**Comment by jforissier** [comment]
On the platform I am currently working on (RockPi4B):
- the fTPM TA is an [early TA](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#early-ta) so that it doesn't need to be loaded from the root filesystem (it is readily available after OP-TEE initialization)
- OP-TEE is configured to use RPMB only (`CFG_REE_FS=n CFG_RPMB_FS=y`) and `tee-supplicant` is started by the initramfs. This way the fTPM TA can access secure storage before the root filesystem is mounted.

**Comment by kuldeepmarker-eaton** [comment]
Thanks @jforissier for your inputs so do you think I have to be concerned here. And also I wanted to know how did you tested fTPM TA using OPTEE client API.

**Comment by jforissier** [comment]
> Thanks @jforissier for your inputs so do you think I have to be concerned here.

Well it depends on what you expect I suppose ;-)

> And also I wanted to know how did you tested fTPM TA using OPTEE client API.

I don't know the details about the fTPM, but AFAIK the TA is called by the Linux TPM driver. On my board I consider that all is well when I see no error message on boot and the following command prints out some measurements:
```
$ sudo tpm2_eventlog /sys/kernel/security/tpm0/binary_bios_measurements
```

**Comment by kuldeepmarker-eaton** [comment]
HI @jforissier ,

I have appended tpm2 as a feature in my distro and after the flashing the image on board I am not seeing tpm2_eventlog in my /usr/bin folder. Any idea what am I missing here. Below is the list of tpm2 commands in my /usr/bin folder. Also I am not seeing  tpm0 entry in /sys/kernel/security/. As a result of this I am not able to test fTPM TA.

root@stm32mp1:~# ls /usr/bin/ | grep "tpm"
tpm2_activatecredential
tpm2_certify
tpm2_certifycreation
tpm2_changeauth
tpm2_changeeps
tpm2_changepps
tpm2_checkquote
tpm2_clear
tpm2_clearcontrol
tpm2_clockrateadjust
tpm2_create
tpm2_createak
tpm2_createek
tpm2_createpolicy
tpm2_createprimary
tpm2_dictionarylockout
tpm2_duplicate
tpm2_encryptdecrypt
tpm2_evictcontrol
tpm2_flushcontext
tpm2_getcap
tpm2_getekcertificate
tpm2_getrandom
tpm2_gettestresult
tpm2_gettime
tpm2_hash
tpm2_hierarchycontrol
tpm2_hmac
tpm2_import
tpm2_incrementalselftest
tpm2_load
tpm2_loadexternal
tpm2_makecredential
tpm2_nvcertify
tpm2_nvdefine
tpm2_nvextend
tpm2_nvincrement
tpm2_nvread
tpm2_nvreadlock
tpm2_nvreadpublic
tpm2_nvsetbits
tpm2_nvundefine
tpm2_nvwrite
tpm2_nvwritelock
tpm2_pcrallocate
tpm2_pcrevent
tpm2_pcrextend
tpm2_pcrread
tpm2_pcrreset
tpm2_policyauthorize
tpm2_policyauthorizenv
tpm2_policyauthvalue
tpm2_policycommandcode
tpm2_policycountertimer
tpm2_policyduplicationselect
tpm2_policylocality
tpm2_policynamehash
tpm2_policynv
tpm2_policynvwritten
tpm2_policyor
tpm2_policypassword
tpm2_policypcr
tpm2_policyrestart
tpm2_policysecret
tpm2_policysigned
tpm2_policytemplate
tpm2_policyticket
tpm2_print
tpm2_quote
tpm2_rc_decode
tpm2_readclock
tpm2_readpublic
tpm2_rsadecrypt
tpm2_rsaencrypt
tpm2_selftest
tpm2_send
tpm2_setclock
tpm2_setprimarypolicy
tpm2_shutdown
tpm2_sign
tpm2_startauthsession
tpm2_startup
tpm2_stirrandom
tpm2_testparms
tpm2_unseal
tpm2_verifysignature
tpm_server
