### ISSUE TITLE
How to test fTPM TA from user space

### ISSUE THREAD

**Issue by kuldeepmarker-eaton** [OP-TEE/optee_os#5353]
I have build fTPM TA and is available in my /lib/optee_armtz folder. Now I need to test this TA from user space. I have gone through optee-examples but I can't figure out how can I add a new example which can test fTPM. So could you please provide some pointers as how I should proceed,

**Comment by etienne-lms** [comment]
@kuldeepmarker-eaton, is it ok to close this issue? It seems addressed by https://github.com/OP-TEE/optee_os/issues/5378.
