### ISSUE TITLE
failed to find an OP-TEE supplicant  device

### ISSUE THREAD

**Issue by Xiexijin** [OP-TEE/optee_os#5358]
**I tried to run xtest on rock pi 4b, but this error occurred when I started tee supplicant:**

`rock@rockpi-4b:~$ tee-supplicant &                                             
[1] 831                                                                        
rock@rockpi-4b:~$ ERR [831] TSUP:main:723: failed to find an OP-TEE supplicant 
device                                                                         
                                                                               
[1]+  Exit 1                  tee-supplicant                                   
rock@rockpi-4b:~$ ps | grep supplicant                                         
rock@rockpi-4b:~$ dmesg | grep optee                                           
[    2.415121] optee: probing for conduit method.                              
[    2.415553] optee: revision 3.16 (d0b742d1)                                 
[    2.415861] optee: dynamic shared memory is enabled                         
[    2.417018] optee: initialized driver                                       
rock@rockpi-4b:~$ ls /dev/*tee*                                                
/dev/tee0  /dev/teepriv0`

How can I solve this problem?

**Comment by jforissier** [comment]
Hi,

You need to run tee-supplicant as root. The message is misleading, it could be improved when a device is found but it can't be opened.

**Comment by Xiexijin** [comment]
@jforissier 
**The result was strange**
rock@rockpi-4b:~$ sudo tee-supplicant &                                       
[1] 833                                                                       
rock@rockpi-4b:~$ sudo tee-supplicant &                                       
[2] 834                                                                                                                                                 
[1]+  Stopped                 sudo tee-supplicant 
**Has tee supplicant been started?**
