### ISSUE TITLE
Verifying the control flow of the Linux kernel from the secure world

### ISSUE THREAD

**Issue by akorb** [OP-TEE/optee_os#5362]
## Use case
I want to verify the control flow of the Linux kernel running in the normal world from the secure world on an ARM (AArch64) machine.

## Problem
I do not trust the OS kernel to provide me with its control flow (e.g., with `ftrace`).

## Idea
My idea is to receive the CoreSight traces directly from within the secure world. As far as I understood, each device on an ARM SoC is either in the SW or the NW. Therefore, it should theoretically be possible to access the CoreSight peripherals exclusively from the SW if configured accordingly.

## Questions
While Linux itself [provides interfaces for ARM CoreSight](https://docs.kernel.org/trace/coresight/coresight.html), I think this does not help me as I do not trust the kernel.
Therefore, I guess my approach would require an ARM CoreSight implementation in OP-TEE Core, am I right?

Also, I suspect that this violates the nature of trusted applications, since it is a continuous process, not an event-driven one.

**Comment by akorb** [comment]
That's what I thought. So, my guess that I would need to access the ARM CoreSight interfaces in OP-TEE is correct?

**Comment by jenswi-linaro** [comment]
Except that it's pointless. Since whatever you do in user space can't be trusted anyway if you can't trust the kernel. I seems I'm missing some point.

**Comment by akorb** [comment]
I do not trust the Linux kernel in NW, but I trust OP-TEE in the SW (its TAs and OP-TEE core). So, I guess I need to access the ARM CoreSight interfaces from the SW, i.e., OP-TEE.

**Comment by jenswi-linaro** [comment]
Where are you going to interpret the result of this, in normal world? I still don't get it.

**Comment by akorb** [comment]
I would interpret it in the SW.
The kernel in the NW produces the control flow data for CoreSight. I guess it would make sense to implement an interface for OP-TEE which allows a TA to get the CoreSight data. This TA would also verify/interpret the data.

So, the control flow would be forwarded like this:
kernel OS (producer) --> ARM CoreSight -> OP-TEE -> TA (verifier)

**Comment by jenswi-linaro** [comment]
Got it now, thanks for your patience.

I guess you'll need to make CoreSight secure only or the kernel can perhaps tamper with it. You'll need some support in OP-TEE Core and add a PTA providing an interface to TAs.

I'm not sure how strong this verification would be. What if the kernel uses some dummy mapping to make it look like it does what it's supposed to do while in reality doing nothing or something else? I suppose it's still better than nothing in your use case.
