### ISSUE TITLE
Linking libatomic in OPTEE TA

### ISSUE THREAD

**Issue by seanedmond** [OP-TEE/optee_os#5371]
I'm having some trouble linking the follow code in an OPTEE TA:

```c
    return __atomic_compare_exchange(
        (__int128 *)destination,    // ptr
        (__int128 *)expectedValue,  // expected
        (__int128 *)desiredValue,   // desired
        FALSE,                      // weak (set to FALSE => strong)
        __ATOMIC_RELAXED,           // success_memorder
        __ATOMIC_RELAXED);          // failure_memorder
  ```
        
       
I'm getting the following error:
"undefined reference to `__atomic_compare_exchange_16'"

Note:
- I can compile on my platform outside of OPTEE on my platform by adding "-latomic" to the make command
- OPTEE TA is able to link fine to __atomic_compare_exchange_8

 I'm building with a sub.mk.  Is it possible to link libatomic in an OPTEE TA?  Can I modify my sub.mk to ensure this is linked properly?

**Comment by jforissier** [comment]
HI @seanedmond,

You can add libraries to the link via the `LDADD` variable in the TA Makefile, see https://github.com/OP-TEE/optee_test/blob/3.17.0/ta/os_test/Makefile#L9.

That being said, you need a library that is compatible with the OP-TEE TA environment -- in other words, built from source using the "TA dev kit". The library can't be linked against the Linux libc or any other Linux library for example.

Moreover, you should not need actual atomic operations in a TA. TAs are single-threaded and are not re-entered, as required by the GlobalPlatform specification. So you could easily replace `__atomic_compare_exchange(dest, expected, desired)` with its non-atomic equivalent. Perhaps your source code even has a non-threaded version to begin with? (configuration option?).

HTH.
