### ISSUE TITLE
How to dynamically add memory mapping and manipulate it in OPTEE?

### ISSUE THREAD

**Issue by shumeigiku** [OP-TEE/optee_os#5374]
Hi all,

I want to dynamically add a memory mapping for a OP-TEE kernel. 
For instance, I have a physical region 0xa000_0000 - 0xa000_4000, and I set the TZASC to allow the secure world to access it, but Non-secure world cannot (So it is not the "shared memory" situation).
Now I want to create a VA->PA mapping for this 16KB region in OP-TEE. And if better, I wish to dynamically cancel the mapping in the future.
Once I create the mapping, I also want a function that can create a 16KB buffer and map to the region, so I can handle the buffer to read/write the region.

Any functions could I use?

Sincerely,
Shumeigiku

**Comment by shumeigiku** [comment]
Thanks for your help, it works!

BTW, I want to ask another question about the memory manipulation:
1. Does OP-TEE provide some solutions to copy memory from (1) virtual_addr src-> virtual_addr dst, and (2) physical_addr src-> physical_addr dst? I am not sure which type memcpy() supports.

**Comment by etienne-lms** [comment]
When MMU is enable, `memcpy()` will operate only on virtual addresses. When MMU is disable, the function will operate only on physical addresses. See [`phys_to_virt()`](https://elixir.bootlin.com/op-tee/3.17.0/source/core/include/mm/core_memprot.h#L70) to convert a physical address range into its mapped virtual address range.
