### ISSUE TITLE
How to extend the maximum amount of memory usable by TA?

### ISSUE THREAD

**Issue by liangpig1** [OP-TEE/optee_os#538]
Hey, guys. 
I'm recently programming a TA that needs to allocate a relatively large amount of memory. 
After setting the macro TA_DATA_SIZE to a value greater than (2 * 1024 * 1024), I find that the user TA will panic on execution, in the function malloc_add_pool because it fails the assertion "start < end". 

After checking the code, it comes to me that it could be due to inappropriate value of  "heap_start_addr", which is assigned in function tee_ta_init_heap:

          heap_start_addr = va_start + CORE_MMU_USER_CODE_SIZE - heap_size;

here if the heap_size is big enough, the value of heap_start_addr could be calculated wrongly.

So do somebody know how to extend the maximum amount of memory usable by TA?

**Comment by jenswi-linaro** [comment]
Please try again with latest. You'll need to recompile the TA also.

**Comment by liangpig1** [comment]
Thanks for your advice. Actually I've just checked the latest version and find that the corresponding code seems to have changed a lot. 

However, I've developed (including adjust the kernel for my own requirement) based on the v0.3 for some time. I guess it's not gonna be a easy work to move them to the new version. 

Therefore, would you please kindly tell me if it's possible for the v0.3 to reach this goal if I change a bit of TA 's address space layout correctly? Or whether there's some tricks in design which make this version really hard to do so?

**Comment by jenswi-linaro** [comment]
I don't think it should be that hard. There's probably some call to `tee_mm_alloc()` close to the code snippet above that need to be adjusted and then that line above. You may need to do something in `tee_mmu_set_ctx()` too.

**Comment by liangpig1** [comment]
I check the code around tee_mm_alloc() as well as tee_mmu_set_ctx(). It seems that the logic of the tee_mmu_umap_set_vas() needs to be modified. The original code:

va += CORE_MMU_USER_CODE_SIZE;

assumes that each section in the ctx->mmu->table[] is at most CORE_MMU_USER_CODE_SIZE large. So I change it to,

va += mmu->table[n].size.

Of course, tee_ta_init_heap() needs to be modified accordingly, which sets the value of heap_start_addr.

I test the modification in a really simple test, which just repeatedly malloc and free. 
At least, It works so far.

**Comment by jbech-optee-adm** [comment]
Question has been answered, please re-open in case you have additional questions.
