### ISSUE TITLE
Question about generate DH key with Mbed-TLS

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#5391]
TEE cannot generate the public key with the right length when I try to share the DH key between TEE and REE 
( with `CFG_CRYPTOLIB_NAME := mbedtls` and `CFG_CRYPTOLIB_DIR := lib/libmbedtls`).

Then I modify the `xbytes` with `dhm.len` in [crypto_bignum_bin2bn(buf, xbytes, key->y)](https://github.com/OP-TEE/optee_os/blob/e906cbe741f09eaaa5b2c340eaf7beebb4925946/lib/libmbedtls/core/dh.c#L83), everything comes right.

I'm very curious to know if this is a safe and reasonable modification？

**Comment by jforissier** [comment]
Sounds like it could be related to the `TEE_ATTR_DH_X_BITS` attribute. Is your TA using it?

**Comment by YogzZ** [comment]
Thank you! No problem now.
