### ISSUE TITLE
Add a library to a PTA

### ISSUE THREAD

**Issue by f1bu** [OP-TEE/optee_os#5424]
Hi,

I want to add a static library which interacts with hardware (reads and write some registers).
I want to link this library to a PTA, but I‘m not quite sure how to do this (where to put the library .a file and which makefiles I have to edit). I found some issues about this for userspace TAs, but it seems like it works different for PTAs. I would be glad about any help.

Regards,
Finn

**Comment by jforissier** [comment]
Hello @f1bu,

As you probably know, Pseudo-TAs are an integral part of the TEE core binary. Therefore, there is no link phase for each PTA; the object files are simply added to the link phase of the TEE core. So, you need to look at `core/arch/arm/kernel/link.mk`. I think your library needs to be added to the `link-ldadd` variable. Note that there is `link-ldadd = $(LDADD)` so `make LDADD=/path/to/your/library.a` should probably be enough.

A quick note of warning about external libraries though. You need to make sure they are built with compiler flags that are consistent with the TEE core build flags. For this reason, and assuming you have the source code, it is easier and safer to import it somewhere under `optee_os/` and use the OP-TEE build system (`sub.mk`). If the library is third-party however it is a different story.
