### ISSUE TITLE
SHMEM conflict between U-Boot and Linux

### ISSUE THREAD

**Issue by philip-ro** [OP-TEE/optee_os#5432]
Hi,

I have an issue linked to shared mem usage. Whenever I call a PTA from U-Boot before booting into Linux, the Linux optee driver will crash when calling a (P)TA from Linux.

In the proximity of optee_handle_rpc() the kernel prints this error:
"Unable to handle kernel paging request at virtual address 8ef6e734"

The address causing the error is saved as a cookie of a shmem object during the U-Boot PTA call. Later on, when Linux is running, OP-TEE passes this address to Linux. So Linux apparently gets confused by a shmem object allocated by U-Boot.

Any ideas on how to fix this?

Best regards,
Philip

**Comment by jenswi-linaro** [comment]
OP-TEE has a rpc argument caching mechanism that could lead to errors like this if left enabled when U-Boot is done. However, to my knowledge U-Boot doesn't even enable that. There's also the `tee_pre_remove()` function which tries to free all remaining SHMs. I'm afraid you need to dig a bit deeper.

**Comment by jenswi-linaro** [comment]
Perhaps https://github.com/OP-TEE/optee_os/pull/5431 relates to this?

**Comment by philip-ro** [comment]
#5431 solved it, thanks!
