### ISSUE TITLE
How to call a static/pseudo TA from the u-boot in RPI3

### ISSUE THREAD

**Issue by saleemuddinshaiks** [OP-TEE/optee_os#5435]
- how to call TA from u-boot through SMC. ?
- is there any other ways to call TA through u-boot ?

**Comment by jenswi-linaro** [comment]
There is a driver in `drivers/tee/optee` for this purpose.

**Comment by saleemuddinshaiks** [comment]
how to check static TA is working or nor through u-boot ?

**Comment by jenswi-linaro** [comment]
`drivers/rng/optee_rng.c` might serve as a good example.

**Comment by DevendraDevadiga** [comment]
Here the example of CA, TA, PTA:
https://github.com/DevendraDevadiga/optee-secure-bootlog

PTA: https://github.com/OP-TEE/optee_os/pull/5081/commits/668bf21305109d9e65c5893382c065b780a4ea88

OP-TEE OS hands-on for beginners: https://youtu.be/m8WlSanGDwI
https://youtu.be/FthDUSW3yQY

**Comment by DevendraDevadiga** [comment]
Early TA: https://github.com/DevendraDevadiga/Early-TA
