### ISSUE TITLE
How to compile out dir source files into the image

### ISSUE THREAD

**Issue by Chengweiadp** [OP-TEE/optee_os#5437]
I'm developing a crypto driver some of whose source files are outside of the OPTEE directory, How should I compile them into the core.?
How should I link a static library to the core in compromise?

**Comment by jforissier** [comment]
Hi @Chengweiadp,

What you are asking is not currently supported. `srcs-y += /tmp/foo.c` happens to be somewhat working (it puts the object file under `$(out-dir)/tmp`), but `subdirs-y += /tmp/bar` doesn't. I am not sure we want to introduce such possibilities.

My suggestion is to use symbolic link(s). For example, `subdirs-y += foo_driver` in `core/drivers/sub.mk` with `ln -s /path/to/foo_driver core/drivers/foo_driver". That should work I think.
