### ISSUE TITLE
how to debug PTA code?

### ISSUE THREAD

**Issue by huangcm0101** [OP-TEE/optee_os#5438]
hi, guys
I need to run some core tests in optee with EL1, so I create the PTA code in optee-os/core/pta to do it, and I created the optee-example to invoke it. 
once the PTA code run core test, panic is observed:

########E/TC:3 0
E/TC:3 0 Core undef-abort at address 0xfe268020
E/TC:3 0  esr 0x02000000  ttbr0 0xfe2b2060   ttbr1 0x00000000   cidr 0x0
E/TC:3 0  cpu #3          cpsr 0x80000104
E/TC:3 0  x0  0000000000000000 x1  0000000000000000
E/TC:3 0  x2  00000000000000ec x3  00000000000000ec
E/TC:3 0  x4  00000000fe21b6f0 x5  0000000000000000
E/TC:3 0  x6  00000000ff701038 x7  0000000000000000
E/TC:3 0  x8  00000000ff701000 x9  0000000000000000
E/TC:3 0  x10 0000000000000000 x11 0000000000000000
E/TC:3 0  x12 0000000000000000 x13 0000000040014fb0
E/TC:3 0  x14 0000000000000000 x15 0000000000000000
E/TC:3 0  x16 00000000fe20f934 x17 0000000000000000
E/TC:3 0  x18 0000000000000000 x19 0000000000000000
E/TC:3 0  x20 00000000fe2b6fd0 x21 00000000fe2b6e80
E/TC:3 0  x22 00000000fe2b70c0 x23 00000000fe2b6fc8
E/TC:3 0  x24 00000000fe2b6fd0 x25 0000000000000001
E/TC:3 0  x26 00000000fe299d30 x27 0000000000000000
E/TC:3 0  x28 0000000000000000 x29 00000000fe2b6e50
E/TC:3 0  x30 00000000fe21b76c elr 00000000fe268020
E/TC:3 0  sp_el0 00000000fe2b6e50
E/TC:3 0 Call stack:
E/TC:3 0  0x00000000fe268020
E/TC:3 0  0x00000000fe205b24
E/TC:3 0  0x00000000fe2175d8
E/TC:3 0  0x00000000fe210cd0
E/TC:3 0  0x00000000fe20864c
E/TC:3 0 Panic '[abort] undefined abort (trap CPU)' at core/arch/arm/kernel/abort.c:464 <get_fault_t>
E/TC:3 0 TEE load address @ 0xfe200000
E/TC:3 0 Call stack:
E/TC:3 0  0x00000000fe20abd8
E/TC:3 0  0x00000000fe216560
E/TC:3 0  0x00000000fe209164
E/TC:3 0  0x00000000fe206318

I searched the document, it seems the tool scripts/symbolize.py is for TA in user space.
could you please guide me how to debug PTA?

**Comment by jenswi-linaro** [comment]
Symbolize works here too.

**Comment by etienne-lms** [comment]
Try to pass only the 1st part of the log to symbolize, the one that cause the panic.
(+ the 2 header lines 'load address' and 'Call stack' : strange you don't get them in the 1st trace):
```
E/TC:3 0 TEE load address @ 0xfe200000
E/TC:3 0 Call stack:
E/TC:3 0 0x00000000fe268020
E/TC:3 0 0x00000000fe205b24
E/TC:3 0 0x00000000fe2175d8
E/TC:3 0 0x00000000fe210cd0
E/TC:3 0 0x00000000fe20864c
