### ISSUE TITLE
TZC on imx6

### ISSUE THREAD

**Issue by philip-ro** [OP-TEE/optee_os#5446]
Hi,

optee_os configures tzc regions in core/arch/arm/plat-imx/drivers/tzc380.c. But apparently there is no action taken upon a access permission violation.

Is there really no protection against normal world accessing secure world memory in the default optee_os source tree?

(I guess I could do something like plat-stm32mp1/plat_tzc400.c for plat-imx, just want to make sure not to miss something)

**Comment by clementfaure** [comment]
Hi @philip-ro,
On i.MX platforms, the default TZASC configuration takes no specific action upon access permission violation. The memory transaction is simply denied by the TZASC, and you will most likely get a bus error.
Because no interruption handler is defined, it doesn't mean the memory is not protected.

Following the stm32mp1 implementation and `panic()` upon unauthorized memory access is up to you.

**Comment by philip-ro** [comment]
HI @clementfaure,

thanks for the reply. In my case memory transactions are not being denied. I can read and write secure memory from normal world.

This is an example of how to make OP-TEE (load address 0x8c000000) crash from within U-Boot. The same can be done from Linux.

=> mw.l 8c000000 0 1000
=> my_call_to_optee
E/TC:0 0                                                       
E/TC:0 0 Core prefetch-abort at address 0x0 (translation fault)

Now the strange thing is, that in the TZASC fail address register I can actually see that the violation was detected as such, still it won't be denied. Any ideas on what kind of misconfiguration this might be?

Below is my TZASC configuration dump.

D/TC:0 0 tzc_dump_state:336 TZC380 configuration:           
D/TC:0 0 tzc_dump_state:337 security_inversion_en 0         
D/TC:0 0 tzc_dump_state:344                                 
D/TC:0 0 tzc_dump_state:345 region 1                        
D/TC:0 0 tzc_dump_state:348 region_base: 0x0000000080000000 
D/TC:0 0 tzc_dump_state:350 region sp: f                    
D/TC:0 0 tzc_dump_state:351 region size: 1d                 
D/TC:0 0 tzc_dump_state:344                                 
D/TC:0 0 tzc_dump_state:345 region 2                        
D/TC:0 0 tzc_dump_state:348 region_base: 0x000000008c000000 
D/TC:0 0 tzc_dump_state:350 region sp: c                    
D/TC:0 0 tzc_dump_state:351 region size: 19                 
D/TC:0 0 tzc_dump_state:344                                 
D/TC:0 0 tzc_dump_state:345 region 3                        
D/TC:0 0 tzc_dump_state:348 region_base: 0x000000008d000000 
D/TC:0 0 tzc_dump_state:350 region sp: c                    
D/TC:0 0 tzc_dump_state:351 region size: 17                 
D/TC:0 0 tzc_dump_state:344                                 
D/TC:0 0 tzc_dump_state:345 region 4                        
D/TC:0 0 tzc_dump_state:348 region_base: 0x000000008dc00000 
D/TC:0 0 tzc_dump_state:350 region sp: f                    
D/TC:0 0 tzc_dump_state:351 region size: 15                 
D/TC:0 0 tzc_dump_state:354 Lockdown select: 1              
D/TC:0 0 tzc_dump_state:356 Lockdown range: 80000007        
D/TC:0 0 tzc_dump_state:358 Action register: 1              
D/TC:0 0 tzc_dump_state:359 exit

**Comment by Emantor** [comment]
You have to disable the TZC bypass which is enabled by default on i.MX6 SoCs. This can't be done within OP-TEE and AFAIR needs to be done before the MMU is enabled in the previous boot stage.

**Comment by philip-ro** [comment]
Thanks @Emantor. Setting the TZASC1_BYP bit in U-Boot SPL solved the problem.
