### ISSUE TITLE
Secure Storage FEK key-size revisited

### ISSUE THREAD

**Issue by larperaxis** [OP-TEE/optee_os#5447]
I found the #4711 issue that discusses an extension of the FEK size to 256-bit but it ended without any action taken upstream.
We are expecting demands for 256-bit symmetric keys to increase from customers to get 128-bit security in a PQC-world.

We are preparing local changes to get a 256-bit HUK and a 256-bit FEK but we prefer to align with upstream on a common solution.

The minimum effort solution seems to be an opt-in solution where new platforms can set:
TEE_FS_HTREE_FEK_SIZE = 32
TEE_FS_KM_FEK_SIZE = 32
HW_UNIQUE_KEY_LENGTH = 32

This solution will not support updating from firmware that had secure storage objects written with the smaller key sizes so we expect the new key sizes must be set from the beginning for a given product.

What are your thoughts on this subject ?

**Comment by jenswi-linaro** [comment]
Setting these from the platform specific config like that is a quick and dirty fix to the problem, but I guess that in the end it will boil down to that in some way. The three keys are independent, but if you use RPMB to store the REE FS hash all three will need to be increased in size as you suggest.

One thing to keep in mind is to find a way that makes it easy for new platforms or new variants of a platform to make the right choice.
