### ISSUE TITLE
STM32MP1 Hardware Unique Key

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#5448]
Has anyone given any thought to generating a HUK for the STM32MP1 platform? Maybe @etienne-lms ?

Intuitively perhaps using the [Secure Secret Provisioning process ](https://www.st.com/resource/en/application_note/dm00713831-.pdf) to write a 256 bit secret key to a pre-defined OTP, deny it access from NSEC and then using it to encrypt the SoC unique identifier should be enough. 

Just as it is done on the Xilinx/AMD platforms.

Any other thoughts for a HUK driver? Shall I propose something along those lines?

**Comment by etienne-lms** [comment]
Hi @ldts,
Indeed using BSEC OTP fuses to store secret HUK is the recommended way. The reference you provide is the good one for burning the target fuses. Yet there is no predefined default location for the OTP words that shall store the HUK, for stm32mp1 platforms. Defining fuses would be nice but not all people really want to burn fuses. There are free locations in the secure part of the BSEC OTP fuse memory.

That said, I've been asked at few times some example code. I've prepared this [patch](https://github.com/etienne-lms/optee_os/commit/cfec862b017d0a97e184f32abfdd75c3d0000eef) (non-permanent link) to define 4 OTPs words for that purpose, expecting `CFG_xxx` switches to define the location, yet allowing to use an all 0's test key. IHIH. Maybe it would be wroth merging this code in mainline.

By the way, OP-TEE OS currently expects a 128bit HUK. The referred patch expects 4 32bit OTPs words to store HUK.

**Comment by ldts** [comment]
thanks @etienne-lms; I was thinking we could perhaps use the SoC unique identifier - 96 bits - to make it unique and then just have the OEMs  write an AES encryption key on the OTP eFuse to generate the HUK - rather than having the actual HUK in OTP? So maybe extending your patch we could retrieve a 256 encryption key?

then maybe the OP-TEE core could have a generic driver that generates the HUK as
1) gets some public uniqueness for the SoC
2) encrypts it with a secret key (from either eFuse or already enabled in the crypto engine)

what do you think?

**Comment by etienne-lms** [comment]
Do you propose an alternate implementation of `huk_subkey_derive()` to do HUK derivation with different inputs (a HUK read from fuses that is not 128bit large, a platform specific unique ID, ...)? 
With what you describe, the platform still needs a HUK root data from fuses, so I think it is simpler if  `huk_subkey_derive()` remains what it is and it's still up to each platform to generate its HUK from its desired scheme/input (by implementing `tee_otp_get_hw_unique_key()`).
For stm32mp1, I think storing the HUK plain in OTPs is simpler and safer.

For platforms where there is HW capable of deriving a HUK that is not readable at all by the SW, I think we need herean alternate implementation of `huk_subkey_derive()` to call back-end platform HW driver to get derivation params and produce the desired derived key.

As usual, P-Rs are always welcome, even if they sometime take time to land.
As for stm32mp1, I think i'll create a P-R to propose the implementation I shared above and maybe extend it with some HUK provisioning means.

**Comment by ldts** [comment]
I think `tee_otp_get_hw_unique_key` instead of just reading data from eFuse could perhaps

1) read a **_key_** from eFuse
2) read a SoC _unique_ id
3) sym-encrypt the unique id with the key and return this value.

That way the logic provisioning the eFuse gets simplified (just write a key) and it avoids HUK collisions between boards.

**Comment by ldts** [comment]
So similar to https://github.com/OP-TEE/optee_os/pull/5351 and https://github.com/OP-TEE/optee_os/pull/5426/commits/2bc7d7135f7f1af0b2dd618879907568b88756c8#diff-35a8c09534eeac37da2b63abe7ed0d720477d8ac97557978d3ec139b73fdd334R284
