### ISSUE TITLE
What factors affect the size of shared memory that can be registered?

### ISSUE THREAD

**Issue by trriger** [OP-TEE/optee_os#5450]
Hi!
My device is hikey960 and optee version is 3.16.
I wrote a program. When different functions call the TEEC_RegisterSharedMemory function, the buffer sizes of the shared memory that can be registered are different. One of them can register a buffer not larger than 12M. But when another function registers more than 2M functions, 0xffff0000 error occurs.
What factors affect the buffer size of registered share memory?

**Comment by etienne-lms** [comment]
I don't see any size constraints on registered shared memory when dynamic shm is enable (`CFG_CORE_DYN_SHM=y`), but generic core resources exhaustion (heap, xlat tables).

**Comment by trriger** [comment]
@etienne-lms ,Thank you for your reply, and I have one more question.

Is CFG_CORE_DYN_SHM=y enabled by default, or do you need to reconfigure the environment to enable it.

**Comment by etienne-lms** [comment]
Yes, CFG_CORE_DYN_SHM is enabled by default, but to effectively support dynamic shm you also need the platform to tell optee where the main RAM is (base physical address(s) and size(s)).

For this, you can use macros `register_ddr()`, for example:
https://github.com/OP-TEE/optee_os/blob/bb75092f2f898c3b65863671133324c5deddf23b/core/arch/arm/plat-vexpress/main.c#L44-L49

Antoher way to provide main memory/ies location is to have boot stage passing an external DTB to OP-TEE at boot time. OP-TEE wil look for nodes with property `device_type` set to `"memory"` and find the DDR location, see [`get_nsec_memory()`](https://github.com/OP-TEE/optee_os/blob/3.18.0/core/arch/arm/kernel/boot.c#L990).

**Comment by trriger** [comment]
@etienne-lms 
From your description above, there is normally no limit to the size of the SHM.
Due to the installation requirements of Mali GPU driver, I used an old version of Linux kernel 4.19. Could this error be caused by the kernel?

**Comment by trriger** [comment]
![image](https://user-images.githubusercontent.com/55041272/181403732-82642b18-be55-4fea-bf48-6797d2a0ca3c.png)
I just found that "alloced_size" is smaller than "size" in TEEC_SharedMemory. Is this the cause? Then I check the [GlobalPlatform TEE Client API [Specification]() v1.0 (GPD_SPE_007](https://globalplatform.org/specs-library/?filter-committee=tee) and there is no description of this member. What is the role of "alloced_size"

**Comment by etienne-lms** [comment]
I don't think optee driver of Linux kernel 4.19 supports dynamic shared memory.

**Comment by trriger** [comment]
Thanks for the answer. The reason for this failure to register large shared memory is that I forgot CloseObject in the TA section of the code. Loop multiple times causing TA secure memory to run out.
