### ISSUE TITLE
Issue related to mempool allocation in optee_os

### ISSUE THREAD

**Issue by vlrk** [OP-TEE/optee_os#5466]
Hi All,

I want to generate a rsa key pair with 4096 bits. 
Using below mbedTLS api , inside my TEE server side implementation.

ret = mbedtls_rsa_gen_key( mbedtls_pk_rsa( key ), mbedtls_ctr_drbg_random, &ctr_drbg, 4096, 65537 );

This is resulting in the below error.
mempool_alloc:197Failed to allocate 288 bytes, please tune the pool size failed 

Mines is arm64 infrastructure, with kernel 4.19.183 and optee_os 3.7.0 
We tried doing below change (courtesy: https://github.com/OP-TEE/optee_os/issues/3328) and recompiling tomcrypt library
In core/lib/libtomcrypt/mpi_desc.c, we changed MPI_MEMPOOL_SIZE

      #define MPI_MEMPOOL_SIZE        (42 * 1024)

to    #define MPI_MEMPOOL_SIZE        (82 * 1024)

This didn’t help, kindly provide your inputs.                                                                                      

Thanks

**Comment by jforissier** [comment]
Hi @vlrk,

There are two memory pools and therefore two values for `MPI_MEMPOOL_SIZE`: one in `core/lib/libtomcrypt/mpi_desc.c` which is used by the core (SEL1), and the other in `lib/libutee/tee_api_arith_mpi.c` for user space. When calling MBedTLS directly in a TA you are using the latter. Try increasing that one.

Note that you can also generate RSA keys using the GlobalPlatform API (`TEE_GenerateKey()`) which has some adavtages:  secret material remains at SEL1 rather than being exposed to SEL0; on some platforms it is hardware accelerated; the key can easily be written to secure storage etc.

**Comment by vlrk** [comment]
Thanks for the inputs .

After changing the variable in the later file , no more mempool_alloc issue observed.

With this I will be closing the issue . 

Apart from this I need a suggestion on mbedtls usage with optee .

I am trying to get a CSR using mbedtls. 

This CSR needs rsa key as one of it's parameter, as of now using the mbedTLS api (mbedtls_rsa_gen_key ) for rsa key generation. 

I want rsa to be stored in TEE secure storage. This I guess can be done in two ways.

1. Use TEE_Generatekey for generating rsa key pair. Give this required key parameter to mbeldTLS API's to get the CSR workdone . Though I can store the rsa key , but as of now I don't know how to pass TEE generated RSA key pair to mbedTLS API's. 

Else 

2. Use mbedTLS API's to  generate rsa key  and get CSR generation done.. In this method also , don't know how mbedTLS rsa key can be stored in the TEE secure storage . 

If this is not a right forum , please let me know where can I find leads related to this.
(I already posted this in op-tee@lists.trustedfirmware.org . )

Thanks a lot .

**Comment by jforissier** [comment]
> I want rsa to be stored in TEE secure storage. This I guess can be done in two ways.

Correct.
 
> 1. Use TEE_Generatekey for generating rsa key pair. Give this required key parameter to mbeldTLS API's to get the CSR workdone . Though I can store the rsa key , but as of now I don't know how to pass TEE generated RSA key pair to mbedTLS API's.

The proper function to use to extract the key is `TEE_GetObjectBufferAttribute()` with `TEE_ATTR_RSA_MODULUS`, `TEE_ATTR_RSA_PUBLIC_EXPONENT`, `TEE_ATTR_RSA_PRIVATE_EXPONENT`. It will give you raw numbers in big-endian format (see GlobalPlatform TEE Internal Core API specification tables 6-15 and 6-16). To save the key to secure storage, you just call `TEE_CreatePersistentObject()` with the key.

> 
> Else
> 
> 2. Use mbedTLS API's to  generate rsa key  and get CSR generation done.. In this method also , don't know how mbedTLS rsa key can be stored in the TEE secure storage .

That is also a valid option. Two choices here:
- You could either create a GP key from the raw values returned by MBedTLS using `TEE_AllocateTransientObject()` and `TEE_PopulateTransientObject()`, in which case you are back to case number 1.
- Or you just write your MBedTLS key in the native format or after any formatting you may want (meta-data...) using the `initialData` parameter of `TEE_CreatePersistentObject()` or using `TEE_WriteObjectData()`.

> If this is not a right forum , please let me know where can I find leads related to this. (I already posted this in [op-tee@lists.trustedfirmware.org](mailto:op-tee@lists.trustedfirmware.org) . )

Both places are OK.
