### ISSUE TITLE
TEEC_Opensession failed with code 0xffff000c origin 0x3

### ISSUE THREAD

**Issue by ponnij** [OP-TEE/optee_os#5469]
Hi Team,

We are seeing the below error in TA execution.
TEEC_Opensession failed with code 0xffff000c origin 0x3

From other reference, we tried increasing the TA_STACK_SIZE and TA_DATA_SIZE in user_ta_header_defines.h, 
but it doesn't seem to help.

Kindly provide us with suggestions on how to resolve this.

**Comment by jforissier** [comment]
Hi @ponnij,

>  TEEC_Opensession failed with code 0xffff000c origin 0x3

I assume this message is logged by the client application. 0x3 is `TEE_ORIGIN_TEE` which seems to indicate the error occurs when OP-TEE is loading the TA, not when the TA is actually executing. Perhaps the TA is too big? Try reducing `TA_DATA_SIZE` or increasing the memory available for TAs in the TEE core (increase `CFG_TZDRAM_SIZE` and/ir decrease `CFG_TEE_CORE_HEAP_SIZE`, the specifics could depend on the platform).

**Comment by ponnij** [comment]
Hi @jforissier ,

Thanks for your suggestion. Yes, you are right the message is logged by client application.
"TEEC_Opensession failed with code 0xffff0000 origin 0x3"

We tried decreasing the TA_DATA_SIZE, but still we see the failure. Please help.

E/TC:? 0 read_compressed:206 Decompression error (-4)
E/LD:  populate_segments:641 sys_copy_from_ta_bin
E/TC:? 0 init_with_ldelf:229 ldelf failed with res: 0xffff0000
E/TC:? 0 tee_ta_open_session:727 Failed. Return error 0xffff0000
TEEC_Opensession failed with code 0xffff0000 origin 0x3

**Comment by jforissier** [comment]
> E/TC:? 0 read_compressed:206 Decompression error (-4)

Early TA decompression error, very likely due to insufficient core heap memory. Try increasing `CFG_CORE_HEAP_SIZE`.

**Comment by ponnij** [comment]
Hi @jforissier,

We increased CFG_CORE_HEAP_SIZE in optee_os-3.7.0/mk/config.mk to CFG_CORE_HEAP_SIZE ?= 524288.
Previously it was 65536. But Still, same issue is seen.
Kindly let us know if we are changing in the correct file.
we are running the application on arm64 infrastructure, with kernel 4.19.183 and optee_os 3.7.0

**Comment by jforissier** [comment]
> Hi @jforissier,
> 
> We increased CFG_CORE_HEAP_SIZE in optee_os-3.7.0/mk/config.mk to CFG_CORE_HEAP_SIZE ?= 524288. Previously it was 65536. But Still, same issue is seen. Kindly let us know if we are changing in the correct file. 

Not sure. If you are building for a platform that defines a platform-specific default value in `core/arch/arm/plat-X/conf.mk` then `mk/config.mk` is not the correct place. In this case you need to change the platform-specific file, or override the value on the make command line: `make CFG_CORE_HEAP_SIZE=xxx`. You can check the actual value used at build time in `out/arm-plat*/conf.mk`.

**Comment by ponnij** [comment]
Hi @jforissier,

Yes, i see the modified value is reflected in below file.
optee_os-3.7.0/out/arm-plat-bca/export-ta_arm64/host_include/conf.mk:18:CFG_CORE_HEAP_SIZE=524288

**Comment by hardik722** [comment]
What is can be a cause for SecureOS RSA encrypt failed (teec=0xffff000c, origin=0x00000004).
Provide solution if any.
