### ISSUE TITLE
Define `MBEDTLS_PKCS5_C` in `mbedtls_config_uta.h`

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#5473]
To use `mbedtls_pkcs5_pbkdf2_hmac` in mbedtls in user TA, I add `#define MBEDTLS_PKCS5_C` in `mbedtls_config_uta.h`.

Is it safe and stable?

**Comment by jforissier** [comment]
Yes.

**Comment by YogzZ** [comment]
Thank you!
