### ISSUE TITLE
OP-TEE builds for Raspberry Pi 3B plus

### ISSUE THREAD

**Issue by tedescn** [OP-TEE/optee_os#5476]
I have attempted OP-TEE builds from versions 3.13.0 to 3.18.0, reusing the same process.

OP-TEE versions 3.13.0 & 3.14.0 loaded successfully. Where versions 3.15.0 -3.18.0 indicate both BTL1 & BT31:cortex_53 issues.

Booting the trusted firmware, BL1: workaround 843419 is successfully applied, as is workaround 855873. However, BL1 workaround 1530924 is identified as missing, as a warning. Subsequently, BL31 echos the same workaround successes and failure. Note, we asume the warning is an issue?

As build machines I've tested fully patched VMs of both Ubuntu 18:04 & 20.04, and suspect I'm missing something regards the differeent versions?

Can I ask if all versions are tested, and is there a recommended approach to debugging the build process?

Attached is a .csv file, of the various files sizes generated vs build versions.

Currently, I'm treating 3.18.0 as an outlier, where the .dts of the .dtb demostrates a diverence of contents at lines 102.

Any suggestions appreciated.

Regards
Nigel

[Summary_of_OP-TEE_boot_file_sizes_by_Version-Ubuntu_20.04-Draft_1A.xlsx](https://github.com/OP-TEE/optee_os/files/9277611/Summary_of_OP-TEE_boot_file_sizes_by_Version-Ubuntu_20.04-Draft_1A.xlsx)

**Comment by jforissier** [comment]
Hello @tedescn,

> I have attempted OP-TEE builds from versions 3.13.0 to 3.18.0, reusing the same process.
> 
> OP-TEE versions 3.13.0 & 3.14.0 loaded successfully. Where versions 3.15.0 -3.18.0 indicate both BTL1 & BT31:cortex_53 issues.

I suppose you mean BL1 and BL31.

> Booting the trusted firmware, BL1: workaround 843419 is successfully applied, as is workaround 855873. However, BL1 workaround 1530924 is identified as missing, as a warning. Subsequently, BL31 echos the same workaround successes and failure. Note, we asume the warning is an issue?

BL1 and BL31 messages are from TF-A, not OP-TEE, so you may be able to get more information by asking on the TF-A mailing list. That being said, I suspect the message you see means that `ERRATA_A53_1530924` was set to `0` (disabled) at build time. Whether it is a good idea to enable it or not, I don't know. There may be a reason why this one is disabled by default and not others.

> As build machines I've tested fully patched VMs of both Ubuntu 18:04 & 20.04, and suspect I'm missing something regards the differeent versions?

Messages about CPU erratas depend on the CPU (whether or not it has the errata) not the build machine, and the version/configuration of the software, TF-A in this case (whether or not is contains special code to mitigate the errata).

> Can I ask if all versions are tested, and is there a recommended approach to debugging the build process?

Which platforms are tested for each OP-TEE release is documented in the "CHANGELOG" commit which is tagged for each release. You can use `git show --no-patch 3.16.0` etc. to see the `Tested-by:` tags.

> Attached is a .csv file, of the various files sizes generated vs build versions.
>
> Currently, I'm treating 3.18.0 as an outlier, where the .dts of the .dtb demostrates a diverence of contents at lines 102.
> 
> Any suggestions appreciated.

What is the problem?
