### ISSUE TITLE
Restrict OPTEE to certain core

### ISSUE THREAD

**Issue by f1bu** [OP-TEE/optee_os#5477]
I want to restrict OP-TEE to a certain core, e.g. Core1. I know that this is not possible by default, but I wonder if it would be possible like this:
1. Normally we assume cooperation by the Linux OS. CAs are always pinned to Core1, and the corresponding TAs are therefore also running on Core1.
2. When the core switches to secure world and executes OPTEE, OPTEE checks if it is running on Core1. If not (because a "bad actor" scheduled it on the wrong core), it refuses execution and returns to normal world.

Would this generally be possible?

Regards,
Finn

**Comment by jenswi-linaro** [comment]
Yes, that should be possible and quite easy as long as you don't mind configuring all the cores at boot (just as today).

**Comment by f1bu** [comment]
Alright, thanks a lot!
