### ISSUE TITLE
PCSC

### ISSUE THREAD

**Issue by Yummy813** [OP-TEE/optee_os#5493]
error:    winscard.h is required for pcsc？？？？？？？？？？？

**Comment by JiaLianga** [comment]
> error: winscard.h is required for pcsc？？？？？？？？？？？

解决了吗请问

**Comment by Cishoon** [comment]
> > error: winscard.h is required for pcsc？？？？？？？？？？？
> 
> 解决了吗请问

手动设置gcc的include
export C_INCLUDE_PATH=/usr/include/PCSC:$C_INCLUDE_PATH
