### ISSUE TITLE
TEE_AsymmetricDecrypt failure

### ISSUE THREAD

**Issue by gappudon** [OP-TEE/optee_os#5497]
Hello ,

I am trying to perform an RSA Encryption and Decryption with RSA_OAEP_SHA512. I generate a key and then extract public& private exponent from it along with modulus.

I pass these extracted values via TEE_PopulateTransientObject functions. However, the TEE_AsymmetricDecrypt seems to pass but TEE_AsymmetricDecrypt is failing. Can you please help me figure out the issue ?

Please find my code snipper below : 

  TEE_ObjectHandle key_handle = (TEE_ObjectHandle)NULL;
  TEE_ObjectHandle key_handle_enc = (TEE_ObjectHandle)NULL;
  TEE_ObjectHandle keyhandle = (TEE_ObjectHandle)NULL;
  TEE_OperationHandle op_handle = NULL;
  TEE_OperationHandle op_handle_decrpt = NULL;
  TEE_ObjectHandle key_handle_decrpt = (TEE_ObjectHandle)NULL;
  uint8_t testop[512] = {0};
  uint32_t cipher_len = 512;
  uint8_t testip[10] =  {0};
  uint8_t plain_txt[512];
  uint32_t plain_len = 512;
  uint8_t modulus[512] =  {0};
  uint8_t exponent[512] =  {0};
  uint8_t exponent1[512] =  {0};

   TEE_Result prepare_rsa_operation(TEE_OperationHandle *handle, uint32_t alg, TEE_OperationMode mode, TEE_ObjectHandle key) {
    
	TEE_Result ret = TEE_SUCCESS;	
	TEE_ObjectInfo key_info;
	ret = TEE_GetObjectInfo1(key, &key_info);
	if (ret != TEE_SUCCESS) {
		DMSG("\nTEE_GetObjectInfo1: 0x%x\n" , ret);
		return ret;
	}

	ret = TEE_AllocateOperation(handle, alg, mode, key_info.maxObjectSize);
	if (ret != TEE_SUCCESS) {
		DMSG("\nFailed to alloc operation handle : 0x%x\n", ret);
		return ret;
	}
	DMSG("\n========== Operation allocated successfully. ==========\n");

	ret = TEE_SetOperationKey(*handle, key);
	if (ret != TEE_SUCCESS) {
		DMSG("\nFailed to set key : 0x%x\n", ret);
		return ret;
	}
    DMSG("\n========== Operation key already set. ==========\n");
    
	return ret;
}

static TEE_Result RSA_encrypt(void) {
    
	TEE_Result ret;
	uint32_t rsa_alg = TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA512;
    TEE_Attribute rsa_pubkey_attr[3];
    DMSG("\n========== Preparing encryption operation ==========\n");
    memset(testip,0xcc,sizeof(testip));

    ret =  TEE_AllocateTransientObject(TEE_TYPE_RSA_KEYPAIR, 4096, &key_handle_enc);
    if (ret != TEE_SUCCESS) {
		DMSG("\n TEE_AllocateTransientObject failed: 0x%x\n", ret);
		return ret;
	}    

    rsa_pubkey_attr[0].attributeID = TEE_ATTR_RSA_MODULUS;
    rsa_pubkey_attr[0].content.ref.buffer = modulus;
    rsa_pubkey_attr[0].content.ref.length = 0x200;

    rsa_pubkey_attr[1].attributeID = TEE_ATTR_RSA_PUBLIC_EXPONENT;
    rsa_pubkey_attr[1].content.ref.buffer = exponent;
    rsa_pubkey_attr[1].content.ref.length = 0x4;

    rsa_pubkey_attr[2].attributeID = TEE_ATTR_RSA_PRIVATE_EXPONENT;
    rsa_pubkey_attr[2].content.ref.buffer = exponent1;
    rsa_pubkey_attr[2].content.ref.length = 0x200;

    ret = TEE_PopulateTransientObject(key_handle_enc, rsa_pubkey_attr, 3);
    if (ret != TEE_SUCCESS) {
		DMSG("\n TEE_PopulateTransientObject failed: 0x%x\n", ret);
		return ret;
	}
    ret = TEE_AllocateOperation(&op_handle, rsa_alg, TEE_MODE_ENCRYPT, 4096);
    if (ret != TEE_SUCCESS) {
		DMSG("\n TEE_AllocateOperation failed: 0x%x\n", ret);
		return ret;
	}
    ret = TEE_SetOperationKey(op_handle, key_handle_enc);
    if (ret != TEE_SUCCESS) {
		DMSG("\n TEE_SetOperationKey failed: 0x%x\n", ret);
		return ret;
	}

    DMSG("++++INPUT MESSAGE FOR ENCRYPTION+++++++++++");
    for(uint8_t i = 0; i < sizeof(testip); i++){
        DMSG(" input = %d", testip[i]);
    }
	ret = TEE_AsymmetricEncrypt(op_handle, (TEE_Attribute *)NULL, 0,
					testip, 10, testop, &cipher_len);					
	if (ret != TEE_SUCCESS) {
		DMSG("\nFailed to encrypt the passed buffer: 0x%x\n", ret);
		goto err;
	}
    DMSG("\nouput encryption length: %d\n", cipher_len);
	DMSG("\n========== Encryption successfully ==========\n");

	return ret;

err:
	TEE_FreeOperation(op_handle);
	TEE_FreeOperation((TEE_OperationHandle)key_handle);
    
	return ret;
}

TEE_Result RSA_decrypt() {
    
	TEE_Result ret;
    TEE_Attribute rsa_pubkey_attr[3];
	uint32_t rsa_alg = TEE_ALG_RSAES_PKCS1_OAEP_MGF1_SHA512;

	DMSG("\n========== Preparing decryption operation ==========\n");

    ret =  TEE_AllocateTransientObject(TEE_TYPE_RSA_KEYPAIR, 4096, &keyhandle);
    if (ret != TEE_SUCCESS) {
		DMSG("\n TEE_AllocateTransientObject failed: 0x%x\n", ret);
		return ret;
	}    

    rsa_pubkey_attr[0].attributeID = TEE_ATTR_RSA_MODULUS;
    rsa_pubkey_attr[0].content.ref.buffer = modulus;
    rsa_pubkey_attr[0].content.ref.length = 0x200;

    rsa_pubkey_attr[1].attributeID = TEE_ATTR_RSA_PUBLIC_EXPONENT;
    rsa_pubkey_attr[1].content.ref.buffer = exponent;
    rsa_pubkey_attr[1].content.ref.length = 0x4;

    rsa_pubkey_attr[2].attributeID = TEE_ATTR_RSA_PRIVATE_EXPONENT;
    rsa_pubkey_attr[2].content.ref.buffer = exponent1;
    rsa_pubkey_attr[2].content.ref.length = 0x200;

    ret = TEE_PopulateTransientObject(keyhandle, rsa_pubkey_attr, 3);
    if (ret != TEE_SUCCESS) {
		DMSG("\n TEE_PopulateTransientObject failed: 0x%x\n", ret);
		return ret;
	}
    ret = TEE_AllocateOperation(&op_handle_decrpt, rsa_alg, TEE_MODE_DECRYPT, 4096);
    if (ret != TEE_SUCCESS) {
		DMSG("\n TEE_AllocateOperation failed: 0x%x\n", ret);
		return ret;
	}
    ret = TEE_SetOperationKey(op_handle_decrpt, keyhandle);
    if (ret != TEE_SUCCESS) {
		DMSG("\n TEE_SetOperationKey failed: 0x%x\n", ret);
		return ret;
	}
	DMSG("\nData to decrypt: \n");
	ret = TEE_AsymmetricDecrypt(op_handle_decrpt, (TEE_Attribute*)NULL, 0,
				testop, cipher_len, plain_txt, &plain_len);
	if (ret != TEE_SUCCESS) {
		DMSG("\nFailed to decrypt the passed buffer: 0x%x\n", ret);
		goto err;
	}
	
	DMSG("\n========== Decryption successfully ==========\n");
    DMSG("\nouput plain text length: %d\n", plain_len);
    DMSG("++++OUTPUT MESSAGE FOR DECRYPTION+++++++++++");
    for(uint8_t i = 0; i < plain_len; i++){
        DMSG(" output = %d", plain_txt[i]);
    }
    int32_t ret1 = TEE_MemCompare(testip,plain_txt,10U);
    if(ret1 == TEE_SUCCESS){
        DMSG("\n========== TEST PASSED ==========\n");
    }  
	return ret;

err:
	TEE_FreeOperation(op_handle_decrpt);
	TEE_FreeTransientObject(key_handle_decrpt);
    
	return ret;
}
*********** Main function ************
TEE_Result RSA_create_key_pair(void *session) {
    
    (void) session;
	TEE_Result ret;
	size_t key_size = 4096;
    uint32_t count = 4096;
	// struct rsa_session sess;
	DMSG("\nCalling RSA keypair func\n");
	ret = TEE_AllocateTransientObject(TEE_TYPE_RSA_KEYPAIR, key_size, &key_handle);
	if (ret != TEE_SUCCESS) {
		DMSG("\nFailed to alloc transient object handle and keysize: 0x%x, %d\n", ret, key_size);
		return ret;
	}
	DMSG("\n========== Transient object allocated. ==========\n");

	ret = TEE_GenerateKey(key_handle, key_size, (TEE_Attribute *)NULL, 0);
	if (ret != TEE_SUCCESS) {
		DMSG("\nGenerate key failure and key_size: 0x%x, %d\n", ret, key_size);
		return ret;
	}
    ret =  TEE_GetObjectBufferAttribute(key_handle, TEE_ATTR_RSA_MODULUS , modulus,  &count);
    if (ret != TEE_SUCCESS) {
		DMSG("\n TEE_GetObjectBufferAttribute failed for modulus: 0x%x\n", ret);
		return ret;
	}
    DMSG("\nCount for Modulus is : 0x%x \n", count);
    count = 4096;
    ret =  TEE_GetObjectBufferAttribute(key_handle, TEE_ATTR_RSA_PUBLIC_EXPONENT , exponent,  &count);
    if (ret != TEE_SUCCESS) {
		DMSG("\n TEE_GetObjectBufferAttribute failed for exponent: 0x%x\n", ret);
		return ret;
	}
    DMSG("\nCount for Public Exponent is : 0x%x \n", count);
    count = 4096;
    ret =  TEE_GetObjectBufferAttribute(key_handle, TEE_ATTR_RSA_PRIVATE_EXPONENT , exponent1,  &count);
    if (ret != TEE_SUCCESS) {
		DMSG("\n TEE_GetObjectBufferAttribute failed for exponent: 0x%x\n", ret);
		return ret;
	}
    DMSG("\nCount for Private Exponent is : 0x%x \n", count);
	DMSG("\n========== Keys generated. ==========\n");
    ret =  RSA_encrypt();
    if (ret != TEE_SUCCESS) {
		DMSG("\n RSA_encrypt failure and key_size: 0x%x, %d\n", ret, key_size);
		return ret;
	}
	DMSG("\n========== RSA_encrypt successful. ==========\n");
    ret = RSA_decrypt();
    if (ret != TEE_SUCCESS) {
		DMSG("\n RSA_decrypt failure and key_size: 0x%x, %d\n", ret, key_size);
		return ret;
	}
	DMSG("\n========== RSA_decrypt successful. ==========\n");
    
	return ret;
}

**Comment by gappudon** [comment]
fixed

**Comment by janjosephlim** [comment]
@gappudon can you explain how did you fix the issue with decrypt? I tried running the given code snippet and I am having a problem with decrypt

specifically:
E/TC:? 0 crypto_acipher_rsaes_decrypt:339 rsa_decrypt_key_ex() returned 7
D/TA:  RSA_decrypt:330 Failed to decrypt the passed buffer: 0xffff0006
D/TA:  RSA_create_key_pair:404  RSA_decrypt failure and key_size: 0xffff0006, 1024

**Comment by gappudon** [comment]
The public exponent length while populating should be 3 and not 4
