### ISSUE TITLE
__args_count calculate wrong result in assert.h

### ISSUE THREAD

**Issue by ZheTing815** [OP-TEE/optee_os#5502]
Hi,

In lib/libutils/isoc/include/assert.h, Is there something wrong for "__args_count"?
For Example:
```
#include <stdio.h>

#define ___args_count(_0, _1, x, ...)  x
#define __args_count(... ) ___args_count(__VA_ARGS__, 2, 1, 0)

int main()
{
   // __args_count test
    printf("%d\n", __args_count(true));
    printf("%d\n", __args_count(true, "msg"));
    printf("%s\n", __args_count(std::is_constructible<int, float>::value, "msg"));

   return 0;
}
```
Output is following:
1
2
msg

But for third one, it should also be 2.

**Comment by jenswi-linaro** [comment]
`__args_count` is just an internal helper for the `static_assert()` macro so you should not depend on it for anything else.

Out of curiosity, why do you believe it should be 2 in the last case too?

**Comment by ZheTing815** [comment]
Thanks for quick reply.

Sorry, I explain in details.

First, our toolchain is Clang-12.0.1.

The assert.h define:
```
#define ___args_count(_0, _1, x, ...) x
#define __args_count(...) ___args_count(__VA_ARGS__, 2, 1, 0)

#define __static_assert_1(expr)		_Static_assert(expr, "")
#define __static_assert_2(expr, msg)	_Static_assert(expr, msg)
#define ___static_assert(count, ...)	__static_assert_ ## count(__VA_ARGS__)
#define __static_assert(count, ...)	___static_assert(count, __VA_ARGS__)

#define static_assert(...) \
	__static_assert(__args_count(__VA_ARGS__), __VA_ARGS__)
#endif
```

The CPP code  ```static_assert( is_constructible<_Tp, _Args...>::value, "Can't construct object in make_shared" );``` will be expanded to ```__static_assert_"Can't construct object in allocate_shared"(is_constructible<_Tp, _Args...>::value, "Can't construct object in allocate_shared");``` .
It should be ```__static_assert_2(is_constructible<_Tp, _Args...>::value, "Can't construct object in allocate_shared");```
Or it will compile error because compiler cannot recognize the syntex ```__static_assert_"Can't construct object in allocate_shared"(is_constructible<_Tp, _Args...>::value, "Can't construct object in allocate_shared");```

These codes can only output 1 or 2.
```
#define ___args_count(_0, _1, x, ...) x
#define __args_count(...) ___args_count(__VA_ARGS__, 2, 1, 0)
```
In our test code, ```__args_count(std::is_constructible<int, float>::value, "msg")```, it get "msg"(second argument). But it should be 2.

However, ```static_assert``` in C++11 is belong to reserved word. [http://doc.hc2.ch/c_cpp/en/cpp/keywords.html](http://doc.hc2.ch/c_cpp/en/cpp/keywords.html). We don't need include any headers to use ```static_assert```.
If it need to be redefine in OPTEE header. Maybe the macro naming need to avoid to have the same name as programming language or compile extension.

By the way, We found the same issue in compiler.h for ```fallthrough```.
For example:
In compiler.h ```#define fallthrough __attribute__((__fallthrough__))```. When we use ```#define OPENSSL_FALLTHROUTH _attribute_((fallthrough))```. It will be extended to ```__attribute__ ((__attribute__((__fallthrough__))))```.

Thanks!

**Comment by jforissier** [comment]
> However, `static_assert` in C++11 is belong to reserved word. http://doc.hc2.ch/c_cpp/en/cpp/keywords.html. We don't need include any headers to use `static_assert`.

Should the definition in our `assert.h` be guarded by `#if !defined(__cplusplus) || (__cplusplus < 201103L)` perhaps?

**Comment by jforissier** [comment]
@ZheTing815 OK, feel free to open a PR and propose a patch.

**Comment by ZheTing815** [comment]
Ok thanks.

But this solution can't work on  ```fallthrough``` case. For this case, do you have any other suggestions?

**Comment by jforissier** [comment]
> But this solution can't work on `fallthrough` case. For this case, do you have any other suggestions?

Perhaps it should be renamed `__fallthrough`. All other definitions in `compiler.h` have a double underscore prefix (except `barrier()`).

**Comment by jenswi-linaro** [comment]
> > But this solution can't work on `fallthrough` case. For this case, do you have any other suggestions?
> 
> Perhaps it should be renamed `__fallthrough`. All other definitions in `compiler.h` have a double underscore prefix (except `barrier()`).

No, it should be `fallthrough`. Perhaps something can be done so OpenSSL doesn't see this define at all.?

**Comment by ZheTing815** [comment]
There is one way that we add ```#undef fallthrough``` in OpenSSL. So that OpenSSL won't use the definition in OP-TEE.

But it seems not good, that means anyone use ```fallthrough``` in toolchain or C++ need to do that.

**Comment by jenswi-linaro** [comment]
Perhaps you're trying to fix the error in the wrong place.
Using `#define OPENSSL_FALLTHROUTH __attribute__((__fallthrough__))` should also work if I'm not mistaken.

**Comment by ZheTing815** [comment]
Sorry, I think I have wrong explanation.

If there is a definition ```#define OPENSSL_FALLTHROUTH __attribute__((__fallthrough__))```, like [this](https://github.com/google/boringssl/blob/master/crypto/internal.h#L198). When we use ```OPENSSL_FALLTHROUTH```, it references the ```fallthrough``` in OP-TEE's ```compiler.h```. Therefore it will be extended to ```__attribute__ ((__attribute__((__fallthrough__))))```.

In OP-TEE's compiler.h
```
#if __has_attribute(__fallthrough__)
#define fallthrough __attribute__((__fallthrough__))
#else
#define fallthrough do {} while (0) /* fallthrough */
#endif
```
In other header
```
#define OPENSSL_FALLTHROUTH _attribute_((fallthrough))
```
So, ```OPENSSL_FALLTHROUTH ``` is extended to ```__attribute__((__attribute__((fallthrough))))```.

**Comment by jenswi-linaro** [comment]
What are we trying to fix, when does this error occur? I assume not when compiling optee_os since we don't compile that with OpenSSL.

**Comment by ZheTing815** [comment]
Our TA will compile with OpenSSL, so it will reference the header in optee os.

**Comment by jenswi-linaro** [comment]
We're following the Linux kernel approach with the `fallthrough` macro. I guess we need to find a way to avoid exposing this macro to user space.

**Comment by jforissier** [comment]
> We're following the Linux kernel approach with the `fallthrough` macro. I guess we need to find a way to avoid exposing this macro to user space.

`#ifndef __KERNEL__`? It's defined for the TEE core only (in `core/core.mk`).

**Comment by jenswi-linaro** [comment]
OK, fine with me.
