### ISSUE TITLE
How can I add a library to TA?

### ISSUE THREAD

**Issue by qq8512852** [OP-TEE/optee_os#5503]
I compiled a .a/.so library which just implement easy function. (compiler toolchain is form toolchains folder)
How can I add it to TA?
I tried to add some code in the Makefile which in the ta_dev_kit.mk as follow: 
“libdirs  += /home/wubo/Desktop/temp/create-so/lib/build
libnames += MyTestLib
libdeps  += /home/wubo/Desktop/temp/create-so/lib/build/libMyTestLib.a”
However it can't complied successfully:
"make[3]: *** No rule to make target 'lMyTestLib', needed by 'out/f4e750bb-1437-4fbf-8785-8d3580c36abb.elf'.  Stop.
make[2]: *** [package/pkg-generic.mk:296: /home/wubo/Desktop/code/optee-0822/out-br/build/optee_examples_ext-1.0/.stamp_built] Error 2"

I'm looking forward to your help.
Thanks.

**Comment by qq8512852** [comment]
somebody can help me?

**Comment by jenswi-linaro** [comment]
Did you check https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-do-i-link-a-library-into-a-trusted-application and all the links?

**Comment by qq8512852** [comment]
> Did you check https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-do-i-link-a-library-into-a-trusted-application and all the links?

Thanks. Let me have a check.
