### ISSUE TITLE
OP-TEE PTA  size for heap and stack ?

### ISSUE THREAD

**Issue by hvmr-psicontrol** [OP-TEE/optee_os#5517]
Hi,

I am developing a PTA at this moment, and I would like to know if it is possible to adapt the stack and heap size for this specific application.

I have read the FAQ concerning stack and heap size of a TA, but I didn't find similar information concerning a PTA.
They are built along with and statically built into to the OP-TEE core blob. What configuration files may help me changing the stack and heap size values ?

Thanks

**Comment by jforissier** [comment]
Hello @hvmr-psicontrol,

PTAs are executed in a TEE core thread context. Therefore the stack size is STACK_THREAD_SIZE defined in `core/arch/arm/include/kernel/thread_private_arch.h`. You can increase it via `CFG_STACK_THREAD_EXTRA` (default 0).
Unsurprisingly the heap is the TEE core heap, which can be controlled via `CFG_CORE_HEAP_SIZE` (but note that increasing it will reduce the amount of memory allocated to user space TAs).

**Comment by hvmr-psicontrol** [comment]
Thanks @jforissier 

I am working on an optee os master branch taken one year ago (between 3.14.0 and 3.15.0). My target is a sabrelite development board (iMX6quad). 

So, I found the STACK_THREAD_SIZE definition in  **core/arch/arm/kernel/thread.c** and the CFG_CORE_HEAP_SIZE in **mk/config.mk**. 

Is that OK to change the values in both files ?

**Comment by jforissier** [comment]
Yes, it should be OK. For `CFG_CORE_HEAP_SIZE` you can add it to `core/arch/arm/plat-imx/conf.mk` to avoid impacting other platforms (although in a dev environment you probably don't care much...). For `STACK_THREAD_SIZE`, if `CFG_STACK_THREAD_EXTRA` doesn't exist in your version then yes you will need to change it in `core/arch/arm/kernel/thread.c`.

**Comment by hvmr-psicontrol** [comment]
Thanks again @jforissier
