### ISSUE TITLE
core_mmu_add_mapping() granule size wether support 4KB？

### ISSUE THREAD

**Issue by curtyang** [OP-TEE/optee_os#5521]
Hi , maintainer:
In core_mmu_add_mapping() requested physical address rounded up/down to granule size 2MB(0x200000), granule size wether support 4KB？expecting feedback，version:3.12.

**Comment by curtyang** [comment]
Hi , maintainer:
expecting feedback, thanks.

**Comment by jenswi-linaro** [comment]
What's the question? You've noticed that the effective granule is 2MB, but you'd like to use 4kB instead?

**Comment by curtyang** [comment]
> What's the question? You've noticed that the effective granule is 2MB, but you'd like to use 4kB instead?

Yes, I want to use 4KB granule size, pls help to provide support, thanks.

**Comment by jenswi-linaro** [comment]
Depending on your use-case, perhaps `core_mmu_map_pages()` is an option.

**Comment by curtyang** [comment]
> Depending on your use-case, perhaps `core_mmu_map_pages()` is an option.
Hi Jenswi:
Thank you for your prompt reply.
From the code point of view, the functions of core_mmu_map_pages and core_mmu_add_mapping are different.
1 core_mmu_map_pages() is map list of pages at given virtual address.
2 core_mmu_add_mapping is to convert physical addresses into virtual addresses for TOS use according to attributes.
  Core_mmu_add_mapping and core_mmu_remove_mapping are used together to complete physical address map and unmap  
  actions for TOS.
For example, there is such a scenario, uboot puts some data on DDR, the physical address is pa, and it needs TOS access (with cache, no need to flush cache). It can be done as follows:
vaddr_t *va;        
*va = (vaddr_t)core_mmu_add_mapping(MEM_AREA_RAM_NSEC, pa, 0x10000);
The current problem is that the granularity of core_mmu_add_mapping is 2MB (2MB can also be satisfied, but the software is not friendly to use), and the granularity we need is 4KB, thanks.

**Comment by jenswi-linaro** [comment]
What's the problem with mapping a bit more than needed? I assume you're unmapping at some point too.

**Comment by curtyang** [comment]
> What's the problem with mapping a bit more than needed? I assume you're unmapping at some point too.
There is no problem, that is, the granularity of 2MB is too large, and it is not very friendly to software use. Can it support the granularity of 4KB now.

**Comment by jenswi-linaro** [comment]
Generally, I believe that the 2MB granularity used by `core_mmu_add_mapping()` is good enough and you have confirmed that it's not a problem. So what is it that needs to be fixed? Mapping using 4kB pages just because it feels better isn't a technical argument. Mapping using 4kB pages costs more memory than mapping using 2MB sections.

**Comment by curtyang** [comment]
So what is it that needs to be fixed?

> Generally, I believe that the 2MB granularity used by `core_mmu_add_mapping()` is good enough and you have confirmed that it's not a problem. So what is it that needs to be fixed? Mapping using 4kB pages just because it feels better isn't a technical argument. Mapping using 4kB pages costs more memory than mapping using 2MB sections.
Thanks for your strong suuport.
Is granularity software configurable? For example through macros.In this way, the software configures different granularities according to different scenarios.

**Comment by jenswi-linaro** [comment]
It's not exactly configurable, it depends on how translation tables are initialized.
The function `assign_mem_granularity()` sets granularity for `MEM_AREA_RES_VASPACE` which is used in this case.
