### ISSUE TITLE
tee_ta_open_session init session failed 0xffff000c

### ISSUE THREAD

**Issue by jiang-12345678** [OP-TEE/optee_os#5526]
Hi Team,
  We are seeing the below error in TA execution.
tee_ta_open_session:721 init session failed 0xffff000c

I have change CFG_CORE_HEAP_SIZE from 131072 to 262144,the failure have existed.

Kindly provide us with suggestions on how to resolve this.

I have added debugs to code .
root@localhost:~# xtest -t regression 1004
Test ID: 1004
RD/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
un test suite with level=0

TEE test applicatiD/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
on started over default TEE instD/LD:  ldelf:134 Loading TS cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
ance
##########D/TC:? 0 ldelf_syscall_open_bin:145 Lookup user TA ELF cb3e5ba0-adf1-11e0-998b-0002a5d5c51b (Secure Storage TA)
################################D/TC:? 0 tee_svc_storage_file_ops:33 CFG_REE_FS!
############
#
# regression
#D/TC:? 0 ree_fs_open_primitive:415 create =0

##############################D/TC:? 0 rpc_shm_mobj_alloc:292 entry 1
########################
 
* rD/TC:? 0 get_rpc_arg:401 arg is null
egression_1004 TDest User Crypt /TC:? 0 get_rpc_arg:424 params[0].attr is 0x1!
A
D/TC:? 0 get_rpc_arg:426 params[0].vlue.a is 0x0!
D/TC:? 0 get_rpc_arg:428 params[0]vlue.b is 0x1000!
D/TC:? 0 get_rpc_arg:430 params[0].vlue.c  is 0x8!
D/TC:? 0 get_rpc_arg:469 arg->params[0].attr  is 1!
D/TC:? 0 get_rpc_arg:471 arg->ret  is -65536!
D/TC:? 0 thread_rpc_alloc:631 entry  thread_rpc_alloc

^CD/TC:? 0 get_rpc_alloc_res:562 arg->num_params is 1
D/TC:? 0 get_rpc_alloc_res:563 arg->ret  is 0xffff000c
D/TC:? 0 get_rpc_alloc_res:567 arg is null
D/TC:? 0 thread_rpc_shm_cache_alloc:1682 mobj null!
D/TC:? 0 operation_open_dfh:44 thread_rpc_shm_cache_alloc null!
D/TC:? 0 ree_fs_open_primitive:421 res=0xffff000c
D/TC:? 0 tee_fs_dirfile_open:131 res=0xffff000c
D/TC:? 0 tee_fs_dirfile_open:168 res=0xffff000c
D/TC:? 0 get_dirh:570 res=0xffff000c
D/TC:? 0 ree_fs_open:622 res=0xffff000c
D/TC:? 0 ree_fs_open:655 res=0xffff000c
D/TC:? 0 tadb_open:234 res=0xffff000c
D/TC:? 0 tee_tadb_open:253 res=0xffff000c
D/TC:? 0 tee_tadb_ta_open:658 res=0xffff000c
D/TC:? 0 secstor_ta_open:22 res=0xffff000c
D/TC:? 0 ldelf_syscall_open_bin:149 res=0xffff000c
E/LD:  init_elf:437 sys_open_ta_bin(cb3e5ba0-adf1-11e0-998b-0002a5d5c51b)
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff000c
D/TC:? 0 tee_ta_open_session:721 init session failed 0xffff000c

now 
ta_operation_open 
        |
thread_rpc_shm_cache_alloc
        |
alloc_shm
        |
thread_rpc_alloc_payload
       |
thread_rpc_alloc

thread_rpc_alloc return NULL，so ta_operation_open return 0xffff000c

**Comment by jiang-12345678** [comment]
static struct mobj *thread_rpc_alloc(size_t size, size_t align, unsigned int bt)
{
	uint32_t rpc_args[THREAD_RPC_NUM_ARGS] = { OPTEE_SMC_RETURN_RPC_CMD };
	void *arg = NULL;
	uint64_t carg = 0;
	struct thread_param param = THREAD_PARAM_VALUE(IN, bt, size, align);
	uint32_t ret = get_rpc_arg(OPTEE_RPC_CMD_SHM_ALLOC, 1, &param,
				   &arg, &carg);

	if (ret)
    {
        DMSG ("ge_rpc_arg null\n");
		return NULL;
   }
    DMSG ("entry  thread_rpc_alloc\n");
	reg_pair_from_64(carg, rpc_args + 1, rpc_args + 2);
	thread_rpc(rpc_args);

	return get_rpc_alloc_res(arg, bt);
}

struct mobj *thread_rpc_alloc_payload(size_t size)
{
	return thread_rpc_alloc(size, 8, OPTEE_RPC_SHM_TYPE_APPL);
}

which function calls handle_rpc_func_cmd_shm_alloc?

**Comment by jforissier** [comment]
As I said `handle_rpc_func_cmd_shm_alloc()` is in the linux driver: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/tee/optee/smc_abi.c?h=v6.0-rc4#n776
`process_alloc()` is in `tee-supplicant`: https://github.com/OP-TEE/optee_client/blob/3.18.0/tee-supplicant/src/tee_supplicant.c#L653

**Comment by jiang-12345678** [comment]
Hi Jforlssler,
  tee-supplicant is a demo serving the Trusted OS.
  linux/drivers/tee is driver of linux kernel.handle_rpc_func_cmd_shm_alloc is part of linux driver.

   now function optee_supp_thrd_req  return NULL,and req->ret = TEEC_ERROR_COMMUNICATION，so handle_rpc_func_cmd_shm_alloc return NULL;

 handle_rpc_func_cmd_shm_alloc
           |
  cmd_alloc_suppl
           |
optee_supp_thrd_req


u32 optee_supp_thrd_req(struct tee_context *ctx, u32 func, size_t num_params,
			struct tee_param *param)

{
	struct optee *optee = tee_get_drvdata(ctx->teedev);
	struct optee_supp *supp = &optee->supp;
	struct optee_supp_req *req;
	bool interruptable;
	u32 ret;

	/*
	 * Return in case there is no supplicant available and
	 * non-blocking request.
	 */
	if (!supp->ctx && ctx->supp_nowait)
	{
	        pr_err("supp->ctx is null!\n");
		return TEEC_ERROR_COMMUNICATION;
	}

	req = kzalloc(sizeof(*req), GFP_KERNEL);
	if (!req)
	{
	        pr_err("kzalloc is null!\n");
		return TEEC_ERROR_OUT_OF_MEMORY;
	}

	init_completion(&req->c);
	req->func = func;
	req->num_params = num_params;
	req->param = param;

	/* Insert the request in the request list */
	mutex_lock(&supp->mutex);
	list_add_tail(&req->link, &supp->reqs);
	req->in_queue = true;
	mutex_unlock(&supp->mutex);

	/* Tell an eventual waiter there's a new request */
	complete(&supp->reqs_c);

	/*
	 * Wait for supplicant to process and return result, once we've
	 * returned from wait_for_completion(&req->c) successfully we have
	 * exclusive access again.
	 */
	while (wait_for_completion_interruptible(&req->c)) {
		mutex_lock(&supp->mutex);
		interruptable = !supp->ctx;
		if (interruptable) {
			/*
			 * There's no supplicant available and since the
			 * supp->mutex currently is held none can
			 * become available until the mutex released
			 * again.
			 *
			 * Interrupting an RPC to supplicant is only
			 * allowed as a way of slightly improving the user
			 * experience in case the supplicant hasn't been
			 * started yet. During normal operation the supplicant
			 * will serve all requests in a timely manner and
			 * interrupting then wouldn't make sense.
			 */
			if (req->in_queue) {
				list_del(&req->link);
				req->in_queue = false;
			}
		}
		mutex_unlock(&supp->mutex);

		if (interruptable) {
		        pr_err("interruptable is true!\n");              ------------failure here
			req->ret = TEEC_ERROR_COMMUNICATION;
			break;
		}
	}

	ret = req->ret;
	kfree(req);

	return ret;
}

**Comment by jenswi-linaro** [comment]
Does this fail all the time, that is, you never ever succeed in loading any TA? What's the "demo" tee-supplicant? It looks like there is no supplicant running and the client process has received a signal.

**Comment by jiang-12345678** [comment]
no,regression 1001 1002  test success!
root@localhost:~# xtest -t regression 1001
Test ID: 1001
Run test suite wiD/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
th level=0

TEE test applicatiD/TC:? 0 tee_ta_init_pseudo_ta_session:312 Open invoke_tests.pta
on started over default TEE instD/TC:? 0 tee_ta_init_pseudo_ta_session:329 invoke_tests.pta : d96a5b40-c3e5-21e3-8794-1002a5d5c61b
ance
##########D/TC:? 0 create_ta:384 create entry point for pseudo TA "invoke_tests.pta"
################################D/TC:? 0 open_session:397 open entry point for pseudo ta "invoke_tests.pta"
############
#
# regression
#D/TC:? 0 tee_ta_close_session:512 csess 0xfc10b350 id 1

##############################D/TC:? 0 tee_ta_close_session:531 Destroy session
########################
 
* rD/TC:? 0 close_session:403 close entry point for pseudo ta "invoke_tests.pta"
egression_1001 Core self tests
D/TC:? 0 destroy_ta:390 destroy entry point for pseudo ta "invoke_tests.pta"
  regression_1001 OK
+-----------------------------------------------------
Result of testsuite regression filtered by "1001":
regression_1001 OK
+-----------------------------------------------------
2 subtests of which 0 failed
1 test case of which 0 failed
91 test cases were skipped
TEE test application done!
root@localhost:~# xtest -t regression 1002
Test ID: 1002
RD/TC:? 0 tee_ta_init_session_with_context:607 Re-open TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
un test suite with levelD=0

T/TC:? 0 create_ta:384 create entry point for pseudo TA "invoke_tests.pta"
E test application staDrted over/TC:? 0 open_session:397 open entry point for pseudo ta "invoke_tests.pta"
default TEE instance
##########D/TC:? 0 test_entry_params:179 expect memref params: 0xf4801000/16384 - 0x0/0zu - 0x0/0zu - 0x0/0zu
######################D#########/TC:? 0 tee_ta_close_session:512 csess 0xfc10b1f0 id 1
############
D/TC:? 0 tee_ta_close_session:531 Destroy session

# regression
#
##############D/TC:? 0 close_session:403 close entry point for pseudo ta "invoke_tests.pta"
################################D/TC:? 0 destroy_ta:390 destroy entry point for pseudo ta "invoke_tests.pta"
########
 
* regression_1002 PTA parameters
  regression_1002 OK
+-----------------------------------------------------
Result of testsuite regression filtered by "1002":
regression_1002 OK
+-----------------------------------------------------
3 subtests of which 0 failed
1 test case of which 0 failed
91 test cases were skipped
TEE test application done!

**Comment by jiang-12345678** [comment]
Hi,
all tests  about  handle_rpc_func_cmd_shm_alloc return null!

regards,
jiang

**Comment by jiang-12345678** [comment]
Hi,
 Thank you for your reply.
  What's the "demo" tee-supplicant?
  The demo tee-supplicant is not up.

   The folder (/date/tee) can be created when the tee-supplicant start.
  
 the reason is  start tee-supplicant with root.
Thank you !

regards,
jiang

**Comment by jforissier** [comment]
> no,regression 1001 1002 test success!

These tests load no TA, they invoke a pseudo-TA.

>  The demo tee-supplicant is not up.
> The folder (/date/tee) can be created when the tee-supplicant start.
>  the reason is start tee-supplicant with root.

I think we need to make the troubleshooting of this kind of configuration issues easier in the future. Back to the initial error:

```
E/LD: init_elf:437 sys_open_ta_bin(cb3e5ba0-adf1-11e0-998b-0002a5d5c51b)
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff000c
```

In my opinion this message is misleading (`0xffff000c` = `TEE_ERROR_OUT_OF_MEMORY`). There is no memory shortage involved anywhere, especially not in the TEE core. Since the real cause of the error was that RPC was interrupted, I'd much rather see `TEE_ERROR_COMMUNICATION` here. It would give a strong hint that something is wrong in the Normal World. Or we could at least print one more error line when the RPC error occurs. I will propose a patch.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/5530
