### ISSUE TITLE
Port OPTEE_OS to normal world?

### ISSUE THREAD

**Issue by shumeigiku** [OP-TEE/optee_os#5533]
Hi all,

I want to migrate OP-TEE's secure OS to normal world. 
I am not sure whether it is feasible, and not sure whether someone has done it. So I ask here, and, discuss my idea.

In ATF, we reserve a "shared" memory region (I mean, in TZASC we allow both secure and non-secure to access this region) to load the OP-TEE kernel.
When entering Linux and OP-TEE client communicate with the kernel, we can configure ATF to let the the op-tee smc handler jump to normal world. The context switch can be done in ATF, so we do not need KVM virtualization here.
Then we perform some tests, and exit OP-TEE OS.

Is it feasible? Is there something I forget?

Sincerely,
shumeigiku

**Comment by jenswi-linaro** [comment]
> Is it feasible? Is there something I forget?

Without a hypervisor at EL2 there would be no isolation between Linux and OP-TEE, that is, the Linux kernel could map the physical memory used by OP-TEE.

**Comment by shumeigiku** [comment]
Thanks for your reply!

Actually, I just wanna test something (e.g., compare the performance when OP-TEE runs in secure/non-secure world) and not consider its security. I know my idea is not "secure", but I just wanna know "whether it is feasible".

So it is feasible to move OP-TEE into normal world? If yes, how can I do it?

**Comment by jenswi-linaro** [comment]
I believe there shouldn't be much problem running OP-TEE in non-secure mode as long as all used resources (memory and devices) are non-secure. You'd need to hack a bit on the OP-TEE dispatcher in TF-A.
