### ISSUE TITLE
When entering OP-TEE, how to correctly configure SCR_EL3.EEL2?

### ISSUE THREAD

**Issue by irakatz** [OP-TEE/optee_os#5537]
Greetings,
When I try to configure Armv8.4 (SEL2) features with running a OP-TEE (but no Hafnium), I face some problems. Here are my operations and faults:

1. I write a fast optee smc (I set the x0 as 0xFF000001) and try to catch it in the corresponding handler, it is OK.
2. Then, want to configure SCR_EL3.EEL2 bit as 1 when entering OP-TEE. To do it, in tf-a/services/spd/opteed/opteed_main.c file's opteed_smc_handler() function, I enable SCR_EEL2_BIT before returning to secure world context, like this.

...
		/* Propagate hypervisor client ID */
		write_ctx_reg(get_gpregs_ctx(&optee_ctx->cpu_ctx),
			      CTX_GPREG_X7,
			      read_ctx_reg(get_gpregs_ctx(handle),
					   CTX_GPREG_X7));
		write_ctx_reg(get_el3state_ctx(&optee_ctx->cpu_ctx), CTX_SCR_EL3, read_scr_el3()|SCR_EEL2_BIT); //Added by me
		SMC_RET4(&optee_ctx->cpu_ctx, smc_fid, x1, x2, x3);
}

3. Then, when I call the smc, it gets a permission fault (ESR_EL3=0x86000006, ELR_EL3=0x60018e8), the ELR_EL3 points to the following code:
00000000060018e4 <thread_vector_table>:
...
 60018e8:	17ffffb1 	b	60017ac <vector_fast_smc_entry>
...

It seems that, even though I have not enabled the secure Stage-2 translation (HCR_EL2's last bit is 0), OP-TEE still rejects the SEL2. I am not sure what happen, and how can I fix this problem.

I am not using Hafnium, so my building command of TF-A sets "SPD=opteed", and BL32 points to OP-TEE's bin (I follow the configurations in the provided docs).

Can someone help me?

**Comment by irakatz** [comment]
Sorry, after I read the manual, it is a translation fault, not permission fault.

**Comment by jenswi-linaro** [comment]
Perhaps there's something more with S-EL2 that needs to be disabled.

**Comment by irakatz** [comment]
Thanks, 
I re-configure the HCR_EL2 registers and it works.
