### ISSUE TITLE
optee_os free_wipe() performance issue

### ISSUE THREAD

**Issue by zjuzzy** [OP-TEE/optee_os#5542]
Hi all,

When I set CFG_CORE_HEAP_SIZE to 70 MB during the test on the FPGA, it takes a long time. After analysis, I found that when using ```void free_wipe(void *ptr)```, the range of memset 0x55 may be greater than the length of the memory space I need to free.

I found that developers raised similar issues in 2019 (https://github.com/OP-TEE/optee_os/issues/3374) . But no one seems to be offering a solution.

We have fixed the problem and passed the test. Can I submit a patch to optee_os?

**Comment by jforissier** [comment]
Hi @zjuzzy,

> We have fixed the problem and passed the test. Can I submit a patch to optee_os?

Please do, we will gladly review it.

**Comment by zjuzzy** [comment]
> Hi @zjuzzy,
> 
> > We have fixed the problem and passed the test. Can I submit a patch to optee_os?
> 
> Please do, we will gladly review it.

Thanks for your reply, we will submit PR as soon as possible.
