### ISSUE TITLE
TA_FLAG_INSTANCE_KEEP_ALIVE

### ISSUE THREAD

**Issue by youssefesmat** [OP-TEE/optee_os#555]
Hello,

In function tee_ta_load(), TA_FLAG_INSTANCE_KEEP_ALIVE is not one of the allowed optional flags. Are there plans to add it in the future or has it been left out for a specific reason?

Thank you,
Youssef

**Comment by jenswi-linaro** [comment]
Hi Youssef,

I think that `TA_FLAG_INSTANCE_KEEP_ALIVE` has been left out of `opt_flags` by mistake.

I would welcome a PR to fix this. :-)

Thanks,
Jens

**Comment by pascal-brand-st** [comment]
Implemented in https://github.com/OP-TEE/optee_os/pull/602
