### ISSUE TITLE
How to get normal world linux kernel log? (QEMU_v8)

### ISSUE THREAD

**Issue by ubisun** [OP-TEE/optee_os#5560]
Hello, I'm trying to add a testing linux kernel feature for OPTEE.
When I run QEMU_v8, linux kernel logs are printed out, but the output console is changed to buildroot prompt.
After login test/root account, I can see only initial boot part of kernel log with dmesg.
Is there any way to see linux kernel log?

**Comment by jforissier** [comment]
Hello @ubisun,

You should be able to see the full boot log by scrolling back in your terminal. I personally use gnome-terminal with 10000 lines of scrollback history. See also https://github.com/OP-TEE/build/pull/598 which may be helpful.

**Comment by DevendraDevadiga** [comment]
@ubisun You can refer this guide also:
https://github.com/DevendraDevadiga/optee_qemu_armv8a_prebuilt_binaries
https://www.youtube.com/playlist?list=PLrwOamjP8JAKZ3hIdH1z3hxvYSq7XoI8d
