### ISSUE TITLE
Using `stat()` on OPTEE secure storage files from normal world

### ISSUE THREAD

**Issue by NoxiousFly** [OP-TEE/optee_os#5564]
I have stored multiple certificates in OPTEE secure storage and I would like to know the last updated time of certificate file using `stat()`.

As all the certificate object is assigned with internal integer identifier like `/conf/tee/<file number>`. Couldn't identify the certificate object file.

Is any way available to find the absolute path of certificate path from normal world?

**Comment by jenswi-linaro** [comment]
I'm afraid that the short answer is no.

**Comment by NoxiousFly** [comment]
@jenswi-linaro Thanks,

I have other question related to secure storage files.

Initially Secure storage default path has some files like below.

```
~ # ls /data/tee/ -l
total 53
-rw------- 1 sysadmin sysadmin 4228 Dec 31 1999 0
-rw------- 1 sysadmin sysadmin 16384 Dec 31 1999 1
-rw------- 1 sysadmin sysadmin 16384 Dec 31 1999 2
-rw------- 1 sysadmin sysadmin 16384 Dec 31 1999 dirf.db
```

After I added some files to secure storage, new file is created with integer name 3 and deleted file 2.

```
~ # ls /data/tee/ -l
total 53
-rw------- 1 sysadmin sysadmin 4228 Dec 31 1999 0
-rw------- 1 sysadmin sysadmin 16384 Dec 31 1999 1
-rw------- 1 sysadmin sysadmin 16384 Oct 4 17:47 3
-rw------- 1 sysadmin sysadmin 16384 Oct 4 17:47 dirf.db
```

Then after , If i add any file. The file created in order 3, 2 , 4 , 5 , 6 ..etc

```
~ # ls -l /conf/tee/
total 101
-rw-------    1 sysadmin sysadmin      4228 Dec 31  1999 0
-rw-------    1 sysadmin sysadmin     16384 Dec 31  1999 1
-rw-------    1 sysadmin sysadmin     16384 Oct 4 08:17 2
-rw-------    1 sysadmin sysadmin     16384 Oct 4 08:14 3
-rw-------    1 sysadmin sysadmin     16384 Oct 4 08:17 4
-rw-------    1 sysadmin sysadmin     16384 Oct 4 08:17 6
-rw-------    1 sysadmin sysadmin     16384 Oct 4 08:17 dirf.db
```

Could you please explain , why files created in this order.

**Comment by jenswi-linaro** [comment]
That's due to the internals of the REE FS based secure storage implementation.

**Comment by jenswi-linaro** [comment]
> Is it possible to know more about
> 
> > internals of the REE FS based secure storage implementation.

Sure, see https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_ree_fs.c and https://optee.readthedocs.io/en/latest/architecture/secure_storage.html#ree-fs-secure-storage

> 
> Current file creation order is 3, 2 , 4 , 5 , 6 ..etc . Is it possible to change in correct order 3 , 4 , 5 ... etc.

Note very likely.
