### ISSUE TITLE
Assign more Heap Memory for PTA

### ISSUE THREAD

**Issue by f1bu** [OP-TEE/optee_os#5575]
Hi,

for my application I need more heap memory for a PTA. In  #5517 it was stated that CFG_CORE_HEAP_SIZE needs to be modified. I tried to set the value in conf.mk from 49152 to 98304 for testing. Now the board does not boot anymore and ends up with an error
 **Panic 'Impossible memory alignment' at ?:0**
I also tried other values, but with the same result. Theoretically there should be enough free memory for a larger heap (stats --alloc shows that only 630KB of 32MB secure memory are allocated), so I'm wondering what went wrong.

I'm working with a STM32MP157A-DK1 board. Any help would be appreciated.

**Comment by etienne-lms** [comment]
@f1bu, very late reply, sorry, I missed your post.
STM32MP15 has an 256kByte internal secure RAM where OP-TEE runs with pager enabled (`CFG_WITH_PAGER=y`). Pager needs a pool of free physical pages to operate. Core heap is pager resisdent memory so the more is provisionned to the heap, the less remains for the pager page pool.

**Comment by f1bu** [comment]
Thanks, that nudged me into the right direction to understand OPTEE memory management better.
