### ISSUE TITLE
Can PTA open a session of USER TA?

### ISSUE THREAD

**Issue by weizhaojiang** [OP-TEE/optee_os#5579]
A quick question is can PTA(like stats.ta) call TEE_OpenTASession() to open a user TA and then call invoke CMDs to handle something?

when I edit core/pta/stats.c and let it open a user TA's session. it report below error:

OP-TEE/optee-master/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-ld.bfd: out/arm/core/pta/stats.o: in function `get_ta_memstats':
OP-TEE/optee-master/optee_os/core/pta/stats.c:42: undefined reference to `TEE_OpenTASession'

any suggestion?

Thanks.

**Comment by etienne-lms** [comment]
Sorry, there is no PTA->TA invocation schemes. You would need to implement functions like `pta_open_ta_session()`/`pta_invoke_ta_command()`/`pta_close_session()` to forge the ABIs and call the generic `tee_ta_open_session()`/`tee_ta_invoke_command()`/... with. PTA shold be very careful with the memory it exposes to a TA. To pass a secure buffer memref, you shall use only pages allocated from `mempool_default` mempool. I think it's doable, unless I missed something.

**Comment by jenswi-linaro** [comment]
I'm not so sure about the `mempool_default` part.

**Comment by weizhaojiang** [comment]
thanks for the helpful info.
