### ISSUE TITLE
Errors like "undefined reference to `__aeabi_dcmpeq' "

### ISSUE THREAD

**Issue by fanguannan0706** [OP-TEE/optee_os#558]
Hi,
I tried to make a library and revise ta.mk and ta_dev_kit.mk, so the ta can use it. But it report errors like this:
undefined reference to `__aeabi_dcmpeq'
undefined reference to `__aeabi_dmul'
undefined reference to `__aeabi_dcmplt'
undefined reference to `__aeabi_ddiv'
undefined reference to `__aeabi_dcmpge'
undefined reference to `__aeabi_d2uiz'
undefined reference to `__aeabi_ui2d'
undefined reference to `__aeabi_dsub'
I think it because the kernel can't support floating point operation. So how can I solve it?

**Comment by vchong** [comment]
Ref https://github.com/OP-TEE/optee_os/issues/442

**Comment by jbech-optee-adm** [comment]
Question has been answered and therefore I'm closing the issue, please re-open if you have follow up questions.
