### ISSUE TITLE
RPMB virtualization

### ISSUE THREAD

**Issue by jingdlu** [OP-TEE/optee_os#5581]
Hi experts,

1, If I try to enable virtualization feature in OP-TEE by CFG_VIRTUALIZATION flag to serve multiple REE instances, how to operate RPMB in this scenario?
2, If there is the solution, is this code already in OP-TEE?

Thanks,
Jingdong

**Comment by jenswi-linaro** [comment]
That's an excellent question. Unfortunately, we don't have a solution for this in OP-TEE yet.

**Comment by jingdlu** [comment]
Thanks for the confirmation.
