### ISSUE TITLE
How to change the entry point of optee from 0xff000000 to 0xff200000? Thanks!

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5592]

**Comment by etienne-lms** [comment]
`CFG_TZDRAM_START` is usually used as both secure RAM base address and OP-TEE entry point.
If you wantr OP-TEE load address/entry point to be at a offset from secure RAM start, set also `CFG_TEE_LOAD_ADDR` accordingly. This assumes you don't enable OP-TEE pager.

See https://github.com/OP-TEE/optee_os/blob/3.19.0/core/arch/arm/include/mm/generic_ram_layout.h#L12.

**Comment by zzbios** [comment]
> `CFG_TZDRAM_START` is usually used as both secure RAM base address and OP-TEE entry point. If you wantr OP-TEE load address/entry point to be at a offset from secure RAM start, set also `CFG_TEE_LOAD_ADDR` accordingly. This assumes you don't enable OP-TEE pager.
> 
> See https://github.com/OP-TEE/optee_os/blob/3.19.0/core/arch/arm/include/mm/generic_ram_layout.h#L12.

**Comment by zzbios** [comment]
> `CFG_TZDRAM_START` is usually used as both secure RAM base address and OP-TEE entry point. If you wantr OP-TEE load address/entry point to be at a offset from secure RAM start, set also `CFG_TEE_LOAD_ADDR` accordingly. This assumes you don't enable OP-TEE pager.
> 
> See https://github.com/OP-TEE/optee_os/blob/3.19.0/core/arch/arm/include/mm/generic_ram_layout.h#L12.

Hello! Glad to see your answers. For now, I have the compiled files, **tee_header_v2.bin** and **tee_pager_v2.bin**.
And I have an available ARM UEFI environment. What I want to do is just run the optee os at BL32 with BL31 guiding.
But I encountered the following problems：

INFO:    Image id=4 loaded: 0xff200000 - 0xff20001c
INFO:    Mark image(4) as authenticated
INFO:    SCP unlock SPI success
INFO:    OPTEE ep=0xff200000
INFO:    OPTEE header info:
INFO:          magic=0x4554504f
INFO:          version=0x2
INFO:          arch=0x1
INFO:          flags=0x0
INFO:          nb_images=0x1
WARNING: The load address in optee header 0xff000000 - 0xff09c358 is not in reserved area: 0xff200000 - 0xffc00000.
WARNING: OPTEE header parse error.

It seems that the entry point of OPTEE is 0xff000000 and the entry point of OPTEE the BL31 is also 0xff000000.
So, how to change the entry point of OPTEE? Could you provide some specific operations in terms of OPTEE OS code? 
Thank you!!!

**Comment by etienne-lms** [comment]
Your issue in in TF-A I think. Check the size loaded in `image_max_size` field of `image_info_t` for the optee BL32 (and BL32_EXTRA1/BL32_EXTRA2) images.

**Comment by zzbios** [comment]
> Your issue in in TF-A I think. Check the size loaded in `image_max_size` field of `image_info_t` for the optee BL32 (and BL32_EXTRA1/BL32_EXTRA2) images.

I have printed the BL32 address space: 0xff20 0000 - 0xffc0 0000
and for optee
(header)  ARM_MAP_OPTEE_CORE_MEM: 0xff20 0000 - 0xffc0 0000
(pager) ARM_OPTEE_PAGEABLE_LOAD_MEM: 0xff80 0000 - 0x0xffc0 0000

So where is the problem?

**Comment by etienne-lms** [comment]
Sorry, issue not in TF-A. You're right. I misread your log.

If you build OP-TEE with the expected entry point, _tee-header_v2.bin_ should show this address. You can look into the binary data, there is not much bytes to read.

OP-TEE build process get `_start` symbol from _tee.elf_ file and uses that to set the load address of image _tee-pager_v2.bin_ in OP-TEE header file (_tee-header_v2.bin_). Tool is _scripts/gen_tee_bin.py_. Check your generated _tee.elf_ (or _tee.dmp_) if really embedding `.text` section at 0xff200000.

**Comment by zzbios** [comment]
> Sorry, issue not in TF-A. You're right. I misread your log.
> 
> If you build OP-TEE with the expected entry point, _tee-header_v2.bin_ should show this address. You can look into the binary data, there is not much bytes to read.
> 
> OP-TEE build process get `_start` symbol from _tee.elf_ file and uses that to set the load address of image _tee-pager_v2.bin_ in OP-TEE header file (_tee-header_v2.bin_). Tool is _scripts/gen_tee_bin.py_. Check your generated _tee.elf_ (or _tee.dmp_) if really embedding `.text` section at 0xff200000.

Thank you anyway. As you said, we have looked into **tee-header_v2.bin** with hexdump tool. The **load_addr_lo** data in header is 0xff00 0000, which means that load address of optee os image has been determined when its code is compiled. The next work is to rebuild the **tee-header_v2.bin** with correct **load_addr_lo**.
