### ISSUE TITLE
Merging the RISC-V optee os architecture code

### ISSUE THREAD

**Issue by cck-wcs** [OP-TEE/optee_os#5599]
Hello, I see code based on RISC-V architecture is being added. We also have done some work based on RISC-V, xtest has been successfully passed right now, the whole system includes linux, opensbi, optee os, etc. I wonder if we can participate in to accelerate the support of RISC-V in optee os? Thanks!

**Comment by jenswi-linaro** [comment]
Hi @cck-wcs,

Your help is most welcome! Please try to synch up with @maroueneboubakri on how to proceed.
I hope we should be able to speed things up a bit.

**Comment by cck-wcs** [comment]
> Hi @cck-wcs,
> 
> Your help is most welcome! Please try to synch up with @maroueneboubakri on how to proceed. I hope we should be able to speed things up a bit.
Hi @maroueneboubakri , is there anything we can do?.

**Comment by cck-wcs** [comment]
Hi @maroueneboubakri , is there anything we can do?.

**Comment by jenswi-linaro** [comment]
I think it would be nice if you could compare design decisions with each other. Given that @cck-wcs has something that is passing xtest it should be quite advanced. @maroueneboubakri, have you been able to pass xtest with your stuff?

**Comment by maroueneboubakri** [comment]
Hi @jenswi-linaro, Yes, was able to pass xtest also but without the need to implement everything especially memory manager.

**Comment by cck-wcs** [comment]
Hi @jenswi-linaro @maroueneboubakri , comparing designs is a really good idea. Since many design points need to be compared, which method is better? Do you have any good suggestions? Thank you very much.

**Comment by jenswi-linaro** [comment]
@cck-wcs, I'd start with looking at what's in https://github.com/OP-TEE/optee_os/pull/5606
While stuff is still reviewed it's much easier to have concerns addressed, once it's merged it will take more effort if something needs to change approach or whatever.

Apart from that, I guess you have some key points you care about more than others. Check that against what @maroueneboubakri  has done.

**Comment by cck-wcs** [comment]
> @cck-wcs, I'd start with looking at what's in #5606 While stuff is still reviewed it's much easier to have concerns addressed, once it's merged it will take more effort if something needs to change approach or whatever.
>  Hi @jenswi-linaro, does that mean we'll discuss how to commit our code after #5506 is merged?
> Apart from that, I guess you have some key points you care about more than others. Check that against what @maroueneboubakri has done.
>  We'll take look at @maroueneboubakri 's submission.

**Comment by jenswi-linaro** [comment]
> > @cck-wcs, I'd start with looking at what's in #5606 While stuff is still reviewed it's much easier to have concerns addressed, once it's merged it will take more effort if something needs to change approach or whatever.
> 
> 1. > Hi @jenswi-linaro, does that mean we'll discuss how to commit our code after [nist p521 - fix key size #5506](https://github.com/OP-TEE/optee_os/pull/5506) is merged?

I guess you mean #5606 . What happens after #5606 is up to you and @maroueneboubakri . I hope you can find some common ground. Even if @maroueneboubakri was starting to contribute to arch/riscv doesn't mean he's the only one with a say in what goes in.

Timely updates will be excepted now that you're more than one looking to contribute to arch/riscv.

> 
> > Apart from that, I guess you have some key points you care about more than others. Check that against what @maroueneboubakri has done.
> 
> 2. > We'll take look at @maroueneboubakri 's submission.

Thanks.

**Comment by jenswi-linaro** [comment]
> > 
> 
> > > > @cck-wcs, I'd start with looking at what's in #5606 While stuff is still reviewed it's much easier to have concerns addressed, once it's merged it will take more effort if something needs to change approach or whatever.
> > > 
> > > 
> > > 
> > > 1. > Hi @jenswi-linaro, does that mean we'll discuss how to commit our code after [nist p521 - fix key size #5506](https://github.com/OP-TEE/optee_os/pull/5506) is merged?
> > 
> > 
> > > I guess you mean #5606 . What happens after #5606 is up to you and @maroueneboubakri . I hope you can find some common ground. Even if @maroueneboubakri was starting to contribute to arch/riscv doesn't mean he's the only one with a say in what goes in.
> > 
> > 
> > > Timely updates will be excepted now that you're more than one looking to contribute to arch/riscv.
> 
> Does that mean we can start committing patches that have little relevance to arch/riscv?

Sure, but keep in mind that @maroueneboubakri probably has quite a bit more he needs to get upstream before stuff starts to work. There will be only one arch/riscv so you must find a way to pick the best from the two implementations you have.

**Comment by cck-wcs** [comment]
> > > 
> > 
> > 
> > > > > @cck-wcs, I'd start with looking at what's in #5606 While stuff is still reviewed it's much easier to have concerns addressed, once it's merged it will take more effort if something needs to change approach or whatever.
> > > > 
> > > > 
> > > > 
> > > > 1. > Hi @jenswi-linaro, does that mean we'll discuss how to commit our code after [nist p521 - fix key size #5506](https://github.com/OP-TEE/optee_os/pull/5506) is merged?
> > > 
> > > 
> > > > I guess you mean #5606 . What happens after #5606 is up to you and @maroueneboubakri . I hope you can find some common ground. Even if @maroueneboubakri was starting to contribute to arch/riscv doesn't mean he's the only one with a say in what goes in.
> > > 
> > > 
> > > > Timely updates will be excepted now that you're more than one looking to contribute to arch/riscv.
> > 
> > 
> > Does that mean we can start committing patches that have little relevance to arch/riscv? 
> 
> Sure, but keep in mind that @maroueneboubakri probably has quite a bit more he needs to get upstream before stuff starts to work. There will be only one arch/riscv so you must find a way to pick the best from the two implementations you have.

OK. Now, my colleague is preparing the first commit about **ldelf** which is not releated to arch/riscv.

**Comment by liushiwei007** [comment]
> > > > 
> > > 
> > > 
> > > > > > @cck-wcs, I'd start with looking at what's in #5606 While stuff is still reviewed it's much easier to have concerns addressed, once it's merged it will take more effort if something needs to change approach or whatever.
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. > Hi @jenswi-linaro, does that mean we'll discuss how to commit our code after [nist p521 - fix key size #5506](https://github.com/OP-TEE/optee_os/pull/5506) is merged?
> > > > 
> > > > 
> > > > > I guess you mean #5606 . What happens after #5606 is up to you and @maroueneboubakri . I hope you can find some common ground. Even if @maroueneboubakri was starting to contribute to arch/riscv doesn't mean he's the only one with a say in what goes in.
> > > > 
> > > > 
> > > > > Timely updates will be excepted now that you're more than one looking to contribute to arch/riscv.
> > > 
> > > 
> > > Does that mean we can start committing patches that have little relevance to arch/riscv?
> > 
> > 
> > Sure, but keep in mind that @maroueneboubakri probably has quite a bit more he needs to get upstream before stuff starts to work. There will be only one arch/riscv so you must find a way to pick the best from the two implementations you have.
> 
> OK. Now, my colleague is preparing the first commit about **ldelf** which is not releated to arch/riscv.

Hi @jenswi-linaro , #5630  is my commit about ldelf. thanks.
