### ISSUE TITLE
run optee test script error

### ISSUE THREAD

**Issue by neil1899** [OP-TEE/optee_os#560]
hi,all
I run a script to test optee os
such as
while [ 1 ]
do
tee_xtest
sleep 2
done

but after a few  minutes, it will occursomething wrong,  like"out of memory "
log is:
TEE-CORE:write_one_block:818: Failed to allocate plaintext buffer,  case is _6 or _4

* XTEST_TEE_6001 Test TEE_CreatePersistentObject
ERR ERR TEE-CORE:write_one_block:818: Failed to allocate plaintext buffer, size=4096
[-149644308] TEEC:TEEC_InvokeCommand:412: Function returns with [-267386879]
vendor/amlogic/tdk-1.0.1/demos/optee_test/host/xtest/xtest_6000.c:615: fs_create(&sess, file_00, sizeof(file_00), 0x00000002 | 0x00000ERR TEE-CORE:write_one_block:818: Failed to allocate plaintext buffer, size=4096
004, 0, data_00, sizeof(data_00), &obj) has an unexpected value: 0xf0100001 = TEE_ERROR_CORRUPT_OBJECT, expected 0x0 = TEEC_SUCCESS
  XTEST_TEE_6001 FAILED
 
* XTEST_TEE_6002 Test TEE_OpenPersistentObject
ERERR TEE-CORE:write_one_block:818: Failed to allocate plaintext buffer, size=4096
R [-149644308] TEEC:TEEC_InvokeCommand:412: Function returns with [-267386879]
vendor/amlogic/tdk-1.0.1/demos/optee_test/host/xtest/xtest_6000.c:640: fs_create(&sess, file_01, sizeof(file_01), 0x00000002, 0, datERR TEE-CORE:write_one_block:818: Failed to allocate plaintext buffer, size=4096
a_00, sizeof(data_00), &obj) has an unexpected value: 0xf0100001 = TEE_ERROR_CORRUPT_OBJECT, expected 0x0 = TEEC_SUCCESS
  XTEST_TEE_6002 FAILED
what's the problem?

everytime, when run 14times, it must occur
thanks in advance!

**Comment by neil1899** [comment]
it's the ddr problem.

**Comment by neil1899** [comment]
hi all
when i increase the size of TEE_RAM_SIZE to 4M
it can run 20times, i think it's the problem of memory leak.

**Comment by vchong** [comment]
Were you able to solve the problem yourself? Care to share the solution?

**Comment by neil1899** [comment]
on my paltform, i realize the hw crypt, it causes the problem, not the optee os or others.

thanks!
