### ISSUE TITLE
How do we reference the project in Bibtex

### ISSUE THREAD

**Issue by trriger** [OP-TEE/optee_os#5600]
We are going to publish a paper and have implemented our code using OP-TEE's environment. Could you tell us some citation information?

**Comment by zengxiaoxu-HUAWEI** [comment]
I find some answers on Google that might helpful.

```If you're writing a research paper in computer science or another technical discipline, you may want to include source code in your research sources, such as code you find in a GitHub repository. Generally, you should include enough information in your list of references at the end of your paper to enable your reader to locate the code and review it for themselves. However, the specific format of your citation will vary depending on which citation guide you use. In the computer sciences, Institute of Electrical and Electronics Engineers (IEEE), Association for Computing Machinery (ACM), and Council of Science Editors (CSE) citation styles are most commonly used.```

[How to Cite a GitHub Repository](https://www.wikihow.com/Cite-a-GitHub-Repository)

**Comment by trriger** [comment]
> I find some answers on Google that might helpful.
> 
> `If you're writing a research paper in computer science or another technical discipline, you may want to include source code in your research sources, such as code you find in a GitHub repository. Generally, you should include enough information in your list of references at the end of your paper to enable your reader to locate the code and review it for themselves. However, the specific format of your citation will vary depending on which citation guide you use. In the computer sciences, Institute of Electrical and Electronics Engineers (IEEE), Association for Computing Machinery (ACM), and Council of Science Editors (CSE) citation styles are most commonly used.`
> 
> [How to Cite a GitHub Repository](https://www.wikihow.com/Cite-a-GitHub-Repository)
Sorry, because of my carelessness, I wrote the subject of the issue title as "you".
We need to briefly introduce the OP-TEE project in the "related work" section. We have also found some information that is sufficient for reference, so the issue will be closed.
