### ISSUE TITLE
Modify optee syscall but does not work

### ISSUE THREAD

**Issue by smartdabao** [OP-TEE/optee_os#5617]
Hi,

    I am working on IMX8mpevp board，and fsl-release-bsp1-5.4.70-2.3.0 was used, optee-os and optee-client are both 3.10.0. I build optee_examples-3.19.0 random example on the board(run make TA_DEV_KIT_DIR=/usr/include/optee/export-user_ta_arm64/ on random/ta directory, run make on random/host directory), and it worked fine as follows.

```
Invoking TA to generate random UUD/TA: random_number_generate:74 has been called
ID...
I/TA: Generating random data over 16 bytes.
TA generated UUID value = 0xc15b5bb512f9f74b783d263cb1ad751a
```

random example call _utee_cryp_random_number_generate syscall. So I modify syscall_cryp_random_number_generate in optee-os, I add a patch. And I am sure the patch takes effective.

```
--- a/core/tee/tee_svc_cryp.c 2022-10-25 16:13:12.547214327 +0800
+++ b/core/tee/tee_svc_cryp.c 2022-10-25 16:14:32.128618185 +0800
@@ -3172,6 +3172,7 @@

TEE_Result syscall_cryp_random_number_generate(void *buf, size_t blen)
{
+#if 0
struct tee_ta_session *sess = NULL;
TEE_Result res = TEE_SUCCESS;

@@ -3191,6 +3192,9 @@
return res;

return res;
+#endif
+ memset(buf, 0, blen);
+ return TEE_SUCCESS;
}
```

TEE_Result syscall_authenc_init(unsigned long state, const void *nonce,

Then I rebuid optee-os,

`$bitbake -c cleanall optee-os && bitbake optee-os`

Then I got four deb packages, and I copy them to board and use dpkg to install them.

optee-os_3.10.0.imx-r0_arm64.deb

optee-os-dbg_3.10.0.imx-r0_arm64.deb

optee-os-dev_3.10.0.imx-r0_arm64.deb

optee-os-staticdev_3.10.0.imx-r0_arm64.deb

Then I reboot the board. And rebuild random example, copy ta to /lib/optee_armtz/. But its output makes no difference. I also tried to directly modify source code in git directory and use bitbake -c compile -f optee-os && bitbake optee-os, and it still makes no difference. It seems I did not make any change. But the md5 value in /lib/firmware/ directory on board really changed.

So my question is how to modify optee-os code and how to build and deploy it to the board. Thanks.

**Comment by jforissier** [comment]
Hello @smartdabao,

I am not familiar with the build environment you are using for your i.MX8 board, but I would be surprised if you could update OP-TEE using a `.deb` package. OP-TEE is usually contained into a firmware binary image, and depending on how the board boots it may need to be copied onto a SD card with `dd` or transferred into the board's eMMC via USB using some flashing tool.

Hopefully some i.MX8 users will be able to tell more.

**Comment by smartdabao** [comment]
Thanks for your reply @jforissier . 
I am newbie to op-tee. The OP-TEE deb includes files as follows:
drwxr-xr-x root/root         0 2022-10-25 06:42 ./lib/
drwxr-xr-x root/root         0 2022-10-25 06:42 ./lib/firmware/
-rw-r--r-- root/root        28 2022-10-25 06:42 ./lib/firmware/tee-header_v2.bin
-rw-r--r-- root/root         0 2022-10-25 06:42 ./lib/firmware/tee-pageable_v2.bin
-rw-r--r-- root/root    424016 2022-10-25 06:42 ./lib/firmware/tee-pager_v2.bin
-rw-r--r-- root/root    424016 2022-10-25 06:42 ./lib/firmware/tee-raw.bin
-rw-r--r-- root/root    424044 2022-10-25 06:42 ./lib/firmware/tee.bin

Are these sufficient for op-tee os?
