### ISSUE TITLE
What particular files run in the background?

### ISSUE THREAD

**Issue by sabra58** [OP-TEE/optee_os#5629]
I have this question; I was not able to find answer to elsewhere.

What particular files run in the background when example TA or newly created TA is executed. I know TEE CLENT API is called which will in turn call Linux kernel which invoke secure world and will reach optee core and core will transfer the request to the target TA.

BUT pin pointedly what are those files run in the background.

**Comment by jenswi-linaro** [comment]
Perhaps this link answers your questsion: https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#open-session

**Comment by sabra58** [comment]
Sorry Sir ! May I am unable to explain what I am trying to ask , but the link above does not answers my question.

As I mentioned at the first place I know the flow TEE CLENT API is called which will in turn call Linux kernel which invoke secure world and will reach optee core and core will transfer the request to the target TA.

But for each for these above steps which particular c file is excecuted , or else libraries are called?

**Comment by jenswi-linaro** [comment]
Here are some entry points:
- kernel tee subsystem ioctl, linux/drivers/tee/tee_core.c tee_ioctl()
- kernel OP-TEE SMC driver, linux/drivers/tee/optee/smc_abi.c optee_clnt_ops
- OP-TEE all SMC entries, optee_os/core/arch/arm/kernel/thread_optee_smc_a64.S thread_vector_table
- OP-TEE normal yielding TEE calls, optee_os/core/tee/entry_std.c tee_entry_std()

You should be able to fill in the rest of the details yourself.

**Comment by sabra58** [comment]
Thank you!
