### ISSUE TITLE
problems with set CFG_CORE_DYN_SHM=y

### ISSUE THREAD

**Issue by zhaoshuli1548** [OP-TEE/optee_os#5631]
optee version 3.11
xen version 4.14

optee config: CFG_CORE_DYN_SHM=y CFG_VIRTUALIZATION=y
xen config: CONFIG_TEE=y CONFIG_OPTEE=y CONFIG_EXPERT=y

I use `register_ddr(CFG_TZDRAM_START+CFG_TZDRAM_SIZE,0x00200000) ` to set share memory range。
I meet some problems:

```
root@s32g3ramdisk:~# optee_example_hello_world 
(XEN) do_call_with_arg enter.
(XEN)  do_call_with_arg a0:838860804 a1:8 a2:3637379072 a3:1 a4:0 a5:0
E/TC:6 0 std_smc_entry:206 Bad arg address 0x8d8ce0000
optee_example_hello_world: TEEC_Opensession failed with code 0xffff000e origin 0x2 
```
the 0x8d8ce0000 is out of range!
1.how the xen known share memory's range? 
I think it depends on an API (fast call), or it is forced to write in the device tree。
2.where set 0x8d8ce0000 in the xen?
do not find。。。。

thanks all！

**Comment by jenswi-linaro** [comment]
I guess it's the call of `page_to_maddr()` in `handle_std_call()` you're looking for.

**Comment by zhaoshuli1548** [comment]
> I guess it's the call of `page_to_maddr()` in `handle_std_call()` you're looking for.

thanks, 
yes，I had find it 
`xen_addr = page_to_maddr(call->xen_arg_pg);`

the xen_addr  is 0x8d8ce0000, but my physical addresses is 4G(0xffffffff), it is wrong。
so this problem return to `1.how the xen known share memory's range?`

**Comment by jenswi-linaro** [comment]
I assume there is more than one way for Xen to get this information. Perhaps device tree in this case? Where do you get the physical address 0xffffffff from?

**Comment by zhaoshuli1548** [comment]
> I assume there is more than one way for Xen to get this information. Perhaps device tree in this case? Where do you get the physical address 0xffffffff from?

thanks！
physical address 0xffffffff is here :
![image](https://user-images.githubusercontent.com/104406436/200563667-91e3ead2-b9d0-4f81-be3d-aa29cc505fa5.png)

what does the  device tree means ,kernel dtb or  optee-os 's  CFG_DT ? if CFG_DT ,I have set it n(CFG_DT=n)
if  kernel dtb , I have check it in xen ,i can not find anything about optee's shm memory。

**Comment by jenswi-linaro** [comment]
You're using `CFG_CORE_DYN_SHM=y` as you should with virtualization, that means that any non-secure DRAM can be used as shared memory. The catch is that OP-TEE must know the valid ranges of non-secure DRAM.

If Xen has allocated `0x838860804` for a VM it probably means that that address is valid or you would have seen a crash much earlier. So I suspect that you just need to update the OP-TEE configuration.

**Comment by zhaoshuli1548** [comment]
> You're using `CFG_CORE_DYN_SHM=y` as you should with virtualization, that means that any non-secure DRAM can be used as shared memory. The catch is that OP-TEE must know the valid ranges of non-secure DRAM.
> 
> If Xen has allocated `0x838860804` for a VM it probably means that that address is valid or you would have seen a crash much earlier. So I suspect that you just need to update the OP-TEE configuration.

this MY OPTEE CONFIG:
![image](https://user-images.githubusercontent.com/104406436/200589592-41943ecd-66bb-45db-8b7d-8d6822d232fc.png)
I think xen can also known the dyn share memory physical address(start & size (2m)),but now xen do not run as I think。
I understand that now I am is incorrect
I should split my address（4g） to two part ，one is security addr（20m） ，another is no-secutity addr（Exclusion security addr），and set it to register_addr(). Is that right？

**Comment by jenswi-linaro** [comment]
dyn share memory physical address should be all dram used normal world, including Xen.
What is "other"?

**Comment by zhaoshuli1548** [comment]
> dyn share memory physical address should be all dram used normal world, including Xen. What is "other"?

other is BL31 : ATF (2M) , BL33: U-BOOT(6M)

**Comment by jenswi-linaro** [comment]
So BL31 is supposed to be secure memory too, but the BL33 is non-secure.
So basically everything below 22M is secure, and the rest up to 0xffffffff is non-secure.
You need to configure some memory firewall to make sure that this is enforced too.

However, the fact that Xen seems to allocate and use memory above 0xffffffff suggests something is missing in the picture.

**Comment by zhaoshuli1548** [comment]
> 所以BL31也应该是安全内存，但BL33是不安全的。 所以基本上所有低于 22M 的东西都是安全的，其余的 0xffffffff 是不安全的。 您需要配置一些内存防火墙以确保这也被强制执行。
> 
> 然而，Xen 似乎分配和使用高于 0xffffffff 的内存的事实表明图片中缺少一些东西。

thanks!
