### ISSUE TITLE
QEMUv8: trusted key test fails when CFG_CORE_DYN_SHM=n

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#5632]
```
$ make -j10 check CHECK_TESTS=trusted-keys CFG_CORE_DYN_SHM=n
[...]
Starting QEMU... done, guest is booted.
Running: keyctl tests...
!!! Error
make: *** [Makefile:458: check] Error 1
$ tail -8 ../out/bin/serial0.log
Welcome to Buildroot, type root or test to login
buildroot login: root
# export LD_LIBRARY_PATH=/lib:/lib/arm-linux-gnueabihf
# function fail { echo FAILED ; }
# keyctl add trusted kmk "new 32" @u || fail
[    5.233219] trusted-key-tee optee-ta-f04a0fe7-1f5d-4b9b-abf7-619b85b4ce8c: key shm register failed
add_key: Invalid argument
FAILED
```
The TEE core prints:
```
E/TC:? 0 __tee_entry_std:583 Unknown cmd 0x4
```
...which is `OPTEE_MSG_CMD_REGISTER_SHM`. The Linux driver has correctly detected that OP-TEE doesn't support dynamic shared memory, i.e. the message "optee: dynamic shared memory is enabled" is **NOT** present.

(Note: this is with https://github.com/OP-TEE/build/pull/601 applied, without it the test fails but the failure is not reported)

**Comment by jforissier** [comment]
@b49020 with your patch (and https://github.com/OP-TEE/build/pull/601):
```
# keyctl add trusted kmk "new 32" @u || fail
add_key: No such device
FAILED
```
So yeah that looks good I suppose. We just need to handle this case in the Expect script (skip test when not supported). I'll push another commit to https://github.com/OP-TEE/build/pull/601. Thanks!

**Comment by b49020** [comment]
> So yeah that looks good I suppose.

I suppose this I can take it as your tested-by tag while pushing above patch upstream.

> We just need to handle this case in the Expect script (skip test when not supported). I'll push another commit to https://github.com/OP-TEE/build/pull/601.

Makes sense.

**Comment by jforissier** [comment]
> > So yeah that looks good I suppose.
> 
> I suppose this I can take it as your tested-by tag while pushing above patch upstream.

Absolutely:

```diff
diff --git a/security/keys/trusted-keys/trusted_tee.c b/security/keys/trusted-keys/trusted_tee.c
index 2ce66c199e1d..83b6f3618414 100644
--- a/security/keys/trusted-keys/trusted_tee.c
+++ b/security/keys/trusted-keys/trusted_tee.c
@@ -224,7 +224,8 @@ static int trusted_tee_get_random(unsigned char *key, size_t key_len)
 
 static int optee_ctx_match(struct tee_ioctl_version_data *ver, const void *data)
 {
-       if (ver->impl_id == TEE_IMPL_ID_OPTEE)
+       if (ver->impl_id == TEE_IMPL_ID_OPTEE &&
+           ver->gen_caps & TEE_GEN_CAP_REG_MEM)
                return 1;
        else
                return 0;
```
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by b49020** [comment]
Upstream patch for review: https://lkml.org/lkml/2022/11/10/342

**Comment by b49020** [comment]
> Upstream patch for review: https://lkml.org/lkml/2022/11/10/342

Patch merged in mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1506fba28b53fd159c7028c4809a4a3143a38eb7. I suppose its fine to close this issue now.

**Comment by jforissier** [comment]
@b49020 yes, thanks!
