### ISSUE TITLE
optee benchmark

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#5634]
Is this repository still maintained and functional?
https://github.com/linaro-swg/optee_benchmark

We are noticing a big performance gap between iMX8mm and STM32MP1 using PKCS11 - we suspect the PAGER and the SIMD performance difference on SW crypto operations (aarch64 vs arm) but is there a simple way to confirm where the time is being spent?

thanks

**Comment by jenswi-linaro** [comment]
> Is this repository still maintained and functional?
> https://github.com/linaro-swg/optee_benchmark

It doesn't seem to work in one of my builds, so I'd say that it's not maintained.
If I remember correctly it depends on some special kind of shared memory that might not work. The best would probably be if we could find a way of using normal shared memory instead. With that I believe it would be less of an effort to keep it working.

**Comment by jforissier** [comment]
> We are noticing a big performance gap between iMX8mm and STM32MP1 using PKCS11 - we suspect the PAGER and the SIMD performance difference on SW crypto operations (aarch64 vs arm) but is there a simple way to confirm where the time is being spent?

ftrace may help, in particular `CFG_SYSCALL_FTRACE`, see https://optee.readthedocs.io/en/latest/debug/ftrace.html.
