### ISSUE TITLE
Add RSA AES key wrap mechanism

### ISSUE THREAD

**Issue by varder** [OP-TEE/optee_os#5636]
I would like to implement the following mechanism:
```
6.1.23 RSA AES KEY WRAP
The RSA AES key wrap mechanism, denoted CKM_RSA_AES_KEY_WRAP, is a mechanism based on the RSA public-key cryptosystem and the AES key wrap mechanism. It supports single-part key wrapping; and key unwrapping.
```
https://docs.oasis-open.org/pkcs11/pkcs11-spec/v3.1/cs01/pkcs11-spec-v3.1-cs01.html#_Toc111203390

But the problems are
1. it requires AES KWP mechanism
CKM_AES_KEY_WRAP_KWP
which is not implemented in OP-TEE.

2.  The latest release of Global Platform documentation that I have found does not mention KWP in
https://globalplatform.org/specs-library/tee-internal-core-api-specification/
GPD_TEE_Internal_Core_API_Specification_v1.3.1_PublicRelease_CC.pdf
```
208 / 375 TEE Internal Core API Specification – Public Release v1.3.1
Table 6-6b: Symmetric Encrypt/Decrypt Operation Parameters
```

The questions are:

It looks like mbedtls has implemented the KWP mechnism
https://github.com/Mbed-TLS/mbedtls/blob/0fe6631486db70178b380f8ef6e5d89063ae39a3/library/cipher_wrap.c#L2079
does it make sense to add API despite it is not mentioned in Global Platfrom?

If adding API does not make sense,
Can the mbedtls functions encrypt/decrypt be used in PKCS11 TA?

Are there any other possible solution?

**Comment by jforissier** [comment]
Hello @varder,

Extending the GP API is a bit delicate; it can cause conflicts if GP decides to introduce the algorithm in the future and it might also cause confusion. However it is a good option for better protection of the key material, which in this case would be available only to SEL1 or even only to hardware (depending on hardware/drivers).

I would still suggest to start by using MBedTLS in the PKCS#11 TA, it sounds like the simplest option to introduce the new mechanism. The underlying implementation can always be revisited later.

**Comment by varder** [comment]
Hi,
@jforissier thanks for reply

The KWP key wrapping is done is the following PR using mbedtls 
https://github.com/OP-TEE/optee_os/pull/5647

I would like to add wrapping RSA private key with the RSA AES key wrap mechanism,

According to the specification
https://docs.oasis-open.org/pkcs11/pkcs11-spec/v3.1/cs01/pkcs11-spec-v3.1-cs01.html#_Toc111203390
The private target key will be encoded as defined in section 6.7

https://docs.oasis-open.org/pkcs11/pkcs11-spec/v3.1/cs01/pkcs11-spec-v3.1-cs01.html#_Toc111203467
For wrapping, a private key is BER-encoded according to [PKCS #8] PrivateKeyInfo ASN.1 type.  PKCS #8 requires an algorithm identifier for the type of the private key.  The object identifiers for the required algorithm identifiers...

Should I manually implement RSA private key BER encoding/decoding in the TA?
Are there any functions can be reused in libtomcrypt or mbedtls etc?
Are there any other solution for this?

**Comment by varder** [comment]
Added RSA BER encoding/decoding using mbedtls functions
https://github.com/OP-TEE/optee_os/commit/ad2fe47a86caaffc6d52b7a14a0e4e746e6319c8
