### ISSUE TITLE
Is the shared memory safe when use TEE_InvokeTACommand?

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#5651]
I want to use `TEE_InvokeTACommand` to do some confidential computing work between several TAs.

I want to know if the shared memory used by `TEE_InvokeTACommand` is safe. Or it's as same as the shared memory used by `TEEC_InvokeCommand`?

**Comment by jenswi-linaro** [comment]
`TEE_InvokeTACommand()` uses secure memory as temporary memory when communicating between TAs so it's safe.

**Comment by YogzZ** [comment]
Thank you! @jenswi-linaro
