### ISSUE TITLE
Scheme Discussion for OPTEE

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5654]
Hello, experts,

I have three questions.

If OPTEE OS runs as SP in S-EL1 and Hafnium runs as S-EL2,

1. How does SPs map to the corresponding physical cores?

2. How to switch physical cores between SPs?

3. Can I assign the specified cores to the OPTEE OS to keep it running？If so，how?

Looking forward to your reply. Thank you very much.

**Comment by jenswi-linaro** [comment]
In the current design, there's a one-to-one mapping between physical cores and the virtual that OP-TEE uses. So the principle is more or less the same as without S-EL2. Switching between cores is still the responsibility of the normal world scheduler. With the exception of secure interrupt processing where the time is stolen, but that's also the same as before only more formalized.

> Can I assign the specified cores to the OPTEE OS to keep it running？If so，how?

As long as you don't exit with a CPU it's yours but Hafnium at S-EL2 may complain at some point. It could also upset interrupt handling in normal for this CPU.

Chapter 7 Partition runtime models and Chapter 8 Interrupt management, in the FF-A 1.1 specification (https://developer.arm.com/documentation/den0077/latest) go into detail about how the CPU time is managed.
