### ISSUE TITLE
Compile  error: too many arguments to function 'print_stack_arm32 when the CFG_TEE_CORE_LOG_LEVEL, CFG_TEE_TA_LOG_LEVEL set to 0

### ISSUE THREAD

**Issue by BingHsu** [OP-TEE/optee_os#5655]
Hi All,

I am using version 3.2.0 OP-TEE and trying to set CFG_TEE_CORE_LOG_LEVEL, CFG_TEE_TA_LOG_LEVEL set to 0 to disable the error log from OPTEE OS and TA. The compile error would happen shown the following:
`core/arch/arm/kernel/abort.c: In function '__print_stack_unwind_arm32':
core/arch/arm/kernel/abort.c:149:2: error: too many arguments to function 'print_stack_arm32'
  print_stack_arm32(TRACE_ERROR, &state, exidx, exidx_sz,
  ^~~~~~~~~~~~~~~~~`

The API prototype(print_stack_arm32, print_stack_arm64) defined for case TRACE_LEVEL<=0 does not align with TRACE_LEVEL>0.
I tried to align the API prototype(print_stack_arm32, print_stack_arm64) for case TRACE_LEVEL<=0 to TRACE_LEVEL>0 then the compile error was resolved. I just want to double-check the following modification makes sense and does not impact another function. Please let me know if there is any problem. Thanks.

```
--- a/src/bsp/trustzone/optee/optee_os/mt2xxx/3.2.0/core/arch/arm/include/kernel/unwind.h
+++ b/src/bsp/trustzone/optee/optee_os/mt2xxx/3.2.0/core/arch/arm/include/kernel/unwind.h
@@ -89,16 +89,16 @@ void print_kernel_stack(int level);

 #ifdef ARM64
 static inline void print_stack_arm64(int level __unused,
-                                    struct unwind_state_arm64 *state __unused,
-                                    uaddr_t exidx __unused,
-                                    size_t exidx_sz __unused)
+                                    struct unwind_state_arm64 *state __unused,
+                                        bool kernel_stack __unused, vaddr_t stack __unused, size_t stack_size__unused)
 {
 }
 #endif
 static inline void print_stack_arm32(int level __unused,
                                     struct unwind_state_arm32 *state __unused,
                                     uaddr_t exidx __unused,
-                                    size_t exidx_sz __unused)
+                                    size_t exidx_sz __unused, bool kernel_stack __unused,
+                      vaddr_t stack __unused, size_t stack_size __unused)
 {
 }
```

**Comment by jforissier** [comment]
> I just want to double-check the following modification makes sense and does not impact another function.

That's correct. This bug was fixed 4 years ago in https://github.com/OP-TEE/optee_os/commit/440610460.

**Comment by BingHsu** [comment]
Hi jforissier,

Thanks for the confirmation. 

Bing
