### ISSUE TITLE
Is it safe to configure CFG_DRAM_SIZE larger than real DRAM size on the board?

### ISSUE THREAD

**Issue by tinghan-shen** [OP-TEE/optee_os#5656]
Hi experts,

I'm struggling about how to about configuring CFG_DRAM_SIZE for different boards with the same SoC. The SoC supports up to 8GB address space for DRAM, but the DRAM size on each board is different. The DRAM size may be 4G, 8G, or less. 
Do I need to configure the CFG_DRAM_SIZE to match the real DRAM size on each board? or can I configure the max size, i.e. 8G, for all of them? If I uses the max size, does it have any potential issue or weakness that I have to take care?

**Comment by jenswi-linaro** [comment]
When OP-TEE uses dynamically shared memory the normal world can use any DRAM as shared memory. OP-TEE must be able to tell if a physical address is valid before it can be mapped or we can run into unexpected data aborts. If you pick a too large size normal world can trick OP-TEE into accessing memory that doesn't exist.

**Comment by tinghan-shen** [comment]
> When OP-TEE uses dynamically shared memory the normal world can use any DRAM as shared memory. OP-TEE must be able to tell if a physical address is valid before it can be mapped or we can run into unexpected data aborts. If you pick a too large size normal world can trick OP-TEE into accessing memory that doesn't exist.

thank you very much!
