### ISSUE TITLE
In the case that SEL2(SPMC) is enabled, how to add the sp.pkg(optee-os package) into the fipimage?

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5661]

**Comment by zzbios** [comment]
For my environment, bl2 runs at bl3. And the tb_fw_config is not used, so i cannot find the (spks)node.  (spks)node include the info of each sp.pkg. Now, I wanna to know that how add the sp.pkg to the list of bl2_mem_params_descs?

**Comment by jenswi-linaro** [comment]
I guess you need to use tb_fw_config to know which .pkg's to load.

**Comment by zzbios** [comment]
> I guess you need to use tb_fw_config to know which .pkg's to load.
Hello, glad to see your answers again. When BL2 runs at EL3 and BL1 is not used, TB_FW_CONFIG is not used any more. Can I load the TB_FW_CONFIG by bl2 instead of bl1? 
And where should I put the code for loading TB_FW_CONFIG？
Thank you~

**Comment by zzbios** [comment]
> I guess you need to use tb_fw_config to know which .pkg's to load.

Is there any other methods？Can I insert the sp.pkg into the bl2_mem_params_descs list directly?

**Comment by zzbios** [comment]
> I guess you need to use tb_fw_config to know which .pkg's to load.

**supplement to the above question**

As what I see in the TF-A reference code, 
sp.pkg depends on fconf_populate_arm_sp to append itself into the sp_mem_params_descs list, 
fconf_populate_arm_sp is registered by FCONF_REGISTER_POPULATOR(TB_FW,

When BL2 does not run at EL3, below function will be executed to populate the sp.pkg info.
For my environment, bl2 runs at bl3, the function bl2_el3_plat_arch_setup will be executed instead of bl2_plat_arch_setup, which does not implement the population for the sp.pkg info.

_void bl2_plat_arch_setup(void)
{
	const struct dyn_cfg_dtb_info_t *tb_fw_config_info;

	arm_bl2_plat_arch_setup();

	/* Fill the properties struct with the info from the config dtb */
	fconf_populate("FW_CONFIG", config_base);

	/* TB_FW_CONFIG was also loaded by BL1 */
	tb_fw_config_info = FCONF_GET_PROPERTY(dyn_cfg, dtb, TB_FW_CONFIG_ID);
	assert(tb_fw_config_info != NULL);

	fconf_populate("TB_FW", tb_fw_config_info->config_addr);
}_
