### ISSUE TITLE
Attestation PTA - should it provide a unique id?

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#5662]
Is the attestation PTA supposed to be feeding some Entity Attestation Token generator service as part of the device attestation?

If so, I am wondering if perhaps it shouldn't also provide the unique id (simply derived from the HUK for instance).

**Comment by jforissier** [comment]
I suppose the public key generated on first call can be used as a device identifier. Do you have a specific use case in mind?

**Comment by ldts** [comment]
um, sorry maybe not...there is some form of spec already for the unique id from IETF (I should have checked)... https://www.ietf.org/archive/id/draft-ietf-rats-eat-12.html#name-universal-entity-id-claim-u

**Comment by jforissier** [comment]
Interesting. I agree the attestation PTA seems a good place to implement that.
