### ISSUE TITLE
Need some advice about C++ standard library support

### ISSUE THREAD

**Issue by YogzZ** [OP-TEE/optee_os#5665]
Thanks to #3693, we are comfortable using basic C++ grammar.  Just like #5213, I really want to get further steps on C++ standard library support. 

I have some questions:
1. Port the whole `newlib` to `OP-TEE` or link a new `libc` static library to TA instead of `libutils`, which is better?
2. Which `libc` or `libc++` library is more suitable for OP-TEE TA?

**Comment by jenswi-linaro** [comment]
`libutils` is our `libc` even if it's spelled and pronounced funny. So whatever `libc` stuff we need should go into `libutils`. The word is **need**, unused stuff doesn't need to be added.

Regarding C++ stuff I think the approach should be the same here, add what's needed. I have no idea of which library to try to port.

**Comment by YogzZ** [comment]
Thank you for the answer!

I want to get more C++ libraries and `libc` to support some 3rd parties without changing `OP-TEE OS`.

I have tried to add stuff one by one, but some depend on deep libraries. So I think it might be more efficient to handle and link the overall `libc` and `libstdc++`.

I know I can get more C++ support by [openenclave](https://github.com/openenclave/openenclave), but it's too complex and still has some little bugs...

So I intended to develop a TA SDK just like [teaclave](https://github.com/apache/incubator-teaclave-trustzone-sdk) and start with this question...

May I get more specific suggestions?

**Comment by jenswi-linaro** [comment]
It looks like you've made changes to a .h file and missed an `#ifndef __ASSEMBLER__`.
By the way, why are you doing this with ancient stuff?

**Comment by YogzZ** [comment]
> It looks like you've made changes to a .h file 

I put all the `newlib-cygwin/newlib/libc` header files into the `OP-TEE OS` without changing anything.

> and missed an `#ifndef __ASSEMBLER__`.

Thank you! I find some examples in `libutils/ext/include/util.h` and `libutils/isoc/include/stdint.h`，I will check how to use `#ifndef __ASSEMBLER__`.

> By the way, why are you doing this with ancient stuff?

I cloned the 3.12 before, and added some syscall and SMC requests to operate the disk (I know they didn't comply with the `TEE Internal Core API Specification`) for porting [sqlcipher](https://github.com/sqlcipher/sqlcipher) in TA. It works well, so I didn't update the project...
