### ISSUE TITLE
When hafnium run into optee, stage-2 page fault occurs(show in the comment). What does it mean? How to solve?

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5675]

**Comment by zzbios** [comment]
platform configuration：
```
aarch64_toolchains("secure_aem_v8a_fvp") {
  cpu = "cortex-a57"
  origin_address = "0xff200000"
  boot_flow = "//src/boot_flow:spmc"
  console = "//src/arch/aarch64/pl011"
  iommu = "//src/iommu:absent"
  gic_version = 4
  gicd_base_address = "0x2e000000"
  gicr_base_address = "0x2e140000"
  gicr_frames = 8
  heap_pages = 180
  max_cpus = 8
  max_vms = 16
  # branch_protection = "standard"
  toolchain_args = {
    plat_ffa = "//src/arch/aarch64/plat/ffa:spmc"
    plat_psci = "//src/arch/aarch64/plat/psci:spmc"
    plat_interrupts = "//src/arch/aarch64/plat/interrupts:gicv3"
    plat_prng = "//src/arch/aarch64/plat/prng:prng"
    secure_world = "1"
    pl011_base_address = "0x2A400000"
    smmu_base_address = "0x3F000000"
    smmu_memory_size = "0x400000"
    # enable_mte = "1"
    plat_log_level = "LOG_LEVEL_VERBOSE"
  }
}
```

debug log：
one_time_init:169
INFO: Loading VM id 0x8001: op-tee.
VERBOSE: VM has 0 physical interrupts defined in manifest.
INFO: Loaded with 8 vCPUs, entry at 0xff400000.
vcpu_secondary_reset_and_start:113
one_time_init:177
one_time_init:183
one_time_init:187
one_time_init:190
one_time_init:194
one_time_init:198
one_time_init:202
INFO: Hafnium initialisation completed
cpu_main:26
VERBOSE: plat_psci_cpu_resume: cpu mpidr 0x0 ON
arch_cpu_init:260
arch_cpu_init:262
arch_cpu_init:265
arch_cpu_init:269
arch_cpu_sve_configure_sve_vector_length:235
arch_cpu_sve_configure_sve_vector_length:238
arch_cpu_sve_configure_sve_vector_length:241
arch_cpu_sve_configure_sve_vector_length:247
arch_cpu_sve_configure_sve_vector_length:249
arch_cpu_init:273
arch_cpu_init:275
cpu_main:39
vcpu_set_phys_core_idx:209
cpu_main:42
cpu_main:45
mpidr=0x0
WARNING: Stage-2 page fault: pc=0xff42c500, vmid=0x8001, vcpu=0, vaddr=0xff2b6a10, ipaddr=0xff2b6a10, mode=0x2 0x3078300000007c
NOTICE: Injecting Data Abort exception into VM 0x8001.


```
void __nostackcheck thread_init_thread_core_local(void)
{
	size_t n = 0;
	struct thread_core_local *tcl = thread_core_local;

	for (n = 0; n < CFG_TEE_CORE_NB_CORE; n++) {
		tcl[n].curr_thread = THREAD_ID_INVALID;
		tcl[n].flags = THREAD_CLF_TMP;
	}
	tcl[0].tmp_stack_va_end = GET_STACK_BOTTOM(stack_tmp, 0);
}

```

**Comment by jenswi-linaro** [comment]
I'm sorry, was this a question?

**Comment by zzbios** [comment]
> I'm sorry, was this a question?

expert, I update the title(the previous title has some edit errors, sorry)

**Comment by jenswi-linaro** [comment]
It looks like OP-TEE is mapping (and accessing) memory that doesn't exist in the stage-2 mapping. It could be due to not having enough memory defined in the manifest or perhaps an error in OP-TEE.

**Comment by zzbios** [comment]
> It looks like OP-TEE is mapping (and accessing) memory that doesn't exist in the stage-2 mapping. It could be due to not having enough memory defined in the manifest or perhaps an error in OP-TEE.

The configuration for the spmc_optee_sp_manifest.dts is as follow:
```
/dts-v1/;

#define	AFF	00

#include "m1-defs.dtsi"
#undef POST
#define	POST \
	};

/ {
	compatible = "arm,ffa-core-manifest-1.0";
	#address-cells = <2>;
	#size-cells = <1>;

	attribute {
		spmc_id = <0x8000>;
		maj_ver = <0x1>;
		min_ver = <0x0>;
		exec_state = <0x0>;
		load_address = <0x0 0xFF200000>;
		entrypoint = <0x0 0xFF200000>;
		binary_size = <0x80000>;
	};

	hypervisor {
		compatible = "hafnium,hafnium";
		vm1 {
			is_ffa_partition;
			debug_name = "op-tee";
			load_address = <0xFF400000>;
			smc_whitelist = <0xFFE00000>;
			smc_whitelist_permissive;
			vcpu_count = <8>;
			mem_size = <1048576>;
		};
	};

	cpus {
		#address-cells = <0x2>;
		#size-cells = <0x0>;

		CPU_0

		/*
		 * SPMC (Hafnium) requires secondary core nodes are declared
		 * in descending order.
		 */
		CPU_7
		CPU_6
		CPU_5
		CPU_4
		CPU_3
		CPU_2
		CPU_1
	};

	memory@0xFF200000 {
		device_type = "memory";
		reg = <0x0 0xFF200000 0x00A00000>; /* Trusted DRAM */
	};

#if MEASURED_BOOT
#include "event_log.dtsi"
#endif
};

```

As shown in fault, ipaddr is in the configured address space in the memory attribute node. Why does stage-2 mapping not exist？
In addition, is a 10M space（Trusted DRAM）not enough to run hafnium and optee (I put the hafnium image after 0xff20_0000 and the optee package after 0xff40_0000)？

**Comment by jenswi-linaro** [comment]
Yet you've set entry point address to `0xFF200000`. I think you need to do a bit of debugging.
A good start could be to start with a configuration known to work and only start to modify it later.
