### ISSUE TITLE
Hafnium runs on s-el2 and optee runs on s-el1. What are the things that optee needs to configure to support hanfium？

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5679]

**Comment by jenswi-linaro** [comment]
Hi, apparently you're trying to run OP-TEE with Hafnium. I believe this mail thread can be of interest to you. https://lists.trustedfirmware.org/archives/list/hafnium@lists.trustedfirmware.org/thread/OK2G4VJDXW552XFXMWLY2H44KPAEZVBC/

This is still experimental and not even upstream yet. If you'd like to try this out please be prepared to get your hands dirty.

PS.
Please avoid asking a lot of questions about more or less the same thing in every possible forum.
