### ISSUE TITLE
why should thread_user_kdata_page be mapped PRW?

### ISSUE THREAD

**Issue by shp4rk** [OP-TEE/optee_os#5691]
afaik thread_user_kdata_page is only read during restoring mapping, to get the thread_user_kcode_offset, and it is never written. I am wondering if I am missing something and there are some reasons why thread_user_kdata_page is mapped PRW

**Comment by jenswi-linaro** [comment]
It is written to while initializing at least. I guess it should be possible to have it mapped read-only after that.

**Comment by shp4rk** [comment]
Thank you for the response!

I thought it was being initialized with the full mapping iiuc. If you have any scenario that thread_user_kdata_page is written after initialization, please share!

I would really appreciate your help 😄

**Comment by jenswi-linaro** [comment]
I can't recall why it's mapped with `TEE_MATTR_PRW` in `map_kinit()`. You could try to if it works with read-only instead.

**Comment by shp4rk** [comment]
Okay thank you for your answer!
