### ISSUE TITLE
symbolize.py can not dump ta crash log

### ISSUE THREAD

**Issue by coversky2018** [OP-TEE/optee_os#5694]
i have a question and i can not find solution

i got a ta crash 
E/TC:? 00 User TA data-abort at address 0x0 (translation fault)
E/TC:? 00  fsr 0x00000805  ttbr0 0x053d806a  ttbr1 0x053a806a  cidr 0x6
E/TC:? 00  cpu #2          cpsr 0x60000030
E/TC:? 00  r0 0x00002551      r4 0x0012de5c    r8 0x0012de6c   r12 0x00110f3c
E/TC:? 00  r1 0x00110f2c      r5 0x00110f2c    r9 0x0012ddd0    sp 0x00110f20
E/TC:? 00  r2 0x00002551      r6 0x00110f80   r10 0x00136e00    lr 0x00125c1d
E/TC:? 00  r3 0x00000000      r7 0x0012de4c   r11 0x00000002    pc 0x0011d6ce -0x0011c000=16ce
E/LD:   Status of TA e92a43ab-b4c8-4450-aa12-b1516259613b
E/LD:    arch: arm
E/LD:   region  0: va 0x00103000 pa 0x055a6000 size 0x002000 flags rw-s (ldelf)
E/LD:   region  1: va 0x00105000 pa 0x055a8000 size 0x006000 flags r-xs (ldelf)
E/LD:   region  2: va 0x0010b000 pa 0x055ae000 size 0x001000 flags rw-s (ldelf)
E/LD:   region  3: va 0x0010c000 pa 0x055af000 size 0x003000 flags rw-s (ldelf)
E/LD:   region  4: va 0x0010f000 pa 0x055b2000 size 0x001000 flags r--s
E/LD:   region  5: va 0x00110000 pa 0x05605000 size 0x001000 flags rw-s (stack)
E/LD:   region  6: va 0x0011c000 pa 0x00001000 size 0x011000 flags r-xs [0]
E/LD:   region  7: va 0x0012d000 pa 0x00012000 size 0x00a000 flags rw-s [0]
E/LD:    [0] e92a43ab-b4c8-4450-aa12-b1516259613b @ 0x0011c000
E/LD:   Call stack:
E/LD:    0x0011d6ce
E/LD:    0x00125c1d
E/LD:    0x00129bd7
E/LD:    0x0011e8a4

i use this command : 
**./scripts/symbolize.py  -d /mnt/fileroot/hongbin.wang/workspace/temp/provision_code/provision/out/ta/**

then i  input this crash log  . but got err happens.
err like this.
E/TC:? 00 User TA data-abort at address 0x0 (translation fault)
E/TC:? 00  fsr 0x00000805  ttbr0 0x053d806a  ttbr1 0x053a806a  cidr 0x6
E/TC:? 00  cpu #2          cpsr 0x60000030
E/TC:? 00  r0 0x00002551      r4 0x0012de5c    r8 0x0012de6c   r12 0x00110f3c
E/TC:? 00  r1 0x00110f2c      r5 0x00110f2c    r9 0x0012ddd0    sp 0x00110f20
E/TC:? 00  r2 0x00002551      r6 0x00110f80   r10 0x00136e00    lr 0x00125c1d
E/TC:? 00  r3 0x00000000      r7 0x0012de4c   r11 0x00000002    pc 0x0011d6ce -0x0011c000=16ce
E/LD:   Status of TA e92a43ab-b4c8-4450-aa12-b1516259613b
E/LD:    arch: arm
E/LD:   region  0: va 0x00103000 pa 0x055a6000 size 0x002000 flags rw-s (ldelf)
E/LD:   region  1: va 0x00105000 pa 0x055a8000 size 0x006000 flags r-xs (ldelf)
E/LD:   region  2: va 0x0010b000 pa 0x055ae000 size 0x001000 flags rw-s (ldelf)
E/LD:   region  3: va 0x0010c000 pa 0x055af000 size 0x003000 flags rw-s (ldelf)
E/LD:   region  4: va 0x0010f000 pa 0x055b2000 size 0x001000 flags r--s
E/LD:   region  5: va 0x00110000 pa 0x05605000 size 0x001000 flags rw-s (stack)
Traceback (most recent call last):
  _**File "./scripts/symbolize.py", line 514, in <module>
    main()
  File "./scripts/symbolize.py", line 506, in main
    symbolizer.write(line)
  File "./scripts/symbolize.py", line 453, in write
    elf_idx) +
  File "./scripts/symbolize.py", line 353, in sections_in_region
    self.read_sections(elf)
  File "./scripts/symbolize.py", line 322, in read_sections
    objdump = self.my_Popen([cmd, '--section-headers', elf])
  File "./scripts/symbolize.py", line 110, in my_Popen
    bufsize=1)**_
TypeError: __init__() got an unexpected keyword argument 'text'
hongbin.wang@droid08-bj:/mnt/fileroot/hongbin.wang/workspace/optee/optee_os$ E/LD:    0x0011d6ce
-bash: E/LD:: No such file or directory
hongbin.wang@droid08-bj:/mnt/fileroot/hongbin.wang/workspace/optee/optee_os$ E/LD:    0x00125c1d
-bash: E/LD:: No such file or directory
hongbin.wang@droid08-bj:/mnt/fileroot/hongbin.wang/workspace/optee/optee_os$ E/LD:    0x00129bd7
-bash: E/LD:: No such file or directory
hongbin.wang@droid08-bj:/mnt/fileroot/hongbin.wang/workspace/optee/optee_os$ E/LD:    0x0011e8a4

can anybody help analysis why this err happend ?

thanks

**Comment by jenswi-linaro** [comment]
`symbolize.py` can't find the needed cross toolchain binutils, readelf and friends, as it expects.

I agree that the error message is a bit cryptic, I would have preferred a good error message and that the input was either consumed before exiting.

**Comment by coversky2018** [comment]
![image](https://user-images.githubusercontent.com/39891057/206400244-04ffe9f0-df71-4eb2-a93e-4c7845e15d4b.png)
i have already use **export PATH=/opt/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/:$PATH  .** 
but still got err.
![image](https://user-images.githubusercontent.com/39891057/206400520-6a911ab4-ccbe-4032-ac7f-d912a0f246c3.png)

**Comment by coversky2018** [comment]
this issue is not complete resolve.
