### ISSUE TITLE
OPTEE Live-update

### ISSUE THREAD

**Issue by i-nevo** [OP-TEE/optee_os#5699]
Hi,
We want to make OPTEE Live-updateable, i.e. replacing the OPTEE image running on a system without rebooting it, in order to have security updates, bug fixes & new features without interrupting the functionality of our system too much. We see two options for this Live-update:
1. Storing all OPTEE runtime data in a secure place (exporting), overwriting the OPTEE binary with a new image and restoring the runtime data so the new image keeps all former states: TAs remain in their inner states, restoring TAs context, all memory allocations & mappings (Both Kernel & user spaces), all encryption/decryption keys, etc.
2. Loading & running a new OPTEE and loading all TAs, running everything afresh.
Although the second option seems much simpler it requires having all active TAs queried for their current state & runtime data and restoring their state after OPTEE is updated.
My questions:
1. Is there any support for OPTEE live-update, e.g. runtime data export/import, or at least a list of all runtime data needed to be saved & restored?
2. Is there an easy way to ask the OPTEE driver running in Linux kernel to repeat the probing process (after replacing the OPTEE) and get updated with the new OPTEE data?

Thanks in advance for any info, tip, idea or better solution for live-updating OPTEE.

**Comment by jenswi-linaro** [comment]
Option 2 means that the normal world applications will need to restart their sessions with secure world too. If that's acceptable then that should indeed be a much easier path.

3: No, but the state that needs to be exported shouldn't be too hard to get hold of.

4: You can bind/unbind the driver in the kernel using:
```
echo -n "firmware:optee" > /sys/bus/platform/drivers/optee/unbind
echo -n "firmware:optee" > /sys/bus/platform/drivers/optee/bind
```
or in the FF-A case:
```
echo -n "arm-ffa-8001" > /sys/bus/arm_ffa/drivers/optee/unbind
echo -n "arm-ffa-8001" > /sys/bus/arm_ffa/drivers/optee/bind
```

**Comment by i-nevo** [comment]
Thank you very much for your reply.
I had some difficulties with unbinding & binding the optee driver, there are no `bind` & `unbind` items in the optee driver "folder", but using `rmmod` & `insmod` worked.
I killed the client daemon, unbound the driver, replaced the optee image with a new one, called its init entry point, bound back the driver and restarted the daemon. The only problem I have now, is that trying to run a TA (e.g. hello-world) I get `TEE_ERROR_CORRUPT_OBJECT` in response. Do you have any idea why it happens and how to avoid it?

Thanks in advance.

**Comment by jenswi-linaro** [comment]
Perhaps something is wrong in secure storage. If you reboot does the problem go away? I suppose you need to add a few debug prints to try to narrow it down.
