### ISSUE TITLE
Secure Storage and tee_otp_get_hw_unique_key () and tee_otp_get_die_id ()

### ISSUE THREAD

**Issue by ffreimann-mtk** [OP-TEE/optee_os#5706]
Hi there OPTEE

I have some questions with respect to OPTEE Secure Storage which I could not resolve so far. The OPTEE document (https://optee.readthedocs.io/en/latest/architecture/secure_storage.html, section 'Important caveats') states 'To allow Secure Storage to operate securely on your platform, you must define implementations in your platform code for tee_otp_get_hw_unique_key () and tee_otp_get_die_id ()'. Is there a reason that both functions MUST be implemented?

1. If one could guarantee that each device contains / creates a unique key, which is returned with 'tee_otp_get_hw_unique_key ()',  why is it necessary to also support 'tee_otp_get_die_id ()'?
2. I see that OPTEE provides compile macros (e.g. 'CFG_CORE_HUK_SUBKEY_COMPAT' and 'CFG_CORE_HUK_SUBKEY_COMPAT_USE_OTP_DIE_ID') which allow for building OPTEE without 'tee_otp_get_die_id ()'. But that seems to be contractionary to the documentation which states that this function MUST be provided. So, is 'tee_otp_get_die_id ()' really required or is it optional?
3. Assuming 'tee_otp_get_die_id ()' is indeed required what should it return? Based on the function name I assume some chip identification or maybe a serial number which is again unique for each chip / device?

**Comment by jenswi-linaro** [comment]
Perhaps some clarification is in order for the documentation. It's OK to use the default `tee_otp_get_die_id()` implementation if you have a proper `tee_otp_get_hw_unique_key()`.
