### ISSUE TITLE
Mapping user VA space and understanding the use of CORE_MMU_PGDIR_LEVEL and CORE_MMU_PGDIR_SIZE

### ISSUE THREAD

**Issue by maroueneboubakri** [OP-TEE/optee_os#5725]
Hi @jenswi-linaro, @jforissier,

I was looking at `vm.c` and `pgt_cache.c` I'm a bit confused about the usage of `CORE_MMU_PGDIR_LEVEL` and `CORE_MMU_PGDIR_SIZE`.
My use case is simple, I want to decide at which level I want to map the user-space. I want to map it using 2M pages. I'm not sure if this could be done easily ? as there is strong bound between `CORE_MMU_PGDIR_LEVEL` ,`CORE_MMU_PGDIR_SIZE` and memory regions. 

These do not have sens in RISC-V as there is no PGDIRs. Not sure if this could replaced with more generic definitions likes mega pages, giga pages in addition to small pages ? When working with memory regions and page tables ? 
I noticed that despite changing value of CORE_MMU_PGDIR_LEVEL, setting VA base to 2M aligned address in `core_mmu_get_user_va_range()`:
`ldelf_loader.c` uses number of pages of `SMALL_PAGE_SIZE `?
`mobj_get_pa()` returns always 4K aligned PAs ? 
`select_va_in_range()` returns 4K aligned adresses or padded with 4K pages.

Short question is, what is the appropriate way to map user VA space using giga pages or mega pages. In ARM is it enough to replace `L1_XLAT_ADDRESS_SHIFT` with `L0_XLAT_ADDRESS_SHIFT ` for example ? 

Appreciate your help.
Maro

**Comment by maroueneboubakri** [comment]
Also here, what `(pgdir)` means ?

```
D/TC:?   add_phys_mem:635 MU_BASE type IO_NSEC 0x88000000 size 0x00008000
D/TC:?   add_phys_mem:635 ROUNDDOWN(0x0c000000, CORE_MMU_PGDIR_SIZE) type IO_SEC 0x0c000000 size 0x00200000
D/TC:?   add_phys_mem:635 ROUNDDOWN(0x10000000, CORE_MMU_PGDIR_SIZE) type IO_NSEC 0x10000000 size 0x00200000
D/TC:?   add_phys_mem:635 TEE_SHMEM_START type NSEC_SHM 0x88f00000 size 0x00200000
D/TC:?   add_phys_mem:635 TA_RAM_START type TA_RAM 0x80500000 size 0x00b00000
D/TC:?   add_phys_mem:635 VCORE_UNPG_RW_PA type TEE_RAM_RW 0x8014d000 size 0x003b3000
D/TC:?   add_phys_mem:635 VCORE_UNPG_RX_PA type TEE_RAM_RX 0x80100000 size 0x0004d000
D/TC:?   add_va_space:675 type RES_VASPACE size 0x00a00000
D/TC:?   add_va_space:675 type SHM_VASPACE size 0x02000000
D/TC:?   dump_mmap_table:800 type TEE_RAM_RX   va 0x80100000..0x8014cfff pa 0x80100000..0x8014cfff size 0x0004d000 (smallpg)
D/TC:?   dump_mmap_table:800 type TEE_RAM_RW   va 0x8014d000..0x804fffff pa 0x8014d000..0x804fffff size 0x003b3000 (smallpg)
D/TC:?   dump_mmap_table:800 type TA_RAM       va 0x80500000..0x80ffffff pa 0x80500000..0x80ffffff size 0x00b00000 (smallpg)
D/TC:?   dump_mmap_table:800 type IO_NSEC      va 0x81000000..0x81007fff pa 0x88000000..0x88007fff size 0x00008000 (smallpg)
D/TC:?   dump_mmap_table:800 type NSEC_SHM     va 0x81008000..0x81207fff pa 0x88f00000..0x890fffff size 0x00200000 (smallpg)
D/TC:?   dump_mmap_table:800 type SHM_VASPACE  va 0x81400000..0x833fffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:?   dump_mmap_table:800 type RES_VASPACE  va 0x83400000..0x83dfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:?   dump_mmap_table:800 type IO_SEC       va 0x83e00000..0x83ffffff pa 0x0c000000..0x0c1fffff size 0x00200000 (pgdir)
D/TC:?   dump_mmap_table:800 type IO_NSEC      va 0x84000000..0x841fffff pa 0x10000000..0x101fffff size 0x00200000 (pgdir)
```

**Comment by jenswi-linaro** [comment]
PGDIR is a pure software definition in OP-TEE, it is defined as the level of translation tables used to map small pages, 4k on Arm.

I suppose it's possible to change to map TAs using another granularity, but since we haven't had the need for it we've never bothered with it. It sounds like a strange optimization to start with at this stage since I expect that the most common use case is to map TAs using small pages since you want different attributes for code pages and data pages.

> Short question is, what is the appropriate way to map user VA space using giga pages or mega pages. In ARM is it enough to replace L1_XLAT_ADDRESS_SHIFT with L0_XLAT_ADDRESS_SHIFT  for example ?

I doubt it's that simple, there's bound to be loads of corner cases.

However, if you feel like adding support for 2M pages or such I'll help to review, but you may need to do some debugging on QEMU Arm too if something breaks.

**Comment by maroueneboubakri** [comment]
The motivation behind the need to to map to 2M pages is in other sens, maps the TAs to second page table level. `base_table[user_va_idx]` points to TA tables, this is ugly but easier. The way how user va is mapped differs from core ?

Seems that we are 'manually' creating the mapping across page table levels ?

https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/core_mmu_lpae.c#L742
https://github.com/OP-TEE/optee_os/blob/master/core/mm/vm.c#L209
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/core_mmu_lpae.c#L972
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/core_mmu_lpae.c#L758
https://github.com/OP-TEE/optee_os/blob/master/core/mm/core_mmu.c#L1908

On RISC-V based on the MMU mode we may have different page table levels. 

for Sv32 LEVELS=2
for Sv39 LEVELS=3
for Sv48 LEVELS=4
for Sv57 LEVELS=5

And would be great to have a generic way of mapping user-space like the kernel-space using find_table ?
 
Regards
Maro

**Comment by jenswi-linaro** [comment]
That situation isn't unique for riscv either. But I don't find it particularly limiting. We still need to reserve a virtual address range for TAs. I'd recommend just trying to get the riscv port to fit in with what we currently have. Once we have something that works upstream we can try to improve the situation if needed.

> And would be great to have a generic way of mapping user-space like the kernel-space using find_table ?

I'm not sure I follow. User space is mapped using the vm_*() functions.

**Comment by maroueneboubakri** [comment]
> PGDIR is a pure software definition in OP-TEE, it is defined as the level of translation tables used to map small pages, 4k on Arm.

So `CORE_MMU_PGDIR_SIZE ` is intended to be 4k ? what is its relationship to `SMALL_PAGE` ? In vm.c, pgt_cache.c, core_mmu.c is it used to define another granularity in addition to `SMALL_PAGE` ?

**Comment by jenswi-linaro** [comment]
> > PGDIR is a pure software definition in OP-TEE, it is defined as the level of translation tables used to map small pages, 4k on Arm.
> 
> So `CORE_MMU_PGDIR_SIZE ` is intended to be 4k ? what is its relationship to `SMALL_PAGE` ? In vm.c, pgt_cache.c, core_mmu.c is it used to define another granularity in addition to `SMALL_PAGE` ?

No `CORE_MMU_PGDIR_SIZE` is typically 1 or 2 megs depending on the format of the translation tables. A PGDIR translation table is used to map 4k pages.

A PGDIR would be a level 3 table in the example at https://optee.readthedocs.io/en/3.18.0/architecture/core.html#long-descriptor-translation-table-format.

**Comment by maroueneboubakri** [comment]
> > And would be great to have a generic way of mapping user-space like the kernel-space using find_table ?
> 
> I'm not sure I follow. User space is mapped using the vm_*() functions.

I mean the flow behind, my understating is, for core va space, given a region VA and size we attempt to find a table which can hold/map this region  `core_mmu_find_table()`  if not we go to the next page table level using `core_mmu_entry_to_finer_grained()` when the appropriate table is found we set the appropriate entry in it using `core_mmu_set_entry()` and we are done, this is seems generic.

However, for the user va space is more complicated, what complicates it is the 'hard-coding' of page table levels using `magics`.
Starting from[ `set_um_region()` in vm.c `core_mmu_set_info_table(&ti, CORE_MMU_PGDIR_LEVEL, 0, NULL);`](https://github.com/OP-TEE/optee_os/blob/master/core/mm/vm.c#L209) I understood that A PGDIR translation table is used to map 4k pages, but this seems to be strongly bound to ARM architecture where the number of translation levels is already fixed/known. While for RISC-V, we may have 2 to 4 levels.

Also trying to get rid of https://github.com/OP-TEE/optee_os/blob/master/core/mm/core_mmu.c#L1908 also because of the PGDIR notion.

**Comment by jenswi-linaro** [comment]
> > > And would be great to have a generic way of mapping user-space like the kernel-space using find_table ?
> > 
> > 
> > I'm not sure I follow. User space is mapped using the vm_*() functions.
> 
> I mean the flow behind, my understating is, for core va space, given a region VA and size we attempt to find a table which can hold/map this region `core_mmu_find_table()` if not we go to the next page table level using `core_mmu_entry_to_finer_grained()` when the appropriate table is found we set the appropriate entry in it using `core_mmu_set_entry()` and we are done, this is seems generic.

We use that for semi-static global mappings. It's usable to map TAs at this stage. For one thing, it's not very good at reusing translation tables.


> 
> However, for the user va space is more complicated, what complicates it is the 'hard-coding' of page table levels using `magics`.

It's only magic in the sense that we know it at compile time. I suppose it could be made more dynamic to be calculated while initializing instead if needed.

> Starting from[ `set_um_region()` in vm.c `core_mmu_set_info_table(&ti, CORE_MMU_PGDIR_LEVEL, 0, NULL);`](https://github.com/OP-TEE/optee_os/blob/master/core/mm/vm.c#L209) I understood that A PGDIR translation table is used to map 4k pages, but this seems to be strongly bound to ARM architecture where the number of translation levels is already fixed/known. While for RISC-V, we may have 2 to 4 levels.

That's not so different from Arm, I believe Arm has 2 to 5 levels. The point is that this is something you can know build time, you typically select the minimal number of levels that makes sense for your platform. Not doing this at runtime simplifies things a bit. It scales well enough for now. It may help to remember that OP-TEE comes from an originally very memory constrained environment. TAs aren't expected to be very large. The common case is less than 2 megs, but we can deal with a few times larger than that.

> 
> Also trying to get rid of https://github.com/OP-TEE/optee_os/blob/master/core/mm/core_mmu.c#L1908 also because of the PGDIR notion.

The problem I'm seeing is that going to a more fine grained or deeper level on arm means increasing the level, while it's the other way around on riscv as described in the hardware architecture. However, the translation table level we're working with here is a pure software construct and doesn't have to match the hardware except that it's a bit inconvenient when it doesn't match.

How about making the translation table level a signed integer instead? Arch/arm continues to use it unchanged while arch/riscv uses negative values in the generic API:
- core_mmu_set_info_table()
- core_mmu_set_entry_primitive()
- core_mmu_get_entry_primitive()
- the level field in struct core_mmu_table_info

the internal code in `core/arch/riscv/mm/core_mmu_arch.c` flips the sign to get the native level. It should be easy enough to assert() that the level has the expected sign at strategic places.

Once there's a working riscv port upstream we can target areas to be improved since it's more visible to everyone involved.

**Comment by maroueneboubakri** [comment]
Re-poen for further discussion.

**Comment by gagachang** [comment]
Dear @maroueneboubakri ,

To align with current OP-TEE implementation,
I think the translation levels defined by **increasing style** is also feasible for RISC-V. Start from level 1:
```
Sv32: 1, 2
Sv39: 1, 2, 3
Sv48: 1, 2, 3, 4
Sv57: 1, 2, 3, 4, 5
```

Let `CORE_MMU_PGDIR_LEVEL` be maximum translation level (e.g., 3 for Sv39 and 4 for Sv48), and `CORE_MMU_PGDIR_SHIFT` is the shifted bits of `CORE_MMU_PGDIR_LEVEL - 1`.
Both of them are compiled time definitions, since we might not change the address translation mode at runtime.


```
#define CORE_MMU_SHIFT_OF_LEVEL(level) (RISCV_PGLEVEL_BITS * \
					((RISCV_PGLEVELS) - level) + \
					RISCV_PGSHIFT)

#if RISCV_MMU_MODE == 57	/*Sv57*/
#define CORE_MMU_PGDIR_LEVEL	U(5)
#elif RISCV_MMU_MODE == 48	/*Sv48*/
#define CORE_MMU_PGDIR_LEVEL	U(4)
#elif RISCV_MMU_MODE == 39	/*Sv39*/
#define CORE_MMU_PGDIR_LEVEL	U(3)
#elif RISCV_MMU_MODE == 32	/*Sv32*/
#define CORE_MMU_PGDIR_LEVEL	U(2)
#else
#error unknown or unsupported mmu mode
#endif

#define CORE_MMU_PGDIR_SHIFT \
	CORE_MMU_SHIFT_OF_LEVEL((CORE_MMU_PGDIR_LEVEL - 1))

#define CORE_MMU_BASE_TABLE_LEVEL U(1)
#define CORE_MMU_BASE_TABLE_SHIFT \
	CORE_MMU_SHIFT_OF_LEVEL(CORE_MMU_BASE_TABLE_LEVEL)
```

**Comment by jenswi-linaro** [comment]
Sounds good to me.

**Comment by maroueneboubakri** [comment]
> Dear @maroueneboubakri ,
> 
> To align with current OP-TEE implementation, I think the translation levels defined by **increasing style** is also feasible for RISC-V. Start from level 1:
> 
> ```
> Sv32: 1, 2
> Sv39: 1, 2, 3
> Sv48: 1, 2, 3, 4
> Sv57: 1, 2, 3, 4, 5
> ```
> 
> Let `CORE_MMU_PGDIR_LEVEL` be maximum translation level (e.g., 3 for Sv39 and 4 for Sv48), and `CORE_MMU_PGDIR_SHIFT` is the shifted bits of `CORE_MMU_PGDIR_LEVEL - 1`. Both of them are compiled time definitions, since we might not change the address translation mode at runtime.
> 
> ```
> #define CORE_MMU_SHIFT_OF_LEVEL(level) (RISCV_PGLEVEL_BITS * \
> 					((RISCV_PGLEVELS) - level) + \
> 					RISCV_PGSHIFT)
> 
> #if RISCV_MMU_MODE == 57	/*Sv57*/
> #define CORE_MMU_PGDIR_LEVEL	U(5)
> #elif RISCV_MMU_MODE == 48	/*Sv48*/
> #define CORE_MMU_PGDIR_LEVEL	U(4)
> #elif RISCV_MMU_MODE == 39	/*Sv39*/
> #define CORE_MMU_PGDIR_LEVEL	U(3)
> #elif RISCV_MMU_MODE == 32	/*Sv32*/
> #define CORE_MMU_PGDIR_LEVEL	U(2)
> #else
> #error unknown or unsupported mmu mode
> #endif
> 
> #define CORE_MMU_PGDIR_SHIFT \
> 	CORE_MMU_SHIFT_OF_LEVEL((CORE_MMU_PGDIR_LEVEL - 1))
> 
> #define CORE_MMU_BASE_TABLE_LEVEL U(1)
> #define CORE_MMU_BASE_TABLE_SHIFT \
> 	CORE_MMU_SHIFT_OF_LEVEL(CORE_MMU_BASE_TABLE_LEVEL)
> ```

@gagachang thanks for suggestion, I'll try that and let you know.

**Comment by maroueneboubakri** [comment]
> Dear @maroueneboubakri ,
> 
> To align with current OP-TEE implementation, I think the translation levels defined by **increasing style** is also feasible for RISC-V. Start from level 1:
> 
> ```
> Sv32: 1, 2
> Sv39: 1, 2, 3
> Sv48: 1, 2, 3, 4
> Sv57: 1, 2, 3, 4, 5
> ```
> 
> Let `CORE_MMU_PGDIR_LEVEL` be maximum translation level (e.g., 3 for Sv39 and 4 for Sv48), and `CORE_MMU_PGDIR_SHIFT` is the shifted bits of `CORE_MMU_PGDIR_LEVEL - 1`. Both of them are compiled time definitions, since we might not change the address translation mode at runtime.
> 
> ```
> #define CORE_MMU_SHIFT_OF_LEVEL(level) (RISCV_PGLEVEL_BITS * \
> 					((RISCV_PGLEVELS) - level) + \
> 					RISCV_PGSHIFT)
> 
> #if RISCV_MMU_MODE == 57	/*Sv57*/
> #define CORE_MMU_PGDIR_LEVEL	U(5)
> #elif RISCV_MMU_MODE == 48	/*Sv48*/
> #define CORE_MMU_PGDIR_LEVEL	U(4)
> #elif RISCV_MMU_MODE == 39	/*Sv39*/
> #define CORE_MMU_PGDIR_LEVEL	U(3)
> #elif RISCV_MMU_MODE == 32	/*Sv32*/
> #define CORE_MMU_PGDIR_LEVEL	U(2)
> #else
> #error unknown or unsupported mmu mode
> #endif
> 
> #define CORE_MMU_PGDIR_SHIFT \
> 	CORE_MMU_SHIFT_OF_LEVEL((CORE_MMU_PGDIR_LEVEL - 1))
> 
> #define CORE_MMU_BASE_TABLE_LEVEL U(1)
> #define CORE_MMU_BASE_TABLE_SHIFT \
> 	CORE_MMU_SHIFT_OF_LEVEL(CORE_MMU_BASE_TABLE_LEVEL)
> ```

@gagachang Back to this, I'm not sure it is suitable that at certain page table level will have a shift and therefore page size of the previous level. This will make debugging a mess. I was not able to make it working with your suggestion but by just reading the code it leads to confusion. I'll try another way.

**Comment by gagachang** [comment]
@maroueneboubakri That's OK. Any better solution or discussion are welcome!

By the way, one of important issues is the mapping of ARM SMCCC to RISC-V SBI.
I can see @liushiwei007 has submitted a proposal of SBI TEE extension, but unfortunately it did not capture committee's attention.

**Comment by gagachang** [comment]
Hi @jenswi-linaro 

Is it possible to add a `next_level` field into [struct core_mmu_table_info](https://github.com/OP-TEE/optee_os/blob/master/core/include/mm/core_mmu.h#L381) ?
The `next_level` means the "next finer grained level" according to that table.
Therefore ARM can have `next_level` with increasing style, while RSIC-V has decreasing style.

In [core_mmu_map_region()](https://github.com/OP-TEE/optee_os/blob/master/core/mm/core_mmu.c#L1748) which is used to create **va** to **pa** mapping with page tables.
The `level++` could be `level = tbl_info->next_level`.
`assert(level <= CORE_MMU_PGDIR_LEVEL);` could be changed to arch-specific checking function.

The same concept could be adopted also to [core_mmu_populate_user_map()](https://github.com/OP-TEE/optee_os/blob/master/core/mm/core_mmu.c#L2002).
`dir_info->level + 1` could be `dir_info->next_level`.

Any comments would be appreciated, thanks!

**Comment by jenswi-linaro** [comment]
@gagachang, good idea. I guess, `level`, `next_level`, and `shift` could all use a `uint8_t` instead so the struct doesn't have to grow in size.

**Comment by gagachang** [comment]
@jenswi-linaro  thanks for agreement,
I will prepare some PR for this.

**Comment by maroueneboubakri** [comment]
Based on this I re-open my old MM PR
https://github.com/OP-TEE/optee_os/pull/6104
Feel free to add your comments.
