### ISSUE TITLE
Use distro host toolchain instead of the one provided by Arm?

### ISSUE THREAD

**Issue by jbech-linaro** [OP-TEE/optee_os#5726]
In the OP-TEE project we've always been using pre-built toolchains provided by Arm (and Linaro in the past). However, I've seen a couple of challenges with using the Arm provided toolchains:
- They're often lagging behind with their releases.
- They're linked to various Python versions making it pretty challenging to run GDB.

I'd like to hear what others have to say about us moving away from the pre-built Arm provided toolchains to instead use the one provided by the host. I.e., for now, for example, step up to gcc11 (I can see that 12 also is available).
```
$ sudo apt install gdb-multiarch gcc-11-aarch64-linux-gnu gcc-11-arm-linux-gnueabihf
```

**Comment by jenswi-linaro** [comment]
By the way, what's the problem with GDB? I rarely try to keep that in sync.

**Comment by jbech-linaro** [comment]
Our current GCC version we use in OP-TEE is linked to Python 2.7. The 11.3.Rel1 Arm provide is linked to Python 3.8. I've done various exotic exercises with installing and/or providing the correct libraries and Python versions. But, by far, the easiest is to just install `gdb-multiarch` and use that to run gdb. So, if we don't want to make big changes, perhaps letting people know that would be an easy way forward. The "lagging" issue I suppose we can live with, but not being able to run gdb, is bad IMHO :)

**Comment by jforissier** [comment]
> I'd like to hear what others have to say about us moving away from the pre-built Arm provided toolchains

I would be favorable to that, it would be one less dependency to worry about and update on our side. Note that the GitHub CI script in `optee_os` already uses the Ubuntu 22.04 host toolchain (see the [CI script](https://github.com/OP-TEE/optee_os/blob/3.19.0/.github/workflows/ci.yml#L76-L77) and [Dockerfile](https://github.com/jforissier/docker_optee_os_ci/blob/8fab8f569896/Dockerfile#L29-L30)). And "big projects" like Yocto/OE do not use the Arm toolchain either, so I see very little point in keeping it as some sort of reference.

**Comment by jenswi-linaro** [comment]
> Support both ways? That could certainly also be an alternative.

Come to think of it, it might be better to just support one way.
I'm in favor of switching to a distro host toolchain.

**Comment by jforissier** [comment]
When updating the dev environment to GCC 11.3 in https://github.com/OP-TEE/build/pull/625 I was reminded that using an external toolchain with Buildroot has some constraints (one needs to specify `BR2_TOOLCHAIN_EXTERNAL_GCC_<version>` and `BR2_TOOLCHAIN_EXTERNAL_HEADERS_<version>`). Not sure how this is best handled. Using an internal toolchain is of course possible and easy but will add to build time.

**Comment by jbech-linaro** [comment]
> When updating the dev environment to GCC 11.3 in [OP-TEE/build#625](https://github.com/OP-TEE/build/pull/625) I was reminded that using an external toolchain with Buildroot has some constraints (one needs to specify `BR2_TOOLCHAIN_EXTERNAL_GCC_<version>` and `BR2_TOOLCHAIN_EXTERNAL_HEADERS_<version>`). Not sure how this is best handled. 

So, you're worried that we'll have a hard time setting something there that works for various distros? One "simple" way could be so simply say that we support the toolchain coming from them latest Ubuntu LTS? Also, I believe on most distros, you have the ability to install different versions of toolchains. But yes, it's a bit sub-optimal.

> Using an internal toolchain is of course possible and easy but will add to build time.

Internal as using the one that is used by default in Buildroot? Yes, that could work, but yes, build time is a concern. If one could use that, but pre-built, then the added time would be negligible, but if we have to compile the toolchain, then build time will increase a lot.

**Comment by jenswi-linaro** [comment]
> > When updating the dev environment to GCC 11.3 in [OP-TEE/build#625](https://github.com/OP-TEE/build/pull/625) I was reminded that using an external toolchain with Buildroot has some constraints (one needs to specify `BR2_TOOLCHAIN_EXTERNAL_GCC_<version>` and `BR2_TOOLCHAIN_EXTERNAL_HEADERS_<version>`). Not sure how this is best handled.
> 
> So, you're worried that we'll have a hard time setting something there that works for various distros? One "simple" way could be so simply say that we support the toolchain coming from them latest Ubuntu LTS? Also, I believe on most distros, you have the ability to install different versions of toolchains. But yes, it's a bit sub-optimal.

Can we check which version of the toolchain is provided and set those BR2_TOOLCHAIN* variables as needed?

> 
> > Using an internal toolchain is of course possible and easy but will add to build time.
> 
> Internal as using the one that is used by default in Buildroot? Yes, that could work, but yes, build time is a concern. If one could use that, but pre-built, then the added time would be negligible, but if we have to compile the toolchain, then build time will increase a lot.

This is a last resort for some corner cases. Normally we should be able to use a provided toolchain.
