### ISSUE TITLE
Multi-threaded TA

### ISSUE THREAD

**Issue by th0ma5b** [OP-TEE/optee_os#5744]
Hi OP-TEE experts,

Are you aware of any ongoing work regarding adding support for multi-threading in the same TA memory space?

Best Regards

**Comment by jforissier** [comment]
Hi @th0ma5b,

No, I am not aware of any effort in this area. The topic has been mentioned a few times in the past but it didn't go as far as implementation as far as I can tell.

**Comment by th0ma5b** [comment]
- In the list of ideas Jens Wiklander/OP-TEE team has kindly collected a while back in this document:
https://docs.google.com/document/d/1a8usDgYcB5JCJTHM6oCfDK4r6laVoJmTZA4Du6OnyqU/edit?usp=sharing
Are you aware of a preferred one? Or of one that has definitely been ruled out?

- Is it right to think that the only way to get spare threads is via the non-secure world?

**Comment by jforissier** [comment]
> Is it right to think that the only way to get spare threads is via the non-secure world?

As long as the scheduler remains on the Linux side, I believe there is no choice other than having threads created there too. If threads were to be known only to OP-TEE, the TEE core would need its own scheduler and that would have big implications I believe (need a timer interrupt, how to play nice with the NS scheduler, etc.).
