### ISSUE TITLE
Use CFG_VIRTUALIZATION=y on optee_os fvp version, Build Error

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5746]
Hello,

I'm try to enable CFG_VIRTUALIZATION=y on OP-TEE 3.19 on server environment. optee os runs at S-EL1 and hafnium runs at S-EL2.
When I build the optee_os code, I encountered the below error:

In file included from core/arch/arm/mm/core_mmu_lpae.c:61:0:
core/arch/arm/mm/core_mmu_lpae.c: In function ‘core_alloc_mmu_prtn’:
lib/libutils/isoc/include/assert.h:31:24: error: duplicate case value
   switch (0) { case 0: case ((x) ? 1: 0): default : break; } \
                        ^
core/arch/arm/mm/core_mmu_lpae.c:460:2: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
  COMPILE_TIME_ASSERT(sizeof(base_xlation_table) <= SMALL_PAGE_SIZE);
  ^~~~~~~~~~~~~~~~~~~
lib/libutils/isoc/include/assert.h:31:16: note: previously used here
   switch (0) { case 0: case ((x) ? 1: 0): default : break; } \
                ^
core/arch/arm/mm/core_mmu_lpae.c:460:2: note: in expansion of macro ‘COMPILE_TIME_ASSERT’
  COMPILE_TIME_ASSERT(sizeof(base_xlation_table) <= SMALL_PAGE_SIZE);
  ^~~~~~~~~~~~~~~~~~~
core/arch/arm/mm/core_mmu_lpae.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-c2x-extensions’
mk/compile.mk:163: recipe for target 'out/arm-plat-vexpress/core/arch/arm/mm/core_mmu_lpae.o' failed
make: *** [out/arm-plat-vexpress/core/arch/arm/mm/core_mmu_lpae.o] Error 1
++ cp out/arm-plat-vexpress/core/tee-pager_v2.bin /home/yuye/V2/Ali_M1_Private/Atf/optee/

I tracked the code. SMALL_PAGE_SIZE is 0x1000, sizeof(base_xlation_table) is 0x2000. I dont know why? 
It might be worth adding that in my current configuration, CFG_TEE_CORE_NB_CORE=128 and CFG_CORE_UNMAP_CORE_AT_EL0=y.

**Comment by jenswi-linaro** [comment]
This isn't supported upstream yet. The pull request https://github.com/OP-TEE/optee_os/pull/5359 should sort out the OP-TEE side of things, but note that you need something for the non-secure hypervisor too. Are you using Xen as non-secure hypervisor or some other configuration?

**Comment by zzbios** [comment]
> This isn't supported upstream yet. The pull request #5359 should sort out the OP-TEE side of things, but note that you need something for the non-secure hypervisor too. Are you using Xen as non-secure hypervisor or some other configuration?

Hi，I thought CFG_VIRTUALIZATION=y was the configuration that relates to SPMC on the secure-world side. And I'm a bit confused, if I use Hafnium as a relay for CA/TA communication, is a hypervisor on the non-secure side required？

**Comment by jenswi-linaro** [comment]
I'm sorry for the confusion. `CFG_VIRTUALIZATION` was introduced a long time ago before we even had heard of a secure EL2.  See https://optee.readthedocs.io/en/latest/architecture/virtualization.html for more info.

For an SPMC a non-secure hypervisor is optional in the Arm architecture and not yet supported in OP-TEE.

See this mail thread for my test setup on QEMU with Hafnium: https://lists.trustedfirmware.org/archives/list/hafnium@lists.trustedfirmware.org/thread/OK2G4VJDXW552XFXMWLY2H44KPAEZVBC/

**Comment by jforissier** [comment]
> I'm sorry for the confusion. `CFG_VIRTUALIZATION` was introduced a long time ago before we even had heard of a secure EL2. See https://optee.readthedocs.io/en/latest/architecture/virtualization.html for more info.

Should the symbol be renamed `CFG_NW_VIRTUALIZATION` maybe? (with `CFG_NW_VIRTUALIZATION ?= $(CFG_VIRTUALIZATION)` for compatibility). CC @lorc

**Comment by lorc** [comment]
Hi @jforissier,

Yes, it seems like a reasonable change.

**Comment by jforissier** [comment]
> Yes, it seems like a reasonable change.

Thanks for the feedback, I'll propose a PR after the upcoming release.

**Comment by zzbios** [comment]
> I'm sorry for the confusion. `CFG_VIRTUALIZATION` was introduced a long time ago before we even had heard of a secure EL2. See https://optee.readthedocs.io/en/latest/architecture/virtualization.html for more info.
> 
> For an SPMC a non-secure hypervisor is optional in the Arm architecture and not yet supported in OP-TEE.
> 
> See this mail thread for my test setup on QEMU with Hafnium: https://lists.trustedfirmware.org/archives/list/hafnium@lists.trustedfirmware.org/thread/OK2G4VJDXW552XFXMWLY2H44KPAEZVBC/

Thanks for the confirmation.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/5809
