### ISSUE TITLE
The version of newlibc

### ISSUE THREAD

**Issue by bqiu728** [OP-TEE/optee_os#5747]
Hi all,

Is there anywhere that I can get the version of newlib c, which is used in OPTEE-OS

thanks

**Comment by jforissier** [comment]
Hi @bqiu728,

I'm afraid there is no simple answer to that question. OP-TEE does not use the "official" newlib C library, instead some source files from the newlib repository are imported into OP-TEE and are compiled into libutils (under `lib/libutils`). Code has been imported in several steps on an ad hoc basis. That means, functions may come from different versions of newlib.
Also note that some function have been modified to fit OP-TEE needs (typically to be able to build outside of the normal newlib build system).

**Comment by bqiu728** [comment]
> 

Hi jforissier,

Got it. Thanks for your reply.
