### ISSUE TITLE
How to creat a new memory pool

### ISSUE THREAD

**Issue by bqiu728** [OP-TEE/optee_os#5748]
Hi All

Is there any API that can allow users to create a new memory pool just like gen_pool_create in Linux kernel ? 

I would like to manage a independent memory range for some use case. And this range can not be used by other case.

thanks

**Comment by jenswi-linaro** [comment]
Not quite like `gen_pool_create()`, but perhaps good enough for your purpose. The raw_* functions in `malloc.h` might do what you're looking for. If you need an out of band allocator instead you should look at the tee_mm_* functions in `tee_mm.h`

**Comment by bqiu728** [comment]
> tee_mm_

Thanks， Thant‘s what I'm looking for. I would try  tee_mm_* in `tee_mm.h `functions first
