### ISSUE TITLE
Memory buffer shared between instances of a multi-instance TA

### ISSUE THREAD

**Issue by th0ma5b** [OP-TEE/optee_os#5754]
Hi OP-TEE Team,

What is the best way to share a memory buffer only between all instances of a multi-instance TA?

**Comment by jenswi-linaro** [comment]
I assume it's a non-secure memory buffer. You have to pass it as a memref in each invoke.

**Comment by th0ma5b** [comment]
Hi Jens, thanks for your reply,
Sorry I should have been clearer here, please assume it is Secure memory.

**Comment by th0ma5b** [comment]
Probably overkill, but could a global buffer defined in a dynamic TA be used for this purpose?

**Comment by jenswi-linaro** [comment]
Only read-only shared secure memory is supported at the moment and that's set up automatically when the TA is loaded.

**Comment by th0ma5b** [comment]
That's good, so loading a dynamic TA would allow to share a read-only buffer between all instances of a multi-instance TA.

Are you aware of any other method?

**Comment by jforissier** [comment]
Secure storage could be another option if access speed is not critical.

**Comment by th0ma5b** [comment]
Thanks, so for now I'll assume these are the only 2 methods.
