### ISSUE TITLE
How does AArch64 Kernel in EL1 invoke Tee-OS ?

### ISSUE THREAD

**Issue by ericwu0083** [OP-TEE/optee_os#576]
Excuse me, I am a newbie of tee OS to support 64 bit architecture.

It seems the newest optee OS can support 64 bit cpu architecture.
However, I found there is only aarch32 smc vector table assembly (core/arch/arm/sm/sm_a32.S) in source code, then how does aarch64 kernel running in EL1 jump to AArch32 smc vector?

As my understanding, smc instruction called in AArch64 execution state jump to AArch64 EL3 exception vectors without switching cpu execution state,

Thanks.

**Comment by jenswi-linaro** [comment]
Hi,

SMCs are trapped at EL3 in Aarch64. OP-TEE only handles Secure EL1 and EL0 in Aarch64. EL3 is handled by ARM Trusted Firmware. ARM-TF contains a Dispatcher which corresponds to the Secure Monitor used in ARMv7/Aarch32.

Regards,
Jens

**Comment by jbech-optee-adm** [comment]
Question has been answered, please re-open in case you have additional questions.

**Comment by ericwu0083** [comment]
Sorry I have the additional question after I port BL31.

I am testing the BL31(tspd) --> BL32 (tsp) with the TSP_ADD/TSP_SUB/TSP_MUL/TSP_DIV fast call.
However, I will assert at assert(handle == cm_get_context(NON_SECURE));
because my  cm_get_context(NON_SECURE) is null.
If I force to set this with cm_set_context(handle, NON_SECURE), the dispatch can go on to tsp_entrypoint，but something will be abnormal:
1.  It didn't switch to secure state at EL1 
2.  My uart is locked

I am wondering did I made any mistake in BL31 initialization to cause this problem?
Thanks.
