### ISSUE TITLE
OPTEE secure DRAM assumed to be <=32MB on i.MX 8M Plus (and other i.MX 8M family members)

### ISSUE THREAD

**Issue by acoshan** [OP-TEE/optee_os#5763]
Hi.  Please forgive any etiquette breachs from me as a first-time poster.  Sorry, but I could not find a way to ask a question (raise an issue) on the repo nxp-imx/imx-optee-os, which seems to be the new location of the codeaurora repo that I am using.  Hence me asking here.

I am building OPTEE for an i.MX8MPlus.  I obtained the source code from source.codeaurora.org/external/imx/imx-optee-os.git (branch "lf-5.10.y_1.0.0", commit "87956c343f6a1a24dfe57e7d5c77dfc10b45148c")

I need to make more (secure) DRAM available to my TAs and so I increased _CFG_TZDRAM_SIZE_ from 01c00000 (defaulted in core/arch/arm/plat-imx/conf.mk) to 04000000 (set on the 'make' command line), i.e. 64MB.

Having rebuilt, I found that _verify_special_mem_areas()_ in core/arch/arm/mm/core_mmu.c failed due to [_DRAM1_NSEC_BASE_, _DRAM1_NSEC_BASE_+_DRAM1_NSEC_SIZE_) overlapping with _MEM_AREA_TA_RAM_

It would appear that this is due to the definition of _DRAM1_NSEC_BASE_ in core/arch/arm/plat-imx/platform_config.h assuming that the TA_RAM is at most 32MB.
 

**So, my questions are:** 
(a) is it acceptable to make the _MEM_AREA_TEE_RAM\_*_ plus _MEM_AREA_TA_RAM_ larger than 32MB (it defaults to 28MB, comprising 2MB for the former followed by 26MB for the latter)?

(b) would it be safe to change platform_config.h to define _DRAM1_NSEC_BASE_ as (_CFG_TZDRAM_START_ + _CFG_TZDRAM_SIZE_), rather than (_CFG_TZDRAM_START_ + 0x2000000) ?
 

Many thanks,
Andy

**Comment by jenswi-linaro** [comment]
(a): sounds OK to me.
(b): Sure, but don't forget to update eventual firewall settings the memory too.

**Comment by acoshan** [comment]
Thank you @jenswi-linaro 

What do you mean by "eventual firewall settings" in your answer to (b)?  

I have checked that the TZASC is correctly configured according to my new value of _CFG_TZDRAM_SIZE_ (configured by _tzc_auto_configure()_ in core/drivers/tzc380.c; I checked using _tzc_dump_state()_).  Is there somewhere else I should check/update?


Thanks,
Andy

**Comment by jenswi-linaro** [comment]
No, it was the TZASC I had in mind.
