### ISSUE TITLE
Get device/bootloader information via TA

### ISSUE THREAD

**Issue by mhelpenstein** [OP-TEE/optee_os#5765]
Hello all,

I am currently trying to create a secure environment for a research project where it can be detected if a device has been compromised. For this I am trying to load different information from the hardware device/bootloader directly from a TA without passing this information over the NW before. I am currently testing the setup with Qemu and with an NXP i.MX 6 board.

My question is if Optee has any way to get this information directly from the boot process or from the device. Maybe the bootloader can store this information in a secure storage and read this information directly from the TA.

I have found a similar question on this before (https://github.com/OP-TEE/optee_os/issues/1469), but it was a few years ago and maybe there is a way to do this now.

**Comment by jenswi-linaro** [comment]
This sounds a bit like a TPM event log.
Anyway, there is no generic way for a TA to ask OP-TEE about this. It might help with a more concrete example.

**Comment by Helpi1990** [comment]
Unfortunately, we don't know exactly what information we need yet because we don't know what we can work with. 

An example would be the mac address/chip id of the board or the version of the bootloader.

Another example would be the checksums of the loaded software to verify it.

**Comment by jenswi-linaro** [comment]
OK, sounds like this could potentially be secure or sensitive stuff. It would at least need to have guarantees for its integrity.

To start with I'd recommend adding a pseudo TA to interface with a normal user TA. OP-TEE could when initializing read values provided at some magic address by the boot loader.

**Comment by Helpi1990** [comment]
Thanks for your help, I was able to successfully create my own pseudo ta and use it with a user ta.

> OP-TEE could when initializing read values provided at some magic address by the boot loader.

Could you tell me where the collection of information needs to be implemented so that this information can be provided to the PTA?

**Comment by jenswi-linaro** [comment]
I guess this is the implementation specific part of the problem. OP-TEE should probably gather this during boot before exiting to the normal world the first time.

**Comment by mhelpenstein** [comment]
Thanks, ticket can be closed
