### ISSUE TITLE
riscv support on op-tee

### ISSUE THREAD

**Issue by sichunqin** [OP-TEE/optee_os#5770]
Hi,
I see that some riscv activities are going on op-tee. I am wondering how op-tee is support on risc-v.  As I know that, risc-v doesn't support trustzone hardware on which op-tee replies on.  risc-v has PMP support which could be used as security measure.  
Does op-tee requires risc-v support trustzone?  Look forwarding to your replies. Thanks!
Best Regards,
Sichun Qin

**Comment by gagachang** [comment]
Without hardware (like TrustZone) support there should be some security and performance penalties.
For example, peripheral and interrupt isolations, direct interrupt handling in S-mode.
If these things do not matter, PMP is enought to build an educative system.
Remember that you still need a M-mode secure monitor and S-mode kernel driver.

**Comment by sichunqin** [comment]
@gagachang, thanks for your reply. If I understand correctly, Hardware supported TrustZone on RISC-V is required to set up secure OP-TEE? M-mode secure monitor is set up based on Open-SBI?  Is it part of OP-TEE, or separate repository? Thanks.

**Comment by gagachang** [comment]
> Hardware supported TrustZone on RISC-V is required to set up secure OP-TEE? 

If you don't care about the peripherals and performance, PMP is enough to construct a secure environment to run OP-TEE.

> M-mode secure monitor is set up based on Open-SBI?

I only know someone has implemented their secure monitor based on openSBI, but I don't have the code.
See: https://github.com/riscv-software-src/opensbi/issues/282

**Comment by maroueneboubakri** [comment]
Hi @sichunqin,

Thanks @gagachang for providing preliminary answers.

TrustZone is ARM proprietary technology.  Correct statement is that OP-TEE relies on it for ARM architecture indeed. For RISC-V there is security mechanisms that allow you to create a TEE/enclave such as PMP,IOPMP and probably more (smpu/smepmp )
We are leveraging these to run OP-TEE on RISC-V.

There is ongoing work also on implementing a Hypervisor-based TEE. 

With regards to peripherals we rely on IOMPMP to assign a peripheral to the domain where OP-TEE run.

Regards
Maro

**Comment by gagachang** [comment]
The IOPMP specification is still under discussion, and its ratification target date is Q4, 2023.

**Comment by maroueneboubakri** [comment]
> The IOPMP specification is still under discussion, and its ratification target date is Q4, 2023.

Correct. For now what we are implementing is only based on ratified extensions.

**Comment by sichunqin** [comment]
@maroueneboubakri @gagachang Thanks a lot for your reply!

I guess the context switch between normal world and secure world would be done in M-code (openSBI?). This part of code could not in OP-TEE repository, but in somewhere in openSBI repository? This part of source code could be open sourced? 

Best Regards,
Sichun

**Comment by maroueneboubakri** [comment]
Hi @sichunqin,

All what you said is correct

Have a look at https://github.com/riscv-non-isa/riscv-ap-tee 
You can also look at https://github.com/keystone-enclave/keystone
and https://github.com/riscv-software-src/opensbi/issues/282

But in the current stage we will not use any of these, instead we rely on OpenSBI domains.

Best
Maro

**Comment by sichunqin** [comment]
Hi @maroueneboubakri, 
Thanks for the sharing!

I fail to make RISCV op-tee on the lastest tee-os code by using the following make command: 
make ARCH=riscv PLATFORM=spike CROSS_COMPILE64=riscv64-linux-gnu-

It seems that CI test doesn't include RISCV testing yet. 

Best Regards,
Sichun

**Comment by maroueneboubakri** [comment]
> Hi @maroueneboubakri, Thanks for the sharing!
> 
> I fail to make RISCV op-tee on the lastest tee-os code by using the following make command: make ARCH=riscv PLATFORM=spike CROSS_COMPILE64=riscv64-linux-gnu-
> 
> It seems that CI test doesn't include RISCV testing yet.
> 
> Best Regards, Sichun

@sichunqin Building yet is not possible, there is more PRs to be opened or merged.

**Comment by Ethan-cho** [comment]
@maroueneboubakri 
Hello, Can I ask a question?
Can I run OP-TEE for RISC-V based on QEMU?

**Comment by maroueneboubakri** [comment]
> @maroueneboubakri Hello, Can I ask a question? Can I run OP-TEE for RISC-V based on QEMU?

@Ethan-cho In the current upstreaming stage, no, when finished merging all PRs yes you will be able to run it on QEMU Virt machine.

**Comment by yli147** [comment]
@maroueneboubakri  do you have a code base in github can let have a quick try ? Thanks

**Comment by maroueneboubakri** [comment]
@yli147 unfortunately no.

**Comment by fanghuaqi** [comment]
> 

@yli147 we have open source our Op-TEE platform implementation here, you can check this issue https://github.com/OP-TEE/optee_os/issues/6173
