### ISSUE TITLE
User-defined Syscall

### ISSUE THREAD

**Issue by i-nevo** [OP-TEE/optee_os#5783]
Hi, 
In order to support our TA's needs we added a User defined Syscall:
`#define TEE_SCN_USER_DEF_OPERATION		71`
so the TA can request OPTEE to do something on its behalf (e.g. send an SMC, access a secure HW resource).
In order to make the implementation of this syscall user defined we implemented an empty weak routine:
```
/* Allows adding a user defined syscall in the platform specific code
 * If such syscall is not defined, then the operation is not supported.
 */
__weak TEE_Result syscall_user_def_operation(unsigned long op_id __maybe_unused,
									unsigned long param1 __maybe_unused,
									unsigned long param2 __maybe_unused,
									unsigned long param3 __maybe_unused,
									unsigned long param4 __maybe_unused,
									unsigned long param5 __maybe_unused,
									unsigned long param6 __maybe_unused,
									unsigned long param7 __maybe_unused)
{
	return TEE_ERROR_NOT_SUPPORTED;
}
```
and added it to the syscall table:
`SYSCALL_ENTRY(syscall_user_def_operation)`
And had an overriding routine that handles all such calls in our Platform-specific code.
We considered using a PTA for this, but since our TA is use for Real-time tasks it requires low latency and the API between TAs is just not fast enough.
To avoid future problems with OPTEE version updates, we would like to upstream this change, but we saw in previous discussions that adding syscalls is discouraged. Would you consider adding a single User-defined syscall so everyone can add new functionality (using the first register/parameter as operation ID) using this syscall?

**Comment by jenswi-linaro** [comment]
Such hardware specific things are not supposed to be visible to a TA so I assume it should be possible to abstract it in some way.
