### ISSUE TITLE
Implementing symbol versioning in shared libraries

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#5801]
During the review of #5688 the question came up of implementing symbol versioning in user space shared libraries (especially libutee). I am opening this issue for reference only, to share a quick investigation I've done: https://docs.google.com/document/d/1qvN4WIIcmk3MGWdpdB3-hpg3oOErI7tgYbfGx9VR6FA.

In case anyone feels like doing the ldelf part, feel free :wink:

**Comment by jenswi-linaro** [comment]
Thanks for the investigation. Sounds like a fun little project if you can afford the time.

**Comment by etienne-lms** [comment]
thanks @jforissier for the details.

**Comment by jforissier** [comment]
Closing because https://github.com/OP-TEE/optee_os/pull/5833 has all the information and some code.
