### ISSUE TITLE
optee secure_storage example CA fails to run

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5803]
Run optee_example_secure_storage in REE OS, the debug print of Hafnium and OPTEE is as follows:
#./optee_example_secure_storage

Prepare session with the TA
D/TC:046 0 mobj_ffa_get_by_cookie:382 cookie 0 resurrecting
D/TC:??? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA f4e750bb-1437-4fbf-8785-8d3580c34994
D/TC:??? 0 ldelf_load_ldelf:96 ldelf load address 0x40008000
D/LD:  ldelf:134 Loading TS f4e750bb-1437-4fbf-8785-8d3580c34994
F/TC:??? 0 trace_syscall:151 syscall #3 (syscall_get_property)
F/TC:??? 0 trace_syscall:151 syscall #5 (syscall_open_ta_session)
D/TC:??? 0 ldelf_syscall_open_bin:143 Lookup user TA ELF f4e750bb-1437-4fbf-8785-8d3580c34994 (early TA)
D/TC:??? 0 ldelf_syscall_open_bin:146 res=0
F/TC:??? 0 trace_syscall:151 syscall #7 (syscall_invoke_ta_command)
F/TC:??? 0 read_compressed:178 4096 bytes
F/TC:??? 0 trace_syscall:151 syscall #11 (syscall_mask_cancellation)
F/TC:??? 0 trace_syscall:151 syscall #7 (syscall_invoke_ta_command)
F/TC:??? 0 read_compressed:178 91832 bytes
F/TC:??? 0 trace_syscall:151 syscall #3 (syscall_get_property)
F/TC:??? 0 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:??? 0 read_compressed:178 1024 bytes
F/TC:??? 0 read_compressed:178 1024 bytes
F/TC:??? 0 read_compressed:178 328 bytes
F/TC:??? 0 read_compressed:178 920 bytes
F/TC:??? 0 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:??? 0 read_compressed:178 248 bytes
F/TC:??? 0 read_compressed:178 760 bytes
F/TC:??? 0 trace_syscall:151 syscall #6 (syscall_close_ta_session)
F/TC:??? 0 trace_syscall:151 syscall #3 (syscall_get_property)
D/LD:  ldelf:169 ELF (f4e750bb-1437-4fbf-8785-8d3580c34994) at 0x40061000
F/TC:??? 0 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:??? 0 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:??? 0 trace_syscall:151 syscall #4 (syscall_get_property_name_to_index)
D/TC:046 0 ffa_inactivate:495 cookie 0

Test on object "object#1"
\- Create and load object in the TA secure storage
VERBOSE: Marked sending complete.
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x1 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
**VERBOSE: Invalid transition for send.**
**VERBOSE: Complete failed, freeing share state.**
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x1 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
VERBOSE: Marked sending complete.
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x1 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
D/TC:046 0 mobj_ffa_get_by_cookie:382 cookie 0 resurrecting
E/TC:046 0 mobj_ffa_get_by_cookie:385 Populating mobj from rx buffer, cookie 0x1
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x1 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x1 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
E/TC:046 0 mobj_ffa_get_by_cookie:385 Populating mobj from rx buffer, cookie 0x2
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x1 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x1 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
F/TC:??? 0 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:??? 0 trace_syscall:151 syscall #42 (syscall_storage_obj_create)

Is this problem related to the configuration CFG_SHMEM_START and CFG_SHMEM_SIZE in optee_os？

**Comment by jenswi-linaro** [comment]
No, this is likely due to the Linux app trying to register the same physical page twice. There's a fallback when that happens, but the SPMC in TF-A seem to log the error.

**Comment by zzbios** [comment]
> No, this is likely due to the Linux app trying to register the same physical page twice. There's a fallback when that happens, but the SPMC in TF-A seem to log the error.

If so, how to explain this, when I change the CFG_SHMEM_START and CFG_SHMEM_SIZE, run CA in host os and get different results.
I even ran through the CA once successfully, but after I rebooted the server, the results changed again, such as:
```
VERBOSE: Freed share state after successful reclaim.
WARNING: SPM(42): 0x84000061 0x0 0x0 0x0 0x0 0x0 0x0 0x0
Command DELETE failed: 0xffff3024 / 3
**optee_example_secure_storage: Failed to delete the object: 0xffff3024**
WARNING: SPM(42): 0x8400006f 0x8001 0x0 0x80000000 0x0 0x0 0x0 0x0
VERBOSE: sender_vm->id:0x0, receiver_vm->id:0x8001
VERBOSE: sender_vm->messaging_method:3, receiver_vm->messaging_method:3
D/TC:042 0 mobj_ffa_get_by_cookie:382 cookie 0 resurrecting
D/TC:??? 0 tee_ta_close_session:511 csess 0xf00f27f0 id 1
D/TC:??? 0 tee_ta_close_session:529 Destroy session
D/TC:042 0 ffa_inactivate:495 cookie 0
WARNING: SPM(42): 0x84000070 0x80010000 0x0 0x0 0x0 0x0 0x0 0x0

```

**Comment by jenswi-linaro** [comment]
I can't. I guess you have to do some debugging.

**Comment by zzbios** [comment]
> I can't. I guess you have to do some debugging.

Hi, by the way, do you know the minimum amount of memory that optee needs to run TA like the secure_storage example？How about the static share memory？

**Comment by zzbios** [comment]
```
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x1 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
WARNING: Stage-2 page fault: pc=0x40032106, vmid=0x8001, vcpu=13, vaddr=0x40046ce0, ipaddr=0x8a9b28ce0, mode=0x81 0x63
NOTICE: Injecting Data Abort exception into VM 0x8001.
D/TC:013 0 abort_handler:550 [abort] abort in User mode (TA will panic)
E/TC:??? 0
E/TC:??? 0 User mode data-abort at address 0x40046ce0 (translation fault)
E/TC:??? 0  esr 0x94020007  ttbr0 0x20000f03061a0   ttbr1 0x00000000   cidr 0x0
E/TC:??? 0  cpu #13          cpsr 0x00000130
E/TC:??? 0  x0  000000004003e348 x1  000000004003e349
E/TC:??? 0  x2  0000000040046ce0 x3  000000004003e348
E/TC:??? 0  x4  0000000040036088 x5  0000000000000000
E/TC:??? 0  x6  0000000000000000 x7  0000000040042e28
E/TC:??? 0  x8  0000000000000000 x9  0000000000000000
E/TC:??? 0  x10 0000000000000000 x11 0000000000000000
E/TC:??? 0  x12 0000000000000000 x13 0000000040042e28
E/TC:??? 0  x14 00000000400213cf x15 0000000000000000
E/TC:??? 0  x16 0000000000000000 x17 0000000000000000
E/TC:??? 0  x18 0000000000000000 x19 0000000000000000
E/TC:??? 0  x20 0000000000000000 x21 0000000000000000
E/TC:??? 0  x22 0000000000000000 x23 0000000000000000
E/TC:??? 0  x24 0000000000000000 x25 0000000000000000
E/TC:??? 0  x26 0000000000000000 x27 0000000000000000
E/TC:??? 0  x28 0000000000000000 x29 0000000000000000
E/TC:??? 0  x30 0000000000000000 elr 0000000040032106
E/TC:??? 0  sp_el0 0000000040042f80
E/LD:  Status of TA f4e750bb-1437-4fbf-8785-8d3580c34994
E/LD:   arch: arm
E/LD:  region  0: va 0x40006000 pa 0xf0404000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40008000 pa 0xf0406000 size 0x011000 flags r-xs (ldelf)
E/LD:  region  2: va 0x40019000 pa 0xf0417000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x4001a000 pa 0xf0418000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x4001e000 pa 0xf041c000 size 0x001000 flags r--s
E/LD:  region  5: va 0x4001f000 pa 0x00001000 size 0x017000 flags r-xs [0]
E/LD:  region  6: va 0x40036000 pa 0x00018000 size 0x00c000 flags rw-s [0]
E/LD:  region  7: va 0x40042000 pa 0xf0440000 size 0x001000 flags rw-s (stack)
E/LD:  region  8: va 0x40043000 pa 0x8b9101620 size 0x003000 flags rw-- (param)
E/LD:  region  9: va 0x40046000 pa 0x8a9b28ce0 size 0x001000 flags rw-- (param)
E/LD:   [0] f4e750bb-1437-4fbf-8785-8d3580c34994 @ 0x4001f000
E/LD:  Call stack:
E/LD:   0x40032106
E/LD:   0x400213cf
E/LD:   0x4001f29b
E/LD:   0x4001f473
E/LD:   0x40023a25
E/LD:   0x40023a97
E/LD:   0x4003143f
E/LD:   0x4001f4b8
D/TC:??? 0 user_ta_enter:177 tee_user_ta_enter: TA panicked with code 0xdeadbeef
D/TC:??? 0 destroy_ta_ctx_from_session:322 Remove references to context (0xf02f27a8)
D/TC:??? 0 destroy_context:307 Destroy TA ctx (0xf02f2790)
D/TC:013 0 ffa_inactivate:495 cookie 0x1
D/TC:013 0 ffa_inactivate:495 cookie 0x2
D/TC:013 0 ffa_inactivate:495 cookie 0
WARNING: SPM(13): 0x84000070 0x80010000 0x0 0x0 0x0 0x0 0x0 0x0
WARNING: SPM(13): 0x8400006f 0x8001 0x0 0x3 0x1 0x0 0x0 0x0
VERBOSE: sender_vm->id:0x0, receiver_vm->id:0x8001
VERBOSE: sender_vm->messaging_method:3, receiver_vm->messaging_method:3
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x1 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x1 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
WARNING: SPM(13): 0x84000070 0x80010000 0x0 0x0 0x0 0x0 0x0 0x0
WARNING: SPM(13): 0x84000077 0x1 0x0 0x0 0x0 0x0 0x0 0x0
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x1 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
VERBOSE: Freed share state after successful reclaim.
WARNING: SPM(13): 0x84000061 0x0 0x0 0x0 0x0 0x0 0x0 0x0
WARNING: SPM(13): 0x8400006f 0x8001 0x0 0x3 0x2 0x0 0x0 0x0
VERBOSE: sender_vm->id:0x0, receiver_vm->id:0x8001
VERBOSE: sender_vm->messaging_method:3, receiver_vm->messaging_method:3
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
WARNING: SPM(13): 0x84000070 0x80010000 0x0 0x0 0x0 0x0 0x0 0x0
WARNING: SPM(13): 0x84000077 0x2 0x0 0x0 0x0 0x0 0x0 0x0
Current share states:
SHARE 0x0 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 1 retrieved,  sender's original mode: 0x7
SHARE 0x2 (from VM 0x0, attributes 0x2f, flags 0x8, tag 0, to 1 recipients [VM 0x8001: 0x6 (offset 48)]): fully sent with 1 fragments, 0 retrieved,  sender's original mode: 0x7
VERBOSE: Freed share state after successful reclaim.
WARNING: SPM(13): 0x84000061 0x0 0x0 0x0 0x0 0x0 0x0 0x0
Command READ_RAW failed: 0xffff3024 / 3
optee_example_secure_storage: Failed to read an object from the secure storage
WARNING: SPM(13): 0x8400006f 0x8001 0x0 0x80000000 0x0 0x0 0x0 0x0
VERBOSE: sender_vm->id:0x0, receiver_vm->id:0x8001
VERBOSE: sender_vm->messaging_method:3, receiver_vm->messaging_method:3
D/TC:013 0 mobj_ffa_get_by_cookie:382 cookie 0 resurrecting
D/TC:??? 0 tee_ta_close_session:511 csess 0xf02f27f0 id 1
D/TC:??? 0 tee_ta_close_session:529 Destroy session
D/TC:013 0 ffa_inactivate:495 cookie 0
WARNING: SPM(13): 0x84000070 0x80010000 0x0 0x0 0x0 0x0 0x0 0x0

```

**Comment by jenswi-linaro** [comment]
> WARNING: Stage-2 page fault: pc=0x40032106, vmid=0x8001, vcpu=13, vaddr=0x40046ce0, ipaddr=0x8a9b28ce0, mode=0x81 0x63
> NOTICE: Injecting Data Abort exception into VM 0x8001.

This is the key part. It seems that OP-TEE tries to use an IPA which isn't mapped by Hafnium. Hafnium maps (from what I have understood) IPA with its PA.

**Comment by zzbios** [comment]
>

**Comment by zzbios** [comment]
> > WARNING: Stage-2 page fault: pc=0x40032106, vmid=0x8001, vcpu=13, vaddr=0x40046ce0, ipaddr=0x8a9b28ce0, mode=0x81 0x63
> > NOTICE: Injecting Data Abort exception into VM 0x8001.
> 
> This is the key part. It seems that OP-TEE tries to use an IPA which isn't mapped by Hafnium. Hafnium maps (from what I have understood) IPA with its PA.

**Comment by zzbios** [comment]
Hi, ,there are some new developments on this issue. After the Hafnium finished configuring the stage-2 page table, we enable the TLB invalidation and the stage-2 page fault disappeared. The root cause needs to be further located.

**Comment by odeprez** [comment]
Hi,
We may miss invalidating S2 TLB entries for NS IPA space, in Hafnium mm code.
Can you try this as a workaround:

--- a/src/arch/aarch64/mm.c
+++ b/src/arch/aarch64/mm.c
@@ -397,6 +397,7 @@ void arch_mm_invalidate_stage2_range(uint16_t vmid, ipaddr_t va_begin,
                for (it = begin; it < end;
                     it += (UINT64_C(1) << (PAGE_BITS - 12))) {
                        tlbi_reg(ipas2e1is, it);
+                       tlbi_reg(ipas2e1is, it | (1ULL << 63));
                }

We may provide refined changes (hopefully beg. of March) as follow up to this discussion:
https://lists.trustedfirmware.org/archives/list/hafnium@lists.trustedfirmware.org/thread/ZUHRGWVDPUQ5CK6SRWZ7AMI5IKVS6J47/

**Comment by zzbios** [comment]
> Hi, We may miss invalidating S2 TLB entries for NS IPA space, in Hafnium mm code. Can you try this as a workaround:
> 
> ```
> --- a/src/arch/aarch64/mm.c
> +++ b/src/arch/aarch64/mm.c
> @@ -397,6 +397,7 @@ void arch_mm_invalidate_stage2_range(uint16_t vmid, ipaddr_t va_begin,
>                 for (it = begin; it < end;
>                      it += (UINT64_C(1) << (PAGE_BITS - 12))) {
>                         tlbi_reg(ipas2e1is, it);
> +                       tlbi_reg(ipas2e1is, (it | (1ULL << 63)));
>                 }
> ```
> 
> We may provide refined changes (hopefully beg. of March) as follow up to this discussion: https://lists.trustedfirmware.org/archives/list/hafnium@lists.trustedfirmware.org/thread/ZUHRGWVDPUQ5CK6SRWZ7AMI5IKVS6J47/

Hi,
It has been tested several times on our server that the fix here can effectively solved the issue.
Thanks. Precise change.
