### ISSUE TITLE
Questions about uid and gid of tee and teeclnt.

### ISSUE THREAD

**Issue by ydonghyuk** [OP-TEE/optee_os#5804]
I am testing the optee environment using qemu.
I have a question regarding tee / teeclnt.

Below are some of the contents of br-ext/package/optee_client_ext/optee_client_ext.mk.
```
# User tee is used to run tee-supplicant because access to /dev/teepriv0 is
# restricted to group tee.
# Any user in group teeclnt (such as test) may run client applications.
# Any user in group ion may access /dev/ion
define OPTEE_CLIENT_EXT_USERS
     tee -1 tee -1 * - /bin/sh - TEE user
     - -1 teeclnt -1 - - - - TEE users group
     - -1 ion -1 - - - - ION users group
     test -1 test -1 - - /bin/sh teeclnt,ion Test user, may run TEE client applications
endef
```

After compiling qemu buildroot, checking the '/etc/passwd' and '/etc/group' files under out-br (build output), I couldn't find a summary of tee and teeclnt.
However, when checking the same file after booting qemu, it was confirmed that the contents of tee and teeclnt were applied.

Could you explain how this works?

**Comment by jforissier** [comment]
Hello @ydonghyuk,

I don't know exactly how it works but it seems that Buildroot takes care of it when generating the image, not when populating the  `target/` directory. See the message: "Generating filesystem image" in `buildroot/fs/common.mk`. `PACKAGES_USERS` is used as an input. It is created by gathering all the `*_USERS` variables from the packages (such as `OPTEE_CLIENT_EXT_USERS`) by `buildroot/package/pkg-generic.mk`.

**Comment by ydonghyuk** [comment]
Thank you. You told me exactly what I was curious about.
