### ISSUE TITLE
conflict between printf & DMSG

### ISSUE THREAD

**Issue by yanxing-cui** [OP-TEE/optee_os#5808]
Hi there,
I'm running optee_example __aes__ demo in my board. After I configured the CFG_TEE_TA_LOG_LEVEL=3, the actual log in my terminal seems not normal like bellow:
````bash
Reset ciphering operation in TA (D/TA:  cipher_buffer:340 Session 0x4005b500: cipher buffer
provides the initial vector)
````
The expected log should be like this:
````bash
Reset ciphering operation in TA (provides the initial vector)
D/TA:  cipher_buffer:340 Session 0x4005b500: cipher buffer
````
The first line comes from printf function in CA. And the second line comes from DMSG micro in TA. I assume there might be some conflict between those two functions, right? 
Can anyone help here? Really appreciate it.

**Comment by jbech-linaro** [comment]
I guess that you don't have two separate UARTS? I.e., one for non-secure and one for secure. If you only have a single UART shared between secure and non-secure, then what you describe will happen.

**Comment by yanxing-cui** [comment]
Oh, that's right. Thanks for your reply!
