### ISSUE TITLE
How to register a memory range from DTS ?

### ISSUE THREAD

**Issue by bqiu728** [OP-TEE/optee_os#5811]
Hi,
I would like to register a memory range from DTS? I found that the method used most is that:
`#define __register_memory(_name, _type, _addr, _size, _section) \
	SCATTERED_ARRAY_DEFINE_ITEM(_section, struct core_mmu_phys_mem) = \
		{ .name = (_name), .type = (_type), .addr = (_addr), \
		  .size = (_size) }`
It seems that is static register.
So is there any other API I can use?

Thanks

**Comment by jenswi-linaro** [comment]
That's supposed to be taken care of in `discover_nsec_memory()` using `get_nsec_memory()`.

**Comment by bqiu728** [comment]
> 

thanks ,
It seems that this can only be used for nonsec memory. Is there any API for sec memory?

**Comment by jenswi-linaro** [comment]
No, but patches are welcome! :-)
