### ISSUE TITLE
Question for 'teeclnt' group

### ISSUE THREAD

**Issue by ydonghyuk** [OP-TEE/optee_os#5814]
I am testing the optee environment using qemu.
When I tried to proceed with this as a random user, not the root environment, I found out the existence of the 'teeclnt' group.
Additionally, I found out that the test user created in optee_clinet_ext.mk belongs to the teeclnt group.

When trying to access a TA, if the user does not belong to teeclnt or does not have a teeclnt gid, an access error occurs. Can you tell me where I can find information or code related to this?

**Comment by jforissier** [comment]
Hello @ydonghyuk,

Please see https://github.com/OP-TEE/build/commit/749527c6dcd0db13045c1f331024988b8d21a20f. This is purely a matter of permissions on `/dev/tee0`.

**Comment by ydonghyuk** [comment]
Thanks for your answer.

When a process (not root, run by a specific user) tries to access TA, how should uid/gid be set?

For example, should I run the process as username:teeclnt?
Or, like the test user provided by optee, should the specific user be included as a member of teeclnt and run as username:username?

**Comment by jforissier** [comment]
Your choice I suppose, based on other requirement your client application may have and other security policies for your system.

**Comment by ydonghyuk** [comment]
Checking the code, the test user belongs to teeclnt, but also to ion group.
Do I have to be included in the ion group in order to make a request to the TA as a specific user?

**Comment by jforissier** [comment]
https://github.com/OP-TEE/build/pull/623

**Comment by ydonghyuk** [comment]
Thanks for your support

**Comment by ydonghyuk** [comment]
Is the commit you provided merged now?
Did you just make a request?

**Comment by jforissier** [comment]
> Is the commit you provided merged now? Did you just make a request?

Not merged yet, still under review as well as https://github.com/OP-TEE/optee_test/pull/648.
