### ISSUE TITLE
Read/Write from/to OTP

### ISSUE THREAD

**Issue by aliii1986** [OP-TEE/optee_os#5820]
Hi community,

I am new to OPTEE OS, and need to read/write from/to an OTP register via a Trusted Application. I understand that I cannot read a register using its physical address and need to use the MMU address to access the register. What is the best was to find the MMU address of a register using its physical address via a Trusted Application?

Thanks!

**Comment by jenswi-linaro** [comment]
I don't think you should access OTP at all directly from a TA. Depending on the use case you may need to add a PTA to do this.

**Comment by gagachang** [comment]
You need to implement your OTP driver into kernel.
You also need to implement a Pseudo TA into kernel which invokes API of your OTP driver.
Finally, your user-space Trusted Application can invoke TEE Internal API to call your Pseudo TA.
PTA can do OTP operations and return results to user-space Trusted Application.

There is an example from broadcom SOTP:
https://github.com/OP-TEE/optee_os/blob/master/core/pta/bcm/sotp.c

**Comment by patrickdelaunay** [comment]
other example of PTA for OTP access on STM32MP13/15 platform with BSEC PTA

https://github.com/OP-TEE/optee_os/blob/master/core/pta/stm32mp/bsec_pta.c

and we are checking if OTP are accessible by non-secure 

Today the access is not allowed to other TA but it is planed 
for  OTP provisioning with TA (TA NVMEM) when 
- login == TEE_LOGIN_TRUSTED_APP
- ta_uuid = uuid of NVEM TA

**Comment by aliii1986** [comment]
Thanks a lot!!

**Comment by gjylnk** [comment]
I want to know how to get the data of otp, what do I need to do, can you help me answer?

**Comment by aliii1986** [comment]
See gagachang's answer above. That outlines the steps you need to take to read OTP register data.

**Comment by gjylnk** [comment]
I see it, but I don't know how to call this to implement it

**Comment by aliii1986** [comment]
Call what?
Can you be more specific on which of the steps listed in gagachang's comment you need help with?

**Comment by gjylnk** [comment]
The file he lists exists in my optee, but I don't know how to get this otp data from the file system

**Comment by gjylnk** [comment]
You successfully implemented this feature
