### ISSUE TITLE
the part that runs tee-supplicant through systemd init

### ISSUE THREAD

**Issue by ydonghyuk** [OP-TEE/optee_os#5825]
I am trying to test optee os and keymaster operation through systemd.

I configured the config as below to boot qemu with systemd init enabled.

```
BR2_PACKAGE_DROPBEAR=y
BR2_TARGET_GENERIC_ROOT_PASSWD="root"
# BR2_PACKAGE_BUSYBOX is not set
BR2_INIT_SYSTEMD=y
BR2_ROOTFS_SKELETON_DEFAULT=y
```

When checking after booting, the tee-supplicant daemon is not running.
I wonder if this part is implemented.

If possible, please guide me on that part.

**Comment by jenswi-linaro** [comment]
I guess that `BR2_INIT_SYSTEMD=y` means that boot is done slightly differently. You'll probably need to add something to the systemd configuration to start tee-supplicant.

**Comment by jforissier** [comment]
> You'll probably need to add something to the systemd configuration to start tee-supplicant.

Yes, from a Buildroot point of view it is probably just a matter of adding a new file: ` br-ext/board/<board_name>/overlay/etc/systemd/system/tee_supplicant.service`, but the question is what exactly needs to be put inside that file :wink:

**Comment by ydonghyuk** [comment]
Basically, it seems that tee_supplicant.service should be added by referring to the S30optee script when using busybox init.
If anyone can help, please comment.

**Comment by ydonghyuk** [comment]
@jenswi-linaro @jforissier 


After registering the tee-supplicant service, I succeeded in running it without problems.
However, there is one problem that I am struggling with.
When using busybox init, ssh access is normally possible from localhost to my qemu (remote) system. (I installed the dropbear package from qemu)
However, after activating systemd, ssh connection does not work as shown below.
The dropbear service is running normally in qemu.

'''
OpenSSH_7.6p1 Ubuntu-4ubuntu0.5, OpenSSL 1.0.2n 7 Dec 2017
debug1: Reading configuration data /home3/donghyuk.yang/.ssh/config
debug1: /home3/donghyuk.yang/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "localhost" port 12345
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to localhost [127.0.0.1] port 12345.
debug1: Connection established.
debug1: identity file /home3/donghyuk.yang/.ssh/id_rsa type 0
debug1: key_load_public: No such file or directory
debug1: identity file /home3/donghyuk.yang/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home3/donghyuk.yang/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home3/donghyuk.yang/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home3/donghyuk.yang/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home3/donghyuk.yang/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home3/donghyuk.yang/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home3/donghyuk.yang/.ssh/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5
ssh_exchange_identification: read: Connection reset by peer
'''

Can you please help me with this issue?

**Comment by ydonghyuk** [comment]
I solved the above problem after enabling below setting.
BR2_PACKAGE_NETWORK_MANAGER=y

However, I am not sure which of the packages installed by this had an effect.

**Comment by jforissier** [comment]
@ydonghyuk thanks for sharing. Would you mind pasting the systemd startup script you are using for tee-supplicant? I'm sure it can come in handy for some other people.

**Comment by ydonghyuk** [comment]
Nothing great, but sharing for those who need it.
I wrote it by referring to S30optee (busybox init start script).

```
[Unit]
Description=TEE-Supplicant
After=systemd-sysctl.service local-fs.target
Before=systemd-networkd.service

[Service]
Type=forking
PermissionsStartOnly=true
User=tee

ExecStartPre=/bin/chown root:tee /dev/teepriv0
ExecStartPre=/bin/chmod 0660 /dev/teepriv0
ExecStartPre=/bin/chown root:teeclnt /dev/tee0
ExecStartPre=/bin/chmod 0660 /dev/tee0

ExecStartPre=/bin/mkdir -p /data/tee
ExecStartPre=/bin/chown -R tee:tee /data/tee
ExecStartPre=/bin/chmod 0770 /data/tee
ExecStart=/usr/sbin/tee-supplicant -d /dev/teepriv0

[Install]
WantedBy=multi-user.target
```
