### ISSUE TITLE
Generating key pairs based on secret seeds

### ISSUE THREAD

**Issue by PrithviAPai** [OP-TEE/optee_os#5828]
Would OP-TEE (TEE_GenerateKey) allows developer to pass some secret value 
based on which it can generate ECC or RSA key pairs ?

**Comment by PrithviAPai** [comment]
@jforissier can you please help on this ?

**Comment by jbech-linaro** [comment]
I'd say no. The spec also says that it generates a **random key or key-pair**. I think that is expected behavior as well for RSA and ECC, since you need find/base it on prime numbers. What you're asking for is more something you'd see if you want to salt a regular password, that could be used for HMAC's for example. Perhaps I misunderstand your intentions?

**Comment by PrithviAPai** [comment]
I have a requirement to generate key-pairs which remain same is there any way I can do that ?

**Comment by quduoduo1** [comment]
Hello, I have the same problem. If TEE_GenerateKey does not accept input, does it mean that the last parameter uint32_t paramCount can only be 1？

**Comment by quduoduo1** [comment]
@jbech-linaro Can you please help on this？

**Comment by quduoduo1** [comment]
`	
	TEE_Result res = TEE_SUCCESS;
	TEE_ObjectHandle transient_key = TEE_HANDLE_NULL;
        uint32_t key_size = 256;
        objectType = TEE_TYPE_SM2_DSA_KEYPAIR;

	res = TEE_AllocateTransientObject(objectType, key_size, &transient_key);
	if (res != TEE_SUCCESS)
		return TEE_ERROR_OUT_OF_MEMORY;

	attrslen = 2;
	attrs = TEE_Malloc(attrslen * sizeof(*attrs), 0);
	if (!attrs) {
		res = TEE_ERROR_OUT_OF_MEMORY;
		goto free_obj;
	}

	attrs[0].attributeID = TEE_ATTR_ECC_CURVE;
	attrs[0].content.value.a = TEE_ECC_CURVE_SM2;

	attrs[1].attributeID = TEE_ATTR_SECRET_VALUE;
	attrs[1].content.ref.buffer = salt;
	attrs[1].content.ref.length = salt_size;

	res = TEE_GenerateKey(transient_key, key_size, attrs, attrslen);
	if (res != TEE_SUCCESS)
		goto free_attrs;`
I tried this, salt is a 64bits random number, but this leads to panic, ` TA panicked with code 0xffff0008`,  I wonder if I am using it wrong

**Comment by jforissier** [comment]
Hello @quduoduo1, for some reason I can't find your last comment anymore. I noticed:
```
attrs[0].attributeID = TEE_ATTR_ECC_CURVE;
attrs[0].content.value.a = TEE_ECC_CURVE_SM2;
```
This is wrong, for SM2 key pair generation you should not set the TEE_ATTR_ECC_CURVE attribute.
You do not need a seed either. In fact no attribute is needed at all, see the GlobalPlatform specification 1.3.1 table 5-12.

**Comment by PrithviAPai** [comment]
@jforissier for ECDSA key pair generation with secret seeds  do we have support from OP-TEE ?

**Comment by quduoduo1** [comment]
@PrithviAPai You can try this:
`objectType = TEE_TYPE_ECDSA_KEYPAIR;
keysize = 192/224/...,;
res = TEE_AllocateTransientObject(objectType , key_size,&transient_key);
attrs[0].attributeID = TEE_ATTR_ECC_CURVE;
attrs[0].content.value.a = TEE_ECC_CURVE_NIST_P192/TEE_ECC_CURVE_NIST_P224...;`
res = TEE_GenerateKey(transient_key, key_size, attrs, 1);

**Comment by quduoduo1** [comment]
@jforissier Thanks for the answer！ it seems that I did get confused...

**Comment by PrithviAPai** [comment]
@quduoduo1 but, where is that we are passing secret seed here ?

**Comment by quduoduo1** [comment]
@PrithviAPai TEE_GenerateKey does not require secret seed. Maybe you can look at TEE_DeriveKey？it accepts the other party’s public key as a parameter.But the two interfaces serve very different purposes，and TEE_DeriveKey's algorithm is also limited.

**Comment by PrithviAPai** [comment]
Thanks for the answer @quduoduo1 
I will check if TEE_DeriveKey suits my requirement

**Comment by PrithviAPai** [comment]
Closing the issue as OP-TEE doesnt support passing seeds while generating key pairs
