### ISSUE TITLE
Support for multiple interrupts per device node

### ISSUE THREAD

**Issue by abhisk612** [OP-TEE/optee_os#5831]
I see that interrupt parsing API  in GIC driver, namely,
`static int gic_dt_get_irq(const uint32_t *properties, int count, uint32_t *type, uint32_t *prio)` 
supports only 1 interrupt parsing from device's DT node's "interrupts =" property:
https://github.com/OP-TEE/optee_os/blob/3.20.0/core/drivers/gic.c#L213-L241

Since the `count` argument is containing correct number of bytes based on "interrupts ="  property (even if multiple interrupts are specified), ideally, we should be able to extend `dt_get_irq` API and get interrupt by index.

Is there any reason on why this API is not extended to parse multiple interrupts from DT?

**Comment by abhisk612** [comment]
Hi, is above observation correct, or did I miss something?

**Comment by jenswi-linaro** [comment]
I don't understand but feel free to propose a change to illustrate what you're missing.

**Comment by etienne-lms** [comment]
For info @abhisk612 , I created RFC P-R https://github.com/OP-TEE/optee_os/pull/5954 that may interrest you.
