### ISSUE TITLE
The dependecy with Yocto version

### ISSUE THREAD

**Issue by Ungsin** [OP-TEE/optee_os#5832]
Hi, 

We are planning to upgade the optee-os version from 3.8.0 to 3.20.0 with Yocto project 3.0.2.
Is there any dependency with Yocto project version?
The below is the detail information regarding Yocto project 3.0.2.

Yocto Project	[3.0.2](http://git.yoctoproject.org/cgit/cgit.cgi/poky/tag/?id=yocto-3.0.2)
Toolchain gcc-poky	    9.2
Kernel Ver         	    5.4
Userland 64/32bit	    64
U-Boot	                    2020.01

Also I'd like to know if there are minimum requirements for optee-os 3.20.0 version, such as the Linux Kernel Version or GCC version.
Thanks in advance,

Br,
Ungin.

**Comment by jenswi-linaro** [comment]
I don't see any obvious problems. I don't know which version of optee_client is used by Yocto. The version doesn't have to match what optee_os has, but if you have a choice it's good to keep it updated. I assume you're using a 5.4-stable kernel so that should be updated with critical fixes.

**Comment by jbech-linaro** [comment]
In addition to what Jens said, for 3.20 we used gcc 10.2, but IIRC it worked fine with older as well as newer versions as well. @jforissier just recently updated to use gcc 11.x by default, i.e., which will be used for 3.21.

OP-TEE is usually pretty independent on external tooling, it's more internal dependencies. I.e., optee_client, optee_test, optee_os etc, usually have to go hand in hand. I.e., taking optee_os 3.20 and optee_test 3.15 will most likely not work. So, when upgrading it should be done across all gits that the OP-TEE project consists of.

May I ask why you decided to go with gcc 9.2? It's a pretty old toolchain by now ([released 2019](https://gcc.gnu.org/gcc-9/))?

**Comment by Ungsin** [comment]
Hi Jesnswi and Jbech,
Thanks for your kind explanation.
