### ISSUE TITLE
Plan to enable PAN (Privileged Access Never)

### ISSUE THREAD

**Issue by shp4rk** [OP-TEE/optee_os#5837]
PAN is relatively old (compared to PAC/BTI/MTE) hardware-based security mitigation that would improve security under presence of malicious TAs. From what I understand, OP-TEE currently is not compatible with PAN, for example, it often does not discriminate accesses to kernel memory from accesses to user memory (the latter should be done with copy_to|from_user). Based on OP-TEE's history of adopting hardware-based security features, OP-TEE has been quite proactive when it comes to integrating new security features. Hence, I am curious why PAN has been an exception, and if you have plans to adopt PAN in the near future.

**Comment by jenswi-linaro** [comment]
Thanks for the reminder, I'm adding `PAN` to our list of things to look into.

**Comment by shp4rk** [comment]
When you think you will be available to work on PAN?

**Comment by jenswi-linaro** [comment]
I don't know. By the way, patches are welcome! :-)

**Comment by shp4rk** [comment]
I see. Thanks! Please let me know when you  guys pick up this topic 🙏

**Comment by shp4rk** [comment]
I was trying to design PAN support, but encountered an issue regarding crypto APIs. In particular, most of the crypto operations, which run inside the kernel space, freely accesses the user space buffers. For example:

https://github.com/OP-TEE/optee_os/blob/d690c8389bd24c64b77dbc264cdfa80ebecfc7f7/core/crypto/crypto.c#L105-L108

In the above code block, `update` will access the user-space buffer pointed by the `data`, hence ends up raising exception if PSTATE.PAN is set.

Viable workarounds that came up in my mind are:
1. to toggle PSTATE.PAN while performing crypto operation, or 
2. maintaining a bounce buffer within the kernel space

For the sake of security, I would way the latter is preferred, but it would increase the memory footprint a lot. I wanted to ask, which of the above approaches you would like, or if you have another recommendations.

Thanks

**Comment by etienne-lms** [comment]
As PAN is not supported by many platforms already supported by OP-TEE, I think these platforms will prefer conservative way allowing kernel land to still access userland memory, at least upon some build config switch directive.

As for option 1. or 2. for the platforms that could support PAN, I have not strong opinion. Could the userland buffers used specifically for these crypto operations be tagged so that priviledge access is permitted while PSTATE.PAN remains enable (for other non tagged buffers)? Or is PAN an all-or-none feature?

**Comment by jenswi-linaro** [comment]
I'd prefer option 1 for now, at least for hashing and symmetric ciphers. For asymmetric ciphers, we may want to use bounce buffers since they are going to be so small anyway.

**Comment by shp4rk** [comment]
Thank you for your feedbacks @etienne-lms and @jenswi-linaro.

Regarding the question on marking userland buffers to be able to be accessed from the kernel when PSTATE.PAN is set, currently I am not aware of such a mechanism. In that sense, I would say the PSTATE.PAN is close to all-or-none feature.

However, as a work-around, the kernel can safely access the content of the userland buffer by creating a kernel mapping to the physical memory that is occupied by the user buffer, although this might raise some alignment (by 4KiB) issues.
