### ISSUE TITLE
How to send FFA-calls from CA to ATF spmd_smc_handler with self-defined FUNCID

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5838]
Hi, expert

If I have defined a FFA smc_fid in ATF by myself and I want to use a CA in host OS to send a FFA call to ATF in terms of the specified FFA smc_fid. What should I do?

**Comment by jenswi-linaro** [comment]
FF-A SMC Function Identifiers are defined by the FF-A specification, not as an arbitrary extension. If you want to define a new SMC Function Identifier for some special purpose should probably look into adding it in the range of SiP or OEM Service Calls, see https://developer.arm.com/documentation/den0028/latest/.

**Comment by zzbios** [comment]
> FF-A SMC Function Identifiers are defined by the FF-A specification, not as an arbitrary extension. If you want to define a new SMC Function Identifier for some special purpose should probably look into adding it in the range of SiP or OEM Service Calls, see https://developer.arm.com/documentation/den0028/latest/.

Thanks a lot for your help：）
