### ISSUE TITLE
QEMU v8 complie error

### ISSUE THREAD

**Issue by ydonghyuk** [OP-TEE/optee_os#5839]
The following error occurred when building qemu v8 in Ubuntu 18.04 environment.
There seems to be a problem when compiling edk2, but I couldn't find a solution.
Is there anyone who can help?

(system)
Linux 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

(build log)
build.py...
 : error 7000: Failed to execute command
        make tbuild [/home3/user/work/qemu_230222_v8/edk2/Build/ArmVirtQemuKernel-AARCH64/RELEASE_GCC5/AARCH64/CryptoPkg/Library/OpensslLib/OpensslLibCrypto]

build.py...
 : error F002: Failed to build module
        /home3/user/work/qemu_230222_v8/edk2/CryptoPkg/Library/OpensslLib/OpensslLibCrypto.inf [AARCH64, GCC5, RELEASE]

- Failed -
Build end time: 04:24:55, Feb.22 2023
Build total time: 00:00:08

common.mk:433: recipe for target 'edk2-common' failed
make: *** [edk2-common] Error 1

**Comment by jforissier** [comment]
Hello @ydonghyuk,

Ubuntu 18.04 is old. Use 22.04 or 20.04 if you can, and see https://optee.readthedocs.io/en/latest/building/prerequisites.html.

**Comment by ydonghyuk** [comment]
@jforissier Thanks your support!

Oh.. I got it.
Can you tell me how to enable build in 18.04, or what version of optee can build in 18.04?

**Comment by jbech-linaro** [comment]
> @jforissier Thanks your support!
> 
> Oh.. I got it. Can you tell me how to enable build in 18.04, or what version of optee can build in 18.04?

You can give the 3.7 version a try. But here you have to follow [the instructions as they looked when 3.7 was the most recent version](https://optee.readthedocs.io/_/downloads/en/3.7.0/pdf/).

**Comment by jbech-linaro** [comment]
> You can give the 3.7 version a try. But here you have to follow [the instructions as they looked when 3.7 was the most recent version](https://optee.readthedocs.io/_/downloads/en/3.7.0/pdf/).

And [here](https://optee.readthedocs.io/en/3.7.0/) is the online version if you prefer that.

**Comment by ydonghyuk** [comment]
@jbech-linaro thanks for comment.

The version shown in CHANGELOG.md under 'optee_os'
```
# OP-TEE - version 3.20.0 (2023-01-20)
```
Are the versions you are talking about different?

If it is the same,
```
# OP-TEE - version 3.7.0 (2019-10-18)
```
Are you referring to version 3.7 which was released in 2019?

**Comment by ydonghyuk** [comment]
FYI, I tested version 3.17 by building it with Ubuntu 18.04.

**Comment by ChenaniahGSF** [comment]
because edk2 link some other repositories, when you repo sync edk2, these repoitories will not download, you need download manually and replace it.
download frome this link. 
https://github.com/tianocore/edk2/releases/tag/edk2-stable202111

**Comment by ydonghyuk** [comment]
@ChenaniahGSF Thanks for your comment.
Should I delete the entire edk2 directory and get a new one?

**Comment by ChenaniahGSF** [comment]
no need to delete the entire edk2.
for example,
/edk2/BaseTools/Source/C/BrotliCompress/brotli  maybe brotli is a empty floder.
download
[submodule-BaseTools-Source-C-BrotliCompress-brotli.zip](https://github.com/tianocore/edk2/releases/download/edk2-stable202111/submodule-BaseTools-Source-C-BrotliCompress-brotli.zip)
unzip brotli.zip, and replace brotli

**Comment by ChenaniahGSF** [comment]
maybe you will need
https://blog.csdn.net/u014734955/article/details/116465937

**Comment by ydonghyuk** [comment]
Thanks for the kind guide.
However, the edk2 downloaded through optee is not empty in the parts you said.

I temporarily solved it by reverting the commit related to toolchain version up under build.

"19b7b07 toolchain: update GCC to v11.3"
