### ISSUE TITLE
How to enable TA automatic vectorization option?

### ISSUE THREAD

**Issue by trriger** [OP-TEE/optee_os#5843]
I used version 3.16 of OP-TEE. 
I've recently been working on ways to make my own TA programs run faster. The compiler is gcc 10.3. Which makefile should be modified to enable the -O1-O2 or -O3 option.
Thank you!
![image](https://user-images.githubusercontent.com/55041272/220809777-b942595e-1d5c-4a26-9cdd-db6b72837393.png)

**Comment by jforissier** [comment]
Hello @trriger,

The easiest way is to define `CFLAGS_ta_arm64` (or `CFLAGS_ta_arm32` if your TA is 32-bit). You can set it on the make command line or in your TA Makefile (for example near the place you define BINARY=<TA uuid>).

**Comment by trriger** [comment]
@jforissier  Thank you for your assistance. It's useful. The TA runs much faster.
