### ISSUE TITLE
Minor thing about shared memory unregistration

### ISSUE THREAD

**Issue by ubisun** [OP-TEE/optee_os#5846]
Hello, I have a minor concern about shared memory unregistration.

When I check shared memory register/unregister logic, the shared memory objects aren't binding to session. OPTEE manages them with cookie to search proper shared memory object the CA wants, but it doesn't have problem in use scenario.

However, in case of unregistration, it relies on only cookie. Therefore, it can be unregistered by malicious request. (Of course, it is a rare case, because requires kernel privilege and should knows exact cookie value) I think that if only shared memory owner(did registration) can unregister it, this potential threat can be eliminated. Is there a plan to complement shared memory management scheme?

**Comment by jenswi-linaro** [comment]
I don't see how OP-TEE can be able to tell if it's the entity that did the registration that does the unregister request.
Adding some extra ID would not make a difference, it would only make it a larger cookie, perhaps harder to guess but if you have compromised the kernel you may not need to guess.
OP-TEE checks that it's not currently using the shared memory, but the rest is a normal world problem.

**Comment by ubisun** [comment]
Um, yes, you're right. kernel privileged attacker can abuse other session id, even if shared memory is bound to session. It is kind of authentication issue for REE requester. Thank you for your reply.
