### ISSUE TITLE
Ask a question about how to use GPROF.

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#5847]
I try to use GPROF to measure the performance of my TA.
https://optee.readthedocs.io/en/latest/debug/gprof.html#gprof
I refer to the link above, and I added to the Common.mk as follows and rebuilt the Optee-OS Build.
 -CFG_TA_GPROF_SUPOPOT = Y
 -CFG_ULIBS_MCOUNT = Y

For reference, I am working on Qemu V8.

And in TA's makefile, CFLAGS was added as shown below.
  -CFLAGS = -pg
  
-pg options have been added to confirm that the size of the TA result is different.
And when I run it, the following file was created under the /tmp directory.
 - /tmp/ftrace-[My-UUID].out

I was performed on the host PC as follows to check the profiling results.

$ aarch64-none-linux-gnu-gprof ftrace-dca51a37-0264-14e7-23b1-6ab7b4074a51.out > result.txt
-> aarch64-none-linux-gnu-gprof: ftrace-dca51a37-0264-14e7-23b1-6ab7b4074a51.out: not in executable format

I didn't know why this error occurs.

For reference, the contents of the out file are as follows.
$ cat aarch64-none-linux-gnu-gprof: ftrace-dca51a37-0264-14e7-23b1-6ab7b4074a51.out
TEE load address @ 0x83662000
region  0: va 0xc0064000 pa 0x00001000 size 0x061000 flags r-xs [0]
region  1: va 0xc00c5000 pa 0x00062000 size 0x049000 flags rw-s [0]
 [0] dca51a37-0264-14e7-23b1-6ab7b4074a51 @ 0xc0064000
Function graph for TA: dca51a37-0264-14e7-23b1-6ab7b4074a51 @ c0064000
     .224 us |     0x00000000c0068c94();
      .192 us |     0x00000000c0068c94();
      .192 us |     0x00000000c0068c94();
   328.816 us |    }
     1.456 us |    0x00000000c006cca4();
              |    0x00000000c006ed0c() {
      .704 us |     0x00000000c006ecd8();
    45.632 us |    }
  2861.952 us |   }
              |   0x00000000c0069c94() {
     1.600 us |    0x00000000c0068c94();
    51.200 us |   }
     6.608 us |   0x00000000c006bde0();
      .736 us |   0x00000000c006bde0();
      .240 us |   0x00000000c006bde0();
     3.552 us |   0x00000000c006bde0();
      .624 us |   0x00000000c006be5c();
  4780.480 us |  }
  4825.968 us | }
              | 0x00000000c007b214() {
              |  0x00000000c0065198() {
              |   0x00000000c0069c94() {
     2.928 us |    0x00000000c0068c94();
    55.872 us |   }
   381.344 us |  }
   434.400 us | }
              | 0x00000000c007b214() {
   485.664 us |  0x00000000c0065130();
              |  0x00000000c006506c() {
              |   0x00000000c006b804() {
     3.488 us |    0x00000000c006b1a4();
   165.152 us |   }
  1044.224 us |  }
  1856.832 us | }

If you know how to check GPROF, thank you for your answer.
BR,

**Comment by jforissier** [comment]
Hello @SangsubLim,

It looks like you are mixing up `gprof` and `ftrace`. Here is a sequence of commands that work for me (actually the call count works but the time profiling does not, I need to further investigate that).

```
optee/build$ make -j$(nproc) CFG_TA_GPROF_SUPPORT=y CFG_ULIBS_MCOUNT=y CFG_TA_MCOUNT=y QEMU_VIRTFS_AUTOMOUNT=y run
[...]
QEMU 7.2.0 monitor - type 'help' for more information
(qemu) c
[...]
Welcome to Buildroot, type root or test to login
buildroot login: root
# xtest 4002
[...]
# cp /tmp/gmon-cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.out /mnt/host/
(qemu) ^C
optee/build$ cd ..
optee$ aarch64-linux-gnu-gprof out-br/build/optee_test_ext-1.0/ta/crypt/out/cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.elf gmon-cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.out
```

**Comment by SangsubLim** [comment]
thank you
I'll try as you advised on QEMU v7.

**Comment by jforissier** [comment]
Re-opening this issue and changing its title a bit so it can serve as a support for investigating the difference between v7 and v8.
Here is a more meaningful run with `xtest 8101` (MBed TLS user space self-tests).
```
** QEMU_v8

optee_v8/build$ make -j$(nproc) CFG_TA_GPROF_SUPPORT=y CFG_ULIBS_MCOUNT=y CFG_TA_MCOUNT=y QEMU_VIRTFS_AUTOMOUNT=y run
# xtest 8101
D/TC:? 0 gprof_stop_pc_sampling:133 TA sampling stats: sample count=0 user time=18992618 cntfrq=62500000 rate=0
# cp /tmp/gmon-cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.out /mnt/host
optee_v8$ aarch64-linux-gnu-gprof out-br/build/optee_test_ext-1.0/ta/crypt/out/cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.elf gmon-cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.out | head -15
Flat profile:

Each sample counts as inf seconds.
 no time accumulated

  %   cumulative   self              self     total
 time   seconds   seconds    calls  Ts/call  Ts/call  name
  0.00      -nan     -nan   175005     -nan     -nan  memset
  0.00      -nan     -nan   167502     -nan     -nan  mbedtls_platform_zeroize
  0.00      -nan     -nan   140874     -nan     -nan  mpi_mul_hlp
  0.00      -nan     -nan   137720     -nan     -nan  memcpy
  0.00      -nan     -nan   120000     -nan     -nan  mbedtls_aes_crypt_ecb
  0.00      -nan     -nan    60000     -nan     -nan  mbedtls_aes_crypt_cbc
  0.00      -nan     -nan    60000     -nan     -nan  mbedtls_internal_aes_decrypt
  0.00      -nan     -nan    60000     -nan     -nan  mbedtls_internal_aes_encrypt

** QEMU

optee_v7/build$ make -j$(nproc) CFG_TA_GPROF_SUPPORT=y CFG_ULIBS_MCOUNT=y CFG_TA_MCOUNT=y QEMU_VIRTFS_AUTOMOUNT=y run
# xtest 8101
D/TC:? 0 gprof_stop_pc_sampling:133 TA sampling stats: sample count=82 user time=52040795 cntfrq=62500000 rate=98
# cp /tmp/gmon-cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.out /mnt/host
optee_v7$ arm-linux-gnueabihf-gprof out-br/build/optee_test_ext-1.0/ta/crypt/out/cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.elf gmon-cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.out | head -15
Flat profile:

Each sample counts as 0.0102041 seconds.
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name
 31.18      0.30     0.30    60000     0.00     0.01  mbedtls_internal_aes_decrypt
 17.20      0.46     0.16   140506     0.00     0.00  mpi_mul_hlp
 10.75      0.56     0.10    31267     0.00     0.00  mbedtls_internal_sha256_process
  7.53      0.63     0.07    60000     0.00     0.00  mbedtls_internal_aes_encrypt
  4.30      0.67     0.04   174837     0.00     0.00  memset
  3.23      0.70     0.03    15630     0.00     0.00  mbedtls_internal_sha1_process
  3.23      0.73     0.03                             __gnu_mcount_nc
  3.23      0.77     0.03                             mbedtls_pk_parse_public_key
  1.08      0.78     0.01   167500     0.00     0.00  mbedtls_platform_zeroize
  1.08      0.79     0.01   120000     0.00     0.00  mbedtls_aes_crypt_ecb
```

**Comment by jenswi-linaro** [comment]
We should consider generating secure interrupts instead if we need more reliable statistics.
