### ISSUE TITLE
Does raspi 3b trustzone even support interrupt?

### ISSUE THREAD

**Issue by Liaojinghui** [OP-TEE/optee_os#5849]
Hi,
I am currently working on a project that requires handling interrupts within the Trustzone on a Raspberry Pi 3B platform. Unfortunately, I'm facing an issue where the itr_core_handler function I added to the main.c file doesn't seem to get triggered. I'm now wondering if this is due to a lack of support for interrupts within the Trustzone on the Raspberry Pi 3B platform.

**Comment by gagachang** [comment]
Hi, it seems that the Raspberry Pi 3B does not have ARM GIC.

See the following references:
https://github.com/kata-containers/runtime/issues/848
https://www.kernel.org/doc/Documentation/devicetree/bindings/interrupt-controller/brcm%2Cbcm2835-armctrl-ic.txt
