### ISSUE TITLE
Adding mbedtls_x509write_crt_set_ext_key_usage to optee mbedTLS

### ISSUE THREAD

**Issue by PrithviAPai** [OP-TEE/optee_os#5851]
Some functions which are developed in mbedTLS main branch is NOT included in mdebTLS in OP-TEE. One such example is ```mbedtls_x509write_crt_set_ext_key_usage``` 
Is there any plans to add the same ?

**Comment by jforissier** [comment]
Hello @PrithviAPai,

You are raising an interesting question. The OP-TEE version of Mbed TLS is based on 2.28.1 and the function you need was introduced in 3.3.0. A major version bump usually means backwards incompatibilities. So if we update in optee_os it could cause  some inconvenience for TA developers (they would need to adapt their code). Maybe it's acceptable? We could also build two versions of the user space `libmbedtls.a` but it would be more maintenance work (keeping both up to date with upstream security patches etc.).

Opinions welcome.

**Comment by PrithviAPai** [comment]
Hi @jforissier,

okay do you suggest adding patches ? Wanted to check if it was possible to add the requirement in the upstream community. Thanks a lot for quick response.

**Comment by jforissier** [comment]
> okay do you suggest adding patches

If the patches are simple enough it could be a good compromise.

**Comment by PrithviAPai** [comment]
@jforissier Thanks a lot for your suggestion. Yes, the patch is simple

**Comment by PrithviAPai** [comment]
I will close the ticket as I got the answer
