### ISSUE TITLE
Question about running OP-TEE on DRAM physical address over 4GB with ARMv7

### ISSUE THREAD

**Issue by jesse-sc** [OP-TEE/optee_os#5855]
We are working on a SoC, which supports 64GB DRAM.
With ARMv8 AArch64, it is easy to set OP-TEE CFG_TZDRAM_START and CFG_SHMEM_START to address larger than 4GB. OP-TEE works fine on physical address larger than 4GB.
However, with ARMv7, CFG_TZDRAM_START and CFG_SHMEM_START cannot set to address larger than 4GB.
Is it possible to run OP-TEE on physical address over 4GB with ARMv7?
If yes, could you give us a hint or example to configure? Thanks.

BRs,
Jesse

**Comment by etienne-lms** [comment]
Is the issue is related to `paddr_t` being 32bit? `CFG_CORE_LARGE_PHYS_ADDR=y` should do the work.
As for the implementation, IMO it should allow 32bit OP-TEE to emmit 40bit IPA/PA access requests (in LPAE mode).

**Comment by jesse-sc** [comment]
Hi Etienne,

Thanks for replying. We have already set `CFG_CORE_LARGE_PHYS_ADDR=y` and make `paddr_t` to be 64-bit.

Because `CFG_TZDRAM_START` is 64-bit. In ARMv7, `__SIZEOF_LONG__` equals to 4 and `__SIZEOF_PADDR__` equals to 8.

The first problem is compile warning about `_register_memory_ul()`:
`core/include/mm/core_mmu.h:191:64: warning: unsigned conversion from 'long long int' to 'unsigned int' changes value from '68853694464' to '134217728' [-Woverflow]`

This warning results in the higher 32-bit address is truncated.

BTW, Linux can run on physical address larger than 4GB with ARMv7 using `pv_fixup()` function, which modifies page table entry with the offset of high physical address and low physical address. 
I guess OP-TEE may need some implementation like `pv_fixup()` to support running over 4GB physical address.  Is my understanding correct?

BRs,
Jesse

**Comment by jenswi-linaro** [comment]
I don't know what `pv_fixup()` does, but I doubt we need it in OP-TEE.

The `register_phys_mem_ul()` is a quick and dirty workaround when the input address and size are based on symbols generated in the link script. Perhaps it's possible to replace the problematic use of `register_phys_mem_ul()` with `register_phys_mem()`?

**Comment by jesse-sc** [comment]
Hi Jens,

Thanks for your explanation. Finally, I've found a way to make OP-TEE work on my SoC.

I still link OP-TEE code/data at address space below 4GB and use `register_ddr()` to declare 2 DRAM regions: one for below 4GB and the other for above 4GB.
This makes all the DRAM physical space can be mapped into OP-TEE.

BRs,
Jesse
