### ISSUE TITLE
OpenSSL EVP interface support?

### ISSUE THREAD

**Issue by wgzh1987** [OP-TEE/optee_os#5864]
Hi,

People who that use OpenSSL EVP interface for their application do not want rewrite the  crypto interface. Is it possible to support OpenSSL EVP interface in op-tee?  myabe some elements or a wrapper around the existing crypto libraries.

Thanks and best regards
Guangwei Zhou

**Comment by jenswi-linaro** [comment]
Do you mean to have the OpenSSL EVP interface available for TAs only? If so it looks like it should be quite easy to implement a wrapper for TEE Internal Core API.
