### ISSUE TITLE
Where do the secure datas store when both REE-FS and RPMB-FS set to 'y'

### ISSUE THREAD

**Issue by bqiu728** [OP-TEE/optee_os#5868]
Hi，
I’m just studying the secure storage part of OP-TEE.

It seems that when both REE-FS and RPMB-FS set to 'y'. There will be three parts of secure data:
1. `dirfile.db.hash` in RPMB which hold a hash representing the state of REE FS
2. meta data which stores in REE-FS
3. block data which stores in REE-FS

Is my understanding right ？
If it is， if there any risk to meet the requirement of GP? It seems that the meta data and block data can be destroyed by REE users 

thanks

**Comment by jenswi-linaro** [comment]
We can't guarantee data availability, only integrity, and confidentiality. Only integrity and confidentiality are required by GP.
