### ISSUE TITLE
xtest 1008 case fail with TEEC_ERROR_OUT_OF_MEMORY sometimes

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5874]
FAIL_LOG
#./xtest 1008&
[2] 12436
Test ID: 1008
Run test suite with level=0

TEE test application started over default TEE instance
######################################################
\#
\# regression
\#
######################################################

* regression_1008 TEE internal client API
o regression_1008.1 Invoke command
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x9
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x9
ta_entry_client: enter
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x9
  regression_1008.1 OK
o regression_1008.2 Invoke command with timeout
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x9
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x9
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x9
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x9
ta_entry_wait: waiting 2000
  regression_1008.2 OK
o regression_1008.3 Create session fail
n = 0
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x9
E/TC:??? 0 tee_ta_open_session:785 Failed. Return error 0xffff0000
  regression_1008.3 OK
o regression_1008.4 Load corrupt TA
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
/root/mjq2/optee_test/host/xtest/regression_1000.c:685: res has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0xffff000f = TEEC_ERROR_SECURITY
/root/mjq2/optee_test/host/xtest/regression_1000.c:714: load_corrupt_ta(c, __builtin_offsetof (struct shdr, img_size), 1) has an unexpected value: 0x0 = false, expected 0x1 = true
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
/root/mjq2/optee_test/host/xtest/regression_1000.c:685: res has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0xffff000f = TEEC_ERROR_SECURITY
/root/mjq2/optee_test/host/xtest/regression_1000.c:726: load_corrupt_ta(c, 3000, 1) has an unexpected value: 0x0 = false, expected 0x1 = true
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
/root/mjq2/optee_test/host/xtest/regression_1000.c:685: res has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0xffff000f = TEEC_ERROR_SECURITY
/root/mjq2/optee_test/host/xtest/regression_1000.c:727: load_corrupt_ta(c, 8000, 1) has an unexpected value: 0x0 = false, expected 0x1 = true
  regression_1008.4 FAILED
  regression_1008 FAILED
+-----------------------------------------------------
Result of testsuite regression filtered by "1008":
regression_1008.4 FAILED first error at /root/mjq2/optee_test/host/xtest/regression_1000.c:685
regression_1008 FAILED
+-----------------------------------------------------
75 subtests of which 6 failed
1 test case of which 1 failed
100 test cases were skipped
TEE test application done!

SUCCESS_LOG
* regression_1008 TEE internal client API
o regression_1008.1 Invoke command
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
ta_entry_client: enter
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
  regression_1008.1 OK
o regression_1008.2 Invoke command with timeout
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
ta_entry_wait: waiting 2000
  regression_1008.2 OK
o regression_1008.3 Create session fail
n = 0
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
E/TC:??? 0 tee_ta_open_session:785 Failed. Return error 0xffff0000
  regression_1008.3 OK
o regression_1008.4 Load corrupt TA
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
E/TC:032 0 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x5
  regression_1008.4 OK
  regression_1008 OK

FAIL is difficult to repeat, but it does happen, is there any methods of debugging?

**Comment by zzbios** [comment]
I increased the CFG_CORE_HEAP_SIZE and the CFG_NUM_THREADS, which seems to reduce the probability of the problem occurring. Do these two configurations have anything to do with the problem？

**Comment by jenswi-linaro** [comment]
`CFG_CORE_HEAP_SIZE` could affect this.

**Comment by zzbios** [comment]
> `CFG_CORE_HEAP_SIZE` could affect this.

This does not seem to be the root cause of the problem. Is there any way to locate it further？

**Comment by jenswi-linaro** [comment]
A similar problem is discussed at https://lists.trustedfirmware.org/archives/list/op-tee@lists.trustedfirmware.org/thread/U4OOBBBAONJIPTZRLGWLMOCCJ4INR3BL/
