### ISSUE TITLE
Watchdog reset leads to CPU stall / vector catch

### ISSUE THREAD

**Issue by coveritytest** [OP-TEE/optee_os#5880]
I'm using a STM32MP1 board with TF-A v2.4-stm32mp-r2.2 and OP-TEE OS v3.12.0-stm32mp-r2.2. In OP-TEE a `while(1);` leads to an IWDG2 watchdog reset, the system comes up correctly after this. In U-Boot and Linux Kernel the watchdog reset leads to a CPU stall. Using a debugger I can see an SVC to secure mode, so apparently something's wrong with the secure call handling in OP-TEE OS. Any ideas how to debug this further? This is the register view wenn the watchdog hardware triggers the reset: 
![image](https://user-images.githubusercontent.com/7345039/224727479-3ba59b25-d698-4435-b505-709f7691ed08.png)

**Comment by etienne-lms** [comment]
Hi @coveritytest. Sorry but these TF-A and OP-TEE OS references are not maintained in OP-TEE repositories.

**Comment by coveritytest** [comment]
Okay, seems to be a problem in the ST code regarding `wait_cpu_reset()`.
