### ISSUE TITLE
P11 C_SeedRandom always returns CKR_OK when it doesn't

### ISSUE THREAD

**Issue by nvanduyn** [OP-TEE/optee_os#5883]
https://github.com/OP-TEE/optee_os/blob/442c670a2b565173306a89ad028ad33bac5cca56/core/crypto/rng_hw.c#L12

The C_SeedRandom function will always return CKR_OK but it appears that it isn't actually doing anything. Instead an empty function is defined. This gives the impression that the function is correctly seeding entropy into OP-TEE.

**Comment by etienne-lms** [comment]
`C_SeedRandom()` invokes command `PKCS11_CMD_SEED_RANDOM` in pkcs11 TA that invokes command `PTA_SYSTEM_ADD_RNG_ENTROPY` in OP-TEE core system PTA that in turn calls `crypto_rng_add_event()` which is OP-TEE core internal API function to seed the random number generator, whatever it is. When `CFG_WITH_SOFTWARE_RNG=n` we expect HW RNG don't need any seed so it is discarded.
