### ISSUE TITLE
OpenSSL support in OP-TEE

### ISSUE THREAD

**Issue by PrithviAPai** [OP-TEE/optee_os#5884]
Hi Team,

Is there any plans of OPTEE community to have OpenSSL just like mbedTLS in optee_os ? 
If not, is there any way users can enable ? 

Thanks

**Comment by PrithviAPai** [comment]
@jforissier can you please help

**Comment by jforissier** [comment]
Hi @PrithviAPai,

At the moment there is no plan on our side (Linaro) to implement OpenSSL support. Perhaps it could be done outside of OP-TEE, since I believe only public APIs are needed (the TEE Internal Core API in libutee and of course the "C library": libutils)?

Related issue: #5864.
