### ISSUE TITLE
optee load_address configuration 

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5885]
Hi, experts,
In our current environment, we use ATF to load op-tee.pkg, op-tee.pkg is packed by ATF using sp_tool on tee-pager_v2.bin.
The load_address of optee.pkg is defined in the properties of vm node in m1_spmc_optee_sp_manifest.dts, 
but since there is an address offset of 0x4000 for entry-point, CFG_TZDRAM_START should add 0x4000 to this address. 

So, should CFG_TZDRAM_SIZE add the forward offset 0x4000 from mem_size in the properties of vm node?

**Comment by jenswi-linaro** [comment]
Yes, because that's where the OP-TEE binary is loaded.

**Comment by zzbios** [comment]
> Yes, because that's where the OP-TEE binary is loaded.

Thanks. By the way, does optee currently support 64-bit load_address?
