### ISSUE TITLE
xtest case run fail after reboot

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5893]
Hi, experts,
We are test stability for xtest.
After firmware image is burned for the first time, all test cases run success. 
After server reboot, a large number of case failed.

typical case fail like this:
o regression_1008.4 Load corrupt TA
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x2
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x2
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x2
/root/mjq2/optee_test/host/xtest/regression_1000.c:685: res has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0xffff000f = TEEC_ERROR_SECURITY
/root/mjq2/optee_test/host/xtest/regression_1000.c:714: load_corrupt_ta(c, __builtin_offsetof (struct shdr, img_size), 1) has an unexpected value: 0x0 = false, expected 0x1 = true
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x2
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x2
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x2
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x2
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x2
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x2
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x4
/root/mjq2/optee_test/host/xtest/regression_1000.c:685: res has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0xffff000f = TEEC_ERROR_SECURITY
/root/mjq2/optee_test/host/xtest/regression_1000.c:726: load_corrupt_ta(c, 3000, 1) has an unexpected value: 0x0 = false, expected 0x1 = true
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x2
E/TC:042 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x4
/root/mjq2/optee_test/host/xtest/regression_1000.c:685: res has an unexpected value: 0xffff000c = TEEC_ERROR_OUT_OF_MEMORY, expected 0xffff000f = TEEC_ERROR_SECURITY
/root/mjq2/optee_test/host/xtest/regression_1000.c:727: load_corrupt_ta(c, 8000, 1) has an unexpected value: 0x0 = false, expected 0x1 = true
  regression_1008.4 FAILED
  regression_1008 FAILED

o regression_4002.10 MAC case 9 algo 0x30000004
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x10
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x10
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x10
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x10
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x10
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x10
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x10
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x10
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x12
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x10
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x12
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x10
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x12
  regression_4002.10 OK
o regression_4002.11 MAC case 10 algo 0x30000005
E/TC:049 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x10
/root/mjq2/optee_test/host/xtest/regression_4000.c:225: ret_orig has an unexpected value: 0x1 = TEEC_ORIGIN_API, expected 0x4 = TEEC_ORIGIN_TRUSTED_APP
/root/mjq2/optee_test/host/xtest/regression_4000.c:1305: ta_crypt_cmd_mac_update(c, &session, op1, mac_cases[n].in + offs, mac_cases[n].in_incr) has an unexpected value: 0xffff0000 = TEEC_ERROR_GENERIC, expected 0x0 = TEEC_SUCCESS
  regression_4002.11 FAILED
  regression_4002 FAILED

xtest log:
[optee_xtest_log.txt](https://github.com/OP-TEE/optee_os/files/10987173/optee_xtest_log.txt)
optee config:
[conf.txt](https://github.com/OP-TEE/optee_os/files/10987370/conf.txt)

It is worth noting that xtest runs stably after reboot on another server with the same configuration.

**Comment by jenswi-linaro** [comment]
This is out of memory errors somewhere in the chain, typically in SPMC or OP-TEE. My guess is that some resource is very close to being exhausted and with a bit more fragmentation that's just too much. Fragmentation can occur in the heap, but also with the physical pages. In both cases, limits are too tight for reliable operation.

**Comment by zzbios** [comment]
> This is out of memory errors somewhere in the chain, typically in SPMC or OP-TEE. My guess is that some resource is very close to being exhausted and with a bit more fragmentation that's just too much. Fragmentation can occur in the heap, but also with the physical pages. In both cases, limits are too tight for reliable operation.

Hello, it should be noted that our system has 128 cores, do you know what memory configuration is related to the number of cores? So far, we've increased the optee heap size and the spmc heap size, but this doesn't seem to be working.
