### ISSUE TITLE
crypto api - driver selection and HW keys

### ISSUE THREAD

**Issue by lm-aml** [OP-TEE/optee_os#5896]
Hi,

There are some use cases I have in mind:
1.1/  Some platforms support doing AES or other crypto operations with a key accessible to the HW, but not the host CPU. Somewhat similar to #2445.

1.2/ Also, the HW key in (1.1) may be referenced by a key slot index instead of the actual raw key data. 

2/ There could be various reasons to choose different crypto implementations, like performance differences depending on the data length.  SW may be faster than HW for small data lengths, or only HW supports the HW key.

The problem is that limited info is passed from the TA to core with the TEE Internal Core API (TEE_AllocateOperation, TEE_AEInit, etc.).

I would like some suggestions on how to support the above use cases.  I would like to avoid adding a PTA like in #2445.  Perhaps by extending the TEE Internal Core API to pass in more info about the Operation and key Object down to the crypto implementation/driver.

(1.1) and (2) could be solved if the TA could specify the driver name or some flags when calling TEE_AllocateOperation. Though, TEE_AllocateOperation can't be changed due to GlobalPlatform spec.  If this info could be passed in, then a specific drvcrypt or crypto implementation could be chosen.
This would be similar to the Linux kernel's crypto_alloc_skcipher.  It has a parameter, alg_name, which can be the algo name or a specific driver name (https://docs.kernel.org/crypto/api-skcipher.html#c.crypto_alloc_skcipher).  
Another idea is to add a new TEE_SetOperationUsage to let the TA set the Operation's usage flags, and add new flag to indicate TEE_USAGE_HW_CRYPTO or TEE_USAGE_KEY_SLOT, etc.

For (1.2) is there a way to indicate to the crypto implementation that the key passed in is a key slot, or some other info about the key?  Right now it only gets the key bytes and length, which must match the crypto algo requirements. Perhaps use TEE_RestrictObjectUsage1(key_handle, TEE_USAGE_...) with a new usage flag, and let the usage flag be passed down to the crypto implementation/driver.
I also saw RSEC #4807 changes the key object, so that might help for (1.2).

**Comment by jenswi-linaro** [comment]
The HW key is per definition only accessible by hardware, so any reference by software must be via an index or such. This sounds like a new type of key, for instance, `TEE_TYPE_HW_AES`.

For (2) different implementations could be selected at runtime depending on the data length in each call. This should still be abstracted from the TAs.
