### ISSUE TITLE
Unable to generate CSR for my RSA keys

### ISSUE THREAD

**Issue by satishkrishna687** [OP-TEE/optee_os#5897]
So, I'm running optee: revision 3.20 (2be3770e) on qemu v7 that I built from https://optee.readthedocs.io/en/latest/building/devices/qemu.html
I have added extra packages in the common.mk file under /optee-qemu/build/ 
BR2_PACKAGE_LIBP11 ?= y
BR2_PACKAGE_PKCS11_HELPER ?= y
BR2_PACKAGE_OPENSSL_FORCE_LIBOPENSSL ?= y
BR2_PACKAGE_LIBOPENSSL_BIN ?= y
BR2_PACKAGE_OPENSSH ?= y
BR2_PACKAGE_OPENSSH_CLIENT ?= y
BR2_PACKAGE_OPENSSH_SERVER ?= y
BR2_PACKAGE_OPENSSH_KEY_UTILS ?= y
BR2_PACKAGE_STRONGSWAN ?= y

so I'm successfull in generating RSA Key but when I try to generate a csr using openssl(1.1.1q) engine api, 
<a href="https://freeimage.host/i/HhfllPj"><img src="https://iili.io/HhfllPj.md.png" alt="HhfllPj.md.png" border="0"></a>

it always, throws me an error.
<a href="https://freeimage.host/i/HhflJFR"><img src="https://iili.io/HhflJFR.md.png" alt="HhflJFR.md.png" border="0"></a>

I have tried with giving it URI as well. I got it to generate a CSR.
Can anyone direct me as to how to get the CSR for the RSA keys inside.

I tried generating my private key, csr and get the certicate signed from CA from outside and import the private key inside the slot after everthing. But strongswan fails to load this privatekey. Where as key that is directly generated inside the OP-TEE slot gets loaded.
                  Please guide me where I can generate the CSR and some steps to do would be very helpful. 
I'm noobie in all this any help is greatly appreciated.

**Comment by jforissier** [comment]
Hello @satishkrishna687,

Coincidentally, I have just been through a similar process about a week ago. I'm not sure exactly what is wrong in your commands or in your config (probably the latter), but here is a script which does work for sure. Tested on QEMUv8, but the platform shouldn't matter much:

```sh
set -e
alias p11="pkcs11-tool --module /usr/lib/libckteec.so.0"
p11 --token-label mytoken --read-object --type pubkey \
    --label mykey >/dev/null 2>&1 || {
  p11 --init-token --so-pin 12345678 --label mytoken;
  p11 --token-label mytoken --so-pin 12345678 --init-pin --pin 12345;
  p11 --token-label mytoken --pin 12345 --keypairgen \
      --key-type rsa:2048 --label mykey;
}
cat <<_EOF_ >csr.cnf
[req]
distinguished_name = req_distinguished_name
prompt = no
[req_distinguished_name]
C = UK
ST = Cambridgeshire
L = Cambridge
O = Linaro, Ltd.
OU = R&D
CN = .
_EOF_
cat <<_EOF_ | openssl
engine dynamic -pre SO_PATH:/usr/lib/engines-1.1/pkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/usr/lib/libckteec.so.0
req -new -config csr.cnf -engine pkcs11 -key pkcs11:object=mykey;type=private?pin-value=12345 -keyform engine -out p.csr
_EOF_
cat p.csr
```

As you can see, I am not relying on the OpenSSL configuration file because I needed to use PKCS#11 temporarily in a script hence the `engine dynamic` line. But in case it helps, I am also using the following configuration for OpenSSL v3 (which doesn't accept piping lines into the `openssl` command anymore):

```sh
...
cat <<_EOF_ >openssl-pkcs11.conf
openssl_conf = openssl_init

[openssl_init]
engines = engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
dynamic_path = /usr/lib/engines-3/pkcs11.so
MODULE_PATH = /usr/lib/libckteec.so.0
_EOF_
OPENSSL_CONF=openssl-pkcs11.conf openssl req ... # same command as above
```

Hope this helps!

**Comment by satishkrishna687** [comment]
@jforissier thanks a ton. Dynamically loading the engine was the solution. For some reason even If I don't set the engine configuration in openssl.conf it still says pkcs11 engine(available) 😆.
