### ISSUE TITLE
How to use PAC instructions in OPTEE_OS

### ISSUE THREAD

**Issue by erhade** [OP-TEE/optee_os#5899]
Hi,

I attempted to use PAC instructions, such as `pacia`, to sign in the Secure World kernel. However, calling `pacia` did not effectively and the system seems to ignore this instruction.

![2023-03-21_00-46](https://user-images.githubusercontent.com/49524292/226410422-4dfee68d-b330-4f9f-9107-bb419bbea21d.png)

I then tried enabling the `CFG_CORE_PAUTH` option: https://github.com/OP-TEE/optee_os/blob/1478437e65c44163f7c96f8a4c5d1532a9312bc3/mk/config.mk#L954, but it caused the system to become unresponsive and fail to run. The system boot stops at the place shown in the figure below: 

![2023-03-21_00-34](https://user-images.githubusercontent.com/49524292/226407817-dbb0aa90-d704-4f91-9c6f-5e7c21528353.png)

Nevertheless, I can use the `pacia` directive without issue in the client application.

![2023-03-21_00-46_1](https://user-images.githubusercontent.com/49524292/226410507-6e875aad-1d5b-4920-aa13-61298c15bbf8.png)

Thanks!

**Comment by jenswi-linaro** [comment]
Try to build everything `make PAUTH=y all -j8` instead to be sure to have TF-A built with `CTX_INCLUDE_PAUTH_REGS=1`. With that, you should be able to observe OP-TEE making use of pointer authentication.
