### ISSUE TITLE
How to compile Optee for i.mx6

### ISSUE THREAD

**Issue by Liaojinghui** [OP-TEE/optee_os#5901]
Hi,

Does anyone know how to compile optee for i.mx6 board? The document says optee support i.mx6 board, but there is no manual for that.

**Comment by jforissier** [comment]
Hi @Liaojinghui,

In general to build OP-TEE you need to install a few [prerequisites](https://optee.readthedocs.io/en/latest/building/prerequisites.html), then simply run `make PLATFORM=<platform>[-<platform_flavor>]`. For i.MX6 boards, `<platform>` is `imx` and `<platform_flavor>` can be chosen in quite a big list:
```
$ git grep mx6 core/arch/arm/plat-imx/conf.mk | head -37
core/arch/arm/plat-imx/conf.mk:PLATFORM_FLAVOR ?= mx6ulevk
core/arch/arm/plat-imx/conf.mk:mx6ul-flavorlist = \
core/arch/arm/plat-imx/conf.mk:	mx6ulevk \
core/arch/arm/plat-imx/conf.mk:	mx6ul9x9evk \
core/arch/arm/plat-imx/conf.mk:	mx6ulccimx6ulsbcpro \
core/arch/arm/plat-imx/conf.mk:	mx6ulccbv2 \
core/arch/arm/plat-imx/conf.mk:mx6ull-flavorlist = \
core/arch/arm/plat-imx/conf.mk:	mx6ullevk \
core/arch/arm/plat-imx/conf.mk:	mx6ulzevk \
core/arch/arm/plat-imx/conf.mk:mx6q-flavorlist = \
core/arch/arm/plat-imx/conf.mk:	mx6qsabrelite \
core/arch/arm/plat-imx/conf.mk:	mx6qsabreauto \
core/arch/arm/plat-imx/conf.mk:	mx6qsabresd \
core/arch/arm/plat-imx/conf.mk:	mx6qhmbedge \
core/arch/arm/plat-imx/conf.mk:	mx6qapalis \
core/arch/arm/plat-imx/conf.mk:mx6qp-flavorlist = \
core/arch/arm/plat-imx/conf.mk:	mx6qpsabreauto \
core/arch/arm/plat-imx/conf.mk:	mx6qpsabresd \
core/arch/arm/plat-imx/conf.mk:mx6sl-flavorlist = \
core/arch/arm/plat-imx/conf.mk:	mx6slevk
core/arch/arm/plat-imx/conf.mk:mx6sll-flavorlist = \
core/arch/arm/plat-imx/conf.mk:	mx6sllevk
core/arch/arm/plat-imx/conf.mk:mx6sx-flavorlist = \
core/arch/arm/plat-imx/conf.mk:	mx6sxsabreauto \
core/arch/arm/plat-imx/conf.mk:	mx6sxsabresd \
core/arch/arm/plat-imx/conf.mk:	mx6sxudooneofull \
core/arch/arm/plat-imx/conf.mk:mx6d-flavorlist = \
core/arch/arm/plat-imx/conf.mk:	mx6dhmbedge \
core/arch/arm/plat-imx/conf.mk:	mx6dapalis \
core/arch/arm/plat-imx/conf.mk:mx6dl-flavorlist = \
core/arch/arm/plat-imx/conf.mk:	mx6dlsabreauto \
core/arch/arm/plat-imx/conf.mk:	mx6dlsabresd \
core/arch/arm/plat-imx/conf.mk:	mx6dlhmbedge \
core/arch/arm/plat-imx/conf.mk:mx6s-flavorlist = \
core/arch/arm/plat-imx/conf.mk:	mx6shmbedge \
core/arch/arm/plat-imx/conf.mk:	mx6solosabresd \
core/arch/arm/plat-imx/conf.mk:	mx6solosabreauto \
```

That being said, you obviously need more that just OP-TEE OS to run use cases, so please refer to https://optee.readthedocs.io/en/latest/ for information on the build and development environment (manifest.git, build.git).

For more specific i.MX information, ask here and I'm sure the maintainers will chime in!

Hope this helps.

**Comment by Liaojinghui** [comment]
@jforissier , thank you very much for answering my question. May ask you if there is any instruction to build optee for mx6? I understand that the optee-core has mx6 support. However, there is no build manual for it and the  `makefile` for imx dose not support mx6, it is imx8 by default. And i have dug into the project synced from the manifest, and there is only mkimage for imx8, only `uboot-imx8.conf` in the build/kconfigs folder https://github.com/OP-TEE/build/tree/master/kconfigs. 

![image](https://user-images.githubusercontent.com/10189511/226619500-b7f137d0-dc50-40da-9867-48c342cd15a4.png)

![image](https://user-images.githubusercontent.com/10189511/226619585-40cf6f16-7510-4ed3-9fb1-6ce994a3bd75.png)

**Comment by jforissier** [comment]
@Liaojinghui you are right, there is no i.MX6 support in the upstream OP-TEE development environment. I personally do not use this platform so I'm afraid I can't provide more help.

**Comment by Liaojinghui** [comment]
@jforissier  thank you very much for your patience and kind help.
