### ISSUE TITLE
Minor: why try to read residue bytes before closing TA binary?

### ISSUE THREAD

**Issue by shp4rk** [OP-TEE/optee_os#5902]
In the function `ldelf_syscall_close_bin`, it tries to read the residue bytes to NULL, which I am not sure why it's necessary:
https://github.com/OP-TEE/optee_os/blob/2a0d456fa09fba195ab615420d510a041398dbe5/core/kernel/ldelf_syscalls.c#L208-L210

Digging down, I found that the code was there since the function was implemented for the first time (https://github.com/OP-TEE/optee_os/commit/0b414d3f912828b02fc37d2489a9b8f8907a7ca4 as part of system PTA).

I am curious why it has to read the residue bytes to NULL destination. Could you please share the rationale behind that logic, please?

**Comment by jenswi-linaro** [comment]
It's there to let `ree_fs_ta_read()` do the final check when `handle->offs == handle->nw_ta_size`.
This is only needed when `CFG_REE_FS_TA_BUFFERED=n` and `CFG_REE_FS_TA=y`, and otherwise harmless.

**Comment by shp4rk** [comment]
Thank you for your clarification!
