### ISSUE TITLE
OP-TEE core exception with TA memstats

### ISSUE THREAD

**Issue by weizhaojiang** [OP-TEE/optee_os#5905]
General guidance when creating issues:
I enable `CFG_TA_STATS ?= y` to have ta memory dump. It can work in most cases expect below one:
Shell1 execute:
console# xtest 6016
Shell2 execute:
console# xtest --stats --ta

optee core will data abort with below log:
[   35.607698]<6> (6)[2254:xtest]E/TC:6 2 Core data-abort at address 0xffffffffffffff80 (translation fault)

The issue can be reproduced in latest version of master.

I debugged on it and found happens when core try to switch the user ta to its user context. However, the usr_stack from context is 0 – this is a fatal error. After that it does a  ROUNDUP() and get the fake stack pointer – 0xffffffffffffff80(64bits). Data abort happens when core access the user ta's stack.

Any suggestion to figure out why the stack pointer will be changed to 0 in this case?

**Comment by weizhaojiang** [comment]
With below patch, the crash will be gone. But still like to figure out why it gets 0 stack_pointer.

`@@ -151,11 +151,30 @@ static TEE_Result user_ta_enter(struct ts_session *session,
                        goto out;
        }

+       /* Make room for usr_params at top of stack */
+       usr_stack = utc->uctx.stack_ptr;
+       DMSG("!!utc->uctx.stack_ptr = 0x%x", utc->uctx.stack_ptr);
+       if (usr_stack == 0) {
+               res = TEE_ERROR_CORRUPT_OBJECT;
+               DMSG("!!!!!!session = 0x%x", session);
+               DMSG("!!!!!!utc = 0x%x", utc);
+               DMSG("!!!!!!usr_stack == 0");
+               DMSG("!!!!!!utc->uctx.is_initializing = %d", utc->uctx.is_initializing);
+               DMSG("!!!!!!utc->uctx.is_32bit = %d", utc->uctx.is_32bit);
+               DMSG("!!!!!!utc->uctx.ts_ctx = 0x%x", utc->uctx.ts_ctx);
+               DMSG("!!!!!!utc->uctx.dl_entry_func = 0x%x", utc->uctx.dl_entry_func);
+               DMSG("!!!!!!utc->uctx.load_addr = 0x%x", utc->uctx.load_addr);
+               struct tee_ta_ctx *ta_ctx = &utc->ta_ctx;
+               DMSG("!!!!!!ta_ctx->panicked = %d", ta_ctx->panicked);
+               DMSG("!!!!!!ta_ctx->ref_count = %d", ta_ctx->ref_count);
+               DMSG("!!!!!!ta_ctx->panic_code = 0x%x", ta_ctx->panic_code);
+               DMSG("!!!!!!ta_ctx::uuid: = 0x%08x", ta_ctx->ts_ctx.uuid.timeLow);
+               goto out;
+       }
+
        /* Switch to user ctx */
        ts_push_current_session(session);

-       /* Make room for usr_params at top of stack */
-       usr_stack = utc->uctx.stack_ptr;
`

Below is the log I capture:
`D/TC:? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA b689f2a7-8adf-477a-9f99-32e90c0ad0a2
D/TC:? 0 ldelf_load_ldelf:66 !!stack_addr = 0x102000
D/TC:? 0 ldelf_load_ldelf:96 !!uctx->stack_ptr = 0x0
D/TC:? 0 ldelf_load_ldelf:97 !!uctx->ldelf_stack_ptr = 0x104000
D/TC:? 0 ldelf_load_ldelf:98 !!uctx->entry_func = 0x104000
D/TC:? 0 ldelf_load_ldelf:99 !!uctx->ts_ctx = 0x8cc0f4e4
D/TC:? 0 ldelf_load_ldelf:100 ldelf load address 0x104000
D/LD:  ldelf:135 Loading TS b689f2a7-8adf-477a-9f99-32e90c0ad0a2
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF b689f2a7-8adf-477a-9f99-32e90c0ad0a2 (early TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF b689f2a7-8adf-477a-9f99-32e90c0ad0a2 (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF b689f2a7-8adf-477a-9f99-32e90c0ad0a2 (REE)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0
D/TC:? 1 tee_ta_init_session_with_context:624 Re-open TA d96a5b40-e2c7-b1af-8794-1002a5d5c61b
D/TC:? 1 get_user_ta_stats:171 tee_ta_dump_stats return: 0xffff0010
D/TC:? 1 user_ta_enter:156 !!utc->uctx.stack_ptr = 0x0
D/TC:? 1 user_ta_enter:159 !!!!!!session = 0x8cc0f520
D/TC:? 1 user_ta_enter:160 !!!!!!utc = 0x8cc0f368
D/TC:? 1 user_ta_enter:161 !!!!!!usr_stack == 0
D/TC:? 1 user_ta_enter:162 !!!!!!utc->uctx.is_initializing = 1
D/TC:? 1 user_ta_enter:163 !!!!!!utc->uctx.is_32bit = 1
D/TC:? 1 user_ta_enter:164 !!!!!!utc->uctx.ts_ctx = 0x8cc0f4e4
D/TC:? 1 user_ta_enter:165 !!!!!!utc->uctx.dl_entry_func = 0x0
D/TC:? 1 user_ta_enter:166 !!!!!!utc->uctx.load_addr = 0x0
D/TC:? 1 user_ta_enter:168 !!!!!!ta_ctx->panicked = 0
D/TC:? 1 user_ta_enter:169 !!!!!!ta_ctx->ref_count = 1
D/TC:? 1 user_ta_enter:170 !!!!!!ta_ctx->panic_code = 0x0
D/TC:? 1 user_ta_enter:171 !!!!!!ta_ctx::uuid: = 0xb689f2a7
D/TC:? 1 tee_ta_close_session:529 csess 0x8cc0e738 id 2
D/TC:? 1 tee_ta_close_session:548 Destroy session
`

**Comment by weizhaojiang** [comment]
attached tee log...

I found that the 0 stack pointer happen when below log appears:
D/TC:? 1 tee_ta_init_session_with_context:624 Re-open TA d96a5b40-e2c7-b1af-8794-1002a5d5c61b
[Uploading op_tee_log.txt…]()

**Comment by weizhaojiang** [comment]
Thanks for helping this issue out. Yeah, the root cause of this issue is the user TA doesn't get initialization completed.

**Comment by jenswi-linaro** [comment]
That's great. Would you like to propose a fix in a pull request?
