### ISSUE TITLE
(qemu) qemu-system-aarch64: Could not find ROM image 'bl1.bin'

### ISSUE THREAD

**Issue by feiyiban** [OP-TEE/optee_os#5906]
excute “make -f qemu_v8.mk run-only” 
result：
rch64-softmmu/qemu-system-aarch64 \
	-nographic \
	-serial tcp:localhost:54320 -serial tcp:localhost:54321 \
	-smp 2 \
	-s -S -machine virt,secure=on -cpu cortex-a57 \
	-d unimp -semihosting-config enable,target=native \
	-m 1057 \
	-bios bl1.bin \
	-initrd rootfs.cpio.gz \
	-kernel Image -no-acpi \
	-append 'console=ttyAMA0,38400 keep_bootcon root=/dev/vda2' \
	-object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,max-bytes=1024,period=1000 -netdev user,id=vmnic -device virtio-net-device,netdev=vmnic
QEMU 3.0.93 monitor - type 'help' for more information
(qemu) qemu-system-aarch64: Could not find ROM image 'bl1.bin'
make: *** [Makefile:198: run-only] Error 1

”

**Comment by feiyiban** [comment]
env ubuntu20.4 qemu_v8 branch 3.8

**Comment by jenswi-linaro** [comment]
Did you ever run `make all`?

**Comment by feiyiban** [comment]
fix
