### ISSUE TITLE
TA comunicate with TA using shared memory

### ISSUE THREAD

**Issue by zz-fz-john** [OP-TEE/optee_os#5910]
Can a TA fetch data  that another TA stored from shared memory ?

**Comment by etienne-lms** [comment]
A client app (non-secure) can share a piece of memory with 2 TAs it invokes. In that case, the 2 TAs can access the very same memory area. Note that such memory is map in the TA space only for the time being of the TA invocation (e.g. InvokeCommand API) and unmaped once TA has completed the invocation.

When a TA invokes another TA and wants to share a buffer from its secure memory, then OP-TEE core creates a temporary (secure memory) buffer specifically for that invocation, with data copy prior and after invocation. So here, TAs do not really share memory, they rather share data (passed through temp memory buffers).

**Comment by zz-fz-john** [comment]
> A client app (non-secure) can share a piece of memory with 2 TAs it invokes. In that case, the 2 TAs can access the very same memory area. Note that such memory is map in the TA space only for the time being of the TA invocation (e.g. InvokeCommand API) and unmaped once TA has completed the invocation.
> 
> When a TA invokes another TA and wants to share a buffer from its secure memory, then OP-TEE core creates a temporary (secure memory) buffer specifically for that invocation, with data copy prior and after invocation. So here, TAs do not really share memory, they rather share data (passed through temp memory buffers).

thank you ,In the first way you said,is the shared memory secure memory.

**Comment by etienne-lms** [comment]
> thank you ,In the first way you said,is the shared memory secure memory.

If you refer to paragraph _"A client app (non-secure) can share a piece of memory with 2 TAs it invokes..."_, then no, non-secure applications can only share non-secure memory with the TA(s) they invoke.
