### ISSUE TITLE
TA read data from GPIO on raspberry 3b

### ISSUE THREAD

**Issue by zz-fz-john** [OP-TEE/optee_os#5913]
Did the optee_internal_api provide an api to read data from GPIO on raspberry in secure world ?
or if i can use reading  uart address to read data in secure world?

**Comment by etienne-lms** [comment]
There exist a [GPIO driver API framework](https://github.com/OP-TEE/optee_os/blob/3.20.0/core/include/gpio.h) in optee, rather simplistic. I don't think _plat-rpi3_ embeds it.
What do you mean by _"uart address to read data in secure world"_?

**Comment by zz-fz-john** [comment]
> There exist a [GPIO driver API framework](https://github.com/OP-TEE/optee_os/blob/3.20.0/core/include/gpio.h) in optee, rather simplistic. I don't think _plat-rpi3_ embeds it. What do you mean by _"uart address to read data in secure world"_?

yeah！，thank you,I am using uart peripheral.I looked the internal_api.I found that there exist peripheral API,maybe I can use it to read data from uart.

**Comment by zz-fz-john** [comment]
> There exist a [GPIO driver API framework](https://github.com/OP-TEE/optee_os/blob/3.20.0/core/include/gpio.h) in optee, rather simplistic. I don't think _plat-rpi3_ embeds it. What do you mean by _"uart address to read data in secure world"_?

yeah！，thank you,I am using uart peripheral.I looked the internal_api.I found that there exist peripheral API,maybe I can use it to read data from uart.

**Comment by zz-fz-john** [comment]
> There exist a [GPIO driver API framework](https://github.com/OP-TEE/optee_os/blob/3.20.0/core/include/gpio.h) in optee, rather simplistic. I don't think _plat-rpi3_ embeds it. What do you mean by _"uart address to read data in secure world"_?

yeah! thank you,I am using uart peripheral.I looked the internal_api.I found that there exist peripheral API,maybe I can use it to read data from uart.

**Comment by zz-fz-john** [comment]
> There exist a [GPIO driver API framework](https://github.com/OP-TEE/optee_os/blob/3.20.0/core/include/gpio.h) in optee, rather simplistic. I don't think _plat-rpi3_ embeds it. What do you mean by _"uart address to read data in secure world"_?

I mean that I want to read data from the uart0 on rpi3,I found that there defines the uart address in [optee_os](https://github.com/OP-TEE/optee_os)/[core](https://github.com/OP-TEE/optee_os/tree/master/core)/[arch](https://github.com/OP-TEE/optee_os/tree/master/core/arch)/[arm](https://github.com/OP-TEE/optee_os/tree/master/core/arch/arm)/[plat-rpi3](https://github.com/OP-TEE/optee_os/tree/master/core/arch/arm/plat-rpi3)/main.c ,can I read data from this address?
And by the way,I found a TEE_Peripheral in https://globalplatform.org/wp-content/uploads/2016/11/GPD_TEE_Internal_Core_API_Specification_v1.2_PublicRelease.pdf,but it looks like the optee_os does not achieve it . Does it means that I couldn't use this api to control peripherals in OP-TEE?

**Comment by etienne-lms** [comment]
OP-TEE does not implement the Peripheral & Event APIs of TEE Internal Core API.

**Comment by qianfei11** [comment]
> OP-TEE does not implement the Peripheral & Event APIs of TEE Internal Core API.

Is there any reason, that why optee did not implement the Peripheral & Event APIs?

**Comment by etienne-lms** [comment]
matter of time, priorities etc... but contributions are welcome.
