### ISSUE TITLE
How to pass the boot data such as TZDRAM_SIZE to optee by spmc?

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5916]
Hi, experts,

In our current environment, optee runs at sel1 as sp, hafnium runs at sel2 as spmc, and optee's memory size is statically configured by CFG_TZDRAM_SIZE and CFG_TZCRAM_SIZE. Now that I have configured these two parameters before booting optee and want to pass them to optee via spmc. How to do?

**Comment by jenswi-linaro** [comment]
Does this relate to https://lists.trustedfirmware.org/archives/list/hafnium@lists.trustedfirmware.org/thread/3YOKL2WMQU2EGQ4BQROZCTPISRVLY22C/ ?

**Comment by zzbios** [comment]
Yes

**Comment by jenswi-linaro** [comment]
I believe you have the answer to your question in https://lists.trustedfirmware.org/archives/list/hafnium@lists.trustedfirmware.org/thread/HGSSTOVFYPIUNSY6SK2I3BWY22B6VZWR/
