### ISSUE TITLE
How to use core_mmu_add_mapping to map a large region?

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5919]
Hi, experts,

For dynamic mapping in core, core_mmu_add_mapping() allocates virtual memory space in the "reserved VA space" (MEM_AREA_RES_VASPACE) of core vmem ranges and maps memory to.

The function parameters are here:
void *core_mmu_add_mapping(enum teecore_memtypes type, paddr_t addr, size_t len)

I tried to add a map into the function boot_init_primary_late.

When I set the addr 0x8b0000000 and increase the len to 0x20000000, 
the following code did not pass:
	/*
	 * Something is wrong, we can't fit the va range into the selected
	 * table. The reserved va range is possibly missaligned with
	 * granule.
	 */
	if (core_mmu_va2idx(&tbl_info, map->va + len) >= tbl_info.num_entries)
		return NULL;

I add the debug message and it is shown as follows:
        D/TC: my_debug core_mmu_va2idx(&tbl_info, map->va + len):0x211, tbl_info.num_entries:0x200

It seems that tbl_info.num_entries is not large enough.
Do I ignored some configurations that should be modified synchronously？

Thanks.

optee configuration:
[conf.txt](https://github.com/OP-TEE/optee_os/files/11079812/conf.txt)

**Comment by jenswi-linaro** [comment]
This function is intended for smaller mappings and is not capable of adding mappings larger than the translation table used for MEM_AREA_RES_VASPACE.

Have you tried making it part of the static memory mappings using for instance `register_phys_mem()` instead? 

If that isn't an option then `core_mmu_add_mapping()` needs to be fixed so it can handle more than one translation table, a bit like `core_mmu_map_contiguous_pages()`.

**Comment by zzbios** [comment]
> This function is intended for smaller mappings and is not capable of adding mappings larger than the translation table used for MEM_AREA_RES_VASPACE.
> 
> Have you tried making it part of the static memory mappings using for instance `register_phys_mem()` instead?
> 
> If that isn't an option then `core_mmu_add_mapping()` needs to be fixed so it can handle more than one translation table, a bit like `core_mmu_map_contiguous_pages()`.

In our scenario, we control optee's memory size with uefi variable, so static memory mapping may not be possible. Thanks for the confirmation.
