### ISSUE TITLE
Virtualization and core_mmu_add_mapping

### ISSUE THREAD

**Issue by patrickjauernig** [OP-TEE/optee_os#5924]
Hi,

I am using a setup with Xen + OP-TEE with CFG_NS_VIRTUALIZATION. While Xen is initializing (before the first VM booted), I want to call OP-TEE (core) and use cryptographic functions. However, they do not have a "context" at this time (and hence, fail), so I am creating a VM (corresponding to the hypervisor) to create a context (shortened):

```
thread_get_core_local()->curr_thread = 0;
virt_guest_created(id);
virt_set_guest(id);
```

This works, but then `core_mmu_add_mapping` and `core_mmu_remove_mapping` (with the `MEM_AREA_NSEC_SHM` type) do not work correctly anymore when trying to (un)map Xen memory (I think it is mainly due to the absence of MEM_AREA_RES_VASPACE). 

Is there anything to create the context for the cryptographic functions without creating a VM, or to fix the memory mappings? Sorry, I could not find any information on this topic.

**Comment by jenswi-linaro** [comment]
It sounds like you're on the right track. Why isn't `MEM_AREA_RES_VASPACE` available?

**Comment by patrickjauernig** [comment]
It was there before I created the VM but is not there anymore after the "hypervisor VM" was created and set as guest. I guess it is because (based on the current implementation) VM contexts are not expected to need it? Based on what I saw, virtualization is heavily focusing on TA execution.

As a side observation, in the "hypervisor VM", `core_mmu_add_mapping` does not work the first time I invoke it (taking [this branch](https://github.com/OP-TEE/optee_os/blob/db8ca286ea44786a19e344ca02b47cc8be04924e/core/mm/core_mmu.c#L2050)), i.e., `find_map_by_va` returns NULL . When invoking it a second time, it takes the [other branch](https://github.com/OP-TEE/optee_os/blob/db8ca286ea44786a19e344ca02b47cc8be04924e/core/mm/core_mmu.c#L2058), and I can get the map containing the virtual address. 

Then, when removing the mapping later, [it errors out because it cannot find MEM_AREA_RES_VASPACE](https://github.com/OP-TEE/optee_os/blob/db8ca286ea44786a19e344ca02b47cc8be04924e/core/mm/core_mmu.c#L1939).

**Comment by jenswi-linaro** [comment]
We've done just enough to have the current use cases working with virtualization. By the way, what you call "hypervisor VM" we call partition.

One shortcut is the initialized data section for partitions, it's copied from the partition data section of what we had when exiting to normal world for the first time. It's mostly just initialized, but some of that data section is changed, for instance `static_memory_map`. I suppose you've noticed `__nex_bss` and `__nex_data`, that's data shared between partitions. We call that part of the code the nexus. Other global variables without a `__nex_*` tag are per partition.
