### ISSUE TITLE
TA Fails To Read NSEC_SHM Region from Secure World

### ISSUE THREAD

**Issue by rtrimana** [OP-TEE/optee_os#5927]
Hi All,

I have been trying to follow the recipes to access the memory of the Normal World (NW) from the Secure World (SW) as discussed in #1343 and the other related issues (such as #4430). However, I could not even read the already mapped `NSEC_SHM` region from my TA. This was tested on QEMU v7.

My memory translation table is as the following (as shown on the SW side):
```
D/TC:0   dump_mmap_table:807 type TEE_RAM_RX   va 0x0e100000..0x0e1aefff pa 0x0e100000..0x0e1aefff size 0x000af000 (smallpg)
D/TC:0   dump_mmap_table:807 type TEE_RAM_RW   va 0x0e1af000..0x0e2fffff pa 0x0e1af000..0x0e2fffff size 0x00151000 (smallpg)
D/TC:0   dump_mmap_table:807 type SHM_VASPACE  va 0x0e300000..0x102fffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0   dump_mmap_table:807 type RES_VASPACE  va 0x10300000..0x10cfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0   dump_mmap_table:807 type IO_SEC       va 0x10d00000..0x10dfffff pa 0x08000000..0x080fffff size 0x00100000 (pgdir)
D/TC:0   dump_mmap_table:807 type IO_SEC       va 0x10e00000..0x10efffff pa 0x09000000..0x090fffff size 0x00100000 (pgdir)
D/TC:0   dump_mmap_table:807 type IO_SEC       va 0x10f00000..0x10ffffff pa 0x0e000000..0x0e0fffff size 0x00100000 (pgdir)
D/TC:0   dump_mmap_table:807 type TA_RAM       va 0x11000000..0x11cfffff pa 0x0e300000..0x0effffff size 0x00d00000 (pgdir)
D/TC:0   dump_mmap_table:807 type NSEC_SHM     va 0x11d00000..0x11efffff pa 0x7fe00000..0x7fffffff size 0x00200000 (pgdir)
```

When trying to read the `TA_RAM` portion (address `0x11000000`) or `NSEC_SHM` (address `0x11d00000`), I got the following panic messages.
```
E/TC:? 0 TA panicked with code 0xffff0001
E/LD:  Status of TA 484d4143-2d53-4841-3120-4a6f636b6542
E/LD:   arch: arm
E/LD:  region  0: va 0x00102000 pa 0x0e300000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x00104000 pa 0x0e302000 size 0x00c000 flags r-xs (ldelf)
E/LD:  region  2: va 0x00110000 pa 0x0e30e000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x00111000 pa 0x0e30f000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x00115000 pa 0x0e313000 size 0x001000 flags r--s
E/LD:  region  5: va 0x00116000 pa 0x0e33f000 size 0x001000 flags rw-s (stack)
E/LD:  region  6: va 0x00195000 pa 0x00001000 size 0x01f000 flags r-xs [0]
E/LD:  region  7: va 0x001b4000 pa 0x00020000 size 0x00c000 flags rw-s [0]
E/LD:  region  8: va 0x00200000 pa 0x44793c80 size 0x001000 flags rw-- (param)
E/LD:  region  9: va 0x00201000 pa 0x44793c94 size 0x001000 flags rw-- (param)
E/LD:   [0] 484d4143-2d53-4841-3120-4a6f636b6542 @ 0x00195000
E/LD:  Call stack:
E/LD:   0x001a1134
E/LD:   0x001a0a59
E/LD:   0x0019dfe3
E/LD:   0x0019e005
E/LD:   0x001951b7
E/LD:   0x001958b1
E/LD:   0x00195b07
E/LD:   0x001a249b
E/LD:   0x00195bd3
E/LD:   0x001a2165
E/LD:   0x001a21ef
E/LD:   0x00195b53
E/LD:   0x00195bec
D/TC:? 0 user_ta_enter:176 tee_user_ta_enter: TA panicked with code 0xffff0001
D/TC:? 0 destroy_ta_ctx_from_session:341 Remove references to context (0x158e0fb4)
D/TC:? 0 destroy_context:326 Destroy TA ctx (0x158e0fa8)
D/TC:? 0 tee_ta_close_session:529 csess 0x158e0fe8 id 1
D/TC:? 0 tee_ta_close_session:548 Destroy session
```
What confuses me the most is probably that we have two virtual addresses (`va`) for the `TA_RAM` (with `pa=0x0e300000`). One is `0x11000000` in the SW messages and the other one is `0x00102000` in the panic messages. Now, I believe reading from `0x00102000` in the TA works flawlessly.

**Further Questions:**

(1) In other related issues on accessing NW memory from SW (e.g., a TA), people have been talking about traversing the translation table. How do we access/traverse the table from inside the TA? I was trying to look into the available APIs for TA in `optee_os/lib/libutee/tee_api.c`, but did not find anything that allows me to access the translation table. Currently, my understanding (by reading the code) is that this translation table access is performed a lot in `core_mmu.c`.

(2) What is the right way to access the `NSEC_SHM` from the TA, provided that I can map the memory from the NW into the `NSEC_SHM` pool and get the right virtual address by traversing the translation table? Code snippets/examples are much appreciated here.

If anyone has any insights, please kindly share them here. Thanks so much in advance.

**Comment by jenswi-linaro** [comment]
The shared memory normally comes from normal world. We're implementing GlobalPlatform TEE Client API Specification, https://globalplatform.org/specs-library/tee-client-api-specification/ so that should be a good start.

**Comment by rtrimana** [comment]
Thank you so much for the pointers. I am closing this issue now. I will reopen it again if I have further questions.

**Comment by jenswi-linaro** [comment]
The QEMU v7 (and v8) platform ports now pick up the non-secure memory range from the DTB generated by QEMU at the start, so DRAM0_BASE and DRAM0_SIZE are not needed any longer. If compiled with CFG_CORE_RESERVED_SHM=y we're carving out a static shared memory area using `mark_static_shm_as_reserved()`.

**Comment by rtrimana** [comment]
I see. Thanks so much for this information. How about the Rockchip board, whose [platform configuration is shown here](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-rockchip/platform_config.h)? This is the board we are currently using and unlike other boards (e.g., [Hikey](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/platform_config.h#L107)), it doesn't have `DRAM0_BASE` and `DRAM0_SIZE` as well.

**Comment by jenswi-linaro** [comment]
Rockchip might be using `CFG_CORE_RESERVED_SHM=y` with a fixed shared memory carveout instead, see `CFG_SHMEM_START` and `CFG_SHMEM_SIZE` in `core/arch/arm/plat-rockchip/conf.mk`.

**Comment by rtrimana** [comment]
Thank you so much @jenswi-linaro for sharing your knowledge and insights. I will keep the issue open for a little while in case I have more questions.
