### ISSUE TITLE
alloc_pgt:148 19 page tables not available 

### ISSUE THREAD

**Issue by trriger** [OP-TEE/optee_os#5928]
Hi
The development board I used was Hikey960 and the OP-TEE version was 3.16.
I set `CFG_TZDRAM_SIZE` from 16MB(`0x01000000`) to 32MB (`0x02000000`) and then `DRAM1_BASE` from `0x40000000` to `0x41000000`. After these modifications, the system started normally, and the tests of `xtest` were all successful.
However, when running my own program, I found that using `TEEC_Operation` to  transmit data about 10MB to the TA would output `E/TC:? 0 alloc_pgt:148 19 page tables not available`.
What is the possible reason for this, or am I modifying the configuration incompletely?

**Comment by jenswi-linaro** [comment]
You're running out of translation tables reserved for TAs. It's defined as `PGT_CACHE_SIZE` in `pgt_cache.h`. The easiest way to increase it is to increase `CFG_NUM_THREADS`.

**Comment by trriger** [comment]
Thanks@jenswi-linaro 
I set CFG_NUM_THREADS=32. My TA is working normally. I want to know  the maximum CFG_NUM_THREADS which can be set on the Hikey960.
