### ISSUE TITLE
Generating deterministic RSA keypair

### ISSUE THREAD

**Issue by aminusamine** [OP-TEE/optee_os#593]
Hello,

I also working on OPTEE and i saw in the GPD internal API that GenerateKey function generates random keys, is there a way to generate deterministic keys according to a parameter transmitted ?

Thank you, 
Best regards

**Comment by pascal-brand-st-dev** [comment]
Hello,

the best is to populate an object with the key of your choice, as in the [4006](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/xtest_4000.c#L3819) xtest

Regards,
Pascal.

**Comment by jbech-optee-adm** [comment]
Question has been answered and therefore I'm closing the issue, please re-open if you have follow up questions.
