### ISSUE TITLE
TEE_GetObjectBufferAttribute failure

### ISSUE THREAD

**Issue by like-c** [OP-TEE/optee_os#5934]
Hello ,

I am trying to perform an RSA Private-key Encryption with RSA_NOPAD. I import a key and then extract public& private exponent from it along with modulus.
```
TEE_ObjectHandle transient_key_handle = NULL; 
uint32_t create_flag = TEE_DATA_FLAG_ACCESS_READ|TEE_DATA_FLAG_ACCESS_WRITE|TEE_DATA_FLAG_ACCESS_WRITE_META|TEE_DATA_FLAG_OVERWRITE;

... // set n,d,e members of attrs from params
TEE_AllocateTransientObject(TEE_TYPE_RSA_KEYPAIR, 4096, &transient_key_handle); 
TEE_PopulateTransientObject(transient_key_handle, attrs/*n,d,e*/, attrs_num);
TEE_RestrictObjectUsage1(transient_key_handle, TEE_USAGE_ENCRYPT | TEE_USAGE_DECRYPT | TEE_USAGE_SIGN | TEE_USAGE_VERIFY);

TEE_GetObjectBufferAttribute(transient_key_handle, TEE_ATTR_RSA_PRIVATE_EXPONENT, (void*)out, &size); 
```
I get 'TA panicked with code 0xffff0006' when call TEE_GetObjectBufferAttribute whith TEE_ATTR_RSA_PRIVATE_EXPONENT. When I modify TEE_ATTR_RSA_PUBLIC_EXPONENT, I get '0x01,0x00,0x01‘(publicExponent).

@jforissier , please help me point out the reason why my above example is incorrect. Thank you very much. :pray:  🙏

**Comment by jforissier** [comment]
Hello @like-c,

I think you need to add `TEE_USAGE_EXTRACTABLE` to the usage flags in `TEE_RestrictObjectUsage1()`.

**Comment by like-c** [comment]
@jforissier 
Thank you for your help. Due to the need for functional integration and hardware adaptation,  I apologize for the delay in replying to this message...
 I have verified this solution on the s32g SOC and it is working. After trying to understand the macros (refer to  #1677 #5497), my understanding is that it is not necessary to export the key during formal product delivery, but to use the object handle to complete the corresponding functions in subsequent processes.
 Is my understanding correct? thank you.

**Comment by jforissier** [comment]
In principle there is no need to export the private key. The TA usually doesn't need it. For better security it should remain in the TEE core, or even better in a hardware accelerator (for platforms that have a TEE driver for that, for example the NXP CAAM).

**Comment by like-c** [comment]
Get it, thanks. :slightly_smiling_face:
