### ISSUE TITLE
Not Able to get TA Logs in OPTEE v3.3.0

### ISSUE THREAD

**Issue by dhruv77777** [OP-TEE/optee_os#5939]
Hey All,

I am trying to run OPTEE v3.3.0 on imx6 board, OPTEE is working fine but, i am not able to get any TA logs.
I went through all the issues where they have mentioned to change "**CFG_TEE_TA_LOG_LEVEL**" and "**CFG_TEE_CORE_LOG_LEVEL**". 
Both of these configs i have set to 4 in **mk/config.mk** and **TA Makefile** and generated a new OPTEE image and CA/TA, but still no traces. Do i have to make any extra change in Kernel code or have to enable some config from kernel as well?

**Comment by jforissier** [comment]
Hi @dhruv77777,

Traces are sent to the secure console (UART). The kernel is not involved. Do you at least see some messages from OP-TEE, such as the initialization logs (`OP-TEE version xxx` etc.)?

**Comment by dhruv77777** [comment]
Hi @jforissier 

Thanks for the reply....
Yes, I can be able to see the startup logs from OPTEE, such as 
**TEE_SHMEM_START type NSEC_SHM 0x4fa00000 size 0x00200000
TA_RAM_START type TA_RAM 0x4e100000 size 0x01900000**

I am pretty sure, the version is OPTEE 3.3.0 and OPTEE is working (As i have used the secure storage API to store data into REE_FS).

**Comment by jforissier** [comment]
>  Yes, I can be able to see the startup logs from OPTEE [...]

That's good. Can you check that the log levels are actually OK in the generated configuration file in the build directory? The path is `optee_os/out/arm/conf.mk` (`arm` may `arm-plat-$(PLATFORM)` instead depending on how you build). For example in my build environment:
```
$ grep LOG_LEVEL out/arm/conf.mk
CFG_TEE_CORE_LOG_LEVEL=2
CFG_TEE_TA_LOG_LEVEL=1
```
Then sorry for stating the obvious... but are you 100% sure the OP-TEE image you are running it the one you have rebuilt? Same for the TA.
