### ISSUE TITLE
Does optee currently supports stmm with FFA？

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5941]
Hi, experts,
I see the function id about stmm with FFA in stmm_sp.c, does optee provide test cases related to stmm now? If not, should I write the CA like stats_pta case?

**Comment by jenswi-linaro** [comment]
I'm not sure how useful that is. StMM is only used by the boot loader and then internally by the kernel. Interacting directly with StMM may give inconsistent results compared to the kernels view of things.

**Comment by zzbios** [comment]
> I'm not sure how useful that is. StMM is only used by the boot loader and then internally by the kernel. Interacting directly with StMM may give inconsistent results compared to the kernels view of things.

Hi, I just want to test if stmm works.

**Comment by jenswi-linaro** [comment]
Perhaps @apalos has a few tips.
