### ISSUE TITLE
PTA attestation from TA

### ISSUE THREAD

**Issue by jewcomm** [OP-TEE/optee_os#5942]
Hello,

I want call functions from [attestation.c](https://github.com/OP-TEE/optee_os/blob/master/core/pta/attestation.c) from TA. I watched #4776 but dont understand how do it. I enable **CFG_ATTESTATION_PTA** in _config.mk_. 

Do i need to use functions similar to **TEEC_InvokeCommand**, or can i directly call from TA to PTA?
 
How to do this if I don't have headers with **cmd_hash_tee_memory** and others?

**Comment by jenswi-linaro** [comment]
You need to use `TEE_InvokeTACommand()`. `pta_attestation.h` is available for TAs to include.

**Comment by jforissier** [comment]
You can see some use cases in `xtest`: https://github.com/OP-TEE/optee_test/blob/178f3b12a761b1ebcf813da27dfcc825c523989b/host/xtest/regression_1000.c#L3114-L3146
