### ISSUE TITLE
Failed to run large size TA

### ISSUE THREAD

**Issue by zzbios** [OP-TEE/optee_os#5943]
Hi, experts,
We are currently testing the feasibility of running a large size TA（about 7M+）.
The method is to add a 7MB variable with const char type in hello_world_ta.c as follows:
const char test_char[7 * 1024 * 1024];

When I run this TA, the system failed with error code **0xffff000c** sometimes, which means TEE_ERROR_OUT_OF_MEMORY.
I added some debug prints near the error message.

**The error log is as follows:**
#./optee_example_hello_world
D/TC:003 000 mobj_ffa_get_by_cookie:381 cookie 0 resurrecting
D/TC:??? 000 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
D/TC:??? 000 ldelf_load_ldelf:96 ldelf load address 0x40008000
D/LD:    ldelf:134 Loading TS 8aaaf200-2450-11e4-abe2-0002a5d5c51b
F/TC:??? 000 trace_syscall:151 syscall #3 (syscall_get_property)
F/TC:??? 000 trace_syscall:151 syscall #5 (syscall_open_ta_session)
D/TC:??? 000 ldelf_syscall_open_bin:143 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (early TA)
D/TC:??? 000 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:??? 000 ldelf_syscall_open_bin:143 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:003 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1481 
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1493
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1498
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1504 READ_ONCE(descr->address_range_count):1
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1511 
D/TC:??? 000 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:??? 000 ldelf_syscall_open_bin:143 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:003 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0xb
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1481 
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1493
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1498
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1504 READ_ONCE(descr->address_range_count):265
E/TC:??? 000 mobj_ffa_get_by_cookie:423 Failed to get cookie 0xb internal_offs 0
D/TC:??? 000 thread_rpc_alloc:1264 mobj_ffa_get_by_cookie(0xb, 0): failed
D/TC:??? 000 ldelf_syscall_open_bin:146 res=0xffff000c
E/LD:    init_elf:486 sys_open_ta_bin(8aaaf200-2450-11e4-abe2-0002a5d5c51b)
E/TC:??? 000 ldelf_init_with_ldelf:131 ldelf failed with res: 0xffff000c
D/TC:??? 000 tee_ta_open_session:735 init session failed 0xffff000c
D/TC:??? 000 thread_rpc_free:1224 freeing cookie 0x1
D/TC:003 000 ffa_inactivate:493 cookie 0x1
D/TC:003 000 ffa_inactivate:493 cookie 0
optee_example_hello_world: TEEC_Opensession failed with code 0xffff000c origin 0x3

**Sometimes it can run succesfully. The log is as follows:**
#./optee_example_hello_world
D/TC:003 000 mobj_ffa_get_by_cookie:381 cookie 0 resurrecting
D/TC:??? 000 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
D/TC:??? 000 ldelf_load_ldelf:96 ldelf load address 0x40008000
D/LD:    ldelf:134 Loading TS 8aaaf200-2450-11e4-abe2-0002a5d5c51b
F/TC:??? 000 trace_syscall:151 syscall #3 (syscall_get_property)
F/TC:??? 000 trace_syscall:151 syscall #5 (syscall_open_ta_session)
D/TC:??? 000 ldelf_syscall_open_bin:143 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (early TA)
D/TC:??? 000 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:??? 000 ldelf_syscall_open_bin:143 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:003 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0x1
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1481 
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1493 
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1498 
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1504 READ_ONCE(descr->address_range_count):1
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1511
D/TC:??? 000 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:??? 000 ldelf_syscall_open_bin:143 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:003 000 mobj_ffa_get_by_cookie:384 Populating mobj from rx buffer, cookie 0xc
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1481 
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1493 
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1498 
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1504 READ_ONCE(descr->address_range_count):172
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1511 
D/TC:??? 000 ldelf_syscall_open_bin:146 res=0
F/TC:??? 000 trace_syscall:151 syscall #7 (syscall_invoke_ta_command)
F/TC:??? 000 trace_syscall:151 syscall #11 (syscall_mask_cancellation)
F/TC:??? 000 trace_syscall:151 syscall #7 (syscall_invoke_ta_command)
F/TC:??? 000 trace_syscall:151 syscall #3 (syscall_get_property)
F/TC:??? 000 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:??? 000 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:??? 000 trace_syscall:151 syscall #6 (syscall_close_ta_session)
D/TC:??? 000 thread_rpc_free:1224 freeing cookie 0xc
D/TC:003 000 ffa_inactivate:493 cookie 0xc
F/TC:??? 000 trace_syscall:151 syscall #3 (syscall_get_property)
D/LD:    ldelf:169 ELF (8aaaf200-2450-11e4-abe2-0002a5d5c51b) at 0x4008a000
F/TC:??? 000 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:??? 000 trace_syscall:151 syscall #8 (syscall_check_access_rights)
F/TC:??? 000 trace_syscall:151 syscall #4 (syscall_get_property_name_to_index)
D/TA:  TA_CreateEntryPoint:41 has been called
D/TA:  TA_OpenSessionEntryPoint:70 has been called
I/TA: Hello World!
D/TC:??? 000 thread_rpc_free:1224 freeing cookie 0x1
D/TC:003 000 ffa_inactivate:493 cookie 0x1
D/TC:003 000 ffa_inactivate:493 cookie 0
Invoking TA to increment 42
D/TC:003 000 mobj_ffa_get_by_cookie:381 cookie 0 resurrecting
D/TA:  inc_value:107 has been called
I/TA: Got value: 42 from NW
I/TA: Increase value to: 43
D/TC:003 000 ffa_inactivate:493 cookie 0
TA incremented value to 43
D/TC:003 000 mobj_ffa_get_by_cookie:381 cookie 0 resurrecting
D/TC:??? 000 tee_ta_close_session:530 csess 0x894106900 id 1
D/TC:??? 000 tee_ta_close_session:548 Destroy session
I/TA: Goodbye!
D/TA:  TA_DestroyEntryPoint:52 has been called
D/TC:??? 000 destroy_context:326 Destroy TA ctx (0x8941068a0)
D/TC:003 000 ffa_inactivate:493 cookie 0

**Key print is as follows:**
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1504 READ_ONCE(descr->address_range_count):265
E/TC:??? 000 mobj_ffa_get_by_cookie:423 Failed to get cookie 0xb internal_offs 0
And I saw this in the funtion **thread_spmc_populate_mobj_from_rx**:
	/*
	 * OP-TEE is only supporting a single mem_region while the
	 * specification allows for more than one.
	 */
I guess the problem has something to do with optee not supporting multiple mem_regions.
It should be added that the problem may also have something to do with this issue.
https://github.com/OP-TEE/optee_os/issues/5893

**I have two questions now.**
1. Why does optee not support multiple mem_regions and how does this affect the problem？
2. How to solve this problem？

Thanks！

**Comment by jenswi-linaro** [comment]
> **I have two questions now.**
> 
> 1. Why does optee not support multiple mem_regions and how does this affect the problem？

That's not a limiting factor. You're maybe confusing struct ffa_mem_region with struct ffa_address_range.

> 2. How to solve this problem？

You need to pinpoint the problem first. Is the problem in OP-TEE or in Hafnium?

By the way, it's an impressive system you have with a three-digit number of cores.

Since you have such a large-scale system you're not unlikely to run into all kinds of unexpected limits.

**Comment by zzbios** [comment]
> > **I have two questions now.**
> > 
> > 1. Why does optee not support multiple mem_regions and how does this affect the problem？
> 
> That's not a limiting factor. You're maybe confusing struct ffa_mem_region with struct ffa_address_range.
> 
> > 2. How to solve this problem？
> 
> You need to pinpoint the problem first. Is the problem in OP-TEE or in Hafnium?
> 
> By the way, it's an impressive system you have with a three-digit number of cores.
> 
> Since you have such a large-scale system you're not unlikely to run into all kinds of unexpected limits.

D/TC:??? 000 ldelf_syscall_open_bin:143 Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:??? 000 ree_fs_ta_open:256
D/TC:003     thread_spmc_msg_recv:985
D/TC:003     handle_yielding_call:446
D/TC:??? 000 rpc_load:205
D/TC:003     thread_spmc_msg_recv:985 FFA_MSG_SEND_DIRECT_REQ
D/TC:003     handle_yielding_call:446
D/TC:??? 000 thread_rpc_alloc:1264
D/TC:003 000 mobj_ffa_get_by_cookie:388 Populating mobj from rx buffer, cookie 0x9
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1487
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1499
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1504
D/TC:003 000 thread_spmc_populate_mobj_from_rx:1510
D/TC:003 000 set_pages:1458 set_pages:1458, num_regions:272
D/TC:003 000 set_pages:1468 set_pages:1468, idx:1668,num_pages:1815
E/TC:??? 000 mobj_ffa_get_by_cookie:427 Failed to get cookie 0x9 internal_offs 0
D/TC:??? 000 thread_rpc_alloc:1268 mobj_ffa_get_by_cookie(0x9, 0): failed
D/TC:??? 000 ldelf_syscall_open_bin:146 res=0xffff000c
E/LD:    init_elf:486 sys_open_ta_bin(8aaaf200-2450-11e4-abe2-0002a5d5c51b)
E/TC:??? 000 ldelf_init_with_ldelf:131 ldelf failed with res: 0xffff000c
D/TC:??? 000 tee_ta_open_session:735 init session failed 0xffff000c
D/TC:??? 000 thread_rpc_free:1227 freeing cookie 0x1
D/TC:003 000 ffa_inactivate:497 cookie 0x1
D/TC:003     thread_spmc_msg_recv:985 FFA_MSG_SEND_DIRECT_REQ
D/TC:003     handle_yielding_call:446
D/TC:003 000 ffa_inactivate:497 cookie 0
optee_example_hello_world: TEEC_Opensession failed with code 0xffff000c origin 0x3

Hi, I debuged the issue further and found a few problems:
1. thread_spmc_msg_recv is called only when CFG_CORE_SEL1_SPMC=y is compiled. Our system selects CFG_CORE_SEL2_SPMC=y for hafnium. I haven't figure out why thread_spmc_msg_recv is being called here.
2. I added some debug_logs in function set_pages
```
static int set_pages(struct ffa_address_range *regions,
		     unsigned int num_regions, unsigned int num_pages,
		     struct mobj_ffa *mf)
{
	unsigned int n = 0;
	unsigned int idx = 0;
	DMSG("%s:%d, num_regions:%d\n",__func__,__LINE__,num_regions);
	for (n = 0; n < num_regions; n++) {
		unsigned int page_count = READ_ONCE(regions[n].page_count);
		uint64_t addr = READ_ONCE(regions[n].address);

		if (mobj_ffa_add_pages_at(mf, &idx, addr, page_count)) {
			DMSG("s:%d, n:%d\n",__func__,__LINE__,n);
			return FFA_INVALID_PARAMETERS;
		}
	}
	DMSG("%s:%d, idx:%d,num_pages:%d\n",__func__,__LINE__,idx,num_pages);
	if (idx != num_pages)
		return FFA_INVALID_PARAMETERS;

	return 0;
}
```
I found that when num_regions >= 252, mobj_ffa_add_pages_at(mf, &idx, addr, page_count) will fail and set_pages return FFA_INVALID_PARAMETERS; When num_regions < 252, TA runs success. The value of num_regions is random each time TA is run.

**Comment by jenswi-linaro** [comment]
Cookie is the FF-A handle.

The PA comes from the normal world. In this case, I expect that it's memory allocated in tee-supplicant.

**Comment by zzbios** [comment]
> Cookie is the FF-A handle.
> 
> The PA comes from the normal world. In this case, I expect that it's memory allocated in tee-supplicant.

Hi, Jens,
I seem to have found some valuable leads.
1. This problem occurs when the number of fragments allocated for shared memory on the ree side is greater than 1, that is, address_range_count>252.
2. I tried to modify the following code:
static uint8_t __rx_buf[SMALL_PAGE_SIZE] __aligned(SMALL_PAGE_SIZE); 
-> 
static uint32_t __rx_buf[SMALL_PAGE_SIZE] __aligned(SMALL_PAGE_SIZE); 
The strange address 0x8002f0000 is missing and printed 0x0， 
debug log is as follows：
hafnium print in the function ffa_memory_retrieve:
retrieve_request_length:30
receiver_id:8001
constituent_count:853, page_count:1815
start_address of ffa_memory_region_constituent:0x00000008800d7040,
constituents[0].address:0x9b3654000, constituents[0].page_count:0x1
constituents[1].address:0x9b3633000, constituents[1].page_count:0x1
constituents[2].address:0x9ce4f5000, constituents[2].page_count:0x2
constituents[3].address:0x9c6c5e000, constituents[3].page_count:0x1
...
constituents[251].address:0x9a2eec000, constituents[251].page_count:0x2
constituents[252].address:0x9a2f06000, constituents[252].page_count:0x2
constituents[253].address:0x9bb5c0000, constituents[253].page_count:0x2
...
constituents[851].address:0x9d2eec000, constituents[851].page_count:0x4
constituents[852].address:0x99ef7c000, constituents[852].page_count:0x4
constituents[853].address:0x9c5758000, constituents[853].page_count:0x4

optee print in the function mobj_ffa_add_pages_at:
D/TC:041 000 mobj_ffa_add_pages_at:220, idx:0, n:1, pa:0x9b3654000, num_pages:1
D/TC:041 000 mobj_ffa_add_pages_at:220, idx:1, n:2, pa:0x9b3633000, num_pages:1
D/TC:041 000 mobj_ffa_add_pages_at:220, idx:2, n:4, pa:0x9ce4f5000, num_pages:2
D/TC:041 000 mobj_ffa_add_pages_at:220, idx:4, n:5, pa:0x9c6c5e000, num_pages:1
...
D/TC:041 000 mobj_ffa_add_pages_at:220, idx:421, n:423, pa:0x9a2eec000, num_pages:2
D/TC:041 000 mobj_ffa_add_pages_at:220, idx:423, n:423, pa:0x0, num_pages:0
D/TC:041 000 mobj_ffa_add_pages_at:220, idx:423, n:423, pa:0x0, num_pages:0
...
D/TC:041 000 mobj_ffa_add_pages_at:220, idx:423, n:423, pa:0x0, num_pages:0
D/TC:041 000 mobj_ffa_add_pages_at:220, idx:423, n:423, pa:0x0, num_pages:0
D/TC:041 000 mobj_ffa_add_pages_at:220, idx:423, n:423, pa:0x0, num_pages:0

It seems optee had a problem with the retrieving the 252nd constituent memory in which case fragments>=2.
Do you know how to solve the problem?

**Comment by jenswi-linaro** [comment]
> Do you mean the part of optee that hasn't been implemented is the one in the red box?

Yes, that's correct.

**Comment by wangym307** [comment]
To avoid ffa memory fragmented transaction, maybe we could change ffa tx/rx buffer of (REE, hafnium and OPTEE) to a bigger size, such as 16k or 64k(current default size is 4k).  
However, It seems hafnium and OPTEE have some limits for changing ffa tx/rx buffer size. **Is it possible? or have you seen someone who did it successfully?**

**Comment by jenswi-linaro** [comment]
It might be easier to implement fragmented transactions directly instead. It shouldn't take long with a good test case on QEMU provided that only OP-TEE needs to be updated.
