### ISSUE TITLE
Can the link address be different from the loading address?

### ISSUE THREAD

**Issue by LeiSen62** [OP-TEE/optee_os#5944]
Hi, experts,
If the OPTEE-OS loading address allocated by the BIOS is different from the OPTEE-OS link address,  the OPTEE-OS cannot be started. Whether we can support the link address is different from the loading address, so that we boot OPTEE-OS in mutable address. I have a patch that can do this.

**Comment by jenswi-linaro** [comment]
> I have a patch that can do this.

So do I, or in fact, quite a few patches to in the end enable this.

**Comment by LeiSen62** [comment]
I have passed the debugging based on the D06 platform. Should I submit the patch first for discussion?

**Comment by jenswi-linaro** [comment]
Sure, it should be interesting to compare different approaches to the problem.

**Comment by LeiSen62** [comment]
I have submitted a PR: https://github.com/OP-TEE/optee_os/pull/5948
Any good ideas please contact me, thank you!
