### ISSUE TITLE
Will optee adapt to the GP interface of the x448 curve recently?

### ISSUE THREAD

**Issue by bhLou** [OP-TEE/optee_os#5951]
Hi, experts,
I see the merge:Gp 1.3.1 updates #5688 that add TEE_ATTR_X448_* defines, does optee will implement the X448 GP interface adaptation soon?

**Comment by jenswi-linaro** [comment]
We have no concrete plans for that as far as I know, but patches are welcome.

**Comment by jforissier** [comment]
Both LibTomCrypt and MBedTLS support the x448 curve so it should not be too hard to implement. I suppose x25519 can be used as a reference (see `git log --grep=X25519`).

**Comment by bhLou** [comment]
Yes，as I know，there are many similarities between the x448 and x25519 curves. 
Should the two curves be implemented separately or combined?  If combined, how to modify it, such as x25519_448?

**Comment by jenswi-linaro** [comment]
Please use a separate struct x448_keypair for now, unless there is a large gain in reusing it.

I can't find any x25519 in the upstream drvcrypt, but perhaps I've been looking at the wrong place.
