### ISSUE TITLE
Does it have glib-2.0 into Op-tee internal API

### ISSUE THREAD

**Issue by lindrix** [OP-TEE/optee_os#5956]
Hi!
Is there the glib-2.0 in OpTEE libraries? If yes, how to declare it in my TA Makefile?

**Comment by jforissier** [comment]
Hi @lindrix, the answer is no. Some libraries can be ported to the TA runtime environnement relatively easily, others are much more problematic depending on what they depend on.

**Comment by lindrix** [comment]
Ah, i understood, jforissier...
Thank you!
