### ISSUE TITLE
About FF-A ABI and GP API

### ISSUE THREAD

**Issue by Master-Chi** [OP-TEE/optee_os#5958]
Hi, Optee community
     I am learning FF-A spec v1.1 right now. I think the FF-A ABI and GP API have many functions in common. 
But FF-A abi is more brief and has better abstraction. Is there any chance FF-A abi could replace GP API in some day ? 
Or do you think they will co-exist for a long time？

**Comment by Master-Chi** [comment]
Like FFA_MEM_SHARE vs TEEC_SharedMemory and FFA_MSG_SEND_DIRECT_REQ vs TEEC_InvokeCommand

**Comment by jenswi-linaro** [comment]
Got it, thanks.

No, FF-A is not going to replace GP Client API. There is some overlap, but they provide abstraction at different levels and perhaps in different contexts too. Even if it might be possible to provide an FF-A ABI for non-secure user space there are still a few features missing. FF-A should rather be seen as a replacement for using the SMC instruction directly.

**Comment by Master-Chi** [comment]
Thanks for your relay.
I will try to understand your point of view
