### ISSUE TITLE
Meson in Op-TEE

### ISSUE THREAD

**Issue by lindrix** [OP-TEE/optee_os#5959]
Hi!
Is there meson build system support in Op-TEE toolchain? 

If no, how to can i change a app, that use meson, to use other build system?

Thanks.

**Comment by jbech-linaro** [comment]
Hi @lindrix ,

Not what I'm aware of and hence this is not something you find being used/implemented in the OP-TEE code base. Unfortunately I have no experience configuring meson, so I cannot give any advice either. // Joakim

**Comment by lindrix** [comment]
Ok.
Thank you very much for answer, Jbech.
