### ISSUE TITLE
OPTEE on Autotalks chip

### ISSUE THREAD

**Issue by dhruv77777** [OP-TEE/optee_os#5964]
Hey All,

Can we port OPTEE 3.3.0 on Autotalks CRATON2 CUT 3.0 Chip.
If yes, what are the necessary changes we need to do in U-Boot and Kernel?

**Comment by jbech-linaro** [comment]
Hi,

The only thing I can see when searching for that product is: "Integrated dual-core ARM Cortex A7 application CPU". So, based on that, yes, you should be able to port. What changes required is really hard to say. However OP-TEE has been successfully ported to various devices without much efforts. We have written a bit about it in the documentation [here](https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-do-i-port-op-tee-to-another-platform).

**Comment by dhruv77777** [comment]
Hey,

I have got the toolchain for this chip, in which the CROSS_COMPILER being used is **arm-poky-linux-gnueabi-**. 
Can we compile the Optee image with this toolchain? If yes, is there any reference from where i can get the about how to do this?

**Comment by jforissier** [comment]
> Hey,
> 
> I have got the toolchain for this chip, in which the CROSS_COMPILER being used is **arm-poky-linux-gnueabi-**. Can we compile the Optee image with this toolchain? If yes, is there any reference from where i can get the about how to do this?

https://optee.readthedocs.io/en/latest/building/gits/optee_os.html?cross-compile#cross-compile

**Comment by jenswi-linaro** [comment]
> Hey,
> 
> I am able to compile the optee default platform with the arm-poky-linux-gnueabi-. Now, i need to compile it for my chip platform (Autotalks). Can anyone please explain what are all the files needed to make it happen as i can see there is no official support for this platform from OPTEE.

This is a good start: https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-do-i-port-op-tee-to-another-platform
