### ISSUE TITLE
Why syscall_cryp_random_number_generate doesn't add TEE_MEMORY_ACCESS_ANY_OWNER when calling vm_check_access_rights 

### ISSUE THREAD

**Issue by mazhenke** [OP-TEE/optee_os#5970]
Hi,

I see that the function call of vm_check_access_rights() in syscall_cryp_random_number_generate() only has TEE_MEMORY_ACCESS_WRITE, and no TEE_MEMORY_ACCESS_ANY_OWNER added to the flags parameter:
![image](https://user-images.githubusercontent.com/16829846/233349141-fcabebdf-38b3-46ef-95bb-2485d036353d.png)

Buf for other syscall functions in the same file, they have TEE_MEMORY_ACCESS_ANY_OWNER, for example:
1. The nonce check in syscall_authenc_init.
2. The dst_data check in syscall_authenc_enc_final.

Missing TEE_MEMORY_ACCESS_ANY_OWNER in checking buf in syscall_cryp_random_number_generate(), the out buffer couldn't use shared memory(In my case, I am using dynamic share memory).

Appreciate for your reply, thanks!

**Comment by jforissier** [comment]
Hello @mazhenke, the reason is the `[out]` annotation in the GP Specification. It is `[out]` not `[outbuf]` meaning that shared memory is not allowed.

**Comment by mazhenke** [comment]
@jforissier Oh yes, thanks a lot
