### ISSUE TITLE
Giving more SRAM to OP-TEE on STM32MP157

### ISSUE THREAD

**Issue by johndoe31415** [OP-TEE/optee_os#5971]
This is a followup of the performance investigation in #5915. The summary is: OP-TEE, to run with good performance, would like to have around 384 kiB of RAM because otherwise frequent evictions of the pager make everything quite slow.

The STM32MP1 is a Cortex-A that has an internal Cortex-M4 companion. There is 256 kiB of SYSRAM which OP-TEE usually runs in (see STM RM0436 Rev 6 pg 158 for the memory map), starting at `0x2ffc0000` (until `0x2fffffff`). The SRAM which is usually dedicated to the M4 is split into four peripherals, SRAM1, SRAM2, SRAM3 and SRAM4. They have sizes 128, 128, 64, and 64 kiB. SRAM1 starts by default at `0x1000000`, BUT there is a RAM alias starting at `0x3000000` (right after the SYSRAM) in which SRAM1, 2, 3 and 4 are also mapped.

So, in theory, we could have a contiguous SRAM memory area of 384 kiB (SYSRAM + SRAM1), where `0x2ffc0000` to `0x2fffffff` is occupied by SYSRAM followed directly by the SRAM1 alias `0x30000000` to `0x3001ffff`.

Can we access SRAM1 from OP-TEE/TZ? I believe so. While for SYSRAM it is relatively straightforward by programming decprot of the ETZPC (see page 1117 of RM0436) , the four SRAMs are marked as "Securable IP" behind an "AHB stub". I.e., SRAM is connected to the AHB, but it is "extended w/ security". I currently am completely uncertain what this "stub" looks like or how it would work.

Later in the RM, page 1125, it lists SRAM to be connected to the MLAHB as a type 3 peripheral ("securable and MCU isolation support") with a default configuration of `0b11`. Table 92 on page 1120 shows type 3 peripherals wiht a decprot configuration of `0b11` are by default non-secure, but that means that secure write is possible (only that additionally non-secure write would also be possible).

So it is my understanding that in the default configuration after bootup, SRAM1 should be read/writable from the secure world (obviously this wouldn't yet be secure because the insecure world could also access the memory, but good enough for trying out if it works in principle).

My understanding of OP-TEE on the STM32MP1 is the following: the memory layout is so that OP-TEE starts at SYSRAM (`_start` at `0x2ffc0000`) and the pagable data is located in pages that follow right after SYSRAM (i.e., in my case `0x30000000` where coincidentally the actual physical RAM is located I want to use). As far as I understand the linker script is generated during the OP-TEE build and also the MMU is programmed according to the page layout.

So, in theory, I thought I could get away with something as simple as making OP-TEE believe that it simply has 384 kiB of SYSRAM; my thinking was that it would insert a 1:1 logical/physical MMU mapping on the address space from `0x2ffc0000` to `0x3001ffff` (SYSRAM + SRAM1) and would simply start the `.text_pageable` section at `0x30020000`.

Firstly, I was surprised that `CFG_TZSRAM_SIZE` defaults to `0x3f000` or 252 kiB (one page less than available). I'm assuming one page is reserved for the non-secure portion of the SYSRAM (I believe this is where `SCSI_SHM` is located?). Simply moving this up from `0x3f000` to `0x5f000` (380 kiB) did not work, since it then fails the compile time assertion:

```
	COMPILE_TIME_ASSERT(((SYSRAM_BASE + SYSRAM_SIZE) <= CFG_TZSRAM_START) ||
			    ((SYSRAM_BASE <= CFG_TZSRAM_START) &&
			     (SYSRAM_SEC_SIZE >= CFG_TZSRAM_SIZE)));
```

I believe this assertion is caused because it is assumed that OP-TEE only ever resides in SYSRAM. I took it out and moved `CFG_STM32MP1_SCMI_SHM_BASE` to `0x3001f000`, which then in turn causes the `SYSRAM_SEC_SIZE` to automatically become equal to `SYSRAM_SIZE`. This is what we want since we don't want a "SHM hole" in our memory, but rather a contiguous SRAM area (and the SHM possibly at the very end).

The next step was to attempt to configure the SRAM to allow only access from OP-TEE right in `init_stem32p1_drivers`: 

```
	res = stm32_firewall_set_config(MCUSRAM_BASE, 0x20000, sec_cfg);
	if (res)
		panic("Unable to secure SRAM1");
```

This panics, however, unable to secure SRAM1. In principle, this should work but I believe I'm missing something. If I do not try to secure SRAM1, I get stuck in a bootloop (not sure where it hangs, but eventually I run into a watchdog reset).

Again so much rabbit hole for relatively little effort. But I do think what I'm attempting should be doable and actually fairly easy. It would have great performance benefits on STM32MP1 and would certainly be worthwhile, I believe. Any support would be greatly appreciated to point me in the right direciton. Thanks!

**Comment by johndoe31415** [comment]
One more idea that I had: The SYSRAM is usually partitioned into `SEC` and `NS` parts where the `NS` parts is used for the SCMI SHM communication. SYSRAM can be partioned like this, but SRAM1 to the best of my knowledge cannot. So possibly this could be the reason for it hanging? I've tried disabling the SCMI PTA, but that didn't change anything, but also I'm entirely unsure how the SCMI subsystem works.

**Comment by etienne-lms** [comment]
Hi @johndoe31415,

You're right, there are some internal RAMs that can be assigned to secure world and their physical address ranges are contiguous SYSRAM. So yes, you can assign all thoses to OP-TEE and set, for example, `CFG_TZSRAM_SIZE` to 256kB (SYSRAM) + 128K+128K+64k+64K (SRAM1/2/3/4) ending up with 640kB of secure internal RAM. This is not the configuration currently released as STM32MP15 platforms initially expect one can use these SRAMs for companion Cortex-M4.

As you mention, using such a layout together with SCMI requires SCMI shared memory to not be located at SYSRAM last 4kB page. It could be moved to SRAM4 (if not secured) or simply SCMI config changed to use OP-TEE generic shared memory: remove `shmem` property (if used) from U-Boot/Linux DTS files and hack into _optee_os/.../plat-stm32/scmi_server.c_ to not map and use SYSRAM as SCMI shared mem.

To help you achieving this, I've created a (somewhat hacky) [change](https://github.com/etienne-lms/optee_os/commit/f0b728de4485362c1ef189e3193b805a0780570a) ([branch stm32-wider-sram](https://github.com/etienne-lms/optee_os/commits/stm32-wider-sram)) in my optee_os.git fork you can freely pick and use. Note that this change applies to mainline OP-TEE source tree, not the source tree you are using, but I think you'll find your way with. I did not think about upstreaming such a setup but if one thinks there is interest in, I could clean it up and submit to the upstream.

**Comment by johndoe31415** [comment]
Hi @etienne-lms , this looks *incredibly* helpful, thanks a bunch!

I've spent all night backporting your patch to 3.16, with somewhat success. I do have a cleanly compiling version that I believe could work, but unfortunately in the process I somehow broke DTB initialization of the device. Therefore, the RNG does not get initialized and the whole system panics. I'm currently trying to figure out from where this code is called and why it might fail.

The `stm32_etzpc.c` has seen major refactoring and looks very different in your version. Instead of cherrypicking pieces, I simply transplanted the whole driver to 3.16, which worked surprisingly well. I believe, however, that in there were some init calls that I also removed. Need to take a closer look.

My initial approach was not to worry about it and remove the RNG initialization altogether, butchering it just to attempt if it works at all. But this has led to more and more problems down the road (Panic: "E/TC:0 0 probe_dt_drivers:727 Probe sequence result: 0x80000000"). I need to fix initialization of DTB-declared peripherals properly to be able to test this.

It also appears you're on an MP13 while I'm on MP15, so I've had to change a few peripheral names. I also could have introduced an error there. Do I need to initialize *all* of them or can I just omit those that have a NS configuration since that should be the default, shouldn't it?

I've also been thinking about the SCMI memory. Using SRAM4 as NS doesn't seem too appealing to me because it would take away a whole 64 kiB block only for the single needed page. But doesn't the SYSRAM partitioning allow for S and NS parts to be configured independently? So the SCMI SHM page could be the very *first* page of SYSRAM (as opposed to be the last page), configured NS, and then following it there would be contiguously configured secure memory, with a nice granularaty (SYSRAM + 0-5 SRAMs). That would mean there is also more memory for the M4 if operation of both the A and M4 are required in the application.

**Comment by johndoe31415** [comment]
Hello again @etienne-lms! I am incredibly happy to report success 🥳

While I did not have a lot of luck in backporting to 3.16 (ran into more and more issues, first with the RNG, then with the DTB/clocks/etc), backporting to 3.19 was super easy, I could essentially just do a few manual tweaks of your patch https://github.com/etienne-lms/optee_os/commits/stm32-wider-sram and it worked out of the box.

The results are amost a TENFOLD increase in performance. I can now perform a full TLS handshake with P-256 based client certificates (keys in OP-TEE) in roughly 650ms when it previously took 5 seconds. This added RAM is an absolute GAMECHANGER and makes deployment of OP-TEE viable.

I cannot stress enough how important this is for practical purposes. This is a super, super valuable patch. I really hope it makes it into an official patchset (be it vanilla OP-TEE or the STM fork), since I do believe many people would like to sacrifice one or two chunks of MCUSRAM for this kind of performance gain.

Thanks again for your incredible support and patience. I love learning more about these technical issues and it certainly has given me significantly more insight into how it all fits together. Have a great weekend!

**Comment by ricardosalveti** [comment]
Nice, great stuff, it would be definitely useful to have the option of using the extra sram via config options upstream (we do have customers that could take advantage of using it).

**Comment by ch-f** [comment]
Great work! Thank you for sharing.

I'm facing a similar issue where a TLS connection takes way too long. However, I require the M4 firmware to remain operational for IPC mailbox data sharing with Linux and for controlling some I2C stuff.

So is it possible to allocate only SRAM3 and SRAM4 to OP-TEE?

By doing this, I hope to improve the TLS connection speed, even if just slightly (+128K RAM). What do you think?
