### ISSUE TITLE
TEE_GetSystemTime(...) not compliant with TEE core API spec.

### ISSUE THREAD

**Issue by zlhk100** [OP-TEE/optee_os#5973]
1.  As per internal TEE core API spec:
void TEE_GetSystemTime([out] TEE_Time* time );
//  time: A value that SHOULD indicate Filled with the number of seconds and milliseconds since
// midnight on January 1, 1970, UTC.

But actually xtest returns the value, which is since POR.
How to reproduce:
$xtest -t regression 1006

regression_1006 Test Basic OS features                                                                           
Getting properties for implementation                                                                        
**system time 333.372**    

2. Actual platform implementation can be 
./core/arch/arm/kernel/tee_time_arm_cntpct.c:
REGISTER_TIME_SOURCE(arm_cntpct_time_source).

Which seems aligned with the xtest result.

3.  How secure is this implementation as it claims?   secure timer by utilizing CNTPCT processor physical counter.   
static const struct time_source arm_cntpct_time_source = {
        .name = "arm cntpct",
        **_.protection_level = 1000,    //   how secure is it?_**
        .get_sys_time = arm_cntpct_get_sys_time,
};

**Comment by etienne-lms** [comment]
@zlhk100, I think you are right.
Indeed, since GPD TEE Intenral Core API v1.1, time protection level 1000 requires a calibrated time origin. This requires a secure RTC or like support from the platform. I think we missed that in arm/cntp time driver when we moved from API v1.0 (that did not require this time origin) to v1.1 and onwards.

**Comment by jforissier** [comment]
@etienne-lms so it sounds like two fixes are required: (1) query the NW RTC clock to obtain the offset to be applied to the CNTPCT in order to return a number of seconds since the epoch, as specified; and (2) downgrade the protection level.

**Comment by etienne-lms** [comment]
I agree for (2).

Regarding (1), I think there is a bit more to do: use secture storage to ensure time does not rollback across reboots. That would apply to both `ree_time_source` and `ree_time_source`.

**Comment by jenswi-linaro** [comment]
Using secure storage for this seems a bit much, it means writing each time someone is querying the time.
We need to depend on a secure RTC or another way to restore the time at boot.

**Comment by etienne-lms** [comment]
A secure RTC would definitly help but I think we also need to have another look at required relationship between time and secure storage from GP TEE spec view.

Reading again (and again and again) the GP spec, this issue affects both protection levels 100 and 1000, so I think downgrading it for `arm_cntpct_time_source` is not relevant here (despite my [above comment](https://github.com/OP-TEE/optee_os/issues/5973#issuecomment-1521958629)).

**Comment by zlhk100** [comment]
It's an interesting design decision for op-tee to switch to different platform specific implementation based on different hardware specifications:    
eg.   actual platform might support one of following RT timer capabilities 

Case 1.  As @jenswi-linaro mentioned, secure coin battery backed RTC capability(physical tamper proof) owned by TZ.
Case 2.  Regular coin battery backed RTC only. 
Case 3.  Not battery backed RTC and device's actual system time can be sync'ed from cloud service eg. NTP.

How can OPTEE provide a framework to allow implementing platform specific EPOC based secure timer for TEE_getSystemTime(...)?    

For sure, case 1. will present smallest attack surface since everything is owned by TEE.
However,  OP-TEE also need to provide a framework to accommodate Case 2/3 with minimum attack surface and time integrity protection.

**Comment by zlhk100** [comment]
we are discussing different options offline.   thanks.
