### ISSUE TITLE
no key allocated before crypto_acipher_free_rsa_public_key

### ISSUE THREAD

**Issue by stefenzhou** [OP-TEE/optee_os#5979]
For patch https://github.com/OP-TEE/optee_os/commit/8a697013f714256c0b15708023fd45298f95b658.
Eg: 
For error handle: if (shdr->magic != SHDR_MAGIC),
There is no key allocated. But it will call crypto_acipher_free_rsa_public_key. Is it OK?

	if (shdr->magic != SHDR_MAGIC)
		return TEE_ERROR_SECURITY;
		goto err;

	if (TEE_ALG_GET_MAIN_ALG(shdr->algo) != TEE_MAIN_ALGO_RSA)
		return TEE_ERROR_SECURITY;
		goto err;
.......

err:
        res = TEE_ERROR_SECURITY;
        FTMN_SET_CHECK_RES_NOT_ZERO(&ftmn, err_incr * FTMN_INCR0, res);
out:
        FTMN_CALLEE_DONE_CHECK(&ftmn, FTMN_INCR0, FTMN_STEP_COUNT(2), res);
        crypto_acipher_free_rsa_public_key(&key);
.....

@jenswi-linaro

**Comment by jenswi-linaro** [comment]
Yes, that's supposed to be harmless.

**Comment by stefenzhou** [comment]
Should we keep this way of writing or we need to re-modify the code? 
If not, could you tell me reason? I have some confusion about this.
Thank you.

**Comment by jforissier** [comment]
Perhaps we could add a comment on the `crypto_acipher_free_rsa_public_key()` stating that it is valid to pass a `struct rsa_public_key` containing NULL pointer(s). It is quite similar to the libc `free()` function.

**Comment by stefenzhou** [comment]
Yes, I think it should be better to add comment: 
https://github.com/OP-TEE/optee_os/blob/master/core/drivers/crypto/crypto_api/acipher/rsa.c#L60

**Comment by stefenzhou** [comment]
If it is no any issue, I will close this issue. Is it OK?
Thanks.
@jenswi-linaro  @jforissier

**Comment by jforissier** [comment]
@stefenzhou yes. If you would like to add a comment you may create a pull request.
