### ISSUE TITLE
OP-TEE does not work on the current ARM Foundation Model

### ISSUE THREAD

**Issue by oliviermartin** [OP-TEE/optee_os#598]
The OP-TEE build scripts rely on ARM Trusted Firmware v1.1 (+ patches) from February 2015 - see https://github.com/OP-TEE/manifest/blob/master/fvp_stable.xml.

This version of the ARM Trusted Firmware does not work on the current ARM Foundation Model (ARM V8 Foundation Platformr0p0 (platform build 9.5.40)).
![atf-on-current-foundation](https://cloud.githubusercontent.com/assets/5757507/11880058/c9872db8-a4f6-11e5-9789-b877b4d55fa3.png)

Updating the ARM Trusted Firmware to the latest (in progress) release https://github.com/ARM-software/arm-trusted-firmware/releases/tag/v1.2-rc0 with the flag `ARM_TSP_RAM_LOCATION=tdram` instead of `FVP_TSP_RAM_LOCATION=tdram FVP_SHARED_DATA_LOCATION=tdram` prevents OP-TEE OS to start on the current Foundation model.
After doing some debugging (limited debugging because of the limitation of the ARM Foundation Model), I found OP-TEE starts but fails to initialize the stack and fails when `console_init()` pushes registers into the stack.

I found an old Foundation model that make the OP-TEE software stack.
But unfortunately, there is no (easy) way on ARM Connect to identify the ARM Foundation Model (I already raise an issue to ARM Ltd). So, it is quite complicated to make OP-TEE works on the ARM Foundation Model.

/cc @danh-arm

**Comment by jenswi-linaro** [comment]
Does this https://github.com/jenswi-linaro/arm-trusted-firmware/tree/optee_paged_151203 work better?

**Comment by oliviermartin** [comment]
I have not tried yet. Are these changes hacks? Or you are planning to send these changes to the ARM Trusted Firmware project?

**Comment by jenswi-linaro** [comment]
Yes they are hacks in the sense the we don't plan to upstream them in the current state. I made those changes over a year ago (and have been rebasing them a couple of times) when we had to change the format of the OP-TEE binary in order to enable paging.

There's some work ongoing to fix this.

**Comment by oliviermartin** [comment]
The v1.2 of ARM Trusted Firmware has been released yesterday. Maybe you could rebase your patches on this latest stable release.

**Comment by jenswi-linaro** [comment]
OK, I'll do that.

**Comment by jenswi-linaro** [comment]
OK, I have the rebased patches here https://github.com/jenswi-linaro/arm-trusted-firmware/tree/optee_paged_armtf_v1.2

**Comment by jbech-optee-adm** [comment]
Question has been answered and we are now the (default) [branch](https://github.com/linaro-swg/arm-trusted-firmware) we're currently using has been rebased to v1.2. Feel free to re-open the issue if you have more questions on the same topic.
