### ISSUE TITLE
Questions about TA concurrency

### ISSUE THREAD

**Issue by erhade** [OP-TEE/optee_os#5983]
By reading the documentation I learned that OPTEE_OS does not implement scheduling for TA, scheduling relies on REE scheduling for CA.
I would like to know if the following ideas are correct:

1. If there are multiple CAs issuing `TEEC_InvokeCommand` at the same time, only one CA invocation will be executed in the TEE, and all other invocation threads will sleep. Until the CA closes the session (`TEEC_CloseSession`) or the CA is blocked, the `TEEC_InvokeCommand` of the other CAs will be executed. My guess is that TEE adds a spin lock to the execution of a single CA call.
2. As described in 1, is it understood that the TA execution in OP-TEE will not be concurrent？
3. Faced with multiple concurrent CA requests, is the execution of TA in OP-TEE always on one CPU core?
4. If an interruption (RPC returns and availablity of interrupt to return to normal world) occurs while the trusted thread is executing, will optee_os still be on the original CPU core when it returns to the execution of trusted thread?

**Comment by erhade** [comment]
@jforissier 
Thank you for your reply.
1. My own experiments are a bit different from what you said. I found that the different instances are **not concurrent**, when one instance closes the session, the commands of the other instance are executed. This is also true for TAs with different UUIDs. I think this should be concurrent to make sense.
2. Single-instance and multi-session mode is **concurrent**. This one makes me wonder, for the sake of thread safety of TAs, this should not be concurrent in this case.

**Comment by etienne-lms** [comment]
@erhade, have a look at daeea0369d17a7473953eecd6b5af4735ec12fcb and try `CFG_CONCURRENT_SINGLE_INSTANCE_TA=y`. That should address your issue IIUC.

**Comment by jforissier** [comment]
@etienne-lms good catch I did not remember about this limitation by default.

**Comment by erhade** [comment]
@etienne-lms @jforissier 
Thank you for the link you gave.
However, this doesn't seem to be the question I was asking. the CFG_CONCURRENT_SINGLE_INSTANCE_TA option doesn't seem to affect concurrency in multiple sessions.
What I am asking is:
1. does enabling **single instance and multiple sessions** are running concurrently create a thread safety issue for TA execution.
2. I observed that concurrency is not default between different instances, and between TAs with different UUIDs. Does this affect performance?

**Comment by etienne-lms** [comment]
@erhade, are you asking information on how OP-TEE works or do you have a use case in mind that you cannot get executed?

**Comment by erhade** [comment]
@etienne-lms 
I just want to ask how OP-TEE works.
Based on what you just said, I already understand that the execution of TA is thread-safe. But could you answer my second question:
I observed that concurrency is not default between different instances, and between TAs with different UUIDs. When one instance closes the session, the commands of the other instance are executed. Does this affect performance?

**Comment by erhade** [comment]
@etienne-lms 
Let me be more precise:
I observed that if I execute two CAs concurrently on the REE side, the second CA needs to wait for the first CA's open_session->invoke_command->close_session to finish executing before it can be executed. Although the execution of each CA call (eg. invoke_command) by the TA is atomic, it gives me the impression that the execution of a series of calls (i.e. open_session->invoke_command->close_session) by the TA to the CA is also atomic.

**Comment by jforissier** [comment]
What are the `TA_FLAGS` for your TA(s)?

**Comment by erhade** [comment]
@jforissier 
TA_FLAG_EXEC_DDR

**Comment by etienne-lms** [comment]
Such a TA is a so-called multi-instance. Multi-instance TAs are individual TAs, each supporting only a single session by definition as each new session open toward that TA creates a new instance of the TA.
The instances of such a TA are fully concurrent with each other.
