### ISSUE TITLE
Attestation on OP-TEE

### ISSUE THREAD

**Issue by kunisuzaki** [OP-TEE/optee_os#5984]
I found the [PTA code](https://github.com/OP-TEE/optee_os/blob/eb238769ae57603e501b83d0c0129f60f6512f3f/core/pta/attestation.c) for attestaion on OP-TEE.
However, there is no document. [OP-TEE documentation](https://optee.readthedocs.io/en/latest/) has no explanation.
Please tell me how to use the attestaion.
I aslo want to know how to set up a verifier.

**Comment by jewcomm** [comment]
Hi! 
Look at the definitions of the following [file](https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/include/pta_attestation.h) 
You can also see my similar question https://github.com/OP-TEE/optee_os/issues/5942

**Comment by kunisuzaki** [comment]
Thank you. @jewcomm
The test code is included in the "xtest"!
The comments say 

> /*
>   Verification of the output of the attestation PTA
>  (If hash != NULL) check buf contains the expected hash
> (If OpenSSL is available) Check that the signature is valid
> */

Could you tell me how to setup a attestaion key and verify the signature using OpenSSL?
