### ISSUE TITLE
OPTEE Support for Samsung Exynos chip

### ISSUE THREAD

**Issue by dhruv77777** [OP-TEE/optee_os#5996]
Hey there, 

Is there any support or porting information available for Samsung Exynos chip?
If no, is there any chance that optee support will be there in near future?

**Comment by jbech-linaro** [comment]
Not what I'm aware of, the list [here](https://optee.readthedocs.io/en/latest/general/platforms.html) is up-to-date I believe. I'm not aware of anyone working with adding (official) support for it in the near future. Some companies upstream the support, some don't.
