### ISSUE TITLE
Missing memory barrier for io API = access to HW registers mapped as "device" memory ?

### ISSUE THREAD

**Issue by patrickdelaunay** [OP-TEE/optee_os#5997]
Hi,

I want a recommendation about the barriers in OP-TEE driver and usage of the "IO" API defined in ./core/include/io.h

for example:

      static inline void io_write32(vaddr_t addr, uint32_t val)
      {
           *(volatile uint32_t *)addr = val;
      }

      static inline uint32_t io_read32(vaddr_t addr)
      {
      	return *(volatile uint32_t *)addr;
      }

If I correctly understood the coding rule on OP-TEE, this IO api MUST be used to access to register of IO device, mapped as "device" memory for ARM as it is done in Linux (IO api defined in arch/arm/include/asm/io.h) or in U-Boot (./arch/arm/include/asm/io.h).

But today it is only a direct access to the memory
=> the required memory barrier are NOT managed at this level (as it is done in Linux kernel and in U-Boot)
=> no guaranty of effective write in the HW / no guaranty of order on the reception by the HW.

My question :
-------------------

the required memory barrier need to be added in ANY driver when it is needed  ?
=> I don't see any advice of this IO API or the need of memory barrier in the OP-TEE documentation.

Or do you think the required memory barrier can be added in these OP-TEE IO functions ?
as it is done in Linux kernel or in U-Boot....

and perhaps add a relaxed version of these API when memory barrier is not required (for optimization, to be use when coder know that it possible).

See also https://www.kernel.org/doc/Documentation/memory-barriers.txt
=> KERNEL I/O BARRIER EFFECTS
- writeX => version with memory barrier
- writeX_relaxed => version without memory barrier

I think that if it is done in OP-TEE IO API level, it should be more simple to write / port drivers without low barrier knowledge 
=> a little reduction of performance (barrier are use by default)
=> No issue difficult to debug (caused by missing barrier).

for example:

      static inline void io_write32(vaddr_t addr, uint32_t val)
     {
	     dmb();
	     *(volatile uint32_t *)addr = val;
     }
      static inline uint32_t io_read32(vaddr_t addr)
      {
         uint32_t  __v =  *(volatile uint32_t *)addr;
         dmb();
         return __v;
      }

But If you think it is a bad proposal, the barrier usage with IO api should be explained in driver porting guide of documentation and I will add the missing barrier in the STM32MP13 / STM32MP15 drivers.

Regards.

Patrick

**Comment by etienne-lms** [comment]
Hi @patrickdelaunay, 
Thanks for the question. Note the same question could be raised in TF-A (old OP-TEE companion) that uses very similar `mmio_read_32()` and friends helper functions, see [mmio.h](https://review.trustedfirmware.org/plugins/gitiles/TF-A/trusted-firmware-a/+/refs/tags/lts-v2.8.6/include/lib/mmio.h).

IMHO it should be the responsibility of the drivers implementation to place memory barriers where needed rather than enforcing all `io_read32()` and like functions do include such barriers. Maybe some helper macros/inline functions could help for memory barrier-ed IO accesses like `iomb_read32()`, `iomb_setbits32()` etc.... 
By the way, for such helper functions, which barrier to use: `dmb()` on reads and `dsb()` on writes? Maybe rather `dsb_ishst()` on writes (see [inline comment about `OPTEE_SMC_NSEC_CAP_UNIPROCESSOR`](https://github.com/OP-TEE/optee_os/blob/3.21.0/core/arch/arm/tee/entry_fast.c#L70-L81)).

**Comment by jenswi-linaro** [comment]
Hi Patrick,

Thanks for bringing this up. The memory barrier isn't expensive if I've understood it correctly so using it by default in those functions should be fine. If you don't mind please create a pull request for this.

These memory barriers need a different mental model compared to for instance `dsb()`. What you guarantee with a `dmb()` is that an eventual write will not happen _before_ the `dmb()` and vice versa with a read, we can guarantee that the read will not happen after the `dmb()`. It might be worth giving a hint about that somewhere.

By the way, would it make sense to introduce `dmb_st()` and `dmb_ld()` for better precision?

**Comment by jenswi-linaro** [comment]
Etienne, you have a point. We should probably have specialized functions instead so the correct barrier is used.

**Comment by patrickdelaunay** [comment]
>  Maybe rather `dsb_ishst()` on writes

https://developer.arm.com/documentation/dui0489/c/arm-and-thumb-instructions/miscellaneous-instructions/dmb--dsb--and-isb

inner shareable ? => I think it is not the correct memory barrier for device memory (not cacheable)

but barrier is an big source of error => I prefer use the same code that other to avoid issue

I use dmb as in U-Boot = ./arch/arm/include/asm/io.h

#define __iormb()	dmb()
#define __iowmb()	dmb()

in Linux it is more difficult to follow....

in io.h:

#define __iormb()		rmb()
#define __iowmb()		wmb()

in barrier.h

#define rmb()		dsb()
#define wmb()		__arm_heavy_mb(st)

**Comment by etienne-lms** [comment]
> inner shareable ? => I think it is not the correct memory barrier for device memory (not cacheable)

I think you're right. My mistake.

> The memory barrier isn't expensive if I've understood it correctly so using it by default in those functions should be fine.

A point to @patrickdelaunay. If that does not cost much, maybe it's worth adding dmb's to these functions, and introduce `io_raw_read32()` for non-barrier-ed accesses.

**Comment by GseoC** [comment]
Hi,

Looking at ARM documentation, default behavior for dmb()/dsb() is full-system DMB/DSB operation, which seems to be the appropriate behaviour for such API. In this case, there's no need to provide an option.

**Comment by patrickdelaunay** [comment]
> Etienne, you have a point. We should probably have specialized functions instead so the correct barrier is used.

Yes, I see 2 solutions

1/  Add memory barrier in existing functions (= iomb_read32()))
    + new function without memory barrrier to used when necessary (= io_read32_relaxed())
     it is the solution chosen by Linux / U-Boot
 
2/ keep existing function without memory barrier (= io_read32()) 
    + new function with memory barrier (= iomb_read32())
    it is the proposition done by Etienne 

It is depending if existing function( the more simple = io_read32()) )  which already used by driver should use memory barrier to avoid issue
=> if the answer is yes, we can correct them just by modify the io API (option 1)
=> what it the confidence on the driver code quality; the barriers will be really be added when necessary !

PS: in Linux / U-Boot the simple IO function (writeX function not relaxed one) use memory barrier
       because in many drivers the required memory barrier was missing 
       and that cause problem difficult to investigate (write on several IP  sent on several BUS: order is not respected)
       => if I remember right, the barrier are added by default to avoid common issues
            and let the driver to chose the API without barrier for optimization (but only when it is possible)

I prefer 1/ to have the save behavior in OP-TEE (and perhaps also in TF-A) to easy port of driver to OP-TEE
But if Etienne prefer the solution 2/ to avoid possible impact on existing drivers

I can also propose something for the 2 solutions....
but I don't know that is the expected default behavior in OP-TEE / TF-A

Patrick

REF = https://lists.denx.de/pipermail/u-boot/2010-December/084123.html  (U-BOOT)
REF = https://marc.info/?l=git-commits-head&m=128054515909668    (LINUX)

**Comment by jenswi-linaro** [comment]
Devices are mapped in OP-TEE as Device-nGnRE, that is, non-Gathering, non-Reordering, and with Early Write Acknowledgement for LPAE and AArch64. For short descriptor tables, AArch32/Armv7, we use Device that is from what I understand as compatible as possible. Reads and writes are supposed required to be done in order on the peripheral. What role does the `dmb` instruction play here?

**Comment by patrickdelaunay** [comment]
Hi Jens,

I just ask after code review and with my old remembers of ARM achitecture training.
It is only a potential issue => I have today no use-case which demonstrate it. 

But perhaps miss something in memory device and ARM specification, so any ARM expert advice is welcome.

But for me the issue is for the "Early Write Acknowledgement" when we have 2 consecutive writes for 2 different HW devices; the request are only ordered at the output of the CPU (up to AXI bus), 
not for the peripheral BUS up to the device (it is issue around outer shareable).

=> no guarantee that each WRITE request reach the HARDWARE device is the same order
     it is depending of the PATH of followed by the requests up to the IPs 
     (because you can have several bus and bridge)

But perhaps I make a error here.... 
I don't check again the MMU configuration / the ARM architecture documents

Example for STM32MP:

- Write 1) SYSCFG to enable feature of IP 'A'
- Write 2) Write in RCC => enable clock of IP 'A'
- Write 3) Write in register of IP 'A'

at the interface between CPU and main bus (AXI) the write order is respected => 1) 2) 3)
and with cache and core optimization, the 3 request are sent in 3 consecutive request on the AXI bus 
(at the device memory is buferreable).

But the patch to reach the 2 IP SYSCFG and RCC is slower to path to reach IP 'A'
(we have some bridge to reach the AHB and APB bus used to access to this 'IP' registers and we have slower frequency on this bus peripheral bus).

So IP 'A' received the request '3' before the previous request is received by SYSCFG and RCC 
=> the request can't eb treated as but IP 'A4 is not yet clock / not activated by SYSCFG.

I know 2 best practices to insure the write sequence between several IP on different bus but it need to be respected by any developer in drivers and they need to know this kind of problem.

Solution A) => always request read on a register after a write when the write result need to be waited
                          as the order is preserved the next write on only done when write / read is performed

- Write 1) SYSCFG to enable feature of IP 'A'
- Read SYSCFG register (FAKE => don't treat the read value)
- Write 2) Write in RCC => enable clock of IP 'A'
- Read RCC register (FAKE => don't treat the read value)
- Write 3) Write in registe of IP 'A'

we have guarantee that write order is respected at hardware level, for each IP

Solution B) Add barrier to guarantee the effective WRITE on the bus up to device (waiting ACK doen by IP)

- Write 1) SYSCFG to enable feature of IP 'A'
- barrier 
- Write 2) Write in RCC => enable clock of IP 'A'
- barrier 
- Write 3) Write in register of IP 'A'

PS: we have the same issue if the READ is followed by a WRITE on 2 different IP (and read value is depending of the write action)

- Write 1) in SYSCFG to enable feature of IP 'A'
- Read 2)  in register of IP 'A'
- Write 3) in SYSCFG to enable feature of IP 'A'

=> what append if the Read 2) is received by hardware IP 'A' is received before 1) or after 3)
     for me the read value is invalid

If you confirm that it is a potential issue,  I want to have a recommendation for access to register mapped "device" 
(for OP-TEE and perhaps the TF-A also as they share the same API)

1) to add barrier in low level IO API (as it is done in Linux / U-Boot)
    to avoid issue for each user of the IO API  used to access to IP registers 
    => the only recommendation for driver is to use this IO API to access register mapped as "device"
 
2) or to force every contributor to add in the drivers the required read request or barrier (to call API with barrier as proposed by Etienne) when it is recommended.
    => each driver contributors need to know the best practice for register access and code them correctly in driver.

P: in U-Boot and in Linux kernel the recommendation to the IO function (readX/writeX) to access register by default.
      For optimization,the relaxed/raw version of these API (without memory barrier) can be used.

Regards

Patrick

**Comment by patrickdelaunay** [comment]
Hi,

I think that using dmb is enough for device memory with default level SY = system, as it is done in U-Boot,

Data Memory Barrier (DMB):
  This instruction ensures that all memory accesses in program order before the barrier are observed in the system 
  before any explicit memory accesses that appear in program order after the barrier. It does not affect the ordering of 
  any other instructions executing on the core, or of instruction fetches.

DMB is required to be sure that register operation is observable for the required shareable domain.
=> register write really reach the device with SY barrier because it is observable by all master in the system.

refrence => 
https://developer.arm.com/documentation/den0013/d/Memory-Ordering/Memory-barriers
file:///local/home/frq07632/Downloads/Barrier_Litmus_Tests_and_Cookbook_A08.pdf
https://community.arm.com/support-forums/f/architectures-and-processors-forum/11846/dsb-and-dmb
https://stackoverflow.com/questions/15491751/real-life-use-cases-of-barriers-dsb-dmb-isb-in-arm
https://linux-arm-kernel.infradead.narkive.com/xcjDLY8l/dmb-and-dsb-for-linux-arm-arch-6

but the dsb is used for Linux !?
that force more restriction :

Data Synchronization Barrier (DSB)
  This instruction forces the core to wait for all pending explicit data accesses to complete before any additional 
  instructions stages can be executed. There is no effect on pre-fetching of instructions.

Patrick

**Comment by jenswi-linaro** [comment]
I believe that a DSB barrier should be needed in solution B above, due to the side effects.

Which barrier is needed seems to depend on the platform, device, and situation in question.

I think we should keep the io_writeXX() and io_readXX() as they are (I'm tempted to re-implement them using `READ_ONCE()` and `WRITE_ONCE()` instead to get rid of the volatile).

We can add a new set of functions for instance, io_writeXX_barrier() and io_readXX_barrier(), for convenience.

Doing it the other way around and checking each caller if it can be converted to io_writeXX_relaxed() or not isn't feasible.
