### ISSUE TITLE
Right way get access to Linux kernel memory

### ISSUE THREAD

**Issue by jewcomm** [OP-TEE/optee_os#6003]
Hello, i want to access system call table from OPTEE.

Now i use next sequence: 
1. Linux kernel module, that gets the physical address(PA) of the syscall table.
2. Custom PTA, that receives from 1 PA of the table, and translate to virtual address(VA)
```c
core_mmu_add_mapping(MEM_AREA_RAM_NSEC, PA, size_syscall_table * sizeof(unsigned long));
unsigned long * VA = phys_to_virt(PA, MEM_AREA_RAM_NSEC, sizeof(unsigned long) * size_syscall_table);
```

and passed this VA to my TA app, and saved in TA. The address translation is performed only once.

Its correct way? Or should I convert PA to VA every time my TA is called?

**Comment by etienne-lms** [comment]
If your PTA calls `core_mmu_add_mapping()`, calling it once is enough, that mapping is persistent. The function already returns the virtual base address of the mapped area, no need to call `phys_to_virt()` afterward.

Note your scheme will work only if your Linux kernel driver knows the effective physical address you want to reach, that is it is not an IPA (intermediate physical address) some hypervisor could have mapped to some different effective physical address. In such case, the Linux kernel driver needs to pass the memory area as a MEMREF parameter at each invocation of the PTA and the memory area is mapped in OP-TEE only during execution of the invoked PTA command.
