### ISSUE TITLE
PKCS#11 destroy object can cause access to freed pointer in multisession access

### ISSUE THREAD

**Issue by vting-seq** [OP-TEE/optee_os#6005]
If there are two PKCS#11 sessions running, a token object being destroyed in one of those sessions can result in the access of that freed pointer in the other session causing a data-abort.

The token object database is global w.r.t all sessions (see init_persistent_db).  In object.c : entry_find_objects_init, the global token database is scanned for matching objects.  If one is found (and a handle to it is not found in the session), a handle is created for it, and the raw pointer is added to the handle list for that session.

The problem is that if the _other_ session destroys that token object, that pointer (and handle) should no longer be valid.  If the session is in the middle of using that handle - pkcs11_handle2object will still return that destroyed pointer - leading to a data-abort.

I can sort of fix this by iterating through **all** the sessions and doing a handle_put for the object (i.e. removing the handle --> pointer reference) in destroy_object.  The other session using the handle will then return an error (invalid handle) the next time it is used.  However I am not sure if it is really safe, as it might still be possible if one session has already converted the handle to the pointer, during which the object is destroyed.

To see this behaviour, in one session:

```
C_FindObjectsInit(session_0,template,1);
C_FindObjects(session_0,&object,1,&objcount);

------(second session)----------------------->  C_DestroyObject(session_1,object)

C_GetAttributeValue(session_0,object,objtemplate,objtemplatecount);  <---- will cause data-abort
```

Note:  object must be a persistent token object.

**Comment by etienne-lms** [comment]
You are right. There is an issue here.
I've create a test case to trigger the issue (https://github.com/OP-TEE/optee_test/pull/665) and a change in optee_os to addressed it (https://github.com/OP-TEE/optee_os/pull/6018).
