### ISSUE TITLE
Is the value of the TEE_ALG_X448 macro correct?

### ISSUE THREAD

**Issue by bhLou** [OP-TEE/optee_os#6008]
Hi, experts,
Now，the x25519 algorithm related macro are ：
    #define TEE_ALG_X25519                            0x80000044
    #define TEE_TYPE_X25519_PUBLIC_KEY      0xA0000044
    #define TEE_TYPE_X25519_KEYPAIR            0xA1000044

but , the x448  algorithm related macro are ：
    #define TEE_ALG_X448                             0x80000045
    #define TEE_TYPE_X448_PUBLIC_KEY       0xA0000049
    #define TEE_TYPE_X448_KEYPAIR             0xA1000049
I think, the TEE_ALG_X448  value maybe 0x80000049?

**Comment by etienne-lms** [comment]
The value is defined by GlobalPlatform TEE Internal Core API specification, refer to Public Release v1.3.1 page 241 and 243.
