### ISSUE TITLE
How to link exist static lib to ta?

### ISSUE THREAD

**Issue by WangYanjiong** [OP-TEE/optee_os#601]
Hi,

How to link exist static lib to ta? 

Thanks a lot.
BR.

**Comment by pascal-brand-st-dev** [comment]
Hello,

Please add something like the following in the Makefile of your TA:

    include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
    ldargs-$(binary).elf += <mylib>

**Comment by WangYanjiong** [comment]
Thanks Pascal.

Is it ok to use LDADD += <mylib> or LDFLAGS += <mylib>? These seem better since we can control whether the lib linked after or before objs.

**Comment by jenswi-linaro** [comment]
`LDADD` is what I would have used, you normally want to list the libraries after the object files.

Regards,
Jens

**Comment by jbech-optee-adm** [comment]
Question has been answered and therefore I'm closing this issue. Feel free to re-open if you have further questions on the same topic.

**Comment by ryankumar** [comment]
how can i creat a generic api for trusted application and interface with tzcode????

**Comment by jbech-linaro** [comment]
@ryankumar , to answer your question, there is already a generic API for the TA's. That is what GlobalPlatform has defined in the GP TEE Internal Core API that you can find at [globalplatform.org](https://globalplatform.org/specs-library/?filter-committee=tee). In the future, please avoid taking a random issue when asking questions. Either ask in an existing issue related to your question or please open a new issue.

**Comment by piachristel** [comment]
I think this issue (title) perfectly fits the problem I am currently facing. Therefore, I allow myself to reopen it.

I have tried to link a static library to a TA (based on the hints of the issues related to that topic and to the documentation (https://optee.readthedocs.io/faq/faq.html?highlight=link%20library#q-how-do-i-link-a-library-into-a-trusted-application).

1. 
I have added the library `add` to the `ta/library` dir. Then in `ta/library/add` I have created the static library with
```
aarch64-linu-gnu-gcc -c *.c
ar -cvq mylib.a *.o
```
And then copied the mylib.a file into the `ta/library`dir.
2.
In `ta/sub.mk`, I have added:
```
libdirs += library/
libnames += mylib
libdeps += libmylib.a
```
3.
In `ta/Makefile` 
below `CPPFLAGS...`, I have added:
`LDFLAGS += -static`
and below `-include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk`, I have added:
`ldargs-$(binary).elf += mylib`
4.
But then running `make buildroot` gives the following error:
```
make[3]: Nothing to be done for 'all'.
Building /home/ubuntu/optee-project/out-br/build/optee_examples-1.0/hello_world_lib/ta/Makefile
make[3]: *** No rule to make target 'libmylib.a', needed by 'out/8aaaf200-2450-11e4-abe2-0002a5d5c51b.elf'.  Stop.
package/pkg-generic.mk:229: recipe for target '/home/ubuntu/optee-project/out-br/build/optee_examples-1.0/.stamp_built' failed
make[2]: *** [/home/ubuntu/optee-project/out-br/build/optee_examples-1.0/.stamp_built] Error 2
Makefile:16: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/ubuntu/optee-project/out-br'
common.mk:201: recipe for t
```
I have tried different options for `mylib` in `ldargs-$(binary).elf +=`.
But none of it helped.
What I am missing?
