### ISSUE TITLE
GP131:Reasons for deprecating TEE_ALG_ECDSA_P* and using TEE_ALG_ECDSA_SHA*

### ISSUE THREAD

**Issue by mrnuclear8** [OP-TEE/optee_os#6011]
Hi,
In this revision, there is a change of macro definition TEE_ALG_ECDSA_P* to TEE_ALG_ECDSA_SHA*:[GP131: Add TEE_ALG_ECDH_DERIVE_SHARED_SECRET and TEE_ALG_ECDSA_SHA* · OP-TEE/optee_os@fe2fd3f (github.com)](https://github.com/OP-TEE/optee_os/commit/fe2fd3ff46c0bada3dc9b2ae8c1025bfd8f57f3f)

The reason for the change stated on page 358 of the GP131 document is written: **ECDSA algorithm identifiers should be tied to the size of the digest, not the key. The key size information is provided with the key material.**

I see that the OPTEE-OS code simply modified the macro definition, OPTEE's ECDSA algorithm identifier is not tied to the size of the digest, is tied to the size of the key, seems to violate the GP131, for example, when calling the GP interface TEE_AllocateOperation, TEE_AsymmetricSignDigest.

The following is an excerpt of the code

1.Obviously, in OPTEE,  ECDSA algorithm identifiers is tied to the key size, **TEE_ALG_ECDSA_SHA512** should not be bound to the ECC521 key size,  you should only check if **maxKeySize** is greater than the minimum ECC key length supported by OPTEE.

```
TEE_Result TEE_AllocateOperation(TEE_OperationHandle *operation,
                 uint32_t algorithm, uint32_t mode,
                 uint32_t maxKeySize)
...
	case TEE_ALG_ECDSA_SHA512:
	case __OPTEE_ALG_ECDSA_P521:
	case __OPTEE_ALG_ECDH_P521:
		if (maxKeySize != 521)
			return TEE_ERROR_NOT_SUPPORTED;
		break;
```

2.Obviously, ECDSA algorithm identifiers is tied to the key size,  **TEE_ECC_CURVE_NIST_P384**  be bound to **TEE_ALG_ECDSA_SHA384**, OPTEE's code logic does not pay attention to the digest length that needs to be signed, for example, I use SHA256withECDSA and ECC384, the digest length passed in is 256 bit both 32 bytes, but in OPTEE, the algorithm used is **TEE_ALG_ECDSA_SHA384**, In the GP131 document, section 6.7.2 TEE_AsymmetricSignDigest, it is written：**Where a hash algorithm is specified in the algorithm, digestLen SHALL be equal to the digest length of this hash algorithm.**

```
TEE_Result TEE_AsymmetricSignDigest(TEE_OperationHandle operation,
                    const TEE_Attribute *params,
                    uint32_t paramCount, const void *digest,
                    uint32_t digestLen, void *signature,
                    uint32_t *signatureLen)
...
core\lib\libtomcrypt\ecc.c :: _ltc_ecc_sign

case TEE_ECC_CURVE_NIST_P384:
	size_bits = 384;
	size_bytes = 48;
	name = "NISTP384";
	if ((algo != 0) && (algo != TEE_ALG_ECDSA_SHA384) &&
	    (algo != TEE_ALG_ECDH_DERIVE_SHARED_SECRET))
		return TEE_ERROR_BAD_PARAMETERS;
	break;
```

So I have the following problem:

1. How does OPTEE understand the TEE_ALG_ECDSA_SHA* macro definition, and does the usage method go against the original intent of GP131 to deprecate TEE_ALG_ECDSA_P*. I think this change is to more accurately describe the ECDSA signature algorithm using the SHA-* hash functions
2. After I call the TEE_AsymmetricSignDigest interface, does OPTEE adjust the digest algorithm TEE_ALG_ECDSA_SHA* according to the digestLen passed in? I guess there is, because I called the ECDSA function, such as ECC256/384/521 with SHA256+SHA384+SHA512 in OPTEE all worked, but I'm sorry I didn't find the relevant adjustment code, can you point out the location of the relevant code?

**Comment by jenswi-linaro** [comment]
I'm sorry I don't get the question, or are you asking for something to be changed? If so feel free to provide a patch fixing the issue you have and perhaps it will be easier to understand.

**Comment by mrnuclear8** [comment]
For example, if I want to sign SHA512 post-digest data with an ECC384 key, then my entry should be

`TEE_AllocateOperation(operation, TEE_ALG_ECDSA_SHA512, sign, 384)`

while the OPTEE requirement is

`TEE_AllocateOperation(operation, TEE_ALG_ECDSA_SHA384, sign, 384)`

This makes me wonder why my signed digest data is SHA512, but the algorithm id used is `TEE_ALG_ECDSA_SHA384`

**Comment by jenswi-linaro** [comment]
Good point. Would you mind supplying a pull request to fix this?

**Comment by mrnuclear8** [comment]
Okay, I will consider it

**Comment by jforissier** [comment]
Could this be related to a backward-compatibility issue I have observed: when running `xtest` and TAs from OP-TEE version 3.18.0 on top of OP-TEE core built from current master, regression test 6001.43 fails as follows:
```
o regression_4006.43 Asym Crypto case 426 algo 0x80000045 line 3545
xtest_helpers.c:63: ret_orig has an unexpected value: 0x3 = TEEC_ORIGIN_TEE, expected 0x4 = TEEC_ORIGIN_TRUSTED_APP
regression_4000.c:3906: ta_crypt_cmd_allocate_operation(c, &session, &op, tv->algo, TEE_MODE_ENCRYPT, max_key_size) has an unexpected value: 0xffff3024 = TEE_ERROR_TARGET_DEAD, expected 0x0 = TEEC_SUCCESS
  regression_4006.43 FAILED

E/TC:? 0 TA panicked with code 0xffff0006 (TEE_ERROR_BAD_PARAMETERS)
E/LD:  Status of TA cb3e5ba0-adf1-11e0-998b-0002a5d5c51b
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0x0e333000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0x0e335000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000e000 pa 0x0e33d000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x4000f000 pa 0x0e33e000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40013000 pa 0x0e342000 size 0x001000 flags r--s
E/LD:  region  5: va 0x40014000 pa 0x0e3a0000 size 0x009000 flags rw-s (stack)
E/LD:  region  6: va 0x4007c000 pa 0x00001000 size 0x04d000 flags r-xs [0] .ta_head .text .eh_frame .rodata .gnu.hash .dynsym .dynstr .hash .rela.dyn
E/LD:  region  7: va 0x400c9000 pa 0x0004e000 size 0x010000 flags rw-s [0] .dynamic .got .rela.data .rela.got .data .bss
E/LD:   [0] cb3e5ba0-adf1-11e0-998b-0002a5d5c51b @ 0x4007c000 (cb3e5ba0-adf1-11e0-998b-0002a5d5c51b.elf)
E/LD:  Call stack:
E/LD:   0x40085614 TEE_AllocateOperation at optee_os/lib/libutee/tee_api_operations.c:358
E/LD:   0x4007d1d4 ta_entry_allocate_operation at out-br/build/optee_test_ext-1.0/ta/crypt/cryp_taf.c:122 (discriminator 2)
E/LD:   0x400883d8 entry_invoke_command at optee_os/lib/libutee/arch/arm/user_ta_entry.c:370
E/LD:   0x40080a38 __ta_entry at optee_os/out/arm/export-ta_arm64/src/user_ta_header.c:48
```
