### ISSUE TITLE
Call TA from PTA

### ISSUE THREAD

**Issue by jewcomm** [OP-TEE/optee_os#6016]
When starting the device, I need to send data to the server once from my TA.
The solution seems to be to make a Linux kernel module that would call my TA, but as I understand it, it is impossible to call TA from the Linux kernel.
I use PTA to get information from Linux. 
Can I call my TA from the PTA after receiving this information?

**Comment by jforissier** [comment]
Hi @jewcomm,

> When starting the device, I need to send data to the server once from my TA. The solution seems to be to make a Linux kernel module that would call my TA, but as I understand it, it is impossible to call TA from the Linux kernel.

It is possible. See the linux source code, `<linux/tee_drv.h>` functions `tee_client_open_session()`, etc. You may look at `security/keys/trusted-keys/trusted_tee.c` for an example.

> I use PTA to get information from Linux. Can I call my TA from the PTA after receiving this information?

That should be possible too but I don't think we have examples in OP-TEE at the moment.

**Comment by jewcomm** [comment]
Hi @jforissier, thanks for the answer 

I tried this method
> It is possible. See the linux source code, `<linux/tee_drv.h>` functions `tee_client_open_session()`, etc
but got

```/TC:? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA e73c0f36-3753-40ce-a0e9-4d3c55797392
D/TC:? 0 ldelf_load_ldelf:96 ldelf load address 0x40006000
D/LD:  ldelf:135 Loading TS e73c0f36-3753-40ce-a0e9-4d3c55797392
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF e73c0f36-3753-40ce-a0e9-4d3c55797392 (early TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF e73c0f36-3753-40ce-a0e9-4d3c55797392 (Secure Storage TA)
E/TC:? 0 get_rpc_alloc_res:645 RPC allocation failed. Non-secure world result: ret=0xffff000c ret_origin=0x2
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff000c
E/LD:  init_elf:486 sys_open_ta_bin(e73c0f36-3753-40ce-a0e9-4d3c55797392)
E/TC:? 0 ldelf_init_with_ldelf:131 ldelf failed with res: 0xffff000c
D/TC:? 0 tee_ta_open_session:735 init session failed 0xffff000c
```

I try run next code

```c
    struct tee_context *ctx;
    struct tee_ioctl_open_session_arg sess_arg;
    struct tee_ioctl_invoke_arg transceive_args;
    struct tee_param command_params[4];

    int rc;
    
    ctx = tee_client_open_context(NULL, syscall_pta_match, NULL, NULL);
    if(IS_ERR(ctx)){
        if(PTR_ERR(ctx) == -ENOENT) return -EPROBE_DEFER;
        return PTR_ERR(ctx);
    }

    memset(&sess_arg, 0, sizeof(sess_arg));
	export_uuid(sess_arg.uuid, &my_ta_uuid);
    sess_arg.clnt_login = TEE_IOCTL_LOGIN_REE_KERNEL;
	sess_arg.num_params = 0;

    rc = tee_client_open_session(ctx, &sess_arg, NULL);
    if((rc < 0) || (sess_arg.ret != 0)) {
        rc = -EINVAL;
        goto out_tee_session;
    }
    
    tee_client_close_session(ctx, sess_arg.session);
    out_tee_session:
    tee_client_close_context(ctx);
```

When I change the uuid to the uuid of my PTA, everything works without problems. Could you suggest what could be the problem?

**Comment by jewcomm** [comment]
> That should be possible too but I don't think we have examples in OP-TEE at the moment.

Is it possible to solve this using functions `tee_ta_open_session`, etc from the `<tee_ta_manager.h>`, or are they meant for something else?

**Comment by jforissier** [comment]
> Hi @jforissier, thanks for the answer
> 
> I tried this method
> 
> > It is possible. See the linux source code, `<linux/tee_drv.h>` functions `tee_client_open_session()`, etc
> 
> but got
> 
> ```
> D/TC:? 0 ldelf_load_ldelf:96 ldelf load address 0x40006000
> D/LD:  ldelf:135 Loading TS e73c0f36-3753-40ce-a0e9-4d3c55797392
> D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF e73c0f36-3753-40ce-a0e9-4d3c55797392 (early TA)
> D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
> D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF e73c0f36-3753-40ce-a0e9-4d3c55797392 (Secure Storage TA)
> E/TC:? 0 get_rpc_alloc_res:645 RPC allocation failed. Non-secure world result: ret=0xffff000c ret_origin=0x2

`tee-supplicant` not yet running maybe?
If you need to invoke your TA early at boot then you can make it an "early TA", that is, have it linked into the OP-TEE binary (the drawback being, you need to update the whole binary to update the TA).

**Comment by jewcomm** [comment]
> `tee-supplicant` not yet running maybe?

Thank you! You are absolutely right, I missed this moment
