### ISSUE TITLE
TEE_Malloc or Secure Storage for Intermediate Result?

### ISSUE THREAD

**Issue by LZYHHHHH** [OP-TEE/optee_os#6017]
Hi,

I tried to transmit multiple sets of data from the client application to the trusted application in a sequential manner at different points in time. When the trusted application receives data, I want to do some computation with the data inside the TEE in order to protect and store the result in secure memory. These results will later be used for further computations with data sent from the client application again. The algorithm can be represented graphically as shown below.
![IMG_0755](https://github.com/OP-TEE/optee_os/assets/113720727/957f8346-a479-481b-8287-b1d368c7f69c)

My questions are:

If I want to accomplish this within a single session, using only one trusted application, what would be the best approach for handling intermediate results during data transfer? Should I make use of a buffer within the TEE, employing functions such as TEE_Malloc and TEE_MemMove? Or it is better to create a persistent object, similar to the secure storage example, to store these intermediate results?

Another question is can the trusted application and client application perform the intermediate calculations in parallel? (like 5+1 and 5*2 at the same time). Would it be necessary for the client application to be multi-threaded during this process?

I would greatly appreciate any assistance or insights regarding these questions! Wish you have a good weekend!

**Comment by jforissier** [comment]
Hello @LZYHHHHH,

Unless you need some persistence/checkpointing (i.e., being able to resume some computation after device reboot for example) and/or the data is too big to fit in memory, I would not recommend using the secure storage for what you describe. I would suggest to keep things as simple as possible and use `TEE_Malloc()` instead (or even a global variable).
As you guessed it, the CA and TA can perform computations in parallel if the client is multi-threaded . Note that TAs are not multi-threaded though; there can only be one thread at a time entering your TA.

**Comment by LZYHHHHH** [comment]
Hi @jforissier 
Thank you so much for your prompt reply. It really helps! I will do some research on the multi-thread CA later.
I have another quick question: since TEE_Malloc() returns memory that is private to the specific instance of the Trusted Application (TA), would it be secure enough if I store the intermediate result in a global variable within the TA.c file, as compared to using TEE_Malloc()?

**Comment by jforissier** [comment]
> would it be secure enough if I store the intermediate result in a global variable within the TA.c file, as compared to using TEE_Malloc()?

It would be the same. In fact, the heap used by `TEE_Malloc()` is declared as a global variable, see here: https://github.com/OP-TEE/optee_os/blob/23419643ecf2dcce31ccc2ee03dfa74096a45de5/ta/user_ta_header.c#L119.

**Comment by LZYHHHHH** [comment]
I see, so the global variables and the memory allocation both occupy the secure memory.
Thank you for your help and wish you have a good day.
