### ISSUE TITLE
Soft FP support

### ISSUE THREAD

**Issue by Yanjiong** [OP-TEE/optee_os#603]
Hi,

When I ld my ta with a lib include soft fp instructions, I got errors as below:
undefined reference to `__aeabi_fdiv'

Then I have to ld libgcc to solve this, but ta failed to be opened since BAD_FORMAT. 

Why this happen? How to solve this?

Thanks a lot.

BR.
Wang Yanjiong

**Comment by Yanjiong** [comment]
Hi,

After link libgcc, there will be one EXIDX Program Header in front of the fisrt LOAD Program Header, which will cause TA load failed.

BR.
Wang Yanjiong

**Comment by jenswi-linaro** [comment]
Hi,

We've recently added support for softfloat on the master branch, please try with that.

Regards,
Jens

**Comment by Yanjiong** [comment]
Hi,

Thanks. 

Floating point support for TAs default on only for arm32 core?

Any problem if I enable it for arm64 core?

BR.
Wang Yanjiong

**Comment by jenswi-linaro** [comment]
There's no eabi for soft-float for Aarch64 so it will not work. I'm working on patches for hard floating point for both arm32 and arm64.

**Comment by Yanjiong** [comment]
Hi,

What if arm64_core with arm32_ta? 

Since the TA need soft-float, and the lib should be linked to arm32_ta, the soft-float should works, right?

BR.
Wang Yanjiong

**Comment by jenswi-linaro** [comment]
Yes, that should work.

**Comment by Yanjiong** [comment]
Thanks a lot.

**Comment by Yanjiong** [comment]
Is there any schedule to release the patches for hard floating point? I can help to test if the patch link available.

**Comment by jenswi-linaro** [comment]
There isn't a fixed schedule but the patches will be merged soon. Testing is always welcome, keep an eye on pull request for this repository the nearest weeks and you'll have an opportunity to test it before it's merged. By the way, which platform are you using?

**Comment by jbech-optee-adm** [comment]
Questions have been answered and therefore I'm closing this issue. Please feel free to re-open it again if you have more questions on the same topic.

// Joakim
