### ISSUE TITLE
A RISC-V linking issue on buildroot optee_test package

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/optee_os#6033]
Hi @maroueneboubakri @liushiwei007 and maintainers,

I encountered a linking issue, I am not sure if you saw it before, thanks.

When I build the buildroot with optee_test package, the following error occurs:
```
>>> optee_test_ext 1.0 Building
Consolidate compiler generated dependencies of target f07bfc66-958c-4a15-99c0-260e4e7375dd.plugin
Consolidate compiler generated dependencies of target xtest
[  6%] Built target f07bfc66-958c-4a15-99c0-260e4e7375dd.plugin
[100%] Built target xtest
Building /optee_riscv/out-br/build/optee_test_ext-1.0/ta/os_test_lib/Makefile
  LD      out/libos_test.so
/optee_riscv/build/../toolchains/riscv64/bin/riscv64-unknown-linux-gnu-ld.bfd: relocation R_RISCV_JAL against `__utee_panic' which may bind externally can not be used when making a shared object; recompile with -fPIC
make[3]: *** [/optee_riscv/optee_os/out/riscv/export-ta_rv64/mk/link_shlib.mk:36: out/libos_test.so] Error 1
make[2]: *** [package/pkg-generic.mk:294: /optee_riscv/out-br/build/optee_test_ext-1.0/.stamp_built] Error 2
make[1]: *** [Makefile:23: _all] Error 2
make[1]: Leaving directory '/optee_riscv/out-br'
make: *** [common.mk:344: buildroot] Error 2
```

Previously I tried the toolchain downloaded from https://toolchains.bootlin.com/, everything works well.
But when I switch to RISC-V official release: https://github.com/riscv-collab/riscv-gnu-toolchain/releases, the error happened.

I think that we have added `-fpic` into the compiler flags:
```
ta_rv64-platform-cflags := -Os -g3 -fpic -mstrict-align -fstack-protector-strong
ta_rv64-platform-cxxflags := -fpic -Os -g3
```

**Comment by liushiwei007** [comment]
hi, @gagachang 
Instead of using buildroot, we built rootfs directly using busybox, so I can only say that we are not experiencing this problem at the moment. Here is my build log:
make[2]: 离开目录“/home/lsw/work/test_performance_1/tee/optee_test/ta/crypt”
make[2]: 进入目录“/home/lsw/work/test_performance_1/tee/optee_test/ta/os_test_lib”
  CC      /home/lsw/work/test_performance_1/tee/optee_test/out/ta/os_test_lib/os_test_lib.o
  LD      /home/lsw/work/test_performance_1/tee/optee_test/out/ta/os_test_lib/libos_test.so
  OBJDUMP /home/lsw/work/test_performance_1/tee/optee_test/out/ta/os_test_lib/libos_test.dmp
  OBJCOPY /home/lsw/work/test_performance_1/tee/optee_test/out/ta/os_test_lib/libos_test.stripped.so
  LN      /home/lsw/work/test_performance_1/tee/optee_test/out/ta/os_test_lib/ffd2bded-ab7d-4988-95ee-e4962fff7154.elf
  SIGN    /home/lsw/work/test_performance_1/tee/optee_test/out/ta/os_test_lib/ffd2bded-ab7d-4988-95ee-e4962fff7154.ta

**Comment by gagachang** [comment]
Dear @liushiwei007 
May I know which toolchain you used to build optee-os ?

**Comment by gagachang** [comment]
I can fix this build error by modifying `j __utee_panic` to `call __utee_panic`
`j __utee_panic` is not PC-relative jump, so can not be PIC.
```
	FUNC _utee_panic, :
	j	__utee_panic                --> call	__utee_panic
	END_FUNC _utee_panic
```
However, the xtest fails many cases with the latest official toolchain.
I think keep using stable one from  https://toolchains.bootlin.com/ is better.

**Comment by liushiwei007** [comment]
hi，@gagachang 
I used riscv64-unknown-linux-gnu-gcc, which was provided to me by my colleague.  I also used other toolchains before.  I did not pay much attention to the specific sources, which should not be too new, after all, I started to use this toolchain in the middle of last year.  I guess the new toolchain adds new features or restrictions, and I think we can modify the code if necessary.

**Comment by gagachang** [comment]
> I guess the new toolchain adds new features or restrictions, and I think we can modify the code if necessary.

Agree, thanks.

Actually I am preparing a patch for toolchain.mk, which adds RISC-V toolchain support.
Should we use RISC-V latest toolchain from official release or other website such as bootlin ?

1. https://github.com/riscv-collab/riscv-gnu-toolchain/releases
2. https://toolchains.bootlin.com/releases_riscv64-lp64d.html

**Comment by liushiwei007** [comment]
I don't know much about the difference between these compilers, I just asked a colleague, we compile our own compiler. I think you need to make that decision。

**Comment by gagachang** [comment]
> I don't know much about the difference between these compilers, I just asked a colleague, we compile our own compiler. I think you need to make that decision。

OK thank you!

Dear @maroueneboubakri , do you have any comments about the choice of RISC-V toolchain ?

**Comment by gagachang** [comment]
Dear @liushiwei007 ,

The PR https://github.com/OP-TEE/optee_os/pull/6045 fixes this issue.
Because the original code is submitted by you, would you please review the PR?
Thanks!

**Comment by gagachang** [comment]
Close this issue since solution is merged in https://github.com/OP-TEE/optee_os/pull/6045.
