### ISSUE TITLE
How to measure the the delay time of the world switching and execution time of function in TA

### ISSUE THREAD

**Issue by LZYHHHHH** [OP-TEE/optee_os#6034]
Hi Team,

I tried to measure the delay time of the world switching which is the time between the CA invoke command and the TA receiving the parameters. My thought is that with more data inside the buffer of the operation (TEEC_MEMREF_TEMP_INPUT), the delay time will increase. 
I used the ```clock_gettime(CLOCK_MONOTONIC, &start_time)``` in the CA and send ```start_time.tv_sec``` and ```start_time.tv_nsec``` to the TA within the operation. On the TA side, I used the ```TEE_GetSystemTime(&ta_time)``` and subtract it from the received CA time. The problem is that the delay time seems over the total execution time I measure on the CA side. Therefore I think the two measurements are in different standards. Is there any suggestion for switching time measurement? 

Also, I want to measure the execution time of the function running inside TA and I am working on QEMU7. 
At first, I tried ```TEE_GetSystemTime```, but it only get milliseconds. 
Then I followed with the post [#4558](https://github.com/OP-TEE/optee_os/issues/4558) and [#4029](https://github.com/OP-TEE/optee_os/issues/4029) and tried to measure with cntpct as shown below:
```
#include <arm_user_sysreg.h>
static unsigned int arm_cnt_cnt2us(uint64_t cnt)
{
	return (cnt * 1000000) / read_cntfrq();
}
	uint64_t t1, t2;
	t1 = read_cntpct();
	CALCULATION HERE
        t2 = read_cntpct();
	IMSG("time spent in microseconds: %u", arm_cnt_cnt2us(t2 - t1));
```

However, TA panicked with the below error code even if I increase the TA_STACK_SIZE and TA_DATA_SIZE. Am I on the right track? Really appreciate any advice and help, wish you have a wonderful day!

```
CA: TEEC_InvokeCommand failed with code 0xffff3024 origin 0x3
TA:


D/TC:0 0 abort_handler:539 [abort] abort in User mode (TA will panic)
E/TC:? 0 
E/TC:? 0 User mode undef-abort at address 0x40029310
E/TC:? 0  esr 0x6232faa1  ttbr0 0x400000e1a1000   ttbr1 0x00000000   cidr 0x0
E/TC:? 0  cpu #0          cpsr 0x60000100
E/TC:? 0  x0  000000004026d628 x1  000000004003a264
E/TC:? 0  x2  0000000000000024 x3  000000004026d628
E/TC:? 0  x4  000000004026d628 x5  0000000000000000
E/TC:? 0  x6  0000000000000023 x7  000000004026d320
E/TC:? 0  x8  0000000000000001 x9  000000004026d328
E/TC:? 0  x10 0000000000000000 x11 0000000000000000
E/TC:? 0  x12 0000000000000000 x13 000000004026d1bb
E/TC:? 0  x14 0000000000000020 x15 0000000000000000
E/TC:? 0  x16 00000000c98c4f50 x17 0000000000000000
E/TC:? 0  x18 0000000000000000 x19 0000000000000000
E/TC:? 0  x20 000000004003a1fc x21 000000004026d730
E/TC:? 0  x22 000000004026d678 x23 0000000000000000
E/TC:? 0  x24 0000000000000005 x25 0000000000000000
E/TC:? 0  x26 0000000000000000 x27 0000000000000000
E/TC:? 0  x28 0000000000000000 x29 000000004026d5f0
E/TC:? 0  x30 0000000040029310 elr 0000000040029310
E/TC:? 0  sp_el0 000000004026d5f0
E/LD:  Status of TA 8abaf200-2450-11e4-abe2-0002a5d5c51b
E/LD:   arch: aarch64
E/LD:  region  0: va 0x40004000 pa 0x0e326000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x40006000 pa 0x0e328000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x4000e000 pa 0x0e330000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x4000f000 pa 0x0e331000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x40013000 pa 0x0e335000 size 0x001000 flags r--s
E/LD:  region  5: va 0x40015000 pa 0x457f3660 size 0x001000 flags rw-- (param)
E/LD:  region  6: va 0x40029000 pa 0x00001000 size 0x013000 flags r-xs [0]
E/LD:  region  7: va 0x4003c000 pa 0x00014000 size 0x204000 flags rw-s [0]
E/LD:  region  8: va 0x40240000 pa 0x0e54d000 size 0x02e000 flags rw-s (stack)
E/LD:   [0] 8abaf200-2450-11e4-abe2-0002a5d5c51b @ 0x40029000
E/LD:  Call stack:
E/LD:   0x40029310
E/LD:   0x4002ae74
E/LD:   0x400293d8
D/TC:? 0 user_ta_enter:176 tee_user_ta_enter: TA panicked with code 0xdeadbeef
```

**Comment by jenswi-linaro** [comment]
You need to enable access to the register before you can access it from user mode.

**Comment by LZYHHHHH** [comment]
Hi @etienne-lms ,
Thanks for the reply. Could you please provide more information about how to enable PL0PCTEN in cntkctl for EL0? Should I rebuild the OPTEE-OS with CFG_SECURE_TIME_SOURCE_CNTPCT=y?

**Comment by LZYHHHHH** [comment]
Yes, I think so. I am using raspberry pi 3b with [ARM Cortex-A53](https://developer.arm.com/documentation/ddi0500/e/generic-timer/generic-timer-register-summary/aarch32-generic-timer-register-summary).
