### ISSUE TITLE
Assessing the security using OpenSSF scorecard

### ISSUE THREAD

**Issue by Sadiq1811** [OP-TEE/optee_os#6037]
Hello OPTEE team,

I recently came across the `OpenSSF scorecard` which assesses the security of opensource projects.
Does it make sense to run this on all the OPTEE repositories?

**References:** 
https://openssf.org/
https://securityscorecards.dev/

Regards
Sadiq

**Comment by jbech-linaro** [comment]
Great idea, but it think that would introduce requirements on the code base that isn't even relevant to OP-TEE. Example, from https://securityscorecards.dev/#the-checks:
- Does the project have unfixed vulnerabilities? Uses the OSV service.
  - We do have our own well established way of dealing with vulnerabilities.
 
This is one example, but there are several of the things in there that doesn't match very well with our way of working and how OP-TEE is built. I'm pretty sure these kind of scorecards are useful, but I struggle to see how they can be applied generically.

**Comment by Sadiq1811** [comment]
i completely agree with you as some checks don't seem like a "one size fits all" sort of a solution.
But, yeah there needs to be some way to get it generalized
