### ISSUE TITLE
question for thread_rpc_free

### ISSUE THREAD

**Issue by Master-Chi** [OP-TEE/optee_os#6038]
hi, community
I have some confuse about function thread_rpc_free in core/arch/arm/kernel/thread_spmc.c

``` C
static void thread_rpc_free(unsigned int bt, uint64_t cookie, struct mobj *mobj)
{
	struct thread_rpc_arg rpc_arg = { .call = {
			.w1 = thread_get_tsd()->rpc_target_info,
			.w4 = OPTEE_FFA_YIELDING_CALL_RETURN_RPC_CMD,
		},
	};
	struct thread_param param = THREAD_PARAM_VALUE(IN, bt, cookie, 0);
	uint32_t res2 = 0;
	uint32_t res = 0;

	DMSG("freeing cookie %#"PRIx64, cookie);

	res = get_rpc_arg(OPTEE_RPC_CMD_SHM_FREE, 1, &param, NULL);

	mobj_put(mobj);
	res2 = mobj_ffa_unregister_by_cookie(cookie);
	if (res2)
		DMSG("mobj_ffa_unregister_by_cookie(%#"PRIx64"): %#"PRIx32,
		     cookie, res2);
	if (!res)
		thread_rpc(&rpc_arg);
}
```

Why should mobj_ffa_unregister_by_cookie be called here first rather than waiting for OPTEE_FFA_UNREGISTER_SHM?

sorry for bothering and wired format

**Comment by jenswi-linaro** [comment]
There will never be an `OPTEE_FFA_UNREGISTER_SHM` for this allocation. That's an optimization for shared memory established via RPC.

**Comment by Master-Chi** [comment]
Sorry, i am still confused
in optee os
`thread_rpc_free
    thread_rpc
`

in Linux Driver:
`handle_ffa_rpc_func_cmd
    handle_ffa_rpc_func_cmd_shm_free
        /*which invoke a fastcall OPTEE_FFA_UNREGISTER_SHM*/
        optee_ffa_shm_unregister
       
`

**Comment by jenswi-linaro** [comment]
It's actually `optee_ffa_shm_unregister_supp()` that is called when tee-supplicant unregisters shared memory.

**Comment by Master-Chi** [comment]
I got it, thanks a lot
