### ISSUE TITLE
Incorrect MPIDR Parsing causes MMU faults

### ISSUE THREAD

**Issue by LeiSen62** [OP-TEE/optee_os#6043]
Hi，i incorrectly parses MPIDR, which causes two different cores correspond to the same core id. In this case, when I execute some test cases that require large memory (16 MB), MMU faults generated by instruction accesses and synchronous external aborts will happen. The error location may not be the same each time. Why? What happened?

**Comment by jenswi-linaro** [comment]
Each core must have a unique code id or things will fail in many different ways.
