### ISSUE TITLE
How to add a python interpreter to the normal world of op-tee？

### ISSUE THREAD

**Issue by wsx11** [OP-TEE/optee_os#6047]
I am new to this project. I am using qemu to run op-tee. I want to know how to add .py files to normal world, and add python interpreter. Thanks!!!

**Comment by jforissier** [comment]
Use `make -j$(nproc) run BR2_PACKAGE_PYTHON3=y`.

Additional files (`.py` or whatever) can be added to `br-ext/board/qemu/overlay/`,  but for development purpose a good option may be to add `QEMU_VIRTFS_AUTOMOUNT=y`. With that, your project directory will be made visible to the QEMU guest as `/mnt/host` which is convenient for debugging.

**Comment by wsx11** [comment]
> 

thank you for your reply! Adding Additional files I have successfully done. But I want to ask you again, in which directory should the command 'make -j$(nproc) run BR2_PACKAGE_PYTHON3=y' be executed? Thank you!

**Comment by wsx11** [comment]
> Use `make -j$(nproc) run BR2_PACKAGE_PYTHON3=y`.
> 
> Additional files (`.py` or whatever) can be added to `br-ext/board/qemu/overlay/`, but for development purpose a good option may be to add `QEMU_VIRTFS_AUTOMOUNT=y`. With that, your project directory will be made visible to the QEMU guest as `/mnt/host` which is convenient for debugging.

thank you for your reply! Adding Additional files I have successfully done. But I want to ask you again, in which directory should the command 'make -j$(nproc) run BR2_PACKAGE_PYTHON3=y' be executed? Thank you!

**Comment by jforissier** [comment]
@wsx11 from `<project top dir>/build`. See https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8.

**Comment by wsx11** [comment]
> @wsx11 from `<project top dir>/build`. See https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8.

I have solved all the problems, thanks again for your reply!

**Comment by wsx11** [comment]
@jforissier   Excuse me again. I would like to ask how to use the 'make' command in the normal world?

**Comment by jforissier** [comment]
> @jforissier Excuse me again. I would like to ask how to use the 'make' command in the normal world?

`BR2_PACKAGE_MAKE=y`, probably.

**Comment by wsx11** [comment]
> > @jforissier Excuse me again. I would like to ask how to use the 'make' command in the normal world?
> 
> `BR2_PACKAGE_MAKE=y`, probably.

This doesn't seem to work. Error when building.

**Comment by wsx11** [comment]
> > @jforissier Excuse me again. I would like to ask how to use the 'make' command in the normal world?
> 
> `BR2_PACKAGE_MAKE=y`, probably.

You are right. Previously it was an error caused by a network problem. Thanks!!

**Comment by shirinebadi** [comment]
Hi @jforissier. I'm curious to know if there is anyway to install pip in normal world and use it.

**Comment by jforissier** [comment]
> Hi @jforissier. I'm curious to know if there is anyway to install pip in normal world and use it.

I don't think Buildroot allows to build and install pip. One way could be to enable `BR2_PACKAGE_PYTHON_3=y` then log into the target system, download `get-pip.py` and run it: `curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py`.

**Comment by shirinebadi** [comment]
I'm running OP-TEE on QEMU and I used wget to get the get-pip.py, then I tried `python get-pip.py`, but I got `zipimport.ZipImportError: can't decompress data; zlib not available`. How can I run my python code with dependency to specific libraries in normal word?

**Comment by shirinebadi** [comment]
> > Hi @jforissier. I'm curious to know if there is anyway to install pip in normal world and use it.
> 
> I don't think Buildroot allows to build and install pip. One way could be to enable `BR2_PACKAGE_PYTHON_3=y` then log into the target system, download `get-pip.py` and run it: `curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py`.

I'm running OP-TEE on QEMU and I used wget to get the get-pip.py, then I tried `python get-pip.py`, but I got `zipimport.ZipImportError: can't decompress data; zlib not available`. How can I run my python code with dependency to specific libraries in normal word?

**Comment by jforissier** [comment]
`make ... BR2_PACKAGE_ZLIB=y` maybe?

**Comment by shirinebadi** [comment]
> `make ... BR2_PACKAGE_ZLIB=y` maybe?

umm...no difference!

**Comment by jforissier** [comment]
`BR2_PACKAGE_PYTHON3_ZLIB`

**Comment by shirinebadi** [comment]
> `BR2_PACKAGE_PYTHON3_ZLIB`

I solved the ZLIB, then I encountered no module named 'xml', and I tried `BR2_PACKAGE_PYEXPAT=y BR2_PACKAGE_EXPAT=y`, however, I again keep facing this error. It seems like it is not even getting this module. I did `make clean all` and tried again, however, no difference!

**Comment by Charlie-Ping** [comment]
> > `BR2_PACKAGE_PYTHON3_ZLIB`
> 
> I solved the ZLIB, then I encountered no module named 'xml', and I tried `BR2_PACKAGE_PYEXPAT=y BR2_PACKAGE_EXPAT=y`, however, I again keep facing this error. It seems like it is not even getting this module. I did `make clean all` and tried again, however, no difference!

Can you tell me how you solved the missing zlib issue? I have already selected `BR2_PACKAGE_PYTHON3_ZLIB=y` and   `BR2_PACKAGE_ZLIB=y`.

**Comment by anHuynh19** [comment]
> > > `BR2_PACKAGE_PYTHON3_ZLIB`
> > 
> > 
> > I solved the ZLIB, then I encountered no module named 'xml', and I tried `BR2_PACKAGE_PYEXPAT=y BR2_PACKAGE_EXPAT=y`, however, I again keep facing this error. It seems like it is not even getting this module. I did `make clean all` and tried again, however, no difference!
> 
> Can you tell me how you solved the missing zlib issue? I have already selected `BR2_PACKAGE_PYTHON3_ZLIB=y` and `BR2_PACKAGE_ZLIB=y`.

how did you solve it? Can you help me?
