### ISSUE TITLE
Document to setup optee_os as virtual environment in linux

### ISSUE THREAD

**Issue by gunaMect** [OP-TEE/optee_os#6051]
Hi all,

I am new to optee_os. Is there any document available to setup optee_os virtually in linux environment. 

Can anyone point to the document so that i can prepare a setup and start contributing to this project?

**Comment by gagachang** [comment]
You can check the following OP-TEE documentation to run it on QEMU with virtual ARMv8.

https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8
