### ISSUE TITLE
Core count for OPTEE OS

### ISSUE THREAD

**Issue by coach-bin** [OP-TEE/optee_os#6059]
Hi experts,
My platform has 4 cores, but 1 core is for RTOS and 3 cores are for linux.
In this case, what is the correct value for CFG_TEE_CORE_NB_CORE(optee_os) and PLATFORM_CORE_COUNT(arm-trusted-firmware)?

CFG_TEE_CORE_NB_CORE = 3, PLATFORM_CORE_COUNT = 4 is correct?

**Comment by jenswi-linaro** [comment]
Core count is the number of cores used by OP-TEE. If OP-TEE ever enters with an unknown core it should panic, but hopefully this should be catched earlier by TF-A.

**Comment by coach-bin** [comment]
@jenswi-linaro Thanks for your answer. PLATFORM_CORE_COUNT may be the core count of TF-A that you mentioned, which is being used for PSCI, etc. Assuming that linux kernel doesn't use PSCI  FW and RTOS doesn't have any application calling SMC, (3 cores for linux, 1 core for RTOS in above case) should I have PLATFORM_CORE_COUNT = CFG_TEE_CORE_NB_CORE = 3 or should I have 4 for these values?

**Comment by jenswi-linaro** [comment]
I guess `3` should work then.

**Comment by coach-bin** [comment]
@jenswi-linaro  Thanks for the clarification!
