### ISSUE TITLE
Incorrect selection of gcc version: expected 11.x, got 10.2.1

### ISSUE THREAD

**Issue by gappudon** [OP-TEE/optee_os#6060]
i am trying to setup optee on my ubuntu.

The below steps have been successfull -
$ mkdir optee-qemu && cd optee-qemu
$ repo init -u https://github.com/OP-TEE/manifest.git
$ repo sync
$ cd build
$ make toolchains -j2

when i run the next step - make run, i run into below error

rsync -a --link-dest=/home/gappu/optee/out-br/per-package/host-skeleton/target/ /home/gappu/optee/out-br/per-package/host-skeleton/target/ /home/gappu/optee/out-br/per-package/toolchain-external-custom/target
rsync -a --link-dest=/home/gappu/optee/out-br/per-package/skeleton/target/ /home/gappu/optee/out-br/per-package/skeleton/target/ /home/gappu/optee/out-br/per-package/toolchain-external-custom/target
Incorrect selection of gcc version: expected 11.x, got 10.2.1
make[2]: *** [package/pkg-generic.mk:283: /home/gappu/optee/out-br/build/toolchain-external-custom/.stamp_configured] Error 1
make[1]: *** [Makefile:23: _all] Error 2
make[1]: Leaving directory '/home/gappu/optee/os

Any idea what might be going wrong ?

**Comment by jforissier** [comment]
Your toolchain is outdated. Try:
```
rm -rf ../toolchains
make toolchains
```

**Comment by gappudon** [comment]
Still the same issue after trying the above steps

**Comment by jforissier** [comment]
Then `rm -rf ../out-br` perhaps. I tried the exact same steps you mentioned above and all went fine.

**Comment by TaihuLight** [comment]
@jforissier 
#https://github.com/OP-TEE/build/issues/652

**Comment by intern-fidility** [comment]
Incorrect selection of gcc version: expected 9.x, got 7.5.0
make[1]: *** [package/pkg-generic.mk:279: /home/fidility2/ela_lab_exercises_rpi/rpi_build/rootfs/v2024.02/buildroot/output/build/toolchain-external-custom/.stamp_configured] Error 1
make: *** [Makefile:83: _all] Error 2
please give me the solution
