### ISSUE TITLE
Why 'TEE_ALG_SM4_CTR' doesn't support the update size is not multiple block-size

### ISSUE THREAD

**Issue by soloicesky** [OP-TEE/optee_os#6071]
The API  `TEE_Result tee_do_cipher_update(void *ctx, uint32_t algo,
				TEE_OperationMode mode, bool last_block,
				const uint8_t *data, size_t len, uint8_t *dst)`,  see below screenshot for detail:
![image](https://github.com/OP-TEE/optee_os/assets/5044681/80f79284-5983-4962-8bb6-4aabe26d4b65)
Why the algo-TEE_ALG_SM4_CTR is excluded? CTR modes are stream cipher they should support incomplete blocks for each update operation.

**Comment by soloicesky** [comment]
您好，你的邮件已收到，我会尽快回复你。                               best regards                                      zaixing_liu

**Comment by soloicesky** [comment]
> It looks like `TEE_ALG_SM4_CTR` is missing there. I guess that also means that the SM4 CTR tests would benefit from another test case.

Thanks for your reply, will it be fixed in the future? ```TEE_ALG_SM4_CTR``` should be treated the same as ```TEE_ALG_AES_CTR ```, what do you think?

**Comment by jenswi-linaro** [comment]
Feel free to propose it in a pull request, patches are welcome!
