### ISSUE TITLE
riscv smp interrupt context  problem

### ISSUE THREAD

**Issue by matthewgui** [OP-TEE/optee_os#6075]
On the RISCV platform, the PLIC interrupt controller interrupt source enable mode can be set to M mode or S mode. 

**When M mode interrupt is enabled, it will trap into M mode; S mode interrupt is enabled and delegate is set, it will trap to S mode.**

M mode software stack is monitor , S mode software stack is REE os / TEE os.

**To distinguish between secure and non-secure interrupts, Setting interrupts that are not handled by the current world to M mode, while interrupts handled by the current world will be set to Smode.**

When M mode interrupt occur, it will trap to M mode, save prev context , restore next context, then forward to another world for processing, when S mode interrupt is triggered, it is directly handled by the current world.

We use this method when **porting OPTEE to riscv**, but ***there is a problem that when core1 is executed in the TEE world, M mode interrupt is triggered,
M mode Monitor will save the context of core1 TEE, restore thre context of core1 REE, then mret to REE to continue, after REE processes the interrupt, the REE system schedules
core2 to continue execute this task, unfortunately it is not possible to restore the execution context of core1 because of thread core local, temp stack is percpu structure***.
.Unlike ARM, when the ARM TEE world executes, foreign interrupt will trap to OPTEE, OPTEE will save the current thread , and then rpc with threadid to REE,other core can use threadid
to restore pre context.

In this case, what should i do on riscv? Thank you in advance.

**Comment by gagachang** [comment]
Hi @matthewgui 

I don't have environment to test, so I just try to think a solution to be discussed.

> To distinguish between secure and non-secure interrupts, Setting interrupts that are not handled by the current world to M mode, while interrupts handled by the current world will be set to Smode.

Since current RISC-V PLIC does not support S/NS interrupt identifier, your solution looks good. 

> M mode Monitor will save the context of core1 TEE, restore thre context of core1 REE, then mret to REE to continue

I think M mode should not save the context of core1 TEE directly.
M mode should enter OPTEE and tell OPTEE that there is a foreign interrupt and it should suspend the current thread.

OPTEE can register its vector to M-mode in boot time, like what ARM does:
M-mode can enter(mret) OPTEE based on this vector table.
```
FUNC thread_vector_table , : , .identity_map, , nobti
	b	vector_std_smc_entry
	b	vector_fast_smc_entry
	b	vector_cpu_on_entry
	b	vector_cpu_off_entry
	b	vector_cpu_resume_entry
	b	vector_cpu_suspend_entry
	b	vector_fiq_entry
	b	vector_system_off_entry
	b	vector_system_reset_entry
END_FUNC thread_vector_table
```

We can implement a function called `vector_foreign_intr_entry`.
In `vector_foreign_intr_entry`, the current TEE thread is suspended, just like what ARM's `foreign_intr_handler` does.

So if a NS interrupt is taken in M-mode first, the steps look like:
**1. M-mode knows current CPU is in TEE. M-mode `mret` to OPTEE's `vector_foreign_intr_entry`.
2. OPTEE suspends current thread, and issues ecall (RPC with foreign interrupt) back to REE. (Like ARM's `thread_foreign_intr_exit()`)**
3. M-mode handles RPC `ecall` and switches the execution to REE.
4. REE gets RPC with foreign interrupt. It handles the interrupt and then returns RPC back to TEE.
5. TEE can resume previous thread.

Step 2~5 are identical to ARM's flow.
Step 1 is RISC-V's solution.

**Comment by matthewgui** [comment]
Hi @gagachang 
good solution, i will try, thank you!

**Comment by gagachang** [comment]
@matthewgui 

My pleasure!
Please let me know the result or any further problems.

**Comment by matthewgui** [comment]
Hi @gagachang 
it seems we cannot modify the MEPC, because it hold the TEE program address which is interrupted by foreign intr.
all register status must be saved, or it cannot be restore to continue in TEE.

**Comment by gagachang** [comment]
Hi @matthewgui 

When `thread_state_suspend()` is called, the interrupted PC is stored into OPTEE's thread context.

**Comment by matthewgui** [comment]
Hi @gagachang 
oh, no , interrupted PC is in MEPC register, if need to mret to TEE vector_foreign_intr_entry, MEPC value will be changed
this point is different from arm.
```
	/*
	 * Mark current thread as suspended
	 */
	mov	w0, #THREAD_FLAGS_EXIT_ON_FOREIGN_INTR
	mrs	x1, spsr_el1
	mrs	x2, elr_el1
	bl	thread_state_suspend
```

**Comment by gagachang** [comment]
Hi @matthewgui 

I think the value of MEPC can be stored into SEPC, since OPTEE will get the interrupted PC from SPEC not MEPC.
1. Store MEPC to SEPC
2. Set MEPC as `vector_foreign_intr_entry` and mret

> all register status must be saved, or it cannot be restore to continue in TEE.

Yes, the `vector_foreign_intr_entry` should save and restore all registers for this purpose.
The interrupted PC is also read from SEPC (we write it as value of MEPC before).
When `thread_state_suspend()` is called, the interrupted PC is stored into OPTEE's thread context.

**Comment by gagachang** [comment]
> Hi @gagachang oh, no , interrupted PC is in MEPC register, if need to mret to TEE vector_foreign_intr_entry, MEPC value will be changed this point is different from arm.
> 
> ```
> 	/*
> 	 * Mark current thread as suspended
> 	 */
> 	mov	w0, #THREAD_FLAGS_EXIT_ON_FOREIGN_INTR
> 	mrs	x1, spsr_el1
> 	mrs	x2, elr_el1
> 	bl	thread_state_suspend
> ```

Yes, we need to save MEPC to SPEC first.
Then we can change MEPC.

**Comment by matthewgui** [comment]
> Hi @matthewgui
> 
> I think the value of MEPC can be stored into SEPC, since OPTEE will get the interrupted PC from SEPC not MEPC.
> 
> 1. Store MEPC to SEPC
> 2. Set MEPC as `vector_foreign_intr_entry` and mret
> 
> > all register status must be saved, or it cannot be restore to continue in TEE.
> 
> Yes, the `vector_foreign_intr_entry` should save all registers for this purpose. The interrupted PC is read from SEPC (we write it as value of MEPC before). When `thread_state_suspend()` is called, the interrupted PC is stored into OPTEE's thread context.


M mode can interrupt S mode interrupt service, so sepc maybe in use ?

**Comment by gagachang** [comment]
How about asserting a fake interrupt to OPTEE which represents a foreign interrupt?

1. OPTEE is handling an secure interrupt
2. Suddenly a NS interrupt is asserted. CPU enters M-mode.
3. M-mode disables all NS interrupts. Note that NS interrupts are still pended.
4. M-mode asserts a fake interrupt to S-mode OPTEE and mret to OPTEE.
5. After OPTEE handles previous secure interrupt, it handles the fake interrupt and knows it is a foreign interrupt.
6. OPTEE can suspend the thread and CPU is switched back to REE.

But I think it is a tricky ...

**Comment by matthewgui** [comment]
Hi @gagachang 
```
But if so it means a NS interrupt can preempt secure interrupt, right?
```
yes, riscv have no NS/S interrupt, we use PLIC M/S interrupt enable mode to distinguish Foreign Intr, Native Intr.
```
Therefore M-mode can disable all NS interrupts when CPU enters OPTEE, instead of setting interrupts that are not handled by OPTEE to M-mode.
```
maybe we cannot do that ,first interrupt reponse is slow, second we cannot sure how long OPTEE will execute which will block REE

```
How about asserting a fake interrupt to OPTEE which represents a foreign interrupt?
```
it seems not a common method

**Comment by gagachang** [comment]
What if all NS/S interrupts are handled by OPTEE first when CPU is in OPTEE?

OPTEE knows which interrupt sources are secure interrupts, others are NS interrupt sources.
If OPTEE gets an NS interrupt source by PLIC claim, OPTEE can ignore it.
OPTEE just asserts that NS interrupt source pending bit again to PLIC, without completing the NS interrupt source.
Then OPTEE suspends current thread, and CPU is switched back to REE.

Because NS interrupt source is still pended and have not been completed, REE can still get that NS interrupt by PLIC claim.

**Comment by gagachang** [comment]
Oh sorry please ignore my last comment
PLIC pending bits may be read-only.

**Comment by fanghuaqi** [comment]
Is there any possible way to do different architecture porting for riscv unlike the current Arm one, to make it possible to save and restore TEE context in M-mode without consider current executing core, maybe this need help from the optee architecture designer's help, could maintainer @jforissier give us some suggestion?

Thank you

**Comment by jforissier** [comment]
@fanghuaqi arm64 has EL3 and arm32 has a Monitor mode. Both of which are used to switch context between secure and non-secure states. I believe they could be considered equivalent to M-mode on RISC-V. For arm64, OP-TEE typically depends on Trusted Firmware A (TF-A) BL31 which is the piece of software that runs at EL3. For arm32, OP-TEE has its own "Secure Monitor" which runs in Monitor mode (`core/arch/arm/sm`). So maybe RISC-V could have its own equivalent of a Secure Monitor?

**Comment by fanghuaqi** [comment]
> @fanghuaqi arm64 has EL3 and arm32 has a Monitor mode. Both of which are used to switch context between secure and non-secure states. I believe they could be considered equivalent to M-mode on RISC-V. For arm64, OP-TEE typically depends on Trusted Firmware A (TF-A) BL31 which is the piece of software that runs at EL3. For arm32, OP-TEE has its own "Secure Monitor" which runs in Monitor mode (`core/arch/arm/sm`). So maybe RISC-V could have its own equivalent of a Secure Monitor?

Thank you @jforissier , yes for risc-v the secure monitor could be implemented as part of [opensbi][1] which is running in M-mode, and existing always even linux kernel is running, and provide some functions via sbi calls when linux kernel want to access resources only accessable in M-mode. 


---

[1]: https://github.com/riscv-software-src/opensbi

**Comment by gagachang** [comment]
I think the key point is ARM relies on OP-TEE to solve Linux task migration during RPC.
RISC-V needs M-mode to solve it ?

**Comment by jenswi-linaro** [comment]
> I think the key point is ARM relies on OP-TEE to solve Linux task migration during RPC. And RISC-V needs to solve the task migration in M-mode firmware ?

This is also known as a managed exit. You should preferably find a way to reenter OP-TEE from M-mode firmware to let OP-TEE do a proper managed exit. If not you'll need to reenter OP-TEE on the core that received the normal world interrupt. That might make a mess in the kernel driver.

**Comment by gagachang** [comment]
> ```
> How about asserting a fake interrupt to OPTEE which represents a foreign interrupt?
> ```
> it seems not a common method

After studying [ARM FF-A](https://developer.arm.com/documentation/den0077/f) section 9.3.1, seems ARM asserts virtual interrupt to enter OPTEE for thread suspending.

Before RISC-V supports NS/S interrupt identifying, I think this approach is applicable on current RISC-V.
If PLIC does not support writable pending bit, maybe supervisor software interrupt pending (SSIP) can be used ?

**Comment by fanghuaqi** [comment]
> > I think the key point is ARM relies on OP-TEE to solve Linux task migration during RPC. And RISC-V needs to solve the task migration in M-mode firmware ?
> 
> This is also known as a managed exit. You should preferably find a way to reenter OP-TEE from M-mode firmware to let OP-TEE do a proper managed exit. If not you'll need to reenter OP-TEE on the core that received the normal world interrupt. That might make a mess in the kernel driver.

If I save the context of Op-TEE world in secure monitor, and when I have done jobs in normal world, and restore the context of Op-TEE world in secure monitor, is it applicable? If not, what is a proper managed exit?

Thank you

**Comment by fanghuaqi** [comment]
> > ```
> > How about asserting a fake interrupt to OPTEE which represents a foreign interrupt?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it seems not a common method
> 
> Hi @matthewgui
> 
> After studying [ARM FF-A 1.2 ALP0](https://developer.arm.com/documentation/den0077/f) section 9.3.1, seems ARM asserts virtual interrupt to enter OPTEE for thread suspending.
> 
> Before RISC-V supports NS/S interrupt identifying, I think this approach is applicable on current RISC-V. If PLIC does not support writable pending bit, maybe supervisor software interrupt pending (SSIP) can be used ?

Software interrupt maybe a good way to re-enter optee to do a managed exit without touch any optee context, and let optee do proper managed exit and return to monitor via ecall.

**Comment by gagachang** [comment]
> If I save the context of Op-TEE world in secure monitor, and when I have done jobs in normal world, and restore the context of Op-TEE world in secure monitor, is it applicable? If not, what is a proper managed exit?

Assume that OPTEE **HART 0** context is saved in secure monitor and return to REE by RPC with foreign interrupt.
Then REE migrates the task to **HART 1** and returns RPC via ecall.
In this case, the secure monitor will restore the context of **HART 1**, right?
Because secure monitor has no information about the task have been migrated from HART 0 to HART 1.

**Comment by gagachang** [comment]
> If I save the context of Op-TEE world in secure monitor, and when I have done jobs in normal world, and restore the context of Op-TEE world in secure monitor, is it applicable? If not, what is a proper managed exit?

If your system has only one hart, I think it is workable

**Comment by fanghuaqi** [comment]
> > If I save the context of Op-TEE world in secure monitor, and when I have done jobs in normal world, and restore the context of Op-TEE world in secure monitor, is it applicable? If not, what is a proper managed exit?
> 
> Assume that OPTEE **HART 0** context is saved in secure monitor and return to REE by RPC with foreign interrupt. Then REE migrates the task to **HART 1** and returns RPC via ecall. In this case, the secure monitor will restore the context of **HART 1**, right? But the correct previous TEE context is in **HART 0**.
> 
> Unless there are some hints to tell the secure monitor that it should also migrate the **HART 0** context to **HART 1**.

Ok, it make sense, it seems we have to let optee do the save and restore task, then a managed exit in s-mode is required.

**Comment by gagachang** [comment]
I am not expert of task migration.
How about disabling linux task migration during `optee_smc_do_call_with_arg()` ?

https://lwn.net/Articles/836503/

**Comment by jenswi-linaro** [comment]
> If I save the context of Op-TEE world in secure monitor, and when I have done jobs in normal world, and restore the context of Op-TEE world in secure monitor, is it applicable? If not, what is a proper managed exit?

For OP-TEE that means when `thread_state_suspend()` (or the corresponding thing for risc-v) has been called which enabled OP-TEE to later resume the work on any CPU core.

Without suspending the thread there may be CPU core specific references in the current state so it's only possible to resume on the same CPU core.

**Comment by jenswi-linaro** [comment]
> I am not expert of task migration. But how about disabling linux task migration during `optee_smc_do_call_with_arg()` ?
> 
> https://lwn.net/Articles/836503/

I guess it's possible, but you'd have to explain (on the LKML) why it's so much harder to support task migration on Risc-v than on Arm. I'd do the right thing from the start instead.

**Comment by gagachang** [comment]
> I guess it's possible, but you'd have to explain (on the LKML) why it's so much harder to support task migration on Risc-v than on Arm. I'd do the right thing from the start instead.

Yes you're right.
I think it's possible to support task migration on RISC-V by managed exit, we have mentioned the possible solutions in this ticket.

1. Let M-mode get NS interrupts first. M-mode can inject a fake interrupt (e.g., SGI) and enter OP-TEE to perform task suspending.
2. If interrupt **"re-pending"** is possible, OP-TEE can get all the interrupts first.
OP-TEE might know which interrupts are NS.
If the coming interrupt is NS, OP-TEE asserts pending bit again without completing that interrupt, and perform thread suspending.
Therefore REE can also get that interrupt soon after.

**Comment by fanghuaqi** [comment]
> > I guess it's possible, but you'd have to explain (on the LKML) why it's so much harder to support task migration on Risc-v than on Arm. I'd do the right thing from the start instead.
> 
> Yes you're right. I think it's possible to support task migration on RISC-V by managed exit, we have mentioned the possible solutions in this ticket.
> 
> 1. Let M-mode get NS interrupts first. M-mode can inject a fake interrupt (e.g., SGI) and enter OP-TEE to perform task suspending.
> 2. If interrupt **"re-pending"** is possible, OP-TEE can get all the interrupts first.
>    OP-TEE might know which interrupts are NS.
>    If the coming interrupt is NS, OP-TEE asserts pending bit again without completing that interrupt, and perform thread suspending.
>    Therefore REE can also get that interrupt soon after.

Thanks @jenswi-linaro @gagachang , we will take a try to re-enter optee via SWI or other ways to let optee save context.

**Comment by gagachang** [comment]
> Let M-mode get NS interrupts first. M-mode can inject a fake interrupt (e.g., SGI) and enter OP-TEE to perform task suspending.

I reference ARM's managed exit and draw an UML diagram for RISC-V solution.

![a](https://github.com/OP-TEE/optee_os/assets/43228610/96d3b99b-2309-4eb2-895d-7f0daf9cdf36)

**Comment by fanghuaqi** [comment]
> > we will take a try to re-enter optee via SWI or other ways to let optee save context.
> 
> Hi @fanghuaqi
> 
> Would you give some comments after you try it? Thanks!

Ok, when we have some results, we can comment on it.

**Comment by fanghuaqi** [comment]
Hi @gagachang, we are facing a lot of debug issue, no progress now.

**Comment by gagachang** [comment]
Hi @fanghuaqi 

Thanks for reply.
If you have anything to discuss please feel free to mention them here.

**Comment by matthewgui** [comment]
hi @gagachang  
Using software interrupts to notify optee doesn't work，becuase software interrupt is used by linux IPI interrupt，we
cannot break its state
Using plic interrupt to notify optee may be work，but the interrupt management is bit complicated, we have not continued to debug this

**Comment by gagachang** [comment]
> What if all NS/S interrupts are handled by OPTEE first when CPU is in OPTEE?
> 
> OPTEE knows which interrupt sources are secure interrupts, others are NS interrupt sources. If OPTEE gets an NS interrupt source by PLIC claim, OPTEE can ignore it. OPTEE just asserts that NS interrupt source pending bit again to PLIC, without completing the NS interrupt source. Then OPTEE suspends current thread, and CPU is switched back to REE.
> 
> Because NS interrupt source is still pended and have not been completed, REE can still get that NS interrupt by PLIC claim.

Did you try this way?
It might work if PLIC pending bits are writable.

**Comment by matthewgui** [comment]
> > What if all NS/S interrupts are handled by OPTEE first when CPU is in OPTEE?
> > OPTEE knows which interrupt sources are secure interrupts, others are NS interrupt sources. If OPTEE gets an NS interrupt source by PLIC claim, OPTEE can ignore it. OPTEE just asserts that NS interrupt source pending bit again to PLIC, without completing the NS interrupt source. Then OPTEE suspends current thread, and CPU is switched back to REE.
> > Because NS interrupt source is still pended and have not been completed, REE can still get that NS interrupt by PLIC claim.
> 
> Did you try this way? It might work if PLIC pending bits are writable.

local timer interrupt trap to M mode，so we cannot do that.

**Comment by gagachang** [comment]
> local timer interrupt trap to M mode，so we cannot do that.
No delegation support?

**Comment by matthewgui** [comment]
> > local timer interrupt trap to M mode，so we cannot do that.
> 
> No delegation support?

currently In our platform, timer trap to M mode whether or not set delegation. maybe in feature, our sstc feature can delegation timer to S mode directly

**Comment by gagachang** [comment]
Hello @fanghuaqi  @matthewgui 
Have you ever tried AIA such as APLIC ?

**Comment by fanghuaqi** [comment]
> Hello @fanghuaqi @matthewgui Have you ever tried AIA such as APLIC ?

currently no

**Comment by gagachang** [comment]
> currently no

OK thanks
I just think that APLIC (without IMSIC) has solution of your issue, and has greater interrupt performance than PLIC.
