### ISSUE TITLE
[Question] What to do with the old keys when upgrading OP-TEE

### ISSUE THREAD

**Issue by varder** [OP-TEE/optee_os#6078]
Suppose a user is trying to update the system with OP-TEE, for example from 3.15.0 to 3.19.0,
1. Is it possible to reuse objects in the folder(/data/tee) that contains TEE file-system or it should be cleared every time?
2. In what circumstances the /data/tee contents can or cannot be reused during the upgrade procedure?

**Comment by jenswi-linaro** [comment]
You should be able to reuse the object for all 3.x.0 releases. However, this is not something we're testing on a regular basis so it might be more of an intent than of a guarantee.
When the major version is bumped you'll need to check the release notes.

**Comment by jforissier** [comment]
Note also that `rm -rf /data/tee` will clear secure storage ONLY if RPMB is NOT used (that is, only when `CFG_REE_FS=y` AND `CFG_RMPB_FS=n`).
