### ISSUE TITLE
i want to know  what ATTESTATION_PTA  used for ?

### ISSUE THREAD

**Issue by coversky2018** [OP-TEE/optee_os#6079]
i search core/pta/attestation.c and xtest region_1000.c,  i  just know it can get RSA key and verify  tee mem or ta mem.
i don not know what ATTESTATION_PTA  can have Other usage scenarios ？ 
What kind of problem did this  come up with to solve ？

**Comment by jforissier** [comment]
In general this is about making sure that a device is actually running the code it is expected to run. For example if a TA connects to a server, the server may request a measurement of the TA. Suppose the TA has been tampered with in memory, or even has been replaced by a totally different TA with the same UUID, then the server will detect it and may refuse to provide the requested data. The attestation PTA is just a small piece in such a scenario. It allows to authenticate the TA and the device (via its public key).

**Comment by coversky2018** [comment]
ok  i understand it , thanks @jforissier
