### ISSUE TITLE
The object type  properties for ```TEE_TYPE_HMAC_SM3``` is problematic

### ISSUE THREAD

**Issue by soloicesky** [OP-TEE/optee_os#6083]
The object type  properties for ```TEE_TYPE_HMAC_SM3``` is problematic see below definition in ```/optee_os/core/tee/tee_svc_cryp.c```:
![image](https://github.com/OP-TEE/optee_os/assets/5044681/5ebe1477-2f6d-4119-ac96-92b54f28afc6)
![image](https://github.com/OP-TEE/optee_os/assets/5044681/52dec7ea-5e16-49c7-aea7-7f9cd275c479)
 the ```alloc_size```  should be no less than ```max_size```, otherwise, the crypto object doesn't have enough room to store the content.
For the ```TEE_TYPE_HMAC_SM3``` case, I think it should be ```PROP(TEE_TYPE_HMAC_SM3, 8, 80, 1024,
		1024 / 8 + sizeof(struct tee_cryp_obj_secret),```.
Please correct me if I am wrong.

**Comment by jforissier** [comment]
Please don't post screenshots. They don't get indexed by search engines, and they can't be copied/pasted which is annoying.

> For the `TEE_TYPE_HMAC_SM3` case, I think it should be `PROP(TEE_TYPE_HMAC_SM3, 8, 80, 1024, 1024 / 8 + sizeof(struct tee_cryp_obj_secret),`.
> Please correct me if I am wrong.

I think you're right. PR welcome!

Thanks.
