### ISSUE TITLE
how add openssl to os?

### ISSUE THREAD

**Issue by wsx11** [OP-TEE/optee_os#6085]
I want to include <openssl/*.h> in my ta.c file. But there is: No such file or directory error. How can I fix it? Thank you all!!

**Comment by jforissier** [comment]
Hello @wsx11, that is not supported. See https://github.com/OP-TEE/optee_os/issues/5884.

**Comment by wsx11** [comment]
> Hello @wsx11, that is not supported. See #5884.
OK, thanks!

**Comment by wsx11** [comment]
> @jforissier But in ca.c file, still this problem.No such file or directory.

@jforissier PLEASE!
