### ISSUE TITLE
Some questions about hikey

### ISSUE THREAD

**Issue by fanguannan0706** [OP-TEE/optee_os#609]
Hi,
I tried to add some libs to optee, when I compiled them on fvp, there is no error, but when I tried on hikey, I met some errors like "sorry, unimplemented: ‘-mgeneral-regs-only’ and floating point code".

**Comment by jforissier** [comment]
Hello @fanguannan0706,
You get this kind of errors when passing 64-bit compiler flags to a 32-bit cross compiler. So, you should double check your `CROSS_COMPILE*` settings.
Assuming you're on the latest optee_os master, to build OP-TEE with 64-bit support you typically need:
```
make PLATFORM=hikey CFG_ARM64_core=y CROSS_COMPILE_core=aarch64-linux-gnu- CROSS_COMPILE_ta_arm64=aarch64-linux-gnu-
```

**Comment by fanguannan0706** [comment]
Thank you for answer!
There is another question. I tried to compile the source and flash to hikey, and it seems finished. But when I boot it, it would stop at sometime and can't continue to run.

**Comment by fanguannan0706** [comment]
The last info is : [         8.273508]  random:  nonblocking pool is initialized.  Then it stops.

**Comment by fanguannan0706** [comment]
The boot process is like this:
![583348898107515877](https://cloud.githubusercontent.com/assets/9778175/12330979/992ee25e-bb22-11e5-90b4-835137de94e6.jpg)
