### ISSUE TITLE
Unhandled FFA

### ISSUE THREAD

**Issue by jwinarske** [OP-TEE/optee_os#6093]
I'm working on a TFA SPD=opteed and OP-TEEE (fTPM+RPMB).  Goal is SecureBoot support via UEFI for Rockchip.

I'm seeing this:
```
/TC:0   thread_spmc_register_secondary_ep:1654 FFA_SECONDARY_EP_REGISTER_64 ret 0xffffffffffffffff
E/TC:0   thread_spmc_msg_recv:1341 Unhandled FFA function ID 0xffffffff
```
Tight loop, never gets cleared.

I only have one segment from tee.elf preloaded.  Do I need multiple segments loaded in RAM?

My build config:
```
  make \
  CROSS_COMPILE=arm-none-linux-gnueabihf- \
  PLATFORM=rockchip-rk3399 \
  CFG_ARM64_core=y \
  CFG_RPMB_FS=y \
  CFG_RPMB_FS_DEV_ID=0 \
  CFG_CORE_HEAP_SIZE=524288 \
  CFG_RPMB_WRITE_KEY=y \
  CFG_CORE_DYN_SHM=y \
  CFG_RPMB_TESTKEY=y \
  CFG_REE_FS=n \
  CFG_CORE_ARM64_PA_BITS=48 \
  CFG_TEE_CORE_LOG_LEVEL=1 \
  CFG_TEE_TA_LOG_LEVEL=1 \
  CFG_SCTLR_ALIGNMENT_CHECK=n \
  CFG_TEE_BENCHMARK=n \
  CFG_CORE_SEL1_SPMC=y \
  CFG_ULIBS_SHARED=y \
  NOWERROR=1 \
  OPTEE_CLIENT_EXPORT=`pwd`/out/usr \
  TEEC_EXPORT=`pwd`/out/usr \
  EARLY_TA_PATHS=`pwd`/../../MSFT/ms-tpm-20-ref/Samples/ARM32-FirmwareTPM/optee_ta/out/fTPM/bc50d971-d4c9-42c4-82cb-343fb7f37896.stripped.elf \
  V=1 all mem_usage -j
```  

Do I need to have all tee.elf loadable regions prelocated, or do I only need `tee-pager_v2.bin`?

**Comment by jwinarske** [comment]
Also on the fTPM elf how does that get loaded?  Does it need to be prelocated relative to the pager, and if so at what offset?

```
fTPM/bc50d971-d4c9-42c4-82cb-343fb7f37896.stripped.elf
```
Has two loadable segments:
0x00000000.bin
0x00051000.bin

**Comment by jenswi-linaro** [comment]
Since you're building TF-A without FF-A support you should also build OP-TEE without FF-A support, that is, don't set `CFG_CORE_SEL1_SPMC=y`.

**Comment by jwinarske** [comment]
@jenswi-linaro That did the trick.  Thanks!
