### ISSUE TITLE
[RFC] Rename "mva" to "va"

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/optee_os#6099]
The terminology "mva" is specific for older ARM architecture which has FCSE extension [1].
To support multiple architecture, it would be good to rename "mva" to common terminology, such as "va".

Suggest renaming related functions in `core/mm/vm.c` and `core/include/mm/core_mmu.h`:
As is:
```
tlbi_mva_range()
tlbi_mva_range_asid()
```
To be:
```
tlbi_va_range()
tlbi_va_range_asid()
```

[1] https://developer.arm.com/documentation/ddi0406/c/Appendices/Fast-Context-Switch-Extension--FCSE-

**Comment by etienne-lms** [comment]
I'm fine with such a change. As Arm refer the mva for these instruction, the Arm implementation could wrap `tlbi_va_range()` to a call to arch specific `tlbi_mva_range()` and preserve its existing tlb_helpers functions implementation that is consistent with the architectures reference manuals.

**Comment by gagachang** [comment]
Dear @etienne-lms 

I have a local branch with commits which apply your suggestion. 
https://github.com/gagachang/optee_os/tree/rename-mva

Please take a look, thanks!

**Comment by jenswi-linaro** [comment]
Please propose this change in a pull request. It's much easier to review it in that format.

**Comment by gagachang** [comment]
Hi @jenswi-linaro 

Here is the proposed PR: https://github.com/OP-TEE/optee_os/pull/6101

**Comment by gagachang** [comment]
Since https://github.com/OP-TEE/optee_os/pull/6101 has already been merged, I close this ticket.
