### ISSUE TITLE
newer release

### ISSUE THREAD

**Issue by angusmart** [OP-TEE/optee_os#610]
We want to configure a new environment in juno and it Include Secure Boot； but when we get the setup_juno_optee.sh in the github and found the commit is too old, such as  STABLE_ARM_TF_COMMIT is Nov 20 14:16:38 2014. 
who can give me an newer release which can runing Secure Boot well.

**Comment by jbech-linaro** [comment]
Hi @angusmart ,

As you probably have seen in the README.md, the current Juno setup is "broken". We should fix it, it's just that we haven't been able to free up any engineer to work with it. Meanwhile waiting for a proper fix you can try this:

```
mkdir ~/my_juno_working_dir && cd ~/my_juno_working_dir
repo init -u https://github.com/pascal-brand-st-dev/manifest.git -m juno.xml -b juno_enabler
repo sync
cd build
make toolchains
make all
```

// Joakim

**Comment by pascal-brand-st-dev** [comment]
https://github.com/OP-TEE/manifest/pull/17 allows a juno setup using the repo way. Documentation is currently being written.

Please close this issue if it answers.

**Comment by pascal-brand-st** [comment]
up-to-date repo manifest are now available for Juno.
