### ISSUE TITLE
Ask a question: Are there any non-blocking interrupt wait functions available in optee_os repo?

### ISSUE THREAD

**Issue by wangxiang-github** [OP-TEE/optee_os#6103]
### Background
I want to implement an i2c driver in my local optee_os repo, i2c driver has two main interfaces: `i2c_read` and `i2c_write`, both of which invoke the `i2c_transfer` interface, which waits for the interupt event to return and processes data. And the interrupt event handling function is `i2c_handler_interrupts`, which will invoke `i2c_handler_cb` functions to process data transfer, data acceptance, data error and return the processing result.
### A simple i2c driver invoke relationship is implemented as follows:
```
void i2c_init()
{
    /* address mapping */
    itr_add(i2c_itr_handler);
    itr_enable(i2c_itr_handler.it);
}
driver_init(i2c_init);

static struct itr_handler i2c_itr_handler = {
    .it = I2C_IRQ_0, /* a valid value */
    .flags = ITRF_TRIGGER_LEVEL,
    .handler = i2c_handler_interrupts,
};

static enum itr_return i2c_handler_interrupts(struct itr_handler *handler)
{
    /* pointer handling */
    i2c_handler_cb(*msg_pointer);
}
static TEE_Result i2c_transfer(struct i2c_msg *p_msg)
{
    /* organize a set of frame data */

    /* A non-blocking function is needed here to wait for the return of the interrupt event. */
    wait_for_completion_timeout();
}

TEE_Result i2c_read(struct i2c_msg *p_msg)
{
    return i2c_transfer(p_msg);
}
TEE_Result i2c_write(struct i2c_msg *p_msg)
{
    return i2c_transfer(p_msg);
}

```
### Therefore
In `i2c_transfer`, I need a non-blocking interrupt wait function to wait for the return of interrupt event, just like `wait_for_completion_timeout` function in the kernel, but I can't find any non-blocking functions in the optee_os repo like the one in kenel. So my question is, does the optee_os have a non-blocking interrupt wait function? if not, how do I process such internal interrupts? Only the polling approach is available for this?

If you know how to solve this problem, thank you for your answer.
Best Regards!

**Comment by jenswi-linaro** [comment]
There's an example in https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-vexpress/main.c where the UART is optionally read from using a bottom half thread.

**Comment by wangxiang-github** [comment]
> Hi jenswi-linaro:
 Sorry, I have a little confused about this example, I don't use any threads in my i2c driver, Is this example suitable for this i2c driver? In other words, do I need to register `console_notif` structure and implement the interrupt handling operations in the `yielding_cb`?

**Comment by jenswi-linaro** [comment]
If you'd rather block the current thread instead you could wait with `notif_wait()` on a value previously allocated with `notif_alloc_async_value()`. Then when getting called in `i2c_handler_interrupts()` you can notify the waiting thread with `notif_send_async()` using the previously obtained value.

**Comment by wangxiang-github** [comment]
As far as I am understand, 
1) I need to alloc a **sync value** via `notif_alloc_async_value` function in i2c driver initialization. 
2) The `notif_wait` function is invoked directly by `i2c_transfer` to wait for the previous **sync value**.
3) The function `i2c_handler_interrupts` invokes `notif_send_async` to notify the waiting thread to handle interrupt by sending **sync value**. 

If I use this process, do I still need to register the structure `notif_driver` by function `notif_register_driver`?
```
struct notif_driver {
	void (*atomic_cb)(struct notif_driver *ndrv, enum notif_event ev);
	void (*yielding_cb)(struct notif_driver *ndrv, enum notif_event ev);
	SLIST_ENTRY(notif_driver) link;
};
```

**Comment by jenswi-linaro** [comment]
> If I use this process, do I still need to register the structure `notif_driver` by function `notif_register_driver`?

No, that shouldn't be needed.
