### ISSUE TITLE
Q: bus error occurs in EL1h

### ISSUE THREAD

**Issue by coach-bin** [OP-TEE/optee_os#6106]
Hi,
I'm porting OPTEE.
When optee_msg_api_uid_is_optee_api() is called from linux optee_probe(), the system stucked. I attached T32 debugger and saw the states. CPU is in EL1h and PC is el1_sync_sp1, but bus error occurs so all the code memory is displayed with ???????? in T32

Is there any point that I should check?

**Comment by jenswi-linaro** [comment]
There are so many things that could have gone wrong at this point. I'd start checking that the secure state is properly restored when S-EL1 is entered, especially with regards to memory mapping since that seems suspect at this point.

**Comment by coach-bin** [comment]
@jenswi-linaro, Thanks for your answer.
My understanding is that core_init_mmu_map() will generate a translation table automatically as platform-defined configuration. And I got a debug message like below. (0x2103000 is where optee_probe jumps to.)
D/TC:0          [LVL3] VA:0x00020ff000 INVALID
D/TC:0          [LVL3] VA:0x0002100000 PA:0x0002100000 MEM-RO-XN-S (CFG_TZDRAM_START)
D/TC:0          [LVL3] VA:0x0002101000 PA:0x0002101000 MEM-RO-X -S (CFG_TEE_LOAD_ADDR)
D/TC:0          [LVL3] VA:0x0002102000 PA:0x0002102000 MEM-RO-X -S
D/TC:0          [LVL3] VA:0x0002103000 PA:0x0002103000 MEM-RO-X -S
D/TC:0          [LVL3] VA:0x0002104000 PA:0x0002104000 MEM-RO-X -S

From this log, I thought that there is no problem in memory mapping. But I'm still wondering if  there is any extra point that I need to check.

And can you elaborate about how I can check that the secure state is properly restored when S-EL1 is entered?

**Comment by jenswi-linaro** [comment]
I'm sorry, it's a bit too much to cover and I don't have a clue as to what changes you have made.

Since you have a debugger, try setting a breakpoint as early as possible on re-entry to OP-TEE to try to figure out why the memory can't be accessed.

**Comment by coach-bin** [comment]
I found a problem - another FW overwrites the OPTEE OS code area, causing the problem. Closing this issue. Thanks for support
