### ISSUE TITLE
Implement i.MX power and clock management _or_ drop i.MX support

### ISSUE THREAD

**Issue by DemiMarie** [OP-TEE/optee_os#6114]
These need to be implemented in the secure world on these platforms.

**Comment by zandrey** [comment]
This is done as part of _TF-A_ PSCI implementation, is it not?

Since there are no additional information on the _i.MX_ derivative or family used, I would assume that _AArch64_-based SOCs are mentioned.

This implies that one cannot start the _i.MX8[M]_ derivatives without _TF-A_, so why an explicit interface is required in _OP-TEE_ as well?

**Comment by DemiMarie** [comment]
@zandrey I’m referring to GHSA-4pqr-q8rf-8464, which was due to stuff being handled in the non-secure world that needed to be handled in the secure world.

**Comment by DemiMarie** [comment]
Still a problem.

**Comment by DemiMarie** [comment]
I strongly believe that OP-TEE should not support a platform if it cannot support the platform securely.  My understanding is that there are some i.MX platforms where:

- Power and clock management is currently handled by the normal world.
- Preventing normal ⇒ secure world privilege escalation requires that power and clock management be handled in the secure world.
- There is no secure-world software with the needed power and clock management support.

In this case, having OP-TEE claim to support these platforms is misleading, as they are only supported in an insecure configuration and a significant amount of new development would be needed to support them in a secure configuration.

However, @zandrey pointed out in https://github.com/OP-TEE/optee_os/issues/6114#issuecomment-1597463718 that TF-A does have the needed support.  In this case, I think the safest option is to make TF-A support a hard requirement on platforms vulnerable to https://github.com/OP-TEE/optee_os/security/advisories/GHSA-4pqr-q8rf-8464.  Configuring the system correctly would then be TF-A’s responsibility, which avoids system integrators thinking their system is secure when it is not.

**Comment by jenswi-linaro** [comment]
> I strongly believe that OP-TEE should not support a platform if it cannot support the platform securely. 

This might become a problem since upstream OP-TEE doesn't support any platform securely, at least all platforms will print
```
I/TC: WARNING: This OP-TEE configuration might be insecure!
I/TC: WARNING: Please check https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html
```
in the default configuration.

Anyway, if there's something you feel should be changed feel free to propose it in pull requests.
