### ISSUE TITLE
optee 3.21.0: core: mobj_reg_shm_dec_map

### ISSUE THREAD

**Issue by omasse-linaro** [OP-TEE/optee_os#6120]
Hi

I'm getting an assert in reg_shm_unmap_helper when performing a simple stress test with two threads which invoke in a infinite loop a ping command to a TA with an input shared memory as parameter.

E/TC:1 1 assertion 'r->mm' failed at core/arch/arm/mm/mobj_dyn_shm.c:117 <reg_s>
E/TC:1 1 Panic at core/kernel/assert.c:28 <_assert_break>
E/TC:1 1 TEE load address @ 0xe1b32000

it seems that reg_shm_unmap_helper is called by mobj_reg_shm_dec_map when the mapcount reach 0 with an already unmapped object.

looking at the refcount.h (core/include/kernel/refcount.h) it is specify that when refcount_dec(r) is true, the object o is uninitialize if refcount_val(r) is still 0 AND o is not NULL.

however mobj_reg_shm_dec_map in core/arch/arm/mm/mobj_dyn_shm.c do not check if r->mm is not NULL before calling reg_shm_unmap_helper.

doing so, my stress test run fine without assert.
could we have a race condition when two threads call to mobj_reg_shm_dec_map occur at the same time ?

after doing refcount_dec on mapcount, thread 1 take the lock before thread 2 and call reg_shm_unmap_helper and release the lock.
thread 2 then take the lock and call reg_shm_unmap_helper as well, which fail with assert(r->mm).

**Comment by jenswi-linaro** [comment]
Each call to `mobj_dec_map()` must be matched by a previous call to `mobj_inc_map()`. When that rule is followed then the race you're describing can't occur.

I believe the real problem is that the `mobj_inc_map()` and `mobj_dec_map()` calls are unbalanced for some reason.

**Comment by omasse-linaro** [comment]
indeed, I see that you have fix a race issue in mobj_reg_shm_inc_map, but why not just get the reg_shm_map_lock spin lock before incrementing or decrementing the map refcount ?

**Comment by omasse-linaro** [comment]
Yes, I just reproduce the issue with qemu as well.
![Screenshot from 2023-06-21 11-27-52](https://github.com/OP-TEE/optee_os/assets/4939714/c1073263-4398-485f-9802-279e12c8fd7a)

**Comment by omasse-linaro** [comment]
draft submitted here https://github.com/OP-TEE/optee_os/pull/6133

**Comment by jenswi-linaro** [comment]
What's regression case 1040?

**Comment by omasse-linaro** [comment]
It's a dedicated added test that ping a TA with an input shared memory.
PFA a patch for optee_test.
[xtest_1040.zip](https://github.com/OP-TEE/optee_os/files/11870410/xtest_1040.zip)

**Comment by jenswi-linaro** [comment]
> It's a dedicated added test that ping a TA with an input shared memory. PFA a patch for optee_test. [xtest_1040.zip](https://github.com/OP-TEE/optee_os/files/11870410/xtest_1040.zip)

Thanks

**Comment by jenswi-linaro** [comment]
What are the steps needed to reproduce the problem on QEMU?
I understand that I need https://github.com/OP-TEE/optee_test/pull/663, but what else is needed? Which flags do you compile OP-TEE with? Which patches do you have in OP-TEE OS?

**Comment by omasse-linaro** [comment]
Test was done on optee os master branch at revision https://github.com/OP-TEE/optee_os/commit/504f15942ec89ec4cc4c0090217e02301edd1fdb
Test fail without any added patches.

OP-TEE is build with CFG_TEE_CORE_LOG_LEVEL set to 1.
```make run CFG_TEE_CORE_LOG_LEVEL=1```

**Comment by jenswi-linaro** [comment]
Can you reproduce the problem with https://github.com/OP-TEE/optee_os/pull/6137?

**Comment by omasse-linaro** [comment]
No, issue is fixed with that patch.

**Comment by omasse-linaro** [comment]
Thanks, let's close this issue.
