### ISSUE TITLE
Global Platform TEE Core internal API version - mismatch between the document and code?

### ISSUE THREAD

**Issue by zjchen666** [OP-TEE/optee_os#6134]
Hello OPTEE team,
    I have been referring to the OPTEE documentation, specifically the section on the Global Platform TEE Core internal API, which states that the version used is v1.1. (https://optee.readthedocs.io/en/latest/faq/faq.html#q-which-apis-have-been-implemented-in-op-tee)
    However, upon reviewing the codebase, I noticed that there have been updates in line with version 1.3.1. This has led to some confusion regarding the actual version being used in OPTEE.
    https://github.com/OP-TEE/optee_os/commits/master/lib/libutee/include/tee_internal_api.h

Could you kindly provide some clarification on this? I would greatly appreciate it if you could shed light on whether the documentation needs updating or if there is any specific reason for the codebase reflecting version 1.3.1 while the documentation mentions v1.1. I want to ensure I'm using the most accurate information. Thanks.

**Comment by jenswi-linaro** [comment]
It's the documentation that needs updating. Patches are welcome! :-)

**Comment by etienne-lms** [comment]
Indeed, I've created https://github.com/OP-TEE/optee_docs/pull/200 as proposal.

**Comment by zjchen666** [comment]
Do we have any documentation or notes that captures the correlation between OPTEE OS releases and the versions of the internal Core API used in the GP platform's TEE?
For instance: OPTEE OS release v3.xx -> GP TEE internal API 1.3.1. 
thanks

**Comment by jenswi-linaro** [comment]
It was included in the 3.21.0 release.

**Comment by zjchen666** [comment]
@jenswi-linaro  
Do you mean this file?  
https://github.com/OP-TEE/optee_os/blob/master/CHANGELOG.md
I'm unable to locate the information related to the GP TEE Core API versions 1.2.x and 1.3.x in this file. 
Could you please provide more insights or guidance?
thanks

**Comment by jenswi-linaro** [comment]
The git history is the truth:
``` bash
%git log --oneline|grep GP131|head -1 
3b439c8fc172 GP131: Fix the TEE_ALG_SM2_PKE define
%git tag --contains=3b439c8fc172
3.21.0
3.21.0-rc1
```

**Comment by etienne-lms** [comment]
@zjchen666, maybe you want to post a comment or an Acked-by tag for https://github.com/OP-TEE/optee_docs/pull/200?

**Comment by zjchen666** [comment]
`Acked-by: Zhijun Chen <zhijunc@netflix.com>`

**Comment by zjchen666** [comment]
Done. thanks
