### ISSUE TITLE
What does decide the value of CFG_SHMEM_START/CFG_SHMEM_SIZE?

### ISSUE THREAD

**Issue by jiameixie** [OP-TEE/optee_os#6140]
We are working on enabling Optee for a new platform. When loading the FFA driver, it fails in [ffa_rxtx_map](https://elixir.bootlin.com/linux/v6.1.25/source/drivers/firmware/arm_ffa/driver.c#L815) . From the source code, the tx/rx buffers are allocated from the heap directly.  Optee-os will map it. Function [spmc_handle_rxtx_map ](https://github.com/OP-TEE/optee_os/blob/cabb8df35bc345d18102a477427939b1610cd8bb/core/arch/arm/kernel/thread_spmc.c#L237) in  Optee-os will invoke map_buf. map_buf will check if the pa is nonsecure memory.  I add some logs and find it will check if the tx/rx buffer pa is in the range of
CFG_SHMEM_START - CFG_SHMEM_START+CFG_SHMEM_SIZE.

I have some confusion. The FFA driver allocates tx/rx buffer from the Linux heap. The physical address of tx/rx buffer might be in a large range.  What does decide the value of [CFG_SHMEM_START](https://github.com/OP-TEE/optee_os/blob/cabb8df35bc345d18102a477427939b1610cd8bb/core/arch/arm/plat-corstone1000/conf.mk#L38C1-L38C1) and CFG_SHMEM_SIZE?

Is there any agreement between Linux and Optee about which memory area is used for rx/tx buffer? AFAIK, Optee is configurable while Linux is not about the memory area. So Optee should obey the principle of Linux and set the whole Linux heap range as the shared memory? But for corstone1000, it sets CFG_SHMEM_SIZE 0x20000(2M), which might not the whole Linux heap range.

So I am really confused. Could someone please tell me how to decide the value of CFG_SHMEM_START and CFG_SHMEM_SIZE? Thanks.

**Comment by jenswi-linaro** [comment]
CFG_SHMEM_START, CFG_SHMEM_SIZE, and CFG_CORE_RESERVED_SHM should not be used with FF-A. FF-A used dynamically shared memory only so reserved shared memory would remain unused and wasted.

OP-TEE is supposed to be able to use any valid physical memory supplied by the kernel, so no special agreement is needed.

**Comment by jiameixie** [comment]
Hi @jenswi-linaro,
  Do you mean disabling CFG_CORE_RESERVED_SHM when FF-A is used?

I have a try by setting CFG_CORE_RESERVED_SHM=n, but it still fails to map tx/rx buffer. In the function [map_buf](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread_spmc.c#L204), it will check if the memory is CORE_MEM_NON_SEC by invoking [core_pbuf_is](https://github.com/OP-TEE/optee_os/blob/master/core/mm/core_mmu.c#L1491). 
```
	case CORE_MEM_NON_SEC:
		return pbuf_is_inside(nsec_shared, pbuf, len) ||
			pbuf_is_nsec_ddr(pbuf, len);
```

And I added some logs and found both `pbuf_is_inside` and `pbuf_is_nsec_ddr` are 0. So it failed to map the buffer.

`E/TC:12   core_pbuf_is:1428, pbuf_is_inside:0x0,pbuf_is_nsec_ddr:0x0
`

**Comment by jenswi-linaro** [comment]
If you're not using S-EL2 then you need to register all non-secure DDR that might be used as shared memory using `register_ddr()`, see for instance `core/arch/arm/plat-vexpress/main.c`

**Comment by jiameixie** [comment]
@jenswi-linaro Yes, S-EL2 is not used. By registering all non-secure DDR, it succeeded to map tx/rx buffer. Thanks very much.
