### ISSUE TITLE
Question about memory configuration

### ISSUE THREAD

**Issue by coach-bin** [OP-TEE/optee_os#6141]
1. I found that my configuration has both CFG_CORE_DYN_SHM=y and CFG_CORE_RESERVED_SHM=y. Then what is the highest priority?

2.  If I use CFG_CORE_DYN_SHM=y, CFG_SHMEM_START and CFG_SHMEM_SIZE will be ignored in optee? and I donot need to reserve the shared memory(CFG_SHMEM_START~) from linux kernel?

3. My linux kernel dts has some reserved memories in DDR. In this case, should I avoid to register these areas with register_ddr() from OPTEE? (Currently I registered all the DDR range with register_ddr(), but I wonder if I need to exclude the reserved memory being used by linux kernel)

**Comment by jenswi-linaro** [comment]
1 & 2:
The Linux kernel OP-TEE driver will first try dynamic shared memory (CFG_CORE_DYN_SHM=y) and if that fails try static shared memory(CFG_CORE_RESERVED_SHM=y).

OP-TEE Core in the secure world doesn't prioritize shared memory schemes. I'd recommend using CFG_CORE_DYN_SHM=y and CFG_CORE_RESERVED_SHM=n unless you have some special requirement where a static memory pool for shared memory must be used.

CFG_CORE_RESERVED_SHM=n has the advantage that you don't need to update the kernel DTS to match CFG_SHMEM_START and CFG_SHMEM_SIZE.

3:
register_ddr() is used to let OP-TEE know which memory is safe to map as non-secure memory. The main objective is to avoid asynchronous external aborts if the normal world should try to supply an invalid physical address. OP-TEE will not map or use any non-secure memory unless the normal world has requested OP-TEE to use it as shared memory. So if you trust the kernel to not use your reserved DDR memory ranges there's no need to exclude those in OP-TEE, but if it might be related to some level of security it may add another level of defense to exclude it.

**Comment by coach-bin** [comment]
@jenswi-linaro It's very clear and it help me understand more  :)  Thanks!
