### ISSUE TITLE
How to improve performance of TEEC_InvokeCommand?

### ISSUE THREAD

**Issue by wangym307** [OP-TEE/optee_os#6142]
Hi expert,
    My environment:optee 3.20 version, CFG_CORE_FFA=y, CFG_CORE_DYN_SHM=y, CFG_CORE_RESERVED_SHM=n
    We assume that there is a certain scenario where TEEC_InvokeCommand could be called frequently by one TA, so I'm testing time of TEEC_InvokeCommand and trying to improve it.
    Now, I found that TEEC_MEMREF_PARTIAL_INOUT spend less time than TEEC_MEMREF_TEMP_INOUT, because we needn't to allocate share memory every time when calling TEEC_InvokeCommand. however, 
1.when `MY_SHM_SIZE=4*1024(4kB)`, TEEC_InvokeCommand cost about 20 us;
2.when `MY_SHM_SIZE=1*1024*1024(1MB)`, TEEC_InvokeCommand cost about **400 us**;
    My key code is as below:
```
ecall_shm.size = 4*1024*1024;
ecall_shm.flags = TEEC_MEM_INPUT | TEEC_MEM_OUTPUT;
TEEC_RegisterSharedMemory(session.ctx, &ecall_shm);

op.params[1].memref.parent = &ecall_shm;
op.params[1].memref.offset = 0;
op.params[1].memref.size = MY_SHM_SIZE;
res = TEEC_InvokeCommand(
    &session, MY_FUNC_ID, &op, &err_origin);
```
  I have tested ecall time of sgx, it seems much faster than optee when share memory raise to 1MB.
  how can I reduce time(400 us) of TEEC_InvokeCommand when share memory size reaches 1MB or bigger?

**Comment by jenswi-linaro** [comment]
This relates a bit to https://lists.trustedfirmware.org/archives/list/op-tee@lists.trustedfirmware.org/thread/FWLOMOHOU3C2VZJWFOO5JQIXLQHS5ASM/

It would be A good start to try to figure out where the increased time is spent.

Please note that OP-TEE originates from a memory-constrained environment where a small memory footprint may have been prioritized over performance. When you start to push the boundaries like you do here you're bound to find new bottlenecks and opportunities for optimization.
