### ISSUE TITLE
Software vulnerabilities investigation on OP-TEE

### ISSUE THREAD

**Issue by janislley** [OP-TEE/optee_os#6145]
Hello.

I am performing some tests on op-tee as a security investigative report.
During the tests, potential software vulnerabilities were found.
To identify this kind of vulnerabilities it was used the tool ESBMC-WR: https://github.com/janislley/esbmc-wr

More about the tool: https://arxiv.org/pdf/2102.02368.pdf

Tests were performed in the latest OP-TEE version.
Please let me know if you need more reports or information regarding the tests.

Check the logs of the verification:

Issue 1 - Security code violation: division by zero
----------------------------------------------------

########################################
[FILE] core/tee/tee_cryp_pbkdf2.c
[ARGS] ['--unwind', '1', '--no-unwinding-assertions']
[FUNCTION] tee_cryp_pbkdf2
########################################

Counterexample:

State 1 file tee_cryp_pbkdf2.c line 78 function tee_cryp_pbkdf2 thread 0
out = 0

State 2 file tee_cryp_pbkdf2.c line 82 function tee_cryp_pbkdf2 thread 0

hmac_parms.algo = { .algo=805306368 | hash_id&0#0, .anon_pad$1=0, .hash_len=0,
.ctx=0 }

State 5 file tee_cryp_pbkdf2.c line 92 function tee_cryp_pbkdf2 thread 0

pbkdf2_parms.password = { .pointer_object=nil, .pointer_offset=nil }

State 6 file tee_cryp_pbkdf2.c line 93 function tee_cryp_pbkdf2 thread 0

pbkdf2_parms.password_len = 0 (00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000)

State 7 file tee_cryp_pbkdf2.c line 94 function tee_cryp_pbkdf2 thread 0

pbkdf2_parms.salt = 0

State 8 file tee_cryp_pbkdf2.c line 95 function tee_cryp_pbkdf2 thread 0

pbkdf2_parms.salt_len = 0 (00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000)

State 9 file tee_cryp_pbkdf2.c line 96 function tee_cryp_pbkdf2 thread 0

pbkdf2_parms.iteration_count = 0 (00000000 00000000 00000000 00000000)

State 10 file tee_cryp_pbkdf2.c line 98 function tee_cryp_pbkdf2 thread 0

Violated property:
file tee_cryp_pbkdf2.c line 98 function tee_cryp_pbkdf2
division by zero
hmac_parms.hash_len != 0

VERIFICATION FAILED

Issue 2 - Security code violation: array bounds violated
----------------------------------------------------

########################################
[FILE] lib/libmbedtls/mbedtls/library/ecdsa.c
[ARGS] ['--unwind', '1', '--no-unwinding-assertions']
[FUNCTION] ecdsa_signature_to_asn1
########################################

Counterexample:

State 2 file asn1write.h line 39 function ecdsa_signature_to_asn1 thread 0

len = 805306359 (00000000 00000000 00000000 00000000 00101111 11111111 11111111 11110111)

State 4 file asn1write.h line 39 function ecdsa_signature_to_asn1 thread 0

len = 1610612718 (00000000 00000000 00000000 00000000 01011111 11111111 11111111 11101110)

State 6 file asn1write.h line 39 function ecdsa_signature_to_asn1 thread 0

len = 3221225436 (00000000 00000000 00000000 00000000 10111111 11111111 11111111 11011100)

State 8 file asn1write.h line 39 function ecdsa_signature_to_asn1 thread 0

len = 4294967256 (00000000 00000000 00000000 00000000 11111111 11111111 11111111 11011000)

State 10 file string.c line 264 function memcpy thread 0

Violated property:
file string.c line 264 function memcpy
dereference failure: array bounds violated

########################################
[FILE] lib/libutee/tee_api_objects.c
[ARGS] ['--unwind', '1', '--no-unwinding-assertions']
[FUNCTION] TEE_GenerateKey
########################################

ESBMC version 6.7.0 64-bit x86_64 linux
file lib/libutee/tee_api_objects.c: Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.096s
GOTO program processing time: 0.001s
Starting Bounded Model Checking
**** WARNING: no body for function __utee_check_attr_in_annotation
Not unwinding loop 16 iteration 1 file tee_api_objects.c line 19 function __utee_from_attr
**** WARNING: no body for function _utee_cryp_obj_generate_key
**** WARNING: no body for function TEE_Panic
Symex completed in: 0.012s (121 assignments)
Slicing time: 0.000s (removed 100 assignments)
Generated 19 VCC(s), 11 remaining after simplification (21 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.037s
Solving with solver Boolector 3.2.0
Encoding to solver time: 0.037s
Runtime decision procedure: 0.026s
Building error trace

Counterexample:

State 1 file tee_api_objects.c line 20 function __utee_from_attr thread 0

Violated property:
file tee_api_objects.c line 20 function __utee_from_attr
dereference failure: array bounds violated

########################################
[FILE] lib/libutils/isoc/strndup.c
[ARGS] ['--unwind', '1', '--no-unwinding-assertions']
[FUNCTION] strndup
########################################

Counterexample:

State 1 file strndup.c line 10 function strndup thread 0

l = 2593440088142643200 (00100011 11111101 11000000 00000101 00000000 00000000 00000000 00000000)

State 2 file strndup.c line 11 function strndup thread 0

p = &dynamic_1_array[0]

State 5 file string.c line 264 function memcpy thread 0

Violated property:
file string.c line 264 function memcpy
dereference failure: array bounds violated

VERIFICATION FAILED

Issue 3 - Security code violation: invalid pointer freed
----------------------------------------------------

########################################
[FILE] core/crypto/aes-gcm.c
[ARGS] ['--unwind', '1', '--no-unwinding-assertions']
[FUNCTION] aes_gcm_free_ctx
########################################

Counterexample:

State 2 file util.h line 113 function to_aes_gcm_ctx thread 0

__ptr = 0

State 3 file aes-gcm.c line 451 function aes_gcm_free_ctx thread 0

Violated property:
file aes-gcm.c line 451 function aes_gcm_free_ctx
dereference failure: invalid pointer freed

########################################
[FILE] lib/libmbedtls/core/hash.c
[ARGS] ['--unwind', '1', '--no-unwinding-assertions']
[FUNCTION] mbed_hash_free_ctx
########################################

Counterexample:

State 2 file util.h line 113 function to_hash_ctx thread 0

__ptr = 0

State 3 file hash.c line 86 function mbed_hash_free_ctx thread 0

hc = invalid-object

State 4 file hash.c line 89 function mbed_hash_free_ctx thread 0

Violated property:
file hash.c line 89 function mbed_hash_free_ctx
dereference failure: invalid pointer freed

VERIFICATION FAILED

Issue 4 - Security code violation: invalid pointer
----------------------------------------------------

########################################
[FILE] lib/libmbedtls/core/sm2-pke.c
[ARGS] ['--unwind', '1', '--no-unwinding-assertions']
[FUNCTION] sm2_point_to_bytes
########################################

Counterexample:

State 1 file sm2-pke.c line 274 function sm2_point_to_bytes thread 0

xsize = 0 (00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000)

State 2 file sm2-pke.c line 275 function sm2_point_to_bytes thread 0

ysize = 0 (00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000)

State 3 file sm2-pke.c line 279 function sm2_point_to_bytes thread 0

Violated property:
file sm2-pke.c line 279 function sm2_point_to_bytes
dereference failure: invalid pointer

########################################
[FILE] lib/libmbedtls/mbedtls/library/pkwrite.c
[ARGS] ['--unwind', '1', '--no-unwinding-assertions']
[FUNCTION] mbedtls_pk_write_key_der
########################################

Counterexample:

State 1 file pkwrite.c line 324 function mbedtls_pk_write_key_der thread 0

c = 0 + 9223372036854775805

State 3 file pkwrite.c line 408 function mbedtls_pk_write_key_der thread 0

ec = 0

State 5 file pkwrite.c line 427 function mbedtls_pk_write_key_der thread 0

c = 0 - 1

State 11 file pkwrite.c line 147 function pk_write_ec_param thread 0

Violated property:
file pkwrite.c line 147 function pk_write_ec_param
dereference failure: NULL pointer

VERIFICATION FAILED

Issue 5 - Security code violation: Null pointer
----------------------------------------------------

########################################
[FILE] core/lib/libfdt/fdt.c
[ARGS] ['--unwind', '1', '--no-unwinding-assertions']
[FUNCTION] fdt_check_node_offset_
########################################

Counterexample:

State 1 file fdt.c line 135 function fdt_next_tag thread 0

offset = 0 (00000000 00000000 00000000 00000000)

State 2 file libfdt.h line 129 function fdt32_ld thread 0

bp = 0

State 7 file fdt.c line 116 function fdt_offset_ptr thread 0

absoffset = 65537 (00000000 00000001 00000000 00000001)

State 8 file libfdt.h line 129 function fdt32_ld thread 0

bp = 0

State 13 file libfdt.h line 129 function fdt32_ld thread 0

bp = 0

State 18 file libfdt.h line 129 function fdt32_ld thread 0

bp = 0

State 23 file libfdt.h line 129 function fdt32_ld thread 0

bp = 0

State 28 file fdt.c line 139 function fdt_next_tag thread 0

tagp = (unsigned int *)0

State 29 file fdt.c line 142 function fdt_next_tag thread 0

Violated property:
file fdt.c line 142 function fdt_next_tag
dereference failure: NULL pointer

VERIFICATION FAILED

**Comment by jforissier** [comment]
Hi @janislley,

I don't know this ESBMC-WR tool, but my first impression is that it may easily give false positives. Let's consider issue 5 for instance:

>  [FILE] core/lib/libfdt/fdt.c
> [...]
> State 28 file fdt.c line 139 function fdt_next_tag thread 0
> 
> tagp = (unsigned int *)0
> 
> State 29 file fdt.c line 142 function fdt_next_tag thread 0
> 
> Violated property: file fdt.c line 142 function fdt_next_tag dereference failure: NULL pointer

The code is:
```C
/* 139 */		tagp = fdt_offset_ptr(fdt, offset, FDT_TAGSIZE);
/* 140 */		if (!tagp)
/* 141 */			return FDT_END; /* premature end */
/* 142 */		tag = fdt32_to_cpu(*tagp);
```

As you can see, there is a check against `tagp` being a NULL pointer, so that diagnostic is clearly bogus. Such an obvious false positive doesn't give me much confidence in the quality of the tool, to be honest.

Same goes for issue 4. `sm2_point_to_bytes()` is only called once with the `size_t *size` parameter being the address of a local variable (`&C`), which by construction cannot be an invalid pointer.

It is perfectly fine to use tools to help find issues, but please do some sanity checks before reporting here (and preferably with a suggestion on how to fix the issue). Thanks!

**Comment by janislley** [comment]
Hello @jforissier 
Thanks for the quick report.

ESBMC tool is a reference model checking tool commonly used in the industry by large companies. Check more details: https://github.com/esbmc/esbmc
ESBMC-wr is a whapper to check large open-source projects automatically. 

A set of sanity checks were made in order to check false positives cases. 
Indeed, issues 4 and 5 are false positives. Maybe issue 3 too.

If you consider, I suggest checking issues 1 and 2.
I can give more reports if you need them.

**Comment by jbech-linaro** [comment]
Also a side-note, this is already here in public, but for true and demonstrable security incidents, in those cases, please reporting according to [this](https://optee.readthedocs.io/en/latest/general/contact.html#vulnerability-reporting).

**Comment by janislley** [comment]
Got it @jbech-linaro.
Thanks for checking.
I will close the ticket and from now on open cases if found as you requested.

**Comment by jforissier** [comment]
> Hello @jforissier Thanks for the quick report.
> 
> ESBMC tool is a reference model checking tool commonly used in the industry by large companies. Check more details: https://github.com/esbmc/esbmc ESBMC-wr is a whapper to check large open-source projects automatically.
> 
> A set of sanity checks were made in order to check false positives cases. Indeed, issues 4 and 5 are false positives. Maybe issue 3 too.

Issue 3: invalid too. The `hash.c` case: `__ptr = 0` is not a valid case since it would imply that `ctx == NULL` (at line 36 in `hash.c`: `container_of(ctx, ...` in function `to_hash_ctx()`) which is excluded due to the `assert(ctx && ...);` at line 34.
The `aes-gcm.c` case is identical.

> 
> If you consider, I suggest checking issues 1 and 2. I can give more reports if you need them.

Issue 1: `out = 0` cannot happen since it is set from the penultimate parameter of `tee_cryp_pbkdf2()`, which is called only from `core/tee/tee_svc_cryp.c:3703` as `tee_crypt_pbkdf2(..., (uint8_t *)(sk + 1), derived_key_len);`.

Issue 2: I very much doubt it is possible to have these crazy length values because they must have been checked sooner.
