### ISSUE TITLE
Question about storing and restoring VFP context of non-secure world

### ISSUE THREAD

**Issue by bqiu728** [OP-TEE/optee_os#6146]
Hi
I'm confused about the VFP context storing and restoring of non-secure world:
It seems that: 
1. VFP context  storing and restoring is realized in the function of `thread_user_enable_vfp` and `thread_lazy_restore_ns_vfp` in OP-TEE OS
2. It is also realized in the function `fpregs_context_save` and `fpregs_context_restore` in trusted firmware
And my question is :
If there is no HW float instruction used in trusted firmware. Does the codes about VFP in trusted firmware can be deleted ? It seems that the codes in OP-TEE OS is enough

Thanks

**Comment by jenswi-linaro** [comment]
TF-A is used for many use cases so removing the code might be a bit much. Depending on your use case it might be motivated to make it configurable. However, that's more of a TF-A problem than an OP-TEE problem.

**Comment by odeprez** [comment]
Hi,
TF-A has the optional CTX_INCLUDE_FP_REGS build option which can be used for a TEE OS that does not support NEON NS context save/restore.
OP-TEE does this operation in the TEE core so the TF-A option is unnecessary in context of OP-TEE.
