### ISSUE TITLE
bringup with generic boot

### ISSUE THREAD

**Issue by neil1899** [OP-TEE/optee_os#615]
hi，all

when i enable generic boot, i found my board could't run.

the log is:
INF TEE-CORE:init_primary_helper:208: init_runtime Start
INF TEE-CORE:init_runtime:127: malloc_init Start
ERR TEE-CORE:_assert_log:38: Assertion 'start < end' failed at lib/libutils/isoc/bget_malloc.c:785

kern.ld.S is 
		__heap1_start = .;
		. += HEAP_SIZE;
		. = ALIGN(16 * 1024);
		__heap1_end = .;

and in the function of init_runtime:
malloc_init(__heap1_start, __heap1_end - __heap1_start); failed.

in the file of tee.dmp
0536f6d0 g       .heap1	00000000 __heap1_start
05378000 g      .heap1	00000000 __heap1_end

how can i change it?
thanks in advance!

**Comment by jenswi-linaro** [comment]
`malloc_init()` doesn't exist any more, please try something more recent.

**Comment by neil1899** [comment]
hi，jenswi
I have update my code
	thread_init_boot_thread();
	malloc_add_pool((void *)__heap1_start, __heap1_end - __heap1_start);

but the Log is same
 ERR TEE-CORE:_assert_log:38: Assertion 'start < end' failed at lib/libutils/isoc/bget_malloc.c:785

**Comment by neil1899** [comment]
hi,jenswi:
about link.mk
I found the problem is:
$(link-out-dir)/tee.bin: $(link-out-dir)/tee-pager.bin \
			 $(link-out-dir)/tee-pageable.bin \
			 $(link-out-dir)/tee-init_size.txt \
			 $(link-out-dir)/tee-init_load_addr.txt \
			 $(link-out-dir)/tee-init_mem_usage.txt \
			./scripts/gen_hashed_bin.py
	@$(cmd-echo-silent) '  GEN     $@'
	$(q)./scripts/gen_hashed_bin.py \
		--arch $(if $(filter y,$(CFG_ARM64_core)),arm64,arm32) \
		--init_size `cat $(link-out-dir)/tee-init_size.txt` \
		--init_load_addr_lo \
			`cat $(link-out-dir)/tee-init_load_addr.txt` \
		--init_mem_usage `cat $(link-out-dir)/tee-init_mem_usage.txt` \
		--tee_pager_bin $(link-out-dir)/tee-pager.bin \
		--tee_pageable_bin $(link-out-dir)/tee-pageable.bin \
		--out $@

if i use this way to generate tee.bin, it can run.
$(link-out-dir)/tee.bin: $(link-out-dir)/tee.elf
	@$(cmd-echo-silent) '  OBJCOPY $@'
	$(q)$(OBJCOPYcore) -O binary $< $@

**Comment by jenswi-linaro** [comment]
About the assert above, since `end` is assigned as `uintptr_t end = start + len;` I guess the variable is wrapping.

**Comment by neil1899** [comment]
but if i don't use generic boot, it's ok. the platform is sunxi

		unsigned long a, s;
		/* core malloc pool init */
		a = (unsigned long)&__heap1_start;
		s = (unsigned long)&__heap1_end;
		a = ((a + 1) & ~0x0FFFF) + 0x10000; /* 64kB aligned */
		s = s & ~0x0FFFF;	/* 64kB aligned */
		s = s - a;
		malloc_init((void *)a, s);

it's ok

**Comment by jenswi-linaro** [comment]
Sorry, I don't have any idea. Checking the values of `__heap1_start` and `__heap1_end` could give some clue to what's going on.

**Comment by neil1899** [comment]
ok, i'll try, how about link.mk

in bl31, it can't enter bl32 use gen_hash*.py to build tee.bin. it holds on the func of opteed_enter_sp

**Comment by jenswi-linaro** [comment]
To load the tee.bin generated with gen_hashed_bin.py you need the (prof of concept) patches corresponding to what's at https://github.com/linaro-swg/arm-trusted-firmware/tree/optee_paged_armtf_v1.2

There's work ongoing to upstream something to the official repository to avoid these patches, but until that's done this is what we have.

**Comment by neil1899** [comment]
hi，jenswi 
thanks so much！

about head_start/end:
I found the right value is (not config generic boot)
start:0x5390000
len:0x130000

error value is (config generic boot)
start:0x536F938
len:0x1406c8

**Comment by neil1899** [comment]
hi,jenswi:
if i use the branch of https://github.com/linaro-swg/arm-trusted-firmware/tree/optee_paged_armtf_v1.2

i need to config WITH_PAGER in bl32?

**Comment by jenswi-linaro** [comment]
You don't need WITH_PAGER to work with that, the header in tee.bin tells all ARM-TF needs to know to load the binary correctly.

**Comment by neil1899** [comment]
how about __head_start/end:
I found the right value is (not config generic boot)
start:0x5390000
len:0x130000

error value is (config generic boot)
start:0x536F938
len:0x1406c8

it's the problem of kern.ld.S?
thanks in advance!

**Comment by neil1899** [comment]
thanks so much! i have bringup with generic boot

**Comment by neil1899** [comment]
sorry, jenswi：
i have another, how can i enable arm64_core, now in my conf.h always arm32_core enable.
how can i change it?

**Comment by neil1899** [comment]
hi,jenswi

on my platform, i have define CFG_ARM64_core = y in my conf.mk,
but the generate file conf.h, it also shows #define CFG_ARM32_core 1 /* 'y' */

**Comment by jenswi-linaro** [comment]
It looks like CFG_ARM32_core also is set, both can't be set at the same time.

**Comment by neil1899** [comment]
hi jenswi
i only set 64core，but in the module of sm,the sub.mk shows that

srcs-y += sm_a32.S
srcs-y += sm.c

only a32.S

**Comment by jforissier** [comment]
Indeed, secure monitor code in `core/arch/arm/sm` is available only for 32 bits. If your platform supports 64-bits, you're supposed to use ARM Trusted Firmware instead (or write you own secure monitor code). See for instance `core/arch/arm/plat-hikey/conf.mk`: HiKey supports both 32- and 64-bit secure OS, in both cases it uses ARM Trusted Firmware as the secure monitor and SMC dispatcher.

**Comment by neil1899** [comment]
hi jforissier
i am using arm trusted firmware (opteed)as the secure monitor.
so, i don't build sm module right?but optee os build sm module as default right?

**Comment by jforissier** [comment]
Check your `conf.mk`. I bet you're adding `$(arch-dir)/sm` to `core-platform-subdir`.

**Comment by neil1899** [comment]
hi all
thanks so much!
