### ISSUE TITLE
assertion '!tadb_db' failed at core/tee/tadb.c:247 <tee_tadb_open>

### ISSUE THREAD

**Issue by hearyouagain** [OP-TEE/optee_os#6152]
when i use benchmark in first time，the tadb is NULL，but when i use benchmark in second time， the tabdb is not NULL which lead to the panic occurd.

The code is :
static TEE_Result tee_tadb_open(struct tee_tadb_dir **db)
{
>---TEE_Result res = TEE_SUCCESS;

>---mutex_lock(&tadb_mutex);
>---**EMSG("---------------sample_test---%#x----------------\n", tadb_db);**
>---if (!tadb_db_refc) {
>--->---assert(!tadb_db);
>--->---res = tadb_open(&tadb_db);
>--->---if (res)
>--->--->---goto err;
>---}
>---tadb_db_refc++;
>---*db = tadb_db;
err:
>---mutex_unlock(&tadb_mutex);
>---return res;
}

static void tadb_put(struct tee_tadb_dir *db)
{
>---assert(db == tadb_db);
>---mutex_lock(&tadb_mutex);
>---assert(tadb_db_refc);
>---tadb_db_refc--;
>---EMSG("---------------sample_test-------------------\n");
>---if (!tadb_db_refc) {
>--->---db->ops->close(&db->fh);
>--->---free(db->files);
>--->---free(db);
>--->---tadb_db = NULL;
>--->--**-EMSG("---------------sample_test---%#x----------------\n", tadb_db);**
>---}
>---mutex_unlock(&tadb_mutex);
}

the appearence is :
first time :
/mnt/optee_asic/optee_benchmark # ./benchmark /mnt/optee_asic/osal_test/out/ca/o
ptee_example_secure_storage
1. Opening Benchmark Static TA...
2. Allocating per-core buffers, cores detected = 2
E/TC:1 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:1 00 bm_timestamp:203 ------------------sample_test 2---- 1
3. Starting origin host app /mnt/optee_asic/osal_test/out/ca/optee_example_secure_storage ...
Dumping timestamps to /mnt/optee_asic/osal_test/out/ca/optee_example_secure_storage.ts ...
===================================================================================================================
Prepare session with the TA
**E/TC:? 00 tee_tadb_open:245 ---------------sample_test---0----------------

E/TC:? 00 tadb_put:265 ---------------sample_test-------------------
E/TC:? 00 tadb_put:271 ---------------sample_test---0----------------**

Test on object "object#1"
- Create and load object in the TA secure storage
E/TC:1 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:1 00 bm_timestamp:203 ------------------sample_test 2---- 1
random: crng init done
random: 1 urandom warning(s) missed due to ratelimiting
E/TC:1 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:1 00 bm_timestamp:203 ------------------sample_test 2---- 1
- Read back the object
E/TC:1 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:1 00 bm_timestamp:203 ------------------sample_test 2---- 1
E/TC:1 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:1 00 bm_timestamp:203 ------------------sample_test 2---- 1
- Delete the object
E/TC:1 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:1 00 bm_timestamp:203 ------------------sample_test 2---- 1
E/TC:1 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:1 00 bm_timestamp:203 ------------------sample_test 2---- 1

Test on object "object#2"
E/TC:1 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:1 00 bm_timestamp:203 ------------------sample_test 2---- 1
E/TA:   read_raw_object:189 Failed to open persistent object, res=0xffff0008
E/TC:1 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:1 00 bm_timestamp:203 ------------------sample_test 2---- 1
- Object not found in TA secure storage, create it.
E/TC:1 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:1 00 bm_timestamp:203 ------------------sample_test 2---- 1
E/TC:1 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:1 00 bm_timestamp:203 ------------------sample_test 2---- 1

We're done, close and release TEE resources
4. Done benchmark
E/TC:0 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:0 00 bm_timestamp:203 ------------------sample_test 2---- 0
E/TC:? 00 unregister_benchmark:155 ---------------------------goodgoodgood!!!!!

secode time:
/mnt/optee_asic/optee_benchmark # ./benchmark /mnt/optee_asic/osal_test/out/ca/o
ptee_example_secure_storage
1. Opening Benchmark Static TA...
2. Allocating per-core buffers, cores detected = 2
E/TC:0 00 bm_timestamp:200 ------------------sample_test ---- 0
E/TC:0 00 bm_timestamp:203 ------------------sample_test 2---- 0
3. Starting origin host app /mnt/optee_asic/osal_test/out/ca/optee_example_secure_storage ...
Dumping timestamps to /mnt/optee_asic/osal_test/out/ca/optee_example_secure_storage.ts ...
==================================================================================================E/TC:? 00 tee_tadb_open:245 ---------------**sample_test---0x30000000----------------**
=================
Prepare session with the TA
E/TC:? 00 assertion '!tadb_db' failed at core/tee/tadb.c:247 <tee_tadb_open>
E/TC:0 00 Panic at core/kernel/assert.c:28 <_assert_break>
E/TC:0 00 TEE load address @ 0x40030000

So, why this happened, and is there some method to fix it

**Comment by jenswi-linaro** [comment]
The assert is obviously not expected, but I don't see how it can happen in the current code. Perhaps there's some memory corruption? A few debug prints on the `tadb_db` value might help to figure out what's going on.

**Comment by hearyouagain** [comment]
indeed, and the problem haven't been happened again, the version of optee is 3.20.0, but i adjusted some benchmark code to use the tools, the deadlock will occur sometimes.

**Comment by hearyouagain** [comment]
the code of pta:
// SPDX-License-Identifier: BSD-2-Clause
/*
 * Copyright (c) 2017, Linaro Limited
 */
#include <bench.h>
#include <compiler.h>
#include <kernel/misc.h>
#include <kernel/mutex.h>
#include <kernel/pseudo_ta.h>
#include <malloc.h>
#include <mm/core_memprot.h>
#include <mm/mobj.h>
#include <mm/tee_mm.h>
#include <mm/tee_pager.h>
#include <mm/vm.h>
#include <optee_rpc_cmd.h>
#include <pta_benchmark.h>
#include <stdio.h>
#include <string.h>
#include <string_ext.h>
#include <trace.h>

#define TA_NAME "benchmark.ta"
#define TA_PRINT_PREFIX "Benchmark: "

static struct tee_ts_global *bench_ts_global;
static struct tee_ts_global bench_ts = {0};
static size_t bench_ts_size;

static struct mutex bench_reg_mu = MUTEX_INITIALIZER;
static struct mobj *bench_mobj;

static TEE_Result rpc_reg_global_buf(uint64_t type, paddr_t phta, size_t size)
{
    struct thread_param tpm = THREAD_PARAM_VALUE(IN, type, phta, size);

    return thread_rpc_cmd(OPTEE_RPC_CMD_BENCH_REG, 1, &tpm);
}

static TEE_Result alloc_benchmark_buffer(uint32_t type,
                                         TEE_Param p[TEE_NUM_PARAMS])
{
    TEE_Result res;

    if ((TEE_PARAM_TYPE_GET(type, 0) != TEE_PARAM_TYPE_MEMREF_INOUT) ||
        (TEE_PARAM_TYPE_GET(type, 1) != TEE_PARAM_TYPE_NONE) ||
        (TEE_PARAM_TYPE_GET(type, 2) != TEE_PARAM_TYPE_NONE) ||
        (TEE_PARAM_TYPE_GET(type, 3) != TEE_PARAM_TYPE_NONE)) {
        return TEE_ERROR_BAD_PARAMETERS;
    }

    /*
     * We accept only non-secure buffers, as we later perform
     * registration of this buffer in NS layers
     * (optee linux kmod/optee client)
     */
    if (!tee_vbuf_is_non_sec(p[0].memref.buffer, p[0].memref.size))
        return TEE_ERROR_BAD_PARAMETERS;

    mutex_lock(&bench_reg_mu);

    /* Check if we have already registered buffer */
    if (bench_ts_global) {
        EMSG(TA_PRINT_PREFIX "timestamp buffer was already registered");
        mutex_unlock(&bench_reg_mu);
        return TEE_ERROR_BAD_STATE;
    }

    DMSG("Registering timestamp buffer, addr = %p, paddr = %" PRIxPA "\n",
         p[0].memref.buffer,
         virt_to_phys(p[0].memref.buffer));
    bench_ts_global = p[0].memref.buffer;
    bench_ts_size = p[0].memref.size;

    memcpy(&bench_ts, bench_ts_global, sizeof(struct tee_ts_global));

    mutex_unlock(&bench_reg_mu);

    /* Send back to the optee linux kernel module */
    res = rpc_reg_global_buf(OPTEE_MSG_RPC_CMD_BENCH_REG_NEW,
                             virt_to_phys((void *)bench_ts_global),
                             bench_ts_size);

    return res;
}

static TEE_Result get_benchmark_memref(uint32_t type,
                                       TEE_Param p[TEE_NUM_PARAMS])
{
    if ((TEE_PARAM_TYPE_GET(type, 0) != TEE_PARAM_TYPE_VALUE_OUTPUT) ||
        (TEE_PARAM_TYPE_GET(type, 1) != TEE_PARAM_TYPE_NONE) ||
        (TEE_PARAM_TYPE_GET(type, 2) != TEE_PARAM_TYPE_NONE) ||
        (TEE_PARAM_TYPE_GET(type, 3) != TEE_PARAM_TYPE_NONE)) {
        return TEE_ERROR_BAD_PARAMETERS;
    }

    mutex_lock(&bench_reg_mu);

    DMSG(TA_PRINT_PREFIX "Sending back timestamp buffer paddr = %p",
         (void *)virt_to_phys((void *)bench_ts_global));

    if (bench_ts_global) {
        p[0].value.a = virt_to_phys((void *)bench_ts_global);
        p[0].value.b = bench_ts_size;
    } else {
        p[0].value.a = 0;
        p[0].value.b = 0;
    }

    mutex_unlock(&bench_reg_mu);

    return TEE_SUCCESS;
}

static TEE_Result unregister_benchmark(uint32_t type,
                                       TEE_Param p[TEE_NUM_PARAMS] __unused)
{
    TEE_Result res;

    if ((TEE_PARAM_TYPE_GET(type, 0) != TEE_PARAM_TYPE_MEMREF_INOUT) ||
        (TEE_PARAM_TYPE_GET(type, 1) != TEE_PARAM_TYPE_NONE) ||
        (TEE_PARAM_TYPE_GET(type, 2) != TEE_PARAM_TYPE_NONE) ||
        (TEE_PARAM_TYPE_GET(type, 3) != TEE_PARAM_TYPE_NONE)) {
        return TEE_ERROR_BAD_PARAMETERS;
    }
    // if ((TEE_PARAM_TYPE_GET(type, 0) != TEE_PARAM_TYPE_NONE) ||
    //     (TEE_PARAM_TYPE_GET(type, 1) != TEE_PARAM_TYPE_NONE) ||
    //     (TEE_PARAM_TYPE_GET(type, 2) != TEE_PARAM_TYPE_NONE) ||
    //     (TEE_PARAM_TYPE_GET(type, 3) != TEE_PARAM_TYPE_NONE)) {
    //     return TEE_ERROR_BAD_PARAMETERS;
    // }

    if (!tee_vbuf_is_non_sec(p[0].memref.buffer, p[0].memref.size))
        return TEE_ERROR_BAD_PARAMETERS;


    mutex_lock(&bench_reg_mu);
    DMSG("Registering timestamp buffer, addr = %p, paddr = %" PRIxPA "\n",
         p[0].memref.buffer,
         virt_to_phys(p[0].memref.buffer));
    bench_ts_global = p[0].memref.buffer;

    memcpy(bench_ts_global, &bench_ts, sizeof(struct tee_ts_global));
    memset(&bench_ts, 0, sizeof(struct tee_ts_global));

    DMSG(TA_PRINT_PREFIX "Unregister benchmark ts buffer paddr = %p",
         (void *)virt_to_phys((void *)bench_ts_global));
    bench_ts_global = NULL;
    mutex_unlock(&bench_reg_mu);

    DMSG(TA_PRINT_PREFIX "Unregister benchmark ts buffer paddr = %#x",
         bench_ts_global);

    res = rpc_reg_global_buf(OPTEE_MSG_RPC_CMD_BENCH_REG_DEL, 0, 0);

    return res;
}

static TEE_Result invoke_command(void *session_ctx __unused, uint32_t cmd_id,
                                 uint32_t param_types,
                                 TEE_Param params[TEE_NUM_PARAMS])
{
    switch (cmd_id) {
        case BENCHMARK_CMD_ALLOCATE_BUF:
            return alloc_benchmark_buffer(param_types, params);
        case BENCHMARK_CMD_GET_MEMREF:
            return get_benchmark_memref(param_types, params);
        case BENCHMARK_CMD_UNREGISTER:
            return unregister_benchmark(param_types, params);
        default:
            break;
    }

    return TEE_ERROR_BAD_PARAMETERS;
}

pseudo_ta_register(.uuid = BENCHMARK_UUID, .name = TA_NAME,
                   .flags = PTA_DEFAULT_FLAGS,
                   .invoke_command_entry_point = invoke_command);

void bm_timestamp(void)
{
    struct tee_ts_cpu_buf *cpu_buf;
    struct tee_time_st ts_data;
    uint64_t ts_i;
    void *ret_addr;
    uint32_t cur_cpu;
    uint32_t exceptions;

    if (!bench_ts_global)
        return;

    exceptions = thread_mask_exceptions(THREAD_EXCP_ALL);
    cur_cpu = get_core_pos();

    // if (cur_cpu >= bench_ts_global->cores) {
    if (cur_cpu >= bench_ts.cores) {
        thread_unmask_exceptions(exceptions);
        return;
    }

    ret_addr = __builtin_return_address(0);

    cpu_buf = &bench_ts.cpu_buf[cur_cpu];
    // cpu_buf = &bench_ts_global->cpu_buf[cur_cpu];
    ts_i = cpu_buf->head++;
    ts_data.cnt = read_pmccntr() * TEE_BENCH_DIVIDER;
    ts_data.addr = (uintptr_t)ret_addr;
    ts_data.src = TEE_BENCH_CORE;
    cpu_buf->stamps[ts_i & TEE_BENCH_MAX_MASK] = ts_data;

    thread_unmask_exceptions(exceptions);
}

the code have been adjusted in client application:
static void register_bench_buf(uint32_t cores)
{
>---TEEC_Result res;
>---TEEC_Operation op = { 0 };
>---uint32_t ret_orig;

>---ts_buf_shm.size = sizeof(struct tee_ts_global) +
>--->--->---sizeof(struct tee_ts_cpu_buf) * cores;

>---/* allocate global timestamp buffer */
>---res = TEEC_AllocateSharedMemory(&ctx, &ts_buf_shm);
>---tee_check_res(res, "TEEC_AllocateSharedMemory");

>---init_ts_global(ts_buf_shm.buffer, cores);

>---op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_PARTIAL_INOUT,
>--->--->---TEEC_NONE, TEEC_NONE, TEEC_NONE);
>---//op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_WHOLE,
>---//>->---TEEC_NONE, TEEC_NONE, TEEC_NONE);
>---op.params[0].memref.parent = &ts_buf_shm;
>---op.params[0].memref.size = ts_buf_shm.size;

>---TEEC_InvokeCommand(&sess, BENCHMARK_CMD_REGISTER_MEMREF,
>--->--->--->--->---&op, &ret_orig);
>---tee_check_res(res, "TEEC_InvokeCommand");
}

static void unregister_bench(void)
{
>---TEEC_Result res;
>---TEEC_Operation op = { 0 };
>---uint32_t ret_orig;

>---//op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_WHOLE,
>---//>->---TEEC_NONE, TEEC_NONE, TEEC_NONE);
>---op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_PARTIAL_INOUT,
>--->--->---TEEC_NONE, TEEC_NONE, TEEC_NONE);
>---op.params[0].memref.parent = &ts_buf_shm;
>---op.params[0].memref.size = ts_buf_shm.size;
>---//op.paramTypes = TEEC_PARAM_TYPES(TEEC_NONE,
>---//>->--->--->---TEEC_NONE, TEEC_NONE, TEEC_NONE);

>---res = TEEC_InvokeCommand(&sess, BENCHMARK_CMD_UNREGISTER,
>--->--->--->--->---&op, &ret_orig);
>---tee_check_res(res, "TEEC_InvokeCommand");
}

occation:
[Benchmark] INFO: 1. Opening Benchmark Static TA...
[Benchmark] INFO: 2. Allocating per-core buffers, cores detected = 2
[Benchmark] INFO: 3. Starting origin host app /mnt/optee_asic/mmz_test/out/ca/optee_example_mmz ...
[Benchmark] INFO: Dumping timestamps to /mnt/optee_asic/mmz_test/out/ca/optee_example_mmz.ts ...
===================================================================================================================
Mythread1
/mnt/optee_asic/optee_benchmark # ./benchmark /mnt/optee_asic/osal_test/out/ca/o
ptee_example_secure_storageERR [1305] TEES:main:893: failed to find an OP-TEE supplicant device

1. Opening Benchmark Static TA...
2. Allocating per-core buffers, cores detected = 2
3. Starting origin host app /mnt/optee_asic/osal_test/out/ca/optee_example_secure_storage ...
Dumping timestamps to /mnt/optee_asic/osal_test/out/ca/optee_example_secure_storage.ts ...
===========================================================
E/TC:0 00 __mutex_lock:47 possible spinlock deadlock reminder 0

so, i don't know why the deadlock occured occasionally but not necessarily. And the other question is how can i use bench_ts_global in  **bm_timestamp**?

**Comment by hearyouagain** [comment]
the code of pta:
```
static struct tee_ts_global *bench_ts_global;
static struct tee_ts_global bench_ts = {0};
static size_t bench_ts_size;

static struct mutex bench_reg_mu = MUTEX_INITIALIZER;
static struct mobj *bench_mobj;

static TEE_Result rpc_reg_global_buf(uint64_t type, paddr_t phta, size_t size)
{
struct thread_param tpm = THREAD_PARAM_VALUE(IN, type, phta, size);

return thread_rpc_cmd(OPTEE_RPC_CMD_BENCH_REG, 1, &tpm);
}

static TEE_Result alloc_benchmark_buffer(uint32_t type,
TEE_Param p[TEE_NUM_PARAMS])
{
TEE_Result res;

if ((TEE_PARAM_TYPE_GET(type, 0) != TEE_PARAM_TYPE_MEMREF_INOUT) ||
    (TEE_PARAM_TYPE_GET(type, 1) != TEE_PARAM_TYPE_NONE) ||
    (TEE_PARAM_TYPE_GET(type, 2) != TEE_PARAM_TYPE_NONE) ||
    (TEE_PARAM_TYPE_GET(type, 3) != TEE_PARAM_TYPE_NONE)) {
    return TEE_ERROR_BAD_PARAMETERS;
}

/*
 * We accept only non-secure buffers, as we later perform
 * registration of this buffer in NS layers
 * (optee linux kmod/optee client)
 */
if (!tee_vbuf_is_non_sec(p[0].memref.buffer, p[0].memref.size))
    return TEE_ERROR_BAD_PARAMETERS;

mutex_lock(&bench_reg_mu);

/* Check if we have already registered buffer */
if (bench_ts_global) {
    EMSG(TA_PRINT_PREFIX "timestamp buffer was already registered");
    mutex_unlock(&bench_reg_mu);
    return TEE_ERROR_BAD_STATE;
}

DMSG("Registering timestamp buffer, addr = %p, paddr = %" PRIxPA "\n",
     p[0].memref.buffer,
     virt_to_phys(p[0].memref.buffer));
bench_ts_global = p[0].memref.buffer;
bench_ts_size = p[0].memref.size;

memcpy(&bench_ts, bench_ts_global, sizeof(struct tee_ts_global));

mutex_unlock(&bench_reg_mu);

/* Send back to the optee linux kernel module */
res = rpc_reg_global_buf(OPTEE_MSG_RPC_CMD_BENCH_REG_NEW,
                         virt_to_phys((void *)bench_ts_global),
                         bench_ts_size);

return res;
}

static TEE_Result get_benchmark_memref(uint32_t type,
TEE_Param p[TEE_NUM_PARAMS])
{
if ((TEE_PARAM_TYPE_GET(type, 0) != TEE_PARAM_TYPE_VALUE_OUTPUT) ||
(TEE_PARAM_TYPE_GET(type, 1) != TEE_PARAM_TYPE_NONE) ||
(TEE_PARAM_TYPE_GET(type, 2) != TEE_PARAM_TYPE_NONE) ||
(TEE_PARAM_TYPE_GET(type, 3) != TEE_PARAM_TYPE_NONE)) {
return TEE_ERROR_BAD_PARAMETERS;
}

mutex_lock(&bench_reg_mu);

DMSG(TA_PRINT_PREFIX "Sending back timestamp buffer paddr = %p",
     (void *)virt_to_phys((void *)bench_ts_global));

if (bench_ts_global) {
    p[0].value.a = virt_to_phys((void *)bench_ts_global);
    p[0].value.b = bench_ts_size;
} else {
    p[0].value.a = 0;
    p[0].value.b = 0;
}

mutex_unlock(&bench_reg_mu);

return TEE_SUCCESS;
}

static TEE_Result unregister_benchmark(uint32_t type,
TEE_Param p[TEE_NUM_PARAMS] __unused)
{
TEE_Result res;

if ((TEE_PARAM_TYPE_GET(type, 0) != TEE_PARAM_TYPE_MEMREF_INOUT) ||
    (TEE_PARAM_TYPE_GET(type, 1) != TEE_PARAM_TYPE_NONE) ||
    (TEE_PARAM_TYPE_GET(type, 2) != TEE_PARAM_TYPE_NONE) ||
    (TEE_PARAM_TYPE_GET(type, 3) != TEE_PARAM_TYPE_NONE)) {
    return TEE_ERROR_BAD_PARAMETERS;
}
// if ((TEE_PARAM_TYPE_GET(type, 0) != TEE_PARAM_TYPE_NONE) ||
//     (TEE_PARAM_TYPE_GET(type, 1) != TEE_PARAM_TYPE_NONE) ||
//     (TEE_PARAM_TYPE_GET(type, 2) != TEE_PARAM_TYPE_NONE) ||
//     (TEE_PARAM_TYPE_GET(type, 3) != TEE_PARAM_TYPE_NONE)) {
//     return TEE_ERROR_BAD_PARAMETERS;
// }

if (!tee_vbuf_is_non_sec(p[0].memref.buffer, p[0].memref.size))
    return TEE_ERROR_BAD_PARAMETERS;


mutex_lock(&bench_reg_mu);
DMSG("Registering timestamp buffer, addr = %p, paddr = %" PRIxPA "\n",
     p[0].memref.buffer,
     virt_to_phys(p[0].memref.buffer));
bench_ts_global = p[0].memref.buffer;

memcpy(bench_ts_global, &bench_ts, sizeof(struct tee_ts_global));
memset(&bench_ts, 0, sizeof(struct tee_ts_global));

DMSG(TA_PRINT_PREFIX "Unregister benchmark ts buffer paddr = %p",
     (void *)virt_to_phys((void *)bench_ts_global));
bench_ts_global = NULL;
mutex_unlock(&bench_reg_mu);

DMSG(TA_PRINT_PREFIX "Unregister benchmark ts buffer paddr = %#x",
     bench_ts_global);

res = rpc_reg_global_buf(OPTEE_MSG_RPC_CMD_BENCH_REG_DEL, 0, 0);

return res;
}

static TEE_Result invoke_command(void *session_ctx __unused, uint32_t cmd_id,
uint32_t param_types,
TEE_Param params[TEE_NUM_PARAMS])
{
switch (cmd_id) {
case BENCHMARK_CMD_ALLOCATE_BUF:
return alloc_benchmark_buffer(param_types, params);
case BENCHMARK_CMD_GET_MEMREF:
return get_benchmark_memref(param_types, params);
case BENCHMARK_CMD_UNREGISTER:
return unregister_benchmark(param_types, params);
default:
break;
}

return TEE_ERROR_BAD_PARAMETERS;
}

pseudo_ta_register(.uuid = BENCHMARK_UUID, .name = TA_NAME,
.flags = PTA_DEFAULT_FLAGS,
.invoke_command_entry_point = invoke_command);

void bm_timestamp(void)
{
struct tee_ts_cpu_buf *cpu_buf;
struct tee_time_st ts_data;
uint64_t ts_i;
void *ret_addr;
uint32_t cur_cpu;
uint32_t exceptions;

if (!bench_ts_global)
    return;

exceptions = thread_mask_exceptions(THREAD_EXCP_ALL);
cur_cpu = get_core_pos();

// if (cur_cpu >= bench_ts_global->cores) {
if (cur_cpu >= bench_ts.cores) {
    thread_unmask_exceptions(exceptions);
    return;
}

ret_addr = __builtin_return_address(0);

cpu_buf = &bench_ts.cpu_buf[cur_cpu];
// cpu_buf = &bench_ts_global->cpu_buf[cur_cpu];
ts_i = cpu_buf->head++;
ts_data.cnt = read_pmccntr() * TEE_BENCH_DIVIDER;
ts_data.addr = (uintptr_t)ret_addr;
ts_data.src = TEE_BENCH_CORE;
cpu_buf->stamps[ts_i & TEE_BENCH_MAX_MASK] = ts_data;

thread_unmask_exceptions(exceptions);
}
```

the code have been adjusted in client application:
```
static void register_bench_buf(uint32_t cores)
{

---TEEC_Result res;
---TEEC_Operation op = { 0 };
---uint32_t ret_orig;

---ts_buf_shm.size = sizeof(struct tee_ts_global) +
--->--->---sizeof(struct tee_ts_cpu_buf) * cores;

---/* allocate global timestamp buffer */
---res = TEEC_AllocateSharedMemory(&ctx, &ts_buf_shm);
---tee_check_res(res, "TEEC_AllocateSharedMemory");

---init_ts_global(ts_buf_shm.buffer, cores);

---op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_PARTIAL_INOUT,
--->--->---TEEC_NONE, TEEC_NONE, TEEC_NONE);
---//op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_WHOLE,
---//>->---TEEC_NONE, TEEC_NONE, TEEC_NONE);
---op.params[0].memref.parent = &ts_buf_shm;
---op.params[0].memref.size = ts_buf_shm.size;

---TEEC_InvokeCommand(&sess, BENCHMARK_CMD_REGISTER_MEMREF,
--->--->--->--->---&op, &ret_orig);
---tee_check_res(res, "TEEC_InvokeCommand");
}

static void unregister_bench(void)
{

---TEEC_Result res;
---TEEC_Operation op = { 0 };
---uint32_t ret_orig;

---//op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_WHOLE,
---//>->---TEEC_NONE, TEEC_NONE, TEEC_NONE);
---op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_PARTIAL_INOUT,
--->--->---TEEC_NONE, TEEC_NONE, TEEC_NONE);
---op.params[0].memref.parent = &ts_buf_shm;
---op.params[0].memref.size = ts_buf_shm.size;
---//op.paramTypes = TEEC_PARAM_TYPES(TEEC_NONE,
---//>->--->--->---TEEC_NONE, TEEC_NONE, TEEC_NONE);

---res = TEEC_InvokeCommand(&sess, BENCHMARK_CMD_UNREGISTER,
--->--->--->--->---&op, &ret_orig);
---tee_check_res(res, "TEEC_InvokeCommand");
}

```
occation:
```
[Benchmark] INFO: 1. Opening Benchmark Static TA...
[Benchmark] INFO: 2. Allocating per-core buffers, cores detected = 2
[Benchmark] INFO: 3. Starting origin host app /mnt/optee_asic/mmz_test/out/ca/optee_example_mmz ...
[Benchmark] INFO: Dumping timestamps to /mnt/optee_asic/mmz_test/out/ca/optee_example_mmz.ts ...
Mythread1
/mnt/optee_asic/optee_benchmark # ./benchmark /mnt/optee_asic/osal_test/out/ca/o
ptee_example_secure_storageERR [1305] TEES:main:893: failed to find an OP-TEE supplicant device

Opening Benchmark Static TA...
Allocating per-core buffers, cores detected = 2
Starting origin host app /mnt/optee_asic/osal_test/out/ca/optee_example_secure_storage ...
Dumping timestamps to /mnt/optee_asic/osal_test/out/ca/optee_example_secure_storage.ts ...
===========================================================
E/TC:0 00 __mutex_lock:47 possible spinlock deadlock reminder 0
```
so, i don't know why the deadlock occured occasionally but not necessarily. And the other question is how can i use bench_ts_global in bm_timestamp?

**Comment by hearyouagain** [comment]
the reason why i adjusted the code is the **thread_rpc_alloc_payload** do not work even i patched the linux, but using the memref which will be not available after invokement,  the version of linux is 5.10, and i have patched it with [ OP-TEE Benchmark **not for mainline** Add Benchmark support](https://github.com/linaro-swg/linux/commit/527d88b5e5c88f1be35a38554a71f949d7f5d266)
