### ISSUE TITLE
Read linux files from OPTEE 

### ISSUE THREAD

**Issue by PrithviAPai** [OP-TEE/optee_os#6156]
Hi Team,

I am trying to read linux files from OPTEE and I am NOT able to read any files. Is there any provision to read files from OPTEE ? 

Thanks,
Prithvi A Pai

**Comment by jforissier** [comment]
Hi @PrithviAPai, no there isn't.

**Comment by etienne-lms** [comment]
For info, you can implement a tee-supplicant pluggin for such purpose. See https://optee.readthedocs.io/en/latest/architecture/globalplatform_api.html#loadable-plugins-framework

**Comment by PrithviAPai** [comment]
@etienne-lms  can you share any example code ? Where this is implemented

**Comment by etienne-lms** [comment]
OP-TEE examples provides an example of the client application that loads a tee-supplicant pluggin (syslog pluggin) and and invokes a TA that calls the pluggin.
https://github.com/linaro-swg/optee_examples/tree/master/plugins
