### ISSUE TITLE
Hafnium failed to load optee

### ISSUE THREAD

**Issue by linmu-t** [OP-TEE/optee_os#6158]
hello：
When I used the following environment to build an optee based on Hafnium, the following error occurred:

environment：  **repo init -u https://github.com/jenswi-linaro/manifest.git -m qemu_v8.xml -b qemu_sel2**
question：Unable to load optee

WARNING: Stage-2 page fault: pc=0xe310670, vmid=0x8001, vcpu=0, vaddr=0xd00000, ipaddr=0xd00000, mode=0x1 0x7c
NOTICE: Injecting Data Abort exception into VM 0x8001.

How should I configure it to start OPTEE normally？Thank！

------------------------------------------------------------------------------------------------------------
The complete log is as follows：

NOTICE:  Booting Trusted Firmware
NOTICE:  BL1: v2.8(debug):v2.8-151-gf4d8ed50d-dirty
NOTICE:  BL1: Built : 11:12:52, Jul  6 2023
INFO:    BL1: RAM 0xe0ee000 - 0xe0f7000
INFO:    BL1: Loading BL2
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=1 at address 0xe06b000
INFO:    Image id=1 loaded: 0xe06b000 - 0xe074b69
NOTICE:  BL1: Booting BL2
INFO:    Entry point address = 0xe06b000
INFO:    SPSR = 0x3c5
NOTICE:  BL2: v2.8(debug):v2.8-151-gf4d8ed50d-dirty
NOTICE:  BL2: Built : 11:12:53, Jul  6 2023
INFO:    BL2: Doing platform setup
INFO:    BL2: Loading image id 3
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=3 at address 0xe0a0000
INFO:    Image id=3 loaded: 0xe0a0000 - 0xe0ae0a4
INFO:    BL2: Loading image id 4
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=4 at address 0xe100000
INFO:    Image id=4 loaded: 0xe100000 - 0xe12b298
INFO:    BL2: Skip loading image id 21
INFO:    BL2: Skip loading image id 22
INFO:    BL2: Loading image id 26
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=26 at address 0xe002000
INFO:    Image id=26 loaded: 0xe002000 - 0xe002399
INFO:    BL2: Loading image id 24
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=24 at address 0xe001000
INFO:    Image id=24 loaded: 0xe001000 - 0xe0010e9
INFO:    BL2: Loading image id 40
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=40 at address 0xe300000
INFO:    Image id=40 loaded: 0xe300000 - 0xe3d3190
INFO:    BL2: Skip loading image id 41
INFO:    BL2: Skip loading image id 42
INFO:    BL2: Skip loading image id 43
INFO:    BL2: Skip loading image id 44
INFO:    BL2: Skip loading image id 45
INFO:    BL2: Skip loading image id 46
INFO:    BL2: Skip loading image id 47
INFO:    BL2: Loading image id 5
WARNING: Firmware Image Package header check failed.
INFO:    Loading image id=5 at address 0x60000000
INFO:    Image id=5 loaded: 0x60000000 - 0x60200000
NOTICE:  BL1: Booting BL31
INFO:    Entry point address = 0xe0a0000
INFO:    SPSR = 0x3cd
NOTICE:  BL31: v2.8(debug):v2.8-151-gf4d8ed50d-dirty
NOTICE:  BL31: Built : 11:12:53, Jul  6 2023
INFO:    GICv3 without legacy support detected.
INFO:    ARM GICv3 driver initialized in EL3
INFO:    Maximum SPI INTID supported: 287
INFO:    BL31: Initializing runtime services
INFO:    SPM Core setup done.
INFO:    BL31: Initializing BL32!!!
INFO: Initializing Hafnium (SPMC)
INFO: text: 0xe100000 - 0xe125000
INFO: rodata: 0xe125000 - 0xe12b000
INFO: data: 0xe12b000 - 0xe214000
INFO: stacks: 0xe214000 - 0xe224000
INFO: Supported bits in physical address: 48
INFO: Stage 2 has 4 page table levels with 1 pages at the root.
INFO: Stage 1 has 4 page table levels with 1 pages at the root.
INFO: Memory range:  0xe000000 - 0xeffffff
INFO: Loading VM id 0x8001: op-tee.
INFO: Loaded with 4 vCPUs, entry at 0xe300000.
INFO: Hafnium initialisation completed
WARNING: Stage-2 page fault: pc=0xe310670, vmid=0x8001, vcpu=0, vaddr=0xd00000, ipaddr=0xd00000, mode=0x1 0x7c
NOTICE: Injecting Data Abort exception into VM 0x8001.

**Comment by jenswi-linaro** [comment]
It seems that the prototype setup has become outdated. I've just created two pull requests to switch to upstream instead. Please try https://github.com/OP-TEE/manifest/pull/241 and https://github.com/OP-TEE/build/pull/663 instead.

**Comment by linmu-t** [comment]
Thank you very much. The problem has been resolved and the system can start normally

**Comment by jenswi-linaro** [comment]
I'm glad it worked.
