### ISSUE TITLE
Inquiries about TEE memory

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#6160]
I am studying memory in TEE, and I have a few questions.
I'm working on QEMU v8 environment. (CFG_WITH_PAGER=n)
1. CFG_TZDRAM_SIZE.
    Refer to the generic_ram_layout.h file for details.
    Checking TEE RAM layout without CFG_WITH_PAGER, there is TEE core secure RAM (TEE_RAM).
    Does this include both the code area and data area of optee-os?

2. If so, the Trusted Application RAM (TA_RAM) seems to be the area for TA's code and data.
    It is thought that several TAs share and use this area. I wonder how memory is managed when several TAs are running.
    For example, if TA A has allocated a large amount of heap memory, and TA B also requests a large amount of heap, how is it managed?
    I understand that general Linux systems are managed through PAGING and SWAP. In optee, is out of memory returned in the above situation or is there a separate management method?

3. The heap size of optee os is designated as "CFG_CORE_HEAP_SIZE" when building optee-os, and the heap size of TA is designated as property (TA_DATA_SIZE) when building TA.
Looking at TEE RAM layout without CFG_WITH_PAGER, it seems that there is no CFG_XXXX that distinguishes between TEE core secure RAM (TEE_RAM) and Trusted Application RAM (TA_RAM).
Is it used as contiguous memory as shown below?
```

----------------------------------------|----------------- -- <-- CFG_TZDRAM_START
TEE core secure RAM (TEE_RAM)           | optee-os code area
                                        | optee-os data area
----------------------------------------|----------------- --
Trusted Application RAM (TA_RAM)        | TAs code area
                                        | TAs data area
----------------------------------------|-------------------- <-- CFG_TZDRAM_START + CFG_TZDRAM_SIZE

```
If so, I think increasing the size of "CFG_CORE_HEAP_SIZE" will lower the maximum allowed value of TA_DATA_SIZE. Am I right?
And in the picture above, do other areas other than code and data exist?
 
4. Can the OPTEE paging system be used only in an environment where SRAM exists?
   I saw in the link below that it was written as a solution for SRAM 128 to 256 KiB environment.
   https://optee.readthedocs.io/en/latest/architecture/core.html#pager
  
Again, I'm studying on QEMU v8 right now, and I've confirmed that CFG_WITH_PAGER=n is set.

BR,

**Comment by TaihuLight** [comment]
How to check the available TEE memory size when SBC boot?
@etienne-lms @SangsubLim

**Comment by etienne-lms** [comment]
When core is built with `CFG_WITH_STATS=y`, you can use  `xtest --stats --alloc` to get core heap (TEE_RAM heap) and secure DDR (TA_RAM) pools info (value in bytes). See the dump below, from a recent qemu_virt run :
```
(...)
Welcome to Buildroot, type root or test to login
buildroot login: root
# xtest --stats --alloc
Pool:                Heap
Bytes allocated:                       17704
Max bytes allocated:                   17784
Size of pool:                          77880
Number of failed allocations:          0
Size of larges allocation failure:     0
Total bytes allocated at that failure: 0

Pool:                
Bytes allocated:                       0
Max bytes allocated:                   0
Size of pool:                          0
Number of failed allocations:          0
Size of larges allocation failure:     0
Total bytes allocated at that failure: 0

Pool:                Secure DDR
Bytes allocated:                       253952
Max bytes allocated:                   253952
Size of pool:                          13631488
Number of failed allocations:          0
Size of larges allocation failure:     0
Total bytes allocated at that failure: 0

Pool:                
Bytes allocated:                       0
Max bytes allocated:                   0
Size of pool:                          0
Number of failed allocations:          0
Size of larges allocation failure:     0
Total bytes allocated at that failure: 0

Pool:                
Bytes allocated:                       0
Max bytes allocated:                   0
Size of pool:                          0
Number of failed allocations:          0
Size of larges allocation failure:     0
Total bytes allocated at that failure: 0
#
