### ISSUE TITLE
TA data persistence with FVP and fTPM

### ISSUE THREAD

**Issue by akorb** [OP-TEE/optee_os#6162]
My goal is to boot an FVP with fTPM enabled and that the storage of the TPM persists across reboots. In the default configuration, the FVP data is volatile and lost on shutdown.

My idea would be to mount a local rw block file to `/data/tee/` within the FVP environment. This block file would persist across reboots and therefore, the TA data would be persistent.

Afaik, there are two FVP platforms, Base and Foundation. Both are supported by OP-TEE, which can be toggled by `FVP_USE_BASE_PLAT`.
While the Foundation platform boots properly, I can't find a way to inject a local block file into the FVP environment that I could mount within FVP. I suppose the right option would be `block-device`, but it's already occupied with `--block-device=optee/build/../out/boot-fat.uefi.img` and the flag is only allowed once.

OP-TEE supports to mount a block file within the FVP Base platform with `FVP_VIRTFS_ENABLE`. Unfortunately, the Base platform hangs during boot when the fTPM is enabled, i.e., built with `MEASURED_BOOT=y MEASURED_BOOT_FTPM=y FVP_USE_BASE_PLAT=y make -j $(nproc)`.

![image](https://github.com/OP-TEE/optee_os/assets/6689889/df5d6a68-63cf-417f-b42a-28b982f54545)

I tried a full OP-TEE rebuilt from `master`, but this results in the very same behavior.

So far, I see two options. Either find a way to get the Base platform working with the fTPM, or find a way to inject a local block file into the Foundation platform. But I'm not experienced with FVP. Also, maybe there is another way I don't know. For example, to change something within buildroot such that `boot-fat.uefi.img` is modified from the FVP and hence, keeps the system data.

Maybe someone with more expertise can point me into the right direction?

**Comment by jenswi-linaro** [comment]
I'd recommend to continue working on the `FVP_VIRTFS_ENABLE=y` track. Note that it's not OP-TEE mounting the p9-device, it's the kernel. Does virtfs work without `MEASURED_BOOT=y MEASURED_BOOT_FTPM=y` on FVP?

**Comment by akorb** [comment]
> I'd recommend to continue working on the `FVP_VIRTFS_ENABLE=y` track.

I also believe that would be the cleanest solution.

> Does virtfs work without `MEASURED_BOOT=y MEASURED_BOOT_FTPM=y` on FVP?

I just tried it, and virtfs works flawlessly. Only with fTPM enabled the booting process gets stuck.

**Comment by jenswi-linaro** [comment]
Perhaps something during early boot is trying to do something with the fTPM TA that requires RPC support, for instance, secure storage.

**Comment by akorb** [comment]
Wouldn't the same problem appear with the Foundation platform then?

**Comment by akorb** [comment]
Are there some debug flags which I can enable that we gain more insights by more verbose output?

**Comment by jenswi-linaro** [comment]
> Wouldn't the same problem appear with the Foundation platform then?

Good point. Yes, I suppose so.

**Comment by jenswi-linaro** [comment]
> Are there some debug flags which I can enable that we gain more insights by more verbose output?

Try building OP-TEE with `CFG_TEE_CORE_LOG_LEVEL=4`.
Building TF-A with `TF_A_LOGLVL=50` or `TF_A_LOGLVL=40` should give traces of entry/exit of secure world too.

**Comment by akorb** [comment]
`TF_A_LOGLVL=50` doesn't have an effect with `fvp.mk`. As a workaround, I simply added it manually to the according line in the Makefile.

This happens now:

![image](https://github.com/OP-TEE/optee_os/assets/6689889/75883d66-b381-40bc-96ad-f7890dedb64b)

As far as I can interpret it, the execution is given to BL32 (=OP-TEE), and then it stalls. But the second terminal started nevertheless, without any output. What is the first function that is executed in OP-TEE OS? Then maybe I can add a printing statement and figure out where exactly it's stalling (assuming the execution transfer from BL31 to BL32 works correctly).

**Comment by jenswi-linaro** [comment]
The first function is `_start()` in `core/arch/arm/kernel/entry_a64.S`. You can without too much trouble add some assembly code to output single characters on the UART to figure out where it goes wrong.

**Comment by akorb** [comment]
So, `bl32_init` [(here)](https://github.com/ARM-software/arm-trusted-firmware/blob/e318411f02f8a9526c97a23d0cdada2f128446e3/bl31/bl31_main.c#L166) points to `_start()`, correct?
Because this is the function that doesn't return for the Base platform, but it returns for the Foundation platform.

Also, is there some reference code somewhere in OP-TEE or somewhere else how to print characters on the UART via assembly code?

**Comment by akorb** [comment]
Instead of the approach of printing to the manual, I used [TarmacTrace](https://developer.arm.com/documentation/100964/1111-00/Plug-ins-for-Fast-Models/), a plug-in for FVP.

With that, I figured out the exact instruction that triggers the problem.
A snippet of the function call stack that leads to the problem is:
- [get_aslr_seed](https://github.com/OP-TEE/optee_os/blob/e8abbcfbdf63437a640d5fd87b7e191caab6445e/core/arch/arm/kernel/boot.c#L1581)
    - fdt_check_header
        - fdt_magic
            - fdt_get_header
                - [fdt32_ld](https://github.com/OP-TEE/optee_os/blob/e8abbcfbdf63437a640d5fd87b7e191caab6445e/core/lib/libfdt/include/libfdt.h#L127)

The disassembled version of fdt32_ld is:

```
0000000006036928 <fdt32_ld>:
fdt32_ld():
/home/andreas/optee_final/optee_os/core/lib/libfdt/include/libfdt.h:131
 6036928:       39400001        ldrb    w1, [x0]
 603692c:       39400402        ldrb    w2, [x0, #1]
 6036930:       aa022022        orr     x2, x1, x2, lsl #8
 6036934:       39400801        ldrb    w1, [x0, #2]
 6036938:       39400c00        ldrb    w0, [x0, #3]
 603693c:       aa014041        orr     x1, x2, x1, lsl #16
 6036940:       aa006020        orr     x0, x1, x0, lsl #24
/home/andreas/optee_final/optee_os/core/lib/libfdt/include/libfdt.h:135
 6036944:       5ac00800        rev     w0, w0
 6036948:       d65f03c0        ret
```

The first instruction (`ldrb  w1, [x0]`) triggers a synchronous exception.
It can be further analysed from the TarmacTrace log. The log file format is explained in the link at the top, e.g., [here](https://developer.arm.com/documentation/100964/1111-00/Plug-ins-for-Fast-Models/TarmacTrace/Processor-memory-access-trace?lang=en) is the memory access event log explained.

```
4492427940000 ps cluster0.cpu0 IT (449242794) 06008374 9400b9aa O EL1t_s : BL       {pc}+0x2e6a8 ; 0x6036a1c
4492427940000 ps cluster0.cpu0 R X30 0000000006008378
4492427950000 ps cluster0.cpu0 IT (449242795) 06036a1c a9bf7bfd O EL1t_s : STP      x29,x30,[sp,#-0x10]!
4492427950000 ps cluster0.cpu0 MW8 060b9c70:0000060b9c70 00000000_060b9c80
4492427950000 ps cluster0.cpu0 MW8 060b9c78:0000060b9c78 00000000_06008378
4492427950000 ps cluster0.cpu0 R SP_EL0 00000000060B9C70
4492427960000 ps cluster0.cpu0 IT (449242796) 06036a20 aa0003e3 O EL1t_s : MOV      x3,x0
4492427960000 ps cluster0.cpu0 R X3 0000000080000000
4492427970000 ps cluster0.cpu0 IT (449242797) 06036a24 910003fd O EL1t_s : MOV      x29,sp
4492427970000 ps cluster0.cpu0 R X29 00000000060B9C70
4492427980000 ps cluster0.cpu0 IT (449242798) 06036a28 97ffffc0 O EL1t_s : BL       {pc}-0x100 ; 0x6036928
4492427980000 ps cluster0.cpu0 R X30 0000000006036A2C

// Until here was just the prologue for some context, the next instruction causes the exception

4492427990000 ps cluster0.cpu0 IT (449242799) 06036928 39400001 O EL1t_s : LDRB     w1,[x0,#0]
4492427990000 ps cluster0.cpu0 MR1 80000000:000080000000 (ABORTED)
4492427990000 ps cluster0.cpu0 E 06036928:000006036928 EL1h 00000019 CoreEvent_ModeChange
4492427990000 ps cluster0.cpu0 E 06036928:000006036928 00000080 CoreEvent_CURRENT_SP0_SYNC
4492427990000 ps cluster0.cpu0 R cpsr 400003c5
4492427990000 ps cluster0.cpu0 R ESR_EL1 0000000096000210
4492427990000 ps cluster0.cpu0 R FAR_EL1 0000000080000000
4492427990000 ps cluster0.cpu0 R ELR_EL1 0000000006036928
4492427990000 ps cluster0.cpu0 R SPSR_EL1 00000000400002c4
4492427990000 ps cluster0.cpu0 SIGNAL: SIGNAL=DebugReset STATE=N
4492427990000 ps cluster0.cpu0 SIGNAL: SIGNAL=ResetHold STATE=N
4492428000000 ps cluster0.cpu0 IT (449242800) 06001000 14000000 O EL1h_s : B        {pc} ; 0x6001000
4492428010000 ps cluster0.cpu0 IT (449242801) 06001000 14000000 O EL1h_s : B        {pc} ; 0x6001000
4492428020000 ps cluster0.cpu0 IT (449242802) 06001000 14000000 O EL1h_s : B        {pc} ; 0x6001000
```

The exception-throwing instruction is here denoted as `LDRB     w1,[x0,#0]`.
Because of this load instruction, a **M**emory **R**ead of **1** byte (MR1) is logged. The accessed address seems to be (when I understand the log correctly) `0x80000000`, which seems to be invalid. The instruction aborts, the cpu resets and jumps to exactly [this](https://github.com/OP-TEE/optee_os/blob/e8abbcfbdf63437a640d5fd87b7e191caab6445e/core/arch/arm/kernel/entry_a64.S#L621) instruction. This instruction branches to itself and therefore, loops forever. The last three lines of the upper log snippet show this branch instruction. The log file continues like that until I stopped the simulation.

With this information, I did some further testing.
`MEASURED_BOOT=y` automatically enables `CFG_DT`. So, I rebuilt OP-TEE and TF-A without fTPM support, but with `CFG_DT=y`, to ensure that not the fTPM is the problem, but something with the device tree.
I tried this for the Foundation and the Base platform. Foundation keeps booting properly, while the Base platform freezes again. Hence, I'd conclude that the fTPM is not the problem, but somehow the device tree.

Do you have an idea what causes this memory access problem?

**Comment by jenswi-linaro** [comment]
Perhaps there's just garbage instead of useful DTB where OP-TEE starts using the DTB?

**Comment by akorb** [comment]
I doubt that, since the DTB parsing code isn't reached.
I further analysed the memory access problem. For that, I added some output:

```c
unsigned long __weak get_aslr_seed(void *fdt)
{
	int rc = 0;
	const uint64_t *seed = NULL;
	int offs = 0;
	int len = 0;

        // added additional output
        EMSG("fdt: %p", fdt);
        char* tmp = (char*)fdt;
        EMSG("fdt[0]: %02hhx", tmp[0]);
```

`fdt` is [handed to us](https://github.com/OP-TEE/optee_os/blob/e8abbcfbdf63437a640d5fd87b7e191caab6445e/core/arch/arm/kernel/entry_a64.S#L159C6-L159C9) by the previous boot component (via register `x2`).

`fdt` is `0x80000000`. Which makes sense, since according to the FVP Base documentation that's where the DRAM starts, with a size of 2 GB. The second `EMSG` is never printed, since `tmp[0]` triggers the synchronous exception. In other words, the content of the address is never retrieved, and therefore, the dtb parsing is not happening yet.
From the starting point of `0x80000000`, a block of `0x7f000000 - 1` bytes (=2032 MB - 1 Byte) yields the same exception. After this block, i.e., starting from the address `0x80000000 + 0x7f000000 = 0xff000000`, the memory is readable again.

For Foundation `fdt` references the same address (`0x80000000`), just that the memory access works and the memory region contains the dtb data.

I'm not sure what that tells us, though. Maybe the 2032 MB ring some bells for someone more experienced?
I also didn't find this size somewhere specified in the Base dtb file.
Is it possible that BL31 corrupts something? I'd wonder then why it works for Foundation but not Base, however.

**Comment by akorb** [comment]
Out of curiosity, I wondered if something goes wrong in OP-TEE or if the address is not accessible from the start.

I added `ldrb    w1, [x20]` near the entry point of OP-TEE. Note that x20 contains the address to the device tree, i.e., `0x80000000`.

```asm
FUNC _start , :
	mov	x19, x0
	mov	x20, x2		/* Save DT address */
	ldrb    w1, [x20]
```

It hangs immediately. So, the memory isn't accessible from the start of OP-TEE, which was expected I'd say.

**Comment by jenswi-linaro** [comment]
When MMU isn't enabled we're accessing memory using secure physical addresses. What if for some reason the model doesn't accept secure physical access to non-secure physical memory?

**Comment by akorb** [comment]
I checked the manuals to see how the DRAM memory range is configured security-wise.
For Foundation, Secure and Non-secure accesses are permitted.
For Base, it must be programmed by programming the TZC_400 (which is missing on Foundation). The programming is done by TF-A [here](https://github.com/ARM-software/arm-trusted-firmware/blob/9881bb93a3bc0a3ea37e9f093e09ab4b360a9e48/plat/arm/board/fvp/fvp_security.c#L14).
So, maybe somewhere there it's configured that the previously described memory block starting at `0x80000000` may only be accessed by non-secure accesses, but not secure accesses. I'm lacking technical in-depth knowledge to verify that.

Also, I found a workaround to accomplish my overall goal, allowing me persisting TA data with the Base platform.
For that, I start the Base platform with setting `-C bp.secure_memory=0`. This makes the Base platform boot and also `xtest` work.

This also allowed to me to check what is stored at `fdt` for the Base platform. As expected, its dtb content is stored there, just as for the Foundation platform.

So far so good, but the fTPM didn't work anymore. The linux ftpm kernel module loaded, but apparently silently failed without establishing the `/dev/` nodes. `dmesg` didn't receive any logs unfortunately.

I was able to fix this by building the whole software stack (TF-A, OP-TEE, and so on) for the Foundation platform, but still launching it with the Base platform. In other words, the [device tree of the Foundation platform](https://github.com/linaro-swg/linux/blob/optee/arch/arm64/boot/dts/arm/foundation-v8-gicv3-psci.dts) is used. Thereby, everything is working (boot, fTPM, xtest).

However, Plan9 isn't declared in the Foundation device tree, which hindered me at sharing a directory between host and guest. I manually enabled this in the device tree with: 
```diff
diff --git a/arch/arm64/boot/dts/arm/foundation-v8.dtsi b/arch/arm64/boot/dts/arm/foundation-v8.dtsi
index e8ef75fab..912016f9c 100644
--- a/arch/arm64/boot/dts/arm/foundation-v8.dtsi
+++ b/arch/arm64/boot/dts/arm/foundation-v8.dtsi
@@ -189,7 +189,8 @@ bus@8000000 {
                                <0 0 39 &gic 0 GIC_SPI 39 IRQ_TYPE_LEVEL_HIGH>,
                                <0 0 40 &gic 0 GIC_SPI 40 IRQ_TYPE_LEVEL_HIGH>,
                                <0 0 41 &gic 0 GIC_SPI 41 IRQ_TYPE_LEVEL_HIGH>,
-                               <0 0 42 &gic 0 GIC_SPI 42 IRQ_TYPE_LEVEL_HIGH>;
+                               <0 0 42 &gic 0 GIC_SPI 42 IRQ_TYPE_LEVEL_HIGH>,
+                               <0 0 43 &gic 0 GIC_SPI 43 IRQ_TYPE_LEVEL_HIGH>;
 
                ethernet@202000000 {
                        compatible = "smsc,lan91c111";
@@ -201,7 +202,7 @@ iofpga-bus@300000000 {
                        compatible = "simple-bus";
                        #address-cells = <1>;
                        #size-cells = <1>;
-                       ranges = <0 3 0 0x200000>;
+                       ranges = <0 3 0 0x210000>;
 
                        v2m_sysreg: sysreg@10000 {
                                compatible = "arm,vexpress-sysreg";
@@ -237,6 +238,12 @@ virtio@130000 {
                                reg = <0x130000 0x200>;
                                interrupts = <42>;
                        };
+
+                       virtio@140000 {
+                               compatible = "virtio,mmio";
+                               reg = <0x140000 0x200>;
+                               interrupts = <43>;
+                       };
                };
        };
```

As far as I can see until now, everything works perfectly now. But for sure it's a workaround and no fix. Maybe there is something broken in the Base device tree, or the TF-A configures the TZC_400 wrong. Anyways, I can continue working for now.

**Comment by jenswi-linaro** [comment]
Thanks for sharing.
