### ISSUE TITLE
internal compiler error on rand_lib.c when building qemu_v8 target in 3.21.0 and 3.22.0 manifests

### ISSUE THREAD

**Issue by rkomar** [OP-TEE/optee_os#6164]
I'm trying to build the op-tee QEMUv8 platform on a 64-bit ubuntu 22.04 system using the manifest build.  The build stops due to an internal compiler error when compiling edk2/CryptoPkg/Library/OpensslLib/openssl/crypto/rand/rand_lib.c.  It looks like the heap got corrupted in the compiler during the parsing stage.  I have this problem under both the 3.21.0 and 3.22.0 builds (which use the gcc 11.3-rel1 toolchain for x86_64).  The same file compiles fine using the 10.2 toolchain used with the 3.19.0 build.  My build system is a VirtualBox guest run on either of an i7 or i5 desktop system.  Has anyone else run into this issue?  It seems like I shouldn't be the only one who has experienced it, although I may be the only one who tried to run the build in a virtualbox guest.

**Comment by rkomar** [comment]
I managed to get the build running on the host system, and it produced the same internal compiler error.  So, this doesn't appear to be something caused by VirtualBox.

**Comment by rkomar** [comment]
I'll try that a bit later.  I touched the missing rand_lib.obj file in the hopes that it wasn't really needed, and managed to get the build to continue.  However, I got another internal compiler error later when building the buildroot.  This time, it was an unsupported instruction exception.  This leads me to believe that the arm toolchain is built for newer x86_64 architectures than my systems have (both machines are at least 10 years old).  If so, this is not really a problem with the op-tee manifest, and the Docker image probably won't help.  I'm going to try to build my own toolchain based on the arm toolchain sources and see if that fixes the builds.  In any case, I think you should not spend anymore time on this until I come back with more details.

**Comment by jforissier** [comment]
Sounds reasonable. If you want to build your own toolchain I recommend using crosstool-ng, it is very good, very convenient.
