### ISSUE TITLE
OP-TEE PKCS11 TA related issue

### ISSUE THREAD

**Issue by TMN11** [OP-TEE/optee_os#6166]
I've done the following steps:

1. INIT_TOKEN
2. OPEN RW SESSION
3. LOGIN TO SO
4. INIT_PIN
(Everything works perfect so far. It tells me that my session state is RW_SO_FUNCTIONS and pin is initialized)

5. LOGOUT
6. LOGIN TO USER
(Here it tells me that my session state is RO_PUBLIC... And failed to log in to the user)

I've tried everything: 
- after step 5: CLOSE_SESSION and OPEN_SESSION again, followed by login to the user
- after step 4, directly LOGIN to the user..nothing seems to work for me to login to the user

Sorry for the lack of context, but i guess people that know this functionality will understand. If not, I will try to give more details.

**Comment by etienne-lms** [comment]
Do you have any error code when log in as user fails?
Can you reprodure the issue with OP-TEE/Qemu setup and a dedicated xtest test ([pkcs11_1000.c](https://github.com/OP-TEE/optee_test/blob/master/host/xtest/pkcs11_1000.c)).

At step 5, I would expect the session state is RW_PUBLIC, since step 2. opened a rw session. 
See `session_logout()` from _ta/pkc11/src/pkcs11_token.c#L1388-L1391_ from 3.22.0:
https://github.com/OP-TEE/optee_os/blob/bb5d1825919719a1f4c3bc3a19f1040f427d8f60/ta/pkcs11/src/pkcs11_token.c#L1388-L1391

**Comment by TMN11** [comment]
I am getting at step 5 also RO_PUBLIC. So immediately after logout, although after step 4 session state is RW_SO...
I am working at reproducing the error with OP-TEE/Qemu setup and a dedicated xtest test.

"
...
step 4
session state -> 4 (RW_SO), no error code returned
step 5
 session state -> 0 (RO_PUBLIC), no error code returned
step 6
 session state -> 0 (RO_PUBLIC), no error code returned
"

**Comment by TMN11** [comment]
I am using the OP-TEE  ta directly, using commands like: PKCS11_CMD_SESSION_INFO, PKCS11_CMD_LOGIN, PKCS11_CMD_LOGOUT.

**Comment by TMN11** [comment]
Ok, so this works fine:


```
static void xtest_pkcs11_test_1000(ADBG_Case_t *c)
{

	//int ret = 0;
	CK_RV rv;
	rv = C_Initialize(0);
	if (rv)
		return;

	CK_UTF8CHAR token_user_pin[] = {
	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
};

	CK_UTF8CHAR token_so_pin[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8 , 9, 10, };
	CK_UTF8CHAR token_label[] = "PKCS11 TA test token";
	rv = C_InitToken(0, token_so_pin, sizeof(token_so_pin), token_label);
	if (!ADBG_EXPECT_CK_OK(c, rv))
		goto close_lib;

	CK_SESSION_HANDLE session = CK_INVALID_HANDLE;
	rv = C_OpenSession(0, CKF_SERIAL_SESSION | CKF_RW_SESSION, NULL, 0, &session);
	if (!ADBG_EXPECT_CK_OK(c, rv))
		goto close_lib;

	rv = C_Login(session, CKU_SO, token_so_pin,
		     sizeof(token_so_pin));
	if (!ADBG_EXPECT_CK_OK(c, rv))
		goto close_lib;

	rv = C_InitPIN(session, token_user_pin,
		       sizeof(token_user_pin));
	if (!ADBG_EXPECT_CK_OK(c, rv))
		goto close_lib;

	C_Logout(session);
	if (!ADBG_EXPECT_CK_OK(c, rv))
		goto close_lib;

	rv = C_Login(session, CKU_USER,	token_user_pin,
		     sizeof(token_user_pin));
	if (!ADBG_EXPECT_CK_OK(c, rv))
		goto out;

	CK_SESSION_INFO session_info = { };
	rv = C_GetSessionInfo(session, &session_info);
	if (!ADBG_EXPECT_CK_OK(c, rv))
		goto out;

	printf("\n\n TMN session state: %d \n\n", (int)session_info.state);




out:
	ADBG_EXPECT_CK_OK(c, C_CloseSession(session));
close_lib:
	ADBG_EXPECT_CK_OK(c, close_lib());

/*
	rv = C_Initialize(NULL);
	if (!ADBG_EXPECT_CK_OK(c, rv))
		return;

	rv = C_Finalize(NULL);
	if (!ADBG_EXPECT_CK_OK(c, rv))
		return;

	rv = C_Initialize(NULL);
	if (!ADBG_EXPECT_CK_OK(c, rv))
		return;

	rv = C_Initialize(NULL);
	ADBG_EXPECT_CK_RESULT(c, CKR_CRYPTOKI_ALREADY_INITIALIZED, rv);

	rv = C_Finalize(NULL);
	ADBG_EXPECT_CK_OK(c, rv);

	rv = C_Finalize(NULL);
	ADBG_EXPECT_CK_RESULT(c, CKR_CRYPTOKI_NOT_INITIALIZED, rv);

	*/
}
```


![Screenshot from 2023-07-12 15-17-29](https://github.com/OP-TEE/optee_os/assets/139214469/43f94d12-3114-402f-8725-c33668ffc750)


Here session state is 3, but I am doing the same thing when I am trying to access the PKCS11 TA directly.

**Comment by TMN11** [comment]
![Screenshot from 2023-07-17 16-48-21](https://github.com/OP-TEE/optee_os/assets/139214469/529d1a6a-5953-4a0f-85a6-8118c8647bf0)

I've seen that you guys are allocating some shared memory beetwen normal world and secure world, where you are placing the input parameters. If I am calling PKCS11_CMD_LOGIN from another TA (using TEE_InvokeTACommand) do I need to use some shared memory between the two TA's for the inputs also?

At this moment I am declaring them like this:

uint8_t data[n];
params_login[0].memref.buffer = data;
params_login[0].memref.size = n*sizeof(uint8_t);
