### ISSUE TITLE
Maximum number of TA's that can run in parallel

### ISSUE THREAD

**Issue by Jianqiang-Mei** [OP-TEE/optee_os#6172]
When I execute the following command in linux several times：
for i in {1..64}; do ./optee_example_hello_world&; done;
there will be many process that cannot be exit normally.
optee log print like this：
*D/TC:113 060 mobj_ffa_get_by_cookie:370 cookie 0x1 active: refc 2
*D/TC:??? 061 do_notif:36 sleep thread 61 0x8900b2a48
*D/TC:??? 060 do_notif:36 sleep thread 60 0x8900b2a48
*D/TC:115 058 mobj_ffa_get_by_cookie:370 cookie 0x1 active: refc 3
D/TC:114 059 mobj_ffa_get_by_cookie:370 cookie 0x1 active: refc 4
*D/TC:??? 058 do_notif:36 sleep thread 58 0x8900b2a48
*D/TC:??? 059 do_notif:36 sleep thread 59 0x8900b2a48
*D/TC:116 057 mobj_ffa_get_by_cookie:370 cookie 0x1 active: refc 5
D/TC:117 055 mobj_ffa_get_by_cookie:370 cookie 0x1 active: refc 6
*D/TC:??? 057 do_notif:36 sleep thread 57 0x8900b2a48
*D/TC:??? 055 do_notif:36 sleep thread 55 0x8900b2a48
What is maximum number of TA's that can run in parallel? And what does It depends on？

**Comment by jenswi-linaro** [comment]
The main constraint is the number of threads available. Then there's also the configured size of the heap and the amount of available TA memory. When pushing this to the limit you may find other bottlenecks too, but hopefully no crashes.
