### ISSUE TITLE
hash: TA panicked with code 0xffff0001

### ISSUE THREAD

**Issue by guagua-m** [OP-TEE/optee_os#6175]
Hello OP-TEE team,

I can't use the GP Internal API in my TA without any problems. I tried to locate the error and found that the error was returned in the TEE_DigestDoFinal() function with the following error log:
**my optee version: 3.21.0**

D/TC:? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA ebb6f4b5-7e33-4ad2-9802-e64f2a7cc20c
D/TC:? 0 ldelf_load_ldelf:96 ldelf load address 0x80006000
D/LD:  ldelf:135 Loading TS ebb6f4b5-7e33-4ad2-9802-e64f2a7cc20c
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ebb6f4b5-7e33-4ad2-9802-e64f2a7cc20c (early TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ebb6f4b5-7e33-4ad2-9802-e64f2a7cc20c (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ebb6f4b5-7e33-4ad2-9802-e64f2a7cc20c (REE)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0
D/LD:  ldelf:169 ELF (ebb6f4b5-7e33-4ad2-9802-e64f2a7cc20c) at 0x80031000
...
...
E/LD:   arch: aarch64
E/LD:  region  0: va 0x80004000 pa 0x0e333000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x80006000 pa 0x0e335000 size 0x008000 flags r-xs (ldelf)
E/LD:  region  2: va 0x8000e000 pa 0x0e33d000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x8000f000 pa 0x0e33e000 size 0x004000 flags rw-s (ldelf)
E/LD:  region  4: va 0x80013000 pa 0x0e342000 size 0x001000 flags r--s
E/LD:  region  5: va 0x80014000 pa 0x0e36c000 size 0x001000 flags rw-s (stack)
E/LD:  region  6: va 0x80015000 pa 0x7b8bee29 size 0x001000 flags rw-- (param)
E/LD:  region  7: va 0x80016000 pa 0x7b8be52a size 0x001000 flags rw-- (param)
E/LD:  region  8: va 0x80031000 pa 0x00001000 size 0x01c000 flags r-xs [0]
E/LD:  region  9: va 0x8004d000 pa 0x0001d000 size 0x00d000 flags rw-s [0]
E/LD:   [0] ebb6f4b5-7e33-4ad2-9802-e64f2a7cc20c @ 0x80031000
E/LD:  Call stack:
E/LD:   0x80039034
E/LD:   0x80031eb4
E/LD:   0x80031438
E/LD:   0x80031268
E/LD:   0x8003c51c
E/LD:   0x800334f8
D/TC:? 0 user_ta_enter:176 tee_user_ta_enter: TA panicked with code 0xffff0001
D/TC:? 0 destroy_ta_ctx_from_session:341 Remove references to context (0x48266ad8)
D/TC:? 0 destroy_context:326 Destroy TA ctx (0x48266ac0)
D/TC:? 0 tee_ta_close_session:529 csess 0x48266b20 id 2
D/TC:? 0 tee_ta_close_session:548 Destroy session
Thanks,
guagua_M

**Comment by jforissier** [comment]
0xffff0001 is TEE_ERROR_ACCESS_DENIED, what kind of output memory are you using? Should be TA private memory I think.

**Comment by guagua-m** [comment]
@jforissier How should I check which output memory I am using?

**Comment by jforissier** [comment]
Private memory is memory that is not shared by the TA. So, it can be in the heap (`TEE_Malloc()`), a global variable or on the stack. It can NOT be memory shared with the CA (that is memory coming as a parameter of `TA_InvokeCommandEntryPoint() or `TA_OpenSessionEntryPoint()`).

**Comment by guagua-m** [comment]
@jforissier Thanks, I probably understand a little bit. But I don't understand what my problem is. 
Here is my code for these two functions.

```TEE_Result TA_OpenSessionEntryPoint(uint32_t paramTypes, TEE_Param __maybe_unused params[4], 
                void __maybe_unused **sessionContext)
{
    TEE_Result ret=TEE_SUCCESS;
    TF("Crypto verify task TA_OpenSessionEntryPoint\n");

    UNUSED(paramTypes);
    UNUSED(params);
    UNUSED(sessionContext);

    return ret;
}

TEE_Result TA_InvokeCommandEntryPoint(void __maybe_unused *session_context,
                uint32_t cmd_id, 
                uint32_t paramTypes, TEE_Param params[4])
{
    TEE_Result l_ret = TEE_SUCCESS;
    int l_RetVal = FAIL;

    TF("CMD_ID = %d\n", cmd_id);

    /** 1) Handle the CA request message according to command index
    *      - EN_CMD_AES_KEY_GET: Get the aes boot key;
    *      - Default:            discard the message */
    switch(cmd_id)
    {
        case CMD_GEN_RANDOM_OPER: 
            TF("Start to generate random data!!!!\n");
            l_RetVal= g_CryptoTaHandle_Random(paramTypes, params);
            break;
        case CMD_SHA_OPER:
            TF("Entry the sha oper\n");
            l_RetVal = g_CryptoTaHandle_Sha(paramTypes, params);
            break;
        case CMD_AES_OPER:
            TF("Entry the aes operation!!!\n");
            l_RetVal = g_CryptoTaHandle_Aes(paramTypes, params);
            break;
        case CMD_PBKDF_OPER:
            TF("Entry pbkdf operation!!\n");
            l_RetVal = g_CryptoTaHandle_Pbkdf(paramTypes, params);
            break;
        case CMD_RSA_ENC_PKCS1_OPER:
            TF("Entry RSA1024_ENC_PKCS1!\n");
            l_RetVal = g_CryptoTaHandle_Rsa(paramTypes, params, EM_OP_ENC, PADDING_PKCS1);
            break;
        case CMD_RSA_DEC_PKCS1_OPER:
            TF("Entry RSA1024_DEC_PKCS1!\n");
            l_RetVal = g_CryptoTaHandle_Rsa(paramTypes, params, EM_OP_DEC, PADDING_PKCS1);
            break;
        case CMD_RSA_SIGN_PKCS1_OPER:
            TF("Entry RSA1024_SIGN_PKCS1!\n");
            l_RetVal = g_CryptoTaHandle_Rsa(paramTypes, params, EM_OP_SIGN, PADDING_PKCS1);
            break;
        case CMD_RSA_VERIFY_PKCS1_OPER:
            TF("Entry RSA1024_VERIFY_PKCS1!\n");
            l_RetVal = g_CryptoTaHandle_Rsa(paramTypes, params, EM_OP_VERIFY, PADDING_PKCS1);
            break;
        case CMD_HMAC_OPER:
            TF("Entry HMAC!\n");
            l_RetVal = g_CryptoTaHandle_hmac(paramTypes, params);
            break;
        case CMD_BASE64_OPER:
            TF("Entry BASE64!\n");
            l_RetVal = g_CryptoTaHandle_base64(paramTypes, params);
            break;

        default:
            l_RetVal = FAIL;
            break;
    }

    /**2) Check if the crypto operation is successful */
    if(FAIL == l_RetVal)
    {
        l_ret = TEE_FAIL;
    }
    else
    {
        l_ret = TEE_SUCCESS;
    }

    /**3) Return the result */
    return  l_ret;
}

**Comment by guagua-m** [comment]
And the above code works fine with both base64 and hmac.

**Comment by jforissier** [comment]
Sorry I was wrong when I said the output of `TEE_DigestDoFinal()` should be TA private memory. The spec has the `[outbuf]` qualifier which does allow shared memory. So this is not the cause of the error. I suggest more debugging, first use `symbolize.py` to decode the stack trace and make sure which function panics. Then add debug traces to the code (`DMSG()`) to locate where the `TEE_ERROR_ACCESS_DENIED` is set.

**Comment by guagua-m** [comment]
> Sorry I was wrong when I said the output of `TEE_DigestDoFinal()` should be TA private memory. The spec has the `[outbuf]` qualifier which does allow shared memory. So this is not the cause of the error. I suggest more debugging, first use `symbolize.py` to decode the stack trace and make sure which function panics. Then add debug traces to the code (`DMSG()`) to locate where the `TEE_ERROR_ACCESS_DENIED` is set.

The error function I locate when I use hash's command is TEE_DigestDoFinal(). Then I looked further and realized it was an error in the _utee_hash_final. That's as far as I can get.

**Comment by jforissier** [comment]
> The error function I locate when I use hash's command is TEE_DigestDoFinal(). Then I looked further and realized it was an error in the _utee_hash_final. That's as far as I can get.

`_utee_hash_final()` is a syscall wrapper for `syscall_hash_final()`, that is where things are happening.

**Comment by guagua-m** [comment]
@jforissier Sorry, But I don't know what an error here means.

**Comment by jforissier** [comment]
Just saying that if you put enough debug traces in `syscall_hash_final()` you should be able to understand why it returns an error...

**Comment by guagua-m** [comment]
Another question is that I'm running tee-supplicant to return an error, I don't know if this has any effect?
```
# tee-supplicant
ERR [151] TSUP:main:884: failed to find an OP-TEE supplicant device
# ps | grep supplicant
  101 tee      /usr/sbin/tee-supplicant -d /dev/teepriv0
  168 root     grep supplicant
# ls -al /dev/tee*
crw-rw----    1 root     teeclnt   247,   0 Jul 19 02:12 /dev/tee0
crw-rw----    1 root     tee       247,  16 Jul 19 02:12 /dev/teepriv0
# dmesg | grep optee
[    1.245719] optee: probing for conduit method.
[    1.247539] optee: revision 3.21 (e8abbcfb)
[    1.251631] optee: dynamic shared memory is enabled
[    1.273139] optee: initialized driver
[    1.274160] Driver 'optee' was unable to register with bus_type 'arm_ffa' because the bus was not initialized.

**Comment by guagua-m** [comment]
> Just saying that if you put enough debug traces in `syscall_hash_final()` you should be able to understand why it returns an error...
I added debug trace inside this function as you said and found that the vm_check_access_rights() function returns error 0xffff0001

**Comment by guagua-m** [comment]
> > I added debug trace inside this function as you said and found that the vm_check_access_rights() function returns error 0xffff0001
> 
> Which one? First call or second call?
> 
> It means the input or output buffer is invalid (not readable / nor writable)

Second, The first one returns success, the second one returns an error. Does that mean it's not writable but readable? How should I change the permissions?
```
res = vm_check_access_rights(&to_user_ta_ctx(sess->ctx)->uctx,
				     TEE_MEMORY_ACCESS_READ |
				     TEE_MEMORY_ACCESS_ANY_OWNER,
				     (uaddr_t)chunk, chunk_size);
	EMSG("1RES = 0x%x\n", res);
	if (res != TEE_SUCCESS)
		return res;

	res = get_user_u64_as_size_t(&hlen, hash_len);
	EMSG("2RES = 0x%x\n", res);
	if (res != TEE_SUCCESS)
		return res;

	res = vm_check_access_rights(&to_user_ta_ctx(sess->ctx)->uctx,
				     TEE_MEMORY_ACCESS_READ |
				     TEE_MEMORY_ACCESS_WRITE |
				     TEE_MEMORY_ACCESS_ANY_OWNER,
				     (uaddr_t)hash, hlen);
	EMSG("3RES = 0x%x\n", res);  //error! return 0xffff0001
	if (res != TEE_SUCCESS)
		return res;

**Comment by jforissier** [comment]
Check the output parameter to `TEE_DigestDoFinal()`. What is the address, is it writable, where does it come from?

**Comment by guagua-m** [comment]
> Check the output parameter to `TEE_DigestDoFinal()`. What is the address, is it writable, where does it come from?

The output buffer is obtained in the params parameter in the `TA_InvokeCommandEntryPoint(void __maybe_unused *session_context, uint32_t cmd_id,  uint32_t paramTypes, TEE_Param params[4])` function
```
TEE_Result TA_InvokeCommandEntryPoint(void __maybe_unused *session_context,
                uint32_t cmd_id, 
                uint32_t paramTypes, TEE_Param params[4])
{
    TEE_Result l_ret = TEE_SUCCESS;
    int l_RetVal = FAIL;

    TF("CMD_ID = %d\n", cmd_id);

    /** 1) Handle the CA request message according to command index
    *      - EN_CMD_AES_KEY_GET: Get the aes boot key;
    *      - Default:            discard the message */
    switch(cmd_id)
    {
        case CMD_GEN_RANDOM_OPER: 
            TF("Start to generate random data!!!!\n");
            l_RetVal= g_CryptoTaHandle_Random(paramTypes, params);
            break;
        case CMD_SHA_OPER:
            TF("Entry the sha oper\n");
            l_RetVal = g_CryptoTaHandle_Sha(paramTypes, params);
            break;
...

```
// TA sha
int g_CryptoTaHandle_Sha(uint32_t paramTypes, TEE_Param params[4])
{
    EN_SHA_MODE l_shaMode;
    CHAR* l_InputData= NULL;
    CHAR* l_OutPut = NULL;
    UINT32 l_InputLen = 0U;
    UINT32 l_OutputLen = 0U;
    UNUSED(paramTypes);

    /**1) Get the sha mode, input data info & output info */
    l_InputData = params[0].memref.buffer;
    l_InputLen = params[0].memref.size;
    l_shaMode = params[1].value.a;
    l_OutPut = params[2].memref.buffer;
    l_OutputLen = params[2].memref.size;

    /**2) Do sha operation */
    g_CryptoTaHash_sha(l_shaMode, l_InputData, l_InputLen, l_OutPut, &l_OutputLen);
    
    return OK;
}

```
int g_CryptoTaHash_sha(EN_SHA_MODE shaMode, CHAR* input, UINT32 inLen, CHAR* output, UINT32* pOutLen)
{
    TEE_Result ret;
    TEE_OperationHandle l_OperationHandle;   
    TEE_CRYPTO_ALGORITHM_ID l_AlgorithmId;
    int l_RetVal = OK;
    
    TF("Input data just like follow(0x%x), 0x%x:\n", inLen, (UINT32)(output));
    //g_TA_Printf(input, 20);

    /**1) Set the algorithm variable */
    switch(shaMode)
    {
        case EN_OP_SHA1:
            TF("The md is sha1@!!!!\n");
            l_AlgorithmId = TEE_ALG_SHA1;
            break;
        case EN_OP_SHA256:
            l_AlgorithmId = TEE_ALG_SHA256;
            break;
        default:
            l_AlgorithmId = TEE_ALG_INVALID ;
            l_RetVal = FAIL;
            goto cleanup_1;
            TF("Invalid sha mode\n");
            break;
    }

    /**2) Allocate the operation handle */
    ret = TEE_AllocateOperation(&l_OperationHandle, l_AlgorithmId, TEE_MODE_DIGEST, 0);
    if(ret != TEE_SUCCESS) 
    {
        TF("Allocate SHA operation handle fail\n");
        l_RetVal = FAIL;
        goto cleanup_1;
    }

    TEE_DigestUpdate(l_OperationHandle, input, inLen);

    /**4) Do the final sha operation */
    ret = TEE_DigestDoFinal(l_OperationHandle, NULL, 0, output, pOutLen);
    TF("The out put length is :%d\n", *pOutLen);
    TF("The return value is :0x%x\n", ret);
    //ret = TEE_DigestDoFinal(l_OperationHandle, l_pInputTmp, inLen, output, pOutLen);
    if(ret != TEE_SUCCESS)
    {
        TF("Do the final sha operation fail\n");
        l_RetVal = FAIL;
        goto cleanup_2;
    }
...

**Comment by guagua-m** [comment]
> > Check the output parameter to `TEE_DigestDoFinal()`. What is the address, is it writable, where does it come from?
> 
> The output buffer is obtained in the params parameter in the `TA_InvokeCommandEntryPoint()` function
> 
> ```
> TEE_Result TA_InvokeCommandEntryPoint(void __maybe_unused *session_context,
>                 uint32_t cmd_id, 
>                 uint32_t paramTypes, TEE_Param params[4])
> {
>     TEE_Result l_ret = TEE_SUCCESS;
>     int l_RetVal = FAIL;
> 
>     TF("CMD_ID = %d\n", cmd_id);
> 
>     /** 1) Handle the CA request message according to command index
>     *      - EN_CMD_AES_KEY_GET: Get the aes boot key;
>     *      - Default:            discard the message */
>     switch(cmd_id)
>     {
>         case CMD_GEN_RANDOM_OPER: 
>             TF("Start to generate random data!!!!\n");
>             l_RetVal= g_CryptoTaHandle_Random(paramTypes, params);
>             break;
>         case CMD_SHA_OPER:
>             TF("Entry the sha oper\n");
>             l_RetVal = g_CryptoTaHandle_Sha(paramTypes, params);
>             break;
> ...
> ```
> 
> int g_CryptoTaHandle_Sha(uint32_t paramTypes, TEE_Param params[4]) { EN_SHA_MODE l_shaMode; CHAR* l_InputData= NULL; CHAR* l_OutPut = NULL; UINT32 l_InputLen = 0U; UINT32 l_OutputLen = 0U; UNUSED(paramTypes);
> 
> ```
> /**1) Get the sha mode, input data info & output info */
> l_InputData = params[0].memref.buffer;
> l_InputLen = params[0].memref.size;
> l_shaMode = params[1].value.a;
> l_OutPut = params[2].memref.buffer;
> l_OutputLen = params[2].memref.size;
> 
> /**2) Do sha operation */
> g_CryptoTaHash_sha(l_shaMode, l_InputData, l_InputLen, l_OutPut, &l_OutputLen);
> 
> return OK;
> ```
> 
> }
> 
> ```
> int g_CryptoTaHash_sha(EN_SHA_MODE shaMode, CHAR* input, UINT32 inLen, CHAR* output, UINT32* pOutLen)
> {
>     TEE_Result ret;
>     TEE_OperationHandle l_OperationHandle;   
>     TEE_CRYPTO_ALGORITHM_ID l_AlgorithmId;
>     int l_RetVal = OK;
>     
>     TF("Input data just like follow(0x%x), 0x%x:\n", inLen, (UINT32)(output));
>     //g_TA_Printf(input, 20);
> 
>     /**1) Set the algorithm variable */
>     switch(shaMode)
>     {
>         case EN_OP_SHA1:
>             TF("The md is sha1@!!!!\n");
>             l_AlgorithmId = TEE_ALG_SHA1;
>             break;
>         case EN_OP_SHA256:
>             l_AlgorithmId = TEE_ALG_SHA256;
>             break;
>         default:
>             l_AlgorithmId = TEE_ALG_INVALID ;
>             l_RetVal = FAIL;
>             goto cleanup_1;
>             TF("Invalid sha mode\n");
>             break;
>     }
> 
>     /**2) Allocate the operation handle */
>     ret = TEE_AllocateOperation(&l_OperationHandle, l_AlgorithmId, TEE_MODE_DIGEST, 0);
>     if(ret != TEE_SUCCESS) 
>     {
>         TF("Allocate SHA operation handle fail\n");
>         l_RetVal = FAIL;
>         goto cleanup_1;
>     }
> 
>     TEE_DigestUpdate(l_OperationHandle, input, inLen);
> 
>     /**4) Do the final sha operation */
>     ret = TEE_DigestDoFinal(l_OperationHandle, NULL, 0, output, pOutLen);
>     TF("The out put length is :%d\n", *pOutLen);
>     TF("The return value is :0x%x\n", ret);
>     //ret = TEE_DigestDoFinal(l_OperationHandle, l_pInputTmp, inLen, output, pOutLen);
>     if(ret != TEE_SUCCESS)
>     {
>         TF("Do the final sha operation fail\n");
>         l_RetVal = FAIL;
>         goto cleanup_2;
>     }
> ...
> ```

**Comment by jforissier** [comment]
```
            l_RetVal = g_CryptoTaHandle_Sha(paramTypes, params);
```
What's the value of `paramTypes`? Does it reflect the fact that `params[2].memref` is an output-capable buffer?
Or in other words: how do you set the parameters on the client side?

**Comment by guagua-m** [comment]
> ```
>             l_RetVal = g_CryptoTaHandle_Sha(paramTypes, params);
> ```
> 
> What's the value of `paramTypes`? Does it reflect the fact that `params[2].memref` is an output-capable buffer? Or in other words: how do you set the parameters on the client side?

paramtypes = 1557, I think it indicates that the first parameter is an input/output value, the second parameter is an input value, the third parameter is an output value, and the fourth parameter is not used. Is this correct? So should I change the third parameter to input/output?

**Comment by guagua-m** [comment]
@jforissier Thank you for your help. I finally solved the problem, I had previously used the address fetching approach when passing in `l_OutputLen` in the `g_CryptoTaHandle_Sha()` function. 
When I initialized `l_OutputLen` to a pointer and used `TEE_Malloc()` to allocate memory, this code worked. 
But I don't really understand why this is. Because the wrong code with the hash_len parameter passed correctly runs the following statement `res = get_user_u64_as_size_t(&hlen, hash_len)` (`in syscall_hash_final()`), and prints the value of `hlen` correctly, but it does not pass the checking of `vm_check_access_rights`.
Here is the code I changed:
```
int g_CryptoTaHandle_Sha(uint32_t paramTypes, TEE_Param params[4])
{
    EN_SHA_MODE l_shaMode;
    CHAR* l_InputData= NULL;
    CHAR* l_OutPut = NULL;
    UINT32 l_InputLen = 0U;
    UINT32* l_OutputLen = NULL;
    UNUSED(paramTypes);

    /**1) Get the sha mode, input data info & output info */
    l_InputData = params[0].memref.buffer;
    l_InputLen = params[0].memref.size;
    l_shaMode = params[1].value.a;
    l_OutPut = params[2].memref.buffer;
    l_OutputLen = TEE_Malloc(1, 0);
    if (!l_OutputLen)
        return TEE_ERROR_OUT_OF_MEMORY;
    *l_OutputLen = params[2].memref.size;

    /**2) Do sha operation */
    g_CryptoTaHash_sha(l_shaMode, l_InputData, l_InputLen, l_OutPut, l_OutputLen);
    params[2].memref.size = *l_OutputLen;
    TEE_MemMove(params[2].memref.buffer, l_OutPut, *l_OutputLen);
    TEE_Free(l_OutputLen);
    return OK;
}
```

**Comment by jforissier** [comment]
>     l_OutputLen = TEE_Malloc(1, 0);

Should be `l_OutputLen = TEE_Malloc(sizeof(*l_OutputLen), 0);` in other words 4 bytes not 1.

**Comment by guagua-m** [comment]
> > ```
> > l_OutputLen = TEE_Malloc(1, 0);
> > ```
> 
> Should be `l_OutputLen = TEE_Malloc(sizeof(*l_OutputLen), 0);` in other words 4 bytes not 1.

Oh，thanks!
