### ISSUE TITLE
How to make TA in RasberryPi3 connected to PC

### ISSUE THREAD

**Issue by shuta1000** [OP-TEE/optee_os#6177]
Hello. 
I'm trying to create a TA with OP-TEE(3.21.0) and Ubuntu(22.04.2).
The RasberryPi3 connected to a PC with a UART cable.
Is it possible to create a TA on a PC in this state and incorporate it into OP-TEE?

If there is already a similar question in the past, I would be glad to know.
Lastly, I'm not from an English-speaking country, so my English may not be correct.

**Comment by jenswi-linaro** [comment]
The short answer is yes.

There's more device-specific information available at https://optee.readthedocs.io/en/latest/building/devices/rpi3.html.
I'd recommend testing a bit first with the TAs already available, perhaps the hello world TA.
