### ISSUE TITLE
Implementation of ECDH Key Exchange Implementation between Trusted Party and Untrusted Party

### ISSUE THREAD

**Issue by intx4** [OP-TEE/optee_os#6178]
Hello,
I am very new to OP-TEE and I am getting familiar with the Client API and TEE Internal API. To play around with the APIs, I wanted to implement a toy example in which a trusted party A, and an untrusted party B perform a ECDH Key exchange. For this, I want to create a TA application that will handle all the cryptographic operations for party B. I have a rough idea on how to implement it on the TA side (i.e., which API functions to call inside the TA code), but I have two questions for the CA side. Specifically, in the toy example, I want to implement party A as a CA which communicates with the TA over, for example, a TCP socket.
The two questions are:
1 - How can I create a socket for network communication between the TA and a CA?
2 - In the CA, how can I create a ECDH key pair such that I can send (and receive) the key material and perform the Point Multiplication to derive the shared key? In other words, can I use a library for this such that it is consistent to what happens under the hood in the TA code using the TEE internal API? I have tried to reverse engineer the function calls in the TA, but with no sucess. I have seen that two libraries are used, ```mbedtls``` and ```libtomcrypt```, but not sure which one to use.

Thanks in advance for the help or any pointers :)

**Comment by jforissier** [comment]
Hello @intx4,

The CA typically communicates with the TA using the TEE Client API. Why would you need something else (a socket)?
The CA is a "normal" Linux application so you may use any cryptographic library you want (OpenSSL, MBed TLS are two examples).

**Comment by intx4** [comment]
Hi @jforissier,
Thanks a lot for the reply. Sorry I forgot to mention a crucial part of my scenario. What I refer to trusted party A is a CA leaving in a REE which is not necessarily deployed in the same machine of the TEE (e.g., a remote server). The goal then would be to establish a chennel (which ideally would be secure like with TLS, but for the sake of the example can be just a TCP socket) to make the CA of party A communicate with the TA deployed in the machine of the untrusted party B (i.e., for untrusted here I mean that the REE of the machine representing party B might be untrusted, so the need for a TA to handle the cryptographic operations). Hence the problem is that if I want to implemente a ECDH key exchange, I assume I would need to handle the cryptographic operations happening at party A CA (which is trusted) in such a way that the parameters sent over the socket (e.g., EC public key) can be straightforwardly used by the code in the TA of party B by simplying invoking the right API calls.
Hope this is more clear.

**Comment by ivila** [comment]
I think you can try develop a tee-suppliant plugin?
check this: https://github.com/OP-TEE/optee_docs/pull/102/files
