### ISSUE TITLE
Does OPTEE plan to support Samsung chips such as Exynos 4 Quad (4412)?

### ISSUE THREAD

**Issue by splinuxarm** [OP-TEE/optee_os#6180]
Does OPTEE plan to support Samsung chips such as Exynos 4 Quad (4412)?
I currently have OPTEE running on QEMU. I want to run OPTEE on a real device and try to port it myself. Sorry I'm a newbie for TEE. I have a 4412 development board in my hand, and I can find the register definitions of 4412 TZASC and TZPC from a public document. Is this information sufficient?

**Comment by jforissier** [comment]
Hi @splinuxarm,

>  I have a 4412 development board in my hand, and I can find the register definitions of 4412 TZASC and TZPC from a public document. Is this information sufficient?

You will need to know a bit more. For example, how should the platform boot, an more specifically where should OP-TEE be loaded ? (physical address range). Which kind of UART is available for OP-TEE to use for secure console output, and at which address is it, how should it be configured?

You may want to check the Git history for commits introducing new platforms (for example 28a029b5b). Also the documentation may help: https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html

**Comment by splinuxarm** [comment]
Hi @jforissier ,
Thanks for your suggestion, I will follow your suggestion to make this work. Thanks again.
