### ISSUE TITLE
Address Sanitizer

### ISSUE THREAD

**Issue by ZijjWang** [OP-TEE/optee_os#6182]
Hi,

We registered the platform in optee and developed the driver. Now I want to use address sanitizer to eliminate address out-of-bounds and other problems.

Does the optee platform support address sanitizer? How to enable it?

Thanks.

**Comment by jenswi-linaro** [comment]
Yes, but it is a bit tricky to enable. The flag to enable is `CFG_CORE_SANITIZE_KADDRESS`, the look for how `CFG_ASAN_SHADOW_OFFSET` is provided in `core/arch/arm/plat-vexpress/conf.mk` and try to do the same calculation for your platform.

**Comment by jenswi-linaro** [comment]
It might be a good idea to try it out a bit on QEMU first just to see that it works as you expect.
Another option is `CFG_MEMTAG=y` if your platform can support it.
