### ISSUE TITLE
Panic in interrupt_main_handler

### ISSUE THREAD

**Issue by LeiSen62** [OP-TEE/optee_os#6183]
Hi, when I update OPTEE-OS from 3.20.0 to 3.22.0 and run xtest 4005 in the D06 platform, the following error message is displayed:
F/TC:??? 00 trace_syscall:163 syscall #24 (syscall_cryp_obj_get_info)
F/TC:??? 00 trace_syscall:163 syscall #24 (syscall_cryp_obj_get_info)
F/TC:??? 00 trace_syscall:163 syscall #31 (syscall_cryp_obj_copy)
F/TC:??? 00 trace_syscall:163 syscall #24 (syscall_cryp_obj_get_info)
F/TC:??? 00 trace_syscall:163 syscall #28 (syscall_cryp_obj_close)
F/TC:??? 00 trace_syscall:163 syscall #34 (syscall_authenc_init)
F/TC:??? 00 trace_syscall:163 syscall #35 (syscall_authenc_update_aad)
F/TC:??? 00 trace_syscall:163 syscall #35 (syscall_authenc_update_aad)
F/TC:??? 00 trace_syscall:163 syscall #8 (syscall_check_access_rights)
E/TC:116 00 Panic 'Secure interrupt handler not defined' at core/kernel/interrupt.c:142 <interrupt_main_handler>

Other xtest cases are successfully executed. What do I need to do to adapt to version 3.22.0?

**Comment by jforissier** [comment]
Hello @LeiSen62,

I believe you need to rename your implementation of `itr_core_handler()` to `interrupt_main_handler()`, due to this commit: 358bf47c0.

**Comment by LeiSen62** [comment]
Thanks，I also need to set CFG_GIC=y。
