### ISSUE TITLE
QEMU 8.0.0 issue with OP-TEE latest version on Ubuntu22.04：pflash_write: Write to buffer emulation is flawed

### ISSUE THREAD

**Issue by buaamy** [OP-TEE/optee_os#6185]
I have met an issue when execute “c" in QEMU console. The error message I see on the QEMU side:

**make[1]: Entering directory '/home/mayao/Desktop/optee/build'
ln -sf /home/mayao/Desktop/optee/build/../out-br/images/rootfs.cpio.gz /home/mayao/Desktop/optee/build/../out/bin/

* QEMU is now waiting to start the execution
* Start execution with either a 'c' followed by <enter> in the QEMU console or
* attach a debugger and continue from there.
*
* To run OP-TEE tests, use the xtest command in the 'Normal World' terminal
* Enter 'xtest -h' for help.

cd /home/mayao/Desktop/optee/build/../out/bin && /home/mayao/Desktop/optee/build/../qemu/build/aarch64-softmmu/qemu-system-aarch64 \
        -nographic \
        -serial tcp:localhost:54320 -serial tcp:localhost:54321 \
        -smp 2 \
        -s -S -machine virt,secure=on,mte=off,gic-version=3,virtualization=false \
        -cpu max,sme=on,pauth-impdef=on \
        -d unimp -semihosting-config enable=on,target=native \
        -m 1057 \
        -bios bl1.bin           \
        -initrd rootfs.cpio.gz \
        -kernel Image -no-acpi \
        -append 'console=ttyAMA0,38400 keep_bootcon root=/dev/vda2 ' \
         \
        -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,max-bytes=1024,period=1000 -netdev user,id=vmnic -d
evice virtio-net-device,netdev=vmnic
qemu-system-aarch64: -no-acpi: warning: -no-acpi is deprecated, use '-machine acpi=off' instead
QEMU 8.0.0 monitor - type 'help' for more information
(qemu) c
(qemu) pflash_write: Write to buffer emulation is flawed
pflash_write: Write to buffer emulation is flawed
pflash_write: Write to buffer emulation is flawed
pflash_write: Write to buffer emulation is flawed
pflash_write: Write to buffer emulation is flawed
pflash_write: Write to buffer emulation is flawed
pflash_write: Write to buffer emulation is flawed**

For the above reason, I can‘t start the REE and the TEE console，qemu just stop there without any response.

**Comment by jforissier** [comment]
>  pflash_write: Write to buffer emulation is flawed

This message has been present in the QEMU output for ages. It is not the cause of the issue. Please make sure you have the latest commits in the `build/` directory (up to https://github.com/OP-TEE/build/commit/490323419a0bd89b594238d0c71a917b760276e4 at least), then do: `make arm-tf-clean` and `make run` again.

**Comment by buaamy** [comment]
> > pflash_write: Write to buffer emulation is flawed
> 
> This message has been present in the QEMU output for ages. It is not the cause of the issue. Please make sure you have the latest commits in the `build/` directory (up to [OP-TEE/build@4903234](https://github.com/OP-TEE/build/commit/490323419a0bd89b594238d0c71a917b760276e4) at least), then do: `make arm-tf-clean` and `make run` again.

I’ve  checked qemu_v8.mk in `build/` directory：
  
`TF_A_FLAGS ?= \
        BL33=$(BL33_BIN) \
        PLAT=qemu \
        QEMU_USE_GIC_DRIVER=$(TFA_GIC_DRIVER) \
        ENABLE_SVE_FOR_NS=2 \
        ENABLE_SME_FOR_NS=2 \
        ENABLE_SVE_FOR_SWD=1 \
        ENABLE_SME_FOR_SWD=1 \
        ENABLE_FEAT_FGT=2 \
        BL32_RAM_LOCATION=tdram \
        DEBUG=$(TF_A_DEBUG) \
        LOG_LEVEL=$(TF_A_LOGLVL)`

，then do `make arm-tf-clean` and `make run`，but the issue is still the same.

**Comment by jforissier** [comment]
Well, I just re-built from scratch using this Dockerfile: https://github.com/OP-TEE/optee_docs/files/12068209/Dockerfile.22.04.txt and it worked. So I don't know what's wrong on your side.

**Comment by buaamy** [comment]
> Well, I just re-built from scratch using this Dockerfile: https://github.com/OP-TEE/optee_docs/files/12068209/Dockerfile.22.04.txt and it worked. So I don't know what's wrong on your side.

Solved! Thanks a lot！
