### ISSUE TITLE
The booted CPU cores is not equal to CFG_TEE_CORE_NB_CORE

### ISSUE THREAD

**Issue by jiameixie** [OP-TEE/optee_os#6193]
Does CFG_TEE_CORE_NB_CORE decide the number of CPU cores in OPTEE, ie the number of calls to function [boot_cpu_on_handler](https://github.com/OP-TEE/optee_os/blob/e4b1172625af43092b8742144113b64375190b71/core/arch/arm/kernel/boot.c#L1254)？ In the TF-A device tree, it has 16 CPU cores and PLATFORM_CORE_COUNT is 16. I defined CFG_TEE_CORE_NB_CORE = 16, but it turns out only 4 CPU core is up and it can't enter Linux.

```
I/TC: Primary CPU switching to normal world boot
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0xe0000000
INFO:    SPSR = 0x3c9
I/TC: xjm 000 boot_cpu_on_handler CFG_WITH_ARM_TRUSTED_FW
I/TC: xjm Secondary CPU 4 initializing
I/TC: xjm init_secondary_helper, CFG_TEE_CORE_NB_CORE:0x10
I/TC: Secondary CPU 4 switching to normal world boot
I/TC: xjm 000 boot_cpu_on_handler CFG_WITH_ARM_TRUSTED_FW
I/TC: xjm Secondary CPU 8 initializing
I/TC: xjm init_secondary_helper, CFG_TEE_CORE_NB_CORE:0x10
I/TC: Secondary CPU 8 switching to normal world boot
I/TC: xjm 000 boot_cpu_on_handler CFG_WITH_ARM_TRUSTED_FW
I/TC: xjm Secondary CPU 12 initializing
I/TC: xjm init_secondary_helper, CFG_TEE_CORE_NB_CORE:0x10
I/TC: Secondary CPU 12 switching to normal world boot
```

 If limiting the CPU cores to 4 in the GRUB_LINUX command, it can enter Linux normally.
My optee cfg is as below:
```
CFG_ARM64_core ?= y
CFG_ARM_GICV3 = y
CFG_CORE_SEL1_SPMC = y
CFG_WITH_ARM_TRUSTED_FW	= y
CFG_CORE_RESERVED_SHM = n
CFG_CORE_FFA=y
CFG_WITH_SP=y 
CFG_DT=y
CFG_TEE_BENCHMARK=n
CFG_TEE_CORE_LOG_LEVEL=4
CFG_SECURE_PARTITION=y
CFG_MAP_EXT_DT_SECURE=y
$(call force,CFG_GIC,y)
$(call force,CFG_PL011,y)
$(call force,CFG_SECURE_TIME_SOURCE_CNTPCT,y)
$(call force,CFG_CORE_ARM64_PA_BITS,42)
$(call force,CFG_TEE_CORE_NB_CORE,16)
```

**Comment by jforissier** [comment]
OP-TEE expects the CPU cores to be numbered sequentially in the range 0 .. CFG_TEE_CORE_NB_CORE. The core number is returned by the inline function `get_core_pos()` which is implemented by `__get_core_pos()`, which in turn relies on `get_core_pos_mpidr()`. That function is platform-specific but there is a default (`weak`) implementation in `core/arch/arm/kernel/misc_a64.S`. The default implementation relies on `CFG_CORE_CLUSTER_SHIFT` and `CFG_CORE_THREAD_SHIFT` to compute the code number from the MPIDR. I suspect these values are wrong for your platform. See the comments in [`mk/config.mk`](https://github.com/OP-TEE/optee_os/blob/3.22.0/mk/config.mk#L652-L662).

**Comment by jiameixie** [comment]
I see. I don't define this function.  Thanks very much. Do I need to define the CPUs in the sp_manifest.dts in TF-A like https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/tree/plat/arm/board/fvp/fdts/fvp_spmc_optee_sp_manifest.dts#n48?  I run optee without Hafnium.

**Comment by jforissier** [comment]
Does it boot further if you set `CFG_TEE_CORE_NB_CORE=128`?

I suggest to apply this patch first to print the MPIDR of each secondary CPU as it enters OP-TEE:
```diff
diff --git a/core/arch/arm/kernel/boot.c b/core/arch/arm/kernel/boot.c
index 95055e01b..59d6c17f1 100644
--- a/core/arch/arm/kernel/boot.c
+++ b/core/arch/arm/kernel/boot.c
@@ -1223,6 +1223,7 @@ static void init_secondary_helper(unsigned long nsec_entry)
 	 * its functions.
 	 */
 	thread_set_exceptions(THREAD_EXCP_ALL);
+	IMSG("MPIDR: 0x%08x", read_mpidr());
 
 	secondary_init_cntfrq();
 	thread_init_per_cpu();
```


You want to make sure that `get_core_pos_mpidr(mpidr)` returns a value between 0 and 15 for any valid value of `mpidr`.

**Comment by jiameixie** [comment]
The CPU cores can be booted successfully after adding my own platform implementation of `get_core_pos_mpidr()`  without setting the CPU nodes in the `sp_manifest.dts `in TF-A.

**Comment by jforissier** [comment]
@jiameixie glad it worked! Therefore I am closing this issue.
