### ISSUE TITLE
Panic issued by fault mitigation

### ISSUE THREAD

**Issue by vsatoes** [OP-TEE/optee_os#6196]
Hello,

I have updated a platform to use optee v3.21 and when running AOSP VTS to test a [keymaster](https://github.com/linaro-swg/kmgk) feature, I run into a panic issued by fault mitigation.

Here is the log of the error:
```
E/TA:  TA_finish:1867 Finish operation failed with error code ffffffe2              
E/TA:  TA_rsa_finish:270 RSA no pad verification signature failed                   
E/TA:  TA_finish:1867 Finish operation failed with error code ffffffe2              
E/TA:  TA_rsa_finish:270 RSA no pad verification signature failed                   
E/TA:  TA_finish:1867 Finish operation failed with error code ffffffe2              
E/TA:  TA_finish:1867 Finish operation failed with error code ffffffe2              
E/TC:0 0 Panic at lib/libutils/ext/fault_mitigation.c:87 <___ftmn_callee_done_check>
E/TC:0 0 TEE load address @ 0x43200000                                              
E/TC:0 0 Call stack:                                                                
E/TC:0 0  0x4320a7ac                                                                
E/TC:0 0  0x4321fed8                                                                
E/TC:0 0  0x4327c464                                                                
E/TC:0 0  0x43262c24                                                                
E/TC:0 0  0x43257580                         
E/TC:0 0  0x43247194                         
E/TC:0 0  0x43206c1c                         
E/TC:0 0  0x4320669c                         
E/TC:0 0  0x4320439c                         
```
With a higher log level and translating symbols:
```
D/TA:  TA_deserialize_param_set:339 TA_deserialize_param_set 339
D/TA:  TA_deserialize_param_set:360 params->length:20
D/TA:  TA_add_origin:478 TA_add_origin 478
D/TA:  TA_restore_key:790 populate attrs is finished with err 0
D/TA:  TA_possibe_size:111 TA_possibe_size 111
F/TC:? 0 trace_syscall:149 syscall #8 (syscall_check_access_rights)
F/TC:? 0 trace_syscall:149 syscall #20 (syscall_hash_final)
F/TC:? 0 trace_syscall:149 syscall #18 (syscall_hash_init)
F/TC:? 0 trace_syscall:149 syscall #40 (syscall_asymm_verify)
E/TC:2 0 Panic at lib/libutils/ext/fault_mitigation.c:87 <___ftmn_callee_done_check>
E/TC:2 0 TEE load address @ 0x43200000
E/TC:2 0 Call stack:
E/TC:2 0  0x4320a9f0 print_kernel_stack at optee-os/core/arch/arm/kernel/unwind_arm64.c:91
E/TC:2 0  0x432203fc __do_panic at optee-os/core/kernel/panic.c:26 (discriminator 32)
E/TC:2 0  0x4327d324 ___ftmn_callee_done_check at optee-os/lib/libutils/ext/fault_mitigation.c:87
E/TC:2 0  0x43263aac __ftmn_callee_done_check at optee-os/lib/libutils/ext/include/fault_mitigation.h:349
E/TC:2 0  0x43258408 sw_crypto_acipher_rsassa_verify at optee-os/core/lib/libtomcrypt/rsa.c:669
E/TC:2 0  0x43247ecc syscall_asymm_verify at optee-os/core/tee/tee_svc_cryp.c:4420
E/TC:2 0  0x43206d18 scall_do_call at optee-os/core/arch/arm/kernel/arch_scall_a64.S:140
E/TC:2 0  0x43206798 thread_scall_handler at optee-os/core/arch/arm/kernel/thread.c:1115
E/TC:2 0  0x432043e8 el0_svc at optee-os/core/arch/arm/kernel/thread_a64.S:850
```
The [VTS](https://cs.android.com/android/platform/superproject/+/android-12.0.0_r34:hardware/interfaces/keymaster/3.0/vts/functional/keymaster_hidl_hal_test.cpp;l=2035) test being executed verifies RSA signature/verifications and it panics on the last [test](https://cs.android.com/android/platform/superproject/+/android-12.0.0_r34:hardware/interfaces/keymaster/3.0/vts/functional/keymaster_hidl_hal_test.cpp;l=2121).

The following errors are expected, since VTS forces a corrupt signature. 
```
E/TA:  TA_rsa_finish:270 RSA no pad verification signature failed                   
E/TA:  TA_finish:1867 Finish operation failed with error code ffffffe2              
E/TA:  TA_finish:1867 Finish operation failed with error code ffffffe2 
```
However, the generated panic seems to indicate a mismatch between `ftmn.check.res` and `res`. 
By disabling `CFG_FAULT_MITIGATION` test passes with expected previous errors.

Would it be possible that a memory corruption is happening and tampering struct [ftmn_check](https://elixir.bootlin.com/op-tee/3.21.0/source/lib/libutils/ext/include/fault_mitigation.h#L72), whichhhhhh stores the expected call result ? 

I've tried enabling `CFG_TEE_TA_MALLOC_DEBUG`, `CFG_TEE_CORE_MALLOC_DEBUG` and adding some `mdbg_check(1)` calls but it did not helped.

Any suggestions ?

Thank you,
Vitor

**Comment by vsatoes** [comment]
Some updates:

The caller of ‘FTMN_CALLEE_DONE_CHECK()’ which causes the panic in the OPTEE this one[ https://elixir.bootlin.com/op-tee/3.21.0/source/core/lib/libtomcrypt/src/pk/rsa/rsa_verify_hash.c#L194](https://elixir.bootlin.com/op-tee/3.21.0/source/core/lib/libtomcrypt/src/pk/rsa/rsa_verify_hash.c#L194).
 
This situation is created when `ftmn_set_check_res_memcmp()` is called  in:
```
if ((reallen == outlen) &&
          (digestinfo[0].size == hash_descriptor[hash_idx]->OIDlen) &&
        (XMEMCMP(digestinfo[0].data, hash_descriptor[hash_idx]->OID, sizeof(unsigned long) * hash_descriptor[hash_idx]->OIDlen) == 0) &&
          (siginfo[1].size == hashlen) &&
        (ftmn_set_check_res_memcmp(&ftmn, FTMN_INCR1, XMEMCMP,
				   siginfo[1].data, hash, hashlen) == 0)) {
         *stat = 1;
      }
```

Since VTS test uses a corrupted message to verify RSA, `siginfo[1].data` and `hash` does't match, which causes the following call to my_memcmp to return a value different from 0:
```
static inline int ftmn_set_check_res_memcmp(struct ftmn *ftmn,
					    enum ftmn_incr incr,
					    ftmn_memcmp_t my_memcmp,
					    const void *p1, const void *p2,
					    size_t nb)
{
	int res = my_memcmp(p1, p2, nb);

	if (IS_ENABLED(CFG_FAULT_MITIGATION))
		___ftmn_set_check_res_memcmp(&ftmn->check, incr, res,
					     my_memcmp, p1, p2, nb);

	return res;
}

```
This value is then stored in `ftmn.check.res` and later the function `FTMN_CALLEE_DONE_CHECK()` checks it against the value `!*stat` and since they don’t match will cause an OPTEE panic. 

I'm wondering if a hash mismatch should cause a panic or only issue an error and gracefully exit.

One possible approach would be to not set the `ftmn.check.res` as the return of `my_memcmp` if comparison fails, since `stat=0` would already indicate and invalid operation.

Any other suggestions ?

Thank you,
Vitor

**Comment by jforissier** [comment]
> I'm wondering if a hash mismatch should cause a panic or only issue an error and gracefully exit.

No, clearly not. The "fault mitigation" framework is supposed to cause a TEE core panic only when the software is being attacked, that is, when the control flow has been modified. No panic should happen as a result of runtime input (valid or not).

Could you propose a pull request with the change you have in mind? Thanks!

**Comment by vsatoes** [comment]
Thanks @jforissier 

I opened a PR: https://github.com/OP-TEE/optee_os/pull/6202

**Comment by jenswi-linaro** [comment]
It would be great with a test case in xtest too, to make sure that this error doesn't resurface by mistake. It would also make it easier for me to check that we're doing the right thing.
