### ISSUE TITLE
Can't boot on hikey

### ISSUE THREAD

**Issue by fanguannan0706** [OP-TEE/optee_os#620]
Hi,
I get the latest source and toolchains, then I compile the source and flash it to the hikey, and it seems completed. but when I boot the board, it always stop at the same step and can't continue, like this:
![583348898107515877](https://cloud.githubusercontent.com/assets/9778175/12370394/4d468062-bc4a-11e5-93e3-663c2414ab1c.jpg)
I don't why because I don't change anything. ps: the board is lemaker version.

**Comment by vchong** [comment]
If you're using op-tee/build, in hikey.mk, try changing below from 3 to 0 and compile again.

CFG_NW_CONSOLE_UART ?= 3
CFG_SW_CONSOLE_UART ?= 3

If you're just building optee_os, add below flag to make command:
CFG_CONSOLE_UART=0

**Comment by vchong** [comment]
Or if you're already on UART3, check your /etc/inittab in your initramfs. Make sure ttyAMA3 is enabled.

**Comment by fanguannan0706** [comment]
Ok, it can work now, thank you!

**Comment by Hackhao** [comment]
Hi,
I encountered the same problem. I followed the above approach, my problem is still not resolved.
Did you do any other operations?Looking forward to your reply！
