### ISSUE TITLE
 Check the code coverage of the driver code

### ISSUE THREAD

**Issue by ZijjWang** [OP-TEE/optee_os#6206]
Hi,
  Can I add the -fprofile-arcs -ftest-coverage compilation option to optee's driver to check the code coverage of the driver code? If I can, where should I add it?

Thanks.

**Comment by jenswi-linaro** [comment]
This seems to be a Linux kernel question rather than an OP-TEE question, even if you're looking at the OP-TEE driver in the kernel. Perhaps you can get better help in some Linux forum.

**Comment by ZijjWang** [comment]
OK，thank you！
