### ISSUE TITLE
Using Libtomcrypt in Optee

### ISSUE THREAD

**Issue by aminusamine** [OP-TEE/optee_os#621]
Hello,

How we can define libtomcrypt as the default cryptographic library (if it isn't by default) ?

And how to access to some functions, like fortuna PRNGs in the Secure World ?

Thank you,

Best Regards.

**Comment by jbech-linaro** [comment]
Hi @aminusamine ,

You will most likely find your answers here:
https://github.com/OP-TEE/optee_os/blob/master/documentation/crypto.md

And if you're not familiar with the GP APIs that the TA uses, then you also need to study the specification called "TEE Internal Core API Specification v1.1 | GPD_SPE_010" that could be found here:
http://globalplatform.org/specificationsdevice.asp

LibTomCrypt is the default crypto library in OP-TEE (and enabled in default builds).

// Joakim

**Comment by aminusamine** [comment]
Thank you, but i read the  "TEE Internal Core API Specification v1.1 | GPD_SPE_010"  but i want for example to reseed the PRNG, this function is included in optee_os/core/lib/libtomcrypt/src/prngs/fortuna.c, but i don't know how to call it from a TA. In the specification, there is no reference to these functions.

**Comment by aminusamine** [comment]
Hi @jbech-linaro , 

I want to execute some operations not existing in the Internal API. For example, there is in the libtomcrypt a function to generate randomly a sequence of bits called fortuna which i cannot get to. 

Can you explain me how to access this function and the libtomcrypt function not added to the internal library.

Thank you.

**Comment by pascal-brand-st-dev** [comment]
Libtomcrypt functions cannot be accessed directly by the TA. If you need to access specific functionalities not part of the GP API, you may develop your own "static TA", which is part of the core, and which can accessed any function of the core. Current static TAs can be found in https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/sta

Please close this issue if it answers.

**Comment by pascal-brand-st-dev** [comment]
@aminusamine Could you close this issue if it answers

**Comment by aminusamine** [comment]
Last question before closing the issue. If i understand well your answer, if i write a static TA with the functionalities i want, i can access them from a "normal" TA ? what do you mean by accessed by any function of the core ?

**Comment by pascal-brand-st-dev** [comment]
if i write a static TA with the functionalities i want,
    i can access them from a "normal" TA

Yes.

    what do you mean by accessed by any function of the core ?

Sorry for my english. I did not mean "accessed", but "access". Your static TA can then directly call any function of the core, including libtomcrypt internal functions.

Please close this issue if it answers
