### ISSUE TITLE
Linux Kernel Hanged when RAM gone to around 85 %. Either TEE or TA Crash/

### ISSUE THREAD

**Issue by dksgahlot** [OP-TEE/optee_os#6210]
E/TC:? 0 tee_ta_open_session:728 Failed. Return error 0xffff000f

Output of xtest: 
TEE test application started with device [(null)]
######################################################
#
# regression
#
######################################################

* regression_1001 Core self tests
  regression_1001 OK

* regression_1002 PTA parameters
  regression_1002 OK

* regression_1003 Core internal read/write mutex
    Number of parallel threads: 6 (2 writers and 4 readers)
    Max read concurrency: 2
    Max read waiters: 1
    Mean read concurrency: 1.325
    Mean read waiting: 1
  regression_1003 OK

* regression_1004 Test User Crypt TA
o regression_1004.1 AES encrypt
  regression_1004.1 OK
o regression_1004.2 AES decrypt
  regression_1004.2 OK
o regression_1004.3 SHA-256 test, 3 bytes input
  regression_1004.3 OK
o regression_1004.4 AES-256 ECB encrypt (32B, fixed key)
  regression_1004.4 OK
o regression_1004.5 AES-256 ECB decrypt (32B, fixed key)
  regression_1004.5 OK
  regression_1004 OK

* regression_1005 Many sessions
  regression_1005 OK

* regression_1006 Test Basic OS features
  regression_1006 OK

* regression_1007 Test Panic
E/TC:? 0 
E/TC:? 0 TA panicked with code 0xbeef
E/LD:  Status of TA 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b
E/LD:   arch: arm
E/LD:  region  0: va 0x00102000 pa 0xbdc30000 size 0x002000 flags rw-s (ldelf)
E/LD:  region  1: va 0x00104000 pa 0xbdc32000 size 0x005000 flags r-xs (ldelf)
E/LD:  region  2: va 0x00109000 pa 0xbdc37000 size 0x001000 flags rw-s (ldelf)
E/LD:  region  3: va 0x0010a000 pa 0xbdc38000 size 0x003000 flags rw-s (ldelf)
E/LD:  region  4: va 0x0010d000 pa 0xbdc3b000 size 0x001000 flags r--s
E/LD:  region  5: va 0x0010e000 pa 0x00001000 size 0x00c000 flags r-xs [0]
E/LD:  region  6: va 0x0011a000 pa 0x0000d000 size 0x0e5000 flags rw-s [0]
E/LD:  region  7: va 0x001ff000 pa 0xbdd2d000 size 0x003000 flags rw-s (stack)
E/LD:  region  8: va 0x00202000 pa 0x00000000 size 0x002000 flags r-xs [1]
E/LD:  region  9: va 0x00204000 pa 0x00001000 size 0x002000 flags rw-s [1]
E/LD:   [0] 5b9e0e40-2636-11e1-ad9e-0002a5d5c51b @ 0x0010e000
E/LD:   [1] ffd2bded-ab7d-4988-95ee-e4962fff7154 @ 0x00202000
E/LD:  Call stack:
E/LD:   0x00202e28
E/LD:   0x0010eccd
E/LD:   0x00112795
E/LD:   0x00116bc5
E/LD:   0x0010f448
  regression_1007 OK

**Comment by dksgahlot** [comment]
D/TC:0 0 abort_handler:524 [abort] abort in User mode (TA will panic)
E/TC:? 0 
E/TC:? 0 User TA undef-abort at address 0x1078a6
E/TC:? 0  fsr 0x00000000  ttbr0 0xbdb66059  ttbr1 0xbdb5c059  cidr 0x4
E/TC:? 0  cpu #0          cpsr 0x40000130
E/TC:? 0  r0 0x00000002      r4 0x00000000    r8 0x00000073   r12 0x00103f80
E/TC:? 0  r1 0x00000000      r5 0x00103e28    r9 0x00000000    sp 0x00103d50
E/TC:? 0  r2 0x001079be      r6 0x00000000   r10 0x001079bc    lr 0x00107019
E/TC:? 0  r3 0x001079bf      r7 0x00000000   r11 0x00103e2a    pc 0x001078a6
E/TC:? 0  region  0: va 0x00100000 pa 0xbdb00000 size 0x001000 flags ---R-X
E/TC:? 0  region  1: va 0x00102000 pa 0xbdc30000 size 0x002000 flags rw-RW-
E/TC:? 0  region  2: va 0x00104000 pa 0xbdc32000 size 0x005000 flags r-x---
E/TC:? 0  region  3: va 0x00109000 pa 0xbdc37000 size 0x001000 flags rw-RW-
**E/TC:? 0 init_with_ldelf:225 ldelf panicked**
D/TC:? 0 tee_ta_close_session:499 csess 0xbdb592b8 id 2
D/TC:? 0 tee_ta_close_session:518 Destroy session
D/TC:? 0 destroy_context:298 Destroy TA ctx (0xbdb59278)
E/TC:? 0 tee_ta_open_session:728 Failed. Return error 0xffff0000


When RAM consumption goes to around 85%. These types of logs are coming.

**Comment by jenswi-linaro** [comment]
The last error looks like potential memory corruption. Perhaps you're mapping non-secure memory and the kernel is using that memory at the same time. Running TAs from non-secure memory is not secure, but may make sense on a development platform. However, you must then make sure that the normal world (Linux kernel) doesn't use that memory at the same time.
