### ISSUE TITLE
riscv on spike platform build failure

### ISSUE THREAD

**Issue by lubing521** [OP-TEE/optee_os#6213]
Hi all,
    I get the newlest optee os code to compile it  ,but failure.build command as below: 
```
make ARCH=riscv PLATFORM=spike CROSS_COMPILE64=riscv64-unknown-linux-gnu- ta-targets=ta_rv64
```
    output the error information show as below:
   ``` lubing@lubing-VirtualBox:~/work/riscv/org_optee/optee_os$ make ARCH=riscv PLATFORM=spike CROSS_COMPILE64=riscv64-unknown-linux-gnu- ta-targets=ta_rv64
  CHK     out/riscv-plat-spike/conf.mk
  UPD     out/riscv-plat-spike/conf.mk
  CHK     out/riscv-plat-spike/include/generated/conf.h
  AS      out/riscv-plat-spike/core/arch/riscv/kernel/cache_helpers_rv.o
  CC      out/riscv-plat-spike/core/arch/riscv/kernel/idle.o
  CC      out/riscv-plat-spike/core/arch/riscv/kernel/tee_time_rdtime.o
In file included from core/arch/riscv/kernel/tee_time_rdtime.c:6:
core/arch/riscv/include/kernel/clint.h: In function 'clint_ipi_send':
core/arch/riscv/include/kernel/clint.h:17:27: error: 'CLINT_BASE' undeclared (first use in this function)
   17 | #define CLINT_MSIP(hart) (CLINT_BASE + (4 * (hart)))
      |                           ^~~~~~~~~~
core/arch/riscv/include/kernel/clint.h:26:20: note: in expansion of macro 'CLINT_MSIP'
   26 |         io_write32(CLINT_MSIP(hart), 1);
      |                    ^~~~~~~~~~
core/arch/riscv/include/kernel/clint.h:17:27: note: each undeclared identifier is reported only once for each function it appears in
   17 | #define CLINT_MSIP(hart) (CLINT_BASE + (4 * (hart)))
      |                           ^~~~~~~~~~
core/arch/riscv/include/kernel/clint.h:26:20: note: in expansion of macro 'CLINT_MSIP'
   26 |         io_write32(CLINT_MSIP(hart), 1);
      |                    ^~~~~~~~~~
core/arch/riscv/include/kernel/clint.h: In function 'clint_ipi_clear':
core/arch/riscv/include/kernel/clint.h:17:27: error: 'CLINT_BASE' undeclared (first use in this function)
   17 | #define CLINT_MSIP(hart) (CLINT_BASE + (4 * (hart)))
      |                           ^~~~~~~~~~
```
    I see CLINT_BASE only define on plat-virt,i think spike platform alos need support CLINT.
```
./core/arch/riscv/plat-virt/platform_config.h:23:#ifndef CLINT_BASE
./core/arch/riscv/plat-virt/platform_config.h:24:#define CLINT_BASE		0x02000000

```

**Comment by gagachang** [comment]
> I see CLINT_BASE only define on plat-virt,i think spike platform alos need support CLINT.

Yes, spike should also have the following definitions in `platform_config.h`

```
/* CLINT */
#ifndef CLINT_BASE
#define CLINT_BASE		0x02000000
#endif
```

**Comment by gagachang** [comment]
Hi @lubing521 

Please check PR https://github.com/OP-TEE/optee_os/pull/6275

**Comment by rscvtee** [comment]
> Hi @lubing521
> 
> Please check PR #6275

OK,  close this issue.

**Comment by lubing521** [comment]
> Hi @lubing521
> 
> Please check PR #6275

OK,close this issue. thanks!

**Comment by lubing521** [comment]
there are some issues  on spike platform also.

lubing@lubing-VirtualBox:~/work/tee/optee_os$ make ARCH=riscv PLATFORM=spike CROSS_COMPILE64=riscv64-unknown-linux-gnu- ta-targets=ta_rv64
  CHK     out/riscv-plat-spike/conf.mk
  UPD     out/riscv-plat-spike/conf.mk
  CHK     out/riscv-plat-spike/include/generated/conf.h
  CHK     out/riscv-plat-spike/core/include/generated/asm-defines.h
  UPD     out/riscv-plat-spike/core/.buildcount
  GEN     out/riscv-plat-spike/core/version.o
  LD      out/riscv-plat-spike/core/tee.elf
riscv64-unknown-linux-gnu-ld.bfd: out/riscv-plat-spike/core/arch/riscv/kernel/entry.o: in function `.L31':
(.identity_map+0x120): undefined reference to `mu_service'
riscv64-unknown-linux-gnu-ld.bfd: out/riscv-plat-spike/core/kernel/thread.o: in function `.L54':
thread.c:(.text.thread_init_threads+0x5c): undefined reference to `pgt_init'
riscv64-unknown-linux-gnu-ld.bfd: out/riscv-plat-spike/core/kernel/notif.o: in function `.L0 ':
notif.c:(.text.notif_wait+0x48): undefined reference to `thread_rpc_cmd'
riscv64-unknown-linux-gnu-ld.bfd: notif.c:(.text.notif_send_sync+0x48): undefined reference to `thread_rpc_cmd'
make: *** [core/arch/riscv/kernel/link.mk:106: out/riscv-plat-spike/core/tee.elf] Error 1
lubing@lubing-VirtualBox:~/work/tee/optee_os$
