### ISSUE TITLE
Ways to access other medias. (secure storage id & pkcs#11)

### ISSUE THREAD

**Issue by coach-bin** [OP-TEE/optee_os#6214]
I'm studying and planning about secure storage. I'm considering 3 other medias: trusted storage which optee provides, OTP memory, EEPROM (protected by trustzone)

In my case, would implementing fs_ops for OTP and EEPROM and adding storage_id for OTP and EEPROM to here be a good approach? compared to implementing other TAs for them (considering complexity, efficiency, etc..)
https://github.com/OP-TEE/optee_os/blob/69715ce97ef2ac050e62b882e33a1c2700000e96/core/include/tee/tee_fs.h#L77

It seems that pkcs#11 TA only supports TEE_STORAGE_PRIVATE. If I want to use the approach that I explained above, then I think it's not compatible with pkcs#11(because storage_id is fixed as TEE_STORAGE_PRIVATE). And If I want to use pkcs#11, then implementing other pTAs for OTP and EEPROM will be better approach. Is my understanding correct?
https://github.com/OP-TEE/optee_os/blob/69715ce97ef2ac050e62b882e33a1c2700000e96/ta/pkcs11/src/object.c#L257

Possible scenarios may be like the followings. Among these, I'd like to confirm the right way for me to go.
1. cryptoki -> pkcs#11 ta -> TEE internal core API with storage_id -> media (trusted storage/otp/eeprom)
2. cryptoki -> pkcs#11 ta -> TEE internal core API with storage_id -> media (trusted storage)
    TEE client API? -> other ta or pTA-> optee core driver -> otp/eeprom
3. TEE client API -> ta -> TEE internal core API with storage_id -> media (trusted storage/otp/eeprom)
4. TEE client API -> ta1 -> TEE internal core API with storage_id -> trusted storage
    TEE client API? -> ta2 or pTA -> optee core driver  -> otp/eeprom

**Comment by jenswi-linaro** [comment]
Especially the OTP storage will be very limited in size so for efficient usage of the little space you have you're probably better off with a special-purpose PTA. For the EEPROM I'm not sure how large it is and how you erase data. Likely you're better off with a special-purpose PTA here too.

I'm not an expert on the PKCS#11 TA, but surely it must be possible to extend it so you can use another storage solution for some objects. Anyway, I believe the communication pattern should be something like:
(cryptoki -> pkcs#11 ta) or (TEE client API -> ta) -> PTA -> ([optional layer] OP-TEE core driver ->) otp/eeprom.

**Comment by coach-bin** [comment]
1. PKCS#11
I checked more and I found that PKCS#11 can support both REE_FS and RPMB_FS. It only depends on CFG_REE_FS and CFG_RPMB_FS, even though pkcs#11 TA always call TEE_CreatePersistentObject() with TEE_STORAGE_PRIVATE. 

2. Adding other storage_id for OTP & EEPROM
The reason I'm worrying about adding another storage_id is that it only seems to support media that supports the file system. (at least, it requires extra efforts/resources to implement file system for them)  For example, if storage_id == TEE_STORAGE_PRIVATE, it returns ree_fs_ops.
https://github.com/OP-TEE/optee_os/blob/69715ce97ef2ac050e62b882e33a1c2700000e96/core/include/tee/tee_fs.h#L82

3. Is it worth using OTP/EEPROM compared to the trusted storage?
In my system, OTP/EEPROM is only accessible via secure world. That's why I considered OTP/EEPROM as a storage. (I think that trusted storage is a REE file system encrypted by SSK) But I want to be sure that this approach is good (most guys seem to be using a trusted storage, because it's enough?)

4. usages
My initial thought was that user application uses cryptoki(PKCS#11) library and it interfaces with pkcs#11 TA and it communicates to trusted storage/otp/eeprom. But if there is a huddle in adding storage_id for otp/eeprom, I think there are two options.
1) To have a dedicated CA & TA for otp/eeprom : user application uses both cryptoki library and a dedicated CA .
2) Not to use PKCS#11 and to have single CA & TA for trusted storage/otp/eeprom : to give up PKCS#11 benefits (provide an abstraction to access HSM - TPM,TEE,etc)
Is there another scenario that I can consider?

**Comment by jenswi-linaro** [comment]
> 3\. Is it worth using OTP/EEPROM compared to the trusted storage?

Yes, for some things like Hardware Unique Key, a hash of some public key, and so on. I'd say more for the need for OP-TEE Core than for TAs.

EEPROM might even be useful to implement a monotonic counter that could be used to protect secure storage instead of RPMB.

**Comment by coach-bin** [comment]
> EEPROM might even be useful to implement a monotonic counter that could be used to protect secure storage instead of RPMB.

Can you elaborate on this?  Are you assuming there is no medium that supports RPMB?  I think you're saying that I can use a trusted storage and I can implement a similar method like write counter of RPMB and can enhance a trusted storage. If I understood correctly, I wonder whether optee provides an interface where I can implement a monotonic counter or not.

**Comment by jenswi-linaro** [comment]
> > EEPROM might even be useful to implement a monotonic counter that could be used to protect secure storage instead of RPMB.
> 
> Can you elaborate on this? Are you assuming there is no medium that supports RPMB?

Yes, that's a possible configuration, and if so we need another way of doing rollback protection.

> I think you're saying that I can use a trusted storage and I can implement a similar method like write counter of RPMB and can enhance a trusted storage.

Yes, if RPMB is missing it would improve security if there's another way to protect against rollback.

> If I understood correctly, I wonder whether optee provides an interface where I can implement a monotonic counter or not.

We don't have such an interface, but it would make sense to add one if you can implement it. I can help with a stubbed implementation if you need some help to get started.

**Comment by coach-bin** [comment]
> We don't have such an interface, but it would make sense to add one if you can implement it. I can help with a stubbed implementation if you need some help to get started.

If you can help me, it would be great! Even though I'm in system design phase, checking it and if it's worth adding will  really help.

**Comment by jenswi-linaro** [comment]
I've added an RFC PR https://github.com/OP-TEE/optee_os/pull/6260, feedback is welcome.
