### ISSUE TITLE
Seeking Advice for Improving SHA256 Performance in TA

### ISSUE THREAD

**Issue by J-StrawHat** [OP-TEE/optee_os#6215]
I've been conducting performance measurements of the SHA256 function in both the CA using OpenSSL, and within a TA utilizing the built-in libtomcrypt library. I've observed a significant discrepancy in the execution time between the two environments, with the TA implementation proving to be much slower.

![](https://i.imgur.com/RZMwrsE.png)

Are there any suggestions for ways in which I could improve the efficiency of the SHA256 function within the TA? Are there any optimizations I could make, or is there an alternative library that may provide better performance?

**Comment by jenswi-linaro** [comment]
Are you building with `CFG_CRYPTO_SHA256_ARM_CE=y`?

**Comment by J-StrawHat** [comment]
Yes, in addition, I also enable the -O3 option in TA. However, the execution time difference measured by `gettimeofday()` of `<sys/time.h>` does not change significantly.

**Comment by J-StrawHat** [comment]
This is the SHA256 function I defined in TA
```c
static TEE_Result sha256(void* session, uint32_t param_types, TEE_Param params[4])
{
    TEE_Result res;
    struct my_session* sess = (struct my_session*)session;

    char* inputDataBuffer = params[0].memref.buffer;
    char* hashListOutBuffer = params[1].memref.buffer;
    uint32_t inputDataLen = params[0].memref.size;
    uint32_t hashListOutLen = params[1].memref.size;

    res = TEE_AllocateOperation(&sess->op_handle, TEE_ALG_SHA256, TEE_MODE_DIGEST, 0);
    ...
    TEE_DigestUpdate(sess->op_handle, inputDataBuffer, inputDataLen);
    res = TEE_DigestDoFinal(sess->op_handle, NULL, 0, hashListOutBuffer, &hashListOutLen);
    ...
    TEE_FreeOperation(sess->op_handle);
    return TEE_SUCCESS;
}
```

**Comment by jforissier** [comment]
> Yes, in addition, I also enable the -O3 option in TA. However, the execution time difference measured by `gettimeofday()` of `<sys/time.h>` does not change significantly.

The crypto code is in the TEE core so the TA flags do not apply. You can try `CFG_CC_OPT_LEVEL=3` but I doubt it will change the performance significantly.

**Comment by J-StrawHat** [comment]
Well, there is no big change in performance. Are there any possible ways to further improve performance? Is it feasible to replace other cryptographic libraries?

**Comment by J-StrawHat** [comment]
Thank you very much for your advice, I found that replacing LibTomCrypt with MBedTLS became much faster.
I will use the ftrace framework to further analyze the log of function calls
