### ISSUE TITLE
Dynamic TA Heap Allocation

### ISSUE THREAD

**Issue by Yuri-Loarc** [OP-TEE/optee_os#6218]
We're trying to resolve out of memory issue is optee-os.
Here is situation, some TA running multiple platform with same binary. 
Usually It requires less than 8kb heap memory however in some case It over 8kb and need more.
Of cause it can easily resolve with change 'TA_DATA_SIZE' with maximum value. I feel like it's wasting memory is usual cases.

So right now, I consider that enhancing TEE_Malloc(), If there is no sufficient memory in TA pool, request next poll using separate system call and like 'ldelf_syscall_map_zi' and allocate it.
Of cause it should be checked overall memory is less than 'gpd.ta.dataSize' in property.

What I really want to know is there any reason of current optee-os design , decide TA heap size in build time and use it. likewise simplicity, security or performance

Thanks,

**Comment by jenswi-linaro** [comment]
> What I really want to know is there any reason of current optee-os design , decide TA heap size in build time and use it. likewise simplicity, security or performance

Simplicity, it was the easiest way to do it.

> So right now, I consider that enhancing TEE_Malloc(), If there is no sufficient memory in TA pool, request next poll using separate system call and like 'ldelf_syscall_map_zi' and allocate it.
> Of cause it should be checked overall memory is less than 'gpd.ta.dataSize' in property.

Makes sense, but we may cause some fragmentation of physical TA memory with this. If that becomes a problem then we'd need to find a way to use physically discontiguous memory when mapping TA memory.

**Comment by Yuri-Loarc** [comment]
@jenswi-linaro 
Thanks we'll consider your comment when improving this feature.

**Comment by Yuri-Loarc** [comment]
@jenswi-linaro
Thanks we'll consider your comment when improving this feature.
