### ISSUE TITLE
Does OPTEE plan to add X448 support using libtomcrypt as the backend crypto implementation？

### ISSUE THREAD

**Issue by loubaihui** [OP-TEE/optee_os#6220]
Hi, experts,
Does OPTEE plan to add support for X448 using libtomcrypt as the backend crypto implementation?

**Comment by jbech-linaro** [comment]
Hi @loubaihui ,

Haven't been discussed, hence no such plans for now. But whenever we see a valid use case for something, we're typically open for adding support for it.

**Comment by loubaihui** [comment]
OK，thank you.
