### ISSUE TITLE
Run Optee on Morello Kernel

### ISSUE THREAD

**Issue by engMennaMahmoud** [OP-TEE/optee_os#6222]
Hi all,

I tried to run optee on Morello kernel but when running `xtest` command, it failed. any idea please?

I tried to write what I did, you can full steps here: https://github.com/engMennaMahmoud/Morello-Kernel-Project/wiki/How-to-enable-OPTEE-in-Morello-kernel

Thanks in advance

**Comment by jenswi-linaro** [comment]
Does this relate to https://github.com/OP-TEE/optee_os/issues/6244 by any chance?

**Comment by engMennaMahmoud** [comment]
> Does this relate to #6244 by any chance?

yes, I will close this issue. 

Thanks
