### ISSUE TITLE
does a context-switch pause other cores?

### ISSUE THREAD

**Issue by TheFrozenDuck** [OP-TEE/optee_os#6223]
I stumbled upon a question that I could not answer myself using the documentation:

When a switch on a multi-core setup, such as the Hikey960 happens, does the complete system make a context switch or only a single core?

An entry in Arm's forum [1] suggests that normally the execution on other core's is not paused.

[1] https://community.arm.com/support-forums/f/dev-platforms-forum/140/how-does-the-secure-world-work-with-multicore-system

**Comment by jforissier** [comment]
Context switching is a per-core thing, it doesn't pause execution on other cores.

**Comment by TheFrozenDuck** [comment]
Thank you for clearing that up. I kinda expected it with the normal world logs continuing but I was unsure if that isn't the buffer not being fast enough writing out everything.
