### ISSUE TITLE
In SPMC EL2，Does OP-TEE OS support parsing of memory&device regions logic?

### ISSUE THREAD

**Issue by LeiSen62** [OP-TEE/optee_os#6238]
Hi，Currently, the OP-TEE OS parses only load-address and mem-size of the manifest file. Can the logic for parsing memory&device regions be added?

**Comment by jenswi-linaro** [comment]
Sure. What do you have in mind?

**Comment by LeiSen62** [comment]
I have a patch to parse memory&device regions, and I will be submitting a PR shortly.
