### ISSUE TITLE
RFC: pta: imx: manufacturing_protection: should we add an optee client interface

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#6241]
Having an interface via optee_client would simplify the integration of this platform specific feature.  

Should we add a libteehwpta to optee_client to try to cover for these use cases? 
I can propose something for discussion unless it has been considered before and perhaps dropped (hence why I am asking)

thanks!

**Comment by jenswi-linaro** [comment]
Sure, it makes sense to me. I would suggest putting it in `libptateec` with the possibility of adding more PTA wrappers as needed in the future. PTAs exposed like this must provide a stable ABI and be available in upstream OP-TEE OS.

**Comment by ldts** [comment]
@jenswi-linaro I submited https://github.com/OP-TEE/optee_client/pull/352

I will require a change in the PTA though as the session can not be open unless we get rid of this restriction
https://github.com/OP-TEE/optee_os/blob/master/core/pta/imx/manufacturing_protection.c#L92

@clementfaure would there be an issue doing this change? ie, removing the open_session method in the PTA? I  don't understand why this is required, could you maybe explain a bit?

**Comment by jenswi-linaro** [comment]
Does it have any security implications?

**Comment by clementfaure** [comment]
I will double-check if there is any concerns regarding the 'sign' function.

**Comment by ldts** [comment]
@clementfaure what is the TA using the manufacturing protection PTA? do you have some documentation on it?
Just wondering why this key was not integrated in a way that it is reachable from pkcs#11 to be used for mTLS.

**Comment by clementfaure** [comment]
@ldts I don't have any views on potential TA/TAs using the MP PTA.
The MP PTA has been around for quite some time now but only upstreamed recently. The original requirement at first was to expose CAAM MP capabilities to TAs, that's it.

Regarding the potential security threat of exposing MP capabilities to non-secure. For the public key export : no problem. For the sign operation : it depends on your architecture ; if you want your signed message to come from a trusted source (like a TA) or from an untrusted source (non-secure). By exposing the MP sign operation to the non-secure, the OEM server won't be able to tell if the message originates from the secure or non-secure. That could be totally fine or could not fit with some designs.

**Comment by clementfaure** [comment]
That would be preferable ; the restrictive option enabled by default and a flag to enable to expose MP features to the non-secure

**Comment by ldts** [comment]
https://github.com/OP-TEE/optee_os/pull/6274
