### ISSUE TITLE
xtest failed on fvp and morello

### ISSUE THREAD

**Issue by engMennaMahmoud** [OP-TEE/optee_os#6244]
Hi all,

I tried to run Optee on the Morello platform, I succeeded in running the Morello kernel but got the below errors

![Screenshot from 2023-08-17 21-01-03](https://github.com/OP-TEE/optee_os/assets/135363693/d65bfa32-eb00-4b8c-950c-f8903dc8da6f)

I followed these steps: https://engmennamahmoud.github.io/How-to-enable-OPTEE-in-Morello-kernel

Could you please help me?

**Comment by ichergui** [comment]
Hey @engMennaMahmoud 
It looks like the TEE driver is not enable. 
Please check with 'dmesg | grep -i "optee"'
And share the result.

**Comment by engMennaMahmoud** [comment]
Hi @ichergui 

Thanks for your reply, I got nothing
![Screenshot from 2023-08-17 22-50-57](https://github.com/OP-TEE/optee_os/assets/135363693/1d9b4bc7-0921-47d5-ae15-eee6f9754f37)

**Comment by ichergui** [comment]
Please check your `.config` file in the kernel Linux build directory and the device tree.
You can be base on the following link regarding the device tree.
```
https://www.kernel.org/doc/Documentation/devicetree/bindings/arm/firmware/linaro%2Coptee-tz.txt
```

**Comment by engMennaMahmoud** [comment]
Thanks, @ichergui, I have checked the `.config` file and will check the device tree.
