### ISSUE TITLE
riscv on qemu platform build failure

### ISSUE THREAD

**Issue by JESSIY225** [OP-TEE/optee_os#6245]
Hi all,
I get the newlest optee os code to compile it ,but failure.build command as below:

make ARCH=riscv PLATFORM=virt CROSS_COMPILE64=riscv64-unknown-linux-gnu- ta-targets=ta_rv64

output the error information show as below:

make[1]: Entering directory '/home/b105/optee/optee_os'
  CHK     out/riscv/conf.mk
  CHK     out/riscv/include/generated/conf.h
  AS      out/riscv/core/arch/riscv/kernel/thread_rv.o
core/arch/riscv/kernel/thread_rv.S: Assembler messages:
core/arch/riscv/kernel/thread_rv.S:294: Error: illegal operands `li a0,TEESMC_OPTEED_RETURN_CALL_DONE'
core/arch/riscv/kernel/thread_rv.S:359: Error: illegal operands `li a0,TEESMC_OPTEED_RETURN_CALL_DONE'
mk/compile.mk:165: recipe for target 'out/riscv/core/arch/riscv/kernel/thread_rv.o' failed
make[1]: *** [out/riscv/core/arch/riscv/kernel/thread_rv.o] Error 1
make[1]: Leaving directory '/home/b105/optee/optee_os'
common.mk:534: recipe for target 'optee-os-common' failed

**Comment by gagachang** [comment]
Since that SBI interface has not been implemented yet, the build errors are expected.
