### ISSUE TITLE
Call the TA during boot before tee_supplicant loading

### ISSUE THREAD

**Issue by fengyuanyu1** [OP-TEE/optee_os#6247]
Hello, optee teams. Can I call the Early TA after normal world boots but before the tee_supplicant loads. I try to search the corresponding issues as follows:
#5435 
#4729
I can use the `make ... EARLY_TA_PATHS=` to convert the user TA to early TA, so that I can call the early TA before the normal world starts. I can call it in u-boot environment, u-boot has the  optee driver to support calling. But can I call it without the driver? For example, when the system jump into the boot of linux kernel without loading the optee driver? I think it is possible but there are no API provided for us to do this. Maybe I need to write some assembly like `SMC` to do this? Is it correct?
Thanks for your attention and reply.

**Comment by jforissier** [comment]
> Maybe I need to write some assembly like SMC to do this? Is it correct?

Yes, but you will end up re-writing the optee driver more or less. SMC has to be issued in kernel mode so you need a driver, there is no way around that.

**Comment by fengyuanyu1** [comment]
Thanks for your reply.
