### ISSUE TITLE
TEEC_Context usage

### ISSUE THREAD

**Issue by profit-of-doom** [OP-TEE/optee_os#6248]
I have some questions regarding when/if multiple TEEC_Context objects should be used:

Q1. As I understand things, if a single TEE is present, a CA requires only a single TEEC_Context instance, regardless of how many TA sessions are opened? Is this correct?

Q2. Is this still true if the TAs are heterogeneous? For example: TA1 provides DRM, TA2 provides user auth.

Q3. If the answer to Q1 is yes: Assume that a single TEEC_Context instance is initialised during CA start. If TA sessions are then opened on multiple threads, does the CA need to provide mutex protection for the TEEC_Context instance, or is this handled by TEEC?

Q4. From the resource management perspective, it is simpler to initialise a new TEEC_Context instance per thread. The GlobalPlatform Client API permits this. Other than resource usage, are there any drawbacks to this approach?

**Comment by jforissier** [comment]
Hi @profit-of-doom,

> I have some questions regarding when/if multiple TEEC_Context objects should be used:
> 
> Q1. As I understand things, if a single TEE is present, a CA requires only a single TEEC_Context instance, regardless of how many TA sessions are opened? Is this correct?

Yes.

> Q2. Is this still true if the TAs are heterogeneous? For example: TA1 provides DRM, TA2 provides user auth.

Yes.

> Q3. If the answer to Q1 is yes: Assume that a single TEEC_Context instance is initialised during CA start. If TA sessions are then opened on multiple threads, does the CA need to provide mutex protection for the TEEC_Context instance, or is this handled by TEEC?

No mutex protection should be needed.

> Q4. From the resource management perspective, it is simpler to initialise a new TEEC_Context instance per thread. The GlobalPlatform Client API permits this. Other than resource usage, are there any drawbacks to this approach?

Not that I can think of.

**Comment by profit-of-doom** [comment]
Thanks @jforissier!
