### ISSUE TITLE
Using TEE_OpenPersistentObject to open Object in another TA.

### ISSUE THREAD

**Issue by Dark-Sphere** [OP-TEE/optee_os#6251]
Hello, 
I want to create a TA (lets call it TA1), which generates a secret key and stores it securely as a persistent object. This it seems I have done successfully.

Now i want to have another TA (lets call it TA2), which is able to read this persistent object. When I try to use TEE_OpenPersistentObject I recieve an TEE_ERROR_ITEM_NOT_FOUND, eventhough I used the same ObjectId as in TA1. Therefore my question is, if it is even possible to open the persistent object created in TA1 from the TA2. 

I am using a QUEMU V8 build with the branch 3.22.0. 

Thanks for any help.

**Comment by jenswi-linaro** [comment]
> Therefore my question is, if it is even possible to open the persistent object created in TA1 from the TA2.

No, that's not permitted.

**Comment by jenswi-linaro** [comment]
I guess you could generate the key in TA1, serialize it into some binary format, and call TA2 with that binary blob as an argument.

**Comment by Dark-Sphere** [comment]
> I guess you could generate the key in TA1, serialize it into some binary format, and call TA2 with that binary blob as an argument.

I made a workaround were everything is in one TA. This seems to work for now. 
Thanks for the help.
