### ISSUE TITLE
Building OPTEE-OS with Kernel ASAN.

### ISSUE THREAD

**Issue by Abhishek-612** [OP-TEE/optee_os#6252]
I am trying to build OPTEE-OS with the kernel address sanitizer on qemu_armv8. 
I am using `CFG_ASAN_SHADOW_OFFSET=0xc6a71c0` as given in `conf.mk` in `plat_vexpress`.

After building, the initial secure world logs show a kernel panic triggered from the `check_access()` function in `asan.c`, which checks the virtual address to shadow mapping. As per my understanding, the panic is triggered due to some out-of-bounds memory access.

**Secure World Logs:**
```
E/TC:0 0 Panic at core/kernel/asan.c:189 <check_access>
E/TC:0 0 TEE load address @ 0xe100000
E/TC:0 0 Call stack:
E/TC:0 0  0x0e109c70
E/TC:0 0  0x0e11d25c
E/TC:0 0  0x0e117ac0
E/TC:0 0  0x0e10391c
E/TC:0 0  0x0e183460
E/TC:0 0  0x0e18357c
E/TC:0 0  0x0e12b068
E/TC:0 0  0x0e12bb78
E/TC:0 0  0x0e10958c
```

**asan.c code snippet (lines 186-190):**
```
	e = va_to_shadow((void *)(addr + size - 1));
	for (a = va_to_shadow(begin); a <= e; a++) {
		if (*a < 0)
			panic();
	}
```

I would like to know:
1. What exactly could be triggering this panic in the default implementation? 
2. Is this a configuration issue? If yes, then which particular config constants require change?
3. How can I inject `DMSG` logs in `asan.c`, to identify which address causes the panic?
4. Is there any detailed documentation / steps for OPTEE build with Kernel ASAN?

Do let me know if you need additional information.

**Comment by jenswi-linaro** [comment]
`CFG_CORE_SANITIZE_KADDRESS=y` isn't supported (yet) with the `qemu_armv8a` platform flavor.
When trying to enable it for that flavor you should expect to sort out some smaller problems at least.
I'd recommend starting with the `qemu_virt` (v7) platform flavor, just to see that things work as expected.

To debug these things on QEMU I'd expect gdb to be much more useful than DMSG since walking up the stack should point out the problem accurately. You could also try to feed that panic to ./scripts/symbolize.py.

I'm afraid we don't have much more documentation on CFG_CORE_SANITIZE_KADDRESS than what you find in the code and `.mk` files.

**Comment by jforissier** [comment]
> `CFG_CORE_SANITIZE_KADDRESS=y` isn't supported (yet) with the `qemu_armv8a` platform flavor.
> When trying to enable it for that flavor you should expect to sort out some smaller problems at least.

Indeed. I have a few fixes for that, I got KASAN working with ASLR disabled but I am trying to figure out a crash with ASLR turned on.

**Comment by Abhishek-612** [comment]
As a matter of fact, I followed #6253 , and disabled `CFG_CORE_ASLR`. I still end up with the same panic call. 

@jforissier would you be able to help me with any other configuration adjustments that might be necessary for the armv8a built?

Below are the modifications I made so far in the `config.mk` file:
- `CFG_CORE_ASLR ?= n`
- `CFG_CORE_SANITIZE_KADDRESS ?= y`
- `CFG_ASAN_SHADOW_OFFSET ?= 0xc6a71c0`

**Comment by jforissier** [comment]
Have you checked out the code in #6253?
```
optee_os$ git fetch github pull/6253/head && git checkout FETCH_HEAD
optee_os$ cd ../build
build$ make CFG_CORE_SANITIZE_KADDRESS=y CFG_CORE_ASLR=n run
```

**Comment by Abhishek-612** [comment]
#6253 code worked. Thanks a lot for the help!

Closing this issue.
