### ISSUE TITLE
TA paniks with Error Code 0xffff0001 (TEE_ERROR_ACCESS_DENIED) when trying to TEE_PopulateTransientObject

### ISSUE THREAD

**Issue by Dark-Sphere** [OP-TEE/optee_os#6254]
Hello toghether, 
I stumbled onto another problem. Like the titel says I want to TEE_PopulateTransientObject a Object which a allocated earlier. 
When I run the programm it returns me an Error Code 0xffff0001 (TEE_ERROR_ACCESS_DENIED). I tried to find the issue, but I am running out of ideas. 

I am using a QUEMU V8 build with the branch 3.22.0.

Thanks for any help in advance.

**Comment by jforissier** [comment]
> I tried to find the issue, but I am running out of ideas.

Not possible. You have the source code for everything, so you can enable traces and add some if needed.
