### ISSUE TITLE
Build failure when CFG_TEE_CORE_NB_CORE is 18 or 12

### ISSUE THREAD

**Issue by gowthamithiagu** [OP-TEE/optee_os#6255]
Building optee_os with either CFG_TEE_CORE_NB_CORE as 18 or 12 throws the below error.
We do have few platforms with core numbers as mentioned.

The error is thrown by these instructions

add     x0, x0, #CORE_MMU_BASE_TABLE_OFFSET
sub     x0, x0, #CORE_MMU_BASE_TABLE_OFFSET

from core/arch/arm/kernel/thread_a64.S

make PLATFORM=marvell-cnf10ka
core/arch/arm/kernel/thread_a64.S: Assembler messages:
core/arch/arm/kernel/thread_a64.S:339: Error: immediate out of range
core/arch/arm/kernel/thread_a64.S:347: Error: immediate out of range
core/arch/arm/kernel/thread_a64.S:355: Error: immediate out of range
core/arch/arm/kernel/thread_a64.S:372: Error: immediate out of range
core/arch/arm/kernel/thread_a64.S:379: Error: immediate out of range
core/arch/arm/kernel/thread_a64.S:386: Error: immediate out of range
core/arch/arm/kernel/thread_a64.S:660: Error: immediate out of range
core/arch/arm/kernel/thread_a64.S:732: Error: immediate out of range
make: *** [mk/compile.mk:165: out/core/arch/arm/kernel/thread_a64.o] Error 1

**Comment by jenswi-linaro** [comment]
The PR https://github.com/OP-TEE/optee_os/pull/6257 should take care of this error.

**Comment by gowthamithiagu** [comment]
Hi @jenswi-linaro,

Could you please check whether the proposed add_imm/sub_imm macro works if
CFG_TEE_CORE_NB_CORE is 12?
Looks like it still throws the same error .

Thanks,
Gowthami

**Comment by jenswi-linaro** [comment]
They work when CFG_TEE_CORE_NB_CORE is 12 or 18 when I'm testing. Are you sure you're testing with https://github.com/OP-TEE/optee_os/pull/6257 and https://github.com/OP-TEE/optee_os/pull/6227 only?

**Comment by gowthamithiagu** [comment]
Yes. For CFG_TEE_CORE_NB_CORE as 12, CORE_MMU_BASE_TABLE_OFFSET is 6144 and the macro expands to the same add instruction as before(causing the out of range error).

When CFG_TEE_CORE_NB_CORE is 24, the macro expands to 2 add instructions instead of 1.
add     x0, x0, #0x3, lsl #12
add     x0, x0, #0x1, lsl #12

Shouldn't the value checked in the macro be 0xfff instead of 0x1fff?

Kindly pass on your comments.

**Comment by jenswi-linaro** [comment]
> Shouldn't the value checked in the macro be 0xfff instead of 0x1fff?

Yes, I believe you're right. Does it work as expected with `0xfff` instead?

**Comment by gowthamithiagu** [comment]
Yes, I have tested it for few platforms. It's working as expected.

**Comment by gowthamithiagu** [comment]
> Great, thanks. I've updated the PR, would you mind giving feedback? And perhaps a Tested-by tag?

Sure.
