### ISSUE TITLE
Read public key components into TA

### ISSUE THREAD

**Issue by Dark-Sphere** [OP-TEE/optee_os#6259]
Hello,
I have given public key compontents in the user-space (modulus and public exponent), which I want to give to a TA via a Input Parameter. 
Since the necessary attributes for a object of TEE_TYPE_RSA_PUBLIC_KEY need the modulus in a BIGNUM format (according to the TEE_Internal_core_Api documentation and OP-TEE documentation). I wanted to ask if there exists any library or way to convert hex into the needed BIGNUM format or a library which can handle this format. 

Thanks for any help in advance.

**Comment by jforissier** [comment]
The expected format is big-endian binary, see table 6-16 in the GP spec. So you do not need any fancy conversion function.

**Comment by Dark-Sphere** [comment]
Ah well, that makes it easier. Thanks for the clarification and help.

**Comment by jforissier** [comment]
> Ah well, that makes it easier.

Indeed :wink: 

> Thanks for the clarification and help.

You're welcome.
