### ISSUE TITLE
Writing TEE_ObjectHandle Data in persistent object

### ISSUE THREAD

**Issue by Dark-Sphere** [OP-TEE/optee_os#6262]
Hello, 
I have a function which generates a aes key. Since I want to use this key in later states (when the TA is not running anymore), I wanted to put the key data in a persistent object. (Since the TEE_GenerateKey stores the data only in a transient object)
For this I allocated a persistent object  with the necessary infos.
![image](https://github.com/OP-TEE/optee_os/assets/60129774/36965675-577a-4621-9da0-d7d95fc12446)
![image](https://github.com/OP-TEE/optee_os/assets/60129774/d33dca50-7804-4d12-acb2-cf52aea85c7f)

I tried to write the data of the ObjectHandle into the persistent object like this: 
![image](https://github.com/OP-TEE/optee_os/assets/60129774/4e44bd7b-6280-4181-b809-7ffb396f80d7)

On one side my feeling tells me that this isn´t really going to work, on the other side I recieve wierd data, when printing out the key like this:
![image](https://github.com/OP-TEE/optee_os/assets/60129774/69a915c1-9b3f-4fb0-ac7d-f44cde598741)
![image](https://github.com/OP-TEE/optee_os/assets/60129774/6e9df7af-7653-4496-9374-4757f7ec7f13)
![image](https://github.com/OP-TEE/optee_os/assets/60129774/3ce73f10-2da5-4926-b68d-89377f3ff7d8)

How would I write the data of an TEE_ObjectHandle correct into a persistent object or is there a way to transform a transient object into a persistent object? (For the latter I did not find documentation, maybe I read over it.)

**Comment by jforissier** [comment]
Hi @Dark-Sphere 

> On one side my feeling tells me that this isn´t really going to work

Your feeling's right :wink: Please see the GP spec for `TEE_CreatePersistentObject()`, note the sentence: "To transform an initialized transient object into a persistent object, see the description of the object parameter following Table 5-13.". 
I would have copied and pasted the proper code here but since you used screen captures instead of text I am not bothering.

**Comment by Dark-Sphere** [comment]
Thanks for the information. Sorry for not posting text but screenshots. :( 
So if I understood it right I need to change:
res = TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE, obj_id, obj_id_sz,
                                         TEE_DATA_FLAG_ACCESS_READ | TEE_DATA_FLAG_ACCESS_WRITE | TEE_DATA_FLAG_OVERWRITE, 
                                         TEE_HANDLE_NULL,
                                         NULL, 0, &sec_storage);
to 
res = TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE, obj_id, obj_id_sz,
                                         TEE_DATA_FLAG_ACCESS_READ | TEE_DATA_FLAG_ACCESS_WRITE | TEE_DATA_FLAG_OVERWRITE, 
                                         key_handle,
                                         NULL, 0, &sec_storage);

Is this correct? 

Do I still need to TEE_WriteObjectData? How would I do this correctly? 
At the moment I dont see how the generated key material is passed.

**Comment by jforissier** [comment]
No, use:

```C
res = TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE, obj_id, obj_id_sz,
        TEE_DATA_FLAG_ACCESS_READ | TEE_DATA_FLAG_ACCESS_WRITE | TEE_DATA_FLAG_OVERWRITE,
        key_handle, NULL, 0, NULL);
```
Possibly you don't need `TEE_DATA_FLAG_ACCESS_{READ,WRITE}` (I'm not sure), and `TEE_DATA_FLAG_OVERWRITE` depends on your use case (what to do if the secure storage object already exists).

> Do I still need to TEE_WriteObjectData? How would I do this correctly?

No.

**Comment by Dark-Sphere** [comment]
Ah sorry, now I understand it, Makes sens to put NULL in the end. 
Sadly now the TEE_CreatePersistentObject panics with 0x0. 


> Possibly you don't need `TEE_DATA_FLAG_ACCESS_{READ,WRITE}` (I'm not sure), and `TEE_DATA_FLAG_OVERWRITE` depends on your use case (what to do if the secure storage object already exists).

Thanks for the explanation the `TEE_DATA_FLAG_OVERWRITE` is needed for my usecase :)

**Comment by jforissier** [comment]
> Ah sorry, now I understand it, Makes sens to put NULL in the end. Sadly now the TEE_CreatePersistentObject panics with 0x0. 

Hmmm we might have a bug here... try to pass `&sec_storage` instead of `NULL` as the last parameter:
```
res = TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE, obj_id, obj_id_sz,
        TEE_DATA_FLAG_ACCESS_READ | TEE_DATA_FLAG_ACCESS_WRITE | TEE_DATA_FLAG_OVERWRITE,
        key_handle, NULL, 0, &sec_storage);
```

**Comment by Dark-Sphere** [comment]
> See an example in: https://github.com/OP-TEE/optee_test/blob/3.22.0/ta/storage/storage.c#L474-L478 (that's `xtest 6013`).

Thanks for providing the example. I took a look at it and for me it seems like the only difference is the objectID so i changed it to the same way the are using it in the example. 
I still recieve the same error. 

```c
     IMSG("Trying to TEE_CreatePersistentObject!");
        result = TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE, &objectID, sizeof(objectID),
                                         TEE_DATA_FLAG_ACCESS_READ | TEE_DATA_FLAG_ACCESS_WRITE | TEE_DATA_FLAG_OVERWRITE, 
                                         key_handle,
                                         NULL, 0, NULL);
        if (result != TEE_SUCCESS)
        {
            DMSG("Issues with the persistent object! Error code: %#" PRIx32, result);
        }
        else
        {
            IMSG("Success creating persistent object! Object ID: %s", objectID);
        }
 ```
Now the only difference is the TEE_STORAGE_PRIVATE, but as far as I know/understand, this should not be the issue. 
Do I need to previously create the persistent object like in the xtest example? (That I dont get, since it gets closed and deleted anyways)
If yes can somebody explain this?

**Comment by Dark-Sphere** [comment]
I had another idea, that maybe my transient object isnt initialized. But I dont get why this would be the issue. As far as I know my code should be right or am I not seeing something? 

```c
IMSG("Trying to allocate transient object!");
result = TEE_AllocateTransientObject(TEE_TYPE_AES, key_bit_size, &transient_key);
if(result != TEE_SUCCESS)
{
 EMSG("Failed to allocate transient object handle: 0x%x!", result);
 return result; 
}
else
{
 IMSG("Success allocating transient object handle(0x%x, %" PRId32 "): 0x%x", 
 TEE_TYPE_AES, key_bit_size, result);
} 

IMSG("Trying to generate key!");
 result = TEE_GenerateKey(transient_key, key_bit_size, NULL, 0);
  if(result != TEE_SUCCESS)
  {
   EMSG("Failed to generate transient key: 0x%x!", result);
   TEE_FreeTransientObject(transient_key);
   return result;
}
else 
{   
 IMSG("Success generating key!");
}
 ```

**Comment by Dark-Sphere** [comment]
Thanks for the advice. I tired to execute the symbolo [scripts/symbolize.py](https://optee.readthedocs.io/en/latest/debug/abort_dumps.html) (hopefully correctly, somehow there are still questionsmarks ...). This lead to the following output: 
![image](https://github.com/OP-TEE/optee_os/assets/60129774/f05299bd-75ac-43a6-9d6c-33da53b64436)

So it seems to me the panic has to do something with Line 669 in optee_os/lib/libutee/tee_api_objects.c:669. 
So I diged there and saw this code: 
```c
TEE_Result TEE_CreatePersistentObject(uint32_t storageID, const void *objectID,
				      size_t objectIDLen, uint32_t flags,
				      TEE_ObjectHandle attributes,
				      const void *initialData,
				      size_t initialDataLen,
				      TEE_ObjectHandle *object)
{
	TEE_Result res = TEE_SUCCESS;
	uint32_t *obj_ptr = NULL;
	uint32_t obj = 0;

	if (object) {
		__utee_check_out_annotation(object, sizeof(*object));
		obj_ptr = &obj;
	}

	res = _utee_storage_obj_create(storageID, objectID, objectIDLen, flags,
				       (unsigned long)attributes, initialData,
				       initialDataLen, obj_ptr);

	if (res == TEE_SUCCESS && object)
		*object = (TEE_ObjectHandle)(uintptr_t)obj;

	if (res != TEE_SUCCESS &&
	    res != TEE_ERROR_ITEM_NOT_FOUND &&
	    res != TEE_ERROR_ACCESS_CONFLICT &&
	    res != TEE_ERROR_OUT_OF_MEMORY &&
	    res != TEE_ERROR_STORAGE_NO_SPACE &&
	    res != TEE_ERROR_CORRUPT_OBJECT &&
	    res != TEE_ERROR_STORAGE_NOT_AVAILABLE)
		TEE_Panic(res);

	if (res != TEE_SUCCESS && object)
		*object = TEE_HANDLE_NULL;

	return res;
}

TEE_Result __GP11_TEE_CreatePersistentObject(uint32_t storageID,
					     const void *objectID,
					     uint32_t objectIDLen,
					     uint32_t flags,
					     TEE_ObjectHandle attributes,
					     const void *initialData,
					     uint32_t initialDataLen,
					     TEE_ObjectHandle *object)
{
	__utee_check_out_annotation(object, sizeof(*object));

	return TEE_CreatePersistentObject(storageID, objectID, objectIDLen,
					  flags, attributes, initialData,
					  initialDataLen, object);
}
 ```

Line 669 would be the ```__utee_check_out_annotation(object, sizeof(*object)); ```. Sadly I can not tell what is wrong there but I noticed two things. 
1. I am calling ```TEE_CreatePersistentObject ```, why is the ```__GP11_TEE_CreatePersistentObject ``` getting called? 
2. In  ```TEE_CreatePersistentObject ``` the line  ```__utee_check_out_annotation(object, sizeof(object) ``` is in a if statement, in ```__GP11_TEE_CreatePersistentObject ``` not, does this needs to be changed?

**Comment by jforissier** [comment]
Hi @Dark-Sphere ,

`TEE_CreatePersistentObject()` was changed in the v1.3 of the GlobalPlatform spec to accept a NULL `object`. Prior to that it was forbidden. `__GP11_TEE_CreatePersistentObject()` is the v1.1 version of the function. It is used when the TA requests backwards compatibility at compile time. Please check if your build flags include `__OPTEE_CORE_API_COMPAT_1_1=1`. I suspect they do. To use the latest version of the function, do not set this macro.

**Comment by etienne-lms** [comment]
Right, i missed the v1.1 path. Note: using the old API should work passing a output `TEE_ObjectHandle` pointer to `TEE_CreatePersistentObject()`.

**Comment by Dark-Sphere** [comment]
So I change the ```__OPTEE_CORE_API_COMPAT_1_1=1``` to ``__OPTEE_CORE_API_COMPAT_1_1=0``` in the build-user-ta.mk and the ta_dev_kit.mk 
Now there is no error or panic returned. Thanks for your great help :D

The only issue to me now is that the key seems kinda wierd (to me it seems like garbage values and not a key) 
![image](https://github.com/OP-TEE/optee_os/assets/60129774/b00b3ede-2901-4667-8486-c44a1ca0ace7)

This is how I tried to print the key to confirm it is generated correctly:
```c
    IMSG("Trying to TEE_OpenPersistentObject!");
    result = TEE_OpenPersistentObject(TEE_STORAGE_PRIVATE, &objectID, sizeof(objectID), TEE_DATA_FLAG_ACCESS_READ, &key_handle);
    if (result != TEE_SUCCESS){
        EMSG("Failed to open persistent key: 0x%x", result);
        return result;
    }
    else
    {
        IMSG("Success to open persistent key!");
    }

    DMSG("Trying to TEE_GetObjectInfo1");
    result = TEE_GetObjectInfo1(key_handle, &key_info);
    if (result != TEE_SUCCESS)
    {
        EMSG("TEE_GetObjectInfo failed!");
        EMSG("TEE_GetObjectInfo: %#" PRIx32, result);
        return result;
    }
    else
    {
        IMSG("TEE_GetObjectinfo succeeded!");
    }

    IMSG("Trying to read persistent key data!");
    result = TEE_ReadObjectData(key_handle, read_key_data, key_info.dataSize, &read_bytes);
    if(result != TEE_SUCCESS){
        EMSG("Failed to read persistent key data!");
        TEE_CloseObject(key_handle);
	    TEE_Free(objectID);
        TEE_Free(read_key_data);
	    return result;
    }
    else
    {
        IMSG("This is the size of read_key: %u", sizeof(read_key_data));
        IMSG("Read key:");
        for (size_t i = 0; i < sizeof(read_key_data); i++){
            IMSG("%i ", (int)read_key_data[i]);
        }
        IMSG("Success executing TEE_ReadObjectData!");
    }
```

**Comment by Dark-Sphere** [comment]
I tried to get the size of the object data with: 
```c
IMSG("Trying to get Object Info!");
result = TEE_GetObjectInfo1(transient_key, &keyInfo);
if (result != TEE_SUCCESS)
{
            EMSG("Failed to get Object info of persistent object: 0x%x", result);
            TEE_FreeTransientObject(transient_key);
            TEE_CloseObject(transient_key);
            return result;
}
else
{
            IMSG("Success getting object info of persistent object!");
            IMSG("Here is the object usage flag: %#" PRIx32, keyInfo.objectUsage);
            IMSG("Here is the object data size: %#" PRIx32, keyInfo.dataSize);
}

When I execute the previously shown code I get the output that the object data size is 0. So is there no key generated or is it lost when transforming the object? Or is there some other reason? 

The output of the code execution:
![image](https://github.com/OP-TEE/optee_os/assets/60129774/c9da5f54-59c4-46fa-bd21-588e0b439f55)

**Comment by jforissier** [comment]
Data size does not include the key. A persistent object stores attributes (such as key parameters) and *optionally* a data stream. When creating a persistent object from a transient object there is no data.

**Comment by Dark-Sphere** [comment]
> Data size does not include the key. A persistent object stores attributes (such as key parameters) and _optionally_ a data stream. When creating a persistent object from a transient object there is no data.

Thanks for the clarification. 
So is there a possibility to read the key material from the persistant object? 
1. So I can check if it is generated correcty
2. So I can perform a key exchange using asymmetric encryption?

**Comment by jforissier** [comment]
> So is there a possibility to read the key material from the persistant object?

Yes, with `TEE_GetObjectBufferAttribute()`.

**Comment by Dark-Sphere** [comment]
Wow ... sorry for the dumb question ... I sould read more carefully the Docs ... 🤦

Thank you so much for the help :D

**Comment by Dark-Sphere** [comment]
Sadly I have to reopen the issue since I encountered another problem. Bevore I was able to transform the transient object into a persistent object my encryption functions worked well or at least did not throw any errors. 
Now this is different. 
I want to encrypt my data (given with the function call) with AES-GCM. And when I call the TEE_AEEncryptFinal function I get a panic 0xffff001 (TEE_ERROR_ACCESS_DENIED)
So I wrote the following code: 

```c
outbuf = params[2].memref.buffer;
outbuf_len = params[2].memref.size;
tag = params[3].memref.buffer;
tag_len = params[3].memref.size;

result = TEE_AEInit(encrypt_op, iv, iv_sz, 96, 0, 0);
if(result != TEE_SUCCESS)
{
 EMSG("TEE_AEInit failed! Reason: %#" PRIx32, result);
}
else
{
 IMSG("TEE_AEInit succeeded!");
}

// Did this since earlier I got the error message that the outputbuffer is too small
outbuf_len = inbuf_len + 32;
result = TEE_AEUpdate(encrypt_op, inbuf, inbuf_len, outbuf, &outbuf_len);
if(result != TEE_SUCCESS)
{
   EMSG("TEE_AEEncryptFinal failed! Reason: %#" PRIx32, result);
}
else
{
   IMSG("Cypher: %p, size %i", outbuf, outbuf_len);
}
result = TEE_AEEncryptFinal(encrypt_op, inbuf, inbuf_len, outbuf, &outbuf_len, tag, &tag_len);
```
Everything prior to the function seems to work. My inbuffer is filled and the setting of the key as well as operation allocation seem to work fine. But the AEEncryptFinal paniks. Does this have to do something with me disabling the GP1.1 functions? Or is the error something else. 

Additionally here is the output dumb with symbolize.py, which shows the error beeing with the function  TEE_AEEncryptFinal:
![image](https://github.com/OP-TEE/optee_os/assets/60129774/e3913f69-605b-485f-adf3-ab43076f01df)

**Comment by jforissier** [comment]
> ```C
> // Did this since earlier I got the error message that the outputbuffer is too small
> outbuf_len = inbuf_len + 32;
> ```

Ouch! The buffer comes from the client so you clearly can't do that. Nor should you need to, because AES-GCM encryption keeps the size unchanged.

> ```C
> result = TEE_AEUpdate(encrypt_op, inbuf, inbuf_len, outbuf, &outbuf_len);
> if(result != TEE_SUCCESS)
> {
>    EMSG("TEE_AEEncryptFinal failed! Reason: %#" PRIx32, result);
> }
> else
> {
>    IMSG("Cypher: %p, size %i", outbuf, outbuf_len);
> }
> result = TEE_AEEncryptFinal(encrypt_op, inbuf, inbuf_len, outbuf, &outbuf_len, tag, &tag_len);
> ```

You're processing `inbuf` twice. Please drop the `TEE_AEUpdate()` call.

**Comment by Dark-Sphere** [comment]
> Ouch! The buffer comes from the client so you clearly can't do that. Nor should you need to, because AES-GCM encryption keeps the size unchanged.

This was more ment to skip the error msg of TEE_AEUpdate and see what TEE_AEEncryptFinal does or in my case does not do 
XD 

> > ```c
> > result = TEE_AEUpdate(encrypt_op, inbuf, inbuf_len, outbuf, &outbuf_len);
> > if(result != TEE_SUCCESS)
> > {
> >    EMSG("TEE_AEEncryptFinal failed! Reason: %#" PRIx32, result);
> > }
> > else
> > {
> >    IMSG("Cypher: %p, size %i", outbuf, outbuf_len);
> > }
> > result = TEE_AEEncryptFinal(encrypt_op, inbuf, inbuf_len, outbuf, &outbuf_len, tag, &tag_len);
> > ```
> 
> You're processing `inbuf` twice. Please drop the `TEE_AEUpdate()` call.

Ah ok. Seems I did not understand the documentation correctly there. Thanks for the clarification that I only need TEE_AEEncryptFinal. 


Also I did manage to solve my issue with the function. So everything works as intended. :D
