### ISSUE TITLE
HMAC-SHA256 minimum key size 

### ISSUE THREAD

**Issue by zjchen666** [OP-TEE/optee_os#6269]
looks like the HMAC-SHA256 minimum key size is 192bits now.
https://github.com/zjchen666/optee_os/blob/8b15600d8d266b735ea86c68e58033c8a706be8d/core/tee/tee_svc_cryp.c#L414
```
	PROP(TEE_TYPE_HMAC_SHA256, 8, 192, 1024,
		1024 / 8 + sizeof(struct tee_cryp_obj_secret),
		tee_cryp_obj_secret_value_attrs),
```
Can you please help me understand the justification for not supporting the 128bits key size?
is there any workaround for this limitation? 
Thanks,
Zhijun

**Comment by jbech-linaro** [comment]
It's coming from the specification, have a look at the GlobalPlatform Internal Core API spec, there is a table there specifying valid key sizes  for various algorithms and for HMAC SHA256 it says: `"Between 192 and 1024 bits, multiple of 8 bits"`. So, I'm afraid the question should be asked to GlobalPlatform. I cannot remember out of my head whether these are coming from the FIPS and NIST specifications or not.

**Comment by zjchen666** [comment]
understood. thanks for the clarifying
