### ISSUE TITLE
How to allocate DMA coherent memory for drivers in optee

### ISSUE THREAD

**Issue by ruchi393** [OP-TEE/optee_os#628]
Hello,

We are planning to plug-in driver for our SoC's crypto block in OPTEE. The block requires some DMA coherent memory. I am unable to find any API's in OPTEE which allocate such memory. Can you provide more details on how we can do this ? 

Would using malloc in OPTEE give us physically contiguous memory ?

Regards,
Ruchika

**Comment by jenswi-linaro** [comment]
`malloc()` in OP-TEE currently gives physically contiguous memory. It's not guaranteed as we don't say so anywhere, but in practice the heap only has physically contiguous memory in the pool(s). The heap in OP-TEE is normally quite small, ~24KiB, and could be a bit fragmented. How large allocations are we talking about?

Regards,
Jens

**Comment by ruchi393** [comment]
The allocations would be of size 256 bytes for the crypto driver.

For cryptographic operations, often the caller provides buffer for input and output data using pointers...How are these buffers shared with Trusted world ? Can they be assumed to be in physically contiguous memory ? 

Regards,
Ruchika

**Comment by pascal-brand-st-dev** [comment]
Buffers are transferred from the Non-Secure world to the Trusted one using Shared Buffers (cf. Global Platform API). In case buffers are not contiguous, the OP-TEE linux driver copies the buffer to/from physically contiguous temporary buffers.

Please close this issue if it answers.

**Comment by pascal-brand-st** [comment]
Question has been answered, please re-open in case you have additional questions

**Comment by junwua** [comment]
Hi  @jenswi-linaro  ,  we add spi driver, use the spi translate buf with DMA buf, size 1K byte.
so how to do it?  I find other tee os finish this function, don't know how to do it.
thanks.

**Comment by P1119r1m** [comment]
I don't think this question should be closed.
What will you do to share, for example, video buffer.
We don't need here an overhead isn't it?
