### ISSUE TITLE
Secure storage object(with PKCS11) usage 

### ISSUE THREAD

**Issue by coach-bin** [OP-TEE/optee_os#6280]
When we used other secure OS(not OPTEE), a client application had APIs such as write_certificate(idx, data), read_certificate(idx, data). For example, 3 certificates were stored in external storage permanently, and they had own index: 0, 1, 2. so we accessed the certifcates via those index.

As we migrate to OPTEE, I'd like to see if I can use pkcs11 in a same way. (considering to use secure storage instead)

I think the scenario like below. 
1. In initial booting, CA creates 3 persistent objects with C_CreateObject(CKA_LABLE={0,1,2}, CKA_TOKEN=TRUE, CKA_MODIFIABLE=TRUE, CKA_DESTROYABLE=FALSE) : This is just to populate 3 objects, and it will write dummy data and will write real data later.
2. CA manages a map of object index and label. 
3. CA can access the object via index.
   Pseudo code:
   write_certificate(idx,data) {
      label = get_label(idx);
      template = {
         {CKA_LABEL, label, ...},
         {CKA_MODIFIABLE, FALSE, ...} // at this point, make it impossible to modify
      };
      C_CreateObject(template);
   }
   read_certificate(idx,data) {
      label = get_label(idx);
      template = {
         {CKA_LABEL, label, ...},
      };
       C_FindObjects(template);
   }
5. From 2nd booting, CA checks the label corresponding to index 0. If the object corresponding to the label exists, it doesn't create persistent objects any more. And it can writre/read the object via index

Does this make sense? Or is there any concern for this scenario? (Please consider this is first time to try to use pkcs11 :))

**Comment by etienne-lms** [comment]
Hello @coach-bin, you description looks good to me. Using object label is a good way to identify object.

**Comment by coach-bin** [comment]
@etienne-lms  Thanks for reviewing. I'll test this way

**Comment by coach-bin** [comment]
@etienne-lms 
I'm checking the step 3 that I described above, but it's failing. Once I created an object with template below, if I tried to modify its attribute, C_SetAttributeValue() returns CKR_ATTRIBUTE_READ_ONLY, but I can't find any clew. Is there anything that I need to check? I treid CKO_DATA class.

	CK_ATTRIBUTE data_template[] = {
		{ CKA_LABEL, (CK_UTF8CHAR_PTR)label1, strlen(label1) },
		{ CKA_CLASS,	&(CK_OBJECT_CLASS){CKO_DATA},
							sizeof(CK_OBJECT_CLASS) },
		{ CKA_TOKEN,	&(CK_BBOOL){CK_TRUE}, sizeof(CK_BBOOL) },
		{ CKA_EXTRACTABLE, &(CK_BBOOL){CK_TRUE}, sizeof(CK_BBOOL) }, /* important */
		{ CKA_MODIFIABLE, &(CK_BBOOL){CK_TRUE}, sizeof(CK_BBOOL) },
		{ CKA_VALUE,	(void *)data_buf, sizeof(data_buf) },
	};

	CK_ATTRIBUTE set_template[] = {
		{ CKA_VALUE, (void *)set_buf, sizeof(set_buf) },
	};

	rv = C_CreateObject(session, data_template,
			    ARRAY_SIZE(data_template),
			    &obj_hdl);

	rv = C_SetAttributeValue(session, obj_hdl, set_template, ARRAY_SIZE(set_template));
        // it's returing CKR_ATTRIBUTE_READ_ONLY

**Comment by coach-bin** [comment]
I tried to modify CKA_LABEL instead of CKA_VALUE just for testing, and it succeeded. I think this may mean that CKA_VALUE modification is prohibited by spec(even I hadn't found something related yet) or OPTEE. What I can consider may be to create a new object with a new value and to destroy the old object.

**Comment by etienne-lms** [comment]
I checked the implementation: indeed most attributes for`CKO_DATA` are not modifiable.
As one can see in [_ta/pkcs11/src/pkcs11_attributes.c_](https://github.com/OP-TEE/optee_os/blob/3.22.0/ta/pkcs11/src/pkcs11_attributes.c#L2056-L2111), line 2098:
```c
	case PKCS11_CKO_DATA:
		/* None of the data object attributes are modifiable */
		return false;
```
Reading the spec I can't see such  constraints. I'll check it again the spec but I think the implementation is too restrictive here. Thanks for reporting the issue.

**Comment by etienne-lms** [comment]
P-R https://github.com/OP-TEE/optee_os/pull/6291

**Comment by etienne-lms** [comment]
From https://github.com/OP-TEE/optee_os/pull/6291 discussion thread, it seems this change is not needed. Yet, this tocken restriction could be mentioned in the docs.
I'll let this Issue and P-R #6291close if there's not activity on this topic.

**Comment by coach-bin** [comment]
@etienne-lms I agree to describe this token restriction in the doc. And I have no strong opinion on whether we need to change current behavior. In my scenario it's good to change this and all I'm worried about is reverting this change again. As this is my first experience with pkcs11 and the spec is ambiguous, I'm cautious.
