### ISSUE TITLE
TA :Trusted Keys: AES-GCM IV generation

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#6283]
In AES-GCM the IV should be unique (not so much random). 

The Trusted Keys TA exposes the IV _outside_ the secure world along with the cipher-text reusing the same key on every operation.

To avoid the same IV being reused (as much as possible), should we replace the IV generation code to use a 12 byte hashed UUID instead? I believe that should be better at guaranteeing the uniqueness of these vectors.

**Comment by jenswi-linaro** [comment]
> In AES-GCM the IV should be unique (not so much random).
> 
> The Trusted Keys TA exposes the IV _outside_ the secure world along with the cipher-text reusing the same key on every operation.

I agree, this is an issue.

> 
> To avoid the same IV being reused (as much as possible), should we replace the IV generation code to use a 12 byte hashed UUID instead? I believe that should be better at guaranteeing the uniqueness of these vectors.

Would it make sense to hash the payload too? That way it's not possible to get the IV for a different payload.

**Comment by ldts** [comment]
sorry just noticed that the IV size is 16 bytes on this TA so we could just replace it with the UUID (no need to hash it)

**Comment by jenswi-linaro** [comment]
> AFAIK IVs must be unique for any operation with the same key - even for the same payload - so deriving the IV somehow from payload wont be sufficient if that is what you mean?

The same KEY+IV pair must never be reused. The IV should ideally be chosen by the trusted keys TA.

**Comment by jenswi-linaro** [comment]
A random IV sounds good.

**Comment by b49020** [comment]
Isn't it already a random IV [1] for every AES-GCM operation in trusted-keys on a different payload? So there ins't any issue, right?

[1] https://github.com/OP-TEE/optee_os/blob/5f1edb13c7308888f385b5c4ad857138e6c052ee/ta/trusted_keys/entry.c#L105C2-L105C20

**Comment by ldts** [comment]
@b49020 yes it is random but that does not equate to unique (UUID on the other hand had some mathematical uniqueness guarantees...beyond my level of knowledge to explain though).

if we could use an UUID from OP-TEE that would be great, but failing that I suppose we can live with random (probabilistic-ally speaking)

**Comment by jforissier** [comment]
Can we agree than choosing the 16-byte IV randomly as is currently done is OK, since the chance for IV re-use is vanishingly small? (assuming proper randomness of course).

**Comment by nathan-menhorn** [comment]
> Can we agree than choosing the 16-byte IV randomly as is currently done is OK, since the chance for IV re-use is vanishingly small? (assuming proper randomness of course).

Hi @jforissier I would agree this would be sufficient.

**Comment by b49020** [comment]
> if we could use an UUID from OP-TEE that would be great

I am not sure if we can add the complete UUID library inside OP-TEE available for TAs but IMO we can make the uniqueness of IV more robust via hashing timestamp value (fetched via `TEE_GetSystemTime()` although it only has ms granularity) into the randomly generated IV.

> Can we agree than choosing the 16-byte IV randomly as is currently done is OK, since the chance for IV re-use is vanishingly small? (assuming proper randomness of course).

Agree and the recommended source of randomness is HWRNG. So the chances are very rare to get a double hit for same 16-byte IV.

**Comment by b49020** [comment]
> Hi @ldts you are correct. This is a requirement by the NIST standard. Please see: https://csrc.nist.gov/pubs/sp/800/38/d/final for details.

I went through this NIST requirement and section: `8.2 IV Constructions` says for 128-bit and 160-bit IVs, RBG-based Construction can be used. So I don't think we need any custom method for 16 bytes IV generation here.
