### ISSUE TITLE
How can i get the return of read_is_device_unlocked to be unlocked? 

### ISSUE THREAD

**Issue by fsickle** [OP-TEE/optee_os#6290]
I got a code of uboot, and there is function read_is_device_unlocked which always return of locked status. I read the code, and did not get any code to set the value of state-> ta_avb_lock_state.
  Is there any way to get the return of read_is_device_unlocked change with no change of the source code? I tried the fastboot command which used in android, however it does not work. Thanks a lot, if you can give some advice.

**Comment by fsickle** [comment]
By the way, I skipped the code of check read_is_device_unlocked, and write something to emmc0 when uboot. Then it Succeeded. So, the value of " locked" does not mean that the device can not read or write. What does it actually mean?

**Comment by etienne-lms** [comment]
@fsickle, see [Android AVB locked and unlocked modes](https://android.googlesource.com/platform/external/avb/+/main/README.md#locked-and-unlocked-mode).
