### ISSUE TITLE
Upgrading from 3.12 to 3.16 - secure storage access

### ISSUE THREAD

**Issue by mirceacaprioru** [OP-TEE/optee_os#6296]
Hi,

I have been using OP-TEE 3.12 on a device and storing keys inside the secure storage using the default REE fs.

Now I am trying to upgrade to 3.16, but after I do this I get these errors:
```
LD:  init_elf:439 sys_open_ta_bin(fd02c9da-306c-48c7-a49c-bbd827ae86ee)
E/TC:? 0 ldelf_init_with_ldelf:130 ldelf failed with res: 0xf0100001
E/LD:  init_elf:439 sys_open_ta_bin(fd02c9da-306c-48c7-a49c-bbd827ae86ee)
E/TC:? 0 ldelf_init_with_ldelf:130 ldelf failed with res: 0xf0100001
E/LD:  init_elf:439 sys_open_ta_bin(fd02c9da-306c-48c7-a49c-bbd827ae86ee)
E/TC:? 0 ldelf_init_with_ldelf:130 ldelf failed with res: 0xf0100001
E/LD:  init_elf:439 sys_open_ta_bin(fd02c9da-306c-48c7-a49c-bbd827ae86ee)
E/TC:? 0 ldelf_init_with_ldelf:130 ldelf failed with res: 0xf0100001
E/LD:  init_elf:439 sys_open_ta_bin(fd02c9da-306c-48c7-a49c-bbd827ae86ee)
E/TC:? 0 ldelf_init_with_ldelf:130 ldelf failed with res: 0xf0100001
```
If I remove the `dirf.db` from `/data/tee` these errors go away but I also lose the data from the secure storage. 

Is there a way to do an upgrade while preserving the secure data ? 

Thank you,
Mircea

**Comment by jenswi-linaro** [comment]
I was expecting that it should be backward compatible. Any chance of bisecting or in other ways narrowing down the problem?

**Comment by vesajaaskelainen** [comment]
Don't recall what version it was but we had to adjust imx variant with:

>     CFG_CORE_HUK_SUBKEY_COMPAT_USE_OTP_DIE_ID=n \

In order to keep secure storage working

**Comment by abularca** [comment]
Hi,

Mircea is out of office for the moment, therefore I will try to help on this topic.
Conclusions so far:
- running other TA generates the same error, so this problem is not specific only to the PKCS11 TA
- the `CFG_CORE_HUK_SUBKEY_COMPAT_USE_OTP_DIE_ID` option is by default set to 'n'
- MAC verification fails during hash tree read/verify.
  There seems to be an authentication problem (MAC) in function `verify_root()`, which returns the `TEE_ERROR_CORRUPT_OBJECT` error code.

As we couldn't enable debug logs because the board doesn't boot anymore, we had to manually add logs to narrow down the problem.
The logs generated by running the TA:
```
root@host:~# optee_example_hello_world 
I/TC: tee_ta_init_user_ta_session():420 Init user TA session
I/TC: ldelf_handle_svc():313 - syscall(#1)
I/LD: Loading TS 8aaaf200-2450-11e4-abe2-0002a5d5c51b
I/TC: ldelf_handle_svc():313 - syscall(#3)
I/TC: ldelf_handle_svc():313 - syscall(#5)
I/TC: Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (early TA)
I/TC: res=0xffff0008
I/TC: Lookup user TA ELF 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
I/TC: secstor_ta_open():19 Secure Storage: open TA
I/TC: ree_fs_open():631
I/TC: ree_fs_open_primitive():409 
E/TC:? 1 authenc_decrypt_final:528 MAC invalid
E/TC:? 1 tee_fs_htree_open:676 verify_root() fails: 0xf0100001
I/TC: tee_fs_htree_open():694 return: 0xf0100001
I/TC: ree_fs_open_primitive():439 return: 0xf0100001
I/TC: res=0xf0100001
I/TC: ldelf_handle_svc():313 - syscall(#1)
E/LD:  init_elf:440 sys_open_ta_bin(8aaaf200-2450-11e4-abe2-0002a5d5c51b)
I/TC: ldelf_handle_svc():313 - syscall(#0)
E/TC:? 1 ldelf_init_with_ldelf:132 ldelf failed with res: 0xf0100001
optee_example_hello_world: TEEC_Opensession failed with code 0xf0100001 origin 0x3
```

Could it be that between v3.12 and v3.16 something has changed with regards to the secure storage and the
two versions are not compatible?

Thank you,
Adrian

**Comment by jenswi-linaro** [comment]
> Could it be that between v3.12 and v3.16 something has changed with regards to the secure storage and the
> two versions are not compatible?

That is a possibility, but so far I haven't found anything obvious. If it's possible to `git bisect` it, that's probably our best option.

**Comment by mirceacaprioru** [comment]
We have found the issue. We had a different hardware key in between 3.12 and 3.16.

**Comment by jenswi-linaro** [comment]
Thanks for reporting back.
