### ISSUE TITLE
Call the secure monitor from PTA

### ISSUE THREAD

**Issue by fengyuanyu1** [OP-TEE/optee_os#6299]
Hey Team,

I am trying to call the ATF from PTA. I search the issues and find #4236 and #1330. From them, I get the information as follwing:
1. SMC need to be called in the priviledged level.
2. SMC is used to switch the world.

And I have two questions.
1. Can I use the SMC in PTA to call specific service provided by ATF? Is it possible?
2. Can I reject the switch of world without change ATF? That is, can I return to PTA after calling ATF service using SMC?

**Comment by etienne-lms** [comment]
Yes, you can call a TF-A monitor service from an OP-TEE PTA, using a SMC instruction. Helper function `thread_smccc()` can help you. TF-A will not operate a world switch when secure world calls such a service.

An example is the TRNG SMCCC service to get random bytes from TF-A (when it supports that service), see _core/drivers/smccc_trng.c_.

**Comment by fengyuanyu1** [comment]
@etienne-lms It is very useful. Thank you very much.
