### ISSUE TITLE
Trusted application Access conflict Error code leads to tampering of data stored in Secure Storage

### ISSUE THREAD

**Issue by dhruv77777** [OP-TEE/optee_os#6302]
Hey Team, 

I have created an API to Hash the data and then sign the data with the private key (Which is to be fetched from Secure Storage).
I am calling this API for one time, and the operation is successful but when i am calling this API for more than 5-6 times (Using a shell script file). I am getting an error with the code **"0xffff0003"**, Which i understand is expected in our case. 

But I am also seeing after calling this Shell scripting multiple times, i am also getting error at some cases **"0xffff0008"**, which is ITEM_NOT_FOUND. 
After this operation, the metadata stored in partition gets updated and i am unable to further sign the data using the pre generated key. 

Attaching the logs for the same....

```
secure_crypto_init : TEEC init success
start hash
secure_crypto_init : Secure Crypto library version 01.9 ...
secure_crypto_init : TEEC init success
start hash
secure_crypto_init : Secure Crypto library version 01.9 ...
secure_crypto_init : TEEC init success
start hash
secure_crypto_init : Secure Crypto library version 01.9 ...
secure_crypto_init : TEEC init success
start hash
secure_crypto_open_session : open session success.
secure_crypto_open_session : open session success.
secure_crypto_open_session : open session success.
secure_crypto_open_session : open session success.
secure_crypto_hash_init : hash_init success.
secure_crypto_hash_init : hash_init success.
secure_crypto_hash_init : hash_init success.
secure_crypto_hash_init : hash_init success.
secure_crypto_hash_update : hash_update success.
secure_crypto_hash_update : hash_update success.
secure_crypto_hash_update : hash_update success.
secure_crypto_hash_update : hash_update success.
secure_crypto_hash_final : hash_final success.
secure_crypto_hash_final : hash_final success.
hash calculated over file test.bin (length 1024)
hash calculated over file test.bin (length 1024)
=============================================================================================
=============================================================================================
95 81 35 dd bb c1 bc 4b ea 2a ac 33 af 90 db 54 d5 6a 15 f3 7f 5c 75 f7 c0 99 64 58 90 a4 fd ba
=============================================================================================
secure_crypto_hash_final : hash_final success.
95 81 35 dd bb c1 bc 4b ea 2a ac 33 af 90 db 54 d5 6a 15 f3 7f 5c 75 f7 c0 99 64 58 90 a4 fd ba
=============================================================================================
check_storage_param : success...
secure_crypto_hash_final : hash_final success.
hash calculated over file test.bin (length 1024)
=============================================================================================
check_storage_param : success...
hash calculated over file test.bin (length 1024)
=============================================================================================
95 81 35 dd bb c1 bc 4b ea 2a ac 33 af 90 db 54 d5 6a 15 f3 7f 5c 75 f7 c0 99 64 58 90 a4 fd ba
=============================================================================================
check_storage_param : success...
95 81 35 dd bb c1 bc 4b ea 2a ac 33I af 90 db 54 d5 6a 15 f3 7f 5c 75 f7 c0 99 64 58 90 a4 fd ba
=============================================================================================
check_storage_param : success...
/HTA: storage open session!
*I/HTA: storage open session!
I/HTA: storage open session!
I/HTA: storage open session!
*I/HTA: Inside TA getdatasize routine
*I/HTA: Inside TA getdatasize routine
*I/HTA: Inside TA getdatasize routine
*E/HTA:  **ta_storage_getdatasize:428 Failed to open persistent object, res=0xffff0003**
*E/HTA:  **ta_storage_getdatasize:428 Failed to open persistent object, res=0xffff0003**
*E/HTA:  ta_call_secure_storage_getdatasize:205 TEE_InvokeCommand failed with code 0xffff0003 origin 0x4
*E/HTA:  ta_call_secure_storage_getdatasize:205 TEE_InvokeCommand failed with code 0xffff0003 origin 0x4
*I/HTA: storage close session!
*I/HTA: storage close session!
*I/HTA: Inside TA getdatasize routine
E/HTA:  **ta_storage_getdatasize:428 Failed to open persistent object, res=0xffff0003**
*E/HTA:  Asymmetric_signDigest:682 Asymmetric_signDigest()::ta_call_secure_storage_getdatasize error 0xffff0003
*E/HTA:  Asymmetric_sigsecure_crypto_asym_sign_verify : TEEC_InvokeCommand TA_CMD_Asymmetric_signDigest :: read private key failed with code 0xffff0003 origin 0x4
ERROR signing... ret = ffff0003
secure_crypto_closne_session : close session done.
secure_crypto_deinit : TEEC deinit done.
Digest:682 Asymmetric_signDigest()::ta_call_secure_storage_getdatasize error 0xffff0003
*E/HTA:  ta_call_secsecure_crypto_asym_sign_verify : TEEC_InvokeCommand TA_CMD_Asymmetric_signDigest :: read private key failed with code 0xffff0003 origin 0x4
ERROR signing... ret = ffff0003
secure_crypto_close_session : close session done.
secure_crypto_deinit : TEEC deinit done.
ure_storage_getdatasize:205 TEE_InvokeCommand failed with code 0xffff0003 origin 0x4
*E/HTA:  **_### ta_storage_getdatasize:428 Failed to open persistent object, res=0xffff0008_**
*I/HTA: storage close session!
*E/HTA:  ta_call_secure_storage_getdatasize:205 TEE_InvokeCommand failed with code 0xffff0008 origin 0x4
*E/HTA:  Asymmetric_signDigest:682 Asymmetric_signDigest()::ta_call_secure_storage_getdatasize error 0xffff0003
*I/HTA: storasecure_crypto_asym_sign_verify : TEEC_InvokeCommand TA_CMD_Asymmetric_signDigest :: read private key failed with code 0xffff0003 origin 0x4
ERROR signing... ret = ffff0003
secure_crypto_close_session : close session done.
secure_crypto_deinit : TEEC deinit done.
ge close session!
E/HTA:  Asymmetric_signDigest:682 Asymmetric_signDigest()::ta_call_secure_storage_getdatasize error 0xffff0008
secure_crypto_asym_sign_verify : TEEC_InvokeCommand TA_CMD_Asymmetric_signDigest :: read private key failed with code 0xffff0008 origin 0x4
ERROR signing... ret = ffff0008
secure_crypto_close_session : close session done.
secure_crypto_deinit : TEEC deinit done.
```

Kindly let me know if you need any clarification on the execution of API.

**Comment by etienne-lms** [comment]
I don't think _dirf.db_ is updated when no object data (here only in _/data/tee/0_) is updated. 
Could is be _/data/tee/0_ was updated at timestamp 05:31:59 and then _/data/tee/dirfs_ update right after, at timestamp 05:32:00?

Note that when a TA is loaded (from Linux filesystem) in OP-TEE, the TA UUID and its version number are stored in OP-TEE secure storage, for TA version rollback protection. Therfore, the first time a TA is ever loaded, such an entry is created in the secure storage. When the same TA is loaded again later and shows the same version number, the related entry in the secure storage is not updated as it does not need to.

Regarding you initial issue, it's hard to tell without looking at the TA code.

**Comment by dhruv77777** [comment]
Hello @etienne-lms

1) I Executed an API for creation of data and storing that data into Secure Storage:
ls -lah /mnt/global/tee
drwx------    2 root     root        4.0K Aug  7 05:35 .
drwx------    3 root     root        4.0K Aug  7 05:30 ..
-rw-------    1 root     root       16.0K Aug  7 05:35 0
-rw-------    1 root     root       16.0K Aug  7 05:35 dirf.db

2) After 3 Minutes, i got the updated time as 05:38:06:
root@xyz:date
Mon Aug  7 05:38:06 UTC 2023

3) Ran the Shell Scripting File through which we are Calling the Secure Storage Read Only for multiple times....
root@dhruv:~/test-tools# ./test.sh
[Error codes as stated above]

4) Found the Metadata got updated.
root@dhruv:~/test-tools# ls -lah /mnt/global/tee/
drwx------    2 root     root        4.0K Aug  7 05:35 .
drwx------    3 root     root        4.0K Aug  7 05:30 ..
-rw-------    1 root     root       16.0K Aug  7 05:35 0
-rw-------    1 root     root        4.1K Aug  7 05:38 dirf.db

So, After this if i use the API normally (Single Call), It results in 0xffff0008.

Please note that i am using the Same TA for single call (Where it is working fine) and multiple call (Where it is failing).

**Comment by dhruv77777** [comment]
Hey Team,

Is there any update on the above-asked request?

**Comment by jenswi-linaro** [comment]
It seems we don't have enough data to help much more. It looks like something is wrong, but without being able to reproduce the problem myself I can't help.
If you can share the steps to reproduce the problem on the latest upstream version of OP-TEE on qemu_v8 I can take another look, provided that the steps are not too complicated.
