### ISSUE TITLE
Explore a way to examine TEE secure time

### ISSUE THREAD

**Issue by weizhaojiang** [OP-TEE/optee_os#6304]
We are working on video streaming product which includes DRM features. In DRM TA, we depends on TEE secure time to identify the license is expired or not. Therefore, the accuracy of secure time is very critical to us. Meanwhile, we are working on different platforms which have different secure time implementation. The secure time might go fast or slow, which cause problems.

Now, we are looking for a way to examine secure time in a run-time. 

One of my thinking is add one cmd in ``stats PTA``: 
```
#define STATS_CMD_TA_SECURE_TIME
```
We pass two parameters: 1) REE system time and 2) delta allowed, when invoking that cmd. The cmd then return a ``bool`` value to tell us if the TEE time is sync with REE time.

This way is using REE system time as base to examine TEE secure time to see if it goes fast or slow.

Please help to review above and let me know if it breaks something in security. If you have other proposal, please kindly share to me. Thanks.

**Comment by weizhaojiang** [comment]
Correct, it's for testing purpose. If test result shows the secure time is not accurate enough, we will go to refine its implementation.
Will have PR on this change. Thanks.

**Comment by weizhaojiang** [comment]
@jenswi-linaro May I have question?
I looking into TEE secure time and call below two functions in PTA to get ``ree_time`` and ``tee_time``.
```
	tee_time_get_ree_time(&ree_time);
	tee_time_get_sys_time(&tee_time);
```
When run on Qume, I found ``ree_time`` is an epoch unix timestamp while ``tee_time`` is timestamp from 0 when system boot up. I believe different platform will have different tee_time source. So, looks like I can't use ``ree_time`` absolute value to examine ``tee_time`` as they have different start point.
To check if a tee time is good or not, I need to make sure
1. the time is monotonically increasing, not rollback across power cycle;
2. The TEE time increment should be consistent with the REE time.

To simplify the testcase design, can I have the CDM ``STATS_CMD_TA_SECURE_TIME`` return the TEE time to REE world? Any security concern here?

**Comment by jenswi-linaro** [comment]
The platform probably needs to maintain a secure time offset using a secure RTC or such.
Another stats cmd shouldn't be a problem.

**Comment by weizhaojiang** [comment]
The patches have been merged, closing the ticket.
