### ISSUE TITLE
Question about PKCS11 authentication

### ISSUE THREAD

**Issue by coach-bin** [OP-TEE/optee_os#6313]
I'm testing Cryptoki & PKCS11, but it's very unclear to me what the PIN is used for. I thought the PIN was an authentication method to take ownership of HSM(PKCS11 TA). However, I was able to use C_CreateObject(), C_SetAttributeValue(), C_Verify(), etc.... without any authentication (without calling C_InitToken(), C_InitPIN(), C_Login()). Even after I logged in as user with specific PIN and logout, I was able to create object and set its attribute value and so on..

PIN seems to be only used for login, and login action doesn't seem to have any special meaning in operation. 

- I'm curious if the tested behavior is normal.
- If this is normal operation, can someone explain how login has a meaning in pkcs11 operation?
- If this is normal, is it ok to use Cryptoki and PKCS11 without calling C_InitToken(), C_InitPIN(), C_Login()? Or is there any concern point?

**Comment by coach-bin** [comment]
found a related stuff from PKCS#11 spec:

2.4. Users
Only the normal user is allowed access to private objects on the token, and that access is granted only after the normal user has been authenticated.  Some tokens may also require that a user be authenticated before any cryptographic function can be performed on the token, whether or not it involves private objects. 
--> With testing, I understood that OPTEE PKCS11 token requires normal user authentication only for a private object, and this doesn't seem to violate the PKCS#11 spec

**Comment by etienne-lms** [comment]
Private objects are object with `CKA_PRIVATE` boolean attribute set to true.
Private keys are not always private objects.
OP-TEE pkcs11 TA uses a helper function `check_access_attrs_against_token()` to check if an object is reachable or can be created according to session state.
https://github.com/OP-TEE/optee_os/blob/65fb909241a7b8b0d23343fc34de22c998c3beed/ta/pkcs11/src/pkcs11_attributes.c#L934-L961

**Comment by coach-bin** [comment]
@etienne-lms Thanks for the info. From this I learned that class objects can also be private objects.
