### ISSUE TITLE
What is the status on 64bit TEE_Time port for 32bit builds?

### ISSUE THREAD

**Issue by xnox** [OP-TEE/optee_os#6325]
OP-TEE is used on Ubuntu armhf & arm64

What is the status on porting TEE_Time to 64bit?
Does it matter?

I cannot tell if 32bit time is simply used as a seed, or if it significant to not overflow. I am working on projects that desire 10 year support, and if things overrun a bit, seems like trivial to have these devices operational in 2038.

**Comment by jforissier** [comment]
Hi @xnox,

`TEE_Time::seconds` is `uint32_t` (note that is is **unsigned** not **signed**) so as mentioned in the GlobalPlatform specification: "When used to return a time value, this structure can represent times up to 06:28:15 UTC on Sun, 7 February 2106, where the zero value represents midnight on January 1, 1970, UTC".

**Comment by xnox** [comment]
2106 problem is better. Shame I might still be around to deal with it.
