### ISSUE TITLE
Probe sequence result: 0x80000000

### ISSUE THREAD

**Issue by symdeb** [OP-TEE/optee_os#6337]
Attempting to adopt the 157A-DK1 device tree onto a custom board with the same MPU, with the goal of minimal a boot-able board, that is only needing to boot from SD and  UART4 as console with OPTEE  (either with or without pager) the boot so far results in:
```
I/TC: Early console on UART#4
I/TC: 
I/TC: Pager is enabled. Hashes: 2976 bytes
I/TC: Pager pool size: 96kB
I/TC: Embedded DTB found
I/TC: OP-TEE version: Unknown_3.19 (gcc version 12.2.0 (GCC)) #1 Tue Oct  3 14:45:05 UTC 2023 arm
I/TC: WARNING: This OP-TEE configuration might be insecure!
I/TC: WARNING: Please check https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html
I/TC: Primary CPU initializing
I/TC: Platform stm32mp1: flavor PLATFORM_FLAVOR - DT stm32mp157a-dk1.dts
I/TC: DTB enables console (non-secure)
I/TC: HUK unlocked
E/TC:0 0 probe_dt_drivers:750 **Probe sequence result: 0x80000000**
E/TC:0 0 Panic
```
What does this error mean and what to look for and change in the device trees ?

**Comment by etienne-lms** [comment]
0x80000000 is `TEE_ERROR_DEFER_DRIVER_INIT`. Some driver failed to initialize.
Which driver? You would need more trace verbosity (set `CFG_TEE_CORE_LOG_LEVEL` to 3 or 4).
Again, OP-TEE github issues may not help you much as your image is based on OP-TEE OS fork from ST. There are ST forums for [STM32MPU embedded software](https://community.st.com/t5/stm32-mpus-embedded-software/bd-p/mpu-embedded-software-forum) that could help.

**Comment by symdeb** [comment]
Thank you for the hint. Confirmed & closed. This was  a (known) bug in the ST code but not straightforward to find the information about it.

**Comment by symdeb** [comment]
@maxswjeon  Try the ECO 5.02 update. This error seemed to be caused by several things, including the UART timeout issue. I build all .dts file based from the plain CubeMX file, so mistakes in those could have been one of them. The reason for your error might be totally different.  Likely it is  related what you have in  the .dts file for OPTEE.

**Comment by DanielMartensson** [comment]
> @maxswjeon Try the ECO 5.02 update. This error seemed to be caused by several things, including the UART timeout issue. I build all .dts file based from the plain CubeMX file, so mistakes in those could have been one of them. The reason for your error might be totally different. Likely it is related what you have in the .dts file for OPTEE.

@symdeb Hello! I got the same bug as well. ST seems to not having solve that bug yet. 
I have a question: What do you mean with ECO 5.02 update? Where can I find that?

**Comment by i-tesetd-it-no-problem** [comment]
@symdeb "Hello, I have encountered the same issue. Could you please share how you resolved it? Could I take a look at your device tree for reference?"

If you need any further adjustments, feel free to ask!
