### ISSUE TITLE
how to link a static library with driver code 

### ISSUE THREAD

**Issue by Amit-Radur** [OP-TEE/optee_os#6346]
I have a static library file "libxyz.a" , that I am trying to link to tee.bin. But seeing "undefined reference to `hw_initialize' " while compiling. Function "hw_initialize" is part of static library.

Placed the static library in core/lib/libxyz/libxyz.a

From the core/drivers/abc/abc_hw.c, making call to hw_initialize function, and core/drivers/abc/sub.mk look like:

```make
srcs-y += abc_hw.c

libdirs += ../../lib/libxyz
libnames += xyz

LDFLAGS +=-L../../lib/libxyz/ -llibxyz.a
```

How do I properly link this external library with driver code ?

**Comment by jforissier** [comment]
> ```make
> srcs-y += abc_hw.c
> ```

OK

> ```make
> libdirs += ../../lib/libxyz
> libnames += xyz
> ```

No, libdirs and libnames are used internally to *create* a static library, not to *use* an external one.

> ```make
> LDFLAGS +=-L../../lib/libxyz/ -llibxyz.a
> ```

That could work... are you sure you gave the proper path? It should be relative to the top project directory, where the main Makefile resides. You may also give an absolute or relative path to the library file (libxyz.a) instead of -L / -l.

> How do I properly link this external library with driver code ?

LDFLAGS should work but you may also be able to leverage this variable which has a slightly more appropriate name I think:
```
core/arch/arm/kernel/link.mk:42:link-ldadd += $(ldflags-external)  
```

`ldflags-external` is not used currently. Can you try `make ... ldflags-external=/path/to/libxyz.a`? or alternatively, setting `ldflags-external := /path/to/libxyz.a` (or a proper relative path, relative to the top level directory) in `core/drivers/abc/sub.mk`.

**Comment by jforissier** [comment]
Note however that linking an external library is usually a bad idea due the issues it can cause with multiple architectures and incompatible compile flags (32 bit vs 64 bit TEE binary, BTI support...).

**Comment by Amit-Radur** [comment]
@jforissier , thanks for suggesting ldflags-external, did try this, and seeing it trying to link to libxyz.a but within the libxyz.a, some of references it could not find, and getting these errors:

aarch64-none-linux-gnu-ld.bfd: core/lib/libxyz/libxyz.a(xsm.c.o): in function `xsm_msg_params':
xsm.c:(.text.xsm_msg_params+0xe8): undefined reference to `xsm_alloc'

xsm_alloc is part of object file contained into libxyz.a

ldflags-external := core/lib/libxyz/libxyz.a

Another observation is , when I move abc_hw.c to core/lib/libxyz/ , it compile without any linking issue.

# cat core/lib/libxyz/sub.mk

srcs-y += abc_hw.c

**Comment by jforissier** [comment]
OK so there is some link order issue. The library should come later on the link line, or maybe use `--start-group .. --end-group`.

**Comment by Amit-Radur** [comment]
@jforissier, did you mean to surround ldflags-external := core/lib/libxyz/libxyz.a with --start-group .. --end-group ?

Something like:
 --start-group
ldflags-external := core/lib/libxyz/libxyz.a
 --end-group

**Comment by jforissier** [comment]
You need to surround more things, the object files too. What is between start and end group the linker will make several passes to resolve symbols.

**Comment by Amit-Radur** [comment]
@jforissier Okay, this is something I tried in core/drivers/abc/sub.mk

srcs-y += abc_hw.c
ldflags-external := core/kernel/libxyz.a
link-ldadd += --start-group xsm.o $(ldflags-external) --end-group

wanted to at least see link dependency for xsm.o gets removed but I see same linking issue.

aarch64-none-linux-gnu-ld.bfd: core/lib/libxyz/libxyz.a(xsm.c.o): in function xsm_msg_params': xsm.c:(.text.xsm_msg_params+0xe8): undefined reference to xsm_alloc'
