### ISSUE TITLE
Question about tee_supplicant log

### ISSUE THREAD

**Issue by coach-bin** [OP-TEE/optee_os#6357]
I set CFG_TEE_SUPP_LOG_LEVEL to 4.
However, DMSG only outputs to /data/tee/teec.log and not to the uart console.
(Exactly speaking, only the first DMSG is output to the console) - see console output below)
How do I output all DMSGs to the console?

[console output]
\# tee-supplicant -d
DBG [1413] TSUP:plugin_load_all:162: loading the <test> plugin were successful
\# cat /data/tee/teec.log
DBG [1413] TSUP:plugin_load_all:162: loading the <test> plugin were successful
DBG [1414] TSUP:open_dev:468: using device "/dev/teepriv0"
DBG [1414] TSUP:process_one_request:624: looping

**Comment by jforissier** [comment]
Hello @coach-bin,

When `tee-supplicant` is started with the `-d` argument, it is detached as a daemon and thus the console is closed. If you want console messages you may start `tee-supplicant` without `-d` (and put it in the background of the current shell with `&` if you wish: `tee-supplicant&`).

**Comment by coach-bin** [comment]
@jforissier Thanks for your answer :)
