### ISSUE TITLE
Integrate OpenSSL in optee_os

### ISSUE THREAD

**Issue by PrithviAPai** [OP-TEE/optee_os#6366]
Is there any provision from optee to allow openssl library to be integrated with optee_os. 
The reason for integration is OpenSSL has FIPS certified versions which can be used for crypto operations.

@jforissier can you please comment on this ?

**Comment by jforissier** [comment]
No change since last time you asked (#5884).

**Comment by PrithviAPai** [comment]
Thank you

**Comment by PrithviAPai** [comment]
A follow up question on the same @jforissier. Is there any document to help OP-TEE users on how to get mbedTLS in OP-TEE FIPS certifiable ?

**Comment by jforissier** [comment]
> A follow up question on the same @jforissier. Is there any document to help OP-TEE users on how to get mbedTLS in OP-TEE FIPS certifiable ?

No, sorry. Note that OP-TEE has now switched to MBedTLS 3.4.0.

**Comment by PrithviAPai** [comment]
Thank you for your response.
