### ISSUE TITLE
Assertion failed when core ASLR is enabled

### ISSUE THREAD

**Issue by tl455047** [OP-TEE/optee_os#6370]
Hi, We're running OP-TEE-3.21.0 on our board, which is armv8, aarch64 CPU, ```CFG_LPAE_ADDR_SPACE_BITS=32```.

We tried to enable core ASLR, our ```TEE_RAM_START``` is ```0x43041000```, ```TEE_RAM_SIZE``` is ```0xfaf000```, we overridden ```plat_get_aslr_seed```, and returned seed using HW RNG. At most time it worked fine, but somtimes we encountered assertion ```assert(user_va_idx != -1) (core/arch/arm/mm/core_mmu_lpae.c)``` failed in some boot.
Following is our boot log：
```
...
D/TC:0   init_mem_map:1245 Mapping core at 0xbfe01000 offs 0x7cdc0000
D/TC:0   dump_mmap_table:805 type IDENTITY_MAP_RX va 0x43041000..0x43042fff pa 0x43041000..0x43042fff size 0x00002000 (smallpg)
D/TC:0   dump_mmap_table:805 type IO_SEC       va 0xbbc00000..0xbbdfffff pa 0x0c000000..0x0c1fffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:805 type IO_SEC       va 0xbbe00000..0xbbffffff pa 0x08000000..0x081fffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:805 type RES_VASPACE  va 0xbc000000..0xbc9fffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0   dump_mmap_table:805 type SHM_VASPACE  va 0xbcc00000..0xbebfffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0   dump_mmap_table:805 type NSEC_SHM     va 0xbee41000..0xbf040fff pa 0x43ff0000..0x441effff size 0x00200000 (smallpg)
D/TC:0   dump_mmap_table:805 type TA_RAM       va 0xbf041000..0xbfdeffff pa 0x43241000..0x43feffff size 0x00daf000 (smallpg)
...
D/TC:0   dump_mmap_table:805 type TEE_RAM_RX   va 0xbfe01000..0xbfe72fff pa 0x43041000..0x430b2fff size 0x00072000 (smallpg)
D/TC:0   dump_mmap_table:805 type TEE_RAM_RW   va 0xbfe73000..0xc0000fff pa 0x430b3000..0x43240fff size 0x0018e000 (smallpg)
...
E/TC:0   assertion 'user_va_idx != -1' failed at core/arch/arm/mm/core_mmu_lpae.c:714 <set_user_va_idx>
E/TC:0   Panic at core/kernel/assert.c:28 <_assert_break>
```
We guess this is because when new base calculated from ASLR seed uses 3 entries in L1 table, user va cannot find an empty entry in L1 table, which causes assertion failed.

We restrict the seed range, prevent new base from exceeding ```0xc0000000```, everything seems to be fine, we wonder is there a general way to solve this problem?

**Comment by jenswi-linaro** [comment]
I'm surprised I haven't encountered this on a regular basis. Anyway, the `IDENTITY_MAP_RX` must be located where it is so that one can't be moved. The problem in your example layout is that the selected memory range spans over the two remaining top-level entries.

 We should perhaps pick the `user_va_idx` (and exclude that entry from ASLR selection) before we use the seed to assign the rest of the memory layout.

**Comment by tl455047** [comment]
Thanks for your reply, picking ```user_va_idx``` before assigning other memory layout can solve the assertion failed. I'm somewhat confused that if the memory layout still needs more than 2 top-level entries, will this cause problem? In our memory layout, this situation happens when ASLR seed exceeds certain value.

**Comment by jenswi-linaro** [comment]
`init_mem_map()` will try a few different memory locations before giving up. So if there's an overlap with the top-level entry selected by `user_va_idx` it should just try another location that hopefully doesn't cause a conflict. We can tweak this further if needed, I just picked something simple that worked well enough in my tests.

**Comment by tl455047** [comment]
Get it, if we exclude the ```user_va_idx``` entry before ASLR selection,   ```init_mem_map()``` should find a new location that needs only two top-level entries to map the memory layout.
