### ISSUE TITLE
I wonder where exactly the function TA_InvokeCommandEntryPoint is called.

### ISSUE THREAD

**Issue by nolzaheo** [OP-TEE/optee_os#6382]
Hello all, the picture below says that TA Interfaces are called by the Trusted Core Framework. Then, is there any exact code or github link which includes calling TA_InvokeCommandEntryPoint()?

![image](https://github.com/OP-TEE/optee_os/assets/55793819/be0e2b5d-dd50-4a13-bb45-fc1f7b3a4db8)

**Comment by etienne-lms** [comment]
You can grep `UTEE_ENTRY_FUNC_INVOKE_COMMAND` in optee_os source tree.
This command is called from _core/kernel/user_ta.c_, where trusted core framework switches to secure user mode execution and branches to `__utee_entry()` (_lib/libutee/user_ta_entry.c_) where the command is converted into a call to `TA_InvokeCommandEntryPoint()`.

**Comment by nolzaheo** [comment]
This helped me a lot. Thanks :)
