### ISSUE TITLE
ARMv9 Support

### ISSUE THREAD

**Issue by sichunqin** [OP-TEE/optee_os#6396]
Does optee_os support Cortext A510 (ARMv9)？ 
I can't find any related information about OPTEE ARMv9 support. Looking forward to your reply! Thanks.

**Comment by jenswi-linaro** [comment]
No, I don't think we have support for any Armv9 platform if you don't count QEMU. We're using the "max" CPU with QEMU so we by default get all supported features, it's possible it has some v9 feature enabled even in our test setup.

**Comment by sichunqin** [comment]
@jenswi-linaro Thanks for reply. You mean QEMU can support ARMv9 OPTEE? I can see the QEMU ARMv8 set up, but not see ARMv9 set up.

**Comment by jenswi-linaro** [comment]
My understanding is that Armv9 isn't so different from Armv8 unless the new features are enabled. However, don't take my word for it.

**Comment by rejoiceliberty** [comment]
Hello, experts,
If the OP-TEE supports ARMv9, what changes need to be made, such as TZASC and GIC adaptation? Are there any other changes to be made? When will OP-TEE start supporting ARMv9?

**Comment by jbech-linaro** [comment]
> You mean QEMU can support ARMv9 OPTEE?

Not exactly an answer to that particular question, but Arm did provide some updates also covering QEMU at the recent Linaro connect, see:
- https://resources.linaro.org/en/resource/oZKiZZFUGEWdroBhh3kFEM
- https://resources.linaro.org/en/resource/47Lkk6eqrHgJh5zGBDvwGX

At the first link, they mention QEMU as well. It's probably worth watching the video as well for context.

**Comment by jbech-linaro** [comment]
> When will OP-TEE start supporting ARMv9?

We don't know, no plans made for that as of now. I guess that when we get hardware (or like said here, QEMU/FVP as a stable setup), we'll most likely start making plans for it. But as of now, no plans.
