### ISSUE TITLE
Create a pull request with library files

### ISSUE THREAD

**Issue by liang-yan-yu** [OP-TEE/optee_os#6397]
I am a software engineer from Macronix. We would like to create a pull request to add driver support for our secure flash products in OP-TEE. But, some of code logic is confidential now due to our company's policy. I am wondering that is it possible to submit a pull request with some source files compiled in library format (like .a file)?

**Comment by jforissier** [comment]
Helle @liang-yan-yu,

> I am wondering that is it possible to submit a pull request with some source files compiled in library format (like .a file)?

No, we do not want such binary files in the source repository for several reasons (they are difficult to maintain, may raise licensing issues...). But you are welcome to update the makefiles as necessary to link against your library file in an external location.

**Comment by liang-yan-yu** [comment]
Hi @jforissier ,

> But you are welcome to update the makefiles as necessary to link against your library file in an external location.

Do you mean that I can submit a pull request with the available source files only (.c .h and makefiles) and provide the library files in other way (like download from our website)?

**Comment by jenswi-linaro** [comment]
Compare with `CFG_NXP_SE05X_PLUG_AND_TRUST`.

**Comment by liang-yan-yu** [comment]
Thanks! I'll take a look on it.
