### ISSUE TITLE
How can I load a TensorFlow model in OP-TEE? What are the steps involved and any specific considerations I need to keep in mind?

### ISSUE THREAD

**Issue by pluto-llf** [OP-TEE/optee_os#6398]

**Comment by jbech-linaro** [comment]
Too vague question. But, in short, there is no support to run TensorFlow in OP-TEE. If your question is about store and load a model (as a binary), then it's the `TEE_CreatePersistentObject(...)` that you're looking for.

**Comment by pluto-llf** [comment]
> Too vague question. But, in short, there is no support to run TensorFlow in OP-TEE. If your question is about store and load a model (as a binary), then it's the `TEE_CreatePersistentObject(...)` that you're looking for.

OK，i got it ~Thanks
