### ISSUE TITLE
How to include openssl on user_ta.c?

### ISSUE THREAD

**Issue by nolzaheo** [OP-TEE/optee_os#6403]
Like this issue (https://github.com/OP-TEE/optee_os/issues/5278),
I need to include openssl on optee_os/core/kernel/user_ta.c.
I've tried to edit buildroot/boot/optee-os/optee-os.mk, adding 'openssl' in OPTEE_OS_DEPENDENCIES like below but it didn't work.

![image](https://github.com/OP-TEE/optee_os/assets/55793819/29929b74-e736-4d09-a159-b8fb7653a872)

1. Is there any way to include openssl in 'user_ta.c' in kernel secure part?
(If it's not, what about mbedtls?)

2. Also, I want to know if it is possible to open file in 'user_ta.c' using FILE object type and open() function defined in <stdio.h>
ex) FILE *cert_file = fopen("/mnt/host/trusted-firmware-a/build/qemu/debug/tb_fw.crt");

Thank you in advance for your attention to this matter.

**Comment by J-StrawHat** [comment]
May I ask if you have solved this problem?

**Comment by J-StrawHat** [comment]
Yes, I have found it. Thank you very much for your prompt reply !
