### ISSUE TITLE
Whether to support pkcs11 AES_GCM

### ISSUE THREAD

**Issue by 408419237** [OP-TEE/optee_os#6406]
HI TEAM:
              Excuse me, whether to support PKCS11 AES_GCM？
              I can't find any related information about PKCS11 AES_GCM support. 
              Has it now supported the protocol of PKCS11 3.1 version?
              Looking forward to your reply! Thanks.

**Comment by maroueneboubakri** [comment]
Hi @etienne-lms,

+1 for that request, this is highly valuable for many use-cases, for example for usage with Alexa enabled-devices, [according to the documentation](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/hardware-security-module.html),  the AVS Device SDK uses AES-GCM encryption to protect sensitive information. To maintain security, only manage your main encryption key with HSM and make sure it's not accessible from anywhere outside of your SDK configuration.

Best
Maro

**Comment by etienne-lms** [comment]
Sorry, AES-GCM is currently not supported by OP-TEE pkcs11 TA.

Be warned that if you want this support to be merged soon, I fear you'll need to find some contributors to help. I can work on that but I can't tell when it will be ready.

There is a draft version for AES-CCM and AES-GCM support in the pkcs11 TA in my repo that may help: see commit f486bcfc650beab10a036a9f19adc4131b5a38c3 from my old [sks-to-pkcs11](https://github.com/etienne-lms/optee_os/commits/sks-to-pkcs11) branch. There are also some patches on my optee_test repo to test the feature: [1e847b](https://github.com/etienne-lms/optee_test/commit/1e847b03a2df60241bccd417a26b149f29479125) + [999236](https://github.com/etienne-lms/optee_test/commit/9992365aeae4f6a05b08523cab1f527742fbce93). The implementation was drafty, not reviewed by peers and not tested enough. I remember some corner case input arguments made to TA to crash (invalid AE parameters not sufficiently sanitized). In case it helps.

**Comment by moose-rivieh** [comment]
+1 for adding AES-GCM support.

**Comment by 408419237** [comment]
> Sorry, AES-GCM is currently not supported by OP-TEE pkcs11 TA.
> 
> Be warned that if you want this support to be merged soon, I fear you'll need to find some contributors to help. I can work on that but I can't tell when it will be ready.
> 
> There is a draft version for AES-CCM and AES-GCM support in the pkcs11 TA in my repo that may help: see commit [f486bcf](https://github.com/OP-TEE/optee_os/commit/f486bcfc650beab10a036a9f19adc4131b5a38c3) from my old [sks-to-pkcs11](https://github.com/etienne-lms/optee_os/commits/sks-to-pkcs11) branch. There are also some patches on my optee_test repo to test the feature: [1e847b](https://github.com/etienne-lms/optee_test/commit/1e847b03a2df60241bccd417a26b149f29479125) + [999236](https://github.com/etienne-lms/optee_test/commit/9992365aeae4f6a05b08523cab1f527742fbce93). The implementation was drafty, not reviewed by peers and not tested enough. I remember some corner case input arguments made to TA to crash (invalid AE parameters not sufficiently sanitized). In case it helps.

thanks.

**Comment by maroueneboubakri** [comment]
> Sorry, AES-GCM is currently not supported by OP-TEE pkcs11 TA.
> 
> Be warned that if you want this support to be merged soon, I fear you'll need to find some contributors to help. I can work on that but I can't tell when it will be ready.
> 
> There is a draft version for AES-CCM and AES-GCM support in the pkcs11 TA in my repo that may help: see commit [f486bcf](https://github.com/OP-TEE/optee_os/commit/f486bcfc650beab10a036a9f19adc4131b5a38c3) from my old [sks-to-pkcs11](https://github.com/etienne-lms/optee_os/commits/sks-to-pkcs11) branch. There are also some patches on my optee_test repo to test the feature: [1e847b](https://github.com/etienne-lms/optee_test/commit/1e847b03a2df60241bccd417a26b149f29479125) + [999236](https://github.com/etienne-lms/optee_test/commit/9992365aeae4f6a05b08523cab1f527742fbce93). The implementation was drafty, not reviewed by peers and not tested enough. I remember some corner case input arguments made to TA to crash (invalid AE parameters not sufficiently sanitized). In case it helps.

Thank you @etienne-lms , I'll try them and open a PR.

**Comment by etienne-lms** [comment]
Implemented by P-R #6467.

**Comment by etienne-lms** [comment]
Still under development/review (https://github.com/OP-TEE/optee_os/pull/6467 + https://github.com/OP-TEE/optee_test/pull/720).

**Comment by moose-rivieh** [comment]
@etienne-lms, any update on this? Thx!

**Comment by etienne-lms** [comment]
https://github.com/OP-TEE/optee_os/pull/6467 seems stalled. The implementation looks good to me but for the one-shot operation that is not supported and needs to be.

**Comment by etienne-lms** [comment]
@maroueneboubakri, I had a look at the implementation and tried to progress on that topic. I have few findings. Would you mind if I create new P-Rs for optee_os and optee_test for implementation proposals for would supersede https://github.com/OP-TEE/optee_os/pull/6467 and https://github.com/OP-TEE/optee_test/pull/720?

I've also found test case to revealed an minor issue in optee_client, see https://github.com/OP-TEE/optee_client/pull/375.

**Comment by maroueneboubakri** [comment]
> I had a look at the implementation and tried to progress on that topic. I have few findings. @maroueneboubakri, would you mind if I create new P-Rs for optee_os and optee_test for implementation proposals that would supersede #6467 and [OP-TEE/optee_test#720](https://github.com/OP-TEE/optee_test/pull/720)?
> 
> I've also found test cases that revealed an minor issue in optee_client, see [OP-TEE/optee_client#375](https://github.com/OP-TEE/optee_client/pull/375).

@etienne-lms Sure !

**Comment by etienne-lms** [comment]
New implementation proposal through P-Rs https://github.com/OP-TEE/optee_os/pull/6683, https://github.com/OP-TEE/optee_client/pull/375 and https://github.com/OP-TEE/optee_test/pull/730.

**Comment by etienne-lms** [comment]
@408419237, @moose-rivieh, this issue is expected to be solved through the P-Rs mentioned above. We'll close this issue. Please create another issue if you face any problems related to this feature.
