### ISSUE TITLE
Segmentation fault in pkcs11 TA 

### ISSUE THREAD

**Issue by guilhermeeec** [OP-TEE/optee_os#6407]
Hello,
I was trying to follow the [Linux userland integration](https://optee.readthedocs.io/en/latest/building/userland_integration.html#linux-userland-integration) examples, in Latest release. However, I'm having trouble running the command:
`# OPENSSL_CONF=optee_hsm.conf openssl req -new -engine pkcs11 -keyform engine -key label_mykey -subj "/CN=My CSR" -out mykey_csr.pem
engine "pkcs11" set.` 

The screenshot bellow presents the error.
![Screenshot from 2023-10-23 13-27-31](https://github.com/OP-TEE/optee_os/assets/56051028/8ba5eaf0-1fac-4985-91c6-5ef43bc4c3f5)

For compilation for the QEMU v8 plattform, I used the following Makefile options:
`make run BR2_PACKAGE_OPENSC=y BR2_PACKAGE_LIBOPENSSL=y BR2_PACKAGE_LIBOPENSSL_BIN=y BR2_PACKAGE_LIBP11=y QEMU_VIRTFS_ENABLE=y QEMU_USERNET_ENABLE=y QEMU_VIRTFS_HOST_DIR=/optee/SHARED/`

**Comment by embetrix** [comment]
@guilhermeeec : how did you create/imported the keys ? how your openssl config file looks like ?

**Comment by guilhermeeec** [comment]
The steps for initializing the token in slot 0 were identical to the tutorial.
The command for generating the key is:
`# p11 -l --pin 12345 --keypairgen --key-type EC:prime256v1 --label mykey`
The configuration file `/root/optee_hsm.conf` is as follows:
![image](https://github.com/OP-TEE/optee_os/assets/56051028/db551b39-0a17-405e-9e38-c975f7a94bb7)
The command for setting the CSR is:
`OPENSSL_CONF=optee_hsm.conf openssl req -new -engine pkcs11 -keyform engine -key label_mykey -subj "/CN=My CSR" -out mykey_csr.pem`

**Comment by embetrix** [comment]
@guilhermeeec : wekk the key label **label_mykey** is different from the label you created **mykey** !!

**Comment by guilhermeeec** [comment]
Thank you for your help. This solved the segmentation fault. However, I am still having trouble with the tutorial
![image](https://github.com/OP-TEE/optee_os/assets/56051028/fd66af5b-0245-404c-8e04-8c95bbc5d318)
