### ISSUE TITLE
Is there a max value of TA sessions?

### ISSUE THREAD

**Issue by qianfei11** [OP-TEE/optee_os#6408]
Hi experts, 

I wrote the following code to test how many sessions can be exists at one time (I assume the value of `arg->session` will gradually accumulate): 

```
static uint32_t max_session_id = 0;

/*
 * If tee_entry_std() is overridden, it's still supposed to call this
 * function.
 */
TEE_Result __tee_entry_std(struct optee_msg_arg *arg, uint32_t num_params)
{
	TEE_Result res = TEE_SUCCESS;

	DMSG("max_session_id = %d, arg->session = %d\n", max_session_id, arg->session);
	if (arg->session > max_session_id)
	{
		max_session_id = arg->session;
		DMSG("max_session_id = %d\n", max_session_id);
	}
...
```

After I ran the `xtest` command, the `max_session_id` is 10, is optee os currently running 10 TA sessions at a time? 

```
D/TC:0 0 __tee_entry_std:544 max_session_id = 10, arg->session = 10
```

And in the configuration, `CFG_TEE_CORE_NB_CORE` is 4, `CFG_NUM_THREADS` is 2 and `QEMU_SMP` is 4. It seems that the number of sessions is not related to these macros?

Here are my questions: 

1. Is session id increased by number as the following logic?

```
for (int i = 0; i < max_size; i++)
{
  if (sessions[i].is_available)
  {
    session_id = i;
    break;
  }
}
```

2. How many sessions can be running at the same time?
3. Are these macros (`CFG_TEE_CORE_NB_CORE`, `CFG_NUM_THREADS`, `QEMU_SMP` ) related to the currently running sessions?
4. Is there a max value of session id? or just max value of a 32 bit integer?

**Comment by etienne-lms** [comment]
Hi @qianfei11,
FYI there is no explicit limits on how many sessions can OP-TEE services support. It mainly depends on the memory allocation pools of OP-TEE (core heap + TA RAM).
`QEMU_SMP` is unrelated, it set the number of CPU emulated with QEMU.
`CFG_TEE_CORE_NB_CORE` is unrelated, there can be far more sessions opened than the number of CPUs OP-TEE supports.
`CFG_NUM_THREADS` is unrelated. A TEE thread is allocated when a Linux thread request an OP-TEE service and is released once the service execution is completed. `TEEC_OpenSession()` is a service. `TEE_InvokeCommand()` is another service. Therefore there can be far more sessions opened than the number of thread contexts provisioned in OP-TEE core.

**Comment by qianfei11** [comment]
Thanks for replying. I should close the issue.
