### ISSUE TITLE
How can I include openssl in 'user_ta.c' of kernel secure part?

### ISSUE THREAD

**Issue by nolzaheo** [OP-TEE/optee_os#6411]
Like this issue (https://github.com/OP-TEE/optee_os/issues/5278),
I need to include openssl on optee_os/core/kernel/user_ta.c.
I've tried to edit buildroot/boot/optee-os/optee-os.mk, adding 'openssl' in OPTEE_OS_DEPENDENCIES like below but it didn't work.

![image](https://github.com/OP-TEE/optee_os/assets/55793819/29929b74-e736-4d09-a159-b8fb7653a872)

1. Is there any way to include openssl in 'user_ta.c' in kernel secure part?
(If it's not, what about mbedtls?)

2. Also, I want to know if it is possible to open file in 'user_ta.c' using FILE object type and open() function defined in <stdio.h>
ex) FILE *cert_file = fopen("/mnt/host/trusted-firmware-a/build/qemu/debug/tb_fw.crt");

Thank you in advance for your attention to this matter.

**Comment by etienne-lms** [comment]
1: openSSL is not supported in OP-TEE OS. On the other hand, MbedTLS is supported, both from OP-TEE core and from OP-TEE Trusted Applications.

2: OP-TEE OS does not provide a Posix filesystem API. OP-TEE OS does not access Linux filesystems. 
That said, you can implement a [TEE supplicant plugin](https://optee.readthedocs.io/en/latest/architecture/globalplatform_api.html#loadable-plugins-framework) to have OP-TEE accessing files from a Linux filesystem through **tee-supplicant** Linux application. Note however that, from OP-TEE perspective, such files are not secure.

**Comment by nolzaheo** [comment]
Thanks always for your help!
