### ISSUE TITLE
Question regarding the convention followed for memory permission checks in syscalls

### ISSUE THREAD

**Issue by karthikbhata97** [OP-TEE/optee_os#6413]
I have been auditing the source code to understand how the permission checks are implemented when a TA performs a syscall and passes a pointer to the syscall argument. I made following observation:
- In most places one of the variants of `copy_from_user` / `copy_to_user` is used (which internally uses `vm_check_access_rights` for checks).
  - Eg: https://github.com/OP-TEE/optee_os/blob/f7acc214e71264263a6a80191d024228e2a469b7/core/tee/tee_svc.c#L995
- But there are also instances where a buffer is directly checked for permissions using `vm_check_access_rights` and then passed to subsequent functions which will then perform `memcpy`.
  - Eg: https://github.com/OP-TEE/optee_os/blob/f7acc214e71264263a6a80191d024228e2a469b7/core/tee/tee_svc_cryp.c#L4393
  - I also notice that in this example, the buffer is then passed to `libtomcrypt`, which populates / consumes it.

So I wanted to understand,
1.  Is there any specific convention followed when implementing a new syscall. 
2.  Is there a reason to not standardize the usage to the existing `copy_to/from_user` wrappers across all syscalls?

**Comment by jenswi-linaro** [comment]
`copy_from_user()`, `copy_to_user()`, and the `bb_*user*()` functions should normally be used when accessing user space memory, but there are exceptions, for example when potentially large buffers are passed for hashing or encryption. There are a few other remaining cases where I believe these helper functions should be used.

You should generally not add a new syscall, we usually add another function to a PTA instead. However, there are exceptions to that too if there's a good argument for it.
