### ISSUE TITLE
How does OPTEE use standard C libraries?

### ISSUE THREAD

**Issue by qianfei11** [OP-TEE/optee_os#6419]
Hi experts, 

I have searched for the ways of how a user TA switching to kernel space, found out that `ldelf` and `libutee` have some SVC system calls that trap into the kernel space. But there are also some normal world functions like `malloc`, `printf`, etc. And I cant find any system call (`mmap`, `write`) may be related to.

I found that OPTEE use [bget](https://www.fourmilab.ch/bget/) to manage heap memory, so are these functions only executing in user space?

Also, I manually traced the `DMSG` macro (`DMSG`->`trace_printf_helper`->`trace_printf`->`__printf`), and still cant find any clues. And I made an assumption that these `print` functions use MMIO to write some tty registers to enable the output, is this assumption possible?

These are my questions:

1. Does OPTEE make its own implementation of standard C libraries?
2. Is there any other ways (other than `ldelf` and `libutee` syscalls) can let TA switching to TOS?

**Comment by etienne-lms** [comment]
> Does OPTEE make its own implementation of standard C libraries?

Yes, see [_lib/libutils_](https://github.com/OP-TEE/optee_os/tree/master/lib/libutils).
Note: we should have a word on think in the [documentation](https://optee.readthedocs.io/en/latest/architecture/libraries.html#libraries). Help and patches in [optee_docs](https://github.com/OP-TEE/optee_docs) are welcome!

> Is there any other ways (other than ldelf and libutee syscalls) can let TA switching to TOS?

Have a look at OP-TEE [Pseudo-TAs](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#pseudo-trusted-applications). It's a  flexible way to expose specific core services to TAs, based on system calls but offering higher interface abstraction.

**Comment by qianfei11** [comment]
> > Does OPTEE make its own implementation of standard C libraries?
> 
> Yes, see [_lib/libutils_](https://github.com/OP-TEE/optee_os/tree/master/lib/libutils). Note: we should have a word on think in the [documentation](https://optee.readthedocs.io/en/latest/architecture/libraries.html#libraries). Help and patches in [optee_docs](https://github.com/OP-TEE/optee_docs) are welcome!
> 
> > Is there any other ways (other than ldelf and libutee syscalls) can let TA switching to TOS?
> 
> Have a look at OP-TEE [Pseudo-TAs](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#pseudo-trusted-applications). It's a flexible way to expose specific core services to TAs, based on system calls but offering higher interface abstraction.

Thanks for replying! This helps me a lot!
