### ISSUE TITLE
When connecting between TAs, I can't check the memory status of each TA.

### ISSUE THREAD

**Issue by ydonghyuk** [OP-TEE/optee_os#6420]
When checking the memory status through CFG_TA_STATS setting and xtest --stats --ta,
If TA1 and TA2 are connected (TA1 -> TA2), the memory status of TA2 is not confirmed.
Is it really like this?

ta1(xxx..)
         panicked(0) -- True if TA has panicked
         session number(1)
         Heap Status:
                 Bytes allocated: 128
                 Max bytes allocated: 256
                 Size of pool: 32768
                 Number of failed allocations: 0
                 Size of large allocation failure: 0
                 Total bytes allocated at that failure: 0

ta2(yyy...)
         panicked(0) -- True if TA has panicked
         session number(0)
         Heap Status:
                 Bytes allocated: 0
                 Max bytes allocated: 0
                 Size of pool: 0
                 Number of failed allocations: 0
                 Size of large allocation failure: 0
                 Total bytes allocated at that failure: 0

**Comment by ydonghyuk** [comment]
If anyone can help in any way, please leave a comment.

**Comment by etienne-lms** [comment]
You mean you queried TA2 stats at the same time TA1 was invoking TA2? Or maybe it is still initializing.
See the error cases in `[dump_ta_memstats()`](https://github.com/OP-TEE/optee_os/blob/4.0.0/core/kernel/tee_ta_manager.c#L802).

**Comment by ydonghyuk** [comment]
After connecting TA2 through TEE_OpenTASession from TA1,
Memory stats are being checked while TA2 is operating with TEE_InvokeTACommand.

**Comment by etienne-lms** [comment]
Getting stats from a TA goes through an invocation of the TA and that cannot be done while the TA is executing. I think you fall in the BUSY case. You need to wait the TA completes the command invocation.
