### ISSUE TITLE
mbedTLS as shared object 

### ISSUE THREAD

**Issue by PrithviAPai** [OP-TEE/optee_os#6427]
Hi Team,

As per my understanding, currently the applications using mbedTLS are linked statically with mbedTLS library. 
This is a bottleneck for OP-TEE users to get their applications FIPS certifiable. 
Is there any way to build mbedTLS as shared object ? So that FIPS boundary will be just restricted to the mbedTLS library instead of Trusted Application. 

Thanks,
Prithvi A Pai

**Comment by jforissier** [comment]
Hello @PrithviAPai,

> Is there any way to build mbedTLS as shared object ?

Yes. You may set `CFG_ULIBS_SHARED=y`, then all the user-space libraries will be built both as static (`.a`) and shared (`.so`) libraries. For MBedTLS, you will get: `libmbedtls.a`, `libmbedtls.so`, and `87bb6ae8-4b1d-49fe-9986-2b966132c309.ta` (the signed or signed+encrypted version of `libmbedtls.so`, loadable by OP-TEE).
