### ISSUE TITLE
OPTEE calling failure after system recovers from hiberation(STD)

### ISSUE THREAD

**Issue by VincentCui632** [OP-TEE/optee_os#6428]
I have  new project  for developping TEE in notebook. the system needs to support S4 (Hiberation/STD) in order to reduce the power consume.   
To make the design simplest, I follow the regular suspend flow as below:
1. the kernel implement suspend flow to freeze thread and store data in swap paritition. then enter into S3 mode
2. system wakeups by pressing poweron event, and boot into kernel as normal. and the TEE OS and Trusted firmware will initialize like in normal boot.

Once kernel recover all context,  I try to issue CA again, and it prompts the below error message. 
![image](https://github.com/OP-TEE/optee_os/assets/84758008/d13f0150-79b6-420f-912d-cc4f1dd573aa)

I know that the context of TEE-OS and TEE driver does not match new after system recovery...  I wonder to know if there is way to cleanup TEE driver before entering into S4 to make CA work after wakeup .

Thank you for your help .

**Comment by jenswi-linaro** [comment]
I'm not familiar with how much state the kernel saves during hibernation, but here it seems that not enough is saved. I believe that the open sessions and registered shared memory must be restored after hibernation.

**Comment by VincentCui632** [comment]
Hay Jneswi, there is a way to fix it I mentioned above..  it only needs to build TEE Driver in KO file instead of build-in method. I found that TEE OS could be communicated with CA successfully, and SHM could be reallocated in new session. 

But it seems to be good in normal work  mode.. but there is still some use case in which  the kernel needs to know whether there is some TA running in curretn session or not..  Is there a API or method to know status of TA or all session created ?

**Comment by jenswi-linaro** [comment]
It sounds a bit strange with the kernel module versus built-in, surely built-in must have a way to have its state saved.
Each session is opened to a TA, without a TA there shouldn't be a session. There's no kernel API for this, but it should be possible to extract sessions etc from the internal state of the driver.
