### ISSUE TITLE
invalid mask in core_mmu_v7.c:map_page_memarea() when pa is not alligned

### ISSUE THREAD

**Issue by patrickdelaunay** [OP-TEE/optee_os#643]
Hi,

I try to map not-aligned section and after some investigation 
I found issue in the function map_page_memarea()
invalid mask SMALL_PAGE_MASK is used and that cause issue when pa is not aligned
=> SECTION_MASK should be used

 	/* Fill in the entries */
 	while ((pg_idx * SMALL_PAGE_SIZE) <
 		(mm->size + (mm->pa & SECTION_MASK))) {
-		l2[pg_idx] = ((mm->pa & ~SMALL_PAGE_MASK) +
+		l2[pg_idx] = ((mm->pa & ~SECTION_MASK) +
 				pg_idx * SMALL_PAGE_SIZE) | attr;

core/arch/arm/mm/core_mmu_v7.c

entry parameter :
mm->pa=0x2ffc0000
mm->va=2ffc0000

when the function is executed, the memory map sees not correct (not 1 to 1)
  l2[191] = 0
  l2[192] = 0x30080416
  l2[193] = 0x30081416

with attached patch, the mapping is correct
  l2[191] = 0
  l2[192] = 2ffc0416
  l2[193] = 2ffc1416
....

[0001-core-armv7-solve-map-issue-for-unaligned-pa.patch.txt](https://github.com/OP-TEE/optee_os/files/119507/0001-core-armv7-solve-map-issue-for-unaligned-pa.patch.txt)

BR 

Patrick

**Comment by pascal-brand-st-dev** [comment]
Could you propose a pull-request?

**Comment by patrickdelaunay** [comment]
pull-request done : #645
https://github.com/OP-TEE/optee_os/pull/645

**Comment by pascal-brand-st** [comment]
is fixed by https://github.com/OP-TEE/optee_os/pull/645
