### ISSUE TITLE
Hafnium SPMC_AT_EL=2 panic

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#6435]
I am investigating an issue with the Hafnium CI job which is currently failing (see recently updated pull requests). Problems started to appear when I rebased the `linaro-swg/linux` branch `optee` onto upstream kernel v6.6 (from v6.2-rc3). That's commit  [a24278ea74b2](https://github.com/linaro-swg/linux/tree/a24278ea74b2b4beddbe0af01a27459cf35d86d7). On the other hand, [`wip/optee-v6.2-rc3`](https://github.com/linaro-swg/linux/tree/wip/optee-v6.2-rc3) works as expected.

Serial console output in `out/serial1.log` contains:
```
I/TC: Primary CPU switching to normal world boot
PANIC at PC : 0x000000000e0a13c4
```

**Comment by odeprez** [comment]
Hi with latest kernel I'm enabling HCX and disabling TRF build options:

diff --git a/qemu_v8.mk b/qemu_v8.mk
index 64e6ae7..f461f21 100644
--- a/qemu_v8.mk
+++ b/qemu_v8.mk
@@ -179,6 +179,7 @@ TF_A_FLAGS ?= \
        ENABLE_SME_FOR_SWD=1 \
        ENABLE_FEAT_FGT=2 \
+        ENABLE_FEAT_HCX=2 \
+       ENABLE_TRF_FOR_NS=0 \
        BL32_RAM_LOCATION=tdram \
        DEBUG=$(TF_A_DEBUG) \
        LOG_LEVEL=$(TF_A_LOGLVL)

See for some rationale:
https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/23399
https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/23648

**Comment by odeprez** [comment]
Hi I'm using TF-A+Hafnium tip of the tree, I guess inhibiting TRF might be required later when OP-TEE rebases to latest upstream.

**Comment by jforissier** [comment]
> Hi I'm using TF-A+Hafnium tip of the tree, I guess inhibiting TRF might be required later when OP-TEE rebases to latest upstream.

Correct. I hope the next release will disable the flag by default, but if it is not the case I have prepared https://github.com/OP-TEE/build/pull/698. Thanks!
