### ISSUE TITLE
TEEC_OpenSession with the TEEC_LOGIN_USER & TA_InvokeCommandEntryPoint

### ISSUE THREAD

**Issue by YaelAv** [OP-TEE/optee_os#6436]
My inquiry is related to a session that initiated through TEEC_OpenSession with the TEEC_LOGIN_USER login method. Can we ensure that, when a TA dispatches a TA_InvokeCommandEntryPoint, it's exclusively processed if it originates from the same client who initiated the session? Should this verification take place within the TA or in the TEE core layer? If this needs to be performed within the TA, what is the method for obtaining the client's UUID?

**Comment by etienne-lms** [comment]
Isolation of TEE sessions initiated for non-secure world userland clients are reliable as far as the Linux kernel is reliable. When a Linux userland client issues a `TEEC_OpenSession()` call, the Linux kernel stores a session handle for the opened session. The Linux userland client cannot modify this session handle and can only use the same session handle when its calls to `TEE_InvokeCommand()` ,`TEEC_CloseSession()` and `TEEC_RequestCancellation()` reach OP-TEE.

Note that OP-TEE introduces a `TEE_LOGIN_REE_KERNEL` ID that only Linux kernel drivers can use as login method.

For TEE sessions opened from a TA, it is TEE core that stores a session handler the client TA cannot modify. Client TA calls to `TEE_InvokeTACommand()` and `TEE_CloseSession()` will always end in using the very same session handler.

Therefore, an invoked TA only needs to verify its client identity at session opening request.

Linux userland clients can use several identification means: public, user ID and group ID. Linux kernel is responsible for verifying the user ID matches effective ID assigned to the user in Linux ACL. Linux kernel is also responsible for verifiying that the client group ID matches one of group IDs assigned to the user in Linux ACL.  GPD TEE Client API specification also define application ID based login methods (`TEEC_LOGIN_APPLICATION` and friends) but OP-TEE does not support them.

Client TA always use its TA UUID as identifier, no alternative. TEE core is responsible for the validity of the TA UUID the callee TA gets from its client TA.

(I rely on dear readers to point out any false statement in the above description)

**Comment by etienne-lms** [comment]
> Should this verification take place within the TA or in the TEE core layer? If this needs to be performed within the TA, what is the method for obtaining the client's UUID?

It is the callee TA responsibility to verify its client identity if needed. Look at GPD TEE Internal Core API v1.3.1, section 4.6 Client Properties. A TA can use to following to get it's client ID:
```c
TEE_Identity identity = { };
TEE_Result res = TEE_SUCCESS;

res = TEE_GetPropertyAsIdentity(TEE_PROPSET_CURRENT_CLIENT, "gpd.client.identity", &identity);`
```
A client identity, as seen by a TA, is always a UUID. User ID and group ID based login uses UUIDv5 namespace specification to generate the UUID related to a user ID or a group ID.  See [`tee_session_calc_client_uuid()`](https://elixir.bootlin.com/linux/v6.6/source/drivers/tee/tee_core.c#L198) for it is implemented in the Linux kernel.

**Comment by amirasologmail** [comment]
An additional related question: Assuming the TA can identify the Normal World client opening a session to it by its uid/gid - is it possible to leverage the Key Manager to persist session keys so that they are encrypted to this client? In other words, is it possible to derive a key from the Key Manager's TSK key using the client's uuid, so that only this client could use the persisted key?

**Comment by etienne-lms** [comment]
> is it possible to derive a key from the Key Manager's TSK key using the client's uuid, so that only this client could use the persisted key?

TAs can invoke [`PTA_SYSTEM_DERIVE_TA_UNIQUE_KEY`](https://github.com/OP-TEE/optee_os/blob/3.13.0/lib/libutee/include/pta_system.h#L40-L51) command from the system PTA to achieve that.

**Comment by amirasologmail** [comment]
@etienne-lms thank you!
