### ISSUE TITLE
About the uuid of client application

### ISSUE THREAD

**Issue by ydonghyuk** [OP-TEE/optee_os#6444]
I can get CA's uuid from TA as below.
```
     res = TEE_GetPropertyAsIdentity(TEE_PROPSET_CURRENT_CLIENT, "gpd.client.identity", &identity);
     if (res != TEE_SUCCESS) {
         EMSG("Failed: TEE_GetPropertyAsIdentity returned 0x%x\n", (unsigned int)res);
         return res;
     }
     else {
         DMSG("identity.login: 0x%x", identity.login);
         DMSG("identity.uuid: %08x-%04x-%04x-%02x%02x%02x%02x%02x%02x%02x%02x", identity.uuid.timeLow, identity.uuid.timeMid, identity.uuid. timeHiAndVersion,
                                                                                 identity.uuid.clockSeqAndNode[0], identity.uuid.clockSeqAndNode[1],
                                                                                 identity.uuid.clockSeqAndNode[2], identity.uuid.clockSeqAndNode[3],
                                                                                 identity.uuid.clockSeqAndNode[4], identity.uuid.clockSeqAndNode[5],
                                                                                 identity.uuid.clockSeqAndNode[6], identity.uuid.clockSeqAndNode[7]);
     }
```

Does this uuid come from optee_os or kernel?
So, I wonder if this value changes every time TA opens.
When I actually tested it (I haven't tried it a few times yet),
The value did not change.

And is it possible to hard code CA's uuid as well as TA's uuid?

**Comment by etienne-lms** [comment]
This depends on the login method.
`TEE_LOGIN_PUBLIC`: no UUID.
`TEE_LOGIN_USER`: UUID is set by Linux kernel tee driver from effective user ID.
`TEE_LOGIN_GROUP`: UUID is set by the CA and verified by Linux kernel tee driver against the groups the user belongs to.
`TEE_LOGIN_APPLICATION`/`TEE_LOGIN_APPLICATION_USER`/`TEE_LOGIN_APPLICATION_GROUP`: not supported by OP-TEE.
`TEE_LOGIN_TRUSTED_APP`: set by OP-TEE core from effective client TA UUID.
`TEE_LOGIN_REE_KERNEL` (OP-TEE extension): no UUID.

**Comment by ydonghyuk** [comment]
@etienne-lms 
Thanks for your reply.

I would appreciate some help with additional questions.

1/
TEE_LOGIN_USER
When a session is opened with this,
If the EUID is the same, will it always be set to the same UUID?

2/
TEE_LOGIN_GROUP
Is this affected by the CA's gid?
I am confused as to whether this can be determined by hard coding.

3/
TEE_LOGIN_TRUSTED_APP
Does this apply to TA->TA connection?

**Comment by ydonghyuk** [comment]
Question number 3 seems a bit strange.

TEE_LOGIN_TRUSTED_APP
It seems to be a similar concept to euid.
I think I lack knowledge about effective client TA UUID.
Are you referring to the uuid of the TA trying to open a session?

**Comment by etienne-lms** [comment]
1/  yes, obviously.
2/ no, only the group ID of the Linux user is used.
3/ yes, this login method is strictly dedicated to TA-to-TA session.
3-bis/ yes, the UUID used as login credential is the client TA UUID.

**Comment by ydonghyuk** [comment]
@etienne-lms 

I actually tested what you told me.
The uuids of different CAs with the same euid were actually set to be the same.
In this case, access control through this does not seem to have much meaning.

Lastly, for TA1-TA2 sessions, how can I get the uuid of TA1 from TA2? (When connecting between TAs, tee appears to be automatically set to TEE_LOGIN_TRUSTED_APP)

I had no success with this method of getting the CA's uuid from the CA-TA connection. (using identity)

**Comment by ydonghyuk** [comment]
Ah, I made a mistake.
The same uuid could be obtained from the TA-TA connection.

There was one thing I missed,
I understand that there is no case or method to hard code the CA's uuid like TA.
Is this correct?

thank you

**Comment by etienne-lms** [comment]
> In this case, access control through this does not seem to have much meaning.

It does. You don't know which application invoked the callee TA but you know which user (or which user group) execute the CA which at some point is of greater value.

For example, OP-TEE pkcs11 TA provides such an authentication mean when `CFG_PKCS11_TA_AUTH_TEE_IDENTITY=y`.

> Lastly, for TA1-TA2 sessions, how can I get the uuid of TA1 from TA2?

If TA1 connects TA2, TA2 can get TA1 identity with the above mentioned `TEE_PROPSET_CURRENT_CLIENT`/"gpd.client.identity" property.

> (When connecting between TAs, tee appears to be automatically set to TEE_LOGIN_TRUSTED_APP)

Of course, a TA cannot pretend to be something else than a TA and cannot spoof its UUID.

> I had no success with this method of getting the CA's uuid from the CA-TA connection. (using identity)

Does the code from https://github.com/OP-TEE/optee_os/issues/6444#issue-1984960351 fails? I'm pretty sure it succeeds. Check which login method argument is used by the CA (`TEEC_OpenSession()` 4th argument `uint32_t connectionMethod`).

> I understand that there is no case or method to hard code the CA's uuid like TA.
> Is this correct?

Not exactly correct. If a CA has to provide some specific information to identify itself towards a TA, it should provide it using the parameters passed with `TEEC_OpenSession()`. 
Extract from GP TEE Client API (v1.0), section 4.5.7:
_"Note: This API intentionally omits any form of support for static login credentials, such as PIN or password
entry. The login methods supported in the API are only those which have been identified as requiring
support by the rich operating environment. If a Trusted Application requires a static login credential then
this can be passed by the Client Application using the standard Shared Memory mechanisms for data
exchange."_

Note that there are no unified UUID defined for Client Applications. For example in the case of a standard Linux based OS, there is no generic UUID based means to identify userland applications. You would need some extra framework for that (SELinux maybe, or something equivalent).

**Comment by ydonghyuk** [comment]
@etienne-lms 
Thank you, It helped me a lot.
