### ISSUE TITLE
Error while building OP-TEE on QEMU(ubuntu 20.04)

### ISSUE THREAD

**Issue by Wkh19** [OP-TEE/optee_os#6450]
I'm using Ubuntu 20.04
Command used: repo init -u https://github.com/OP-TEE/manifest.git --repo-url=https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -b 3.12.0
i've installed all the required packages by following:https://optee.readthedocs.io/en/latest/building/prerequisites.html#prerequisites
i could see the following error log:
arning: gpg (GnuPG) is not available.
warning: Installing it is strongly encouraged.

warning: templates not found /build/git-repo-publish/parts/git/install/usr/share/git-core/templates
Get https://mirrors.tuna.tsinghua.edu.cn/git/git-repo
remote: Enumerating objects: 4891, done.
remote: Counting objects: 100% (4891/4891), done.
remote: Compressing objects: 100% (2428/2428), done.
remote: Total 8629 (delta 4315), reused 2463 (delta 2463), pack-reused 3738
Receiving objects: 100% (8629/8629), 4.17 MiB | 3.77 MiB/s, done.
Resolving deltas: 100% (5577/5577), done.
From https://mirrors.tuna.tsinghua.edu.cn/git/git-repo
 * [new branch]      main       -> origin/main
 * [new branch]      maint      -> origin/maint
 * [new branch]      master     -> origin/master
 * [new branch]      repo-1     -> origin/repo-1
 * [new branch]      stable     -> origin/stable
 * [new tag]         v1.0       -> v1.0
 * [new tag]         v1.0.1     -> v1.0.1
 * [new tag]         v1.0.2     -> v1.0.2
 * [new tag]         v1.0.3     -> v1.0.3
 * [new tag]         v1.0.4     -> v1.0.4
 * [new tag]         v1.0.5     -> v1.0.5
 * [new tag]         v1.0.6     -> v1.0.6
 * [new tag]         v1.0.7     -> v1.0.7
 * [new tag]         v1.0.8     -> v1.0.8
 * [new tag]         v1.0.9     -> v1.0.9
 * [new tag]         v1.1       -> v1.1
 * [new tag]         v1.10.0    -> v1.10.0
 * [new tag]         v1.10.1    -> v1.10.1
 * [new tag]         v1.10.2    -> v1.10.2
 * [new tag]         v1.10.3    -> v1.10.3
 * [new tag]         v1.10.4    -> v1.10.4
 * [new tag]         v1.11.0    -> v1.11.0
 * [new tag]         v1.11.1    -> v1.11.1
 * [new tag]         v1.12.0    -> v1.12.0
 * [new tag]         v1.12.1    -> v1.12.1
 * [new tag]         v1.12.10   -> v1.12.10
 * [new tag]         v1.12.11   -> v1.12.11
 * [new tag]         v1.12.12   -> v1.12.12
 * [new tag]         v1.12.13   -> v1.12.13
 * [new tag]         v1.12.14   -> v1.12.14
 * [new tag]         v1.12.15   -> v1.12.15
 * [new tag]         v1.12.16   -> v1.12.16
 * [new tag]         v1.12.17   -> v1.12.17
 * [new tag]         v1.12.18   -> v1.12.18
 * [new tag]         v1.12.19   -> v1.12.19
 * [new tag]         v1.12.2    -> v1.12.2
 * [new tag]         v1.12.20   -> v1.12.20
 * [new tag]         v1.12.21   -> v1.12.21
 * [new tag]         v1.12.22   -> v1.12.22
 * [new tag]         v1.12.23   -> v1.12.23
 * [new tag]         v1.12.24   -> v1.12.24
 * [new tag]         v1.12.25   -> v1.12.25
 * [new tag]         v1.12.26   -> v1.12.26
 * [new tag]         v1.12.27   -> v1.12.27
 * [new tag]         v1.12.28   -> v1.12.28
 * [new tag]         v1.12.29   -> v1.12.29
 * [new tag]         v1.12.3    -> v1.12.3
 * [new tag]         v1.12.3.1  -> v1.12.3.1
 * [new tag]         v1.12.30   -> v1.12.30
 * [new tag]         v1.12.30.1 -> v1.12.30.1
 * [new tag]         v1.12.31   -> v1.12.31
 * [new tag]         v1.12.32   -> v1.12.32
 * [new tag]         v1.12.33   -> v1.12.33
 * [new tag]         v1.12.34   -> v1.12.34
 * [new tag]         v1.12.35   -> v1.12.35
 * [new tag]         v1.12.36   -> v1.12.36
 * [new tag]         v1.12.37   -> v1.12.37
 * [new tag]         v1.12.4    -> v1.12.4
 * [new tag]         v1.12.5    -> v1.12.5
 * [new tag]         v1.12.6    -> v1.12.6
 * [new tag]         v1.12.7    -> v1.12.7
 * [new tag]         v1.12.8    -> v1.12.8
 * [new tag]         v1.12.9    -> v1.12.9
 * [new tag]         v1.13.0    -> v1.13.0
 * [new tag]         v1.13.1    -> v1.13.1
 * [new tag]         v1.13.10   -> v1.13.10
 * [new tag]         v1.13.11   -> v1.13.11
 * [new tag]         v1.13.2    -> v1.13.2
 * [new tag]         v1.13.3    -> v1.13.3
 * [new tag]         v1.13.4    -> v1.13.4
 * [new tag]         v1.13.5    -> v1.13.5
 * [new tag]         v1.13.5.1  -> v1.13.5.1
 * [new tag]         v1.13.6    -> v1.13.6
 * [new tag]         v1.13.7    -> v1.13.7
 * [new tag]         v1.13.7.1  -> v1.13.7.1
 * [new tag]         v1.13.8    -> v1.13.8
 * [new tag]         v1.13.9    -> v1.13.9
 * [new tag]         v1.13.9.1  -> v1.13.9.1
 * [new tag]         v1.13.9.2  -> v1.13.9.2
 * [new tag]         v1.13.9.3  -> v1.13.9.3
 * [new tag]         v1.13.9.4  -> v1.13.9.4
 * [new tag]         v1.2       -> v1.2
 * [new tag]         v1.3       -> v1.3
 * [new tag]         v1.3.1     -> v1.3.1
 * [new tag]         v1.3.2     -> v1.3.2
 * [new tag]         v1.4       -> v1.4
 * [new tag]         v1.4.1     -> v1.4.1
 * [new tag]         v1.4.2     -> v1.4.2
 * [new tag]         v1.4.3     -> v1.4.3
 * [new tag]         v1.4.4     -> v1.4.4
 * [new tag]         v1.5       -> v1.5
 * [new tag]         v1.5.1     -> v1.5.1
 * [new tag]         v1.6       -> v1.6
 * [new tag]         v1.6.1     -> v1.6.1
 * [new tag]         v1.6.10    -> v1.6.10
 * [new tag]         v1.6.10.1  -> v1.6.10.1
 * [new tag]         v1.6.10.2  -> v1.6.10.2
 * [new tag]         v1.6.2     -> v1.6.2
 * [new tag]         v1.6.3     -> v1.6.3
 * [new tag]         v1.6.4     -> v1.6.4
 * [new tag]         v1.6.5     -> v1.6.5
 * [new tag]         v1.6.6     -> v1.6.6
 * [new tag]         v1.6.7     -> v1.6.7
 * [new tag]         v1.6.7.1   -> v1.6.7.1
 * [new tag]         v1.6.7.2   -> v1.6.7.2
 * [new tag]         v1.6.7.3   -> v1.6.7.3
 * [new tag]         v1.6.7.4   -> v1.6.7.4
 * [new tag]         v1.6.7.5   -> v1.6.7.5
 * [new tag]         v1.6.8     -> v1.6.8
 * [new tag]         v1.6.8.1   -> v1.6.8.1
 * [new tag]         v1.6.8.10  -> v1.6.8.10
 * [new tag]         v1.6.8.11  -> v1.6.8.11
 * [new tag]         v1.6.8.2   -> v1.6.8.2
 * [new tag]         v1.6.8.3   -> v1.6.8.3
 * [new tag]         v1.6.8.4   -> v1.6.8.4
 * [new tag]         v1.6.8.5   -> v1.6.8.5
 * [new tag]         v1.6.8.6   -> v1.6.8.6
 * [new tag]         v1.6.8.7   -> v1.6.8.7
 * [new tag]         v1.6.8.8   -> v1.6.8.8
 * [new tag]         v1.6.8.9   -> v1.6.8.9
 * [new tag]         v1.6.9     -> v1.6.9
 * [new tag]         v1.6.9.1   -> v1.6.9.1
 * [new tag]         v1.6.9.2   -> v1.6.9.2
 * [new tag]         v1.6.9.3   -> v1.6.9.3
 * [new tag]         v1.6.9.4   -> v1.6.9.4
 * [new tag]         v1.6.9.5   -> v1.6.9.5
 * [new tag]         v1.6.9.6   -> v1.6.9.6
 * [new tag]         v1.6.9.7   -> v1.6.9.7
 * [new tag]         v1.6.9.8   -> v1.6.9.8
 * [new tag]         v1.7       -> v1.7
 * [new tag]         v1.7.1     -> v1.7.1
 * [new tag]         v1.7.2     -> v1.7.2
 * [new tag]         v1.7.3     -> v1.7.3
 * [new tag]         v1.7.3.1   -> v1.7.3.1
 * [new tag]         v1.7.4     -> v1.7.4
 * [new tag]         v1.7.4.1   -> v1.7.4.1
 * [new tag]         v1.7.4.2   -> v1.7.4.2
 * [new tag]         v1.7.4.3   -> v1.7.4.3
 * [new tag]         v1.7.5     -> v1.7.5
 * [new tag]         v1.7.6     -> v1.7.6
 * [new tag]         v1.7.6.1   -> v1.7.6.1
 * [new tag]         v1.7.7     -> v1.7.7
 * [new tag]         v1.7.7.1   -> v1.7.7.1
 * [new tag]         v1.7.7.2   -> v1.7.7.2
 * [new tag]         v1.7.7.3   -> v1.7.7.3
 * [new tag]         v1.7.7.4   -> v1.7.7.4
 * [new tag]         v1.7.7.5   -> v1.7.7.5
 * [new tag]         v1.7.7.6   -> v1.7.7.6
 * [new tag]         v1.7.8     -> v1.7.8
 * [new tag]         v1.7.8.1   -> v1.7.8.1
 * [new tag]         v1.7.8.2   -> v1.7.8.2
 * [new tag]         v1.8.0     -> v1.8.0
 * [new tag]         v1.8.1     -> v1.8.1
 * [new tag]         v1.8.2     -> v1.8.2
 * [new tag]         v1.9.0     -> v1.9.0
 * [new tag]         v1.9.1     -> v1.9.1
 * [new tag]         v1.9.2     -> v1.9.2
 * [new tag]         v1.9.3     -> v1.9.3
 * [new tag]         v1.9.4     -> v1.9.4
 * [new tag]         v1.9.5     -> v1.9.5
 * [new tag]         v1.9.6     -> v1.9.6
 * [new tag]         v2.0       -> v2.0
 * [new tag]         v2.1       -> v2.1
 * [new tag]         v2.1.1     -> v2.1.1
 * [new tag]         v2.10      -> v2.10
 * [new tag]         v2.11      -> v2.11
 * [new tag]         v2.11.1    -> v2.11.1
 * [new tag]         v2.12      -> v2.12
 * [new tag]         v2.12.1    -> v2.12.1
 * [new tag]         v2.12.2    -> v2.12.2
 * [new tag]         v2.13      -> v2.13
 * [new tag]         v2.13.1    -> v2.13.1
 * [new tag]         v2.13.2    -> v2.13.2
 * [new tag]         v2.13.3    -> v2.13.3
 * [new tag]         v2.13.4    -> v2.13.4
 * [new tag]         v2.13.5    -> v2.13.5
 * [new tag]         v2.13.6    -> v2.13.6
 * [new tag]         v2.13.7    -> v2.13.7
 * [new tag]         v2.13.8    -> v2.13.8
 * [new tag]         v2.14      -> v2.14
 * [new tag]         v2.14.1    -> v2.14.1
 * [new tag]         v2.14.2    -> v2.14.2
 * [new tag]         v2.14.3    -> v2.14.3
 * [new tag]         v2.14.4    -> v2.14.4
 * [new tag]         v2.14.5    -> v2.14.5
 * [new tag]         v2.15      -> v2.15
 * [new tag]         v2.15.1    -> v2.15.1
 * [new tag]         v2.15.2    -> v2.15.2
 * [new tag]         v2.15.3    -> v2.15.3
 * [new tag]         v2.15.4    -> v2.15.4
 * [new tag]         v2.16      -> v2.16
 * [new tag]         v2.16.1    -> v2.16.1
 * [new tag]         v2.16.2    -> v2.16.2
 * [new tag]         v2.16.3    -> v2.16.3
 * [new tag]         v2.16.4    -> v2.16.4
 * [new tag]         v2.16.5    -> v2.16.5
 * [new tag]         v2.16.6    -> v2.16.6
 * [new tag]         v2.16.7    -> v2.16.7
 * [new tag]         v2.16.8    -> v2.16.8
 * [new tag]         v2.17      -> v2.17
 * [new tag]         v2.17.1    -> v2.17.1
 * [new tag]         v2.17.2    -> v2.17.2
 * [new tag]         v2.17.3    -> v2.17.3
 * [new tag]         v2.18      -> v2.18
 * [new tag]         v2.19      -> v2.19
 * [new tag]         v2.2       -> v2.2
 * [new tag]         v2.20      -> v2.20
 * [new tag]         v2.21      -> v2.21
 * [new tag]         v2.22      -> v2.22
 * [new tag]         v2.23      -> v2.23
 * [new tag]         v2.24      -> v2.24
 * [new tag]         v2.24.1    -> v2.24.1
 * [new tag]         v2.25      -> v2.25
 * [new tag]         v2.26      -> v2.26
 * [new tag]         v2.27      -> v2.27
 * [new tag]         v2.28      -> v2.28
 * [new tag]         v2.29      -> v2.29
 * [new tag]         v2.29.1    -> v2.29.1
 * [new tag]         v2.29.2    -> v2.29.2
 * [new tag]         v2.29.3    -> v2.29.3
 * [new tag]         v2.29.4    -> v2.29.4
 * [new tag]         v2.29.5    -> v2.29.5
 * [new tag]         v2.29.6    -> v2.29.6
 * [new tag]         v2.29.7    -> v2.29.7
 * [new tag]         v2.29.8    -> v2.29.8
 * [new tag]         v2.29.9    -> v2.29.9
 * [new tag]         v2.3       -> v2.3
 * [new tag]         v2.30      -> v2.30
 * [new tag]         v2.31      -> v2.31
 * [new tag]         v2.32      -> v2.32
 * [new tag]         v2.33      -> v2.33
 * [new tag]         v2.34      -> v2.34
 * [new tag]         v2.34.1    -> v2.34.1
 * [new tag]         v2.35      -> v2.35
 * [new tag]         v2.36      -> v2.36
 * [new tag]         v2.36.1    -> v2.36.1
 * [new tag]         v2.37      -> v2.37
 * [new tag]         v2.38      -> v2.38
 * [new tag]         v2.39      -> v2.39
 * [new tag]         v2.4       -> v2.4
 * [new tag]         v2.4.1     -> v2.4.1
 * [new tag]         v2.5       -> v2.5
 * [new tag]         v2.6       -> v2.6
 * [new tag]         v2.7       -> v2.7
 * [new tag]         v2.8       -> v2.8
 * [new tag]         v2.9       -> v2.9
  File "/home/robin/optee/.repo/repo/main.py", line 94
    )
    ^
SyntaxError: invalid syntax
i use command:python --version  it is python3.8.10
Could anyone help me solve this issue please?

**Comment by jforissier** [comment]
> Command used: repo init -u https://github.com/OP-TEE/manifest.git --repo-url=https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -b 3.12.0

I tried this exact command in the Dockerfile provided in the Ubuntu 20.04 tab of the [documentation](https://optee.readthedocs.io/en/latest/building/prerequisites.html#prerequisites) (I replaced the `RUN repo init ...` line) and it worked well. For the build to complete and since this is an older OP-TEE version (3.12.0) you need to add `python3-pycryptodome` to the `apt install` command and also add `ENV FORCE_UNSAFE_CONFIGURE=1`.

I believe some packages are missing or wrong on your machine and I suggest you try building in a Docker container instead. Here is how:

```
mkdir /tmp/optee && cd /tmp/optee
cat >Dockerfile <<_EOF_
FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y
RUN apt install -y \
    android-tools-adb \
    android-tools-fastboot \
    autoconf \
    automake \
    bc \
    bison \
    build-essential \
    ccache \
    cpio \
    cscope \
    curl \
    device-tree-compiler \
    expect \
    flex \
    ftp-upload \
    gdisk \
    git \
    iasl \
    libattr1-dev \
    libcap-ng-dev \
    libfdt-dev \
    libftdi-dev \
    libglib2.0-dev \
    libgmp3-dev \
    libhidapi-dev \
    libmpc-dev \
    libncurses5-dev \
    libpixman-1-dev \
    libslirp-dev \
    libssl-dev \
    libtool \
    make \
    mtools \
    netcat \
    ninja-build \
    python-is-python3 \
    python3-crypto \
    python3-cryptography \
    python3-pip \
    python3-pycryptodome \
    python3-pyelftools \
    python3-serial \
    rsync \
    unzip \
    uuid-dev \
    wget \
    xdg-utils \
    xterm \
    xz-utils \
    zlib1g-dev
RUN curl https://storage.googleapis.com/git-repo-downloads/repo > /bin/repo && chmod a+x /bin/repo
RUN mkdir /optee
WORKDIR /optee
RUN repo init -u https://github.com/OP-TEE/manifest.git --repo-url=https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -b 3.12.0 && repo sync -j10
WORKDIR /optee/build
ENV FORCE_UNSAFE_CONFIGURE=1
_EOF_
docker build -t optee_3.12.0_dev .
docker run -it --rm optee_3.12.0_dev
```
The last line will launch the docker image, at this point then you can type build everything and run the self-tests like so:
```
make -j2 toolchains
make -j$(nproc) check
```
