### ISSUE TITLE
PKCS11 TA: Invalid attribute CKA_CHECK_VALUE for secure key object

### ISSUE THREAD

**Issue by maroueneboubakri** [OP-TEE/optee_os#6453]
Hello,

According to the PKCS#11 specifications, CKA_CHECK_VALUE is an attribute of certificate object (CKO_CERTIFICATE) and also secure key object (CKO_SECRET_KEY). It seems that the PKCS11 TA recognizes this only for certificate object, returing invalid attribute type when requested for a secure key object (CKR_ATTRIBUTE_TYPE_INVALID). It is intentional ? or a bug ? 

I'll open a PR.

@etienne-lms FYI.

Thanks
Maro

**Comment by etienne-lms** [comment]
If you have an implementation for `CKA_CHECK_VALUE`, a P-R a warmly welcome. See https://github.com/OP-TEE/optee_os/issues/6431.

**Comment by etienne-lms** [comment]
Imeplemented by https://github.com/OP-TEE/optee_os/pull/6494.

**Comment by etienne-lms** [comment]
Work still on-going.
https://github.com/OP-TEE/optee_os/pull/6494 has been merged but led to 2 series of fixup changes:
- https://github.com/OP-TEE/optee_os/pull/6579 has been merged.
- https://github.com/OP-TEE/optee_os/pull/6550 is under review.
