### ISSUE TITLE
Issue building OP-TEE for Qemuv8: Illegal instruction while compiling U-Boot / Kernel ...

### ISSUE THREAD

**Issue by maroueneboubakri** [OP-TEE/optee_os#6454]
Hi @jforissier,

While following https://optee.readthedocs.io/en/latest/building/devices/qemu.html#id3 we encounter an issue:

```
lib/display_options.c: In function ‘print_freq’:
lib/display_options.c:59:9: internal compiler error: Illegal instruction
   59 |         unsigned long d = 1e9;
      |         ^~~~~~~~
0x1739600 diagnostic_impl(rich_location*, diagnostic_metadata const*, int, char const*, __va_list_tag (*) [1], diagnostic_t)
        ???:0
0x173a286 internal_error(char const*, ...)
        ???:0
0xc26e2f crash_signal(int)
        ???:0
0x193cec9 __gmpn_mul_basecase
        ???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
scripts/Makefile.build:256: recipe for target 'lib/display_options.o' failed
make[2]: *** [lib/display_options.o] Error 1
Makefile:1853: recipe for target 'lib' failed
make[1]: *** [lib] Error 2
make[1]: Leaving directory '/home/nxf45729/avs/optee/u-boot'
Makefile:290: recipe for target 'u-boot' failed
make: *** [u-boot] Error 2

```
Seems to be an issue with the toolchain.
Could you double-check ?

**Comment by maroueneboubakri** [comment]
@jforissier upgrading the toolchain to `12.3.rel1` solves the issue.

**Comment by jforissier** [comment]
Does the toolchain installed by `make toolchains` cause the error? It should be 11.3.1
```
build (master)$ ../toolchains/aarch64/bin/aarch64-linux-gnu-gcc --version | head -1
aarch64-linux-gnu-gcc (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712
```

**Comment by maroueneboubakri** [comment]
> Does the toolchain installed by `make toolchains` cause the error? It should be 11.3.1
> 
> ```
> build (master)$ ../toolchains/aarch64/bin/aarch64-linux-gnu-gcc --version | head -1
> aarch64-linux-gnu-gcc (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712
> ```

Yes.

**Comment by jforissier** [comment]
I have been able to do a clean build just now, using the Ubuntu 22.04 Docker file from https://optee.readthedocs.io/en/latest/building/prerequisites.html, so I suspect something might be wrong with your build host. Can you try with Docker too?

**Comment by maroueneboubakri** [comment]
I tried on Ubuntu 20.04 also and encounter the same issue, seems to be a known bug on 11.x ARM toolchain 
I'll try it on Docker, but probably better to upgarde the toolchain version, there is a lot of disucssions with regards to this bug.

**Comment by maroueneboubakri** [comment]
Also Linux Kernel can't compile

```
free(): invalid pointer
editors/awk.c: In function ‘parse_expr’:
editors/awk.c:1425:25: internal compiler error: Aborted
 1425 |                         v = hash_search(ahash, t_string);
      |                         ^
0x7fe9c0f7d08f ???
        /build/glibc-BHL3KM/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7fe9c0f7d00b __GI_raise
        ../sysdeps/unix/sysv/linux/raise.c:51
0x7fe9c0f5c858 __GI_abort
        /build/glibc-BHL3KM/glibc-2.31/stdlib/abort.c:79
0x7fe9c0fc726d __libc_message
        ../sysdeps/posix/libc_fatal.c:155
0x7fe9c0fcf2fb malloc_printerr
        /build/glibc-BHL3KM/glibc-2.31/malloc/malloc.c:5347
0x7fe9c0fd0b2b _int_free
        /build/glibc-BHL3KM/glibc-2.31/malloc/malloc.c:4173
0x7fe9c0f5e082 __libc_start_main
        ../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
scripts/Makefile.build:197: recipe for target 'editors/awk.o' failed
make[4]: *** [editors/awk.o] Error 1

```

and

```
drivers/clk/qcom/gcc-ipq5018.c:680:9: internal compiler error: Illegal instruction
  680 |         F(2500000, P_UNIPHY_RX, 12.5, 0, 0),
      |         ^
0x7fd71073008f ???
        /build/glibc-BHL3KM/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7fd710711082 __libc_start_main
        ../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
scripts/Makefile.build:243: recipe for target 'drivers/clk/qcom/gcc-ipq5018.o' failed
make[6]: *** [drivers/clk/qcom/gcc-ipq5018.o] Error 1
scripts/Makefile.build:480: recipe for target 'drivers/clk/qcom' failed
make[5]: *** [drivers/clk/qcom] Error 2
scripts/Makefile.build:480: recipe for target 'drivers/clk' failed
make[4]: *** [drivers/clk] Error 2
scripts/Makefile.build:480: recipe for target 'drivers' failed
make[3]: *** [drivers] Error 2
/home/nxf45729/avs/optee/linux/Makefile:1913: recipe for target '.' failed
make[2]: *** [.] Error 2
Makefile:234: recipe for target '__sub-make' failed
make[1]: *** [__sub-make] Error 2
make[1]: Leaving directory '/home/nxf45729/avs/optee/linux'
common.mk:369: recipe for target 'linux-common' failed
make: *** [linux-common] Error 2
make: *** Waiting for unfinished jobs....
```

and probably more, buildroot ...

**Comment by jforissier** [comment]
> I tried on Ubuntu 20.04 also and encounter the same issue, seems to be a known bug on 11.x ARM toolchain 

OK

> I'll try it on Docker, but probably better to upgarde the toolchain version, there is a lot of disucssions with regards to this bug.

The problem is that upgrading will break C++ support in TAs (https://bugs.linaro.org/show_bug.cgi?id=6015) and we don't have an alternative yet. Of course we will need to upgrade one day or another but this at least explains why we haven't already ;) and in any case 11.x should work as shown using the Dockerfile (which is Ubuntu 22.04, but the 20.04 version works too).

**Comment by maroueneboubakri** [comment]
> > I tried on Ubuntu 20.04 also and encounter the same issue, seems to be a known bug on 11.x ARM toolchain
> 
> OK
> 
> > I'll try it on Docker, but probably better to upgarde the toolchain version, there is a lot of disucssions with regards to this bug.
> 
> The problem is that upgrading will break C++ support in TAs (https://bugs.linaro.org/show_bug.cgi?id=6015) and we don't have an alternative yet. Of course we will need to upgrade one day or another but this at least explains why we haven't already ;) and in any case 11.x should work as shown using the Dockerfile (which is Ubuntu 22.04, but the 20.04 version works too).

Indeed, in optee_test TA.
