### ISSUE TITLE
raspberry 4B can not boot the SD card on the UART

### ISSUE THREAD

**Issue by mlhh1103** [OP-TEE/optee_os#6458]
My machine verison is Ubuntu 22.04, and I follow the instruction from the OP-TEE website, and the version docs are the latest. I run the command "dd if=/home/mlh/optee/build/../out/rpi3-sdcard.img of=/dev/sdb bs=1024k conv=fsync status=progress" 
and it only shows 
147849216 bytes (148 MB, 141MiB) copied, 1 s, 148 MB/S
193+0 records in
193+0 records out
202375168 bytes(202 MB, 193MiB) copied, 22.2784 s, 9.1MB/s
Is that right? after that I plugged the device in the UART cable and attach to the UART, but there is no response when I power up the rsp Pi 4B. I check the Pin links and they are right. 
So where is the problem? Should I use the RPI 3B instead of 4B? I would appreciate it if anyone could give me some help.

**Comment by jbech-linaro** [comment]
> Should I use the RPI 3B instead of 4B?

Yes! --> https://optee.readthedocs.io/en/latest/building/devices/rpi3.html#what-versions-of-raspberry-pi-will-work

**Comment by mlhh1103** [comment]
> > Should I use the RPI 3B instead of 4B?
> 
> Yes! --> https://optee.readthedocs.io/en/latest/building/devices/rpi3.html#what-versions-of-raspberry-pi-will-work

Thanks for your reply! I have replaced my device with Raspberry PI 3B+, and the UART prints and the xtest is running properly!

**Comment by jbech-linaro** [comment]
> Thanks for your reply! I have replaced my device with Raspberry PI 3B+, and the UART prints and the xtest is running properly!

Awesome!
