### ISSUE TITLE
Expected behaviour of TEE_AEUpdate() and TEE_AEEncryptFinal()

### ISSUE THREAD

**Issue by maroueneboubakri** [OP-TEE/optee_os#6466]
Hello,

I'm adding support of AES-GCM to PKCS#11 TA, I want a clarification with regards to the usage of  `TEE_AEUpdate()`  and `TEE_AEEncryptFinal()`.

Aassume `in_buf ` has length of `in_size=28`. 
 `TEE_AEUpdate(handle, in_buf, in_size, out_buf, &out_size);`
`TEE_AEUpdate()` outputs `out_size=28`. Well

Now when calling:
`TEE_AEEncryptFinal(handle, NULL, 0, NULL, &size, &tag, &tag_len);`
`tag_len` is 16. Well.

What is the expected value of `size` ? should not be zero ?  

I saw many disucssion with regards to this, buffering etc, at certain point I'm not following well.

@etienne-lms @jenswi-linaro 

Best
Maro

**Comment by jforissier** [comment]
> Now when calling: `TEE_AEEncryptFinal(handle, NULL, 0, NULL, &size, &tag, &tag_len);` `tag `is 16. Well.

I suppose you mean `tag_len` is 16.
 
> What is the expected value of `size` ? should not be zero ?

With AES GCM the size of the encrypted data is the same as the input data (ignoring the fact that a 16-byte tag is added, this is separate in the API). So if you set `size` to 0 on input (non-zero would be invalid with `destData == NULL`), it should remain 0 on output. But if for some reason the previous call to `TEE_AEEncryptUpdate()` has not consumed all the data, then there would be some leftover. In this case you would get `TEE_ERROR_SHORT_BUFFER` and the needed size would be copied to `size`.

**Comment by maroueneboubakri** [comment]
Thank you @jforissier
