### ISSUE TITLE
RPI 3 model B+ - How to access Secure world TA logs console 

### ISSUE THREAD

**Issue by gunaMect** [OP-TEE/optee_os#6485]
I have successfully flashed the OPTEE image in the RPI 3 and running the available optee_examples_* and xtest is also working fine.

I have a question of how to view the TA logs in the RPI 3.

I am using HDMI for accessing the Linux and Client logs. I need to access the Secure World TA logs - same like in QEMU environment. Can anyone help me here? Thanks in Advance....

**Comment by jbech-linaro** [comment]
Hi @gunaMect , you need an UART cable connected like [this](https://optee.readthedocs.io/en/latest/building/devices/rpi3.html#uart-rpi3-cable). You can buy any cheap USB/UART cable as long as it's 3.3V (like [this one](https://www.amazon.com/dp/B07R8BQYW1/ref=sspa_dk_detail_2?th=1) for example). You find some additional userful information [here](https://pinout.xyz/pinout/uart).

**Comment by gunaMect** [comment]
Thanks @jbech-linaro I have seen the TA logs using the UART cable following the above procedure.
