### ISSUE TITLE
Clang 

### ISSUE THREAD

**Issue by etienne-lms** [OP-TEE/optee_os#6486]
I face an issue with the regulator.h implementation when building with Clang.
The issue was for releaved yet as CI make (multi-platforms) builds only vexpress-qemu_virt default config with Clang and `CFG_DRIVERS_REGULATOR` is default disabled for that platform flavor.

P-R #6481 makes generic statistics PTA to include _regulator.h_ hence processed by Clang build for vexpress-qemu_virt.
```
_make COMPILER=clang
In file included from core/pta/stats.c:7:
core/include/drivers/regulator.h:111:29: error: field 'desc' with variable sized type 'struct regulator_voltages' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
                struct regulator_voltages desc;
                                          ^
core/include/drivers/regulator.h:113:4: error: field 'voltages_fallback' with variable sized type 'struct voltages_fallback' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
        } voltages_fallback;
          ^
2 errors generated.
```

See the related structures definition below, extracted from _regulator.h_:
```c
struct regulator_voltages {
	enum voltage_type type;
	size_t num_levels;
	int entries[];
};

(...)

struct regulator {
	(...)
	unsigned int refcount;
	struct mutex lock;	/* Concurrent access protection */
	struct voltages_fallback {
		struct regulator_voltages desc;
		int levels[3];
	} voltages_fallback;
	size_t levels_count_fallback;
	SLIST_ENTRY(regulator) link;
};
```

I though of a way out but I'd rather have some advice here:
```patch
 	struct voltages_fallback {
-		struct regulator_voltages desc;
-		int levels[3];
+		union {
+			struct regulator_voltages desc;
+			struct {
+				uint8_t hdr[sizeof(struct regulator_voltages)];
+				int levels[3];
+			};
+		};
 	} voltages_fallback;
```

@jforissier, is there a place I could get the Clang binaries OP-TEE OS CI is using to make some build tests?

**Comment by jforissier** [comment]
> @jforissier, is there a place I could get the Clang binaries OP-TEE OS CI is using to make some build tests?

CI uses Clang 12.0. Try this:
```
$ cd build
$ make clang-toolchains
$ export PATH=$(pwd)/../clang-12.0.0/bin:$PATH
$ make -j$(nproc) optee-os COMPILER=clang
```

**Comment by jforissier** [comment]
> ```
> _make COMPILER=clang
> In file included from core/pta/stats.c:7:
> core/include/drivers/regulator.h:111:29: error: field 'desc' with variable sized type 'struct regulator_voltages' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
>                 struct regulator_voltages desc;
>                                           ^
> core/include/drivers/regulator.h:113:4: error: field 'voltages_fallback' with variable sized type 'struct voltages_fallback' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
>         } voltages_fallback;
>           ^
> 2 errors generated.
> ```

The issue is actually a warning that gets turned into an error due to `CFG_WERROR=y` (which adds `-Werror`). Perhaps we should consider allowing that construct.

**Comment by jenswi-linaro** [comment]
I'm not so keen on this. What is the point with a variable-sized `struct regulator_voltages` when it can't be that or we'll have memory corruption?

**Comment by etienne-lms** [comment]
> I'm not so keen on this. What is the point with a variable-sized struct regulator_voltages when it can't be that or we'll have memory corruption?

I think there is an easy way to address my issue. I'll keep you informed.

**Comment by etienne-lms** [comment]
Ok, I found my way to test with Clang and to address the issue.
I'll create a P-R to fix _regulator.h_.
Many thanks.

**Comment by etienne-lms** [comment]
Fix proposal for the _regulator.h_ issue in https://github.com/OP-TEE/optee_os/pull/6487.
