### ISSUE TITLE
Debug support for OP-TEE 3.3

### ISSUE THREAD

**Issue by Pavan-Kumar-7** [OP-TEE/optee_os#6490]
Need to understand how to debug the below case - 

1) once in a while issue where the OPTEE on IMX6Q board, gets stuck after the below log from OP-TEE-
 
**I/HC:**

Post this is where the Kernel gets uncompressed and is loaded. Any suggestions will help, please note OP-TEE will load the Kernel in the Boot Flow here.

**Comment by jenswi-linaro** [comment]
OP-TEE isn't loading any boot binaries, but I guess it could be instructed to hand over directly to the kernel instead of a non-secure boot loader. I suspect memory corruption. Are the kernel, rootfs, and dtb always loaded at the same physical addresses?

**Comment by jenswi-linaro** [comment]
Are you loading OP-TEE with U-Boot? And the problem is before OP-TEE has initialized?

**Comment by Pavan-Kumar-7** [comment]
Yes we are loading optee through uboot. And if I am not wrong based on the logs optee is getting initialised and post that the kernel is not getting loaded.

**Comment by Pavan-Kumar-7** [comment]
It should be entering directly from OP-TEE.
