### ISSUE TITLE
memset() in TEE_MemFill()

### ISSUE THREAD

**Issue by zjchen666** [OP-TEE/optee_os#6500]
the memset() is used by the TEE_MemFill() implementation could be optimized/removed by the compiler, so that the TAs which use TEE_MemFill() may be vulnerable to leak sensitive data.
```
void TEE_MemFill(void *buff, uint32_t x, size_t size)
{
	memset(buff, x, size);
}
```
Is there any reason we don't use memzero_explicit() here? can we use memzero_explicit() to replace memset() as a security enhancement?
Thanks,
Zhijun

**Comment by jenswi-linaro** [comment]
The drawback is that it prevents optimization of code where you wouldn't mind some optimization.
We should probably add it as an extension instead if this really is needed.

**Comment by etienne-lms** [comment]
As the spec says "_The TEE_MemFill function writes the byte x into the first size bytes of the buffer pointed to by buffer._" it seems better to ensure the operation is not removed by the compiler even at the cost of some sub-optimization, IMHO.

**Comment by jenswi-linaro** [comment]
The C standard says:
_The memset function copies the value of c (converted to an unsigned char) into
each of the ﬁrst n characters of the object pointed to by s._
Sounds like the same thing, just as ambiguous, that is.

**Comment by etienne-lms** [comment]
But the TEE spec is designed for security, not the C standard lib.

**Comment by jenswi-linaro** [comment]
That's a good point. In practice, I believe it's never optimized out so it may not make a difference to use `memzero_explicit()` instead, except that it's better to be explicit if this is the intent.

**Comment by jforissier** [comment]
> That's a good point. In practice, I believe it's never optimized out so it may not make a difference to use `memzero_explicit()` instead, except that it's better to be explicit if this is the intent.

+1 and TAs can always use `memset()` for a potentially better optimized code if they wish to do so.

**Comment by zjchen666** [comment]
Given the continuous evolution of compilers, it's not guaranteed that memset() won't be optimized by any compiler. Making it explicit with memzero_explicit() is a safer approach.
and agreed that TAs can use memset() for optimizable use cases.
