### ISSUE TITLE
Reading Metadata of Data stored in REE Secure Storage

### ISSUE THREAD

**Issue by gunaMect** [OP-TEE/optee_os#6503]
Using the optee_example_secure_storage, it is creating secure storage file in REE FS.

Is there a way to print the meta data of the file created in REE FS. What will be stored in the data/tee/dirf.db? Also, is there any way to analyze/debug the content available in the data/tee/dirf.db.

Thanks in advance.

**Comment by Amit-Radur** [comment]
> Using the optee_example_secure_storage, it is creating secure storage file in REE FS.

Yes, "optee_example_secure_storage" is creating objects/file in REE FS that is present in encrypted form.

 >Is there a way to print the meta data of the file created in REE FS.

You can look it here, the "tee_fs_htree_image"  struct has meta data information that can be printed
https://github.com/OP-TEE/optee_os/blob/master/core/include/tee/fs_htree.h#L56
