### ISSUE TITLE
How to make TA in RasberryPi3 connected to PC

### ISSUE THREAD

**Issue by gunaMect** [OP-TEE/optee_os#6504]
I have prepared optee image for Rpi 3 model B and ran the existing examples along with the xtest. All seems to be working fine.
1. Can you share any easiest method to test the new TA's and its respective clients in OPTEE as well as RPI 3. It means I need a method to update the binaries in the runtime in RPI3
2. Also, how to place my custom files to integrate with the build? Let's say i am having custom key.bin, I need this file in the Linux file system in the /root path.

Any support will be great help for me for TA development. Thanks in advance.

**Comment by jbech-linaro** [comment]
There are a couple of different ways. If you need to update the TEE itself, then it's unfortunately moving the SD card to a computer and copy files again. If it's TA's (or other regular files, applications) then you can scp files to `/lib/optee_armtz/` and just overwrite the TA's you've updated. Another way is to enable NFS and then you can just copy files to your local root filesystem and the device will see the files. We have instructions for NFS [here](https://optee.readthedocs.io/en/latest/building/devices/rpi3.html#nfs-boot). Personally I've been using a shell script together with minor makefile change to support my own NFS setup that I use for RPi3. I have a branch for that [here](https://github.com/jbech-linaro/build/commits/rpi_nfs) where the last ~10 patches is about that. Most of the "magic" there is [this](https://github.com/jbech-linaro/build/blob/rpi_nfs/rpi3.mk#L189-L222).

So, NFS .. works, but can be tricky to set up. SSH. if enabled, makes it fairly easy to scp files. I rarely use scp for OP-TEE development, so I cannot remember if it's enabled by default. But I believe I've used the "dropbear SSH" for this in the past.
