### ISSUE TITLE
Is there any reason for not including 'MBEDTLS_PK_PARSE_C' in mbedtls_config_kernel.h?

### ISSUE THREAD

**Issue by nolzaheo** [OP-TEE/optee_os#6520]
Hello all, I'm trying to use mbedtls_pk_parse_key() in user_ta.c.
I included mbedtls/pk.h, but implicit declaration of function error occurs like below.
![image](https://github.com/OP-TEE/optee_os/assets/55793819/5e65db90-6c49-4bbd-a870-177356977d66)

mbedtls_pk_parse_key() function seems to be available only when MBEDTLS_PK_PARSE_C is defined, but it appears not to be defined in mbedtls_config_kernel.h. I wonder if this omission is intentional or if mbedtls_pk_parse_key() can be used without modifying this file.

I'm using mbedtls with version of 2.28.1

Is there anyone who can help?
Thank you in advance.

**Comment by jenswi-linaro** [comment]
That is intentional since we don't need it upstream.

**Comment by nolzaheo** [comment]
Thank you for your answer!

Then how can I set to use mbedtls_pk_parse_key()?
I tried to add #define MBEDTLS_PK_PARSE_C into mbedtls_config_kernel.h, but the same error occurred

**Comment by nolzaheo** [comment]
Yes, I did.
I've included <mbedtls/pk.h>, and I have confirmed that the function declaration and definition match.

You can also see my situation here (https://github.com/Mbed-TLS/mbedtls/issues/8577)

Thank you for your consideration

**Comment by jenswi-linaro** [comment]
It's not the same error. You mention a link error there, here it's a missing prototype.

**Comment by nolzaheo** [comment]
I also found hope here as well, but pkparse.c has been already added
here..(line 54)

https://github.com/OP-TEE/optee_os/blob/a5e75b7ea399137e60503bb6693e3cb03ef2b8eb/lib/libmbedtls/sub.mk#L54


Still, thank you for looking into it!! :)

2023년 12월 5일 (화) 오전 12:01, David Horstmann ***@***.***>님이 작성:

**Comment by davidhorstmann-arm** [comment]
> I also found hope here as well, but pkparse.c has been already added here

Ah you're right I missed that, apologies!

**Comment by nolzaheo** [comment]
@jenswi-linaro I've been considering various possible reasons for the error, as the program didn't run though I added MBEDTLS_PK_PARSE_C into mbedtls_config_kernel.h. And I thought the linking issue was one of the possible reasons. 

thank you!

**Comment by nolzaheo** [comment]
@jenswi-linaro Also I think there might need to be a slight modification in the explanation of how to include the mbedtls library, as the libmbedtls library is located in /lib/libmbedtls instead of core/lib/libmbedtls.

https://optee.readthedocs.io/en/latest/architecture/libraries.html#libmbedtls
![image](https://github.com/OP-TEE/optee_os/assets/55793819/44a50b28-5f5e-4313-9f9d-d7c46d56e0a6)

**Comment by jenswi-linaro** [comment]
Thanks for pointing that out. Would you mind submitting a PR to fix it?

**Comment by nolzaheo** [comment]
@jenswi-linaro No problem! I'll go ahead and submit a PR to address it :)

**Comment by nolzaheo** [comment]
@davidhorstmann-arm I really appreciate your help, and I finally got to know that I missed there's one more part to try in sub.mk, under the line92(https://github.com/OP-TEE/optee_os/blob/397d66f8d10427e3e938a09e494a4abe502332d9/lib/libmbedtls/sub.mk#L92)
I added pkparse.c under the pk.c and it worked. It appears that the problem was related to linking, not the mbedtls library itself.

Thanks a lot!
