### ISSUE TITLE
Issue with TEE_BigIntConvertToFMM &   TEE_BigIntConvertFromFMM

### ISSUE THREAD

**Issue by pangupta** [OP-TEE/optee_os#653]
I am trying to write create API (vis a vis to  BN_mod_exp()) for a trusted application using the available exposed APIs.

When I try to use the below API  back to back, I am not able to get the base value back in res.
TEE_BigIntConvertToFMM(dest, base, mod, fmm_ctx); 
  TEE_BigIntConvertFromFMM(res,dest,mod,fmm_ctx);

I am not able to get the base value back in res when the mod is of higher bytes (in my case it is 64 bytes).

Please suggest if I am missing something.

Please find my code snipped below:

size_t mod_bit_size = TEE_BigIntGetBitCount(mod);
size_t fmm_ctx_len = TEE_BigIntFMMContextSizeInU32(mod_bit_size);
size_t fmm_len = TEE_BigIntFMMSizeInU32(mod_bit_size);

TEE_BigIntFMM *dest;
TEE_BigIntFMMContext *fmm_ctx;

fmm_ctx=(TEE_BigIntFMMContext *)TEE_Malloc(fmm_ctx_len * sizeof(TEE_BigIntFMMContext),0);
TEE_BigIntInitFMMContext(fmm_ctx, fmm_ctx_len, mod);

dest = (TEE_BigIntFMM *)TEE_Malloc(fmm_len * sizeof(TEE_BigIntFMM),0);
TEE_BigIntInitFMM (dest , fmm_len);

TEE_BigIntConvertToFMM(dest, base, mod, fmm_ctx);
TEE_BigIntConvertFromFMM(res,dest,mod,fmm_ctx);

**Comment by pascal-brand-st-dev** [comment]
`TEE_BigIntFMM`, computed from `B` and `mod`, is an internal representation to ease computation of `(A * B) % mod`. Hence, there is no reason that the internal representation are different for 2 different B. At least, it is not a constraint from Global Platform API, and I do not intuit how it could be the case as `TEE_BigIntFMMSizeInU32()` depends on of the size of `mod`, but not of the size of `B`.

Please close the issue if it answers.

**Comment by pangupta** [comment]
Thanks for the reply.
My code is successfully working if base = 2  and mod=2.
but as I set the mod value as 64 bit. the above mentioned issue observed.

I am sorry, as I am new to this, I am not able to deduce your suggestions for investigating my code.

I looked around for the example code for the above APIs but could not locate it.
Can you share any example code which was used to verify these APIs? 
It will of great help. Thanks.

regards
Pankaj

**Comment by pangupta** [comment]
Thanks for the reply.
My code is successfully working if base = 2  and mod=2.
but as I set the mod value as 64 bit. the above mentioned issue observed.

I am sorry, as I am new to this, I am not able to deduce your suggestions for investigating my code.

I looked around for the example code for the above APIs but could not locate it.
Can you share any example code which was used to verify these APIs? 
It will of great help. Thanks.

regards
Pankaj

**Comment by pascal-brand-st-dev** [comment]
If you're a member of Global Platform, you will find valuable tests in their test suite. Unfortunately, I cannot share them.

**Comment by pascal-brand-st-dev** [comment]
@pangupta Could you close this issue in case the support is completed?
