### ISSUE TITLE
crypto_authenc_update_aad on decrypt path in hash tree 

### ISSUE THREAD

**Issue by Amit-Radur** [OP-TEE/optee_os#6532]
I have few queries regarding crypto function used under hash tree.

1) Do we really need to call crypto_authenc_update_aad when TEE_OperationMode  is decrypt, shouldn't the Additional 
    authenticated data is updated only when TEE_OperationMode is encrypt ?

   https://github.com/OP-TEE/optee_os/blob/master/core/tee/fs_htree.c#L476C9-L476C34

2) Is this a BUG, using TEE_FS_HTREE_FEK_SIZE instead of TEE_FS_HTREE_HASH_SIZE ?

``
                 
 
            if (!ni) {
                   res = crypto_authenc_update_aad(ctx, mode, ht->root.node.hash,
     -                                               TEE_FS_HTREE_FEK_SIZE);
     +                                               TEE_FS_HTREE_HASH_SIZE);

3) How do one fully reset secure storage, do we need to create the /data/tee directory every time we wanted to reset 
    the secure storage ?

**Comment by jenswi-linaro** [comment]
1. Yes, it's needed to calculate the tag correctly.
2. Yes, fixing it will unfortunately break already existing secure storage objects. This means that we're currently using truncated SHA-256 hashes. I would very much like to fix this, but we should do it in a compatible way.
3. That depends on what you use for rollback protection. If you have none, it's enough to remove the content of `/data/tee`.

**Comment by jenswi-linaro** [comment]
https://optee.readthedocs.io/en/latest/debug/abort_dumps.html

**Comment by jenswi-linaro** [comment]
I'm sorry, I can't help debugging your code.

**Comment by Amit-Radur** [comment]
Sure, No issues. I am closing it as your answers helped me with few things.
