### ISSUE TITLE
How to perform automatic CI on my commit before submitting a PR?

### ISSUE THREAD

**Issue by LeiSen62** [OP-TEE/optee_os#6549]
Hi，how to perform automatic CI on my commit before submitting a PR？

**Comment by jbech-linaro** [comment]
Many ways, setup your own GitHub actions, setup your own local CI. I've just recently played with [Buildbot](https://buildbot.net/). If you're creative, you can write you own scripts etc. I.e., hard to give a single good advice.

**Comment by jforissier** [comment]
When you push code to a branch of your `optee_os` fork, it should trigger the GitHub Actions CI, even if you haven't created a pull request yet.

**Comment by LeiSen62** [comment]
Thanks!
