### ISSUE TITLE
Transient objects 

### ISSUE THREAD

**Issue by YaelAv** [OP-TEE/optee_os#6552]
As I understand, transient objects are used to hold a cryptographic object. In case I use my own cryptography library (not mbedtls or libtomcrypt), is it still useful to create the transient object just for performing of the cryptographic operation?

**Comment by NewDwarf** [comment]
In terms of OP-TEE, you implemented your own crypto provider and replaced default one. This shouldn't change the approach of using of the original design of OP-TEE.
So, from the perspective of developing of the TA, nothing changes.
