### ISSUE TITLE
TA from REE to TEE

### ISSUE THREAD

**Issue by mardyr** [OP-TEE/optee_os#6558]
Hi guys!
I am trying to navigate and understand the flow from triggering TA from REE to execution in TEE. So transition from user mode in REE to kernel mode and after that decryption,validation in TEE and its safe execution. I've stumbled upon  https://github.com/OP-TEE/optee_os/issues/4565 , which partially explains the first non-secure part, but I've got lost in syscall delegation [ldelf_syscall_open_bin()](https://github.com/OP-TEE/optee_os/blob/3.12.0/core/kernel/ldelf_syscalls.c#L155) , how it is triggered. I am not even saying about this second part. So do you have any guidance or documentation which I can follow. I know that code is the best documentation, but it is not small project.

**Comment by NewDwarf** [comment]
Good question which is not highlighted for unknown reasons. There is a just mention of abstract `ldelf` in documentation but what is actually is `ldelf` is not clear after reading.
The flow to open TA is TEEC_OpenSession() -> ioctl() -> SMC (Linux kernel TEE driver) -> BL31 (Secure monitor entry) -> SM thread_std_smc_entry() ... -> OP TEE ldelf_load_ldelf() -> OP TEE ldelf code -> ldelf_syscall_open_bin() -> RPC open

The most unclear part is `ldelf`. On compile time, ldelf.elf is built, then the script `gen_ldelf_hex.py` produces the file `ldelf_hex.c` which is then builtin into the OP TEE blob. The `ldelf_hex.c` has the `ldelf_data` array which is actually native code.
Then take a look at the `ldelf_load_ldelf()` function to see how the `ldelf_data` array is used
`memcpy((void *)code_addr, ldelf_data, ldelf_code_size);`

**Comment by mardyr** [comment]
In the meantime I found amazing article https://zhuanlan.zhihu.com/p/559626917 , everything is described in details

**Comment by jforissier** [comment]
> In the meantime I found amazing article https://zhuanlan.zhihu.com/p/559626917 , everything is described in details

Very good article indeed :+1:
