### ISSUE TITLE
Is it possible to add a physical address using kernel _stext and _text to the optee os mmu table?

### ISSUE THREAD

**Issue by ljmblueday** [OP-TEE/optee_os#6560]
**[Prerequisites]**
linaro linux kernel: commit a24278ea74b2b4beddbe0af01a27459cf35d86d7
optee os: commit bce2f88ab347b28f4149dacef2ad48ac67a500b6 
Development Environment: QEMU v8
**[Scenario]**
1. Create a pseudo-TA to check the integrity of the kernel image
2. Use arm_smccc_smc function in linux/mm/mm_init.c of Linux kernel to pass the physical address of _stext, _text to pseudo-TA
3. Pesudo TA creates a hash for the kernel image using the physical address received from the kernel
[Problem]
There is no optee os an MMU table for the physical address received from kernel

Try: 
Implement get_tmp_mmap in pseudo-TA and get the existing MMU table
Mapping physical address of actual kernel to static_memory_map[last] in mmu_table

Failed to get information about static_memory_map from pesudo TA

Question: Is there any way to bring information about static_memory_map other than the core_mmu.c file?
If this method is not correct, how can I add the physical address of the kernel image to optee os' MMU table?

I added the code below to pesudo-TA, but a build error occurred.
error: ‘static_memory_map’ undeclared (first use in this function)
52 | memset(tmp_mmap, 0, sizeof(static_memory_map));

`static struct tee_mmap_region *get_tmp_mmap(void)
{
	struct tee_mmap_region *tmp_mmap = (void *)__heap1_start;

#ifdef CFG_WITH_PAGER
	if (__heap1_end - __heap1_start < (ptrdiff_t)sizeof(static_memory_map))
		tmp_mmap = (void *)__heap2_start;
#endif

	memset(tmp_mmap, 0, sizeof(static_memory_map));
	DMSG("static_memory_map size = 0x%lx", sizeof(static_memory_map));
	return tmp_mmap;
}
`

**Comment by etienne-lms** [comment]
You should have a look at https://github.com/OP-TEE/optee_os/pull/4938.

**Comment by ljmblueday** [comment]
Thank you @etienne-lms 
I changed linux test code for checking kernel images as below.
I can understand how to add the physical address of the kernel to the mmu table of optee os.


//       pa = page_to_phys(page);
       pa = __pa_symbol(_stext);
       etext_pa = __pa_symbol(_etext);
       l = etext_pa - pa;
       pr_info("kernel image size = 0x%lx", l);

       p = page_address(page);
       pr_info("p %#lx l %#zx\n", (unsigned long)pa, l);


       res = add_rti_check(optee->smc.invoke_fn, pa, l, 0);
       if (res)
               pr_err("add_rti_check: %#x\n", res);
       res = run_rti_check(optee->smc.invoke_fn);
       if (res)
               pr_err("run_rti_check: %#x\n", res);
       p[23] = 10;
       res = run_rti_check(optee->smc.invoke_fn);
       if (res)
               pr_err("run_rti_check: OK\n");
       else
               pr_err("run_rti_check: Not OK\n");

**Test Result**
D/TC:? 0 tee_ta_close_session:487 Destroy session
D/TC:0   core_mmu_map_rti_check:2604 0x42210000:0x1030000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x1f0000
D/TC:0   core_mmu_map_rti_check:2604 0x42400000:0xe40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42600000:0xc40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42800000:0xa40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42a00000:0x840000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42c00000:0x640000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42e00000:0x440000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x43000000:0x240000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x43200000:0x40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x40000
D/TC:0   core_mmu_map_rti_check:2604 0:0
D/TC:0   core_mmu_map_rti_check:2604 0x42210000:0x1030000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x1f0000
D/TC:0   core_mmu_map_rti_check:2604 0x42400000:0xe40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42600000:0xc40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42800000:0xa40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42a00000:0x840000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42c00000:0x640000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42e00000:0x440000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x43000000:0x240000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x43200000:0x40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x40000
D/TC:0   core_mmu_map_rti_check:2604 0:0
D/TC:0   core_mmu_map_rti_check:2604 0x42210000:0x1030000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x1f0000
D/TC:0   core_mmu_map_rti_check:2604 0x42400000:0xe40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42600000:0xc40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42800000:0xa40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42a00000:0x840000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42c00000:0x640000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x42e00000:0x440000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x43000000:0x240000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x200000
D/TC:0   core_mmu_map_rti_check:2604 0x43200000:0x40000
D/TC:0   core_mmu_map_rti_check:2684 *mapped_len 0x40000
D/TC:0   core_mmu_map_rti_check:2604 0:0
