### ISSUE TITLE
How to release memory after using `thread_rpc_shm_cache_alloc` ? 

### ISSUE THREAD

**Issue by p870613** [OP-TEE/optee_os#6562]
Hi

I use the `thread_rpc_shm_cache_alloc` to allocate the share memory in pta in order to using `thread_rpc_cmd`.
But, I don't know how to release this share memory after rpc call.

example code: 
```
struct mobj *mobj = NULL;
void *va = NULL;
struct thread_param thread_params[3];
TEE_Result res = TEE_SUCCESS;
int fd;

va = thread_rpc_shm_cache_alloc(THREAD_SHM_CACHE_USER_FS,
                        THREAD_SHM_TYPE_APPLICATION, TEE_FS_NAME_MAX, &mobj);

memset(&params, 0, sizeof(params));
thread_params[0] = THREAD_PARAM_VALUE(IN, OPTEE_RPC_FS_CREATE, 0, 0);
thread_params[1] = THREAD_PARAM_MEMREF(IN, mobj, 0, TEE_FS_NAME_MAX);
thread_params[2] = THREAD_PARAM_VALUE(OUT, 0, 0, 0);
res = thread_rpc_cmd(OPTEE_RPC_CMD_FS, ARRAY_SIZE(params), &thread_params);
if(res != TEE_SUCCESS)
    return res;
fd = params[2].value.a;

```
Do you have any idea ?  

Thanks!!

**Comment by jenswi-linaro** [comment]
There's no need to free it, it will be freed automatically later in for example `call_entry_std()`.
Note that allocations from thread_rpc_shm_cache_alloc() are only valid until the next call with the same `enum thread_shm_cache_user user` argument.

**Comment by p870613** [comment]
Thanks for your replay ~~
