### ISSUE TITLE
How to init tee_crypt_int in optee_os 

### ISSUE THREAD

**Issue by rvceng** [OP-TEE/optee_os#6563]
When investigate in  ARM crypto extension driver in optee_os ,I saw  it initialized  along **service_init** in **optee_os/core/tee/tee_crypt_ult.c** 

In these source code : 

"static TEE_Result tee_cryp_init(void)
{
    
    DMSG("--------------ALready to initialize crypto API-----------------");
    TEE_Result res = crypto_init();
    DMSG("------------Done crypto API-----------------");
    if (res) {
        EMSG("Failed to initialize crypto API: %#" PRIx32, res);
        panic();
    }
    plat_rng_init();
#endif
 
    return TEE_SUCCESS;
}
service_init(tee_cryp_init);
"
I want to confirm when optee_os start the tee_cryp_init() will be called and print DMSG for me . I tried to add some DMSG but it was not print out . Will I need to add configure to enable ARM crypto extension driver ?

**Comment by jenswi-linaro** [comment]
Are you sure you're booting with the updated binary? Do you have debug prints enabled? Platforms are expected to enable the config options for supported crypto extensions.

**Comment by rvceng** [comment]
Hi @jenswi-linaro ,
I have built the rcar_gen4_3.13 source code and use that image, is it right?

**Comment by jenswi-linaro** [comment]
Yes, but are you sure you're booting with the updated binary? Look for the date and build ID in the boot log, it's printed at the end of the `I/TC: OP-TEE version:` line.

**Comment by rvceng** [comment]
Hi @jenswi-linaro  

I just checked and It booted with  updated vesion : optee: revision 3.13 (6f9792db) , optee driver R-Car Rev.1.0.11 
I  solved the issue and I will close this ticket. Thank you for your support
