### ISSUE TITLE
TEE_GetPropertyAsBool() does not return the expected value (ECC support)

### ISSUE THREAD

**Issue by oliviermartin** [OP-TEE/optee_os#657]
Here is the code I am running in my Trusted Application:

```
	uint32_t ret;
	bool ecc;

	// Check if ECC is supported by the Trusted OS
	ret = TEE_GetPropertyAsBool(TEE_PROPSET_TEE_IMPLEMENTATION, (char*)"gpd.tee.cryptography.ecc", &ecc);
	assert(ret == TEE_SUCCESS);
	assert(ecc == true);
```

The assert `assert(ecc == true)` fails.

I am using OPTEE OS v1.0.1 which seems to support ECC.

**Comment by pascal-brand-st-dev** [comment]
This should be now fixed with https://github.com/OP-TEE/optee_os/pull/648, merged last week on master branch. Could you check it?
