### ISSUE TITLE
How can I use secure periodic timer?

### ISSUE THREAD

**Issue by ljmblueday** [OP-TEE/optee_os#6570]
Hello.
I try to use the secure periodic timer.
I already find another issue #2925 , #6295.
I'm simply trying to make a handler that takes debug message every 1000ms
The code below is implemented to register handlers using a generic timer and print "[DEBUG] interrupt" every 1000ms.
But the handler doesn't get called periodically. What's wrong?

**[Prerequisites]**
linaro linux kernel: commit a24278ea74b2b4beddbe0af01a27459cf35d86d7
optee os: commit https://github.com/OP-TEE/optee_os/commit/bce2f88ab347b28f4149dacef2ad48ac67a500b6
Development Environment: QEMU v8

file : /core/arch/arm/plat-vexpress/main.c
```c
#define GIC_SPI_SEC_PHY_TIMER	29
#define TIMER_PERIOD_MS	1000

static enum itr_return timer_itr_cb(struct itr_handler *h __unused)
{
	/* Reset timer for next FIQ */
	generic_timer_handler(TIMER_PERIOD_MS);

	/* Collect entropy on each timer FIQ */
	DMSG("[DEBUG] interrupt");

	return ITRR_HANDLED;
}

static struct itr_handler timer_itr = {
	.it = GIC_SPI_SEC_PHY_TIMER,
	.flags = BIT(0),
	.handler = timer_itr_cb,
};

static TEE_Result init_timer_itr(void)
{
	if (interrupt_add_handler_with_chip(interrupt_get_main_chip(),
					    &timer_itr))
		panic();

	interrupt_enable(timer_itr.chip, timer_itr.it);

	/* Enable timer FIQ to fetch entropy required during boot */
	generic_timer_start(TIMER_PERIOD_MS);

	return TEE_SUCCESS;
}
service_init(init_timer_itr);
```

**Comment by jenswi-linaro** [comment]
I see that you've copied the code from `core/arch/arm/plat-synquacer/main.c`. Where did you get
``` C
#define GIC_SPI_SEC_PHY_TIMER	29
```
from?

**Comment by ljmblueday** [comment]
I just get from #2925 (https://github.com/OP-TEE/optee_os/issues/2925#issuecomment-484606270)

**Comment by jenswi-linaro** [comment]
OK, the SPI part of the define is misleading as it's a PPI. Anyway, it looks like this should work since the QEMU v8 virt platform also uses this number. I guess you need to debug this in some way (GDB or prints), I can't do that for you.

**Comment by ljmblueday** [comment]
Is there a compilation option that needs to be enabled to use timer interrupt in QEMU v8?

**Comment by ljmblueday** [comment]
@jenswi-linaro 
After testing with CFG_ARM_GICV3=n I can see the debug message in the secure world periodically.

@jforissier
I know that you uploaded the below commit. Let me know how I can enable a generic timer on GIC3.
https://github.com/OP-TEE/optee_os/commit/ba6b29591828040f913d336d5825fd0772e5b3d7

**Comment by jforissier** [comment]
> @jforissier I know that you uploaded the below commit. Let me know how I can enable a generic timer on GIC3. [ba6b295](https://github.com/OP-TEE/optee_os/commit/ba6b29591828040f913d336d5825fd0772e5b3d7)

I don't know. The author of the commit is @b49020, perhaps he can answer your question.

**Comment by b49020** [comment]
@ljmblueday 

> Let me know how I can enable a generic timer on GIC3. [ba6b295](https://github.com/OP-TEE/optee_os/commit/ba6b29591828040f913d336d5825fd0772e5b3d7)

On Armv8-A platforms its TF-A responsibility to initialize GICv3 and thereby assigning interrupts to secure world as G1S interrupts. For timer interrupt, you can look at here [1] for the configuration. I suppose similar config on Qemu should enable secure world timer interrupt.

[1] https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/tree/plat/socionext/synquacer/sq_gicv3.c#n29

**Comment by jenswi-linaro** [comment]
Better double-check that TF-A has configured the GIC correctly. That it works with GICv2 makes it possible that TF-A might have configured that interrupt for EL3 with GICv3.
