### ISSUE TITLE
When the following information is output to the console, the Linux system automatically restarts. How should I troubleshoot this issue?    

### ISSUE THREAD

**Issue by chuanqi723** [OP-TEE/optee_os#6571]
E/TC:0      
E/TC:0 Core data-abort at address 0x81c8000c
E/TC:0 fsr 0x00000008 ttbr0 0x0848406a ttbr1 0x08484068 cidr 0x0
E/TC:0 cpu #0  cpsr 0x000001f3 
E/TC:O rO Oxffff7100  r4 0x814e0000  r8 Oxffffff5c   r12 Oxfffc9c28 
E/TC:O r1 0x81590000  r5 0x80446197  r9 0x8d99c718   sp 0x08493680
E/TC:O r2 0x81c80000  r6 Oxffff0000  r10 0x00000000  Ir 0x0842dc1c 
E/TC:0 r3 Oxffff0000  r7 0x00000000  r11 0x8d9a7a20  pc 0x08400c84

**Comment by jenswi-linaro** [comment]
You could try enabling `CFG_UNWIND` to get a stack trace that you can feed into `scripts/symbolize.py`.

**Comment by chuanqi723** [comment]
Thank you for your advice, but I have already enabled CFG_UNWIND. When the console repeatedly outputs the above log, the Linux system suddenly restarts without any other log information. When I encode the data from one sensor in H.264 and the data from another sensor in JPEG, after a few hours or days, this issue occurs. If I perform H.264 or JPEG encoding separately, the problem does not occur
