### ISSUE TITLE
How to add external libraries to TEE and provide TA to the code for calling

### ISSUE THREAD

**Issue by oldoldcoder** [OP-TEE/optee_os#6572]
Hello,experts:

I try to use tee to complete the Paillier semi-homomorphic encryption algorithm. Since the general implementation of this algorithm is based on GMP and NTL, two libraries related to large number operations, my questions are as follows:

1. How to place these library files in the TEE test to ensure that my TA uses the relevant data structures without errors.
2. I need to modify those makefiles

Thanks for your reply, salute to you!

**Comment by jenswi-linaro** [comment]
If you intend to upstream this somewhere please give a few more details of what you have in mind.
If not:
1: No special place is needed, perhaps close to the TA would make sense
2: You're probably better off starting from scratch using a `sub.mk` file, compare with how `lib/libmbedtls` is compiled.

**Comment by hallowsman** [comment]
> Hello,experts:
> 
> I try to use tee to complete the Paillier semi-homomorphic encryption algorithm. Since the general implementation of this algorithm is based on GMP and NTL, two libraries related to large number operations, my questions are as follows:
> 
> 1. How to place these library files in the TEE test to ensure that my TA uses the relevant data structures without errors.
> 2. I need to modify those makefiles
> 
> Thanks for your reply, salute to you!



Have you successfully implemented GMP compilation into TA on your end? How is the process implemented? Can you provide a complete compilation process?
