### ISSUE TITLE
ATF has no LOG output

### ISSUE THREAD

**Issue by erhade** [OP-TEE/optee_os#6575]
My board is ROCK PI 4B. 
Although the OP-TEE system can be flashed normally according to the documentation, there is no LOG output from the firmware during startup, and the output from both the operating system and TEE is normal. 

Before entering U-Boot, the ATF has no output.
I have set the firmware compilation option to `ARCH=aarch64 PLAT=rk3399 SPD=opteed DEBUG=1 LOG_LEVEL=40` in Makefile. 

How can I output firmware to the console?

**Comment by jforissier** [comment]
Hi @erhade,

You may need to change `RK3399_UART_CLOCK` from 115200 to 1500000 in `trusted-firmware-a/plat/rockchip/rk3399/rk3399_def.h`.

**Comment by erhade** [comment]
It works. Thank you so much, Happy New Year!

**Comment by erhade** [comment]
Modifying the baud rate can only output the firmware information before Boot. The LOG I added cannot be output during runtime, such as the `NOTICE()` added in `trusted-firmware-a/services/arm_arch_svc/arm_arch_setup.c`.

The version of my TF-A is `2.9.0`. I want to print out LOG information in `arm_arch_svc_smc_handler`.

![image](https://github.com/OP-TEE/optee_os/assets/49524292/05b6093c-c12c-4a7c-b901-003ff57c0f53)

**Comment by jforissier** [comment]
Unfortunately, I don't know TF-A well enough to be able to help much. Perhaps it is not possible to call the log functions from `arm_arch_svc_smc_handler()`?

**Comment by jenswi-linaro** [comment]
It should be possible to log from `arm_arch_svc_smc_handler()` too. The problem is likely that normal world has reconfigured the UART.

**Comment by erhade** [comment]
I found a way to enable LOG. Because LOG is not output when running by default, I need to replace the `CONSOLE_FLAG_BOOT` flag in `trusted-firmware-a/drivers/console/multi_console.c` with `CONSOLE_FLAG_RUNTIME`.
