### ISSUE TITLE
Modify host/makefile to add external libraries, but fatal error is still prompted in host/main.c: openssl/bn.h: No such file or directory

### ISSUE THREAD

**Issue by oldoldcoder** [OP-TEE/optee_os#6577]
This makes me very distressed,I try to use OpenSSL in host to complete my function module:

<img width="632" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/6ddd7a0e-815a-4b48-ae19-c488f1814005">

At the same time, I naturally believe that modifying the compilation parameters of host/makefile can achieve my purpose:：

<img width="971" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/f7e3b4d4-254a-444f-b015-27bfb561bd18">

> Openssl libaries in /usr/include folder,While this may not be necessary, I tried this after many failed attempts

But after compiling, I got the wrong message:：

<img width="779" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/3ec4bb52-dcf3-4afe-8c22-b5ac942ae8d0">

I then tried to modify the makefile and other files in the Pailier Copy folder (anything that may be useful):

<img width="1103" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/5a671350-f8c8-4328-8f7c-a63fcafbb9d8">

> Android.mk

<img width="810" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/9b3781ba-e152-4e25-865a-fc0a2ae9b5af">

> CmakeList.txt

After I read the docs: https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-do-i-link-a-library-into-a-trusted-application
I found the relevant TA content (although I also use OpenSSL in TA, no errors are reported so far, but I still think there is a problem), but it seems that my problem is still not solved.

After that I want try:
`mv /usr/include/OpenSsl $(TEEC_EXPORT)/include', but I didn’t do this

my question:
1. How can I fulfill my needs?
2. Add the library in TA according to the documentation (https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-do-i-link-a-library-into-a-trusted-application )Is it feasible
3. Is there any difference between the two commands make buildroot and make run? When I compile optee_examples

**Comment by oldoldcoder** [comment]
Can anyone help me, thank you very much

**Comment by jforissier** [comment]
In `optee_examples/`:
```diff
diff --git a/your_app/CMakeLists.txt b/your_app/CMakeLists.txt
index 937b8cf..3ae6961 100644
--- a/your_app/CMakeLists.txt
+++ b/your_app/CMakeLists.txt
@@ -4,10 +4,12 @@ set (SRC host/main.c)
 
 add_executable (${PROJECT_NAME} ${SRC})
 
+find_package(OpenSSL)
+
 target_include_directories(${PROJECT_NAME}
 			   PRIVATE ta/include
 			   PRIVATE include)
 
-target_link_libraries (${PROJECT_NAME} PRIVATE teec)
+target_link_libraries (${PROJECT_NAME} PRIVATE teec PRIVATE crypto)
 
 install (TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_BINDIR})
```
In build/:
```diff
diff --git a/br-ext/package/optee_examples_ext/optee_examples_ext.mk b/br-ext/package/optee_examples_ext/optee_examples_ext.mk
index 113a9b3..cb046eb 100644
--- a/br-ext/package/optee_examples_ext/optee_examples_ext.mk
+++ b/br-ext/package/optee_examples_ext/optee_examples_ext.mk
@@ -3,7 +3,7 @@ OPTEE_EXAMPLES_EXT_SOURCE = local
 OPTEE_EXAMPLES_EXT_SITE = $(BR2_PACKAGE_OPTEE_EXAMPLES_EXT_SITE)
 OPTEE_EXAMPLES_EXT_SITE_METHOD = local
 OPTEE_EXAMPLES_EXT_INSTALL_STAGING = YES
-OPTEE_EXAMPLES_EXT_DEPENDENCIES = optee_client_ext host-python-cryptography
+OPTEE_EXAMPLES_EXT_DEPENDENCIES = optee_client_ext host-python-cryptography libopenssl
 OPTEE_EXAMPLES_EXT_SDK = $(BR2_PACKAGE_OPTEE_EXAMPLES_EXT_SDK)
 OPTEE_EXAMPLES_EXT_CONF_OPTS = -DOPTEE_EXAMPLES_SDK=$(OPTEE_EXAMPLES_EXT_SDK)
```

**Comment by oldoldcoder** [comment]
@jforissier Salute for you.I'll try it next, and has no one asked similar questions before?
