### ISSUE TITLE
Panic 'GICR_BASE missing' on Arm FVP

### ISSUE THREAD

**Issue by imre-kis-arm** [OP-TEE/optee_os#6581]
Since the [changes happened](https://github.com/OP-TEE/optee_os/commit/05089e5f9a56db581046e9966179bb96e042a07e) around the GIC redistributor OP-TEE fails to boot on Arm FVP. I am using [fvp-psa-sp.mk ](https://github.com/OP-TEE/build/blob/master/fvp-psa-sp.mk) but I assume it would fail with fvp.mk too because the panic happens in the init code.
The optee_os version is `bace0716e3692bff0da8c87b41635fc35e11bfd8`.
If I replace the panic call at `gic.c:362` with a simple `return` everything seems fine but I am not confident that this would be the right solution.
This issue should be fixed before the release as now OP-TEE is unable to boot on Arm FVP.
Please let me know if you need further information about the issue.

```
I/TC: OP-TEE version: 4.0.0-238-gbace0716e (gcc version 11.3.1 20220712 (Arm GNU Toolchain 11.3.Rel1)) #19 Mon Jan  8 15:04:00 UTC 2024 aarch64
I/TC: WARNING: This OP-TEE configuration might be insecure!
I/TC: WARNING: Please check https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html
I/TC: Primary CPU initializing
D/TC:0 0 boot_init_primary_late:1210 Executing at offset 0 with virtual load address 0x6000000
I/TC: GIC redistributor base address not provided
I/TC: Assuming default GIC group status and modifier
E/TC:0 0 Panic 'GICR_BASE missing' at core/drivers/gic.c:362 <gic_init_donate_sgi_to_ns>
E/TC:0 0 TEE load address @ 0x6000000
E/TC:0 0 Call stack:
E/TC:0 0  0x0600d970 print_kernel_stack at core/arch/arm/kernel/unwind_arm64.c:89
E/TC:0 0  0x0601b79c __do_panic at core/kernel/panic.c:73
E/TC:0 0  0x06017424 gic_init_donate_sgi_to_ns at core/drivers/gic.c:362
E/TC:0 0  0x06010418 boot_primary_init_intc at core/arch/arm/plat-vexpress/main.c:65
```

**Comment by jenswi-linaro** [comment]
This should be fixed in https://github.com/OP-TEE/optee_os/pull/6586

**Comment by imre-kis-arm** [comment]
Thank you, the PR solves the issue.
