### ISSUE TITLE
How to set STACK_SIZE for OPTEE CORE(core/kernel/user_ta.c)

### ISSUE THREAD

**Issue by nolzaheo** [OP-TEE/optee_os#6585]
Hello all, I'm adding some codes into user_ta.c in optee_os/core/kernel, and this code gets some run-time error when declaring a string longer than 1000.
I know that stack and data size for example codes can be modified in user_ta_header_defines.h, 
then is there any header file for configuring stack size for user_ta.c?

Any help would be appreciated. 

Thank you!

**Comment by jforissier** [comment]
Hello @nolzaheo,

The stack size for core threads is defined by `STACK_THREAD_SIZE` in `core/arch/$(ARCH)/thread_private_arch.h`. It is currently 8K (10K when `CFG_CORE_SANITIZE_KADDRESS=y`) plus the value of `CFG_STACK_THREAD_EXTRA`.

Therefore, the easiest way to increase the stack size is to set `CFG_STACK_THREAD_EXTRA`.

That being said, it is usually not a good idea to use the stack for large amounts of data. Why don't you store your >1000 character string somewhere else?

**Comment by nolzaheo** [comment]
I checked the code running fine with increased value of CFG_STACK_THREAD_EXTRA, as you suggested.
I'll also take that into consideration, storing this long string somewhere else. 

Thanks a lot!
