### ISSUE TITLE
Is it possible to add OpenSsl to it by adding the standard library to it as mentioned in the document?

### ISSUE THREAD

**Issue by oldoldcoder** [OP-TEE/optee_os#6588]
Hello,expert
View the documentation via: https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-do-i-link-a-library-into-a-trusted-application
And previous questions: #280, #601, #901 It seems that you can modify sub.mk and add

`ldargs-$(binary).elf += -lssl -lcrypto`

way to add OpenSsl to Ta, but ask questions by watching: #6085 #5884 #5278 #6411
It seems that the answer given by the engineer is not supported, so it means that my needs cannot be fulfilled through the explanation in the document?

**Comment by etienne-lms** [comment]
OpenSSL has quite many dependencies over standard library functions and features not supported by OP-TEE Trusted Applications C-source development kit. I think you'll need more than adding linker directives I think.

**Comment by oldoldcoder** [comment]
@etienne-lms Thank you for your reply,It means that If forcibly use OpenSSL, is there an unsafe problem?Also can you tell me what is "OP-TEE Trusted Applications C-source development kit", I'm just a beginner, again I salute you!

**Comment by etienne-lms** [comment]
> It means that If forcibly use OpenSSL, is there an unsafe problem?

No unsafe issues but rather linker dependencies. OP-TEE TAs use specific standard libraries that do not implement all standard libs functions and OP-TEE uses specific system calls that don't comply with POSIX and like standards. I think OpenSSL needs more operation system features than what OP-TEE provides. That said, I have no idea of the gap.

> Also can you tell me what is "OP-TEE Trusted Applications C-source development kit", 

When you build a TA, you use a filetree, named devkit, that hosts header files, libraries binaries and build scripts. This filetree is generated when you build OP-TEE core: _<buildir>/.../export-ta_arm32/_ and _<buildir>/.../export-ta_arm64/_.

**Comment by oldoldcoder** [comment]
@etienne-lms Thanks again for your reply, I will next try to refactor my code using mbedtls and then complete the feature!
