### ISSUE TITLE
Secure Network Channel

### ISSUE THREAD

**Issue by shirinebadi** [OP-TEE/optee_os#6593]
Hey. I'm trying to build a system that a TA needs to get a key from a remote server. According to [3659](https://github.com/OP-TEE/optee_os/issues/3659), is it possible for a TA to directly communicate with a remote server over a secure channel using mbedTLS?
(Also, I would appreciate any ideas on a better way to get the key.)
And after getting the key can the TA add it to the remote attestation PTA's secure storage?

**Comment by jenswi-linaro** [comment]
I'd recommend using the GlobalPlatform API available to TAs for crypto operations.

The GP Socket API is available to TAs, but I'd recommend letting the TA client do all the non-secure network communication directly instead. It's easier to debug etc.

> And after getting the key can the TA add it to the remote attestation PTA's secure storage?

I'm not sure what you mean by that.

**Comment by shirinebadi** [comment]
Thank you so much for your prompt response.
This key will be used for remote attestation. Do you think it's safe to use client application to get the key from remote server and send it to the TA?
Since I'm new to OP-TEE, I would appreciate any documents or code examples for GP Socket API in TA.

I appreciate your time and support.

**Comment by jenswi-linaro** [comment]
> Do you think it's safe to use client application to get the key from remote server and send it to the TA?

Not in plain text, you'd need to negotiate a protected communication channel between the TA the remote server.

> Since I'm new to OP-TEE, I would appreciate any documents or code examples for GP Socket API in TA.

We have a test TA using GP Socket API here https://github.com/OP-TEE/optee_test/blob/master/ta/socket/ta_entry.c

But as I said, I believe you'd be better off doing the communication via the client. The GP Socket API is somewhat hard to debug and not very flexible.

**Comment by shirinebadi** [comment]
Just to confirm, is it possible to use TLS socket in client app?

**Comment by shirinebadi** [comment]
Sorry for making it too long.

I was thinking about CA as a proxy, so there will be a key exchange between the remote server and the TA through the CA. Then, CA will get the encrypted data from the remote server over TLS and send it to the TA using mbedTLS(a secure channel between the CA and the TA). You think it is not an efficient way?

**Comment by shirinebadi** [comment]
Sorry but I don't see why it is not secure?

**Comment by jenswi-linaro** [comment]
It's not insecure, but it doesn't improve security either. The Linux user space must be able to trust the kernel and an eventual hypervisor.
