### ISSUE TITLE
About the memory area related to "Error TEE_AllocateOperation"

### ISSUE THREAD

**Issue by ydonghyuk** [OP-TEE/optee_os#6596]
```
E/TA:  TA_create_operation:1233 Error TEE_AllocateOperation maxObjectSize=4096
D/TC:? 0 tee_ta_invoke_command:840 Error: ffff000c of 4
D/TC:? 0 tee_ta_invoke_command:840 Error: ffff000c of 4
```

The above error occurred during RSA signing operation. (out of memory)
What memory area does this error relate to?

I modified CFG_TZDRAM_SIZE to increase TA_RAM size,
I increased TA_HEAP_SIZE and TA_STACK_SIZE, but it had no effect.
Am I approaching this wrong?

**Comment by jenswi-linaro** [comment]
This is likely `CFG_CORE_HEAP_SIZE`

**Comment by ydonghyuk** [comment]
@jenswi-linaro ok, thanks for your help.
I will check it, and comment.

**Comment by ydonghyuk** [comment]
@jenswi-linaro
CFG_TA_STATS 설정 후에 아래 command 결과에서, 아래 데이터를 볼 수 있다.
```
Pool :                        Heap
/*snip*/
Size of pool :            68720
/*snip*/
```

CORE_HEAP_SIZE와 연관이 있는 거니?

**Comment by jenswi-linaro** [comment]
No

**Comment by ydonghyuk** [comment]
```
diff --git a/mk/config.mk b/mk/config.mk
index 3b3ccec..c60dd9b 100644
--- a/mk/config.mk
+++ b/mk/config.mk
@@ -549,7 +549,8 @@ CFG_DRIVERS_DT_RECURSIVE_PROBE ?= n
 CFG_BOOT_SECONDARY_REQUEST ?= n

 # Default heap size for Core, 64 kB
-CFG_CORE_HEAP_SIZE ?= 65536
+#CFG_CORE_HEAP_SIZE ?= 65536
+CFG_CORE_HEAP_SIZE ?= 262144
```

If I change the existing 64KB to 256KB, I can check the value as below.
```
# xtest --stats --alloc
Pool:                Heap
Bytes allocated:                       20384
Max bytes allocated:                   20848
Size of pool:                          265328
Number of failed allocations:          0
Size of larges allocation failure:     0
Total bytes allocated at that failure: 0
```

I don't think it's completely unrelated. What do you think?

**Comment by zwb-233** [comment]
I feel that we seem to have a similar problem. Recently, we have been using Optee 4.0 and HiKey 960 to compile our code, and we are attempting to increase the sizes of `share_memory` and `secure_memory`. We made some changes as follows:
```
optee_os/core/arch/arm/plat-hikey/conf.mk
Line 10: Modify CFG_NUM_THREADS to 64.
Line 56: Modify CFG_TZDRAM_START from 0x3F000000 to 0x40E00000 (+30MB).
Line 57: Modify CFG_TZDRAM_SIZE from 0x01000000 (16MB) to 0x20000000 (512MB).
Line 59: Modify CFG_SHMEM_SIZE from 0x00200000 (2MB) to 0x02000000 (32MB).
Line 60: Modify CFG_TEE_RAM_VA_SIZE from 0x00200000 (2MB) to 0x00800000 (8MB).

optee_os/core/arch/arm/plat-hikey/platform_config.h
Line 108: Modify DRAM0_SIZE from 0x3F000000 to 0x40E00000.
Line 110: Modify DRAM1_BASE value from 0x40000000 to 0x60E00000.
Line 133: Modify DRAM1_SIZE_NESC from 0xA0000000 to 0xE0000000 - 0x60E00000 = 0x7F200000.

trusted-firmware-a/plat/hisilicon/hikey960/hikey960_def.h
Line 31: Modify DDR_SEC_SIZE from 0x01000000 to 0x20000000.
Line 32: Modify DDR_SEC_BASE from 0x3F000000 to 0x40E00000.

optee_os/core/arch/arm/plat-hikey/main.c
Replace deprecated register_dynamic_shm() with register_ddr() instead in Line 36-41.
```

At the beginning,  we used the command `make -j8 PLATFORM=hikey-hikey960 CFG_DRAM_SIZE_GB=4 CFG_ARM64_core=y COMPILE_S_USER=64` for compilation. However, we encountered failures when attempting to allocate a larger space than the default `share_memory` size.It seems that the modification was not successful.

Later, we tried adding `CFG_CORE_DYN_SHM=n` to make, and the shared memory could be allocate successfully.

Moreover, we found that with this configuration, there is an allocation limit for secure_memory. Exceeding this limit results in an error with the code `ffff000c`. This limit persists even after modifying the configuration to 1024MB and is approximately around 250MB.

We also tried modifying `CFG_CORE_HEAP_SIZE`, changing it from 73728 (72KB) to 131072 (128KB), but it seems that this change did not take effect.

Later, we attempted to change CFG_NUM_THREADS on Line 10 in optee_os/core/arch/arm/plat-hikey/conf.mk to 128.Now, we are able to allocate 480MB of memory.

@jenswi-linaro ,`CFG_CORE_HEAP_SIZE` can address this problem? After modifying `CFG_CORE_HEAP_SIZE`, do we need to change other parameters? If this approach is viable, we may continue modifying our code based on this solution.
Thanks

**Comment by jenswi-linaro** [comment]
> Later, we attempted to change CFG_NUM_THREADS on Line 10 in optee_os/core/arch/arm/plat-hikey/conf.mk to 128.Now, we are able to allocate 480MB of memory.

This suggests that you have previously been running out of translation tables in the pgt_cache, they are defined in `core/include/mm/pgt_cache.h` as `PGT_CACHE_SIZE`. Have been using a very large TA (size counted in megs rather than kBs)?
``` C
/*      
 * A proper value for PGT_CACHE_SIZE depends on many factors: CFG_WITH_LPAE,
 * CFG_TA_ASLR, size of TA, size of memrefs passed to TA, CFG_ULIBS_SHARED and
 * possibly others. The value is based on the number of threads as an indicator
 * on how large the system might be.
 */
#if CFG_NUM_THREADS < 2
#define PGT_CACHE_SIZE  4
#elif (CFG_NUM_THREADS == 2 && !defined(CFG_WITH_LPAE))
#define PGT_CACHE_SIZE  8
#else
#define PGT_CACHE_SIZE  ROUNDUP(CFG_NUM_THREADS * 2, PGT_NUM_PGT_PER_PAGE)
#endif
```

There's an option to use CFG_CORE_PREALLOC_EL0_TBLS=y that uses a different method to allocate the translation tables needed for S-EL0 mappings. This method might be more suitable in systems where you need to map large amounts of memory for S-EL0.

**Comment by zwb-233** [comment]
> There's an option to use CFG_CORE_PREALLOC_EL0_TBLS=y that uses a different method to allocate the translation tables needed for S-EL0 mappings. This method might be more suitable in systems where you need to map large amounts of memory for S-EL0.

@jenswi-linaro , thanks. Recently, We tried replacing the modification of `CFG_NUM_THREADS` with `CFG_CORE_PREALLOC_EL0_TBLS=y`, but unfortunately, it didn't yield similar results(1024MB). Shall we need to change other parameters?

**Comment by TaihuLight** [comment]
@jenswi-linaro we conducted detailed tests on the impact of CFG_NUM_THREADS and CFG_CORE_PREALLOC_EL0_TBLS for TA size. We used a test program that only requests secure memory space, as well as our own program consisting of two TAs, to test the maximum amount of TA space that can be allocated. The results are shown in the table below. The first three columns in the table represent the values of the corresponding configuration items, while the last two columns represent the maximum number of megabytes.

<html>
<body>

CFG_NUM_THREADS | CFG_CORE_PREALLOC_EL0_TBLS | Test Program | Own (2 TAs)
-- | -- | -- | --
8 | y | 450MB | 55MB
8 | n | 20MB | <25MB
16 | y | 660MB | 85MB
16 | n | 28MB | <25MB
32 | y | 660MB | 85MB
32 | n | 92MB | 60MB
64 | y | 660MB | 85MB
64 | n | 220MB | 120MB
128 | y | 660MB | 85MB
128 | n | 475MB | 250MB


</body>
</html>

**Comment by jenswi-linaro** [comment]
Nice table. You need to dig a bit deeper to better understand why the allocations fail. I suspect that you have more than one limit in play here. The sizes you're using far exceed what we consider normal use cases, but we're of course interested in supporting this too if you're able to find out what needs to be fixed.
