### ISSUE TITLE
How to use mbedtls in ta

### ISSUE THREAD

**Issue by oldoldcoder** [OP-TEE/optee_os#6597]
In the manner described, I introduced the appropriate header files:

<img width="408" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/bd3d7e8b-9a3c-492e-8c1a-d0b6f8658c95">

Also add the commands from the previous answer to the Makefile.

<img width="965" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/107dc28f-a4b4-4f45-b2f5-eef583d1bcfd">

But at the moment the compilation suggests that the header file cannot be found.
1. what should i do to solve this problem, what is the process of introducing non-standard libraries into ta?
2. Also what is meant by the previous reply that mbedtls is integrated into optee?
3. what does the content in https://optee.readthedocs.io/en/latest/architecture/libraries.html#libmbedtls refer to?

**Comment by ancientmodern** [comment]
Hello, have you found any examples of working with mbedtls in TA?
