### ISSUE TITLE
While upgrading the OP-TEE version to 4.1.0-rc, a segmentation fault occurred

### ISSUE THREAD

**Issue by zwb-233** [OP-TEE/optee_os#6601]
Hello OP-TEE team,

I have a project that uses Hikey960 & OP-TEE version 3.20, and it runs successfully on this version. Now, I want to upgrade it to version 4.1.0-rc.

I am using the repository https://github.com/OP-TEE/manifest.git with the tag 4.0.0. Then, I am individually upgrading optee_os to version 4.1.0-rc. I use the following compilation command:
`
make PLATFORM=hikey-hikey960 COMPILE_S_USER=64 CFG_DRAM_SIZE_GB=4 CFG_CORE_LARGE_PHYS_ADDR=y CFG_TEE_CORE_LOG_LEVEL=4 CFG_ARM64_core=y CFG_NUM_THREADS=64 CFG_TEE_RAM_VA_SIZE=0x00400000 CFG_TZDRAM_SIZE=0x04000000 CFG_DRAM1_BASE=0x430000000
`
The compilation is successful.

However, whether I use the export-ta_arm64 generated by version 3.20 or the one generated by version 4.1.0-rc, running the code results in a segmentation fault.

The following is the error output generated by the export-ta_arm64 from **version 4.1.0-rc**:
D/TC:? 0 tee_ta_init_session_with_context:561 Re-open TA ebf27aea-8019-8f98-4964
D/TC:? 0 tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA eff27aea-8019-8f98-4
D/TC:? 0 ldelf_load_ldelf:110 ldelf load address 0x80007000
D/LD:  ldelf:142 Loading TS eff27aea-8019-8f98-4963-406233b51e44
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF eff27aea-8019-8f98-4963-)
D/TC:? 0 ldelf_syscall_open_bin:167 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF eff27aea-8019-8f98-4963-)
D/TC:? 0 ldelf_syscall_open_bin:167 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF eff27aea-8019-8f98-4963-)
D/TC:? 0 ldelf_syscall_open_bin:167 res=0
E/LD:  populate_segments:883 sys_map_zi
E/TC:? 0 ldelf_init_with_ldelf:152 ldelf failed with res: 0xffff000c
D/TC:? 0 tee_ta_open_session:689 init session failed 0xffff000c
D/TC:? 0 tee_ta_close_session:463 csess 0x3f0a2310 id 2
D/TC:? 0 tee_ta_close_session:482 Destroy session

The following is the error output generated by the export-ta_arm64 from **version 3.20**:
D/TC:1 0 core_mmu_xlat_table_alloc:527 xlat tables use8
D/TC:? 0 tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA ebf27aea-8019-8f98-4
D/TC:? 0 ldelf_load_ldelf:110 ldelf load address 0x80007000                     
D/LD:  ldelf:142 Loading TS ebf27aea-8019-8f98-4963-406233b51e44                
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF ebf27aea-8019-8f98-4963-)
D/TC:? 0 ldelf_syscall_open_bin:167 res=0xffff0008                              
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF ebf27aea-8019-8f98-4963-)
I/TC: WARNING (insecure configuration): Failed to get monotonic counter for REE0
D/TC:? 0 ldelf_syscall_open_bin:167 res=0xffff0008                              
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF ebf27aea-8019-8f98-4963-)
D/TC:? 0 ldelf_syscall_open_bin:167 res=0                                       
D/LD:  ldelf:176 ELF (ebf27aea-8019-8f98-4963-406233b51e44) at 0x8008e000       
D/TC:? 0 tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA eff27aea-8019-8f98-4
D/TC:? 0 ldelf_load_ldelf:110 ldelf load address 0x80007000                     
D/LD:  ldelf:142 Loading TS eff27aea-8019-8f98-4963-406233b51e44                
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF eff27aea-8019-8f98-4963-)
D/TC:? 0 ldelf_syscall_open_bin:167 res=0xffff0008                              
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF eff27aea-8019-8f98-4963-)
D/TC:? 0 ldelf_syscall_open_bin:167 res=0xffff0008                              
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF eff27aea-8019-8f98-4963-)
D/TC:? 0 ldelf_syscall_open_bin:167 res=0                                       
E/LD:  populate_segments:883 sys_map_zi                                         
E/TC:? 0 ldelf_init_with_ldelf:152 ldelf failed with res: 0xffff000c            
D/TC:? 0 tee_ta_open_session:689 init session failed 0xffff000c  

Thanks

**Comment by oldoldcoder** [comment]
Sorry to disturb an already closed question, but I wanted to ask if you resolved this issue?
