### ISSUE TITLE
Why is MMU_NUM_ASID_PAIRS set to 64?

### ISSUE THREAD

**Issue by LeiSen62** [OP-TEE/optee_os#6607]
For ARMv7-A and ARMv8-A Aarch32, the ASID max is 255, should MMU_NUM_ASID_PAIRS be set to 128?

**Comment by jenswi-linaro** [comment]
No, the max would be 126 if you read the comment just above the define. Are you running into this limit or just curious?

**Comment by LeiSen62** [comment]
Yes，I had run into the limit。When I have more than 64 sessions open at the same time，"Failed to allocate ASID" will be reported.

**Comment by jenswi-linaro** [comment]
We could update it to use the maximum supported for AArch32 and AArch64 respectively. Would you mind creating a pull request?

**Comment by LeiSen62** [comment]
I will create a pull request to update it soon.
