### ISSUE TITLE
Sample test case for TEE_ALG_ECDH_DERIVE_SHARED_SECRET algorithm

### ISSUE THREAD

**Issue by dhruv77777** [OP-TEE/optee_os#6609]
Hi Team,

Is there any test case or sample test code available to check the functionality of "TEE_DeriveKey" using the algorithm "TEE_ALG_ECDH_DERIVE_SHARED_SECRET". As i can see the xtest cases are defined for other algorithms but not for this algorithm.

**Comment by dhruv77777** [comment]
@jforissier Is there any update on this?

**Comment by jforissier** [comment]
@dhruv77777 that's true, we have no test for `TEE_ALG_ECDH_DERIVE_SHARED_SECRET`.
