### ISSUE TITLE
android can't boot up in hikey board

### ISSUE THREAD

**Issue by louisjohn0416** [OP-TEE/optee_os#662]
when i build android filesystem from source code with the help of this link:
http://wiki.lemaker.org/HiKey(LeMaker_version):Build_AOSP_from_Source_Code.
i found that i can't boot up android due to surfaceflinger can't run with following error message:
Abort message: 'couldn't find an OpenGL ES implementation'

So my question is how can i get the corresponding hikey opengl library, i find android source will not 
generate these libraries. Thank you !

**Comment by hybridNeo** [comment]
https://github.com/jforissier/hikey_optee/tree/aosp

Try this out, It works for me

**Comment by jbech-linaro** [comment]
Hi @louisjohn0416 ,

We're about to wrapping up Android builds based on Google's official tree for HiKey. It's not 100% done yet, but you can have a sneak peak here: https://github.com/d3zd3z/optee_android_manifest
Those instructions will be moved to the official OP-TEE and linaro-swg very soon, so please have a look there again within a week or two.

**Comment by jbech-optee-adm** [comment]
Question has been answered, but If the issue persists or you have more questions, please re-open the issue.
