### ISSUE TITLE
Getting error in building optee_os

### ISSUE THREAD

**Issue by prajeesh-mohan** [OP-TEE/optee_os#663]
Hello,

I am getting the following compilation error while trying to build optee_os on my machine.

Traceback (most recent call last):
  File "scripts/pem_to_pub_c.py", line 79, in <module>
    main()
  File "scripts/pem_to_pub_c.py", line 45, in main
    from Crypto.PublicKey import RSA
ImportError: No module named Crypto.PublicKey

My Python version is 2.7.5
ubuntu version: 14.04 LTS (64 bit)

Can anyone please help me out?

Prajeesh

**Comment by jforissier** [comment]
`sudo apt-get install python-crypto` maybe? (not sure for Ubuntu 14.04, I have been using 15.04 for a while and just switched to 15.10).
See https://github.com/OP-TEE/optee_os/blob/master/README.md#41-prerequisites

**Comment by prajeesh-mohan** [comment]
I tried installing python-crypto. And also installed all the prerequisites...
But the problem still exist.

**Comment by prajeesh-mohan** [comment]
Is there any specific version of python is required or 2.7.5 shall work?

**Comment by pascal-brand-st-dev** [comment]
I am using python 2.7.6 successfully on Ubuntu 14.04.

In a previous environment (could not remember which python version I had), I did the following to install the crypto lib locally:

    wget https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz
    tar xf pycrypto-2.6.1.tar.gz
    cd pycrypto-2.6.1/
    python setup.py build
    python setup.py install --home=/home/brand/local/
    export PYTHONPATH=/home/brand/local/lib/python

**Comment by prajeesh-mohan** [comment]
I updated to 15.10 and the issue disappeared :)
Thanks for the support

**Comment by sooorajjj** [comment]
Have this issue on 
Linux dayo 4.19.78-1-MANJARO #1 SMP PREEMPT Mon Oct 7 20:24:34 UTC 2019 x86_64 GNU/Linux

**Comment by etienne-lms** [comment]
Maybe this can help: https://optee.readthedocs.io/en/latest/building/prerequisites.html
