### ISSUE TITLE
Transition to Kconfig?

### ISSUE THREAD

**Issue by igoropaniuk** [OP-TEE/optee_os#6632]
Taking into account amount of existing config options/its dependencies in OP-TEE OS, have you considered/or have already plans (and if such contributions would be welcome) to make transition to Kconfig/Kbuild in future for to better dependency tracking and unification of some of existing config options?

**Comment by ricardosalveti** [comment]
I think Zephyr is using it, and it is licensed under Apache-v2: https://github.com/zephyrproject-rtos/zephyr/blob/main/Kconfig

**Comment by jforissier** [comment]
@ricardosalveti that's interesting. I can see a mix of Apache 2.0 and ISC licensed files in this implementation (https://github.com/zephyrproject-rtos/zephyr/blob/main/scripts/kconfig/). That would be OK to use in OP-TEE IMO.

**Comment by jenswi-linaro** [comment]
That's also my view since the Kconfig code isn't part of the compiled binary.

**Comment by jenswi-linaro** [comment]
I even made a quick attempt at this a few years ago but stopped before I had anything useful since it was evident that it would take too much time to do without proper prioritization. To address the license issue I added a note like:

``` diff
diff --git a/scripts/kconfig/README.license b/scripts/kconfig/README.license
new file mode 100644
index 000000000000..99bc9715071e
--- /dev/null
+++ b/scripts/kconfig/README.license
@@ -0,0 +1,8 @@
+This subdirectory is imported from the Linux kernel, scripts/kconfig
+
+The default license of the Linux kernel applies from this point and downwards.
+
+Note that none if these files are sources for the software running on the
+target system. These files are only compiled for the host compiling and
+configuring the software. So the final OP-TEE binaries are not affected
+by the licenses in used in this subtree.
```

But I think we should make sure that this is true or we may face a very difficult situation.

**Comment by igoropaniuk** [comment]
And the tool itself is licenced under ISC License:
```
A permissive license lets people do anything with your code with proper attribution and without warranty. The ISC license is functionally equivalent to the BSD 2-Clause and MIT licenses, removing some language that is no longer necessary.
```

**Comment by jenswi-linaro** [comment]
That sounds like a much better option, provided that it's stable enough. We want to avoid having to depend on certain versions and so on.

**Comment by etienne-lms** [comment]
My 2 cents: indeed a good idea to use Kconfig or some equiv resources to have a more standard OP-TEE configuration framework (documentation, dependencies, ...).

**Comment by igoropaniuk** [comment]
As the main purpose of this issue was to find out plans for Kconfig (and quite a lot of input was received), closing it
