### ISSUE TITLE
SMC FIQ IRQ Interrupts timeouts

### ISSUE THREAD

**Issue by mardyr** [OP-TEE/optee_os#6635]
Hi guys, 

I've looked into the code, but I didn't found a answer, so here I am.

I am wondering for how long SMC call(fast and standard) could be executed -> I've looked in ATF as Secure Monitor is responsible for that but I haven't found a number(amount of time). On top of that I am looking for secure thread suspending timeout, I mean in case of foreign interrupt.

**Comment by jenswi-linaro** [comment]
There are no limits for fast calls, but we try to keep them short enough. Standard calls or yielding calls are preemptible so they are less of an issue.

**Comment by mardyr** [comment]
There as some time limitations for standard calls?
