### ISSUE TITLE
Execution time measurement in TEE kernel mode

### ISSUE THREAD

**Issue by nolzaheo** [OP-TEE/optee_os#6646]
Hello, I'm trying to measure execution time of a function in user_ta.c.
Is there any way to use TEE_GetSystemTime() in TEE kernel mode?
I've tried, but implicit declaration of function error occurred.

Thank you

**Comment by etienne-lms** [comment]
Rather use `tee_time_get_sys_time()` from TEE kernel mode.

**Comment by nolzaheo** [comment]
@etienne-lms Thanks for your help! :)
