### ISSUE TITLE
Tests required before submitting a PR

### ISSUE THREAD

**Issue by liang-yan-yu** [OP-TEE/optee_os#6647]
Hi, 
I am a engineer from Macronix. We plan to create a pull request to add driver support for our secure flash products in OP-TEE. I have two questions about testing our work: 

1. Is there any required tests I need to run before sending out a PR? Currently, I have already dived into `optee_test` project and run the test with our driver, is that enough to evaluate our work?
2. Because the storage test in `optee_test` mainly focuses on testing the GlobalPlatform secure storage API, it does not tend to test the specific hardware features. Is there any tests that aim to test hardware drivers? Or do we need to provide the test cases on our own?

**Comment by jforissier** [comment]
Hi @liang-yan-yu,

At a minimum we want:
- no breakage in the current CI, obviously (which involves building many platforms and running tests, including `optee_test` with QEMU)
- a build test for your driver in the CI loop (https://github.com/OP-TEE/optee_os/blob/4.1.0/.github/workflows/ci.yml#L264). Typically this means adding a line: `make PLATFORM=xxx CFG_<your_driver>=y` or something like that.

Having a runtime test would of course be nice. You may extend `optee_test` for that. You would be responsible for maintaining the test code and also running the test and reporting if all is good when we do the quarterly releases (see the Tested-by: tags in https://github.com/OP-TEE/optee_os/pull/6574 for example).

**Comment by liang-yan-yu** [comment]
Thanks, I'll have a look on it.
