### ISSUE TITLE
How to setup configuration without dedicate cores for OPTEE.

### ISSUE THREAD

**Issue by gurisong** [OP-TEE/optee_os#6650]
Hi experts,

I want to know how to setup configuration without dedicate cores for OPTEE. If possible, I want to know if there are any problems or issues.

Thanks

**Comment by gurisong** [comment]
We are considering a 2-core system and we want OP-TEE to work without any performance issues on both cores, without a dedicated core. would you please let me know how to setup it for this.

**Comment by jenswi-linaro** [comment]
> We are considering a 2-core system and we want OP-TEE to work without any performance issues on both cores, without a dedicated core. would you please let me know how to setup it for this.

That's the default configuration, so it should already work as you expect it.
