### ISSUE TITLE
Does optee support static TA

### ISSUE THREAD

**Issue by Chengde3** [OP-TEE/optee_os#666]
Could a TA be run right after the start of secure world and before the run of normal world?
Looking forward to answers.

**Comment by vchong** [comment]
Yes. Static TAs are compiled directly into the core. See files in `core/arch/arm/sta` for some examples of static TAs.

**Comment by Chengde3** [comment]
Thanks for your information and i found the code. 
Is there any document about that or some more detail information for more complex examples?
btw, we don't want to compile the static ta into the core and could a ta in user space to be static?

**Comment by jenswi-linaro** [comment]
No, static user space TAs are not supported.

**Comment by Chengde3** [comment]
i see, lots of thanks~

**Comment by aminusamine** [comment]
Hello, 

i'm interested with a static TA, is there any document or tutorial explaining how to write it and especially how to compile it with the core. 

Thanks

**Comment by pascal-brand-st-dev** [comment]
No, there is no current documentation. Nothing is really tricky. You can use https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/sta/stats.c as an example:

* define an uuid for your TA and the command ID
* define `static_ta_register` with your entry-point functions
* add your file in https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/sta/sub.mk

Please close this issue if it answers.

**Comment by aminusamine** [comment]
Hello, 

Thank you for the previous answer, it was very clear. 

However after writing a static TA, how to execute it on the secure world on fvp_optee ?

Thanks again.

**Comment by pascal-brand-st-dev** [comment]
The static TA can be called as any User-TA, using OpenSession and InvokeCommand. You can have a look at xtest 1001 that now uses the self-test static TA.

Please close this issue if it answers.

**Comment by aminusamine** [comment]
I don't think i have fully understand what you explained. In my case, i have a static TA which encrypts with AES 128 a static const char*,  i wrote it and added a uuid and a command ID, static_ta_register and i added my file to optee_os/core/arch/arm/sta/sub.mk. but i didn't find it when i turned on the optee in FVP.

I hope it is clear enough to allow you helping me

**Comment by targetnull** [comment]
I just tested the static TA using a simple Client application similar to [hello world](https://github.com/jenswi-linaro/lcu14_optee_hello_world), and it seemed that I can use a normal client application to communicate with it, as if it is a dynamic TA. I guess the TA is designed to be transparent to CAs.
My example is very simple, I cannot assure that it would be the same when things gets complicated, I am learning OP-TEE as well.
I hope that helps you.

**Comment by aminusamine** [comment]
I don't understand how i can test it, how i can put it on the TEE as i did with a normal TA  by compiling it and add it to the filelist.txt if you can help with steps to perform before you can execute it on the TEE side

**Comment by targetnull** [comment]
@aminusamine When you compile optee_os, static TAs will be compiled at the same time, so you don't have to add it to filelist.
When you open a session, the optee will load the static TA, I find it's code [here](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/static_ta.c#.L168).

**Comment by aminusamine** [comment]
Thank you, i have an error when compiling the optee_os, armv7-linux-gcc is not found, i installed gcc-arm-linux-gnueabi  and i have the same problem, did you know how to fix it ?

**Comment by targetnull** [comment]
Maybe you forget to set `CROSS_COMPILE`? Also, you need to set `TEEC_EXPORT`
I don't know the details of your script, but the instructions in the [hello world](https://github.com/jenswi-linaro/lcu14_optee_hello_world#build-instructions) might be helpful.

**Comment by pascal-brand-st-dev** [comment]
Please have a look at https://github.com/OP-TEE/optee_os/blob/master/README.md#5-repo-manifests.
`make toolchains` in build repository should do the job.

Please close this issue if it answers.

**Comment by aminusamine** [comment]
it didn't work, i did all what specify the manifest, i have many "normal" TA that i execute normally, i'm now trying to compile the optee_os and i have a problem with  armv7-linux-gcc. In the toolchains file i have aarch32, aarch64 aarch64-none-elf but the error is : /bin/bash: armv7-linux-gcc: command not found

**Comment by aminusamine** [comment]
Can someone help me with this please ?

Thanks

**Comment by pascal-brand-st-dev** [comment]
Are you able to use repo without any changes?

**Comment by aminusamine** [comment]
Yes, in the case of a non static TA i'm able to compile and run the optee with the wanted TA. I can execute it normally. But in the case of a static TA, what i understood is that i have to compile again optee_os to use the static TA after running the platform if i understood well. 

I tried to run the script build_optee_os.sh it succeed, but if i go into optee_os directory and use the Makefile i have this problem 

/bin/bash: armv7-linux-gcc: command not found and

make: *** [out/arm-plat-stm/core/arch/arm/kernel/tee_ta_manager.o] Error 127

if the compilation of the static TA succeed, should i find it in /bin in  optee while running ?

**Comment by pascal-brand-st-dev** [comment]
`build_optee_os.sh` was an auto-generated script, but this script is no more generated since version 1.0.0

You should go in build, and `make optee-os`

Please close this issue if it answers

**Comment by aminusamine** [comment]
I Think i have an older version because i have not a folder named build. Should i update to the new version or it is possible to get the same functionalities in my version ?

**Comment by pascal-brand-st-dev** [comment]
Yes please.

**Comment by aminusamine** [comment]
I have to re-download or their is a mechanism to update ?

**Comment by pascal-brand-st** [comment]
Please re-download from scratch and follow instructions from https://github.com/OP-TEE/optee_os/blob/master/README.md

Please re-open in case you have more questions or it didn't solve the issue
