### ISSUE TITLE
question about how to run OP-TEE using QEMU for RISCV (either 32 or 64)

### ISSUE THREAD

**Issue by aousherovitch-tt** [OP-TEE/optee_os#6668]
Hello,
In https://optee.readthedocs.io/en/latest/building/gits/build.html and https://optee.readthedocs.io/en/latest/building/devices/qemu.html I see instructions for building and running OP-TEE using QEMU for Armv8-A.
Can you please advise how the RISCV related changes in OP-TEE are being tested (presumably on qemu?).
I've tried running the following

```
ARCH=riscv make -j2 toolchains
ARCH=riscv make run 
```
and the toolchain was built ok, but make run fails, it is still expecting to build and run for ARM:

```
% ARCH=riscv make run
make -C /data/aousherovitch/prj/optee/build/../optee_os O=out/riscv CFG_USER_TA_TARGETS=ta_rv64 CFG_RV64_core=y PLATFORM=vexpress-qemu_armv8a CROSS_COMPILE="/usr/bin/ccache /data/aousherovitch/prj/optee/build/../toolchains/riscv64/bin/riscv64-unknown-linux-gnu-" CROSS_COMPILE_core="/usr/bin/ccache /data/aousherovitch/prj/optee/build/../toolchains/riscv64/bin/riscv64-unknown-linux-gnu-" CROSS_COMPILE_ta_rv64="/usr/bin/ccache /data/aousherovitch/prj/optee/build/../toolchains/riscv64/bin/riscv64-unknown-linux-gnu-" CROSS_COMPILE_ta_rv32="/usr/bin/ccache " CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=0 CFG_IN_TREE_EARLY_TAS="trusted_keys/f04a0fe7-1f5d-4b9b-abf7-619b85b4ce8c" DEBUG=0 CFG_ARM_GICV3=y 
make[1]: Entering directory '/data/aousherovitch/prj/optee/optee_os'
core/arch/riscv/riscv.mk:72: *** CFG_ARM_GICV3 is set to 'y' (from command line) but its value must be 'n'.  Stop.
make[1]: Leaving directory '/data/aousherovitch/prj/optee/optee_os'
make: *** [common.mk:550: optee-os-common] Error 2
```
looking more at the https://github.com/OP-TEE/optee_os/blob/master/.github/workflows/ci.yml and the build make files in https://github.com/OP-TEE/build (and manifest files in https://github.com/OP-TEE/manifest) - does not seem like the riscv support is there yet.
Please advise.
Thank you

**Comment by gagachang** [comment]
Hello @aousherovitch-tt 
The RISC-V port is WIP. There are still some patches to be pushed and merged in near future.

**Comment by aousherovitch-tt** [comment]
Hi @gagachang ,
yes, I understand that, was curious about whether/how these patches get built and verified in the interim.
Thanks

**Comment by gagachang** [comment]
Hi @aousherovitch-tt 

Maybe you can check my previous PR
https://github.com/OP-TEE/build/pull/694

Note that patches for openSBI and Linux are not submitted to upstream yet.

**Comment by aousherovitch-tt** [comment]
Hi @gagachang 
not sure how to use it w/o the updates to opensbi (and linux) AND without the integrated build environment that allows building it all together.
I have tried bringing over the latest opensbi under the $(ROOT), but meanwhile I am having issues with my build environment - I am using Ubuntu 20.04.6 LTS and the latest libc6 there is 2.31-0ubuntu9.14, but the toolchain from riscv64-glibc-ubuntu-22.04-gcc-nightly-2023.07.07-nightly.tar.xz appears to require glibc 2.32, 2.33 and 2.34.  I will try to build my own toolchain and see if that helps.
Btw, I was running the following build commands with your make files:
```
cd $(ROOT)/build
ARCH=riscv make toolchains                                                                              ARCH=riscv make -f qemu_riscv64.mk 
```
If I will manage to fix the build issues, then I can try                                                           `ARCH=riscv make -f qemu_riscv64.mk run-only`
Hope I did not miss anything obvious.
Thank you

**Comment by aousherovitch-tt** [comment]
@gagachang - after I've changed toolchain.mk to point RISCV64_GCC_VERSION to riscv64-glibc-ubuntu-20.04-gcc-nightly-$(RISCV64_GCC_RELEASE_DATE)-nightly instead of riscv64-glibc-ubuntu-22.04-gcc-nightly-$(RISCV64_GCC_RELEASE_DATE)-nightly, the build completes. 
But to run, rootfs.ext2 had to be generated and it was not:
```
cd /data/aousherovitch/prj/optee/build/../out/bin && /data/aousherovitch/prj/optee/build/../qemu/build/qemu-system-riscv64 \
        -nographic \
        -serial tcp:127.0.0.1:54320 -serial tcp:127.0.0.1:54321 \
        -machine virt \
        -smp 1 \
        -d unimp -semihosting-config enable=on,target=native \
        -m 2048 \
        -bios fw_jump.bin \
        -kernel Image \
        -append "rootwait root=/dev/vda ro" \
        -drive file=rootfs.ext2,format=raw,id=hd0 \
        -device virtio-blk-device,drive=hd0 \
        -device loader,file=tee.bin,addr=0x8e000000
qemu-system-riscv64: -drive file=rootfs.ext2,format=raw,id=hd0: Could not open 'rootfs.ext2': No such file or directory
make: *** [qemu_riscv64.mk:164: run-only] Error 1

% ll /data/aousherovitch/prj/optee/build/../out/bin/
total 24
drwxrwxr-x 2 aousherovitch aousherovitch 4096 Feb 20 15:23 ./
drwxrwxr-x 3 aousherovitch aousherovitch 4096 Feb  1 14:43 ../
lrwxrwxrwx 1 aousherovitch aousherovitch  107 Feb 20 15:22 fw_jump.bin -> /data/aousherovitch/prj/optee/build/../opensbi/install/usr/share/opensbi/lp64/generic/firmware//fw_jump.bin*
lrwxrwxrwx 1 aousherovitch aousherovitch   66 Feb 20 15:22 Image -> /data/aousherovitch/prj/optee/build/../linux/arch/riscv/boot/Image*
lrwxrwxrwx 1 aousherovitch aousherovitch   64 Feb 20 15:23 rootfs.ext2 -> /data/aousherovitch/prj/optee/build/../out-br/images/rootfs.ext2
lrwxrwxrwx 1 aousherovitch aousherovitch   70 Feb 20 15:22 tee.bin -> /data/aousherovitch/prj/optee/build/../optee_os/out/riscv/core/tee.bin*

% ll /data/aousherovitch/prj/optee/build/../out-br/images
total 49212
drwxr-xr-x 2 aousherovitch aousherovitch     4096 Feb 20 15:22 ./
drwxrwxr-x 7 aousherovitch aousherovitch     4096 Feb 20 15:22 ../
-rw-r--r-- 1 aousherovitch aousherovitch 20633600 Feb 20 15:22 rootfs.cpio
-rw-r--r-- 1 aousherovitch aousherovitch  8273466 Feb 20 15:22 rootfs.cpio.gz
-rw-r--r-- 1 aousherovitch aousherovitch 21473280 Feb 20 15:22 rootfs.tar
```

**Comment by gagachang** [comment]
Hi @aousherovitch-tt 

What I want to show to you is the command to build optee_os.
Linux and openSBI have some patches , which has not been submitted to upstream.
I expect that you can not boot to optee_os, unless you modified Linux and openSBI by yourself.

**Comment by gagachang** [comment]
>  But to run, rootfs.ext2 had to be generated and it was not:

Did you compile the buildroot?
rootfs.ext2 should be compiled into your `/data/aousherovitch/prj/optee/out-br/images`.
And I've softlink it into binary path by the following command, before running QEMU:
```
ln -sf $(ROOT)/out-br/images/rootfs.ext2 $(BINARIES_PATH)/
```

**Comment by aousherovitch-tt** [comment]
I did run 
`ARCH=riscv make -j32 -f qemu_riscv64.mk all` 
and also tried 
`ARCH=riscv make -j32 -f qemu_riscv64.mk buildroot`
but after both $(ROOT)/out-br/images/rootfs.ext2 is not generated, only the following is there:
```
 % ll /data/aousherovitch/prj/optee/out-br/images/
total 49216
drwxr-xr-x 2 aousherovitch aousherovitch     4096 Feb 20 15:22 ./
drwxrwxr-x 7 aousherovitch aousherovitch     4096 Feb 20 19:05 ../
-rw-r--r-- 1 aousherovitch aousherovitch 20633600 Feb 20 19:05 rootfs.cpio
-rw-r--r-- 1 aousherovitch aousherovitch  8274267 Feb 20 19:05 rootfs.cpio.gz
-rw-r--r-- 1 aousherovitch aousherovitch 21473280 Feb 20 19:05 rootfs.tar
```
How do you compile buildroot / generate rootfs.ext2?

> What I want to show to you is the command to build optee_os.
> Linux and openSBI have some patches , which has not been submitted to upstream.
> I expect that you can not boot to optee_os, unless you modified Linux and openSBI by yourself.
Do you have a prototype somewhere and/or expect to raise a PR some time with these patches in the foreseeable future?
I assume that the security monitor will be a part of the openSBI changes?
Thank you!

**Comment by gagachang** [comment]
Hi @aousherovitch-tt 

> How do you compile buildroot / generate rootfs.ext2?

Could you try to add `BR2_TARGET_ROOTFS_EXT2=y` into `qemu_riscv64.mk` ?
I must forget to add this option into  `qemu_riscv64.mk`.

> Do you have a prototype somewhere 

Currently no.

>  expect to raise a PR some time with these patches in the foreseeable future?

Yes, it is now part of RISE project (https://wiki.riseproject.dev/display/HOME/OPTEE_00_01+-+OP-TEE+support).

> I assume that the security monitor will be a part of the openSBI changes?

Yes, it would be a new SBI extension for those features related to TEE.

**Comment by aousherovitch-tt** [comment]
Hi @gagachang 

> Could you try to add BR2_TARGET_ROOTFS_EXT2=y into qemu_riscv64.mk ?
> I must forget to add this option into qemu_riscv64.mk.

yes, that was it, now everything builds and runs within the expected limitations.
Thank you
