### ISSUE TITLE
RPMB key writing with RPMB_EMU=1 on i.MX8 platforms

### ISSUE THREAD

**Issue by awais11010** [OP-TEE/optee_os#6674]
Hello,

I am working with OP-TEE (3.19) on an i.MX8M Nano platform where we'd like to utilize RPMB as a secure store. I was able to develop the TA/CA combo as per needs following the amazing resources available in the docs and around the web.
The issue I am dealing with at this point relates to manufacturing vs production builds (Yocto based). We're working on modifying our manufacturing process to account for what's needed by OP-TEE for RPMB key provisioning and we have a plan that would sort this out. However, I'd like some input on this

OPTEE-OS manufacturing image
- CFG_RPMB_WRITE_KEY=y
- CFG_RPMB_FS=y (and related ones)
- CFG_REE_FS=n

OPTEE-Client manufacturing image
- RPMB_EMU=1

OPTEE-OS production image
- CFG_RPMB_WRITE_KEY=n
- CFG_RPMB_FS=y (and related ones)
- CFG_REE_FS=n

OPTEE-Client production image
- RPMB_EMU=0

It is pretty evident that a combination of OPTEE-OS manufacturing with OPTEE-Client production will allow us to provision the key correctly (device to be closed before this) for the actual device. Once provisioned, we can simply switch to OPTEE-OS production and the key will remain secure. Is this understanding correct?

Furthermore, we run our tests with manufacturing images (i.e. CFG_RPMB_WRITE_KEY=y, RPMB_EMU=1) and I was hoping that this will work as the key would [simply be written to the emulated RPMB device](https://github.com/OP-TEE/optee_os/issues/3555#issuecomment-579301064) and we'll use the emulated device for testing. Unfortunately, it turns out that this might not be as expected because on i.MX8 platforms [plat_rpmb_key_is_ready](https://github.com/OP-TEE/optee_os/blob/master/core/drivers/imx_snvs.c#L161) always returns false if the device is not already closed and hence key writing and subsequent ops fail. We don't expect to close the devices we're using for tests/development. This probably points out a gap between OPTEE-OS/Client, where with emulation not checking if the device is closed should be fine? How should this scenario be handled/addressed?

**Comment by jforissier** [comment]
> Hello,
> 
> I am working with OP-TEE (3.19) on an i.MX8M Nano platform where we'd like to utilize RPMB as a secure store. I was able to develop the TA/CA combo as per needs following the amazing resources available in the docs and around the web. The issue I am dealing with at this point relates to manufacturing vs production builds (Yocto based). We're working on modifying our manufacturing process to account for what's needed by OP-TEE for RPMB key provisioning and we have a plan that would sort this out. However, I'd like some input on this
> 
> OPTEE-OS manufacturing image
> 
>     * CFG_RPMB_WRITE_KEY=y
> 
>     * CFG_RPMB_FS=y (and related ones)
> 
>     * CFG_REE_FS=n
> 
> 
> OPTEE-Client manufacturing image
> 
>     * RPMB_EMU=1

`RPMB_EMU=0`. With `=1` the tee-supplicant will emulate the RPMB so the key write etc. would not reach the actual device.

**Comment by awais11010** [comment]
> > Hello,
> > I am working with OP-TEE (3.19) on an i.MX8M Nano platform where we'd like to utilize RPMB as a secure store. I was able to develop the TA/CA combo as per needs following the amazing resources available in the docs and around the web. The issue I am dealing with at this point relates to manufacturing vs production builds (Yocto based). We're working on modifying our manufacturing process to account for what's needed by OP-TEE for RPMB key provisioning and we have a plan that would sort this out. However, I'd like some input on this
> > OPTEE-OS manufacturing image
> > ```
> > * CFG_RPMB_WRITE_KEY=y
> > 
> > * CFG_RPMB_FS=y (and related ones)
> > 
> > * CFG_REE_FS=n
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > OPTEE-Client manufacturing image
> > ```
> > * RPMB_EMU=1
> > ```
> 
> `RPMB_EMU=0`. With `=1` the tee-supplicant will emulate the RPMB so the key write etc. would not reach the actual device.

@jforissier many thanks for the reply but I guess I wasn't clear enough.

Our goal with OPTEE-Client manufacturing image (RPMB_EMU=1) is exactly as you described i.e. we do not want the key or other ops to reach the actual device however the second part of the original post explains that the i.MX platform implementation inisde OPTEE-OS isn't allowing us to work with an emulated RPMB because the platform is not closed at this point.

**Comment by jenswi-linaro** [comment]
I'd recommend to never use `CFG_RPMB_WRITE_KEY=y` on anything but test devices.
The script `scripts/derive_rpmb_key.py` can be used to help derive the RPMB key from the CID, provided that you know the HUK.

**Comment by jforissier** [comment]
> @jforissier many thanks for the reply but I guess I wasn't clear enough.

My bad. I did not read carefully enough :wink: Jens' recommendation is probably the best path, I just did not remember about it...

**Comment by awais11010** [comment]
> I'd recommend to never use `CFG_RPMB_WRITE_KEY=y` on anything but test devices. The script `scripts/derive_rpmb_key.py` can be used to help derive the RPMB key from the CID, provided that you know the HUK.

Knowing the CID is straight forward, however deriving the HUK with i.MX/CAAM isn't straight forward or even possible AFAICT and that's why we resorted to using `CFG_RPMB_WRITE_KEY=y` for the manufacturing.

Do we have any NXP/iMX experts here?

**Comment by ricardosalveti** [comment]
What we do is to fuse even on testing devices, after fusing the RoT and closing the device first, that way HUK is derived at runtime and stable. You can always reset the RPMB (CFG_RPMB_RESET_FAT) during your testing as well.

We basically have a set of public/test keys we use for development and suggest our customers to create their own set of keys when going to production, that way you can test the same code path during development (and skip RPMB emulation).

**Comment by awais11010** [comment]
> What we do is to fuse even on testing devices, after fusing the RoT and closing the device first, that way HUK is derived at runtime and stable. You can always reset the RPMB (CFG_RPMB_RESET_FAT) during your testing as well.
> 
> We basically have a set of public/test keys we use for development and suggest our customers to create their own set of keys when going to production, that way you can test the same code path during development (and skip RPMB emulation).

Thanks @ricardosalveti but that has a big down side of having to sign even the development images that we normally don't as our signing facility is secured. This also negates the awesome RPMB emulation feature which could be leveraged in such scenarios. Is this problem/shortcoming only tied to iMX platforms? Are other vendors handling this differently?

@clementfaure any thoughts?

**Comment by awais11010** [comment]
> > Thanks @ricardosalveti but that has a big down side of having to sign even the development images that we normally don't as our signing facility is secured.
> 
> All you need is access to the manufacturing tools from NXP, the key can be public to the team, as they are just test keys.
> 

That's understood as we already have secure boot however not for dev and we don't plan to follow this path hence looking for some suggestions here. A device that is not closed, shall ideally revert back with a test RPMB key and not say that the plat_rpmb_key_is_ready is false. It would then become a responsibility for the system maintainer to make sure when and when not the rpmb emulation is used. Thoughts?

> The problem is that you are setting write key when that is not really desired since you don't want to burn the RPMB key. You would probably need a custom config option to protect you from such action (and to skip rpmb key is ready). That would be the only way to protect you as you could have other supplicants (e.g. u-boot).

For u-boot it is already known that it does not provide RPMB emulation and hence care shall be taken with key writing enabled. Maybe I am missing something here.

**Comment by ricardosalveti** [comment]
> A device that is not closed, shall ideally revert back with a test RPMB key and not say that the plat_rpmb_key_is_ready is false. It would then become a responsibility for the system maintainer to make sure when and when not the rpmb emulation is used. Thoughts?

The problem is that plat_rpmb_key_is_ready is usually bound to having a valid HUK (otherwise you can easily end up burning the development key by mistake), which is why my suggestion for defining a new config or similar that can bypass the check (with a big warning or similar).

> Maybe I am missing something here.

Basically as you said, needs to be handled with care (and why I would probably look at an option in optee-os and not necessarily bound do optee-client).

**Comment by awais11010** [comment]
Thanks a lot @ricardosalveti. After a bit of more thought, a shared known test key between the os and the client should ideally be able to solve the gap. I'll see if I end up with something upstream acceptable :)

**Comment by awais11010** [comment]
Here's what I am going to go with for now. Use a test key between OPTEE-OS/Client when device is not closed (iMX specific). If client is built with RPMB emulation just write the key to emulated device. If client does not have RPMB emulation and it sees the test key, refuse to write unless forced with a new configuration.

Closing this for now. Will re-open if need be. Thanks a lot for all the suggestions/clarifications :)
