### ISSUE TITLE
Crash on ARMv9 platform when ASLR is enabled. 

### ISSUE THREAD

**Issue by sichunqin** [OP-TEE/optee_os#6675]
we encounter another crash when enable ASLR on ARMv9 platform (Cortex-A510). Since the platform has not debug capability, so we can't find more information which cause the crash.

Seems it crashes on enable_mmu function on entry_a64.S. I doubt that ARMv9 MMU can't support memory overlapping? Enable ASLR, two different VAs would map same PAs. I am afraid that it may be generic ARMv9 issue.

**Comment by odeprez** [comment]
Hi not sure this will really help or if this is any kind of related, but in my FVP setup I have ASLR enabled since some time, and doesn't seem to cause issues.
However either way when disabling it with CFG_CORE_ASLR=n it ends up in some page table exhaustion at boot time:

```E/TC:4 0 mobj_ffa_get_by_cookie:415 Populating mobj from rx buffer, cookie 0x1
E/TC:4 0 core_mmu_xlat_table_alloc:519 5 xlat tables exhausted
E/TC:4 0 Panic 'Failed to spread pgdir on small tables' at core/mm/core_mmu.c:1856 <core_mmu_map_pages>
E/TC:4 0 TEE load address @ 0xfd284000
E/TC:4 0 Call stack:
E/TC:4 0  0xfd28ca6c
E/TC:4 0  0xfd2984b0
E/TC:4 0  0xfd2a2cf4
E/TC:4 0  0xfd28e81c
E/TC:4 0  0xfd28a578
```

**Comment by sichunqin** [comment]
@odeprez Thanks! Seems this is different issue since we can run OPTEE with disabled ASLR.
