### ISSUE TITLE
Generating DH Key Pair

### ISSUE THREAD

**Issue by shirinebadi** [OP-TEE/optee_os#6676]
Hi. I'm trying to generate Difiie-Hellman Keypair using `TEE_GenerateKey`. Here is my code:

TA

```      TEE_ObjectHandle key;
        uint32_t key_size = 2048;
	const uint32_t key_type = TEE_TYPE_DH_KEYPAIR;
        size_t xbits = 1024;
	const uint8_t *p;
	size_t p_len = 2048;
	const uint8_t *g;
	size_t g_len = 256;


    // Create a key object
    res = TEE_AllocateTransientObject( key_type, key_size, &key);
    if (res) {
        return res;
    }

	TEE_Attribute attrs[2];
	TEE_InitRefAttribute(&attrs[0], TEE_ATTR_DH_PRIME, p, p_len);
	TEE_InitRefAttribute(&attrs[1], TEE_ATTR_DH_BASE,g, g_len);

    // Generate the key pair
    res = TEE_GenerateKey(key, key_size, attrs, sizeof(attrs)/sizeof(TEE_Attribute));
```

But, I get 0 TA panicked with code 0xffff0001 in TEE_InitRefAttribute.

Thank you in advance for your help.

**Comment by ivila** [comment]
@shirinebadi I think you must call TEE_RestrictObjectUsage1(with parameter TEE_USAGE_EXTRACTABLE) before TEE_InitRefAttribute.

**Comment by ivila** [comment]
@shirinebadi Maybe you forget to call TEE_RestrictObjectUsage1(with parameter TEE_USAGE_EXTRACTABLE) first.

**Comment by ivila** [comment]
@shirinebadi Maybe you forget to call TEE_RestrictObjectUsage1(with parameter TEE_USAGE_EXTRACTABLE) first.

**Comment by Kingxukai** [comment]
Hi there,in TEE_InitRefAttribute,your paramters of p and g is not only just a pointer,but an pointer which point a buffer with initialized data.
For example, the following code can be used to initialize a DH key generation:
TEE_Attribute attrs[3];
TEE_InitRefAttribute(&attrs[0], TEE_ATTR_DH_PRIME, &p, len);
TEE_InitRefAttribute(&attrs[1], TEE_ATTR_DH_BASE, &g, len);
TEE_InitValueAttribute(&attrs[2], TEE_ATTR_DH_X_BITS, xBits, 0);
TEE_GenerateKey(key, 1024, attrs, sizeof(attrs)/sizeof(TEE_Attribute));
Note that in the case of TEE_InitRefAttribute, only the buffer pointer is copied, not the content of the
buffer. This means that the attribute structure maintains a pointer back to the supplied buffer. It is the
responsibility of the TA author to ensure that the contents of the buffer maintain their value until the attributes
array is no longer in use.
