### ISSUE TITLE
TEE_PopulateTransientObject is failing for "TEE_ALG_ECDH_DERIVE_SHARED_SECRET" algortihm

### ISSUE THREAD

**Issue by dhruv77777** [OP-TEE/optee_os#6681]
Hey Team,

I am working on implementation of deriving the shared secret key using the algorithm "TEE_ALG_ECDH_DERIVE_SHARED_SECRET".
Case 1: I am generating the key in the TA and using the algorithm -> works fine. (No usage of "TEE_PopulateTransientObject" API)
Case 2: I am reading key from securestorage and populating a transient object for the further operations. -> Failing with Error Code 3024.

Can you help me this?

**Comment by jforissier** [comment]
Hi @dhruv77777, hard to give advice without seeing the code.
