### ISSUE TITLE
How to port OP-TEE on AMD-Xilinx Kira-KR260 (Cortex-A53)

### ISSUE THREAD

**Issue by kunisuzaki** [OP-TEE/optee_os#6682]
I would like to use OP-TEE on AMD-Xilinx Kira-KR260 (Cortex-A53), but the board (based on ZynqMP) is not listed on the supported platfrom. 
   General Support https://optee.readthedocs.io/en/latest/building/gits/build.html#platforms-supported-by-build-git
   ZynqMP support https://optee.readthedocs.io/en/latest/building/devices/zynqmp.html

Is thre a way to port on AMD-Xilinx Kira-KR260?
    KR260 https://www.xilinx.com/products/som/kria/kr260-robotics-starter-kit.html

**Comment by jenswi-linaro** [comment]
I'm afraid you may need to do most of the work yourself.

I'd start comparing the configuration done in `core/arch/arm/plat-zynqmp/platform_config.h` and `core/arch/arm/plat-zynqmp/conf.mk` with what's needed for your platform. So far it looks like the different ZynqMP variants use identical configurations so you may get lucky and not have to do more than add your platform to the list.

**Comment by kunisuzaki** [comment]
Dear jenswi-linaro,

Thank you for your reply.  I also compared `core/arch/arm/plat-zynqmp/platform_config.h` and `core/arch/arm/plat-zynqmp/conf.mk` .
I found the article 
[plat-zynqmp: add ZCU104 and ZCU106 flavour support](https://github.com/OP-TEE/optee_os/commit/c89e397c838f443db2b60ab20aac8565d21a8774)
and check the diifrences.

**Comment by ricardosalveti** [comment]
We use op-tee with kria kv260 and it works just fine, so you should be able to get it to work with kr260 based on the pure zynqmp support available in op-tee.

**Comment by kunisuzaki** [comment]
Dear ricardosalveti,

Good news. Thank you.
Anyway, which boad name did you use to build OP-TEE for kv260?
`PLATFORM=zynqmp-zcu102` or `PLATFORM=zynqmp-zcu104` or `PLATFORM=zynqmp-zcu106` ?
https://optee.readthedocs.io/en/latest/building/devices/zynqmp.html

**Comment by ricardosalveti** [comment]
I use `PLATFORM=zynqmp-zcu102`.

**Comment by kunisuzaki** [comment]
Dear ricardosalveti,

Thank you. We will try OP-TEE build with ` PLATFORM=zynqmp-zcu102`.

**Comment by NikoSalamini** [comment]
Hi @ricardosalveti, did you build the op-tee with the zcu102 option without modifying anything? I am trying to run op-tee on the KR260 too.
