### ISSUE TITLE
store a sample text in Trusty os in android google source code

### ISSUE THREAD

**Issue by srinivasbollaboyena** [OP-TEE/optee_os#6693]
I want to store a sample text in the trusty os  ,securely is it possible or not
hi @jforissier
 can u please explain is it possible and how

**Comment by jbech-linaro** [comment]
This is an OP-TEE git, not Trusty. I.e., we're talking about two different implementations of TEE/TrustZone. I'd advice to try to ask Trusty questions to Google who host and maintain Trusty.

**Comment by srinivasbollaboyena** [comment]
ok that your telling this tee and trusty os is different?

**Comment by srinivasbollaboyena** [comment]
Currently I am building an application to store data in trusty os ,@jbech-linaro ,@jforissier, is it there any code related to that in git

**Comment by jbech-linaro** [comment]
No, there isn't any code shared between OP-TEE and Trusty. Same goals more or less, but different implementations.

**Comment by srinivasbollaboyena** [comment]
do you know anything about trusty os ,in android source code
