### ISSUE TITLE
Question about declaring non-secure memory at runtime

### ISSUE THREAD

**Issue by jesse-sc** [OP-TEE/optee_os#6696]
Hi OPTEE experts,

I've know about `register_phy_mem()` can be declared at runtime using `core_mmu_add_mapping()`.

But currently we want to dynamically declare DRAM size, which is delcared by `register_ddr()`. Is there any function that can be called at runtime that works as `register_ddr()`? Thanks.

BRs,
Jesse

**Comment by etienne-lms** [comment]
There is currently no such function.
Memory registered with `register_ddr()` is memory OP-TEE core will consider as legitimate for being used as shared memory with non-secure world. If the non-secure world is to dynamically define such a memory area, can OP-TEE be sure it is not memory intended for some other purpose in the system? Maybe not a big issue as OP-TEE will access such a memory area with the same attributes as non-secure world would, but that OP-TEE may panic if accessing an area not authorized to non-secure world.

**Comment by jesse-sc** [comment]
Hi Etienne,

Thanks for your reply. Since there is currently no such function, we would like to try other way.
In fact, we just want to configure DRAM size at boot stage by registers in H/W instead of deciding DRAM size at compile time. We think this should not involve security consideration.

BRs,
Jesse

**Comment by etienne-lms** [comment]
Feel free to propose some dynamic registration. If using some internal RAM to pass the info from some boot stage to OP-TEE, maybe consider using firmware handoff transfer lists: https://github.com/FirmwareHandoff/firmware_handoff &  [_core/kernel/transfer_list.c_](https://github.com/OP-TEE/optee_os/blob/4.1.0/core/kernel/transfer_list.c).

**Comment by jesse-sc** [comment]
Hi Etienne,

Got it. Many thanks for your suggestion.

BRs,
Jesse
