### ISSUE TITLE
Way to import sys/fcntl.h

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/optee_os#6698]
Hello,

I have some code that uses general file flags, such as `O_RDONLY`, `O_APPEND`, `O_CREAT`, etc.
It seems current OP-TEE does not have `sys/fcntl.h`, which defines these flags.

May I know how to import such code or header file into OP-TEE source tree?
Can I just copy `sys/fcntl.h` from newlib project
(https://github.com/bminor/newlib/blob/master/newlib/libc/include/sys/fcntl.h)
 into `optee_os/lib/libutils/isoc/include/sys` ?

Thanks!

**Comment by jforissier** [comment]
Hello @gagachang,

Generally speaking, yes. But can you explain why you would need these defines? OP-TEE doesn't provide the `open()` function/syscall to TAs for example.

**Comment by gagachang** [comment]
> But can you explain why you would need these defines?

I want to play **semi-hosting** in OP-TEE kernel.
There are some operations related to file I/O.
Please refer to ARM's documentation:
https://developer.arm.com/documentation/dui0471/g/Semihosting/Semihosting-operations?lang=en

**Comment by jforissier** [comment]
OK, that's interesting.

**Comment by gagachang** [comment]
Thanks! I will try it.
