### ISSUE TITLE
Need a example of Trusted Applications

### ISSUE THREAD

**Issue by prz999** [OP-TEE/optee_os#67]
Hi all,
    I'm very interesting in your OP-TEE. I think it would be very useful in the future. And I has study it for a long time.But I can't find a example of the Trusted Application. Or I don't know how a Trusted Application should be defined and built. I want to know how I can create a simple Trusted Applications. Sending "Hello tee!" from Trusted Application to Client is enough. I will very appreciate for you do that.
Best Regards,
Ruizhi

**Comment by bngabonziza** [comment]
How do you debug a ta ?
