### ISSUE TITLE
Add other SOC in plat-mediatek

### ISSUE THREAD

**Issue by p870613** [OP-TEE/optee_os#6703]
Hi 

I want to add new SOC, mt7988, into `plat-mediatek`, but `plat-mediatek` has already existed.
Howerver, we are different product line.
Can I add new directory in `core/arch/arm/plat-mediatek-xxx` about our platform config ? 

Thanks !!

**Comment by jforissier** [comment]
Hi @p870613,

> Can I add new directory in `core/arch/arm/plat-mediatek-xxx` about our platform config ?

If you really need to, yes. But I would prefer if you could re-use `plat-mediatek`. It should not be difficult. You would use a new `PLATFORM_FLAVOR` like so:

In `.mk` files:
```make
ifeq ($(PLATFORM_FLAVOR),mt7988)
# ...
endif
```
In C files:
```C
#ifdef PLATFORM_FLAVOR_mt7988
/* ... */
#endif
```
```
And you would build with `make PLATFORM=mediatek-mt7988`.

**Comment by p870613** [comment]
Thanks for your reply.

There is different config in common config like below
```
#ifdef CFG_WITH_LPAE
#define MAX_XLAT_TABLES		5
#endif
```
In mt7988, `MAX_XLAT_TABLES` must set to 10.
I will discuss internal.

Thanks !!
