### ISSUE TITLE
Add RISC-V build to CI

### ISSUE THREAD

**Issue by gagachang** [OP-TEE/optee_os#6704]
Hello maintainers,

Previously we talked about adding RISC-V build to CI in https://github.com/OP-TEE/optee_os/pull/6576.
After https://github.com/OP-TEE/optee_os/pull/6617 was merged, now we can build upstream RISC-V optee_os without any local patches.
I think it is good time to start it.

We would like to add the build commands into existing `make (multi-platform)`, or adding new job for RISC-V platforms.

We've tried the following steps in Ubuntu 22.04 system:

```Shell
# System
{ROOT}/optee_os$ uname -a
Linux alvinga-VirtualBox 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

# Download and install RISC-V toolchain packages
{ROOT}/optee_os$ sudo apt-get install -y gcc-riscv64-linux-gnu

# Check toolchain
{ROOT}/optee_os$ which riscv64-linux-gnu-gcc
/usr/bin/riscv64-linux-gnu-gcc

# Build optee_os
{ROOT}/optee_os$ make ARCH=riscv PLATFORM=virt CFG_USER_TA_TARGETS=ta_rv64 CFG_RV64_core=y \
    CROSS_COMPILE="ccache riscv64-linux-gnu-" CROSS_COMPILE_core="ccache riscv64-linux-gnu-" \
    CROSS_COMPILE_ta_rv64="ccache riscv64-linux-gnu-"
```

Hope the information is enough.
If you need more information please let me know, thank you!!

**Comment by gagachang** [comment]
C.C. @maroueneboubakri  @lyctw

**Comment by maroueneboubakri** [comment]
Hello @gagachang,

Thank you, we can work on it, if you have something to submit, do we still need patches for Linux kernel to enable your conduit method ? 

Best
Maro

**Comment by jforissier** [comment]
Hi @gagachang,

Thanks for the information, I believe I have all I need to extend the `make (multi platform)` build. I will create a PR. I may have a few suggestions to simplify the build command line too (default values for `CROSS_COMPILE*` etc.).

As for runtime tests, that's clearly the next step, it should be a new job `make check (QEMU riscv64)` for example. I let you guys figure out what is needed in manifest.git and build.git etc.

**Comment by gagachang** [comment]
Hello @maroueneboubakri 

> Thank you, we can work on it, if you have something to submit, do we still need patches for Linux kernel to enable your conduit method ?

For now we can just add "build" CI.
The "runtime test" CI needs patches for linux and SM, as you mentioned.
It can be future work.

**Comment by maroueneboubakri** [comment]
> Hello @maroueneboubakri
> 
> > Thank you, we can work on it, if you have something to submit, do we still need patches for Linux kernel to enable your conduit method ?
> 
> For now we can just add "build" CI. The "runtime test" CI needs patches for linux and SM, as you mentioned. It can be future work.

Sure ! Just was curious to know.

**Comment by gagachang** [comment]
Since https://github.com/OP-TEE/optee_os/pull/6705 has been merged, I close this issue.
