### ISSUE TITLE
Can a TA request some service in the normal world?

### ISSUE THREAD

**Issue by targetnull** [OP-TEE/optee_os#671]
Hi,
I read the some code of the TA, and find that the TA is designed to *receive* the request from the normal world. That is to say, a TA seems not able to *'ask'* the normal world to do something, for instance, to send the content of a file to TA.

Is there anyway to do so? I don't find relevant code in the current examples.
Thanks a lot.
Tgn

**Comment by pascal-brand-st-dev** [comment]
OPTEE is a Global Platform compliant TEE. The internal API defines some specific cases where the TA 'asks' something to the non-secure world. For example, getting the [REE time](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/tee_time.c#L75). 

Sending the content of a file to the TA is not part of the API.

Please close this issue if this answers.

**Comment by targetnull** [comment]
I see, maybe i need to write my own TA and modifiy the driver to do my work.

I have a question about the time-relevant functions. I find that the implemention of [tee_time_wait](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/tee_time.c#L51) function uses RPC method. But in the `libtomcrypt` lib(for aarch64), it uses [rdtsc](https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/test/x86_prof.c#L67) function to directly get the timer register value.

Would it be more secure to use the TEE Timer to implement `tee_time_wait` since the REE timer is not protected. 
Thanks.

**Comment by pascal-brand-st-dev** [comment]
`rdtsc` is restricted to x86 architecture.
However, we may use the ARM Cycle Counter for this. We'll investigate this.

**Comment by targetnull** [comment]
Many thanks.
