### ISSUE TITLE
How could I change the setting for the binary not modified?

### ISSUE THREAD

**Issue by norainsX** [OP-TEE/optee_os#6711]
I have a question:
The TA souce code doen't change, but when I rebuild it everytime, the output binary would modified.
How could I do, when the source code doesn't change, and the binary file would not modified?
Thanks~!

The part of modified:
![image](https://github.com/OP-TEE/optee_os/assets/29322364/a9eb7751-4cd3-4524-b354-2e105030d4f6)

**Comment by jforissier** [comment]
Hi @norainsX,

The parts that change in the signed TA binary are the signature. The reason is because the signature algorithm (`TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256`) uses a random salt of length 32 (bytes) by default. You can get reproducible builds with the following change:

```diff
diff --git a/scripts/sign_encrypt.py b/scripts/sign_encrypt.py
index 435d63be7..da703d49b 100755
--- a/scripts/sign_encrypt.py
+++ b/scripts/sign_encrypt.py
@@ -735,6 +735,8 @@ class BinaryImage:
         return pad

     def sign(self):
+        from cryptography.hazmat.primitives import hashes
+        from cryptography.hazmat.primitives.asymmetric import padding
         from cryptography.hazmat.primitives.asymmetric import utils
         from cryptography.hazmat.primitives.asymmetric import rsa

@@ -743,7 +745,9 @@ class BinaryImage:
                          'please use offline-signing mode.')
             sys.exit(1)
         else:
-            self.sig = self.key.sign(self.img_digest, self.__get_padding(),
+            padding = padding.PSS(mgf=padding.MGF1(hashes.SHA256()),
+                                  salt_length=0)
+            self.sig = self.key.sign(self.img_digest, padding,
                                      utils.Prehashed(self.chosen_hash))

             if len(self.sig) != self.sig_size:
```

Be aware that doing so will weaken the algorithm's security. To which extent is hard to say, but see for instance https://crypto.stackexchange.com/questions/1217/rsa-pss-salt-size.

**Comment by norainsX** [comment]
> Hi @norainsX,
> 
> The parts that change in the signed TA binary are the signature. The reason is because the signature algorithm (`TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256`) uses a random salt of length 32 (bytes) by default. You can get reproducible builds with the following change:
> 
> ```diff
> diff --git a/scripts/sign_encrypt.py b/scripts/sign_encrypt.py
> index 435d63be7..da703d49b 100755
> --- a/scripts/sign_encrypt.py
> +++ b/scripts/sign_encrypt.py
> @@ -735,6 +735,8 @@ class BinaryImage:
>          return pad
> 
>      def sign(self):
> +        from cryptography.hazmat.primitives import hashes
> +        from cryptography.hazmat.primitives.asymmetric import padding
>          from cryptography.hazmat.primitives.asymmetric import utils
>          from cryptography.hazmat.primitives.asymmetric import rsa
> 
> @@ -743,7 +745,9 @@ class BinaryImage:
>                           'please use offline-signing mode.')
>              sys.exit(1)
>          else:
> -            self.sig = self.key.sign(self.img_digest, self.__get_padding(),
> +            padding = padding.PSS(mgf=padding.MGF1(hashes.SHA256()),
> +                                  salt_length=0)
> +            self.sig = self.key.sign(self.img_digest, padding,
>                                       utils.Prehashed(self.chosen_hash))
> 
>              if len(self.sig) != self.sig_size:
> ```
> 
> Be aware that doing so will weaken the algorithm's security. To which extent is hard to say, but see for instance https://crypto.stackexchange.com/questions/1217/rsa-pss-salt-size.

I'm sorry, but the reply is late because there is something wrong with the computer these days. I have tested it here, and your method is very effective. Thank you very much!
