### ISSUE TITLE
Problem with passing parameters : CA passes mbedtls_mpi type parameters to TA, but an error occurs!

### ISSUE THREAD

**Issue by oldoldcoder** [OP-TEE/optee_os#6716]
### Hello experts, my question is as follows：

I am trying to pass mbedtls_mpi type parameters to TA through CA. The approximate content is as follows：

>The declared parameters are as follows, and the initialization is completed similar to `mbedtls_mpi_init` ：

<img width="187" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/c6cf4174-49b5-4230-845a-2fa6cb760be3">

> After completing the calculation later, I tried passing the parameters through：

<img width="728" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/497ed8b6-93b1-43c1-b50d-15a78b4c18ab">

> On the TA side I try to receive and use

<img width="501" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/feaaf613-8a23-4d20-9740-ccc876d5e873">

But an error occurred when running, probably similar to the following：

<img width="496" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/af422ce7-ec57-437f-9879-4f0106f80e44">

### Hope to get help：
1.How to pass parameters correctly
2.TA’s access mechanism to CA’s data or memory

### note：
TA UUID is deadbeef-2450-11e4-abe2-0002a5d5c51b

**Comment by jforissier** [comment]
The `mbedtls_mpi` structure contains a pointer, it is not self-contained. Therefore you cannot pass it from CA to TA. You need to use `mbedtls_write_binary()` and `mbedtls_read_binary()`.

**Comment by oldoldcoder** [comment]
@jforissier Does this mean that all structure pointers are not passable in this process, so for some custom structures I should implement the serialization and deserialization operations myself?

**Comment by jforissier** [comment]
@oldoldcoder yes.

**Comment by oldoldcoder** [comment]
@jforissier Thank you very much for your answer, I will close this question
