### ISSUE TITLE
Error with QEMU build

### ISSUE THREAD

**Issue by zero-clouds-** [OP-TEE/optee_os#672]
Hi,

I'm having an error building OP-TEE for QEMU. I'm on Ubuntu 14.04. I had to build the toolchains by hand because tar didn't know how to deal with .xz extensions. Attached is the output of 'make all run'. There were no errors or warnings otherwise until this point.

  Building modules, stage 2.
  MODPOST 0 modules
make[1]: Leaving directory `/home/ben/devel/optee/linux'
cd /home/ben/devel/optee/build/../gen_rootfs &&  \
		CC_DIR=/home/ben/devel/optee/build/../toolchains/aarch32 \
		PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ben/devel/optee/build/../linux/usr \
		/home/ben/devel/optee/build/../gen_rootfs/generate-cpio-rootfs.sh \
			vexpress
Generator for a simple initramfs root filesystem for some ARM targets
Building Versatile Express root filesystem
Set up cross compiler at: /home/ben/devel/optee/build/../toolchains/aarch32
Check ccache ...make: *** [busybox-common] Error 1

**Comment by vchong** [comment]
Try `sudo apt-get install xz-utils` for the tar file?
For the build, not getting a problem here, even without ccache. Did you change anything?

**Comment by zero-clouds-** [comment]
xz-utils is already installed. Actually, I don't think curl is getting anything. I will redo that with wget and see if that helps.

The only thing I did differently than the instructions was unpacking the toolchains by hand.

**Comment by zero-clouds-** [comment]
Changed curl to wget in toolchains.mk, that works now, but xz-utils is installed and tar still doesn't know how to deal with the xz extension. I've also tried the -J flag, same result.

**Comment by zero-clouds-** [comment]
Same error.

**Comment by zero-clouds-** [comment]
I just tried on Fedora, curl resulted in files that tar would not recognize. Changed to wget and ran `make all run` and it failed, but with a different error:

`Building Versatile Express root filesystem
Set up cross compiler at: /home/bgreen/devel/optee/build/../toolchains/aarch32
Check ccache ...which: no ccache in (/home/bgreen/devel/optee/build/../toolchains/aarch32/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/bgreen/.local/bin:/home/bgreen/bin:/home/bgreen/devel/optee/build/../linux/usr)
common.mk:50: recipe for target 'busybox-common' failed
make: *** [busybox-common] Error 1`

**Comment by vchong** [comment]
It should work without it anyway, but just for kicks, have you tried installing ccache?

**Comment by zero-clouds-** [comment]
That worked. That fixed the issues I was having on both Fedora and Ubuntu. Thanks.

**Comment by vchong** [comment]
For the OP-TEE developers, this is a bug! Build fails if ccache is not installed. Verified on both hikey and qemu build.

**Comment by pascal-brand-st-dev** [comment]
@vchong  I'll work on the ccache issue

**Comment by ryankumar** [comment]
i want to repeat the previous question again. 1st i got error in "make toolchains" but manually i copied toolchains from another optee . but i m getting error in "make all run" . The error is as follows

  CHK     out/arm/include/generated/conf.h
ccache: error: execv of /home/mahannee/qemu_stable/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-gcc failed: No such file or directory
mk/compile.mk:232: recipe for target 'out/arm/core/include/generated/.asm-defines.s' failed
make[1]: *** [out/arm/core/include/generated/.asm-defines.s] Error 1
make[1]: Leaving directory '/home/mahannee/qemu_stable/optee_os'
common.mk:380: recipe for target 'optee-os-common' failed
make: *** [optee-os-common] Error 2

please help me to solve this one.

**Comment by jforissier** [comment]
@ryankumar you have been told a [few](https://github.com/OP-TEE/optee_os/issues/1724#issuecomment-409666980) [times](https://github.com/OP-TEE/optee_os/issues/601#issuecomment-414286937) [already](https://github.com/OP-TEE/build/pull/83#issuecomment-417568559) not to append new questions to old issues or PRs unless your question is related. You won't get any help until you do.

To open a new issue, go to https://github.com/OP-TEE/optee_os/issues and click the "New issue" button on the top right of the page. Is there something that doesn't work for you? If it is the case, please let me know and I will create the issue for you, then you can add comments.

**Comment by Varsha-a** [comment]
Hi,
I am trying to setup optee on my 64-bit linux machine ,I am having an issue when I try to do make ,Below is the error I am getting.

make -C /home/varsha/optee/build/../optee_os O=out/arm CFG_ARM64_core=y CROSS_COMPILE="/usr/bin/ccache /home/varsha/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_core="/usr/bin/ccache /home/varsha/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" CROSS_COMPILE_ta_arm64=/home/varsha/optee/build/../toolchains/aarch64/bin/aarch64-linux-gnu- CROSS_COMPILE_ta_arm32=/home/varsha/optee/build/../toolchains/aarch32/bin/arm-linux-gnueabihf- CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=0 CFG_TEE_BENCHMARK=n PLATFORM=rpi3
make[1]: Entering directory '/home/varsha/optee/optee_os'
  CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
make[1]: *** No rule to make target '/home/user/optee/toolchains/aarch64/lib/gcc/aarch64-linux-gnu/8.2.1/include/stddef.h', needed by 'out/arm/core/include/generated/.asm-defines.s'.  Stop.
make[1]: Leaving directory '/home/varsha/optee/optee_os'
common.mk:394: recipe for target 'optee-os-common' failed
make: *** [optee-os-common] Error 2

I will be really great if some one could help.
