### ISSUE TITLE
 Why recommend gcc-arm-aarch64-none-linux-gnu instead of gcc-arm-aarch64-none-elf 

### ISSUE THREAD

**Issue by huzai9527** [OP-TEE/optee_os#6723]
1. The arm community gives differences: The 'elf' version is for bare metal targets, the 'linux' version is for building Linux applications.
2. Is optee a Linux application?

**Comment by jforissier** [comment]
> 1. The arm community gives differences: The 'elf' version is for bare metal targets, the 'linux' version is for building Linux applications.

OK
>     2. Is optee a Linux application?

No.

The reason is convenience. We can use the same compiler to build the whole stack, including the Linux client applications and libraries.

**Comment by huzai9527** [comment]
Thank you, will there be any problems if I use elf to compile tos?

**Comment by jforissier** [comment]
> Thank you, will there be any problems if I use `elf` to compile tos?

No, it should work fine.

**Comment by huzai9527** [comment]
> > Thank you, will there be any problems if I use `elf` to compile tos?
> 
> No, it should work fine.

thanks for your answer
