### ISSUE TITLE
about OP-TEE impact on nsec interrupts and scheduling latency

### ISSUE THREAD

**Issue by etienne-lms** [OP-TEE/optee_os#6731]
Dear all,

As I said during the last OP-TEE public meeting, I've looked at the impacts of OP-TEE on the latency of non-secure world interrupts and scheduler responsiveness. Instrumenting a bit some OP-TEE functions I found some pretty big issues preventing OP-TEE from being used together with a real-time Linux kernel, even with not very strong real-time constraints.

I instrumented the OP-TEE functions that mask/unmask interrupts to find how long these were masked and from where. These functions are mainly `thread_mask_exceptions()` and `thread_unmask_exception()`, more commonly used through `cpu_spin_lock_xsave()`/`cpu_spin_unlock_xrestore()`. Doing so, I found some pieces of code that were a bit old and could be upgrade to more recent helper functions, hence I created P-R https://github.com/OP-TEE/optee_os/pull/6729. P-R https://github.com/OP-TEE/optee_os/pull/6725 is related to a helper function I used to ease measuring time spent between 
 `thread_mask_exceptions()` and `thread_unmask_exceptions()`.

I saw that there are few places where current OP-TEE (latest tag at time of writing is 4.1.0) masks interrupts for quite a long time: from several dozen to several hundreds of microseconds on my Cortex-A7 platform.
* mapping/unmapping dynamic shared memory can take a while. Up to 800µs for example when the shared buffer is several MByte large. I've created P-R [#6728](https://github.com/OP-TEE/optee_os/pull/6728) to try to address that but I feel I've miss something.
* The wipe-on-free feature of bget/malloc can hold its interrupt masked lock for more than 100µs for a buffer of few kBytes. I propose P-R [#6726](https://github.com/OP-TEE/optee_os/pull/6726) to address that.
* Switching between secure and non-secure world seems to take up to 35µs on my platform. This number is to be consolidated. @igoropaniuk OP-TEE benchmark setup would have helped here but it's no more supported. I did not focus on that and will need to kdo some more precise measurments, considering Armv7-A 32bit Secure motinor, and TF-A 64bit Secure monitor.
* On Arm platforms, using VFP registers also impact interrupt latency in 2 ways:
  * Using VFP registers in OP-TEE means they are part of the context to save/restore hence increasing the time to switch between worlds (which is obviously done with interrupts masked). 
  * When core uses VFP, it shall use thread_kernel_enable_vfp() and thread_kernel_disable_vfp() between which foreign interrupts are masked. Core uses VFP for few crypto operations (tomcrypt AES GCM, Armv8 CE for AES, hashes, SM3, SM4).
* Drivers should be implemented to not mask interrupts for too long also. There fore I created PR [#6724](https://github.com/OP-TEE/optee_os/pull/6724) to make sure clocks are used in thread context. Using reset controllers with timeout support (API functions `rstctrl_assert_to()`/`rstctrl_deassert_to()` should be done with care from non-thread context)

Addressing the above mentioned issues does not guarantee OP-TEE complies with a real-time Linux kernel configuration, but they are preliminaries to.

In the hope this description can help someone and can clarify the purpose of the few P-Rs I created recently.
Regards

**Comment by b49020** [comment]
Thanks @etienne-lms for working on making OP-TEE more responsive to Linux (non-secure world) interrupts (eg. scheduler events etc.). But still I think context switching (I suppose it will be comparatively larger than 35 us on an Armv8-A platform with TF-A) can be a real issue for some RT workloads. BTW, you can try to check min/max latencies while running OP-TEE xtest.

IMO, above should be coupled with system tuning applied to isolate (CPU pinning) OP-TEE workloads from RT workloads. This session [1] [2] can be a good reference to achieve that.

[1] https://youtu.be/UMWGNjgZS6A?si=ZbmZ1m-1NMErdHtm
[2] https://elinux.org/images/c/c0/Linux_Real-Time_kernel_and_tuning_robotics_platform_-_Krzysztof_Kozlowski%2C_Linaro_-_ELCE_2023.pdf
