### ISSUE TITLE
The results of the two executions are inconsistent : about 'Failed to get monotonic counter for REE FS'

### ISSUE THREAD

**Issue by oldoldcoder** [OP-TEE/optee_os#6733]
hello expert

### 1.Problem Description：

I passed two very long encrypted strings and the serialized public and private keys from ca to ta, and tried to complete the decryption calculation in ta, but I encountered some problems. I suspect it may be the parameters passed. Too long and an error will occur:

### 2..Key Information

> Executing CA for the first time displays

<img width="329" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/33ee7943-2ce2-4f3b-adb3-87466212bc9f">

> TA display

<img width="280" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/117d137e-20df-465f-b268-a7e4d157c883">

You can see that there is an obvious warning, but I don't know what it means.：
` I/TC: WARNING (insecure configuration): Failed to get monotonic counter for REE FS, using 0
I/TC: WARNING (insecure configuration): Failed to commit dirh counter 2 `

The next time I execute the code, I can execute it normally without modifying anything. Why is this? I can not understand

This is my configuration：

<img width="540" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/33de48d6-3e0b-4ce9-a655-b134456d3621">

### 3.doubt

1) Is this because his memory is too small, or what is the reason?
2) Is there any good way for me to restore it to normal?

**Comment by oldoldcoder** [comment]
<img width="792" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/5dfe2f19-e5e2-4e5e-865a-2c4e2bd0ba77">

At the same time, this problem often occurs, User mode data-abort at address 0x80303000 (translation fault), When I'm halfway through deserializing

**Comment by oldoldcoder** [comment]
@jenswi-linaro Hello experts, are you free to help me with this problem?

**Comment by jenswi-linaro** [comment]
The monotonic counter warning was introduced with commit 623b9bd4ec21 ("core: use monotonic counter for secure storage without RPMB"). It is just a warning that you don't have a working implementation of monotonic counters on your platform and that you don't use RPMB either. We utilize warnings like this to warn about potentially insecure configurations so they are easier to catch before releasing a product.

For the other error, I can't help you with debugging you're own code.

**Comment by oldoldcoder** [comment]
@jenswi-linaro Is it because when I pass parameters, the content passed is too large, but I use pointers to pass past parameters, similar to this, the pointers here all point to strings (the result of serializing the data), because before This has never happened when I passed relatively small data. My program often crashes by itself.

```
memset(&op, 0, sizeof(op));
    op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INOUT, TEEC_MEMREF_TEMP_INPUT, TEEC_MEMREF_TEMP_INPUT, TEEC_NONE);
    op.params[0]
        .tmpref.buffer = bufA;
    op.params[1]
        .tmpref.buffer = bufB;
    op.params[2]
        .tmpref.buffer = bufPkeys;

    printf("-----in TEE-----\n");
    res = TEEC_InvokeCommand(&ctxx.sess, 0, &op, &err_origin);
    if (res != TEEC_SUCCESS){
         errx(1, "TEEC_InvokeCommand failed with code 0x%x origin 0x%x", res, err_origin);
    }
    printf("-----out TEE-----\n");
    mbedtls_mpi_read_string(&e_m1r1_mul_m2r2, SERIALIZE_RADIX, op.params[0].tmpref.buffer);
```

I always accept it this way

```
IMSG("-------------------------------compute_multi-----------------------------------------------");
//  Assume that all pointer parameters passed are available  
    char *bufA = params[0].memref.buffer;
    char *bufB = params[1].memref.buffer;
    char * pkeys = params[2].memref.buffer;

    if(mbedtls_mpi_read_string(&a,SERIALIZE_RADIX,bufA) != 0){
        IMSG("bufA string -> mbedtls_mpi has error");
        return TEE_ERROR_BAD_PARAMETERS;
    }
    if (mbedtls_mpi_read_string(&b,SERIALIZE_RADIX, bufB) != 0)
    {
        IMSG("bufB string -> mbedtls_mpi has error");
        return TEE_ERROR_BAD_PARAMETERS;
    }
    IMSG("Serialize the pkeys....");
    // 反序列化转换
    deserializing_pkeys(&keys, pkeys, sizeof(pkeys));
    IMSG("Received the parameters passed over \n");
```

**Comment by jenswi-linaro** [comment]
As I said, that's something for you to debug. I will not do it.
