### ISSUE TITLE
tee_otp_get_hw_unique_key

### ISSUE THREAD

**Issue by YaelAv** [OP-TEE/optee_os#6737]
I'm curious about the security rationale behind limiting access to tee_otp_get_hw_unique_key solely to the OPTEE OS. Would it be feasible from security aspects to extend this access to my User Mode TA, either directly or via an API call to a new PTA?

**Comment by YaelAv** [comment]
I am aware to PTA_SYSTEM_DERIVE_TA_UNIQUE_KEY. Is it reasonable, from security aspects, that I create a new PTA that just return the HUK without deriving a key from it?

**Comment by jenswi-linaro** [comment]
No, I think it would be quite bad. The HUK is normally never used directly instead we derive a separate key for each case. Exposing one derived key doesn't expose the HUK or the other derived keys.
