### ISSUE TITLE
Getting value of stack pointer from PTA

### ISSUE THREAD

**Issue by mikolaj33300** [OP-TEE/optee_os#6739]
Hi, I had a question about whether it was possible for a PTA to not only directly inspect the memory contents of the calling TA, but also find the stack pointer/value of the sp/fp register at the time of calling. 

I've seen attestation.c uses session user context to get information about allocation of a TA. However, uctx->stack_ptr points to the bottom of the stack. I tried different things: the functions I tried calling from the PTA all involve accessing registers in case of a fault, or require being called by something else. The information that I found that is available about stacks, concerns outer limits, not the actual active pointer. 

Could anyone give me an idea on how to go about this?

**Comment by jenswi-linaro** [comment]
I assume this is for AArch64 (Arm-v7 has the SP in usr_sp). You can see how the registers are saved in `el0_svc()` in `core/arch/arm/kernel/thread_a64.S`. A pointer to this `struct thread_scall_regs` is passed on to `scall_handle_user_ta()`. `scall_do_call()` extracts the argument registers `x0..x7` and calls the syscall function, for instance, `syscall_invoke_ta_command()`. However, now we don't have the pointer to the `struct thread_scall_regs` any longer.

`struct thread_scall_regs` is always saved at the same location relative to `kern_sp` in `struct thread_ctx` of the current thread. This is one way to find the saved `sp_el0` of the TA. FP registers are stored in the `vfp_state` in `struct thread_ctx` of the current thread, depending on the current state of the lazy saving.

**Comment by mikolaj33300** [comment]
Thanks for the in depth explanation, it all works now!
