### ISSUE TITLE
How to find the NSEC_DDR_0_BASE and NSEC_DDR_0_SIZE needed by dynamic memory sharing for a given platform?

### ISSUE THREAD

**Issue by ZhanYF** [OP-TEE/optee_os#6742]
Hi,

To enable dynamic memory sharing for optee os, I believe that NSEC_DDR_0_BASE and NSEC_DDR_0_SIZE need to be declared, but I don't know how to find the address base and have doubts on which format should the size be declared in.

For my rk3399 system with 4GB of memory I'm using `register_ddr(0x00000000, 0xF6000000);` now, it appears to work, but I doubt this is the correct values. Unfortunately rk3399's device tree source does not contain the base address, nor can I find this information from SoC's datasheet.

Any ideas on how can I find and validate the memory base and size? is this totally board-dependent?

**Comment by jenswi-linaro** [comment]
I have a Rock4A+ that I've started to play with for testing purposes.
I can't find the memory node in the DTB supposedly used by the kernel.
I'll let you know if I find out anything more.
