### ISSUE TITLE
failed to find an OP-TEE supplicant device

### ISSUE THREAD

**Issue by Xxxgrey** [OP-TEE/optee_os#6745]
Hello,  I use `ps aux | grep tee-supplicant` , it shows
```
  ps aux | grep tee-supplicant
 1579 tee      /usr/sbin/tee-supplicant -d /dev/teepriv0
 7548 root     grep tee-supplicant

```
but when I use `tee-supplicant -d`
it shows
```
tee-supplicant -d
ERR [7549] TSUP:main:694: failed to find an OP-TEE supplicant device

```

all the `xtest` works and 0 failed. I don't know where went wrong.
Please help me.Thank you
![Snipaste_2024-03-11_20-13-32](https://github.com/OP-TEE/optee_os/assets/121740214/729b30b0-5db1-4a75-b00d-2760bc6f851a)

**Comment by Xxxgrey** [comment]
The system I use is VMware, Ubuntu20.04

**Comment by Xxxgrey** [comment]
@jenswi-linaro , @jforissier Please  please help me out.

**Comment by jforissier** [comment]
You can't start a new `tee-suplicant` if it is already running.

**Comment by jforissier** [comment]
> > You can't start a new `tee-suplicant` if it is already running.
> 
> So it is running? Thanks a lot

What do you think `ps aux | grep tee-supplicant` does?

**Comment by Xxxgrey** [comment]
> > > You can't start a new `tee-suplicant` if it is already running.
> > 
> > 
> > So it is running? Thanks a lot
> 
> What do you think `ps aux | grep tee-supplicant` does?

OK thanks
