### ISSUE TITLE
secure python code by optee

### ISSUE THREAD

**Issue by misagham** [OP-TEE/optee_os#6746]
hi  i1m very new on optee please help me about my question 
as i understand there is no way to run python code from secure world of optee 
is there any way to only store python code in trusted Env to normal world users don`t be able to do any modification or copy the code and just be able to run it from normal word with something like TA execution command (eg. sudo my_code_run )???
if it`s possible tell me how i gonna do it???

**Comment by jenswi-linaro** [comment]
It's possible to store any data in the secure world to retrieve it later from the normal world if that's how the involved TA is designed. However, it seems pointless. What kind of added security are you looking for?

**Comment by misagham** [comment]
thanks for your response 
i have a python code on my nvidia jetson that have many library dependencies and i want to protect this code from getting copies or any modification by the device users or anybody else 
as i understand there is no way to implement the python code as a trusted application in OPTEE
the only way that came to my mind was that to store python code in trusted Env and secure storage and make a trusted application that when user wanna run my python code , run the TA in normal world and  that application bring that stored code to normal word and run it there, somehow nobody be able to see the code and after the code execution done nothing be remain of the python code in normal world
is it possible at all ???

**Comment by ivila** [comment]
@misagham Have you try cython? Usually we protect our python codes by compile it to C module.

**Comment by misagham** [comment]
> @misagham Have you try cython? Usually we protect our python codes by compile it to C module.
hi @ivila thanks for your response 
it`s not possible to use cython for this python code to convert C in the code i used multiple AI framework like pytorch and tensorflow and its not possible to convert all of the code to C with cython becuase of library dependencies
