### ISSUE TITLE
Enabling PSS and DH Algorithms in mbedtls_config_uta.h by Default in Future OP-TEE Versions

### ISSUE THREAD

**Issue by Hanlin928** [OP-TEE/optee_os#6750]
Hello,

During the certification process of our Trusted Application (TA), we require the use of mbedtls's PSS and DH algorithms. I noticed that these algorithms are not enabled by default in `optee_os/lib/libmbedtls/include/mbedtls_config_uta.h`, whereas they are enabled by default in the native mbedtls `mbedtls_config.h`.

To avoid the need to manually enable these algorithms with each new release of OP-TEE, would it be possible to have the following macros enabled by default in `mbedtls_config_uta.h` in future versions of OP-TEE?

- `MBEDTLS_PKCS1_V21`
- `MBEDTLS_DHM_C`
- `MBEDTLS_ERROR_C`
- `MBEDTLS_X509_RSASSA_PSS_SUPPORT`

This would greatly facilitate the development process for TAs that rely on these cryptographic algorithms.

Thank you for considering this request and for any guidance you can provide.

Best regards,
Hanlin.Wang

**Comment by jenswi-linaro** [comment]
Feel free to propose a pull request where this is enabled.

**Comment by Hanlin928** [comment]
Thanks for your quick response.
Let me close this issue.
