### ISSUE TITLE
Question about Linux/optee compatibility

### ISSUE THREAD

**Issue by RNNord2** [OP-TEE/optee_os#6751]
Hi. Back in 2020, I worked in a i.MX6 based project using optee 3.7.0 and Linux 4.14.149. To make everything work, we ended up with optee-os patches to a) read the HUK at startup (we used an adaption of PR3608) and b) read the CAAM HW RNG at startup to seed the Fortuna PRNG. As I remember, the reason these patches were required was that Linux turned off the CAAM clock, prohibiting HUK reading and HW RNG usage after Linux startup.

Now we are about to upgrade to Linux 5.10, and at the same time we want to upgrade to a new optee version. We're thinking about using optee 3.13.0 since it was released in about the same time as Linux 5.10. Is that a correct choice, or would you say that we could or should go for a newer optee version? If possible, we would prefer not having to make the above mentioned patches at all to optee-os. As far as I can see, at least the read and store of HUK was included natively in optee 3.13.0. Do you know if the Linux 5.10 also turns the CAAM clocks off so that we still need the same approach to HUK reading and RNG usage?

**Comment by jenswi-linaro** [comment]
Generally, I recommend starting from the latest version of OP-TEE.
If you start from an older version, you risk missing security fixes since we currently don't maintain stable versions.

**Comment by RNNord2** [comment]
Thank you for your help. I will make a try to use OP-TEE 4.1.0 in our project. It looks like many (or possibly all) of the issues we had to address by making patches to 3.7.0 are taken care of in 4.1.0.
