### ISSUE TITLE
Ping Watchdog from TA?

### ISSUE THREAD

**Issue by jackgladowsky-emp** [OP-TEE/optee_os#6753]
Hello. 

I am an intern currently working on implementing our Trusted Application (TA) for our project. We want to be able to start a watchdog from the TA, and then every set duration, we want to ping the watchdog so the processor does not reset. 

**Is it possible to start and ping a watchdog from the TA?**

I have found optee_os/core/drivers/imx_wdog.c in the repo, but I am not sure if that is even usable from the TA.

If someone could please help point me in the right direction, I would really appreciate it!

Thanks!

**Comment by jenswi-linaro** [comment]
For this, you would need a pseudo-TA, see `core/pta` for examples.
There's test WD example in `core/tests/notif_test_wd.c` that uses a different approach based on notifications

**Comment by jackgladowsky-emp** [comment]
Thank you for the help!
