### ISSUE TITLE
"expected readable system register" error in vfp when compiling with Clang 18 

### ISSUE THREAD

**Issue by jonmason** [OP-TEE/optee_os#6754]
When compiling OP-TEE OS 4.1.0 with Clang 18, I'm seeing the following error:
[https://gitlab.com/jonmason00/meta-arm/-/jobs/6391567517#L291](url)

... snipped to save from clicking the link ...

| core/arch/arm/include/arm64.h:436:1: error: expected readable system register
| core/arch/arm/include/arm64.h:437:1: error: expected readable system register
| core/arch/arm/include/arm64.h:436:1: error: expected writable system register or pstate
| core/arch/arm/include/arm64.h:437:1: error: expected writable system register or pstate

Same code was compiling without issue with Clang 17

**Comment by jenswi-linaro** [comment]
It's complaining over "FPCR, Floating-point Control Register" and "FPSR, Floating-point Status Register".
``` C
DEFINE_U32_REG_READWRITE_FUNCS(fpcr)
DEFINE_U32_REG_READWRITE_FUNCS(fpsr)
```

Perhaps there's a new compiler flag that controls which registers are visible.

**Comment by jforissier** [comment]
Fixed by https://github.com/OP-TEE/optee_os/pull/6892.
