### ISSUE TITLE
How to adjust TA's MMU L1 table?

### ISSUE THREAD

**Issue by Minesweper** [OP-TEE/optee_os#6755]
I use ```qemu_v8``` ```OP-TEE 3.10.0``` try to get more memory.
I change ```CFG_TZDRAM_SIZE``` in ```optee_os/core/arch/arm/plat-vexpress/conf.mk```
```
ifeq ($(PLATFORM_FLAVOR),qemu_armv8a)
CFG_TZDRAM_START ?= 0x0e100000
CFG_TZDRAM_SIZE  ?= 0x04000000
```
and increase ```TA_DATA_SIZE``` from **10MB** to **32MB** in ```ta/include/user_ta_header_defines.h```.
I face the problem like [this](https://github.com/mofanv/darknetz/issues/29#issue-1009364238).
According to [adjust TA’s MMU L1 table](https://optee.readthedocs.io/en/latest/faq/faq.html#q-whats-the-maximum-size-for-heap-and-stack-can-it-be-changed), I need to change some configurations. But I don't know what to do.
Thanks to everyone's help!

**Comment by jenswi-linaro** [comment]
QEMU has a fixed amount of secure memory as you can see at https://github.com/qemu/qemu/blob/ba49d760eb04630e7b15f423ebecf6c871b8f77b/hw/arm/virt.c#L182

Setting `CFG_TZDRAM_SIZE` to something beyond that will not help.

**Comment by Minesweper** [comment]
Thanks a lot!
I can work on it.
