### ISSUE TITLE
How to debug OPTEE (Secure World) via JTAG

### ISSUE THREAD

**Issue by sakjain92** [OP-TEE/optee_os#676]
I am not able to connect JTAG to debug secure World. As soon as I try to connect via JTAG when I am in secure world (EL1 secure OPTEE), I get an exception  in EL3(ESR_EL3 shows it is an unknown class exception).

The ARM register dbgauthstatus_el1 is 0xFF (So I think this means SPIDEN is enabled). I am also enabling Debug exceptions (DAIF) in OPTEE before attaching JTAG.

Kindly let me know if there are any settings I am missing

**Comment by sakjain92** [comment]
I am able to debug EL3 with JTAG though

**Comment by jbech-linaro** [comment]
Hi @sakjain92 ,

I have files, scripts etc for running JTAG on HiKey using OpenOCD (works on secure side also), but that hasn't been created by me myself and I haven't been able to look into it yet and try it out fully. I could zip everything and send it to you and then you'd have to investigate on your own. Let me know if you want it and to who I should send it to (email) in case you are interested.

// Joakim

**Comment by jbech-linaro** [comment]
I've tar'ed my files and those could be found here:
https://transfer.sh/NbvTf/jtag.hikey.tar.gz

$ sha1sum jtag.hikey.tar.gz 
c52ae0dbfa476cd14129cfb44c8b5e2bcb670c4f  jtag.hikey.tar.gz

The URL is valid 14 days from today.

I still have issues with getting breakpoints to work in GDB, but besides that things seems to be working. I can attach, do stuff with the telnet -> OpenOCD console etc.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been partly answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by victormon** [comment]
Hi @jbech-linaro,
Can you upload the file again? I am having exactly the same problem that has @sakjain92 and I am trying to solve it.

Thanks in advance!

**Comment by jbech-linaro** [comment]
File uploaded again, here's the new URL
https://transfer.sh/8vcXF/jtag.hikey.tar.gz

Again, valid two weeks from today.

**Comment by victormon** [comment]
Thanks!
