### ISSUE TITLE
[RFC] i2c transactions within OP-TEE

### ISSUE THREAD

**Issue by massonju** [OP-TEE/optee_os#6763]
We integrated OP-TEE in our Android solution for TI boards, we are using OP-TEE since several years now, it works great.
We have been tasked to work on the following request: (short summary)
> We want to have an i2c driver in OP-TEE and it must be upstreamed in OP-TEE.
> This driver must support basics i2c features and should be able to switch between slave and master mode.

We don't know what device is connected through i2c but everything must be handle within OP-TEE either in slave or master mode.

I have created this ticket because I'm not convinced that this i2c driver can be upstreamed since it might be too specific and I would like your opinion on that before working/sending something.

From what I see in the project, there is several paths where we can find i2c code:
- core/drivers/*_i2c.c
- core/drivers/i2c/*
- core/drivers/crypto/se050/glue/i2c*
- core/arch/arm/kernel/rpc_io_i2c.c

My first suggestion was to use `rpc_io_i2c` and let the "caller" (kernel, U-Boot ...) do the 12c transactions as we do with mmc transactions for example (eg. RPMB).
But all i2c operations must be handle within OP-TEE so we can't use that.

Another suggestion was to write i2c driver: `core/drivers/ti_i2c.c` or `core/drivers/i2c/ti_i2c.c`
And create PTA to expose i2c functionnalities for a TA: read/write, set speed, switch master/slave mode ...

It's not completely clear to me where the code should be placed and how it will be accepted by the reviewers.

Can you please give me your opinion on that ?

Thanks

**Comment by etienne-lms** [comment]
Hello @massonju,
Implementing an I2C service in OP-TEE exposed to Linux kernel makes sense to me and using a PTA as interface for this is the preferred way I think. Linux should indeed provide the requested I2C bus configuration and handle multi-frame I2C transactions. The OP-TEE service should be able to filter the I2C device address that Linux side is allowed to access or not. To get some feedback, the best is to create a pull request. The PTA interface should be implemented in _core/pta/_ and preferably rely on I2C API functions declared in _core/include/drivers/i2c.h_ (possibly adding resources of some are missing).
This is only my opinion of course.

**Comment by massonju** [comment]
Thanks for your feedback @etienne-lms 

> Implementing an I2C service in OP-TEE exposed to Linux kernel makes sense to me ...

Yes I agree with that but we've been tasked that all the i2c operations **must** be done in OP-TEE.
Nothing is forwarded to the linux kernel.

That would be this kind of logic:
```
|----------------------+--------+-------------------------------------|
|                      | core   | i2c driver: core/drivers/ti_i2c.c   |
| OP-TEE os            | ------ | ----------------------------------- |
|                      | PTA    | i2c API exposed:                    |
|                      |        | - i2c_read_cmd                      |
|                      |        | - i2c_write_cmd                     |
|                      |        | - i2c_slave_mode_cmd                |
|                      |        | - i2c_slave_master_cmd              |
|                      |        | ...                                 |
|----------------------+--------+-------------------------------------|
        ^
        |
        v
|-------------------------------+-------------------------------------|
| Trusted Application           | Hypothetic i2c crypto chip driver:  |
|                               | - call internally i2c_*_cmd         |
|                               | - expose commands:                  |
|                               |   - crypto_write_key_cmd            |
|                               |   - crypto_read_key_cmd             |
|                               |   - crypto_remove_key_cmd           |
|                               |   ...                               |
|-------------------------------+-------------------------------------|
        ^
        |
        v
|-------------------------------+-------------------------------------|
| Linux                         | crypto service:                     |
|                               | - call crypto_*_cmd                 |
|-------------------------------+-------------------------------------|
```
And so we are wondering about how it will be accepted if we try to upstream the `optee-os` part, does it make sense to do like this ?

**Comment by etienne-lms** [comment]
I understand your figure as:
- Linux invokes crypto_*_cmd commands of a TA
- That TA calls i2c_*_cmd commands of the PTA
- The PTA perfoms the I2C accesses.
Am I right?

Since the example you show is related to crypto operations, I think the TA should better rely on existing `TEE_xxx()` crypto operation API functions defined by the GP TEE Internal Core API specification. On OP-TEE OS side, a crypto driver implements the needed crypto oprations (see `drvcrypt` resources in OP-TEE OS source tree)  and interacts with the external crypto device through an I2C bus to perform the required crypto operations.

**Comment by massonju** [comment]
> I understand your figure as:
> - Linux invokes crypto_*_cmd commands of a TA
> - That TA calls i2c_*_cmd commands of the PTA
> - The PTA perfoms the I2C accesses.
> 
> Am I right?

Yes exactly but the funny part is that we don't know what will be connected through i2c.

Basically we've been tasked to write an i2c driver for TI boards, be able to switch between slave/master mode and the driver **must** be upstreamed in OP-TEE.

We will certainly have an hardware setup to test the i2c driver (random i2c devices either in slave or master) but we won't have a real use case.

In my example I took an hypothetic i2c crypto chip because it seems to be a common case but it might be something different.

And so the first thing I asked myself was: Would it be accepted if I send an i2c driver (+ maybe PTA) without a real use/test case ?

I would say no but I see drivers like `ls_i2c.c` where nobody use it (no calls of `i2c_bus_xfer` ...).

**Comment by jenswi-linaro** [comment]
We should be able to accommodate something of this. Is the PTA only going to be used for testing or do you expect to expose any I2C device to a TA? I assume the former since it might be tricky to keep the device secure.

**Comment by massonju** [comment]
> We should be able to accommodate something of this.

Got it

> Is the PTA only going to be used for testing or do you expect to expose any I2C device to a TA?

I would say the PTA will expose i2c device to a TA but we did not take a final decision on that.

Thanks a lot @jenswi-linaro @etienne-lms for your support.
I think I got enough information, I don't want to bore you more, we need to take decision on our side.

**Comment by etienne-lms** [comment]
I must admit exposing an I2C device straight to TA looks strange to me. I was more thinking of exposing a I2C service to the Linux kernel when the platform has constraints where a single I2C bus is available but used to communicate with 2 devices, one used by the secure world and one by the non-secure world.
