### ISSUE TITLE
Question: single key storage for XTS crypto mode

### ISSUE THREAD

**Issue by ilie-halip-nxp** [OP-TEE/optee_os#6771]
XTS mode (for AES and SM4) requires 2 keys for crypto operations.

I'm looking into a scenario about integrating PSA [1] with op-tee.

In the PSA spec, XTS mode is acknowledged to need 2 keys, but says that in this case a double-sized key should be used: "_XTS mode uses two keys for the underlying block cipher. These are provided by using a key that is twice the normal key size for the cipher_" [2]. This means that a PSA SM4-128-XTS key is actually 256 bits. When using this key for a crypto operation, it could be split into 2 parts and each of them used separately as operation keys.

Right now, op-tee only allows 128-bit SM4 keys - would it be possible to support 256-bit SM4 keys for this use case? I can open a PR.

[1] https://arm-software.github.io/psa-api/crypto/1.1/index.html
[2] https://arm-software.github.io/psa-api/crypto/1.1/api/ops/ciphers.html#c.PSA_ALG_XTS

**Comment by ilie-halip-nxp** [comment]
Hey!

I believe op-tee right now already supports the `TEE_ALG_SM4_XTS` algorithm, there is a test for it in [optee-test](https://github.com/OP-TEE/optee_test/blob/dda3212f244f618116cbcefc6183802b247baae5/ta/crypto_perf/ta_crypto_perf.c#L279). And in my testing I found that I can indeed use 2 keys in the same manner.

My issue is that PSA APIs don't have a concept of using multiple keys for crypto operations. For example, [psa_cipher_encrypt()](https://arm-software.github.io/psa-api/crypto/1.1/api/ops/ciphers.html#c.psa_cipher_encrypt) and many more functions take a single key ID.

What I would like to achieve is to store the 2 128-bit SM4-XTS keys as a single 256-bit TEE object. Right now, op-tee only [allows](https://github.com/OP-TEE/optee_os/blob/a8cfcdf2387ce322dd2f04151b32c340c1ae53c6/core/tee/tee_svc_cryp.c#L526) 128-bit SM4 keys.

**Comment by jforissier** [comment]
> Hey!
> 
> I believe op-tee right now already supports the `TEE_ALG_SM4_XTS` algorithm, there is a test for it in [optee-test](https://github.com/OP-TEE/optee_test/blob/dda3212f244f618116cbcefc6183802b247baae5/ta/crypto_perf/ta_crypto_perf.c#L279). 

True :smile:
 
> And in my testing I found that I can indeed use 2 keys in the same manner.

Good!

> My issue is that PSA APIs don't have a concept of using multiple keys for crypto operations. For example, [psa_cipher_encrypt()](https://arm-software.github.io/psa-api/crypto/1.1/api/ops/ciphers.html#c.psa_cipher_encrypt) and many more functions take a single key ID.
> 
> What I would like to achieve is to store the 2 128-bit SM4-XTS keys as a single 256-bit TEE object. Right now, op-tee only [allows](https://github.com/OP-TEE/optee_os/blob/a8cfcdf2387ce322dd2f04151b32c340c1ae53c6/core/tee/tee_svc_cryp.c#L526) 128-bit SM4 keys.

Since OP-TEE has proper support for the two keys already, why not use the API as it is? You probably don't need much code to do the adaptation between PSA and OP-TEE.

**Comment by ilie-halip-nxp** [comment]
Fair enough, I'll close this ticket. Thanks!
