### ISSUE TITLE
ARM32 bit plaform overflow in tee_entry_get_os_revision()  when handling Git SHA1

### ISSUE THREAD

**Issue by GseoC** [OP-TEE/optee_os#6783]
Hi, I think I might have been very (un)lucky here.

<command-line>: error: unsigned conversion from 'long long int' to 'uint32_t' {aka 'unsigned int'} changes value from '30451703637' to '386932565' [-Werror=overflow]
core/arch/arm/tee/entry_fast.c:363:20: note: in expansion of macro 'TEE_IMPL_GIT_SHA1'
  363 |         args->a2 = TEE_IMPL_GIT_SHA1;
      |                    ^~~~~~~~~~~~~~~~~

Looking at tee_entry_get_os_revision() on ARM32 platforms, in
args->a2 = TEE_IMPL_GIT_SHA1; 
We put a _at least!_ 8 characters long (4bytes) string in a uint32_t. But what if git rev-parse returns more than 8 characters (e.g: collision with another commit in my git tree on the first 8 characters)?

How would you handle this case?

**Comment by jforissier** [comment]
We should truncate the output of `git rev-parse` to 8 characters. It doesn't matter so much is the value is ambiguous IMO.

**Comment by etienne-lms** [comment]
I agree with both of you. I would suggest something like:
```c
	/* Discard upper bytes if TEE_IMPL_GIT_SHA1 value overflows args->a2 */
	args->a2 = TEE_IMPL_GIT_SHA1 & GENMASK_64(sizeof(args->a2) * 8 - 1, 0);

**Comment by jforissier** [comment]
> I agree with both of you. I would suggest something like:
> 
> ```c
> 	/* Discard upper bytes if TEE_IMPL_GIT_SHA1 value overflows args->a2 */
> 	args->a2 = TEE_IMPL_GIT_SHA1 & GENMASK_64(sizeof(args->a2) * 8 - 1, 0);
> ```

We want the start of the SHA1 string i.e., the 32 or 64 most significant bits. So discarding the upper bytes won't work. My proposal: https://github.com/OP-TEE/optee_os/pull/6785
