### ISSUE TITLE
Try to write to RPMB using CFG_RPMB_TESTKEY

### ISSUE THREAD

**Issue by CZutter** [OP-TEE/optee_os#6800]
Hello,

I try to write from UBoot to RPMB using CFG_RPMB_TESTKEY but verify key failed. I use the "fiovb" sample which looks well so I think the issue is in my configuration.
Optee is built with commandline ... CFG_EARLY_TA=y CFG_RPMB_FS=y CFG_TA_DEBUG=y CFG_TEE_CORE_TA_TRACE=y CFG_TEE_TA_LOG_LEVEL=4 CFG_TEE_CORE_LOG_LEVEL=4 CFG_RPMB_TESTKEY=y CFG_RPMB_WRITE_KEY=n

UBoot command "write_persistent_value test 123" results follwing output:

```
D/TC:0   tee_entry_exchange_capabilities:100 Asynchronous notifications are disabled
D/TC:0   tee_entry_exchange_capabilities:109 Dynamic shared memory is enabled
D/TC:0 0 core_mmu_xlat_table_alloc:526 xlat tables used 4 / 8
D/TC:? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA 22250a54-0bf1-48fe-8002-7b20f1c9c9b1
D/TC:? 0 ldelf_load_ldelf:96 ldelf load address 0x80006000
D/LD:  ldelf:134 Loading TS 22250a54-0bf1-48fe-8002-7b20f1c9c9b1
F/TC:? 0 trace_syscall:151 syscall #3 (syscall_get_property)
F/TC:? 0 trace_syscall:151 syscall #5 (syscall_open_ta_session)
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF 22250a54-0bf1-48fe-8002-7b20f1c9c9b1 (early TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF 22250a54-0bf1-48fe-8002-7b20f1c9c9b1 (Secure Storage TA)
D/TC:? 0 tee_rpmb_init:1125 RPMB: Syncing device information
F/TC:? 0 plat_prng_add_jitter_entropy:72 0xC00
D/TC:? 0 tee_rpmb_init:1133 RPMB: RPMB size is 32*128 KB
D/TC:? 0 tee_rpmb_init:1134 RPMB: Reliable Write Sector Count is 1
D/TC:? 0 tee_rpmb_init:1161 RPMB INIT: Deriving key
D/TC:? 0 tee_rpmb_key_gen:302 RPMB: Using test key
D/TC:? 0 tee_rpmb_init:1176 RPMB INIT: Verifying Key
```

Assumue trouble starts here. I figure out "get_op_result_bits(...)" sets op_result = RPMB_RESULT_GENERAL_FAILUR
hence "tee_rpmb_resp_unpack_verify(...)" returns  TEE_ERROR_GENERIC

```
E/TC:? 0 tee_rpmb_verify_key_sync_counter:1024 Verify key returning 0xffff0000
E/TC:? 0 tee_rpmb_init:1187 Verify key failed!
E/TC:? 0 tee_rpmb_init:1188 Make sure key here matches device key
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0000
E/LD:  init_elf:453 sys_open_ta_bin(22250a54-0bf1-48fe-8002-7b20f1c9c9b1)
E/TC:? 0 ldelf_init_with_ldelf:131 ldelf failed with res: 0xffff0000
D/TC:? 0 tee_ta_open_session:716 init session failed 0xffff0000
```

Is this information sufficient to give my a hint what I am doing wrong or is some more information needed?

Many thanks Christian.

**Comment by CZutter** [comment]
Hi jenswi,

thanks for your proposal. I did the test with a new board and the problem persits (default in config.mk is  CFG_RPMB_WRITE_KEY ?= n). Also I would await RPMB_RESULT_AUTH_FAILURE in case of RPMB is already  programmed with a different key.
Is there any possibility to figure out if the key is already programmed?

**Comment by jenswi-linaro** [comment]
Looking at the error code `0xffff0000` (TEE_ERROR_GENERIC), op_result is not `RPMB_RESULT_AUTH_KEY_NOT_PROGRAMMED`, but I don't know what it is.

**Comment by CZutter** [comment]
Because we can not locate the issue in our configuration until now we decide to use another storage for our purpose. To use secure storage is not mandatory for us at the time. Maybe I will come back somewhere :).
