### ISSUE TITLE
how to include python3 package in op-tee for pi3 build

### ISSUE THREAD

**Issue by jamesxyzzy** [OP-TEE/optee_os#6808]

**Comment by jbech-linaro** [comment]
If the question is about the rootfs, then it can be done via Buildroot configs. When you've figured out the flags needed, then you can enable it like [here](https://github.com/OP-TEE/build/blob/master/rpi3.mk#L11-L36). if the question is about OP-TEE os, then you're out of luck. It doesn't work.

**Comment by jamesxyzzy** [comment]
Thanks very much for the information. I should add that I am following the
instructions in  OP-TEE: Part 3 – Setting up OP-TEE on QEMU & Raspberry Pi
3 – Kickstart Embedded
<https://kickstartembedded.com/2022/11/07/op-tee-part-3-setting-up-op-tee-on-qemu-raspberry-pi-3/>
for Pi 3


I found that I could do the following :
BR2_PACKAGE_PYTHON3=y make all -j$(nproc)
On the rpi 3, 'which python3' results in: /usr/bin/python3

But then i tried BR2_PACKAGE_PYTHON3=y BR2_PACKAGE_PYTHON_SERIAL=y  make
all -j$(nproc)
which did not work.
python3 is still found but I could not find pyserial  :

>>>import serial
Traceback (most recent call last):
.......
ModuleNotFoundError:No module named 'serial'
>>>

Is pre-pending the make command with multiple BR2_PACKAGE_XXX=y correct
syntax?
What am i doing wrong?

Many thanks

**Comment by jamesxyzzy** [comment]
Joakim,
When I attempt to add systemd package to optee like this =>
BR2_PACKAGE_SYSTEMD=y make all -j$(nproc)

I get this :

#
# configuration written to
/home/james/Desktop/optee_rpi3-ble-centric-kernel-tools/out-br/.config
#
make[1]: Leaving directory
'/home/james/Desktop/optee_rpi3-ble-centric-kernel-tools/buildroot'
make[1]: Entering directory
'/home/james/Desktop/optee_rpi3-ble-centric-kernel-tools/out-br'
package/systemd/systemd.mk:764: *** Configuration error: both "systemd" and
 are selected as providers for virtual package "udev". Only one provider
can be selected at a time. Please fix your configuration.  Stop.
make[1]: *** [Makefile:23: _all] Error 2
make[1]: Leaving directory
'/home/james/Desktop/optee_rpi3-ble-centric-kernel-tools/out-br'
make: *** [common.mk:346: buildroot] Error 2

Confused by what I found on the web - I seek your advice.

Thanks.
