### ISSUE TITLE
Is is possible to develop a driver in optee?

### ISSUE THREAD

**Issue by astuowhu** [OP-TEE/optee_os#681]
I may have to develop a driver in secure world to protect some hardware resources on Hikey, but I don't know how, espescially that I'm not sure whether the hw resources can be accessed when in secure world. Because I'm not familiar with embeded development.

Could someone please show me an example, provide me with some documentation or just some suggestions? 

Many thanks.

**Comment by jenswi-linaro** [comment]
Please have a look in `core/drivers` there's a few uart drivers.

**Comment by astuowhu** [comment]
I find GIC and PL011 and some others. However, hikey doesn't have GIC enabled(CFG_GIC is not set), but hikey has gic-400, why not set CFG|_GIC. Is it because of some special reasons?

**Comment by jenswi-linaro** [comment]
No special reasons, it's just that we currently don't need to receive any FIQs on Hikey. Note that ARM-TF initializes GIC at boot.

**Comment by astuowhu** [comment]
I didn't check ARM-TF, I will see it soon.
Lots of thanks.
