### ISSUE TITLE
Accessing HUK in trusted application

### ISSUE THREAD

**Issue by arunlalkm-intel** [OP-TEE/optee_os#6810]
I can see that using PTA_SYSTEM_DERIVE_TA_UNIQUE_KEY I can get a derivation of HUK 

TEE_InvokeTACommand(session, 0, PTA_SYSTEM_DERIVE_TA_UNIQUE_KEY,
				  param_types, params, &ret_origin);

But this gives a derivation of HUK + caller UUID + buffer we pass (optional) 

Problem statement:
The functionality I am looking for is to use HUK + buffer I have + use the crypto algorithm of my choice. 
And to do the same from trusted application. (do not want to use TA UUID)

Question:
Is there a way HUK can be accessed in trusted application? 
So that I can use the HUK + the buffer of my choice and crypto algo from mbedtls and make a key.

**Comment by jbech-linaro** [comment]
> Is there a way HUK can be accessed in trusted application?

Not directly.

> So that I can use the HUK + the buffer of my choice and crypto algo from mbedtls and make a key.

Would you be able to use something like what is done [here](https://github.com/OP-TEE/optee_os/blob/master/ta/trusted_keys/entry.c#L60-L93) . I.e., before calling `TEE_InvokeTACommand` you can fill up the `params` as needed?

**Comment by arunlalkm-intel** [comment]
Yes this option can be used, but doesn't it mean the derived key is based on HUK + Buffer + UUID ?
I was looking for an option which uses just the HUK + Buffer 

And this options also does not give me control over which crypto algorithm to use rt?

**Comment by jenswi-linaro** [comment]
The point is that TAs aren't trusted with the HUK since the platform's security relies on the HUK. The UUID is also used to provide separation between TAs.

**Comment by arunlalkm-intel** [comment]
Thank you. 
Closing ticket.
