### ISSUE TITLE
Question about CFG_CORE_HEAP_SIZE

### ISSUE THREAD

**Issue by ydonghyuk** [OP-TEE/optee_os#6814]
CFG_CORE_HEAP_SIZE needs to be increased in the ongoing project.
In this case, I would like to inquire about which memory there is a trade-off.

In default settings without any modification,
It is confirmed that 2MB of TZDARM_SIZE is used as TEE_RAM. Is additional allocation being made here?

**Comment by jenswi-linaro** [comment]
Yes, the heap memory is carved out from that range.

**Comment by ydonghyuk** [comment]
@etienne-lms 

You told me that CFG_CORE_HEAP_SIZE is only involved in TEE_RAM, but I don't understand the sentence below.
"the bigger CFG_CORE_HEAP_SIZE is, the lower TA_RAM size is."

Is this only if CFG_TEE_RAM_VA_SIZE is set?

**Comment by etienne-lms** [comment]
My mistake. Indeed TEE_RAM size is set from `CFG_TEE_RAM_VA_SIZE` (I agree the name is confusing).
Changing `CFG_CORE_HEAP_SIZE` will not modify `CFG_TEE_RAM_VA_SIZE`, hence not modify TA_RAM size.

**Comment by ydonghyuk** [comment]
@etienne-lms 
Thank you for the correction.
If CFG_WITH_PAGER=n and CFG_TEE_RAM_VA_SIZE is not set, I would like to know how TEE_RAM_VA_SIZE is set.

**Comment by etienne-lms** [comment]
`TEE_RAM_VA_SIZE` defaults to `CORE_MMU_PGDIR_SIZE` that is 2MBytes on Armv8-A.

**Comment by ydonghyuk** [comment]
@etienne-lms 
To increase the maximum RSA operation, we are going to modify CORE_HEAP_SIZE from 64kB to about 144kB.
Will there be any major problems if I continue to use the default TEE_RAM of 2MB?

**Comment by etienne-lms** [comment]
I don't think you will face issues.

**Comment by ydonghyuk** [comment]
@etienne-lms 
Thank you very much for your help.
