### ISSUE TITLE
Issue with HiKey make flash

### ISSUE THREAD

**Issue by zero-clouds-** [OP-TEE/optee_os#682]
Ran into an issue when running `make flash`. It would sit at `< waiting for device >` forever. Found that running `sudo make flash` allows the command to continue.

Similarly, `fastboot devices` would not show the board, but `sudo fastboot devices` would. Perhaps they are connected?

Thanks,
B

**Comment by hybridNeo** [comment]
It probably accessed /dev/tty of your computer, so it needs sudo

**Comment by jbech-linaro** [comment]
@zero-clouds- still an issue? To me out sounds like it's about udev rules also. My `/etc/udev/rules.d/51-hikey.rules` file looks like this:
```
# HiKey board -- https://github.com/96boards/documentation/wiki/HiKeyGettingStarted
# fastboot protocol on Kirin620 SoC
SUBSYSTEM=="usb", ATTR{idVendor}=="18d1", ATTR{idProduct}=="d00d", MODE="0660", GROUP="dialout"
# adb protocol on Kirin620 SoC
SUBSYSTEM=="usb", ATTR{idVendor}=="12d1", ATTR{idProduct}=="1057", MODE="0660", GROUP="dialout"
# rndis for Kirin620 SoC
SUBSYSTEM=="usb", ATTR{idVendor}=="12d1", ATTR{idProduct}=="1050", MODE="0660", GROUP="dialout"
# Recovery mode Kirin620
# HiKey board recovery port (to flash firmware with hisi-idt.py tool)
# The device is available when the board is booted with jumper J15 pins 3-4 are closed
# NOTE: the devices disappears after 60s (firmware timeout)
SUBSYSTEM=="usb", ATTR{idVendor}=="12d1", ATTR{idProduct}=="3609", MODE="0660", GROUP="plugdev" RUN+="chmod 777 /dev/ttyUSB*"

```

**Comment by jbech-optee-adm** [comment]
Question has been answered, but If the issue persists or you have more questions, please re-open the issue.
