### ISSUE TITLE
Systemd buildroot compile time errors when building for RPi3

### ISSUE THREAD

**Issue by jamesxyzzy** [OP-TEE/optee_os#6824]

**Comment by ivila** [comment]
```both "systemd" and are selected```
What is the missing part of the **and**? I think the error is quiet clear, that you must select only one of those two.

**Comment by jbech-linaro** [comment]
May I also ask you to spend some time on making reports/questions here look somewhat good and readable next time posting here? Pasting output from your environment into the subject line and send that a report simply doesn't look good. Pick a clear subject, add good description and try to use the [markdown formatters](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) when showing code and error messages. With those best practices, you'd be more likely to get (good) feedback from others.

**Comment by jamesxyzzy** [comment]
Let's take this in 3 steps :

Step 1 - given I did this : BR2_PACKAGE_SYSTEMD=y make all -j$(nproc)
and got this error message :

#
# configuration written to
/home/james/Desktop/optee_rpi3-ble-centric-kernel-tools/out-br/.config
#
make[1]: Leaving directory
'/home/james/Desktop/optee_rpi3-ble-centric-kernel-tools/buildroot'
make[1]: Entering directory
'/home/james/Desktop/optee_rpi3-ble-centric-kernel-tools/out-br'
package/systemd/systemd.mk:764: *** Configuration error: both "systemd" and
 are selected as providers for virtual package "udev". Only one provider
can be selected at a time. Please fix your configuration.  Stop.
make[1]: *** [Makefile:23: _all] Error 2
make[1]: Leaving directory
'/home/james/Desktop/optee_rpi3-ble-centric-kernel-tools/out-br'
make: *** [common.mk:346: buildroot] Error 2

Step 2 - but, looking closer at the error message :

*** Configuration error: both "systemd" and  are selected as providers for
virtual package
                                                                     ^
there is a missing word here between 'and' and the 'are' !!!
viz: ....blah,.....both "systemd" and X are selected as.......blah,

Step 3 - What is X??

ivila - "I think the error is quiet clear, that you must select only one of
those two"
The answer must be - one of which two?

Thanks in advance for your help.

**Comment by ivila** [comment]
@jamesxyzzy after adding BR2_PACKAGE_SYSTEMD=y, I meet the same error as you do
```shell
package/systemd/systemd.mk:883: *** Configuration error: both "systemd" and  are selected as providers for virtual package "udev". Only one provider can be selected at a time. Please fix your configuration.  Stop.
```
But I also notice that there is another warning
```shell
../out-br/defconfig:23:warning: override: reassigning to symbol BR2_PACKAGE_SYSTEMD
```
And after checking the configuration file, I see two **BR2_PACKAGE_SYSTEMD=y**, so maybe the duplicate configuration result in the error.
Just try not adding **BR2_PACKAGE_SYSTEMD=y** manually as it is auto selected (make sure run **make clean** manually at the buildroot folder first)

**Comment by jamesxyzzy** [comment]
systemd is not used in the op-tee rpi3 build (auto selected or not).
see : https://ubuntushell.com/identify-the-init-system/

i did this on the rpi3b target :

# readlink /sbin/init
../bin/busybox
# ls -l /sbin/init
lrwxrwxrwx    1 root     root            14 May  8  2024 /sbin/init ->
../bin/busybox
#

Ubuntu 22.04 does use systemd :

***@***.***:~/Desktop$ ls -l /sbin/init
lrwxrwxrwx 1 root root 20 Nov 21 15:57 /sbin/init -> /lib/systemd/systemd
***@***.***:~/Desktop$

Thanks

**Comment by ivila** [comment]
@jamesxyzzy Maybe you should add an extra argument "BR2_PACKAGE_PROVIDES_UDEV=systemd", and give it a try.
