### ISSUE TITLE
Size of object returned by shdr_alloc_and_copy can be smaller than expected? 

### ISSUE THREAD

**Issue by karthikbhata97** [OP-TEE/optee_os#6825]
In `shdr_alloc_and_copy`, `SHDR_GET_SIZE` is used to get the size required for allocation.
https://github.com/OP-TEE/optee_os/blob/6e4bc5d90b23db5bb1bd7e696cb532d9536cd4b6/core/crypto/signed_hdr.c#L31

But `SHDR_GET_SIZE` might return 0 if there is a potential overflow
https://github.com/OP-TEE/optee_os/blob/6e4bc5d90b23db5bb1bd7e696cb532d9536cd4b6/core/include/signed_hdr.h#L59

But `shdr_alloc_and_copy` does not check if the return value is 0 before passing to `malloc`. Hence, the size of the returned object might be smaller than expected, resulting in an out-of-bounds read later.

**Comment by jenswi-linaro** [comment]
You're right. Do you want to fix it with a pull request or should I do it?

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/optee_os/pull/6848 please let my know if you want your name and email address in an `Reported-by:` tag.

**Comment by karthikbhata97** [comment]
Sorry, I was away. I am okay with how the commit it done.
