### ISSUE TITLE
OperationState

### ISSUE THREAD

**Issue by shirinebadi** [OP-TEE/optee_os#6826]
Hi.

In `CipherDoFinal()`, there is this constant checking:

```
	if (operation->operationState != TEE_OPERATION_STATE_ACTIVE) {
		res = TEE_ERROR_BAD_PARAMETERS;
		goto out;
	}
```

How can I set and get operation state? I couldn't find it in `TEE_GetOperationInfo`.

**Comment by ivila** [comment]
I think this is an internal state that you must not operate it yourself.
May I ask why you want to set and get operation state?
