### ISSUE TITLE
Question about MbedTLS mbedtls_mpi_uint

### ISSUE THREAD

**Issue by ubisun** [OP-TEE/optee_os#6827]
Hi! I have a question regarding MbedTLS mbedtlsmpi_uint.

As I know, user-level mbedtls library is developed to use only uint32_t as mbedtls_mpi_uint.
I would like to use it as uint64_t to make better performance during Bignum operation.

When I tried as below, it works fine with uint64_t as mbedtls_mpi_uint.

1. lib/libmbedtls/include/mbedtls_config_uta.h
\+#undef MBEDTLS_HAVE_INT32
\+#define MBEDTLS_HAVE_INT64

2. lib/libutee/tee_api_arith_mpi.c
\-       COMPILE_TIME_ASSERT(sizeof(mbedtls_mpi_uint) == sizeof(uint32_t));
\+       //COMPILE_TIME_ASSERT(sizeof(mbedtls_mpi_uint) == sizeof(uint32_t));
...
\-       memcpy(dst_hdr + 1, src_hdr + 1, src_hdr->nblimbs * sizeof(uint32_t));
\+       memcpy(dst_hdr + 1, src_hdr + 1, src_hdr->nblimbs * sizeof(mbedtls_mpi_uint));

Could you please give me some concern if we use MBEDTLS_HAVE_INT64 for user-level mbedtls library?

**Comment by jenswi-linaro** [comment]
Just above the compile time assert there's this comment explaining the problem:
``` C
        /*      
         * The way the GP spec is defining the bignums it's
         * difficult/tricky to do it using 64-bit arithmetics given that
         * we'd need 64-bit alignment of the data as well.
         */     
```
How do you plan to handle the alignment problem?

**Comment by ubisun** [comment]
Thanks for your response!

When I check the alignment, current optee_os handles its alignment based on long type size.

#define MEMPOOL_ALIGN	__alignof__(long)
(https://github.com/OP-TEE/optee_os/blob/master/lib/libutils/ext/include/mempool.h#L31)

Trusted Application uses static memory for mempool with "__aligned(MEMPOOL_ALIGN)".
(https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_arith_mpi.c#L45)

In allocation step, the alignment is checked.
(https://github.com/OP-TEE/optee_os/blob/master/lib/libutils/ext/mempool.c#L124-L125)



If we consider MPI allocation scenario, below call flow is used.
mempool_alloc() -> raw_malloc() -> raw_memalign()

> void *raw_malloc(size_t hdr_size, size_t ftr_size, size_t pl_size,
		 struct malloc_ctx *ctx)
{
	/*
	 * Note that we're feeding SizeQ as alignment, this is the smallest
	 * alignment that bget() can use.
	 */
	return raw_memalign(hdr_size, ftr_size, SizeQ, pl_size, ctx);
}

The SizeQ is used for basis of alignment as below.
#define SizeQ	((SizeQuant > QLSize) ? SizeQuant : QLSize)
#ifdef __LP64__
#define SizeQuant   16
#endif

Therefore, IMHO, the User-space MPI 64bits alignment can be handled with current optee_os implementation.

**Comment by jenswi-linaro** [comment]
Please see TEE Internal Core API Specification v1.3.1, https://globalplatform.org/specs-library/tee-internal-core-api-specification/, section 8.3.1 TEE_BigInt.

Here's the crux:
> 1. The size of the representation SHALL be a multiple of 4 bytes.
> 2. The extra memory within the representation to store metadata SHALL NOT exceed 8 bytes.
> 3. The representation SHALL be stored 32-bit aligned in memory
