### ISSUE TITLE
Does memory fragmentation exist in optee_os?

### ISSUE THREAD

**Issue by LeiSen62** [OP-TEE/optee_os#6828]
When I test encryption and decryption cases for a long time, malloc function returns NULL. Is there a memory fragmentation issue?

**Comment by ivila** [comment]
Maybe you should check the following first:
1. if there are memory leaks? Do we free everything in the end?
2. if there are special test cases, like it need massive amount of memory?
3. if your TA heap enough? check the TA_DATA_SIZE in user_ta_header_defines.h

**Comment by LeiSen62** [comment]
Thanks！
