### ISSUE TITLE
Accessing UART Inside OP-TEE Trusted Application

### ISSUE THREAD

**Issue by Arun-mcet** [OP-TEE/optee_os#6830]
Hi, 
I am using Raspberry Pi 3+ Model B board.I need to access the UART inside the OP-TEE trusted application but I am unable to include the necessary files inside my trusted application. Whether it is possible to access the UART and other Peripherals inside the OP-TEE Trusted application or It is necessary  to write driver file to access UART. If, it is possible where I can find that inbuilt  api's to access the UART . If not where I need to include  header and source files available in normal world to access the UART and other Peripherals in trusted world.

**Comment by jbech-linaro** [comment]
What do you mean by access? Your debug prints etc are routed to the UART by default. Are you saying that you want to "own" the UART completely from a TA? That's not possible I guess, since the core itself uses the UART.

**Comment by Arun-mcet** [comment]
> What do you mean by access? Your debug prints etc are routed to the UART by default.

Here, by "access," I mean establishing communication between an OP-TEE-enabled SoC (like the Raspberry Pi 3+ Model B) and external devices via UART. These operations need to be performed within the trusted application, for which I require TEE APIs. However, I am currently unable to locate these APIs.

>Are you saying that you want to "own" the UART completely from a TA?

Yes, that's correct. For example, I intend to utilize UART0 within the Trusted Application to both transmit and receive data from external devices. During this process, UART0 won't be accessible from the Normal World. I aim to have full control over UART operations exclusively within the Trusted Application.

**Comment by jbech-linaro** [comment]
Ok, got it. But, there is no support for doing that. I/O routed to TA's are limited. You're probably in a better situation if you try to do it from a [PTA](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#pseudo-trusted-applications) at this point. If you can control the GPIO pins, then you should be able to talk to external sensors/devices via UART in a PTA after some hacking I believe.

**Comment by Arun-mcet** [comment]
Thanks for your response. Is there another method to utilize the UART within the trusted application?
