### ISSUE TITLE
Null pointer access in bin_close() from ldelf_syscalls.c : ldelf_syscall_open_bin()

### ISSUE THREAD

**Issue by vting-seq** [OP-TEE/optee_os#6832]
There is a scenario where bin_close will call binh->op->close(binh->h), where binh->op->close == NULL - and the TEE will data abort.

If one attempts to load a user TA (or an SP ELF) that does _not_ exist in any of the TA storages, the SCATTERED_ARRAY_FOREACH will fall out the bottom with binh->op pointing to SCATTERED_ARRAY_END... which is one element _past_ the end of the array.

Since the TA (or SP ELF) is not found, res at this point == TEE_ERROR_ITEM_NOT_FOUND, and will jump to err: and call bin_close(binh).

binh->op will _not_ have a close field assigned (binh->op->close == NULL) and since bin_close doesn't check for whether or not binh->op->close != NULL, it will attempt to call 0x00000000.

In addition, semantically, only the last checked storage will have binh->op->close called on it (all previous storages where the open failed, will _not_ have binh->op->close called - however the last checked storage whether it succeeds or fails will have binh->op->close called).

This code is extant in the master branch as of this posting.

```
if (is_user_ta_ctx(sess->ctx) || is_stmm_ctx(sess->ctx)) {
		SCATTERED_ARRAY_FOREACH(binh->op, ta_stores,
					struct ts_store_ops) {
			DMSG("Lookup user TA ELF %pUl (%s)",
			     (void *)bb_uuid, binh->op->description);

			res = binh->op->open(bb_uuid, &binh->h);
			DMSG("res=%#"PRIx32, res);
			if (res != TEE_ERROR_ITEM_NOT_FOUND &&
			    res != TEE_ERROR_STORAGE_NOT_AVAILABLE)
				break;
		}
	} else if (is_sp_ctx(sess->ctx)) {
		SCATTERED_ARRAY_FOREACH(binh->op, sp_stores,
					struct ts_store_ops) {
			DMSG("Lookup user SP ELF %pUl (%s)",
			     (void *)bb_uuid, binh->op->description);

			res = binh->op->open(bb_uuid, &binh->h);
			DMSG("res=%#"PRIx32, res);
			if (res != TEE_ERROR_ITEM_NOT_FOUND &&
			    res != TEE_ERROR_STORAGE_NOT_AVAILABLE)
				break;
		}
	} else {
		res = TEE_ERROR_ITEM_NOT_FOUND;
	}

	if (res)       <----- at this point if no TA or SP is found, binh->op points to one past the end of the array
		 goto err;
.
.
.


err:
	bin_close(binh);   <------ binh->op->close == NULL


static void bin_close(void *ptr)
{
	struct bin_handle *binh = ptr;

	if (binh) {
		if (binh->op && binh->h)
			binh->op->close(binh->h);     <--------- binh->op->close == NULL !!
		file_put(binh->f);     
	}
	free(binh);
}
```

**Comment by jforissier** [comment]
Hi @vting-seq,

Have you found this issue when running the code, or is it static code analysis? I don't think the NULL pointer de-reference can happen because `binh->h` is supposed to remain NULL when `binh->op->open()` returns any error code.

That being said, it may be a bit better to make sure `binh->op` is either NULL or valid. Perhaps like so?
```diff
diff --git a/core/kernel/ldelf_syscalls.c b/core/kernel/ldelf_syscalls.c
index 1c4fcef96..63679aac4 100644
--- a/core/kernel/ldelf_syscalls.c
+++ b/core/kernel/ldelf_syscalls.c
@@ -126,6 +126,7 @@ TEE_Result ldelf_syscall_open_bin(const TEE_UUID *uuid, size_t uuid_size,
 	struct ts_session *sess = ts_get_current_session();
 	struct user_mode_ctx *uctx = to_user_mode_ctx(sess->ctx);
 	struct system_ctx *sys_ctx = sess->user_ctx;
+	const struct ts_store_ops *op = NULL;
 	struct bin_handle *binh = NULL;
 	uint8_t tag[FILE_TAG_SIZE] = { 0 };
 	unsigned int tag_len = sizeof(tag);
@@ -158,8 +159,9 @@ TEE_Result ldelf_syscall_open_bin(const TEE_UUID *uuid, size_t uuid_size,
 		return TEE_ERROR_OUT_OF_MEMORY;
 
 	if (is_user_ta_ctx(sess->ctx) || is_stmm_ctx(sess->ctx)) {
-		SCATTERED_ARRAY_FOREACH(binh->op, ta_stores,
+		SCATTERED_ARRAY_FOREACH(op, ta_stores,
 					struct ts_store_ops) {
+			binh->op = op;
 			DMSG("Lookup user TA ELF %pUl (%s)",
 			     (void *)bb_uuid, binh->op->description);
 
@@ -170,8 +172,9 @@ TEE_Result ldelf_syscall_open_bin(const TEE_UUID *uuid, size_t uuid_size,
 				break;
 		}
 	} else if (is_sp_ctx(sess->ctx)) {
-		SCATTERED_ARRAY_FOREACH(binh->op, sp_stores,
+		SCATTERED_ARRAY_FOREACH(op, sp_stores,
 					struct ts_store_ops) {
+			binh->op = op;
 			DMSG("Lookup user SP ELF %pUl (%s)",
 			     (void *)bb_uuid, binh->op->description);

```

It would also be good to have a test case for a non-existent TA in `optee_test`.

**Comment by vting-seq** [comment]
Hi @jforissier ,

Ah, ok - I wasn't aware of the requirement for binh->h to remain NULL if the binh->op->open() fails for any reason.

This was found in running code, I had made a typo in a UUID, and found OpTEE to crash at this point, but it would seem that the semantics of our own custom TA storage needs to change (binh->h = NULL for any error code out of binh->op->open())

Thanks!

**Comment by jforissier** [comment]
> Hi @jforissier ,
> 
> Ah, ok - I wasn't aware of the requirement for binh->h to remain NULL if the binh->op->open() fails for any reason.

Yeah a comment in `core/include/kernel/ts_store.h` would be welcome I suppose.
 
> This was found in running code, I had made a typo in a UUID, and found OpTEE to crash at this point, but it would seem that the semantics of our own custom TA storage needs to change 

Good, that explains it. 

> (binh->h = NULL for any error code out of binh->op->open())

In fact the requirement on the output parameter `struct ts_store_handle **h` is a bit weaker than that: `*h` is assumed not to be modified when `res != TEE_SUCCESS`. Or to put it more simply: "written to only on success" which is a common thing to do. Since it is initialized to zero by `calloc()` in `ldelf_syscall_open_bin()`, that works.

> Thanks!
