### ISSUE TITLE
C++ client app

### ISSUE THREAD

**Issue by shirinebadi** [OP-TEE/optee_os#6833]
Hi, I have a C++ code that wants to invoke a TA. I couldn't find any sources to know if it is possible to do so, and if not, can my C++ program somehow call the related C function in the client app to communicate with the TA?

**Comment by jforissier** [comment]
Hello @shirinebadi,

Yes it is possible to call a TA from C++ code. There is no C++ API for the TEE client, so as you said, you need to use the C functions.
That being said I think the OP-TEE header files are lacking the `extern "C" { }` statements that are required to disable the C++ name mangling, so you will probably need to add them (pull request welcome!).

**Comment by shirinebadi** [comment]
Thanks @jforissier.
Actually, I'm having difficult time understanding how to make it work. I have an application written in C++. I'm adding it to the Qemu through buildroot. My TA and CA are in optee_examples directory. How can I include them in my application?

**Comment by jforissier** [comment]
See https://github.com/jforissier/optee_examples/commit/c477052c438ad8605d4df98fc67fe0d248103b0a.
```
Welcome to Buildroot, type root or test to login
buildroot login: test
$ optee_example_hello_world_cxx
Invoking TA to increment 42
TA incremented value to 43
$
```
