### ISSUE TITLE
OP-TEE License - BSD or GPL ?

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_os#6834]
Hi @jenswi-linaro @jforissier 

There has been recent addition of some files in optee_os code like:
```
./core/drivers/hisi_trng.c
./scripts/gen_compile_commands.py
```

These files have only `SPDX-License-Identifier: GPL-2.0 License`
But as far as I know, OP-TEE has BSD License.
If we combine files with GPL2.0 and BSD license in a project, that project will be distributed under GPL2.0 License

So can you please let me know if there is any recent change regarding the License of OP-TEE ?

Thanks
Sahil Malhotra

**Comment by jforissier** [comment]
Hello Sahil,

The OP-TEE license terms have not changed.

> `./scripts/gen_compile_commands.py`

This is a helper script that can be used to set up a development environment (see commit 8d541aee2e0f). It is not embedded in OP-TEE OS and not even used during the build. So I don't think it is an issue that it is GPL-2.0.

> `./core/drivers/hisi_trng.c`

That one however should not have been checked-in with a GPL license. That's an oversight during the review process. @bhLou would you mind submitting a pull request to change the license to `BSD-2-Clause`?

**Comment by sahilnxp** [comment]
Hi @jforissier 

Thanks a lot for this information.

There is one more file https://github.com/OP-TEE/optee_os/blob/master/core/include/dt-bindings/mfd/st%2Cstpmic1.h which has only GPL-2.0, but that is pretty old file. Can we take care of this also ?

This file https://github.com/OP-TEE/optee_test/blob/master/scripts/aes_gcm_test.py in optee-test also don't have any license, Should we put one here? If you want me to open one issue for OP-TEE test in optee_test repo, please let me know.

**Comment by jforissier** [comment]
> Hi @jforissier
> 
> Thanks a lot for this information.
> 
> There is one more file https://github.com/OP-TEE/optee_os/blob/master/core/include/dt-bindings/mfd/st%2Cstpmic1.h which has only GPL-2.0, but that is pretty old file. Can we take care of this also ?

@etienne-lms this is for you I suppose ;)

> This file https://github.com/OP-TEE/optee_test/blob/master/scripts/aes_gcm_test.py in optee-test also don't have any license, Should we put one here? If you want me to open one issue for OP-TEE test in optee_test repo, please let me know.

@omasse-linaro what license would be applicable?

**Comment by omasse-linaro** [comment]
Hi @jforissier 

> > This file https://github.com/OP-TEE/optee_test/blob/master/scripts/aes_gcm_test.py in optee-test also don't have any license, Should we put one here? If you want me to open one issue for OP-TEE test in optee_test repo, please let me know.
> 
> @omasse-linaro what license would be applicable?

Let's use copyright and license info as follow:
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2024, Linaro Limited
#

**Comment by jforissier** [comment]
> Hi @jforissier
> 
> > > This file https://github.com/OP-TEE/optee_test/blob/master/scripts/aes_gcm_test.py in optee-test also don't have any license, Should we put one here? If you want me to open one issue for OP-TEE test in optee_test repo, please let me know.
> > 
> > 
> > @omasse-linaro what license would be applicable?
> 
> Let's use copyright and license info as follow:
> 
> ```
> # SPDX-License-Identifier: BSD-2-Clause
> #
> # Copyright (c) 2024, Linaro Limited
> #
> ```

LGTM. Would you mind creating a PR?

**Comment by etienne-lms** [comment]
> > There is one more file https://github.com/OP-TEE/optee_os/blob/master/core/include/dt-bindings/mfd/st%2Cstpmic1.h which has only GPL-2.0, but that is pretty old file. Can we take care of this also ?
>
> @etienne-lms this is for you I suppose ;)

Indeed. I'll take care of that.

**Comment by sahilnxp** [comment]
Hi @jforissier @etienne-lms 

I see that one patch is merged in optee-test regarding this.
Any update on other parts in OP-TEE ?

**Comment by jbech-linaro** [comment]
> > `./scripts/gen_compile_commands.py`
> 
> This is a helper script that can be used to set up a development environment (see commit [8d541ae](https://github.com/OP-TEE/optee_os/commit/8d541aee2e0fe7242ec6fb57aabc7a04471b2237)). It is not embedded in OP-TEE OS and not even used during the build. So I don't think it is an issue that it is GPL-2.0.
> 
> >

Correct, I was even mentioning this in the pull request itself (https://github.com/OP-TEE/optee_os/pull/6387). So this one is not an issue.

**Comment by sahilnxp** [comment]
Thanks @jforissier for taking care of hisi_trng.c, but there is no reply from the file owner, how we will proceed in this case ?

Thanks @jbech-linaro for PR link, I got your point.

@etienne-lms Can you please help on the ./core/include/dt-bindings/mfd/st,stpmic1.h part ?

**Comment by jforissier** [comment]
> Thanks @jforissier for taking care of hisi_trng.c, but there is no reply from the file owner, how we will proceed in this case ?

In this case we'll just remove the file. In the meantime let me add another name to the re-licensing PR (the D06 maintainer).

**Comment by etienne-lms** [comment]
> @etienne-lms Can you please help on the ./core/include/dt-bindings/mfd/st,stpmic1.h part ?

Hi @sahilnxp. Yes, the change is currently under review in the LKML, patch v2 sent this morning:
https://lore.kernel.org/lkml/20240617092016.2958046-1-etienne.carriere@foss.st.com/
Once it's been acked, I've push updates in both U-Boot and OP-TEE OS.

**Comment by sahilnxp** [comment]
Thanks @jforissier and @etienne-lms for your quick response.

**Comment by etienne-lms** [comment]
FYI, the stpmic1 DT binding issue is fixed by https://github.com/OP-TEE/optee_os/pull/6917.

**Comment by sahilnxp** [comment]
@etienne-lms Thanks for taking care of this.

**Comment by sahilnxp** [comment]
Thanks @jforissier @etienne-lms @jbech-linaro for taking care of this.
