### ISSUE TITLE
Notify normal world TA's from static TA

### ISSUE THREAD

**Issue by Amit-Radur** [OP-TEE/optee_os#6838]
As I understand, pseudo TA (static TAs) runs in ARMv8 S-EL1 mode, which is the OS layer of the secure world. Running in this layer, a 
 pseudo TA cannot use the GlobalPlatform TEE Internal Core API, is there way to notify Normal world TA (NS-TA) from static TA (without NS-TA  requesting anything) ?

**Comment by jforissier** [comment]
Hi @Amit-Radur,


> As I understand, pseudo TA (static TAs) runs in ARMv8 S-EL1 mode, which is the OS layer of the secure world. Running in this layer, a pseudo TA cannot use the GlobalPlatform TEE Internal Core API, 

Correct

> is there way to notify Normal world TA (NS-TA) from static TA (without NS-TA requesting anything) ?

There is no such thing as a "Normal word TA" because the TA runs in Secure world. The answer to your question is yes, a PTA can simply invoke a TA.

**Comment by Amit-Radur** [comment]
@jforissier , Thanks for reply.

But one can't use GlobalPlatform TEE Internal Core API (from PTA aka static TA), then what are the methods for notifying any TA from PTA ?

**Comment by jforissier** [comment]
`TEE_InvokeTACommand()`
