### ISSUE TITLE
armv7sec.0: shm service not available

### ISSUE THREAD

**Issue by oliviermartin** [OP-TEE/optee_os#684]
I have tried the latest optee_os `1243cb51c` on Hikey board. When I start `tee-supplicant` I have got the error:

```
[  796.859951] armv7sec armv7sec.0: shm service not available: FFFFFFFF
[  796.866932] misc opteearmtz00: tee_get: opteearmtz00::start() failed, err=-22
ERR [1876] TEES:main:392: error opening [/dev/opteearmtz00]
```

The OPTEE Linux drivers starts well:

```
               TEE Core Framework initialization (ver 1:0.1)
[  644.311441] TEE armv7 Driver initialization
[  644.311911] tz_tee_probe: name="armv7sec", id=0, pdev_name="armv7sec.0"
[  644.311921] TEE core: Alloc the misc device "opteearmtz00" (id=0)
[  644.312542] TEE Core: Register the misc device "opteearmtz00" (id=0,minor=57)
```

OPTEE on the Trusted side seems to be initialized successfully.

I noticed this merged pull-request: "armtz: switch to use OPTEE MSG protocol" (source: https://github.com/OP-TEE/optee_linuxdriver/pull/43). So I also updated optee_linuxdriver.

Here is my configuration:

# optee_os:

```
commit 1243cb51ca265731086106cb7b0d89b3d5a446c9
Author: Jens Wiklander <jens.wiklander@linaro.org>
Date:   Tue Mar 1 19:37:21 2016 +0100
```

# optee_linuxdriver:

```
commit b62551902d89e2dab8186aeacc53e37fd17309ee
Author: Zoltan Kuscsik <zoltan.kuscsik@linaro.org>
Date:   Wed Mar 2 14:03:15 2016 +0100
```

**Comment by oliviermartin** [comment]
I have not updated ARM Trusted Firmware. I had a quick look through the OPTEE SPD and I have not seen any obvious reason the SPD is the issue as it registers a SMC range instead of registering some specific SMC IDs.

**Comment by jforissier** [comment]
You need to update ARM-TF to https://github.com/linaro-swg/arm-trusted-firmware branch: hikey_gendrv because commit 9d3b0ecf9ffa ("opteed: forward x4-x6 to OP-TEE") is required. It is likely the cause of the issue you are seeing.
Also, please make sure you run the latest optee_client from https://github.com/OP-TEE/optee_client branch: master, because db9c64d45818d ("tee-supplicant: add TEE_RPC_LOAD_TA2
") is required, too.

**Comment by oliviermartin** [comment]
Thanks Jérôme for all these info. I guess you know what you are speaking about. I will update all the components another day (I am a bit lazy to do it at the moment). I downgraded optee_os and optee_linuxdriver just before this API change and this configuration works.

I will close this issue for now.

**Comment by oliviermartin** [comment]
FYI, I was using ARM Trusted Firmware from: https://github.com/96boards/arm-trusted-firmware.git (branch `hikey`)
