### ISSUE TITLE
Secure Write Protection and writing  authenticated device configuration to RPMB 

### ISSUE THREAD

**Issue by mmo4** [OP-TEE/optee_os#6840]
Hi everyone. 

As described in the JEDEC Standard No. 84-B51, RPMB has an Authenticated Device Configuration area which controls the setting of secure write protection for partitions on eMMC. 

I want to be able to set the parameters inside that area using OP-TEE. As I read the source, these are the defined request and response  message types within OP-TEE:
```
#define RPMB_MSG_TYPE_REQ_AUTH_KEY_PROGRAM          0x0001
#define RPMB_MSG_TYPE_REQ_WRITE_COUNTER_VAL_READ    0x0002
#define RPMB_MSG_TYPE_REQ_AUTH_DATA_WRITE           0x0003
#define RPMB_MSG_TYPE_REQ_AUTH_DATA_READ            0x0004
#define RPMB_MSG_TYPE_REQ_RESULT_READ               0x0005
#define RPMB_MSG_TYPE_RESP_AUTH_KEY_PROGRAM         0x0100
#define RPMB_MSG_TYPE_RESP_WRITE_COUNTER_VAL_READ   0x0200
#define RPMB_MSG_TYPE_RESP_AUTH_DATA_WRITE          0x0300
#define RPMB_MSG_TYPE_RESP_AUTH_DATA_READ           0x0400
```

in the JEDEC standard message types for authenticated device configuration read/write are described as follows:
Authenticated Device Configuration write request: 0x0006
Authenticated Device Configuration read request: 0x0007

I searched online but couldn't find anything related to setting Authenticated Device Configuration on RPMB. Also saw the issue #4209 , and @jenswi-linaro mentioned they are  not supported by OP-TEE. 

How can I achieve protecting eMMC partitions using OP-TEE or any other methods/tools?

Thanks.

**Comment by jenswi-linaro** [comment]
If this is something you intend to do during the production phase of the device, have you tried https://docs.kernel.org/driver-api/mmc/mmc-tools.html?

If it's done after manufacturing outside of the factory then I believe it must be done by OP-TEE since the RPMB key mustn't be known by anyone after this phase.

**Comment by mmo4** [comment]
Hi, thanks for reply.

I need to be able to enable/disable write protection on the devices in the field since it will be part of the remote update process. Therefore I need to apply this configuration using OP-TEE. Required message types(defined in JEDEC) for secure write protection is not supported by OP-TEE.  Need guidance on how to be able to set secure write protection configuration using OP-TEE.
