### ISSUE TITLE
Inquiry on how to use subkey.

### ISSUE THREAD

**Issue by ydonghyuk** [OP-TEE/optee_os#6842]
I'm trying to use subkey, but I have a few questions.

1) How to change the root key (default_ta.pem) (or is there a set rule for the algorithm used)

2) Meaning of --name-size and --name among options when creating subkey (sign_encrypt.py)
     2-1) Specifically, I would like to know the difference between identify subkey and normal subkey.
     2-2) I think identify subkey will be sufficient in our environment.

I have a lot of questions, but thank you in advance for your help.

**Comment by jenswi-linaro** [comment]
> I'm trying to use subkey, but I have a few questions.
> 
> 1. How to change the root key (default_ta.pem) (or is there a set rule for the algorithm used)

You can override TA_SIGN_KEY to point to another key.

> 2. Meaning of --name-size and --name among options when creating subkey (sign_encrypt.py)
>    2-1) Specifically, I would like to know the difference between identify subkey and normal subkey.
>    2-2) I think identify subkey will be sufficient in our environment.

Have you checked out https://www.linaro.org/blog/subkeys-in-op-tee-part-2/ ?

You typically use an identity subkey if the TA needs a specific UUID, the downside is that you'll need one identity subkey for each of the TAs with specific UUIDs so it might take a bit more effort to maintain.

**Comment by ydonghyuk** [comment]
I am already checking the contents of the link below.
https://www.linaro.org/blog/subkeys-in-op-tee-part-2

However, I inquired because there was no process for creating a root key or using it to create a sub key.
I am creating a root key and sub key as shown below. Am I using them correctly?

// root key
``
$ openssl genrsa -out new_key.pem 2048
``

//optee_os/mk/config.mk
```
diff --git a/mk/config.mk b/mk/config.mk
index 3b3ccec..f22c79c 100644
--- a/mk/config.mk
+++ b/mk/config.mk
@@ -219,7 +219,7 @@ _CFG_WITH_SECURE_STORAGE := $(call cfg-one-enabled,CFG_REE_FS CFG_RPMB_FS)
  # When performing external HSM signing for TA's TA_SIGN_KEY can be set to dummy
  # key and then set TA_PUBLIC_KEY to match public key from the HSM.
  # TA_PUBLIC_KEY's public key will be embedded into OP-TEE OS.
-TA_SIGN_KEY ?= keys/default_ta.pem
+TA_SIGN_KEY ?= keys/new_key.pem
  TA_PUBLIC_KEY ?= $(TA_SIGN_KEY)
```

// sub key
``
$ openssl genrsa -out sub_key.pem 2048
$ ./sign_encrypt.py sign-subkey --in sub_key.pem --uuid [uuid] --key new_key.pem --out sub_key --name-size 0
``

// TA Makefile
```
+TA_SIGN_KEY = ../../conf/qemu_v8/subkey/km_subkey_qemu_v8.pem
+TA_SUBKEY_BIN = ../../conf/qemu_v8/subkeys/subkey/km_subkey_qemu_v8.bin
+TA_SUBKEY_ARGS = --subkey $(TA_SUBKEY_BIN)
+TA_SUBKEY_DEPS = $(TA_SIGN_KEY)
```

**Comment by jenswi-linaro** [comment]
There's another example available at https://raw.githubusercontent.com/OP-TEE/optee_test/master/ta/subkey_notes.txt

**Comment by ydonghyuk** [comment]
@jenswi-linaro 
Thanks for your guide.
I will check it.

Sorry, but I have two questions.

One/
When changing/creating root key and sub key,
Is it okay if I use an RSA key size of 2048 or higher?
I would like to inquire about any rules regarding the size of the root/sub key.

2/ 
Is TA Signing possible with a first level subkey (top subkey)?

Thank you in advance for your help.

**Comment by jenswi-linaro** [comment]
> 1/ When changing/creating root key and sub key, Is it okay if I use an RSA key size of 2048 or higher? I would like to inquire about any rules regarding the size of the root/sub key.

No subkey specific rules, use what you need.

> 
> 2/ Is TA Signing possible with a first level subkey (top subkey)?

Yes

**Comment by jenswi-linaro** [comment]
The risk is supposed to be reduced since fewer people need access to the private root key.

**Comment by ydonghyuk** [comment]
thanks for help
