### ISSUE TITLE
Loading Large TA  - TEEC_Opensession fails with code 0xffff000c

### ISSUE THREAD

**Issue by pluto-llf** [OP-TEE/optee_os#6847]
**Description:**
I'm encountering an issue while attempting to load a Trusted Application (TA) with a size of approximately 59 MB. In the Normal World, the error message I receive is "TEEC_Opensession failed with code 0xffff000c origin 0x3".

In an attempt to resolve this, I referred to issue #5469 and adjusted the following configurations in `optee_os/mk/config.mk`:

```Makefile
CFG_CORE_DYN_SHM ?= y
CFG_CORE_RESERVED_SHM ?= y
CFG_CORE_HEAP_SIZE ?= 524288
```
Additionally, I modified values in `optee_os/core/arch/arm/plat-vexpress/conf.mk`:

```Makefile
CFG_SHMEM_SIZE  ?= 0x00C00000
CFG_TEE_RAM_VA_SIZE ?= 0x01400000
```
Despite these changes, the OpenSession operation still fails.

My `user_ta_header_defines.h` configuration is as follows:

```C
#define TA_STACK_SIZE            (2 * 1024 * 1024)
#define TA_DATA_SIZE             (10 * 1024 * 1024)
```
**Error Log:**

```Log
D/TC:? 0 entry_open_session:372 ae757a2c-9e88-4b4a-909b-3addadaabba2
D/TC:? 0 entry_open_session:373 00000000-0000-0000-0000-000000000000
D/TC:? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA ae757a2c-9e88-4b4a-909b-3addadaabba2
D/TC:? 0 ldelf_load_ldelf:96 ldelf load address 0x40006000
D/LD:  ldelf:134 Loading TS ae757a2c-9e88-4b4a-909b-3addadaabba2
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ae757a2c-9e88-4b4a-909b-3addadaabba2 (early TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ae757a2c-9e88-4b4a-909b-3addadaabba2 (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ae757a2c-9e88-4b4a-909b-3addadaabba2 (REE)
D/TC:0 0 core_mmu_xlat_table_alloc:534 xlat tables used 13 / 16
D/TC:0 0 core_mmu_xlat_table_alloc:534 xlat tables used 14 / 16
D/TC:? 0 ldelf_syscall_open_bin:146 res=0
D/TC:? 0 user_vm_region_split_align:2051 r0::va:0x40081000 offset:0x0 size:0xb9000
D/TC:? 0 user_vm_region_split_align:2059 r1::va:0x4013a000 offset:0x2b9000 size:0xc6000
D/TC:? 0 user_vm_region_split_align:2068 r2::va:0x40200000 offset:0xb9000 size:0x200000
D/TC:? 0 user_vm_region_split_align:2077 r3::va:0x40400000 offset:0x37f000 size:0x9c000
D/TC:? 0 user_vm_region_split_align:2084 r::va:0x40081000 offset:0x0 size:0x41b000
D/TC:? 0 core_mmu_populate_user_map:2110 large_page_size:0x200000
D/TC:? 0 set_pg_region:1592 va:0x40200000 pa:0xf600000 attr:0x3831 size:0x200000
D/TC:? 0 set_pg_region:1593 large page handle!
D/TC:? 0 core_mmu_populate_user_map:2110 large_page_size:0x200000
D/TC:? 0 set_pg_region:1592 va:0x40200000 pa:0xf600000 attr:0x3a91 size:0x200000
D/TC:? 0 set_pg_region:1593 large page handle!
E/LD:  populate_segments:883 sys_map_zi
E/TC:? 0 ldelf_init_with_ldelf:131 ldelf failed with res: 0xffff000c
D/TC:? 0 tee_ta_open_session:735 init session failed 0xffff000c
```
**Questions:**

1. **Resolution:** How can I successfully load this large TA without encountering the OpenSession failure? Is there any other configuration or approach I should consider?

2. **Memory Usage During OpenSession:** Could you explain which memory is utilized during the OpenSession process? Specifically, are there limitations on the size that can be allocated using TEEC_RegisterSharedMemory() and TEEC_AllocateSharedMemory()? It seems they can allocate beyond CFG_SHMEM_SIZE; what parameters govern their allocation limits?
---
Any guidance or clarification on addressing this OpenSession failure and understanding the memory management during this operation would be greatly appreciated.

**Comment by jforissier** [comment]
Hi @pluto-llf,

> 2\. **Memory Usage During OpenSession:** Could you explain which memory is utilized during the OpenSession process? Specifically, are there limitations on the size that can be allocated using TEEC_RegisterSharedMemory() and TEEC_AllocateSharedMemory()? It seems they can allocate beyond CFG_SHMEM_SIZE; what parameters govern their allocation limits?

When `CFG_CORE_DYN_SHM=y` the TEE client library will preferably allocate "dynamic shared memory", in other words, memory that is NOT in the reserved shared memory pool but somewhere else in the CA memory space. So `CFG_SHMEM_SIZE` (the size of the reserved pool) does not matter. In fact in general when `CFG_CORE_DYN_SHM=y` there is no need to enable `CFG_CORE_RESERVED_SHM`.

**Comment by jenswi-linaro** [comment]
The qemu_armv8a flavor has only 15 meg (or is it 13?) of memory usable for TAs. See also the `VIRT_SECURE_MEM` line in `hw/arm/virt.c` in the QEMU source tree.

**Comment by pluto-llf** [comment]
Thanks for your responses and insights. I know the reason why modifying the `CFG_SHMEM_SIZE` item before did not work.

I attempted to increase the `VIRT_SECURE_MEM` value in `qemu/hw/arm/virt.c` to accommodate my larger TA, but unfortunately, I'm still encountering the 0xffff000c error during the TA loading process, and at times, some similar errors occur like this:
```
D/TC:? 0 entry_open_session:372 ae757a2c-9e88-4b4a-909b-3addadaabba2
D/TC:? 0 entry_open_session:373 00000000-0000-0000-0000-000000000000
D/TC:? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA ae757a2c-9e88-4b4a-909b-3addadaabba2
D/TC:? 0 ldelf_load_ldelf:96 ldelf load address 0x40006000
D/LD:  ldelf:134 Loading TS ae757a2c-9e88-4b4a-909b-3addadaabba2
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ae757a2c-9e88-4b4a-909b-3addadaabba2 (early TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ae757a2c-9e88-4b4a-909b-3addadaabba2 (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ae757a2c-9e88-4b4a-909b-3addadaabba2 (REE)
E/TC:? 0 get_rpc_alloc_res:645 RPC allocation failed. Non-secure world result: ret=0 ret_origin= 0x2
x
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff000c
E/LD:  init_elf:486 sys_open_ta_bin(ae757a2c-9e88-4b4a-909b-3addadaabba2)
E/TC:? 0 ldelf_init_with_ldelf:131 ldelf failed with res: 0xffff000c
D/TC:? 0 tee_ta_open_session:735 init session failed 0xffff000c
```
I have some follow-up inquiries:
1. Are the sizes of TA and shared memory included in `VIRT_SECURE_MEM`?
2. With respect to the specific error messages, particularly the `0xffff000c` code and the note regarding "RPC allocation failed," could you offer targeted troubleshooting advice or insights? These errors might indicate resource constraints or misconfigurations specific to handling substantial TA sizes.

Your continued assistance is invaluable, and I look forward to any further guidance you can provide.

**Comment by jenswi-linaro** [comment]
> * Are the sizes of TA and shared memory included in `VIRT_SECURE_MEM`?

No, only TA and OP-TEE Core memory.

> * With respect to the specific error messages, particularly the `0xffff000c` code and the note regarding "RPC allocation failed," could you offer targeted troubleshooting advice or insights? These errors might indicate resource constraints or misconfigurations specific to handling substantial TA sizes.

You have the location in the code where the error is detected. To pinpoint it further you need to add a few more temporary debug prints. It's a rather large chunk so the error might be at an unusual place. Perhaps it's `SHM_VASPACE_SIZE` that needs to be increased.

**Comment by pluto-llf** [comment]
I've attempted to increase `SHM_VASPACE_SIZE`, but this adjustment did not yield the desired effect.

Upon increasing `CFG_CORE_HEAP_SIZE`, I observe that more shared memory becomes available. However, I'm uncertain about the usability of this additional memory. What's the connection between `CFG_CORE_HEAP_SIZE` and the overall memory allocation? 

Furthermore, I'd like to inquire about the role of memory obtained via `TEEC_RegisterSharedMemory()/TEEC_AllocateSharedMemory()`. Are these allocations intended specifically for data transfers between CA and TA post-TEEC_OpenSession, or do they also play a part in the TEEC_OpenSession process itself?

**Comment by jenswi-linaro** [comment]
`CFG_CORE_HEAP_SIZE` is used to allocate all kinds of OP-TEE core data structures, among others data structures needed to handle shared memory. It's essentially used for the OP-TEE counterpart of `kmalloc()` in the Linux kernel.

`TEEC_RegisterSharedMemory()/TEEC_AllocateSharedMemory()` can be used before `TEEC_OpenSession()`.

**Comment by pluto-llf** [comment]
> `TEEC_RegisterSharedMemory()/TEEC_AllocateSharedMemory()` can be used before `TEEC_OpenSession()`.

Does OpenSession utilize shared memory to load TA?
Can the content registered and allocated during Register and Allocate be applied to loading TA via OpenSession?

**Comment by JolyonJian** [comment]
@pluto-llf  I made a successful attempt on qemu_v8. The modifications I made are as follows: 
1. In `optee_os/mk/config.mk`
```
CFG_CORE_HEAP_SIZE ?= 524288
```
2. In `optee_os/core/arch/arm/plat-vexpress/conf.mk`
```
CFG_TZDRAM_SIZE  ?= 0x01400000 # 20MB
CFG_SHMEM_SIZE  ?= 0x00400000 # 4MB
```
3. In `qemu/hw/arm/virt.c`
```
[VIRT_SECURE_MEM] =         { 0x0e000000, 0x01400000 },
```
4. In `optee_os/core/arch/arm/include/mm/pgt_cache.h`
```
// #if CFG_NUM_THREADS < 2
// #define PGT_CACHE_SIZE	4
// #else
// #define PGT_CACHE_SIZE	ROUNDUP(CFG_NUM_THREADS * 2, PGT_NUM_PGT_PER_PAGE)
// #endif
#define PGT_CACHE_SIZE	12
```
With these modifications, I successfully ran a TA with large memory requirements:
```
#define TA_STACK_SIZE			(2 * 1024 * 1024)
#define TA_DATA_SIZE			(10 * 1024 * 1024)
```

In addition, on the Raspberry Pi 3B+ development board, it is easier to expand the secure memory. 
Only need to modify `CFG_TZDRAM_SIZE`, `CFG_SHMEM_SIZE`, and `PGT_CACHE_SIZE`.

**Comment by pluto-llf** [comment]
> Have you read the documentation at https://optee.readthedocs.io/en/latest/ in particular https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#loading-ree-fs-ta?

I read the documentation and did some debugging. I found that in `optee_os/core/tee/entry_std.c`, there is the following code in `__tee_entry_std()`:
```
#ifndef CFG_CORE_FFA
#ifdef CFG_CORE_DYN_SHM
	case OPTEE_MSG_CMD_REGISTER_SHM:
		register_shm(arg, num_params);
		break;
	case OPTEE_MSG_CMD_UNREGISTER_SHM:
		unregister_shm(arg, num_params);
		break;
#endif
#endif
```
When I run the `hello_world` example, it jumps to `register_shm()`. But when I run my TA application, it does not jump or enter the case statement.

Additionally, in an attempt to gain deeper insight, I attempted to add debugging print statements within the tee-supplicant source code. Unfortunately, none of these print statements are executed. I'm not quite sure how to proceed, if you have any other experience or suggestions I would be grateful.

**Comment by pluto-llf** [comment]
@JolyonJian @jenswi-linaro  my setup within `user_ta_header_defines.h`, I'm able to successfully run with the following configuration when my uuid.ta file size is relatively small:
```
#define TA_STACK_SIZE			(2 * 1024 * 1024)
#define TA_DATA_SIZE			(10 * 1024 * 1024)
```
However, when the uuid.ta binary grows significantly (to around 59 MB), the execution fails.
In an attempt to resolve this issue, I made several adjustments:
1. In `optee_os/core/arch/arm/plat-vexpress/config.mk` :
```
CFG_TZDRAM_SIZE  	?= 0x09600000 # 150M
CFG_TEE_RAM_VA_SIZE ?= 0x01E00000 # 30M
```
2. In `optee_os/mk/config.mk`:
```
CFG_CORE_HEAP_SIZE ?= 524288
CFG_CORE_DYN_SHM ?= y
```
3. In `qemu/hw/arm/virt.c`:
```
[VIRT_SECURE_MEM] =         { 0x0e000000, 0x03C00000 }
```
4. In `optee_os/core/arch/arm/mm/core_mmu_lape.c`:(The reason for modifying this is thar Trusted World prompted me `core_mmu_xlat_table_alloc:527 16 xlat tables exhausted`)
```
#define MAX_XLAT_TABLES		(64 + \
                               XLAT_TABLE_VIRTUALIZATION_EXTRA + \
                               XLAT_TABLE_ASLR_EXTRA + \
                               XLAT_TABLE_USER_EXTRA)
```
After applying these modifications, the initial error failed with code `0xffff000c` no longer appears, but instead, I encounter a different error sequence during the TA loading process:
```
D/TC:? 0 entry_open_session:372 ae43c032-6f8e-4050-a140-a242f027b66e
D/TC:? 0 entry_open_session:373 00000000-0000-0000-0000-000000000000
D/TC:? 0 tee_ta_init_pseudo_ta_session:296 Lookup pseudo TA ae43c032-6f8e-4050-a140-a242f027b66e
D/TC:? 0 ldelf_load_ldelf:102 ldelf load address 0x40006000
D/LD:  ldelf:134 Loading TS ae43c032-6f8e-4050-a140-a242f027b66e
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ae43c032-6f8e-4050-a140-a242f027b66e (early TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ae43c032-6f8e-4050-a140-a242f027b66e (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF ae43c032-6f8e-4050-a140-a242f027b66e (REE)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0
E/LD:  check_range:233 .dynstr/STRTAB 0x0 out of range
E/TC:? 0 ldelf_init_with_ldelf:138 ldelf failed with res: 0xffff0005
D/TC:? 0 tee_ta_open_session:742 init session failed 0xffff0005
```
Are my changes wrong? Or there any other modification methods?

**Comment by etienne-lms** [comment]
FYI, indeed `PGT_CACHE_SIZE` needs to be tuned for a platform to host very large TAs, as reported by https://github.com/OP-TEE/optee_os/issues/6847#issuecomment-2132736069.  I created https://github.com/OP-TEE/optee_os/pull/6908 to propose a generic solution.
Regarding `MAX_XLAT_TABLES`, it also needs to be tuned: platform currently can do that through their `platform_config.h` file.
