### ISSUE TITLE
Can i use gcc "math" library in TA ?

### ISSUE THREAD

**Issue by louisyang1977** [OP-TEE/optee_os#685]
Hi,
We try to port the current function to optee_os as TA and this function uses gcc math library (link option -lm, include file math.h), is it possible to use gcc standard math library in optee_os ??

Thanks !!

**Comment by jenswi-linaro** [comment]
Hi,

This isn't supported. I wouldn't be surprised if it would appear to just work especially if you link with a bare metal version of the lib. But be prepared that some corner cases may not work.

Regards,
Jens

**Comment by louisyang1977** [comment]
Hi Jenswi,
Thanks for your quick response !!
