### ISSUE TITLE
Access to SPI NOR and eMMC block layer

### ISSUE THREAD

**Issue by awilliams-marvell** [OP-TEE/optee_os#6855]
I am trying to migrate our firmware update functionality to a new SoC, however at least part of this must be done in secure memory since it requires access to a hardware security module to verify digital signatures. The question is, is there some way I can use Optee to use the tee-supplicant to write to the eMMC and/or SPI NOR? When I look at the supplicant I don't see a way to do this unless I am missing something. Is there a way to write extensions for this or would I need to make a custom supplicant with this functionality. My other alternative would be to do everything in user space except for the calls to verify digital signatures.

We do not use the secure eMMC area for booting, but use space near the beginning of the device after the partition table.

**Comment by ivila** [comment]
Are you looking for [plugin](https://github.com/linaro-swg/optee_examples/tree/master/plugins)
actually tee-supplicant support loading plugin inside REE, and your ta can call tee_invoke_supp_plugin method inside TEE.
