### ISSUE TITLE
Using non-FF-A OP-TEE from Linux with FF-A support

### ISSUE THREAD

**Issue by bklintefjord** [OP-TEE/optee_os#6858]
## Disclaimer

I am not sure if this is the right place to raise my question, since it is maybe more related to the Linux Kernel (OP)TEE and FF-A modules.

## Background

I wanted to test OP-TEE with FF-A and Xen. I am working with a Linux kernel (6.6.13) that does not have FF-A enabled. To not risk causing any trouble for others, FF-A support was added as a kernel module (in 6.6.15):

```
CONFIG_ARM_FFA_SMCCC=y
CONFIG_ARM_FFA_TRANSPORT=m
```

Furthermore, both of the kernels have:

```
CONFIG_TEE=m
CONFIG_OPTEE=m
# CONFIG_OPTEE_INSECURE_LOAD_IMAGE is not set
```

## Test procedure

With 6.6.15, OP-TEE with FF-A and Xen works. However, OP-TEE without FF-A no longer works. I test with the following:

```bash
repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml -b 4.2.0
cd build
make -j2 toolchains
cat >> kconfigs/u-boot_qemu_v8.conf <<-EOF
CONFIG_CMD_SYSBOOT=y
CONFIG_BOOTCOMMAND="setenv kernel_addr_r 0x42200000 && setenv ramdisk_addr_r 0x45000000 && sysboot virtio 0:1 any ${scriptaddr} /extlinux/extlinux.conf"
EOF
make -j$(nproc) qemu arm-tf
sed -i -e '/^QEMU_BASE_ARGS += -\(initrd\|kernel\|append\)/d' Makefile
export QEMU_EXTRA_ARGS="-drive if=none,file=linux.img,format=raw,id=hd1 -device virtio-blk-device,drive=hd1"
cp /path/to/linux.img ../out/bin/linux.img
make run-only
```

The linux.img image contains both of the kernels: 6.6.13 without the above FF-A configs, and 6.6.15 with the above FF-A configs.

## Result

If I use 6.6.13, OP-TEE works as expected, I can run xtest and it passes. If I use 6.6.15, the optee module fails to load:

```bash
$ sudo modprobe optee
[   65.007702] ARM FF-A: FFA_VERSION returned not supported
modprobe: ERROR: could not insert 'optee': Operation not supported
```

This error comes from (reference to the Linux kernel source code) `drivers/firmware/arm_ffa/driver.c:ffa_version_check`:

```c
    invoke_ffa_fn((ffa_value_t){
              .a0 = FFA_VERSION, .a1 = FFA_DRIVER_VERSION,
              }, &ver);

    if (ver.a0 == FFA_RET_NOT_SUPPORTED) {
        pr_info("FFA_VERSION returned not supported\n");
        return -EOPNOTSUPP;
    }
```

The function ffa_version_check is called from `ffa_init()`, via `subsys_initcall(ffa_init);`

## Analysis

So my interpretation is that since the 6.6.15 kernel has CONFIG_ARM_FFA_TRANSPORT=m, then the optee kernel module will depend on the arm_ffa module, since the file `drivers/tee/optee/ffa_abi.c` contains:

```c
int optee_ffa_abi_register(void)
{
    if (IS_REACHABLE(CONFIG_ARM_FFA_TRANSPORT))
        return ffa_register(&optee_ffa_driver);
    else
        return -EOPNOTSUPP;
}
```

Where `ffa_register` is defined as `ffa_driver_register(driver, THIS_MODULE, KBUILD_MODNAME)` which in turn is defined in the arm_ffa module (when it is available).

So the problem is not that `optee_ffa_abi_register` would return an error, but that the arm_ffa module fails to load. This can be seen also be trying to load the arm_ffa module directly, which produces the same error:

```bash
$ sudo modprobe arm_ffa
[   70.601992] ARM FF-A: FFA_VERSION returned not supported
modprobe: ERROR: could not insert 'ffa_module': Operation not supported
```

## Questions

1. Am I doing this the right way, or do I get this error because I have done something wrong in my setup/configuration? I have not tested `CONFIG_ARM_FFA_TRANSPORT=y`.
1. Is this known/expected/wanted behavior?
1. Is there a way to have a Linux kernel that supports both non-FF-A OP-TEE and FF-A OP-TEE at the same time? The way I interpret the code in the optee kernel module, it seems to be designed to use whatever transport is available, meaning that it would have worked if not the arm_ffa kernel module would block the optee kernel module from loading.

**Comment by jenswi-linaro** [comment]
I expect modules to work, but I haven't tested it much so perhaps something has slipped.
I usually compile all FF-A support into the kernel and use the same kernel for FF-A and non-FF-A testing. The probing takes care of selecting the right drivers. To rule out module problems you could try the same.
Regarding `FFA_VERSION`, the easiest is to start with all components supporting version 1.1.

**Comment by bklintefjord** [comment]
I recompiled the FF-A-enabled kernel with

```
CONFIG_ARM_FFA_TRANSPORT=y
```

But leaving the tee and optee modules as "m". With this change, the optee module is loaded without issue, and xtest passes.

I still find it strange/confusing in a way that the arm_ffa module cannot be loaded, but when it is built-in OP-TEE works. Especially confusing when OP-TEE is not using FF-A anyway (in this setup).

So the idea we had, "compile arm_ffa as a module to not break anything" turned out to be the reverse. By compiling it as a module the non-FF-A use case stopped working, but if we instead have it built in, we do not seem to break anything.

Thanks for the help, @jenswi-linaro.

**Comment by jenswi-linaro** [comment]
> I still find it strange/confusing in a way that the arm_ffa module cannot be loaded, but when it is built-in OP-TEE works. Especially confusing when OP-TEE is not using FF-A anyway (in this setup).

I agree, something is not right. The OP-TEE module has two drivers where only the FF-A based driver needs FF-A. I'm not so keen on splitting the OP-TEE module, I'd like to know if there's a way of allowing the OP-TEE module to be loaded even if the FF-A module has failed to load.

**Comment by bklintefjord** [comment]
I raised the question on the [linux-arm-kernel mailing list](https://lists.infradead.org/pipermail/linux-arm-kernel/2024-May/930223.html), so lets see if someone there has some suggestion or thought about it.
