### ISSUE TITLE
ArmV8interrupt handling

### ISSUE THREAD

**Issue by ericwu0083** [OP-TEE/optee_os#686]
Hi,

I read the document:
https://github.com/OP-TEE/optee_os/blob/master/documentation/interrupt_handling.md

and I am wondering if masking/unmasking IRQ or FIQ were implemented in BL31 instead of Secure Monitor code of OPTEE OS  at ArmV8 architecture?

Thanks!

**Comment by murasesyuka** [comment]
I think, Only ARM-Trusted-Firemware not supported ARMv7. Maybe...

**Comment by jbech-linaro** [comment]
Quite late answer, in v8, ARM-TF is also part of the IRQ/FIQ routing, but on v7 there are no ARM-TF, hence everything there is taken care of in OP-TEE itself.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
