### ISSUE TITLE
A question about configuration for optee crypto

### ISSUE THREAD

**Issue by sungkeunsong** [OP-TEE/optee_os#6862]
Hi experts,

I have a question about OPTEE crypto
How can I configure the following? is it possible?
symmetric algorithm and hashing : use ARM CE
asymmetric algorithm : use SoC HW engine

Thanks

**Comment by etienne-lms** [comment]
Hello. Yes you can. Your platform needs to register drvcrypt driver(s) for the expected asymm algo(s), and enable `CFG_CRYPTO_WITH_CE=y` to leverage ARM CE (`CFG_CRYPTO_xxx_ARM_CE`).
