### ISSUE TITLE
How to read hardware registers from TA

### ISSUE THREAD

**Issue by arunlalkm-intel** [OP-TEE/optee_os#6903]
My use case is that I want to read chip ID in TA. 

Just like in Linux we read using /dev/mem is there a way to read hardware registers from TA?

**Comment by ivila** [comment]
I think it depends on the chip provider, for example, if you are using rockchip, you can check the [rockchip_cpuinfo_probe](https://github.com/rockchip-linux/kernel/blob/9ed2be4b9c001ca8006cb4c72928c09927c44f89/drivers/soc/rockchip/rockchip-cpuinfo.c#L27) method, it use dts to find the register, and read the information from efuse.

**Comment by jenswi-linaro** [comment]
The short answer is, no. But if you need it anyway you must do it via pseudo TA. Have you considered `PTA_SYSTEM_DERIVE_TA_UNIQUE_KEY` from the system PTA?

**Comment by arunlalkm-intel** [comment]
Thanks for suggestions. 
I am using PTA_SYSTEM_DERIVE_TA_UNIQUE_KEY but that gives me only HUK based key.

**Comment by jenswi-linaro** [comment]
A pseudo-TA for chip ID is your only option then. If the chip ID is sensitive you'll need to add some filtering so only the expected TAs are allowed to get hold of it.

**Comment by arunlalkm-intel** [comment]
I am unfamiliar with pseudo-TA. It will be helpful if you can give bit more details or point me to an example.

**Comment by jenswi-linaro** [comment]
https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#pseudo-trusted-applications
