### ISSUE TITLE
Does current OPTEE OS code support RISC-V 32?

### ISSUE THREAD

**Issue by ddb2100** [OP-TEE/optee_os#6905]
I am trying to build OPTEE OS for RISC-V 32. But it reports some error. For example, 

- core/arch/risc/kernel/spinlock.S uses "addiw" which is only valid for RV64
- core/arch/riscv/kernel/asm-defines.c uses "offsetof(struct thread_ctx, kern_sp)" but kern_sp is member for thread_ctx only for RV64 as defined in core/include/kernel/thread_private.h.

Seems to me that current OPTEE OS only supports RISC-V 64, not RISC-V 32, is that the case? Thank you.

**Comment by gagachang** [comment]
> Seems to me that current OPTEE OS only supports RISC-V 64, not RISC-V 32, is that the case? 

Yes, currently only RV64 is supported.

May I know why you need RV32 OP-TEE OS ?
Which non-secure OS do you use? RV32 Linux kernel ?
