### ISSUE TITLE
Configuring the Linux kernel so that it recognises OP-TEE

### ISSUE THREAD

**Issue by huntc** [OP-TEE/optee_os#6910]
Hi, I'm attempting to configure OP-TEE for my custom Microchip SAMA5D27-WLSOM1 board.

I see some other questions relating to OP-TEE and the Microchip boards, but a difference here is that `at91bootstrap3` launches the Linux kernel directly i.e. there is no u-boot involved.

I’m able to use buildroot to configure and build OP-TEE such that at91bootstrap3 is able to invoke it. But I’m unsure what to configure with the Linux kernel. The Microchip documentation doesn’t appear to have a recipe for this, only some examples for other boards.

Here are some log file snippets:

```
AT91Bootstrap 4.0.6 (2024-06-22 23:47:29)

SD/MMC: Image: Read file zImage to 0x26f00000
MMC: ADMA supported
SD: Card Capacity: High or Extended
SD: Specification Version 3.0X
SD/MMC: dt blob: Read file sama5d27_wlsom1_cuprous_gw.dtb to 0x21000000

KERNEL: Booting zImage ...
DT: Using device tree in place at 0x21000000

KERNEL: Starting linux kernel ..., machid: 0xffffffff

SD/MMC: Done to load image
SD/MMC: Image: Read file tee.bin to 0x20000000
Starting OP-TEE, Run at 0x20000000, Non-secure entry at 0x26f00000
…
I/TC: Embedded DTB found
I/TC: OP-TEE version: Unknown_4.2 (gcc version 13.2.1 20231009 (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7))) #1 Sat Jun 22 13:01:44 UTC 2024 arm
I/TC: WARNING: This OP-TEE configuration might be insecure!
I/TC: WARNING: Please check https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html
I/TC: Primary CPU initializing
...
I/TC: Primary CPU switching to normal world boot
```

…and then that’s it i.e. the kernel doesn’t appear to boot. I have a working buildroot config without OP-TEE.

I have enabled kernel support for OP-TEE, but I'm wondering what else must be done. I'm suspecting that something device-tree related may need to be done.

Thanks for any help or pointers.

**Comment by jenswi-linaro** [comment]
So you load both the kernel and OP-TEE using AT91Bootstrap, and when OP-TEE exits to the normal world it enters the kernel directly instead of a normal world boot loader? You must make sure that r0-r3 holds the values needed by the kernel. This is something that a bootloader normally prepares, but now AT91Bootstrap must tell OP-TEE these values. Compare with that `core/arch/arm/plat-ti/main.c` does with `struct plat_nsec_ctx`.

**Comment by huntc** [comment]
At91bootstrap normally invokes the kernel for me directly instead of invoking uboot. Are you saying I must do something to op-tee so that it can invoke the kernel?

**Comment by jenswi-linaro** [comment]
Yes, and preferably in a way that OP-TEE only passes on values received from the loader.
@nodeax, do you have any advice?

**Comment by nodeax** [comment]
I have not tried op-tee without u-boot. I don't have any advice off the top of my head but I will try dig into the at91bootstrap hand-off code and get back later this week.

@clementleger for possible suggestions.

**Comment by huntc** [comment]
I've had an initial look at at91bootstrap and it does appear to set up r0, r1 and r2, which I think is the requirement. This appears to be the relevant bit of code: https://github.com/linux4sam/at91bootstrap/blob/e240bd43c149ab868741d1728af2f5973d2a6735/driver/load_kernel.c#L457-L472. The `optee_init_nw_params` structure is set up with r0, r1 and r2, and then used later by `optee_load`: https://github.com/linux4sam/at91bootstrap/blob/e240bd43c149ab868741d1728af2f5973d2a6735/main.c#L145-L148. `optee_load` appears to set up the registers and then jump into OP-TEE.

**Comment by huntc** [comment]
After spending a few hours on this today, I'm of the opinion that OP-TEE must be informed to pass on r0, r1 and r2, and that this isn't a requirement for when invoking U-Boot. As it is valid for at91bootstrap to bypass U-Boot then I think this should be supported by OP-TEE. I'd like to suggest a PR for this with some further guidance. However, at this stage, I'm not sure where these registers would require setting up, but I'm thinking it'd be around an overload of`init_sec_mon`, along with some assembly? Is the security monitor referred to in this context the Linux kernel? Thanks.

**Comment by clementleger** [comment]
@tprrt, Any idea ? (I'm not working anymore on this project)

**Comment by tprrt** [comment]
Hi,

I'm facing the same issue, since a few days,  when I switched from u-boot-at91 to u-boot-mch.

I advised Microchip about it, I shall investigate this issue.

Kind regards,
Thomas

**Comment by huntc** [comment]
> I'm facing the same issue, since a few days, when I switched from u-boot-at91 to u-boot-mch.

Am I right in thinking that jumping to u-boot shouldn't be an issue though i.e. it doesn't require those registers being set up?

Thanks for having followed up with Microchip.

**Comment by huntc** [comment]
Hey @tprrt - just wondering if you were able to find anything suspicious in your investigations.

Having studied the OP-TEE code today, I'm not seeing what calling into Linux should be different from calling U-Boot. My understanding is that the [`smc` call here](https://github.com/OP-TEE/optee_os/blob/bf8703986477d485ed1b2b2d4a2c5ce6e83dab11/core/arch/arm/kernel/entry_a32.S#L611) should switch to the monitor, which should then switch to the OS given the register setup.

I'm assuming that there's no special configuration required on the Linux kernel itself; at least to demonstrate that it can be jumped into from OP-TEE. Is that right?

Any other thoughts or ideas? Thanks.

**Comment by tprrt** [comment]
Hello @huntc,

I think it is an U-Boot issue, because on my setup no issue occurs, when I'm swapping the U-Boot binary with a binary built with an old U-boot-at91-devel branch.

Kind regards,
Thomas

**Comment by huntc** [comment]
@tprrt - But I'm not using U-Boot.... I'm trying to launch the Linux kernel directly from OP-TEE. :-)

**Comment by tprrt** [comment]
Hello @huntc,

> @tprrt - But I'm not using U-Boot.... I'm trying to launch the Linux kernel directly from OP-TEE. :-)

Sorry, I did not see.
Moreover, I never test to do that.

Have you adapted the dts of your target to use scmi, psci and devices drived by OP-TEE ?
Something like that: [arch/arm/boot/dts/microchip/sama5d2-optee.dtsi](https://github.com/linux4microchip/linux/blob/linux-6.6-mchp/arch/arm/boot/dts/microchip/sama5d2-optee.dtsi)

On wlsom1 and som1 evk, this dtsi is included in dts to override clk nodes and to disable device nodes managed by optee:
```
diff --git a/arch/arm/dts/at91-sama5d27_wlsom1_ek.dts b/arch/arm/dts/at91-sama5d27_wlsom1_ek.dts                                                                                                                                              
index 6d4b35ea9661..36c2eaac14d8 100644                                                                                                                                                                                                       
--- a/arch/arm/dts/at91-sama5d27_wlsom1_ek.dts                                                                                                                                                                                                
+++ b/arch/arm/dts/at91-sama5d27_wlsom1_ek.dts                                                                                                                                                                                                
@@ -9,6 +9,9 @@                                                                                                                                                                                                                               
 /dts-v1/;                                                                                                                                                                                                                                    
 #include <dt-bindings/gpio/gpio.h>                                                                                                                                                                                                           
 #include "sama5d27_wlsom1.dtsi"                                                                                                                                                                                                              
+#ifdef CONFIG_CLK_SCMI                                                                                                                                                                                                                       
+#include "sama5d2-optee.dtsi"                                                                                                                                                                                                                
+#endif                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                              
 / {                                                                                                                                                                                                                                          
        model = "Microchip SAMA5D27 WLSOM1 EK";                                                                                                                                                                                               
--  
```

Kind regards,
Thomas

**Comment by huntc** [comment]
> > @tprrt - But I'm not using U-Boot.... I'm trying to launch the Linux kernel directly from OP-TEE. :-)
> 
> Sorry, I did not see. Moreover, I never test to do that.
> 

Thanks for the reply. I like to pioneer the way. ;-) As having at91bootstrap boot the Linux kernel directly in place of U-Boot is a valid thing to do, it'd be great to understand how it can be achieved. I'm sure I'm not the first person to have the problem, but I'm happy to put in what effort is required to see this through. U-Boot adds considerably to the boot time of devices, and isn't necessary for our embedded scenario.

> Have you adapted the dts of your board to use scmi, psci and devices drived by OP-TEE ? Something like that: [arch/arm/boot/dts/microchip/sama5d2-optee.dtsi](https://github.com/linux4microchip/linux/blob/linux-6.6-mchp/arch/arm/boot/dts/microchip/sama5d2-optee.dtsi)

I have done this - and modifed the Linux kernel kconfig to apply settings per the Microchip examples. Here's my dtb that's used by at91bootstrap, and (I think) available to OP-TEE:

```
$ dtc -I dtb output/images/sama5d27_wlsom1_cuprous_gw.dtb | grep optee
<stdout>: Warning (simple_bus_reg): /ahb/apb/ptc@fc060000: simple-bus unit address format error, expected "800000"
<stdout>: Warning (interrupt_provider): /ahb/apb/interrupt-controller@fc020000: Missing #address-cells in interrupt provider
<stdout>: Warning (interrupt_provider): /ahb/apb/pinctrl@fc038000: Missing #address-cells in interrupt provider
		optee_core@20000000 {
		optee_shm@21000000 {
		optee {
			compatible = "linaro,optee-tz";
```

...and here's evidence of that dtb being picked up:

```
RomBOOT
Backup mode enabled


AT91Bootstrap 4.0.6 (2024-06-28 16:56:34)

SD/MMC: Image: Read file zImage to 0x26f00000
MMC: ADMA supported
SD: Card Capacity: High or Extended
SD: Specification Version 3.0X
SD/MMC: dt blob: Read file sama5d27_wlsom1_cuprous_gw.dtb to 0x21000000    <<< HERE'S MY DTB

KERNEL: Booting zImage ...
DT: Using device tree in place at 0x21000000

KERNEL: Starting linux kernel ..., machid: 0xffffffff

SD/MMC: Done to load image
SD/MMC: Image: Read file tee.bin to 0x20000000
Starting OP-TEE, Run at 0x20000000, Non-secure entry at 0x26f00000
I/TC: 
I/TC: Embedded DTB found
I/TC: OP-TEE version: Unknown_4.2 (gcc version 13.2.1 20231009 (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7))) #1 Fri Jun 28 07:24:45 UTC 2024 arm
I/TC: WARNING: This OP-TEE configuration might be insecure!
I/TC: WARNING: Please check https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html
I/TC: Primary CPU initializing
I/TC: Primary CPU switching to normal world boot
```

Even without that though, I'd expect to some evidence of Linux booting. I'm obviously doing something fundamentally wrong. Do you have any further recommendations re. debug?

Also, did Microchip respond? I can also raise a support case with them, but I suspect this is the best place to have my OP-TEE issues resolved, and for me to be able to contribute any fixes required.

Thanks for the help so far.

**Comment by huntc** [comment]
I don't know if this helps, but the Microchip example has `CONFIG_ATMEL_PM` disabled. However, I don't seem to be able to disable that unless `CONFIG_PM` is also disabled (which I don't think it is with the Microchip example).

**Comment by huntc** [comment]
I've now made my changes to our buildroot config available as a draft PR. Our board is largely based on the atsama5d27-wlsom1-ek. The README explains how to set it up - it should be straightforward in terms of buildroot familiarity. I'd really appreciate someone here being able to take it for a spin. Meanwhile, I'll also raise an issue with Microchip. Thanks so much.

https://github.com/cuprous-au/buildroot-external-cuprous/pull/1

**Comment by jenswi-linaro** [comment]
Do you have the kernel loaded at `0x26f00000`? To see if you can get the kernel to boot you could try to hard code the expected values into `nsec_ctx->{r0-r3}` in` init_sec_mon()`. It should be the same values that `at91bootstrap3` has passed to OP-TEE if you don't know the values.

**Comment by huntc** [comment]
Hi @jenswi-linaro - the logs above do indicate the kernel being loaded there, and the non-secure address being the same.

**Comment by jenswi-linaro** [comment]
It might be interesting to prove that the kernel can boot in this configuration, provided it sees the expected register content.

**Comment by huntc** [comment]
> It might be interesting to prove that the kernel can boot in this configuration, provided it sees the expected register content.

This is where my lack of knowledge may show, but isn’t the jump into the kernel the same in terms of setup, whether jumping from optee, uboot or at91bootstrap? Isn’t it just the setup of r0-4 that’s important?

I’m no kernel or optee developer, but I’m willing to give things a go if I can be guided further. Thanks.

**Comment by jenswi-linaro** [comment]
> > It might be interesting to prove that the kernel can boot in this configuration, provided it sees the expected register content.
> 
> This is where my lack of knowledge may show, but isn’t the jump into the kernel the same in terms of setup, whether jumping from optee, uboot or at91bootstrap? Isn’t it just the setup of r0-4 that’s important?

Yes, that is what we expect at this stage. But we don't know for sure if there's some other issue.
You can find more information on the registers at https://docs.kernel.org/arch/arm/booting.html.
Anyway, perhaps @tprrt finds something.

**Comment by huntc** [comment]
Any further thoughts @tprrt? Thanks for any guidance you may be able to provide.

**Comment by tprrt** [comment]
Hello @huntc,

> Any further thoughts @tprrt? Thanks for any guidance you may be able to provide.

I'm reproducing the issue with my setup:
```
AT91Bootstrap 4.0.9 (2024-07-26 11:48:51)

SD/MMC: Image: Read file Image to 0x22000000
MMC: ADMA supported
SD: Card Capacity: High or Extended
SD: Specification Version 3.0X
SD/MMC: dt blob: Read file sama5d2.dtb to 0x21000000

KERNEL: Booting zImage ...
DT: Using device tree in place at 0x21000000

KERNEL: Starting linux kernel ..., machid: 0xffffffff

SD/MMC: Done to load image
SD/MMC: Image: Read file tee.bin to 0x20000000
Starting OP-TEE, Run at 0x20000000, Non-secure entry at 0x22000000
I/TC: 
I/TC: Embedded DTB found
I/TC: OP-TEE version: Unknown_4.3 (gcc version 12.3.0 (Buildroot 2021.11-11272-ge2962af)) #1 Fri Jul 26 09:35:42 UTC 2024 arm
I/TC: WARNING: This OP-TEE configuration might be insecure!
I/TC: WARNING: Please check https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html
I/TC: Primary CPU initializing
I/TC: nvmem_huk: HUK truncated from 32 to 16 bytes
I/TC: Primary CPU switching to normal world boot
```

I'm starting to figure it out.

Kind regards,
Thomas

**Comment by TonyHan11** [comment]
Hello @huntc 

I made it work on SAMA5D27-WLSOM1-EK1_RevA board and find that the issue is caused by 2 main reasons:
 - access memory that is protected by OPTEE-OS during the boot of the kernel
 - wrong Linux command line got from arch/arm/kernel/setup.c:setup_arch()

Following are the modifications for the workaround.
The patch for [at91bootstrap 0820e87](https://github.com/linux4sam/at91bootstrap/): 
```
diff --git a/driver/load_kernel.c b/driver/load_kernel.c
index de710293..96263f2c 100644
--- a/driver/load_kernel.c
+++ b/driver/load_kernel.c
@@ -52,6 +52,10 @@ static int setup_dt_blob(void *blob)
        dbg_info("DT: Using device tree in place at %x\n",
                                                (unsigned int)blob);

+#if defined(CONFIG_LOAD_OPTEE) && defined(CONFIG_LINUX_IMAGE)
+       return 0;
+#endif
+
        /* no point in fixing if we do not have configured bootargs */
        if (bootargs && *bootargs) {
                char *p;
```

at91bootstrap/configs/sama5d27_wlsom1_ek-opteesd_linux_defconfig
```
# Copyright (C) 2024 Microchip Technology Inc. and its subsidiaries
#
# SPDX-License-Identifier: MIT

CONFIG_CRYSTAL_24_000MHZ=y
CONFIG_CONSOLE_INDEX=0
CONFIG_DEBUG=y
CONFIG_DDR_SET_BY_DEVICE=y
CONFIG_DDR_AD220032D=y
CONFIG_SDCARD=y
# CONFIG_SDHC_8BIT_SUPPORT is not set
CONFIG_LOAD_OPTEE=y
CONFIG_LED_ON_BOARD=y
CONFIG_LED_R_ON_PIOA=y
CONFIG_LED_R_PIN=6
CONFIG_LED_G_ON_PIOA=y
CONFIG_LED_G_PIN=7
CONFIG_LED_B_ON_PIOA=y
CONFIG_LED_B_PIN=8
CONFIG_LOAD_LINUX=y
CONFIG_IMAGE_NAME="zImage"
CONFIG_OF_OVERRIDE_DTB_NAME="at91-sama5d27_wlsom1_ek.dtb"
CONFIG_JUMP_ADDR="0x23000000"
CONFIG_OF_ADDRESS="0x26000000"
```

The patch for linux-at91:
```
diff --git a/arch/arm/boot/dts/microchip/sama5d2.dtsi b/arch/arm/boot/dts/microchip/sama5d2.dtsi
index 6f93f7375526..500301bae6c0 100644
--- a/arch/arm/boot/dts/microchip/sama5d2.dtsi
+++ b/arch/arm/boot/dts/microchip/sama5d2.dtsi
@@ -73,9 +73,9 @@ etm_out: endpoint {
                };
        };

-       memory@20000000 {
+       memory@22000000 {
                device_type = "memory";
-               reg = <0x20000000 0x20000000>;
+               reg = <0x22000000 0x0E000000>;
        };

        clocks {
```

config of command line in kernel's defconfig:
```
CONFIG_CMDLINE="console=ttyS0,115200 initrd=0x21100000,25165824 root=/dev/mmcblk0p2 rw rootwait rootfstype=ext4 rw"
```

**Comment by TonyHan11** [comment]
`PS for yesterday's comment:` without the patch for at91bootstrap and the modification of config for command line in kernel's defconfig it also works properly, but following 2 lines need to be added to `sama5d27_wlsom1_ek-opteesd_linux_defconfig`
```
CONFIG_OVERRIDE_CMDLINE=y
CONFIG_ARG_ROOTFSTYPE=" rootfstype=ext4"
```

**Comment by huntc** [comment]
Thanks so much for the follow up here. I will try and apply these discoveries next week.
