### ISSUE TITLE
get stuck with RNG in OPTEE

### ISSUE THREAD

**Issue by viewpro9711** [OP-TEE/optee_os#6919]
Hi everyone, when I was booting OPTEE for testing Arm Crypto Extension algorithms. I got panic while I enabled CFG_CRYPTO_CE=y  and CFG_WITH_SOFTWARE_PRNG=y . I found the error occured in :

```
void crypto_accel_sha256_compress(uint32_t state[8], const void *src,
				  unsigned int block_count)

{
	uint32_t vfp_state = 0;
 
	vfp_state = thread_kernel_enable_vfp();

	sha256_ce_transform(state, src, block_count);

	thread_kernel_disable_vfp(vfp_state);
}
	
```
when sha256_ce_transform(state, src, block_count)  ran- -> I got panic when it called to assembly . 

Can someone give me some suggestion for debug and solve this issue .

Thanks and Regards

**Comment by jenswi-linaro** [comment]
Are you sure that your platform supports the Arm Crypto Extensions?

**Comment by viewpro9711** [comment]
Hi @jenswi-linaro ,

Actually, I develop on virtual environment platform, so I'm not sure my platform already support  Arm Crypto Extensions yet . Do you have any idea to confirm this. Thanks

**Comment by jenswi-linaro** [comment]
Checking the documentation for the virtual environment platform is a good start, perhaps there's some extra option needed. :-)
