### ISSUE TITLE
ARM trusted firmware and EUFI makefile problem

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#692]
Hi, I moved the root director that I have for building the ARM Trusted Firmware with EUFI and OPTEE. Everything else works except this:

Building opteed Trusted OS
Target: AARCH64
Build: other
Target: ARM
Build: other
CFG_ARM64_core=y
CROSS_COMPILE_ta_arm64=aarch64-linux-gnu-
CROSS_COMPILE=arm-linux-gnueabihf-
CROSS_COMPILE_core=aarch64-linux-gnu-
PROFILE=RELEASE
PLATFORM=hikey
PLATFORM_FLAVOR=
CFG_TEE_CORE_LOG_LEVEL=2
make: *** No rule to make target `**/home/peter/datacapsule/HiKey/tools/arm64-tc/lib/gcc/aarch64-linux-gnu/4.9.3/include/stddef.h**', needed by `out/arm-plat-hikey/core/arch/arm/kernel/tee_ta_manager.o'.  Stop.
make: *** Waiting for unfinished jobs....
  CHK     out/arm-plat-hikey/conf.mk

Somehow, parts of the makefile is reading a config from somewhere it seems...that is stuck on the original root path. Just wondering how I can regenerate these paths afresh?

**Comment by vchong** [comment]
Run 'make clean' command, delete optee_os/out dir and try again.

**Comment by peterfeifanchen** [comment]
That worked thanks!

**Comment by pascal-brand-st** [comment]
Question has been answered, please re-open in case you have additional questions
