### ISSUE TITLE
mbedtls cfb symmetric cipher mode not working

### ISSUE THREAD

**Issue by supernovagr** [OP-TEE/optee_os#6938]
Hello everyone, I am using op-tee latest master version (i am guessing that is 4.3.0-rc1) on linux with qemu v8. 

I am also using mbedtls version 3.6.0 for the cryptographic operations of my trusted applications. When developing a new application, i do it in x86 again using mbedtls, and then convert it into a trusted application so i do not have to rebuild or cross compile every time i have to make a change.

When running my application in x86 environment, i get no errors, but when i build optee with my TA in the optee_examples folder, there is an error about mbedtls_aes_crypt_cfb128. 

Is this function not enabled in optee, if yes why not, and how can i enable it?

Thanks in advance.

**Comment by jenswi-linaro** [comment]
TAs use a minimal mbedtls configuration, see `lib/libmbedtls/include/mbedtls_config_uta.h`
