### ISSUE TITLE
How to use TZASC to configure a new secure region in Hikey960?

### ISSUE THREAD

**Issue by qianfei11** [OP-TEE/optee_os#6940]
I found in https://github.com/OP-TEE/optee_os/issues/4359 that I can use TZASC to configure a dynamic mapping from `plat-stm32mp1/plat_tzc400.c` on the STM32MP157C-DK2 board. However, in the `plat-hisilicon/` folder, there are only `main.c` and `psci.c` files, neither of which seem to have any relation to TZASC. Is there any support for TZASC configuration in OP-TEE for the Hikey960 board?

Also, I found this answer on the [96boards forum](https://discuss.96boards.org/t/trustzone-hardware-features-tzasc-tzma-tzpc-on-hikey/1919). It seems that the Hikey960 does not expose the related hardware information, so the related code is not implemented. Is this correct?

Lastly, I want to inquire about `core/drivers/tzc400.c` and `core/drivers/tzc380.c`. Are they simple implementations for TZASC? If I can provide a base for TZASC registers, can I use these functions to configure TZASC?

**Comment by etienne-lms** [comment]
> Lastly, I want to inquire about core/drivers/tzc400.c and core/drivers/tzc380.c. Are they simple implementations for TZASC? If I can provide a base for TZASC registers, can I use these functions to configure TZASC?

Regarding this last question:yes, these drivers can be used with Arm TZC400/TZC380 hardware components if implemented in the silicon of the device.
