### ISSUE TITLE
optee riscv support

### ISSUE THREAD

**Issue by stefvas** [OP-TEE/optee_os#6948]
This issue aims to determine whether OP-TEE can run on RISC-V architecture and identify any boards that can be used for testing.
Objectives

    Confirm if OP-TEE is compatible with RISC-V architecture.
    Identify any necessary modifications or patches needed for compatibility.
    Determine available boards for testing OP-TEE on RISC-V.
    Document the setup and testing process.

Tasks

    Research and verify if OP-TEE has existing support for RISC-V.
    Identify any ongoing efforts or existing patches for RISC-V support in OP-TEE.
    Modify and compile OP-TEE for a RISC-V target, if necessary.
    Test OP-TEE on the QEMU RISC-V emulator.
    Identify and test on available RISC-V development boards (e.g., HiFive Unleashed).
    Document the setup process and any issues encountered.

**Comment by lyctw** [comment]
Hi @stefvas,

We are working on OP-TEE RISC-V support; currently, there is no RISC-V development board supported, but you can run OP-TEE on a QEMU virt machine, follow the [steps](https://wiki.riseproject.dev/display/HOME/OPTEE_00_01+-+OP-TEE+support) in the "QEMU Virt test environment" section.
