### ISSUE TITLE
tee-supplicant fails on hikey board

### ISSUE THREAD

**Issue by zero-clouds-** [OP-TEE/optee_os#695]
Following instructions from 96boards: https://github.com/96boards/documentation/wiki/HiKeyOPTEE#optee-test
After running `depmod` and `modprobe optee_armtz`, `tee-suuplicant&` fails with the following in serial output:

> armv7sec armv7sec.0: shm service not available: FFFFFFFF
> misc opteearmtz00: tee_get: opteearmtz00::start() failed, err=-22

Upon a second try, found that tee-supplicant is actually running

> misc opteearmtz00: tee_get: opteearmtz00::start() failed, err=-22
> armv7sec armv7sec.0: tee_supp_open: ERROR Only one Supplicant is allowed

But xtest fails every test. Any ideas what is happening?

**Comment by jforissier** [comment]
Outdated arm-trusted-firmware, most probably.

**Comment by weihuang** [comment]
@jforissier I have the exactly same issue with tee-supplicant on hikey board. I did the following but the problem remains:

I checked out the arm-trusted-firmware from
`$git clone -b hikey  https://github.com/96boards/arm-trusted-firmware.git`
The latest version commit is:
```
commit 7fb9b0e1bf90d167ba451fa3d1485ad07ca5c1da
Date:   Tue Jan 12 14:18:51 2016 +0800
```
then cleaned up everything and rebuit.

**Comment by vchong** [comment]
We're currently investigating.. will get back to you guys asap..

**Comment by jforissier** [comment]
Sorry for not providing a link to what I meant by "the latest arm-trusted-firmware", I replied from a smartphone ;)
If you are using the latest optee_os you need https://github.com/linaro-swg/arm-trusted-firmware/tree/hikey_gendrv, which contains this commit: https://github.com/linaro-swg/arm-trusted-firmware/commit/9d3b0ecf9ffaf52f918b3870d69a55c42fb7fbac
@vchong it seems https://github.com/OP-TEE/manifest/blob/master/hikey.xml needs updating.

**Comment by vchong** [comment]
@jforissier Thanks! In addition to using linaro-swg/arm-trusted-firmware@9d3b0ec, will cherry-picking the commit into https://github.com/96boards/arm-trusted-firmware work as well?

@zero-clouds-, @weihuang Can one of you test and let us know if this helps?

**Comment by jforissier** [comment]
@vchong yes you can cherry-pick, actually merge and it will be a fast-forward because the only difference between the 96boards and linaro-swg branches is this commit!

**Comment by vchong** [comment]
@jforissier Oh, ok! Should have looked haha. Thanks!

**Comment by zero-clouds-** [comment]
After cloning the repo advised, building and flashing everything over to the board, I ran into this error, repeating endlessly, when booting:

> hi6220-mbox f7510000.mailbox: Try increasing MBOX_TX_QUEUE_LEN

I will try rebuilding again to make sure it wasn't something wrong in the build.

**Comment by weihuang** [comment]
@vchong I switched to [https://github.com/linaro-swg/arm-trusted-firmware/tree/hikey_gendrv](https://github.com/linaro-swg/arm-trusted-firmware/tree/hikey_gendrv)  , cleaned up and rebuilt everything (I suppose only fip.bin is changed here?). 
It boots up but this time there is one more error message after I run 
`$tee-supplicant & `:

> ERR [1976] TEES:main:392: error opening [/dev/opteermtz00]

before which the same "shem service not available" error is still there:

> armv7sec armv7sec.0: shm service not available: FFFFFFFF
> misc opteearmtz00: tee_get: opteearmtz00::start() failed, err=-22

Thanks.

**Comment by vchong** [comment]
@zero-clouds- @weihuang Thanks for helping with testing! I think I might have a clue what's wrong. Will do some testing and post back the result asap! Stay tuned..

**Comment by vchong** [comment]
@zero-clouds- @weihuang Sorry for the delay. Ran into a bit of problem but managed to sort everything out. The instructions at https://github.com/96boards/documentation/wiki/HiKeyOPTEE have been updated. Please try again from scratch and close this issue if everything is ok.

The main issue was that as of 24-Nov-2015, OP-TEE has been integrated into 96boards HiKey releases and snapshots images, so if you followed the previous instructions, you're basically making an extra copy of the driver, supplicant and client library in the rootfs and confusing the system. The instructions have been updated to copy the files to the proper path to replace existing ones.

**Comment by zero-clouds-** [comment]
@vchong @weihuang Thanks for working on this. With the new instructions I was able to get everything onto the board without trouble.

Did xtest fail tests for either of you? My summary looks like this:
> 8878 subtests of which 3399 failed
> 59 test cases of which 43 failed
> 0 test case was skipped
> TEE test application done!

**Comment by vchong** [comment]
@zero-clouds- No. I didn't see any failures when I ran it earlier. Did you copy the *.ta files to lib/optee_armtz/? What errors are you getting?

**Comment by vchong** [comment]
@zero-clouds- Sorry. I just noticed an error in the instructions. `sudo mkdir usr/lib/optee_armtz` should be `sudo mkdir lib/optee_armtz`. Maybe that's what causing the failures for you. You should see errors like 'TA not found' or something to that effect.

Note that you don't have to recreate the jessie image; you can create the proper directory and move the \*.ta files over to the proper location directly from the HiKey console itself, **IF** those files have been copied somewhere in the rootfs.

**Comment by zero-clouds-** [comment]
@vchong That was it. xtest now runs all tests with no failures. Thanks.
