### ISSUE TITLE
Support for HW features in OP-TEE

### ISSUE THREAD

**Issue by larschristensen** [OP-TEE/optee_os#696]
Hi,

I remember from another thread that support for HW floating-point + NEON instructions is in the pipeline. Do you have any information on when this support can be expected?

In addition, computationally demanding applications could also benefit significantly by multi-core support within the TEE. Any thoughts on the possibility for supporting for this?

Best regards
-Lars Christensen

**Comment by jenswi-linaro** [comment]
Hi Lars,

All this is merged to master now.

Regards,
Jens

**Comment by larschristensen** [comment]
Hi Jens,

That sounds great. So you are saying that support for multi-threading across multiple CPU cores has also been merged to master?

Best regards
-Lars

**Comment by jenswi-linaro** [comment]
Yes

**Comment by larschristensen** [comment]
That is news to me, but great news. Thanks for the

**Comment by larschristensen** [comment]
Hi Jens,

I can't seem to find any platform APIs that a TA can use for multi-threaded execution across multiple CPUs. Could you point me to the right API?

Best regards
-Lars

**Comment by jenswi-linaro** [comment]
Hi Lars,

I'm sorry, I think I misunderstood your question.

"multi-threading across multiple CPU cores within a single TA" is not entirely true, by GlobalPlatform specification a TA must not execute in parallel in the same address space (or instance). We do support several instances of the same TA to execute in parallel, but from your comment it seems that's not what you're looking for.

Others has asked for true multi-threading in a single instance of a TA. The greatest challenge for that is actually to define an API, I haven't looked into that though.

Regards,
Jens

**Comment by larschristensen** [comment]
Thanks for the clarification Jens.

Do you have any plans for looking into this?

Best regards
-Lars

**Comment by jenswi-linaro** [comment]
We don't have any specific plans for that currently.

Regards,
Jens
