### ISSUE TITLE
Integrating OP-TEE to work with KasperskyOS

### ISSUE THREAD

**Issue by iitKD** [OP-TEE/optee_os#6967]
I am working on a project, where i want to build the kasperskyOS based solution that is able to utilise the Trustzone of ARM devices, since OP-TEE is open source i thought it would be a good way to do it, but sice OP_TEE is based on LINUX system , how can i port it for KasperskyOS, is it even possible.

My though process was to build a KOS based host application that could interact with the OP-TEE based TA, but i dnot know how i will do that cause KOS is supports rpi4 and OP_TEE pi3 .

KasperskyOS is a microkernel , which i cannont build as stanalone OS and use it to build other application, currently thee community edition available build image for application based on KOS to run on quemu or rpi4.

Can anyone help or point in some direction that i follow to assertain if this can be done or not, Thank you.
Guide to kaspersky OS : https://support.kaspersky.com/help/KCE/1.2/en-US/whats_new.htm

**Comment by jenswi-linaro** [comment]
You'll need a driver in the kernel you're using to interact with OP-TEE and TAs in the secure world.
