### ISSUE TITLE
Secure storage from PTA

### ISSUE THREAD

**Issue by ayuser123** [OP-TEE/optee_os#6968]
Hi,
I'm trying to have a PTA store/read a persistent object.
I understand the TEE API is not available for use from the PTA.
In my attempt to use the functions in tee_svc_storage.c directly, I end up with a panic from "ts_get_current_session();"

What would the best approach be for doing this?  
Are there any examples I could follow?

Thanks!

**Comment by jforissier** [comment]
> Hi, I'm trying to have a PTA store/read a persistent object. I understand the TEE API is not available for use from the PTA.

Correct.

> In my attempt to use the functions in tee_svc_storage.c directly, I end up with a panic from "ts_get_current_session();"
> 
> What would the best approach be for doing this? Are there any examples I could follow?

See for instance `core/pta/attestation.c` and, more specifically, `sec_storage_obj_read()` and `sec_storage_obj_write()`.
