### ISSUE TITLE
How does memory protection actually work with and without MMU enabled?

### ISSUE THREAD

**Issue by zzm7000** [OP-TEE/optee_os#697]
Hi

I have been wondering how memory protection actually works with and without MMU enabled.

I know memory separation is configured in platform_config.h. Take Hikey board as an example, OPTEE assigns 0 - 0x3EF00000 to normal world, and above to Secure World in [Hikey platform_config](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/platform_config.h#L61). And, this is reflected in the Secure World page table in [core_init_mmu_tables](https://github.com/OP-TEE/optee_os/blob/f2930adaf8a10f2a6154ae21ec991ce7133fde82/core/arch/arm/mm/core_mmu_lpae.c#L430). But, how this can stop the normal world from mapping and accessing the memory above 0x3EF00000, since normal world uses a different page table that donot need to respect the secure world table? 

I feel there is a need to specify which memory belongs to secure world or normal world physically, maybe in a co-processor? But I could not find anything. It also seems the TZASC is only for off-SoC RAM not on-SoC RAM.

Also in this [thread](https://community.arm.com/thread/3200), it is said "With the MMU disabled, the secure world will only generate secure accesses.  The non-secure/normal world will only generate non-secure accesses.". Then, how to specify which memory region belongs to which world in this case?

Thank you. I apologize if my question is too naive.

**Comment by jforissier** [comment]
On HiKey, the physical memory range 0x3F000000 - 0x3FFFFFFF is made secure by https://github.com/linaro-swg/arm-trusted-firmware/blob/hikey/plat/hikey/plat_security.c. I don't think it matters whether MMU is turned on or off.
Hi6220 has some sort of memory controller that can do this, similar to TZASC. And yes this memory range is actually off-chip RAM.

**Comment by zzm7000** [comment]
Thank you so much for your answer! 

So, as used in ```#define MDDRC_SECURITY_BASE	0xF7121000```, what is it at this address? Is it the memory controller you are talking about? I checked the document at [https://github.com/96boards/documentation/blob/master/hikey/Hi6220V100_Multi-Mode_Application_Processor_Function_Description.pdf?raw=true](https://github.com/96boards/documentation/blob/master/hikey/Hi6220V100_Multi-Mode_Application_Processor_Function_Description.pdf?raw=true), and I did not find it mentioned in this document.

**Comment by jforissier** [comment]
@zzm7000 this is undocumented, unfortunately, and I have no further information. But, there is some kernel code for hi6210sft which looks remarkably similar, maybe you can try to figure out how it works and see if it applies to HiKey: https://github.com/slade87/ALE21-Kernel/blob/master/drivers/hisi/ap/platform/hi6210sft/soc_mddrc_security_interface.h and https://github.com/slade87/ALE21-Kernel/blob/master/drivers/hisi/ddrc/ddrc_dmc_protect.c.

Now I'm wondering: could the protection of the top 16 MB, set by https://github.com/linaro-swg/arm-trusted-firmware/blob/hikey/plat/hikey/plat_security.c, be reverted by non-secure kernel code? I'm afraid it can. That would be a problem ;) I need to check that. Maybe this is controlled via `SOC_MDDRC_SECURITY_SEC_LOCKDOWN_SELECT_UNION`? But what is the 'secure_boot_lock signal' mentioned in the comments? I don't know.

**Comment by zzm7000** [comment]
@jforissier Exactly, that was my original question. Obviously, it doesnot make sense if the normal world has a way to revert it. I thought there should be some controllers other than MMU in charge of secure/non-secure isolation, but could not find it before. Now I know for HiKey the undocumented controller is at `0xF7121000`. It also means OPTEE relies on firmware to partition secure/non-secure memory, which is new information to me.

Here is my theory now: 

What is said here [https://github.com/slade87/ALE21-Kernel/blob/master/drivers/hisi/ap/platform/hi6210sft/soc_mddrc_security_interface.h#L184](https://github.com/slade87/ALE21-Kernel/blob/master/drivers/hisi/ap/platform/hi6210sft/soc_mddrc_security_interface.h#L184) is: when `secur_boot_lock` signal is high, the register `SEC_LOCKDOWN_SELECT` will be set as read-only. Also, other registers specified in `SEC_LOCKDOWN_SELECT` will be set as read-only. And, they can only be unset by power-on reset.

So, ARM-TF first configures the controller at address `0xF7121000` including `SEC_RGN_MAP`, `SEC_RGN_ATTRIB `, and others to specify which region is for secure world. Then, lock the registers. 

Next question is how to raise the `secur_boot_lock` signal?

**Comment by vchong** [comment]
Section 1.6.2 of https://github.com/96boards/documentation/blob/master/hikey/Hi6220V100_Multi-Mode_Application_Processor_Function_Description.pdf mentions:

The eFUSE configuration is as follows:
security_boot_flg: 0 (non-secure boot)
1: secure boot

So maybe this one? The only thing is the values for it all seems 'don't-cares'.

**Comment by zzm7000** [comment]
@vchong Maybe you are right. I couldn't find anything else.
