### ISSUE TITLE
low memory in Android U CTS test

### ISSUE THREAD

**Issue by klcib508** [OP-TEE/optee_os#6979]
in cts test ,when test RSA crypto ,lowmemory rsp ,but Idonot know whick memory config should be increase
(240807_15:27:01.557)D/TA:  TA_add_to_params:58 TA_add_to_params 58
(240807_15:27:01.557)D/TA:  TA_add_to_params:61 Failed to get ECC curve nist, key_size = 2048
(240807_15:27:01.557)D/TA:  TA_fill_characteristics:282 TA_fill_characteristics 282
(240807_15:27:01.557)D/TA:  TA_push_param:141 TA_push_param 141
(240807_15:27:01.557)D/TA:  TA_push_param:141 TA_push_param 141
(240807_15:27:01.558)D/TA:  TA_push_param:141 TA_push_param 141
(240807_15:27:01.558)D/TA:  TA_push_param:141 TA_push_param 141
(240807_15:27:01.558)D/TA:  TA_push_param:141 TA_push_param 141
(240807_15:27:01.558)D/TA:  TA_push_param:141 TA_push_param 141
(240807_15:27:01.558)D/TA:  TA_push_param:141 TA_push_param 141
(240807_15:27:01.558)D/TA:  TA_push_param:141 TA_push_param 141
(240807_15:27:01.558)D/TA:  TA_serialize_param_set:900 TA_serialize_param_set 900
(240807_15:27:01.558)D/TA:  TA_encrypt:218 TA_encrypt 218
(240807_15:27:01.558)D/TA:  TA_execute:159 TA_execute 159 size = 4392
(240807_15:27:01.558)D/TA:  TA_open_secret_key:36 TA_open_secret_key 36
(240807_15:27:01.558)D/TA:  TA_open_secret_key:38 Use existing masterKey
(240807_15:27:01.558)D/TA:  TA_execute:188 tagLen = 16
(240807_15:27:01.558)D/TA:  TA_execute:192 tagLen = 16
(240807_15:27:01.558)D/TA:  TA_serialize_rsp_err:484 res: 0
(240807_15:27:01.558)D/TA:  TA_serialize_key_blob_akms:831 TA_serialize_key_blob_akms 831
(240807_15:27:01.558)D/TA:  TA_serialize_characteristics_akms:729 TA_serialize_characteristics_akms 729
(240807_15:27:01.558)D/TA:  TA_serialize_auth_set:624 TA_serialize_auth_set 624
(240807_15:27:01.558)D/TA:  TA_serialize_auth_set:669 indirect_data_size: 0
(240807_15:27:01.558)D/TA:  TA_serialize_auth_set:679 elems cnt: 8
(240807_15:27:01.558)D/TA:  TA_serialize_auth_set:703 elems size: 65
(240807_15:27:01.558)D/TA:  TA_serialize_auth_set:713 auth_set size: 77
(240807_15:27:01.558)D/TA:  TA_serialize_auth_set:624 TA_serialize_auth_set 624
(240807_15:27:01.558)D/TA:  TA_serialize_auth_set:669 indirect_data_size: 0
(240807_15:27:01.558)D/TA:  TA_serialize_auth_set:679 elems cnt: 0
(240807_15:27:01.558)D/TA:  TA_serialize_auth_set:703 elems size: 0
(240807_15:27:01.558)D/TA:  TA_serialize_auth_set:713 auth_set size: 12
(240807_15:27:01.558)D/TA:  TA_free_params:25 TA_free_params 25
(240807_15:27:01.558)D/TA:  TA_free_params:25 TA_free_params 25
(240807_15:27:01.558)D/TA:  TA_free_params:25 TA_free_params 25
(240807_15:27:01.558)D/TA:  TA_InvokeCommandEntryPoint:2175 KM_EXPORT_KEY
(240807_15:27:01.558)D/TA:  TA_exportKey:915 TA_exportKey 915
(240807_15:27:01.558)D/TA:  TA_deserialize_auth_set:228 TA_deserialize_auth_set 228
(240807_15:27:01.558)D/TA:  TA_deserialize_auth_set:251 indirect_data_size:0
(240807_15:27:01.558)D/TA:  TA_deserialize_auth_set:259 indirect_base:0x80109000
(240807_15:27:01.558)D/TA:  TA_deserialize_auth_set:278 elem cnt:0
(240807_15:27:01.558)D/TA:  TA_deserialize_auth_set:288 elem serialized size:0
(240807_15:27:01.558)D/TA:  TA_deserialize_auth_set:290 param_set->length:0
(240807_15:27:01.558)D/TA:  TA_deserialize_key_format:470 TA_deserialize_key_format 470
(240807_15:27:01.558)D/TA:  TA_deserialize_key_blob_akms:408 TA_deserialize_key_blob_akms 408
(240807_15:27:01.558)D/TA:  TA_deserialize_key_blob_akms:415 key_blob->key_material_size = 4392 sizeof(key_blob->key_material_size) = 4
(240807_15:27:01.558)D/TA:  TA_decrypt:224 TA_decrypt 224
(240807_15:27:01.558)D/TA:  TA_execute:159 TA_execute 159 size = 4392
(240807_15:27:01.558)D/TA:  TA_open_secret_key:36 TA_open_secret_key 36
(240807_15:27:01.558)D/TA:  TA_open_secret_key:38 Use existing masterKey
(240807_15:27:01.558)D/TA:  TA_populate_key_attrs:558 padding = 4 *type = 0xa1000030
(240807_15:27:01.558)D/TA:  TA_populate_key_attrs:569 RSA attrs_count = 8 algorithm = 1
(240807_15:27:01.609)D/TA:  TA_populate_key_attrs:593 *key_size = 2048 attrs_count = 8 padding = 8
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:598 i = 0 padding = 12 tag = 3489661232
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:616 i = 0 padding = 16 attr_size = 256
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:633 i = 0 padding = 272 attr_size = 256
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:598 i = 1 padding = 276 tag = 3489661488
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:616 i = 1 padding = 280 attr_size = 3
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:633 i = 1 padding = 283 attr_size = 3
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:598 i = 2 padding = 287 tag = 3221226288
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:616 i = 2 padding = 291 attr_size = 256
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:633 i = 2 padding = 547 attr_size = 256
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:598 i = 3 padding = 551 tag = 3221226544
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:616 i = 3 padding = 555 attr_size = 128
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:633 i = 3 padding = 683 attr_size = 128
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:598 i = 4 padding = 687 tag = 3221226800
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:616 i = 4 padding = 691 attr_size = 128
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:633 i = 4 padding = 819 attr_size = 128
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:598 i = 5 padding = 823 tag = 3221227056
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:616 i = 5 padding = 827 attr_size = 128
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:633 i = 5 padding = 955 attr_size = 128
(240807_15:27:01.644)D/TA:  TA_populate_key_attrs:598 i = 6 padding = 959 tag = 3221227312
(240807_15:27:01.645)D/TA:  TA_populate_key_attrs:616 i = 6 padding = 963 attr_size = 128
(240807_15:27:01.645)D/TA:  TA_populate_key_attrs:633 i = 6 padding = 1091 attr_size = 128
(240807_15:27:01.645)D/TA:  TA_populate_key_attrs:598 i = 7 padding = 1095 tag = 3221227568
(240807_15:27:01.645)D/TA:  TA_populate_key_attrs:616 i = 7 padding = 1099 attr_size = 128
(240807_15:27:01.645)D/TA:  TA_populate_key_attrs:633 i = 7 padding = 1227 attr_size = 128
(240807_15:27:01.645)D/TA:  TA_deserialize_param_set:335 TA_deserialize_param_set 335
(240807_15:27:01.645)D/TA:  TA_deserialize_param_set:356 params->length:8
(240807_15:27:01.645)D/TA:  TA_add_origin:485 TA_add_origin 485
(240807_15:27:01.645)E/TA:  TA_restore_key:795 populate attrs is finished with err 0
(240807_15:27:01.645)D/TA:  TA_check_permission:1094 TA_check_permission 1094
(240807_15:27:01.645)D/TA:  TA_check_permission:1096 in_params->params[0].tag = 268435458
(240807_15:27:01.645)D/TA:  TA_check_permission:1096 in_params->params[1].tag = 536870913
(240807_15:27:01.645)D/TA:  TA_check_permission:1096 in_params->params[2].tag = 536870917
(240807_15:27:01.645)D/TA:  TA_check_permission:1096 in_params->params[3].tag = 536870918
(240807_15:27:01.645)D/TA:  TA_check_permission:1096 in_params->params[4].tag = 1879048695
(240807_15:27:01.645)D/TA:  TA_check_permission:1096 in_params->params[5].tag = 268436158
(240807_15:27:01.645)D/TA:  TA_check_permission:1096 in_params->params[6].tag = 805306371
(240807_15:27:01.645)D/TA:  TA_check_permission:1096 in_params->params[7].tag = 1342177480
(240807_15:27:01.645)D/TA:  mbedTLS_import_rsa_pk:737 mbedTLS_import_rsa_pk 737
(240807_15:27:01.645)D/TA:  TA_serialize_rsp_err:484 res: 0
(240807_15:27:01.645)D/TA:  TA_serialize_blob_akms:498 TA_serialize_blob_akms 498
(240807_15:27:01.645)D/TA:  TA_free_params:25 TA_free_params 25
(240807_15:27:01.645)D/TA:  TA_free_params:25 TA_free_params 25
(240807_15:27:01.645)D/TA:  TA_InvokeCommandEntryPoint:2184 KM_DELETE_KEY
(240807_15:27:01.645)D/TA:  TA_deleteKey:1322 TA_deleteKey 1322
(240807_15:27:01.645)D/TA:  TA_serialize_rsp_err:484 res: 0
(240807_15:27:01.701)D/TA:  TA_InvokeCommandEntryPoint:2193 KM_BEGIN
(240807_15:27:01.735)D/TA:  TA_begin:1447 TA_begin 1447
(240807_15:27:01.735)D/TA:  TA_deserialize_purpose:456 TA_deserialize_purpose 456
(240807_15:27:01.735)D/TA:  TA_deserialize_key_blob_akms:408 TA_deserialize_key_blob_akms 408
(240807_15:27:01.736)D/TA:  TA_deserialize_key_blob_akms:415 key_blob->key_material_size = 4392 sizeof(key_blob->key_material_size) = 4
(240807_15:27:01.736)D/TA:  TA_deserialize_auth_set:228 TA_deserialize_auth_set 228
(240807_15:27:01.736)D/TA:  TA_deserialize_auth_set:251 indirect_data_size:69
(240807_15:27:01.736)D/TA:  TA_deserialize_auth_set:259 indirect_base:0x80107de0
(240807_15:27:01.736)D/TA:  TA_deserialize_auth_set:278 elem cnt:4
(240807_15:27:01.736)D/TA:  TA_deserialize_auth_set:288 elem serialized size:36
(240807_15:27:01.736)D/TA:  TA_deserialize_auth_set:290 param_set->length:4
(240807_15:27:01.736)D/TA:  param_deserialize:115 param tag:0x10000002
(240807_15:27:01.736)D/TA:  param_deserialize:115 param tag:0x20000006
(240807_15:27:01.736)D/TA:  param_deserialize:115 param tag:0x20000005
(240807_15:27:01.736)D/TA:  param_deserialize:115 param tag:0x900003ea
(240807_15:27:01.736)D/TA:  param_deserialize:202 type blob, blob_data:0x80107c30, blob len:69
(240807_15:27:01.736)D/TA:  TA_decrypt:224 TA_decrypt 224
(240807_15:27:01.736)D/TA:  TA_execute:159 TA_execute 159 size = 4392
(240807_15:27:01.736)D/TA:  TA_open_secret_key:36 TA_open_secret_key 36
(240807_15:27:01.736)D/TA:  TA_open_secret_key:38 Use existing masterKey
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:558 padding = 4 *type = 0xa1000030
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:569 RSA attrs_count = 8 algorithm = 1
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:593 *key_size = 2048 attrs_count = 8 padding = 8
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:598 i = 0 padding = 12 tag = 3489661232
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:616 i = 0 padding = 16 attr_size = 256
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:633 i = 0 padding = 272 attr_size = 256
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:598 i = 1 padding = 276 tag = 3489661488
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:616 i = 1 padding = 280 attr_size = 3
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:633 i = 1 padding = 283 attr_size = 3
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:598 i = 2 padding = 287 tag = 3221226288
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:616 i = 2 padding = 291 attr_size = 256
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:633 i = 2 padding = 547 attr_size = 256
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:598 i = 3 padding = 551 tag = 3221226544
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:616 i = 3 padding = 555 attr_size = 128
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:633 i = 3 padding = 683 attr_size = 128
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:598 i = 4 padding = 687 tag = 3221226800
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:616 i = 4 padding = 691 attr_size = 128
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:633 i = 4 padding = 819 attr_size = 128
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:598 i = 5 padding = 823 tag = 3221227056
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:616 i = 5 padding = 827 attr_size = 128
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:633 i = 5 padding = 955 attr_size = 128
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:598 i = 6 padding = 959 tag = 3221227312
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:616 i = 6 padding = 963 attr_size = 128
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:633 i = 6 padding = 1091 attr_size = 128
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:598 i = 7 padding = 1095 tag = 3221227568
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:616 i = 7 padding = 1099 attr_size = 128
(240807_15:27:01.736)D/TA:  TA_populate_key_attrs:633 i = 7 padding = 1227 attr_size = 128
(240807_15:27:01.736)D/TA:  TA_deserialize_param_set:335 TA_deserialize_param_set 335
(240807_15:27:01.736)D/TA:  TA_deserialize_param_set:356 params->length:8
(240807_15:27:01.736)D/TA:  TA_add_origin:485 TA_add_origin 485
(240807_15:27:01.736)E/TA:  TA_restore_key:795 populate attrs is finished with err 0
(240807_15:27:01.736)D/TA:  TA_check_params:636 TA_check_params 636
(240807_15:27:01.736)D/TA:  TA_check_params:644 KM_TAG_ALGORITHM
(240807_15:27:01.736)D/TA:  TA_check_params:657 KM_TAG_PURPOSE
(240807_15:27:01.736)D/TA:  TA_check_params:704 KM_TAG_DIGEST
(240807_15:27:01.736)D/TA:  TA_check_params:710 KM_TAG_PADDING
(240807_15:27:01.736)D/TA:  TA_check_params:721 KM_TAG_NO_AUTH_REQUIRED
(240807_15:27:01.736)D/TA:  TA_check_params:731 Unused parameter with tag 0x100002be
(240807_15:27:01.736)D/TA:  TA_check_params:640 KM_TAG_KEY_SIZE
(240807_15:27:01.736)D/TA:  TA_check_params:731 Unused parameter with tag 0x500000c8
(240807_15:27:01.736)D/TA:  TA_check_params:737 purpose[0] = 1
(240807_15:27:01.736)D/TA:  TA_check_params:739 op_purpose = 1 purpose_count = 1
(240807_15:27:01.736)D/TA:  TA_check_params:775 in_params->params[0].tag = 0x10000002
(240807_15:27:01.736)D/TA:  TA_check_params:841 Unused parameter with tag 0x10000002
(240807_15:27:01.736)D/TA:  TA_check_params:775 in_params->params[1].tag = 0x20000006
(240807_15:27:01.736)D/TA:  TA_check_params:775 in_params->params[2].tag = 0x20000005
(240807_15:27:01.736)D/TA:  TA_check_params:775 in_params->params[3].tag = 0x900003ea
(240807_15:27:01.738)D/TA:  is_origination_purpose:1080 is_origination_purpose 1080
(240807_15:27:01.738)E/TC:3 0 print_oom:201 Memory allocation failed: size 512 context 0x55b5a7b8
(240807_15:27:01.738)E/TC:3 0 TEE load address @ 0x55b00000
(240807_15:27:01.738)E/TC:3 0 Call stack:
(240807_15:27:01.738)E/TC:3 0  0x0000000055b0ac34
(240807_15:27:01.738)E/TC:3 0  0x0000000055b42754
(240807_15:27:01.738)E/TC:3 0  0x0000000055b3f230
(240807_15:27:01.738)E/TC:3 0  0x0000000055b2e0a0
(240807_15:27:01.738)E/TC:3 0  0x0000000055b2a38c
(240807_15:27:01.738)E/TC:3 0  0x0000000055b2a834
(240807_15:27:01.738)E/TC:3 0  0x0000000055b1fea8
(240807_15:27:01.738)E/TC:3 0  0x0000000055b20030
(240807_15:27:01.738)E/TC:3 0  0x0000000055b11a88
(240807_15:27:01.738)E/TC:3 0  0x0000000055b08120
(240807_15:27:01.738)E/TC:3 0  0x0000000055b038c8
(240807_15:27:01.738)E/TA:  TA_create_operation:1003 Error TEE_AllocateOperation maxKeySize=2048
(240807_15:27:01.738)D/TA:  TA_serialize_rsp_err:484 res: -65524
(240807_15:27:01.738)D/TA:  TA_free_params:25 TA_free_params 25
(240807_15:27:01.738)D/TA:  TA_free_params:25 TA_free_params 25
(240807_15:27:01.738)D/TA:  TA_free_params:25 TA_free_params 25

**Comment by jforissier** [comment]
Hi @klcib508,

It looks like the TEE core heap is too small. Please try increasing `CFG_CORE_HEAP_SIZE`.

**Comment by klcib508** [comment]
yeah,thank yout ,increasing CFG_CORE_HEAP_SIZE  can fix this problem
