### ISSUE TITLE
Mapping of memory for external DT

### ISSUE THREAD

**Issue by jkroon81** [OP-TEE/optee_os#6981]
Hi,

Commit 66763721fe35b96b3b694e16b80240d9b015fa41, "core: add support for transfer list", changed the logic of how the external DT is mapped in memory. Before the change, the DT was unconditionally mapped with:

fdt = core_mmu_add_mapping(MEM_AREA_EXT_DT, phys_dt, CFG_DTB_MAX_SIZE);

After the change, it is first checked if the PA is already mapped and if so gets the address via phys_to_virt().

In my project, the DT is located inside MEM_AREA_SHM_VASPACE, but this area looks more like a placeholder(?), because the phys_to_virt() fails.

Would something like the patch here make sense ?
https://github.com/jkroon81/optee_os/commit/445bc74ded047bd0fba53e5d687c8c8e3942a33b

**Comment by gagachang** [comment]
Hi @jkroon81 , Have your OP-TEE OS applied https://github.com/OP-TEE/optee_os/pull/6914 ?
We've encountered the same issue and fixed it by that PR.
The `MEM_AREA_RES_VASPACE` and `MEM_AREA_SHM_VASPACE` mappings do not have `TEE_MATTR_VALID_BLOCK` attribute.

**Comment by jkroon81** [comment]
Yes, that fix solves the problem for us as well, thanks!

**Comment by gagachang** [comment]
> Yes, that fix solves the problem for us as well, thanks!

You're welcome 👍
