### ISSUE TITLE
PKCS11 doesn't write Persistent keys: Keys removed after reboot

### ISSUE THREAD

**Issue by Muhammadhassan1234** [OP-TEE/optee_os#6982]
Hello Community!

I have just started working on the optee and trying to use optee as a virtual HSM. I am writing keys to Optee using PKCS11 commands like this 

```
pkcs11-tool --module /usr/lib/libckteec.so.0 --init-token --label rauc --so-pin 123412344

pkcs11-tool --module /usr/lib/libckteec.so.0 --label rauc --login --so-pin 12341234 --init-pin --pin 12341234

pkcs11-tool --module /usr/lib/libckteec.so.0 --login --write-object crypt.key.pem --type privkey --label rauc

pkcs11-tool --module /usr/lib/libckteec.so.0 --login --write-object crypt.cert.pem --type cert --label rauc
```

I successfully wrote the keys in optee too and did rauc bundle verification once too using this. but when I rebooted the system, all my data from optee is gone. Can anyone tell me what can be the issue? Does optee write data on ram and not on any persistent storage?

I am using REE_FS for now but no /data/tee folder is creating

**Comment by Muhammadhassan1234** [comment]
Solved using rpmb

**Comment by ancientmodern** [comment]
Hi, I met the same issue, could you give more details on how to solve this? Thanks!

**Comment by Muhammadhassan1234** [comment]
Hi @ancientmodern , There are 2 ways to secure keys in the optee. One is REE FS (Rich Execution environment FileSystem) in which any key you stored in optee is available in ecrypted form in your Linux system. The location of encrypted keys in linux system is usually selected in tee-supplicant software. If this location is some temporary memory like /tmp or /var/run that gets cleared after every reboot, your optee keys will be wiped out after every reboot. So, In order to resolve this and make it permanent for lifetime of product, I made a seperate partition and mounted it on linux and I set the path of encrypted keys in tee-supplicant to that folder so that keys don't get removed after every reboot. Thats a very hgh level overview of things, if you need more detail please let me know.

The second solution is to use rpmb fs which stores keys on a seperate hardware partition in emmc which is good for security reasons also. Here you can study the secure storage in optee. 

https://optee.readthedocs.io/en/latest/architecture/secure_storage.html
