### ISSUE TITLE
optee rpmb secure storage example in u-boot: TEE_ERROR_ITEM_NOT_FOUND

### ISSUE THREAD

**Issue by Muhammadhassan1234** [OP-TEE/optee_os#6986]
Hi Community, 

I am new to optee and working on optee in u-boot these days. I am using the secure storage TA with rpmb as early_TA and trying to write data into it in the userspace and read it from the uboot. 

When I write data into optee from the userspace and read it in userspace too, it gives me the perfect expected data. However, when I try to read the same object from the u-boot, it gives me the `TEE_ERROR_ITEM_NOT_FOUND` errors. The optee_rpmb command is communicating with my TA and even hit the desired read function in TA but from there `TEE_OpenPersistentObject` always return the `TEE_ERROR_ITEM_NOT_FOUND` error in uboot. I even hardcoded the object name in TA in case my TA is sending the wrong name as shown below but it gives the same error. But when I tried to read the object#3 value in userspace with the same TA in optee, it fetches the right data for me

```
	res = TEE_OpenPersistentObject(TEE_STORAGE_PRIVATE_RPMB,
					"object#3", 8,
					TEE_DATA_FLAG_ACCESS_READ |
					TEE_DATA_FLAG_SHARE_READ | TEE_DATA_FLAG_ACCESS_WRITE,
					&object);
	if (res != TEE_SUCCESS) {
		TEE_Free(obj_id);
		TEE_Free(data);
		return res;
	}
```

I have already enabled mmc 0 as FS_DEV  in optee. Further RPMB_FS is enabled in optee and already checked its reading and writing function in userspace. Here are the flags I enabled in u-boot for optee and rpmb

```
+CONFIG_ARM_SMCCC=y
+CONFIG_MMC_RPMB_TRACE=y
+CONFIG_SUPPORT_EMMC_RPMB=y
+CONFIG_CMD_MMC_RPMB=y
+CONFIG_TEE=y
+CONFIG_OPTEE=y
+CONFIG_OPTEE_LIB=y
+CONFIG_OPTEE_TA_AVB=y
+CONFIG_CMD_OPTEE_RPMB=y

```

Please guide me where I am making mistake in accessing rpmb via optee in uboot.

**Comment by jforissier** [comment]
Hi @Muhammadhassan1234,

When you are trying to read data from U-Boot, the linux userspace is not yet up and running, and therefore `tee-supplicant` is not available to service the RPMB requests from OP-TEE. There is work in progress to address this use case, please see https://lore.kernel.org/linux-mmc/20240812133127.865879-5-jens.wiklander@linaro.org/T/.

**Comment by Muhammadhassan1234** [comment]
Hi @jforissier Thank you for your reply. I got your point but I want to ask that android verified boot (AVB) have already done this in uboot. How are they doing it if tee-supplicant or any other equivalent is not available in uboot ?

**Comment by jforissier** [comment]
> Hi @jforissier Thank you for your reply. I got your point but I want to ask that android verified boot (AVB) have already done this in uboot. How are they doing it if tee-supplicant or any other equivalent is not available in uboot ?

Sorry, you are right, there is an equivalent of `tee-supplicant` in U-Boot for the RPMB access. Perhaps more debug traces could help see why `TEE_OpenPersistentObject()` is failing.

**Comment by Muhammadhassan1234** [comment]
@jforissier I enabled the debug log but can't get any important information. Does anyone have a clue about this issue. if some other information is also required, I can provide it too.

**Comment by jforissier** [comment]
Could you please add `DHEXDUMP(object_id, object_id_len);` on entry of `syscall_storage_obj_open()` and post the new traces? Thanks.

**Comment by Muhammadhassan1234** [comment]
@jforissier Thanks for the help. Avb built-in example got worked for me and I modified it according to my demand of work. But I don't know why my custom TA didn't work in uboot. I even debugged at code level but can't find the root cause of problem.
