### ISSUE TITLE
why the TA user address space is limited to 32MB?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#699]
i find in the function core_mmu_get_user_va_range(core/arch/arm/mm/core_mmu_v7.c.), the user va is limited to 32MB, i think that is quit small, can anyone help to explain?

**Comment by jenswi-linaro** [comment]
This limit is per TA. Compared to the TAs I've seen and written so far it's a quite big, but perhaps you have a special use case. It's possible to extend if needed.

**Comment by prime-zeng** [comment]
got it, thank you, maybe i need to extend it, from your point of view, how long will it take to do that?

**Comment by jenswi-linaro** [comment]
Not much, two or three days.
