### ISSUE TITLE
[Build][Device tree] Device tree update ignored due to makefile dependency

### ISSUE THREAD

**Issue by GseoC** [OP-TEE/optee_os#7015]
Hi,

Since commit `mk/compile.mk: separate rule to produce preprocessed dts files` (f0bb1a5a), the device tree pre-processing makefile rule is separated from the device tree blob (DTB) build rule.

The pre-processing rule depends on:

```
$$(dtb-predts-$2): $1 FORCE
	$$(if $$(strip $$(filter-out FORCE, $$?) \
	    $$(filter-out $$(dtb-precmd-$2), $$(dtb-old-precmd-$2)) 	\
	    $$(filter-out $$(dtb-old-precmd-$2), $$(dtb-precmd-$2))), 	\
		$(q)set -e; 						\
		mkdir -p $$(dir $2); 					\
		$(cmd-echo-silent) '  CPP     $$(dtb-predts-$2)'; 	\
		$$(dtb-precmd-$2);					\
		echo "dtb-old-precmd-$2 := $$(subst \",\\\",$$(dtb-precmd-$2))" > \
			$$(dtb-precmd-file-$2) ;\
```

$1 which hold the path to the device tree file.

However, $1 holds the exact name of the device-tree file, and the pre-processing hasn't been done. Therefore, any modification in an included file in the device tree file is not resolved, leading to the device tree not being pre-processed again. Moreover, as the DTB build rule depends on the pre-processing rule:

```
$2: $$(dtb-predts-$2) FORCE
	$$(if $$(strip $$(filter-out FORCE, $$?) \
	    $$(filter-out $$(dtb-cmd-$2), $$(dtb-old-cmd-$2)) 		\
	    $$(filter-out $$(dtb-old-cmd-$2), $$(dtb-cmd-$2))),		\
		$(q)set -e; 						\
		mkdir -p $$(dir $2); 					\
		$(cmd-echo-silent) '  DTC     $$@'; 			\
		$$(dtb-cmd-$2);						\
		echo "dtb-old-cmd-$2 := $$(subst \",\\\",$$(dtb-cmd-$2))" > \
			$$(dtb-cmd-file-$2) ;\
	)
```

=> the DTB is not updated as well.

I do not see an easy solution while keeping the 2 rules. IMO, the device-tree file pre-processing should always be done to handle the different files included in it. Do you have any suggestion?

**Comment by jforissier** [comment]
Hi @GseoC,

When looking at `out/arm-plat-stm32mp1/core/arch/arm/dts/.stm32mp157a-dk1.pre.dts.d` I notice the target is `out/arm-plat-stm32mp1/core/arch/arm/dts/stm32mp157a-dk1.dtb:` but it should be the preprocessed DT instead (`out/arm-plat-stm32mp1/core/arch/arm/dts/stm32mp157a-dk1.pre.dts`) since it is what the preprocessor generates.
This tells me the `-MT` parameter in `dtb-cppflags-$2` is wrong. Could you please try this?

```diff
diff --git a/mk/compile.mk b/mk/compile.mk
index f57f3fd4f..e8d9026b2 100644
--- a/mk/compile.mk
+++ b/mk/compile.mk
@@ -272,7 +272,7 @@ cleanfiles := $$(cleanfiles) $2 \
 
 dtb-cppflags-$2 := -Icore/include/ -x assembler-with-cpp -Ulinux -Uunix \
 		   -E -ffreestanding $$(CPPFLAGS) \
-		   -MD -MF $$(dtb-predep-$2) -MT $2
+		   -MD -MF $$(dtb-predep-$2) -MT $$(dtb-predts-$2)
 
 dtb-dtcflags-$2	:= $$(DTC_FLAGS) -I dts -O dtb -Wno-unit_address_vs_reg \
 		   -d $$(dtb-dep-$2)
```

**Comment by GseoC** [comment]
That is exactly what we've been trying in parallel :D 

I was about to post the comment, it works perfectly, thanks, I'll propose a patch
