### ISSUE TITLE
Subject: Buildroot Error: [package/pkg-generic.mk:273: /optee/out-br/build/host-tar-1.35/.stamp_configured] Error 1

### ISSUE THREAD

**Issue by YuqiDai** [OP-TEE/optee_os#7020]
Hi,

I’m encountering an error while building optee. The error message is as follows:

```shell
make[2]: *** [package/pkg-generic.mk:273: /optee/out-br/build/host-tar-1.35/.stamp_configured] Error 1
make[1]: *** [Makefile:23: _all] Error 2
make[1]: Leaving directory '/optee/out-br'
make: *** [common.mk:343: buildroot] Error 2
```

I use Ubuntu 22.04.4 LTS and follow the guide on [https://optee.readthedocs.io/en/latest/building/gits/build.html#get-and-build-the-solution](https://optee.readthedocs.io/en/latest/building/gits/build.html#get-and-build-the-solution). At step 5, when I ran
```shell
make -j `nproc`
```
this issue happened.

Could someone provide guidance on how to resolve this issue?

Thank you.

**Comment by YuqiDai** [comment]
Right now I'm doubting if it's because I run all the commands on [https://optee.readthedocs.io/en/latest/building/prerequisites.html#prerequisites](https://optee.readthedocs.io/en/latest/building/prerequisites.html#prerequisites) with root privilege.    

Because there is a check didn't pass due to I used root to create the /optee/ directory. I will remove the /optee/ and reinstall it with user rights.

**Comment by YuqiDai** [comment]
# Issue fixed
## 1. Why this issue occurred?    
I used root privilege to curl download op-tee project, this caused the failures like `Permission denied to XXX`. So I `sudo` the shell commands which I shouldn't do. This triggered a checking failure and essentially caused this issue.

## 2. How to resolve?    
Remove the "/optee/" folder then download it with normal user's right again.

## 3. Some tricky things
As a new user of OP-TEE, I read the prerequisite at first, then I convert the docker file into shell script directly which I should not, because I notice there are some slight difference between it and the build steps in the following chapters. And I'm not sure if these difference are also the reasons causing the issue, since I followed the build steps at the second time, and it works perfectly.     

So I suggest the admins to update the prerequisites, or you can add some conspicuous words telling new users to follow the [build steps](https://optee.readthedocs.io/en/latest/building/gits/build.html#get-and-build-the-solution) rather than the [prerequisites](https://optee.readthedocs.io/en/latest/building/prerequisites.html).

**Comment by jenswi-linaro** [comment]
A pull request with the update is welcome. :-)
