### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by manoj23** [OP-TEE/optee_os#7023]
Hello,

The commit 6959626e1621baa41a2b83be367fdfcfa0f8f78a introduces 2 pointers `head_new` and `head_old`.

`head_new` is being set to NULL before being freed at line  1092.
Shouldn't we free `TEE_Free(obj->attributes);` before `obj->attributes = head_old;` at line 1097?

Thank you,

Georges

**Comment by jforissier** [comment]
Hello @manoj23,

> Shouldn't we free `TEE_Free(obj->attributes);` before `obj->attributes = head_old;` at line 1097?

Yes. Could you please create a PR for this? Thanks!

**Comment by manoj23** [comment]
Hello @jforissier, I created the PR.
