### ISSUE TITLE
Support for changing the secure storage provisioning path.

### ISSUE THREAD

**Issue by alfredpchacon** [OP-TEE/optee_os#7024]
Hi,
We were working with the secure storage API and want to check if it's possible to change the path where the secure objects are stored, but we didn't find it on the docs. And how and what needs to be modified? We are working on Ti's Jacinto 7 board. 
Thanks.

**Comment by ivila** [comment]
If your path means **the ree path in the linux**, then pass an argument(the **fs-parent-path**) when start tee-supplicant should work.
```shell
tee-supplicant --help
Usage: tee-supplicant [options] [<device-name>]
        -h, --help: this help
        -d, --daemonize: run as a daemon (fork and return after child has opened the TEE device or on error)
        -f, --fs-parent-path: secure fs parent path [/data/tee]
        -l, --ta-path: TA load path
        -t, --ta-dir: TAs dirname under /lib [optee_armtz] (deprecated, cannot be used with --ta-path)
        -p, --plugin-path: plugin load path [/usr/lib/tee-supplicant/plugins/]
        -r, --rpmb-cid: RPMB device identification register (CID) in hexadecimal
```

**Comment by alfredpchacon** [comment]
Got it, so it's on the client side not the kernel side of optee. Thanks for the response, I will give it a try,
