### ISSUE TITLE
 Question about rockchip board support

### ISSUE THREAD

**Issue by TephrocactusMYC** [OP-TEE/optee_os#7036]
Hi experts,

In the official documentation under [Platforms supported](https://optee.readthedocs.io/en/latest/general/platforms.html), I noticed that rk3399 is listed as a supported platform. I'm wondering if OP-TEE OS can run on all development boards that use the rk3399 chip, such as Orange Pi 4B, Orange Pi RK3399, and NanoPi M4. I understand this might be a basic question, but I'm still unsure. 

Additionally, in the [Device specific information](https://optee.readthedocs.io/en/latest/building/devices/index.html), I only found details for the ROCK Pi 4, with no mention of other rk3399-based boards. If those boards are not supported, would I need to port OP-TEE OS myself? Given that both TF-A and OP-TEE already support rk3399, I assume the porting process wouldn’t be too difficult—am I correct in this assumption?

Also, I'd like to know if the same answer applies to other Rockchip SoCs, such as the rk322x. Thanks in advance for your help!

**Comment by jforissier** [comment]
Hello @TephrocactusMYC,

You are right, it is more precisely RockPi 4 that is supported than rk3399 in general, but it should be easy enough to port OP-TEE to other rk3399-based boards. Mainly change some physical addresses for peripherals (UART...) and load address etc.

Other Rockchip SoCs would probably be a bit more work especially if new drivers are needed, but as you can see if you look at commits introducing new board, it is a small amount of code most of the time.

**Comment by TephrocactusMYC** [comment]
Hi @jforissier 
Thanks a lot. If I make any progress, I might initiate a commit.
