### ISSUE TITLE
OP-TEE on ARMv8 aarch64 question

### ISSUE THREAD

**Issue by louisyang1977** [OP-TEE/optee_os#704]
Hi jenswi,
According to issues https://github.com/OP-TEE/optee_os/issues/576

You just mention :
_SMCs are trapped at EL3 in Aarch64. OP-TEE only handles Secure EL1 and EL0 in Aarch64. EL3 is handled by ARM Trusted Firmware. ARM-TF contains a Dispatcher which corresponds to the Secure Monitor used in ARMv7/Aarch32._

And i have additional the question about op-tee os : 
Should i run the op-tee os on aarch64 or aarch32 (armv8 a53) or both ??
According to the OP-TEE slide on the slideshare site, it mentions the OP-TEE is running at aarch32 on armv8, is that correct ??
I have this question because currently we just do like the slide said, but we have problem bring up the OP-TEE at aarch32 on armv8.
(we have mmu init problem when op-tee os runs at aarch32 armv8, but the old platform armv7 is okay)
If you can clarify my concern, that would be great.

Thanks !!

**Comment by jenswi-linaro** [comment]
On ARMv8 you can run OP-TEE in either Aarch64 or Aarch32 it's a config option.

As for the mmu init problem, not easy to give any good advice there.

**Comment by louisyang1977** [comment]
Thanks jenswi, it's useful information.
