### ISSUE TITLE
Memory Access Issue while using Customized User Space Page Table in PTA

### ISSUE THREAD

**Issue by Xander-C** [OP-TEE/optee_os#7045]
## Environment
board: IMX-6q with Cortex-A9 Core
optee version: i.MX optee os 3.10.0 (2020-08-21)

## Objective
I am writing a PTA in OPTEE that utilizes the [core_mmu_set_user_map()](https://github.com/OP-TEE/optee_os/blob/3.10.0/core/arch/arm/mm/core_mmu_v7.c#L643) function to modify the ttbr0 register for mapping a custom page table to a low virtual address space. The custom page table use section to map physical memory similar to a TA.

my 1st level descriptors: 
```
    for (size_t l1_i = 0; l1_i < 88; l1_i++) {
        l1_pt[l1_i + 1] = (REGION_START_PA + l1_i * 0x100000) | 
                    L1_SECTIOE_DESC | L1_SECTIOE_AP_FULL_ACCESS | 
                    L1_SECTION_SHARED | L1_SECTION_NG;
    }
    return virt_to_phys(uiee_l1_pt);
```

## Issue Encountered
After setting the ttbr0 register, accessing addresses within the custom page table translates some data correctly but encounters mapping errors (or something similar?) with a 32-byte granule. 
those incorrect 32-byte granules have a default value of 0 instead of the expected content from the physical memory page. These 0-valued addresses can be written to successfully, and subsequent reads display the written content, although this write operation does not affect physical memory.
```
I/TC: 0x1510258: 0xe3a00001
I/TC: 0x151025c: 0xe3a01002
I/TC: 0x1510260: 0x0
I/TC: 0x1510264: 0x0
I/TC: 0x1510268: 0x0
I/TC: 0x151026c: 0x0
I/TC: 0x1510270: 0x0
I/TC: 0x1510274: 0x0
I/TC: 0x1510278: 0x0
I/TC: 0x151027c: 0x0
I/TC: 0x1510280: 0xe3013145
I/TC: 0x1510284: 0xe3a07047
I/TC: 0x1510288: 0xe3a06000
I/TC: 0x151028c: 0xef000000
I/TC: 0x1510290: 0xe3a07047
I/TC: 0x1510294: 0xe3a06000
I/TC: 0x1510298: 0xef000000
I/TC: 0x151029c: 0xe3a07000
I/TC: 0x15102a0: 0x0
...... All Zero......
I/TC: 0x15102bc: 0x0
I/TC: 0x15102c0: 0xe3a06000
...... Correct Value......
I/TC: 0x15102e0: 0xe3a06000
```
Write Test:
```
I/TC: 0x1510258: 0xe3a00001
I/TC: 0x151025c: 0xe3a01002
I/TC: 0x1510260: 0x114514
..... Correct Written Content (0x114514) ......
I/TC: 0x151027c: 0x114514
I/TC: 0x1510280: 0xe3013145
I/TC: 0x1510284: 0xe3a07047
```
Mapping physical memory to OPTEE's kernel space using the core_mmu_add_mapping() function allows correctly access to physical memory.
```
I/TC: 0x91810258: 0xe3a00001
I/TC: 0x9181025c: 0xe3a01002
I/TC: 0x91810260: 0xe3a02003
I/TC: 0x91810264: 0xe3013145
I/TC: 0x91810268: 0xe3a07047
I/TC: 0x9181026c: 0xe3a06000
I/TC: 0x91810270: 0xef000000
I/TC: 0x91810274: 0xe3a00001
I/TC: 0x91810278: 0xe3a01002
I/TC: 0x9181027c: 0xe3a02003
I/TC: 0x91810280: 0xe3013145
I/TC: 0x91810284: 0xe3a07047
I/TC: 0x91810288: 0xe3a06000
```

My page table utilizes Section Descriptors, and any errors encountered should occur in 1MB increments. However, the current occurrence of errors in 32-byte increments. Any ideas what could cause this?

It seems that the issue might be related to the cache. However, even after incorporating the following operations in core_mmu_set_user_map(), the problem persists.
```
tlbi_all();
icache_inv_all();
dcache_op_all(DCACHE_OP_CLEAN_INV);
isb();
dsb();
dmb();
```

**Comment by jenswi-linaro** [comment]
Invalid mmu mappings lead to errors hard to diagnose. I'd recommend trying this on QEMU instead. If you have the same kind of problem there you can debug QEMU itself to see what's going on.

**Comment by Xander-C** [comment]
The problem could not be reproduced after porting to QEMU, we have decided to use QEMU instead. Thank you very much.
