### ISSUE TITLE
 qemu-system-arm: -s: Failed to bind socket: Address already in use

### ISSUE THREAD

**Issue by yingkailiang** [OP-TEE/optee_os#706]
Hi, 
I am doing some research related to TrustZone and I want to test optee_os on QEMU. When I run command "make all run" in build folder, following error message shows up:

QEMU 2.1.50 monitor - type 'help' for more information
(qemu) qemu-system-arm: -s: Failed to bind socket: Address already in use
make[1]: *** [run-only] Error 1
make[1]: Leaving directory `/PATH/devel/optee/build'
make: *** [run] Error 2

Any idea how to address this issue? Thanks

**Comment by jforissier** [comment]
A previous instance of QEMU must still be running.

**Comment by yingkailiang** [comment]
Problem solved. Thanks for your quick response.
