### ISSUE TITLE
How to run linux kernel with optee on QEMU?

### ISSUE THREAD

**Issue by yingkailiang** [OP-TEE/optee_os#707]
I have a question about how to run linux kernel with optee on qemu. I finish compiled optee_os source code with qemu option on my host machine. 
When I run "make all run" , I expect to see a linux kernel boots in normal world and optee os boots in secure world. 
The part I don't understand is, when I run the command, both terminal only executes same socket program but does not boot up any linux kernel. Following screenshot is what I saw. 
![screen shot 2016-03-20 at 3 38 42 pm](https://cloud.githubusercontent.com/assets/3341468/13906639/e97b3fce-eeb1-11e5-857e-bca57b9e42c5.png)

Can anyone provide some guideline? If I want to run a linux kernel which includes optee_os, what additional steps should I do? Thanks in advance.

**Comment by jforissier** [comment]
You must type `c` to continue.
https://github.com/OP-TEE/build/blob/master/qemu.mk#L169

**Comment by yingkailiang** [comment]
@jforissier Thanks for your answer. Problem solved

**Comment by saurabhsamanta** [comment]
When I am tying c noting is happening. I am tying c on (qemu) prompt.

**Comment by vchong** [comment]
As answered in #1476.
