### ISSUE TITLE
Does optee-os have an LTS version?

### ISSUE THREAD

**Issue by xtaens** [OP-TEE/optee_os#7071]
The update of 4 versions a year is a bit fast, and the actual project cannot be upgraded to the new version in time

**Comment by jbech-linaro** [comment]
Hi,

Currently don’t have any OP-TEE LTS branches. We’ve done a pre-study, with conclusion that we’re ready to spin-up LTS when asked for. We see (at least) two different ways to do LTS:
- Community driven and funded LTS = Fully open and available to anyone.
- Vendor specific LTS (closed) = Open LTS + vendor patches + eventual integration testing. This likely will be done on a service contract of some sort by companies with in-depth knowledge of OP-TEE.

At Linaro we've discussed both. The former is most interesting to the community as such, but will require funding. The latter might be more interesting to individual companies, but is of little or no value to the open community. If you/your company is interested or have any suggestions, feel free to talk to us at [Linaro](https://www.linaro.org/contact). If you do so, please refer to this thread.

**Comment by xtaens** [comment]
> Hi,
> 
> Currently don’t have any OP-TEE LTS branches. We’ve done a pre-study, with conclusion that we’re ready to spin-up LTS when asked for. We see (at least) two different ways to do LTS:
> 
> * Community driven and funded LTS = Fully open and available to anyone.
> * Vendor specific LTS (closed) = Open LTS + vendor patches + eventual integration testing. This likely will be done on a service contract of some sort by companies with in-depth knowledge of OP-TEE.
> 
> At Linaro we've discussed both. The former is most interesting to the community as such, but will require funding. The latter might be more interesting to individual companies, but is of little or no value to the open community. If you/your company is interested or have any suggestions, feel free to talk to us at [Linaro](https://www.linaro.org/contact). If you do so, please refer to this thread.

Got it, thanks

**Comment by xtaens** [comment]
thanks
