### ISSUE TITLE
I'm the one main Issue with Implementing CAN Bus Communication in CA on OP-TEE for Raspberry Pi 3Btaining the RPi3 build for OP-TEE, last time I tried was at the 4.0.0 release. Back then [it was working as expected](https://github.com/OP-TEE/optee_os/pull/6341#pullrequestreview-1687824736). Unfortunately, we don't have the RPi3 on a CI loop, but I can give it a try again to see whether there is a new regression not seen before.

### ISSUE THREAD

**Issue by pengxinyuanaaa** [OP-TEE/optee_os#7076]
I am currently working on a project involving a custom OP-TEE system on a Raspberry Pi 3B with Ubuntu. I am trying to develop my own Client Application (CA) that includes CAN bus communication. I attempted to implement the CAN communication logic in the CA part of the code, but unfortunately, I couldn’t get it to work as expected.

Here’s a brief summary of the issue I’m facing:

System Setup: Raspberry Pi 3B with Ubuntu and OP-TEE.
Goal: Implement a CAN bus communication in the CA to send and receive messages.
Problem: The CAN bus communication code compiles successfully, but when I run the CA, it fails to communicate with the CAN device. No errors are logged, but the CAN messages are not being transmitted or received as intended.I am unsure whether the issue is related to the way OP-TEE manages hardware resources or if it’s a limitation of integrating CAN communication in the CA. Could you provide any insights or suggest a better approach for implementing CAN bus communication within the OP-TEE Client Application?

**Comment by ivila** [comment]
First of all, I don't think there is anything relative with OP-TEE, the Client Application is just a normal linux program, you can do whatever you want to like a normal linux program.
Secondly, you should provide more information if you are really looking for help, the only thing I can get for now is that **there has a problem**, what I don't know what and how.
