### ISSUE TITLE
Error occurs during high-frequency calls in optee 4.0

### ISSUE THREAD

**Issue by zwb-233** [OP-TEE/optee_os#7077]
Hi,
I’m currently using OP-TEE 4.0.0 on the Hikey960, and I need to frequently call two functions from a TA within a short period of time. At the moment, I need to call each function around 100 times within 15 seconds to test.

However, sometimes I encounter the following output, :

```text
E/LD:    Status of TA eff27aea-8019-8f98-4963-406233b51e44
E/LD:     arch: aarch64
E/LD:    region  0: va 0x80005000 pa 0x52801000 size 0x002000 flags rw-s (ldelf)
E/LD:    region  1: va 0x80007000 pa 0x52803000 size 0x008000 flags r-xs (ldelf)
E/LD:    region  2: va 0x8000f000 pa 0x5280b000 size 0x001000 flags rw-s (ldelf)
E/LD:    region  3: va 0x80010000 pa 0x5280c000 size 0x004000 flags rw-s (ldelf)
E/LD:    region  4: va 0x80014000 pa 0x52810000 size 0x001000 flags r--s
E/LD:    region  5: va 0x8008e000 pa 0x00001000 size 0x01c000 flags r-xs [0]
E/LD:    region  6: va 0x800aa000 pa 0x0001d000 size 0xc805000 flags rw-s [0]
E/LD:    region  7: va 0x8c8af000 pa 0x5f032000 size 0x1e01000 flags rw-s (stack)
E/LD:    region  8: va 0x8e6b0000 pa 0x3ee01000 size 0x549000 flags rw-- (param)
E/LD:     [0] eff27aea-8019-8f98-4963-406233b51e44 @ 0x8008e000
E/LD:    Call stack:
E/LD:     0x8009066c
E/LD:     0x80099464
E/LD:     0x8009062c
E/LD:     0x3f5098d03f13e884
D/TC:? 000 user_ta_enter:201 tee_user_ta_enter: TA panicked with code 0xffff300f
D/TC:? 000 release_ta_ctx:668 Releasing panicked TA ctx
D/TC:? 000 tee_ta_close_session:468 csess 0x506a80d0 id 1
D/TC:? 000 tee_ta_close_session:487 Destroy session
D/TC:? 000 tee_ta_close_session:468 csess 0x506a81c0 id 2
D/TC:? 000 tee_ta_close_session:487 Destroy session
D/TC:? 000 tee_ta_invoke_command:796 Error: ffff3024 of 3
D/TC:? 000 tee_ta_invoke_command:796 Error: ffff3024 of 3
```

These outputs don’t always occur, and I don't think it is related to my code.

To debug this further, I wrote a test TA that simply allocates and releases the same size of secure memory during each call. The same output occurred.

 As an optimization, I modified the code to allocate a fixed amount of memory once, and then use `TEE_MemFill` to reset it instead of allocating and releasing it. This optimization worked well until I reduced the interval between serial TA calls, at which point the error returned.

Currently, my workaround is to add a 5ms delay between each call, which prevents the issue, but I would like to find a more robust solution. Do you have any suggestions on how to handle this more efficiently?

Thank you!

**Comment by ivila** [comment]
@zwb-233 Maybe you can check this first: https://optee.readthedocs.io/en/latest/debug/abort_dumps.html, to see what's the reason that result in the abortion.

**Comment by zwb-233** [comment]
I encountered the error three times during execution and translated these errors, but the locations where the errors occurred were different each time, and the corresponding line numbers were also different. In the second time, the error even corresponded to the declaration of a `uint32_t` variable. @ivila

**Comment by ivila** [comment]
@zwb-233 do you see this error in your console: `stack smashing detected`,
Or could you please submit a minimum reproduce program?

**Comment by zwb-233** [comment]
[secure_storage.zip](https://github.com/user-attachments/files/17372095/secure_storage.zip)

I did not see `stack smashing detected` in the console.

I tried to write a minimum reproduce program that simulates most of my current operations, except for the interaction with PTA. This program only confirms that frequent memory initialization and release can lead to errors, but I haven't encountered the exact error I'm currently experiencing.

It is worth noting that I increased the secure memory of OP-TEE, and this issue might not occur under the default configuration.

When I modified the data acquisition from PTA to directly assigning default values in the TA, the intermittent error in my program always occurs at the end of the function (`}`), and I saw a `stack smashing detected` message and the error code `0xffff300f`.

**Comment by zwb-233** [comment]
I understand now that the error occurred because my communication with 'ta' was managed and completed through a thread pool, but I did not limit the number of communications. As the speed increased, the thread pool sent more requests to ta's waiting queue, resulting in the error. Thank for help.
