### ISSUE TITLE
QEMU build kernel panic

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#708]
I followed the repo instructions in optee_os to build for qemu. At the end when I type 'c', the system gives me two terminals: Normal and Secure. However while booting the normal world, I get the following:

![image](https://cloud.githubusercontent.com/assets/3120140/13910802/ea64c4f4-eee4-11e5-8c5d-69fba210e2fe.png)

Also I was looking at the "run" target in qemu.mk, I was wondering how does the virtual disk for qemu get passed in? Where is it? Thanks. 

P.S. Also would I be able to build Trusted Applications and client Applications in QEMU just as if I had a board supporting TrustZone? Just wondering about the limitations between say if I was to develop on a HiKey board and to develop on QEMU.

**Comment by peterfeifanchen** [comment]
I resolved this issue by switching to the toolchain in the repo rather than my own.

**Comment by vchong** [comment]
Is your own toolchain built by yourself, downloaded from non-Linaro website, or downloaded from another Linaro website? If from Linaro, can you please provide the link to it? We need to know whenever one of our toolchains breaks a build. Thanks!

**Comment by peterfeifanchen** [comment]
The tools were from the HiKey OPTEE setup instructions [here](https://github.com/96boards/documentation/wiki/HiKeyOPTEE)

which was from Linaro I believe.

**Comment by vchong** [comment]
Ok. This is not a toolchain issue then. HiKey can be a mixture of 32- and/or 64-bit build, but Qemu is only 32-bit so far I believe, so you need to make sure to use the proper toolchain for your build. Thanks for the info anyway!
