### ISSUE TITLE
ldelf issue when using -Wl,--hash-style=sysv

### ISSUE THREAD

**Issue by gyuri-szing** [OP-TEE/optee_os#7082]
Hi,

I am using OP-TEE SHA:`136cc65fc184cab44efa3822f195e9f8e43c60eb` (4.4.0-rc1) and ldelf fails to load my SP binary. 
The compile is `aarch64-poky-linux-gcc (GCC) 13.3.0`.

The problem can be tracked back to this line: https://github.com/OP-TEE/optee_os/blob/136cc65fc184cab44efa3822f195e9f8e43c60eb/ldelf/ta_elf_rel.c#L203

It seems `nbuckets` is 0 and `bucket` array will be indexed out of bounds, which causes a data abort.

Content of the `.hash` section it this:
```
# objdump -s -j .hash spm-test1_5c9edbc3-7b3a-4367-9f83-7c191ae86a37

spm-test1_5c9edbc3-7b3a-4367-9f83-7c191ae86a37:     file format elf64-little

Contents of section .hash:
 1acf0 00000000 03000000 00000000 00000000  ................
 1ad00 00000000                             ....            
```

Using `-Wl,--hash-style=gnu` solves the issue.

Allying the following patch solves the issue too:
```
diff --git a/ldelf/ta_elf_rel.c b/ldelf/ta_elf_rel.c
index bc895e84d..39d0c7e25 100644
--- a/ldelf/ta_elf_rel.c
+++ b/ldelf/ta_elf_rel.c
@@ -198,6 +198,9 @@ static TEE_Result resolve_sym_helper(const char *name, vaddr_t *val,
 		uint32_t *bucket = &hashtab[2];
 		uint32_t *chain = &bucket[nbuckets];
 
+		if (!nbuckets)
+			return TEE_ERROR_ITEM_NOT_FOUND;
+
 		hash = elf_hash(name);
 
 		for (n = bucket[hash % nbuckets]; n; n = chain[n]) {
```

The crash dump:
```
D/TC:0 0 abort_handler:562 [abort] abort in User mode (TA will panic)
E/TC:0 0 
E/TC:0 0 User mode data-abort at address 0x69df0908 (translation fault)
E/TC:0 0  esr 0x92000006  ttbr0 0xc00000616f000   ttbr1 0x00000000   cidr 0x0
E/TC:0 0  cpu #0          cpsr 0x000003c0
E/TC:0 0  x0  000000000a75eb04 x1  0000000000000000
E/TC:0 0  x2  0000000000000000 x3  000000000a75eb04
E/TC:0 0  x4  0000000040006e98 x5  0000000000000000
E/TC:0 0  x6  0000000000000011 x7  0000000040013ea0
E/TC:0 0  x8  0000000000000006 x9  000000000001b000
E/TC:0 0  x10 0000000000000011 x11 0000000000000000
E/TC:0 0  x12 0000000000000000 x13 0000000040006c78
E/TC:0 0  x14 0000000000000000 x15 0000000000006ffd
E/TC:0 0  x16 000000000601ac98 x17 0000000000000000
E/TC:0 0  x18 0000000000006ffd x19 0000000040013ea0
E/TC:0 0  x20 0000000040006f40 x21 0000000000000000
E/TC:0 0  x22 0000000040075cf8 x23 0000000000000000
E/TC:0 0  x24 0000000040013ea0 x25 000000004000e159
E/TC:0 0  x26 0000000000000003 x27 0000000000000000
E/TC:0 0  x28 0000000000000000 x29 0000000040006e30
E/TC:0 0  x30 000000004000aa68 elr 000000004000a838
E/TC:0 0  sp_el0 0000000040006e30
E/TC:0 0  region  0: va 0x0000000040000000 pa 0x0000000006002000 size 0x002000 flags ---R-X
E/TC:0 0  region  1: va 0x0000000040002000 pa 0x0000000006160000 size 0x001000 flags ---RW-
E/TC:0 0  region  2: va 0x0000000040004000 pa 0x000000000631e000 size 0x001000 flags ---RW-
E/TC:0 0  region  3: va 0x0000000040005000 pa 0x000000000631f000 size 0x002000 flags rw-RW-
E/TC:0 0  region  4: va 0x0000000040007000 pa 0x0000000006321000 size 0x008000 flags r-x---
E/TC:0 0  region  5: va 0x000000004000f000 pa 0x0000000006329000 size 0x001000 flags rw-RW-
E/TC:0 0  region  6: va 0x0000000040010000 pa 0x000000000632a000 size 0x004000 flags rw-RW-
E/TC:0 0  region  7: va 0x0000000040014000 pa 0x000000000632e000 size 0x001000 flags r--R--
E/TC:0 0  region  8: va 0x000000004005b000 pa 0x000000000632f000 size 0x01b000 flags r-xR--
E/TC:0 0  region  9: va 0x0000000040076000 pa 0x000000000634a000 size 0x00d000 flags rw-RW-
E/TC:0 0 ldelf_init_with_ldelf:148 ldelf panicked
E/TC:0 0 sp_open_session:623 Failed loading SP  0xffff0000
E/TC:0 0 sp_init_all:1855 Failed initializing SP(5c9edbc3-7b3a-4367-9f83-7c191ae86a37) err:0xffff3024
E/TC:0 0 Panic at /usr/src/debug/optee-os/4.1.0/core/arch/arm/kernel/secure_partition.c:1858 <sp_init_all>
E/TC:0 0 TEE load address @ 0x6000000
E/TC:0 0 Call stack:
E/TC:0 0  0x0600d850
E/TC:0 0  0x0601b7ac
E/TC:0 0  0x0600a63c
E/TC:0 0  0x0601d594
E/TC:0 0  0x0600d4bc
``

**Comment by jforissier** [comment]
Hi @gyuri-szing,

> Hi,
> 
> I am using OP-TEE SHA:`136cc65fc184cab44efa3822f195e9f8e43c60eb` (4.4.0-rc1) and ldelf fails to load my SP binary. The compile is `aarch64-poky-linux-gcc (GCC) 13.3.0`.
> 
> The problem can be tracked back to this line:
> 
> https://github.com/OP-TEE/optee_os/blob/136cc65fc184cab44efa3822f195e9f8e43c60eb/ldelf/ta_elf_rel.c#L203
> 
> It seems `nbuckets` is 0 and `bucket` array will be indexed out of bounds, which causes a data abort.
> 
> Content of the `.hash` section it this:
> 
> ```
> # objdump -s -j .hash spm-test1_5c9edbc3-7b3a-4367-9f83-7c191ae86a37
> 
> spm-test1_5c9edbc3-7b3a-4367-9f83-7c191ae86a37:     file format elf64-little
> 
> Contents of section .hash:
>  1acf0 00000000 03000000 00000000 00000000  ................
>  1ad00 00000000                             ....            
> ```

That's a strange .hash section. I can't make much sense of it... if I refer to http://www.sco.com/developers/gabi/latest/ch5.dynamic.html#hash it means `nbuckets` is 0 and `nchains` is 3, and all entries in the chains table point to symbol 0.
Does the executable contain a dynamic symbol table (`.dynsym`)? I suspect it does and its size is 3 (since the `nchain` entry in `.hash` is 3 and the number of symbol table entries should equal `nchain`). But then why the `.hash` section would not allow to find them? (I mean, especially symbol 1 and 2).

> Using `-Wl,--hash-style=gnu` solves the issue.

Makes sense. In that case we use a different algorithm in resolve_sym_helper().

> 
> Allying the following patch solves the issue too:
> 
> ```
> diff --git a/ldelf/ta_elf_rel.c b/ldelf/ta_elf_rel.c
> index bc895e84d..39d0c7e25 100644
> --- a/ldelf/ta_elf_rel.c
> +++ b/ldelf/ta_elf_rel.c
> @@ -198,6 +198,9 @@ static TEE_Result resolve_sym_helper(const char *name, vaddr_t *val,
>  		uint32_t *bucket = &hashtab[2];
>  		uint32_t *chain = &bucket[nbuckets];
>  
> +		if (!nbuckets)
> +			return TEE_ERROR_ITEM_NOT_FOUND;
> +

Looks reasonable, although we might also reject the binary as non-compliant in check_hashtab() perhaps. If it happens to be the case that it is non-compliant, of course.

>  		hash = elf_hash(name);
>  
>  		for (n = bucket[hash % nbuckets]; n; n = chain[n]) {
> ```
> 
> The crash dump:
> 
> ```
> D/TC:0 0 abort_handler:562 [abort] abort in User mode (TA will panic)
> E/TC:0 0 
> E/TC:0 0 User mode data-abort at address 0x69df0908 (translation fault)
> E/TC:0 0  esr 0x92000006  ttbr0 0xc00000616f000   ttbr1 0x00000000   cidr 0x0
> E/TC:0 0  cpu #0          cpsr 0x000003c0
> E/TC:0 0  x0  000000000a75eb04 x1  0000000000000000
> E/TC:0 0  x2  0000000000000000 x3  000000000a75eb04
> E/TC:0 0  x4  0000000040006e98 x5  0000000000000000
> E/TC:0 0  x6  0000000000000011 x7  0000000040013ea0
> E/TC:0 0  x8  0000000000000006 x9  000000000001b000
> E/TC:0 0  x10 0000000000000011 x11 0000000000000000
> E/TC:0 0  x12 0000000000000000 x13 0000000040006c78
> E/TC:0 0  x14 0000000000000000 x15 0000000000006ffd
> E/TC:0 0  x16 000000000601ac98 x17 0000000000000000
> E/TC:0 0  x18 0000000000006ffd x19 0000000040013ea0
> E/TC:0 0  x20 0000000040006f40 x21 0000000000000000
> E/TC:0 0  x22 0000000040075cf8 x23 0000000000000000
> E/TC:0 0  x24 0000000040013ea0 x25 000000004000e159
> E/TC:0 0  x26 0000000000000003 x27 0000000000000000
> E/TC:0 0  x28 0000000000000000 x29 0000000040006e30
> E/TC:0 0  x30 000000004000aa68 elr 000000004000a838
> E/TC:0 0  sp_el0 0000000040006e30
> E/TC:0 0  region  0: va 0x0000000040000000 pa 0x0000000006002000 size 0x002000 flags ---R-X
> E/TC:0 0  region  1: va 0x0000000040002000 pa 0x0000000006160000 size 0x001000 flags ---RW-
> E/TC:0 0  region  2: va 0x0000000040004000 pa 0x000000000631e000 size 0x001000 flags ---RW-
> E/TC:0 0  region  3: va 0x0000000040005000 pa 0x000000000631f000 size 0x002000 flags rw-RW-
> E/TC:0 0  region  4: va 0x0000000040007000 pa 0x0000000006321000 size 0x008000 flags r-x---
> E/TC:0 0  region  5: va 0x000000004000f000 pa 0x0000000006329000 size 0x001000 flags rw-RW-
> E/TC:0 0  region  6: va 0x0000000040010000 pa 0x000000000632a000 size 0x004000 flags rw-RW-
> E/TC:0 0  region  7: va 0x0000000040014000 pa 0x000000000632e000 size 0x001000 flags r--R--
> E/TC:0 0  region  8: va 0x000000004005b000 pa 0x000000000632f000 size 0x01b000 flags r-xR--
> E/TC:0 0  region  9: va 0x0000000040076000 pa 0x000000000634a000 size 0x00d000 flags rw-RW-
> E/TC:0 0 ldelf_init_with_ldelf:148 ldelf panicked
> E/TC:0 0 sp_open_session:623 Failed loading SP  0xffff0000
> E/TC:0 0 sp_init_all:1855 Failed initializing SP(5c9edbc3-7b3a-4367-9f83-7c191ae86a37) err:0xffff3024
> E/TC:0 0 Panic at /usr/src/debug/optee-os/4.1.0/core/arch/arm/kernel/secure_partition.c:1858 <sp_init_all>
> E/TC:0 0 TEE load address @ 0x6000000
> E/TC:0 0 Call stack:
> E/TC:0 0  0x0600d850
> E/TC:0 0  0x0601b7ac
> E/TC:0 0  0x0600a63c
> E/TC:0 0  0x0601d594
> E/TC:0 0  0x0600d4bc
> ``
> ```

**Comment by gyuri-szing** [comment]
> Does the executable contain a dynamic symbol table (.dynsym)? I suspect it does and its size is 3 (since the nchain entry in .hash is 3 and the number of symbol table entries should equal nchain).

`.dynsim` is indeed there and as suspected it contains three entries. Cutout from readelf output:
```
[Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
[ 6] .dynsym           DYNSYM           000000000001b7d0  0001c7d0
       0000000000000048  0000000000000018   A       7     3     8
...
Symbol table '.dynsym' contains 3 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000000000     0 SECTION LOCAL  DEFAULT    1 .sp_head
     2: 000000000001c130     0 SECTION LOCAL  DEFAULT   14 .data
```
And this is the content of `.dynsym`:
```
Contents of section .dynsym:
 1b7d0 00000000 00000000 00000000 00000000  ................
 1b7e0 00000000 00000000 00000000 03000100  ................
 1b7f0 00000000 00000000 00000000 00000000  ................
 1b800 00000000 03000e00 30c10100 00000000  ........0.......
 1b810 00000000 00000000                    ........        
 ```

> But then why the .hash section would not allow to find them?

No clue :) 

> Looks reasonable, although we might also reject the binary as non-compliant in check_hashtab() perhaps. If it happens to be the case that it is non-compliant, of course.

The binary loads and executes fine with the above fix applied. But SPs load different than TAs (sp_head must be at 0x0, and entry point is used form elf header, so no symbol lookup is needed) and I am not sure how and if this affects shared library support for TAs. I assume TA support is checked by the CI, but is shared library support checked too?

**Comment by jforissier** [comment]
> The binary loads and executes fine with the above fix applied. But SPs load different than TAs (sp_head must be at 0x0, and entry point is used form elf header, so no symbol lookup is needed) and I am not sure how and if this affects shared library support for TAs. I assume TA support is checked by the CI, but is shared library support checked too?

Yes, xtest 1022 does test shared library support via dlopen()/dlsym(). We could also add `make -j$(nproc) check CFG_ULIBS_SHARED=y` to the QEMUv8 job in `.github/workflows/ci.yml` to further test the "usual" shared library support (i.e., library load and symbol resolution as the TA is loaded). I will open a PR for this.

Can you open a PR for the fix you proposed?

**Comment by jforissier** [comment]
> We could also add `make -j$(nproc) check CFG_ULIBS_SHARED=y` to the QEMUv8 job in `.github/workflows/ci.yml` to further test the "usual" shared library support (i.e., library load and symbol resolution as the TA is loaded). I will open a PR for this.

https://github.com/OP-TEE/optee_os/pull/7084
