### ISSUE TITLE
error when replace tomcrypt with mbedtls

### ISSUE THREAD

**Issue by huzai9527** [OP-TEE/optee_os#7092]
when i try to use mbedtls without tomcrypt，code change like below
![image](https://github.com/user-attachments/assets/53ab90aa-2ebd-42aa-85b6-43e96dae94ac)

then，i compile tee，error occurs
![image](https://github.com/user-attachments/assets/f24984ea-c472-40f1-b1d7-5ef56117fb9c)

**Comment by jenswi-linaro** [comment]
You've done something more because it works for me at the latest.

**Comment by guojh2xiaopeng** [comment]
I encountered the same problem, when I config CFG_CRYPTO_WITH_CE :=y @jenswi-linaro

**Comment by guojh2xiaopeng** [comment]
I also meet that problem , when I  change code as @huzai9527  , other I had config  CFG_CRYPTO_WITH_CE := y.  @jenswi-linaro

**Comment by jenswi-linaro** [comment]
Still works for me with `CFG_CRYPTOLIB_NAME=mbedtls CFG_CRYPTOLIB_DIR=lib/libmbedtls CFG_CRYPTO_WITH_CE=y` for the qemu_armv8a variant. I can't help you if I can't reproduce the compile error.

**Comment by guojh2xiaopeng** [comment]
I test found that, when add config  as follow , It build pass.  can you show me your crypto.mk?

`diff --git a/core/crypto.mk b/core/crypto.mk
index ac651eeb9..693c7820e 100644
--- a/core/crypto.mk
+++ b/core/crypto.mk
@@ -233,6 +233,7 @@ _CFG_CORE_LTC_SHA256_DESC := $(CFG_CRYPTO_DSA)
 _CFG_CORE_LTC_SHA384_DESC := $(CFG_CRYPTO_DSA)
 _CFG_CORE_LTC_SHA512_DESC := $(CFG_CRYPTO_DSA)
 _CFG_CORE_LTC_XTS := $(CFG_CRYPTO_XTS)
+**_CFG_CORE_LTC_CTR := $(CFG_CRYPTO_CTR)**
 _CFG_CORE_LTC_CCM := $(CFG_CRYPTO_CCM)
 _CFG_CORE_LTC_AES := $(call cfg-one-enabled, CFG_CRYPTO_XTS CFG_CRYPTO_CCM \
                                             CFG_CRYPTO_AES)
`

**Comment by jenswi-linaro** [comment]
I'm compiling with https://github.com/OP-TEE/optee_os/blob/b7c039eb81db098d2bf18c44b2986d8bc5121ee4/core/crypto.mk

While the fix looks easy enough, I can't tell if it's fixing a symptom or a problem.
