### ISSUE TITLE
HiKey Busybox Repo build error

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#710]
I downloaded the HiKey Repo according to optee_os instructions. However when I run make all:

> peter@peter-HP-Pavilion-Sleekbook-15-PC:~/MasterThesis/HIKEY_REPO/build$ make busybox
> make -C /home/peter/MasterThesis/HIKEY_REPO/build/../linux LOCALVERSION= CROSS_COMPILE=" /home/peter/MasterThesis/HIKEY_REPO/build/../toolchains/aarch64/bin/aarch64-linux-gnu-" ARCH=arm64 Image modules hi6220-hikey.dtb
> make[1]: Entering directory `/home/peter/MasterThesis/HIKEY_REPO/linux'
>   CHK     include/config/kernel.release
>   CHK     include/generated/uapi/linux/version.h
>   CHK     include/generated/utsrelease.h
>   CALL    scripts/checksyscalls.sh
>   CHK     include/generated/compile.h
>   CHK     kernel/config_data.h
> make[2]: `arch/arm64/boot/Image' is up to date.
>   Building modules, stage 2.
>   MODPOST 117 modules
> make[2]: `arch/arm64/boot/dts/hi6220-hikey.dtb' is up to date.
> make[1]: Leaving directory `/home/peter/MasterThesis/HIKEY_REPO/linux'
> cd /home/peter/MasterThesis/HIKEY_REPO/build/../gen_rootfs &&  \
> 		CC_DIR=/home/peter/MasterThesis/HIKEY_REPO/build/../toolchains/aarch64 \
> 		PATH=/home/peter/Code/Repo/:/home/peter/MasterThesis/LEMAKER_HiKey/tools/arm-tc/bin:/home/peter/MasterThesis/LEMAKER_HiKey/tools/arm64-tc/bin:/home/peter/datacapsule/HiKey/tools/arm-tc/bin:/home/peterdatacapsule/HiKey/tools/arm64-tc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/peter/MasterThesis/HIKEY_REPO/build/../linux/usr \
> 		/home/peter/MasterThesis/HIKEY_REPO/build/../gen_rootfs/generate-cpio-rootfs.sh \
> 			hikey nocpio
> Generator for a simple initramfs root filesystem for some ARM targets
> Building HiKey AArch64 root filesystem
> Set up cross compiler at: /home/peter/MasterThesis/HIKEY_REPO/build/../toolchains/aarch64
> Check ccache ...make: *** [busybox-common] Error 1

I am not sure what goes wrong here. The last statement "Check ccache" seems to be from gen_rootfs's generate-cpio-rootfs.sh. 

Just a bit more information, not sure if they contribute. The repo sync seems to get all the repositories I need, but all the repo are not currently on any branches. While Also I had to install the tools manually as make toolchains's curl command does not seem to download the tool tar.xz files but just exits. I tried curl some other things and that seemed to work. So not sure what was up with that. 

I am doing this on Ubuntu 14.04.

**Comment by vchong** [comment]
Are you using the latest code?
Try installing ccache (`sudo apt-get install ccache`) and then try building again.

**Comment by peterfeifanchen** [comment]
Thanks. ccache worked. I actually just found the old issue on this. So now it builds, but when I go make flash:

> fastboot flash ptable /home/peter/MasterThesis/HIKEY_REPO/build/../l-loader/ptable-linux-4g.img
> < waiting for device >
> target reported max download size of 268435456 bytes
> sending 'ptable' (17 KB)...
> OKAY [  0.001s]
> writing 'ptable'...
> OKAY [  0.002s]
> finished. total time: 0.003s
> fastboot flash fastboot /home/peter/MasterThesis/HIKEY_REPO/build/../arm-trusted-firmware/build/hikey/release/fip.bin
> target reported max download size of 268435456 bytes
> sending 'fastboot' (1400 KB)...
> OKAY [  0.040s]
> writing 'fastboot'...
> OKAY [  0.066s]
> finished. total time: 0.107s
> fastboot flash nvme /home/peter/MasterThesis/HIKEY_REPO/build/../out/nvme.img
> target reported max download size of 268435456 bytes
> sending 'nvme' (128 KB)...
> OKAY [  0.004s]
> writing 'nvme'...
> OKAY [  0.005s]
> finished. total time: 0.010s
> fastboot flash boot /home/peter/MasterThesis/HIKEY_REPO/build/../out/boot-fat.uefi.img
> target reported max download size of 268435456 bytes
> sending 'boot' (65536 KB)...
> OKAY [  1.676s]
> writing 'boot'...
> OKAY [  3.173s]
> finished. total time: 4.849s

I notice that it doesn't flash a rootfs. Is this on purpose? Is there a way to build for 8g HiKey and not 4g HiKey? Right now the boot process gets stuck at:

> preparing networking...
> ip: SIOCGIFFLAGS: No such device
> running rc.d services...
> mounting tmpfs at /dev ...done
> mounting pts at /dev/pts ...done
> creating initial mdev device nodes ...done
> setting system time from /dev/rtc0
> Starting telnetd...
> Starting OP-TEE...
> [    8.332715] 
> [    8.332715] TEE Core Framework initialization (ver 1:0.1)
> [    8.350027] TEE armv7 Driver initialization
> [    8.358783] tz_tee_probe: name="armv7sec", id=0, pdev_name="armv7sec.0"
> [    8.369550] TEE core: Alloc the misc device "opteearmtz00" (id=0)
> [    8.380438] TEE Core: Register the misc device "opteearmtz00" (id=0,minor=57)
> uptime idle: 8.29 60.51
> [    8.401991] of_dma_request_slave_channel: dma-names property of node '/smb/uart@f8015000' missing or empty
> [    8.418942] uart-pl011 f8015000.uart: no DMA platform data
> 
> Please press Enter to activate this console. [   28.393839] random: nonblocking pool is initialized

This might because the rootfs is an 8g rootfs from my last flash. The "make all" must build a rootfs somewhere with all the optee_client and optee_linuxdriver and optee_test built in? Or is that left to be done manually?

**Comment by jforissier** [comment]
What is the part you don't understand in "Please press Enter to activate this console"? ;-)

The rootfs is not on the SD or eMMC, it is in the initramfs.

**Comment by peterfeifanchen** [comment]
It hangs there. I press enter, but it doesn't work. When I try to connect an HDMI display to it, nothing shows up. I don't get a console anywhere. Meanwhile LED04 keeps flashing.

I am wondering if it is possible to modify the repo build environment here (maybe something in gen_rootfs) so that its like the steps [here:] (https://github.com/96boards/documentation/wiki/HiKeyOPTEE#flash) where:

1) I flash a 8G jessie.updated.img in the end with all the optee normal world binaries
2) Create an 8G ptable. Currently, PTABLE_LST=linux-4g in hikey.mk (e.g., can I just set this to linux-8g)?

**Comment by vchong** [comment]
The objective of this repo is provide a quick/easy/fast development for OP-TEE, so the build uses an initramfs only, which IS 'inserted' into the boot-fat.uefi.img. Think of it as a minimal rootfs, rather than a 'full' rootfs like those you see on the 96boards pages. See [1] for details on initramfs. All the optee_[client|linuxdriver|test] build artifacts are in this initramfs, if you look at the makefile again.

The 8g rootfs from your last flash will just remain in the system partition and not be used. It should not interfere with anything built from this repo since the system partition is not used here.

Yes, to build the ptable for 8g, just change PTABLE_LST=linux-4g to PTABLE_LST=linux-8g and rebuild. This should be the only thing you need for the 8g board. The rest should work as is, but I've not tried this configuration personally, so please post a reply and let us know if it works for you.

If you want to use the Debian rootfs, follow the instructions in the hikeyoptee page you mentioned. Please do not try to mix and match the instructions here and there. The only thing different you have to do for the Debian rootfs is to wget and flash the 8g ptable image instead of the 4g one. Again, this has not been tested.

[1] https://en.wikipedia.org/wiki/Initramfs

**Comment by peterfeifanchen** [comment]
Okay. I see. But with the repo initramfs build, I am unable to get past "Please press Enter to activate this console". Similarly, once I get to the linux on the normal world side with the Debian build from 96board>OPTEE, again I get stuck at the prompt. It seems there is something wrong with the UART once it gets to the operating system. Either that or my minicom configuration...although it seems to be fine during the boot stage.

I am using the adaptor that was recommended [here](https://www.96boards.org/forums/topic/hikey-96board-serial-console/).

**Comment by vchong** [comment]
It's hard to tell from here, but if you're getting stuck on both builds, then yes it would seem like the problem is with your UART (TX) or terminal program. Try screen instead of minicom, but don't think it'll help though.

**Comment by vchong** [comment]
Btw, it seems that the 4g and 8g ptable have no differences right now, so if you wish, you don't have to change anything in the makefiles. No guarantee things will remain this way in the future though..

**Comment by peterfeifanchen** [comment]
Just to confirm, the UART settings are 115200 8N1, Yes for hardware flow control, No for software? The TX seems to work all the way to the Grub menu where I can press enter and get past the 10s wait.

**Comment by vchong** [comment]
I use 115200 8N1 and No for both HW And SW flow control. Which UART are you using? Did you make any changes to any files? Maybe try a different cable.

**Comment by peterfeifanchen** [comment]
Thanks! It as the No on the HW flow control. It works now.
