### ISSUE TITLE
Does OPTEE support NIST ECDSA P521 Testvector verification?

### ISSUE THREAD

**Issue by sungkeunsong** [OP-TEE/optee_os#7100]
Dear all,

I am verifying ECDSA verification using SigVer.rsp, NIST test vectors.
https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/dss/186-4ecdsatestvectors.zip
All testvectors passed up to P384 but P521 testvectors are encountering verification failures.
R, S of P521 testvectors is 131 hex digit, respectively. So signature size is 131 bytes.
I got TEE panic (0xffff0006).
so I tried adding a 1-byte 0x00 at the beginning or end to adjust the certificate size to 132 bytes.
All test vectors that should pass verification are failing.
Let me know if OPTEE support NIST ECDSA P521 Testvector verification
I'm using OPTEE version 3.11

Thank you

**Comment by jenswi-linaro** [comment]
We have some tests based on https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/dss/186-2ecdsatestvectors.zip
Do you know what's different with the newer file?

**Comment by sungkeunsong** [comment]
testvectors for SHA-2(SHA-224, SHA-256, SHA-384, SHA-512) are added.

**Comment by jenswi-linaro** [comment]
Thanks. The vectors are supposed to pass, if they don't, it's an error. Do we have the same problem with 4.4? It would be nice to have a few of those vectors in xtest to help fix the issue and also make sure it stays fixed with CI.

**Comment by sungkeunsong** [comment]
I don’t have a device running version 4.4, but I’ll test it if I get a chance.
