### ISSUE TITLE
How to encrypt a .ta file?

### ISSUE THREAD

**Issue by andreas-brix** [OP-TEE/optee_os#7112]
Hello, 

I created a trusted application using optee_examples and added my application there in the same way. I tested it using the qemu emulator and it works as expected. If I understand correctly, the optee_examples refer to user mode trusted applications. I read in the documentation, that "they consist of a [ELF](https://en.wikipedia.org/wiki/Executable_and_Linkable_Format) file, signed and optionally encrypted, named from the UUID of the TA and the suffix .ta." 

For possible deployment, I want to protect my algorithms inside the TEE since they are intellectual property, so I would like to use the optional encryption. Is there any documentation how this can be done? Is it correct, that the .ta file would then reside in an encrypted form in the REE and would only be decrypted and executed in the TEE if I use scripts/sign_encrypt.py properly? Is there anything to be changed in the trusted application such that I can use that encryption? 

Any help would be appreciated and if I have mistakes in my understanding, please point them out.

Thank you very much.

**Comment by zjchen666** [comment]
is the TA encryption key TA unique? thanks

**Comment by etienne-lms** [comment]
No, the TA encryption key is currently shared for all TAs, see `tee_ta_decrypt_init()` and its use of `tee_otp_get_ta_enc_key()`.
Current implementation of `tee_otp_get_ta_enc_key()` does not have the TA UUID as argument or some other hint which could be used to select the expected encryption key when TA is loaded.

**Comment by andreas-brix** [comment]
Thank you for your answer @jforissier. Is there another way than using a HUK for TA encryption? If I understand the `core/kernel/otp_stubs.c` file correctly, I would have to override the functions to get the keys with code that reads the HUK from the fuse. Is there another way to securely store the key for TA encryption? Reading the fuses is not possible because afaik the code for it is closed source and not available for me.

**Comment by andreas-brix** [comment]
I found out that I had a small misunderstanding here. Fortunately, on the device that I am using (Jetson AGX Orin) there is an implementation of the retrieval of the HUK, which is then used for the encryption of a TA. This means that the issue is solved for my case. Thank you!

**Comment by jforissier** [comment]
You're welcome. I'm closing this issue then.
