### ISSUE TITLE
How to write an SMC Call to ARM Trusted Firmware in optee_example?

### ISSUE THREAD

**Issue by likeyou600** [OP-TEE/optee_os#7120]
I used the rockpi4.xml from OP-TEE to set up the repository.

I copied the helloworld folder and renamed it to test_smc_call.
In the code, I included linux/arm-smccc.h and intend to use arm_smccc_smc to call the mmu_smc_handler that I defined in ARM Trusted Firmware.
I'm not sure if there is a better method than arm_smccc_smc.

However, when I directly include the header, I encounter errors. I also tried modifying the CMakeLists.txt but still couldn't make it work.
I am directly importing the contents from the linux directory at the root level.

Is there a better way to implement a secure monitor call?
![image](https://github.com/user-attachments/assets/ce46b70c-941f-442e-9447-9106387dadca)

---
![image](https://github.com/user-attachments/assets/a9ee7051-605b-475d-85fd-b65acad04a15)

---
![image](https://github.com/user-attachments/assets/e650b9ac-bfa3-45cf-b322-2f39db015831)

**Comment by jenswi-linaro** [comment]
You can't do SMCs from user-space. It must be done from EL1 or EL2.

**Comment by jenswi-linaro** [comment]
Yes, it's possible. There's a reason why EL0 can do SMCs, if you add a bridge like this you'll allow user-space to do things only the kernel should be able to.

**Comment by etienne-lms** [comment]
@jenswi-linaro, I think you meant *"There's a reason why EL0 can**not** do SMCs, ..."* :)

**Comment by jenswi-linaro** [comment]
> @jenswi-linaro, I think you meant _"There's a reason why EL0 can**not** do SMCs, ..."_ :)

Right, thanks. :-)
