### ISSUE TITLE
Core data-abort when reading external device tree

### ISSUE THREAD

**Issue by iceaway** [OP-TEE/optee_os#7124]
Hi,

I am trying to get optee running on my board which has a i.MX 7Dual processor (1 GB DDR memory). The DDR is accessible from physical address `0x80000000`. The boot flow is that the BootROM loads SPL, SPL loads U-Boot and U-boot loads optee + linux kernel + device tree. When optee starts it gets to the point of loading the external device tree, which is located at `0x83000000` (optee itself is loaded at `0x84000000`).  When it tries to read from the device tree I get this Core data-abort repeatedly:

```
E/TC:0 0 Core data-abort at address 0x7f500000
E/TC:0 0  fsr 0x00000008  ttbr0 0x840a006a  ttbr1 0x840a006a  cidr 0x0
E/TC:0 0  cpu #0          cpsr 0x600001f3
E/TC:0 0  r0 0x00000007      r4 0x84067d0c    r8 0x8405fb9c   r12 0xfffb7d2c
E/TC:0 0  r1 0x00000000      r5 0x7f500000    r9 0x840ada40    sp 0x840a98c8
E/TC:0 0  r2 0x00000000      r6 0x83000000   r10 0x0000afae    lr 0x84041baf
E/TC:0 0  r3 0x00000000      r7 0x8405fb40   r11 0x000014d8    pc 0x8401631c
D/TC:0 0 get_fault_type:546 [abort] Unhandled fault!
```

This is the dump of the mmap table:
```
D/TC:0   add_va_space:707 type RES_VASPACE size 0x00a00000
D/TC:0   add_va_space:707 type SHM_VASPACE size 0x02000000
D/TC:0   dump_mmap_table:835 type NSEC_SHM     va 0x7d500000..0x7d6fffff pa 0x85e00000..0x85ffffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:835 type TA_RAM       va 0x7d700000..0x7f3fffff pa 0x84100000..0x85dfffff size 0x01d00000 (pgdir)
D/TC:0   dump_mmap_table:835 type EXT_DT       va 0x7f500000..0x7fefffff pa 0x83000000..0x839fffff size 0x00a00000 (pgdir)
D/TC:0   dump_mmap_table:835 type IO_SEC       va 0x80000000..0x800fffff pa 0x31000000..0x310fffff size 0x00100000 (pgdir)
D/TC:0   dump_mmap_table:835 type IO_SEC       va 0x80100000..0x804fffff pa 0x30800000..0x30bfffff size 0x00400000 (pgdir)
D/TC:0   dump_mmap_table:835 type IO_NSEC      va 0x80600000..0x807fffff pa 0x30800000..0x309fffff size 0x00200000 (pgdir)
D/TC:0   dump_mmap_table:835 type IO_SEC       va 0x80800000..0x80bfffff pa 0x30400000..0x307fffff size 0x00400000 (pgdir)
D/TC:0   dump_mmap_table:835 type IO_SEC       va 0x80d00000..0x810fffff pa 0x30000000..0x303fffff size 0x00400000 (pgdir)
D/TC:0   dump_mmap_table:835 type TEE_COHERENT va 0x81200000..0x812fffff pa 0x00900000..0x009fffff size 0x00100000 (pgdir)
D/TC:0   dump_mmap_table:835 type TEE_COHERENT va 0x81300000..0x813fffff pa 0x00100000..0x001fffff size 0x00100000 (pgdir)
D/TC:0   dump_mmap_table:835 type RES_VASPACE  va 0x81400000..0x81dfffff pa 0x00000000..0x009fffff size 0x00a00000 (pgdir)
D/TC:0   dump_mmap_table:835 type SHM_VASPACE  va 0x81f00000..0x83efffff pa 0x00000000..0x01ffffff size 0x02000000 (pgdir)
D/TC:0   dump_mmap_table:835 type TEE_RAM_RX   va 0x84000000..0x8406dfff pa 0x84000000..0x8406dfff size 0x0006e000 (smallpg)
D/TC:0   dump_mmap_table:835 type TEE_RAM_RW   va 0x8406e000..0x840fffff pa 0x8406e000..0x840fffff size 0x00092000 (smallpg)
I/TC: static map->pa = 85e00000, type = NSEC_SHM
D/TC:0   core_mmu_alloc_l2:316 L2 table used: 1/6
```

Initially I did not manually `add_phys_mem()` the `EXT_DB` region and it tried to read the device tree from the `RES_VASPACE` area. Then the data-abort was at address `0x00000000` and I thought the issue was that it was trying to read from physical address `0x00000000`. But adding the `EXT_DB` memory does not improve the behavior. I am new to both optee and MMU usage so perhaps I am missing something obvious.

**Comment by iceaway** [comment]
> Perhaps you need to map the DT memory as secure, CFG_MAP_EXT_DT_SECURE=y.

This did the trick, thank you! I could even remove the `EXT_DT` mapping, and it still works. Just out of curiosity, how does that work out when it tries to map the external device tree in the `RES_VASPACE` area that is mapped to physical address 0? It feels like I am missing something.

**Comment by jenswi-linaro** [comment]
Mapping physical address 0 shouldn't be a problem, but when passing physical address 0 as an argument it is usually treated as NULL, that is, an invalid address. So to avoid problems, the DTB shouldn't be stored at physical address 0 if it's to be passed to OP-TEE during boot.
