### ISSUE TITLE
Getting TEE_ERROR_MAC_INVALID when using the TEE_AEDecryptFinal API.

### ISSUE THREAD

**Issue by kyoWNC** [OP-TEE/optee_os#7130]
Hi,

When I use AES decryption (TEE_AEDecryptFinal), I found that the input data is correct, but there is a chance of receiving TEE_ERROR_MAC_INVALID. However, after retrying, it succeeds.

uint8_t aes_decrypted_key[] = {0x56, 0x6b, 0x6d, 0x73, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x63, 0x68, 0x5f, 0x5f, 0x4e, 0x41, 0x44};
uint8_t encrypted_data[] = {0x82, 0x74, 0x73, 0xf6, 0x18, 0x48, 0xae, 0x35, 0x38, 0x07, 0xd9, 0x24, 0x85, 0x57, 0xeb, 0x66};
uint8_t nonce[] = {0x4e, 0xbf, 0x66, 0x72, 0x55, 0xc8, 0xda, 0x7e, 0x0e, 0xc2, 0xd1, 0xd6};
uint8_t tag[] = {0xd8, 0x59, 0x27, 0x2e, 0x96, 0x2f, 0x70, 0x5f, 0x29, 0x75, 0xcf, 0x21, 0x68, 0xed, 0x69, 0x23};
No AAD.

I found that there is inconsistency in the underlying process of generating the tag.

E/TC:0 __gcm_dec_final:330 -----state->buf_tag-----
E/TC:0 __gcm_dec_final:332 49
E/TC:0 __gcm_dec_final:332 a1
E/TC:0 __gcm_dec_final:332 67
E/TC:0 __gcm_dec_final:332 37
E/TC:0 __gcm_dec_final:332 56
E/TC:0 __gcm_dec_final:332 23
E/TC:0 __gcm_dec_final:332 3d
E/TC:0 __gcm_dec_final:332 16
E/TC:0 __gcm_dec_final:332 2b
E/TC:0 __gcm_dec_final:332 87
E/TC:0 __gcm_dec_final:332 72
E/TC:0 __gcm_dec_final:332 0b
E/TC:0 __gcm_dec_final:332 cb
E/TC:0 __gcm_dec_final:332 b8
E/TC:0 __gcm_dec_final:332 a9
E/TC:0 __gcm_dec_final:332 6e
E/TC:0 __gcm_dec_final:333 -----tag-----
E/TC:0 __gcm_dec_final:336 d8
E/TC:0 __gcm_dec_final:336 59
E/TC:0 __gcm_dec_final:336 27
E/TC:0 __gcm_dec_final:336 2e
E/TC:0 __gcm_dec_final:336 96
E/TC:0 __gcm_dec_final:336 2f
E/TC:0 __gcm_dec_final:336 70
E/TC:0 __gcm_dec_final:336 5f
E/TC:0 __gcm_dec_final:336 29
E/TC:0 __gcm_dec_final:336 75
E/TC:0 __gcm_dec_final:336 cf
E/TC:0 __gcm_dec_final:336 21
E/TC:0 __gcm_dec_final:336 68
E/TC:0 __gcm_dec_final:336 ed
E/TC:0 __gcm_dec_final:336 69
E/TC:0 __gcm_dec_final:336 23
E/TA:  aes_gcm_decrypt:378 ---------TEE_AEDecryptFinal, result=ffff3071

Thanks

**Comment by jenswi-linaro** [comment]
Are you supplying all the data in a single call to `TEE_AEDecryptFinal()`?
Which platform are you testing with? OP-TEE version? Configuration flags?

**Comment by kyoWNC** [comment]
Sometimes, a panic occurs.

E/TC:0 TA panicked with code 0xffff0001
E/TC:0 Status of TA 9e646a4c-85f2-4e9c-8c08-15c422e797b6 (0x4ea8cd10) (active)
E/TC:0  arch: aarch64  load address: 0x80009000 ctx-idr: 6
E/TC:0  stack: 0x80004000 18432
E/TC:0  region 0: va 0x80000000 pa 0x4e9a0000 size 0x2000 flags ---R-X
E/TC:0  region 1: va 0x80002000 pa 0x4ea90000 size 0x1000 flags ---RW-
E/TC:0  region 2: va 0x80004000 pa 0x4ec73000 size 0x5000 flags rw-RW-
E/TC:0  region 3: va 0x80009000 pa 0x4ec30000 size 0x34000 flags r-x--- [0]
E/TC:0  region 4: va 0x8003d000 pa 0x4ec64000 size 0xf000 flags rw---- [0]
E/TC:0  region 5: va 0x8004d000 pa 0x4f3a1000 size 0x3000 flags rw-RW-
E/TC:0  [0] 9e646a4c-85f2-4e9c-8c08-15c422e797b6 @ 0x80009000
E/TC:0 Call stack:
E/TC:0  0x000000008000a4c4  ===>TEE_AEDecryptFinal
E/TC:0  0x00000000800270f8
E/TC:0  0x000000004e9a4148
D/TC:0 unwind_stack_arm64:56 FP out of bounds 0
D/TC:0 user_ta_enter:316 tee_user_ta_enter: TA panicked with code 0xffff0001
D/TC:0 tee_ta_invoke_command:625 Error: ffff3024 of 3
D/TC:0 tee_ta_invoke_command:606 Panicked !
D/TC:0 tee_ta_invoke_command:606 Panicked !

**Comment by jenswi-linaro** [comment]
Which platform variant is this from `core/arch/arm/plat-*`? Do you have local changes on top of the tag `3.2.0`?
Have you supplied any `CFG_*` variables overriding the default values in the build?

**Comment by kyoWNC** [comment]
1. mediatek
2. We just applied some security patches.
3.  
$(call force,CFG_8250_UART,y)
$(call force,CFG_GENERIC_BOOT,y)
$(call force,CFG_PM_STUBS,y)
$(call force,CFG_SECURE_TIME_SOURCE_CNTPCT,y)
$(call force,CFG_WITH_ARM_TRUSTED_FW,y)
$(call force,CFG_GIC,y)
$(call force,CFG_ARM_GICV3,y)
$(call force,CFG_TEE_CORE_NB_CORE,4)
$(call force,CFG_CORE_CLUSTER_SHIFT,0)
CFG_NUM_THREADS ?= $(CFG_TEE_CORE_NB_CORE)
CFG_WITH_SOFTWARE_PRNG := n

Is it possible for the error I encountered to be influenced by something? Because the issue occurs randomly, I have no clue where to find the problem.

Thanks for yor time.

**Comment by jenswi-linaro** [comment]
Do the errors occur on `3.2.0` without any other patches on top?

> Is it possible for the error I encountered to be influenced by something? Because the issue occurs randomly, I have no clue where to find the problem.

Perhaps something bad happens when non-secure interrupts pre-empt OP-TEE. You can test commenting out
``` C
thread_set_foreign_intr(true);
```
in `tee_entry_std()`.

**Comment by kyoWNC** [comment]
Thanks your answer but it doesn't work,

**Comment by jenswi-linaro** [comment]
> Thanks for your answer but it doesn't work,

What, testing on a plain `3.2.0`?

**Comment by kyoWNC** [comment]
No ,i have applied some CVE patches to 3.2.0. https://github.com/OP-TEE/optee_os/issues/5987
