### ISSUE TITLE
About 64-bit OP-TEE OS and 32-bit TA

### ISSUE THREAD

**Issue by zhupg** [OP-TEE/optee_os#7134]
Dear,
I know that 64-bit OP-TEE OS supports both 64-bit TA and 32bit TA.
If we use 64-bit OP-TEE OS/32-bit TA and the system have more than 4G memory, can the TA works well?
For examlple, the dynamic share memory is allocated from linux driver, the physical address may exceed 4G, how OPTEE-OS process it for TA?
Thanks and Best regards.

**Comment by jenswi-linaro** [comment]
TAs (32 and 64-bit) are mapped using virtual addresses below 4G, so the 4G limit for 32-bit TAs is avoided.

**Comment by zhupg** [comment]
Just as I guessed, thanks a lot.
