### ISSUE TITLE
How to obtain QEMU virt DTB that succeeds optee_probe()?

### ISSUE THREAD

**Issue by yuvraj1803** [OP-TEE/optee_os#7137]
From what I have noticed, qemu-system-aarch64's virt machine (v8) does not have the optee entry in its dtb. Can be check with "-machine dumpdtb=qemu.dtb", and I am sure this is known already.

After reading [this](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v5.4-rc3&id=14e21cb8f811), I made the same changes into the dumped qemu DTB and passed it into qemu through "-dtb qemu.dtb". But now I get another issue.

# dmesg | grep tee
[    1.957983] optee: probing for conduit method.
[    1.958617] optee: revision 4.4 (cd9b1df64f61b7e0)
[    1.961913] optee firmware:optee: error -ENXIO: IRQ index 0 not found
[    1.962401] optee: platform_get_irq: ret -6
# 

So, I believe more changes have to be made to the DTS, like reserved mem, etc.

Please let me know where to find this DTS, or how to modify QEMU's DTB so that optee_probe() finishes successfully.

**Comment by jenswi-linaro** [comment]
We test QEMU v8 AArch64 on each pull request in the CI loop, so this failure must be caused by the changes you made. Anyway, OP-TEE is patching up the DTB at boot on QEMU, see update_external_dt() in core/arch/arm/kernel/boot.c.

**Comment by yuvraj1803** [comment]
Yes, these changes I made for testing purposes only (to be ignored). Either way, are there any other machines in qemu which support OPTEE? I just need the kernel and OPTEE to be up and running for some other purpose.

**Comment by jenswi-linaro** [comment]
None, I'm aware of.
