### ISSUE TITLE
How to add custom hardware encryption and decryption drivers in optee-os

### ISSUE THREAD

**Issue by xtaens** [OP-TEE/optee_os#7143]
As the title says, I have an encryption and decryption driver. How do I add it to optee-os? Is there a ready-made interface that I can just adapt? Or can I just replace the code in libtomcrypt or mbedtls with my own?

Currently I am using optee-os 4.0.0

Thank you

**Comment by etienne-lms** [comment]
You can find examples of existing crypto drivers in https://github.com/OP-TEE/optee_os/tree/4.0.0/core/drivers/crypto.

**Comment by xtaens** [comment]
> You can find examples of existing crypto drivers in https://github.com/OP-TEE/optee_os/tree/4.0.0/core/drivers/crypto.

Thanks, I'll learn it.
