### ISSUE TITLE
Do we need to check return of tee_mm_init() ?

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_os#7144]
Coverity reported an error here: `Unchecked return value (CHECKED_RETURN)`
Do we need to check return of tee_mm_init() here ?

https://github.com/OP-TEE/optee_os/blob/da603884e808dedf6615a9c1dd742b0b27c9ca83/core/mm/phys_mem.c#L35

**Comment by etienne-lms** [comment]
Nice catch, we should. Would you mind creating a P-R?

**Comment by sahilnxp** [comment]
@etienne-lms Yeah, will create a P-R..

**Comment by sahilnxp** [comment]
PR Created: https://github.com/OP-TEE/optee_os/pull/7145

**Comment by sahilnxp** [comment]
Pull request https://github.com/OP-TEE/optee_os/pull/7145 merged.
