### ISSUE TITLE
Erasing RPMB partition and/or OP-TEE

### ISSUE THREAD

**Issue by anakin4747** [OP-TEE/optee_os#7146]
Hello, 

I am experiencing some issues when trying to use a new RPMB key for interacting with optee through pkcs11.

I am on commit 9d2ec578119130e2fd66e2577581bbeb13ee3582 from imx-optee-os and I am compiling with the following configurations:

```sh
CFG_NS_ENTRY_ADDR=0x12000000 \                                            
CFG_DT_ADDR=0x18000000 \                                                  
CFG_RPMB_FS=y \                                                           
CFG_RPMB_WRITE_KEY=y \                                                    
CFG_REE_FS=n \                                                            
CFG_RPMB_FS_DEV_ID=2 \                                                                                                  
CFG_TEE_TA_LOG_LEVEL=4 \                                                  
CFG_TEE_CORE_LOG_LEVEL=4 \                                                
```

Currently reading optee through pkcs11 is failing due to the RPMB key being mismatched.

I added `CFG_RPMB_RESET_FAT=y` hoping to erase the partition and optee so that a new key can be generated and written by optee.

However, after enabling that configuration option I get the following error when I try to access optee through pkcs11:
```
...
D/TC:? 0 tee_rpmb_init:1123 RPMB: Reliable Write Sector Count is 1
D/TC:? 0 tee_rpmb_init:1150 RPMB INIT: Deriving key
I/TC: RPMB: Using generated key
D/TC:? 0 tee_rpmb_init:1165 RPMB INIT: Verifying Key
D/TC:? 0 tee_rpmb_resp_unpack_verify:877 MAC mismatched:
E/TC:? 0 tee_rpmb_verify_key_sync_counter:1013 Verify key returning 0xffff000f
E/TC:? 0 tee_rpmb_init:1176 Verify key failed!
E/TC:? 0 tee_rpmb_init:1177 Make sure key here matches device key
...
```
It seems to not let me use a new key since it doesn't match the old one.

How can I properly use the `CFG_RPMB_RESET_FAT` symbol to reset the partition and erase optee? Is it possible to erase the RPMB partition or optee without the previous RPMB key?

**Comment by ricardosalveti** [comment]
RPMB key is a write-once key, you will only be able to reset fat if the same key is used.

**Comment by anakin4747** [comment]
Thank you very much!
