### ISSUE TITLE
Run optee_os with android on QEMU

### ISSUE THREAD

**Issue by yingkailiang** [OP-TEE/optee_os#715]
I am a researcher in Syracuse University. Our group's research interest is mobile security, especially Android and ARM TrustZone. We are interested in setting up **android + optee** running on **QEMU**(with TrustZone feature enable). I found your group already has some thought and interesting discussion in  #605.  
I want to ask what is the current status in term of **android + optee on QEMU** development?
If such platform is not ready yet, I am also interested in making contribution to this **android + optee QEMU** platform. Right now, I can run AOSP image on QEMU. I can also run OPTEE+linux kernel on QEMU. Can anyone briefly explains the main challenges to incorporate android + OPTEE + linux kernel (optee_driver) running on QEMU? 

Thanks in advance

**Comment by hybridNeo** [comment]
I tried this sometime back and was not successful so I went and bought a hikey board for 100$, Also which AOSP image did you load on QEMU, as far as I know armv8 + TrustZone is not supported by QEMU yet, but in a months time it should be supported.

**Comment by yingkailiang** [comment]
I download the AOSP from linaro official release, the version I use is 15.01. I use arm7 (-M vexpress-a9 -cpu cortex-a15) + TrustZone. Right now I can run their released android image and kernel on qemu. 
In order to run OPTEE OS + android, I still need to generate a bios.bin to enable trustzone feature based on their document: 
http://www.linaro.org/blog/core-dump/arm-trustzone-qemu/

I am still doing some investigation how to generate this bios.bin file.
