### ISSUE TITLE
How to solve ldelf_init_with_ldelf:152 ldelf failed with res: 0xffff0008

### ISSUE THREAD

**Issue by xtaens** [OP-TEE/optee_os#7152]
When running xtest 1013 with optee-os + client + test version 4.0.0, the following error occurred. Is this due to misconfiguration? Or is it caused by other problems? Thank you

The log without detailed trace is as follows. The case running result is normal, but there is an error prompt

![111](https://github.com/user-attachments/assets/a7e64c33-927f-491f-955d-7f265ebd7fae)

```
# xtest 1013
Test ID: 1013
Run test suite with level=0

TEE test application started over default TEE instance
######################################################
#
# regression+pkcs11
#
######################################################
 
* regression_1013 Test concurrency with concurrent TA
o regression_1013.1 Using small concurrency TA
D/TC:? 0 tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA d96a5b40-e2c7-b1af-8794-1002a5d5c61b
D/TC:? 0 ldelf_load_ldelf:110 ldelf load address 0x40007000
D/LD:  ldelf:142 Loading TS d96a5b40-e2c7-b1af-8794-1002a5d5c61b
F/TC:? 0 trace_syscall:150 syscall #3 (syscall_get_property)
F/TC:? 0 trace_syscall:150 syscall #5 (syscall_open_ta_session)
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF d96a5b40-e2c7-b1af-8794-1002a5d5c61b (Secure Storage TA)
F/TC:? 0 plat_prng_add_jitter_entropy:72 0x98
F/TC:? 0 plat_prng_add_jitter_entropy:72 0xAB
F/TC:? 0 plat_prng_add_jitter_entropy:72 0x91
F/TC:? 0 plat_prng_add_jitter_entropy:72 0x24
F/TC:? 0 plat_prng_add_jitter_entropy:72 0xBD
D/TC:? 0 ldelf_syscall_open_bin:167 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF d96a5b40-e2c7-b1af-8794-1002a5d5c61b (REE)
D/TC:? 0 ldelf_syscall_open_bin:167 res=0xffff0008
E/LD:  init_elf:486 sys_open_ta_bin(d96a5b40-e2c7-b1af-8794-1002a5d5c61b)
E/TC:? 0 ldelf_init_with_ldelf:152 ldelf failed with res: 0xffff0008
D/TC:? 0 tee_ta_open_session:694 init session failed 0xffff0008
F/TC:? 0 plat_prng_add_jitter_entropy:72 0xD6
o regression_1013.1.1 Busy loop repeat 10000
D/TC:? 0 tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA e13010e0-2ae1-11e5-896a-0002a5d5c51b
*D/TC:? 2 tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA e13010e0-2ae1-11e5-896a-0002a5d5c51b
*D/TC:? 0 ldelf_load_ldelf:110 ldelf load address 0x40007000
*D/TC:? 2 ldelf_load_ldelf:110 ldelf load address 0x40007000
*D/LD:  ldelf:142 Loading TS e13010e0-2ae1-11e5-896a-0002a5d5c51b
*D/TC:? 1 tee_ta_init_pseudo_ta_session:297 Lookup pseudo TA e13010e0-2ae1-11e5-896a-0002a5d5c51b
*F/TC:? 0 trace_syscall:150 syscall #3 (syscall_get_property)
*D/TC:? 1 ldelf_load_ldelf:110 ldelf load address 0x40007000
*F/TC:? 0 trace_syscall:150 syscall #5 (syscall_open_ta_session)
*D/LD:  ldelf:142 Loading TS e13010e0-2ae1-11e5-896a-0002a5d5c51b
*D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF e13010e0-2ae1-11e5-896a-0002a5d5c51b (Secure Storage TA)
*F/TC:? 2 trace_syscall:150 syscall #3 (syscall_get_property)
*D/LD:  ldelf:142 Loading TS e13010e0-2ae1-11e5-896a-0002a5d5c51b
*F/TC:? 2 trace_syscall:150 syscall #5 (syscall_open_ta_session)
*F/TC:? 0 plat_prng_add_jitter_entropy:72 0x7A
*D/TC:? 2 ldelf_syscall_open_bin:163 Lookup user TA ELF e13010e0-2ae1-11e5-896a-0002a5d5c51b (Secure Storage TA)
*F/TC:? 0 plat_prng_add_jitter_entropy:72 0xE6
*D/TC:? 2 do_notif:36 sleep thread 2 0x850746f0
*F/TC:? 1 trace_syscall:150 syscall #3 (syscall_get_property)
*D/TC:? 0 do_notif:36 wake  thread 2 0x850746f0
*F/TC:? 1 trace_syscall:150 syscall #5 (syscall_open_ta_session)
*F/TC:? 0 plat_prng_add_jitter_entropy:72 0x9C
*D/TC:? 1 ldelf_syscall_open_bin:163 Lookup user TA ELF e13010e0-2ae1-11e5-896a-0002a5d5c51b (Secure Storage TA)
*D/TC:? 0 do_notif:36 wake  thread 2 0x850746f0
*F/TC:? 1 plat_prng_add_jitter_entropy:72 0xFD
*D/TC:? 0 ldelf_syscall_open_bin:167 res=0xffff0008
*F/TC:? 1 plat_prng_add_jitter_entropy:72 0x82
*D/TC:? 2 do_notif:36 sleep thread 2 0x850746f0
*F/TC:? 1 plat_prng_add_jitter_entropy:72 0xD9
*D/TC:? 0 ldelf_syscall_open_bin:163 Lookup user TA ELF e13010e0-2ae1-11e5-896a-0002a5d5c51b (REE)
```

**Comment by jenswi-linaro** [comment]
I was expecting to see something about "TEEC_ERROR_OUT_OF_MEMORY - ignored" since that's an error that sometimes occurs during this test case, depending on the memory configuration. The purpose of the test is to stress concurrent loading of TAs, this is done at least somewhat even if it fails with out of memory.

I'm surprised that the test case doesn't error out on TEE_ERROR_ITEM_NOT_FOUND returned by init session.

**Comment by xtaens** [comment]
> I was expecting to see something about "TEEC_ERROR_OUT_OF_MEMORY - ignored" since that's an error that sometimes occurs during this test case, depending on the memory configuration. The purpose of the test is to stress concurrent loading of TAs, this is done at least somewhat even if it fails with out of memory.
> 
> I'm surprised that the test case doesn't error out on TEE_ERROR_ITEM_NOT_FOUND returned by init session.

Hi, is there any troubleshooting or solution?

**Comment by xtaens** [comment]
> I was expecting to see something about "TEEC_ERROR_OUT_OF_MEMORY - ignored" since that's an error that sometimes occurs during this test case, depending on the memory configuration. The purpose of the test is to stress concurrent loading of TAs, this is done at least somewhat even if it fails with out of memory.
> 
> I'm surprised that the test case doesn't error out on TEE_ERROR_ITEM_NOT_FOUND returned by init session.

Hi, can I try the latest 4.4.0? Or is there a bug in 4.0.0?

**Comment by jenswi-linaro** [comment]
> Hi, can I try the latest 4.4.0? Or is there a bug in 4.0.0?

Sure, I'm not aware of bugs in 4.0.0 relating to this.

**Comment by xtaens** [comment]
> > Hi, can I try the latest 4.4.0? Or is there a bug in 4.0.0?
> 
> Sure, I'm not aware of bugs in 4.0.0 relating to this.

Hello,
1. I haven't upgraded to the latest version, and I'm still using version 4.0
2. After defining the following macro, the error 0xffff0008 is gone. Why is this?
Thank you

```
CFG_WITH_STATS := y
CFG_TA_STATS := y
```

**Comment by xtaens** [comment]
> It seems that the tests try to open a session to a PTA enabled by those flags. I'd check the code for details.

Thank you, waiting for your good news

**Comment by jenswi-linaro** [comment]
> > It seems that the tests try to open a session to a PTA enabled by those flags. I'd check the code for details.
> 
> Thank you, waiting for your good news

I'm sorry for the confusion. I meant, if I were you I would check the code for details.

**Comment by xtaens** [comment]
> > > It seems that the tests try to open a session to a PTA enabled by those flags. I'd check the code for details.
> > 
> > 
> > Thank you, waiting for your good news
> 
> I'm sorry for the confusion. I meant, if I were you I would check the code for details.

Oh, I understand, thank you, I will check the code again
