### ISSUE TITLE
TEE_ERROR_NOT_SUPPORTED when running xtest --stats --ta

### ISSUE THREAD

**Issue by ybernsteinoz** [OP-TEE/optee_os#7153]
Hello, 
I am using optee on QEMU, I have an app that makes use of the ta. 
I am interested in measuring the ta memory usage as described here https://github.com/OP-TEE/optee_os/issues/6124

I compile my ta with the flags:
CFG_TEE_CORE_MALLOC_DEBUG = y
CFG_TEE_TA_MALLOC_DEBUG = y
CFG_WITH_STATS=y
CFG_TA_STATS=y

But when I run the command xtest --stats --ta I get:
xtest: TEEC_InvokeCommand: res 0xffff000a err_orig 0x4
which means TEE_ERROR_NOT_SUPPORTED.

Thanks

**Comment by etienne-lms** [comment]
`CFG_TA_STATS=y` and `CFG_WITH_STATS=y` are enough to measure memory consumption in TAs.
I've just tested on my platform, works fine.

`CFG_TEE_TA_MALLOC_DEBUG` is rather used internally in embedded code (*bget_malloc.c|.h*) to assert the heap pool consistency (effective assertion requires `NDEBUG` is not defined).
`CFG_TEE_CORE_MALLOC_DEBUG` does the same (effective assertion requires `CFG_TEE_CORE_DEBUG=y`).

**Comment by ybernsteinoz** [comment]
@etienne-lms thanks for your reply!
I've tried to remove the other flags, so the flags I currently have are:
CFG_TEE_TA_LOG_LEVEL ?= 4
CFG_TA_OPTEE_CORE_API_COMPAT_1_1=y
CFG_WITH_STATS=y
CFG_TA_STATS=y

but the same error still occurs.

**Comment by etienne-lms** [comment]
Looking into the implementation, the sole reason I see `xtest --stats --ta` results in `res=0xffff000a err_orig=0x4` is [`CFG_TA_STATS` is disabled](https://github.com/OP-TEE/optee_os/blob/4.4.0/core/pta/stats.c#L150) (unless I missed something, of corse :-). Check the OP-TEE core you test is really the one you have rebuilt.

**Comment by xtaens** [comment]
hi
I ran the following error on 4.0.0

```
# 
# xtest --stats --ta
xtest: TEEC_InvokeCommand: res 0xffff0008 err_orig 0x4
# 
#
```

**Comment by etienne-lms** [comment]
0xffff0008/`TEE_ERROR_ITEM_NOT_FOUND` : this is likely returned because these are no TA loaded in OP-TEE at the time you run `xtest --stats --ta`, [e.g. here](https://elixir.bootlin.com/op-tee/4.0.0/source/core/kernel/tee_ta_manager.c#L954). To get stats from a TA, you need to TA to be loaded in OP-TEE secure userland and you need that there is at least a session opened towards that TA.

FYI, the implementation of `get_user_ta_stats()` and `tee_ta_instance_stats()` has not changed from OP-TEE release tag 3.20.0 to tag 4.4.0 (including 4.0.0).

**Comment by xtaens** [comment]
> 0xffff0008/`TEE_ERROR_ITEM_NOT_FOUND` : this is likely returned because these are no TA loaded in OP-TEE at the time you run `xtest --stats --ta`, [e.g. here](https://elixir.bootlin.com/op-tee/4.0.0/source/core/kernel/tee_ta_manager.c#L954). To get stats from a TA, you need to TA to be loaded in OP-TEE secure userland and you need that there is at least a session opened towards that TA.
> 
> FYI, the implementation of `get_user_ta_stats()` and `tee_ta_instance_stats()` has not changed from OP-TEE release tag 3.20.0 to tag 4.4.0 (including 4.0.0).

Thank you, I solved the problem after adding the following macro, but the cause has not been found yet

```
CFG_WITH_STATS := y
CFG_TA_STATS := y
```

**Comment by ybernsteinoz** [comment]
I found out that I added the flags in the wrong place - had to add them in the QEMU and not in the ta.
thanks, closing this
