### ISSUE TITLE
QEMU networking

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#716]
Is there a way to enable networking to the outside world? Currently I am trying ping (does not work) and ifconfig (gives me no devices).

I tried to add:

_-netdev user,id=network0 -device e1000,netdev=network0_

The QEMU manual says this should automatically create a netback device that bridges to the host network. Am I doing something wrong here?

**Comment by jenswi-linaro** [comment]
You probably need to set up networking inside the virtual machine as well.

**Comment by peterfeifanchen** [comment]
I a bit of a novice at QEMU. I tried looking [here](http://wiki.qemu.org/Documentation/Networking). But it basically said to do what I've done above to get a simple network bridge going. 

Not sure what needing to setup inside the virtual machine means...

**Comment by jenswi-linaro** [comment]
The initrd image we're using is very limited, the main purpose is to be able to run our test suite. You may need to boot a real distro instead, but then you'll need to find a way of adding the files needed by OP-TEE into that.

Changing emulated network device to `virtio-net-device` with `-netdev user,id=network0 -device virtio-net-device,netdev=network0` I'm able to setup some networking with:
```
ifconfig lo 127.0.0.1
ifconfig eth0 10.0.2.20
route add default gw 10.0.2.2
```
But I don't seem to be able to reach anything in the host, there's probably some other option missing somewhere.

**Comment by peterfeifanchen** [comment]
Okay I think I got it. Follow the tap/tun instructions [here](https://en.wikibooks.org/wiki/QEMU/Networking) and modify the up/down scripts according to your own setup.

1) manually start the qemu-ifup script (or you can pass it through the commandline in step 2
    _./qemu-ifup tap0_
2) add sudo to the run target
    add -netdev tap,id=network0,ifname=tap0,script=no (or add here), downscript=no
    add -device virtio-net-device,netdev=network0
3) once you get into the normal world, ifconfig your eth0 to the same prefixed address as whatever you set your network br to and whatever gateway the br is connected to
4) at this point, you'll be able to ping the bridge and likewise whatever the bridge is connected to.

I built a private network with tap so all I can ping is the bridge on the host side.

**Comment by srjrjjr** [comment]
How to include these scripts in the QEMU build environment? Where to place these scripts ?
