### ISSUE TITLE
xtest --stats --ta gives only zeros for my ta

### ISSUE THREAD

**Issue by ybernsteinoz** [OP-TEE/optee_os#7160]
hello, 
I compiled my qemu environment with the flags CFG_WITH_STATS=y, CFG_TA_STATS=y
and also compiled my ta with the same flags.
I run my example and the **xtest --stats --ta** in parallel (measure every 0.05 seconds)
and I only get this output:

# xtest --stats --ta
ta(<TA_1>)
	panicked(0) -- True if TA has panicked
	session number(1)
	Heap Status:
		Bytes allocated:                       128
		Max bytes allocated:                   256
		Size of pool:                          16368
		Number of failed allocations:          0
		Size of larges allocation failure:     0
		Total bytes allocated at that failure: 0

ta(<MY_TA>)
	panicked(0) -- True if TA has panicked
	session number(0)
	Heap Status:
		Bytes allocated:                       0
		Max bytes allocated:                   0
		Size of pool:                          0
		Number of failed allocations:          0
		Size of larges allocation failure:     0
		Total bytes allocated at that failure: 0

please notice that the <TA_1> always shows the same numbers. I don't know why and what is this ta.
<MY_TA> always shows zero, and **my question is why**. I have several places in my code that allocates memory.

**Comment by etienne-lms** [comment]
Malloc stats for TA <MY_TA> are 0 because when xtest queries the TA stats, there are no open session towards that TA as shown in message `session number(0)`.

**Comment by ybernsteinoz** [comment]
@etienne-lms I also have some prints that the session number is 1 (and the results are still 0):

ta(<TA_1>)
	panicked(0) -- True if TA has panicked
	session number(1)
	Heap Status:
		Bytes allocated:                       256
		Max bytes allocated:                   432
		Size of pool:                          16368
		Number of failed allocations:          0
		Size of larges allocation failure:     0
		Total bytes allocated at that failure: 0

ta(<MY_TA>)
	panicked(0) -- True if TA has panicked
	session number(1)
	Heap Status:
		Bytes allocated:                       0
		Max bytes allocated:                   0
		Size of pool:                          0
		Number of failed allocations:          0
		Size of larges allocation failure:     0
		Total bytes allocated at that failure: 0

**Comment by etienne-lms** [comment]
Crosscheck the TA you test is really the one you rebuilt with `CFG_TA_STATS=y`. Note that your TA needs to be built with a TA devkit (e.g. *.../export_ta_armXX/*) generated from OP-TEE OS that was also built  with `CFG_TA_STATS=y`.

**Comment by ybernsteinoz** [comment]
@etienne-lms here is my ta makefile:

CFG_TEE_TA_LOG_LEVEL=4
CFG_TA_OPTEE_CORE_API_COMPAT_1_1=y
CFG_TEE_TA_MALLOC_DEBUG=y
CFG_TEE_CORE_MALLOC_DEBUG=y
CFG_TA_STATS=y

# The UUID for the Trusted Application
BINARY=<MY TA>
-include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk

ifeq ($(wildcard $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk), )
clean:
	@echo 'Note: $$(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk not found, cannot clean TA'
	@echo 'Note: TA_DEV_KIT_DIR=$(TA_DEV_KIT_DIR)'
endif


Do you see any issue here?

**Comment by etienne-lms** [comment]
Check that `TA_DEV_KIT_DIR` content was built with `CFG_TA_STATS=y`.
For example, look into `$(TA_DEV_KIT_DIR)/host_include/conf.mk`.

If both OP-TEE core and libutee where built with this flag set, I cannot see how you can get zero TA heap stats with `session number(1)` as in trace shown in comment aboove (https://github.com/OP-TEE/optee_os/issues/7160#issuecomment-2511224408).

**Comment by ybernsteinoz** [comment]
@etienne-lms  hello, so I got a new devkit that was built with CFG_TA_STATS=y, and I also build the optee os for the QEMU with this flag.
but... I still get the same output. 
Is there anything specific to pay attention to while working with QEMU?
Any other idea?

**Comment by ybernsteinoz** [comment]
That was the issue, thank you very much!
