### ISSUE TITLE
A question about ARMv8 Cryptographic Extensions when enabled optee virtualization?

### ISSUE THREAD

**Issue by myspark104** [OP-TEE/optee_os#7165]
Dear all,

I have already enabled the OP-TEE virtualization feature with CFG_VIRTUALIZATION=y in OP-TEE 3.18 on the device.
Now I have a concern: if I enable ARMv8 Cryptographic Extensions with CFG_CRYPTO_WITH_CE=y, will two VMs using ARM v8 CE simultaneously operate serially or in parallel? From https://optee.readthedocs.io/en/latest/architecture/virtualization.html#sharing-hardware-resources-and-ptas, I known it can only be used by multiple VMs simultaneously is serial console, but I'm not sure about ARMv8 Cryptographic Extensions.

Thank you for your help!

**Comment by jenswi-linaro** [comment]
Interrupts are masked while using ARM v8 CE so the VMs will operate serially on a single CPU, but multiple CPUs can work in parallel.

**Comment by myspark104** [comment]
> Interrupts are masked while using ARM v8 CE so the VMs will operate serially on a single CPU, but multiple CPUs can work in parallel.

Got it! Thanks.
