### ISSUE TITLE
No ouput in UART0 on Hikey

### ISSUE THREAD

**Issue by targetnull** [OP-TEE/optee_os#717]
Note that **I have already switched it to UART0** by defining 
> CFG_NW_CONSOLE_UART ?= 0
> CFG_SW_CONSOLE_UART ?= 0

I compiled the whole optee project and then flashed it to Hikey, the flash process succeeded, but when I boot the board, there is just no output(I think the boot process is complete because the LED light is blinking normally). 

I remember that in older versions, `make flash` would also flash the bootloader. But it seems to have been removed in the latest version. Do I need to flash the l-loader.bin manually? If it is not the matter of bootloader, what else could I miss?

Thanks

**Comment by vchong** [comment]
How are you connected to UART0? Did it use to work before this? Does it work on UART3 instead?
In either case, l-loader.bin should not affect UART for the other components.

There are 2 ways to get into fastboot mode to flash the images - recovery mode (pin 1-2 3-4 closed) and UEFI fastboot mode (pin 1-2 5-6 closed), so please also check your pin settings. If you want to flash images in recovery mode, then you need to flash l-loader.bin first. It is easier to flash images from UEFI fastboot mode, i.e. you don't need to flash l-loader.bin first, which is what the makefile now defaults to.

**Comment by vchong** [comment]
Btw, just curious, are you using the 4g or 8g version of HiKey board?

**Comment by targetnull** [comment]
I use a convertor to convert USB to TTL,. This is a new Hikey board, I haven't flashed it before and I don't have a UART3 component at moment, so I'm not able to test it on UART3.

I'm using the LeMaker version, 2GB SDRAM,  and the ptable I flashed is the dedault 4g version.

**Comment by targetnull** [comment]
Should I flash the bootloader since it is a new board? But there already exists a bootloader in it, will that work too?

**Comment by vchong** [comment]
So to use UART0, you have a 2x2 male header soldered on to J801 and connected to your USB-TTL cable?

The LeMaker has an 8g flash so you need to rebuild the ptable. In hikey.mk line 366, change `PTABLE_LST=linux-4g` to `PTABLE_LST=linux-8g`, and line 412, change `ptable-linux-4g.img` to `ptable-linux-8g.img` before running `make all` and `make flash`. If it doesn't work the first time, reboot and `make flash` again to make sure the ptable has taken.

I don't know which bootloader comes out of the factory. To be safe, you can try flashing it again with the one you built. To do this, AFTER `make all`, run `make recovery` instead of `make flash`.

**Comment by targetnull** [comment]
@vchong 
I apologize for my mistake, there was something wrong with my convertor(a pin seems to be broken for unknown reasons). I change a new one and now everything is ok(I didn't change the ptable), and all the tests running with `xtest` have succeeded. So maybe I don't have to change ptable later on?

There is a little problem is that the output of both secure world and the normal world get together, thus making it hard to recognize. Is there any way to get the output separately?

Thanks a lot for your help!
Tgn

**Comment by vchong** [comment]
Ok. I checked the build script and it looks like at this point there's no difference between the 4g and 8g ptable, so yes you don't have to change ptable, at least for now.

If you want separate logs, you'll have to use both UART0 and UART3, i.e. you also need 2 cables. Then for CFG_NW_CONSOLE_UART and CFG_SW_CONSOLE_UART, set one of them to 0 and the other to 3.

**Comment by targetnull** [comment]
I see, it seems that I need to rebuild the project.

Many thanks.
