### ISSUE TITLE
[HELP] How to define load based address for loading TA

### ISSUE THREAD

**Issue by lzc1001** [OP-TEE/optee_os#7174]
Hi every experts,
I'm do some work on optee in recent, and I want to fix the load address for TA, I find that the default load based address is 0x40000000, but this address feild can not be used on FVP TC1. Then, I try to find some configuration file or head file to find some macro that define load based address, but ....,hhhh, So, I don't know how to set the load based address. It is my frist time to use optee
I run xtest 1004 on my HW, the following picture is the output log
![image](https://github.com/user-attachments/assets/f463f00f-bfb2-4b6d-8081-c59d11054d8e)
![image](https://github.com/user-attachments/assets/c1b99635-aa07-4cf9-952b-4fd4c91e6414)

and it seem that this function(core_mmu_get_user_va_range) would set load baed address, but I don't understand why used this method to set load address, because the address feild of 0x40000000 is system mmu according to FVP TC1 manual
![image](https://github.com/user-attachments/assets/0e854171-3539-43bb-ac3c-d08efe2e5cd8)
Thank you very much!

**Comment by jforissier** [comment]
> Hi every experts, I'm do some work on optee in recent, and I want to fix the load address for TA, I find that the default load based address is 0x40000000, but this address feild can not be used on FVP TC1.

Why not? 0x40000000 in this case is a VA, not a PA.

**Comment by jforissier** [comment]
I believe 0x40069d10 is in the TA at offset 0x40069d10 - 0x40041000 = 0x28d10.

**Comment by lzc1001** [comment]
Thank you very much! @jforissier
