### ISSUE TITLE
How to restart a TA if the TA paniced?

### ISSUE THREAD

**Issue by Yanjiong** [OP-TEE/optee_os#718]
Hi,

When a TA paniced, is it possible to restart it clearly from Host side?

BR.
Wang Yanjiong

**Comment by jenswi-linaro** [comment]
Yes, but keep in mind that eventual objects stored in secure storage will remain as they where then the TA paniced.

**Comment by pascal-brand-st** [comment]
Question has been answered, please re-open in case you have additional questions
