### ISSUE TITLE
Calling API functions from a static TA

### ISSUE THREAD

**Issue by aminusamine** [OP-TEE/optee_os#719]
Hello, 

I'm using a static TA to perform some work. And i want to use some API functions like TEE_GetSystemTime for instance but i can't call it from the TA. It says undefined reference to function TEE_GetSystemTime. Is there a way to call such a function from a static TA.

Thank you

**Comment by hybridNeo** [comment]
Have a look at this, if it helps https://github.com/hybridNeo/secure_quiz/blob/master/ta/ta.c

**Comment by targetnull** [comment]
@aminusamine Actually you don't have to use an API, you can directly use the functions provided by trusted OS in a static TA.
