### ISSUE TITLE
How does OPTEE switches secondary cores to normal world on multi-core platforms, such as Hikey?

### ISSUE THREAD

**Issue by bngabonziza** [OP-TEE/optee_os#731]
Hi

I am wondering how cpu core 1 ~ 7 switch to normal world on OPTEE Hikey board. It looks like only core 0 will execute the _start function at [https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/generic_entry_a64.S#L37](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/generic_entry_a64.S#L37), which has the SMC instruction at the end [https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/generic_entry_a64.S#L144](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/generic_entry_a64.S#L144).

Core 1 ~ 7 will execute the function cpu_on_handler at [https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/generic_entry_a64.S#L37](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/generic_entry_a64.S#L37), which does not include an SMC instruction.

So, my question has two parts 1) what triggers core 1 ~ 7 to execute cpu_on_handler? 2) where is the SMC instruction core 1 ~ 7 use to switch to normal world. I guess the answer is related to Trusted Firmware, but not sure.

Thank you very much.

**Comment by jenswi-linaro** [comment]
Hi,

You're right in your guesses, it's ARM-TF that triggers the cpu_on_handler. cpu_on_handler ends with an SMC switching back to ARM-TF (EL3) again and then the Dispatcher does the world change.

Regards,
Jens

**Comment by bngabonziza** [comment]
@jenswi-linaro 
Hi,
Thanks a lot for your reply, can you please points me, where in the source code to look or maybe the source file names with the calls to smc and dispatcher.

Again, thanks!

**Comment by jenswi-linaro** [comment]
One interesting function in the dispatcher is `opteed_smc_handler()` at https://github.com/linaro-swg/arm-trusted-firmware/blob/optee_paged_armtf_v1.2/services/spd/opteed/opteed_main.c#L333

OP-TEE is entered via thread_vector_table at https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread_a64.S#L155

This vector table is returned when the primary CPU returns from the initialization.

**Comment by bngabonziza** [comment]
Great thanks, but I still have some questions to help me understand better.

My understanding now is that the primary cpu gets initialized first, then passes control to ARM-TF which in turn initializes core 1 ~ 7.

My question is: in ARM-TF where is the code, if there is any, to put core 1 ~ 7 to sleep when core #0 is being initialized, and where is the code to wake them up, so they can also be initialize?

Thanks you,

**Comment by jenswi-linaro** [comment]
My understanding now is that the primary cpu gets initialized first, then
> passes control to ARM-TF which in turn initializes core 1 ~ 7.
>

Correct.


> My question is: in ARM-TF where is the code, if there is any, to put core
> 1 ~ 7 to sleep when core #0 is being initialized, and where is the code to
> wake them up, so they can also be initialize?
>
This is platform specific, but typically the secondary cores are waiting in
a platform specific plat_secondary_cold_boot_setup() until
psci_pm_ops.pwr_domain_on is called via PSCI_CPU_ON_AARCH32
or PSCI_CPU_ON_AARCH64.

**Comment by jbech-optee-adm** [comment]
Question has been answered, but If the issue persists or you have more questions, please re-open the issue.
