### ISSUE TITLE
PLAT is fvp on the Hikey branch of ARM-Trusted-Firmware

### ISSUE THREAD

**Issue by targetnull** [OP-TEE/optee_os#732]
Hi, 

I'm trying to understand the code of arm-tf of Hikey branch, but I find that the arm-tf code has chosen FVP to be its platform?(see [line 48](https://github.com/96boards-hikey/arm-trusted-firmware/blob/hikey/Makefile#.L48)).

Besides, it doesn't define any SPD(see [line 51](https://github.com/96boards-hikey/arm-trusted-firmware/blob/hikey/Makefile#.L51)), I wonder why would the optee dispatcher would still work since both platform and SPD are incorrect (at least it really worked when there is an SMC) .

The arm-tf repo seems inactive at present, so I choose to open my issue here. If you think that is irrelevant, please comment on it and I will close the issue.

Thanks.
Tgn

**Comment by jenswi-linaro** [comment]
Those options are overridden when building ARM-TF, see https://github.com/OP-TEE/build/blob/master/hikey.mk#L84

**Comment by targetnull** [comment]
Thanks, I forgot to check the top level Makefile.
