### ISSUE TITLE
How to write new QEMU bios.bin to boot android platform?

### ISSUE THREAD

**Issue by yingkailiang** [OP-TEE/optee_os#736]
I want to run optee + android on qemu (with TEE enabled). Based on the document I read from http://www.linaro.org/blog/core-dump/arm-trustzone-qemu/ 
In order to boot two OSes on single qemu emulator and enable TrustZone feature, I have to use -bios option to to initiate execution of a raw binary image. So my goal is to _generate a new bios.bin file can boot OPTEE OS and Android OS together on qemu_. (If there is more easy way to boot OPTEE OS without -bios option, please correct me.)

I take a look at the /build/qemu.mk file, following is how to generate a bios.bin file. To generate a bios.bin, we need to provide a linux kernel and root file-system for non-secure os and OPTEE OS binary for secure os. 

        +$(MAKE) -C $(BIOS_QEMU_PATH) \
                CROSS_COMPILE=$(CROSS_COMPILE_NS_USER) \
                O=$(ROOT)/out/bios-qemu \
                BIOS_NSEC_BLOB=$(LINUX_PATH)/arch/arm/boot/zImage \
                BIOS_NSEC_ROOTFS=$(GEN_ROOTFS_PATH)/filesystem.cpio.gz \
                BIOS_SECURE_BLOB=$(OPTEE_OS_BIN) \
                PLATFORM_FLAVOR=virt

Right now I can boot the linaro release android image and kernel on qemu using the follow command. 

`./qemu-system-arm -M vexpress-a9 -cpu cortex-a9 -m 1024 -machine secure=on -initrd ramdisk.img -kernel boot/kernel -sd vexpress.img -nographic`

My understanding is that -bios option can replace the functionalities of both -kernel and -initrd option in qemu. So my first question is:  to generate a new bios.bin, can I simply replace the sample linux kernel with linaro release linux kernel like following?

`BIOS_NSEC_BLOB=$(ROOT)/android_kernel/kernel `

In this case, this bios generation ignores the initrd file, will it cause any problem?

My second question is android OS use a quite different filesystem structure compare with traditional linux. I think the kernel image file already include file system, do I have to provide filesytem.cpio when generate the new bios.bin? 
If yes, any suggestion how to generate this filesystem.cpio ? 

Any suggestion will be welcomed and thanks in advance.

**Comment by jenswi-linaro** [comment]
On Fri, Apr 8, 2016 at 4:08 AM, yingkailiang0920 <notifications@github.com>
wrote:

> My understanding is that -bios option can replace the functionalities of
> both -kernel and -initrd option in qemu. So my first question is: to
> generate a new bios.bin, can I simply replace the sample linux kernel with
> linaro release linux kernel like following?
>
> BIOS_NSEC_BLOB=$(ROOT)/android_kernel/kernel
>
Yes

> In this case, this bios generation ignores the initrd file, will it cause
> any problem?
>
No, the initrd file is included in the bios.bin with what BIOS_NSEC_ROOTFS
points at.

> My second question is android OS use a quite different filesystem
> structure compare with traditional linux. I think the kernel image file
> already include file system, do I have to provide filesytem.cpio when
> generate the new bios.bin?
> If yes, any suggestion how to generate this filesystem.cpio ?
>
You could just point  BIOS_NSEC_ROOTFS at the ramdisk.img used by android.

Regards,
Jens

**Comment by yingkailiang** [comment]
hi @jenswi-linaro , thanks for your response. It helps a lot. Here I have one more question. 

The PLATFORM_FLAVOR value qemu.mk provide is _virt_ type. If I want to run on vexpress-a9 instead of virt machine. What value should I put into PLATFORM_FLAVOR field?

**Comment by yingkailiang** [comment]
I found the answer in bios_qemu_tz_arm/bios/platform_config.h. The value _vexpress_  works for me. Thanks for you assistant again.  @jenswi-linaro

**Comment by romanliv** [comment]
Hi @yingkailiang.
Old discussion, I know, but did not find any better reference than this.
Can you please elaborate a bit more how you managed to run Android + op-tee on qemu?
Did you achieve running Android UI?
If you succeeded with this, how did you map system.img and userdata.img? According to http://www.linaro.org/blog/core-dump/running-64bit-android-l-qemu/ it is doable, but I had no success while doing this with qemu -bios option.
From where did you take the "linaro release linux" referred as
`BIOS_NSEC_BLOB=$(ROOT)/android_kernel/kernel`
above?
Thank you.

**Comment by vchong** [comment]
@romanliv See https://github.com/OP-TEE/optee_os/issues/1246#issuecomment-269849208. @yingkailiang has moved to a "hikey + android + optee" solution.
