### ISSUE TITLE
How to switch OPTEE running machine type to vexpress-a9 instead of virt on QEMU?

### ISSUE THREAD

**Issue by yingkailiang** [OP-TEE/optee_os#737]
I run optee_os on QEMU platform. I checked the running script in build/qemu.mk. The machine type used in sample is **virt**. _My goal is to change qemu machine type to vexpress-a9_ , because eventually I want to boot android +optee on qemu and right now I only have android image and kernel which support vexpress platform. To achieve the goal, I modify the running command to be following: 
`
$(QEMU_PATH)/arm-softmmu/qemu-system-arm
                -nographic 
                -serial tcp:localhost:54320 -serial tcp:localhost:54321 
                -s -S -M vexpress-a9 -machine secure=on -cpu cortex-a15 
                -m 1024
                -bios $(ROOT)/out/bios-qemu/bios.bin $(QEMU_EXTRA_ARGS)`

I also change the qemu-bios-common platform_flavor to vexpress in qemu.mk. Following is how I change  

        +$(MAKE) -C $(BIOS_QEMU_PATH) \
                CROSS_COMPILE=$(CROSS_COMPILE_NS_USER) \
                O=$(ROOT)/out/bios-qemu \
                BIOS_NSEC_BLOB=$(LINUX_PATH)/arch/arm/boot/zImage \
                BIOS_NSEC_ROOTFS=$(GEN_ROOTFS_PATH)/filesystem.cpio.gz \
                BIOS_SECURE_BLOB=$(OPTEE_OS_BIN) \
                PLATFORM_FLAVOR=vexpress

Before I made these change, the virt machine type works fine and I can run the [helloworld](http://www.slideshare.net/linaroorg/lcu14103-how-to-create-and-run-trusted-applications-on-optee) example. 
The above two places are all the change I made, the compilation is succeed. After run qemu by typing "make all run", two serial xterm does not show any message other than socket connection message. 

My question is in order to change qemu machine type to vexpress-a9, did I make the correct modification? Or any other places should I modify as well? 

Any suggestion are welcomed and thanks in advance.

**Comment by jenswi-linaro** [comment]
I'm not sure if the `vexpress-a9 ` machine supports secure mode properly and even if it does you would need to port OP-TEE to that machine as we're using hard coded based addresses etc instead of reading it from device tree.

**Comment by yingkailiang** [comment]
Secure mode is to support OP-TEE on qemu, am I right? 
For qemu secure mode, only virt type are supported certainly?

**Comment by jenswi-linaro** [comment]
I know for sure the secure mode works with virt, for the others I don't know.

**Comment by vchong** [comment]
This might help: http://www.linaro.org/blog/core-dump/testing-qemu-arm-trustzone

- The Security Extensions will be available only on machines supporting ARM1176, Cortex-A8, Cortex-A9, and Cortex A-15 CPUs.
- The ARM Security extensions are currently only supported, and enabled by default, on the Versatile Express and the virt machine models. All other machine models will have the ARM Security extensions disabled by default.

**Comment by yingkailiang** [comment]
Thanks for clarify.
