### ISSUE TITLE
How to access sharedmemory from kernel space?

### ISSUE THREAD

**Issue by targetnull** [OP-TEE/optee_os#742]
Hi,

I want to send some special data which cannot be accessed from kernel space, but it fails. Here is what I try to do: when it enters `tee_ioctl_open_session`(in [https://github.com/linaro-swg/linux/blob/gendrv/drivers/tee/tee.c#.L239](https://github.com/linaro-swg/linux/blob/gendrv/drivers/tee/tee.c#.L239)), I try to access param[n].u.memref.shm->kaddr right after it has copied params from user and right before it invokes open_session(I do the access in [line 280](https://github.com/linaro-swg/linux/blob/gendrv/drivers/tee/tee.c#.L280))

I inserted this line `printk(KERN_INFO "%p", param[n].u.memref.shm->kaddr )` to line 280, but it causes an NULL pointer error(have already allocated SharedMemory in tee_client_api.c before it enters kernel space), says

>XTEST_TEE_1001 Core self tests
[  299.696033] Unable to handle kernel NULL pointer dereference at virtual address 00000008
[  299.696110] pgd = ffffffc87aa4e000
[  299.696165] [00000008] *pgd=00000008faa53003, *pud=00000008faa53003, *pmd=0000000000000000
[  299.696284] Internal error: Oops: 96000006 [#1] PREEMPT SMP
[  299.696343] Modules linked in:
[  299.696415] CPU: 1 PID: 850 Comm: xtest Not tainted 4.5.0 #6
[  299.696480] Hardware name: Foundation-v8A (DT)
[  299.696552] task: ffffffc87ab34800 ti: ffffffc87aa94000 task.ti: ffffffc87aa94000
[  299.696649] PC is at tee_ioctl+0xb34/0xc5c
[  299.696729] LR is at tee_ioctl+0x930/0xc5c
[  299.696798] pc : ffffffc0005c539c lr : ffffffc0005c5198 pstate: 60000145

It's a little strange because I just want to print out its address rather than its value. The `shm->kaddr` seems indeed to be a virtual address, should I directly access physical using `shm->paddr` instead? There must be someway to achieve this, but I don't know much about how to access it from kernel space. Could anyone please help me with it?

Thanks.

=================================================
**EDIT:**
It turned out that the shm was not allocated normally for unknown reasons even if I run `make all-clean`, so I rolled back to a former status and run `repo sync` again. At least the hello_world example is OK now and I can print out the address of `shm`.

But I haven't tested wether I can modify the content of SharedMemory in kernel space, I'll try it asap.

**Comment by pascal-brand-st-dev** [comment]
Also please not that the current supported driver is no more  https://github.com/linaro-swg/linux/tree/gendrv, but  https://github.com/linaro-swg/linux/tree/optee instead.

**Comment by jbech-optee-adm** [comment]
Question has been answered and it seems like you have been able to get it working by updating repositories, cleaning and rebuild, but if the issue persists or you have more questions, please re-open the issue.
