### ISSUE TITLE
CreatePersistentObject after running application again

### ISSUE THREAD

**Issue by SyedElec** [OP-TEE/optee_os#745]
Hey,

i have some questions about CreatePersistentObject function.
First is, according to documentation, it's written "optionally returns [either] a handle on the created object" however your implementation does not give choice, we have to specify an object handler, if not it will fails, is it normal ?
I want to call my function with 
`TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE, id, id_len, TEE_DATA_FLAG_OVERWRITE, NULL, NULL, 0, NULL (instead of &object));`

Second is, when I run a really basic application with CreatePersistentObject function only, it will create my persistent object and is not deleted at the end of the application, this is fine. But if I run again my application, I have a TEE PANIC with FFFF3024 error code. i don't understand why, I use the TEE_DATA_FLAG_OVERWRITE flag so it should overwrite the persistent object if it already exists or am I missing something ?

Thank you for your help.

**Comment by jenswi-linaro** [comment]
This is a bug, I've experienced the same problem.
