### ISSUE TITLE
Shared memory data corruption 

### ISSUE THREAD

**Issue by niteshnarayanlal** [OP-TEE/optee_os#746]
When data of size 29 bytes or above is transmitted from TA to the host side, we have seen data corruption.
Kindly suggest the area where I should look into or let me know if you need any dumps?

**Comment by jenswi-linaro** [comment]
What kind of data corruption are we talking about, overwritten memory (kernel or user space) or just unexpected output?
How is this data transmitted, shared memory via parameters for the TA or during RPC?

**Comment by niteshnarayanlal** [comment]
The data sent from TA to the host gets modified.
Data transmission is done through shared memory via parameters for the TA.

**Comment by jenswi-linaro** [comment]
So you do an invoke and the TA fills in something in an out/inout memref?

It could be a cache issue or perhaps has the reservation of the shared memory range failed. Does the memory range used for shared memory show in `/debug/memblock/reserved`?
Are you using any of our supported platforms?

**Comment by niteshnarayanlal** [comment]
I am using (Freescale)FSL LS1 platform.
The shared memory range is allocated by using TEEC_AllocateSharedMemory.

**Comment by jenswi-linaro** [comment]
First step is to verify that `CFG_SHMEM_START` and `CFG_SHMEM_SIZE` is covered by an entry in `/debug/memblock/reserved` or that the address ranges isn't in `/debug/memblock/memory`.

@MrVan, @b49020 do you have any other suggestions?

**Comment by niteshnarayanlal** [comment]
Issue is with the TEEC_RegisterSharedMemory API usage in the  host application (removing it resolved the issue).
