### ISSUE TITLE
xtest 1008 assumes TAs are writable

### ISSUE THREAD

**Issue by d3zd3z** [OP-TEE/optee_os#748]
xtest number 1008 (currently 1008.5) tests that the system will refuse to work with various corrupt TAs.  It does this by modifying the test TAs in place.  This makes an assumption that this directory is writable.

On Android, the /system partition, where most things are written, and likely where people will want to put TAs is not writable, and recent versions of Android seem to prevent the partition from even being remounted as read-write.

    o XTEST_TEE_1008.5 Load corrupt TA
    external/optee_test/host/xtest/xtest_1000.c:633: r has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:730: load_corrupt_ta(c, __builtin_offsetof(struct shdr, magic), 1) has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:633: r has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:732: load_corrupt_ta(c, __builtin_offsetof(struct shdr, img_type), 1) has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:633: r has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:734: load_corrupt_ta(c, __builtin_offsetof(struct shdr, img_size), 1) has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:633: r has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:736: load_corrupt_ta(c, __builtin_offsetof(struct shdr, algo), 1) has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:633: r has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:738: load_corrupt_ta(c, __builtin_offsetof(struct shdr, hash_size), 1) has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:633: r has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:740: load_corrupt_ta(c, __builtin_offsetof(struct shdr, sig_size), 1) has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:633: r has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:742: load_corrupt_ta(c, sizeof(struct shdr), 1) has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:633: r has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:744: load_corrupt_ta(c, sizeof(struct shdr) + 32, 1) has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:633: r has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:745: load_corrupt_ta(c, 3000, 1) has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:633: r has an unexpected value: 0x0 = false, expected 0x1 = true
    external/optee_test/host/xtest/xtest_1000.c:746: load_corrupt_ta(c, 30000, 1) has an unexpected value: 0x0 = false, expected 0x1 = true
      XTEST_TEE_1008.5 FAILED
      XTEST_TEE_1008 FAILED

**Comment by jenswi-linaro** [comment]
The quick fix is likely to skip the test case if we discover that the file is read-only.

Long term we'll probably want a way to deploy new TAs without reflashing /system.

**Comment by d3zd3z** [comment]
Perhaps something like a TA load path, rather than just a single directory?

**Comment by jenswi-linaro** [comment]
Sure, that would work.

**Comment by d3zd3z** [comment]
Another suggestion was to just install the corrupt TAs instead of trying to modify existing ones.

**Comment by d3zd3z** [comment]
Fix at [optee_client#54](https://github.com/OP-TEE/optee_client/pull/54) [optee_test#109](https://github.com/OP-TEE/optee_test/pull/109).

**Comment by d3zd3z** [comment]
Fix has been merged in other repos.
