### ISSUE TITLE
Adding xterminal for QEMU build for OP-TEE

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#750]
Just wondering, if I want an extra xterminal for the normal or secure world for QEMU, how would I get that? Thanks!

**Comment by jenswi-linaro** [comment]
Currently QEMU virt has two uarts, one for normal world and one for secure world. Are you asking for an additional uart? As far as I know that can't be done without modifying the model.

**Comment by peterfeifanchen** [comment]
Could I open two xterm to the same UART? I am not sure if that is possible in this case. I was thinking kind of like how you can open two SSH to a machine.

**Comment by jenswi-linaro** [comment]
What would you expect to see, the same output in both? That can be achieved with screen or tmux.

**Comment by peterfeifanchen** [comment]
I just want to say enter one command on one terminal and then run concurrent commands in the other.

**Comment by jenswi-linaro** [comment]
That would require additional uarts.

**Comment by peterfeifanchen** [comment]
I see. Is it hard to do that? If it is, I might just make do.

**Comment by jenswi-linaro** [comment]
You would need to patch qemu a bit (hw/arm/virt.c and include/hw/arm/virt.h). I assume it's a uart for normal world so you'll probably need to update the rootfs to get something to listen on the new uart too.

**Comment by peterfeifanchen** [comment]
Alright, I'll see if I can make do with one...Thanks! :)
