### ISSUE TITLE
OP-TEE TA concurrency and isolation

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#751]
Sorry if the question is a bit general. But I was wondering:

1) How are TA's protected from each other? What prevents a malicious TA from reading say the secure files of another TA or some common secret (e.g., keys) stored in SW?

2) If I have a TA servicing multiple clients in the NW and these clients are read/write on some shared variable in the TA, who should be handling concurrency? The client? The TA? OP-TEE driver/os will serialize?

Thanks.

**Comment by targetnull** [comment]
+1.

**Comment by jenswi-linaro** [comment]
On Wed, Apr 20, 2016 at 10:17 AM, peterfeifanchen <notifications@github.com>
wrote:

> Sorry if the question is a bit general. But I was wondering:
>
> 1) How are TA's protected from each other? What prevents a malicious TA
> from reading say the secure files of another TA or some common secret
> (e.g., keys) stored in SW?
>
A TA can only access/see objects created by itself, the check is based on
the UUID of the TA. If I'm not mistaken there's currently a weakness in the
protection of the objects in the way that they are all encrypted with the
same key so if tee-supplicant would supply an object belonging to another
TA it would be possible to access the object.

> 2) If I have a TA servicing multiple clients in the NW and these clients
> are read/write on some shared variable in the TA, who should be handling
> concurrency? The client? The TA? OP-TEE driver/os will serialize?
>
Only one instance of a TA can be executing at a time, that is, the second
invoke will wait for the first to complete before it starts. If a TA is a
multi-instance TA it can execute in several instances concurrently, but
they will not share any secure memory. They can however use the same normal
world shared memory and there's no synchronization primitives available for
the TA to deal with that, or even detect that.

**Comment by peterfeifanchen** [comment]
Thanks, I think I understand 1). 

For 2) I was more asking along the lines of if I initialize a context and then start two sessions to the same TA instance. How would two simultaneous invokes be serialized and where? Or if I create two contexts and call for the same TA instance, again both send invokes, where do they get serialized? Is your answer saying that they would still execute one after the other somehow in the TA even if they come from different threads in the Normal World? If so, is it the linuxdriver or the optee-os that provides this?

**Comment by jenswi-linaro** [comment]
The calls are serialized in (OP-TEE core) `tee_ta_invoke_command()` by a call to `tee_ta_set_busy()`.

**Comment by peterfeifanchen** [comment]
Thanks I see.
