### ISSUE TITLE
Issue while using TEEC_RegisterSharedMemory

### ISSUE THREAD

**Issue by niteshnarayanlal** [OP-TEE/optee_os#755]
We have a TA & Host application which was working fine with the release 1.0.0.
In our host application source, we have used both TEEC_RegisterSharedMemory & TEEC_AllocateSharedMemory. 
As per the documentation we can use either one of them and it should solve our purpose of fetching shared memory for communication between TA & Host. But in the above scenario when I tried running the application by removing TEEC_AllocateSharedMemory and fetching the shared memory via TEEC_RegisterSharedMemory, I got segmentation fault. The same thing works fine if I remove TEEC_RegisterSharedMemory and keep TEEC_AllocateSharedMemory.

**Comment by pascal-brand-st-dev** [comment]
Do you think you can create a unit test that reproduces this issue so that we can investigate? The best would to have a new xtest added in https://githhub.com/OP-TEE/optee_test

Is this issue related to https://github.com/OP-TEE/optee_os/issues/754?

**Comment by niteshnarayanlal** [comment]
Sorry for the delay in response, I will prepare a unit case as I find some time and get back to you.

**Comment by jbech-linaro** [comment]
@niteshnarayanlal , is this still on your radar? I.e., creating a test case as Pascal asked for?

**Comment by niteshnarayanlal** [comment]
Unfortunately no, not at the moment.
I am closing it for now, if I face any issue I will reopen it.
