### ISSUE TITLE
issue while a user TA call a static TA

### ISSUE THREAD

**Issue by zhupg** [OP-TEE/optee_os#756]
There is a failure while a user TA call a static TA, the demo code is as follow:
-----------------------------------------------------------------------------------------------------------------------
    char *buf[10];
    res = TEE_OpenTASession(&uuid, 0, types, params, &session, &origin);
    types =
        TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT, TEE_PARAM_TYPE_NONE,
                TEE_PARAM_TYPE_NONE, TEE_PARAM_TYPE_NONE);

    params[0].memref.buffer = buf;
    params[0].memref.size = sizeof(10);

    res = TEE_InvokeTACommand(session, 0, CMD_ID_TEST, types, params, &origin);
-----------------------------------------------------------------------------------------------------------------------
The function TEE_InvokeTACommand() return with error code 0xFFFF000F, because parameters check fail(the function tee_ta_verify_param()).
If a user TA call another user TA, this error don't appear.

Is there any different between static TA and user ta? Is static TA also run in user space as user TA?

**Comment by jenswi-linaro** [comment]
Please test with latest, https://github.com/OP-TEE/optee_os/pull/752 addresses this.

**Comment by jbech-optee-adm** [comment]
Question has been answered, but If the issue persists or you have more questions, please re-open the issue.
