### ISSUE TITLE
HiKey and QEMU linux read-only sys_call_table symbol 

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#758]
Hi, I was looking at the System.map of the compiled linux image from the repo builds. I was wondering if there is a way to compile the image such that the sys_call_table symbol is Read-only rather than T or D. This question might be more linux than optee, so if anyone know where to direct me to more properly ask this question, that would be great too!

Also as a tag-on, does ARM have an equivalent to x86's CR0 register's write-protection bit? If so, which register or co-processor should I look at? Thanks.

**Comment by jbech-linaro** [comment]
Very late reply, I have no good answer to your questions and since no-one else have answered it I think it's like you said more of a Linux kernel question than OP-TEE.

CR0 equivalent? Well, maybe SCR, SCTRL, CPACR, DACR could do something related to that.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
