### ISSUE TITLE
rpc_load failed in user_ta.c due to OPTEE_MSG_RPC_CMD_SHM_ALLOC is handled by new Linux driver

### ISSUE THREAD

**Issue by xzhao10** [OP-TEE/optee_os#760]
Hi,

I am working on optee in ASR-Micro, a new Chinese start-up focusing on ARM SoC.

I am trying enable the optee version 2.0 with the new Linaro linux driver on ARMv8 SoC in VDK environment, and meet one issue: session creation using user TA fails due to the rpc_load fails.

I noticed in the optee_os, the rpc_load will query the TA size first, then fire a rpc command OPTEE_MSG_RPC_CMD_SHM_ALLOC to get the buffer for TA loading.  In version 1.1, this was handled by tee-supplicant in process_alloc().  However, in 2.0, this is handled by the Linux driver, so tee-supplicant won't be aware of the share memory allocation call, and it won't update the shm_head variable.  Thus, when the second rpc call (OPTEE_MSG_RPC_CMD_LOAD_TA） from optee os arrives the normal world attempting to load the user TA, tee-supplicant will fail due to shm_head is still NULL (in get_param() within load_ta()).

Can any one give me suggestions on how to fix this issue?  Thanks.

Henry Zhao

**Comment by jforissier** [comment]
Hi,

The issue you're having reminds me of a similar one when I was testing the new driver on HiKey. I had checked out the wrong kernel branch, hence the wrong driver. Can you make sure you are using https://github.com/linaro-swg/linux/tree/optee?

**Comment by xzhao10** [comment]
Thank you very much for your prompt response.

The problem is root-caused as wrong branch of the Linux..as the default branch is not optee after git clone.  Now this issue is closed.
