### ISSUE TITLE
File corruption with PersistentObject

### ISSUE THREAD

**Issue by SyedElec** [OP-TEE/optee_os#763]
Hi,

I'm experiencing file corruption when using TEE_RenamePersistentObject and in one other case. I've simplified both problems to the following codes :

1)

```c

TEE_ObjectHandle object = NULL;
TEE_ObjectHandle object_renamed = NULL;

int object_id = 0;
int object_id_renamed = 1;

uint32_t flags = TEE_DATA_FLAG_ACCESS_READ | TEE_DATA_FLAG_ACCESS_WRITE |
                 TEE_DATA_FLAG_ACCESS_WRITE_META

TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE, &object_id, sizeof(object_id), flags,
						   TEE_HANDLE_NULL, NULL, 0, &object);

TEE_RenamePersistentObject(object, &object_id_renamed, sizeof(object_id_renamed));

TEE_CloseObject(object);

TEE_OpenPersistentObject(TEE_STORAGE_PRIVATE, &object_id_renamed, 
						 sizeof(object_id_renamed), flags, &object_renamed);

```

The function TEE_OpenPersistentObject fails with TEE_ERROR_CORRUPT_OBJECT if I use the TEE_CloseObject(object) 
(it fails with TEE_ERROR_ACCESS_CONFLICT if I comment the line TEE_CloseObject(object))

2)
```c
TEE_ObjectHandle object = TEE_HANDLE_NULL;
TEE_ObjectHandle object_opened = TEE_HANDLE_NULL;

int object_id = 0;

uint32_t flags = TEE_DATA_FLAG_ACCESS_READ | TEE_DATA_FLAG_ACCESS_WRITE;

ret = TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE, &object_id, sizeof(object_id), flags, 
								 TEE_HANDLE_NULL, NULL, 0, &object);
TEE_CloseObject(object);

if (ret == TEE_ERROR_ACCESS_CONFLICT) {

	ret = TEE_OpenPersistentObject(TEE_STORAGE_PRIVATE, &object_id, sizeof(object_id), 
								   flags, &object_opened);

	TEE_CloseObject(object_opened);
}
```

The first time I execute this code, it's fine, however, if I execute it twice in a loop, I enter the condition and the TEE_OpenPersistentObject fails with TEE_ERROR_CORRUPT_OBJECT. I would have understood if it was TEE_ERROR_ACCESS_CONFLICT but why a file corruption ?
Again if I comment the line TEE_CloseObject(object), I will have the TEE_ERROR_ACCESS_CONFLICT error.

Thank you for your help.

**Comment by pascal-brand-st-dev** [comment]
I cannot reproduce the described issues, when using master branch, or when using 2.0.0 version, on QEMU.
What optee_os sha1 are you based on?

**Comment by SyedElec** [comment]
That was my mistake, I was not using the latest version 2.0.0 (or master branch), sorry.
Thank you, I close the issue.
