### ISSUE TITLE
Enlarging the stack size and 32KB TA size

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#765]
Hi, I was wondering how I should go about to enlarge the size allowed for a TA and the stack size of the TA? What would I have to change? 

Rather than the default 32KB TA size and 2KB stack size, I would like to make it 64KB and 8KB. Thanks.

**Comment by jenswi-linaro** [comment]
There's actually no default values for stack and heap size, they always need to be specified in `user_ta_header_defines.h` which describes the properties of the TA.

**Comment by peterfeifanchen** [comment]
So does that mean the maximum size of a TA is arbitrary (e.g. I can enlarge the stack and heap as much as I want)? As long as I don't hit the limit of the actual TEE memory size itself?

**Comment by jenswi-linaro** [comment]
Yes, that's correct.

**Comment by jbech-optee-adm** [comment]
Question has been answered, but if you have more questions, please re-open the issue.

**Comment by ademyankov** [comment]
@jenswi-linaro Is there TEE memory size limit variable somewhere? Because my TA ties to allocate 32Kb block of memory and it fails, returns NULL, I presume it means no memory available.

**Comment by jbech-linaro** [comment]
Did you tweak the size in the file @jenswi-linaro referred to in previous reply? I.e., as example [here](https://github.com/linaro-swg/optee_examples/blob/master/hotp/ta/user_ta_header_defines.h#L22-L23).

**Comment by ademyankov** [comment]
@jenswi-linaro  Shoot! It works now, thanks. Sorry for bothering for nothing. That was the first think I checked! I knew I changed **TA_DATA_SIZE** to a few megs, but for some reason the value turned out to be the old one a few hundreds Kbs. Messed up my code somehow. :)

Cheers!

**Comment by jbech-linaro** [comment]
Happy to help!
