### ISSUE TITLE
Sending the TA a RSA public-private key pair

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#766]
I am trying to have my TA decrypt a symmetric key that has been encoded by an arbitrary public key. I want to give the TA the private key to decrypt such a piece of data that had been encrypted. I am thinking of something like an invoked command that allows the normal world to register a private-public key pair. I am also using tomlibcrypt on the normal world side. There is this load_rsa_key() in tomlibcrypt, but I don't see any internal APIs that would support this. So is the best way to add my own utee syscall?

**Comment by jenswi-linaro** [comment]
Is this part of some key deployment scheme or just for testing? In either case, I wouldn't extend the TA api, instead divide the key-pair into components and create a transient or persistent object to be able to use the available api.

**Comment by pascal-brand-st-dev** [comment]
xtest 4006 provides examples how keys are transmitted from normal-world to secure-world (see https://github.com/OP-TEE/optee_test/blob/master/host/xtest/xtest_4000.c#L3762)

**Comment by jenswi-linaro** [comment]
Keep in mind that this is for test. It's not supposed to be a good example of how to write secure code.

**Comment by peterfeifanchen** [comment]
I am not trying to build a secure key deployment scheme. I am working on a research project that just requires me to be able to register public/private RSA key pair. So after looking at the code a bit more closely and the internal APIs, would the following be a good idea?

1) call load_rsa_key() in normal world
2) copy the contents of rsa_key struct (they are all fip_int) to Trusted World through shared memory.
3) set up a transient object and set the key attributes according to rsa_key struct values
4) use the internal API to create a persistent object for this key from the transient object
5) now I can load the rsa key from secure storage at a later time

**Comment by jenswi-linaro** [comment]
Yes, that looks good. The link provided by Pascal can save you some time with serializing attributes also.

**Comment by peterfeifanchen** [comment]
Thanks! Last thing, would you or Pascal be able to point me to a good reference in xtest_ac_cases, there seems to be lots!

**Comment by jenswi-linaro** [comment]
`xtest_add_attr()`, `xtest_add_attr_value()` and `pack_attrs()` deals with serializing attributes, then there a corresponding function `unpack_attrs()` in `ta/crypt/cryp_taf.c` to transform it back to an array of `TEE_Attribute`

**Comment by jbech-optee-adm** [comment]
Question has been answered, but if you have more questions, please re-open the issue.
