### ISSUE TITLE
Debugging test case using gdb : No symbol table is loaded

### ISSUE THREAD

**Issue by radheshkrishnan** [OP-TEE/optee_os#768]
Hi,

I am trying to debug a test case using GDB (QEMU).  I successfully set breakpoint on the target test function; however, not able to step through each line of the code. Following is what I tried:

1. Added following script to $HOME/.gdbinit
```
     set print array on
     set print pretty on
     define optee
       handle SIGTRAP noprint nostop pass
       symbol-file /home/krish/devel/optee/optee_os/out/arm/core/tee.elf
       target remote localhost:1234
    end
     define xtest
       handle SIGTRAP noprint nostop pass
       symbol-file /home/krish/devel/optee/optee_test/out/xtest/xtest
       target remote localhost:1234
    end
    document optee
      Loads and setup the binary (tee.elf) for OP-TEE and also connects to the
      remote.
   end
```
2. started the  QEMU with command 
   
  $ make all run
3. started GDB
     
     $ $HOME/devel/optee/toolchains/aarch32/bin/arm-linux-gnueabihf-gdb -q  
4.  Connect to remote and load tee
     $ (gdb) xtest

5.  Set break point on the target test function xtest_tee_test_4005.
    $ (gdb) b xtest_tee_test_4005
       Breakpoint 1 at 0x175d0.
6. continued  
   $ (gdb) c
    Continuing.

7.  Ran the test case and got a hit at breakpoint
   $ Breakpoint 1, 0x000175d0 in xtest_tee_test_4005 ()
    (gdb) n
   
8. At point the QEMU is stuck/hang. Not able to step through each line of code.

Another problem I am facing is, when I try to debug "optee" as explain [here](https://github.com/OP-TEE/optee_os/blob/master/documentation/debug.md#13-scripts). I am not able to set breakpoint at function "tee_entry". It throws "function not defined" error. Am I missing something here?

Thanks in advance.

**Comment by jenswi-linaro** [comment]
xtest is a Linux user space process, the mapping of that process is only available when the process is executing. To debug Linux user space processes you need to run a debugger in Linux user space.

The `tee_entry()` function is no more, it's replaced by `tee_entry_std()` and `tee_entry_fast()`.

**Comment by radheshkrishnan** [comment]
Thank you for your reply. So I have to push the gdb binary to qemu and debug inside normal world, yes that make sense.  I tried to use a gdb binary inside qemu and I am getting following two errors:

```
$ gdb xtest

Errors:
1. dlopen failed on libthread_db.so.1
2. Darf error : Wrong version in compilation unit header (is 4, should be 2)
```

I think I have to change the "g3" flag to "-g" in corresponding Makefiles? Am I right?
I am  bit stuck  there.  

`tee_entry_std` worked. May be we have to fix the documentation [here](https://github.com/OP-TEE/optee_os/blob/master/documentation/debug.md#13-scripts)? 

I am closing this issue. Please feel free to comment.

**Comment by jenswi-linaro** [comment]
As pull request to update the documentation is welcome. :-)

It guess it should world if you cross compile gdb with the same toolchain which is used when compiling xtest, but I suspect it will be more work that it's worth.
