### ISSUE TITLE
math function support issue

### ISSUE THREAD

**Issue by Yanjiong** [OP-TEE/optee_os#770]
Hi,

It seems currently, some math functions not supported as round, sqrt, log...  Any plan to support this?

Thanks.

BR.
Wang Yanjiong

**Comment by pascal-brand-st-dev** [comment]
This is because lib math is not part of the GlobalPlatform Internal API.
We do not have planned to support it.

**Comment by Yanjiong** [comment]
Thanks.

**Comment by jbech-optee-adm** [comment]
Question has been answered, but if you have more questions, please re-open the issue.
