### ISSUE TITLE
'Hello world' build not working

### ISSUE THREAD

**Issue by Dani2735** [OP-TEE/optee_os#776]
Hello, I'm trying to build and execute the 'Hello world' program in optee environment, and I get some errors in the building. 

I followed that guide: https://github.com/jenswi-linaro/lcu14_optee_hello_world/blob/master/README.md

And these are the errors I get:
![issue](https://cloud.githubusercontent.com/assets/16964329/15066669/51d4ba40-136b-11e6-9d03-ce23b5295346.png)

Can someone help me please?

Thanks!

**Comment by LeiShenHeros** [comment]
I guess your normal world user space is 64-bit,and you need to change the HOST_CROSS_COMPILE
`export HOST_CROSS_COMPILE=$PWD/../toolchains/aarch64/bin/aarch64-linux-gnu-
`

**Comment by Dani2735** [comment]
I did it, here it's the result: 
![issue2](https://cloud.githubusercontent.com/assets/16964329/15068036/d123b0fe-1374-11e6-9719-e4a5a726b0c9.png)

**Comment by LeiShenHeros** [comment]
are you finish all  steps? :）
`
export HOST_CROSS_COMPILE=$PWD/../toolchains/aarch64/bin/aarch64-linux-gnu-
export TA_CROSS_COMPILE=$PWD/../toolchains/aarch32/bin/arm-linux-gnueabihf-
export TEEC_EXPORT=$PWD/../optee_client/out/export
export TA_DEV_KIT_DIR=$PWD/../optee_os/out/arm/export-ta_arm32
`
before make ,you need do a `make clean`

**Comment by Dani2735** [comment]
Yep! All steps done but still not working...

This is the output of the make clean:

![issue3](https://cloud.githubusercontent.com/assets/16964329/15068781/e3d44d08-1379-11e6-8c55-5fed4695c92e.png)

**Comment by LeiShenHeros** [comment]
I can't see the image

**Comment by Dani2735** [comment]
Here I post it again:

![issue4](https://cloud.githubusercontent.com/assets/16964329/15069293/f8cf8eea-137c-11e6-8f02-ddc906da8935.png)

**Comment by LeiShenHeros** [comment]
At first,you need to make  OPTEE in /optee/build :)

**Comment by Dani2735** [comment]
If you mean to do a make all run at the build path it's done too, but if I try to run the 'Hello world' in the Normal world it tells me that it's not found. :(

**Comment by LeiShenHeros** [comment]
I'm not this mean,this mistake is system can't find ta_dev.kit.mk,after make optee,this file will be put into /out/arm/export-ta_arm32/mk/

**Comment by Dani2735** [comment]
Oh yes, I just found it! 'ta_dev.kit.mk' it's in that path: /optee_os/ta/mk

I guess that if I could change the path I would be able to solve the problem, right?

**Comment by Dani2735** [comment]
I changed the path in the makefile and it looks that it worked :)

Now I have two new issues... Should I build in normal mode or in superuser? 

![issue5](https://cloud.githubusercontent.com/assets/16964329/15069931/4fb4a4b2-1381-11e6-89b3-65ed8e3f6e9e.png)

Thank you for your time!

**Comment by LeiShenHeros** [comment]
you need to make it in superuser,and put it into filesystem

**Comment by Dani2735** [comment]
Right, done, this is the output:
![issue](https://cloud.githubusercontent.com/assets/16964329/15071254/76b3835e-138a-11e6-97be-54f2c9d726ce.png)

It looks like there is a library called 'teec' that is not found.

**Comment by LeiShenHeros** [comment]
This look like the system can't find  TEEC_EXPORT,can you find this file in /../optee_client/out/export

**Comment by Dani2735** [comment]
Yes, there are 3 folders inside /export which are /bin, /include and /lib.

Inside /lib there are 3 files called 'libteec.so', 'libteec.so.1' and 'libteec.so.1.0'.

**Comment by LeiShenHeros** [comment]
:),you need to do a `make clean` in lcu14_optee_hello_world,and set these path again

**Comment by Dani2735** [comment]
I've done, but it throws me another error :(

![issues](https://cloud.githubusercontent.com/assets/16964329/15071484/49931e64-138c-11e6-98e0-9f9f4d42792b.png)

**Comment by LeiShenHeros** [comment]
There is an error is normal.just make clean,and set these path and try again.:)

**Comment by Dani2735** [comment]
Yes of course, I've done that, but same error appears... :(

Thank you again for your pattience, I hope we can fix it soon!

**Comment by LeiShenHeros** [comment]
you should't to change Makefile,please change back

**Comment by Dani2735** [comment]
Changed to the original one and still failing :(

**Comment by LeiShenHeros** [comment]
please show your mistake

**Comment by Dani2735** [comment]
I'm sorry, I've been out of office until now. Hope you had a nice weekend :)

This is the error that I get:

![issue](https://cloud.githubusercontent.com/assets/16964329/15105444/f0e68570-15c1-11e6-84fe-0f796e79339c.png)

Thanks in advance!
