### ISSUE TITLE
Error building toolchains

### ISSUE THREAD

**Issue by Dani2735** [OP-TEE/optee_os#779]
Hello, I'm getting this error building toolchains:

![issue2](https://cloud.githubusercontent.com/assets/16964329/15108374/e84bb6a6-15d5-11e6-84ed-3772f1c64ad2.png)

Can someone help me please?

Thanks in advance.

**Comment by jforissier** [comment]
It looks like the location of the archive has changed. You need to add `-L` to the `curl` command in `common.mk`.

**Comment by Dani2735** [comment]
Sorry, I don't understand what you are saying. I've just searched in common.mk but curl command not found.

**Comment by jforissier** [comment]
Excuse-me, I meant `toolchain.mk`. Are you using the latest `build.git`? I don't think so because `-L` is present in https://github.com/OP-TEE/build/blob/master/toolchain.mk#L22-L33.

**Comment by Dani2735** [comment]
Fixed! Thank you so much :)
