### ISSUE TITLE
'/usr/bin/ld: cannot find -lteec'

### ISSUE THREAD

**Issue by Dani2735** [OP-TEE/optee_os#781]
Hello, I'm trying to build the 'Hello world' example and I'm getting this error:

![issue](https://cloud.githubusercontent.com/assets/16964329/15137906/bff58968-168c-11e6-801f-83195167d1fd.png)

I tried to change the makefile, move the lib path and many many more but nothing worked. 

I've checked all the Issues board (and jenswi-linaro too) but nothing worked for me :(

Can anyone help me please?

Thanks in advance.

**Comment by vchong** [comment]
Resolved in https://github.com/jenswi-linaro/lcu14_optee_hello_world/issues/17
