### ISSUE TITLE
ARM GICv3 support

### ISSUE THREAD

**Issue by zhizhouzh** [OP-TEE/optee_os#782]
Hi experts,

Do you have any plan to support arm gicv3?

**Comment by jbech-linaro** [comment]
Hi,

Sooner or letter I'd guess we will need to support it, but as of now we have nothing planned for gicv3 this year. But I know that some Linaro members have started to ask for it, so it might be that it gets higher priority sooner than later.

Anyhow, if you have done some work or want to do some work in this area, you are more than welcome to contribute.

**Comment by zhizhouzh** [comment]
I see, thanks for the information.

**Comment by jbech-optee-adm** [comment]
Question has been answered, but if you have more questions, please re-open the issue.
