### ISSUE TITLE
data transfer using SharedMemory between TA and host

### ISSUE THREAD

**Issue by SyedElec** [OP-TEE/optee_os#788]
Hi,

I have a problem using SharedMemory. If I use the TEE_RegisterSharedMemory, data is transferred from HOST to TA but not from TA to HOST, it seems like a one way shared memory even if I use the INPUT and OUTPUT flags.

Also if I replace TEE_RegisterSharedMemory by TEE_AllocateSharedMemory, the data transferred from HOST to TA is not correct but the other way (TA -> HOST) it's working great.

Looking at the code in optee_client : [TEE_RegisterSharedMemory and TEE_AllocateSharedMemory](https://github.com/OP-TEE/optee_client/blob/fcd1014947e784ca8d618035bcb999f9151096b0/libteec/src/tee_client_api.c#L600-L653) I don't understand difference between buffer and shadow_buffer, more generally what's the difference between TEE_RegisterSharedMemory and TEE_AllocateSharedMemory and when to use them ?

I think this issue is related to issues [#755](https://github.com/OP-TEE/optee_os/issues/755) and [#754](https://github.com/OP-TEE/optee_os/issues/754)

You can find an hard-coded code below just to reproduce the issue, I'm using optee_os 2.0.0, optee_client master and QEMU. I didn't have this issue in optee_os 1.0.0 (didn't try for 1.1.0).

Thank you very much for help.

HOST CODE :
```c
const char *src = "HOST";
char *dst;

TEEC_SharedMemory shm = {0};

shm.flags = TEEC_MEM_INPUT | TEEC_MEM_OUTPUT;
shm.size = 4;
shm.buffer = calloc(4, sizeof(char));

dst = calloc(4, sizeof(char));

op.params[0].memref.parent = &shm;

memcpy(shm.buffer, src, 4);

printf("[HOST] SENDING TO TA %s\n", (char *)shm.buffer);

if (TEEC_RegisterSharedMemory(&ctx, &shm) != TEEC_SUCCESS) {
	free(shm.buffer);
}
//if (TEEC_AllocateSharedMemory(&ctx, &shm) != TEEC_SUCCESS) {
//	free(shm.buffer);
//}

TEEC_InvokeCommand(&sess, TEST_SHM, &op, &err_origin);

printf("[HOST] RECEIVED IN HOST %s : SHOULD BE TATA\n", (char *)shm.buffer);

memcpy(dst, shm.buffer, 4);

TEEC_ReleaseSharedMemory(&shm);
free(shm.buffer);
free(dst);
```

TA CODE :

```c
char *src;
const char *tmp = "TATA";
void *dst;

MSG_RAW("[TA] GOT IN TA BUFFER : %s", (char *)params[0].memref.buffer);

src = params[0].memref.buffer;

dst = TEE_Malloc(4, TEE_MALLOC_FILL_ZERO);

TEE_MemMove(dst, tmp, 4);

TEE_MemMove(params[0].memref.buffer, dst, 4);

MSG_RAW("[TA] SENDING TO HOST : %s", (char *)params[0].memref.buffer);

```

**Comment by pascal-brand-st-dev** [comment]
In the host code, `op.paramTypes` is not set.

**Comment by SyedElec** [comment]
Here is the ```op.paramTypes``` I use  :
```c
TEEC_Operation op = {0};
op.paramTypes = TEEC_PARAM_TYPES(TEEC_MEMREF_WHOLE,
					 TEEC_NONE,
					 TEEC_NONE,
					 TEEC_NONE);
```

**Comment by SyedElec** [comment]
@pascal-brand-st-dev 
problem fixed, it was from a condition in optee-client, where shadow_buffer were not copied into buffer :
https://github.com/OP-TEE/optee_client/blob/master/libteec/src/tee_client_api.c#L343-L345

in the host code, I have to set manually the size of the shared memory reference by adding the line
```c
op.params[0].memref.size = shm.size;
```

I suppose in the previous version, it was automatically done by :

```c
op.params[0].memref.parent = &shm;
```

Thank you,
I close the issue.

**Comment by zacchaeusliang** [comment]
for the ta what do you define the param types to be?
