### ISSUE TITLE
stdio.h conflict  

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#789]
I am creating my own client application on the normal world side. However because I need to access certain header files from the optee_os/out, I added it to the include paths.

However now I can't use fprintf() because it automatically goes to the stdio.h in optee_os/out.

However I see that in xtest, the make process must somehow have solved this? Otherwise, would I have to copy out only the header files I need and make a separate directory?

**Comment by jenswi-linaro** [comment]
For xtest we have a separate include directory, `host_include`, perhaps that's good enough for your purposes too?

**Comment by peterfeifanchen** [comment]
I can't seem to find that directory in optee_test. Is it somewhere else?

**Comment by peterfeifanchen** [comment]
oh I see its under optee_os, it looks like its fine. I'll give it a try. THanks.

**Comment by peterfeifanchen** [comment]
ok yup!
