### ISSUE TITLE
el0_fiq_a64 handler save context & jump to elx_irq 

### ISSUE THREAD

**Issue by colincheng10** [OP-TEE/optee_os#792]
Hi, 

I found a wierd code in el0_fiq_a64, 
the el0 fiq handler save context & jump to elx_irq !
could you please kindly check if this is wrong 
(https://github.com/OP-TEE/optee_os/commits/master/core/arch/arm/kernel/thread_a64.S)

	.align	7
el0_fiq_a64:
	store_xregs sp, THREAD_CORE_LOCAL_X0, 0, 3
	b	elx_irq                 
	check_vector_size el0_fiq_a64

this change was submited @ 
https://github.com/OP-TEE/optee_os/commit/bee0235940cbfac837013b0857d532dc2d8e5b87

**Comment by jenswi-linaro** [comment]
Hi,

I agree that it looks a bit strange, probably an error but I'd like to test it and analyze it before changing anything.

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/optee_os/pull/796 should take care of this, please review.

**Comment by pascal-brand-st-dev** [comment]
`Reviewed-by: Pascal Brand <pascal.brand@linaro.org>`

**Comment by jbech-optee-adm** [comment]
We're closing this issue since a fix has been provided. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
