### ISSUE TITLE
Can't find normal world application.

### ISSUE THREAD

**Issue by renzoz** [OP-TEE/optee_os#799]
Hello, I have been trying to recreate a trusted application based on the Hello World example, but I can't  find the executable for the normal world inside Qemu. 
Everything has been builld correctly and the trusted application was placed on /lib/teetz. Any clues that migh help?.
Thanks

**Comment by pascal-brand-st-dev** [comment]
Could you have a look at the final answer of https://github.com/jenswi-linaro/lcu14_optee_hello_world/issues/18  (search for `diff --git a/qemu.mk b/qemu.mk`)? It may help.

**Comment by renzoz** [comment]
Indeed that helps!. After including it on the make file it worked.
Thanks a lot.
