### ISSUE TITLE
Translating normal_world virtual address to physical address from secure world on ARM_v8

### ISSUE THREAD

**Issue by bngabonziza** [OP-TEE/optee_os#803]
Hi,

​I am doing some experiments to use secure world to inspect the normal world. I have successfully mapped the normal world memory in the secure world. I can also access exported Linux kernel symbols by consulting system.map and translate the virtual address to physical due to linear mapping. However, the challenge I am facing now is how to translate the virtual address of kernel heap objects to physical address, so my secure world code can access it.

​I have tried to play with the AT instruction and manually set TTBR and SCR.NR before calling AT. However, it seems it is not working for me. I am not even sure if it is possible to do this with the AT instruction​. Any help would be greatly appreciated.

Thank you very much!

**Comment by jenswi-linaro** [comment]
Hi,

On ARMv7 you can use `ATS12NSOPR` to do non-secure address translation while in secure mode.

On ARMv8 it's different, then there's no convenient way of doing the non-secure address translation. You'll need to traverse the translation tables in software.

Regards,
Jens

**Comment by bngabonziza** [comment]
Thank you!

**Comment by bngabonziza** [comment]
Hi,

I was able to do the translation by traversing translation tables on hikey , **but on fvp** when I translated this virtual address **(0xffffffc87b488330)** by traversing normal world translation tables, I got the following physical address **(0x8fb488330)** which is more than a 32bit address. 

I wondered if there is a way of mapping the obtained physical address into the range the ram provided in the platform-config file: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-vexpress/platform_config.h#L118
Thanks,

**Comment by jenswi-linaro** [comment]
It should be possible to map that memory with either a static register_phys_mem() or a dynamic core_mmu_add_mapping(). For the > 4GB physical addresses you need to run in Aarch64.

**Comment by bngabonziza** [comment]
Thanks a lot!

**Comment by targetnull** [comment]
@bngabonziza Hi, I'm wondering how you managed to "mapped the normal world memory in the secure world", did you translate it into physical address manually and pass it as a parameter to the secure world and then translate in a reverse way? 

I once tried to get the base address of normal world translation tables directly from secure world, but I found that the two worlds are using completely different translation tables. The address of  normal world translation tables is saved in cpu core data structure and can only be accessed in the EL3 monitor mode, therefore I wouldn't be able to know its address and it bothers me for quite some time.

Would you please share your method? I'd be very grateful.

**Comment by zzm7000** [comment]
@targetnull 

Hi, all the physical memory addresses are configured at platform_config.h. To map the normal world memory, there is no need to pass it from the normal world. We simply added another entry to `struct map_area bootcfg_memory_map[]` in core/arch/arm/kernel/generic_core_bootcfg.c. But, it seems this file has been replaced in the latest commits. So you need to figure out where to change.

If you want to access any specific memory in ARMv8, you can 1) find the physical address of the normal world translation tables. It is usually linear mapped, so not hard to find. 2) traverse the translation tables in software.

**Comment by targetnull** [comment]
@zzm7000 Hi, thanks a lot. But there is still one thing that I don't understand, you say that you added another entry to `bootcfg_memory_map[] `, wouldn't the entry you add overlap with the existing entries?

According to the [Hikey memory map](https://github.com/OP-TEE/optee_os/blob/6d7ecad5042b4dadb8bd48e2e6131c9b61fdb5d0/core/arch/arm/plat-hikey/platform_config.h#.L55), it seems that the physical address has been divided into adjacent parts and each is already in use.

**Comment by zzm7000** [comment]
No, it would not.

In the version (7315b7b47303ec73b8f5a994c37bb6bed0d00e37) we worked on, the structure looks like this

```
static struct map_area bootcfg_memory_map[] = {
	/* TEE core execution RAM. */
	{
	 .type = MEM_AREA_TEE_RAM,
	 .pa = CFG_TEE_RAM_START, .size = CFG_TEE_RAM_PH_SIZE,
#ifdef CFG_WITH_PAGER
	 .region_size = SMALL_PAGE_SIZE,
#endif
	 .cached = true, .secure = true, .rw = true, .exec = true,
	 },

	/* TEE core TA load/exec RAM: secure, user exec only. */
	{
	 .type = MEM_AREA_TA_RAM,
	 .pa = CFG_TA_RAM_START, .size = CFG_TA_RAM_SIZE,
	 .cached = true, .secure = true, .rw = true, .exec = false,
	 },

	/* TEE core public RAM: non-secure, non-exec. */
	{
	 .type = MEM_AREA_NSEC_SHM,
	 .pa = CFG_SHMEM_START, .size = CFG_SHMEM_SIZE,
	 .cached = true, .secure = false, .rw = true, .exec = false,
	 },
```

You see, it does not have the normal world memory there, because OPTEE has no intention to map and access that. 

What actually controls which memory range belongs to secure or normal is configured way before this. 
We had another thread to discuss this at [https://github.com/OP-TEE/optee_os/issues/697](https://github.com/OP-TEE/optee_os/issues/697)

**Comment by targetnull** [comment]
Thanks a lot, if my understanding is correct, you add one entry covering the whole non-secure physical memory so that OP-TEE is able to map the physical memory directly.

**Comment by zzm7000** [comment]
Exactly, what we add is like this

```
/* TEE core normal memory: non-secure, non-exec. */
	{
	 .type = MEM_AREA_NSEC_SHM,
	 .pa = DRAM0_BASE, .size = DRAM0_SIZE,
	 .cached = true, .secure = false, .rw = true, .exec = false,
	 },
```

**Comment by targetnull** [comment]
Many thanks, it's very detailed.
