### ISSUE TITLE
TA panics when setting a pointer

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#805]
I am trying to use symmetric operations to decrypt some text with my TA. The first thing my TA does is to find the right key to use, which it finds by decrypting something in a header. Data is passed in through registered shared memory. 

I am getting this weird error where I can go:

`struct TrustedCap *header;
header = params[1].memref.buffer;`

and it works fine. But if I later add:

`uint8_t* p;
p = (uint8_t*) params[1].memref.buffer;
UNUSED(p)`

It would cause a kernel panic in the TEE and return TEEC_ERROR_TARGET_DEAD on the normal world side while in the trusted world it shows:

> ERR USER-TA: TEE_CipherDoFinal:1098: Panic 0x0
> ERR [0x0] TEE-CORE: tee_svc_sys_return_helper:228: TA panicked with code 0x0 usr sp 0x101698 usr lr 0x205ff9
> ERR [0x0] TEE-CORE: user_ta_enter:468: tee_user_ta_enter: TA panicked with code 0x0

I am not sure how adding another pointer to point to some shared memory can cause a panic? This is literally the only changes. If I remove the line where I set p, it works fine.

**Comment by peterfeifanchen** [comment]
It seems the problem was if I had called TEE_CipherDoFinal() on a portion of the src buffer (in my case the shared memory buffer in TEE_Params), then somehow any later access to the rest of the buffer causes a panic.

Is there a reason why this is? Was this by design?

Right now I am memcpying out the portion I want to decrypt so I still can reference the original shared memory.

**Comment by peterfeifanchen** [comment]
I think I might have figured out the issue. You need to set the *destLen in TEE_CipherDoFinal(). The TEE Internal API made it sound like this is the len that comes out after the operation so I understood it as being set by the function.

**Comment by jforissier** [comment]
When not NULL, `destLen` is an in/out parameter. It indicates the size of the allocated buffer on input, and is updated by the function on success. See the GlobalPlatform TEE Internal Core API Specification v1.1 sections 3.4.4 and 3.4.5.

**Comment by peterfeifanchen** [comment]
Ahh I missed that. Thanks.
