### ISSUE TITLE
use of first 32K  nsec pub ddr .    nsec_tee_size 

### ISSUE THREAD

**Issue by sandeepbrcm** [OP-TEE/optee_os#806]
Hi,
     I am not seeing how the first 32k of pub_ddr is being used. 

     teecore_init_pub_ram()
    /*
         * 32kByte first bytes are allocated from teecore.
         * Remaining is under control of the NSec allocator. */

        void teecore_init_pub_ram(void)
        tee_mm_init(&tee_mm_pub_ddr, s, s + nsec_tee_size, SMALL_PAGE_SHIFT,
                    TEE_MM_POOL_NO_FLAGS);
        s += nsec_tee_size;

**Comment by jenswi-linaro** [comment]
This seems to be legacy stuff that could be removed.

**Comment by jbech-linaro** [comment]
@sandeepbrcm is this something that you could provide a patch for?

**Comment by jbech-linaro** [comment]
@sandeepbrcm ping?

**Comment by sandeepbrcm** [comment]
@jbech-linaro   Is that as simple as sending the patch  to  optee@linaro.org  ?  
Other wise could you please push it when I familiarize with it. 

The tested patch is to remove the code:
 
diff --git a/core/arch/arm/mm/tee_mmu.c b/core/arch/arm/mm/tee_mmu.c
index 6055731..a4dfc3c 100644
--- a/core/arch/arm/mm/tee_mmu.c
+++ b/core/arch/arm/mm/tee_mmu.c
@@ -714,7 +714,6 @@ void teecore_init_pub_ram(void)
 {
 	vaddr_t s;
 	vaddr_t e;
-	unsigned int nsec_tee_size = 32 * 1024;
 
 	/* get virtual addr/size of NSec shared mem allcated from teecore */
 	core_mmu_get_mem_by_type(MEM_AREA_NSEC_SHM, &s, &e);
@@ -725,18 +724,6 @@ void teecore_init_pub_ram(void)
 	/* extra check: we could rely on  core_mmu_get_mem_by_type() */
 	TEE_ASSERT(tee_vbuf_is_non_sec(s, e - s) == true);
 
-	/*
-	 * 32kByte first bytes are allocated from teecore.
-	 * Remaining is under control of the NSec allocator.
-	 */
-	TEE_ASSERT((e - s) > nsec_tee_size);
-
-	TEE_ASSERT(tee_mm_is_empty(&tee_mm_pub_ddr));
-	tee_mm_final(&tee_mm_pub_ddr);
-	tee_mm_init(&tee_mm_pub_ddr, s, s + nsec_tee_size, SMALL_PAGE_SHIFT,
-		    TEE_MM_POOL_NO_FLAGS);
-	s += nsec_tee_size;
-

**Comment by jbech-linaro** [comment]
Hi @sandeepbrcm ,

We can do a patch for it. I wasn't sure whether you were onto it or not. For future patches etc, you are supposed to create a pull request (fork optee_os, create a branch, fix and then send a pull request). The details how to do that could be found here: https://github.com/OP-TEE/optee_os/blob/master/documentation/github.md#contributing

Thanks for reaching out so promptly.

**Comment by pascal-brand-st** [comment]
Question has been answered, but If the issue persists or you have more questions, please re-open the issue.
