### ISSUE TITLE
UUID Security Error

### ISSUE THREAD

**Issue by renzoz** [OP-TEE/optee_os#809]
Hi, I'm working on a new TA with a new UUID and I have being getting an error when loading the TA.
The weird thing is that some work and other don't. For example ce96fdc0-1ce1-11e6-a74d0002a5d5c51b works just fine, but if I change it for 1e11672a-2181-11e6-b67b9e71128cae77 I get this:

Normal world
`
misc opteearmtz00: tee_session_create_and_open: ERROR ret=0 (err=0xffff000f, org=3,  sessid=0x00100000)
ERR [602] TEEC:TEEC_OpenSession:298: open session to TA UUID 1e11672a 2181 11e6 failed
`

Secure world

`
DBG TEE-CORE:tee_ta_init_static_ta_session:1041:    Lookup for Static TA 1e11672a-2181-11e6
DBG TEE-CORE:tee_ta_init_session_with_signed_ta:1084:    Load dynamic TA
DBG TEE-CORE:tee_ta_open_session:1171: init session failed 0xffff000f
DBG TEE-CORE:tee_dispatch_open_session:128:   => Error: ffff000f of 3
`

Considering the code hasn't been change, other than UUID, I find myself clueless. Any ideas?
Thanks

**Comment by pascal-brand-st-dev** [comment]
Have you changed the uuid in the .h file of the TA, as well as in the Makefile of the TA?

**Comment by renzoz** [comment]
Yes, all the UUID is handled by a script which:
-Generates the propper TA binary.
-Exports the clients binary.
-Exports the .TA
So by changing what UUID the scripts uses, it should do the same for both.

**Comment by renzoz** [comment]
I tested a new client where it only initialize the context and it worked. After that I included the code for creating a session and it failed.
Here is the code I used for creating a session:

`res = TEEC_OpenSession(&context02, &session01, &trustedCoreFramework,
			       TEEC_LOGIN_PUBLIC, NULL, NULL, NULL);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_Opensession failed with code 0x%x", res);`

**Comment by pascal-brand-st-dev** [comment]
It would be good if the error comes from the file https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/user_ta.c, and more specifically https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/user_ta.c#L371

**Comment by jbech-linaro** [comment]
@renzoz maybe a stupid question, but quick to check. Have you double checked that you indeed have managed to put the "new" TA on the filesystem? I.e are you sure that a TA with the name
`ce96fdc0-1ce1-11e6-a74d0002a5d5c51b.ta` exists just as well as a TA with the name
`1e11672a-2181-11e6-b67b9e71128cae77.ta` at `/lib/optee_armtz/`?

It's very easy to forget updating root-fs related section in the build/Makefile and/or forget to rebuild it. I've been doing that mistake more than once.

**Comment by renzoz** [comment]
Yes I do; In fact, in order to reduce modifying the makefile (qemu.mk for rootfs), I just copy the resulting TA into `optee_test/out/ta` where it should be automatically found by:
`find $(OPTEE_TEST_OUT_PATH) -name "*.ta"`

**Comment by jbech-linaro** [comment]
`modprobe optee_armtz` and the other prints implies that you're still using the [legacy TEE driver](https://github.com/OP-TEE/optee_linuxdriver#op-tee-linux-driver---deprecated) and eventually also OP-TEE < 2.0.0.

Please ensure that you either are using tags on older stable pre 2.0.0 release. Or the best would be to just update all gits to latest so that you start using 2.0.0.

If you still, after updating, cannot get it to work and since this is an unknown error for us (can't reproduce it), I'd suggest that you setup [OP-TEE + QEMU](https://github.com/OP-TEE/optee_os#5-repo-manifests) and then simply debug it using gdb. How that is done is described [here](https://github.com/OP-TEE/optee_os/blob/master/documentation/debug.md) (and it's not hard to get it working). The error code `0xffff000f` is `TEE_ERROR_SECURITY` and that doesn't happen in that many places. So with that knowledge and GDB the issue is probably easy to find.

**Comment by renzoz** [comment]
Thank you very much, I hadn't really paid much attention to versions since I was given the enviroment all build up.
In any case, I will try and build it from scratch when I have some free time and give it a try.

**Comment by renzoz** [comment]
Just an update: I think I found the issue, after building everything up from scratch and creating a new TA I noticed that on user_ta_header_defines.h there is a define of TA_UUID. Not sure where this define is used, but I managed to get the TA to work with another UUID when I set it with the new UUID definition.
Thanks

**Comment by jenswi-linaro** [comment]
Are you testing with something recent, like 2.1.0?

**Comment by renzoz** [comment]
I belive so, I'm currently testing it on a HiKey board with the debian (hikey_debian.xml) and after a re-sync it showed I had Optee_os:ac3cc1102a081a7fe2b0446d38c6a484c2e9b26f.
