### ISSUE TITLE
OP-TEE and ARM-TF

### ISSUE THREAD

**Issue by helen-fornazier** [OP-TEE/optee_os#811]
If I understand correct, I can use OP-TEE with ARM Trusted Firmware right? So I can have a secure boot.
It seems that both projects provide a secure monitor, which one should I use? Are there any difference between them?
Is there any documentation regarding how to use OP-TEE with ARM-TF?
I also notice that optee_os generates a bootable image, thus is ARM-TF required? Or it's only required for secure boot?

Thank you

**Comment by jenswi-linaro** [comment]
Yes, OP-TEE can be used with ARM-TF. There's an OP-TEE Dispatcher in ARM-TF which is the analogue of a secure monitor in ARMv7-A (OP-TEE uses its internal secure monitor on ARMv7-A). Each trusted OS typically has their own Dispatcher to handle the details in communication.

Please check https://github.com/ARM-software/arm-trusted-firmware/blob/master/readme.md for ARM-TF documentation.

On ARMv8-A ARM-TF is a requirement. OP-TEE doesn't execute at EL3.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
