### ISSUE TITLE
128 bit AES CTR cipher only decrypts first 16 bytes correctly

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#812]
Hi, I am using TEE_CipherUpdate() and TEE_CipherDoFinal(). I created an outbuf that is large enough to do the decryption operation in a single go. So I just called TEE_CipherDoFinal(). My IV is 0. 

For some strange reason, I can decrypt the first 16 bytes fine. But the rest becomes jibberish. I am using a 256 outbuf and inbuf that is some AES-128 encrypted ciphertext of 153 bytes. 

Is there something I am missing that is causing the decryption to only work on the first 128 bit block and not the rest? I looked at xtest 4003 but I don't see that I am doing anything different.

**Comment by peterfeifanchen** [comment]
I can manually decrypt it I use libtomcrypt directly on my localhost computer. 

I double checked my IV, max_key_len, they are all correct (0x00 and 128). My key type is TEE_TYPE_AES and I passed in the key to a transient object using a single TEE_ATTR_SECRET_VALUE attr. 

I allocated an operation with TEE_ALG_AES_CTR and TEE_MODE_DECRYPT. I called TEE_SetOperationKey with the previously created transient object that has the AES key. Then I called TEE_CipherInit with IV 0x00 and IV size of 16. 

I checked the src and srcLen when I call TEE_CipherUpdate or TEE_CipherDoFinal. The input matches what the ciphertext should be. 

I feel for some reason the CTR value is not being updated after every block....? But I don't control that through the internal API.

**Comment by pascal-brand-st-dev** [comment]
I could not answer from this.
You can have a look at the test 4003 https://github.com/OP-TEE/optee_test/blob/master/host/xtest/xtest_4000.c#L2304 that tests CTR configuration https://github.com/OP-TEE/optee_test/blob/master/host/xtest/xtest_4000.c#L2228

**Comment by peterfeifanchen** [comment]
Lol...I lucked out. The problem in the end was endianness in ctr_start. OPTEE-OS sets it to big-endian while I encrypted my text in little-endian. I guess this would only correctly decode the first block if my IV was 0x00.
