### ISSUE TITLE
errors when use Debian on Hikey

### ISSUE THREAD

**Issue by fanguannan0706** [OP-TEE/optee_os#824]
Hi,
I used Debian on Hikey as guide and meet some errors when use some commands like reboot, halt, ifconfig. It's strange because errors would not always appear. 
THe error message is like : Failed to start halt.target: Connection timed out
I'm not sure it's the problem of hardware, or system. Hope for help.

**Comment by fanguannan0706** [comment]
The other question is, I find the tests related to storage will fail if I use rpmb fs, such as xtest 2000.

**Comment by jforissier** [comment]
`xtest` tests in the 20k range (not 2k) do not apply to RPMB FS ; they assume the normal world (REE) files with encryption. So, please make sure you re-build `xtest` when you change the optee_os compile-time flags.

**Comment by fanguannan0706** [comment]
I find it can't save persistent object using rpmb as storage. when I reboot the board, it can't find the file I have saved last time.
Here is a error message:ERR [888] TEES:compute_hmac:329: Cannot compute MAC (key not set)

**Comment by jforissier** [comment]
By default, `tee-suplicant` emulates the RPMB device in memory. This was done to make testing easier and avoid inadvertently accessing the RPMB. If you want to access a real device (such as `/dev/mmcblk0rpmb`), you need to comment out `RPMB_EMU := 1` in `optee_client/tee-supplicnat/Makefile` or pass `RPMB_EMU=0` on the build command line.

**Comment by fanguannan0706** [comment]
I comment out `RPMB_EMU :=1` and do `make optee_client` , then re-flash the board, but it seems have no effect. Should I do `make all`? By the way, I can't find a device named `mmcblk0rpmb` or something else in '/dev'.

**Comment by jforissier** [comment]
@fanguannan0706 I think you need to clean optee_client and rebuild, otherwise it won't notice that `RPMB_EMU` has changed.
As for the missing `/dev/mmcblk0rpmb`: your kernel is probably missing this patch: http://thread.gmane.org/gmane.linux.kernel/2232277.
Please note that if you run `xtest` with RPMB, it will first attempt to program a key into your RPMB partition. You may want to set `CFG_RPMB_TESTKEY=y` when compiling optee_os, so that you know which key is programmed ;)

**Comment by jbech-linaro** [comment]
@fanguannan0706 for the non-RPMB related question and issues. I'd recommend that you ask the questions at the [HiKey 96Boards forum](http://www.96boards.org/forums/forum/products/hikey/) instead, since that seems to be general HiKey/Debian issues not related to OP-TEE.

**Comment by fanguannan0706** [comment]
The questions are solved, If I have others about RPMB I would ask at forum then. Thank you for answer.
