### ISSUE TITLE
Trusted Android Apps using OP-TEE

### ISSUE THREAD

**Issue by jsherman3** [OP-TEE/optee_os#825]
Hi, I'm currently a graduate research assistant and I've been trying to use Android with TrustZone extensions for some time now.  I recently stumbled upon OP-TEE and the link: https://github.com/jforissier/hikey_optee/tree/aosp which demonstrates how to run Android + OP-TEE on the Hikey Board.  I was wondering if there was any instructions or an example application that uses Android with OP-TEE?

**Comment by jbech-linaro** [comment]
@jsherman3 Hi, I'm not aware of any example application (atleast not from us working with OP-TEE on daily basis). It should however not be that complicated. I'm not a JAVA/Android application developer. But with the JNI/KNI(?) interface just can call regular C functions from an app I guess. So, with permissions etc correct you should be able to invoke the commands in libteec.so in [optee_client.git](https://github.com/OP-TEE/optee_client) that talks to the Trusted Application.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
