### ISSUE TITLE
Persistent RSA keys not working for decryption

### ISSUE THREAD

**Issue by SyedElec** [OP-TEE/optee_os#827]
Hi,

I found that creating a persistent rsa key from transient rsa key generates a different handleFlags, I don't know if it's the source of the problem but I have only the decryption that is not working using the persistent rsa key. 

The problem might be from the way that transient keys are converted to persistent keys.

Here is a sample code :

```c
TEE_ObjectHandle rsa_keypair = NULL, persisten_rsa_keypair = NULL;
TEE_ObjectInfo rsa_key_info, persisten_rsa_key_info;

char object_id[] = "0000";

uint32_t flags = TEE_DATA_FLAG_ACCESS_WRITE | TEE_DATA_FLAG_ACCESS_READ;

TEE_AllocateTransientObject(TEE_TYPE_RSA_KEYPAIR, 512, &rsa_keypair);
TEE_GenerateKey(rsa_keypair, 512, NULL, 0);

TEE_GetObjectInfo(rsa_keypair, &rsa_key_info);

IMSG("objectSize : %zu", rsa_key_info.objectSize);            // 512
IMSG("maxObjectSize : %zu", rsa_key_info.maxObjectSize);      // 512

IMSG("objectType : 0x%08X", rsa_key_info.objectType);         // 0xA1000030
	
IMSG("keySize : %zu", rsa_key_info.keySize);                  // 512
IMSG("maxKeySize : %zu", rsa_key_info.maxKeySize);            // 512

IMSG("objectUsage : 0x%08X", rsa_key_info.objectUsage);       // 0xFFFFFFFF
IMSG("handleFlags : 0x%08X", rsa_key_info.handleFlags);       // 0x00020000

TEE_CreatePersistentObject(TEE_STORAGE_PRIVATE, object_id, sizeof(object_id), flags, 
						   rsa_keypair, NULL, 0, &persisten_rsa_keypair);

TEE_GetObjectInfo(persisten_rsa_keypair, &per_rsa_key_info);

IMSG("objectSize : %zu", per_rsa_key_info.objectSize);        // 512
IMSG("maxObjectSize : %zu", per_rsa_key_info.maxObjectSize);  // 512

IMSG("objectType : 0x%08X", per_rsa_key_info.objectType);     // 0xA1000030
	
IMSG("keySize : %zu", per_rsa_key_info.keySize);              // 512
IMSG("maxKeySize : %zu", per_rsa_key_info.maxKeySize);        // 512

IMSG("objectUsage : 0x%08X", per_rsa_key_info.objectUsage);   // 0xFFFFFFFF
IMSG("handleFlags : 0x%08X", per_rsa_key_info.handleFlags);   // 0x00030000 ??
```

The decryption operation fails using persistent rsa key with Panic 0xFFFF0007 which is TEE_ERROR_BAD_STATE. However, using the transient key, it works well.
```
ERROR:   TEE-CORE: ERROR:   USER-TA: Panic 0xffff0007
ERROR:   TEE-CORE: TA panicked with code 0xffff0007 usr_sp 0x100d20 usr_lr 0x109a95
```

The full code to reproduce the complete crypto problem is here : http://pastebin.com/wMRKimuA

I precise that using the same approach with AES persistent key works perfectly with encryption and decryption, even the handleFlags is always 0x00020000 (TEE_HANDLE_FLAG_INITIALIZED)

Thank you very much for your help.

**Comment by jenswi-linaro** [comment]
I'm looking into this.

**Comment by jenswi-linaro** [comment]
This is almost the same as https://github.com/OP-TEE/optee_os/issues/785, which is solved now on `master` branch.

Please test with latest to confirm that the problem persists.

**Comment by SyedElec** [comment]
@jenswi-linaro Thank you for looking into it.

Yes, I saw this issue and I'm using the latest master version of today. In the issue described, he is using AES algorithm to make encryption and decryption, and it works just fine for me too using persistent aes key or transient one.

The problem I experiment come from RSA algorithm (and rsa key). Attributes seem to be copied fine from transient rsa key to persistent rsa key except handleFlags which has a value (0x00030000) I can't find in GP documentation.

I just tried again with the [provided code](http://pastebin.com/wMRKimuA) and latest optee_os on QEMU, the decryption operation still fails.

**Comment by jenswi-linaro** [comment]
Thanks for retesting, I'll check.

**Comment by jenswi-linaro** [comment]
@SyedElec, does https://github.com/OP-TEE/optee_os/pull/833 fix the problem?

**Comment by SyedElec** [comment]
@jenswi-linaro, yes it fixed the problem, the RSA decryption is working fine, thank you very much.

I just wanted to ask what is the handleFlags 0x00030000 and what does it correspond to ? I still have it.

**Comment by jenswi-linaro** [comment]
The handle flags are from
```
#define TEE_HANDLE_FLAG_PERSISTENT         0x00010000
#define TEE_HANDLE_FLAG_INITIALIZED        0x00020000
```
You'll find it in the GP spec now that you have the defines to search for.

**Comment by SyedElec** [comment]
I looked there but I can't find the value ```0x00030000``` that I obtain by getting the persistent rsa key object infos :

```c
TEE_GetObjectInfo(persisten_rsa_keypair, &per_rsa_key_info);

[...]
IMSG("handleFlags : 0x%08X", per_rsa_key_info.handleFlags);   // 0x00030000 ??
```

**Comment by jenswi-linaro** [comment]
It's a bitfield, the two values are or-ed.

**Comment by SyedElec** [comment]
Ok thank you, I understand, I missed that.
