### ISSUE TITLE
extending file length in optee_os 

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#831]
I am reading the code for optee_os fs operations [here](https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_ree_fs.c). In ree_fs_truncate_internal(), it calls out_of_place_write() to extend a file with 00's. 

I can't seem to figure out how a new file block gets created here. It seems to me that out_of_place_write() will first try to grab the block and cache it, or at least read in the data from that block if there is no cache. In any case, it'll call read_block_from_storage(). But at this point, since we are extending, that file for that block doesn't exist. If read_block_from_storage() cannot find the file, won't the out_of_place_write() not proceed? 

I see that flush_block_to_storage() calls open() with O_CREATE. but if the read_block_from_storage() fails before that, the code to flush a 00's block would never execute. Shouldn't it be out_of_place_write() but if its extending, the read_block_from_storage() should be skipped?

**Comment by jforissier** [comment]
`read_block_from_storage()` returns success when the block doesn't exists. It just will not touch the block parameter. Not obvious, I agree ;)

**Comment by peterfeifanchen** [comment]
I see. Thanks.
