### ISSUE TITLE
ERR [985] TEES:main:380: failed to find an OP-TEE supplicant device 

### ISSUE THREAD

**Issue by symu1818** [OP-TEE/optee_os#835]
I got the following error when I execute the tee-suplicant in Hikey platform:

root@HiKey:/ tee-supplicant                                                     
ERR [985] TEES:main:380: failed to find an OP-TEE supplicant device             
root@HiKey:/ 

Could you please help me?

**Comment by jforissier** [comment]
Do you have the following entries in `/dev`? (I suppose not):
```
root@HiKey:/ ls /dev/tee*
/dev/tee0      /dev/teepriv0
```

If you don't it means your kernel is missing the OP-TEE driver. See here: https://github.com/linaro-swg/linux/tree/optee.

**Comment by symu1818** [comment]
Yes, I do.

root@HiKey:/ ls /dev/tee*                                                                  
/dev/tee0      /dev/teepriv0

**Comment by vchong** [comment]
Maybe you're trying to load the supplicant a 2nd time. On HiKey, tee-supplicant should be loaded automatically on bootup. You will see the error if you try to load it again. Run `ps | grep supplicant` to see if it's already loaded.

**Comment by symu1818** [comment]
OK. I should be this, then. It is already loaded:
```
root@HiKey:/ ps | grep supplicant                                                          
  883 root       0:00 tee-supplicant                                                       
  907 root       0:00 grep supplicant 
```
Thanks!
