### ISSUE TITLE
TUI font rendering is _very_ slow

### ISSUE THREAD

**Issue by d3zd3z** [OP-TEE/optee_os#838]
The text is rendered a pixel at a time, which will be thousands to millions of times slower than more specialized code. If we're going to stick with bitmap fonts, there are some good examples of the kind of bitblt we need in the X11 code (is this license compatible).

The current code is certainly functional, but coming up with better text rending will likely be important to make the UI usable.

**Comment by jbech-linaro** [comment]
TUI stuff was removed in #1844.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
