### ISSUE TITLE
QEMU Secure World DBG messages: How to turn them off?

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#839]
Hi, I am using the persistentObject API, for some reason, I am getting whole bunch of DBG msg from TEE-CORE. Just wondering where is the flag in the makefile that I can turn it off with? Thanks.

**Comment by jforissier** [comment]
Set `CFG_TEE_CORE_LOG_LEVEL` to 2 (info), 1 (error) or 0 (none).

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by peterfeifanchen** [comment]
I can't seem to find this in any of the mk or Makefiles in optee_os. Where should I set this?

**Comment by peterfeifanchen** [comment]
nevermind found it
