### ISSUE TITLE
Code still not Werror safe

### ISSUE THREAD

**Issue by koenkooi** [OP-TEE/optee_os#848]
|   CC      out/arm-plat-hikey/ta_arm64-lib/libutee/tui/image_png.o
|   CC      out/arm-plat-hikey/ta_arm64-lib/libutee/tui/font.o
| lib/libutee/tui/image_png.c: In function 'error_cb':
| lib/libutee/tui/image_png.c:42:59: error: unused parameter 'msg' [-Werror=unused-parameter]
|  static void error_cb(png_structp png_ptr, png_const_charp msg)
|                                                            ^
|   CC      out/arm-plat-hikey/ta_arm64-lib/libutee/arch/arm/user_ta_entry.o
| cc1: all warnings being treated as errors
| mk/compile.mk:146: recipe for target 'out/arm-plat-hikey/ta_arm64-lib/libutee/tui/image_png.o' failed

**Comment by vchong** [comment]
More of a workaround than solution but this Werror can also be disabled (hackishly) by adding NOWERROR=1 to EXTRA_OEMAKE in the recipe.

**Comment by jforissier** [comment]
Which compiler version please? The one I'm using [1] does not report any error, maybe it's time to upgrade.

[1] :
```
$ aarch64-linux-gnu-gcc --version
aarch64-linux-gnu-gcc (crosstool-NG linaro-1.13.1-4.9-2014.09 - Linaro GCC 4.9-2014.09) 4.9.2 20140904 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by koenkooi** [comment]
For RPB builds it's

```
aarch64-oe-linux-gcc (Linaro GCC 5.2-2015.11-2) 5.2.1 20151005
```

For regular linaro OE builds it will be linaro-5.3 or vanilla 6.0

**Comment by jbech-linaro** [comment]
@jforissier the reason we cannot see it in our daily builds is because we're building with 
`CFG_TEE_TA_LOG_LEVEL=3` by default and then the `msg` is indeed defined. We can also trigger this error if we're build with `CFG_TEE_TA_LOG_LEVEL=0`. What we should do is add builds in Travis which contains that configuration also for QEMU, HiKey etc (there are a few targets where this should be added). I can provide a patch for that.

**Comment by jforissier** [comment]
@jbech-linaro ah yes I did not notice the `EMSG`. +1 for a Travis build with `CFG_TEE_TA_LOG_LEVEL=0`. Well, actually I can add it to https://github.com/OP-TEE/optee_os/pull/849.

**Comment by jbech-linaro** [comment]
@jforissier , sure if you want too, pull/grab my patch that I just created for that, it's a single patch on this branch.
https://github.com/jbech-linaro/optee_os/commits/ta_log_level_0

**Comment by jforissier** [comment]
@jbech-linaro let's keep your patch, since it updates all the targets. Please make a PR.

**Comment by jbech-linaro** [comment]
@jforissier , OK, I'll create a PR.
