### ISSUE TITLE
Can't use HDMI when flash OP-TEE on Hikey platform

### ISSUE THREAD

**Issue by LeiShenHeros** [OP-TEE/optee_os#853]
Hi everyone,
I try to implement a touch panel driver in secure world and want it can be use after change the state of touch panel from normal world to secure world. But I find I can't use HDMI and any peripherals after flash OP-TEE on Hikey platform. I have been  change  Linux versions and  amend  the Makefile file,it also useless.I make a test use the optee_debian and HDMI can be use,so I guess there are some things I missed,anyone help?
Thank you so much for your time,
WeiMin

**Comment by radheshkrishnan** [comment]
Hey @LeiShenHeros, 

Interesting! Is it possible to share your implementation of touch panel driver in secure world?

Cheers,
Radhesh

**Comment by LeiShenHeros** [comment]
Hi @radheshkrishnan
now,I'm working on it,I'd like to share my implementation about this,but if Hikey platform can't use any peripherals,I can't test it.
WeiMin
