### ISSUE TITLE
Trying to build the Android TAs using the shell script

### ISSUE THREAD

**Issue by jsherman3** [OP-TEE/optee_os#855]
Hello,
I'm currently using the following link: https://github.com/linaro-swg/optee_android_manifest/tree/master
I have successfully completed the previous steps, however when I run the shell script ( ./optee/build_ta.sh hikey optee/android_optee_examples.cfg ) to build the trusted applications, I run into the following error:

make: Entering directory `/home/jsherman/Downloads/AOSP/external/optee_hello_world/ta'
Makefile:5: /optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk: No such file or directory
make: *** No rule to make target `/optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk'.  Stop.
make: Leaving directory `/home/jsherman/Downloads/AOSP/external/optee_hello_world/ta'
make: Entering directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/concurrent'
../ta_common.mk:3: /optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk: No such file or directory
make: *** No rule to make target `/optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk'.  Stop.
make: Leaving directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/concurrent'
make: Entering directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/concurrent_large'
../ta_common.mk:3: /optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk: No such file or directory
make: *** No rule to make target `/optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk'.  Stop.
make: Leaving directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/concurrent_large'
make: Entering directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/create_fail_test'
../ta_common.mk:3: /optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk: No such file or directory
make: *** No rule to make target `/optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk'.  Stop.
make: Leaving directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/create_fail_test'
make: Entering directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/crypt'
../ta_common.mk:3: /optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk: No such file or directory
make: *** No rule to make target `/optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk'.  Stop.
make: Leaving directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/crypt'
make: Entering directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/os_test'
../ta_common.mk:3: /optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk: No such file or directory
make: *** No rule to make target `/optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk'.  Stop.
make: Leaving directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/os_test'
make: Entering directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/rpc_test'
../ta_common.mk:3: /optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk: No such file or directory
make: *** No rule to make target `/optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk'.  Stop.
make: Leaving directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/rpc_test'
make: Entering directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/sims'
../ta_common.mk:3: /optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk: No such file or directory
make: *** No rule to make target `/optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk'.  Stop.
make: Leaving directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/sims'
make: Entering directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/storage'
../ta_common.mk:3: /optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk: No such file or directory
make: *** No rule to make target `/optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk'.  Stop.
make: Leaving directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/storage'
make: Entering directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/storage_benchmark'
../ta_common.mk:3: /optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk: No such file or directory
make: *** No rule to make target `/optee_os/out/arm-plat-hikey/export-ta_arm64/mk/ta_dev_kit.mk'.  Stop.
make: Leaving directory `/home/jsherman/Downloads/AOSP/external/optee_test/ta/storage_benchmark'
I was wondering if anyone knew what I was doing wrong? I followed the instructions precisely

**Comment by jbech-linaro** [comment]
Obviously you're missing the TA-dev-kit for some reason. The TA-dev-kit are created when building optee_os. Was [this](https://github.com/linaro-swg/optee_android_tools/blob/master/build_ta.sh#L70-L75) step built successfully?

**Comment by jsherman3** [comment]
I'm not sure if the op-tee was built successfully was I supposed to clone the optee repository and drag it into the AOSP folder? I just ran the shell script like the directions said

**Comment by jbech-linaro** [comment]
It should be included when running
https://github.com/linaro-swg/optee_android_manifest/tree/master#32-add-the-op-tee-overlay

Now it's been a couple of weeks since I tried this myself. For me it was working back then. But I can't say whether some new bug has sneaked in or if it's something wrong on your side. I'm afraid I don't have any time to look into this right now. But we will come back to it later. In the mean time if you find out why it fails, please let us know.

**Comment by jsherman3** [comment]
Yeah I added the overlay does it have anything to do with optee directory variable ?

**Comment by vchong** [comment]
The log shows the path to the TA-dev-kit is wrong. From the script it appears that CURRENT_BUILD_PATH is not defined properly, so optee_os and the devkit are probably not built. You should have seen an error for that first, did you not? Can you add `echo "CURRENT_BUILD_PATH = $CURRENT_BUILD_PATH"` before the make command in https://github.com/linaro-swg/optee_android_tools/blob/master/build_ta.sh#L70-L75 and see what the output is?

**Comment by vchong** [comment]
It's showing on the 96boards forum [1] that you managed to get the build completed. Can you explain the problem and solution here for reference please? Thanks!

[1] www.96boards.org/forums/topic/trying-to-flash-to-emmc-but-its-not-working

**Comment by jsherman3** [comment]
I didn't have the program realpath installed, so when I printed out $CURRENT_BUILD_PATH, it was blank.

**Comment by vchong** [comment]
Great! Thanks for sharing!
