### ISSUE TITLE
Formatting of UUIDs is incorrect

### ISSUE THREAD

**Issue by d3zd3z** [OP-TEE/optee_os#857]
Although GlobalPlatform specifies that TAs and such are identified with UUIDs, we don't format them quite right when turning them into strings. Per https://www.ietf.org/rfc/rfc4122.txt, there should be another hyphen after the first two bytes of `clockSeqAndNode`.

Unfortunately, fixing this would break compatibility between how TAs are built, and when the OS loads them. Perhaps we should fix it at a significant release.

**Comment by jforissier** [comment]
Very true... +1 for fixing this when convenient.

**Comment by d3zd3z** [comment]
This is also related to the endianness issue in [#858](https://github.com/OP-TEE/optee_os/issues/858).
