### ISSUE TITLE
Is fp enabled in kernel?

### ISSUE THREAD

**Issue by Yanjiong** [OP-TEE/optee_os#862]
Hi Experts:

Is fp enabled in kernel when doing fs encrypt? It seems speed is very slow now.

Thanks.

BR.
Wang Yanjiong

**Comment by jenswi-linaro** [comment]
It's platform specific, for ARMv8 platforms the crypto extensions are usually used.

The bottleneck in fs encrypt is likely not in the crypto operation, instead it's in the way data is written to flash.

**Comment by Yanjiong** [comment]
From my test, if fs encrpt disabled, the 4/5 time cast could be saved, increase BLOCK_SIZE written to flash the speed could also higher.

It seems fs encrypt is the bottleneck.

**Comment by jenswi-linaro** [comment]
If you say so, I haven't benchmarked it myself.

By the way, what's the problem with the speed. Does it cause a problem in a use case?

**Comment by Yanjiong** [comment]
No, just found that the speed is too low compare to ree fs, and want to clarify the root cause of that.

Since fp enabled in ta and performance is good, but the fs encrypt takes big part of the time, so I wander if fp is not enalbled well in kernel.

**Comment by jbech-linaro** [comment]
@Yanjiong , we are doing work related to secure storage and we hope that it should increase performance. We're also looking into doing better benchmarks. Having that said, is it OK if I close this issue, if there are no more questions or any other discussion ongoing?

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
