### ISSUE TITLE
"double free or corruption" error when building optee_os

### ISSUE THREAD

**Issue by vchong** [OP-TEE/optee_os#863]
Please note above error when building optee_os on i386 Ubuntu systems only due to an issue with the wand package [1].

[1] https://bugs.launchpad.net/ubuntu/+source/wand/+bug/1460358

**Comment by vchong** [comment]
Posting for FYI and notification purposes only. Closing.

**Comment by jbech-linaro** [comment]
@pascal-brand-st-dev this is something that could be worth mention in the "known bugs" section for the coming release.
