### ISSUE TITLE
Print Error have to help Issue

### ISSUE THREAD

**Issue by acy54321** [OP-TEE/optee_os#864]
Hi OPTEE Experts

In my own tests found a strange phenomenon. I use uint64_t data type but in different location in time will be different results.

I add code like following :
--- a/core/arch/arm/kernel/generic_boot.c
+++ b/core/arch/arm/kernel/generic_boot.c
@@ -315,6 +315,8 @@ static void init_runtime(uint32_t pageable_part __unused)
 
 static void init_primary_helper(uint32_t pageable_part, uint32_t nsec_entry)
 {
+       uint64_t a = 0x12345678666666;
+       EMSG("%llx\n",a);
        /*

--- a/core/tee/tee_svc.c
+++ b/core/tee/tee_svc.c
@@ -1094,6 +1094,9 @@ TEE_Result syscall_wait(unsigned long timeout)
        struct tee_ta_session *s;
        TEE_Time base_time;
        TEE_Time current_time;
+       uint64_t a = 0x123456786666;
+       uint64_t b = 0x9999999986666;
+       EMSG("Ian %llx %llx\n",a,b);
 
        res = tee_ta_get_current_session(&s);
        if (res != TEE_SUCCESS)
@@ -1128,6 +1131,10 @@ TEE_Result syscall_get_time(unsigned long cat, TEE_Time *
        struct tee_ta_session *s = NULL;
        TEE_Time t;
 
+       uint64_t a = 0x123456786666;
+       uint64_t b = 0x9999999986666;
+       EMSG("Ian %llx %llx\n",a,b);
+

But Execution results are as follows

listening on port 54321
soc_term: accepted fd 4
soc_term: read fd EOF
soc_term: accepted fd 4
ERR [0x0] TEE-CORE:init_primary_helper:319: 12345678666666

INF [0x0] TEE-CORE:init_primary_helper:331: Initializing (2.0.0-dev #4 日  6月 19 13:58:27 UTC 2016 arm)
.
.
.
.
ORE:init_session_with_signed_ta:566:       dyn TA : 5b9e0e40-2636-11e1-ad9e0002a5d5c51b
DBG [0x0] TEE-CORE:tee_ta_close_session:317: tee_ta_close_session(0x7df678e8)
DBG [0x0] TEE-CORE:tee_ta_close_session:336:    ... Destroy session
DBG [0x0] TEE-CORE:tee_ta_close_session:355:    ... Destroy TA ctx
ERR [0x0] TEE-CORE:syscall_get_time:1136: Ian 5678666680000093 9998666600001234

[ta log] system time 19.515

ERR [0x0] TEE-CORE:syscall_get_time:1136: Ian 5678666680000093 999866660000123

In booting flow correct print out a var =  0x12345678666666 but in svc code is not correct var(shift).

I thought about several possible points : 
     1. lib/libutee/arch/arm/utee_syscalls_a32.S marco UTEE_SYSCALL only save r5~r7,lr in User TA call system call use svc instruction, but in ABI in ARM defined r0~r3 is pass argument (http://infocenter.arm.com/help/topic/com.arm.doc.ihi0042f/IHI0042F_aapcs.pdf), so change " "r5~r7,lr" to "r4~r7,lr" but it not work and will create additional problems
     2. I doubted uint64_t data in the memory has been to change,so use uint_t* to check data in the memory there is no problem, and use disassembly to check if compiler produce error instruction,But everything looks okay
     3. According to the analysis result output is shift 32bit, so I suspect maybe the va_start or kprintf have some logic error(very few possibilities for compiler error), but va_start is compiler build-in api.

Environment : QEMU

OPTEE Experts please give some point and suggest on this issue~~thx

**Comment by jenswi-linaro** [comment]
Please check with the latest on the master branch. There has been some fixes recently regarding alignment of the stack pointer.

**Comment by acy54321** [comment]
Hi jenswi
Problem fix in 9744b0a9601d37837a06e312f407cfb5bc76b15b
 core: thread: fix unaligned stack pointer

Fixes unaligned stack pointer in __thread_enter_user_mode. The
stack pointer must always be 8 byte aligned when entering a new
function.

thanks

**Comment by pascal-brand-st** [comment]
Question has been answered, but If the issue persists or you have more questions, please re-open the issue.
