### ISSUE TITLE
TA-dev-kit: Use configuration flags from platform being built

### ISSUE THREAD

**Issue by jockebech** [OP-TEE/optee_os#87]
In the current version of TA-dev-kit we have hard-coded flags in ta/mk/ta_dev_kit.mk. In some situation this will be a problem since different platforms have need for different set of flags.

We should instead change TA-dev-kit so that it makes use of the configuration flags coming from the current platform being built.

**Comment by jforissier** [comment]
Implemented in PR #165.

**Comment by pascal-brand-st-dev** [comment]
@jbech-linaro Do you want to close it?
