### ISSUE TITLE
Does every core have its own TTBR on multicore ARMv8 and ARMv7 platform?

### ISSUE THREAD

**Issue by zzm7000** [OP-TEE/optee_os#871]
Hi

I have been searching and could not find the answer. On a multicore ARMv8 platform, does every core have its own set of TTBR0_EL1, TTBR1_EL1, TTBR0_EL2, and TTBR0_EL3? Or, there is just one single instance of each register no matter how many cores there are? It makes more sense to me that each core has its own set. But, I could not find any document to support that. 

Thanks!

**Comment by jenswi-linaro** [comment]
Each core has its own set.

**Comment by zzm7000** [comment]
Thank you!
