### ISSUE TITLE
Open sockets when TA crashes

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#873]
Just wondering if a TA crashes while having open sockets on the supplicant side, do these sockets get closed automatically?

**Comment by jbech-linaro** [comment]
@peterfeifanchen I don't think I understand? Are you referring to the socket API which we still haven't implemented?

**Comment by peterfeifanchen** [comment]
So in the optee os, it uses the supplicant to open and close sockets. These are opened with the GP internal APIs. Just wondering if I was to shut down the client application with ctrl+c, or the optee os crashes in say TEE_ReadObjectData(), is there some mechanism to clean up the fd still left open by the TA at that time on the supplicant side or are they left open?

**Comment by etiennec-linaro** [comment]
When a client application invokes a TA, the  libteec issues a  syscall. Once the client thread enters optee driver it becomes un-interruptible (and can't be killed) until returning from the syscall.
That said, when a TA or optee-os needs to access data on the linux filesystem, optee-os invokes tee-supplicant to open then access then close the file, using the still un-interruptible thread refered on optee driver.

Hence, when a client application becomes back interruptible, the linux fs file accesses are already completed and no file descriptor is pending in tee-suppliciant.

Regarding network socket, current tee-supplicant does  not handle sockets as jbech pointed out.
Up to 2.1.0 at least.

Note that the tee-suppliciant itself is interruptible while executing or waiting in optee driver.

**Comment by haleyyew** [comment]
@etiennec-linaro I don't think you quite understand the question, the task is to have the TA requesting an rpc to the tee-supplicant to create sockets and open a network connection. If the TA in the secure world crashes, the TEE calls CloseSession automatically to clean up all the memory (including the list of fd's) for that TA session. So no traces of fd will be left. The issue now is if TA crashes, the server on the other end of the socket connection doesn't know that the client has crashed, therefore would never close the network connection.

**Comment by jenswi-linaro** [comment]
This hypothetical as the code isn't written yet, but I guess it would work something like that. The server should notice that the connection is closed from the client side.
