### ISSUE TITLE
optee-os porting to an arm64-bit board

### ISSUE THREAD

**Issue by chinnabha** [OP-TEE/optee_os#874]
#Hi Jens,

The architecture folder of optee-os has only "arm" folder @https://github.com/OP-TEE/optee_os/tree/master/core/arch/arm. There is no arch64 folder available.

Kindly tell me where is the relevant source code and whether optee-os supports arm64 compilation? 

Thanks,
Chinnabha

**Comment by vchong** [comment]
There is no aarch64 specific folder. Both are in the arm folder.

**Comment by chinnabha** [comment]
Thanks Vector for the help.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
