### ISSUE TITLE
Trying to access a secure memory region from the non secure world

### ISSUE THREAD

**Issue by jsherman3** [OP-TEE/optee_os#876]
Hello,

I was wondering if you would simply make a pointer in the TA and try to access it from the NS world would it throw an exception? And also, is there some configuration file that configures which region of memory is secure or non secure?

**Comment by jenswi-linaro** [comment]
All this is platform specific. Normally you would get an asynchronous external abort, the memory regions are usually configured via hardware registers.

**Comment by jbech-linaro** [comment]
Related to this question, a while ago I played with accessing (shared) memory directly by just mmap the address.
https://github.com/jbech-linaro/trasher

Non-shared memory however (that Jens referred to), should not be accessible at all.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by yym-hjr** [comment]
@jbech-linaro
Hello：
 In accordance with your code, Found in the end of the program “while()” the function jump does not come out,, which means that the Linux side can not change the value of this * buf? If the linux side again on the shared memory to read and write, how can I do.Looking forward to your reply.thanks
