### ISSUE TITLE
Dependencies when building a TA

### ISSUE THREAD

**Issue by renzoz** [OP-TEE/optee_os#878]
Hello again, 
I have setup all the enviromment from scratch and the hello world example seems to be working just fine. But now that I want to develop some applications, so I looked around the make files and was able to setup a project for a CA on eclipse. Unfortunately I'm not very knowledgeable on make files to get what it's going on when building a TA.
So I wonder, is there a clear list of dependencies and a building steps needed to build a TA? or would it be too complicated to be set up on an IDE.
Thanks

**Comment by jbech-linaro** [comment]
I'm not using Eclipse, so how hard it is I cannot tell, but what is needed to compile a TA is that your first build `optee_os` which creates the so called "TA DEV KIT". That is a pre-condition to be able to compile TA's. When that is done, you simply need to set (needs tweak for 64 vs 32-bit platform).
```
# Path to the TA-DEV-KIT coming from optee_os
export TA_DEV_KIT_DIR=${ROOT}/optee_os/out/arm/export-ta_arm32
```

You probably also want to set the correct platform, as an example for QEMU 32-bit that would be:
```
export PLATFORM=vexpress
export PLATFORM_FLAVOR=qemu_virt
```

And then you need to set the cross compile variable (the compiler must of course also be known, either by `$PATH` variable or the correct filesystem path)

```
# Toolchain prefix for the Trusted Applications
TA_CROSS_COMPILE=arm-linux-gnueabihf-
```

The makefiles for the TA's should be the same, as a reference you can see how the makefiles in xtest (optee_test) are looking. All of them include this common file:
https://github.com/OP-TEE/optee_test/blob/master/ta/ta_common.mk

And the makefile for the TA is a simple as this:
https://github.com/OP-TEE/optee_test/blob/master/ta/storage/Makefile

The final step is to just run `make` (use `O=path) if you want to store the built files somewhere else. If you don't care, leave it out).
```
# Build the Trusted Application
make O=$CURDIR/ta/out CROSS_COMPILE=$TA_CROSS_COMPILE
```

**Comment by renzoz** [comment]
Hello,
I didn't know it was platform specific. I guess that if I want to build it for the HiKey board I would need to build everything based on the HiKey manifest, correct?
Also how can I include multiple source/header files and directories into the makefile?
Thanks

**Comment by renzoz** [comment]
**UPDATE** I just figure how to include multiple local files.
I use the sub.mk to include source files with their relative path such as:
`srcs += extra/extra.c`
The header files are also included as locals:
`#include "extra/extra.h"`
