### ISSUE TITLE
Tmp stacks aren't defined for more than 8 CPUS

### ISSUE THREAD

**Issue by chinnabha** [OP-TEE/optee_os#879]
Hi all,

May I know why the temporary stacks are not defined for more than 8 CPUs in /core/arch/arm/kernel/threads.c?  Does it because optee_os current requirement is to support 8 cores at max? Can these stacks extended to support more cpu cores in the future? Hope there are no limitations to extend the stacks.

const vaddr_t stack_tmp_top[CFG_TEE_CORE_NB_CORE] = {
        GET_STACK(stack_tmp[0]),
#if CFG_TEE_CORE_NB_CORE > 1
        GET_STACK(stack_tmp[1]),
#endif
#if CFG_TEE_CORE_NB_CORE > 2
        GET_STACK(stack_tmp[2]),
#endif
#if CFG_TEE_CORE_NB_CORE > 3
        GET_STACK(stack_tmp[3]),
#endif
#if CFG_TEE_CORE_NB_CORE > 4
        GET_STACK(stack_tmp[4]),
#endif
#if CFG_TEE_CORE_NB_CORE > 5
        GET_STACK(stack_tmp[5]),
#endif
#if CFG_TEE_CORE_NB_CORE > 6
        GET_STACK(stack_tmp[6]),
#endif
#if CFG_TEE_CORE_NB_CORE > 7
        GET_STACK(stack_tmp[7]),
#endif
#if CFG_TEE_CORE_NB_CORE > 8
**#error "Top of tmp stacks aren't defined for more than 8 CPUS"**
#endif
};

Regards,
Chinnabha

**Comment by jbech-linaro** [comment]
There is no strict limit, we just thought it was sane to use 8 cores as maximum at the time when we did this. You can extend it if you so wish.

**Comment by chinnabha** [comment]
Got it. Thanks Joakim.

**Comment by chinnabha** [comment]
Can the number of cores defined via CFG_TEE_CORE_NB_CORE needs to be same as the number of cores running in Normal OS? 

If normal world is running with 8 cores can the optee_os execution confined to first 4 cores by defining  CFG_TEE_CORE_NB_CORE = 4?

**Comment by jenswi-linaro** [comment]
With current design `CFG_TEE_CORE_NB_CORE` has to be at least as large as the number of cores to start. This is because before a cpu be enter non-secure state it has to be configured in secure state and for that we need a stack.

The size of the tmp stack is a bit large, mainly because we'd like to use debug prints even when running with tmp stack. For production use you'd never need that and the tmp stacks could be much smaller.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by jforissier** [comment]
@chinnabha the hard-coded array of tmp stack pointers has been removed in commit https://github.com/OP-TEE/optee_os/commit/3aa8bf429a69cfa6ccef5edf4908677aceb1d7bf so you should not need to change the code anymore to use `CFG_TEE_CORE_NB_CORE` greater than 8.

**Comment by chinnabha** [comment]
Sure. Thanks for the update.
