### ISSUE TITLE
How to extract public key from RSA key pair

### ISSUE THREAD

**Issue by toddkuhreng** [OP-TEE/optee_os#880]
Hi,

I am trying to generate the RSA key pair inside TA and trying to share the public key component of it to normal world app. I am not able to figure out how to extract the public key component of the RSA key pair and send it to Normal world application. I guess I just need to extract the modulus and exponent  from the rsa key pair; but how do I do that? Any help is appreciated, thanks a lot!

Following is the TA code I  have written:

```
static TEE_Result Generate_RSA_key_pair_and_get_pub_key_from_it(uint32_t param_types,
    TEE_Param params[4])
{
  TEE_BigInt *out_param_exponent = (TEE_BigInt *)params[0].memref.buffer;
  TEE_BigInt *out_param_modulus = (TEE_BigInt *)params[1].memref.buffer;
  size_t key_size;
  size_t bigInt_len;
  TEE_BigInt *bigIntExp;
  TEE_BigInt *bigIntMod;
  uint8_t  buffer[512] =  {0};
  uint8_t  mod[512] = {0};
  uint32_t bufferlen;
  uint32_t rsa_alg = TEE_ALG_RSAES_PKCS1_V1_5;
  TEE_ObjectInfo info;
  uint32_t modlen;
  uint32_t res;
  TEE_OperationHandle handle = (TEE_OperationHandle)NULL;
 
  uint32_t exp_param_types = TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_OUTPUT,
      TEE_PARAM_TYPE_MEMREF_OUTPUT,
      TEE_PARAM_TYPE_NONE,
      TEE_PARAM_TYPE_NONE);

  if (param_types != exp_param_types)
    return TEE_ERROR_BAD_PARAMETERS;


  key_size = 512;

  /* Generate the RSA key pair */
  res = TEE_AllocateTransientObject(TEE_TYPE_RSA_KEYPAIR, key_size, &rsa_keypair);

  if (res != TEE_SUCCESS) {
    DMSG("TEE_AllocateTransientObject failed!TEE_AllocateTransientObject res: 0x%x", res);
  }

  res = TEE_GenerateKey(rsa_keypair, key_size, NULL, 0);
  if (res != TEE_SUCCESS) {
    DMSG("TEE_GenerateKey failed!TEE_GenerateKey res: 0x%x", res);
  }
  /* END Generate RSA key pair */

  /* initialize the BigInt structure */
  bigInt_len =  TEE_BigIntSizeInU32(key_size);
  bigIntExp =(TEE_BigInt *)TEE_Malloc(bigInt_len * sizeof(TEE_BigInt), TEE_MALLOC_FILL_ZERO);
  TEE_BigIntInit(bigIntExp, key_size);
  bigIntMod =(TEE_BigInt *)TEE_Malloc(bigInt_len * sizeof(TEE_BigInt), TEE_MALLOC_FILL_ZERO);
  TEE_BigIntInit(bigIntMod, key_size);

  /* get the public value, as an octet string */
  bufferlen = sizeof(buffer);
  res = TEE_GetObjectBufferAttribute(rsa_keypair, TEE_ATTR_RSA_PUBLIC_EXPONENT, buffer, &bufferlen);
  if (res != TEE_SUCCESS) {
    DMSG("TEE_GetObjectBufferAttribute failed!TEE_GetObjectBufferAttribute res: 0x%x", res);
  }
  modlen = sizeof(mod);
  res = TEE_GetObjectBufferAttribute(rsa_keypair, TEE_ATTR_RSA_MODULUS, mod, &modlen);
  if (res != TEE_SUCCESS) {
    DMSG("TEE_GetObjectBufferAttribute (Modulus) failed!TEE_GetObjectBufferAttribute res: 0x%x", res);
  }

  /* convert the octet string to a BigInt */
  res = TEE_BigIntConvertFromOctetString(bigIntExp, buffer, bufferlen, 0);
  if (res != TEE_SUCCESS) {
    DMSG("TEE_BigIntConvertFromOctetString failed!TEE_BigIntConvertFromOctetString res: 0x%x", res);
  }

  res = TEE_BigIntConvertFromOctetString(bigIntMod, mod, modlen, 0);
  if (res != TEE_SUCCESS) {
    DMSG("TEE_BigIntConvertFromOctetString failed!TEE_BigIntConvertFromOctetString res: 0x%x", res);
  }

  memcpy(out_param_exponent, bigIntExp, (bigInt_len * sizeof(TEE_BigInt)));
  memcpy(out_param_modulus, bigIntMod, (bigInt_len * sizeof(TEE_BigInt)));

  TEE_Free(bigIntExp);
  TEE_Free(bigIntMod);

  return TEE_SUCCESS;
}
```
Then I printed out these out_param_exponent and out_param_modulus variables at normal world in hex form. Tried to encrypt a value at normal world using these modulus and exponent,  and tried to decrypt this encrypted value at trusted app side. But it didn't decrypt the value at trusted side correctly.  Is there any obvious mistake with what I am doing?  Any help is greatly appreciated. Thanks a lot!

**Comment by toddkuhreng** [comment]
I created a transient object of type TEE_TYPE_RSA_PUBLIC_KEY and filled the exponent and modulus value. It worked.

**Comment by tesmnorth** [comment]
Can you share last code? Because I dont understand error

**Comment by akoskinas** [comment]
Hello everyone,

I have recently started an internship and one of its goals is to explore OP-TEE and to examine how it can be utilized to enhance security in some existing applications. At the moment I am using a Raspberry Pi Model 3b, and by following the instructions in the OP-TEE documentation, I managed to port OP-TEE to the pi and to run xtest successfully. 

After that, I am trying to achieve some basic functionality and one of the very first things I wanted to do is to create an RSA key pair inside the TEE and extract the public key to the normal world. I followed an approach similar to the one mentioned here, but I couldn't get it to run successfully. 

More specifically, inside the ta.c file, I use the function TEE_AllocateTransientObject to initialize an object and the TEE_GenerateKey function to generate the RSA key pair. To my understanding, then the option that I have is to call function TEE_GetObjectBufferAttribute with TEE_ATTR_RSA_PUBLIC_EXPONENT as an argument to get back a pointer pointing at the exponent. 

Is this approach / reasoning correct? And how should I proceed to return the exponent and the modulus to the normal world? Any help is more than welcome. Thanks in advance.

**Comment by jforissier** [comment]
@akoskinas all correct. The public exponent will be returned in the supplied buffer as a "bignum", which is an unsigned number in big-endian format. You may store this value in shared memory (output memref) so as to be able to read it in the client application when the TA returns. See the "random" example ([here](https://github.com/linaro-swg/optee_examples/blob/master/random/ta/random_example_ta.c#L64-L89)) for details how to do it.
