### ISSUE TITLE
TZDRAM configuration for optee_os

### ISSUE THREAD

**Issue by chinnabha** [OP-TEE/optee_os#881]
Hi all,

I need to fix the TZDRAM base address and size on my board to load and run the optee_os from TZDRAM. But I am not sure what is exactly TZDRAM and how to configure TZDRAM. Please help me answering the following:

1. Is it simply some DRAM space which is not in the address space of normal OS?
2. Can the DDR configuration cover the TZDRAM space or TZDRAM needs to be configured separately? 
3. If TZDRAM configuration can be part of DDR configuration, are there any specific things that needs to be taken care for TZDRAM space?

Kindly provide me if there is any link available which explains the steps for TZDRAM configuration.

Thanks,
Chinnabha

**Comment by jenswi-linaro** [comment]
Hi,

TZDRAM is TrustZone protected DRAM which can't be accessed by non-secure world. How to set it  up is hardware specific, please check the reference manual for your hardware.

Regards,
Jens

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by chinnabha** [comment]
Thanks very much for the help. 

It seems it takes sometime for my TZDRAM to be configured and available for optee_os. Meanwhile I want to integrate optee_os with ATF and UBoot/UEFI. Can I load and run optee_os from normal DRAM just by initializing TZDRAM_BASE with some location in DRAM? Or is it fundamentally violating something here? 

This is just temporary set up to speed up my development.

Regards,
Chinnabha

**Comment by vchong** [comment]
Yes it won't be secure but for test purpose it should be fine.

**Comment by chinnabha** [comment]
Thank you. You are saying it won't be secure because the optee_os is located in DRAM (or) optee_os won't behave like secure os due to its placement in DRAM?

As we aware the Trustzone enabled MMU is seen as two virtual MMUs one running normal address space and the other running secure address space on time sharing. So, on which virtual MMU the optee_os runs when it is executed from normal DRAM? 

Regards,
Chinnabha

**Comment by vchong** [comment]
It won't be secure because optee_os is located in unprotected DRAM, but it will not behave any differently due to its location in memory.

**Comment by chinnabha** [comment]
So, all the processors (primary/secondary) execute optee_os in secure EL1 itself in spite optee_os placement in normal DRAM? I am little worried about the NS bit in secure EL1 MMU and caches. The NS bit of optee_os program/data memory indicates it is secure memory but it actually referring to normal DRAM.

**Comment by vchong** [comment]
The NS bit determines if the program execution is in the Secure or Non-secure world. I don't think it has anything to do with whether memory is protected or not. Experts out there please chip in if I'm wrong. As you mentioned previously this is temporary only anyway until you're able to setup TZDRAM. Until then just make sure normal world code doesn't trample across that space. 

[1] http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0333h/Chdfjdgi.html

**Comment by chinnabha** [comment]
You are correct. As a temp set up I tested optee_os on normal RAM. No issues.
