### ISSUE TITLE
Failed to load tee-supplicant in latest version of op-tee for qemu

### ISSUE THREAD

**Issue by toddkuhreng** [OP-TEE/optee_os#884]
Hi,

Everything was working fine till I updated the my op-tee repo for qemu platform. 
Now I am not able to load tee-supplicant. I am getting following error. 
What could be the problem?  
![op-tee](https://cloud.githubusercontent.com/assets/20192842/16443302/48f62bd8-3dd8-11e6-8502-d4284f8c6b63.png)
Thanks a lot!

**Comment by jbech-linaro** [comment]
@toddkuhreng I've re-synced my forest, rebuilt all and I have no issues. See the screenshot below, there is both the repo sync, what my revisions are and that tee-supplicant loads as it should. Please try to clean your forest and rebuilt again.

![screenshot from 2016-06-29 09-10-28](https://cloud.githubusercontent.com/assets/6168937/16443499/8b97f33a-3dd9-11e6-9c50-39c3500ed55a.png)

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
