### ISSUE TITLE
optee_os execution from normal DRAM

### ISSUE THREAD

**Issue by chinnabha** [OP-TEE/optee_os#890]
Hi all,

It takes sometime for my TZDRAM to be configured and available for optee_os. Meanwhile I want to integrate optee_os with ATF and UBoot/UEFI booting chain. Can I load and run optee_os from normal DRAM just by initializing TZDRAM_BASE (@https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-xxxx/platform_config.h) with some location in DRAM? Does it fundamentally violates something or is that ok? 

This is just temporary set up to speed up my development. 

Regards,
Chinnabha

**Comment by vchong** [comment]
Answered in #881. Please close issue.

**Comment by chinnabha** [comment]
That issue is different as per me. May be I did not able to correlate. Kindly help here.

**Comment by chinnabha** [comment]
sorry, did not notice your message. closing this.

Thanks a lot.
