### ISSUE TITLE
Debugging TEE OS calls

### ISSUE THREAD

**Issue by hoihochan** [OP-TEE/optee_os#900]
While I was debugging several issues at the OS level, it seems IMSG/EMSG are not working somehow. How do I insert proper printf-like statements? For example these are what I see on the console:

FLOW:    [0x0] TEE-CORE:trace_syscall:143: syscall #26 (syscall_cryp_obj_get_attr)
FLOW:    [0x0] TEE-CORE:trace_syscall:143: syscall #19 (syscall_hash_update)
FLOW:    [0x0] TEE-CORE:trace_syscall:143: syscall #20 (syscall_hash_final)
FLOW:    [0x0] TEE-CORE:trace_syscall:143: syscall #28 (syscall_cryp_obj_close)
FLOW:    [0x0] TEE-CORE:trace_syscall:143: syscall #28 (syscall_cryp_obj_close)
FLOW:    [0x0] TEE-CORE:trace_syscall:143: syscall #17 (syscall_cryp_state_free)

However if the syscall panics I do not know the exact line of code that caused it.

Thanks!

**Comment by jbech-linaro** [comment]
When calling make, ensure the you provide the `CFG_TEE_CORE_LOG_LEVEL=[1 .. 4]` (for an example see [here](https://github.com/OP-TEE/optee_os/blob/master/.travis.yml#L113-L114)). The levels and how they are working could be found [here](https://github.com/OP-TEE/optee_os/blob/ff3dc8402d97d4753af7a6d872fecf2035285592/lib/libutils/ext/include/trace_levels.h#L48-L53). How to use those, could been found [here](https://github.com/OP-TEE/optee_os/blob/ff3dc8402d97d4753af7a6d872fecf2035285592/lib/libutils/ext/include/trace.h#L60-L93).
