### ISSUE TITLE
Does the op-tee support  TA to REE call？

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#904]
Hi ：
Currently we support rpc from the optee-kernel to linux-kernel/tee-supplicant, but no support for TA to linux-kernel and no support for TA to CA(client application) rpc.

Any plan to support or any suggestion for how to implement?

Thanks.

**Comment by jbech-linaro** [comment]
Hi, there is no such plan to do that and that would also violate the GP specification I think. If you need to expose more services (besides what is stated in GP), then you should add that to the TA itself.

What is the use case you're thinking about?

**Comment by prime-zeng** [comment]
In the DRM solution, we need the callback from the TEE to REE, i think it is similar to Secure Storage(RPMB/REE FS), but it  is a general solution.

**Comment by prime-zeng** [comment]
Of course it is not in the scope of the GP specification, but i don't think there is violation.

**Comment by etiennec-linaro** [comment]
When a linux client application invokes an optee service, the optee services executes in the context of client application linux (user) thread. While TA is invoked, all RPCs called from optee  are executed in the context of the initial client application thread. RPCs to optee driver are served straight. RPCs to tee-supplicant trig wakeup of supplicant thread (that is blocking waiting   (blo do release the supplicant blocking access and blocking waits for supplicant to complete. wait for
 Tee-supplicant itself run from inits and endlessly waits, on its own thread for optee requests.

In your setup, in which context should the REE callback be executed ? 

If in the same linux thread context as the client application that invoked the TA,  then using the current design, the client application could simply use TA specific return values to detect some callback should be called and TA invoked back on callback completed.

If the callback is to be executed in another thread/process, then:
- same as above, and callback triggs a semaphore/signal/... to the target thread. 
- or we could think of some optee linux driver device blocking entry. A linux client could be blocking wait for its TA RPC as current tee-supplicant does. But its not easy to define how client application "supplicants" could register to RPCs from specific TA instances. Moreover, such services are available only as far as the target TA instance is "alive" in optee.

**Comment by etiennec-linaro** [comment]
(updated comment)
In your setup, in which context should the REE callback be executed ?

If in the same linux thread context as the client application that invoked the TA, then using the current design, the client application could simply use TA specific return values to detect some callback should be called and TA invoked back on callback completed.

If the callback is to be executed in another thread/process, then:
- same as above, and callback triggs a semaphore/signal/... to the target thread.
- or we could think of some optee linux driver device blocking entry. A linux client could be blocking wait for its TA RPC as current tee-supplicant does. But its not easy to define how client application "supplicants" could register to RPCs from specific TA instances. Moreover, such services are available only as far as the target TA instance is "alive" in optee.

**Comment by prime-zeng** [comment]
I have to scenarios：
1. The callback is to be executed in another thread, i think semaphore/signal will satisfy the requirement.
2. The callback context is in the kernel space, something like the shm_alloc rpc, and now i can add a new rpc cmd like shm_alloc, but that's not a good way, since we need to modify the common source code each time we add a new callback, and a common mechanism is appreciated. 

Currently i could think of a new optee linux agent driver, which extends the  op-tee driver, it can maintains a list of agents which each of them can process specified rpcs. and the op-tee is an instance of agent,  the op-tee linux agent driver provides 4 interfaces for both kernel and userspace: 
1.  register an agent which creates an instance of the agent with the driver. 
2.  recv event which waits for the event for the specified agent and get the event from the agent driver.
3.  send event which send the rpc result back to the TEE(such as the op-tee driver does. now)
4. unregister the agent with the agent linux driver.

And users are allowed to do their callback after receive the rpc event.

**Comment by jbech-linaro** [comment]
@prime-zeng have you digged more into this? It sound like this also is related to the question you had regarding the limitation in the current TEE driver that only talks to a single supplicant?

**Comment by prime-zeng** [comment]
Not yet, currently this problem is not urgent  for me,  i just have a basic idea, but i 'd rather you can take it as a future feature.

**Comment by jbech-linaro** [comment]
Alright, I'll note it down internally and I'll let this stay open until we've decided what to do about it (marking it with the Enhancement label).

**Comment by jbech-linaro** [comment]
An update here, this is what @lackan is working with and we have a Jira ticket for this in Linaro also (SWG-254: Secure- to normal-world upcalls). Since it is ongoing work and already tracked, I will close this issue here at GitHub.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
