### ISSUE TITLE
Periodic task in Secure World

### ISSUE THREAD

**Issue by dsblue** [OP-TEE/optee_os#911]
What is the best practice for handling periodic tasks in the secure world?  For example how can OP-TEE be configured to execute a task every 100 ms?  I assume this would be with a secure timer interrupt, but is there a standard for doing this in OP-TEE? Like a secure system tick task?

**Comment by jenswi-linaro** [comment]
No, we don't have a standard for that yet. It would need to run in FIQ context so one has to be careful about which functions to use.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
