### ISSUE TITLE
Need helping configuring Android.mk file ( AOSP + OPTEE )

### ISSUE THREAD

**Issue by jsherman3** [OP-TEE/optee_os#913]
Hello, currently I'm trying to make an Android app that communicates natively with OP-TEE using the JNI interface.  I started off using the hello_world OP-TEE example, and tried implementing a native method.

code:

```
#include<jni.h>
#include<string.h>
#include <err.h>
#include <stdio.h>
#include "tee_client_api.h"
#include "ta_hello_world.h"

jstring Java_com_example_jsherman_ndktest_MainActivity_helloWorld(JNIEnv* env,jobject obj){


	TEEC_Result res;
	TEEC_Context ctx;
	TEEC_Session sess;
	TEEC_Operation op;
	TEEC_UUID uuid = TA_HELLO_WORLD_UUID;
	uint32_t err_origin;

	/* Initialize a context connecting us to the TEE */
	res = TEEC_InitializeContext(NULL, &ctx);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_InitializeContext failed with code 0x%x", res);

	/*
	 * Open a session to the "hello world" TA, the TA will print "hello
	 * world!" in the log when the session is created.
	 */
	res = TEEC_OpenSession(&ctx, &sess, &uuid,
			       TEEC_LOGIN_PUBLIC, NULL, NULL, &err_origin);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_Opensession failed with code 0x%x origin 0x%x",
			res, err_origin);

	/*
	 * Execute a function in the TA by invoking it, in this case
	 * we're incrementing a number.
	 *
	 * The value of command ID part and how the parameters are
	 * interpreted is part of the interface provided by the TA.
	 */

	/*
	 * Prepare the argument. Pass a value in the first parameter,
	 * the remaining three parameters are unused.
	 */
	memset(&op, 0, sizeof(op));
	op.paramTypes = TEEC_PARAM_TYPES(TEEC_VALUE_INOUT, TEEC_NONE,
					 TEEC_NONE, TEEC_NONE);
	op.params[0].value.a = 42;

	printf("Invoking TA to increment %d\n", op.params[0].value.a);
	res = TEEC_InvokeCommand(&sess, TA_HELLO_WORLD_CMD_INC_VALUE, &op,
				 &err_origin);
	if (res != TEEC_SUCCESS)
		errx(1, "TEEC_InvokeCommand failed with code 0x%x origin 0x%x",
			res, err_origin);
	printf("TA incremented value to %d\n", op.params[0].value.a);

	/*
	 * We're done with the TA, close the session and
	 * destroy the context.
	 *
	 * The TA will print "Goodbye!" in the log when the
	 * session is closed.
	 */

	TEEC_CloseSession(&sess);

	TEEC_FinalizeContext(&ctx);


    return (*env)->NewStringUTF(env,"Hello world");
}
```

Android.mk file:

```
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libteec
LOCAL_SRC_FILES := /home/jsherman/devel/optee/optee_client/out/export/lib/libteec.so
include $(PREBUILT_SHARED_LIBRARY)


include $(CLEAR_VARS)
CFG_TEEC_PUBLIC_INCLUDE = /home/jsherman/devel/optee/optee_client/public

LOCAL_SHARED_LIBRARIES := libteec
LOCAL_MODULE := ndktest
LOCAL_SRC_FILES := ndktest.c

LOCAL_C_INCLUDES := /home/jsherman/devel/optee/optee_hello_world/ta/include \
		$(CFG_TEEC_PUBLIC_INCLUDE) \
		/home/jsherman/devel/optee/optee_client/libteec/src/ \

include $(BUILD_SHARED_LIBRARY)
```

I'm pretty sure my Android.mk file is configured incorrectly, but cant seem to find any solution.  Any thoughts?

**Comment by etiennec-linaro** [comment]
looks ok. any traces? issues at build time or at runtime?

**Comment by d3zd3z** [comment]
Feel free to post specific errors, which will be helpful to see what might be going wrong.

**Comment by vchong** [comment]
User is getting undefined reference errors to the TEEC_* functions [1].

```
/home/jsherman/AndroidStudioProjects/NDKTest/jni/ndktest.c:19: undefined reference to'TEEC_InitializeContext'
/home/jsherman/AndroidStudioProjects/NDKTest/jni/ndktest.c:27: undefined reference to 'TEEC_OpenSession'
/home/jsherman/AndroidStudioProjects/NDKTest/jni/ndktest.c:51: undefined reference to 'TEEC_InvokeCommand'
/home/jsherman/AndroidStudioProjects/NDKTest/jni/ndktest.c:66: undefined reference to 'TEEC_CloseSession'
/home/jsherman/AndroidStudioProjects/NDKTest/jni/ndktest.c:68: undefined reference to 'TEEC_FinalizeContext'
```

[1] http://www.96boards.org/forums/topic/need-help-with-configuring-android-mk-file-aosp-optee/

**Comment by d3zd3z** [comment]
I don't think you're going to be able to use the libteec.so out of the optee-build. There should be one in the Android tree, and it should be sufficient to just have
```
LOCAL_SHARED_LIBRARIES := libteec libcrypto
```
in your Android.mk to link against them. Android libraries will be build with different options and dependencies than the conventional linux userspace libraries build in an OP-TEE standalone build.

**Comment by jsherman3** [comment]
@d3zd3z, where is this .so library in the Android tree?

**Comment by d3zd3z** [comment]
It's put in out/target/product/hikey/system/lib(64)/libteec.so. It should get built on demand when you have a dependency on it. If your tee-supplicant is getting built, it should already be included.

**Comment by jsherman3** [comment]
@d3zd3z 

So my make file should look like this?

```
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libteec
LOCAL_SRC_FILES := /pathtoAOSP/out/target/product/hikey/system/lib(64)/libteec.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libcrypto
LOCAL_SRC_FILES := /pathtolibcrypto/libcrypto.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
CFG_TEEC_PUBLIC_INCLUDE = /home/jsherman/devel/optee/optee_client/public

LOCAL_SHARED_LIBRARIES := libteec libcrypto
LOCAL_MODULE := ndktest
LOCAL_SRC_FILES := ndktest.c

LOCAL_C_INCLUDES := /home/jsherman/devel/optee/optee_hello_world/ta/include \
        $(CFG_TEEC_PUBLIC_INCLUDE) \
        /home/jsherman/devel/optee/optee_client/libteec/src/ \

include $(BUILD_SHARED_LIBRARY)
```

**Comment by d3zd3z** [comment]
You should remove the entire part with the PREBUILT_SHARED_LIBRARY. It isn't prebuilt, and will be built by the Android build system.  Just refer to libteec and it should work.

**Comment by jsherman3** [comment]
@d3zd3z 

I'm confused, I built the Android system and put it on the HiKey board, now I'm trying to build an Android app to talk to a Trust Application.  The libraries should already be built, and I couldn't get it to compile without doing the PREBUILT-SHARED_LIBRARY stuff

**Comment by d3zd3z** [comment]
I'm not very familiar with how out-of-tree android app building works, since we're essentially using libraries that are not part of the Android tree. But, the library should be on the device, you just need it to be available at compile/link time. It is important to use one built in an Android tree, and not files/libraries that were built in a standalone OP-TEE build.

**Comment by jsherman3** [comment]
@d3zd3z, Okay, I'll try to link the one from the Android tree.

**Comment by jsherman3** [comment]
@d3zd3z I also had another question,

is it possible I can run the native hello world example from the command line?
Example:
https://github.com/jenswi-linaro/lcu14_optee_hello_world

Whenever I compile the example and adb push the binary file to /system/bin and run hello_world, it always says no such file or directory found, even though I list the /system/bin directory and it shows up.

**Comment by d3zd3z** [comment]
I suspect if you just use `adb push` it isn't ending up as executable on the target. Can you try
```
# chmod 755 /system/bin/hello_world
```
The `adb sync` command should preserve permissions, but it will require that you have the directory laid out as you will need on the target (a full Android build does this).

**Comment by jforissier** [comment]
'No such file or directory' is also displayed when a shared library is missing. Is `libteec.so` installed?

**Comment by jsherman3** [comment]
@d3zd3z, I have tried to set the permissions and then execute it and I still get no such file or directory, even though it shows up when I ls /system/bin

**Comment by d3zd3z** [comment]
As Jerome mentioned, is libteec.so installed in /system/lib and/or /system/lib64? Are you able to run the xtest binary that gets installed as part of the build?

**Comment by jsherman3** [comment]
@d3zd3z, yes the libraries are installed in /system/lib or /system/lib64, and yes xtest runs,

```
21996 subtests of which 22 failed
50 test cases of which 1 failed
0 test case was skipped
TEE test application done!
```
I still can't get hello_world to run on the command line:

Basically the steps I did were:

Download and compile AOSP+OP-TEE and put it on the board.
Compiled the hello_world for 64 bit and pushed the hello_world onto system/bin
chmod 775 /system/bin/hello_word
ran AOSP and typed the following commands:
su
tee-supplicant&
`/system/bin/sh: /system/bin/hello_world: No such file or directory
`
Another question I had was, when I compile the hello_world program, it uses the libteec.so in the OPTEE directory, I remember you mentioning that if I wanted to make the Android app using NDK, I would have to use the libteec.so in /system/lib/, How is this any different because I'm still accessing the same c file?

**Comment by d3zd3z** [comment]
It sounds like you might be trying to run a version of hello_world built for "Linux" in an Android environment. This won't work, as the necessary libraries aren't going to be present. The userspace of Android and Linux are quite different. For example, the C library used is completely different, and a library such as libteec.so are linked against the appropriate library.

We've only ever built applications for this environment by placing the files within the AOSP directory structure and building them. I don't see a fundamental reason that hello_world couldn't be built against the NDK, but you would have to figure out how to get the headers and libraries in place.

Building hello_world using the non-Android build of optee certainly isn't going to work, however.

**Comment by jsherman3** [comment]
@d3zd3z , so from my understanding, I can't run a command line version of hello_world?, I'm going to have to use Android Studio and access the c file using NDK?  Also, is the number of failed test cases that I was receiving normal for AOSP+OP-TEE?

**Comment by etienne-lms** [comment]
@jsherman3 you should be able to run a gnu/linux application is an android
env if the application is fully staticallly linked.
You must change the hello_wolrd build script for that.
I would expect both loaders are compatible to that point.

**Comment by d3zd3z** [comment]
However, we don't build static libraries for OP-TEE. I wouldn't necessarily expect even a static version of an app to work on Android, it depends on what assumptions it makes about the rest of userspace. I do think the tee devices have the same name, but in general, even device names differ in Android from conventional Linux. Certainly things like logging from the tee library will be different in Android, and won't happen properly from a non-Android app.

But, in general, you should be using Android development tools to develop Android applications.

**Comment by d3zd3z** [comment]
As far as failed test cases, can you try pulling the tip of `external/optee_client` and `external/optee_test`, and rebuilding? Specifically [this](https://github.com/OP-TEE/optee_client/commit/81f0257a4445338139b6ddc437a52f94c02c48fc), and [this](https://github.com/OP-TEE/optee_test/commit/b2865abeac9e9806a9ce785c4504ec1b7221fe50) fix a problem on Android where `/system` is not writable. Alternatively, you can do `adb remount` from the host to make system writable.

If this doesn't fix the errors, you should probably report it, though.

**Comment by jsherman3** [comment]
@d3zd3z , I tried downloading and building the latest code from https://github.com/linaro-swg/optee_android_manifest, when I try to build it, I get the following error:

```
FAILED: /bin/bash -c "(out/host/linux-x86/bin/checkpolicy -M -c 29 -o out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.tmp out/target/product/hikey/obj/ETC/sepolicy_intermediates/policy.conf > /dev/null ) && (out/host/linux-x86/bin/checkpolicy -M -c 29 -o out/target/product/hikey/obj/ETC/sepolicy_intermediates//sepolicy.dontaudit out/target/product/hikey/obj/ETC/sepolicy_intermediates/policy.conf.dontaudit > /dev/null ) && (out/host/linux-x86/bin/sepolicy-analyze out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.tmp permissive > out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ) && (if [ \"userdebug\" = \"user\" -a -s out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ]; then 		echo \"==========\" 1>&2; 	echo \"ERROR: permissive domains not allowed in user builds\" 1>&2; 		echo \"List of invalid domains:\" 1>&2; 		cat out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains 1>&2; 		exit 1; 		fi ) && (mv out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy.tmp out/target/product/hikey/obj/ETC/sepolicy_intermediates/sepolicy )"
device/linaro/hikey/sepolicy/file.te:2:ERROR 'duplicate declaration of type/attribute' at token ';' on line 15568:
type configfs, fs_type;
#line 1 "device/linaro/hikey/sepolicy/file.te"
checkpolicy:  error(s) encountered while parsing configuration
ninja: build stopped: subcommand failed.
make: *** [ninja_wrapper] Error 1
```

Any thoughts?

**Comment by vchong** [comment]
@jsherman3 See https://github.com/linaro-swg/optee_android_manifest/issues/6.

**Comment by d3zd3z** [comment]
Ah, the joys of AOSP being a moving target. In this case, this get fixed soon in [device-linaro-hikey#3](https://github.com/linaro-swg/device-linaro-hikey/pull/3). You can always just remove the redundant declaration in the described file.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by arunn-tp** [comment]
Hi,

Im trying to bring up android O with OPtee on my platform 

To expose the OPTee apis from my platform to android application i could do it by creating a Jni file so that eventually my tee apis can be accesed from my android application.

I also understand that any Tee OS can be used to access the TEE layers of my platform as long as my platform supports it.

The apis that OPTee os uses are different than that of what Trusty OS uses.

but from an android application point of view. is there any generalized way that , if the app wants to acces the TEE layers of the platfrom , say to play a DRM content, does it have to be developed keeping in mind that as to what tee os the platform supports.

in simple words. 
if i have to create an android app to access the TEE layers, does it also depend on what kind of tee-os the platform supports too , so that apis specific to that tee-os have to be called.

**Comment by vchong** [comment]
OP-TEE APIs are based on GlobalPlatform (GP) specifications so if you expose these APIs to your apk, then your apk can work with any other GP based TEE OS. Unfortunately, it seems like Trusty doesn't support GP [1] so it seems like there's nothing in common that can be generalized.

[1] https://lwn.net/Articles/708680

**Comment by arunn-tp** [comment]
@vchong thank you for helping me understand better .
