### ISSUE TITLE
why do we design pgt_cache

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#920]
Currently, optee only support limited pgt entry for user TAs, but if we don't use pager ,there is enough ram for pgt entrys, limited pgts will slow down the system with page faults, anyone who can help to explain? Thanks.

**Comment by jenswi-linaro** [comment]
Without pager enabled, pgt_cache will not result in page faults. It's just a tailored memory management for page tables then.

**Comment by prime-zeng** [comment]
The pgt entries are limited, how can it get work when  a ta's  va space exceed the limited?

**Comment by jenswi-linaro** [comment]
We could add some other config flag to affect how `PGT_CACHE_SIZE` is defined, for instance:
```
#define PGT_CACHE_SIZE  ROUNDUP(CFG_NUM_THREADS * CFG_PGTS_PER_THREAD, \
                                PGT_NUM_PGT_PER_PAGE)
```
Another option would be to allocate new page tables directly from the same memory pool as we allocate memory for TAs, but I would prefer if we wouldn't have to do that as it would complicate the code even further. There's enough of different options to keep track of as it is.

**Comment by prime-zeng** [comment]
OK. I got it, 3Q
