### ISSUE TITLE
TEE_Malloc() and TEE__GenerateRandom()

### ISSUE THREAD

**Issue by Miraje** [OP-TEE/optee_os#923]
Hi, I have some questions about the implementation of TEE_Malloc() and TEE__GenerateRandom() (this one in juno).

- TEE_GenerateRandom()

I was reading some documentation about the juno board and I saw that the board includes a "Trusted Entropy Source" which provides a 128-bit random number.

The intent of the random number is to be used as a seed for a software algorithm, some older documentation suggests using the 128-bit seed to generate '512 different random numbers'.

If I'm not mistaken the TEE_GenerateRandom() uses the board random generator when available. So my question was if TEE_GenerateRandom() would use the hardware described above?

I tried to 'follow' the code to understand how it is implemented but it was a little bit complicated but I'm thinking the TEE_GenerateRandom() uses a PRNG (more specifically Fortuna) is that wright?

- TEE_Malloc()

Another question that I have is about the TEE_Malloc() function.

I know that session context is only a pointer that is stored and passed to subsequent TEE invocations so I allocated memory for a structure that will be used as session context using TEE_Malloc().

And I wanted to know if the session context pointer is only accessible to the the secure world? as well if the memory allocated by TEE_Malloc() is only accessible to the the secure world?

At last, I wanted to thank in advance the attention and any possible clarification to the above questions.

**Comment by jenswi-linaro** [comment]
On Fri, Jul 15, 2016 at 3:05 PM, Miraje Gentilal <notifications@github.com>
wrote:

> Hi, I have some questions about the implementation of TEE_Malloc() and
> TEE__GenerateRandom() (this one in juno).
>
>    - TEE_GenerateRandom()
>
> I was reading some documentation about the juno board and I saw that the
> board includes a "Trusted Entropy Source" which provides a 128-bit random
> number.
>
> The intent of the random number is to be used as a seed for a software
> algorithm, some older documentation suggests using the 128-bit seed to
> generate '512 different random numbers'.
>
> If I'm not mistaken the TEE_GenerateRandom() uses the board random
> generator when available. So my question was if TEE_GenerateRandom() would
> use the hardware described above?
>
> I tried to 'follow' the code to understand how it is implemented but it
> was a little bit complicated but I'm thinking the TEE_GenerateRandom() uses
> a PRNG (more specifically Fortuna) is that wright?
>
Yes, that's correct. Platforms can add their own entropy source, plat-stm
does that for instance. Adding special support for Juno would be a welcome
contribution.


>    - TEE_Malloc()
>
> Another question that I have is about the TEE_Malloc() function.
>
> I know that session context is only a pointer that is stored and passed to
> subsequent TEE invocations so I allocated memory for a structure that will
> be used as session context using TEE_Malloc().
>
> And I wanted to know if the session context pointer is only accessible to
> the the secure world? as well if the memory allocated by TEE_Malloc() is
> only accessible to the the secure world?
>
TEE_Malloc() returns memory private to the specific instance of the TA. The
memory can't be accessed by normal world or other TAs. The session pointer
is also private a specific instance of the TA, see entry_invoke_command()
in lib/libutee/arch/arm/user_ta_entry.c on how it's managed.

Regards,
Jens

**Comment by Miraje** [comment]
@jenswi-linaro Thank you very much for the fast responses.
They were very helpful!

With the best regards,
Miraje Gentilal
