### ISSUE TITLE
sudo apt-get install libz1:i386

### ISSUE THREAD

**Issue by icylon** [OP-TEE/optee_os#924]
During 4.1 Prerequisites.............
No issues with libc6:i386 and libstdc++6:i386.
Below is the error message that I received for libz1:i386.
------------------------------------------------------------------------------
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'zlib1g:i386' instead of 'libz1:i386'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cron : Depends: adduser but it is not going to be installed
        Depends: libpam-runtime (>= 1.0.1-11) but it is not going to be installed
        PreDepends: dpkg (>= 1.15.7.2)
        Recommends: exim4 but it is not going to be installed or
                    postfix but it is not going to be installed or
                    mail-transport-agent
 init : PreDepends: systemd-sysv but it is not going to be installed or
                    sysvinit-core but it is not going to be installed or
                    upstart
 init-system-helpers : Depends: perl-base (>= 5.20.1-3) but it is not going to be installed
 initscripts : Depends: sysv-rc or
                        file-rc but it is not going to be installed
               Recommends: e2fsprogs
 libpam-modules : PreDepends: debconf (>= 0.5) but it is not going to be installed or
                              debconf-2.0
                  PreDepends: libpam-modules-bin (= 1.1.8-3.1+deb8u1)
 libpam0g : Depends: debconf (>= 0.5) but it is not going to be installed or
                     debconf-2.0
 x11-common : Depends: debconf (>= 0.5) but it is not going to be installed or
                       debconf-2.0
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by icylon** [comment]
This error message is on Raspberry Pi 3.

**Comment by jbech-linaro** [comment]
@icylon , just so I don't misunderstand you. You are trying to run this in a local PC running Ubuntu or something similar? I.e, you are not trying to setup the and build on the Raspberry Pi 3?

When working with the RPi3 setup I've been using Ubuntu 16.04 and Linux Mint 17.1 (which I think is based on 14.04). zlib is no new dependency in OP-TEE, it's been there for quite a while and I haven't seen any issue related to that when working the the RPi3 last week.

What OS are you running? The message above get me to think that there is yet another dependency that needs to be installed to get zlib on your PC. If we could pinpoint that, then we should add it to the pre-req list.

**Comment by d3zd3z** [comment]
For reference, I can generate a Docker image off of the baseline ubuntu 16.04 image with the following apt commands:
```
# dpkg --add-architecture i386 && \
        apt-get update && \
        apt-get -y upgrade
# apt-get update && \
        apt-get install -y \
                git \
                build-essential uuid-dev iasl \
                autoconf bison \
                cscope \
                curl flex gdisk \
                libglib2.0-dev \
                libpixman-1-dev \
                netcat \
                python-crypto \
                python-serial \
                python-wand \
                uuid-dev \
                xdg-utils \
                xz-utils \
                zlib1g-dev \
                mtools \
                libtool \
                libftdi-dev \
                libhidapi-dev \
                wget \
                python \
                libc6:i386 \
                libstdc++6:i386 \
                libz1:i386
```
The docker image has fewer packages than the desktop install, so there may be one or two extra things in there from a desktop system, but it should be sufficient.

However, the error above does look like what I'd expect to see trying to install an i386 package on an ARM system.

**Comment by icylon** [comment]
Thank you for getting back to me quickly.

I am afraid I was trying to build it on the Raspberry Pi 3.
Libz1:i386 is the only library that I wasn’t able to load.

Q

**Comment by icylon** [comment]
No issues on Ubuntu 14.04 but only lib that I am having an issue on RPi 3.

Kyu

**Comment by d3zd3z** [comment]
Just realized my list above is missing 'unzip' and 'bc' as packages.

**Comment by d3zd3z** [comment]
In theory, BTW, it should be possible to build on RPi3 itself, but the code probably makes a lot of assumptions about cross compiling. You would, however, discover, that the RPi3 isn't really all that fast.

**Comment by jbech-linaro** [comment]
Even though it sounds like an interesting "project" it's not really useful, since it will be painfully slow to build everything and besides that this is something that we are not supporting. Having that said, if you manage to pull something together that will make it work, feel free to submit patches for it and we will review it and merge it if we think it's OK.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by icylon** [comment]
Thank you for your help,

Q
