### ISSUE TITLE
why does the op-tee need to rename-section when compiling TAs?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#927]
@jenswi-linaro 
I have noticed that the rodata and rodata.str1.1  sections have been renamed when compiling TAs, but i think there is no need to do that, can we remove that?

**Comment by jenswi-linaro** [comment]
Sure, but I don't see the point.
I don't think we're interested in removing it upstream as it could be useful when compiling with `-ffunction-sections` in combination with linking with `-gc`.

**Comment by prime-zeng** [comment]
I got it , thank you so much.
