### ISSUE TITLE
OP-TEE and QEMU

### ISSUE THREAD

**Issue by icylon** [OP-TEE/optee_os#929]
I received following error message during "make all run". 
Instruction is from Linaro Connect Bangkok 2016, 
OS is Ubuntu 16.04.

Thanks in advance.

$ sudo apt-get install android-tools-fastboot autoconf bison cscope curl \
flex gdisk libc6:i386 libfdt-dev libglib2.0-dev \
libpixman-1-dev libstdc++6:i386 libz1:i386 netcat \
python-crypto python-serial uuid-dev xz-utils zlib1g-dev
$ sudo apt-get install ccache
$ mkdir -p $HOME/devel/optee
$ cd $HOME/devel/optee
$ repo init -u https://github.com/OP-TEE/manifest.git -m default.xml
$ repo sync
$ cd $HOME/devel/optee/build
$ make toolchains
**$ make all run**

ERROR
-----------------------------------
make -C /home/kyu/DEV/OPTEE/build/../optee_os O=out/arm CROSS_COMPILE="/usr/bin/ccache /home/kyu/DEV/OPTEE/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CROSS_COMPILE_core="/usr/bin/ccache /home/kyu/DEV/OPTEE/build/../toolchains/aarch32/bin/arm-linux-gnueabihf-" CROSS_COMPILE_ta_arm64=/home/kyu/DEV/OPTEE/build/../toolchains/aarch64/bin/aarch64-linux-gnu- CROSS_COMPILE_ta_arm32=/home/kyu/DEV/OPTEE/build/../toolchains/aarch32/bin/arm-linux-gnueabihf- CFG_TEE_CORE_LOG_LEVEL=3 DEBUG=1 PLATFORM=vexpress-qemu_virt
make[1]: Entering directory '/home/kyu/DEV/OPTEE/optee_os'
  CHK     out/arm/conf.mk
  CHK     out/arm/include/generated/conf.h
  GEN     out/arm/ta_arm32-lib/libutee/tui/default_bold.c
Traceback (most recent call last):
  File "scripts/render_font.py", line 29, in <module>
    from wand.image import Image
ImportError: No module named wand.image
mk/subdir.mk:150: recipe for target 'out/arm/ta_arm32-lib/libutee/tui/default_bold.c' failed
make[1]: *** [out/arm/ta_arm32-lib/libutee/tui/default_bold.c] Error 1
make[1]: Leaving directory '/home/kyu/DEV/OPTEE/optee_os'
common.mk:194: recipe for target 'optee-os-common' failed
make: *** [optee-os-common] Error 2
kyu@ubuntu:~/DEV/OPTEE/build$

**Comment by icylon** [comment]
Fixed after installing following.
apt-get install libmagickwand-dev and python-wand
Not sure if both of them are required.

**Comment by jbech-linaro** [comment]
@icylon , even though you got it to work, please follow the instructions in the README.md and it will work.

Pre-req's are super important
https://github.com/OP-TEE/optee_os/#41-prerequisites

Then get the source, so 5.1, 5.2 and 5.3 for QEMU
https://github.com/OP-TEE/optee_os/#5-repo-manifests

And the finally section 6
https://github.com/OP-TEE/optee_os/#6-load-driver-tee-supplicant-and-run-xtest

I'm testing this several times every week (using QEMU), so I'm 100% sure it's working on a Ubuntu based machine from 14.04 and later.

**Comment by icylon** [comment]
I think it would be better to make a clear statement that all should have a same pre-req if that is the case.
Pre-reqs for RPi 3 and OP-TEE with QEMU are different based on my experience.
But if the recommendation is to use a same pre-req. I think that is a good ideas but needs to clearly state “super important” for newbies like me.

Thank you for your help,

Q

**Comment by vchong** [comment]
@icylon The instructions from Linaro Connect Bangkok 2016 is outdated, hence missing the python-wand dependency. It was only required beginning April when support for text rendering was added. The latest instructions can always be found @ https://github.com/OP-TEE/optee_os/blob/master/README.md.
