### ISSUE TITLE
Can we remove the sections between text_end and rodata_start in the kern.ld.S? 

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#932]
I think it's not needed ,  can we remove it  to make a more clean kern.ld.s.
Now i want to make the text and rodata sections readonly, but the sections between them make me confused and in fact in they are empty now.

**Comment by jenswi-linaro** [comment]
Those sections aren't needed with the current compiler options. I don't want to remove them, but moving is OK if you can find a better spot.

**Comment by prime-zeng** [comment]
Can i just ignore these sections when mark all text sections ro?

**Comment by jenswi-linaro** [comment]
Yes, I suppose so.

**Comment by prime-zeng** [comment]
OK.  I get it.  Thank you.
