### ISSUE TITLE
Optee QEMU testing with multiple processes

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#937]
I want to run some concurrency tests. There is this test process I want to run multiple instances of. I wasn't sure if the QEMU VM is emulating multiple cores? I remember I read somewhere it was single core...although I don't know what or where gave me that idea. Not sure how I would also find out.

**Comment by jforissier** [comment]
QEMU supports multiple cores with `-smp cpus=n,cores=cores` (see the command-line help). For instance for 2 cores: `-smp 2,cores=2`.
I couldn't get our 32-bit OP-TEE setup [1] to boot with 2 cores (I suspect the basic loader does not support multiple cores). The ARMv8 64-bit configuration [2], however, boots successfully with 2 cores. If you want to try it out, just add `-smp 2,cores=2` into the Makefile [3]. Check `/proc/cpuinfo` to make sure 2 cores were detected. If you want more than 2 cores you'll need to increase `CFG_TEE_CORE_NB_CORE` in optee_os which is 2 by default [4].

[1] https://github.com/OP-TEE/manifest/blob/master/default.xml (32-bit QEMU manifest)
[2] https://github.com/OP-TEE/manifest/blob/master/qemu_v8.xml (64-bit QEMU manifest)
[3] https://github.com/OP-TEE/build/blob/8519bcf/qemu_v8.mk#L253-L260
[4] https://github.com/OP-TEE/optee_os/blob/e3b7383/core/arch/arm/plat-vexpress/platform_config.h#L213

**Comment by peterfeifanchen** [comment]
Yup. I get two CPUs. Thanks!
