### ISSUE TITLE
error: Cannot fetch hello_world

### ISSUE THREAD

**Issue by NightEugene** [OP-TEE/optee_os#939]
$ repo init -u https://github.com/OP-TEE/manifest.git -m rpi3_experimental.xml
$ repo sync

Fetching project busybox.git
Fetching projects:  10% (1/10)  Fetching project gen_rootfs.git
Fetching projects:  20% (2/10)  Fetching project linux.git
Fetching projects:  30% (3/10)  Fetching project build.git
Fetching projects:  40% (4/10)  Fetching project arm-trusted-firmware.git
Fetching projects:  50% (5/10)  Fetching project u-boot.git
Fetching projects:  60% (6/10)  Fetching project optee_test.git
Fetching projects:  70% (7/10)  Fetching project optee_client.git
Fetching projects:  80% (8/10)  Fetching project hello_world.git
fatal: Couldn't find remote ref refs/heads/rpi3_initial_drop
fatal: Couldn't find remote ref refs/heads/rpi3_initial_drop
error: Cannot fetch hello_world.git

error: Exited sync due to fetch errors

**Comment by vchong** [comment]
Sorry my bad. Will fix soon. In the meantime please add `revision="master"` to https://github.com/OP-TEE/manifest/blob/master/rpi3_experimental.xml#L31.

**Comment by NightEugene** [comment]
Thanks, it works!
