### ISSUE TITLE
About RPMB FEK 

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#941]
After RPMB FEK is generated by PRNG,  when and where is it  encrypted ?
I only find it is decrypted by SSK when used for encrypting block.
Is RPMB FEK considered has been encrypted after PRNG?
Looking forward to your reply, thanks.

**Comment by jforissier** [comment]
I think what you're looking for is here: https://github.com/OP-TEE/optee_os/blob/b8cceb5/core/tee/tee_fs_key_manager.c#L295-L296

**Comment by airbak** [comment]
@jforissier  thanks for your reply.
The FEK which generated in tee_fs_key_manager.c is used for normal filesystem, and it is encrypted by SSK.  But the FEK which used for RPMB is not encryped in tee_rpmb_fs.c.

**Comment by jforissier** [comment]
@airbak sorry for the confusion, I somehow missed that your question was related to RPMB (!).

You are right. I think `generate_fek()` should call `tee_fs_generate_fek()` instead of `crypto_ops.prng.read()`. Feel free to submit a pull request. Thanks.

**Comment by airbak** [comment]
Thanks for your replay.

**Comment by jforissier** [comment]
PR created: https://github.com/OP-TEE/optee_os/pull/956.
