### ISSUE TITLE
Switching from Rich OS to Secure OS

### ISSUE THREAD

**Issue by HelloCoderZ** [OP-TEE/optee_os#946]
Hi guys, I'm new to OPTEE. 
I just set up my Juno board with openembedded system as described https://community.arm.com/docs/DOC-10804 and I can enter the normal world. 

I see the source code also includes the optee folder. Now I'm wondering how could I enter the optee_os. Could you please give me some advice?

**Comment by vchong** [comment]
Hi,

What do you mean by enter optee_os? If you mean the console, there should be another uart port at the rear of the device for you to connect to. If you mean by code, then you can write a Trusted Application (TA). See https://github.com/linaro-swg/hello_world as an example.

**Comment by HelloCoderZ** [comment]
Thank you for replying @vchong . I have tried the example you give me and it works for my board. 

However, that's not what I asked for. 

For you example, both host and ta programs are saving in the Rich OS and I run them by input the command in the Rich OS. I'm wondering is there any way for me to directly interact with secure OS like input some command by console?

**Comment by vchong** [comment]
You're welcome.

The ta is indeed saved in the Rich OS but verified and executed in secure context. The secure OS doesn't offer an interactive prompt. That would make it a not very secure OS I suppose. Even if it does, it's just a minimal OS (not Linux) and contains only whatever is necessary (to reduce attack surfaces), so commands that you're probably expecting to work like `ls` or `cd` or etc will not. Maybe when Trusted UI is implemented, there can be some direct user interaction with the Secure OS, but probably not a command prompt.
