### ISSUE TITLE
Maximum code and data size for TA

### ISSUE THREAD

**Issue by KwnagBaek** [OP-TEE/optee_os#947]
Hi.

I want to know maximum data size and code size for TA
How can I find it in the source code?

Thanks,

**Comment by jforissier** [comment]
Hi @KwnagBaek,

I think the maximum size for TA code + data (including also heap and stack) is CFG_TA_RAM_SIZE.

Space for TA code and data (including the TA heap) is allocated from the `tee_mm_sec_ddr` memory pool by `load_elf()`, see here: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/user_ta.c#L232. The stack is allocated separately a few lines later from the same pool. Not that space for the heap is defined and reserved in the TA binary itself in `user_ta_header.c` which is compiled and linked with the TA (see here: https://github.com/OP-TEE/optee_os/blob/master/ta/arch/arm/user_ta_header.c#L91).

The `tee_mm_sec_ddr` pool is initialized in `tee_init_ta_ram()`: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/tee_mmu.c#L652 from information found in the memory map. ; the TA RAM is registered here: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/mm/core_mmu.c#L103.

**Comment by d3zd3z** [comment]
Note also that some of the code (at least on 64-bit) uses PC-relative loads, and some things will be restricted to +/- 1MB offsets. I haven't tried making larger TA's to see how this affects it, however.

**Comment by KwnagBaek** [comment]
Thanks All~ This is very helpful information for me.
