### ISSUE TITLE
TZPC and TZASC can be used on the hikey platform?

### ISSUE THREAD

**Issue by LeiShenHeros** [OP-TEE/optee_os#948]
Hi everyone,
I try to implement TUI on the hikey platform,and I find TZPC and TZASC can be used on the hi6210sft soc,so I guess it can be used on the hi6220 soc,too. I have been change the TZPC register and the tzpcstate register can be change by tzpcset register.  but all  peripherals are not affected.when I change the tzpcstate01 register 0xFFFFFFFF(this means all the bus set to non-secure state),set up the OP-TEE, 
the minicom will be show a Synchronization error. I have been set TZPC_DEP and AO_TZPC,but I didn't find the AXI-APB bridge.so I guess I missing something.
Could you please give me some advice?

**Comment by jforissier** [comment]
Hi @LeiShenHeros ,

Do you have some documentation on Hi6210sft TZPC/TZASC that you could share? Possibly some register offset are different on Hi6220.

**Comment by LeiShenHeros** [comment]
yes,I find a introduce in https://github.com/olrak2/android_kernel_huawei_hi6210sft/blob/44581fdbb73c5c8c77a273c3013014fb681f412a/drivers/hisi/ap/platform/hi6210sft/soc_tzpc_interface.h  and https://github.com/olrak2/android_kernel_huawei_hi6210sft/blob/44581fdbb73c5c8c77a273c3013014fb681f412a/drivers/hisi/ap/platform/hi6210sft/soc_baseaddr_interface.h. after compared the two platforms Register address list  , found that are remarkably similar.

**Comment by LeiShenHeros** [comment]
Hi @jforissier ,
I have find TZPC's PLCK and TZMA's PLCK,so I guess HI6220 soc has achieved Trustzone IP core,but I can't find a detail in hi6220 soc reference,so I guess it is not published. is it possible to other security control register isolation tzpc , leads to tzpc unable to start?
Thank you so much for your time,
LeiShenHeros

**Comment by jbech-linaro** [comment]
@jforissier would you mind have a look at this so we could give @LeiShenHeros an answer. If we cannot give an answer due to lack of specifications from our side, then I'm afraid we have to close this with no good answer and instead the advice would be to talk to Hisilicon directly.

**Comment by jforissier** [comment]
@jbech-linaro the latest and more comprehensive information I have on Hi6220 TZPC is in issue https://github.com/OP-TEE/optee_os/issues/1065. Quick summary: it is a proprietary TZPC, it seems we know how to configure UART3 in secure mode (that's code I was allowed to share) but nothing more, and HiSilicon won't publish the register mapping.

**Comment by jbech-optee-adm** [comment]
Alright, thanks for the quick reply, based on that I'll close this issue. Sorry @LeiShenHeros that we couldn't give more precise answer than we've being trying to do here in this issue. As I said, you could try talk to Hisilicon directly.
