### ISSUE TITLE
MEM_AREA_KEYVAULT cannot be used

### ISSUE THREAD

**Issue by zhupg** [OP-TEE/optee_os#949]
MEM_AREA_KEYVAULT is used for storing some secrets, but in core/arch/arm/mm/core_mmu.c
core/arch/arm/mm/core_mmu.c() and core_init_mmu_map() don't handle the type "MEM_AREA_KEYVAULT", so optee os will panic here.

By the way,  there are 4 frequency used memory type.
no cache, no secure  <-->  MEM_AREA_IO_NSEC
no cache, secured  <-->  MEM_AREA_IO_SEC
cached, secured  <-->  MEM_AREA_KEYVAULT
cached, no secure <-->  NO TEE MEM TYPE
There is no tee memory type defined for cached and no secure memory, is this for safety considerations? If no, is It better to add this type to meet different requirements?

Thanks.

**Comment by jforissier** [comment]
Yes, `MEM_AREA_KEYVAULT` should probably be handled by `core_init_mmu_map()`. I also think it is OK to add an enum for cached, non-secure memory.

**Comment by zhupg** [comment]
Dear jforissier:
    I submit a pull request #952 , Would you please help to review?

**Comment by zhupg** [comment]
closed
