### ISSUE TITLE
TA Output Message

### ISSUE THREAD

**Issue by HelloCoderZ** [OP-TEE/optee_os#954]
Hi guys,

Recently I tried an example of TA from this link: https://github.com/jenswi-linaro/lcu14_optee_hello_world .

I run the program for increasing number successfully but I don't know where I could check the result of code "DMSG("Goodbye!\n");". 
I tried the dmsg command in Rich OS while I got nothing.

Furthermore, I'm wondering if I use print function in the TA part, can I see the print result somehow?

Thank you very much.

**Comment by d3zd3z** [comment]
The output from the `DMSG` macro will depend on several factors.

- What level `CFG_TEE_TA_LOG_LEVEL` is set to when your TA is compiled. Only messages lower than this level will be printed at all.
- The particular target you are on. Currently, hikey, intermixes the Linux kernel messages and the TA messages over the same UART port. The emulators (qemu and fvp) simulate a second serial port that just shows the messages from the TA. In general, however, they will be coming over a serial port.

You might try `EMSG` to start with, since most of the time, the log level will at least be configured to print errors.

**Comment by jforissier** [comment]
About your `dmesg` question: currently the messages cannot be forwarded to the Rich OS, although we thought about implementing such a feature some time ago. Please check https://github.com/OP-TEE/optee_os/pull/810. This would definitely need some more work before it can be merged. Feel free to start form there if you're interested!

**Comment by HelloCoderZ** [comment]
Hi @d3zd3z , I'm using Juno board and I set CFG_TEE_TA_LOG_LEVEL as 2.

I tried EMSG too while I got no output from my TA. Should I set the level higher?

**Comment by HelloCoderZ** [comment]
Hi @jforissier , so in general, is there anyway for me to output a string in TA program and I could check it?

**Comment by d3zd3z** [comment]
It looks like the JUNO board uses UART1 for the messages from the secure side. Are you able to plug a serial port into the UART1 connector (I believe kernel messages come out the UART0 connector).

**Comment by HelloCoderZ** [comment]
Hi @d3zd3z , I tried the UART1 this morning while I keep getting the warning "Skipping Errata workaround for non matching CPU revision number." I google the warning but I don't find what's the exactly problem, could you please check it? Thank you.

**Comment by vchong** [comment]
Those are output from ARM-TF [1], so you're seeing messages from the secure side. Assuming everything boots up correctly/properly, you should also see the TA output when you run hello world.

[1] https://github.com/ARM-software/arm-trusted-firmware/commit/7395a725ae74de70820d7b126ba1af727f39e263#diff-ed52584d1cf17e5c507a9aac0a337917R205

**Comment by d3zd3z** [comment]
> "Skipping Errata workaround for non matching CPU revision number."

This doesn't sound like an error, or even a warning, to me. It could be worded better, but it just means that your particular CPU doesn't have this Errata, so the workaround isn't needed.

**Comment by HelloCoderZ** [comment]
@vchong Thank you for the reply. I checked it again and I do see the output. However, since I keep getting the message "Skipping Errata workaround for non matching CPU revision number." it's hard for me to catch the information from TA, do you know any method to disable this message?

**Comment by d3zd3z** [comment]
If it prints more than once, I'd call that a bug, and it probably deserves its own issue report. You could either file it against optee_os to track it here, or try to report it to upstream. It'd be nice to track here, though, since we aren't necessarily using the tip version of the firmware.

**Comment by HelloCoderZ** [comment]
@d3zd3z Okay I'll close this issue and open another one, thanks.
