### ISSUE TITLE
Secure OS Serial Port Warning Message

### ISSUE THREAD

**Issue by HelloCoderZ** [OP-TEE/optee_os#958]
Hi there, I'm using the Juno r1 board with OpenEmbedded system provided by Linaro.

This morning, I connected the board's UART1 to a serial port for getting the output of Secure OS while the port keeps outputting the warning messages: "Skipping Errata workaround for non matching CPU revision number."

I set up the board as the instruction of this link: https://community.arm.com/docs/DOC-10804.

Please let me know if there is anyway to remove these messages, thank you.

**Comment by jenswi-linaro** [comment]
Hi,

I don't know the source of those messages. Do you get them only during boot?

Regards,
Jens

**Comment by d3zd3z** [comment]
These prints are protected by `DEBUG` in `arm-trusted-firmware/lib/cpus/aarch64/cortex_a57.S`. You could either build the firmware with `DEBUG` not set, or remove these calls.

What's surprising to me is that they print constantly, figuring that out would probably take some more debugging. But it'd be interesting to see if it works by just removing the message print.

**Comment by HelloCoderZ** [comment]
@jenswi-linaro not just during the boot. For my version it keeps popping up.

@d3zd3z I remove the code and rebuilt the system, now there is no warning anymore, thanks!

**Comment by d3zd3z** [comment]
I wonder if we should report this against ARM's Trusted Firmware, or at least investigate whether the problem appears in their latest version.
