### ISSUE TITLE
why don't we use the write_ats1cpr instead of write_ats1cpw in the arm_va2pa_helper?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#965]
For read right is forced for the entire address op-tee kernel space, but  write right may not.

**Comment by etienne-lms** [comment]
i think you are right.
do you want to post a PR ?

**Comment by prime-zeng** [comment]
Yes, but i am not if the arm64 has the same issue.

**Comment by etienne-lms** [comment]
Aarch64 Implementation relies on AT_S1E1R that is equivalent to
aarch32 ats1cpr: read access from priviledge mode/secure state.

**Comment by prime-zeng** [comment]
close it since the patch is merged. #982
