### ISSUE TITLE
tee-supplicant Command Not Found

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#968]
Hi,

I'm using the Juno r1 board. 
Today I just built the OpenEmbedded LAMP system followed the instruction of https://community.arm.com/docs/DOC-10804. 
I chose the Linaro latest-armlt (15.09) and I boot the system successfully. 

I have done this one time before and for the previous OPTEE I was told to insmod the optee.ko and optee_armtz.ko before running the TA.

Now, I see your instruction 6 mentions that I could directly use the command "tee-supplicant" but when I was running I got the error "-sh: tee-supplicant: command not found".

I also checked the optee_linuxdriver folder for the ".ko" files while there is no file anymore. In this case, how could I activate the tee-supplicant and running the TA?

Thank you very much.

**Comment by vchong** [comment]
The driver is now 'integrated' into the linux kernel and hence doesn't have to be built (as a module) and loaded (insmod) separately.

Afaik the tee-supplicant is also automatically loaded in ARM's build. I might be wrong, but you can verify this using `ps -ef | grep supplicant` to see if it's already running. If yes, then you don't have to run it again, and can just go ahead and run your TAs.

**Comment by SimonWan** [comment]
Hi @vchong , thank you so much for replying me on the weekend.

I run the command you shared while I only got:

>  root      5527  1179  0 02:02 ttyAMA0  00:00:00 grep supplicant

I also tried to run the hello world program directly (the program is getting from  [https://github.com/jenswi-linaro/lcu14_optee_hello_world](url) ).  I saved the TA part in the folder

>  \lib\teetz

. However, I got this error:

> ./hello_world: error while loading shared libraries: libteec.so.1.0: cannot opey

In this case, I don't think the tee-supplicant is automatically loaded. Do you have any suggestion for me to run an example TA? I just want to see if the TrustZone part could work.

**Comment by vchong** [comment]
Not sure what the problem is either. Maybe the TEE driver in kernel itself hasn't been loaded. Try running `dmesg | grep optee`. If you get nothing there, then the driver hasn't been loaded correctly.

The TA part should be saved in `/lib/optee_armtz/`. IIRC `/lib/teetz/` might be the old path. If you `ls /lib/optee_armtz`, do you see other TA files there?

If you `ls /lib/`, do you see `libteec.so.1.0` there?

If you just want to see if the TrustZone part could work, there should be a default test suite called `xtest` under `/bin/` that you can run. 

Have you also tried the latest build (16.06?) to see if things work?

**Comment by SimonWan** [comment]
@vchong thank you for your patient.

I just checked my system again, it looks like the OE system is only deployed with OPTEE 15.09 and it doesn't load optee automatically.
Since the website [https://community.arm.com/docs/DOC-10804](url) doesn't provide OE with OPTEE 16.06 so I change the system to Android.

Now my configure is: Juno r1, Android and OPTEE 16.06.

When I using the command , I got the result:

> [    4.364096] optee firmware:optee: probing for conduit method from DT.        
[    4.370628] optee firmware:optee: initialized driver 

It looks like I have load the driver correctly. However, for the android system I don't find folder `/lib/optee_armtz/` or `/bin/` so I'm not sure how to check TA and test the TrustZone now.

Do you have any idea about run TA on Android or should I tried to figure a way to implement OE system with OPTEE 16.06?

Thank you again for your help!

**Comment by vchong** [comment]
Just fyi, there's no OP-TEE 15.09 or 16.06. These are ARM release dates/versions.

Now that the driver is loaded correctly, try `ps -ef | grep supplicant` again to see if the tee-supplicant is loaded automatically and running.

For android, you need to look under `/system/lib/optee_armtz/` and `/system/bin/`. If the files are there, then you should be able to run `/system/bin/xtest`.

**Comment by SimonWan** [comment]
@vchong sorry for misunderstanding the versions number.

I tried the `ps` command while getting nothing, I also checked the path `/system/lib` and `/system/bin` but I couldn't find the `optee_armtz` folder or `xtest` program.

Do you think the link [https://community.arm.com/docs/DOC-10804](url) is still useful for running OPTEE or should I tried other ways to configure the Juno board?

**Comment by vchong** [comment]
Sorry myself. Minor correction: the version numbers are actually Linaro releases for Juno in collaboration with ARM engineers.

I'm looking at https://community.arm.com/docs/DOC-10952 and it says that OP-TEE is not functional for 16.06, but doesn't explain why. Can you try 16.05 instead?

Looking further down, the page says that OP-TEE was only added to the default Juno build in 15.12, so probably 15.09 release doesn't have it. But you said you've done this before 15.09?

**Comment by SimonWan** [comment]
@vchong I would try the version 16.05 later. 

For my last time experience, I sync the new workspace to Linaro Release 16.02 even the OE looks stay with 15.09 and it does have the OPTEE source code in my workspace. I also find the drivers so I loaded them by myself that time.

I would let you know if I have any progress. I really appreciate your patient and nice tips!
