### ISSUE TITLE
QEMU 64-bit sys_call_table

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#970]
I have made a kernel module that intercepts the kernel system calls which then calls into the Trusted World to perform certain things before returning and letting the normal system call. This requires me to edit the sys_call_table symbol. 

In the 32-bit QEMU, the sys_call_table symbol built from linux is in the text section:
`8000f584 T sys_call_table `

However in the 64-bit QEMU, the sys_call_table symbol built froml inux is somehow in the read-only section:
```
ffffffc0006fe000 R sys_call_table
ffffffc000700000 R compat_sys_call_table
```

Is there a way to edit the kernel linker or the sys_call_table definition to put this symbol somewhere else where it is not read-only?

Thanks.

**Comment by d3zd3z** [comment]
This is a trend in the kernel, generally around the idea of increasing secure. More and more things that aren't intended to be modified are being made read-only from within the kernel.

Depending on your purposes, you could try removing the 'const' from the table definition in arch/arm64/kernel/sys.c.

I'm actually a little surprised you can write to the one in 32-bit mode. It suggests we might not have things configured as securely as desired.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
