### ISSUE TITLE
[RPMB]When multiple CPU use RPMB, it may not work well

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#972]
When two CPUs call rpmb_fs_write() in different TA, they may write data to the same address. 
Is there any LOCK for RPMB to avoid it? 
Please check it, thanks.

**Comment by jforissier** [comment]
We haven't tested RPMB with concurrent access. But, you're right, it looks like some operations like `rpmb_fs_write()` are not properly protected.
Currently, `rpmb_mutex` is used to serialize the low-level accesses to the RPMB partition, but `tee_rpmb_fs.c` has other data structures that need to be protected. I think we should move the lock higher up, i.e., at the level of `rpmb_fs_ops` probably. Could you please try it and propose a patch for us to review?

**Comment by airbak** [comment]
Thanks for your reply. I will try it and propose a patch later.

**Comment by jforissier** [comment]
@airbak has sent a patch to me privately (thanks!), I have created https://github.com/OP-TEE/optee_os/pull/1014.
