### ISSUE TITLE
[RPMB] Why call tee_mm_init() in rpmb_fs_write() each time?

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#973]
Frequent interaction with RPMB may affect performance.
Could we call tee_mm_init() in first time and save the RPMB fat info in DDR? And refresh it after write data to RPMB.
Is there any risk?

**Comment by etiennec-linaro** [comment]
i think i should be ok, with some multi-thread protection.
however make sure that you really need performance when writing to rpmb. maybe data could be kept in secure RAM and effectively stored in rpmb less often.

**Comment by airbak** [comment]
Thanks for your reply, I will try.
