### ISSUE TITLE
Fialed to find an OP-TEE supplicant device

### ISSUE THREAD

**Issue by tong901023041** [OP-TEE/optee_os#983]
I have build it by following README.md, but only linux-image-4.4.0-optee-rpb_4.4.0-optee-rpb-1_arm64.deb exist in the file. so when I send   linux-image-_.deb, only  linux-image-4.4.0-optee-rpb_4.4.0-optee-rpb-1_arm64.deb was send to the hikey board. after the dpkg command, "blockdev: ioctl error on BLKROSET: Opreation not permitted" was display on the screen, and after the tee-supplicant & command, it prompt "fialed to find an OP-TEE supplicant device". When command using ls /dev/tee_,  we can see tee0 and teepriv0.  And using command ps -A, can't find tee-supplicant. what can I do to solve this problem ?

**Comment by jforissier** [comment]
@etienne-lms yes
