### ISSUE TITLE
fiq handle problem

### ISSUE THREAD

**Issue by zhizhouzh** [OP-TEE/optee_os#985]
Hi experts,

When a NS interrupt (e.g. arch timer, IPI) occurs in secure world (say, now processor is executing optee-os instrutions now), a FIQ rises. 

Currently in optee-os code, the elx_irq handler is more like a fiq handler. elx_irq save state of optee-os then set up parameters for A-TF, at last call smc to A-TF. The A-TF return to linux to handle this irq.
And the elx_fiq's behaver is more like an irq handler, it execute the irq handler and call eret to return current EL.

So it seems now optee-os doesn't handle fiq correctly, would you please help to check it?

**Comment by prime-zeng** [comment]
NS interrupt should be set to rise the IRQ.

**Comment by zhizhouzh** [comment]
@prime-zeng 
No, according to section 4.6.2 in <IHI0069B_gic_architecture_specification_v3>,  table 4-3 shows a NS interrupts in secure-EL1 or EL0 should signal as a FIQ.

**Comment by jenswi-linaro** [comment]
I haven't read into GICv3 100%, but from what I've gathered so far are interrupts for the other world (n-sec or secure depending on current state) delivered as FIQ. For OP-TEE this means that the IRQ and FIQ handlers should be more or less swapped for GICv3. I would prefer if the solution is somewhat dynamic as we're likely to probe GIC version at some point, at least for QEMU.

There's probably something for the OP-TEE Dispatcher in ARM-TF to change also, at least how we update SCR.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered and there hasn't been any activity for almost two months. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
