### ISSUE TITLE
why do we have to disable exceptions during the cpu_spin_lock and cpu_spin_unlock ?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#986]
I get this restrictions from the document/optee_design.md, but i can‘t quite understand, can anyone help to explain?

**Comment by d3zd3z** [comment]
A spin lock works kind of like the name suggests, if the resource is in use by another CPU, it will "spin" continuously trying to read the lock until it is available.

This means they should only be held for short, and predictable times. If interrupts are enabled while a lock is held, the CPU could spend time doing something else, possibly taking a long time. During that long time, any other CPUs that need the lock will just be stuck spinning waiting for the resource.

Depending on the code, another thread could also get scheduled, and if it tried to get the same spinlock, the system would deadlock.

The spinlocks should only be used when interrupts are already masked, and the code just needs to prevent concurrent access by the other CPUs.

**Comment by prime-zeng** [comment]
So i think this is a should, not a must, right?   The reason is that REE-interrupts may cause a schedule in the REE side, it will take a long time, but when a FIQ in TEE side happens , it will not cause a schedule. it is more accurate only to disable REE-interrupts instead of all exceptions?

**Comment by jenswi-linaro** [comment]
No, all interrupts should be disabled to minimize the time the spinlock is held if nothing else.

**Comment by prime-zeng** [comment]
So why don't named as spin_lock_irq_save  and spin_lock_irq_restore?  More suitable then the current functions.

**Comment by jenswi-linaro** [comment]
The current name of the functions are due to legacy reasons. To me it looks misleading to have irq in the name of the functions as they have nothing to do with irq, even if they indirectly have some requirements on irq and other asynchronous exceptions.

**Comment by prime-zeng** [comment]
we can disable irq and asynchronous exceptions inside the functions and then rename.

**Comment by jenswi-linaro** [comment]
I don't see much to gain by this. These functions are low level functions which are only used when a normal mutex can't be used. At some places are the exceptions already disabled so there it would just be overhead to disable once again.

Then there's also the problem of where the old exception status should be saved, currently it's saved on the stack as we disable exceptions separately.

Adding an assert in the functions that the proper exceptions already are disabled could be useful though.

**Comment by d3zd3z** [comment]
spin_lock and spin_lock_irq_save are different functions, and you wouldn't want to just replace them. Sometimes it is useful to both mask interrupts and spinlock, and for those cases, the full operation makes sense. But, if interrupts are already masked, the plain spinlock is needed.

**Comment by prime-zeng** [comment]
Agree, from the spin_lock user side of view, i 'd rather provide both spin_lock and spin_lock_irq_save, and users determine which to use. Why i raise this question is that our guys will easily abuse the spin_lock, sometimes they forget to  mask the exceptions but it works well(so i think this is not a must, if it's a must , the function should take care of it).

**Comment by d3zd3z** [comment]
I would definitely say that spin_lock **must** be used with interrupts masked. Even if it appears to work there could easily be scheduling problems that are very rare. It does make sense for a debug mode to have spin_lock check the IRQ mask and fail if it isn't set.

**Comment by prime-zeng** [comment]
OK,  i think it's clear for the question, close it.
