### ISSUE TITLE
Compile Lua as TA

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#988]
This is a pretty general question. I was wondering if anyone has had experience getting Lua source code to compile into a TA. Off the top of my mind, I don't remember optee-os having anything such as setjmp.h. Would the work around in such cases be to drop the missing libc functions in myself?

**Comment by jforissier** [comment]
OP-TEE *does* have `setjmp.h`: see https://github.com/OP-TEE/optee_os/blob/master/lib/libutils/isoc/include/setjmp.h. It was added by commit [0c81fcd6798b](https://github.com/OP-TEE/optee_os/commit/0c81fcd6798bb5fa251f130ec7657e128c17cc46) ("libutil: add setjmp/longjmp").

Still, I can't guarantee that Lua builds with OP-TEE's libc (`libutils.a`). I have never tried myself. Quite possibly, our libc may be lacking some other functions.

**Comment by peterfeifanchen** [comment]
Okay I will give it a try. One more thing, in TA's sub.mk, is there a faster way of telling it to add every *.c file in the folder? 

something like srcs-y += $(FOLDER)/*.c?

**Comment by jforissier** [comment]
`srcs-y += $(wildcard $(FOLDER)/*.c)` should work I suppose.

**Comment by d3zd3z** [comment]
You might want to have a look at [Embedded Lua](https://github.com/elua/elua). Although not directly applicable, it should help to see what they had to do to be able to run Lua on a microcontroller.

**Comment by peterfeifanchen** [comment]
I took a look at elua. I don't think I need something nearly as complicated. My main problem right now are 

1) missing libc (I am taking out functionality from Lua if I don't need it and writing my own if its simple enough like abs(), isdigit(), strspn() etc.)
2) comparing floating point warnings (e.g. == && !=). Although [here](http://stackoverflow.com/questions/11421756/weverything-yielding-comparing-floating-point-with-or-is-unsafe) seems to say I do not need to worry about that
3) cast increases required alignment of target type [-Wcast-align] warnings due:
      `#define cast(t, exp)  ((t)(exp))`

So far for 1), I am moving along and haven't encountered anything that I can't fix yet...albeit I am only on 4/30 files (I removed lua, luac and a bunch of standard libraries). But the thing I am uncertain about is 3), I think Lua got away with it due to x86, but on ARM, I am not sure what happens when you make unaligned accesses. I googled this and ARM page [here](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka15414.html) says that I can use __pack to fix this. But this cast is literally sprayed everywhere in Lua source code. Plus if I make one value __pack, whenever it gets assigned or assigned to, that value has to be __pack (at least that is my understanding). I don't see how elua got around this...as they have the exact same source code here calling the cast macro. 

Perhaps is there a flag I can give the cross compiler to just declare every struct, variable as __pack. I am okay with poorer performance if I don't have to manually go change the attribute of every Lua variable ever declared.

**Comment by jenswi-linaro** [comment]
Perhaps the problem with the casts is that the pointer is passed via an unfortunate type instead of `void *`.

**Comment by peterfeifanchen** [comment]
hmm. Maybe. There are alot of these casts though...buried beneath layers of macros. I'll post back here once I know if its a problem.

But on the porting against OP-TEE libc-side. I am quite behind for my optee-os repo. I am developing against [830a08e4946821202fb2377b4afeee03e2689500](https://github.com/OP-TEE/optee_os/commit/830a08e4946821202fb2377b4afeee03e2689500) on QEMU 32-bit build. If I want setjmp.h, do I just need to pull setjmp_a32.S, setjmp_a64.S, and setjump.h? There is alot of #if defined in there...

Eventually I would port my code to QEMU64. But right now I just want to get the lua interpreter working in the TA first.

**Comment by jenswi-linaro** [comment]
It could just work to take those files. Note that the latest OP-TEE also runs on QEMU32.

**Comment by peterfeifanchen** [comment]
Okay. I got it to compile. You were right about the void*. I fixed a few macros and the misalign warnings are gone. Now my x86 Lua and ARM TrustZone Lua only throw the same warnings (e.g., suggest-attribute=noreturn and -Wfloat-equal). I am going to assume since on x86, the -Wfloat-equal didn't result in runtime errors...that it won't on ARM also. The other warning shouldn't do anything.

The missing libc functions after I stripped it down are follows (string.h, cytpe.h and math.h):
strspn(), strchr(), strcpy(), strtod(), strpbrk(), strcoll(), isalnum(), isdigit(), toupper(), tolower(), isalpha(), iscntrl(), isgraph(), islower(), ispunct(), isspace(), isupper(), isxdigit(), abs(), rand(), floor(), pow(), fmod(), frexp(), abort()

It seems most of these can be replicated...although I see that abort() and rand() exists in libutils and libutee for OPTEE-OS, however I can't seem to find the header files that goes with them to include into lua. Any hints on where they may be?

Thanks! Hopefully, my lua interpreter still works with all the stuff I stripped out.

**Comment by jforissier** [comment]
Your list of missing libc functions rings a bell ;) Check this commit: https://github.com/jforissier/optee_os/commit/9c9a90532688c71eced3cc87df717a620af95b28

Most functions come from the 'newlib' C library, except for the simple functions in `ctype.c` which I re-implemented myself, and also `atoi()` which I copied from PDCLib as mentioned in the comments. In any case I think newlib is a good reference for any other function you may need.

**Comment by peterfeifanchen** [comment]
I am having trouble finding an implementation that I can port for some of the math.h functions: ceil, floor, pow, fmod, frexp. I tried using the __built_in functions of the ARM toolchain. 

When I do my own cross compile, it works fine. But when I try to build the trusted application, it says undefined reference to floorl, ceill, powl, fmodl, frexpl. 

I am calling the functions as e.g. __builtin_powl() etc., It seems the trusted application build has somehow disabled builtin functions. Is there a way to re-enable it?

**Comment by jenswi-linaro** [comment]
I don't know what's disabling the builtins. You can always check compiler arguments by supplying V=1 when compiling, or check .filename.o.cmd in the out directory.

**Comment by peterfeifanchen** [comment]
Okay ignore my comment above. It was a bit strange, turns out I was including -lm all the time in our reference code. There were no builtin functions. I just reimplemented the libc by looking at uclibc. Lua works as part of TA now. Thanks for all your help!
