### ISSUE TITLE
Should we fix the default TAPersistentTime.protectionLevel ?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#991]
The default value is 100 now, but it depends on the _time_source, can we get it from the _timer_source and treat it the same as systemTime?

**Comment by jforissier** [comment]
Persistent time has to survive across reboots and there's currently nothing in OP-TEE to do that. So I think `gpd.tee.TAPersistentTime.protectionLevel` cannot be higher than `100` on any of the platforms we support by default. If you implement time persistence for your platform, then you can consider implementing a callback like we have done for `gpd.tee.systemTime.protectionLevel`.

**Comment by prime-zeng** [comment]
Persistent is not implemented in OP-TEE now, but the protectionLevel should depend on it's clocksource which comes from the REE or TEE side. so i think  implementation is one thing while the protectionLevel is another.

**Comment by jforissier** [comment]
protectionLevel depends on the time source (REE vs. TEE), but also on the persistent storage.
> 100: Persistent time based on an REE-controlled real-time clock and on the TEE Trusted Storage
for the storage of origins. [...]
> 1000: Persistent time based on a TEE-controlled real-time clock and the TEE Trusted Storage. [...]

Actually sue to the missing use of Trusted Storage, we comply neither with 100 nor 1000 :( And you are right that the only difference between 100 and 1000 is the time source.

Are you proposing the following? (untested):
```diff
diff --git a/core/tee/tee_svc.c b/core/tee/tee_svc.c
index f2d573b..f3daa47 100644
--- a/core/tee/tee_svc.c
+++ b/core/tee/tee_svc.c
@@ -258,8 +258,7 @@ const struct tee_props tee_propset_tee[] = {
        {
                .name = "gpd.tee.TAPersistentTime.protectionLevel",
                .prop_type = USER_TA_PROP_TYPE_U32,
-               .data = &ta_time_prot_lvl,
-               .len = sizeof(ta_time_prot_lvl)
+               .get_prop_func = get_prop_tee_sys_time_prot_level
        },
        {
                .name = "gpd.tee.cryptography.ecc",
```

**Comment by prime-zeng** [comment]
No, i am not proposing the PR, i' d rather to have it fixed together with the persistent storage of persistent time.

**Comment by d3zd3z** [comment]
What about an attack that removes the encrypted persistent storage file? Persistent storage is robust against decoding, it isn't robust against being removed.

**Comment by prime-zeng** [comment]
So maybe need rpmb to store the persistent TA time.

**Comment by jbech-linaro** [comment]
RPMB is the best we have for the moment when it comes to secure and persistent storage. @prime-zeng , would you mind provide a patch or send an implementation proposal?

**Comment by prime-zeng** [comment]
@jbech-linaro , I need sometime to think of the implementation.
