### ISSUE TITLE
OPTEE-OS Schedules multiple TAs

### ISSUE THREAD

**Issue by HelloCoderZ** [OP-TEE/optee_os#997]
Hi everyone,

I'm using Juno r1 board with OpenEmbedded system which is built as the instruction [https://community.arm.com/docs/DOC-10804](url).

I'm wondering is there any document describes that how does the Secure OS schedule multiple TAs? And how does a core schedule TA with normal application if they are assigned to the same core?

If there is no document, could you please give me some hint like where is the source code working for these purposes so I could check by myself? I'm looking for the whole project but I don't find any related code yet except the scheduler for normal OS.

Thank you very much.

J.Zhou

**Comment by jenswi-linaro** [comment]
Hi,

OP-TEE doesn't have a scheduler, it relies on normal world for scheduling. Rescheduling is something that typically could happen during an IRQ delivery to normal world. Most of this stuff hand handled in `core/arch/arm/kernel/thread*`.

Regards,
Jens

**Comment by HelloCoderZ** [comment]
@jamescfkung okay, I'll check this route and let you know if I have any future question, thank you.

**Comment by jackzhang190105** [comment]
hi Jens:
           Is there any plan to add a scheduler in op-tee ? 

thanks!
jack.zhang

**Comment by prime-zeng** [comment]
I think the op-tee is more like a library called by the REE os, and support multi-core, so i don't see the need for scheduler?

**Comment by jbech-linaro** [comment]
@jackzhang190105 prime-zeng is right, OP-TEE is designed to be scheduled by the Linux kernel and we have no plans to change that design.
