### ISSUE TITLE
Loading Kernel Module for Secure OS

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#998]
Hello,

I'm currently trying to get the CPU information in the Secure OS like which core is running TA and I was told that getting this information needs kernel privilege.

In this case, I want to know for the current optee_os can I load LKM? 
So far I only could see the output of TA by serial port and I have no idea about interacting with optee_os.

Any suggestions are welcome.

**Comment by jenswi-linaro** [comment]
We don't support LKMs in OP-TEE, whatever you need to run in kernel mode has to be statically linked into the binary.

I don't understand the question. CPU info from the CPU you're currently executing the code that wants to know? Unless it's a single CPU system it's not that easy as a TA can be rescheduled to another CPU at any time.

**Comment by SimonWan** [comment]
@jenswi-linaro thank you for the answer about LKMs.

One example of my question is that when a TA is running, I want it to output on which core it is running. This is easy for normal application by using function like `getcpu` but I don't know how to do this in secure OS.

**Comment by jenswi-linaro** [comment]
We have no support for doing that from a TA. I guess it can be added for an important use case.

**Comment by SimonWan** [comment]
@jenswi-linaro okay, I can try to see if there is anything I can do to get information.

By the way, I also have another question regarding to this issue. 
Currently I'm using the `top` command in the normal world to observe the cpu usage. And it looks like when one core's `sy`(system cpu time) value becomes large, then this core is running the TA.

Do you think this method make sense?

**Comment by jforissier** [comment]
Time spent in the TA is accounted for in system time, because the secure world is invoked from within the driver with no special handling of time statistics. So until the syscall returns, CPU ticks are considered spent in the driver, hence system time.

**Comment by SimonWan** [comment]
@jforissier Thank you for confirming my guess.
