### ISSUE TITLE
Secure OS Debugging Issue

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#999]
Hi there,

I'm currently trying to write a scheduler for optee_os to schedule TAs better. To do this, I think I would modify part of your code and re-build the system. 

However, I'm wondering how do you conduct the debugging for the secure OS before when you revised the code? 
So far I only know that serial port could output some secure OS messages but I think this method is restricted. And I'm trying to figure out some way to interact with the OS like pausing the system.

Any suggestions are welcome.

Thank you.

**Comment by jenswi-linaro** [comment]
I usually debug on QEMU or FVP Base model. If a single cpu system is enough I'd use QEMU virt v7 else QEMU virt v8. A limitation of the QEMU debugger is that you can't read system registers directly with the debugger.

What's the problem with the current TA scheduling?
